### ISSUE TITLE
import of '!text' file via `plugin-text` module generates error

### ISSUE THREAD

**Issue by mcalthrop** [facebook/flow#1002]
We are using the `plugin-text` module to allow importing of text as follows:

``` js
import template from './template.html!text';
```

However, this is producing the following error when running `flow` against the code:

```
  4: import template from './template.html!text';
                          ^^^^^^^^^^^^^^^^^^^^^^ ./template.html!text. Required module not found
```

Any suggestions on how to handle this?

One solution would be to switch the `flow` checking off for a code block (using comments, like you can in jshint/jslint etc) – I searched the [flowtype docs](http://flowtype.org/docs/), but couldn't find that capability there (did I miss something?!).

**Comment by agentcooper** [comment]
I think you can create a new file, say `flow_text.js` with contents like
```js
// @flow
module.exports = 'some string';
```
and redirect modules ending with `!text` to this file using [`name_mapper`](http://flowtype.org/docs/advanced-configuration.html#options).

**Comment by mcalthrop** [comment]
Thanks @agentcooper.

In my case, I ended up using the `templateUrl` property instead, as it is being used for an Angular component's template.

**Comment by acusti** [comment]
For anyone else running into this, see specific solutions in [MoOx’s gist](https://gist.github.com/MoOx/12ac2bee8d876a5c1fe1593e4815895d).

Also, pretty sure this issue can be closed.
