### ISSUE TITLE
Property cannot be accessed on possibly null value

### ISSUE THREAD

**Issue by josebalius** [facebook/flow#1004]
A team member of mine brought this case to my attention:

```
const nullThing = null;
const notNull = (nullThing !== null);
const breaksFlow = notNull && (nullThing.arbitraryAttribute === 1);
```

Has this already been reported?

**Comment by samwgoldman** [comment]
Yeah, I think this is the same as #998 which came up yesterday.

**Comment by calebmer** [comment]
Duplicate of https://github.com/facebook/flow/issues/998
