### ISSUE TITLE
Dynamic type check does not refine object property after a function call

### ISSUE THREAD

**Issue by DanielHeath** [facebook/flow#1005]
I have the following code on 0.18.1:
```
eventValue(event: Event): string {
    if (event.target instanceof HTMLInputElement) {
        console.log("HI")
        return ltrim(event.target.value);
    }
    return "";
}
```
It fails typechecking with: `property value not found in EventTarget`.

If I remove the `console.log("HI");` line, flow thinks this is fine.

**Comment by samwgoldman** [comment]
This behavior is [documented on the Web site](http://flowtype.org/docs/dynamic-type-tests.html#caveats). Does the workaround mentioned in the docs help you get around this?

**Comment by DanielHeath** [comment]
Ahh, I understand now. Comes up infrequently enough that it's hard to remember. Thanks so much for the help :)

**Comment by jeffmo** [comment]
Just to throw in some hope: @bhosmer has a pending change that should make this much less prevalent after the next release (0.19).

(namely, it records which variables are written to by a given function and only invalidates refinements on variables that are actually modified by a function call)

**Comment by samwgoldman** [comment]
Looking forward to that change! In this case, we'd need some way to communicate r/w sets through function declarations in lib files, s.t. `console.log` had empty r/w sets.
