### ISSUE TITLE
Misattributed error with intersection type

### ISSUE THREAD

**Issue by danvk** [facebook/flow#1007]
I ran across an extremely misleading error from Flow today:

``` javascript
/** @flow */
var _ = require('underscore');
var o = {a: 1, b: 2, c: 3};
var cs = _.map(o, x => x.count);  // this should be x => x, not x => x.count
```

Flow reports this error:

```
$ flow status
foo.js:7
  7: var cs = _.map(o, x => x.count);
              ^^^^^^^^^^^^^^^^^^^^^^ call of method `map`. Function cannot be called on
  5:   declare function map<T, U>(a: T[], iteratee: (val: T, n?: number)=>U): U[];
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ intersection type. See: lib/underscore.js:5

Found 1 error
```

Changing the offending function body to `x => x` makes the error go away. The error _should_ say something about how the values in `o` don't have a `count` property. `_.map` can definitely be called on objects (see declaration below).

This feels much like the error @samwgoldman and I [discussed](https://github.com/facebook/flow/pull/837#issuecomment-147611103) in PR #837.

Here are the other files in my project:

``` javascript
// lib/underscore.js
declare module "underscore" {
  declare function map<T, U>(a: T[], iteratee: (val: T, n?: number)=>U): U[];
  declare function map<K, T, U>(a: {[key:K]: T}, iteratee: (val: T, k?: K)=>U): U[];
}
```

```
// .flowconfig
[ignore]
.*node_modules/flow-bin.*
.*node_modules/underscore/.*

[libs]
lib
```

This is on Flow 0.18.1:

```
$ flow version
Flow, a static type checker for JavaScript, version 0.18.1
```

**Comment by rohanpai** [comment]
Did you ever find a solution to this? I think I'm experiencing a similar issue.

**Comment by SamChou19815** [comment]
We now give better error messages.
