### ISSUE TITLE
Cannot dynamically create an object of union type

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1014]
Within the conditional `s` can be either "a" or "b", which means it should be possible to create variable `z` of a union type as declared. However Flow doesn't allow this...
```
// @flow
type A = {mode:"a", foo: string};
type B = {mode:"b", foo: string};
type Z = A|B;

var s: ?string;
// ...
if (s === "a" || s === "b") {
  var z: Z = {mode: s, foo: "ok"}; // Flow error here
}
```

**Comment by samwgoldman** [comment]
This is pretty similar to #965

**Comment by pasha-mf** [comment]
On a further thought, I believe this to be still a different issue. Here's a smaller test case:
```
type AB1 = {mode: "a"} | {mode: "b"};
type AB2 = {mode: "a"|"b"};
function test(x: AB1, y: AB2) {
  (x: AB2);
  (y: AB1);
}
```
Types `AB1` and `AB2` are conceptually equivalent, however Flow doesn't recognize that.
In the original example, variable `s` should have been refined to `"a"|"b"` within the if statement (currently it doesn't, but that's issue #965). However even after such a refinement the object would have failed to instantiate because `Z` type is not equivalent to `{mode: "a"|"b", foo: string}`.

**Comment by pasha-mf** [comment]
Here's a test case similar to above, but it shows an interesting quirk. Look at the definition of `x`: it is initialized from a ternary that has both sides identical: `mode==="a"? {mode} : {mode}`. It is however not possible to simplify this expression to just `{mode}` -- Flow doesn't accept that... 
```
type AB = {mode: "a"} | {mode: "b"};
function test(mode: "a" | "b") {
  var x: AB = mode === "a"? {mode} : {mode}; // this works
  var y: AB = {mode}; // Flow error
}
```

**Comment by avikchaudhuri** [comment]
See explanation on #1194. It is incorrect to say that `AB1` and `AB2` are conceptually equivalent, because of invariance of property types. When we have read-only properties, we can do more.
