### ISSUE TITLE
Cannot access DOM-related properties on nodes found with document.getElements* 

### ISSUE THREAD

**Issue by snicky** [facebook/flow#102]
```javascript
var nodeList = document.getElementsByTagName('p');
for (var i = 0; i < nodeList.length; i++) {
  nodeList[i].style.backgroundColor = 'red';
}

var nodeList = document.getElementsByClassName('block');
for (var i = 0; i < nodeList.length; i++) {
  nodeList[i].style.backgroundColor = 'red';
}

var e = document.getElementById('container');
e.style.backgroundColor = 'red';
```

The first two raise: "property style - Property not found in ...lib/dom.js", the last one is okay. Both `getElements*` methods return `NodeList`s which are lists of `Node`s, not `HTMLElement`s. How to work around this issue?

Also, is it possible to map `window` as a global namespace?

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
