### ISSUE TITLE
Does not show error when reaching invalid fields of string-based union types.

### ISSUE THREAD

**Issue by zsszatmari** [facebook/flow#1020]
Hi!

An example would clarify this better than I could describe the problem:

``` javascript
/* @flow */
"use strict";

/*::
type Action = {type: 'FETCH_COW', bells: number} |
              {type: 'FETCH_ELEPHANT', peanuts: number};
*/

function handleAction(action /*: Action */)
{
    switch(action.type) {
        case 'FETCH_COW':
            console.log('bells: ' + action.bells);
            break;
        case 'GO_RUNNING':
            // this code is clearly unreachable, should print error
            console.log('go-go-go');
            break;
        case 'FETCH_ELEFANTtypo':
            // the real pain: Action union type does not have these fields, either because there was no such
            // field in the first place...:
            console.log('penuts?: ' + action.penuts);
            // ...or because it does not apply:
            console.log('bells?: ' + action.bells);
            break;
    }
}


```

Thanks for looking into this!
Using 0.18.1.

**Comment by alexeyraspopov** [comment]
This is still an issue for `v0.20.1`

```javascript
/* @flow */

type CounterActionType = 'INCREMENT' | 'DECREMENT';
type CounterAction = { type: CounterActionType, value: number };

function reducer(state: number, action: CounterAction): number {
	switch (action.type) {
	case 'INCRT':
		return state + action.value;
	case 'DECREMENT':
		return state - action.value;
	default:
		return state;
	}
}

const action: CounterAction = { type: 'INCREMENT', value: 1 };
const state = reducer(0, action);
```

**Comment by alexeyraspopov** [comment]
This issue is still reproducible in 0.22.1

**Comment by samwgoldman** [comment]
Thanks—this issue has come up a number of times in the past. We're definitely interested in adding this kind of check in the future.

**Comment by alexeyraspopov** [comment]
I would probably try to fix it if can point me in right direction of what I
should check first.

**Comment by TrySound** [comment]
This is fixed 💯 
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoARAVwM4FMzYAuATgJYDGh6A3KqqAFwOqECeADvgIKWlwB2YALxgA3m04MwAcgBiAUQAqAYQASAfWUB5AOrSANGABGuGDGxT+mALYniAXzAAfVGDfuPH8R1xS5StXV5ABl5AAVVLgA5RQMwTgBDK0ILMCtbXAdaFDooTH5eATAACySAExhcHkI+fgAKBMLBRjBq2uRgAEpUUVd3bARSQnJihqaAOglcTrE+zzByBLwZBRUNbT1mefnyAWw4SvH4AHM66RMzVOkwAGowRpqBcYvzTtptzyNiXASAa3ftotltIAOJadQAJQAqlEogBJKIg6RbD7uYDAMCEYqkbALOBlfA4haVBLEGCsMD5b6NUpGSqGbDFOCYGBleJkfiEMCZYhwYhzVG7fj7Q4nM7HOAAWgl0rg0jeAo+Xx+-0V7iB+H8ayCoVk0UUEjlKNRYHRmOK+GpMHiCVI-CkbSK+XaUzAZTguFx-DgXNKADd8FjPfgoKRTGVsIZcEMLcRjLhFjhA7H8Aglmk4ARMCM1fMzaHw2A7eaQ6RiER4jBGrhxrXjYK9gca2LpJxktgAPx+W73CZtzApBUmtxm2vjPnxxPLIZuj1en33djscn1j5CkXNuCnc6mcxdmQ9h61Z677BD4fKv4Atz2VD2IA
