### ISSUE TITLE
Standard Formatting

### ISSUE THREAD

**Issue by thomas-jeepe** [facebook/flow#1022]
Just wondering, does Facebook have a formatter with support for flow or have style guidelines on flow typing? My formatter breaks with flow and esparse reads js but doesn't support flow parsing.

**Comment by DaleJefferson** [comment]
I have the same problem, all of the JavaScript code formatting tools I have tried so not support Flow annotations.

I was hoping Nuclide's format-js would do what I wanted but I can't see how to set the output style. https://github.com/facebook/nuclide/tree/master/pkg/nuclide/format-js

**Comment by DaleJefferson** [comment]
@thomas-jeepe esformatter-flow has just been release which adds flow support to esformatter. https://github.com/millermedeiros/esformatter-flow

**Comment by thomas-jeepe** [comment]
Awesome!

Thanks for letting me know :)

**Comment by samwgoldman** [comment]
Awesome! Is this issue resolved?

**Comment by DaleJefferson** [comment]
@samwgoldman Maybe we should add something to readme recommending esformatter-flow? @thomas-jeepe Otherwise this question has been answered so I think we can close.

**Comment by thomas-jeepe** [comment]
Yep @samwgoldman
