### ISSUE TITLE
Method call to parent causes error

### ISSUE THREAD

**Issue by majjoha** [facebook/flow#1023]
I am currently working a project where we use Flow alongside Flux, and React, and I noticed that method calls to the parent causes the following error:

```
src/app.js:13
 13:     return super().filter(state => state.name)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `filter`. Method cannot be called on possibly undefined value
 13:     return super().filter(state => state.name)
                ^^^^^^^ undefined
```

This happens if you have a structure of this kind:

```
/* @flow */
class MapStore {
  getState() {
    return [{ name: 'state' }]
  }
}

class OrderedMapStore extends MapStore {
}

class BarStore extends OrderedMapStore {
  getState() {
    return super().filter(state => state.name)
  }
}

let bs = new BarStore()
console.log(bs.getState())
```

If you change `getState()` in `BarStore` to be `return super.getState().filter(state => state.name)`, Flow returns 0 errors. Both approaches correctly returns `[ { name: 'state' } ]`, though. Is it an error that Flow complains over `super()`, or is this by design?

**Comment by jeffmo** [comment]
In JS classes, `super()` can only occur in constructors and can only only refer to a construction call to the constructor. For methods, we only have `super.`.

So I think what you want here is `super.getState().filter(state => state.name)`

**Comment by majjoha** [comment]
Thanks for clarifying, @jeffmo.
