### ISSUE TITLE
Typed simple property access and assignment

### ISSUE THREAD

**Issue by sheerun** [facebook/flow#103]
Hello. I wonder if it's possible in some way to typecheck property reading and assignment, like so:

```es6
// @flow

class Model {
  name: string;
  age: number;

  set(key: string, value: any) {
    this[key] = value;
  }

  get(key: string): any {
    return this[key];
  }
}

var model = new Model();
model.set('name', 'Smith');
model.set('age', 42);
```

Note that `"name"` and `"age"` keys accessed as passed as strings. No advanced functions.

For now I'm getting "assignment of computed property/element. Indexable signature not found in".

**Comment by bakesteve** [comment]
Think I'm hitting the same issue, which boils down to indexable properties on class definitions.

I've tried simplifying my example down, but hopefully the intent is there.
I tried telling flow this class extends an Array of string: string, but no joy
Did manage to get past the error by the typed `var that = this` but would really rather not have to resort to that as it feels fairly hacky..
Is this something planned in? or is it a fairly significant feature?
```
class Mappable extends Array<{ [key:string]: string}> 
{
  Value:string;
  Id:number;

  constructor(data: Array<{ ItemId: string; Value: string }>){
    this.Value = '';
    if(data){
      data.forEach(item => {
        //I'd LIKE  to just set this as a map:
        this[item.ItemId] = item.Value; //throws a Indexable signature not found
        //I can coerce it - but feels clunky..
        var that: {[key:string]: string } = this;
        that[item.ItemId] = item.Value;
      });
    }
  }
}
```

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by samwgoldman** [comment]
I separated out the indexable signature on classes into #1323.

Regarding a type-safe `set` method, or similar, I'm hoping to explore some stuff like this in the context of Immutable.js.

For the specific case above, where the set of keys is known, Avik's recommendation to use an overloaded function signature (an intersection of function types) is exactly correct.
