### ISSUE TITLE
Should not function handle all types from the union it accepts ?

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1033]
Here is my code:

```js
/* @flow */

export type Foo = {type: "Foo"}
export type Bar = {type: "Bar"}
export type Action
  = Foo
  | Bar

export type update <model> = (model:model, action:Action) => model
export const $update:update = (model, action) => {
  if (action.type === "Foo") {
    return model
  }
}
```

I would expect code error to fail given that if passed action is of `Bar` type return value will be `undefined` , instead flow finds no errors.

**Comment by Gozala** [comment]
It seems that issue is related to `:update` type annotation, as inlining type annotations does produce errors. Although I do find behavior with inlined type annotations also surprising (see #1034)

**Comment by samwgoldman** [comment]
This is the same issue as #1035 --- `$update` is typed as `update<any>`, and `void` is a valid `any`.
