### ISSUE TITLE
Error location is sometimes wrong when union types are involved

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1039]
Consider the following test suite:

## test.js ##
```
/* @flow */

export type FooBar = Foo | Bar | Baz | Foz;
type Foo = {op: "foo"; value: Array<FooBar>; };
type Bar = {op: "bar"; value: Array<FooBar>; };
type Baz = {op: "baz"; value: FooBar; };
type Foz = {op: "foz"; value: string; };
```

## test2.js ##
```
/* @flow */
import {FooBar} from "./test.js";

function test(s: FooBar) {
  if (s.op === "foo" || s.op === "bar")
    s.value.forEach(v => test(v));
}
```

When running a flow check, this setup will produce the following error message:
```
test.js:4
  4: type Foo = {op: "foo"; value: Array<FooBar>; };
                                   ^^^^^^^^^^^^^ array type. This type is incompatible with
  6: type Baz = {op: "baz"; value: FooBar; };
                                   ^^^^^^ union type

test.js:6
  6: type Baz = {op: "baz"; value: FooBar; };
                                   ^^^^^^ object type. This type is incompatible with
  7: type Foz = {op: "foz"; value: string; };
                                   ^^^^^^ string

test.js:7
  7: type Foz = {op: "foz"; value: string; };
                                   ^^^^^^ string. This type is incompatible with
  6: type Baz = {op: "baz"; value: FooBar; };
                                   ^^^^^^ union type
```

So as you can see, there are several issues here:
1. All errors are reported in file `test.js`, even though they occur because of line 6 in file `test2.js`. This is problematic, especially in a large codebase, because it's very hard to figure out where the error actually occurs.
2. Too many errors are reported. In my actual codebase "FooBar" is an arithmetic expression with a dozen or so sub-clauses, and a single line of code produces 34 error messages.
3. There should have been no errors in the first place: in function `test()` the if-condition should have refined `s` to `Foo|Bar`, both having `value` field of type `Array<FooBar>`. Thus it should be safe to iterate such an array and call `test()` on each element.
4. When I run `flow dump-types test.js` the reported type is `test.js:3:8-43: [type: any | {op: 'bar', value: Array<any>,} | {op: 'baz', value: any,} | {op: 'foz', value: string,}]`. I have no idea what `any`s do there, maybe it's just a display issue...

**Comment by samwgoldman** [comment]
The point about error messages is well taken. I don't have a solution for that, but this is helpful.

Regarding the fact that this code should not have any errors—you're correct. The reason you are seeing errors is the same issues as #582. If you split the conditional like so, there is no error:

```javascript
function test(s: FooBar): void {
  if (s.op === "foo") {
    s.value.forEach(v => test(v));
  } else if (s.op === "bar") {
    s.value.forEach(v => test(v));
  }
}
```

There is absolutely an issue here, and a solution to #582 should also fix it here. Hopefully the knowledge of this bug will help you come up with a workaround until a fix lands.

All the error message stuff is legit and separate.
