### ISSUE TITLE
Not supplying polymorphic parameter should not be equivalent of supplying `any` 

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1044]
Here is an example code:

```js
/* @flow */

type Map <T> = (x:T) => T

const change:Map = (x) => null

change("Hello").substr(5)
```

Flow does not error here that is because it understands typeof `change` as:

```js
(x:any) => any
```

Which I would argue is an unintuitive and probably worst possible behavior as above example illustrates. It would make much more sense to treat type of change exactly as it was typed:

```js
<T> (x:T) => T
```

As unlike any this clearly carries important detail that was encoded in the type signature, which is it's argument and return value types are of a same (non any) type.

**Comment by Gozala** [comment]
Another advantage of this would be that it would make following two type signatures equivalent, which I would eliminate question in regards when to use one options over the other:

```js
type foo <T> = () => T
type foo = <T> () => T
```

**Comment by samwgoldman** [comment]
@avikchaudhuri introduced this behavior in 1f3927032e4e3fd9dc253a5499dd0dbe84abde86, and it seems pretty intentional.

Before that commit, `const change:Map = ...` was the same as writing `const change:Map<*>` today. That is, you can use an explicit existential to get the old behavior. Does that help?

Even with the old behavior, I do not agree with the equivalence you're drawing. See the following code:

```javascript
/* @flow */

type A<T> = (x:T) => T
type B = <T>(x:T) => T;

const a: A<*> = x => x;
const b: B = <T>(x: T): T => x;

var a0: number = a(0);  // error
var a1: string = a(""); // error

var b0: number = b(0);
var b1: string = b(""); // ok
```

For `a: A`, we accumulate types into a single type variable. For `b: B`, each invocation has a separate type variable. Indeed, `B` is the type of `<T>(x: T) => T`. `A` is a similar, but different type.

**Comment by Gozala** [comment]
> @avikchaudhuri introduced this behavior in 1f39270, and it seems pretty intentional.

> Before that commit, const change:Map = ... was the same as writing const change:Map<*> today. That is, you can use an explicit existential to get the old behavior. Does that help?

Unfortunately I do not know what `*` means neither I can find a documentation for it on the http://flowtype.org but given the examples you provide it is not what I propose. In a way it's a good thing, because I can see why previous behavior wash changed although I would still argue that current behavior is not good & would suggest to consider proposed behavior instead.

> Even with the old behavior, I do not agree with the equivalence you're drawing. See the following code:

That makes sense, because I do not propose previous behavior, instead I propose behavior that would have that equivalence I was trying to draw.

> For a: A, we accumulate types into a single type variable. For b: B, each invocation has a separate type variable. Indeed, B is the type of <T>(x: T): T => x. A is a similar, but different type.

I think this explanation is very specific to implementation details, while I was suggesting to consider different behavior that may or may not fit into current implementation strategy.



Also please consider #1045 which I believe highlight another flaw of the current behavior, I would not expect anything even explicitly passed `any` for polymorphic parameter to elevate explicitly define bonds.

**Comment by AgentME** [comment]
Here's another good discussion on the current behavior: https://github.com/facebook/flow/issues/542

**Comment by samwgoldman** [comment]
Nothing to do here. Things are working as designed. I think the default behavior is a bit unsavory myself, but there's a workaround if you need it, and we made it this way for a good reason, which is spelled out in the commit I linked to above.
