### ISSUE TITLE
Flow should never drop bounds defined on polymorphic type annotations

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1045]
Consider following example:

```js
/* @flow */

type Model = {x:number}
type Update <model:Model> = (state:model) => model

const inc:Update = ({x}) => ({x: x + 1})

inc(5)
```

I would expect type of `inc` to be exactly what code specified:

```js
<model:Model> (state:model) => model
``` 

And not what flow currently relaxes to:

```js
(state:any) => any
```

Just to be clear this is not the same issue as #1044 because, one can argue that no omitting a parameter should be treated as `any`, but event then I would argue that dropping explicitly coded bound `:Model` should not happen. In other words if omitted type parameter is treated as `any` I would still expect that type of the above `inc` would be:

```js
(state:Model) => Model
``` 

P.S.: It was first brought up this issue in #1035 but it assumed this was a bug, while here I propose to change a behavior.

**Comment by samwgoldman** [comment]
`any` is a subtype of the bound, and anything is a subtype of `any`. This is just how `any` works. The bound isn't dropped or lost; this is just `any` being `any`.

You're recommending we change a behavior in this issue, and #1044 is an issue that recommends exactly the same thing. How are these issues different, as you claim?
