### ISSUE TITLE
esproposal.class_instance_fields does not seem to work

### ISSUE THREAD

**Issue by torarnek** [facebook/flow#1049]
.flowconfig
```
[options]
esproposal.class_instance_fields=ignore
esproposal.class_static_fields=ignore
```

flow giving output:
```
src/main/javascript/common/upload/fileInput.js:18
 18:     handleClick = (e:Event) => {
         ^^^^^^^^^^^ Unexpected identifier
```

ignore and warn seem to give the same result.
Using version 0.18.1 on osx

**Comment by jeffmo** [comment]
Do you, by chance, have a field declaration just before this one that doesn't end in a semicolon?

(Field declarations have to end in semicolons to remain unambiguous)

**Comment by torarnek** [comment]
Yes indeed I had a field declaration just before without semicolon (as I thought they were optional). 

Thank you.
