### ISSUE TITLE
Add fetch API to the DOM interface definitions

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1052]
https://fetch.spec.whatwg.org

**Comment by Gozala** [comment]
I will submit a pull request with for this.

**Comment by trave7er** [comment]
any update on this?

**Comment by aackerman** [comment]
This looks done to me, https://github.com/facebook/flow/commit/3130f25751048d0354d4f39330d794993d69deec

**Comment by samwgoldman** [comment]
Thanks for noticing!
