### ISSUE TITLE
Phantom types

### ISSUE THREAD

**Issue by paulyoung** [facebook/flow#1056]
I was talking to @jeffmo on IRC about this and was asked to create an issue.

I have a project where I'm using some types purely as type constraints, or phantom types. This is currently available at https://github.com/paulyoung/tss.

In order to make sure these types can't be constructed I must do the following:

``` javascript
class _Foo {}; export type Foo = _Foo;
```

This way, even if someone does `import { Foo } from Bar` instead of `import type { Foo } from Baz`, `new Foo()` causes the error `Constructor cannot be called on type `Foo``.

However, this has the undesired result of the error for an incorrect type to read `This type is incompatible with _Foo`, rather than when simply doing `export class Foo {}` which yields `This type is incompatible with Foo`.

I'm also unsure how to create a declaration file that achieves the same behavior (or even if this is necessary, but it seemed to be the only way to use one flow-annotated project inside another).

I'd prefer some way of exporting an anonymous type, perhaps something like this:

``` javascript
export type Foo = class {};
export type Bar = class {};
```

Of course, this would require that `Foo` and `Bar` are considered to be different types.

If there are any other ways to achieve this currently, I'd love to know how.

Thanks!

**Comment by gabelevi** [comment]
I think the missing feature is opaque types. Currently, type aliases are transparent. If you have

  export type URIString= string;

Then anyone who imports `URIString` can use it interchangeably with `string`. This is great if you're using type aliases to avoid rewriting some complicated types, but it's not so great if you want to create new types that should be checked nominally and not structurally.

[Hack does this with the `newtype` keyword](http://docs.hhvm.com/manual/en/hack.typealiasing.php). Their opaque types are transparent within the file they're declared, which is nice for writing type constructors and eliminators. Though maybe we could do something clever with exports instead. Like what if you could write

```JavaScript
// URIString.js
type URIString = string;
export function encode(s: string): URIString {
  return encodeURI(s);
}
export function decode(s: URIString): string {
  return decodeURI(s);
}
export opaque type { URIString };

// Other module
import { encode, decode } from './URIString';
var encoded_string = encode('Hi there'); // No error
var decoded_string = decode(encoded_string); // No error

decide("Other string"); // Error: string ~> URIString
encode(encoded_string); // Error: URIString ~> string
```

If we had that, then you could create your phantom types as opaque. Then they would be checked nominally and the errors would reference them therefore by name.

Though now that I've written this, there's another feature which I'm not sure how it would fit in. With opaque types, it's nice sometimes to be able to specify a subtyping behavior. Like we might like to say that `URIString` is a subtype of `string` (so all `URIString`'s are `string`'s, but not all `string`'s are `URIString`'s). This isn't really what you need, but it's useful. [Hack has support for this too](http://docs.hhvm.com/manual/en/hack.typealiasing.opaquewithconstraints.php). So maybe it would be better to follow their syntax, which would mean something like

```JavaScript
// URIString.js
newtype URIString as string = string;
export function encode(s: string): URIString {
  return encodeURI(s);
}
export function decode(s: URIString): string {
  return decodeURI(s);
}
export type { URIString };

// Other module
import { encode, decode } from './URIString';
var encoded_string = encode('Hi there'); // No error
var decoded_string = decode(encoded_string); // No error

decide("Other string"); // Error: string ~> URIString
encode(encoded_string); // No error, since URIString is a subtype of string
```

**Comment by samwgoldman** [comment]
See some earlier discussion in #465. I recently hacked together an interface file for [testcheck](https://github.com/leebyron/testcheck-js) that [uses classes to simulate an opaque type](https://github.com/samwgoldman/testcheck-js/commit/3b79e91faf56c522ccf94644115971b425b1efe5#diff-549cdf89a8e1c8f89e650f9e5bdee3cfR58).

**Comment by paulyoung** [comment]
I believe I've stumbled upon a nicer way to do this while working around a limitation with the current support  for `export`.

```javascript
// @flow
// Properties.js

export class Margin {}
export class Padding {}
```

```javascript
// @flow
// index.js

// export * from "./Properties";
import * as Properties from "./Properties";
export type Margin = Properties.Margin;
export type Padding = Properties.Padding;
```

Using this approach `new Margin()` and `new Padding()` isn't valid, and `Margin` is incompatible with `Padding` as a type constraint.

**Comment by mhagmajer** [comment]
+1

**Comment by JenniferWang** [comment]
I really want this feature to distinguish `Int` and `Float` on client side.

**Comment by simprince** [comment]
+1 this is important to differentiate Int from Float. This avoids human errors where we forget to round float to int value and cause errors down the road.

**Comment by mhagmajer** [comment]
Also, it's something that Hack for PHP already supports. I hope this comes
around for JS as well soon...

**Comment by ckknight** [comment]
Perhaps a syntax like

```js
type URIString = $Opaque<string>;
```

would be useful before adding concrete keywords.

**Comment by mhagmajer** [comment]
The dollar sign is pretty crazy

**Comment by jbrown215** [comment]
Closing since opaque types went out in 0.51
docs here: https://flow.org/en/docs/types/opaque-types/
