### ISSUE TITLE
Missing type check for JSX inside const

### ISSUE THREAD

**Issue by majjoha** [facebook/flow#1061]
I've been facing an issue recently where JSX inside a `const` isn't properly type checked as expected.

```js
type TCounter = (props: {
  value: number
}) => ReactElement
const Counter: TCounter = ({ value }) => (
  <div>{ value }</div>
)

const SomeOtherComponent = () => (
  Counter({ value: '4' })
)

const SomeOtherComponent2 = () => (
  <Counter value='4' />
)
```

Here, `SomeOtherComponent` correctly tells me that there is an issue with the type of `value`, whereas `SomeOtherComponent2` incorrectly passes. Do I need some additional configuration to have Flow support this use case, is it a bug, or is this not supported by design?

**Comment by samwgoldman** [comment]
The issue here is that Flow doesn't currently support functional components in JSX. This is a new feature in React 0.14 and we simply haven't caught up with them yet. Closing this in favor of the more clearly described issue in #1081. Thanks!
