### ISSUE TITLE
Passing types between context

### ISSUE THREAD

**Issue by Radivarig** [facebook/flow#1071]
Hi, I'm using React and would like to define a type for the component's state.

By using [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck), the following is my workaround based on the observation that the type saved to a variable is a function that returns bool if the passed object is of the correct type.

```js
mixins: [ StateTypeMixin ]
, getInitialState() {
    type stateType = {
      stateNumVar: number;
    }
    this.stateTypeCheck = stateType    //converts the type to a function
    return this.typedState({
      stateNumVar: 3    //changing the type will throw exception
    })
  }
//call setTypedState instead of setState
```
```js
var StateTypeMixin = {
  setTypedState(s, cb) {
    return this.setState(this.typedState(s), cb)
  }
, typedState(s) {
    var newState = Object.assign({}, this.state, s)
    if (this.stateTypeCheck(newState)) return newState    //uses the function here
    else throw 'Type mismatch for state: ' +JSON.stringify(newState)
  }
}
```

Is there a better way to achieve this?
Thanks in advance

**Comment by jeffmo** [comment]
This seems like a question for babel-plugin-typecheck, not Flow (the two are not related at all). Maybe open an issue over on that GitHub repo?

**Comment by Radivarig** [comment]
I did [here](https://github.com/codemix/babel-plugin-typecheck/issues/46) and the conclusion is the mentioned workaround. I am asking if there is a way to pass the type differently from the Flow side? I'm aware of the `import/export type` but as I understand it is related to `require` and happens in compile-time as well.

**Comment by phpnode** [comment]
@Radivarig you can't pass a type around at all, they are an abstract concept and simply do not exist when the program is running. I think you've misunderstood something about how they work, in both flow and typecheck.
