### ISSUE TITLE
seeking structural types

### ISSUE THREAD

**Issue by raould** [facebook/flow#1077]
This is apparently already supported (yay!), but I am too dumb and couldn't easily find out via web / issue searching, so I'm adding this here for seo purposes, if that is considered ok?

```
/* @flow */
type T = {a:string};
function foo(x:T) {
    console.log( x );
    return x.a;
}
function bar(x:{b:number}) {
    console.log( x );
    return x.b;
}
foo({a:'Hello, world!'});
foo({a:'Hello, world!',b:'foobar'});
//foo({b:'foobar'});                                                                                                                                                
//bar({a:'Hello, world!'});                                                                                                                                         
bar({a:'Hello, world!',b:42});
bar({b:42});
```

**Comment by samwgoldman** [comment]
I'm not sure what's going on here. Are you reporting an issue with Flow? Is this an attempt to add documentation? I don't think an issue on GitHub is a great place to add information—people rarely read this. If you want to add documentation, your best bet is to clone the repo and send a PR to the `gh-pages` branch. If you aren't able to do that, please be more specific about what documentation is missing, so we can track that.

**Comment by raould** [comment]
Apologies. Yes this was a stab at documentation. I can try to find time to do the whole PR thing instead, of course. Thanks for everybody's efforts on Flow.
