### ISSUE TITLE
support 'whitelist' to check on command line

### ISSUE THREAD

**Issue by raould** [facebook/flow#1078]
Flow seems to check every file that exists. I would like to be able to give it a list of files (mostly actually usually just one file, as I am working on that file) and have it only check those. Having to use check-contents seems really weird and laborious for my use case. Could a "check-files" command be added?

**Comment by calebmer** [comment]
You can use strategic placement of your `.flowconfig` along with `ignore` to only check the files you need. Let me know if this is inadequate 👍

We also now have `focus-check`.
