### ISSUE TITLE
React.createElement has improper type annotations

### ISSUE THREAD

**Issue by chris-lock** [facebook/flow#1082]
According to the [React docs](https://facebook.github.io/react/docs/top-level-api.html#react.createelement), the first parameter for `React.createElement` should be a union of `string` and `ReactClass`.

```
ReactElement createElement(
  string/ReactClass type,
  [object props],
  [children ...]
)
```

Currently only `ReactClass` is being [enforced](https://github.com/facebook/flow/blob/master/lib/react.js#L132).

Looks like there was a pull request for this a while ago. https://github.com/facebook/flow/pull/272

Love Flow. Thanks for all the work.

**Comment by AsaAyers** [comment]
With React 0.14 that type signature would also include [stateless functional components](http://facebook.github.io/react/blog/2015/10/07/react-v0.14.html#stateless-functional-components).

So it's something more like `string/ReactClass/FunctionalComponent`. where

    type FunctionalComponent = (props?: Props, context?: any) => ReactElement<any, any, any>

**Comment by danez** [comment]
We also have the same problem with this Type of code:
```js
render() {
   ...
   const Tag = others.href ? 'a' : 'button';

   return <Tag {...others}>{this.children}</Tag>;
}
```

I tried adjusting the react definition similar to this [typescript] definition, but i could not manage to get it working. :(

[typescript]: https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/react/react.d.ts

**Comment by jedwards1211** [comment]
@samwgoldman is there any clean way to override Flow's internal defs, so that we could use that PR until this is fixed?

**Comment by danez** [comment]
Seems that strings are now allowed in master now with #1559

**Comment by danez** [comment]
And stateless components are supported now also. Seems this is fixed.
