### ISSUE TITLE
Types of function declaration

### ISSUE THREAD

**Issue by AsaAyers** [facebook/flow#1083]
I have a set of functions that all take a very similar signature:

```
type Reducer<T> = (state: T, action: FSA) => T
```

if I use variables and function expressions I can reuse my type and it doesn't require me to hint each parameter and the return type.

```
export const expressionReducer: Reducer<string> = function(state = "", action) {
    return state
}
```

If I prefer to write it as a function declaration, the closest solution I've been able to find is to cast the function. It still isn't the same though, because flow only checks the return type here.

```
export function declareReducer(state = "", action) { // errors about missing annotations
    return state // it correctly tells me this isn't a number
}
(declareReducer: Reducer<number>) // this is intentionally the wrong type
```

**Comment by samwgoldman** [comment]
Can you clarify what your expectation is? It would be helpful if you shared the actual output/behavior and your expected output/behavior.

**Comment by AsaAyers** [comment]
ok, I shouldn't have included the last section with my attempt at figuring it out.

```js
type Reducer<T> = (state: T, action: {}) => T
const expressionReducer: Reducer<number> = function(state = 0, action) {
    return state
}

function declareReducer(state: number = 0, action: {}): number {
    return state
}
```

In the code above it seemed like `expressionReducer` and `declareReducer` have exactly the same signature. I was looking for a way to use a declaration (`function declareReducer`) along with `Reducer<number>`.

**Comment by ultragtx** [comment]
Hi @AsaAyers, have you figured out how to reuse function types in function declarations?

**Comment by AsaAyers** [comment]
No, I ran into several issues and had to abandon flow completely.

**Comment by calebmer** [comment]
We are sorry to here that you had to abandon Flow 😔

We hope to win you back in time.
