### ISSUE TITLE
Document common Flow errors

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1084]
Errors like "is not compatible with" are pretty self-evident, but "missing annotation" can be a bit disorienting before you have the background to justify why it is an error.

We should have a page on the Web site that lists the most common errors and explains why they happen and, if applicable, how to resolve them.

**Comment by TrySound** [comment]
@samwgoldman Is this still relevant?

**Comment by samwgoldman** [comment]
This is too vague to be actionable. Improving error messages is a perennial issue, and some kind of documentation about common errors would be nice, but I don't think this open issue is valuable.

**Comment by mrkev** [comment]
PR'd on https://github.com/facebook/flow/pull/4554, being looked at
