### ISSUE TITLE
Ability to "declare type"

### ISSUE THREAD

**Issue by dallonf** [facebook/flow#1085]
From an actual module, you can `export` a `type`:
```js
// @flow

export function doSomething(opts: DoSomethingOptions): void {
  // ...
}

export type DoSomethingOptions = {
  // ...
}
```

But the same is not true of a declaration file:

```js
declare module 'do-something' {
  declare function doSomething(opts: DoSomethingOptions): void;
  declare type DoSomethingOptions = {
    // ...
  }
}
```

This seems like it would be very useful.

**Comment by dallonf** [comment]
Related to this suggestion (I'll happily move this to a different ticket if it's something else entirely), it would be useful to be able to import a type from another declaration...

```js
// interfaces/redux.js

declare module 'redux' {
  // ...
  declare type Store = {
    // ...
  }
  // ...
}
```

```js
// interfaces/react-redux.js
import type Store from './redux.js';

declare module 'react-redux' {
  // ...
  declare class Provider extends ReactComponent<any, {
    store: Store;
  }, any> {};
  // ...
}
```

**Comment by samwgoldman** [comment]
Your first snippet shows that you tried `export type` from a declaration file. Did you also try `declare type`? IIRC, this is already implemented.

**Comment by dallonf** [comment]
What on earth...? I swear, that wasn't working 10 minutes ago... :confounded: Maybe the issue is that I was trying to declare the types below where they were used?

**Comment by samwgoldman** [comment]
Happens to everyone. The tag-along issue about dependencies between interface files is interesting to me as well. I haven't really thought about it, but it seems important. Would you mind opening a separate issue for that?

**Comment by dallonf** [comment]
@samwgoldman I just tried that and it seems to work, too. I'm guessing I messed up in the syntax in my initial attempts.

**Comment by samwgoldman** [comment]
Good to know. Thanks!
