### ISSUE TITLE
cannot use EventEmitter.call(···)

### ISSUE THREAD

**Issue by oriSomething** [facebook/flow#1088]
for:

``` js
EventEmitter.call(this);
```

the error message: 

```
15:     EventEmitter.call(this);
         ^^^^^^^^^^^^^^^^^^^^^^^ call of method `call`
 15:     EventEmitter.call(this);
                      ^^^^ property `call`. Property not found in
465:   declare class EventEmitter extends events$EventEmitter {}
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ statics of EventEmitter. See: /private/tmp/flow/flowlib_2ed57059/node.js:465
```

because technically `EventEmitter` isn't ES6 class, and not only use exclusively with `class inherit` i think it's fully legally to use `EventEmitter.call(···)`

**Comment by aprock** [comment]
Found this while searching for the answer myself....leaving here for future searches.

use instanceof to tell flow what you're doing.

```javascript
if (EventEmitter instanceof Function) {
  EventEmitter.call(this);
}
```

This is from the  _[Flow, meet Underscore](http://flowtype.org/docs/underscore.html)_ case study.

**Comment by calebmer** [comment]
It looks like this works now 😊

https://flow.org/try/#0JYWwDg9gTgLgBAbwKIDcCmA7GSTBjNKAXzgDMoIQ4ByNdLagbgChnVNtd9CA6AYwCGAGyEAKGAAtgAZwCULIA
