### ISSUE TITLE
"unsupported destructuring"/"Unexpected token" with a default value

### ISSUE THREAD

**Issue by AsaAyers** [facebook/flow#1089]
I split this into two parts because there definitely is a problem, but I don't know which one is the expected behavior. #1008

unsupported destructuring
=====
You don't seem to have [a test](https://github.com/facebook/flow/blob/master/tests/destructuring/destructuring.js) that verifies this, but adding a default value breaks destructuring.

`flow check-contents src/base_character.js < src/base_character.js` 

```
src/base_character.js:249
249:         const { min = 0, foo } = meta
                           ^ unsupported destructuring
```

If I remove `= 0` it stops complaining.

unexpected token
=====

`flow check`

```
src/base_character.js:248
248:         const { min = 0, foo } = meta
                         ^ Unexpected token =
```

**Comment by samwgoldman** [comment]
This is a known issue. See #183
