### ISSUE TITLE
`module.name_mapper` - bug or user error?

### ISSUE THREAD

**Issue by dallonf** [facebook/flow#1090]
So, let's say... totally hypothetically of course... that I have the following lines in my `.flowconfig`:

```
[options]
module.name_mapper='^.*\.less$' -> '_LessFile'
```

And a declaration in my my `interfaces` directory:

```
// @flow

declare module '_LessFile' {
  declare var exports: {[key: string]: string};
}
```

And, finally, in the real code:

```
import styles from './DataList.less';
```

However, when checking the code, it throws the same `./DataList.less. Required module not found` error as it would if nothing were configured in `options` at all.

Here's the steps I've taken to troubleshoot this:
1. Use `require()` instead of `import`; result: no effect
2. Copy the [example from the docs](http://flowtype.org/docs/advanced-configuration.html#options) into my config and add `var image = require('image!foo.jpg');` to my code and `declare module 'ImageStub' {}` to the declarations file; result: error in `flowconfig`: `Error parsing value for "module.name_mapper". Expected a mapping of form: 'single-quoted-string' -> 'single-quoted-string'`. Eh?
3. Removed the space after the `=` from the example (might want to update the docs!). Result: Same old "DataList.less... not found" error, along with a brand new "image!foo.jpg. Required module not found"

I'm not sure whether I'm doing something wrong here or if there's a legitimate bug in Flow. Here's my system environment:
- Flow v0.18.1, installed via `npm3 install flow-bin`
- Mac OS X v10.11.1 (El Capitan)
- Anything else needed? I'm unsure what kind of information would be useful here

**Comment by blacktaxi** [comment]
Are you using `module.system=haste`?

**Comment by dallonf** [comment]
`module.system` is not set in `.flowconfig`, so it's whatever the default value is (I think `node`).

**Comment by MoOx** [comment]
Seems like a dup of #1068

**Comment by calebmer** [comment]
Closing as this is a duplicate.
