### ISSUE TITLE
Flow is not checking condition

### ISSUE THREAD

**Issue by rileylark** [facebook/flow#1097]
I'm running flow 0.18.1, and simple conditions aren't being checked. For example:

```
/* @flow */

type T = {prop: number};

const val: T = {prop: 5};

if (val.nonExistentProp) {
  console.log(val.prop);
}
```

I'd expect a type error on `nonExistentProp`. If I change it to `if (val.nonExistentProp())` or `if (val.nonExistentProp + 2)`, flow correctly notices that there is no such property.

Thanks for any help! Let me know if I can provide any other info.

**Comment by samwgoldman** [comment]
This is actually intended behavior. See earlier discussion in #698.

**Comment by rileylark** [comment]
Thanks for your quick response - that's always helpful!
