### ISSUE TITLE
Support for multiple exports statements

### ISSUE THREAD

**Issue by webpro** [facebook/flow#11]
Flow incorrectly warns me about "property not found" on an exported object, if I have multiple export statements like this:

```js
exports.prop1 = 1;
exports.prop2 = 2;
exports.prop3 = 3;
```
```
../module2.js:3:13,34: property prop1
Property not found in
  ../module1.js: exports
```

If I just export it as a single object it's happy again:

```js
exports = {
  prop1: 1,
  prop2: 2,
  prop3: 3
}
```

**Comment by samwgoldman** [comment]
This is working now and this issue can be closed.

**Comment by samwgoldman** [comment]
Closing. Please reopen if this is still an issue.
