### ISSUE TITLE
type alias in declaration file

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#110]
Currently the compiler seems not to allow type alias inside a declaration, this force us to do a lot of boilerplate ...

```typescript

declare module 'test' {
  declare function doSomething(obj: { foo: string}): void;
  declare function doSomethingElse(obj: { foo: string}): void;
}
```

I would like to be able to write something like : 

```typescript

declare module 'test' {
  type MyObj =  { foo: string};
  declare function doSomething(obj: MyObj): void;
  declare function doSomethingElse(obj: MyObj): void;
}
```

**Comment by samwgoldman** [comment]
This has been implemented (`declare type`). Please re-open if the implementation doesn't satisfy your use case.
