### ISSUE TITLE
Library definition for "react-dom" module

### ISSUE THREAD

**Issue by graue** [facebook/flow#1101]
Unless I'm missing something, doing `require('react-dom')` in a module checked by Flow doesn't seem to be possible right now. To fix that, we'd want to add a `declare module 'react-dom'` block in https://github.com/facebook/flow/blob/master/lib/react.js, right?

**Comment by jonaskello** [comment]
+1 also not getting react-dom to work in flow.

**Comment by jonaskello** [comment]
Found some info here that helped me get it working. The trick was to not ignore all of node_modules but instead only:

[ignore]
.*/fbjs/.*

**Comment by graue** [comment]
@jonaskello: It depends on your definition of "working". That'll fix the "react-dom. Required module not found" error, but won't typecheck uses of ReactDOM. For example, it'll happily say there are no errors in this code:

```js
ReactDOM.findDOMNode('clowntown').focus();
ReactDOM.render().fireTorpedoes();
```

For type-checking, you need an interface definition, either as part of your own project, or upstream in React or Flow.
