### ISSUE TITLE
Triple equals type checking?

### ISSUE THREAD

**Issue by Agrosis** [facebook/flow#1103]
Where `item.equippable` is a boolean, 

```
if (item.equippable == 24) {
  return new Equipment(item);
} else {
  return null;
}
```

Doesn't type check, but this does:

```
if (item.equippable === 24) {
  return new Equipment(item);
} else {
  return null;
}
```

Is there just not type checking support on triple equals?

**Comment by mroch** [comment]
Thanks for bringing this up. I took a look and think this is the same issue as #698. I believe I have a fix, will attach it to that issue.
