### ISSUE TITLE
Switch from make to ocp-build?

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1106]
We are using ocp-build to support windows, so now we're maintaining both `build.ocp` and `Makefile`. Should we just switch to ocp-build? Having to install ocp-build makes it slightly harder to build flow, but if you have `opam` anyway, it's no big deal.

**Comment by mroch** [comment]
cc @OCamlPro-Bozman @OCamlPro-Henry @gabelevi

**Comment by OCamlPro-Henry** [comment]
@lefessan

**Comment by lefessan** [comment]
I suppose that what you mean is using ocp-build just to build flow, and still use the Makefile for other targets. I think that such a use of ocp-build is safe. ocp-build is not as concise as Makefiles for generic targets, but it is quite simple and often much faster for OCaml targets. We can probably add some more comments in the `build.ocp` to make it easy to extend.

**Comment by mroch** [comment]
yeah, I guess just to build flow, unless there's support for running generic commands but I don't see that in the user manual. I think we'd just keep the Makefile and have it run `ocp-build`, but that's better than the `ocamlbuild` stuff we're doing in the makefile now, which doesn't match how we build internally.

we use [Buck](https://buckbuild.com/) internally, which has files very similar in spirit to `build.ocp` (a bunch of targets with a list of sources and dependencies). I wonder if we could even generate the BUCK file from the build.ocp... that would solve a source of breakage that we run into when we add new files/directories and update the `BUCK` files but forget to update `Makefile` or `build.ocp`. I'll look more into what `build.ocp` supports to see if that's doable for us.

**Comment by calebmer** [comment]
I’m going to close because of inactivity. Feel free to reopen if this is still a thing 😊
