### ISSUE TITLE
`if (!foo in map)` should be an error

### ISSUE THREAD

**Issue by danvk** [facebook/flow#1107]
This is a common JS gotcha:

```javascript
/** @flow */
function add(map: {[key:string]: number}, k: string) {
  if (!k in map) map[k] = 0;  // <-- looks up "!k"
}
```

it should be:

```javascript
/** @flow */
function add(map: {[key:string]: number}, k: string) {
  if (!(k in map)) map[k] = 0;  // note extra parens
}
```

Flow should be able to catch this but, as of Flow 0.18.1, it does not.

`!k` where `k` is a `string` should either be an error or have type `boolean`, which shouldn't be possible to look up in a map with keys of type `string`.

**Comment by samwgoldman** [comment]
We identify this pattern [in Type_inference_js.ml](https://github.com/facebook/flow/blob/4e669af3837de63b124aea0f7ee36500ce772d39/src/typing/type_inference_js.ml#L3952). Right now we simply claim that the whole `l in r` expression is a boolean, but it is possible we could do more.

**Comment by danvk** [comment]
Cool. I don't see much loss for making `x in map` be an error if `x` has the wrong type. If Flow can determine ahead of time that this will evaluate to `false`, then you should just remove it :)

**Comment by samwgoldman** [comment]
Even in your example, we wouldn't know statically that the expression evaluates to false, because the boolean is coerced to a string. `false in { "false": null }` is `true`, for example. Still, I think there's a reasonable argument to be made for warning in this case.

**Comment by danvk** [comment]
Even so, I don't think there's much loss to making this an error.

If you really intend to look up `"false"`, then you can just write `k.toString() in map`.
