### ISSUE TITLE
Invalid return type of Map.prototype.get

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#1110]
The current interface is
```
declare class Map<K, V> {
    // ...
    get(key: K): V;
    // ...
}
```
whereas according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/get) it should be `get(key: K): ?V`.

**Comment by mroch** [comment]
actually let's do `V | void`, since `?V` is `V | null | void`

**Comment by samwgoldman** [comment]
Would be nice if we could somehow refine this with `Map.prototype.has`

**Comment by pasha-mf** [comment]
The same apply for array access as well: if `arr: Array<number>` then `arr[0]` should have type `void|number`. But then Flow would have to understand refinements based on `arr.length`.

**Comment by mhagmajer** [comment]
How would those refinements work for sparse arrays?
