### ISSUE TITLE
Invalid type check for Map constructor argument

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#1111]
This type checks in Flow 0.18.1:

```javascript
const map: Map<number, number> = new Map([[1, 'one']]); // key type mismatch

function test(m: Map<string, number>): Map<string, string> {
  return new Map(m); // // value type mismatch
}
```

**Comment by samwgoldman** [comment]
Looks like we might need an explicit `void` dummy arg to avoid the extra args are valid issue. See the [type declarations in lib/core.js](https://github.com/facebook/flow/blob/0a4395c5958e9633db168f68003b09be2630879e/lib/core.js#L356).

**Comment by mroch** [comment]
Map has no constructor currently (these lines mean you can call an instance; you need `constructor` for it to be run as a constructor via `new`). I'm fixing this in the same diff as #1110.
