### ISSUE TITLE
Referencing the type of a property in an object type (feature request)

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#1112]
Let's say we have `Person` object type defined like this:

``` js
type Person = {
  name: string;
  address: {
    street: string;
    house: number;
  }
};
```

Is there any way to reference the address part of this type like below?

``` js
type Address = Person['address'];
```

**Comment by vkurchatkin** [comment]
This works: `type Address = Person.address;`

**Comment by mhagmajer** [comment]
Oh, cool!

**Comment by calebmer** [comment]
We now have `$PropertyType`. So you can write `$PropertyType<Person, 'address'>` :tada:
