### ISSUE TITLE
in lib.dom.js: HTMLImageElement.crossOrigin and HTMLMediaElement.crossOrigin should be nullable

### ISSUE THREAD

**Issue by ckknight** [facebook/flow#1117]
Currently HTMLImageElement and HTMLMediaElement define their crossOrigin property as `string`, despite the default value being `null`.

**Comment by mroch** [comment]
[the spec](https://html.spec.whatwg.org/multipage/infrastructure.html#cors-settings-attribute) says that a _missing default value_ represents "no CORS" but an _invalid default value_ is equivalent to `"anonymous"`. I'm not sure, but I interpret it as `null` being an invalid value (it's a value that is not `"" | "anonymous" | "use-credentials"`), so it's actually different than it being `undefined`.

I think it should be `string | void` not `string | null`. even better would be for it to be `"" | "anonymous" | "use-credentials" | void`, though.

**Comment by mroch** [comment]
but you're right, if I inspect an <img> on this page and do `$0.crossOrigin` I get `null`, not `undefined`. would love to find what justifies that behavior...
