### ISSUE TITLE
React.createElement interface could be more restrictive

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#1121]
The current interface for React.createElement is

```
declare function createElement<DefaultProps, Props, State, A: $Diff<Props, DefaultProps>>(
    name: ReactClass<DefaultProps, Props, State>,
    attributes: A,
    children?: any
  ): ReactElement<DefaultProps, Props, State>;
```

While this ensures all non-default props are passed as attributes, it does not restrict arbitrary props from being passed.

I think the declaration for the attributes should be:

```
A: $Shape<Props> & $Diff<Props, DefaultProps>
```

I think making this more restrictive is beneficial as passing a prop to a class which does not expect is often a bug. For example, imagine a class which expected a prop minSize which was later refactored to receive minWidth and minHeight. If these have defaults, the bug would not be caught at component call-sites.

Of course, I'm not sure this is a bug or by design.
- Are there createElement attributes which are not component props? If that set is finite, we could still have `$Shape<GlobalAttributes & Props> & $Diff<Props, DefaultProps>`.

**Comment by smirea** [comment]
+1 this would be very useful and doesn't seem hard to implement

**Comment by nikita-gazarov-hs** [comment]
eslint proptypes validation also allows undefined properties to be passed, and React itself does not complain about undefined properties with console.warn. I'm not sure why, but this seems intentional.

**Comment by asolove** [comment]
A lot has changed in the year and a half since this issue was opened. The syntax and typing rules for React Components have changed, and Flow now offers "exact object" types if you want to ensure that an object only has the properties that are explicitly expected.

Combining those two things, we can now get Flow to tell us if we include unwanted extra props:

```js
/* @flow */

import * as React from 'react';

class Thingy extends React.Component<{| name: string |}, *> {
  render() {
    return <div>{this.props.name}</div>;
  }
}

<div>
	<Thingy name="Adam"/> // Works fine
	<Thingy name="Adam" extra="2"/> // Error: property extra not found in object type.
</div>
```

So I think this is now working and can be closed! (/cc @calebmer )

**Comment by cprodescu** [comment]
Agree, have appreciated the changes in this direction!
