### ISSUE TITLE
Failure on Nuclide codebase

### ISSUE THREAD

**Issue by nmote** [facebook/flow#1122]
I'm experiencing failures in parts of the Nuclide codebase. A trivial project works fine, and some other files also work fine.

I bisected the issue to 4be93bf2a9346bdff82f9be91dc06ed51cd0ce63 (cc @avikchaudhuri, @bhosmer).

Steps to repro:
* Check out https://github.com/facebook/nuclide/commit/08a8276edac961ed7ba1ab95c374c1e237f8867a (any recent rev should do, but note that we recently moved to a single .flowconfig so you'll want one after that).
* Run the Nuclide setup script
* Run `flow get-def pkg/nuclide/busy-signal/lib/MessageStore.js 39 20`

I get `Fatal error: exception End_of_file`

If I replace `get-def` with `type-at-pos`, I get this instead:

```
/path/to/nuclide/pkg/nuclide/busy-signal/lib/MessageStore.js:39:20:
Not_found
```

It may be worth noting that I'm on Fedora 21.

Autocomplete also doesn't appear, but I haven't checked exactly what its output is.

**Comment by nmote** [comment]
Just checked, and this also happens on OS X.

**Comment by samwgoldman** [comment]
I was able to repro both the `get-def` and `type-at-pos` exceptions.

I also saw ~80 errors, some of which seem to be related to changed error reasons (presumably due to improved messaging) which invalidates error suppressing comments, which are no longer at the reported position of the error.

Is this issue in reference to those errors as well, or just the exceptions?

**Comment by nmote** [comment]
This is just in reference to the exceptions. I'm aware of the changes since v0.18.1 that have caused new errors we will have to clean up, but that's our problem :smile:

**Comment by nmote** [comment]
Although, it would be nice to fix the error locations. Right now I think the only way to fix some of those errors is to cast to `any`, since suppression comments will no longer work. But anyway, I can live with that. This issue is about the outright failures.

**Comment by samwgoldman** [comment]
My understanding is that nothing is someone else's problem. :smile: I'd be happy to sit down and look at the errors next week.

Regarding the exceptions, I did a bit of digging here. Using a debug build (`make build-flow-debug`) I tracked down the `get-def` exception to [here](https://github.com/facebook/flow/blob/5fbc8263f4c033c902b552590233e88e00616d85/src/server/server.ml#L345), which isn't super helpful, but if I print the backtrace in that exception handler, we're directed to a [reasonable suspect](https://github.com/facebook/flow/blob/5fbc8263f4c033c902b552590233e88e00616d85/src/typing/module_js.ml#L550).

**Comment by avikchaudhuri** [comment]
Thanks @samwgoldman. Yeah that's it, and I have a simple fix, but before sending it out I'm trying to figure out why the defense is needed.

**Comment by avikchaudhuri** [comment]
Oh got it, this file was ignored. Interesting, I'll add a test case so that we don't forget about those. :)
