### ISSUE TITLE
How to make Flow process selected sub-folder from node_modules only

### ISSUE THREAD

**Issue by Efimster** [facebook/flow#1129]
version 0.18.1

I have a project where node_modules folder contains more than 50 sub-folders.
I was trying to configure flow to ignore node_modules/* but node_modules/flux/flow/include . 

Here are failed attempts that had to work from my perspective. What i'm doing wrong? Thanks  

approach 1) 
//.flowconfig
[ignore]
.\*/node_modules/.\*

[include]
node_modules/flux/flow/include

approach 2) 
//.flowconfig
[ignore]
.\*/node_modules/(?!flux/flow/include).\*

approach 3) 
//.flowconfig
[ignore]
.\*/node_modules/[^f][^l][^u][^x]/[^f][^l][^o][^w]/[^i][^n][^c][^l].\*

**Comment by mroch** [comment]
I don't think there's a good way to do this. see #564

**Comment by ncalexan** [comment]
This could be achieved by exclusion-inclusion.  How do `[ignore]` and `[include]` interact?  Could we make them chain?  I think it's quite common to ignore `node_modules` save for a small subset; that suggests that we should make `[include]` override `[ignore]`.
