### ISSUE TITLE
Add https definitions to lib/node.js

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1137]
Flow is missing definitions for the [https module](https://nodejs.org/api/https.html). Also the [http module](https://nodejs.org/api/http.html) is missing some definitions.

**Comment by jamesgpearce** [comment]
Isn't it basically exactly the same as http?

**Comment by mroch** [comment]
yeah, except `options` has a bunch of extra options for TLS

**Comment by jamesgpearce** [comment]
...meaning a manager could do it? :see_no_evil:
