### ISSUE TITLE
Add support for Object.setPrototypeOf

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1138]
See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/setPrototypeOf

**Comment by mroch** [comment]
actually since this has to actually change the prototype, this'll be harder than just adding it to lib/core.js. it'll have to be added in [type_inference_js.ml](https://github.com/facebook/flow/blob/dbb288e4e15fe09131fa54089bddc520dccd4b9f/src/typing/type_inference_js.ml#L5181) too, I think.

**Comment by nnmrts** [comment]
Any news on this? 😞

**Comment by SamChou19815** [comment]
Unlikely to support this since we discourage dynamic patterns like this.
