### ISSUE TITLE
Allow core-lib declarations to be ignored

### ISSUE THREAD

**Issue by tcoopman** [facebook/flow#114]
At the moment I cannot find a way to ignore the core-lib declarations at startup.
It would be nice if we could provide our own declarations. This would allow us to fix problems with the core declarations that are out of sync with the spec.

See for example: https://github.com/facebook/flow/pull/113 or https://github.com/facebook/flow/pull/108

**Comment by samwgoldman** [comment]
You can use --no-flowlib to ignore the builtin libs.
