### ISSUE TITLE
Wrong error location for a method that fails to return the correct value

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1144]
``` js
/* @flow */
class Foo<T> {
  test(): T {}
}
```

output:

```
3: class Foo<T> {
         ^ some incompatible instantiation of `T`. This type is incompatible with an implicitly-returned undefined.
```

The error should be pointing at the `test` method instead of the class declaration.

**Comment by thejameskyle** [comment]
(Updated issue with current error output)

**Comment by TrySound** [comment]
Seems like error location is correct right now
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AMTjgB4AVAPjAG9UwwAXAUxwYAoBKALjDJoF9U-IA

/cc @vkurchatkin
