### ISSUE TITLE
Possible integration with Immutable.js

### ISSUE THREAD

**Issue by DecSander** [facebook/flow#1146]
While Immutable.js can be used with Flow.js, I think there may be an especially interesting integration when looking at http://flowtype.org/docs/dynamic-type-tests.html#caveats 

I say this because while obviously a function call can cause an unforseen mutation per the example at the above link, it may be possible that using Immutable.js, Flow can ensure that mutation did not occur without going into a full mutation analysis and thus not require another typecheck.

This is obviously not a trivial task and it's more just meant to gauge interest on whether this is something people want

**Comment by AgentME** [comment]
Related: A similar way that Flow could better work with Immutable.js is discussed here: https://github.com/facebook/flow/issues/1016. It should be possible to cast an immutable `List<number>` to `List<number|string>`, etc.
