### ISSUE TITLE
Fatal error: exception Invalid_argument("String.sub / Bytes.sub")

### ISSUE THREAD

**Issue by kimmobrunfeldt** [facebook/flow#1148]
When running flow, I get a fatal error:

```
Fatal error: exception Invalid_argument("String.sub / Bytes.sub")
```
I have an empty .flowconfig created with `flow init`. I installed flow via `npm install flow-bin`, but that downloads the released binary so I assumed it makes no difference.

**Versions:**
OS X 10.10.5 
Flow: OS X Binaries: v0.19.0/flow-osx-v0.19.0.zip
npm 2.14.2
node v4.0.0

**Comment by danvk** [comment]
I'm also seeing this on my project.

OS X 10.10.5
Flow 0.19.0
npm 3.3.9
node v5.0.0

**Comment by mroch** [comment]
looking at the places we call `String.sub`, it's most likely while trying to print an error. can you try with `--old-output-format`? that'll help figure out what the error struct looks like so we can repro with the new printer.

**Comment by danvk** [comment]
```
$ flow check --old-output-format

/Users/danvk/github/pileup.js/node_modules/npmconf/test/fixtures/package.json:1:3,2: Unexpected end of input

Found 1 error
```

**Comment by danvk** [comment]
Adding `.*node_modules/npmconf.*` to the `ignore` section of my `.flowconfig` made the error go away.

**Comment by mroch** [comment]
hrm, that's an empty file. we have a [unit test for that](https://github.com/facebook/flow/blob/555d43d5cf57bdedc81b1dc1e30f94f5dd745cb2/tests/node_tests/invalid_package_file/package.json), I think because of this exact npm module, since it has invalid files in its tests... I'll try to repro.

**Comment by mroch** [comment]
our unit tests run with `--old-output-format` so they pass... but it repros if you do `flow check tests/node_tests/` without `--old-output-format`.

**Comment by kimmobrunfeldt** [comment]
I tried it with the `--old-output-format` as you adviced. I get the same error as @danvk but from a different module apparently:

```/My/Project/Path/node_modules/david/node_modules/npm/test/fixtures/config/package.json:1:3,2: Unexpected end of input```

**Comment by mroch** [comment]
found the problem, fix incoming. ignoring `.*node_modules/npm/test/.*` is not a bad idea anyway, and should work around this in the meantime.

**Comment by kimmobrunfeldt** [comment]
That was fast, thanks! :)

**Comment by danvk** [comment]
Thanks @mroch. Does this merit a 0.19.1 bugfix release?

**Comment by gabelevi** [comment]
Yep! We're cherry picking the fix into a 0.19.1 release. First time doing it this way, so hopefully we don't ruin everything!

**Comment by gabelevi** [comment]
Ok 0.19.1 is tagged and release.

* flow-bin is published
* [homebrew PR is out](https://github.com/Homebrew/homebrew/pull/46642)
* [opam PR is out](https://github.com/ocaml/opam-repository/pull/5242)

Thanks for the error report, thanks for using flow, and thanks for your patience!

**Comment by bcowgill** [comment]
I am getting this same error and not seeing line numbers when I use old output format so rather tricky fixing things.

Flow, a static type checker for JavaScript, version 0.22.1
Linux worksharexps-XPS-15-9530 3.19.0-43-generic #49-Ubuntu SMP Sun Dec 27 19:43:07 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux


NODE_DEBUG=* ./node_modules/.bin/flow
Fatal error: exception Invalid_argument("String.sub / Bytes.sub")
$ NODE_DEBUG=* ./node_modules/.bin/flow --old-output-format

lib/support.js: return
Missing annotation

support.js:99:4,4: return
Missing annotation

support.js: return
Missing annotation

lib/support.js: return
Missing annotation

lib/support.js: return
Missing annotation

lib/support.js: return
Missing annotation

Found 6 errors

**Comment by bcowgill** [comment]
After some investigation it seems the flow parser will choke on this:
function x() //: function
{
}

but not
function x() /*: function */
{
}

my bad assumption about how the annotation comments could be formatted.

**Comment by echenley** [comment]
Just had this issue in Flow v0.47. Adding `.*/node_modules/npm/test/.*` to the [ignore] section of .flowconfig resolved it.

**Comment by andreiglingeanu** [comment]
Same, I'm on `0.59.0`.

**Comment by toddmedema** [comment]
Same error on 1.4.0, but none of these [ignore]s fixed it and the --old-output-format is now disabled. Is there any other way I can get a more useful error out of this? (eventually found the problem folder by ignoring everything and slowly adding them back, but it would have been great to have a useful error from the start...)

**Comment by rodrigopr** [comment]
same error on latest flow version.
```ml
Unhandled exception: Invalid_argument("String.sub / Bytes.sub")
Raised at file "pervasives.ml", line 33, characters 20-45
Called from file "string.ml", line 47, characters 2-23
Called from file "src/common/errors/errors.ml", line 2045, characters 44-70
Called from file "list.ml", line 96, characters 24-34
Called from file "src/common/errors/errors.ml", line 2014, characters 46-1023
Called from file "list.ml", line 96, characters 24-34
Called from file "src/common/errors/errors.ml", line 2007, characters 32-1023
Called from file "map.ml", line 286, characters 19-24
Called from file "map.ml", line 285, characters 19-27
Called from file "src/common/errors/errors.ml", line 1999, characters 22-1023
Called from file "src/common/errors/errors.ml", line 2400, characters 8-170
Called from file "src/common/errors/errors.ml", line 2570, characters 12-320
Called from file "list.ml", line 85, characters 12-15
Called from file "src/common/errors/errors.ml", line 2582, characters 8-62
Called from file "src/flow.ml", line 82, characters 6-34
```

Managed to find the source of the errors with `flow --json --pretty` (cc @toddmedema)

**Comment by caoilte** [comment]
Just encountered this problem. Went away after I forced the server to reinitialise.

**Comment by toddmedema** [comment]
@caoilte I've also been getting a surprising number of errors about node_modules that are fixed with a server restart. A bit disappointed that that's even a problem... seems like a pretty big bug with the server system.

**Comment by Hawkz69** [comment]
run 

> killall flow

 then and run flow.
