### ISSUE TITLE
new.target support

### ISSUE THREAD

**Issue by bradleat** [facebook/flow#1152]
Flow breaks if you give it:

   var x = new.target

It tells me that the "." is an unexpected token.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/new.target

**Comment by mroch** [comment]
TIL. added it to #560 too.

**Comment by rogchap** [comment]
Even get this error even with option: `suppress_comment` (flow v0.23.0) eg.

``` javascript
// $FlowIssue: https://github.com/facebook/flow/issues/1152
if (new.target === BaseClass) {
  throw TypeError("new of abstract class BaseClass");
}
```

**Comment by jlouazel** [comment]
Is there any update on this one? I am like @rogchap, `suppress_comment` seems not to work with it.

**Comment by Ltrlg** [comment]
The following is a parse error 0.38.0:

```js
function a(x = new.target){}
```

I found no evidence it should be forbidden and both Firefox and Node read it without error.

**Comment by Sigfried** [comment]
I'm still getting this problem:

```
./node_modules/flow-bin/flow-osx-v0.40.0/flow check
src/components/SigmaReactGraph.js:40
 40:     if (new.target === MacroNode) {
             ^^^^^^^^^^ not (sup)ported

```

**Comment by ThomasGHenry** [comment]
> I'm still getting this problem:
> 
> ```
> ./node_modules/flow-bin/flow-osx-v0.40.0/flow check
> src/components/SigmaReactGraph.js:40
>  40:     if (new.target === MacroNode) {
>              ^^^^^^^^^^ not (sup)ported
> ```

Same. What's the recommended way to do this?
