### ISSUE TITLE
Flow in windows: MapViewOfFileEx error

### ISSUE THREAD

**Issue by submain** [facebook/flow#1157]
First, congratulations on this major milestone! It is awesome to finally have flow on windows.

When doing flow.exe init followed by flow.exe check, I get:

    Fatal error: exception Unix.Unix_error(12, "MapViewOfFileEx", "")
    Raised by primitive operation at file "hack\heap\sharedMem.ml", line 45, characters 2-97
    Called from file "src\server\serverFunctors.ml", line 261, characters 28-55
    Called from file "src\flow.ml", line 86, characters 2-19

Any clues?

**Comment by storzinc** [comment]
I am getting the same error message on windows 7, on windows 10 all seems to work fine.

**Comment by submain** [comment]
I am on windows 7 as well.

**Comment by mroch** [comment]
cc @OCamlPro-Bozman

**Comment by OCamlPro-Bozman** [comment]
Hi,

Thanks for the report. We are aware of this issue on Windows 7 (only). We are investigating why the `MapWiewOfFileEx`is behaving differently on Windows 7.

**Comment by OCamlPro-Bozman** [comment]
I juste uploaded a new version which should fix this bug on Windows 7:

    http://www.ocamlpro.com/pub/ocpwin/flow-builds/

**Comment by submain** [comment]
Thanks for the fast response! It works wonderfully now.
