### ISSUE TITLE
jsx syntax not checked on 0.19.0 and 0.19.1

### ISSUE THREAD

**Issue by arypurnomoz** [facebook/flow#1158]
Hi, i'm using OSX el capitan, after upgrading to 0.19.0 and 0.19.1, i notice flow no longer check the proptypes on jsx syntax
```
type DefaultProps = {}
type Props = {
  required: string
}
type State = {}
class FlowTest extends ReactComponent<DefaultProps,Props, State> {
  static defaultProps:DefaultProps;
}
FlowTest.propTypes = {
  required: React.PropTypes.string.isRequired
}

// these two won't throw any error on 0.19.0 and 0.19.1
var a = <FlowTest />
  , b = <FlowTest required={1} />
```
Everything works perfectly on version 0.18.1

**Comment by ianobermiller** [comment]
Running your code through 0.19 `flow check-contents` shows the following errors for me (after adding an import for React):

-:16
 16: var a = <FlowTest />
             ^^^^^^^^^^^^ React element `FlowTest`
  8: class FlowTest extends ReactComponent<DefaultProps,Props, State> {
                                                        ^^^^^ property `required`. Property not found in
 16: var a = <FlowTest />
             ^^^^^^^^^^^^ type parameter `Props` of React element `FlowTest`

-:17
 17:   , b = <FlowTest required={1} />
             ^^^^^^^^^^^^^^^^^^^^^^^^^ React element `FlowTest`
 17:   , b = <FlowTest required={1} />
                                 ^ number. This type is incompatible with
  5:   required: string
                 ^^^^^^ string

**Comment by arypurnomoz** [comment]
Does it work if you import React from "react-native"?

**Comment by tp** [comment]
I have the same problem with 0.19.1. I would expect propTypes to be validated, but they are not.

I tried the React description and also native flow, but neither works for me.

Repro:
https://gist.github.com/tp/b50e5be97dfa5ed25af0

**Comment by STRML** [comment]
```
[ignore]
.*/node_modules/react/.*
```

fixes the issue in my testing.

**Comment by arypurnomoz** [comment]
@STRML thanks, it fixed the problem, but what if i also want to `require("react")`?

**Comment by ianobermiller** [comment]
Good point, I had that in the project I was running `flow` in. @arypurnomoz, it will just be untyped by flow, which is probably fine since the surface area is tiny. You can probably grab or write a flow lib file instead.
