### ISSUE TITLE
Warn when types exposed to external code (via exported functions) aren't exported

### ISSUE THREAD

**Issue by jeswin** [facebook/flow#1160]
This is a feature request. It would be nice to get warnings when types used in the signature of exported functions are themselves not exported.

In the following code, can we get a warning saying that ExampleType and SomeOtherType must also be exported?

``` javascript
type ExampleType = { n: number }
type SomeOtherType = { r: string }

export function Hello(arg: ExampleType) : SomeOtherType {
  //....
}
```

With .flow files in v0.19, integrating flow into npm has become very straight forward. By just pushing "somelib.js" (transpiled) and "somelib.js.flow" (original) to npm, consumers of somelib can start using flow. As a result, it is no longer necessary to write separate def files and the above use case might become somewhat common.

I hope it makes sense.

**Comment by vkurchatkin** [comment]
There is no necessity  to export these types. Flow uses structural typing, so one can implement a type without importing it.
