### ISSUE TITLE
Adding support for another language?

### ISSUE THREAD

**Issue by cakoose** [facebook/flow#1161]
[This is just a question, not a bug report.  Please let me know if there's a better place to ask these.]

I want to write a type checker for another language.  Is it easy to write custom parsing and type checking code but still take advantage of other infrastructure that Flow provides (incremental processing, etc)?

**Comment by samwgoldman** [comment]
This is a fun question. I don't really have a specific answer for you, but if you look at the source, you'll notice that quite a bit of the infrastructure is in a directory called `hack`. This directory is actually shared with the Hack project, which implements a type system for PHP. This in itself is a kind of proof by construction that, yes, you should be able to take parts of this codebase and apply them to another language (IANAL, but do be aware that this code is licensed for your use, and comply with any laws, etc.)

Regarding the type checking logic itself, some parts are generic and some parts are pretty tied into JS runtime semantics / module resolution rules. Often the generic/specific parts are only conceptually distinct, and occupy the same space in the source code. A motivated reader might be able to derive the generic bits to apply to another language/implementation.

If you do have questions about the implementation of Flow, the best place to ask is probably IRC #flowtype @ freenode, where the core team often can be found.
