### ISSUE TITLE
Ways to seal objects, even at instantiation?

### ISSUE THREAD

**Issue by STRML** [facebook/flow#1164]
We use objects often as a way to pass many parameters to remoting functions.

We'd like to very strictly typecheck these objects, but it appears we're unable to properly seal the objects in the type definitions. For example, we want the following code to fail:

```js
type GetTableParams = {table: string, optionalProperty?: number};
db.getTable = (params: GetTableParams): Promise<Array<Object>> {
  ...
}

// This should throw an error
db.getTable({table: 'foo', anInvalidProperty: 'bar'});
```

Is there a way to signify that an object type should have only the properties in the typedef and nothing more?

**Comment by STRML** [comment]
I found a workaround that properly throws errors for extra properties:

```js
type GetTableParams = {
  table: string,
  optionalProperty?: number,
  // Mark any other properties as invalid.
  [key: string]: void
};

db.getTable = (params: GetTableParams): Promise<Array<Object>> {
  ...
}
// Throws 'string: This type is incompatible with void'
db.getTable({table: 'foo', anInvalidProperty: 'bar'});
```

**Comment by aldendaniels** [comment]
Thanks for the workaround. Proper support within Flow for sealed object types would be a big win for flow IMO.

**Comment by STRML** [comment]
Can close this now that we have `$Exact<obj>` and its shorthand, `{|foo: string|}`.

**Comment by gcanti** [comment]
Is there a difference between the built-in `$Exact<T>` and the custom `$Exact2<T> = T & $Shape<T>;`?
