### ISSUE TITLE
Please provide an ability to annotate function's parameters as template

### ISSUE THREAD

**Issue by trikadin** [facebook/flow#1165]
For example, I've got a function to "callbackify" promisified functions, something like that:

```
function callbackify(fn) {
  return function(...args) {
    const callback = args[args.length - 1];

    fn
      .apply(this, args.slice(0, -1))
      .then(
        (value) => callback(null, value), 
        (err) => callback(err)
      );
  }
}
```

It would be nice to have an ability to annotate this function like this:

```
function callbackify<ARGS, RES>(fn: (ARGS) => Promise<RES>): (ARGS, callback: (err: ?Error, res: RES)) => void {
  return function(...args) {
    const callback = args[args.length - 1];

    fn
      .apply(this, args.slice(0, -1))
      .then(
        (value) => callback(null, value), 
        (err) => callback(err)
      );
  }
}
```

I mean, ARGS could be any number of parameters of any type -- it's just a placeholder, copy of signature of original function, applied to another function and extended with additional param "callback".

**Comment by gajus** [comment]
How is this different from https://github.com/facebook/flow/issues/249 ?

**Comment by calebmer** [comment]
This should work. Let me know if you are experiencing any issues 😊

**Comment by pnevyk** [comment]
I think there is no way how to do it. I would simplify @trikadin's example:

Imagine a function which wraps passed functions (and possibly add some specific behavior):

```js
function wrap(callback) {
    return function (...args) {
        return callback(...args);
    };
}
```

Now, I would like to use this function with every kind of callback and I only know that `wrap` function accepts the same parameter types and has the same return type as given callback.

```js
wrap(function (a: number, b: string): number { return a; }); // (number, string) => number
wrap(function (a: string, b: number): string { return a; }); // (string, number) => string
```

I don't know any way how to type annotate the `wrap` function.

```js
// this obviously doesn't work for me since it will accept only functions with single parameter
function wrap<TArgs, TRes>(callback: (TArgs) => TRes): (TArgs) => TRes {}

// this doesn't work either since it will accept only paramaters with the same type
function wrap<TArg, TRes>(callback: (...Array<TArg>) => TRes): (...Array<TArg>) => TRes {}

// this works but it won't typecheck parameters
function wrap<TRes>(callback: (...Array<any>) => TRes): (...Array<any>) => TRes {}
```

If I missed something in the docs, please let me know. If it's not possible now, I am sure it will be very difficult to implement properly. I would appreciate any feedback. Thanks.
