### ISSUE TITLE
Variable nullability is not inferred properly when tested in loops followed with continue/break control statements

### ISSUE THREAD

**Issue by shushz** [facebook/flow#1167]
```javascript
'use babel';
/* @flow */

function foo(i: number): ?string {
  if (i % 2) {
    return null;
  }

  return 'str';
}

function test() {
  let st: string = 'abc';

  for (let i = 1; i < 100; i++) {
    const fooRes = foo(i);
    if (!fooRes) {
      break;
    }

    st = fooRes;    // null and undefined incompatible type errors are reported here
  }

  return st;
}

test();
```

Even though the fooRes can not be null, at the time of the assignment to st, flow reports an error. The loop is deliberately wrapped in a function, so that foo() wouldn't have access to st.

**Comment by bhosmer** [comment]
@shushz thanks for reporting this! It's a bug that's specific to `const` - will have a fix shortly, meanwhile you can work around it if desired by making (e.g.) `fooRes` a `let`.
