### ISSUE TITLE
If there is a path without a return, undefined should be included in the return type.

### ISSUE THREAD

**Issue by dimvar** [facebook/flow#117]
In this example, we should get a warning that the first operand to minus could be number or undefined.

    function f(x) {
      if (x > 1) {
        return 42;
      }
    }
    f(0) - 123;

**Comment by mroch** [comment]
Fixed in 0.4.0 (https://github.com/facebook/flow/commit/c6457eb11c37f598ccd357e5ff88938d2c0c9411#diff-c600001e37d25814dbc857496fecd26dL4060)

thanks!
