### ISSUE TITLE
Objects do not intersect properly

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1172]
It is my understanding that an intersection (`&`) of two objects is equivalent to merging type declarations of those objects. So in the example below types `A` and `B` should be identical. As the test demonstrates, they are not.
```
/* @flow */

type A = {x: number} & {y: number};
type B = {x: number, y: number};
function test (a: A, b: B) {
  (a: B); // Flow error
  (b: A); // ok
}
```

**Comment by sterpe** [comment]
My problem was something more like this

```javascript
/* @flow */

/* ::
  type Quux = ({foo: string, baz: string} & Array<any>)
*/

const assign /* : Function */ = require('object-assign')

function Q() /* : Quux */ {
  const quux = assign([], {foo: 'bar'})
  return quux
}

Q().foo
Q().baz
Q().push(1)
Q().push('a')
Q().quux // Error !

module.exports = Q
```

**Comment by samwgoldman** [comment]
Thanks, @pasha-mf. Merging this into the issue I created. @sterpe, creating a separate issue for object/array intersection types. Going to track everything intersection related in a new meta-issue.
