### ISSUE TITLE
child_process missing functions

### ISSUE THREAD

**Issue by NullDivision** [facebook/flow#1174]
Apparently not all functions were implemented yet on 0.19.1

```
index.js:5
  5: import {execFile, spawn} from 'child_process';
                       ^^^^^ "spawn" export of "child_process". Property not found in
  5: import {execFile, spawn} from 'child_process';
                                   ^^^^^^^^^^^^^^^ exports of "child_process"
```

**Comment by STRML** [comment]
@NullDivision This is a perfect opportunity for a PR to fix this; see e.g. [similar PRs](https://github.com/facebook/flow/pull/1123/files) that patched node core typedefs..

**Comment by TrySound** [comment]
This looks like fixed
https://github.com/facebook/flow/blob/master/lib/node.js#L314
