### ISSUE TITLE
class declaration does not match error

### ISSUE THREAD

**Issue by smirea** [facebook/flow#1179]
In my local lib I have: 

```
declare class Test {
    foo () : boolean;
}
```

and use it as:

```
class MyTest {
    foo () { return true }
}

const test_method = (test : Test) => {
    test.foo();
}

test_method(new MyTest);
```

it throws the error:

```
 45: test_method(new MyTest);
                 ^^^^^^^^^^ MyTest. This type is incompatible with
 41: const test_method = (test : Test) => {
                                 ^^^^ Test
```

Hoever, if I switch the declaration to an object, it works.

```
declare type Test = {
    foo () : boolean;
}
```

The only problem with the object notation is that I can't take advantage of inheritance or static properties. Any thoughts as to why this is not working as expected?

**Comment by samwgoldman** [comment]
Classes are nominal in Flow, but interfaces are structural. You should be able to use `declare interface` in your local lib to get the behavior you're expecting.

**Comment by smirea** [comment]
wow somehow I missed the `interface` keyword. thanks!
