### ISSUE TITLE
[Windows] Flow for Windows isn't parsing header comment blocks correctly with Haste

### ISSUE THREAD

**Issue by ykagan** [facebook/flow#1188]
We use the Haste module system with flow. Our comment blocks looks like this:
```javascript
/**
 * @providesModule ModuleName
 * @flow
 */
```

Flow for windows isn't parsing these blocks correctly. The following individual lines do work, if they are the first non-empty line in the file: 

```javascript
/* @providesModule ModuleName */
```
```javascript
/* @flow */
```

**Comment by mroch** [comment]
shooting in the dark here, I wonder... are you using Windows line endings? it shouldn't matter but i wonder if we're not accounting for `\r`.

**Comment by ykagan** [comment]
Hmm I don't think that's the problem - the same exact files type check correctly on a Mac. Unless git is doing some kind of text transform magic.

**Comment by mroch** [comment]
git is capable of doing magic like that (https://help.github.com/articles/dealing-with-line-endings/#platform-all), but I haven't tried to repro yet.

one quick option might be to open one of the files in a hex editor to see if the line ends with \x0d\x0a or just \x0a

**Comment by RReverser** [comment]
> git is capable of doing magic like that (https://help.github.com/articles/dealing-with-line-endings/#platform-all), but I haven't tried to repro yet.

Yeah, Git does that on Windows by default unless you have `.gitattributes` or global config set to LF only.
