### ISSUE TITLE
Allow `declare class Foo extends T` when `T` is a type

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#1189]
``` js
/* @flow */

import type Events from 'events';

declare class Foo extends Events.EventEmitter {
  bar(): number;
}

const f = new Foo();
f.on('bar', ()=>{});
```

In Flow 0.20, this gives an error:

```
test.js:5
  5: declare class Foo extends Events.EventEmitter {
                               ^^^^^^ Events. type referenced from value position
  3: import type Events from 'events';
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type Events


Found 1 error
```

Works fine with Flow 0.19.1.

**Comment by avikchaudhuri** [comment]
Please try:

```
/* @flow */

import { EventEmitter } from 'events';

declare class Foo extends EventEmitter {
  bar(): number;
}

const f = new Foo();
f.on('bar', ()=>{});
```

As far as I can tell, the fact that it was working before was a bug.

**Comment by AgentME** [comment]
`import type` has been very useful to me as often I don't want to import a module (so I can avoid its execution and side effects being taken immediately, or so I can avoid increasing the size of a javascript bundle) but the module is still involved in the type signatures. This worked correctly before. I can't see why it wouldn't be intended.

**Comment by runn1ng** [comment]
This bug-slash-feature seems to extend *(no pun intended)* to definition file.

As in, in definition file, I cannot declare one type extending another type, because "type referenced in value position". Even when that makes zero sense in definition file.

See the immutable-js discussion that linked here

**Comment by runn1ng** [comment]
As far as I can tell, you cannot now declare any kind of type hierarchy in the .js definition file, since it is always "type referenced in value position". It seems like a bug to me.

**Comment by samwgoldman** [comment]
As @avikchaudhuri mentioned, it's an error to use a type as the argument to `extends`. This is part of JavaScript class syntax and isn't stripped away by Babel, so using a type there would cause a runtime error.

Let me know if there's something I missed here. Thanks!

**Comment by AgentME** [comment]
I'm using `declare class`. The whole class declaration is stripped away by Babel, so there wouldn't be a runtime error.

**Comment by samwgoldman** [comment]
Oh, I see. I've wanted this in the past, too. Thanks for clarifying!

**Comment by joarwilk** [comment]
Any news on this? Fairly significant bug

**Comment by calebmer** [comment]
It looks like this works now. Let me know if you still have issues 👍 

https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwILwN4F8BQeoSci0q8AQvCAB4AuIAdsGprgWAPaPJ3wBGALkrwAvPAAUjAK4QIwqIwCeASgDceIA

**Comment by Alxandr** [comment]
Isn't this still an issue when the types exist in different modules?

```js
declare module 'foo' {
  declare class Foo {}
}

declare module 'bar' {
  import typeof { Foo } from 'foo';
  
  declare class Bar extends Foo {}
}
```

**Comment by fabiomcosta** [comment]
This is still a bug on v0.132
