### ISSUE TITLE
Can't cast instance of object to type with constructor property

### ISSUE THREAD

**Issue by Macil** [facebook/flow#1190]
I've found myself in a position where I have several classes which each have a static method following the same interface (same name, arguments, and return value). I call this method in a few places that I do not have an instance of the class, so I'm confident it makes sense as a static method.

I have some functions that can accept instances of any of these classes, and then I want to find the class of that instance and call the static method on that class. I can do this via `someInstance.constructor.staticMethod()` fine. Now I want to create a Flow type to describe the `someInstance` parameter so I can make sure that callers can only pass an instance of a class that implements certain methods and certain static methods. I've tried many variations of the following, but it doesn't seem to be supported:

``` js
/* @flow */

type FooInterface = {
  method(): number;
  constructor: Function&{
    staticMethod(): string;
  }
};

class FooImplementation {
  static staticMethod() { return 'abc'; }
  method() { return 123; }
}

const f: FooInterface = new FooImplementation();
f.constructor.staticMethod();
```

```
[chris /tmp/foo]$ flow version
Flow, a static type checker for JavaScript, version 0.20.0
[chris /tmp/foo]$ flow
test.js:10
 10: class FooImplementation {
           ^^^^^^^^^^^^^^^^^ default constructor. Expected object instead of
 10: class FooImplementation {
           ^^^^^^^^^^^^^^^^^ statics of default constructor


Found 1 error
```

**Comment by SamChou19815** [comment]
This kind of dynamic pattern is unlikely to be supported well.
