### ISSUE TITLE
Boolean sentinel not correctly being checked

### ISSUE THREAD

**Issue by JohnyDays** [facebook/flow#1193]
Maybe there's a better title for this, but from my limited understanding of flow, that's what I could come up with.
The problem is the following:
```javascript
type success = { A: string }
type error = { B: string, success: false }
type response = success | error

const result: response = global.anyMethod()
if (result.success === false) {
  console.log(result.B) //Errors when it shouldn't
}
```
```javascript
  8:   console.log(result.B)
                          ^ property `B`. Property not found in
  4: type response = success | error
                     ^^^^^^^ object type


Found 1 error
```

Am i missing something obvious?
This isn't a 0.20 problem, I had it before upgrading from 0.19, I'm actually on a current master built version though.
Thanks a bunch for flow, i've been using it in all my new projects and i'm never looking back. Cheers!

**Comment by zgao** [comment]
Hypothesis: perhaps you would have to put success: true in A? Otherwise some result like { A: 'test', success: false } would fall into type success, since it says nothing about the value of success

**Comment by samwgoldman** [comment]
Boolean sentinels is a TODO (#577), but in this example, due to subtyping, that `response` type isn't sufficient for discrimination on the `success` property. As a counter example, the following statement is legal given the above declarations.

```javascript
var r: response = { A: "hi", success: false }
```

**Comment by JohnyDays** [comment]
Cool! I'll track that issue to look out for it. 
But how would you model this case, where an error response MUST have { success: false } but a successful response doesn't have the key at all? This is pretty common, at least with most apis I've used

**Comment by samwgoldman** [comment]
`type success = { A: string, success: void }` would indicate that the success response doesn't have the key.

**Comment by JohnyDays** [comment]
Does that type definition not mean that the key is there, but it has a null value?

**Comment by samwgoldman** [comment]
Well, you could try it and see, but I realize I've misled you a bit. void is the type of undefined, but if you want to allow omitting the key entirely you need to use the optional object property syntax, e.g. { success?: void }.

**Comment by JohnyDays** [comment]
Cool, I was under the impression that void was null.
I'll try that out when I'm back at work, regardless I'll have to wait for #577. Thanks again :+1: !

**Comment by JohnyDays** [comment]
I was able to do this in the latest version, so closing.
