### ISSUE TITLE
Core library missing Reflect API

### ISSUE THREAD

**Issue by steelsojka** [facebook/flow#1195]
The core class library is missing declarations for the [Reflect API](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect). Is this intentional or on the road map? I can implement a PR if needed.

**Comment by jeffmo** [comment]
Not intentional, just oversight mostly. Please do send a PR if you don't mind :)

**Comment by steelsojka** [comment]
Will do!

**Comment by steelsojka** [comment]
PR https://github.com/facebook/flow/pull/1196
