### ISSUE TITLE
Flow 0.20 regression: autocomplete fails for `this.` expressions from class methods

### ISSUE THREAD

**Issue by mastercactapus** [facebook/flow#1197]
When attempting to autocomplete any member expression with `this.` from a class method, no results are returned.

```javascript
/*@flow*/
class Foo {
  baz: string;
  bar() {}
  hello() {
    this.
  }
}
```

In Flow 0.19.1 you get the following results:
```
$ flow autocomplete 6 10 <test.js
bar () => void
baz string
hello () => void
```

In Flow 0.20.0 no autocomplete entries are returned.
```
$ flow autocomplete 6 10 <test.js
```
As I'm not sure if this is related to #1191 I also tested against latest commit on master (75aeef0 at time of testing) and this issue is still present.

**Comment by mastercactapus** [comment]
In the case that it is helpful; the last commit I found to work is de41e09 the regression seems to have been introduced by commit 831cb1e.

**Comment by avikchaudhuri** [comment]
This might be a general issue with autocomplete of stuff whose types are
type params, and the recent change modeling the type of this as a type
parameter might have triggered the particular problem. Will fix.
