### ISSUE TITLE
Using flow with an application using dependency injection?

### ISSUE THREAD

**Issue by steelsojka** [facebook/flow#1198]
This is a question, not an issue. How do you use flow in an application that is using dependency injection? For my example I will use angular 1.x, but this applies to any dependency injection framework. I have a module with two services in them like so:

index.js

``` javascript
import angular from 'angular';

import MyService from './MyService';
import OtherService from './OtherService';

export default angular.module('myModule', [])
  .service('myService', MyService)
  .service('otherService', OtherService);
```

MyService.js

``` javascript
export default class MyService {
  otherService: OtherService;

  constructor(otherService: OtherService) {
    this.otherService = otherService;
  }

  useOtherService(): boolean {
    return this.otherService.doSomething();
  }
}

MyService.$inject = ['otherService'];
```

OtherService.js

``` javascript
export default class OtherService {
  doSomething(trueOrFalse: boolean): boolean {
    return !trueOrFalse;
  }
}
```

Since the services are imported and registered with the DI, flow doesn't know what an `OtherService` is in `MyService`. One solution was to create an interface file for each of these and put them in the `lib` paths in the `.flowconfig` but this becomes very cumbersome having to rewrite type definitions twice. Is there a solution for this?

**Comment by bassettsj** [comment]
I am having the same issues, would be great to see how we could handle this better.

**Comment by vkurchatkin** [comment]
You can just `import type OtherService from './OtherService';`

**Comment by calebmer** [comment]
The recommended way is to use import type like @vkurchatkin recommends. Let me know if you still have issues 😊
