### ISSUE TITLE
Support declaring the type of `this` like variables

### ISSUE THREAD

**Issue by Raynos** [facebook/flow#1199]
I tried refactoring some of my code that used the `var self = this` pattern

```js
/* @flow */
/*::
declare class Foo {
    foo: number;
}*/

function Foo() {
    var self  = this;
    /*:: var self: Foo = this*/
    self.foo = 42;
    self.bar = 'wat'; // type error
}

var f = new Foo();
```

The above snippet work as expected and tells me that assigning the field `bar` to `self` is a type error.

I wanted to remove the `var self = this;` pattern as it causes v8 to de-optimize (writing a nodejs specific application)

I noticed that there was no way of stating what the type of `this` is in a function. I tried

```js
/* @flow */
/*::
declare class Foo {
    foo: number;
}*/

function Foo() {
    /*:: (this: Foo) */
    this.foo = 42;
    this.bar = 'wat'; // type error
}

var f = new Foo();
```

The above program passes the type checker. I expected it to complain about assignment to the field `bar`.

I tried editing my local copy of flow by changing the parser to allow `var this: Foo = this` however i quickly got stuck in trying to find the right place to put the branching logic.

**Comment by Raynos** [comment]
This could also be implemented in other ways;

like annotating it in the function signature as a "implicit parameter"

```
/* @flow */
/*::
declare class Foo {
    foo: number;
}*/

function Foo(/*::this:Foo*/) {
    this.foo = 42;
    this.bar = 'wat'; // type error
}

var f = new Foo();
```

or a new keyword of choice

```
/* @flow */
/*::
declare class Foo {
    foo: number;
}*/

function Foo() {
    /*:: typethis: Foo */
    this.foo = 42;
    this.bar = 'wat'; // type error
}

var f = new Foo();
```

I would love to contribute this feature with guidance or review it.

**Comment by samwgoldman** [comment]
See #452. All of your examples show the comment syntax. I think it's important we come up with a non-comment syntax for this. Also, I imagine the TypeScript folks are also thinking about this. Whatever happens here should be in line with whatever they're thinking too.

**Comment by mroch** [comment]
thanks, let's consolidate conversation on #452
