### ISSUE TITLE
Feature request: Add a [version] section to config for specifying flow versions

### ISSUE THREAD

**Issue by LegNeato** [facebook/flow#1205]
This would be a good first bug, writing it down here so someone can poke at it if I don't get a chance.

Add a `[version]` section to config for specifying flow versions. It would look something like this in `.flowconfig`:

```ini
[version]
min = 0.21.1
max = *
```

If `flow` sees its version is not in the range, it would bail with an error. The lack of an entry would imply `*` / no version limit.

This would allow teams to state what version of flow they depend on in configuration rather then separate docs.

Not sure how this would work as I think `.flowconfig` is parsed once at startup, but we can start there maybe?

**Comment by gabelevi** [comment]
There actually is a [version] section already supported. It basically just [asserts that you're running the right version of Flow](https://github.com/facebook/flow/blob/8c9e7be995e15dc97b3b64ee9a15fc020e68edb8/src/common/flowConfig.ml#L686). Technically it supports [semver](https://github.com/facebook/flow/blob/8c9e7be995e15dc97b3b64ee9a15fc020e68edb8/src/common/semver.ml) too!

**Comment by LegNeato** [comment]
Ah sweet!
