### ISSUE TITLE
Type Refinements?

### ISSUE THREAD

**Issue by jasonkuhrt** [facebook/flow#1208]
Is there interest/would it be a good idea to consider Type Refinements. My reference for this is [Liquid Haskell](https://github.com/ucsd-progsys/liquidhaskell) ([introduction](http://ucsd-progsys.github.io/liquidhaskell-tutorial/), [demo](http://goto.ucsd.edu:8090/index.html)). It seems that some of the more dynamic parts of JavaScript (which is a lot of it) could be successfully validated at compile time with Refinement Types.

**Comment by avikchaudhuri** [comment]
@jasonkuhrt Aware of that work. Might get to restricted forms of type refinements next year (at least boolean refinements). But it is unlikely we'll be using a SAT solver in the backend, or turn into a general enough theorem prover anytime soon.

**Comment by jasonkuhrt** [comment]
@avikchaudhuri thanks for the clarification. Ok, well feel free to close this issue, or keep it open as a long-term todo... : )

**Comment by calebmer** [comment]
I’m going to close. We will continue to think about this feature 👍
