### ISSUE TITLE
Is the "flux example" up to date?

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1211]
Hello,

I am trying to learn Flux now and I want to use Flow right from the start, so I found the doc here
- http://flowtype.org/docs/react-example.html
- https://github.com/facebook/flow/blob/gh-pages/docs/02-react-example.md

I want to ask, since the file was last updated 1 year ago, what "work-arounds" are still necessary and how much is the example up-to-date in general (since flow moves pretty fast)

**Comment by runn1ng** [comment]
In any way, I *will* try to read along and *will* make pull requests if I see any obvious error. But I would still like to know what part is definitely outdated :)

**Comment by avikchaudhuri** [comment]
Wouldn't be surprised if it was severely outdated. You should use it as no more than a guideline for now, sorry. We plan to set aside quite a bit of time to update docs next half.

**Comment by runn1ng** [comment]
I will ask here, if I may. Since I don't know how many people are reading IRC, also I don't really like IRC in general.

I am trying to get the flux chat to typecheck. I get this, among other errors

    node_modules/fbjs/flow/include/Deferred.js:14
     14: var Promise = require('Promise');
                       ^^^^^^^^^^^^^^^^^^ Promise. Required module not found

Hm. What does that mean? It seems to be an "error" in [fbjs](https://github.com/facebook/fbjs), and for some reason that I don't understand there are some files in `flow/include` in `node_modules/fbjs` (where do they come from? they are not in the git repo...).

Do I have to include node `Promise` by hand? Why is that necessary? What is happening over there exactly? I am a little lost

**Comment by runn1ng** [comment]
Oh, there is some stuff in here
https://github.com/samwgoldman/issue-react-flow-setup
and here
https://github.com/facebook/fbjs/issues/44

but I don't understand it too much.

**Comment by runn1ng** [comment]
Hm. When I ignore fbjs and flux modules, as is recommended in the second issue, all the weird Promise errors disappear.

However, I am not sure if I want to actually do that. The facebook modules seem to be using flow (??? I guess? They have flow folder, but now flowconfig, so I don't know), so I feel like it's the opposite of what I would want, intuitively.

Also, I find it rather ironic, that I have to "remove" one Facebook thing in order to get another Facebook thing to work :)

**Comment by samwgoldman** [comment]
I believe the issue here is that fbjs is using the haste module setting, where, when Flow encounters `require("Promise")`, it searches for a corresponding `@providesModule Promise` (and, in fbjs, Flow will find the module). However, when included in a project that uses node modules (normal outside of FB), Flow tries to find `Promise` within `node_modules`.

Ignoring fbjs is the correct thing to do for now. I would like to find a way to make these modules work "natively" as dependencies in node-based Flow projects. Will consider this further and update in the coming weeks.

**Comment by runn1ng** [comment]
:+1: great! Sorry for so many messages, I was *really* trying to get it to work without ignoring fbjs :) it felt "wrong" to just ignore it

What is `@providesModule` exactly? Is it some internal Facebook thing?

**Comment by runn1ng** [comment]
OK, now I have an issue I don't know how to resolve :disappointed: 

When I don't ignore `flux` module, I get all the errors, similar to `fbjs` errors. (Missing modules etc)

When I *do* ignore `flux`, as you recommend, I get this

    js/dispatcher/ChatAppDispatcher.js:16
     16: var Dispatcher = require('flux').Dispatcher;
                          ^^^^^^^^^^^^^^^ flux. Required module not found

Is this possible to solve?

**Comment by samwgoldman** [comment]
Yeah, you need to declare the flux module (`declare module flux {...}`) and point Flow to your declaration using the `[libs]` directive in the `.flowconfig`. Not ideal, I know. Will look deeper soon.

**Comment by runn1ng** [comment]
Oh ok. Thanks!

**Comment by runn1ng** [comment]
Another question. More general in scope, as I am diving in and trying to understand Flux.

You have a message dispatcher, that sends messages. The messages, in this example, can be general objects, that, in Flow, are handled as union of types.

Now, my Java-ist instinct is.... wouldn't it be better, instead of making a general Payload type and then hitting Flow limitations instantly - because you cannot narrow the union, based on a declared type in the string - wouldn't it be better to incorporate actual class system into all this, first making an "abstract"* Payload class, all the messages would get to be subtypes of this Payload, and then the narrowing in the stores would be "trivial" instanceof?

(*not really abstract, since that wouldn't be possible in JS, and that's probably a good thing)

**Comment by eikeon** [comment]
I've been working on getting flux's flow example up to date; see: facebook/flux#285 and Facebook/flux#336.

Anyone know of an example of flow and flux working together?

**Comment by tdfischer** [comment]
Bump. This still affects me. I can't seem to get flux and flow to work together *at all*.

**Comment by nmn** [comment]
@tdfischer What flavor of Flux are you trying to use. There are a few blog posts online to use Redux with Flow. Not sure about Flux.

**Comment by calebmer** [comment]
I’m going to close this issue since it is about outdated documentation. If you are still having issues with Flux and Flow we encourage you to open a new issue 👍 

I will be updating our types for Redux soon.
