### ISSUE TITLE
bluebird: Required module not found

### ISSUE THREAD

**Issue by henridf** [facebook/flow#1213]
(I'm guessing this must be blindingly obvious but haven't found any answer after searching/googling so here goes...)

I'm using flow on a small node-based project. Flow is finding some npm-installed modules just fine (`require('underscore')`, `require('log4js')`). 

But I've just added bluebird, and `require('bluebird')` gets me a "Required module not found" error. Any ideas what is special about the bluebird package that results in this?

**Comment by teod** [comment]
Try to add /path/to/node_modules/bluebird/* below the [include] in .flowconfig in your project src root.

**Comment by henridf** [comment]
Actually I'd already tried that and it doesn't work. 

What would be really helpful is some description (or pointer to, if i've missed something somewhere) of how flow handles requires/imports and what it automagically does with node_modules. 

As noted above, flow finds other modules in node_modules just fine, without having added that path to .flowconfig.

**Comment by samwgoldman** [comment]
What does your `.flowconfig` look like? I'm assuming that `./node_modules/bluebird` exists?

**Comment by henridf** [comment]
Oooh I see now. I had `.*/js/.*js` which was greedily capturing stuff in node_modules. My bad, sorry for the noise.
