### ISSUE TITLE
Throw refinements(?) not kept through function calls

### ISSUE THREAD

**Issue by JohnyDays** [facebook/flow#1222]
``` javascript
function test(a) {
  if (a == null) {
    throw new Error('Is null')
  }
}

const b: ?any[] = null
if (b == null) {
  throw new Error('Is null')
}
console.log(b.map) //No error

const c: ?any[] = null
test(c)
console.log(c.map) //Property map cannot be accessed on possible null value
```

Not sure if refinement is the right word, is this expected behaviour because of some javascript detail I'm missing?

**Comment by calebmer** [comment]
Yeah, refinements are not kept through function calls 😔

We may add this feature in the future, but it is unlikely. Let me know if you still have questions 👍
