### ISSUE TITLE
Support for expanded export statements

### ISSUE THREAD

**Issue by nevir** [facebook/flow#1225]
It'd be handy to support the expanded `export` syntax as proposed in https://github.com/leebyron/ecmascript-more-export-from (and implemented via [babel's `export-extensions` plugin](http://babeljs.io/docs/plugins/syntax-export-extensions/)

---

For example:

```js
export Thing from './Thing';
```

**Comment by jeffmo** [comment]
Indeed these are on our radar! We're tracking things over in #940 if you want to subscribe to that issue

**Comment by nevir** [comment]
ah, awesome!
