### ISSUE TITLE
libs should be automatically include-d

### ISSUE THREAD

**Issue by nevir** [facebook/flow#1226]
Currently, it appears that files included via `[libs]` are not `[include]`d. 

You can observe this by:
- Making a project that references declarations that are outside of its root (say `../interfaces`)
- Make one of the files in `../interfaces` invalid
- Run `flow`, and see the error
- Fix the invalid file in `../interfaces`
- Run `flow` again, and the error persists, with incorrect lines highlighted

**Comment by calebmer** [comment]
I’m going to close since unfortunately this issue hasn’t gotten much attention 😔

If this is still an issue please reopen!
