### ISSUE TITLE
Cannot declare modules with / in them

### ISSUE THREAD

**Issue by nevir** [facebook/flow#1227]
This fails with a `Required module not found`:

`definitions.js`:

``` js
declare module 'foo/bar' {}
```

`source.js`:

``` js
import 'foo/bar';
```

---

Whereas this succeeds:

`definitions.js`:

``` js
declare module 'foo' {}
```

`source.js`:

``` js
import 'foo';
```

**Comment by TrySound** [comment]
Seems like this works if `definitions.js` is placed in `flow-typed` folder.

This probably can be closed.
/cc @vkurchatkin
