### ISSUE TITLE
Types passed to a higher-order function can get mixed up.

### ISSUE THREAD

**Issue by dimvar** [facebook/flow#123]
Here, Flow warns that boolean and number are incompatible. Also, it warns that we may be passing a string to minus.

```
function app(f, x) {
  return f(x);
}
var call1 = app(function(x) { return x - 1; }, 123);
var call2 = app(function(x) { return x ? 'qwer' : 'adsf'; }, false);
call1 - 5;
```

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by gcnew** [comment]
Is the following another instance of this issue?

```js
function flip<A, B, R>(f: (a: A, b: B) => R): (b: B, a: A) => R {
    return (b, a) => f(a, b);
}

function fconst<A, B>(x: A, _: B) => A {
    return x;
}

const g = flip(fconst);
g(1, "hello"); // error
g("hello", 1); // error
```

**Comment by lukeapage** [comment]
Adding typing to the hof does fix it.

https://flow.org/try/#0FAMwrgdgxgLglgewgAgIYAd0B4AqAaZAVQD4AKEALlJwEoBeYwggDwtosOQG9hlkAnAKYww-FCFLMaAbmABfYADdU-ZFFQAbDQEZkdNJnKRYiCJJrcBw0SmbIAtMm3TkcgtoBMAZhlKVazQ0PPQN0I2h4JHNLIRExZDsAfmQAcgBHAHdBfhTkClTUABMAZxAUlzdkEE1iwV91LV1HAFZpIA

Should this just be closed?

**Comment by SamChou19815** [comment]
Flow decides to require annotation for polymorphic functions a long time ago.
