### ISSUE TITLE
some incompatible instantiation errors - flow error or my error ?

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1231]
Following code produces errors you see below I do personally fail to see what's working with my code if it is an issue with my code.

## `src/scratch.js`

```js
/* @flow */

type None =
  { type: "Effects.None" }

type Batch <action> =
  { type: "Effects.Batch"
  , effects: Array<Effects<action>>
  }

type Run <action> =
  (callback:(result:action) => void) =>
  void

type Task <action> =
  { type: "Effects.Task"
  , run: Run<action>
  }

type Effects <action>
  = None
  | Batch <action>
  | Task <action>

type Selector <item> =
  Array<item>

type Is <item> = (item:item) => boolean
type UpdateItem <item, action> = (item:item) =>
  [item, Effects<action>]

const none = {type: "Effects.None"}
const task = <action> (run:Run<action>) =>
  ( { type: "Effects.Task"
    , run: run
    }
  )

const batch = <action> (effects:Array<Effects<action>>) =>
  ( { type: "Effects.Batch"
    , effects: effects
    }
  )

type Move = <item, action>
  (isMarked:Is<item>, mark:UpdateItem<item, action>, unmark:UpdateItem<item, action>) =>
  (selector:Selector<item>, isTarget:Is<item>) =>
  [Selector<item>, Effects<action>];


export const move:Move =
  (isMarked, mark, unmark) =>
  (selector, isTarget) => {
  const [items, effects] =
    selector.reduce
    ( ([items, effects], item) => {
        const [next, fx] =
          ( isTarget(item)
          ? mark(item)
          : isMarked(item)
          ? unmark(item)
          : [item, none]
          );

        items.push(next)
        effects.push(fx)

        return [items, effects]
      }
    , [[], []]
    );

    return [items, batch(effects)];
  };
```

## `stdout`

```
src/sratch.js:45
 45: type Move = <item, action>
                  ^^^^ item. This type is incompatible with
 52:   (isMarked, mark, unmark) =>
       ^ some incompatible instantiation of `item`


Found 1 error
```

**Comment by samwgoldman** [comment]
You've hit this particular behavior in a lot of different ways! Probably because of the way you prefer separating out the function types.

This ~70 line code dump has the same issue as this:

```javascript
type F = <T>(x: T) => T;
var f: F = x => x;
```

**Comment by cullophid** [comment]
@samwgoldman So is this a bug in flow? 
as far as i can see your example should be valid ?

**Comment by bodyflex** [comment]
@samwgoldman why was this issue closed? is this a bug, has the bug been fixed or is the behaviour expected (I don't see why it should be though)?

**Comment by bradennapier** [comment]
Core Flow team seems to like making comments with cryptic responses followed by closing as if fixed and everyone left asking questions without the question answered.  Documentation is similar --- simple example without really going in-depth into things.  

Classic problem of the people who build it not having patience for people that are trying to understand their product and assuming everyone should either understand it or they are just too stupid to explain it too... getting pretty old - could probably find 50 posts showing unsolved questions like this with non-answers (and most of them are copy and paste of the above actually).

just google "incompatible with some incompatible instantiation" and you will notice almost every person having this issue asks and never gets a reply that answers anything...
