### ISSUE TITLE
[include] in .flowconfig

### ISSUE THREAD

**Issue by iSuslov** [facebook/flow#1237]
Hey, I'm trying to adopt flow for meteor. So far it's good but I have some troubles with:
_first question_ 
Don't find any documentation about `[include]` in `.flowconfig`. I tried to create `lib.js` and put it in `/folder_1`. There Inside `lib.js` is only one line:
`var Random = {};`

In `.flowconfig`:

```
[ignore]
.*/.meteor/.*
.*/.packages/.*
.*/.npm/.*
.*/private/.*

[include]
/folder_1

[libs]
private/types/

[options]
esproposal.class_static_fields=ignore
```

But I still get this error inside my meteor project:

```
server/methods.js:8
  8: console.log(Random.id())
                 ^^^^^^ identifier `Random`. Could not resolve name
```

So what is the purpose of using `[include]`?

_second question_
In Meteor to define global var we need to use this syntax:
`MyVar = "something"`
But flow does not like this:

```
server/methods.js:7
  7: MyVar = 3;
     ^^^^ assignment of identifier `MyVar`. Could not resolve name
```

It's not a big issue since we can define namespace for global vars and declare it. But anyway, is there any other workaround for this?
Thanks!

**Comment by JimmyLv** [comment]
Same problem...

**Comment by Brianzchen** [comment]
Include docs have since been added, and they're for files to parse through for type checking
https://flow.org/en/docs/config/include/ 

This issue is probably looking for defining a global variable as a lib def
https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-global-variable
