### ISSUE TITLE
Sometimes Flow does not take the execution order into account

### ISSUE THREAD

**Issue by dimvar** [facebook/flow#124]
Here, Flow warns about incompatibility of number and string, but prop becomes a string after the subtraction, so there is no warning. This is probably a feature request, since tracking execution order across scopes is difficult.

```
function Foo() {
  this.prop = 123;
}
Foo.prototype.method = function() {
  this.prop = 'asdf';
};
var x = new Foo;
x.prop - 5;
x.method();
```

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
