### ISSUE TITLE
parameterized type aliases not supported ?

### ISSUE THREAD

**Issue by AlexGalays** [facebook/flow#1241]
Trying to make my life easier with shorter type-casting (which cannot be avoided to the type system limitations :p)

If I write :

```js
function y(): any { return {} }
const x = ( y() : { value: number, (arg: number): void } );
x(33);
```
It works.

However, If I create an alias for the above type, the last line no longer typecheck.

```js
function y(): any { return {} }
type Action<T> = { value: T, (arg: T): void };
const x = ( y() : Action<number> );
x(33);
```

The error is : `function call  Expected polymorphic type instead of Default import from blabla`

**Comment by avikchaudhuri** [comment]
@AlexGalays can you paste the whole example with the import? The code above seems to work fine by itself, but from the error message it looks like we're missing an easy case when taking apart imports, so some more information might result in an immediate fix. cc @jeffmo

**Comment by jeffmo** [comment]
Looks like we'll need some more details to help troubleshoot this. It's been a while, so I'm going to close this out -- but feel free to re-open if more details come to light.
