### ISSUE TITLE
property `getBoundingClientRect`. Property not found in Node

### ISSUE THREAD

**Issue by meleyal** [facebook/flow#1244]
Flow flags an error when calling `getBoundingClientRect` on an element:

```js
const rootElement = document.getElementById('root')
const { width, height } = rootElement.parentNode.getBoundingClientRect()
```

```shell
src/index.js:19
 19: const { width, height } = rootElement.parentNode.getBoundingClientRect()
                                                      ^^^^^^^^^^^^^^^^^^^^^ property `getBoundingClientRect`. Property not found in
 19: const { width, height } = rootElement.parentNode.getBoundingClientRect()
                               ^^^^^^^^^^^^^^^^^^^^^^ Node
```

My guess is that flow is suggesting that `parentNode` could be undefined, but in this case it would fall back to `document.body`.

**Comment by rjbailey** [comment]
Try `parentElement`--not all `Node`s are `Element`s, and `getBoundingClientRect` is an `Element` method.

**Comment by mroch** [comment]
thanks @rjbailey, I think that should do it.

@meleyal: please reopen if that doesn't work

**Comment by meleyal** [comment]
Thanks @rjbailey, that worked :+1:
