### ISSUE TITLE
[idea] Port to Flow to JavaScript

### ISSUE THREAD

**Issue by trusktr** [facebook/flow#1246]
I mean, like, uh, how are you gonna encourage JavaScript developers to contribute to, and improve, a JavaScript tool that is written in... OCaml???

Just sayin. :]

**Comment by jeffmo** [comment]
When we started the project we did discuss the costs/benefits of writing in ocaml vs JS very carefully, but after running through that exercise it was clear we'd have to make some kind of trade-off. Ultimately we decided on ocaml (see below) and, in hindsight, there's a very good chance we wouldn't be nearly as far along in progress with Flow as we are if we hadn't gone with it.

We know it makes it a little more difficult to contribute if you haven't written ocaml before, but luckily ocaml really isn't that tricky to pick up! :) (see [https://realworldocaml.org/](https://realworldocaml.org/) if you're interested. Coming from a significant JS background myself, I've really come to like ocaml for what it is)

(1) We had some necessary (non-trivial) infrastructure already written in ocaml for [Hack](http://www.hacklang.org) that we needed to re-use.

(2) OCaml has very stable and predictable performance characteristics. Flow's internals are extremely perf sensitive, so choosing a language and toolchain where we can have highly predictable performance was critical.

(3) OCaml has some language features that are extremely useful for this kind of project (mostly: efficient pattern matching and first-class immutable structures)

Please keep the ideas coming! :)
