### ISSUE TITLE
Objects with non-optional properties cannot be assigned to locations expecting optional properties

### ISSUE THREAD

**Issue by rjbailey** [facebook/flow#1252]
I would expect the following to typecheck:

``` js
/* @flow */

type Foo = {
  foo: number,
  bar?: number
};

export function isBarGreaterThan4(obj: Foo): boolean {
  return !obj.bar ? false : obj.bar > 4;
}

type FooBar = {
  foo: number,
  bar: number
};

const fooBar: FooBar = {
  foo: 5,
  bar: 5
};

console.log(isBarGreaterThan4(fooBar));
```

But Flow emits this error:

```
 22: console.log(isBarGreaterThan4(fooBar));
                 ^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  5:   bar?: number
             ^^^^^^ undefined. This type is incompatible with
 14:   bar: number
            ^^^^^^ number
```

If I remove the `: FooBar` annotation on `const fooBar`, the file typechecks.

If I try to assign `fooBar` to a variable annotated as a `Foo`, the error location isn't even shown, only the "conflicting" type definitions:

``` js
// Replace the console.log statement above with this line
const foo: Foo = fooBar;
```

```
  5:   bar?: number
             ^^^^^^ undefined. This type is incompatible with
 14:   bar: number
            ^^^^^^ number
```

**Comment by samwgoldman** [comment]
You are correct that this should fail, if objects were immutable. However, because objects are mutable, we run into this hazard:

```javascript
type T1 = { foo?: string };
type T2 = { foo: string };

function f(t: T1) {
  delete t.foo; // oops
}

var t: T2 = { foo: "foo" };
f(t); // oops
```

**Comment by samwgoldman** [comment]
Removing the type annotation from the `fooBar` binding in your example works because `fooBar` has no constraints, so there is no hazard. My example would also pass if I removed the `T2` annotation from the `t` variable binding (or passed an object literal in directly).

**Comment by samwgoldman** [comment]
And, to give a sense of what's coming up, the solution to this problem is immutable types. No specific timeline yet, but it's on our radar.

**Comment by rjbailey** [comment]
Okay, that makes sense. These objects were all instances of `Immutable.Record` in my code, so I didn't think about mutation :)

In that case, consider this a bug report for the latter case where the error location isn't reported--that was the error I originally ran into, and I had to fuss around for a bit before I figured out what was going on.

**Comment by samwgoldman** [comment]
Actually, the latter case (if you're referring to the unannotated object not resulting in an error) is not a bug.

**Comment by samwgoldman** [comment]
Oh, you're referring to the error message with this code? I agree we can do better here:

```
// @flow

type T1 = { foo?: string };
type T2 = { foo: string };
var t1: T1 = { foo: "hi" };
var t2: T2 = t1;
```
```
test.js:3
  3: type T1 = { foo?: string };
                       ^^^^^^ undefined. This type is incompatible with
  4: type T2 = { foo: string };
                      ^^^^^^ string
```

**Comment by rjbailey** [comment]
Yeah, that's what I meant. In my case, the type definitions were both in another file, so there was no indication that there was anything wrong with the file where the assignment was happening.

**Comment by samwgoldman** [comment]
Yup. Thanks for the report. Until we can improve the error message, it may help to be aware of `flow check --traces n` where n is a positive integer. That will give you more context.

**Comment by samwgoldman** [comment]
We were holding this issue open because of the bad error message. Our error messages have been improved in master and now we report the following:

```
Error: test.js:22
 22: console.log(isBarGreaterThan4(fooBar));
                                   ^^^^^^ object type. This type is incompatible with the expected param type of
  8: export function isBarGreaterThan4(obj: Foo): boolean {
                                            ^^^ object type
  Property `bar` is incompatible:
      5:   bar?: number
                 ^^^^^^ undefined. This type is incompatible with
     14:   bar: number
                ^^^^^^ number


Found 1 error
```
