### ISSUE TITLE
Multiple Compilation Context

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#126]
Let's say I have the following dir structure : 

```
- src
---myModule.js
---__tests__
-----myModule-test.js
-lib
---forTestAndRuntimeDeclarion.js
---onlyForTestDeclaration.js
```

`myModule` and `myModule-test` will need the definiton of the module  `forTestAndRuntimeDeclariont` however the module `onlyForTestDeclaration` should not be avaible from `myModule`. 
I would like to be able to tell explicitly to flow which definitons is available for which modules.
Perhaps by having 2 declarations folder and 2 separate config in .flowconfig.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nmn** [comment]
Is it OK if I close this issue. Seems like a hard to implement feature with very little value.
