### ISSUE TITLE
How to define custom method of HTMLElement?

### ISSUE THREAD

**Issue by mjj2000** [facebook/flow#1265]
I have a plugin object(ActiveX/NPAPI) and it has a custom method `foo` which is not defined in prototype of HTMLElement. If I get this object by `document.getElementById` then invoke this custom method, errors will occur for flow type checking.

Is there any way to extend definitions of HTMLElement?

HTML:
```html
<object id="my_plugin"> ... </object>
```

JavaScript:
```js
document.getElementById('my_plugin').foo();
```

Flow check:
```console
>> main.js:317,20,64: property foo
>> Property not found in
>>   [LIB] dom.js:361,1,1: HTMLElement
```

**Comment by ooflorent** [comment]
You can define a new type using `class`:

```js
declare class CustomHTMLElement extends HTMLElement {
  foo(): void;
}
```

Or using an intersection:

```js
type CustomHTMLElement = HTMLElement & {
  foo(): void;
}
```

And then use down cast from `any`:

```js
el: CustomHTMLElement = (document.getElementById("foo"): any)
el.foo()
```

**Comment by yeddaliu** [comment]
In my case, we didn't write type annotations in source code, cause build system doesn't support Babel to transform away Flow syntax yet. And we use flow interface files to help type checking.

Regrading the down case suggestion of `document.getElementById()`, it seems no chance to do it within interface file, writing type annotation along with source code turns to a MUST-BE solution.

Fortunately, Flow supports [special comments] (http://flowtype.org/blog/2015/02/20/Flow-Comments.html) to allow writing type annotations without strip them out before running JavaScript.

Here is my implementation.

Flow interface file:

```javascript
declare class CustomHTMLElement extends HTMLElement {
  foo(): void;
}
```

JavaScript:

```javascript
/* @Flow */
el/* : CustomHTMLElement */ = (document.getElementById("my_plugin")/* : any */)
el.foo()
```

**Comment by mjj2000** [comment]
Defining custom type with special comments works!
Thanks all :+1:
