### ISSUE TITLE
PROJECT_ROOT tests fails on OS X

### ISSUE THREAD

**Issue by gf3** [facebook/flow#1266]
Not only do the tests fail, but the feature has never actually worked for me on OS X. I attempted to debug the issue, unfortunately my OCaml isn't strong enough.

<img width="1204" alt="failed_test" src="https://cloud.githubusercontent.com/assets/18397/12245361/12b93cf0-b876-11e5-9ae6-9c0f64758318.png">

**Comment by jeffmo** [comment]
I suspect this might have to do with case-sensitivity on OSX. Haven't had a chance to dig in yet, though

**Comment by jeffmo** [comment]
This appears to be fixed now
