### ISSUE TITLE
Promise.all type confusion

### ISSUE THREAD

**Issue by mrjackdavis** [facebook/flow#1267]
I seem to be having a problem with `Promise.all` and destructuring. I can't tell if it's related to another issue. 

Consider the following

```
/*@flow*/

let a = Promise.resolve('foo');
let b = Promise.resolve(1);

Promise.all([a,b])
  .then(([duck,goose])=>{
    let c = a + b.toString();
    console.log(c);
  });
```

I receive the following from flow

```
scripts/test.js:8
  8:     let c = a + b.toString();
                 ^ Promise. This type is incompatible with
  8:     let c = a + b.toString();
                 ^^^^^^^^^^^^^^^^ string

```

By the look of it, flow is assuming `a` is a promise resolving an integer. I have a feeling `Promise.all` is assuming parameters are of the same type.

**Comment by mrjackdavis** [comment]
Nevermind me; PEBCAK

**Comment by samwgoldman** [comment]
FWIW, you weren't really wrong. The type of `Promise.all` combines the inner promise types to a single union type, which makes using it with heterogeneously typed promise collections pretty difficult. (In your example, both `duck` and `goose` have the type `string|number`, for example.) However, no need for an issue here, as this is a well-known issue and already on our radar.
