### ISSUE TITLE
Getting future reserved word error when using static class properties

### ISSUE THREAD

**Issue by tp** [facebook/flow#1269]
Flow version: `0.20.1`

.flowconfig:
````
[ignore]
.*/node_modules/.*
.*/public/.*
.*/build/.*

[include]

[libs]

[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
````

sample class:
```js
class ToolWithDetailsBubble extends BaseComponent {
  static propTypes = {
    bubbleContent: React.PropTypes.node.isRequired,
    tooltipID: React.PropTypes.string.isRequired,
  }

  static defaultProps = {
    closeOnClick: true,
    bubbleContent: '',
    children: [],
  }

  [...]
}
```

I get the following error which I assume should not be presented because I enabled `class_static_fields`:
```
static defaultProps = {
^^^^^^ Use of future reserved word in strict mode
```

**Comment by gabelevi** [comment]
I think the problem is that you're missing semicolons after your prop initializers. Class properties do not do automatic semicolon insertion. Try

```JavaScript
static propTypes = { ... };
static defaultProps = { ... };
```

The `Use of future reserved word in strict mode` error is probably because, without the semicolon, Flow thinks the `static defaultProps` is part of the first initializer.

Please re-open this issue if my suggestion isn't the right fix.

**Comment by tp** [comment]
True, after updating the Babel version I also get this as warning. Thanks!

**Comment by balupton** [comment]
Adding semicolon hasn't helped:

```
class Stalker extends EventEmitter {
	/* :: static watchers: {[key:string]: Watcher}; */
	/* :: watcher: Watcher; */
```

```
$ flow check
es2015/index.js:128
128: 	/* :: static watchers: {[key:string]: Watcher}; */
     	      ^^^^^^ Use of future reserved word in strict mode


Found 1 error
```

**Comment by balupton** [comment]
Nevermind, was an issue with flow checking the compiled code instead of the source code
