### ISSUE TITLE
Support `extends null`

### ISSUE THREAD

**Issue by bmeck** [facebook/flow#1272]
``` javascript
class X extends null {}
```

results in:

```
class X extends null {
                          ^^^^ null. Expected polymorphic type instead of possibly null value
class X extends null {
                          ^^^^ null
```

used for non-coercible types.

**Comment by samwgoldman** [comment]
Can you give an example of how such a class might behave?

**Comment by bmeck** [comment]
@samwgoldman in what sense of the word, it is essentially an `Object` without `Object.prototype` in the chain.

```javascript
x = Object.create(null);
x+'' // throws cannot be converted to string
String(x) // throws no .toString
Number(x) // throws no .valueOf
+x// throws // throws cannot be converted to number
```

**Comment by samwgoldman** [comment]
So, Flow doesn't catch the errors in your example today. I wasn't aware of that behavior, so thanks for bringing it to my attention. I'll see what we can do there.

However, I don't think your recommended syntax will work. The `extends null` part would be stripped off before runtime, and the runtime behavior of any class instance is that it's coercible. Flow can't change that.

Can I re-title this issue to target the `Object.create` syntax instead, or do you think I'm mistaken about classes here?

**Comment by bmeck** [comment]
@samwgoldman `extends null` should work in the JS spec: https://tc39.github.io/ecma262/#sec-runtime-semantics-classdefinitionevaluation step 6.e.

**Comment by samwgoldman** [comment]
Haha, oops. I'm totally wrong. `extends` is absolutely runtime syntax.

You're right. We get this wrong (and `Object.create`). Thanks for the issue report.

**Comment by adrianheine** [comment]
#1332 might be related

**Comment by SamChou19815** [comment]
The support is now explicitly banned as Flow becomes stricter.
