### ISSUE TITLE
Import function signature?

### ISSUE THREAD

**Issue by donaldpipowitch** [facebook/flow#1277]
Let's say I have an action creator (in Redux) which looks like this:

```
type IncrementSecondAction = { type: string, index: number };
export type IncrementSecondActionCreator = (index:number) => IncrementSecondAction;
export function incrementSecond(index: number): IncrementSecondActionCreator {
  return {
    type: INCREMENT_SECOND,
    index
  };
}
```

And I want to use it like this (as props in a component):

```
import React, { Component } from 'react';
import type { IncrementSecondActionCreator } from '../action-creators';

type Props = {
  incrementSecond: IncrementSecondActionCreator,
  index: number,
  second: number,
};
class DynamicComponent extends Component {
  props: Props;

  componentDidMount() {
    const { incrementSecond, index } = (this.props: Props);
    this.intervalId = setInterval(() => incrementSecond(index), 1000);
  }

  componentWillUnmount() {
    clearInterval(this.intervalId);
  }

  render(): ReactElement {
    const { second } = this.props;
    return (
      <div>
        I count {second} seconds.
      </div>
    )
  }
}

export default DynamicComponent;
```

Why do I need to duplicate the function signature of `incrementSecond` as `type IncrementSecondActionCreator`? Wouldn't it be nicer if I could `import type { incrementSecond } from '../action-creators';` where `type` means to import the signature of `incrementSecond` instead of `incrementSecond` as a function itself?

And why do I need to import my own type while it seems to be fine to use `render(): ReactElement` without importing `ReactElement`?

**Comment by corbt** [comment]
I'm not a flow expert, but I think you should be able to do the following:

```js
import { incrementSecond } from '../action-creators';

type Props = {
  incrementSecond: typeof incrementSecond,
  index: number,
  second: number,
};
```

That way you don't have to export the function's type.

**Comment by samwgoldman** [comment]
There's also an import typeof shorthand, which will avoid the runtime dependency.

**Comment by donaldpipowitch** [comment]
Works great! \o/
