### ISSUE TITLE
Type checking props across React components seems not to work

### ISSUE THREAD

**Issue by janv** [facebook/flow#1279]
I tried to come up with the simplest example possible:

a.js:
```js
/* @flow */
import React from 'react';
import B from './b';

class A extends React.Component {
  render() : React.Element {
    return <B foo={1}></B>;
  }
}

```

b.js:
```js
/* @flow */
import React from 'react';

type Foo = {foo:string};

class B extends React.Component {
  props:Foo;

  render() : React.Element {
    return <h1>{this.props.foo}</h1>;
  }
}
```

See also https://github.com/janv/wtf_flow.

This should warn me about assigning a number to a string prop, but it doesn't. I ran this with React 0.14.6 and flow 0.20.1. I tried variations:
- I changed `class B` to `extends React.Component<void, Foo, Object>` (see [Changelog.md#v0190](https://github.com/facebook/flow/blob/master/Changelog.md#v0190)), 
- I added `static defaultProps:Foo = {foo: ''}` to the definition of B (see same changelog link and https://github.com/facebook/flow/issues/277#issuecomment-132412126).
- I put B and A in the same file

I just can't get this to throw an error and I have no idea what I'm doing wrong.

You can try for yourself by pulling from https://github.com/janv/wtf_flow, `npm install` and `flow check`

**Comment by frankychung** [comment]
I could get https://github.com/janv/wtf_flow to display errors if you add `node_modules/react` folder to your `.flowconfig`'s ignore config. (That way it will use Flow's internal definitions.) Some of us found this out further down in the issue you thread you linked to (https://github.com/facebook/flow/issues/277)

**Comment by janv** [comment]
That works!

Thank you so much

**Comment by davidlygagnon** [comment]
I'm hitting this issue with flow 0.50. I also tried to add .*/node_modules/react/.* to my .flowconfig ignore section but that doesn't seem to work. Has anyone else experienced this lately ?

I'm passing props as generics to the component (i.e.: class MyComponent extends React.Component<void, Props, void> )

**Comment by simonayzman** [comment]
Also facing this issue.

**Comment by asolove-stripe** [comment]
@simonayzman What specifically is happening? In Flow 0.53, some major improvements to component typing happened. If you're not yet on that version, an upgrade is probably in order since this won't be fixed on any older version. If you're already at that version or later, then the cause of the problem is different than the one in this thread.

**Comment by simonayzman** [comment]
Thanks for the update @asolove-stripe! We'll update our RN app to the latest version in October probably, and I'll check back in then.

**Comment by ezmiller** [comment]
I know this thread is old, but I've been having a similar (or the same) problem trying to get type checking to work on an imported component. Have an issue on flow's issues here: https://github.com/facebook/flow/issues/5373

**Comment by davidlygagnon** [comment]
In my case, I had to annotate index.js with flow `//@flow`, then it worked.

**Comment by ezmiller** [comment]
@davidlygagnon: That was it for me too!
