### ISSUE TITLE
Scoped NPM packages fail

### ISSUE THREAD

**Issue by corbt** [facebook/flow#1281]
Flow doesn't seem to properly import [scoped NPM packages](https://docs.npmjs.com/misc/scope).

Example:
```
 14: import ExNavigator from '@exponent/react-native-navigator';
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ @exponent/react-native-navigator. Required module not found
```

When installed, this package is found in `node_modules/@exponent/react-native-navigator`.

I'm using Flow 0.20.1 and npm 3.3.6.

**Comment by corbt** [comment]
Sorry, turns out this was actually due to an error in the `react-native-navigator` package.

**Comment by gleb-lobastov** [comment]
@corbt I'm facing the same issue, could you tell what was the problem with module?

**Comment by difelice** [comment]
@gleb-lobastov did you figure out how to solve this?
