### ISSUE TITLE
Can't fully infer `this.state` in React component class instance method

### ISSUE THREAD

**Issue by chenglou** [facebook/flow#1282]
Flow 0.20.1

``` jsx
class Foo extends React.Component {
  state: {a: number};
  props: {b: number};
  constructor() {...}
  myMethod() {
    this.state; // can't infer type of this
    const {z} = this.state; // but will correctly warn that `b` property not found on state object
    this.props; // can't infer
    const {b} = this.props; // correctly warns
  }
}
```

Tried to infer using `flow type-at-pos`

(Also can't infer `this`, is this normal?)

**Comment by samwgoldman** [comment]
Hmm, so there's a difference between "can't infer" and "can't print type" and, as you've shown, in some scenarios Flow will correctly infer a type (thus errors when extracting the `z` and `b` props), but `type-at-pos` will not print anything useful.

For `this` inside the method, I'd expect `type-at-pos` to print `Foo`. For `this.state`, `{a: number}`. For `this.props`, `{b: number}`. Is that inline with your expectations?

**Comment by chenglou** [comment]
yep

**Comment by asolove** [comment]
The type at pos for this code now seems to be right in flow 0.53.
