### ISSUE TITLE
Display progress when parsing files (x/n files)

### ISSUE THREAD

**Issue by monperrus** [facebook/flow#1286]
starting flow in my $HOME, it then hangs for **long** minutes with:

```
flow is still initializing; this can take some time. [parsing]
```

the reason is that my $HOME contains thousands of folders and files, and I suppose that flow recursively traverses them. By moving `.flowconfig` in a subfloder with nothing else, the issue is fixed.

To avoid this confusing message, I suggest to check what the current folder contains and outputs an appropriate error message.

**Comment by samwgoldman** [comment]
This problem isn't specific to $HOME, but any directory that contains a very large amount javascript source code. I'm not sure there's much value in checking for $HOME.

**Comment by monperrus** [comment]
I agree. Changed the issue title accordingly.

**Comment by mroch** [comment]
What kind of error would be helpful here? Some projects (e.g. Facebook) intentionally have many thousands of folders and files, so this isn't an error IMO.

**Comment by monperrus** [comment]
Not necessarily an error but some feedback.

Something like a progress bar:

Listing JS files .....

Found 6547 JS files

Indexing x/6547 ....

--Martin

**Comment by samwgoldman** [comment]
Seems reasonable to me. Thanks for this feature request!

**Comment by mroch** [comment]
I like this idea.

one interesting wrinkle is that we start parsing files in worker processes while we're still listing them in another process, so we don't actually know how much work there is to do when we would need to start showing this progress bar. we should still show as much progress as we know, but the denominator will increase too.

**Comment by villesau** [comment]
Some progress bar would be really good to make sure flow hasn't frozen or something else funky. Flow has been running now for me tens of minutes in a project and still claiming that "flow is still initializing; this can take some time. [processing] \"

We have relatively large project where some of the files uses flow and some not.

**Comment by SamChou19815** [comment]
We do display the progress in CLI now
