### ISSUE TITLE
Optional object field/function param makes flow bail on every related inference

### ISSUE THREAD

**Issue by chenglou** [facebook/flow#1287]
Flow 0.20.1

```js
type A = {
  a: number,
  b?: string, // problem here
};

let asd: A = {
  a: 1,
  b: 'bla',
};
```

And

```
function func(asd?: number): void {
  console.log(asd);
}
```

Expected: `flow type-at-pos fileName line col` gives the right inference of `{a: number, b?: string}` for asd, and some notation of `optional number` for the second asd.

And I guess likely many other places with optional things?

Can't infer the type of `asd` with `flow type-at-pos. Also makes flow fail to infer every place that uses A, even if you manually assign a type to those places.

Pretty dangerous in practice; I've only caught it 5 commits later. Without the IDE I wouldn't have known that a whole region failed to infer.

**Comment by samwgoldman** [comment]
Thanks for the report. I'm not 100% sure I understand the issue. Can you add the actual and expected outcomes?

**Comment by chenglou** [comment]
Added.

**Comment by mroch** [comment]
did you forgot `// @flow`? it seems to work for me:

```
$ flow type-at-pos ~/playground/test.js 8 6
{a: number, b?: string}
/data/users/mroch/playground/test.js:8:5,8:10
```

**Comment by mroch** [comment]
actually it looks like i was running master, and it repros in 0.20.1. so this may already be fixed.

**Comment by mroch** [comment]
nice, looks like https://github.com/facebook/flow/commit/c99e1994c4be6f54ce460177a39274a3cc8e9394
