### ISSUE TITLE
Add command to look up type by entry name instead of position

### ISSUE THREAD

**Issue by chenglou** [facebook/flow#1288]
(Follow-up thoughts of #1287)

Context: I've been using Flow extensively with Nuclide and the latter's been saving my ass because I can hover over a variable and get the inferred type. Often times I don't know if something's inferred correctly (e.g. bugs with react component's `this.*`, object assignment, for-in, etc.) so I hover over the result and add the type manually if it's not inferred. Sometimes this can fail too, as per the above issue.

For Nuclide users like me this is a somewhat smaller problem than for users of other editors that don't have Flow type hint display; they're forced to use `flow type-at-pos file line col`, which nobody sane would call manually every time they want to check a few types. I understand that this feature's most likely exposed for IDEs, but I was wondering if there can be something along the line of:

```
$ flow type-at-pos file myVariable
Here are all the occurrences of myVariable:
number, 265:22,265:31
string, 312:28,265:37
...
```

Just an example of an interface. For each occurrence of the variable `myVariable`, we output the type, along with the line & column. This way we can check the type by entering the name rather than checking line and column, which also varies across small edits.

**Comment by samwgoldman** [comment]
Thanks for the feature request! I hope you don't mind that I editorialized the title.

**Comment by chenglou** [comment]
Thanks a lot! =)
Though looking up type by entry name was just an example of what I meant. Could be other things, e.g. display all the inferences (yeah no).

**Comment by samwgoldman** [comment]
Definitely easier to take specific feature requests. There's an experimental (read, undocumented and subject to change) command, `flow dump-types` that will just output the inferred type for everything. There are some types that don't print correctly, but often Flow still "knows" the type. There's definitely some work to do here. :)

**Comment by SamChou19815** [comment]
Given that Flow has LSP support, we are unlikely to implement this.
