### ISSUE TITLE
Should check React propTypes

### ISSUE THREAD

**Issue by bsansouci** [facebook/flow#1290]
Hey everyone,

I'm using flow v0.19.1 and have this chunk of code:
```js
/* @flow */

import React from 'react';

const App = React.createClass({
  propTypes: {
    blabla: React.PropTypes.string.isRequired,
  },

  render() {
    const {blabla} = this.props;

    return (
      <div style={{
        backgroundColor: blabla
      }}>
        Hello, world.
      </div>
    );
  }
});

const Bla = <App />;
```

From my understanding this is wrong and Flow should warn against it, but it doesn't say anything.

EDIT: it works on [this tryflow.org](http://tryflow.org/#6d6ed4bff05d142aec1415ae8e1f7fe7)

**Comment by samwgoldman** [comment]
@bsansouci I suspect you need to update Flow. I'm able to see the same expected error output locally, so this must be something that we fixed since 0.19.1. Thanks!

**Comment by bsansouci** [comment]
Mmmh just tried with v0.20.1 and it didn't work.

**Comment by bsansouci** [comment]
I've been investigating a little bit, and found a way to make it work. Turns out, when I remove all of my `node_modules` (including `node_modules/react`) then flow acts properly. I copy pasted this from the tests (which all pass):
```js
/* @flow */

var React = require('react');
var Foo = React.createClass({
  propTypes: {
    bar: React.PropTypes.string.isRequired,
  },
});

var props = {bar: 42};
var blah = <Foo {...props} />; // error bar, number given string expected
```

With no react in my node_modules, flow tells me
```bash
src/index.js:11
 11: var blah = <Foo {...props} />; // error bar, number given string expected
                ^^^^^^^^^^^^^^^^^^ React element `Foo`
 10: var props = {bar: 42};
                       ^^ number. This type is incompatible with
  6:     bar: React.PropTypes.string.isRequired,
              ^^^^^^^^^^^^^^^^^^^^^^ string


Found 1 error
```

Then I simply run `npm i react --save`, then `flow check` again and get:
```bash
Found 0 errors
```

I tried with different versions of react and didn't find one that changed anything. I then tried with different versions of flow. Turns out `v0.18.1` catches those the way it's expected (regardless of `node_modules` being present). I can try to dig deeper and maybe pinpoint a commit after which it stopped working. My guess is that Flow just bails out of checking for some reason.

**Comment by AlexJozwicki** [comment]
I think this is due to the fact that react is not typed right now, and Flow declares every type itself.
Just ignore the module in your flow config

**Comment by bsansouci** [comment]
Ok, I'm going to ignore the react folder itself. I've been hitting a bunch of those issues where Flow will _silently_ fail. Do you guys think that's an issue worth solving? Would you consider a strict mode that would warn against failed inference/checking...?

Thanks for your help!
