### ISSUE TITLE
"Expensive" and "performance-critical" annotations

### ISSUE THREAD

**Issue by jspahrsummers** [facebook/flow#1292]
Could Flow support annotating functions as "expensive" or "performance-critical," to help prevent performance regressions in "hot path" code?

The idea would be that calling any expensive functions from within a performance-critical function should be a warning or error. Even _transitively_ calling an expensive function should generate a warning or error, if that's possible.

**Comment by avikchaudhuri** [comment]
Thanks for this request. At some point we plan to include call graph analysis in Flow, which would capture characteristics of functions that go beyond just I/O behaviors (so not just "what's input, what's output?" but "what could be the effects of this computation?"). At that point we'll be well-poised to support whatever you're requesting, and much more (e.g., what exceptions could be thrown, what state might be touched).

**Comment by jspahrsummers** [comment]
Awesome! :blush:
