### ISSUE TITLE
Check EventEmitter event types in node

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#1295]
It would be nice if flow could check event names used with an instance of EventEmitter. It could work as following:

```js
class MyEmitter extends EventEmitter<'event1' | 'event2'> {}

const emitter = new MyEmitter();
emitter.on('event1', () => {}); // ok
emitter.on('event3', () => {}); // fails
```

**Comment by runn1ng** [comment]
I made this right now for myself. It's not 100% what you want, but it's good enough for me :)

https://github.com/runn1ng/flow-events

**Comment by samwgoldman** [comment]
Yeah, from what I can tell the best way to use EventEmitter in a type safe way is to wrap it up in a small type safe API, as @runn1ng has done.

**Comment by vkurchatkin** [comment]
@samwgoldman the idea is to provide types for node.js APIs. It would be nice if the following worked:

```js
type T<E: ['string', Function]> = {
  on(...a: E): void
}
```

Then we can define emitter as following: `T<['foo', (a: string) => void] | ['bar', (b: number) => void]>`

**Comment by vkurchatkin** [comment]
Closing, the best solution is indeed not to use EventEmitter in your flow code.

Theoretically this can also be achieved by generating `EventEmitter` declarations for specific number of events:

```js
class Emitter2<E1: string, F1: Function, E2: string, F2: Function> {
   on(e: E1, fn: F1): void,
   on(e: E2, fn: F2): void
}
```
