### ISSUE TITLE
Bounded Polymorphism: Incompatible Instantiation

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#1297]
<h3>Why Does 2 Throw an Error?</h3>

The "Bounded Polymorphism" blog post does not cover this example & I cannot figure out why #2 throws (http://flowtype.org/blog/2015/03/12/Bounded-Polymorphism.html).

Is this a bug or am I missing something? Can I not access the "T" type within the scope of the function?

    type MyType = {
      name: string;
    }

    function yourFunction(arg: MyType): MyType {    // #1
      var stashArg: MyType = arg;
      return { name: 'hello', hiddenExtra: "" };
    }

    function myFunction<T: { name: string }>(arg: T): T {    // #2
      var stashArg: T = arg;    // <— Error
      return { name: 'hello', notHiddenExtra: "" }
    }

<b># 2 Throws:</b>
object literal: /Users/mwalkerwells/Dropbox/Development/Web/helped/js/components/Column.js:40
This type is incompatible with
some incompatible instantiation of `T`: /Users/mwalkerwells/Dropbox/Development/Web/helped/js/components/Column.js:38

**Comment by pasha-mf** [comment]
Running your code I get an error in the "return" line, not in `stashArg` assignment (with Flow 0.20.1, build `8916982845f5a4fd5f412a77c04cf4319e5be01f`).
The error is correct: what you return is not necessary of type `T`. For example, you could have had `T = {foo: string, name: string}` which satisfies the constraint on T, however the return type clearly has a different signature.

**Comment by mwalkerwells** [comment]
Sorry for being so late on this & thanks for your response. I still find it strange that removing the return type (and relying on type inference) works though. :/

```
// Error / Relies on static return type T
function myFunction<T: { name: string }>(arg: T): T {    // #3
  var stashArg: T = arg;
  return { name: 'hello', notHiddenExtra: "" }
}

// No Error / Relies on Type Inference
function myFunction<T: { name: string }>(arg: T)  {    // #4 
  var stashArg: T = arg;
  return { name: 'hello', notHiddenExtra: "" }
}
```

**Comment by mwalkerwells** [comment]
For those who find this, here is a good explanation: https://github.com/facebook/flow/issues/2194
