### ISSUE TITLE
 Function cannot be called on exception

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1303]
Here is a contrived example:

### `result.js.flow`

```js
/* @flow */

export type Result
  = {type: "Ok"}
  | {type: "Error"}

export type ok = () => Result
export type error = () => Result
```

### `file.js`

```js
/* @flow */
import * as result from "./file"

export const ok:result.ok =
  () =>
  ({ type: "Ok"})

export const error:result.error =
  () =>
  ({ type: "Error" })

export type Result = result.Result
```

### `user.js`

```js
/* @flow */

import * as Result from "./file"

const a = Result.ok()
```

### `stdout`

```
user.js:5
  5: const a = Result.ok()
               ^^^^^^^^^^^ call of method `ok`. Function cannot be called on
  7: export type ok = () => Result
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ type `ok`. See: result.js.flow:7


Found 1 error
```

So I do understand the issue here is that flow expects me to define function annotations in `.flow` files differently more like:

```js
declare export function ok () : Result
declare export function error () : Result
```

But then I can't use `ok` an `error` as type declarations. I do find whole another set of declarations to be redundant harming flow's usability.

Same thing can be defined in multitudes of ways

```js
type Box <a> = {
   map <b> (f:(a:a) => b): Box<b>
}
```

```js
type Box <a> = {
  map: <b> (f:(a:a) => b) => Box<b>
} 
```

Above `Box` can also be defined as `interface`:

```js
interface Box <a> {
     map <b> (f:(a:a) => b): Box<b>
}
```

or like:

```js
interface Box <a> {
     map: <b> (f:(a:a) => b) => Box<b>
}
```

Is there any chance that all these forms of expressing conceptually same idea could be reduced to single form ? Is there really needs to be a different syntax for interface files and type definition files ? I would personally suggest to reduce all function signatures to a single one:

```js
type map = <a, b> (f:(a:a) => b, Box<a>) => Box<b>
```

for the following reasons:

1. Other than `type map =`  type signature is a one that you have to use for callback arguments type definitions anyhow.
2. If is more composeable due to aliasinig: 
    
    ```js
    type Mapper <a, b> = (a:a) => b
    type map = <a, b> (f:Mapper<a,b>, Box<a>) => Box<b>
    ```

3. It's related to above point, but aliases can be used for methods unlike other forms:
    
   ```js
    type MapMethod <Box, a> = <b> (f:Mapper<a, b>) => Box<b>
    type Foo <a> = { map: MapMethod<Foo, a> }
    type Bar <b> = { map: MapMethod<Bar, a> }
    ```

**Comment by samwgoldman** [comment]
OK, so I can see that you're trying to use `.js.flow` files to achieve your goal from #838, but that's not the intended use. The error message here is correct and I can't see any issue here.
