### ISSUE TITLE
Spread operator doesn't work with tuples

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#1307]
This doesn't work:

```javascript
type T = {
  x(...a: [string, number]): void
}
```

Outputs: `tuple type. rest parameters should be an array type, got a tuple type instead`.
It makes sense, but it would be nice if it worked.

It breaks completely if you make type parametrised:

```js
type T<E: ['string', Function]> = {
  x(...a: E): void
}
```

Outputs: 

```
Did not expect BoundT:
Called from file "list.ml", line 84, characters 24-34
Called from file "list.ml", line 73, characters 12-15
```

Flow version 0.20.1.

**Comment by trevorr** [comment]
A related problem is that spreading a tuple as arguments seems to yield each argument being a union of the tuple types, rather than the respective types:

```
function g(s: string, n: number) {
    console.log(s, n)
}
function f(m: Map<string, number>) {
  for (let e of m.entries()) {
    g(...e)
    // g(e[0], e[1]) <-- no error
  }
}
f(new Map([['a', 1], ['b', 2]]))
```

```
  4: function f(m: Map<string, number>) {
                       ^^^^^^ string. This type is incompatible with
  1: function g(s: string, n: number) {
                              ^^^^^^ number

  4: function f(m: Map<string, number>) {
                               ^^^^^^ number. This type is incompatible with
  1: function g(s: string, n: number) {
                   ^^^^^^ string
```

**Comment by vkurchatkin** [comment]
> A related problem is that spreading a tuple as arguments

This makes sense, since spread works with iterables, so it has to treat all elements as the same type

**Comment by trevorr** [comment]
Are you saying that tuple support is only intended for element access, and in all other cases they're treated as arrays? Re-reading the [docs](https://flowtype.org/docs/arrays.html#tuples), I suppose it does imply that (if spread is not considered element access):

> Given types T0, T1, …, Tn, a tuple type [T0, T1, ..., Tn] is an array. That array has a general type Array\<T0 | T1 | ... | Tn>, but Flow also understands that accessing the element at index n will evaluate to the specific type Tn.

**Comment by vkurchatkin** [comment]
> Are you saying that tuple support is only intended for element access

I guess so. I think technically it could be done, but it also makes sense to live it as is. Iterating over tuples is wrong semantically, so they are treated as arrays

**Comment by trevorr** [comment]
I think we're viewing spread differently. I don't view it as iteration, even if that's how it's implemented. In these contexts, we're unpacking the tuple into its constituent elements. There's a one to one mapping of a fixed number of tuple elements to a fixed number of function arguments. By contrast, iteration generally deals with an arbitrary number of elements. To me, it seems very natural to use spread with tuples.

But I agree that it's not wrong as it is; this is just a feature that's not supported. I haven't profiled it, but I could also imagine spread being less efficient than explicit element access for small tuples, in which case flow is encouraging me to write faster code. 😃

**Comment by vkurchatkin** [comment]
>  I could also imagine spread being less efficient than explicit element access for small tuple

It most definitely is

I think semantically you should use spread if you define arguments as `...rest: Array<>`
