### ISSUE TITLE
Issues with importing a package from tests

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1311]
My typical package that uses flow is set up in a following manner:
1. My `src` folder contains all `file.js.flow` & `file.js` files.
2. During build step all `src/*.flow` files are copied over to `lib` and `src/*.js` files are compiled via babel and also stored in `lib`.
3. `package.json` main points to `lib/some-module.js`.
4. In my package tests I import package as `import * as MyName from '..'`.

Now the problem is once build is made flow will try to type check `lib/*.js` files and error as babel does not strips `flow comments` that I happen to use, but does strip out `@flow` comment at the top of the file.
But given that I don't actually want flow to analyze `lib` folder I can add `.*/lib/.*` to ignore section of `.flowconfig`. But than flow fails to find imported package from the tests.

Only thing that works for me is to add a name_mapper like:

```
module.name_mapper='../../package-name' -> './src/main-module-name.js'
```

But that's not a great solution as it varies from package to package and honestly I'd rather avoid extra configuration for this.

Is there any better solution ? I really wish I could override `main` just for flow in `package.json` like requested in #932

**Comment by samwgoldman** [comment]
To make sure I understand... in your test you `import * as foo from ".."`, where `".."` is the project root. Flow notices that's a directory, searches for a `package.json` file, finds one, parses out the `main` and therefore picks up the compiled source from `lib` instead of the one you want, which is in `src`.

However, if you have a `.js.flow` file in `lib`, as you say, Flow should pick that up instead, and you should be good to go.

I think what's happening here is you're doing something funny and using type annotations in both the `.js` and `.js.flow` files, like what you showed in #1309. If that's the case, I think you might have to find your own workaround because that's not how we intended that feature to be used. One thought on that workaround: just kill `lib` before you run tests. You only need to build when you're about to create a npm package.

**Comment by Gozala** [comment]
The actual problem is that flow just eagerly type checks all the `.js` files it can find in the package, which is problematic as soon as you have interdependent packages that use flow. Let me break it down:

1. Package that uses flow needs to compile it's actual source to JS that can run natively in node / browser. In my specific case compiled JS files and `.js.flow` files are aggregated in the `./lib` directory.
2. Given that `lib` contains compilation artifacts I don't want flow to type check that. Especially because there are babel bugs that cause flow to choke, but regardless I think it's reasonable to not want to type check compilation output.
3. To avoid type checking compiled artifacts users only options is to put compilation output directory into  ignored path in `.flowconfig`.
4. In `package.json` you do want to point main to compiled source so that users can load your package just by requiring it's name.
5. When you test your package you want to test your package as users would have consume it. So you import `..` (your package root) and assume that flow would look at `./lib/index.js.flow`  but instead flow fails to find imported module because `lib` is ignored.

This issue is even more complicated when your project depends on other project that has similar setup. Because again, flow will eagerly try to type check everything including `./node_modules/dependency/lib/index.js` even if `./node_modules/dependency/lib/index.js.flow` exists. That is problematic because:

1. Flow is very slow if you use type unions or polymorphic functions.
2. Because compiled output can also fail type checking given a bugs in babel. 


I think flow should just let user choose a source directory and type check that. It can follow up dependencies from the source but then if there is `.js.flow` for that dependency it can just use type information instead of attempting to type check other files.

You did mentioned `PROJECT_ROOT` in #932 which I'll try to learn more about to see if that can be used to configure flow such that it will only type check source files.

**Comment by Gozala** [comment]
So as far as I can tell `PROJECT_ROOT` maybe used to mitigate issues with in the package bounds, but as soon as you package is used by other, that other user winds up with the same set of problems as described above unless it carefully ignores certain paths and maps others.

**Comment by calebmer** [comment]
I’m going to close because of inactivity. If this is still an issue and you still need help, please let me know!
