### ISSUE TITLE
Type Annotation Comments not Working

### ISSUE THREAD

**Issue by jacobp100** [facebook/flow#1320]
# Input
```js
/* : string */
export const x = 4;
```

# Expected
Warning or error about this being invalid

# Actual
```
src/util/index.js:41
 41: /* : string */
     ^^^^ Unexpected token /* :
```

# Info
Flow, a static type checker for JavaScript, version 0.20.1
Node v5.5.0
Ubuntu 14.04

**Comment by Gozala** [comment]
@jacobp100 you're expected to use annotations as follows:

```js
export const x/*:string*/ = 4;
```

**Comment by samwgoldman** [comment]
Thanks, @Gozala.

**Comment by jacobp100** [comment]
Sorry, you're correct for that example. However, in the flotate project, this syntax was possible for functions.

```js
/* : (fn: string, message: number, value: Object): number */
export const assert = curry((fn, message, value) => {
  if (!fn(value)) {
    throw new Error(message);
  }
});
```

This should be throwing exceptions about types, but I get the same syntax error. Was it intentional to not include this format?
