### ISSUE TITLE
Support indexable signature for class declarations

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1323]
We support indexable signatures in interfaces and "declare class" but not real class declarations.

``` javascript
class C {
  [key: string]: number;
}
var c: C = new C();
c[""] = 0; // OK
c[0] = 0; // error
c[""] = ""; // error
```

**Comment by STRML** [comment]
Could we also add `mixins` support to classes and not just class declarations? Otherwise certain patterns are very awkward as you essentially have to create class stub files just so you can mixin an interface.

**Comment by chrisui** [comment]
@samwgoldman I might be missing something here but the "declare class" syntax does not seem to work for me. Any ideas?

Ie. https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAJgUwMYwIYBOmYueAzmWAKIB2ArgLYA8AygFxgDyARgFY4AXAHxgA3qjBgA2gGtMATw5kBBAJY0A5gF0OeGvIDcEknBrKCdbALgEAFGQ4sAlBwBucVeiOSADgTg+mAQCqpgOXHyC3mCueDB0YRwAggQEePJMevJCRgC+qKjYpspgeGAAvGA0mEi0jLaiACpULI0cAIy5TkaoeAB0fgFBIWFG-bHxo719za09QA

**Comment by StarpTech** [comment]
Hi, what's the status ? Thanks!

**Comment by gabro** [comment]
as a temporary (and ugly) workaround we can do

```js
class C { foo: number }
const key = 'foo';
const c = new C();
(c: Object)[key] = 42; 
```

**Comment by indiescripter** [comment]
Just ran into this very issue minutes ago so it's a genuine use case.

In my particular situation I am using the new "implements" feature to implement an interface which has an indexable signature. Flow complains about my class which implements such interface with:

property `$value` of Foo. Indexable signature not found in.

**Comment by raould** [comment]
Is there a nice, succinct way to use the "ugly workaround" when we're doing all our flow stuff via comments?

**Comment by STRML** [comment]
You can also use this (ugly) hack, but it will break on class property assignment:

[Flow Try](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwBrwN4Ch7wBcBLAWxGQKhIAcAueAESgJBwF8cB6AKlvtCRx43Tomip4AMQD20+Dz7wSRAB5EAdmkwjseeb1oBtANYgAnvQowNAcwC69dQFcSAIxAwA3CPY4w0zQJ4KHgAXnh1EAB3KVkACgBKTz8AigiXRxd3GDDggDpXWE95UScACwAaeA8YaRgAfhTA9JIAJky3D1yoQwByQpheu2LOUXVpIKh1aphamCa0q0sCa3UbboKoAC8R0Rq6nCg84jIKKmpj6QAZaTAoCBAAZRXbRN2IieDp-ZggA)

[Babel REPL](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code=declare%20class%20X%20%7B%0A%20%20timestamp%3A%20Date%0A%7D%0A%2F*%3A%3A%20declare%20*%2F%20class%20Foo%20%2F*%3A%3A%20mixins%20X%20*%2F%20%7B%0A%20%20%2F*%3A%3A%20%5Bkey%3A%20string%5D%3A%20number%3B%20*%2F%0A%20%20fn()%20%7B%0A%20%20%20%20return%201%0A%20%20%7D%0A%7D%0Aconst%20a%20%3D%20new%20Foo()%3B%0Aconst%20num%3A%20number%20%3D%20a.bar%3B%20%2F%2F%20uh%2C%20error%3F%0Aconst%20num2%3A%20number%20%3D%20a%5B'bar'%5D%3B%20%2F%2F%20not%20an%20error%0Aconst%20str%3A%20string%20%3D%20a.baz%3B%20%2F%2F%20error%0Aa.timestamp.toLocaleString()%3B%20%2F%2F%20not%20an%20error)

```jsx
declare class X {
  timestamp: Date
}
/*:: declare */ class Foo /*:: mixins X */ {
  /*:: [key: string]: number;*/
}
const a = new Foo();
const num: number = a.bar; // uh, error?
const num2: number = a['bar']; // not an error
const str: string = a.baz; // error
a.timestamp.toLocaleString(); // not an error
```

**Comment by mhagmajer** [comment]
+1

My workaround:

```js
interface Indexable {
  [key: string]: string
}

class MyIndexable implements Indexable {
  $key: any;
  $value: any;
  ...
}
```

works just like the one below should

```js
class MyIndexable {
  [key: string]: string;
}
```

except `myIndexable['prop']` is fine but `myIndexable.prop` isn't.

**Comment by sibelius** [comment]
any progress on this?

can somebody point in out where is the code related to fix this?

**Comment by dhoulb** [comment]
Question for the Flow devs:

The `$key` / `$value` syntax on classes isn't documented but seems to work great (with and without the interface measured above.. Is there any danger of this being removed somewhere down the line? 

I'm finding it very useful but I'm not sure whether to rely on it? I suppose it'll be replaced by `[indexer: string]` syntax at some point?

```js
class MyClass {
  $key: number;
  $value: boolean | number;
}

const myObj = new MyClass();

// Works correctly!!
(myObj[1]: string | number);
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCyBPAYQ21AG9FRQASAawFN8AuUAOwFcBbAI3oCcA3JRoA3dNHb0W3WLGj10rUAB82XXoMQBfZClitMAF1Cd8AeW4ArUAF429eHiIlMACgCUQxCFAB1WHy0OIAm5IDwfwCE4YiuphaWANoAjAC60rLyiipqPPyeQA)

**Comment by samwgoldman** [comment]
Yes, there is imminent danger of this being removed.

It is unlikely that we are going to support this in the near term. We are working toward a model where the layout of instances are more precise, and this looseness would be problematic.

For example, the indexer might shadow properties on a superclass.

The better choice here is to create a `data: { [K]: V }` field in your class instead of making the instance itself a dictionary.

**Comment by soulofmischief** [comment]
I thought I'd share a case where this kind of behavior is ideal:

[In this example](https://flow.org/try/#0MYewdgzgLgBMAWBDMYCmAbCMC8MDaMA5AE6EA0RA5uUQEaEwC6AUM6gB4AOIxsw6iCFgDCIdDxgBvZjBgASANaoAngC4Y0YgEswlGfIBuidAFdU6sCYC2tVMVaziF67fuzKzm3f21Prh3DgmibAUDwAFPqOfnZkUTAeMJZexHGysr5JLt6yAJRS8QDytABWqKEAdIIQWpRg4TBQ8FoQFJIwqQkUtDAAvrn6vQGIACYjDcDqouLEMPnS6R2oUCbEYEmoAO4w0xEV+wjIaJgVVoicE0goGDgAfPGyAPSPMAAyWlZasEamqFhhMAAjA8YABZRBNU46BpNFoEQ7XdBMGAAajg8KuxyYFEBc3iuQGsiG+isJnQUC0nHQygaEGAxkQTiyKTmBUWxGWq3WaG2u2IDX2FQRxwgp3OlyON2w90WTxewgEVk4MB+Ziwtigm1QqHWAAYALSAiog8GQs7sBqm+BQ+qNZoQDGSpGMGAAKg09IEnV1cwoPsJ6QJg2YvSAA), we have a simple class making use of array methods to dramatically shorten LOC and bug surface.

If support for

```
$key: string
$value: number
```

were dropped, the class would need to be reworked to scope the `r`, `g` and `b` properties under something like `values`, and property access would take the form of `Color.values.x` vs `Color.x`, which in my opinion is clumsy for such a simple use case and is behavior I would seek to avoid when writing some libraries.

I agree that using the key/value definitions is a hacky approach and would prefer something more standardized and streamlined for cases like the above.

**Comment by STRML** [comment]
@samwgoldman Is there still imminent danger of this being removed? It is very useful to us as `$key: string` and `$value: mixed`, forcing the developer to check the type of what he uses but making many common use cases not outright type errors forcing a `$FlowIgnore`. In total, adding it to some of our base datastructures has made our code more sound.

**Comment by pulli23** [comment]
Is there any update on this?

**Comment by samwgoldman** [comment]
We have no plans to support this right now, as the indexable signature is overly loose and particularly dangerous when combined with subclassing / prototype chains. Flow has no way of knowing if a `[string]: T` indexer will shadow a method defined in the class itself or any of the methods / fields defined in the superclass.

The $key/$value hack will be removed, although the timeline is unclear. This was an internal implementation detail (a hack) that was never meant to be user visible.

The better choice here continues to be a `data: {[K]: V}` indexer type.

**Comment by goodmind** [comment]
@samwgoldman is it at least possible to fix this on `declare class`? https://github.com/facebook/flow/issues/4014
