### ISSUE TITLE
Custom ast processing?

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#1324]
I'd like to process flow AST and export it in certain format (for example generate metadata for runtime). Example:

```
//a.js
class A {
    x : string;
    y()  : number {};
}
```
and I base of this I'd like to achieve generated code:
```
//a_metadata.js
MetadataContainer.register(A, {
    x : {memberType: "field", type : "string"},
    y : {memberType: "method", signature : {returns : "number"}}
});
```

Is there a way to achieve something similar to this? Or is there a possibility to add a custom processor for flow ast, to achieve this?

**Comment by samwgoldman** [comment]
@vaukalak You can run `flow ast a.js` to generate a JSON representation of the AST. You can also use the `flow-parser` npm module to get at the AST. From there, you can write a program to generate code however you like. Let me know if that doesn't solve your problem.

**Comment by vaukalak** [comment]
@samwgoldman yes, thanks a lot.
