### ISSUE TITLE
Object type spread

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1326]
It would be nice to be able to spread an existing object type into another one:

``` javascript
type A = {
  foo: string,
  bar: number,
};
type B = {
  bar: boolean,
};
type C = {
  ...A,
  ...B,
};
```

In the above, `C` would resolve to `{ foo: string, bar: boolean }`.

This is different from intersection types. With intersection types, `A & B` becomes something more like `{ foo: string, bar: number & boolean }`, which the observant reader will notice is uninhabitable.

**Comment by STRML** [comment]
This would be incredibly useful to us, we extend types all the time just for arguments. This is really nice if a function has defaults, but then we want all functions called by that to actually have a proper object with all missing attributes filled in. A simple use case:

```js
type OptionsInput = {
  a: number,
  b: ?string,
  c: Date
};

type FnOptions = {
  ...OptionsInput,
  b: string
};

function foo(opts: OptionsInput) {
  if (!opts.b) opts.b = 'some default';
  doSomethingWith(opts);
}
```

**Comment by vkurchatkin** [comment]
@STRML in this case intersection should probably work

**Comment by STRML** [comment]
@vkurchatkin It doesn't. For example, I'm intersecting such an optional property with a required property:

```js
 16:   keys?: Array<string>,
              ^^^^^^^^^^^^^ undefined. This type is incompatible with
 22:   keys: Array<string>,
             ^^^^^^^^^^^^^ array type
```

**Comment by egauderman** [comment]
Another thought: Even in cases where intersection would work, the spread syntax would enable an easier-to-read shorthand.

For example, to include common types in a disjoint union:
Currently, with intersections:
```js
type Todo = {
  id: string,
  text: string,
};

type Action =
  | (
    {
      type: 'CREATE_TODO',
    } & Todo
  )
  | {
    type: 'DELETE_TODO',
    id: string,
  }
;
```
With spread:
```js
type Todo = {
  id: string,
  text: string,
};

type Action =
  | {
    type: 'CREATE_TODO',
    ...Todo,
  }
  | {
    type: 'DELETE_TODO',
    id: string,
  }
;
```

**Comment by STRML** [comment]
Any status on this? This would be a huge help in defining so many types.

**Comment by kamek-pf** [comment]
This would be useful to type database schemas.

Depending on how you perform queries, a field that represent a relationship with another table / document may return an id or an object (if you're asking for a join).

```
type Client = {
    id: string,
    name: string
};

type Campaign = {
    id: string,
    name: string,
    client: Client | string // <- this
};
```
This works, but forces you to check the type of the `client` field at run time. It feels awkward because you already know what this is going to be depending on what your query looks like.
I'd rather handle that sort of things on a case-by-case basis, something like that :

```
export type Campaign = {
    id: string,
    name: string,
    client: string
};

// somewhere else in the code, when querying Campaigns and populating the client field
import type { Client } from '.....';
import type { Campaign as CampaignBase } from '....';
type Campaign = {
    ...CampaignBase,
    client: Client
};
```

Would love to hear how you guys handle database / ORM stuff.

**Comment by guigrpa** [comment]
Any update on this? It would be very useful to handle the very common use case described by @STRML

**Comment by mtford90** [comment]
👍

**Comment by conartist6** [comment]
Another note on the usefulness of this feature: currently using intersection types the resultant errors can be rather indecipherable, displaying full lists of all the intersecting types. Simplified error messaging for spreads should be possible, given that a type mismatch will now be traceable to a single concrete property definition and never to something strange like an uninhabitable union, which is a problem that is fundamentally split between definitions in two locations.

**Comment by conartist6** [comment]
I'm thinking of trying to tackle the code for this. Does anyone have thoughts about what the limitations of the spread operator should be?

**How should it treat a spreaded object type that has an indexer or a callable?**
Current thought: It should ignore callables and indexers.

**Should it be able to spread unsealed object types? What should the behavior be?**
Current thought: I have no idea. Example with intersections: https://flowtype.org/try/#0C4TwDgpgBAIhBmBDArgG2ABQE4HswGcoBeKAbygAtF84k1gAuKAIxx1QkQDsoBfAbgBQggMY4u+YFCwQAjsTKCBg0JCgBJLsAhYuiVNjyEStFOkMEoAMiiqIOeNLlDBM2QDoR+1M0QiA1grwyFwiwACW4gAUAJRkym7uSAAeCgBEAKxZALRZGbl5aS4AbohYthCSUAya2rr6FsaKUFBeqD5+-kzBoRHRcaS8ADSCAPSjLSlMAOTTIy1UNAhmjLZYyBBK-EA

**Should it be able to spread intersection of object and/or union of object types?**
Current thought: Being able to spread intersections of objects would help people who have been making do with intersections while waiting for the type spread operator. They are after all mostly identical operations if executed on objects with fully disjoint sets of properties. If the user wants the behavior that could ostensibly result for spreading a union, they should instead spread all the constituents of the union individually.

**Comment by bgw** [comment]
@conartist6, I think you can do something like `{...?DefaultProps}` today with

```
type DefaultProps = {callback: function};
type OptionalProps = $ObjMap<DefaultProps, <V>(v: V) => ?V>;
```

But you need to watch out for #2674.

**Comment by conartist6** [comment]
That was one of the first things I looked at, but it is actually not correct! The problem is that it is creating optional values not optional keys.

https://flowtype.org/try/#0C4TwDgpgBACgTgezAZygXigbwFBSgMwQQC4oB+ZYOASwDsBzbAXwG5tsBjAGwENlUAwggC2YKBAAewCLQAmqAEoQeHYABIhohLRnAAPADcE1WQBpYiFOaMmAfFibtO2ylGmuMezWID0tlkA

**Comment by STRML** [comment]
This seems [good to close](https://flowtype.org/try/#0C4TwDgpgBA8mwEsD2A7AzgSRWArsKAvFAN4BQUUAhgFxQo4C2ARhAE4A05UTtawrCFAHNOFAMa0AIpWARSAXwDcpUqEhQAYijiJUaQiS4A6EzuTosuYKO60A-HwHCbAE179BQhctIAzHChiuihQvkhIABRI8Gi0ZnqWeACUJPIq-oHB3JSsUTG0WvHoKcRpfuERxDRQAIzstlAA5GFIjfUSdBAA7lDSshFJ8knKLZXVdQ30ADZT7bQo3b0yEANDilAA9BtQEAAekEEQLipMOWO0EzxNLW1QHQs9fStJ9W7X4Y1rpKe5VRf1V2mszu80WTwGr1ozQ+a022xQSB2rFYSFYAEJvmc-rUAfMcDM5p1HstVsM4Tt9hBDi4kawgA)!

**Comment by seveibar** [comment]
This may need to be reopened,

I don't think the current implementation is what @samwgoldman proposed- [see this example](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUBmB7LAuKAzsAE4CWAdgOYA0aUARgIbH7kCuAtvRMbQL4BuFKEhQAQgmR0mLBjgA2ERuX5CR0AMKTU6AHT6YtPfrGq6KAPQWoWggAssbeQBMoxCASzyAbtGBZkTBx8IjIqagZmfHoFJXIoPnNFYCgKIhhcOEQkILwoAHI7CHl5LHyImXwARgAGBKEUAGMsck9FXVLKAAo04BhdbCxdfwAZLAB3Hg1GAggugEp5huTU1uANXC1s3PxC4tLyyNkMRnlZ+pQmlraIDqxu3o0BnGGsMcniadmFpagrKAAosRiFhiAQAISXf5VACc+GarS8t06PTWT0Gr3eUxmc0WAj+1iBILBkP+6HJFMp6AAelBGqd5FAsBgoBwIMAHK4AAajCbY2Zc3RQACy7M5dOU5CwKW4EpKEFcLSgYCwBAIpHo8hAUDY5GcEAwFAVUG8pzYEEs1lh8OuSLuDzRzyGvI+X1xv3+RNBEMtVL9FNpuv1hvICqAA)

The example above shows that
```javascript
type A = {
  foo: string,
  bar: number,
};
type B = {
  bar: boolean,
};
type C = {
  ...A,
  ...B,
};
```
Does not resolve `C` to `{ foo: string, bar: boolean }`.

**Comment by STRML** [comment]
@seveibar See https://github.com/facebook/flow/issues/3534. You can work around this by [using exact types](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKAzA9jgXFAM7ABOAlgHYDmANBlAEYCGphlArgLaMSn0oAvgG40oSFABCCZOkws2TPABsIzSgJFjw0AMIzUDAHQmY9TCaOTNozGgD09qPqIALHB2UATKKQhEcZQA3aGAcZGw8QhIKGlomVkJGFTVKKEEGNFVgKCoSGHw4RCRIgigAclcIZWUccviFQgBGAAZ00TQAYxxKANUjWuoACjzgGCNcHCMwgBkcAHc+XWYiCCGASnWO7Nze4F18fWLSwkrq2vqExSxmZVX2tC6evogBnGHR3Qm8aZw5xdIy1WGy2UEcUAAoqRSDhSEQAISPcFNACchG6vUCr0GIz2X0mv3+SxWa02wjBTihMLhiPBmHpDMZmAAelBOrdlFAcFgoFwIMB3D4AAazBbE1ZCoxQACy-MFbPUlBwOV4CpqEB8PSgYBwRCI5EYyhAUA4lC8ECwVA1UCCtw4EAcTlR6OeWLeHzx3ymooBQNJoPBVNhCMdTLDDNZpvNlsoGqAA) for now.

**Comment by msiebert** [comment]
@STRML I get `SyntaxError: Unexpected token` when I try to use the spread notation. I found a [suggestion to use flow comments](https://github.com/babel/babel-eslint/issues/443#issuecomment-296178850) to get around this issue, and it works, but I was wondering if you had a more elegant solution. Thanks!

**Comment by STRML** [comment]
Be sure your babel version is up to date for that.

**Comment by msiebert** [comment]
Just tried 6.26.0 and got the same issue. As far as I can tell, that's the latest version of babel, right?

**Comment by STRML** [comment]
Oh right. I think it's only been merged into the 7.x branch.

Mark Siebert wrote:

**Comment by msiebert** [comment]
Cool. Thanks for your help. :+1: I'll just stick with the comment syntax for now.

**Comment by mgtitimoli** [comment]
@conartist6 you can do what you asked [here](https://github.com/facebook/flow/issues/1326#issuecomment-273677565) using a combination of spreading and $Shape like follows:

```
type Result = {
  ...$Shape<OtherType>,
  // additional entries
};
```

**Comment by jedwards1211** [comment]
Does object type spread work?

```
// @flow

type Foo = {bar: number}
type Foo2 = {...Foo}

function f(foo: Foo2) {
	const n: number = foo.bar // should be fine, right?
}
```

```
7: 	const n: number = o.foo                      ^ Cannot assign `o.foo` to `n` because undefined [1] is incompatible with number [2].
References:
3: type Foo = {foo: number}
                    ^ [1]
7: 	const n: number = o.foo
             ^ [2]
```

**Comment by goodmind** [comment]
@jedwards1211 it works fine in `master`

**Comment by jedwards1211** [comment]
all released versions I've tried don't work though, going back a long way.  So I'm not sure whether it's a bug or something I fundamentally misunderstand about how object type spread is intended to work

**Comment by goodmind** [comment]
it's long standing bug

**Comment by mgtitimoli** [comment]
https://medium.com/flow-type/coming-soon-changes-to-object-spreads-73204aef84e1
