### ISSUE TITLE
Intersection of object types should be a valid lower bound of the object type with properties from all branches

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1327]
Repro:
```javascript
/* @flow */
type A = { a: string } & { b: string };
type B = { a: string, b: string };
declare var a: A;
var b: B = a;
```
```
test.js:5
  5: var b: B = a;
                ^ intersection: object type(s). This type is incompatible with
  5: var b: B = a;
            ^ object type
```

What's happening here, as far as I can tell, is that Flow tries both branches of the intersection in A one at a time. As if we assigned `var b: B = { a: string }` then later `var b: B = { b: string }`. Both of these assignments independently should fail, but if we imagined that both assignments happened "together" should succeed.

I think that lots of issues related to intersection types might reduce to this. Check out linked issues for more examples.

**Comment by pasha-mf** [comment]
Seems like https://github.com/facebook/flow/issues/1172 is related.
