### ISSUE TITLE
Generics superclass check don't work

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#1328]
Suppose a code like this:
```
/* @flow */
class A {
    someField : string;
}

class B<T : A> {
    arr : Array<T>;
}

function foo(b : B) : void {
    b.arr.push(1);
}
```

Flow will find zero errors in it. Anyway if I change to
```
function foo(b : B<A>) : void
```
it will throw exception, as expected. The issue here, is that `T` should always extend `A`. So `B` should always be considered as `B<A>`, or even better as `B<T : A>`.

**Comment by samwgoldman** [comment]
If you don't fully parameterize a generic class type, Flow will fill in `any`—so `let b: B` is the same as `let b: B<any>`.

Adding the lower bound constrains the parameter, so given `class B<T : A>`, I couldn't pass, say, `number`, but I could pass a hypothetical subclass of `A`.

The behavior of using `any` here isn't super new, but it is changed from the original behavior. If you don't want to specify a type parameter explicitly, you might be able to use existentials. That is, `let b: B<*>`. The * can be thought of as an "auto" instruction to the typechecker, telling it to fill in the type from context.
