### ISSUE TITLE
Flow does not detect type issues when using Object.defineProperty

### ISSUE THREAD

**Issue by newbreedofgeek** [facebook/flow#133]
I've been using Flow on an API library I'm building, I purely use ES5 techniques to create the OO model.

For e.g: To create a function that sits off the window object I use Object.defineProperty.

I noticed that Flow cannot detect Type issues when you do this:

I've written the same logic below using basic function definition and using Object.defineProperty. Flow should detect that "property length not found in Number" when calling both these functions.

<pre><code>/* @flow */

Object.defineProperty(window, 'testServerLoadA', {
    value: function(noOfHits) {
        var boostLoad = noOfHits.length * 10;  // Flow WONT detect this issue
        console.log(boostLoad);
    },
    writable: true,
    enumerable: true,
    configurable: true
});

window.testServerLoadA(3);

function testServerLoadB(noOfHits) {
    var boostLoad = noOfHits.length * 10; // Flow WILL detect this issue
    console.log(boostLoad);
}

testServerLoadB(3);</code></pre>

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by GAntoine** [comment]
Test

**Comment by apsavin** [comment]
Looks like it fixed @goodmind 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAA8wBeMAbwF8BudAeQCMArAUw3wDoATVqAS2ysACgCc4AB1aj8ATwAURADRgA5PlYEAytIBu0gDJwAhtwCCqlRVRhbYXcZgBXVgC4wUJ9g78c87HD0UAAS-Pi4AJSUNnaxDqJgjHBwBEamZGABQaHhnDCs2ADm+AAWyGAAjAAMNLbAwGAAYvBIAOr0AHIAKmC8Ghxgpfy4YMO4LjGxtlh4cPl5cIXySSn4adwRdLFUSpNgCKJhxoz57viiLruxBU4AttLHp4MXrFd2MwKFTqKPbs8TVE26CInA02j0hhM5nkAGYgahPN58L5sINNPgdKJ9KJ1gAhfyBEJhSLROLGBIrVJQjJZIm5fJFUrlaq1epNFpgVoASQMBl6rH6hCGIzGE1iM1wc1YCyWlLWUKBVHQYIxEJxUPxcKAA
