### ISSUE TITLE
Can't import variable named `of`

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#1340]
Not sure if this by spec or a bug, but I couldn't find any mention of `of` being somehow special case in import.

```
4: import {of} from 'foo'
           ^^ Unexpected token of
```

**Comment by codemonkey800** [comment]
`of` is a reserved keyword for ES6. It's called a `for-of` loop It's used for iterating through the values in an iterable object:

```
const stuff = [1, 2, 3, 4, 5];
for (const value of stuff) {
  console.log(value);
}
```

You can read more about it here: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...of :smiley:

**Comment by michaelficarra** [comment]
@codemonkey800 No it's not.

**Comment by codemonkey800** [comment]
@michaelficarra Hmm, you're right. My mistake. Just went on MDN and confirmed it's not. Not sure what the issue is then.

**Comment by samwgoldman** [comment]
Yup, looks like we're overstrict on this. Thanks for the bug report!

**Comment by samwgoldman** [comment]
(By the way, I think the fantasyland project is great—is there an effort to integrate Flow? If so, keep me in the loop. I think it's a good motivating use case for us.)

**Comment by rpominov** [comment]
@samwgoldman Unfortunately we accidently have made that integration harder by trying to fix name clashes issue (see 2. in https://github.com/fantasyland/fantasy-land/issues/122#issuecomment-177134562)
