### ISSUE TITLE
Inconsistent docs: Objects / Adding properties

### ISSUE THREAD

**Issue by amakhrov** [facebook/flow#1344]
The [docs say](http://flowtype.org/docs/objects.html#adding-properties):
````
file.js:3:16,16: undefined
This type is incompatible with
  file.js:8:7,12: string
````
> In other words, Flow knows enough to infer that whenever the x property of o does exist, **it is a number**, so a string should not be expected.

So the text piece is not consistent with the code sample / output. Also it's not illustrative enough, as the order of `foo()` and `bar()` calls differs from the previous code snippet

**Comment by gabelevi** [comment]
Closing this out, [per my comment on #1345](https://github.com/facebook/flow/pull/1345#issuecomment-203247954). Thanks for the report!

**Comment by amakhrov** [comment]
@gabelevi looks like the new snippet of the code still lacks the `return` statement:
````
function foo(p) { p.x = 42; }
function bar(q) { q.f(); }
````
here the `bar` function doesn't return anything (return type is always underfined). My assumption is that it's not exactly what you wanted to illustrate by this snippet, considering the explanation below:

> Flow knows enough to infer that whenever the x property of o does exist, **it is a number**, so a string should not be expected.

**Comment by gabelevi** [comment]
Gah, yeah, I see it. I'll patch it quickly.
