### ISSUE TITLE
Bug in class property parser

### ISSUE THREAD

**Issue by steelbrain** [facebook/flow#1350]
```js
export class Some {
  some: string;
  constructor() {}
}
```
now if we remove that semi-colon, and make it
```js
export class Some {
  some: string
  constructor() {}
}
```
We get an unexpected identifier error. I'm on linux with flow `0.21.0`

**Comment by samwgoldman** [comment]
Thanks for the report. This is actually not a bug, but rather an intentional (if controversial) design decision to prevent infinite lookahead in the parser.

**Comment by steelbrain** [comment]
@samwgoldman but what about the people who don't use semi-colons in JS?

**Comment by samwgoldman** [comment]
¯\_(ツ)_/¯

This isn't a Flow issue. Flow is parsing this as designed. If you have comments on the proposal, you should talk to TC39.
