### ISSUE TITLE
Cannot build flow

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1352]
I tried to build flow. I made a clean clone and tried to build it from master. The error is:

```
ocamlbuild  -no-links  -I src/commands -I src/common -I src/dts -I src/embedded -I src/parser -I src/parsing -I src/server -I src/services/autocomplete -I src/services/inference -I src/stubs -I src/typing -I hack/dfind -I hack/find -I hack/globals -I hack/heap -I hack/hhi -I hack/procs -I hack/search -I hack/socket -I hack/stubs -I hack/third-party/avl -I hack/third-party/core -I hack/utils -I hack/third-party/inotify -I hack/fsnotify_linux -lib unix -lib str -lib bigarray -lflags "hack/third-party/inotify/inotify_stubs.o hack/heap/hh_shared.o hack/hhi/hhi_elf.o hack/utils/files.o hack/utils/get_build_id.gen.o hack/utils/get_build_id.o hack/utils/handle_stubs.o hack/utils/nproc.o hack/utils/realpath.o hack/utils/sysinfo.o hack/utils/priorities.o hack/utils/win32_support.o hack/hhi/hhi_win32res_stubs.o src/embedded/flowlib_elf.o -cclib -l -cclib elf   " src/flow.native
+ /usr/bin/ocamlc -c -w A -warn-error A -w -4-6-29-35-44-48-50 -I src/server -I src/parsing -I src/parser -I src/dts -I src/typing -I src/stubs -I src/commands -I src/embedded -I src/common -I src/services/inference -I src/services/autocomplete -I hack/procs -I hack/socket -I hack/search -I hack/dfind -I hack/find -I hack/utils -I hack/stubs -I hack/heap -I hack/globals -I hack/hhi -I hack/fsnotify_linux -I hack/third-party/core -I hack/third-party/avl -I hack/third-party/inotify -o src/server/serverEnvBuild.cmo src/server/serverEnvBuild.ml
File "src/server/serverEnvBuild.ml", line 26, characters 30-50:
Error: This expression has type string but an expression was expected of type
         Unix.file_descr
Command exited with code 2.
Compilation unsuccessful after building 204 targets (0 cached) in 00:00:19.
Makefile:119: recipe for target 'build-flow' failed
make: *** [build-flow] Error 10
```

The whole make process is here
https://asciinema.org/a/7i175provjjsgk15j1hmk5uch

It seems to me the bug is that this line
https://github.com/facebook/flow/blob/master/src/server/serverEnvBuild.ml#L26
is incompatible with this commit
https://github.com/facebook/flow/commit/ef67bfb638a36785fd70e8fee58ee04872cb4889

where the first argument stops being conditional. 

I have no idea how did this pass through Travis, since it crashes during make, which Travis should be doing.

(I wanted to fix this with pull request, but then it boiled down to logic of hack/utils/daemon.ml, and I got so lost in there that I will just put this issue here :) )

**Comment by samwgoldman** [comment]
Nice catch—this happens from time to time because we sync in hack changes.

**Comment by runn1ng** [comment]
Oh, it actually didn't pass through Travis, the build is still going/in queue/something like that. That explains it.

https://travis-ci.org/facebook/flow/builds

**Comment by runn1ng** [comment]
And yes, I can confirm that going one commit back before the hack "kill log_mode" commit temporarily fixes it.

**Comment by runn1ng** [comment]
Seems to be fixed, closing.
