### ISSUE TITLE
Error:  was expected of type  Unix.file_descr

### ISSUE THREAD

**Issue by mictadlo** [facebook/flow#1358]
Hello,
I got the following error:

       Error: This expression has type string but an expression was expected of type
              Unix.file_descr

after I did the following steps:

    sudo apt-get install ocaml libelf-dev opam
    git clone https://github.com/facebook/flow.git 
    cd flow
    make

What did I do wrong?

**Comment by runn1ng** [comment]
Duplicate of #1352

**Comment by runn1ng** [comment]
Fixed now, I suggest closing

**Comment by mictadlo** [comment]
Thank you it works for me, too.
