### ISSUE TITLE
Flow 100% CPU, flow stop not working

### ISSUE THREAD

**Issue by tryggvigy** [facebook/flow#1359]
I have encountered weird behaviour in flow. We use flow in two relatively similar repos, and flow works fine in one of them. However when I run flow in the other it spawns lots of flow processes, some of which can't be killed with `flow stop` 

`flow start`:

![screen shot 2016-02-03 at 12 49 44](https://cloud.githubusercontent.com/assets/2373958/12782708/e1cef06a-ca74-11e5-9a28-3663b8f6793a.png)
Notice the 4 processes using over 50% of CPU.

`flow stop`:

![screen shot 2016-02-03 at 12 50 34](https://cloud.githubusercontent.com/assets/2373958/12782735/1b217176-ca75-11e5-9d03-690b2ae3b405.png)

OS: El Capitan
flow logs:
```
[2016-02-03 12:48:23] Initializing Server (This might take some time)
[2016-02-03 12:48:23] executable=/usr/local/Cellar/flow/0.21.0/bin/flow
[2016-02-03 12:48:23] version=0.21.0
[2016-02-03 12:48:23] Parsing
```

**Comment by tryggvigy** [comment]
1. rm -rf repo
2. git clone repo
3 everything working normally

closing

**Comment by mvolkmann** [comment]
This is related to #2828.
