### ISSUE TITLE
Wrongly reported undefined

### ISSUE THREAD

**Issue by Zaba999** [facebook/flow#1361]
Flow reports possible undefined variable in below snippet

``` javascript
function canReturnUndefined(param/*: string*/) {
    if (param === "") {
        return;
    }
    return {field: "value"};
}

function doSomething(param_a/*: string*/, param_b/*: string*/) {
    var a = canReturnUndefined(param_a);
    var b = canReturnUndefined(param_b);

    if (a === undefined && b === undefined) {
        console.log("##!! option A");
    }
    else if (a === undefined && b !== undefined) {
        console.log("##!! option B", b.field);
    }
    else if (a !== undefined && b === undefined) {
        console.log("##!! option C", a.field);
    }
    else {
        // both 'a' and 'b' can't be 'undefined' here as such situation will be "caught" by previous 'if' statements
        console.log("##!! option D", a.field, b.field);
    }
}
```

error log:

```
flowTest.js:26
 26:         console.log("##!! option D", a.field, b.field);
                                            ^^^^^ property `field`. Property cannot be accessed on possibly undefined value
 26:         console.log("##!! option D", a.field, b.field);
                                          ^ undefined

flowTest.js:26
 26:         console.log("##!! option D", a.field, b.field);
                                                     ^^^^^ property `field`. Property cannot be accessed on possibly undefined value
 26:         console.log("##!! option D", a.field, b.field);
                                                   ^ undefined
```

Problem is that both a and b cannot be undefined in this situation.

**Comment by Zaba999** [comment]
Any idea? This is quite a big blocker for my project.

**Comment by samwgoldman** [comment]
I can repro. It's definitely a bug. Without investigating, it seems to be an interaction between the logical conjunction and the refinement. While it's true that `a` and `b` can't be `void` in the `else` clause, we can only know that through a somewhat complex logical reduction, where `x` depends on `y`. Flow doesn't track implications like this in its refinement machinery. It's highly likely you can restructure your code to make Flow happy.

**Comment by Zaba999** [comment]
Yes, but changing code to make Flow happy is not the way ;)

**Comment by d14b3l** [comment]
Hi, any update regarding this issue?

**Comment by calebmer** [comment]
This may be prohibitively difficult to implement due to what @samwgoldman said. So instead we recommend you structure your code in the following way 😊

```js
type T = {prop: number};

const a: T | null = null;
const b: T | null = null;

if (a) {
  if (b) {
	option4(a, b);
  } else {
    option2(a, b);
  }
} else {
  if (b) {
    option3(a, b);
  } else {
    option1(a, b);
  }
}

function option1(a: null, b: null) {}
function option2(a: T, b: null) {}
function option3(a: null, b: T) {}
function option4(a: T, b: T) {}
```

https://flow.org/try/#0C4TwDgpgBAKlC8UDeYBOB7MAuKA7ArgLYBGEqAvgNwBQ1AxurgM7BQCGOcAPnvgDZ8EvATQbNWxTlB4EBQ2XxrUAlgDMoACjYBKZNShQ1m4rqTUAkJmDLGAFi0AaKCZoHyUCHybQzBg1ZtcACZHZ21XKHJqd09vPQMjDRN4vwDGAGZQl31Ijy8fHP8wa0YARizwnKio6lV8XDoS3Cg03HKOYT4nSU7TKLqGppbiwJCOmG6cBT7a+sbA4abMjoVJ2BmB+cZFwPtxtZgZoA
