### ISSUE TITLE
Can't use boolean variable with disjoint union

### ISSUE THREAD

**Issue by MarcoPolo** [facebook/flow#1363]
```js
// @flow

type Foo = {data: number, error: false} | {error: true, data: string}

(errorB: boolean) => {
  // This fails although is the same thing as below
  const foo: Foo = {
    error: errorB,
    data: errorB ? 'asdf' : 0
  }

  let bar: Foo
  if (errorB === true) {
    bar = {
      error: true,
      data: 'asdf'
    }
  } else {
    bar = {
      error: false,
      data: 0
    }
  }

}


```

This means that if you want to use a disjoint union with a boolean you have to write twice as much code :cry: 

Might be related to: https://github.com/facebook/flow/issues/577

Thanks!

**Comment by avikchaudhuri** [comment]
@MarcoPolo This is a limitation, yes, but not something we can do much about with a significant amount of work. What you're asking for is basically correlating the check on `errorB` on the assignment to `data` with the value assigned to `error` on the previous line (for `foo`).

You can easily rewrite that part of the code to:
```
const foo2: Foo = errorB? {
    error: true,
    data: 'asdf'
  } : {
    error: false,
    data: 0
  };
```
which should work.
