### ISSUE TITLE
How to implement something like "abstract method"?

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1364]
This is something between a question about ES6/flow and feature request

I want to do something like this (in pseudo-javascript):

```
class AbstractAnimal {
     abstract sound(): string;
     makeSound(): void {
          console.log(this.sound());
     }
}

class Dog extends AbstractAnimal {
     sound(): string {
          return "Woof woof";
     }
}

class Cat extends AbstractAnimal {
     sound(): string {
          return "Meow meow";
     }
}
```

I know that it's not possible with ES6 alone, but I was thinking Flow might be able to help somehow. What I did - but it's pretty ugly - is this

```
class AbstractAnimal {
     sound(): string {
          throw new Error("This is abstract class");
     }

     makeSound(): void {
          console.log(this.sound());
     }
}

class Dog extends AbstractAnimal {
     sound(): string {
          return "Woof woof";
     }
}

class Cat extends AbstractAnimal {
     sound(): string {
          return "Meow meow";
     }
}
```

but nothing typechecks here that the ancestors will actually implement it. Now I am thinking that I am maybe Java-ing the code too much and it could be done maybe better and more JavaScript-y. But I don't see how.

**Comment by runn1ng** [comment]
OK I did it like this. I am closing (but would like to hear some discussion)

```
class AnimalSoundWriter {
     soundInfo: Animal;
     makeSound(): void {
          console.log(soundInfo.sound());
     }
}

type Animal = {
     sound: () => string;
}

// not necessary to write "implements Animal"
class Dog {
     sound(): string {
          return "Woof woof";
     }
}

class Cat {
     sound(): string {
          return "Meow meow";
     }
}
```

**Comment by jeffmo** [comment]
We've talked about abstract method enforcement a bit, but it hasn't surfaced the priority queue yet. Your discovery that you can use an object type to match these classes structurally is intentional, though.

FWIW: What seems to be asked for more often (and so might surface sooner) is the ability to specify `implements SomeInterface` on classes -- which would then assert that the given class *itself* implements the interface
