### ISSUE TITLE
Autocomplete not working for `this` in derived class

### ISSUE THREAD

**Issue by leonardfactory** [facebook/flow#1368]
With flow v0.21.0, whenever I try to define a derived class, `this` autocompletion stops working, both in constructor and methods. However `flow check` correctly reports 0 errors. Sample code:

```js
/* @flow */
class Test {
  prop: number;

  constructor(prop: number) {
    this.prop = prop;
  }
}

class ExtendTest extends Test {
  extended: string;

  constructor(extended: string) {
    super(10);
    this.extended = extended;
  }

  method() {
    this.prop = 12;
    this./* here */
  }
}
```

**Output with flow `v0.21.0`**

```sh
$ flow autocomplete --strip-root src/app/components/_test/test2.js 20 10 < src/app/components/_test/test2.js
# No hints
```
and
```sh
$ flow autocomplete --json --strip-root src/app/components/_test/test2.js 20 10 < src/app/components/_test/test2.js
{"result":[]}
```

**Output with flow `v0.19.1`** (_the latest one working with this test case_)
```sh
$ flow autocomplete --strip-root src/app/components/_test/test2.js 20 10 < src/app/components/_test/test2.js
extended string
method () => void
prop number
```
and

```sh
$ flow autocomplete --json --strip-root src/app/components/_test/test2.js 20 10 < src/app/components/_test/test2.js
[{"name":"extended","type":"string","func_details":null,"path":"src/app/components/_test/test2.js","line":11,"endline":11,"start":13,"end":18},{"name":"method","type":"() => void","func_details":{"return_type":"void","params":[]},"path":"src/app/components/_test/test2.js","line":18,"endline":21,"start":3,"end":3},{"name":"prop","type":"number","func_details":null,"path":"src/app/components/_test/test2.js","line":3,"endline":3,"start":9,"end":14}]
```

I'd like to give help, however I'm still pretty new to OCaml. l'll give a try to check the code.

**Comment by leonardfactory** [comment]
I'm attaching here the log from flow server:

```
Couldn't autocompleteFile "src/typing/flow_js.ml", line 5975, characters 4-10: Assertion failed
```

The line is in the Autocomplete module.

**Comment by samwgoldman** [comment]
Sorry this one slipped through the cracks. I'll take a look ASAP.

**Comment by leonardfactory** [comment]
Debugging the code I've found that the problem is in `flow_js.ml` [line 6173](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L6173). While matching pattern `TypeAppT`, [`instantiate_poly_t`](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L5962) is called with `t` of type `ThisClassT`, triggering `assert false`, because function is expecting only a `PolyT` type.

I've tried adding the following pattern just to test:

```ml
...
and instantiate_poly_t cx t types =
  match t with
  ...
  | ThisClassT t -> t (* here *)
  | _ ->
    assert false
```

Now autocomplete returns results for "ExtendedTest" (derived class) members, but not for parent class members. 

Hope this helps. If anyone can point me to some test I can do or explain me some logic to follow in order to better understand this part, I'll be glad to dig deeper and eventually find a solution.

Thanks!

**Comment by leonardfactory** [comment]
I've found that adding 

```ml
and instantiate_poly_t cx t types =
  match t with
  ...
  | ThisClassT _ -> t (* here *)
  | _ ->
    assert false
```

results in correct behaviour (all tests passing), however I still don't understand deeply the codebase, so I'm looking for further ideas:

From my tests on the `extract_member`, I can see that:

* if `Bar` does not inherits from `Foo` (`class Bar {}`):
  * Type is Bar (InstanceT)
  * `super` is `MixedT` [(here)](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L6151)
  * `extract_member` provides `Bar` members
* if `Bar` inherits from `Foo`:
  * Type is Bar (InstanceT)
  * `super` is `ThisTypeAppT` (with `c` as `ThisClassT`) [(here)](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L6151)
  * `extract_members` continues recursion and steps into `ThisTypeAppT` pattern matching
  * with **patched** `instantiate_poly_t`, successive `instantiate_type` call returns `InstanceT` (`Foo`)
  * `extract_members` continues recursion on `InstanceT` (now Foo), terminating the cycle and providing `Foo` and `Bar` members

I'd like to ask, especially for my personal understanding, if:
* Is it safe to change in this way `instantiate_poly_t`? I did only a fast check on the code, so I'm not sure about potential side effects.
* Maybe we can just change `extract_members` matching and handling specifically `ThisTypeAppT`, something like:
   ```ml
   | ThisTypeAppT (c, _, ts) ->
      ...
      (* let inst_t = derive t from c, matching, another modified `instantiate_poly_t` function *)
      let inst_t = instantiate_type inst_t in
      extract_members cs inst_t
   ```
   I don't know if this is correct, however I didn't find `ThisAppTypeT` with `c`different from `ThisClassT`, but I'd like to know if this idea is valid from flow devs

Thank you!

**Comment by avikchaudhuri** [comment]
On it.

**Comment by avikchaudhuri** [comment]
@leonardfactory Your initial recommendation on adding a case to `instantiate_poly_t` is correct, and I'll put up a fix shortly following that. The reason is that post 0.20, which introduced this types, empty type args can arise for non-polymorphic classes, in which case the shape of the class being instantiated legitimately doesn't have a PolyT wrapper. So basically the fix amounts to checking `types = []` and doing nothing if that's the case.
