### ISSUE TITLE
disjoint unions regression between 0.19 and 0.21

### ISSUE THREAD

**Issue by sakari** [facebook/flow#1371]
the following program passes on flow 0.19 and in http://tryflow.org/#57c61a492a07f6e77eeb451064a5e2e4

```
function create(a: any): { type: 'B', data: number } | { type: 'A', data: string }
 {
  return {
    type: 'A',
    data: a
  }
}
```

but fails on OSX El Capitan with flow 0.21

```
test$ flow version
Flow, a static type checker for JavaScript, version 0.21.0
test$ flow
test.js:4
  4:   return {
              ^ object literal. This type is incompatible with
  2: function create(a: any): { type: 'B', data: number } | { type: 'A', data: string }
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union: object type(s)


Found 1 error
```

**Comment by sakari** [comment]
interestingly if i set `type: 'B'` in the object literal flow does not complain

**Comment by jeffmo** [comment]
This is a known problem that we're actively working on. There are various nasty bugs with unions right now that we're ironing out.

Thanks for reporting!

**Comment by avikchaudhuri** [comment]
This will be fixed in an upcoming release.
