### ISSUE TITLE
Functions incorrectly allowed in type `Class<$Subtype<...>>`

### ISSUE THREAD

**Issue by fixplz** [facebook/flow#1373]
Currently any function is permitted as an element of `ReactClass`. Fe. you can do `React.createElement(() => {})`.

More simply this is permitted too:

``` js
class X {}
let x : Class<$Subtype<X>> = () => {}
```

Only classes related to `X` should be permitted.

Using version af67541

**Comment by calebmer** [comment]
The React specific issue will be addressed in an upcoming version of Flow 👍
