### ISSUE TITLE
Better exhaustiveness checking for variant type conditions

### ISSUE THREAD

**Issue by fixplz** [facebook/flow#1374]
In this code Flow will allow `f1` but not `f2`, because it considers the else-if in `f2` inexhaustive:

```js
/*@flow*/

type Opts = {bzt:{}}

type Variant = { type: 'a', opts_a: Opts } | { type: 'b', opts_b: Opts }

function f1 (val : Variant) : Opts {
  if(val.type === 'a') {
    return val.opts_a
  }
  else {
    return val.opts_b
  }
}

function f2 (val : Variant) : Opts {
  if(val.type === 'a') {
    return val.opts_a
  }
  else if(val.type === 'b') {
    return val.opts_b
  }
}
```

I prefer using the second version stylistically – it makes more sense to explicitly state what you're deconstructing. In fact I believe `f2` should be valid and `f1` should not be (`opts_b` should not be accessible in `f1`).

Using version af67541

**Comment by samwgoldman** [comment]
Merging with #451
