### ISSUE TITLE
Allow == operator for variant type conditions

### ISSUE THREAD

**Issue by fixplz** [facebook/flow#1376]
Currently, to use branching on variant types, you have to use the `===` operator. If you change it to `==` in the below code Flow won't acknowledge the refinement.

``` js

type Opts = {bzt:{}}

type Variant = { type: 'a', opts_a: Opts } | { type: 'b', opts_b: Opts }

function f1 (val : Variant) : Opts {
  if(val.type === 'a') {
    return val.opts_a
  }
  else {
    return val.opts_b
  }
}
```

This is a gotcha. There should be a warning advising to use `===`, or better yet Flow should allow `==` here and prevent cases where `==` and `===` would have different results.

Using version af67541

**Comment by SamChou19815** [comment]
This is expected behavior
