### ISSUE TITLE
Flow should include version in json results

### ISSUE THREAD

**Issue by steelbrain** [facebook/flow#1377]
Currently the whole trace system of flow is very broken, to apply some workarounds and make sure they don't affect future builds, it'll be nice to have flow include it's version along with results with `--json` param is given

**Comment by jeffmo** [comment]
Can you clarify what you mean by "trace system"?

Most commands that emit results with `--json` do include a `"version"` key on the emitted JSON object, though: https://gist.github.com/jeffmo/234f340b93efe075a71d

**Comment by steelbrain** [comment]
@jeffmo By "trace system" I meant blaming of errors, just found it that it actually exists, which is weird because it didn't when I checked last time, maybe because I checked using `autocomplete`
```
~/.a/p/linter ❯❯❯ print "AUTO332" | flow autocomplete --json
{"result":[{"name":"exports","type":"{}","func_details":null,"path":"","line":0,"endline":0,"start":1,"end":0}]}
```
