### ISSUE TITLE
Cannot re-export imported type

### ISSUE THREAD

**Issue by karel-3d** [facebook/flow#1379]
This syntax doesn't work.

`export type {ImportedType} from './file'`

(note that it does work with re-exporting functions, classes etc, Flow understands that and imports/exports correctly, just not types)

**Comment by jamesgpearce** [comment]
You can import and then re-export, but unfortunately it seems you have to change the name:

```
import type {MyType} from './types';
export type MyTypeToo = MyType;
```

...which is a bit annoying if your external clients have to use one type name, whilst inside the module you're using the other.

**Comment by AgentME** [comment]
You can change the name in import line:

```js
import type {MyType as _MyType} from './types';
export type MyType = _MyType;
```

**Comment by jamesgpearce** [comment]
Oh I had tried that, and it failed on the client's import. But I think that must have been to do with Flow caching something over the node_modules boundary - because when I restart, this approach now works. Thanks for the prompt.

Still a bit hacky ;)

**Comment by STRML** [comment]
Would it be possible for Flow to support `export type MyType` in the future? This would be a huge help for us.

**Comment by kamek-pf** [comment]
Stumbled on this today, none of the above solution works. Flow doesn't complain about missing modules, but it's not catching any errors either.
Importing directly from the right file works though.

**Comment by jamesisaac** [comment]
What version of flow are you using?  This works for me on 0.33.0:

definition.js:
``` js
// @flow
export type { MyType } from './types'
```

test.js:
``` js
// @flow
import type { MyType } from './definition'
const foo: MyType = 'a'
```

Flow output:
```
common/__tests__/test.js:3
  3: const foo: MyType = 'a'
                         ^^^ string. This type is incompatible with
  3: const foo: MyType = 'a'
                ^^^^^^ number

Found 1 error
```

And your other example works too.

test.js:
``` js
// @flow
import type { MyType, SomeTypeThatDoesntExist } from './definition'
const foo: MyType = 2
```

Flow output:
```
common/__tests__/test.js:2
  2: import type { MyType, SomeTypeThatDoesntExist } from './definition'
                           ^^^^^^^^^^^^^^^^^^^^^^^ Named import from module `./definition`. This module has no named export called `SomeTypeThatDoesntExist`.


Found 1 error
```

**Comment by kamek-pf** [comment]
Well I just tried again, and it actually works, my bad.
> Did you maybe forget a // @flow annotation at the top of your test files? That has caught me out before.

Yeah probably, I think I forgot the annotation on the definition file, and it obviously won't work without it.
Thanks @jamesisaac, and sorry for the noise :p
