### ISSUE TITLE
Special type operator allowing for "instance of"

### ISSUE THREAD

**Issue by zgao** [facebook/flow#1388]
Suppose I am passing into my HOC a react class and a couple functions that expect a member of that class. For example, let's say I have a CodeField with a cursorPosition.

I want Flow to be able to typecheck `HOC(CodeField, (cfInstance) => cfInstance.getCursorPosition())` - meaning that I want some `InstanceOf<T>` operator that allows me to do:

`function HOC<T: ReactClass, U>(component: T, f: (inst: InstanceOf<T>) => U)`

**Comment by dchambers** [comment]
I just hit the same issue, and ended up using this workaround:

~~~
declare var thing: Thing;
type ThingType = typeof thing;
~~~

**Comment by STRML** [comment]
Ran into the same issue when writing a typedef, issue is that there's an object floating around where its properties are classes, not instances of classes. I wanted to use $PropertyType to get the type of an instance but had no luck.

A [demonstration](https://flowtype.org/try/#0MYGwhgzhAEBiD29oG8C+Aodx4DsIBdowAuORaAXmhwFMB3M+ACgEp18BPABxsYGFwUStAGQIAHgTwAfAG50AegXQA6gAswhCGvgBXEABNo+NQEsYAI16mAZtDq9cIDtA0A3XlNFQA-FlwE0BakACQAknj4YDjANADyNpKI3hDSwrQMUqyyQA):

```jsx
class Foo {}

const a: Foo = new Foo()
type FooClass = Class<Foo>;
// What should this be if we only have FooClass?
const b: $InstanceOf<FooClass> = new Foo();
```

**Comment by STRML** [comment]
I'm happy to report you can do this now with `$Call`, and it works great!

```js
declare type InstanceOfClassExtractor = <C>(Class<C>) => C;
declare type InstanceOf<Cls: Class<any>> = $Call<InstanceOfClassExtractor, Cls>;
```

For instance, to work around import restrictions in type declarations, I sometimes use `$Exports<pkgName>`. So if I wanted to declare something as an instance of e.g. `EventEmitter3`:

```js
class Foo {
  addEmitter(emitter: InstanceOf<$Exports<'eventemitter3'>>): void;
}
```

**Comment by aksuska** [comment]
+1. Also the solution posted by @STRML does not address the main concern of this thread. I can't even get it to work for the use case he brings up given the code provided: i.e. variable/property as a class object, rather than an instance of a class (object of class type).

**Comment by STRML** [comment]
Could you elaborate on "couldn't get it to work"?

**Comment by aksuska** [comment]
Considering:
declare type InstanceOfClassExtractor = <C>(Class<C>) => C;
declare type InstanceOf<Cls: Class<any>> = $Call<InstanceOfClassExtractor, Cls>;
class MyObject {}
var classRef: InstanceOf<MyObject> = MyObject;

result:
Cannot instantiate `InstanceOf` because `MyObject` [1] is incompatible with statics of `C` [2] in the first argument.

**Comment by STRML** [comment]
Yes, for a variety of reasons:

1. You copied/pasted the extraction code incorrectly and omitted several type arguments
2. You provided no type argument what for what you thought `classRef` was an instance *of*
3. You did not actually instantiate `MyObject` 

Try [this running example](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQSQHYGdFSzBAHkAzAYWhxwFEAPRGKMRAexngF54AecgPgAUlKNT78AlF37xyAbgBQoSLAQp08bHgJEyfCDgBcsqjh4Fk-GdwAk5KBAg8t+QiQqn6jZmxgAaExx+RRVqeABZZGIAIwArcER4AG8AXwUAN1h4UJwAJRBSYxcdd31RM0iY+JYrLngsEAB3CKi4hMEJOSA)

And this [example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgEyTQBsUi4YBPMJOASQDsBnGFNzRIA8pgDCDXrwCiADxhR0MaHAC8cADziAfAApJKadp0BKdTrjiKNeow6t2XPgKGjM2urwBcVqb01BFh1LDQAScRQ6Ok0efkFhMUNpeUVlaAAaP14dCjh8gvzyAHpiuABiAEYAZgAOWrgkORRwOiRqWgYmTABXIRhgCG44AAkRcU0AFV9kgORlADpxXEhuJG4YQO4WLKCQrIBVfTQVofWYX0msomFgADckKF89YBdfONdEj0mzCzgD0y+O4QYBUCjkOzSKwQGgAMWASDoVEaCnWVF4iGIMCWpzWGy2OzgezgAG9yAUAOZIGDiHpQXjQAAKEF4wAGQz05hJcCIMDpw3wZDgAF9yKKxuIDDCkPDEVQsno0JgPgkkOY1JYlSq3AsqTS6QyoMzWezuJzTOQJVK4QikQqtS5VerNcrHTq9bT6UyWWzBtwAEzmuClRpQHBQACEQA) which addresses the question in OP.

**Comment by aksuska** [comment]
The first example shows what I was missing. Your original solution did not show a concrete example so my tests were broken due to my incomplete understanding of Flow syntax. In particular the concrete usage of your example is:
InstanceOf<Class<Class_Name>>

**Comment by aksuska** [comment]
@STRML Did you also figure out how to declare inheritable class types, i.e. where a property or return type is a class of a class that extends the class, rather than an instance?

**Comment by SamChou19815** [comment]
It can now be achieved with conditional type
