### ISSUE TITLE
Flow does not prove that switch statement over every case of a union type is total

### ISSUE THREAD

**Issue by cdparks** [facebook/flow#1390]
Using `flow` version 0.19.1 on Ubuntu 14.04.3. I have the following (simplified) source:

```javascript
/* @flow */

type ThisOrThat = 'This' | 'That'

function toInt(t: ThisOrThat): number {
  switch (t) {
    case 'This':
      return 0
    case 'That':
      return 1
  }
}
```

When I run `flow`, I get the following errors:

```plaintext
x.js:5
  5: function toInt(t: ThisOrThat): number {
                                    ^^^^^^ return undefined. This type is incompatible with
  5: function toInt(t: ThisOrThat): number {
                                    ^^^^^^ number
```

I can suppress this error by adding a `return null` at the end of `toInt`, but then I have to make the return type nullable, and I won't get a warning if I add a new case to `ThisOrThat`:

```javascript
type ThisOrThat = 'This' | 'That' | 'SomethingNew' // New case is unhandled

function toInt(t: ThisOrThat): ?number {
  switch (t) {
    case 'This':
      return 0
    case 'That':
      return 1
  }
  return null
}
```

Does `flow` attempt to do totality checking in `switch` statements? Would this be a new feature or is this an existing issue?

**Comment by samwgoldman** [comment]
Merging with #451

**Comment by cdparks** [comment]
Ah, thanks! I missed that one.
