### ISSUE TITLE
Stop parsing non-@flow files

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1392]
Historically, we had to parse every file because we used the comments extracted by the parser to look for the @flow pragma. If a file encountered a parse error, we suppressed the errors and did not add it to the map of files Flow knows about (which it uses to resolve require/import), which led to "module not found" errors. Then we changed it to only show parse errors on files that are required by @flow files as a compromise to avoid the "module not found" errors.

Today, we use the lexer to extract the first comment token in order to extract the pragma, and don't need to parse the entire file.

**Comment by mroch** [comment]
unclear to me right now whether we should parse @noflow files. probably not. but then there's no difference between @noflow and no pragma. @noflow would become useful again once we add the ability to make flow opt-out (#284)

**Comment by jeffmo** [comment]
I think the presence of @noflow would be more of an indicator that the file was intentionally/explicitly opted out (vs not opted-in)
