### ISSUE TITLE
Impossible to annotate variable as a polymorphic function

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1395]
I have being running into this limitation a lot, but mostly because I was trying to define type annotations separate from implementations, but now I run into this issue in very regular use of flow. In fact I don't think there is a way to define this without flow failing:

``` js
/* @flow */

export const get = <item>
  (index:number):(items:Array<item>) => ?item =>
  (items) =>
  items[index]

export const first = get(0)
```

This produces following error

```
type parameter `item` of function call Missing annotation
```

I also tried different ways to annotate `first`:

``` js
export const first:(<item> (items:Array<item>) => ?item) = get(0);
```

and

``` js
export const first = (get(0):(<item> (items:Array<item>) => ?item));
```

But non of these works.

**Comment by Gozala** [comment]
Only way I managed to workaround this is by tricking flow into thinking that have provided diff implementation:

```js
/* @flow */

export const get = <item>
  (index:number):(items:Array<item>) => ?item =>
  (items) =>
  items[index];

export const last = <item>
  (items:Array<item>):?item =>
  items[items.length - 1];

export const first = (get(0)/*::,last*/);
```

**Comment by jeffmo** [comment]
Looks like Flow is expecting annotations on typeparams for exported functions... Can repro this with normal functions as well (a little easier to parse):

```javascript
function get<item>(index): (items:Array<item>) => ?item {
}
```

**Comment by Gozala** [comment]
BTW it would be really great if flow did not require return type annotation if it's just closure that only returns another annotated function. Because you pretty much end up repeating yourself twice in such cases.

**Comment by jeffmo** [comment]
> BTW it would be really great if flow did not require return type annotation if it's just closure that only returns another annotated function

The reason Flow requires annotations on module boundaries is a bit of a trade-off: Requiring annotations reduces the amount of work Flow has to do when it is solving types for an entire codebase. If all exports went unannotated, Flow would likely be fairly slow.

To address this problem we have some heuristic logic that determines which circumstances to be lenient on vs not -- but currently this logic operates at a fairly coarse-grained level. Flow can tolerate *some* level of this work. Picking where to be lenient is a trade-off between being confusing vs annoying: It's confusing if it's lenient sometimes but not others ("what are the rules?"). It's annoying if it asked for *everything* (think about all properties on every object that is exported, etc).

Because the "requires annotation" logic is coarse-grained right now, we're somewhat limited on which patterns we can add exceptions to be more lenient on -- but we do have some ideas to make that better in the future.

**Comment by ianobermiller** [comment]
This is the same as #846?

**Comment by Gozala** [comment]
Turns out it's actually the same issue as #2105. [see modified version works](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwBjOAOwGdiBzDYgXjAB4BLQjAWwD5UwwAFK3IATbAC5yAV04AjDPgCUYBr35ty5BePZdug3Z0riAgvnwBDAJ4at+bovEB+YXZVqwhygG1hYrAC6ANzo-PyYuATEZFTEMBbUKiyGHkIcRqbm1mzpDs6G7nye6T5eAHQwGOQ0hAAWYAC0YACMwejYeESkFIlQrPiJTHSEAgAMikFAA):

```js
/* @flow */

export const get = <item>
  (index:number) =>
  <inner:item> (items:Array<inner>):?inner =>
  items[index];

    
export const last = <item>
  (items:Array<item>):?item =>
  items[items.length - 1];

export const first = get(0);
```


It's just polymorphic high order functions do return polymorphic functions bound to the same parameters, but flow expects you to explicitly annotate inner function as polymorphic, otherwise it treats it as some kind of not fully typed monomorphic function. @avikchaudhuri  tried to explain it in more details here:
https://github.com/facebook/flow/issues/2105#issuecomment-234118176

Anyway as I mentioned in that other bug I find it counter intuitive that flow requires inner functions to be manually annotated as polymorphic with bounds to outer params, due to arguments made in that issue.

With more & more instance of that issue I'm even more convinced that chosen default is counter intuitive.

**Comment by lapanoid** [comment]
@Gozala How you managed get this to work, I have errors if try to actually use `last` or `first` funcs. 

```
const arr = ['1', '2', '3']
    
const f = first(arr)
```

```
15: const arr = ['1', '2', '3']
                 ^ string. This type is incompatible with
5:   <inner:item> (items:Array<inner>):?inner =>
            ^ some incompatible instantiation of `item`
15: const arr = ['1', '2', '3']
                      ^ string. This type is incompatible with
5:   <inner:item> (items:Array<inner>):?inner =>
            ^ some incompatible instantiation of `item`
15: const arr = ['1', '2', '3']
                           ^ string. This type is incompatible with
5:   <inner:item> (items:Array<inner>):?inner =>
            ^ some incompatible instantiation of `item`
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwBjOAOwGdiBzDYgXjAB4BLQjAWwD5UwwAFK3IATbAC5yAV04AjDPgCUYBr35ty5BePZdug3Z0riAgvnwBDAJ4at+bovEB+YXZVqwhygG1hYrAC6ANzo-PyYuATEZFTEMBbUKiyGHkIcRqbm1mzpDs6G7nye6T5eAHQwGOQ0hAAWYAC0YACMwejYeESkFIlQrPiJTHSEAgAMiiFhYKgxiRbmSd4A5M1LADRgSwBM65sAzEsBReGzxFBJfQMj80pAA

**Comment by calebmer** [comment]
It looks like this works now.

Let me know if I’m missing something 👍

```js
// function get<TItem>(index: number): (items: Array<TItem>) => ?TItem {
//   return (null: any);
// }

const get = <TItem>(index: number) => (items: Array<TItem>) => items[index];

const first: string = get(0)([1, 2, 3]);
```

https://flow.org/try/#0PTAEDMFcDsGMBcCWB7aoDmBTeAeAKgJLyYC2AfABSLQAmmAHgFyjSQkBGmATgJTNXESAZ2YBBLlwCGAT3xFSZHqAC8ZUAH5Cg0AG8AUCFBGu2SFzQVWAGyvNJ0aTwDcBsAF89e2KiHwM2FVA5QUpqOiYWNk5eFTUBUhFQcSlZLQUlVVBEQSEAbTCGAF0XLx8-cEQuX2ZfLmp0QKx4CgAGHgpcgEYAGlAAJl6AZkLnPSA

**Comment by karlhorky** [comment]
Hm, that link is erroring out now with `0.75.0`.

```
7: const first: string = get(0)([1, 2, 3]);
                         ^ Cannot assign `get(...)(...)` to `first` because `TItem` [1] is incompatible with string [2].
References:
5: const get = <TItem>(index: number) => (items: Array<TItem>) => items[index];
                                                       ^ [1]
7: const first: string = get(0)([1, 2, 3]);
                ^ [2]
```

```
7: const first: string = get(0)([1, 2, 3]);
                                 ^ Cannot call `get(...)` with array literal bound to `items` because number [1] is incompatible with `TItem` [2] in array element.
References:
7: const first: string = get(0)([1, 2, 3]);
                                 ^ [1]
5: const get = <TItem>(index: number) => (items: Array<TItem>) => items[index];
                                                       ^ [2]
```

etc...

**Comment by karlhorky** [comment]
I was having a similar problem with something that I wanted to do with generic parameters and bounded polymorphism throwing `incompatible` errors, but was unsure if this was actually a bug:

https://flow.org/try/#0MYewdgzgLgBA5gUygMRCGBeGAeAKgPgAoQAjAKwC4YBvAMzSoEEAnZgQwE898BfASkz4YpMgDp6IANwAoUJFi0Als2hNWnbGACuAWxIJmQrIhRpCdBjADaARgA0MAEwOAzAF1+MoA

**Comment by wchargin** [comment]
This is strange. The problem doesn’t require a third-party libdef; you
can [reproduce it as follows][try-broken]:

```js
function getArr<T: number>(obj: {numbers: Array<T>}) {
  return obj.numbers;
}
declare var o: {numbers: Array<number>};
const arr: Array<number> = getArr(o);  // error?!
```

If we ask `flow type-at-pos` the type of `getArr`, it says:

```js
<T: number>(obj: {numbers: Array<T>}) => Array<T>
```

which is correct. If we explicitly annotate the return type of `getArr`…

```js
function getArr<T: number>(obj: {numbers: Array<T>}): Array<T> {
  return obj.numbers;
}
declare var o: {numbers: Array<number>};
const arr: Array<number> = getArr(o);  // works (good)
```

then [the problem goes away][try-fixed].

[try-broken]: https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZQIICcsB4AqAXImCALYBGqWAfABRwUBWxA3qZdQM7HZYCGATwI0AvgEpErAFCJEWdCCxJGTAHQcqWLgG5po6QBNUEADb8FiAG4XEcNpu68cQ3I9qi9EBFyiILWM4Cwu40iAC8KOh8DOJ6QA
[try-fixed]: https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZQIICcsB4AqAXImCALYBGqWAfABRwUBWxA3qZdQM7HZYCGATwI0AvgEpeOISMSsAUIkRZ0ILEkZMAdBypYuAbnmj5AE1QQANvxWIAbjcRw2u7lIHDXtUUYgIuUIg2WO4yXjSIALwo6HwM4gZKAPRJiADucFgA1lyIdMhwcKbi8kA

It’s true that `Array<T>` is not and should not be a subtype of
`Array<number>` (if you’re not sure why, let me know and I can explain),
but it’s not clear why that is relevant here. As expected, replacing
`Array` with `$ReadOnlyArray` everywhere fixes the problem.

Unless I’m missing something, this looks like an inference bug.
