### ISSUE TITLE
Unexpected token ILLEGAL

### ISSUE THREAD

**Issue by bingerog** [facebook/flow#1396]
I am experimenting with flow in a existing code base.  During flow tool execution I am getting following error 

03:04:31 Running "flow" task
03:04:43 src/cm/PDDBMetadataJSONConverter.js:142
03:04:43 142:     this.productData = xml.productData ? xml.productData.map(function(xml)B {
03:04:43                                                                                ^ Unexpected token ILLEGAL

But If I check the code in any text editor, the code does not have any additional parameters like "B". 

Code excerpt for your reference 
```javascript
 this.productData = xml.productData ? xml.productData.map(function(xml) {
        return {
            name: xml.$.name,
            property: xml.property ? xml.property.map(xmlAttributeMapper) : undefined
        };
    }) : undefined;
```

What is the root cause of this issue?  How can I suppress this error?

**Comment by samwgoldman** [comment]
The provided excerpt is insufficient to reproduce the error. Please provide a complete code example that exhibits the error behavior.

**Comment by bingerog** [comment]
Currently we are doubting utf-8 characters in this file. Once we isolate this issue, I will update.

**Comment by bingerog** [comment]
The issue was related to a utf-8 character. JS is tolerent to this, but not flow. 

@samwgoldman: Thank you very much for your prompt response

**Comment by jacquesdev** [comment]
If it will help anyone, I had the same error because I had name a branch which included a "." character in the name and got this error.
