### ISSUE TITLE
Revising DOM interface, open questions

### ISSUE THREAD

**Issue by fkling** [facebook/flow#140]
So, I [revised the DOM interface](https://github.com/fkling/flow/blob/b2722bb63e6569769a698db5a2803c9f64a874be/lib/dom.js), but encountered some questions during the process:

**Separation of DOM and HTML DOM interface**

I think separating the DOM and HTML DOM declarations would improve maintainability. The problem is that HTML DOM extends DOM through *partial* interfaces. I.e. they augment the interface definitions in DOM. There doesn't seem to be a way to do something like this in Flow, so the only way for defining HTML DOM is to add those attributes / methods to the DOM declarations.
Is there anything on the road map which would allow us to extend an existing declaration, just like WebIDL does? This would also be great for managing browser specific extensions.

Some declarations such as `File` or `Blob` don't even have anything to do with DOM. Maybe we can at least put those interfaces into their own file.

**Interfaces**

What are the plans for interfaces? For my changes I had to copy the same definition to multiple class declarations because interfaces are not supported (yet?).

**Instance of a class**

Hack has the type `this` to indicate that a method returns an instance of the same class the method is invoked on. That's especially useful for inheritance. In this particular case: `cloneNode()`, defined in the `Node` class. What are the plans for this feature and how to handle this now? Would I have to declare that method with the correct return type in every class that extends `Node`?

**Which DOM version?**

I followed the declarations of https://dom.spec.whatwg.org/. [This section](https://dom.spec.whatwg.org/#historical) explains the changes to the previous version (DOM Level 3). I assume we also want to include changed or removed attributes / methods from previous versions?

**Testing**

What would be the best way to test my declarations?

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mroch** [comment]
I think some of these questions have been solved, and the rest will be solved by flow-typed. For example, one of the things we hope to do is unbundle the DOM and node libdefs from the flow binary, so that there can be more than one for different versions of DOM and node.
