### ISSUE TITLE
Questions about Flow best practices

### ISSUE THREAD

**Issue by ccoffey** [facebook/flow#1405]
I have the following code.

```javascript
function openMessenger() {
  return {
    type: 'OPEN_MESSENGER'
  };
}

function closeMessenger() {
  return {
    type: 'CLOSE_MESSENGER'
  };
}

module.exports.openMessenger = openMessenger;
module.exports.closeMessenger = closeMessenger;
```

There are a few different ways that I could add Flow types to this code and I am wondering what is considered best practice.

1) Use exact string values for the type of OpenMessengerAction & CloseMessengerAction.

```javascript
/* @flow */
type OpenMessengerAction = {
  type: 'OPEN_MESSENGER';
};
type CloseMessengerAction = {
  type: 'CLOSE_MESSENGER';
};

function openMessenger(): OpenMessengerAction {
  return {
    type: 'OPEN_MESSENGER'
  };
}

function closeMessenger(): CloseMessengerAction {
  return {
    type: 'CLOSE_MESSENGER'
  };
}

module.exports.openMessenger = openMessenger;
module.exports.closeMessenger = closeMessenger;
```

2) Use string instead of exact value for type of OpenMessengerAction & CloseMessengerAction.

```javascript
/* @flow */
type OpenMessengerAction = {
  type: string;
};
type CloseMessengerAction = {
  type: string;
};

function openMessenger(): OpenMessengerAction {
  return {
    type: 'OPEN_MESSENGER'
  };
}

function closeMessenger(): CloseMessengerAction {
  return {
    type: 'CLOSE_MESSENGER'
  };
}

module.exports.openMessenger = openMessenger;
module.exports.closeMessenger = closeMessenger;
```

3) OpenMessengerAction & CloseMessengerAction are basically the same except for the value of type so define a common type MessengerAction for them.

```javascript
/* @flow */
type MessengerAction = {
  type: string;
};

function openMessenger(): MessengerAction {
  return {
    type: 'OPEN_MESSENGER'
  };
}

function closeMessenger(): MessengerAction {
  return {
    type: 'CLOSE_MESSENGER'
  };
}

module.exports.openMessenger = openMessenger;
module.exports.closeMessenger = closeMessenger;
```

**Comment by jeffmo** [comment]
Do you plan to mutate these objects after getting them from the function? If not, any reason not to just use raw strings ('OPEN_MESSENGER', etc) rather than an object wrapper around them?

**Comment by ccoffey** [comment]
@jeffmo these are Redux actions, the typical pattern is to have an object with a type and optionally some data. Please see [here](http://redux.js.org/docs/basics/Actions.html)

**Comment by jeffmo** [comment]
@ccoffey got it. In that case, I think your best bet is to type each action individually and use string-literal types for the `type` key (AKA: option 1 in your list).

This is the only of the 3 options that will let Flow understand when you distinguish the two types later (via a switch or if-statement, etc).

**Comment by ccoffey** [comment]
@jeffmo just for completion's sake, can you please explain how option 1 is best for Flow when I have a reducer that uses the above two actions?

```javascript
module.exports = function(state = initialState, action) {
  switch (action.type) {
  case 'OPEN_MESSENGER':
    return Object.assign({}, state, {isMessengerOpen: true});
  case 'CLOSE_MESSENGER':
    return Object.assign({}, state, {isMessengerOpen: false});
  default:
    return state;
  }
};
```

**Comment by jeffmo** [comment]
So, given that the two objects are identical except for the type, there's not actually a huge benefit in this specific scenario. However -- if ever you decide to add another action (or add any additional keys to any of the existing actions), using disjoint types lets Flow understand the difference between the shapes of the objects for each action.

So imagine this hypothetical change to the `OpenMessengerAction` type in the future:

```javascript
type OpenMessengerAction {
  type: 'OPEN_MESSENGER',
  openedFromLink: boolean,
};
```

```javascript
switch (action.type) {
  case 'OPEN_MESSENGER':
    // Flow will understand that action.openedFromLink is a boolean here
  case 'CLOSE_MESSENGER':
    // Flow will understand that there are *no* other keys on action other than "type" here
}
```
