### ISSUE TITLE
Can't declare function name that is keyword

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#1407]
I'm trying to define an interface for the axios module. Everything works except the axios.delete function. I get "Library parse error" and "Unexpected token delete". I assume this is because delete is a JavaScript keyword, but that is the name of the function. Is there a workaround for this?

**Comment by jeffmo** [comment]
Can you provide a paste or gist of the code you're hitting the error with?

**Comment by mvolkmann** [comment]
Note the "delete" function below. Flow doesn't like that.

````
declare module axios {
   declare function axios(config: ?Object): Promise;
   declare function delete(url: string, config: ?Object): Promise;
   declare function get(url: string, config: ?Object): Promise;
   declare function head(url: string, config: ?Object): Promise;
   declare function patch(url: string, config: ?Object): Promise;
   declare function post(url: string, config: ?Object): Promise;
   declare function put(url: string, config: ?Object): Promise;
}
````

Here is the error I get:
````
flow-libs/axios.js:10
 10:   declare function delete(url: string, config: ?Object): Promise;
                        ^^^^^^ Library parse error:
 10:   declare function delete(url: string, config: ?Object): Promise;
                        ^^^^^^ Unexpected token delete
````

**Comment by jeffmo** [comment]
Aha! Thanks. So this one is sort of tricky, but I think your best bet for right now would be to do something like this instead:

```javascript
declare module axios {
  declare var exports: {
    axios(config: ?Object): Promise,
    delete(url: string, config: ?Object): Promise;
    ...etc...
  };
}
```

I have some general thoughts around revamping the `declare module` syntax a bit, but it'll likely be a while before that surfaces the priority queue -- so using the special `exports` export is probably your best bet for now.

Feel free to re-open if you have any further issues!

**Comment by samwgoldman** [comment]
@jeffmo isn't this a parser bug? Despite a workaround existing, we shouldn't close this if it's a bug.

**Comment by gforge** [comment]
I think this is still a bug, I get the issue adding `async`, e.g. below works

```
export const test = {
  stuff: {
    delete(parentValue: mixed, values) {
      console.log(values);
    }
  }
}
```

while this causes the error

```
export const test = {
  stuff: {
    async delete(parentValue: mixed, values) {
      console.log(values);
    }
  }
}
```

or have I missed something?
