### ISSUE TITLE
Use Promise as thenable failed

### ISSUE THREAD

**Issue by Spy-Seth** [facebook/flow#1408]
I'm trying to use a Promise as a thenable value, but flow fail to validate it:

```javascript
/* @flow */

export default (): Promise => {
    const fooPromise = Promise.resolve(42);
    const barPromise = Promise.resolve(51);

    return barPromise.then(fooPromise);
};
```

It trigger an internal error: 
```
andbox/foo.js:7
  7:     return barPromise.then(fooPromise);
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `then`
422:       onFulfill?: (value: R) => Promise<U> | U,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Library type error:. See: /private/tmp/flow/flowlib_13e86e0/core.js:422
422:       onFulfill?: (value: R) => Promise<U> | U,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type. Callable signature not found in. See: /private/tmp/flow/flowlib_13e86e0/core.js:422
  7:     return barPromise.then(fooPromise);
                                ^^^^^^^^^^ Promise
```

**Comment by motiz88** [comment]
Flow is right. `Promise.then` doesn't take a `Promise` argument: It takes a _function_ - or rather two functions, `onFulfill` and `onReject`. Those functions can return a new value (or indeed a new `Promise`), resulting in [Promise transformation](https://www.promisejs.org/#then) (aka [Promise chaining](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/then#Chaining)), a full explanation of which is probably out of scope here.

If you want to return `fooPromise`'s value after `barPromise` has resolved, use a callback:
```javascript
return barPromise.then(() => fooPromise);
```

Though in real code you'll probably want to somehow _generate_ `fooPromise` inside that handler:

```javascript
return barPromise.then(barValue => someAsyncCall(barValue)); // or .then(someAsyncCall);
```

**Comment by jeffmo** [comment]
@motiz88 seems to have described the problem well, so I'll close out the issue
