### ISSUE TITLE
Newbie: ES6 features, Babel, and Flow don't seem to play well together

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [facebook/flow#1411]
So, feel free to close this if this is exclusively an upstream problem … but it seems like Flow is designed to be used with Babel to write ES2015-compliant JS with static type-checking, and that process seems completely broken for even the most basic uses right now:

Simply by *installing* `babel`, I can no longer Flow without a ton of type-error noise:

```
mkdir flow-fail && cd !#:1
npm init --force
npm i --save flow-bin babel-cli
flow init
flow check
```

This dumps [all of this error spam](https://gist.github.com/ELLIOTTCABLE/96c2f2f5b10ca62fcfc6) to my console.

Is there a way that I, as a beginner, can avoid this mess and focus on typing *my own* files? (Notice that I created no file, nor used `/* @flow */` here, at all; this is in an otherwise-empty directory! Thus, `/* @flow weak */`, which is the only recourse mentioned in the documentation, isn't helpful to me here.)

> This seems to be primarily an upstream problem (i.e. that Babel's libraries [claim to type-check](https://github.com/babel/babel/blob/b1bb39e7336f1120f7b1d5c757a1804d960ee26a/packages/babel-types/src/flow.js#L1), but [don't](https://github.com/babel/babel/blob/b1bb39e7336f1120f7b1d5c757a1804d960ee26a/packages/babel-types/src/flow.js#L10).) I've posted this as [T7114](https://phabricator.babeljs.io/T7114) on their Maniphest issue-tracker; if that's as much resolution as you guys are interested in, feel free to close this.

**Comment by winkler1** [comment]
Am using. Seems wrestling .flowconfig/[ignore] is price of admission. Agree, not a great out-of-the-box for new users.

**Comment by ELLIOTTCABLE** [comment]
Yeah, @winkler1's reply on Twitter pointed me towards *a* solution, in `.flowconfig`:

    [ignore]
    .*/node_modules/babel-.*

Honestly, more than a little surprised that this seems to work? I'd have expected Flow would need type information from the Babel libraries to correctly type-check stuff like complex compiled `_regenerator2` calls. I'll have to see how well this works as a workaround as I proceed to learn Flow!

**Comment by cesarandreu** [comment]
@ELLIOTTCABLE Flow won't usually process the output code generated by babel (although it could, if you compiled and then ran the output through flow), it'll just process the source directly. It crawls node_modules by default because there might be type definitions that it needs to pick up.

**Comment by samwgoldman** [comment]
Quick update here. We've been focusing on the new user experience for OSS stacks in the last week. FB's use case is slightly different so we don't run into these issues internally. Thanks for sending in these issues, so we are better informed to solve these issues.

Anyway, we landed a change to no longer parse non-flow files, which fixed a bunch of node module errors and improved perf. It turns out that a couple libraries—fbjs and babel notably—ship with invalid flow declarations.

I'm working to fix those libraries now. Thanks for sending in this feedback, helping each other work around issues, and for your patience as we resolve them.

**Comment by ELLIOTTCABLE** [comment]
No patience necessary! I'm not paying you or your company for any service, heh; I'm just happy you've open-sourced this wonderful tool.

(@samwgoldman: Is more feedback from non-Facebook users something you're actively soliciting? If it'll help your team, I can try and put aside some time to explore Flow as a whole, and write up some comprehensive feedback. It's a great project!)

**Comment by jeffmo** [comment]
@ELLIOTTCABLE: That would be really awesome! Getting more feedback from non-FB users is something we could definitely use more of

**Comment by ELLIOTTCABLE** [comment]
It seems that, as of recently, the initial installation process (at least, the parts I complained about above) are much-improved. Although documentation and general OSS UX could still stand some love and attention, *this specific* issue is handled; so I'm gonna close it out.

<3, guys!
