### ISSUE TITLE
module.name_mapper doesn't work if the mapping resolves to a libdef module

### ISSUE THREAD

**Issue by jeffmo** [facebook/flow#1415]
```javascript
// libs/LessStub.js
declare module LessFileStub {
  declare function someLessAPI(): number;
}
```

```
// .flowconfig
[options]
module.name_mapper='.*\.less' -> 'LessFileStub'
```

```javscript
import {someLessAPI} from 'blah.less'; // blah.less. Required module not found"
```

------

The issue appears to be [here](https://github.com/facebook/flow/blob/master/src/services/inference/module_js.ml#L437) where we assume that an import can be resolved on the FS (but neglect to deal with the fact that an import might be made available in a libdef's `declare module`).

**Comment by samwgoldman** [comment]
Dup! #1322

**Comment by jeffmo** [comment]
doh! Thanks
