### ISSUE TITLE
Identify an "ECMAScript 5 Class" as a type

### ISSUE THREAD

**Issue by leonardo-silva** [facebook/flow#1419]
I am using Flow to infer types for a JS application. This is the command I use: `flow dump-types filename.js`. However, Flow does not identify "constructor functions"  as types, in a ES5 code. By constructor functions I mean those we instantiate with new or Object.create(). See the following example:

```
function Point(x, y) {
    this.x = x;
    this.y = y;
    this.toString = function() { return ('x = ' + this.x + '; y = ' + this.y)};
}

function Line(x1,y1,x2,y2) {
    this.p1 = new Point(x1,y1);
    this.p2 = new Point(x2,y2);
}

var line = new Line(1,3,8,2);
console.log (line.toString());

```

For the code above, Flow can give me the types below, considering the attributes bound to this:

```
x :  number
y :  number
p1 :  {toString: () => string, x: number, y: number,}
p2 :  {toString: () => string, x: number, y: number,}
```

What I would like to say is that p1 and p2, inside function Line, are of type 'Point'. But Flow identifies the type of p1, for example, as the structure of the new object created.

Is there a way Flow can tell me that p1 and p2 are of type Point, instead of {toString: () => string, x: number, y: number,} ?

**Comment by samwgoldman** [comment]
To be clear, your issue here is that we print the full instance signature (`{ x: number, y: number, ...}`) instead of `Point`?

There's no unexpected type error, or lack of a type error in an incorrect program?

**Comment by avikchaudhuri** [comment]
Maybe, yeah...but there's always going to be people wanting the structural rather than the nominal type. Let's think about it a bit more. We absolutely want to emit inferred types that are themselves syntactically valid, so what this suggests is that maybe there's a place for syntax like `Point { x: number, ... }`. In fact, thinking a bit more, I'm not sure we print stuff in prototypes, but by mentioning `Point` in the type we implicitly point to `Point.prototype` as well, so the full type is something like `{ x: number, ... } & T` where `T` is the type of `Point.prototype`. Thanks for bringing this up.

**Comment by leonardo-silva** [comment]
samwgoldman: Yes,  the idea is to be able to link `p1` and `p2` to the function `Point`. The dependency is not clear if you look at the structure of the plain object.  It is not the case of a type error.

**Comment by leonardo-silva** [comment]
avikchaudhuri: Yes, I think something like `Point { x: number, ... }` would be great. It would serve both: people wanting structural and also nominal type. Thanks.

**Comment by moll** [comment]
Has there been any progress in this? I take it the inability to define classes in ECMAScript 5 syntax also relates to Flow in no way identifying constructors and their prototypes? For example, given the following commented-class definition and its related definition, Flow throws assignment errors:

```js
/* @flow */

/*::
declare class Person {
  constructor(_ :string): void;
  greet(): string;
}
*/

function Person(name) {
  this.name = name
}

Person.prototype.greet = function() { return "Hi, " + this.name }

var john = new Person("John")
john.greet()
john.meet()
```

```
14: Person.prototype.greet = function() { return "Hi, " + this.name }
                     ^ Cannot assign function to `Person.prototype.greet` because property `greet` is not writable.
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVoBcnUEgAmApgMYwCGAToWKWQM51gAKhFdcAdmAN6pj9hcxTnQAuFAK7FRcCgAoA+mExiKASw4BzAJSYwANzhr8Abj4CLmqoVFzdYVRs1mLAX1Qp0UCR2lrOzKzsHHIcZAC2hNo85qIAFmp0AHRhkWAAvGCphKjuqCxsnEkADhRwMqIAnsWESVaENhlg3r6i-iHR3GBUohIUXABEABJqADRgA2AA1GDxiSkR1Hn6lGAAVnBxXJkchEgFwXIDAFKbHAPaqBtbdda2l9ccSZE2dkA

**Comment by SamChou19815** [comment]
Closing as we removed support for this old style class.
