### ISSUE TITLE
"required module not found" for webpack shimmed module

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#1421]
Flow seems to be incorrectly warning me about a module I'm trying to import:

```
import ShimmedModule from 'exports?ShimmedModule=SomeModule!some-library-js';
                          --------------------------------------------------
```

I'm following webpack's convention for importing a module from a library that doesn't export it's values by using the `exports-loader`.

https://webpack.github.io/docs/shimming-modules.html

Is there a way to have Flow recognize that this is webpack-specific syntax?

**Comment by calebmer** [comment]
You can use the `module.name_mapper` config option to provide types for modules like this 😊

https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string
