### ISSUE TITLE
Using typeof with multiple mixed values is not properly detected by flow

### ISSUE THREAD

**Issue by keithamus** [facebook/flow#1423]
Firstly, thanks for the awesome project, I've been using it to annotate some existing codebases and it has already managed to surface a couple of inconsistencies in the code!

In one particular codebase, I have a function which takes two arguments, both are either a String or a Function - and the return result of the function is a combination of the functions/strings as appropriate. Here's some reduced code:

``` js
/* @flow*/
type functionish = string|()=>string
function combine(firstFunction: functionish, secondFunction: functionish): functionish {
  if (typeof secondFunction === 'function' && typeof firstFunction === 'function') {
     return (first, ...rest) => secondFunction(firstFunction(first, ...rest), ...rest);
  } else if (typeof secondFunction === 'function') {
    return (first, ...rest) => secondFunction(firstFunction, ...rest);
  } else {
    return secondFunction;
  }
}
```

As you can see - I have type checks around the potential errors, so this function is pretty robust, however I get the following flow errors:

``` js
src/test.js:5
  5:      return (first, ...rest) => secondFunction(firstFunction(first, ...rest), ...rest);
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. Function cannot be called on
  2: type functionish = string|()=>string
                        ^^^^^^ string

src/test.js:5
  5:      return (first, ...rest) => secondFunction(firstFunction(first, ...rest), ...rest);
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. Function cannot be called on
  2: type functionish = string|()=>string
                        ^^^^^^ string

src/test.js:7
  7:     return (first, ...rest) => secondFunction(firstFunction, ...rest);
                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. Function cannot be called on
  2: type functionish = string|()=>string
```

`Function cannot be called on string` seems to be a misnomer - as my function already guards all function calls with a typeof check. Is this a bug - or have I just got things wrong?

**Comment by keithamus** [comment]
I have managed to wrestle the parser into only showing 1 error now, instead of three. The implementation has changed slightly because of this but not enough to make a difference for my use case:

```js
/* @flow*/
type actualFunction = () => string;
type functionish = actualFunction|string;
export default function combine(firstFunctionish: functionish, secondFunctionish: functionish): actualFunction {
  const secondFunction: actualFunction = typeof secondFunctionish === 'string' ?
    () => secondFunctionish : secondFunctionish;
  const firstFunction: actualFunction = typeof firstFunctionish === 'string' ?
    () => firstFunctionish : firstFunctionish;
  return (first, ...rest) => secondFunction(firstFunction(first, ...rest), ...rest);
}
```

The error now is:

```js
src/test.js:3
  3: type functionish = actualFunction|string;
                        ^^^^^^^^^^^^^^ function type. This type is incompatible with
  2: type actualFunction = () => string;
                                 ^^^^^^ string
```

This error seems particularly cryptic to me. I'm not really sure what `function type is incompatible with string` is supposed to mean?

**Comment by keithamus** [comment]
To reduce this test case down even further...

```js
/* @flow*/
export default function stringToFunction(functionOrString: string|(() => string)): (() => string) {
  if (typeof functionOrString === 'string') {
    return () => functionOrString;
  }
  return functionOrString;
}
```

Which produces the following:

```js
src/test.js:4
  4:     return () => functionOrString;
                      ^^^^^^^^^^^^^^^^ function type. This type is incompatible with the expected return type of
  2: export default function stringToFunction(functionOrString: string|(() => string)): (() => string) {
                                                                                               ^^^^^^ string


Found 1 error
```

It seems as though flow cannot deal with function/string union types?

**Comment by calebmer** [comment]
This is because function arguments are not constant by default 😊

So Flow errors here to assert that sometimes `functionOrString` may be reassigned to a new value. To fix the error you can write:

```js
function stringToFunction(_functionOrString: string|(() => string)): (() => string) {
  const functionOrString = _functionOrString;
  if (typeof functionOrString === 'string') {
    return () => functionOrString;
  }
  return functionOrString;
}
```

We want to make this more robust in the future so const is assumed if there is no assignment. You can also use the `experimental.const_params` option 👍 

https://flow.org/try/#0GYVwdgxgLglg9mABAZygJxmA5gFTgMXGnjAAoB9USWBAeTQGV1MsAuFZ7AH1NIEpEAXgB8HDNj592vASLEsBAbwBQiRBASpEVYnUacsQxJSI0w9JuKwBuVYhjBEpKAE8ADgFM4jnWYsGhQUFEAHJUKxClOzU0DygQNCR+IVFfEn8rWzUAXztY+MTtU3T9TOVcoA
