### ISSUE TITLE
"could not resolve name" for webpack variable injected by the DefinePlugin

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#1424]
Flow is warning me about a variable that it cannot resolve:

> identifier `__VERSION__` Could not resolve name

```
module.exports = {
  __VERSION__,
  -----------
  ...
}
```

`__VERSION__` is a "free variable" injected by webpack's `DefinePlugin`:

http://webpack.github.io/docs/list-of-plugins.html#defineplugin

```
new webpack.DefinePlugin({
  __VERSION__: 'v1.0.0',
})
```

Is there a way to let Flow know about this variable? Is there a way to tie Flow's config with webpack's config so that it knows about these free variables?

**Comment by leonardfactory** [comment]
Using flow [declarations](http://flowtype.org/docs/declarations.html), you can just define them:

```js
declare var __VERSION__:string;
```

Then flow will typecheck correctly

**Comment by UnsungHero97** [comment]
thank you!

**Comment by samwgoldman** [comment]
Thanks, @leonardfactory!

**Comment by jeantimex** [comment]
Thanks @leonardfactory!

**Comment by SebastienGllmt** [comment]
For anybody else who finds this via Google:

You can declare global variables without breaking any other tool that parses your file by using Flow's [comment type](https://flow.org/en/docs/types/comments/) syntax.

For example we can define the global `chrome` without breaking Firefox's linting rule requirements for submitting extensions to the Mozilla addons page.

```javascript
/*::
declare var chrome;
*/
```
