### ISSUE TITLE
Cannot use imported (react) types in declarations

### ISSUE THREAD

**Issue by danez** [facebook/flow#1425]
Currently it is not possible to do this in declarations:

```js
import { Component } from 'react';

declare module 'react-addons-shallow-compare' {
    declare var exports:
     (instance: Component, nextProps: ?Object, nextState: ?Object) => boolean;
  }
```

When i do this it seems to mess up the declaration of react, as I get the following error in my react components:

```
  3: import React, { Component, Element } from 'react';
                     ^^^^^^^^^ Named import from module `react`. This module has no named export called `Component`.
```

**Comment by STRML** [comment]
I've seen this as well - makes it difficult to properly type abstractions, such as a base Component superclass.

**Comment by MoOx** [comment]
I got the same message for a Component usage here

```js
/* @flow */

import React, { Component } from "react"
//...
class Button extends Component<void, Props, State> {
// got the issue on the Component import above
```
Somewhere I just defined this "helpers"

```
import type { Element, Component } from "react"

export type ReactElement = RElement
export type ReactComponent = RComponent | ReactClass | Function
```
 
I found a workaround:

```js
import type { Element as RElement, Component as RComponent } from "react"

export type ReactElement = RElement
export type ReactComponent = RComponent | ReactClass | Function
```

This way, no "conflict" with Component name. No sure why but it seems to works for me.

```

**Comment by jeffmo** [comment]
This is finally on my near-term plate, and we're going to be chatting more about it over [here](https://github.com/flowtype/flow-typed/issues/16) -- so lets consolidate discussion there.

**Comment by neurosnap** [comment]
I'm still seeing this error on 0.38.0, has this specific issue been fixed?

**Comment by danez** [comment]
@neurosnap You can use imports inside module declarations:

```js
declare module A {
    import type B from "B";
    ...
}
```

**Comment by neurosnap** [comment]
Any file that imports `Component` throws an error for us.  So it has less to do with declaring modules and more about `import { Component } from 'react'` throwing an error: Named import from module `react`. This module has no named export called `Component`.
