### ISSUE TITLE
Should `typeof x === "object"` refine `x` to `{ [k: string]: mixed }` or `Object`?

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1429]
I was toying around with the following code:

```js
type JSON = | string | number | boolean | null | JSONObject | JSONArray;
type JSONObject = { [key:string]: JSON };
type JSONArray = Array<JSON>;

function typedJSON(x: mixed): JSON {
  if (typeof x === "object" && x !== null) {
    // Flow would accept `return x;` here, but that would be wrong :(
    let o: JSONObject = {}; 
    for (let k of Object.keys(x)) {
      o[k] = x[k]; // flow also accepts `x[k]` here, when `typedJSON(x[k])` is correct
    }   
    return o;
  }

  if (Array.isArray(x)) {
    return x.map(typedJSON);
  }

  if (x === null ||
      typeof x === "string" ||
      typeof x === "number" ||
      typeof x === "boolean") {
    return x;
  }

  throw new Error("Invalid JSON");
}
```

Everything works fine, except the object branch. Since the refinement goes to `Object`, all the recursive coercing of properties to `JSON` are not necessary to type check. We could have simply returned `x` from that branch, but that code wouldn't be correct.

Is it worth being stricter here?

**Comment by mroch** [comment]
definitely think that the typeof check for objects should only assert that it's an object. since the whole thing was `mixed` to begin with, totally makes sense to me for the values to still be `mixed` too.

**Comment by bmeck** [comment]
A note here is that `typeof Object.create(null) === 'object'` but it does not inherit from `Object.prototype`

**Comment by jedwards1211** [comment]
Remember, strings are not the only type of keys.  Really JS objects accept any type, defined or not, inside `[ ]`, but this should at least support `Symbol` in addition to `string`.
