### ISSUE TITLE
function types and missing parameter

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#1431]
Why do I not get an error from the last line because testFn is missing the parameter "baz"?
"baz" is not declared to be an optional parameter in the type definition of MyFn.

```
type MyFn = (foo: number, bar: boolean, baz: string) => string;
function testFn(foo: number, bar: boolean): string {
  return 'in testFn';
}
const someFn: MyFn = testFn;
```

**Comment by vkurchatkin** [comment]
It's ok to pass more arguments, they will simply be ignored
