### ISSUE TITLE
Question: Adding interfaces for 3rd party react component - e.g. material-ui

### ISSUE THREAD

**Issue by mkellyclare** [facebook/flow#1434]
Is it possible to add an interface to a third party react component?

I would love to be able to add an interface that validates the proptypes of components that I am importing.

I tried a few different variations on this  - 

```
// Filename:  /interfaces/material-ui.js

declare module 'material-ui/lib/flat-button' {
  declare class FlatButton extends ReactElement {
    type: ReactClass<void, {label: string}, void>;
  }
}
```

but I get the following error - 

```
  4: import FlatButton from 'material-ui/lib/flat-button';
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ module `material-ui/lib/flat-button`. This type is incompatible with
132:     name: ReactClass<DefaultProps, Props, State>,
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ class type: existential. See: /private/tmp/flow/flowlib_3f857f8f/react.js:132
```

Thanks

**Comment by cprodescu** [comment]
Not sure if you still need this, but fwiw the suggestion in https://github.com/facebook/flow/issues/314 works for me:
```
declare class FlatButton extends ReactComponent {
  static defaultProps: {};
  props: { foo: 'bar' };
  state: void;
}
```

**Comment by asolove** [comment]
With Flow v0.53, there have been minor changes to the syntax for typing `Component`s. The example from @cprodescu is still close to right, but the syntax now [looks like this](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAJlrgDbKVwgSMCurWciGQwsUYMlYBaXsAD0rYACM5BdjClLeMGBAB2ZOAG86cOMzYdBl1OgBi6gELbdeuFgAeovY3TY8MAB0AMIkkHpYejAAPEbsSlisAFxwqDDiegDmAL4ANIgAfCZm2XTZQA).

Unless there is a further question, I think this issue can be closed (/cc @calebmer).
