### ISSUE TITLE
Documentation: React Component Class Annotations

### ISSUE THREAD

**Issue by bassettsj** [facebook/flow#1437]
I had some difficulty as a beginner finding the correct documentation for adding flow type annotations to our react components classes in the application. I was hoping the flux react example might provide better guidance, it did not. I eventually found a blog post, [_Type checking React with Flow_](http://sitr.us/2015/05/31/type-checking-react-with-flow.html), that answered my question. Would it be possible to add / contribute some documentation to the Flow site so others might not get stuck for so long?

**Comment by mroch** [comment]
we've been working on improving the docs recently. @jeffmo wrote up some new React docs that are landing right now (https://github.com/facebook/flow/commit/8337b4bb890985b3500dda37bb62e358831c57fa), which should be live at http://flowtype.org/docs/react.html in the next ~15 min.

**Comment by mroch** [comment]
let us know here if you've got any suggestions for that page, or there'll be an "Edit on GitHub" link in the top corner

**Comment by bassettsj** [comment]
@mroch Thanks for your awesomely quick response, I will go ahead and close this for now then :smile:
