### ISSUE TITLE
put note about React$Element change specifically in the changelog

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1438]
I've already used `ReactElement` in Flow annotations all over my code...now that 0.22.0 changed that to `React$Element` a lot of my flow annotations broke.  This seems worth of specific mention in the changelog to me.

**Comment by AgentME** [comment]
I think `React$Element` is intended to be private to the React declarations file, but Flow doesn't scope type declarations into the declarations file (feature request?). Other files should refer to the type as `React.Element` (assuming the module has been imported as React). The changelog probably should point this out.

**Comment by samwgoldman** [comment]
`React.Element` is what we'd like people to use. Yeah, we should add this to the changelog. We should also add this to the documentation. Sorry about the confusion.

**Comment by jedwards1211** [comment]
Gotcha, thanks!  I'm guessing Flow converts `$` in names in declarations to `.`?

**Comment by jedwards1211** [comment]
Sorry nevermind, I just saw the note about it being private to the definition file
