### ISSUE TITLE
Flow thinks a += b is a string if b is assigned within a switch case, even though a and b are numbers

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1439]
``` js
/* @flow */

let a: number = 0;
let b: number = 2;
let c: number = 0;

a += b;

switch (c) {
  case 0:
    b = 5;
    break;
  case 1:
    break;
}

a += b;
```

Produces:

```
react-sandbox/scratch/flowbugs.js:17
 17: a += b;
     ^^^^^^ string. This type is incompatible with
  3: let a: number = 0;
            ^^^^^^ number

react-sandbox/scratch/flowbugs.js:17
 17: a += b;
          ^ number. This type is incompatible with
 17: a += b;
     ^^^^^^ string
```

There's not some kind of super-obscure JS semantics I'm missing here, are there?

**Comment by samwgoldman** [comment]
Wow! Good catch. Looks like a legit bug to me. Thanks so much for including a small repro case!

**Comment by jedwards1211** [comment]
You're welcome!

Random thought of the day: I wonder how difficult it would be to make a tool that automatically tries variations of a given code sample to isolate what's causing the bug?

**Comment by TrySound** [comment]
Seems like this is fixed.
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMBDALjADsBXAWwCNMAnMAXjAAYBuDHMSosq2hsAExssuAMbcK1Oo1bo8YANSNKbVAGcEAS2yiAFmAAUogJRgA3qjBhReNZmYFLVzvwCsbZ5xqY8Aaw-WtvYAjI6elN5+bAC+corKLEA

/cc @vkurchatkin
