### ISSUE TITLE
Improve the Makefile

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1442]
the make targets are `build-flow` and `copy-flow-files` instead of actual artifacts like `bin/flow`, so every time you run make, we rebuild even if nothing has changed. see http://caml.inria.fr/pub/docs/u3-ocaml/make/Makefile.ocaml for example

also, we should add a `make install` target

**Comment by samwgoldman** [comment]
An old issue (which Gabe fixed a while back) was that `make` didn't rebuild when `lib/` stuff changed. We don't have automated tests for building, so I'm commenting so whomever changes this will not cause a regression.

**Comment by SamChou19815** [comment]
The Makefile is very different now, and we mostly use dune for oss build nowadays
