### ISSUE TITLE
(regression) Wrong type mutation across file boundaries

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#1447]
Flow version v0.22.0 [cf1a279ff382932c6bf9978f057b67358ec8b258], the problem didn't occur in v0.21.
## File 1
```
/* @flow */
export type Result = ?React.Element;

(<div>spoiler</div>: Result);
```

## File 2
```
/* @flow */
import type {Result} from "./file1.js";

(<div>test</div>: Result);
```

This setup produces
```
js/file2.js:4
  4: (<div>test</div>: Result);
      ^^^^^ React element: `div`
  4: (<div>test</div>: Result);
      ^^^^^ React$Element. This type is incompatible with
  4: (<div>test</div>: Result);
                       ^^^^^^ Element
```

The error goes away if I were to replace `?React.Element` with `?React$Element`, or with `React.Element`, or remove "spoiler" from file1. However I feel that if one declares a type in a particular way, that definition should remain constant regardless of the circumstances of its use...

**Comment by avikchaudhuri** [comment]
@pasha-mf You need to add the following line to file1.js:
```
import React from 'react';
```

**Comment by pasha-mf** [comment]
Well, I have a global declaration `declare var React: React;`, which works fine everywhere else but here...
