### ISSUE TITLE
Required module not found (for any ES6 module)

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#1448]
**UPDATE**: this was caused by a problem in my `.flowconfig`, see https://github.com/facebook/flow/issues/1448#issuecomment-237404200

For any ES6 (compiled) module I try to use, I get an error like this:
````
  2: import ExtendableError from 'es6-error';
                                 ^^^^^^^^^^^ es6-error. Required module not found
````

Here are some modules that reproduce the error for me:
* https://github.com/bjyoungblood/es6-error
* https://github.com/digitaldesignlabs/es6-promisify
* https://github.com/mozilla/web-extension-manifest-schema

Each of these modules publish node-compatible source code compiled with babel. The package.json declares the distribution something like `"main": "dist/index.js"` and this file exists in my local directory as one would expect, such as `./node_modules/es6-error/dist/index.js`.

Am I missing some configuration? I'm not ignoring these directories in `.flowconfig`. ~~Is there a workaround for this?~~ The workaround is to import each one from an opted out file within your app. Example: https://github.com/mozilla/web-ext/blob/master/src/util/es6-modules.js

Versions I'm using:
* flow-bin: 0.22.0
* Node: 4.3.0
* npm: 3.7.2
* webpack: 1.12.13
* babel-core: 6.5.2

**Comment by schickling** [comment]
Same here for `graphql`

**Comment by kumar303** [comment]
Hmm, I'm not sure if it's related. I tried the workaround in https://github.com/facebook/flow/issues/1420#issuecomment-187687051 but it did not make my imports resolvable. Also, the `es6-errors` package is very minimal -- I don't see any json files in there besides `package.json`.

**Comment by ericwooley** [comment]
Any update on this, these are kind of blockers. I am just ignoring the errors for now. But this is definitely not ideal

**Comment by kumar303** [comment]
My workaround is to import them from an opted out module (one without ``/* @flow */``): https://github.com/mozilla/web-ext/blob/master/src/util/es6-modules.js

**Comment by ericwooley** [comment]
I just made types. 

I am not sure I was actually encourting this problem, since I am still new to flow.

**Comment by raould** [comment]
js es6 modules are pretty confusing in and of themselves because TMTOWTDI so it would be great to have Flow docs clearly state with examples and unit tests the docs can link to what does work and what doesn't e.g. actively assert that certain things don't work, so that is documented by the tests.

I.e. is there any kind of es6 module use that works? Does it have to go through Babel first? Or something? thanks for any clues.

**Comment by thejameskyle** [comment]
ES6 modules should all work out of the box unless you are mixing them with CommonJS modules.

I'm not sure why these errors are occurring, could someone in this thread who has had this problem please create a project on GitHub that replicates the issue? It will provide a lot more context for us.

**Comment by vkurchatkin** [comment]
One of the common reasons for this error is that you ignore all `json` files and a module doesn't have `index.js` in it's root folder.

**Comment by kumar303** [comment]
@thejameskyle if I get some time I'll try to make a more minimal example. Until then you could clone https://github.com/mozilla/web-ext to reproduce it (today's master is at `c73c3152428e0cfc3232d3f6c643278b5b6f2e1c`). After cloning do this:

    npm install

Apply this patch:

`````diff
diff --git a/src/util/es6-modules.js b/src/util/es6-modules.js
index f84c994..c176f99 100644
--- a/src/util/es6-modules.js
+++ b/src/util/es6-modules.js
@@ -1,3 +1,4 @@
+// @flow
 /*
  * Flow does not validate any of these imports. This is a workaround for:
  * https://github.com/facebook/flow/issues/1448

`````

Run this to see the import errors:

    npm run flow-check

I see:

````
Running "flowbin:check" (flowbin) task
src/util/es6-modules.js:7
  7: import promisify from 'es6-promisify';
                           ^^^^^^^^^^^^^^^ es6-promisify. Required module not found

src/util/es6-modules.js:8
  8: import signAddon from 'sign-addon';
                           ^^^^^^^^^^^^ sign-addon. Required module not found

src/util/es6-modules.js:9
  9: import {createInstance as createLinter} from 'addons-linter';
                                                  ^^^^^^^^^^^^^^^ addons-linter. Required module not found
`````

**Comment by kumar303** [comment]
> unless you are mixing them with CommonJS modules.

Maybe that's exactly what I'm doing? :) Not sure what you mean here. The modules that are failing are ones that have been compiled from an ES6 source to NodeJS-compatible ES5 source.

**Comment by vkurchatkin** [comment]
@kumar303 the problem is that you have `.*/dist/.*` pattern in ignore section. You should probably use `<PROJECT_ROOT>/dist/.*` instead

**Comment by kumar303** [comment]
@vkurchatkin wow! I would have never found that mistake. Thanks so much for digging into the code to diagnose that. This definitely solved the issue for me (so this could be closed) but I don't know if everyone else was hitting the same problem.

**Comment by kumar303** [comment]
actually, re-reading the comments on here, I don't think anyone else was hitting this exact problem, heh. Thanks again for the help, I'll close it.

**Comment by dimpiax** [comment]
Better `../node_modules/*`, in case that `.flowconfig` placed in subfolder to project, for example in `src`.
