### ISSUE TITLE
JSX with multiple spreads

### ISSUE THREAD

**Issue by ianobermiller** [facebook/flow#1457]
Flow has a false positive on missing props when you use more than one spread:

``` jsx
import {Component} from 'react';

class Test extends Component {
  props: {
    a: string,
    b: number,
  };
}

const withA = {a: 'foo'};
const withB = {b: 123};

// property `a` not found in props (pointing at withB)
<Test {...withA} {...withB} />;
// workaround that does not error
<Test {...{...withA, ...withB}} />;
```

http://tryflow.org/#d6230b57a621b9053039b17161a8ada9

The use case for this was a container component that passes both props and state to its view, all of which are required by the view:

``` jsx
<View {...this.props} {...this.state} />
```

**Comment by samwgoldman** [comment]
Thanks, Ian. This definitely seems like an important use case.

**Comment by vkurchatkin** [comment]
It seems that it has been fixed
