### ISSUE TITLE
function with too few parameters

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#1458]
In the example below, should I get an error because the function I assign to cb doesn't take two parameters?

```
type Callback = (err: ?Error, result: string) => void;
const cb: Callback = err => console.log('in cb');
```

**Comment by samwgoldman** [comment]
Flow allows this. Consider the callback for Array.prototype.map, which takes three parameters (the item, the index, and the array itself). Would you want Flow to error on `arr.map(x => x * 2)` because the callback didn't specify all 3 arguments?

**Comment by mvolkmann** [comment]
Since Flow has syntax for specifying optional arguments, I would expect the callback for the Array map method to be defined like this:
````
(currentValue: any, index?: number, array?: Array) => any
````
That would allow callbacks that only specify the first parameter. It would also allow getting errors for cases where a function is expected to have all the possible parameters (by not making any of the parameters optional).

Maybe there are reasons this would be a bad idea that I'm not grasping yet.

**Comment by samwgoldman** [comment]
@mvolkmann Good insight about optional arguments. It's pretty nuanced, but using optional arguments is actually not a good way to model this. In particular, modeling `Array.prototype.map` this way would be unsound.

```js
// @flow

class MyArray<T> {
  _array: Array<T>;
  constructor(array: Array<T>) {
    this._array = array;
  }
  map(f: (value: T, index?: number, array?: Array<T>) => any): MyArray<T> {
    let result = []; 
    for (let value of this._array) {
      result.push(
        f(value) // Oh no! We forgot to pass `index` and `array`!
      )   
    }   
    return new MyArray(result);
  }
}
```

**Comment by mvolkmann** [comment]
Thanks Sam! I'm okay with this being closed whenever you are.
