### ISSUE TITLE
Lazy load node_modules to speed up Flow when in dependency hell

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#1461]
With recent versions of npm, node_module dependencies are flattened, which creates a massive amount of top-level directories that Flow descends into at startup. Could this be done lazily, right as the app under test tries to import something that Flow needs to analyze? I think this would also address https://github.com/facebook/flow/issues/719

As an example of how npm flattening affects Flow, my `package.json` defines 38 dependencies but my node_modules folder has 700 top-level modules :fire: . When I auto-generated ignore rules for these folders (https://github.com/facebook/flow/issues/719#issuecomment-180616534), the Flow server would start up twice as fast.

**Comment by AgentME** [comment]
Related suggestion: #869.

**Comment by samwgoldman** [comment]
@kumar303 Are you running 0.22? As of that version, we no longer parse non-`@flow` files, so large `node_modules` directories should have a much better experience.

**Comment by kumar303** [comment]
oh wow, it is a big improvement in 0.22, thanks! Feel free to close this issue. Funny enough, my startup time is faster now without my auto-generated ignore rules (probably because it's not doing so much regex).

**Comment by calebmer** [comment]
Closing, but we will continue thinking about not typechecking files in `node_modules` 👍
