### ISSUE TITLE
FAQ

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1465]
- When to annotate, when to infer
- When to run flow / editor, workflow integration
- What to put in .flowconfig
- When to use `any`, `Object`, `Function` types

Issues labelled "faq"

What else?

**Comment by avikchaudhuri** [comment]
Can we please call this a FAQ? Anything that goes in best practices can be asked as a FAQ. A FAQ is also more general. And it is easier to justify as a potentially arbitrary bag of stuff.

**Comment by samwgoldman** [comment]
@avikchaudhuri I actually want to *also* have a FAQ, and I've started tagging issues with a "faq" tag.

**Comment by samwgoldman** [comment]
Changed my mind. This is really just a FAQ.

**Comment by avikchaudhuri** [comment]
Nice. :)
