### ISSUE TITLE
Transparent wrapper for elements

### ISSUE THREAD

**Issue by raeesiqbal** [facebook/flow#1468]
Is there something similar to `<x:frag />` (as in HackLang) in FlowType? `<x:frag />` is a transparent wrapper when you dont have a wrapper for elements.
```hack
<x:frag>
  <a href="/home">Home</a>
  <a href="/login">Log In</a>
</x:frag>
```
will be rendered into:
```html
<a href="/home">Home</a>
<a href="/login">Log In</a>
```

**Comment by samwgoldman** [comment]
This is actually more of a React question, but I can answer it for them. No, currently a React component needs to return a single element. However, the team is looking to remove that restriction in the future. There is no timeline for that work, but it's discussed in depth on the React GitHub issues.

**Comment by raeesiqbal** [comment]
Thanks
