### ISSUE TITLE
point of .js.flow files

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#1469]
I'm not understanding the point of the .js.flow style of declarations yet.
The docs say they must be colocated with the .js file with the same name.
The example in the docs shows that types are also declared in the implementation file.
It seems like since those are present, there is no need for the .js.flow file.
However, the example shows that the type of the year parameter to the isLeapYear function differs between the implementation and declaration files. Why would it be useful for them to differ?

Please let me know if you would prefer that I not ask questions like this in Github issues.

**Comment by jeffmo** [comment]
> Please let me know if you would prefer that I not ask questions like this in Github issues.

This is a perfect use of GitHub issues!

So the main point of .js.flow files is to let you compile to ordinary JS (which can lose some type info -- like, say, classes in favor of imperative prototype building. Or various compiled-away type annotations) while retaining the original fully-expressive information for Flow to pick up.

In general, if you're going to ship Flow-typed JS to example, we'd recommend that you do so via `cp orig.js orig.js.flow; babel orig.js > orig.js` (I sort of fudged the CLI interface for Babel there, but hopefully you get the point).

**Comment by jeffmo** [comment]
IOW: .js.flow files are a way of telling Flow what the original file was (pre-compilation) while allowing runtimes (like node or packagers) deal in terms of "vanilla"/compiled JS

**Comment by mvolkmann** [comment]
Thanks Jeff! I understand the benefit of removing type information from the implementation file and specifying that in a separate .js.flow file. But why does the example in the docs show the implementation file still containing types and having types that differ from those in the .js.flow file?

**Comment by leonardfactory** [comment]
@mvolkmann The example in the docs is showing that a `.js.flow` declaration **always override** any type defined in the real `.js` implementation file; in this case, the declaration is clearly incorrect, and as the docs say:

> As this example shows, declaration files must be written with care: it is up to the programmer to ensure they are correct, otherwise they may hide type errors.

Flow doesn't care if original implementation `.js` file still contains annotations. The `.js.flow` will provide and eventually override type annotations; an use case may be, as docs suggest:

> [...] Sometimes, the implementation code may not yet be free of type errors, but we may want to move on and come back to fixing the type errors later [...]

Hope this helps!

**Comment by mvolkmann** [comment]
Thanks! I get it now. I suppose it's a matter of personal preference, but currently I think I would prefer to include type annotations in the .js files and provide tooling to strip the type annotations as part of the build process (for example, using babel-plugin-transform-flow-strip-types).

**Comment by jeffmo** [comment]
@mvolkmann: Yea, that will work -- but it means that downstream consumers of your library will consume the compiled version of the code (which is likely to exclude much of the information that Flow would need to typecheck consumers of the code).

Another alternative that we tried for a while was having the compiler simply use comment-syntax for the output, but this broke down when we discovered that not all compiler output easily takes the shape of the original code in way that Flow-comments make sense (i.e. compiling a class to a function is something that you can't really just sugar comments on to to give the shape of the original code). As a result, we've landed on .js.flow.

All that said, I'd actually like to see the babel plugin take on the responsibility of outputting .js.flow files as well. Of course you could always do the `cp`s yourself -- but it probably makes sense for the plugin to just DoTheRightThing for you. I might look in to what this would take in a few weeks and see where things land.

**Comment by evbo** [comment]
@jeffmo I wish I had read this before reading the [docs](https://flow.org/en/docs/declarations/), which as @mvolkmann pointed out are quite confusing. Since two days ago I've completely refactored my codebase using `.js.flow` files presuming they were like C++ header files - partitioning type declarations away separately from implementations and thus enabling the implementations to stay in vanilla javascript.

P.S.: I think the above interpretation would be a really powerful enhancement, as vanilla js projects could migrate to Flow without a single line of code change - and should they ever migrate away from Flow cleanup is easy: `rm -rf *.js.flow`
