### ISSUE TITLE
IE8 support?

### ISSUE THREAD

**Issue by dutzi** [facebook/flow#147]
The following code:
```javascript
/* @flow */

var div = document.createElement('div');

if (div['attachEvent']) {
	div.attachEvent('click', function() {
		console.log('Click!');
	});
}
```

Yields: `call of method attachEvent Property not found in HTMLElement`

Is there a way to disable this error? Or maybe add attachEvent to the list of known HTMLElement properties?

**Comment by samwgoldman** [comment]
You can either disable the error (using the suppression support) or use custom lib files, per #114. Please reopen if this is still an issue.
