### ISSUE TITLE
Unexpected behavior with unions of string literals (enums)

### ISSUE THREAD

**Issue by DJCordhose** [facebook/flow#1473]
When you define a union type of string literals like this

`type A = 'a1' | 'a2' ;`

assignment is checked as expected in an enum:

``` javascript
let a: A;
// ok
a = 'a1';
// ok
a = 'a2';
// error as expected
a = 'a3';
```

But when ckecking for values that are not in the enum, there is no error:

``` javascript
switch (a) {
    case 'a1': console.log('a1'); break;
    case 'a2': console.log('a2'); break;
    case 'a3': console.log('why is this legal code???'); break;
    default: console.log('and why this?');
}
```

Other type systems supporting enums would forbid this and also would report an error if I did not have case for each literal in the enum. 

flow accepts both cases. Any explanation why this is so?

**Comment by samwgoldman** [comment]
The technical reason is that the first case is unsound—i.e., could cause a runtime error later since we're breaking an assumption about what `a` contains. The latter will never cause a runtime error, so *technically* it's perfectly acceptable.

However, it's definitely dead code and we should error on this code. There are a number of open issues about this and closely related behaviors. Future versions of Flow will likely have this behavior, either directly or through an integration with a linter.

Thanks for opening the issue. Going to file under documentation because it'll be a lot easier for me to point someone to a prewritten explanation next time this comes up :)

**Comment by DJCordhose** [comment]
I agree that this is not technically an error, but most likely a programming mistake. A classic would be to forget one option of an enum (which might have been added later) or misspelling one option.

Would there be any drawback or general objection to implement this behavior or did it just not happen, yet?

**Comment by samwgoldman** [comment]
No objection. Like I said, future versions of Flow will likely have this behavior.

**Comment by DJCordhose** [comment]
I think OCaml has a pretty reasonable way of handling this case. Just tried this out

```
type action = Make | Delete;;

let reduce = function
  | Make -> 1
(*  | Delete -> 2 *)
  ;;
```

and not matching all constants of that type leads to this _warning_

```
Warning 8: this pattern-matching is not exhaustive.
Here is an example of a value that is not matched:
Delete
```

**Comment by greghe** [comment]
You could enforce type constraints at the `case` level to induce the desired error:
```
switch (a) {
    case ('a1': A):  // OK
       console.log('a1'); 
       break;

    case ('a2': A): // OK
       console.log('a2'); 
       break; 

    case ('a3': A): // Flow error - incompatible type
       console.log('why is this legal code???'); 
       break; 

    default: // OK - harmless
       console.log('and why this?');
       break;
}
```

**Comment by DJCordhose** [comment]
Thanks for the hint @greghe! Seems weird, to state the type (A) again, right? Additionally, this will not help if you only check for 'a1', forgetting about option 'a2'. But still helpful!

**Comment by philikon** [comment]
> A classic would be to forget one option of an enum (which might have been added later) or misspelling one option.

I couldn't find a separate issue for this, but I just wanted to pile on and say that this would be very nice to have. (Should I file a separate issue for this?)

**Comment by Swatinem** [comment]
Just to clarify, this is about having a similar error to what typescript provides?

```ts
declare var u: "a" | "b";
if (u === "c") {}
// error TS2365: Operator '===' cannot be applied to types '"a" | "b"' and '"c"'.
```

This would help immensely with refactoring when you are just changing/renaming the tag of a disjoint union.

**Comment by TrySound** [comment]
This is already fixed ;)
https://flow.org/try/#0C4TwDgpgBAglC8UDkBDAjEqAfZKBMmA3AFDEA2EwUKAXLCQPQNQD2A1sSgrho8+526oCJAM4B3AJbAAxgAsoAChQBKKAG9iUbVBkpR0VBjoyWAO1EsKAOjIsA5oqNIVhKACMAThBRsSO3X1DfCQTc0sbO0dhFzcvHz8tHT0DXABmUN1wqwhbBydxORAoSVEoYDlSqAp7FDIsgBMIAH5W2I9vX38dJoAzFABXMmAwixy86JQzBqhC4orS5tjiAF8gA
