### ISSUE TITLE
`const foo = foo` does not produce an error.

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1474]
This little code should produce error (in my opinion) but it doesn't.

```
const foo = foo;
```

This should not be a legal ES6 code. Also it's most often wrong.

Eslint can catch that, fortunately, with `no-use-before-define`.

**Comment by runn1ng** [comment]
No, actually, ESLint's no-use-before-define doesn't catch it for me either. (Not that it's relevant to this issue that much)

**Comment by samwgoldman** [comment]
Nice catch!

**Comment by jeffmo** [comment]
c9dbefcad9c3d124071b096ea12262325c6c31fa

**Comment by runn1ng** [comment]
Nice!

I hope this doesn't break things like

````
const fun = () => {
   if (something) {
       return fun();
   }
   return something;
}
````

But I can only try :D

**Comment by jeffmo** [comment]
Yep, I added new regression tests to make sure that continues to work
