### ISSUE TITLE
Covariance not working

### ISSUE THREAD

**Issue by jeswin** [facebook/flow#1475]
As in the following example, I am defining the return type of createServer() to be a MockServer interface (which is empty); instead of "Server" as defined in https://github.com/facebook/flow/blob/master/lib/node.js

Shouldn't this work, since an empty interface can stand in for any class?

```
/* @flow */
var http = require("http");

interface MockServer {}

type HttpModule = {
  createServer: (listener?: Function) => MockServer
}

function test(mod: HttpModule) {
  var p  = mod.createServer();
}

test(http);
```

The result of "flow check" is:
```
test.js:7
  7:   createServer: (listener?: Function) => MockServer
                                              ^^^^^^^^^^ MockServer. This type is incompatible with
689:   declare function createServer(listener?: Function): Server;
                                                           ^^^^^^ Server. See: /tmp/flow/flowlib_31ae1283/node.js:689
```

**Comment by jeswin** [comment]
Sorry about the noise, this issue is probably invalid. 

What I overlooked was this:

mod.createServer() sets the "this" pointer inside createServer() to mod. 
But "mod" in the example above is my definition of HttpModule, and not Node's Http module. 
Hence the correctness of the this pointer cannot be guaranteed inside createServer(), and flow is correct in not allowing it to pass.

If this is the reason, the error message could be fixed perhaps.

**Comment by samwgoldman** [comment]
The following code does type check:

```js
/* @flow */

var http = require("http");

interface MockServer {}

interface HttpModule {
  createServer(listener?: Function): MockServer,
}

function test(mod: HttpModule) {
  var p  = mod.createServer();
}

test(http);
```

Object types, like `HttpModule` in your example are not property-wise covariant, which is necessary for soundness because objects are mutable.

Classes and interfaces in Flow treat methods as read-only, which makes covariance for methods possible.

**Comment by jeswin** [comment]
Thanks Sam. Closing.
