### ISSUE TITLE
Property not found when modifying prototype

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#1482]
I extend the prototype of Date in the following way:

```
Date.prototype.getWeek = function () {
  var date = new Date(this.getTime());
  date.setHours(0, 0, 0, 0);
  // Thursday in current week decides the year.
  date.setDate(date.getDate() + 3 - (date.getDay() + 6) % 7);
  // January 4 is always in week 1.
  var week1 = new Date(date.getFullYear(), 0, 4);
  // Adjust to Thursday in week 1 and count number of weeks from date to week1.
  return 1 + Math.round(((date.getTime() - week1.getTime()) / 86400000 - 3 + (week1.getDay() + 6) % 7) / 7);
}
```

But on using the method Flow gives me the following error:
```
 34:     let week = now.getWeek();
                        ^^^^^^^ property `getWeek`. Property not found in
 34:     let week = now.getWeek();
                    ^^^ Date
```

The error itself seems logical to me because Flow doesn't know about this added method. Is there a way to make the error go away?

**Comment by samwgoldman** [comment]
You can write `(now:any).getWeek()` to tell Flow to shut up, but you might consider rewriting your code a bit to avoid extending the prototype. `function getWeek(date: Date): number` as a util, for example.

**Comment by hmeerlo** [comment]
Thanx for the tip. I will do the latter, that is the better solution.
