### ISSUE TITLE
Document class is missing `getSelection` method

### ISSUE THREAD

**Issue by coot** [facebook/flow#1487]
`Document.getSelection` in [mdn](https://developer.mozilla.org/en-US/docs/Web/API/Document/getSelection)

**Comment by vjefri** [comment]
Hello coot, I would love to take this on. I am a bit confused where this change needs to take place and would love some more information from you. Would you like me to add more information in the docs regarding the missing `getSelection` method? Thanks again.

**Comment by coot** [comment]
@vjefri you'd need to add it to [lib/dom.js](https://github.com/facebook/flow/blob/master/lib/dom.js), and also add a type declaration for the value it returns.

**Comment by vjefri** [comment]
Hello coot, reaching out because I would really love your feedback and next best steps on this issue. Submitted pull req but for some reason a few travis tests are failing. Would love your pro tip advice on this one. Thanks.
