### ISSUE TITLE
Flow does not follow symbolic links when requiring files. 

### ISSUE THREAD

**Issue by silfverstrom** [facebook/flow#149]
I've noticed that Flow does not seem to follow symbolic links when requiring files. 
For instance. I have a file hierarchy, 
app/
  shared_component.js
  node_modules/
  components/
    test_component.js

To access shared modules from sub-folders I've added a symlink from node_modules to app. Thus, a module in a subfolder can require using app/ as its basepath. 

``` javascript
//test_component
var SharedComponent = require('app/shared_component');
```

This code works using nodejs and browserify. However Flow does not seem to find the files and returns an error stating "Required module not found". 

If I copy the files instead of linking them, the code runs as expected.

**Comment by arypurnomoz** [comment]
Is there any workaround for this?

**Comment by leoasis** [comment]
Same problem here, it fails when testing a package that is `npm link`ed and contains flow types

**Comment by bjouhier** [comment]
I hit this one too.

This make flow incompatible with `npm link`, which is the recommended way to reference modules that are installed globally.

**Comment by galki** [comment]
`v0.68.0` symlinked dirs not resolving on windows.

also noticed that real paths outside of PROJECT_ROOT like
```
module.name_mapper='^common' -> '<PROJECT_ROOT>/../../common'
```
do not resovle - how to go about this?

**Comment by vladp** [comment]
I am not able to get module alias resolution working 
I am on windows 10





I created initially the app with create react app
`dir myrootproject\src`
```

07/10/2018  02:25 PM    <SYMLINKD>     app.src [..\..\app.src\]
07/10/2018  02:15 PM               257 App.test.js
07/10/2018  02:15 PM                68 index.css
07/12/2018  02:47 PM             1,770 index.js
07/10/2018  02:25 PM    <SYMLINKD>     js.app [..\..\..\..\rn.common\src\js.app\]
07/10/2018  02:15 PM             2,678 logo.svg
07/10/2018  02:15 PM             4,501 registerServiceWorker.js
07/10/2018  02:25 PM    <SYMLINKD>     wc.src [..\..\..\web.common\wc.src\]
```


.flowconfig 

```

[ignore]

.*/node_modules/.*
.*/build/.*
config-overrides.js
.*/src/registerServiceWorker.js
.*/src/index.js


[include]

[libs]
flow-typed

[lints]

[options]

all=true

module.system.node.resolve_dirname=node_modules
module.name_mapper='^react-native' ->'node_modules/react-native-web'
module.name_mapper='^rnjs_common/' ->'src/js.app'
module.name_mapper='^web_common/' ->'src/wc.src'
module.name_mapper='^app_src/' ->'src/app.src'


esproposal.decorators=ignore
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

suppress_type=$FlowIssue
suppress_type=$FlowFixMe



[strict]

```

I also tried

`module.system.rnjs_common.resolve_dirname= ''^rnjs_common/' ->'<absolute path eg c:\users\me\project\myrootproject\src\js.app>`
that did not help

is there a solution (my symlinks are not related to node_modules).
 ?

thank you
