### ISSUE TITLE
specify type of a property

### ISSUE THREAD

**Issue by coot** [facebook/flow#1498]
Currently this code will raise a syntax error (`Unexpected token :`):

``` js
function MyClass() {
 this.x: number = 1;
}
```

There are some workarounds:

``` js
function MyClass() {
  let x: number = this.x = 1;
}
```

or use ES6 classes

``` js
class MyClass {
  x: number;
  constructor() {
    this.x = 1;
  }
}
```

But when introducing flow to an existing code base, one might not want to rewrite all the code.

I tried to use `this.x = (1: number)` but this will not assure that the `x` property will be always of a number type.  Another possible choice is to define an interface and type use it when `MyClass` is instantiated, but then one has to remember to do that, and interfaces are structural rather than nominal, like classes are.

Though it does not seem useful, it is only because the example is very simple.  A real example in which one would like to specify type directly is when the property is a knockout observable which could hold only a specific type (knockout observables are functions with return a type `T` and which can set the stored value when given a parameter (of type `T`)).

**Comment by samwgoldman** [comment]
I think the best solution to this issue is actually the solution to #452. What do you think?

**Comment by coot** [comment]
@samwgoldman, could you be more specific, I don't see there anything that could help me here.

**Comment by avikchaudhuri** [comment]
@coot I think what @samwgoldman means is that you could do something like the following in the future (module syntax):
```
function MyClass[this: { x: number }]() {
 this.x = 1;
}
```

**Comment by coot** [comment]
Did I missed it in the docs? I think I haven't stumbled on how to specify type of this in functions.

**Comment by samwgoldman** [comment]
No, it's not implemented. The linked issue is still open. My point is that solving that issue will also solve this one.

**Comment by calebmer** [comment]
We recommend you use ES6 classes. Please let me know if you still have questions 👍
