### ISSUE TITLE
Don't assume JSX components are React components

### ISSUE THREAD

**Issue by joshaber** [facebook/flow#1504]
We're using Babel's [JSX transform](https://babeljs.io/docs/plugins/transform-react-jsx/) with [Etch](https://github.com/nathansobo/etch).

Flow believes that all of our JSX components should be React components and tries to type check them as such. Not too surprisingly, they don't type check. So we end up having to suppress a lot of Flow errors.

See an example error below.

Ideally Flow would be able to figure out based on the type of `MyComponent` that it's not a React component. Barring that, it'd be nice if we could tell Flow we're not using React so we didn't have to suppress it in each case.

```
 33:       <MyComponent
           ^ React element `MyComponent `
  5: import MyComponent from './my-component'
            ^^^^^^^^^^^ MyComponent. This type is incompatible with
 95: type _ReactClass<DefaultProps, Props, Config: $Diff<Props, DefaultProps>, C: React$Component<DefaultProps, Props, any>> = Class<C>;
                                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ React$Component. See: /private/tmp/flow/flowlib_a6c0f88/react.js:95
```

**Comment by avikchaudhuri** [comment]
@jeffmo Can we do a kind of config to control this behavior? At least on/off to begin with, but ideally the meaning of jsx could be configurable to route to any function of choice (instead of React.createElement)?

Also cc @samwgoldman

**Comment by samwgoldman** [comment]
#317 ;)

**Comment by joshaber** [comment]
@samwgoldman :metal: Feel free to close this then.

**Comment by samwgoldman** [comment]
This feature would be really good to have. Subscribe to #317 if you want a ping when it lands, but no promises on a specific timeline.
