### ISSUE TITLE
Arrays getting refined when elements are added

### ISSUE THREAD

**Issue by DanielHeath** [facebook/flow#1509]
In https://gist.github.com/DanielHeath/c376a4e37b89e2325756 , both Foo and Bar implement ReactClass. Why is flow complaining that they are incompatible in the array?

**Comment by DanielHeath** [comment]
To clarify: This worked in `0.21`.

**Comment by DanielHeath** [comment]
Both `Baz` and `Bar` extend from `React.Component`
```
 30: const First: Array<ReactClass> = [Baz, Bar]
                                       ^^^ Baz. This type is incompatible with
 30: const First: Array<ReactClass> = [Baz, Bar]
                                            ^^^ Bar
```

**Comment by DanielHeath** [comment]
I'm happy to provide more information / clarification if needed - I'm very keen to upgrade.

**Comment by calebmer** [comment]
Closing since there hasn’t been a lot of activity on this issue. We are sorry about that 😔

If you are still having issues, please reopen!
