### ISSUE TITLE
Default types for parameters

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#1513]
Right now if we omit type parameter (or use `*`) it is assumed to be `any`, even if constraint is present. It makes sense to use constraint type instead in such cases.

Example:

```js

type FeatureCollection<T: GeometryObject> = {
  type: 'FeatureCollection',
  features: Array<Feature<T>>
};

type MyCollection = FeatureCollection; // the same as FeatureCollection<GeometryObject>
```

**Comment by avikchaudhuri** [comment]
There may be some changes in this part of the design in the next release, stay tuned!

**Comment by vkurchatkin** [comment]
@avikchaudhuri I think this can be closed?
