### ISSUE TITLE
Guidance on binding class methods in constructor

### ISSUE THREAD

**Issue by tomauty** [facebook/flow#1517]
Hello. First off, thanks for Flow :)

I have a component that basically looks like this:

```javascript
export default class Root extends Component {
	constructor(props : Object) {
		super(props);
		this.state = {};
		this._handleAppStateChange = this._handleAppStateChange.bind(this);
		this.interval = null;
	}
	_handleAppStateChange() {
		const { refreshToken } = this.props;
		if (this.props.auth.token.current) {
			refreshToken();
		}
	}
}
```

And I receive the error 
`property '_handleAppStateChange' Property not found in Root.`

If I put the constructor at the bottom, flow doesn't care, but eslint does. Any help with best practices here is appreciated.

**Comment by samwgoldman** [comment]
Thanks for opening this issue. We really need to document this behavior more clearly, but let me give a high-level overview here.

Methods on classes (and interfaces) are considered to be read only by Flow. This trade-off makes covariance possible for methods, which is hugely important. If we did allow methods to be read/write, covariance would be unsound—we'd make them invariant—and other very common patterns would be type errors.

We're very aware of this autobinding pattern in React components. One workaround is to do something like this in the constructor:

```
(this:any).myMethod = this.myMethod.bind(this);
```

We are looking into ways to make this pattern possible while retaining covariance for methods.

**Comment by tomauty** [comment]
Ah okay, that makes a lot of sense. Thanks! I'll leave it up to you to close this issue.

**Comment by AgentME** [comment]
If you're using the Babel stage-1 preset and have the following in your .flowconfig:

```
[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
```

then you can do this:

```js
export default class Root extends Component {
    constructor(props : Object) {
        super(props);
        this.state = {};
        this.interval = null;
    }
    _handleAppStateChange: ()=>void = () => {
        const { refreshToken } = this.props;
        if (this.props.auth.token.current) {
            refreshToken();
        }
    };
}
```

Well, you can also go one step further:

```js
export default class Root extends Component {
    state: Object = {};
    interval: any = null;
    _handleAppStateChange: ()=>void = () => {
        const { refreshToken } = this.props;
        if (this.props.auth.token.current) {
            refreshToken();
        }
    };
}
```

**Comment by tomauty** [comment]
I've never seen an instance method declared that way. What is this about?
`    _handleAppStateChange: ()=>void = () => {`

**Comment by AgentME** [comment]
It's the proposed ES7 syntax for a property initializer (with a Flow type declaration mixed into it). Compare it to how `state` and `interval` are initialized in my second example. `_handleAppStateChange` is being initialized to an arrow function. When you use an arrow function in a property initializer, `this` is bound to the instance of the class.

**Comment by Gpx** [comment]
```js
(this:any).myMethod = this.myMethod.bind(this);
```

gives me the following error:

```
src/components/FundListGroup/FundListGroup.js:19
 19:     (this:any).renderHeaderCell = this.renderHeaderCell.bind(this)
              ^ Unexpected token :
```

As a workaround I introduced a `self` variable like so:

```js
const self: any = this
self.renderHeaderCell = this.renderHeaderCell.bind(this)
```

This seems to work.

**Comment by mmazzarolo** [comment]
Hello there,
I'm starting a new React Native and React project and this time I'm determined to use Flow.
Today I played a little with Flow and it seems that binding method to the class with arrow function (ES7) won't work (and it is the way I always used in my previous projects):
```javascript
export default class App extends React.Component {

  _test = (): void => {
    console.log('test')
  }

  render (): React.Element { // Flow error here: Unexpected identifier
    return <HomeScreen />
  }
}
```

.babelrc:
```
{
  "presets": ["react-native"],
  "plugins": ["transform-decorators-legacy", "syntax-flow"]
}
```

It seems that the alternatives are:
**1.** Biding in the constructor with `(this:any)` (Worst option for me, I tend to have a lot of binded method and this seems to be the most verbose way)
**2.**  As suggested by @AgentME :`_handleAppStateChange: ()=>void = () => {`... a bit weird?
**3.** Using the [@autobind decorator](https://github.com/andreypopp/autobind-decorator), my favorite option at the moment, even if I get the obnoxious warning from Flow: `Experimental decorator usage. Decorators are an early stage proposal that may change`

Any suggestions/options/alternative?
Thank you in advance and also thank for all the hard work you put in Flow, have a nice day!

**Comment by AgentME** [comment]
You don't have the syntax correct here:
```
  _test = (): void => {
```

`_test` is missing a type annotation, and the `: void` part isn't attached to anything. The right syntax is
```
  _test: ()=>void = () => {
```

**Comment by AgentME** [comment]
Oh, you can specify the return types of arrow functions like that. I think there might be a parsing issue with Flow there.

**Comment by mmazzarolo** [comment]
Nevermind, class properties do work, but need an ending semicolon.
Any reason for the needed semicolon? 
Babel doesn't need it and it has [already been discussed in the pas](https://github.com/babel/babel/pull/3225) and unfortunately clashes with StandardJS and other linters...

**Comment by consideRatio** [comment]
Both `a)` and `b)` works fine for when you do not have a parameter.

- a) `_test: ()=>void = () => {}`
- b) `_test = (): void => {}`

But when you do, as in `b'`, my autocomplete within Nuclide based on Flow fails to name the parameter correctly.

- a') `_test: (myText: string)=>void = (myText: string) => {}`
- b') `_test = (myText: string): void => {}`

I've tried writing code like `a)`, but my souls is being torn apart...

**Comment by mmazzarolo** [comment]
@consideRatio did you try adding an ending semicolon? it works that way for me, take a look at #1682

**Comment by pavlelekic** [comment]
The problem with () => {} solution is that those are all anonymous functions, so when you're debugging you'll see a big stack trace of anonymous functions and it would be hard for you to work like that. Also, if you're doing any sort of profiling you'll have the same problem, you'll see a sea of anonymous functions, and you would have to dive into the code to figure out which function are you looking at.

To solve that issue you could write:
`someMethodName = someMethodName(arg1, arg2, arg3) = { ... }`

There's a bit repetition there too.

**Comment by brwr** [comment]
Is there any update on handling this syntax in a constructor: `this.fn = this.fn.bind(this);`?

**Comment by mmazzarolo** [comment]
FYI on React-Native ^0.36.0 the following syntax works fine:
```javascript
export class PlaceList extends Component {
  props: {
    places: Array<Place>,
    isLoading: boolean,
    fetchPlaces: () => void,
    navigator: Object
  }

  static route = {
    navigationBar: {
      title: 'Home
    }
  }

  componentDidMount () {
    this._loadList()
  }

  _loadList = () => {
    this.props.fetchPlaces()
  }

  _handlePlacePress = (placeId: string) => {
    const { navigator } = this.props
    navigator.push('test')
  }

  render () {
    return (
      <View style={styles.container}>
        ...
      </View>
    )
  }
}
```

Even without the semicolons 🎉 !

**Comment by jedmao** [comment]
@Gpx it's `this: any` not `this:any`. You need the space or you'll see the error you're seeing. Not sure why Flow does this, but that's how it is.

**Comment by john1jan** [comment]
https://medium.com/@john1jan/react-binding-revealed-aa458df8c136#.fd5z0vmjl

**Comment by baba43** [comment]
Still not working?

The Arrow Syntax is no working alternative since it breaks hot loading.

**Comment by bradennapier** [comment]
If anyone happens to run across this.. You can at least make the syntax look a little bit nicer by implementing an interface.    Since some of these things with Flow can be maddening I figured I would write up a full overview so it can save others some time hopefully!

I ran into a situation where referencing an instance that is passed through various functions would showup as not typed by Flow:

![image](https://user-images.githubusercontent.com/15365418/32210918-66d8ac04-bdcd-11e7-8fe6-61a9cb69dea3.png)

setState is currently something like this as a method on my class (use of Object.assign here because state is a covariant property on the instance):

```js
setState = (state: $Shape<Datastream$ClientState>) => {
    Object.assign(this.state, state);
    return this;
  };
```

Where as an example our state can be 

```js
export type Dash$Identities = {
  +dealerID: string,
  +projectID?: string,
  +systemID: string,
};

export type Datastream$ClientState = {
  authToken: ?string,
  identities: ?Dash$Identities,
};
```

This can be a pretty big deal - for example -- I am using this in a back-end api where I do various validation of data structures from REST Responses, etc.  Once I validate them - flow knows the structures -- so if I do something like the setIdentities or setState on the instance - I want it to be able to validate against that structure vs what it expects... while there are no errors in the current implementation without changes, the checking simply isn't there.  

For example, its not gonna care if I do (other than the coverage warning):

![image](https://user-images.githubusercontent.com/15365418/32211058-0dc090ae-bdce-11e7-8ed7-8b7f83d65cf0.png)

So after reading this post I found that adding the redundant type right before the definition does work:

```js
setState: (state: $Shape<Datastream$ClientState>) => DatastreamClient = (
    state: $Shape<Datastream$ClientState>,
  ) => {
    Object.assign(this.state, state);
    return this;
  };
```

![image](https://user-images.githubusercontent.com/15365418/32211088-2fe4e5c2-bdce-11e7-8e53-bea4ceda7225.png)

Awesome - but ugly... I'm definitely not going to do that ugliness everywhere.... enter `interface` and `implements` ! Still typing it ttwice - but now it is at least with my type files that are imported from the type files rather than in a place that has zero value:

```js
export interface Datastream$Client {
  +identity: Datastream$ClientID;
  +state: Datastream$ClientState;
  setState: (state: $Shape<Datastream$ClientState>) => DatastreamClient;
  setIdentities: (identities: $Dash$Identities) => DatastreamClient;
}
```

and when defining the class (after importing the types):

```js
class DatastreamClient implements Datastream$Client {
    // other methods and such...
   setState = (state: $Shape<Datastream$ClientState>) => {
    Object.assign(this.state, state);
    return this;
  };

  setIdentities = (identities: Dash$Identities) => {
    this.state.identities = identities
    // continue parsing identities... 
    console.log(identities);
    return this;
  };
}
```

Success!  

![image](https://user-images.githubusercontent.com/15365418/32211436-c0d568c6-bdcf-11e7-8433-5979869c5b9f.png)

**Comment by Andarist** [comment]
@bradennapier aren't those type parameters redundant when using an interface?

**Comment by gingur** [comment]
I think this thread has gotten a bit off topic, the original request was related to best practices on how to bind in the constructor, not how to avoid using bind altogether. 

So what is suggested?

> (this:any).myMethod = this.myMethod.bind(this);

or statically attaching something like

> myMethod: Function;

or something else entirely?

There is performance/memory issues w/ using arrow functions over using bind, may be trivial or considered a pre-optimization but the decision shouldn't be influenced based on using Flow.
