### ISSUE TITLE
Display types inferred by Flow

### ISSUE THREAD

**Issue by Juiblex** [facebook/flow#1518]
Hi,

Running flow with option `suggest` prints out a type-annotated diff on your file (as I understand it).
But are those types the types that Flow inferred for each declared variable?
If not, would it be possible to add an option that does that?
For example, with code

     function f(x) {
         return x.bar;
     }
     var x = {foo:1};
     f(x);

`flow suggest` displays type `function g(x: {foo: number})` when I would expect `function g(x: {bar: number})`. Or does the type inference algorithm just not work that way?

Thanks!

**Comment by AgentME** [comment]
It looks like it's ambiguous whether it's the caller or the implementation of the function that's right and which one is wrong. The mistake could be in either. I don't think Flow is wrong to pick either interpretation.

**Comment by Juiblex** [comment]
Yeah, of course, I agree with that (hence my second question). That was kind of the example I had at hand at the moment, maybe I phrased my question wrong.
My main question was whether or not those were the types actually inferred by the type inference algorithm, and whether there would be an option to display all inferred types in a file (in a more readable format than a diff with the original un-annotated source).

But thanks anyway for your quick answer!

**Comment by avikchaudhuri** [comment]
@Juiblex yeah the type inference algorithm basically does data flow, and keeps enough info around for type checking, but when synthesizing types for `suggest` it only looks at values flowing in (it doesn't summarize based on uses flowing out). When your program doesn't have errors this works well enough, so try getting rid of errors first before running `suggest`! (You can use `type-at-pos` while debugging.)
