### ISSUE TITLE
command line flag emulates "// @flow" in files

### ISSUE THREAD

**Issue by raould** [facebook/flow#1519]
I don't want to have to somehow go edit all the .js files in our project just to put "// @flow" at the top of them. But if I don't do that, flow apparently does nothing? Could there not be a command line flag that turns on checking no matter what? That would be nice, I think.

**Comment by mroch** [comment]
Nice to hear that you want to go all-in on flow! Is it a new project? It makes a lot more sense for flow to be "opt out" (@flow by default) when starting from scratch, and more sense for it to be "opt in" (have to add @flow) when gradually converting an existing project. So, agreed 100% that it should be configurable.

The `--all` flag should do what you want. There's also https://github.com/facebook/flow/issues/284 tracking making it a `.flowconfig` option.

**Comment by raould** [comment]
Thanks, apparently I am on 0.15.0 and there's no "--all" flag (I did check for such things in the version I had before opening the issue, but I guess I should have also checked on the version, it figures. :-)

**Comment by raould** [comment]
P.s. homebrew installs 0.17.0 which still does not seem to have "--all" anywhere?

**Comment by raould** [comment]
P.p.s. 
```
$ npm install -g flow-bin
$ flow --version
Warning: `flow --version` is deprecated in favor of `flow version`
Flow, a static type checker for JavaScript, version 0.22.1
$ flow --all
flow: unknown option '--all'.
```

**Comment by mroch** [comment]
oh, it's a flag to `flow check` and `flow server`, but not `flow` or `flow status`. The latter are commands that talks to an already-running server, and it can't switch the mode after the server has started.

those flags should exist in 0.15 and 0.17, but you should definitely try to upgrade. homebrew does have the newer version (https://github.com/Homebrew/homebrew/blob/0e3d72581dc8f4c7c96ab194cc021977c262f22a/Library/Formula/flow.rb) so you probably just need to `brew update`. you can also install from npm with the `flow-bin` package.

**Comment by raould** [comment]
I see re: server, thanks!

**Comment by raould** [comment]
(p.s. if the "--all" could become a 'client' option, instead of a global 'server' setting, i think that would be nifty.)
