### ISSUE TITLE
Default export in interface file

### ISSUE THREAD

**Issue by karel-3d** [facebook/flow#1522]
I want to write an interface file for a module that has a default export.

I want to do something like this.

```
declare module 'external-module' {
    declare export default var foo: number;
}
```

I have tried various variations of `declare`, `export` and `default` and nothing seems to work.

**Comment by avikchaudhuri** [comment]
See this test for some examples. Unless there's another solution I'm not remembering right now, this is what we have and use right now, it's kind of hacky and we should have more formal syntax for this.

https://github.com/facebook/flow/blob/f1273c67638b5403973a496e30b4a3fe8dfe19bc/tests/export_default/lib/lib.js

**Comment by davidtheclark** [comment]
I'm confused by this, as the documentation suggests a syntax that Flow apparent rejects. When I try any of the `declare export` examples provided in https://flow.org/en/docs/libdefs/creation/#toc-declaring-an-es-module, I get `Library parse error`s.

**Comment by TrySound** [comment]
This is how es modules work. Nothing to do with flow.
```
declare module 'external-module' {
    declare var foo: number;
    declare export default foo;
}
```
