### ISSUE TITLE
Way to type React higher-order component functions?

### ISSUE THREAD

**Issue by paulshen** [facebook/flow#1523]
Is there a way to type higher-order component functions in React?

```javascript
type MyComponentProps = {
  foo: number,
  bar: string,
};
class MyComponent extends React.Component<void, MyComponentProps, void> {
  render() {
    return <div>{this.props.foo} {this.props.bar}</div>;
  }
}

function withBar(ComposedComponent) {
  return class WithBar extends React.Component {
    render() {
      return <ComposedComponent {...this.props} bar="test" />;
    }
  }
}

const MyWrappedComponent = withBar(MyComponent);

<MyComponent />; // hopefully complains about not having foo
<MyComponent foo={3} />; // hopefully no complaints
```

Thanks!

**Comment by bsr203** [comment]
does the last example in doc answers you http://flowtype.org/docs/react.html#_

**Comment by paulshen** [comment]
It doesn't for me. What I'm looking for, more accurately, is how to type decorators that are applied to the class (and therefore all subsequent instances) versus a single-use HOC.

**Comment by janv** [comment]
I'm also running into this problem.

When decorators (or React.cloneElement situations) add props to an element, there's a discrepancy between the props observable from _inside_ the component and the props expected from the _outside_ of the component, with currently no way to declare types that satisfy both sides.

I tried getting around it by giving my decorated component a different type from the undecorated component:

```js
type TemplateProps = {
  template: TemplateDef,
  connectDragSource: Function
};

class Template extends React.Component<void, TemplateProps, void> {
  ...
}



type DraggableTemplateProps = {
  template: TemplateDef
};

var DraggableTemplate: typeof React.Component<void, DraggableTemplateProps, void>;
DraggableTemplate = DragSource(...)(Template)
```

However, Flow will complain about an "unexpected typeof Expression".
I'm sure Flow has some undocumented features that would make this work. When I peek into the Flow definition Files for react, I see a lot of undocumented Syntax in there. Maybe there's a way to tell Flow what `DraggableTemplate` is, using that?
