### ISSUE TITLE
property `toBlob`. Property not found in HTMLCanvasElement

### ISSUE THREAD

**Issue by salzhrani** [facebook/flow#1531]
I am using `toBlob` polyfill found [here](https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob). and I get the following error
```js
 53: 		HTMLCanvasElement.prototype.toBlob = function toBlob(callback, type, quality) {
     		                            ^^^^^^ property `toBlob`. Property not found in
 53: 		HTMLCanvasElement.prototype.toBlob = function toBlob(callback, type, quality) {
     		^^^^^^^^^^^^^^^^^^^^^^^^^^^ HTMLCanvasElement
```
also tried `defineProperty` with the same error

```js
 40: 		Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
     		                                                   ^^^^^^^^ property `toBlob`. Property not found in
 40: 		Object.defineProperty(HTMLCanvasElement.prototype, 'toBlob', {
     		                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^ HTMLCanvasElement
```

although `toBlob` is present in flow and I don't know how to address or workaround this error

**Comment by samwgoldman** [comment]
Interesting. What version of Flow are you using? It looks like the definition for `toBlob` was [added recently](https://github.com/facebook/flow/blame/65df15357e20c560d9e8b9309b275d8b42f79cc1/lib/dom.js#L734) and should be available in the 0.22.1 release (latest).

**Comment by samwgoldman** [comment]
Oh, sorry. I see what's going on.

Flow treats class methods as read-only, separately from properties. The "property not found" error is a little misleading for this reason.

I'd recommend opting out of Flow for polyfills like this. Should be as simple as putting the polyfill in a file that doesn't have a `/* @flow */` pragma at the top. HTH!

**Comment by salzhrani** [comment]
Thank you.
