### ISSUE TITLE
autocomplete "sometimes" not working accross module boundaries

### ISSUE THREAD

**Issue by FossiFoo** [facebook/flow#1534]
Unfortunately i haven't been able to pinpoint this to a cause. (v 0.22.1)

Sometimes flow autocomplete just comes up empty on the following code, while it works on a copy of the same directory.

bar.js:
`/* @flow */
export type Bar = { baz: string; }`

foo.js
`/\* @flow */

import type {Bar} from "./bar";

var a : Bar = {baz: "a"};
a.
`

In one directory (the copy), the ouput is as expected:

`flow autocomplete --json 9 3 < src/foo_completing_barish.js 
{"result":[{"name":"baz","type":"string","func_details":null,"path":"/home/cmewes/projects/betty/betty_ordercapture_ui/master/foo/src/bar.js","line":3,"endline":3,"start":26,"end":31},{"name":"hasOwnProperty","type":"(prop: any) => boolean","func_details":{"return_type":"boolean","params":[{"name":"prop","type":"any"}]},"path":"/tmp/flow/flowlib_bd9b1e4/core.js","line":48,"endline":48,"start":5,"end":38},{"name":"propertyIsEnumerable","type":"(prop: any) => boolean","func_details":{"return_type":"boolean","params":[{"name":"prop","type":"any"}]},"path":"/tmp/flow/flowlib_bd9b1e4/core.js","line":49,"endline":49,"start":5,"end":44},{"name":"toLocaleString","type":"() => string","func_details":{"return_type":"string","params":[]},"path":"/tmp/flow/flowlib_bd9b1e4/core.js","line":50,"endline":50,"start":5,"end":28},{"name":"toString","type":"() => string","func_details":{"return_type":"string","params":[]},"path":"/tmp/flow/flowlib_bd9b1e4/core.js","line":51,"endline":51,"start":5,"end":22},{"name":"valueOf","type":"() => Object","func_details":{"return_type":"Object","params":[]},"path":"/tmp/flow/flowlib_bd9b1e4/core.js","line":52,"endline":52,"start":5,"end":21}]}`

In the other it is just empty.

`$ flow autocomplete --json 9 3 < src/foo_completing_barish.js 
{"result":[]}`

Following  is the output of dump-types, which is the same in both:
`$ flow dump-types src/foo_completing_barish.js 
foo/src/foo_completing_barish.js:5:1-27: [type: {quux: number}]
foo/src/foo_completing_barish.js:7:5-11: {baz: string}
foo/src/foo_completing_barish.js:7:15-24: {baz: string}
foo/src/foo_completing_barish.js:7:21-23: string
foo/src/foo_completing_barish.js:8:5-11: {quux: number}
foo/src/foo_completing_barish.js:8:15-23: {quux: number}
foo/src/foo_completing_barish.js:8:22: number
foo/src/foo_completing_barish.js:9:1: {baz: string}
foo/src/foo_completing_barish.js:9:1,10:0:`
`

From this i expect the autocomplete to be able to work.

I tried to restart the server and delete /tmp/flow/*. Is there any caching or such that might also influence this behaviour? Is there a way to generate more debug output during "autocomplete"? Both --verbose and --debug do not seem to print anything at all.

**Comment by gkz** [comment]
We've made a variety of improvements to autocomplete, let us know if you're still having issues.
