### ISSUE TITLE
Type Refinements with Switch not Preserved in new Function Scope

### ISSUE THREAD

**Issue by garetht** [facebook/flow#1535]
To reproduce, begin by creating one or two types with literal types so that we can refine them with a switch statement:
```js
type TestAction = {
    type: 'test';
    position: number;
}
type TestActionTwo = {
    type: 'test2';
    name: string;
}
type TestActions = TestAction | TestActionTwo;
```

Then, run the typechecker on this function. It succeeds. 
```js
function test(action: TestActions): void {
    var state;
    switch(action.type) {
        case 'test':
            var p = action.position;
            state = function() {p};
            break;
        case 'test2':
            var n = action.name;
            state = function() {n};
            break;
        default:
            break;
    }
    return;
}
```

But once we move the access of the `position` and `name` properties of the `action` object into the body of the function that is later assigned to `state`, the typechecker throws an error:

```js
function test(action: TestActions): void {
    var state;
    switch(action.type) {
        case 'test':
            state = function() {action.position}; // property `position` property not found on object type
            break;
        case 'test2':
            state = function() {action.name}; // property `name` property not found on object type
            break;
        default:
            break;
    }
    return;
}
```

This was reproduced on `tryflow.org`, but a similar problem was encountered running Flow 0.22.1.

**Comment by samwgoldman** [comment]
This is a FAQ. See the documentation here: http://flowtype.org/docs/dynamic-type-tests.html#caveats

Since objects are mutable, it's not safe to assume that `action` will still have the same properties when captured by a function that may run later.

In this case, the `state` function never escapes its scope (and is never invoked), so it's technically "safe" here and Flow is being overly pessimistic, but this is not safe in general.

**Comment by garetht** [comment]
Ah yes got it. I probably even read that before. Thanks and sorry about that!
