### ISSUE TITLE
[Docs] Clarification on Array Syntax needed

### ISSUE THREAD

**Issue by clentfort** [facebook/flow#1537]
In the docs two versions to specify an array are used: 

- [`T[]`](http://flowtype.org/docs/syntax.html#function-declarations)
- [`Array<T>`](http://flowtype.org/docs/arrays.html#type-annotating-arrays). 

IMHO this could lead to confusion and only one of the two ways should be used. (Why are there even two ways of doing this?)

**Comment by gabelevi** [comment]
We support `T[]` for TypeScript compatibility, though we tend to lean towards `Array<T>` ourselves, since we find it easier to read (`Array<T>` has no precedence ambiguity and when `T` is a long type expression the `[]` can be hard to spot).
