### ISSUE TITLE
files and directories specifiable on command line

### ISSUE THREAD

**Issue by darrenderidder** [facebook/flow#154]
Using the /\* @flow */ header directive to control selective file processing is quite awkward. For integration into existing toolchains it would be preferable to support the specification of directories and/or files as command line arguments in the traditional unix fashion, ie.:

   flow check [OPTION]... [ROOT | file | pattern]...
   flow check ./
   flow check libs/ demo/
   flow check src/*.js

**Comment by cletusw** [comment]
This needs to be reopened.

**Comment by wi-ski** [comment]
Please.
