### ISSUE TITLE
Example project for loading 3rd party libraries

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/flow#1540]
Hello, 

I'm going through the documentation for flow in order to understand how to include third party libraries like mentioned in the Docs under [ThirdParty](http://flowtype.org/docs/third-party.html). Is there an example file or project on github that contains a sample flowconfig and files?

**Comment by samwgoldman** [comment]
Hi, @kennetpostigo. Yes. You can check out a number of Facebook open source projects, like relay, graphql-js, nuclide, and draft.js.

There's also a really cool [starter kit](https://github.com/davezuko/react-redux-starter-kit) for React/Redux/Flow projects.

Hope this helps!

**Comment by kennetpostigo** [comment]
Thank you @samwgoldman
