### ISSUE TITLE
(possible) Strange behavior for type inference

### ISSUE THREAD

**Issue by otbe** [facebook/flow#1541]
Hi everyone,

Im observing a possible strange behavior when using type inference.
```
let age: number = 40;
let myAge = age;
```

Now the following throws an error:
```
let o = myAge.length;
```
Thats fine, because ```number``` does not have a length field.

But the following throws no error:
```
myAge = 'test';
```

```myAge``` should be typed as ```number``` by type inference, shouldn't it ?

Im running the most recent version of flow.

**Comment by samwgoldman** [comment]
@otbe Thanks for providing such a complete explanation.

This is the expected behavior. Assigning a string to `myAge` doesn't cause an error at runtime, which is the argument for accepting this code.

In fact, after assigning '"test"' to `myAge`, Flow understands that `myAge` is exactly a string—using it as a number will cause a type error.

Does this answer your question?

**Comment by donaldpipowitch** [comment]
This isn't what I would expect and I think TypeScript behaves differently here. Would it be possible to reconsider this default behavior or make it a more strictly opt-in through additional syntax? Maybe something like `let age: !number = 40;`, so that you can't assign a new type?

**Comment by samwgoldman** [comment]
Allowing this seems strictly better to me. It allows more correct programs to type check while also rejecting unsound programs. Why be stricter than necessary to ensure soundness?

**Comment by aluanhaddad** [comment]
> This isn't what I would expect and I think TypeScript behaves differently here. Would it be possible to reconsider this default behavior or make it a more strictly opt-in through additional syntax? Maybe something like let age: !number = 40;, so that you can't assign a new type?

Indeed, TypeScript errors on code like this. For my part, I think that while it's perfectly valid JavaScript, it's very poor code and I would want a type error. How often is this kind of code not a bug. Even in the unprecedentedly dynamic JavaScript language, this behavior is not really useful. It might be useful if you could pass parameters by reference, but JavaScript does not support that.
