### ISSUE TITLE
.js.flow declaration "leaks" imported types

### ISSUE THREAD

**Issue by marudor** [facebook/flow#1543]
Flow seems to leak a imported type in a .js.flow.
Reference commit in my libdefs: https://github.com/marudor/flowInterfaces/commit/640224bbecf8a85ea11e826026efd40ba7ca8afa
Basically if I use

``` js
import { EventEmitter } from 'events';
```

flow know EventEmitter outside of this file. If I create a class that extends EventEmitter (a different one imported from somewhere else) flow fails to correctly check.
Looked like it it used both definitions for EventEmitter for type checking.

**Comment by samwgoldman** [comment]
Thanks! I think this is part of a bigger issue, in which we don't provide an official way to set up dependencies between library definitions. I'm going to create a separate issue for that and merge this one in, because it's a fairly important issue that we should track.

**Comment by samwgoldman** [comment]
Sorry, I just saw that @jeffmo asked you to open this. Reopening, since he said he'd look into it. :)

**Comment by danez** [comment]
I think this is the same issue as #1425.

**Comment by calebmer** [comment]
Closing since there hasn’t been a lot of activity on this issue. We are sorry about that 😔

If you are still having issues, please reopen!

We also support imports in `declare module` which should help resolve this.

**Comment by migueloller** [comment]
This is still a huge issue. Even if there hasn't been a lot of activity, shouldn't it be tracked somewhere? 

Is there a different issue where this problem is being tracked? Should this issue be reopened?
