### ISSUE TITLE
Support function bind syntax (stage 0)

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1545]
https://github.com/zenparsing/es-function-bind

People ask for this regularly, but the proposal is still stage 0 and somewhat controversial. We have no plans to do this work until either a) it advances to stage 3 of b) we see a groundswell of support for this issue (reactions welcome).

**Comment by bordoley** [comment]
Interesting to note that the RxJs team is actively encouraging use of the bind operator as a best practice with the [RxJS beta 5](https://github.com/ReactiveX/RxJS).

**Comment by samwgoldman** [comment]
That's bold, since the proposal is still stage 0. That doesn't really change my feelings about Flow support.

**Comment by mmazzarolo** [comment]
It's true that supporting a stage 0 feature might be a risky move, but in my opinion flow should support at least one kind of not-too-much-verbose binding syntax (spoiler alert: this post is related to #1517)

**Comment by Anahkiasen** [comment]
I don't mind Flow not supporting this but could it at least be ignored the same way decorators can be? Currently any file with a `::` just crashes, and that can quickly be very problematic. That's the current reason preventing me from using Flowtype personally.

**Comment by marudor** [comment]
PR - WIP.
Parser support exists.
https://github.com/facebook/flow/pull/1675

**Comment by LikeJasper** [comment]
If not included, at least a way to suppress the parsing error would be great. See #662

**Comment by vkurchatkin** [comment]
Decorators can be ignored because they are not statements or expressions, and in a lot of cases they are only used to attach some metadata, so flow can simply behave if they are not there. This is not true for bind operator, stripping it off will simply make your code incorrect in most cases.

**Comment by appsforartists** [comment]
eslint let's you specify a parser (e.g. Babel) that understands syntaxes it doesn't.  That way, you can use experimental/bespoke syntactic sugars without breaking the tooling.  I wonder what that would look like in Flow.  Maybe Flow could use Babel + source maps to understand the translated code but still put the errors in the correct place in your original file.  Not sure what the impact would be on speed though.

**Comment by jsheetzati** [comment]
:: is pretty common in React examples.  Surprised flow doesn't support it.

**Comment by iansinnott** [comment]
> could it at least be ignored the same way decorators can be?

Completely agreed with @Anahkiasen. The fact that ignore comments like`// $FlowFixMe` cannot be used to suppress these errors means that just one use of `::` in a file and the whole file must be ignored.

Maybe instead of ignoring this syntax globally Flow could simply allow suppression.

**Comment by salanki** [comment]
```
Currently any file with a :: just crashes, and that can quickly be very problematic. That's the current reason preventing me from using Flowtype personally.
```
+1

**Comment by DarrylD** [comment]
any progress on this?

**Comment by gajus** [comment]
There are a lot bigger priorities (like solving all the existing bugs) than catering for bleeding edge (stage 0) proposals.

This proposal does not even have a champion (https://github.com/tc39/proposal-bind-operator/issues/24).

**Comment by goooseman** [comment]
Instead of writing

```
class Test extends React.Component {
  _foo () {console.log(this)}
  render () {
    return <Bar foo={::this._foo} />
  }
}
```

You can use

```
class Test extends React.Component {
  _foo = () => {console.log(this)}

  render () {
    return <Bar foo={this._foo} />
  }
}
```

This works fine: the function gets `this` context and Flow works with it fine.

**Comment by pronebird** [comment]
We use `::` a lot. Is there any way to silence this error at least?

**Comment by DiMoNTD** [comment]
We use :: a lot too. Is there any way to silence this error at least?

**Comment by smikhalevski** [comment]
I created a tiny example of how flow **can be used** with function bind operator https://github.com/smikhalevski/flow-function-bind.

In my projects I heavily use `::` and lack of its support in Flow is frustrating. So +1 for adding this feature to the core!

**Comment by ticky** [comment]
I’d like to put down a vote for including this, too. We’re making use of the syntax in buildkite/frontend and right now this limits our ability to adopt Flow in any serious manner, as it simply chokes on some of our code.

I have ended up down a weird rabbit hole of adapting @smikhalevski’s approach to work with SublimeLinter as well as in CI using an intermediary script which pipes Babel output into Flow, and unfortunately using Babel to transform _just_ this bit of code changes our code’s layout sufficiently that we end up with output in weird places!

**Comment by mroch** [comment]
I have no objection to this once the proposal progresses, but for now it seems pretty dead. I'm going to close this issue and we can certainly reopen it if there is any activity on it at TC39.
