### ISSUE TITLE
Stale/badly formatted docs on http://facebook.github.io/flow/

### ISSUE THREAD

**Issue by winkler1** [facebook/flow#1546]
![image](https://cloud.githubusercontent.com/assets/883896/13855571/7a56d80e-ec47-11e5-92c4-b398e56099a2.png)

.. should redirect to http://flowtype.org/?

**Comment by mroch** [comment]
facebook.github.io supports https but flowtype.org doesn't (a limitation of github pages), so we shouldn't redirect. tracking fixing the absolute URLs that are breaking this in #584, so gonna close this one. thanks, though!
