### ISSUE TITLE
Object subtyping rules

### ISSUE THREAD

**Issue by dimvar** [facebook/flow#1550]
The docs mention that Object is a supertype of the other object types. However, it sometimes can act as a subtype, eg, I can assign from Object to Foo in the example below without errors. But I do get an error when I pass an Object to a function that takes a Foo. Bug or feature?

```
// @flow

class Foo {}

function f(x: Foo, y: Object) {
  x = y; // was expecting error here, got nothing
}

function g(x: Foo) {}
g(new Object); // error as expected
```

**Comment by dimvar** [comment]
This is with the latest release, v0.22.1.

**Comment by samwgoldman** [comment]
Ah, thanks for the report! It's a docs bug. `Object` is a supertype _and_ a subtype of object types, by design. [The typing rule](https://github.com/facebook/flow/blob/33c5383e6d85110c8ae2a4719e19cffb14e40686/src/typing/flow_js.ml#L1327), for reference.

I will be sure to update the docs. The same behavior is true of `Function`, which has the same docs bug.

**Comment by samwgoldman** [comment]
Aside, I wish we had named this type `AnyObject` instead. We could certainly have a `MixedObject` type—do you think that would be generally useful?

**Comment by dimvar** [comment]
If Object is a subtype of all objects, shouldn't we be able to pass it to a function that takes a Foo?

> We could certainly have a MixedObject type—do you think that would be generally useful?

In Closure Compiler, the Object type is the top object (the MixedObject as you say) and we don't have an AnyObject type. Has worked out OK for us. I don't have strong evidence in favor of one or the other though.

**Comment by samwgoldman** [comment]
> If Object is a subtype of all objects, shouldn't we be able to pass it to a function that takes a Foo?

The type of `new Object` isn't `Object`, confusingly. It's `{}`.

> In Closure Compiler, the Object type is the top object

Our model is a bit unintuitive here, because we don't treat everything as an object. `number`, for example, isn't a subtype of `Object` or `{}`, but is a subtype of `any` and `mixed`. It sounds like `mixed` is the Flow equivalent of Closure Compiler's Object type.

**Comment by dimvar** [comment]
> The type of new Object isn't Object, confusingly. It's {}.

Oh, I would never have guessed that :)

> we don't treat everything as an object.

We don't either; number is not a subtype of Object in Closure Compiler.

> It sounds like mixed is the Flow equivalent of Closure Compiler's Object type.

AFAIU, Flow's mixed is the same as Closure Compiler's top type, written *.

I'm looking into these things because I'm trying to document the differences between the two type systems. I'll keep you posted.

**Comment by samwgoldman** [comment]
> I'm looking into these things because I'm trying to document the differences between the two type systems.

Oh, great! Looking forward to that.

**Comment by samwgoldman** [comment]
Oh, and since you're getting into the weeds here, let me add that the type of `new Object` and the literal expression `{}` is considered [unsealed](http://flowtype.org/docs/objects.html#sealed-object-types). That's a dimension of the type which isn't exposed in the type annotation.

**Comment by gkz** [comment]
`Object` is now just an alias for `any`, and deprecated. You can make it an error with the `unclear-type` Flow lint rule. You can check the docs on arbitrary objects: https://flow.org/en/docs/types/objects/#arbitrary-objects
