### ISSUE TITLE
 Nuclide's Autocomplete failed with flow's `lib/react.js`.

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#1552]
I have a same [issue #417](https://github.com/facebook/nuclide/issues/417) in `nuclide` previously,and nuclide confirmed this is belong to `flow`. 
The problem happened when  Nuclide's Autocomplete work with flow's `lib/react.js`.
When lib/react.js is short enough, Autocomplete will work right:
When lib/react.js get longer,Autocomplete will fail, seems caused by nuclide directly use the contents of module as the type hint for something imported from a module.( seems failed with some complex syntax ? )

I tested this issue with `flow's Repository`,these are results:
**With short  `lib/react.js` like this,Autocomplete work correctly:**

```
declare module react {
  declare var Children: any;
  declare var DOM: any;
  declare var PropTypes: ReactPropTypes;
  declare var version: string;
  declare function initializeTouchEvents(shouldUseTouch: boolean): void;
}
```

the type is shown like:
![r1](https://cloud.githubusercontent.com/assets/8873545/13881234/f23eebba-ed17-11e5-808d-f2442b28c9e4.png)
and Autocomplete is shown as:
![screenshot from 2016-03-18 14-08-27](https://cloud.githubusercontent.com/assets/8873545/13881302/5181108a-ed18-11e5-8527-7b2e94541bef.png)

**With full long contents of `lib/react.js`** as [flow's react.js#L148](https://github.com/facebook/flow/blob/master/lib/react.js#L148) **Autocomplete failed**:
no Autocomplete information for module,and the type hint is shown as any
![r_any](https://cloud.githubusercontent.com/assets/8873545/13881432/cd1a10fc-ed18-11e5-9c09-ba720e5415fb.png)
 (as a module,the type should be any,but seems marked it with `module 'react'` should be better? or give it a typename as descibed below?)

[modified react.js#L148 `declare type React`](https://github.com/iamchenxin/flow/blob/nuclideFlow/lib/react.js#L148),will give it a type like this have some help in resolution?

```
declare module react {
  declare type React = {
      Children: any;
      DOM: any;
  };
  declare var exports: React;
}
```

though as directly imported , the result will be an `object type`. but this will give an additional type `React` which can be imported.

**Comment by graphman65** [comment]
I have the same issue using the last version of both flow and nuclide.
I guess it's a important issue as flow is mainly used with react.
