### ISSUE TITLE
[question] What to do with EventEmitters?

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#1554]
I kind of like Node's EventEmitters, because they allow to abstract a lot of things easily; however, I strongly dislike how it's impossible to statically typecheck them with Flow.

For example, I have an event like this

`emitter.emit('click', {x, y})`

with `x,y` being coordinates; and on the other end, I want to do

`emitter.on('click', ({x, y}) => { /*something*/ })`

However, I don't want to, by mistake, do this:

`emitter.on('click', (x, y) => { /*something*/ })`

Or, I want to change the format of emitted object, etc. Basically everything Flow is for.

I have not idea how to solve this. Of course I can build my own class like this and reimplement EventEmitter _(note: I am writing it now so it might not be 100% correct)_:

````
export type Coordinates = {
  x: number;
  y: number;
};

type CoordinatesFun = (c: Coordinates) => void

class ClickEmitter {
  onceFunctions: Array<CoordinatesFun> = [];
  functions: Array<CoordinatesFun> = [];
  once(f: CoordinatesFun) {
    onceFunctions.push(f);
  }
  on(f: CoordinatesFun) {
    functions.push(f);
  }
  emit(c: Coordinates) {
    functions.forEach(fun => fun(c));
    onceFunctions.forEach(fun => fun(c));
    onceFunctions = [];
  }
}
````

but doing it explicitly for every possible actions removes the easiness of EventEmitters, even when I could make it easier by using generics. Also it's error-prone, etc.

There might be some other concept that is similar to EventEmitters that is more easily typecheckable, but I don't know it. 

I would love to somehow write "this is the list of events this emitter is emitting, and it has these types of objects." - something like `EventEmitter<{'click': ({x: number, x:number})}>`, something like that.

**Comment by runn1ng** [comment]
But it seems I am not the first one to want this - https://github.com/facebook/flow/issues/1295 :cry:

**Comment by runn1ng** [comment]
It seems there are some wrappers for eventemitters for typescript, I am not sure how they work, but they could be of help

https://www.npmjs.com/package/ts-eventemitter

(I just found this, so I am not sure how good idea is this)

**Comment by runn1ng** [comment]
I have tried to use the above module with flow with minimal changes, and it seems it's not possible, since Flow and TypeScript logic is slightly different. Not that much, but the subtle differences are big enough to render that useless.

So it's impossible to use that module directly only with flow definition file (or, I am not able to write one).

Now maybe I could write my own one :) but... don't have the time to do that at the moment

**Comment by runn1ng** [comment]
Ha, in the end, I made this -  https://github.com/runn1ng/flow-events

Feel free to use it, or make it better, etc :)

**Comment by samwgoldman** [comment]
@runn1ng Nice stuff! I think this is a great example of an unsafe/dynamic API that can be made safe with a small wrapper API.

Is there any other action item here, or can this be closed?

**Comment by runn1ng** [comment]
I am closing.
