### ISSUE TITLE
Classes should inherit from Function

### ISSUE THREAD

**Issue by bfdill** [facebook/flow#1561]
I'm trying use code that can be simplified to this:

``` javascript
var foo = Array.apply(null, [1,2]);

// And I'm receiving the following error:
index.js:3
  3: var foo = Array.prototype.apply(null, [1,2]);
                               ^^^^^ property `apply`. Property not found in
144: declare class Array<T> {
     ^ Array. See: /private/tmp/flow/flowlib_62cf125/core.js:144
```

**Comment by jeffmo** [comment]
Summary of the problem: `Array` is both callable and constructable -- so the static `Array` global is a function with a proto chain that points to `Function.prototype`.

To fix this we should make sure that all class objects *statically* inherit from "Function"

**Comment by samwgoldman** [comment]
Agreed. I editorialized the title to reflect the actual incompleteness here.

**Comment by mroch** [comment]
given `class Foo { constructor() {} }`, `Foo()` throws a TypeError (per [ES6 § 9.2.1.2](http://www.ecma-international.org/ecma-262/6.0/#sec-ecmascript-function-objects-call-thisargument-argumentslist)), so I'm not sure all classes should inherit from `Function`. Seems like only class-like functions like `Array`, `String`, `Date`, etc. should allow this.

**Comment by samwgoldman** [comment]
Yeah, `Foo` isn't callable (callable constructors is a proposal), so `Foo.bind`, etc., all work but when they are eventually invoked it is a runtime error. `Foo instanceof Function` is `true`, however. Whether we want to model that is questionable.

**Comment by jedwards1211** [comment]
Even in that case, "property `apply` is not found in ..." is technically incorrect, and may confuse developers.  Technically correct error messages would be "class constructor functions are not callable" and "Flow rejects `bind` on constructor functions because they aren't callable".

**Comment by SamChou19815** [comment]
The original example no longer errors, and Function is now an alias of any so the proposal no longer makes sense.
