### ISSUE TITLE
support for checking a named file or set of files

### ISSUE THREAD

**Issue by raould** [facebook/flow#1568]
I might be confused, but I haven't seen how to do e.g. "flow x.js", it seems to always check every file around? It would be nice if I could do "flow x.js" and it wouldn't hit e.g. the y.js in the same directory. And also support of course a set of files to check e.g. "flow x.js y.js".

**Comment by calebmer** [comment]
You can use `flow focus-check` for this in the latest version of Flow. It currently only allows a single file name, but we will be adding support for multiple files soon 😊
