### ISSUE TITLE
union types in properties of interfaces

### ISSUE THREAD

**Issue by coot** [facebook/flow#1569]
With the following interface I am getting an error:

```
declare interface A {
 a: null | 'a',
};

let a: A = {a: null};
```

However if I change `interface` into `type` the code type checks.

**Comment by avikchaudhuri** [comment]
I suspect that this is not a union type bug, but instead an incompleteness. We fire a special subtyping rule for object types to make this code typecheck, but fail to do the same for interfaces.

**Comment by SamChou19815** [comment]
This now works, probably for a while
