### ISSUE TITLE
Infer across files

### ISSUE THREAD

**Issue by OliverJAsh** [facebook/flow#157]
I have two CommonJS modules:

``` js
// partial.js
/* @flow */

function foo(x) {
  return x*10;
}

exports = module.exports = foo;
```

``` js
// main.js
/* @flow */

var foo = require('./partial');

foo('bar');
```

Flow does not infer the types for `foo` when it is `require`d (CommonJS):

```
$ flow check

/Users/Oliver/Downloads/flow/examples/01_HelloWorld/partial.js:3:14,14: parameter x
Missing annotation

/Users/Oliver/Downloads/flow/examples/01_HelloWorld/partial.js:3:16,16: return
Missing annotation

Found 2 errors
```

If the `foo` function is moved into the same file as the function invocation, Flow will infer:

```
$ flow check

/Users/Oliver/Downloads/flow/examples/01_HelloWorld/hello.js:7:5,9: string
This type is incompatible with
  /Users/Oliver/Downloads/flow/examples/01_HelloWorld/hello.js:4:10,13: number

Found 1 error
```

**Comment by leoasis** [comment]
@avikchaudhuri I'm having this same problem here: https://github.com/facebook/flow/issues/157. If type inference across files doesn't work, is there any way to write a type signature that satisfies the examples there with the same behavior as the inferred one?

**Comment by ccorcos** [comment]
+1 -- why not infer across files?!
