### ISSUE TITLE
using `Object.assign` does not work with arrays anymore.

### ISSUE THREAD

**Issue by despairblue** [facebook/flow#1571]
``` js
/* @flow */
'use strict'

const works = Object.assign([], {})
const kaputt = Object.assign([], [])

module.exports = exports = {
  works,
  kaputt
}
```

This used to work with before [this commit](https://github.com/facebook/flow/commit/3c39e0e2a43f5b583983a8647a310741a838d340#diff-f265d6a6b6b64d4d096fddcf7d620a76).

**Comment by calebmer** [comment]
This should work in the latest version. Please reopen if it doesn’t 👍
