### ISSUE TITLE
Promise.catch is not typed correctly

### ISSUE THREAD

**Issue by kentonv** [facebook/flow#1576]
https://github.com/facebook/flow/blob/master/lib/core.js#L453 defines `Promise<R>.catch` as:

```
catch<U>(
  onReject?: (error: any) => ?Promise<U> | U
): Promise<U>;
```

This appears to completely forget about the non-exceptional case. For example:

```
const p: Promise<number> = Promise.resolve("foo").catch(err => {return 123;});
```

Here, `p` will end up being a `Promise<number>` that resolves to `"foo"` -- not a number. However, Flow does not detect any type errors in this line.

I'm new to Flow, but it seems to me that catch should be defined as:

```
catch(
  onReject?: (error: any) => ?Promise<R> | R
): Promise<R>;
```

**Comment by nmn** [comment]
I don't see anything wrong here:
```typescript
declare class Promise<+R> {
    constructor(callback: (
      resolve: (result: Promise<R> | R) => void,
      reject:  (error: any) => void
    ) => mixed): void;

    then<U>(
      onFulfill?: (value: R) => Promise<U> | U,
      onReject?: (error: any) => Promise<U> | U
    ): Promise<U>;

    catch<U>(
      onReject?: (error: any) => ?Promise<U> | U
    ): Promise<U>;

    static resolve<T>(object: Promise<T> | T): Promise<T>;
    static reject<T>(error?: any): Promise<T>;
    static all<Elem, T:Iterable<Elem>>(promises: T): Promise<$TupleMap<T, typeof $await>>;
    static race<T, Elem: Promise<T> | T>(promises: Array<Elem>): Promise<T>;
}
```

**Comment by kentonv** [comment]
As I said above, the `onReject` passed to `catch()` needs to return type
`Promise<R>`, not `Promise<U>`. `catch()` is not allowed to change the
promise type, since in the non-exceptional case it passes through the value
of type `R`.

On Mar 22, 2017 8:06 AM, "Naman Goel" <notifications@github.com> wrote:

I don't see anything wrong here:

declare class Promise<+R> {
    constructor(callback: (
      resolve: (result: Promise<R> | R) => void,
      reject:  (error: any) => void
    ) => mixed): void;

    then<U>(
      onFulfill?: (value: R) => Promise<U> | U,
      onReject?: (error: any) => Promise<U> | U
    ): Promise<U>;

    catch<U>(
      onReject?: (error: any) => ?Promise<U> | U
    ): Promise<U>;

    static resolve<T>(object: Promise<T> | T): Promise<T>;
    static reject<T>(error?: any): Promise<T>;
    static all<Elem, T:Iterable<Elem>>(promises: T):
Promise<$TupleMap<T, typeof $await>>;
    static race<T, Elem: Promise<T> | T>(promises: Array<Elem>): Promise<T>;
}

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/facebook/flow/issues/1576#issuecomment-288428142>, or mute
the thread

**Comment by kentonv** [comment]
Oops, should have looked at the GitHub thread before replying by email.
Will delete replies when I get to my desk...

**Comment by vkurchatkin** [comment]
Fixed
