### ISSUE TITLE
Destructuring literal object with default parameter

### ISSUE THREAD

**Issue by vhf** [facebook/flow#1580]
This issue will be short lived, but here it is anyway:

I'd like to annotate the parameter in the following function:

```js
function f1({ x = 1 } = {}) {
  return 2 * x;
}
```

My reasoning is that `x` prop in argument object is optional, but then Flow thinks that if the `arg.x` is not provided, it'll will be `undefined`. Which is not correct because in this case, `x` would be `1` instead of `undefined`:

```js
function f2({ x = 1 }: { x?: number } = {}) {
  return 2 * x;
}
f2({});
//   8:   return 2 * x; // This type is incompatible with number
//                   ^ undefined. This type is incompatible with
//   8:   return 2 * x; // This type is incompatible with number
//               ^^^^^ number
```

@samwgoldman told me he fixed something similar here: 97bc5623d71ec3ceea7966ff001abd098c912f94

I haven't checked this particular commit but can confirm the current master (12b0d121a33b3b21adccd10156658b465db0db42) doesn't suffer the problem described here.

**Comment by samwgoldman** [comment]
Thanks for writing this up!
