### ISSUE TITLE
'Could not resolve name' when annotating function arguments in destructuring

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#1583]
I see some similar open issues but this one seems a little different. The following:
````javascript
export function person({firstName: string}: Object) {
  console.log(firstName);
}
````
results in something like:
````
console.log(firstName);
            ^^^^^^^^^ identifier `firstName`. Could not resolve name
````
Why? It appears that I cannot annotate the destructured argument. This will work without error:
````javascript
export function person({firstName}: Object) {
  console.log(firstName);
}
````
but it doesn't let me declare a type for the argument.

I'm using Flow 0.22.1

**Comment by garetht** [comment]
You can declare the type of the destructuring object with the object type syntax:

```js
export function person({firstName}: {firstName: string}) {
  console.log(firstName);
  1 - firstName; // will throw a type error
}
```

**Comment by kumar303** [comment]
ok, I didn't know about that. Thanks. This requires a lot of duplication effort though. I also can't seem to get parameters with default to be accepted like `{thing=theDefault}: {thing: ?string}`. It always tells me that the function call forgot to pass in `thing`. That looks like a separate issue though.

**Comment by avikchaudhuri** [comment]
@kumar303 What you wrote originally means something else. Try this:

```
export function person({firstName: x}: Object) {
    console.log(x);
}
```

Basically that destructuring syntax already uses `:` to introduce local variables / nested patterns. @garetht is right. To mitigate duplication, we're going to support a more compact syntax soon (without disturbing the meaning of the untyped syntax, obviously).

**Comment by avikchaudhuri** [comment]
See also #1580 for defaults

**Comment by kumar303** [comment]
> What you wrote originally means something else

oh, ha! The 'Could not resolve name' error makes perfect sense now. Thanks for the explanation.
