### ISSUE TITLE
Type checking not working for triple equals

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#1584]
Double equals (==) type checking works fine, for example https://github.com/facebook/flow/blob/master/tests/equals/equals.js
```
/* @flow */

(1 == 1);
("foo" == "bar");
(1 == null);
(null == 1);
(1 == ""); // error
("" == 1); // error

var x = (null : ?number);
(x == 1);
(1 == x);
```
outputs the expected errors.

However, the same example will type check if we use triple equals ===:
```
/* @flow */

(1 == 1);
("foo" == "bar");
(1 == null);
(null == 1);
(1 === ""); // no error
("" === 1); // no error

var x = (null : ?number);
(x == 1);
(1 == x);
```

Tested with flow release 0.22.1.

**Comment by garetht** [comment]
According to [the documentation](http://flowtype.org/docs/troubleshooting.html), "Non-strict equality `==` should be performed only on values that have the same type...because they tend to be hazardous...Usually there is a safer way to express the intent of the code in these cases: e.g... `===`". It seems that first is a type error because of risk present in implicit type conversions, but the strict equality version is easy to understand (no complicated conversion tables are involved) and always returns the boolean `false`.

**Comment by cprodescu** [comment]
@garetht Thanks for the reference, but I don't feel that explains why strict equality is not typechecked.

I argue strict equality (`===`) involving two different types (as inferred by flow) is always false, hence the respective code is most likely a programmer mistake which should be prompted by flow.

In contrast, flow typechecks weak equality (`==`), where something like `((str: string) == 0)` is useful (while terribly misleading) JS code.

I feel we are typechecking against misleading (`==` types mismatch), but not against clearly wrong (`===` type mismatch).

**Comment by avikchaudhuri** [comment]
@cprodescu IMO this is less a type checking issue than a dead code detection request. 

There might be a few cases like number/string where Flow could prove that `===` returns `false`, but in general it *does not hold* that if two expressions have different types, `===` doesn't make sense. In fact it does, as long as there is non-empty intersection between the types. For example, `a === b` does not always return `false` when `a: ?number` and `b: ?string` (e.g., they could both be `null`); neither when `a: { x: number }` and `b: { y: string}` (e.g., they could both be `{ x: 42, y: "..." }`).

Closing, please reopen as a feature request if you still think it is valuable.

**Comment by cprodescu** [comment]
@avikchaudhuri Thanks for the in-depth example.
Perhaps I'm too opinionated towards typing everything (`===` and equivalently `switch` statements not being typed are my flow pet peeves), but I definitely see value in this.

I totally agree the correct typing should be non-disjoint intersection, not equal types.

Can you re-open and add the feature label? I don't have access to re-open.
