### ISSUE TITLE
React ES6 failures

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#1594]
Can someone explain why this code:

```
/* @flow */
import React from 'react';// eslint-disable-line no-unused-vars

type Props = {
  receiver: string
};

type State = {
  value: number
};

class Test extends React.Component<void, Props, State> {

  constructor() {
    super();
    this.state = {
      value: 0
    }
  }

  render() {
    return (
      <div>Hello {this.props.receiver}: {this.state.value}</div>
    );

  }
}

export default Test;
```

fails with the following error?

```
src/components/Util/test.js:12
 12: class Test extends React.Component<void, Props, State> {
                                                     ^^^^^ object type. This type is incompatible with
 12: class Test extends React.Component<void, Props, State> {
                                                     ^^^^^ undefined. Did you forget to declare State?

src/components/Util/test.js:12
 12: class Test extends React.Component<void, Props, State> {
                                                     ^^^^^ undefined. Did you forget to declare State?. This type is incompatible with
 12: class Test extends React.Component<void, Props, State> {
                                                     ^^^^^ object type
```

I stripped everything from my code to come with this example. I can not understand why it doesn't pickup my definition of State.

**Comment by eikeon** [comment]
I've been trying to work through similar issues over at facebook/flux#336. I added a state property declaration with type annotation to the class along the lines of http://flowtype.org/docs/react.html#higher-order-components and it seemed to have fixed the error.

**Comment by hmeerlo** [comment]
That is how I do it now as well, I just liked the 'generics way' better :-)

**Comment by eikeon** [comment]
@hmeerlo It'd be nice to get the 'generics way' working too. I am assuming the `State` in `extends  Component<void, Props, State>` should be enough for the type to be inferred if flow is picking up on https://github.com/facebook/flow/blob/master/lib/react.js#L16. But perhaps not if the $Abstract means the subclass needs to specify re: https://github.com/facebook/flow/blob/master/lib/react.js#L21.

**Comment by nmn** [comment]
I ran into a similar issue, and it turns out that currently you need to use the experimental stage-1 features to really work around this issue.

So your code, written like this would work correctly with flow.

/* @flow */
import React from 'react';// eslint-disable-line no-unused-vars

type Props = {
  receiver: string
};

type State = {
  value: number
};

class Test extends React.Component<void, Props, State> {
  state = {value: 0};

  render() {
    return (
      <div>Hello {this.props.receiver}: {this.state.value}</div>
    );

  }
}

export default Test;
```

The same is also true for default props. If you use `Test.defaultProps = {}` after the class definition, Flow complains. But if you put a `static defaultProps = {};` inside the class body flow is fine with it.

Of course to use class static and property fields, you need to add this to your `.flowconfig`:

```
[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
```

I hope this problem can be fixed soon, but at least I have a proper work around for now.

**Comment by hmeerlo** [comment]
Thanx, it seems to work. I do need to make one small change, I must annotate the state with its type, otherwise flow complains about a missing annotation:

```
state: State = {value: 0};

**Comment by rosskevin** [comment]
may or may not relate to #1908

**Comment by adriantoine** [comment]
I had the same issue but I solved it differently. If you really need your state to be in your constructor (for example if it depends on the props, or if you compiler doesn't compile class properties), you can add a type annotation for the State **in** the class:
```js
class Playground extends Component<void, Props, State> {
  state: State; // <- There

  constructor() {
    super();
    this.state = {
      count: 0,
    };
  }
  
  ...
}
```
Then you won't get the error anymore.

**Comment by mengxingshike2012** [comment]
Ok, Meet this issue and got fixed by @adriantoine 's solution. But it's a  duplication, right ?

**Comment by asolove** [comment]
I think this issue can be closed. The original example, [after just a tiny syntax change](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqgQCe2amAAKzbBQC8YAN6owYTnWroAbtTwAuMGQJ50AOwDmqAL58Bw0QGUCJAqNkKl6kjACu1XUc+YAIy0LKzoYcgoAFWp9MGoADycjABMKGnoCADoAYRZcI2ojAgAeCTgpABowe0dqAD55fiU6OCN9PE8GfAAKAEpGpSUyTxE8Pr5BsAIAC3QyTP1asBdFSbB3Lx8wAAZVpXNVg9XOFK0+gcHOAk88IzBuvcHi5I06gAlqGHh5GbnM7Ek8xUak0eHMujkv3miycmQ23nMxWAL3UdUevSs+wsQA), now works fine in Flow v0.53, which improved the way `Component`s are typed. (/cc @calebmer)
