### ISSUE TITLE
x.constructor type refinement

### ISSUE THREAD

**Issue by maxxk** [facebook/flow#1595]
Is it possible to enable type refinement for the dynamic type tests based on the constructor equality?
The following examples show two use cases for which flow v0.22.1 reports the same error.

``` javascript
/*@flow */

type StringOrBool = string | boolean

function length_if(x : StringOrBool) : number {
  if (x.constructor == String) {
    return x.length;
  }
  if (x.constructor == Boolean) {
    return 0;
  }
  throw new Error('Unreachable')
}

function length_switch(x : StringOrBool ) : number {
  switch (x.constructor) {
    case String:
      return x.length;
    case Boolean:
      return 0;
  }
  throw new Error('Unreachable')
}
```

```
src/flow-switch-constructor.js:7
  7:     return x.length;
                  ^^^^^^ property `length`. Property not found in
  3: type StringOrBool = string | boolean
                                  ^^^^^^^ Boolean

src/flow-switch-constructor.js:18
 18:       return x.length;
                    ^^^^^^ property `length`. Property not found in
 18:       return x.length;
                  ^ Boolean
```

**Comment by vkurchatkin** [comment]
@maxxk constructor check doesn't really guarantee anything.

**Comment by maxxk** [comment]
And neither does tagged union in some special cases, e.g., for now, involving setPrototypeOf. But type refinement for tagged unions is enabled anyway.

```javascript
class First {
  type : 'first';
  first : number;
  constructor(f) {
    this.first = f;
  }
}
First.prototype.type = 'first';

class Second {
  type : 'second';
  second : number;
  constructor(s) {
    this.second = s;
  }
}
Second.prototype.type = 'second';

type TUnion = { type: 'first', first : number } | { type :'second', second : number };
function test(x : TUnion) : number {
  if (x.type === 'first') return x.first;
  if (x.type === 'second') return x.second;
  return -1;
}

let f = new First(1);
Reflect.setPrototypeOf(f, Second.prototype)
test(f)
```

**Comment by vkurchatkin** [comment]
The problem is with `setPrototypeOf`, not with tagged unions. I guess if your type is `string | boolean`, then it would be a valid assertion, nut not if there is an object type in the union.

**Comment by vieks** [comment]
> @maxxk constructor check doesn't really guarantee anything.

Really, why ?

**Comment by maxxk** [comment]
@vieks It is because for objects constructor property is writable, you may look at the [example](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/constructor) at MDN. It was used to implement inheritance explicitly before ES2015 classes. I don't know are there any cases when it still feasible to overwrite `constructor`.

But I personally think that both these cases (`setPrototypeOf` and overwriting `constructor`) are similar except for the one thing. If you set an incompatible `constructor` it will break only the code like in my first post. If you set an incompatible `prototype` it may break a lot of code in unexpected places.

**Comment by vieks** [comment]
@maxxk Thanks for that explanation but I am already aware of the ```constructor``` prop and that behavior should not prevent making test on it to induce types, it's a very useful JS feature.
Yes it's a writable property  and its handy for handling old ES5 inheritance:

```javascript
function Foo(){}
function Bar(){}

// inherits
Bar.prototype = Object.create(Foo.prototype);
Bar.constructor = Bar;// Set back the correct constructor for Bar
```

 But it must be consider as a source of truth for typechecking. As the Python devise states:
"**We're all adults here**."

So I still asking to @vkurchatkin as I am a stubborn guy, why ?

**Comment by vkurchatkin** [comment]
@vieks I guess when type is `Foo | Bar` when can use `constructor` for refinement, but if type is `Object` or `mixed`, we can not.

**Comment by calebmer** [comment]
We aren’t really interested in refining using `constructor`. Please use `instanceof` or `typeof` 😊 

Closing since there hasn’t been a lot of activity on this issue. We are sorry about that 😔

If you are still having issues, please reopen!
