### ISSUE TITLE
Export type signature without exporting the class itself

### ISSUE THREAD

**Issue by spicyj** [facebook/flow#16]
Is there a way to export a type signature without exporting the constructor? For example, in one project I have, we have a `Style` class where the constructor isn't exposed, just certain instances:

https://github.com/Khan/KaTeX/blob/a2f81d9d73940842085f73fa626b3ef008f68062/src/Style.js

Right now I can write something like:

```
var Style = require("./Style");
type StyleType = typeof Style.DISPLAY;

var s: StyleType = ...;
```

but it would be nice if there was a way to export a type directly from a module, so that perhaps I could write `var s: Style.T;` or something like that.

**Comment by jeffmo** [comment]
@spicyj: Now that we have `export type` syntax, it should be possible to define a class locally, not export it, but instead export a type alias for it:

```javascript
class MyClassImpl {}

// Creates an alias for the type of instances of this class and exports that alias
export type MyClass = MyClassImpl; 
```

**Comment by spicyj** [comment]
:tada:
