### ISSUE TITLE
Detect invalid number literals

### ISSUE THREAD

**Issue by alexbooker** [facebook/flow#1608]
Please excuse me if this isn't within the scope of Flow, but shouldn't Flow detect invalid numbers like this one:

```
let num: number = 01
```

At the moment, Flow does not complain even though `01` is not a valid number in JavaScript. I have to wait until runtime to realize my typo,

**Comment by samwgoldman** [comment]
I believe 01 is 1 in octal (010 is 8)

**Comment by alexbooker** [comment]
It is, but that would be written as `0o1` in JavaScript, not `01` (using an ES2015 an octal integer literal).

**Comment by mroch** [comment]
01 was deprecated in ES3 and removed in ES5, but [still exists](https://es5.github.io/B.html#B.1.1) in non-strict code.

flow will complain about it if you're in strict mode: https://github.com/facebook/flow/blob/a68b5a18d87fa679e544ee7493fc937d015199c5/src/parser/parser_flow.ml#L1617

:)

**Comment by mroch** [comment]
please reopen if strict mode doesn't make flow error

**Comment by mroch** [comment]
btw, I added a `module.use_strict` option that will make files use strict mode by default, in case you're using a compiler that adds it for you: https://github.com/facebook/flow/commit/9057c0886a13a1051308ca623bdc7c9ea7658260

**Comment by alexbooker** [comment]
@mroch Thanks for the update.
