### ISSUE TITLE
String literal keys for object type aliases

### ISSUE THREAD

**Issue by crm416** [facebook/flow#161]
When I try:

```js
type MyType = {
  'foo-bar': number;
};
```
Flow gives me the `"Unsupported key in object type"` error. Changing `'foo-bar'` to, e.g., `fooBar` fixes the issue. Is there any way to use string literal keys in this case?

(First experience with Flow, so apologies in advance if I've messed up any of the nomenclature.)

**Comment by gabelevi** [comment]
This looks fixed :)
