### ISSUE TITLE
How to replace `any` with `mixed` in library definitions

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1611]
So obviously, `mixed` is a great way to avoid `TypeError`s.  But some 3rd-party library definitions may use `any` for return values instead of `mixed`, preventing any type checking on the returned values.  So it would be helpful if e.g. one could append an option to `/* @flow */` to treat all `any` return types as `mixed` instead.

For instance, the unofficial Flow type defs for Immutable.js I've seen floating around (https://gist.github.com/bouk/911b8d4993c19de3f98f) use `any` everywhere and don't use `mixed`.

Library authors could make the function type defs return `mixed`, but that might be way too strict for some users, especially when migrating large established codebases to Flow.

So for instance:

``` js
/* @flow */
import Immutable from 'immutable';

let emptyMap = Immutable.Map();
emptyMap.get('hello')(); // TypeError could be prevented if get returned mixed
```

Obviously one could work around this by doing

``` js
let item: mixed = emptyMap.get('hello');
mixed(); // Flow catches this error
```

But of course it would be nice to catch potential errors when developers forget to assign to a mixed variable.

**Comment by avikchaudhuri** [comment]
@jedwards1211 I know what you mean but literally replacing `any` with `mixed` works only half of the time. Consider a function that takes a parameter of type `any`, changing that to `mixed` doesn't cause any more errors.

**Comment by jedwards1211** [comment]
@avikchaudhuri Yes, unfortunately that doesn't work, but it would at least help with return values.

**Comment by zeorin** [comment]
I've proposed an option to automatically cast any to mixed here: #7515. Not just for the types in library definitions, but it would also affect them.

**Comment by SamChou19815** [comment]
I don't think we plan to add a mode to interpret `any` as `mixed`
