### ISSUE TITLE
Higher order function annotation

### ISSUE THREAD

**Issue by LoganBarnett** [facebook/flow#1612]
Right now I'm checking against `Function` for a lot of things, but I'd like to get more specific.

For example, I want to declare a parameter should be a function that takes a `Foo` and a `Bar` and returns a `Foo`. Haskell notation would be something like `(Foo -> Bar -> Foo)`.

As I understand, I can make a type alias like this:

```
// declare
type F = (p1: Foo, p2: Bar) => Foo;
// use
const myFunc = (f:F) => { ... };
```

Do these strictly need to be declared as separate type aliases? If so, is this due to preference?

Thanks for the lib folks. I got Flow working in my Webpack setup yesterday and I'm going crazy with it :)

**Comment by avikchaudhuri** [comment]
@LoganBarnett Glad you're enjoying Flow! You don't *need* to make a type alias if you don't want to, you can just write the type inline, like:

```
const myFunc = (f: (p1: Foo, p2: Bar) => Foo) => { ... };
```

So mostly the same as Haskell notation except for currying and parameter names.

**Comment by mroch** [comment]
I think we should improve our docs around this, this is the 3rd time recently someone's asked about this.

**Comment by rongierlach** [comment]
@mroch A call to reference <a href="https://flowtype.org/docs/syntax.html#function-types">here</a> from the <a href="https://flowtype.org/docs/functions.html#_">Functions docs</a> for readers looking to implement HOF annotation would have saved me some confusion :)
