### ISSUE TITLE
Flow fails to infer calls to polymorphic function in an out scope

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#1614]
Here is the most simplified example I could come up with:

``` js
/* @flow */

const greetWith = <user>
  ( printName:(input:user) => string
  , model:{user: user}
  ):(input:{user:user}) => string =>
  model => greet(printName, model)

const greet = (printUser, model) => `Hi ${printUser(model.user)}`
```

That produces following error:

```
scratch.js:7
  7:   model => greet(printName, model)
                ^^^^^^^^^^^^^^^^^^^^^^^ function call
  9: const greet = (printUser, model) => `Hi ${printUser(model.user)}`
                                                         ^^^^^^^^^^ user. This type is incompatible with
  3: const greetWith = <user>
                       ^ some incompatible instantiation of `user`


Found 1 error
```

In reality flow just fails to infer because greet is defined in an outer scope. If `greet` is inlined flow seems to infer everything as expected:

``` js
/* @flow */

const greetWith = <user>
  ( printName:(input:user) => string
  , model:{user: user}
  ):(input:{user:user}) => string =>
  model => {
    const greet = (printUser, model) => `Hi ${printUser(model.user)}`
    return greet(printName, model)
  }
```

Also worth mentioning that adding annotations to the greet does resolve the problem:

``` js
/* @flow */

const greetWith = <user>
  ( printName:(input:user) => string
  , model:{user: user}
  ):(input:{user:user}) => string =>
  model =>
  greet(printName, model);

const greet = <user>
  ( printUser:(input:user) => string
  , model: {user: user}
  ):string => `Hi ${printUser(model.user)}`
```

But that is contagious, and what I mean by that is that in less trivial example (where I run into this) callee in outer scope may refer to other functions that in turn refer to yet other functions (in my example about 10 diff functions) & all of them need to be annotated for flow to be able handle.

**Comment by calebmer** [comment]
I’m going to close since this issue has not gotten a lot of activity. We are sorry about that 😔

If you are still having issues, please reopen and give us an example on https://flow.org/try!
