### ISSUE TITLE
Why is Flow implemented in OCaml?

### ISSUE THREAD

**Issue by kazzkiq** [facebook/flow#1619]
>**Notice:** Please don't take this Issue as offensive or trolling, its a genuine doubt.

So, is there any special reason why Flow is made mostly upon OCaml instead of JavaScript? I'm sure there are definitely some reasons to choose using it (probably performance, if I had to guess), but as I couldn't find anything on Facebook's Dev Blog or Flow's documentation, I felt the need to ask over here.

Are there any special reasons to do so, instead of developing it fully in JavaScript (and enabling its installation via `npm` on all OSes)?

**Great project**, and badass work on here thought, keep the good job and thanks for this tool!

**Comment by arypurnomoz** [comment]
And what do we use to do static analysis for flow that is implemented in javascript? it's a chicken-egg problem

**Comment by sledorze** [comment]
Ocaml being a Statically typed functionnal language, is simply a better tool for this kind of job.

**Comment by alexbooker** [comment]
@arypurnomoz, like @kazzkiq, I do not mean to be offensive but isn't [bootstrapping](https://en.wikipedia.org/wiki/Bootstrapping#Compilers) common? I know Flow isn't a compiler per se, but I think the same principles apply. I'm only writing this because I'm curious to be proven wrong.

**Comment by kazzkiq** [comment]
@arypurnomoz I cant even start to imagine the quirks both TypeScript and Flow core teams had to deal with when building those tools, and they surely had to face *obscure* bugs and architecture concerns, but TypeScript is made 100% in ... TypeScript. So if it managed to use its own language to make a compiler, why Flow didn't followed the same path? I just ask that because I got curious about Flow choosing OCaml instead of JavaScript or Flow's syntax itself.

**Comment by avikchaudhuri** [comment]
A lot of people including the Flow team believe that functional programming
languages like OCaml are great for writing compilers. These kinds of
programs make heavy use of abstract data types and pattern matching. Plus,
OCaml's nice interop with C and fast running times make it an ideal
language for systems programming / scaling for perf.

Bootstrapping is cool but we'd still have a compiler to maintain after the
initial coolness fades away.

What's more, OCaml can be compiled to JS so we don't *have* to give up on
JS interop either.

-Avik.

**Comment by kazzkiq** [comment]
@avikchaudhuri Great, thanks!
