### ISSUE TITLE
Difficulties writing an alias with name_mapper

### ISSUE THREAD

**Issue by cbrwizard** [facebook/flow#1620]
Hey, I have just started using flow and I am having a difficulty with telling it to correctly work with import path aliases.
Here is my code:
File structure:
- .flowconfig
- webpack.config.js
- /node_modules
- /apps
  - /src
    - /sagamore
      - sagamore_global.js
      - /lib
        - prevent_default.js

`.flowconfig`:
```
[ignore]
.*/node_modules/fbjs/.*
.*/node_modules/flux/.*
.*/node_modules/config-chain/.*
.*/node_modules/npmconf/.*
.*/node_modules/y18n/.*

[options]
module.name_mapper='sr\/(.*)' -> '<PROJECT_ROOT>/src/sagamore/\1'
```

`webpack.config.js`:
```js
...
  resolve: {
    alias: {
      sr: path.join(__dirname, 'apps/src/sagamore'),
    }
  }
...
```

`apps/src/sagamore/lib/prevent_default.js`:
```js
// @flow
import Sagamore from 'sr/sagamore_global'
```

`apps/src/sagamore/sagamore_global.js`:
```js
export default true
```

I have tried setting `module.system=haste` but it didn't help.
Setting a direct regexp like `module.name_mapper='sr\/sagamore_global' -> '<PROJECT_ROOT>/src/sagamore/sagamore_global'` helps but obviously that's not an ideal solution.

Is this a bug? Or am I doing something wrong? Please give me an idea [: Thanks!

**Comment by jeffmo** [comment]
The two things that stand out to me are that you haven't escaped your group-parens and that you've escaped a backslash that doesn't need to be escaped.

Does something like the following fix things? `sr/\(.*\)`

(We use ocaml's regexp engine, which is a bit different from most others in this regard)

**Comment by cbrwizard** [comment]
Ooh yeah @jeffmo it fixed my problem! This issue can be closed.
Thank you! Want me to open a PR with a similar example added to the documentation?

**Comment by jeffmo** [comment]
@cbrwizard That would be awesome!

FWIW: In the medium/longer term we're planning to switch to a better, more fully-featured regexp engine than ocaml's built-int one -- so hopefully that will make this a little simpler. Docs in the meantime are a good idea, though.
