### ISSUE TITLE
type Promise matches with all types.

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#1626]
no errors are found for the following code:

```
let a : Promise = 123;
let b : Promise = new Date();
function c() : Promise {
    return [];
}
```

version 0.22.1

**Comment by mroch** [comment]
make sure you add `/* @flow */` or `// @flow` to the top of files you want to be checked by flow. each file has to be opted-in, which was a design decision to enable projects to add flow gradually. (see http://flowtype.org/docs/new-project.html#typechecking-your-files)

please reopen if that doesn't help!
