### ISSUE TITLE
not existing type behaves like mixed

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#1628]
this code :
```let a : AFEWFVCXZVZXVSDAVASDV = 1;```
will not fail with an error. type `AFEWFVCXZVZXVSDAVASDV` does not exists. 

flow version: `0.22.1`

**Comment by vaukalak** [comment]
sorry, it was due an error in the `.flowconfig`

I did a mistake and wrote following:

```
[include]
src/

[libs]
src/
```

And than flow started working really strange. Probably, there should be a warning in case of misconfiguration like this.

**Comment by samwgoldman** [comment]
I am not able to reproduce this issue. Given a flow project without any configuration, the following produces an expected error:

```
// @flow
let a: AFEWFVCXZVZXVSDAVASDV = 1;
```

```
test.js:2
  2: let a: AFEWFVCXZVZXVSDAVASDV = 1;
            ^^^^^^^^^^^^^^^^^^^^^ identifier `AFEWFVCXZVZXVSDAVASDV`. Could not resolve name
```
