### ISSUE TITLE
Flow Interface File Naming Convention Isn't Well-Documented

### ISSUE THREAD

**Issue by alexbooker** [facebook/flow#1629]
Hello there,

I spent more time than I care to admit trying to figure out why Flow wouldn't detect my interface files.

I made an interface file called **interfaces/isomorphic-fetch.flow**:

```javascript
declare module 'isomorphic-fetch' {
  declare var exports: (url: string, options?: Object) => Promise;
}
```
... And I updated **.flowconfig** to point at the **interfaces** directory:

```javascript
[libs]
interfaces/
```

Then, within a file called **index.js**, I wrote some JavaScript:

```javascript
// @flow
import fetch from 'isomorphic-fetch'

fetch(10)
```

I was expecting Flow to emit an error because `fetch` does not take a `number` (in this case, '10'), but I didn't get one.

After a bit of research, I deduced that Flow wasn't detecting the interface file so I tried to be as explicit as I could in telling Flow where to find it:

```
flow stop && flow start --lib ./interfaces/isomorphic-fetch.flow && flow
```

... I still didn't get the error I was expecting.

After some more research I learned that Flow convention dictates that interface files be called **interfaces/isomorphic-fetch.js.flow** but mine was called **interfaces/isomorphic-fetch.flow**. Renaming the interface file caused the type error I was expecting to be emitted. Cool.

Trouble is:

- This information does not appear to be documented in the obvious place, which is http://flowtype.org/docs/third-party.html. I had to learn about it via #1469.
- I think Flow could have been more helpful by emitting a warning or some information relevant to my problem in the `.log` file.

**Comment by samwgoldman** [comment]
Thanks for writing this up! I'll follow up with a documentation update to better explain that we expect just `.js` files in the `[libs]` directory.

Can I ask how you came to the conclusion that `.flow` was the expected file extension?

**Comment by alexbooker** [comment]
I inferred it from #1469.

Thanks :smile:
