### ISSUE TITLE
can't declare global function definitions (for example mocha functions)

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#1632]
Mocha has some global functions `describe`, `before`, `it` etc. So I've wrote following in my test:
```
declare function describe(name:string, callback:Function):void;
declare function before(callback:Function):void;
declare function beforeEach(callback:Function):void;
declare function it(name:string, callback:Function):void;
```
and everything worked perfectly.

But than I had to move that to my library folder, and I ran into troubles. My code looks like:
```
declare module "Mocha" {
    declare function describe(name:string, callback:Function):void;
    declare function before(callback:Function):void;
    declare function beforeEach(callback:Function):void;
    declare function it(name:string, callback:Function):void;
}
```
But as I can see from the docs, the only way to link that to my code is to write:
```import {describe, beforeEach} from 'Mocha';```
this will type check, but it will cause a runtime issue, cause `describe`, `before`, `it` are global functions, rather than mocha methods. Is there a way to deal with this?

**Comment by splodingsocks** [comment]
I just ran into this very same thing, and I have the same question :)

**Comment by vaukalak** [comment]
@splodingsocks hopefully I've found the solutions, it was quite easy 😄 
I've putted:
```declare function describe(name:string, callback:Function):void;
declare function before(callback:Function):void;
declare function beforeEach(callback:Function):void;
declare function it(name:string, callback:Function):void;```
to file `interfaces/mocha/mocha.js` (which is under `[libs]`), and did not import anything. It works 😄 .

**Comment by splodingsocks** [comment]
Nice! Thanks for following up!
