### ISSUE TITLE
Describe the logic of @flow comment lookup

### ISSUE THREAD

**Issue by gajus** [facebook/flow#1641]
> You can opt-in on a per file basis by simply adding a /* @flow */ comment to the top of your source file. Flow uses type inference to find errors without further guidance. You can add type assertions by annotating your program with types.

http://flowtype.org/docs/about-flow.html#gradual

What is the exact implementation?

* Check all top level comments.
* Check first comment only.
* Check first N comments.
* ... ?

**Comment by gajus** [comment]
This is required for development of third-party tools (https://github.com/gajus/eslint-plugin-flowtype/issues/5) that require to identify files that have `@flow` comment.

**Comment by samwgoldman** [comment]
Flow looks for the first comment, skipping over any tokens until the first comment is found.
