### ISSUE TITLE
is it possible to refactor flow so that I can get parsing as a separate library?

### ISSUE THREAD

**Issue by bobzhang** [facebook/flow#1642]

**Comment by samwgoldman** [comment]
yes

**Comment by jeffmo** [comment]
Ok... So to be a little more helpful:

The parser is isolated from the rest of the system [here](https://github.com/facebook/flow/tree/master/src/parser). It does not have dependencies on anything outside of that directory.

You can call the [`parse_program`](https://github.com/facebook/flow/blob/master/src/parser/parser_flow.ml#L4398) function to pass in source text and receive an AST.

Also note (just for clarity) that Flow does not typecheck while parsing -- so this parser function only generates ASTs.
