### ISSUE TITLE
Proxying as an operator?

### ISSUE THREAD

**Issue by STRML** [facebook/flow#1643]
I'm doing some work on [iflow-lodash](https://github.com/marudor/flowInterfaces/blob/master/packages/iflow-lodash/index.js.flow) which doesn't support `_.chain()/_()`.

In TypeScript, they support chaining through a [very complex series of wrappers](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/lodash/lodash-3.10.d.ts#L4136) around every output type. Perhaps Flow could make this better via a flexible syntax that allows us to actually instruct the typechecker as to how it should interpret calls to this object.

It would be great if we could define a `$Proxy`:

``` js
$Proxy<Target, ArgTypeTransform, ReturnTypeTransform>
```

As in:

``` js
type LodashChainWrapper<T, U> = $Proxy<
  Lodash, 
  (...args: any) => (T, ...args), 
  (out: U) => LodashChainWrapper<U>
>;

declare module 'lodash' {
  declare class Lodash {
    chain<T>(value: T): LodashChainWrapper<T>;

    // ...
    filter<T>(array: ?Array<T>, predicate?: Predicate<T>): Array<T>;
  }
}
```

The idea is that Flow could understand that any function called on the result of `chain()` already has its first parameter filled in, and that it returns the proxy itself. The syntax above probably needs a lot of fleshing out.

**Comment by samwgoldman** [comment]
Yes, we are *very* interested in providing type combinators like this. Lodash is an excellent API to target. We're also looking at Immutable.js and Redux :)

@bhosmer and I have been thinking about this. Look out for updates in the coming months.

**Comment by SamChou19815** [comment]
Beyond conditional type and mapped type, we do not intend to add more utility type that does transformation.
