### ISSUE TITLE
--all option hangs without output

### ISSUE THREAD

**Issue by oliverbenns** [facebook/flow#1646]
Hey guys, thanks for Flow!

I'm hoping to type check all my files in a small project, without including `// @flow` at the top of each Js file. The docs say I can specify the `--all` flag, but when I do add it, it just hangs, with no errors, whilst my Macbook fans start spinning away. My npm script can be seen here: https://github.com/oliverbenns/pong/blob/add-type-checking/package.json#L21 

If I remove the `--all` flag and add the comment to the top of a file it works fine.

Thanks.

**Comment by samwgoldman** [comment]
How long did you wait? Using `--all` does what it says on the tin. If you have a lot of files in your `node_modules` directory, which is likely, then Flow is going to spend time analyzing them all.

**Comment by oliverbenns** [comment]
Hey,

I had already decided to ignore my node modules in my `.flowconfig`:
```
[ignore]
node_modules/.*
```
As for my own, it's ~20 files with around 40 lines each and waited about 10 minutes

**Comment by oliverbenns** [comment]
Ah, had added the ignore incorrectly. Doh!

```
[ignore]
.*/node_modules/.*
```
