### ISSUE TITLE
node-js Buffer.toJSON() type is Array<number> but should be an Object

### ISSUE THREAD

**Issue by d14b3l** [facebook/flow#1647]
In lib/node.js we can see that Buffer.toJSON is returning an Array<number> type:
https://github.com/facebook/flow/blob/master/lib/node.js#L41

but node-js documentation says that it should be an Object type:
https://nodejs.org/api/buffer.html#buffer_buf_tojson

**Comment by mroch** [comment]
thanks, you're right. based on https://github.com/nodejs/node/blob/59d23ad63dc75c68631480b2bdd98cbb67265d9d/lib/buffer.js#L771, we might be able to make it even more specific, although I'm not sure whether they were intentionally vague (`Object` vs `{ type: 'Buffer', data: Array<number> }`)

**Comment by mroch** [comment]
to complicate things, this has changed in some version of node between 0.10 and latest. here's 0.10's implementation: https://github.com/nodejs/node/blob/0439a28d519fb6efe228074b0588a59452fc1677/lib/buffer.js#L386
