### ISSUE TITLE
Versioned documentation

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1648]
Currently the website is always describing `master`.

On one hand, this is great because it allows us to add documentation to features as we add them. Missing or inadequate documentation has been a big problem for us in the past.

On the other hand, people using the latest release might find something that isn't released yet and will be very confused. In addition, people who are using older versions don't have any way of finding the documentation that applies to the version they're using.

React Native has solved this problem. We should do what they are doing.

![versioned docs](https://cloud.githubusercontent.com/assets/254842/14438312/4ec723be-ffda-11e5-958b-21ac089a5a07.gif)

**Comment by rishabhsrao** [comment]
@samwgoldman I’d like to give this a try but I’ll need your guidance on the next steps. I looked into this a little bit. [react-native](https://github.com/facebook/react-native) has a separate repository for documentation, [react-native-website](https://github.com/facebook/react-native-website) and it’s using [Facebook’s](https://github.com/facebook/docusaurus) [Docusaurus](https://docusaurus.io/). A few things to consider in terms of feasibility are:

* How do we make sure that existing docs hyperlinks redirect appropriately?
* Do we also create a new [flow-website](https://github.com/facebook/flow-website) repository?
* If yes, then how do migrate over the [existing docs](https://github.com/facebook/flow/tree/master/website/en/docs) to the new repository?
* What about in-flight pull-requests inside the [`website`](https://github.com/facebook/flow/tree/master/website) directory? If we move the underlying directory, then it’ll lead to merge conflicts.
* _... anything else that I may have missed..._

**Comment by gkz** [comment]
We don't have the bandwidth to add such functionality. We now add "since version" and "until version" badges various sections which helps.
