### ISSUE TITLE
Dynamic type test information lost inside closure?

### ISSUE THREAD

**Issue by asolove** [facebook/flow#1655]
When a variable's type has been narrowed by dynamic type tests, uses of that variable within a nested function seem to lose the dynamic knowledge and revert to the originally-declared type. This is quite painful, for example, if you have already established that a variable isn't null, or is one case of a union type.

Here are two examples:

## Optional types

Modifying the `maybe_test` function from the Dynamic Type Tests doc page:

```js
function maybe_test(x: ?string): string {
  if (x == null) {
    return "";
  } else {
    return (() => x)(); // this does not type check, says x may be null or undefined.
  }
}
```

If the else case is changed to say `return x` it passes. Also `let y: String = x; return (() => y)();` type checks. This is what makes me think the dynamic type narrowing may be lost when the variable x is used inside the new function context.

## Union types

Just to show this isn't limited to optionals, here is the case with union types. This is the actual case that is bugging me. I have tried to get to a minimal case although that means this is a stupid function. But handling union types by case and then waiting to use the value of that case in a nested function seems reasonable.

```js
type Foo = { type: "bar", bar: number } | { type: "quux", quux: number };

function getNumber(foo: Foo): number {
  if(foo.type === 'bar') {
    return foo.bar;
  } else if (foo.type === 'quux') {
    return (() => foo.quux)(); // Fails: no property 'quux' in object type { type: "bar" ...}
  } else {
    return foo;
  }
}
```

Again, this type checks if you replace the `else if` case with just `return foo.quux` or if you assign `foo.quux` to a local variable outside the nested function and then refer to that from inside the function.

**Comment by asolove** [comment]
Ah, ok, I assume this is a case of pessimistic refinement removal, per the Caveats section of the docs: http://flowtype.org/docs/dynamic-type-tests.html#caveats And I can see how that caveat applies in my original code, where the anonymous function was being passed into code that Flow wasn't analyzing. But in the minimal cases here, it seems like Flow should be able to analyze these immediately-invoked functions.

**Comment by ndbroadbent** [comment]
I just ran into this too. I'm writing a Redux reducer and using Flow's type refinements for the different actions. For now I'll just follow the workaround and store a reference to the value.

But I think Flow should really handle the case where you define an anonymous function inside the refinement scope and then immediately call it. I can't think of any possible way that the refinement could actually be invalidated, so this special case should be allowed.

@asolove Could you please reopen this issue to get some feedback?

**Comment by ndbroadbent** [comment]
Ah never mind, now I understand the problem.

I'm passing a function that I'm 100% sure will be called immediately, but Flow doesn't have any way of looking ahead and figuring that out. 

It would be great if the Flow refinement algorithm was improved. Or maybe if there was a special escape hatch that developers could use, like the `any` type. Something that tells Flow to always preserve the refinement inside a closure.
