### ISSUE TITLE
Class composition

### ISSUE THREAD

**Issue by bolismauro** [facebook/flow#1656]
I everyone,
I just started to use flow and it seems amazing!

I'm porting a library we have internally where I work to flow and I encounter a situation I don't really know how to handle.

So basically I have this  function that returns  with a lot of methods (that are tied to some variables I pass to the function), and I used to separate the implementation of these methods in separate files for readability (and then merge together using Object.assign).

I'm rewriting this portion of code using ES6 classes and flow but I can't find a way to handle the separation of methods in files.
I was thinking to use mixins but it seems I can't declare functions there.

Is there a way to have this kind of composition?

Thanks!

**Comment by fabiomcosta** [comment]
Can you give us a simplified version of your code using http://tryflow.org/ ?
That might make it easier to to help you.

**Comment by bolismauro** [comment]
Basically the code I've converted was something like this
http://tryflow.org/#671979e9525052011dc2261154e01095

The code actually compiles and flow handle this very well.
I just had trouble with autocompletion (nuclide) so I decided to switch to a class based approach where long methods are invoked on a different file.

I think it is all ok.
I forgot to close the issue, my bad

**Comment by fabiomcosta** [comment]
Hmm the nuclide autocomplete functionality comes directly from flow, so there could be a bug in Flow.
Can you try running `flow autocomplete <line> <column> < file.js` where <line> and <column> are just placeholders for the actual line and column of your code that should show your methods as autocomplete options?
Please let us know if the expected options are now shown. If they are please close the issue.
