### ISSUE TITLE
Flow thinks optional props of optional argument are not optional

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1657]
In the following, the units property of the argument to formatStatusValue is clearly optional:

``` jsx
/* @flow */

function formatStatusValue(status?: {
  value?: number,
  units?: string
} = {}): string {
  return 'not implemented'; 
}

type ModbusChannelStatus = {
  modbus?: {
    value?: number
  },
};

function temp(status: ModbusChannelStatus): string {
  return formatStatusValue(status && status.modbus); 
}
```

```
react-sandbox/scratch/flowissues.js:17
 17:   return formatStatusValue(status && status.modbus); 
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  3: function formatStatusValue(status?: {
                                         ^ property `units`. Property not found in
 17:   return formatStatusValue(status && status.modbus); 
                                ^^^^^^^^^^^^^^^^^^^^^^^ object type
```

**Comment by mroch** [comment]
it's actually not complaining because it's optional, it's complaining because `{ value?: number, units?: string }` is not compatible with `{ value?: number }`. because of subtyping, flow can't guarantee what you're trying to do is sound, because of a caller like this:

```
temp({modbus: { value: 123, units: false }})
```

the arg is a valid `ModbusChannelStatus`, but cannot be safely passed to `formatStatusValue`.

**Comment by jedwards1211** [comment]
Oh right, I so often forget about this subtle aspect of Flow types.  So really the only option is to cast `status.modbus` to `any`, right?  I would like to be able to typecheck things like I tried to do here so that, for instance, if the type of `ModbusChannelStatus.value` changes to `Object`, Flow will catch an error when I pass it to `formatStatusValue` (casting to `any` of course prevents any type checking).

Are there plans to provide better typechecking capability in cases like this?  For instance I could tag the `status` argument as `readonly` and then there would be no danger of passing in an object that's missing some of the fields.  I run into this issue quite often.

**Comment by jedwards1211** [comment]
This is a confusing error in any case, because it's worded exactly the same as for missing non-optional properties.  Something like "types are incompatible" would be less confusing.
