### ISSUE TITLE
dynamic type fails inside switch case statement

### ISSUE THREAD

**Issue by EnoahNetzach** [facebook/flow#1669]
I have this piece of code:

```es6
const TYPE_1 = 'TYPE_1'
const TYPE_2 = 'TYPE_2'
const TYPE_3 = 'TYPE_3'

type S = { [id: string]: number }
type A =
  { type: 'TYPE_1', payload: { id: string, num: number } } |
  { type: 'TYPE_2', payload: { test: number } } |
  { type: 'TYPE_3', payload: { visible: boolean } }

const f = (s: S = {}, a: A): S => {
  const p = a.payload

  switch (a.type) {
    case TYPE_1:
      return {
        ...s,
        [p.id]: p.num
      }
    case TYPE_2:
      return {
        ...s,
        ['empty']: p.test
      }
    case TYPE_3:
      return {
        ...s,
        ['empty']: p.visible ? 1 : 2
      }
    default:
      return s
  }
}
```

```
[p.id]: p.num
   ^^ property `id`. Property not found in
[p.id]: p.num
 ^ object type
------------------------
[p.id]: p.num
          ^^^ property `num`. Property not found in
[p.id]: p.num
        ^ object type
------------------------
['empty']: p.test
             ^^^^ property `test`. Property not found in
['empty']: p.test
           ^ object type
```
Here flow should be able to infer the refined type inside the first two `switch` cases, as with the third one.

I tried this with [tryflow](http://tryflow.org/#189dd728cfd02560cc6509587405fbcb).

**Comment by EnoahNetzach** [comment]
After some other testing and fiddling around, I found that simply reassigning p in every `case` "solves" the problem..

```es6
const TYPE_1 = 'TYPE_1'
const TYPE_2 = 'TYPE_2'
const TYPE_3 = 'TYPE_3'

type S = { [id: string]: number }
type A =
  { type: 'TYPE_1', payload: { id: string, num: number } } |
  { type: 'TYPE_2', payload: { test: number } } |
  { type: 'TYPE_3', payload: { visible: boolean } }

const f = (s: S = {}, a: A): S => {
  let p = a.payload

  switch (a.type) {
    case TYPE_1:
      p = a.payload
      return {
        ...s,
        [p.id]: p.num
      }
    case TYPE_2:
      p = a.payload
      return {
        ...s,
        ['empty']: p.test
      }
    case TYPE_3:
      p = a.payload
      return {
        ...s,
        ['empty']: p.visible ? 1 : 2
      }
    default:
      return s
  }
}
```

As can be seen [here](http://tryflow.org/#5dff9ab949337d90ad53a0537c01cec3).

**Comment by mroch** [comment]
Good find with the workaround. I think it makes sense, since in your first example, `a` hasn't been refined yet when you assign `p`, so `p` takes on the combined type of all the payloads. flow doesn't go back and refine all references that might be carried around when you do a related refinement.

I'm not sure we can reasonably do better here so I'm going to close this, but maybe @bhosmer can chime in/reopen if it is possible.

**Comment by EnoahNetzach** [comment]
That's unfortunate.. :(
The two strange things are that if you were to swap the `switch` with an appropriate `if` chain, it works as intended;
and the third `case` (the `TYPE_3` one) doesn't throw any error unless you remove the first two `case`s..

I hope all this could bring us to something. :)
