### ISSUE TITLE
Support Node's require('file.json')

### ISSUE THREAD

**Issue by glenjamin** [facebook/flow#167]
This seems somewhat related to #73 - i use a `config.json` which is loaded with `require` to setup default configuration for the application.

```js
StartApp(require('./config.json'));
```

This results in a "module not found" error, which can't be fixed via a declaration until it's possible to declare the default export - ideally require-JSON support would give me the complete object as a "type".

**Comment by tcoopman** [comment]
I believe this is a duplicate of #51?

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by jeffmo** [comment]
As of [Flow v0.20](https://github.com/facebook/flow/blob/master/Changelog.md#v0200), Flow can now understand what it means to `require()` or `import` JSON files.
