### ISSUE TITLE
Flow interfaces and subtyping

### ISSUE THREAD

**Issue by marcopaz** [facebook/flow#1678]
Hello, I'm working on a new project and I'd like to try flow. I have some questions:

1) I'm trying to override the type of a variable of a interface that extends another interface, something like this:

```
declare class MyClassA {}
declare class MyClassB extends MyClassA {}

declare interface MyInterfaceA {
  elm: MyClassA;
}

declare interface MyInterfaceB extends MyInterfaceA {
  elm: MyClassB;
}
```

is there a way to do so in flow? The above code gives an error "MyClassA is incompatible with type MyClassB". [Here](http://tryflow.org/#50258490597072f6743dcf86ba268658) the code in tryflow.

2) Is it possible to declare that a class must implement a given interface? In typescript I'd write
`class MyClass implements MyInterface`.

3) Is it possible to declare an interface method as optional?

4) I have an object type "A" and an object type "B" that includes all the properties of "A" plus some other, how can I express this in flow?

**Comment by zerkalica** [comment]
+1 for implements

**Comment by AgentME** [comment]
2) It's a hack, but when I'm making a class that is expected to implement an type, I usually have a dummy function that never gets called which tests that an instance of the class can be cast to the type:

```js
import type {ThingInterface} from './thing';

class Foo {
  constructor(blah: Blah, blue: Blue) {
    //...
  }
  //...
}

// This function does not get executed. It's only checked by Flow to make sure
// this class successfully implements the type interface.
function __interfaceCheck() {
  let test: ThingInterface = new Foo(({}:any), ({}:any));
}
```

**Comment by zerkalica** [comment]
Another hack: false condition for dead code elimination and destructing parameters.

```js
if (0) (new Foo(...(0: any)): ThingInterface) // eslint-disable-line
```

**Comment by samwgoldman** [comment]
> 1) I'm trying to override the type of a variable of a interface that extends another interface, something like this:

Like this:

```
declare class MyClassA {}
declare class MyClassB extends MyClassA {}

declare interface MyInterfaceA {
  +elm: MyClassA;  // <-- covariant property
}

declare interface MyInterfaceB extends MyInterfaceA {
  elm: MyClassB;
}
```

> 2) Is it possible to declare that a class must implement a given interface? In typescript I'd write
`class MyClass implements MyInterface`.

That exact syntax now works.

3) Is it possible to declare an interface method as optional?

```
interface I {
  m?: () => void;
}
```

> 4) I have an object type "A" and an object type "B" that includes all the properties of "A" plus some other, how can I express this in flow?

This is a bit trickier, if A is an exact object type, you can do this:

```
type A = {| x: number, y: number |};
type B = {...A, z: number};
```

If type A is not an exact object type, you can always factor out an exact object type like so:

```
type X = {| x: number, y: number |};
type A = {...X};
type B = {...X, z: number};
```

HTH
