### ISSUE TITLE
Improve how error is shown in case of missing default statement in switch case

### ISSUE THREAD

**Issue by singhshashi** [facebook/flow#1679]
While writing my reduce store, I missed writing the default case and then on running flow got the following error 

![image](https://cloud.githubusercontent.com/assets/371601/14639199/e6191f36-0658-11e6-8da2-55f1d4c809c0.png)

This was confusing and I ended up spending some time wondering why flow was interpreting UIState as undefined. When I actually pass add the default case and pass undefined then the error is much more clear.

![image](https://cloud.githubusercontent.com/assets/371601/14639265/475f2650-0659-11e6-84b2-65c6b682a2c5.png)

In the first error, the arrows point to UIState and say return undefined, which is confusing. Maybe the arrows could point at the reduce function and say that it returns undefined which is not compatible with declared return type UIState.

**Comment by mroch** [comment]
agreed, the position of the implicit return is not great. So something like this?

```
 15:    reduce(state: UIState, action: KaalAction) : UIState {
        ^^^^^^ implicitly-returned undefined. This type is incompatible with
```

could be a problem for anonymous functions, especially arrow functions which don't even have a `function` keyword to point at.

it could highlight the entire function body, which the CLI would print as

```
 15:    reduce(state: UIState, action: KaalAction) : UIState {
                                                             ^ implicitly-returned undefined. This type is incompatible with
```

I suppose that's not the worst...

**Comment by singhshashi** [comment]
Yeah.. I am not sure what's the best way, but the way it is currently is confusing.

**Comment by calebmer** [comment]
We have a special error now for implicitly returned undefineds!

https://flow.org/try/#0GYVwdgxgLglg9mABADwBQEoBciwgLYBGApgE6IDeAvkA
