### ISSUE TITLE
Perform ASI for class properties

### ISSUE THREAD

**Issue by mmazzarolo** [facebook/flow#1682]
Hello there,
it seems that semicolons are required by Flow for class methods and variables (#825 , #1517) and maybe even in other statements.  
Is there any plan for dropping the need of semicolons in the future?  
Babel doesn't need them (it has [already been discussed in the past](https://github.com/babel/babel/pull/3225)) and unfortunately semicolons clash with StandardJS and other common standards/linter configs.  

Thank you in advance.

**Comment by samwgoldman** [comment]
I think an earlier version of the class properties proposal required semicolons, but I believe updated versions allow for automatic semicolon insertion. You still need to be careful about starting a line with `(` and `[`, I imagine.

Kicking this over to Jeff, since he's the authority on this proposal. Thanks, Jeff!

**Comment by mmazzarolo** [comment]
`You still need to be careful about starting a line with ( and [, I imagine.`  
Yep, you are right, but this is easily forced by linting (and it's not that common).  

P.S.: Thanks, the title sounds definitely better now.

**Comment by aluanhaddad** [comment]
Semicolons are good for your health.

**Comment by mmazzarolo** [comment]
Hello there! 
Should the commit up here have fixed it?  
It's still not working for me on `flow-bin@0.24.2`:

The following snippet works: 
```javascript
import React, { Component } from 'react'
import { View } from 'react-native'

export default class Test extends Component {

  _testFunction = () => {
    return null
  }; // !!!

  render (): ReactElement {
    return <View />
  }
}
```

The following snippet returns `render (): ReactElement { -> Unexpected identifier`
```javascript
/** @flow */
import React, { Component } from 'react'
import { View } from 'react-native'

export default class Test extends Component {

  _testFunction = () => {
    return null
  }

  render (): ReactElement {
    return <View />
  }
}
```

Thank you again guys, have a nice day

**Comment by marudor** [comment]
Ah. My Commit was only for Class Properties. Not in general.

**Comment by mmazzarolo** [comment]
@marudor ouch, thank you anyway
I'd gladly contribute if anyone can point me to the right direction.

**Comment by mmazzarolo** [comment]
FYI it works fine now on :)
https://github.com/facebook/flow/issues/1517#issuecomment-265607128
