### ISSUE TITLE
flow 0.23.0 errors about Immutable not having default export

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#1687]
I just upgraded to Flow 0.23.0, now I get a bunch of errors like this:

```
node_modules/redux-plugins-immutable/src/lib/pluginReducer.js:3
  3: import Immutable from 'immutable';
            ^^^^^^^^^ Default import from `immutable`. This module has no default export.
```

Haven't checked the immutable code thoroughly, but I am able to use it, and I am using Babel 6.
Is there a one-line way to turn off all errors about `immutable` not having a default export?

**Comment by samwgoldman** [comment]
This would seem to be an issue with the library definitions you are using for Immutable, not Flow itself. Can you share the definitions you are using?

**Comment by jedwards1211** [comment]
I have some old ones sitting in a folder in my project, however that folder is not in the `[libs]` section of my `.flowconfig`.  The folder is within an `[include]` folder though, does that make its `declare`s get processed?  I don't think so because commenting out every line in those library definitions doesn't make any difference.

What's weirder is that I have two separate projects with nearly identical structure and only one of them has this problem.  I haven't figured out what the difference is yet.  The project with the immutable errors is also getting these, even though `fbjs/lib/warning` is clearly present:

```
node_modules/redux-plugins-immutable/src/lib/pluginReducer.js:4
  4: import warning from 'fbjs/lib/warning';
                         ^^^^^^^^^^^^^^^^^^ fbjs/lib/warning. Required module not found
```

To me it seems like there's some kind of bug.

**Comment by samwgoldman** [comment]
Can you share more information about your code? A repro would make diagnosing this very straightforward.

**Comment by jedwards1211** [comment]
Okay, assuming you have flow 0.23.0 installed, run:
```sh
git clone https://github.com/jedwards1211/flow-import-issue
npm i
flow status
```
I should note, there are `/* @flow */` annotations in the code in my `redux-plugins-immutable` package; might they cause problems since it's inside `node_modules`?

**Comment by marudor** [comment]
This would be because immutableJS exports flow definitions now.
But it does not have a default export. Thats why you get the error about Immutable not having a default export.

**Comment by jedwards1211** [comment]
Oh. Oops!  All the code their site refers to things as `Immutable.Map` etc. instead of `import {Map} from 'immutable'`, so I'm sure that's an error.  Thanks for letting us know!
