### ISSUE TITLE
Issue with generics, subclasses and interfaces

### ISSUE THREAD

**Issue by wayne-nlt** [facebook/flow#1695]
Hi,
I am trying to use template types with interfaces and subclasses, and I came up with the issue demonstrated below. As far as I can tell this should not cause any errors, as IX can still apply to Y.
Can anyone point me at what I am doing wrong?
Many Thanks,
Wayne

Waynes-MacBook-Pro:~ wayne$ cat flow-test.js 
```
"use strict";
/* @flow */

declare interface Finder<T> {
  find(): T;
}
declare interface IX {
}

declare interface IY extends IX {
  id(): number;
}

class X {

}

class Y extends X {
  id(): number { return 1; }
}

class YFinder {
  find() {
    return new Y();
  }
}

function YFinderFactory(): Finder<IY> {
  return new YFinder();
}

function XFinderFactory(): Finder<IX> {
  return YFinderFactory();
}
```
Waynes-MacBook-Pro:~ wayne$ flow check-contents < flow-test.js 
```
-:28
 28: function YFinderFactory(): Finder<IY> {
                                       ^^ property `id` of IY. Property not found in
 32: function XFinderFactory(): Finder<IX> {
                                       ^^ IX


Found 1 error
```
Waynes-MacBook-Pro:~ wayne$ flow version
Flow, a static type checker for JavaScript, version 0.22.1

**Comment by samwgoldman** [comment]
Type parameters are invariant by default. If you declare your `Finder<T>` type as covariant (`Finder<+T>`) there are no errors.

**Comment by wayne-nlt** [comment]
Thanks very much Sam, I had seen that around and was curious about it, now I know :)

For those looking for the documentation, see here: http://flowtype.org/docs/classes.html#polymorphism-and-type-parameter-variance
