### ISSUE TITLE
flow ignores check for undefined if done before callback

### ISSUE THREAD

**Issue by d14b3l** [facebook/flow#1697]
```javascript
function foo(bar/*: string | void*/) {
    var array = [1,2,3]
    if(bar !== undefined) {
        array.map( function() {
        bar.split( " " );
        })
    }
}
```

In example above there is check if bar is undefined but flow still complains that bar might be undefined inside map function.

```
example.js:7
  7:         bar.split( " " );
             ^^^^^^^^^^^^^^^^ call of method `split`. Method cannot be called on possibly undefined value
  7:         bar.split( " " );
             ^^^ undefined
```

**Comment by jeffmo** [comment]
Indeed, this is currently a limitation of flow (http://flowtype.org/docs/dynamic-type-tests.html#caveats)

Even though it's pretty obvious to you and I when reading this code, Flow doesn't understand that the `.map()` function is executed synchronously, only once, or that `bar` is never changed -- so it has to be conservative and forget about the type refinement you have here.

Until we get better at detecting these things, one way to give flow confidence would be to assign the `bar` parameter to a new variable inside the undefined-test if block:

```javascript
function foo(maybeBar: string | void) {
  if (maybeBar !== "undefined") {
    var bar = maybeBar;
    array.map(...);
  }
}
