### ISSUE TITLE
ES7+ class properties should not require semi-colons

### ISSUE THREAD

**Issue by nmn** [facebook/flow#1698]
Flow's parser has a problem with class properties right now.

This should work, but doesn't:
```
class X {
  state = {}
  render() {
    return null;
  }
}
```

This does work however:
```
class X {
  state = {};
  render() {
    return null;
  }
}
```

So flow requires a semi-colon where the proposal doesn't. According to the proposal, semi colons at the end of class properties are optional. They are only needed when then next method in the class is computed. Eg. Here the semi-colon should be required:
```
class X {
  state = {};
 [someVar]() {
    return null;
  }
}
```

**Comment by andreypopp** [comment]
Dup of #1682?

**Comment by nmn** [comment]
Duplicate of #1682. Closing.
