### ISSUE TITLE
Array literal can't use a union type

### ISSUE THREAD

**Issue by spicyj** [facebook/flow#17]
The following code fails to type-check:

```
/* @flow */

type T =
    {type: "a"; a: number} |
    {type: "b"; b: string};

var l: Array<T> = [
    {type: "a", a: 1},
    {type: "a", a: 2},
    {type: "a", a: 3},
    {type: "a", a: 4},
    {type: "b", b: "monkey"},
    {type: "b", b: "gorilla"},
    {type: "b", b: "giraffe"},
    {type: "b", b: "penguin"},
];
```

because the object literals' properties don't match up. It works correctly if I initialize the array as empty and then push each element on.

Should this code work as-is? Is there a better way to do tagged enums?

**Comment by avikchaudhuri** [comment]
Should be fixed in the next release, will close when it lands.

**Comment by samwgoldman** [comment]
This is an old issue, but I can confirm the original code produces `No errors!`, so this can be closed.
