### ISSUE TITLE
Untyped imported value passed to method declared with overloads prevents other arguments from being type-checked

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#1701]
This should fail but doesn't:

``` js
/* @flow */

import _ from 'lodash';

declare class Stream {
  combine(otherObs: Stream): Stream;
  combine(otherObs: Stream, combinator: any): Stream;
}

let s = new Stream();

s.combine(null, _.blah);
```

If you cast `_` to any or replace it with `({}: any)`, then you correctly get an error.

Flow version 0.23.0

**Comment by meandmax** [comment]
Looks somehow similiar to this behavoir! 

https://github.com/facebook/flow/issues/1696

**Comment by calebmer** [comment]
This is fixed in the latest version of Flow 👍 

https://flow.org/try/#0JYWwDg9gTgLgBAfTgMyhEcDkAbCATAQwGcALTAbgChK8BTAY2wKlrkeKLgGUYWCMA3pTht0AI2AA7WgAoIMErSgB5MUQBc3XrX4BKTTz4gqI+uKmz5ilWoPb+AGlEgJkgjGiaCkgJ76tRlQAvtTYtPCcALxw0gDuATogMrpUlEQAdGYuFjKSAK7Y2E4I6WJMJClAA
