### ISSUE TITLE
Class instances flow to interface constraints without validating statics

### ISSUE THREAD

**Issue by popham** [facebook/flow#1704]
Given the following, Flow doesn't generate any errors:

``` js
interface I {
  static x: number;
  static fn(): number
}

class Impl {
  static x: string;
  static fn(): string {
    return "some string";
  }
};
Impl.x = "another string";

function f(c: I): number {
  return c.constructor.fn();
}

var i = new Impl();
var n: number = f(i);
```

Flow should flag both members of `Impl` as incompatible with the corresponding members of `I`, right?  (I stumbled on this when babel 6.5.2--latest npm version--choked on an interface that includes the `static` "unexpected token" before a static method's signature.  Before I open a bug report over there, I want to verify that interfaces are intended to include statics--I asked this over at #803 a while back, but it was never _really_ resolved.)

**Comment by wbyoung** [comment]
@popham there seem to be some inconsistencies in what Flow is doing right now. Here's some strange behavior I'm observing in 0.42.0:

```js
/* @flow */

interface I {
  static x: number;
}

class Impl implements I {
  static y: number;
}

const iClass: Class<I> = Impl;
const implClass: Class<Impl> = Impl;

console.log(iClass.y);
console.log(iClass.x);
console.log(implClass.y);
console.log(implClass.x);
```

```
14: console.log(iClass.y);
                       ^ property `y`. Property not found in
14: console.log(iClass.y);
                ^ statics of I
17: console.log(implClass.x);
                          ^ property `x`. Property not found in
17: console.log(implClass.x);
                ^ statics of Impl
```

There should probably also be an error since `Impl` doesn't fully implement `I`, but Flow is noticing that `iClass` does have the static `x` while it doesn't have `y`.
