### ISSUE TITLE
Version bump missed in flowConfig.ml(?)

### ISSUE THREAD

**Issue by popham** [facebook/flow#1708]
For the latest master branch, `flow version` yields 0.23.0.  Shouldn't it be 0.23.1?

**Comment by jeffmo** [comment]
Sorry about that! I'll follow up in a few minutes with a 0.23.2 I suppose...

**Comment by jeffmo** [comment]
On second thought... Since we're planning to do the 0.24 release later this week, maybe I'll just bump the version to 0.23.1 in master and we'll just call this a blip in `flow version`'s history.

**Comment by jeffmo** [comment]
Fixed in https://github.com/facebook/flow/commit/d7000eb8226d181f9b447fc6ca049c20992842ca -- thanks for the report!
