### ISSUE TITLE
Emacs flow autocomplete??

### ISSUE THREAD

**Issue by cocodrino** [facebook/flow#171]
Hi guys, I notice than atom and brackets has support right now for facebook flow, providing a better autocomplete for javascript

you can check the screen captures here
https://atom.io/packages/ide-flow

unfortunately I can't found any similar package for emacs and is hard to find a package because the name "flow" is not the best choice and the search engines return any kind of results

is possible get similar behaviour in emacs?..I only can found a flow linter support

personally I hate the name flow :D maybe FFlow or FBFlow had been better but can be helpfull if in the documentation you add info about the support in differents ide/editors...

thanks!!!..

**Comment by avikchaudhuri** [comment]
There isn't an autocomplete feature yet for emacs, but it shouldn't be hard to write one (there's a client command that needs to be hooked up). Want to try?

**Comment by axyz** [comment]
is there any news about that? I'd like to properly integrate it on emacs, I'm quite new to emacs lisp, but if nobody is trying it out I'm considering to try to integrate it with flycheck and company.

Any advice will be really helpful (particularly quick links to documentation about getting a list of completion from flow to feed company), as for flycheck it should not be too much different from eslint or jshint implementations I guess.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mroch** [comment]
i don't use emacs, but it looks like this is supported now: https://github.com/facebook/flow/blob/5e2b96b12d6fc03f7411de34597877a5c28b4ac7/flow-types.el#L102

**Comment by bartonhammond** [comment]
Any instructions on adding the flow-types.el to emacs?

**Comment by CodyReichert** [comment]
@bartonhammond -- A little late, but in case anyone else is looking for instructions, you should be able to add this to your emacs init file (eg, `~/.emacs.d/init.el`):

```
(load-file "/path/to/flow-for-emacs/flow.el")
```

All of the functions in the file are just top level commands so you can `M-x flow` and see what's available. It's a bit lacking, but has a few good features.
