### ISSUE TITLE
JSON typechecking only possible with `flow check --all`

### ISSUE THREAD

**Issue by erydo** [facebook/flow#1714]
Valid JSON files cannot have the required `/* @flow */` pragma, and there is no way in `.flowconfig` to opt those files in. As a result, Flow does not have a way to typecheck imported JSON files except when running `flow check --all`, which can perform extremely poorly on some codebases.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!

**Comment by STRML** [comment]
This shouldn't be closed, it is still an issue.
