### ISSUE TITLE
ocp-build no longer produces windows binary

### ISSUE THREAD

**Issue by cdchambers** [facebook/flow#1728]
Evaluating ES5+Babel+Flow vs TypeScript for a large project. Need flow to at least work on Windows.  Ocamlpro guys has a binary for 0.19 but that's now .5 versions behind and the project looks to be inactive since last December. Happy to build the flow binary myself going forward, but need at least a 0.23 flow binary to get things started.

I checked out the commit in which the make.bat was first introduced (Nov 2015) but it doesn't seem to build either. The question is has there ever been a successful build of flow on Windows from master?

Is there any plan to support flow on Windows in the near future?

Would prefer Flow to TypeScript because of features like non-nullable types (a big one!) and generic resolution captures... but need at least a working build of a somewhat recent version of flow on Windows and a path to upgrade Flow to produce Windows binaries myself.

**Comment by sktguha** [comment]
:+1:

**Comment by mroch** [comment]
The Windows builds released by OcamlPro are based on a series of pull requests that haven't been merged into master yet. #1183, #1184, #1186

@gabelevi is working on updating them, fixing some perf/memory issues, and getting them merged. Soon!

**Comment by mroch** [comment]
gonna close this in favor of #6, but please follow that one so we can hopefully get you to help us test it!

**Comment by cdchambers** [comment]
@mroch @gabelevi would love to help test it! Any ETA re when we should expect them to appear on master?
