### ISSUE TITLE
Error Tracing for React Components wrong

### ISSUE THREAD

**Issue by marudor** [facebook/flow#1729]
Working on flow-typed I noticed the following problem.
With these Tests & Definition:
https://github.com/flowtype/flow-typed/pull/59/files
Flow will incorrectly trace the error of the commented out tests to the libdef file instead of the line of the error.
This results in the $ExpectError (SurpressError setting) to not work as there is no error in the line.

**Comment by asolove** [comment]
This is an interesting complication of the general issue with "wrong error locations", where a line marked `$ExpectError` can be the _cause_ of a type failure, but not the reported location, and therefore the error will still be reported.

**Comment by TrySound** [comment]
Seems like this is fixed.

This probably can be closed.
/cc @vkurchatkin
