### ISSUE TITLE
declaring constructor field on class silently breaks type-checking

### ISSUE THREAD

**Issue by nicks** [facebook/flow#1731]
Run flow on the following code:

```
'use strict' // @flow

class Foo {
  constructor: Function;
}

function f(): number { return new Foo() }
```

Expected: "Foo. This type is incompatible with the expected return type of number"
Actual: "No errors!"

If I remove the line `constructor: Function;`, the type-checking works as expected.

Repro'd on Flow 0.24.0

**Comment by nicks** [comment]
i guess i could be convinced that this is expected, but it seemed odd to me.

**Comment by calebmer** [comment]
`Function` is almost the same as `any`. If you want to give constructor a custom type (which is not recommended) try the following:

https://flow.org/try/#0MYGwhgzhAEBiD29oG8BQ1rHgOwgFwCcBXYPeAgLmgAoBKaAXgD4UBfAblVdVQDMjspAJY5ovOlWxEAtgCMApgRTQC8vEQLZo2eQHc4iOtG5A
