### ISSUE TITLE
Mixins seem incompatible with comment annotations

### ISSUE THREAD

**Issue by balupton** [facebook/flow#1737]
```
$ flow version
Flow, a static type checker for JavaScript, version 0.24.0

$ flow check
source/logger.js:86
 86: class Logger extends PassThrough /* : mixins Generic */ {
                                      ^^^^ Unexpected token /* :


Found 1 error
```

Which seems correct according to http://flowtype.org/docs/declarations.html#mixins and http://flowtype.org/blog/2015/02/20/Flow-Comments.html

**Comment by mroch** [comment]
I started trying to fix this and then realized a couple of things:

1) `/* : Foo */` turns into `: Foo`, so this would be like writing `class Logger extends PassThrough : mixins Generic`. to not have the extra `:`, you'd write `/* :: mixins Generic */`

2) `mixins` only works on `declare class`, not a real class

sorry it took so long to properly triage this...
