### ISSUE TITLE
Array type is incompatible with string when using rest with union type

### ISSUE THREAD

**Issue by glortho** [facebook/flow#1738]
I have a function that can take an array or strings as arguments:

``` javascript
type Args = Array<string | Array<string>>;

function myFn( ...args: Args ) {
  // use Array.isArray to check first member of arg etc.
}

myFn( [ 'foo', 'bar' ] );
myFn( 'foo', 'bar' );
```

This fails with:

```
  7: type Args = string | Array<string>;
                          ^^^^^^^^^^^^^ array type. This type is incompatible with
  7: type Args = string | Array<string>;
                                ^^^^^^ string
```

Am I annotating this incorrectly? (Flow 0.24)

**Comment by tryggvigy** [comment]
flow version `0.24.1` will warn you that:
![image](https://cloud.githubusercontent.com/assets/2373958/15481294/477f7db2-2119-11e6-8612-6f82a831a4e4.png)

**Comment by vkurchatkin** [comment]
Correct code:

```js
function myFn( arg: string | Array<string>, ...args: Array<string> ) {
}
```

This will allow `myFn(['str'], 'str')` though

**Comment by mejine** [comment]
Array<[string, mixed]>;
    static freeze<T>(o: T): T;
    static getOwnPropertyDescriptor(o: any, p: any): any;
    static getOwnPropertyNames(o: any): Array<string>;
    static getOwnPropertySymbols(o: any): Symbol[];
    static getPrototypeOf: Object$GetPrototypeOf;
    static is(a: any, b: any): boolean;
    static isExtensible(o: any): boolean;
    static isFrozen(o: any): boolean;
    static isSealed(o: any): boolean;
    static keys(o: any): Array<string>;
    static preventExtensions(o: any): any;
    static seal(o: any): any;
    static setPrototypeOf(o: any, proto: ?Objectyne

**Comment by avikchaudhuri** [comment]
Couldn't repro with 0.26.0.

```
function myFn( ...args: Array<string | Array<string>> ) {
  // use Array.isArray to check first member of arg etc.
}

myFn( [ 'foo', 'bar' ] );
myFn( 'foo', 'bar' );
```
gives `Found 0 errors`.

**Comment by glortho** [comment]
Sorry, I left out the full example, which points to `Array.isArray` and `.reduce` as culprits:
```javascript
function myFn( ...args: Array<Object | Array<Object>> ) {
  const stores = Array.isArray( args[0] ) ? args[0] : args;
  const foo = stores.reduce( ( memo, store ) => {
    memo[ store.key ] = store;
    return memo;
  }, {} );
  console.log( foo );
}

myFn( [ { key: 'foo' }, { key: 'bar' } ] );
myFn( { key: 'foo' }, { key: 'bar' } );
```
Fails with:
```
  4: function myFn( ...args: Array<Object | Array<Object>> ) {
                                            ^^^^^^^^^^^^^ array type. This type is incompatible with
  4: function myFn( ...args: Array<Object | Array<Object>> ) {
                                                  ^^^^^^ object type
```
Shouldn't flow recognize `store` as `Array<Object>`? It fails even if I type stores as such.

**Comment by samwgoldman** [comment]
cc @avikchaudhuri

**Comment by SamChou19815** [comment]
This is not a refinement that will be supported by Flow.
