### ISSUE TITLE
Incomplete type checking for objects property

### ISSUE THREAD

**Issue by StyMaar** [facebook/flow#174]
Hi,

It looks that the type checking seams really loose when it comes to object properties. 

For instance with type annotation : 

```JavaScript
/*
 * @flow
 */
function test1(obj: {a: boolean; b: string}){
  return 4 + obj.a; // 4 + boolean is unsafe
};
test1({a:true,b:""});

function test2(obj: {a: boolean; b: string}){
  if(obj.a){
    console.log("True");
  }
};
test2({a:42,b:""}); //obj.a is not a boolean
```
```
No errors!
```

Some validation is performed though:

```JavaScript

function test3(obj: {a: number; b: string}){
  return 4 + obj.a;
};

test3({a:null,b:""}); //obj.a is null
```
The validation is properly done in that situation:
```
 testFlow/scratchpad.js:25:10,13: null
This type is incompatible with
  testFlow/scratchpad.js:21:25,30: number
Found 1 error
```

The situation is even worst with type inference without annotation: 
```JavaScript
function test4(obj){
  return 4 + obj.a; //obj has no property a
};

test4({b:4}); //obj has no property a

function test5(obj){
  return 4 + obj.a; //obj.a type is wrong
};

test5({a:""}); //obj.a type is wrong
```
```
No errors!
```

I love this project though ;)

**Comment by avikchaudhuri** [comment]
You're hitting 4 separate cases, of which three are expected behaviors and one is a known feature/bug.

In your first code snippet:

(a)
number + boolean = number. This is according to JS semantics of + (boolean gets converted to number).

(b)
Second, anything is convertible to a boolean. This is why anything can be used in an if. In particular, a number is convertible to a boolean.

In your third code snippet:

(a) 
See issue #106 (and other related ones merged into that issue), along with the explanation of why Flow behaves the way it does with object properties.

(b)
number + string = string (again, following JS semantics of +)
