### ISSUE TITLE
failed to install flow-bin, ubuntu 14.04LTS, node 4.4.3 , npm 3.8.8

### ISSUE THREAD

**Issue by dannl** [facebook/flow#1743]
hi, I tried to install flow , but always got stuck at :

> xx@xx:~$ sudo npm install -g flow-bin
> /usr/bin/flow -> /usr/lib/node_modules/flow-bin/cli.js
> 
> flow-bin@0.24.1 postinstall /usr/lib/node_modules/flow-bin
> node lib/install.js
> //...1 or 2 hours passed, nothing happened....

is it a network issue or what?
any help would be greatly appreciated !!!

**Comment by yibuyisheng** [comment]
Same problem! And The version of flow-bin is `0.25`.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen if you are still having issues!
