### ISSUE TITLE
Guys, did anyone successfully use flow with babel? With actual type checking, not just stripping types.

### ISSUE THREAD

**Issue by idchlife** [facebook/flow#1744]
I have advantages of IDE autocomplete, errors, warnings etc. But I'm not getting any flow errors when I'm writing e.g.:

```
const a: number = 'string';
```

How is it possible to use flow for actually showing errors?

**Comment by jeffmo** [comment]
Confirming: Do you have `// @flow ` at the top of your file?

**Comment by idchlife** [comment]
@jeffmo yep.

![image](https://cloud.githubusercontent.com/assets/4563032/15020559/2a422a1c-122b-11e6-87eb-f2e91af910c2.png)

**Comment by jeffmo** [comment]
Hmm, [this](https://gist.github.com/jeffmo/0682a06fc212378bd8d46f2ae159b4ef) gives errors for me...

What output do you get when you run `node_modules/.bin/flow check` (assuming you're using `flow-bin`?) on the command line?

**Comment by idchlife** [comment]
@jeffmo  I'm using webpack + babel + plugins syntax-flow and transform-flow-strip-types. Those I found out on babel and flowtype websites in sections about using them together. Basically I see here that I lack of something that must be checking code before stripping types... But I'm not sure how to include those into flow

**Comment by jeffmo** [comment]
@idchlife: Can you confirm what output running `node_modules/.bin/flow check` gives on the command line?

This will help confirm whether Flow is set up properly on your system (or if there's an issue with the setup) before we go further into figuring out what's going wrong for you

**Comment by jeffmo** [comment]
In general, the workflow for Flow is:

1. Run `flow` on the pre-transformed code to check the types (and see any potential type errors)
2. Compile to strip away the extra type annotation syntax (i.e. Babel)
3. Run the output of the compilation

I'm not sure what workflow you have set up, so before we dig in to that I want to be sure that Flow is properly set up and installed for your project. Once we know that Flow is set up, we can see why you're not seeing any type errors

**Comment by idchlife** [comment]
@jeffmo yep, I installed flow-bin and it does work properly (showing some errors about not being able to find module Set from node_modules, but it's the lack of exclude, I think). Now I just need to find out how to use it with webpack, since flowcheck-loader fails unable to find flowcheck/transform module.

Thanks! The problem with setup, indeed. If I find solution I will post it here.
