### ISSUE TITLE
Declaration order of class methods causes inconsistent object errors

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#1745]
In the below code, `B` as a type error but `A` does not. Neither should have a type error.

```js
/* @flow */

class A {
  x: {[k:string]: number};

  m1() {
    this.x = {};
  }

  m2() {
    this.x.foo = 0;
  }
}

class B {
  x: {[k:string]: number};

  m2() {
    this.x.foo = 0;
  }

  m1() {
    this.x = {};
  }
}
```

```
test.js:23
 23:     this.x = {};
         ^^^^^^ assignment of property `x`
 16:   x: {[k:string]: number};
          ^^^^^^^^^^^^^^^^^^^^ property `foo`. Property not found in
 23:     this.x = {};
                  ^^ object literal
```

**Comment by avikchaudhuri** [comment]
@samwgoldman This is pretty clowny. I know what's happening. We consider read/write of a property on a dictionary to be non-strict, where the non-strict flag is intended to ensure that we don't error if the property is not found. Unfortunately we also use the non-strict flag as a signal to add the property when it doesn't exist. The latter is totally wrong: we should be using non-sealed as the signal for adding a property instead. Will fix.
