### ISSUE TITLE
Declare private methods and properties in comments

### ISSUE THREAD

**Issue by vjpr** [facebook/flow#1746]
I do not like the underscore convention for privates in JavaScript.

I propose adding a comment-based way to specify private methods and variables.

E.g.

```js
class Foo {

  // this is foo
  // @private
  foo;

  // this is bar
  // @private
  bar() {

  }

}
```

Because the `munge_underscores` flag is already implemented, this should be easy to do.

We should allow a custom regex for the comment format (similar to the `suppress_comment` option).

Would be great if the regex could support parsing AtomDoc (TomDoc syntax) - the documentation used in Gihub's Atom Editor.

```js
class Foo { 
  // Public: foo is a foo
  // 
  // Foo foo foo.
  foo;
}
```

We should also support JSDoc style comments too.

```js
class Foo { 
  /**
   @private
   */
  foo;

  /** @private */
  bar;

  /* @private */
  baz;
}
```

**Comment by thejameskyle** [comment]
Flow does have a [comment syntax](https://flowtype.org/blog/2015/02/20/Flow-Comments.html) but no support for private class members.

Merging this into the feature request issue for private class members: #275
