### ISSUE TITLE
 Property cannot be assigned on possibly null value, even after check for the property

### ISSUE THREAD

**Issue by clentfort** [facebook/flow#1747]
Well there is not much to say to this error, flow complains when assigning a property, even though I check for the properties existence.

Flow Version: 0.24.1
Repo: http://tryflow.org/#21c2d7c6d5563c877e5b977772387e1f

**Comment by calebmer** [comment]
Try assigning the property to a constant. This is intentional behavior that prevents bugs, we will be updating error messages to better point this out soon 👍
