### ISSUE TITLE
Aliasing inferred types

### ISSUE THREAD

**Issue by jareware** [facebook/flow#175]
If I use this fairly common pattern for object creation:
```
function createFooBar() {
    return {
        doThings() {}
    };
}
```
...is there any way for me to annotate other parts of my codebase as expecting the inferred return type of `createFooBar()`, along the lines of:
```
function baz(x : FooBar) {}
```
Would it be possible, for instance, to somehow alias the inferred return type into `FooBar`?

I know I can declare `type FooBar = { doThings: () => void }` but I'd rather avoid the duplication, if possible! :)

**Comment by avikchaudhuri** [comment]
Merging with #47.

**Comment by mindeavor** [comment]
This doesn't seem related to #47. Here's a counter-example use case:

```javascript
exports.makeWidget = function () {
  return { name: "My Widget" }
}

exports.renderWidget = function (widget: ???) {
  return widget.name
}
```

`renderWidget` expects an object that is the return type of `makeWidget`. Is this possible?

**Comment by samwgoldman** [comment]
flow requires you to annotate exported types anyway, so this should do it:

```
type Widget = { name: string }

exports.makeWidget = function(): Widget {
  return { name: "My Widget" }
}

exports.renderWidget = function(widget: Widget): string {
  return widget.name
}
```

**Comment by mindeavor** [comment]
Ah, I see... that's unfortunate...

**Comment by samwgoldman** [comment]
@mindeavor Can you elaborate?

**Comment by mindeavor** [comment]
With this setup I need to annotate every property I create in `myWidget`, which feels like flow's type inference isn't being that useful.

**Comment by samwgoldman** [comment]
I don't agree. Flow is doing exactly the appropriate inference.

Consider the following code:
```javascript
function makeWidget() { return { name: "widget" } }
function renderWidget(widget) { return widget.name }
var f: number = renderWidget(makeWidget()) // error: number incompatible with string
```

Flow is able to infer that the return type of `makeWidget` is a valid argument type for `renderWidget`. That is, it infers the types `makeWidget(): { name: string }` and `renderWidget<T>(widget: { name: T }): T`.

However, if you want to let the type checker enforce that relationship, you need to annotate. Now, even if you don't, flow should complain at the call sites:

```javascript
function makeWidget() { return { name: "widget" } }
function renderWidget(widget) { return widget.oops }
var f = renderWidget(makeWidget())
```
```
test2.js|5 col 9 error|  function call
|| Error:
test2.js|4 col 40 error|  property oops
|| Property not found in
test2.js|3 col 32 error|  object literal
|| 
```

But the annotation only serves to make your intention clear.

**Comment by mindeavor** [comment]
I understand that flow does have type inference. I'm talking about the case of exports, where you export both factories and functions on the result of those factories. I imagine this is a common case.

Annotations do make intent clearer, but they also require you to update code in two places.

**Comment by samwgoldman** [comment]
What have you actually tried? Can you share some code that is written the way you would like which either a) raises an error when you don't expect one or b) does not raise an error when you do?

**Comment by mindeavor** [comment]
Here's my use case stripped down to a minimal example. I must be doing something wrong, because this example doesn't throw a type error:

```javascript
/* @flow */

function controller () {
  var ctrl = {}
  ctrl.mode = 'show'
  ctrl.updateMode = function (newMode) { ctrl.mode = newMode }
  return ctrl
}

function view (ctrl, options) {
  ctrl.updateMode('edit')
  ctrl.idontexist() // <-- no type error?
  return options.testContent + "!"
}

// Attempted workaround for issue; use explicitly for flow type checking
view(controller(), { testContent: 'hello' })
```

**Comment by samwgoldman** [comment]
Ah! Thanks for the clear example. You've identified an interesting issue, but not the one you expected:

If I change your definition of `controller`, I get the expected error:

```
function controller () {
  var ctrl = {
    mode: 'show',
    updateMode: function (newMode) { ctrl.mode = newMode }
  }
  return ctrl
}
```
```
test2.js|18 col 1 error|  function call
|| Error:
test2.js|13 col 3 error|  call of method idontexist
|| Property not found in
test2.js|8 col 10 error|  object literal
|| 
```

I think what's happening is that flow doesn't consider the object "sealed" when built incrementally like this, but it seems like a bug. Would you open up a new issue with that exact code example?

**Comment by mindeavor** [comment]
Sure, I'm happy to create an issue. To be clear though, it's not related to the issue at hand. The line I labeled as a workaround is the problem; in order for flow to type check, I have use that workaround (run the code within my module with test data), or I have to annotate the return value of my controller as you suggested. Both require updating my code in two places. If I add unit tests, that becomes three places.

**Comment by samwgoldman** [comment]
OK, I guess I'm not clear how you expect flow to understand the relationship between two functions "automatically." What information does flow have that would make it clear that `controller` and `view` have this relationship that the return type of one is the parameter type of the other?

**Comment by mindeavor** [comment]
It would be nice to do this:

```javascript
exports.makeWidget = function () {
  return { name: "My Widget" }
}

exports.renderWidget = function (widget: typeof exports.makeWidget()) {
  return widget.name
}
```

I'm not suggesting you do this, or even suggesting it's reasonable :) This is just a feature I would want when using a type system.
