### ISSUE TITLE
Requiring a file without the pragma provide unhelpful error message

### ISSUE THREAD

**Issue by karlbright** [facebook/flow#176]
Given the two files:

```javascript
/* @flow */
// src/foo/foo.js
var bar require('../bar/hello-world');
module.exports = bar();
```

```javascript
// src/bar/hello-world.js
module.exports = function() { return "hello world"; }
```

Flow returns an error with the message "Required module not found". Based on this message you assume the require statement is looking in the wrong location, you have provided it the incorrect path. You double check and see that is is set correctly and try again, same issue.

This can be resolved by adding the flow pragma to the top of the file you are trying to require. You could argue that this is how it should work, to provide data flow checking. However the error message that Flow provides doesn't make it clear as to why it is not working.

**Comment by avikchaudhuri** [comment]
Sorry, but I could not reproduce this: I get a required module not found error only when I make a mistake naming hello-world.js (say, as helloworld.js), but not in the scenario you describe.

Specifically, I added a .flowconfig to src/ and ran flow check src/.

Could you share your setup?

**Comment by samwgoldman** [comment]
@karlbright If you can reproduce this, please reopen. It would be particularly helpful if you could share a repo that exhibits the issue.
