### ISSUE TITLE
constructor call. Method cannot be called on T.

### ISSUE THREAD

**Issue by cameron-martin** [facebook/flow#1760]
If I try to typecheck the following code:

```javascript
function construct<T>(constructor: Class<T>): T {
  return new constructor();
}
```

I get the following error:

```
 88:   return new constructor();
              ^^^^^^^^^^^^^^^^^ constructor call. Method cannot be called on
 88:   return new constructor();
                  ^^^^^^^^^^^ T
```

It seems like this code should be valid.

**Comment by vkurchatkin** [comment]
Flow has now way of knowing what arguments should be passed to constructor

**Comment by cameron-martin** [comment]
Good point. For my use, this will never be able to be safe (probably without dependent types), so I had to cast `constructor` to `any`.

**Comment by vkurchatkin** [comment]
@cameron-martin See: https://github.com/facebook/flow/issues/1409. To avoid `any` you can pass factory function instead of constructor
