### ISSUE TITLE
Flow does not recognize variable when used within withMutations of an immutable type

### ISSUE THREAD

**Issue by singhshashi** [facebook/flow#1764]
In my ReduceStore, I am batching a bunch of changes to the immutable state using withMutations as follows: 

```
  const appStateId = action.signedInUser._id + '-'+ Date.now().toString();
  changedState = state.withMutations(st => {
    st.set('_id',appStateId).set('signedIn', true).set('signedInUser', action.signedInUser)
  });
```

When running flow I get the following error:

```
 35:             st.set('_id',appStateId).set('signedIn', true).set('signedInUser', action.signedInUser)
                                                                                           ^^^^^^^^^^^^ property `signedInUser`. Property not found in
 35:             st.set('_id',appStateId).set('signedIn', true).set('signedInUser', action.signedInUser)
                                                                                    ^^^^^^ object type
```

Since flow did not throw the error for the line

`const appStateId = action.signedInUser._id + '-'+ Date.now().toString();`

should it throw the error, when used within the context of withMutations? The code works as expected and the correct value is assigned to signedInUser. So this seems like an issue with flow.

**Comment by calebmer** [comment]
Flow forgets refinements in closures to prevent the case where a user may write `action.signedInUser`. Make `signedInUser` covariant to fix this error 👍
