### ISSUE TITLE
Hoisted functions defined after control flow exits scope are not type checked

### ISSUE THREAD

**Issue by mbergal** [facebook/flow#1769]
c is not declared, but file type checks:

```
/* @flow */

function a(a:number) {
    return b(a);

    function b(b) { return c + 1; } // c is not declared
}

a(1)
```

See #205.

Flow 0.23.0

**Comment by despairblue** [comment]
Also in 0.24.2

**Comment by calebmer** [comment]
This is fixed in the latest version of Flow 👍 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBDACjIC5tMBbAIwFMAnASjAG9Uw+xWzfJlalGVdgG50-MFjxESYcY05cBQkaVxgA1GACMksAF8wwYGB2EAzmGxx8YACbNcMMoOeoT6SgfYgA
