### ISSUE TITLE
Requiring a module with __dirname ignores the inclusion of flow pragma.

### ISSUE THREAD

**Issue by karlbright** [facebook/flow#177]
Somewhat related to issue https://github.com/facebook/flow/issues/176.

Given the two files:

```javascript
/* @flow */
// src/foo/foo.js
var bar require('../bar/hello-world');
module.exports = bar();
```

```javascript
// src/bar/hello-world.js
module.exports = function() { return "hello world"; }
```

Flow will return an error stating the the required module could not be found. However if we change the require statement to the following, it shall not return this error message.

```javascript
/* @flow */
// src/foo/foo.js
var bar require(__dirname + '../bar/hello-world');
module.exports = bar();
```

**Comment by avikchaudhuri** [comment]
Umm, I'm pretty sure Flow has no idea what __dirname + ... resolves to. :)

Will revisit this once you provide more information about #176, OK?

**Comment by samwgoldman** [comment]
I think you avoid the error because flow ignores require statements whose argument is not at string literal. Please reopen if this is different from #176, and you can share some repro code. Thanks!
