### ISSUE TITLE
module.name_mapper let the type imports, but no type checking

### ISSUE THREAD

**Issue by bsr203** [facebook/flow#1773]
I have the following in my `.flowconfig`.

```
module.name_mapper='^frontend\/\(.*\)$' -> '<PROJECT_ROOT>/src/frontend'
```
when I import type from a file like

```
import { iDontExist } from 'frontend/utils/response';
```
there is no error.

> ❯❯❯ flow                                                                                                                                                 
> No errors!

but, if I use relative path, 

```
import { iDontExist } from '../../../../../frontend/utils/response';
```

flow detects the error

> 
> ❯❯❯ flow                                                                                                                                                 
> src/frontend/bundles/common/components/Conf/ConfList.js:11
> 11: import { iDontExist } from '../../../../../frontend/utils/response';
>              ^^^^^^^^^^ Named import from module `../../../../../frontend/utils/response`. This module has no named export called `iDontExist`.
> 
> 
> Found 1 error

**Comment by bsr203** [comment]
flowconfig
-----
```
[ignore]
.*/bin/.*
.*/build/.*
.*/dist/.*
.*/docs/.*
.*/server/.*
.*/__tests__/.*
.*/node_modules/fbjs.*
.*node_modules/babel-core.*
.*/node_modules/.*/\(lib\|test\).*\.json$
[include]

[libs]
./interfaces/

[options]
module.system=haste
munge_underscores=true

esproposal.class_static_fields=enable
esproposal.export_star_as=enable
esproposal.class_instance_fields=enable

module.name_mapper='.*\(.scss\)' -> 'empty/object'
module.name_mapper='^frontend\/\(.*\)$' -> '<PROJECT_ROOT>/src/frontend'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(2[0-1]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(>=0\\.\\(2[0-1]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*\\)?)\\)? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixedInNextDeploy

[version]
0.22.1
```

**Comment by mroch** [comment]
I think the problem here is that your mapper is mapping `frontend/path/to/file` to `/path/to/root/src/frontend`, not `/path/to/root/src/frontend/path/to/file`. try something like `<PROJECT_ROOT>/src/frontend/\1`

do you have a `src/frontend/index.js` file, likely without `@flow`? that would explain why it didn't error about an unknown module, since it was actually resolving to a file.

**Comment by bsr203** [comment]
@mroch thanks a ton. You are correct in the cause and solution. I had `src/frontend/index.js` without flow annotation, and adding `\1` solved the issue and getting type errors. Cheers.
