### ISSUE TITLE
How to reuse types in declaration files. Bug?

### ISSUE THREAD

**Issue by zerkalica** [facebook/flow#1778]
I try to reuse exported interfaces between declaration files, but got an error:

```bash
src/index.js:4
  4:     TestFn
         ^^^^^^ Named import from module `flowtest`. This module has no named export called `TestFn`.
```

```js
// flow-typed/flow-test-a.js
/* @flow */

declare module 'flowtest' {
    declare type TestFn = Function;
}
```

```js
// flow-typed/flow-test-b.js
/* @flow */

import type {
    TestFn
} from 'flowtest'
```

```js
// src/index.js
/* @flow */

import type {
    TestFn
} from 'flowtest'
```

Problem with filenames sorting, if i rename flow-test-a.js to flow-test-c.js, all works fine. Probably bug?
I created repository with this files: https://github.com/zerkalica/flowtest-bug

How to reuse types in project itself alike in imported projects?

In flow examples i found only ugly hack: all reusable types are prefixed and placed in one big file with exported declarations, like [buffer$NonBufferEncoding](https://github.com/facebook/flow/blob/master/lib/node.js).

But i want to write types once for internal and external purposes and place them in multiple files.

**Comment by samwgoldman** [comment]
This is something we're working on (see flowtype/flow-typed#16), but for now the recommended way is to create a top-level declaration with a prefix containing the module name and $. For example, for a module `foo`, something like this:

```
class foo$Foo {
  // ...
}

declare module foo {
  declare var Foo = typeof foo$Foo;
}
```

Then you can depend on the top-level declaration from another module declaration, bar:

```
declare module bar {
  declare class Bar extends foo$Foo {
    // ...
  }
}
```
