### ISSUE TITLE
Stripping exported type aliases

### ISSUE THREAD

**Issue by skogsbaer** [facebook/flow#178]
I have a module defining a type alias. I want to use the type alias in another module, so I export the type alias.

```
// module LogParser.js
module.exports = { parseAccessLog, NetperfEntry };
type NetperfEntry = { time: Date; host: string; perf: Array<Timespan> };
```

```
// module Persistence
var Parser = require('./LogParser.js');
class Persistence {
  addEntry(entry: Parser.NetperfEntry): void {
    console.log("time=" + entry.time + ", host=" + entry.host);
  }
}
```

flow happily type checks this code. To run the code, I use jsx to strip away the types. jsx also removes the type alias definition, but not the export. Thus, when running the code, I get

```
ReferenceError: NetperfEntry is not defined
```

How to fix this problem?

Note: this problem is possibly related to #47.

**Comment by avikchaudhuri** [comment]
Yeah, you shouldn't include types in your exports. (Ideally we should report an error when you do.) The stripping transform has no idea when arbitrary run-time expressions could in fact resolve to compile-time only type aliases. (In your example, it's fairly simple to detect, but in general it isn't.)

As @k-bx mentions, export/import of type definitions is a known missing feature that will be implemented soon. Meanwhile, you need to duplicate type aliases, sorry! :(

(Merging with #16)
