### ISSUE TITLE
Flow as an OCaml API

### ISSUE THREAD

**Issue by fxfactorial** [facebook/flow#1781]
I have some ideas about flow and I'm wondering if flow exposes an OCaml public api, like compiler-libs does for the OCaml compiler. 

For example, say I give a snippet of JavaScript code in my OCaml code to Flow, then I want it to typecheck it for me and other fancy things. 

Is this currently possible, or can I scrape together an API myself?

**Comment by bwestergard** [comment]
In this vein: is there, or could there be, a Javascript API for flow? I'm writing code to generate Flow-annotated code, and would like to automatically check that the latter typechecks.

**Comment by saadq** [comment]
@bwestergard There is [`flow-parser`](https://www.npmjs.com/package/flow-parser) on npm. 

Usage:

```js
import flow from 'flow-parser'

flow.parse('let x = 4')
```

**Comment by saadq** [comment]
Woops sorry, that package is just used for parsing some code into an AST. It looks like the regular `flow-bin` package has an example of [how it can be used programatically](https://www.npmjs.com/package/flow-bin#api).
