### ISSUE TITLE
Broken subtyping of declared class methods with return type `this`

### ISSUE THREAD

**Issue by popham** [facebook/flow#1784]
I get 0 errors when I modify `lib/test.js` from the `declare_class` test to

``` js
declare class _C {
  foo(): this; // was `number`
}
declare var _module: {
  C: Class<_C>;
}
declare class D extends _module.C {
  foo(): string;
}
```

Shouldn't Flow complain about inconsistent use of library definitions?  (Changing the return type of `D`'s `foo` to `this` and leaving `_C` alone induces the expected "inconsistent use of library definitions" error.)

**Comment by calebmer** [comment]
This is fixed in the latest version of Flow 👍 

https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwPoGF4G8BQ88AZgPYkAUAlAFzwAuAFgJbIDc8A9B-AO4rwADAHYBXALYAjEDAF4AvnlBI48AG6wMYksBEQQtfIUy1M0VAB4sAPlbzF4aCqSp4AEXggAHnRBDgadC0dPQA6bENiMipaZDoYJiEAc1sFIA
