### ISSUE TITLE
Problems with .d.ts files (mocha and assert)

### ISSUE THREAD

**Issue by skogsbaer** [facebook/flow#179]
Hi,

I tried to get mocha working with flow. I used the following two .d.ts files:

https://github.com/borisyankov/DefinitelyTyped/blob/master/assert/assert.d.ts
https://github.com/borisyankov/DefinitelyTyped/blob/master/mocha/mocha.d.ts

The assert.d.ts file is not accepted by flow. I could fix it by replacing "export" with "declare" and by removing the constructor declaration in class AssertionError.

The mocha.d.ts file is accepted by flow, but flow then does not typecheck a call of the describe function. Here is the declaration in the mocha.d.ts file:

```
declare var describe : {
    (description: string, spec: () => void): void;
    only(description: string, spec: () => void): void;
    skip(description: string, spec: () => void): void;
    timeout(ms: number): void;
}
```
I could fix this problem by writing instead

```
declare function describe(description: string, spec: () => void): void;
declare var describe : {
    (description: string, spec: () => void): void;
    only(description: string, spec: () => void): void;
    skip(description: string, spec: () => void): void;
    timeout(ms: number): void;
}
```

Are this know issues?

**Comment by avikchaudhuri** [comment]
In general, .d.ts files won't work as is with Flow. A converter is in the works (see http://flowtype.org/docs/coming-soon.html#_).

For the example you have, you should try the following instead:

declare class describe {
    static (description: string, spec: () => void): void;
    static only(description: string, spec: () => void): void;
    static skip(description: string, spec: () => void): void;
    static timeout(ms: number): void;
}

Otherwise I suspect that while calls to describe work, calls of static methods on describe (e.g., describe.timeout("invalid") will not be type checked properly.

**Comment by buzinas** [comment]
@avikchaudhuri  Any preview date for this converter?
