### ISSUE TITLE
defining (but not calling) a function assigning to this in class constructor leads to unnecessary error `Property cannot be assigned on possibly undefined value unintialized this (expected super constructor call)`

### ISSUE THREAD

**Issue by charlieschwabacher** [facebook/flow#1790]
```
// @flow
class A {}
class B extends A {
  constructor() {
    const func = () => {
      this.a = 1;
    };
    super(func);
  }
}
```

The code above fails type checking - `func` here is not accessible outside of the constructor, and is never called before being passed to super.

**Comment by calebmer** [comment]
This is fixed in the latest version of Flow:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBjaBDAzh0BBUBvAXxXS1ACFQBTADwBcqA7AE2z30VFGVkYzoBOAV2R1YAgBQBKApy7de-UJCGNkoALyhpmgHyz58ugAsAlhgB0aTaACMAbjldCjwxiEAHKpJVqpr0GJCIA
