### ISSUE TITLE
Return-values from class constructors

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [facebook/flow#1796]
So, Flow seems to be pretty ignorant about [the semantics of `new`](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ecmascript-function-objects-construct-argumentslist-newtarget), overall:

``` es6
class Foo {
   constructor() : Function {
      return function(){} }}

const f = new Foo
f()
```

http://tryflow.org/#70e7c222d9db485d1c31c007acf2fb73

```
flow-test.js:8
  8: f()
     ^^^ function call. Callable signature not found in
  8: f()
     ^ Foo
```

And this one makes even _less_ sense:

``` es6
const f = function(){ return new Number(5) }
    , n = new f()

n + 1
```

http://tryflow.org/#6d6c0dff3a167772654fae019f1ee8c4

```
flow-test.js:7
  7: n + 1
     ^ Number. This type cannot be added to
  7: n + 1
     ^^^^^ string

flow-test.js:7
  7: n + 1
         ^ number. This type cannot be added to
  7: n + 1
     ^^^^^ string
```

Is this intentional, just to be opinionated about Good Practice; or might I consider it a bug? (Patterns like this are pretty common in my codebases, and are quite intentional; this is something of a blocker for me!)

**Comment by ryyppy** [comment]
This is a very interesting way to express your APIs... what is your benefit of utilizing `new` to return a completely different closure / type from a constructor? 

Isn't the whole point of prototype to create an instance of the given class description?
This really looks like something you would express in a factory function, which is class-less.

Would be interesting to see some details about your mentioned codebases

**Comment by ELLIOTTCABLE** [comment]
@ryyppy I'd argue that that's a very Java-centric view; JavaScript is often used in a very not-classist-inheritance-oriented manner. (The very idea of a ‘factory’ is so un-JavaScript …)

To be clear, yes, the same thing *can* be expressed in that style; but isn't the point of Flow somewhat that it can statically type-express *current* JavaScript paradigms / approaches? Instead of having to re-write existing code to fit existing type paradigms like that?

As for the purpose in existing codebases: Often, a particular module might express a ‘class-ish’ thing (from the perspective of the user / consuming-implementor), but that ‘class-ish’ thing needs to be *invokable*. Objects (created via constructor-invocation of existing Functions) in JavaScript are not callables; in JS, that can only be expressed by a Function object … so to simulate a callable ‘class instance’, we use an apparent constructor-function, that instead returns a constructed (either statically, or dynamically through `Function(body)` / `(1,eval)(body)`) Function object.

(I'm sorry if the above comes across as condescending, I've re-written this response something like four times. I think I'm just a little shocked that somebody who writes JavaScript regularly isn't familiar with this pattern. Probably something like half of the JS APIs I've ever written have included a ‘callable object’ using this pattern; and I've seen it leveraged in plenty of others' libraries and APIs, so I perceive it as extremely common …)

**Comment by ryyppy** [comment]
Alright, I am sorry to hear that. Discussion aside, I think I found out why your second example doesn't work (`return new Number(5)`).

So you are returning the wrapper type `Number`, which is an `Object` and you try to add it to a primitive `number`, which is not an object... JavaScript implicitly calls the `.toString()` method before concatenating, which causes flow to throw an error (string cannot be added to number).

To fix this, you have to use the `.valueOf()` method, which (as defined by flowtype's core.js lib) will return a number.

```
const f = function()  {
    return new Number(5);
}

const n = new f;

const x = n.valueOf() + 1;
```

http://tryflow.org/#0454d2f7c7a8da55d345a6965cdfedd3

For the first example, I don't know how one would solve this. I realized that immutablejs is doing this `return some other context from constructor` thing tho. Maybe you can find some hints in it's typescript declarations?

Does this help somehow?

**Comment by ELLIOTTCABLE** [comment]
Re: the second (your first), that workaround is clearly the way out *at the moment*; but I suppose it just seems to me that some of JavaScript's core semantics re: auto-boxing / auto-unboxing primitves should probably be understood and represented by Flow in a reliable manner? (Again: This isn't posed in a “this is a good idea and we should encourage people to do it” sort of way, but rather in a “Flow works on top of Real World JavaScript, and has a design goal *(see below)* of supporting JavaScript as-is instead of forcing particular usage patterns; so making sure that basic JavaScript mechanics are supported and function intuitively is important” sort of sense! I'm only interested in UX here, not good practice. `=)`)

(For instance, as concrete suggestion, could primitives' operations be encoded in Flow as involving auto-boxing, so that the boxed types thus implicitly support all the same operations that the primitives currently do? Forgive me again, I don't know Flow's internals well. At least, not yet!)

Re: first (your second), I have [a functioning workaround](https://gist.github.com/ELLIOTTCABLE/84737219da76c2b7b641a9c3702b85d1#file-gistfile1-flow-js-L23-L25) *for myself* (typing a function as a ‘callable object’ works; which, to be fair, matches the letter of the ES6 semantics `=P`), it just feels like … V. Scary Black Magic. Again, I only bring this up from a UX perspective, not a “help me solve this problem I have” perspective. (I mentioned it being a blocker in terms of mindset, not in terms of me-not-having-a-workaround: if workarounds like this are necessary for common JavaScript patterns, Flow might not be something I wish to adopt at a large scale across my various works, y'know? I'm one of the people who leverages JavaScript as, well, JavaScript; not as a pseudo-classist language, so I'm not too surprised that a static-type-analysis system doesn't play too well with my code … `=P`)

----

The more I write here, the more it becomes clear I should be asking *this*, before continuing to try and produce feedback: I think I need some clarification on Flow's direction and intentions. While some statements from the [introductory blog-post](https://code.facebook.com/posts/1505962329687926/flow-a-new-static-type-checker-for-javascript/)¹ and [docs](http://flowtype.org/docs/about-flow.html#idiomatic)² led me to assume that Flow, in all cases, is designed to attempt to support JavaScript common-practices of all sorts, even when they're inherently resistant to static analysis (yay dynamic languages `>,<`), I'm starting to think I'd gotten the wrong idea.

Simply put: in terms of the larger (and longer-term) goals of the Flow project, should I consider Flow-incompatibilities with the edge-cases and nasty corners of JavaScript's semantics (especially ones that are heavily used in legacy, small-team, or OSS JavaScript codebases) as ‘bugs’, i.e. things for which Issues / patches / pull-requests would be ideal; or instead as intentional encouragement towards better practices / wontfixes?

> 1. “We have designed Flow so developers can reap its benefits without losing the “feel” of coding in JavaScript.” “Flow does not force you to change how you code — it performs sophisticated program analysis to work with the idioms you already know and love.”

> 2. “Writing code with Flow should feel like writing JavaScript, from the common idioms in the language to the fast development cycle.” “Flow is designed to understand even very dynamic code which is often found in JavaScript programs.”
