### ISSUE TITLE
Error when trying to create "generic" classes that inherit from another one.

### ISSUE THREAD

**Issue by graphman65** [facebook/flow#1798]
``` javascript
class MyComponent<DefaultProps, Props, State> extends React.Component<DefaultProps, Props, State> {}

type MyProps = {};
type MyState = {};

let blah : MyComponent<void, MyProps, MyState>; 
```

The first line is giving me error telling that I may forget to declare State.
In the react declaration file, defaultProps and state are defined as Abstract types of DefaultProps and State. Flow seems to not understand them the right way in this case.

A workaround is to define defaultProps and state in this child class.

**Comment by STRML** [comment]
See https://github.com/facebook/flow/blob/2600ed9b43d6b8af461d3713889e5c8d2cdbd069/lib/react.js#L53 - if you subclass React.Component, you need to redeclare state, defaultProps, and props.

**Comment by asolove** [comment]
If I update this to Flow v0.53, [the updated code](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQduANmugLICeAwiZAHZY+MADwAFYmFQAaOAGUYyGFgB8cLAA8lfACbpseGADoe4CAKFiJ0uQqWqA3gF86QA)now works fine. There were changes to the `Component` type in v0.53 specifically to deal with problems like this, so I think this issue can now be closed (/cc @calebmer)
