### ISSUE TITLE
flow ls command does not exist in 0.25.0

### ISSUE THREAD

**Issue by oliverzy** [facebook/flow#1799]
I downloaded 0.25.0, and it seems the binary doesn't contain ls command

**Comment by mroch** [comment]
hm, indeed. looks like it landed after the 0.25 release branch was cut but made it into the release notes by mistake. it'll be in 0.26 soon, though!

@gabelevi should/can we edit the release notes?

**Comment by mroch** [comment]
the release notes look like they were updated and we forgot to close this
