### ISSUE TITLE
Is there any way to declare a custom type for real numbers?

### ISSUE THREAD

**Issue by dmitriz** [facebook/flow#1800]
Is there any way to define a custom type accepting all real numbers but excluding the infinites and `NaN`? Something like this:

``` js
function square (x: finite) {
  return x * x
}
```

The reason is to catch possible arithmetic errors at the compile time that would lead to hard-to-find-bugs at the run-time due to JavaScript's famous unpredictable treatment of `NaN`.

**Comment by nikita-gazarov-hs** [comment]
Related: https://github.com/facebook/flow/issues/1406

**Comment by calebmer** [comment]
We’ve recently released support for opaque types! Check out the docs 😊

**Comment by vkurchatkin** [comment]
@calebmer I guest the point was that `finite * finite` should yield `finite`, although I'm not sure.
