### ISSUE TITLE
Is there any way to make flow stricter such that it'll be an error if you don't have types defined?

### ISSUE THREAD

**Issue by AriaFallah** [facebook/flow#1802]
At the very least I would like to have types for all the parameters of a function and a return type for any given function, but sometimes I forget, and flow doesn't throw errors for me if a function's params don't have types.

Is there any way to make flow stricter?

**Comment by jeffmo** [comment]
If you don't explicitly write types for a function's parameters or return types, flow will infer them (and it does not ever infer the `any` type for function parameters or return types). So even when you don't write type annotations, you can rest assured that your program is still typed and you will still get errors if you use the functions in a way that isn't safe.

This is actually a design goal of Flow: *You* decide when it's appropriate to write type annotations (usually either as documentation for complex functions or as a lynchpin for the type system to be more specific).

If, say for style reasons, you would rather write type annotations more often than Flow actually needs, I would recommend building an eslint rule for this.
