### ISSUE TITLE
[libs] ignores entries with non-.js extensions

### ISSUE THREAD

**Issue by skogsbaer** [facebook/flow#181]
I try to use the momentjs library with flow. I got a .d.ts file from https://github.com/borisyankov/DefinitelyTyped/blob/master/moment/moment.d.ts but couldn't convince flow to accept the moment module.

I debugged the problem and discovered that the module name 'moment' causes the problem.

I have created a strip-down version of the problem.

```
$ tree -a
.
├── .flowconfig
├── jssrc
│   └── Sample.js
└── lib
    └── moment.d.ts
```

```
$ cat .flowconfig
[ignore]

[include]
./jssrc/

[libs]
./lib/moment.d.ts

[options]
```

```
$ cat jssrc/Sample.js
/* @flow */

var moment = require('moment'); // REPLACE 'moment' with 'foobar' to get it working
```

```
$ cat lib/moment.d.ts
declare module moment { // replace moment with foobar to get it working
}
```

If I now run `flow`, I get

```
$ flow check

jssrc/Sample.js:3:14,30: moment.js
Required module not found
```

If I replace the two occurrences of moment with foobar, I get

```
$ flow check

Found 0 errors
```

**Comment by avikchaudhuri** [comment]
Very surprising. I think I saw a similar bug elsewhere. Will look into it, thanks for reporting!

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by bigunaleksej** [comment]
Any news?

**Comment by mroch** [comment]
This repros:

```
mkdir -p test
pushd test
printf "declare module foobar {\n  declare var foo: string;\n}\n" > lib.d.ts
printf "[libs]\nlib.d.ts\n" > .flowconfig
printf "// @flow\n\n((require('foobar').foo): number);\n" > index.js
flow check
# got a missing module error, rather than complaining that foo is a string, not a number
popd
```

The problem is that Flow only looks at file extensions `.js` and `.json`, not `.ts`, even if the entry in `[libs]` is an actual file.
