### ISSUE TITLE
Wrong behavior with EventTarget checking.

### ISSUE THREAD

**Issue by rmakarov94** [facebook/flow#1812]
I noticed strange behavior with checking event handler. Looks like flow(0.25 flow-bin) recognize e.tagtet as HTMLSelectElement only for first statement within if().

``` javascript
chooseFilter(e: Event) {
  if (e.target instanceof HTMLSelectElement) { 
    console.log(e.target);
    this.state.set('filter', e.target.value);
  }
}
```

`e.target.value property not found in e.target`

``` javascript
chooseFilter(e: Event) {
  if (e.target instanceof HTMLSelectElement) { 
        this.state.set('filter', e.target.value);
        console.log(e.target);
  }
}
```

`Everything is fine with Flow!`

**Comment by rmakarov94** [comment]
Maybe it works this way to avoid side effects affection, but it's not very intuitive.

**Comment by conartist6** [comment]
You are correct, this is by design. The error messaging on this could be better.

**Comment by rmakarov94** [comment]
```javascript
function updateHandler(event: Event<HTMLInputElement>) {
}
```
That's how I had to use, I guess
