### ISSUE TITLE
Guidance on using Flow and ESLint

### ISSUE THREAD

**Issue by bookercodes** [facebook/flow#1813]
I want to create a Flow declaration file for [Express](https://github.com/expressjs/express)

I created a file `declarations/express.js.flow`:

```
declare class Request {
  statusCode: number;
}
```

And referenced it from `.flowconfig`:

```
[libs]
declarations/express.js.flow
```

Now I can reference `Request` and Flow works:

![](http://i.imgur.com/6aVCpqf.png)

But ESLint complains that `Request` isn't found:

![](http://i.imgur.com/n9aSN3Q.png)

I'm using [`babel-plugin-transform-flow-strip-types`](babel-plugin-transform-flow-strip-types) with the [`babel-eslint`](https://github.com/babel/babel-eslint) parser.

This obviously isn't a problem with Flow -- Flow is working fine. It's something to do with ESLint. I'm writing here because I would love some guidance on using ESLint and Flow together. They're definitely not mutually exclusive. It would be great to see something in the docs.

**Comment by blaiprat** [comment]
Hi, have you tried using https://github.com/zertosh/eslint-plugin-flow-vars?

**Comment by alexbooker** [comment]
@blaiprat I hadn't heard of `eslint-plugin-flow-vars` before. Works great :+1: 

Another workaround is to [specify global via ESLint](http://eslint.org/docs/user-guide/configuring#specifying-globals):

```javascript
/*global Request*/
```

**Comment by ryyppy** [comment]
You won't be happy if you define global variables for `eslint` :-) .... `eslint-plugin-flow-vars` is definitely the way to go here!

**Comment by alexbooker** [comment]
Agreed :smile:     


As an aside, I just stumbled upon [**flow-guide**](https://github.com/runtastic/flow-guide) (via your profile actually, @ryyppy :smile:)

**Comment by ryyppy** [comment]
@alexbooker cool! hope it actually helps in one way or another 😄

**Comment by amilajack** [comment]
Is it possible to write a eslint plugin for flow where errors in flow are reported as eslint errors? This would make for an amazing workflow.

**Comment by amilajack** [comment]
^^ Turns out it is possible. [Here it is](https://github.com/amilajack/eslint-plugin-flowtype-errors):

![ESLint Flow Demo](https://github.com/amilajack/eslint-plugin-flowtype-errors/blob/master/flow-demo.gif?raw=true)

**Comment by SamChou19815** [comment]
Now documented here: https://flow.org/en/docs/tools/eslint/
