### ISSUE TITLE
return value of `Object.keys()` cannot be inferred

### ISSUE THREAD

**Issue by despairblue** [facebook/flow#1817]
``` js
/* @flow */
'use strict'

const obj = {
  bar: 'baz'
}

const keys = Object.keys(obj)
const values = Object.values(obj)

exports.foo = Object.keys(obj)

exports.fii = Object.values(obj)

exports.fuu = values

exports.fee = ['bar']

exports.faa = keys
```

``` sh
$ flow check
test.js:8
  8: const keys = Object.keys(obj)
                  ^^^^^^^^^^^^^^^^ array type. Missing annotation

test.js:11
 11: exports.foo = Object.keys(obj)
                   ^^^^^^^^^^^^^^^^ array type. Missing annotation
```

**Comment by mroch** [comment]
@samwgoldman: putting this on your radar. i think this happens because we don't know what `Object.keys` does until merge, but check for missing annotations before then.

**Comment by calebmer** [comment]
There are no errors in the latest version of Flow. If you still have a similar issue then please feel free to open a new issue 👍 

https://flow.org/try/#0MYewdgzgLgBCBGArGBeGBvAUDG8CGATgFwwDk+AXqZgL6aaiSwDWApgJ4SowDySrwKADo2nABQJEASgbhoMAG54ANgFdWXNH0QDhStRolIZmVgA8ADiAJQIQgGYgQ3bbpEcIR6fXNWbd+wBLQJd+QSF9dU9JE19rWwdVVW5IjR9LeIDWVm4AbXJCUgBddL8E+zw8blEITCA
