### ISSUE TITLE
Implement async iteration proposal (stage 3)

### ISSUE THREAD

**Issue by mroch** [facebook/flow#1824]
https://github.com/tc39/proposal-async-iteration

Stage 2, and Babel supports it as of 6.8.0.

**Comment by samwgoldman** [comment]
woah—cool

**Comment by zertosh** [comment]
Stage 3: https://github.com/tc39/proposals/commit/96f8d79dac33575e24f6ac3ec2082efe75d519ba

**Comment by samwgoldman** [comment]
Thanks for the update. Let's do it :)

**Comment by samwgoldman** [comment]
@zertosh let me know if you run into any issues with the implementation that just landed. I'm sure I messed up somewhere :)

**Comment by BenoitZugmeyer** [comment]
Really looking forward to use this!

I just tried it quickly, a few notes:
* `AsyncIterators` have [optional methods `return` and `throw`](https://tc39.github.io/proposal-async-iteration/#table-async-iterator-optional) (well, `Iterators` too)
* `AsyncIterators` are basically a superset of `Iterators`, in the sense that:
  * the `.next` method can return `Promise<IteratorResult>|IteratorResult`
  * `for await` can iterate on both `AsyncIterators` and `Iterators`
* `Symbol.asyncIterator` definition is missing

**Comment by zertosh** [comment]
Thanks @samwgoldman! Looks like this is going into 0.34.0, so I'll add the transform support in Nuclide so we can take it for a test drive :)
