### ISSUE TITLE
Cannot build flow 0.25 with node 6.1 on OS X 10.11.4

### ISSUE THREAD

**Issue by frogcjn** [facebook/flow#1828]
`npm install flow` will hang on `node lib/install.js`, because the lack of `flow-bin/vendor/flow`
after put the release version binary file on that location, everything is fine.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen with a reproduction on https://flow.org/try if you are still having issues!
