### ISSUE TITLE
Can't implement a type with optional function with class method

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#1832]
This works:

```js
class T {
  a(): void {
  }
}

type A = {
  a: () => void
}

const t: A = new T();
```

This doesn't:

```js
class T {
  a(): void {
  }
}

type A = {
  a?: () => void
}

const t: A = new T();
```

**Comment by vkurchatkin** [comment]
Another similar example:

```js
class A {
  a: string;
}

type X = {
  a: ?string
};

var x: X = new A;
```

**Comment by ryyppy** [comment]
Hm, the first failing example seems reasonable, I would also expect this to work...
for the last example, I think this works as intended, since it would be weird if you could change the return type of `a` from maybe `?string` to a literal type `string`,... or am I mistaken?

**Comment by vkurchatkin** [comment]
@ryyppy no, you are right, the second one actually makes sense: if you assign to x, then it will allow you to set `a` to `null`, which is incorrect. Probably the same logic applies to the first example as well, but it's deleting instead of setting to `null`. 

It gets confusing sometimes, but kind of makes sense, so I'm gonna close it. Let's hope immutability modifiers will make these kind of problems history some day.

**Comment by mroch** [comment]
Yeah, you guys are right. Interfaces will do what you want, though:

```
interface A {
  a?: () => void
}
```

but it's possible immutability modifiers will make the `interface` syntax unnecessary/just sugar in the future (cc @samwgoldman)
