### ISSUE TITLE
Tree View on Right Side

### ISSUE THREAD

**Issue by preschian** [facebook/flow#1834]
is there an option to show tree view on the right side?

**Comment by mroch** [comment]
which tree view are you referring to? :)

**Comment by JohnyDays** [comment]
I think this might be about nuclide. You want ctrl+<

**Comment by mejine** [comment]
tested and it is working like a charm .

**Comment by mroch** [comment]
@preschian please reopen if this didn't help

**Comment by preschian** [comment]
ups sorry, i mean tree view on nuclide
