### ISSUE TITLE
Add flag where an uncovered expression is an error.

### ISSUE THREAD

**Issue by Raynos** [facebook/flow#1836]
I suspect that if `flow coverage file.js` is <100 then there are untyped expressions that can cause nasty errors at runtime. 

I'd be great if there was a mode where those expressions became errors. For example:
- Accessing a non-existant field returns an `any` and is marked as untyped in `flow coverage`
- Importing a non-typed module returns an `any` and is marked as untyped in `flow coverage`
- Adding an event listener, aka `server.on('request', onRequest)` makes the parameters of the `onRequest` function declaration have type `any` and is marked as untyped in `flow coverage`
- If the arguments to a method definition in a class are not typed then they default to `any` and is marked as untyped in `flow coverage`

If these untyped expressions were type errors with a useful error message it will make it a lot easier to get a program to 100% flow type coverage.

**Comment by asolove** [comment]
A lot of this is now handled by configuring [flow linting](https://medium.com/flow-type/linting-in-flow-7709d7a7e969).

**Comment by SamChou19815** [comment]
We don't intend to build this. You can query the coverage result and fail based on some criteria on your own
