### ISSUE TITLE
?[Bug|Feature Request] Refinements from object property sentinel

### ISSUE THREAD

**Issue by JohnyDays** [facebook/flow#1838]
``` javascript
type First = {
  type: {
    name: "a"
  },
  first: () => any,
}

type Second = {
  type: {
    name: "b"
  },
  isSecond: true,
  second: () => any,
}

export const test = ( arg: First|Second ) => {
  if ( arg.type.name === "a" ) {
    arg.first()
  }
  else {
    arg.second()
    arg.isSecond
  }
}
```

Errors with: 

```
property `first` not found in object type
property `second` not found in object type
property `isSecond` not found in object type
```

Is this a bug or just not planned to be possible? I have a use case for it when typing an existing library (sequelize)

(I'm using flow compiled from master)

**Comment by mejine** [comment]
type First = {
  type: {
    name: "a"
  },
  first: () => any,
}

type Second = {
  type: {
    name: "b"
  },
  isSecond: true,
  second: () => any,
}

export const test = ( arg: First|Second ) => {
  if ( arg.type.name,,

**Comment by tryggvigy** [comment]
The problem is probably with this condition
```js
 if ( arg.type.name === "a" )
```
Is it to granular for flow to be sure that this codepath only has `arg: First` ?

**Comment by SamChou19815** [comment]
This is expected since sentinel refinement only goes one level deep.
