### ISSUE TITLE
TypedArray constructors missing

### ISSUE THREAD

**Issue by martine** [facebook/flow#184]
```
$ cat test.js 
var a = new Float32Array([1.0]);
$ flow check --all

.../test.js:1:26,30: array literal
This type is incompatible with
  .../lib/core.js:388:25,35: ArrayBuffer

Found 1 error
```

Flow seems to only have one ctor for TypedArray types:
https://github.com/facebook/flow/blob/master/lib/core.js#L388

Here's TypeScript's definitions of array constructors.  You can see `number[]` is allowed.
https://github.com/Microsoft/TypeScript/blob/master/src/lib/es6.d.ts#L3173

**Comment by samwgoldman** [comment]
This is working now and this issue can be closed.
