### ISSUE TITLE
Add yellow highlighting for `any`, `Object`, `Function` to coverage

### ISSUE THREAD

**Issue by ianobermiller** [facebook/flow#1840]
The `flow coverage` command is really useful for finding where you don't have any flow coverage, but doesn't help if something is explicitly typed as `any`, as happens during codemods or initial conversion. We could highlight any expressions that evaluate to the "barely typed" values of `any`, `Object`, or `Function` in yellow.

**Comment by DanielHeath** [comment]
I'd be interested to take this further, adding `--html` to render the code with all types overlaid.

**Comment by SamChou19815** [comment]
These types should be considered as uncovered now
