### ISSUE TITLE
always typecheck a certain file extension?

### ISSUE THREAD

**Issue by matthewmueller** [facebook/flow#1845]
is there any way to define a certain filetype in the CLI or `.flowconfig` to always check a certain file, regardless of if it has `// @flow` at the top?

It would be nice to add an file extension, say `.ft`, that we can ensure flowtype will always check.

**Comment by matthewmueller** [comment]
Just adding onto this, it'd be nice if you guys advocated an extension, these flavors of `.js` shouldn't be `.js`, since it's not really vanilla JS. Maybe `.jsx`, but currently that sort of implies that there is xml in the JS. 

It'd be nice to identify this flow's flavor of JS so syntax highlighters can start highlighting flow syntax.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen if you are still want this feature!
