### ISSUE TITLE
Arrow function in class definition

### ISSUE THREAD

**Issue by dmfilipenko** [facebook/flow#1846]
I've stuck with such problem. I have code:
```js
class Navigation extends React.Component {
  toggleAsideAttach = () => {}
  render() {}
}
```
And flow throw error
<img width="325" alt="screen shot 2016-05-25 at 18 02 32" src="https://cloud.githubusercontent.com/assets/1822520/15544890/05ed0bf4-22a3-11e6-950f-949ebf727caa.png">
Also, changing definition to this doesnt help
```js
class Navigation extends React.Component {
  toggleAsideAttach: () => void = () => {}
  render() {}
}
```

**Comment by popham** [comment]
You forgot a semicolon dude--I'm not gonna say where :). I think you'll have to assign `toggleAsideAttach` in the constructor.

**Comment by dmfilipenko** [comment]
@popham thanks, my bad:(
