### ISSUE TITLE
Should `stream.Duplex` stream be `typeof stream.Duplex | typeof stream.Writable | typeof stream.Readable`?

### ISSUE THREAD

**Issue by AKST** [facebook/flow#1850]
Since `stream.Duplex` implements the interface for both `stream.Writable` and `stream.Readable`, should it's type be something like this?

``` js
typeof stream.Duplex | typeof stream.Writable | typeof stream.Readable
```

Possibly something similar for `stream.Transform`?

**[[API docs here]](https://nodejs.org/api/stream.html#stream_api_for_stream_implementors)**

**Comment by jgrund** [comment]
Was wondering the same thing. Right now it only covers `stream$Readable`.

I wonder if we could extend Readable with Writable, or vice-versa and use that as the basis for Duplex etc...
