### ISSUE TITLE
Can't create a class within class methods

### ISSUE THREAD

**Issue by popham** [facebook/flow#1852]
Flow chokes on the following:

``` js
class C {
  static Fn(): Class<C> {
    return class D extends C {}
  }
  Gn(): Class<C> {
    return class E extends C {}
  }
}
```

The pattern is especially interesting when you start intersecting the `Class<C>`s with interfaces.

**Comment by Brianzchen** [comment]
Works in latest version 0.141.0
https://flow.org/try/#0MYGwhgzhAEDC0G8BQ1oQC5nQS2NAYgHYAUAlAFxzhQA8sAfIiqtAE4Cm6Arq4dKJBgARaOwAe6doQAmMeAgC+zJagDiJClUF1GyFm048+AqNACioiVNlxEK6EoVA
