### ISSUE TITLE
Constructor in a subclass accessing an inherited field outputs a "Missing annotation" error

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#186]
Running:

```js
/* @flow */

class C {
  x: number;
}

class D extends C {
  constructor() {
    this.x  = 1;
  }
}

module.exports = D;
```

Expected:

```
Found 0 errors
```

Actual:

```
/Users/thomasboyt/flowtest/D.js:9:10,10: field x constructor init
Missing annotation

Found 1 error
```

~~Oddly enough, if you remove the final line (`module.exports = D;`), you get the expected output.~~

Even stranger, if you set `x` to something different from a number, you get the correct type error, *along with* the incorrect "missing annotation" error:

```
/Users/thomasboyt/flowtest/D.js:9:10,10: field x constructor init
Missing annotation

/Users/thomasboyt/flowtest/D.js:9:15,22: string
This type is incompatible with
  /Users/thomasboyt/flowtest/D.js:4:6,11: number

Found 2 errors
```

**Comment by avikchaudhuri** [comment]
Thanks for reporting this!

**Comment by gcazaciuc** [comment]
Is there a workaround for this ? We've hit the same problem and we're pretty much stuck with Flow at the moment due to this. Thanks

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by samwgoldman** [comment]
This no longer reproduces. Thanks for reporting!
