### ISSUE TITLE
Issue with creating style node

### ISSUE THREAD

**Issue by zaiddag** [facebook/flow#1861]
with the line:
`var style = document.createElement('style')`
we get the error:
`call of method `createElement`:
Function cannot be called on any member of intersection type
intersection:`
though it seems that https://github.com/facebook/flow/blob/master/lib/dom.js#L376 declares style as a valid element type

**Comment by tryggvigy** [comment]
Works for me in version `0.25.0` which version are you using?

**Comment by avikchaudhuri** [comment]
@zaiddag Couldn't repro.

```
var style: HTMLStyleElement = document.createElement('style');
```

works for me with 0.26.0.

You might get the mentioned error if you use the value `style` in a way that is not allowed through the `HTMLStyleElement` type. In any case, please confirm and point to a repro?

**Comment by avikchaudhuri** [comment]
Closing, please re-open if necessary.

**Comment by zaiddag** [comment]
Looks like type inference causes the error?

`var style = document.createElement('style')` will give above error while
`var style:HTMLStyleElement = document.createElement('style')` won't give the error

**Comment by zaiddag** [comment]
@avikchaudhuri
