### ISSUE TITLE
Confusion Surrounding Asynchronous Functions, the Promise Type, and a Variable Called "Promise"

### ISSUE THREAD

**Issue by alexbooker** [facebook/flow#1865]
Consider this code:

![](http://i.imgur.com/qm18DYO.png)

I wanted to tell Flow that this **`async`** function should return a **`Promise<number>`**. 

I was confused when I realized I could return a **`Promise<string>`** (or **`any`**) without Flow complaining.

After some time I _finally_ deduced that Flow was interpreting **`Promise`** from the line _"**`import Promise from 'bluebird'`**"_ instead of using the **`Promise`** type :dizzy_face:. 

I wonder if there's anything that can be done to improve the usability here? 
 
Maybe the annotation **`Promise<number>`** should have caused an error because [bluebird](https://github.com/petkaantonov/bluebird) does not have any generic type parameters (or Flow annotations for that matter).

**Comment by ryyppy** [comment]
Did you also add a  `[libs]` file for the `bluebird` module? Otherwise I would imagine that `flow` will just annotate the module's exports as `any` and ignore the `<number>` completely? 😱  
What happens if you change `import Promise` to `import Promise as BBPromise`?

**Comment by alexbooker** [comment]
> Did you also add a [libs] file for the bluebird module? 

Nope.

> Also, what happens if you change import Promise to import BBPromise?

In my experience, the **`Promise`** type would work as expected.

----

For reference, [here is the file I was working on](https://github.com/alexbooker/communitycasts.co/blob/master/source/util/youtubeClient.js).

As you can see, I no longer import **`Promise`**. Flow works fine.

**Comment by avikchaudhuri** [comment]
Closing, OP seems happy.
