### ISSUE TITLE
flow error: expected array of arguments instead of Uint8Array

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#1866]
I believe Flow is incorrectly reporting the following error:

`call of method 'apply'. expected array of arguments instead of Uint8Array`

The code:

```
function decodeutf8(uint8 :Uint8Array) :string {
  const utf8String = String.fromCharCode.apply(null, uint8); // problematic line
  return decodeUTF8(utf8String);
}
```

The `uint8` parameter is a typed array, so it should satisfy the `expected array of arguments`. However, Flow's definition for `fromCharCode` doesn't support typed arrays:

https://github.com/facebook/flow/blob/master/lib/core.js#L266
`static fromCharCode(...codes: Array<number>): string;`

Any suggestions on how this should be handled?

**Comment by avikchaudhuri** [comment]
Hmm, it seems to be part of a specification that the argument to apply only needs to be "array-like": http://www.ecma-international.org/ecma-262/6.0/#sec-createlistfromarraylike

TIL.

I think the way to fix this would be to change how `apply` is handled in Flow to match the spec, and possibly make a few other changes to the type definition of `Array` and `Uint8Array` (etc.) to adjust if necessary.

Workaround for now would be to wrap the occurrence of `uint8` passed to `apply` as `(uint8: any)`.
