### ISSUE TITLE
Static analysis fails silently at module boundaries

### ISSUE THREAD

**Issue by freebroccolo** [facebook/flow#1868]
I am trying to create flow declarations for some libraries and have run into a problem using Flow (version `0.26.0`) for situations that involve multiple modules. Here is a simple example that demonstrates the problem:

*.flowconfig*:
```
[include]
src/**

[libs]
lib
```

*lib/index.js*:
```javascript
// @flow

declare module "m0" {
  declare type T0 = string;
  declare class C0 {}
}

import type { T0 } from "m0";
import { C0 } from "m0";

declare class C1 {
  p0: T0;
  p1: C0;
}
```

*src/index.js*:
```javascript
// @flow

declare var o0: C1;
const v0: number = o0.p0;
const v1: number = o0.p1;
```

Running `flow` from the terminal or within nuclide reports no errors and autocomplete shows no types for `o0.p0` or `o0.p1` although they do show up as an entries.

*result of `$ flow`*:
```
No errors!
```

*result of `$ flow autocomplete --json 4 24 < src/index.js | jq`*:
```json
{
  "result": [
    {
      "name": "p0",
      "type": "",
      "func_details": null,
      "path": "~/github/flow-problem/lib/index.js",
      "line": 12,
      "endline": 12,
      "start": 7,
      "end": 8
    },
    {
      "name": "p1",
      "type": "",
      "func_details": null,
      "path": "~/github/flow-problem/lib/index.js",
      "line": 13,
      "endline": 13,
      "start": 7,
      "end": 8
    }
  ]
}
```

However, if the type `T0` and class `C0` are declared globally, `flow` reports type errors as expected:

```
// @flow

// declare module "m0" {
declare type T0 = string;
declare class C0 {}
// }

// import type { T0 } from "m0";
// import { C0 } from "m0";

declare class C1 {
  p0: T0;
  p1: C0;
}
```

*result of `$ flow`*:
```
src/index.js:5
  5: const v0: number = o0.p0;
                        ^^^^^ string. This type is incompatible with
  5: const v0: number = o0.p0;
               ^^^^^^ number

src/index.js:6
  6: const v1: number = o0.p1;
                        ^^^^^ C0. This type is incompatible with
  6: const v1: number = o0.p1;
               ^^^^^^ number
```

*result of `$ flow autocomplete --json 4 24 < src/index.js | jq`*:
```json
{
  "result": [
    {
      "name": "p0",
      "type": "string",
      "func_details": null,
      "path": "~/github/flow-problem/lib/index.js",
      "line": 12,
      "endline": 12,
      "start": 7,
      "end": 8
    },
    {
      "name": "p1",
      "type": "C0",
      "func_details": null,
      "path": "~/github/flow-problem/lib/index.js",
      "line": 13,
      "endline": 13,
      "start": 7,
      "end": 8
    }
  ]
}
```

Is this a known issue? If so, I'm having a difficult time seeing how Flow can be used effectively with libraries where the interface depends on structures defined in other modules. If the types are primarily structural, perhaps it is possible to work around by duplicating all of the declarations locally, but for classes it seems especially problematic.

**Comment by ryyppy** [comment]
Not sure if I understood the problem correctly,... so you want to use type declarations outside of the `declare module` scope... currently, flow only allows that in the global scope and this is the reason why we currently declare publicly available types in some kind of "namespace".

E.g. in the [highlight.js](flow-typed/definitions/npm/highlight.js_v8.x.x/flow_>=v0.13.x/highlight.js_v8.x.x.js) libdef, you can see that we put the type definitions in the namespace `HighlightJs$`.

Also, you may have noticed that flow does the same for `React$Component`... it's just a globally defined type entity.

If you wanna get more insights in how to write proper libdef declarations, check out the current [flow/lib](https://github.com/facebook/flow/tree/master/lib) or the uprising [flow-typed](https://github.com/flowtype/flow-typed/tree/master/definitions/npm) definitions :-)

**Comment by freebroccolo** [comment]
@ryyppy thanks for the suggestions, I will take a closer look at those links.

I think there are two issues here:

1. Flow doesn't currently support any notion of dependency between libs (where "interface" is whatever flow collects from a single `.flowconfig` file).

2. Flow just fails silently doing analysis across module boundaries.

The first one I already understood and although I hope it is eventually addressed, I think it can be worked around. The second item seems like a bigger problem to me.

For one thing, I do not think `flow` should simply continue checking without reporting any warnings or errors in this case. In fact, if it had complained, I would have figured out what was going wrong a lot sooner.

Beyond that, I guess what I don't understand is how declaring classes globally in this namespaced fashion is supposed to work in practice. Say I have a module "foo" and it defines a class "C". Now, if I understand correctly, you are suggesting I provide declaration for this like like so:

*libs/foo.js*:
```javascript
declare class Foo$C {
  // declaration of C from Foo
  …
}
```

How does that interact with some implementation where I need to import that class from "foo"? Am I supposed to do something like this?

*src/index.js*:
```javascript
import { Foo as Foo$C } from "foo";

// some code that uses Foo$C
…
```

Will flow understand that?

As for what I am trying to use this for, I have created flow interfaces for the Atom API [here](https://github.com/flow-atom). As I started to split up the packages, I thought things were working but once I started using [flow-atom-api](https://github.com/flow-atom/flow-atom-api) for something real, I noticed that everything outside of the main package was being ignored once it had been split out into a separate module.

**Comment by freebroccolo** [comment]
After experimenting with several different approaches, it looks like I can get pretty close to the behavior I was after in the original example doing something like the following:

```javascript
declare type M0$T0 = string;
declare class M0$C0 {
  …
}

declare module "m0" {
  declare type T0 = M0$T0;
  declare class C0 extends M0$C0 {}
}

declare class C1 {
  p0: M0$T0;
  p1: M0$C0;
}
```

**Comment by ryyppy** [comment]
The last approach is exactly how we do it at flow-typed! 👍
Just in different files of course... it's working, although I would really love to see a way of handling the module dependencies like TypeScript does in the future...
