### ISSUE TITLE
Mixing map annotations with other properties

### ISSUE THREAD

**Issue by crm416** [facebook/flow#187]
I may not have a great understanding of how the [objects-as-maps](http://flowtype.org/docs/objects.html#objects-as-maps) type system should work, but it's strange to me that Flow lets you add map-violating properties to an object literal at time of creation, only to throw an error when you attempt to read from it.

For example:
```js
var numToString: { [key:number]: string} = {
  foo: 'bar' // no error here, even though the key is not a number
};
numToString.foo; // throws an error because the key is a string
numToString['foo']; // throws an error because the key is a string
```

You get the same behavior if you include the property in the type annotation:

```js
var numToString: { foo: string; [key:number]: string} = {
  foo: 'bar' // no error here
};
numToString.foo; // throws an error
numToString['foo']; // throws an error
```

With the current behavior, the only reason I can think of to allow mixing map annotations and specific-property annotations would be to mark some keys as required, and that would only work (as-is) if you're using a map from strings to something else.

Intuitively, my guess is that my first example should throw an error at the time of creation, but that my second should work throughout (i.e., adding specific-property annotations is way of white-list properties that don't adhere to the overall map type).

**Comment by samwgoldman** [comment]
My understanding is that it only make sense for keys to be `string`, so the `{ [key: number]: string }` type is not really worth supporting. In fact, I'd argue that providing a syntax to specify key types isn't very sensible.

**Comment by samwgoldman** [comment]
I ran into this as well, and after a bit of digging, it looks like the cause is in [the (ObjT, GetT) flow](https://github.com/facebook/flow/blob/e57870ec52576c2d0cf69f65ce1d15cc29cc4656/src/typing/flow_js.ml#L2737), which always compares the property with the indexer, without considering that the property could be in the prop map instead.

**Comment by samwgoldman** [comment]
This no longer reproduces.
