### ISSUE TITLE
Analysis does not match fs.readFileSync declaration

### ISSUE THREAD

**Issue by bryannaegele** [facebook/flow#1870]
https://github.com/facebook/flow/blob/master/lib/node.js#L634 shows fs.readFileSync correctly returning type string when an encoding is passed.

Given this declaration:
```js
declare module 'html-frontmatter' {
  declare var exports: (input: string) => {};
}
```

and this implementation:
```js
import fs from 'fs'
import path from 'path'
import frontMatter from 'front-matter'
import objectAssign from 'object-assign'
import htmlFrontMatter from 'html-frontmatter'

let data
...
const html = fs.readFileSync(pagePath, 'utf-8')
data = objectAssign({}, htmlFrontMatter(html), { body: html })
```

Flow check raises this error
```
22:     data = objectAssign({}, htmlFrontMatter(html), { body: html })
                                 ^^^^^^^^^^^^^^^^^^^^^ function call
 22:     data = objectAssign({}, htmlFrontMatter(html), { body: html })
                                                 ^^^^ Buffer. This type is incompatible with
  2:   declare var exports: (input: string) => {};
                                    ^^^^^^ string. See lib: interfaces/html-frontmatter.js:2
```

and running flow suggest for the file resolves Buffer, as well.
```
-    const html = fs.readFileSync(pagePath, 'utf-8')
+    const html: Buffer = fs.readFileSync(pagePath, 'utf-8')
```

Are overloads working correctly?

Node 6.2.0
Flow 0.26

**Comment by mroch** [comment]
Overloads are tried in order and the first one to match wins. Since extra params are also allowed, that first one will match and the second one won't. :/

I think reversing the order of the overloads in lib/node.js will help. I can try it when I get into the office.

**Comment by bryannaegele** [comment]
Thanks for the insight and tackling that @mroch.

**Comment by bryannaegele** [comment]
@mroch I'm still seeing this issue with v0.27.
 
I also tried the non-shorthand object options to readFileSync `fs.readFileSync(pagePath, { encoding: 'utf-8' })` but saw the same result.

**Comment by pitops** [comment]
hey how was this resolved? its 2020 and have the same issue.
