### ISSUE TITLE
Impossible to declare custom iterable objects

### ISSUE THREAD

**Issue by StyMaar** [facebook/flow#1871]
When I try to define an iterable object, flow complains twice :

When I try to delcare my object as iterable:

```
*[Symbol.iterator] () {
         ^ computed property keys not supported
```

And when I try to spread over this object

```
[...myObject]
    ^^^^^^^^ MyClass. This type is incompatible with spread operand
```

**Comment by shouze** [comment]
Yes, I have the same issue and found no solution ATM.

**Comment by vkurchatkin** [comment]
Closing in favour of https://github.com/facebook/flow/issues/1163
