### ISSUE TITLE
Inconsistent type checking for object properties

### ISSUE THREAD

**Issue by StyMaar** [facebook/flow#1879]
Let's consider the following scenario:

``` JavaScript
let defaultConfig = {
    property_1: "foo",
    property_2: true,
}

type ConfType = typeof defaultConf;
```

Depending on how I try to access to the properties of a `ConfType` object, the type checker will catch errors, or won't.

For instance, the following will type check: 

``` JavaScript
function doSomething(conf:ConfType):void{
    let shouldIDoSomething = conf.property2; // notice the typo
    if(shouldIDoSomething){

    }
}
```

but the following will not :

``` JavaScript
function doSomething(conf:ConfType):void{
    if(conf.property2){ // notice the typo

    }
}
```

Is there any reason the 2nd scenario is not type-checked ? Or is it a bug ?

**Comment by StyMaar** [comment]
ping

**Comment by Pauan** [comment]
I found something similar which might be related:

https://flowtype.org/try/#0G4QwTgBAHhC8EG8IDMD2qBcECMEC+A3AFBED0pAlshABRQB0ARuAJSJ4kPNgFA

```
var x = { foo: 1 };

//if (x.bar) {}

x.bar;
```

It correctly displays an error when trying to access the non-existent property `bar`.

Now uncomment the `if`. Notice that it no longer displays an error, even though the property access is outside of the `if`

**Comment by calebmer** [comment]
We allow the second scenario so that you can check for the existence of a property. We may be able to add a warning for this, but we don’t want to an error 😊
