### ISSUE TITLE
Slower in nested directory

### ISSUE THREAD

**Issue by Brakkar** [facebook/flow#1881]
Hi,
I try flow on a very simple nodejs/express install with just boilerplate startup code in app.js, and some test conde in projectroot/dec/test.js .
I also have some modules in node_modules.

I notice a couple of things:

1) When I run flow on app.js, it's must faster than when I run in on dec/test.js. Is there a reason for this ? 2) Also each time flow seems to "start a new flow server", I'm not sure it is normal.

Please advise.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen if you are still having issues!
