### ISSUE TITLE
how to disallow extra fields with `any` type in object type

### ISSUE THREAD

**Issue by sakari** [facebook/flow#1883]
This passes the typechecker

```
// @flow
type Arg 
  = { foo?: string, [key: string]: void } 

declare var someExternal : any;

function b(p: (a: Arg) => void) {
    p({zzz: someExternal})
}
```

is there any way to disallow the `zzz` field from the call of `p` when the value comes from some untyped source and has `any` type?

**Comment by sakari** [comment]
I can use `$Shape<Arg>` but that allows omitting any of the fields which is inconvenient if there would be any really required fields

**Comment by calebmer** [comment]
You can now use exact object types.

https://flow.org/try/#0C4TwDgpgBAggTgcygKClAvFA3gHygMwHtCB+ALigGdg4BLAOwQBoocBfFZAEwgGMAbAIZxoAN2FVCAWwgBRAB7AIceoP5QKg+iADcyZPgCu9XsFqF6UAEYAKMBRuCK8BAEoMAPiijCtLu6xUNCgwGywAL0iKSmk5RWVVfjZXZDZkIA
