### ISSUE TITLE
.flowconfig file too complex

### ISSUE THREAD

**Issue by xaviervia** [facebook/flow#1887]
Hi,

I love the project, but after trying to set it up in several different applications I'm finding out the `.flowconfig` file to be pretty complex to use. I'm trying to pitch adoption for adopting flowtype in my team and I can see how this is going to turn into a persistent pain point that will make adoption more unlikely. The problem are the OCaml regular expressions.

Given that I love the tool I'm willing to go through the process of learning how to do that configuration, but I find somewhat surprising that a tool specifically aimed at JavaScript developers doesn't provide a more familiar interface for configuration, such as glob patterns or JS regular expressions. If this is not viable I would suggest adding a complete real life example to the documentation–the way I managed to fix mine was by reading the [`.flowconfig` file from the React Native repository](https://github.com/facebook/react-native/blob/master/.flowconfig).

Thanks!

**Comment by mroch** [comment]
agreed, i'm hoping to switch to PCRE/JSCRE (https://github.com/facebook/flow/issues/564). i think the best time to do it would be while changing the entire .flowconfig format to JSON or some other format (https://github.com/facebook/flow/issues/153), otherwise we won't be able to tell which format is being used.

**Comment by xaviervia** [comment]
Thanks for your reply! Good to see that this is on the radar already.

Do you think it would be possible to add the real life example to the documentation for the time being? I fully understand that changing the configuration file format will imply non trivial effort, I think what's more valuable to me is to have some way of doing these configurations easily and without having to dig into the OCaml regular expressions documentation. I think the more common issues and gotchas (one undocumented issue I got for example is a npm linked dependency being processed even when the node_modules folder was being ignored) could be listed in there and that would be a big help 😃

**Comment by calebmer** [comment]
Improving the format of `.flowconfig` is on our radar. Thanks for opening this issue 👍
