### ISSUE TITLE
Generic interface parameters cannot be used in extends clause to extend from them

### ISSUE THREAD

**Issue by mbergal** [facebook/flow#1888]
I am not sure it if this is a bug or a feature.  

```
/* @flow */

// extends plain object with mongoose document properties

interface MongooseDocument<T> extends T  {                 
                            // ^ extends `T`. Could not resolve name
    toObject(): T;
}

type Account = {
    name: string,
    domains: Array<string>,
}

var a : ?MongooseDocument<Account> = null;
```
If this is a feature, what would be a supported way to handle above. 

Thank you.

**Comment by ajhyndman** [comment]
@mbergal Did you find a nice alternative to this pattern that satisfied the use-case?  I want to be able to type check a factory function that copies a template object passed as a parameter.

**Comment by ncoder** [comment]
I was also looking to do this just now.
