### ISSUE TITLE
Tighten the type definition for the `space` param to `JSON.stringify()`

### ISSUE THREAD

**Issue by bolinfest** [facebook/flow#189]
Currently, `JSON.stringify()` is declared as:

```
declare class JSON {
  static stringify(
      value: any,
      replacer?: ?((key: string, value: any) => any) | Array<any>,
      space?: any
  ): string;
}
```

but I believe the final parameter should be declared as `space?: number | string`.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
