### ISSUE TITLE
Class<T> for subclass of T

### ISSUE THREAD

**Issue by dimonomid** [facebook/flow#1893]
Given that code:
```javascript
class Foo { }
class Bar extends Foo { }
let c: Class<Foo> = Bar;
```
I'm getting the following error:
```
myfile.js:14
 14: let c: Class<Foo> = Bar;
                  ^^^ Foo. This type is incompatible with
 14: let c: Class<Foo> = Bar;
                         ^^^ Bar
```
So, how can I express that variable might represent any class that extends the given one? (kind of analogue of Java's `? extends T`). I can't find anything about it in the documentation http://flowtype.org/docs/classes.html

Thanks.

**Comment by popham** [comment]
I've got an incomplete PR related to this (PR #1847).  The current limitation is an artifact of how derived classes do not require class constructor subtyping.  You can't impose your sought constraint.

In the following case, a slight generalization of your use case would cause problems:

```js
class A {
  constructor(n: number) {}
}
class B extends A {
  constructor(s: string) {} //OK: Not a subtype of `A`'s ctor, but this should be allowed
}
let X: Class<A> = B; // Bad stuff happens if this allowed, such as...
let x1 = new X(1); // Operating from the annotation, this yields a false positive
let x2 = new X("two"); // Operating from the annotation, this yields a false negative
```

I'm waiting for some feedback on a stronger `Class<.>` annotation that would impose constructor subtyping, but I'm not sure if this use case will be supported somehow in the near future.

**Comment by popham** [comment]
Try `let c: Class<$Subtype<Foo>> = Bar;` for now....

**Comment by vesln** [comment]
@popham thanks, this worked just fine for me

**Comment by avikchaudhuri** [comment]
This was fixed a few releases back.
