### ISSUE TITLE
Fail to typecheck a simple program

### ISSUE THREAD

**Issue by efurmantt** [facebook/flow#1900]
Gist is [here](https://gist.github.com/efurmantt/47b936e88b6cba73b934c0e2d0c51167).

The package.json is from the [getting started](http://flowtype.org/docs/getting-started.html#_) page.

The file looks like this:

``` js
// @flow

function f() {
    return {}
}

f().hello();
```

I'd expect flow to correctly infer the types and report this simple type error.

**Comment by calebmer** [comment]
Objects without properties are unsealed to allow you to assign things to it. Try adding a property:

https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqJABQCUoA3oqDaAE4Cm2qdhFAHgFwAsATAL6JBKMgDoAFg2hwyAbkRA
