### ISSUE TITLE
Adding an `export` to libs silently breaks type-checking

### ISSUE THREAD

**Issue by nicks** [facebook/flow#1905]
Create a libs file like this:

```
// @flow
declare module 'client' {
  declare class Client extends events$EventEmitter {
  }
}
export type ServiceRequestType = {}
```

And create a test.js file like this:

```
'use strict' // @flow
import type {Client} from 'client'
function f(client: Client) {
  client.foo()
}
```

Expected behavior: Flow should warn that `export` isn't allowed in a `[libs]` file. AND it should warn that `foo` is not a property of `client1.

Actual behavior: No errors found

Note: If I remove the `export type ServiceRequestType = {}` line, Flow successfully reports the 'foo' error

**Comment by calebmer** [comment]
This is intentional. If you have a global libdef it should not have top level exports.
