### ISSUE TITLE
Object construction via spread silently breaks typechecking in some cases

### ISSUE THREAD

**Issue by janv** [facebook/flow#1907]
This is the simplest example I could come up with:

``` js
/* @flow */
var o:{x:string}
o = {...window.something, x:1}
```

This typechecks.

The important part being that `window.something` is an expression that flow can't analyze. If you replace it with a known expression, Flow correctly indicates an error.

I see two problems with this:
1. The actual bug. I'm not an expert in the Ecmascript spec, but afaik, objects assembled this way are assembled from left to right. Even if `window.something` contains an `x`, that shouldn't matter, as the following `x:1` expression would overwrite whatever value that has.
2. The way Flow deals with situations like this. Instead of warning me about an expression it can't analyze, it just silently stops checking. I've encountered this multiple times. I would really like to get Flow into a mode where any unknown expression that is
   - not an untyped require/import of a 3rd party library
   - not an explicitly `any` typed expression
   
   raises an error or a warning. As it is, what's now called _strict mode_ isn't very strict at all.

**Comment by janv** [comment]
Related: #298 (implicit any)

**Comment by thejameskyle** [comment]
Slightly simpler case:

```
declare var a: any;
var o:{x:string}
o = {...a, x:1}
```

Since `window` is typed `any` right now.
