### ISSUE TITLE
es6/7 class parsing failure - property declarations without semicolons - [bounty][test repo available]

### ISSUE THREAD

**Issue by rosskevin** [facebook/flow#1908]
version: 0.26.0

[![bountrsource](https://api.bountysource.com/badge/issue?issue_id=34989221)](https://www.bountysource.com/issues/34989221-es6-7-class-parsing-failure-property-declarations-without-semicolons-test-repo-available)

## Bug description
This shows an ES2015/ES6/ES7 parsing bug - it will fail if there isn't a semicolon or static method after property declarations  and before the first member method.

I first found in the test case that a constructor **without** a static method above it causes linting to fail on the first method with `^^^^^^^^^^^ Unexpected identifier`.  After suggestion, I tried adding a semicolon which proves the parsing error.

### flowconfig
Same results with and without the following:

```
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
``` 

## Test cases
https://github.com/rosskevin/react-flow-classes 

## Works (static method above)

```javascript
// @flow
import React from 'react'

type DefaultProps = { x: 1 }
type Props = { x: number }
type State = { y: number }

class Foo extends React.Component {
  props:Props
  state:State
  static defaultProps:DefaultProps

  static bar ():void {}

  constructor (props) {
    super(props)
  }

  render () {
    return <div>Hello World</div>
  }
}
```

## Fails (no static method above)

```javascript
// @flow
import React from 'react'

type DefaultProps = { x: 1 }
type Props = { x: number }
type State = { y: number }

class Foo extends React.Component {
  props:Props
  state:State
  static defaultProps:DefaultProps

  // fails without this static method above constructor
  //static bar ():void {}

  constructor (props) {
    super(props)
  }

  render () {
    return <div>Hello World</div>
  }
}
```

## Works (a single semicolon)

```javascript
// @flow
import React from 'react'

type DefaultProps = { x: 1 }
type Props = { x: number }
type State = { y: number }

class Foo extends React.Component {
  props:Props
  state:State
  static defaultProps:DefaultProps;

  // fails without this static method or semicolon above first constructor/member method
  //static bar ():void {}

  constructor (props) {
    super(props)
  }

  render () {
    return <div>Hello World</div>
  }
}
```

I proved the same in the sample repo with parameterized classes.  May be related to #1171 
cc @STRML

## Expectation

All current failing classes in the test repo should succeed.  I should not need to use any semicolons, and I don't need static methods above my constructor or member method.

**Comment by rosskevin** [comment]
I can't help but notice the absence of the problem render method in the flow tests:
https://github.com/facebook/flow/blob/master/tests/new_react/classes.js

**Comment by STRML** [comment]
I think there may still be some odd parsing rules with semicolons, try
that?

**Comment by rosskevin** [comment]
Indeed a single semicolon and it works (repo updated):
https://github.com/rosskevin/react-flow-classes/commit/3c56fd9b7efe4bbcf4ca434e57af0b8c9b5218b7

**Comment by mroch** [comment]
fix incoming

**Comment by mroch** [comment]
@rosskevin thanks for offering the bounty, but I can't accept it :) it's generous and a cool idea, so maybe move it to your next favorite bug instead!

**Comment by rosskevin** [comment]
Thanks for the quick fix!  Will definitely move it to the next one.

**Comment by rosskevin** [comment]
@mroch - please reopen, my sample cases still fail with 0.27.0.

```bash
src/es6/Fails.js:16
 16:   constructor (props) {
       ^^^^^^^^^^^ Unexpected identifier

src/es6/FooFails.js:14
 14:   constructor (props) {
       ^^^^^^^^^^^ Unexpected identifier

src/es6/ParameterizedFails.js:16
 16:   constructor (props) {
       ^^^^^^^^^^^ Unexpected identifier
```

**Comment by mroch** [comment]
@rosskevin this didn't make it into the 0.27 branch. should be fixed in master, though.

**Comment by rosskevin** [comment]
ah, thank you.
