### ISSUE TITLE
Question: can you annotate classes that are not defined with the ES6 class keyword

### ISSUE THREAD

**Issue by klyngbaek** [facebook/flow#1909]
I have a lot of legacy ES5 code that does not use the class keyword to define "classes". I would like to annotate and do type checking with Flow. Is that possible?

**Comment by popham** [comment]
Yup.  Check out the [constructor_annots tests](https://github.com/facebook/flow/tree/master/tests/constructor_annots).  You might prefer to [declare them](https://flowtype.org/docs/declarations.html) if you want to leave the legacy code unaltered (or for some other reason).

**Comment by klyngbaek** [comment]
Thanks!
