### ISSUE TITLE
How to validate jsx without React.Component?

### ISSUE THREAD

**Issue by zerkalica** [facebook/flow#1911]
JSX is not only react part, for example [preact](https://preactjs.com/) or [deku](http://anthonyshort.me/deku/). How to teach flow read Props interface from raw class with custom realization state and props, not extended from React.Component?
Need flexible and universal solution for this.

For example:

``` js
// @flow

type Props = {
    a: string;
}

type State = {
    b: string;
}

export class W1 {
    // Only for flowtype:
    props: $FlowJSXHelper<Props>;

    customRender(props: Props & State) {
        return (
            <div>
                {this.props.a}
                {this.props.b}
            </div>
        )
    }
}

// or for objects
export default {

   render(props: Props & State) {...}
}: CustomWidget & $FlowJSXHelper<Props>
```

**Comment by jgrund** [comment]
@zerkalica Have you seen: https://github.com/facebook/flow/pull/2624

**Comment by asolove** [comment]
After #2624, Flow correctly interprets the `@jsx` pragma and turns JSX expressions into calls to the named function. So as long as that function is imported/defined in your module, JSX will type-check fine. I can confirm I've used Flow with Preact and it's default `h` function and this works.
