### ISSUE TITLE
declare module trigger coverage warning

### ISSUE THREAD

**Issue by pgherveou** [facebook/flow#1918]
Hey there. Thanks for this awseome project I am getting addicted to type checking my js files

I have a small issue on coverage warning when declaring modules. can you let me know how to work around it.

I created a simple declaration files in my project  under `interfaces/foo.js`
where I typed

```js
class Foo {}

declare module 'foo' {
  declare var exports: typeof Foo;
}
```

this trigger some warning inside atom nuclide
and I get the following warning when running coverage on this file

```
1:0,1:12: [class: Foo] (ClassT)
3:0,6:0: any (AnyT)
4:2,4:34: [class: Foo] (ClassT)
class Foo {}

declare module 'foo' {
  declare var exports: typeof Foo;
}

Covered: 66.67% (2 of 3 expressions)
```

**Comment by avikchaudhuri** [comment]
Merging with #1962
