### ISSUE TITLE
Bounded polymorphism doesn't work for unwrapped parameters

### ISSUE THREAD

**Issue by pseudonom** [facebook/flow#1920]
```
flow version
Flow, a static type checker for JavaScript, version 0.26.0
```

``` js
/* @flow */

type TypeWrapper<A> = A
class ClassWrapper<A> {
}

const xs: Array<{x: number}> = [{x: 1}]
const y: TypeWrapper<{y: string}> = {y: 'bar'}
const wrappedY: ClassWrapper<{y: string}> = new ClassWrapper(y)

const where = function<U, T: U>(list: Array<T>, properties: TypeWrapper<U>) {
}
const whereWrapped = function<U, T: U>(list: Array<T>, properties: ClassWrapper<U>) {
}

where(xs, y)
whereWrapped(xs, wrappedY)
```

```
  index.js:14
  14: whereWrapped(xs, wrappedY)
  ^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
  8: const wrappedY: Wrap<{y: string}> = new ClassWrapper(y)
  ^^^^^^^^^^^ property `y`. Property not found in
  6: const xs: Array<{x: number}> = [{x: 1}]
  ^^^^^^^^^^^ object type


  Found 1 error
```

Why is there no corresponding error for `where`?

**Comment by kastermester** [comment]
This happens as your type parameter is invariant. See https://flowtype.org/docs/classes.html#polymorphism-and-type-parameter-variance

To solve this, mark it as covariant (using the `+` specifier):

```
/* @flow */

type TypeWrapper<A> = A
class ClassWrapper<+A> {
}

const xs: Array<{x: number}> = [{x: 1}]
const y: TypeWrapper<{y: string}> = {y: 'bar'}
const wrappedY: ClassWrapper<{y: string}> = new ClassWrapper(y)

const where = function<U, T: U>(list: Array<T>, properties: TypeWrapper<U>) {
}
const whereWrapped = function<U, T: U>(list: Array<T>, properties: ClassWrapper<U>) {
}

where(xs, y)
whereWrapped(xs, wrappedY)
```

Note though that this is only useful when the type is actually covariant.

**Comment by pseudonom** [comment]
I don't think that's right? Marking `ClassWrapper` as covariant causes the type error to disappear. But I want the type error! It seems to me that *both* `where` and `whereWrapped` should produce an error, not neither.

**Comment by kastermester** [comment]
Oh I get what you mean now, my bad, I misread the issue.

**Comment by gcanti** [comment]
@pseudonom with flow v0.32.0 I get an error for both

**Comment by calebmer** [comment]
It looks like this is fixed in the latest version of Flow 👍 

https://flow.org/try/#0FAFwngDgpgBAKpKB1ATgQwtFAeAggPhgF4ZdgBjAGzQGcaYBhau1DLPQgb2AF9gKA9gDsaIGAA8aALlIp0YbJ3EyhAVwC2AIygoehEgG0lMgIw8AuoJFiwMhNFaYdi2zFEoAlkIDme4jE5XAHJNNBQgvnJhURgAd3QnABMATRkmWhpHdkCZdy9ffRghKFjGZkyErAAKMABKfijrOIALHVgSADNVIXIQD2FsAFUAGngZQfwqyg9RGVw5NAU4fFGIFAEsPqhpeEQs5wnagN4rGNjWlGRKqET-Lp6+gZGxmAmpmZA5haWVmDWNnRbHbpFjXHCHY58YDnNpVSSjOrQi5XNg3OE0UbxVEpepAA
