### ISSUE TITLE
Using Flow types for generative testing

### ISSUE THREAD

**Issue by jefffriesen** [facebook/flow#1921]
(I don't know if this is a question that would be better for IRC, a feature request or a request for documentation... pardon in advance.)

The more I use Flow the more I get out of it. It seems like it can go a lot further though. Clojure has had generative testing with [test.check](https://clojure.github.io/test.check/intro.html) for a long time (borrowed from Haskell) where the tests will automatically generate variations of inputs and see where the function breaks. It even narrows down the inputs into the simplest breaking case. 

Clojure folks just released [clojure.spec](https://clojure.org/about/spec) that lets you specify type annotations. Clojure's version goes deep and has lots of implications, but one thing they get is generative testing for free once the specs are done.

Are people doing this with Flow? If so it would be fantastic to put documentation on the site to point to examples and libraries that can do this. I know of mocha-check but don't know of any way to leverage Flow.

If people aren't doing this, are there technical limitations or difficulties to do it? Could this be built into Flow or add features to Flow that could enable this by other libraries?

Flow's value proposition is already good, but being able to get generative testing out of it could be amazing.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

If you want this we’d love to see it built in the ecosystem 😊
