### ISSUE TITLE
`.flow` declarations disable type checking?

### ISSUE THREAD

**Issue by pseudonom** [facebook/flow#1928]
See https://github.com/pseudonom/flow-scratch.

This project has an obvious type error in `index.js`. If I remove the `foo.js.flow` file, `flow` spots the type error. However, if I give a truthful signature to `a` in `foo.js.flow`, the type error no longer surfaces.

Flow 0.26.0

**Comment by msiebert** [comment]
I just ran into the same issue! It also appears that adding the `js.flow` file makes it so anything can be anything can be imported from the module.

```javascript
import {somethingThatClearlyDoesntExist} from './Option'
```

Seems to work just fine even though both `Option.js` and `Option.js.flow` are completely empty.

**Comment by shinout** [comment]
I've experienced the same problem and finally found that we must put

```js
// @flow
```
at .js.flow.

Current documentation tells us to write this.

**Comment by msiebert** [comment]
Ah, yes, I missed that one line while reading through the docs... oops. Thanks so much for your help, @shinout!

**Comment by thejameskyle** [comment]
Assuming this is resolved
