### ISSUE TITLE
Disjoint Union tags has to be located at top level of an object

### ISSUE THREAD

**Issue by sverrejoh** [facebook/flow#1931]
The tags in a Disjoint Union has to be located at the top level of the object, and can not be nested in another object. Meaning that the following code will not work:

```
/* @flow */

type FooStyle = {
    style: {
        width: number,
    },
    data: {
        type: "foo"
    }
}

type BarStyle = {
    style: {
        height: number,
    },
    data: {
        type: "bar"
    }
}

type ElementStyle = FooStyle | BarStyle;

function process(ele: ElementStyle) {
    if (ele.data.type === "bar") {
        // This gives a flow error as height is not found in the object.
        console.log(ele.style.height);
    }
}
```

Is there any reason for this? I'm working with a library that limits arbitrary properties to a nested object, so I can't add the tag at top level, and I optimistically thought this would work.

**Comment by tungv** [comment]
this is still broken:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCyAhjPgLxgDeqAkNgE5xQCWpAXFamNzwOa4A7ACa56HAOQFxXHgF8ANDO7YiA9AH0ERZgGd0HAQFcAtgCNRqWagw58AMVzGS5TnUYt2nHt7D9hoiTtpbwUZLV19MCMzUUUrVChDAQBjdGY4AV9cdAB1bT0ACmYBbENI4lIwAB8wBydSAEoDE3N6LzB6bMN6TOLS9AA6BiZWXAG-ETayabBJYLAaAH4wPrKh1Q1wvSUwDlXBrfQAbksgA

**Comment by SamChou19815** [comment]
This is expected behavior as a limitation of refinements on disjoint union.
