### ISSUE TITLE
children in a stateless component

### ISSUE THREAD

**Issue by salzhrani** [facebook/flow#1934]
It seems that the `children` special case is not handled in stateless functional components. flow looks for `children` in the passed props.

**Comment by jedwards1211** [comment]
@salzhrani I don't think it's just stateless functional components, I'm seeing this bug for normal `React.Component`s too.

**Comment by jedwards1211** [comment]
For now this is a workaround:
```js
<div children={<span>flow bug</span>}>
  <span>This is the actual children which overrides the children prop above</span>
</div>
```

**Comment by thejameskyle** [comment]
Moving into #1964 since that has more detail.
