### ISSUE TITLE
Class information lost after matching interface

### ISSUE THREAD

**Issue by jgrund** [facebook/flow#1936]
Consider the following code (flow 0.27):

```
// @flow

interface Fooable {
  foo(): string;
}

class AFoo {
  foo() { return 'foo from A' };
}

const fn = (a:Fooable):Fooable => a;

const result = fn(new AFoo());
(result:AFoo);
```

Running this outputs:

```
Library type error:
inconsistent use of library definitions
 14: (result:AFoo);
      ^^^^^^ Fooable. This type is incompatible with
 14: (result:AFoo);
             ^^^^ AFoo

Found 1 error
```

Given that I am using `Fooable` to satisfy an interface (shape), it would be nice if flow would remember the passed in type.

**Comment by kastermester** [comment]
It happens because your function return type explicitly states that it is only returning a `Fooable`, try this instead:

```js
// @flow

interface Fooable {
  foo(): string;
}

class AFoo {
  foo() { return 'foo from A' };
}

const fn = <T: Fooable>(a:T):T => a;

const result = fn(new AFoo());
(result: AFoo);
```

This instructs the type system that the input must be a `Fooable` but also that it returns the exact same type as the input type.

**Comment by jgrund** [comment]
Perfect. Thanks.
