### ISSUE TITLE
Erroneous "Function cannot be called on possibly undefined value undefined" error 

### ISSUE THREAD

**Issue by jmuthad** [facebook/flow#1938]
There is an issue where an unrelated line above a method call seems to be able to cause an issue.  I have tested it in both 0.24.0 and 0.27.0 so it's not new and also not fixed.  

Consider the following two types before the examples below.  

> type Props = {
>   value? : string;
>   onChangeText? : (text : string) => void;
>   onSubmitSearch? : (text : string) => void;
>   onClearPressed? : () => void;
>   placeholder? : string;
>   style : Object;
> }
> type State = {
>   value : string;
> }

I get an error saying that "call of method `onSubmitSearch` Function cannot be called on possibly undefined value" regarding the line where that function is called. 
> if (!!this.props.onSubmitSearch) {
>       let text = _.get(this.state, 'value', '');
>       this.props.onSubmitSearch(this.state.value);
> }

while When I remove the unrelated text variable definition and assignment above it as below the error goes away: 

> if (!!this.props.onSubmitSearch) {
>       this.props.onSubmitSearch(this.state.value);
> }

Note that the value for text isn't even used in the block at this point.  Also if I remove the assignment and just declare the `text` variable it removes the error.

**Comment by tadeuzagallo** [comment]
I believe that's because Flow can't be sure that the call `_.get(this.state, 'value', '')` won't modify the value of `this.props.onSubmitSearch`. You can assign the function to a local variable immediately after the null check, and the type refinement should be preserved across function calls.

**Comment by popham** [comment]
The exposition at https://flowtype.org/docs/dynamic-type-tests.html#caveats supports @tadeuzagallo.

**Comment by jmuthad** [comment]
fair enough.  Might be a good idea to get a more clear error message to be output but I could see how that would be difficult to implement.  Thanks @tadeuzagallo and @popham

**Comment by gbbr** [comment]
That #caveats page is now gone and this problem is still there...

**Comment by popham** [comment]
@gbbr The same or similar material is now under [docs/lang/refinements](https://flow.org/en/docs/lang/refinements/#refinement-invalidations).
