### ISSUE TITLE
Package up properly the parser as findlib package

### ISSUE THREAD

**Issue by fxfactorial** [facebook/flow#1945]
The parser right now is just dumped in the build directory. All that's missing is a META file to make the parser something that can be used in other OCaml projects. Basically I want to be able to use `flowtype.parser` as an ocamlfind package. 

This will make it much easier for me to use it in another project based on JavaScriptCore, (About to post another issue)

**Comment by jeffmo** [comment]
I think this makes sense, but we (the core team) would probably be a little reluctant to build something like this without a specific consumer in mind and thus: specific goals for the API. It'd be too easy to build something that's not quite right.

So with this in mind it might actually be easier to see this through and discuss specifics if you threw together a PR that refactors and/or does what you're looking for here. Obviously we can try to help answer specific questions if you have them -- either here or on IRC.
