### ISSUE TITLE
Some node methods' errors types are wrong

### ISSUE THREAD

**Issue by alexeygolev** [facebook/flow#1946]
Node has a `SystemError` class that extends `Error`. It has additional fields such as `errno` and `code`. At the moment all type declarations use Error type. ([example](https://github.com/facebook/flow/blob/699253b9ba4d2ce9b214381cfa8521b73017d3cd/lib/node.js#L572)) As methods such as `exists` are going to be deprecated and methods like `stat` will be used instead it's quite important to type errors as `SystemError` because people will have to rely on a particular field like `code`

**Comment by vkurchatkin** [comment]
I don't think that you can actually rely on this properties being there all the time

**Comment by chicoxyzzy** [comment]
This is how it's defined in TypeScript
https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/node/node.d.ts#L1445

**Comment by alexeygolev** [comment]
@vkurchatkin you most definitely can (see node [docs](https://nodejs.org/api/errors.html#errors_system_errors)). And as I mentioned there is no other way for some use cases (to check if the folder exists). TypeScript version takes it into account

**Comment by vkurchatkin** [comment]
>  you most definitely can 

It's not documented that fs functions are guaranteed to return only systems errors, so it's not test or enforced in any way.

> should at least be optional

Typescript definition seems reasonable, but it would be more accurate to say that error's type is `SystemError | Error`, which is the same as `Error`

**Comment by alexeygolev** [comment]
@vkurchatkin `SystemError | Error` will let me have this line typechecked without errors
```js
  if (err && err.code === 'ENOENT') {
        return resolve(false)
      }
```
At the moment  it says `property 'code' Property not found in Error`
