### ISSUE TITLE
Useless error reporting from parser, or provide better API? 

### ISSUE THREAD

**Issue by fxfactorial** [facebook/flow#1947]
I am writing OCaml bindings to JavaScriptCore, https://github.com/fxfactorial/ocaml-javascriptcore, and one cool idea I had was something like this:

``` ocaml
let () = 
  let js_vm = new JavaScriptCore.vm in
    (js_vm#evaluate_script [%check_js {|
const first = "Hello";
const second = " World";
first + second
|}]) 
|> print_endline
```

and the `check_js` is a `ppx` extension that will use `flow` to do some neat typechecking. (Also would be nice if flow can provide a function that takes a flow string and convert to plain JS rather than calling babel or something)

I've muddled around with flow and found one way, (related to my other issue of asking to make the parser a proper ocamlfind package)

``` ocaml
let () =
  let (a, b) =
    Parser_flow.program {|
      const first = "Hello";
const second = " World";
break
|}
  in
  List.iter (fun (_, item) ->
      Parser_flow.Error.PP.error item |> print_endline) b;
  ()
```

This clearly causes an error, but the error I get is utterly useless: 

``` shell
 ocamlopt parser_flow.cmxa test.ml -o T
~/R/f/_/s/parser ❯❯❯ ./T
Fatal error: exception Parse_error.Error(_)
Raised at file "hashtbl.ml", line 139, characters 19-28
```

So you could see how this could be really cool, assuming flow gave me better errors (Oh and I have JSC give back a free and easy `js_check_syntax` function)

**Comment by samwgoldman** [comment]
Errors are pretty useful, though. See the `Parse_error` module. The exception has a structure and with locations and messages. There's a printer for the errors as well.

**Comment by fxfactorial** [comment]
@samwgoldman Okay, maybe I'm doing something wrong? 

```ocaml
let () =
  let (a, b) =
    Parser_flow.program {|
      const first = "Hello";
const second = " World";
break
|}
  in

  let d = Parse_error.Error b in
  Printexc.to_string d |> print_endline
```
and the error printed is: 
```
Fatal error: exception Parse_error.Error(_)
Raised at file "hashtbl.ml", line 139, characters 19-28
```

Which doesn't seem to sound like a JavaScript based error

**Comment by samwgoldman** [comment]
You want to wrap `Parser_flow.program` in a `try ... with` to catch the exception. See `Parsing_service_js.do_parse` for an example.

**Comment by fxfactorial** [comment]
@samwgoldman great example, should be good for me, although meh it assumes a file?

**Comment by fxfactorial** [comment]
@samwgoldman Okay so now have:

```ocaml
let () =
  try
    let (a, b) =
      Parser_flow.program {|
      const first = "Hello";
const second = " World";
break
|}
    in
    print_endline "Everything is great"
  with
  | e ->
    let s = Printexc.to_string e in
    let err = Errors_js.(simple_error ~kind:ParseError Loc.none s) in
    let l = Errors_js.infos_of_error err in
    List.iter (fun (_, r) -> List.iter print_endline r) l
```

But this won't compile because I need `Errors_js.ml`, which okay because there isn't a `cmxa` being built I follow the breadcrumbs with:  (Some copied over from hack)

```shell
ocamlopt sys_utils.ml path.ml myMap.ml  utils_js.ml errors_js.ml parser_flow.cmxa test.ml -o T
```

which will crap out with Core and I won't install core just for this. Any way to built out flow common as a ocamlfind library? I see some remaining ocp-build stuff that seems to have tried to do that?

**Comment by samwgoldman** [comment]
hmm, you shouldn't need anything outside of src/parser. Can't you handle the parse error without Errors_js?

**Comment by fxfactorial** [comment]
@samwgoldman  I could but I thought that `Errors_js` would provide the nice information about what's wrong with the JS code. Do you have an example that wouldn't need that?

**Comment by jeffmo** [comment]
@fxfactorial: Note that the error given is *Parse_error*.Error (not *Errors_js*.Error). Maybe I'm missing something?

**Comment by samwgoldman** [comment]
I thought you just wanted to get parse errors. If you want to get type errors, you will need to pull in a lot more of Flow, including core and lots of hack.

**Comment by fxfactorial** [comment]
@samwgoldman that's fine, how much more? And is it easily done? Can you guys expose it so that its easily usable outside of flow?

**Comment by samwgoldman** [comment]
I know that @mroch is interested in cleaning up our dependency on hack. Both he and @gabelevi are trying to move us over to a more "stock" ocaml build pipeline, which might make it easier to modularize the core. However, turning Flow into a library isn't a priority for us, at least in the near term.

**Comment by fxfactorial** [comment]
Okay bummer. Thanks

**Comment by mroch** [comment]
I think Core is actually hack/utils/core.ml which depends on a very stripped down version of the real Core, in hack/third-party

**Comment by calebmer** [comment]
Closing since it looks like support was provided. If you are still having problems then let us know 👍
