### ISSUE TITLE
spread operator ignores order when used as an arguments list

### ISSUE THREAD

**Issue by f1qwase** [facebook/flow#1951]
here is an example

``` javascript
const f = function(x: string, y: number) {
    return;
}
const a = ['5', 6];

//this works
f.apply(null, a);

/* but this gives 2 errors:
* "string. This type is incompatible with number "
* and
* "number. This type is incompatible with string"
*/
f(...a);
```

It looks like Flow works with a list of arguments as an unordered list with
[live example](https://tryflow.org/?code=LyogQGZsb3cgKi8KCmNvbnN0IGYgPSBmdW5jdGlvbih4OiBzdHJpbmcsIHk6IG51bWJlcikgewogICAgcmV0dXJuOwp9Cgpjb25zdCBhID0gWyc1JywgNl07CgovL3RoaXMgd29ya3MKZi5hcHBseShudWxsLCBhKTsKCi8vIGJ1dCB0aGlzIGRvZXNuJ3QKZiguLi5hKTs=)

**Comment by calebmer** [comment]
This works in the latest version of Flow 👍 

https://flow.org/try/#0MYewdgzgLgBAZjAvPArmYUCW4AUAPALhmgCdMwBzAGhgE8iwUBbAIwFMSBKGAbwCgYgmCTZQUJMAG4+AXz6hIsAIZIYAbQDkAVg00AbAF1pfAPQmoAC0wQYAdxAkA1hD5wAdEoAOngDa0cjD4+NEqcxiYAVDAsKLCW1jAUmABubDYATDAcJA4QBHxRAESk5BRuMAAqVjZQtJ5sMAnkoEyeSlgsPg22mJYwjKwcMIUFMEpgACajhQPsJOVVCbX1jTbNIK3tmJ3dvRbEUGSUIxEmrjhul6HSQA
