### ISSUE TITLE
nonexisting field read is allowed in an `if`

### ISSUE THREAD

**Issue by sakari** [facebook/flow#1954]
I understand that the check for existence of `falg` makes it kinda ok (from typing perspective) to read the value but it is a source of great many program errors that a mistyped field is falsy in comparisons like this.

```
class Foo {
    flag: boolean;

    constructor() {
        this.flag = true
    }

    noerror() {
        if(this.falg)
            console.log('whoohaa')
    }
}
```

having to type `if(this.flag === true)` or something like that feels a bit tedious and easy to miss coming from straight up javascript.

Is there any way to prevent undeclared field reads here? In typescript the typechecker detects this so I assume that it is possible.

**Comment by Awpteamoose** [comment]
Assuming #1810 was closed with a fix, this could be a regression?

**Comment by gopritescu** [comment]
Seeing this as well with 0.42.0

**Comment by nmn** [comment]
I don't think this is a bug. Objects in Flow are allowed extra types, so you should be able to check for them.

**Comment by calebmer** [comment]
This is not a bug. We allow this in `if`s so that you can check for property types 👍
