### ISSUE TITLE
Document `constructor` functions in classes.

### ISSUE THREAD

**Issue by btipling** [facebook/flow#196]
I noticed that in the flow lib code that use of a special `constructor` function declaration is used but it's not documented on the website. I've tried to use it but it has so far led to errors, so I have to go through the flow source code some more to figure it out, but here is an example of it in `lib/node.js`:

```
declare class Buffer {
  constructor(value: Array<number> | number | string, encoding?: string): void;
 ...
}
```

`constructor` should probably be included in the [Classes documentation](http://flowtype.org/docs/classes.html#_).

What I've tried to do is in an interface is:

```
declare class DiffMatchPatch {
  constructor(): void;
}

declare var diff_match_patch: DiffMatchPatch;
```

and then try to use `new diff_match_patch();` in our `@flow weak` code but it blows up saying Constructor cannot be called even though I defined it in the interface file.

**Comment by glenjamin** [comment]
I still can't see any docs for how to document a constructor in a type declaration, am I missing something obvious?

**Comment by thejameskyle** [comment]
@glenjamin Do you mean like this:

```js
declare module "my-module" {
  declare class Foo<X: number> {
    x: X;
    constructor(x: X): this;
  }
}
```

**Comment by glenjamin** [comment]
Yep, couldn't see that in the docs anywhere - figured it out from some comments on here
