### ISSUE TITLE
Function cannot be called on any member of intersection type

### ISSUE THREAD

**Issue by nodkz** [facebook/flow#1966]
I have properly working code with `compose` function. But flow returns to me such error:

<img width="465" alt="screen shot 2016-06-17 at 21 17 44" src="https://cloud.githubusercontent.com/assets/1946920/16155395/063207f0-34d1-11e6-8554-7c32cfc5488b.png">
```
function call: src/resolver/resolver.js:85
Function cannot be called on any member of intersection type
intersection: src/resolver/resolver.js:85
```

[resolver.js](https://github.com/nodkz/graphql-compose/blob/flow_error/src/resolver/resolver.js)
```js
type ResolverMWResolveFn = (resolveParams: ResolveParams) => mixed;
type ResolverMWResolve = (next: ResolverMWResolveFn) => ResolverMWResolveFn;

class Resolver {
  composeResolve(): GraphQLFieldResolveFn {
    const resolveMWs: ResolverMWResolve[] =
      this._getMiddlewaresByKey('resolve')
      .map(mv => mv.resolve);
    return compose(...resolveMWs)(this.resolve);  
           ^^^^^^^^^^^^^^^^^^^^^^  error
  }
}
```

`compose` function has following annotation [compose.js](https://github.com/nodkz/graphql-compose/blob/flow_error/src/utils/compose.js):
```
type FN<A,R> = (a: A) => R;
const compose:
  ((end: void) => (<T>(x: T) => T)) &
  (<A,B>(m1: FN<A,B>, end: void) => FN<A,B>) &
  (<A,B,C>(m1: FN<B,C>, m2: FN<A,B>, end: void) => FN<A,C>) &
  (<A,B,C,D>(m1: FN<C,D>, m2: FN<B,C>, m3: FN<A,B>, end: void) => FN<A,D>) &
  (<A,B,C,D,E>(m1: FN<D,E>, m2: FN<C,D>, m3: FN<B,C>, m4: FN<A,B>, end: void) => FN<A,E>) &
  (<A,R>(...funcs: Array<FN<A,R>>) => FN<A,R>)
  = (composeImpl: any);
```

May be it `flow` bug, because similar implementation with object (instead func) [works perfectly](https://github.com/nodkz/graphql-compose/blob/flow_error/src/resolver/resolver.js#L74).

You may clone branch `flow_error` https://github.com/nodkz/graphql-compose/tree/flow_error it has only this one error. 
And it blocking me.

**Comment by nodkz** [comment]
Or may be somebody suggest me how to force flow to skip this line (do not display/track error)

**Comment by samwgoldman** [comment]
The latest version of Nuclide includes the full error information from Flow. You can also run `flow` from the command line to see the detailed information. Can you provide the full error info to this issue?

**Comment by nodkz** [comment]
Problem was on my side with types incompatibility. I'd solve this problem couple days ago, exactly after nuclide update and extended error information! 
Thanks a lot.

Now errors much much more informative.
<img width="463" alt="screen shot 2016-06-27 at 10 25 09" src="https://cloud.githubusercontent.com/assets/1946920/16368593/95da10c8-3c51-11e6-80a7-da63e6eda604.png">

**Comment by nodkz** [comment]
@samwgoldman 
Will be greate if you done something similar with Coverage:
One line, two same errors. What exactly not covered is too difficult to understand.

<img width="785" alt="screen shot 2016-06-27 at 10 33 32" src="https://cloud.githubusercontent.com/assets/1946920/16368683/c1b8b8ba-3c52-11e6-97aa-23c3e04fa357.png">
