### ISSUE TITLE
`opam depext --install flowtype` hangs on `[flowtype: make] Command started` forever

### ISSUE THREAD

**Issue by yamafaktory** [facebook/flow#1972]
Hi,

I've created a [Docker image](https://hub.docker.com/r/yamafaktory/docker-flowtype/) based on ocaml/opam:debian-8_ocaml-4.03.0 which is working great with Flow v0.26.0 but fails with the latest v0.27.0:

```bash
[flowtype: make] Command started
```

And then nothing more happens and no errors are thrown... any idea?

The source repository of the image is on [https://github.com/yamafaktory/docker-flowtype](https://github.com/yamafaktory/docker-flowtype). The described issue can be reproduced by running the following commands:

```bash
git clone https://github.com/yamafaktory/docker-flowtype.git
cd docker-flowtype
docker build --build-arg BUILD_FLOW_VERSION=0.27.0 -t yamafaktory/docker-flowtype .
```

**Comment by mroch** [comment]
This sounds similar to the issue described by https://github.com/facebook/flow/pull/1941. Presumably neither mercurial nor git are available in the docker image, right?

**Comment by yamafaktory** [comment]
@mroch Thanks for the guidance! Strangely adding *git* (`apt-get install git` or `apt-get install git-core`) didn't fix the issue but *mercurial* did it. Regarding *git*, I also tried to upgrade the Debian image to Stretch without success.
