### ISSUE TITLE
Property starts with $ can not be auto completed

### ISSUE THREAD

**Issue by ajihyf** [facebook/flow#1973]
``` javascript
class Scope {
  $$watchers: Watcher[] = [];
  $on(eventName: string, listener: ScopeEventListener): AnyFunction {
     this. // can not autocomplete $$watcher 
  }
}

const scope = new Scope();
scope.$o // can not autocomplete $on
```

There is an option `munge_underscores` in the [doc](https://flowtype.org/docs/advanced-configuration.html#options). But I didn't find doc saying property starts with `$` is not allowed.

**Comment by Brianzchen** [comment]
Looks like they both work now, will close unless there's anymore issues related

<img width="1036" alt="Screen Shot 2021-01-03 at 3 50 11 pm" src="https://user-images.githubusercontent.com/12436524/103471969-67d32700-4ddb-11eb-9ba3-5a3981ce77e0.png">
<img width="855" alt="Screen Shot 2021-01-03 at 3 50 01 pm" src="https://user-images.githubusercontent.com/12436524/103471970-6bff4480-4ddb-11eb-9b4f-654bd238a355.png">
