### ISSUE TITLE
Question: what does "Not covered by Flow" mean

### ISSUE THREAD

**Issue by dudeinthemirror** [facebook/flow#1976]
(using Nuclide package in Atom)
Can't seem to find the meaning of these flow warnings. Here are a couple of cases:

![screen shot 2016-06-19 at 7 04 21 am](https://cloud.githubusercontent.com/assets/981638/16177840/e2ab4fa4-35ec-11e6-8c16-fa83da7f1e4c.png)
![screen shot 2016-06-19 at 7 04 34 am](https://cloud.githubusercontent.com/assets/981638/16177849/f6ce8e88-35ec-11e6-9190-d45cb3d590bf.png)

![screen shot 2016-06-19 at 7 13 34 am](https://cloud.githubusercontent.com/assets/981638/16177871/7f06face-35ed-11e6-874e-5845dd2889dc.png)
![screen shot 2016-06-19 at 7 13 56 am](https://cloud.githubusercontent.com/assets/981638/16177872/81d70ece-35ed-11e6-97bc-abb7c8d111bd.png)

**Comment by samwgoldman** [comment]
I'm not totally certain, but I suspect this error is saying that the module "ReactNative" doesn't include Flow type information, which means the imports from that module will have the type `any` in your typed module. You should follow up with Nuclide, though.
