### ISSUE TITLE
Promises: chaining .then() loses type information 

### ISSUE THREAD

**Issue by dalongi** [facebook/flow#198]
var p = new Promise(function(resolve, reject) {
  resolve(5);
});
var p2 = p.then(function(num) {
  return num.toFixed();
});

// Actual: p2 is Promise::any::
// Expect: p2 to be Promise::string::

**Comment by avikchaudhuri** [comment]
When I add the following line to your test:

p2.then(function(str: number) { return str; });

I get expected number / string incompatibility errors.

When I fix the annotation of str to string, the errors go away.

This means that p2 is indeed tracked as Promise<string> and not Promise<any>, at least internally. Do you remember how you concluded that .then() loses type information? (It would point to a different bug, in that case. For example, did you try a different annotation? Or did you use type-at-pos to view the inferred type?

**Comment by dalongi** [comment]
Yes, it seems to be ok when the function is explicitly typed. But this should work based on inference. I have verified both of these do not work as expected:
 - type-at-pos to view inferred type
 - No explicit type, undetected error in usage of inferred type

var p2 = new Promise(function(resolve, reject) {
  resolve(5);
})
.then(function(num) {
  return num.toFixed();
})
.then(function(str) {
  // This should fail because str is str, not number
  return str.toFixed();
});

**Comment by dalongi** [comment]
Ping.

**Comment by gabelevi** [comment]
Spoke to @dalongi offline. I think I have a fix for this...it seemed to be an issue with how we were dealing with union types, and the type of `then()` has a union type. We're discussing it internally.

**Comment by avikchaudhuri** [comment]
Will be fixed in the next release, will close when it lands.

**Comment by samwgoldman** [comment]
This is definitely fixed and this issue can be closed. Since the callback argument to then is a union type, error messages suffer from #341

**Comment by samwgoldman** [comment]
Actually, why is the onFulfill callback argument to then a union type? It seems like it shouldn't be.

**Comment by samwgoldman** [comment]
OK, specifics:

```
/* @flow */

var p: Promise<string> = new Promise(function(resolve, reject) {
  resolve(5);
});

// test2.js|3 col 26 error|  constructor call
// || Error:
// test2.js|4 col 11 error|  number
// || This type is incompatible with
// /private/var/folders/z1/sdzkzrw94b1dttp72spg4fd00000gn/T/flow/flowlib_12b93d9f/lib/core.js|339 col 25 error|  union type
// || 
```

Why isn't this error message complaining that number is incompatible with string?

**Comment by samwgoldman** [comment]
OK. Apologies for the incessant comments. This is the last one.

My example above truly is the issue described in #341.

The following is, I believe, different:

If the type of a promise is specified, things work as expected.

```
var p: Promise<number> = new Promise(function(resolve, reject) {
  resolve(5);
});

var p2: Promise<string> = p.then(function(n) {
  var check = n; // type-at-pos here returns `number`
  return n.toString();
})
```

But if the `p` promise's type is not specified, flow seems to infer a union.

```
var p = new Promise(function(resolve, reject) {
  resolve(5);
});

var p2: Promise<string> = p.then(function(n) {
  var check = n; // type-at-pos here returns "union type"
  return n.toString();
})
```

However! The following still type checks:

```
var p = new Promise(function(resolve, reject) {
  resolve(5);
});

var p2: Promise<string> = p.then(function(n) {
  var check: number = n; // if we infer a union, why does this work?
  return n.toString();
})
```

This is probably a separate issue.

**Comment by mroch** [comment]
Gonna close this since it looks like the original issue is fixed.

@samwgoldman , if there's another issue can you file a new one? thanks :)
