### ISSUE TITLE
Release 0.27.0 archive won't build while checkout tag does

### ISSUE THREAD

**Issue by turadg** [facebook/flow#1981]
A source download from the Releases page fails to `make` but checking out tag `v0.27.0` succeeds. (MacOS 10.11.5, OCaml 4.03.0)

To repro,
```
wget https://github.com/facebook/flow/archive/v0.27.0.tar.gz
open v0.27.0.tar.gz && cd flow-0.27.0/
make
```
It stops after,
```
mkdir -p _build/src/embedded/
cp src/embedded/flowlib_elf.c _build/src/embedded/flowlib_elf.c
cd _build/src/embedded/ && ocamlopt   -ccopt -DNO_LZ4 -c flowlib_elf.c
ocaml -I scripts -w -3 unix.cma scripts/gen_build_id.ml _build/hack/utils/get_build_id.gen.c
```

This causes https://github.com/Homebrew/homebrew-core/pull/1883 to fail, requiring a checkout https://github.com/Homebrew/homebrew-core/pull/2196#issuecomment-227196507.

**Comment by mroch** [comment]
i think this is the same underlying issue as https://github.com/facebook/flow/issues/1972: if hg and/or git aren't installed, gen_build_id.ml seems to stall forever.

when you check out the tag, are you running it any differently? like maybe in a container that has git vs one that doesn't?

**Comment by turadg** [comment]
By container you mean Docker? I'm just running this in MacOS terminal. Same shell env. The above doesn't work and the following does,
```
git clone git@github.com:facebook/flow.git
cd flow
git checkout v0.27.0
make
```
Ending with,
```
mkdir -p bin
cp _build/src/flow.native bin/flow
```

**Comment by mroch** [comment]
ok i can repro by removing `hg` from my path, even when git is installed. not sure why it works from a git checkout... still looking into it.

**Comment by mroch** [comment]
fix incoming
