### ISSUE TITLE
Question: Possible bug or bad docs with destructuring default

### ISSUE THREAD

**Issue by SeeThruHead** [facebook/flow#1982]
```javascript
export const clickIfAction = withProps(
  ({ action = {}, possible_actions }: { action?: any, possible_actions: any }) => ({
    clickHandler: action.type
      ? () => possible_actions[action.type](action) : null
  })
);
```

this errors out with `unexpected token =`

flow-bin@0.27.0

just started using flow but this is the same syntax used for stateless components in the docs

**Comment by samwgoldman** [comment]
I am not able to reproduce with the provided example. Can you double check?

**Comment by SeeThruHead** [comment]
this is my mistake i think

running node_modules/.bin/flow doesn't show this error

but running flow from path does, is the npm package 'flow' deprecated?

npm ls -g flow
```
flow@0.2.3
```
