### ISSUE TITLE
Flow doesn't seem to understand default values in array destructuring

### ISSUE THREAD

**Issue by glenjamin** [facebook/flow#1985]
From the Firefox console:

``` js
const [a, b = {}, c = {}] = [1, {a: 1}];
a
1
b
Object { a: 1 }
c
Object {  }
```

https://tryflow.org/?code=Y29uc3QgW2EsIGIgPSB7fSwgYyA9IHt9XSA9IFsxLCB7YTogMX1dOw==
in flow:

```
assignment of identifier `c`. Could not resolve name
```

**Comment by samwgoldman** [comment]
Thanks for the report!

**Comment by mroch** [comment]
the default causes flow to parse the default and subsequent array elements as a sequence expression.

slightly simpler repro: https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAG0BDAXgEYAaDAXTDOOrACZaBuIA

check out the AST. the right side of the AssignmentPattern is incorrectly a SequenceExpression.
