### ISSUE TITLE
Inferring array type from object values when exporting does not work

### ISSUE THREAD

**Issue by philipp-spiess** [facebook/flow#1989]
The following code does not work as expected:

``` js
/* @flow */

const foo: {'bar': {}}= {
  'bar': {}
}

module.exports = {
  baz: [
    foo['bar'],
  ],
}
```

Flow does not infer a type for the `baz` array:

```
test.js:9
  9:     foo['bar'],
         ^^^^^^^^^^ access of computed property/element. Missing annotation
```

When I specify the type of `foo['bar']`, everything works as expected:

``` js
/* @flow */

const foo: {'bar': {}}= {
  'bar': {}
}

module.exports = {
  baz: [
    (foo['bar']: {}),
  ],
}
```

Edit: When I remove the `module.exports` (in favour of `const lol =`), flow reports no error.

**Comment by calebmer** [comment]
This is fixed in the latest version of Flow 👍 

https://flow.org/try/#0MYewdgzgLgBAZiEAuGBvA5AIwIYCd0qoC+RAvGgFAwxZ4FpEWMUC2IAJgK4A2ApgHS8AHgAcQuKBBjlUVGDgBeKANpzqCEMtr4AugBo5+pkA
