### ISSUE TITLE
add support for CustomEvent

### ISSUE THREAD

**Issue by coot** [facebook/flow#1990]
- `CustomEvent` custructor
- `Event.initCustomEvent` which must receive four arguments: `eventType: string`, `bubbles: boolean`, `cancelable: boolean` and `detail: any`.

This is not perfect, since the method `document.createEvent` might return `CustomEvent` instance rather than just `Event`, but flow has no logic to express return depending on the input type.  It would be nice to be able to say that `document.createEvent('CustomEvent')` returns `CustomEvent` instance while `document.createEvent('MouseEvent')` returns `MouseEvent` instance.

**Comment by gf3** [comment]
i have a PR for this here → https://github.com/facebook/flow/pull/1873

**Comment by gf3** [comment]
btw you can implement a form of polymorphism with literal arguments:

```js
declare class MyClass {
  myMethod(arg: 'a'): A;
  myMethod(arg: 'b'): B;
  myMethod(arg: string): C;
}
```
