### ISSUE TITLE
Required module not found

### ISSUE THREAD

**Issue by aocenas** [facebook/flow#1993]
Hi,

I use Flow in a project without trouble most of the time but I recently installed npm package and for some reason Flow cannot find it.

```
31: const postcssMiddleware = require('postcss-middleware');
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ postcss-middleware. Required module not found
```

When I do `flow get-imports ./src/app.js` I get something like this:

```
...
/Users/andrejocenas/dev/whatlib/node_modules/autoprefixer/lib/autoprefixer.js@/Users/andrejocenas/dev/whatlib/src/app.js:30:22,30:44
postcss-middleware@/Users/andrejocenas/dev/whatlib/src/app.js:31:27,31:55
path@/Users/andrejocenas/dev/whatlib/src/app.js:22:14,22:28
```

It seems like Flow wants to resolve the `postcss-middleware` module as system module like `path` but I do not know why. The code that requires those modules is the same:

```
const autoprefixer = require('autoprefixer');
const postcssMiddleware = require('postcss-middleware');
```

I use flow installed via npm `"flow-bin": "0.27.0`.

**Comment by agrcrobles** [comment]
you will have to declare postcssMiddleware interface in [lib] section

**Comment by aocenas** [comment]
@agrcrobles thanks, declaring the module in my [libs] helped, but it seems like a workaround for some module resolution problem. Only thing that seems to be different for the `postcssMiddleware` is that it has typescript `d.ts` definitions but I am not sure if it is the only one of my dependencies that has that.  

If anybody wondered how you declare a commonJS module, you need `declare var exports: <type>`. This does not seem to be documented in the Flow docs.

**Comment by calebmer** [comment]
You can use `flow-typed` to install type definitions for your modules and generate stubs for those without type definitions. Please use `flow-typed` 👍
