### ISSUE TITLE
transform-flow-strip-types causes eslint error with ES6 default parameter

### ISSUE THREAD

**Issue by Zerim** [facebook/flow#1997]
The following triggers a 'space-infix-ops' error:

```
const myFunc = (a: any, b: Object = {}, c: any) => {}
```

The following does not (but is ugly and contrary to community style conventions). Note the space before the colon:
```
export const myFunc = (a: any, b : Object = {}, c: any) => {}
```

This seems partly related to eslint/eslint#3380.

Seems like flow-strip-types is greedily removing whitespace, causing the assignment operator to appear with no spaces next to the parameter name to eslint. I think the default behavior should be to leave a whitespace on either side of the assignment operator since this is a widely used style convention.

(Not sure if this is the right place to file this bug, but there are no issues enabled [here](https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-flow-strip-types)

**Comment by pvolok** [comment]
Babel related issues can be reported here: https://phabricator.babeljs.io/

**Comment by mroch** [comment]
thanks @Zerim (and @pvolok)! I think @pvolok's right about babel's phabricator being a better place to report this.

**Comment by mroch** [comment]
but cc @kittens just in case, since he wrote that plugin back in the day

**Comment by Zerim** [comment]
Thanks for the quick response. Posted the issue on phabricator: https://phabricator.babeljs.io/T7458
