### ISSUE TITLE
Create a Sublime Text plugin

### ISSUE THREAD

**Issue by iclems** [facebook/flow#2]
IMO, A simple JSLint-like with live margin icons and warnings/errors would be huge. Do you have that in plan? Are you interested?

**Comment by samwgoldman** [comment]
Seems like people have stepped up to make this one work—cool! @iclems, do any of the plugins mentioned in this thread meet your needs?

**Comment by pluma** [comment]
A little birdie told me Facebook is currently trying to improve developer experience across different editors (not just Nuclide). Are there any plans to provide a ST3 plugin that handles code intelligence a bit better? SublimeLinter-Flow is better than nothing but it's 3rd party and only adds warnings and errors.

**Comment by StreetStrider** [comment]
Hello. I'm not using margin icons and warnings and other IDE-ish-style features in ST, but I would love to see plugin which can infer types under cursor (essentially a `type-at-pos` feature from CLI). I was often finding myself needing to know which types are Flow *thinks* my code produces. It is often happen that even if `flow check` shows zero errors is not meaning everything is ok (false negative). Plugin would allow me to catch such errors more fast and more often.
