### ISSUE TITLE
crypto$Hmac update() returns itself, but definition in node.js returns void

### ISSUE THREAD

**Issue by ikai** [facebook/flow#2002]
This line:

https://github.com/facebook/flow/blob/master/lib/node.js#L317

`update(data: any): void;`

Seems to be incorrect. In a node REPL, I see:

```
> crypto.createHmac('sha1', 'abc').update('asdasdsasas')
Hmac { _handle: {}, _options: undefined }
```

This is confirmed when I look at the node.js code:

https://github.com/nodejs/node/blob/master/lib/crypto.js#L96

returns an instance of `Hash.prototype.update`, which is defined as:

```
Hash.prototype.update = function(data, encoding) {
  encoding = encoding || exports.DEFAULT_ENCODING;
  this._handle.update(data, encoding);
  return this;
};
```

The line in node.js should probably be:

`update(data: any): crypto$Hmac;`

Similar to the definition for `crypto$Hash`.

**Comment by mroch** [comment]
i agree! nice catch. looks like Sign.update is wrong too; its implementation is literally `Sign.prototype.update = Hash.prototype.update;`
