### ISSUE TITLE
Type union fails to check properly when imported from lib

### ISSUE THREAD

**Issue by gf3** [facebook/flow#2005]
Perhaps I'm doing something wrong here, but I have a type union that checks correctly when defined local to the file however when the exact same union is defined in a lib the type fails to check correctly. I've created [a barebones sample repo](https://bitbucket.org/gf3/flow-immutable-issue) to demonstrate the issue.

Relevant files:
- [.flowconfig](https://bitbucket.org/gf3/flow-immutable-issue/src/3a2d3afdec0a41549adcfc6058d033a460117619/.flowconfig?at=master&fileviewer=file-view-default)
- [lib/user.js.flow](https://bitbucket.org/gf3/flow-immutable-issue/src/3a2d3afdec0a41549adcfc6058d033a460117619/lib/user.js.flow?at=master&fileviewer=file-view-default)
- [index.js](https://bitbucket.org/gf3/flow-immutable-issue/src/3a2d3afdec0a41549adcfc6058d033a460117619/index.js?at=master&fileviewer=file-view-default)

**Comment by calebmer** [comment]
This should be fixed in the latest version of Flow :+1:
