### ISSUE TITLE
New Dynamic Type Test: value.constructor

### ISSUE THREAD

**Issue by appsforartists** [facebook/flow#2009]
The [Dynamic Type Test documentation](https://flowtype.org/docs/dynamic-type-tests.html) points out that Flow will understand that `x` will be understood to be a `Thing` inside this block:

``` javascript
if (x instanceof Thing) {`
```

unfortunately, the same is not true of this code:

``` javascript
if (x.constructor === Thing) {`
```

This is not just a stylistic choice; there are some cases where `instanceof` fails but `value.constructor` succeeds (for instance, `value.constructor === Number`).  Can we please add a dynamic type test that teaches `if` blocks about `constructor` checks?

**Comment by SamChou19815** [comment]
I don't think we intend to add support for corner cases like this. If you want to test for number, use `typeof x === 'number'` instead.
