### ISSUE TITLE
`unsafe.enable_getters_and_setters` with `suppress_comment` raises errors

### ISSUE THREAD

**Issue by januswel** [facebook/flow#2014]
We aren't able to set `unsafe.enable_getters_and_setters` option when dependent npm packages suppress the lines using `suppress_comment`.

We get

``` text
// $FlowIssue
^^^^^^^^^^^^^ Error suppressing comment. Unused suppression
```

Any oversights?

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣
