### ISSUE TITLE
If possible to support root resolve or let us turn off  "Required module not found" checking ?

### ISSUE THREAD

**Issue by smilexu** [facebook/flow#2015]
I am working a react-js project with https://github.com/davezuko/react-redux-starter-kit.

I got lots of "required module not found" error, due to  this feature https://github.com/davezuko/react-redux-starter-kit#root-resolve.
Paste content below:

> Webpack is configured to make use of resolve.root, which lets you import local packages as if you were traversing from the root of your ~/src directory. Here's an example:
> // current file: ~/src/views/some/nested/View.js
> // What used to be this:
> import SomeComponent from '../../../components/SomeComponent'
> 
> // Can now be this:
> import SomeComponent from 'components/SomeComponent' // Hooray!

For my case:

```
import * as Constants from 'constants/AppConstants'
import * as Api from 'constants/Api'
```

We will get error “required module not found”

```
import * as Constants from '../constants/AppConstants'
import * as Api from '../constants/Api'
```

These code is fine

`import { ajax, when } from 'jquery'`
Same problem for this code.

In this case, can we support it or at least allow us to turn off this checking.

**Comment by vjpr** [comment]
I am interested in such a feature too.

The only workaround seems to be to add declaration files for all your dependencies.

**Comment by mmazzarolo** [comment]
Any reason for this discussione being closed?

**Comment by CodyReichert** [comment]
For modules within your own source-code, `module.name_mapper` should work for your use-case, right? https://flowtype.org/docs/advanced-configuration.html#options

I have a similar setup, and that works great for me (minus the duplication between those name mappings and my webpack module resolvers).

Regarding the jQuery import -- what does your `.flowconfig` look like? Are you ignoring `node_modules`? If so, you will need a declaration file.

**Comment by mmazzarolo** [comment]
@CodyReichert yup:
```
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=.
```

Works perfectly, thanks!

**Comment by neutraali** [comment]
To add an example to @CodyReichert's suggestion from the perspective of trying to things the "webpack way" - You can transform:  
```
import * as Constants from 'constants/AppConstants'
``` 
... To something that **Flow** understand like by tweaking your `.flowconfig`
```
[options]
module.name_mapper='^\([-a-zA-Z]+\)\/\(.*\)' -> '<PROJECT_ROOT>/\1/\2'
```

You can sort of verify this by running:
``` 
flow find-module constants/AppConstants path/to/myComponent.js
```
