### ISSUE TITLE
"We've run out of filesystems to use for shared memory" on travis

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2017]
I get this error on travis when I do `flow check` with 0.27. Version 0.26 works fine. I suppose there should be a way to fix this with configuration, but I didn't manage to find it

**Comment by jeffmo** [comment]
@gabelevi is digging into a potentially similar Travis issue at the moment, so let's see what he comes up with

**Comment by vkurchatkin** [comment]
@jeffmo @gabelevi any updates? it seems that something similar happens on CircleCI as well

**Comment by vkurchatkin** [comment]
Actually it's a bit different. It fails silently with code 15 (Out_of_shared_memory ?), but this only happens when I run `flow check` from make. Works fine if I run it directly from shell

**Comment by vkurchatkin** [comment]
Exactly the same happens on travis when using `sudo: required`. Running flow directly from `.travis.yml` (or `circle.yml`) works fine

**Comment by vkurchatkin** [comment]
Ok, it looks like Out_of_shared_memory problem is fixed in `0.30.0`

**Comment by vkurchatkin** [comment]
Closing in favour of https://github.com/facebook/flow/issues/2161

**Comment by jokeyrhyme** [comment]
Just FYI: I'm seeing this with `flow` 0.51.0 in Ubuntu 16.04 under Windows Subsystem for Linux

**Comment by jbaxleyiii** [comment]
@jokeyrhyme I'm seeing the same

**Comment by rhyek** [comment]
Also seeing this on WSL.

**Comment by rhengles** [comment]
Another one here having this issue.

This seems to be the cause:

https://github.com/Microsoft/WSL/issues/1732
