### ISSUE TITLE
Use of Object and Function discouraged?

### ISSUE THREAD

**Issue by ffxsam** [facebook/flow#2018]
I have a question about the docs, which discourage the use of `Object` and `Function` types.

Should they really be discouraged at all? Because I'd say in most cases, it's not practical to specify the full type of an object or function. For instance, if I use a third party library that returns an object that has 200 properties attached to it, and I want to pass that into my own function which is annotated with Flow. It's not practical at all for me to create a new type and specify those 200 props. I'd just use `Object`.

Am I approaching this wrong? Bear with me as I literally _just_ started using Flow a few days ago!
Thanks.

**Comment by vkurchatkin** [comment]
You can use them, as well as `any`, but then flow will be unable to type-check some parts of your code.

>  I want to pass that into my own function which is annotated with Flow. It's not practical at all for me to create a new type and specify those 200 props

You can just specify the props you are going to use in your function

**Comment by ffxsam** [comment]
Ah ok, so you can do selective annotation for objects. Great! Thanks for the info :)
