### ISSUE TITLE
Flow not reporting an error about passing wrong type into func

### ISSUE THREAD

**Issue by ffxsam** [facebook/flow#2019]
I've got the following code (all in the same file):

```js
type InsightType = {
  ownerId: string,
  test: boolean,
};

// ...

    }, (error, result: InsightType) => {
      if (error) console.error(error.message);
      else {
        dispatch(sendNotification(result.ownerId, 'Updated yo!'));
      }
    });
```

And then in another file, the `sendNotification` signature is:

```js
export function sendNotification(userIds: Array<string>, message: string): Function {
```

Yet when I run `npm run flow`, I get no errors. Clearly I'm passing a string into a function that expects an array of strings. Why does this not throw an error?

**Comment by samwgoldman** [comment]
Can you provide a repro case? There isn't enough information in this issue to say what's wrong here.

**Comment by ffxsam** [comment]
Sure, here you go.

https://github.com/ffxsam/flow-issue

**Comment by samwgoldman** [comment]
You need to add the `/* @flow */` pragma comment to the top of notification.js

**Comment by ffxsam** [comment]
Oh geez. 😣  Dumb mistake indeed, still not used to that.

Thanks 👍
