### ISSUE TITLE
props type checking doesn't work with wrapped components

### ISSUE THREAD

**Issue by ffxsam** [facebook/flow#2022]
Consider the following:

``` jsx
// @flow

import React, { Component, PropTypes } from 'react';
import Radium from 'radium';

class TestThing extends Component {
  props: {
    name: string,
  };

  render() {
    return <div>
      Hello {this.props.name}.
    </div>
  }
}

export default Radium(TestThing)
```

If, in another file, I do `<TestThing name={23} />`, Flow doesn't report any errors because Radium is wrapping `TestThing`. If I remove `Radium()`, then it works as expected.

**Comment by asolove** [comment]
I don't think this is a Flow-specific issue, it's just a question of Radium declaring the right types for its wrapper component. I looked and there is a [slightly out-of-date libdef](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/radium_v0.19.x/flow_v0.30.x-/radium_v0.19.x.js#L107) that should correctly figure out the prop types for the wrapping component. It will need to be updated to support the React type changes in Flow v0.53.

But I think this Flow-specific issue can be closed, and those who want a Radium libdef that works with React 0.53 can discuss it in the Radium repo. (/cc @calebmer)
