### ISSUE TITLE
[feature] call stack for error

### ISSUE THREAD

**Issue by nodkz** [facebook/flow#2023]
Sometimes flow gives unclear errors and root of problem located in not that part which is highlight by flow. So it will be very cool if flow can gives a call stack for particular error. And guys from nuclide team implemented it for atom-nuclide.

Right now flow gives first and last point of type inconsistency. But need to see all intermediate steps.

Example of such problem can be found in [graphql-js](https://github.com/graphql/graphql-js/tree/63f9985c535352f0d503807d1881c0b01a0cd868), if change flow from 0.26 to 0.27:
https://github.com/graphql/graphql-js/pull/412#issuecomment-229860609

**Comment by nmn** [comment]
There is an option to enable traces in flow, that gives you a stack trace. For performance you have to manually define the trace depth.

**Comment by nodkz** [comment]
@nmn can you point me to this option. I can not found it.

**Comment by nodkz** [comment]
found only this `flow check --traces 5 --json`
output is a something crazy (without --json get holy-crazy). 

It does not help me to determine intermediate lines of code, which was used between type declaration and point of type inconsistency.

So if I have about 5-10 errors, without a case of beer and a ton of free time it can not be processed.

**Comment by nmn** [comment]
@nodkz Flow doesn't run your code. So the current traces is your best option. It can just point you to the type definitions, which already does. You can use something like linter-flow in Atom to get a slightly nicer interface around the whole thing.

**Comment by nodkz** [comment]
This feature may not be actual due landing of new flowtype 0.28
https://flowtype.org/blog/2016/07/01/New-Unions-Intersections.html

Awesome work 😉
