### ISSUE TITLE
Is there an elegance way to express a recursive type like GraphQLType?

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2024]
A Type from `graphql` like this:

```
type GraphQLType =
  GraphQLNamedType|
  GraphQLList<GraphQLType> |
  GraphQLNonNull<
    GraphQLNamedType|
    GraphQLList<GraphQLType>
  >;
```

Ideally, the `GraphQLList` should be narrowed to `GraphQLList<GraphQLType>`, but seems it is resolved to `GraphQLList<any>`(test with the latest 0.27). Is there some way to express a recursive type like this?

**Comment by samwgoldman** [comment]
Can you update this issue with some code that doesn't behave the way you expect? To my knowledge there is no problem with recursive types. I'm not sure what you mean by this statement in particular:

> Ideally, the GraphQLList should be narrowed to GraphQLList<GraphQLType>

**Comment by iamchenxin** [comment]
Seems it is a bug from nuclide.I find that although nuclide display the GraphQLList is GraphQLList<any>, but flow resolved that type to GraphQLList<GraphQLType>.
![fix271](https://cloud.githubusercontent.com/assets/8873545/16539800/41e69cda-403d-11e6-8af1-a5ca00cb3a49.png)

**Comment by ajhyndman** [comment]
It took me a few reads, but I think I understand @iamchenxin now.

I've run into the same issue.  It seems that if nuclide encounters a recursive type or an imported type that it cannot resolve to its most primitive form it will report `any` type instead.

This is certainly better than looping infinitely and crashing the server, but it could be better.  I'd prefer to see the type reported as `unresolved` or `self` - or better, as the non-primitive name of the type that it is attempting to resolve.

**Comment by calebmer** [comment]
This should be fixed in the latest version of Flow. Please reopen with a reproduction on https://flow.org/try/ if you are still having this issue 👍
