### ISSUE TITLE
Class-returning-function breaks nominal typing of instances

### ISSUE THREAD

**Issue by popham** [facebook/flow#2026]
Under the following, Flow considers all `create`ed classes as equivalent.

``` js
function create() {
    return class K {}
}

let A = create();
let B = create();

function fn(K: Class<A>): A {
    return new K();
}
fn(B); // ng, but flow says ok
```

There exists no explicitly annotated analogue to `create` that causes the same problem.

**Comment by vkurchatkin** [comment]
It seems fine. `A` and `B` are produced by the same function, so have the same type

**Comment by popham** [comment]
Sorry for the meh example. Classes are nominally typed. Given `x` that's an instance of `A`, `x instanceof B === false`.

Given the following, Flow flags zero errors:

```js
function create() {
    return class K {
        s(): string { return "one"; }
    }
}

let A = create();
let B = create();

function fn(a: A | string): string {
    if (a instanceof B) { // Flow incorrectly narrows the union type here
        return a.s();
    }
    return a;
}
```

**Comment by vkurchatkin** [comment]
@popham oh, I see.

The thing is that the return type of `create` is `Class<Something>`, and flow assumes that all values of the this type are actually the same value, which is usually true. Also flow allows you to use `A` and `B` as types, although they are not types. This two thing together cause this behaviour.

I think this should be solved by introducing 'structural' classes. For example:

```js
type A = StructuralClass<() => void, {
  s(): string
}>
```

The first parameter is type of constructor, the second is the type of constructed value. Values of this type shouldn't be allowed to use as types, structural type of constructed value should be used instead.

**Comment by popham** [comment]
I just wanted to point out that there exists a path to break the type system.

An explicit interface return type should work someday, e.g. `create(): Class<InterfaceThatMirrorsK>...`. Flow doesn't currently subtype classes, so that will fail when Flow tries to unify the nominal-typed class with the interface, but someday perhaps. My workaround is to trivially extend the created classes, e.g.

```js
let A = class A extends create();
let B = class B extends create();
```

My point is that there exists a path to break the type system. Regardless of a workaround's existence, such a path shouldn't exist.

**Comment by calebmer** [comment]
We are ok with this for now. Nominality is assigned based on the class declaration/expression.

**Comment by popham** [comment]
I currently have a memoizing polymorphic function that depends on this behavior, i.e.

```js
export class PointerList {
  static _specials: { [hash: string]: Class<ByteAlignedList<any>> };
  static of<R: AnyPointer | ByteAlignedList<*> | BoolList>(_R: Class<R>): Class<ByteAlignedList<R>> {
    const hash = _R._hash();
    const cached = this._specials[hash];
    if (cached) {
      return ((cached: any): Class<ByteAlignedList<R>>);
    }

    class List extends ByteAlignedList<R> {
      static _hash(): string {
        return "L("+_R._hash()+")";
      }
      // ...
    }

    return this._specials[hash] = List;
  }
}
```

Can I rely on this pattern?
