### ISSUE TITLE
property `apply` not found on any classes

### ISSUE THREAD

**Issue by jamiebuilds** [facebook/flow#2035]
``` js
class Foo {}
var foo = new Foo();
Foo.apply(foo);
```

```
3: Foo.apply(foo);
       ^ property `apply`. Property not found in
3: Foo.apply(foo);
   ^ statics of Foo
```

I'm currently trying to do this with `Array` in order to port some TypeScript definitions

**Comment by vkurchatkin** [comment]
In theory it's a good thing, since apply won't work with es6 classes

**Comment by thejameskyle** [comment]
[Right](http://www.ecma-international.org/ecma-262/7.0/index.html#sec-ecmascript-function-objects-call-thisargument-argumentslist), I guess I should've focused on the treatment of built-in constructors like Array or Object that can be called with `.call` or `.apply`

**Comment by fibo** [comment]
I am using `React.Component.apply(this, arguments)` for inheritance, flow complains but the code works.

**Comment by SamChou19815** [comment]
Likely we won't support this, since we want to move away from old style classes and more dynamic features of JS.
