### ISSUE TITLE
Helper type for "anything but"

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2039]
With the fixes to union types, I found myself in an odd situation with Promise.try(). The definition:

```js
  static try<R>(fn: () => BluebirdPromise<R>, args?: any[], ctx?: any): BluebirdPromise<R>;
  static try<R>(fn: () => R, args?: any[], ctx?: any): BluebirdPromise<R>;
```

When a function defined in `Promise.try()` returns a value that is a promise, Flow doesn't know which branch to take:

```
271:   return Promise.try(function validateInputs() {
              ^ call of method `try`. Could not decide which case to select
271:   return Promise.try(function validateInputs() {
              ^ polymorphic type: function type
  Case 1 may work:
  424:   static try<R>(fn: () => BluebirdPromise<R>, args?: any[], ctx?: any): BluebirdPromise<R>;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ polymorphic type: function type. See lib: interfaces/promise.js:424
  But if it doesn't, case 2 looks promising too:
  425:   static try<R>(fn: () => R, args?: any[], ctx?: any): BluebirdPromise<R>;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ polymorphic type: function type. See lib: interfaces/promise.js:425
  Please provide additional annotation(s) to determine whether case 1 works (or consider merging it with case 2):
  271:   return Promise.try(function validateInputs() {
                                                     ^ return
```

Is there a way to prefer the first case if it matches, or otherwise refine `R` to be "anything but a `BluebirdPromise`"?

**Comment by mroch** [comment]
this would also be helpful in https://github.com/facebook/flow/issues/2034

**Comment by avikchaudhuri** [comment]
Can't be sure without looking at all the relevant code, but could you try changing the signature of `try` to the following (instead of overloading, use a union):
```
static try<R>(fn: () => BluebirdPromise<R> | R, args?: any[], ctx?: any): BluebirdPromise<R>;
```

**Comment by STRML** [comment]
@avikchaudhuri That does work.

It's strangely important to set the fn's return type as `BluebirdPromise<R> | R`, not `R | BluebirdPromise<R>`, as it appears to simply take the first matching option of the union rather than the most specific matching option.

**Comment by avikchaudhuri** [comment]
Merging with #2212, which tracks the need for docs on the importance of ordering of union cases (and is also a Promise example).
