### ISSUE TITLE
Static methods on an interface

### ISSUE THREAD

**Issue by appsforartists** [facebook/flow#2048]
Say I have an interface I want a class to define, and one of the methods/properties is static.  What's the right way to define that?

I tried this:

``` typescript
export type PlanAndTargetT = {
  plan:PlanT,
  target:mixed
};

export interface PerformerI {
  static canHandle(planAndTarget:PlanAndTargetT):boolean;
  someProperty:string;
}
```

and Flow didn't know how to parse it.  This appears to work, but it seems hacky-at-best:

``` typescript
interface PerformerInstancesI {
  someProperty:string;
}

type PerformerStaticsT = {
  canHandle(planAndTarget:PlanAndTargetT):boolean;
}

export type PerformerI = PerformerInstancesI&PerformerStaticsT;
```

**Comment by nmn** [comment]
ProTip: use ` ```typescript ` at the starting of your code block to get syntax highlighting.

**Comment by vkurchatkin** [comment]
Static methods on interface doesn't make much sense. If you want your class to have some static methods, then you need to create a separate type containing those methods.

**Comment by popham** [comment]
Static methods in ES6 are perfectly analogous to ordinary methods, unlike in Java or C++. Further, they're accessible within ordinary methods through the `constructor` property. It therefore makes perfect sense to support them on interfaces. Submitting pull request.
