### ISSUE TITLE
Incorrect `unreachable code` error with function hoisting

### ISSUE THREAD

**Issue by fizker** [facebook/flow#205]
The following code produces said incorrect error:

```javascript
/* @flow */

function a(a:number) {
	return b(a);

	function b(b) { return b + 1; }
}
```

Function hoisting is the one example where there would be no unreachable code, and it should not fail for this.

The use-case for this is internal helper functions. Since you do not have to read well-named functions to know what they do, I use this pattern a lot to make the main flow understandable (you only have to read to the `return` statement).

**Comment by avikchaudhuri** [comment]
Merging with #125.
