### ISSUE TITLE
flow types stdout as Buffer when it should be string | Buffer

### ISSUE THREAD

**Issue by glortho** [facebook/flow#2051]
In the callback of child_process.exec, the second argument is `stdout`, [which can be a string or buffer](https://nodejs.org/api/child_process.html#child_process_child_process_exec_command_options_callback).

[Flow explicitly types it as a Buffer](https://github.com/facebook/flow/blob/master/lib/node.js#L126), however, so any string methods on `stdout` cause typecheck failure.

**Comment by ryyppy** [comment]
As for the current master, this libdef is fixed now?
https://github.com/facebook/flow/blob/master/lib/node.js#L140

@vkurchatkin Can we close this?

**Comment by vkurchatkin** [comment]
Sure! Although I'm not a fan of this solution, as it makes you perform unnecessary runtime checks
