### ISSUE TITLE
Flow coverage doesn't work with imported types

### ISSUE THREAD

**Issue by nikgraf** [facebook/flow#2053]
```
➜  flow-test git:(master) ✗ flow coverage --color app/components/Events/index.js 
```

![screen shot 2016-07-08 at 17 20 42](https://cloud.githubusercontent.com/assets/223045/16692286/718ac450-4530-11e6-923f-2fc8b0959139.png)

Here the same file /w the Event type directly defined in the same file.

![screen shot 2016-07-08 at 17 21 20](https://cloud.githubusercontent.com/assets/223045/16692316/901fd31a-4530-11e6-84f6-b55f228f221c.png)

I published a test repo where you can try it yourself: https://github.com/nikgraf/flow-test
I'm using flow 28.

**Comment by ryyppy** [comment]
You forgot to annotate the `// @flow` in the beginning of your imported file :-)

**Comment by nikgraf** [comment]
waaaaaaaaaahhhhh, thx @ryyppy
