### ISSUE TITLE
Enforcing second argument to be subset of the first one.

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2055]
I am trying to define a `merge` function where first argument `model` is an arbitrary class or plain object and the second argument `patch` is a record containing subset (or all) of the fields from `model` type. I would like to define it such that flow will be able to detect type mismatches between `model` and `patch` fields if they occur. Here is my attempt to implement this:

``` js
/* @flow */

declare function merge <patch, model:patch & *>
  (state:model, changes:patch):model

export type Model = {
  value: string
}

const clear = (model:Model):Model =>
  merge(model, {value: null})
```

I would expect flow to error due to type mismatch of the `value` field when calling `merge` in the function `clear`. Instead flow reports no errors. I'm testing on my machine with 0.27.0 and on on try flow, presumable it runs latest & greatest:

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsAWy0IHMSAeAB32pwAWAGmZxsMAFy9+AsADJkAPlRgwACgDO1PlglMxWGCMH4KHDVL6CAlHoMx0WAB7c4hamGoBPbiQCy9mAAvGAA3ipgAG74MGS6YFqEtGaoAL7oOAxaYHhYRMHq+uISAeK2pYbByqos7FhqRYYiodGx8RRkMDCp1qhAA

**Comment by Gozala** [comment]
Got a response from @marudor on IRC:

> 10:32 AM <marudor> <model, path: $Shape<model>>(state: model, change: path) => model
> 10:35 AM  → bhosmer joined  ⇐ rmg_ quit  
> 10:39 AM <gozala> marudor: what dose that $Shape<model> mean ?
> 10:39 AM <marudor> $ indicates its private
> 10:39 AM <marudor> $Shape means something that has the shape of model
> 10:40 AM <marudor> as in subset.
> 10:40 AM <marudor> If it includes a specific property it has to be just like the one typed

And it seems to work as expected with a following changes:

```js
/* @flow */

declare function merge <model, patch:$Shape<model>>
  (state:model, changes:patch):model

export type Model = {
  value: string;
  selectionDirection: 'forward' | 'backward' | 'none';
}

const clear = (model:Model):Model =>
  merge(model, {value: null})
```

I get following errors:

```
12:   merge(model, {value: null})
                           ^ null. This type is incompatible with
7:   value: string;
            ^ string
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsAWy0IHMSAeJubGAGjAAHfNRwALAFwASAMrj8QrN15YYAPnWowYABQBnaqKySefQRPwUO+ySLHiAlKdUx0WAB5C4hamGoAnkpgALKuYAC8YADe2mAAbvgwZCZghoS01gDccfpquHQMACK0xDT0FJJgAORQPghEGNVgAD41AEb4OADWDYRNrTUUDFjVOQC+6DgMhmB4WESRemZqkmF8zutqkVo6LOxYuisCMYnJqRRkMDDjjqhAA

**Comment by Gozala** [comment]
Can `$Shape` be documented and demystified ?

**Comment by gkz** [comment]
`$Shape` is documented, but also now deprecated in favor of `Partial`, which is also documented.
