### ISSUE TITLE
intersection of Function Types not working correctly.

### ISSUE THREAD

**Issue by nmn** [facebook/flow#2059]
Steps To Reproduce: 

``` typescript
type NumberXString = ((value: number) => string) & ((value: string) => number)

var numberXString: NumberXString = (value: number | string) => {
    if (typeof value === 'string') {
        return 1
    }
    return String(value)
}
```

Currently flow shows errors on all the return types and values. But there should be no errors.
I'm looking at different ways to write this, to maybe make it work correctly.

**Comment by avikchaudhuri** [comment]
This is currently not possible, because the return type of the arrow
function has to be fixed. The type being inferred is number | string, the
correlation between input and output is lost. Might support this pattern
eventually, it's an ongoing problem we occasionally think about, and were
actually thinking about quite recently too...

**Comment by alexeygolev** [comment]
@avikchaudhuri is it only relevant for an arrow function? This doesn't seem to work properly either
```js
const numberXString: NumberXString = function (value: number | string) {
  if (typeof value === 'string') {
    return 1
  }
  return String(value)
}
```

**Comment by avikchaudhuri** [comment]
No sure the problem is not specific to arrows, just that the original
example used it.

**Comment by nmn** [comment]
@avikchaudhuri So is it safe to assume that any function that's actually written needs to have a fixed return type for now? So, if we have a need for functions that maintain correlation between input and out arguments, (mostly to keep type safety when passing values through such functions) which of these are valid approaches?

1. Try to make it work with generics, where there is a fixed return typed using a generic type. (works is some cases)
2. Do what I did in the example, and suppress all the errors.
3. Write these sort of functions in untyped modules, and declare their types in a `.js.flow` file separately.

**Comment by avikchaudhuri** [comment]
If generics work, go for it. Otherwise maybe type check the function in
isolation with whatever inferred return type Flow thinks of, then double
cast the function to the intersection type via any.

Meanwhile I'll take a quick crack at this and report back next week.

**Comment by nmn** [comment]
Just to confirm, you mean something like this? :

```typescript
type NumberXString = ((value: number) => string) & ((value: string) => number)

var numberXString = (value: number | string): number | string => {
    if (typeof value === 'string') {
        return 1
    }
    return String(value)
}

module.exports = ((numberXString: any): NumberXString)
```

**Comment by avikchaudhuri** [comment]
FYI the plan is to not make this work via cast (subtyping doesn't work that way) but have a way to directly declare an overloaded type for the definition. TBD.

**Comment by billyjanitsch** [comment]
Hi @avikchaudhuri and @nmn! Sorry to resurrect an old issue, but I'm wondering why it was closed. As far as I can tell, this is still an issue in the latest Flow, and there is still not a way to directly define an overloaded function. Am I missing something, or has the discussion moved elsewhere?

**Comment by zeorin** [comment]
Interfaces seem to have the behaviour you're looking for: https://github.com/facebook/flow/issues/3021#issuecomment-404156975.
