### ISSUE TITLE
Publish v0.1.3

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#206]
It looks like the following download locations still only have v0.1.2:

* http://flowtype.org/downloads/flow-osx-latest.zip (used by the flow-bin NPM package)
* https://github.com/facebook/flow/releases

It also looks like OPAM still only has v0.1.0: https://opam.ocaml.org/packages/flowtype/flowtype.0.1.0/

**Comment by unknownexception** [comment]
+1

**Comment by tcoopman** [comment]
When published, it would be nice if you could use versioned binaries for flow-bin (#71)

**Comment by gabelevi** [comment]
Sorry, this was my fault. Looking into getting these built and published.

**Comment by thomasboyt** [comment]
this was fixed :+1:

**Comment by popham** [comment]
Given a fresh `opam install flowtype`, I get "Flow, a static type checker for Javascript, version 0.1.0" from `flow --version` :(

I've confirmed that 0.1.0 is still the only version on https://opam.ocaml.org/packages/

**Comment by popham** [comment]
I just did the ol' `git clone https://github.com/facebook/flow.git && cd flow && make`.  How about a `package.js` with `private : true` and binary paths so that `npm link` exposes flow to the scripts in `package.js`?


When I get around to it I'll create a `package.json` with the binaries path set so that I can `npm link` flow into my projects and execute flow commands with `npm run x` for flow scripts

**Comment by gabelevi** [comment]
@avsm was kind enough to set up the opam package and we've neglected to keep it updated. I've just submitted a [PR to update the opam package to v0.3.0](https://github.com/ocaml/opam-repository/pull/3570) and I'll try to update it with each release. Sorry about that!

To be clear about the `package.json`, what you'd like is to be able to do
`git clone https://github.com/facebook/flow.git && cd flow && make && npm link`

What scripts do you want to expose Flow to? I'm not 100% sure what you mean.

**Comment by popham** [comment]
`npm init` generates a `package.json` that contains

```
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
```

Given a key `someScript` in the `scripts` object, I can run the corresponding script with `npm run someScript`.  I want to call run `flow` from these scripts, e.g. `someScript: "flow check asdf.js"`.

`npm` adds any exported binaries to the path during `npm run someScript`, so if `flow` included a `package.json` with

```
    name: "flow",
    bin: ["bin/flow"],
    private: true,
```

then I could build `flow` anywhere, run `npm link` from `flow`'s root directory, and then run `npm link flow` from within any project that I want to use it with, project `x` for instance.  Presuming an `npm link flow` for project `x`, the scripts section of `x/package.json` could contain the string `"flow check asdf.js"` and just work.  (One time calls like `flow init` would be a little tricky, requiring `flow-init` boilerplate within `scripts` or more reasonably a one time call of `x/node_modules/.bin/flow init`.)

**Comment by avsm** [comment]
@gabelevi I'm not too familiar with NPM, but if it helps it's quite easy to add a `make cold` target to flow that bootstraps OPAM entirely within the repository (including the OCaml compiler if necessary).  The final output binary could then be linked to NPM.  @jordwalke also has some thoughts on this at Facebook.
