### ISSUE TITLE
Logo is too large in the toolbar

### ISSUE THREAD

**Issue by jamesgpearce** [facebook/flow#2063]
![image](https://cloud.githubusercontent.com/assets/90942/16717513/c161894a-46cb-11e6-94a5-ef4165f16824.png)

(I think there should be margin above and below like https://facebook.github.io/react/ ;) )

**Comment by matthewjohnston4** [comment]
It looks to me that this was done intentionally as the proper flow logo has been cropped like this here: https://flowtype.org/assets/flow-logo.png

**Comment by mroch** [comment]
yeah, the full bleed is intentional
