### ISSUE TITLE
dynamic type tests don't work in ternary operator

### ISSUE THREAD

**Issue by f1qwase** [facebook/flow#2069]
here is an example
```javascript
const stringFunc = (x: string) => null;
const numberFunc = (x: number) => null;

// this works
const ifElse = (a: string | number) => {
    if (typeof a === 'string') {
        return stringFunc(a);
    }
    else {
        return numberFunc(a);
    }
}

// this gives error "string: this type is incompatible with number"
const ternary = (a: string | number) =>
    a === 'string' ? stringFunc(a) : numberFunc(a);
```

[live example](https://tryflow.org/?code=LyogQGZsb3cgKi8KY29uc3Qgc3RyaW5nRnVuYyA9ICh4OiBzdHJpbmcpID0+IG51bGw7CmNvbnN0IG51bWJlckZ1bmMgPSAoeDogbnVtYmVyKSA9PiBudWxsOwoKLy8gdGhpcyB3b3Jrcwpjb25zdCBpZkVsc2UgPSAoYTogc3RyaW5nIHwgbnVtYmVyKSA9PiB7CiAgICBpZiAodHlwZW9mIGEgPT09ICdzdHJpbmcnKSB7CiAgICAgICAgcmV0dXJuIHN0cmluZ0Z1bmMoYSk7CiAgICB9CiAgICBlbHNlIHsKICAgICAgICByZXR1cm4gbnVtYmVyRnVuYyhhKTsKICAgIH0KfQoKLy8gdGhpcyBnaXZlcyBlcnJvciAic3RyaW5nOiB0aGlzIHR5cGUgaXMgaW5jb21wYXRpYmxlIHdpdGggbnVtYmVyIgpjb25zdCB0ZXJuYXJ5ID0gKGE6IHN0cmluZyB8IG51bWJlcikgPT4KICAgIGEgPT09ICdzdHJpbmcnID8gc3RyaW5nRnVuYyhhKSA6IG51bWJlckZ1bmMoYSk7Cg==)

**Comment by BlooJeans** [comment]
You missed a 'typeof' in your ternary
```javascript
const ternary = (a: string | number) =>
  typeof a === 'string' ? stringFunc(a) : numberFunc(a);
```

**Comment by f1qwase** [comment]
shame on me
