### ISSUE TITLE
Assigning to less restrictive type leads to unexpected error, with bad error message

### ISSUE THREAD

**Issue by kolman** [facebook/flow#2072]
Example:

```
/* @flow */

export type Address = {
  name: string;
  street: string;
};

export type IncompleteAddress = {
  name: string;
  street?: string;
};

function foo(x: Address) {
  const y: IncompleteAddress = x;
}
```

leads to error:

```
10:   street?: string;
               ^ undefined. This type is incompatible with
5:   street: string;
             ^ string
```

First, the error message is missing information that the issue is inside the function, when assigning x to y. If you delete the function, validation passes, but lines 10 and 5 are in the type definitions, not inside the function.

Second, it should pass, as x.street will be always defined, which should satisfy y.street.

**Comment by kolman** [comment]
I found a workaround. When using spread instead of assigning, it works:
```
const y: IncompleteAddress = {...x}; // no error
```
The same works for function calls:
```
function bar(x: IncompleteAddress){
}

function foo(x: Address) {  
  bar(x); // the same error as in the first post
  bar({...x}); // no error
}
```

**Comment by vkurchatkin** [comment]
This is expected behaviour. When you assign `Address` to `IncompleteAddress`, it makes it possible to delete `street` property, so it's forbidden.

**Comment by kolman** [comment]
OK, makes sense. The error message should point to the line where assignment is made (line 14 in the first example), it is quite hard to spot it in larger codebase.

**Comment by samwgoldman** [comment]
Flow will now point to the location of the assignment, which makes it a lot easier to see what is going wrong:

```
Error: test.js:14
 14:   const y: IncompleteAddress = x;
                                    ^ object type. This type is incompatible with
 14:   const y: IncompleteAddress = x;
                ^^^^^^^^^^^^^^^^^ object type
  Property `street` is incompatible:
     10:   street?: string;
                    ^^^^^^ undefined. This type is incompatible with
      5:   street: string;
                   ^^^^^^ string
```
