### ISSUE TITLE
Intersection fails if more specific type comes last

### ISSUE THREAD

**Issue by appsforartists** [facebook/flow#2074]
Consider these types:

```javascript
type SpecificFirstT = { target:Element }&{ target:mixed };
type SpecificLastT =  { target:mixed   }&{ target:Element };
```

Since an intersection requires a value to suit all of the types, those should both be equivalent to `{target:Element}`.  However in practice, Flow will treat `target` as `mixed` for `SpecificLastT` and as `Element` for `SpecificFirstT`.

Here's [a diff](http://codereview.cc/D1203#cbc9784c) that shows this bug in practice.  `PlanAndTargetT` has `target` set to `mixed` because different Performers may take different targets.  However, for any particular Performer, I know exactly which type of `target` it should take, and want to be able to annotate accordingly.

`specificT&genericT` and `genericT&specificT` should be equivalent.

**Comment by avikchaudhuri** [comment]
This is a design choice. Intersections and unions are necessarily ordered to make the process of selecting the best match predictable. In general, it is not easy to order types according to precision, so selecting a best match is not always possible.

**Comment by appsforartists** [comment]
Can we at least make that clear [in the docs](https://flowtype.org/docs/union-intersection-types.html)?  I only found the workaround through happenstance.
