### ISSUE TITLE
Regression: Template literals can no longer include non-strings.

### ISSUE THREAD

**Issue by LegNeato** [facebook/flow#2076]
This code:

```js
throw new Error(`NODE_ENV set to invalid value: ${process.env.NODE_ENV}.`);
```

Gives the error:
```js
 21:   throw new Error(`NODE_ENV set to invalid value: ${process.env.NODE_ENV}.`);
                                                         ^^^^^^^^^^^^^^^^^^^^ undefined. This type cannot be added to
 21:   throw new Error(`NODE_ENV set to invalid value: ${process.env.NODE_ENV}.`);
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
```

Which isn't correct...that should be fine I think? Previous `flow` versions did not complain, but I started seeing these after I upgraded to:

```
Flow, a static type checker for JavaScript, version 0.28.0
```

**Comment by alexeygolev** [comment]
Change log mentions this:
```
Variables in template literals are now subject to the same rules as variables being concatenated with a string using +. This may surface template strings with variables that may not safely coerce to a string
```

**Comment by LegNeato** [comment]
Ah, missed that.

These seems not ideal...can't `undefined` be coerced safely? What about `boolean`? (I'm seeing similar stuff with boolean). Is current js behavior with these types explicitly defined (`undefined` -> `''`, `boolean` -> `'true' | 'false')?

**Comment by arv** [comment]
Sad.

Why isn't boolean considered safe?

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAodBjOA7AzgFzACMAuYuOGAUwENswBeMKGmXKgblSz0OzOwBXALZEqAJ0ZgALACYuPAmFxkC4gJbYA5lIAGNACQBvIgF8Mx7KYAmujkA

**Comment by thejameskyle** [comment]
@arv It's less about being safe than it is about being intentional. When Flow was allowing coercion people were putting things into strings by mistake. By requiring it to be explicit we surface these issues.

**Comment by samwgoldman** [comment]
Yeah, @thejameskyle is absolutely right. I just want to add that this change made string concatenation with `+` and string concatenation with template literals consistent. We are still open to changing the rules for both. For example, we don't require explicit casts for numbers, because patterns like `0 + "%"` are so incredibly common. We're not so stuck in our ways :)
