### ISSUE TITLE
Question: Feasible to use Flow without annotations?

### ISSUE THREAD

**Issue by rkistner** [facebook/flow#2077]
Is it feasible to use Flow for basic type checking and autocomplete without adding any type annotations?

I'm assuming:
1. Only a single source file (without annotations).
2. All libraries have annotations.
3. The script does not export any functions.

Are there any pitfalls, where it is not feasible to pass all the checks without adding type annotations?

Background: I'm working on an online script editor, and I'm currently using TernJS for type checking and autocomplete. I'm now investigating using Flow as an alternative, but do not want to require the users to learn about Flow's type annotations.

**Comment by avikchaudhuri** [comment]
It should be possible, yes. As long as you don't export anything you shouldn't need annotations...except when your libraries have union types, in which case some annotations may be needed to type check.

**Comment by rkistner** [comment]
Thanks - I'll start to work on a proof-concept soon. I'll update here when I have something working, but closing the issue for now.
