### ISSUE TITLE
dynamic test doesn't work

### ISSUE THREAD

**Issue by f1qwase** [facebook/flow#2078]
The code below raise an error while it hasn't, because `degree` cannot be `null` on line 9
```javascript
const nthRoot = (x: number, degree: number) => Math.pow(x, 1/degree);

const bindDegree = (degree: ?number) => {
    if (degree == null) {
        return Math.sqrt;
    }
    else {
        return x => nthRoot(x, degree);
        //                     ======
        // here i got an error "null: this type is not compatible with number"
    }
}
```
I found workaround for this case: replacing `degree` with `degree + 3` in line 9 disappears error. So the modified code below does not raise errors.
```javascript
const nthRoot = (x: number, degree: number) => Math.pow(x, 1/degree);

const bindDegree = (degree: ?number) => {
    if (degree == null) {
        return Math.sqrt;
    }
    else {
        return x => nthRoot(x, degree + 3);
    }
}
```

**Comment by avikchaudhuri** [comment]
Unfortunately this is a limitation of the type system: Flow has to conservatively forget refinements of variables inside closures because it doesn't know whether they would be called later, when those refinements no longer hold.

Consider the following variation of your example:
```
const nthRoot = (x: number, degree: number) => Math.pow(x, 1/degree);

const bindDegree = (degree: ?number) => {
    var f = Math.sqrt;
    if (degree != null) {
        f = x => nthRoot(x, degree);  // degree can indeed be null depending on when it is called!
    }
    degree = null;
    f(0);
    return f;
}
```

Your second example works because we allow `null + number`, yielding `number` (`null` gets converted to `0`).

Here's a workaround for your example:

```
const nthRoot = (x: number, degree: number) => Math.pow(x, 1/degree);

const bindDegree = (degree: ?number) => {
    if (degree == null) {
        return Math.sqrt;
    }
    else {
        const degreeNumber = degree;
        return x => nthRoot(x, degreeNumber); // ok
    }
}
```

**Comment by syrnick** [comment]
This argument doesn't quite apply to a function argument that is never re-assigned or anything `const`. If the value is const, the closure can inherit type refinements.

Please re-open the issue.
