### ISSUE TITLE
Flow should catch invalid cases when matching over tagged unions

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2079]
Consider following example:

``` js
/* @flow */

type Message =
  | { tag: "Inc" }
  | { tag: "Dec" }

const update =
  (model:number, message:Message):number => {
    switch (message.tag) {
      case "Inc":
        return model + 1
      case "Dec":
        return model - 1
      default:
        throw Error('Invalid message')
    }
  }
```

Everything works as expected and flow type checks fine. Then after a month and some refactoring we end up with a following code:

``` js
/* @flow */

type Message =
  | { tag: "Increment" }
  | { tag: "Decrement" }

const update =
  (model:number, message:Message):number => {
    switch (message.tag) {
      case "Increment":
        return model + 1
      case "Dec":
        return model - 1
      default:
        throw Error('Invalid message')
    }
  }
```

Flow type checks fine, but there is an error, author forgot to update `case "Dec"` to `case "Decrement"` and there for runtime error will occur. Please note that this closely related to #1835 and  #451 but not the same. While in this case `default` case is just a workaround, there could be valid cases where default case is required. I think flow should handle such errors, maybe via opt in pref or somewhat different pattern matching pattern.

**Comment by steelbrain** [comment]
Friendly bump :)

**Comment by TrySound** [comment]
Fixed
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyeAziQIYDmBAvKmGAD5gDeYGVAXGAEQCSAOwDGAJzwBbPAIw8wAX3pNW7LrwAieURKkz56IXAEkMYAK44AJuQy1FACnFwLeGJwGnxAIzwiANGEkyKjxOYiDqAEo3D28RMBoAPlZFBhIEAEsMIQALMAdSCmoAOg5KCOSGSrAhchICfmExSWkeThSqsDEMUxEBAKcXMABqMABGdoYauvVNVonKrp6+x2cYMABaMfnnKHJTGAw2jsqMbJFEMABREXOROwByQQA3chh0iwCC4PuI9oUGORAA
