### ISSUE TITLE
Dump type annotations as JSON?

### ISSUE THREAD

**Issue by tmcw** [facebook/flow#208]
Would it be possible to have a [tern-like feature](http://ternjs.net/doc/manual.html#typedef) which would dump all parsed definitions as a JSON object from the `flow` server?

**Comment by gabelevi** [comment]
Hmm...we are slowly building out APIs for querying the Flow server for code-intelligence sorts of things. For example, there is `flow autocomplete`. It's still pretty early, though.

What query specifically are you looking for? What is the type information we know about an expression at a particular location? Or what local variables are in scope at a loc and what are they're types?

**Comment by tmcw** [comment]
I'd like to be able to use flow in a similar way to how [immutable-js](https://github.com/facebook/immutable-js) uses typescript annotations to generate documentation - point it at a module, get all typing information and exported functionality as JSON, and generate things from that data.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by STRML** [comment]
It may be useful to you to check out [runtime-types](https://github.com/seanhess/runtime-types), which can dump a JSON object of parsed types.

I'm actually looking as well for something that can do the opposite - download JSON schemata from e.g. a database and build a Flow object typedef out of it.

**Comment by tmcw** [comment]
Thanks for the discussion! I'm finding that babel's type parsing is perfectly good for my usecase!
