### ISSUE TITLE
missing /website/_assets/js/flow.js

### ISSUE THREAD

**Issue by zhenyong** [facebook/flow#2081]
I follow [README](https://github.com/facebook/flow/tree/3b750cae36be558c2198791ea6883520384183ac/website) under /website to install and see errosr:

```
      GitHub Query: releases for facebook/flow
                    couldn't find file 'flow.js'
  Liquid Exception: couldn't find file 'flow.js' in try/index.html
jekyll 3.1.6 | Error:  couldn't find file 'flow.js'
```

## solved
I download flow.js from `https://flowtype.org/assets/flow.js` and put into `/website/_assets/js/`, then fixed

**Comment by mroch** [comment]
this file is built from source via `make js` (from the root dir, not /website) and then needs to be copied from `bin/flow.js` to `_assets/js/flow.js`. IMO we should add a Makefile to `website/` that does this as part of `make` or `make serve` or whatever.

**Comment by zhenyong** [comment]
@mroch I get it. Thanks so much.

**Comment by STRML** [comment]
Now that `gh-pages` is dead, is there any automated process left for updating `flow.js` when a new revision comes out? The current live version on https://flowtype.org/try/ appears to be a few releases old.

**Comment by mroch** [comment]
@STRML it's updated by Travis automatically and tracks master. seems to be up to date right now, but maybe Travis was failing for a while when you looked?

**Comment by STRML** [comment]
Thanks - perhaps a README in the folder should indicate this? I must have just caught a fluke.
