### ISSUE TITLE
Stdin/stdout communication with flow server

### ISSUE THREAD

**Issue by howareyouman** [facebook/flow#2083]
It will be grate to send files (override disk content) directly to server.

**Comment by avikchaudhuri** [comment]
We get this feature request often, especially from those working on editors. For now there is `flow check-contents` using which you can send over arbitrary contents (but those contents are only checked, not persisted in any way, by the server). From the help:

```
Usage: flow check-contents [OPTION]... [FILE]

Runs a flow check on the contents of stdin. If FILE is provided, then
check-contents pretends that the contents of stdin come from FILE

e.g. flow check-contents < foo.js
or   flow check-contents foo.js < foo.js
```

**Comment by howareyouman** [comment]
Just to clarify you understand our request correctly: our editor can have several unsaved files simultaneously, and to perform check, we have to send all unsaved files content to server. Currently, we can send only one.

**Comment by SamChou19815** [comment]
You can now communicate with the Flow server with LSP protocol. However, we are unlikely to support any other protocols.
