### ISSUE TITLE
Flow error result text is cut off in terminals

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/flow#2085]
Both Terminal and iTerm on Mac. 
Font: SF Mono 18pt. 

<img width="993" alt="screen shot 2016-07-14 at 11 29 35 am" src="https://cloud.githubusercontent.com/assets/95672/16845282/5997bde6-49b6-11e6-828a-4b9fc3b915a6.png">

<img width="1150" alt="screen shot 2016-07-14 at 11 29 52 am" src="https://cloud.githubusercontent.com/assets/95672/16845287/5d282176-49b6-11e6-9602-fcdd4c6382eb.png">

**Comment by avikchaudhuri** [comment]
Could you please clarify which text you think is cut off? The attached output looks normal to me, what am I missing? (The third and fifth line are part of the same sentence explaining the error.)

**Comment by kevinSuttle** [comment]
I've since refactored this code, but it's supposed to say "this type cannot be added to **props**". It shows up fine in the status bar of Atom, etc. when linters run.

**Comment by mrkev** [comment]
This has since been fixed
