### ISSUE TITLE
Can't install flow-bin@0.28.0

### ISSUE THREAD

**Issue by vtomole** [facebook/flow#2089]
I typed: npm install flow-bin@0.28.0
In my terminal and I got 
/usr/bin/env: ‘node’: No such file or directory

**Comment by avikchaudhuri** [comment]
Probably `node` is not in your path? See https://github.com/nodejs/node-v0.x-archive/issues/3911 if it helps.

**Comment by vtomole** [comment]
It works now, Thanks!
