### ISSUE TITLE
How to build code with flow "correctly" before pushing to npm?

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#2095]
This is a little vague question, but I have to ask it.

I have a code with Flow type annotations, that I want to put into a package and push to npm repository.

I want people, who don't use Babel and don't have transform-flow-strip-types babel plugins installed to be able to just require my package and use it outright. On the other hand, I want people who *do* have flow to be able to typecheck against my annotations.

How to do that correctly? Is that even possible?

The only think I can think of is to build it with browserify and babelify, and add `.js.flow` annotation that I will make by hand, but that is not effective.

**Comment by avikchaudhuri** [comment]
@jeffmo What workflow do you recommend?

**Comment by vkurchatkin** [comment]
Here is a script that we use: https://github.com/sim-sys/node-template/blob/master/Makefile#L89-L97

Basically, it  compile files with babel and also copies originals with `.flow` extension

**Comment by runn1ng** [comment]
Oh, that works too? That sounds great

**Comment by runn1ng** [comment]
Closing this issue, I didn't realize you can just copy the `.js` files as `.js.flow`.
