### ISSUE TITLE
Typescript parity: allowing modification of built-in types

### ISSUE THREAD

**Issue by opensrcken** [facebook/flow#2096]
Is there a way to extend a built-in type in Flow? If not, I believe there should be. Though it may not be the most desirable pattern, there's no arguing that it is common in the JS world:

https://tryflow.org/?code=Y29uc3QgcCA9IG5ldyBQcm9taXNlKChyZXNvbHZlLCByZWplY3QpID0+IHsKICAgIHJlc29sdmUoNSk7Cn0pOwpwLnRoZW4odiA9PiBjb25zb2xlLmxvZyh2KSk7CnAuZmluYWxseSgoKSA9PiB7IGNvbnNvbGUubG9nKCJISSEiKTsgfSk7

This is how Typescript exposes such a capability to users: http://stackoverflow.com/questions/16816414/extending-instance-static-functions-on-existing-prototypes-with-typescript/28020863#28020863

**Comment by avikchaudhuri** [comment]
You can shadow a built-in type by creating your own lib defs (and pointing to it in the `[libs]` section of your `.flowconfig`, see [here](https://flowtype.org/docs/declarations.html#pointing-your-project-to-declarations): simply copy something from the core defs and add more stuff to it, and it will shadow core defs.

Being able to define them in parts is not a can of worms we'd like to open right now, especially given how Flow works...it doesn't make any assumptions of analyzing parts of your code in any given order (except for the rule that user libs override core libs, made especially for this use case).
