### ISSUE TITLE
Cannot setState to value that was initially null - type is incompatible

### ISSUE THREAD

**Issue by Foxhoundn** [facebook/flow#2098]
There is a modal manager I am transferring to flow in our codebase and it has an initial state - 

``` javascript
state = {
  modal: null,
}
```

When the app changes the state - adds a react element to the modal state value - flow errors with 

``` javascript
169:         this.setState({ modal: lastModal });
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method setState
169:         this.setState({ modal: lastModal });
                                    ^^^^^^^^^ React$Element. This type is incompatible with
 27:     modal: null,
                ^^^^ null
```

The state is typed as follows

``` javascript
state: {
  modal: ?React.Element<any>,
};
```

**Comment by avikchaudhuri** [comment]
As a workaround, please cast `null` to the appropriate type, like
```
state = {
  modal: (null: ?React.Element<any>),
}
```

Let us know if it doesn't work. Also, where does the above line appear?

**Comment by Foxhoundn** [comment]
@avikchaudhuri that worked, although I don't like having so much boilerplate. Why isn't the state type declaration taking this into context?

Thanks

**Comment by AugustinLF** [comment]
Any news on that? I stumbled onto this case too, here is a small [example](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChS0AbFAZxrgGFdIA7JF+JADxnYBN6ydDAB0TcBDYc4Ab1Jw48uDRgpeALlnA+mgPwsAriABGSKAF8lSlWqRwAvFp1xDlSpYUKlaZpPYwAEW0AWQgDDgAKAEpZJQBIGAALYBoRGiQYAGVVXgiZbU0ARnMopUtzIA). @avikchaudhuri's workaround does work, but is that really normal?

**Comment by AugustinLF** [comment]
This works as expected in 0.53, it can be closed.
