### ISSUE TITLE
Checking `!== undefined` should suffice for an optional argument

### ISSUE THREAD

**Issue by spicyj** [facebook/flow#21]
This code doesn't type-check:

```
/* @flow */

function foo(x?: string): string {
    if (x !== undefined) {
        return x;
    }
    return "meow";
}
```

Changing the conditional to `x != null` makes the code work, but I believe checking against undefined should suffice because the argument type itself isn't nullable. Also: `!= undefined` doesn't work even though it has the same meaning as `!= null`.

**Comment by gabelevi** [comment]
@avikchaudhuri fixed this awhile back when he revamped optional types in v0.2.0. Sorry for forgetting to close out the issue!
