### ISSUE TITLE
incompatible types when using inline polymorphic function

### ISSUE THREAD

**Issue by jlongster** [facebook/flow#2103]
This works:

``` js
function add<T>(x: T) : T {
  return x + 1;
}

function foo(func) {
  return func(5);
}

foo(add);
```

But this doesn't:

``` js
function foo(func: <T>(arg: T) => T) {
  return func(5);
}

foo(x => x + 1);
```

It gives the following error:

``` js
 47: foo(x => x + 1);
              ^^^^^ +
 47: foo(x => x + 1);
              ^^^^^ mixed. This type is incompatible with
 47: foo(x => x + 1);
         ^^^^^^^^^^ some incompatible instantiation of `T`
```

I would have expected them to be semantically equivalent. This is part of a bigger goal to get this working: https://gist.github.com/jlongster/80daed0621243919428c90254858b4b3. But I clearly don't understand how inline arrow functions work with polymorphism.

**Comment by avikchaudhuri** [comment]
@jlongster The fact that the former example works is a known hole in the typing of `+` combined with how bodies of polymorphic functions are checked. Will fix.

**Comment by jlongster** [comment]
@avikchaudhuri great, thanks. If it's known is there an existing issue we can dupe to?

**Comment by vkurchatkin** [comment]
This issue issue seems obsolete. In Flow 0.56.0 both examples don't work and provide sensible error messages.
