### ISSUE TITLE
npm flow-parser module not working

### ISSUE THREAD

**Issue by nzakas** [facebook/flow#2104]
I just tried using the `flow-parser` module on npm, and I think it's not working correctly. When I call `parse()`, it returns a function rather than an AST (and the function throws an error if called).

```js
var x = require("flow-parser")

console.log(x.parse("var x:string = 'hi';"));    // function
```

See it live:

https://tonicdev.com/578fbe8f5349241300bc2347/578fbe8f5349241300bc2348

I'm guessing this isn't the way it's intended to be used, but wanted to double-check just in case.

(Tested on Node 4 and 6)

**Comment by avikchaudhuri** [comment]
cc @gabelevi

**Comment by jeffmo** [comment]
You'll need to specify a second param for the options object due to the way js_of_ocaml is generating the function:

https://tonicdev.com/jeffmo/578fcf4220045d120024f9cc

**Comment by nzakas** [comment]
Ah ok, perhaps it would make sense to add that information in the readme?

**Comment by jeffmo** [comment]
@nzakas: Not a bad idea... Let me see if I can find a way to actually just make the second param "optional" first
