### ISSUE TITLE
Declare types for Promises ?

### ISSUE THREAD

**Issue by rogergl** [facebook/flow#211]
That is how my declaration looks.

```javascript
declare class Promise$Type {
    all(promises: Object): void;
    then(result: Function, err: Function): void;
}

declare function Promise(callback: (resolve: Function, reject: Function) => void): Promise$Type ;

declare module "es6-promise" {
	declare var Promise: Promise;	
}
```

The problem is that the following code passes the flow check call:

```javascript
var test = Promise(function(resolve, reject) {});
test.then1(function(d) {

});
```

**Comment by rogergl** [comment]
There seems to be some overlapping with #213.  flow check succeeds if the 'es6-promise' module is not installed. Otherwise I get 'Required module not found'.

**Comment by samwgoldman** [comment]
Support for promises is built in. You shouldn't need to declare anything on your own. Are you still having this issue?

**Comment by samwgoldman** [comment]
Please reopen if this is still an issue for you. Thanks!
