### ISSUE TITLE
Extend type in class

### ISSUE THREAD

**Issue by fb55** [facebook/flow#2114]
I'm trying to build models that accept subtypes of themselves* as constructor arguments. Basically as a base class (which doesn't work as `this` can only occur covariantly):

```js
class BaseClass<T> {
  constructor(obj?: this) {  }
}
```

Another idea was to specify that a class inherits all properties of a type. The obvious

```js
class BaseClass<T> extends Class<T> {
  constructor(obj?: T) {  }
}
```

does not work, as `Class<T>` can't be resolved (as it isn't an actual JS value).

Is there a nice way to implement this, or do I need to resort to declarations or duplicated types?

---

\* or `$Shape`s of the subtypes, but that isn't the issue here

**Comment by freebroccolo** [comment]
Something like this?

```javascript
class Base {
  constructor<T: Base>(obj?: T): this {
    return this;
  }
}
class Ext extends Base {
}
const ext = new Ext();
const foo = new Base(ext);
```

**Comment by freebroccolo** [comment]
Oh, if you mean you want this generically for each classes in an inheritance chain, I don't think there's a way to do that currently.

You *might* be able to put together a solution with some combination of class expressions and intersections but I suspect it'd be too much trouble. You'd probably end up losing whatever advantage there was to using classes to begin with.

I think a mostly structural approach (using interfaces and intersections) will end up being a lot easier to work with here than a nominal approach (using classes).

**Comment by fb55** [comment]
Thanks a lot @freebroccolo!
