### ISSUE TITLE
Server/client mismatch case sensitive URLs

### ISSUE THREAD

**Issue by steelsojka** [facebook/flow#2117]
I'm getting this error when running flow@0.29.0 locally on MacOSX:

server_root: /Users/soj214/Projects/ngoms-ui-flow, client_root: /users/soj214/Projects/ngoms-ui-flow
Unhandled exception: CommandExceptions.Server_directory_mismatch

I assume this has to do with macs case insensitive file system. Is there a current solution/configuration for this?

**Comment by avikchaudhuri** [comment]
cc @gabelevi

**Comment by ubershmekel** [comment]
I'm getting this on windows:

```
flow is running on a different directory.
server_root: e:\1stuff\dev\javascript\tags\webapp, client_root: E:\1stuff\dev\javascript\tags\webapp
Unhandled exception: CommandExceptions.Server_directory_mismatch
```

**Comment by YongX** [comment]
+1 on my mac.
server_root: /Users/xiangyong/WebstormProjects/test, client_root: /Users/xiangyong/webstormprojects/test

**Comment by lednhatkhanh** [comment]
+1, facing this error on windows, any news?

**Comment by peterjoel** [comment]
I saw this issue in Git Bash on Windows. However, it works when I switched to Windows PowerShell.

**Comment by burdiuz** [comment]
Have identical paths except of drive letters  
server_root: D:\www\my\***, client_root: d:\www\my\***

**Comment by Trenrod** [comment]
Using powershell plugin for VSC didnt work. 
Worked with new powershell.

**Comment by michaluu** [comment]
Same problem. No matter what I'm using I get a mismatch. Tried with cmd, powershell, git-bash. The only part of path that doesn't match is drive letter. "c", "C".

`Unhandled exception: CommandExceptions.Server_directory_mismatch`

Does anyone have a workaround?

**Comment by ghodir** [comment]
@michaluu I had the same problem and fixed it by adding a script to call flow with the lowercased path:

```javascript
// file: scripts/flow.js
const child_process = require('child_process');
const dir = process.cwd();
const client_root = dir.charAt(0).toLowerCase() + dir.slice(1);
child_process.execSync(`flow status ${client_root}`, { stdio: [0, 1, 2] });
```

```json
// package.json
{
  "scripts": {
    "flow": "node ./scripts/flow"
  }
}
```

**Comment by willemodendaal** [comment]
Failed for me on first run (in Powershell), then on second run it worked.

**Comment by wgilpin** [comment]
Same problem - suddenly

flow is running on a different directory.
server_root: d:\Projects\wf2\xxx, client_root: D:\Projects\wf2\xxx

**Comment by Mg-Yaya** [comment]
if you use visual code, adding "flow.useNPMPackagedFlow": false to user preferences can solve the problem

**Comment by bondom** [comment]
@Mg-Yaya This setting doesn't exists, so error message `Unknown configuration setting` is shown

**Comment by bondom** [comment]
For those of you who has this issue in vscode and uses this plugin in your project: https://github.com/zhirzh/flow-babel-webpack-plugin

You can use updated version of this plugin that fixes this error:
https://github.com/bondom/flow-babel-webpack-plugin

I applied fix proposed by @ghodir above

**Comment by bmsuseluda** [comment]
> @michaluu I had the same problem and fixed it by adding a script to call flow with the lowercased path:
> 
> ```js
> // file: scripts/flow.js
> const child_process = require('child_process');
> const dir = process.cwd();
> const client_root = dir.charAt(0).toLowerCase() + dir.slice(1);
> child_process.execSync(`flow status ${client_root}`, { stdio: [0, 1, 2] });
> ```
> 
> ```json
> // package.json
> {
>   "scripts": {
>     "flow": "node ./scripts/flow"
>   }
> }
> ```

I modified your workaround a little bit, so that you could execute other flow commands as well f.e. flow stop:

```
const childProcess = require('child_process');

const executeFlow = options => {
  childProcess.execSync(`flow ${options.join(' ')}`, { stdio: [0, 1, 2] });
};

const flowCommands = process.argv.slice(2);

if (flowCommands.length > 0) {
  return executeFlow(flowCommands);
}

const dir = process.cwd();
const clientRoot = dir.charAt(0).toLowerCase() + dir.slice(1);
return executeFlow(['status', clientRoot, '--color=always']);
```

**Comment by moongoal** [comment]
2020 and here I have the same issue...

**Comment by nifgraup** [comment]
@moongoal what about now with #6592 fixed?

**Comment by moongoal** [comment]
@nifgraup that project was moved to a different technology, I won't be able to help on this I'm afraid.

**Comment by mroch** [comment]
this should be fixed by https://github.com/facebook/flow/commit/859a35cb5f07a3fc4256e9a293163147b9cf8129 which removed the check.

on case-insensitive filesystems the differently-cased roots refer to the same directory, so they will connect to the same socket, which should be as desired.
