### ISSUE TITLE
Generator & Function

### ISSUE THREAD

**Issue by pgherveou** [facebook/flow#2119]
Hi guys thks for the awesome project. 
Could the Generator definition integrate the function definition 
so we dont have to write this 
```js
// should work: 
// function test(gen: Generator<any, any, any>) {
function test(gen: Generator<any, any, any> & Function) {
  let context = { foo: 'bar' }
  let boundGen = gen.bind(context)
  // do somethin with boundGen
}

```

Let me know if this make sense.
I am not really used to the code base but with some guidance I will be happy to send a PR!

**Comment by samwgoldman** [comment]
A `Generator` is an object, not a function. Functions produce generators, but you don't call a generator like you would a function. A generator supports the method `next`.

If you want to talk about a "generator function"—or a function that produces a generator, you can use a type like this: `() => Generator<any,any,any>`. You can of course be as specific as you like about the function's parameters and the type parameters of the generator itself.

Hope this helps!

**Comment by pgherveou** [comment]
Make sense, Thks for the explanations!
