### ISSUE TITLE
Does $Shape<T> flow into T?

### ISSUE THREAD

**Issue by gcanti** [facebook/flow#2121]
``` js
type Person = {
  name: string,
  age: number
};

function foo(x: $Shape<Person>): Person {
  return x // <= should raise an error
}

const x: Person = foo({ name: 'Giulio' }) // <= should raise an error
```

**Comment by samwgoldman** [comment]
Good observation. This behavior is [known](https://github.com/facebook/flow/blob/f302c310f0c4819c6525bac763e0eb7fc3b81001/src/typing/flow_js.ml#L2820), but clearly undesirable.

This internal type was developed to be used as an upper bound, specifically for React, but we'd like to make it part of the public API. Implementing consistent behavior when used as a lower bound is definitely a prerequisite for that.

Thanks for raising this issue.

**Comment by bwestergard** [comment]
Any update on this? `$Shape<T>`, a type which had any subset of the keys in T, would be extremely convenient for writing extractors.

**Comment by TrySound** [comment]
@samwgoldman I changed label to bug. Is this behaviour still undesirable?

**Comment by dannyharding10** [comment]
Any update on this? I'm having to jump through some hoops to make sure my code is actually safe when using `$Shape`. I would love to hear about any progress here 👍

**Comment by STRML** [comment]
Use `$Rest<T, {}>` instead of `$Shape<T>` for better results @dannyharding10 .
