### ISSUE TITLE
"expected `T` to occur only covariantly" and type aliases

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#2122]
Here is an example. Should this work and there is a bug, or am I doing something wrong?

```js
// @flow

type Fn<+T> = (x: T) => void

class Foo<+T> {
  bar(fn: (x: T) => void): void {} // works
  baz(fn: Fn<T>): void {} // doesn't work
}
```

```
baz(fn: Fn<T>): void {}
                ^ T. contravariant position (expected `T` to occur only covariantly)
```

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMQHYA8A1ACoB8oAvKABQAeAXKKQJTWUBusAlgCbIAxtACGAZzF5YsEhVABvRKFAAjEQCdakfMwbM2HUN36tmxvgoC+S1SIBeWnXiIVTR3hfnXLQA

**Comment by avikchaudhuri** [comment]
Try
```
type Fn<-T> = (x: T) => void
```

In that definition `T` appears contravariantly (roughly, in an input position) rather than covariantly (roughly, in an output position). See https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)

**Comment by rpominov** [comment]
Ah, I see, thanks!
