### ISSUE TITLE
Issue with required prop and JSX prop spread

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#2124]
[Repro](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqUArgHbV0cPmADC9XH1J8CACmx1sAZwBcYAN6ZyfACbkC+AJ5qlBPOj4BzADRg42AkL7kYAfjV8emAEak8AXwBKdVQASBYCHjwRAB4ddAA3YAA+Tn8uXgFHYTACUlMARllg1DAwULKYUiIFeyUwAF4NUrLW0K1dfSM1fh1SKAtSHTBgYABJMFIAD2xSaiGe3X7BnQA6MAAVAAt0eoJDWbBdo4EJfXRvKrAEdAIt1YeW1rB-TgqwCKjY8RxhaSJ1A9VrVlP4UuxnmBUOluPxBDk8qYAEzFEJld5VGqKepNNGQ9raPQGPDGMC9ZZSYajAAy6AA1qQwFs-KQnq1XmEyp9oiRWARVpQWPpSABRKqYf6yH6Sf62EFKQJpVBAA)

```typescript
/* @flow */
import React from 'react';

function Component(props: {mandatory: string, optional?: number}){
    return <div/>;
}

function test1(){
      let props = {
        mandatory: undefined //I expected: undefined. This type is incompatible with...
      };
      return <Component {...props}/>;     
}

function test2(){
      let props = {
        mandatory: undefined //Like here
      };
      return React.createElement(Component, props);
}
```

I believe this behavior is caused by the `{...props}` bit, but haven't investigated.

**Comment by asolove** [comment]
I have a similar issue that I can minimize to just the use of spread:

```javascript
// @flow

type Thingy = {
  a: bool
}

const t1: Thingy = {
  a: undefined
} // generates a type error 

const t2: Thingy = {
  ...{ a: undefined }
} // does not throw a type error
```

At first I thought maybe flow just couldn't "see through" the spread operator. But if you remove the `a: undefined` and just have an empty object, you do get a type error for the missing `a` key. It just doesn't seem to check the type of `a` inside the spread object against the one expected outside it.

**Comment by Foxhoundn** [comment]
This fixes your issue, because flow thinks that mandatory will ALWAYS be a string, you have to give it the maybe type.

```
function Component(props: {mandatory: **?string**, optional?: number}){
	return <div/>;
}
```

**Comment by asolove** [comment]
@Foxhoundn I think you misunderstand the problem. We want the property to be mandatory and this issue shows several cases where flow fails to give an error when that property is not present.

**Comment by Foxhoundn** [comment]
@asolove bahah, sorry 😅

**Comment by asolove** [comment]
This is a pretty serious issue, more than the current title indicates. Can I recommend changing it to "Allows allows unexpected undefined in uses of Object.assign/spread operator".

**Comment by henrikbjorn** [comment]
I am seeing this aswell.

**Comment by davidnormo** [comment]
This seems pretty serious. I'd like to use flow in our project but this bug is one thing holding us back. I'd contribute a fix but don't know ocaml.

**Comment by rstacruz** [comment]
This is still an issue. Any workarounds?

**Comment by KingHenne** [comment]
As a freelance developer with TypeScript experience issues like this deter me from accepting work on Flow projects.

**Comment by nmn** [comment]
Seems like an issue with object spreads in general. This doesn't catch the error either:
```typescript

function test2(){
  	  let props = {
      	mandatory: undefined //Like here
      };
	  return React.createElement(Component, {...props});
}
```

**Comment by asolove** [comment]
Yeah, it's a completely generic problem about `Object.assign`/spread. Would be nice to get the react label off this, since it's not react-specific, and to instead consider it a core bug in the JS typing.

**Comment by rkettering** [comment]
Yeah, this is a huge showstopper for us as well - I'm experiencing the same issue, and we use the spread operator almost to the complete exclusion of any direct prop access, in our company's code.  We are of course using babel to allow the spread operator.

This basically neutralizes the benefit of flow to check nested react components for us.

**Comment by aaronshaf** [comment]
Bump. Please address. This is a huge pain.

**Comment by asolove** [comment]
The changeling for v0.53.1 listed a fix for some case of spread/`Object.assign` typing so I re-checked this and can confirm the bug is still present in v0.53.1.

**Comment by SamChou19815** [comment]
This issue has been fixed a while ago.
