### ISSUE TITLE
[React/JSX] Property not found in JSX Intrinsic on `div` with `style` and `onClick`

### ISSUE THREAD

**Issue by rricard** [facebook/flow#2126]
On flow 0.29.0, this kind of code block will raise errors:

``` js
     return (
        <div onClick={() => onClick && onClick()}
             style={[
               GlobalStylesheet.horizontalLayout,
               xxx.frame
             ]}>
               {/* ... */}
        </div>
      );
```

with those two errors:

```
xxx.js:184
184:         <div onClick={() => onClick && onClick()}
             ^ property `onClick`. Property not found in
203:         <div></div>;
             ^^^^^ props of JSX Intrinsic: `div`

xxx.js:184
184:         <div onClick={() => onClick && onClick()}
             ^ property `style`. Property not found in
203:         <div></div>;
             ^^^^^ props of JSX Intrinsic: `div`
```

A `div` element should be able to take inline styles and click events.

Thank you!

**Comment by rricard** [comment]
Found a out a bit more about it: it happens in the following cases, I have a typed render function using **type inference**: `React.Element<*>` and a conditional combined:

```js
render(): React.Element<*> {
  if(cond) {
    return <FooBar .../>
  } else {
    return <div ... />
}
```

**Comment by rricard** [comment]
The easy way out is to use `React.Element<any>`, but you should use an union type.

**Comment by rricard** [comment]
However, I'm reopening because type inference _should_ be able to infer an union type!

**Comment by asolove** [comment]
As of Flow 0.53, it looks like this is working as expected. If I write a branching method and let the returned element type be inferred, things type-check as they should:

```js
// @flow

import * as React from 'react';

const Thingy = (props) => <h1>Stuff</h1>;
let onClick = (e) => {};

function render(): React.Element<*> {
  if(Math.random() > 0.3) {
    return <div onClick={onClick}/>
  } else {
    return <Thingy/>
  }
}
```

So I think this can be closed. (cc @calebmer )
