### ISSUE TITLE
Object.values() appears to be unusable with custom types.

### ISSUE THREAD

**Issue by thisbejim** [facebook/flow#2133]
In lib/core.js:
```
static values(object: any): Array<mixed>;
```
This method doesn't seem to be compatible with a custom type because it is defined as a mixed array. 

Simple example:

types:
```
type Person = {
  name: string
}

export type People = Array<Person>;
```
function:
```
const getPeople = (): People => {
  // fetch data from an api for example
  const people = {
    john: {
      name: "John"
    },
    frank: {
      name: "Frank"
    }
  }
  return Object.values(people);
}
```
Which results in something like:
```
return Object.values(people); 
           ^^^^^^^^^^^ call of method `values`
export type People = Array<Person>;
                                ^^^^^ object type. This type is incompatible with. See: app/actions/types.js:75
```

Does this mean flow users need to rewrite utility functions like .values() to account for custom types?

**Comment by vkurchatkin** [comment]
Object type implies that an instance has particular properties, but it doesn't mean that it doesn't have any other properties. So, mixed is the only safe option

**Comment by stryju** [comment]
@vkurchatkin well, it does if you annotate it:

```
type Person = {
  name: string,
};

type: People = {
  [key: string]: Person,
};

const people: People = {
  john: {
    name: "John"
  },
  frank: {
    name: "Frank"
  }
};
```

I'd follow this issue: https://github.com/facebook/flow/issues/2174

**Comment by deecewan** [comment]
@vkurchatkin I've seen that touted a couple of times, but the main problem is that the same functionality can be implemented in a 'type-safe' way using Object.keys.

```js
type Person = { name: string };
type People = { [string]: Person };

const people = {
	john: { name: 'john'},
	frank: { name: 'frank' },
}

const fromValue: Array<Person> = Object.values(people); // fails
const fromKeys: Array<Person> = Object.keys(people).map(key => people[key]); // works
```

[**Here**](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKeATgM5wB2YAvGAN5iUCGAtngFxhkYkCWlAOZgAvgG5MuAsTg4YBOowDaPfkIC6XYuSqiJqAMZUeYfLPm0GqAJAArOAAtKXRi3ZcA5PaceRAGhsoEmZKAGsXJjZOMA8gkNCPUQCRdCNKEyC4VgA1ZhgAV2iAQRJgrAAebQpKAD5LAHkAI1s8AwwAOgA3PMKyAAozOTwASjEwYGAwKGY+GDJDYwwpkiyAaTwsMi4SssrSarq6Jpa29tCN-sH5YfbWZhw+86xaOqu8JSf1UfHJhDgSUJkIA) is the same code in the 'Try' page.

To my understanding, the `fromKeys` is essentially the same as the underlying implementation of `fromValues` (at least, that's how polyfill libs did it for a while). And I can't see how using `keys` can be any more sure of what 'values' will be present.

**Comment by EnoahNetzach** [comment]
a simple override declaration of something similar to:

```js
declare function values<K: string, T>({ [K]: T }): Array<T>
declare function values(o: any): Array<mixed>
```

should work for both cases.

**Comment by deecewan** [comment]
given my understanding of how flow treats objects, I think this should be good as a libdef:

```js
declare function values<T>(p: { [string]: T }): Array<T>;
declare function values(p: Object): mixed;
```

This way, if a known object is passed in (with only a single value type), it returns an array of the known values. If any other object type is passed in, it returns an array of mixed.

[this repl](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsAN3xjKwGcAeAFQD4AFAAcAXGADeYANodqhWhQDmAXTE8wAXwCUYgIKFC+AJ68+Abky4CxUpRr1GLNp2FiA8gCMAVrmo6w+oYmALa0AB5YGObo1EZCJAAKWIQcDGAAvBJgFPjBWGKy8kqaFrHxYElwQjAkmZIycgoqYkkpaRoWqDgMsmDxVTUZEqgAkF5wABYUYpI5eWIA5ONTCxoANKNQhhQA1jPZuflgC1v4uwuaGxro3RS91JzUQ+Kjy9NZc0dLkxQX66hgQGkbZ7D6HRanc6XAFA1J5agTJpiOTsDZAsBnOAI5JiACMVxuPSe1D0BmMXFaqQofCGTnYHGEWAGWC0ZjAwGAfXwHA4nC6RNI+FoMA4pKCFOSVJpmTpLgeslZ7M5UCFIrAHlw+DIvLA2JsRBIWDCcnwfUIVWSdD5t16YTF5NCESitNY9IE8r8bI5XJ5nCAA) shows it in action. Unless I'm missing something, this should work.

**Comment by mrkev** [comment]
Hmm, this looks promising. I'd like to examine this more closely. PR @deecewan?

**Comment by deecewan** [comment]
I started one earlier. There were a couple of issues.

I'll finish it up and put it up for comment in the morning.

**Comment by sibelius** [comment]
@deecewan this looks correct

**Comment by deecewan** [comment]
It seems to work in most cases for `values`. For some reason, my implementation was no working correctly with `entries`. I'll look into it soon.

**Comment by nnmrts** [comment]
Why is this still closed?

`Object.values` resulting in `Array<mixed>` every time, no matter what, is a **bug**.
`Object.entries` resulting in `Array<[string, mixed]>` every time, no matter what, is a **bug**.

**Comment by nnmrts** [comment]
I just love it how there's now way to use `Object.values` with flow. It really just **is** unusable.

**Comment by deecewan** [comment]
@nnmrts I just avoid `values` and `entries` and use `Object.keys(...).map(...)` instead

**Comment by nnmrts** [comment]
@deecewan Great! You could also just use `instanceof` every time!

Or even better, just use the `// $FlowFixMe` comment over every second line!

No, wait, even better, just typecheck by hovering over every variable in your IDE, that will do it!
<hr>
Sorry but after over 3 years I'm expecting a little more than shitty workarounds for this, from a library developed by facebook. Whatever, sorry for ranting...

**Comment by goodmind** [comment]
I think other issue already exists

**Comment by DnEgorWeb** [comment]
Really, why is this issue closed? "Avoid using Object.values(), use Object.keys() instead" is not a solution. Code should not depend on instruments like Flow, especially when we talk about native methods like Object.values().

**Comment by Robloche** [comment]
Why is this issue still closed?
Having `Object.keys()` not behaving like `Object.values()` and `Object.entries()` seems really awkward.
