### ISSUE TITLE
property `_read` not found in stream$Readable

### ISSUE THREAD

**Issue by glortho** [facebook/flow#2134]
I get the above with this code:

```
const rs = new stream.Readable( { objectMode: true } );
rs._read = myFn() {...};
```

This should be valid according to: https://nodejs.org/api/stream.html#stream_readable_read_size_1

**Comment by klyngbaek** [comment]
+1

**Comment by Brianzchen** [comment]
Exists now https://github.com/facebook/flow/blob/master/lib/node.js#L1885
