### ISSUE TITLE
Traits

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/flow#2135]
Very late to the party on [this](http://www.barbarianmeetscoding.com/blog/2016/01/04/safer-javascript-object-composition-with-traits-and-traits-dot-js/)—like, [slightly late](https://twitter.com/slightlylate/status/757944069905608704)—but I'm wondering how Flow can support this style of composition. 

Right now, Flow supports HOCs, but that's not always what is needed. 
https://flowtype.org/docs/react.html#higher-order-components

What do you think?

**Comment by jedwards1211** [comment]
Looking back through the history of programming, it seems clear that most people can agree an single inheritance.  But if there had been a clear winner among the myriad approaches to multiple inheritance I think it would have become common by now.

**Comment by kevinSuttle** [comment]
Take this for example: composing React props.

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCArhhnAHYAKATnDgM5gC8YA3qmGJQMIwCWAYwDWALjAAKAJQsAfGABucfgBMANJzDZ84gOQAjUuQq6wAHzC6aeBngymLuhsX0BbfvY1cVN-gHMKPRwaflcAQxosB0tbQUoVCKjzSxwwvzxo3XI4GAx+HABJCig4TOzc-IAROEEGXS9uCgAxGuIGcWk5RWV1TUpXODa8OAU8Gg6ZZnklVQb+wdtBjAmumd6uQRgwhgYAOTDXPFEGDBCKPwbBAAt+GBVrQLAAQRoaMKwAHgAJABUAWQAMgBRGB4Q4UDCyDQAX3Q2gIBTi1DojBY7E0fhguCux1O-HOly2O32hwA-OITmcLpo8hh



Attempting to merge Flow types to use as propTypes throws this error: "Property cannot be accessed on any member of intersection type". https://cloudup.com/cICohVjFUqa

**Comment by kevinSuttle** [comment]
Also @jedwards1211, shelve the condescending tone. Not helpful.

**Comment by jedwards1211** [comment]
What version of flow are you using?  I've seen those errors on intersection types less as I've upgraded to newer versions of flow.

**Comment by jedwards1211** [comment]
Sorry my comment sounded condescending, what I should say is, given that React mixins are deprecated, and the decorator proposal is in enough flux that we have `babel-plugin-transform-decorators-legacy`, I see a lot of churn in this area, so I think Flow shouldn't support any solution to this problem unless it becomes widely adopted.

**Comment by kevinSuttle** [comment]
No worries. Here's what I'm attempting to do, which I realize may be fools' gold: 
- satisfy both React PropTypes and Flow types
- reuse and merge props 
 
https://gist.github.com/kevinSuttle/fb3d4b33c83e091e7f980dda9ff8df8e

**Comment by jedwards1211** [comment]
The prop intersection with `&` should work although there have been [issues with it in the past](https://github.com/facebook/flow/issues/1366).  I think I sometimes still see legitimate errors that confusingly seem to come from the intersection failing to work, but it's hard to remember.  I take it you were interested in using Traits to work around the flow type errors?
Merging `propTypes` can be done with the dot spread operator.
On the other hand you might be able to use [babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb) instead of `propTypes` to get runtime checking of your flow types.

**Comment by kevinSuttle** [comment]
These Flow issues came after the fact because declarative composition isn't documented right now, but there are plenty of blog posts/docs that are anti-Class, anti-inheritance, anti-createClass, and anti-mixin. I personally feel that HOCs are convoluted and unnecessarily complex. It just comes off dogmatic at the cost of real-world use cases. 

Even the [intersection type example](https://flowtype.org/docs/union-intersection-types.html#intersection-example) from the Flow docs feels confusing. This doesn't feel like how people normally write code. 

What's attractive about traits is that you get: 
- composition
- conflict resolution
- declarative, human-readable syntax 
- data privacy
- immutability

**Comment by jedwards1211** [comment]
I agree about the intersection type example, there should be more examples than just an intersection of functions.

I can understand the appeal of traits, but I'm not convinced they're better than object composition.  Maybe there are better examples, but I would just use object composition for what the examples in that link are trying to do with traits:
```js
class Position {
  constructor(self) {
    this.self = self
  }
  x = 0;
  y = 0;
  print() {
    console.log(`${this.self} is calmly resting at (${this.x}, ${this.y})`);
  }
}
class Move {
  constructor(self, position) {
    this.self = self
    this.position = position
  }
  to(x,y){
      console.log(`${this.self} moves from (${this.position.x}, ${this.position.y}) to (${x}, ${y})`);
      this.position.x = x;
      this.position.y = y;
  }
}

class MovingMinion {
  position = new Position(this)
  move = new Move(this, this.position)
  toString() { 
    return 'moving minion'
  }
}

var movingMinion = MovingMinion();
movingMinion.position.print();
// => moving minion is calmly resting at (0, 0)
movingMinion.move.to(2,2);
// => moving minion moves from (0, 0) to (2, 2)
movingMinion.position.print();
// => moving minion is calmly resting at (2, 2) 
```
Down farther in the article things get more complicated with `Trait.resolve` because name conflicts are an inherent problem with all of these approaches to multiple inheritance.  And I think there will always be weird cases that Traits can't support because of name conflicts that object composition can handle just fine.  For instance what if you also wanted to have a `targetPosition` on a minion?  As far as I can tell from cursory reading you couldn't put two `Position` traits on an object because they would both try to use `this.x` and `this.y`.  But with object composition it's easy:
```js
class MovingMinion {
  position = new Position(this)
  targetPosition = new Position(this)
  move = new Move(this, this.position)
  moveToTarget = new MoveToTarget(this, this.position, this.targetPosition)
  toString() { 
    return 'moving minion'
  }
}
```
It's much more explicit how the composed behaviors are hooked up this way than when using Traits.

**Comment by kevinSuttle** [comment]
Thanks for the thorough explanation. 

Here's what I find odd about the intersect type.

This: no errors
https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MkQB5Z6i4CeGIqABCAV1y5YAOwAK1DAGdQAXlABvRKFDSAwtBRkA1gC5QACgCUKgHygAbrBQATADSbeAoqboAjcZKk6UAAfekYFIlwg0LoFUR80FCi3LSciBRQAcylvDGx0Emw+aPoIsmknQuKQ+gwSTKISuklYaFwUDABJKUhYJpa2joARWDIFOhTtKQAxUdEFU0sbe0dXd2k0WHmiWDsibEWrZVsHZ0mNrYit3EPl07WtMmgSBQUAORI0LwVcfKlMyZkAAWKGgTkYOVAAEFsNgSHwADwACQAKgBZAAyAFFoEQvlJcNY3ABfdhcHD4J4vJRiCTSUCcXBEKROJTEci4AB0OhoWCkzPwGncPxI7TIoDSkBIojaclgihU6ncWn4gm8fjpgUmqXSWUhdDyBSKE2VoCprw+X3VuC17lJ7nKUh+2FEFBwZjy8oWtICcsUFg0Wi0cUE2A98gUFjYWntWghaTDAdNjFwomwUnMpq0CI1ASzQfN70+RGUagA2gADAAkalwIIUnM9ik5aQy2WJoBrdZQDabDcLlqIxIrAF1SUGJ1M9AZDKXu72I5zdPojOPJ9Z81pa-XG4vgaDwcy1xOEcBc9INxOLHbEPbVUIMSQfERoH6lKpA6Bns-oMZnSh-hJZB71AR8fx9aQ30VCDZAjUAADJQKfF83zYRBOG4SlpB+JDwP8elVHDL1jDAl8YLfI5L1ABEYIlXVslLPsW3oqQO2XGdGMXdjVyo7Nvxfaw1CY-joGJU8RKo08YI3RAgA

This: errors all over the place
https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MkQB5Z6i4CeGIqABCAV1y5YAOwAK1DAGdQAXlABvRKFDSAwtBRkA1gC5QACgCUKgHygAbrBQATADSbeAoqboAjcZKk6UAAfekYFIlwg0LoFUR80FCi3LSciBRQAcylvDGx0Emw+aPoIsmknQuKQ+gwSTKISuklYaFwUDABJKUhYJpa2joARWDIFOhTtKQAxUdEFU0sbe0dXd2k0WHmiWDsibEWrZVsHZ0mNrYit3EPl07WtMmgSBQUAORI0LwVcfKlMyZkAAWKGgTkYOVAAEFsNgSHwADwACQAKgBZAAyAFFoEQvlJcNY3ABfdhcHD4J4vJRiCTSUCcXBEKROJTEci4AB0OhoWCkzPwGncPxI7TIoDSkBIojaclgihU6ncWn4gm8fjpgUmqXSWUhdDyBSKE2VoCprw+X3VuC17lJ7nKUh+2FEFBwZjy8oWtICcsUFg0Wi0cUE2A98gUFjYWntWghaTDAdNjFwomwUnMpq0CI1ASzQfN70+RGUagA2gADAAkalwIIUnM9ik5aQy2WJoBrdZQDabDcLlqIxIrAF1SUGJ1M9AZDKXu72I5zdPojOPJ9Z81pa-XG4vgaDwcy1xOEcBc9INxOLHbEPbVUIMSQfERoH6lKpA6Bns-oMZnSh-hJZB71AR8fx9aQ30VCDZAjUAADJQKfF83zYRBOG4SlpB+JDwP8elVHDL1jDAl8YLfI5L1ABEYIlXVslLPsW3oqQO2XGdGMXdjVyo7Nvxfaw1CY-joGJU8RKo08YI3RB2QoTl432MwEVI6BaOAIkJTmfEuQaXAcTxAVhD4TonDMOg0BIAC6Csa8gA

**Comment by kevinSuttle** [comment]
I think the REPL on Try Flow differs from the cli executable as well, _especially_ with regards to importing and exporting types from various files.

I should note that locally I have a Button and Icon class, but the rest are pure functional components.  Maybe that's the discrepancy?

**Comment by jedwards1211** [comment]
It's because you need to declare the required properties e.g. `<LabelButton label="..." .../>`

**Comment by jedwards1211** [comment]
Are you coming from TypeScript?  TypeScript only added non-nullable properties recently, before that it had no concept of required properties as far as I know

**Comment by jedwards1211** [comment]
basically "Property not found in" means "required property missing from" in those errors

**Comment by jedwards1211** [comment]
You'll get the same errors if you do `var buttonProps: ButtonProps = {}` or try to render `<Button />` after annotating it with `class Button extends React.Component<void,ButtonProps,void>`

**Comment by kevinSuttle** [comment]
No, I haven't used TypeScript. More from classical statically-typed OOP languages (non-functional). 

I feel like I'm missing something foundational.

**Comment by jedwards1211** [comment]
The errors are saying you need to pass in the required props you've declared (the ones without `?` before the colon) to the JSX element.  Does that make sense?

**Comment by kevinSuttle** [comment]
I think so. 

I've refactored a bit and gotten the errors down, but I'm still not quite sure what it's looking for.

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgBCArrlywAdgAVqGAM6gAvKADeiUKE7cAXPQBGg4SLqgAPvUZSiuA8bpT+WtCgsAaZaAAmRKSgDmIzXQzY6CTYHJb0ZmSirsGhRvQYJF5EYXTCsNC4KBgAkiKQsClpGVkAIrBkUnTOKmTQJFJSAHIkaETqUriBIl7VoKIAYuX8UgD8mgAUAJRyAHygAG6wKK69omiww0Sw80TYY6BTswtLKy5rG2YbuPuHsnOLy6siAMLQKGQA1jfTd8ePLmQABYoaCuRgifYjACC2GwJA4AB4ABIAFQAsgAZACi0CIrREuBmzgAvuwuDwMSQtERoBJYNI5IoXHVqdB2p0UN0ScgiAAPLB4UCREQdPi6USM8YKdyeHyyfyBNAxKpCuoNZqteVaXD6Ryqcla8X6YmgTQCISiOkMn4zFwInQWkQuGpqpotIiyBQAbQABgASaUebwiE0B2r1N2tYk+gC6pJUKltKgRwAdeltZO4oEprPNeitMnkectkhkADJs1SaQW2Ig+QL8MLRTmacWRJKAvSpOoW9A2wWbXa224g3KFJ3pAA6GXBk2iV7vD6eidSSfzt6fYlJhMIlk0mbj0uTvfQYkpk-blNtjNAA

**Comment by kevinSuttle** [comment]
I think this is what's throwing me off. 

Optional vs absent vs non-nullable
https://medium.com/@chenglou/react-proptypes-flow-types-cheat-sheet-ed80f8e1383d#.v53gwexvf

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgBCArrlywAdgAVqGAM6gAvKADeiUKE7cAXPQBGg4SLqgAPvUZSiuA8bpT+WtCgsAaZaAAmRKSgDmIzXQzY6CTYHJb0ZmSirsGhRvQYJF5EYXTCsNC4KBgAkiKQsClpGVkAIrBkUnTOKmTQJFJSAHIkaETqUriBIl7VoKIAYuX8UgD8mgAUAJRyAHygAG6wKK69omiww0Sw80TYY6BTswtLKy5rG2YbuPuHsnOLy6siAMLQKGQA1jfTd8ePLmQABYoaCuRgifYAQWw2BIHAAPAAJAAqAFkADIAUWgRFaIlwM2cAF92FweOiSFoiNAJLBpHJFC46lToO1OihusTkEQAB5YPCgSIiDp8XSiBnjBTuTw+WT+QJoGJVQV1BrNVpyrS4fSOVRkzVi-RE0CaARCUS0+k-GYueE6c0iFw1VVNFpEWQKADaAAMACRSjzeETG-21equ1pE70AXRJKhUNpU8OA9r0NtJ3FAFJZZr0lpk8lzFskMgAZFnKdT82xELz+fghSLs9SiyIJQE6VJ1M3oK389bba23IHZQoO9IAHTSoPG0Svd4fD3jqQTudvT7GsNqt2yABEWpEu713D3qdEu8T8fhzOpMzHJYnN+gROTT8vydb6aAA

**Comment by jedwards1211** [comment]
@kevinSuttle Ah, I got bit by this one too, unfortunately Flow doesn't support default values in destructuring right now: https://github.com/facebook/flow/issues/183
So even though for instance you have `className='btn'` Flow doesn't realize a default is being assigned

**Comment by jedwards1211** [comment]
And yeah optional vs absent vs non-nullable took me a little while to wrap my head around too

**Comment by jedwards1211** [comment]
In any case, regardless of whether you use traits for something else, I don't think you'd need them to fix these Flow errors

**Comment by kevinSuttle** [comment]
Re: #183: https://flowtype.org/docs/react.html#stateless-functional-components I guess it's a very subtle difference? 

And add in Maybe types, and then I'm super confused. 

But to your point, yes, these errors don't appear solvable by traits.

**Comment by jedwards1211** [comment]
Ah, so in their example for default props in stateless functional components they use a maybe prop in the type signature for the defaulted prop.  Which I think unfortunately means Flow doesn't know it's guaranteed to be defined.  This is different than when using `Component` classes, where you can explicitly declare props with defaults as non-maybe but Flow will not complain if you omit them thanks to internal magic.

**Comment by kevinSuttle** [comment]
Hm. Ok. Thanks for the detailed responses. Appreciated @jedwards1211.

**Comment by jedwards1211** [comment]
No problem, I went through a lot of the same frustration when I was getting started with flow!
