### ISSUE TITLE
Wrong version of Flow. The config specifies version ^0.27.0 but this is version 0.29.0

### ISSUE THREAD

**Issue by arielelkin** [facebook/flow#2136]
```
react-native-cli: 1.0.0
react-native: 0.30.0
```

I had flow version 0.26 and was getting this error when running it in my React Native project:
`Wrong version of Flow. The config specifies version ^0.27.0 but this is version 0.29.0`

So I did:
`$ npm install --global flow-bin`

Result:

```
$ flow
Launching Flow server for ~/directory/project
Wrong version of Flow. The config specifies version ^0.27.0 but this is version 0.29.0
Could not start Flow server!
```

I have no clue why...

```
$ flow version
Flow, a static type checker for JavaScript, version 0.29.0
```

Here's my `.flowconfig`:

```
[ignore]

# We fork some components by platform.
.*/*.android.js

# Ignore templates with `@flow` in header
.*/local-cli/generator.*

# Ignore malformed json
.*/node_modules/y18n/test/.*\.json

[include]

[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
node_modules/react-native/flow
flow/

[options]
module.system=haste

esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

experimental.strict_type_args=true

munge_underscores=true

module.name_mapper='^image![a-zA-Z0-9$_-]+$' -> 'GlobalImageStub'
module.name_mapper='^[./a-zA-Z0-9$_-]+\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FixMe

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(2[0-7]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(>=0\\.\\(2[0-7]\\|1[0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)?:? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixedInNextDeploy

[version]
^0.27.0

```

**Comment by pvolok** [comment]
The caret does not increment first non-zero part in version: https://docs.npmjs.com/misc/semver#caret-ranges-123-025-004

You can check your version here: https://semver.npmjs.com/

**Comment by thejameskyle** [comment]
Yup @pvolok is correct, `0.29.0` does not satisfy `^0.27.0` following the rules of semver.

You can either install `0.27` directly with `npm install flow-bin@0.27` or update your app to the latest version of Flow

**Comment by arielelkin** [comment]
> the rules of semver

1. There are no carets in Semver 
1. "Major version zero (0.y.z) is for initial development. Anything may change at any time. The public API should not be considered stable."

http://semver.org/

> Likely as a result of the long-standing behaviour of the tilde range specifier in npm, we seem to have reinterpreted the semver spec. Many package authors currently communicate breaking and non-breaking changes by condensing all version changes into the last two segments of the version, something like: 0.MAJOR.MINOR.

https://nodesource.com/blog/semver-tilde-and-caret/

Just don't call it Semver. Call it Nodever.

**Comment by tibistibi** [comment]
i changed the version number in the config file:
/.flowconfig

this worked (and i hope it is the correct way)

**Comment by tobua** [comment]
For those who want to avoid updating the version all the time the following two approaches also work.

* Remove the version from the config altogether (including the `[version]`)
* Add a range including major releases: `>=0.27.0`

Sidenote: Currently 75% of `flow-bin` releases are major ones which should include breaking changes. If they moved to version 1 and started planning the breaking changes better the default `^` would work as expected and most people actually need to make changes to the code when updating the version.
