### ISSUE TITLE
Do expressions esproposal does not exist

### ISSUE THREAD

**Issue by frontsideair** [facebook/flow#2141]
I'm using stage-0 of babel in a project I work on and it includes [do expressions](http://wiki.ecmascript.org/doku.php?id=strawman:do_expressions). I tried using this feature but Flow complained and I couldn't find a switch to enable this, unlike `class_static_fields` and `class_instance_fields`.

I know it's a strawman proposal at this point, but are there any plans to add this?

**Comment by indeyets** [comment]
It's stage-1 currently: https://github.com/tc39/proposal-do-expressions

**Comment by jamesisaac** [comment]
Closing in favour of #6417 (more discussion)
