### ISSUE TITLE
Annotation required in an if statement condition, why?

### ISSUE THREAD

**Issue by Foxhoundn** [facebook/flow#2143]
This is the relevant code

```
state: {
  showDropdown: boolean,
  selected: Array<*>,
};

state = {
  showDropdown: this.props.show,
  selected: this.props.selected || [(this.props.def: ?string)],
};

componentDidUpdate(): void {
  document.removeEventListener('click', this.handleOutsideClick);

  if (this.state.showDropdown) {
    document.addEventListener('click', this.handleOutsideClick);
  }
}
```

Flow outputs -

```
44:     if (this.state.showDropdown) {
             ^^^^^^^^^^^^^^^^^^^^^^^ property `showDropdown`. Missing annotation
```

?? Why ??

**Comment by avikchaudhuri** [comment]
In general Flow need annotations for any part of an exported type that it cannot pin down exactly. Can you paste the entire file?

**Comment by jedwards1211** [comment]
@Foxhoundn @avikchaudhuri I wonder if the error would go away if you put the annotation inline with the assignment like this?

```js
state: {
  showDropdown: boolean,
  selected: Array<*>,
} = {
  showDropdown: this.props.show,
  selected: this.props.selected || [(this.props.def: ?string)],
};

```

**Comment by TrySound** [comment]
This is probably fixed with new react definitions.

/cc @vkurchatkin

**Comment by AugustinLF** [comment]
[Yes it is](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChSYBPMJOABRzAGc4BeOAb1LjiaQBskGJABMAXHACCUKCkoAeAFQA+ADTdeACwgB3CQCMIEQSgB26gL4VqtAMowUMWuy48m2nQBFGI3aYNGJuYafILC4lIyckpqpFakaPwoTCwAwrhgcEgAHk6mIizI6DAAdOngEKZIpjDyDBDMqnD2jkjKnCEOTmwdPG4e3g2+Ov5wMJrATCVgjFPuuup9vAJCThHjk9OzJaGronAAPgdwANoAFBtTMw1TIkiYEgD8TDBQwKYA5gCUALqLcBYANzkHhoDKVaowTzAEQAVTAIlaZy+EgAbhAYb0+sBMHALhM5l0kDsBj4-F9OFYeFYLEA).
