### ISSUE TITLE
Type Error when assigning a string to an OscillatorNode's type

### ISSUE THREAD

**Issue by lamarqua** [facebook/flow#2146]
According to the W3C WebAudio spec, the type of the property `OscillatorNode.type` should be [a string (or more precisely an enum)](https://www.w3.org/TR/webaudio/#idl-def-OscillatorType).
When typechecking the following program, I get an error complaining about the type not being an AudioParam (which is wrong, and was most likely copied from the faulty [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/API/OscillatorNode/type) ?)

```
// @flow

const OSC_TYPE = "square";

var audioCtx = new AudioContext();

var oscNode = audioCtx.createOscillator();
oscNode.type = OSC_TYPE;
```

```
audioparam.js:8
  8: oscNode.type = OSC_TYPE;
     ^^^^^^^^^^^^ assignment of property `type`
  8: oscNode.type = OSC_TYPE;
                    ^^^^^^^^ string. This type is incompatible with
561:   type: AudioParam;
             ^^^^^^^^^^ AudioParam. See lib: /private/tmp/flow/flowlib_3f665f2d/bom.js:561


Found 1 error
```

**Comment by thejameskyle** [comment]
Moving to #2147
