### ISSUE TITLE
Docs: explain exactly what `&` does in Intersection types

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/flow#2148]
Example:

``` jsx
/* @flow */

export type ButtonProps = {
  onClick: () => void,
  type: 'button' | 'reset' | 'submit',
  design: 'primary' | 'secondary' | 'page' | 'tooltipInfo' | 'tooltipDocs',
  onFocus: () => void,
  onmouseover: () => void,
  onmouseout: () => void,
  className:string,
  children: Array<HTMLElement>,
}

export type IconProps = {
  glyph:string,
  className?: string,
  title?: string,
  width?: string,
  height?: string,
};

// what does the following line actually do?
// Object.assign? Some other wizardry? 
type IconButtonProps = ButtonProps & IconProps
```

**Comment by vkurchatkin** [comment]
It means that object has type `IconButtonProps` if it has both types `ButtonProps` and `IconProps`. In some case it has the same effect as `Object.assign` (when all property names are unique)

**Comment by kevinSuttle** [comment]
Hm. Ok. Can you explain this behavior as a result? https://github.com/facebook/flow/issues/2135#issuecomment-235625700

**Comment by jedwards1211** [comment]
I've had those kinds of errors with intersection types often.  If you're using an older version of flow, try upgrading; that's fixed a lot of those errors for me.

**Comment by gkz** [comment]
This is documented here: https://flow.org/en/docs/types/intersections/
