### ISSUE TITLE
Assigning prototype from Object.create causes "property not found" errors

### ISSUE THREAD

**Issue by jdelStrother** [facebook/flow#2149]
This only seems to occur across multiple modules.   If everything is in one file it works fine.

foo.js: 

``` js
// @flow
function SuperClass() {}
function Foo() {}
Foo.prototype = Object.create(SuperClass.prototype)
Foo.prototype.bar = function() {}

export default Foo
```

app.js:

``` js
// @flow
import Foo from './foo'
var f = new Foo()
f.bar()
```

results in: 

```
app.js:4
  4: f.bar()
       ^^^ property `bar`. Property not found in
  4: f.bar()
     ^ new object


Found 1 error
```

Is there a way of expressing this that flow will be happy with?

(Not sure if this might be a variation of #286 or #623 ?)

**Comment by avikchaudhuri** [comment]
Try something like:

```
interface IFoo {
  static (): void;
  bar(): void;
}

export default (Foo: Class<IFoo>);
```

Let us know if this works. Basically exported functions have regular function types and "lose" their power as constructors, but casting them to a class type is allowed, and a class can obviously be instantiated. The recipe to follow is: add all the methods in prototypes (available to instances via `new`), and add a static callable with the same signature as the function (available to direct callers).

**Comment by jdelStrother** [comment]
Hmm, ok.   Is there any way of intersecting the interface types to avoid repeating methods from the SuperClass object in the IFoo interface?

```
interface ISuperClass {
  static (): void;
  baseMethod(): string;
}
function SuperClass() {}
SuperClass.prototype.baseMethod = function() { return 'super' }

interface IFoo {
  static (): void;
  baseMethod(): string;  // copy & pasted from ISuperClass, hope it doesn't change!
  subMethod(): string;
}
function Foo() {}
Foo.prototype = Object.create(SuperClass.prototype)
Foo.prototype.subMethod = function(x) {return x}
export default (Foo: Class<IFoo>)
```

**Comment by thejameskyle** [comment]
Looks like you can use `Class<typeof SuperClass>` [to get 90% of the way there](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCIFMoCWAdgQC4FxEBcqUArkQMbmVgBiccAFAG4CGMOripgidALYAjXACcAlGADeAX1Qc4AOgAOMuKT0BPLbg3jcpABZwAJmAC8YekxZFeAoSLFTZClQG5UUiNcdk4AYRg+AGco+zAI6KiAHiDjOChQzR09Q2MAPgD0TDAAVSi+AHNhVEZImLAAIT4ZMFwAD1JcImtYrnURdQSY31QwMEZKKNIZOmY4GS4RsbGoumMFgHIpmWIKjbk-MGKkgFowAGUrOhhbaTA+IlaZXRlRsFVVfhbJZriiXCQTQWB1QPxkpnMVmsXC2012+0OxzOAElYg8ni8gA).

**Comment by SamChou19815** [comment]
We no longer support prototypes well.
