### ISSUE TITLE
Multiple parameter lists

### ISSUE THREAD

**Issue by phadej** [facebook/flow#215]
The example probably explains better. I'd like to write:
```js
function nth<T>(n: number)(arr: Array<T>): T {
  return arr[n];
}

var first = nth(0);
```

Now I have to do:
```js
function nth<T>(n: number): (arr: Array<T>) => T {
  return function (arr) {
    return arr[n];
  }
}
```

The difference is not big, but still IMHO this is *nice to have*.

**Comment by samwgoldman** [comment]
We want to keep our syntax extensions to an absolute minimum. If you can get some traction with this syntax through the ECMAScript proposal process, we'll be happy to implement it. Otherwise, we want to stay compatible with other tools.
