### ISSUE TITLE
[dom lib] window.localStorage vs localSorage

### ISSUE THREAD

**Issue by SamWyld** [facebook/flow#2150]
This typechecks

``` js
localStorage.getItem('key') //?string
```

but this doesn't

``` js
window.localStorage.getItem('key') //?string
```

Is it intended?

**Comment by thejameskyle** [comment]
Right now `window` is defined as `any`: https://github.com/facebook/flow/blob/master/lib/bom.js#L39

We should improve that, but is there a reason you need to refer to `window` directly?

**Comment by SamWyld** [comment]
@thejameskyle I like the explicitness of it, but It'll do for now I guess, thank you. I think this can be closed :)

**Comment by jeffmo** [comment]
We can work on making `window` reflect the nature of how it exposes the global scope soon, too

**Comment by vicapow** [comment]
fwiw, we use `import window from 'global/window'` in addition to lint rules to discourage the use of global references so being abel to have `window.localStorage` be type checked would be helpful for that.

There's also situations where we prefer to pass `window` as a dependency to reducers / functions and stub them out for tests, etc. so A `Window` type would be helpful in those situations.

**Comment by calebmer** [comment]
Closing for now, but we will continue to think about how we model JavaScript environments 😊

If you want to contribute a `Window` type, please feel free!

@vicapow there is nothing stopping you from creating a window type yourself with the subset of APIs you need 😊
