### ISSUE TITLE
Possible performance issue with discriminated unions in flow 0.28.0

### ISSUE THREAD

**Issue by kastermester** [facebook/flow#2153]
See this repo:

https://github.com/kastermester/flow-discriminated-unions-issue

It is a small code extraction from a library I'm in the process of writing. It has been a pleasure working with flow on that library, but for some reason it starts to have issues with the discriminated unions performance wise - everything is resolved as it should be, no false positives or missing negatives.

The problem is most clearly seen when working in nuclide, where every autocompletion help and etc suddenly disappears.

**Comment by kastermester** [comment]
I just tested this on 0.29.0 as well where I get similar results.

If I try this on master however (I let it run for about a minute) I never get a result, but I can see the process is taking up a lot of CPU and memory (it was up to about 700MB when i quit it).

**Comment by avikchaudhuri** [comment]
Thanks for the report, @kastermester! Will look into it shortly.

**Comment by avikchaudhuri** [comment]
Good news, I might have a general fix for this. Will probably land in time for 0.31.

**Comment by kastermester** [comment]
Sounds great - I'll be happy to test it out :) I'm on holiday for the next two weeks though.

**Comment by kastermester** [comment]
I have tried the committed fix, and while it has helped greatly in the isolated repro i posted I still have trouble in my actual project.

The project will be open sourced once ready - but due to its unfinished nature I am not confident with opening it up to everyone yet. Can I provide you with the source so you can take another look and figure out what is causing the problem in my project? I am not entirely sure if it is related to discriminated unions there as well. I have a project where `flow ls` says there are 32 files visible, yet a `flow check` takes about 50 seconds (ish) to run on my desktop. The files are fairly straight forward - the only thing that comes to mind is that a lot of recursive defined discriminated unions are used, like in the example. Let me know if I can provide you with the source somehow.

**Comment by avikchaudhuri** [comment]
Could you DM me the code at my Twitter account @__avik? I'll have a look.

**Comment by kastermester** [comment]
@avikchaudhuri Done :) Thanks a lot! :)

**Comment by avikchaudhuri** [comment]
@kastermester For some reason I didn't get it. Could you resend at flow@fb.com? Sorry.

**Comment by kastermester** [comment]
I tried sending an email to that address, but it bounced. Either way, it was just a link to the private repo located here (you should be a collaborator on the repo): https://github.com/kastermester/hablar-perf-issue

**Comment by avikchaudhuri** [comment]
Thanks @kastermester. For future reference, the correct email address is flowtype@fb.com, sorry for the confusion.

I've reopened this issue. I'm also perf debugging another report around disjoint unions, hopefully related. :P Thanks for your patience!

**Comment by kastermester** [comment]
Thanks! Again I'll be happy to test possible fixes once you get that far :)

**Comment by TrySound** [comment]
This is probably fix by [v0.66](https://github.com/facebook/flow/blob/master/Changelog.md#misc)

This probably can be closed.
/cc @vkurchatkin
