### ISSUE TITLE
process.exitCode is missing from decls

### ISSUE THREAD

**Issue by steelbrain** [facebook/flow#2156]
Docs link: https://nodejs.org/api/process.html#process_process_exitcode
Title says it all, here's a screenshot for proof
<img src="https://cloud.githubusercontent.com/assets/4278113/17223442/6baa031c-54b1-11e6-9266-2b8065a8d8f0.png">

I'm on flow @ 0.29.0

**Comment by avikchaudhuri** [comment]
Mind sending a PR? See https://github.com/facebook/flow/blob/master/lib/node.js#L1436

**Comment by steelbrain** [comment]
@avikchaudhuri There's already https://github.com/facebook/flow/pull/2158 :)
