### ISSUE TITLE
polymorphic type: function type

### ISSUE THREAD

**Issue by phadej** [facebook/flow#216]
The example above doesn't type check. Does all `var`s (and return types?) have to be monomorphic?

```js
/* @flow */

function nth(n: number) : <T>(arr: Array<T>) => T {
  return function (arr) {
    return arr[n];
  }
}

var first: <T>(arr: Array<T>) => T = nth(0);
```

**Comment by samwgoldman** [comment]
This is because flow will not infer a generic type. If you specifically annotate the inner function, you can convince flow that the returned function fits the return type of `nth`.

Here is a smaller example showing that flow doesn't infer generics:

```
/* @flow */

function index(xs, i) {
  return xs[i];
}

// Either one of these individually type checks, but together it fails
var ex1: string = index(["hi"], 0);
var ex2: number = index([0], 0);
```

**Comment by facebook-github-bot-8** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
