### ISSUE TITLE
error 15 when running under gnu make 3.81 ubuntu 14.04 LTS x86_64

### ISSUE THREAD

**Issue by raould** [facebook/flow#2161]
hi, 

I haven't been able to learn/see/figure out why flow seems to behave differently when I run it via make. Is it bash vs. sh? Is is something about npm? Is it something about make? Any clues/thoughts/hints/help/fixes would be appreciated.

```
x@x:~/Dev/z$ flow version ; flow check src ; echo $?
Flow, a static type checker for JavaScript, version 0.29.0
Found 0 errors
0
x@x:~/Dev/z$ make check
flow version
Flow, a static type checker for JavaScript, version 0.29.0
flow check src
make: *** [check] Error 15
```

**Comment by avikchaudhuri** [comment]
cc @gabelevi

**Comment by mroch** [comment]
if that error message is because `flow check src` is exiting w/ code 15: flow's exit code 15 means "out of shared memory"

**Comment by vkurchatkin** [comment]
I had exactly the same issue

**Comment by kbahr** [comment]
There are a few comments on the linked issue, #2017 and I'm adding mine - I also get this consistently on WSL.
