### ISSUE TITLE
Parsing flow annotated files to IR or AST

### ISSUE THREAD

**Issue by PatoBeltran** [facebook/flow#2162]
Hello,

I'm looking at the possibility of a tool that get's flow annotated files and produces typings files for Typescript. I feel like this would make flow and typescript users easier to work with each other.

I am looking at the flow compiler as a starting point, and was thinking about using it to get a IR or AST that knows about types and from there write a backend that outputs `.d.ts` files. Is this possible with the current `flow` compiler? If not, what changes would need to happen in order for this to be possible?

Thanks!

**Comment by gcanti** [comment]
> was thinking about using it to get a IR or AST

You may want to take a look at the `ast` command

```sh
$> flow ast --help

Usage: flow ast [OPTION]... [FILE]

e.g. flow ast foo.js
or   flow ast < foo.js

  --from    Specify client (for use by editor plugins)
  --help    This list of options
  --pretty  Pretty-print JSON output
  --tokens  Include a list of syntax tokens in the output
  --type    Type of input file (js or json)
```

**Comment by vkurchatkin** [comment]
It's probably easier to use babel's parser (babylon) for that

**Comment by gcanti** [comment]
@vkurchatkin Ah yeah, you are right (just checked with AST Explorer). The only incompatibility between the inner parser and babylon seems the new `declare module.exports` syntax

**Comment by pvolok** [comment]
There is also `dump-types` command.

```
$ flow dump-types --help
```

**Comment by PatoBeltran** [comment]
Thanks for everyone's response! I will check out all of those options to see if it's possible to implement.

**Comment by mroch** [comment]
Cool, comment if you make progress!
