### ISSUE TITLE
Static variable in class is not compiled

### ISSUE THREAD

**Issue by olleharstedt** [facebook/flow#2163]
Using Babel and Flow, this code:

```
class Agent {
  static agents;
}
```

is compiled to

```
class Agent {}
```

Yet not error is thrown.

**Comment by samwgoldman** [comment]
What kind of error did you expect?

**Comment by olleharstedt** [comment]
Sorry, I was a bit confused by the fact that I can't initialise the static variable in the class, but rather have to do

```
Agent.agents = []
```

outside the class. Will close this.
