### ISSUE TITLE
Allow introducing generic variables in const expressions

### ISSUE THREAD

**Issue by asolove** [facebook/flow#2165]
It would be nice to be able to provide type signatures on `const` declarations that require introducing generic type variables. This is currently possible when declaring functions, classes, and types, but not for `const`.

There are two useful benefits of this:
1. It makes it possible to define functions using generics much more succinctly.
2. It make it possible to export generic functions that are obtained as expressions rather than declarations. I have an outstanding [StackOverflow question](http://stackoverflow.com/questions/38663988/trouble-exporting-curried-generic-function/38674912#38674912) about doing this and it seems to currently be impossible:

``` javascript
export function curry2<A,B,C>(f: (x: A, y: B) => C): (x: A) => (y: B) => C {
  return (a) => (b) => f(a, b)
}

function _push<A>(item: A, items: Array<A>): Array<A> {
  return items.concat(item)
}

export const push = curry2(_push)
```

Flow says that the exported `push` needs to annotate its type parameters A and B, but this is currently not possible because `const` declarations cannot introduce type variables.

**Comment by avikchaudhuri** [comment]
Note that applications of generic functions are implicitly instantiated, so what's going on here is that `push` is instantiated to a particular choice of `A` and `B` (it asks for annotations because `push` is also exported, but that's orthogonal). This is evident if you try:

```
export function curry2<A,B,C>(f: (x: A, y: B) => C): (x: A) => (y: B) => C {
  return (a) => (b) => f(a, b)
}

function _push<A>(item: A, items: Array<A>): Array<A> {
  return items.concat(item)
}

const push = curry2(_push);

(push(0)([0]): Array<number>);
push("")([""]); // error, string =/= number
```

Currently you need to do:
```
const push = function<A>(x: A): (x: Array<A>) => Array<A> { return curry2(_push)(x) };
```
to make the above work.

**Comment by 0rvar** [comment]
Another use case is to be able to properly type connected Redux components. Ie:

```jsx
type ExternalProps<T> = {| value: T |}
type ConnectProps = {| foo: string |}
type Props<T> = {| ...ExternalProps<T>, ...ConnectProps |}
class MyComponent<T> extends React.Component<Props<T>> {}

const connected: <T>(React$ComponentType<ExternalProps<T>>) = connect(
   function mapStateToProps(state: mixed): ConnectProps { return { foo: 'bar' } }
)(MyComponent)
```

This is currently not possible.
