### ISSUE TITLE
"import type" silently ignored

### ISSUE THREAD

**Issue by skovhus** [facebook/flow#2166]
`import type` requires the file exporting types to have have `// @flow` comment in the file. 

So currently flow doesn't silently ignores any requires of types from files without a `@flow` comment. This can take a long time to debug...

So if I have two files `defs.js` and `main.js` no error is catched by `flow`:

``` javascript
# defs.js
export type UserID = number;

# main.js
// @flow
import type { UserID } from './defs';
export function myFunc(): UserID {
    return '42';
}
```

Even importing something that is not exported doesn't fail:

``` javascript
// @flow
import type { xxxxxxxxxxx } from './defs';
export function myFunc(): xxxxxxxxxxx {
    return '42';
}
```

When adding `// @flow` to the `defs.js` file the error shows up. I propose that either: 
- flow complains if the type file you require doesn't have the `@flow` pragma
- OR (even better) not require `@flow` to be there

See more about this feature here https://flowtype.org/docs/modules.html#type-imports--exports

**Comment by avikchaudhuri** [comment]
Sorry the docs don't make this point explicit!

**Comment by avikchaudhuri** [comment]
FWIW this behavior is not specific to `import type` but to all kinds of imports, but I agree it's particularly confusing for `import type`.

**Comment by houshuang** [comment]
I totally agree. I had a problem with a type imported from a different module, where I thought I had generated js.flow files, but it turned out I hadn't. If I explicitly import types, and it doesn't "work", I expect flow to shout loudly about it. In this case, I had imported the type, and type annotated code, and wondered why circle-ci passed the flow tests... Because I hadn't properly installed flow-copy-source.

**Comment by houshuang** [comment]
This issue just hit me again - I was trying to test a complex type configuration, and didn't understand why I couldn't get an error on an imported type, before finally realizing that I had inadvertently removed the //@flow annotation from the file exporting the type. When someone explicitly imports a type, you should definitively error if the type cannot be found.

**Comment by gcazaciuc** [comment]
Encountered this issue also multiple times and it's pretty hard to figure it out why the imported types just don't work. I believe a friendly error/warning would go a really long way in terms of smoothing the dev experience.

**Comment by adamborowski** [comment]
@skovhus Have you tried to add `// @flow` to your defs.js file as well?

**Comment by vicapow** [comment]
@rostero1 flow can catch these errors too but it’s a config you have to enable. See https://flow.org/en/docs/linting/rule-reference/#toc-untyped-type-import

**Comment by mrkev** [comment]
What's missing here? This is available via a lint: would better documentation on the default behaviour make this better? It's tagged as `opt-in vs. opt-out`: does this mean there's discussion wether to keep this this opt-in by default? (I personally think it should be opt-out).

**Comment by vicapow** [comment]
I do think we should consider making this an opt-out but might be better to move that to a separate ticket if there's interest
