### ISSUE TITLE
Interface type check fails on maybe types 

### ISSUE THREAD

**Issue by inv8der** [facebook/flow#2167]
The following code generates flow errors. However, if I change `A` to be a `type`, everything checks out. Seems similar to #1569

```
declare interface A {
    hello: string,
    foo?: string
}

const obj: A = {
    hello: 'world'
};

const copy: A = { ...obj };
const copy2: A = Object.assign({}, obj);
```

<img width="509" alt="screen shot 2016-08-01 at 11 50 26 am" src="https://cloud.githubusercontent.com/assets/830026/17305837/794d4a5a-57e1-11e6-8e88-008aa9822512.png">

**Comment by avikchaudhuri** [comment]
Yeah it's similar. Will fix.

**Comment by vkurchatkin** [comment]
Simple example:

```js
interface A {
  a: ?number
}

var a: A = { a: null }
```

**Comment by netproteus** [comment]
👍

**Comment by SamChou19815** [comment]
They now error by saying you cannot spread interfaces.
