### ISSUE TITLE
flow does not understand creating an object through for/in loops when the object is exported

### ISSUE THREAD

**Issue by drabinowitz** [facebook/flow#2168]
I was able to produce this on flow v0.30, here is the smallest example case i can provide

in one file:
```javascript
/* @flow */
// flow-error-export.js

var testObject = {
    a: 1,
    b: 2,
};

export function createTest () {
    var res = {};
    for (let k in testObject) {
        res[k] = testObject[k];
    }
    return res;
}

var resObject = createTest();
console.log(resObject.a);
```

and then in another:
```javascript
/* @flow */
// flow-error-import.js

import { createTest } from './flow-error-export';

var resObject = createTest();
console.log(resObject.a);
```

flow result:
```
src/flow-error-import.js:6
  6: console.log(resObject.a);
                           ^ property `a`. Property not found in
  6: console.log(resObject.a);
                 ^^^^^^^^^ object literal


Found 1 error
```

note that flow does not report an error for the resObject in the file where `createTest` was declared so it looks as though this issue relates to flow losing information about the object when it is accessed by another module. Please let me know if there is any other information I can provide.

**Comment by avikchaudhuri** [comment]
This is intentional behavior (designed to catch unintentional errors).

Please annotate the return of `createTest` as `{ [key: string]: number }` if you want to silence the errors.
