### ISSUE TITLE
Difference between $Enum and $Keys

### ISSUE THREAD

**Issue by chrisui** [facebook/flow#2169]
On the face of it they seem to be very similar. Is there some underlying implementation which would lead me to use one over the other?

```
$Keys<typeof obj> === $Enum<typeof obj> it seems
``` 

Also would be great to have a comment on https://github.com/facebook/flow/issues/627 around how we could extract names & values in the context of named/keyed enums.

**Comment by vkurchatkin** [comment]
IIRC they just aliases for the same thing

**Comment by avikchaudhuri** [comment]
Yeah, see https://github.com/facebook/flow/blob/master/src/typing/type_annotation.ml#L275

**Comment by avikchaudhuri** [comment]
Merging with #627

**Comment by chrisui** [comment]
Cheers! :)
