### ISSUE TITLE
Is there something like TypeScripts playground ?

### ISSUE THREAD

**Issue by rogergl** [facebook/flow#217]
Is there something like TypeScript Playground ? It is very helpful to see the inferred types there.

**Comment by unknownexception** [comment]
Going to add inferred type signatures here http://tryflow.org/ in next few days along with other features

**Comment by unknownexception** [comment]
If you are still interested:
![image](https://cloud.githubusercontent.com/assets/1004115/6182032/7d5f12fa-b35e-11e4-963f-8cac4c5b2ac5.png)

**Comment by samwgoldman** [comment]
tryflow is the coolest! @rogergl can this issue be closed now?

**Comment by rogergl** [comment]
Yes it can be closed.

**Comment by samwgoldman** [comment]
Cool. @rogergl, you can close it, but I can't. :)
