### ISSUE TITLE
identifier `HTMLTableRowElement`. Could not resolve name

### ISSUE THREAD

**Issue by kasperpeulen** [facebook/flow#2170]
I have the following code:

```
/* @flow */

export function findTableRowParent(el:HTMLElement):?HTMLTableRowElement {
  while (!(el.parentNode instanceof HTMLTableRowElement)) {
    if (!el.parentNode) {
      return null;
    }
    el = el.parentNode;
  }
  return el.parentNode;
}
```

I get this error:
![image](https://cloud.githubusercontent.com/assets/1035299/17311027/84d92cba-5848-11e6-92ed-299c5b009916.png)

Not sure what is going on here, cuase flow can resolve other dom types like `HTMLTextAreaElement`.

**Comment by avikchaudhuri** [comment]
Looks like it's declaration is not yet in https://github.com/facebook/flow/blob/master/lib/dom.js

Mind sending a PR?
