### ISSUE TITLE
Can flowtype automatically annotate the code?

### ISSUE THREAD

**Issue by xuesu** [facebook/flow#2173]
For example:
`function add(x){return x + 10;}` 
can be changed to:
`function add(x:string){return x + 10;}` 
or
`/*@params {string} x*/
function add(x:string){return x + 10;}`

**Comment by avikchaudhuri** [comment]
How would Flow know you didn't mean `function add(x: number){return x + 10;}`?

In general, no, Flow cannot annotate your code perfectly, but you can try `flow suggest <file>`. It should work well for output types but not so well for input types (as in your example).

**Comment by xuesu** [comment]
thx a lot!
