### ISSUE TITLE
React Native 0.29 - mixins: [NativeMethodsMixin]

### ISSUE THREAD

**Issue by DanielBroad** [facebook/flow#2175]
I'm getting a flow warning for every file in react-native now i've upgraded to 0.29.

```
node_modules/react-native/Libraries/Text/Text.js:89
 89: const Text = React.createClass({
                  ^ super of React component. Cannot inherit
182:   mixins: [NativeMethodsMixin],
                ^^^^^^^^^^^^^^^^^^ statics of function type
```

**Comment by uc-spr** [comment]
Please provide a working example for NativeMethodsMixin in react native

**Comment by thejameskyle** [comment]
What are the versions of both Flow and React Native that you are using and could you provide us with a complete code example that reproduces the error?

**Comment by shirohana** [comment]
Resolved by adding the followings into `.flowconfig`:

##### `.flowconfig`
```
[options]
module.name_mapper='NativeMethodsMixin' -> '<PROJECT_ROOT>/node_modules/react-native/Libraries/Renderer/shims/NativeMethodsMixin.js'
```
