### ISSUE TITLE
Are there some good way to cast `List<number>` to `List<number|string>` ?

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2178]
These code structure are something borrowed from GraphQL (like: GraphQLInputType)

```
type List<T> = { data:T };
type Scalar = number|string|boolean; 
type P = Scalar | List<Scalar>;
```

given those type, are there some good way to direct cast `List<number>` to `P` ?
I tried some method to write correctly code , but get a bit confused.
Currently, seems Flow treat types passed into polymorphic `T` as a integrated type, and did not try to match them.
So `fn` will fail.
But can use `fn1` to around it. but actually this method has no benefit, except increasing redundancy codes .
And especially consider `fn3`, a `{ data:2 }` should be `{ data:number }`, but when typed it ,Flow will fail. If a directly `{ data:2 }` is acceptable, should its type also be accepted?

detail codes:
[flowtype.org/try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAyAlgM4YA8AKgHxgC8YA3qmGACYCGGnAXFagC+AbnTZ8YAMoBjTjE4AnBmAB2AVwC2AIzwKAPuQXEVAcz1a4cGHk4rR4ggAVlMuYrB6iZSq-kKaoqhQairSGMRwKmBQKgAUAG68XuQU6tq6BhhGpjQAlLzOLGwKeBhqClHxwmDAwGC6CnAKQujBoeGR0SoAjAlJJClpOvqGxiZ5BcysYCVlFcwc3Hxg8QB0XDxgIi1BIWERUTEATLH5hdOz5VFMizy8R1uigrvtB10AzKeTRWDSkeS3PhMDZ8Ia6QTKG4g+6PC6lK6A6q1eoKRoKAA0YC0agwYFIAAs4GoYOwFtCHhCVHBcTowJxmNCwQpBAB+FptfadGIAFi+5zYfxUAOhA0oIDojChSxh22K8PmIKerT2HUOKgArH1VJphmcpnK5tdAbx4rDnkA)

```
/* @flow */

type List<T> = {
  data:T
};

type Scalar = number|string|boolean;
type P = Scalar | List<Scalar>;

function fn(v: List<number|string>):P {
  return v; // error
}

function fn1(v: List<number|string>):P {
  return { data: v.data };
}

function fn2():P {
  return { data:2 };
}
function fn3():P {
  const data:{data:number} = { data:2 };
  return data; // error, but should { data:2 } not be a {data:number}?
}
function fn4():P {
  const data:List<*> = { data:2 };
  return data;
}

function fn5(v: number):P {
  return { data:v };
}
```

**Comment by gabelevi** [comment]
If `number | string` is a subtype of `number`, why isn't `List<number | string>` a subtype of `List<number>`?

The problem is that you're assuming that `data` is read-only, but that's not being enforced by anything. In theory, you could write code like this:

```JavaScript
const numList: List<number> = { data: 3 };
const numOrStringList: List<number | string> = numList; // If we let you do this
numOrStringList.data = "hello"; // Then you could do this
(numList.data: number); // And now this is wrong
```

So what's missing is the ability to say that the `data` property is read-only. @samwgoldman is actually working on this right now! Once that launches, Flow will be able to treat the `T` in `List<T>` as covariant.

**Comment by iamchenxin** [comment]
The const feature sounds awesome. I think it will make something work, not sure if all of them.
My mainly problem is, if the type of `{data:number}` can allow to `P`. Cause If it upper cast to a `Scalar`, to recast it to a `number`, there must be a dynamic check , its enforced by Flow. So I think allow this type cast will not cause logic problem.
Actually they are something condensed from here [graphql/ definition.js#L55](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L55)
```
export type GraphQLInputType =
  GraphQLScalarType |
  GraphQLEnumType |
  GraphQLInputObjectType |
  GraphQLList<GraphQLInputType> |
  GraphQLNonNull<
    GraphQLScalarType |
    GraphQLEnumType |
    GraphQLInputObjectType |
    GraphQLList<GraphQLInputType>
  >;
```
I got a more weird way to solve this: (hope the new feature will come soon.)
```
type P<T: number|string> = List<T>;
function ts(v: List<number>):P<*> {
  return v;
}
```

**Comment by iamchenxin** [comment]
! Thank you , The const feature looks awesome!
i think maybe i have some misunderstanding to Flow's `polymorphic`.
previously i think i wrote a more weird way to solve this( but now seems it is the right semantic in Flow)
```
type P<T: number|string> = List<T>;
function ts(v: List<number>):P<*> {
  return v;
}
``
Actually they are something condensed from here [graphql/ definition.js#L55](https://github.com/graphql/graphql-js/blob/master/src/type/definition.js#L55)
```
export type GraphQLInputType =
  GraphQLScalarType |
  GraphQLEnumType |
  GraphQLInputObjectType |
  GraphQLList<GraphQLInputType> |
  GraphQLNonNull<
    GraphQLScalarType |
    GraphQLEnumType |
    GraphQLInputObjectType |
    GraphQLList<GraphQLInputType>
  >;
```
I think when this new feature landed , some of those code could be restruct well.

**Comment by iamchenxin** [comment]
@gabelevi @samwgoldman Im still a bit confused of how to express this type rightly. (though when the const feature landed, seems there maybe have a road to around it).

Here is a condensation of the `GraphQLInputType`'s problem.(Graphql will output .js.flow in recent version, these typo will make  confliction in user's code).

below is a wrong expression of InputType, but can do a recursively expression.
```
type Scalar = number|string;
type InputType =
  Scalar|
  List< InputType >| // Its wrong here, in source code logic
  // List should be List<number> or List<string>
  // but never should be List<number|string>
  NonNull< Scalar| List<InputType> >; // Its same error semantic here.
```
I try to express this type in semantic.
Seems it can be expanded by hand, but i dont know how to express a recursion type like 
`List<List<NonNull<List<List<number>>>>>> `in below style.
```
type InputType2 =
  Scalar |
  List<number> | List<string> | //List< List(how to express a recursion here?) >|
  NonNull<number> | NonNull<string> | 
  NonNull< List<number> >; // same here ,dont know how to express recursively
```
Are there same style to express this rightly?

**Comment by gkz** [comment]
Make it read only: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAyAlgM4YA8AKgHxgC8YA3qmGANQAmAhhtwFxVUAXwDc6bPjABlAMbcY3AE4MwAOwCuAWwBGeJQB9yS4moDmBnXDgw83NeMkEACqrkLlYA0TKV3ipRpxVCgNNVkMYjg1MCg1AAoAN34fcgpNXX0jDBNzGgBKflcWNiU8DA0lGMTRMGBgMH0lOCURdFDwyOjYtQBGJJSSNIy9Q2NTMwKi5lYwMoqq5jAePhTEgDoV7jAxNpCwiKiYuIAmeMLi2fnKmKZl3gETnfFhfc6jnoBmc+mSsFlouR7qsmFt+CN9MJVHcwU9dqVyjdgdxavVGkpmkoADRgHQaDBgUgACzgGhgnCWsJ26jgBL0YG2oIe4O0o2EAH42h1Dt04gAWH6XNgAtRAsFDSggOiMGHMuHiBELGJbF7tA5dY5qACsA3UrP0FxmiqRstWiWebSAA
