### ISSUE TITLE
Required object attribute does not satisfy maybe object attribute

### ISSUE THREAD

**Issue by philikon** [facebook/flow#2182]
Let's say I have a function that processes an object and not in all cases all fields are required. But I want to be very explicit about when I want all fields to be specified and when I'm ok with using the more lax version.

Take this example:
```js
// @flow

type Options = {
  type: string;
  quantity: number;
};

function process(options: Options) {
  processWithOptionalQuantity(options);
};

type OptionalQuantityOptions = {
  type: string;
  quantity?: number;
};

function processWithOptionalQuantity(options: OptionalQuantityOptions) {
  // ...
}
```

`process()` defers its implementation to `processWithOptionalQuantity()`. The advantage for me as a consumer is that when I call `process()`, Flow will be able to tell me if I'm not passing the right kind of object. So if I want the more lax processing function, I explicitly need to call `processWithOptionalQuantity()`.

Sadly, this code produces the following error:

```
 11:   processWithOptionalQuantity(options);
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call
 16:   quantity?: number;
                  ^^^^^^ undefined. This type is incompatible with
  7:   quantity: number;
                 ^^^^^^ number
```

That doesn't quite make sense to me. Am I misunderstanding something?

I'm using Flow 0.30.

**Comment by vkurchatkin** [comment]
The problem is that Flow considers all objects mutable. Optional property is allowed to be deleted, so it's unsafe to have references of types `OptionalQuantityOptions` and `Options` pointing at the same object. To avoid this problem you need to make a copy of original options object.

**Comment by philikon** [comment]
Oh! Good catch. Thanks!
