### ISSUE TITLE
Suppress "Flow is initializing"

### ISSUE THREAD

**Issue by JakeCooper** [facebook/flow#2185]
It would be great if there was a config option to remove this message. Its rather disruptive to the build process.

![image](https://cloud.githubusercontent.com/assets/5499880/17377181/95aa99fe-596d-11e6-8000-67a7adb95e2e.png)

**Comment by gabelevi** [comment]
What build system are you using? You could ignore stderr I suppose, but it would be nice if either flow or the build system handled this more gracefully

**Comment by thejameskyle** [comment]
Why would this ever show up more than once?  Why would this ever show up more than once?  Why would this ever show up more than once?  Why would this ever show up more than once?

**Comment by JakeCooper** [comment]
@gabelevi We're using Webpack, and we only seem to get this spam once when it starts up. Not the end of the world, but we usually want to keep everything as clean as possible :).

**Comment by gabelevi** [comment]
Oh actually this isn't a Windows issue, this happens for everyone. Flow is trying to do a `\r` sort of thing to show a spinner while `flow status` waits for the Flow server to finish initializing or rechecking.

At the very least, if we should check `Unix.isatty` before [clearing the line](https://github.com/facebook/flow/blob/1f1c44269ee2a7473e68531d207154d067a742f0/src/commands/commandConnect.ml#L181). And we probably shouldn't print status messages at all.

**Comment by mroch** [comment]
@gabelevi https://github.com/facebook/flow/blob/1f1c44269ee2a7473e68531d207154d067a742f0/hack/utils/tty.ml#L110

Perhaps webpack is doing something that makes fd 1 still look like a tty instead of a redirection, which would trick `Unix.isatty`.

**Comment by gabelevi** [comment]
@mroch - `print_clear_line` checks `isatty`, the logspew in the picture above is just coming from regular `Utils.prerr_endlinef`.
