### ISSUE TITLE
Document importable types as an alternative to magic includes

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#2189]
I was delighted to recently discover that this is possible with babel transforms:

``` javascript
import type {SomeClass} from '../any-module';

export function getSomething(): SomeClass {
  // ....
}
```

I like this better than relying on magically injected global types via the configured include directory because it's explicit and easier to read.

Is this documented anywhere? I can't find it. It should be documented.

Maybe it needs to be added to https://flowtype.org/docs/type-aliases.html and / or to https://flowtype.org/docs/advanced-configuration.html#include

**Comment by jeffmo** [comment]
It is documented here: https://flowtype.org/blog/2015/02/18/Import-Types.html
...but a blog post is a super undiscoverable place for documentation.

Thanks for this issue, we should move this into the first-class docs.

**Comment by rpominov** [comment]
It is in the docs https://flowtype.org/docs/modules.html#type-imports--exports
