### ISSUE TITLE
Array.find - incorrect definition in lib/core.js

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2191]
Current it is define as :
```
find(callbackfn: (value: T, index: number, array: Array<T>) => any, thisArg?: any): T;
```

The return value should be as ?T.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/find

**Comment by avikchaudhuri** [comment]
That's fair, thanks!

**Comment by szagi3891** [comment]
The next version will fix?
