### ISSUE TITLE
Class declaration file

### ISSUE THREAD

**Issue by NullDivision** [facebook/flow#2192]
I tried creating a flow declaration file for a React component but for some reason it's not working. Maybe I'm missing something.

`./src/MyComp.js`

```
export default MyComp extends React.Component {
    constructor(props) {
        super(props);
    }

    render() {
        return <div />;
    }
}
```

`./src/MyComp.js.flow`

```
declare class MyComp {
    constructor(props: {}): void;
}
```

But I still get an error:

```
 14:   constructor(props) {
                   ^^^^^ parameter `props`. Missing annotation
```

**Comment by avikchaudhuri** [comment]
Having a declaration file doesn't stop Flow from still checking the implementation file for internal errors, etc. If you want to stop Flow from looking at that file, add @noflow in the header instead of @flow.

**Comment by szagi3891** [comment]
Beter add declaration:

```
type propsType = {
//props
};
export default MyComp extends React.Component {
    constructor(props: propsType) {
        super(props);
    }

    render() {
        return <div />;
    }
}
```

**Comment by NullDivision** [comment]
Is there no way to prevent adding annotations directly in the file but still telling flow how it's implemented?

**Comment by Brianzchen** [comment]
Closing as this is quite outdated syntax. React.Component now requires generics `<Props>`.

You can define how a component works with declaration files for consumers of the component, but if you want components to be implemented with flow you have to annotate it directly.
