### ISSUE TITLE
Polymorphic type alias for objects doesn't work with return values?

### ISSUE THREAD

**Issue by emirotin** [facebook/flow#2194]
Sorry if duplicate.

Let's look at this trivial function:

``` js
// @flow

function prefixObj <V>(
  obj: { [key: string]: V }
): { [key: string]: V } {
  var ret = {}

  for (var k in obj) {
    ret['_' + k] = obj[k]
  }

  return ret
}
```

It validates just fine. As we can see, its return type is actually the same as its argument type.
So let's try this:

``` js
// @flow

function prefixObj <V, TObj: { [key: string]: V }>(
  obj: TObj
): TObj{
  var ret = {}

  for (var k in obj) {
    ret['_' + k] = obj[k]
  }

  return ret
}
```

The error is

```
index.js:12
 12:   return ret
              ^^^ object literal. This type is incompatible with the expected return type of
  3: function prefixObj <V, TObj: { [key: string]: V }>(
     ^ some incompatible instantiation of `TObj`


Found 1 error
```

Why is it so? The error message looks extremely cryptic to me.

Add: if I only use the (same) type alias for the input argument it works fine.

---

And also if you excuse me let me ask a related question.
Such signatures assume the object passed acts as a homogenous dictionary, where all the values have the same type. Even if it isn't enforced (I checked the method with the 1st signature called on an object with different value types and didn't get an error) it's implied semantically.
Though, the function like that only cares about the keys being strings.
How am I supposed to define it for that matter? Using `mixed` or `any`, or is there some better / preferred method?

**Comment by gcanti** [comment]
@emirotin this issue seems relevant https://github.com/facebook/flow/issues/1955#issuecomment-237381604

> I checked the method with the 1st signature called on an object with different value types and didn't get an error

```js
const a = prefixObj({ a: 1, b: 's' }) // <= no error because Flow infers V = number | string
```

You can check that by yourself using an IDE which shows the types (for example VS Code with the vscode-flow plugin or Atom with Nuclide https://nuclide.io/docs/languages/flow/#type-hinting) or calling the command `flow type-at-pos [OPTION]... [FILE] LINE COLUMN`

**Comment by thejameskyle** [comment]
So you can simplify this even further down to just:

```js
function coerceToOne<T: number>(n: T): T {
  return 1;
      // ^ number. This type is incompatible with the expected
      //   return type of some incompatible instantiation of `T`

}
```

The reason for this is that polymorphic types exist to reference the *same exact* value through a function or class. Not the *type* of value but the value or a modified version of the value itself. In this case, you can either `return n` or even `return n + 1` and it will work.

So in your `prefixObj` function, when you create a new object you are no longer referring to the original value and it is invalid with a polymorphic type.

Basically you could do something like this:

```js
function modifyObject<T: { [key: string]: number }>(obj: T): T {
  obj.foo = 1;
  obj.bar = 1;
  return obj;
}
```

But not this:

```js
function modifyObject<T: { [key: string]: number }>(obj: T): T {
  var newObj = {};
  newObj.foo = 1;
  newObj.bar = 1;
  return newObj;
}
```

If you wanted to match the "shape" of the object passed in you could do this:

```js
function createShape<T: { [key: string]: number }>(obj: T): $Shape<T> {
  return { foo: 1 };
}

createShape({ bar: true });
                // ^ boolean. This type is incompatible with number
```

> Note: Shape in this case means the type `{ [key: string]: boolean }` not `{ bar: boolean }`.

Hopefully this is helpful

**Comment by emirotin** [comment]
If I understand it properly, basically, it means that as soon as a generic type is _matched_ with the specific value it gets _frozen_, now representing this specific value's type?

While it makes sense from the compiler's point of view it may be confusing to the users. Maybe at least flow can try to detect such usage and generate a more explanative error?

And yeah, I'm aware of `$Shape`, I was going to use it but was surprised by the default behavior in the first place.

**Comment by thejameskyle** [comment]
Yup thats good feedback, we should do a better job of explaining error messages, both by having better error messages and having more documentation around them. I think it'd even be good to create links to the website that explain them in greater detail.

**Comment by emirotin** [comment]
@gcanti yeah, looks related, thanks. 
BTW, my experiments are related to your flow-update :)
Were you aware of it when you wrote the type difs for https://github.com/gcanti/flow-update/blob/master/index.js#L53?

**Comment by emirotin** [comment]
Yeah, links to detailed articles would be great (angular does it and I
think react started doing it recently?), but first it's obviously needed to
detect the errors more specifically.
I have "approximate" understanding how they happen to be generic and how it
may be challenging to detect them earlier, but as of now it's really
challenging to get what's wrong (and I have some basic understanding of
type systems and compilers, including some familiarity with OCaml).

**Comment by mwalkerwells** [comment]
@thejameskyle Can you explain your comment?

> Not the type of value but the value or a modified version of the value itself. In this case, you can either return n or even return n + 1 and it will work.

Just ran into this issue today & was confused. For a primitive type (specifically number), why is a return type of n + 1 any different than n * 1? Specifically, why * considered a "modify?"

**Error:**
```
const mutiplyBy3<T: number>(n: T): T {
  return n * 3;
      // ^ number. This type is incompatible with the expected
      //   return type of some incompatible instantiation of `T`
}
```

**No Error:**
```
const add3<T: number>(n: T): T {
  return n + 3;
}
```

**Comment by mwalkerwells** [comment]
cc @gcanti

**Comment by wchargin** [comment]
I’m not sure what @jamiebuilds is referring to by saying that “The
reason for this is that polymorphic types exist to reference the _same
exact value_ through a function or class.” This is not consistent with
my understanding of Flow.

The actual explanation is very simple. The function

```js
function coerceToOne<T: number>(n: T): T {
  return 1;
      // ^ number. This type is incompatible with the expected
      //   return type of some incompatible instantiation of `T`

}
```

does not typecheck because the constraint `T: number` only requires that
the type `T` be a _subtype_ of `number`, and there is no guarantee that
`1` is a value of this arbitrary subtype. For instance, `7` is a subtype
of `number`, and so is `empty`.

Similarly, the `prefixObj` function defined above does not typecheck
because `TObj` could be `{[key: string]: V, id: number}`, or some class
type `MyClass`.

@mwalkerwells: the fact that your `add3` typechecks is absolutely a bug.

**Comment by gnprice** [comment]
This issue should be closed, because the behavior is correct for the reason explained by @wchargin in the last comment above.

For better or worse, the error message in this case has become less wordy. It now reads:
```
11:   return ret
             ^ Cannot return `ret` because object literal [1] is
    incompatible with `TObj` [2]. [incompatible-return]
References:
5:   var ret = {}               ^ [1]
4: ): TObj{
      ^ [2]
```
without the "some incompatible instantiation" phrasing. The old wording was kind of a lot to unpack, so hopefully the new more-concise version is more helpful for people.

**Comment by darichey** [comment]
As explained above, this is working as intended.
