### ISSUE TITLE
Regression: Can't use default value in parameter object destructuring when type is union

### ISSUE THREAD

**Issue by Macil** [facebook/flow#2198]
This broke in Flow v0.29.0. It worked in previous versions.

``` js
/* @flow */
function f({a=5}: {a: number|Function}) {
}
```

```
$ ./flow29/flow check
test.js:2
  2: function f({a=5}: {a: number|Function}) {
                 ^ function type. This type is incompatible with
  2: function f({a=5}: {a: number|Function}) {
                 ^ number

test.js:2
  2: function f({a=5}: {a: number|Function}) {
                 ^ number. This type is incompatible with
  2: function f({a=5}: {a: number|Function}) {
                 ^ function type


Found 2 errors
```

**Comment by avikchaudhuri** [comment]
@samwgoldman This might be because of `BecomeT` pinning down things after splitting the union?

**Comment by samwgoldman** [comment]
Confirmed. I'm on this.

**Comment by ricardogama** [comment]
@samwgoldman Any update on this?

**Comment by Augustin82** [comment]
We've hit this problem today. We've encountered several open issues on this (such as #183, in the last few comments).

Any way to circumvent that problem?

**Comment by threehams** [comment]
It's not pretty, but you can fall back to what babel compiles to:

```
const Icon = ({ size }: IconProps) => {
  size = size === undefined ? "sm" : size;
```

**Comment by hlomzik** [comment]
@threehams or more es6 way — `props: IconProps` with later destructuring: `const { size = "sm" } = props`

**Comment by augustinr** [comment]
Any updates on this ?

**Comment by zeorin** [comment]
Seems like this is still a problem.
