### ISSUE TITLE
Type alias causes error when in imported file

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#2200]
I was getting some nonsense error messages, and I've finally made a minimal reproduction case:

run.js
```js
/* @flow */

type Fooable = {foo(): Object};
export default function run(f: Fooable) {
  f.foo();
}
```

main.js
```js
/* @flow */

import run from './run';

class Fooish {
  foo(): Object {
    return {};
  }
}

const x = new Fooish();
run(x);
```

```
$ flow version
Flow, a static type checker for JavaScript, version 0.30.0
$ flow
main.js:12
 12: run(x);
     ^^^^^^ function call
  5:   f.foo();
       ^ object type. This type is incompatible with. See: run.js:5
global object


Found 1 error
```

First, something is pretty wrong with the error message: "This type is incompatible with."

Strangely, the error message goes away if I stop using the `Fooable` type and inline its definition in run.js:

```js
/* @flow */

export default function run(f: {foo(): Object}) {
  f.foo();
}
```

Alternatively, putting everything in one file also makes the error message go away:

```js
/* @flow */

type Fooable = {foo(): Object};
function run(f: Fooable) {
  f.foo();
}

class Fooish {
  foo(): Object {
    return {};
  }
}

const x = new Fooish();
run(x);
```

**Comment by jeffmo** [comment]
cc @avikchaudhuri who recently fixed some stuff related to this in master, I think?

**Comment by avikchaudhuri** [comment]
Yup, this is fixed in master (https://github.com/facebook/flow/commit/38da9258758d89dd861c0e7f90f042811f8d32c5), but not in time for 0.30. Should go out in the next release!
