### ISSUE TITLE
Properly type React ref property

### ISSUE THREAD

**Issue by gabelevi** [facebook/flow#2202]
Currently `<Foo ref={...} />` works because we allow extra props to be set on any react element. In a bunch of other places in https://github.com/facebook/flow/blob/master/lib/react.js we type `ref`/`refs` as `any`.

At some point, we should improve the typing of these.

**Comment by asolove** [comment]
Seems like string refs will die before these type changes happen.

**Comment by TrySound** [comment]
String refs will be deprecated since react 16.4. So I this this is not longer relevant and we can close it.

/cc @vkurchatkin
