### ISSUE TITLE
Add `projectRoot` attribute in `flow --json` output

### ISSUE THREAD

**Issue by ryyppy** [facebook/flow#2203]
Right now, I am building a tool for parsing `flow --json` and format the output to a VIM quickfix window friendly format.

My problem is that I get only absolute paths for files causing a flow error, which will lead to messages like this:

```
/Users/me/Projects/test/redux-saga_0.9.5.js:26:5,29: $npm$ReduxSaga$CallEffect | Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)
```

Since some messages can get really long (in one line), I would like to have the possibility to strip the first part of the path and only report relative paths to the given project directory, like this:

```
test/redux-saga_0.9.5.js:26:5,29: $npm$ReduxSaga$CallEffect | Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)
```

To accomplish this, I need to determine the root directory of the project (something I assume the flow server is aware of). Of course, I could calculate this path on my own (VIML etc.), but I think it would be much more consistent (and useful for other tools), to get the `projectRoot` right away in the `flow --json` output like this:

```
{
  "flowVersion": "0.30.0",
  "errors":[],
  "passed":true,
  "projectRoot": "/Users/me/Projects/flow-vim-quickfix"
}
```

**Comment by vkurchatkin** [comment]
What about `--strip-root` option?

**Comment by ryyppy** [comment]
@vkurchatkin I was also thinking about that... for my use-case this would also be sufficient. But I reckon a `--strip-root` is much harder to implement?

**Comment by vkurchatkin** [comment]
> But I reckon a --strip-root is much harder to implement?

well, it's already there

**Comment by ryyppy** [comment]
Oh! Just tried this with `--json` and it works like a charme (so far)... thanks for the help, should really check the `--help` menu the next time 👍
