### ISSUE TITLE
Strange [LIB] in file pathes in `flow --json --strip-root` output

### ISSUE THREAD

**Issue by ryyppy** [facebook/flow#2204]
If I run `flow --json --strip-root` with some errors in libdef files, I will eventually get output like this:

```
{
            "kind": "infer",
            "level": "error",
            "message": [
                {
                    "context": "  | $npm$ReduxSaga$PutEffect",
                    "descr": "$npm$ReduxSaga$PutEffect",
                    "end": 28,
                    "endline": 25,
                    "line": 25,
                    "loc": {
                        "end": {
                            "column": 28,
                            "line": 25,
                            "offset": 550
                        },
                        "source": "[LIB] interface/redux-saga_0.9.5.js",
                        "start": {
                            "column": 5,
                            "line": 25,
                            "offset": 526
                        },
                        "type": "LibFile"
                    },
                    "path": "[LIB] interface/redux-saga_0.9.5.js",
                    "start": 5,
                    "type": "Blame"
                },
                {
                    "context": null,
                    "descr": "Application of polymorphic type needs <list of 1 argument>. (Can use `*` for inferrable ones)",
                    "end": 0,
                    "endline": 0,
                    "line": 0,
                    "path": "",
                    "start": 1,
                    "type": "Comment"
                }
            ]
        }
```

Is there any special reason why there is a `[LIB] "interface/redux-saga_0.9.5.js"` path, when the `--strip-root` flag is enabled?

**Comment by samwgoldman** [comment]
`[LIB]` is prefixed to positions that come from library definitions. I believe the intention is to indicate that the path is not necessarily under the root. For example, the flowlib (files in `lib/*.js` of this repo) are installed into a tmp directory.

Is this format getting in the way of something you would like to do with the JSON output? If so, can you share a little more about your use case?

**Comment by ryyppy** [comment]
I need this for the VIM quickfix list (see https://github.com/ryyppy/flow-vim-quickfix).
It's not getting in the way so far, since I can just strip it via pre-processing.

The thing is, that the quickfix list uses the path to navigate to the next error (`:lne`), which will cause problems, if there is a `[LIB]` in the path. Anyways, if flow doesn't output the full path to the lib itself, it will be problematic to navigate to this file, as soon as it is located in a subdirectory, right?

**Comment by samwgoldman** [comment]
> Just realized, you probably not mean subdirectories, but more like paths to flow's core libs, right?

Right, a lib def path might not be a child of the project root.

FWIW, vim-flow seems to bring up a useful quickfix when there are type errors. I took a peek at the source and it seems like setting the errorformat causes vim to automatically print a short path based on pwd.

**Comment by gabelevi** [comment]
Can you avoid using `--strip-root` and make flow-vim-quickfix relative-ize the paths? You'll still be able to tell which files are lib files by seeing if `loc.type === "LibFile"`

**Comment by ryyppy** [comment]
Oooooh, now that's a mindtrick... alright, so the actual path formatting of `errorformat` works as expected... I got tricked by LIB errors on locations outside of my current projects.. I was super sure they are in my project.

Good, then I will remove the `--strip-root` ... just tested it, works really nice now! :-)

**Comment by ryyppy** [comment]
Thanks @gabelevi & @samwgoldman !
