### ISSUE TITLE
"delete" ignored

### ISSUE THREAD

**Issue by also** [facebook/flow#2207]
Flow 0.30.0 allows `delete a.a` in locations where `a.a = undefined` would trigger an error:

``` javascript
/* @flow */

type A = {a: string};

function deletes(a: A): A {
  delete a.a;
  return a;
}

console.log(deletes({a: 'a'}).a.length);
```

I would expect this to result in an error like:

```
6:   delete a.a;
              ^  undefined. This type is incompatible with
3: type A = {a: string};
                ^ string
```

**Comment by samwgoldman** [comment]
Thanks for the report!

**Comment by vkurchatkin** [comment]
@samwgoldman 
I think the tricky part here is that `delete` works with reference (per spec), not with values. So it's not as simple as making delete behave like a function.

It seems that at the moment `delete` is roughly a function with type `(t: mixed) => boolean`, so when you have something like `delete a.a` Flow treats `a.a` as property lookup, while in fact it's not. For example, this should work:

```js
type A = { -a?: string };

declare var a: A;

const x = delete a.a;
```

But instead we get this:

```
7: const x = delete a.a;
                    ^ object type. Contravariant property `a` incompatible with covariant use in
7: const x = delete a.a;
                    ^ property `a`
```

**Comment by samwgoldman** [comment]
That looks like a variance bug to me, for sure. `delete a.a` is a contravariant use, afaict.

**Comment by vkurchatkin** [comment]
@samwgoldman yep, it just confirms that none of "write" semantics of `delete` is implemented
