### ISSUE TITLE
"array literal. This type is incompatible with Array"

### ISSUE THREAD

**Issue by also** [facebook/flow#2208]
Assigning the `Array` global to a local variable and then using that variable in a type annotation leads to a very confusing error message:

``` javascript
/* @flow */

const A = Array;

// this doesn't work
const a1: A<string> = ['a'];

// but this does
const a2: Array<string> = ['a'];
```

In Flow 0.30.0, I get this error:

```
  6: const a1: A<string> = ['a'];
                           ^^^^^ array literal. This type is incompatible with
  6: const a1: A<string> = ['a'];
               ^^^^^^^^^ Array
```

I'm not sure if this is just an unclear error message or an issue elsewhere, but I was surprised that the type information seemed to be lost in the `A = Array` assignment.

**Comment by samwgoldman** [comment]
Weird! Thanks for the report and the small repro case :)
