### ISSUE TITLE
Non-nullable instance variables should be set in the constructor.

### ISSUE THREAD

**Issue by vishnevskiy** [facebook/flow#2209]
The example is below.

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAWQE8BhHfMAb1TDABcBTXegLjADsBXAWwCNGAJwDc6OoK4cAFAEpqtOmAxwOLMMTABeMAEYwAagYALAJa4AdExajFSlbjgxG5+AHMpAcnqmLV+h4AadRkbMABfVAjMe3owHjIKAm0ORiQScjxcWVF4jPxzCWkQoA

Flow should ensure that `test` is set in the `constructor`.

**Comment by avikchaudhuri** [comment]
Yes! This issue has been on the TODO list for a while. Will see if we can get it expedited.

**Comment by vkurchatkin** [comment]
Duplicate of https://github.com/facebook/flow/issues/650
