### ISSUE TITLE
Support HTML files

### ISSUE THREAD

**Issue by matthewp** [facebook/flow#2218]
Using web components, and HTML Imports it's common to put JavaScript directly into HTML like so:

``` html
<template> ... </template>
<script>
(function(){
  // define a custom element here
})();
</script>
```

You can put these scripts into external files but it's often nicer not to. Would be nice if these `<script>`s could be flow checked.

**Comment by danmindru** [comment]
Same case for .vue (Vue.js) components. There's a nasty workaround in Vue that'll make it work atm (using comments): 

```
/* @flow
<template>...</template>

<style>...</style>
*/

// <script>
...
// </script>
```

It's nasty to say the least & it might break in a future release of Vue. If Flow could parse the <script> tag all of this will go away.

**Comment by SoullessWaffle** [comment]
+💯 

For reference, there is a plugin for ESLint called [eslint-plugin-html](https://github.com/BenoitZugmeyer/eslint-plugin-html) that enables it to lint HTML files.
Perhaps something similar could be developed for Flow.

**Comment by cr0cK** [comment]
Any progress on it? Vue is more and more popular, it should be nice if a solution à la eslint-plugin-html could be added to Flow... Perhaps like an option?

**Comment by scottbedard** [comment]
Has any progress been made on this, or is anyone working on it? This feature is the only thing preventing me from using Flow.

**Comment by therealmarv** [comment]
Is this a possible solution/workaround?
Seperate .vue files at the beginning and let them act as kind of "loader" for .js and .html files like in this [vue 2.0 boilerplate](https://github.com/petervmeijgaard/vue-2.0-boilerplate/tree/master/src/app/pages/login/index). It's this way not ugly looking comments.

Example .vue file:
```
<template src="./index.html"></template>
<script src="./index.js" lang="babel"></script>
```

and place your .html and js file in the same directory (let flow ignore .vue).

**Comment by danmindru** [comment]
That should be fine for standalone, but it won't work for the runtime-only build.

**Comment by therealmarv** [comment]
a workaround for runtime is by using [babel-plugin-tcomb](https://github.com/gcanti/babel-plugin-tcomb). Explanation here http://stackoverflow.com/a/40130503/756056

**Comment by sobolevn** [comment]
You actually can use `flow` with `vue`. 

```js
module.exports = {
  "extends": [
    "standard"
  ],
  "plugins": [
    "html",
    "flowtype-errors"
   ],
   "rules": {
      // raise flow errors
      "flowtype-errors/show-errors": 2
   },
   "parser": "babel-eslint",
   "parserOptions": {
     "ecmaVersion": 2017,
     "sourceType": "module"
    }
}
```

Here's the full example: https://github.com/wemake-services/wemake-vue-template

**Comment by mrkev** [comment]
JS in HTML is a complicated issue. It potentially necessitates a whole new way of building dependency graphs and also introduces the concept of a cross-file global environment.

**Comment by goodmind** [comment]
@mrkev what you mean by cross-file global environment, isn't this already exists with `declare var`?

**Comment by mrkev** [comment]
@goodmind I mean the implicit `window`. I guess it's not _necessary_ per-se, but I was just wondering how we could build a dependency graph with a different way of handling imports/exports.

**Comment by goodmind** [comment]
@mrkev would this require some OCaml HTML parser? jsx parser is not good for html files

**Comment by mrkev** [comment]
@goodmind probably that too for inline JS, yeah.
