### ISSUE TITLE
Errors when using destructuring and union types

### ISSUE THREAD

**Issue by abalhier** [facebook/flow#2220]
Hello !

First thank you for your awesome work on this project ! 👍 

On our project we encountered a bug with flow's handling of destructuring. It seems like it does not deduce the attributes available from the property on which destructuring is applied. This bug can be circumvented by using a generic clone function which does the destructuring :

```
function clone<T>(obj: T) : T {
    return {...obj,};
}
```

There is quiet the same issue when creating an object from a $Shape of its type and filling the object with default values for missing properties. Using an Object instead of a Shape makes the error disappear.

I pushed an example here : https://github.com/abalhier/flowPlayground/blob/master/destructuring.js
Or you can see errors directly [here on flow website](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIICMBnZAJwEMBjZAFQ2wF5dQAfUAIQG5EVbGGBvRKCGg0WAFygA5DkmdhoUgFtYAVwB2yCQH41KxXkzFOAX07csbUP0HDRmCZNaybQtUvugtRYgEs1AcxMzc2wcNVhkAAtDGgtreR8AEwlvP0CXUEgfTGhk3EISCmpaEy5ESHVKH1g1UHJYdFQAMWzcgApSCTCI6OJYzABKUC6Cskp+0AF5erUiBQBhBtRh-O8iif4AOm3STaycxNMueWJMZBViWtJFxtLyyuRq2vrGloOAdR8o+bg1TCaHk8Ol1wlEYrQhiM1uMeFNhDM5tclit8NDinE6r9MB09q1EgMzCczhcrjdUHcKmoqjVMTVMAAeKgAPjasDwACsJFRIaAqJMMqdzpdJttNmz2QAaI7GLiU6nPU6kZCYHBNYiwRQAZUipCwbXQpGIj1I0AA8hyJAASbW6hmowowrBMnn2sbo7BwoSCkn8+TyOwOGQSjLyJSqDQSXTQaDBv3CUUGo0+E3myUZaWywE08iK5Wq9VanVYVOYSj6w3Gs0W0Alygu0brWEC4nCz1+gNSIMh4Rh9SaUBRmPdoQJivJqtp+TSoA).

It seems to happen in flow 0.27+. I didn't try with older versions.

**Comment by gabelevi** [comment]
There seems to be an unfortunate interaction between the new union type algorithms and spreads. It's not clear where to annotate to clear the ambiguity. Small repro:

```
type Foo = { type: 'A'; } | { type: 'B'; };

function copy(a: Foo) : Foo {
    return {...a};
}
```

@avikchaudhuri - mind taking a look?

**Comment by avikchaudhuri** [comment]
@gabelevi Sure, it's on my queue already! (This problem was noted in the new union type implementation...currently spreads have orthogonal bugs in their implementation that interact especially badly with unions).

**Comment by eloytoro** [comment]
@avikchaudhuri any progress with this? this is very frustrating
https://flowtype.org/try/#0C4TwDgpgBACgTgezAZygXigbygWws5AQwHMIAuKZYOASwDtiAaKYGvZAfgroFccAjCHCgAfStXrEoAXwBQsgGY86AY1YI6UAKIqAFggAU2dkVLNW7dFABMMivCTIAlFllQocCMB5xNJkhAA3LLSQA

**Comment by Augustin82** [comment]
Hi all,
we're still encountering the problem.
Any news on this?

**Comment by eloytoro** [comment]
Still happening on master branch

**Comment by thymikee** [comment]
Is this on a roadmap? It would be super nice to use destructured action unions in Redux reducers:

```js
export type Action = Update | Remove;
export default function reducer(state: State = initialState, action: Action) {
  const { type, payload } = action;
  switch (type) {
    case 'UPDATE':
      return {
        ...state,
        [payload.field]: payload.value,
      };
    case 'REMOVE':
      return {
        ...state,
        array: state.array.filter(item => item.code !== payload),
      };
  }
}
```

**Comment by eloytoro** [comment]
In your example if the union type doesn't share the same structure it would
cause an error, I wouldn't type my actions like that

**Comment by thymikee** [comment]
@eloytoro thanks, but I would like to do it, like the docs say: https://flow.org/en/docs/react/redux/#toc-typing-redux-reducers

**Comment by eloytoro** [comment]
you're not following

if your actions dont have the same structure you shouldnt use union types
for them, otherwise deconstructuring them is unsafe.

https://flow.org/try/#0C4TwDgpgBAysCGxoF4oG8oGoBu8A2ArhAFxQDyARgFYQDGwUAvgNwBQrokUAYgPa8BBegEteAOyioMnElABE3MmTkAaKGHgg8veABNSlGvSZsZUAELwATkOCiJUqDNJzzAgEqr1m7XoPU6BhZ2M1t7SR5+MPEoAB8La2ixNlYAMwIxERirCF0CWggrAAoAZwQkUjhECDV4LLFSJIBKSvLoNFYoKFpxMvQncBrvLR1dJgi6u3E2LpKAd2FgWgALKCKZJvROru74EugFJTlSHOACKwkMADobsuq1XEJZSfsrjRG9E22u2j2Dt08JwgZwu-RuVzuSAe+CIpBe4jePlGXx2UF0EFS8AIeGAxG+O1O5wkkIgMyYrEYQA
