### ISSUE TITLE
How to suppress something like `import sass...`

### ISSUE THREAD

**Issue by mikeerickson** [facebook/flow#2230]
I have a line in my index file as:

```
import '!style!css!sass!./app.sass'
```

How can I disable this line, or have @flow skip it all together in any file?  I am sure I can add something to the `.flowconfig` file, but not sure what to skip

**Comment by aackerman** [comment]
Take a look at the `module.name_mapper` portion of the [configuration](https://flowtype.org/docs/advanced-configuration.html#options) options. I don't believe you can skip it, but you can use configuration to work around it.

**Comment by thejameskyle** [comment]
Yup, using that you can create a libdef for those files that just exports `any` since you aren't importing any exports of those modules.

**Comment by mikeerickson** [comment]
@aackerman @thejameskyle awesome thx guys

**Comment by mikeerickson** [comment]
@aackerman @thejameskyle 

Hey guys!  Would one of you kind gentleman help me with this definition.  My regex skills are below average and I cant seem to figure this one out.

As outlined above, I need to have the following pass w/ flow

```
import '!style!css!sass!./app.sass'
```

This is what I have tried, but it doesnt seem to want to work

```
[options]
module.name_mapper='^!style!css!sass![a-zA-Z0-9$_]+$' -> 'app.sass'
```

**Comment by thejameskyle** [comment]
Try this:

**./.flowconfig**

```ini
[options]
module.name_mapper='^!style!css!sass!\(.*\)$' -> './sass.js.flow'
```

**./sass.js.flow**

```js
// @flow

declare export default void;
```
