### ISSUE TITLE
Can't resolve name of destructured function arguments

### ISSUE THREAD

**Issue by migueloller** [facebook/flow#2239]
```es6
/* @flow */

function add({ x, y = x }: { x: number, y: number }): number {
  return x + y;
}
// Identifier 'x' Could not resolve name
```
This specifically happens due to `x` being used as the default value of `y`. Interestingly enough, the error doesn't seem to be reported in [https://flowtype.org/try/](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBDAEwoAoBvMADwBowBPMAXkbAF8AuMPQYDsmALYAjAKYAnFqxHjpM3gEpFk2YNRgwMqfkwzSDMAGo2AblQ9UQA). It is reported if run in the terminal, though.

**Comment by avikchaudhuri** [comment]
Fixed by @samwgoldman in https://github.com/facebook/flow/commit/e047e9194bd3854f3fb7c5bb2eefe4018a38cd0e, should go out in the next release.
