### ISSUE TITLE
"Unexpected token ILLEGAL" error on valid UTF-8 identifier

### ISSUE THREAD

**Issue by vjau** [facebook/flow#224]
Hi,
in my UTF-8 encoded js source, a var name contains the é character (common in french).
Afaik, this is a perfectly valid Ecmascript var name.
However, flow reports an "Unexpected token ILLEGAL" error.
I have not found a configuration option to prevent this.

Thank you in advance for your help.

**Comment by blixt** [comment]
I'm seeing this too for other alphabetic characters that are valid in JavaScript identifiers.

Examples: `ª`, `º`, `Δ`, `Ω`

See this tool to find out what is and is not valid JavaScript identifiers: https://mothereff.in/js-variables

**Comment by mroch** [comment]
Thanks for the report! This was reported again in #521 and @gabelevi commented with a good description of the challenge in fixing this, so I'm gonna close this one even though this one came first.
