### ISSUE TITLE
Subclassing Number

### ISSUE THREAD

**Issue by alexeygolev** [facebook/flow#2241]
It would be really nice if this could typecheck

```
class SNum extends Number {}

const n = new SNum(2)
const m = new SNum(3)

const s = n + m

```

It can serve similar purposes to `newtype` in Haskell.

**Comment by rpominov** [comment]
Seems like it boils down to making Flow understand `.valueOf()`. Since this example works basically because `SNum` inherits constructor and `valueOf` from `Number`, and then under the hood JS does `n.valueOf() + m.valueOf()`.

Btw, this also doesn't work:

```js
const n = new Number(2)
const m = new Number(3)

const s = n + m
```

https://flowtype.org/try/#0MYewdgzgLgBGMF44FMDuMByBXAtgI2QCcAKAJgEoAoUSWHRFdbfI4gZiuvGhggfgDUMHEA

**Comment by alexeygolev** [comment]
@rpominov it would be cool though, wouldn't it? :)

**Comment by rpominov** [comment]
Yea, maybe :)

**Comment by vkurchatkin** [comment]
I don't think there is good reason to subclass `Number` or event use `Number` at all.

**Comment by dralletje** [comment]
@vkurchatkin 
Yet there are some inventive libraries out in JS land that (ab)use `valueOf` for prettier syntax.

**Comment by alexeygolev** [comment]
@vkurchatkin there is no need to us Number. But subclassing it means you can be more specific with types of numbers you're dealing with. Exactly the same way `newtype` in Haskell is a good way to be specific about what values you're dealing with. Another good strategy for these things is phantom type variables (there was an article about using them with flow)

**Comment by vkurchatkin** [comment]
I'm not sure what `newtype` is, but I don't think that subclassing numbers can be more useful than `type Something = number`. For example:

```js
class Minutes extends Number {}
class Kilometers extends Number {}

const result = new Minutes(8) + new Kilometers(13); // <-- makes no sense
```

Even if it's not a problem for you, these types don't compose:

```js
const result = new Mintues(8) + new Minutes(8); // <-- not Minutes
```

**Comment by dralletje** [comment]
This is a very very very exotic example, so I am really not sure if we *want* to support this kind of stuff, but this uses valueOf to make some nice syntax

https://github.com/tobytailor/def.js/

**Comment by rpominov** [comment]
I think if something like `newtype` will be introduced in Flow it should work [similar to PureScrip](https://github.com/purescript/purescript/wiki/Language-Guide#newtypes) (when compiled to JS values are represented as unwrapped values, but Flow/PureScrip treats them as wrapped). Something like this is considered in https://github.com/facebook/flow/issues/465

**Comment by alexeygolev** [comment]
@rpominov yep, that would be much better
