### ISSUE TITLE
Can't destructure array properties (i.e., `length`)

### ISSUE THREAD

**Issue by migueloller** [facebook/flow#2243]
Flow seems to expect the entity being destructured to be an object but it could very well be anything in JS world. It seems to work for [functions](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCmwC4wAxAV2w3wEscwBeMACgEpmA+MAbwF8A3JhwE+YbAEMAtgFMw-MrwkzZZAgCc62AOYLmRbMKA) but not for [arrays](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMAnEgLjAEEyiBPAHiOzoD4wBeMAbQF0BuTDgJgA3mBgBTbAHN8ACzABfSuKmyFlbAFcAtgCNJJZZ2JlBQA).

**Comment by samwgoldman** [comment]
Thanks for the report! This should work as you expect.

**Comment by SamChou19815** [comment]
Destructuring now works for arrays.
