### ISSUE TITLE
Annotating prop that is a class

### ISSUE THREAD

**Issue by NgoKnows** [facebook/flow#2244]
So I have a class that I am passing into a React component, and in that React Component I have

```
import myClass from 'classes/myClass';

class myComponent extends Component {
  props: {
    classProp: myClass
  }
}
```

In the myClass class I am annotating it within that file, but the classProp prop is not being checked properly by flow.

**Comment by gcanti** [comment]
The first letter must be capitalized: **M**yComponent

**Comment by NgoKnows** [comment]
Sorry yeah, in my use case it's capitalized, this is just an example. My question is, is the way to annotate a prop that is a class, is to use the class itself as an annotation?

**Comment by samwgoldman** [comment]
If you define a class, the class name can be used as the type of *instances* of that class and its subclasses. You can use the `Class<C>` type to describe the class itself:

```js
/* @flow */

class A {}
class B extends A {}
class X {}

var instA: A = new A; // ok
var instB: A = new B; // ok, subclass
var instX: A = new X; // error, X <> A

var clsA: Class<A> = A; // ok
var clsB: Class<A> = B; // ok, subclass
var clsX: Class<A> = X; // error, X <> A
```

Does that answer your question?

**Comment by dralletje** [comment]
Just a small thing @gcanti, classes do not require to be capitalized. Lowercase works just fine, it's just that we use capitalised class names to make it easier for us to read code 😃

**Comment by gcanti** [comment]
@dralletje non capitalized react components don't type check using JSX

```js
class myComponent extends React.Component {
  props: { a: number };
}

<myComponent /> // <= no error

class MyComponent extends React.Component {
  props: { a: number };
}

<MyComponent /> // <= error: property `a`. Property not found in props of React element `MyComponent`
```

**Comment by thejameskyle** [comment]
Hopefully Sam's answer covers the question well enough, but heres a flow/try you can play around with if you want to experiment with it:

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxDsBnfAQzwFMAKKOOALjADEWBKMAbwC+GHAWKl8ATwAOdAPJQmLdpJlwonHvyFY8REmADWMahQqK2YAMLHTAHi5wAfL0HpgwMAFpvP33-8BgQHouDYUGnBa6ORUtLiM2HRIDgzc3ADcqDE09AwOGegqcgqJySypBUXyeTyZqEYmZqURFZkNpjVwBajuXkH9A4MhYWAAQtQATmB0AB74dNgAJuEOUVmUOfEMzeMTreuxubvdVSVJY5P7pwzHde1N57v79zeT3b2Dn1++w40XAF5rbJxBKPaj-fbAo7gk7SYrbMEQtKZa7jf7dF47cHPMKvdGZIA
