### ISSUE TITLE
Export a polymorphic type in libdefs ?

### ISSUE THREAD

**Issue by njakob** [facebook/flow#2245]
I was looking for the correct way to write a libdefs that directly expose a polymorphic type. During my research I ran into the definition of [`lru-cache`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/lru-cache_v4.0.x/flow_%3E%3Dv0.26.0/lru-cache_v4.0.x.js). Is the following the only correct way to declare it?

**decls/lru-cache-1.js**
```
declare module 'lru-cache' {
  declare type LRUCache<K, V> = {
    set: (key: K, value: V) => void;
    get: (key: K) => V;
  }

  declare function exports<K, V>(): LRUCache<K, V>;
}
```

Would it be possible to transform that declaration with a `class` instead of a `type` and having polymorphic parameters? The main issue there is the `exports` syntax.

**decls/lru-cache-1.js**
```
declare class lruCache$LRUCache {
  set(key: string, value: number): void;
  get(key: string): number;
}

declare module 'lru-cache' {
  declare var exports: Class<lruCache$LRUCache>;
}
```

**Comment by dralletje** [comment]
It seems like you just want to do

```javascript
declare module 'lru-cache' {
  declare class exports<K, V> {
    set(key: K, value: V): void;
    get(key: K): V;
  }
}
```

Hard part here is that you can also use lru-cache **without `new`**, which I think is not supported by flows class syntax at all.

What is wrong with the functions declaration?

**Comment by njakob** [comment]
@dralletje That's a possibility to directly export the class, never tried that way, thank you for the hit.

I brought the lru-cache because that was the only example I found with a polymorphic type directly exposed by the `exports` in a library. However, my question wasn't directly related to this specific use-case. 

The only issue with this solution is you don't have a global definition (eg. `lruCache$LRUCache`) in case you wont to reference the class into another library declaration. Or simply if you want to reference the class elsewhere into the declaration file.

**Comment by thejameskyle** [comment]
I'm not sure how you're trying to use it that this doesn't cover:

```js
import type {LRUCache} from 'lru-cache';

function foo<A, B>(bar: Class<LRUCache<A, B>>) {
  // ...  
}
```

**Comment by njakob** [comment]
I managed to come with a solution that fill all my requirements with all your hits. So here was clearly what I tried to do and how I resolved it:

* Module that expose a polymorphic type by default
* Be able to use the type both for flowtype check and runtime usage
* Provide a global declaration for other libraries

**lib/foo.js**
```js
// @flow

declare class foo$Bar<T> {
	foo(v: T): void;
}

declare module 'foo' {
	declare type Bar<T> = foo$Bar<T>;
	declare class exports<T> extends foo$Bar<T> {}
}
```

**lib/test-foo.js**
```js
// @flow

declare module 'test-foo' {
	declare function exports<T>(v: foo$Bar<T>): void;
}
```

**example-1.js**: Runtime usage of the type
```js
// @flow

import Bar from 'foo';

const f: Bar<number> = new Bar();

function t1(b: Bar<number>) {
	b.foo(1);
}

function t2(b: Bar<number>) {
	b.foo('1');
}
```

**example-2.js**: Flowtype check only
```js
// @flow

import type { Bar } from 'foo';

function t1(b: Bar<number>) {
	b.foo(1);
}

function t2(b: Bar<number>) {
	b.foo('1');
}
```

Thank you for the help !
