### ISSUE TITLE
Using babel with basic setup, import/export is not transpiled to ES5

### ISSUE THREAD

**Issue by olleharstedt** [facebook/flow#2246]
Not sure if it's intentional or not, but when setting up Babel as on the Flow homepage, import/export keywords will remain in build code, not working in browsers.

**Comment by rpominov** [comment]
I believe Flow docs only describe how to use Babel for removing Flow annotations from JavaScript. If you use any other new JavaScript features that don't supported by browsers etc. you should check Babel docs to find out how to compile those to ES5.

**Comment by olleharstedt** [comment]
Yes, thanks you, it was pointed out to me that import/export is ES6 features and not related to Flow. I'm using Browsify now, together with CommonJS module style.

**Comment by olleharstedt** [comment]
By the way, is it possible to have a project split up in many files _without_ using modules in Flow?

**Comment by rpominov** [comment]
You mean just add several `<script>` tags in HTML for each JS file? Not 100% sure, but I think Flow doesn't support this use-case. You have to use either ES6 modules or commonjs (node style) modules in order for Flow to typecheck all files as a whole.
