### ISSUE TITLE
Cannot declare interface

### ISSUE THREAD

**Issue by olleharstedt** [facebook/flow#2247]
According to the docs in https://flowtype.org/docs/declarations.html, this should be possible:

```
declare interface MyInterface {
  foo() : number;
}
```

Yet I get this error:

> Use of future reserved word in strict mode

**Comment by rpominov** [comment]
I can't reproduce this. Do you get the error from `flow` command or maybe from `babel` for instance?

**Comment by olleharstedt** [comment]
No, it's from `flow check`. I'm using version 0.13.1.

**Comment by olleharstedt** [comment]
Wow, I'm sorry, did an Opam install of the package and now it's up to date (version 0.29.0). No idea how I managed to get such an old version installed.
