### ISSUE TITLE
Constructor cannot be called on XY

### ISSUE THREAD

**Issue by stephanos** [facebook/flow#2249]
Hey there,

I'm desperately trying to integrate `nedb` into my project and have it type checked. But I just don't get it.

This is the code:

```
import Datastore from 'nedb';
...
db = new Datastore();
```

This is my declaration file:

```
declare module 'nedb' {
  declare class Datastore {
    constructor(): void;
  }

  declare module.exports: Datastore;
}
```

and the error message is:

```
 18:     this.db = new Datastore();
                   ^^^^^^^^^^^^^^^ constructor call. Constructor cannot be called on
  18:     this.db = new Datastore();
                       ^^^^^^^^^ Datastore
```

I couldn't really find anything helpful in the documentation.

Can you please give me some pointers?

**Comment by njakob** [comment]
You're not that far, in order to make it works you have two different possibilities:

```
declare module 'nedb' {
  declare class Datastore {
    constructor(): void;
  }
  declare module.exports: typeof Datastore;
}
```

```
declare module 'nedb' {
  declare class Datastore {
    constructor(): void;
  }

  declare module.exports: Class<Datastore>;
}
```

Sadly, the documentation doesn't cover a lot of libdefs. However, you can find a lot of useful examples in [Flowtyped](https://github.com/flowtype/flow-typed).

**Comment by stephanos** [comment]
ah, thanks :)
yeah, the documentation is pretty sparse on this part.

**Comment by MoOx** [comment]
I am getting the same issue with a built-in type "Date".
I have a `new Date(string)` and flow tells me "constructor cannot be called on type `date`" :/

**Comment by vkurchatkin** [comment]
If `Date` is used as a type, it means instance of `Date`, not `Date` constructor

**Comment by MoOx** [comment]
I am just making a `new Date(string)` and passing this as a props to a component that is defined like this `FormattedDate: Class<React$Component<*,*,*>>;` (because I am lazy). Not sure to understand what I am doing wrong (if I am).

**Comment by thejameskyle** [comment]
@MoOx could you give a full example

**Comment by MoOx** [comment]
Here is a snippet:

```js
//...

import type { CommunicationSummaryType } from "./types.js"

type Props = CommunicationSummaryType

const CommunicationSummary = (props: Props): React$Element<any> => {
  const dateTime = new Date(props.creationDate + "T" + props.creationTime)
  return (
    <Grid>

// ...
```

The imported type

```js
export type type CommunicationSummaryType = {
  // ...
  creationDate: string,
  creationTime: string,
}
```

The error

```
constructor call: /.../src/app/Communication/Summary.js:18
Constructor cannot be called on
type `Date`: /.../src/app/Communication/Summary.js:18
```

Happening with flow 0.30.0 & 0.32.0

I tried to reproduce here https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AYVgLYECuAdgJYDGAhiubKQMrFHUBOaAKpjgLygBvRKFCU2WWvVIARWlgBcoAM4o25UgHMANMNHjJDTuQILlq9dsQBfZOmygACm1gYlofviJkqBpiwLsXDzIlAwqeIQkFDR0DMysHO6gABQYzq6KTi5KAJTuAHyCuqGk4QAmckYmSaRY8KCyKFip6UoAdGISsTJyoADUoABEnIP9oGnZHfrdVVg51kA
but no luck. Not sure what can cause this issue...

**Comment by mwalkerwells** [comment]
> If Date is used as a type, it means instance of Date, not Date constructor

@vkurchatkin Funny how easy that is to forget...

**Comment by MoOx** [comment]
In my case (for `Constructor cannot be called on type Date`) I basically got a flow interface definition that got a `type Date = ` defined...

So pretty sure it's a PEBKAC for everyone in this thread :)

**Comment by SamChou19815** [comment]
This should be covered by https://flow.org/en/docs/types/utilities/#toc-class
