### ISSUE TITLE
Flow fails to infer that `[t]` is valid `[?t]`

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2253]
Here is a code to illustrate this issue:

``` js
/* @flow */

type Image = { url: string }
declare function updateImage (model:Image):[Image]

export const maybeUpdateImage =
  (model:?Image):[?Image] =>
  ( model == null
  ? [model]
  : updateImage(model)
  )
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAtgIYDmBAvGAN5gCuATjAFxgDOGTAlgHbkwAX1QATPAGMYpJgSgM+EjDzh9GOUaQx4SFAgApiccW12UAlKwDaZvAF10eAB444TDGAmquYMlgBGeACqGlo6ZJRgVKhgYIbGeGwA-LaWVikR9lEAfDFxvgkwUTR8DDAweUlgVkYmDrHsDKHatvEm5nnmQA

Which fails with a following error:

```
 (model:?Image):[?Image] =>
                      ^ null. This type is incompatible with
4: declare function updateImage (model:Image):[Image]
                                               ^ object type
7:   (model:?Image):[?Image] =>
                      ^ undefined. This type is incompatible with
4: declare function updateImage (model:Image):[Image]
                                               ^ object type
```

Interestingly enough unboxing and reboxing a value resolves the issue:

``` js
/* @flow */

type Image = { url: string }
declare function updateImage (model:Image):[Image]

export const maybeUpdateImage =
  (model:?Image):[?Image] => {
    if (model == null) {
      return [model]
    }
    else {
      const [image] = updateImage(model)
      return [image]
    }
  }
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAtgIYDmBAvGAN5gCuATjAFxgDOGTAlgHbkwAX1QATPAGMYpJgSgM+EjDzh9GOUaQx4SFAgApiccW12UAlKwDaZvAF10eAB444TDGAmquYMlgBGeACqGlo6ZJRgVKhgYIbGeGwA-LaWVikR9lEAfHQxsWA8UHFGJlE0fAwwMOZ5BQWyGMxqVqWJDvUi9YkcBLT59V58PlY8mXZR6pratvEm5gMNeE1MLWN6HQVdwkA

There for I suspect that flow fails to infer that `[image]` type returned by `updateImage` is compatible with (due being a subset of) `[?image]`, but reboxing an `image` somehow triggers inference.

**Comment by vkurchatkin** [comment]
Makes sense, arrays are invariant, so `[Image]` is not a subtype of `[?Image]`

**Comment by Gozala** [comment]
> Makes sense, arrays are invariant, so `[Image]` is not a subtype of `[?Image]`

Can you give me an example where tuple `[t]` is not compatible with expected expected tuple `[?t]` ? Otherwise I have hard time seeing how that makes sense.

**Comment by vkurchatkin** [comment]
Here is what happens if you make `[Image]` subtype of `[?Image]`:

```js
const image: [Image] = [image];
const maybeImage: [?Image] = image;
maybeImage[0] = null;

image[0].url // <-- runtime error
```

**Comment by Gozala** [comment]
Oh so it's pretty there only to guard against mutations in the tuple :( Ok that explains why reboxing a value resolves the issue as well.

**Comment by vkurchatkin** [comment]
Yep. Immutability is the key to make such use cases work
