### ISSUE TITLE
Unable to detect divergent polymorphic types

### ISSUE THREAD

**Issue by msiebert** [facebook/flow#2254]
I'm not sure if this a bug or if I just haven't uncovered the documentation on how to do this, but I want to be able to have a function that takes two functions as parameters, and have flow enforce that the two functions return the same type. However, both locally and in the "try flow" editor, the following code yields no errors, even though one function is returning a string and the other returns a number:

``` javascript
function test<A>(a: () => A, b: (num: number) => A): A {
  if (Math.random() == 0)
    return a()
   else {
     return b(1)
   }
}

test(() => 'a', (num: number) => 1)
```

Any help would be much appreciated! :smile:

**Comment by vkurchatkin** [comment]
Flow infers that `A` is `string | number` in this case. Not sure that there is some simple way around this.

**Comment by msiebert** [comment]
Darn, that's too bad. Do you know if there's some way to hint what `A` should be? Like something like:

```javascript
test<string>(() => 'a', (num: number) => 1)
```

**Comment by vkurchatkin** [comment]
In your case probably `var a: string = test(() => 'a', (num: number) => 1)` is the easiest way

**Comment by msiebert** [comment]
Ah ok. I would have hoped that this could be detected automatically, but I guess that's difficult with union types. Thanks for your help!

**Comment by avikchaudhuri** [comment]
@msiebert Thanks for the excellent example! This points to a limitation of subtyping-based inference, which often under-constrains the system until a real error is found (which is why the return type casting of @vkurchatkin causes an expected error). Good to keep this example in mind for docs and future work!

**Comment by iamchenxin** [comment]
This is a good example for Union Types in polymorphism, should docs this to Union Types?
@avikchaudhuri Hope do not remove this feature, its a powerful mechanism to collect type information.

**Comment by SamChou19815** [comment]
This is expected. If you don't like the inference result, you can always annotate the type argument explicitly.
