### ISSUE TITLE
Typing Class and Properties with Flow

### ISSUE THREAD

**Issue by sandysaders** [facebook/flow#2259]
Hello,

I'm new to Flow and I'm trying to type classes but I get odd responses from flow:

Say I have a sample classes like this:
```js
class Node {
  data: any;
  next: any;
  constructor (data: any) {
    this.data = data;
    this.next = null;
  }
}

class Stack {
  top: ?StackNode;
  next: any;
  pop: Function;

  constructor () {
    this.top = null;
  }

  pop (): ?StackNode {
    if (this.top === null) return null;
    var item: any = this.top.data;
    this.top = this.top.next;
    return item;
  }

  push (item: StackNode): void {
    var stackElement: StackNode = new StackNode(item);
    stackElement.next = this.top;
    this.top = stackElement;
  }

  peek (): ?any {
    if (this.top === null) return null;
    return this.top.data;
  }

  isEmpty (): boolean {
    return this.top === null;
  }
}
```
when I run flow I get: 
```
 23:     var item: any = this.top.data;
                                  ^^^^ property `data`. Property cannot be accessed on possibly undefined value
 23:     var item: any = this.top.data;
                         ^^^^^^^^ undefined

 24:     this.top = this.top.next;
                             ^^^^ property `next`. Property cannot be accessed on possibly undefined value
 24:     this.top = this.top.next;
                    ^^^^^^^^ undefined

 36:     return this.top.data;
                         ^^^^ property `data`. Property cannot be accessed on possibly undefined value
 36:     return this.top.data;
                ^^^^^^^^ undefined

```
I'm not sure how to fix this, I want to return null when empty on purpose. Is there a best practice alternative to this in the flow community?

When I run something similar to this I get the following from webpack:
```
Module build failed: SyntaxError: Missing class properties transform.
```
But they are flow types and I'm using  `babel-plugin-transform-flow-strip-types`

Also in the Docs I see and tried to read explanations but I don't understand why/when to use something like this:
```js
class Page <[someLetters]> { // what do the angle brackets and letters within them mean?

}

class Book <[someLetters]> {

}
```

**Comment by rpominov** [comment]
`?StackNode` means `StackNode | null | void`, so you need to check for `undefined` too:

```diff
- if (this.top === null) return null;
+ if (this.top === null || this.top === undefined) return null;
```

Or:

```diff
- if (this.top === null) return null;
+ if (this.top == null) return null;
```

**Comment by sandysaders** [comment]
@rpominov thanks for that! do you have any suggestions about the webpack error?

**Comment by thejameskyle** [comment]
Alternatively you can just check:

```js
if (!this.top) return null;
```

You don't really have to worry about other falsey values as mentioned above `this.top` can only ever be `StackNode`, `null`, or `undefined`.

**Comment by rpominov** [comment]
@sandysaders You probably need to use [transform-class-properties plugin](http://babeljs.io/docs/plugins/transform-class-properties/) to fix `Missing class properties transform` error.

**Comment by thejameskyle** [comment]
> what do the angle brackets and letters within them mean?

Those are polymorphic types. They allow you track a single value through a function or class. i.e.

```js
function identity<T>(input: T): T {
  return input;
}

identity({ foo: 1 }).foo; // Flow knows that the object will be returned.
```

**Comment by thejameskyle** [comment]
See the docs on polymorphic classes: https://flowtype.org/docs/classes.html#polymorphic-classes
and the docs on polymorphic functions: https://flowtype.org/docs/functions.html#polymorphic-functions

**Comment by sandysaders** [comment]
@rpominov okay I guess I'll just add in the babel-plugin.
@thejameskyle I tried reading the docs on polymorphic-classes 3 times, but it just didn't make much sense to me at all. 😭

**Comment by thejameskyle** [comment]
@sandysaders I'll try to improve them, I'm sorry that they confuse you right now. I promise you that they are actually quite simple once they click in your head, we just need to do a better job of getting there.

I'm going to close this issue since it seems like everything has been answered. Feel free to continue commenting
