### ISSUE TITLE
mixins in React Component results in: object literal This type is incompatible with mixins of React class

### ISSUE THREAD

**Issue by tommilimmot** [facebook/flow#226]
```js
/* @flow */

var ViewControllerMixin = {
  updateState: function () {},
  resetState: function () {}
}

module.exports = ViewControllerMixin;
```

```js
/* @flow */

var ViewControllerMixin = require('./ViewControllerMixin');

var component = React.createClass({
  mixins: [ViewControllerMixin], //Error on this line: object literal This type is incompatible with mixins of React class
  render: function () {
    return null;
  }
}
```

Flow created a folder _flow\_declarations_ with a _react.d.js_ file that lacks the __mixins__ property declaration. 
Is this error related to that?

**Comment by tommilimmot** [comment]
...And the error goes away when I remove ```/* @flow */``` from the ViewControllerMixin file.

So, does one have to create a flow declaration for every mixin, or is this related to something else?

**Comment by bakesteve** [comment]
seems to stem from https://github.com/facebook/flow/blob/master/lib/react.js
is there anyway to override this within flow? I tried adding a react.js file into my definitions folder I pass into flow, but that then just throws a ton of errors:
```
inconsistent use of library definitions
  [LIB] react.js:12:1,18:1: ReactClass
This type is incompatible with
  [LIB] react.js:12:1,18:1: ReactClass
```

**Comment by arypurnomoz** [comment]
+1

**Comment by gabelevi** [comment]
We're aware of this issue. Our solution will be to use `React.createMixin()` (added in https://github.com/facebook/react/commit/295ef0063b933e13b2ddd541c108b386b35b648b). [Currently it is just the identify function](https://github.com/facebook/react/commit/295ef0063b933e13b2ddd541c108b386b35b648b), but it lets us infer which objects are react mixins. Once this is in, you'll just need to do

```JavaScript
var ViewControllerMixin = React.createMixin({
  updateState: function () {},
  resetState: function () {}
});
```

Thanks to @sebmarkbage for adding it to React!

**Comment by samwgoldman** [comment]
The original code example no longer produces an error. Whether that is a bug or a feature is unclear to me, but I suspect this issue can be closed.

**Comment by tommilimmot** [comment]
Wow! So it seems on Flow 0.10.0.

@gabelevi, is React.createMixin( ) still on track? Seems that it isn't needed anymore, at least for this.
