### ISSUE TITLE
support for 32 bit systems

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2262]
you can add support for 32-bit systems?
I would like to use the module from npm "flow-bin" in my 32-bit linux.

**Comment by gabelevi** [comment]
https://github.com/facebook/flow/issues/270 has some context on why this is hard. The shared memory implementation assumes 64 bit, and it would be difficult to re-write for 32 bit.

**Comment by szagi3891** [comment]
I suggest closing this issue.

**Comment by goodmind** [comment]
Duplicate of https://github.com/facebook/flow/issues/270
