### ISSUE TITLE
How to declare third party code

### ISSUE THREAD

**Issue by montogeek** [facebook/flow#2263]
Hi!

After ask on Discord and Twitter without response I am asking here:
I am trying to write https://stripe.com/docs/stripe.js declarations for https://github.com/flowtype/flow-typed.git, following this guide https://medium.com/@thejameskyle/flow-mapping-an-object-373d64c44592#.t2m25uqbn and https://flowtype.org/docs/third-party.html without success

.flowconfig
```
[libs]
decls/.*
```

decls/decl.js
```
/* @flow */

declare class Stripe {
  setPublishableKey(key: string): void;
}

declare var Stripe: Stripe;
```

src.js
```
/* @flow */

Stripe.setPublishableKey('key');
```

Error:
identifier `Stripe`: Could not resolve name

**Comment by aackerman** [comment]
In this case you would want to add the `static` identifier to the `setPublishableKey` method.

And use the following in your `.flowconfig`

```
[libs]
decls/
```

**Comment by aackerman** [comment]
@montogeek was that able to solve your issues?

**Comment by thejameskyle** [comment]
```diff
  [libs]
- decls/.*
+ decls/
```

**Comment by montogeek** [comment]
@aackerman Yes, thank you
