### ISSUE TITLE
Array.map doesn't work with union of Array types

### ISSUE THREAD

**Issue by janicduplessis** [facebook/flow#2264]
Here is a small example to reproduce the issue. Since both types in the unions are arrays I assume flow should be able to handle this case properly.

``` js
const a: Array<number> | Array<string> = ['www'];
test(a);

function test(array: Array<number> | Array<string>) {
  return array.map(a => a);
}
```

```
1042:   test(array: Array<number> | Array<string>) {
                                          ^^^^^^ string. This type is incompatible with
1042:   test(array: Array<number> | Array<string>) {
                          ^^^^^^ number
```

Flow version 0.30.0

**Comment by avikchaudhuri** [comment]
This is due to an approximation made by Flow to prevent non-termination, where the instantiation of any generic type (like `Array`) on a method call (like `map`) is fixed. So it can be either `number` or `string`, but not both.

Will try to see if something can be done for explicit unions.

**Comment by oonsamyi** [comment]
flow v0.87.0

This behavior is very strange:
```js
declare var arr: string[] | number[]

arr.map(x => x) // Error
;(arr: string[] | number[]).map(x => x) // No error
```

**Comment by oonsamyi** [comment]
I think it's temporary solution:
```js
declare var arr: string[] | number[]

;(arr: $ReadOnlyArray<string | number>).map(value => value)
```
We downgrade string[] to  `$ReadOnlyArray<string | number>` and number[] to `$ReadOnlyArray<string | number>`. In order to downgrade Array type it should be covariant (`$ReadOnlyArray`).

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
