### ISSUE TITLE
[End_of_file] error

### ISSUE THREAD

**Issue by tomitrescak** [facebook/flow#2268]
Hi, not sure what is going on, but following always results into End_of_file error.

```js
// file one has following import
import mf from '../configs/i18n'; 
```

i18n file

```js
// this is the i18n file
const mf = (key: string, params?: Object): string => {
  return key;
};  

export default mf; 
```

**Comment by avikchaudhuri** [comment]
Sorry, couldn't repro. What version of flow are you running?

**Comment by tomitrescak** [comment]
I really tried to create a reproducible repo but I failed ;(( It seems to appear at random times now :/ I close this until I'll find the exact culprit.

**Comment by mjomble** [comment]
@tomitrescak Are you by any chance using Mercurial on Windows? See #4960
