### ISSUE TITLE
Generic return type

### ISSUE THREAD

**Issue by tomitrescak** [facebook/flow#2270]
Is it possible to have functions with generit return types, based on generic parameter?

```js
function a<T>(): T {
}

// calling
let m: ExistingType  = a<ExistingType>();
```

If you ask why is this useful, then it is very useful when creating containers for react components, where I can specify the props of the container.

For example:

```js
// redux connect is defined as:
export function connect<T>(funcs: IConnectFunctions): (component: any) => React.StatelessComponent<T>;

// then I can create my container as following

interface IProps {
  id: string;
}

const mapStateToProps = (context: Context, state: State, ownProps: IProps): IComponentProps => ({
  html:state.texts[id]
});

export default connect<IProps>({ mapStateToProps })(Component); // this line currently fails
```

If I do it like this, i get warnings if component is not used with correct props (this is done in typescript)

**Comment by vkurchatkin** [comment]
No it's not possible. A function can't return T if no T is passed in. So what you want is inherently unsafe.

**Comment by tomitrescak** [comment]
Fair enough. Thanks.

**Comment by rpominov** [comment]
You could do:

```js
return (({html:state.texts[id]}: any): React.StatelessComponent<T>)
```

In which case `connect<IProps>({ mapStateToProps })(Component)` would be just another way to do unsafe typecast.

Another option is to remove type argument from the function and just to do unsafe typecast outside:

```js
export default ((connect({ mapStateToProps })(Component): any): React.StatelessComponent< IProps >)
```

But anyway as @vkurchatkin already pointed out this is unsafe. It'll be programmer's responsibility to manage types, Flow won't check them. Still it might be reasonable sometimes.

**Comment by rpominov** [comment]
Ah, sorry. I've misunderstood the code. Something like this would have to be in redux code. If types come from implementation file.

But actually nevermind what I wrote in first comment. This is not possible. @vkurchatkin was right. You can't specify type argument when calling a function. Flow doesn't have syntax for this. Probably exactly for the reason that it would be unsafe anyway.

**Comment by vkurchatkin** [comment]
There is one trick:

```js
function trick<T>(token: ?T): T {
}

const num = trick((null: ?number));
```

It's simplier just to return `any`, though
