### ISSUE TITLE
Disabling node_modules directory breaks React functionality

### ISSUE THREAD

**Issue by tomitrescak** [facebook/flow#2275]
Hi, when I put node_modules into [ignore] section of .flowconfig, the React import no longer recognizes React.Component and everything else. I even tried copying the react declaration to the libs folder and still nothing. 

Flow says that React does not contain "Component" as `React.Component`.

Any idea? Thanks.

**Comment by tomitrescak** [comment]
I have nailed the culprit but it looks like a bug in flow. I have created a reproducible repo here: https://github.com/tomitrescak/flow-crash-example.git

I know its a bit of files, but the only file one needs to focus on is the "src/declarations/semanticui-react.js".

When you run 'flow' in the project now you will see no errors (only eslint crashes on the declaration of the class), but when you try to make eslint happy and you change 

```
import React from 'react';
```

to

```
import { Component } from 'react'; 
```

Flow stops to recognise Component in React and throws several errors. Any idea what could be going wrong?

**Comment by tomitrescak** [comment]
The fastest way to reproduce this behaviour in the other manner is:

```
git clone https://github.com/tomitrescak/flow-crash-example.git
cd flow-crash-example
git checkout Case2
flow
```

this results to:

```
^^^^^^^^^^^^^^^^^^ Component. Property not found in
158: declare module react {
     ^ module `react`. See lib: /private/tmp/flow/flowlib_1f851f42/react.js:158
```

When I open that file, I can clearly see the declaration.

Now, when you uncomment the copied over definition of react in `src/declarations/react.js`. Everything compiles well.

**Comment by danez** [comment]
Why do you ignore node_modules completely, there might be flow declarations in there that would could make your type information more rich?

**Comment by TrySound** [comment]
Just don't ignore `node_modules`.

This probably can be closed.
/cc @vkurchatkin

**Comment by tomitrescak** [comment]
@TrySound good one. Closing this. Not using flow anymore. Thanks @danez for your reply.
