### ISSUE TITLE
Flow ignores incorrect tuple members

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2277]
According to docs:

> Given types T0, T1, …, Tn, a tuple type [T0, T1, ..., Tn] is an array. That array has a general type Array<T0 | T1 | ... | Tn>
> ...
> values >= n can still exist as long as they are consistent with the general element type of the array

but this type-checks:

``` js
var g: [number, string] = [123, 'duck', {}]
```

**Comment by samwgoldman** [comment]
@avikchaudhuri I think this is a regression from 742d9b3f8c4a6d08d7a337bc400735879a0e108e

Thanks for reporting!

**Comment by vkurchatkin** [comment]
Not an issue in 0.38
