### ISSUE TITLE
Relevance of definition order within object literals containing spreads is the opposite of what it should be

### ISSUE THREAD

**Issue by dchambers** [facebook/flow#2278]
Although there are lots of bugs related to spreads I couldn't find one for the use case below. Also, there's a small chance this is a quick win since Flow seems to do exactly the opposite to what it should do in this case, so maybe ... just maybe, the logical condition that controls this behaviour just needs inverting :smile:.

The following code (tested in Flow `0.30.0`) causes Flow to error even though it's correct (the type of `x` is `X` after evaluating the assignment):

``` es6
type X = {
  type: 'X',
  p: number
};

type Y = {
  type: 'Y', // Flow errors here
  p: number
};

const f = (x: X) => x;

const y: Y = {
  type: 'Y',
  p: 1
};

const x: X = f({
  ...y,
  type: 'X'
});

console.log(x); // eslint-disable-line no-console
```

but changing the defintion of `x` so that `y` is spread-in after `type` has been defined, as follows:

``` es6
const x: X = f({
  type: 'X',
  ...y
});
```

causes the error to disappear, even though the program is now incorrect; the type of `x` will now be `Y`.

**Comment by asolove** [comment]
This seems like something worth fixing. I didn't realize Flow was doing this in reverse order, but that possibly explains several of the other object spread bugs. (/cc @calebmer)

**Comment by SamChou19815** [comment]
The issue was fixed a while ago
