### ISSUE TITLE
Can't export type

### ISSUE THREAD

**Issue by olleharstedt** [facebook/flow#2279]
It's possible to export a class using CommonJS notation, but not possible to export a type:

    class C {}
    type t : {x : number, y : number};

    exports.C = C;
    exports.t = t;  // <--- Error here

> type referenced from value position

Not sure if by design.

**Comment by olleharstedt** [comment]
Note: I didn't successfully setup browserify with ES6 style modules. That's why I'm using CommonJS style modules.

**Comment by vkurchatkin** [comment]
Well, classes exist at runtime, types don't. You need to use `export type` for this

**Comment by samwgoldman** [comment]
Yeah, @vkurchatkin is exactly right. If you want to export a type declared in module A for use in module B, you can do something like this:

a.js

```js
export type T = string
```

b.js

```js
import type { T } from "./a"
var x: T = 0; // error, number incompatible with string
```

Read more in the docs: https://flowtype.org/docs/modules.html#type-imports--exports

Reply here if this doesn't resolve your issue.
