### ISSUE TITLE
Does not work with Webpack's require() for CSS

### ISSUE THREAD

**Issue by gaearon** [facebook/flow#228]
We use Webpack's [loaders](http://webpack.github.io/docs/loaders.html) for requiring CSS. This means we have calls like this:

```js
var React = require('react'),
    Icon = require('../atoms/Icon'),
    ActivityTypes = require('../constants/ActivityTypes'),
    createStoreMixin = require('../mixins/createStoreMixin'),
    { transitionTo } = require('../router'),
    { PropTypes } = React;

// Oops!
require('./Activity.less');
```

I understand this is kinda abusing `require` syntax and it won't work in Node, but it's really handy for client-only code. Can I instead somehow tell Flow to ignore `require` when the extension is `.less`?

**Comment by gaearon** [comment]
I guess this could also be solved by supporting something like

```js
/* @flow ignore:start */
require('./Activity.less');
/* @flow ignore:end */
```

in the spirit of JSHint.

**Comment by tcoopman** [comment]
Possible duplicate of #51

**Comment by gaearon** [comment]
Right, it's a dupe.
