### ISSUE TITLE
Idea: type that can't be ignored

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2281]
One common source of error is forgetting to use promise:

``` js
async function main() {
  foo(); // should be await foo();
}
```

This can be solved with generic `$MustUse` type:

``` js
async function foo(): $MustUse<Promise<void>> {
// ...
}
```

**Comment by AriaFallah** [comment]
@vkurchatkin 

Is there anything like this currently?

**Comment by vkurchatkin** [comment]
Not to my knowledge

**Comment by SamChou19815** [comment]
This is now implemented with unused promise lint.
