### ISSUE TITLE
`instanceof` erases type information

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2282]
Test case:

``` js
  var x = 'string';

  if (x instanceof Array) {
    x.bla(); // no error
  }
```

**Comment by avikchaudhuri** [comment]
I suspect we're effectively considering `x` unreachable at that point. Ideally we'd be reporting unreachable code errors for that entire if-block. Do you agree?

**Comment by vkurchatkin** [comment]
I guess it makes sense in this particular case. The problem is that behaviour is the the same if `x` is `mixed`.

**Comment by vkurchatkin** [comment]
It seems that Flow doesn't consider class type to be subtype of `mixed`, for example this doesn't work:

```js
class Foo {}
class Bar {}

function test(v: mixed) {
  if (v instanceof Foo) {
    v.boom();
  }
}
```

but this does:

```js
class Foo {}
class Bar {}

function test(v: mixed | Foo) {
  if (v instanceof Foo) {
    v.boom();
  }
}
```

**Comment by bluepnume** [comment]
Just to paste the example from my closed issue -- following code doesn't trigger a type error when it should:

    function getBar(foo : mixed) {
      if (foo instanceof HTMLElement) {
        return foo.bar;
      }
    }

**Comment by vith** [comment]
Would this be the same issue?

```flow
// @flow

class A {
  aaa() {}
}

class B {
  bbb() {}
}


declare function surprise(): A | B

const s = surprise()

switch (true) {
  case s instanceof A:
    s.aaa()
    break
  case s instanceof B:
    s.bbb()
    break
  default:
    throw "too much surprise"
}
```

```
18:     s.aaa()
          ^ property `aaa`. Property not found in
18:     s.aaa()
        ^ B
21:     s.bbb()
          ^ property `bbb`. Property not found in
21:     s.bbb()
        ^ A
```

**Comment by migueloller** [comment]
Ran into this issue as well. Here's a simple [repro](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwGIHtPwN4F8AoeeQ0JOeAN1ngDNsAueAWwEsAPEYQwtu+AAoGONgDtkAFyhiwITAKyYAlHmJCRzECwAOkgJ6qA9EfgAVABZs0yC5gCuEYPABGCGfBAwYmGADpCIiA).

**Comment by Scimonster** [comment]
I'm having a similar issue, but in my case I'm doing `if (!(obj instanceof Something)) {throw new Error}`. The weird thing is, i'm checking 2 properties, and it successfully refines one but not the other, even if i separate the checks.

```typescript
class MyData {
  check() {
    return Math.random() > 0.5
  }
}

type Data = {
  a: ?MyData,
  b: ?MyData
}

function checkBoth(data: Data) {
  if (!(data.a instanceof MyData) || !(data.b instanceof MyData)) {
    throw new Error()
  }
  return data.a.check() && data.b.check();
  // Cannot call `data.b.check` because property `check` is missing in null or undefined [1].
}
```

([try](https://flow.org/try/#0C4TwDgpgBAysBOARAhsZUC8UDeAoKUY8A9mAIwBcUA-AM4ICWAdgOYA0+hJYATFXY1a4AvrlwAzAK5MAxsAbEmUZABMVAGQitgAC1oAKFamRU4SYwEocnBuKj6AhPtCRido2gB0RUmUxYAcnp4ZhYAqwAfCKgnFwg3KA9kb24efyggwTCLKzwCAl0SAHcoJggSgFF4Enh9C05RAngIYEl4JSSU308AGy0WXSgAakTjLt5e-t0AbhExXBlFWmI+3uIWfVUNKb19bB9yKgDkACMZALYuUj4MlQhxAOEcsRke5FpaKABZEBQ0awIMh0EBkAGs6gD8s1Wu1vqgdJ54MgmCpiABbCEAPigAAZPABWBpzXBxKB-dBYPLKfg-ckcAgnGm-YzEqSyeSKKBAkGggBCxF0hmMVHJuRsdkcQq86GY9GRMnidlpligURiUuSJygsrQskV32ZaBykIKOmKpXKUCqNTqRKaLTaHTGyW5YIhADJ3aMvCdPK7wRZZqIFksVhA1ht-fzBdgTBaSsq0JdGfGDeSnhYgA))
