### ISSUE TITLE
Multiple optional function arguments

### ISSUE THREAD

**Issue by anilanar** [facebook/flow#2289]
```
declare fn(str?: string, num?: number): void
````

**Test**
```
fn(5);
```

**Actual Result**
```
fn(5);
   ^ number. This type is incompatible with
fn(str?: string, num?: number): void;
         ^^^^^^ string.
```

**Expected Result**
I assume it should not error for the following uses:
```
fn();
fn('str');
fn(5);
fn('str', 5);
```

**Comment by vkurchatkin** [comment]
I think it works as expected. You need to add an overload for this to work

**Comment by anilanar** [comment]
Shouldn't this be documented somewhere though?

**Comment by samwgoldman** [comment]
@vkurchatkin is right on both counts, this is working as designed and you might be looking for function overloads. You might also be looking for union types, i.e., `function f(arg: number | string) { ... }`.

Contributions to the docs are very welcome!
