### ISSUE TITLE
Add support for deprecations

### ISSUE THREAD

**Issue by fgarcia** [facebook/flow#2290]
Just a minor feature request, but I believe it would be amazing adding some kind of annotation to deprecate code. This can make code refactorings (specially libs) much easier

For example, imagine we implemented `Stack.add()` but later realized it is far more idiomatic to just use `Stack.push()`

```
declare interface Stack<T> {
  add(item: T): void: Deprecate
  push(item: T): void;
  pop(): T;
  isEmpty(): bool;
}
```

Right now I use a custom `log.deprecate` but statically typed would be so much nicer.

Not sure how one should chain annotations. An alternative might be this:

```
  add(item: T): [void, Deprecate]
```

**Comment by dralletje** [comment]
Something like `$Deprecate<void>` could work without introducing new syntax

**Comment by samwgoldman** [comment]
This is an interesting idea! I think the `$Deprecate<T>` syntax could work, but we'd also need to introduce some concept of warnings which are separate from errors. I imagine people wouldn't want deprecation warnings to break their builds.

**Comment by SamChou19815** [comment]
We do surface `@deprecated` in jsdoc now, but we won't add a new type for this
