### ISSUE TITLE
Getting a value from an object being used as a Map

### ISSUE THREAD

**Issue by dasilvacontin** [facebook/flow#2292]
```js
function logPlayerScore (scores: { [key: string]: number }, player: string) {
  const score = scores[player]
  console.log(score.toFixed())
}

logPlayerScore({}}, 'dasilvacontin')
```

Flow doesn't complain. I would expect `score` to be type `number | void`. Does `{ [key: string]: number }` assume that there's a value for all keys?

Current workaround is to define type as `{ [key: string]: number | void }`.

**Comment by vkurchatkin** [comment]
> Does { [key: string]: number } assume that there's a value for all keys?

It does. The logic is the same as for arrays: `arr[n]` is of type `T`, not `?T`, otherwise iterating over arrays and objects would be very inefficient.

**Comment by dasilvacontin** [comment]
I see – thanks for the explanation, @vkurchatkin!
