### ISSUE TITLE
Add support to declare imported types

### ISSUE THREAD

**Issue by HenriJ** [facebook/flow#2294]
To share types between projects, we want to export them in their own npm modules and npm install them where needed.

Sometimes, we would like to be able to declare an imported type globally in the application.

Simply speaking, it would be great to be able to do something like that, in interfaces/globals.js:
```
import type { MyType } from 'my-type';
declare type MyType;
```

Sadly, because imports don't seem to work in lib files, it won't work right now...

**Comment by thejameskyle** [comment]
Moving this into https://github.com/flowtype/flow-typed/issues/16
