### ISSUE TITLE
'any' type infects key accesses

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2295]
[Example on FlowType Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMAuMAbwG0BrAUwE8yCAnAS2wHMBdM7AVwC2AI1rMAvmAC8FVGDBQ4cMgEYANKjEBudFjyEiAZXzMmx9hynFKAcgVxrXbboLEA0gzJFs9S7cXWnHBchIxMwFnNLIkoid3pHIA)

```jsx
const a: {[key: string]: number} = {
  foo: 1,
};

const aStr: string = a['foo']; // errors correctly
const aKey: any = 'foo';
const bStr: string = a[aKey]; // should error, does not
```

Given an object of type `{[key: string]: number}`, indexing it with an `any` type shouldn't create a value of `any`. On the `a` object, for any given key, it should be treated as a `?number`.

I assume this is a consequence of prototype chains (`a['hasOwnProperty']: Function`). Will the upcoming `$Exact` type fix this?

**Comment by vkurchatkin** [comment]
But why `?number` and not `number`?

**Comment by STRML** [comment]
For any given key, Flow should be able to say that it *could* be a `number`, but it doesn't know for sure if the key is actually in the object. So it could be `undefined`.

**Comment by gcanti** [comment]
I guess it should be `void | number`, getting a value is unsafe

```js
const a: {[key: string]: number} = {}
const b: number = a.unknown * 2 // <= no error
console.log(b) // => NaN
```

**Comment by STRML** [comment]
That's interesting, the behavior is pretty odd - it actually assumes that *all* keys are numbers, except if the key is from an `Object` type, then `any` flows.

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMAuMAbwG0BrAUwE8yCAnAS2wHMBdM7AVwC2AI1rMAvmAC8FMZhwEwQpvjacpxSgGUV7DgAoAskXwALAHTMi2ACZwBegJQOuAbjl5CcIQCsyAeR9aDEJpcjE3LA8wDGVVDnUiSi9vMyg4OFcgA

```jsx
const a: {[key: string]: number} = {}
const b: string = a[String(Math.random())]; // errors
const obj: Object = {};
const c: string = a[obj.foo]; // should error, does not
```

**Comment by vkurchatkin** [comment]
I think that's by design, and won't change. Think of map `{[key: string]: number} ` as a function `(key: string) => number`.

**Comment by gcanti** [comment]
So, just to clarify the current behaviour:

arrays and dictionaries behave consistently if the key is not of type `any`

```js
const arr: Array<number> = []
const elem: number = arr[0] // no error (unsafe?)
const elem: string = arr[0] // error

const dict: {[key: string]: number} = {}
const val: number = dict['foo'] // no error (unsafe?)
const val: string = dict['foo'] // error
```

while they behave differently if the key is of type `any`

```js
const arr: Array<number> = []
const i: any = 0
const elem: string = arr[i] // <= error: number. This type is incompatible with string

const dict: {[key: string]: number} = {}
const k: any = 'foo'
const val: string = dict[k] // no error <= this seems a bug
```

**Comment by vkurchatkin** [comment]
@gcanti well, that part is certainly a bug

**Comment by STRML** [comment]
Thanks for isolating it @gcanti

**Comment by samwgoldman** [comment]
This isn't actually specific to `any`. We currently allow any statically unknown strings or numbers to index any object. This is unsound and I'd like to tighten things up here, but we have this rule because many common JS idioms run into this.

Example:

```js
declare var obj: { p: number };
declare var strkey: string;
declare var numkey: number;
(obj[strkey] : number & string);
(obj[numkey] : number & string);
```

Note that `number & string` is a cheap way of constructing an "empty" type, as no type other than `any` (or itself) can inhabit that type.

So, long story short, this is working as designed. You may be interested to [read the source in the type checker](https://github.com/facebook/flow/blob/1694f400c2e3e8cef1023e92b657c2de0d90a6ee/src/typing/flow_js.ml#L3654) that allows this.

**Comment by vkurchatkin** [comment]
@samwgoldman I think it only supposed to work like this for record objects, not for map objects

**Comment by samwgoldman** [comment]
OK, I see. I missed the dictionary part. Right above the code I linked to shows the logic for the dictionary case, but we never reach it because we don't propagate the any there. This should be a simple fix, but to be clear, this is the expected behavior?

```js
const dict: {[key: string]: number} = {}
const k: any = 'foo'
const val: string = dict[k] // error: number incompatible with string
```

**Comment by STRML** [comment]
Right, that's the behavior I would expect.
