### ISSUE TITLE
Can't use React as a global variable

### ISSUE THREAD

**Issue by fgarcia** [facebook/flow#2300]
After defining React as a global variable, I added these lines to my global declarations

```
import type { React as ReactType } from 'react';
declare var React : ReactType;
```

After this, Flow no longer complains about not being able to resolve the `React` identifier, however all PropType checking is disabled.

How can I tell Flow that React is a globally defined import?

**Comment by aackerman** [comment]
You can use the following to declare a global for React.

```js
declare var React: $Exports<'react'>;
```

**Comment by neutraali** [comment]
God it took me hours/days to find this issue! Huge thumbs up to @aackerman :+1:
