### ISSUE TITLE
Unable to bound generic function return type with primitive type

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2304]
This is more of a type alias than it is a bounded polymorphic type, but it seems like a bug?

Error:
`const testFunc = <T: number>(num: T): T => num * 2;`

> This type is incompatible with the expected return type of some incompatible instantiation of `T`

No Error:
`const testFunc = <T: number>(num: T): => num * 2;`

**Comment by mwalkerwells** [comment]
This does work though, but seems strange to do.
`const testFunc = <T: number>(num: T): number => num * 2;`

**Comment by mwalkerwells** [comment]
When bounding types to a primitive type, shouldn't the type signature be (in the case of number):
`(num: number) => number`
...not
`<T>(num: T) => T`

I'm guessing this is the cause?

**Comment by mwalkerwells** [comment]
If I missed something, please let me know! Didn't see anything in:

- [Flow Blog: Bounded Polymorphism](https://flowtype.org/blog/2015/03/12/Bounded-Polymorphism.html)
- [Docs: Classes #Bounded-Polymorphism](https://flowtype.org/docs/classes.html#bounded-polymorphism)

**Comment by gcanti** [comment]
Relevant https://github.com/facebook/flow/issues/2194#issuecomment-237899795

The "or a modified version" part of this sentence

> Not the type of value but the value or a modified version of the value itself

in not clear though. It works with `n + 1` but not in your case: `n * 2`

**Comment by mwalkerwells** [comment]
Ah, thanks for the link! Moving the conversation there...
