### ISSUE TITLE
Spread operator doesn't work with generators

### ISSUE THREAD

**Issue by jchitel** [facebook/flow#2305]
The spread operator is supposed to work with any object that has a `[Symbol.iterator]` function, [which includes generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols#Is_a_generator_object_an_iterator_or_an_iterable). When I run the following code, it works:

```javascript
// @flow

function* generator() {
    yield 1;
    yield 2;
    yield 3;
}

console.log([...generator()]); // [1, 2, 3]
```

When I run it through flow, however, I get the following error:

```
flow-generator-spread.js:9
  9: console.log([...generator()]);
                     ^^^^^^^^^^^ Generator. This type is incompatible with
  9: console.log([...generator()]);
                     ^^^^^^^^^^^ spread operand


Found 1 error
```

**Comment by samwgoldman** [comment]
Thanks for the report! This is a known issue, so I'm going to merge this with the original task over in #1059.
