### ISSUE TITLE
0.31 broke raw property type access

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2308]
Given a type:

```jsx
export type Foo = {
  a: string,
  b: number
}
```

In other modules, I was setting prop types like the following:

```jsx
import {Foo} from 'ui/types';

// ...
props: {
  a: Foo.a,
  b: Foo.b
}
```

In 0.30, this works. I now receive the following error in 0.31:

```
 25:     a: Foo.a
            ^^^^^ a. Property cannot be accessed on
 67: export type Foo = {
     ^ type `Foo`. See: ui/types.js:67
```

Was this intentionally broken in favor of `$PropertyType`?

**Comment by STRML** [comment]
This is an easy find/replace so no big deal, just wanted to clarify intent.

**Comment by samwgoldman** [comment]
Yeah, this is expected in 0.31. To be completely honest, we're still deliberating how the `.` should work in types, so this behavior may change again in the future. For now and for the foreseeable future, `$PropertyType<T, 'key'>` is the recommended way to do this. It's also possible to factor the property type out into a separate named alias, as always.

**Comment by STRML** [comment]
Okay, great. Deep property accesses are tough with this syntax. I'd like to do something like this:

```jsx 
declare type $Val<T, U> = $PropertyType<T, U>;
declare type $Val<T, U, V> = $PropertyType<$PropertyType<T, U>, V>;
declare type $Val<T, U, V, W> = $PropertyType<$PropertyType<$PropertyType<T, U>, V>, W>;
```

but I receive the following error:

```
type $Val<T, U> = $PropertyType<T, U>;
                     ^ expected object type and string literal as arguments to $PropertyType
```

It appears there's some magic preventing this from being used generically?

**Comment by vkurchatkin** [comment]
@STRML yeah, `$PropertyType` is very limited right now, you can't even use type alias instead of literal

**Comment by samwgoldman** [comment]
@vkurchatkin That looks like an issue! Filed #2310

We need to know that the second type parameter is a statically knowable string value, so it's unclear that a fully generic `$PropertyType<O,K>` should be valid.

**Comment by samwgoldman** [comment]
I'm going to close this because things are generally working as defined, except for the issue identified in #2310. Thanks for opening this with such clear examples. Please let us know if you run into any more problems.
