### ISSUE TITLE
Flow errors on unicode keys

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2309]
This is valid JS.

> Error: Unexpected token ILLEGAL

Code:

```jsx
const CONVERSIONS = {
  m: 1,
  cm: 100,
  mm: 1000,
  μm: 1000000
}
```

[FlowType Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAGEB5AOQDUBRAJQGUBJcusAXjAG9UwwBbALjABGADTcwGAcIAM0sT15ShsueMA9wEpUrUAXyA)

**Comment by samwgoldman** [comment]
Yeah, this is a bummer :(

Gabe gave a great explanation in the original issue, #521. I'm going to merge this with that issue.

Thanks for filing an issue!

**Comment by STRML** [comment]
Thanks, sorry for the duplicate!
