### ISSUE TITLE
Allow string literal type alias in $PropertyType

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#2310]
``` js
/* @flow */
type Key = 'key';
type T = { key: number };
declare var prop: $PropertyType<T,Key>;
```

Actual output:

```
4: declare var prop: $PropertyType<T,Key>;
                     ^ expected object type and string literal as arguments to $PropertyType
```

Expected: `No error`

**Comment by nmn** [comment]
I'm sure that this is a really hard problem, but I wonder if `$PropertyType` could be extended to work in this case: (From Immutable.js)

```typescript
declare class Record<T: Object> {
  static <T: Object>(spec: T, name?: string): Class<T & Record<T>>;
  get<K: $Keys<T>>(key: K): $PropertyType<T, K>;
  set<A>(key: $Keys<T>, value: A): T & Record<T>;
  remove(key: $Keys<T>): T & Record<T>;
}
```

Currently, Flow complains that `$PropertyType` only a string literal as the second parameter. This one feature (if possible) would make it possible to write the type for every thing that it's currently impossible to write types for.

**Comment by nmn** [comment]
I've tried to make this work in User Space, but it hasn't worked. The closest I've got is to get the union of all value types in an Object. So `$Keys` but for values:

```typescript
type $Object<V> = {[key: string]: V}
type _$Values<V, O: $Object<V>> = V
type $Values<O: Object> = _$Values<*, O>
```

Using this in the Immutable.js Record type:
```typescript
declare class Record<T: Object> {
  static <T: Object>(spec: T, name?: string): Class<T & Record<T>>;
  construtor(spec: T): this;
  get(key: $Keys<T>): $Values<T>;
  set<A>(key: $Keys<T>, value: A): T & Record<T>;
  remove(key: $Keys<T>): T & Record<T>;
}
```

This gives us slightly better results.
```typescript
import {Record} from 'immutable'

type P = {
  name: string,
  age: string
}

const Person = Record({name: 'John Doe', age: '25'})

var bob: Record<P> = new Person({name: 'Bob', age: '31'})

;(bob.get('name'): string) // no error here
;(bob.get('name'): number) // Flow Error: it's a string not a number
```

**Comment by aaronjensen** [comment]
@samwgoldman would allowing a string literal type also allow what @nmn is asking for? Being able to do `$PropertyType<T, K>` in the general case would be really powerful.

**Comment by yarax** [comment]
So are there any plans to introduce $Values utility type? 
Which takes object type as parameter and gives a union of values.

**Comment by byronmwong** [comment]
as a point of reference, Typescript 2.1 introduced the ability to type `set` functions via `K keyof T` and `T[K]`. From their [release notes](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html):

```
function setProperty<T, K extends keyof T>(obj: T, key: K, value: T[K]) {
    obj[key] = value;
}
```

**Comment by calebmer** [comment]
You can use `$ElementType` for this! If you are having any issues please let us know 😊

```js
type Key = 'key';
type T = { key: number };
declare var prop: $ElementType<T,Key>;
```

https://flow.org/try/#0C4TwDgpgBA0hJQLxQOQGt4oNwChSSgBUkoBvKDEALigDsBXAWwCMIAnKAX1wBMIBjADYBDNtABuoqGDYB7MDQAkAUUERGEWsELgIAHkIAaOCAB8uIA

**Comment by philippotto** [comment]
This looks very promising, @calebmer. However, the following code doesn't typecheck for me:

```js
export type SomeType = {
  aString: string,
  aNumber: number,
};

function f2<S: $Keys<SomeType>>(
  propertyName: S,
  value: $ElementType<SomeType, S>,
) {
  
};

function f1<S: $Keys<SomeType>>(
  propertyName: S,
  value: $ElementType<SomeType, S>,
) {
  f2(propertyName, value);
};

f1("aNumber",  2);
```
[try](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKEC2wAqzUC8cA3gFBxwCGaMUAlgHYDmAXHAM62NMA05VAOQCumAEbAobBiPFQ+AXwDcpUgDMhDAMYw6EBnFUAmADxo2AEgDSwRO1NZc+AHxOAFPzBQIKWIgGVsNjQ+CgA3SgAbIWALAFEI4GwGGDwUe2xU4B50Jz4AShJ+UiUVdS0dPQMARlMLa1t0xxQXdwpPbwkkf0D0ELhwqJi4c3jE4GTMxszstFzSArIKI1d2ny6ArP7I6LzlErUq1wAiSmExCSPsuENdoA)

If `f1` doesn't call `f2` it typechecks. Am I missing something here?

**Comment by emdash** [comment]
$ElementType Doesn't type-check correctly when used as a return-value:

Type checking fails in Foo.getValue(), arguing that the return type of ValueOf is incompatible with each of "number", "string", and "object type" in turn.

```
type T = {| 
  key: number,
  foo: string,
  bar: {}
|};
	
type ValueOf<K: $Keys<T>> = $ElementType<T, K>;

class Foo {
  obj: T;
 
  getValue<K: $Keys<T>>(key: K): ValueOf<K> {
  	return this.obj[key];
  }
}
```

```
  15:   	return this.obj[key];
                  ^ number. This type is incompatible with the expected return type of
    14:   getValue<K: $Keys<T>>(key: K): ValueOf<K> {
                                         ^ object type
    15:   	return this.obj[key];
                  ^ number. This type is incompatible with the expected return type of
    14:   getValue<K: $Keys<T>>(key: K): ValueOf<K> {
                                         ^ string
    15:   	return this.obj[key];
                  ^ object type. This type is incompatible with the expected return type of
    14:   getValue<K: $Keys<T>>(key: K): ValueOf<K> {
                                         ^ number
    15:   	return this.obj[key];
                  ^ object type. This type is incompatible with the expected return type of
    14:   getValue<K: $Keys<T>>(key: K): ValueOf<K> {
                                         ^ string
    15:   	return this.obj[key];
                  ^ string. This type is incompatible with the expected return type of
    14:   getValue<K: $Keys<T>>(key: K): ValueOf<K> {
                                         ^ number
    15:   	return this.obj[key];
                  ^ string. This type is incompatible with the expected return type of
    14:   getValue<K: $Keys<T>>(key: K): ValueOf<K> {
                                         ^ object type
```

**Comment by villesau** [comment]
@calebmer can you elaborate what are the differences between $PropertyType and $ElementType? My little test says there are no differences: https://flow.org/try/#0C4TwDgpgBA8gRgKygXigbwFBSmATgezAC50A7AVwFsSLK4JcBfDZjACjVpIEYAmAZkYkAJAFEANhEoRSwACrgIAHngIANFADkeQpoB8ASgDc7TlR4ChUYQAUCkXKAWQViDdvv7jQA
