### ISSUE TITLE
How to extend existing type definitions

### ISSUE THREAD

**Issue by arekkas** [facebook/flow#2313]
I have two types:

```js
type A = {
  foo: string,
  bar: Array<string>
}

type B = {
  baz: string,
  a: A
}
```

However, I want `B.a.bar` to be `Array<number>` instead of  `Array<string>`. I don't want to copy all of `A` to `B.a` because in real code, it's a lot of definitions. I various things, but all of them failed. Intersections failed when trying to destruct `B.a` somewhere in the code.

```
type B = {
  baz: string,
  a: {...A, bar: Array<number>}
  a: A & {bar: Array<number>}
  a: A | {bar: Array<number>}
}
```

How can I achieve this in flow?

**Comment by gcanti** [comment]
```js
type _A<T> = {
  foo: string,
  bar: Array<T>
};

type A = _A<string>;

type B = {
  baz: string,
  a: _A<number>
};
```

**Comment by arekkas** [comment]
This is very good advice, thank you.
