### ISSUE TITLE
Object initialization does not respect object type seals

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#2314]
I would not expect this to type check, but it does:

```js
/* @flow */

type Foo = {
  bar: string
}

const foo: Foo = { bar: "hi", baz: "whatever" }
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgBGAhgE4BcYAzhkwJYB2A5qgC+6AMZxenMFBJtipCpXrM2AIgAW3VQBplALzUJ1DDHgBueJqrAjUQA

Is this "by design"?

It causes flow to miss typos in redux reducers like:

```js
const reducer = (state, action) => ({ ...state, typo: action.foo })
```

**Comment by vkurchatkin** [comment]
This is by design. Try using new `$Exact` type:

```js
type Foo = $Exact<{
  bar: string
}>

const foo: Foo = { bar: "hi", baz: "whatever" } // error
```

**Comment by aaronjensen** [comment]
Hmm, that works in the try page but not in my project...

```
client/app/reducers/session.js:14
 14: export type SessionState = $Exact<{
                                ^ identifier `$Exact`. Could not resolve name
```

**Comment by andreypopp** [comment]
@aaronjensen probably you are using an older version of flow?

**Comment by aaronjensen** [comment]
@andreypopp older than what? 0.31.0 isn't released yet on npm, is that where it was added?

```
$ `npm bin`/flow version
Flow, a static type checker for JavaScript, version 0.30.0
```

**Comment by samwgoldman** [comment]
Yeah, `$Exact` was included in 0.31, but it hasn't made it to npm yet (cc @jeffmo).

**Comment by aaronjensen** [comment]
Awesome. I didn't see it in the changelog or docs. I'll close this out then since it sounds like there's a proper way of doing this. Thanks all.

**Comment by aaronjensen** [comment]
I should also mention that it's a little confusing. I'm sure there's a good reason for it, but if the object types are sealed by default it's strange that they're not sealed during initialization. It's just another level of potential confusion (hence this issue). Is there a thread where this was discussed so I can understand the reasoning? Thanks!

**Comment by samwgoldman** [comment]
You're right, except the subtyping relation there goes the other way :)

**Comment by vkurchatkin** [comment]
> You're right, except the subtyping relation there goes the other way :)

My bad! Fixed it
