### ISSUE TITLE
Heretogeneous type parameters in list

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#2316]
I'm trying to do something that I'm not sure that Flow supports. So this is either a feature request or an issue about the documentation.

Is there a way to change the Foo or FooList types so that Flow detects an error here?

```js
/* @flow */

type Foo<T> = {a: T, b: T};
type FooList = Array<Foo<any>>;

function foo(list: FooList) {
}

foo([
  {a: 5, b: 6},
  {a: '.', b: ','},
  {a: ':', b: 7} // <- This line should make it fail
]);
```

I realized that the issue is that T is being set to any here. I tried using `type FooList = Array<Foo<*>>;` instead but that also failed to fail because I assume * is getting set to any. I can't think of a way to allow each Foo object in the list to get its own T value.

**Comment by aackerman** [comment]
I thin for this specific case you could what you have to `type FooList = Array<Foo<string> | Foo<number>>;`

**Comment by rpominov** [comment]
This issue seems similar to https://github.com/facebook/flow/issues/2254

You can use `*` or propagate type argument to `FooList` and `foo`:

```js
type FooList<T> = Array<Foo<T>>;

function foo<T>(list: FooList<T>) {
}
```

But it won't help because Flow just detect `T` to be `number | string`.

**Comment by AgentME** [comment]
@aackerman That'd work, though In my real code, it's actually a large list of classes the parameters could be so it's a less appealing solution.

@rpominov Right, there's only one value of T for the whole list instead of a T per item. But now that you point out union types and that linked issue, I think even if what I wanted was possible, it could still detect the T type for the last item as `number|string` anyway. Flow being flexible like that with inferring union types is something I generally like and I assume many people depend on, so I'm just going to take it as that what I wanted isn't really possible in this exact way.
