### ISSUE TITLE
Disjoint unions broken

### ISSUE THREAD

**Issue by philip-peterson** [facebook/flow#2317]
Hi there! In my application, I have two types (let's call them A and B) which have some overlapping property names. However the properties are of different (incompatible) types. This should not be a problem as I am not intersecting them or anything. 

However I am using a disjoint union to accept an array of objects that are either of type `A` or `B`, the type of which can be refined based on a tag (`type` property). This is not the actual cause of the problem, but wanted to provide some context.

The actual problem comes when I want to cast from a specific type (e.g. B) to a supertype (`A | B`).

```
type Athing = {id: number};
type Bthing = {id: ?number};

type TaggedAlpha = {type: 'a', value: Athing};
type TaggedBeta = {type: 'b', value: Bthing};
type TaggedThing = TaggedAlpha | TaggedBeta;

const filterThings = (things: Array<TaggedThing>): Array<TaggedThing> => {
    return things;
};

const getFilteredThings = (betas: Array<TaggedBeta>): Array<TaggedBeta> => {
    return filterThings(betas);
};
```

When I run this through flow, I get the following errors:

```
(snipped, file/line number info)
 78:     return filterThings(betas);
                ^^^^^^^^^^^^^^^^^^^ function call
 67: type Bthing = {id: ?number};
                         ^^^^^^ null. This type is incompatible with
 66: type Athing = {id: number};
                        ^^^^^^ number

(snipped, file/line number info)
 78:     return filterThings(betas);
                ^^^^^^^^^^^^^^^^^^^ function call
 67: type Bthing = {id: ?number};
                         ^^^^^^ undefined. This type is incompatible with
 66: type Athing = {id: number};
                        ^^^^^^ number

(snipped, file/line number info)
 78:     return filterThings(betas);
                ^^^^^^^^^^^^^^^^^^^ function call
 69: type TaggedAlpha = {type: 'a', value: Athing};
                               ^^^ string literal `a`. Expected string literal `b`, got `a` instead
 70: type TaggedBeta = {type: 'b', value: Bthing};
                              ^^^ string literal `b`

(snipped, file/line number info)
 78:     return filterThings(betas);
                ^^^^^^^^^^^^^^^^^^^ function call
 70: type TaggedBeta = {type: 'b', value: Bthing};
                              ^^^ string literal `b`. Expected string literal `a`, got `b` instead
 69: type TaggedAlpha = {type: 'a', value: Athing};
                               ^^^ string literal `a`
```

These error messages seem very confusing. Is there some limitation to tagged/disjoint unions at work here?

**Comment by jesseschalken** [comment]
I think there's two problems:

1. Arrays are invariant, so `Array<TaggedBeta>` is not compatible with `Array<TaggedThing>`. This is because `filterThings()` could potentially add an arbitrary `TaggedThing` to the array (eg via `.push()`) which `getFilteredThings()` thinks contains only `TaggedBeta`s.
2. Even if arrays were covariant, `getFilteredThings()` says it returns `Array<TaggedBeta>` while `return filterThings(betas);` is returning an `Array<TaggedThing>` (`TaggedThing` is not compatible with `TaggedBeta`).

**Comment by jesseschalken** [comment]
This works:

```js
type Athing = {id: number};
type Bthing = {id: ?number};

type TaggedAlpha = {type: 'a', value: Athing};
type TaggedBeta = {type: 'b', value: Bthing};
type TaggedThing = TaggedAlpha | TaggedBeta;

const filterThings = <T : TaggedThing>(things: Array<T>): Array<T> => {
    return things;
};

const getFilteredThings = (betas: Array<TaggedBeta>): Array<TaggedBeta> => {
    return filterThings(betas);
};
```

**Comment by philip-peterson** [comment]
Thanks so much for your quick reply! That generic syntax is very handy, and I understand the problem now. Perhaps this will someday be mitigatable by being able to annotate params as read-only (immutable)? Anyways, thanks for the help. :)

**Comment by jesseschalken** [comment]
No worries. In terms of defining things as immutable, in general you would define a covariant interface/type (eg `ConstArray<+T>`) which your mutable class implements, and use that as your type annotation instead.

I'm not sure if such a thing already exists for `Array` in Flow, though. Even the `Iterable` type appears to be invariant, which I find surprising ([link](https://github.com/facebook/flow/blob/b792969a33706639084ce1015b0f4b5257cd7ced/lib/core.js#L432)):

```js
interface $Iterable<Yield,Return,Next> {
    @@iterator(): $Iterator<Yield,Return,Next>;
}
type Iterable<T> = $Iterable<T,void,void>;
```

Even though `Generator` is covariant in `Yield` and is compatible with `Iterable`:

```js
/* Generators */
interface Generator<+Yield,+Return,-Next> {
    @@iterator(): $Iterator<Yield,Return,Next>;
    next(value?: Next): IteratorResult<Yield,Return>;
    return<R>(value: R): { done: true, value: R };
    throw(error?: any): IteratorResult<Yield,Return>;
}
```

It'd be great if someone more familiar with Flow could comment on what's going on there.

That would only solve your first problem, though. You still need the type parameter so `filterThings` can return something compatible with `Array<TaggedBeta>` even though it only knows about `TaggedThing`s.

**Comment by samwgoldman** [comment]
@jesseschalken You're right on! Thanks for writing up such a clear response :)

I think you're right that `Iterator` should have the same variance as `Generator`—not sure why it isn't so already. Using `Iterator` would be a great way to solve many of the issues people run into with array invariance. I'll check it out now.

**Comment by jesseschalken** [comment]
@samwgoldman Thanks for fixing that. How about `ConstArray`, `ConstMap` and `ConstSet` interfaces? They would be handy for code that needs covariance but still need things like `f.orEach()`, `.filter()`, `.length` etc. Should I create a separate issue?

**Comment by samwgoldman** [comment]
Yeah, if you don't mind :) I think @avikchaudhuri is interested in Const* types, so please ping him as well.

**Comment by jesseschalken** [comment]
Submitted as #2333
