### ISSUE TITLE
Case analysis of disjoint unions is possibly broken

### ISSUE THREAD

**Issue by SamWyld** [facebook/flow#2318]
See the [example](https://tryflow.org/?code=ZXhwb3J0IHR5cGUgUHJvamVjdEFjdGlvbiA9IAp8IHsgdHlwZTogJ0FERF9QUk9KRUNUJywgdGV4dDogc3RyaW5nIH0KfCB7IHR5cGU6ICdERUxFVEVfUFJPSkVDVCcsIGlkOiBzdHJpbmcgfQp8IHsgdHlwZTogJ1NFVF9DVVJSRU5UX1BST0pFQ1QnLCBpZDogc3RyaW5nIH0KCgpmdW5jdGlvbiB0ZXN0KGFjdGlvbjogUHJvamVjdEFjdGlvbikgewogICAgc3dpdGNoIChhY3Rpb24udHlwZSkgewogICAgICAgIGNhc2UgJ0FERF9QUk9KRUNUJzoKICAgICAgICAgICByZXR1cm4gYWN0aW9uLnRleHQKICAgICAgICBjYXNlICdERUxFVEVfUFJPSkVDVCc6CiAgICAgICAgICByZXR1cm4gYWN0aW9uLmlkCiAgICAgICAgZGVmYXVsdDoKICAgICAgICAgIHJldHVybiBudWxsCgogICAgfQogICAgCn0KCmZ1bmN0aW9uIHRlc3QoYWN0aW9uOiBQcm9qZWN0QWN0aW9uKSB7CiAgICBzd2l0Y2ggKGFjdGlvbi50eXBlKSB7CiAgICAgICAgY2FzZSAnQUREX1BST0pFQ1QnOgogICAgICAgICAgIHJldHVybiAoKSA9PiBhY3Rpb24udGV4dAogICAgICAgIGNhc2UgJ0RFTEVURV9QUk9KRUNUJzoKICAgICAgICAgIHJldHVybiAoKSA9PiBhY3Rpb24uaWQKICAgICAgICBkZWZhdWx0OgogICAgICAgICAgcmV0dXJuIG51bGwKCiAgICB9CiAgICAKfQ==)
If used within a function in a case all of a sudden flow forgets about the fact that we are already in a particular case.

**Comment by vkurchatkin** [comment]
This is correct behaviour. `action` is a mutable binding, so it can change before function is called. Here is a fix: https://tryflow.org/?code=ZXhwb3J0IHR5cGUgUHJvamVjdEFjdGlvbiA9IAp8IHsgdHlwZTogJ0FERF9QUk9KRUNUJywgdGV4dDogc3RyaW5nIH0KfCB7IHR5cGU6ICdERUxFVEVfUFJPSkVDVCcsIGlkOiBzdHJpbmcgfQp8IHsgdHlwZTogJ1NFVF9DVVJSRU5UX1BST0pFQ1QnLCBpZDogc3RyaW5nIH0KCgpmdW5jdGlvbiB0ZXN0KGFjdGlvbjogUHJvamVjdEFjdGlvbikgewogICAgc3dpdGNoIChhY3Rpb24udHlwZSkgewogICAgICAgIGNhc2UgJ0FERF9QUk9KRUNUJzoKICAgICAgICAgICByZXR1cm4gYWN0aW9uLnRleHQKICAgICAgICBjYXNlICdERUxFVEVfUFJPSkVDVCc6CiAgICAgICAgICByZXR1cm4gYWN0aW9uLmlkCiAgICAgICAgZGVmYXVsdDoKICAgICAgICAgIHJldHVybiBudWxsCgogICAgfQogICAgCn0KCmZ1bmN0aW9uIHRlc3QoYTogUHJvamVjdEFjdGlvbikgewogICAgY29uc3QgYWN0aW9uID0gYTsKICAgIHN3aXRjaCAoYWN0aW9uLnR5cGUpIHsKICAgICAgICBjYXNlICdBRERfUFJPSkVDVCc6CiAgICAgICAgICAgcmV0dXJuICgpID0+IGFjdGlvbi50ZXh0CiAgICAgICAgY2FzZSAnREVMRVRFX1BST0pFQ1QnOgogICAgICAgICAgcmV0dXJuICgpID0+IGFjdGlvbi5pZAogICAgICAgIGRlZmF1bHQ6CiAgICAgICAgICByZXR1cm4gbnVsbAoKICAgIH0KICAgIAp9

**Comment by alexeygolev** [comment]
How exactly can it change? e.g. in this [scenario](https://tryflow.org/?code=ZXhwb3J0IHR5cGUgUHJvamVjdEFjdGlvbiA9IAp8IHsgdHlwZTogJ0FERF9QUk9KRUNUJywgdGV4dDogc3RyaW5nIH0KfCB7IHR5cGU6ICdERUxFVEVfUFJPSkVDVCcsIGlkOiBzdHJpbmcgfQp8IHsgdHlwZTogJ1NFVF9DVVJSRU5UX1BST0pFQ1QnLCBpZDogc3RyaW5nIH0KCgpmdW5jdGlvbiB0ZXN0KGFjdGlvbjogUHJvamVjdEFjdGlvbikgewogICAgc3dpdGNoIChhY3Rpb24udHlwZSkgewogICAgICAgIGNhc2UgJ0FERF9QUk9KRUNUJzoKICAgICAgICAgICByZXR1cm4gYWN0aW9uLnRleHQKICAgICAgICBjYXNlICdERUxFVEVfUFJPSkVDVCc6CiAgICAgICAgICByZXR1cm4gYWN0aW9uLmlkCiAgICAgICAgZGVmYXVsdDoKICAgICAgICAgIHJldHVybiBudWxsCgogICAgfQogICAgCn0KCmZ1bmN0aW9uIHRlc3QyKGFjdGlvbjogUHJvamVjdEFjdGlvbikgewogICAgc3dpdGNoIChhY3Rpb24udHlwZSkgewogICAgICAgIGNhc2UgJ0FERF9QUk9KRUNUJzoKICAgICAgICAgICByZXR1cm4gW10uZmlsdGVyKHggPT4gYWN0aW9uLnRleHQpCiAgICAgICAgY2FzZSAnREVMRVRFX1BST0pFQ1QnOgogICAgICAgICAgcmV0dXJuIFtdLmZpbHRlcih4ID0+IGFjdGlvbi5pZCkKICAgICAgICBkZWZhdWx0OgogICAgICAgICAgcmV0dXJuIG51bGwKCiAgICB9CiAgICAKfQ==)

**Comment by vkurchatkin** [comment]
Well, flow has no way of knowing that function runs callback synchronously

**Comment by alexeygolev** [comment]
@vkurchatkin would you mind giving an example where action can change before the function is called? Trying to wrap my head around it

**Comment by vkurchatkin** [comment]
You probably mean tha binding is local and it's possible to detect that there no mutations, but I guess flow just doesn't do that

**Comment by alexeygolev** [comment]
@vkurchatkin Well, to be honest, I just don't understand the `action is a mutable binding, so it can change before function is called` part. I was hoping an example would help me:)

**Comment by andreypopp** [comment]
@alexeygolev for [example](https://tryflow.org/?code=dHlwZSBBY3Rpb24gPSB7dHlwZTogJ3N0cmluZyc7IHN0cmluZzogc3RyaW5nfQogICAgICAgICAgICB8IHt0eXBlOiAnbnVtYmVyJzsgbnVtYmVyOiBudW1iZXJ9OwogICAgICAgICAgICAKZnVuY3Rpb24gcmVwb3J0KGFjdGlvbjogQWN0aW9uKSB7CiAgICBsZXQgZXhlY3V0ZTsKICAgIGlmIChhY3Rpb24udHlwZSA9PT0gJ3N0cmluZycpIHsKICAgICAgICBleGVjdXRlID0gKCkgPT4gY29uc29sZS5sb2coJ0l0IGlzIGEgc3RyaW5nJywgYWN0aW9uLnN0cmluZyk7CiAgICB9IGVsc2UgewogICAgICAgIGV4ZWN1dGUgPSAoKSA9PiBjb25zb2xlLmxvZygnSXQgaXMgYSBudW1iZXInLCBhY3Rpb24ubnVtYmVyKTsKICAgIH0KICAgIGFjdGlvbiA9IHt0eXBlOiAnbnVtYmVyJywgbnVtYmVyOiA0Mn07IC8vIG9vcHMsIGV4ZWN1dGUgd2lsbCBmYWlsIGIvYyBvZiB0aGlzCiAgICBleGVjdXRlKCk7Cn0=)

**Comment by andreypopp** [comment]
@alexeygolev ok, flow could easily analyse this, but consider [this example](https://tryflow.org/?code=dHlwZSBBY3Rpb24gPSB7dHlwZTogJ3N0cmluZyc7IHN0cmluZzogc3RyaW5nfQogICAgICAgICAgICB8IHt0eXBlOiAnbnVtYmVyJzsgbnVtYmVyOiBudW1iZXJ9OwogICAgICAgICAgICAKZnVuY3Rpb24gcmVwb3J0KGFjdGlvbjogQWN0aW9uLCB0aW1lb3V0OiBudW1iZXIpIHsKICAgIGxldCBleGVjdXRlOwogICAgaWYgKGFjdGlvbi50eXBlID09PSAnc3RyaW5nJykgewogICAgICAgIGV4ZWN1dGUgPSAoKSA9PiBjb25zb2xlLmxvZygnSXQgaXMgYSBzdHJpbmcnLCBhY3Rpb24uc3RyaW5nKTsKICAgIH0gZWxzZSB7CiAgICAgICAgZXhlY3V0ZSA9ICgpID0+IGNvbnNvbGUubG9nKCdJdCBpcyBhIG51bWJlcicsIGFjdGlvbi5udW1iZXIpOwogICAgfQogICAgc2V0VGltZW91dChmdW5jdGlvbigpIHsKICAgICAgYWN0aW9uID0ge3R5cGU6ICdudW1iZXInLCBudW1iZXI6IDQyfTsgLy8gb29wcywgZXhlY3V0ZSBjb3VsZCBmYWlsIGIvYyBvZiB0aGlzIAogICAgfSwgMTAwKTsKICAgIHNldFRpbWVvdXQoZXhlY3V0ZSwgdGltZW91dCk7Cn0=)

**Comment by rpominov** [comment]
It can also be mutated from outside:

```js
function test(action: ProjectAction) {
    switch (action.type) {
        case 'ADD_PROJECT':
           return () => action.text
        case 'DELETE_PROJECT':
          return () => action.id
        default:
          return null
    }
}

const action = { type: 'DELETE_PROJECT', id: '123' }
const fn = test(action)
action.type = 'SET_CURRENT_PROJECT'
fn()
```

That makes it weird that https://github.com/facebook/flow/issues/2318#issuecomment-241798939 fix works, btw. I think a more correct fix looks like [this](https://tryflow.org/?code=ZXhwb3J0IHR5cGUgUHJvamVjdEFjdGlvbiA9IAp8IHsgdHlwZTogJ0FERF9QUk9KRUNUJywgdGV4dDogc3RyaW5nIH0KfCB7IHR5cGU6ICdERUxFVEVfUFJPSkVDVCcsIGlkOiBzdHJpbmcgfQp8IHsgdHlwZTogJ1NFVF9DVVJSRU5UX1BST0pFQ1QnLCBpZDogc3RyaW5nIH0KCgpmdW5jdGlvbiB0ZXN0KGFjdGlvbjogUHJvamVjdEFjdGlvbikgewogICAgc3dpdGNoIChhY3Rpb24udHlwZSkgewogICAgICAgIGNhc2UgJ0FERF9QUk9KRUNUJzoKICAgICAgICAgICByZXR1cm4gYWN0aW9uLnRleHQKICAgICAgICBjYXNlICdERUxFVEVfUFJPSkVDVCc6CiAgICAgICAgICByZXR1cm4gYWN0aW9uLmlkCiAgICAgICAgZGVmYXVsdDoKICAgICAgICAgIHJldHVybiBudWxsCgogICAgfQogICAgCn0KCmZ1bmN0aW9uIHRlc3QoYWN0aW9uOiBQcm9qZWN0QWN0aW9uKSB7CiAgICBzd2l0Y2ggKGFjdGlvbi50eXBlKSB7CiAgICAgICAgY2FzZSAnQUREX1BST0pFQ1QnOgogICAgICAgICAgY29uc3Qge3RleHR9ID0gYWN0aW9uCiAgICAgICAgICByZXR1cm4gKCkgPT4gdGV4dAogICAgICAgIGNhc2UgJ0RFTEVURV9QUk9KRUNUJzoKICAgICAgICAgIGNvbnN0IHtpZH0gPSBhY3Rpb24gICAgCiAgICAgICAgICByZXR1cm4gKCkgPT4gaWQKICAgICAgICBkZWZhdWx0OgogICAgICAgICAgcmV0dXJuIG51bGwKCiAgICB9CiAgICAKfQ==).

**Comment by alexeygolev** [comment]
@rpominov I like the destructuring one. Mutating scenario is very annoying:( mostly because you wouldn't write your code like this. It can be a pain to grok by the flow beginners (taken that redux is very popular)

**Comment by alexeygolev** [comment]
@rpominov what result do you expect `fn()` to return? Because if you run this code it returns `123` which I would expect it to return.

**Comment by rpominov** [comment]
Yea. I've tried to build [more illustrative example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2YAvGKmGAD5gDe2+AXGAOSE8AaMAENurUWEoBXALYAjPACcAvsobM2HPNx4AhQWDlijk2QpVrUoVFCmVSFahjwBnDAAphDqtxLkqAJTc7gG0AHym8kps6i4IZBjEABZgnt6UAHRaoazqjMTCLgR8PJx5jGCKeBhSitQh4SLpGcIt5QVFvPplFRVVNXWpoTQRXv6Zchly5QAmeFDCUjAYPb2V1bX1wxEADOpqaijotvbjYM5unr7pQUON0lGKMflUbk1ndMKx8YkpaeNZXB4HLtQrFfirXr9TZ3EbvRwtNq9DrFbrlRjQwYNOFjBGTaa9OYLJYrdHrAZbRp7RgHdDEV4YeFUWiaIE6fhCCTibgAJlUqHplDeUGodAuHlxgVQksyWhZeh40uawhZdiJZEoeBmSoBchZrBMfNQQA) and it shows that https://github.com/facebook/flow/issues/2318#issuecomment-241798939 is a correct fix. Flow protects from such kind of mutations. So we need to only care about variable `action` from `test()` scope being mutated. Cool!

**Comment by alexeygolev** [comment]
@rpominov but isn't mutating the bound variable a very discouraged practice? It just seems like good practices are penalised for the support of the bad ones. But again, just my opinion. I might not see the whole picture

**Comment by rpominov** [comment]
I guess it's a tradeoff between more safety and convenience. I probably don't see the whole picture either.

**Comment by vkurchatkin** [comment]
> good practices are penalised for the support of the bad ones

Not sure what you are talking about. Mutating argument binding  is not encouraged, but it's a possiblity

**Comment by alexeygolev** [comment]
@rpominov I 100% agree with you on this one. I'd rather make mutation inconvenient though:) at the moment it's the other way round

**Comment by alexeygolev** [comment]
@vkurchatkin it's a possibility indeed, but the examples provided (although they are obviously naive) show that normally when you do mutate your argument binding in a way it can mess up your closures you probably don't care much about statically checking your code:)

**Comment by samwgoldman** [comment]
The workaround from the [caveats section of the docs on dynamic type tests](https://flowtype.org/docs/dynamic-type-tests.html#caveats) will also work in this case.

Making Flow more sensitive to refinement invalidation is definitely something we will continue to work on, but for the moment, this is working as designed.

**Comment by wereHamster** [comment]
If flow wants to be pessimistic, it MUST also consider property accesses to potentially mutate the object. The following code is /not/ sound if you allow mutable values or impure functions in the language:

```javascript
const x: { y?: string } = ...
if (x.y) {
  const y = x.y; // may be undefined / null!
  something(); // this line is irrelevant because you already lost.
}
```

Trivial counterexample: 

```javascript
const x = {
  _y: "haha",
  get y(): string | null { const ret = this._y; this._y = null; return y; },
};
```

**Comment by gcanti** [comment]
@wereHamster get/set properties are not yet supported

**Comment by vkurchatkin** [comment]
@wereHamster IMO the best way to support these scenarios is to make accessor properties incompatible with simple properties.

**Comment by wereHamster** [comment]
And then you have [Proxy](https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Global_Objects/Proxy), which should be completely transparent to surrounding code.

If you want to be on the safe side, you would have to force the user to deconstruct all values he uses inside a type refinement branch to primitive values (boolean, string, number), because only those are truly immutable.
