### ISSUE TITLE
Passing `this` as a parameter to a function call inside of a class method will error if the parameter is defined as `this`'s superclass

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#232]
Sorry for the awkwardly long issue title, couldn't find a more succinct way to put it. Here's the relevant code:

```js
/* @flow */

class A { }

function foo(a: A) { }

class B extends A {
  tryFoo() {
    foo(this);
  }
}

var b = new B();
b.tryFoo();
```

This should typecheck fine, as `B extends A`, and thus is a valid argument to pass to `foo`. Instead, the following error is output:

```
/Users/tboyt/flowtest/foo.js:7:7,7: B
This type is incompatible with
  /Users/tboyt/flowtest/foo.js:5:17,17: A

Found 1 error
```

This seems to be an issue specific to using an instance's context, as just calling `foo(b)` will typecheck with no errors. This is also a very frustrating error, as the line numbers in the error don't match up to the actual function call (line 9) - it took me a while to track down the source!

It can be worked-around by narrowing with a runtime typecheck, like so:

```
class B extends A {
  tryFoo() {
    if (this instanceof A) {
      foo(this);
    }
  }
}
```

But obviously, this shouldn't be required.

**Comment by samwgoldman** [comment]
This example no longer causes a type error.

**Comment by samwgoldman** [comment]
Please reopen if this is an issue.
