### ISSUE TITLE
type inference when throwing on null nullable properties

### ISSUE THREAD

**Issue by taylor1791** [facebook/flow#2323]
Flow does not infer that a property is not null after throwing on a null property. However, if we create a new object with the property it does not.

Here is an example of the first sentence. Uncomment the return statement to see the effect of creating a new object.

In theory, we could create a new object, but it is often desirable to return the same reference.

https://flowtype.org/try/#0C4TwDgpgBAglC8UDeAoKUB2BDAthAXFAM7ABOAlhgOYA0KAvgNwoqiRQDKwWw0iSAezBgBGCBmCEA-DCatw0AAqkhRBMiEixEwrOYoAZgFcMAY2DlRxCABsI5gBQkeBTt14BKQstXI0UcgMoJ3cIADpNUXFgBEQMIxsbDz90dGAACxUAd0wIHIBRUhVSBwByADkBKAB5YSiJUo9mdHoWdAB6dqhSCGAjUgwNOu1JYlCI4ejW9B6+gbGXZlagA

As a reference
Code:
```
type A = {
  name: string,
};

type State = {opponent: ?A};
type Props = {opponent: A};

function select(state: State): Props {
  if (state.opponent == null) {
    throw new Error('No Opponent');
  }

  // return {opponent: state.opponent}
  return state;
}
```
Error
```
5: type State = {opponent: ?A};
                            ^ null. This type is incompatible with
6: type Props = {opponent: A};
                           ^ object type
5: type State = {opponent: ?A};
                            ^ undefined. This type is incompatible with
6: type Props = {opponent: A};
                           ^ object type
```

**Comment by samwgoldman** [comment]
This kind of refinement is unsound in general, because objects are mutable. Consider the following code, if this function type-checked:

```js
var state: State = { opponent: { name: "Taylor" } };
var props: Props = select(state);
state.opponent = null; // this write also changes `props`, which no longer has type `Props`
```

**Comment by taylor1791** [comment]
Looks like your beat your opponent this round! Good game and thank you.
