### ISSUE TITLE
How to instantiate a type alias

### ISSUE THREAD

**Issue by arekkas** [facebook/flow#2324]
I tried looking everywhere, but I couldn't find an answer. How can I instantiate a type without having to copy all the keys. If I had to prototype it, I would write it as:

```jsx
type Foo = {
  baz: string,
  bar: string
}

// what I want to do
const a: Foo = { ...Foo, baz: 'bar' }
console.log(a) // { bar: '', baz: 'bar' }

// what I currently do
const a: Foo = { bar: '', baz: 'bar' }
console.log(a) // { bar: '', baz: 'bar' }
```

This obviously only makes sense when more keys are defined in `Foo` but the example should be enough to understand the problem.

**[Code example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgBGAhgF4BcYAzhgE4CWAdgHMANDXoMubTr0GoAvumDAwCABYMMYAJLKGfDRlIATOKgDGcPpzAM2xUhUpgAdC7tCxrMAHJGXL2HlzSzgYPCd4AQAKBgBKMEUqMQlvL3dGTx9xf3kzCys6WxJyRPS2TL8A3ODQ8LgoujiEx18y1I8y32yFJVV1LTBTAFcuLjw9GCwwYyqrU0L7EvFWtOYOrMqg9hCwiMjTRqVmpZSVjM6AoA).**

**Comment by vkurchatkin** [comment]
You can't instantiate a type. Flow type just describes object structure. Instantiating is done with plain javascript code.

**Comment by arekkas** [comment]
Would this be something subject to reconsideration or is that decision final?

**Comment by vkurchatkin** [comment]
In Flow compilation to javascript means simply removing all Flow-specific constructs. I don't think that this is going to change.

Here is what you can do:

```js
type Foo = {
  baz: string,
  bar: string
};

const emptyFoo = {
  bar: '',
  baz: ''
};

const a: Foo = { ...emptyFoo, baz: 'bar' }
```

**Comment by arekkas** [comment]
Ok, that's how I do it at the moment. With a lot of keys, this get's harder to refactor (add, remove, rename keys).

**Comment by vkurchatkin** [comment]
Well, flow has no way of knowing default values for fields anyway

**Comment by arekkas** [comment]
I assumed flow would use defaults like any other typed language. An uninitialized string is empty, an uninitialized reference is nil/null, An uninitialized number is 0, ...

**Comment by jesseschalken** [comment]
@arekkas Only nullable types can be nil/null, so non-nullable references have no meaningful default.

**Comment by arekkas** [comment]
I see, thanks
