### ISSUE TITLE
CLI `--quiet` flag to suppress all output except when there are errors

### ISSUE THREAD

**Issue by tribou** [facebook/flow#2329]
Hi,

I'd like to formalize the request mentioned in scrooloose/syntastic#1649 for flow to provide a `--quiet` option that suppresses all output except errors.  This will help improve the unbearable experience using Syntastic where it has to run `flow check` and block on every save.

**Comment by samwgoldman** [comment]
cc @thejameskyle The linked issue describes some frustration with Flow/IDE integration. Wanted to make sure this was on your radar.

**Comment by gabelevi** [comment]
Doesn't `flow check --quiet` already exist?

**Comment by tribou** [comment]
Sorry for the confusion. 

I think that's the command currently used in Syntactic which causes a few seconds of blocking each time it's run. The `flow` and `flow check-contents` commands are the ones that executed much faster in my tests.

**Comment by gabelevi** [comment]
Ah ok, got it. The non-server commands like `flow status` and `flow check-contents` need `--quiet` flags. Furthermore, the quiet flag should suppress more than it actually does. I think at the moment it just suppresses the profiling information.

**Comment by olalonde** [comment]
Bump!

**Comment by mroch** [comment]
duplicate of #2185, this is fixed in 0.34+
