### ISSUE TITLE
React decorated components

### ISSUE THREAD

**Issue by tmonte** [facebook/flow#2331]
I have a nested component with flow definitions for props. The component is decorated with react-jss useSheet(), like:
```
// Parent.js -- No error
const Parent = () => 
    <div><Child/></div>

// Child.js
styles = {...}
const Child = ({name}:{name: string}) => 
    <div>{name}</div>
Child.propTypes = {name: React.PropTypes.string.isRequired}
export default useSheet(Child, styles)
```
Flow does not see a problem in the above code, even if the required prop is not passed in.
It does find the error if the component is not decorated though:
```
// Parent.js -- Property not found
const Parent = () => 
    <div><Child/></div>

// Child.js
const Child = ({name}:{name: string}) => 
    <div>{name}</div>
Child.propTypes = {name: React.PropTypes.string.isRequired}
export default Child
```

Any ideas on what to do in this case?

**Comment by aackerman** [comment]
In this case flow doesn't have annotations for `useSheet` so flow doesn't know what the return value of `useSheet` is. 

If you run coverage on the file `flow coverage --color Child.js` you will see colored annotations of the parts of the file that have coverage issues, `useSheet` being one of them. It will be necessary for you to add type annotations for useSheet.

**Comment by gcanti** [comment]
```js
// Child.js

type FunctionComponent<P> = (props: P) => ?React$Element<any>;

declare function useSheet<P, FC: FunctionComponent<P>>(C: FC, styles: Object): FC;

const Child = ({name}: {name: string}) => <div>{name}</div>

export default useSheet(Child, { ... })
```

**Comment by tmonte** [comment]
Thanks! That really helps. Shouldn't it have thrown an error when I flow check it though, like in the example in the "Checking third party code" of the docs? Am I missing some config?

**Comment by aackerman** [comment]
`flow check` doesn't error if you don't have 100% expression coverage on your code. I believe it will make some assumptions to keep running.

**Comment by tmonte** [comment]
That makes sense, thanks!
