### ISSUE TITLE
Missing type definitions for SVG elements

### ISSUE THREAD

**Issue by aackerman** [facebook/flow#2332]
Many of the MDN docs for SVG elements seem to specify the same interface as corresponding HTML elements. The [SVGTitleElement](https://developer.mozilla.org/en-US/docs/Web/API/SVGTitleElement) element is the same in SVG and the DOM for all intents and purposes. But several elements are specific only to SVG and it would be nice to get them added.

These are a couple examples:
https://developer.mozilla.org/en-US/docs/Web/API/SVGElement
https://developer.mozilla.org/en-US/docs/Web/API/SVGRect

**Comment by lionelB** [comment]
I would like to help since I need these definitions too :)

**Comment by iainbeeston** [comment]
Sounds like something that could go into [flow-typed](https://github.com/flowtype/flow-typed)?

**Comment by jgebhardt** [comment]
Afaik, flow-typed focuses on _third-party_ libraries.
@nmote can you confirm whether `lib/dom.js` would be the right place for SVG definitions?

**Comment by xtuc** [comment]
What is the status of this issue? Do you mind if do a PR?

**Comment by aackerman** [comment]
I have some work on a branch that I put a couple hours into, but no PR yet, I was looking at creating a PR in the next day or so.

**Comment by nmote** [comment]
@jgebhardt Right, core libdefs still belong here. There's talk of moving them all to flow-typed but that hasn't happened yet.

**Comment by lifeiscontent** [comment]
@aackerman any updates on this?

**Comment by emarukyan** [comment]
still nothing ?

**Comment by jgebhardt** [comment]
@emarukyan it sure seems that way– luckily, pull requests are accepted :)

@lionelB and others who want to help, the process should be fairly straightforward, though a bit laborious:
Comb through the [SVG spec](https://svgwg.org/svg2-draft/types.html#DOMInterfacesForSVGElements) and translate any type definitions to Flow declarations in https://github.com/facebook/flow/blob/master/lib/dom.js. It might make sense to split this up by interface.

**Comment by lionelB** [comment]
@jgebhardt thx! I will take a look

**Comment by TrySound** [comment]
I started here https://github.com/facebook/flow/pull/4551
Who want to help a can share access for fork.

**Comment by TrySound** [comment]
This probably can be closed in favor of #4551.
/cc @vkurchatkin
