### ISSUE TITLE
Missing initEvent method of document.createEvent('Event')

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#2336]
See https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzAUwwBcwBeMAEzgGMBXAW3wDsiA6anfLI-AUQ2ZEAFAHJ+gkQEoA3KkJsAlkwVFxLUZyzUiAWmowF1ANYiANGChYYAZ3znLN-DNRA

We're using it in React: https://github.com/facebook/react/blob/master/src/renderers/shared/utils/ReactErrorUtils.js#L71-L72

**Comment by samwgoldman** [comment]
I think we removed this recently because it's deprecated. I'm not opposed to adding it back, but you might consider not using a deprecated API.

**Comment by vjeux** [comment]
cc @spicyj

**Comment by samwgoldman** [comment]
Yeah, I'm OK with supporting it. (Although @mroch may feel differently, I believe we want to discourage it in general.)

**Comment by mroch** [comment]
i don't think it was removed. `initCustomEvent` was added in https://github.com/facebook/flow/commit/f592ccb16ca06ec9c746d107648ae41f2c8658b6 despite being deprecated, so seems like we can add it.
