### ISSUE TITLE
Missing defintion for PromiseRejectionEvent

### ISSUE THREAD

**Issue by bassettsj** [facebook/flow#2338]
Greetings, it looks like flow core libs are missing unhandled promise rejection events.

- [Unhandled Rejections](http://www.2ality.com/2016/04/unhandled-rejections.html)
- [Node - Event: 'unhandledRejection'](https://nodejs.org/api/process.html#process_event_unhandledrejection)

**Comment by aackerman** [comment]
The event itself was added in the past few days, probably not in a release yet. https://github.com/facebook/flow/blob/c4cd21aa367c5eef2da63b917e0c2cd865c1a4d6/lib/dom.js#L223-L226

**Comment by bassettsj** [comment]
Oh let me close this then 💅
