### ISSUE TITLE
How to use it with CoffeeScript?

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#234]
I have some legacy CoffeeScript code that I want to use with Flow. How would you recommend I go about this task? Is it feasible to pass js generated by CoffeeScript through Flow? What might I lose in that process?

**Comment by myfreeweb** [comment]
You'll lose correct line numbers.  Just go ahead and try it, might be okay :)

**Comment by srb-** [comment]
I wasn't able to get Flow going with CS out of the box (I believe it chokes on the wrapper function) but I did get it going with the excellent Flotate:

https://github.com/jareware/flotate

Just annotate your functions with block comments (###) and you're good to go. The line numbers don't match up to the CS but I can live with that...

**Comment by volkanunsal** [comment]
@srb- flotate looks awesome. I'm going to play with it. Thanks for sharing.

**Comment by volkanunsal** [comment]
flotate is going very slow for me @srb-. It might be because it recursively copies all my files to a temp directory, apparently, and I have a lot of files in this project. Also, occasionally there were some weird errors that I didn't know how to fix. So, back to square one again!

**Comment by srb-** [comment]
@volkanunsal you're right - I've experimented some more with flotate and there's too much missing functionality (custom types, for example.) Darn. 

As an aside, I've been trying out TypeScript and I'm enjoying a lot of aspects of it (except for the mash of ugly brackets.) It seems to be evolving in good directions too. I'm thinking I'll do my next project in that.

**Comment by volkanunsal** [comment]
TypeScript looked good. My only reservation with it was the lack of type inference. 

Regarding the wrapper functions you mentioned above, have you tried compiling CS without wrapper functions using the `-b` flag?

```
-b, --bare         compile without a top-level function wrapper
```

**Comment by volkanunsal** [comment]
With 0.4.0, comment annotations are in Flow, so I can close this.
