### ISSUE TITLE
Incorrect type checking callback

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2341]
```
/* @flow */

type FuncType = () => void;

function foo(callback: FuncType): void {
  callback('asadsa');
}

foo(() => {
});
```

resulting message: No errors!

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiArgHYDGAKrgQLxgAUAlGLQHxgBucAlgCYBudFDLkMPOKTBQ4cBuQCGMGACMF5ANYAuIqOr4mO7vzABvVGDCLlazQwDkCgM4K+L+0yEBfYbIbNWDnMvTyA

**Comment by gcanti** [comment]
It's by design https://github.com/facebook/flow/issues/2155

**Comment by szagi3891** [comment]
it is weak :(

**Comment by samwgoldman** [comment]
Closing to keep discussion in the existing issue.
