### ISSUE TITLE
Editor support FAQ entry

### ISSUE THREAD

**Issue by hpurmann** [facebook/flow#2342]
We are currently on our way to migrate our existing CoffeeScript codebase into either 
- ES6 + Flow
- TypeScript

I tried to sum up advantages/disadvantages of these two and got stuck on the "Editor support" aspect. [TypeScript has a Docs page](https://github.com/Microsoft/TypeScript/wiki/TypeScript-Editor-Support) to sum up Editor Support. Can we have something similar for Flow? I'd make a PR with a draft if that's OK.

**Comment by samwgoldman** [comment]
Yeah it would be nice to explain our editor support better. Thanks for the recommendation!

**Comment by hpurmann** [comment]
I'm closing this because there is [that neat docs page](https://flow.org/en/docs/editors/).
