### ISSUE TITLE
0.31 branch is missing commits from Aug 11-Aug 17

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2343]
Found this confusing when wondering why the following features didn't work:

* [Sugar for exact object types](https://github.com/facebook/flow/commit/c710c40aa2a115435098d6c0dfeaadb023cd39b8)
* [Missing values in tuples](https://github.com/facebook/flow/issues/2215)

They work properly on [FlowType Try](https://flowtype.org/try/#0FDAuE8AcFMAIFEAeBDAxqA8gIwFbXbALywDeAPgGYD2VAXLAM6gBOAlgHYDmZAvgNxgocJGky58oAExFYAEhHoAPCWp1GLDpx4A+PkA) but not in the release.

Was this intentional? If so, in the future, could FlowType Try be pegged to a release (or even better yet, have a release selector: `master|0.31|0.30` etc)?

**Comment by STRML** [comment]
Just to clarify, I understand these things weren't in the release notes either - but as a user of Flow in production you get used to reading the code/commit logs to find undocumented features to properly type your programs.

**Comment by samwgoldman** [comment]
We try to release every two weeks. On even weeks we cut the release branch and on odd weeks we push it out. Between the cut and push, we are continuing to develop on master, but those commits won't necessarily make it into the release. We do cherry-pick some important fixes into the release branch. This process means we don't need to slow down or wait to push changes around releases, but also means some commits in master will not be in the latest release. Hope this makes sense!

**Comment by STRML** [comment]
I see - thanks Sam! I appreciate the clarification.
