### ISSUE TITLE
Using "declare function" instead of "declare type" leads to strange behavior

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2352]
Is there a reason no errors are thrown when using "declare function" instead of "declare type" in the following scenario?

I just realized no errors were being thrown when calling a similar function with the wrong parameters.

```
declare function Bar<A, B: number>(value: A): B;
function Foo(value: Bar): void {}
Foo(_ => 'baz')
```

This is the correct type definition:
`declare type Bar = <A, B: number>(value: A) => B;`

**Comment by vkurchatkin** [comment]
`declare function` declares that function `Bar` exists, not that type `Bar` exists. Instead you should write:

```js
function Foo(value: typeof Bar): void {}
```
