### ISSUE TITLE
"expected `T` to occur only covariantly" and (x: {t: T}) => void

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#2354]
Not sure if I misunderstand something or there is a bug.

```js
/* @flow */

class A<+T> {
  foo(cb: (x: T) => void): void {} // this works
  bar(cb: (x: {t: T}) => void): void {} // this doesn't work
}
```

```
bar(cb: (x: {t: T}) => void): void {}
                ^ T. invariant position (expected `T` to occur only covariantly)
```

Example in ["Try Flow"](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQQB4BqAFQD4wBvVMMKOOACgwCMAuMFgD2-IBKMAF5qANzgBLACaDuk2bQC+9MO2wAnNlx79aAFwHLhYsIrkLpMlamVA)

**Comment by vkurchatkin** [comment]
Well, `x.t` is both readable and writable in the seconds case, so it's invariant

**Comment by rpominov** [comment]
So the problem is that someone can do the following?

```js
a.bar(x => {
  x.t = ...
})
```

I'm still struggling with variance so I don't understand well what I'm doing to be honest.

**Comment by rpominov** [comment]
Hm, it seems to work with a little hack:

```js
/* @flow */

type Obj<+T> = {t: T} 

class A<+T> {
  foo(cb: (x: T) => void): void {}
  bar(cb: (x: Obj<T>) => void): void {}
}
```

**Comment by vkurchatkin** [comment]
I think that variance with type aliases is broken, this is obviously unsafe.

**Comment by rpominov** [comment]
A you sure it's unsafe? [Flow seems to disallow the unsafe mutations.](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFYA8A1ACoB8YAvGAN4YBcY1AvmOgMYwAhgGdhYAIJU6LVGDBQ4cABR9iHJQA8O1AJSN6ANzgBLACY6ORsyy6ywxQQCcVasJo4kKdPQ0Mnzlv42qLaopngCTgQGTmCCHJIAdgCuALbEeI60dqiCAHQOzhr6MnIaeRiMYADk1SE6QA)

**Comment by vkurchatkin** [comment]
This definition is unsafe on it's own:

```js
type Obj<+T> = {t: T} 
```

And, as you [can see](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAMTjjAG8BfTXA40gysAISLCwAPAC5YAdhiq16zdMICeABxIB5AEYArADwBqACoA+MAF5GwgFxg9TMOhxwx5YWEGX12voSOmGYC2DEsJE8wJgBuVHtHZ3k3TS1pbxcwoA), it doesn't really work

**Comment by rpominov** [comment]
Yeah, I get it. Thanks!

So if your example worked, then this would also have to work, and this is more clearly unsafe:

```js
/* @flow */

declare class Foo {}
declare class Bar extends Foo {}
declare class Baz extends Foo {}

type Obj<+T> = {t: T} 

const x: Obj<Bar> = { t: new Bar };
const y: Obj<Foo> = x

y.t = new Baz
```

This is sad though. I'll have to choose between less convenient API on one hand and unsafe poorly typed API on the other.

**Comment by rpominov** [comment]
Is it ok to use interface for this?

```
/* @flow */

interface Obj<+T> {t: T}

class A<+T> {
  foo(cb: (x: T) => void): void {}
  bar(cb: (x: Obj<T>) => void): void {}
}
```

**Comment by vkurchatkin** [comment]
I think it is the same. The only that would make it possible is immutable properties

**Comment by rpominov** [comment]
The only difference is Flow won't complain. Though it's still [unsafe](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAMTjjAG8BfTXA40gysAISLCwAPAC5YAdhiq16zVmQ5lufAF4CR4yTTqMWqAJZjRhKPhwkA8gCMAVgB4A1ABUAfI2EAuMI9044Y8sJggp5WdnyErgC8jGAeYGJYSOFgTADcqL7+gQCeITa20lFB6ajZAHSB0QlJ+MpAA). But I'm going to use interfaces in my case, seems to be the best option, even though a bit unsafe.

**Comment by vkurchatkin** [comment]
Interfaces a pretty broken in some cases, for example, properties of optional types don't work
