### ISSUE TITLE
Function arguments typed as a disjoint union of array literals

### ISSUE THREAD

**Issue by ccorcos** [facebook/flow#2357]
I'm not sure if this is a bug necessarily so I posted a question on StackOverflow: http://stackoverflow.com/questions/39196371/defining-explicit-function-arguments-type-with-flow-type

[This code:](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccAggE4DmAzmALxgDa1G5AlgHaUC6qY-AwQIA+TDgFcAtgCM85XkMX9RzVp0oAaMBJlzeqKOI4BjDGzgcwUEgAoAdA4CGVWgC4iJCjQCUYAN58YKgAvqhAA)

``` js
/* @flow */

type FooArgs = [string]
             | [number]
             | [string, number]

function foo(...args : FooArgs) {

}
```

generates "rest parameter should have an explicit array type (or type `any`)". but I believe an array literal is an array type.

**Comment by ccorcos** [comment]
Hmm. I suppose those are Tuples, not arrays. Seems like [this should work too](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccAggE4DmAzmALxgDa1G5AlgHaUC6qY-AwQIA+TDgFcAtgCM85XkMX9RzVp0oAaMBJlzemXAWJkq9MC3ZcwogPw7Z5A-iIkASnmriYGM6subtKQdeKHEOAGMMNjgOMCgSAAoAQwAuFxMA6TTjCkoASjBstw8vHwBvPjA2KDAE7Hw4GqT6OgYAcgt1NoKKwWra+rxGsGkW9vs5brBeoXI8DHFyWMYkrWluMEr+AF8wPBhqAn6E0daGMIATPChOPAvrUVPWwJgYHq2BOYWlplWwAAYFAJdvtDtMPvwMAALciIMAAFUMAFFyLDyAk2tIkvcklRqFMPttKiCDkcanVDMNmmcwG0JuQpjN+F9Fss2m0tEkgSSwUywNDYUhEfgUWiMVicXiCTtUETUPE4BisB4OWAAIx5eWJNrK-GahUJDXoYDAbRwPaouDkQoJLWKtVaABM+sSDtpuu6dsNTq0AGYtAAWLQAVk1qCAA):

```
/* @flow */

type FooArgs = [string]
             | [number]
             | [string, number]

type FooArg = string | ?number
type FooResult = [string, number]
function foo(a: FooArg, b: FooArg) : FooResult {
  if (typeof a === 'string') {
    if (typeof b === 'number') {
      return [a, b] 
    } else if (b === undefined || b === null) {
      return [a, 0]
    } else {
      throw TypeError('bad args') 
    }
  } else if (typeof a === 'number') {
    return ['', a]
  } else {
    throw TypeError('bad args') 
  }
}

foo('yes', 1)
foo('yes')
foo(1)

// no error :(
foo(1, 2)
foo(1, 'yes')
foo(1, 2, 3, 4, 5)
```

**Comment by vkurchatkin** [comment]
Yes, typing rest arguments as tuple is not supported

**Comment by calebmer** [comment]
This works in the latest version of Flow 😊 

```js
type FooArgs = [string]
             | [number]
             | [string, number]

function foo(...args : FooArgs) {

}

foo('hello');
foo(42);
foo('hello', 42);
foo(true);
```

https://flow.org/try/#0C4TwDgpgBAYg9nAggJwOYGcoF4oG13DICWAdqgLoBQUNtdtAPniQK4C2ARhMlfXzU3yFSqADRRWnblUoAzFiQDGwInBJRZCABQA6PQEM0mAFywEKDAEooAb0qUAvvc1wtAcgAWEADbe4bywBuOW0AFgAmIJDXTx8-N3EIqJctQhYIKKA
