### ISSUE TITLE
Support Webpack Loaders

### ISSUE THREAD

**Issue by ccorcos** [facebook/flow#2363]
So I have the following code and it doesnt work:

``` js
// @flow

interface ErrorResponse<S,T> {
  status: S,
  statusText: T,
}

interface JSONResponse<S,J> {
  status: S,
  json(): Promise<J>,
}

type DecrementJSON = { count: number }
type DecrementResponse = ErrorResponse<400,string>
                       | JSONResponse<200,DecrementJSON>

// TODO DecrementResponse
export const decrement = (count : number) : Promise<DecrementResponse> =>
  fetch('/dec', {
    method: 'POST',
    headers: {
      Accept: 'application/json',
      'Content-Type': 'application/json',
    },
    body: JSON.stringify({ count }),
  })
```

Apparently because I need to validate the response. This is quite a pain in the butt. Since I'm defining the type definition and then validating that exact definition manually. So what would be cool is we could use [json-to-flow](https://www.npmjs.com/package/json-to-flow) as a webpack loader. we could do something like this:

``` js
import {DecrementResponse} './path/to/json/schema?flow'
import {DecrementResponseValidator} './path/to/json/schema?validator'
```

Now we can use the same definition for the Flow type definition and as a [validator](https://github.com/tdegrunt/jsonschema)!

**Comment by calebmer** [comment]
You can use `module.name_mapper` to support Webpack loaders. Let us know if you are still having issues 😊
