### ISSUE TITLE
flow coverage infinite loop with --color flag

### ISSUE THREAD

**Issue by aackerman** [facebook/flow#2366]
In the course of working on #2365, being a novice with OCaml I spent far too much time trying to debug this issue that I believe is an infinite loop.

To test my changes I was running `make` and then `./bin/flow coverage --color lib/node.js` and the process would hang completely instead of outputting anything to the terminal. Running the same command on `lib/dom.js` did not produce this behavior.

I see the same behavior when running the same command with the `v0.30` build so it doesn't seem to be a problem with the changes I was making at the time.

It appears to be an issue with the `split_overlapping_ranges` method.

**Comment by aackerman** [comment]
@avikchaudhuri I looked into this a little bit further and it looks like the problem is that `split_overlapping_ranges` doesn't account for `loc1` range ending in the middle of `loc2`.

```diff
- else if loc1._end.offset = loc2._end.offset then
+ else if loc1._end.offset <= loc2._end.offset then
```

**Comment by avikchaudhuri** [comment]
@aackerman Yes! I'm in the process of fixing it in master, I'll try to get it into the next deploy.
