### ISSUE TITLE
WeakMap definition in core.js has `delete` method commented out

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#237]
Is there a particular reason that `WeakMap` in core.js has the `delete` method commented out? https://github.com/facebook/flow/blob/master/lib/core.js#L297

**Comment by gabelevi** [comment]
There was a reason, but it was a very old reason. The first prototype of Flow used [pfff](https://github.com/facebook/pfff)'s parser, which didn't allow `delete` (and I think other keywords) as an object properties.

@avikchaudhuri actually fixed this recently but I don't think his diff landed. I'll make sure it makes its way into next week's release. If that's too slow then I'm also happy to merge a PR.

**Comment by samwgoldman** [comment]
`delete` is now uncommented in core.js :)
