### ISSUE TITLE
implements keyword

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#2376]
So there a lot of issues where is feature is mentioned, but theres no one specific for it.
The desired result would be to achieve following syntax:

```
interface A {
  foo() : number;
}

class AImpl implements A {
   foo() : number {
    return 1;
  }
}
```

**Comment by AlexJozwicki** [comment]
Would be quite great indeed to have this

**Comment by vkurchatkin** [comment]
Here is a workaround:

```js
class AImpl {
  constructor() {
    (this: A);
  }
   foo() : number {
    return 1;
  }
}
```

**Comment by vaukalak** [comment]
@vkurchatkin wow, I think that it's not only a workaround, but we could roll with that. Maybe the syntax is not so perfect, but that seems to cover all use cases of `implements`. You can also implement more than one interface:
```
class AImpl {
  constructor() {
    (this: A & B);
  }
  ....
}
```
I'll send a PR for documenting this on the week.

**Comment by gcanti** [comment]
Also

```js
class AImpl {
  constructor(): A {
    return this
  }
  foo() : number {
    return 1
  }
}
```

**Comment by alexeygolev** [comment]
`implements` would be nice though.

**Comment by jeffmo** [comment]
We'd like to get to this, but it's not high priority at the moment because @vkurchatkin's workaround works fairly well.
