### ISSUE TITLE
No support for merged types

### ISSUE THREAD

**Issue by NullDivision** [facebook/flow#2378]
I don't know if it's just me but, is there really no way to create a combined type.

Something like this"
```javascript
type State = { a: string };
type Dispatch: { b: Function };
type Props = $Combined<State, Dispatch> // { a: string, b: Function }
```

**Comment by vkurchatkin** [comment]
Try this: `type Props = State & Dispatch`

**Comment by NullDivision** [comment]
Yeah. A RTFM moment for me :laughing: 

Thank you for the help. Closing in relative shame.
