### ISSUE TITLE
React module definition doesn't match react.js

### ISSUE THREAD

**Issue by gabelevi** [facebook/flow#239]
When you do

    var React = require('React');

Flow understands that the `React` variable holds the module defined in [lib/react.js](https://github.com/facebook/flow/blob/master/lib/react.js#L86). However when you do

    var React = require('react');

Flow doesn't understand that `React` is referencing the defined module. While the react haste package is called `React`, the npm installation installs a `react.js` so the commonjs require would be `require('react')`.

**Comment by gabelevi** [comment]
This will be fixed in the next release. Here's what we're doing:

1. Changing the module definition from `React` to `react`
2. Updating React to be consistent between haste and node, so that you always do `require('react')`. https://github.com/facebook/react/pull/3031

**Comment by samwgoldman** [comment]
Is this still an issue? I feel like the recent changes to `lib/react.js` probably solved this.

**Comment by samwgoldman** [comment]
I can't reproduce this anymore.
