### ISSUE TITLE
Possible regression with tagged unions

### ISSUE THREAD

**Issue by nemanja-stanarevic** [facebook/flow#2391]
There seems to be a regression in 0.32 with respect to tagged unions.  Specifically, when a restriction is made based on existence of a field, the field type is not inferred correctly.  Here is a minimal example:

``` javascript
// tagged union
type ObjectType = { kind: 'object', name: string, fields: Array<string> };
type InterfaceType = { kind: 'interface', name: string, fields: Array<string> };
type UnionType = { kind: 'union', name: string, members: Array<string> };
type Type = ObjectType | InterfaceType | UnionType

function print(element: Type) {
  // this doesn't work in flow 0.32. In flow < 0.32 it was fine:
  if (element.fields) {
    element.fields.forEach(f => console.log(f));
  }

  // this doesn't work either:
  if (element.members) {
    element.members.forEach(f => console.log(f));
  }

  // this works fine:
  if (element.kind === 'object') {
    element.fields.forEach(f => console.log(f));
  }
}
```

Here is the example along with errors within [try flow tool](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgC4EMDm+ApgCZgCuAdgJZyWrYCeADkWAPIBGAVkQMbYAKizYBeMAG8wAa2qUSALjAByOD37ZlAGjCVcAWyJKAztgBOc-DqjUiMEsaUBBM2dyMAPKYuV8APjAAXwBuBhEwAElKbCIzKFw+ImFWMHEpWXklZTkYuISibV0DIzBvS2tbe0cwFzdPMt8AkLCUgFUaOmSxSRk5RRUqWkpCvUMTc3KwQ31OWOra9y8JxqDQphSu1I51AU2AH0jo2PjE-bB2oa70KCoBIbBmH2wACjsiQ2ilLoBKSVQwMCYHAAC2oxjAJDgRGMw2wYAQcDM0jAcjAsEQYAADAA6ADMACZsYc0fAkB4sXj8Si4QhcOCbJQjP8UVAwK8YO8iNFsTY7A5fhJmQC3h9sDzKg4eYiAKIJYHPVmiAJ8OjGOAc7HwfAK77fUIAwLoAFA7Cg8GQ6Gw+GI5FEaim2IKZnUVnsznc6azMzGAVCsAirliz1zKVmWV8eWK5Wq9VETVwbVQXX6oJGwFYU1g61I+lyJkAl1sgPcjJkUTllRqXgCZS+gHCjmi8V84yh8OR1LRyhqjVanV65mGw1AA). 

This may be related to issues #2390 and #2389

**Comment by dgreensp** [comment]
Same issue with this code:

```
type Success = {
  value1: Object;
  value2: Object;
}

type Failure = {
  error: Object;
}

type Executor = () => Success|Failure;

function execute(f: Executor) {
  const result = f();
  if (result.value1) {
    console.log(result.value1);
    console.log(result.value2);
  }
}
```

Accessing `result.value2` is marked as an error.

**Comment by vkurchatkin** [comment]
I'm going to close this, as it seems to be correct behaviour. In @dgreensp's example even if result has `value1` property, it still can be `Failure` type. The only way to prove that result is `Success` is to check that `result.error` is not an object, but types `Success` and `Failure` intersect, so there are values of `Success | Failure` that can't be theoretically refined.

**Comment by dgreensp** [comment]
Is there a way to define these types so that they do not intersect?  Thanks.

**Comment by vkurchatkin** [comment]
The best way is to add a property to all branches with non intersecting types (aka discriminated union). In theory $Exact can help as well, but I don't think it will be implemented any time soon

**Comment by dgreensp** [comment]
Ok, thanks.

So in @nemanja-stanarevic's code, the error is that `element` could be a `UnionType` with an extra `fields` field that isn't an array?

Exact record types would help.  It seems that two features are conflicting:
* Polymorphic records
* Discriminating between a union of structs in an idiomatic way

Record polymorphism is useful in other cases, but feels intrusive here.
