### ISSUE TITLE
Comparing unknown string value with enum should be marked as an error

### ISSUE THREAD

**Issue by abalhier** [facebook/flow#2394]
Hello,

Flow does not mark as an error a strict comparison between an enum value and a string constant not in this enum.
Example : https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDCc8ATmALxgDkASgKIAi1YAPjQOIP0ByL71AEIAZAKr1qAbnQBjOADsAzhjByyALiIk45KtS71eU2QsUk8AOngBzABQBLRQEkMgmAFc8ttToCUv6VQod3kZDHsFMEcXN09vTWIyXzBNACM4cwBDeTAAb1QwMFI8DHdSHJlKCj0RCUkwYGAwHjgwPFJSHTAAMXgEABowABM8RRx7DAJexFU4dxgh4EUACzmFsABreRmMZcyVXYI8AA8cYsVFCJyEexgYMEyYBEysRTBUgihHxQJsobBdvsAct2gRHA93u5rKgAL6oIA

**Comment by vkurchatkin** [comment]
IMO this shouldn't be an error, but it should be used to detect unreachable code, and this in turn can be optionally treated as an error

**Comment by abalhier** [comment]
In which case unreachable code would be correct/useful ?

**Comment by vkurchatkin** [comment]
> In which case unreachable code would be correct/useful ?

It can be useful to catch situations where static types don't reflect dynamic types for some reason. For example, variable has a enum type (`'A' | 'B'`). You can do this:

```js
if (x === 'A') {
  doA();
} else {
  doB();
}
```
and it's OK, but you can also do this:

```js
if (x === 'A') {
  doA();
} else if (x === 'B') {
  doB();
} else {
   throw new Error(`Unexpected x: ${x}`);
}
```
and it's much more reliable

**Comment by abalhier** [comment]
Indeed :)

**Comment by pronebird** [comment]
I believe this must be an error. Consider the following example:

```
type Fruit = '🍊' | '🍌' | '🍎';

const apple: Fruit = '🍎';
const a = (apple === '🍉'); // Incorrect: no error
const b = (apple === '🍉') ? true : false; // Correct: incompatible type
```

In case of `a` developer will never be notified about the error. This is typed-value vs. constant comparison (not dynamic code) and I believe case A and case B should be treated equally.

LHS is enum and it's compared against random String. This is clearly a bug.

**Comment by calebmer** [comment]
We are going to keep this behavior for now, but if any external contributors want to add a warning for this we’d be happy to merge a PR 😊

**Comment by pronebird** [comment]
@calebmer why closing the issue then?
