### ISSUE TITLE
Switch fall-through on disjoint union variants

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#2395]
It seems that switching on disjoint union tags, with fall through, does not flow correctly.

Example:

Simple union (code cannot flow to default, and Flow confirms it):
[Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAlnAHZgC8YA5AIJ1gA+9AQs23QMJ0Dc6KAFcKAYzKUwAQwDOsvACcMAOTwA3JQApSAWxxx5pAEYw8ALnp592ZgDJ6FDUroBKS9IpYwAb1QBfIVEJciocRTgxPHliSQotOEtY0PcwCmFdYyVfVDAwWQRSDDEACzAE1xy8vLE5AkY6Sz9q6sU8DGFFKgBGQRbAltqFDkbc6qH6viaxlraOrrAAJj7qgeqAEzwoaWEYDGmW6uBgGRgYMDgSUNkwMThNNvWAGlvPCjgMMFhEMAw4MBKSgIAFowAAxeBIaQAcza0RmrXanSocgUyjUDwqKzya0C-iAA)

``` js
type Option = 'A' | 'B' | 'C';

function assertNever(impossible: 'empty' & 'never'): any {
}

function processOption(o: Option): number {
  switch (o) {
    case 'A': {
      return 1;
    }
    case 'B':
    case 'C': {
      return 2;
    }
    default: {
       // all options covered, cannot flow to here - Flow agrees
      return assertNever(o);
    }
  }
}
```

Disjoint union (code cannot flow to default, but Flow does not confirm it):
[Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAlnAHZgC8YA3mNvgFxgDkAgm2AL5gA+9Rrjys2AIW59BDJqPYBhKQG50UAK4UAxmUpgAhgGdDeAE4YAcngBuZgBSkAtjjjHSAIxjy2eZ9m4AZOwUNmZsAJSs+hRY9Kg8apo65FQ4pnBaeMbEuhR2cKw5KZFgFOqO7mZxYGCGCKQYWgAWYPkAdHLh1TVgWkYEnGysdKg9PaZ4GOqmVACMqmMJY30m7JLMoz0rA0rDm2MTUzNgAEwLPUs9ACZ4UPrqMBh7YzXAwAYwMGBwJCmGvXBbBMrgAaXrRChwDBgWCIRhwMBNMwEAC0YAAYvAkFc4FlSlCDABzCZ4ACE+3Gk2mVCMJnMViB7U65xqlwSPCAA)

``` js
type Option = { type: 'A' } | { type: 'B' } | { type: 'C' };

function assertNever(impossible: 'empty' & 'never'): any {
}

function processOption(o: Option): number {
  switch (o.type) {
    case 'A': {
      return 1;
    }
    case 'B':
    case 'C': {
      return 2;
    }
    default: {
      // all options covered, cannot flow to here - Flow does not agree!
      return assertNever(o.type);
    }
  }
}
```

**Comment by jeffmo** [comment]
cc @bhosmer -- I believe this is a known issue, right?
Did you have something queued up to address it, or is it something we still need to dig into?

**Comment by bhosmer** [comment]
Hmm, this looks like a bug with switch fallthrough processing. If you give 'B' its own case, Flow properly [avoids the default](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAlnAHZgC8YA3mNvgFxgDkAgm2AL5gA+9Rrjys2AIW59BDJqPYBhKQG50UAK4UAxmUpgAhgGdDeAE4YAcngBuZgBSkAtjjjHSAIxjy2eZ9m4AZOwUNmZsAJSs+hRY9Kg8apo65FQ4pnBaeMbEuhR2cKw5KZFgFOqO7mZxYGCGCKQYWgAWYPkAdHLh1TVgWkYEnGysdKg9PaZ4GOqmVACMqmMJY30m7JLDo2NgE1MzYABMCz1LPSsDShtb25PTVIebNSc1ACZ4UPrqMBiXW8DABjAYGA4CQUoZenBbBNngAaXrRChwDBgWCIRhwMBNMwEAC0YAAYvAkM84FlSkiDABzCZ4ACED3GNz2RhM5isUPanSOj02CR4QA). 

Putting the issue back up for grabs.

**Comment by markostakic** [comment]
Works if written like [this](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAlnAHZgC8YA3mNvgFxgDkAgm2AL5gA+9Rrjys2AIW59BDJqPYBhKQG50UAK4UAxmUpgAhgGdDeAE4YAcngBuZgBSkAtjjjHSAIxjy2eZ9m4AZOwUNmZsAJSs+hRY9Kg8apo65FQ4pnBaeMbEuhR2cKw5KZFgFOqO7mZxYGBalIYYwvg0YHAAdHKqNYYIpBhaABZgdnLh1TW1RgScbKx0qBMTpngY6qZUAIxdEwmLWlPskswLE-smirPji8ur62AATNs1uxMAJnhQ+uowGHMni8BgAYYDBWiQUoZanBbMtXgAaSYUChwRqwRCMOBgAZmAgAWjAADF4EhXnAsqUUQYAObLPAAQn+SxWayoRhM5isMJGInCT14JwSPCAA):

```js
type Option = { type: 'A' } | { type: 'B' } | { type: 'C' };

function assertNever(impossible: 'empty' & 'never'): any {
}

function processOption(o: Option): number {
  const type = o.type;
  switch (type) {
    case 'A': {
      return 1;
    }
    case 'B':
    case 'C': {
      return 2;
    }
    default: {
      // all options covered, cannot flow to here - Flow does not agree!
      return assertNever(type);
    }
  }
}
```

**Comment by TrySound** [comment]
Seems like related https://github.com/facebook/flow/issues/2399
