### ISSUE TITLE
SessionStorage provided wrong type in core.js

### ISSUE THREAD

**Issue by Lalaland** [facebook/flow#240]
I am attempting to use sessionStorage in a project, but flow provides a bad type of Location.

I believe the bug is in https://github.com/facebook/flow/blob/02515d2074db14a89d70147c4e8ac36043f915d8/lib/core.js#L509.

Example code to reproduce would be:

    /* @flow */
    if (sessionStorage.getItem('currentUser'))
    {
        console.log("OK");
    }

The provided error message is:

    /home/ethan/test/foo/test.js:3:5,41: call of method getItem
    Property not found in
       /tmp/flow_ethan/flowlib_3db57ad7/lib/bom.js:28:1,41:1: Location

**Comment by gabelevi** [comment]
Thanks for the report! I took a look and fixed the definition! The fix will be in 0.1.7 next week.

**Comment by Lalaland** [comment]
Thanks for the quick fix.
