### ISSUE TITLE
When using disjoint unions, flow can't extrapolate that all cases are covered

### ISSUE THREAD

**Issue by AugustinLF** [facebook/flow#2400]
When switching on the literal type of a disjoint union, it's possible to cover all the cases, which means that the returned value of a function can be extrapolated by flow. See this [example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZhQCWATgM4ZgC8YA5AIa2a4Fl4DGcAdgCbV0AjJtnxgAqlyLd+xcpQA+YNp17oVFMOwAWHANYAVFvwAUeGHgC2eLhgBc4ydwCU9iiSJcA5tQB8YAN6oSghEGNpgpuZWNk4BQWCa9Gx0jLbxCWAkeBgAriRcdLIUtADc6exJBLRCaRkJWbn5dMrcPKVBAL6oHUA).

**Comment by iam-peekay** [comment]
yes! This would be an amazing feature to have. Annotating the return type for a function with a switch statement on a disjoint union is incredibly valuable and the only way to currently do it is to have a `default` case even if all the possible cases are covered.

**Comment by frou** [comment]
As plain as it looks, this is the standout feature that attracts me to use a sophisticated type system. I **really** hope that flow will get smarter about exhaustive switching!

**Comment by AugustinLF** [comment]
Usually, I now add a throw in the default case, see [this example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZhQCWATgM4ZgC8YA5AIa2a4Fl4DGcAdgCbV0AjJtnxgAqlyLd+xcpQA+YNp17oVFMOwAWHANYAVFvwAUeGHgC2eLhgBc4ydwCU9iiSJcA5tQB8YAN6oSghEGNpgpuZWNk4BQWCa9Gx0jLbxCWAkeBgAriRcdLIUtADc6exJBLRCaRkJWbn5dMrcPKXpPHhQ9DkwdukJGFokiGBceEgAoiQjJMYABpNR1pQAJP5mlisAvmBEZGNwlPRgAG70MER8OPQk9FYYeCSEcM-aeob4805lYNuo2yAA). I kind of like this way, it's not perfect, but it adds some explicitness :) Overall, adding invariants in these kind of cases helps flow, without making you write "illogical things".

**Comment by frou** [comment]
Isn't that straight back to the unchecked control flow of a typical C-style language?

If you then add `type third = 'c'` to the union, _flow_ will have nothing to say about it, and the function will bomb with a nonsensical error message at runtime?

**Comment by AugustinLF** [comment]
If you want to ensure that you are exhaustive (which I think is another problem, as of today, you have to use a default, which means that you already can't be exhaustive), you can cast the [value to empty](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAdgJZzFgC8YA5AIa1gA+dARk67QMa3rcUAzhjDcAFnm4BrACq4CNABR4YeALZ5iGAFxEyFAJS7hAJ1LEA5tQB8YAN6owghKQziwy1Rq0H7jsKL0ggQMtNr+AWAmeBgAriaUtFCkJsK0ANwR3EEhHOGRAdFxCXTBAsQAJhkRFXhQ9LEwOhEBnuqaOmDqONgGLWAYYiaIYMR4SACiJsMmin1gAL6oC0A).

```javascript
const checkType = (element: 'a' | 'b' | 'c'): string => {
 switch (element) {
   case 'a':
     return 'first';
   case 'b':
     return 'second';
   default:
     (element: empty)
     throw new Error()
 }
}
```

**Comment by frou** [comment]
Yep, thanks. That's a good workaround. 

Like I said, for people thinking about adopting a sophisticated type system, matching with exhaustiveness checking seems like a big win that's easy to understand! It would be great if flow completely nailed it.

**Comment by entropitor** [comment]
Is there any update on this feature / bug?

**Comment by SamChou19815** [comment]
Has been fixed a while ago
