### ISSUE TITLE
Is export something from 'something supported?

### ISSUE THREAD

**Issue by tonyxiao** [facebook/flow#2403]
Flow chokes on the following statement. 

```
export App from './app';
```

I found `esproposal.export_star_as` but it doesn't help in this case. 
https://flowtype.org/docs/advanced-configuration.html

**Comment by rpominov** [comment]
This is supported and usually works without additional configuration. What is extension of `app` file, and how it's export looks? And what error Flow gives?

**Comment by SamChou19815** [comment]
Now supported
