### ISSUE TITLE
using external files and libraries while globally declaring type definitions

### ISSUE THREAD

**Issue by l2silver** [facebook/flow#2410]
I made a stackoverflow post for this, but I think this might actually be an issue worth looking into.

So, I'm trying to declare a global $ListOf type that looks like this:

decls/immutable.js

```
import {List} from 'immutable'
declare type $ListOf<X> = List<X>
```

.flowconfig

```
[libs]
decls/
```

but when I check flowtype of $ListOf I get undefined. Is there anyway to use external libraries while creating global types? This would be really really useful if there was

**Comment by aackerman** [comment]
I think your import may be incorrect, immutable ships types separately from the implementation.

Try something like the following

```js
import type {List} from 'immutable/dist/immutable.js.flow'
```

**Comment by l2silver** [comment]
@aackerman alas, also does not work...

decls/immutable.js
````
//@flow
import type {List, Map} from 'immutable/dist/immutable.js.flow';

declare type $ListOf<X> = List<X>;
declare type $MapOf<X, Y> = Map<X, Y>;
declare type $AnotherList<X> = Array<X>
````
example.js
````
//@flow
const {List} = require('immutable');
type Role = $ListOf<number>;
const x : Role = List(['string']); // no erro, $ListOf is undefined

type Role2 = $AnotherList<number>
const y: Role2 =  List(['string']) // error, not array type
const z: Role2 =  ['string'] // error, not number
````

**Comment by aackerman** [comment]
@l2silver Does it work if you omit the type polymorphism

```js
//@flow
import type {List, Map} from 'immutable/dist/immutable.js.flow';
declare type $ListOf = List;
```

**Comment by l2silver** [comment]
@aackerman still (unknown)

**Comment by l2silver** [comment]
#2130
