### ISSUE TITLE
Missing error when `*` annotation is used in imported function

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#2416]
I ran into an issue where Flow is ignoring a specific error. Interestingly, while trying to reproduce the issue, I found that Flow will correctly detect the type error if everything is in one file without any imports.

test.js

``` js
/* @flow */
import watchEl from './watchEl';
watchEl(document.body, {attributes: true, attributeFilter: 'class'});
```

watchEl.js

``` js
/* @flow */
export default function watchEl(el: HTMLElement, options: *) {
  const m = new MutationObserver(muts => {
    console.log('got mutations', muts);
  });
  m.observe(el, options);
}
```

Line 3 of test.js should trigger an error. (`attributeFilter` is supposed to be `Array<string>`, not `string`. I make this specific mistake way too often.) Flow gives no error here. 

Interestingly, if watchEl is defined in the same file that it's called in, then Flow gives an error as it should:

``` js
/* @flow */
function watchEl(el: HTMLElement, options: *) {
  const m = new MutationObserver(muts => {
    console.log('got mutations', muts);
  });
  m.observe(el, options);
}
watchEl(document.body, {attributes: true, attributeFilter: 'class'});
```

```
$ flow
test.js:6
  6:   m.observe(el, options);
       ^^^^^^^^^^^^^^^^^^^^^^ call of method `observe`
  8: watchEl(document.body, {attributes: true, attributeFilter: 'class'});
                                                                ^^^^^^^ string. This type is incompatible with
202:         attributeFilter?: Array<string>;
                               ^^^^^^^^^^^^^ array type. See lib: ../flow/flowlib_3cfb74d/bom.js:202


Found 1 error
$ flow version
Flow, a static type checker for JavaScript, version 0.32.0
```

Possibly related: I ran into another issue before (https://github.com/facebook/flow/issues/1140) that also went away if everything was defined in one file. Maybe there's a common bug causing loss of some types across file boundaries?

**Comment by gcanti** [comment]
I guess that:

if everything is in one file Flow gives an error as it should because Flow *also* scans the implementation of `watchEl`.

if you split the code in 2 files, Flow firstly type checks `watchEl.js` and then uses *only* the exported signature in order to type check `test.js`.

The exported signature is

```js
function watchEl(el: HTMLElement, options: *)
```

so when you call

```js
watchEl(document.body, {attributes: true, attributeFilter: 'class'});
```

Flow infers `typeof {attributes: true, attributeFilter: 'class'}` for `*` and doesn't raise an error

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

We would be willing to add a warning for this if anyone wants to contribute it 👍
