### ISSUE TITLE
Could "unknown" be a return value for `typeof`?

### ISSUE THREAD

**Issue by flarnie** [facebook/flow#2417]
[In IE you will sometimes get "unknown" as the return value from `typeof`](http://stackoverflow.com/questions/10982739/typeof-returning-unknown-in-ie). This is non-standard, but still something we sometimes want to check for in code that supports old IE. The following check will trigger a Flow error though:
```
if (typeof foo !== 'unknown') {
// ...
}
```

Can we allow "unknown" as a valid return type of `typeof`, or is there a recommended work-around for this issue?

**Comment by samwgoldman** [comment]
> In IE you will sometimes get "unknown" as the return value from typeof.

Wow, I had no idea.

Should this "refine" to `mixed`? Just accept & ignore?

**Comment by jesseschalken** [comment]
As a workaround, you can thread the `typeof` through a type annotation:

```js
let foo = 1;
if ((typeof foo:string) !== 'unknown') {
// ...
}
```

You could also do the `typeof` via a function like `let typeof_ = x  => typeof x`.

**Comment by flarnie** [comment]
Ok - this is a rare enough thing that I think a workaround is fine. Thanks for the ideas!
