### ISSUE TITLE
Support for parameters after rest parameters

### ISSUE THREAD

**Issue by migueloller** [facebook/flow#2420]
I want to be able to do this:

``` es6
function promisify(fn: (...args: Array<mixed>, cb: (error: mixed, result: mixed) => mixed)) {
  return (...args) => new Promise((resolve, reject) => {
    fn(...args, (error, result) => {
      if (error) reject(error);
      else resolve(result);
    });
  });
}
```

But this is currently unsupported by Flow. Are there any other options other than making different signatures and then making an intersection of them?

**Comment by vkurchatkin** [comment]
While this could be useful for function types, it's not supported by Ecmascript, so it would hard to implement such a type, i. e. this:

```js
function fn (...args: Array<mixed>, cb: (error: mixed, result: mixed) => mixed) {}
```

is invalid

**Comment by migueloller** [comment]
It's not invalid (at least in Babel). I've implemented such function [here](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Cstage-0&code=function%20promisify(fn)%20%7B%0A%20%20return%20(...args)%20%3D%3E%20new%20Promise((resolve%2C%20reject)%20%3D%3E%20%7B%0A%20%20%20%20fn(...args%2C%20(error%2C%20result)%20%3D%3E%20%7B%0A%20%20%20%20%20%20if%20(error)%20reject(error)%3B%0A%20%20%20%20%20%20else%20resolve(result)%3B%0A%20%20%20%20%7D)%3B%0A%20%20%7D)%3B%0A%7D).

**Comment by migueloller** [comment]
You're right, it is unsupported by Ecmascript. Still, it could describe valid function signatures without having to do this:
```js
(arg1: mixed, cb: (error: mixed, result: mixed) => mixed) & (arg1: mixed, arg2: mixed, cb: (error: mixed, result: mixed) => mixed) & ...
```

If it's unsupported by Ecmascript, could it be still implemented in Flow?

**Comment by calebmer** [comment]
This is not allowed in ECMAScript and we are not going to implement it until it is in ECMAScript since we don’t add language features. Only type annotations.
