### ISSUE TITLE
Are there some `$` keyword for Function overloading partial specialization?

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2423]
Assume have a overloading Function like this:

```
type Fn = ( (v:'a', fn:(iv: boolean)=>void )=>void )&  // 1
          ( (v:'b', fn:(iv: number)=>void )=>void )&   // 2
          ( (v: string, fn: Function)=>void);          // 3
```

Literal 'a' and 'b' are more specialization than a string. Some language allow this kind overloading.(allow 'a' exclude from a const string), and cause in JavaScript, there is no Function overloading indeed, the args will be checked in runtime inside a Function, it is legal to exclude 'a' from string here, do not need a const string.
How to make this overloading work?
Currently when  use 'a' , flow will notify case 1 and case 3 will both work.

```
function ts3(f: Fn) {
  const v = f('a', iv => {}); // fail
}
```

How can i exclude 'a' and 'b' from a string?
flow try => [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAdgExgC8YAFDQG4BcA5AIZMA0YUxD1AlozAAjOHBh4WxAJQUAfHTh8AJmBnzFKqQDJUYPfoM16zIRy49+g4gFcAtkLwAnNQuWq5rzQG502fEWJKI2pGVjNuXgEGYVFxSRcNd3U3bV1DA1oQk3CLKLAbeycElI9E1PSM4zAAZwxHPmIAc04IomtiAGMMPjhpUuUpH1Qodq6ewIxqgGZqKGiSFtJ5sikwAG80jt7asDpyKihSajDOAUpZdYBfQbBN7YxdoKhjtlO6c6ub4GAuFj4YVCXIA)

**Comment by erikdesjardins** [comment]
This would be really useful, especially for stuff like [addEventListener](https://github.com/facebook/flow/blob/44962f21df27d04b364307bcb33d3b70c1ee2776/lib/dom.js#L102-L104); I end up having to annotate almost all of my event listeners to deal with the "...case 3 looks promising too"

**Comment by iamchenxin** [comment]
@erikdesjardins  Is it i missed something or a feature lacked?

**Comment by erikdesjardins** [comment]
You didn't miss anything (AFAIK); I have the same problem as you.

**Comment by iamchenxin** [comment]
@erikdesjardins Try to use this overloading to restrict the passed in parameters. 
Ideally if `v` is `a`, the passed in fn must be `(iv: boolean)=>void`, if `v` is `string`, the passed in fn could be a `Function`.
so i hope this should be checked by Flow. manual-annotating is useless to me, 
But im a bit nervous about this issue, half month passed, it is still not confirmed to  a bug, so seems it is me missed something? There is a right way to make this overloading work, but a write a stupid code. ~_~ sadness

**Comment by vkurchatkin** [comment]
@iamchenxin what you are trying to do is probably pointless, because if your string is not a literal, it's still can have value `a` or `b`

**Comment by iamchenxin** [comment]
@vkurchatkin Seems in this situation, i need some key word to declare a general string literal.(like const string ?).   So that `a` and `b` could be excluded from a const string rightly.

**Comment by alexeygolev** [comment]
@iamchenxin `a` and `b` can't be excluded from a type that includes all possible strings which the `string` type is. You'll need a way to say that my type is a set of all possible strings excluding `a` and `b`.

**Comment by iamchenxin** [comment]
@vkurchatkin @alexeygolev After think this again, I find something interesting, cause JavaScript does not really have Function overloading, in truth, it is legal to exclude a string literal from string（no need a const string, cause inside a function, the args are checked in runtime.）, this is a bit different from a language which has a Function overloading(args are checked in compile time, so 'a' and 'b' can only exclude from a const string, not a string)

Maybe in JavaScript, we should not call this feature Function overloading, they are just a description of possible args combinations.

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

If we see better patterns for function overloading in the future from JavaScript then we’ll implement it 👍
