### ISSUE TITLE
Flow fails to catch errors with bottomless types

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2425]
Here is an [example](http://bit.ly/2c8WEXz)

``` js
/* @flow */

type Never =
  | Never

class Process <exit, message> {
  send(payload:message) {
  }
}

declare export function spawn <exit> ():Process<exit, Never>


spawn().send(5)
```

I would expect flow to error with message like:

```
15: spawn().send(5)
                 ^ number. This type is incompatible with
12: declare export function spawn <exit> ():Process<exit, Never>
                                                          ^ Never
```

But instead it reports no errors.

**Comment by Gozala** [comment]
I probably define bottomless types incorrectly here, but regardless flow should definitely be failing here.

**Comment by rpominov** [comment]
Seems like what you want is similar to Empty from this issue #2225
You can use `null & void` as Never and it [should work](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgByeAbngE5gC8YAdgK4wxgBkYJcAlgCboDGMAIYBnYWAAK5OHzyiwAHjwAPThgA0YALazhggOZ4AfGADeqMGGF5a3ABQ5BWeIO4AubaP14AlKfNgAX1Qg1G48AUFyAmUcOHIMMCh6Wj4MTjhaSwcETMUVDGNbb1dJaR081Q1iMnJDf3rhbNoigDorG1sAVm8gA).

**Comment by calebmer** [comment]
We now have `empty`. We recommend that you use that 😊
