### ISSUE TITLE
Should anything typecheck when interpolated into an ES6 template string?

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#2427]
I would expect this to typecheck:

```js
function foo(x: mixed): string {
  return `hello ${x}`
}
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wBbQ6gUwBMBKegZ3wCdC2AOZgA3qjBg+LfJj6kABgAsWMeGAAko6gF8FqHaiA

When I asked in IRC I was told it was because `toString()` could throw. If I call `toString()` manually, it type checks. This seems weird to me.

**Comment by vkurchatkin** [comment]
This doesn't typecheck for the same reason this doesn't typecheck:

```js
function foo(x: mixed): number {
  return 4 * x;
}
```

It's valid js, but usually a mistake to do so.

**Comment by aaronjensen** [comment]
@vkurchatkin why is it a mistake to rely on `toString`?

**Comment by vkurchatkin** [comment]
If you pass `undefined` too `foo`, it will return `hello undefined`. This is usually considered an error. The same goes for `hello [object Object]`, etc.

**Comment by AgentME** [comment]
This isn't specific to template strings. There are other places too where Javascript will happily cast values into strings or numbers, but Flow is stricter and complains. I've found Flow's strictness handy.

**Comment by aaronjensen** [comment]
Ok, I think I'm understanding the motivation here. I'm going to go ahead and close this out. If someone on the team decides this isn't expected behavior please reopen. Thanks all.
