### ISSUE TITLE
Too easy to convert mixed to any object

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#2428]
I would expect this not to type check:

``` js
/* @flow */
const ajax = require('ajax')
const invariant = require('invariant')

const result = ajax('http://whatever')

type User = {
  name: string,
}

function handleResult(result: mixed): User {
  if (typeof result !== 'object') throw new Error
  if (!result) throw new Error

  // We didn't prove name exists and is a string, why does this work?
  return result
}
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gCGAVoQB5gC8YATgKYCOArgJb0AUA5CeZwJQZs+MCywA3QjRaEsBavWZs6XURKky8-VINwF6OJjDlFSZLgAs8eAA4AuYMATnCeOmLo0tqPAE9rdMABVHA8qMABvVDAwLEIAWzpbMHwpLABzABpUAF9tKCYsdDwWbDBnLAATGDoAJToDI3Z9QzwkuJYyOgq+JODQyOiWKDB2X384YeajMABCSmpOOAAjYjoi-jA8cxpEGLokAFEaHZookWH2Gam8Pk3t3ax9sCOTs7OHMAB1AIqWCqxOARrDt3DF4gE6GQWPgcERKiJYYRknhUpkwE4fGAKnB6ndoei4DQANYAfjO9DwTBoWFo9RaOVQQA

Is there something else I should do enforce ensuring safety w/ flow for external input?

**Comment by vkurchatkin** [comment]
Take a look at this issue: https://github.com/facebook/flow/issues/1794

**Comment by aaronjensen** [comment]
Thanks @vkurchatkin that looks like we're trying to do similar things.

**Comment by calebmer** [comment]
It looks like this is an error now. Closing because of the lack of inactivity. Thank you for reporting! 😊
