### ISSUE TITLE
Subtyping across files not working

### ISSUE THREAD

**Issue by Lalaland** [facebook/flow#243]
I am having issues extending a class which is defined in another file.

My simplest test case has two files:

test.js

    /* @flow */
    class A {}

    class B extends A {}

    var x: A = new B();

    module.exports = A;

test2.js

    /* @flow */
    var A = require("./test.js");

    class C extends A {}

    var x2: A = new C();

The error is:

     /home/ethan/test2.js:7:21,21: C
    This type is incompatible with
       /home/ethan/test.js:9:22,22: A

    Found 1 error

Am I doing something wrong, or is this a bug?

**Comment by gabelevi** [comment]
This seems like a bug and we're looking into it. Thanks for the report and the simple repro!

**Comment by samwgoldman** [comment]
Tried this with the latest version and got no errors. @Lalaland are you still having this issue?

**Comment by samwgoldman** [comment]
This can be closed.
