### ISSUE TITLE
Are there some way to make `$NonMaybeType` work on a polymorphic return Type?

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2439]
FlowTry -> [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAdgDwAqAfGALxgAUAbgFxgDOGATgJbEDmASlrUAJADk4xALIBDLACM85XHgqUA3KigBXYgGMM3SWChNWHHvwGsA-Bd58wAb1RgwnPBm2diYYtpgYTQBfdD1JDhMAJmYSUhBqOih1MGBgMAALRDAMODAAWxkAawIMDO42MD5PMBkwPE5OOE5MhrxUNPDiSKgAZliyOy4HRJMUtLAEbkD6xuagA)
I want to write a polymorphic Type to restrict a function must return a NonMaybe Type.
How can i write it? Seems \* did not resolve the return type for `$NonMaybeType`? Are there some way to make this work.

```
type Fn<T> = (v: string) => $NonMaybeType<T>;
function f(v: string): ?string {
  return null;
}

const f2:Fn<*> = f; // how to make this get a error here
//const f3:Fn<?string> = f; // will error
```

**Comment by calebmer** [comment]
We don’t recommend you use `*` since it’s very confusing if you don’t understand the deep internals of Flow. Closing because of the lack of inactivity 👍

**Comment by sibelius** [comment]
try this

```jsx
const nonMaybeHelper = <T>(v: T): $NonMaybeType<T> => {
  return v;
};
```
