### ISSUE TITLE
subset / belongs operator

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#2441]
So, I don't think this is implemented in any language. But I think, that this feature would be really great for javascript (as dynamic language). Basically all typed languages are not perfect, cause there always some un flexible points. But what if we make dynamic friend of static?
Suppose following code:

```
type Foo = { a : number, b : string };
class Immutable<T> {
  set(name: string, value: *) : this;
}

const myImmutable: Immutable<Foo> = new Immutable();
myImmutable.set('a', []);
```

For sure that code will not type check. We can improved a bit like following:

```
type Foo = { a : number, b : string };
type SetParams =  ((key: "a", value: number ) => MyImmutable ) & (( key: "b", value: string ) => MyImmutable );
class Immutable<T, SP> {
  set: SP;
}
const myImmutable: Immutable<Foo, SetParams> = new Immutable();
myImmutable.set('a', []);
```

This code will type check, but imagine we'll have to write a stuff like this EACH time that we declare an immutable object. Btw this is example is not complete, cause we should write declarations for `get` and other methods. An approach like this will make codebase so verbose, that no one will use it...
For that reason, we can use a better (shorter) approach:

```
class Immutable<T> = {
  set: function <[K, V ∈ T]>set(name: K, value: V) : this;  
}
const myImmutable: Immutable<Foo> = new Immutable();
myImmutable.set('a', []);
```

where `[K, V ∈ T]` means, a key-value pair that belongs to T. So with syntax like this flow will type check if value type corresponding to key `a` is an `Array` (and should be a `number`). Thoughts?

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

Please reopen if you still want to have a discussion around this feature!
