### ISSUE TITLE
Using generators as coroutines

### ISSUE THREAD

**Issue by darky** [facebook/flow#2445]
Very hard to use **flowtype** with libraries like https://github.com/tj/co or http://bluebirdjs.com/docs/api/promise.coroutine.html
Would be cool, if I could to mark some generators as coroutines and get an opportunity to work with it like with async/await

**Comment by samwgoldman** [comment]
Have you read the blog post we published introducing generators? It goes into some of the limitations of typing generators and offers some workarounds: https://flowtype.org/blog/2015/11/09/Generators.html

It would also help if you could provide a small example of some code that is problematic to type check.

**Comment by vkurchatkin** [comment]
I think the problem is that we can't define yield as a function, like we do with await, so using generators for coroutines is impossible

**Comment by darky** [comment]
```javascript
    type Api = { 
        // try as simple function
        getSegmentWithAudience(segment : string) : Object;
        // or try as generator
        getSegmentWithAudience(segment : string) : Generator<Object, Object, Object>;
    }

    declare type Data = {
        response : {
            result : Object | Array<Object>;
        };
    }

    // global var api
    declare var api : Api;

    run: function* (data /* :: Data */) {
        data.response.result = yield api.getSegmentWithAudience(data.params._id);
    }
```

This throw error:

`
run: function* (data /* : Data */) {
                                            ^ undefined. This type is incompatible with  result : Object | Array<Object>;
                      ^^^^^^^^^^^^^^^^^^^^^^ union: object type | array type
`

I want, that **flowtype** ignore generator in this case and parse it as simple function

**Comment by darky** [comment]
> I think the problem is that we can't define yield as a function, like we do with await, so using generators for coroutines is impossible

Would be cool if I can something like:

```javascript
function* (data /* :: Data */) /* : Coroutine<result> */ {
        data.response.result = yield api.getSegmentWithAudience(data.params._id);
    }
```

And all `yield` inside it ignores and processes as simple functions. Or maybe how to define generator for this case, why `Generator<Object, Object, Object>` not working as expected.

**Comment by samwgoldman** [comment]
If I understand the API of co, this seems like the correct way to annotate the function:

```
declare function co<T>(gen: () => Generator<Promise<any>,T,any>): Promise<T>;
```

That is, `co` takes a generator function which yields promises and returns a value of some type `T`, then itself returns a promise of type `T`.

Does that help?

**Comment by darky** [comment]
I can't access to `co` explicity, because architecture of project so arranged.
I work with clear generators, that works as coroutine.

**Comment by darky** [comment]
@samwgoldman, your case not working, bacause https://github.com/facebook/flow/issues/2080#issuecomment-246986993

**Comment by darky** [comment]
I create a fork https://github.com/darky/flow/tree/v0.32, where generators force using as plain function.
Seems stable, bacause fail tests only "Generators" and "Yield"
For those who use coroutines this can help.
