### ISSUE TITLE
Native String#match declaration incorrect

### ISSUE THREAD

**Issue by milesj** [facebook/flow#2450]
The declaration here is incorrect: https://github.com/facebook/flow/blob/3a65d833a6a9b6ca02d006b1f41b2cc2030c7613/lib/core.js#L250

According to MDN, `match` returns an array of strings as well as an `index` and `input` property.

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match

**Comment by alecperkins** [comment]
I just ran into this issue. It causes flow to fail at usage of the `match_instance.index` property:

```
return `${ source.substring(0, ext_match.index) }.css`;
                                         ^^^^^ property `index`. Property not found in
return `${ source.substring(0, ext_match.index) }.css`;
                               ^^^^^^^^^^^^^^^ Array
```

**Comment by miklass** [comment]
Any progress? I've had to do some wacky "any" workarounds and the whole thing felt like a big hack.

**Comment by milesj** [comment]
@miklass I was actually looking into this this week. However, it seems they don't review PRs often (I have another waiting).

**Comment by rstuven** [comment]
In the meantime, I suggest you add the following to .flowconfig
```ini
[options]
suppress_comment=.*\\$FlowIssue
```

And then, just before the problematic line, add a comment like this:
```js
const rxa = ''.match(/./);
if (rxa) {
  // $FlowIssue: https://github.com/facebook/flow/issues/2450
  console.log(rxa.index);
}
```

**Comment by milesj** [comment]
PR: https://github.com/facebook/flow/pull/3359

**Comment by michaelhogg** [comment]
Since PR #3359 (9611080) was reverted in commit 3107fb3, I think this issue needs to be reopened.

Also see:

* PR #3007 – Fixes String#match and RegExp#exec declarations
* Duplicate issue #3554 – regex String .match flow type wrong

**Comment by kesor** [comment]
@miklass @milesj I have a hack that does not involve sprinkling `any` everywhere, just correcting the signature locally using `flow-typed/node.js`, explained it here - https://stackoverflow.com/questions/48063016/how-to-extend-flow-bin-to-support-new-node-js-methods/48384325
