### ISSUE TITLE
Unclear what the best way to install Flow on Linux is

### ISSUE THREAD

**Issue by bolinfest** [facebook/flow#2451]
https://github.com/facebook/flow mentions `brew`, but not `apt` or `yum` or anything else. By comparison, https://flowtype.org/docs/getting-started.html#_ suggests:

    npm install --save-dev flow-bin

but doesn't acknowledge that that installs Flow. I'm pretty sure that example doesn't do it globally. So two things:

1. What is the best way to install Flow on Ubuntu 16.04?
2. Could you please update the docs to make that explicit? You might also want to clarify that Homebrew is only for OS X.

**Comment by AgentME** [comment]
That command will install flow under the current project's node_modules directory, and make flow be usable from the scripts section in package.json. You could use npm's `-g` flag (instead of `--save-dev`) to install flow globally. (On Linux, you'll probably need to use `sudo` too.)
