### ISSUE TITLE
Maybe Functor `map`

### ISSUE THREAD

**Issue by ccorcos** [facebook/flow#2462]
I'm just [playing around with some category theory](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgD6AUgK4DOGAPAGoB8YAvGAN6phGHb4BcYA5GUr8ANOzAA3AIYxSePjTEBfdNwKESFavSZgAFBIUBKJg02VadVHgAeOOACcMYAMZwAdpTBDnfDT6oQBmZpWQJGBgB5ACMAKzwXDAA6KAc8PAAvPD02Dg01PkEtUXFQuWUjVVx1ADk4DAALAEt3AHNdXM4CgTrGltaSlUxqzl7mtt09EwiiMf7rO0dnN09nOYm-QnXW5inTMBj4xJS0zOzO-OrC7cHK4fwiAFkpLGi8S11zbQYAH1n68atKoPQh4ACOpBk5F0lj0AFsAIx+Z6vd70aYMeEAJmRLzelgxYGicDgMDwUncC3sTlcHi84MhMGhfgZUN0iP2cKxpnE8IRSUuD0YwoEPn4YAAZBKwFyBVwRsLmEVhCYAPziRFJMrhEWy7VgHi8zWCnVKm6S6Wyk1MEX8G5q8QYBxyA3iKBQvDA9RwqQ4GE0BEiGhYuh6KB8AwKBGE4OE+G41G0BF0QmEFH44NWWzU5Z05w+v1+Au6KCcnkcOFytQ2pVisDqjg+MPwrUyORGEyGjjbKZAA) stuff and I can't define `Maybe.map`. I'm confused by the phrase "some incompatible instantiation of" because I'm explicitly using the inferred types:

```js
type _map = <V1,V2>(f: (v: V1) => V2) => (m: _Maybe<V1>) => _Maybe<V2>
export const map : _map = f => m =>
  m.__type === 'Just' ?
  Just(f(m.value)) :
  Nothing()
```

While I'm at it, do you know of any examples of algebraic data types like Maybe and Either?

**Comment by gcanti** [comment]
[flow-static-land: implementation of common algebraic types in JavaScript + Flow](https://github.com/gcanti/flow-static-land)

**Comment by ccorcos** [comment]
Whoa @gcanti those are some epic posts. Thanks for sharing your knowledge! I read the paper, had no idea what was going on, then read your post on Higher Kinded Types, and it all make complete sense. Really cool. THANK YOU!
