### ISSUE TITLE
Test for subtyping

### ISSUE THREAD

**Issue by gcanti** [facebook/flow#2466]
I'm curious to know if this a quick and reliable way to test if a type `A` is a subtype of a type `B`, with the possible exceptions of `any` and `mixed` (the test leverages the contravariant part of a function).

**Test**

``` js
type A = ...;
type B = ...;

declare function getB(): B;
declare function f(a: A): void;
declare function getA(): A;
declare function g(b: B): void;

f(getB()) // no errors implies B <= A
g(getA()) // no errors implies A <= B
```

**Partial order**

More generally, is subtyping a partial order on types for flow?
- _reflexivity_ `A <= A` for all `A`
- _antisymmetry_ if `A <= B` and `B <= A` then `A ~ B`
- _transitivity_ if `A <= B` and `B <= C` then `A <= C`

**Comment by asolove** [comment]
Flow now has `$Subtype` and `$Supertype` to accomplish this. For example, the following does not have any errors:

```js
type A = {a: number};
type B = {a: number, b: string};

declare function getB(): B;
declare function f(a: $Subtype<A>): void;
declare function getA(): A;
declare function g(b: $Supertype<B>): void;

f(getB()) // no errors implies B <= A
g(getA()) // no errors implies A <= B
```

I think that solves the code request.

As to the typing properties, I _believe_ all three of those are true, with possible exceptions around "weird" types like `any` or `empty`.
