### ISSUE TITLE
"Required module not found" when many files

### ISSUE THREAD

**Issue by asci** [facebook/flow#2467]
I have a lot of files in a project and it looks like flow can't handle it.
I tried to add file's directory to `INCLUDE` section of config -> no result.
What can I try else?

**Comment by asci** [comment]
Some example:
```
app/assets/js/components/_helpers/apiCalls.js:3
  3: import ApiErrorsActions from '../../actions/apiErrors.actions.es6';
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ../../actions/apiErrors.actions.es6. Required module not found

```

That file is definitely there and `js-hyperclick` can find it

**Comment by asci** [comment]
and by many I mean more than 110K files (including `node_modules`)

**Comment by mroch** [comment]
by default flow only looks at .js and .json files. for it to see .es6 files, use the `module.file_ext` flowconfig option (https://flowtype.org/docs/advanced-configuration.html):

```
[options]
module.file_ext=.js
module.file_ext=.json
module.file_ext=.es6
```
