### ISSUE TITLE
Import exported flow modules by module name not relative path

### ISSUE THREAD

**Issue by dtothefp** [facebook/flow#2469]
I noticed in the React GH repo they were `import`ing their flow types by module name rather than a relative path. 

https://github.com/facebook/react/blob/master/src/renderers/shared/stack/event/ReactSyntheticEventType.js#L17

Looking through the build it wasn't apparent how this was possible. Is this some magic within flow configuration or something else in the build process?

**Comment by vkurchatkin** [comment]
I think `module.system=haste` does the trick
