### ISSUE TITLE
module.name_mapper.extension config overrides module.name_mapper configs

### ISSUE THREAD

**Issue by acusti** [facebook/flow#2476]
As far as I can tell, the priority of `module.name_mapper` config options is determined by the order of the options. If a module name matches an earlier option, that options mapping is used. However, this is not the case if a later `name_mapper` option uses the `name_mapper.extension` shorthand.

A working `.flowconfig`:

``` ocaml
module.name_mapper='^!raw!.*$' -> '<PROJECT_ROOT>/flow/stub/url-loader.js'
module.name_mapper='.*\.css$' -> '<PROJECT_ROOT>/flow/stub/css-loader.js'
```

A “broken” `.flowconfig` (the latter css entry overrides the initial name_mapper):

``` ocaml
module.name_mapper='^!raw!.*$' -> '<PROJECT_ROOT>/flow/stub/url-loader.js'
module.name_mapper.extension='css' -> '<PROJECT_ROOT>/flow/stub/css-loader.js'
```

Based on the [note in the docs](https://flowtype.org/docs/advanced-configuration.html#options):

> _Note that this is just shorthand for `module.name_mapper='^\(.*\)\.EXTENSION$' -> 'TEMPLATE')`_

I’m assuming that this isn’t desired behavior. If it is, however, I can add a note explaining that to the `options` section of the advanced configuration docs.

**Comment by mroch** [comment]
that's surprising. does it prevent the first `module.name_mapper` from matching *anything* (like, `!raw!foo.jpg` gets mapped to `css-loader.js`), or does it take precedence on module names that match both, like `!raw!foo.css`?

[the code](https://github.com/facebook/flow/blob/6e0a161693f7d714da30c01ad5087f88244383e8/src/common/flowConfig.ml#L524) really does just convert it into a `module.name_mapper` and adds it to the existing list.

there's a slight difference between your working config and what `.extension` does. does this make any difference?

```
module.name_mapper='^!raw!.*$' -> '<PROJECT_ROOT>/flow/stub/url-loader.js'
module.name_mapper='^\(.*\)\.css$' -> '<PROJECT_ROOT>/flow/stub/css-loader.js'
```

**Comment by calebmer** [comment]
Closing since this issue hasn’t seen a lot of activity. Sorry about that 😣

We are happy to accept PRs fixing this!
