### ISSUE TITLE
adding media-related types

### ISSUE THREAD

**Issue by stryju** [facebook/flow#2480]
hey!

I want to add some media-related types (media constraints, media device info, media device kind etc.)

should I add them to `bom.js` or is there (should there be?) a better place for that?

**Comment by thejameskyle** [comment]
Probably, but I'm not sure what media-related types you're talking about

**Comment by stryju** [comment]
- `MediaStreamConstraints`
- `MediaDeviceInfo`
- `MediaDeviceKind`

to name a few - was just thinking if something like `media.js` wouldn't be a better place for this

WDYT?

**Comment by thejameskyle** [comment]
Nah, I would put this in `bom.js`

**Comment by calebmer** [comment]
Closing since it appears like this issue has been resolved 👍
