### ISSUE TITLE
Class literal properties

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#2482]
``` js
class Id<T> {
  _x: T;
  constructor(x: T) {
    this._x = x
  }
  static 'fantasy-land/of'<T>(x: T): Id<T> {
    return new Id(x)
  }
}
```

Flow yields:

```
11:   static 'fantasy-land/of'<T>(x: T): Id<T> {
      ^ literal properties not yet supported
```

From error message I understand that Flow team aware about this issue, but I just wanted to give you another use-case (we need this for [Fantasy Land](https://github.com/fantasyland/fantasy-land#prefixed-method-names)) and open an issue to track progress if that's ok.

This should also be added to the list in #560 .

**Comment by Kovensky** [comment]
Sure you don't need the computed property square brackets? `static ['fantasy-land/of'] () {}`

**Comment by rpominov** [comment]
@Kovensky I think it's valid ES with or without square brackets in this case. At least it works in babel and latest Chrome without them.

**Comment by calebmer** [comment]
This is a known issue. We currently don’t support it, but we should be adding support in the future 👍
