### ISSUE TITLE
Built-in `ObjectMap` type

### ISSUE THREAD

**Issue by dchambers** [facebook/flow#2483]
I think it would be helpful to have a built-in `ObjectMap` type that offered an equivalent to the `Map` type (for ES6 maps) for those using objects as maps. At present I just keep defining this myself as follows:

``` es6
type ObjectMap<T> = {[key: string]: T};
```

**Comment by cloudkite** [comment]
@dchambers if you really want this you could always add it as a global type definition to your projects flow defs folder

**Comment by dchambers** [comment]
Hi @cloudkite, this sounds like a really nice idea in principle, but the docs don't mention that it's possible to declare types in this way, and I couldn't actually get it to work. I tried adding this:

~~~es6
declare type ObjectMap<T> = {[key: string]: T};
~~~

and alternatively this:

~~~es6
type ObjectMap<T> = {[key: string]: T};
declare type ObjectMap = ObjectMap;
~~~

to an `interfaces/global.js` file that I configured (within `.flowconfig`) to be used like so:

~~~
[libs]
interfaces/
~~~

but with no luck. Any ideas?

**Comment by cloudkite** [comment]
@dchambers if the type is defined at the top level it go's into global scope. you don't need declare

ie this by itself should work
```
type ObjectMap<T> = { [key: string]: T }
```

see https://github.com/facebook/flow/blob/master/lib/react.js#L370
for an example of this in practice

**Comment by dchambers** [comment]
Works a treat! Thanks @cloudkite :+1:

**Comment by calebmer** [comment]
Closing since you are free to create this type for your own projects 😊
