### ISSUE TITLE
Problem with Proxy objects

### ISSUE THREAD

**Issue by fgarcia** [facebook/flow#2485]
I am trying to add Flow types to this code example, where a Proxy sets a default for the first argument of a function

``` javascript
let panda = {
  fn: function(n: number, s: string) {
    console.log(n, s);
  }
}

let handler = {
  get: function(target,name) {
    return (s) => target[name](1, s)
  }
}

let g = new Proxy(panda, handler)
g.fn('k')

```

Here Flow complains forcing me to type invalid code. 

```
// WRONG, but it is what Flow wants
// g.fn(2, 'k')
```

How can I get Flow to properly identify my Proxy?

This is the error I get with the good version:

```
 19: g.fn('k')
     ^^^^^^^^^ call of method `fn`
 19: g.fn('k')
          ^^^ string. This type is incompatible with
  4:   fn: function(n: number, s: string) {
                       ^^^^^^ number

```

**Comment by calebmer** [comment]
Closing since we currently planning on adding support for proxies.

**Comment by fgarcia** [comment]
@calebmer Which issue should I follow to track this feature and find out when it will be released?

**Comment by gajus** [comment]
Can this be re-opened if these is no other issue to track?

**Comment by bugs181** [comment]
Still no progress after almost 4 years? Just ran into this issue. Unless I'm doing something blatantly wrong? New to type systems and it hasn't been as easy as the whitepapers make it seem.

Code example:
```
constructor(): Proxy<FlowInterface> {}
```

Error:
```
Cannot return `new Proxy(...)` because  `FlowInterface` [1] is incompatible with  `Proxy` [2].Flow(incompatible-return)
```
