### ISSUE TITLE
Unintuitive behavior for arrays of objects

### ISSUE THREAD

**Issue by pnachum** [facebook/flow#2487]
```
type Foo = { foo: number };
type FooBar = { foo: number, bar: number };

function doSomething(obj: Foo) {
}
function doSomethingElse(objs: Foo[]) {
}

const typedFooBar: FooBar = { foo: 1, bar: 2 };
const typedFooBars: FooBar[] = [
  { foo: 1, bar: 2 },
  { foo: 3, bar: 4 },
];

const untypedFooBar = { foo: 1, bar: 2 };
const untypedFooBars = [
  { foo: 1, bar: 2 },
  { foo: 3, bar: 4 }, 
];

// These work
doSomething({ foo: 1, bar: 2 });
doSomething(untypedFooBar);
doSomething(typedFooBar);
doSomethingElse([
  { foo: 1, bar: 2 },
  { foo: 3, bar: 4 },
]);
doSomethingElse(untypedFooBars);

// This doesn't work
doSomethingElse(typedFooBars)
```
or in the online editor:
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN5hQkBcYAdgK4C2ARngE5gC+A3JlwFicAEIBDHhWq04DFh24AaMOykK2nHgPRRmjAMYYAlnEZgAJnADKcVngwALE4wDmACjjsAVg1EAlFSovKj6RqbmVrb2ji7uAKIwAM54Xr7J-iQA2gC6QZQh6IbmyRhg2PiWopJcWeJS5FQ09GAAjKrqdWAATHyCJYxlFcLVJLWZRONSeU3ZqGDNcgwdahq9fMoLS60AzJ3rACybqLmCqIPDBpV4Yw3SO-LtB919upfl16M1Uslz27JWqsugw3ltFoCnvs1t1jrxVKdzsBgGAACpOPCpMAIOBcADWqGsdgczlcnkhKxeoL4AUERNipPcHi+VR+XFphJiJPinhud1qHPp3LJSVSHnmEJaT2B6zBAKlDGhILAcK2+TpXLiIpSaRZtzZyQ5qGRaJcf2smMYAHJyjj8ZziVrEjqPHyDQEgA

**Comment by gcanti** [comment]
It's by design, arrays are invariant. Otherwise it would be unsafe, example:

```js
type Foo = { foo: number };
type FooBar = { foo: number, bar: number };

function doSomethingElse(objs: Foo[]) {
  objs.push({ foo: 2 }) // <= you might modify the input
}

const typedFooBars: FooBar[] = []

doSomethingElse(typedFooBars)

console.log(typedFooBars) // => { foo: 2 } wrong, is not a FooBar
```

As explained in https://github.com/facebook/flow/issues/2333 you can fix `doSomethingElse` using [Bounded Polymorphism](https://flowtype.org/blog/2015/03/12/Bounded-Polymorphism.html)

```js
function doSomethingElse<T: Foo>(objs: Array<T>) {
  // here you can't modify the input though
}
```

**Comment by philpee2** [comment]
Isn't it equally unsafe to allow it on objects though, since they can also be modified? 
ie 
```
function doSomething(obj: Foo) {
  delete obj.foo;
}
doSomething(typedFooBar);
console.log(typedFooBar) // => { bar: 2 } 
```

**Comment by gcanti** [comment]
Yes https://github.com/facebook/flow/issues/2207
