### ISSUE TITLE
Correct annotation / type for functions (callbacks)

### ISSUE THREAD

**Issue by bennoleslie** [facebook/flow#249]
Is there a mechanism for specifying the type of a function parameter? For example in this completely contrived example, I'd like to say the the type of the `cb` argument is not `any`, but rather *a function that takes a number and doesn't return any value*.

    function do_something_async(cb : any) {
            cb(37);
    }

**Comment by gabelevi** [comment]
You mean something like

```JavaScript
function do_something_async(cb : (x: number) => void) {
        cb(37);
}
```

Docs are [here](http://flowtype.org/docs/functions.html#function-based-type-annotations), but probably could be improved

**Comment by bennoleslie** [comment]
My bad. Didn't read carefully enough. Thanks for the explicit pointer.

**Comment by thealjey** [comment]
@gabelevi 
Well, it's all very nice in theory, however, it does not work with Flow v0.12.0
```
function type
This type is incompatible with
/private/var/folders/_1/90xwg0pd17j8qfn91lmj7t6h0000gn/T/flow/flowlib_381eedd4/lib/core.js:57:1,63:1: Function
```
