### ISSUE TITLE
Style of class static declaration affects typechecking

### ISSUE THREAD

**Issue by STRML** [facebook/flow#2490]
Apparently there is a difference between a class static property initializer and a function declaration, although it seems there shouldn't be.

[FlowType Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAMTjjAG9UwxyAXfNgSx1bgFssbABZcAdgHMAym0LiJACnaEAXK1nyAlGuXyA3M3WcefQSPkA5AK781CsTbUP+AIyyFNYALwA+MM7dCAwBfdFo4ADpyASFRSRk5SW8wKCsxHG44MSVZHQ1JTyYWYjYrQjF1INRQ1HComPNJa35k1PTM7OcnG0DCwxKyiucQoA)

``` jsx
declare class Foo {
  static somethingString(str: string): string;
  static somethingNum: (num: number) => number;
}

// Errors: 'somethingString' not found in properties of Foo
Foo.somethingString = function(str: string) {
  return str;
}

Foo.somethingNum = function(num: number) {
  return num;
}
```

Is this intended?

**Comment by calebmer** [comment]
Methods are readonly by default, so yes this is intended 😊

**Comment by STRML** [comment]
In that case, shouldn't there be a different error than `not found in properties of Foo`?

**Comment by calebmer** [comment]
There is a better error message:

```
7: Foo.somethingString = function(str: string) {
       ^ property `somethingString`. Covariant property `somethingString` incompatible with contravariant use in
7: Foo.somethingString = function(str: string) {
   ^ assignment of property `somethingString`
```

The covariant/contravariant language is pretty confusing but it accurately expresses what is happening here. I’ll be working on making error messages more readable soon.

https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwGIHtPwN4Ch55kAXKEgSzGMwFsQSALCgOwHMBlEmVtgClIwAXMW68AlCMG8A3IVHkqNek14A5AK60RfFlpF7aAIxAxx8ALwA+eIZMw5AX3z4A9K-gBRGDEwxkIgDkyHQMzOxcPOyBtpgk8ABmmBoswPCs8AAOvpmmlCBomAkY2PhYmAB0ISrhnGLslokpYJSYLALcUvVs5gREcCQaMCyiDvjOZdhVoarsmrSNCc2t7YYGWva98gNDI4ZO+EA
