### ISSUE TITLE
Functions in type unions are possibly too permissive.

### ISSUE THREAD

**Issue by damncabbage** [facebook/flow#2491]
``` javascript
/* @flow */

const anyToBool      = (x) => false;
const stringToString = (x) => x.toLowerCase();

type SomeUnion = 1 | 2 | anyToBool;
// ^--- What does putting a function in this union mean?
// It doesn't seem to be checking any specifics of the function (reference,
// args+return type, etc); it's just letting any function through
// in the console.log() below.

function what(x: SomeUnion): boolean {
  if (typeof x == "function") {
    return x(1234);
  } else {
    return true;
  }
}

console.log(what(stringToString));
// ^--- Explodes at run-time because 1234 doesn't have toLowerCase.
```

([Code example with 0.30.0 in an online REPL here.](https://tryflow.org/?code=LyogQGZsb3cgKi8KCmNvbnN0IGFueVRvQm9vbCAgICAgID0gKHgpID0+IGZhbHNlOwpjb25zdCBzdHJpbmdUb1N0cmluZyA9ICh4KSA9PiB4LnRvTG93ZXJDYXNlKCk7Cgp0eXBlIFNvbWVVbmlvbiA9IDEgfCAyIHwgYW55VG9Cb29sOwovLyBeLS0tIFdoYXQgZG9lcyBwdXR0aW5nIGEgZnVuY3Rpb24gaW4gdGhpcyB1bmlvbiBtZWFuPwovLyBJdCBkb2Vzbid0IHNlZW0gdG8gYmUgY2hlY2tpbmcgYW55IHNwZWNpZmljcyBvZiB0aGUgZnVuY3Rpb24gKHJlZmVyZW5jZSwKLy8gYXJncytyZXR1cm4gdHlwZSwgZXRjKTsgaXQncyBqdXN0IGxldHRpbmcgYW55IGZ1bmN0aW9uIHRocm91Z2gKLy8gaW4gdGhlIGNvbnNvbGUubG9nKCkgYmVsb3cuCgpmdW5jdGlvbiB3aGF0KHg6IFNvbWVVbmlvbik6IGJvb2xlYW4gewogIGlmICh0eXBlb2YgeCA9PSAiZnVuY3Rpb24iKSB7CiAgICByZXR1cm4geCgxMjM0KTsKICB9IGVsc2UgewogICAgcmV0dXJuIHRydWU7CiAgfQp9Cgpjb25zb2xlLmxvZyh3aGF0KHN0cmluZ1RvU3RyaW5nKSk7Ci8vIF4tLS0gRXhwbG9kZXMgYXQgcnVuLXRpbWUgYmVjYXVzZSAxMjM0IGRvZXNuJ3QgaGF2ZSB0b0xvd2VyQ2FzZS4=))

Further confusing behaviour is written down here as well: https://twitter.com/jusrin00/status/778125972533108740 (I haven't dug into this yet.)

I'm not entirely sure what sort of equality is intended if you include a reference to a function in a union, eg.`function foo() { ... }; type SomeUnion = 1 | 2 | foo;` – is it intended for checking whether a value is:
- Exactly that function (reference equality), or
- Something that matches that type signature (value/structural equality), or
- Something that is any function at all (prototype reference equality?), or
- Something that is an Object, or
- ... something else?

**Comment by damncabbage** [comment]
(CC @thejameskyle, as Web Twitter seems to be horribly broken and I can't reply to your tweet with a link to this issue. :sweat_drops:)

**Comment by gcanti** [comment]
`anyToBool` is a value not a type, shouldn't flow complain?

```js
type SomeUnion = 1 | 2 | typeof anyToBool; // <= using typeof you get a flow error
```

**Comment by vkurchatkin** [comment]
I suspect it is treated as class in this case

**Comment by damncabbage** [comment]
@vkurchatkin: I'm not sure.

Consider:
```javascript
/* @flow */
const Car = (n: number) => ({ wheels: 4, mpg: n })
const Bicycle = () => ({ wheels: 2, spokes: 150 })

type Vehicle = Car | Bicycle;

function getSpokes(x: Vehicle): number {
  return x.spokes; // <--- Should complain, given Vehicle isn't specific enough for us to know we can do this.
}

var x = getSpokes(Car(20)); // <--- x is now undefined; 💥 waiting to happen.
```

Versus:
```javascript
/* @flow */

class Car {
    wheels: 4;
    mpg: number;
    constructor(n) { this.mpg = n; }
}
class Bicycle {
    wheels: 2;
    spokes: 150;
}

type Vehicle = Car | Bicycle;

function getSpokes(x: Vehicle): number {
  return x.spokes; // <--- Complains here as appropriate.
}

var x = getSpokes(Car(20));
```

Separately, in case it helps:
```javascript
/* @flow */
const Car = (n: number) => ({ wheels: 4, mpg: n })
const Bicycle = () => ({ wheels: 2, spokes: 150 })

type Vehicle = Car | Bicycle;

var a = Car(50).spokes; // <---- Complains here as appropriate.
```

**Comment by vkurchatkin** [comment]
I mean, this is why you can use function as type (without `typeof`). It doesn't work correctly, though

**Comment by vkurchatkin** [comment]
It seems that flow allows to use any properties on instances of "sugar-free" classes. So if you accidentally use function as type, you are going to have a bad time

**Comment by damncabbage** [comment]
But my last example seems to point to something different. It's using two "sugar-free classes", but Flow is appropriately detecting the bug. It's only when it's passed through a function boundary (first two examples) does it seem to forget itself.

**Comment by vkurchatkin** [comment]
In the last example you don't actually use Car as type, so it works as expected

**Comment by damncabbage** [comment]
Indeed. `var a = (Car(50): Vehicle).spokes;` incorrectly passes the checker just fine.

**Comment by calebmer** [comment]
More annotations are always better. This works:

```js
/* @flow */

const anyToBool: any => boolean     = (x) => false;
const stringToString: any => string = (x) => x.toLowerCase();

type SomeUnion = 1 | 2 | typeof anyToBool;
// ^--- What does putting a function in this union mean?
// It doesn't seem to be checking any specifics of the function (reference,
// args+return type, etc); it's just letting any function through
// in the console.log() below.

function what(x: SomeUnion): boolean {
  if (typeof x == "function") {
    return x(1234);
  } else {
    return true;
  }
}

console.log(what(stringToString));
// ^--- Explodes at run-time because 1234 doesn't have toLowerCase.
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAENsBPAFTgCE44YAuYssAXgD4wAjWmAUxLCDBLMAAoAHgEpWHKERi5eAbkw4CYAgCcAltgDmlAMr4d+xiVIyNJ3XtZipV8QDp8cADKJemgMJFFopIqqPikAA68YIZwALa8AKrY2jj2AIxgAD5gAEyZYKERcFBMFNQ8KsDAYAB6ALT1YADqABZEhAAmcLy4YGEArvj4tsRgUH3YGEMpuvnN2j3jydhgcSQA-KiVYACSHV242ADkhIq8MflwXJEYzbwYANbDFhoRGNpQ2hg9RbORYxNTZaiTS8KDeXgTXgAGk2VSImj0uAA1CD8H1NMsCtCwLx8BggmBtPhDj0AFZ9dR8QZPZj-SZLWaaOB9PTNWGEzG3MBYPB0XjOeB6QJXeAIZzoOmAsAIVr4CSMaJxRJLSSMbh8gQAb1QgneYixP3ErBEACJJUsTdJtUIwKj0ctxKJUtkAMwAFiCOrAAF8cQpItahHaMflNH1lF7vago6peXwBXAhTK2qItLYjDZ9JJPVs6g0AKLiMLwdrdYiEMPYWpDOJXDBECmRZ3usCdbpHQitABukTcngQ3j8inFQA
