### ISSUE TITLE
How to fix errors for function binding

### ISSUE THREAD

**Issue by JelteF** [facebook/flow#2492]
With the following code I get an error that I would like to fix:

``` javascript
/* @flow weak */

class MyClass {
    thisUsesThis() {
        console.log(this);
    }

    constructor() {
        this.thisUsesThis = this.thisUsesThis.bind(this);
    }
}
```

This is the error:

``` bash
node_modules/.bin/flow check                                                                                                                                                                    4722ms  di 20 sep 2016 17:07:48 CEST
static/js/modules/stream-react/test.js:9
  9:         this.thisUsesThis = this.thisUsesThis.bind(this);
             ^^^^^^^^^^^^^^^^^ assignment of property `thisUsesThis`
  9:         this.thisUsesThis = this.thisUsesThis.bind(this);
                  ^^^^^^^^^^^^ property `thisUsesThis`. Property not found in
  3: class MyClass {
           ^^^^^^^ MyClass


Found 1 error
```

I understand that it is complaining because I'm assigning to a property that is actually a method. How do I change my code to make this error disappear?

**Comment by vkurchatkin** [comment]
You have to declare it as property like this:

```js
class MyClass {
    thisUsesThis: () => void;

    thisUsesThis() {
    }

    constructor() {
        this.thisUsesThis = this.thisUsesThis.bind(this);
    }
}
```

**Comment by JelteF** [comment]
Thanks that indeed works. Is it correct that this should cause errors in weak mode?

**Comment by calebmer** [comment]
Yep @vkurchatkin has the answer 😊

Methods are readonly by default.

**Comment by locomotif** [comment]
Hi team - hope you are all well.  I've been declaring my methods as mentioned above but noticed that I am not getting errors.  Not sure if I should be getting errors.  Please see the contrived example at [example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecAKArlEgMITgQB2SV8AvnAGZQVwDkJ6M7AULzACeYJAVZgAznAC8uegOGiAogA8U4ADajZOXnDgwkEmAC44xqMCoBzXvLQaUEqQGUKZR87hIVhqgBMpIhJySho6AB58cQkAPlw9OESACxQArQB5KlINYDQAazMAChQoazNVdTAtAEoZeIA3CGB-RMS0agtCDGgisBizaIhJOt19fQlCESg+mJrE-Rhk4AkAOlT0pCycvPyZA2W1jf9M7NyC1YAjK38ipZX5-Xl9FLSTrbPdkrLRxIBIEgwYhUOClaxwADUcAAzIl5PIgA)

The above doesn't report an error. Should it?

or do I also need to at types to the function:

```
handleOnClick(arg: Example): void {
  return arg + 3
}
```

Seems a bit redundant, but curious if that is the best practice?

Thanks!
