### ISSUE TITLE
Type checking in react parameters

### ISSUE THREAD

**Issue by bennoleslie** [facebook/flow#250]
Is the type checking meant to see inside expression passed as react parameters?

E.g.:

    var React = require('./react.js');

    var Bar = React.createClass({});

    function foo(x: number) {
    }

    foo("asdf");

    var x = {select: foo.bind("asdf")};

    var bar = <Bar x={foo.bind("asdf")} />;

This code is able to pick up the errors in `foo.bind()` the first two times, but doesn't seem able to see the error when embedded inside the JSX syntax.

**Comment by gabelevi** [comment]
It works for me. From your example it looks like you actually mean `foo.bind(null, "asdf")`. When I do that it seems to work.

```Bash
$ echo "function foo(x: number) {} foo.bind(null, 'hi');" | flow check-contents

-:1:43,46: string
This type is incompatible with
  -:1:17,22: number

Found 1 error
$ echo "function foo(x: number) {} <span x={foo.bind(null, 'hi')} />;" | flow check-contents

-:1:52,55: string
This type is incompatible with
  -:1:17,22: number

Found 1 error
```

Can you confirm that this fixes your problem? If not let me know and I'll look into it further :)

**Comment by jeffmo** [comment]
Going to close this out for now -- but feel free to re-open this issue if you're still having problems!

**Comment by bennoleslie** [comment]
Yeah, this was definitely my bad. Works for me.
