### ISSUE TITLE
Constant folding not always performed 

### ISSUE THREAD

**Issue by jianpingw** [facebook/flow#2500]
The following code has no errors:

```
/* @flow */

let foo : ?string = null;

if (foo == null) {
    foo = "ok"
}
console.log(foo.length)

```

It looks like Flow performs constant folding so that it knows the assignment statement will be executed.

However, Flow issues errors for the the following code:

```
/* @flow */

let foo : ?string = null;

if (true) { // or if ( 2 > 1)
    foo = "ok"
}
console.log(foo.length)

```

The error message is:

```
8: console.log(foo.length)
                     ^^^^^^ property `length`. Property cannot be accessed on possibly null value
```

This is confusing, why in this case Flow does not evaluate the simple expression?

**Comment by calebmer** [comment]
We currently aren’t planning on evaluating booleans that may always be truthy within `if`s.
