### ISSUE TITLE
Flow doesn't refine type when using a reference of `Array.isArray`

### ISSUE THREAD

**Issue by HeavenVolkoff** [facebook/flow#2509]
Example:

```javascript
let isArray = Array.isArray

function f (arr: Array<mixed>): Array<mixed> {
  let subArr:mixed = []
  
  if (isArray(subArr)) {
    return subArr
  }
  
  return []
}
```

Flow result:
```
7:     return subArr
              ^ mixed. This type is incompatible with the expected return type of
3: function f (arr: Array<mixed>): Array<mixed> {
                                   ^ array type
```

However, it refines just fine in the following code:
```javascript
function f (arr: Array<mixed>): Array<mixed> {
  let subArr:mixed = []
  
  if (Array.isArray(subArr)) {
    return subArr
  }
  
  return []
}
```

**Comment by AgentME** [comment]
`Array.isArray` is handled specially right now. If/when https://github.com/facebook/flow/issues/34 is implemented, then the isArray method could be annotated as a normal type-checking function and this would be handled correctly.

**Comment by HeavenVolkoff** [comment]
Ok, I will close this issue and follow development on #34, thanks.

**Comment by vkurchatkin** [comment]
@HeavenVolkoff can you reopen this? Predicates are already merged, but this is still a problem. Another example of incorrect behaviour:

```js
const Array = {
  isArray: () => true
};

function test(x: null | Array<mixed>) {
  if (Array.isArray(x)) {
     x.forEach(() => {}); 
  }
}
```

**Comment by moll** [comment]
This problem still persists as of v0.107.0.
