### ISSUE TITLE
Spread in tuple?

### ISSUE THREAD

**Issue by mirek** [facebook/flow#2522]
Would it be possible to support spread in tuple type definition (effectively making "tuple" variable length array):
```
let tuple: [string, ...number] = ["foo", 0, 1, 2, 3];
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXM2CuADlgFxgDaAztgE4CWAdgOYA0YD+AtgEaY0C6YALwUARFDhxRbAIz8A3KgLFMAOkL5KACwAUAJgCU8sMGDs4YPjTg0A-EqJZ1m3aIDMooybMMLVm-aopmAAkrgIcPgwACZgvOx0AMaYeBbxAIbcWKlglOkAniRBZli4ytlkVLSMrGCq9Rw8fIIi5OKSooLpDLEZWSnYFhra7Fy8NJRgcAww+aroQA

**Comment by thejameskyle** [comment]
Duplicate of #2443
