### ISSUE TITLE
Support for Syntax Do Expression

### ISSUE THREAD

**Issue by tonyxiao** [facebook/flow#2523]
Given the following snippet

http://babeljs.io/docs/plugins/transform-do-expressions/

```javascript
const Component = props =>
  <div className='myComponent'>
    {do {
      if(color === 'blue') { <BlueComponent/>; }
      if(color === 'red') { <RedComponent/>; }
      if(color === 'green') { <GreenComponent/>; }
    }}
  </div>
```

Flow complains that

`Unexpected token do at line... col ...`

Is there a way for to help flow figure out how to support do expressions?

**Comment by gabro** [comment]
@tonyxiao this is being tracked in https://github.com/facebook/flow/issues/560, so I guess this issue can be closed?

**Comment by tonyxiao** [comment]
Sounds great, closing thank you.
