### ISSUE TITLE
Intersection misbehaves when looping over object keys

### ISSUE THREAD

**Issue by dhinus** [facebook/flow#2527]
A simple intersection between two objects is not applied correctly when looping over the object keys (either with `forEach` or plain `for`, same result):

``` js
type A = {
  a: string
};
type B = {
  b: string
};

const i: A & B = {
  a: 'a',
  b: 'b'
};

console.log(i.a); // ok
console.log(i.b); // ok
// console.log(i.c); // fails, as expected

['a', 'b'].forEach(k => {
  console.log(i[k]); // fails on property `b`, why?
});
```

**Comment by gcanti** [comment]
Accessing an object with any statically unknown strings or numbers is unsafe (relevant https://github.com/facebook/flow/issues/2295#issuecomment-241241128), so it's a best practice to annotate the keys, which also happens to be a workaround for this issue

```js
(['a', 'b']: Array<$Keys<typeof i>>).forEach(k => {
  console.log(i[k]) // no error
})
```
