### ISSUE TITLE
separate module assignment yields `Method cannot be called on possibly undefined value`

### ISSUE THREAD

**Issue by ahamid** [facebook/flow#253]
`interfaces/fun.js`

``` javascript
declare module module {
  declare function fun(): any;
}
```

``` javascript
/* @flow */
// No errors
// var m = require('module');

// separate assignment yields
// call of method fun
// Method cannot be called on possibly undefined value
var m;

m = require('module');

function foo() {
  m.fun();
}

(function() {
  m.fun();
})();
```

```
$ flow --version
Flow, a static type checker for JavaScript, version 0.1.6
$ flow check .
test.js:13:3,9: call of method fun
Method cannot be called on possibly undefined value
  test.js:8:5,5: undefined

test.js:17:3,9: call of method fun
Method cannot be called on possibly undefined value
  test.js:8:5,5: undefined

Found 2 errors
```

**Comment by gabelevi** [comment]
Yeah this is a bug in Flow, or at least a bit of intended naivety that we plan to fix eventually. In your example, it involves how we infer the type of `m`. When you do

```JavaScript
var x = "hello";
```
Flow infers that the only type that flows into the variable `x` is `string. However when you do
```JavaScript
var x;
x = "hello";
```
Flow says that both `undefined` and `string` flow into `x`. 

While the later interpretation is technically correct and `x` does hold the value `undefined` for a period of time, it is inconvenient. We should add logic that says "If `x` is not used between `var x` and `x = "hello"` then ignore the fact that `x` held the value `undefined`"

**Comment by ahamid** [comment]
Thanks @gabelevi I suspected that.  I am interested to see if I can get flow working with coffee script generated code (via `flotate`), and this is the style it generates.

**Comment by Brianzchen** [comment]
This now works as expected
