### ISSUE TITLE
DOM libdef: querySelector: ?HTMLElement 

### ISSUE THREAD

**Issue by bassettsj** [facebook/flow#2530]
As the core querySelector definition stands: https://github.com/facebook/flow/blob/master/lib/dom.js#L561 

In the DOM lib def is defined as always returning an `HTMLElement`.

> "Returns null if no matches are found; otherwise, it returns the first matching element."
> -\- [Document.querySelector()](https://developer.mozilla.org/en-US/docs/Web/API/Document/querySelector)

**Comment by calebmer** [comment]
Closing since it looks like this has been resolved 👍
