### ISSUE TITLE
`export type {Foo}` parses but doesn't work properly

### ISSUE THREAD

**Issue by mroch** [facebook/flow#2533]
```
var Foo = 42;
export type {Foo};
```

this should be an error (value used as type).

or it should be a parse error until it works properly.

**Comment by gajus** [comment]
This is still producing no error.

https://flowtype.org/try/#0G4QwTgBAYg9jEF4IBYBMBuAUAUwB4AcYwAXCYgT32wgG9YYBfdIA

**Comment by SamChou19815** [comment]
This is now erroring.
