### ISSUE TITLE
Incorrectly passing analysis

### ISSUE THREAD

**Issue by syrnick** [facebook/flow#2534]
```
// @flow

declare function SomeFn(): void;

type A = {
    type: 'simple';
    foo: number;
    requiredName: string;
};

type B = {
    type: 'error';
    bar: number;
    errorHandler: SomeFn;
};

type AorB = A | B;

class MyClass {
    _states: {[key: string]: AorB};
    constructor() {
        this._states = {};
    }
    addB(n: string): void {
        this._states[n] = {
            type: 'error',
            foo: 1,
        };
    }
}
```

**Comment by syrnick** [comment]
I'd expect this to throw some sort of an error instead of accepting arbitrary objects for assignment.

**Comment by gcanti** [comment]
`SomeFn` is a value, you should use `typeof`

```js
type B = {
  type: 'error',
  bar: number,
  errorHandler: typeof SomeFn
};
```

**Comment by syrnick** [comment]
thanks! that make sense for the "correct type annotation". 

I'm not sure it's a valid behavior for the type checking to pass on this file with this user error in type annotation. I would expect it to fail with something like "type AorB is invalid" or "can't infer type" in `this._states[n] = { ` assignment.

**Comment by gcanti** [comment]
Relevant https://github.com/facebook/flow/issues/2491
