### ISSUE TITLE
Using Flow with react-css-modules

### ISSUE THREAD

**Issue by sgronblo** [facebook/flow#2536]
Been spending some time today trying to hack together a declaration that would allow me to decorate my React.Components with react-css-modules while also having them checked when rendering through JSX.

This is how far I got:

```
// in .flowconfig
[libs]

decls/.js
```

```js
// in decls/react-css-modules.js
declare type CssOptions = {
  allowMultiple?: bool,
  errorWhenNotFound: bool,
}

declare module 'react-css-modules' {
  declare function exports<Config>(reactClass: ReactClass<Config>, styles: any, cssOptions?: CssOptions): ReactClass<Config>
}
```

```js
// in MyComponent.js, simplified example
import CssModules from 'react-css-modules'
import styles from './MyComponent.scss'

type MyComponentProps = {
  foo: string
}

class MyComponent extends React.Component {
  props: MyComponentProps
  //code here
}

export default CssModules(MyComponent, styles, {})
```

```js
// another component
import MyComponent from 'mycomponent'

export default SomeOtherComponent extends React.component {
  render() {
    return <MyComponent /> // missing the foo property here
  }
}
```

The problem is that Flow doesn't detect that the foo property is missing when the other component is rendering it through JSX. It seems like my setup with the decls etc. is working since changing the type of the react-css-modules import to be `declare function exports<A, B, C>(reactClass: React$Component<A, B, C>, styles: any, cssOptions?: CssOptions): React$Component<A, B, C>` gives me an error in the JSX of the other component that MyComponent is wrong because _Expected React component instead of React$Component_.

Is this a bug in Flow + the React declarations or am I just doing it wrong?

**Comment by AgentME** [comment]
You never used the `MyComponentProps` type anywhere. You should try this:

```js
class MyComponent extends React.Component {
  props: MyComponentProps;
  //code here
}
```

**Comment by sgronblo** [comment]
Oh yeah. I'm sorry. That was just a mistake when I was typing in the issue. I actually do have `props: MyComponentProps` in `MyComponent`.

**Comment by gcanti** [comment]
Do not use `ReactClass`, it throws away type checking https://github.com/facebook/flow/issues/2159

```js
declare module 'react-css-modules' {

  declare type CssOptions = {
    allowMultiple?: boolean,
    errorWhenNotFound?: boolean,
  };

  declare type FunctionComponent<P> = (props: P) => ?React$Element<any>;
  declare type ClassComponent<D, P, S> = Class<React$Component<D, P, S>>;

  declare function exports<D, P, S, C: ClassComponent<D, P, S> | FunctionComponent<P>>(reactClass: C, styles: Object, cssOptions?: CssOptions): C;
}
```

**Comment by sgronblo** [comment]
Thank you very much for pointing out a possible problem and for proposing a solution. Unfortunately Flow still doesn't seem to be able to use the HOC component to check its properties from inside of JSX.

**Comment by gcanti** [comment]
Hers's my test (Flow 0.32)

MyComponent.js

```js
// @flow
import React from 'react'
import CssModules from 'react-css-modules'
import styles from './MyComponent.scss'

type MyComponentProps = {
  foo: string
};

class MyComponent extends React.Component {
  props: MyComponentProps
  //code here
}

export default CssModules(MyComponent, styles, {})
```

index.js

```js
import React from 'react'
import MyComponent from './Mycomponent'

export default class SomeOtherComponent extends React.Component {
  render() {
    return <MyComponent />
  }
}
```

Flow complains with

```
src/index.js:8
  8:     return <MyComponent />
                ^^^^^^^^^^^^^^^ React element `MyComponent`
 11:   props: MyComponentProps
              ^^^^^^^^^^^^^^^^ property `foo`. Property not found in. See: src/MyComponent.js:11
  8:     return <MyComponent />
                ^^^^^^^^^^^^^^^ props of React element `MyComponent`
```

**Comment by sgronblo** [comment]
Thanks for checking. It's good to know that there's a way that should work. I probably have some gunk around my actual use case that still prevents it from working. I will try to do some more debugging tomorrow. Would you happen to have any tips for how to figure out where my types are getting lost?

**Comment by sgronblo** [comment]
Oh my god! It works! I had forgotten that I had messed a bit with MyComponent adding explicit type parameters and stuff when I was desperate to get this to work. Forgot to undo those changes that after trying your solution yesterday. Thank you so much!

**Comment by gcanti** [comment]
Nice! Can this issue be closed?

**Comment by sgronblo** [comment]
Yes, thanks for the help. I can close it.
