### ISSUE TITLE
some incompatible instantiation of `T` when checking polymorphic react components

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#2537]
I'm not sure that this is the right way to do this, but I'm not sure how to do it otherwise. I'm trying to type a component that takes another component as a prop and then expects to receive that component's required props as its own.

I've tried a couple of things and I can't get anything to work properly. For some 

```jsx
/* @flow */
import React from 'react'

type Props = {
  foo: string
}

type Props2 = {
  bar: string
}

type FieldProps<T> = {
  component: ReactClass<T>
} & T;
  
class Input extends React.Component {
  props: Props
}

class Input2 extends React.Component {
  props: Props2
}

class Field<T> extends React.Component {
  props: FieldProps<T>
}

const x = <Field component={Input} foo="hi" />
const y = <Field component={Input2} bar="hi" />
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWOqoECe2pYACnWwBnMAF4wAb1RgwUOHABcYYQTzoAdgHNUAXw7deAocIBM4qTLAAjcnmWr12vQZ58AYulIwAJoLgiADwAKgB8FtKylPS4GqQaBMpkVAQAwjDkwsIhoXpgAGRgwQDcVqiUGVlgAJIa2ACuRKQAHgTxPqLJ1AB0qTFwcQmWstgmyv4iLuWVorUNBOYtbRodJKwEvf2DRJFgowHC4yamUxWZop7ePjlgS+2d65s4A-E7Vvsiype+E9lhpwNVGBmhZAt8fGBos9tmJJHNGro5AoxAAiAAW6BRYGAuWiGiBXFB4MhW1esPhC0RtjwqIxWJxHCAA

For some reason this one appears to work for a single `Field` but if you do more than one with different components in the same example it breaks:

```jsx
/* @flow */
import React from 'react'

type Props = {
  foo: string
}

type Props2 = {
  bar: string
}

type FieldProps<T> = {
  component: ReactClass<T>
} & T;
  
class Input extends React.Component {
  props: Props
}

class Input2 extends React.Component {
  props: Props2
}

class Field extends React.Component {
  props: FieldProps<*>
}

const x = <Field component={Input} foo="hi" />;
const y = <Field component={Input2} bar="hi" />;
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWOqoECe2pYACnWwBnMAF4wAb1RgwUOHABcYYQTzoAdgHNUAXw7deAocIBM4qTLAAjcnmWr12vQZ58AYulIwAJoLgiADwAKgB8FtKylPS4GqQaBMpkVAQAwjDkwsIhoXpgAGRgwQDcVqiUGVlgAJIa2ACuRKQAHgTxPqLJ1AB0qTFwcQmWstgmyv4iLuWVorUNBOYtbRodJKwEvf2DRJFgowHC4yamUxWZop7ePmBL7Z3rmzgD8TtW+yLKl74T2SC5+uUBqowM0LIEvtdok9tmJJHNGro5AoxAAiAAW6BRYGAoVK0Q0wK4YIhYChsResPhC0RtjwqIxWJxpQ4QA

**Comment by aaronjensen** [comment]
I should also note that ultimately `component` can be a `string` as well, in which case it should get no additional props. I'm not sure how to type that either, but one step at  a time.

**Comment by gcanti** [comment]
```js
// @flow
import React from 'react'

type FunctionComponent<P> = (props: P) => ?React$Element<any>;
type ClassComponent<D, P, S> = Class<React$Component<D, P, S>>;

type FieldProps<P> = {
  component: ClassComponent<void, P, void> | FunctionComponent<P>
} & P;

class Field<P> extends React.Component<void, FieldProps<P>, void> {}

type Props = {
  foo: string
};
type Props2 = {
  bar: string
};

class Input extends React.Component {
  props: Props
}

class Input2 extends React.Component {
  props: Props2
}

const x = <Field component={Input} foo="hi" />;
const y = <Field component={Input2} bar="hi" />;
```

p.s.

Do not use `ReactClass`, it throws away type checking https://github.com/facebook/flow/issues/2159

**Comment by aaronjensen** [comment]
Awesome, thank you @gcanti. I was able to add a `| string` to `component`'s prop type to cover everything. 

Was my attempt highlighting a bug or just a confusing error message?

**Comment by gcanti** [comment]
AFAIK the problem is that you are "shadowing" the base class type parameter

```js
class A<P1> {
  props: P1
}

class B<P2> extends A {
  props: P2
}

const x: B<{ foo: string }> = new B()
```

```
src/index.js:7
  7: class B<P2> extends A {
             ^^ P2. This type is incompatible with
  7: class B<P2> extends A {
           ^ some incompatible instantiation of `P2`
```           

`P2` might be incompatible with `P1` because `P2` is defined while `P1` is inferred.

This works

```js
class A<P> {
  props: P
}

class B<P> extends A<P> {}

const x: B<{ foo: string }> = new B()
```

because you are explicitly saying that `P2` is `P1`

**Comment by gcanti** [comment]
As a rule I always use the `React.Component<DefaultProps, Props, State>` form in order to add typings

**Comment by aaronjensen** [comment]
I had to switch to React$Component in my type def, React.Component silently let everything through.

**Comment by gcanti** [comment]
@aaronjensen can this be closed now?

**Comment by aaronjensen** [comment]
Yes. Thank you again @gcanti.   do you have an idea why React.Component did not work for me?

**Comment by gcanti** [comment]
Weird. Is it in a libdef or in normal code? Can you post an example?

**Comment by aaronjensen** [comment]
It was in a libdef. Try this one, but change line 80 to use `React.Component` https://gist.github.com/aaronjensen/54643af48aedb2f7eba424d9434ca99f

**Comment by gcanti** [comment]
In a libdef is kind of expected, AFAIK there's no official way to import types from another library, hence the "global types" workaround (`React$Element`, `React$Component`, etc..),
I noticed that `React.Component` is also used in the `reduxForm` definition, is it working there?

**Comment by aaronjensen** [comment]
Oh, that's obnoxious. Is this stuff documented somewhere? How do you know so much 😄 

You're right that `React.Component` didn't work in that spot either. It was totally wrong any way, I really wanted a `ReactClass` or the alternative you proposed.

**Comment by aaronjensen** [comment]
hmm, I don't know how to type `reduxForm`. I need it to take a component then return a component that requires the same props as the component that it took minus a few. 

Basically I want something like this:

```
  declare type FormComponentProps = {
    handleSubmit: Function,
  }

  declare type FormComponent<P, T: FunctionComponent<P>> =
    FunctionComponent<$Diff<P, FormComponentProps>>;

  declare export function reduxForm<T>(config: FormConfig):
   (component: T) => FormComponent<*, T>
```

But that doesn't work, I'm guessing because P gets inferred down to `Object` effectively

**Comment by gcanti** [comment]
What about?

```js
type FunctionComponent<P> = (props: P) => ?React$Element<any>;
type ClassComponent<D, P, S> = Class<React$Component<D, P, S>>;
type Component<P> = ClassComponent<void, P, any> | FunctionComponent<P>;

type FormComponentProps = {
  handleSubmit: Function
};

declare function reduxForm<P>(config: FormConfig):
 (component: Component<P>) => FunctionComponent<$Diff<P, FormComponentProps>>

//
// tests
//

type Props = {
  name: string,
  handleSubmit: Function
};

const C1 = (props: Props) => <div>{props.name}</div>

class C2 extends React.Component<void, Props, void> {}

const RFC1 = reduxForm()(C1)
const RFC2 = reduxForm()(C2)

// $ExpectError
;<RFC1 />
// $ExpectError
;<RFC1 name={1} />
;<RFC1 name="Giulio" />

// ;<RFC2 /> // <= error
// ;<RFC2 name={1} /> // <= error
;<RFC2 name="Giulio" />
```

**Comment by aaronjensen** [comment]
@gcanti that works better, but why don't two class ones work?

**Comment by gcanti** [comment]
Not sure I'm follow, you mean why I wrote this?

```js
// ;<RFC2 /> // <= error
// ;<RFC2 name={1} /> // <= error
```

**Comment by aaronjensen** [comment]
Yes, sort of. If I uncomment those they do not fail, which I would expect/hope them to.

I'm also running into this: https://github.com/facebook/flow/issues/2541

So if I import a component from another module, pass it through a HoC, then import that in another module it loses its prop checking.

**Comment by gcanti** [comment]
Now I have a version which works with class components but **not** with function components, kind of sad

libdef

```js
  declare export type FunctionComponent<P> = (props: P) => ?React$Element<any>;
  declare type ClassComponent<D, P, S> = Class<React$Component<D, P, S>>;
  declare type Component<P> = ClassComponent<void, P, any> | FunctionComponent<P>;

  declare type FormComponentProps = {
    handleSubmit: Function
  };

  declare export function reduxForm<P>(config: FormConfig): (C: Component<P>) => FunctionComponent<$Diff<P, FormComponentProps>>;
```

a.js

```js
// @flow
import React from 'react'

type Props = {
  name: string,
  handleSubmit: Function
};

export const C1 = (props: Props) => <div>{props.name}</div>

export class C2 extends React.Component<void, Props, void> {}
```

b.js

```js
// @flow
import { reduxForm } from 'redux-form'
import { C1, C2 } from './a'

export const RFC1 = reduxForm({})(C1)
export const RFC2 = reduxForm({})(C2)
```

index.js

```js
// @flow

import React from 'react'

import { RFC1, RFC2 } from './b'

;<RFC1 /> // <= no error :(
;<RFC1 name={1} /> // <= no error :(
;<RFC1 name="Giulio" />

// $ExpectError
;<RFC2 />
// $ExpectError
;<RFC2 name={1} />
;<RFC2 name="Giulio" />
```

**Comment by aaronjensen** [comment]
very frustrating 😖

**Comment by gcanti** [comment]
@aaronjensen Yeah, make sure type inference works properly in some advanced use cases already is hard, but when it involves React components is (currently) almost impossible. Often the culprit is that we have 2 kinds of components: functional and classes.

**Comment by rosskevin** [comment]
Hey @gcanti, following this pattern I'm trying to strongly type an HOC, but cannot seem to quite get it right, any thoughts [on this example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3qAMKyawB2RL+AvqJNk6AHJspCgIDcqZnlC4AnhiK0AotCJp2ubr35CRuccmAAqI4lBHQABRLYS63EWwoAXkQAmoAM4oA5ixK4AK7CoLCQoCQssjyBLBQorCTQoGRMWGwcZkbAiEQAHljScgqgAGKx8ayMzBm4ADyWAHygALygABQYfBieAFxWAJStzQD8KmoadZGyjRKIxqbmVjZ2RA5Orh7efgHBimERUSnQJJ6eKWmsGlk5+YX4xYr0J2fV6ZMAItSW1ADKzW1nqdPHViORcAA6N5XDh1L5WP6NWaGExZZa2eyOFzuUCxBIsULhaagYTgi41a7mW4FHAPeSKACCUWhtTh30RrQYL08LM+7NA-1AAB8yhVcPjebCmnNHgK5KpLN1zm0aGZQAs1UsAKqeIiQQLJXCwUD5BwsDy4AAWik88sUJAwGGgKBxRvJ7w4nghmuyarI3KIfVAAHkAEYAKyIFEoao1oHjFh1iitAVAXVgCjw0TdGGBERJepSSWgofIAGsZMarYo3FGcAEcakKRxvfGqWqUCw2NhiJB+uU4uLWDHOHM4xYADKdiskLx2rzWtageAoK35pseyGgACS+DcsEDoBYsHwaFgbhQkGz1vdMPwubOruNq4kS07ttIbmoq4LQWwLHOWc2HgW9amXVdLXzAADf1gUDKC026Rw5AheMYIDTwELQEholDRQ0VgAA3RwnFrFhWwsNEiAhHxUJXK1fjtTx2jQWRGNkVRPEXXABnaABZWRJR4m5EH1Qd8XAhimPaW0OKIX5uP6MNIwoIZVXjYQ-wJMTKhYNkEQFRp2k1NsACFTiIIT+iZQTLlZeEfkMmN4wGfogVeOzJkI2AUC-UAABIPkvSAGj+O1FQzTxGmobzfOaVUTNgs45Tkk08jNNxziEupYr8wLgtClKFSVaLQFy+KTPjdMen6fLIBCxz2OKyLkUqgtzUcdo1La+NUgA-A6CS3UgyGwMIowb8u0cXtqAhOaT2tbBQG4NorRQL1qs8OY2x20BVHwUatp6i5+va2thDcdzhs5GhR3VMA1q9PqHHSiFZNUPjIhIHxHAhYQOuwGS7QUog1gGZBdrbS8OkO8bushnbDpu46drmv72HO9wrsDZyEdRubYe6FHltfBHuCIaBdVoYmkbaf7McujDSchzgIYRvrbQiaBoHG5Vqbx3qMNxvHhD7UBO27GbibRhbHGF3bRzZyHNOCAk6nM3UhNoNHi157hgGRFmTNZkyVf-IqiFJxWTbuWlQFrSASANfB6MtJrAwkIA)?

I can't seem to spot my error.

**Comment by PeteJodo** [comment]
@rosskevin I'm running into a very similar issue as you, here's my [example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiArgHYDGGAlnKQMJwC2OtepGAPAAoB8YAvGAAUOAE5wcAZwBcYLgEoBfAPwAlPAENKAEgCiMPIzacNpLDwDcmXATowNkyQ2at2HACIAaOd4DKfQTsHSQ51LQxtZxZSYw9vLj8eS2t8MCjXTl4BIjJKGnomaNisgB80+0d0mLdTLHjvWuTsVIAVAAtDPBabbIBvMABtcgrJADkNI1lJDFEqUgBzAF0pmbn5sABfK1QoXOpaMCNRea6Oo25ZfowzvFl2zu7Uje8ANVltLnF8UWxHvG5vABya6dQFJISoMBQsAAIQceCqxlkiLcvE8kOhcwAVnhKHgACb3SZgF6oeSyEgUfYFFzVTjadxUKBQAFgK43O43P6bJJsjFQ8i0aZgIkElEYbKIUifCSSJRgDhwyQIwoZNkAOk1UplUg2YBBRn4vWxuIwBNFeuAyWhIpu+PF6vxVEkOHsWHGRmygNF+KEgLAAGpYfCHU6XW6PQQg4D5ICrDbRHgMMRRKRbZ17aq6VYNkA) and getting a similar error. Were you able to figure your issue out?

**Comment by rosskevin** [comment]
@PeteJodo - no- didn't find a solution, ended up refactoring to a different way.
