### ISSUE TITLE
Class property Missing annotation

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/flow#2538]
Flow doesn't accept this:

```js
class {
  handleSomething = (event: E): void => {};
}
```

But it's ok w/ this:

```js
class {
  handleSomething: (event: E) => void = (event) => {};
}
```

Is this intentional?

**Comment by gcanti** [comment]
What do you mean? I got a syntax error and then "identifier `E`. Could not resolve name" for both

**Comment by alexfedoseev** [comment]
This is weird, I just tested it on [simple case](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwwALbAOwBMYBTAZTgFtGAXSgSxoHMwAXjAAKRgDdGNTgC4wAUSkyAlPIlwedYQD5SAXwDcqfeix4CAIVLkqtBi3ZdeA+eOVzFHlbrAatwmKS0pw+QnokRiaoQA) and it works fine. But in my app it gives me this:

<img width="756" alt="screen shot 2016-09-29 at 03 18 42" src="https://cloud.githubusercontent.com/assets/4244251/18928872/9a32d9b0-85f4-11e6-8fb6-a23ba61233d9.png">

Something else is causing this. Sry for the noise, closing it. Thanks for help 👍
