### ISSUE TITLE
Possible to have deep $Shape matching?

### ISSUE THREAD

**Issue by cloudkite** [facebook/flow#2542]
I'm trying add type checking to a function which deeply merges objects. I want it to check the object structures have equivalent types. But allow the obj structure that is the source of the merge to omit keys. I initially thought I could achieve this using $Shape :

```
function mergeDeep<T>(obj: T, source: $Shape<T>): T {
}

mergeDeep({ num: { n1: 1, n2: 2 } }, { num: { n1: 100 } })
// results in { num: { n1: 100, n2: 2 } }
```

However since $Shape only is only against the top-level gives the following error

```
mergeDeep({ num: { n1: 1, n2: 2 } }, { num: { n1: 1 } })
                 ^ property `n2`. Property not found in
mergeDeep({ num: { n1: 1, n2: 2 } }, { num: { n1: 1 } })
                                            ^ object literal
```

Is there any way to express nested $Shape matching in flow?

**Comment by zerkalica** [comment]
Same error for $Key:

```js
class A {
    a: number
}

class B extends A {}

// Property 'a' not found in B:
export const s = ({
    a: 1
}: {[id: $Keys<B>]: any})
```

$Shape and $Keys sans only top-level object or interface, they do not watch into extends, implements, etc.

**Comment by calebmer** [comment]
We aren’t going to add this behavior to `$Shape`, but the `$Keys` behavior is definitely a bug!

**Comment by cloudkite** [comment]
for anyone stumbling across this, managed to do this using $ObjMap

```
type $DeepShape<O: Object> = $Shape<
  $ObjMap<O, (<V: Object>(V) => $DeepShape<V>) | (<V>(V) => V)>
>
```
