### ISSUE TITLE
crypto$Decipher#update type annotation incorrect

### ISSUE THREAD

**Issue by nicks** [facebook/flow#2544]
According to
https://nodejs.org/api/crypto.html#crypto_decipher_update_data_input_encoding_output_encoding
the input_encoding should be `'latin1' | 'base64' | 'hex'`

for some reason, flow's definitions are `'utf8'| 'ascii' | 'binary'`, though it's not clear where that came from.
https://github.com/facebook/flow/blob/8e9755ed36d631679314110ea296683c71f269f0/lib/node.js#L340

**Comment by glennreyes** [comment]
@nicks node v4 used different types for this API:
https://nodejs.org/dist/latest-v4.x/docs/api/crypto.html#crypto_class_decipher

I'll probably send a PR tackling this 👍
