### ISSUE TITLE
Maybe types don't work with non-tuple(?) arrays

### ISSUE THREAD

**Issue by pyryk** [facebook/flow#255]
The following causes flow to yield 3 errors related to type incompatibilities between ?string, string and undefined:

    /* @flow */
    
    var letters: Array<?string> = [
    	'a',
    	'b',
    	'c',
    	'd',
    	'e',
    	'f',
    	'g',
    	undefined
    ];

However, as far as I understand, this should not yield an error because of the maybe type. For instance, removing the `undefined` from the array and `push`ing it separately after the variable definition removes the errors. 

This also happens with arrays of objects with maybe-type members (`{ a: ?string; }`).

Note the number of elements in the array. Removing any of the array elements removes the errors. I think this is related to flow handling smaller arrays as tuples (although according to the documentation at http://flowtype.org/docs/arrays.html#_ 8-element arrays should be tuples as well).

I used Flow version 0.2.0.

The precise error messages:

    $ flow check
    /Users/pkro/Documents/other/flow-test/test.js:3:25,30: ?string
    This type is incompatible with
      /Users/pkro/Documents/other/flow-test/test.js:4:6,8: string
    
    /Users/pkro/Documents/other/flow-test/test.js:4:6,8: string
    This type is incompatible with
      /Users/pkro/Documents/other/flow-test/test.js:11:6,14: undefined
    
    /Users/pkro/Documents/other/flow-test/test.js:11:6,14: undefined
    This type is incompatible with
      /Users/pkro/Documents/other/flow-test/test.js:4:6,8: string
    
    Found 3 errors

**Comment by gabelevi** [comment]
So when you have `var x : type = value` Flow infers the type of `value` first and then makes sure it's compatible with `type`. The errors here come from the inference.

I just wrote a longer explanation of what's happening here including some workarounds and future plans on https://github.com/facebook/flow/issues/256
