### ISSUE TITLE
How to type a lazy thunk?

### ISSUE THREAD

**Issue by ccorcos** [facebook/flow#2554]
I want to have sound type checking for a lazy thunk that looks like this:

```js
const lazy = (fn, args) => {
  return {_type: 'thunk', fn, args}
}
```

This is very similar to `React.createElement` for a stateless component, and not a single argument, but arbitrarily whatever the function's type definition expects....

Any ideas how to do this?

**Comment by jeffmo** [comment]
Flow doesn't currently expose a syntax for specifying a non-uniform arg-spread (i.e. best you can do syntactically right now is `(...args: Array<T>) => R`, but not `(...args: T) => R`. As a result I don't think there's a good way to verify that the args match the supplied function in the type signature. (Making it possible to do `(...args: T) => R` is probably something we should unlock at some point -- I think it's doable)

However, you could do the following to at least verify that the thunk-runner carries through the return type of the function:

https://flowtype.org/try/#0C4TwDgpgBAKgFgVwHYGsA8AxANFASgPigF4oBvAfVEgC4oByYRVOnAMyVuygEMAnAcwDOtAIK9e3EGm5IQ+AL4BuAFDLWyAMbAAlgHskUXsnjJ0uHBloAKAHR2+Q0eMnTZ+AJTFCBK41O0TVEwcAndaXDJlKEMIYAReAz9UG3ZbOySUGwdBdxV5VXUkLT0DAFtuFAhAswtrOyyBYSgxCSkZOU8ib3wrKKh2Thw+7KdW1zksZTDYJnQuAkjo3lj4gwoqCFoGWZZ+pBxspWV85Q19QWAoQQRS4igrblokG4AjCF4cF6fX9+mL3m0SH4XigAGVgACgQ8oABqKAvXKqM5IC5Qfi6XQAE2qd3KlWqVmupRwAG0AIw4ABMAF1EcjUS9uNjZriKlVZoSbqSKVAAETcQSY1i82mKKAAenFUAAcro0RjMVAAO6SKDAOV46CMbSCKDvXi6XjNGAAWSR50uADduAAbbSY3AQa424C0f6A4EkIxIAnorHVOkW+FMx3O11QZ6lN5Gr3GDl+5mmXJAA

**Comment by ccorcos** [comment]
Interesting. Thanks for the tip! Are there any PR's or Issues tracking these features?

1) Specifying function argument types as tuples: `(...args: [string] | [number, number]) => number`

2) Getting the type signature of a function's arguments: `type args = $Args<Fn>`
