### ISSUE TITLE
No way to tell which of a type error message's "reasons" is primary

### ISSUE THREAD

**Issue by pelotom** [facebook/flow#2557]
Take this example:

``` javascript
// @flow

import React, { Component } from 'react'

class Foo extends Component {
    props: {
        firstName: string,
        lastName: string,
    }

    render() {
        return (
            <div>
                <h1>Hello {this.props.firstName} {this.props.lastName}</h1>
            </div>
        )
    }
}

class Bar extends Component {
    render() {
        return <Foo firstName="John" />
    }
}
```

This code has an error, which is that `Bar` is not constructing a `Foo` element with all the required props. Flow correctly notices this:

```
foo.js:6
  6:     props: {
                ^ property `lastName`. Property not found in
 22:         return <Foo firstName="John" />
                    ^^^^^^^^^^^^^^^^^^^^^^^^ props of React element `Foo`
```

however the "top-level context" here is wrong. It's not line 6 where the error is occurring; that's the location of the prop type declaration that's being violated. The real source of the problem is the second one mentioned, on line 22: the use site. This may not seem like a big deal, although just this ordering of messages on the CLI [has been pointed out as being confusing](https://github.com/facebook/flow/issues/2151) in and of itself. But the more annoying problem here is for IDEs and the like using Flow via the API, because they are highlighting the wrong section of code with an error marker. You can see this on [Try Flow](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3qAMKyawB2RL+AvqJNk6AHJspCgORloJAM5TQAMVixQRAB652AE1mNmbDrUSgjoDHwxSAXAeM2eKbFNwA5EmiJXH2FCwDmlQ7ZGko4ubh64Xr7+NpzINsIsGkTYABQAlNaBoMK4AK7YLKApAVnGADwaKABuAHwlpbZlABYAjDUAEkTQcLS4TShSAHSmsOaDkPYhrkTcNH0Dw2ZDwc7TnGXArXUN5cCVtfU2afWxsYgS0rIAQiTYymqa2kxYevg09QlJqRnvpTn5hTKCiUEwcqzcAF4AEQAKVgTRYUNAwG2xlOQA):

![image](https://cloud.githubusercontent.com/assets/128019/19016834/6f731950-87da-11e6-8ca3-1fb55949a74b.png)

The type annotation on `Foo.props` is getting highlighted as if there's an error there. In a more realistic example, the component where the prop types are declared may be in a different file, and it may be used dozens of times throughout your app! It becomes a huge pain to try to figure out where the real problem is.

The API result for this example is currently:

``` json
[
  {
    "kind": "infer",
    "level": "error",
    "message": [
      {
        "context": "    props: {",
        "descr": "property `lastName`",
        "type": "Blame",
        "loc": {
          "source": "-",
          "type": "SourceFile",
          "start": {
            "line": 6,
            "column": 12,
            "offset": 93
          },
          "end": {
            "line": 9,
            "column": 5,
            "offset": 153
          }
        },
        "path": "-",
        "line": 6,
        "endline": 9,
        "start": 12,
        "end": 5
      },
      {
        "context": null,
        "descr": "Property not found in",
        "type": "Comment",
        "path": "",
        "line": 0,
        "endline": 0,
        "start": 1,
        "end": 0
      },
      {
        "context": "        return <Foo firstName=\"John\" />",
        "descr": "props of React element `Foo`",
        "type": "Blame",
        "loc": {
          "source": "-",
          "type": "SourceFile",
          "start": {
            "line": 22,
            "column": 16,
            "offset": 379
          },
          "end": {
            "line": 22,
            "column": 39,
            "offset": 403
          }
        },
        "path": "-",
        "line": 22,
        "endline": 22,
        "start": 16,
        "end": 39
      }
    ]
  }
]
```

It's the 3rd context block which provides the use site which is of primary interest. Compare this with a comparable error involving function arguments:

``` javascript
// @flow

function f(x: number) {
  return x + 1
}

f()
```

The JSON for this error appropriately puts the call site as the first context:

``` json
[
  {
    "operation": {
      "context": "f()",
      "descr": "function call",
      "type": "Blame",
      "loc": {
        "source": "-",
        "type": "SourceFile",
        "start": {
          "line": 7,
          "column": 1,
          "offset": 52
        },
        "end": {
          "line": 7,
          "column": 3,
          "offset": 55
        }
      },
      "path": "-",
      "line": 7,
      "endline": 7,
      "start": 1,
      "end": 3
    },
    "kind": "infer",
    "level": "error",
    "message": [
      {
        "context": "f()",
        "descr": "undefined (too few arguments, expected default/rest parameters)",
        "type": "Blame",
        "loc": {
          "source": "-",
          "type": "SourceFile",
          "start": {
            "line": 7,
            "column": 1,
            "offset": 52
          },
          "end": {
            "line": 7,
            "column": 3,
            "offset": 55
          }
        },
        "path": "-",
        "line": 7,
        "endline": 7,
        "start": 1,
        "end": 3
      },
      {
        "context": null,
        "descr": "This type is incompatible with",
        "type": "Comment",
        "path": "",
        "line": 0,
        "endline": 0,
        "start": 1,
        "end": 0
      },
      {
        "context": "function f(x: number) {",
        "descr": "number",
        "type": "Blame",
        "loc": {
          "source": "-",
          "type": "SourceFile",
          "start": {
            "line": 3,
            "column": 15,
            "offset": 24
          },
          "end": {
            "line": 3,
            "column": 20,
            "offset": 30
          }
        },
        "path": "-",
        "line": 3,
        "endline": 3,
        "start": 15,
        "end": 20
      }
    ]
  }
]
```

Hopefully the fix for this is simple; just reverse the order of the the contexts being used to construct React prop type errors.

**Comment by pelotom** [comment]
After some more experimentation I've discovered that this problem isn't specific to React element creation at all; it happens whenever an object fails to conform to an object type due to missing fields. [A few other examples](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQIYCWATqALygDeoAHgFygB2ArgLYBGWxANKGgyw5dQAX2QhQAFQAWWAM44sNfKwzR5oQowDGsYsSzaU0NKAzMUoFLNBdie0LEZWbsdgCtDlyEWhaA5lawiBK6jJB6rEEuijTYRlgAJlaYWIiQzDoohE6gEbAAFPgMBCQAlFRi+QXU9KAAzKJlyGFyluwlRKQUtQyNYoitltrkoDW0faKd5eJgMvKxKmoauvpeJmbQ+No41or6eoNObaCJ091UE6AARLLQcNe8-A2iLceWWOej1-jE-ursX7-LDXZBAA):

![image](https://cloud.githubusercontent.com/assets/128019/19128023/553728a0-8af6-11e6-9670-b3af7f6a189f.png)

Note that only *missing* fields in an object exhibit this problem, not fields of the wrong type.

**Comment by pelotom** [comment]
I just noticed [another similar problem](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQIYCWATqALygDeoAHgFygB2ArgLYBGWxANKGgyw5dQAX2QhQAA0ixYk0IQDOTWClD48RUgBNmOFLHWh4xWIwDm0NAFp02baEiEs0bQDoPodszXwsAcmIcRlVECQBjaCJWQgsFFH9lDQISPiwUAEJELBoMWGI1cLNFNRlDCmp6UAAiAAsXOGreflAAZlFQcTAPNxV4XlijItYMaHSXNFBtQkhILixGNVZYXTHQbGJa-AxFXj9QFGJJg3VFRUJzRjCwaVl5E+StW0wsBwA3fGJCfHYx3nxGA4UPVQFxTKQASEUPgUIQzOoMNhPoprqB4cCcD9YG8cNosJFPjC4YwskVGCUvJ8GClSBQyoggA) though with wrongly-typed object fields:

![image](https://cloud.githubusercontent.com/assets/128019/19128631/0714c364-8af9-11e6-967d-7bb808f3c2a7.png)

So to restate the general problem here, it seems that there is no consistent way to discover which of the "reasons" mentioned an error's `message` array is the *primary* one. Most editors which show error annotations based on Flow (including Try Flow) seem to have taken the convention that the first reason to appear in the array is primary, and this seems to work for the most part, but there are places where the type checker violates this assumption.

**Comment by pelotom** [comment]
Actually the second case seems to be more problematic, because it's not merely a matter of reordering the existing reasons... there is in fact *no* reason in the list that corresponds to the actual problem area in the code. I will make a separate issue for this.

**Comment by julienvincent** [comment]
I am frequently running into this issue (and the related ones) while using flow in my IDE for error checking. It makes trying to follow and sort out issue a much slower and frustrating process.

How is it that this has not even been so much as commented on by a member in 7 months? Can we have some kind of feedback in regard to this?

**Comment by pelotom** [comment]
I gave up Flow in favor of TypeScript because of this issue ¯\_(ツ)_/¯

**Comment by julienvincent** [comment]
@pelotom I can understand why you would do that - this issue + the fact that there is absolutely no feedback is a real sore point.

**Comment by calebmer** [comment]
Closing since we know about this issue and we are working to fix it 😔

We hope to win you back soon!

**Comment by julienvincent** [comment]
@calebmer Whoop! Thanks for the feedback 👍
