### ISSUE TITLE
Flow fails to parse its own library

### ISSUE THREAD

**Issue by Mohamed-Abo-El-Soud** [facebook/flow#2558]
So i run flow and i find out that its giving me an error when parsing ITS OWN LIBRARY. Talk about Ironic! so i go and take a look at the file `node_modules/react-native/flow/Promise.js` and it doesn't even have the `//@flow` comment even at first place. So:
1. Why is it parsing a file that doesn't have the `//@flow` comment?
2. What is the error? (Im new to flow, so I don't know what its trying to say)

```
> flow
node_modules/react-native/flow/Promise.js:12
 12: declare class Promise<+R> {
                           ^ Library parse error:
 12: declare class Promise<+R> {
                           ^ Unexpected token +
```

**Comment by jeffmo** [comment]
What version of Flow are you using?

PS: we recommend using the `flow-bin ` npm dependency and not a globally-installed version of Flow to avoid Flow versioning issues.

**Comment by Mohamed-Abo-El-Soud** [comment]
0.20.1

**Comment by Kriegslustig** [comment]
> 1. Why is it parsing a file that doesn't have the //@flow comment?

In some contexts it's optional. For example in libdefs (files containing only declarations) imported in the `[libs]` section of a `.flowconfig`.

> 2.. What is the error? (Im new to flow, so I don't know what its trying to say)

You're most likely using a version of flow which doesn't support the "`+`-generics" operator in yet. What version are you running (run `flow version` to check)? The operator was added in Flow 0.21.0.

As you can see [here](https://flowtype.org/try/#0PQKhCgAIUhhB7ADgTwE4EsDmALALpACgGMBKSAJgAYBGAZgFpFUBTAZ2YDtcAaSAMQCGRZgCN48ANa8AkhyIA6KDACCAG1WQMOXK01tmqAG7MAJouhLIAFWzpdreAFdUwyEXgnmkO5FXphHOwmkI4cnqiQuNheAEIAygAi9Ky4yKpefgHskABmTmHeHJHRlgAy0rAAogBycZW56OmFxV6o4vgm6CxEuPCoyJDwOcU+Ds6uuCzM8pDKRQImnbjo8BwCGpioAlyWQ5CIAric+Fp4ukTbkCJeeaHB6EVRXgAKylY1VnENTQ8tkKwCAC2Xk63V6-XMIGA4HAwGA1mi2W2HHguEOK0CkAELDcSGQwAOKVMuTagL+IkcjVw9F+fFU8AA7pBPDkHuhlqtdHlULD4dV0cZIM9SXY2JAGezsP94MDICiOMk0WFscFlM9pLoFp57hxwJ4iKpsV4DQJWLphTLRQAeADUACUAHyQADeUFxgUmjh6fWI61UIiEEgAXIQ3ZA9A5VMYQwQWKxHKpcAB+EMWwHWx2QAA+kDtZAAvE7DPB0CZuGG9AArZg9GMGNqoFNYjjIAtFksmN1tyDpgAephIIeLpYA3DDw08OFaAKoOggV1Z8BOs9RNpMEQzrRzMEN5yCFoUi9gzp05pPT8vh8OrO3Mas9NcEet9EPbVv7p1p62z7OQc9d1Mj2YE8xzdC5cCIbAT3nK9Bg4W972TOtUAbV8W27JMv2PH8c2nADD0tbCHVA8MUnRIgI3gKNgKsOd4BERCmywmjT2sQcCPTY9aLHUi0WWCiWEQq1aKfFC+ibN92OY4TiPHf4+P8LF1CtSp0kBXgrCDaQji2ER0hUtSHTnJhCLYEMrCkoCrQAEisRxEHSABZAREGE3hUkQZg9msgQGQEdkjJ4+TyM0IQWIIEzOLM2YUIEZArWk2iHUs0yZJIyA4UgapVkVbYTBVWZ1VYN0TFWYDZxgq9F2XRpVEfTdVG3Xduz7UxLyq+C7xrJC-1E1Dm3fA9Ws7cN2OHEx0rI-i3FNXAZIIejGPMlKorS8AAF9wCAA), the current version of Flow is perfectly able to parse _"ITS OWN LIBRARY"_. ;)

**Comment by jeffmo** [comment]
Am @kriegslustig points out, this syntax shipping in v0.21. Your best bet is to upgrade to the latest version (and preferably use `flow-bin ` to do so :) )
