### ISSUE TITLE
HTMLElement property `files` missing

### ISSUE THREAD

**Issue by nexneo** [facebook/flow#2559]
HTMLElement property `files` missing
https://www.w3.org/TR/2012/WD-html5-20121025/common-input-element-apis.html#dom-input-files

Code like this will throw type error, 
```
var files = document.querySelector("#upload").files;
                                              ^^^^^ property `files`. Property not found in
var files = document.querySelector("#upload").files;
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ HTMLElement
```

**Comment by mroch** [comment]
The problem is that the element returned by querySelector might not be an input element, and `files` only exists on `HTMLInputElement`.

Test that the element is the right type and it should pass:

```
let files;
if (upload instanceof HTMLInputElement) {
  files = upload.files;
} else {
  // throw or something
}
```

https://github.com/facebook/flow/blob/master/lib/dom.js#L1489

**Comment by nexneo** [comment]
Yay! That works. Thanks
