### ISSUE TITLE
Type checking array with two types fails if the 8th entry is a function

### ISSUE THREAD

**Issue by exi** [facebook/flow#256]
Just an example library code:
```
declare class Myclass {
    myfun(myarray: Array<Function | string>): any;
}
declare var myclass: Myclass;
```
This code checks out without error:
```javascript
myclass.myfun(["1", "2", "3", "4", "5", "6", function (ar) {}])
```
This code produces the error below:
```javascript
myclass.myfun(["1", "2", "3", "4", "5", "6", "7", function (ar) {}])
```
```
/home/exi/tmp/flow/test/code/test.js:1:16,18: string
This type is incompatible with
  /home/exi/tmp/flow/test/code/test.js:1:51,66: function

/home/exi/tmp/flow/test/code/test.js:1:51,66: function
This type is incompatible with
  /home/exi/tmp/flow/test/code/test.js:1:16,18: string

/home/exi/tmp/flow/test/lib/lib.js:2:26,33: function type
This type is incompatible with
  /home/exi/tmp/flow/test/code/test.js:1:16,18: string

Found 3 errors
```

**Comment by gabelevi** [comment]
Yeah, you've hit the super arbitrary threshold we're we stop keeping track of an array like a tuple (with a type for each element) and we try to infer the type of the array.

Unfortunately, our inference doesn't support heterogenous arrays terribly well. @avikchaudhuri told me that keeping a union type of all possible element types didn't scale to huge arrays, and trying to find a common type for all elements was difficult. So the current algorithm takes the type of the first element and assumes the rest of the array has the right type.

I've found a few workarounds. For example, while we have to worry about huge arrays we haven't had to worry about functions with a huge number of rest params, so this works:

```JavaScript
function myArray<T>(...rest: Array<T>): Array<T> { return rest; }
myArray("1", "2", "3", "4", "5", "6", "7", function (ar) {});
```

Another way to tell Flow what type the array elements should be is by specifying the type of the first element. At the moment you can do

```JavaScript
var firstElement: string | (x: any) => void = "1";
[firstElement, "2", "3", "4", "5", "6", "7", function (ar) {}
```

though after the deploy this week (today or tomorrow) you will be able to do
```JavaScript
[("1": string | (x: any) => void), "2", "3", "4", "5", "6", "7", function (ar) {}
```

The long term solution is by adding syntax to tell Flow the type of the array, like how in Java you would say `new ArrayList<MyThing>()`. Not sure what the syntax would be, but the general idea is something like

```JavaScript
  [<number | string> 1, "two", 3, "four", 5, "six", 7, "eight", 9, "ten"]
```

Geez that's ugly. Maybe something quite different :)

**Comment by exi** [comment]
The problem occurred for us in the context of angular style dependency injection like this:
```javascript
    app.factory("AuthService",
        [
            "TokenService",
            "RegisterService",
            "$q",
            "CookieFactory",
            "$localStorage",
            "CustomersService",
            "RedirectionHelperService",
            "UserConfirmationService",
            function (
                TokenService,
                RegisterService,
                $q,
                CookieFactory,
                $localStorage,
                CustomersService,
                RedirectionHelperService,
                UserConfirmationService
            ) {}
        ]
    );
```
This naturally implies that we could have a rather large number of dependencies followed by a single function. And we would of course like to declare the types externally in the lib.
In this case the function is always at the end of the array.
Would it be possible to type the array via a declared type with a rest type in the front?
Something like this:
```
declare array AngularDependencyArray: Array<...deps: string, Function>;
```
That would help a lot for this scenario.

**Comment by gabelevi** [comment]
I don't suppose you could separate the function from the string dependencies? It would be easier to type if you could write

```JavaScript
app.factory("MyService",
  [
    [
      "ServiceA",
      "ServiceB",
      ...,
      "ServiceZ"
    ],
    function (
      ServiceA,
      ServiceB,
      ...,
      ServiceZ
    ) {}
  ]
);
```

Because then you could use a tuple like so

```JavaScript
declare array AngularDependencyArray: [Array<string>, Function];
```

Another alternative is to add syntax to specify when something truely is a tuple. This means Flow wouldn't need to guess and could relax the 8-element limit. But that still wouldn't allow you to just specify the type of the last element of the tuple.

Honestly, I don't foresee us building syntax like you suggest, mostly because I don't think it would be used very often. If I'm wrong we definitely could reconsider.

**Comment by exi** [comment]
Another quick solution would be to make the limit configurable. That would enable us to write third party declarations for the angularjs dependency injector because there most likely are never more than say 16 dependencies for any given angular factory. 



-----Original Message-----

**Comment by avikchaudhuri** [comment]
This issue should be fixed now. Will close it after the next release, which will contain a related test.

**Comment by exi** [comment]
Is this already in master? If so, could you point me to the commit/how to do it? Would love to check it out right away.

**Comment by gabelevi** [comment]
Hi @exi, @bhosmer fixed this in two ways.

1. He changed the way we infer the types of array literals. It basically looks at all the types in the array and if there's more than one type it infers that it is an array of a union type. [Here are some tests](https://github.com/facebook/flow/blob/master/tests/arrays/Arrays.js#L14) demonstrating what you can do now
2. Because his new inference is so much faster than the old, we no longer have the 8 element limit on tuple size. As long as there's no spread element in your array literal, we also keep track of the type of the element at each position.

**Comment by samwgoldman** [comment]
This issue can be closed.

**Comment by abdulhannanali** [comment]
@gabelevi Just a question regarding this, If you are available.

Will this code validate for both of the types? Simplifying this, Does the order matter in the use of `|`? 

```
type A = Array<string | Function>

// Statements to be validated
const a : A = ['a', 'fa', 'fads', function () {}];
const b : A = [function () {}, 'a', 'b'];
```

**Comment by nmn** [comment]
Both should work. Also have you tried using flow.org/try

**Comment by abdulhannanali** [comment]
Thank you @nmn for replying. That clears it out. I haven't but this seems cool. Will definitely give it a shot :heart:

**Comment by nmn** [comment]
@abdulhannanali Just wanted to add that the weird mixed case only applies for inference. If you add the type annotations there is no problem anyway.
