### ISSUE TITLE
data and accessor properties with the same name should be allowed

### ISSUE THREAD

**Issue by mroch** [facebook/flow#2561]
As far as I can tell, ES6 allows an object initializer to have both data and accessor properties with the same name.

Specifically, a getter creates a `PropertyDescriptor` with `[[Get]]` set ([14.3.9](http://www.ecma-international.org/ecma-262/6.0/#sec-method-definitions-runtime-semantics-propertydefinitionevaluation)), and then calls `DefinePropertyOrThrow` ([7.3.7](http://www.ecma-international.org/ecma-262/6.0/#sec-definepropertyorthrow)), which calls `[[DefineOwnProperty]]` ([9.1.6](http://www.ecma-international.org/ecma-262/6.0/#sec-ordinary-object-internal-methods-and-internal-slots-defineownproperty-p-desc)) which calls `ValidateAndApplyPropertyDescriptor` ([9.1.6.3](http://www.ecma-international.org/ecma-262/6.0/#sec-validateandapplypropertydescriptor)). Steps 7-9 of that process explicitly allows duplicates.

Currently, the flow parser errors with `Object literal may not have data and accessor property with the same name`.

For example, `{ foo: 123, get foo() {} }`

**Comment by gabro** [comment]
Babel (babylon) seems happy with it, so yes, this seems like an issue with the flow parser.

https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=true&presets=es2015%2Ces2015-loose%2Ces2016%2Ces2017%2Clatest%2Creact%2Cstage-0%2Cstage-1%2Cstage-2%2Cstage-3&experimental=false&loose=false&spec=false&code=const%20o%20%3D%20%7B%0A%20%20foo%3A%2042%2C%0A%20%20get%20foo()%20%7B%7D%0A%7D
