### ISSUE TITLE
Nested array

### ISSUE THREAD

**Issue by alexeygolev** [facebook/flow#2562]
I'm trying to define a nested array type like so
```js
type NestedArray<T> = Array<T | NestedArray<T>>
 ```
However it seems only go one level deep
```js
const t: NestedArray<number> = [1, [ 2, 2 ] ]  //ok
const t2: NestedArray<number> = [1, [ 2, 2, ['f'] ] ]
/* error
const t: NestedArray<number> = [1, [ 2, 2, ['f'] ] ]
                                              ^ array literal. This type is incompatible with
3: type NestedArray<T> = Array<T | NestedArray<T>>
                               ^ union: number | type application of identifier `NestedArray`
*/
```
Am I defining it in a wrong way?

**Comment by samwgoldman** [comment]
This seems correct to me. It should be a type error to include a string anywhere in the nested array since you explicitly annotated `t2` as `NestedArray<number>`, right? If you replace `'f'` with a number, you should be able to use deeply nested arrays.

**Comment by alexeygolev** [comment]
@samwgoldman Hm, It's working if I do `t2: NestedArray<number|string>`. The error message is confusing though. It says that `array literal` is the problem. Not the string

**Comment by samwgoldman** [comment]
When checking a value against a union type, Flow shows the top-most incompatibility, but also information about why each branch of the union failed. This is the full error:

```
test.js:4
  4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                                                ^^^^^ array literal. This type is incompatible with
  3: type NestedArray<T> = Array<T | NestedArray<T>>
                                 ^^^^^^^^^^^^^^^^^^ union: number | type application of identifier `NestedArray`
  Member 1:
    4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                             ^^^^^^ number
  Error:
    4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                                                  ^^^^^ array literal. This type is incompatible with
    4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                             ^^^^^^ number
  Member 2:
    3: type NestedArray<T> = Array<T | NestedArray<T>>
                                       ^^^^^^^^^^^^^^ type application of identifier `NestedArray`
  Error:
    4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                                                   ^^^ string. This type is incompatible with
    3: type NestedArray<T> = Array<T | NestedArray<T>>
                                   ^^^^^^^^^^^^^^^^^^ union: number | type application of identifier `NestedArray`
    Member 1:
      4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                               ^^^^^^ number
    Error:
      4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                                                     ^^^ string. This type is incompatible with
      4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                               ^^^^^^ number
    Member 2:
      3: type NestedArray<T> = Array<T | NestedArray<T>>
                                         ^^^^^^^^^^^^^^ type application of identifier `NestedArray`
    Error:
      4: const t2: NestedArray<number> = [1, [2, 2, ['f']]]
                                                     ^^^ string. This type is incompatible with
      3: type NestedArray<T> = Array<T | NestedArray<T>>
                                         ^^^^^^^^^^^^^^ array type
```

The array `['f']` is incompatible with Member 1 because it is not a number and incompatible with Member 2 for two reasons again, Member 2.1 because `'f'` (string) is not a number, Member 2.2 because `'f'` (string) is not an array.

**Comment by alexeygolev** [comment]
I guess the confusion is mostly due to `tryflow` and `nuclide` showing  a short version.
I still can't make [this](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSA5LAZ1KwwEFDD9yAeAFQD4wAXjBsO3HmAA+YOo2ajOvPn0y4CxMFACuAOxykAlnB2aCpJjqUAKAB70AXDIZNW7RfwCUjheL4BudApqMB44DDgASSYAWyEwHS1ogCMsQgCgklDwgBkDRjiAbzI4ABFImIcRN3Ew8qxogQBfANQcY3zSUrhcxnoe0m9q3lr+gWEAbQLUMGKyqPrK8YBGABowACYAXVRGzYC2nQ6u+ejKny5zrLqGsdnuvNI+h4A6aPxKWyEBG2fOuYqPK12qQyIMxMNwidbrB8OYsDorH9rvQPEA)
 work though. I don't think flow understands that `Array<Array<TodoItem>>` is `NestedArray<TodoItem>`.
It might be I'm doing something wrong. But I've been trying to fix flow-typed libdef for ramda without any luck because of this.

**Comment by samwgoldman** [comment]
Hmm, my hunch is that you're running into array invariance when you try to say that `Array<Array<T>>` inhabits `NestedArray<T>`. Here's a smaller repro of that:

```
/* @flow */

declare type NestedArray<T> = Array<T | NestedArray<T>>;

function f(x: NestedArray<number>) {}

declare var xxs: Array<Array<number>>;
f(xxs);
```

I think this is actually expected behavior, because I could define `f` like so:

```
function f(x: NestedArray<number>) {
  x[0] = 0; // This is not a valid operation on an Array<Array<number>>!
}
```

You need a covariant (read: readonly) array type (#2333) to make this work. You can see that the basic principle here works as long as the container is covariant:

```
/* @flow */

class List<+T> {}

declare type NestedList<T> = List<T | NestedList<T>>

var xxs: List<List<number>> = new List();
(xxs: NestedList<number>);
```

If you change `+T` to just `T` you get a similar error.

**Comment by alexeygolev** [comment]
@samwgoldman I see. In other words it's not yet possible. Thanks, will mark the issue on `flow-typed` and keep an eye on #2333

**Comment by samwgoldman** [comment]
It's also worthwhile to note that this is a case where using fewer type annotations helps Flow find a valid type for your program:

```
/* @flow */

declare type NestedArray<T> = Array<T | NestedArray<T>>
declare function flatten<T>(xs: NestedArray<T>): Array<T>;

type TodoItem = number;
type TodoList = {toDoItems: Array<TodoItem>};

const toDoListsList = [{toDoItems: [1, 2]}];
const toDoItems = toDoListsList.map(x => x.toDoItems)
const t: Array<TodoItem> = flatten(toDoItems)
```

```
No errors!
```

**Comment by alexeygolev** [comment]
@samwgoldman Well, kind of. But flow goes crazy on [this one](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSA5LAZ1KwwEFDD9yAeAFQD4wAXjBsO3HmAA+YOo2ajOvPn0y4CxMFACuAOxykAlnB2aCpJjqUAKAB70AXDIZNW7RfwCUjheL4BudApqMB44DDgASSYAWyEwHS1ogCMsQgCgklDwgBkDRjiAb1I4ABFImIcRN3Ew8qxovgBfANQcY3zistzGem7SOIBtItK66MqBgEYAGjAAJgBdRvmAtp0Okaj6+jjOuD7evNIAOmj8SlshARsj3c2xj1b2-v7hWHxzLB0rW4qPE7OLoIrmAANRgCYPIA)
it infers `string` out of nowhere
