### ISSUE TITLE
Question: Run flow only on single directory?

### ISSUE THREAD

**Issue by amilajack** [facebook/flow#2564]
I want to run flow recursively for all the files inside a folder without them having the `@flow` pragma. Is this possible?

**Comment by amilajack** [comment]
Also on a side note, what does the error `inconsistent use of library definitions` mean?

**Comment by gabro** [comment]
If your files only live inside a directory, place the `.flowconfig` file inside that directory then use the `--all` options of the server.

Start your flow server with

```sh
flow server --all
```

This will cause flow to typecheck all the files it can see, which (by default) are all the files included recursively starting from the location of the `.flowconfig` file.

**Comment by amilajack** [comment]
Is that equivalent to using

```
[options]
all=true
```
in the `.flowconfig`?

**Comment by gabro** [comment]
Yes, I believe that's the same option and I'm afraid there's not much you can do about the performance issue. 

There's some discussion going on about perf:
https://github.com/facebook/flow/labels/nontermination%20%2F%20perf but you can considering opening a specific issue for that.

**Comment by amilajack** [comment]
Just curious. What are the reasons for the performance issues?

**Comment by gabro** [comment]
I have honestly no idea. I only someone from the Flow team could answer that, like @avikchaudhuri.

**Comment by amilajack** [comment]
Great! Thanks.
