### ISSUE TITLE
Confusing error on intersection type property access

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#2570]
Given a lib def (or imported type) with an intersection type:

```
type T = {p: string} & {q:number};
```

and a file:

```
// @flow
declare var x: T;
var q: string = x.q;
```

Flow reports the following error:

```
test.js:3
  3: var q: string = x.q;
                     ^^^ property `q`. Property cannot be accessed on any member of intersection type
  3: var q: string = x.q;
                     ^ intersection
  Member 1:
    1: type T = {p: string} & {q:number};
                ^^^^^^^^^^^ object type. See lib: lib/core.js:1
  Error:
    3: var q: string = x.q;
                         ^ property `q`. Property not found in
    1: type T = {p: string} & {q:number};
                ^^^^^^^^^^^ object type. See lib: lib/core.js:1
  Member 2:
    1: type T = {p: string} & {q:number};
                              ^^^^^^^^^^ object type. See lib: lib/core.js:1
  Error:
    3: var q: string = x.q;
                       ^^^ number. This type is incompatible with
    3: var q: string = x.q;
              ^^^^^^ string
```

This error message "Property cannot be accessed on any member of intersection type" is confusing because the property `q` _is_ available on the intersection. The error reported (as Member 2) is because that property has type `number`, which we tried to assign to `string`.

At a minimum, we should give a better top-level error than "cannot be accessed." Ideally, we could replace the entire intersection error with just the error from Member 2.

cc @sebmarkbage

**Comment by gabro** [comment]
Probably related, this error is confusing too: 

Given a union type

```js
// @flow
type A = number | string
const a: A = "hey"
a.trim()
```

this is the error we get

```
foo.js:7
  7: a.trim()
       ^^^^ property `trim`. Property not found in
  7: a.trim()
     ^ Number
```

This leads to think that the type of `a` is `number` whereas it's `number | string`.

I understand the rationale of the error (`number` is the offending type of the union, i.e. the one missing the `trim` function), but I think it's confusing.

**Comment by samwgoldman** [comment]
Flow now gives a better error message:

```
Error: test.js:4
  4: var q: string = x.q;
                     ^^^ number. This type is incompatible with
  4: var q: string = x.q;
            ^^^^^^ string
```
