### ISSUE TITLE
Request: Add support for changing a Array<?type> to a Array<type> via 'filter'

### ISSUE THREAD

**Issue by oreqizer** [facebook/flow#2575]
Let's say I have the following:

```javascript
const maybeGet = (param: string): ?Object => param === "correct" ? { data: "data" } : null;
```

I want to fetch a bunch of those, that will give me `Array<?Object>`, then **filter** out those that don't match. That should produce `Array<Object>`. Say I want to do this:

```javascript
function fetchStuff(params: Array<string>): Array<Object> {  // NOPE, Flow shouts at me
  const maybeObjs: Array<?Object> = params.map(maybeGet);

  return maybeObjs.filter(id => id);  // all nulls will get removed
}
```

Would it be possible to permit something like this? Maybe some other neat way of replicating this behavior?

*Note:*
I managed to do this via **reduce**:
```javascript
function fetchStuff(params: Array<string>): Array<Object> {  // OK
  const maybeObjs: Array<?Object> = params.map(maybeGet);

  return maybeObjs.reduce((arr, obj) => {
    return obj ? arr.concat(obj) : arr;
  }, []);
}
```

but it's not really nice to do this all the time, when the *filter* verison is so much simpler.

**Comment by vkurchatkin** [comment]
This is possible already:

```js
const arr: Array<?{}> = [null, {}, {}, null];
const arr1: Array<{}> = arr.filter(Boolean);
```

**Comment by gabro** [comment]
Isn't this the same topic as https://github.com/facebook/flow/issues/1414?

**Comment by oreqizer** [comment]
ohhh thanks @vkurchatkin didn't try it that way. been using the `id => id` thing
