### ISSUE TITLE
Anonymous predicate function

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2576]
I think this should be possible:

``` js
declare function filter<T, P: $Pred<1>>(arr: Array<T>, p: P): Array<$Refine<T,P,1>>;
filter(arr, x => x);
```

Currently you get `Function is incompatible with abstract predicate function` and it seems that the only way to make a function a predicate is to use function declaration.

**Comment by vkurchatkin** [comment]
Never mind, this works: `filter(x, (x): %checks => x)`. But it would be nice if Flow could infer `%checks`

**Comment by samwgoldman** [comment]
That's the plan, ideally. Predicate support was started by @panagosg7 as an intern, and @avikchaudhuri has some follow-up work to land still. Stay tuned!

Ref #34

**Comment by calebmer** [comment]
Closing since I believe this has been resolved.

**Comment by vkurchatkin** [comment]
Well, my original example doesn't work.
