### ISSUE TITLE
Spread type inference fails in very specific case

### ISSUE THREAD

**Issue by JelteF** [facebook/flow#2578]
I might have found the root issue for some of the spread issues already reported (such as #2411). I've narrowed the bug down to a very specific case. Spreading property of `this` of a class that has no default value and should become a union type. The only place where an error occurs in the code below is the `FailingClass`:

``` javascript
/* @flow */
type Test = {
    id: number,
}

type TestSubclass = Test & {
    info: string,
} ;

type TestSubclass2 = {
    id: number,
    info: string,
}

function one(props: TestSubclass) {
    return props;
}

class FailingClass {
    props: TestSubclass;
    two() {
        return one({...this.props});
    }
}

class WorkingClass1 {
    props: TestSubclass;
    props = {id: 1, info: 'uueua'}
    two() {
        return one({...this.props});
    }
}

class WorkingClass2 {
    two(props: TestSubclass) {
        return one({...props});
    }
}

class WorkingClass3 {
    two(props: {a: TestSubclass}) {
        return one({...props.a});
    }
}

class WorkingClass4 {
    props: TestSubclass2;
    two() {
        return one({...this.props});
    }
}
```

It gives the following error:

``` bash
  6: type TestSubclass = Test & {
                                ^ property `info`. Property not found in
 22:         return one({...this.props});
                        ^^^^^^^^^^^^^^^ object literal
```

Maybe this helps in getting this fixed easier. I also wouldn't mind trying to fix it, but I would need a pointer on the place of the code base to look, because there is a lot of code and not really an easy way to find where to look.

**Comment by calebmer** [comment]
Sorry for the lack of inactivity 😔

We currently have correct support for object spread in types and we’ll be adding value spread soon 👍
