### ISSUE TITLE
Allow custom path schemes / absolute paths / path shortcuts

### ISSUE THREAD

**Issue by natew** [facebook/flow#2579]
I notice a few different schemes people are using to get around a lot of the horrible problems you get with relative paths. We were using this before flow:

``` js
import Button from '$views/button'
// desugars to point to the root of the app
import Button from '../../../views/button'
```

I think FB uses some unique file name scheme as well. Not sure if I'm missing an existing ticket, but it would be nice to be able to define schemes for custom imports. Webpack has a few weird ones, FB has their own, and I'm personally a big fan of the `$` method. This would solve one of the last big annoyances within our stack, which makes moving around files very cumbersome.

**Comment by asolove** [comment]
Hmm, so I know Flowconfig can do some things with require paths, like:

- [`module.system`](https://flow.org/en/docs/config/options/#toc-module-system-node-haste) to specify how to resolve `import`/`require` paths.
- [`module.name_mapper`](https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string) for rewriting require strings with regexes.
- [`module.name_mapper.extension`](https://flow.org/en/docs/config/options/#toc-module-name-mapper-extension-string-string) for configuring what to do with imports of other file extensions.

That said, I do really wonder how Facebook use their custom require resolution in Flow. I see that `module.system` only allows Node and Haste, and the Haste site says it's no longer used at Facebook. It would be nice to know how they have gotten it to work, even if the rest of us would have to rebuild something, just to know what path is likely to keep working.

**Comment by dgcoffman** [comment]
I too would love pluggable module resolution. 

Webpack allows this with resolve plugins, but we can't use that because flow doesn't understand it!

**Comment by SamChou19815** [comment]
The options described by asolove is the way to do it. We won't support arbitrary module resolution algorithm though.
