### ISSUE TITLE
Type error in shouldComponentUpdate when specifying nextState

### ISSUE THREAD

**Issue by jviereck** [facebook/flow#258]
When running the flow type checker on the following code example, I get the following error:

``` bash
/Users/jviereck/develop/flow_check/index.js:11:18,33:2: optional state of React component
This type is incompatible with
  /Users/jviereck/develop/flow_check/index.js:7:14,9:1: object type
```
Input program (the error is caused by the `shouldComponentUpdate` method):

```js
'use strict';

/* @flow */

var React = require('react');

type State = {
  fileContent: string;
}

var FileEditor = React.createClass({
  propTypes: {
    filePath: React.PropTypes.string.isRequired
  },

  getDefaultProps: function() {
    return {
      filePath: '#NotSet'
    }
  },

  getInitialState: function() : State {
    return {fileContent: ''};
  },

  // NOTE: When the `nextState` argument is removed, the type checker is happy.
  shouldComponentUpdate: function(nextProps: {filePath: string;}, nextState : State) {
    return nextProps.filePath != this.props.filePath;
  },

  render: function() {
    return (<div>SomeOutput</div>)
  }
});

React.render(<FileEditor filePath="foo" />, document.body);
```
Is this a bug in the flow type checker or am I doing something wrong with the state type here?

**Comment by gabelevi** [comment]
We expect the 2nd and 3rd arguments to `shouldComponentUpdate()` to be optional ([see here](https://phabricator.fb.com/diffusion/FBCODE/browse/master/flow/lib/react.js;96b007669312cc62fd931f3733461bcc81fc773f$42)). Try this:

```JavaScript
shouldComponentUpdate: function(nextProps: {filePath: string;}, nextState? : State) {
  ...
},

**Comment by jviereck** [comment]
Thanks a lot @gabelevi, that makes sense - closing this comment.

PS: This might be out of scope of this issue, but do you think the error message could be improved? The "optional state of React component" makes now sense to me after reading your reply, but it was not clear to me before. Maybe change it towards "Expecting optional argument of type 'state of React component'/nextState? This type is incompatible with the provided type".

**Comment by gabelevi** [comment]
Glad to have helped!

The error message is a symptom of a larger problem that we have around error messages. The way that types flow throw Flow's algorithms make it a little tricky to decide which locations & reasons to show in an error message. @bhosmer is currently working on this problem so hopefully these messages will improve soon!

And thanks for offering to help! We'd love all the help we can get, though at the moment working on error messages & locations might conflict with what @bhosmer is working on. I'm always happy to help if you want to get your hands dirty on something else!
