### ISSUE TITLE
A simple way to create object type with covariant properties

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2580]
It would useful to have a simple way to create object type with covariant properties from object type with invariant properties or vices versa:

``` js
type Foo = {
  bar: string,
  baz: number
}

type FooReadonly = $Covariant<Foo>
// the same as

type Foo = {
  +bar: string,
  +baz: number
}
```

This way one can thinks about covariance only when declaring functions, not data types.

**Comment by samwgoldman** [comment]
You're jumping the gun, @vkurchatkin! We haven't announced property variance yet ;)

This kind of work is definitely on our radar. Property variance is the first step. Will use this issue to track that effort.

**Comment by TrySound** [comment]
$ReadOnly is available
