### ISSUE TITLE
Destructured parameter list not validating when `?` found

### ISSUE THREAD

**Issue by TheOpenDevProject** [facebook/flow#2581]
**Sample Code**
```javascript
    export class SampleClass{
        constructor({paramOne: string, paramTwo? : number = null}){
        }
    }
```
Both of these scenarios cause an issue when validating even though they should pass validation as this is valid ES6 syntax.
```javascript
    export class SampleClass{
        constructor({paramOne: string, paramTwo? : number}){
        }
    }
```

Not sure what causes this but it's completely stopping me using flow.

The exact error is 
```
 ^ Unexpected token ?
```

**Comment by gabro** [comment]
You're mixing up ES6 deconstrutor syntax and flow type annotations. Here's an example using the correct syntax

```js
export class SampleClass{
  constructor({ paramOne, paramTwo }: { paramOne: string, paramTwo: ?number}) {
  }
}
```

**Comment by gabro** [comment]
Note that this doesn't typecheck, probably due a bug tracked here: https://github.com/facebook/flow/issues/183

```js
export class SampleClass{
  constructor({ paramOne, paramTwo = null }: { paramOne: string, paramTwo: ?number}) {
  }
}
```

This is a reasonable workaround that typechecks:

```js
export class SampleClass{
  constructor(params: { paramOne: string, paramTwo: ?number }) {
    const { paramOne, paramTwo = null } = params; 
  }
}
```

**Comment by gabro** [comment]
Final note, there's a difference between `{ paramTwo?: number }` and `{ paramTwo: ?number }`. The former has type `number | void`, the latter `number | void | null`.

You can learn about the difference here: https://flowtype.org/docs/builtins.html#null-and-void

**Comment by TheOpenDevProject** [comment]
This is horribly documented then. I would actually have never guessed that is how I was meant to do that. Thanks for the help though much appreciated.

Closing.

**Comment by gabro** [comment]
@TheOpenDevProject I agree the documentation is not stellar. It's quickly mentioned here https://flowtype.org/docs/syntax.html#destructured-bindings but since it's very confusing, this should be more explicit

**Comment by gabro** [comment]
See also the discussion here: https://github.com/facebook/flow/issues/235
