### ISSUE TITLE
Many of the DOM type declarations should be structural types.

### ISSUE THREAD

**Issue by cameron-martin** [facebook/flow#2584]
Many types defined in [lib/dom.js](https://github.com/facebook/flow/blob/6f5b8dd3e906d856037fa28b1966e46f64119ad5/lib/dom.js#L101) are nominal types. This makes it hard/impossible to construct test doubles for things of these types.

Also, in the DOM spec most of these are defined as interfaces (e.g. https://dom.spec.whatwg.org/#eventtarget), which seem to match best to structural types in flow.

Would there be any disadvantages to changing these to be structural types?

**Comment by calebmer** [comment]
If you want to use test doubles we recommend you first cast to `any` and then cast to the nominal type you want 😊

**Comment by cameron-martin** [comment]
What's the reasoning behind not having them as structural types?

**Comment by calebmer** [comment]
Because they aren’t structural at runtime. You wouldn’t be able to insert an `HTMLElement`ish into the DOM.

**Comment by cameron-martin** [comment]
Good point.
