### ISSUE TITLE
Unwrap Polymorphic Types?

### ISSUE THREAD

**Issue by skevy** [facebook/flow#2585]
Hi there -

I was chatting with Marshall and Avik yesterday about a potential feature possibility for Flow, and they wanted me to make an issue to open the discussion, and to cc @samwgoldman :-p.

@ericvicenti and I were working on some navigation related things for React Native, and we had an interesting use case that we wanted to Flow type. I've provided a simplified example here: https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAEEaGOADsAKnzIAeCQD4wAXjAASANJkeAZznyuqXvyEjxe5WADeqMGCNkAXCcKjJ0vQBpUAXwP3nrgDiZGJk+BSEBADC4lAYAOYW1rYA2gDWWk7ahPgYYvEAuk4AFACUyooAbnAYACZe3tzSYADKkazmKslgtRjaOBFUABYl1C7iTsLjYnrlSlU19T5NxlOu2kk2YOmZYNm5+UVgAPwA8gBGAFZkNA3oUACuYqZiYPEhYRFka+K6UZMvYKhcLtGJiOLxeTFKixBJOKLlSyNVDAVFo1HoGFibJgCg-bEWd7Ar747TFbriRxgMoVKzeLy2QgIOAlOaKJENUoGLE486kwkfEHfF5k7qEIasKk0+Z0hlgKBwB74Vm0jk+LnoVF7BhkIaIMBPBDhHBgPAwHhYAg4IYYKh2ZpDMJkFHAe2rHA4fFSfgbFSqACqYiNFBwMjxIsUAB81IHg6G+RHNei0IZmgAFeg4X1WLbZAhUtr5mSCD1e6TaeR3VBUGAUbQbFo6mK4SliYhkAAehBCtQ25DGADpm3hQm2c7YcJntE4M3AswZbLU4I2sGRxXl4jTurYtS09Q8YLUwOcBJUKDA6qgAJDr7QDydzu951gD3r9QZDclbWyM6ROJjipKTByrY3gaj+YDfleu77oeYBhPQ+DfnYNp3g+WYDs+ZCvn0AyEMMX4Qb+-D-toOrrvkwHIWBXCgcsqBAA

The gist is that `generateActions` is a polymorphic function, and we want to be able to generate a new type alias, in this case `AppActionTypes`, based on the inner polymorphic type of `generateActions`. This isn't possible today, but the conversation we were having yesterday implied that you all may like to see this be possible in the future :)

cc @mroch @avikchaudhuri @ericvicenti

**Comment by mroch** [comment]
this looks like it might work:

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAEEaGOADsAKnzIAeCQD4wAXjAASANJkeAZznyuqXvyEjxe5WADeqMGCNkAXCcKjJ0vQBpUAXwP2wAMqEBLIKFta2ACYY2jgUhFQAFk4AFNQu4k7CGWJ6AJTKigBucBiRXt7c0s6u2uE2YADaANZaTtqE+BhiAOYAuk4A-ADyAEYAVmQ0FehQAK5ipmJgPWRiZPjxZNm1KVTiUBg9BZaVqMAXlxfo+2IdYBQAwgdH9bbijmApBUqKp162QgIOCpH5-bwVLi3e4UHbiOoqVbrTaEbZLbRpZ5iQ7HAzQ4ijLE4t52RKsT7fQpWCENKBwOb4UFU-4+KHwglwu4WJEbLacjGEl64qrGQQ4HCcqT8BF2aRwKAPImvABksv48rAguxR3QV2uhmqAAV6DgZREwB0Qk4giEZGKJUspWRtPIZqgqDAKNo6gEGGRnrgPmJiGQAB6osSROrkdIAOgDeHWwasDRwJu0TmNcFNBiicF9WDIhES3R6lPNtgugUS9JgkU1AiKFBgZVQAEhizFY2ns9pY5bWLHorF4kkUhXbGrPkxi+SmADJ948lxJ2AGmA21WAjW5nWwBt6Ph16Suz3Tf3goPh3EEolx8fAdInExtH7O7158elyuwJUzkA

but it would still be interesting to see if we could get `aAction` to carry around the config's type in a way that is extractable, so you don't have to assign it.

**Comment by mroch** [comment]
this is a little closer:

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAEEaGOADsAKnzIAeCQD4wAXjAASANJkeAZznyuqXvyEjxe5WADeqMGCNkAXCcKjJ0vQBpUAXwP2wAMqEBLIKFta2ACYY2jgUhFQAFk4AFNQu4k7CGWJ6AJTKigBucBiRXt7c0s6uumEqEWAA+k1U4lAYAOYtThJetgDaANZaTtqE+BhinQC6TgD8APIARgBWZDQV6FAArmKmYmCdZGJk+PFk2bVyTivrNPIpbWIdnb15WQd1io2shDv4Q6NACQLWerx6YHBXX6tjAwGAYBwMB22jACESFyKZzArAoMDAIx0YB4cB2YFOZEiNjAvh86ARjMZ6Ge4zAFCu4jRKmOp3OhEuXxSjXEjjAKQKSh+3lhhAQcFSkulFTyBlZxGWnLE3KOJzOFy12mFNMIiVYYolhSsMppUDJ+EVVssNu8qqqxkEOBwWqk-B19jgUHZhoAdGD2l0WmAAGR2aSBsCar5h1oR7pNBmMsASRIxdkwbRwdEEIZohAYU1k4iYopTTp2IvUKhkbRo8MvSNNDyJnbEACSYBrJyYtDJYki7PRFB4DYpcGIlIn7YhTRJZEIIbAfcIqCZUK5EwoUzRpoE-gTEjAUxqXL0u8R-iaAFUxAhzjgAMJpmRP7sST45LoT7yIoKhPvecbGC+b4UJ+371M00Hvl+HadDIIB-vIEH+J63oHL6LYWEhsEoa8MgBkGHJfIosbEXBqHkfGQZJoBWH3ky7oCAACvQOA6o04whE4QQhDIuE+tI2jyFsqBUDAFCtoEDBkF+uCimIxBkAAHgK45ouQ6QhqpeCnBpVg0jgvHaE4PFwHxBhRHAATKaadaWo0tgIoEiRkjAE7LAIRT4mUqDAq52ghpZdkRYJrAhtEsTxEkxpwnC9hOEwopMLCtiulwqXhZFVkhrFZDxTEcQJIkKWpZBYojmaZBkNlNK5W6qWtcCXkBD5Ox+WAZz0PgrV2LmEVRXxJXBHFCWVclHlpdIGWFlg665tMLWpXlNKVJUqBAA

but the `__config__` thing is still not ideal.

**Comment by gcanti** [comment]
@mroch the `__config__` seems to implement a kind of phantom type for dictionaries. What about using an actual phantom type?

[https://flowtype.org/try](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdyuAnhkaAIIUqwA7ADwAVAHygAvKADeiUKHacAXKAAkAaSJsAzqLGIAvgG5WHLr1z8BAcSICi2ErhwBhQZBQBzKbPmgAbQBrbVUdXGwUAS8AXVUACgBKKQkAN1gUABMjU0QlLgBlF0Z9XzkFTJQdDGcyAAsE8itBVUtrfWTJNIzMgBocs04ePkE9DQlpcsCQtlUNONAAfgB5ACMAKyIKAcRMregSRlAyA50dUAAFOpIBFzR3AU8vIVcJGUNkPZPDrkgAVwEIwEoC89kcziIbVGL1aQLsDicxQeTzE8TIHm8qlciVhzQEek02j0rwkADJLtdbjRkd4XmJcuj8fgSFD8b5QQiIaydPEpoIiAlOm9DP0FLh4LBBSlZB9DIlkIzwqBVtz2WDEZCgTyprg6owBaAktL3qLQJBYH9sFKujKjPK8uZQAB9ACqAngTgwQm4vVAACFVFcbncac9uGIJjxTPlQG6PSQvX7I673Z6hAAqX1J6OO7gYDCskTmc7SONp-KwSCgFlasmx1MJoQVqsq2u5GMXagYEt+BThHAGooD735wvFgwmZBEAAeWDwx1O5wKNCI7kw-NuoBnuHsmXOxCaADo11gHJuphguzpA1fchVYMu0ERdVEvEapgoQKACnULdBMsqXCpCQ0BZP4Yp1FUh6XrA3aHv2jCHpU1S1HUvLgQoijmKodD8iwmGgHKGEvjo0FXvBxREEhVQ1Lg9ToQRYrYfQur6vhmFERhX4-n+AGONQ2DEZBpEwXBCFUchtH0R+mH5DhOgri+0TsQoRGqUYyCIEAA)

**Comment by skevy** [comment]
@gcanti that's killer. I'm almost there.

I have a different example (that's doing a very similar thing to the above), and I've used your example as an outline.

[https://flowtype.org/try](https://flowtype.org/try/#0PQKhAIAEDMBsHsDu4zAFBoCYFMDGsBDAJ23HwIGcLwAFACwIDsAXeAWwFkBLIo+IgDwBhAHzgA3gF80zAJ4AHUt179smANLZZFAQBUxAXglpw4ANoBrLQC5wAEk3a9IgLq2HWnfrSSA3BmgAV0ZcZi54RnArWWU+QV1bcUsbcApmIi5GAHM3cEZA2FhJEQAKaIB5ACMAK1tdAEpbWNUNT2dwADJaBhZ2ZvixcRNwEmZAokiq6rxmADpoijKtKfrZkkxA3GwSkrYeOIAaKK168ANB4dM9lSJk2Rcz49l-U1NR8cjruJfwSSOpmazXAkAjMbb5Qr1er+aQyBSkAD6AFVGIgiAR5AIAIJHABCtnoTFYnH2-GxIkM4Cx-jkinAKLRGIEuMpyNR6MxIDxIn8aGwAA95PxmGQImkqaFwoxdPDqEZov0SkNTAAZcoAcQAkgA5WwQ2AHHzQjACoVEEW00hYyURGWKAAi2GgjwZHIElvgzutYVtsp5GEt4HtXAo8lBuDo2MS4Et7gAyoFKpaBGkMtkxMVHiUCDbGLYsadzlTeYG46wSO0jMrwJgQ2HmBHbMHQ+HI-pDdJXl3uz24XTvVLK8ZTLH7I4vCIjj5Lj3Z6YsHhCCRwAA3YipcvYWxl1TY3N7n3S+GO6AU3lpVSzWstht0JUx+G2ADkaq12qfv1OwGAqTo8AKmB5PAIrYDcRzquU5T2gAhGgF4kFedatveo4vhqOoAEwfpIX4-hQf4AeAoGHOAEFQbB8HYIhN4Rihj4SoedrYBQsyvjqn6+OA36-v+sCAYwwFEWBpGQTBQA)

What do you think about this?

There are two problems:

a) The actual `keyMirror` function doesn't type check, because I don't return a type that matches `PhantomMirror<T>`. Any ideas here?
b) When I `export const ActionTypes`, rather than `const ActionTypes`, it gives an error that says "type parameter T of function call missing annotation".

IF we can solve those two problems, I will be happy (and simultaneously amazed at the wonders of Flow).

**Comment by skevy** [comment]
Ok, I fixed b):

[http://flowtype.org/try](https://flowtype.org/try/#0PQKhAIAEDMBsHsDu4zAFBoCYFMDGsBDAJ23HwIGcLwAFACwIDsAXeAWwFkBLIo+IgDwBhAHzgA3gF80zAJ4AHUt179smANLZZFAQBUxAXglpw4ANoBrLQC5wAEk3a9IgLq2HWnfrSSA3CfAZBVJHZT4iACVsCgBXWGZncCMw1Q1PRIAyWgYWdhTBfX80aBjGXGYueEZwK1l8vVtxSxtwCmYiLkYAczdwRjjYSREAClqAeQAjACtbXQBKW1CecKjY+MTxAJJmGKJqyam8ZgA6WopRrQO545JMGNxsYeG2Zf4AGhqtOaSxTdNTF4qIjNWQuJKfWT+f7gba7aqA8JQ8CSD4HI7HXAkAjMR79WCwOZzfzSIKKcAAfQAqoxEEQCPIBABBD4AIVs9CYrE4r0EjJEhnAjP8cjJ1Np9IELIFVJpdIZIFZIiK2AAHvJ+MwyFU2oLypVGLpghRFlp8qs4gkQALavlhn9wAAZMYAcQAkgA5Wx42BvHxEjCq9VETUi0iMvVVQ2KAAi2Gg4LFcoEofg8fDFUjRqVGFD4GjXAo8mxuDoTMa4FD7gAyjEJqGBG0Ot0xENwcMCBHGLZGd8DGIhTnguAq6wSIkjPbMAWi8wS7Z84Xi6X9L7pND1xv-qSw53x8ZTJX7I4vCIPj4ApvL4EcOQSOAAG7EVqj7C2EeqJm79P6qPYWPQfkijaVRjinRdZzoO0K2CWwAHInTdd1YORb5gGAVo6HgOJMD6eBNWwIEPmdMYxmjABCNBgJIUDpyXKDD3gl0PQAJmQyRUPQihMOw8ACPCIiSPIyiXxo8CS3omDdQzA0jWOBCPRQ3xwDQjCsNgHDGDw3jCPAYjSLIoA)

Still lost on a) though.

**Comment by vkurchatkin** [comment]
You can't really implement phantom type, you have to cast to it via `any`

**Comment by skevy** [comment]
That works! Thanks @vkurchatkin!
