### ISSUE TITLE
Flow is slow, and then produces unexpected results

### ISSUE THREAD

**Issue by jeffmo** [facebook/flow#2586]
Over in https://github.com/flowtype/flow-typed/issues/310, @joewalker reported the following.
I'm opening this issue to effectively move that one here.

---

---

Running flow recently started taking 10 / 20 minutes to produce results (with one CPU core maxed out all the way), and then the results it produces seem incorrect.

Some Flow errors that I would have been expected to have been caught are not. As an example below, I have been expecting an error in a IndexedDB call (this is commented out for the time being) but the expected error doesn't happen, so an error is reported.

```
time npm run flow

> project@1.0.0 flow /path/to/project
> flow; test $? -eq 0 -o $? -eq 2

Launching Flow server for /path/to/project
Spawned flow server (pid=35424)
Logs will go to /private/tmp/flow/zSpathzStozSproject.log

...

storage.js:99
 99:         // $FlowIssue: The flow definition of db.transaction seems wrong
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Error suppressing comment. Unused suppression

Found 8 errors
npm run flow  0.48s user 0.31s system 0% cpu 9:50.41 total
```

Also during this run:

flow_typed/test.js:

```
declare type Test = string;
```

someCode.js:

```
import type { Test } from 'test';
const t: Test = 6;
```

---

---

When run with --debug, I get this:

```
Worker interrupted with signal: sigill
Failure("Subprocess(55914): fail 2")
```

---

---

So I've narrowed down something that causes this. The problem goes away if I remove the call to `data.update()` (see the removeInfo function), or if I add a type declaration to the `let data =...` line.

```
// @flow
import * as Immutable from 'immutable';
import fs from 'fs-extra-promise';

let data = Immutable.Map();
// The problem with the data.update call below is fixed by adding this
/* Immutable.Map<string, Object> */

export function removeInfo(id: string): Promise<void> {
  data = data.removeIn([ 'thing', id ]);
  // Something about this causes the problem
  data = data.update('email', email => {
    return email.map(ids => ids.filter(thisId => thisId !== id));
  });
  return save();
}

async function save(): Promise<void> {
  const dataFile = ...;
  const output = JSON.stringify(data, null, '  ') + '\n';
  await fs.writeFileAsync(dataFile, output, { encoding: 'utf8' });
}
```

**Comment by joewalker** [comment]
Thanks for re-raising this. I could probably resurrect the circumstances of this problem if we needed to investigate.

**Comment by hmeerlo** [comment]
Similar problem here, very annoying because I thought I had no errors (as reported by the flow binary) but now I know for sure that there must be errors, but they are just not reported:

```
[2017-01-20 16:20:22] Initializing Server (This might take some time)
[2017-01-20 16:20:22] executable=/Users/hmeerlo/Dev/jbkantoor/node_modules/flow-bin/flow-osx-v0.38.0/flow
[2017-01-20 16:20:22] version=0.38.0
[2017-01-20 16:20:22] Parsing
[2017-01-20 16:20:30] Building package heap
[2017-01-20 16:20:31] Loading libraries
[2017-01-20 16:20:33] Running local inference
[2017-01-20 16:20:39] Re-resolving directly dependent files
[2017-01-20 16:20:39] Calculating dependencies
[2017-01-20 16:20:39] Merging
Worker interrupted with signal: sigill
End_of_file
[2017-01-20 16:20:48] Server is READY
[2017-01-20 16:20:48] Took 25.802131 seconds to initialize.
[2017-01-20 16:20:48] Status: OK
```

**Comment by calebmer** [comment]
Closing because of the lack of activity on this issue 😔

This should be fixed in the latest version of Flow. Let us know if it is not 👍
