### ISSUE TITLE
Exact Object types don't work for autocomplete

### ISSUE THREAD

**Issue by nmn** [facebook/flow#2588]
Minor bug I noticed.

When a variable is annotated with an exact object type, typing a dot does not suggest the keys on it. Changing the type to an inexact type fixes it.

Tested in Atom with `autocomplete-flow` and `nuclide`.

@jeffmo

**Comment by gcazaciuc** [comment]
Same also for type-at-pos . As soon as an object is declared as exact type at pos(hover info) stops working. Tested it both by running manually type-at-pos in terminal and also in vscode using vscode-flow-ide extension.
