### ISSUE TITLE
Generator.return() doesn't account for yield or return inside finally

### ISSUE THREAD

**Issue by jesseschalken** [facebook/flow#2589]
Currently this code passes, but the `.trim()` call fails at runtime because the generator actually refused the return and yielded its own value inside the `finally` block, causing `x` to be the number `2` instead of the string `'hello'`.

```js
function *foo(): Generator<number, void, void> {
  try {
    yield 1;
  } finally {
    yield 2;
  }
}

let f = foo();
f.next();
let x = f.return('hello').value;
x.trim();
```
```
TypeError: x.trim is not a function
```

The definition of `Generator` is currently:

```js
interface Generator<+Yield,+Return,-Next> {
    @@iterator(): $Iterator<Yield,Return,Next>;
    next(value?: Next): IteratorResult<Yield,Return>;
    return<R>(value: R): { done: true, value: R };
    throw(error?: any): IteratorResult<Yield,Return>;
}
```

The result of `return` assumes that the generator doesn't refuse the return using `yield` or `return` inside a `finally` block, and the provided value is what is returned.

To account for a refused return, `return` can be changed to:

```js
//..
    return<R>(value: R): IteratorResult<Yield,Return|R>;
//..
```

which accounts for all three possibilities:

- The generator does a `yield` inside the `finally` block, resulting in `{done: false, value: Yield}`.
- The generator does a `return` inside the `finally` block, resulting in `{done: true, value: Return}`.
- The generator accepts the return and the returned value is the one provided, resulting in `{done: true, value: R}`.

**Comment by samwgoldman** [comment]
Thanks for the report! I'll take a look...
