### ISSUE TITLE
Egghead

### ISSUE THREAD

**Issue by sandysaders** [facebook/flow#2595]
Hello,

I've recently have seen the flow team (@thejameskyle) pump out great articles for the community at large and have been doing a solid job at selling developers on why they should flow in their applications. I've seen the community write articles on their experience and how they made redux actions amazing and a bunch more. However I'm more of a visual learner and learn well from videos like the ones on egghead.io . Is there anyway the flow team could maybe make an egghead course for those people like myself that really excited about flow?

**Comment by jeffmo** [comment]
I'd love to see @thejameskyle do something like this -- there seems to be quite a few people interested and asking for it.

What do you think, James?

**Comment by thejameskyle** [comment]
Egghead has been asking me to do a video series for them for a while now, I've just marked it as a lower priority thing for now since it's going to take up a ton of time. I can do it if people think I should though

**Comment by kennetpostigo** [comment]
This would be amazing!

**Comment by vitorbal** [comment]
@thejameskyle this would be awesome. I love your [medium article series on type systems](https://medium.com/@thejameskyle/type-systems-reachability-and-exhaustiveness-analysis-3d9692c399#.xk4a7g76h) and I think you could translate those into episodes for the video series too. Maybe some "advanced topics" episodes at the end?

**Comment by trevordmiller** [comment]
@thejameskyle That would be awesome! I love articles and docs but I learn the best from screencasts. Egghead is fantastic to work with.

**Comment by johnstew** [comment]
This would be great! Docs are helpful but videos like these really make it easier for people to digest content quickly.

**Comment by sstur** [comment]
Yes please! Totally do it!

**Comment by chrissm79** [comment]
This would be fantastic!

**Comment by avanslaars** [comment]
Egghead videos FTW!!

**Comment by mbilokonsky** [comment]
Do it, Egghead is awesome people and you'll reach a large audience! :)

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
