### ISSUE TITLE
static class properties conflicting with CommonJS exports

### ISSUE THREAD

**Issue by amilajack** [facebook/flow#2597]
Not sure if this issue has already been opened. I did a quick search for `static common` but nothing relevant seemed to show up.

Here's the issue:

```js
// Assume each module should be in different file

// Module 1
export default class Some {
    static test() {
        return 'some';
    }
}

// Module 2
export default class Foo {
    static test() {
        return 'some';
    }
}

// Module 3
export default class Moo {
    static test() {
        return 'some';
    }
}

// Module 4
const examples = [Some, Foo, Moo].map(each => each.test())
// Property `.test` not found in CommonJS exports of './Moo'
// Property `.test` not found in CommonJS exports of './Foo'
// Property `.test` not found in CommonJS exports of './Some'
```

This is an abstracted version of the scenario. [Here's where I'm actually experiencing it](https://github.com/amilajack/popcorn-time-desktop/blob/ui-design-implementation/app/api/torrents/TorrentAdapter.js#L40).

Also I should note that this is the options section of my `.flowconfig`
```
[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
esproposal.export_star_as=enable
```

Ideas?

**Comment by samwgoldman** [comment]
How are you bringing `Some`, `Foo`, and `Moo` into scope in Module 4?

**Comment by amilajack** [comment]
I'm importing them like so:

```js
const providers = [
  require('./Some'),
  require('./Foo'),
  require('./Moo')
];

const examples = providers.map(each => each.test())
```

**Comment by samwgoldman** [comment]
There is no standard (currently) for interop between ES modules and CommonJS modules. Babel has implemented one method and Flow follows that. When you import a ES module using CommonJS `require`, as you've done here, the default export is available as the `default` property on the imported object. This is because, unlike ES modules, CommonJS modules don't have a separate default and named export. Everything is part of a single object.

**Comment by amilajack** [comment]
I see. So I guess we'll have to wait for some kind of standard. Thanks!

**Comment by samwgoldman** [comment]
You can do `require('./Some').default` currently, but if you can control it I would recommend using ES module syntax on both export and import side.

**Comment by amilajack** [comment]
On a side note, is there a way to tell flow to force static typing? Also why does flow allow this:

```
const some = true + 13
```
