### ISSUE TITLE
Disjoint union without tags

### ISSUE THREAD

**Issue by almost** [facebook/flow#2603]
I have a union type where each option is an object with non-overlapping properties, no "type" tag. In previous Flow versions I could check for existence of the relevant property and Flow would seem to narrow the type and everything would work.  In the latest flow (0.33.0) I get an error.

Here's the code:

```
/* @flow */

export type Leaf = {};

export type Node = { leaf: Leaf } |
                   { and: Array<Node> };

let x: Node = {leaf: {}};
if (typeof x.leaf !== "undefined") {
  let y:Leaf = x.leaf;
}
```

And this is the error:

```
10:   let y:Leaf = x.leaf;
                   ^ property `leaf` of unknown type. This type is incompatible with
10:   let y:Leaf = x.leaf;
            ^ object type
```

([Try flow link](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAGQwEMowBeMAbwF8BudbPIk8ygDk4AE0rMWYGHSgAuajLBswAH1RgNmrdq2TaAOxHyAgvny1SAHmFiAfEq6ppxLPJvjW0+vPadUASwYACjIKOAYsADovBgBCRmYAIgBXQwwof30MEUSASlZ1KQxiUlkaeiYwKJiuNlQgA))

Is this meant to work and if so how can I make it work?

**Comment by vkurchatkin** [comment]
Why should it work? Type of `spec` is not defined anywhere

**Comment by almost** [comment]
Sorry, I was renaming things in the example to be more generic and didn't rename all. Will edit and fix it

**Comment by calebmer** [comment]
Currently it is not meant to work and we recommend you use a string literal type to turn your union into a discriminated union 😊
