### ISSUE TITLE
Flow in Atom

### ISSUE THREAD

**Issue by kennetpostigo** [facebook/flow#2604]
I'm currently using flow in a few projects and really enjoying it. I'm using flow in Atom with Nuclide to get the type hints and errors in editor. However Nuclide seems to be pretty heavy package for atom and it really really slows down my computer, when several files are open atom will hang and just be unusable. Nuclide is great if your putting it to good use but at the moment I feel like I use Nuclide for flow only and its really overkill. Is there a standalone package for getting flow hints and errors in editor for atom? I know @thejameskyle has been working on editor plugins for popular editors not sure if theres an atom package.

**Comment by iamchenxin** [comment]
There is a standalone flow plugin for vscode.
But maybe you should got a SSD for your linux. to deal with thousands fragment files in a big project.

**Comment by kennetpostigo** [comment]
The vscode plugin doesn't seem to support on windows machines as far as I've tried it. Do you know if theres been an update for that haven't tried it in a few weeks.
