### ISSUE TITLE
Unable to check type for union types?

### ISSUE THREAD

**Issue by zhangchiqing** [facebook/flow#2605]
I'm writing the type definitions of a `Maybe` type for [`sanctuary.js`](https://github.com/sanctuary-js/sanctuary). 

This is my `interfaces/sanctuary.js` that is included in `.flowconfig`

```
declare module sanctuary {
  declare export type Nothing = { isNothing: bool, isJust: bool };
  declare export type Just<R> = { isNothing: bool, isJust: bool, value: R };
  declare export type Maybe<R> = Nothing | Just<R>;

  declare class Sanctuary {
    Nothing(): Nothing;
    Just <A>(a: A): Just<A>;
    isNothing (a: Maybe<any>): bool;
    isJust (a: Maybe<any>): bool;
    fromMaybe <A>(defaultValue: A, maybeValue: Maybe<A>): Maybe<A>;
    maybeToNullable <A>(maybeValue: Maybe<A>): ?A;
    toMaybe <A>(a: ?A): Maybe<A>;
    maybe <A,B>(b: B, aTob: (va: A) => B, maybeA: Maybe<A>): B;
    justs <A>(maybes: [Maybe<A>]): [A];
    mapMaybe <A,B>(fn: (a: A) => Maybe<B>, as: [A]): [B];
  }

  declare function create (options: any): Sanctuary;
  declare var env: [any];
}
```

With the following code in a `S.js` file, I expected to throw type error, but it didn't
```
// @flow
import type { Maybe, Just, Nothing } from 'sanctuary'

var sanctuary = require('sanctuary');
var S = sanctuary.create({checkTypes: true, env: sanctuary.env});

// expected to throw error, but got no errors.
var justAMaybe : Maybe<bool> = S.Just(1);
```

```
> flow; test $? -eq 0 -o $? -eq 2

No errors!
```

However, if I change `Maybe` to `Just`, it can find error
```
// @flow
import type { Maybe, Just, Nothing } from 'sanctuary'

var sanctuary = require('sanctuary');
var S = sanctuary.create({checkTypes: true, env: sanctuary.env});

// can find the type error
var justAMaybe : Just<bool> = S.Just(1);
```

```
> flow; test $? -eq 0 -o $? -eq 2

S.js:7
  7: var sm : Just<bool> = S.Just(1);
                                  ^ number. This type is incompatible with
  7: var sm : Just<bool> = S.Just(1);
                   ^^^^ boolean


Found 1 error
```

Can I get any advise what I'm doing wrong here?

**Comment by iamchenxin** [comment]
Here it is [flow try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSApAVwGdSAVKrAHgCUA+MAXjABvMAEsGAOTikAFiIB2AcwBcYAEZw4MADSiG9JivWadAN3ww6WFZzABfANzpseIiSh05OUiLhyw+0jB2AEFuAAp8FWCAShUA1mp2EG5HZwJiMHdPb19-RlIAJiDgnR4IqNi8pgSOHkdUM0IwBgBbMDj8mvYjGF4BALCARmjHRua2juq2bo1e-irCoZGgA)
```
/* @flow */

declare type JustType<R> = { isNothing: bool, isJust: bool, value: R };

declare function Just <A>(a: A): JustType<*>; // use a * to infer
declare function Just2 <A, R>(a: A): JustType<R>; // or explicitly write a polymorphic type.

var sm : JustType<bool> = Just(1);
var sm : JustType<bool> = Just2(1);
```
I think the Flow type and the function share a same name will cause confusion. (So maybe i have some misunderstanding for your code ).

**Comment by iamchenxin** [comment]
[flow try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoMYAmBTAxjAQwCdsMAXATwAdSA5OMgCwEsA7AczAF4wBvMZgGd6TNuwBcYAEZw4MADQDBAKQCugspJlywAXwDc6LHkIly1Umo0AVCwB4ASgD5ufJSJYctshUqubpH0UANwIYVWxJBz1DDBx8YlIwShowAFkCCilsRxceDzEwAB8wf1saXMMjeNNSBMFBMABlAlZcMlViCj4jDAKOAAoASkl+9liMUvUyMDsAQScBgkk5kambewWJjCExsCXJDKyc1oonNe0Ybb9p-eX0zOy7U-PvOWuoIjgAWyPs2YWAxwUAIqhgZAAamEIitFN9HtgoeFIg9jvNXqinltemB4cdrHBaGDCFIYKR0QM8dkkTDMTkFmsAPxza5kOB-cmA+7MtYc9HXKmc+QAIUWUkkwsUBAJ4v2oRWQ24LkluIRc0OCPRa2F1wAVtNGhTBYJJABtPkLAC6a1Nc0tAoIVA5AJFiygrEkBzAqyVdLsoqlJrAtutZuF9qMulQ1RMiTAUFUbTIzDgrDAuBIBDIpAGcCoydTQdOaxaSc6RAoExqcdCRDA2FYwTNpwjqGrZlrYEErUkpfa5crqGAwHrAA8aO1sJhknBkowvkhsEQvkRFFJVDN2AwwKxZ0uV4IAHSoTv6jRzZ0atEaIhiPJd1qH-wDACMQ0MncwL-Eex4Z7IF4IoYw5gJ+ABM4hlPYN53q4-6Acc+hgCB+5wHWjBLtgQA)
```
var justAMaybe : Maybe<bool> = S.Just(1); // justAMaybe is casted to Nothing
var v:Nothing = justAMaybe;
```

**Comment by zhangchiqing** [comment]
Thanks @iamchenxin . 

What I want is that the following code should throw type error, because `S.Just(1)` returns `Maybe<number>`, not `Maybe<bool>`.
```
var justAMaybe : Maybe<bool> = S.Just(1); 
```

I figured a workaround: if I add another field `whatever: bool` for `Nothing`, it can throw error.
```
  declare export type Nothing = { isNothing: bool, isJust: bool, whatever: bool };
  declare export type Just<R> = { isNothing: bool, isJust: bool, value: R };
```

[flow try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoMYAmBTAxjAQwCdsMAXATwAdSA5OMgCwEsA7AczAF4wBvMZgGd6TNuwBcYAEZw4MADQDBAKQCugspJlzFCRgTLYAbtiJbZMMAF8A3Oix5CJctVJqNAFVcAeAEoA+bj4lERYOcx0ld01pC0UjAhhVbElfazsMHHxiUjBKGjAAWQIKKWw-QJ5QsTAAHzBorxoKu3ssp1JswUEwAGUCVlwyVWIKPnsMao4ACgBKSSn2DIwG9TIwbwBBf2mCSU351c8fbeWMIUWwXcli0vKBin9D7RgzqLWrvaKSsu8Hp4irwmYCgRDgAFtbmUNttpjgoARVDAyAA1RLJfaKcE-bBopIpb53LYAwm-U7A7F3DxwWhIwhSGCkYnTSllPEY0nlbaHAD8mzeZDgUKZsK+fMOwuJb1ZIvkACEdlJJHLFARqUqrgl9rNuIEVWAZZsbjjiYc5W8AFZrHrMmWCSQAbUl2wAuocHZsXdKCFRhTD5TsoKxJNcwAddZzvArVfawB63Y65V77FZUG1HDkQapBmRmHBWGBcCQDKRpnAqLn87GHod+jmRkQKMt2pmEkQwNhWEZHQ9k6gW8422BBANJHWhg2m6hgMAOwAPGhDbCYPJwPKMMFIUxgoiKKSqdbsBhgVhr7dwIiCAB0qCHVo0mz9xqJL0qw4GV+i0wAjLM7DOwCHTAACZxEaHwNCIMQ33vMhHxxGwwAA8920YUxsCAA)

Is there better way than this hack?

**Comment by samwgoldman** [comment]
What about this?

```
declare  type Nothing = { isNothing: true, isJust: false };
declare  type JustType<R> = { isNothing: false, isJust: true, value: R };
```

**Comment by zhangchiqing** [comment]
>What about this?

Yes. This works too. Thanks @samwgoldman  

I have another question here :)

[flow try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoMYAmBTAxjAQwCdsMAXATwAdSA5OMgCwEsA7AczAF4wBvMZgGd6TNuwBcYAEZw4MADQDBAKQCugspJlzFCRgTLYAbtiJbZMMAF8A3Oix5CJctVJqNAFVcAeAEoA+bj4lERYOcx0ld01pC0UjAhhVbElfazsMHHxiUjBKGjAAWQIKKWw-QJ5QsTAAHzBorxoKu3ssp1JswUEwAGUCVlwyVWIKPnsMao4ACgBKSSn2DIwG9TIwbwBBf2mCSU351c8fbeWMIUWwXcli0vKBin9D7RgzqLWrvaKSsu8Hp4irwmYCgRDgAFtbmUNttpjgoARVDAyAA1RLJfaKcE-bBopIpb53LYAwm-U7A7F3DxwWhIwhSGCkYnTSllPEY0nlbaHAD8mzeZDgUKZsK+fMOwuJb1ZIvkACEdlJJHLFARqUqrgl9rNuIEVWAZZsbjjiYc5W8AFZrHrMmWCSQAbUl2wAuocHZsXdKCFRhTD5TsoKxJNcwAddZzvArVfawB63Y65V77FZUG1HDkQapBmRmHBWGBcCQDKRpnAqLn87GHod+jmRkQKMt2pmEkQwNhWEZHQ9k6gW8422BBANJHWhg2m2ngMAwB4WD0EMwYJYmGCEKgZ0OrRoesaiaxVOCykRKnHegA6aLTACMs0Ul+vAHIAExP2Z9mdgACSHYAHjQQzYJgeQLnkcCgeuHZEGCRCKFIqjrJgzCYKwT5kBeqAjqwF47mQgjTA62FXmst73sOAwkRo0yvu+bqoEAA)

This is the type signature for `justs`
```
    justs <A>(maybes: Array<Maybe<A>>): Array<A>;
```

I expected the following code would throw, because `justs` only takes an array of the same type of `Maybe<A>`. But it didn't throw.
```
san.justs([san.Just(1), san.Just('2')])
```

I inspected with `type-at-pos`
```
▸ ./node_modules/.bin/flow type-at-pos san.js 25 6
[Maybe<number | string>, Maybe<number | string>]
```

Looks like flow infers the type of `[san.Just(1), san.Just('2')]` as `Array<Maybe<number | string>>`. 

Is it possible to disable this behavior? Like don't infer as a union type of `number | string`, so that flow can help me catch the type error that I'm passing different Maybe types in an array to the `justs` function.

**Comment by iamchenxin** [comment]
@samwgoldman Please help me too ~~~
A old issue -> #2440  A `CLASS_<T> { v: T;}` will always match a `ObjectMap = { [key: string]: number }`. (as compared to a `OBJECT_<T> = { v: T};` will not match `ObjectMap`).
Is this behavior  a bug or by design?  [FlowTry here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFZ4DGGAsgIY5gC8YA3mANoDWeWAXGAGcMAJwCWAOwDmAXX7iArgFtieYWAC+AblQATSjFrCCFAwIFgAwgBkAggGU7AfQA8AFQB8rMADd+rzeqYuASEAEIAUgCiFq4uHkxevmCuWuh6JoYE3oZgFACMvNb2Ts5CYlLu2hRw4kI+BSTkVHQMzPmaYMDAYAiiMDBgOLRmADRgxPIYPQAWWGC0-YhgGNOiAgD8YGn6mT45GA0R0bGlIhKSlajVtVPeAEy8jZQ09AkHHV09fQNQtH1jtHEOkE0zg8hgwN+fXQn2udQwFEKtgcLjK508zHeqCAA)
```
type ObjectMap = { [key: string]: number };
declare class CLASS_<T> { v: T;}
type OBJECT_<T> = { v: T};

declare var c1:CLASS_<string>;
const v1:ObjectMap = c1; // will pass, but why allow this? 

declare var t1:OBJECT_<string>;
const v2:ObjectMap = t1; // will fail, and should fail
```

**Comment by zhangchiqing** [comment]
close as it's duplicate to #2630
