### ISSUE TITLE
Simple spread de-structuring failure

### ISSUE THREAD

**Issue by bkase** [facebook/flow#2607]
I know spreads with flow is known to be problematic at the moment, but I couldn't find as simple an example anywhere so I thought I'd post this here:

Code:

``` javascript
type A = { a: string };
function extractA(a: A) { return a.a };
type AB = { b: number } & A;
const {b, ...rest}: AB = { a: 'hello', b: 5 };
extractA(rest);
```

Error:

```
4: function extractA(a: A) { return a.a }
                        ^ property `a`. Property not found in
7: extractA(rest);
            ^ rest of object pattern
```

Expected: No errors

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeoAhgFygDOKATgJYB2A5qAL4DcikArkwGMUDWE1BYAHvTJDcACkp4AlCVB0sKXnTFkAdGQ6pMOXACFCqgEZUmvALaWsdDqABkebgNG0SlgDSgukHqtOxUZhakigDkABZY0HDRAdagAKyGktKyciEoSpxAA

**Comment by SamChou19815** [comment]
This now errors.
