### ISSUE TITLE
Running flow check with --json flag returns an error code 2

### ISSUE THREAD

**Issue by charliedowler** [facebook/flow#261]
Hi,

When I run flow check with the json command option I get a status code of 2
`$ flow check --json`
`...`
`$ echo $?`
`2`

When I run the exact same command with status, it returns 0.
`$ flow status --json`
`...`
`$ echo $?`
`0`

I'm running flow using nodes `execFile`, the error code 2 is giving me a nice `[Command failed: ]` error.

Using flow v0.2.0.

Cheers,
Charlie

**Comment by charliedowler** [comment]
User error, my bad.

**Comment by gabelevi** [comment]
Actually I do think this is a bug. `flow status --json` should use error code 2 if there is an error. `flow status` behaves that way and so does the Hack client.

**Comment by gabelevi** [comment]
Ok, fixed! Thanks for the report!
