### ISSUE TITLE
Support $FlowFixMe in the REPL

### ISSUE THREAD

**Issue by ctrlplusb** [facebook/flow#2611]
Please. :)

I am trying to create some cheatsheets and this would be helpful to have so that I can show cases where we should expect a Flow error to occur.

**Comment by gabro** [comment]
I would love this too! 👍 

`// $ExpectError`

as in the docs would probably be even better

**Comment by gabro** [comment]
I tried to take a stab at this, but I wasn't able to inject any custom configuration in `tryFlow.js`.

What I tried is calling `registerFile` passing a `.flowconfig` content, but it doesn't work. I could definitely use a pointer here /cc @mroch

**Comment by gcanti** [comment]
This would be very helpful in order to share tests
