### ISSUE TITLE
Inference of object properties

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2615]
Somehow Flow allows this:

```js
function a(obj) {
  return obj.a + obj.b;
}

a({ a: 1, b: null });
```

but this fails:

```js
function a(obj) {
  var b: number = obj.b;
  return obj.a + b;
}

a({ a: 1, b: null });
```

**Comment by vkurchatkin** [comment]
Also, this works correctly too:

```js
function a(obj) {
  return obj.a - obj.b;
}

a({ a: 1, b: null });
```

I suspect that this has something to do with the fact that `+` works on both strings and number

**Comment by vkurchatkin** [comment]
It seems that it has nothing to do with neither objects nor inference, Flow simply allows to add `null` to `number`:

```js
var a: number = 1 + null;
```

**Comment by vkurchatkin** [comment]
These [lines](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L4736-L4737) indicate that this is by design. It is a bit weird though and inconsistent with minus operator for no apparent reason.

**Comment by mroch** [comment]
i blamed this once (and it blames to me... :/)

iirc, i was trying to tighten an even looser thing that we were allowing, and instead of just banning it then I ended up making it look intentional. I think we should change this.

**Comment by mroch** [comment]
if this is just about addition, I think it's covered by https://github.com/facebook/flow/issues/2452
