### ISSUE TITLE
Feature request: ability to reference the inferred return type of a function

### ISSUE THREAD

**Issue by Macil** [facebook/flow#2618]
Often I'll create a single function that returns a large object containing many types, and then pass that returned value through many parts of the codebase. I want to avoid having to explicitly create a type for the return value, especially so that there's only one place that needs to be edited to add new properties to the return value. Flow is already able to infer the type of the return value, but I can't reference this inferred type directly. Currently I'm accomplishing this with a little hack:

``` js
/* @flow */

export default function parser(el: HTMLElement) {
  //...
  return {
    isFoo: true,
    numbers: ([5,6,7,8]: number[]),
    coords: {
      x: 2, y: 3
    }
  };
}

/*:: const x = parser(({}:any)); */
export type Parsed = typeof x;
```

The flow comment is pretty hacky. It would be more convenient if I could combine those two lines into this:

``` js
export type Parsed = typeof x(({}: any));
```

Or maybe even define the type directly in the function's definition:

``` js
export default function parser(el: HTMLElement): export type Parsed {
  //...
}
```

(The "export" in "export type Parsed" would be optional.)

**Comment by AgentME** [comment]
Another interesting case I just ran into is where the function returns a Promise for some type that you want to refer to. Here's the even worse hack I'm doing to accomplish that now:

```js
/* @flow */

export default function parser(el: HTMLElement) {
  //...
  return Promise.resolve({
    isFoo: true,
    numbers: ([5,6,7,8]: number[]),
    coords: {
      x: 2, y: 3
    }
  });
}

/*::
declare var __unPromise: <T>(p: Promise<T>) => T;
const __x = __unPromise(parser(({}:any)));
*/
type Parsed = typeof __x;

```

**Comment by gabro** [comment]
Could this be related to https://github.com/facebook/flow/issues/2585?

**Comment by AgentME** [comment]
@gabro If you think of getting the return type of a function as a way of unwrapping the function's type, then it's possible one feature could solve both of these issues.

Or there could be separate features introduced to solve that problem and my first post, and then both features could be used together to solve my second post here.

**Comment by AgentME** [comment]
Oh, so the technique in my second post can also be used for getting the return type of a function.

```js
/* @flow */

export default function parser(el: HTMLElement) {
  //...
}

/*::
declare function getReturn<T>(f: (...args: any[])=>T): T;
const x = getReturn(parser);
*/
export type Parsed = typeof x;
```

**Comment by gabro** [comment]
[Another approach](https://flowtype.org/try/#0C4TwDgpgBA+gogD2AJwIYGNgCULAK7IB2APAEIA0UAYgFxQAUqdqhIAlFALwB8UpvnPgG4AUKEhREKDNlwESVAbClpMOfEWIAqSotEiAZnkKYAlgHtCUMKmQBnCMnoQANnQASAFQCyAGTguEAC2EITAHADeIlBQAPSxAHRJ0VDIckRQUTExpnZU5uZ0KHgQ5CkxhHhBAEaOdnT0ANoArOQAbOQA7OQAHAC6dJU1jo19bGXZUOgFyAAm9Znl2Qh0AEyUIHQAzEsAvim7ovsiYuDQAAq2DrNckkiqshok4hDmBtZXjtwpIvQRULl8uYoLs6Jd7BBZhx4lBHMhzMgAIRAA), courtesy of @gcanti

```js
type _ExtractReturn<B, F: (a: any) => B> = B;
type ExtractReturn<F> = _ExtractReturn<*, F>;

function parser(el: HTMLElement) {
  //...
  return {
    isFoo: true,
    numbers: ([5,6,7,8]: number[]),
    coords: {
      x: 2, y: 3
    }
  };
}


type Parsed = ExtractReturn<typeof parser>
  
({ isFoo }: Parsed) // error!
```

**Comment by AgentME** [comment]
Ha, I was just reviewing the thread again and finally noticed that key part now. I'm liking that way much more. I hadn't realized that type parameters could refer to each other like that.

Btw you should use `(...args: any[]) =>` so that it works on functions of any length:

```js
type _ExtractReturn<B, F: (a: any) => B> = B;
type ExtractReturn<F> = _ExtractReturn<*, F>;
```
