### ISSUE TITLE
Provide command which generates an outline for a specific file

### ISSUE THREAD

**Issue by andreypopp** [facebook/flow#2620]
Merlin provides a useful outline functionality which is used an index for any specified module—a list of functions, types and so on. Editors/IDEs then can use it to quickly jump to locations of interest.

I think flow could provide such functionality in a form of a command:
```
% flow get-outline ./src/some-module.js`
```
which returns a JSON this the following info:
* functions along with locations and types
* classes along with locations and types
* (probably methods) of classes
* other top level bindings with locations and types

What do you think?

**Comment by AgentME** [comment]
Wouldn't the parsed syntax tree give you all this information? Flow actually already has the "flow ast" command which lets you see how it parsed a file.

**Comment by mroch** [comment]
nuclide actually provides an outline view built on top of `flow ast`: https://nuclide.io/docs/features/outline-view/

@nmote how hard was that to build? does this need to be provided by flow?

**Comment by nmote** [comment]
I have mixed feelings about this. On one hand it's a bit annoying to deal with AST (especially when the `flow ast` output changes), but on the other hand, doing this ourselves has allowed us to try cool things that we couldn't have tried as easily otherwise, such as providing outlines for Jasmine-like tests.

**Comment by andreypopp** [comment]
Ok, I missed `ast` command, sorry. I tried it and built an outline plugin for Vim (+ CtrlP) so I think this can be closed.

**Comment by mroch** [comment]
Nice! Is the vim plugin public?

**Comment by andreypopp** [comment]
https://github.com/andreypopp/vim-flow-outline but it depends on vim-flow
which exposes FlowClientCall function (need to do a PR there)
