### ISSUE TITLE
"instanceof" check does not propagate type information in ternary operator

### ISSUE THREAD

**Issue by freddi301** [facebook/flow#2621]

**Comment by gabro** [comment]
Can you provide an example? I tried [this](https://flowtype.org/try/#0MYGwhgzhAEBiD29oG9oDNEAoCUKC+0eAUKJDAEJgBOK0ARtTvoUUQC4CeADgKZznQAvHETQAPtEpVWaAK4A7YGwCW8efTAAvTAA8AXP1zIi0aDujL5ENmEU94aEUgD8ZgHQZ4TAwoAmPNEseXyI8IA)

```js
class Foo { foo() {} }
class Bar { bar() {} }

type FB = Foo | Bar

function baz(x: FB) {
  x instanceof Foo ? x.foo() : undefined
}
```

and it works as expected.

**Comment by freddi301** [comment]
Simplified:
```
class T {}
class A extends T {
  left: T; right: T;
  constructor(left: T, right: T) { super(); this.left = left; this.right = right; }
}
const a = new A(new A(new T, new T), new T);
a instanceof A ? (a.left instanceof A : a.left.left) : a;
```
It works if i declare a separate variable and assign `a.left` to it.
I think there is the same problem within if statements.
It could be that flow do not trace nested objects?

**Comment by freddi301** [comment]
nevermind, typo error :sweat_smile: :
