### ISSUE TITLE
Spread in JSX makes optional props required

### ISSUE THREAD

**Issue by gcazaciuc** [facebook/flow#2623]
Given the following:

``` js
/* @flow */
import ReactDOM from 'react-dom';
import React from 'react';
type propsType = {
    y?: number;
    x: boolean;
}
const El = (props: propsType) => (
    <div>props.x</div>
);
const HOC = (Component) => (props) => (
    <Component {...props} y={1} />
)

const WrappedEl = HOC(El);

ReactDOM.render(<WrappedEl x={true} />, document.getElementById('abc'));
```

I get 

```
 y?: number;
           ^ undefined. This type is incompatible with
12:     <Component {...props} y={1} />
                                ^ number
```

Altought rendering the `<El>` component directly doesn't cause this issue.
Changing the props type declaration  as below to make y required fixes the issue: 
`type propsType = {
    y: number;
    x: boolean;
}`

**Comment by ekosz** [comment]
Just ran into this. Does anyone know of a workaround for now?

**Comment by vkurchatkin** [comment]
How about this:

```js
<Component {...{...props, y: 1 }} />
```

**Comment by AsaAyers** [comment]
It looks to me like this has been fixed, but this issue hasn't been closed. I copied and pasted the code above into [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQCIDyAsmFHnJmAOR4XUC0AJmw4BuDDnxEyVIizadu0kagIBPbKTDZW2AM4AVNRoC8YAN6owlsCoD8ALjAA7AK6YARqTyirYAB4O3ODgYCkdRAF9USjhHHSIAURgwEwAKLThdB3TdA3UASmSAPjAUiysAHn50ADdC7J0AOl9y4Cra1DzRaNiiAAk6AGFkkoG2XEdSRwICo2K07R0ZubLLctHxCamzBp368OsjUwBGfeBCjtQomLiwAHU8cmx1fkTh-oGUxM7LqWp6Bga3Ec-E8KXK90ez1evkOBDwzlIp0KABowIJKK5JgQGgBzUgERKkTBYgBCKgAkvwUhxyG5KBw8t9UEA)
