### ISSUE TITLE
Is it possible to redeclare class definitions to add new statics?

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#2627]
I'm trying to figure out how to add new statics to a class that is already declared by a library. For example, say we have the following:

``` js
// Third party library
class A {}
declare class A {}

// Other library adds new statics to A
A.foo = 'xyz'

// flow error
// property `foo`. Property not found in statics of A
```

I've tried redeclaring the `A` and add the statics myself, but that doesn't seem to be possible. What other options might I have?

**Comment by hackhat** [comment]
Any news on this one?

**Comment by SamChou19815** [comment]
This won't be supported
