### ISSUE TITLE
Document the `ReactClass` type

### ISSUE THREAD

**Issue by Spy-Seth** [facebook/flow#2628]
In the [React HOC](https://flowtype.org/docs/react.html#higher-order-components) documentation you use the `ReactClass` type. No document exists on this special type. 

Could you please add some documentation on it?

**Comment by gre** [comment]
see https://github.com/facebook/flow/blob/master/lib/react.js#L90

**Comment by steida** [comment]
I can understand not everything is working yet, but a short explanation would save thousands of developers.

**Comment by asolove** [comment]
ReactClass is dead. Long live ReactClass.

**Comment by Zhouzi** [comment]
I was expecting to find the proper type to use here so I thought I'd share it for others with the same expectation.


[`React.ComponentType<Props>`](https://flow.org/en/docs/react/types/#toc-react-componenttype)

> This is the type you want to use for functions that receive or return React components such as higher-order components or other utilities.

**Comment by arjun-menon** [comment]
I think it should be `React$ComponentType<Props>`.

For a full list of non-public built-in Flow types, c.f. https://www.saltycrane.com/flow-type-cheat-sheet/latest/
