### ISSUE TITLE
Add ts-node analogy

### ISSUE THREAD

**Issue by ivan-kleshnin** [facebook/flow#2629]
It's not comfortable to establish the whole transpilation machinery (for every test project folder)
just to try some Flow syntax.

TypeScript has `ts-node` which is basically a `node` wrapped with TS compiler.
Obviously, it's not for production, but it's great for **backend script development**!

---

With `ts-node` or `flow-node`: just write some `test.js` and `$ ts-node test.js`.

Without `ts-node` or `flow-node`:

1. `$ npm init`
2. `$ npm install babel babel-loader`
3. `$ npm install webpack`
4. ...

99\. start writing that damned script...

**Comment by gabro** [comment]
Could https://github.com/leebyron/flow-remove-types be what you're looking for?

```
npm install --global flow-remove-types
flow-node test.js
```

**Comment by vkurchatkin** [comment]
You can use `babel-node` for this purpose as well

**Comment by gabro** [comment]
@vkurchatkin true, although with `babel-node` I think you still need to install the appropriate babel plugin and setup a `.babelrc`, right?

**Comment by ivan-kleshnin** [comment]
> Could https://github.com/leebyron/flow-remove-types be what you're looking for?

Probably! I saw `flow-node` somewhere in the docs but I couldn't find a package with such name. It's a shame that so important binary is located under different name.

> You can use babel-node for this purpose as well

Good idea as well!

**Comment by mroch** [comment]
> It's a shame that so important binary is hidden under different title.

it's a good point. cc @leebyron

**Comment by vkurchatkin** [comment]
Small note: I don't really know how `ts-node` works, but I suspect that it actually does type-checking and won't let you run invalid code, while `babel-node` and `flow-node` will just strip type annotations.

**Comment by ivan-kleshnin** [comment]
@vkurchatkin your description is correct, they work differently. I guess that makes sense, giving that Flow is positioned as type-checker rather than separate language. The question is – can we achieve the same level of convenience with Flow as we have with TS?

And the answer is **yes** – we just need to rely on two CLI commands instead of one 
with either `flow-node` or `babel-node` options.
