### ISSUE TITLE
Type Refinement does not flow into function declaration even when mutation analysis is safe

### ISSUE THREAD

**Issue by HerringtonDarkholme** [facebook/flow#2638]
Found here https://github.com/vuejs/vue/blob/dev/src/compiler/codegen/index.js#L232
The author has to declare component as `any`.

I don't think this is the [case here](https://flowtype.org/docs/dynamic-type-tests.html#caveats) because by the time c is passed to `genData` it has not been mutated.

flow version: 0.33

Minimal repro.

``` javascript
/*@flow*/

declare type C = {
    tag: string;
    component?: string;
}

function genComponent(c) {
    '' + c.component
}

function genData(c: C) {
    if (c.component) {
        genComponent(c)
    }
}

```

Expect:
  this code compile

Actual:

error reported on line 9

**Comment by vkurchatkin** [comment]
Flow infers that c is of type C in genComponent, so you have to check component again.

**Comment by HerringtonDarkholme** [comment]
Is there any spec or document specifies this behavior? I wonder.

**Comment by SamChou19815** [comment]
This now errors.
