### ISSUE TITLE
Type aliases within classes

### ISSUE THREAD

**Issue by dchambers** [facebook/flow#2642]
Flow could really do with a way to define type aliases within a class, for example;

``` js
class C<T> {
  type Ts = T[];
}
```

I've put a lot of effort into avoiding the need for this feature, but it's been really hard to avoid:
1. I'd actually prefer to use functions, but functions don't support generics in the same way that classes and object types do, where you can pass in the types you want to be used.
2. I tried constructing the class within a factory class that receives the generic arguments, and which has an anonymous function within the factory method that creates the class (genius I thought :smile:) but this led to subtle errors that eventually caused me to give up on this approach.
3. I tried living without type aliases, but this first led to me having almost unreadable type definitions, and finally led to me having to weaken some type definitions that had become hundreds of characters long, and were completely unreadable.

Nobody else has yet requested this feature yet, so maybe I'm just doing things wrong?

**Comment by sebnow** [comment]
Quite useful, specifically for the use case of a type depending the type from polymorphic classes.

**Comment by akozhemiakin** [comment]
It could also be helpfull in terms of this issue: #235. For example, now, as a workaround, it is suggested ( (here #307 by @jeffmo) to do something like that:
```js
type funcArg = {a: string, b: string};
var myfunction = ({a, b}:funcArg) => { ... }
```

But currently it is not applicable to class methods because we can not define type aliases inside class definitions.

**Comment by xixixao** [comment]
Agreed with @sebnow, this would be helpful to simplify type annotations inside polymorphic classes.

**Comment by colin-han** [comment]
Agreed, this feature is very useful for generate type just like @dchambers mention. 

Currently, I use a workaround like following. But it look is so ugly, and it may cause other compile error if there has more complex types.
```javascript
class C<
    T,
    Ts: Array<T> = Array<T>
> { }
```
