### ISSUE TITLE
Flow raises error when looping over object properties, when object can be multiple types

### ISSUE THREAD

**Issue by AxelDelmas** [facebook/flow#2644]
Accessing property dynamically inside a loop over `Object.keys(obj)` raises an error, when obj can be multiple types:

```
  let copy = {};
  for (let key of Object.keys(obj)) {
    copy[key] = obj[key];
  }
```

See following example on flow try: https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMcBGAVgIxgC8YA3qmGFHHAFxgDk+AhgE4sA0NYHTszbsAXi1QBfdFlwFCAJnJV+7ZsT618zBVPRQArgDsAxtgCWcI2BNwADgE8wACnkBKFbVk37TipUkAbn56ThdvAGtMJzgoMAB5IkwzADoohwBnVyI3D2paWltHAG10gF1leVLosuDaaVpOHANOayKHYOlUduySN2Ce+QV+oA

Using the following instead of `Object.keys(...)` directly works, but I find it quite cumbersome:

```
function _keys<T: string>(obj: any): Array<T> {
    return Object.keys(obj);
}
```

**Comment by asolove** [comment]
I notice that if you declare the type of the `copy` function, then [everything type-checks ok](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMcBGAVgIxgC8YA3qmGFHHAFxgDk+AhgE4sA0NYHTszbsAXi1QBfdFlwFCAJnJV+7ZsT618zBVPRQArgDsAxtgCWcI2BNwADgE8wACnnMA8kUxmAlB69mKrSyNvZOFJSSANz89JwuIQDWmE5wUGCehN7YAHTJDgDOrkQ+PkG0oY4A2vkAusryNSm1MbTStJw4BpzWto4x0qh9DsUkPjHDowrjQA).

The cause of this boils down to Flow having two different ways of thinking about objects. One is "typed, skinny objects", like `{a: string}`, where we know the allowed keys and the type of each value. A completely separate view treats an object as a dictionary mapping string keys to `mixed` values. When you give untyped object literals like in your example, Flow defaults to thinking of them as typed, skinny objects. But to use `Object.keys` and other dictionary-like methods, it needs to be told to think of them as dictionary-like `Object`s.

**Comment by SamChou19815** [comment]
This error is now expected. You must explicit annotate the empty object to make it work.
