### ISSUE TITLE
Bogus error in polymorphic function with union parameters

### ISSUE THREAD

**Issue by anmonteiro** [facebook/flow#2649]
Here's a minimal example:

```js
function foo<T>(x: T | T[]): T[] {
  return Array.isArray(x) ? x : [x];
}

const x: string[] = foo(['some string']);
```

this fails with:
```
const x: string[] = foo(['some string']);
                           ^ array literal. This type is incompatible with
const x: string[] = foo(['some string']);
            ^ string
```

**Comment by vkurchatkin** [comment]
In this case `T` is `string[]`. Try switching `T` and `T[]` in the union

**Comment by anmonteiro** [comment]
@vkurchatkin OK that worked, but I don't understand why?

Closing as this is not really an issue then.

**Comment by vkurchatkin** [comment]
Flow chooses the first branch that works, so `T` should always be the last one. I guess in this particular example it doesn't really "work", but Flow only infers `T` based on arguments.

**Comment by anmonteiro** [comment]
I get it, thanks for the clarification!
