### ISSUE TITLE
`case "foo"` in module scope crashes the parser

### ISSUE THREAD

**Issue by mroch** [facebook/flow#2650]
a file that is just

```
case "foo"
```

hits this `failwith`: https://github.com/facebook/flow/blob/fc6525eed4f91073636a302387c443eacf22a9b3/src/parser/parser_flow.ml#L4255

It looks like `Peek.token` grabs the `T_CASE`, but then `item_fn` skips it while recovering from the error, so it returns a valid AST for the `"foo"` token, which matches the pattern and adds `T_CASE` as `string_token`.

**Comment by gabelevi** [comment]
I think we probably should just get rid of all the failwiths and turn them into "assertion error" parse errors. A bunch of them assume that the input is wellformed, but that's not always true. In any case, the parser should never crash.

**Comment by TrySound** [comment]
Is this fixed?

https://flow.org/try/#0MYQwzgpgBARAZgewTIA

/cc @gabelevi @mroch

**Comment by goodmind** [comment]
@mroch

**Comment by gkz** [comment]
Looks fixed
