### ISSUE TITLE
disjoint unions don't work with classes when "tag" value is a number

### ISSUE THREAD

**Issue by cmatheson** [facebook/flow#2651]
I'm hoping this isn't an intentional thing that I have misunderstood.  The following code typechecks as I would expect:

``` js
type D = {nodeType: 9, foo: Z}
type E = {nodeType: 1, bar: Z}
type Z = {x: string}

function doSomething(container: E | D): string {
  if (container.nodeType === 9) {
    return container.foo.x;
  } else {
    return container.bar.x;
  }
}
```

But similar code (using classes instead of structural typing) fails:

``` js
declare class A { }
declare class D extends A {nodeType: 9, foo: Z}
declare class E extends A {nodeType: 1, bar: Z}
type Z = {x: string}

function doSomething(container: E | D): string {
  if (container.nodeType === 9) {
    return container.foo.x;
  } else {
    return container.bar.x;
  }
}
```

The error in this case is:

```
 11:     return container.foo.x;
                          ^^^ property `foo`. Property not found in
 11:     return container.foo.x;
                ^^^^^^^^^ E
 13:     return container.bar.x;
                          ^^^ property `bar`. Property not found in
 13:     return container.bar.x;
                ^^^^^^^^^ D
```

**Comment by gcanti** [comment]
AFAIK disjoint unions work with objects types. You can use `instanceof` with classes

```js
export function doSomething(container: E | D): string {
  if (container instanceof D) {
    return container.foo.x
  } else {
    return container.bar.x
  }
}
```

**Comment by cmatheson** [comment]
That makes total sense, thanks.  I thought I remembered something like this, but I couldn't remember what it was called (kept getting mixed up with typeof :confused:).  Thanks!

**Comment by vkurchatkin** [comment]
Nope, that's a bug! It works if you use strings for `nodeType` instead of numbers

**Comment by cmatheson** [comment]
oh nice catch @vkurchatkin.  The `instanceof` solution solves my immediate problem, but I guess I'll reopen this and let the flow people decide if it's worth fixing or not?

**Comment by mroch** [comment]
the latter example using classes works as of v0.38.0
