### ISSUE TITLE
spread of null should be checked

### ISSUE THREAD

**Issue by proProbe** [facebook/flow#2652]
I recently found a bug in my code where I had a `?Object` that I tried to spread. It seemed that the maybe Object was null at one time and I failed to add a check there. What I suggest is to add to flow that the `spread-operator` shouldnt be able to be executed on `null` values. Right now it doesnt give any error at all as it actually is possible to spread a null value (which in my opinion is a design flaw).

Example:

**Should give error**

```
const foo = (bar: ?Object) => {
    return {
        ...bar,
        myValue: "something",
    }
}
```

**Comment by andreypopp** [comment]
I think this is by design, object spread `{...a}` is transformed into `Object.assign({}, a)` and this is basically how `Object.assign` works. I think I even have some code which relies on that.

**Comment by thejameskyle** [comment]
Yeah, rest params are supposed to accept `null` values. This seems like an api problem to solve.
