### ISSUE TITLE
Autocomplete should use type name instead of complete signature

### ISSUE THREAD

**Issue by Swatinem** [facebook/flow#2653]
So I had the problem that autocomplete would completely lock up on me, use 100% cpu of one core and eat memory until I kill it.

After some investigation I noticed that this does not happen when I use `interface` declarations instead of `type`.

I think the reason for this is that flow was trying to print out the complete signature of my type.
FYI: the type in question was a union where each variant shared a couple of properties. And one of those properties was also a self recursive type. So maybe the recursion here is the problem?

**Comment by darichey** [comment]
There's not enough info to repro, but this has probably been fixed.
