### ISSUE TITLE
lib for flow.js

### ISSUE THREAD

**Issue by besarthoxhaj** [facebook/flow#2654]
After compiling flow to javascript with `make js`, I tried to look for the lib types of the new generated `flow.js` itself.

Did I maybe miss them? Is there some way I can generate them with `js_of_ocaml`? Or something else.

I'm happy to help if someone can point me in the right direction.

Thanks!

**Comment by samwgoldman** [comment]
What do you mean "lib types"? Do you mean the builtin library definitions in `lib/core.js`, `lib/dom.js`, etc?

If so, take a look at the source for Try Flow. The [README](https://github.com/facebook/flow/tree/master/website#install-js-dependencies) shows that the lib files are found in `static/flowlib` and [read on page load](https://github.com/facebook/flow/blob/master/website/_assets/js/tryFlow.js.es6#L186).

**Comment by besarthoxhaj** [comment]
Hi @samwgoldman, thanks for the reply.

I mean the definitions for flow itself, these ones:
```js
{
  registerFile: Function,
  setLibs: Function,
  check: Function,
  checkContent: Function,
  jsOfOcamlVersion: '2.8.2',
  flowVersion: '0.33.0',
  typeAtPos: Function
}
```

**Comment by samwgoldman** [comment]
Oh, I have no clue. @mroch would know, though.
