### ISSUE TITLE
deleting elements from an array with non-nullable type

### ISSUE THREAD

**Issue by fips999** [facebook/flow#2656]
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzFgLgEEccsBPAHgDsBXAWwCMBTHAPjAF4wBtARgA0AJgEBmALoBudABNmMZgBdm+flPTY8ADwJ0mrLqoAM6zWHK6GLPNyxrpZgF6X9NsHRgwHuMAhfXDWmo5KABLamYZSSA

Here we are deleting a specific element from the array, then attempting to assign the undefined value to a variable of type number.  Relevant snippet below

```
/* @flow */

var a:Array<number> = [1,2,3];

delete a[1];

var y:number = a[1];
```

Flow reports 0 errors.  I expect flow to give an error on the delete line

**Comment by samwgoldman** [comment]
This particular unsoundness is by design. Any value with the type `Array<number>` is assumed to have a `number` value at every index, so even the following type checks:

```
var a: Array<number> = [];
var elem: number = a[100];
```
