### ISSUE TITLE
Flow does not infer function param and result types from previous `declare function`

### ISSUE THREAD

**Issue by andywer** [facebook/flow#2659]
I just noticed that separating a function's type definitions from the actual function implementation does not work. Is that expected behavior?

``` js
/* @flow */

declare function foo(x: ?number): string;

function foo(x) {
  if (x) {
    return x;    // this should lead to an error, but does not
  }
  return "default string";
}
```

Using this instead produces the expected behavior:

``` js
function foo(x: ?number): string {
```

This seems rather counter-intuitive. Would be really nice if people had the chance to declare function's types in a more "haskell-ish" way :)

**Comment by andreypopp** [comment]
I think this is expected, your code examples declares that there's some function `foo` exists in scope and then you override it with another function also named `foo`.

**Comment by andywer** [comment]
Hmm, really? An explanation at least. Thx :)

But I think it would be really cool to be able to do it the functional way and declare the types above the function. If you only use `const` and no `let`, the type for each variable may be inferred automatically as well and you don't need to add any type declarations to the actual code at all.

Just plain JS code, function type declarations next to it and can still perfectly reason about it. 👉 UTOPIA ^^

**Comment by vkurchatkin** [comment]
Here is what you can do:

```js
type foo_t = (x: ?number) => string;

function foo_impl(x) {
  if (x) {
    return x;    // this should lead to an error, but does not
  }
  return "default string";
}

const foo: foo_t = foo_impl;
```

**Comment by andywer** [comment]
Thanks @vkurchatkin. Good to know there is a work-around, even though I wouldn't want to write it for every function I got.

I guess there is hardly a way of running an AST transformation (to automatically transform the functions like that) before flow does its magic?

**Comment by vkurchatkin** [comment]
> I guess there is hardly a way of running an AST transformation 

You can do it, but it will break every usual workflow, because Flow won't be able to check original source code.
