### ISSUE TITLE
Support for code reflection

### ISSUE THREAD

**Issue by skyrpex** [facebook/flow#2660]
Let's start a discussion about code reflection. I will relate my suggestions using code examples.

Is this on the roadmap yet? What do you think about it?

## Exposing types and interfaces to the code

```js
// Declare an interface.
interface BookInterface {
    read(page: number): string;
}

// Create a class that looks like a BookInterface.
class Book /* implements BookInterface */ {
    read(page: number): string {
        return 'page text';
    }
}

// This returns a unique hash for the given interface.
// const type = Type<BootInterface>;

// Usage example
const container = new IocContainer();
container.bind(Type<BookInterface>).to(Book);
const book: BookInterface = container.make(Type<BookInterface>);
```

## Exposing class method types

```js
// interface
import type { Book } from 'contracts/book';

// concrete class
import AnotherClass from 'another/class';

// class with constructor params 
class Shelf {
    constructor(book: Book, another: AnotherClass, number: number) {
        //
    }
}

const types = ArgumentTypes<Shelf, constructor>;
console.log(types);
// Array [
//     Type<Book>,
//     AnotherClass,
//     Number,
// ]
```

**Comment by vkurchatkin** [comment]
This is a bit out of scope of Flow.

> const type = Type<BootInterface>;

What is `Type` in this context? It looks like a generic type, so you can't assign it to `const`.

Your IOC example can be implemented like this:

```js
class Type<T> {}
class BookInterfaceType extends Type<BookInterface> {}
const token = new BookInterfaceType();
```

Then you can use token to represent your type at runtime:

```js

interface Binder<T> {
  to(v: T): void;
}

interface IocContainer {
  bind<T>(t: Type<T>): Binder<T>,
  make<T>(t: Type<T>): T
}

```

**Comment by skyrpex** [comment]
Sorry, I must explained it in a consufing way. I assumed the keyword Type to receive a Flow type or interface and return a unique identifier for the given type or interface.

The objective here is to be able to use interfaces and types as keys in some sort of container (a WeakMap, for example).

**Comment by vkurchatkin** [comment]
> The objective here is to be able to use interfaces and types as keys in some sort of container (a WeakMap, for example).

This would require Flow to emit reference to the same object instance, which in turn requires to maintain a runtime registry of all types and way to lookup types by structure. This is not what static analysis tool is supposed to do.

Furthermore, it's possible to implement as a Babel plugin anyway. The only thing we need is a construct that looks like a function from Flow type to runtime value. This is possible already, but looks ugly:

```js
declare function getType<T>(val: ?T): Type<T>;
const type = getType((null: ?number));
```

**Comment by skyrpex** [comment]
> This would require Flow to emit reference to the same object instance, which in turn requires to maintain a runtime registry of all types and way to lookup types by structure.

That's why I suggested just returning sort of a hash.

> This is not what static analysis tool is supposed to do.

You're right there. Maybe it's out of scope and using a babel plugin is the right thing to do.

> This is possible already

Not sure how could one implement that function without hardcoding all the possible values there...

**Comment by vkurchatkin** [comment]
> Not sure how could one implement that function without hardcoding all the possible values there

This function call would be replaced by babel plugin with some data structure.

**Comment by skyrpex** [comment]
Oh, okay. I didn't get it at first.

Thank you for the support!

**Comment by zerkalica** [comment]
How to to use interface as value key in runtime?

In C# / Ninject we can type:

```js
interface IWeapon {}

class Sword implements IWeapon {}

container.bind<IWeapon>().to<Sword>();
```

We need standards for something like this:

```js
const map = new Map()

map[IWeapon] = Sword
```

And babel plugins can't help there.
