### ISSUE TITLE
Incorrect definition of the Array getter.

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2664]
```
/* @flow */

class Test {
  arr: Array<number>;

  constructor() {
    this.arr = [];
  }

  get(num: number): number {
    return this.arr[num];
  }
}

function addTwho(val: number): number {
  return val + 2;
}

const dd = new Test();

const value1 = dd.get(33);
const sum = addTwho(value1);
```

Flow not reported an error.

**Comment by vkurchatkin** [comment]
What error would you expect?

**Comment by szagi3891** [comment]
type of this.arr[num] should be inferred as:
undefined | number

**Comment by vkurchatkin** [comment]
Oh, well, this is unsound by design. It would be too inefficient to check array element for undefined every time, e.g in `for` loop.

**Comment by szagi3891** [comment]
Therefore, would be useful stronger mode flow-a which will guarantee a zero runtime error.
He could be activated by using the configuration file ".flowconfig".

**Comment by SamChou19815** [comment]
This is the known part where Flow decides to be unsound to allow better DX.
