### ISSUE TITLE
[SET] - The value is not checked in the constructor.

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#2665]
```
type EnumType = 'aa' | 'bb' | 'cc';

function enumToString(value: Set<EnumType>): string {
  if (value.has('aa')) {
    return 'aa label';
  }
  return 'other';
}

const val = new Set('aaa');

const valLabel = enumToString(val);
```

I should get an error that value 'aaa' is invalid.

**Comment by szagi3891** [comment]
Still there is a problem :

```
/* @flow */

type valType = 'aa' | 'bb';

const ff = (aaa: Set<valType>) => {
};

const arg = new Set('aa');
ff(arg);
console.info('has aa', arg.has('aa'));
```
```
No errors!
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBuAhjACq4EC8YA5McbWAD50BGbtA3OgMZwA7AM4YwUKGBoAKBsQBcYAMp4MAHhLlKAPgCUkrWADeqAL49U-YaOIAnAOaSwAvEmUYp9Rjp7iZ97xaCQnAweAB0AJYCUHAeABbEQmAMtAA0yfZhCUIeKTreQA

@vkurchatkin 
You can re-open this issue ?

**Comment by TrySound** [comment]
Fixed
