### ISSUE TITLE
running flow on concatenated source?

### ISSUE THREAD

**Issue by unhammer** [facebook/flow#2666]
I'm using flow to typecheck an old project that has js spread across various files, and simply concatenates those files before minification (no fancy webpack or similar). How can I get flow to understand that it needs to read all files in `assets/js/*.js` before typechecking? I've tried putting `assets/js/*.js` in `[include]` in `.flowconfig`, but to no avail.

Currently I'm doing `cat assets/js/*.js |flow check-contents`, but of course that messes up line numbers.

**Comment by indiescripter** [comment]
I happened upon the same problem though for a new project that it not using modules (ES2015 imports or exports). My sources are contained in a number of @flow-enabled .js files in a bunch of directories under a src/ root directory. I'm not sure if this is proper but found out that by telling Flow that src/ is a library directory seemed to work. Accordingly my .flowconfig directory looks like this:

```
[libs]
src/
```

**Comment by TrySound** [comment]
There is experimental command `flow focus-check` which accepts files or directories. I think with bash glob expansion this can be easily achieved.

This probably can be closed.
/cc @vkurchatkin
