### ISSUE TITLE
Generic is not inferred from constructor value

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#2668]
I'm writing a class `Option` parameterized on a generic `T`, and it seems the constructor argument
is not enough to infer its generic, which makes the class behave closer to `Option<any>`.

Does anyone have any suggestions on how I can improve the definition to get better inference?

```
/* @flow */

class Option<T> {
  _value: T;

  constructor(value: T) {
    this._value = value;
  }

  getOrElse(t: T): T {
    if (this._value) {
      return this._value;
    } else {
      return t;
    }
  };
}

const x = new Option(('': string));
x.getOrElse(''); 	// This is fine
x.getOrElse(1); 	// This should be an error
x.getOrElse({}); 	// This should be an error

// Adding this will make flow detect the errors above
// const y: Option<string> = x;
```

Example code is also available [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAeQAcAXASzgDsAeAFQD4wBvVMMAfQDdsYBXAKYAuMHQDc6dhmq5SAJz4ZScOQAoe-YaICULNuzCkAFuVwA6br0FgAvGA2CJ7AL6SwAcwGlCcgKIxcAVVSETptUL0DMHIoMGCTc0tNXVYo9jkvPjkqQwSLBwEnA2cwAQCBSLSM0iyc0iKXfWcJV0wZUjAAD1swKgEkEgpqVVUAclGRWTlyKndtbQlOs09vP3Kx0YWwAEhgYFEE6IIoGYFUJZWff0DVAEYt3f26Q9wjOD4YABMwACMK7ByAjkchU52WXiu62YzgeewOpjAr3eX1+-0BwNBqDhAEFPp8Zu5cgiEOQYDAwABbbAAawqsEQYE+XgESlyFSBILkBGwPzgXDOcOkVFkYAAniJBpRaFMCUw7J0JEA)

**Comment by vkurchatkin** [comment]
Inference works as expected. If you try to use result of `getOrElse` as `string` you will get an error.

**Comment by cprodescu** [comment]
@vkurchatkin Thanks for the response, I'm referring to the generic `T` of the instance `x` not being inferred from the constructor.
Under the definition of `getOrElse`, `getOrElse(1)` and `getOrElse({})` should prompt errors since `x` is `Option<string>`, while `1` and `{}` are not strings.

Also, changing to [this](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAeQAcAXASzgDsAeAFQD4wBvVMMAfQDdsYBXAKYAuMHQDc6dhmq5SAJz4ZScOQAoe-YaICULNuzCkAFuVwA6br0FgAvGA2CJ7AL6SwAcwGlCcgKIxcAVVSETptUL0DMHIoMGCTc0tNXVYo9jkvPjkqQwSLBwEnA2cwAQCBSLSM0iyc0iKXfWcJV0wZUjAAD1swKgEkEgpqVVUAclGRWTlyKndtbQlOs09vP3LVAEYF1FUllZ9-QLHR3Un5GbmJdFRgYDAAQQATR4vc0zAEchgYMABbbAA1hVYIgwI8vAIlLkKgI5HIVARsAAjOBcAQ3O7SKiyMAATxEg0otCmFyYdk6EiAA):
```
const x = new Option(('': string));
x.getOrElse(1);              // This should be an error
(x.getOrElse(''): string);   // This will throw an error, inferring x.getOrElse(...) should return a number
```
will throw an error, but on the line which uses the same type as provided in the constructor.

Please let me know if I'm missing something.

**Comment by samwgoldman** [comment]
@vkurchatkin is right, that inference is working as designed here.

When you create an `Option` instance, we instantiate `T` to an "open" type variable. An open type variable accumulates lower bounds and upper bounds. Lower bounds come from inflowing values while upper bounds come from uses and annotations.

In this case, the constructor argument is an inflowing value, so our type variable gets a `string` lower bound. Then, when you call `getOrElse`, the type variable gets another lower bound, `number`.

If you annotate `x` as `Option<string>`, the `string` in that annotation becomes an upper bound of the type variable. When you add a type cast to the result of `getOrElse`, the annotation becomes an upper bound of the type variable.

Flow ensures that lower bounds are compatible with upper bounds (read: inflowing values are compatible with their uses or annotations), but not that lower bounds are compatible with each other.

This is the same behavior that causes the following code to infer `number | string` as the type of `x`:

```
function f(b: boolean) {
  let x;
  if (b) {
    x = 0;
  } else {
    x = "";
  }
}
```

**Comment by cprodescu** [comment]
@samwgoldman thank you for the thorough explanation, that explains the behavior I was seeing when fiddling with this.

Probably will go with
```
getOrElse<AlternativeT>(t: AlternativeT): T|AlternativeT
```
since this is closer to the inference model and produces more clear error messages.
