### ISSUE TITLE
A way to explicitly import type definitions

### ISSUE THREAD

**Issue by danvk** [facebook/flow#267]
Is it possible for a module to export Flow types (rather than just symbols which are available at runtime?)

TypeScript has a notion of "import for types", i.e.

```
/// <reference path="path/to/definitions.d.ts" />
```

something like this would be quite helpful in Flow as well, either explicitly importing a types file (as in TS) or pulling in types from a `require`d file (as in C).

The current solution (as I understand it) is to define shared types globally, in the same way that you'd declare types for third-party code.

I see lots of duplication of type definitions in Flow example code, e.g. in the flux-chat example. Looking at just the `Message` type, its definition is duplicated four times in the six components:

(as Flow type)
https://github.com/facebook/flow/blob/master/examples/flux-chat/js/components/ThreadSection.react.js
https://github.com/facebook/flow/blob/master/examples/flux-chat/js/components/MessageSection.react.js

(as React type)
https://github.com/facebook/flow/blob/master/examples/flux-chat/js/components/ThreadListItem.react.js
https://github.com/facebook/flow/blob/master/examples/flux-chat/js/components/MessageListItem.react.js

The duplication between Flow types and React `propTypes` is maybe a separate issue, but also something which would be nice to avoid. The flux-chat example would be improved if it were possible to create a `types.js` file that both `ThreadSection.react.js` and `MessageSection.react.js` could import.

**Comment by bakesteve** [comment]
yeah - the duplication at current between react proptypes and flow types is a bit of a pain. as an EG if you use propTypes, and componentDidUpdate or shouldComponentUpdate (etc) you often see a duplication (or worse, `: any`) 
I've not seen a neater way round that, so anything that can happen here would be good

**Comment by danvk** [comment]
According to [this blog post][1], something along these lines is coming soon:

> Can I use import type to pull in type aliases from another module, too?
> Not quite yet...but soon! There are a few other moving parts that we need to build first, but we're working on it.

[1]: http://flowtype.org/blog/2015/02/18/Import-Types.html

**Comment by jeffmo** [comment]
Indeed, this is on our radar! The longer term plan for `import type` is to allow importing of type aliases as well as class-types.

**Comment by jackphel** [comment]
+1 if I have a shared list of types in apiTypes.js representing what the server could produce, is there any way to get flow to recognize those types when I use them in apiUtilizer.js other than copying the body of the type alias into apiUtilizer.js?

**Comment by bakesteve** [comment]
Yeah, that would be excellent, pushing out types from the server via swagger/Json schema etc and then using that in flow.

**Comment by jackphel** [comment]
@bakesteve that's just what I'm doing :P https://github.com/jackphel/swaggerflowtypes I'm outputting classes for now.

**Comment by bakesteve** [comment]
Great! Now, just need to get these changes onto a windows build (#6 please...)

**Comment by jeffmo** [comment]
I just wanted to post an update that we shipped preliminary support for `import` and `export` (regular es6 modules) as of last week.

Among other things, I'm now working on adding transformation support for that to the `jsx`/`react-tools` transformer (basically our reference-implementation transformer) -- and then I intend to move on to `export type` and more generalized `import type` support.

**Comment by jeffmo** [comment]
Just wanted to follow up here: v0.10 shipped a new `export type` feature that allows you to export type aliases for use with `import type`: https://github.com/facebook/flow/blob/master/Changelog#L4

I have a backlog of docs to write up for this feature and several others, but until I get to doing that the tldr is that this `export type` feature should work just as it sounds:

MyTypeAliases.js
```
/* @flow */
export type ID = number;
export type UserData = {userid: ID, firstName: string, lastName: string};
```

ThingThatDealsWithUsers.js
```
/* @flow */
import type {UserData} from "MyTypeAliases";

function sayHi(user: UserData) {
  console.log("Howdy %s!", user.firstName);
}
```

**Comment by danvk** [comment]
@jeffmo Can you confirm: a module can export symbols (via `module.exports = ...`) or types, but not both?

**Comment by danvk** [comment]
This feature is completely broken with jsx 0.13.2. Do I need to wait for a new release of react-tools before I use it?

```javascript
// other.js
export type Foo = number;
var Other = 1;
module.exports = Other;
```

```
$ jsx --harmony --strip-types --es6module other.js
/** @flow */
// other.js
export
var Other = 1;
module.exports = Other;
```

(look at the bare `export` in the output)

**Comment by jeffmo** [comment]
@danvk: Right, `module.exports = [...]` and `export type` are mutually exclusive (Flow becomes confused about which kind of exports it should use).

What should still work (because there's no ambiguous intent with respect to ES6/CommonJS interop) is something like this:

```
export type Foo = number;
exports.bar = 'asdf';
```

As for the `jsx` tool: Oops, you're right! Let me sync with the React crew today to get a new version of the jsx tool published.

**Comment by jeffmo** [comment]
(PS: As a temporary workaround if you're blocked here -- you should be able to override `node_modules/jstransform` and `node_modules/esprima-fb` with the latest code in https://github.com/facebook/jstransform and https://github.com/facebook/esprima/ and that should hopefully give you the updated transforms that strip out `export type`)

**Comment by jeffmo** [comment]
Ok, I spoke with @zpao and he's in the middle of deprecating `react-tools` in favor of merging the `jsx` cli directly into the `jstransform` npm package.

So, if you can switch to using the CLI over in [jstransform](https://www.npmjs.com/package/jstransform) (it should have exactly the same interface as the `react-tools` CLI), then you should be able to get all the latest stuff right away.

**Comment by zpao** [comment]
*virtually* the same interface

https://github.com/facebook/jstransform#cli-1

**Comment by jeffmo** [comment]
@danvk: Can you confirm if switching to `jstransform` fixed the issue for you?

**Comment by danvk** [comment]
Yep, this looks more reasonable:

```
$ jstransform --harmony --strip-types --es6module other.js
/** @flow */
// other.js

var Other = 1;
module.exports = Other;
```

**Comment by bolinfest** [comment]
@jeffmo In your example, where is `ThingThatDealsWithUsers.js` relative to `MyTypeAliases`? That is, how is one supposed to be able to find the other in an environment like Node? If they were in the same directory, would you ever do:

    import type {UserData} from "./MyTypeAliases";

Apologies for being behind on reading the ES6 modules spec.

**Comment by bolinfest** [comment]
Ah, my Flow was messed up. Now I've got `./` working as expected. Carry on.

**Comment by bolinfest** [comment]
Though I am getting complaints from Flow when I have this in one file:

```
/* @flow */

export type Score = {
  value: string;
  score: number;
};
```

And then do the following in a file in the same directory:

```
import type {Score} from './Score';
```

And try to declare a nullable field in a class:

```
class TopScores {
  _min: ?Score;
```

Flow complains about the use of `?Score`:

```
null
This type is incompatible with
object type
```

**Comment by jeffmo** [comment]
@bolinfest: Hmm, maybe you can send me a gist that repros? When I try what you described, Flow (0.10) doesn't seem to give me any issues:

https://gist.github.com/jeffmo/6012f7d5c63138ef9583

**Comment by rpominov** [comment]
Hi, I'm having issues with importing types. Here is my setup:

```js
// types.js

/* @flow */

export type MyMap = {[key: string]: any};
export type PropName = {prop: string};
```

```js
// main.js

/* @flow */

import type {PropName, MyMap} from './types';

function getPropValue(a: PropName, b: MyMap): any {
  return b[a.prop] || 0;
}

getPropValue({prop: 'bar'}, {foo: 1})
```

```
/Users/anon/projects/my/fluce/src/index.js:9:1,37: function call
Error:
/Users/anon/projects/my/fluce/src/index.js:6:10,18: access of computed property/element
Property not found in
/Users/anon/projects/my/fluce/src/index.js:9:29,36: object literal

Found 1 error
```

If I move type aliases to `main.js` everything works. Am I doing something wrong?
