### ISSUE TITLE
Support flow:main in manifest

### ISSUE THREAD

**Issue by steelbrain** [facebook/flow#2675]
(I searched for an existing issue but couldn't find one so sorry if this is a duplicate)
### The problem

The problem is that we want flow to understand the types of flow-typed modules correctly when requiring them. 
### The workaround

We currently have to keep `.flow` files along with `.js` files after they are babel compiled and that adds an extra build step and a ton of headache.
### The solution

If Flow has support for `flow:main` (like `jsnext:main` [for rollup](https://github.com/rollup/rollup/wiki/jsnext:main)), we would not have to add anything new to our build step. We can just leave the `src` dir in our npm package and set `flow:main` to `src/`.

This is a follow up to https://github.com/facebook/flow/pull/1459

**Comment by natew** [comment]
Any update here? This prevents our entire stack from being flow typed properly!

**Comment by steelbrain** [comment]
@STRML About your comment on the PR, `AgentMe/flow-copy-source` doesn't integrate well with babel so I've forked the babel cli and created a dropin replacement [babel-flow-cli](https://github.com/steelbrain/babel-cli-flow), it works well even with the watcher and updates `$.flow` copies instantly

**Comment by TrySound** [comment]
You might don't need to look for `module` field. Use this way
```js
{
  "main": "./lib/index.js",
  "module": "./esm/index.js",
  "files": ["lib", "esm", "src"],
  "scripts": {
    "build:flow": "echo \"// @flow\\n\\nexport * from '../src';\" > lib/index.js.flow"
  }
}
```

**Comment by wtgtybhertgeghgtwtg** [comment]
I think that's what he was addressing under "The workaround".  It's certainly an option some libraries are taking, but it feels hacky and potentially increases bundle size.

**Comment by TrySound** [comment]
@wtgtybhertgeghgtwtg How this increases bundle size? `lib/index.js.flow` file is used only by flow. Bundlers do not care about it. Also with this you don't need to duplicate types anywhere. Sust place one `.js.flow` reference near entry point.

**Comment by TrySound** [comment]
Also there is #5729 with similar feature, so this can be closed

/cc @vkurchatkin

**Comment by wtgtybhertgeghgtwtg** [comment]
Sorry, I meant package size.
I don't think #5729 solves this issue.  Ideally, Flow types should work without an extra build step and without the consumer having to alter their configuration.

**Comment by TrySound** [comment]
Package size? With a few bytes? Who cares? My way is pretty good for this without any new fields in package.json.

**Comment by TrySound** [comment]
The problem is that own entry point does not solve necessary cases. For example:
```js
import map from 'lodash/map'
```
requires `map.js.flow` file. Such cases are not solvable with simple configuration. But with `.js.flow` and `main` field we have universal way to define types. So I consider it as non-hacky and even more productive than any config and additional fields.

**Comment by steelbrain** [comment]
I've opened a PR to fix this in https://github.com/facebook/flow/pull/6504
