### ISSUE TITLE
Object with optional property is not compatible with another object

### ISSUE THREAD

**Issue by michalkvasnicak** [facebook/flow#2676]
I made a simplified case from code I have:

```js
/* @flow */

type CartWithOptional = {
  products?: [],
  totalPrice: number,
};

type Cart = {
  totalPrice: number,
};

function mutate(cart: CartWithOptional): [] {
  return cart.products || [];
}

function doSomething(cart: Cart): [] {
  return mutate(cart);
}

mutate({ totalPrice: 10 }); // valid

doSomething({ totalPrice: 10 }); // invalid
```

I get an error: 

```
12: function mutate(cart: CartWithOptional): [] {
                          ^ property `products`. Property not found in
17:   return mutate(cart);
                    ^ object type
```

Is this a bug or am I missing something?

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDCAhgE4YDqAlhgBYDyOGVcAdsTGALxgDeqYMDlJwAJgFcAxhgDOAfgBcYANoBdADQCwGOBg4AFUlUl4lrcQFsARnlKaAvgG502fETIZufLTr0xDxqZg5ta2Ds6oUOKs0iysYBbiehh4ABSSHkok5NR0jMxsHACUSmregqR4GOKk8RnkAHTCYlKyYAA+7SqqzvboUTEF8aJwAMpwFlW0VKwA5umZ7uQl3eVgldW1CUnEKQvLveiJyWm82roGRiZKAIwADGD2RREj45N0M-NnvpeBtw9PRxAA

**Comment by vkurchatkin** [comment]
It's not a bug. `CartWithOptional` is not a subtype of `Cart`. For example, value of type `Cart` can have a property name `products` of some other type. You can fix this, if you make `Cart` an exact type:

```js
type Cart = {|
  totalPrice: number,
|};
```

**Comment by michalkvasnicak** [comment]
Thank you, now it makes sense :)

**Comment by mwalkerwells** [comment]
@vkurchatkin I was a bit confused re: the typing relationship between objects, especially ones with optional properties. Why does this work for example?

````js
// @flow

type Supertype = {|
  a: string,
|}

type Subtype = {|
  a: string,
  b?: ?string, // Same thing as —> "b: void | null | string"
|}

function test<T: Subtype>(value: T): void {
  value.b = '' // <—— Why is this possible?
}

declare var foo: Supertype

test(foo)
````

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZQK7YBO62oAvKAN4A+iooAhgFygDOKRAlgHYDmAGkQ0AvslI4CAIwkVqdBi3adeg+qCkB+Vpo7d+A0CDyMAtjhQALVUzahAKAQA+UACIprAG6wuAE1A1QHnxoaH9lfT4XYTFESHweAGMULlgeUBQsDgAeABVWaQlHAAoPRmh8LFYcgEpPbz8qdVLyrAA6KTkAck6jMCz7e1AAdUs0UC47KwnQDFg2Ni4paCxNRBifLAToRiIcUqJQSFhYfMIsEkwscUyUIqPYaqA

**Comment by vkurchatkin** [comment]
` b?: string` means that either object doesn't have property `b` at all, or it is of type `string`.
