### ISSUE TITLE
Typechecking fails with two spreads in JSX

### ISSUE THREAD

**Issue by AvivRubys** [facebook/flow#2679]
When presented with this:

```
const Rawr = (props: {someProp: boolean}) => null;
const src1 = {someProp: false};
const src2 = {};

<Rawr {...src1} {...src2} />
```

Flow responds with:

```
1: const Rawr = (props: {someProp: boolean}) => null;
                        ^ property `someProp`. Property not found in
5: <Rawr {...src1} {...src2} />
                       ^ spread of object literal
```

It seems that flow is searching for "someProp" only on the second spread, ignoring the first spread.
I've reproduced the same issue using `React.Component` as well, so it seems like it's JSX related.

**Comment by vkurchatkin** [comment]
You can use this as a workaround:

```js
<Rawr {...{...src1, ...src2}} />
```

**Comment by AvivRubys** [comment]
Sure, I did do that.
I'd like to help but I know nothing about ocaml...

**Comment by asolove** [comment]
Original code works fine as of Flow 53.
