### ISSUE TITLE
typeof annotation seems to parse incorrectly

### ISSUE THREAD

**Issue by phpnode** [facebook/flow#2682]
It seems that flow parses annotations like `T: typeof string` incorrectly, it treats `string` as if it were a `StringTypeAnnotation`, but presumably it should be an identifier or `GenericTypeAnnotation`?

``` js
const string = "Hello World";
const foo: typeof string = string;
```

**Comment by phpnode** [comment]
Related to this, 
```js
const obj = {a: 123};
const foo: typeof obj.a = obj.a;
```

Here `typeof obj.a` produces a `QualifiedTypeIdentifier`, but I think it should simply be a `MemberExpression`. I guess that the intention is to restrict the argument to the `typeof` operator to a subset of possible expressions in order to disallow e.g. function calls, but the mechanism doesn't seem right.

**Comment by vkurchatkin** [comment]
@phpnode seems like a bug, `QualifiedTypeIdentifier`  is a different construct

**Comment by phpnode** [comment]
@vkurchatkin it seems to just treat the operand as if it were a type annotation, so `typeof {foo: 'abc'}` gives an `ObjectTypeAnnotation` rather than an `ObjectExpression`
