### ISSUE TITLE
$Diff not working with Object.assign

### ISSUE THREAD

**Issue by pbomb** [facebook/flow#2683]
I see there are some open issues already about Object.assign. I'm not sure if my issue is one of those or a new one. I have a small example which reproduces the problem. Can somebody let me know if I'm doing something wrong?

``` js
type Thing = {
  str: string,
  bool: boolean,
  num: number,
};

// partialThing represents default values
const partialThing: $Shape<Thing> = {
  str: 'a string',
  bool: true,
};

// assigning the missing "num" prop from paritialThing type checks correctly
// goodThing has all 3 valid props
const goodThing: Thing = Object.assign({}, partialThing, { num: 3 });

// Defining the object as the diff between Thing and the default values
// seems to work well. I'm forced to include "num" correctly.
const restThing: $Diff<Thing, typeof partialThing> = { num: 3 };

// However, when the last arg to assign is typed as the diff, flow errors
const badThing: Thing = Object.assign({}, partialThing, restThing);
```

With this example code, Flow complains with the following errors:

```
examples/foo.js:21
 21: const badThing: Thing = Object.assign({}, partialThing, restThing);
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `assign`. Expected object instead of
 21: const badThing: Thing = Object.assign({}, partialThing, restThing);
                                                             ^^^^^^^^^ Thing
```

In my library I'm wanting to use `$Diff<Thing, typeof partialThing>` to type a function argument, forcing callers to pass in a valid object. However, that type doesn't seem to work with Object.assign. Is there a way to use the $Diff type with Object.assign? Is there a better way to do this? Thanks!

**Comment by gcanti** [comment]
> Defining the object as the diff between Thing and the default values seems to work well. I'm forced to include "num" correctly.

This typecheck though

```js
const restThing: $Diff<Thing, typeof partialThing> = {};
```

> In my library I'm wanting to use $Diff<Thing, typeof partialThing> to type a function argument

Could you elaborate a bit more? What's the function signature? Maybe there's a workaround using intersections

**Comment by pbomb** [comment]
Thanks, Giulio. Here's a more concrete example of what I'm trying to build.
```js
export type ThingInterface = {
  str: string,
  num: number,
  bool: boolean,
};

const defaultFooValues: $Shape<ThingInterface> = {
  str: 'strDefault',
  bool: true,
};

export class Thing extends ImmutableModel {
  static fromJS(json: $Diff<ThingInterface, typeof defaultThingValues>): Thing {
    const state = Object.assign({}, defaultThingValues, json);
    return new Thing(Immutable.fromJS(state));
  }

  ...
}
```

I'm wanting to allow developers to specify the default values, which are a subset of properties of `ThingInterface` and for them to be required to pass in the rest of the properties when calling `Thing.fromJS`. But when I take this approach, Flow complains about the `Object.assign` statement. Does that help?

**Comment by gcanti** [comment]
Given that `$Diff` doesn't work with `Object.assign`

```js
type D = $Diff<{}, {}>;
declare var x: D;
Object.assign({}, x) // => raises Expected object instead of object type
```

First let's define a test suite

```js
//
// tests
//

Thing.fromJS({ num: 1 })
Thing.fromJS({ num: 1,  bool: true })
Thing.fromJS({ num: 1,  bool: true, str: 'a' })

// $ExpectError
Thing.fromJS({ num: 'a' })
// $ExpectError
Thing.fromJS({ num: 1, bool: 1 })
// $ExpectError
Thing.fromJS()
// $ExpectError
Thing.fromJS({})
// $ExpectError
Thing.fromJS(1)
```

**Trying to avoid $Diff using intersections**

Here's my (admittedly convoluted) code

```js
const defaultThingValues = {
  str: 'strDefault',
  bool: true
}

type OptionalArguments = typeof defaultThingValues;
type RequiredArguments = { num: number };
type ThingInterface = OptionalArguments & RequiredArguments;
type Diff = $Shape<ThingInterface> & RequiredArguments;

export class Thing {
  static fromJS(json: Diff): Thing {
    const state: ThingInterface = Object.assign({}, defaultThingValues, json)
    return new Thing(state)
  }
}
```

All tests green.

---

**Manual definition works as expected**

```js
type Diff = {
  str?: string,
  num: number,
  bool?: boolean
};

export class Thing {
  static fromJS(json: Diff): Thing {
    const state: ThingInterface = Object.assign({}, defaultThingValues, json)
    return new Thing(state)
  }
}
```

All tests green.

**Comment by pbomb** [comment]
Wonderful. Thanks, Giulio. I'll give this approach a shot in my library.

**Comment by SamChou19815** [comment]
Closing since we recommend using spread instead
