### ISSUE TITLE
How to type check partial query results using structural typing

### ISSUE THREAD

**Issue by michalkvasnicak** [facebook/flow#2684]
I have following code:

```
/* @flow */

// file a.js
type QueryResult = {|
    productsCount: number,
	totalPrice: number
|}

function a(): QueryResult {
	return { productsCount: 10, totalPrice: 100 };
}

// file b.js
type QueryResult2 = {|
    products: { id: string }[],
    productsCount: number,
	totalPrice: number
|}

function b(): QueryResult2 {
	return { products: [], productsCount: 10, totalPrice: 100 };
}

// file mutate.js
type QueryResult3 = {
    products?: { id: string }[], 
    productsCount: number,
	totalPrice: number
}

function mutate(r: QueryResult3) {}

mutate(a());
mutate(b());
```

Resulting to

```
26:     products?: { id: string }[], 
                   ^ undefined. This type is incompatible with
15:     products: { id: string }[],
                  ^ array type
```

[Try flow code](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhigSxgUzAEMA6AKwGdUAXATwAdCBFAV3wCdaAlfClmamAC8YAN4AfVGGlh67OABMWAY2oUAwnBYA7agC4w2lgFsARhwA0qAJDU41IjAAK7HMvwGjZjqnEBfdCgdVRw4bWIACgBKA1YObl5+QVEbdnxqFnZw0Vl5JVUNLV0DAEYABgswOwdnV3dSsrKwPwBuVACMLFwCMFNyKjpGMDjOHj4BACZhMUkZXMUVNQMcnAUDCmpXbQBzZoBtAF0rObkFgs0dfUMTc3YrW3tHFzcPa+92Xw6g7RCw3ujYmxRolJmJUulMtl5vklmBDpVTjDCpcGpVqk86q9yk1Wu10JhsHhCMYWA5qPh+jQGMwgQlxtQAMzTFInPKLCgAfmWYFW602OB2+yOYCkMkR7IuxTet3u6NqL08Nx8X2C1FC4RJZPwEXYgPiYySDKiYg6mqI5IiRGiUTaZotpmtLSAA)

We are using it like this because we have multiple queries and mutations (each in its own file) and each is returning it's own shape because we are not querying server for same data. 

How can we typecheck those results? For example we have query for `totalPrice` and `productsCount` and then we have another query which returns same data + `products`, etc.

**Comment by gcanti** [comment]
Isn't `QueryResult3` just a union?

```js
type QueryResult3 = QueryResult | QueryResult2;
```

**Comment by michalkvasnicak** [comment]
Yes it is but in that case I need to import types from files `a.js` and `b.js` to be able to describe it as an union. 

Is there any other way how to do this?

**Comment by gcanti** [comment]
No, in general you can't compress a union to just one type

```js
type A = {
  a: string,
  c: number 
};

type B = {
  b: string,
  c: string
};
```

How can you express `A | B` without defining an actual union? 

This would be plain wrong

```js
type U = {
  a?: string,
  b?: string,
  c: number | string
};
```

**Comment by michalkvasnicak** [comment]
You are right, I was looking at this code in a wrong way.
