### ISSUE TITLE
unknown type breaks object intersection

### ISSUE THREAD

**Issue by l2silver** [facebook/flow#2687]
unknown type breaks object intersection

```
$ownProps = {
 problemPropery: $unknownType 
}

$stateProps = {
 goodProperty: number
}

$propTypes = $ownProps & $stateProps;

function (props: $propTypes){
 props.goodProperty() //should see error here because not a function, but no error
}
```

**Comment by gcanti** [comment]
@l2silver what are you reporting here? Your snippet is not clear and contains invalid syntax

**Comment by l2silver** [comment]
ah jeese

type $ownProps = {
 problemPropery: $unknownType 
}

type $stateProps = {
 goodProperty: number
}

type $propTypes = $ownProps & $stateProps;

function (props: $propTypes){
 props.goodProperty() //should see error here because not a function, but no error
}
