### ISSUE TITLE
Object type inference issue

### ISSUE THREAD

**Issue by chrisblossom** [facebook/flow#2693]
Maybe this is expected behavior, but it seems if a function is called after checking if a object key exists, flow things it is possibly undefined. 

```typescript
/* @flow */

type ObjType = {
    one?: string,
};

function inside(obj: ObjType): string {
    if (obj.one) {
        console.log('this line breaks flow');
        return obj.one;
    }

    return '';
}

function outside(obj: ObjType): string {
    if (!obj.one) {
        return '';
    }

    // If anything uses obj.one below this line will return an error
    console.log('this line breaks flow');

    return obj.one;
}
```

This might be expected since flow doesn't know if something mutated ``obj.one``, but the following doesn't throw an error:

```typescript
function mutated(obj: ObjType): string {
    if (!obj.one) {
        return '';
    }

    // this line should throw flow error
    delete obj.one;

    return obj.one;
}
```

**Comment by vkurchatkin** [comment]
This is expected behaviour. As you've guessed, flow doesn't know what `console.log` does, so it assumes the worst.

> this line should throw flow error

Implementation of `delete` operator is currently incorrect. See: https://github.com/facebook/flow/issues/2207

**Comment by chrisblossom** [comment]
Thanks for the quick reply!
