### ISSUE TITLE
Shouldn't this cause a Flow error

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/flow#2694]
Notice this function's declared return type is _PathInfo_. But there one flow path that returns a `string` by mistake. This got deployed and only discovered at runtime. But I thought this was the exact type of thing Flow was supposed to catch. 

I know that it is type checking this _file_. Because I made a slight typo on purpose and re-ran Flow. And it caught that.
```
function parsePathInfo(loc): PathInfo {
    let path = loc.hash;
    if (!path || path.trim() == "#") {
        return  "jobMain";
    }
    path = path.replace("#", "");
    if (path.startsWith("/")) {
        path = path.substr(1);
    }

    const i = path.indexOf("/");
    if (i == -1) {
        return {
            key: path,
            arg: null
        }
    } else {
        return {
            key: path.substr(0,i),
            arg: path.substr(i+1)
        }
    }
}
```

I am using: 
Flow version 0.33.0
Mac OS X 10.11.4
node v6.4.0

Here is the type PathInfo:
```
export type PathInfo = {
    key:string,
    arg:string
}
```

**Comment by gcanti** [comment]
Flow raises an error (actually two) [Flowtype/try](https://flowtype.org/try/#0C4TwDgpgBACghsAFgSQHYDMD2UC8UDeAUFCVANYQgBcAzsAE4CWqA5gDTGlz0u0PMtCAXwDchQugCuqAMbBGmVFDDcaEeEjRYAFABtMMgJRVYCFBmxFSUXRGDKzuGwYB0iODURjrjdFG0AhCpIUAA+oQ5ILvwAttqGuHgARADESQlW1qT0dpL0SlBJAFaYAEYAsnDMSd6kQpwkwYhOTS45YLpwMhDaqUlshem1JL7+rXTcwDQA6oxIvQD06RkNWU0tZi40kqV09NoAjIbDUPWrMop0UIwbUcwAJhAAHgDy6ItDq6PaNzh4ALRHAiraw5YB5JSZLJZCjUSKIDjQ6HcXhQVCSXS6EF1VZCKAQXRqYFIqBgiHEkmkWEmcY7PbaAAMbEYhkRlJIKJpm22uwYPwA1EdsSR6tZ6vUgA)

**Comment by StokeMasterJack** [comment]
When I put the PathInfo in the same file, it works as expected. This is why your example worked and mine did not.

In my project, PathInfo is in a _separate file_ called PathInfo.js. Then at the top of this file I have:
`import type PathInfo from "./PathInfo.js";`

When I run it this way I get no error.

**Comment by gcanti** [comment]
Using your setup I can see the errors as well:

PathInfo.js

```js
// @flow

export type PathInfo = {
    key:string,
    arg:string
};
```

index.js

```js
// @flow

import type { PathInfo } from "./PathInfo.js";

function parsePathInfo(loc): PathInfo {
    let path = loc.hash;
    if (!path || path.trim() == "#") {
        return  "jobMain";
    }
    path = path.replace("#", "");
    if (path.startsWith("/")) {
        path = path.substr(1);
    }

    const i = path.indexOf("/");
    if (i == -1) {
        return {
            key: path,
            arg: null
        }
    } else {
        return {
            key: path.substr(0,i),
            arg: path.substr(i+1)
        }
    }
}
```

Error

```
src/index.js:8
  8:         return  "jobMain";
                     ^^^^^^^^^ string. This type is incompatible with the expected return type of
  5: function parsePathInfo(loc): PathInfo {
                                  ^^^^^^^^ object type

src/index.js:19
 19:             arg: null
                      ^^^^ null. This type is incompatible with the expected return type of
  5:     arg:string
             ^^^^^^ string. See: src/PathInfo.js:5
```

Please notice

```diff
-import type PathInfo from "./PathInfo.js";
+import type { PathInfo } from "./PathInfo.js";
```

and make sure you have the `// @flow` pragma in the `PathInfo.js` file

**Comment by StokeMasterJack** [comment]
> make sure you have the // @flow pragma in the PathInfo.js file

Duh! That was it. I need a type checker to make sure I'm using the type checker :) Thanks.
