### ISSUE TITLE
Flow Union Types

### ISSUE THREAD

**Issue by willisplummer** [facebook/flow#2695]
Hi! I've run into the following issue while using Flow

If I create the following TestSubject union type

```
type User = {|name: string, id: number, bio: string|}
type Project = {|title: string, id: number, description: string|}
type TestSubject = User | Project
```

I would then expect Flow to accept the following:

```
const testFunction = (subject: TestSubject): string => {
  if (subject.name) {
    return (subject.name + subject.bio)
  } else if (subject.title) {
    return (subject.title + subject.description)
  }
}
```

this doesn't work though - Flow can't figure out that if a TestSubject doesn't have a name, it will always be a Project with a title and description even though that information is explicitly provided in the union type.

similarly below, i would expect to be able to do the following:

```
type User = {|flowType: 'user', name: string, id: number, bio: string|}
type Project = {|flowType: 'project', title: string, id: number, description: string|}
type Backing = {|flowType: 'backing'|}
type TestSubject = User | Project | Backing

const testFunction = (subject: TestSubject): string => {
  switch (subject.flowType) {
    case 'user':
      return (subject.name + subject.bio)
    case 'project':
      return (subject.title + subject.description)
    case 'backing':
      return 'testing'
  }
}
```

but Flow cautions that I haven't accounted for the possibility of an implicitly returned undefined.

the following code will satisfy Flow:

```
type User = {|flowType: 'user', name: string, id: number, bio: string|}
type Project = {|flowType: 'project', title: string, id: number, description: string|}
type Backing = {|flowType: 'backing'|}
type TestSubject = User | Project | Backing

const testFunction = (subject: TestSubject): string => {
  switch (subject.flowType) {
    case 'user':
      return (subject.name + subject.bio)
    case 'project':
      return (subject.title + subject.description)
    case 'backing':
      return 'testing'
    default:
      throw `unrecognized type ${subject.flowType}`
  }
}
```

Adding in the default isn't ideal, though, because it means that if I ever wanted to add another type to the TestSubject union type, I wouldn't be prompted to handle the new case in testFunction. In a large-scale application, this means that there's a higher risk of accidentally forgetting to handle the new case somewhere and instead having to wait until an end user raises a runtime error.

Is there a potential workaround or fix for this issue?

**Comment by gcanti** [comment]
> Is there a potential workaround or fix for this issue?

```js
type empty = 'empty type' & number; // <= Flow v0.34 will ship with an official empty type

type A = {|type: 'a'|};
type B = {|type: 'b'|};
type C = {|type: 'c'|};
type U = A | B;
// type U = A | B | C; // <= decomment this line to get an error

function f(x: U): string {
  switch (x.type) {
    case 'a' :
      return 'a'
    case 'b' :
      return 'b'
    default :
      (x: empty) // <= if U = A | B | C this is not true
      throw `unrecognized type ${x.type}`
  }
}
```

**Comment by vkurchatkin** [comment]
You don't really need `empty` type for this, you can use any type that is not subtype of `U` instead, for example, `null`.

**Comment by willisplummer** [comment]
hey! thanks for the tip about giving the default an invalid type - that's definitely a step in the right direction, because at least your attention is called to the right place. unfortunately the error message isn't very helpful in terms of explaining what the issue is to the developer -- the immediate inclination would be to remove the invalid type instead of trying to account for every case of the switch.

i wonder if the flow team would consider in the future offering some kind of strict-switching config option where flow wouldn't expect a default if all possible cases of a switch statement were accounted for?

this is how Elm's compiler works, and it's a really great development experience imo
