### ISSUE TITLE
Some issues with CSSOM

### ISSUE THREAD

**Issue by k15a** [facebook/flow#2696]
Hey,

I am currently working with stylesheets in JavaScript and would love to check my code with flow.
I have some issues where I don't know if the type checking is correct. Would be lovely if someone could check if I am doing something wrong.

Why is this just a StyleSheet and not a CSSStyleSheet?

``` JS
const style: ?StyleSheet = ((): ?StyleSheet => {
    // Create the <style> tag
    const style: HTMLStyleElement = document.createElement('style')

    style.type = 'text/css'

    // Add the <style> element to the page
    document.head.appendChild(style)

    return style.sheet
})()
```

If this is the indented behaviour how could I get an CSSStyleSheet?

According to https://developer.mozilla.org/en-US/docs/Web/API/CSSStyleSheet/insertRule the return type of insertRule is a number but the flow return type is void https://github.com/facebook/flow/blob/master/lib/cssom.js#L39. Who is wrong?

**Comment by kof** [comment]
Just started to add types to [JSS](https://github.com/cssinjs/jss), types for CSSOM is partially wrong and not fully implemented.

Missing interfaces I use are for e.g. : HTMLStyleElement, CSSStyleSheet, CSSRuleList, CSSStyleRule

**Comment by kof** [comment]
For e.g. I think https://github.com/facebook/flow/blob/master/lib/dom.js#L2648 sheet should be of type CSSStyleSheet, otherwise you get

```
src/backends/DomRenderer.js:211
211:     return this.element.sheet.cssRules
                                   ^^^^^^^^ property `cssRules`. Property not found in
211:     return this.element.sheet.cssRules
                ^^^^^^^^^^^^^^^^^^ StyleSheet
```

**Comment by foray1010** [comment]
have same problem, wonder why `sheet` must be `StyleSheet` but not `CSSStyleSheet` which it actually is

**Comment by necolas** [comment]
Other types like `CSSMediaRule` are missing too

**Comment by kof** [comment]
This can be closed as well.
