### ISSUE TITLE
Set the default values of a property of object type parameter.

### ISSUE THREAD

**Issue by rahul-dutt-sharma** [facebook/flow#2698]
Hey 

The below code wont parse

/* @flow */
`const fun = (
  options: {
    cwd : string = 'rahul',
  }
  )=> {

};`

**Comment by AugustinLF** [comment]
This does not  seem to be valid JS. I'm not sure of what you intend, this is valid (note the extra brackets around the object):
`const fun = ({options: {cwd : string = 'rahul'}}) => {};`

**Comment by rahul-dutt-sharma** [comment]
Thanks a ton!

**Comment by gcanti** [comment]
in

```js
const fun = ({options: {cwd : string = 'rahul'}}) => {};
```

`string` is not a type, you may want

```js
type T = {
  options: {
    cwd: string
  }
};

const fun = ({ options: { cwd = 'rahul' } }: T) => {}
```

**Comment by rahul-dutt-sharma** [comment]
okies understood. feels like type composition :) but I get the idea. wanted to try it this way. did not feel like it was the only way to do it. ty
