### ISSUE TITLE
Flow freezes when 'merging inference'

### ISSUE THREAD

**Issue by villesau** [facebook/flow#2702]
Flow checker freezes completely with following code:

```
// @flow
import React from 'react';
import _ from 'lodash';

export default class Test extends React.Component {

  state: {matrix: Array<Array<boolean>>};
  state = {matrix: _.times(5, () => _.times(5, () => false))};

  toggleCell(rowIndex: number, columnIndex: number) {
    const newRow = this.state.matrix[rowIndex];
    this.setState({matrix: _.set(this.state.matrix, rowIndex, newRow)})
  }

  render() {
    return (<div onClick={() => this.toggleCell(1, 1)}></div>);
  }
}
```

my flow definitions for lodash looks like following:

``` javascript
declare module 'lodash' {
  declare function set(object?: ?Object, path?: ?Array<string>|string, value: any): Object;
  declare function set<T>(array: Array<T>, index: number, value: T): Array<T>;
  declare function times<T>(n: number, iteratee: (i: number) => T): Array<T>;
}

```

few ways how i can get it fixed:
(1. Move   `state = {matrix: _.times(5, () => _.times(5, () => false))};`
to constructor:

``` javascript
export default class Test extends React.Component {

  state: {matrix: Array<Array<boolean>>};

  constructor() {
    super();
    this.state = {matrix: _.times(5, () => _.times(5, () => false))};
  }

  toggleCell(rowIndex: number, columnIndex: number) {
    const newRow = this.state.matrix[rowIndex];
    this.setState({matrix: _.set(this.state.matrix, rowIndex, newRow)})
  }

  render() {
    return (<div onClick={() => this.toggleCell(1, 1)}></div>);
  }
}

```

(2. Declare _.times to return any: `declare function times<T>(n: number, iteratee: (i: number) => T): any;`

(3. Remove _.set: `this.setState({matrix: this.state.matrix})`

``` javascript
  toggleCell(rowIndex: number, columnIndex: number) {
    const newRow = this.state.matrix[rowIndex];
    this.setState({matrix: this.state.matrix})
  }
```

Anyone of above is not optimal solution, and last of them breaks the logic. Just wanted to point it out to narrow the problem.

declaring state outside of the constructor should be valid javascript. Webpack&babel compiles it just fine and it works like expected.

**Comment by gcanti** [comment]
4)

```js
state: {matrix: Array<Array<boolean>>} = {matrix: _.times(5, () => _.times(5, () => false))};
```

**Comment by villesau** [comment]
thanks @gcanti :) Somehow my mind was stuck with approach i had since usually we define type of state and initialize it separately in the constructor. 

Anyhow in my original scenario flow should either be a) error b) it should succeed without freezing.

**Comment by MoOx** [comment]
Looks similar to #1570 somehow (> "something" flow does not like make it ultra slow)

**Comment by TrySound** [comment]
Is this still relevant?

**Comment by villesau** [comment]
Not relevant to me anymore. Not sure if the issue would still exist though.

**Comment by TrySound** [comment]
This probably can be closed in favor of newer feedback.
/cc @vkurchatkin
