### ISSUE TITLE
null guard not working correctly

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/flow#2704]
I am getting the following error:

```
157:             } else if (this.state.row.name.toLowerCase() == q.toLowerCase()) {
                                           ^^^^ property `name`. Property cannot be accessed on possibly null value
157:             } else if (this.state.row.name.toLowerCase() == q.toLowerCase()) {
                            ^^^^^^^^^^^^^^ null
```

But from what I can tell this.state.row will never be null on 157 because I am checking for that.

```
if (this.state.row == null) {
    console.log("onBlur condition 1a: getByName");
    this.getByName(q);
}
else if (this.state.row.name.toLowerCase() != q.toLowerCase()) {
    console.log("onBlur condition 1b: getByName");
    this.getByName(q);
} else if (this.state.row.name.toLowerCase() == q.toLowerCase()) {
    console.log("onBlur condition 1c: no action required");
}
else {
    throw new Error("IllegalState");
}
```

**Comment by gabelevi** [comment]
Try

```
const row = this.state.row;
<Your code, but with s/this.state.row/row/>
```

Calling functions invalidates refinements of non-locals. Flow is worried that the `toLowerCase()` calls in the first `else if` might set `this.state.row` back to `null`, so the second `else if` errors.

Check out https://flowtype.org/docs/dynamic-type-tests.html#caveats

**Comment by dfleury** [comment]
It won't help you more than gabelevi helped but I noticed that you're type checking `this.state.row` for a null value, however you aren't checking `this.state.row.name` before call `.toLowerCase()` and `name` maybe null.
