### ISSUE TITLE
Support destructured object bindings to new variable names

### ISSUE THREAD

**Issue by sarahlim** [facebook/flow#2709]
ES6 supports object destructuring assignment to new variable names. The following example is taken from [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Destructuring_assignment):

```js
var o = {p: 42, q: true};
var {p: foo, q: bar} = o;
 
console.log(foo); // 42 
console.log(bar); // true  
```

There isn't a clear Flow syntax for type annotations with this binding style. This code

```js
var o = {p: 42, q: true};
var {p: foo, q: bar}: { foo: number, bar: number } = o;
```

fails with the following errors:

```js
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
        ^ property `p`. Property not found in
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                         ^ object type
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                ^ property `q`. Property not found in
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                         ^ object type
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                         ^ property `bar`. Property not found in
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                                                        ^ object literal
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                         ^ property `foo`. Property not found in
4: var {p: foo, q: bar}: { foo: number, bar: number } = o;
                                                        ^ object literal
```

[Try Flow link here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzHMAXjAG8AHALjABYAmAGjAEcqAXHAVwFMBfAbky5SlMFDhxGLMACNcPKiVHiqAOw4BbaVxyNZOVRq14eRfALCoAxnBUBnODC4A6eAHMAFGLgBKPmGDANLQW1nYOzm7uer7+gezcYGBAA).

**Comment by samwgoldman** [comment]
Flow does support this, but the annotation should describe the destructured object, not the resulting bindings. The following code does typecheck:

```
var o = {p: 42, q: true};
var {p: foo, q: bar}: { p: number, q: boolean } = o;
(foo: number);
(bar: boolean);
```

**Comment by sarahlim** [comment]
Thanks! The [Flow docs](https://flowtype.org/docs/destructuring.html) for destructuring are pretty sparse on annotations. Is this by design, or could I add the above example in a PR?

**Comment by samwgoldman** [comment]
Improvements to the docs are *always* welcome! :)
