### ISSUE TITLE
npm package for flow-parser is not checking types

### ISSUE THREAD

**Issue by Aetet** [facebook/flow#271]
Hello.
I'm using [flow-parser@0.1.1](https://www.npmjs.com/package/flow-parser) and it does not check types like [flow-bin](https://www.npmjs.com/package/flow-bin) did. All unit tests was successfully passed. 

My testcase:
```js
/* @flow */
var x: number = 'Hello';
var f = function(a: boolean): boolean {
  return 1;
};
f(1);
```

For checking I'm using command: `flowvalidate test/fixture/a.js`

Output:
```
filename: test/fixture/a.js
PASSED test/fixture/a.js
1/1 passed
```

But there must be type mismatch error at `var x: number = 'Hello';`

So what's the trick?

**Comment by gabelevi** [comment]
I think there's a little bit of confusion about what the flow-parser package contains. It is literally just the parser that Flow uses. It doesn't do any type checking, it just generates an AST for the code you present.

It would be a great help to us if you could let us know what led you to believe that the flow-parser package contains the Flow type checker. We definitely want to avoid this sort of mix up!

@mroch - maybe we should rename `flowvalidate` to `flowvalidateparse` to avoid confusion?

**Comment by Aetet** [comment]
Oh, I see, thanks for quick reply.
Yes, `flowvalidate` give me wrong direction. Sorry. 
I think there must be in readme: **Warning: this module does not check flow types and validate only AST tree** or something like that.
