### ISSUE TITLE
Could React props be described as exact object types?

### ISSUE THREAD

**Issue by keyanzhang** [facebook/flow#2711]
``` js
class Foo extends React.Component {
  props: {|
    name: string,
  |};

  render() {
    return <div>{this.props.name}</div>;
  }
}

const bar2 = <Foo name="Jason" />;
```

The code above ([flowtype.org/try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzACUBTAQw0IF4wAnEgRwFcBLegCgHJ6L9OBKANyYcBYuUoARAPIBZMDXrM2JLj0oBaACZwAtgOGYYZXLjAAxOHDAkAHvhLYtZ0rwB0AYT0AHHI8IA3qhgYN60cN64AFxgAQA+wSFg2GS6JDEEtCzYAOYANIlxAL7CSWCJ9E4ktOz8sYkh9PhMtNhgADxaLABuAHwB+AAWLLhuYRGjKWlF7cBdfaVgRajLIniEAEZktABMCh2W1lMkVABEAFImOKdgwL3CQA)) results in an error:

```
16: const bar2 = <Foo name="Jason" />;
                 ^ props of React element `Foo`. Inexact type is incompatible with exact type
7:   props: {| 
            ^ exact type: object type
```

I think this would help for issues like facebook/react#1587, in which we can warn when an unspecified prop is passed into a component. Will this be supported? :)

**Comment by gcanti** [comment]
Before exact types were supported, using 

```js
type Strict<P> = P & $Shape<P>;
```

did work fine for me. 

@vkurchatkin The difference between `Strict<P>` and `$Exact<P>` seems that inflows to exact upper bounds must be exact [newtests/exact/exact_basics.js](https://github.com/facebook/flow/blob/dd0603e9d8c9d5fb99a40f0b179a4d6a2b9e66b7/newtests/exact/exact_basics.js)

---

Note: using the new `jsx` pragma (v0.34), functional components seem to work as expected with exact types

```js
// @flow
// @jsx React.createElement

import React from 'react'

const Foo = (props: {| name: string |}) => <div/>

;<Foo name="Jason" />
;<Foo name="Jason" a="s" /> // <= error
```

while class components still don't work

**Comment by samwgoldman** [comment]
Yeah we want to do this but we need to fix JSX children first

**Comment by omerzach** [comment]
This already seems to work for components in different files—if I define that `Foo` in one file and create `bar2` in another I don't get the `Inexact type is incompatible with exact type` error.

Is that what you meant by "fix JSX children first" or is there some other bug related to the two things being in the same file?

**Comment by jedmao** [comment]
I've got the same issue with [this syntax](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAihkYgFdoOAApV0AZ1ABeUAG8APolBrQAIzikA1gC5QUnFmQA7AOaIlAX1bsuPCbGlzFK9Zu06A-AaMmLABpVdVRYABNkSGRCLClfQ2MzcwBtAF0rWzZSaGIpGQAxWFhQQgAPHEJTcJkiMhwAOgBhakxTKpwAHn5BEXFJKUDQJ2khgDdYZHCAPkU2DyNiHGRSUHCBYVERmXkFEI81LVhdA1pIYtp90CyrhmrYgAoASjmD9VJYUyNFT2OdIbCkWisRk1lcOAAFsgpA10ANWG81AwcEIsKZQA8rojQJ1ImNFA1CQpfroAREojE4tcwcBplj1E8EeprIgWYgcnkZAAhYhYUoVKo1AiMRotDCfDqdCZTcaTcKyqazPYASDu6ywz1e6lVhBRaIx9I8ys6RVghoOysBFJBsgUKVoUNoaTBoHNHlp5sZVxZbPKmFwaw2fVAptYQA).

**Comment by iainbeeston** [comment]
I'll second what @omerzach said. If I change the example above to define the component in one file and require it and use it in another, I get no error. I'm also using react components with exact object types successfully in a larger project.

**Comment by IanVS** [comment]
>Yeah we want to do this but we need to fix JSX children first

Since flow can understand JSX children now, maybe this is unblocked?

**Comment by asolove** [comment]
In Flow v0.53, [this seems to work now](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAihkYgFdoOAApV0AZ1ABeUAG8APolBrQAIzikA1gC5QUnFmQA7AOaIlAX1bsuPCbGlzFK9Zu06A-AaMmLABpVdVRYABNkSGRCLClfQ2MzcwBtAF0rWzZSaGIpGQAxWFhQQgAPHEJTcJkiMhwAOgBhakxTKpwAHidpQNAAN1hkcIA+RTYPI2IcZFJQcIFhUR6ZeQUQjzUtWF0DWkhi2g3QLOOGatiACgBKcc31UlhTI0VPHZ0+sMjo2JlrVxwAAtkFIGuhJFJWPc1AwcEIsKZQJdjtDQJ1Iv1FA1sQo3rpPhEojE4id-sARij1NcoeprIg6YgcnkZAAhYhYUoVKo1AiMRotDBPDqdQbDPqi0bjACQ5wWWBud3UMsIcIRSMpHilnSKsA1mylXyJv1kChStGBtDS-1Aeo85L11OOdIZ5UwuHmixEeB1rCAA).
