### ISSUE TITLE
Project wide outline

### ISSUE THREAD

**Issue by andreypopp** [facebook/flow#2716]
I want to entertain an idea of project wide outline functionality. Basically it is similar to what I've done in https://github.com/andreypopp/vim-flow-outline but for the entire source tree (excluding dependencies of course). I found module-wide outline to be so much useful. You can also think of how ctags work.

I think calling `flow ast --json` for each file in source tree isn't sustainable. Because of that I have a question — what's the best way to do that? To be honest, right now, I think the only way to implement that is to fork flow and add a new command (on server protocol probably) to collect outline and format it accordingly. What do you think?

**Comment by SamChou19815** [comment]
This looks like document symbols of language server protocol. We already have that now, and we are unlikely to implement something to support other custom format.
