### ISSUE TITLE
Weird error messages when adding object to number

### ISSUE THREAD

**Issue by chicoxyzzy** [facebook/flow#2719]
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBGMBqMBvAXwG4g

The weird part is that first two errors are pointing to the same `1` which is mentioned as number and string at the same time and it is also mentioned that I try to add it to itself

```
3: 1 + {};
   ^ number. This type cannot be added to
3: 1 + {};
   ^ string
3: 1 + {};
       ^ object literal. This type cannot be added to
3: 1 + {};
   ^ string
```

**Comment by chicoxyzzy** [comment]
IMO the output above should look like

```
3: 1 + {};
   ^ string (coerced from number). This type cannot be added to
3: 1 + {};
       ^ object literal. This type cannot be added to
3: 1 + {};
   ^ string
```

**Comment by mroch** [comment]
that's bizarre... it should just be

```
3: 1 + {};
       ^ object literal. This type cannot be added to
3: 1 + {};
   ^ number
```

I'll look into it. thanks!
