### ISSUE TITLE
Exporting then importing typed alias does not type check

### ISSUE THREAD

**Issue by neurosnap** [facebook/flow#2722]
I might be doing something wrong, but according to the docs the following should properly type check.

types.js
```js
export type Person = {
  name: string,
  address: string,
};
export type People = Array<Person>;
```

This doesn't show any flow errors:

index.js
```js
import type { People } from './types';

export function getPeople(type: string): People {
  if (type === 'friend') return 0;
}
```

But this does:
```js
import type { Person } from './types';

export function getPeople(type: string): Array<Person> {
  if (type === 'friend') return 0;
}
```

Errors:

```
array type This type is incompatible with an implicitly-returned undefined
number This type is incompatible with the expected return type of array type
```

**Comment by jeffmo** [comment]
Based on the error, it seems like you might be missing an `// @flow` comment at the top of the file with the type exports?

**Comment by neurosnap** [comment]
Bah you're right!  Thank you so much for your help!

**Comment by jeffmo** [comment]
No prob!

(cc https://github.com/facebook/flow/pull/2392 for tracking instances of this general problem)
