### ISSUE TITLE
Not allowed interface extension

### ISSUE THREAD

**Issue by daveGregorian** [facebook/flow#2732]
Does anyone know why this kind of extending interfaces doesn't work with flow?
It is accepted in typescript. Is this maybe a bug or is it a common pattern?

```
	declare interface normalCar {
		Color: ?black;
	}

	declare interface redCar extends normalCar {
		Color: ?red;
	}

	declare interface red {
		x: ?string;
	}

	declare interface black {
		y: ?boolean;
	}

**Comment by gcanti** [comment]
How would be the equivalent typescript definition?

**Comment by daveGregorian** [comment]
Alright, sorry. I did a dumb mistake. I placed the optional question mark at the wrong spot. It should be right after the property key and not before the property type.
