### ISSUE TITLE
flowtype.org/try no longer underlines errors

### ISSUE THREAD

**Issue by kyldvs** [facebook/flow#2734]
Chrome
Version 54.0.2840.71 m (64-bit)

Microsoft Windows 10 Enterprise
Version 10.0.14393 Build 14393

![screenshot 30](https://cloud.githubusercontent.com/assets/1830497/19909626/c4504c58-a045-11e6-9d4d-e9e173045294.png)

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeAzhobgQLxgDeqYYAdgIYC2eAXGGQE4CWTAOYAaBmABuLGAFdS3PoNGoAvgG50AYzhMyk6XJJgaAbXFnGjAORQ4cK2Mt1xT1h2427Dl2BWOwALpiARqowMBgsIhgmiwYmgAWpGAYCfwkqNq6GCmkGACSGHi8cXC83IXFLABGMHgAPCaKwiJEeRT4AQB8xvqypKHhYDgsJCSkmTp6RWQAsiw43PM49c2ibWQdeD00THhIywAUUv0kAJSDESNjE1nTecsATEsLqxgCLcwybNXFO8z7MBHEwmKwzDAOMBgvJWAIBC5AA

**Comment by mroch** [comment]
my bad. there's a JS error because I made tryFlow.js use an API that's only in master. if you change the version selector to `master` it starts working again.

**Comment by kyldvs** [comment]
Yup master works. Up to you if you want to fix old versions then :)
