### ISSUE TITLE
Flow does not catch assignment to imported const

### ISSUE THREAD

**Issue by mcheshkov** [facebook/flow#2736]
`a.js`

```js
// @flow
export const C = 7;
//C = 8; // this will trigger "const cannot be reassigned" error
```

`b.js`
```js
// @flow
import {C} from "./a"
C = 8; // this will not
```

What is interesting, is that babel catch this with `"C" is read-only`, even in form `if (false) C = 8;`

**Comment by jeffmo** [comment]
Thanks for the report!

It's true that an imported `const` *is* an error just as assigning to any `const` would be.

Additionally: While it's true that assignments to imported `let`s and `var`s are not an error in pure JS, they are a silent no-op -- so it makes sense that we should just always give an error for them as well.
