### ISSUE TITLE
calling optional function that has React.PropTypes.func with null check

### ISSUE THREAD

**Issue by bakesteve** [facebook/flow#274]
Same as [this SO question](http://stackoverflow.com/questions/27560997/optional-function-prop-in-react-component-flow-type-check-fail) I have a prop, with PropTypes.func, but am getting 
```
call of method exampleFn
Function cannot be called on possibly null or undefined value
```
despite various methods of null checking, but it only passes if I use the answer given on SO:
```
var exampleFn = this.props.exampleFn || null;
  if (exampleFn) {
    exampleFn();
  }
```

**Comment by samwgoldman** [comment]
Possibly related to the fact that [mk_proptype for func is incomplete](https://github.com/facebook/flow/blob/86d7eb212f5c91e61c25e0b8cec0ee2bb74c8fdd/src/typing/type_inference_js.ml#L3008)

I don't know enough about the internals to be sure this matters, but it seems like exampleFn is treated as Any.

**Comment by kharin** [comment]
This work for me:
```JavaScript
handleClick() {
  if (this.props.exampleFn) {
    this.props.exampleFn();
  }
},
```
Or even:
```JavaScript
handleClick() {
  (this.props.exampleFn: any)();
},
```

**Comment by samwgoldman** [comment]
This is working correctly now. Please reopen if you're still having an issue.
