### ISSUE TITLE
Support requireJS type plugins

### ISSUE THREAD

**Issue by davidswinegar** [facebook/flow#2740]
Any require statement that uses RequireJS plugins (http://requirejs.org/docs/plugins.html) currently throws an error.

As an example, in some places I have in my code:
```
const _t = require('i18n!nls/foo');
```

Even though the resource name corresponds to a module (`nls/foo`), this throws an error when using flow:
```
 10: const _t = require('i18n!nls/foo');
                ^^^^^^^^^^^^^^^^^^^^^^^^ i18n!nls/foo. Required module not found
```

The correct behavior should be to separate the string based on the `!` and check for the existence of the module name (the part after the `!`, in this case `nls/foo`).

Please let me know if you need more clarification!

**Comment by wbinnssmith** [comment]
This could be solved more generically with the ability to use custom resolution algorithms for module lookup, or disabling module resolution all together, maybe.

**Comment by davidswinegar** [comment]
Update: this can be solved through flowconfig options, specifically the module name mapper: https://flowtype.org/docs/advanced-configuration.html#options
