### ISSUE TITLE
flow doesn't follow `export * from`

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/flow#2743]
When I use `export * from` I got `Property not found in` error.

```
flow-bin@0.34.0
```

**Comment by jsdnxx** [comment]
duplicate of #940

**Comment by alexfedoseev** [comment]
@jsdnxx No, it's not. `export * from` is in specs. The issue you linked is about proposed non-standard syntax.

**Comment by TrySound** [comment]
This is probably fixed. I don't have problems with `export *` statements this time.

/cc @vkurchatkin
