### ISSUE TITLE
ESLint collision `no-duplicate-imports`

### ISSUE THREAD

**Issue by neurosnap** [facebook/flow#2744]
I couldn't find any documentation on how to handle duplicate imports using flow.  The following example causing eslint to complain about duplicate imports.  I'm not sure if there's a better way to import types from a module I'm already importing. 

```js
import { put, select, call } from 'redux-saga/effects';
import type { IOEffect } from 'redux-saga/effects';

function* testSaga(): Generator<IOEffect, *, *> {}
```

Any feedback would be greatly appreciated!

**Comment by vkurchatkin** [comment]
No, there is no better way, AFAIK. It would be nice to write something like:

```js
import type { IOEffect }, { put, select, call } from 'redux-saga/effects';
```

**Comment by erikdesjardins** [comment]
FWIW you can work around this by using [eslint-plugin-import](https://www.npmjs.com/package/eslint-plugin-import)'s [`no-duplicates`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) rule instead of `no-duplicate-imports`.

**Comment by samwgoldman** [comment]
I think eslint should just ignore `ImportDeclaration` nodes when their `importKind` is `type`.

**Comment by jfmengels** [comment]
> I think eslint should just ignore ImportDeclaration nodes when their importKind is type.

ESLint will not handle things that are not in the spec. I agree with @erikdesjardins, [`no-duplicates`](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-duplicates.md) from `eslint-plugin-import` is the way to go.

**Comment by jeffmo** [comment]
> ESLint will not handle things that are not in the spec.

I think that's the intent, but is it actively ignoring `import type` given that it's the same kind of node as `import` just with a special `importKind` flag? Seems like an easy bug to have

**Comment by jfmengels** [comment]
AST-wise, `import` and `import type` are the same ([see here](https://astexplorer.net/#/Xlz9icaP4i)), it's just that babel-eslint adds an additional property `importType` property to import type nodes (`type` for `import type`, `value` for normal `import`). Since ESLint doesn't want to support `import type` (until it's in the spec) in its core rules, it doesn't check the value to differentiate both.
