### ISSUE TITLE
optional attributes on object literals

### ISSUE THREAD

**Issue by gabor** [facebook/flow#2745]
this fails:
```
const d = { name: 'n1' };
if (Math.random() < 0.5) {
    d.value = 5;
}
```

this works:
```
const d: {name: string, value?: number} = { name: 'n1' };
if (Math.random() < 0.5) {
    d.value = 5;
}
```

but now consider that `d` is a large object, with many keys, but only one optional key, like:
```
const d = {
   name: 'n1'
   // lots of lines here
};
if (Math.random() < 0.5) {
    d.value = 5;
}
```

it is very inconvenient to explicitly type all the object-keys in such a case (because there are so many of them), and considering flow can infer key-types just fine when none of them are optional... is there a way to tell flow that this one attribute is optional, and the rest should be just inferred?

**Comment by vkurchatkin** [comment]
Simple workaround:

```js
const d = {};

d.name = 'n1';

if (Math.random() < 0.5) {
    d.value = 5;
}
```

If you create an empty object, Flow treats it as "unsealed" to support such a use case. This mode is a bit unsound, so it is not used by default for non-empty objects.

**Comment by samwgoldman** [comment]
Another option:

```
var o = { a, b, c, d, e: (void: ?number) };
o.e = 0;
```

**Comment by gabor** [comment]
@vkurchatkin hmm... but unfortunately it seems that if i start with an empty-object, flow does not report accesses to properties that does not exist anymore. for example, the following code produces no errors:
```
const d = {};
d.name = 'n1';
console.log(d.somethingElse);
```
the same code using an object-literal syntax generates an error:
```
const d = {name: 'n1'};
console.log(d.otherThing);
```

so i'd like to keep this feature of flow.

**Comment by gabor** [comment]
@samwgoldman sorry could you explain your approach? the example-code you showed does not compile, and i'm unsure what it means...

**Comment by samwgoldman** [comment]
@gabor Sorry, I wrote `void` when I meant `undefined` (updated the comment).

The `(undefined: ?number)` part is [type cast syntax](https://flowtype.org/docs/syntax.html#typecasts).

If you write `{ p: undefined }`, Flow currently infers the object type to be `{ p: void }`, so you can't assign, say, a number because numbers are not compatible with void. By saying `{ p: (undefined: ?number }`, Flow infers `{ p: ?number }` which means you can later on assign a number (or null or undefined) to the property.

**Comment by gabor** [comment]
@samwgoldman thank you, this fixed my problem :)

(hmm.. how does this work, should i close the issue now?)

**Comment by samwgoldman** [comment]
glad your problem is resolved!
