### ISSUE TITLE
Recursion limit exceeds

### ISSUE THREAD

**Issue by freddi301** [facebook/flow#2746]
Why this explodes every time?
```javascript
export type Functor<A> = {
  map<B>(f: (a: A) => B): Functor<B>;
}
```
Doesn't matter how i rewrite definition or usage

**Comment by gcanti** [comment]
I can't reproduce (Flow v0.34)

**Comment by gabelevi** [comment]
[I think I can](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiArgHYDGGcATgDwCCAfGALxgDeqYYAtgIY5aAIUYAKKAC4wovlPoBKVsyHypJClToiA3KgC+6AG59qYOACMAVqw57dFywDp+OG1DKUAlnFLSoi9jBqPAxial8HbTA7dFEHNQ9NWlJiHnM8akZ5IA)

@freddi301 - what are you trying to do with this type? Flow shouldn't hit infinite recursion, so this is a bug, but it's not obvious to me what you're trying to do with `Functor`.

**Comment by freddi301** [comment]
Hi, sorry for missing info.
You can see it here https://github.com/freddi301/flow-runes
If i try to do a thing like `const x: Functor<T, string> = Applicative<T, string>` (T is phantom type)
Using the Maybe class for example, the recursion limit occurs.
Let me know if need more details.
I will push some guilty example.

**Comment by freddi301** [comment]
Checkout master, `npm install` `npm run flow:test`
commit (https://github.com/freddi301/flow-runes/commit/daa8b819be8d65cff023d19ebb14e57436cec7c7?diff=unified)

**Comment by gcanti** [comment]
Another example

```js
class Nothing {
  map(): Nothing { return this }
}

class Just<A> {
  value: A;
  constructor(value: A) { this.value = value }
  map<B>(f: (a: A) => B): Just<B> { return new Just(f(this.value)) }
}

type Maybe<A> = Just<A> | Nothing;

type Functor<A> = {
  map<B>(f: (a: A) => B): Functor<B>;
};

const x: Maybe<number> = new Just(1)
const y: Functor<number> = x // => type application of identifier `Maybe`. *** Recursion limit exceeded ***
```

**Comment by SamChou19815** [comment]
These are all fixed a while ago.
