### ISSUE TITLE
Class instance should not be allowed to cast to an arbitrary object type.

### ISSUE THREAD

**Issue by iamchenxin** [facebook/flow#2749]
Test with 0.34, hope this behavior will be forbidden, it is too counterintuitive.
( [flowtry here](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJlgM5GgDC0oA3qEQFy0AuOAlgHYDmANKJAwGIBXNukYtYbUAF8UGbHlAA3XAWh0KAbkToJRRqFgAjBjQDaAa1QBPBntacAugzaCAtodQ5poALyqNoCC0ABawgtDIoGyw+ljQcPCgjMEspCyuAA7QLOgsjNBWBMSMAHTauvr0UW4eXn5GJUQBQQ1ppFhM9hyg7GioyGVAA)): 
```
declare class Cl { s: string, f: Function }
declare var cl:Cl;
const ob: { [key: string]: number } = cl; // should not allow this implicitly cast.
const s: number = ob.s; // ob.s is a string indeed.
```

**Comment by SamChou19815** [comment]
This is now banned
