### ISSUE TITLE
Private methods on classes

### ISSUE THREAD

**Issue by danvk** [facebook/flow#275]
TypeScript has a [private modifier](http://www.typescriptlang.org/Handbook#classes-privatepublic-modifiers), which prevents code outside a class from accessing particular properties and methods. Something similar could be done in Flow.

**Comment by Downchuck** [comment]
The modifier is also a shortcut (sugar), as is the public modifier.
```
constructor( public x : string ) {}
// vs
constructor(x : string) { this.x = x; }
```

**Comment by TrySound** [comment]
Flow also has own private fields with `munge_underscores` option.
```
class A {
  _myPrivateMethod() {}
}
```
Also native private fields are partially implemented and will be ready soon.

This probably can be closed.
/cc @vkurchatkin

**Comment by vjpr** [comment]
There is now a proposal for this: https://github.com/tc39/proposal-private-methods

**Comment by vjpr** [comment]
@TrySound Does this include methods?

**Comment by TrySound** [comment]
No, I misread it's about methods.

**Comment by taylorgoolsby** [comment]
Is there a way to designate private constructors? I have a class which should only be created via a static factory method.
