### ISSUE TITLE
can flow tell me the inferred type of something?

### ISSUE THREAD

**Issue by gabor** [facebook/flow#2750]
can flow tell me the type of an object that it inferred? something like using ":t" in the haskell-repl.
for example (haskell):

```
Prelude> dbl x = x+x
Prelude> :t dbl
dbl :: Num a => a -> a
```

the reason i'm asking for this is that sometimes when i apply flow to a codebase that did not use flow before, i get some flow-errors, and it would be very helpful to ask flow: "ok, what do you THINK the type of this function is?"

**Comment by freddi301** [comment]
`flow --help`
```
  suggest         Shows type annotation suggestions for given files
  type-at-pos     Shows the type at a given file and position

```

**Comment by gabor** [comment]
d'oh..i should have read the help...thank you for the info.
