### ISSUE TITLE
Offer statistics about typing

### ISSUE THREAD

**Issue by danvk** [facebook/flow#276]
Closure Compiler prints something like `93.4% typed` when it finishes compiling your code. A similar option would be helpful for Flow. Unless you're in the habit of performing illegal operations on all your function parameters, it's easy to assume that Flow has correctly inferred their types when, in fact, it's assuming they're `any`.

Alternatively, some kind of source rendering which indicates inferred types for variables & parameters would be fantastic.

**Comment by samwgoldman** [comment]
@mroch landed `flow coverage` in 0ae34ae551b3ba17ccd0f9fbadb3cd73b3d17ddc
