### ISSUE TITLE
libs not getting included

### ISSUE THREAD

**Issue by dlants** [facebook/flow#2760]
I have a project set up with a `flow-declarations/globals.js` file. When i set up `.flowconfig` with
```
[libs]
flow-declarations/
```
, flow does not use globals definitions when running `flow check`.
```
[libs]
flow-declarations/globals.js
```
does, however.

This is not consistent with the documentation here:
https://flowtype.org/docs/advanced-configuration.html#libs

I'm on OS X 10.11.6, flow 0.34.0

**Comment by SamChou19815** [comment]
This is likely fixed a long time ago.
