### ISSUE TITLE
Any way to declare getters in interface?

### ISSUE THREAD

**Issue by arv** [facebook/flow#2761]
Given:

```js
/* @flow */

interface A {
  a: number;  // should really be get a(): number
};

class B {
  get a(): number {
    return 42;
  }
}

const b: A = new B();
```

To make this work in 0.34 I would have to mark `a` as covariant which doesn't seem right.

**Comment by samwgoldman** [comment]
Yeah, we should probably support this. Marking `a` as covariant in the interface *is* right, and if we just cared about variance we wouldn't need to support `get` and `set` in interfaces/types at all. However, since a getter's return type and setter's param type can be different, we do need to support that in declarations as well.

**Comment by vkurchatkin** [comment]
> getter's return type and setter's param type can be different

But is it really useful? It seems that it will make object type a lot more complicated.

**Comment by samwgoldman** [comment]
It's only mildly useful, but the code we used to have to ensure they were the same was worse than allowing them to be different. You might want to write code like this, which we now support:

```
class C {
  _x: string = "default";
  get x(): string { return this._x }
  set x(value?: string): void { this._x = value || "default" }
}
```

**Comment by samwgoldman** [comment]
As far as making object types more complicated, we already have the necessary structure in `Type.Property.t`, we really just need to add parsing support.

**Comment by arv** [comment]
Having classes with getters only is very useful. Both semantically and for performance. It allows hot instances of a class to be smaller in the case of constant properties that can be shared by a getter on the prototype.

**Comment by mroch** [comment]
`HTMLAnchorElement`'s `href` is an example that needs this.

`elem.href` is always a string (returns empty string if there's no href), but can be set to `null`.

**Comment by mroch** [comment]
I implemented this before realizing that since it's gated by `unsafe.enable_getters_and_setters`, I can't use it for `HTMLAnchorElement`. I guess the rest of you will get to have all the fun.

**Comment by btipling** [comment]
How do you even mark a getter as covariant in an interface? I wasn't able to achieve that.

I get a syntax error for:

```
interface A {
  +a: number;  // should really be get a(): number
};
```
