### ISSUE TITLE
$Shape of map with constrained keys

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#2762]
My use case is to use shape of one map as an upper limit for a second map.

But I found inconsistent checking of shape of map.
I tried to come up with minimal example:

```js
type Foo = $Shape<{ [key: 'a' | 'b']: string }>
function useFoo(foo: Foo): void {}

useFoo({ c: '' }); // this does not typecheck - OK

type Bar = { [key: 'c']: string }
const bar: Bar = { c: '' };
useFoo(bar); // this does typecheck although value of bar is the same as the value that does not

function doWithBar(bar: Bar, baz: { [key: 'a']: string }): void {
  // my use case is to not allow this:
  useFoo(bar);

  // but to allow this:
  useFoo(baz);
}
```
[Try flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGACQDKAFgIb4A8A3mANoDWeWAXGAHJ6AsAB9BAIwEBdfgGcMAJwCWAOwDmYAL4A+VFACuqgMYZlcVWANy8xOAAooJfnYCU-AG5xlAEzAstdGtbEns2Y34BES1XAG4wYGAwDFplOTAfODx01TgMZNw8Y1oizjAAWjAAeQBpdGx8MAAhekVyfw5uPkFjGXklNU1A4wsFMAlW-ha2inDI6NjUYLt7CcU4hKSUtIys9IaikuMy+hgUuAN1WjAPU4MCOChx1rAdlII5egBbAnp9kpudwIKXo+Uy2TAuQw6EMJjMFl2AHVlClpqtJs1WgAaZ4AL34bC4PEiwlkYAUKg02ncN28fhYqDAmzAXywVhsYGMfwIb1IULAp3gSG2cl4jPZIQcazi6CZiXGBnyGFIgsQyVSovFy1CE1xMsCQA)

Removing $Shape leads to consistent type checking, but it is no longer an upper limit, so `baz` will not typecheck as well.

**Comment by gcanti** [comment]
I think that `$Shape` is not supposed to work as upper bound for objects as maps: [the value type of the map does not interfere with the types of the properties of the record](https://flowtype.org/docs/objects.html#maps-as-records)

```js
type Foo = $Shape<{ c: string, [key: 'a' | 'b']: string }>;
type Bar = { [key: 'c']: boolean };

function f(foo: Foo): void {}

declare var x: Bar
declare var y: { c: boolean }

f(x) // <= no error
f(y) // error
```

**Comment by minedeljkovic** [comment]
Thanks @gcanti .

Actually I was not planning to use this to constraint type of the properties, but keys (property names) themselves.

Anyway, in the meantime I realized that I completely missed the need for the order in my use case, so map is not a good model anyway.
And without a proper use case I can think of, I am closing this. :)
