### ISSUE TITLE
Disjoint union incosistency

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#2763]
Minimal example:
```js
type Foo =
  | { type: 'A' }
  | { type: 'B' }

function f(foo: Foo): Foo {
  if (foo.type !== 'A') throw new Error();
  const { type } = foo;
  return { type }; // this errors but it should not since type can only be 'A'
}

function f1(foo: Foo): 'A' {
  if (foo.type !== 'A') throw new Error();
  const { type } = foo;
  return type; // this one is OK. It typechecks since 'type' can only be 'A'
}
```
[Try flow](https://flowtype.org/try/#0C4TwDgpgBAYg9nKBeAUFKAfKBvKpIBcUA5AILFQC+amOe4ERxAQhdSgGYCuAdgMbAAlnB5QOACg4Ii8OAEoZCHDUEcokhADp80AIRIkJcnLwALAE5wA7lB4QbAUXOXz4uQG4afEQGdgdHSpkMQRPdHMIYC5zUVxAyncoAHoks0EfKAhnOHMMgCMuf0F-H1M4LgAbABNbOBLBfmhAvgBDUREKkCg86DJiFHZufiERMQBGDThFeSZyZXRVdSk4bQYofUM+k2ALa1t7KCcXNzCobx4-ALXKYOXTiKiY+khElLSMkWh0qAB5AGlNFAAJL+HR8UwQPgAawyPgafF6OgorXaPE63V65AGQA)

**Comment by vkurchatkin** [comment]
Here is even smaller test case:

```js
function test(): { t: 'A' } | { t: 'B' } {
  const t = 'A';
  if (t) {}
  return { t };
}
```

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
