### ISSUE TITLE
Disjoint union not type checking branch properly.

### ISSUE THREAD

**Issue by matthewbpt** [facebook/flow#2768]
The following code is not being type checked correctly. The `id` property is in the disjoint union `AppAction`, but the function `appReducer` is not correctly determining the type for the branch the  `action.type === 'REMOVE'`. According to your blog post this should work https://flowtype.org/blog/2015/07/03/Disjoint-Unions.html . I'm using flow version 0.33, but I tried the same thing on 0.34 [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAKuATgM5wB2YAvGAN6phgCWAJgFxgUCuAtgEYkANIzBRmZdADkAhr1ydS6YswoBzEUxgyls+YuWqNomWoVc+g4qgC+AblQYc+AIKtWNemCx5OAchcAEUC-ITA8MkpOIkiqeyc8MAAlXF44ADd8WjpvZ38kgFEAWQB5ADUC0JYOCwESMHiffBTSXHRPHKb8goBlAoAVPwaHBNdsbBcAY3RmSk83DwAfZNSM-GWWtpGmsB70GXQs+lE8OGwYcxdiYhlMAB4Y8goAPltHScolMBlxlNZuSb1WgACiUB3Me3BHXCuDOF04AG0ALo2MIyaazCicFzjKYzSgASk4kMONGexyYzCgYGB6PxFAAdDtqCywAFgn4CRSmGBiG1uMQqDlTudzAiGRKwYcGSKLmiMZQZSQnmAUQ4mDZRLgYK0WNTaQrGczWX5CqUKpzuUw+egBUKYXDzFLcErHQzxDBDsRgREVdRyb7FWwwABCVl0zEMthc+IarU6-BUmkRxXG2im3oDS0MHnW-mCryysVI4aiTWiG12sDOhz2IA) with the same result.

```
/* @flow */
type Person = {
  id: number,
  firstName: string,
  lastName: string,
  age: number
};

type Add = { type: 'ADD', person: Person };
type Remove = { type: 'REMOVE', id: number };
type Reset = { type: 'RESET' };

type AppAction = Add | Remove | Reset;

type State = {
  people: Array<Person>
}

const appReducer = (state: State = { people: []}, action: AppAction): State => {
  if (action.type === 'ADD') {
    return { people: [...state.people, action.person ]};
  }
  else if (action.type === 'REMOVE') {
    return { people: state.people.filter(person => person.id !== action.id) };
  }
  else if (action.type === 'RESET') {
     return { people: [] };
  }

  return state;
};
```

Error:
```
24:     return { people: state.people.filter(person => person.id !== action.id) };
                                                                            ^ property `id`. Property not found in
24:     return { people: state.people.filter(person => person.id !== action.id) };
                                                                     ^ object type
```

**Comment by vkurchatkin** [comment]
This can be fixed like this:

```js
const appReducer = (state: State = { people: []}, action_: AppAction): State => {
  const action = action_; // const alias
  ....
};
```

The problem is that argument binding is mutable and Flow assumes that it can change when `filter` callback is called. In theory it should be possible to prove otherwise, because it is known that `filter` calls callback  only synchronously and `action` binding is not actually mutated anywhere, but Flow doesn't do such analysis currently.

**Comment by matthewbpt** [comment]
Ah I see, that makes sense. So the workaround is to bind the id to a new variable in the branch and then use that in the filter callback like so:

```
/* @flow */
type Person = {
  id: number,
  firstName: string,
  lastName: string,
  age: number
};

type Add = { type: 'ADD', person: Person };
type Remove = { type: 'REMOVE', id: number };
type Reset = { type: 'RESET' };

type AppAction = Add | Remove | Reset;

type State = {
  people: Array<Person>
}

const appReducer = (state: State = { people: []}, action: AppAction): State => {
  if (action.type === 'ADD') {
    return { people: [...state.people, action.person ]};
  }
  else if (action.type === 'REMOVE') {
    const id = action.id;
    return { people: state.people.filter(person => person.id !== id) };
  }
  else if (action.type === 'RESET') {
     return { people: [] };
  }

  return state;
};
```

This works for me. Thanks!

**Comment by lvdang** [comment]
I made a minor change to the  program to destructure but running into these errors. It is complaining about data is incompatible. 




 https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAKuATgM5wB2YAvGAN6phgCWAJgFxgUCuAtgEYkANIzBRmZdADkAhr1ydS6YswoBzEUxgyls+YuWqNomWoVc+g4qgC+AblQYc+AIKtWNemCx5OAchcAEUC-ITBWGXQZTiIySjB7JzwwACVcXjgAN3xaOm9nfxSAUQBZAHkANSLQ8MjoiwESBIcffDTSXHRPPNbCooBlIoAVP2bHVrAXbGwXAGN0ZnjaNw8AH1T0rPx19s6HJPx+qPQc+lE8OGwYcxdiYhlMAB5Y8goAPltHWcolMBlptKsbizJq0AAUSki5iOUO6YAuV3MAG0ALo2MJ0VphCJRGycKYzeaLCgASk4MJONDeZyYzCgYDBE2ozLAAWCowAZBz8hd6TiZGAAIQsvw8RrEPwkmlMMDETrcYhUPII66cJEAOk1kJO6pVuGxdTAaIcTBsolwMA6LHpjOcNBFxXKVUl0qY3wovzYnn5JplcvQCqV8Nwl1VYG1uF1IcR6vEMBOxDBeDiVGo1OTr3VXuFtDYUsSpvNlvwdIZTIdA2GLoYMqY-sDXj1apRY0LonrivDx1wDnsQA
