### ISSUE TITLE
Declaring properties for class methods seem to cause invariant use errors

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2770]
Here is an [example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFTwGswAeADwBoxsA+MAb1TDCjgCcSAuMAClwBXDBgCmYgCY9+AN2wwhYntgCUYALz1ZcAJaTaUbLpg8A-PzGdOXHpXVawO-Q8bPJqAL7oseAgGURcSkKGjpGMUoAFzEAO0kCYlwyKloGZlYnBSU+bEyMOFjcKM4RKK45bOU1DLYASGEAByt+VUy6qIALXVwAOnlFMU0swczvNg5uQSCJaUrBlVd3Q2NTCysbTjtXJz1JVR53WrYwYVFZ-i6e-qq2tm9PIA) code:

```js
/* @flow */

class Task <x, a> {
  fork: (succeed:(value:a) =>void, fail:?(error:x) => void) => void
}

class Succeed <x, a> extends Task <x, a> {
  value: a
  constructor(value:a) {
  	super()
  	this.value = value
  }
  fork(succeed:(value:a) =>void, fail:?(error:x) => void):void {
    succeed(this.value)
  }
}
```

Which produces following error:

```
7: class Succeed <x, a> extends Task <x, a> {
         ^ Succeed. Covariant property `fork` incompatible with invariant use in
7: class Succeed <x, a> extends Task <x, a> {
                                ^ Task
```

As far as I can tell there is no mismatch between property type and a method but never the less error seems to appear.

**Comment by jeffmo** [comment]
Class methods are covariant but fields are invariant by default.

In this case you probably want an abstract method feature which we don't have yet -- but it's on @samwgoldman's radar. In the meantime, you can mark the field in the base class as covariant with the the new variance syntax:

[See updated example here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFTwGswAeADwBoxsA+MAb1TDAGoo4AnEgLjAAKXAFcMGAKYSAJn0EA3bDBES+2AJRgAvPXlwAltNpRs+mHwD8gid248+lTTrB7DTxq+moAvuix4CAGUxSRkKGjpGCUoAFwkAO2kCYlwyKloGZlYXJRUBbGyMOHjcGO4xGJ4FXNUNLLYASFEABxtBdWyGmIALfVwAOkVlCW0c4ezfNi5eYRCpWWrhtXdPY1NzKxs7bgd3FwNpdT5PerYwUXF5wR6+wZqOtl9vIA)

**Comment by mwalkerwells** [comment]
Glad to hear @samwgoldman is working on this...I'm running into this issue by declaring extensions to a flow-typed lib... :/

````javascript
// flow-typed definition
declare class express$Application extends express$Router {
  //...
}
declare class express$Router extends express$Route {
  //...
  use: express$RouterMethodType<this>;
  //...
}


//  myfile.js
type SessionExpressMiddleware =
  (request: expressSession$Request, response: express$Response, next: express$NextFunction) => mixed |
  (error: ?Error, request: expressSession$Request, response: express$Response, next: express$NextFunction) => mixed

export function SessionExpress(
  sessionOptions: expressSession$Options,
  sessionConstructor: sessionConstructor,
  expressApplication: () => express$Application
) {
  const express = expressApplication()
  express.use(sessionConstructor(sessionOptions))
  return express
}

declare class SessionExpress extends express$Application {
  use: (middleware: SessionExpressMiddleware) => mixed;
}
````
````javascript
    Error:
     95:   ((req: express$Request, res: express$Response, next: express$NextFunction) => mixed) |
                  ^^^^^^^^^^^^^^^ express$Request. This type is incompatible with. See lib: flow-typed/npm/express_v4.x.x.js:95
      7:   (request: expressSession$Request, response: express$Response, next: express$NextFunction) => mixed |
                     ^^^^^^^^^^^^^^^^^^^^^^ expressSession$Request
````
