### ISSUE TITLE
Unsafe behaviour for unrecognised case in case analysis

### ISSUE THREAD

**Issue by fizwidget** [facebook/flow#2774]
Example:
```js
type Action =
    { type: 'A', foo: number } |
    { type: 'B', bar: number };

const action: Action = {
    type: 'A',
    foo: 42,
};

if (action.type === 'A') {
    console.log(action.foo); // OK, as expected.
    console.log(action.bar); // Error, as expected.
} else if (action.type === 'B') {
    console.log(action.foo); // Error, as expected.
    console.log(action.bar); // OK, as expected.
} else if (action.type === 'C') {
    // None of these cause errors: why?
    console.log(action.foo);
    console.log(action.bar);
    console.log(action.baz);
}
```

Is this expected behaviour or a bug? My intuition says that inside the last `else`, we can't have any guarantees about what properties are available on `action`, so attempts to access properties should be type errors.

Tested in Flow 0.34.0.

**Comment by vkurchatkin** [comment]
This is the intended behaviour. Since `action.type` can only be `'A'` or `'B'`, else branch is considered unreachable.  `action` has `empty` type in this branch, which is more or less the same as `any`.

**Comment by jeffmo** [comment]
To be a little pedantic: `empty` is more like the opposite of `mixed` in that [nothing can flow into `empty`, but anything `empty` can flow into anything](https://flowtype.org/try/#0CYUwxgNghgTiAEA3W8QC5UFsAOAXAngNwBQxyM8UGAdgK6YBGIFAvKiefAxiDgfGwAsAJkJA).

(`empty` represents a type that has no possible values)

At some point we'd like to take advantage of `empty` to give errors like reachability scenarios like this -- but there's some work to do to get there.

**Comment by marcins** [comment]
I'm still getting my head around Flow, so apologies if this is a silly question - but in this case in particular (which I just ran into myself) why can't the static analysis determine that `action.type` can never be 'C' (since `action` is an `Action` which is a union type with a fixed set of `type`s), and therefore the comparison `if (action.type === 'C')` line is an error?

**Comment by vkurchatkin** [comment]
@marcins it can, and it does, but it's just not an error.
