### ISSUE TITLE
Node libdefs should return subtypes

### ISSUE THREAD

**Issue by jgrund** [facebook/flow#2776]
Consider a `HTMLElement`, which extends from `Node`.

Given:

```
const el2 = el
  .parentNode;
```

`el2` is of type `Node`. It should be of type `HTMLElement`.

**Comment by asolove** [comment]
Sadly, I think this is not quite true. If you call `.parentNode` on the top-level `<html>` element, you get back `document`, which is a `Node` but not an `HTMLElement`. :(
