### ISSUE TITLE
Unexpected $Diff behavior

### ISSUE THREAD

**Issue by guigrpa** [facebook/flow#2781]
Let's assume the following type definitions:

```js
type A = {
  a: string,
  b: string,
};
type B = $Diff<A, { a: string }>;
```

The following two cases behave as you'd expect:

```js
({ b: 'foo' }: B);  // OK; we omit the 'a' property
({}: B); // ERROR; 'b' must be a string
```

But this is unexpected:

```js
({ b: undefined }: B); // should be an error, but it typechecks
```

While I know `$Diff` is not part of Flow's public API, is this expected *or a bug*?

[This is a related question in SO](http://stackoverflow.com/questions/40283734/replace-the-type-of-an-object-property-in-a-flow-type) showing why I needed to do something like this. I'd love to find a way to *derive* a type from another one, so that a property that is mandatory in `A` (`a: string`) becomes optional in `B` (`a?: string`), without having to modify `A` (to make it parametric or to extract the varying properties). Any idea for a workaround?

**Comment by SamChou19815** [comment]
Fixed recently
