### ISSUE TITLE
Import failure with private modules

### ISSUE THREAD

**Issue by yuri-karadzhov** [facebook/flow#2783]
Flow fails on private modules with an error:
```
@private-module-root-path/private-module-name
Required module not found
```

**Comment by Deadarius** [comment]
Any update on this one? Can someone provide a bit of guidance for me so I could fix that and submit a PR?

**Comment by yuvalsv** [comment]
+1

**Comment by TrySound** [comment]
Can reproduce this, so I guess it's fixed.

/cc @vkurchatkin
