### ISSUE TITLE
flow-parser: Code generation

### ISSUE THREAD

**Issue by andywer** [facebook/flow#2785]
Hi there.

I tried to use the `flow-parser`, but I am not sure if there is a way to generate code from the resulting AST at all. Couldn't find any information about that and using [escodegen](https://github.com/estools/escodegen) with the flow-parser's AST unsurprisingly failed, too.

Is code generation currently possible at all?
Using `babylon` instead seems to be not an option, unfortunately.

Thanks in advance!

**Comment by andywer** [comment]
Update: `babel-generator` works, though. It's just not doing 100% well, since `babylon`'s parsing logic is slightly different to the `flow-parser`.

But I guess it's the best option right now?

(Sorry if this is too detailed or an unpopular request. A simple "no" is also a fine answer)

**Comment by gcanti** [comment]
> Using babylon instead seems to be not an option, unfortunately

Is there a particular reason?

**Comment by andywer** [comment]
@gcanti I was playing around with code transformation. One reason was #2659.

Turns out if I separate function type definition from function declaration, the flow parser is fine with omitting parameter names (`declare function add (number, number): number`) while babylon is not able to parse it.

**Comment by gcanti** [comment]
@andywer Ah yes, I'm playing with code transformations as well and noticed that with babylon. I guess both babylon and eslint/babel-eslint must still catch up with the new syntax

**Comment by likai757** [comment]
> @gcanti I was playing around with code transformation. One reason was #2659.
> 
> Turns out if I separate function type definition from function declaration, the flow parser is fine with omitting parameter names (`declare function add (number, number): number`) while babylon is not able to parse it.

Did you solve this problem? I have the same problem

**Comment by SamChou19815** [comment]
Flow parser is designed with only the use cases of Flow and prettier in mind. We won't intentionally break other use cases, but it's also unlikely that we can help with every possible integration.
