### ISSUE TITLE
Flow doesn't catch variable creation and use in the same line

### ISSUE THREAD

**Issue by Gasparila** [facebook/flow#2786]
Hard to explain in words, but the following is not considered an error in Flow:
```
let foo = foo(1, 2);
```
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjjAF4iSAKAJgBowAWASgG4g

As a contrast, TypeScript does note this case as an error:
http://www.typescriptlang.org/play/index.html#src=const%20foo%20%3D%20foo(2%2C%204)%3B

**Comment by mroch** [comment]
this is fixed in master (c9dbefcad9c3d124071b096ea12262325c6c31fa). :)

**Comment by Gasparila** [comment]
Great to hear. thanks!
