### ISSUE TITLE
How to type check arguments that come after omitted optional arguments

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#2787]
The signature for `httpServer.listen` in node docs is:
```
server.listen([port][, hostname][, backlog][, callback])
```
The current flow def is
```es6
listen(port: number, hostname?: string, backlog?: number, callback?: Function): Server;
```
Which doesn't match the semantics of the node docs (see #1684).  In node doc style the flow def does this:
```
server.listen(port[, hostname[, backlog[, callback]]])
```

Now `httpServer.listen` may ignore arguments after the last argument of the right type in the right position, which would mean the flow lib def should accept *any* arguments.  But in the long run it's probably more desirable to error on any extra invalid arguments, since it would let the user know their function call will probably not behave as they expected.

I tried to figure out a way to define node semantics but it just seems impossible right now.
Here's what I tried:
```es6
// @flow

const listen:
  (port?: number, hostname?: string, backlog?: number, callback?: Function) => void &
  (hostname?: string, backlog?: number, callback?: Function) => void &
  (backlog?: number, callback?: Function) => void &
  (callback?: Function) => void = () => {}

listen(8000)
listen('localhost')
```

This gives the following errors.  I haven't thought deeply enough about the the actual meaning of function union types to know if this is buggy behavior:
```
src/index.js:13
 13:   (callback?: Function) => void = () => {}
                                            ^ undefined. This type is incompatible with
 11:   (hostname?: string, backlog?: number, callback?: Function) => void &
       ^ function type

src/index.js:16
 16: listen('localhost')
     ^^^^^^^^^^^^^^^^^^^ function call
 16: listen('localhost')
            ^^^^^^^^^^^ string. This type is incompatible with
 10:   (port?: number, hostname?: string, backlog?: number, callback?: Function) => void &
               ^^^^^^ number


Found 2 errors
```

Is there a way to create the correct signature for `HttpServer.listen` right now?  If not, is there a plan for a way to make it possible?

To be specific, it would be ideal if flow could accept the following calls:
```es6
server.listen()
server.listen(8000)
server.listen('localhost')
server.listen(() => {})
server.listen(8000, () => {})
server.listen('localhost', () => {})
server.listen(8000, 'localhost', () => {})
// etc
```
And reject these:
```es6
server.listen({})
server.listen(true)
server.listen(() => {}, 8000)
server.listen('localhost', 8000)
// etc
```

**Comment by vkurchatkin** [comment]
You need to wrap branches of intersection:

```js
declare var listen:
  ((port?: number, hostname?: string, backlog?: number, callback?: Function) => void) &
  ((hostname?: string, backlog?: number, callback?: Function) => void) &
  ((backlog?: number, callback?: Function) => void) &
  ((callback?: Function) => void)
```

Also, see this: https://github.com/facebook/flow/issues/433

**Comment by jedwards1211** [comment]
@vkurchatkin oh, no wonder it wasn't working! thanks

**Comment by jedwards1211** [comment]
yeah, sounds like this is a dupe of that issue
