### ISSUE TITLE
Spreading paramaters in functions cause error but manually indexing succeeds

### ISSUE THREAD

**Issue by LegNeato** [facebook/flow#2788]
Using 0.34.0. Pretty self-explanatory.

I have a function that returns an array of parameters. When I spread into a typed function, flow complains about types. When I manually index and pass them as params, type checking succeeds.

**Comment by vkurchatkin** [comment]
Can you provide a test case?

**Comment by LegNeato** [comment]
Let me try to extract it from my codebase. Is there a command I can use to dump what flow sees between both runs?

**Comment by vkurchatkin** [comment]
You can use `type-at-pos` for this

**Comment by LegNeato** [comment]
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgEoFMDOALmAA4CGATmQLb5gAmcAxvgFxgAWhhJbm9uAG654JXBQB01OAC8AljBhkJcCgHNguAHYBaAKoBlYIxbAA6rgBGwAFJlBZA0wpyShYHijjtTXMABiAK5aTIRycFr4wBQEhAD65FTUuITi+OhMEURgaikACpQ0dAC8YAAUAJRgxQB8YADeqGBgmZHEUHBw1WAA5B1wPU0tWcSWlN0ALABMANxDrdljMt31AL5zzTGEgRRaYADaQ839ADRHYGMUZ83NS9dgALpzqxkjDHAAKhxkhF9yWmpumVKGoAIzsIguAEnMAgqbsLSBaiWcQwkEAZnYAHlLAArXChKq1BpDVAvVALYiJIrdXKEApJfCVOYYLB-OhQMgKOhkLT0MD4DhwQIwfkIVQAawkqEYXx+fwBZQkyuptAqLMwYHZAsCTF8uHoPLocmIguFoulsu+vw4-zUZVV+H2AAYHjDHftQW7SIVaPspg91UA

**Comment by vkurchatkin** [comment]
This is a duplicate of https://github.com/facebook/flow/issues/1307
Probably worth reopening

**Comment by goodmind** [comment]
Doesn't repro
