### ISSUE TITLE
Running code with default arguments

### ISSUE THREAD

**Issue by marijnh** [facebook/flow#279]
To have Flow allow calls to a function with not all of its arguments given, those arguments have to be given default values using the ES6 `=` notation.

Yet, JSX does not appear to be able to compile default arguments yet.

So how do I run Flow code that has optional arguments? (The problem is technically in JSX/react-tools/jstransform, but since I assume people are actually running their Flow code, I'm reporting it here in the hope that someone can point out an existing solution.)

**Comment by fkling** [comment]
Default arguments is on the radar: https://github.com/facebook/jstransform/issues/42 (same issue basically). [Babel](https://babeljs.io/) strips types (afaik), and understands JSX and default arguments.

**Comment by marijnh** [comment]
Babel does indeed do this, by default. I did not expect that, but it does solve my problem. Thanks for the fast response!

**Comment by marijnh** [comment]
(Might want to note this on the website, so that the next person doesn't run into this.)
