### ISSUE TITLE
Flow complains about this code when it shouldn't

### ISSUE THREAD

**Issue by praxiq** [facebook/flow#2790]
Consider the code:

    let i: ?number;
    [...more code...]
    let foo: string = ['a', 'b', 'c'][i] || 'd'

What I want to do is let `foo` be `d` if `i` is null, undefined, or out of bounds. It is not an error to index an array with `null` or `undefined` - it simply returns `undefined`. Whatever value `i` might or might not have, `foo` will correctly be assigned a string.

Expected behavior: The expression `['a', 'b', 'c'][i]` should have type `?string`, because it is guaranteed to return a string or undefined, depending on the value of i. The expression `['a', 'b', 'c'][i] || 'd'` should have type `string`, so flow should find no errors in the code.

Actual behavior: Flow complains that `i` might be `null` or `undefined`, and blocks it from being used as an array index at all.

I can clear the error like this: `['a', 'b', 'c'][Number(i)] || 'd'`

However, this changes the behavior. `null` is cast to `0`, so the expression returns `'a'` instead of `'d'`. `undefined` is changed into `NaN`, which has exactly the same effect, although flow doesn't seem to mind it.

(If flow really wants to be paranoid, perhaps the expression `['a', 'b', 'c'][Number(i)]` should be of type `?string`, since `i` is not guaranteed to be in the proper range... that's probably a bad idea though :)

**Comment by wessberg** [comment]
`arr[i] || 'd' would always evaluate to `'d'` where `i =: 0` since 0 is loosely equal to `false` in Javascript. 

Anyway, I think this is proper behavior from flow which reads it as: "Give me the item on index position [undefined | number] of this array, else give me 'd'."

**Comment by praxiq** [comment]
> `arr[i] || 'd'` would always evaluate to 'd' where i := 0 since 0 is loosely equal to false and OR expressions are loosely evaluated in Javascript.

I think you mean, it would always evaluate to to `d` when `arr[i]` is 0. In the example (and in my code), the array is guaranteed to contain only non-empty strings, so I'm not worried about that. Flow doesn't complain about that part anyway, though.

Flow specifically complains because the index to the array could be undefined. However, even if the index were defined, Flow can't guarantee that it's in bounds, and I'm arguing that indexing an array with `undefined` is just a special case of indexing with an out-of-bounds index, something that flow is specifically not designed to check for. 

I can see why it was implemented this way - `undefined` and `null` are special in flow, and that's generally a good thing. I just think in these cases, it would be useful if flow handled it, instead of by throwing an error, instead by returning a maybe type from the expression - this will still catch most errors in practice, unless it was an array of maybe types to begin with.

**Comment by TrySound** [comment]
Actually this can be a problem since `null` and `undefined` are converted to strings `"null"` and `"undefined"`, so one day you may get something different from `undefined`. Flow works correctly here.

This probably can be closed.
/cc @vkurchatkin
