### ISSUE TITLE
Support for spread operator for string

### ISSUE THREAD

**Issue by dudeinthemirror** [facebook/flow#2798]
Given the following code:

```
const str: string = 'abcd';
const charArr = [...str];
```
flow check should pass successfully (`spread operator applied on a string` - part of ES6)

Instead it generates an `incompatible type` warning:

```
20: const charArr = [...str];
                         ^^^ string. This type is incompatible with spread operand
```

![screen shot 2016-11-12 at 7 01 56 pm](https://cloud.githubusercontent.com/assets/981638/20243419/4051153a-a90b-11e6-8e2a-6a8ac38b4812.png)

```
$ > flow version
Flow, a static type checker for JavaScript, version 0.33.0
$ > 
```

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/1667
