### ISSUE TITLE
Flow should not merge union of generic types into one generic of union type

### ISSUE THREAD

**Issue by HerringtonDarkholme** [facebook/flow#2799]
I found this in the slide here. https://speakerdeck.com/gfx/how-do-we-get-along-with-static-types?slide=21

flow version: 0.35

```ts
/*@flow*/
class A<T> {
 constructor(t: T) {}
  method(t: T): T {
    return t
  }
}

var a = Math.random() > 0.5
  ? new A(1)
  : new A('1')

a.method(1)
var b: A<string> | A<number> = a
```

Expected behavior:
flow should report error on the last line. Because `A<string> | A<number>` 's `method` should have the signature of `(t: string & number) => string | number`, according to variance rule.

Actual behavior:
No errors! flow infers a as `A<string | number>`

**Comment by vkurchatkin** [comment]
Sometimes there more than one correct way to infer types. In this case both `A<string | number>` and `A<string> | A<number>` seem to be correct.

**Comment by HerringtonDarkholme** [comment]
No, A<string|number>'s method expands to `(t: string | number) => string | number`, which means it can accept string or number value.
But in runtime, method can only accept a value that is string and number at the same time.

**Comment by vkurchatkin** [comment]
> But in runtime, method can only accept a value that is string and number at the same time.

Well, not in your example. Can you come up with example that leads to a runtime error?

**Comment by HerringtonDarkholme** [comment]
Forget it. Flow's inference is too magic.

```ts
class A<T> {
  constructor(t: T) {}
  method(t: T) {
  }
}
// this line makes correct rejection
// var a1: A<number> = new A(1)
var a1 = new A(1) // this line does not

var a = Math.random() > 0.5
  ? a1
  : new A('1')

a.method('1')

```
