### ISSUE TITLE
Allow to work with requirejs module format

### ISSUE THREAD

**Issue by totty90** [facebook/flow#28]

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by mroch** [comment]
we support commonjs and ES6 these days, and should detect file changes properly. i think this is fixed, but let me know if there's still something missing here.

**Comment by cjdelisle** [comment]
It is possible to write flowed code using require.js, you need to fool flow into thinking the code is commonjs, but this is possible in principle using the comment syntax. For example:

```javascript
/*@flow*/
/*::const define = () => {};*/
define([
    '/common/common.js',
    '/bower_components/jquery/dist/jquery.min.js'
], /*::0);module.exports = (*/ function (Common) {
    /*::Common = require('./common/common.js');*/

    Common.doStuff();
    ///...code goes here

})/*::()*/;
```

It's a bit annoying that we are forced to use require syntax twice but this is the price to pay for flow and requirejs I guess.

**Comment by Kiechlus** [comment]
@cjdelisle Any idea how to deal with that problem: 

![image](https://user-images.githubusercontent.com/9875731/27141066-7895a9a0-5127-11e7-93aa-65f2388d1fca.png)

**Comment by cjdelisle** [comment]
Oh I changed to a different method recently.

```javascript
/*@flow*/
/*::
const define = () => {};
export type MyType_t = {
    id: number,
    ...
};
*/
define([
    '/common/common.js',
    'jquery',
    '/common/hyperscript.js',
    '/common/Html.js',
    '/common/Ver.js'
], function (Common, $, h, Html, Ver) { /*::});module.exports = (function() {
    const Common = require('./common/common.js');
    const h = require('./common/hyperscript.js');
    const $ = (undefined:any);
    const Html = require('./common/Html.js');
    const Ver = require('./common/Ver.js');
    */

    var Messages = Common.Messages;


    ... code goes here ....

})/*::()*/;
```

This method seems to work well.
