### ISSUE TITLE
Recursive disjoint union type + Array.reduce produces multiple errors

### ISSUE THREAD

**Issue by hon2a** [facebook/flow#2803]
For the following code

```javascript
type Tree = Array<any | Tree>;

function reduceTree<T>(
  tree: Tree,
  reduceLeaf: (acc: T, item: any, path: Array<any>) => T,
  initialValue: T,
  path: Array<any> = []
): T {
  return tree.reduce(
    (acc, treeOrLeaf, idx) => Array.isArray(treeOrLeaf)
      ? reduceTree(treeOrLeaf, reduceLeaf, acc, [ ...path, idx ])
      : reduceLeaf(acc, treeOrLeaf, [ ...path, idx ]),
    initialValue
  );
}
```

Flow produces the following errors

```
9:   return tree.reduce(            ^ array type. This type is incompatible with the expected return type of
3: function reduceTree<T>(   ^ some incompatible instantiation of `T`
11:       ? reduceTree(treeOrLeaf, reduceLeaf, acc, [ ...path, idx ])
                                               ^ array type. This type is incompatible with
3: function reduceTree<T>(   ^ some incompatible instantiation of `T`
12:       : reduceLeaf(acc, treeOrLeaf, [ ...path, idx ]),
                       ^ array type. This type is incompatible with
3: function reduceTree<T>(   ^ some incompatible instantiation of `T`
```

(see it on [Flow REPL](https://flowtype.org/try/#0C4TwDgpgBAKgThaBeKBBOcCGIA8mB2IUAPrAhAHwDcAUDQGYCu+AxsAJYD2+UCAJoxYR4iHDAoAKGlCjByALjKIANNN4QBQgDIRM9RRMwsWimMqjtgEALaKCIc2EzAAFovRZc9igEooSClhVGXZ8S3ZMABsANSjGCFNgqCdXdwxsPEJAlABtAF0aH1MoAG81BGBGOB45RAA6fkEIKRkZQ2NzWogAeTgdPXN2PgAPPwC0dJA69gBnD2wJLt7++h81VqgAfnVNYXJF8mXdenNG7WPzIxZzHKg6+5SXQZGoPLWNmUUziBX269lDn0LlBbvc6o9nsNXj4kiEwhworFIvE1D5aABfIA)). The errors go away if I define `Tree` simply as `Array<any>`. I'm not sure what the errors mean and after staring at the code for some time now, I can't see any problem with it. So I'm guessing it's a bug. And if not, I'm hoping someone here can explain to me why :)

**Comment by gcanti** [comment]
Try to add an annotation to `acc: T`

[repl](https://flowtype.org/try/#0C4TwDgpgBAKgThaBeKBBOcCGIA8mB2IUAPrAhAHwDcAUDQGYCu+AxsAJYD2+UCAJoxYR4iHDAoAKGlCjByALjKIANNN4QBQgDIRM9RRMwsWimMqjtgEALaKCIc2EzAAFovRZc9igEooSClhVGXZ8S3ZMABsANSjGCFNgqCdXdwxsPEJAlABtAF0aH1MoAG81BGBGOB45RAA6fkEIKRkZQ2NE2XIAeTgdPXN2PgAPPwC0dJA69gBnD2wJWohe-vofNVaoAH51TWFyRZ6+3XpzRu0T8yMWcxyoOoeUl0GRqDz1zZlFc4hV9puuogVpcoHcHnUni9hm8fEkQmEOFFYpF4mofLQAL5AA)

**Comment by hon2a** [comment]
That does get rid of the errors, thanks. I'd still expect Flow to correctly infer that, but I'm new to Flow, so...

**Comment by gcanti** [comment]
> I'd still expect Flow to correctly infer that

Me too. Adding a return annotation also works

```js
(acc, treeOrLeaf, idx): T => ...
```

**Comment by SamChou19815** [comment]
We no longer produces errors for this example.
