### ISSUE TITLE
Provide a way to indicate that you expect an interface to match a given class

### ISSUE THREAD

**Issue by ForbesLindesay** [facebook/flow#2811]
I'm writing an interface for a `ReadOnlyArray<T>`.  I expect this interface to be a subset of `Array<T>`.  Unfortunately, when I get this wrong, flow complains about each individual usage of the interface by telling me that it expected something that matches `ReadOnlyArray<T>` but got `Array<T>`.  What I would like is a way to say something like:

```js
interface ReadOnlyArray<T> {
  ImplementedBy {Array<T>}
  // ... methods and properties go here ...
}
```

Then flow could complain on that line, and that line only.  This would also give me a sensible place to add a `$FlowFixMe` to work around issues like #2782

**Comment by gajus** [comment]
There is [`$ReadOnyArray<T>`](https://github.com/facebook/flow/search?utf8=%E2%9C%93&q=%24ReadOnlyArray&type=)

**Comment by ForbesLindesay** [comment]
I think the `implements` syntax wasn't documented when I posted this.  It's not quite what I was after, but since `$ReadOnlyArray` exists as well, I no longer need this.
