### ISSUE TITLE
`Array<Array<string>>` and `mixed[]` are incompatible

### ISSUE THREAD

**Issue by keithamus** [facebook/flow#2813]
I'm writing a function that accepts a 2d array of strings, and inside of that function, it calls a function to check the length - which accepts a mixed array (I've notated the type as `mixed[]` for this).

Reduced code:

```js
function thing(foo: Array<Array<string>>) {
 other(foo); 
}

function other(foo: mixed[]) {
  return foo;
}

thing([ [ 'hello' ] ]);
```

Errors:

```
5: function other(foo: mixed[]) {
                       ^ mixed. This type is incompatible with
1: function thing(foo: Array<Array<string>>) {
                             ^ array type
```

If I change the `Array<Array<string>>` to `[ string ][]` this works fine, however.

It seems that both `[ string ][]` and `Array<Array<string>>` are effectively equivalent. Why does one resolve and the other not? More to the point, why is `Array<Array<string>>` incompatible with `mixed[]`? `mixed` is a supertype of Array, right?

**Comment by vkurchatkin** [comment]
`Array` type is invariant, so `Array<Array<string>>` is not subtype of `Array<mixed>`. See: https://github.com/facebook/flow/issues/2333
