### ISSUE TITLE
"This type cannot be coerced to string" in template literals

### ISSUE THREAD

**Issue by disjukr** [facebook/flow#2814]
but it has `toString` method

```
$ cat test.js
// @flow
console.log(`${ {toString() { return 'string'  }} }`);

$ flow check
test.js:2
  2: console.log(`${ {toString() { return 'string'  }} }`);
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type cannot be coerced to
  2: console.log(`${ {toString() { return 'string'  }} }`);
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string


Found 1 error
```

**Comment by mroch** [comment]
technically everything has a `toString` method :) i agree that in cases where there's an overridden `toString` it might make sense to allow this. generally, falling back on `Object.prototype.toString` and getting `[object Object]` is not what you expect.

Flow forbids implicit type coercion, except in a few cases where the syntax exists solely for that purpose like `String(foo)` or `+bar`.

the workaround here is to convert to a string via `String(obj)` or by calling `.toString()`. you could also define a tag function like

```
function debug(quasis: Array<string>, args: Array<any>) {
  let parts = [quasis[0]];
  for (let i = 1; i < quasis.length; i++) {
    parts.push(String(args[i - 1]), quasis[i]);
  }
  console.log(parts.join(""));
}

debug `${foo}`;
```

**Comment by barbalex** [comment]
but according to this: https://ponyfoo.com/articles/template-literals-strictly-better-strings template literals should generally be used instead of strings

which gives me lots of noise in flow because of this issue

am I getting something wrong or might this issue be worth reconsidering?

**Comment by pugnascotia** [comment]
I would argue that in the case of template literals, you really do want .toString() to be called on the object irrespective of its implementation. This wouldn't hold for tagged template literals, however.

**Comment by matrunchyk** [comment]
Yeah, faced the same. 

> 51:         axios.delete(`/api/timeline-posts/${postId}`)
>                                                  ^^^^^^ Number. This type cannot be coerced to
>  51:         axios.delete(`/api/timeline-posts/${postId}`)
>                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string

This is templates designed for, isn't it? Shouldn't `flow` bypass this case (ok, at least warning, not error)?

**Comment by vkurchatkin** [comment]
@matrunchyk there is no good reason to use `Number`, so Flow is actually helpful here

**Comment by matrunchyk** [comment]
@vkurchatkin Why? In that case how to substitute numeric values in strings (e.g. for my particular case)? I don't think concatenation with `+` is a better choice.

**Comment by vkurchatkin** [comment]
Flow allows `number` (primitive, not object wrapper)

**Comment by pugnascotia** [comment]
The precise type isn't the point though - in a context where the code is intentionally performing string concatenation, it seems reasonable to allow `.toString()` to be called implicitly rather than explicitly.

**Comment by vkurchatkin** [comment]
In javascript everything can be coerced to a string or a number (except for symbols). One of the goals of Flow is to limit this behavior.

**Comment by matrunchyk** [comment]
@vkurchatkin How would you write that string in the example to pass Flow and ESlint?

**Comment by vkurchatkin** [comment]
@matrunchyk I wouldn't use `Number` in the first place. Otherwise, calling `toString` is an option

**Comment by StreetStrider** [comment]
@vkurchatkin 
> Flow is to limit this behavior.

In the mean time [the doc](https://flowtype.org/docs/builtins.html#string) says:

> Generally, implicit type casting is an error with Flow. However, it is a fairly common JavaScript idiom to produce a string by combining a string and a number with the binary operator +, so Flow accepts it.

So it's not allowed to coerce in template strings (which is generally designed to concatenate heterohenous content in one string in nice manner), but it's allowed to concatenate string and number without explicit coercion (which is one of the most error-prone places). This two statements sounds nonsence in sum.

**Comment by vkurchatkin** [comment]
> So it's not allowed to coerce in template strings

It is allowed

**Comment by theY4Kman** [comment]
I don't think I'm understanding this correctly. Lemme try to get this straight...

```javascript
// (GOOD) implicit concatenation between string and number primitive
console.log(`This is the number twelve: ${12}`);

// (GOOD) concatenation of string and Number wrapper explicitly case to string
console.log(`This is the number twelve: ${new Number(12).toString()}`);

// (BAD) implicit concatenation of string and Number wrapper
console.log(`This is the number twelve: ${new Number(12)}`);
```

These three examples all **print the same thing**, but the last one draws an error from flow.

To understand why this is so, I've read and reread the explanations in this thread with a fine-toothed comb, and I've learned the reason why implicit concatenation of strings and Number wrappers is disallowed is because it's *Very Bad™* and on the flow *Disapproval List®*.

Sarcasm aside, there's a reason why implicit string concatenation with Number wrappers is disallowed. Why is this? If the reason is because "an aim of flow is to limit this usage", why is this usage discouraged? What are the potential errors we are trying to avoid?

**Comment by pugnascotia** [comment]
Irrespective of whether Flow's behaviour is changed, a better message to the developer would be appreciated. React is good in this regard, giving you pointers on why there was a warning or error.

**Comment by thiagodebastos** [comment]
Hey guys, why was this issue closed? It doesn't feel like it was resolved in any clear way. I have come across the same issue just now: passing in simple props to a React component like this:

```js
src={`/public/img/posters/${props.poster}`}
```

Like @theY4Kman (https://github.com/facebook/flow/issues/2814#issuecomment-288208880), I too would like to understand why flow would be discouraging this?

**Comment by Pragmateek** [comment]
For numbers I've "fixed" it by prefixing with `+`:

    `...${n}...` // KO
    `...${+n}...` // OK

**Comment by vkurchatkin** [comment]
You don't need workarounds for number, they just work

**Comment by Pragmateek** [comment]
Well indeed my use-case was more involved but I have simplified my sample too much 😄 :

    `...${myMapOfNumbers.get(someKey)}...` // KO
    `...${+myMapOfNumbers.get(someKey)}...` // OK

The map was typed as `Map<string, number>`.

**Comment by jedwards1211** [comment]
@mroch okay so is there a way to explicitly allow this for certain types which we intend to use with `toString`? It's too convenient in some cases.

**Comment by josephrexme** [comment]
@vkurchatkin I'm having this same issue in this situation:
```js
return axios.get(`${process.env.HOST}/questions`);
```
and unlike most of what's been discussed above, this is getting what I believe should be a string from the environment variable. Adding `.toString()` didn't fix it for me either.

Here's the precise error I get
```
Cannot call process.env.HOST because property toString is missing in null or undefined
```
and my HOST env var is not missing, it works when I disable flow

**Comment by pugnascotia** [comment]
In this case Flow can't guarantee that `HOST` will be defined in the environment at runtime, so the type is actually (I assume) `?string`.

**Comment by josephrexme** [comment]
I'm surprised why Flow even cares since I'm not returning the string. I'm returning the promise and I have this:
```js
myFunc(): Promise{
  return axis.get(`${process.env.HOST}/questions`);
}
```

**Comment by vith** [comment]
You should be getting a separate error for using `Promise` without a type argument like `Promise<string>`. But your original error is not about the type of the function's return value anyway, it's about potentially interpolating undefined or null into the string template.

**Comment by josephrexme** [comment]
Is there something else I can do instead? Also about that Promise type argument, I should be able to pass `Promise<object>` then

**Comment by vith** [comment]
You have to do something to prove `process.env.HOST` is an appropriate type for string interpolation. 
One example would be:

```js
/* @flow */

const HOST: ?string = Math.random() > 0.5 ? 'foo' : undefined;

type SomeResult = {
  path: string
}

function foo(): Promise<SomeResult> {
  if (typeof HOST !== 'string') {
    throw new TypeError('HOST is undefined'); // try commenting this line out
  }
  return Promise.resolve({
  	path: `${HOST}/questions`
  });
}

```

([flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAAkB5AZQBUAuMAfgICcBLbAczAF4wBZAQ3wAWAOga9sAEzgBbABQBKMAD4wABiEBWOmADkUOHG1gaAVwkBTKCzPiA3OnwBPAA5mwZaWYBKZ3MZiEuAG9UMDAnfgEaRhZWVABfdChTDHwmHDA9OHkaAAUGaSZcMwAedykvHz98ZWDQpigwGUcXOAbSSjAAQg4ubWi2bQVa0LBBfKRsMyQKZzMAUQZ8hhltdoowQrBTcQsrcUGbMGBgUYYHMCwpcuxUtlGBTZgrMDhjfBCwBNCGM3xjBmwYDyBSKIh8cBgADczDJhgBIcKCGgAAwAJIE1nFgABHYw+VI4XDIj5xOR2BJAA) of the above)

**Comment by josephrexme** [comment]
I really don't get that. But I think the error suggests I do something like this which I don't get either:
```js
env : { [key: string] : ?string };
```
Current code:
```js
// @flow
import axios from 'axios';

const Request: Object = {
  getFeed() {
    return axios.get(`${process.env.HOST}/questions`);
  },
  authenticate(email: string, password: string) {
    return axios.post(`${process.env.HOST}/auth/sign_in`, { email, password });
  }
};

export default Request;
```

**Comment by vith** [comment]
I get no errors with this:

```js
// @flow
import axios from 'axios';

const Request: Object = {
  getFeed() {
    if (typeof process.env.HOST !== 'string') {
        throw new TypeError();
    }
    return axios.get(`${process.env.HOST}/questions`);
  },
  authenticate(email: string, password: string) {
    if (typeof process.env.HOST !== 'string') {
        throw new TypeError();
    }
    return axios.post(`${process.env.HOST}/auth/sign_in`, { email, password });
  }
};

export default Request;
```

**Comment by josephrexme** [comment]
Thanks @vith . That worked

**Comment by jjshammas** [comment]
I have an instance of wanting to coerce classes to strings in `styled-components` templates, for example:

```
class A {
  copy(): A { return new A() }
  toString(): string { return "Foo" }
}

var instance = new A();

`${instance}`

`${instance.copy()}`
```

Is this just a bad idea in a type-safe world? Or should there be a way to allow Flow to coerce this class?

**Comment by jack-guy** [comment]
For the sake of completeness, [TypeScript supports this](https://www.typescriptlang.org/play/#src=class%20Foo%20%7B%0D%0A%20%20%20%20toString()%20%7B%0D%0A%20%20%20%20%20%20%20%20return%20%22Bar%22%3B%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0Aconst%20baz%20%3D%20%60qux%20%24%7Bnew%20Foo()%7D%60%3B%0D%0A).

**Comment by benadamstyles** [comment]
@jjshammas A quick fix I always use is: ``${String(instance)}`` – you can see it working [here](https://flow.org/try/#0MYGwhgzhAECC0G8BQ1rAPYAcCeAKAlAFxyLQBOApgC4CuZAdtPRQO5wHQC+K0V6AylTIBLegHMCxCENFjSlWg2gAiAGLp0yrkm5IAbmDLRR0sPWAVoAXiat2+ANxIkGehHQgKAOhDoJAAwASBEERcVwTKjMLfE5-fGdXd08fP1wgkJlwyOjvDBwCWPigA). It may seem like unnecessary boilerplate but actually I've found I quite like the explicitness, it reminds me that `instance` is not a string and I'm doing some typecasting there.

**Comment by jedwards1211** [comment]
@josephrexme your code with `process.env.HOST` is really a separate issue, this is about allowing guaranteed-to-be-defined objects to be coerced to string inside a template literal.

**Comment by nickensoul** [comment]
Okay, this issue is closed, but why? Does any of linked PR fixes this?
Completely agree with @oshalygin and other participants in this tread.
In case of using custom getters like lodash's `get` method, this behaviour makes sense and brings inconvenient, in code style and readability in general.
```const item = _.get(object, `items.${itemId}`, null);``` is pretty understandable, for example and cannot throw exception, especially of checking `item` later.

**Comment by soulofmischief** [comment]
I don't think this issue should be closed. I am still experiencing it when trying to use a value from Object.entries in a template literal, which is a very typical scenario. Flow makes my code so needlessly convoluted sometimes.

**Comment by simkessy** [comment]
How is this code helping write better code?

**Comment by AVykhrystyuk** [comment]
It seems to not work with generics as well 
```ts
type Node<T> = {
  data: T;
}

function print<T>(node: Node<T>): string {
  return `text_${node.data}_text`;
  //             ^ Cannot coerce `node.data` to string because `T` [1] should not be coerced. [incompatible-type]
}

```

**Comment by swedishtechnologies** [comment]
Yes please reopen!
