### ISSUE TITLE
type-at-pos of utility types ($Keys, e.t.c) always is (unknown)

### ISSUE THREAD

**Issue by darky** [facebook/flow#2815]
```javascript
// @flow
const obj /* : $Shape<{a: number, b: number}> */ = {a: 1};
```

`flow type-at-pos example.js 2 7`

```
(unknown)
```
Hard to debug types, when using utility types

**Comment by asolove** [comment]
Small update: as of Flow v0.53.1, this now gives the output "object type", which is slightly better and consistent with what type errors related to this show.

**Comment by SamChou19815** [comment]
This issue has been fixed a while ago.
