### ISSUE TITLE
Spread doesn't replace the type of a property that is provided later

### ISSUE THREAD

**Issue by jamiebuilds** [facebook/flow#2816]
The following code:

```js
declare var beep: {foo: ?string};
const boop: {foo: string} = {...beep, foo: 'something'};
```

Produces this error:

```
3: declare var beep: {foo: ?string};
                            ^ null. This type is incompatible with
4: const boop: {foo: string} = {...beep, foo: 'something'};
```

But Flow should be able to know that `foo: 'something'` will always replace the `?string` type.

**Comment by torifat** [comment]
We are facing something similar in our codebase.

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAKuATgM5wB2YAvGAN6phgUCGAtrgFz2NNhQBLMum6l0xARQDmAGl5MYLMaPGSpvAL5ymLKV2YBXNgCMSvYMDAB5dAAsSYbMTh5i6AblKoNAblQYcfCsYABMiMkoaHiZWDhUJaW0wXX0KI1Nic0sbe2JHZ1d3T28-VCgDCgBjd0i2FgBrXHDyCgAKF25gsJIWgEpuZsiGBVx0MDHaOjAAOlmXMF9edGnY-EnFpmXV6cFhKJcV9lw-TcOOacUxKIByeoMwO+uTsGJRg2IqdD8Nf0rKK-mk14q241w49hCAmuSRS3AAjAAmEr+OqNQZtFy9HxAA

**Comment by dsilvasc** [comment]
Here's a workaround: cast the object being spread to a type that's common between the two types.

```
type Common = {
  foo: number,
}

type A = Common & {
  bar: number,
}

type B = Common & {
  bar: string,
}

function spread(a: A): B {
  return {
    ...(a: Common),
    bar: 'test'
  }
}
```

**Comment by apsavin** [comment]
In react this leads to error:
```jsx
<Component {...props} booleanProp />
```
This works:
```jsx
<Component {...props} booleanProp={true} />
```

**Comment by villesau** [comment]
Made a fix for spreading issues: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
