### ISSUE TITLE
typeof `[]` should be `Array<any>`

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2818]
Here is the [code to reproduce](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFMBbAB3wE8wBeMAbQF10MYBDXXMAURlKOyEAPGwB8YAN6owYbGxJEAXGAIAnAJbYA5tLAYAFupgATVQOUBBVaraUhvfoJGjRurHnyqArhnxxVABRyCopqmloANHqGJmbYilY2dg4KTmKiAJSSujL4hrgAdMFEtLLyRLoAkHnqhQZGpgKl9bECugC+qJ2YOAR6Zmz4RCkChHTOYEHloZ7hUSS2AEZEAMIxjfEA-Im29nyp+M6ZiiNp4jTiUjLufS0bpQuUy2sNcbR02F4wMFWbxORUHJgZSPZ7rOK6XRmfBeVTYWREJCnfBTBRRO5xDJdVBAA):

```js
/* @flow */

const empty = []

class Element <a> {
  name: string
  children: Array<Element<a>>
  constructor(name:string, children:Array<Element<a>>) {
    this.name = name
  	this.children = children
  }
}

const createElement = <a> (name:string, maybeChildren:?Array<Element<a>>):Element<a> => {
  const children = maybeChildren == null
  	? empty
    : maybeChildren
  
  return new Element(name, children)
}
```

That produces following errors:

```
const createElement = <a> (name:string, maybeChildren:?Array<Element<a>>):Element<a> => {
                           ^ a. This type is incompatible with
14: const createElement = <a> (name:string, maybeChildren:?Array<Element<a>>):Element<a> => {                          ^ some incompatible instantiation of `a`
```

I would expect flow to treat `empty` there as `Array<any>` because well empty array is compatible with any array type.

**Comment by HerringtonDarkholme** [comment]
I think this is a correct behavior.

Think about this:
```ts
/* @flow */

const empty = []

class Element <a> {
  children: Array<a>
  constructor(val: a, children:Array<a>) {
  	this.children = children
    this.children.push(val)
  }
}

const createElement = <a> (val: a, maybeChildren:?Array<a>) => {
  const children: Array<a> = maybeChildren || empty
  return new Element(val, children)
}

createElement(123)
createElement('123')

```

**Comment by vkurchatkin** [comment]
@HerringtonDarkholme is right. That would work for read-only arrays

**Comment by Gozala** [comment]
In fact my original code had:

```js
const empty = Object.freeze([])
```

I just oversimplified it I guess (always forget mutability concerns)

**Comment by Gozala** [comment]
Also even with mutability maybe it would make more sense to error if & when empty is mutated in an incompatible way rather then just erroring right away

**Comment by HerringtonDarkholme** [comment]
It can be boiled down to even simpler code.
 
```ts
/*@flow*/

const empty = []

function generic<A>() {
    let arr: Array<A> = empty
}
```

**Comment by cglacet** [comment]
Still no fix for that in recent versions?

**Comment by SamChou19815** [comment]
Under `inference_mode=lti`, this should now works as expected.
