### ISSUE TITLE
flow errors when using `this` in class method argument defaults

### ISSUE THREAD

**Issue by nrser** [facebook/flow#2820]
this sort of thing works in babel-land:

```js
class A {
  x: string;
  
  constructor(x: string) {
    this.x = x;
  }
  
  f(x = this.x) {
    // ...
  }
}
```

but flow (using `v0.35.0`) doesn't like it (seems to see `this` as the global object). maybe this is an anti-pattern of sorts, but it's quite convenient; would be nice if it type-checked.

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/1234

**Comment by nrser** [comment]
thanks. did some searches but didn't see that one.
