### ISSUE TITLE
Flow does not detect type error in argument list at function call

### ISSUE THREAD

**Issue by akatav** [facebook/flow#2821]
Here is the code sample: 

// @flow 
someLib.module("xyz", function(exports) {
exports.app = new someLib.ClassDefinition(function() {

return {
'$extends': demo.Application,
total: function(a:number, b:number) {
return a+b*3;
}
'someFunc': function() {
this.total(3,"Hi");
}
};
});
});
var obj=someLib.module("xyz").app;
obj.prototype.total("Hello", 12);

When running this code with flow, the type error in the function call (when we pass a string to the function: total instead of a number) is not detected at all. Whereas if there is a problem inside the function itself (with the return type ie.,), Flow throws an error. However, if i look at the logs, i see an error like below:

Error: Sys_error("Invalid argument")
Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
Called from file "src\server\serverProt.ml", line 102, characters 10-23
Called from file "src\server\server.ml", line 639, characters 14-51
Called from file "src\server\serverFunctors.ml", line 134, characters 6-43

I suppose this error happens because oCaml is trying to convert the string to a number. But my question is how to make Flow detect the error at the line where the erroneous function is being called and display it  ?

**Comment by WhyEvenTry** [comment]
Related, FYI: [Jetbrains Webstorm -- [Flow] WS gets error from flow.exe](https://youtrack.jetbrains.com/issue/WEB-24993)

**Comment by tselishev-semen** [comment]
I have another example of this error:
 ```js
declare var plugin: {
    set_log_level: Function
};
type logLevel = 1 | 2 | 3|  4

export function setLogLevel(level: logLevel): void {
    plugin.set_log_level(level);
}
```
but, i solved it like that:
 ```js
type logLevel = 1 | 2 | 3|  4

declare var plugin: {
   set_log_level: (level: logLevel) => void
};

export function setLogLevel(level: logLevel): void {
    plugin.set_log_level(level);
}
```

**Comment by TrySound** [comment]
Do not get any errors.
