### ISSUE TITLE
Type cannot be coerced to string

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#2827]
```js
shellExec(args: string[]): Promise<void> {
    const executable = this.gitBinary;

    return new Promise((resolve, reject) => {
      console.log(`Run ${executable} with args ${args}`);

...
```

I swear, it works and `args` is being expanded to string.

But I still receive:

>  [flow] [flow] array type (This type cannot be coerced to string)

**Comment by vkurchatkin** [comment]
Yes, implicit conversion if forbidden. See: https://github.com/facebook/flow/issues/2814

**Comment by pronebird** [comment]
Makes sense! Thanks!
