### ISSUE TITLE
Generics with class instance fields and inheritance possibly broken?

### ISSUE THREAD

**Issue by LegNeato** [facebook/flow#2829]
Not sure if this is a bug or I just don't understand how to use generics. Here is a distilled down repro:

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAodBjGBDAzrsAWQE8BhOOGUnfAHgBUA+MAb1TDCgrAF4wAKAEbYATgC4w9AJS9mbDguDAwAEzhgALgAtsGzVoCWAOwDmAOnZgAvqhuoseAgHUdGgKYA3NyLBuAHu5GKgQk5JTUjrS4GiLGJnJWANyYcEbRYH68YEZuSC66nt78UsmoSmAAInBuuEYA5HoIcCIA1mbtqH5mXHD8dfQAogDK9HUlQA

```js
class MyCoolClass<T> {
  foo = (bar: T) => {
     // do that thing.
  }
}
class Whatever extends MyCoolClass<string> {};

const x = new Whatever();

// Doesn't work...
x.foo('TEST');
```
For my real use-case, I essentially have a set of classes that have the same business logic but only differ in input and output types.  So I made a base class and used generics, yet the "generic" portion doesn't seem to be working as in the above example.

**Comment by LegNeato** [comment]
Interestingly, getting rid of the variable binding  and just using a function directly seems to work:

```js
class MyCoolClass<T> {
  foo(bar: T) {
     // do that thing.
  }
}
```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAodBjGBDAzrsAWQE8BhOOGUnfAHgBUA+MAb1TDCgoAoAjbAE4AuMPQCUrdhw7BgYACZwwAFwAW2ZStUBLAHYBzAHRSAvqjOoseAgHV1ygKYA3BwLAOAHo93yCJcpTU1rS4ygJ6+swsJgDcmHC6oWAeYAC8YLoOSHYazq7cYnGosmAAInAOuLoA5JoIcAIA1oYtqB6GXHDc1fQAogDK9NWFQA

Which makes me think this is a bug 🐞

**Comment by gcanti** [comment]
```js
class MyCoolClass<T> {
  foo: (t: T) => void = (bar) => {
     // do that thing.
  }
}
```

**Comment by LegNeato** [comment]
Ah, thanks! So it appears this is working as intended and I just didn't understand how to use generics + class instance fields, correct? If so I will close.
