### ISSUE TITLE
False Negatives Reported after RegExp

### ISSUE THREAD

**Issue by barakyo** [facebook/flow#2831]
Flow seems to be throwing the error "Property cannot be accessed on possibly undefined value" when accessing a property on an object that has already been checked for undefined. If you look at the code below, if I move the `const key` declaration above before the RegExp, flow will not complain.

In Editor: https://flowtype.org/try/#0C4TwDgpgBAMg9gYwIYBsDCALCCDWAFJAJyQFsJgJCoBeKAbwCgooA7UiALigGdhCBLFgHMANEygVeXAEoQhAUQAeYMc37cAgoWIgA-FwBGcOCghIWDAL4MGoSLESpM2HDXrikCYPzgsuvAWFVCQgpKFkFZWCwInYKQn0HZHQsXAJiMnirGwAzAFcWLx8WKBzjAAoASi54ZOdceihxQnI8whLGZmZPb18uAHIyuH7g5klgLgB6IcnRqBiM8kouTq7mNjIBgyIR8TXxqe3CWb2u9S0dLj48iFPrZmtrBF9eKBRHFJc3IaqAbgZ+DkoOV3nVUjgAHQLOKUSruZjPFivCiKYA0ABEQ3R-wRLzRADdUDc3KCnOCobFMpQIeMIRBFNhyijgJUANoARgAujioIjXjgICASR96pDoVTCBCNhB-pYgA

Code:
```
type LocalCheckParameter = {
  name: string,
  test: RegExp,
  isArray?: boolean
}

type LocalCheck = {
  action: string,
  test: RegExp,
  parameter?: LocalCheckParameter
}

function foo(): LocalCheck { 
  return {
    action: 'foo',
    test: /foo/,
    parameter: {
      name: 'bar',
      test: /bar/,
      isArray: true
    }
  }
}
const localCheck = foo();
if (localCheck.parameter) {
  const text ="foo";
  const value = localCheck.parameter.test.exec(text)[1];
  const key = localCheck.parameter.name;
}
```

Error:
```
28:   const key = localCheck.parameter.name;
                                       ^ property `name`. Property cannot be accessed on possibly undefined value
28:   const key = localCheck.parameter.name;
                  ^ undefined
```

**Comment by vkurchatkin** [comment]
Flow invalidates type refinements after function calls, so it is expected bahaviour
