### ISSUE TITLE
`required module not found` for Node's 'v8'

### ISSUE THREAD

**Issue by anmonteiro** [facebook/flow#2832]
```js
  9: const v8 = require('v8');
                ^^^^^^^^^^^^^ v8. Required module not found
```

It's definitely there: https://nodejs.org/api/v8.html

**Comment by thejameskyle** [comment]
Never knew about that one. If you want to add it, you can do so here: https://github.com/facebook/flow/blob/master/lib/node.js

**Comment by R1ZZU** [comment]
Does it look good enough R1ZZU/flow@9abc37d4b7dda02f78d58d52dbd2750cb59b2473? 😏
