### ISSUE TITLE
Union type cast failure in promise .then()

### ISSUE THREAD

**Issue by gcedo** [facebook/flow#2836]
Given Login type
```
declare type Login = { authorised: true, token: string } | { authorised: false };
```

Flow doesn't complain about this (where `login` is of type `Login`)
```
if (!login.authorised) {
   response.sendStatus(403);
}
return Promise.resolve(login.token)
```

But complains about this:
```
if (!login.authorised) {
   response.sendStatus(403);      
}
return Promise.resolve(login.token)
      .then(value => callback(value, login.token));
```

Here's the error trace, which refers to the `.then` line :
```
property `token`: [...]
Property not found in
object type: [...]
```

**Comment by vkurchatkin** [comment]
The problem is that callback is called later asynchronously, and Flow has no way of knowing that `authorised` will still be true. Instead you should do something like this:

```js
if (!login.authorised) {
   response.sendStatus(403);      
}
const token = login.token;
return Promise.resolve(login.token)
      .then(value => callback(value, token));
```

**Comment by gcedo** [comment]
@vkurchatkin thank you very much for the explanation, that is what I ended up doing
