### ISSUE TITLE
Inferred variable types should include types of re-assignments inside classes

### ISSUE THREAD

**Issue by jamiebuilds** [facebook/flow#2841]
When you declare a variable and mutate it within a function that gets called before reusing that type. The type becomes a union type of the inferred assigned types.

```js
let foo = 1;

function mutate() {
  foo = "hello";
  foo = true;
}
  
mutate();

let bar: number = foo; // Error!
let baz: number | string | boolean = foo; // Works.
```

However, referencing `foo` inside a class method that gets called does not cause the same behavior.

```js
let foo = 1;

class Mutate {
  constructor() {
    foo = "hello";
    foo = true;
  }
}
  
new Mutate();

let bar: number = foo; // Works.
```

**Comment by asolove** [comment]
Just confirming this still happens in v0.53.1

**Comment by SamChou19815** [comment]
If the variable is initialized at the declaration site, we will now consistently use it as the type of the variable without considering others.
