### ISSUE TITLE
Filtering null values from an array of maybe types fails to produce an array of non-optional values

### ISSUE THREAD

**Issue by Firehed** [facebook/flow#2846]
Per the title: if you have an array of maybe types, and filter out null values from that array (e.g. `.map(val => val != null)`, flow fails to detect the "unwrapping" of these values and keeps treating the array as one of maybes. As a result, totally valid and safe future operations emit errors during typechecking.

```js
// @flow

// Problem concept
let maybes: Array<?number> = [1,2,3];
let actuals = maybes
  .filter(val => val != null) // Should now be Array<number>, but stays as Array<?number>
  .filter(val => val > 0);

// Discovered this way
type Story = {id: number};
let story_ids = [1, 2, 3];
let stories: Array<Story> = [{id: 2}, {id: 3}];
let example = story_ids 
  .map(id => stories.find(story => story.id === id))
  .filter(story => story != null)
  .filter(story => story.id > 2)

// Works
let works = story_ids
  .map(id => stories.find(story => story.id === id))
  .filter(story => story != null && story.id > 2)
  // all future operations require the null check as well
```

```
src/example.js:7
  7:   .filter(val => val > 0);
                      ^^^ null. This type cannot be compared to
  7:   .filter(val => val > 0);
                            ^ number

src/example.js:7
  7:   .filter(val => val > 0);
                      ^^^ undefined. This type cannot be compared to
  7:   .filter(val => val > 0);
                            ^ number

src/example.js:16
 16:   .filter(story => story.id > 2)
                              ^^ property `id`. Property cannot be accessed on possibly undefined value
 16:   .filter(story => story.id > 2)
                        ^^^^^ undefined
```

Poking around, it looks like this [should work](https://github.com/facebook/flow/blob/master/lib/core.js#L190), but it's at best unclear how to get flow to pick up on this.

**Comment by gcanti** [comment]
```js
let maybes: Array<?number> = [1,2,3]
let actuals = maybes
  .filter(Boolean)
  .filter(val => val > 0)
```

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/1414

**Comment by eluchsinger** [comment]
@gcanti Does that work only for non falsy values?

**Comment by rszymula** [comment]
This is just a hack for the specific case that the array is full of numbers

let maybes: Array<?number> = [1,2,3]
let actuals = maybes
  .filter(Boolean)
  .filter(val => val > 0)

what if I have 
{
  person: {
    place: ?string
  }
}

and I filter out all non null places?

or what if I want to do a mapping afterwards?

let actuals = maybes
  .filter(Boolean)
  .filter(val => val > 0)
  .map(item => item + 5)

What now? How to fix flow in the general case?
