### ISSUE TITLE
Unable to Import Express Flow-Typed Definition

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2847]
**server.js**
````javascript
import WebpackDevServer from 'webpack-dev-server'

const test = new WebpackDevServer()
````

**express_v4.x.x.js**
_https://github.com/flowtype/flow-typed/blob/master/definitions/npm/express_v4.x.x/flow_v0.25.x-/express_v4.x.x.js_

**webpack-dev-server.js (Test A)**
_If I use "string" as a type, the "const test" type in sever.js picks up the type & ignores the original untyped file._
```javascript
// @flow
import type { $Application } from 'express'

declare module 'webpack-dev-server' {
  declare module.exports: string;
}
```

**webpack-dev-server.js (Test B)**
_If I use "$Application" as a type, the "const test" type in sever.js reverts back to the original untyped file. Thus is "any" type..._
```javascript
// @flow
import type { $Application } from 'express'

declare module 'webpack-dev-server' {
  declare module.exports: $Application;
}
```

Am I missing something obvious?

flow-bin v0.35.0
flow-typed master

**Comment by mwalkerwells** [comment]
@LegNeato as an FYI

**Comment by thejameskyle** [comment]
Hmm... this does appear to work for me: https://github.com/thejameskyle/__flow-typed-express-import

**Comment by mwalkerwells** [comment]
Maybe the difference is that I'm importing the $Application type within another declaration file? I'm actually importing it in a lib declaration file, but I've tried doing it in the auto-generated stub file for webpack-dev-server too.

**Comment by mwalkerwells** [comment]
Now I'm getting this...

https://github.com/mwalkerwells/__flow-typed-express-import

````javascript
index.js:3
  3: import type { $Application } from 'express';
                   ^^^^^^^^^^^^ Named import from module `express`. This module has no named export called `$Application`.
````

**Comment by thejameskyle** [comment]
Oh yeah, declarations currently don't support imports. If you need it you can put things in the global namespace like this: https://github.com/thejameskyle/__flow-typed-express-import/commit/09040d1202cb64cbd858a87ec0696361539558fa?w=1

You probably will want to update it in the flow-typed repository as well

**Comment by mwalkerwells** [comment]
Ah, gotcha. So you can't import within declaration files, but you can within flow-typed?

flow-typed express for example imports type { Server } from 'http'

Sorry, did I miss this in the documentation? :(

**Comment by LegNeato** [comment]
It seems to work for me in declaration files outside flow-typed. Perhaps just change `import type` to `import` (assuming `Application` is a class declaration, which it looks to be in the `express` flow-typed libdef):

```js
/* In my project's local interface files, not flow-typed */
import { $npm$express$Request, $npm$express$Response } from 'express';

declare module 'express-http-proxy' {
  declare class ProxyResponse extends $npm$express$Response {
    // ...
  }
  declare type $ProxyResponse = ProxyResponse;
}
```
And then:
```js
/* In application code */
import type $ProxyResponse from 'express-http-proy';
```

Similarly this appears to work in my project and is closer to what you are trying to do:

```js
import { $npm$express$Middleware } from 'express';

declare module 'morgan' {
  declare module.exports: (format?: string) => $npm$express$Middleware;
}
```

**Comment by mwalkerwells** [comment]
@LegNeato I tried your approach, but it doesn't seem to work for this use case: https://github.com/mwalkerwells/__flow-typed-express-import :/
