### ISSUE TITLE
Type: Class<...>: Unable to Dynamically Call Constructor

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2858]
````javascript
/* @flow */

class Foo {
  s: string
  constructor(s: string) { this.s = s }
}

class Bar {
  n: number
  constructor(n: number) { this.n = n }
}
        
function ForkedConstructor<InstanceA: *, InstanceB: *>(
  ClassA: Class<InstanceA>,
  ClassB: Class<InstanceB>,
  AB: 'A' | 'B',
  Constructor: (value: Class<InstanceA> | Class<InstanceB>) => InstanceA | InstanceA
): InstanceA | InstanceA {
	return AB === 'A' ? Constructor(ClassA) : Constructor(ClassB)
}

ForkedConstructor(Foo, Bar, 'A', Constructor => {
  if (Constructor === Foo) {
    return new Constructor('food')
  }
  if (Constructor === Bar) {
    return new Constructor(5)
  }
})
````

**Error**
````javascript
24:     return new Constructor('food')
                               ^ string. This type is incompatible with
10:   constructor(n: number) { this.n = n }
                     ^ number
27:     return new Constructor(5)
                               ^ number. This type is incompatible with
5:   constructor(s: string) { this.s = s }
                    ^ string
````

Code on Flow.org: https://goo.gl/HyNqgn

Is this not supported for classes? If it is, looks like a bug?

**Comment by mwalkerwells** [comment]
@samwgoldman I'm using your useful tip from https://github.com/facebook/flow/issues/706

**Comment by samwgoldman** [comment]
I haven't spent much time trying to figure out what is going on here exactly, but I think you should consider writing this code slightly differently. This kind of code seems like a great fit for [disjoint unions](https://flowtype.org/docs/disjoint-unions.html).

Can you use something like this instead?

```js
/* @flow */

class Foo {
  s: string
  constructor(s: string) { this.s = s }
}

class Bar {
  n: number
  constructor(n: number) { this.n = n }
}

type T =
  | { type: "Foo", s: string }
  | { type: "Bar", n: number }

function f(x: T): Foo | Bar {
  switch (x.type) {
    case "Foo":
      return new Foo(x.s);
    case "Bar":
      return new Bar(x.n);
    default:
      (x: empty);
      throw new Error("Unhandled case: " + x.type);
  }
}
```

**Comment by samwgoldman** [comment]
Playing around with your original example, it looks like we do understand that `Constructor` in the callback is `Class<Foo> | Class<Bar>`, but `Constructor === Foo` does not refine. I'm not sure how hard it would be to add this refinement, so maintain my suggestion that you try to solve the underlying goal some other way. Hope this helps.

**Comment by mwalkerwells** [comment]
Ah, that's what I expected. I could use another approach, but I was hoping for something more reusable.

Should I leave this open? Not sure if you view this more as a feature request or bug.

Thanks for checking it out. :)
