### ISSUE TITLE
Covariance not enforced with ++

### ISSUE THREAD

**Issue by mroch** [facebook/flow#2861]
```js
function f(o: { +x: number }) {
  o.x++; // should error
  o.x = o.x + 1; // does error
}
```

**Comment by samwgoldman** [comment]
Eek. Good catch. This will probably be pretty straightforward, but fiddly to fix. Good thing I have plane travel coming up.

**Comment by mewdriller** [comment]
It fails on other assignment and arithmetic operators as well:

```js
// @flow

type State = {
  +n: number
};

let state: State = { n: 0 };

// ++
state.n++; // Should error.
state.n = state.n++; // Does error.

// --
state.n--; // Should error.
state.n = state.n--; // Does error.

// +=
state.n += 1; // Should error.
state.n = state.n + 1; // Does error.

// -=
state.n -= 1; // Should error.
state.n = state.n - 1; // Does error.

// *=
state.n *= 1; // Should error.
state.n = state.n * 1; // Does error.

// /=
state.n /= 1; // Should error.
state.n = state.n / 1; // Does error.

// %=
state.n %= 1; // Should error.
state.n = state.n % 1; // Does error.

// **=
state.n **= 1; // Should error.
state.n = state.n ** 1; // Does error.

// <<=
state.n <<= 1; // Should error.
state.n = state.n << 1; // Does error.

// >>=
state.n >>= 1; // Should error.
state.n = state.n >> 1; // Does error.

// >>>=
state.n >>>= 1; // Should error.
state.n = state.n >>> 1; // Does error.

// &=
state.n &= 1; // Should error.
state.n = state.n & 1; // Does error.

// ^=
state.n ^= 1; // Should error.
state.n = state.n ^ 1; // Does error.

// |=
state.n |= 1; // Should error.
state.n = state.n | 1; // Does error.
```

**Comment by Brianzchen** [comment]
Thanks @mewdriller they all seem to error as expected now. [try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA3oqKANQB2AXKHQK4C2ARlgE6IC+AbmTQsKUAGdCxJviKkKzJgAZQg5CFo1EkuQDo6NGgNAbcAC1gtoAE1A9usbru1Ss+0GR3F9h4xoAisFjidtwOTupgALRRLnp0MX5g5pY2oeHOXm50HhKu+okmYIHB6Y7OiBo0JHHeOdWgAIxJeBZWtvbltdm5We40TS0lIZ0RldE1fTlRZM1FrakdYV1TvfnTg-PDZWMaAFST66AHm6ZtaaOZR55He6fFQSPLu2DAh-Emsy0p7TtXHzcPmA5gFHn9IqAAKTvOpQr7zH4XZ7-WGA2GQ+6gbaXCF7A7ddx4+FnRbg1Zonp4zHY5EQgA8dJhPQZxOS5yWGQJOQp7gZ1LBOPGoAAfMKme5RayFr8ceS8h9RfzSoKNKKxVyRZLMYiOStrvLYWqlU9OUKAGTinIW7Xssn61Zm43goUAPUtoDdNtJsvtRxdTpVYAAPu6Q16ZbS5asgwHkUA)
