### ISSUE TITLE
Element direction value rtl seems to be wrongly reported

### ISSUE THREAD

**Issue by dej611** [facebook/flow#2864]
I've just started debugging an existing code base that uses HTML5 Canvas elements with flow.

One of the error flow reports regards these lines:

```js
const newCanvas = document.createElement('canvas');
newCanvas.dir = 'rtl';
```

The specific error is: `This type is incompatible with string enum`
And my flow IDE integration links to a dom.js definition file quoted here:

```
declare class HTMLElement extends Element {
  ...
  dataset: {[key:string]: string};
  dir: 'ltr' | 'trl' | 'auto';
```

But looking at the [spec](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/dir) it seems that the second string should be `rtl` rather than `trl`.

I don't have much experience with flow, so if this issue is incorrect please correct me. :)

Flow version: 0.35.0
OS Platform: OSX El Capitan - 10.11.6

**Comment by yuchi** [comment]
Yeah that’s totally wrong.
