### ISSUE TITLE
Range.insersectsNode() not supported 

### ISSUE THREAD

**Issue by willlma** [facebook/flow#2866]
I looked around, but couldn't find the browser support standard for adding methods to dom classes. I'd like to use [`Range.instersectsNode()`](https://developer.mozilla.org/en-US/docs/Web/API/Range/intersectsNode) by adding 

    intersectsNode(refNode: Node): bool
or

    intersectsNode: ?Function
here: https://github.com/facebook/flow/blob/c48dc1a3ad9652950ec19332a1e704412e92aef7/lib/dom.js#L736

Which makes more sense? Happy to make a PR, or if not appropriate, would love some advice on how to avoid the `property not found in Range` error

**Comment by asolove** [comment]
@calebmer what would be a good process for stuff like this? For additions to the basic DOM APIs, can anyone just make small PRs and get them reviewed? Should I gather a batch of all the open requests and do them at once?

**Comment by calebmer** [comment]
@asolove that would be great! Long term we want to move our library definitions to `flow-typed` where we can make the contribution process a lot simpler. For now it’s fine to submit either many small commits or one larger batched commit 😊
