### ISSUE TITLE
document.caretPositionFromPoint / caretRangeFromPoint do not typecheck

### ISSUE THREAD

**Issue by meleyal** [facebook/flow#2868]
Neither [`document.caretPositionFromPoint`](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretPositionFromPoint) (standards track) nor [`document.caretRangeFromPoint()`](https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint) (old syntax) typecheck, producing the following flow error:

```
caretPos = document.caretPositionFromPoint(x, y)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `caretPositionFromPoint`. Function cannot be called on
caretPos = document.caretPositionFromPoint(x, y)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `caretPositionFromPoint` of unknown type
```

**Comment by Brianzchen** [comment]
In 4 years time, this looks still experimental and not supported in most major browsers, we could add this as an optional method but given the lack of support it would be dangerous to encourage users towards this.
