### ISSUE TITLE
Friendlier experience with new projects

### ISSUE THREAD

**Issue by fgarcia** [facebook/flow#2869]
So far my best experience with Flow is adding types incrementally. That is also the main focus of the documentation encouraging the use of `// @flow` comments on each new file.

However I am a bit at a lost about how to use Flow with a completely new project. I want type checking in all my JS files since day 0. We have the option of:

```
[options]
all=true
```

But that is the worst choice, since it will start checking every third party code in my project.

I might want to do this:

```
[ignore]
<PROJECT_ROOT>/node_modules/.*

[options]
all=true
```

And that also is full of problems breaking lots checks.

Is there an easy way to just tell Flow I want **my code** to be checked? Something like check all files under my `./src` folder (no need of marking each file individually) ?

**Comment by russellmcc** [comment]
I don't really see how _requiring_ a comment at the top of the file is acceptable.  What if two projects did this?

**Comment by mroch** [comment]
@russellmcc it only has to be in a comment at the top of the file before any statement (excluding directives like `"use strict"`).

```
"use strict";

// Copyright ...

/**
 * License
 */

// @flow

...
```

would work, for example. Or you could put the `@flow` in one of the previous comments, like

```
/**
 * Documentation about my module
 *
 * @flow
 */
```

I can't think of a way that this would conflict with other projects.

**Comment by russellmcc** [comment]
Thanks!  I was under the mistaken impression the comment literally had to be the first thing in the file.  This makes the situation a lot better!  I would still prefer to not need the comment, though.

**Comment by mroch** [comment]
I attempted something that might help a while back. https://github.com/facebook/flow/pull/903

This is also pretty similar to https://github.com/facebook/flow/issues/284, so check out the discussion there too.

**Comment by asolove** [comment]
I think this is closable now. You can start with `all` and ignore `node_modules`, which seems to me like it satisfies the original request.
