### ISSUE TITLE
Bounded polymorhism with React

### ISSUE THREAD

**Issue by agentcooper** [facebook/flow#2871]
I am probably missing something obvious here:

```js
// @flow

import React, { Component } from 'react';

import { render } from 'react-dom';

type BasicHighlight = {
    id: string,
    text: string,
};

class HighlightList<X: BasicHighlight> extends Component {
    props: {
        items: Array<X>
    }
    
    render() {
        return <div>{ this.props.items.map(item => <li>{ item.text }</li>) }</div>;
    }
}

const highlights = [
    { id: '2', text: 'bla' }
];

render(<HighlightList items={ highlights }/>, document.body);
```

```bash
src/test.js:12
 12: class HighlightList<X: BasicHighlight> extends Component {
                            ^^^^^^^^^^^^^^ object type. This type is incompatible with
 12: class HighlightList<X: BasicHighlight> extends Component {
           ^^^^^^^^^^^^^ some incompatible instantiation of `X`

src/test.js:23
 23:     { id: '2', text: 'bla' }
         ^^^^^^^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
 12: class HighlightList<X: BasicHighlight> extends Component {
           ^^^^^^^^^^^^^ some incompatible instantiation of `X`
```

[tryflow.org](https://tryflow.org/?code=Ly8gQGZsb3cKCmltcG9ydCBSZWFjdCwgeyBDb21wb25lbnQgfSBmcm9tICdyZWFjdCc7CgppbXBvcnQgeyByZW5kZXIgfSBmcm9tICdyZWFjdC1kb20nOwoKdHlwZSBCYXNpY0hpZ2hsaWdodCA9IHsKICAgIGlkOiBzdHJpbmcsCiAgICB0ZXh0OiBzdHJpbmcsCn07CgpjbGFzcyBIaWdobGlnaHRMaXN0PFg6IEJhc2ljSGlnaGxpZ2h0PiBleHRlbmRzIENvbXBvbmVudCB7CiAgICBwcm9wczogewogICAgICAgIGl0ZW1zOiBBcnJheTxYPgogICAgfQogICAgCiAgICByZW5kZXIoKSB7CiAgICAgICAgcmV0dXJuIDxkaXY+eyB0aGlzLnByb3BzLml0ZW1zLm1hcChpdGVtID0+IDxsaT57IGl0ZW0udGV4dCB9PC9saT4pIH08L2Rpdj47CiAgICB9Cn0KCmNvbnN0IGhpZ2hsaWdodHMgPSBbCiAgICB7IGlkOiAnMicsIHRleHQ6ICdibGEnIH0KXTsKCnJlbmRlcig8SGlnaGxpZ2h0TGlzdCBpdGVtcz17IGhpZ2hsaWdodHMgfS8+LCBkb2N1bWVudC5ib2R5KTs=)

**Comment by mkotsur** [comment]
+1

**Comment by rodrigopr** [comment]
Seems to work with sintax:
```jsx
type Props<X> = { items: Array<X> };
class HighlightList<X: BasicHighlight> extends Component<void, Props<X>, void> {
```
[tryflow.org](https://tryflow.org/?code=Ly8gQGZsb3cKCmltcG9ydCBSZWFjdCwgeyBDb21wb25lbnQgfSBmcm9tICdyZWFjdCc7CgppbXBvcnQgeyByZW5kZXIgfSBmcm9tICdyZWFjdC1kb20nOwoKdHlwZSBCYXNpY0hpZ2hsaWdodCA9IHsKICAgIGlkOiBzdHJpbmcsCiAgICB0ZXh0OiBzdHJpbmcsCn07Cgp0eXBlIFByb3BzPFg+ID0gewogICAgaXRlbXM6IEFycmF5PFg+Cn0KCmNsYXNzIEhpZ2hsaWdodExpc3Q8WDogQmFzaWNIaWdobGlnaHQ+IGV4dGVuZHMgQ29tcG9uZW50PHZvaWQsIFByb3BzPFg+LCB2b2lkPiB7CiAgICByZW5kZXIoKSB7CiAgICAgICAgcmV0dXJuIDxkaXY+eyB0aGlzLnByb3BzLml0ZW1zLm1hcChpdGVtID0+IDxsaT57IGl0ZW0udGV4dCB9PC9saT4pIH08L2Rpdj47CiAgICB9Cn0KCmNvbnN0IGhpZ2hsaWdodHMgPSBbCiAgICB7IGlkOiAnMicsIHRleHQ6ICdibGEnIH0KXTsKCnJlbmRlcig8SGlnaGxpZ2h0TGlzdCBpdGVtcz17IGhpZ2hsaWdodHMgfS8+LCBkb2N1bWVudC5ib2R5KTs=)

But I guess you could use
```
  props: {
    items: Array<BasicHighlight>
  }
```
directly if `BasicHighlight` is just a type alias.

**Comment by gcanti** [comment]
This works

```js
class HighlightList<X: BasicHighlight> extends Component<void, { items: Array<X> }, void> {
    render() {
        return <div>{ this.props.items.map(item => <li>{ item.text }</li>) }</div>;
    }
}
```

because since the signature of `Component` is `Component<DefaultProps, Props, State>`, you must convince Flow that your props are compatible with `Props` for all `X`s

Same as 

```js
class A<Props> {
  props: Props;
}

class B<X> extends A { // <= This type is incompatible with some incompatible instantiation of `X`
  props: X
}

// this is ok
class B<X> extends A<X> {}
```

**Comment by asolove** [comment]
Given the responses with working solutions already, and that the v0.53 upgrade to `React.Component` typing resolved some of the confusion by making authors specify prop types, I think this can be closed. (/cc @calebmer)
