### ISSUE TITLE
[bug] Looses the type of a disjoint union inside an arrow function

### ISSUE THREAD

**Issue by goshakkk** [facebook/flow#2877]
First off, thanks for the amazing tool. Flow has been an incredible time-saver for me and I appreciate all the collective effort that went into it.

I'd like to report a bug that's best demonstrated by code:

[Exhibit A](https://flowtype.org/try/#0C4TwDgpgBAqgzhATlAvFA3lAlnAYgewBtD8B3LAOwHMAuKAI3yKgF8BuAKA9EigEEAxsCz4KqKBygYoPCHQDkuAPIAZFUoDqAfRgBlAKIAleQBpsAEwAedCgFcAtvSSsoAHwlTMshbqUBZfQAVAAkASQA5AHF5Vk4OADNbCiERMVsERDhDCHNbASQACjhgAENgOX5ERBKQAB54JAA+MxKU0TpBYVEASg6qmvqMxoxJKDhyYAEACygC1q6KADpZbpGpKQEShChFVXVtPSN5OnRR9agBUWLsPCxM4HF51MWsK1QUNAAGNigAel+oBR8A8qFgAG6UKhQEpiJCIfCIM7rS4Ua5wWxUKgQYqpODiYplCCLewlMAFAqQTKiMyvSyrFDDU7nc5YeKzWlQACEH2hbSWtNWiAgwFsiDElLgoh+-ygACElP4kechSKxdJFhqJdSbgRiGRIXROVr+XgiCRyNRYkrWN1OMyoCrRWJ0ZjsQs4Hb1iwkeYIPESrZCMA6I61QTyp7vSwgA):

This code is supposed to be working but it's not. I guess what might be happening is, the `action` type information somehow gets lost inside the map arrow function.

```javascript
type User = { isFollowing: bool };

type Action = 
  { type: 'FOLLOW_USER', idx: number } | 
  { type: 'SOMETHING' };

function usersReducer(state: Array<User>, action: Action): Array<User> {
  switch (action.type) {
    case 'FOLLOW_USER': {
      const isFirst = action.idx === 0; // not giving an error
      const suggestions = state.map((person, idx) => {
        if (idx !== action.idx) return person; // BOOM
        return { ...person, isFollowing: !person.isFollowing };
      });
      return suggestions;
    }
    default: return state;
  }
}
```

```
12:         if (idx !== action.idx) return person; // BOOM
                               ^ property `idx`. Property not found in
12:         if (idx !== action.idx) return person; // BOOM
                        ^ object type
```

[Exhibit B](https://flowtype.org/try/#0C4TwDgpgBAqgzhATlAvFA3lAlnAYgewBtD8B3LAOwHMAuKAI3yKgF8BuAKA9EigEEAxsCz4KqKBygYoPCHQDkuAPIAZFUoDqAfRgBlAKIAleQBpsAEwAedCgFcAtvSSsoAHwlTMshbqUBZfQAVAAkASQA5AHF5Vk4OADNbCiERMVsERDhDCHNbASQACjhgAENgOX5ERBKQAB54JAA+MxKU0TpBYVEASg6qmvqMxoxJKDhyYAEACygC1q6KADpZbpGpKQEShChFVXVtPSN5OnRR9agBUWLsPCxM4HF51MWsK1QUNAAGNigAel+oBR8A8qFgAG6UKhQEpiJCIfCIM7rS4Ua5PUShN5odFLV6WH7-C4lMDAWyIaDAKbQMElQi2CBIjZXB5wWxUKgQYqpODiYplCCLezEgoFSCZURmPGrFDDU7nc5YeKzPFQACEH2hbQomMsq3JpMQYjFcFEBIBQKgJGozkY+HscEZ631ZLEmEW7uNEpuBGIZEhdFVntxeCIJHI1FijpY3U48qgzsNYzZHK5V1j6xYSPMEHiJVshGAdATYj55XTmZYQA):

However, if I capture a field from `action` outside the arrow function, then use it in it, things seem to work.

```javascript
type User = { isFollowing: bool };

type Action = 
  { type: 'FOLLOW_USER', idx: number } | 
  { type: 'SOMETHING' };

function usersReducer(state: Array<User>, action: Action): Array<User> {
  switch (action.type) {
    case 'FOLLOW_USER': {
      const isFirst = action.idx === 0; // not giving an error
      const actionIdx = action.idx; // capture the value
      const suggestions = state.map((person, idx) => {
        if (idx !== actionIdx) return person; // no longer booms
        return { ...person, isFollowing: !person.isFollowing };
      });
      return suggestions;
    }
    default: return state;
  }
}
```

```
No errors!
```

[Exhibit C](https://flowtype.org/try/#0C4TwDgpgBAqgzhATlAvFA3lAlnAYgewBtD8B3LAOwHMAuKAI3yKgF8BuAKA9EigEEAxsCz4KqKBygYoPCHQDkuAPIAZFUoDqAfRgBlAKIAleQBpsAEwAedCgFcAtvSStOHAGa2KQkWNsJEcIYQ5rYCSAAUcMAAhsBy-IiI0SAAPPBIAHxm0d6idILCogCU+YnJaf4ZGJJQcOTAAgAWUOE5hRQAdLJF1VJSAtEIUIqq6tp6RvJ06DV9UAKiUdh4WAHA4m0+HVhWqChoAAxsUAD0J1AU+OtUWABulFRQ0WJIiPiIs30LFEtwtlRUCBRHxwcRRWIQDr2aJgcLhSABURmHaWHooKozOZzLBuFooqAAQn2T1ynRRPUQEGAtkQYgRcFExzOF3wUBI1GcjHw9jgnzmlOptOkHRF9KRywIxDIDzoBLFZLwRBI5GoLj5rCKnCxUAFNLEfwBQPacC1fRYn3MEDc0VshGAdF1QvBcVN5pYQA):

Finally, this demonstrates type information is not lost if `Action` is an object type, instead of being a disjoint union.

```javascript
type User = { isFollowing: bool };

type Action = 
  { type: 'FOLLOW_USER', idx: number };

function usersReducer(state: Array<User>, action: Action): Array<User> {
  switch (action.type) {
    case 'FOLLOW_USER': {
      const isFirst = action.idx === 0; // not giving an error
      const suggestions = state.map((person, idx) => {
        if (idx !== action.idx) return person; // no longer booms
        return { ...person, isFollowing: !person.isFollowing };
      });
      return suggestions;
    }
    default: return state;
  }
}
```

```
No errors!
```

This is a bug because in the case A, there is enough information to conclude which branch of the union is being referred inside the `case` statement, and there are no new facts inside the arrow function that would change that.

**Comment by jesseschalken** [comment]
Narrowing on a variable is undone inside a closure that captures that variable because Flow can't prove that the variable won't change before the closure is called.

One workaround is to capture a `const` variable instead:

```js
type User = { isFollowing: bool };

type Action = 
  { type: 'FOLLOW_USER', idx: number } | 
  { type: 'SOMETHING' };

function usersReducer(state: Array<User>, action_: Action): Array<User> {
  const action = action_;
  switch (action.type) {
    case 'FOLLOW_USER': {
      const isFirst = action.idx === 0; // not giving an error
      const suggestions = state.map((person, idx) => {
        if (idx !== action.idx) return person; // okay now
        return { ...person, isFollowing: !person.isFollowing };
      });
      return suggestions;
    }
    default: return state;
  }
}
```

**Comment by goshakkk** [comment]
@jesseschalken wow, thanks for the fast reply! That could work... but it still feels like a hack, much like capturing `idx` before the closure.

I'm not sure if it's tricky to implement this, but maybe Flow could look for argument reassignments, and if none exist, assume it's proven it won't change?

**Comment by jesseschalken** [comment]
@goshakkk That sounds reasonable to me, but you'll have to wait for a Flow dev to say for certain and whether it's achievable in Flow's design.

**Comment by gcanti** [comment]
Another way to fix the error is to set the `experimental.const_params=true` option in the `[options]` section of `.flowconfig`

Related

- https://github.com/facebook/flow/issues/2836
- https://github.com/facebook/flow/issues/2831
- https://github.com/facebook/flow/issues/2768
- https://github.com/facebook/flow/issues/2704
- https://github.com/facebook/flow/issues/2693
- https://github.com/facebook/flow/issues/2602
- https://github.com/facebook/flow/issues/2513
- https://github.com/facebook/flow/issues/2318
