### ISSUE TITLE
Cannot access property of a type

### ISSUE THREAD

**Issue by ppershing** [facebook/flow#2881]
I would expect that
```
type t = {
  	x: () => void,
}

const fn: t.x = () => {}
```
would work, however flow returns
```
5: const fn: t.x = () => {}
             ^ x. Property cannot be accessed on
1: type t = {
        ^ type `t`
```

Any suggestions on how to work around this issue without explicitly declaring all inner types?

**Comment by gcanti** [comment]
Seems a dupe of https://github.com/facebook/flow/issues/2865
