### ISSUE TITLE
GLIBC_2.15, GLIBC_2.14 not found

### ISSUE THREAD

**Issue by jeantimex** [facebook/flow#2885]
Hello community, I am using Flow and it's working pretty well on my local Macbook pro. But when I build my project on Jenkins server, it starts to complain:

```
node_modules/flow-bin/flow-linux64-v0.34.0/flow: /lib64/libc.so.6: version `GLIBC_2.15' not found (required by node_modules/flow-bin/flow-linux64-v0.34.0/flow)
node_modules/flow-bin/flow-linux64-v0.34.0/flow: /lib64/libc.so.6: version `GLIBC_2.14' not found (required by node_modules/flow-bin/flow-linux64-v0.34.0/flow)
flow failed!
```

The current version of glibc on the Jenkins server is 2.12, and it's quite hard to upgrade it since it's company's server and there are a lot of concern about upgrading glibc.

Is it possible to compile the Flow with glibc 2.12? And how to get around this error?

Thanks a lot!

**Comment by mroch** [comment]
yeah, this is a problem sometimes. the Linux binaries we distribute are built by Travis, which uses Ubuntu 12.04 LTS and has glibc-2.15. 12.04 is now 3 LTS versions behind, so this is already pretty old.

if you need to run on an even older version of glibc, compiling from source should work. if your distro has an ancient glibc, it probably also has an ancient ocaml, so use `opam` to install a newer (4.03.0) ocaml.

**Comment by benwiley4000** [comment]
@mroch has the team considered producing multiple builds to get around this? I've seen multiple issue threads about this, and I'm experiencing the same problem.
