### ISSUE TITLE
Error when return type is bound type parameter

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#2886]
Here is an [example code](https://flowtype.org/try/#0C4TwDgpgBAKhAewoF4oG8BQUoDsD2AJhDOBAFxQDMGAvhhgMYA2AhgM5uwLAByh0mbPiIlIKKligEWwFmTbAATgEscAc0kM8OBYoCuDYHkUAKabPlLVagJTpJ2YAAtlbAHTmW4z5Lp1GrBxQAEoQOESKEIr22AyRMsTcfERQADzA3GRwiAB8UGYycrrWNmQZiDHYUJHAeoo4uBAA7lyIyRAFsja+tEA):

```js
type Text = {
  nodeType: 3
}

class TextNode {
  nodeType = 3
  data:string
  constructor(data:string) {
    this.data = data
  }
}

class Renderer {
  createTextNode <text:Text> (data:string):text {
    return new TextNode(data)
  }
}
```

Which produces following errors:

```
15:     return new TextNode(data)               ^ TextNode. This type is incompatible with the expected return type of
14:   createTextNode <text:Text> (data:string):text {      ^ some incompatible instantiation of `text`
```

This example is contrived and type parameter is redundant, that is because actual code it's based of is more complex and type parameter there is necessary.

**Comment by vkurchatkin** [comment]
Everything seems alright here. `TextNode` is subtype of `Text`, but it's not necessarily a subtype of some (unknown) subtype of `Text`.
