### ISSUE TITLE
macOS build missing for 0.36

### ISSUE THREAD

**Issue by dnalborczyk** [facebook/flow#2887]
no build for macOS on the release page  https://github.com/facebook/flow/releases/tag/v0.36.0

this also affects the flow-typed build system.

**Comment by dnalborczyk** [comment]
https://github.com/flowtype/flow-typed/issues/483

**Comment by dnalborczyk** [comment]
binaries just showed up. closing.

**Comment by gabelevi** [comment]
The way it's supposed to work is like this:

1. I add a git tag
2. Travis builds the OSX and Linux builds and uploads them to the release
3. AppVeyor builds the Windows build and uploads it to the release

Unfortunately, Travis took forever to start building, and when it did the OSX machine repeatedly failed to clone the repo. So I did it by hand :P

Anyway, sorry for the delay!

**Comment by dnalborczyk** [comment]
@gabelevi no worries! thanks for taking care of it!
