### ISSUE TITLE
Incorrect subtyping rules for object types with polymorphic functions

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#289]
Plain polymorphic function types seem to work correctly.

```javascript
/* @flow */

type Id<T> = (t: T) => T;
var id: Id<string> = function() {}

// test.js|4 col 32 error|  undefined
// || This type is incompatible with
// test.js|4 col 12 error|  string
// || 
```

But when the polymorphic function is part of an object type, the return type does not seem to be considered in subtyping.

```javascript
/* @flow */

type IdObj = {
  id<T>(t: T): T;
}

// void return type checks
var ex1: IdObj = {
  id: function<T>() {}
}

// unmatched return type checks
var ex3: IdObj = {
  id: function<T>(t):string {
    return t;
  }
}
```

**Comment by jeffmo** [comment]
I'm able to repro and confirm that Flow is ignoring the `:string` return type specified in the `ex3.id` function:

https://gist.github.com/jeffmo/daf7da64c58134b74e0c

Thanks for the report! We'll get this triaged.

**Comment by samwgoldman** [comment]
This is working for me now.
