### ISSUE TITLE
Could not decide which case to select

### ISSUE THREAD

**Issue by stijnvanderlaan** [facebook/flow#2892]
This
```js
export type InitState = {
  type: "init",
  lang: string,
}

export type SecondState = {
  type: "second",
  lang: string,
}

export type State = InitState | SecondState

const transform = (input:State, lang:string) : State => {
  return {
    ...input,
    lang
  }
}

let state: State = {
  type: "init",
  lang: "en"
}

let state2 = transform(state, "nl")

```
Results in the next error.

```
 47:   return {
              ^ object literal. Could not decide which case to select
 46: const transform = (input:State, lang:string) : State => {
                                                    ^^^^^ union type
  Case 1 may work:
   44: export type State = InitState | SecondState
                           ^^^^^^^^^ InitState
  But if it doesn't, case 2 looks promising too:
   44: export type State = InitState | SecondState
                                       ^^^^^^^^^^^ SecondState
  Please provide additional annotation(s) to determine whether case 1 works (or consider merging it with case 2):
  .type

```

Al the cases have `lang`, so I think it should return the same type as it gets, like the next situation, which works fine:

```js
const transform = (input:State, lang:string) : State => {
  return input
}
```

Casting the output to `State` or `typeof input` does not resolve the issue.

**Comment by vkurchatkin** [comment]
Here is a problem: when you something to have type `State` it should either have type `State` already, or it should be one of `InitState` or `SecondState`. Result of object is none of those, it has type `{ type: 'init' | 'second', lang: string }` or something like this.

**Comment by stijnvanderlaan** [comment]
But when `SecondState` has additional parameters you have to make them optional because of this `transform`. This situation is just a illustration what happens in redux when `transform` is a reducer. It would be great to have a reducer with differente states, and be able te change the state without actually knowing which state you are because al cases are compatible.

**Comment by vkurchatkin** [comment]
> be able te change the state without actually knowing which state you are because al cases are compatible

Well, you can actually change (mutate) it, but object spread merges branches together

**Comment by stijnvanderlaan** [comment]
Off course, but redux (and functional programming in general) is build around immutability to knows when changes has been made. I understand it's hard for flow to choose which type it has to output, but it is not impossible, it has the information to decide, right? Unfortunately for me it is now impossible to add flow type to this situation. Thanks for your feedback.

**Comment by gcanti** [comment]
You could refine `input`

```js
function transform(input: State, lang: string): State {
  if (state.type === 'init')
    return {
      type: 'init',
      ...input,
      lang
    }
  return {
    type: 'second',
    ...input,
    lang
  }
}
```

**Comment by stijnvanderlaan** [comment]
Yes, but I have to much types, it would only make the code less easy to manage which is not really beneficial. I think I am going to extract that code into another reducer. Still this enhancement would be very welcome.

**Comment by stijnvanderlaan** [comment]
I was thinking some more: Why does flow needs to know which one it is? Can't the function just return a union type in the case where it's undecidable?

**Comment by rsolomon** [comment]
Apologies for bumping such an old thread, but I'm curious if anyone has found a workaround for this. Manual refinement works fine if the disjoint union has 2 or 3 cases, but it not reasonable for larger sets. I'm not clear on why creating a new object from an old one via spread and changing one property (shared amongst all cases) would not pass Flow checks.

[Example here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeiooAdgIYC2WAXKAOQBiA8m0wDRmgBuVaAFcsAZ0a4ATpKpoAPKJSSAlhQDmAPh4BfANzJ02UACFCJXtTqMmx3ACVuvAcLETpshUtWad+xJCEKAGMUZVgKUBQxFDkAFQlQAB8TDQAKKkk1RliASmzzcmVIUHTMgDpLHAJq5lsHHILyUEksFCFJCNImprLejLUebvJnEXFQAG1esv6ykbEuZijFJgBdQaa9Xm1eFraO0H79bSA)

**Comment by AndersDJohnson** [comment]
Any solution to this yet?

**Comment by Tomekmularczyk** [comment]
```
export default connect(
  (state: ReduxState) => ({
    modalPayload: state.ui.modalPayload,   // Error:(15, 16) Flow: function call. Could not decide which case to select intersection type 
  }),
)(InfoContent);
```

ReduxState is a state declared in flow typed directory as global. I don't know what the error means. After I upgraded `"flow-bin": "^0.57.3",`

**Comment by nodkz** [comment]
Some built-in "private" type will be very useful. 
Something like `$PreferFirstCase<T>` where T must be a union type.
 
**[JUST PROPOSAL, NOT IMPLEMENTED]**

**Comment by shinout** [comment]
+1 for `$PreferFirstCase<T>`!

**Comment by villesau** [comment]
The issue is actually about broken spread. This PR will fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by sahara18** [comment]
Guess managed to rewrite via Object.assign

**Comment by nmote** [comment]
This code no longer errors on master

**Comment by yatin-sodel** [comment]
Flow a ridiculous language
