### ISSUE TITLE
React - Required property not being enforced

### ISSUE THREAD

**Issue by jsheetzati** [facebook/flow#2894]
Trying to move our project from PropTypes to flow and having an issue with properties that should be required.  In the example below, I have baseUrl as a required property.  However, when using the Header component and not specifying baseUrl, no error is reported from flow.  Is there something wrong with the setup or does flow not work for this scenario?

```
type Props = {
	baseUrl: string
};

const Header = (props: Props): Element => {
	return (
		<div>my header is here - {props.baseUrl}</div>
	);
};

export default Header;
```

```
export default class App extends Component {
	render() {
		return (
			<Header /> // no error for not requiring baseUrl
		);
	}
}
```

**Comment by gcanti** [comment]
Everything seems ok here, I can see the error

Header.js

```js
// @flow
import React from 'react'

type Props = {
  baseUrl: string
};

const Header = (props: Props): React.Element<*> => {
  return (
    <div>my header is here - {props.baseUrl}</div>
  )
}

export default Header
```

index.js

```js
// @flow

import React from 'react'
import Header from './Header'

export default class App extends React.Component {
  render() {
    return (
      <Header /> // property `baseUrl`. Property not found in. See: src/Header.js:8
    )
  }
}
```

Make sure you have the `// @flow` pragma on top

**Comment by jsheetzati** [comment]
Thanks, yes, I have /* @flow */ at the top... what version of flow are you using?  I'm on 0.36.0.

**Comment by gcanti** [comment]
> I'm on 0.36.0

Me too

**Comment by jsheetzati** [comment]
Strange.. I literally copied your code as-is and do not receive any errors in nuclide.

**Comment by gcanti** [comment]
Weird (I'm running Flow from the command line)

<img width="803" alt="error" src="https://cloud.githubusercontent.com/assets/878912/20636288/80ea1c22-b36a-11e6-83e4-b022756cd1c2.png">

**Comment by jsheetzati** [comment]
I just tried the command line too.  Getting the error there.. Strange.  Maybe this better suited for the nuclide repo.  Thanks for the help! :)
