### ISSUE TITLE
flow forgets an object has type-checked

### ISSUE THREAD

**Issue by petemill** [facebook/flow#2895]
It seems flow can be confused to think that a type has not been tested to see if it is an *object*, even if it previously has been checked.

Example which results in error:
```js
// @flow
declare class test {
  possibleObject?: string | Buffer | {[key: string]: mixed};
}

function getSomeProperties(tester: test) {
  
  let firstThing: ?string;
  let secondThing: ?string;
  
  if (tester.possibleObject && typeof tester.possibleObject === 'object') {
    firstThing = getIfString(tester.possibleObject.firstThing);
    secondThing = getIfString(tester.possibleObject.secondThing);
    //error: property `secondThing`. Property cannot be accessed on possibly undefined value undefined
    //error: property `secondThing`. Property not found in Buffer
  }
}

function getIfString(thing): ?string {
 
  if (typeof thing === 'string') {
    return thing;
  }
  return null;
}
```

**note that any reference to tester.possibleObject.x after the first reference errors, even though the first reference does not**

However, with the same type signature, but not a property of a class, **0 errors**:
```js
// @flow
declare type test = string | Buffer | {[key: string]: mixed};

function getSomeProperties(possibleObject?: test) {
  
  let firstThing: ?string;
  let secondThing: ?string;
  
  if (possibleObject && typeof possibleObject === 'object') {
    firstThing = getIfString(possibleObject.firstThing);
    secondThing = getIfString(possibleObject.secondThing);
  }
}

function getIfString(thing): ?string {
 
  if (typeof thing === 'string') {
    return thing;
  }
  return null;
}
```

**Comment by gcanti** [comment]
This is because calling functions (such as `getIfString`) can potentially invalidate previous checks. Before you check some value you can assign it to local const to avoid this.

```js
function getSomeProperties(tester: test) {

  let firstThing: ?string;
  let secondThing: ?string;

  const possibleObject = tester.possibleObject
  if (possibleObject && typeof possibleObject === 'object') {
    firstThing = getIfString(possibleObject.firstThing);
    secondThing = getIfString(possibleObject.secondThing);
  }
}
```

Related

- https://github.com/facebook/flow/issues/2877
- https://github.com/facebook/flow/issues/2836
- https://github.com/facebook/flow/issues/2831
- https://github.com/facebook/flow/issues/2768
- https://github.com/facebook/flow/issues/2704
- https://github.com/facebook/flow/issues/2693
- https://github.com/facebook/flow/issues/2602
- https://github.com/facebook/flow/issues/2513
- https://github.com/facebook/flow/issues/2318

**Comment by petemill** [comment]
Yeah what you say makes sense, thanks @gcanti. Although I do not immediately see how it applies in this case: It seems that, in my example, `getIfString` is only given the value of `possibleObject.firstThing`, so I don't see how it could be possible for it to change the reference of `possibleObject`, which it itself does not have a reference to.

*(Even if that is possible, I guess I just assumed that flow knew the extend of what the `getIfString` function does and knows it does not change the reference.)*

**Comment by petemill** [comment]
After reading through the other bug reports (and the [caveat docs](https://flowtype.org/docs/dynamic-type-tests.html#caveats)), I understand now that flow treats any function as being able to manipulate any non-local references.
