### ISSUE TITLE
No type check for Set() initial values

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/flow#2896]
Flow v0.36.0

Works for Map, does not work for Set.

The following shows no error when initializing a Set with the wrong types:

```
const s1: Set<number> = new Set(['foo','bar']);
const s2: Set<string> = new Set([1,2,3,4,5]);
```

This does show an error:

```
const m: Map<number,number> = new Map([['foo','bar']]);
```

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2665
