### ISSUE TITLE
Provide a Flow playground

### ISSUE THREAD

**Issue by Davidhanson90** [facebook/flow#29]
Provide a site where users can experiment with flow like the typescript playground. 

http://www.typescriptlang.org/Playground

It's a great way to aid adoption.

**Comment by jeffmo** [comment]
It looks like @unknownexception has built a version of this over at tryflow.org -- woo!

**Comment by volkanunsal** [comment]
Great work! Thanks @unknownexception!

**Comment by fkling** [comment]
Also noted here btw: https://github.com/facebook/flow/wiki/3rd-party-tools
