### ISSUE TITLE
Wrong number of type arguments in declaration isn't detected until use

### ISSUE THREAD

**Issue by Macil** [facebook/flow#2913]
Minor issue: this code has a Flow mistake, but Flow doesn't give an error. The Emitter type requires two type arguments, but the declaration of bar only gives one. Flow only gives an error if the commented-out line is uncommented.

```js
/* @flow */

type Emitter<V,E> = {
  value(value: V): boolean;
  error(e: E): boolean;
  end(): void;
};

declare function bar<V>(cb: (em: Emitter<V>) => void): void;

bar(em => {
  // em.value(5);
});
```

**Comment by TrySound** [comment]
Fixed
