### ISSUE TITLE
support for React's Context

### ISSUE THREAD

**Issue by jhegedus42** [facebook/flow#2916]
It seems that at the moment there is no support for [React Context](https://facebook.github.io/react/docs/context.html). 

I am trying to make [this](https://egghead.io/lessons/javascript-redux-passing-the-store-down-implicitly-via-context) code type-safe with flow but it does not seem to be possible.

**Comment by vkurchatkin** [comment]
It's inherently impossible to make context type-safe. Since it's passed implicitly, it can only be verified at runtime

**Comment by jhegedus42** [comment]
Thanks for the clarification @vkurchatkin !

**Comment by milesj** [comment]
Jumping in this as I'm running into the same situation. Wouldn't a 4th generic argument solve this?

```
type Context = { foo: string };

class Foo extends React.Component<{}, Props, State, Context> {}
```

**Comment by lifeiscontent** [comment]
@vkurchatkin any updates on this seems @milesj update is working, right?

**Comment by awitherow** [comment]
@vkurchatkin can you please provide some information on this ticket as the update from @milesj works?

**Comment by awitherow** [comment]
@vkurchatkin any updates on this?

**Comment by vkurchatkin** [comment]
@awitherow the problem with this approach is that it doesn't really provide any safety, but breaks a lot of existing code. I'm not sure that it's worth it

**Comment by awitherow** [comment]
Well is there a way we could make this happen in some way?

Assuming flow is the future, our project has completely switched from using propTypes to using flow... except it does not work in 3 lines of code where we use context types. It would be great to be able to remove the package `prop-types` completely and be able to have complete consistency.

Or is it a "not possible".

**Comment by vkurchatkin** [comment]
> Or is it a "not possible".

I would say that, no it's not possible. And context requires propTypes anyway.

**Comment by Peeja** [comment]
Why is this not possible? Flow knows statically all of the ways the components could be put together. Can't it find type problems in the context tree?

**Comment by milesj** [comment]
All we really need (I want) to solve/type annotate is accessing context in components: `const a = this.context.foo`.

```
class Foo extends React.Component<{}, {}, { foo: string }> {}
```

**Comment by zhengxiaoyao0716** [comment]
Well, I resolved it by define the context again.
![image](https://user-images.githubusercontent.com/12682063/48764856-ca483680-eceb-11e8-814d-d8fbd020a877.png)

**Comment by milesj** [comment]
This issue was about the legacy context API, not the new one.

**Comment by zhengxiaoyao0716** [comment]
@milesj oh, I'm sorry I didn't notice it...
