### ISSUE TITLE
get-imports does not search for root dir

### ISSUE THREAD

**Issue by mroch** [facebook/flow#2920]
```
cd some_dir
flow get-imports ~/some_other_dir/foo.js
```

runs flow in `some_dir` (the cwd) and errors saying it can't find `~/some_other_dir/foo.js`. it succeeds if you pass `--root`, like this:

```
flow get-imports --root ~/some_other_dir ~/some_other_dir/foo.js
```

`get-imports` should act like all other commands and guess the root from the path, unless overridden by `--root`.

**Comment by SamChou19815** [comment]
This command no longer exists.
