### ISSUE TITLE
Is this expected behaviour?

### ISSUE THREAD

**Issue by vaclavhofler** [facebook/flow#2926]
Code:

```
/* @flow */

const arr = []
arr[0].toLowerCase()
```

Result: No errors!

**Comment by vkurchatkin** [comment]
Yes, this is expected. Flow doesn't have information about type of array, so it behaves as `Array<any>`.

**Comment by CodyReichert** [comment]
I found [this sections in the docs](https://flowtype.org/docs/nullable-types.html#undefined-values-and-optional-types) that does lead me to believe this is expected behavior:

> Flow ignores the possibility of undefined resulting from object property and array element accesses. Being stricter would force the programmer to do undefined checks (like null checks) on each dereference of an array element or object property to get anything useful done.

**Comment by vaclavhofler** [comment]
Thanks
