### ISSUE TITLE
state: ?Person

### ISSUE THREAD

**Issue by StokeMasterJack** [facebook/flow#2932]
I like to have state be optional. Then I can do something like:

```
render(){
    if(this.state === null) return <Loading/>
    ....
}
```
And then, when the initial person is loaded, I do this:

`this.setState(person);`

But this causes errors:

```
 67:                     this.setState(person);
                         ^^^^^^^^^^^^^^^^^^^^^^^ call of method `setState`
 67:                     this.setState(person);
                                       ^^^^^^^^ property `address` of object type. Property cannot be assigned on possibly null value
 45:     state: ?Person;
                 ^^^^^^^^ null
```

But I don't understand why this should be an error. React seems OK with calling setState when state is null. Why should flow complain?

**Comment by gcanti** [comment]
Seems a problem with `$Shape`

```js
type Person = { name: string };
type State = $Shape<?Person>;
({ name: 'Giulio' }: State) // <= error: property `name` of object literal. Property cannot be assigned on possibly null value
```

**Comment by StokeMasterJack** [comment]
What is $Shape? Is that in the docs?

**Comment by gcanti** [comment]
> What is $Shape?

See here http://sitr.us/2015/05/31/advanced-features-in-flow.html

> Is that in the docs?

No, but is used in the official react libdef for the `setState` method https://github.com/facebook/flow/blob/master/lib/react.js#L26

**Comment by SamChou19815** [comment]
The original issue doesn't provide enough info for debugging.
