### ISSUE TITLE
Linux 32 bits

### ISSUE THREAD

**Issue by Hibou57** [facebook/flow#2933]
As no binary is provided for Linux 32 bits, I tried to compile from source, but it fails with ex. “hh_shared.c requires a architecture that supports memfd_create”. Is this a 32 vs 64 bits platform issue?

More generally, is there a way to get Flow to work on a 32 bits machine?

**Comment by gabelevi** [comment]
No, probably not. The shared memory system relies on 64bit. It would be a significant rewrite to get it to work, and Flow often needs to address more memory than 32bit OSes can handle.

https://github.com/facebook/flow/issues/270 is the main issue for tracking this.
