### ISSUE TITLE
Buffer property not found in module buffer in nodejs

### ISSUE THREAD

**Issue by devmetal** [facebook/flow#2938]
Hi, i'm a first timer in flow. I started refactor my project with this library, and i stuck already. I don't know what i have to do with this error, i tried to search but not found any example or better explanation.

I have this lines:

```JavaScript
// @flow

const { Buffer } = require('buffer');
const { Transform, Readable } = require('stream');
```

And the flow output:

```bash
src/streambuffer.js:3
  3: const { Buffer } = require('buffer');
             ^^^^^^ property `Buffer`. Property not found in
  3: const { Buffer } = require('buffer');
                        ^^^^^^^^^^^^^^^^^ module `buffer`

```

But the Buffer class is the part of nodejs. What is the problem?

edited:
Here is my complete branch if it helps.
https://github.com/devmetal/laren/tree/dev

**Comment by aackerman** [comment]
`Buffer` is available as a global but the [module definition](https://github.com/facebook/flow/blob/2ca41919374e7a1f6377e33a90b8fa68c6a8a87e/lib/node.js#L119-L121) is incomplete in this case, you can work around this by using the global

**Comment by devmetal** [comment]
But how? I don't want to create a type for an existing type. Can i just ignore? Or configure flow to not try to load nodejs modules. I really don't get the point, why is so important to create a nodejs type declarations. I think in my case, is just enough to flow say Buffer is "any" class. Can i kick off the nodejs core modules from flow scope?

**Comment by aackerman** [comment]
Buffer is a global, don't require it, just use it.

**Comment by devmetal** [comment]
So evrything i need from nodejs, just use? If i want to use Transform class for extends like this:
class Xyz extends Transform {}

I dont need to require, just type Transform? And what is the difference of type and module importance?

**Comment by aackerman** [comment]
Just Buffer happens to be an available global, for backwards compat with
older versions of Node.

**Comment by devmetal** [comment]
Okay, and what is the difference of type import and module import?

I i write this:

```JavaScript
import type { Readable, Transform } from 'stream';
```

The flow output is this:

```bash
9: class StreamBuffer extends Transform {
                                ^^^^^^^^^ Transform. type referenced from value position
  5: import type { Readable, Transform } from 'stream';
                             ^^^^^^^^^ type Transform

```

But i also use the Readable type and the flow just accept with it. But if i use the commonjs require, this working well. So what is the difference, and when i have to use type import and when i have to use require?

**Comment by aackerman** [comment]
You need to import the type of type information and flow, but it doesn't
act as a value. Unless the value is coming from elsewhere you probably
don't need to add the type information and can get away with using the
value only

**Comment by devmetal** [comment]
Thank you for help. :)
