### ISSUE TITLE
"Required module not found" when main is pointing to a folder and not explicitly to index.js

### ISSUE THREAD

**Issue by ggarber** [facebook/flow#294]
If package.json is pointing to a folder: "main": "./lib" flow is not able to open the module.     If I replace it with "./lib/index.js" it works fine.

Passport is one example of popular node module where this is an issue

**Comment by samwgoldman** [comment]
I think this is the same issue as #278

**Comment by ggarber** [comment]
Thx, i couldn't find it.  Closing this one
