### ISSUE TITLE
Missing CSSStyleRule which extends CSSRule

### ISSUE THREAD

**Issue by kof** [facebook/flow#2943]
Initially I thought `CSSRule` declaration should have `style` property, but no actually we miss an entire class `CSSStyleRule` which inherits from `CSSRule` and implements `style` property.

https://github.com/facebook/flow/blob/master/lib/cssom.js#L42

**Comment by kof** [comment]
Oh, it also lacks `CSSStyleRuleList`, now I don't know if I should create separate issues for each missing declaration.

**Comment by kof** [comment]
Looks like there is no `CSSStyleRuleList`, there is CSSRuleList which is currently wrong, because it should have `item(index: number): ?CSSStyleRule` not `CSSRule`, at least in chrome.

**Comment by soleh23** [comment]
Experiencing the same issue, currently on flow-bin v0.81.0, but even after upgrade to v0.87.0 the error was occurring.
