### ISSUE TITLE
Definition of process.stdin.setRawMode is not respected

### ISSUE THREAD

**Issue by R1ZZU** [facebook/flow#2944]
With code below

```javascript
// @flow

if (process.stdin.isTTY) {
  process.stdin.setRawMode(true);
}
```

I got following error:

```
index.js:4
  4:   process.stdin.setRawMode(true);
                     ^^^^^^^^^^ property `setRawMode`. Property not found in
  4:   process.stdin.setRawMode(true);
       ^^^^^^^^^^^^^ stream$Readable
```

**Comment by R1ZZU** [comment]
Definition of `setRawMode` method is [present](https://github.com/facebook/flow/blob/master/lib/node.js#L1254) and `process.stdin` [definition](https://github.com/facebook/flow/blob/master/lib/node.js#L1590) is also there, but for some reason flow treats `stdin` as `stream$Readable`, not `tty$ReadStream`

**Comment by vkurchatkin** [comment]
@R1ZZU `process.stdin` is not always a tty stream, so this is actually correct. To make your example work we need to make `process.stdin` a union

**Comment by R1ZZU** [comment]
`process.stdin` is already a union:

```javascript
declare class Process extends events$EventEmitter {
    ...
    stdin : stream$Readable | tty$ReadStream;
    ...
}
```

Am I missing something?

**Comment by vkurchatkin** [comment]
No, it's just not enough to make refinement work, unfortunately

**Comment by R1ZZU** [comment]
I've found a workaround, but not sure if it safe enough... Any thoughts? 💭 

```javascript
declare class ReadableOrTTY extends stream$Readable mixins tty$ReadStream {};

declare class PatchedProcess {
	stdin: ReadableOrTTY
}

declare var process: Process & PatchedProcess;
```

**Comment by Spy-Seth** [comment]
I'm encountering the same issue. 

My workaround is (I only class `setRawMode` once in my applicaiton):

```js
if (process.stdin.setRawMode && typeof process.stdin.setRawMode === 'function') {
    process.stdin.setRawMode(true);
}
```

**Comment by vkurchatkin** [comment]
This is pretty much the same as:

```js
if (process.stdin.isTTY) {
  (process.stdin: any).setRawMode(true);
}
```
