### ISSUE TITLE
Declaring React instance variables

### ISSUE THREAD

**Issue by ide** [facebook/flow#296]
Hi guys - is there a way to declare a component's instance variables (this._somethingStoredOutsideOfState) when using the React.createClass syntax?

**Comment by zoltanmaric** [comment]
+1 I'd also like to know this

**Comment by kyldvs** [comment]
Something like this should work. But setting it's not completely a no-op at runtime since it will actually be adding the key `_subscriptionHandler` to the object before it's passed to createClass.

```
class SubscriptionHandler {
  release(): void {}
}

var Foo = React.createClass({

  _subscriptionHandler: (undefined: ?SubscriptionHandler),

  componentWillMount() {
    this._subscriptionHandler = new SubscriptionHandler();
  },

  componentWillUnmount() {
    if (this._subscriptionHandler) {
      this._subscriptionHandler.release();
    }
  },
});
```

**Comment by jeffmo** [comment]
Casting syntax FTW!

**Comment by ide** [comment]
OK thanks!
