### ISSUE TITLE
Import type doesn't work

### ISSUE THREAD

**Issue by abenhamdine** [facebook/flow#2960]
Hi guys, and thx for this fantastic work.

I'm running into the following problem : type import doesn't check anything.

Here is my code : 

in `fileB.js`
```js
"use strict";
//@flow

/*flow-include  
export type Body = {
        data: Object,
        version: string,
        dospay_id: number,
        entity: string,
        action: string
        };
 */
```

in `fileA.js`
```js
"use strict";

//@flow

/*flow-include
 import type {Body} from "../fileB.js";
*/

const foo = {

	processBody(body /*: Body*/ , callback /*: Function*/ ) {

		body.bar = 'foo'; // this property doesn't exist, flow should report error
		body.action = 5; // action is a string, flow should report error
		return callback();
	}
};

module.exports = foo;
```

I tried to use the inline syntax instead of comment syntax ; nothing change.

However, if i put the type definition in the same file as the code (fileB.js), everything run fine and flow reports the errors : 

![image](https://cloud.githubusercontent.com/assets/7466144/20943103/768ee626-bbfe-11e6-9b6c-eee4cc2ce74a.png)

I don't understand what I'm doing wrong.
Any ideas ?

Version : flow 0.36
Platform : Windows 64

**Comment by gcanti** [comment]
I can't reproduce

Version : flow 0.36
Platform : OSX

**Comment by abenhamdine** [comment]
Actually, with the code i provided, it works perfectly.
The pb should come from my particular code.
For the future reader : I don't know if it can be related, but in my code, I have circular dependencies (fileA require fileB, and fileB require fileA, not a the beggining of the file, but in a code block). 

I close this issues as it seems specific to my particular use case.
