### ISSUE TITLE
Invalid error "possibly undefined value" - Flow cannot follow a closure?

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/flow#2962]
In the example below I return a function from an IIFE which I use to set two variables inside the inner function using the outer function's closure. I think a flow analysis should get this, it's just a string value (and not some nasty object that could change) variable and a simple closure.

In line 13 below: there is guaranteed to be a cache entry for `personHash`, and this happens just before the closure is created. The inner variable `hash` is set to this value. Also: There is no other access to that cache anywhere in the code, so there is reason to suspect the key could be removed.

It's a feature request to get such cases covered, but I don't want to add too much code just to satisfy the type checker, and this one hurts me at least intellectually because I introduced the cache because right here speed matters, so adding code for no reason at all, only to make Flow happy, makes _me_ unhappy.. In other places I just added useless checks but here I think this could be solved by Flow.

```javascript
// @flow
'use strict';

type SHA256Hash = string;
type ReverseMapUpdateFnT = (hash: string, newKey: SHA256Hash, newValue: SHA256Hash) => void;

const personAndGrantCache: Map<SHA256Hash, SHA256Hash[]> = new Map();

const personHash: SHA256Hash = 'foo';
const grantHashesForPerson: SHA256Hash[] = ['bar', 'bla'];

// KEY LINE!!!
personAndGrantCache.set(personHash, grantHashesForPerson);

const cacheUpdateFn = (function (hash: string, cache: Map<SHA256Hash, SHA256Hash[]>): ReverseMapUpdateFnT {
    return function (newKey: SHA256Hash, newValue: SHA256Hash) {
        cache.set(hash, cache.get(hash).concat(newValue));
    };
})(personHash, personAndGrantCache);

// Notation as arrow function:
const cacheUpdateFnArrow =
    ((hash: SHA256Hash,
        cache: Map<SHA256Hash, SHA256Hash[]>): ReverseMapUpdateFnT =>
        (newKey: SHA256Hash, newValue: SHA256Hash) => {
            cache.set(hash, cache.get(hash).concat(newValue));
        })(personHash, personAndGrantCache);
```

Flow output:

```
lib/test.js:17
 17:         cache.set(hash, cache.get(hash).concat(newValue));
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `concat`. Method cannot be called on possibly undefined value
 17:         cache.set(hash, cache.get(hash).concat(newValue));
                             ^^^^^^^^^^^^^^^ undefined

lib/test.js:26
 26:             cache.set(hash, cache.get(hash).concat(newValue));
                                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `concat`. Method cannot be called on possibly undefined value
 26:             cache.set(hash, cache.get(hash).concat(newValue));
                                 ^^^^^^^^^^^^^^^ undefined


Found 2 errors
```

**Comment by gcanti** [comment]
> so adding code for no reason at all

`Map.get` has signature `get(key: K): V | void;` in order to be safe

**Comment by WhyEvenTry** [comment]
I know, but it is supposed to be a "flow" analysis - and in that code I DO set that hash. So the general possibility of `undefined` exists - but only if there is no flow analysis but a "stupid" single-line-by-line check without looking at the context.

**Comment by gcanti** [comment]
> how are we "being safe" considering an undefined result in this code?

```js
personAndGrantCache.delete('fo' + 'o')
cacheUpdateFn('a', 'b') // <= runtime error
```

**Comment by WhyEvenTry** [comment]
So where did you find the delete in the code? I don't see any.

**Comment by vkurchatkin** [comment]
Flow isn't magic: it can't understand every possible situation. `Map` is just an ordinary class for Flow. For example:

```js
map.set('foo', 'bar');
const x = map.get('foo');
```

You know that x should be `'bar'` because you know that's how `Map` works, but there is no way to encode this behaviour in terms of type system

**Comment by WhyEvenTry** [comment]
Your example is far more specific though: I'm not talking about concrete values!

**Comment by vkurchatkin** [comment]
@WhyEvenTry it doesn't really matter. Ok, we can say that you known that `x` is a string or is not `undefined`. But Flow doesn't know that

**Comment by WhyEvenTry** [comment]
Uhm... _shouldn't_ Flow know that? The variable that I assign has a (strict) type after all.

**Comment by vkurchatkin** [comment]
@WhyEvenTry yes, and it's type `string | void` in this case

**Comment by WhyEvenTry** [comment]
See above what I already wrote. I don't see why you see value in repeating comments I already responded to earlier? Turning in circles is useless.

**Comment by vkurchatkin** [comment]
@WhyEvenTry do you have a concrete proposal how to make this work?

**Comment by chicoxyzzy** [comment]
@WhyEvenTry actually having both TS and Flow is good for everyone

**Comment by WhyEvenTry** [comment]
@chicoxyzzy Especially third party lib support comes to mind that would gain a lot if there weren't two different type-checkers to support. And you have 883 tickets open right now and I'm sure a lot of Plans even without all those issues. Anyway, I won't say any more on it. Just my opinion, not important and OT.

@vkurchatkin Better (more detailed) flow analysis? :-)

**Comment by vkurchatkin** [comment]
@WhyEvenTry that's too vague. `Map` is declared here: https://github.com/facebook/flow/blob/master/lib/core.js#L535

How would you change this definition to support your use case?

**Comment by WhyEvenTry** [comment]
The definition is fine. There is no analysis of the code and variables. See what I wrote above, I won't reply any more to another attempt to turn in circles. Are you deliberately being childish? Rhetorical question.

**Comment by vkurchatkin** [comment]
@WhyEvenTry once again, it's the only thing Flow knows about `Map`.  So there are two options here:

 - hard code map semantics in Flow;
 -  add new features that allow to express this semantics in type declarations.

The seconds option seems preferable, as it allows to use this functionality with any type, no just hardcoded ones. 

So the question is, how this would look like?

**Comment by mroch** [comment]
> adding code for no reason at all, only to make Flow happy, makes me unhappy

This sounds like a good time to use [casting](https://flowtype.org/blog/2015/02/18/Typecasts.html#safety) to circumvent Flow.

```
((cache.get(hash): any): Array<SHA256Hash>).concat(...)
```

Since this is only an annotation, there won't be any runtime perf impact.

As far as Flow knowing that `map.get` should not return void when called with the same variable that was previously passed to `map.set`, that would surely be nice to have and sounds like dependent types. closing this in favor of https://github.com/facebook/flow/issues/2924.
