### ISSUE TITLE
Interface / Class Relationship Issue: Class <: Interface?

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2963]
Not sure if this is a bug or a misunderstanding of implementation...

**Interfaces**
https://flowtype.org/docs/syntax.html#interface-declarations
> Declaring an interface creates a type that multiple classes can satisfy without being part of the same inheritance hierarchy.

Should the inverse be true?
...an interface that satisfies a class?

````javascript
/* @flow */

// Declaration File
declare interface Foo {
  foo: string;
}

declare function theirFunc<T>(): Foo

// myFile.js
class Bar {
  foo: string
}

function myFunc(): Bar {
	return theirFunc()
}
````
````javascript
16: 	return theirFunc()
            ^ Foo. This type is incompatible with
15: function myFunc(): Bar {
                       ^ Bar
````

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCIFMDGMAhgE5EAuAlnAHZgBilMuqAJgcSbmJTebiShF83enDhgA3qjBgo4gFxgAzuRK8A5gG5UAX3TtCpblACuNfFVphyAC1yUS9c-gA8AFQB8ACgCUSsTh0TDAAWwBPRmYAOgArZVQjZWUwACFSKRk5RRU1TT10MwsrOgjnCz8ldJJMgEguclMSOjsHJxc-PSA

**Comment by gcanti** [comment]
The type `Foo` is structural, the type `Bar` is nominal

**Comment by mwalkerwells** [comment]
Simply put—thanks!
