### ISSUE TITLE
Objects having `$call` property are considered callable

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#2966]
Example:

```js
const x = {
  $call: () => {}
};

x();
```

I guess it's a known issue, but could be surprising for someone

**Comment by samwgoldman** [comment]
Yeah, the `$call` hack needs to be replaced with something better. Instances have a similar hack with `$key` and `$value` properties :/. I have some WIP to remove these special names, which I'm hoping to wrap up in the near term.

**Comment by mroch** [comment]
I've got several things in progress where we start including $call in errors, which is obviously not good. for example, one thing I'm working on would says something like "Property `$call` is incompatible" if one callable object flows into another with a different signature.

**Comment by TrySound** [comment]
Seems like fixed
https://flow.org/try/#0MYewdgzgLgBAHjAvDA3gKBjAJMAhgG3wC4YAKASiQD5UBfNWgbjTTgsaA
