### ISSUE TITLE
Support parsing dynamic import() syntax

### ISSUE THREAD

**Issue by bradencanderson** [facebook/flow#2968]
Now that [dynamic import](https://github.com/tc39/proposal-dynamic-import) is stage 3 and Webpack 2 will support it for code splitting ([link](https://github.com/webpack/webpack/issues/3098)), flow-parser should correctly parse its syntax.

There's a [PR](https://github.com/estree/estree/pull/137) to ESTree to specify this new syntax.

**Comment by kylpo** [comment]
Hi folks, Webpack2 is out now 🎉 ! Would really appreciate Flowtype not throwing `Unexpected token import` errors when using dynamic imports.

I've tried to add my own `import` declartion with
```js
declare function import(module: string): Promise<Object>
```
, but Flow errors with `Unexpected token import` on this line as well.

**Comment by jaredpalmer** [comment]
The PR to ESTree was merged 16 days ago. Whats the status of this?

**Comment by jeffmo** [comment]
I don't think anyone has picked this up yet. Happy to review PRs to do so!

**Comment by deecewan** [comment]
@jeffmo I'm mostly just throwing shit at walls with this PR. Any chance you can point me in the right direction?
