### ISSUE TITLE
Flow incorrectly reports type incompatibility after undefined check when using Array.map

### ISSUE THREAD

**Issue by AaronKalair** [facebook/flow#2979]
This code:

```
// @flow
function func1(a?: string[], b?: string ) {

    if (a === undefined || b === undefined) {
        return;
    }
    a.map(item => func2(item, b));
}

function func2(a: string, b: string ) {
    console.log(a);
    console.log(b);
}

console.log(func1(['a'], 'b' ));
```

Produces these errors:

```
test.js:7
  7:     a.map(item => func2(item, b));
                                   ^ undefined. This type is incompatible with the expected param type of
 10: function func2(a: string, b: string ) {
                                  ^^^^^^ string
```

If you strip the type annotations and run it the code runs fine console logging 'a' and 'b' as expected.

Without the

```a.map(item => func2(item, b));``` part Flow is also fine with it

```
// @flow
function func1(a?: string[], b?: string ) {
    if (a === undefined || b === undefined) {
        return;
    }
    func2(a[0], b);
}

function func2(a: string, b: string ) {
    console.log(a);
    console.log(b);
}

console.log(func1(['a'], 'b' ));
```

**Comment by AugustinLF** [comment]
This is normal, flow is pessimistic about refinements, it considers that func2 could modify b.

See #2895 for instance. As for a fix, you can [redeclare b as a constant](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaKpgIwAUAhgPwBcoAzlgE45oDmA2gLoA0oARjXpMWrUAEpQAb0SJQc0DkigKoALzrQ6ACYBTSCx1bQAH2P81G7XoNaJ0+Q9CMdWFIzQBuWfIC+3uRj4DAp8avxeDuQAdAC25AAOpDhYOjFqAHyE6BgATEkpMbw4fGJiXn7I2bj4WZh55LQMzGy8fI3CbOJS-qCBaHSw0DpRcKwUZT19A0MjsGMl5TJTg8OjpEQYZOwA5OTbPKDbfNviZUA)

You can also do as said by gcanti https://github.com/facebook/flow/issues/2877#issuecomment-262390960
> Another way to fix the error is to set the experimental.const_params=true option in the [options] section of .flowconfig
