### ISSUE TITLE
Add a configuration that would make all functions of set arity by default

### ISSUE THREAD

**Issue by gajus** [facebook/flow#2980]
Flow documentation suggests that to make a function accept a set number of parameters, one must annotate it with `...Array<void>`, e.g.

```js
* @flow */
// The first overload matches 0 args, the second matches 1 arg, the third
// matches 2 args
declare function foo(...rest: Array<void>): string;
declare function foo(a: number, ...rest: Array<void>): string;
declare function foo(a: number, b: number, ...rest: Array<void>): string;
```

From: https://flowtype.org/docs/functions.html#too-many-arguments

The problem is that if you want to enforce all functions to be of set arity, you need to repeat this pattern across all function declarations, which introduces awfully a lot of code duplication.

Most of the issues that I have run into that are not caught by Flow are because of variadic functions. Therefore, I'd prefer all my functions to be interpret as of set arity by default.

**Comment by vkurchatkin** [comment]
> Most of the issues that I have run into that are not caught by Flow are because of variadic functions

Can you give an example of such an issue?

**Comment by gajus** [comment]
> Can you give an example of such an issue?

Most often simply overlooking to refactor a factor of code, e.g.

My `Plugin` class constructor changed from:

```js
constructor (name: string, getTagsPromise: Promise<TaggingPluginGetTagsType> | TaggingPluginGetTagsType, configuration: PluginConfigurationType) {
```

to

```js
constructor (name: string, getTagsPromise: Promise<TaggingPluginGetTagsType> | TaggingPluginGetTagsType) {
```

as part of refactoring.

However, there remained few instance of code that continue to initialise `Plugin` using `configuration` as the third parameter, e.g.

```js
pluginManager.addPlugin(new Plugin(plugin.name, plugins[plugin.name], plugin.configuration));
```

While this directly does not break the application, it creates an "appendix".

**Comment by vkurchatkin** [comment]
@gajus so, to be fair, this is more of a stylistic issue?

**Comment by gajus** [comment]
> @gajus so, to be fair, this is more of a stylistic issue?

I wouldn't go as far as to say that it is a stylistic issue.

What if another refactor of the same codebase happens and a third-parameter is re-introduced with a different purpose. If you are lucky, type check will raise an error about shape mismatch. However, if it is a primitive type, you are up for a fun debugging time.

**Comment by vkurchatkin** [comment]
> However, if it is a primitive type, you are up for a fun debugging time.

This is a possibility anyways unless you use nominal types

**Comment by gajus** [comment]
https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/ 🥇
