### ISSUE TITLE
How to check if value is in enum (union of string values)?

### ISSUE THREAD

**Issue by gajus** [facebook/flow#2982]
```js
// @flow

type countryCodeType = 'gb' | 'us';

const countryCodes = [
  'gb',
  'us'
];

const getSiteCountryCode0 = (userInput: string): countryCodeType => {
  const countryCodeIndex = countryCodes.indexOf(userInput);
  
  if (countryCodeIndex === -1) {
  	throw new Error('Unexpected country code.');
  }
  
  return countryCodes[countryCodeIndex];
};

const getSiteCountryCode1 = (userInput: string): countryCodeType => {
  if (!countryCodes.includes(userInput)) {
    throw new Error('Unexpected country code.');
  }
  
  return userInput;
};

```

I cannot figure out how to make the above work:

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AY1gK4B2KATmgMKwAmWAKpjgLygDkA5gEaugA+bBAM6sA3MnxFBKPIRLkqtQaBYBtRKDZdWAGnUDhiALpjEEqaHZYUAZQCWKLFWJlKNLAAZloABRCspAEkiDAIUAC5QKVJbInYASgj8Z3k3BmxlAD5QAG89M2kkuVdaINoADy9ClwUsQQA6GPKAeUhfQX8gkJQ4sQ09W0gfKpSSonLlJhYAWgBGOJy9AEgUAAtSBFAiLHhQAFFSddJvVgBVLbLsXAdqGWS0GVo61h69AF89PVIrAlIiW6KaoIVMNilhSlgysZEK8TPkLFY7A4nAC3DMvG0OsFQhEojF4olZNVUoxMgsNAMfABCEGAhpEXDQAiKDGBLHdea5DQaVbrHZbHb7Q7HM4Qy7Xf4uB5YJ4vDTvPoaL4oH5-PysrpiGHIIA

**Comment by gajus** [comment]
I realised `countryCodes` is missing `Array<string>` cast. However, even casting it to `Array<string>` it does not work as expect:

```
// @flow

type countryCodeType = 'gb' | 'us';

const countryCodes: Array<string> = [
  'gb',
  'us'
];

const getSiteCountryCode1 = (userInput: string): countryCodeType => {
  if (!countryCodes.includes(userInput)) {
    throw new Error('Unexpected country code.');
  }
  
  return userInput;
};

```

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AY1gK4B2KATmgMKwAmWAKpjgLygDkA5gEaugA+bBAM6sA3MnxFBKPIRLkqtQQC5QAQVKkAhmgA8U0gEsi7AHygWAbUSg2XVgBprA4YgC6YxBKmh2WFAGUDFCwqYjJKGiwARnNQAAohLFIASSIMAhQVfSN2AEoVfDD5SIZsczMAbycDSHiAQkK5CMUAOiNcaAJFBMEk1PSUXNzQKpsbFAALUgRQIix4UABRDVhSONYAVTmAD2xcYOoZIrQZWhbWXLEbAF8nJ1I-AlIiUESUtIyxa48gA

**Comment by gajus** [comment]
I have also tried:

```js
const countryCodes: Array<countryCodeType > = [
  'gb',
  'us'
];
```

but that produces different set of errors.

**Comment by gcanti** [comment]
Using `find`?

```js
// @flow

type countryCodeType = 'gb' | 'us';

const countryCodes: Array<countryCodeType> = [
  'gb',
  'us'
];

const getSiteCountryCode = (userInput: string): countryCodeType => {
  const maybe = countryCodes.find(v => v === userInput)  
  if (!maybe) {
    throw new Error('Unexpected country code.');
  }
  return maybe;
};
```

[try](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AY1gK4B2KATmgMKwAmWAKpjgLygDkA5gEaugA+bBAM6sA3MnxFBKPIRLkqtQQC5QAQVKkAhmgA8+YmUo16jAHygWAbUSg2XVgBobA4YgC6YxBKmh2WFADKAJYoWFQG8sYWoAAUQlikAJJEGAQoKlKkQUTsAJQq+nJGtAzYFuYA3s7e0gC22pzMMhHFWIIAdJDZ1DEAbuWg-UzDoPFJKWm5ts5BkLEAhPVojVNVtgCQKAAWpAigRFjwoACiGrCkMawAqgcAHti4odTNRTK07ay5YrYAvs6k-gIpCIoCWjTEP08iCAA)

**Comment by gajus** [comment]
Thank you @gcanti.

**Comment by CodyReichert** [comment]
So just for clarification, why _doesn't_ `indexOf` or `includes` work in this case? I would kind of expect the behavior to be the same in all three cases.
