### ISSUE TITLE
Flow does not recognize an anti-undefined "if" when the variable is inside a function (synchronous)

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/flow#2984]
Flow 0.36.0

Code:

```javascript
// @flow
'use strict';

const imap: {search(criteria: Array<*>, cb: Function): void} = {
    search: (criteria, cb) => {}
};

// I also tried
//const search = (from: ?number, to: ?number): Promise<number[]> => {

const search = (from?: number, to?: number): Promise<number[]> => {
    return new Promise((resolve, reject) => {
        imap.search(
            ['ALL'],
            (err: Error, uids: number[]) => {
                if (err) {
                    reject(err);
                } else {

                    // HERE IT WORKS
                    if (from) {
                        const test: boolean = uids[0] >= from;
                    }

                    // HERE IT DOESN'T WORK
                    if (from) {
                        uids = uids.filter((uid: number) => uid >= from);
                    }

                    // HERE IT DOESN'T WORK
                    if (from) {
                        uids = uids.filter(function (uid: number) {
                            return uid >= from;
                        });
                    }

                    resolve(uids);
                }
            }
        );
    });
};
```

Flow output:

```
$ flow status
lib/test.js:27
 27:                         uids = uids.filter((uid: number) => uid >= from);
                                                                        ^^^^ undefined. This type cannot be compared to
 27:                         uids = uids.filter((uid: number) => uid >= from);
                                                                 ^^^ number

lib/test.js:33
 33:                             return uid >= from;
                                               ^^^^ undefined. This type cannot be compared to
 33:                             return uid >= from;
                                        ^^^ number

Found 2 errors
```

Flow doesn't complain in the first example where the comparison is not inside a function.

Flow does not complain if I remove the entire asynchronous Promise stuff around it all, but 
a) that should not make any difference, the  guarding `if (from)` is inside the synchronous part, and
b) it doesn't complain in the first of the three tests.

I also tried adding `&& typeof from === 'number'` to the if condition, no change.

**Comment by gcazaciuc** [comment]
Seems like exactly the same problem and fix as in https://github.com/facebook/flow/issues/2979

**Comment by mroch** [comment]
yep, same problem. see also https://flowtype.org/docs/dynamic-type-tests.html#caveats

**Comment by WhyEvenTry** [comment]
Why do you point me to the caveats? They don't apply here! Did you _look_ at my example?

**Comment by mroch** [comment]
```
                    // HERE IT WORKS
                    if (from) {
                        const test: boolean = uids[0] >= from;
                    }

                    // HERE IT DOESN'T WORK
                    if (from) {
                        uids = uids.filter((uid: number) => uid >= from);
                    }
```

in the first case, there is no closure so the `from` refinement still exists. in the second example, `from` is accessed in a closure, `(uid: number) => uid >= from`. Flow is not aware that `Array.prototype.filter` runs the closure synchronously, and so is pessimistic about whether `from` is still truthy by the time the callback runs.

**Comment by WhyEvenTry** [comment]
Sounds like a bug to me not a missing feature - I'm talking from the perspective that array iteration using callbacks instead of `for` loops is something more than just normal in today's Javascript. Just sayin.

**Comment by gcazaciuc** [comment]
i kind of agree that this level of soundness might be counterintuitive and hinder  the development flow in most situations.  i would personally prefer a less sound approach in some cases if  that makes dev more productive.

**Comment by gabelevi** [comment]
> Why do you point me to the caveats? I don't see how they apply here. Did you look at my example? I read the caveats multiple times and am aware of them. Just asking about that particular part, not about the "duplicate" - if it's already been reported, good.

@WhyEvenTry - you have good points to make. Please don't hide them with rudeness. If you don't understand how an answer helps, just say that you don't understand and ask for clarification. If you think the person answering has misunderstood, just explain what you think the misunderstanding is and clarify your question.

> i kind of agree that this level of soundness might be counterintuitive and hinder the development flow in most situations. i would personally prefer a less sound approach in some cases if that makes dev more productive.

@gcazaciuc - You're right, sometimes it is worth sacrificing some correctness checks to make the dev's life easier. In this case, I think special casing a bunch of common array functions might solve almost all the complaints. Technically someone could replace `Array.prototype.map` with something else, but that might not be worth worrying about.

**Comment by WhyEvenTry** [comment]
I really wanted to shut up because I appreciate the project and the HUGE amount of work the devs put in. I don't mind AT ALL not getting my way and solutions to my filed issues. But I wold like to have _good_ reasons. I don't see how this is "sound". In this specific example there is not just no way on earth for that value to ever be compromised, so the reason it doesn't work does _not_ lie in the code but in the tool. I don't mind setting a type to "any" to turn off the check if the tool can't handle it, but I don't want to be told the code is the problem. Adding workarounds (other than the NOOP "any" type that doesn't cost me anything) so that Flow doesn't complain does not make the code one iota more sound, quite the opposite, now I have superfluous code (if I used those workarounds).

By the way, for comparison, Flow still is doing well compared to the competition: TypeScript (2.1, latest, with `"strictNullChecks": true`) doesn't complain _at all_ even when I remove all three guarding `if (from)` statements.... the only complaint I managed to get out of "tsc", and I configured it to be as strict as possible, was about "unused constant `test`".

**Comment by gabelevi** [comment]
That's a fair question. The short answer is that Flow is not as smart as a human. It only knows as much as we teach it, but there are still gaps. We're working on making Flow smarter and filling in the gaps.

In the meantime, what do we do about these gaps? Do we tell Flow to be pessimistic, and warn the user that their code might be incorrect? Or do we tell Flow to be optimistic and trust the user's code is correct? Sometimes we're pessimistic (like with refinements) and sometimes we're optimistic (like with array access, we don't do bound checking or check for array holes). It's a balancing act and feedback like these issues help us rebalance.

How do we as humans know your original code example is safe? Well, for one, `from` is never modified. Because of this, once we know it is not `undefined`, we never need to worry about it being `undefined` again. We have not taught Flow this principle yet, but we plan to. Basically, we would like to notice when mutable variables (function parameters, vars & lets) are never again modified, and treat them like `const`'s from then on. When you refine a `const`, nothing you do can invalidate that refinement, since we know that `const`'s can never change!

**Comment by mroch** [comment]
I don't think anybody suggested your code was the problem.

some things are easier to statically analyze, like `const`. using `const` is a workaround that allows flow to guarantee that nobody mutated the `from` binding. any VM should also inline an assignment like `const from_ = from;` so there's no runtime cost to this workaround either (maybe an extra 2 or 3 bytes post-minification and gzip?). the only other downside I can see is that it makes the code uglier, but so does casting to `any`.

the other suggested workaround, turning on const params in Flow, wouldn't require you to change your code at all, assuming you don't intentionally mutate params elsewhere.
