### ISSUE TITLE
Extending object types using mixins 

### ISSUE THREAD

**Issue by dendril** [facebook/flow#2985]
is it possible to define:

```
type X = {
   prop: string
}
```

and: 

```
type Y extends X = {
  anotherProp: string
}
```

The expected result should be:

```
type Y = {
  prop: string,
  anotherProp: string
}
```

Any idea if I can do this? I been checking flow has support for "utils", maybe a $merge could do the magic.

Thanks!

**Comment by gcazaciuc** [comment]
what about type y = x & {  anotherProp: string  }  ?

**Comment by dendril** [comment]
It works like a cham. Where is the semantics of this operator defined?

**Comment by CodyReichert** [comment]
@dendril - I believe you're looking for Intersection types here: https://flowtype.org/docs/union-intersection-types.html

**Comment by dendril** [comment]
thanks guys! I guess **Intersection** is not the best name in this case lol.
