### ISSUE TITLE
BUG: truthyness test of nullable arg doesn't carry over into closure

### ISSUE THREAD

**Issue by jaredly** [facebook/flow#2986]
```js
const fn = (Y: ?() => void) => Y && setTimeout(() => Y(), 10)
                                                     ^--
```
this code gives me an error saying `Y` might be null or undefined -- when in fact, there's no way it could be.

Another example of this bug:
```js
const x = (n: number) => 10
const fn2 = (Y: ?number) => Y && (() => x(Y))
````
It again things that Y might somehow be null/undefined inside the closure.

**Comment by gcanti** [comment]
Flow is pessimistic about refinements, it considers that every function call could modify `Y`. As for a fix, you can use a `const` [binding](https://flowtype.org/docs/dynamic-type-tests.html#caveats)

```js
const fn = (Y: ?() => void) => {
  const f = Y
  f && setTimeout(() => f(), 10)
}
```

Related

- https://github.com/facebook/flow/issues/2940
- https://github.com/facebook/flow/issues/2895
- https://github.com/facebook/flow/issues/2877
- https://github.com/facebook/flow/issues/2836
- https://github.com/facebook/flow/issues/2831
- https://github.com/facebook/flow/issues/2768
- https://github.com/facebook/flow/issues/2704
- https://github.com/facebook/flow/issues/2693
- https://github.com/facebook/flow/issues/2602
- https://github.com/facebook/flow/issues/2513
- https://github.com/facebook/flow/issues/2318

**Comment by jaredly** [comment]
I get being cautious w/ object members, but in this case flow should be able to trivially determine that nothing can modify Y

**Comment by tnguyen14** [comment]
Any update on this issue? Will it be fixed soon?
