### ISSUE TITLE
Treat bracket property access with string literals the same as dot property access

### ISSUE THREAD

**Issue by davidswinegar** [facebook/flow#2990]
I use objects with properties that are not valid identifiers in several places in my code. When I use bracket property accessors, I don't seem to be able to type-check the same way as I can with valid javascript property names. Here is an example with unions using both exact object types and tagged unions.

```js
/* @flow */
type exactObjectType = {|
  'a.b': {};
|} | {|
  'a.c': string;
|};

type disjoint = {
  'tag.tag': 'first';
  'a.b': {};
} | {
  'tag.tag': 'second';
  'a.c': string;
};

const testDisjoint = (param: disjoint): string => {
  if (param['tag.tag'] === 'second') {
    return param['a.c'];
  }
  return '';
}

const testFunction = (param: exactObjectType): string => {
  if (param['a.c'] != null) {
    return param['a.c'];
  }

  return '';
};
```

The above examples work if I replace all invalid identifiers with valid ones and instead use dot property access. Are there plans to treat bracket property accesors with string literals the same as dot notation?

**Comment by mroch** [comment]
yeah, I think we should do this. flow specially handles certain syntax trees (in this case, an `EqualityExpression` with a `MemberExpression.IdentifierName` on one side) and I think it's just an oversight that it doesn't handle `MemberExpression[Literal]`.

**Comment by goodmind** [comment]
Actually https://github.com/facebook/flow/pull/7597 doesn't fix this concrete example of `!= null` refinement because it works with `TestPropT` internally (not special cased like other refinements) and there isn't `TestElemT`

**Comment by gkz** [comment]
Example in issue now passes.
