### ISSUE TITLE
Flow thinks that a function is a map type as long as the function type is the same as the value type of the map

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#2991]
I would not think that this should type check, but it does, because flow sees `() => 3` as the value of the `$call` property.

```js
type Example = () => number
const x: { [key: string]: Example } = () => 3
```

https://flowtype.org/try/#0C4TwDgpgBAogHgQwLZgDbQLxQBQEooYB8UAdgK5IBGEATgFADGA9iQM7BRwBcUA3lAG0A1hBA92NAJYkA5gF0e8ZGmgBfAjnxEoAZjpA

This is a refinement of #2543

**Comment by vkurchatkin** [comment]
Let's just merge this into https://github.com/facebook/flow/issues/2966
