### ISSUE TITLE
Flow gets stuck on initialization

### ISSUE THREAD

**Issue by jasonkuhrt** [facebook/flow#2995]
Hi,

When I start flow it seems to get stuck on this:
```
❯ flow status
flow is still initializing; this can take some time. [local inference] \
```

My fans were blaring at one point. Similarly `flow check` never completes.

Version:

```
Flow, a static type checker for JavaScript, version 0.36.0
```

**Comment by CodyReichert** [comment]
What does your `.flowconfig` and directory structure look like?

**Comment by jasonkuhrt** [comment]
```
~/projects/scratching/currying
❯ k
total 144
-rw-r--r--   1 jason.kuhrt 1718724809    48 26 Nov   21:59   .flowconfig
-rw-r--r--   1 jason.kuhrt 1718724809   404 10 Dec   21:20   main.js
drwxr-xr-x 250 jason.kuhrt 1718724809  8500 10 Dec   19:58   node_modules
-rw-r--r--   1 jason.kuhrt 1718724809   599 10 Dec   19:58   package.json
-rw-r--r--   1 jason.kuhrt 1718724809 59723 10 Dec   19:58   yarn.lock

~/projects/scratching/currying
❯ ccat .flowconfig
[ignore]

[include]

[libs]

[options]
all=true
```

**Comment by CodyReichert** [comment]
Maybe one of the maintainers can chime in with some better tips, but have you tried ignoring `node_modules` in the `.flowconfig`?

```
[ignore]
.*node_modules/fbjs.*
```

Maybe try that just to see where it gets you.

Also, is everything in your `main.js` commented out? I'm not sure if it would have an effect, but maybe try uncomment the `add` function?

**Comment by jasonkuhrt** [comment]
@CodyReichert You correctly identified the problem:

> Maybe one of the maintainers can chime in with some better tips, but have you tried ignoring node_modules in the .flowconfig?

Thanks! This happened because I started playing with flow in a directory with just one plain JS file, but then did `yarn init`, added deps, etc. and suddenly had a ton of files causing `flow` to choke.
