### ISSUE TITLE
Proposal: types zero values

### ISSUE THREAD

**Issue by oelmekki** [facebook/flow#2997]
Hi guys,

I've been moving a codebase to flow this week, it's very cool. Thanks!

Coming from golang, what I miss the most is zero values on type initialization. In go, you can do something like this:

```go
type Foo struct {
  Id int
  Name string
  Description string
}

foo := Foo{ Id: 1 }
FindFooById( &foo ) // will fill Name and Description
```

The reason why this works is that, when initializing a type, go will fill unspecified fields in type with their zero value. So, an integer is initialized at `0`, a string is initialized at `""`, etc. This is very convenient because this prevents from having to specify tons of values when we just don't care yet about them.

With flow, I need to do this:

```js
type Foo = {
  id: number,
  name: string,
  description: string
};

let foo : Foo = { id: 1, name: '', description: '' };
findFooById( foo );
```

Which is still ok here, but won't be with a type having like 10 fields.

Of course, we could mark the fields as optional:

```js
type Foo = {
  id: number,
  name?: string
  description?: string
};
```

But now, if have to add checks everywhere in my code to verify if indeed those fields are present, even if they are always present past very first step initialization. Also, if I want a `findFooByName()` methods, now all my fields must be optional.

Of course, this is just one example and we can easily find workarounds for it, like for example having a `findFooById( id : number ) : Foo` instead of `findFooById( foo : Foo )`. But I found myself quite often declaring lot of zero values while initializing my types, so I think having a mean to initialize types zero values would globally makes sense, avoiding that way to have to write one or several factory functions for every single type. 

By the way, if this is too much of a design change, having a generic zero value initializer function would be fine too:

```js
type Foo = {
  id : number,
  name : string
};

foo = FlowInit( Foo ); // => { id: 0, name: "" }
```

Is it something you considered? If yes, what were the reasons to not go this way? Is there a "flow way" which make this initialization problem actually non existent?

Thanks!

**Comment by vkurchatkin** [comment]
This is bit out of scope. Flow is a type checker, it has no way to affect what happens at runtime.
So you can't do it "the Flow way", you have to do it "the JS way":

```js
type Foo = {
  id: number,
  name: string,
  description: string
};

const FooInit = {
  id: 0,
  name: '',
  description: ''
};

let foo: Foo = { ...FooInit, id: 123 };
```

**Comment by oelmekki** [comment]
I didn't thought about using splats ; indeed, it helps.

This is not ideal because you now need twice as much code to declare a type, and you need twice import lines:

```js
import type { Foo } from "./types";
import { FooInit } from "./types";
```

But this is still better than initializing all fields explicitly. Thanks!

**Comment by oelmekki** [comment]
In case the fact that it's a runtime thing is the only problem, here's an idea to work around it: taking advantage of the babel transformation to fill missing fields during transpiling.

We don't need runtime code, actually. What we need is the transpiler to notice that in:

```js
type Foo = { id: number, name: string };
foo : Foo = { id: 1 };
```

... there's a `name : string` field missing, and transpile it to:

```js
var foo = { id: 1, name: "" };
```
