### ISSUE TITLE
Rest Parameter: Allow Bounded Array Type (Feature Request)

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#2999]
Marking as feature request (unless I'm misunderstanding this), but this would be really helpful... 😃

````javascript
const test = <A: Array<*>, B>(func: (...args: A) => B, ...args: A): B => {
    return func.apply(null, args)
}
````
````javascript
3: const test = <A: Array<*>, B>(func: (...args: A) => B, ...args: A): B => {
                                                 ^ A. rest parameter should have an explicit array type (or type `any`)
3: const test = <A: Array<*>, B>(func: (...args: A) => B, ...args: A): B => {
                                                                   ^ A. rest parameter should have an explicit array type (or type `any`)
````

[Flow.org | Try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzHwFMCwBeMAHgEEAuMGgJyYEMBPKkAPgBowAQtwAUUAK7YMDYQDo5rJgHNcDGgEoK3QfzkyFy1WoYDNYAN6owVsE2L4xTbGHGS9ABzcx2w7GJgx+fVw1VABfIA)

**Comment by avikchaudhuri** [comment]
This is a known issue with Flow's implementation of rest params (at least).

**Comment by philippotto** [comment]
Is this issue resolved or why was it closed? Or is there another issue covering this?
