### ISSUE TITLE
Type annotations in comments?

### ISSUE THREAD

**Issue by mhart** [facebook/flow#3]
Didn't see support for this in the documentation, but it would be great if Flow supported type annotations in comments (or similar) – with the aim of allowing everything to be written in pure JavaScript.

This would allow people to keep the same tools they currently use, and skip the transpilation step.

Has this idea been floated at all? Is it doable?

*Edit:*
[Looks like this is doable](https://github.com/facebook/flow/blob/master/tests/docblock/docblock.js) – perhaps the documentation just needs to be updated to expound on this?
*Edit again:*
OK, so atm it's just conversion from docblock to flow – would be great if it could be done in-place... or something

**Comment by CrabDude** [comment]
+1

This would allow compatibility with ES6 transpiled projects (e.g., traceur). Flowtype isn't yet a drop-in replacement for an ES6 transpiler since it's ES6 support is limited.

**Comment by misterspeaker** [comment]
+1 for me too. Is anyone actually working on this? I don't want an "almost-js -> real js" transpile step in my personal projects, so I'd be keen to follow along/help out.

**Comment by jareware** [comment]
For @misterspeaker et al, I put together https://github.com/jareware/flotate for just this purpose. That is, using Flow with standard JavaScript syntax.

**Comment by mhart** [comment]
@jareware Just had a browse of the docs, looks great! I guess it was probably easier to come up with a new syntax rather than try and support JSDoc et al from the get go?

I look forward to trying this out – and hopefully soon we'll be able to check code without the compile/temp-dir step!

**Comment by jareware** [comment]
@mhart yeah, I gave up on JSDoc pretty quickly after realizing how hard it'd be to match up all params with their types, how much repetition that'd introduce, and that (as @Raynos pointed out above as well) it still wouldn't cover e.g. overloaded function signatures well.

By using the exact same positions as Flow does, and reserving a prefix for the comments (`/*:`) the conversion is actually dead-simple, as you don't have to care about where the annotations are encountered, you just strip the surrounding `/*` and `*/` and you're done. :)

I'm hoping something along these lines eventually ends up in Flow itself, at which point the preprocessor obviously becomes unnecessary!

**Comment by Deathspike** [comment]
+1 as it would avoid new non-JavaScript syntax and flow through existing annotated libraries. Arguments have been raised that not every case is covered in JSDoc, and while that is true, it would make flow useful for projects without build steps and using regular JS (e.g. almost *all* node libraries out there).

**Comment by yonkeltron** [comment]
+1 for this feature. Any of the proposed syntax options would immediately speed my adoption of flow since it is unreasonable for my team to convert existing projects to typed JS right now.

**Comment by eternalko** [comment]
Flotate one-line-syntax looks like a much more prefereble solution.
It will not break established workflows, testing routines, IDE support, existing code etc.

Also, it look like it will be easier to integrate flow with things like coffeescript.

**Comment by jareware** [comment]
With regard to the discussion above, while [flotate](https://github.com/jareware/flotate) doesn't (yet) support full-blown JSDoc, there's now also an alternative syntax for functions/methods, so that in addition to:
```js
function foo(x /*: string */, y /*: number */) /*: boolean */ {
    return x.length * y === 5;
}
```
the following is also supported:
```js
/*: (x: string, y: number): boolean */
function foo(x, y) {
    return x.length * y === 5;
}
```
which is nice in keeping the annotations & code separate.

**Comment by benjamine** [comment]
@jareware that's neat! much better readability

**Comment by yonkeltron** [comment]
@jareware Thanks so much for telling us about flotate! I can't wait to use it. As the primary author, do you think that flotate provides evidence that type annotations in comments constitutes a viable method of expressing type information? Seeing as how you went ahead and wrote your own tool, do you think flow proper should support type annotations in comments?

**Comment by jareware** [comment]
@yonkeltron Definitely viable! I guess the question is more about whether *type checking for JavaScript* is useful or not. I think it is, and that Flow is currently the best too for the job. flotate just bridges the small syntactic gap to standard JS. For instance, I'm currently gradually adding type information to an existing project using these tools, and have found them helpful!

As to the second question, I think that's something they're considering, and I'd be glad to have the preprocessor become unnecessary. :)

**Comment by gabelevi** [comment]
Ok, you guys convinced us! We've merged @jareware's awesome [flotate](https://github.com/jareware/flotate) syntax upstream, directly into Flow! [Here's a blog post about it](http://flowtype.org/blog/2015/02/20/Flow-Comments.html) and we'll write proper documentation after we've caught up on sleep :)

**Comment by mhart** [comment]
Yessss, excellent news!

**Comment by mhart** [comment]
Going to close this – if anyone's got issues with the syntax or anything else they can open up separate issues.

**Comment by jareware** [comment]
This is brilliant! :bow:

**Comment by QuantumInformation** [comment]
Good job!

**Comment by ngduc** [comment]
flotate looks great! Please support JSDoc syntax also. Thanks.

**Comment by kamek-pf** [comment]
JSDoc would be nice indeed.
What's the status on this ? Is it going to happen at all ?

**Comment by metrofun** [comment]
+1
JSDoc is would be the right direction for increased interoperability of Flow. Having one more magic syntax for types is quite obtrusive. Right now JSDoc is a clear advantage of Closure Compiler when it comes to type checking.

**Comment by QuantumInformation** [comment]
Any update on jsdoc being wired to flow?

**Comment by ngduc** [comment]
Does flow support flotate one line syntax yet? I haven't found an example online:
```
/* @flow */
/*: (x: string, y: number): boolean */
function foo(x, y) {}
```

**Comment by jareware** [comment]
@ngduc, I don't think it was ever slated for inclusion. And to be fair, while personally I find that one-line syntax very convenient, it's quite different from the standard Flow syntax, and actually isn't as widely applicable as the standard one.

If the team *were* to consider the addition of completely new syntaxes, I'm guessing JSDoc support would be the first thing to shoot for.

**Comment by ronkorving** [comment]
I for one would love to see support for the flotate syntax that @ngduc refers to there. It's the one thing I hoped I could use (the inline comments are a bit messy imho), and would be a fair replacement for JSDoc (for some of my use cases), and much more compact.

**Comment by heyarne** [comment]
There's support for converting existing code using jsdoc syntax into the flow syntax, is that correct? Does that conversion handle modules? That would be a killer feature, enabling correct autocompletion and type-checking for existing well-documented libraries, so I could just `import foo from 'external/library'` and have the documentation right in my editor. 🚀

**Comment by bcherny** [comment]
@heyarne For the record, TypeScript does this!

**Comment by dgreensp** [comment]
I'd like to echo what @ronkorving said.  Being able to annotate a function with a single flow comment would be a huge benefit and make it more likely my team would adopt Flow.  Flow comments (as opposed to real annotations) are super useful not just to avoid preprocessing but also to not block on editor support on a diverse team.

The expectation that this would be implemented comes from the fact that, in theory, flotate has been deprecated and its functionality folded into Flow, but this aspect of flotate apparently did not make it over.

**Comment by Kegsay** [comment]
@heyarne : 
> There's support for converting existing code using jsdoc syntax into the flow syntax, which could then be used for checking, is that correct?

As far as I know, the `flow` binary does not support this. However, I have a project which will do this conversion for you: [Kegsay/flow-jsdoc](https://github.com/Kegsay/flow-jsdoc).

> Does that conversion handle modules?

No, it doesn't add in modules which are required for the type checking to work. It's an addition I want to add in the future though. The tool can operate on an entire directory, but each file is currently treated in isolation.

> And how does it handle mixed code where some files are written using the flow syntax and some use jsdoc?

Badly. Esprima doesn't support Flowtype syntax last time I checked, so the converter won't think it is valid JS.

**Comment by Pyrolistical** [comment]
I agree with @dgreensp. If support was added for a single line comment above the functions I would propose my team to use flow

**Comment by neemzy** [comment]
Hi,

May I ask whether you guys are considering parsing/supporting JSDoc comments to infer type info from it?

**Comment by Kegsay** [comment]
For people who want a 1-line comment of the form:
```js
/*: (x: string, y: number): boolean */
function(x, y) {
 // ...
}
```

Presumably this is desirable due to compactness. If so, presumably the following would be even better (else you need to make sure if you rename a variable that you also rename the comment form):
```js
/*: (string, number): boolean */
function(x, y) {
 // ...
}
```

If there is enough interest in a one-line form, I should be able to very easily fold this behaviour into [flow-jsdoc](https://github.com/Kegsay/flow-jsdoc) given I'm already parsing comments at this stage. This would effectively map:
```js
/*: (string, number): boolean */
function(x, y) {
 // ...
}
```
Into:
```js
/*: (string, number): boolean */
function(x: string, y: number) : boolean {
 // ...
}
```

**Comment by Pyrolistical** [comment]
@Kegsay I love it!  We can even make it more compact by introducing a single line comment syntax:
```
//: (string, number): boolean
function(x, y) {
 // ...
}
```

**Comment by dgreensp** [comment]
My only suggestion on the flow-jsdoc front is consider that Flow could one day support flotate one-line syntax.  The currently proposed flow-jsdoc feature (which is probably best discussed in that repo, not here) is yet another meaning of `/*:` and would cause trouble in that case.

**Comment by samreid** [comment]
The preceding one-line syntax examples are misleading because they lack documentation.  For instance, a documented version of the preceding example might be something like:

```js
  /**
   * Makes a prediction using decision trees whether a person would have survived a trip on the Titanic.
   * @param {string} x - last name of a person who rode on the Titanic (case insensitive)
   * @param {number} y - age of the person who rode on the Titanic in years
   * @return {boolean} - true if the prediction from the model is survival
   */
  //: (string, number): boolean
  function(x, y){
    // ...
  }
```

The one-line syntax (or even flow annotations) is redundant, let's comment our code and add JSDoc type checking for Flow.

**Comment by Kegsay** [comment]
@samreid That is exactly the rationale behind flow-jsdoc. The one line syntax is intended as an *alternative*, I have no desire to replace the exisiting logic to parse JSDoc. One line syntax works particularly well for private methods which people may not be documenting in JSDoc.

@Pyrolistical I would probably support both forms, as I find it somewhat magical if a tool treats block/line comments differently to each other when the actual language doesn't.

As for "Flow may one day sprout X", I'll cross that bridge if it ever happens. Worst case is a major version bump and a disclaimer that it only works on Flow vX and above. I'm not going to do nothing just because of speculative features.

**Comment by samreid** [comment]
@Kegsay I agree with everything you said, keep up the good work!

**Comment by Kegsay** [comment]
[flow-jsdoc](https://github.com/Kegsay/flow-jsdoc) now supports inline syntax of the form:
```js
//: (string): Object
function foo(bar) {
  return {};
}
```
Parameters are paired in order and will currently panic if there are mismatched lengths. I'll probably add a flag to make that optional (and it just won't add types to subsequent params / ignore additional types in comment).

**Comment by Kegsay** [comment]
> @Kegsay's tool looks nice, but doesn't support JSX 

Does now!
