### ISSUE TITLE
Support higher kinded type

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#30]
example : 

``` typescript
interface Mappable<M<A>>  {
  map<B>(func: (a:A) => B): M<B>;
}
```

**Comment by samwgoldman** [comment]
Here's another code dump that aligns more closely with the syntax we have now.

```javascript
type Monoid<T> = {
  zero: T;
  append: (a: T, b: T) => T;
}

// These are fine
var sumMonoid: Monoid<number> = {
  zero: 0,
  append: (a, b) => a + b
}

var productMonoid: Monoid<number> = {
  zero: 1,
  append: (a, b) => a * b
}

// The type variable T can't be free, but this
// formulation is valid for any type T.
var arrayMonoid: Monoid<Array<T>> = {
  zero: [],
  append: (a, b) => a.concat(b)
}

// We should be able to use any type, not just
// built-ins.
type Transformation<T> = (x: T) => T;
var transformationMonoid: Monoid<Transformation<T>> = {
  zero: (x) => x,
  append: (f, g) => (x) => f(g(x))
}
```

Note that these "type classes" are a bit more cumbersome to use than they would be in Haskell, where the compiler will thread the dictionaries around for you, or Scala where the implicit rules will do the same.

**Comment by popham** [comment]
Oddball edge case.  Given `I`:

```js
interface I {
  method(): string;
  static sMethod(): string;
}
```

should the following an error out?

```js
class A implements I {
  method: void => string;
  static sMethod: void => string;
  constructor() {
    this.method = function () { return "peep"; }
  }
}
A.sMethod = function () { return "peep"; }

**Comment by samwgoldman** [comment]
@popham I'm not sure how that is related to HKT. Can you elaborate?

**Comment by popham** [comment]
Off-topic.  Apologies.  (I'm imagineering what `interface` should look like, and this is the only lead I could find.  I just went to delete the prior, but then I saw your response.)

**Comment by rockymadden** [comment]
Looking for this feature as well.

**Comment by impinball** [comment]
Higher order types should also include recursive types. This would help in cases like Lodash's `flatten`. 

```
type Flattenable<A> = Array<A> | Array<Flattenable<A>>;

declare function flatten<T>(list: Flattenable<T>): Array<T>;
```

**Comment by samwgoldman** [comment]
@popham Your example isn't really related to HKT either. Also, recursive types should work. I think your type definition is wrong. You probably want something like this:

```javascript
type Flattenable<A> = Array<A | Flattenable<A>>;
var foo: Flattenable<string> = ['a', ['a'], [['a']]]; // OK
```

**Comment by samwgoldman** [comment]
Also, for what it's worth. Using the existential types that are on master right now, my previous example with 2 character substitutions type checks:

```javascript
/* @flow */

type Monoid<T> = {
  zero: T;
  append: (a: T, b: T) => T;
}

// These are fine
var sumMonoid: Monoid<number> = {
  zero: 0,
  append: (a, b) => a + b
}

var productMonoid: Monoid<number> = {
  zero: 1,
  append: (a, b) => a * b
}

var arrayMonoid: Monoid<Array<*>> = {
  zero: [],
  append: (a, b) => a.concat(b)
}

type Transformation<T> = (x: T) => T;
var transformationMonoid: Monoid<Transformation<*>> = {
  zero: (x) => x,
  append: (f, g) => (x) => f(g(x))
}

// HKT use case
function concat<T>(array: Array<T>, monoid: Monoid<T>): T {
  return array.reduce(monoid.append, monoid.zero);
}

var ex1: number = concat([1, 2, 3], sumMonoid);
var ex2: number = concat([1, 2, 3], productMonoid);
var ex3: Array<number> = concat([[1, 2], [3, 4]], arrayMonoid);
var ex4: Transformation<number> = concat([(x) => x + 1, (x) => x - 1], transformationMonoid);
```

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by pmlt** [comment]
Any update regarding this feature? There was no response within 30 days yet this feature request is not yet closed. I'd also like to see this become reality.

**Comment by gcanti** [comment]
Here's a (hacky) way to implement HKT: https://github.com/gcanti/flow-static-land

**Comment by jeffmo** [comment]
Thanks, @gcanti -- that seems like a reasonable workaround for now.

Just to follow up with something semi-official: There's a chance we may get to this at some point, but it's not on the near-term horizon for the core team. As we've done so far with this, we'll leave this issue open to track the request for if/when this surfaces the priority queue.

**Comment by Jacse** [comment]
Is there still no way to do this "officially"?

**Comment by jasonkuhrt** [comment]
@jeffmo In the year+ since your last comment, how has thinking on this by the core team changed if at all?

**Comment by astampoulis** [comment]
From what I can tell, higher-kinded types are actually supported in Flow, though they are encoded using the simple-kinded function type and the utility type `$Call` for type-level application. In fact, some of the utility types of Flow are using this encoding, such as the [`$ObjMap<T, F>`](https://flow.org/en/docs/types/utilities/#toc-objmap) type, where `F` is higher-kinded. Maybe this isn't official though, because I don't see it explicitly mentioned in the documentation, or I might be missing something.

The encoding is as follows:
the **kind** `Type -> Type` is encoded as the **type** `Function`
the **type-level function** `λA.F(A)` is encoded as the **type** `<A>(A) => F(...A...)`
the **type-level application** `F T` is encoded as the **type** `$Call<F, T>`
the **conversion-rule** is not fully supported, so some times you have to explicitly use an intermediate cast to `any` to view an expression of type `$Call<F, T>` as having the type of the β-redex `F[T]`, so for example if we have `type F = <A>(A) => Array<A>`, an expression of type `$Call<F, string>` is not immediately typeable as `Array<string>`.

Not sure if there is a way to encode kinds like `(Type -> Type) -> Type` (e.g. for monads), maybe by using a more restricted type than `Function` to specify the higher kinds.

**Comment by gcanti** [comment]
@astampoulis this is @hallettj's encoding I'm currently using in [fp-ts](https://github.com/gcanti/fp-ts)

```js
type Either<L, R> = { type: 'Left', value: L } | { type: 'Right', value: R }

type EitherF = <L, R>(x: [L, R]) => Either<L, R>
type ArrayF = <A>(x: [A]) => Array<A>

type ArrOfStrings = $Call<ArrayF, [string]>
type EitherOfStringNumber = $Call<EitherF, [string, number]>

;([1]: ArrOfStrings) // number. This type is incompatible with string
;({ type: 'Right', value: 'foo' }: EitherOfStringNumber) // string. This type is incompatible with number
```

**Comment by PinkaminaDianePie** [comment]
Any updates here? It's so hard to use Flow for functional programming without this. :(
