### ISSUE TITLE
React 0.13 style component definitions do not validate

### ISSUE THREAD

**Issue by thealjey** [facebook/flow#300]
Consider the following code:

    /* @flow */
    var React = require('react/lib/React');
    class Button extends React.Component {
      render() {
        return <button>{this.props.text}</button>;
      }
    }
    Button.defaultProps = {text: ''};
    React.render(<Button text="Click me!" />, document.body);
This produces the following error:

    app.js:9:14,40: React element: Button
    Expected React class instead of
      app.js:3:7,12: class type: Button
However, if reverted to `React.createClass`:

    /* @flow */
    var React = require('react/lib/React');
    var Button = React.createClass({
      getDefaultProps() {
        return {text: ''};
      },
      render() {
        return <button>{this.props.text}</button>;
      }
    });
    React.render(<Button text="Click me!" />, document.body);
Flow happily reports that there are `No errors!`.
Maybe I'm doing something wrong, but I can't find anything in the docs to indicate that.
I'm using `react@0.13.0-rc2 ` and `flow@0.4.0`.

Interestingly, even without trying to render anything this still gives the same error:

    /* @flow */
    var React = require('react/lib/React');
    class Button extends React.Component {
      render() {
        return <button>{this.props.text}</button>;
      }
    }
    Button.defaultProps = {text: ''};
    var el = <Button text="Click me!" />;
Produces this:

    app.js:9:10,36: React element: Button
    Expected React class instead of
      app.js:3:7,12: class type: Button

However, if you remove `var el = <Button text="Click me!" />;` from the last example, the error suddenly goes away.

**Comment by thoradam** [comment]
Flow has built in [declarations](https://github.com/facebook/flow/blob/master/lib/react.js) for the current version of React. I think you should be able copy those into your project, update to match React 0.13, and reference under `[lib]` in your `.flowconfig`.

**Comment by thealjey** [comment]
@thoradam thank you for the advice, I tried doing that, but unfortunately that didn't resolve the problem for me, I still get the same error

**Comment by samwgoldman** [comment]
This is definitely a real issue, and I believe something the core team is actively discussing. For now, the only way to use JSX with custom components is to use `React.createClass`.

**Comment by thealjey** [comment]
Fixed in the flow version 0.5.0

**Comment by thealjey** [comment]
This is only partly fixed!
If your component class inherits React.Component directly, then everything's fine.
But, if there's an intermediate class:

    class Component extends React.Component {
      state: Object;
    }
    class Button extends Component {}
    var el = <Button text="Click me!" />;
Flow reports the same error.
Additionally, it reports that Button is "Missing annotation" for the state property, completely ignoring the fact that it is defined on the parent class.

**Comment by samwgoldman** [comment]
The situation with typing custom components in JSX is pretty bad right now. The type inference engine has specific special cases for `React.createClass` and classes inheriting directly from `React.Component`. These special cases are quite obviously insufficient, but it's unclear to me how the situation can be improved right now.

I'd love to hear from the team at facebook how they plan to approach the bigger picture here.

**Comment by sporto** [comment]
I'm having a related issue:

file1
```
/* @flow */

var React   = require('react');

class Comp extends React.Component {

	render() {
		return (
			<i className="fa fa-spinner fa-spin"></i>
		)
	}

}

module.export = Comp;
```

file2

```
/* @flow */

var React    = require('react');
var Loader   = require('../shared/Loader.jsx');

class Comp extends React.Component {

	render () {
		return (
			<section><Loader /></section>
		)
	}
}
```

Flow error:

```
../file2.jsx:29:17,26: React element: Loader
Expected React class instead of
  ../file1.jsx: exports
```

flow --version
version 0.8.0

**Comment by samwgoldman** [comment]
@sporto Looks like that might just be a typo. You have `module.export = ` instead of `module.exports =`

**Comment by sporto** [comment]
@samwgoldman 	Oh right, thanks

**Comment by samwgoldman** [comment]
Flow is a lot smarter about React components these days. Please reopen if you are still having difficulties using Flow with React.
