### ISSUE TITLE
react-redux intersection error message

### ISSUE THREAD

**Issue by DCKT** [facebook/flow#3002]
Hello,

I'm using flow v0.36 with flow-typed and react/react-redux, and I'm encountering a strange flow error : 
**function call Function cannot be called  on any member of intersection type of intersection**

This occurs when I connect my component : 
```js
export default connect(null, mapDispatchToProps)(MyComponent)
``` 

Is a react-redux definition error ? Or maybe something I wrote ? 
Thanks.

**Comment by wokalski** [comment]
1. Your question cannot be answer without more context. There's probably a bug in your `mapDispatchToProps` definition.
2. This repository contains the implementation of flow itself. For questions regarding definitions try [flowtype/flow-typed](https://github.com/flowtype/flow-typed) or [stackoverflow](http://stackoverflow.com/questions/tagged/flowtype) with `flowtype` tag.

**Comment by DCKT** [comment]
You were right, this error is raised because I didn't annotate the dispatch parameter in `mapDispatchToProps` definition. Nevermind !
Thanks
