### ISSUE TITLE
https://flowtype.org/try failing in v0.37.0

### ISSUE THREAD

**Issue by tryggvigy** [facebook/flow#3003]
The flow playground is currently failing in `v0.37.0` No Errors, JSON or AST generated. See https://flowtype.org/try/#0GYVwdgxgLglg9mABBO4oBM4HcwBU4DCAFgE4wDOUAtgIbkAU6NUApgFyJghUBGLJASg4B+SmTABzRAG8AUImQJKiJgE9yAGRbAoiALyIATABZEAWhXMW8xCRZQQJJGs3aosgL6zZKNJhz4xGSUtAwAREQsADZRcGECskA

Works fine on `master` and `v0.36.0`

Error in console:
![image](https://cloud.githubusercontent.com/assets/2373958/21116792/e96fdcb8-c0ae-11e6-9c74-46c86dd0ed91.png)

**Comment by jeffmo** [comment]
Sorry about that, we're on it. For now you can use `master` instead

**Comment by mroch** [comment]
instead of releasing 0.37.1 or something like that, I cherry-picked f1e43b5d8b52241a196236ef5859e97b4f0b1c55, rebuilt flow.js and manually uploaded it to the CDN.

browsers may have cached it. in that case, shift+reload will pull the new version.
