### ISSUE TITLE
Flow doesn't support getters for defaultProps in es6 classes

### ISSUE THREAD

**Issue by Novex** [facebook/flow#3008]
Given an example es6 style react class like:
```
/* @flow */

import React, { Component } from 'react';

type DefaultProps = {
    foo: number
}

class OnlyGetter extends React.Component {
    static get defaultProps(): DefaultProps {
        return {
            foo: 3
        }
    }
}
```

and `unsafe.enable_getters_and_setters=true` is specified under the `[options]` header of the `.flowconfig`

Flow incorrectly finds the following error, despite it being valid to react (in that react correctly makes use of the `defaultProps`):
```
test.js:5
  5: class ClassGetterTest extends Component {
           ^^^^^^^^^^^^^^^ ClassGetterTest. Covariant property `defaultProps` incompatible with invariant use in
  5: class ClassGetterTest extends Component {
                                   ^^^^^^^^^ statics of React$Component


Found 1 error
```

As far as I know, this is the only way to set `defaultProps` at runtime rather than load time.

From what I can tell, this is due to the fact that the flow type definition expecting `defaultProps` to be able to be set as well as gotten, even though afaik react really only ever gets the value (I could be wrong here?).

Adding a dummy setter seems to work around the problem and causes flow to succeed:
```
    static set defaultProps(props: DefaultProps) {
        // do nothing
    }
```

Unfortunately, it doesn't seem possible to solve this problem in the react definition by marking `defaultProps` as covariant (ie. `+defaultProps`) because this breaks valid situations like:
```
class LaterDefaultProps extends React.Component {
    static defaultProps: DefaultProps
}

LaterDefaultProps.defaultProps = {
    foo: 3
}
```

I can't find a way to express "invariant or covariant, but never contravariant" in the flow definition, but this may be able to be resolved if #1189 is by providing a union between a definition where `defaultProps` is invariant and a definition where `defaultProps` is covariant.

[There's a test case here](https://github.com/Novex/flow/tree/7226046335c5645e2da639b9054c5590ac94872c/tests/react_defaultProps) - making it pass should resolve this problem.

**Comment by asolove** [comment]
With the `Component` interface changes in v53, this now works:

```js
import React, { Component } from 'react';

type DefaultProps = {
    foo: number
}

class OnlyGetter extends React.Component<*,*> {
    static get defaultProps(): DefaultProps {
        return {
            foo: 3
        }
    }
}
```

(@calebmer, I think this can be closed now.)

**Comment by gynekolog** [comment]
I don't think that this issue is solved.
Flow still ignores defaultProps.
When I set some prop in defaultProps(), flow still throws error that prop can be undefined (while it's not possible - it's defined in defaultProps).
Example: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnACJYHICuANjAAKxMOgC8cAN50AkLj5pUAOWQgsALjioYUYADsA5gBo6AXwbNWcYRFFwJ0mTGAw+GrTv3HZ8xSrUA-JrauoYm5nS+qOgAynzAACZYUHBYAB4wWHoJ6Nh4MAB0AMIkkHpZMAA8NqJGiAB8UnRwLR7IzrhwSdz8QiKompw9AjXiTTJyCtH+7gDkBAR8EADusyatcKb0sqgkWDAAFl4AFACUTRstAPRXcIfJbMDoYMQARm4gzZe4EHracFFlKp3CEvPY7kdUAUXrYoYCZvRLnBKDAeFA9HBKglgAA3AFTIFqMSSeHA0xwK71RGtcwRSpxRLJO4uNxiMgxGC2OAgZAAazYICYAKgTDIFPqQA

**Comment by arnoldbird** [comment]
[asolove's approach above](#issuecomment-323790786) is working for me, though it is much more verbose than what I had before I began to integrate flow:  
`MyComponent.defaultProps = { bgcolor: 'yellow' };`
