### ISSUE TITLE
$Shape: Covariant property `constructor` incompatible with contravariant use in

### ISSUE THREAD

**Issue by zerkalica** [facebook/flow#3016]
I try to create analog of [scala case-class](http://alvinalexander.com/scala/scala-case-class-copy-method-example). I use $Shape for validation rec object in copy method in example below. But got an error: "Covariant property `constructor` incompatible with contravariant use in".

```js

class Some {
    country = ''
    // Covariant property `constructor` incompatible with contravariant use in:
    copy(rec: $Shape<this>): this {
        return Object.assign((Object.create(this.constructor.prototype): any), this, rec)
    }
}

const a: $Shape<Some> = {country: 'test'}
const b = new Some()
b.copy(a)
```

Works fine with

```js
b.copy({country: 'test'})
```

**Comment by zerkalica** [comment]
Simpler example:

```js
class A {
    p: number

    copy(old: $Shape<A>): A {
        const a = new A()
        a.p = old.p
        return a
    }
}
const a = new A()

a.copy(a)
```

**Comment by episage** [comment]
+1 ?

**Comment by msiebert** [comment]
what we use at [Blue Matador](http://www.bluematador.com) is 

```js
class A {
  p: number
  constructor(p: number) {
     this.p = p
  }

  copy(props: $Shape<A>): A {
    const clone: Object = Object.assign({}, this, props)
    Object.setPrototypeOf(clone, A.prototype)
    return clone
  }
}

const a = new A(1)
a.copy({p: 2}) // a new instance of A with p = 2
```

What I really want is to be able to mix in a trait like in scala. So far, I've tried implementing it with a function that takes the original class and returns an anonymous class that extends the original class but contains a `copy` method, but I'm still having issues clobbering flow into doing that. Do you guys have any ideas about what to do about that?

**Comment by msiebert** [comment]
Lately I've been thinking that I'd love to be able to declare class properties on these classes with `+` to make them readonly. Something like this:

```js
class A {
  +p: number
  constructor(p: number) {
     this.p = p
  }

  copy(props: $Shape<A>): A {
    const clone: Object = Object.assign({}, this, props)
    Object.setPrototypeOf(clone, A.prototype)
    return clone
  }
}

const a = new A(1)
a.copy({p:2})
```

However, when I do this, I get the following:
```
16: a.copy({p:2})
           ^ property `p` of object literal. Covariant property `p` incompatible with contravariant use in
8:   copy(props: $Shape<A>): A {
```

Any ideas on what I'm doing wrong?
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AQTAG9UwwBqABwC4wA7AVwFsAjAUwCcyx056cAF06N0guJwAUtBiw6cAlCR7kwggBYBLHADoqYALxgqPAL6oefKgE9pnOFRx0AJAGV1WKuwA8BAHwKdESkqrz8Qrzw9Ox0APKsAFbsYoZg8UliOrg4mgDm9JLEpgA0alo4pVT2jgoqaYnJgjo47IIACvbigtZesVCSmPzspQR6nXDdXrWhnK2MnPSRQ2ao5hjhgmBYqdFIBJIAjLVYOla2xLQATKYKQA

**Comment by SamChou19815** [comment]
$Shape is now deleted
