### ISSUE TITLE
Cannot access properties on type made from $Diff

### ISSUE THREAD

**Issue by Macil** [facebook/flow#3020]
The following gives an error.

```js
/* @flow */

type X = {
  a: number;
  b: number;
};

type Y = $Diff<X, {b: number}>;

function foo(y: Y) {
  return y.a;
}
```

```
error.js:33
 33:       const title: string = props.title;
                                       ^^^^^ property `title`. Property cannot be accessed on
 33:       const title: string = props.title;
                                 ^^^^^ type parameter `P` of function call


Found 1 error
```

I've been trying to improve the definitions for redux and react-dnd in the flow-typed project and ran into this issue. Both of these libraries expose functions which take a React component class and ("collect") functions that take in the props passed to the wrapper component and return an object which is merged with the props and passed to the wrapped component. I need to use $Diff to take the `props` type of the wrapped component and subtract the return type of the collect functions. However I run into the above issue whenever the collect functions try to access the props object.

Here's a simplified example showing this problem in the context of some of React-DnD's types if anyone is curious how $Diff is needed in practice: https://gist.github.com/AgentME/5b698bd531790c90825549086bd7f69a

**Comment by vkurchatkin** [comment]
I think `$Diff` is only supposed to be used as argument in declarations

**Comment by xdissent** [comment]
FYI https://flowtype.org/docs/utility-types.html#diffa-b makes it look like you can do exactly what @AgentME is trying. But if you add a body to `setProps()` in the example it breaks:
```typescript
// @flow
type Props = { name: string, age: number };
type DefaultProps = { age: number };
type RequiredProps = $Diff<Props, DefaultProps>;

function setProps(props: RequiredProps) {
  (props.name: string) // err: property `name` Property cannot be accessed on Props
}
```

**Comment by echenley** [comment]
Just to add another example:

```js
type A = { x: string, y: string }
type B = { x: string }
type C = { y: string }
type DiffOne = $Diff<A, B>
type DiffTwo = $Diff<A, B>

// works
let a: DiffOne = { y: '' }

// doesn't think a is an object
let b = Object.assign({}, a)

// doesn't let you reuse a diff type
let c: DiffOne = a

// doesn't recognize C and DiffOne are the same
let d: C = a

// doesn't recognize DiffOne and DiffTwo are the same
let fn = (arg: DiffTwo) => arg
fn(a)
```

https://flowtype.org/try/#0C4TwDgpgBAglC8UDeUAeAuKBnYAnAlgHYDmANFCJjgSVAL4BQokUAQgsmlXkcfU+GgBhDikrYetRs2gARfADMFAeULREAEnlKAPDHKsAfAJbaFAFQDuAew5bFCvQeMMANhGBQAhpjOr1nOIA5EH8DAD04VAAJtYQWIRBnsAAFkQA1t5Q+FjehFDWAEYAVhAAxsBuHlCFHMol5cAAdF5YWPjEhAAUSHTkXgCUDBFRsfGJnu6eINYArlC4ELNY0F4xDlAyVZ5lvg7+HF7DkTFxCUkL5dad+ABewnnRUH5q3oubKdBYXgC2ENsxTAiRBHEancYXRZla6EO5yfavLyEJ5mKy2LzvVJfX7-KZQBT5RBdDHEPZKNEDBCGN7EBgE4lDIA

**Comment by gcazaciuc** [comment]
Having the same issue trying to use $Diff.

**Comment by SamChou19815** [comment]
No longer repros
