### ISSUE TITLE
Function cannot be called on any member of intersection type intersection

### ISSUE THREAD

**Issue by neurosnap** [facebook/flow#3024]
This debug statement is really vague and I've been trying to figure out why I keep getting these while using the `reselect` library.

```js
export const getMaxSyncMin = createSelector(
  getNextThreadMeta,
  (meta: ThreadMetaContainer): ?number => {
    if (meta && meta.meta) return meta.meta.message_sync_min;
    return null;
  },
);
```

![screen shot 2016-12-15 at 10 36 58 am](https://cloud.githubusercontent.com/assets/1940365/21230313/92d3e722-c2b2-11e6-812b-9264b6a75f40.png)

**Comment by mathielo** [comment]
The message is indeed rather vague. Not only that, if you don't pay close attention it might even be misleading as it doesn't point to the exact culprit code line; it points to where the test execution failed instead.

Had a similar issue and took me a while to understand that this was about an [Intersection Type](https://flow.org/en/docs/types/intersections/) that was being **declared on the top of the file**, while flow was pointing the error to the function call many lines later (same as your case).

For this specific case I'd figure that `ThreadMetaContainer` is an **Intersection Type**, e.g.:

    type Type1 = { some: 'object' };
    type Type2 = { something: 'else' };

    type ThreadMetaContainer = Type1 & Type2;

Only way I manage to avoid this error was removing the intersection. Would love to know if there's ~~any other~~ a proper way to fix it.

**Comment by neurosnap** [comment]
```js
export type ThreadMeta = {
  first: ?string,
  last: ?string,
  message_sync_min: number,
  message_sync_max: number,
  next: ?string,
  previous: ?string,
};

export type ThreadMetaContainer = {
  mailboxId: string,
  folderId: string,
  meta: ThreadMeta,
};
```

My guess is it is something internal to the flow-typed `reselect` library that is causing the issue.

**Comment by neurosnap** [comment]
It's really unfortunate but my solution was to remove the libdef for reselect altogether.

**Comment by thehogfather** [comment]
@neurosnap would you be willing to test out this version of the reselect type definition? It is basically a conversion of the typescript typings from reselect repository.
 Should work for flow 0.54 and above [https://github.com/thehogfather/flow-typed/blob/master/definitions/npm/reselect_v3.x.x/flow_v0.54.x-/reselect_v3.x.x.js](https://github.com/thehogfather/flow-typed/blob/master/definitions/npm/reselect_v3.x.x/flow_v0.54.x-/reselect_v3.x.x.js)
