### ISSUE TITLE
JSX - shorthand form of prop passes typechecking when it should not

### ISSUE THREAD

**Issue by gcazaciuc** [facebook/flow#3026]
Given a code like
```js
type PropsType = {
	param: number	
}

const Comp = (props: PropsType) => {
	return (<div>{props.param}</div>);
};

(<Comp param={true} />)  // Raises boolean. This type is incompatible with the expected param type of param: number
(<Comp param />) // Passes.
```

The 2 forms of passing props are equivalent. Also note that shorthand form is very common, especially since it can be enforced and automatically fixed by ESLint.
See it live [Try Flow](https://flowtype.org/try/#0C4TwDgpgBACgTgezAZwCrmgXigbwFACQYAhnMQLYBcUAdgK7kBGEcBeAvnngMYI3LAoAYQTkwUbAAowiFNXhI0GAJQSAfLkJwIwOnBpRJAHgAmASwBuanDMUA6EmXLsjAenNXlAbg4+8xkTEoRwpMHGA4Ogh2KFc1ZX8jQPEQ8lj4riA)

**Comment by goodmind** [comment]
This was fixed
