### ISSUE TITLE
Flow incorrectly(?) assumes static properties are inherited

### ISSUE THREAD

**Issue by ide** [facebook/flow#3028]
Flow disallows this program, even though static properties in JS aren't inherited (in contrast with Python class properties):
```js
class Parent {
  static staticProperty: string = '';
}

class Child extends Parent {
  static staticProperty: number = 0;
}
```

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBjaBDAzh0AFNAnAUwDsAXUAb0VFA1LVIEtlb6nkd9YAHQ-UgJ4AuVvkbEA5qAC8oAORyA3IgC+iFOiygAwgAtG0ACahCAD1IlD2PETKVqrBs0ftOPPoJHEArgFsARnwyoAAMyipAA

Fixing this however is kind of non-trivial because Flow would need to reject this program:

```js
class Parent {
  static staticProperty: string = '';
  printStaticProperty() {
    const cls = this.constructor;
    console.log(cls.staticProperty.toUpperCase());
  }
}

class Child extends Parent {
  static staticProperty: number = 0;
}

new Child().printStaticProperty();
```

**Comment by andreypopp** [comment]
> static properties in JS aren't inherited

Hm... It seems that they are inherited, that's what Chrome console gave to me:
<img width="230" alt="screenshot 2016-12-16 00 07 00" src="https://cloud.githubusercontent.com/assets/30594/21242087/af105166-c323-11e6-9f1e-4208f37a7cfa.png">

**Comment by jeffmo** [comment]
Static fields are inherited because a static field is set on a class object as [the last step of class declaration](http://tc39.github.io/proposal-class-public-fields/#runtime-semantics-class-definition-evaluation), and a class's `__proto__` is `===` it's parent class object.

**Comment by ide** [comment]
That answers this, sorry for the noise.
