### ISSUE TITLE
Detect exhaustive handling of enum types

### ISSUE THREAD

**Issue by jsdnxx** [facebook/flow#3032]
When using an algebraic data type of string literals, e.g.
```js
type Locale =
  | 'EN-us'
  | 'ES-us'
```

Flow should detect when I have exhaustively covered all of the cases. For example, when I handle each of these values in a switch and return from the cases, Flow should know (through refinement) that this will always return a string. Further, Flow should detect that any code after the last case is handled is unreachable, e.g.

```js
function greet (name: string, locale: Locale = 'EN-us'): string {
  switch (locale) {
    case 'EN-us':
      return `Hey there ${name}! What's up?`
    case 'ES-us':
      return `¡Hola ${name}! ¿Cómo estás?`
    case 'sdfds':
      // this should be unreachable
  }
  // this should be unreachable
}
```

See this example gist for how Flow 0.37.0 currently handles this
https://gist.github.com/jsdnxx/522d57085145be91dab2c049a11658ce

Thanks!

**Comment by bb010g** [comment]
Duplicate of #2399 & #2400.

**Comment by jsdnxx** [comment]
@bb010g thanks!

closing in favor of #2400
