### ISSUE TITLE
Un expected  an arithmetic operation must be a number throw

### ISSUE THREAD

**Issue by jyane** [facebook/flow#3033]
I have found a strange behavior of flow.

Here is an example of valid that using plus operator.
<a href="https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsABEyUCgFcYhAAr0cAZzABeMAG9UYMBQBcYAHZisAIzL4uAXy6pe-MDLjylq9ZoD8O-UZPnLVGBTkKABJwAOYCZAAehGS6ACYK5NSEAHQAwgx4ujGEADzCohLSsnIANLbFZQBucBixAHxOGnKEFIQYVGCxIuKSdvI6+T1F9grKahoa2mAAjM4WzjjFOn1yXBrOVHC6zfhiNAQAFIsjy8UAlI1gAJByYvz4R+drYGboGqxxJgcX4xOb28QKFMPMZ8I5CAALDByZLHeTJChgADUM2e7zIhDE+F0YBysQwlTAwDqz1eZiAA">Re-produce</a>

Here is an example of invalid that using minus operator.
<a href="https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsABEyUCgFcYhAAr0cAZzABeMAG9UYMBQBcYAHZisAIzL4uAXy6pe-MDLjylq9ZoD8O-UZPnLVGBTkKABJwAOYCZAAehGS6ACYK5NSEAHQAwgx4ujGEADzCohLSsnIANLbFZQBucBixAHxOGnKEFIQYVGCxIuKSdvI6+T1F9grKahoa2mAAjM4WzjjFOn1yXBrOVHC6zfhiNAQAFIsjy8UAlI1gAJByYvz4R+drYGboGqxxJgcX4xOb28QKFMPMZ8I5CAALDByZLHeTJChgAC0M2e7zIhDE+F0YBysQwlTAwDqz1eZiAA">Re-produce</a>

I think type of a is number. Why I have got an error?

**Comment by kvkirthy** [comment]
I believe, in case  of + operator it acts as a concatenation operator. Other operators like multiplication and - can not work on undefined. 

Adding a null check or if it's not a maybe type, you don't see the error.

```
// This will not show an error
    if(this.props.a != null){
    	const aa: number = this.props.a - 1;
    }

// Neither this will show an error

type Props = {
  a: number;
};
// ...
onst aa: number = this.props.a - 1;
```

**Comment by jyane** [comment]
Thank you for your reply!

I know it, but I think default props will provide default values, so `this.props.a` is always `number`.

**Comment by alfonsoperez** [comment]
Currently, [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8xCBPHMsAYTlzgDsyfQgBU2HAL5go+HmADk+SjTkBudK3ZgAImSgUArjEIAFGTgDOYALyNUYMBQBcYPvqwAjMvjXi1qDRymcBbWtvYUAPzOrh5ePn5UMBTmlgAScADmHGQAHoSCACaW5NSEAHTcvAJCADxBFgB8YWDmhBSEGFRgBboGRvWWNgx29g7OAIwjviM4ZubOA2r2I1T8rfj6NAQAFLPB82ADAJTNAJDm+uz4u3NHS2Di6PaKfD3XJ8OjYKt8rQ5OLjcnnwoUIAAsMOYynsLGUKGAANRgcb3Z5kQj6fB8MA1AoYABuYGADXuj3EQA) doesn't throw errors:

**Comment by stevesuyao** [comment]
@alfonsoperez  no,  [this ](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8xCBPHMsAYTlzgDsyfQgBU2HAL5go+HmADk+SjTkBudK3ZgACjJwBnMAF5GqMGAoB+AFxg+AVywAjMvjXi1qKjAp6DACTgAcw4yAA9CQQATA3JqQgA6bl4BIQAeHTh9AD4TMz1CCkIMKjBIsigKOxhCDP0jXLNzGwBGUzB3NpxdPRtavTUzNqp+fPw7GgIACi7Mnu1ugEoGgEg9O3Z8acWB9vQzRT4yzaWGNrNhvnzzCht7Jxd6gCZkZgALDD14mf14ih39siEOz4PhgVKRDAANzAwCyO3EqHEQA) dose throw error: 
 if we change `const aa: number = this.props.a + 1;` to `const aa: number = 2 * this.props.a;`

error:
`const aa: number = 2 * this.props.a;
                               ^ undefined. The operand of an arithmetic operation must be a number.`
