### ISSUE TITLE
Flow prop validation for function doesn't verify signature/parameter list

### ISSUE THREAD

**Issue by kvkirthy** [facebook/flow#3034]
Consider following type for Props
```
export type CounterProps = {
    offset: number;
    eventCallback: (num: number, eventTime: Date) => void;
};
```
Callback signature is not verified while invoking the component. Flow shows no errors.

```
// Use Counter as below and Flow finds no errors
// Notice eventCallback was not provided with second parameter (eventTime).
 <Counter offset={4} eventCallback = {(num: number) => console.log(`At Counter Value is ${num} `)} />

// Same problem with default props too
Counter.defaultProps = {offset: 1, eventCallback: (num: number) => {}};
```
Component definition as below,
```
export default class Counter extends React.Component{
    props: CounterProps;
    static defaultProps: CounterProps;

    constructor(props: CounterProps){
        super(props);
    }

// rest of class definition

}
```

**Comment by vkurchatkin** [comment]
This is not a bug. A function with less arguments is considered a subtype.

**Comment by kvkirthy** [comment]
It doesn't work (show error) for more number of parameters or change in data type. 

Following doesn't return an error
```
// notice num is string. Type alias has it a number
eventCallback = {(num: string, eventTime: Date) => console.log(`At Counter Value is ${num} `)} 

// more params
<Counter offset={4} eventCallback = {(num: number, eventTime: Date, val: string) => console.log(`At Counter Value is ${num} `)} />
```
Where as documentation at [this link ](https://flowtype.org/docs/react.html#defining-components-as-reactcomponent-subclasses) says 

> While PropTypes are great, they are quite limited. For example, it’s possible to specify that a prop is some kind of function, but not what parameters that function accepts or what kind of value it might return.
> 
> Flow has a much richer type system which is able to express those constraints and more. With class-based components, you can specify the components’ props, default props, and state using Flow’s annotation syntax.

**Comment by vkurchatkin** [comment]
@kvkirthy can you post a complete example on https://flowtype.org/try/ ? I tried it and it works fine

**Comment by kvkirthy** [comment]
@vkurchatkin Tried to share it with you and it works on [flowtype.org/try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG5NcDjzrCAEQDyAWTB0GzVgIC0AEwad0qMgA88RMIQCeOMmADCcAK4A7QmXwAFejgDOYALxgA3qjCewcKFHtlCAC4wMxMsACMrLi8wMgA3MgtDChgYcOoAa2CAClCsYLzI-AAaWISLABVsMmDBCksASmcAPjA4uAx5LgBfLlUNXjB5MigKExhiKhgKe0djc0t8WLVLM3lHfhoAOmMeM0TCdw8vHDt7YPmLK1s4B2ive0J6jCohkbGJm4cL0yubM-unke9RqbmOMU8VF+iwAaikTKDClZwWBeugYhgzFRWFgDjkmk5Wq40TFhtiyLiLPiWm5uiiUVCzI98CYaARsqdbucjNDrmcGu4IQ8TPp8Bz+YCIYQABYYexbYGWZxgoVCqELKxwmAI4IABhRMTRBq8MrlW0x5MpxBcpvlFpxBy24Ux8mytoakpitq2ZIdFmV3t9FMdzrWbtl9g9xs8KLpKPtwYs2QawXanUFqu9-kIAGUnpZsq51X8tTrtBGFfmyFti7D4QYANTls2chxbHx+ALdKPRsAYKDhltnLbxA7JVLpKgZMAAQhcoVSAt7Xorrflo6SKTSmUH8sV1drmvrpX2SDqBYaUdVqNj9NJZEtB2TGaFWYCeZBhcP+FLoKzVZrXkf3rMBZGbeU13bXxs27Ppr37XctkgjdCHHbcp1nedxhgJdrxXIcuRHcpUK3ScMkQ-dAI1YDtTIE8yDPT9L09Lw6UNdEvFYNYrGfa9e1YQgTHwMwwAAHnkDA4laPCYxkzxROlABGZpXH-EEqJLetulE4AlOaZcvHEyTmlE8ITEIQg4BEqYZnsAA5ChcScAAicJCBEtyzFkU5sAofAdGc7wzEMGAXgyJxVIrBMrW6EzmSsgBzZoGx0+KzCSnSzIsqzWgM+T7BwCgzGaAAyMxwgKjhUsK4q8rErLLOs6ZZgcpzXPcsBPO8-BfP8wKrJCsKIsDB8-UIbowDiwh6HS5pZFS6bEpM4AGpynSJKk3t1uM2840uRYfXecZCC+RwXFcDts2CRTShQtCyJyPICjCIoCSJbojU2IQxC2LjhjFFFRP2qxvGggIIoAFgmu7SMyZVXFyMJgmZTEEtu4iqlxWoQVKexHJwGAahR9K3rARl7DgQmtngBLsgAAwAQWIYGll-PtHAAElcPIJrphoJuAfSYlKRQqDCR0EoCABRQmrQAIR0ABJV0WDYQgGZwHAmGYoA) 

However, on a Windows 7 machine it still doesn't. Please review [screenshot at this link](https://github.com/kvkirthy/VenCKI-Samples/blob/master/Flow-basic-sample/Capture.PNG)

**Comment by vkurchatkin** [comment]
Can you run Flow manually from console? It could be IDE integration

**Comment by kvkirthy** [comment]
@vkurchatkin It didn't work on bare bone command prompt either. [Screenshot](https://github.com/kvkirthy/VenCKI-Samples/blob/master/Flow-basic-sample/Capture-Cmd.PNG)

**Comment by asolove** [comment]
Can you still reproduce this problem? The code needs tiny syntax changes because of Flow v0.53, but it seems to work as expected (giving type errors that it should) both on Try Flow and on my desktop.

(If I had to guess, and if this is Windows-specific, I would say maybe the flow server has a Windows-specific bug where it caches old file contents or something? Does it work if you make a new file and paste that in? Or if you add a new, simpler type error to the file, does that show up?)

**Comment by calebmer** [comment]
What version of Flow are you on? This should work in Flow v0.53. I’m going to close for now, but if you continue to get this error in Flow v0.53 please re-open! I wouldn’t expect this code path to be significantly different on Windows 😣
