### ISSUE TITLE
Flow doesn't typecheck object properties when using `+=`

### ISSUE THREAD

**Issue by migueloller** [facebook/flow#3038]
[Here's](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMcBGAVgFxgDeYAdgK4C2pNt+mATmAL5gC85VdpABg4BudAUIA6RmADUPAOTzRqAMZxKAZzhYJ8AOYAKbAE8ADpjhQ8RKXQCUwsMGBgARBuwsAlpT2uwEoF4ABZUcACEqEA) the example with `+=`:
```es6
/* @flow */

let obj: { num: number } = { num: 0 };

obj.num += '';

console.log(typeof obj.num); // "string"

// Flow:
// No errors!
```

[Here's](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMcBGAVgFxgDeYAdgK4C2pNt+mATmAL5gC85VdpABg4BudAUIA6RtzxEpdMAGowAchWjUAYziUAznCwT4AcwAU2AJ4AHTHCizJjAJTCwwYGABEu7CwCWlMaeYBKheAAWVHAAhKhAA) the example without `+=`:
```es6
/* @flow */

let obj: { num: number } = { num: 0 };

obj.num = obj.num + '';

console.log(typeof obj.num); // "string"

// Flow:
// 5: obj.num = obj.num + '';
//              ^ string. This type is incompatible with
// 3: let obj: { num: number } = { num: 0 };
//                    ^ number
```

It looks like because it doesn't see `obj.num` in the right-hand side of the AST it doesn't complain. Any ideas?

**Comment by SamChou19815** [comment]
This is now correctly checked.
