### ISSUE TITLE
`import type` in declaration breaks other imports of that type

### ISSUE THREAD

**Issue by mkscrg** [facebook/flow#3040]
Repro gist here: <https://gist.github.com/mkscrg/65a5d661a0055bc3495bd6b628e05eb4>

When used in a declaration file, the `import type { ... } from ...` syntax breaks other uses of the imported types.

This may be a duplicate of #2130. @avikchaudhuri mentions there that Flow doesn't support `import` in declarations, though I can't find that documented anywhere. If that's the case, can we have an error thrown when Flow encounters imports in declarations?

#### Example

Given two declaration files, where the second declaration imports a type from the first:

`libdefA.js`:
```js
declare module "foo" {
  declare class Bar {}

  declare class Baz {}
}
```

`libdefB.js`:
```js
import type { Bar } from 'foo';
```

`.flowconfig`
```
[ignore]

[include]

[libs]
./libdefA.js
./libdefB.js

[options]
```

Then any use of the type `foo.Bar` causes a Flow error:

`main.js`:
```js
// @flow
import foo from 'foo';

type Bar2 = foo.Bar;
```

```
main.js:4
  4: type Bar2 = foo.Bar;
                 ^^^^^^^ Bar. Property not found in
  1: declare module "foo" {
     ^ module `foo`. See lib: libdefA.js:1
```

#### Related notes

1. We can avoid this issue by using the "normal" import syntax in declaration files. E.g. `libdefB.js` can `import foo from 'foo'` without causing trouble for `main.js`.
1. We can also avoid this issue by swapping the order of the declaration files in `.flowconfig`, e.g.

    ```
    [libs]
    ./libdefB.js
    ./libdefA.js
    ```

    If you put the declaration files in a directory and reference that from `.flowconfig`, then the lexicographic sort of the filenames determines the order, with the same effect. In that case renaming `libdefB.js` to `libdef0.js` avoids the issue.
1. There are several `flow-typed` definitions that use `import type { ... }`. Some cause this issue and some don't, due to the ordering behavior noted in 2 above.

**Comment by sibelius** [comment]
any updates on this?

**Comment by SamChou19815** [comment]
Flow errors on toplevel import in libdefs for quite a long time now
