### ISSUE TITLE
Flow failing to recognize very obvious logic

### ISSUE THREAD

**Issue by taoeffect** [facebook/flow#3041]
Given types:

```js
// types defined in file A
export type JSONType = string | number | boolean | null | JSONObject | JSONArray;
export type JSONObject = { [key:string]: JSONType };
export type JSONArray = Array<JSONType>;

export type EvType = EvTypeErr | EvTypeOK
export type EvTypeErr = 'error'
export type EvTypeOK = 'success' | 'event'

export type Response =
  | {event: EvTypeErr; err: string; data?: JSONType}
  | {event: EvTypeOK; data: JSONType}
```

And code:

```js
// code in file b
const ERROR: EvTypeErr = 'error'

export function makeResponse (
  event: EvType,
  data: JSONType,
  err?: (string | {message: string})
) : Response {
  if (event === ERROR) {
    if (err) {
      return {event, data, err}
    } else {
      return {event, err: data}
    }
  }
  return {event, data}
}
```

Flow fails with several errors, including:

```
shared/functions.js:41
 41:       return {event, data, err}
                  ^^^^^^^^^^^^^^^^^^ object literal. This type is incompatible with
 35: ) : Response {
         ^^^^^^^^ union: object type(s)
  Member 1:
   23:   | {event: EvTypeErr; err: string; data?: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:23
  Error:
   41:       return {event, data, err}
                     ^^^^^ string literal `success`. Expected string literal `error`, got `success` instead
   23:   | {event: EvTypeErr; err: string; data?: JSONType}
                   ^^^^^^^^^ string literal `error`. See: shared/types.js:23
  Member 2:
   24:   | {event: EvTypeOK; data: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:24
  Error:
   41:       return {event, data, err}
                     ^^^^^ string literal `error`. This type is incompatible with
   24:   | {event: EvTypeOK; data: JSONType}
                   ^^^^^^^^ string enum. See: shared/types.js:24
```

Those most surprising error is that it thinks the `return {event, data, err}` could have `event` with value `success`. But that is very obviously impossible because it is within an `if` block where `event` is identical to `ERROR`, which itself has the value `'error'` (with type `EvTypeErr`).

Using Flow version 0.37.0.

**Comment by taoeffect** [comment]
If I spoon-feed Flow by changing `if (event === ERROR) {` to:

```js
if (event === 'error') {
```

Then flow gives me this error, which also doesn't make sense:

```
shared/functions.js:41
 41:       return {event, data, err}
                  ^^^^^^^^^^^^^^^^^^ object literal. Could not decide which case to select
 35: ) : Response {
         ^^^^^^^^ union type
  Case 1 may work:
   23:   | {event: EvTypeErr; err: string; data?: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:23
  But if it doesn't, case 2 looks promising too:
   24:   | {event: EvTypeOK; data: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:24
```

I'm not sure how Flow can think "case 2" looks "promising" when it is impossible.

**Comment by taoeffect** [comment]
Some more troubleshooting, and fixed a slight mistake on my part, but it doesn't seem to affect issue.

This:

```js
return {event, data, err}
```

Should have been this:

```js
return {event, data, err: err.message || err}
```

But Flow is still unhappy:

```
shared/functions.js:43
 43:       return {event, data, err: err.message || err}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object literal. Could not decide which case to select
 36: ) : Response {
         ^^^^^^^^ union type
  Case 1 may work:
   23:   | {event: EvTypeErr; err: string; data?: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:23
  But if it doesn't, case 2 looks promising too:
   24:   | {event: EvTypeOK; data: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:24
  Please provide additional annotation(s) to determine whether case 1 works (or consider merging it with case 2):
   43:       return {event, data, err: err.message || err}
                     ^^^^^ identifier `event`
   43:       return {event, data, err: err.message || err}
                                       ^^^^^^^^^^^^^^^^^^ ||
```

(There's one more error after that too, and it also doesn't make sense, but I'm leaving it out for brevity.)

I don't know what sort of "additional annotations" it wants, but I tried this:

```js
return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: string})
```

And it spat out more nonsense:

```
shared/functions.js:43
 43:       return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: string})
                                      ^^^^^^^^^^^ property `message` of unknown type. This type is incompatible with
 43:       return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: string})
                                                                                                    ^^^^^^ string

shared/functions.js:43
 43:       return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: string})
                                                     ^^^ object type. This type is incompatible with
 43:       return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: string})
                                                                                                    ^^^^^^ string
```

I don't understand how it think `property `message` of unknown type` when it's clearly defined as a string:

```js
  err?: (string | {message: string})
```

The reason I define it that way is to make it possible to pass in an `Error` instance.

**Comment by jedwards1211** [comment]
Maybe Flow is thinking that if `err` is of type `string`, then `err.string` is `undefined` rather than a `string`...though in that case the `||` would fall through to `err`, but maybe Flow can't deduce that correctly.

But you could try `typeof err.message === 'string' ? err.message : err`

**Comment by jesseschalken** [comment]
This works

```js
/* @flow */

export type JSONType = string | number | boolean | null | JSONObject | JSONArray;
export type JSONObject = { [key:string]: JSONType };
export type JSONArray = Array<JSONType>;

export type EvType = EvTypeErr | EvTypeOK
export type EvTypeErr = 'error'
export type EvTypeOK = 'success' | 'event'

export type Response =
  | {event: EvTypeErr; err: string; data?: JSONType}
  | {event: EvTypeOK; data: JSONType}

export function makeResponse (
  event: EvType,
  data: JSONType,
  err?: (string | {message: string})
) : Response {
  if (event === 'error') {
    if (err) {
      const err2 = typeof err === 'string' ? err : err.message;
      return {event:'error', data, err: err2}
    } else {
      return {event:'success', data}
    }
  }
  return {event, data}
}
```

**Comment by taoeffect** [comment]
If I do that I get:

```
shared/functions.js:42
 42:       return {event, data, err: (typeof err.message === 'string' ? err.message : err)}
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object literal. Could not decide which case to select
 31: ) : Response {
         ^^^^^^^^ union type
  Case 1 may work:
   25:   | {event: EvTypeErr; err: JSONType; data?: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:25
  But if it doesn't, case 2 looks promising too:
   26:   | {event: EvTypeOK; data: JSONType}
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type. See: shared/types.js:26
  Please provide additional annotation(s) to determine whether case 1 works (or consider merging it with case 2):
   42:       return {event, data, err: (typeof err.message === 'string' ? err.message : err)}
                                                                                        ^^^ identifier `err`
   42:       return {event, data, err: (typeof err.message === 'string' ? err.message : err)}
                     ^^^^^ identifier `event`
   42:       return {event, data, err: (typeof err.message === 'string' ? err.message : err)}
                                                                          ^^^^^^^^^^^ property `message`
```

Only thing that works is `return ({event, data, err}: {event: EvTypeErr; data: ?JSONType; err: JSONType})`.

This is what that function looks like right now:

```js
// TODO: this is bullshit.
// import {EVENT_TYPE} from './constants'
// const ERROR: EvTypeErr = EVENT_TYPE.ERROR
// const ERROR: EvTypeErr = 'error'
// https://github.com/facebook/flow/issues/3041
// https://flowtype.org/docs/functions.html#too-many-arguments
export function makeResponse (
  event: EvType,
  data: JSONType,
  // err?: (string | {message: string})
  err?: JSONType
  // err?: string
  // err?: (JSONType | {message: JSONType})
) : Response {
  // var response: Response = {event, data}
  if (event === 'error') {
  // if (event === ERROR) {
    if (err) {
      // response.data = data
      // response.err = err
      // return data ? {event, data, err} : {event, err}
      // return {event, data, err}
      // return ({event, data, err}: {event: EvTypeErr; data: ?JSONType; err: string})
      return ({event, data, err}: {event: EvTypeErr; data: ?JSONType; err: JSONType})
      // return {event, data, err: err.message || err}
      // return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: string})
      // return ({event, data, err: err.message || err}: {event: EvTypeErr; data: ?JSONType; err: JSONType})
    } else {
      // response.err = data
      return {event, err: data}
    }
  }
  return {event, data}
}
```

I know this isn't the most trivial of apps to write, and I commend the developers on their great work to improve the JS landscape, but this is serious enough that we'll be putting effort into exploring TypeScript.

**Comment by taoeffect** [comment]
> If I do that I get:

Just saw @jesseschalken's reply (we posted at the same time). Thanks Jesse, that's an interesting hack, one that I definitely did not consider. But flow should work without these kinds of strange workarounds. I don't expect myself or the developers I work with to come up with that sort of thing—it would end up wasting more of our time than it saves. I'm hoping this can be fixed, but if not we'll try TypeScript. If TypeScript can't handle it either, we'll just rely more on tests and do the bare minimum in terms of type annotations until the ecosystem evolves.

**Comment by jesseschalken** [comment]
@taoeffect I'm not sure about this particular example, but in general TypeScript only emits less errors because it lets a truckload of type errors pass silently. If that's what you want, then you can get that in Flow by putting `:any` everywhere.

**Comment by jesseschalken** [comment]
@taoeffect Sorry, I misunderstood your code and broke it above (it returns a success response in the `if` for an error). How is this line supposed to work?

```
      return {event, err: data}
```

`data` is of type `JSONType`, but the `err` property is of type `string`.

**Comment by taoeffect** [comment]
@jesseschalken Yes, that was another little mistake on my part (which again, doesn't impact the relevance of this issue as a whole; Flow's type checker was giving me nonsense when it should have been pointing out things like what you just pointed out).

I fixed that by changing the function parameter types. The code I [pasted here](https://github.com/facebook/flow/issues/3041#issuecomment-267867056) I literally what we're using now, and the new `Response` type is updated accordingly:

```js
export type Response =
  // | {event: EvTypeErr; err: string; data?: JSONType}
  // https://github.com/facebook/flow/issues/3041
  | {event: EvTypeErr; err: JSONType; data?: JSONType}
  | {event: EvTypeOK; data: JSONType}
```

**Comment by jesseschalken** [comment]
@taoeffect The `err: data` problem came straight out of the type checker once the issues around `event` were fixed.

So the only workarounds Flow demands are:

```js
if (event === 'error') {
```

instead of 

```js
if (event === ERROR) {
```

and

```js
      return {event:ERROR, data, err}
      // or
      // return {event:'error', data, err}
```
instead of
```js
      return {event, data, err}
```
So there's a legitimate problem there around unions and constant strings, and the developer has to wiggle a bit to make the code more obvious to the typechecker.

Still, Flow did its job by rejecting code that it couldn't prove was type safe, while there are countless examples and patterns that are obviously not type safe but which TypeScript happily accepts, causing broken code to leak into testing or production, and for which the TypeScript devs have said repeatedly that they wont fix. If that fits your criteria for a static type checker that's fine, but just be aware.

**Comment by taoeffect** [comment]
@jesseschalken Thanks for the caution on TypeScript.

The problem here though is that even though I made some mistakes, IMO Flow did not do its job, because its job is to point those mistakes out to me. Instead, it pointed out totally unrelated things (or at least, things that had all the appearance of being totally unrelated) that didn't make any sense. Am looking forward to these quirks being ironed out, I really want to love Flow.

**Comment by jedwards1211** [comment]
@jesseschalken in general I've always found it difficult to get intersections with shapes to work.  I think Flow probably needs some work in that regard, but on the other hand, these days I generally try to avoid shape intersections, because even if they check out, if you make a mistake later, Flow prints out heinously confusing type errors, and if you think about it, there's probably no obvious way for it to explain why none of the intersected types match.

So while it would be nice to know that `err` will be defined iff `event` is `'error'`, in this case I would usually just use a single shape with `err?`, like so (this code does work):

```js
export type Response = {event: EvType; err?: string; data?: JSONType}

// code in file b
const ERROR: EvTypeErr = 'error'

export function makeResponse (
  event: EvType,
  data: JSONType,
  err?: (string | {message: string})
) : Response {
  if (event === ERROR) {
    if (err) {
      return {event: ERROR, data, err: typeof err === 'string' ? err : err.message}
    } else {
      return {event, err: String(data)}
    }
  }
  return {event, data}
}
```
Note how it has no problem with `ERROR` either.

**Comment by vicapow** [comment]
Hello and thank you for reporting the issue. With that said, this ticket seems to address a few different possible issues. In the future, it may also be helpful to also simply the issue into its basic parts and report those issues separately.

For example, I think this issue touches on at least this particular behavior of Flow (but possibly others) regarding refinements with constants vs literals: https://github.com/facebook/flow/issues/7417

````js
type V = 'A' | 'B';
const A: 'A' = 'A';

declare var v: V;
if (v === A) {
  (v: 'A'); // Should allow being refined to `'A'` but errors instead.
}
````

Closing for now but please feel free to follow up on this thread as well as create separate issues for any other inconsistent behavior.
