### ISSUE TITLE
disjoint unions with primitive types

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#3042]
Should disjoint unions be able to work with primitive types or do they only support other types and classes?
````
// @flow
type PrimitiveType = boolean | number | string;
let value: PrimitiveType = true;
value = 7;
value = 'foo';
value = new Date(); // should get an error here, but do not
console.log('value =', value);
console.log('typeof value =', typeof value); // outputs "object"
````

**Comment by vkurchatkin** [comment]
Date is considered a subtype of number. That's probably on purpose

**Comment by mvolkmann** [comment]
Okay, maybe this isn't a bug then. Feel free to close it if that's the case. It does seem weird to me to treat Date objects as a subtype of number.

**Comment by TrySound** [comment]
Fixed.

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagAoCcBLAWwOQIDdMAVDbAXlACNZZpMBDAO1AB9ROArkUaY8vUAGdkhTgHMA3IjbJQ5dtAGYAXLkIkylGllANpmxWo31QAdgvrNJ0AHJILZ-atPOmeKAAi7MiYABQAlPKgIJIAFrAC0AAmoLKYKlygoniwYjGimAA0TAIqibD8sMiIAMawnBKsmAB0cLIhzpaOdM5FnZgRNXUNbC2wbc5oWLCQqg70PaCTmNOzVhFRYPHI6CUSoABEsIwAVpjVyPtAA
