### ISSUE TITLE
[RFC] integer/natural, constraints, $Specialize, type-level operators, Vector

### ISSUE THREAD

**Issue by bb010g** [facebook/flow#3044]
Five RFCs for the price of one! This was getting a bit big as I tried to work out what you'd need to "sanely" implement Vector, so I figured it would be better split up in increasing difficulty of implementation (I think). I don't expect much of this to actually be like this if/when implemented, but it will at least provide a base for discussion.

### Features
`integer` is a refinement of `number` that excludes numbers with fractional parts (_not_ `NaN`). This would be inferrable at compile time by literals, use of bitwise operators (e.g. `((n: number) | 0): integer`), or numeric operations where all arguments are known to be `integer`.

`natural` is a refinement of `integer` that excludes negatives. This would be inferrable at compile time by literals. (Dynamic creation & manipulation would most likely entail needing type-level operations for them to be useful.)

### Uses
`integer` would be immediately usable for constraining map keys: `{[key: integer]: *}`. The dynamic creation & manipulation would aid with maintaining safety when accessing such maps. Combined with proper disjoint union dynamic type tests (#2400), a lot of existing code that uses disjoint integer unions for state would check with no modifications.

`natural` would be useful as a constraint that would most likely be cast away to be usable at compile time. I'd imagine it wouldn't be too much worse than `integer` to implement, but it isn't very useful without specialization or type-level operators.

### Examples
```javascript
function(n: integer): integer { return n + 1; }
function(n: number): integer { return n|0; }

const alphabet: {[key: natural], string} = {
  [0]: "a",
  [1]: "b",
  [2]: "c",
  ...,
  [25]: "y",
  [26]: "z",
};
```

### Features
The constraint kind would be separate from the kind of normal Flow types. Any constraint would be usable in generics.

This change alone would affect generics: Generic parameter declarations (the `<...>` bits) would have a new syntax: `<(typeParameter,)* ; (constraint,)*>` (pardon my pseudo-BNF). A declaration with no constraint section would desugar to a declaration with an empty constraint section (e.g. `<A>` desugars to `<A;>`). The current syntax of `<A: TypeA, B: TypeB>` could be seen as desugaring to `<A, B; $Typed<A, TypeA>, $Typed<B, TypeB>>`, where `$Typed<Type, Supertype>` is a utility constraint that would ensure `Type` is a subtype of `Supertype`.

`$Valid` is the empty constraint (`Foo` ≡ `Foo<$Valid>`). `$Valid<Type>` is a utility constraint that takes a type and does nothing with it, allowing for a constraint to see if a type checks.

`constraint [name]: C` is a new compile-time declaration that ensures that constraints are filled. Nothing should really need to be changed in the type checker to allow this, and it may currently be simulated in Flow through the use of a constant and generics. If a name is given, it will be used in error messages when reporting violations.

`$Constrain<Type, FreeName, Constraint...>` is a new utility type that allows for attaching constraint checks to an anonymous type. It binds `FreeName` to `Type` when evaluating each `Constraint`.

`$Equals<A, B>` is a utility constraint that takes two types and ensures they are completely equal.

### Uses
Constraints on generics are more expressive than what can be stated in the type of an expression alone. I'm currently using them to ensure that a map's key set is exactly the same as an enum. Also, type aliases cannot currently have constraints or supertypes directly specified, and this allows for them.

### Examples
```javascript
// The constraint kind can currently be awkwardly recreated as so:
/*
 * The unit tuple is a cheap constant. It's still officially runtime cost, but
 * your bundler will probably optimize it out as dead code. This would be equal
 * to $Valid in the spec.
 */
type Constraint = [];
// By having a value to check, the type checker is forced to run.
// Witness is a fun word.
const witness = [];

/*
 * Equivalent to $Equal, except it seems to fail on complex expressions
 * involving $Keys on both sides. (This can be partially resolved if you just
 * make a new, non-$Keys type that both can equal.)
 */
type _EqualConstraint<A, B: A, A: B> = Constraint;
type EqualConstraint<A, B> = _EqualConstraint<A, B, A>;

type FavoriteKey = "bar" | "biz";
type Foo = {
  bar: bool,
  biz: bool,
};
type _FooConstraint<F: {[key: FavoriteKey]: bool}> =
  EqualConstraint<FavoriteKey, $Keys<Foo>>;
const _fooWitness: _FooConstraint<Foo> = witness;

// With the new features, this would be:
constraint: $Typed<Foo, {[key: FavoriteKey]: bool}>;
constraint: $Equal<FavoriteKey, $Keys<Foo>>;
// or even just
type FooInline = $Constrain<{
    bar: bool,
    biz: bool,
  }, F,
  $Typed<F, {[key: FavoriteKey]: bool}>,
  $Equal<FavoriteKey, $Keys<F>>
>;
```

### Features
`$Specialize<Base, ...BaseWithSubtypes>` would be a utility type that allows for providing specialization information to the type checker. `Base` is any valid type, and each `BaseWithSubtypes` is another type of the same shape where each type that comprises the whole expression fulfils `$Subtype<T>` subtype of its respective type `T` in `Base`.

### Uses
Specialize allows for the anonymous, standalone expression of the type of a function that extracts from a record. It also allows for functions that transform types in ways that cannot be directly expressed in records (non-string keys) to have more expressive types.

### Examples
```javascript
const record = { foo: 42, bar: "biz" };
const getRecord: $Specialize<
  (string) => number | string,
  ("foo") => number,
  ("bar") => string
> = function(key: string) {
  return record[key];
};
const n: number = getRecord("foo");

// cannot be emulated with a map due to infinite domain & non-string keys
const nonString: $Specialize<
  (number | boolean) => number | boolean,
  (number) => boolean,
  (boolean) => number
> = function(in: integer | bool) {
  switch (typeof in) {
    case "integer": return in !== 0;
    case "boolean": return in ? 1 : 0;
  }
};

declare var Math {
  ...
  // This type cannot be expressed using a map,
  // as it is a declaration from an external library.
  abs: $Specialize<(x: number) => number, (n: integer) => natural>,
  ...
};
```

### Features
The first release of type-level operators would likely only include basic operations on `integer`s (`+`, `-` (unary & binary), `*`, `%`, comparison, equality, bitwise), `natural`s, and `boolean`s (`p ? t : f`, logical, equality). These operations would also work at compile-time on literal elements of this type. (Note that effective implementation would likely require some form of specialization (#2423?).)

### Examples
Examples:
```javascript
{a: ! true} ≡ {a: false}
type ThreeState = 0 | 1 | 2;
let advanceThreeState = function<TS: ThreeState>(s: TS): ((TS + 1) % 3) {
  return (s + 1) % 3;
};
```

### Features
Vector is a subtype of Array with type-level length. Their type would be `$Vector<T, Len>`, with sugar `[T; Len]`, where `Len` is a member of `natural`. They could be declared like tuples, or with a special syntax `[default; n]` that desugars to `[(default,)*n]` for easy initialization. Vector operations would be specializations of array operations, and support at least type-safe indexing, assignment, length (get & set), push, pop, (un)shift, & splice.

Range support may be desired to make some of this easier to deal with in the future.

### Uses
Type-level lengths, even without type-level operators, allow for safe declarations and accessing of arrays that are hardcoded. Type-level lengths with type-level operators would allow for a whole new realm of safety in code that relies on constants that influence program-wide behavior, like buffers & game engines.

### Examples
```javascript
let vec: [0; 5];
vec[4] === 0; // true
vec[5] === 0; // type error, 5 not in natural enum 0 | 1 | 2 | 3 | 4

vec.push(42);
vec[5] === 0; // false
vec = [0, 1, 2, 3, 4, 5];
vec.length = 3;
vec[2] === 1; // true
vec[3] === 2; // type error, 3 not in natural enum 0 | 1 | 2
```

**Comment by asolove** [comment]
I would be interested to hear if this is something the core Flow team is interested in doing or not.
