### ISSUE TITLE
Multiple arrays are not handled in dynamic type tests

### ISSUE THREAD

**Issue by wbecker** [facebook/flow#3047]
[Here](https://tryflow.org/?code=Y29uc3QgeDogbWl4ZWQgPSB7YTogW10sIGI6IFtdfSA7Cgpjb25zdCBhID0gW107CmNvbnN0IGIgPSBbXTsKCmlmICh4ICYmIHguYSAmJiBBcnJheS5pc0FycmF5KHguYSkgJiYgeC5iICYmIEFycmF5LmlzQXJyYXkoeC5iKSkgewogICAgeC5hLmZvckVhY2goKGFpOiBtaXhlZCkgPT4ge30pOwogICAgeC5iLmZvckVhY2goKGJpOiBtaXhlZCkgPT4ge30pOwp9) is an example: 

    const x: mixed = {a: [], b: []} ;
    const a = [];
    const b = [];

    if (x && x.a && Array.isArray(x.a) && x.b && Array.isArray(x.b)) {
        x.a.forEach((ai: mixed) => {});
        x.b.forEach((bi: mixed) => {});
    }

In this case, the first array is fine, but the second one is not. If only one array existed, this would not cause an issue.

The error given is `property 'b' Property cannot be accessed on mixed`

If an extra check is put around the second array, then it will work:

    const x: mixed = {a: [], b: []} ;
    const a = [];
    const b = [];

    if (x && x.a && Array.isArray(x.a) && x.b && Array.isArray(x.b)) {
        x.a.forEach((ai: mixed) => {});
        if (x.b && Array.isArray(x.b)) {
           x.b.forEach((bi: mixed) => {});
        }
    }

**Comment by jesseschalken** [comment]
This will be because as far as Flow knows `Array.prototype.forEach` could have acccess to the object referenced by `x` and assign something besides an array to `x.b`, invalidating the check that `x.b` is an array.

When doing type tests, pull the value you want to test into a local variable and test that. Since the variable is local, Flow knows calling other functions wont change it and the check will stick.

**Comment by wbecker** [comment]
Makes sense - tested it and this does work. 

        const x: mixed = {a: [], b: []} ;
        
        const aa = [];
        const bb = [];
        
        if (x && x.a && Array.isArray(x.a) && x.b && Array.isArray(x.b)) {
            const a = x.a;
            const b = x.b;
            a.forEach((ai: mixed) => {aa.push(ai)});
            b.forEach((bi: mixed) => {bb.push(bi)});
        }

However, it fails when I try to use object destructuring:
        
        if (x && x.a && Array.isArray(x.a) && x.b && Array.isArray(x.b)) {
            const {a, b} = x;
            a.forEach((ai: mixed) => {aa.push(ai)});
            b.forEach((bi: mixed) => {bb.push(bi)});
        }

The error given is property 'a' Property cannot be accessed on mixed. Is there a similar reason for this?

**Comment by wbecker** [comment]
Will close this and put the other in a top level issue.
