### ISSUE TITLE
Brew version old

### ISSUE THREAD

**Issue by seanhess** [facebook/flow#305]
I was following along here: http://flowtype.org/docs/getting-started.html#_

It implies that you can use brew to install the binary, but brew installs 0.1.0, where the current version is 0.4.0. I then installed vim-flow and it didn't work because of this. 

Can you update brew?

**Comment by gabelevi** [comment]
We have been keeping brew up to date, but I think your local copy might be a little old. Maybe you need to do `brew update`?
