### ISSUE TITLE
React HOC type checking doesn't seem to work the way I expect

### ISSUE THREAD

**Issue by davidswinegar** [facebook/flow#3053]
Posted on #flowtype but had some problems posting the example, and I suspect this is a feature request and not a usage problem, so posting again here.

I have a React higher order component, `addProps`, that wraps a react component and adds some additional props not passed in from the parent component. I want it to type-check so that the wrapped type is the intersection of the additional props and the props passed into the HOC. Or, to restate, so that any usages of the HOC type-check that the props passed in are the props required by the child component, minus the props already provided by the HOC.

You can try out the example below by pasting it into the flowtype try editor. If it works the way I want it to, this example should have an error, but it currently does not.
```
// @flow
const React = require('react');

function addProps<InputProps: {}, AdditionalProps: {}>(additionalProps: AdditionalProps):
    (component: ReactClass<InputProps & AdditionalProps>) => ReactClass<InputProps> {
  return (component: ReactClass<InputProps & AdditionalProps>): ReactClass<InputProps> => {
    const componentName = component.displayName || component.name;
    class MapPropsWrapper extends React.Component {
      props: InputProps;

      render() {
        return React.createElement(component, Object.assign({}, this.props, additionalProps));
      }
    }

    return MapPropsWrapper;
  };
}

class test extends React.Component {
  props: {a: string, b: string}

  render() {
    return <div>{this.props.a} {this.props.b}</div>;
  }
}

const testHOC = addProps({a: 'hello'})(test);

class test3 extends React.Component {
  props: {b: string}
  render() {
    // should error - 'b' is not passed in.
    return <testHOC />;
  }
}
```

**Comment by gcanti** [comment]
- always use capitalised names for components (**no type checking** otherwise)
- do not use `ReactClass` (is buggy https://github.com/facebook/flow/issues/2159#issuecomment-236099652)

Example

```js
type ClassComponent<P> = React$Component<void, P, void>;

function addProps<InputProps: {}, AdditionalProps: {}>(additionalProps: AdditionalProps): (component: Class<ClassComponent<InputProps & AdditionalProps>>) => Class<ClassComponent<InputProps>> {
  return (component) => {
    class MapPropsWrapper extends React.Component {
      props: InputProps;

      render() {
        return React.createElement(component, Object.assign({}, this.props, additionalProps))
      }
    }

    return MapPropsWrapper
  }
}

class Test extends React.Component {
  props: {a: string, b: string}
  render() {
    return <div>{this.props.a} {this.props.b}</div>
  }
}

const TestHOC = addProps({a: 'hello'})(Test)

class Test3 extends React.Component {
  props: {b: string}
  render() {
    return <TestHOC /> // <= error
  }
}
```

**Comment by davidswinegar** [comment]
@gcanti thanks for the info about `ReactClass` and the info about capitalized names. I'm curious - why was that decision about capitalized names made? It seems unintuitive given that Flow should be able to discern the types regardless of capitalization, and it makes it difficult to add Flow incrementally to my project since I have many HOCs that start with a lowercase letter. 

There's another problem I have with this - if you add `b={this.props.b}` to `Test3.render` it still throws an error, even though the usage is now correct!

**Comment by gcanti** [comment]
> There's another problem I have with this

Can't [reproduce](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdyuAnhkaAMLQkDO-bjSwA7IqNwAeAAoA+UAF5CTXABJhmWOMlSAbrBQATADSgZZg8bkBuZJACuoiim2gSRozOoZ+UgJKiGA643rC+AFygAN4AvmYAgp4ouK6iJNBhkTGxcgAUHkYpaRlZ-FFJRanapT78AJRReWQi2hK4UbwCfl2CmmLtAUEhZaAAZKCVxTWZdXJy9UoKvT18fa060oHBoXMK0YigoIy4DtiioM0b7YuK+4dHoGRr-KAAsiQYZQDq2J+c2FARAAHrgJEZXsRyLgAHT9NqSGIPR6gDB1KLbEZ1OzIx6MURGIjYPKLA4olEnM4XKEUGFkRgkMEAUWgRDQ7SuWk2ZgA8gAjABWRFp3RQAHNRHk4mZcAALFD8GFo8L8MyFabpWYq+r1XFHWK4g24ynnd6fH5-DAAh4Go3PbqgAAqRH4+BBYIJkNUcOuiLJqPRMRIUVd2BQojFZj5IdwYYjBqO+MJxNJxqIp1NUiKejk0TlCqVdRhJFiMXziuVvhhfNiUmA2bkNsQdu0rqdLtwAAkedwlO5PGUpcH6LKiNA4HRYvU8s7XbrEPbBO3XQBmIGg8Fe6E+rntJFHSvlGLR0Ch8NihPHcFEkn7vHpqmgKSzrs90B8xR5+UVos10DARt9WbRAgA)

**Comment by davidswinegar** [comment]
@gcanti hmm, this is really quite weird. I added
`const React = require('react');` at the top of your example instead of an ES6 import for that flowtype and it throws an error, as I saw earlier, but does not error when using the ES6 import. Any reason the behavior would be different? For background, we do use AMD imports in our project for the time being.

**Comment by davidswinegar** [comment]
Closing to open more specific issues
