### ISSUE TITLE
Implement interface

### ISSUE THREAD

**Issue by villesau** [facebook/flow#3057]
AFAIK there is couple of very hackish ways to 'implement' an interface: http://stackoverflow.com/questions/38223511/how-to-declare-that-a-given-class-implements-an-interface-in-facebook-flow so there clearly already are most bits and pieces on place.

I'd really like to see a real support for implementing an interface so that i get errors and coding assistance etc when writing the class it self, not just when using it and it's lacking something. It would also clearly declare on class level that the class is supposed to satisfy certain interface which also documents better the purpose of the class. something like: class MyClass implements MyInterface {}

**Comment by vkurchatkin** [comment]
Duolicate of https://github.com/facebook/flow/issues/2376
