### ISSUE TITLE
Introduce new type DOMEventTarget and use it to replace type EventTarget in SyntheticEvent

### ISSUE THREAD

**Issue by singhshashi** [facebook/flow#3058]
In the flow-type definitions of SyntheticEvent, the properties currentTarget and target are defined as type EventTarget

```
declare class SyntheticEvent {
    bubbles: boolean;
    cancelable: boolean;
    currentTarget: EventTarget;
    defaultPrevented: boolean;
    eventPhase: number;
    isDefaultPrevented(): boolean;
    isPropagationStopped(): boolean;
    isTrusted: boolean;
    nativeEvent: Event;
    preventDefault(): void;
    stopPropagation(): void;
    +target: EventTarget;
    timeStamp: number;
    type: string;
    persist(): void;
}
```
https://github.com/facebook/flow/blob/39f8e3e9433b7220db9b8066cc74addbceeea9ed/lib/react.js#L277

However, if I look at react SyntheticEvent, it says the attributes currentTarget and target are of type DOMEventTarget. 
```

boolean bubbles
boolean cancelable
DOMEventTarget currentTarget
boolean defaultPrevented
number eventPhase
boolean isTrusted
DOMEvent nativeEvent
void preventDefault()
boolean isDefaultPrevented()
void stopPropagation()
boolean isPropagationStopped()
DOMEventTarget target
number timeStamp
string type
```
https://facebook.github.io/react/docs/events.html

In fact, I just noticed that the nativeEvent attribute is defined as a DOMEvent in reactjs docs, but as an Event in flow. 

By defining the target and currentTarget as type EventTarget,  DOM attributes such as id and class are not detected by flow and it throws an error. e.g. 

```
handleClick(evt: SyntheticEvent) {
    const selectedTaskId = evt.currentTarget.id.split('*')[1];
    dispatch({type: 'viewtask', selectedTaskId: selectedTaskId })
  } 

```

gives the flow error

```
16:     const selectedTaskId = evt.currentTarget.id.split('*')[1];
                                                 ^^ property `id`. Property not found in
16:     const selectedTaskId = evt.currentTarget.id.split('*')[1];
                               ^^^^^^^^^^^^^^^^^ EventTarget

```

Perhaps, the correct thing to do would be to introduce a DOMEvent and DOMEventTarget and use these so that DOM attributes like id are detected?

**Comment by RusAlex** [comment]
Also met this today

**Comment by RusAlex** [comment]
Please see the fix is here: https://github.com/facebook/flow/issues/218

**Comment by singhshashi** [comment]
After upgrading flow and referring to the docs at https://flow.org/en/docs/react/events/ I was able to correctly use this.
