### ISSUE TITLE
boolean fields are unchecked

### ISSUE THREAD

**Issue by gcanti** [facebook/flow#306]
```js
/* @flow */

var x: {a: boolean;} = {a: 'str'};

// no errors!
```

**Comment by samwgoldman** [comment]
This is the intended behavior. There exists a subtyping relationship `string < boolean`, which is useful because strings are "truthy" in JavaScript and can be used in `if` statements & everywhere booleans are used.

**Comment by samwgoldman** [comment]
Actually, empty strings are falsey and non-empty strings are truthy. Fun!

**Comment by gcanti** [comment]
I see! However usually the idiomatic way to use this subtyping in JavaScript, as you said, is when you use a `if` statement (or equivalent)

```
var x = "str";
if (x) {
  ...
}
```

It's a little bit unexpected for an object field, don't you think?
(For reference TypeScript issues an error: `Type 'string' is not assignable to type 'boolean'`)

**Comment by samwgoldman** [comment]
I'm not an expert, but I don't believe flow distinguishes between what types can flow into an object property vs a local variable. To be honest, I'm not sure that it should, although this subtyping-reflects-implicit-casting rule has come up before as an issue.

It seems that you would prefer only the exact values "true" and "false" to flow into a boolean type, but what is your use case that demands this? Do you expect a boolean-annotated field to print as "true" or "false"? If so, you can change the type from `boolean` to `Boolean` and pass in a the wrapped object which will print correctly.

**Comment by gcanti** [comment]
I'm writing a definition file for reflux's `createAction` API, I just want to rely on `boolean = {true, false}`.
Say you have an API like this:

```
declare function redButton(options: {startThermonuclearWar: boolean; unimportantDescription?: string;}): any;
```

and I mistakenly write something like this:

```
redButton({startThermonuclearWar: 'mydescription'})
```

For Flow it's everything ok, that means I can't rely on static type checking in this case.

**Comment by samwgoldman** [comment]
It really depends on how `options.startThermonuclearWar` is used. Flow takes the stance that "mydescription" _is_ a boolean, because JavaScript will treat it like one. Whether you can "rely" on static type checking is a matter of opinion here. Without flow, passing "mydescription" would do the same thing.

**Comment by samwgoldman** [comment]
Consider some unannotated code:

```javascript
function cond(x) {
  if (x) {
    return "true";
  } else {
    return "false";
  }
}
```

Flow infers the type of `x` to be `boolean`. It legal and valid to pass a string into `cond` so it must follow that `string < boolean`.

**Comment by gcanti** [comment]
> is a matter of opinion here

Sure. My opinion: "mydescription" will be "coerced" to a boolean at **runtime**, however I expect the **static** type `boolean` to have just `{true, false}` values. I think it's the reason why TypeScript issues an error (but I might be wrong :)

**Comment by samwgoldman** [comment]
TypeScript might seem smarter here, but flow does _way_ more type inference, which contributes to the different semantics. For example, TypeScript does not infer the type of `x` in the example above, and just treats it as `any`.

It's possible that flow is taking the wrong approach here, and should distinguish between `boolean` and `boolean-compatible` types, such that `x` would type as `boolean-compatible`, `string < boolean-compatible`, but `string <> boolean`.

I wonder what the core team thinks.

**Comment by jeffmo** [comment]
This does indeed seem surprising at first glance. cc @mroch who's been thinking about boolean refinements stuff...

Would it be possible to interpret truthiness without a subtyping relationship (and only in explicit refinement positions)?

**Comment by samwgoldman** [comment]
The behavior for booleans changed in 0.10.0, so now this works how @gcanti expects.

**Comment by mroch** [comment]
yep, let me know if this ends up causing more issues than it solves, but I think it'll help. perhaps we need a `boolean-compatible` type (I like to call it `booly`), but everything is booly so we didn't add one. for things like `Array.prototype.filter` which casts the callback's result to bool, we changed the expected return type to `any` instead.

thanks guys :)
