### ISSUE TITLE
Nested Polymorphism?

### ISSUE THREAD

**Issue by vejersele** [facebook/flow#3060]
I'm trying to add types to a function that is similar to react-redux's connect function. It is mostly working but the main problem is that I'm not able to get the resulting `WrappedComponent` to type check.

here's the connect function:

```
export default function connect<Props: {}, InnerProps: {}>(
    toProps: (props: Props) => InnerProps
): (ComponentToWrap: (props: InnerProps) => Element<*>) => Class<Component<*, Props, *>> {

    return (ComponentToWrap) => {

        return class extends Component {

            state: InnerProps;

            props: Props;

            constructor(props: Props) {
                super(props);
                this.state = toProps(props);
            }

            render() {
                return <ComponentToWrap {...this.state} />;
            }
        };
    };
}
```

Usage:

```
function TestComponent (props: {name: string}) {
    return <div>{props.name}</div>
} 

function toProps(props: {firstName: string, lastName: string}) {
    return {
        name: props.firstName + ' ' + props.lastName
    }
}

const MyWrappedComponent = connect(toProps)(TestComponent);

<MyWrappedComponent/> // should give an error since firstName and lastName are missing
```

Ideally I would like that flow checks the properties of `MyWrappedComponent` based on the type signature of the toProps function. Not sure if that's possible though ...

A full example can be found [here](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3gMKyawB2RzVoAotEWm7gF9QkbI1ABybKQriA3MiIAPLHlAATIpBIBXaPkjbmFFC1BkWrCgB4ACqIwBnAFy0B1AJLNW2O7EcuaAQA+AApEUAjQXFhff1AQjHtnUFiHAEpQAF4g0E9vVMQ0lxCGJlZ2ABVYAHVsEgxixL9kvKIfJIzsrh4+disAKiDOnLpoEgcHK1KsctwB6lTqQZyaZEjQKVxtbGZ46ZZ+Ktr64do19cjN7d2yMYnQJVw2NQdQfdmz8Ivvh1wSJ5crXazXkX2+6yacVSoPBF3MzF+2G0FBwCSSLlSGVWsNhDm0GDaaOaaXkOPBuAAFigHAA6X7-IhZKIxJJExwksE4gTnMlSZgabAhLGcskRK47UBTRgzQ41OoYWg0pWU6l0v5PITAIKk0Xc2ECHURA2IbmIAxGXAmXYVIi-d78eKQ5I0ZgkPguREoZgAcwEwvW4t2VjUKAAbkEaE6aa6+AIrMAQ+GTaBkObjKZoqk2c7IChsL8AHJuoge3DYL3e6h3XBF92gT0+v1nANELYS7HgmMl0BR3P5mvF0AAagko5HUertaInO5pvhv1AAFkAJ7HDAEtT29hM+GWXAhTMdEI2u3Sg7sDmIKwrtcbre4LVAA)

I was hoping that someone could give me some feedback on what I'm doing wrong here.

Thanks!

**Comment by vejersele** [comment]
This issue can be closed. Turns out I needed to specify the defaultProps type param of the WrappedComponent as `void` instead of *, which makes sense. 

[working solution](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3gMKyawB2RzVoAotEWm7gF9QkbI1ABybKQriA3MiIAPLHlAATIpBIBXaPkjbmFFC1BkWrCgB4ACqIwBnAFy0B1AJLNW2O7EcuaAQA+AApEUAjQXFhff1AQjHtnUFiHAEpQAF4g0E9vVMQ0lxCGJlZ2ABVYAHVsEgxixL9kvKIfJIzsrh4+disAKiDOnLpoEgcHK1KsctwrADdYFDVqVOpBnJpkSNApXG1sZnjpln4q2vrh2m2dyL2Do7IxidAlXDY1B1AT2evw24BDlwJHeLla7Wa8n+AJ2TTiqShMNu5mYQOw2goOASSRcqQyWyRSIc2gwbWxzTS8kJMNwAAsUA4AHRAkFELJRGJJcmOSnQwkCG7UqTMDTYEL4vnUiL3Q6gKaMGZnGp1DC0RnqukM5nA95CYBBKlSgVIgSGiKmxACxAGIy4ExHCpEIE-fjxOHJGjMEh8FxolDMADmAglOxlRysahQ8yCNHdjK9fAEVmAkejltAyBtxlM0VS3I9kBQ2CBADlvURfbhsP6A9Rnrgyz7QH7A8HrqGiPtZQSYQmK6A44Xiw3y6AANQSScTuP1xtEPkCq0ooGgACyAE8LhhSWoXex2SjLLgQrmOiFHc6Fad2LzEFYN1ud3vcPqgA)

**Comment by asolove** [comment]
This can be closed. (/cc @calebmer)
