### ISSUE TITLE
Using intersection type for inheritance doesn't refine nullability.

### ISSUE THREAD

**Issue by drarmstr** [facebook/flow#3063]
Let's say I have a base type:

  type A = {
    foo?: number,
    bar: number,
  };

I'd like to inherit from this type to extend it and refine the types.  With TypeScript I could extend the type and refine the `foo` member to be required.  Flow doesn't offer extending, but my understanding is that intersection types are supposed to be used for this pattern.  For example, to add the `baz` member and refine the `foo` member:

  type B = A & {
    foo: number,
    baz: number,
  };

Based on the definition of union types, this doesn't work because nullable and non-nullable `foo` aren't compatible.  This makes sense.  However, given that, is there a supported mechanism to "extend" types and refine members to be required in Flow?

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/1326

Intersection only work properly when there are no properties with the same name on both branches
