### ISSUE TITLE
Question: exposing types to consumers

### ISSUE THREAD

**Issue by alexreardon** [facebook/flow#3064]
Hi there,

I have recently converted a [library I maintain](https://github.com/alexreardon/raf-stub) to use flow. However, when I use it in a project flow does not pick up the annotations. What is the recommended way of publishing my types so that consumers can use them? Ideally it would just use the rules in the source code. 

Cheers

**Comment by gcanti** [comment]
I'm using [flow-copy-source](https://github.com/AgentME/flow-copy-source)

**Comment by ryyppy** [comment]
I recently wrote an article about this topic (shameless plot):
https://medium.com/@ryyppy/shipping-flowtype-definitions-in-npm-packages-c987917efb65#.xqu48dx45

**Comment by alexreardon** [comment]
Living the dream: somebody has already solved the problem and written a blog about it!
Thanks @gcanti and @ryyppy!!

I will give it a crack now

**Comment by alexreardon** [comment]
It worked well! Cheers
