### ISSUE TITLE
Maybe type inside callback

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/flow#3066]
Maybe it's for the reason I don't understand or `flow` just can't infer it:

```js
type Args = {
  values: Array<number>,
  item: ?{ id: number },
};

const func = ({ values, item }: Args) => 
  item && values.map(value => value === item.id);
                                            ^ property `id`. Property cannot be accessed on possibly null / undefined value

```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCATgOYDOYAvGAN6phgBuAhjAK57kBcRxxLLAB4AduwC2AIzzEAfABoGYAJYY843gH5aKgCa8xUmWAC+ikwG50AYzgjyGMFHYjr1MAAodrDl3kq1cVNeEgoASmpZAPUwADJY5jZOcgA6cRYcDx9OSMTfaioaVXUU5V0wiyA

**Comment by gcanti** [comment]
See https://github.com/facebook/flow/issues/2986#issuecomment-265952300

Fix

```js
const func = ({ values, item }: Args) => {
  const i = item
  i && values.map(value => value === i.id)
}
```

**Comment by alexfedoseev** [comment]
@gcanti Thanks!
