### ISSUE TITLE
Feature request: transitively include .flowconfig files

### ISSUE THREAD

**Issue by ide** [facebook/flow#308]
When your project includes a dependency that defines its own flowconfig file (for example, React Native), currently Flow doesn't import the dependency's flowconfig. This is a feature request for Flow  to automatically import the flowconfig files of dependencies.

I believe there are at least two ways dependency can be specified:
- It lives in a subdirectory such as `node_modules`
- It lives in some other directory but is included under the `[include]` section of .flowconfig

In either case Flow would have to smartly resolve the paths within each flow config it finds.

**Comment by frantic** [comment]
+1

**Comment by bhosmer** [comment]
@ide @frantic the issue with automatically doing this is that there are situations where a parent and child project will both use the child project's tree, *in different ways* (@frantic e.g. our situation in the in-house repo). An explicit import is a possibility though. Will update as events warrant.

**Comment by sahrens** [comment]
@bhosmer Any updates here?

**Comment by nmn** [comment]
Duplicate of  #238
