### ISSUE TITLE
Disjoint union with differing tag types

### ISSUE THREAD

**Issue by lrowe** [facebook/flow#3080]
The JSON data model I work with is a nested structure made up of branch nodes and leaf nodes which are disambiguated based on the existence of a $type key, e.g.:
```
{ "a": { "b": { "$type": "leaf" } } }
```
I'd like to model this using Flow, but tagged unions seem to require that the distinct tags are of the same type, e.g.:
```
// @flow
type MyNode = MyLeaf | MyBranch
type MyLeaf = { $type: 'leaf' };
type MyBranch = { $type: ?null, [key:string]: ?MyNode };

function isLeaf(node: MyNode): ?MyLeaf {
    if (node.$type === 'leaf') {
        return node;
    }
}
```
Flow 0.37.4 gives the following error:
```
$ node_modules/.bin/flow check-contents < example-flow.js 
-:3
  3: type MyLeaf = { $type: 'leaf' };
                            ^^^^^^ string literal `leaf`. This type is incompatible with
  4: type MyBranch = { $type: ?null, [key:string]: ?MyNode };
                               ^^^^ null

-:4
  4: type MyBranch = { $type: ?null, [key:string]: ?MyNode };
                               ^^^^ null. This type is incompatible with
  3: type MyLeaf = { $type: 'leaf' };
                            ^^^^^^ string literal `leaf`

-:4
  4: type MyBranch = { $type: ?null, [key:string]: ?MyNode };
                               ^^^^ undefined. This type is incompatible with
  3: type MyLeaf = { $type: 'leaf' };
                            ^^^^^^ string literal `leaf`


Found 3 errors
```
On the face of it, this limitation doesn't seem inherent when disambiguating using switch statements or strict equality checks.

TypeScript 2.1.4 (running `tsc --strictNullChecks example-typescript.ts`) does seem able to support this case:
```
type MyNode = MyLeaf | MyBranch;
type MyLeaf = { $type: "leaf" };
type MyBranch = { $type: undefined, [keys: string]: MyNode | undefined};

function isLeaf(node: MyNode): MyLeaf | undefined {
    if (node.$type === "leaf") {
        return node;
    }
}
```

(Edited to better reflect a real use case and add TypeScript equivalent.)

**Comment by mroch** [comment]
This should be fixed in master (https://github.com/facebook/flow/commit/edba20c11c0054794f3988ec15c4e5d7c9511594). You can try it in Try Flow by changing the version selector. Let me know if it doesn't work!

**Comment by mroch** [comment]
Actually null and void aren't supported in these prop tests in master yet. I have a diff in progress to fix that, didn't land it yet. But should make 0.38 regardless.

**Comment by lrowe** [comment]
This is now working in master!

**Comment by lrowe** [comment]
To update my example, I've found the following approach to work best:
```js
// @flow
type MyNode = MyLeaf | MyBranch
type MyLeaf = { $type: 'leaf' };
type MyBranch = { $type?: empty, [key:string]: MyNode };
```

Specifying `$type?: empty` seems preferable to `$type: void` since it disallows undefined values, making the type compatible with a covariant json type:

```js
type Primitive = string | number | boolean | null;
type ConstJsonValue =
  | Primitive
  | ConstJsonMap
  | $ReadOnlyArray<ConstJsonValue>;
type ConstJsonMap = { +[key: string]: ConstJsonValue };

declare function jsonArg(val: ConstJsonValue): void;
declare var node: Node;
jsonArg(node);
```
