### ISSUE TITLE
flowtype.org/try fails with "too much recursion" in Firefox

### ISSUE THREAD

**Issue by happylynx** [facebook/flow#3083]
The web playground [flowtype.org/try](https://flowtype.org/try) is too slow. It takes about 10s to reach 'load' event on Chrome, it fails with

```
too much recursion flow.js:66:44
```

on Firefox Nightly and completely freezes the browser for several seconds without reaching the 'load' event and without any message in browser console in current Firefox.

Environment:
Chrome 55.0
Firefox 50.0
Firefox Nightly 53
OS Linux x64
flowtype.org/try 0.37.4

**Comment by mrkev** [comment]
Is this still an issue?

**Comment by Brianzchen** [comment]
Closing, abandoned and stale issue
