### ISSUE TITLE
Possible false positive when checking for undefined property

### ISSUE THREAD

**Issue by doberkofler** [facebook/flow#3087]
The following example report an error when using flowtype 0.37.4 and I do not understand why flowtype assumes that after invoking output1 the property `name` might again be undefined. 
```
// @flow

type objectType = {
	name?: string
}

function func(obj: objectType) {
	if (typeof obj.name === 'string') {
		output1(obj.name);
		output2(obj.name);
	}
}

function output1(s: string) {
	console.log(s);
}

function output2(s: string) {
	console.log(s);
}
```

error message:
```
index.js:10
 10:            output2(obj.name);
                        ^^^^^^^^ undefined. This type is incompatible with the expected param type of
 18: function output2(s: string) {
                         ^^^^^^ string
```

[Try flow](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1LARgFZYDGKAKpjgLygDeiAkAHYCGAtlgPwBcoAzigBOASyYBzRAF9kkAK5NSw2E1ByFACnwFeWkuUoBKOo2GRQ69NlhmtAOlYdQVZ6ADkAkeNdH6DBrFkUDECARk1Ce3YsAwBuRn9A4JQAJnCCSI5YxmlpRDVFZVxE0PU+Xg9RMR9GYmU+WGgsWzgxUqzc-JQlFQCgwNSy-iFK6oZapnrG5thWvnbEIA)

**Comment by CodyReichert** [comment]
There's actually quite a few issues on this and the reason is the Flow is pessimistic and assumes that any other function calls may have mutated the variable. The fix is to assign it to a const first:

https://github.com/facebook/flow/issues/2877#issuecomment-262390960
