### ISSUE TITLE
flow not parsing global declarations in top-file comment

### ISSUE THREAD

**Issue by dasilvacontin** [facebook/flow#3090]
```js
// @flow
/* global requestAnimationFrame */
...
requestAnimationFrame(gameloop)
```

```sh
src/index.js:175
175: requestAnimationFrame(gameloop)
     ^^^^^^^^^^^^^^^^^^^^^ identifier `requestAnimationFrame`. Could not resolve name
```

Is this intended? Or a bug?

In case of it not being supported, is it because it's not a "standard" or?

Cheers!

**Comment by hufeng** [comment]
https://github.com/facebook/flow/blob/master/lib/dom.js#L2963
include requestAnimationFrame

**Comment by dasilvacontin** [comment]
@hufeng Can you show what you are suggesting? Is it a change on the flowconfig file?

**Comment by hufeng** [comment]
![image](https://cloud.githubusercontent.com/assets/533008/21590963/01c9b3be-d13b-11e6-9fd8-2994ebe072da.png)

use flow 0.37.3

**Comment by ryyppy** [comment]
If you can't  upgrade to flow `0.37.3` yet, you could just do this:

**Create a libdef file overriding / adding the requestAnimationFrame declaration:**
```
// flow-typed/override-dom.js

declare function requestAnimationFrame(callback: (timestamp: number) => void): number;
```

And make sure the  `.flowconfig` picks up the `flow-typed` directory:
```
[libs]
flow-typed
```

Restart flow and now you should have proper typings for `requestAnimationFrame`

**Comment by hufeng** [comment]
@ryyppy cool!

**Comment by joncursi** [comment]
Is it possible to declare an object? Another global that exhibits this same behavior in Flow is `Intl` but its an object rather than a function.

**Comment by joncursi** [comment]
```
declare var Intl: Object
```

seems to do the trick!
