### ISSUE TITLE
Constants for file access modes in 'fs' module still unknown to Flow

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/flow#3094]
node.js module "fs" constants like `fs.constants.R_OK` or ` fs.constants.W_OK` were added with https://github.com/facebook/flow/pull/1466 and I can see they are in the declaration file for node.js,

However, I get (from Flow 0.37.4)

```
lib/storage-base-nodejs.js:417
417:         fs.access(filename, fs.constants.R_OK | fs.constants.W_OK, (err: ?ErrnoError) => {
                                    ^^^^^^^^^ property `constants`. Property not found in
417:         fs.access(filename, fs.constants.R_OK | fs.constants.W_OK, (err: ?ErrnoError) => {
                                 ^^ module `fs`

lib/storage-base-nodejs.js:417
417:         fs.access(filename, fs.constants.R_OK | fs.constants.W_OK, (err: ?ErrnoError) => {
                                                        ^^^^^^^^^ property `constants`. Property not found in
417:         fs.access(filename, fs.constants.R_OK | fs.constants.W_OK, (err: ?ErrnoError) => {
                                                     ^^ module `fs`


Found 2 errors
```

**Comment by WhyEvenTry** [comment]
**I checked the binary!** I have flow v0.37.4 - and **the definitions are MISSING!**

I can see how it's supposed to look like here: https://github.com/facebook/flow/blob/master/lib/node.js#L850

But in the binary the last definition for module "fs" is a line `declare var X_OK: number;`.

**Comment by mroch** [comment]
actually #1466 added `fs.R_OK` and friends, not `fs.constants.R_OK`. the latter were added in c2baeb20ba64e16178e9691e1fcbd16db20086ac, which is in master but not 0.37. you can see the 0.37 release branch here: https://github.com/facebook/flow/tree/v0.37

`fs.constants` will be in 0.38 though!
