### ISSUE TITLE
Circular type imports for classes throws: TestClass:  This type is incompatible with 'TestClass'

### ISSUE THREAD

**Issue by ivome** [facebook/flow#3096]
I have an issue with circular type imports. 
Given the following two files: 

```js
// context.js
/* flow */
import {
  myExecutionHandler
} from './handler';

// The following line throws error: TestContext:  This type is incompatible with 'TestContext'
// This can also not be silenced with $FlowFixMe: It says unused suppression in that case
export class TestContext {
  execute(): void {
    return myExecutionHandler(this); // If this line is removed / changed, the error disappears
  }
}
```

```js
// handler.js
/* flow */
import type {
  TestContext
} from './context';

export function myExecutionHandler(test: TestContext): void {
  // Do something with TestContext
  console.log(test);
}
```

If I put all the code in one file, flow does not complain. Am I missing something or are circular imports problematic? The fact that I cannot suppress that error with `$FlowFixMe` makes me think there is more to the problem. Any suggestions? 

I love this library btw! 👍

**Comment by krgeppert** [comment]
I am having the same problem.

`// @flow

import Bar from "./Bar";

class Foo {
  constructor(){
    const bar = new Bar(this);
  }
}

export default Foo;`

`//@flow

import Foo from "./Foo";

class Bar {
  constructor(foo: Foo){
  }
}

export default Bar;
`
