### ISSUE TITLE
Equivalent files with different errors. Removing unreferenced code reveals unrelated errors.

### ISSUE THREAD

**Issue by matthewoates** [facebook/flow#3097]
flow version 0.37.4

please see https://github.com/matthewoates/flow-issue

Copied from `flow-issue/README.md`

# Repro repo for strange flow behavior
**Flow version 0.37.4**

To reproduce issues, clone the repo and run `flow` in the top directory.

I discovered this issue during a refactor of a ~20K LoC web application. I stripped down all of the irrelevant code, and am unable to simplify this case further. I discovered a case where equivalent files generate different errors, which I believe should never be the case. I also discovered multiple cases where removing unreferenced code reveals new unrelated errors.

## Expected behavior:
Flow complains about line 9 of `js/NotificationBuilder.js` and line 9 of `js/NotificationBuilderCopy.js`, as they are equivalent files.

## Actuail behavior:
Flow only complains about line 9 of `js/NotificationBuilderCopy.js`

```
 ➤ flow
js/NotificationBuilderCopy.js:9
  9:         games[0] && games[0].wtfm8();
                                  ^^^^^ property `wtfm8`. Property not found in
  9:         games[0] && games[0].wtfm8();
                         ^^^^^^^^ Game


Found 1 error
```

I was unable to determine the root cause of this, but I found many instances of strange behavior:

- removing `Game.getActiveGames` causes new errors, even though `getActiveGames` is never referenced
- removing `import Promise from 'bluebird';` from `Game.js` causes a new error, even though `Promise` is never referenced
- removing `games = games.filter(() => true)` in `NotificationBuilder` reveals the error that should be reported

**Comment by STRML** [comment]
Anecdotally, I have seen behavior like this many times. It appears that Flow is throwing some kind of internal error and stopping parsing, but that error is not propagating to the top level and errors are simply suppressed.

In this case it appears to be the circular import (`type` or otherwise doesn't seem to matter) between `Game` and `NotificationBuilder`.

This also creates quite strange behavior in verbose mode. Running `flow check --verbose-indent 2> output.txt` spins indefinitely (and can fill up your disk!)

**Comment by matthewoates** [comment]
Something like that would definitely explain the wonky behavior here, however I can have flow detect additional errors after the line with the missed error:

```
/* @flow */

import Game from './Game';

export default class NotificationBuilder {
    static doWork(games: Array<Game>) {
        games = games.filter(() => true);
        
        games[0] && games[0].wtfm8();
        var x: number = 'ok there';
    }
}
/* @flow */

import Game from './Game';

export default class NotificationBuilder {
    static doWork(games: Array<Game>) {
        games = games.filter(() => true);
        
        games[0] && games[0].wtfm8(); // doesn't detect error
        var x: number = 'ok there'; // detects error
    }
}
```

I'm not familiar with the internals of flow, so I don't know if this eliminates your hypothesis or not.

**Comment by STRML** [comment]
I think this still fits the hypothesis - it seems that the circular dep effectively casts `Game` to `any`.

**Comment by STRML** [comment]
Another few datapoints:

Calling this in verbose mode as so:

```
flow check --verbose-indent --no-flowlib 2> output.txt
```

prevents the infinite loop but doesn't even resolve builtins like `Array`.

##### Interfaces

Interestingly, you can also use this syntax to redefine the Bluebird module:

```js
// @flow
declare module 'bluebird' {
  declare export default any;
}
```

The above doesn't change any errors. But strangely, this does (and therefore actually throws the correct error!):

```js
// @flow
declare module 'bluebird' {
  declare export default class Bluebird<T> {
    [key: string]: any;
  }
}
```
