### ISSUE TITLE
Incompatibility of URL and location in DOM defintion

### ISSUE THREAD

**Issue by rgbkrk** [facebook/flow#3098]
Example flow output:

```
src/epics/recipes.js:36
 36:         const url = new URL(`${RECIPE_URI}/${action.id}`, location);
                                                               ^^^^^^^^ Location. This type is incompatible with
1825:   constructor(url: string, base?: string | URL): void;
                                        ^^^^^^^^^^^^ union: string | URL. See lib: /private/tmp/flow/flowlib_32896b33/dom.js:1825
```

Should `Location` be a `URL` type?

**Comment by CodyReichert** [comment]
`Location` and `URL` are not the same, if I recall correctly. The type signature for the constructor is correct according to [mdn](https://developer.mozilla.org/en-US/docs/Web/API/URL/URL), it should take a `URL` or `string`. Location is [different](https://developer.mozilla.org/en-US/docs/Web/API/Location), but it will work if you give it a `URL`.
