### ISSUE TITLE
Support non-standard DOM properties

### ISSUE THREAD

**Issue by gaearon** [facebook/flow#31]
The following code

```javascript
function getInnerText(el: Element): string {
  return el.textContent || el.innerText || '';
}
```

outputs

```
getInnerText.js:5:28,39: property innerText
Property not found in .../lib/dom.js:272:1,299:1: Element

getInnerText.js:5:28,39: property innerText
Property not found in .../lib/dom.js:301:1,316:1: HTMLElement
```

Indeed, `innerText` is non-standard, but how do I get around this?

**Comment by mroch** [comment]
it wasn't possible at the time, but now you can downcast to `any`: `((el : any).innerText : string)`

I think the more general solution will be to let you extend the built-in types (#396) so you can add this property if you want to allow it, without allowing it in other environments.
