### ISSUE TITLE
Computed properties from imports

### ISSUE THREAD

**Issue by benderTheCrime** [facebook/flow#3100]
Hey all,

I'm using flow@0.36.0

I've read this issue: https://github.com/facebook/flow/issues/252 and I believe I've found a followup that should be considered.

It seems as though flow should be able to follow imports to validate computed properties. If I define a type ("type.js"):
```
export type objType = {|
    foo: string,
    bar: string,
|};
```
and then use this type in the following file ("index.js"):
```
import type { objType } from './type';
import { BAR } from './constant';

const obj: objType = {
    foo: 'foo',
    [BAR]: 'bar'
};
```
where "constant.js" is:
```
export const BAR = 'bar';
```

Flow throws an error. Obviously this case is generalized, but the error that is returned looks something like this:
```
flow/type.js:15
 15: export type objType = {|
                         ^ property `foo`. Property not found in
 15:     const obj = {
                               ^ object literal. See: lib/index.js:15
```

This seems like it is relatively feasible. If I define the const `BAR` instead in `index.js` there is no flow error thrown. If this value were not a constant I could understand that flow could not validate it in any way because there would be no guarantee that this value would be defined and equal to the type definition at runtime, but because the value is a constant export there is little room for error.

**Comment by benderTheCrime** [comment]
I just realized I messed up the formatting of the code snippets. Sorry about that. I've updated.

**Comment by cr0cK** [comment]
I'm using https://github.com/pauldijou/redux-act, and this lib provides actions that can be used directly as object keys in reducers and Flow raises this error .. :(

Any plan to support this?

**Comment by goodmind** [comment]
#252
