### ISSUE TITLE
Declare class and const cause name is already bound

### ISSUE THREAD

**Issue by lovedota** [facebook/flow#3103]
Hi guys

I have a code like this, and it causes. Because I am using ImmutableJS with Flow so that I need to make a type definitions for it. 

<img width="1440" alt="screen shot 2016-12-29 at 12 17 49 pm" src="https://cloud.githubusercontent.com/assets/417914/21537245/129f7f84-cdc1-11e6-81e0-9c5e0951ee52.png">

```
import Immutable from 'immutable';

declare class Todo {
  id: string;
  complete: boolean;
  text: string;

  constructor(data: {
    id: string;
    complete: boolean;
    text: string;
  }): void;

  set(key: 'id', value: string): Todo;
  set(key: 'complete', value: boolean): Todo;
  set(key: 'text', value: string): Todo;
}

// $FlowExpectedError: Intentional rebinding for flow.
const Todo = Immutable.Record({
  id: '',
  complete: false,
  text: '',
});

export default Todo;
```

**Comment by hufeng** [comment]
type definitions can define in a separate file. for example your source file named index.js, in the same directory create file named index.js.flow

```js
//@flow
import {Record} from 'immutable'


export default class Todo extends Record<{
  id: number;
  text: string;
  complete: boolean}> {
}
```
