### ISSUE TITLE
Issue not found when destructuring props in stateles React components

### ISSUE THREAD

**Issue by andreyluiz** [facebook/flow#3106]
I don't know if it is an issue or it is working as expected. 

But I wonder why in some cases flow shows issue for no annotation in destructured objects in stateless React components. There's an example of a component where the annotation is needed. Otherwise flow shows an issue:

```jsx
const DataRow = ({
  data,
  columns,
  onClick,
  onDelete
}) => (...);
```

Flow displays the error:

```
app/components/ui/DataRow.js:29
 29: const DataRow = ({
                      ^ destructuring. Missing annotation
```

It's okay for this case. But in certain components flow does not throw the error. An example:

```jsx
const HomeButton  = ({
  text,
  onClick
}) => (...);
```

For this component flow does not display errors.

Anyone knows why? For me, apparently, its exactly the same case.

Thank you.

**Comment by jesseschalken** [comment]
Can you provide an example that reproduces on https://flowtype.org/try/? Your first example shows no error when I copy and paste it there.

**Comment by andreyluiz** [comment]
Hmm. I tried the code in the try it editor and the first example shows no errors as well. Well, I'm not sure what to show you. But I will fill you in some screenshots. Look:

Here's my terminal in my project folder when I have no annotation:
![flow-error](https://cloud.githubusercontent.com/assets/1965897/21577097/9769a5b2-cf35-11e6-95da-97feaf337f9d.png)

In atom my linter screams as well:
![flow-atom](https://cloud.githubusercontent.com/assets/1965897/21577102/bdbf8812-cf35-11e6-8fd7-3d86f57842ea.png)

If I put the decorator:
![flow-terminal-noerrors](https://cloud.githubusercontent.com/assets/1965897/21577108/e67890e6-cf35-11e6-948c-fde19ecbce87.png)

In atom it disappears too:
![flow-atom-fixed](https://cloud.githubusercontent.com/assets/1965897/21577112/052d3456-cf36-11e6-9c1f-225d76c46db1.png)

In the case of the HomeButton, no issues are found with no decorator.
![atom-homebutton](https://cloud.githubusercontent.com/assets/1965897/21577115/4f7fdf0e-cf36-11e6-8d06-e55163576eab.png)

My `.flowconfig` is okay too:

```flow
[ignore]
.*/node_modules/fbjs/.*
.*/app/main.js
.*/app/dist/.*
.*/release/.*
.*/git/.*

[include]

[libs]

[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
esproposal.export_star_as=enable
module.name_mapper.extension='css' -> '<PROJECT_ROOT>/flow/CSSModule.js.flow'
module.name_mapper.extension='styl' -> '<PROJECT_ROOT>/flow/CSSModule.js.flow'
module.name_mapper.extension='png' -> '<PROJECT_ROOT>/flow/WebpackAsset.js.flow'
module.name_mapper.extension='jpg' -> '<PROJECT_ROOT>/flow/WebpackAsset.js.flow'
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
```

I know we could not simulate it, but I still wonder why this is happening in my case.

**Comment by wordyallen** [comment]
It happens when I export a functional component.

**Comment by asolove** [comment]
The type annotation is needed for the argument of any exported function. Pretty sure that's the only issue here and looks like flow is working as exoected. Let me know if that isn't the case and we can discuss further.
