### ISSUE TITLE
Flow doesn't recognize dynamic testing

### ISSUE THREAD

**Issue by thibaultdelor** [facebook/flow#3107]
For some reasons flow let me assign a string to a number, even when I checked dynamically the string.
Example
```javascript
//@flow

let my_var:any = JSON.parse('{"a":"bla"}');

class A {
	a:number;
	constructor(a:number) {
		this.a = a;
	}
}

function to_class(o:any):?A{
	if(typeof o ==="object" && typeof o.a === "string"){
		return new A(o.a);// <--- Expecting Flow to complain here...
	}
	return null;
}
console.log(to_class(my_var))
```

Flow doesn't complain while it is obvious I am assigning a string to a number...

(I am using the latest version of flow: version 0.37.4)

**Comment by jesseschalken** [comment]
The purpose of `any` is to opt out of type checking. If you want a type that can be anything but is still type checked, use `mixed`.

**Comment by thibaultdelor** [comment]
I learnt something today! :)

Thank you
