### ISSUE TITLE
String.prototype.split arity

### ISSUE THREAD

**Issue by EnoahNetzach** [facebook/flow#3108]
`String.prototype.split` can have 0 arity ([**@see**](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/split)).

Flow throws an error, instead:
```
105:   return contents
              ^ undefined (too few arguments, expected default/rest parameters). This type is incompatible with
261:     split(separator: string | RegExp, limit?: number): Array<string>;
                          ^^^^^^^^^^^^^^^ union: string | RegExp. See lib: /tmp/flow/flowlib_413f687/core.js:261
```

The first argument should be `separator?: string | RegExp` in [core.js#L306](https://github.com/facebook/flow/blob/6d6c350ed492afcdfa161a8e672f836d5754b533/lib/core.js#L306).

**Comment by mrkev** [comment]
This was solved
