### ISSUE TITLE
Implementation vs Declaration question

### ISSUE THREAD

**Issue by pastawoua** [facebook/flow#311]
How do you force using a declaration if both the declaration and implementation are found please? I'm using browserify to require jquery and the implementation in node_modules is picked up by flow before my declaration.

**Comment by avikchaudhuri** [comment]
You can try ignoring the implementation for now (by adding a [ignore] section to .flowconfig). In the future, we plan to look at the declaration and check the implementation against the declaration.

**Comment by samwgoldman** [comment]
@pastawoua Does using `[ignore]` solve your problem?
