### ISSUE TITLE
Dynamically set the tag in a disjoint union

### ISSUE THREAD

**Issue by AugustinLF** [facebook/flow#3111]
I couldn't find any other issue, but I'm struggling to describe the situation, so here's the [bin](https://flowtype.org/try/#0C4TwDgpgBAglC8UDeBnAXFA5AQ0wXwChRIoAhBZdLAI3yPGgHkK4AfMggYwHsA7FYFADmEYM0QAKKjkxR2mWgEoM4gHzICASABOogK7belPAG4CeIA).
```javascript
type A = {s: 'a'}
type B = {s: 'b'}
type O = A | B
const getO = (s: 'a' | 'b'): O => {
    return {s};
}
```
In this case, I want to create an object of a given disjoint union type, but the chosen object depends on another union `'a' | 'b'`. I don't see any reason for flow to error here, if I manually add an if/else and manually set the tag, [it works](https://flowtype.org/try/#0C4TwDgpgBAglC8UDeBnAXFA5AQ0wXwChRIoAhBZdLAI3yPGgHkK4AfMggYwHsA7FYFADmEYM0QAKKjkxR2mWgEoM4gHzICASACWAMyhSE8RDMVbNAJ1EBXC70oYZhTRAA2KCOavBb91I9pCPCA).

**Comment by vkurchatkin** [comment]
This is the expected behaviour, `{ s: 'a' | 'b' }` is not a subtype of `{ s: 'a' } | { s: 'b' }`. Consider the following:

```js
var a: A = {s: 'a'};
var b: O = a;
var c: { s: 'a' | 'b' } = b;
c.s = 'b'; // breaks a 
```

To produce an instance of a union type, you must produce an instance of one of its branches.

**Comment by AugustinLF** [comment]
Oh yes, you're right, this mutability matter gets me all the time :'( Thanks for the answer, I'll close that!
