### ISSUE TITLE
Flow infers union function types strangely.

### ISSUE THREAD

**Issue by weakish** [facebook/flow#3114]
`S | T` and `T | S` may bring different result when `S` and `T` are function types.

For example:

```js
/* @flow */
const f: (x: boolean) => number | (x: number) => boolean = (x) => typeof x === 'number' ? true : 0;
```

In the above code Flow thinks `true` is incompatible with `(x: boolean) => number`.

If we swap the types in the union annotation:

```js
/* @flow */
const f: (x: number) => boolean | (x: boolean) => number = (x) => typeof x === 'number' ? true : 0;
```

Now Flow thinks `0` is incompatible with `(x: number) => boolean`.

The expected behavior:

If Flow is really smart, it should inferred the function type correctly, and raises no errors.
If Flow is not smart, it should inferred the function type as `(x: any) => true | 0` like TypeScript.
(FYI, TypedRacket also inferred the above function as `(-> Any (U True Zero))`.)
The current inferred result is rather confusing.

**Comment by weakish** [comment]
Hmm, it seems that Flow only considers the first candidate of the union.

This passes the check without errors:

```js
/* @flow */
const f: (x: number) => boolean | (x: boolean) => number = (x: number) => true;
console.log(f(1))
```

This failed:

```js
const f: (x: boolean) => number | (x: number) => boolean = (x: number) => true
console.log(f(1))
```

**Comment by vkurchatkin** [comment]
@weakish this is because of precedence, this works:

```js
const f: ((x: boolean) => number) | ((x: number) => boolean) = (x: number) => true
```

**Comment by weakish** [comment]
@vkurchatkin

> this works

On which version?

On `https://flowtype.org/try/` (on both `master` and `0.37.4`):

```js
/* @flow */
const f: ((x: boolean) => number) | ((x: number) => boolean) = (x: number) => true
console.log(f(1))
3: console.log(f(1))
                 ^ number. This type is incompatible with the expected param type of
2: const f: ((x: boolean) => number) | ((x: number) => boolean) = (x: number) => true
                 ^ boolean
```

**Comment by vkurchatkin** [comment]
That's right, you can't really call this function, because there is no way to know which branch is it

**Comment by weakish** [comment]
@vkurchatkin Yes it should not know which branch is it. But `const f: (x: number) => boolean | (x: boolean) => number = (x: number) => true; console.log(f(1))` works. So Flow simply selects the first branch.

**Comment by vkurchatkin** [comment]
No, it doesn't. Once again, precedence:

```js
const f: ((x: number) => boolean) | ((x: boolean) => number) = (x: number) => true;
```

**Comment by weakish** [comment]
@vkurchatkin Thanks to point out this.

```
3: console.log(f(1))
                 ^ number. This type is incompatible with the expected param type of
2: const f: ((x: number) => boolean) | ((x: boolean) => number) = (x: number) => true;
                                            ^ boolean
```

It seems flow first try to match `1` against `number` (passed), then match `1` against `boolean` (failed), just as TypedRacket did.
