### ISSUE TITLE
React.findDOMNode doesn't exist in 0.5.0

### ISSUE THREAD

**Issue by oliverzheng** [facebook/flow#312]
I installed flow through brew, and got 0.5.0.

```
$> flow --version
Flow, a static type checker for JavaScript, version 0.5.0

$> flow

/Users/oliver/projects/howtocenterincss/js/components/RadioListComponent.js:25:11,34: call of method findDOMNode
Unknown global name

Found 1 error
```

From the looks of it, the 0.5.0 release should have the declaration in lib/react.js, but perhaps this wasn't included as part of the release? Where is the lib file locally so maybe I can compare the diff?

**Comment by avikchaudhuri** [comment]
This has been fixed.
