### ISSUE TITLE
[Feature request] Infer types across module boundaries

### ISSUE THREAD

**Issue by gcazaciuc** [facebook/flow#3123]
Currently there is a limitation in Flow requiring to annotate the module boundaries(eg exported functions).
This creates several disadvantages:
1. In many cases you need to type the same piece of data multiple times. Eg when you have a hierarchy of React components that just pass data from one to the other A->B->C-> .... . Each one needs to declare the same props types again and again
2. When code changes the update process is much more complicated as you have to update the typings in multiple places.
3. You have to use more extended syntax(eg import type etc) to get the code to be verified by Flow which seems slightly against the Flow idioms as a Javascript type checker.

I would like to ask if the module boundaries annotation requirements can be made optional and if Flow could infer the types based on usage across module boundaries.

**Comment by ajhyndman** [comment]
I'm of the understanding that this decision was made as a performance optimisation.  It would be pretty nice to have an explicit infer declaration.  Maybe using asterisk type signatures on module boundaries?

**Comment by nmn** [comment]
Just to chime in here, there is no reason you should have to type the same piece of data multiple times. You should always be able to import one type and extend it. However, there are some problems with object union types right now that are being worked on.

**Comment by vicapow** [comment]
Just for some perspective this would solve an issue I’m having with typing “shared redux reducers” where the full action union can’t be typed out in the reducer itself.

**Comment by TrySound** [comment]
@vicapow Action shouldn't be typed in reducer. According redux idea all reducers should use all actions, so you need to use union of all actions in reducers.

**Comment by vicapow** [comment]
@TrySound exactly but without the existential type there’s no way to define that union of all actions in a reducer shared across projects

**Comment by TrySound** [comment]
@vicapow Shared
```ts
export type Action1 = {};

const reducer1 = (state: State, action: Action1) => {};

import type { Action1 } from './project/actions';
type Action2 = {} | Action1;

const reducer2 = (state: State, action: Action2) => {};
```

**Comment by vicapow** [comment]
@TrySound for reducer1, it needs to be a union of all actions not just Action1

**Comment by SamChou19815** [comment]
This is explicitly out of scope since types-first rearchitecture.
