### ISSUE TITLE
Disjoint enums and spread operator - false incompatibility 

### ISSUE THREAD

**Issue by wbecker** [facebook/flow#3126]
[Here](https://tryflow.org/?code=dHlwZSBDb21iaW5lZCA9IHwgIkFBIiB8IGZhbHNlOwoKY29uc3QgeDogQ29tYmluZWQgPSAiQUEiOwpjb25zdCB5OiBDb21iaW5lZCA9IGZhbHNlOwoKdHlwZSBPTyA9IHtmb28/OiBDb21iaW5lZH07Cgpjb25zdCBvMTogT08gPSB7Zm9vOiAiQUEifQpjb25zdCBvMjogT08gPSB7Zm9vOiBmYWxzZX0KbzEuZm9vID0gbzIuZm9vOwoKY29uc3QgbzMgPSB7Zm9vOiBmYWxzZSwgLi4ubzF9Owpjb25zdCBvNCA9IHtmb286ICJBQSIsIC4uLm8xfTsKY29uc3QgbzUgPSB7Li4ubzEsIC4uLm8yfQo=) is an example.

```
type Combined = | "AA" | false;

const x: Combined = "AA"; // ok
const y: Combined = false;  // ok

type OO = {foo?: Combined};

const o1: OO = {foo: "AA"}; // ok
const o2: OO = {foo: false}; // ok
o1.foo = o2.foo; // ok

const o3 = {foo: false, ...o1}; //error: This type is incompatible with boolean
const o4 = {foo: "AA", ...o1}; //error: This type is incompatible with boolean
const o5 = {...o1, ...o2}; // ok
```

In this case, the disjoint enum works fine on individual variables, and fine when assigned normally to an object.

However, when using the spread operator it can't figure out how to combine them, but only if you have explicitly set a value (`o3` & `o4`). If you combine two objects using the spread operator without explicitly adding the value, it does work (`o5`)

**Comment by wbecker** [comment]
This may be a duplicate of https://github.com/facebook/flow/issues/1488

**Comment by wbecker** [comment]
As suggested by `o5`, this does work however:

```
const o3 = {...{foo: false}, ...o1};
const o4 = {...{foo: "AA"}, ...o1};
```

**Comment by villesau** [comment]
This fixes the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
