### ISSUE TITLE
Can't use `static` as an object key

### ISSUE THREAD

**Issue by markandrus** [facebook/flow#3129]
Hi,

My issue appears very similar to #829. I'd like to type the [webidl2.js](https://github.com/w3c/webidl2.js) AST. Some of the AST nodes include a `static` property. When I try to type this with Flow, e.g.

```js
declare interface IDLMember {
  static: boolean;
  // additional properties elided
};
```

I get the following error.

```
$ flow check
Library parse error:
decls/idlmember.js:2
  3:   static: boolean;
       ^^^^^^ Use of future reserved word in strict mode

Found 1 error
```

Moreover, disabling `module.use_strict` does not appear to have any affect.

**Comment by loyd** [comment]
Similar problems with babel and babylon.
