### ISSUE TITLE
Flow server fails to start - Unhandled exception "create_process"

### ISSUE THREAD

**Issue by alturium** [facebook/flow#3137]
OS: win 7 64-bit
Flow version: 0.37.0
npm:  3.10.10
node:  7.2.1

IMPORTANT:  I do not have admin rights or privileges on this machine!  I am wondering if the flow server requires admin privileges.

Steps to re-create the problem (from windows cmd window)
1. installed flow >npm i -g flow-bin
2. >flow init
3. >flow 
   Could not start Flow Server!
4. >flow start  OR >flow server
Unhandled exception: Unix.Unix_error(1, "create_process", "c:\\Users\\myusername\\AppData\\Roaming\\npm\\node_modules\\flow-bin\\flow-win64-v0.37
.0\\flow.exe")

Thanks for looking into this issue!

**Comment by mrkev** [comment]
Can @alturium or anyone else confirm if this is still an issue?

**Comment by SamChou19815** [comment]
This issue was likely fixed a while ago.
