### ISSUE TITLE
How to write declaration files containing React classes?

### ISSUE THREAD

**Issue by gcanti** [facebook/flow#314]
I'm trying to write a declaration file for react-bootstrap, it's not clear how I should use `ReactClass<A, P, S>` from `lib/react.js`:

```js
/* @flow */

var React = require('react');

type ReactBootstrapStyle = "success"
  | "info"
  | "warning"
  | "danger";

type ReactBootstrapSize = "lg"
  | "md"
  | "sm"
  | "xs";

type ReactBootstrapAlertProps = {
  bsStyle: ReactBootstrapStyle;
  bsSize?: ReactBootstrapSize;
  onDismiss?: Function;
  dismissAfter?: number;
};

declare var Alert: ReactClass<any, ReactBootstrapAlertProps, any>;

// this works:
<Alert bsStyle="wrong" />; // error: string literal wrong Property not found in string literal type
```

if I write:

```
// this doesn't works
<Alert />; // no errors, bsStyle should be required
```

there are no errors. What I'm supposed to do to enforce the correct type checking?

**Comment by samwgoldman** [comment]
The type parameters to ReactClass et al are not in a usable state right now and the current situation is going to change. The best path forward right now is to use `React.createClass` with `propTypes`. Note that the `oneOf` propType will now properly type check if provided only string literals (#295), but optional propTypes are currently broken (#302).

As an aside, I know that facebook has been discussing the plan for typed React components internally, but currently none of that information has been shared with the community. I would really appreciate if these discussions were documented and shared somewhere.

**Comment by avikchaudhuri** [comment]
@samwgoldman Please bear with us while we bring the new React ES6 model up to speed while preserving  some of the type checking with React.createClass and propTypes. Things should become better in the new release or so, and we'll do a blog post discussing the changes.

**Comment by avikchaudhuri** [comment]
@gcanti you could try the following instead of the line `declare var Alert: ReactClass<any, ReactBootstrapAlertProps, any>;`:

```
declare class Alert extends ReactComponent {
  static defaultProps: { };
  props: ReactBootstrapAlertProps;
  state: any;
}
```

Now you should see both errors.

**Comment by samwgoldman** [comment]
@gcanti Does the hint above about using `ReactComponent` solve your problem?

**Comment by sgronblo** [comment]
Was there ever a "blog post discussing the changes" for this? We are trying to apply Flow to a project that uses react-css-modules and I am trying to hack together some declarations that would make Flow handle the use of CSSModules correctly.
