### ISSUE TITLE
flow check-contents --all parameter redundant

### ISSUE THREAD

**Issue by drabinowitz** [facebook/flow#3141]
produced on flow version 0.37.4
according to the docs `--all` causes `flow check-contents` to `Ignore absence of an @flow pragma`. To me this suggests that, without this flag, `flow check-contents` will ignore stdin missing the `/* @flow */` declaration. However, running `echo 'a = "str";a(5);' | flow check-contents` outputs:
```
-:1
  1: a = "str";a(5);
     ^ assignment of identifier `a`. Could not resolve name

-:1
  1: a = "str";a(5);
               ^^^^ function call. Function cannot be called on
  1: a = "str";a(5);
               ^ string
```
It's unclear to me what the `--all` parameter is for or if I am simply misunderstanding it or if there is an issue with the default `flow check-contents` functionality.

Thanks in advance for the help!

**Comment by gabelevi** [comment]
Hi @drabinowitz! You're right! `--all` is currently a no-op. The reason for this is that we're planning on changing the behavior of check-contents to respect the presence or absence of a `@flow` pragma. Adding `--all` makes the transition a little easier.

@mroch detailed his plan in https://github.com/facebook/flow/commit/768201006495f867e9bdfe2b922e5fa7de09f1d5.

**Comment by drabinowitz** [comment]
Ah, thanks a lot for clearing that up!

**Comment by ulitink** [comment]
Hi @gabelevi. Could you please clarify, in 0.45 `--respect-pragma` is not listed as a possible option in `flow check-contents --help`, but it works as expected and changes the behavior. Will you keep it after making it the default option?

**Comment by tomjakubowski** [comment]
🏓 check-contents --all is still the default, is still documented without mentioning that it is the default behavior and therefore a no-op, and --respect-pragma is still not documented despite having an often quite desirable effect. see #4924
