### ISSUE TITLE
React.createFactory()-created factories with no arguments not checked

### ISSUE THREAD

**Issue by jankuca** [facebook/flow#3142]
There seems to be a bug in the declaration of `React.createFactory()` in that it does not match factory calls made with zero arguments or `null` as the props:

```javascript
const createA = React.createFactory(A)
// This works as expected. Props are correctly type-checked.
createA({ a: 123 })
// These two are not checked.
createA()
createA(null)
```

I looked at the declaration and it should probably be changed in a way similar to the following:

```diff
   declare function createFactory<Config>(
     name: ReactClass<Config>
-  ): (config: Config, children?: any) => React$Element<Config>;
+  ): (config?: ?Config, children?: any) => React$Element<Config>;
```

Here is a demo in flowtype/try: https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wChS0AbFAZxrgEE4kAPGJAOwBN7l0YAdAGFckDp3gBvUnDhgcYGgC4402bPZsVNGFGAcA5jLgBfcrKLckUABQBKVcYtIYAVygdExQQBEA8gCyAlzAAG72xmZmFBAcOnBoRCjscAC8XvwCiajsAGL80ACeNgx2FEnsNpImZdnJSBF1lRyulJRlQA

**Comment by asolove** [comment]
This is fixed as of Flow 0.53. I now get errors on all three bad calls to the factory.

```js
import React from 'react'

class A extends React.Component<{text: string}, *> {
  render() {
    return React.DOM.div()
  }
}

const create = React.createFactory(A)
create({})// error
create() // error
create(null) // error
```
