### ISSUE TITLE
Type declarations are not block-scoped

### ISSUE THREAD

**Issue by phpnode** [facebook/flow#3144]
It looks like type declarations are scoped to functions, not to blocks, e.g. this is an error:
```js
type A = string;
if (true) {
  type A = number; // <- flow error: name is already bound
}
```
but this is ok:
```js
type A = string;
function foo () {
  type A = number;
}
```

is this by design?

**Comment by jeffmo** [comment]
Type aliases use var scope (rather than let) in order to support mutual recursion. We could probably create a block-scoped hybrid...but we kinda didn't want to invent a 3rd scoping mechanism.
