### ISSUE TITLE
repeated use of polymorphic type

### ISSUE THREAD

**Issue by raould** [facebook/flow#3149]
I guess there's a zillion different things people could try to string together to generate confusing edge case situation with generics. :-) I want something vaguely like this code below but I'm doing it wrong / it isn't supported.

```
type Cloneable<T> = { clone: void => T; }
type Particle = { p:number; v:number; a:number; mass:number, radius:number }
type Stepper = <P:Particle & Cloneable<P>>(number, P) => P;
```

thanks for any thoughts, I haven't found much luck doing web searches...

**Comment by AugustinLF** [comment]
Wouldn't `Particle & Cloneable<Particle>` [work](https://flowtype.org/try/#0C4TwDgpgBAwgNgewHYQIYCM4QDwBUB8UAvFAN5QDGiKAXFAG4ICWAJsYbgNxQC+AUKEhQACqgBOwJlWglyYGkgCuAW3QQx3egpVqNUVNtXruy1AGczh3QBooY1CyaLLSo2N4Dw0AMrAIYSHcSbGEaUQkpLCgAMlhqNEwccMlpfHwAClcbEQBKdhFOPihiqD4KZDNgSmoMLGTIiDp66Ri45ASsEPEUrEJZIpLi+SgARmsBwa1R8cHig2mJktMLOjHF4vtHZ1WZ2ap2ugAzRSQKSWR0nPIxCGBFMSQoYAALJjMecZ4gA)?

**Comment by HerringtonDarkholme** [comment]
No, `Cloneable<Particle>` is not the same as `Cloneable<P>` if `P` is a subclass of Particle. `clone` method will lose information about `P`'s specific methods.

[This](https://flowtype.org/try/#0C4TwDgpgBAwgNgewHYQIYCM4QDwBUB8UAvFAN5QDGiKAXFAG4ICWAJsYbgNxQC+AUKEhQACqgBOwJlWglyYGkgCuAW3QQx3egpVqNUVNtXruy1AGczh3QBooY1CyaLLSo2N4Dw0AMrAIYSHcSbGEaUQkpLFsAaTphKAAyWGo0TBxhfHwAClcbKGiASnZ8zj4+KAqoPgpkM2BKagwscMlpYjJyyor5KABGa06urT6BroqDEcHK0ws6fqmK+0dnOdGxiAAPPyQzJmQ6AHIQCDMDta6qZAg6ADNFJApJZCyC8jEIYEUxJChgAAsmGYeAN+HwWBAqOJoPRxFA6v46L5-IEpnx4WAsv0GsgmhAWpEIAUAHSbba7ZBEih-cQwBDggCCwCyAAYCqj0ZjbJckLj8dJidyIC8SVsIDs9khKdSxLSGUzWUA) might work.

**Comment by raould** [comment]
many thanks
