### ISSUE TITLE
Internal Flow error from "export type * from"

### ISSUE THREAD

**Issue by loganfsmyth** [facebook/flow#3152]
I'm assuming that syntax isn't actually expected to work, so obviously not a high priority. I was checking to see since I wasn't sure, and it looks like Flow hits an unexpected error, rather than reporting a syntax error.

    export type * from "./foo";

The Flow CLI reports

    unexpected parsing exception: Failure("Internal Flow Error! Parsed `export type` into something other than a type alias!")

but the website "Try" page doesn't provide any feedback due to an unhandled exception.

**Comment by jeffmo** [comment]
Thanks for the report.

This is a double-whammy and it's on me. At minimum this should be a parse error rather than an internal error. I'll fix this up

**Comment by gajus** [comment]
Is there an issue to add support for https://github.com/leebyron/ecmascript-export-ns-from ?
