### ISSUE TITLE
Strange errors in polymorphic React component

### ISSUE THREAD

**Issue by aldendaniels** [facebook/flow#3153]
Example: [flowtype.org/try/[...]](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3gMKyawB2RzuAvqJNo6AOTZSFfgG5UTPKADOACxLQ48AKIBHAK4LuvNALkKlRDQrHIy0EtOmgAQpaIMmrdgB4ACgC4A8gCMAVkQU1ADK3v6BuAB8oEQAHrhsACbWjljOuC4AJMHyGETukdRuIdE0iKCg5aAgoACqAHJ0XgCyzcr1ACqgHQASysHKoAAyAJL1-d1eoABiIwAaM0NeAOqgygQEXgShVVU10rgkuChkoIlEkCTq0LhuvBjSHqDZuflukeIVNRj3j6Bun2qYAORyIT2CgKqZEYaTYuBysGuiVqGESoIAFKx4ndYA8nsVQFj4YcEuCAJS0KoVIS4dTYZigACE+kUCDUmmg6NwshQ0gAdD9cdJqEScQ8KQAfCWVCqyuUVZnyVkqYyc7m8vkghIiuLE0FkwEcRBGxC4ACeeX+vw6FqIoAAvJSAJCxJ7MdRoHxEbCUKpOs1uj1e7DG8Sm22gYIkog2y2OsoVaFwbBPfgAcyEbH4oGlgiIiWzuZ80HURFMHDD5ksKVgOESMXiSWsdmkDhhLDhlIqgrxVqFsaIgK1YMj0YHu0TLAO2HUFBw6J7fzF0gHFITsuk6jy2AXvwNVNA6v5w4dXflSZwqYzRCzB4rVRNFXkzES0Ac0BOAGt0WuD0fNUQeoJOi65yheKaHjy-KLnysTUDUIzMAAbgoKCJIyMxKKA0LYEIFDQGaMiyAg1jerw2B8ne+4VI+oBCC+3o-me1KAXSDLoi4iQoEhoAsHQH5kJ+9o0P+z6vu+X4cMAkTUaARpGhUiAMHWfLnJc1y3L8p7rq6oAAIy+hUAYCHp-DwWAiEoR+6GYQg2E4HhuAEURJExLhOCUfeQA).

This works:

```javascript
class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
  static defaultProps: $Shape<P>;
  props: P;
  state: S;
  
  componentShouldUpdate(nextProps: P, nextState: S) {
    return !shallowEqual(this.props, nextProps) || 
           !shallowEqual(this.state, nextState);
  }
}
```

This throws errors:
```javascript
class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
  componentShouldUpdate(nextProps: P, nextState: S) {
    return !shallowEqual(this.props, nextProps) || 
           !shallowEqual(this.state, nextState);
  }
}
```

Error:
```
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
         ^ undefined. Did you forget to declare some incompatible instantiation of `S`?. This type is incompatible with
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
         ^ some incompatible instantiation of `S`
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
                         ^ object type. This type is incompatible with
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
                         ^ undefined. Did you forget to declare object type?
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
                                   ^ object type. This type is incompatible with
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
                                   ^ undefined. Did you forget to declare object type?
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
                                   ^ undefined. Did you forget to declare object type?. This type is incompatible with
6: class BaseComponent<P:Object, S:Object> extends Component<$Shape<P>, P, S> {
                                   ^ object type
```

Since the type parameters are passed through to the base [React$Component](https://github.com/facebook/flow/blob/master/lib/react.js#L16) definition, it's unclear to me why I need to redefine props/state/defaultProps on `BaseComponent`. 

Questions:
 1. Is this expected behavior?
 2. If yes, what does the error mean? A better error message would be helpful.

Thanks!

**Comment by Naddiseo** [comment]
I think this might be able to reduced to:

```js
// @flow
import React, { Component } from 'react';

type P = { prop: number };
type S = { sprop: string };

class MyComponent extends Component<any, P, S> {
  //state: S; // starts to work when this is uncommented? why?
}
```

Which currently gives the follow errors:
```
7: class MyComponent extends Component<any, P, S> {
                                               ^ object type. This type is incompatible with
7: class MyComponent extends Component<any, P, S> {
                                               ^ undefined. Did you forget to declare S?
7: class MyComponent extends Component<any, P, S> {
                                               ^ undefined. Did you forget to declare S?. This type is incompatible with
7: class MyComponent extends Component<any, P, S> {
                                               ^ object type
```

However, this might be due to a change which [added `$Abstract`](https://github.com/facebook/flow/commit/2600ed9b43d6b8af461d3713889e5c8d2cdbd069) to `state` and `defaultProps`. `$Abstract` isn't documented yet, but [seems to require subclasses to re-define the props](https://github.com/facebook/flow/issues/2464#issuecomment-248749163)

**Comment by asolove** [comment]
This stuff has changed a lot in React v0.53, where the prop and state types now must be specified as type parameters. This also fixed a number of problems about inferring types with props and defaultProps. So, for example, a slight change to the initial code now works fine:

```js
// @flow
import * as React from 'react';

type P = { prop: number };
type S = { sprop: string };

class MyComponent extends React.Component<P, S> {
}
```

As a result, unless there's something extra here I'm missing, I think this can be closed (/cc @calebmer).
