### ISSUE TITLE
Weird issue with exact object types

### ISSUE THREAD

**Issue by levrik** [facebook/flow#3155]
We experienced a quite weird issue with exact object types.
I was able to break it down to this test case:

```javascript
// @flow

type Foo = {|
  name: string,
  description: string
|};
type Bar = {|
  name: string,
  foos: Foo[]
|};
type Group = {|
  foos: Foo[],
  bars: Bar[]
|};

const group: Group = {
  foos: [],
  bars: []
};

(group.foos: Foo[]);
(group.bars: Bar[]);
([ ...group.foos ]: Foo[]);
([ ...group.bars ]: Bar[]);

([ ...group.foos, ...group.bars ]: Array<Bar | Foo>);
([ ...group.foos ]: Array<Bar | Foo>);
(group.foos: Array<Bar | Foo>); // This fails

/*
 testcase.js:3
 3: type Foo = {|
               ^ property `description`. Property not found in
 7: type Bar = {|
               ^ object type

 testcase.js:7
 7: type Bar = {|
               ^ property `foos`. Property not found in
 3: type Foo = {|
               ^ object type
 */
```

First experienced in 0.35.0, after upgrade to 0.37.4 still present.

**Comment by vkurchatkin** [comment]
This is expected behaviour, arrays are invariant so `Array<Bar | Foo>` is not a subtype of `Array<Foo>`

**Comment by levrik** [comment]
@vkurchatkin But why is `([ ...group.foos ]: Array<Bar | Foo>);` working? From implementation perspective it's the same as `(group.foos: Array<Bar | Foo>);`.

**Comment by vkurchatkin** [comment]
It's not the same, you create a new array, so `Foo` is just a lower bound of array's element. This means that you can assign it to any `Array<T>` as long as `Foo` is subtype of `T`

**Comment by levrik** [comment]
@vkurchatkin Okay. I understand. Still I think there is some issue. The issue gets displayed on the type declarations but not on the line that acutal causes it. It took me hours to find out where this issue come from in a fairly large code base.
