### ISSUE TITLE
Uncorrect error message for index of foreach loop

### ISSUE THREAD

**Issue by yahely** [facebook/flow#3156]
For example:
```javascript
list.forEach((el, j) => {
        var x: number = (j % 2 == 0 ? el.length : el);
        var y: number = (typeof el === 'string' ? el.length : el);
});
```
Flow said that there is an error on j index. The error is: 

> Flow: string. This type is incompatible with number. 

Although there is no such an error, because j is the index of the array and should be a Number type.

**Comment by gcazaciuc** [comment]
I believe the problem is line `var x: number = (j % 2 == 0 ? el.length : el);`. The issue is than when j is uneven x will get the value `el` which can be a string.
Also as a note don't believe it's necessary to annotate x and y as they should be inferred.

**Comment by yahely** [comment]
Yes, but there is an error in my IDE for the j variable at this line: 
```javascript
(j % 2 == 0 ? el.length : el);
```

Although the variable is ok and the problem is with el value. 
It's a little bit confusing and I think it's enough to get an error from the el variable. 
Thanks :)

**Comment by gcazaciuc** [comment]
Maybe it's an issue with error positioning in the IDE plugin you are using . What does running 'flow status' in the project directory giving ?
