### ISSUE TITLE
Incorrect context recognition

### ISSUE THREAD

**Issue by yarax** [facebook/flow#3159]
Flow doesn't recognize nullable variable behavior properly:

```
type A = ?{
      key1?: string,
      key2?: string
}

function f(a: A, data) {
  if (!a) {
    throw new Error(`No a`);
  }
  Object.keys(a).find(key => {
    return a[key] === data; // error: Computed property/element cannot be accessed on possibly null/undefined value
  });
}
```

https://tryflow.org/?code=LyogQGZsb3cgKi8KCnR5cGUgQSA9ID97CiAgICAgIGtleTE/OiBzdHJpbmcsCiAgICAgIGtleTI/OiBzdHJpbmcKfQoKZnVuY3Rpb24gZihhOiBBLCBkYXRhKSB7CiAgaWYgKCFhKSB7CiAgICByZXR1cm47CiAgfQogIE9iamVjdC5rZXlzKGEpLmZpbmQoa2V5ID0+IHsKICAgIHJldHVybiBhW2tleV0gPT09IGRhdGE7CiAgfSk7IAp9

**Comment by vkurchatkin** [comment]
Duplicate of https://github.com/facebook/flow/issues/2979 (and probably others)

**Comment by yarax** [comment]
So it's not considered as a lack of functionality?
