### ISSUE TITLE
Warnings for implicit type coercions

### ISSUE THREAD

**Issue by menelaos** [facebook/flow#316]
Would it be possible for flow to warn the user when code relies on implicit type coercion?
 
Take e.g. the ["Hello Flow" example](http://flowtype.org/docs/five-simple-examples.html).
If I change 
```javascript
function foo(x) {
  return x*10;
}

foo("Hello, world!");
```
to
```javascript
function foo(x) {
  return x+10;
}

foo("Hello, world!");
```
flow does not warn anymore as it assumes I want to concat the strings "Hello, world!" and "10".

I guess for some cases (e.g. number to bool) it is idiomatic javascript to rely on implicit type coercion. Nevertheless, for those who prefer to be explicit about type conversion, it would be great if flow could print a warning in these cases (e.g. via command line flag --warn-implicit).

**Comment by jeffmo** [comment]
cc @avikchaudhuri / @mroch : Do either of you know if this is intentional? It does seem like something we should be warning on...

**Comment by mroch** [comment]
I think it's definitely intentional based on the 3rd and 4th bullet here: http://flowtype.org/docs/base-types.html#base-type-notes-and-caveats

Doesn't mean we can't revisit it, though, perhaps as a .flowconfig option if there's not consensus on it.

**Comment by samwgoldman** [comment]
I think flow behaves correctly here. This example is easily fixed with a type annotation.

**Comment by avikchaudhuri** [comment]
Adding strings and non-strings is pretty common for printing, etc. and is a JS convenience we don't want to mess with, I think.

**Comment by stephencelis** [comment]
Any chance this can be revisited? The caveat seems to have been removed, and the behavior surprised our team (coming from a more statically- and strongly-typed domain). `number + string` (and the inverse) seems to be the only exception to this rule.

**Comment by andreypopp** [comment]
I think it makes sense to support the following behaviour with some special pragma `@flowStrict`:

* Disallow `any`, `Function`, `Object` in module source.
* Treat all `any/Function/Object` types from imported modules as `mixed`.
* Report error if module imports any untyped module.

What do you think?
