### ISSUE TITLE
Alias `type A = any` behaves differently from `any` itself.

### ISSUE THREAD

**Issue by tempname11** [facebook/flow#3164]
Minimal example:
```javascript
type A = any;
type X = 1 | { a: A }
const x: X = 'typechecks!?';
// type Y = 1 | { a: any }
// const y: Y = 'fails';
```
This typechecks, but it should not.

My intended usage for this alias was leaving a type's implementation until later, i.e.:
```javascript
type Todo = any;
type OrderId = Todo;
type Status = Todo;

type Action =
  | { type: 'ONE', id: OrderId }
  | { type: 'TWO', status: Status }
```

Curiously, if `any` is replaced with `any & mixed`, typechecking starts to fail — correctly.

This issue can be reproduced with 0.37.4 and on the current master.

**Comment by ForbesLindesay** [comment]
I think the problem here is that `{a: any}` is not the same as `any`.

For your first example:

```js
const y: Y = {a: 'succeeds'};
// const y: Y = 'fails';
```

So to fix your second example:

```js
type Todo = any;
type OrderId = Todo;
type Status = Todo;

type Action =
  | { type: 'ONE', id: OrderId }
  | { type: 'TWO', status: Status }

const a: Action = {type: 'TWO', status: 'whatever'}; // typechecks!
```

or

```js
type Todo = any;
type OrderId = Todo;
type Status = Todo;

type Action =
  | { type: 'ONE', id: OrderId }
  | { type: 'TWO', status: Status }
  | any;

const a: Action = 5; // typechecks!
```

**Comment by tempname11** [comment]
The point was: it should not typecheck, but it actually does. I edited the first post to make it clearer.

**Comment by ForbesLindesay** [comment]
Ah, you're right.  That definitely looks like a bug to me.

**Comment by vkurchatkin** [comment]
Doesn't reproduce anymore
