### ISSUE TITLE
Flow incorrectly shows errors with tagged disjoint unions

### ISSUE THREAD

**Issue by danwang** [facebook/flow#3165]
Minimal example code: ([try link](https://flowtype.org/try/#0C4TwDgpgBAggjFAvFA3gQwCpoOYC4pwC+A3AFCiSwBMSqmO+VJ540MAdiDLfFAD7UyLSgHEAPAGoY+DlwB8tdDOakAxgHt2AZ2BRstABTYIEfONkw5ASnw6ATgEt2+xAoDkAM3Xq3ZDdt1sBGQjEzMxeGtbYEdnJAVsUIgrP00dPRoQ41MocyooqHsnFwSklKA))

```jsx
type A1 = {aTag: 1};
type A2 = {aTag: 2};
type AnyA = A1 | A2;

type G<+A: AnyA> = {a: A};

const g = (gee: G<AnyA>): string => 'foo';
const g1 = (gee: G<A1>): string => g(gee);
const g2 = (gee: G<A2>): string => g(gee);
```

With this, I get the following errors:

```
1: type A1 = {aTag: 1};
                    ^ number literal `1`. Expected number literal `2`, got `1` instead
2: type A2 = {aTag: 2};
                    ^ number literal `2`
2: type A2 = {aTag: 2};
                    ^ number literal `2`. Expected number literal `1`, got `2` instead
1: type A1 = {aTag: 1};
                    ^ number literal `1`
```

Is there something I'm doing wrong? I declared `G` as covariant on `A` so that `G<A1> <: G<AnyA>`.

Please help, as the error message is meaningless.

Thanks,
Dan

**Comment by STRML** [comment]
I believe you want:

```js
type G<A: AnyA> = {+a: A};
```

[Try Link](https://flowtype.org/try/#0C4TwDgpgBAggjFAvFA3gQwCpoOYC4pwC+A3AFCiSwBMSqmO+VJ540MAdiDLfFAD7UyLSgHEAPDHwcuAPlooA1GinNSAYwD27AM7Ao2WgApsECPnHSYMgJT5dAJwCW7A4jkByAGYaN7spp09bARkY1NzCTgbO2AnFyQ5bDCIa38tXX0aUJMzKAsqaKgHZ1dE5NT1dKCAZiMc-HQG+jxqwkJbItiShP1y4iA)

**Comment by danwang** [comment]
Thanks!
