### ISSUE TITLE
How to output flow interface files

### ISSUE THREAD

**Issue by indiescripter** [facebook/flow#3168]
I hope this isn't a duplicate question.

With TypeScript it is possible to output .d.ts files that the compiler generates. This allows type declaration files to be read by other packages that one is developing (say package B) without having to provide all the .js source from an dependant package (say package B).

To be clear, I would like to be about to run Flow over .js sources in package A and produce a packageA.js.flow file that can be referenced in the [lib] section of the .flowconfig file in packageB.

Is this or similar functionality afforded by Flow?

Thanks

**Comment by ForbesLindesay** [comment]
You can run `flow gen-flow-files my-file.js > my-file.js.flow` which generates a minimal flow definition.  Unfortunately it's still experimental/unfinished at the moment though.

**Comment by indiescripter** [comment]
Thanks so much for that. I'm happy enough to go with experimental; at the moment I'm doing it by hand.

I really hope 2017 is great for Flow as I appreciate its "higher moral ground" re type theory. Then again noone wants to get burnt on the bleeding edge. otoh I've really pushed the envelope of that other JS static type to the point that I'm about to throw in the towel and run blindly with vanilla ES2015.

p.s. @ForbesLindesay are you on Twitter?

**Comment by ForbesLindesay** [comment]
twitter.com/ForbesLindesay
