### ISSUE TITLE
Feature request: Support alternate JSX translations

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#317]
babel has a neat feature where you can control how JSX is translated into javascript. For example:

``` javascript
/* @jsx dom */
<div></div>
```

is translated to

``` javascript
dom("div", null);
```

Currently JSX is always mapped to react.createElement, but the code seems like it should generalize to any method, even if scoped to a module like `/* @jsx myModule.mkElem */`.

**Comment by gabelevi** [comment]
A lot of the JSX support is kind of mixed in with the other code. If you could modularize it into it's own module, then you could always swap that module out with your own implementation. This can be done at build time (configure the makefile to look in directory A for JSX.ml instead of directory B) or in the code itself by reading some option and using MyJSX instead of JSX.

Does that help at all?

**Comment by samwgoldman** [comment]
That does help. It's different from the approach I was thinking of. Ideally, we would not need to compile a separate version of flow to use this feature, although I think that would be a reasonable outcome.

My thought was to fill out the [flow case for arbitrary functions with markup](https://github.com/facebook/flow/blob/a3b1d2c7014aa38272f6b07ef89d8b39f91b3dfd/src/typing/flow_js.ml#L2256). My hope was, for this case, to look up the function specified in the `@jsx` directive from the env, error if one does not exist, and assume it has an API similar to createElement's.

Feels like that should work, but maybe the weak point is looking up the function from the environment, a detail I glossed over in my explanation above.

**Comment by impinball** [comment]
I would prefer the `@jsx` comment over recompiling Flow. The default could be `React.createElement`. Most virtual DOM libraries use the same format:

- Mithril: `@jsx m`
- virtual-dom: `@jsx h`
- etc.

It's a safe assumption to make for most function calls.

```js
// Mithril
m("ul", null, [
  m("li"),
  m("li"),
])

// React
React.createElement("ul", null, [
  React.createElement("li". null, []),
  React.createElement("li", null, [])
])
```

**Comment by vkurchatkin** [comment]
@gabelevi this probably can be closed now?

**Comment by gabelevi** [comment]
@vkurchatkin - right! Thanks for noticing! As of d2930e135f9c34a89a226c2ca36eb4bcab7b59db this should be resolved!
