### ISSUE TITLE
How to model a side effect? Or, how to work around not being able to declare a side effect?

### ISSUE THREAD

**Issue by danfuzz** [facebook/flow#3179]
I'm trying to define a `flow-typed` wrapper for the package `express-ws` (WebSockets for Express), and have run into a roadblock:

When you call `express_ws(app)`, the given `app` gains a new method `ws`, such that you can then call `app.ws(...)`.

How do I declare this with Flow? Or, if I can't, what's the most appropriate way of working around this deficiency?

**Comment by indiescripter** [comment]
My strategy would be to put all your flowtype goodness in the wrapper but don't worry if inside the wrapper source code you have to work around like this:

```
(app: any).ws(...);
```

That's better, well at least tidier, than having a // $FlowFixMe comment preceding the app.ws(...) line.

**Comment by yarax** [comment]
Here is a good article about possible side effect implementation with Flow https://medium.com/@gcanti/the-eff-monad-implemented-in-flow-40803670c3eb#.qjvrucsqb

**Comment by SamChou19815** [comment]
This is not going to be supported.
