### ISSUE TITLE
destructured values seen as undefined by flow?

### ISSUE THREAD

**Issue by ryancole** [facebook/flow#3190]
I'm destructuring some values out of the return value of a function call. Flow is identifying the variables as `undefined`, though. [Here is a link](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwBvMHAQ3wGcBTMAXzCnzizACIBXfGDgbnS0AHniJgAJrSgUuMYgGMYFatTAAZOAoqEMcAHalUYMAAs41QvopZaALjCX8GfQHNBJyoVPXbDpy7u6CYKBk5cCoQEABQ8MP6Ezm4AlEYmIWHEZOaWvrQANOQ6Pjb0TAC8RTS0sbzJHuneGNQAdDlWpWCV7XkNJk2tXiW2XUXevcaMqAyoQA) to the code example in the try flow editor.

```js
/* @flow */

import { parse } from "url";

export default class Location {
  hostname: string;
  pathname: string;

  constructor(url: string) {
    const { hostname, pathname } = parse(url);
    this.hostname = hostname;
    this.pathname = pathname;
  }
}
```

**Comment by jesseschalken** [comment]
Defining `parse()` manually instead of importing it seems to work: [link](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAHAQwCcBnAUwAoAPALjBvysOwHMBKNgG8AFnA7YKAWzosOXXgBpyFfMInTZnbjwC+YQajBgqdfJiqkRY-OplgA5PaWVVtto50BuVDvR0mZHBU+GAAJnRQFJgwIbgwFDQ0YAAycLgqxJaGYKLiUnZy2t5GLmr5bIW83tm4JHKYBEEM5jAVWrx8+tlGtdgc+jnWts4qZdJgegC8yrSMLXzFRmCqhDQAdLk2+WDTm7aLRivrpbY7yq75i76+QA). Does Flow know what the `"url"` module refers to, and have correct types for it?

**Comment by AugustinLF** [comment]
`url.parse` returns an urlObject, which may or may not contain a hostname and a pathname. For instance `require('url').parse('').pathname === null`. Si you'll need to check that these values are defined, if not, you can default them.

**Comment by mroch** [comment]
[this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSBVQmMAXjAG8AfVMMSwuUuHHBgAuMAGdShAJYA7AOZg2YGQFcYMADSdxBMQAssY0QCM4QrPhmLlazdvwrSe0ROnzrq9Vq564El5KyCkqedlyUcISkAW7BNl7avhIy+AC2WDFBHrbeYHr4+pnuITnaYhaEOM7igcXxYWAAjipYhORFcaHWLGAA2q5BALodGmAAdBNgAL65lPhOKekd2Qnh89UDdaG5esRQI6hsU5i4BMRkVLT0AOpSTgDKtXIAii1tTKwcXBNjdA3NrXaNViKxgh2O2DwRBIFGoYD+tycAAUiOUMK9AR92Nofn9cgC2qIev0nsNgUFRj9puCTlDzlAVDIcKQpHArHNCOUABQqeiPQgjbiorAYtr8oKiSQtUZiXQGMQAESwMj4WAAEn5SAB+ExmGAWGQASlECLuehRnKw6Le5AA3LSziQGUyWWyhZaeXzJIKOeVReRxfIdWAoPgYOVrAA3OBSDAyuWGJUq0jqzXB0zmSzG+E3M2Bl42+2Qx0hxnM1ns4WemD8n3C-359N6g3xgrypOqjUSJuZo0m+j21BYAAeESiYGwobUpDAULEYjAABkBPMK6xEprFhlyfJ7WsFmlt5s5IOuIIZK4VMzItWOob11wz2yJKw8pvD6M5gf0tMPr6sNWhp7o+ThSGIYxJKQW4fJBW7AVwoHgV+ejQcwyFwdoxzHEAA) looks like it's working properly
