### ISSUE TITLE
Why does Flow dislike Async Generators?

### ISSUE THREAD

**Issue by steelbrain** [facebook/flow#3192]
I got this while working on one of my projects

<img src="https://cloud.githubusercontent.com/assets/4278113/21962917/abba0f20-db51-11e6-9be6-5ac683e04cff.png">

I'm on flow v0.31.0 and macOS Sierra if that's relevant

PS. I searched for an existing issue but couldn't find any, so sorry if this is a duplicate

**Comment by jesseschalken** [comment]
It seems to work on flowtype.org/try: https://flowtype.org/try/#0FAYwNghgzlAEBiBLMBTWBvAvsUkawEENhZZoBPAOxFgCoAHAJwHsQUYlUAKASgC5CUKiADiKSikYQALs0YAeTigA0sAG7NEAE1UbtAPmKls2IA

**Comment by steelbrain** [comment]
Fair enough, must be an old version or something then

**Comment by jedwards1211** [comment]
@steelbrain note also that `Promise<File>` is the wrong return type:
```js
async function * processFile(): Promise<string> {
}
```
```
1: async function * processFile(): Promise<string> {
                                   ^ Cannot expect `Promise` as the return type of async generator function because `Promise` [1] is incompatible with implicitly-returned `AsyncGenerator`.
References:
1: async function * processFile(): Promise<string> {
                                   ^ [1]
```
Flow only allows a return type of `AsyncIterable<File>` or `AsyncIterator<File>` (at least that's what the latest version allows in try flow)
