### ISSUE TITLE
Object spread doesn't remove inherited properties

### ISSUE THREAD

**Issue by jesseschalken** [facebook/flow#3197]
```js
class A {
  blah(): void {}
}

type Blah = {
  blah(): void;
}

let a: Blah = new A();
a = {...a}; // Won't copy the blah() method because it's not an own property
a.blah(); // No type error, but "a.blah is not a function" at runtime
```

I'm not sure how Flow should deal with this. I guess it needs to track which properties are own properties and which ones are inherited, so it can produce the right type for object spread which only sees own properties.

**Comment by SamChou19815** [comment]
This is fixed when we banned class <: object subtyping
