### ISSUE TITLE
Safer mixed->Array refinement

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3199]
As of https://github.com/facebook/flow/pull/2214 `Array.isArray` refines `mixed` to `Array<mixed>`. It's better than `Array<any>`, but still unsound:

```js
const a: Array<{ foo: string }> = [];
const b: mixed = a;

if (Array.isArray(b)) {
  b.push({});
}
```

Ideally, type parameter should have upper bound `mixed` and lower bound `empty`, that is, writing to such an array should not be possible.

Theoretically, lower bound could be refined by checking array items:

```js
if (Array.isArray(b)) {
  // lower bound is empty
  if (typeof b[0] === 'number') {
    // lower bound is number
    b.push(1);
  }
}
```

**Comment by vkurchatkin** [comment]
The last part is incorrect: lower bound can't be refined. If ` b[0] === 'number'` then `T` can be some subtype of `number` and pushing something else is unsafe.

**Comment by mvitousek** [comment]
Resolved by https://github.com/facebook/flow/commit/5639532065954e7f66a968af5e68f76a762a9c14
