### ISSUE TITLE
flow --colors

### ISSUE THREAD

**Issue by jeanlauliac** [facebook/flow#320]
That'd be nice to be able to do something like:

    flow --colors | less

Because right now, piping cause the colors to be disabled (as expected from well-behaved UNIX tools):

    flow | less

**Comment by mroch** [comment]
added in 0.12!

`flow --color=always` (or `never`, or `auto`)

the flag is missing from some commands in 0.12, like `check`, but that will be fixed in 0.13.

(btw, for your example you probably want `less -R` so it shows the colors instead of the ANSI escape characters)
