### ISSUE TITLE
Cannot convert from number enum to number

### ISSUE THREAD

**Issue by agrcrobles** [facebook/flow#3200]
Given the following snippet I am getting the error below...

> This type is incompatible with the expected return type of number enum

```
type Size = 1 | 2 | 3;
const GetSize = (): Size => {
    const result: number = parseInt(Math.random() * 20);
    if (result > 3) {
        return 3;
    }
    return result;
};
```
You can try it [online](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKAlgF4EC8YAjGAD5gBM9YAzANyp4AeOcAThjABjOADsAzkIDieDCXJgqACgCUALiJlKAPjABvVAEhRkofzwSArjAyaxVgLYAjPPyVgcAQ34S8ASTEMZQBZLwwACwA6fi8xABM4RzVkJgAGVU4jYigwZQtrWzA9VlUDYyMLDCt+MTYsgF9jKpq6gpsMTgb2IA)...

**Comment by vkurchatkin** [comment]
Well, `number` is not a subtype of `1 | 2 | 3`, so this is an error

**Comment by weshardee** [comment]
Well, you could do this:
```
type Size = 1 | 2 | 3;
const GetSize = (): Size => {
    const result: number = parseInt(Math.random() * 20);
    switch (result) {
      case 1: return 1;
      case 2: return 2;
      default: return 3;
    }
};
```
or this:
```
type Size = 1 | 2 | 3;
const sizes = [1, 2, 3];
const GetSize = (): Size => {
  const result = parseInt(Math.random() * 20);
  if (result > 3) {
    return 3;
  }
  return sizes[result];
}
```
Both of these feel overly verbose for my taste, but I don't know if there's a more succinct way to pick a random enum value and make Flow happy.
