### ISSUE TITLE
child_process streams missing destroy property

### ISSUE THREAD

**Issue by rgbkrk** [facebook/flow#3204]
```
> c = chp.spawn('python', ['-v']);
> c.stdout.destroy()
undefined
```

Right now `child_process$ChildProcess`'s `stdout` and `stderr` are declared as `stream$Readable`. Each of these, including `stdin` have some additional properties beyond `stream$Readable/Writable` including `destroy`.

**Comment by lll000111** [comment]
All ReadStream and WriteStream streams in current node.js use `destroy()` and `close()` no longer exists.
