### ISSUE TITLE
Question: why is optional object property being treated as required?

### ISSUE THREAD

**Issue by justin-calleja** [facebook/flow#3207]
Flow version:  0.37.4

I must be doing something wrong or am misunderstanding the use of `?` to mark an optional property in an Object.

I have:

```
  async find(
    [docId, version]: [string, ?number],
    { force = false }: { force?: boolean, jsondiffpatch?: any } = {},
    dbOpts?: Object = {}
  ): Promise<[ Doc, Array<Item> ]> {
```

Which I am then using from:

```
  async addDelta(
    docId: string,
    deltaContent: Object,
    opts: { jsondiffpatch?: any },
    dbOpts?: Object = {}
  ): Promise<Doc> {
// ...
    let doc: Doc = await this.find([docId], opts, DB_OPTS);
}
```

But am getting:

```
src/adapters/PostgresqlDocAdapter.js:103
103:       let doc: Doc = await this.find([docId], opts, DB_OPTS);
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `find`
 61:     { force = false }: { force?: boolean, jsondiffpatch?: any } = {},
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ property `force`. Property not found in
103:       let doc: Doc = await this.find([docId], opts, DB_OPTS);
                                                   ^^^^ object type
```

Just from the flow check output, why if, on line 61 force is defined as optional with `?`, am I then not allowed to pass `opts`, which is not expected to have `force` and is thus typed as: ` { jsondiffpatch?: any }`?

If I add `force?: boolean` to `addDelta`'s `opts` param, it works… but I'm not expecting the use of this option for that operation.

Many thanks

**Comment by AugustinLF** [comment]
If I'm not mistaking, the problem is that that `{ force?: boolean, jsondiffpatch?: any }` is not a subtype of `{jsondiffpatch?: any}`. This is somehow similar to [this issue](https://github.com/facebook/flow/issues/3111). For instance, [nothing prevents you](https://flowtype.org/try/#0GYVwdgxgLglg9mABMGYAmAKAUI3iDaacEAkmgDSIBuApgE4DO8YAugFwENR2oDmlAfjAgAtgCN6LcjjxwOAb2Rw6EGgI5i4cADY0AhmEoArBgjQxgwAA56oEABbrEBgJ6IAvogC8iee+m4AJS+MrhwAHTAyqreiNwgNADcOO5YMqCQsAjOaGgAIjTaUHrYeIhEpGgcXDxg-KHlhcUAwghQNGBQHADyYkY00AGyVlAMCiZmFta2Dk6u-g1oYt0jDE69-dCxfjLB8g26UOXEsSjoGITEZFKIcKuBye5AA) from writing the options in find, which would indeed break the addDelta contract.

**Comment by justin-calleja** [comment]
@AugustinLF thanks for the reply!

First off, the online REPL is adding another error (but I guess that's because it's running an older version of Flow):

```
14:     let doc = find([docId], opts);
                       ^ array literal. Tuple arity mismatch. This tuple has 1 elements and cannot flow to the 2 elements of
2:     [docId, version]: [string, ?number],
                         ^ tuple type
```

Ok, I get it… thanks. I didn't know Javascript was so-called [call-by-sharing](http://stackoverflow.com/a/3638034/990159). That would explain why Flow still thinks of `opts` as typed `{ jsondiffpatch?: any }` even when in `find`'s scope…

I suppose one way around it might be to create another object typed `{ force?: boolean, jsondiffpatch?: any }` before passing it to `find`. In any case, I haven't tried it as I've updated `addDelta` to take `force?: boolean` - it might make sense to update a soft-deleted document.

Many thanks!
