### ISSUE TITLE
Class - Avoiding duplication of attributes

### ISSUE THREAD

**Issue by StarpTech** [facebook/flow#3211]
Previous issue: https://github.com/facebook/flow/issues/3193
Stackoverflow: [Link](http://stackoverflow.com/questions/41662696/reuse-flow-class-declaration-for-class-definition)

```js
// a.flow.js
declare type A {
 name: string;
}
````

```js
// a.js
class A {
 constructor() {
  this.name // error property not found
 }
}
```

```js
// b.js
class B {
 constructor(a: A) {
  a.name
 }
}
```
 How can I avoid to declare my type for `class A` twice? I can only solve it when I implement my `class A` with the same interface of `type A`. This is redundant.

**Comment by aldendaniels** [comment]
@StarpTech Is this the same issues as the following?

```javascript
type PersonData = {
  name: string,
  age: number
};

class Person {
  name: string;
  age: number;
  constructor(data: PersonData) {
    Object.assign(this, data);
  }
}
```

You have to define the type for `name` and `age` twice.

**Comment by StarpTech** [comment]
Hi @aldendaniels yes its the same.

**Comment by zaaack** [comment]
@StarpTech Hit this problem, too. Hope flow could have a new feature to solve this soon.
But now I'm doing something like: 

```js
export type User = Users & UserFields
const u: User = ((new Users()): any)
//or
// $FlowFixMe
const u: User = new Users()
```
At least it works.

**Comment by SamChou19815** [comment]
We do not plan to support any inference on non-declared class props
