### ISSUE TITLE
Later expression seems to affect type of earlier expression

### ISSUE THREAD

**Issue by chrisui** [facebook/flow#3213]
Consider the following.

```
function maybe(obj) { return obj || null }
maybe({}).property;
maybe([]).length;
//  maybe(null).property;
```

I wouldn't expect to see any errors since line 2 `maybe({})` would return an object and accessing an arbitrary property should be fine. And line 3 `maybe([])` should return an array and `length` is a valid property.

Interestingly the error points towards flow thinking the return type of `maybe` is always `Array`.

```
2: maybe({}).property;
             ^ property `property`. Property not found in
2: maybe({}).property;
   ^ Array
```

By uncommenting line 4 I see a similar issue.

```
2: maybe({}).property;
             ^ property `property`. Property not found in
2: maybe({}).property;
   ^ Array
2: maybe({}).property;
             ^ property `property`. Property cannot be accessed on possibly null value
2: maybe({}).property;
   ^ null
3: maybe([]).length;
             ^ property `length`. Property cannot be accessed on possibly null value
3: maybe([]).length;
   ^ null
4: maybe(null).property;
               ^ property `property`. Property cannot be accessed on possibly null value
4: maybe(null).property;
   ^ null
4: maybe(null).property;
               ^ property `property`. Property not found in
4: maybe(null).property;
   ^ Array
```

https://flowtype.org/try/#0GYVwdgxgLglg9mABAWwIYE8BGBTAFHTAKwEpEBvRAJ2yhEqQMMQB9nEwQAbTxAXwCg0WPGV7EAdAAdKcSdkpR0AbkEYcuANoBdCZ2xgA5lAAWKgPRmh6jtwnTZ8xUqA

On one hand I'm sure there are some better ways of structuring this sortof code and typing it more intelligently but on the other it seems a possibility the inference could be improved/adjusted. This may be a misunderstanding of mine as to how it *should* work. Intuitively, and knowing flow can follow the flow an individual piece of data, I would've expected each `maybe()` to be interpreted differently and the above code to be fine and error only on `maybe(null).property`.

Would love insight into how this area works within flow!

Thanks!

**Comment by SamChou19815** [comment]
`inference_mode=lti` would fix this bebavior
