### ISSUE TITLE
Support Excess Property Checks

### ISSUE THREAD

**Issue by jedmao** [facebook/flow#3215]
I believe Flow's [default object type](https://flowtype.org/docs/syntax.html#object-types) vs. the [exact object type](https://flowtype.org/docs/objects.html#exact-object-types) is backwards

The [exact object type](https://flowtype.org/docs/objects.html#exact-object-types) already supports [Excess Property Checks](http://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks) by default. What I'm asking for is only relevant if/when [I can configure strict object types as the default behavior](https://github.com/facebook/flow/issues/3214) #3214. If it were configured as such, the following would be an exact object type:

```jsx
type Point = {
    x: number,
    y: number
};

const p: Point = { x: 5 };
```
[Similar to TypeScript](http://www.typescriptlang.org/play/index.html#src=interface%20Point%20%7B%0D%0A%20%20%20%20x%3A%20number%3B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20p%3A%20Point%20%3D%20%7B%20x%3A%205%20%7D%3B), the above should throw the following error:
> Type `{ x: number; }` is not assignable to type `Point`. Property `y` is missing in type `{ x: number; }` – const p: Point.

Unlocking a strict object type would be achieved with [Excess Property Checks](http://www.typescriptlang.org/docs/handbook/interfaces.html#excess-property-checks), which would look like this:

```jsx
type Point {
    x: number;
    y: number;
    [propName: string]: any;  // <-- exact object type becomes flexible
}
```
Just trying to offer solutions to my [laundry list of friction points with Flow](https://github.com/facebook/flow/issues/72#issuecomment-273691308).

**Comment by vkurchatkin** [comment]
This is core part of Flow's type system: `{ x: X, y: X }` is a subtype of `{ x: X }` and this is not going to change. The same is [true](http://www.typescriptlang.org/play/index.html#src=interface%20Point%20%7B%0D%0A%20%20%20%20x%3A%20number%3B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20p%3A%20Point%20%3D%20%7B%20x%3A%205%20%7D%3B#src=interface%20Point%20%7B%0D%0A%20%20%20%20x%3A%20number%3B%0D%0A%20%20%20%20y%3A%20number%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20a%20%3D%20%7B%20x%3A%205%2C%20y%3A%205%2C%20z%3A%205%20%7D%3B%0D%0Aconst%20b%3A%20Point%20%3D%20a%3B) for TypeScript, actually.

**Comment by jedmao** [comment]
@vkurchatkin, I'm not sure how your example relates to the post.
