### ISSUE TITLE
webpack's require.ensure

### ISSUE THREAD

**Issue by dfleury** [facebook/flow#3217]
I'm not sure how to approach with this issue and I need your help.

When using `require.ensure` to load chunks on demand like below,
```javascript
	require.ensure([ 'someModule' ], () => {
		// do something
	}, 'myChunkName')
```
I'm getting this error:
```
3: 	require.ensure([ 'someModule' ], () => {
            ^ property `ensure`. Property not found in
3: 	require.ensure([ 'someModule' ], () => {
    ^ object type

Or like in Atom's linting:
property `ensure` Property not found in object type
```
To workaround this, I'm using this declaration:
```javascript
declare var require: {
	(id: string): any;
	ensure(ids: Array<string>, callback?: { (require: typeof require): void }, chunk?: string): void
}
```

So, is this the better way to deal with it? Should it belong to a flow-typed package? Built-in maybe?

**Comment by cqfd** [comment]
I was wondering about the same kind of thing with `module.hot.{accept, dispose,...}`.

**Comment by AgentME** [comment]
I usually use `:any` casts for these cases: `(module:any).hot.accept(...)`

**Comment by m14t** [comment]
FWIW: I needed to start using @dfleury's workaround definition for `require.ensure` after upgrading from `flow-bin` `0.36.0` to `0.38.0`.

**Comment by SamChou19815** [comment]
Flow does not intend to support bundler specific typing. You need to override the type instead
