### ISSUE TITLE
Flow does not recognize wrong context

### ISSUE THREAD

**Issue by philippotto** [facebook/flow#3220]
Doing something like ([try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAYTAG9UwwCAuSgFwCcBLAOwHMBucsDOZ3BgK4ZacegApcNfkzYBKUlwq0AFo1wA6AgF5KnCgF8uAWwCmKuABMxsmgDc4jCwooBIemYH1mYFWvW0Tfms9MEMlQNprOwcnMlcePjgYE3V4VjFfDVxZEMNDVFtsejAWfjAdZhMkQjEAImxanIKisCNykr5adVNzC04jYLBgYDAERhgYMChsccoWDBMfZUWEgIAPWhKCZjhNgCM4AWYLIA))

```js
/* @flow */

class C {
  s : string;
  constructor(s: string) {
    this.s = s;
  }
  method(): void {
  	return this.test();
  }
  test(): void {
  	console.log(this.s);
  }
}

var inst = new C("a");
var m = inst.method;
m(); // will fail since the context is not bound
```

typechecks perfectly fine, even though the code will fail, since the class method is not called with the correct context.

Are there any plans to also check cases such as this?

**Comment by SamChou19815** [comment]
This is fixed when we start to emit `method-unbinding` errors
