### ISSUE TITLE
remove declare module React from lib/react

### ISSUE THREAD

**Issue by clarkbw** [facebook/flow#3222]
Noticed the following comment [here](https://github.com/facebook/flow/blob/master/lib/react.js#L229-L233)

```js
// TODO Delete this once https://github.com/facebook/react/pull/3031 lands
// and "react" becomes the standard name for this module
declare module React {
  declare var exports: $Exports<'react'>;
}
```
And checked that https://github.com/facebook/react/pull/3031 landed last year.  We could probably try removing that declaration now.

**Comment by TrySound** [comment]
@jbrown215 Is this piece of code still relevant?

**Comment by jbrown215** [comment]
I don't know, but that PR mentioned was closed and not merged. `'react'` is the standard name for the mdule, afaik though.

Happy to test it out internally and see what happens.

**Comment by SamChou19815** [comment]
It's removed recently
