### ISSUE TITLE
$Diff is not compatible with $Keys

### ISSUE THREAD

**Issue by aldendaniels** [facebook/flow#3230]
[Example](https://flowtype.org/try/#0FAFwngDgpgBAgjAvDAJAEQJYDMsB4DeAhgFwwB2ArgLYBGUATgL4A0M+jAfANyiSwBCSVAGkoYAM6443YMADGAezLiQMAB6lByAOSFtPIA):

```javascript
type A = $Diff<{a: number}, {}>;
type B = $Keys<A>;

const x: B = 'a';
```

**Comment by darichey** [comment]
This works now.
