### ISSUE TITLE
valid type cast function

### ISSUE THREAD

**Issue by alinz** [facebook/flow#3233]
This is not an issue and rather a discussion about how one can do the typecasting from base to child class. It has been documented in [here](https://flowtype.org/blog/2015/02/18/Typecasts.html) but it wasn't enough for me. 

I have prepared one sample code and wanted to ask the community whether it's a good approach or simply dump one.

as I said, my main focus is on casting from base to child,

assume the following classes

```js
class Base {
}

class Child extends Base {
  constructor() {
    super()
  }
}
```

a typical approach for typecasting from base to child is

```js
const base: Base = new Child()

let child: Child
if (base instanceof Child) {
  child = (base: Child)
  ...
}
```

I want to wrap this operation in a generic function which prevent me to write the same code over and over.

``` js
function castTo<T>(Class: T, value: Base): T {
  if (value instanceof Class) {
    return (value: T)
  }
  throw new Error('incompatible type')
}

const base: Base = new Child()

// converting from base to child
// if type is not compatible, it simply throws an exception during the runtime.
const child: Child = castTo(Child, base)
```

Do you guys considering this approach a valid one? any other thoughts

**Comment by vkurchatkin** [comment]
IMO this approach is perfectly fine, this is how you can do it:

```js
function castTo<T>(Class: Class<T>, value: Base): T {
  if (value instanceof Class) {
    return value;
  }
  throw new Error('incompatible type')
}
```

**Comment by alinz** [comment]
@vkurchatkin pretty cool, this is actually a lot simpler than I thought. Thanks!
