### ISSUE TITLE
Flow parser cannot parse simple Literal in Parenthesis.

### ISSUE THREAD

**Issue by danez** [facebook/flow#3234]
The following code makes the flow-parser fail. All other parsers have no problem with it.

```js
("not a directive");
```

The message I receive is:
```
Non-error thrown with value: [ 0,
  [ 248, aw { t: 0, c: 'Failure', l: 7 }, -3 ],
  aw { t: 0, c: 'Nooo: T_LPAREN\n', l: 15 },
```

ASTExplorer with flow also fails (see dev console):
http://astexplorer.net/#/2DM4QE8FCf

Noticed this while working on babel/babylon#277 and using the flow-parser as reference parser to compare the ast from babylon to.

**Comment by mroch** [comment]
thanks, will fix this before 0.39!
