### ISSUE TITLE
Flow sometimes showing errors on type definition instead of usage

### ISSUE THREAD

**Issue by zyklus** [facebook/flow#3235]
This makes debugging extremely difficult.

[Trimmed down example](https://flowtype.org/try/#0MYewdgzgLgBAIgUQOIH0CCBhDBVASpgTRgF4YAGAOjLIEYBuGAekZhprIFsYBDYYAVwBOvAJ4wO3KMAAWAUwit2XACaTuMCLKgAoUJFgAFAPIAZAkiMA5FABUCBhCRgByAyAA2IgObhndbdpQIgAOsjBuAJZgsKQA2mD8HABGsoIANDAJyakAuv5BoTAAQiCCyqlOaILCIgA8kdEAfPkhYSVlqQqkVTW17eWCjYGtxaUDAMqyXhyy0U6xDVAZi3nDhf2pk9OzUACy3MFOAN6xANayIgBcGlCCUV451xuCWzPRAL4t62ObU29QGBA-DmpCOoGBUGuWRS6Q0fx2Tx+L3hHy+bSRrx2gIhXRgJ3OVxudzAD0RHWR22i2NRazCbk8PjAlWq3DqPVZ9RAUSgjWatJgu347igEXp3nAzN6YsZQ20sgAHsFSrACmF9sFqbcxKDtDBMtwZtdoMSvGldTAIsojbd7ma9UkkddBcLRR5xWAzZ8AqqYEhZCAAFLjKzHc2q60mu0wABmskkQnk13ZdSO5r14aJtrTMC8-pmWuuRwzrjdjOcGVAYyikkT4VL4He2b1zebAB88cXnSLpb4KyAq2AaxAnULu-WwO8o3rgoIQKFBCLa0dB4bMyTJ9nLRGs3r3o1Pf5tBwQMohbIKAqlQvcdHgcARRLgtxBJpNYIREGrAAKc3g6Lvz9LGuP1A2DSwzQASmuAA3LllDxX8gX-D8wIoWN40EeQ0NKBBeGkL8v3QqAEygmBYMtEhGgQls9GgPFKzKasoHkDJVXeJwiITChcxAfN338GjwDoh1yWHAVR1dBkJVIAifWIeTwlMcwrFsewEAgpsYAAfhgWIGOUJj5ByTTrn0wyIAgw9d0s7QvSAA)

An error is being shown on the type definitions but it ultimately comes from line 36:

    const borders: MultiPolygon = ((type === POLYGON_TYPE)
      ? [coordinates]
      : coordinates);

And any advice on how to properly annotate this would be appreciated!

**Comment by mroch** [comment]
thanks for the report. I've been working on fixing this class of errors. they boil down to how we handle nested types. in this case, it's because two type parameters conflict. here's a simple example ([Try Flow](https://flowtype.org/try/#0C4TwDgpgBAGlC8UCCAnFBDEAeAdgVwFsAjCFAPgG4AoUSKATQWTUywGdgUBLHAc0qoAKQQG0AugC5YASin1p1IA)):

```
type X = Array<number>;
type Y = Array<string>;
(([]: X): Y);
```

the outer `Array` types are not-incompatible, so we then check the parameters and error because `number` is not compatible with `string`, but we've forgotten that we were only checking that because of the outer types.

**Comment by chrisirhc** [comment]
#4274 is another instance of this, where error is reported on the type definition instead of the usage (spread operator).

**Comment by samwgoldman** [comment]
The errors in the original example now point to the responsible uses in the code.

For Marshall's reduced example, we output this:

```
Error: test.js:4
  4: (([]: X): Y);
           ^ array type. Has some incompatible type argument with
  4: (([]: X): Y);
               ^ array type
  Type argument `T` is incompatible:
      2: type X = Array<number>;
                        ^^^^^^ number. This type is incompatible with
      3: type Y = Array<string>;
                        ^^^^^^ string

Error: test.js:4
  4: (([]: X): Y);
           ^ array type. Has some incompatible type argument with
  4: (([]: X): Y);
               ^ array type
  Type argument `T` is incompatible:
      3: type Y = Array<string>;
                        ^^^^^^ string. This type is incompatible with
      2: type X = Array<number>;
                        ^^^^^^ number
```
