### ISSUE TITLE
Feature: ...rest arguments as tuples 

### ISSUE THREAD

**Issue by faceyspacey** [facebook/flow#3237]
eg:

```
type Action<P> = {
    type: string,
    payload?: P,
    error?: bool,
    meta?: any,
  }

// this won't typecheck since args must be any or Array<something>
type ActionCreator<T, P> = (...args: T) => Action<P> 

type Payload = { index: number, foo: string }

type Args = [number, string]

// the following line uses a tuple type that will NOT correctly be spread into ...args
const performAction: ActionCreator<Args, Payload> = createAction(
  'PERFORM_ACTION', 
   (index: number, foo: string): Payload => ({ index, foo })
)
```

If you just did the following, typechecking won't flow through:

```
type ActionCreator<T, P> = (...args: any) => Action<P>
```

and of course the following won't work because you will rarely ever have all your arguments be the same type:

```
type ActionCreator<T, P> = (...args: Array<T>) => Action<P>
```

Libraries like `redux-actions` (which is what my example is creating a library definition for) need to be abstract enough while letting types flow through spread arguments. Tuples are the way for client code to specify the types of those arguments. Not having this features is a very large limitation.

**Comment by jedwards1211** [comment]
@faceyspacey in Flow 0.89 at least, it seems like using a tuple type for rest args does actually work, though only when you explicitly specify the tuple type (it doesn't seem able to infer a tuple type)
#7279

**Comment by SamChou19815** [comment]
Function params type can now be extracted into tuple via `Parameters` type now.
