### ISSUE TITLE
Confusing error origin reported for assignment between incompatible types

### ISSUE THREAD

**Issue by hayeah** [facebook/flow#324]
When developing with flow, I often see it reporting types errors away from where the the problems actually are, making it hard to know where I made the mistake.

A simple example of this unhelpful behaviour:

```js
/* @flow */
class Foo{};
class Bar{}; // 3: Bar incompatible with Foo

var foo: Foo = new Foo();
var bar: Bar = new Bar(); // 6: Bar incompatible with Foo

foo = bar; // 8: no error reported here

/*
assign.js:3:7,9: Bar
This type is incompatible with
  assign.js:2:7,9: Foo

assign.js:6:20,22: Bar
This type is incompatible with
  assign.js:2:7,9: Foo
*/
```

The error reported for line 6 is confusing, since on its own it's obviously correct. The actual error is on line 8, but nothing is reported there.

Let's see another example that involves arrays:

```js
/* @flow */
class Foo{}; // 2: Foo is incompatible with Bar
class Bar{}; //  3: Bar is incompatible with Foo

var foos: Array<Foo> = [];
var bars: Array<Bar> = [];

foos = bars; // no error report for this line

/*
array.js:2:7,9: Foo
This type is incompatible with
  array.js:3:7,9: Bar

array.js:3:7,9: Bar
This type is incompatible with
  array.js:2:7,9: Foo

Found 2 errors
*/
```

This is even more unhelpful. It tells me that I am confusing Foo and Bar somewhere in my code base, but I'd have no idea where.

The same problem exists for a few other constructs, all involving assignments.

Union:

```js
/* @flow */
class Foo{}; 
class Bar{}; // 3: Bar is incompatible with Foo;  3: Bar is incompatible with string

var foostr: Foo | string = new Foo();
var barstr: Bar | string = new Bar();

foostr = barstr;

/*
union.js:3:7,9: Bar
This type is incompatible with
  union.js:2:7,9: Foo

union.js:3:7,9: Bar
This type is incompatible with
  union.js:5:19,24: string
*/
```

Returned value from function call:

```js
/* @flow */

class Foo{}; // 3: Foo is incompatible with Bar
class Bar{};

function returnFoo(): Foo { // 6: Foo is incompatible with Bar
  return new Foo();
}

var bar: Bar = returnFoo();

/*
return-value.js:3:7,9: Foo
This type is incompatible with
  return-value.js:4:7,9: Bar

return-value.js:6:23,25: Foo
This type is incompatible with
  return-value.js:4:7,9: Bar
*/
```

Again, the errors reported are away from the true culprit.

Property assignment:

```js
/* @flow */

class Foo{};
class Bar{}; // 4: Bar is incompatible with Foo

class FooContainer{
  foo: Foo;

  constructor() {
    this.foo = new Bar(); // no error reported
  }
}

var fc = new FooContainer();
fc.foo = new Bar(); // 15: Bar is incompatible with Foo

/*
prop.js:4:7,9: Bar
This type is incompatible with
  prop.js:7:8,10: Foo

prop.js:15:14,16: Bar
This type is incompatible with
  prop.js:7:8,10: Foo
*/
```

In this case, `this.foo = new Bar()` on line 10 triggers an error report on line 5. 

The explicit property assignment on line 15 is reported with the correct origin.

**Comment by idoros** [comment]
+1

**Comment by avikchaudhuri** [comment]
We're doing an incremental revamp of how errors are reported. (In short, currently we blame endpoints, whereas we're moving to a model where we instead report the location of operations that bring these incompatible endpoints together). These examples are very useful tests for that work, thanks! We'll update you when we're closer to landing.

**Comment by Ptival** [comment]
+1, Flow has become pretty useless to me because of this issue...

**Comment by samwgoldman** [comment]
I just tested all of the above cases (thanks @hayeah for the excellent examples!). Since this issue was opened, changes to Flow's error handling have improved the messaging to a point that I think resolves this issue.
