### ISSUE TITLE
Typing React HOC with spread props

### ISSUE THREAD

**Issue by paulshen** [facebook/flow#3241]
I'm trying to type a React higher-order component similar to the one given in the example but I'm getting errors with transferring props. It seems that Flow isn't happy with the spread operator on a type that is used with `$Diff`.

[From the docs](https://github.com/facebook/flow/blob/f3d3fea5f0c0a6c729bdab6e119639b1ef582781/website/docs/ref/react.doc.js#L339-L345), this is the example of a HOC injecting props.

Here is [an example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqUArgHbV0cPmHR8AVqWoARcgVIAeAAp1sAZwA0YAMIAuEqwIA6bfVx9SfAgpBaVcdVpAA+ZwApUYMAGkzwywT62jDkamoK2s6oAJRBIWEKZFTGpjj+VgoAbnDoACZaACTS6FBQyqqaYADeuXKk+rLyAL7OWtl5rtWeYCwEPHgilPFqYKQAHvJ8uSNJ1CZ+FlZdXl4sU6R4btHLK6ukfQNgCr5pi0S18gC8VRZIjaRbTdVGLwQAFuhqRtgVT8DOnF2TW6wKaQA) of what I'm running into.

```
9:       return <Komponent date={new Date()} {...this.props} />;
                ^ props of React element `Komponent`. Expected object instead of
9:       return <Komponent date={new Date()} {...this.props} />;
                                                 ^ Props
```

[This works](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqUArgHbV0cPmHR8AVqWoARcgVIAeAAp1sAZwBcYAPIAjSdQA0YAMJayVAgDoT9XH1J8CCkMZVx1xkAD5vAClQwMABpO2FHAi0TGHI1NQUTb1QASiiYuIULahswhycFADc4dAATN1U1YyLS3zAAb0CwFgIePBFKdLUwUgAPeT4SrqzrWxxwp3rGoJYB0jw-ZMmg5abSFrawBVCxvKISuVIAXjqHJFl5BYBfeqtbggALdDUrbArr4G9OFcvGn8ugA). Note how I annotate `Props: Object` but have to remove the `$Diff` for this to work.

**Comment by tricoder42** [comment]
I'm having the same problem. The good thing is that following construct allows prop type checking for wrapped component, which is exactly what I needed. The only problem is spread operator above, so I suppressed the type checking for that line.

**Comment by lionelB** [comment]
@paulshen Thanks a lot for you solution. Having the same problem and it fixes it !

I've added a WrappedProps type to ensure Komponent is having a date prop

```typescript
type DateProp = {date: Date}
type WrappedProps<P, DateProp> = P & DateProp  

function injectDate<Props: Object, C: React.Component<*, WrappedProps<P, DateProp>, *>>(
```

**Comment by nmn** [comment]
Here's a working example with `$Diff` in place:
[LINK](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqUArgHbV0cPmHR8AVqWoARcgVIAeVGDDSANMrAAFOtgDOALjABvAL4aVAYSNkqBAHSX6uPqT4EF67br1qw5PgBPAD5UYIAKTQBpZ2E3AiNLGHI9PQVLUIBKROTUhVtqR1jXd08-ABJpdCgoBR04fT9jABM5UiNZeVNgvwCQ4JNNSly9MAB1PHJsbFJmsFIAD3k+ZtGChyccONKQP13kAeNNFRYV0jxwzMGVG7AWAh48EQUYrZKiVvkAXmNXJE7SJdTCZ7KCCAALdB6ezYHzA4DBTi3UyaFEnUgPJ7jSbTWacUxAA)

**Comment by lionelB** [comment]
@nmn thanks for the answer. I can't understand why explicitly specifying react component generics for the returned Class not working
I thought using `<D, $Diff<Props, {date: Date}>, any>>` in favor of `<*, *, *>` should work but that's not the case. What the difference between explicitly specifying react component generics `extends React.Components<D, P, S>` vs function return typed `(): Class<React.Component<D, $Diff<Props, {data: Date}>, any>>`
