### ISSUE TITLE
`implements` and "Did not expect BoundT"

### ISSUE THREAD

**Issue by alexeygolev** [facebook/flow#3243]
Here is the [tryflow](https://flowtype.org/try/#0JYOwLgpgTgZghgYwgAgLJwA4bgIwDYQA8AggHzIDeAUMsgLaaEBCpAFDAFzKvECUyAXnJNeXdFlwFmpKgF8qVBHjgBnFWjgBPHETLJgdDAToRw68dny7y1WgDc4eLsQDcNZAgD2IFWCgBXBDBPKFYAD2d+W1pkMAALYBUAOgc8QWQw93laBgxpdhBnQWFRDW0iFkp3WigIMH8oEGQQCAB3Mp0C1njElMdeXiy5KiA)
Not sure if it's a bug or the way I'm using it.
I couldn't find a similar use case in flow tests.

**Comment by mroch** [comment]
@samwgoldman you're probably the best one to look into this.

looks like it ends up doing an `InstanceT ~> ImplementsT` where it compares the two `map` methods, but at least one hasn't been specialized for whatever reason (I think that's the bug?) so it does a `PolyT ~> PolyT` where the `A` from the interface hasn't been subst'd.

**Comment by samwgoldman** [comment]
drat! investigating...
