### ISSUE TITLE
Flow doesn't parse trailing commas for array pattern in arguments

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#3247]
```js
a = ([s=1,]) => 1;
var [s=1,] = 1;
```

throws `Unexpected token =>`

but

```js
[s=1,] = 1;
```

doesn't.

**Comment by xjamundx** [comment]
Potentially similar to this bug I just found:

```
 const [a,] = (await b)
```

Which returns:
```
558:   ] = (await Promise.all([
       ^ Unexpected token ]
```

I'd just change it a bit, but `prettier` forces me to format it this way 😂

**Comment by vjeux** [comment]
What version of flow are you using? It seems like it works on recent version of flow.
https://prettier.io/playground/#N4Igxg9gdgLgprEAuEACAhgZwJ5TKgMwFc8YBLaQgCgEpVgAdKVFyKTGVAbXQBoBdVAF5UVdAHd0ZTgCMaTAL4heICAAdy0TMlBYYyAugA2mOCpkAndGADWcGAGU11slADmyGBaJmQAEwgwA2NTFQArTAAPACErW3sHdABbOAAZVzhgk18IIhg1PIAmLNCQZwtTC2QQAiMIcWUyi1cYAHUyPxgAC2QADgAGFVMksk9vX0xXNyM4AEUiCHgS3xh0GXbOnqRClS8pIymAYQgkpPRqqGhMlSJTABU17SRDbIUFIA

What do you mean by `prettier` forces me to format it this way? Prettier doesn't put a trailing comma without a new line afterwards. Could you explain your setup?

**Comment by xjamundx** [comment]
Our real code is more like:

```
const [
    oneThingGoesHere = false,
    { reallyLongThingA, reallyLongThingB } = {},
  ] = responses
```

We use `"trailingComma": "all",` in our prettier config.

And we're on `+ flow-bin@0.31.1` and it gets choked on that line with this error:

```
controllers/transfer/helpers/index.js:558
558:   ] = Promise.all([
       ^ Unexpected token ]
```

**Comment by vjeux** [comment]
0.31 is more than a year old, I'm afraid that you'll have to upgrade in order to get the fixes.

![image](https://user-images.githubusercontent.com/197597/32354469-0b001338-bfe7-11e7-9c75-7428c1680614.png)

**Comment by xjamundx** [comment]
oh man. package-lock got me again, I thought I had just updated 😂

**Comment by mroch** [comment]
i can't figure out which commit fixed this, but based on Try Flow, it seems to have been something in 0.51

**Comment by vjeux** [comment]
Thanks <3
