### ISSUE TITLE
React {...props} does not work with Intersections

### ISSUE THREAD

**Issue by jeresig** [facebook/flow#3251]
A reduced case:

```
type A = {a: string}
type AB = A & {b: string}

const Test = (props: AB) => <div/>;
const Foo = (props: AB) => <Test {...props}/>;                    // fails
const Bar = (props: AB) => <Test a={props.a} b={props.b} />;      // ok
```

On [Try Flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4CGAXGAM4YBOAlgHYDmAvprgYQEKkiYAGQUARrQYsO3VAGM4rBmAAqeFWQAUORnBx1aAgJSkAfGAA8AE2YA3YGYDcCpSoBicOEJ16DR-lMSC0t1FXIAOijdfTpORycwJOSU1NTgYDAoSmYYOldlDDB+SkYfGP8iQPMrMKLKEnIKugjKTjBxRuaI8XaEtIywOABrIA).

This only appears to happen if the type was composed from an intersection.

**Comment by thejameskyle** [comment]
Updated title. Just so you know: `&` is for intersection types, `|` is for union types.

**Comment by jeresig** [comment]
@thejameskyle whoops - sorry about that! Updated the post body, too.

**Comment by JelteF** [comment]
This is very likely related to: https://github.com/facebook/flow/issues/2411

**Comment by asolove** [comment]
As of Flow 0.53, the provided code now type checks as expected.
