### ISSUE TITLE
Possibly-undefined properties aren't detected properly

### ISSUE THREAD

**Issue by jeresig** [facebook/flow#3252]
Simple case:

```
type Result = {
  model?: {
    getURL: () => string,
  },
}

const View = ({result}: {result: Result}) => {
  if (!result.model) {
    return null;
  }

  return <a href={result.model.getURL()}>
    <img src={result.model.getURL()} />
  </a>;
};
```

On [Try Flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAzgK4wZgC8YA3qmGALZwAmeMA-AFz2NMwAczwYAqoQAyfABQBKGgD4wJDACcAlgDshAGgEBffQfQBjOFtVgAahrxJaMumtIUMBvs9eU+xcpQMFamUGJg0oMBkAQhd-DAA6Vg4YBVDBFwwyNS0wLQoYAG5DdCYMrJyAHgBDMAALFyhqLzjE9k54kXEpeQNFASYKjWYhFTVTJti3VuSO0QlJHrBgPoHgKsUigwKgA).

The first call to `result.model.getURL()` is marked as an error as "Method cannot be called on possibly undefined value". This is especially odd as 1) The check at the top of the function prevents that and 2) The second call isn't thought to be an issue.

Ensuring that the object is not a property seems to solve the issue, so this definitely seems to be a bug:

```
type Result = {
  model?: {
    getURL: () => string,
  },
}

const View = ({result: {model}}: {result: Result}) => {
  if (!model) {
    return null;
  }

  return <a href={model.getURL()}>
    <img src={model.getURL()} />
  </a>;
};
```

On [Try Flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAzgK4wZgC8YA3qmGALZwAmeMA-AFz2NMwAczwYAqoQAyfABQBKGgD4wJDACcAlgDshAGgEBffQfQBjOFtVgAahrxJaMumtIUMfOqw4wDBjy-JKPmJAjAMFamUGJg0oMBkAQi9OBWjBFwwyNS0wLQoYAG5DdCYMrJyAHgBDMAALFyhqT3ZOADoRcSl5A0UBJgqNZiEVNVMm5Jh20QlJbrBgXv7gKsUigwKgA).

**Comment by vkurchatkin** [comment]
That's expected behaviour. Since objects are mutable, Flow assumes that calling functions might invalidate refinements.

> The second call isn't thought to be an issue.

It's actually a first call, but JSX makes it look like it's a second.

**Comment by kevinbarabash** [comment]
I would be nice if there was a way to mark functions as non-mutating.  Then if only non-mutating functions are called between the refinement and actually using the refinement, it should still be fine to use it.

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/2715

**Comment by jeresig** [comment]
@vkurchatkin Interesting, ok! Thank you for the link to the additional discussion on this. Appreciate it!
