### ISSUE TITLE
Allow only es5 code to be used

### ISSUE THREAD

**Issue by Bnaya** [facebook/flow#3253]
I want to write a project which only es5 code is allowed
Means for instance it should throw error for `Promise` references or when using es6 array features like `Array.from`

In typescript you can do that using the lib compiler option, its very versatile.
you can pick one or more of these:
► ES5 
► ES6 
► ES2015 
► ES7 
► ES2016 
► ES2017 
► DOM 
► DOM.Iterable 
► WebWorker 
► ScriptHost 
► ES2015.Core 
► ES2015.Collection 
► ES2015.Generator 
► ES2015.Iterable 
► ES2015.Promise 
► ES2015.Proxy 
► ES2015.Reflect 
► ES2015.Symbol 
► ES2015.Symbol.WellKnown 
► ES2016.Array.Include 
► ES2017.object 
► ES2017.SharedMemory

**Comment by TrySound** [comment]
Linters and tests better fits to this IMO
