### ISSUE TITLE
I don't know what Flow is telling me

### ISSUE THREAD

**Issue by WhyEvenTry** [facebook/flow#3255]
Flow 0.38, Windows

WHAT error? It mentions a project file and when I remove the flow-check comment from it there is no error, but I have changed _every single Flow type_ in that file to read `any` and still get that error, An error that only contains Flow-internal information, apart from the file name nothing about my project at all.

The sentence _"This type is incompatible with."_ has a nice touch too.... incompatible with _what_ exactly? Why go to the movies when you can get all the tension and excitement from a Flow type check? "This error report will be further expanded on in the next episode."

```
lib/storage-unversioned-objects.js:0
inconsistent use of library definitions
645:     static all<Elem, T:Iterable<Elem>>(promises: T): Promise<$TupleMap<T, typeof $await>>;
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type. This type is incompatible with. See lib: ../../../AppData/Local/Temp/flow/flowlib_17592b4/core.js:645
630:       resolve: (result: Promise<R> | R) => void,
                             ^^^^^^^^^^ Promise. See lib: ../../../AppData/Local/Temp/flow/flowlib_17592b4/core.js:630

Found 1 error
```

**Comment by thejameskyle** [comment]
@WhyEvenTry can you leave an example of code that caused this error?

[Here is some related examples of usage](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqAIbTQCMAPACoB8AFEQE6MBcoAgs0QJ4UAKjWAFtcAZwCm1GjQCUbAcLGTOjHlJqgA3olChG47KkaEFIiQDoS0BsxkBuRAF9kVsnQDaO0KaXn9o2GgAN3E6MhkAGi8fC39AkLpsRlRxSOjBM3E-cQDg0IBybAALfXF8mUQAXRlzYvF0Ojp-VGhsUTYVNXRUIQAjcUZQAB9QXthA8SJCEdEk3HQAc1lQAF4NbV0QUHMdp3tkNCw8AmJSACYKdgjQACFrgGF6JlZQdxjlGmv3ihvP7wylBRHtV5ACJBR3Fdbg9KusvPpDMZ-ooLFYbIx9s5EFYzh50iisnE8mE0rp3tlcgkkilScjMhT4gViqVylUanUGk0ci02mx3N0+gNrmMJlNrrNGPMFtVVnDNmAduY9g4gA).

**Comment by WhyEvenTry** [comment]
The problem is I have not changed anything in that particular file for quite some time, and since I run Flow regularly and this error is new (I always have zero errors), fresh as of this evening, I don't see how it even _could_ be anything in that file. Also, since I declared every single item "any", if it really was something in that file, the error should have gone away, no? And if it _was_ something in that file, why doesn't Flow give me a place?

It's not the first time I get a Flow error that doesn't point to a place, but it's the first time I was unable to find the location by trial and error, removing files and functions from Flow inspection and checking when it starts to complain. Doesn't work here, if the file is out, no error (but the file is unchanged and never caused an error before!), if it's in but with ALL its types set to "any" the error is there.

**Comment by gabelevi** [comment]
If you run `flow check --traces 100` each error will be printed with a pretty unreadable trace of what Flow is doing. If you scan through the trace, it should mention a file that you have touched recently. That should help you debug.

If you figure out how to trigger this error, we'd love to know! @mroch has done a lot of work getting rid of these terrible "inconsistent use of library definitions" errors, but there are a few more hanging around that we'd love to kill!

**Comment by WhyEvenTry** [comment]
Yes that's valuable.

Found it, in a different file, an unusual construct to be sure but nothing _too_ horrible I'd say (the least important function of the whole project).

I don't have a promise to return to the caller so I create a new one, but then I have a promise inside the callback because I call my already promisified `delete` function. Definitely inconsistent, I would not leave it like that if it wasn't really the last significant function of all, and otherwise it's correct and not even hard to read either I think - something I care more about than "elegance".

```javascript
module.exports.cleanTempFiles = function (): Promise<string[]> {
    return new Promise((/**Function*/ resolve, /**Function*/ reject) => {
        fs.readdir(STORAGE_DIR, (err: ?ErrnoError, files: string[]) => {
            if (err && err.code === 'ENOENT') {
                reject(new FileNotFoundError(err, STORAGE_DIR));
            } else if (err) {
                reject(new StorageError(err));
            } else {
                Promise.all(
                    // Temp. file names start with "tmp-", see createTempFileName()
                    files
                    .filter(f => f.startsWith('tmp-') === 0)
                    .map(deleteFile)
                )
                .then(resolve)
                .catch((err: Error) => reject(new StorageError(err)));
            }
        });
    });
};
```
