### ISSUE TITLE
Nested object types not working as expected

### ISSUE THREAD

**Issue by dounan** [facebook/flow#3265]
The weird behavior is illustrated in the link below:

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCWAdnXgE4BcYAkgHKcCiASgH1CAGlQBfANzps+Dt35DSFKmChw4bOgFcAtgCNmoydNwEAQksrV6jVnN6CzRqZlP2FFsldXrNug0yi1HoAhnba+obiLlBadADGGDRwdKoAFAAebIQAlBRi6DB4GGBYljbMbORqGmAAjMJgoXYATGLGRSUAXmyepTFpWDlSnWBdPWB9WBJgwMBgAOoAFmUAJnB4AM5gGEs02-EhWpsEIanMTHBMYCFQGMzpQwD8qEA

Any ideas on why this is happening?

**Comment by dmnd** [comment]
Is structural typing supposed to nest?

**Comment by jesseschalken** [comment]
I think the problem is that `foo(x: A)` would be allowed to assign an `INNER_A` to `x.inner`, so after you've called `foo(y)`, you can no longer expect `y.inner` to be an `INNER_B`.

But if that theory were correct I would expect marking all the properties (or at least `A.inner`) as covariant  to fix it, which it doesn't, but maybe that's a separate issue.

**Comment by jesseschalken** [comment]
Actually, marking `A.inner` as covariant does work, but only if you also explicitly annotate `y` as `B`.

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgDUAlgHYN4BOAXGAJIBy3AogCUA+oQA0qAL4BudNnxdegkaQpUwUOHA4MArgFsARq3HTZuAgCEVlao2bsF-YRZMzM5x0qtkb6zdv0jFnFqAwBDB11DY0k3KB0GAGMMOjgGdQAKAA8OQgBKCgl0GDwMMCwObwo7Vg5yDS0wAEZRMHCHACYJUxKygC9KlSw4jKw8mV6wPoGwKuGwYGAwAHUACywwABM4PABnMAxVun3EsJ1dgjD01hY4FjAwqAxWTLGAflQgA

**Comment by dounan** [comment]
Marking `A.inner` as covariant to prevent writes makes a lot of sense.

But it also works if you mark either [`A.inner`](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgC0AlgHYN4BOAXGAJIBy3AogCUA+oQA0YYMDABhOAwwsAhgDdFLOovmoAvgG502fF16CRpClTBQ4cDgwCuAWwBGrUTv2ZcBAELnK1IzM7Mb8wj7uegbeoaZ+ZAFWNnZOrizu1M5qKS5uHuhQ9gwAxhh0clYAFAAeHIQAlBTa6DB4GGBY-kGsHOTWtmAAjOJZIQBM2lGt7QBeHPEdnlCVWPX602Azc2ALWLoSUgAqABZ0AM5gCHAsANZnqEA) or [`B.inner`](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCWAdnXgE4BcYAkgHKcCiASgH1CAGlQBfANzps+Dt35DSFKmChw4bOgFcAtgCNmoydNwEAQksrUAtPUas5vQWeFhgwMAGE4dDEwCGAG7+TDT+vuJSmKaOChZkVqrqmroGTKLUeiEp+oaR6FBadADGGDQ+qgAUAB5shACUFGLoMHgYYFiWdsxs5GoaYACMrlkOAExikm4eMgRwUB20AM60dFDMTHgAJqit7QBebPEdUVCVWPVSe2D7h2DHWBLTYAAqABY0KwhwTADWS6ggA) as contravariant.

I'm not too familiar with these variance relationships, especially on objects. Any ideas on why these "fixes" work?

**Comment by jesseschalken** [comment]
See https://flowtype.org/blog/2016/10/04/Property-Variance.html

But it's basically as you said, covariance means read-only, so you know `f(y)` isn't going to assign an `INNER_A` to `y.inner` (since an `INNER_A` may lack a `bar` property, that would make `y` incompatible with `B`), so passing a `B` becomes okay.

Marking `B.inner` as contravariant shouldn't work IMO, since you can't treat a read-only (contravariant) property as a read-write (invariant) one....and indeed it doesn't work if you annotate `y` as `B`.

As for why the `y: B` annotation is actually needed, it would be because without type annotations Flow goes into inference mode for object literals (mentioned [here](https://flowtype.org/docs/objects.html#adding-properties)) where it gathers upper and lower bounds for all the properties based on the way the object is used, and while I'm sure it's a great feature I find it very hard to predict or explain Flow's behaviour in that mode, so I put annotations wherever I can to pin things down.

**Comment by jesseschalken** [comment]
A Flow dev would be able to better explain the behaviour without the `y: B` annotation.

**Comment by dounan** [comment]
Thanks for the insights! I think I'm slowly starting to get it.

```
Marking B.inner as contravariant shouldn't work IMO
```
This does work (not sure why...). Check out:
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCWAdnXgE4BcYAkgHKcCiASgH1CAGlQBfANzps+Dt35DSFKmChw4bOgFcAtgCNmoydNwEAQksrUAtPUas5vQWeFhgwMAGE4dDEwCGAG7+TDT+vuJSmKaOChZkVqrqmroGTKLUeiEp+oaR6FBadADGGDQ+qgAUAB5shACUFGLoMHgYYFiWdsxs5GoaYACMrlkOAExikm4eMgRwUB20AM60dFDMTHgAJqit7QBebPEdUVCVWPVSe2D7h2DHWBLTYAAqABY0KwhwTADWS6ggA

Marking `A.inner` as contravariant also works:
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgC0AlgHYN4BOAXGAJIBy3AogCUA+oQA0YYMDABhOAwwsAhgDdFLOovmoAvgG502fF16CRpClTBQ4cDgwCuAWwBGrUTv2ZcBAELnK1IzM7Mb8wj7uegbeoaZ+ZAFWNnZOrizu1M5qKS5uHuhQ9gwAxhh0clYAFAAeHIQAlBTa6DB4GGBY-kGsHOTWtmAAjOJZIQBM2lGt7QBeHPEdnlCVWPX602Azc2ALWLoSUgAqABZ0AM5gCHAsANZnqEA

Trying to make sense of this stuff makes my head hurt O_o

**Comment by dounan** [comment]
I think I was able to simplify the example down a bit.
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCWAdnXgE4BcYA-AM4ZP0DmAGlQBfANzps+MACFSFKrQbM23XnUEjxqGHgxgAHnPL1GrMAHIAFjXNjtusFjbEy+8Tr0AvNrNfigA

This example works with the same covariance + explicit typing fix as above. This fix makes the most intuitive sense to me.
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgDUAlgHYN4BOAXGAPwDOGLjAcwA0qAL4BudNnxgAQqQpUwjZuzC9+DYWMmoYeDGAAeHeWXIrWHAOQALOtYl6DYLB2Jkjk-YYBephS9UIA

Setting either A.inner or B.inner to contravariant in this example also works. This one still doesn't make sense to me.
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgC0AlgHYN4BOAXGAPwDOGLjAcwA0qAL4BudNnxgAQqQpUwjZuzC9+DYWMmoYeDGAAeC8itYcA5AAs6liXoNgsHYmSOT9hgF4d57ySA

**Comment by jesseschalken** [comment]
[This](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgC0AlgHYN4BOAXGAPwDOGLjAcwA0qAL4BudNnxgAQqQpUwjZuzC9+DYWMmooAVwYBjDHTgMwzPABNuhABQAPDoQCUHAG5w61xdWDAYADCAIYW5jBYYCHc3HQCFjx8gkJgRmEA5BhgLHgh1kqOAHQqrAoZUHBwGZLUxaUsCgz6MDCSougGxqbmlng23LJOHLLuYF4+fmABwWE5edbACPwYBBqC3IUlTKxFRgAWISyEGPYADK61YPU7jWQZ+3it1e3oMHjZjgrkDRwPdBkJKgZjdVGAANrwBBlABGcEM1j++wBqX0OHwjThCI4AFs6I4bABdYGBf4ZZTcNJwHE4EKmGHvMAIOgYfZgPEEgozADyAGlUFZbA5HJcSddtmDIYhYfCGIiuOstKj0TLsez8USxUlNAIKVSaXS6AyCMzWerOWK+QL+rYhiLJCCJWUpdDMbL5dqUmA0RiwFi5RxFQJiTNPVo9Qw4NkjNTafTGaa2UGAIRigBycDA0gIrBYcBYnE4YoAKo9cky6K0-QQQjlDKYcTmWHnGqz4QJ9qkYXh0vpuHgxYK7PZXGBrJNQWUyM0q2EuYEh0NR9Y4HhKZOWHtDsdThdU6ggA) is how I _thought_ it was supposed to work, and I made it so it would throw a runtime error if run to demonstrate the Flow is in fact missing a type error.

If you annotate `x` as either `A` or `B` you get the appropriate error. Without an annotation, Flow lets it pass. :(

**Comment by jesseschalken** [comment]
@gabelevi @samwgoldman @mroch Can anyone explain why Flow accepts the code below?

```js
function a(x: {-inner: ?string}): void {
  x.inner = null;
}

function b(x: {inner: string}): void {
  x.inner.charAt(0);
}

let x = {inner: 'hi'};
a(x);
b(x); // Uncaught TypeError: Cannot read property 'charAt' of null
```

I really want to use Flow but every time something like this comes up the apparent unpredictability scares me off.

**Comment by SamChou19815** [comment]
These examples no longer errors.
