### ISSUE TITLE
No type inference for Array.isView()

### ISSUE THREAD

**Issue by leoselig** [facebook/flow#3267]
**Problem:**

I have the following function with a union-based parameter overloading.

```javascript
type TypedArrayType = Uint8Array | Uint16Array | Uint32Array;

export function(val: string | TypedArrayType): string => {
  const md = forge.md.md5.create();

  if (ArrayBuffer.isView(val)) {
    updateForgeMd5WithTypedArray(md, val);
  } else {
    md.update(val);
  }

  return md.digest().toHex();
};
```

As you can see I'm using [`ArrayBuffer.isView()`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/isView) to distinguish strings and typed arrays. 

However, flow throws:
```
updateForgeMd5WithTypedArray(md, val);
                                 ^^^ string. This type is incompatible with the expected param type
```

because it does not recognize that `Array.isView()` will ensure `val` to not be a string.

**Workaround:**
Replace `if (ArrayBuffer.isView(val))` with `if (val instanceof Uint8Array)`.

**Comment by arboreal84** [comment]
> Replace `if (ArrayBuffer.isView(val))` with `if (val instanceof Uint8Array)`.

`ArrayBuffer.isView` will return true for all typed arrays and `DataView`. Typed arrays are not only unsigned integers but also signed integers, and single-precission/double-precission floats.
