### ISSUE TITLE
Vague error message: Not_found

### ISSUE THREAD

**Issue by evansimmons-ck** [facebook/flow#327]
When I run flow check in my project all I get is:
```
.../components/nav.jsx:
Not_found

Found 1 error
```
What is this supposed to mean?

**Comment by gabelevi** [comment]
So `Not_found` is an uncaught OCaml exception. It's a little tricky to debug what is going on without a little bit more context. I don't suppose you have a small repo case or that you're running on an open source project? Also which OS are you running on?

**Comment by evansimmons-ck** [comment]
Here is what is in the file:
```
/* @flow */
'use strict'
var React = require('react')

class Nav extends React.Component {
  render() {
    return (
      <nav id="navslider">
        {this.props.links.map(l => <TrackedAnchor {...l} key={l.content} />)}
      </nav>
    )
  }
}

class TrackedAnchor extends React.Component {
  render() {
    let {content, ...rest} = this.props
    return (
      <a {...rest} data-target="#" role="button">
        {content}
      </a>
    )
  }
}

module.exports = Nav
```

**Comment by gcanti** [comment]
Hi, same error:

folder structure:

```
node_modules
src
 +- .flowconfig
 +- main.js <-- @flow pragma here
```

`.flowconfig` file:

```
[ignore]

[include]
../node_modules/debug

[libs]

[options]
```

commands:

```
myproject> cd src
myproject/src> flow check

... .../src/main.js: 
Not_found
```

---

Then I tried to move the `.flowconfig` up and **it seems to work**:

folder structure:

```
node_modules
src
 +- main.js
.flowconfig <-- .flowconfig in the project root, at the same level of node_modules
```

`.flowconfig` file:

```
[ignore]

[include]
./node_modules/debug

[libs]

[options]
```

commands:

```
myproject/src> cd ..
myproject> flow check

Found 0 errors
```

**Comment by ChristopherBiscardi** [comment]
Moving the `.flowconfig` to be in the same directory as `node_modules` (they are both one directory up from the project now) fixed this for us even though all of our paths are written globally:

```
[ignore]
/opt/hub/app/scripts/build/*
/opt/node_modules/jsxhint

[include]
/opt/hub/app/scripts
/opt/node_modules

[libs]
/opt/hub/flow-libs

[options]
```

**Comment by jareware** [comment]
I'm seeing the same issue, though I'm not sure moving `.flowconfig` up to `node_modules` (e.g. oftentimes the project root) is a valid workaround as for instance declarations [have to live](http://flowtype.org/docs/declarations.html#declarations) outside the scope of `.flowconfig`.

**Comment by garthk** [comment]
Just ran into `Not_found` here on a file named `test/lib/bench.js`. I'm not sure I can work around it, as `.flowconfig` is already at the same level as `package.json` and `node_modules`. My `.flowconfig` has both `lib` and `test` in `[include]`. Adding `test/lib` doesn't help.

**Comment by volkanunsal** [comment]
Same issue here.

**Comment by AbeEstrada** [comment]
Same here with this `.flowcongif` file

    [ignore]
    .*/node_modules/*
    
    [include]
    
    [libs]
    
    [options]

**Comment by teppeis** [comment]
This repo is demo of this error.
https://github.com/teppeis-sandbox/flow-notfound-error

**Comment by mwq27** [comment]
Getting the same error.
Here's my .flowconfig
```
[ignore]
/Users/mw/Projects/flowProject/node_modules/.*
/Users/mw/Projects/flowProject/bower_components/.*

[include]
/Users/mw/Projects/flowProject/js/Stores/OrderStore.js

[libs]

[options]
```

**Comment by adamellsworth** [comment]
Also getting the same error as @AbeEstrada.

    [ignore]
    .*/node_modules/*
    .*/public/*

    [include]

    [libs]

    [options]

**Comment by bhosmer** [comment]
Hey folks - the next deploy of Flow will fix at least one cause of the "Not_found" error, which had to do with package.json files in [include] paths not getting picked up. Looking at the .flowconfigs reported here, I'd guess it'll fix at least some of the instances, but maybe not all. I'm going to mark this fixed in next release, but please check after we deploy and note here if your problem persists. Thanks!

**Comment by Raynos** [comment]
Running into this as well with

```
[ignore]
.*/node_modules/.*
[include]
app.js
[libs]

[options]
```

**Comment by Raynos** [comment]
On second thought; i just realized ignoring node_modules is a bad thing!

```
/home/raynos/uber/autobahn/app.js:10:26,56: counted.js
Required module not found
```

Once I ignored `.*/node_modules/ready-signal/.*` flow said "required module not found" for `require('ready-signal/counted.js')`.

It's the ignoring of a critical module in node_modules that's causing the issue.

**Comment by jareware** [comment]
Yeah, I feel this is something the docs could also improve upon: how to - in practice - set up a typical Flow-enabled project, complete with `node_modules` and some (working) declarations. Or just provide a "seed project" in GitHub somewhere that you can clone and start building on.

**Comment by sporto** [comment]
Same issue here, this is my config:

```
[include]
./client/

[ignore]
.*/node_modules/*
./package.json
.*/app/assets/*

[libs]
./.flow
```

**Comment by seanhess** [comment]
@sporto. Don't ignore node_modules or package.json

**Comment by AbeEstrada** [comment]
@seanhess is that really the solution?

**Comment by seanhess** [comment]
@AbeEstrada it was for me. Read the previous comments about people moving their package.json around. I don't think ignoring node_modules is related to this issue, but you don't want to ignore it because flow reads it for module imports.

**Comment by volkanunsal** [comment]
When I don't ignore `node_modules` this is what happens:

![screen shot 2015-04-16 at 6 54 54 pm](https://cloud.githubusercontent.com/assets/151600/7193079/2256a4bc-e46a-11e4-8a51-f345332df83d.png)

I think that's why I started ignoring it in the first place. Does it ever not throw a huge number of errors when you don't ignore `node_modules`?

**Comment by bhosmer** [comment]
Hi folks - two fixes in the latest Flow (0.9.1) that will help here: 
* `package.json` files are now properly picked up from `[include]` dirs
* file existence tests are now case-sensitive even on Mac - some `Not_found` errors were happening in edge cases where there were case-insensitive overlaps between dir names and/or filenames and/or `@providesModule` names

Interested to hear about outstanding issues that are *not* cleared up.

Also, per the idea of an example real-world .flowconfig setup: definitely hear this. FYI, [react native](https://github.com/facebook/react-native) now delivers a fresh .flowconfig with newly created projects. :)

**Comment by avikchaudhuri** [comment]
Issue seems resolved, OK to close?

**Comment by samwgoldman** [comment]
Closing. Please reopen if you run into this error message again.

**Comment by aadsm** [comment]
I still get this error when I have a static getter (that is being ignored via suppress_comment) and a property type hint.
Works as expected when the getter is not static.

```javascript
// @flow
class IgnoreGetter {
  // $FlowIssue - get/set properties not yet supported
  static get foo() { return 0; }
  bar: number;
}
```
```
$ flow version
Flow, a static type checker for JavaScript, version 0.18.1
```

I don't have the power to re-open this issue though.

**Comment by mroch** [comment]
@aadsm the example you posted doesn't cause a `Not_found` error for me anymore, so closing this again. if it still repros, or if it gives a different error than `Not_found`, please create a new issue. thanks!
