### ISSUE TITLE
Did you forget to declare type parameter `DefaultProps` of identifier `Component`

### ISSUE THREAD

**Issue by ericls** [facebook/flow#3271]
Whenever I use 

```javascript
MyComponent.defaultProps = {
    ...something
}
```

after `MyComponent` is created by

```javascript
class MyComponent extends Component {
    ...
}
```

flow gives the error:
```
object literal. This type is incompatible with undefined
Did you forget to declare type parameter `DefaultProps` of identifier `Component`
```

**Comment by TimSusa** [comment]
This is a bug I would say... suffering the same here at the moment

**Comment by nmn** [comment]
This is type error. Flow has already inferred the type for your class before you try to mutate the defaultProps property.

And since you didn't give it a type it was inferred as `void`.

```typescript
class MyComponent extends Component {
    static defaultProps: Object;
}
```

This should fix it.
