### ISSUE TITLE
Question: Support for JavaScript in html files?

### ISSUE THREAD

**Issue by JdKock** [facebook/flow#3272]
Is it possible to use Flow for JavaScript in html files ?

I'm using Polymer to building Web Components and it would be nice if I can check the JavaScript in the html files.

**Comment by blake-newman** [comment]
Linked to https://github.com/facebook/flow/issues/2691

**Comment by vkurchatkin** [comment]
Duplicate of https://github.com/facebook/flow/issues/2218
