### ISSUE TITLE
Question: Do you plan support to check branches to match return type?

### ISSUE THREAD

**Issue by yury** [facebook/flow#3274]
It would be very cool too also check all possible branches.

Right now `result.field =` anywhere in the function body removes all errors, but actually we got broken object on return.

```js
/* @flow */

type BlaType = {
  field: string
}

let condition = false;

function foo(): BlaType {
  let result = {};
  if (condition) {
    result.field = 'nice';
  } else {
    //... no field assigment. result is wrong type
  }
  return result;
}
```

[Flow | Try Flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCMAhgCq4EC8YA3qmGFAJZ4wAmAXGAM4YBOzAHYBzVAF90MPBjABjOEPbMMzRWBpQSMHngDc6KAFchc1eqhw4ACgCU3YuUp0GYabP54eRmLJq1xA0ZmKDBrBSUVNSFbFwBIRk9vXwA6FjZ2DTAAciFmOTxsoLBxMDZdF0ZGYGAUurAhOCZWDjASHh5mEQBbPCEMFLAkn1lmHjAEfkURMGx8V0lEmSN+ISGvEYNJIA)

**Comment by gkz** [comment]
Fixed: https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c
