### ISSUE TITLE
multiple function calls force flow error by ignoring if condition

### ISSUE THREAD

**Issue by mediabakery** [facebook/flow#3275]
I get an error _Property b not found in object literal_ for following code. When I disable `doSomething(data.a)` flow does not throw an error. Why is flow throwing this error? The code is only active if `data.a` and `data.b` is not undefined.

```
/* @flow */

function doSomething(input:mixed):void {
  // DO
}

const data = {
  a: "Foo"
}

if (data.a != null && data.b != null){
  doSomething(data.a)
  doSomething(data.b)
}
```

**Comment by AugustinLF** [comment]
It's a common misunderstanding, flow is pessimistic about function calls, and consider that doSomething might unvalidate your if check. After the first doSomething call, flow unvalidate the refinement it just did with the if check. [This](https://flowtype.org/try/#0GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFIQA4hQBcmMAHtsgJTUBucMyiA3gFCJEAeiGIAIgHk+AXz58ICAM5QUAQyirEAXl4DEq6ogBEAMThwjMuTGCISydaoB0mgIQ6wIADZfEAMj81DScAI0R3RE8fZj1UDBx8QlIHYNUYmzsU5zcPb18AoOcwiKivGME4rFwCYntHUJigA) works for instance.

**Comment by mediabakery** [comment]
Thanks @AugustinLF for your fast feedback !
