### ISSUE TITLE
Incorrect results from get-def

### ISSUE THREAD

**Issue by undeadcat** [facebook/flow#3276]
For this snippet, flow v.0.38.0:
```
var value = '';
var i = 0;
for (var j = 0; j < 10; j++) {
  //changing the switch variable to i changes the output
  switch (j) {
    case 0:
      value = 'zero';
      break;
    case 1:
      value = 'one';
      break;
  }
}
```
Trying to get definition of 'j++' returns range pointing somewhere inside switch statement.
```$ flow get-def flow-test.js 3 25```
6:5,8:12
Changing the variable used inside the switch from j to i gives what I would consider the correct result:
```$ flow get-def flow-test.js 3 25```
3:10,3:10

**Comment by undeadcat** [comment]
Still not fixed in 0.42.0.
I'm surprised at the lack of response. _Some_ kind of response would be nice, an aknowledgment that this is a valid issue, at least.
Is the problem that get-def is not supported?

**Comment by avikchaudhuri** [comment]
Sorry for the lack of response. `get-def` is definitely supported, but sometimes it points to weird locations, because it uses the underlying type inference machinery which can sometimes infer types from far-away uses.

**Comment by undeadcat** [comment]
Thanks, that's good to know.

But also not clear to me from your reply - is this a valid issue? 
or are we wrong in assuming get-def should return the place where the variable was defined, not where the type was inferred?

**Comment by SamChou19815** [comment]
This now works.
