### ISSUE TITLE
Unable to parse line

### ISSUE THREAD

**Issue by mrasoahaingo** [facebook/flow#3279]
I'm not able to figure out what is wrong with my flow config file.
I get this error when I try to execute flow on my CLI:

```
[ignore]
.*\/node_modules\/fbjs\/
.*\/node_modules\/stylelint\/

[options]
module.name_mapper.extension='scss' -> 'empty/object'
```

$ flow
Flow server launched for /<my workspace>/<my-project folder>
.flowconfig:6 Unable to parse line
Could not start flow server!

Thanks for your help :)

**Comment by mrasoahaingo** [comment]
Fixed by removing and installing flow-bin :)

**Comment by zzossig** [comment]
same problem. fixed after doing this.
before:
module.name_mapper = '^\(.*\)$' -> '<PROJECT_ROOT>/src/\1'
after:
module.name_mapper='^\(.*\)$' -> '<PROJECT_ROOT>/src/\1'

extra space was the problem in my case
