### ISSUE TITLE
Polymorphic constructor with Iterable argument makes class untyped

### ISSUE THREAD

**Issue by billschaller** [facebook/flow#3280]
When a class has a polymorphic constructor that accepts a union of `Iterable` and itself, flow silently bails out of type checking it, making instances of it equivalent to `Object` types.

Flow version: 0.38.0

Example constructor:

```js
  class Foo {
    _bar: Array<number>;
    constructor(arg: Iterable<number> | Foo) {
      if (arg instanceof Foo) {
        // execute clone behavior
        this._bar = arg.getBar().slice();
      } else {
        this._bar = [];
        for(let n of arg) {
          this._bar.push(n);
        }
      }
    }
  
  	// I don't want a setter for _bar.
    getBar(): Array<number> {
      return this._bar;
    }
  }
```

When I create an instance of this class, flow treats it as `Object`.

A plain function is able to refine the type of the arguments and typechecks fine.

[Full tryflow example of the problem and various attempts at a solution](https://flowtype.org/try/#0BQMwrgdgxgLglgewsAlAAgN4Cg1oPR5oAqAFnAM5pQA2AhuZSfWrWgA4LUCeAtggE5syUKknIx+YWALQwELatQQB3NAFN6XKkohwIAcwA0aAEZgYaEEtUATBGvIQA5DBz5CMLmzVQSPgNZocDDGMvpwAG5qLBBaavz8MrQmCOZoyiRcAHRoAJIWaiAgPvBR3LJeDkEQ4rTQVQggQa64BCyUAAZ1XB1ZbjT0lABiCPLYuLgA+ia0-ABcaACCCbRcADwQYDwm8QB8ANxuuFBiElJy-MCz+gv58cnUahtbO-y7aAA+aCMI6OMTuDgTSu-H01Vq9Ua31GfyOAPc6gAHj5zNEaEhojsmBFEPw4QCYGRyFlprM0ABeFigrL6NQwABCs1QWXI1DgUDUqEO8LQAF91NRyNF-jzCRQSTN+BS0ABtAC63J5lgEwEeFggaCh11hSomYuJpP4WTYYHIJGAEBQip5vPxfLhttwbgAkG1cmg7M4LMo6hZWEKYDB4sqpYa+gDaQymSgFst+Ktnts9pg7fw6WB+Br9RLZtb7XD0RBOTHoWNU+nM2gi6ofsB9VaHW5bVh+qdLNLq6XgDKAAxyhu4EA0umMy4oXty6VOWhOfYI-VoM2pag2Sy0ODUNxDyOj1AygCMk8pACZFScahYQKNJdLtyPo4qrwhJROpzO520F0uwCuFOR5CA66boOWTKDATSUj2H6EAAymoag8JQcimNEEDyJ43hUH4UD+HoYK0H6iiahqPzGMEQSUGhFgnFEaariYWhWCoWC8igXItqAkCwIgyA6gipAUNogxoEwlCsHwaF8IIwiiBekjSFKtBQBybDwAYMR5EG8YmI8OT5BU3i+AElAgHoajhgiADCOh4YuCG+uyYlpl67AIAwcA6dEhKpPoJBoHMeD9HQDClimAKGrGKzrJsSZvHm57iPJFwgjcmn3J5iavLsfEEkSOZSpS8p5oOKpqlWmpNNqYVKtmYYmmaFoDvCjoTC1Lpuh6SAuOkvosHZgbBleoaSnpaA8HAvnqggBRRBqPoQH6aCRlpIbNFk60uju0aRfG0UvMmIoTGmMAZlmeWGnmbW4M6hbFgsPzVQCCWXqMHZqDWozdv2xWyeImqEvEo63qMw5RmOP1DWgqp0uVUK1ZKOXwh1UB1N1ppeedI2suyxayPIZgbquAPaBi-nAHauDTX4-CjsaprmpaP0tQCx2ncqCCXU2LbHG2EFVu9XYTk1Q4vn2b6zvORJrhuYmUGoiKGUGNhblkL6HtKp6the7M3pSd5g+xJXPrMr6UtOEuflLtCCgBQGy0iitqMrIFgXzUEIgAmg4xgLoBMuiAkJTlHICAsWxDZYJx0DwEgqDVW6F4aKuWpCQwxhqkhDiLeA0c8bITAWDAtD+FU-pMJhSQasE6WPO0VL6BZbQCZQygCP49vy47NgWRh0REJUADqwQkHc2mPLkNRwDY0SUodszzEsUWZXsXODlxMdZsXDijwRAgAPL8P33gpbcWkPE8MVZZ8xCD8PO+eRP5BT2oJZxgml8HXCQJQ73WqghS5IzbPgAFYlCcGgAAZBA+uWR55oAAISUk2IoRGuBWaVmuLAhIl0BRCkehMZ6VICqygVHaSG0N1QVSIagiY886YNUZnaZmR0KwannpzXALVCGsEpEXEu5Ad4XAPkfTkQtFS0APEeNA5toJoA9qsH2UtW78HbvAsO7FI4524rHPibQAAydIkL8C0P6OA406CKTYGwRISk-LMGSAgKIeM0BplMkWfOaJThJSSKCIKwkHqHQiovXay84oFi8ecFU1xT41wvvtN418fg0O-nWSof8wSAKASYUBsBwFQIMmodJoMgaZOkVojeTgaGtEIPLFEQYSbuKxLQHEAgKb53FIaaUmCtpjhZGyDkhtmq4OFG0toA8SCjDYOQRRgkTDxmgH5OwDgXL+DQqoQkBF65jVNBYHYzRYnrQsqKTGZJCqkN1ENChsNKqgiqXqE5Rp6oMyajaJhjYnTXQ6p6bq81FoBhWpDMMcIemoB2u-eJ7xDpoNYe0g0koOH2lYhoqO2jeLx0IAYmARiTH6HXHNYefUzS0Ewr3aoJpC7oT8L9M4ClwRBloMnSqqdKB6AhByCybhSU-FyGaaUh1JRgr2rFA4q80B+JCgEuEArgnguFfFCJCkT5pTHnE4ViTRg8pIMk4Ev8bkZMAdIkBYDIHQMwTeRBVYfzUDuW0WpUBUQNMxGobEuI2nZl1jArG-TixM2GfggEYyJkICmTMygcy6i+E6ss7qqyVD502dcbZf09nVxVYct1eUPVFTaZcsqGp0l3NwO62Y9Dnk-U4W8gELVbRIqtEAA)

**Comment by SamChou19815** [comment]
Now we error as expected
