### ISSUE TITLE
Doesn't seem to handle module.exports/require correctly for classes

### ISSUE THREAD

**Issue by mockdeep** [facebook/flow#3284]
I have a class function in one file that flow reports an issue with. Everything works fine in the code, so not sure why it would be complaining on this. This is (something like) the code:

```js
// doc.js
var Doc = function (params) {
  ...
};

module.exports = Doc;

// elsewhere...
var Doc = require('doc');

var doc = new Doc({ some: 'params });
```

flow reports:

```
 57:       this.doc = new Doc(this.find('#doc'), doc_params)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ constructor call. Constructor cannot be called on
 57:       this.doc = new Doc(this.find('#doc'), doc_params)
                          ^^^ exports
```

What do I need to do to get flow to work for this?

**Comment by mwalkerwells** [comment]
You should annotate that it's a constructor function (flow doesn't infer that it's a constructor for exports I believe):

Have you tried:

````js
const Doc = function(params) {...}
module.exports = (Doc: Class<Doc>)
````

**Comment by mockdeep** [comment]
Is there a way to do that as an external declaration? I'm trying to avoid adding type declarations in the code for the time being and just take advantage of the type inference. I tried to follow the example [here](https://github.com/facebook/flow/issues/2249) but that didn't do the trick for me. Might be I'm declaring something wrong, though.

```js
declare module 'doc_editor/doc' {
  declare class Doc {
    constructor(): void;
  }
  declare module.exports: typeof Doc;
}
```

**Comment by mockdeep** [comment]
Just tried your solution as well, and that didn't seem to work either.

**Comment by SamChou19815** [comment]
This kind of constructor support is dropped a while ago
