### ISSUE TITLE
Interfaces don't assert constructor returns

### ISSUE THREAD

**Issue by jamiebuilds** [facebook/flow#3285]
```js
// @flow
interface FooI {
  constructor(): number;
}

class Foo {
  constructor() {
    return 'hi';
  }
}

const foo: FooI = new Foo(); // Works
```

[[Try](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAYrLAJKgDeioohsaAzhjgK6Eaw4AUASgBcoNBwC2AI1wBuRAF9khaPhYsyFWvUbM2nbr0FaGDHFgwccaUAHIAFihtyGixYiasMoSBRHkqoAC8oljwGrCCMqAgoADqvADWLEA)]

**Comment by SamChou19815** [comment]
We now correctly error on this, by forcing constructors must return void.
