### ISSUE TITLE
Missing relevant file/line number on error message

### ISSUE THREAD

**Issue by danvk** [facebook/flow#329]
When I run flow on [this tree][1], I get the following error:

```
/Users/danvk/github/pileup.js/types/types.js:1:1,5:1: GenomeRange
This type is incompatible with
  /Users/danvk/github/pileup.js/src/ContigInterval.js:41:18,31: ContigInterval

Found 1 error
```

This is just saying that two types aren't compatible. It doesn't say anything about where I attempted to convert the one to the other (which is where the error really is).

(FWIW the error is really on `src/BigBedDataSource.js:96:53`)

I'm on flow 0.6.0.

[1]: https://github.com/hammerlab/pileup.js/tree/bb3b62e4bd444d8160242ef4571186fb1a751257

**Comment by danvk** [comment]
This is completely maddening. Without line numbers, fixing type errors is a complete guessing game. @gabelevi any guesses on how to deal with this?

**Comment by avikchaudhuri** [comment]
You can use --traces to get some more line numbers.

**Comment by danvk** [comment]
When I use --traces on that tree, I get the exact same output as before:

```
$ flow check --traces

/Users/danvk/github/pileup.js/types/types.js:1:1,5:1: GenomeRange
This type is incompatible with
  /Users/danvk/github/pileup.js/src/ContigInterval.js:41:18,31: ContigInterval

Found 1 error
```

**Comment by Ptival** [comment]
Came here to post this. Unification error messages should ideally be something like:
- location where thing1 is expected to have type1
- location where thing2 is expected to have type2
- location where thing1 and thing2 are used in an incompatible fashion

Right now we just get the location of definitions of type1 and type2, which is almost irrelevant information to the problem. :(

**Comment by danvk** [comment]
Here's a fairly minimal repro:

```javascript
/** @flow */

class Foo {}
class Bar {}

function foo(x: Foo): boolean {
  return x ? true : false;
}

function foobar() {
  var b = new Bar();
  return foo(b);
}
```

The error is:

```
/Users/danvk/code/toy-flow/baderror.js:4:7,9: Bar
This type is incompatible with
  /Users/danvk/code/toy-flow/baderror.js:6:17,19: Foo
```

Line 4 (`class Bar {}`) is useless in the error. Line 6 (`function foo(x: Foo)`) is somewhat helpful.

The error message isn't useful until it mentions line 12 (`foo(b)`), which is where the error is.

**Comment by bolinfest** [comment]
Note this is also a problem when using `[libs]`:

```
# .flowconfig
[libs]
lib/
```

```
# lib/example.js
declare class TextEditor {}

declare function getActiveTextEditor(): ?TextEditor;
```

```js
# src/code.js
/* @flow */

function log(editor: TextEditor) {
  console.log(editor);
}

var activeEditor = getActiveTextEditor(); // Where Flow tells you to look.

log(activeEditor); // Where the problem is.
```

Output from running `flow check --traces` (note `--traces` does not help):
```

/private/tmp/flow-bug/src/code.js:7:20,40: null
This type is incompatible with
  /private/tmp/flow-bug/lib/example.js:1:1,27: TextEditor

/private/tmp/flow-bug/src/code.js:7:20,40: undefined
This type is incompatible with
  /private/tmp/flow-bug/lib/example.js:1:1,27: TextEditor

Found 2 errors
```

**Comment by danvk** [comment]
As of flow 0.11.0, the error for the [above example][1] has become:

```
/Users/danvk/code/toy-flow/baderror.js:12:10,15: function call
Error:
/Users/danvk/code/toy-flow/baderror.js:4:7,9: Bar
This type is incompatible with
/Users/danvk/code/toy-flow/baderror.js:6:17,19: Foo

Found 1 error
```

which is infinitely better. I'm going to close this out—I'll reopen if I run into it again.

[1]: https://github.com/facebook/flow/issues/329#issuecomment-91958931

**Comment by danvk** [comment]
Unfortunately, #409 means that while this is an improvement, it's not an improvement that matters for anything more complicated than a toy example. Once you get beyond a single module, the error is lost.
