### ISSUE TITLE
For-Of with object/array parsed as expression instead of pattern

### ISSUE THREAD

**Issue by danez** [facebook/flow#3291]
Consider the following two for-of loops:

```js
for ({x, y} of z);
for ([p, q] of r);
```

In both cases the flow parser is parsing the `left` field of the `ForOfStatement` as `ObjectExpression`/`ArrayExpression`, although the estree spec says it needs to be a Pattern.
https://github.com/estree/estree/blob/master/es2015.md#forofstatement
https://github.com/estree/estree/blob/master/es5.md#forinstatement

All other parsers also use `ObjectPattern`/`ArrayPattern`.

**Comment by lydell** [comment]
Possibly related:

```json
$ echo "for ({a = 1} of b);" | flow ast | jq .errors
[
  {
    "loc": {
      "source": null,
      "start": {
        "line": 1,
        "column": 8
      },
      "end": {
        "line": 1,
        "column": 9
      }
    },
    "message": "Unexpected token ="
  }
]
```
