### ISSUE TITLE
typeof triggers an error when checking existence of a property in a union type

### ISSUE THREAD

**Issue by gajus** [facebook/flow#3297]
Flow v0.38.

```js
/* @flow */

type DenormalizedAdoptQueryType = {
  adopt: string
};

type DenormalizedExtractQueryType = {
  extract: string
};

export type DenormalizedQueryType =
  DenormalizedAdoptQueryType |
  DenormalizedExtractQueryType;

(denormalizedQuery: DenormalizedQueryType): boolean => {
  return typeof denormalizedQuery.adopt === 'undefined';
};

```

Produces an error:

```
16:   return typeof denormalizedQuery.adopt === 'undefined';
                                      ^ property `adopt`. Property not found in
16:   return typeof denormalizedQuery.adopt === 'undefined';
                    ^ object type

```

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAieAdnAE4C2AhjAJYBeeAJgILNw4YCKArnuSwAVXAQC8YAN6owYahy4AuMAGcM5OiQDmqAL4BudNnxFSFGvSbMAogA911AMY9+gkSYnTZee+ScZlNQ1tPUNUHxwKDDBjAmIyKlpGFj4BYVEwMRlTBItktgUXNPcCAB9s+PMkqzsHZ1S3UTCACmYzRMsU1yxlSo78hvT8AEplACM4OBg8ahJMgD4pbPI8DF5yOdi4KDA23OqutIA6eU5osQuwAHJeEjaoTRYrwwMgA

Use case:

I want to check which type of input do I have (`DenormalizedAdoptQueryType` or `DenormalizedExtractQueryType`). I expect to be able to do it by checking for presence of a property.

**Comment by gajus** [comment]
This is such a basic use case that it is unlikely to be a bug. I am probably doing and overlooking something silly.

**Comment by gajus** [comment]
In this particular case, I have simply used `hasOwnProperty` to work around the issue.

```js
(denormalizedQuery: DenormalizedQueryType): boolean => {
  return !denormalizedQuery.hasOwnProperty('adopt');
};

```

**Comment by goodmind** [comment]
Adding `%checks` to this predicate makes error disappear

**Comment by SamChou19815** [comment]
This no longer errors
