### ISSUE TITLE
Parser: accepting invalid programs

### ISSUE THREAD

**Issue by DmitrySoshnikov** [facebook/flow#3298]
This might be non-critical "over-accepting" parsing, but Flow normally parses some invalid JS code (found while was playing with different parsers):

```js
break;
continue;
return;
{'x': x}
```

All these should be invalid per JS grammar.

**Comment by DmitrySoshnikov** [comment]
FWIW, just found another invalid acceptance:

```js
for (var k = 0 in s, x = 0; in foo) {}
for (var k = 0, s, x = 0 in foo) {}
```

**Comment by mroch** [comment]
yay, none of these parse anymore
