### ISSUE TITLE
Flow not detecting null check

### ISSUE THREAD

**Issue by lionize** [facebook/flow#3299]
I have included a null check on the optional `ids` parameter to a function, but I am receiving the error `call of method 'includes'. Method cannot be called on possibly undefined value` despite that.

```javascript
export const usersSelector = (userState: Object, ids: ?Array<number>) => {
  let userIds = userState.ids

  if (ids != null) {
    userIds = userIds.filter(id => ids.includes(id))
  }

  return userIds.map(id => userSelector(userState, id))
}
```

I have tried a couple of other null checks to attempt to make this work and all of them fail in the same way:

```javascript
const userIds = ids !=null ? userState.ids.filter(id => ids.includes(id)) : userState.ids

let userIds
if (ids == null) {
  userIds = userState.ids
} else {
  userIds = userState.ids.filter(id => ids.includes(id))
}

let usIds
if (ids) {
  userIds = userState.ids
} else {
  userIds = userState.ids.filter(id => ids.includes(id))
}
```

Am I doing something incorrectly or is Flow failing to notice the null check?

**Comment by mroch** [comment]
flow is concerned that the `id => ids.includes(id)` callback might not be called immediately (it doesn't know what `filter` actually does), and so `ids` might not still be `!= null`. if you make it a `const`, flow can be sure.

there are two ways to do that: something like `(userState: Object, ids_param: ?Array<number>) => { const ids = ids_param; ... }`, or by enabling the `experimental.const_params=true` in the `[options]` section of .flowconfig to make all function params const.

**Comment by lionize** [comment]
Thanks @mroch

**Comment by jedwards1211** [comment]
@mroch I don't understand, how could anything in that code possibly make `ids` `null` again after the initial null check?  Even if the callback is called later, I see nothing in the closure that can write the value of `ids` to begin with.

**Comment by rossPatton** [comment]
the key thing here for others hitting this thread is just using `const` instead of `let` when you do falsy checks with flow. even if you 'know' the value could never change, `const` guarantees it
