### ISSUE TITLE
on Windows: Unhandled exception: Sys_error("Invalid argument")

### ISSUE THREAD

**Issue by amcsi** [facebook/flow#3304]
Whe running `flow server` with Flow 0.35.0 on Windows: when detecting a change in a file, there's a high random chance that I see this outputted:

```
[2017-01-30 20:20:03] Merge prep
[2017-01-30 20:20:03] Re-resolving directly dependent files
[2017-01-30 20:20:04] Calculating dependencies
[2017-01-30 20:20:04] Merging
[2017-01-30 20:20:10] Done
Unhandled exception: Sys_error("Invalid argument")
```

Then the application terminates.

**Comment by jabacrack** [comment]
I have similar issue.  I use flow 0.37.4 with Webstorm. 
Often see in log 
`Error: Sys_error("Invalid argument")`
Most of time it go in pair with
```
Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
Called from file "src\server\serverProt.ml", line 102, characters 10-23
Called from file "src\server\server.ml", line 652, characters 14-51
Called from file "src\server\serverFunctors.ml", line 134, characters 6-43
```

**Comment by Kermit** [comment]
Is there any workaround?

**Comment by hackhat** [comment]
Same here.. I got this error only in latest webstorm

**Comment by Yaro77** [comment]
Intellij IDEA 2016.3.5 running on Windows same error

**Comment by Awk34** [comment]
Same on WebStorm 2017.1 (Build #WS-171.3780.79)
+ flow-bin@flow-win64-v0.42.0 npm package
+ Windows 10

```
[2017-03-23 14:53:35] Server is READY
[2017-03-23 14:53:35] Took 36.625000 seconds to initialize.
Error: Sys_error("Invalid argument")
Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
Called from file "src\server\serverProt.ml", line 103, characters 10-23
Called from file "src\server\server.ml", line 721, characters 14-51
Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
```

If I run `./node_modules/.bin/flow` in a console, Flow seems to execute fine.

**Comment by wasd171** [comment]
Same with WebStrom 2017.1, WIndows 10 and `flow-bin@0.43.1`

**Comment by Morphexe** [comment]
Any ideas on what might cause this ? 

this is what I get in the log 

> 
> [2017-04-12 07:24:33] Initializing Server (This might take some time)
> [2017-04-12 07:24:33] executable=C:\~~~\npm\node_modules\flow-bin\flow-win64-v0.43.1\flow.exe
> [2017-04-12 07:24:33] version=0.43.1
> [2017-04-12 07:24:33] Parsing
> [2017-04-12 07:24:35] Building package heap
> [2017-04-12 07:24:35] Loading libraries
> [2017-04-12 07:24:39] Running local inference
> [2017-04-12 07:24:40] Calculating dependencies
> [2017-04-12 07:24:40] Merging
> [2017-04-12 07:24:41] Done
> [2017-04-12 07:24:41] Server is READY
> [2017-04-12 07:24:41] Took 8.266000 seconds to initialize.
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> Error: Sys_error("Invalid argument")
> Raised by primitive operation at file "pervasives.ml", line 381, characters 12-32
> Called from file "src\server\serverProt.ml", line 103, characters 10-23
> Called from file "src\server\server.ml", line 721, characters 14-51
> Called from file "src\server\serverFunctors.ml", line 148, characters 6-43
> [2017-04-12 07:24:41] Status: Error

**Comment by DavidArutiunian** [comment]
Have same issue. Moreover `standard-flow` doesnt work in my projetc althoug I wrote it in `extends` rule

**Comment by fignuts** [comment]
[Here is the issue on Jetbrains issue tracker](https://youtrack.jetbrains.com/issue/WEB-23925) I am not sure if the error is with Flow or with Jetbrains products as flow seems to work fine with VS Code and Nuclide on windows.

**Comment by rastogitech** [comment]
Same issue on Webstorm 2017.2.5 and flow 0.53.0.

**Comment by mroch** [comment]
hi everyone, we've fixed a lot of Windows issues this year. our team only supports VS Code internally, but hopefully the improvements translate over due to the LSP.

I'm going to close this, please file new issues for anything that still crops up on recent versions (e.g. v0.185+). thanks!
