### ISSUE TITLE
Flow implicitly casts to `any` when accessing a property in a conditional from an imported type with indexable signature

### ISSUE THREAD

**Issue by STRML** [facebook/flow#3309]
This is a pretty weird one; discovered after an obvious type error was not caught by flow.

Please see [the reproduction repository](https://github.com/STRML/flow-refinement-bug).

We have noticed the following losses of type information.

The type:

```js
export type StringMap = {
  [key: string]: string;
};
```

Assume `foo` is of type `StringMap`.

```js
if (foo.bar) {
  // due to the above conditional, `foo` is now the `any` type
  const a:number = foo.bar; // Bug: not an error!
}
```

However, this *does not* happen in the following situations:

```js
const {bar} = foo;
if (bar) {
  // `foo` has maintained its type
  const a:number = foo.bar; // error as expected
}
```

Or even when explicitly casting to Boolean:

```js
if (Boolean(foo.bar)) {
  // `foo` has maintained its type
  const a:number = foo.bar; // error as expected
}
```

This issue does not appear to occur without the indexable signature.

Please see https://github.com/STRML/flow-refinement-bug for a reproduction with 0.38.0.

**Comment by STRML** [comment]
Added a failing test PR in #3320.

**Comment by mrkev** [comment]
Looks like this has been fixed ¯\_(ツ)_/¯ 

https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKMoEsB2BzAWQEMw4BeOAbwCg44BtAa2EQC44BnTXPAXXa7Z8AbmoBfUdQAmwAMYAbIlFQA3JXABmECOwxDCJSVg1wAFFogA6AEZKAlFVpwA9M7hSArqhgQEAC1QiawgVVFkIHCksGCwIonkAGjgAAwtkuCwOOBwIAHd-VGSiHER0pBQncJwuOCJWHA8AW2tgKHJNbRslYRc3ACEPPHYc+GK4VqhoAEJxIA
