### ISSUE TITLE
How correctly update flow?

### ISSUE THREAD

**Issue by svipben** [facebook/flow#3312]
Hello,

updated flow-bin with `yarn global add flow-bin@latest`. `yarn global ls` shows **"flow-bin@0.38.0"**. `flow version` shows **Flow, a static type checker for JavaScript, version 0.37.4**. How update flow to latest version?

OS: Linux Ubuntu 16.04
Yarn: latest

P.S. I also did reboot several times...

Thanks for any help!

**Comment by svipben** [comment]
Fixed.

1. Check where is flow - `whereis flow`
2. Remove it - `sudo rm -rf /usr/bin/flow`
3. Add Flow - `yarn global add flow-bin@latest`

I don't remember if I installed Flow with NPM or no, even after deleting whole Node.js and NPM and reinstalling, it was always 0.37.4 version, but after that fix everything seems fine.

**Comment by yury** [comment]
I think it is better to keep flow-bin as dev dependency in your project.
