### ISSUE TITLE
Nested unions issue/question

### ISSUE THREAD

**Issue by yury** [facebook/flow#3313]
Why flow can't infer that OneActionType can be used where ActionType is used in following example:

```
/* @flow */

type ActionTypes = 'ONE' | 'TWO' | 'THREE'

type ActionType = {
  type: ActionTypes
}

type OneActionType = {
  type: 'ONE';
  payload: string
}

// this is ok:
// (x:OneActionType) => (x.type:ActionTypes)
// this is not:
(x:OneActionType) => (x:ActionType)
```

[Try Flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2AKrngM5gC8YA5APIByAoq2AD5tqAdXZ9BragAkASt17ps+IqQo06zMAG9UYMErwAuFeSq189VAF9FG9pTwlT65Sx16Dxjj1YBuXWA4AIZY8EEAJsb0GABOZJQA5tbowMD6ABZkjFlgcADWhqipYAAUAB6G9o6qZnQAlMwAfKVlAHSeTmrmDHVFaRiZ2YyUcBiF5ZUOnbX4DUzNE9MueL1AA)

**Comment by jesseschalken** [comment]
`ActionType.type` is read/write. `OneActionType.type` is only `'ONE'` but if is treated as a `ActionType` it could have `'TWO'` or `'THREE'` assigned to it, violating its type.

You need to mark `ActionType.type` as covariant (read only): [Try Flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2AKrngM5gC8YA5APIByAoq2AD5tqAdXZ9BragAkASt17ps+IqQo06zMAG9UYMAGoleAFwryVWvnqoAvoo3tKeEufXKWOvUdMcerANy6YDgAhljwIQAmpvQYAE5klADmtujAwGAYABZkjLlgcADWxqjpYAAUAB7Gjs6qFnQAlMwAfBWVAHTeLmqWDI2lGdn5+ZRwGCVVNU49DfjNTG1Ts254A0A)

**Comment by yury** [comment]
@jesseschalken thank you!

Leave here [good reading](https://flowtype.org/blog/2016/10/04/Property-Variance.html) about variance in flow.
