### ISSUE TITLE
Unsound function subtyping

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3314]
Example:

```js
function foo(x: ?string): void {
  if (x) {
    x.toLowerCase();
  }
}

const foo_: () => void = foo;
foo_(1);
```

**Comment by vkurchatkin** [comment]
Presumably, function with fewer explicit arguments can never be a supertype of a function, even if it has some maybe/optional arguments.

**Comment by vkurchatkin** [comment]
The same problem with rest args:

```js
declare function foo(...x: Array<string>): void;
const foo_: () => void = foo;
foo_(1);
```

**Comment by vkurchatkin** [comment]
So, here is what happens: Flow reuses code that handles function application for function subtyping. When argument is not present, it is substituted with `void`, which if fine for function application, but  not for subtyping. For subtyping it should be `mixed`. For example:

```js
declare function foo(x: ?string): void;
foo(); // void ~> ?string: OK
(foo: () => void); // mixed -> ?string: ERROR
(foo: (string) => void); // string -> ?string: OK
```

**Comment by jesseschalken** [comment]
Duplicate of https://github.com/facebook/flow/issues/3049?
