### ISSUE TITLE
Unable to export polymorphic function with commonjs exports

### ISSUE THREAD

**Issue by davidswinegar** [facebook/flow#3315]
paste the following into a flow file: 
```
// @flow
declare function x<T>(t: T): void;

// does not error.
// export default x;

// errors, asking for type annotation.
declare module.exports: x;
```

It is possible to export this function using es6 exports, but not with commonJS exports.

See https://flowtype.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJAK4B26ALgJazGgAeAPACoB8AFGQFyiMCUXAbrArIA3IkQhQqWgAdYOMqDSQshaItpiUGbHlABbWMjWoAdNLkKAzl03igA.

**Comment by jedwards1211** [comment]
@davidswinegar looks like if you do
```js
declare module.exports: typeof x;
```
It works

**Comment by davidswinegar** [comment]
@jedwards1211 yep, I started using that syntax a while back and never closed this issue. If anyone is wondering the above solves it
