### ISSUE TITLE
AST: ClassProperty loc includes next identifier's location

### ISSUE THREAD

**Issue by danharper** [facebook/flow#3319]
e.g. given the following code:

```js
class X {
  foo: string

  bar: string;

  baz: string;
}
```

the loc for the `foo` property ends at the end of the `bar` identifier, unless it is terminated with `;`.

https://astexplorer.net/#/gist/c68b21f9f16acb784665323a2dd41dd5/1c304521ed863a6fe02d8d64bf5188f58e66bbb7

without semicolon:

![image](https://cloud.githubusercontent.com/assets/510740/22530037/cf1e4bf6-e8d1-11e6-8a5c-4be922544a00.png)

with semicolon:

![image](https://cloud.githubusercontent.com/assets/510740/22530041/d49b6352-e8d1-11e6-8f33-7b39c6a53744.png)

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
