### ISSUE TITLE
Issues typing higher order component

### ISSUE THREAD

**Issue by davidswinegar** [facebook/flow#3321]
I am trying to type a React higher order component (which seems to be a common problem in the issues). I have the following code:
```
// @flow
import React from 'react';

declare function mapProps<
  DefaultProps,
  OutputProps: {},
  InputProps: {},
  State,
  HocState,
  ChildComponent: React$Component<DefaultProps, OutputProps, State>,
  Hoc: React$Component<{}, InputProps, {}>
>(
  connectorFn: (props: InputProps) => OutputProps
): (component: Class<ChildComponent>) => Class<Hoc>;

type Props = {
  a: string;
  b: string;
};

class Component extends React.Component<any, Props, any> {
  props: Props;

  render() { return <div></div>; }
}

const Hc = mapProps(
  (props: {b: string}) => {
    return {
      ...props,
      a: props.b
    };
  }
)(Component);

// should error - no 'b' in props
const Y = <Hc />;
```

I am trying to type a map props HOC - a React HOC that takes in a function that maps a set of input props to a set of output props and uses that to wrap a component that takes the set of output props. From my example above (paste into try flow), it looks like there should be an error: I'm not passing in `b` to my `Hc` element, even though it's required in my mapProps function. Am I doing this wrong or is there some kind of bug?

**Comment by mwalkerwells** [comment]
It comes down to your incorrect use of [bounded polymorphism](https://flowtype.org/blog/2015/03/12/Bounded-Polymorphism.html). I get confused with this also...it's easy to think of them as "type aliases," but they are opaque types, that are bound to a certain "shape."

...I tried to clean up your example a bit (there's a lot going on here) to see if I can figure out your problem.

**Errors Correctly**
https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiOAnuoaAMLTEDO-ImRzdqmAHaEJOADwAVAHygAvDz6DZw8gBIxGWFJmyAbrGQATADSh5Ns5cWKWFwqT4NQkAK4TyyQ1BUYnQABSp0fllEUFAASQl0bxxw2EiALgBITIBvAF8rGNAAeWSklIj+LNy8xEUAChwsYgl+SGxUdPjE5NTI1WVSnHK+-gBKLt4BIUZRcUNpOSGRyuUVZSnBbTmDIzkElbT+Z0R3aZ55vdBCAA8caQt+AlmAOn1JRdAcovRKrpzQMQuvwmsgJABzGwAI2BoIhoDyAG5ELVToYQaAmi02h1VKAFA0TMRoN5CP9QDDbAiJl9AV07BT6QiBqB6gCXhyiSTCDYgaAuaSXlDqSxSOi8AAJbh44JhSqNZqtdpYVBjervBYyMai8WgfgAC1g3mgFgAolgqFhTdBCKhPmpZFLQMBFEA

````js
// @flow
import React from 'react'

type ClassReactComponent<T> = Class<React$Component<void, T, void>>

declare function mapProps<
  InputProps:		{},
  OutputProps:		{}
>(transform: InputProps => OutputProps): ClassReactComponent<OutputProps> => ClassReactComponent<InputProps>

class Component extends React.Component {
  props: { a: string, b: string };
}

const transform = <T>(value: { b: T }): { a: T, b: T } => ({ ...value, a: value.b })

const HC = mapProps(transform)(Component)

const shouldErrorElement = <HC />
````
````js
15: const transform = <T>(value: { b: T }): { a: T, b: T } => ({ ...value, a: value.b })
                                 ^ property `b`. Property not found in
19: const shouldErrorElement = <HC />                               ^ props of React element `HC`
````

This helped me narrow in on the minimal set of changes you need to make:

**Minimal Set of Changes**
https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IogCaGnTEOiQBXAHblksIaFTF0ABSroAzgB5EoUABFCkYgOg45sRQBpVoAPICc6SwcUAuUAG8AvibUBJIdf3yFDl26gAMo4xDiEgQASsKQhYRGIAHwAFKak4kJcONgAYkIOyei+Dp7etgoAlKAAvInmlmW+iBUF6RjihEI4DgDCPArKRGQ4ACQ91JiZXUqa2ro+hgpG9VY2vstx4YmJVbWgfcQDSkPkYxMd0wGgpWuLyy7brIg4AJ7ohKDlNU6mxA4KOCwyCEAHNWGoAEb-QHAsGIZxPbiHBT7c5TPCEAAe4SE7BRJxwADpxu10UpiEIXstyssKS86o5TEVFg5yk81AxcYQsMkqo5QAwcAIsBIlOxkAA3RJKYDiqXMUDOeFsdJCAGgSKkb5SWS+VJqQrFJxQ0AAoGg5y7BmmDmEIUin5qJ2gQmu5nGG1Ov6gd0KQkQz0I0xKirJEmTTo4CpPECmgAWsF07FA3KoWFAAFpQEJYHQIbRQMCfU1VeqAJrfJSa0DARLMIA
````js
// @flow
import React from 'react';

declare function mapProps<
  DefaultProps,
  OutputProps: {},
  InputProps: {},
  State,
  HocState,
>(
  connectorFn: (props: InputProps) => OutputProps
): (component: Class<React$Component<DefaultProps, OutputProps, State>>) => Class<React$Component<{}, InputProps, {}>>;

type Props = {
  a: string;
  b: string;
};

class Component extends React.Component<any, Props, any> {
  props: Props;

  render() { return <div></div>; }
}

const Hc = mapProps(
  (props: {b: string}) => {
    return {
      ...props,
      a: props.b
    };
  }
)(Component);

// should error - no 'b' in props
const Y = <Hc />;
````
````js
26:   (props: {b: string}) => {
              ^ property `b`. Property not found in
35: const Y = <Hc />;
              ^ props of React element `Hc`
````

**Comment by mwalkerwells** [comment]
@gcanti You have always seemed like a master with ````React$Component```` types (specifically thinking of https://github.com/facebook/flow/issues/3053).

While writing my answer, I realized I don't fully understand why this is working the way it is (`#1` vs `#2`):

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiOAnuoaAMLTEDO-ImRzdqmAHaEJOADwAVAHygAvDz6DZw8gBIxGWFJmyAbrGQATADSh5Ns5cWKWpDfx7jD0vIQAeOaQt3bRwAOn1Jb1AAb0RQUHQqdH4ALhjQYjT+HCxkCQBzGwAjLJy8-NAAXwBuREqXQ2zQHOIJfkhsGjUFRQAKE2JoAFdCNOjQEtsqgEoxjLS7CYWq1WVe8dDNgeHCG0zQbZHQopm4+PP4s4vL6-Or65YQUABiAEZQAFF8fAB5fFBetw-vgPtx5NNEBZCK5iAxQJAhhJyMhDKBUMR0AAFJL8WRnACSEnQQxw2NgyRSAEhKdFKlYzj8ScTSTiqTT6n0Wm0OlhUGlCcyyclVqBGThBTjZuoBEJGKJPEY5GKJeT+MoVMpeDKQhEvMYBSShWqGm08AAJbiqNEYo29LntTrTQEK7wQxCkRp4fgAC1gQ2gFg+WCoWA+0EIqCi3QtoGAzluNwT9wuybuCdAiCezwATKAAHI-T7fP4A-F5oHfUHgyHQvhwhFInAoiTWrE47N4+IGlmqtm0+nxZWG1nU-tnbje5ABtmUrWCHUu4xDnvJRQD0Bmn7cGeztwLgyK2Tdo3KJOcrCtB28-lE4eqkXLo1SidTiwizfcE1NC25tTotuqtmdoXtyjrOgerpfl6vr+oGwbYGGEbeL+oCyD+saKEAA

**Comment by davidswinegar** [comment]
@gcanti thank you so much - I really appreciate you taking the time to help me out with this and the other issue. That link is very useful. 

In case anyone else had a problem with the DefaultProps, the other issue I was running into when playing around with this earlier was typing the HOC as `React$Component<HocDefaultProps, InputProps, HocState>` - so that the DefaultProps was a function parameter. This led to Flow not catching errors, I think because it assumed that default props could be some less specific type. Since my HOC always has no default props, explicitly setting that type to `{}` helped to force Flow to look at the difference between props.

**Comment by mwalkerwells** [comment]
@davidswinegar Not sure if this helps, but I generally make stateless components a function of a type alias called ``RequiredProps``, which is ``$Diff<DefaultProps, Props>``. It has made the mental model much more simple for me.
