### ISSUE TITLE
"string with unknown value" error, but value is known (restricted by type and also fixed by code)

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3325]
Flow 0.38.0, Windows

Error text in a comment. I would understand if `Object.keys` does not work in general, but it does (2nd example, bottom), and the function returns a fixed object so not really a difference to specifying that object, but one works the other doesn't. In addition, the return type of the function is set to just that type.

Background: The more generic `{[string]: string}` object type works, but I tried to restrict it to the four fixed property names.

```javascript
// @flow
'use strict';

type LinkedObjectsTreeObjT = {|
    refs: Array<string>,
    objs: Array<string>,
    clobs: Array<string>,
    blobs: Array<string>
    |};

// Or just function (): Object {
const findLinks = function (obj: Object): { [$Keys<LinkedObjectsTreeObjT>]: string[] } {
    return {
        refs: [],
        objs: [],
        clobs: [],
        blobs: []
    };
};

// DOES NOT WORK:
// test.js:29
//  29: Object.keys(findLinks({})).forEach((key: $Keys<LinkedObjectsTreeObjT>) => {
//      ^^^^^^^^^^^^^^^^^^^^^^^^^^ some string with unknown value. Property not found in
//  29: Object.keys(findLinks({})).forEach((key: $Keys<LinkedObjectsTreeObjT>) => {
//                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object type
// 
// Found 1 error
Object.keys(findLinks({})).forEach((key: $Keys<LinkedObjectsTreeObjT>) => {
    // ...
});

// WORKS:
Object.keys({
    refs: [],
    objs: [],
    clobs: [],
    blobs: []
}).forEach((key: $Keys<LinkedObjectsTreeObjT>) => {
    // ...
});
```

**Comment by ddgromit** [comment]
This actually looks like a more specific bug with string unions used in indexer properties.  

```js
type SomeStrings = 'a' | 'b' | 'c';

// FAILS: objects with *string union* keys are not subtypes of objects with *string* keys
function testStringUnionInKeys(strObject: { [SomeStrings]: number }) {
  (strObject: { [string]: number })
}

// 27: (({}: { [SomeStrings]: number }): { [string]: number })
//                                          ^ string. This type is incompatible with
// 27: (({}: { [SomeStrings]: number }): { [string]: number })
//              ^ string enum
```

$Keys returns a string union, so is affected by this bug.

**Comment by asolove** [comment]
If I remember correctly, the reason these key-related types don't work with methods like `Object.keys` is that Flow currently doesn't track which properties are _own_ properties on the object and which come from a prototype. Flow accepts the type as long as the object has that property even on the prototype, whereas many key related methods operate only on own keys, so Flow is conservative and assumes it doesn't know what keys might show up.

(Also, a note that B needs to be a _supertype_ of A for `{ [B]: string }` to be a subtype of `{ [A]: string }` because its in a contravariant position.)

**Comment by meatwallace** [comment]
To confirm, is this a bug or intended functionality?

**Comment by lll000111** [comment]
UPDATE:

[Flow Try link of my original example code](https://flow.org/try/#0C4TwDgpgBAMglgOwNYQCYHkBGArCBjYAZwBUAnCCLbYqAXigG8AfAKCnanIDNCAuKAIKlSAQxAAeQsFKIA5gD4ANGw4B7HH0HCxk6XKUr2eADbrNQ0RKkyEC5RyiZTmc9qt7b8w1CYBfANwsLAD0wVDopFDYAK5SUFzRCARwqghQABQAlPxU+MCMLHipcVyIqPDIhHTxicmpGerYOTh52YxQANoAJADSECCE4hUoGC0EJOSUOMTyALr81nIds1C+BQ7kwNGkaQzeGxA8-Mv2Dmoax7OnZ1AmZpfXZ073nbPeASwfIWEAIugAogBlKAAOXQNAA6ugAEo9XjfKDACBSAB02D4ACYAJwIqDY5q4AgolADdKlBDlRBIQjpBi+TKZFFcVSkf4iPAAC3S6RJ-F6-UGwzQuXGZAoVBmmTo8gKoRuAD1FUrlSrVSqoIRVABbaCLWxQADucGAHKgiSQCFUBrSADcRMZohAUVAAAqkVSQUigKCW-LMxKoKCIXH48JjYDEgVksrDGl0hlMllsznc3lQfkDIZU4Xhibi6byKW0GV7OU3csVytVhVq2t1pVQRp5RHgCAIhEAMVUAagAEYoBBhCyWCKIySaeTKZVafTGczWeyuTz+ny+pmhaNCUQxVNqIXpesOHKUSfPplAgiobDAfDR5HSXsDkdXo9GpoTt47i4Ht5nt-XmeiYLimy4gKuApZsgOZbnmu6Sgej5HmEJ4omegRAA)

I just tested it, the last version where this error appears is 0.59. There is no error when you select Flow 0.60 and above.
