### ISSUE TITLE
Adding mixins erases static properties inherited from parent class

### ISSUE THREAD

**Issue by idris** [facebook/flow#3326]
It seems that adding mixins to a class erases any static properties that were inherited from a parent (extended) class.

Here's a test case: ([on flow-repl](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAYQMoEEwBvVMMcgF3w4EscwocOAC52HQjwB2AcwDc6NvlGcJM+QF902MsVJ0qtCuQBCYLAA8OWSRgP7GLNgCNl4qXNSbMuArrKUwAGU4AFssAFkecykqRzAQqKwMUSchGCx8SQ0tHyISfzsjajNLa1sae3iomKDQiOrJWNZSV1UPL2BgMAB1OEIAa3IAGjAKEoAHXCsMbx0SADciMHpRDgBPSbgoCqN6eRw4Rrh0gDp4aQAKehPBOABKeVROnr7BkbGLSZxp2d8FpeMqw2WC2O0oxn2h3IxywZzgl2MNyED3QzwAYvgeDByKJxoQ4JNCOswAADW4ksCSOAcARwACuNjAUjE3D4VFBhko1F+eTAi0INCBm22nPI1EhR1O5wu1CR91kQA))
```js
/* @flow */

declare class ClassA {
  static foo: string;

  a: string;
}

declare class ClassB extends ClassA {
  b: string;
}

declare class SomeMixins {
  mixed: boolean;
}

declare class ClassC extends ClassA mixins SomeMixins {
  c: string;
}

// Works, as expected
declare var A: typeof ClassA;
console.log(A.foo);

// Works, as expected
declare var B: typeof ClassB;
console.log(B.foo);

// Fails: property `foo` not found in statics of ClassC
declare var C: typeof ClassC;
console.log(C.foo);
```

Don't try to run the code, obviously it won't run.  But if you run `flow` on this code, the first two cases work and the third fails.  I don't think this is expected behavior.

**Comment by goodmind** [comment]
This was fixed
