### ISSUE TITLE
{}-Bound Polymorphic Type: No Error (Unknown Type)

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3327]
``Object.keys`` returns ``Array<string>``, so why does Test 1 have no error when I specify a return type of ``Array<boolean>``?

``flow type-at-pos`` shows that ``test1`` returns an ``unknown`` type.

Bounding it to ``Object`` correctly errors for some reason...

````js
/* @flow */

// Test 1 (NO ERORR)
function test1<T: {}>(value: T): Array<boolean> {
	return Object.keys(value)
}

// Test 2 (ERORR)
function test2<T: Object>(value: T): Array<boolean> {
	return Object.keys(value)
}
````
````js
10: 	return Object.keys(value)
                        ^ string. This type is incompatible with
9: function test2<T: Object>(value: T): Array<boolean> {
                                              ^ boolean
````

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoFMDOALmAIxgAUAcgPJgCiAStQwwJSpQCuAdgMaEBLONzCEChEgB5sALjABvAL4A+cgDcAhjE6452VnICCAJ2MaAnpIBGcODFwbuyhagCQx3IU7GR1KwCtcfgA6AGtcc3x1LR12RXRMHHEwACYKRmY2Dh5+IRExIhTpOT9A-lVNbV0cAzATM0sbOwcnF3dPb18AoMIwiKjK2NRFIA

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/2645

Flow thinks that `Object.keys` returns empty array, so it can be  a subtype of `Array<boolean>`
