### ISSUE TITLE
Bounded Polymorphic Subtype Issues

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3332]
This should be an error. `string` is not a subtype of `number`:

````js
declare function foo<A, B: A>(valueA: A, valueB: B): void

foo(5, '')
````

**Flowtype Blog**
https://flowtype.org/blog/2015/03/12/Bounded-Polymorphism.html
> Since U is a subtype of T, the method body type checks (as you may expect, U must also satisfy T’s bound, by transitivity of subtyping). Now the following code type checks:
> 
>   // store is a Store<{x: number; y: string}>
>   var store = new Store({x: 42, y: "yay"});
> 
>   var result = store.bar({x: 0, y: "hello", z: "world"});
> 
>   // This works!
>   var test: {x: number; y: string; z: string } = result;
> Also, in a polymorphic definition with multiple type parameters, any type parameter may appear in the bound of any following type parameter. This is useful for type checking examples like the following:
> 
> ````js
>function copyArray<T, S: T>(from: Array<S>, to: Array<T>) {
>   from.forEach(elem => to.push(elem));
> }

**Comment by jesseschalken** [comment]
```js
declare function foo<A, B: A>(valueA: A, valueB: B): A

let x = foo(5, '');
x.charAt(0);
x.toFixed();
```
```
6: x.charAt(0);
     ^ property `charAt`. Property not found in
6: x.charAt(0);
   ^ Number
7: x.toFixed();
     ^ property `toFixed`. Property not found in
7: x.toFixed();
   ^ String```
```

Flow has effectively inferred that `A = string|number`.

**Comment by mwalkerwells** [comment]
It's so easy to forget about inferred unions. Thank you!
