### ISSUE TITLE
Spelling error

### ISSUE THREAD

**Issue by xiayuxiaoyan** [facebook/flow#3333]
https://flowtype.org/docs/quick-reference.html#tuples
![image](https://cloud.githubusercontent.com/assets/7700024/22585580/7be832b8-ea33-11e6-9c86-707bdcb99af0.png)
heterogeneous  should be heterogenous

**Comment by jesseschalken** [comment]
A quick google suggests "heterogeneous" is the correct spelling: https://www.google.com.au/#q=heterogeneous http://www.dictionary.com/browse/heterogeneous

**Comment by xiayuxiaoyan** [comment]
Sorry,  I'm wrong
