### ISSUE TITLE
Add SVG type definitions

### ISSUE THREAD

**Issue by danvk** [facebook/flow#334]
To https://github.com/facebook/flow/blob/master/lib/dom.js

There are some definitions for Closure Compiler here, for example:
https://code.google.com/p/closureidl/downloads/list

**Comment by mjomble** [comment]
Seems like it's being worked on in #4551, can probably close this issue

**Comment by TrySound** [comment]
This probably can be closed in favor of #4551.
/cc @vkurchatkin
