### ISSUE TITLE
Consider destructured array elements as undefined

### ISSUE THREAD

**Issue by pladaria** [facebook/flow#3343]
Flow (0.38.0) finds 0 errors in the following code:
```javascript
// @flow
const [a, b] = ''.split(',');
console.log({a, b}); // prints: { a: '', b: undefined }
b.trim(); // TypeError: Cannot read property 'trim' of undefined
```
I would expect that Flow infers `b` (and maybe `a`) as `undefined`. Is this the expected behavior?

**Comment by jesseschalken** [comment]
You are generally permitted to index into an array without checking for `undefined`:

```js
const a: Array<number> = [];
a[0].toFixed();
// no Flow error
// runtime error: TypeError: Cannot read property 'toFixed' of undefined
```

It is fairly common for array/vector/list structures in statically typed languages to have a subscript operation that returns the _n_ th element without requiring you to explicitly handle the case of _n_ being out of bounds (eg by throwing an exception in that case). Flow considers Array subscript to be the same.

**Comment by pladaria** [comment]
Thank you.
