### ISSUE TITLE
React components as properties of an object are not checked

### ISSUE THREAD

**Issue by derek-duncan** [facebook/flow#3346]
I ran into an interesting bug recently.

React components that are a property of an object are not checked by flow. However, when destructured from the object, flow finally picks them up. This is the obvious work around, but the bug is still tricky to debug because it silently fails. 

Here's the sample code.

```
import React from 'react';

const localComponents: {
  StyledHeader: Class<React$Component<*, { color: string }, *>>,
} = {
  StyledHeader: class StyledHeader extends React.Component {
    render() {
      return <h1 style={{ color: this.props.color }}>Header</h1>;
    }
  },
};

// $ExpectError, but no error
<localComponents.StyledHeader />;
                                    
const { StyledHeader } = localComponents;
<StyledHeader color="#333" />;
```

[I put together an example as well.](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4AbCNFRgYV0hqRpjoBccAN7k4cAMowAnoyQATABKp5SKEPaMUdOgB5k6GABJO4Wrxi6AVABoRcas3VwGUYDQDmcAL52rAPn8bcm84AF4RMUkZOSUVNSE0LR1o2QVlFFUoOCQADxheeTpEYhgAOlNuC0jxcSIaLIAKAEoa2rqkGABXKBo4XQALAEYXGKQw4WEHCCchGAHgOjKwHDAlx2gfb38MrN0AemH-CnbvKN8QinJ9-bgjAFFcsCQMe6gcKHJdZlYOLnM+EspGk4pk1HB9scou0YbC4fD2lRaAx7MDYrtwaEIj82JUAfwKLo0el4tkNlAwgAiADEAGZ6ZSIccgA)

**Comment by asolove** [comment]
If I update this example to Flow 0.53, it now gives the appropriate type error:'

```js
import * as React from 'react';

const localComponents: {
  StyledHeader: Class<React.Component<{ color: string }, *>>,
} = {
  StyledHeader: class StyledHeader extends React.Component<*,*> {
    render() {
      return <h1 style={{ color: this.props.color }}>Header</h1>;
    }
  },
};

// Error about missing prop here
<localComponents.StyledHeader />;
                                    
const { StyledHeader } = localComponents;
<StyledHeader color="#333" />;
```
