### ISSUE TITLE
Issue with SyntheticEvent

### ISSUE THREAD

**Issue by blainekasten** [facebook/flow#335]
If I have an event bound function annotated like so:

```
bindFn(e: SyntheticEvent) {
   if (e.target.nodeName === "INPUT") {...}
}
```

flow throws an error saying nodeName is an unknown attribute on SyntheticEvent.

**Comment by jeffmo** [comment]
So it looks like `EventTarget` isn't defined with a `nodeName` property in our interface definitions:
https://github.com/facebook/flow/blob/master/lib/dom.js#L61

Though it seems like `EventTarget` is intended to be just a partial interface (not a complete class) that can apply to many different types. The best bet here might be to create a variant of `EventTarget` for each of the valid types of a concrete `EventTarget` object.

**Comment by Aweary** [comment]
Flow also warns if you access `event.target.value` in an event handler in React typed with `SyntheticEvent`, since `EventTarget` doesn't cover `value` either.

**Comment by TrySound** [comment]
AFAIK this problem is solved with `event.currentTarget`.
```js
handleClick(e: SyntheticEvent<HTMLInputElement>) {
  e.currentTarget.value
}
```

Target refinement can be achieved with `instanceof`

```js
handleClick(e: SyntheticEvent<HTMLInputElement>) {
  if (e.target instanceof HTMLInputElement) {
    e.target.value
  }
}
```

Should we close this issue?
/cc @vkurchatkin
