### ISSUE TITLE
Proposal:  $UnionMap<U, F>, the dual of $ObjMap<O, F>

### ISSUE THREAD

**Issue by sleexyz** [facebook/flow#3350]
#### Background
As far as I can understand, `$ObjMap<O: Object, F>`, given an Object type, returns a new Object type with a type function `F` applied uniformly to the values of `O`.

So `$ObjMap`, given an Object, returns a modified Object.

#### Proposal

It would be nice to also have its dual, `$UnionMap<U: Union, F>`, which given an Union, returns a Union with the type function `F` applied uniformly to the types being unioned in `U`.

So `$UnionMap` will, given a disjoint Union, return a modified disjoint Union.

#### Bonus

In addition, we can also derive the coveted `$Values<O>` from `$UnionMap<U, F>`,  `$Keys<O>`, and an upgraded `$PropertyType<O, K>` that allows type variables in addition to string literals (which doesn't yet exist):

```js
type $Values<O> = $UnionMap<$Keys<O>, <K>(key: K) => $PropertyType<O, K>>;
```

**Comment by Ashoat** [comment]
> conditional type

Exciting!! Anywhere I can read more about this?

**Comment by SamChou19815** [comment]
Right now the TS docs might be the best reference: https://www.typescriptlang.org/docs/handbook/2/conditional-types.html

We plan to implement the exact behavior as TS' conditional type, modulo some small improvements and deviations.

**Comment by Ashoat** [comment]
Super cool!! I had a need for a conditional type when drafting the [React Navigation libdefs](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/%40react-navigation/drawer_v5.x.x/flow_v0.201.x-/drawer_v5.x.x.js#L436-L441), and ended up hacking a "solution". Would be great to have first-class support for this
