### ISSUE TITLE
Flow can not decide which case to select when class property initializers are used

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#3357]
Here is [an example code](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKeMeAxhnAE5gC8qYYAPmAN5jb4BcARAMIBnAcVIVqPADRgAbgEMYAVzxcBGKgEsAdgHMwAXwbM2HXMp4ANAAqyMACxHlKVSTPlKVarboOoyMWUJgfIQhJI7UbIacBLRg-EIOYs6GcorKqho6hmRwmhkKSQAUqe4ZXgCUkYyMduoCAHQlMa5phgY+OXkYYAJhSVyJTnRgmnhIwaGiToUA5PUAtrJaYAB8YPUCCvOLVFgz5UA) that is also in-lined below for convenience:

```js
/* @flow */

type Selector =
  | { type:"CssSelector", value:string }
  | { type:"XPathSelector", value:string }

class CSSSelector {
  type = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}

const selector:Selector = new CSSSelector('.main > .summary')
```

Arguably there is flow has enough information about `CSSSelector` class to be able to select first case from the union, but instead it fails with a following error:

```
    15: const selector:Selector = new CSSSelector('.main > .summary')
                                  ^ CSSSelector. Could not decide which case to select
    15: const selector:Selector = new CSSSelector('.main > .summary')
                       ^ union type
```

Presumably because `CSSSelector`'s `type` property is inferred as `string`  instead of a literal `"CssSelector"`. I think flow should infer properties with initializers to be of assigned value type, as broadening  a property type like:

```js
class CSSSelector {
  type:string = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}
```

makes more sense than reverse & current default of narrowing it down like:

```js
class CSSSelector {
  type:"CssSelector" = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}
```

**Comment by jesseschalken** [comment]
I don't think `CSSSelector`'s `type` property is necessarily inferred as `string`, because this has the same problem, and adding `type:string` to the class also fixes it:

```js
type Selector =
  | { type:string, value:string }
  | { type:number, value:string }

class CSSSelector {
  type = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}

const selector:Selector = new CSSSelector('.main > .summary')
```

Rather I think Flow is giving `type` a special type that is inferred based on all the ways it is used, like this:

```js
class Foo {
  blah;
}
(new Foo()).blah = 'hello';
(new Foo()).blah = 1;
(new Foo()).blah.toFixed();
(new Foo()).blah.charAt(0);
```
```
6: (new Foo()).blah.toFixed();
                    ^ property `toFixed`. Property not found in
6: (new Foo()).blah.toFixed();
   ^ String
7: (new Foo()).blah.charAt(0);
                    ^ property `charAt`. Property not found in
7: (new Foo()).blah.charAt(0);
   ^ Number
```

Apparently Flow can't use such an inferred type for selecting a case in a union. 😕

**Comment by Gozala** [comment]
> I don't think CSSSelector's type property is necessarily inferred as string, because this has the same problem, and adding type:string to the class also fixes it

I have to admit that I find it surprising that your code snippet does not just work, given that in one case type is string and in other it's a number. Never the less flow is actually able to infer that `type` is a [string in that case](https://flowtype.org/try/#0C4TwDgpgBAyhA2EDGwD2AnKBeAUFKAPlAN5SiQBcAzsOgJYB2A5gDRQBuAhvAK4TW1GTKAF88hEmXD8GPALYAjCOjZde-GvWaicOJPE5UqUAMIxzCZGkzFx5aFigAiE0biIUGJ+LV8BWpnEkVAZNHk90AApfDUFmAEoScXxgAAs6KgA6GOwObj5xMTEcBggAd1NzdysMSIByTLlORigAPihMqnkm9BA6+Mz7TKRUznQAQWBIgAZ4oA):

```js
type Selector =
  | { type:string, value:string }
  | { type:number, value:string }

class CSSSelector {
  type = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}

new CSSSelector('.main > .summary').type.charAt(0)
```

Also worth noting that if you update my original example & providing a type annotation it [will work as expected](https://flowtype.org/try/#0C4TwDgpgBAyhA2EDGwD2AnKBeAUFKAPlAN5SiQBcARAMIDOdciKGVANFAG4CG8ArhAp1g6AJYA7AOZQAvnkIky4QVQAaABW7AAFk2Rp07LrwFCRE6XJxJ43BlBownCfRhLzyK+oxctD2KFoGPT8qeR5+QWExKXkkVHFovj8ACgjTaIsASnd8fB1ROgA6dOgsY0j5OSt4xOAoOl8DChCDAPEIAHcHJ1aMFIByIoBbbgkoAD4oIro+YdH0EAGsoA)

```js
type Selector =
  | { type:"CssSelector", value:string }
  | { type:"XPathSelector", value:string }

class CSSSelector {
  type:"CssSelector" = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}

const selector:Selector = new CSSSelector('.main > .summary')
```

As of your other example there is no property initializer nor type annotation so I would imagine flow treating it as `*` and given your code it would be `string | number` which is why it expects you to refine via `typeof` before treating it as either `string` or `number`.

**Comment by Gozala** [comment]
@jesseschalken Actually I think you're right, flow probably just treats non annotated properties even with initializers as `*` as it has no problem with this code:

```js
class CSSSelector {
  type = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
    this.type = 5
  }
}
``` 

Now question is if it is a good default for the properties with initializers, for use case I posted it is not, but it could be that behavior I'm suggesting has it's own drawbacks that I'm failing to consider.

**Comment by nmn** [comment]
Adding a strict type constraint on the `type` property does fix the problem. So I'm pretty sure the problem is with the type inference and nothing else.

```ts
type Selector =
  | { type:"CssSelector", value:string }
  | { type:"XPathSelector", value:string }

class CSSSelector {
  type: 'CssSelector' = "CssSelector";
  value:string
  constructor(value: string) {
    this.value = value
  }
}

const selector:Selector = new CSSSelector('.main > .summary')
```


That said, I think the type inference is the correct default. Assuming all initial values to be literals instead of their types will break all sorts of things.

For example, you may want to make the value property have a default value as well and initialize it with a string value. If Flow was to infer that as a literal type then the constructor would become a type-error.

**Comment by jesseschalken** [comment]
@nmn What I don't understand is why, if Flow can see the only assignment to `type` is `"CssSelector"`, it can't treat the type effectively as `"CssSelector"` to select the first case in the union. Especially considering this code passes, for example:

```js
type Selector =
  | { type:"CssSelector", value:string }
  | { type:"XPathSelector", value:string }

class CSSSelector {
  type = "CssSelector"
  value:string
  constructor(value:string) {
    this.value = value
  }
}

let x:"CssSelector" = (new CSSSelector('f')).type;
```

**Comment by nmn** [comment]
@jesseschalken OK.
Firstly it's pretty cool that your code works. I just played around with it and it totally does not work in Typescript.

Now, my best guess of why this:

```ts
let x:"CssSelector" = (new CSSSelector('f')).type;
```
works, but not this:

```ts
const selector:Selector = new CSSSelector('.main > .summary')
```

Is this:

At the time of instantiation the value of x is a string. A string is immutable and flow can see that the value of the `selector.type` has not been changed from its default.

However, in the case of selector, you are assigning an object. That object does happen to have the type set to 'CssSelector' however, an object is mutable (further the type property has not been made read-only) and so it's possible that the object can later be mutated and the types would change. So here the types are not actually compatible.

**Comment by jesseschalken** [comment]
> A string is immutable and flow can see that the value of the selector.type has not been changed from its default.

But it stops working if I assign a different type to `type` on a different object altogether.

```js
(new CSSSelector('f')).type = 1;
let x:"CssSelector" = (new CSSSelector('f')).type;
```
```
16: let x:"CssSelector" = (new CSSSelector('f')).type;
                          ^ number. This type is incompatible with
16: let x:"CssSelector" = (new CSSSelector('f')).type;
          ^ string literal `CssSelector`
```

> an object is mutable (further the type property has not been made read-only) and so it's possible that the object can later be mutated and the types would change

You may be on to something. This code passes:

```js
type Selector =
  | { +type:"CssSelector", value:string }
  | { type:"XPathSelector", value:string }

class CSSSelector {
  +type = "CssSelector";
  value:string
  constructor(value: string) {
    this.value = value
  }
}

const selector:Selector = new CSSSelector('.main > .summary')
```

**Comment by SamChou19815** [comment]
We now banned the subtyping of class against object types.
