### ISSUE TITLE
Misguiding error - object literal incompatible with object type

### ISSUE THREAD

**Issue by R0bson** [facebook/flow#3364]
Flow version: 0.38

Received error:
`Flow: object literal. This type is incompatible with object type `

Expected error
`Flow: undefined. This type is incompatible with number `

How to reproduce:

```
type PhotoDetailsType = {
  path: string,
  width: number,
  height: number,
  size: number, // here should be ?number
}

type Photo = {
  mq: PhotoDetailsType,
}

const photo: Photo = {
  mq: {
    path: '/static/images/profilePhotos/6596/696840_mq.jpg',
    width: 920,
    height: 1636,
    size: undefined, // this causes a problem
  }
}
```

**Comment by jesseschalken** [comment]
This gave a better error in 0.37.4 ([Try Flow](https://flowtype.org/try/#0FAFwngDgpgBACgCwPYiQESiAhgSwDYDOAKpLALwwDewMMEWICAXDASAE44B2A5gDQ0YAdxwATRiy4BXALYAjKOwG0EUHDwQhJshUsEEcALyjb5ivjAD0lmKvawCyKXlEwFMAPzSz7YAF9gUFJ4ZFQYCmpaGQBHFkQUdExcQhJoAQDgAGMkLjY6UKQ4gvCqQRiWSNo6BmYYAHJLNgYcTMscGSweKAJLCHYkADN8KHjUHoA2AFYATnHLcdmADgAWAAYAfRiAOgArCB465SqRcVrpgCZVo5U1DS0YAEZxgGZx69YjExgpLlEoIa4UFEFmsMEYOAIMEyWCkBG6MCwdH6cjwUBkggCfiAA) - toggle the version in the top right):

```
18:     size: undefined, // this causes a problem
              ^ undefined. This type is incompatible with
6:   size: number, // here should be ?number
           ^ number
```

**Comment by R0bson** [comment]
One more example (minimalistic):
Received error (v0.38.0):
Flow: object literal. This type is incompatible with object type

Expected error (v0.37.4):
Flow: undefined. This type is incompatible with the expected return type of string

[Try Flow](https://flowtype.org/try/#0FAFwngDgpgBAgjAvDA3sGMCGAuGBnEAJwEsA7AcwBpgBfYUSWAZSVXRgGNcB+Aki6nWAAzAK6kOIYgHtSMMaQAUeXEwCUuBGgyEoIUYTnaMJnPgB0HaiZh06QA)

**Comment by mhaddon** [comment]
I can confirm this bug, it is annoying because it sends you down the wrong rabbit hole

**Comment by madorb** [comment]
Seeing the same issue

**Comment by sabbyt** [comment]
And seeing the same in 0.47.0

**Comment by rsolomon** [comment]
Still an issue with 0.50.0 ;)

**Comment by ohjames** [comment]
Also seems misleading when you try parameter destructuring.

`function blah({ thing = null }: { thing: Thing | null })`

Tells me `null` is `incompatible with object type` and also that `object type` is incompatible with `null`. Maybe this is another bug.

**Comment by samwgoldman** [comment]
I'm not sure what the "still an issue" comments are referring to, but the original example is resolved.

Note that the issue was just that Try Flow didn't display the entire error message. It now matches the Flow CLI, which outputs:

```
Error: test.js:14
                          v
 14: const photo: Photo = {
 15:   mq: {
 16:     path: '/static/images/profilePhotos/6596/696840_mq.jpg',
...:
 21: }
     ^ object literal. This type is incompatible with
 14: const photo: Photo = {
                  ^^^^^ object type
  Property `mq` is incompatible:
               v
     15:   mq: {
     16:     path: '/static/images/profilePhotos/6596/696840_mq.jpg',
     17:     width: 920,
    ...:
     20:   }
           ^ object literal. This type is incompatible with
     11:   mq: PhotoDetailsType,
               ^^^^^^^^^^^^^^^^ object type
      Property `size` is incompatible:
         19:     size: undefined, // this causes a problem
                       ^^^^^^^^^ undefined. This type is incompatible with
          7:   size: number, // here should be ?number
                     ^^^^^^ number


Found 1 error
```

**Comment by madorb** [comment]
@samwgoldman I was getting this error from the CLI not from Try Flow.

**Comment by samwgoldman** [comment]
@madorb OK, sorry about that. In any event, both output the same information now, which is enough information to be useful, I think.
