### ISSUE TITLE
$Pick utility type

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/flow#3367]
Hi there,

I've just came across with the need of defining an object type using a subset of another, or in other words, use some props definition of a certain object type and intersect this result (a reduced object type) with another set of props definitions to define a new type.

I used to do this a lot with PropTypes using pick utility from lodash, but we've recently moved to flow and I really miss this functionality, so I was wondering if you have ever thought of the possibility of adding a `$Pick` utility type to be able to do something like the following:

```javascript
// @flow

type O1 = {
  o1k1: string,
  o1k2: number,
  o1k3: boolean,
};

// o1k1 and o1k2 mandatory
type O2 = $Pick<O1, o1k1 & o1k2> & {
  o2k1: () => void,
  o2k2: Date,
};

// o1k1 and o1k2 optional
type O2 = $Pick<O1, ?o1k1 & ?o1k2> & {
  o2k1: () => void,
  o2k2: Date,
};
```

Right now I partially dealing with this using `$Shape` like the following, but this doesn't restrict additional props I don't want to, neither it let me mark any of them as required

```javascript
// @flow

type O1 = {
  o1k1: string,
  o1k2: number,
  o1k3: boolean,
};

type O2 = $Shape<O1> & {
  o2k1: () => void,
  o2k2: Date,
};
```

**Comment by asolove** [comment]
@mgtitimoli You can do this, albeit with a tiny bit more typing, using the `$PropertyType` utility:

```js
type O1 = {
  o1k1: string,
  o1k2: number,
  o1k3: boolean,
};

type O2 = {
  o2k1: () => void,
  o1k1: $PropertyType<O1, 'o1k1'>,
  o1k2: $PropertyType<O1, 'o1k2'>
};

type O3 = { 
  o2k1: () => void,
  o1k1?: $PropertyType<O1, 'o1k1'>,
  o1k2?: $PropertyType<O1, 'o1k2'>
}
```

**Comment by mgtitimoli** [comment]
Hi @asolove,

I'm currently doing the way you described. What I'm proposing is to simplify that construct as follows:

```javascript
type O1 = {
  o1k1: string,
  o1k2: number,
  o1k3: boolean,
};

type O2 = $Pick<O1, ["o1k1", "o1k2"]> & {
  o2k1: () => void,
};
```

(I hope using an array syntax would have simplified the idea)

The alternative I originally wrote would allow specifying optional entries (by prepending `?` to them), but I've just realized that construct can be done as follows:

```javascript
type O1 = {
  o1k1: string,
  o1k2: number,
  o1k3: boolean,
};

type O2 = $Pick<O1, ["o1k1"]> & $Shape<$Pick<O1, ["o1k2", "o1k3"]>> & {
  o2k1: () => void,
};
```

I would also like to mention that a complementary utility type would be super useful: `$Omit`

(It's worth noting that this proposal is heavily inspired by lodash [pick](https://lodash.com/docs/4.17.4#pick) and [omit](https://lodash.com/docs/4.17.4#omit))

**Comment by Andarist** [comment]
This would be super cool, especially if we could pass to `$Pick`/`$Omit` `$Keys`'s output.

Something like:
```js
const omit = <T: Object, K: $Keys<T>>(keys: K[], obj: T): $Omit<T, K> =>
  Object.keys(obj)
    .filter(key => keys.indexOf(key) === -1)
    .reduce((result, key) => {
      result[key] = obj[key]
      return result
  }, {})
```

**Comment by benweissmann** [comment]
I'd also really like to be able to do this -- I'm looking for the equivalent of typescript's `Pick<T, K>` (https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-1.html), which would let us correctly type things like `_.pick` (compare [our types](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.55.x-/lodash_v4.x.x.js#L1055) to [TypeScript's types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/lodash/index.d.ts#L14428)).

**Comment by bradennapier** [comment]
This goes along with what I just posted with #5767 I think the real goal here is something which is capable of mapping tuples to objects in general?

**Comment by TSMMark** [comment]
Looking for an `$Omit` style feature. I'm thinking it should be useful when wrapping a component with some default props. Maybe something like this exists and I can't find it? See example:

```js
import InnerComponent, { type Props } from 'inner-component'

type PropsExcludingDefaults = ???

export const DefaultInnerComponent: React$StatelessFunctionalComponent<PropsExcludingDefaults> = (props) => (
  <InnerComponent
    {...defaults()}
    {...props}
  />
)
```

**Comment by TrySound** [comment]
@TSMMark There is $Rest.

**Comment by mgtitimoli** [comment]
@TSMMark you might find #5006 useful

**Comment by TSMMark** [comment]
Thanks! $Rest worked great for pulling out the types. Now I need to figure out how to fix flow when merging them back together.

```
  // $FlowFixMe object literal. Inexact type is incompatible with exact type
  <InnerComponent
    {...defaults()}
    {...props}
  />
```

**Comment by apsavin** [comment]
@TSMMark looks like another issue - see #5551

**Comment by mgtitimoli** [comment]
I believe a potential solution to *$Omit* could be near by doing the following...

The idea I have is to create a type that would receive the input object and a tuple and then use `$TupleMap` to construct another object with keys provided by the tuple and values all `*`. If we were somehow able to do this transformation then it would be as simple as applying `$Diff` to the input object with the constructed one to object the difference...

**Comment by mgtitimoli** [comment]
I finally came up with a solution :tada::

```
type Pick<Origin: Object, Keys: Object> = $ObjMapi<
  Keys,
  <Key>(k: Key) => $ElementType<Origin, Key>
>;
```

Exactness can be controlled by passing an exact object in `Keys`

[See it live](https://flow.org/try/#0C4TwDgpgBACglgYwNYB4DyAnOBzOA7ALijQCMArCBYAGigGkIQBnI0iqgPigF4oASNgFkAhmDgoAUFHqMm1KVBQMQHABRIiygJQ8ufAKIAbCAFsIeYABVwEdFlx5ayjhI4BuCRNCQolgAw8sIioAN5IfkQkAPZRxsJ4AL60YRFQ8SAJ7grSEghReEzAUAip-oEpRMAYAK4QCW5QAPSNUHhRUBAYGFEYnnkFRQgAjERlvBVQQ371TS2d3RhAA)

**Comment by mgtitimoli** [comment]
And if you prefer to pass an array/tuple instead of an object in `Keys`, you can use this other alternative:

```
const toObject = keys => keys.reduce((object, key) => {
  object[key] = undefined;

  return object;
}, {});

type Pick<Origin: Object, Keys: $ReadOnlyArray<$Keys<Origin>>> = $ObjMapi<
  $Call<typeof toObject, Keys>,
  <Key>(k: Key) => $ElementType<Origin, Key>
>;
```

**Comment by dotansimha** [comment]
Thanks @mgtitimoli , this actually makes sense and seems to work. 
I had only a small issue with it - I can specify any field that I want... `const c1: T0 = {k0: true, a: 2};` should actually give an error, because `a` is not a known field.

**Comment by alexandersorokin** [comment]
Array/tuple variant does not work if you export and import `Pick` type since Flow v0.86.

**Comment by carmanchris31** [comment]
@alexandersorokin Same in v0.92.1. Types report `any(implicit)` although validation of the tuple still works as expected (they have to be valid keys in Origin).

**Comment by AndrzejSala** [comment]
Fixed mgtitimoli version for keys provided in array
```
 type Pick<Origin: Object, Keys: $ReadOnlyArray<$Keys<Origin>>> = $ObjMapi<
    Origin,
    <Key>(k: Key) => $ElementType<Origin, Key>
  >;
```
Import should work fine and now Pick is highlighting undefined keys in type declaration as well when trying to call not existing property in your code.

[Check on flow try](https://flow.org/try/#0AQFwngDgpsAKCWBjA1gHgPICd4HN4DsAuYdAIwCspEQAaYAaSjAGdiASAJSgEMATdfABswAQUyZuYVG0YsM2PPgB8K4AF5gbMuQCy3CPFQAoYKZIKCNE2dSylACmTFZASnVLNAUUFQAtlHwQABVIKHlcSwYmJWslAG4ja0QAe3xmEFAodPVgAG9rU2QmAEZifLMzfxAAC2TeUuB7bmJ07HwcNzUPbisK0yra3gAmYntOjxBMAFcoAuAAX16zIrARvLn+qBq6gGZR5uB8Kd9SKEw6UmIjk7Px4G5gAGpgUjn563frcGgosGKQn4acqVLaDBqtAg4dzACHtJabbbDUZ3UjJZI+bj4D4JJKpbKTbgoHIgLIgAB0K2KONMADMpvhqPBUpl0sUhjt7JNiAgULYSgCoHQANoAIgGdWKIroYtBdSGUuAMsRADYRQBdJRuYGmSZk8X1ewiknpEUuBIVXX6ob2NlmuaW2W8ACsY3NC0SOtJbI5BJQZqAA)

**Comment by alexandersorokin** [comment]
@AndrzejSala, your version includes all fields of type of original object and does not remove anything.

`Pick<Obj, Keys>` utility type should remove from `Obj` every field that missing in `Keys`.

See [tryflow](https://flow.org/try/#0AQFwngDgpsAKCWBjA1gHgPICd4HN4DsAuYdAIwCspEQAaYAaSjAGdiASAJSgEMATdfABswAQUyZuYVG0YsM2PPgB8K4AF5gbMuQCy3CPFQAoYKZIKCNE2dSylACmTFZASnVLNAUUFQAtlHwQABVIKHlcSwYmJWslAG4ja0QAe3xmEFAodPVgAG9rU2QmAEZifLMzfxAAC2TeUuB7bmJ07HwcNzUPbisK0yra3gAmYntOjxBMAFcoAuAAX16zIrARvLn+qBq6gGZR5uB8Kd9SKEw6UmIjk7Px4G5gAGpgUjn563frcGgosGKQn4acqVLaDBqtAg4dzACHtJabbbDUZ3UjJZI+bj4D4JJKpbKTbgoHIgLIgAB0K2KONMADMpvhqPBUpl0sUhjt7JNiAgULYSgCoHQANoAIgGdWKIoAuko3MDTJMyeL6vYRST0iKXAkKorlUMxtqFokFaS2RyCSgtUA). There should be error at line 25.

**Comment by noppa** [comment]
I'm using 
```javascript

export type Pick<FromType, Properties> =
  $Exact<$ObjMapi<Properties, <K, V>(k: K, v: V) => $ElementType<FromType, K>>>;


export function pick<
  FromType: Object,
  Properties: Object
>(
  from: FromType,
  props: Properties,
): Pick<FromType, Properties> {
  const keys = Object.keys(props)
  const result: any = {}
  if (typeof from !== 'object' || from === null) return result

  for (let i = 0, n = keys.length; i < n; i++) {
    const key = keys[i]
    result[key] = from[key]
  }
  return result
}

```

Usage as function:
```javascript
const original = {foo: 'Hello', bar: 'World', baz: 'You'}
const picked = pick(original, {foo: 0, baz: 0})
```
The type of the values in the second argument don't matter, I'm using `0` just because it's easy to type and isn't too noisy, but you coud use something like `null` too.

Usage as as a type
```javascript
type Picked = Pick<Original, {foo: any, baz: any}>
```

This is obviously not as nice as your usual `pick(.., ['foo', 'baz'])`, the `{foo: 0, baz: 0}` does look weird, but at least it seems to currently work really well with Flow. Flow correctly infers the type to be `{|foo: string, baz string|}`.  And @alexandersorokin [your example gives an error](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgAKAlgMYDWAPAGLawC2AKsSgFygDyARgCsUVXABpyzEngooAzjwHDRAPlABeRKFAASAKJoAhqLo6lAWUMYKdMlJQz5EugGkJANRUAKGjzegANx53AEoNNX1oFBYUADtcDhJGZnZOCRcVTIBuZEgAV1jRClhY0GtaOi1QJlZE7j4hEXEqu1hpXFkFBuVcRG8qyBSeGtSSMSqMKS7W9s7xkJ5KCpG6iRmHDvk1AG8qqhK5fBoUQjkNbqaAOmPTr0m2uRC9g-xseTzoXB5DWMJz7YAvlUKJBQF4iCRYKDBqxQABCdTqUAAclgjVEyNAAB8saAYSwNIjQLEPtAwm9cHlsKU3nIPr0BjgwVF8BRzgAGCSlJE3OSXKKxADmuAAFllQGy6MTxRQANSysK7bTafaxQ6gG7nXkAbQoAF0qtpafTtTc9ed8aaTgbtECjShKdTQMbPoggc81fhcPJ8EilcqbgBGHj+5WgGKi2AAE2DYMMPEO2AoQrC6jUhnGYe0EZF0YATDwvKm1LhsHkUIbQADMwGTgXQKHlTnowBmQvx4l5Fj8BwSfg8EndhzF0CGUCy0D8St2qvIbQQ0guE6Bur-SvNmMJ0vJwXhUCJnc17MO3NR+tFvf8WCwKI-KoAnIe9Wl4w0c7ew7XZeP7T5QodEoCB9QM8xbcFsEWah6CXQgVzSBsN1jH5CABFRFUrUtLkQrwACIP1wHCQhyMNMI3PMi2I2cqnwkCwJfWgiMrRBVXVHAKEFZNDGgf5IGvHhkQACRQaA4GRPtDAglEAHUcGgKMxMnQwAC9+IATVgPJkSBFj8HKY4oxDLFeNgLckyFcTJIPIUsQBc49K8NiONiLiJG2YyeE5RTJPZAEQiAA) too with this type def like it should.

**Comment by mwood23** [comment]
@noppa Thanks for sharing your code, appears to work well for me! I tweaked it a little big to make sure the the values of the pick object are always `0`. I know it doesn't matter, but helps to enforce consistency in usage.


```js
export type Pick<FromType, Properties: { [string]: 0 }> = $Exact<
  $ObjMapi<Properties, <K, V>(k: K, v: V) => $ElementType<FromType, K>>
>;

export function pick<FromType, Properties: { [string]: 0 }>(
  from: FromType,
  props: Properties
): Pick<FromType, Properties> {
  const result: any = {};
  if (typeof from !== 'object' || from === null) return result;
  const keys = Object.keys(props);

  for (let i = 0, n = keys.length; i < n; i++) {
    const key = keys[i];
    result[key] = from[key];
  }
  return result;
}
```

**Comment by somewhatabstract** [comment]
I use:

```
type Pick<T, P: $Shape<T>> = $Diff<T, $Diff<T, P>>;
```

It seems to do the trick and has better checking than say:

```
export type Pick<FromType, Properties> =
  $Exact<$ObjMapi<Properties, <K, V>(k: K, v: V) => $ElementType<FromType, K>>>;
```

as it asserts that the picked properties exist on the type. It basically works like an inverted `$Diff`.

**Comment by somewhatabstract** [comment]
Update based on my previous post. I thought I'd try going a step further (see below). Sadly, in the 0.190.0 flow, it doens't work. 

In theory it ought to since if `K` is say `"a" | "b"`, it should only add those fields, but alas, it doesn't and it just gives a type that is equivalent to `T`. So near, yet so far. The approach in my previous comment remains effective though and some might say is more "Flow-like" since it matches the `$Diff` pattern of passing an object type.

```
type Pick<T, K: $Keys<T>> = $Exact<{
    ...$Diff<T, $Diff<T, {[K]: any}>>
}>;
```

**Comment by noppa** [comment]
@somewhatabstract That's clean. Altho the $ObjMapi version does also give the exact same errors in your example? [Try it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoApgDwA5wE4AuYBAntumAAoCWAxgNYA8AYnnALYAqZ6ANFW3KFq6AM4A+MAF5UYMABIAopgCGtAo3kB5AEYArALIrs1RpUHphY-owDS-AGriAFPQBcYe2ABuHhwEppSSUYdHZ0ADsCbnIWNi4efltxFIBuVFRScjADEhiKKTAAbwAfWTkwFQ9RAjxqCIBzXnK5HQ8IgFd2HUtmirBaDx04OFCVCOaSgF90jOA0ebAASQATSIJqUlR51Fo4CJqwEg8aBkZc-P4LnklCopbKjwAiAjECJ76KtrAAFk+5QbEPAdPioGZzBbAMAAOTgYAAwts0FkKLD4dIqHQmNdyPwilVKhESPxvuMSFNxLNFpQVKJRLt9odMABGDxojH3foEl5vD4Pb4-MEQsCKPBsPCiMA9WgqDqiCi0MDUSVy9ArBkHIiYABMbLg6LuD25rxqfP63wArP8Bh5aiDmlNhaLxZLpbL5VKlZKVFKRmMIhqmQBmPUG4pG54m97W7520GOoA)

**Comment by somewhatabstract** [comment]
@noppa it does but it's hard for folks to grok.  Here's an even simpler version, courtesy of a colleague.

```
type Pick<T, K> = {|
    [K]: T[K];
|};
```

**Comment by noppa** [comment]
@somewhatabstract That doesn't work the same way as `[K in keyof T]: T[K];` would work in TS. We still have to use $ObjMap & $ObjMapi for mapping object entries.

With that definition, the resulting type from `Pick<MyType, 'a' | 'b'>` will be `{['a' | 'b']: string | number}`, not `{a: string, b: number}` like we'd want. So it'll erroneously allow
```javascript
const y: Pick<MyType, 'a' | 'b'> = {
    a: 1,
    b: 'foo',
};
```

**Comment by somewhatabstract** [comment]
@noppa Ah yes, good call. :)

**Comment by dannyharding10** [comment]
@somewhatabstract  @noppa thanks for your help with this! This Pick type is very helpful. Would there be a way to make a `Pick` type that *allows* keys that are not on the original, and just knows that the type at that key will be `void`? Here's an example of what I mean

```
type A = { a: number, shared: string, extra: mixed }
type B = { b: string, shared: string, otherExtra: boolean }
type Picked = Pick<A, { a: 1, b: 1, shared: 1 }> | Pick<B, {a: 1, b: 1, shared: 1}>
// `Picked` should be { a: number | void, b: string | void, shared: string }
////// OOOR (😱 ) even better if `Picked` could be { a: number, shared: string } | { b: string, shared: string }
```

Link to [Flow try](https://flow.org/try/#0PTAEAUEsGMGtQBYFMA2AHJAnUAXAnhgFD4agDiSOA0kngGKYD2AtgDwDymkA5pAHYAuUOwBGAKyTQcAPlABeUKxp5pAClhDlASnmzOPfgG1lAXWIEkEGLA5deg4eMk4ANKGUBnIaIlTZCgBIfAFkAQzRIVkIASE8XGIpqWgYWWwM+aUJM81IAFSRQ6GRsBQBvAB9QPlDmJCEPHC4+bjduTFCAEzrQBqaW0H4AYRRQjy9QEUZGFAK+UHKAXxzLAGUcAFcuvhx5UAqqmu7e-n62zqPGk7dQ7m6+deYRLHmlwi7oEcxLADN1vilIIw5rccABVDxYDysXJCUoLNRoJi+HCAhy5LRCACCmHaeFYUDg0IKRSwblyskqBJsa02SG2ZOk2WgQIaoHWEMwHl2IPBkNUpWqtSEAEZrrcRQstIR2ZDDAAGEwAOhulhAoEx0GgSDGJ1AoVAiMYGEw+FwCFCO0gXL4jB2HnNXw6oGgoRlXJwyFAWCY2FCkwAbkhCEA)


The use case is trying to query multiple data types while projecting fields on both of them. We use the same projection for both data types, but type A and type B only have some intersection in their properties. You can see that in the flow ttry

**Comment by noppa** [comment]
Yes, tell Flow that the object to get keys from also has all the properties from `Keys` as `void´ values.  
```javascript
// Pick helper type
type GetKeyFrom<Origin: Object> = <Key>(k: Key) => Origin[Key]
type Pick<Origin: Object, Keys: Object> = $ObjMapi<
	Keys,
	GetKeyFrom<{...Origin, [key: $Keys<Keys>]: void}>
>
```
[Try flow](https://flow.org/try/#0PTAEAUEsGMGtQBYFMA2AHJAnUAXAnhgFD4agDiSOA0kngGKYD2AtgDwDymkA5pAHYAuUOwBGAKyTQcAPlABeUKxp5pAClhDlASnmzOPfgG1lAXWIEkEGLA5deg4eMk4ANKGUBnIaIlTZCgBIfAFkAQzRIVkIASE8XGIpqWgYWVgBvADos-Xs3Q1haIQDPJVoPaRMhADdGSAATAF9pQmbzUgAVJFDoZGwFNIAfUD5Q5iQhDxwuPm43bkxQuvHQSenZ0H4AYRRQjy9QEUZGFC6+UAGGtssAZRwAVyW+HHlQQeHR5dX+dfnFz6nvm5Qtxlnw7swRFhzpdCEtoDtMJYAGZ3PhSSCMM4gnAAVQ8WA8rHaQjSTVUaCYvhwGIc7S0QgAgpgFnhWFA4ESuj0sG52rIhuybLcHkgnrzpK1oJjJqA7vjMB4Xti8QTVGkRmMhABGIEg7UNLSEKV8GXA5Y1ernYbgyF9WXyjyGAAMJgyZtAIFADOg0CQe2+oFCoApjAwmHwuAQoWekEVfEYzw8UcRdVA0FCcr9kcsWCY2FChyqSCN0ueGv+axemYVztd5cIQA).

**Comment by FezVrasta** [comment]
Thanks to noppa on the Discord Flow channel I managed to prepare this:

```ts
// @flow

declare type toEntries<O> = <K>(K) => [K, O[K]];
declare type toObject<K: $ReadOnlyArray<string>, O> = $Call<
typeof Object.fromEntries,
$TupleMap<K, toEntries<O>>
>;
declare type $Pick<O, K: $ReadOnlyArray<string>> = toObject<K, O>;
```

Compared to other examples posted on this topic, it outputs an object type where each property uses the correct type, not an union of all the original object properties types.
y work with `Pick<Object, KeysObjet>` and `Pick<Object, toObject<Keys>>`.

**Comment by SamChou19815** [comment]
It's now a builtin in 0.210
