### ISSUE TITLE
Status of iterators / ES6 for-of

### ISSUE THREAD

**Issue by tgriesser** [facebook/flow#337]
Just wanted to check and see if `for-of` was on the radar, it was mentioned [here in #62](https://github.com/facebook/flow/issues/62#issuecomment-63720334) that it'd might be fixed shortly, but looking at the latest change logs/tickets it hasn't been mentioned at all.

**Comment by jeffmo** [comment]
Hi @tgriesser,

It's on our radar, but not quite on the top of the stack of the moment. I think we're going to be sitting down next week to work out our road map for the next several months, so I will make sure `for-of` comes up for discussion there. I'll try to follow up here after that discussion.

On the other hand, we're always open to taking pull requests for things like this! :)

**Comment by garthk** [comment]
@jeffmo, might it be worth adding an `ES6` label to collect the ~30 live issues related to ES6 support?

**Comment by samwgoldman** [comment]
Flow has supported Iterators/for-of since 0.12. @garthk, I'm going to clean up the ES6-related issues shortly.
