### ISSUE TITLE
$PropertyType doesn't work with literals

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3374]
```js
type X = $PropertyType<{ x: 1 }, 'x'>;
const x: X = 3;
```

**Comment by vkurchatkin** [comment]
The problem is that `PropertyType` uses `GetPropT` and at some point `SingletonNumT` is replaced with `NumT`, which fine for lower bound, but causes problems when it becomes the upper bound.

**Comment by vkurchatkin** [comment]
It seems that using `SetPropT` instead works for both upper bound and lower bound, but it seems logical that it should be used only for upper bound and `GetPropT` should be used for lower bound. @avikchaudhuri what do you think?

**Comment by Bannerets** [comment]
Fixed in v0.60.0.
