### ISSUE TITLE
Why does Flow require annotations after the method has been declared?

### ISSUE THREAD

**Issue by victorias** [facebook/flow#3377]
In this example, we bind the method `boundMethod` in the constructor. The type signature for `boundMethod` is declared at the top of the class, but flow still wants a type annotation on boundMethod itself. Am I doing this wrong?

```jsx
/* @flow */

import React, { PureComponent } from 'react';

class Test extends PureComponent {
  boundMethod: (data: string) => void
  constructor() {
    super();
    this.boundMethod = this.boundMethod.bind(this);
  }

  boundMethod(data) { /// flow error: missing annotation for data
    return data + this.data;
  }

  render() {
    return (
      <div>

      </div>
    );
  }
}

export default Test;
```

**Comment by jesseschalken** [comment]
You should try not to confuse properties and methods IMO. Methods exist on the prototype chain and are immutable and covariant for the purpose of typing. Properties exist on the object instance itself and are mutable and invariant for the purpose of typing.

If you're trying to define a method that can be directly used as a callback without losing `this`, I would write:

```js
  +boundMethod = (data: string): string => {
    return data + this.data;
  }
```

**Comment by asolove** [comment]
I think the current answer resolves the original question so I'm going to close this. Let me know if more is needed and I can reopen.
