### ISSUE TITLE
Incorrectly producing "Property cannot be accessed on possibly null value" error

### ISSUE THREAD

**Issue by ml9951** [facebook/flow#3378]
The following program:

```JS
type obj = {
  a : number,
  b : number
}
type ty = {
  c : ?obj
}

function test(x : ty){
  if(x.c == null){
    throw new Error('Error!')
  }
  var temp = x.c.a;
  console.log('test')
  return x.c.b;
}
```

Yields the following errors from Flow (0.39.0):

```
index.js:17
 17:   return x.c.b;
                  ^ property `b`. Property cannot be accessed on possibly null value
 17:   return x.c.b;
              ^^^ null

index.js:17
 17:   return x.c.b;
                  ^ property `b`. Property cannot be accessed on possibly undefined value
 17:   return x.c.b;
              ^^^ undefined
```

It's not possible for `x.c` to be null in the stated line given that the `then` branch of the `if` statement would be taken and the exception would be thrown.  Even more odd, if I remove the `console.log`, the error goes away.  

You should be able to reproduce this issue with the following repository: https://github.com/ml9951/Flow-Reproduce-Issue.git

```
npm install
./node_modules/.bin/flow
```

**Comment by davidswinegar** [comment]
@ml9951 As you noted, the issue is the `console.log` call. That's because Flow does pessimistic refinements, and any function call could modify x.c to be null (hey, you could even redefine `console.log` to do so). See https://flowtype.org/docs/dynamic-type-tests.html

The way to fix it is to remove the console statement, or assign `x.c` to a const. Ex:
```
type obj = {
  a : number,
  b : number
}
type ty = {
  c : ?obj
}

function test(x : ty){
  if(x.c == null){
    throw new Error('Error!')
  }
  const c = x.c;
  console.log('test')
  return c.b;
}
```

**Comment by ml9951** [comment]
@davidswinegar, Ahh that makes sense.  Thanks for the explanation.
