### ISSUE TITLE
Flow reports "Required module not found" when requiring a .scss file via Webpack

### ISSUE THREAD

**Issue by gcazaciuc** [facebook/flow#338]
Using Webpack for build management and an example file like:

require('../css/seed-component.scss');

var React = require('react');

var SeedComponent = React.createClass({
    getInitialState: function() {
        return { 'data' : 'Seed Component' };
    },
    render: function(): ?ReactElement {
        return (
            <div className="seed-component">
                <h5>Header for Seed component</h5>
                <span className="seed-data">{this.state.data}</span>
                <h5>Component props</h5>
                <span className="seed-name">{this.props.name}</span>
            </div>
        );
    }
});

When running Flow over it it complains about the line "require('../css/seed-component.scss');" throwing an error  "Required module not found" . I believe Flow should check that it's dealing with a JS file before throwing this error since in webpack it is common to require css files and images. 
Currently this is a showstopper for me on using Flow and Webpack on a large project. Any suggested work-arounds ?

Thanks!

**Comment by tcoopman** [comment]
I believe this is a duplicate of #51?

**Comment by gcazaciuc** [comment]
Indeed, thanks. But still, are there any work-arounds for the issue ?

**Comment by johnryan** [comment]
@gcazaciuc Did you ever find a solution to this?

I'm using ```import styles from './Login.scss';```

and getting an error. However, for another (regular css file) it works fine: 
```import styles from './regular_style.css';```

**Comment by gcazaciuc** [comment]
you just need to make sure that the module.name_mapper setting in flowconfig contains mappings for scss file extension and is mapping it to a dummy module.

**Comment by marianna-exelate** [comment]
Hi, 
Can you please be more specific what dummy module configuration is

**Comment by Malax** [comment]
@marianna-exelate You can find the documentation about that here: https://flowtype.org/docs/advanced-configuration.html

It's basically telling flow to treat such imports (like SCSS files) as another import which flow can actually understand. "Dummy module" just means that that module does not actually do anything besides being there to please flow.

**Comment by rofrol** [comment]
in `.flowconfig`
```
[options]
module.name_mapper.extension='scss' -> 'empty/object'
```

**Comment by patrykkarny** [comment]
@rofrol your solution kills the flow type checking in all *.js, *.jsx files, it should be:

```
[options]
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
module.file_ext=.css
module.file_ext=.scss
module.name_mapper.extension='css' -> 'empty/object'
module.name_mapper.extension='scss' -> 'empty/object'
```
Link for docs
[https://flow.org/en/docs/config/options/#toc-module-file-ext-string](url)

**Comment by jantoebes** [comment]
@patrykkarny @rofrol 

patrykkarny is totally right, it took a while before I discovered that the solution ignores all js type checks

**Comment by tomalexhughes** [comment]
For those looking for documentation, a lot of the above links are either broken or the pages have been updated. [This page](https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string) currently has information on the module.name_mapper option.

**Comment by xuqinggang** [comment]
added all the file types I wanted flow to recognize: in .flowconfig file

```
[options]
module.file_ext=.js
module.file_ext=.jsx
module.file_ext=.json
module.file_ext=.css
module.file_ext=.less
module.file_ext=.scss
```

**Comment by junibrosas** [comment]
Try adding `declare var require: any;` on the top of your file.

**Comment by locky-yotun** [comment]
@patrykkarny thanks, it works — that setting stops flow from showing errors on import of scss files — but now is displays tons of error directly in scss-files, like this:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/desktop/routes/register/Register.scss:1:1

Unexpected token .

     1│ .root {
     2│   padding-left: 20px;
     3│   padding-right: 20px;
     4│ }

```
I have no idea how to fix that – may be you have any thoughts?

**Comment by NachosSs** [comment]
> @patrykkarny thanks, it works — that setting stops flow from showing errors on import of scss files — but now is displays tons of error directly in scss-files, like this:
> 
> ```
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/desktop/routes/register/Register.scss:1:1
> 
> Unexpected token .
> 
>      1│ .root {
>      2│   padding-left: 20px;
>      3│   padding-right: 20px;
>      4│ }
> ```
> Looks like flow tries to import these files content as is – but webpack is configured to load them es ES modules
> I have no idea how to fix that – may be you have any thoughts?

Hi, I have the same problem...

**Comment by q2870030** [comment]
@zaytsev-mxm, @NachosSs

I am facing the same issue (no error is import scss files, but errors occurs inside the actual scss file). Could you please share the solution if you found one? Thanks.

**Comment by rofrol** [comment]
@q2870030

try this https://github.com/facebook/flow/issues/338#issuecomment-349634841
