### ISSUE TITLE
Missing unreachable code with disjoint unions

### ISSUE THREAD

**Issue by lematt1991** [facebook/flow#3380]
I'm not sure if this is a bug or if this is just outside the scope of Flow (I'm using 0.39.0), but the following code

```JS
type ADT = {
  tag : 't1',
  a : number
} | {
  tag : 't2',
  b : string
}

function test2(x : ADT) : number {
  switch(x.tag){
    case 't1':
      console.log('t1');
      return 1;
    case 't2':
      console.log('t2');
      return 2;
    case 't3':
      console.log('Unreachable!!!!!')
      return 3;
    default:
      return 4
  }
}
```

1. Does not flag the `console.log('Unreachable!!!!!!')` line as unreachable
2. Gives me the following error:

```
 11: function test(x : ADT) : number{
                              ^^^^^^ number. This type is incompatible with an implicitly-returned undefined.
```

It would be hugely helpful if Flow could do (non-)exhaustive match analysis as this is one of the biggest advantages you get with algebraic datatypes in my opinion.  The second point I believe is a bug.  If I add a return after the `switch`, then Flow gives me an error about unreachable code, but if I remove it, I get an error about an implicitly returned undefined.

**Comment by BlooJeans** [comment]
I can't speak to your main question, but the default case being necessary has been reported a few times: https://github.com/facebook/flow/issues/3032

What you're hoping for is in fact possible, but not through a switch().  The following should work; You still need to return (or throw) in the default/else case (or after the if/elseif), but the `(x.tag: empty)` check will fail if you didn't exhaustively enumerate over all tags.  (Though your extraneous tag still won't cause problems) 
```    function test3(x : ADT) : number {
      if (x.tag === 't1') {
        console.log('t1');
        return 1;
      }
      else if (x.tag === 't3') {
        console.log('Unreachable!!!!!'); // but flow doesn't care
        return 3;
      }
      else if (x.tag === 't2') {
        console.log('t2');
        return 2;
      }
      else {
        (x.tag: empty);
        throw new Error('invalid tag'); // or return 0;
      }
      // could have also thrown / returned a default number here instead of in the else
    }
```

**Comment by TrySound** [comment]
Fixed https://flow.org/try/#0C4TwDgpgBAggIgFSgXigbwFBSsAhgcygC4oByYARlIBospdioA7AVwFsAjCAJwwF8oAH3R08hEuQBMNOh0YBnYNwCWTfPwwYAZiyYBjYMoD2THBEWSAFAA9G8BAEpGrTjxHZ5Ad2XA9ACxsAOjEHTGxsPVx5aHIqIjpwqD0TeSMAGwhAtKN8S1jSBwBuBPDuCGAWblMKYsTI6LJgaXjEiJT0zOzcqQLa1rKKqqhJPoiomOAAZlIW1uSmVIysnLyAVSYy3H9cDgyAQgODgpLsAcrTSdGoABMILVwWNOBZxLOhgBY6Pn4gA
