### ISSUE TITLE
Branding: Official way of saying "flowtype"

### ISSUE THREAD

**Issue by ryyppy** [facebook/flow#3382]
Hi,
I have seen all kind of variations on how to pronounce flow:

* Flow
* Flowtype
* FlowType
* flowtype
* ...

What is the official way of writing it? FlowType just looks wrong and collides with another github project called `FlowType.js`, but everyone is actually using this pronounciation, since it seems to align with `TypeScript` :-)

I would like to hear what the core devs think!
Thanks

**Comment by mroch** [comment]
![1qvhti](https://user-images.githubusercontent.com/3012/27138232-e4f69ac6-50d4-11e7-8de7-163d2ff65087.jpg)

**Comment by ryyppy** [comment]
Nice, I considered this issue to be settled when the new flow.org homepage was released :)

Thanks for the clarification!
