### ISSUE TITLE
import/export type not throwing error for that type?

### ISSUE THREAD

**Issue by kellyrmilligan** [facebook/flow#3383]
following examples in the docs, node v6.9.2
```
flow-bin: 0.39,
react-scripts: 0.9.0
```
.flowconfig:
```
[ignore]
.*/node_modules/.*
[include]

[libs]

[options]
```

code(from examples on docs)
```
import type { Foo } from './foo'
var foo: Foo = 9 * 10
```

foo.js:
`export type Foo = string;`

if I move the `type Foo = string` into where the import is at, it is working.

**Comment by kellyrmilligan** [comment]
closing, sorry it wasn't clear to me that you needed to add the `// @flow` to the exporting of the type as well 😢

**Comment by jeffmo** [comment]
Thanks for the report. Tagging https://github.com/facebook/flow/pull/2392 for tracking purposes

**Comment by jalalat** [comment]
I am still having the same issue:

PostType.js
`/* @flow */
export type Post = {
	id: string,
	title: string
};`

then importing the same into my other file:

```
/* @flow */
import React, { Component } from 'react';
import type { Post } from '../types/Post';

// type Post = {
// 	id: string,
// 	title: string
// };

class PostDetailsScreen extends Component {
	doSomething = (post: Post) => {
		post.
	}
}
```
it does not show anything with post. If i uncomment the type defined in the same file it works.
