### ISSUE TITLE
This type is incompatible with the expected param type of some incompatible instantiation of 'T' when return function with generic type

### ISSUE THREAD

**Issue by evollu** [facebook/flow#3386]
Flow: v0.37.4
Consider following wrap function
```
function wrap<T>(innerFunc: (data: T)=>any) {
    return (data:T) => innerFunc(data);
}

function inner(x:number) {};
inner(2);

let f = wrap(inner);
f(2);
```
flow throws `number (This type is incompatible with the expected param type of some incompatible instantiation of 'T')` on the last line.

Is it a bug or I did it wrong?

**Comment by mwalkerwells** [comment]
T represents the exact value, not a polymorphic inferred type. `wrap` is just the identity function & this should be written as ``function wrap<T>(innerFunc: T): T { return innerFunc }``

**Comment by mwalkerwells** [comment]
If you really wanted to, you could use this syntax to express this:

````js
type Wrap<T> = (T => any) => (T) => any

var wrap: Wrap<number> = function (innerFunc) {
    return data => innerFunc(data)
}

function inner(x: number) {};

let f = wrap(inner);
f(2);
````

But as you can see, it's just the identity function.

You're trying to do this, but it's impossible since there's no way to know the exact value of T.
````js
type Wrap = <T>(T => any) => (T) => any
````

**Comment by mwalkerwells** [comment]
> ````js
> function makeGetter<T:Object>(obj: T): <U>(key: $Enum<T>) => U {
>   return function<U>(key: $Enum<T>): U {
>     return obj[key]
>   }
> }
> ````
> The problem is that type variables in a function signature (in this case, in the signature of makeGetter) are not in scope in the function body. So we cannot refer to the type T in inner function types, or in variable types in the body of makeGetter.
> 
> http://sitr.us/2015/05/31/advanced-features-in-flow.html#existential-types

**Comment by evollu** [comment]
@mwalkerwells Thanks for your help!
What i really want is to have the wrapper and do something else before running the function. Like:
```
function wrap<T>(innerFunc: (data: T)=>any) {
    return async(data:T) => {
         try{
             await innerFunc(data);
         } catch (e) { console.log(e) }
    }
}
```
In that case the function signature is different from the function being passed in. so the first solution you post doesn't work

The makeGetter is very helpful. But I've tried to replace any T in the code above but none of the combinations works.

I tried to pass the same definition in typescript and it works. Do you think it should be a feature for flow?

**Comment by mwalkerwells** [comment]
I think this is what you're trying to do:
````js
function wrap<T, U>(transform: T => U, sideEffect: void => void): T => ?Promise<U> {
  return data => {
    return new Promise(
      (successHandler, failureHandler) => {
        try {
          successHandler(transform(data))
          sideEffect()
        } catch(e) {
          failureHandler(e)
        }
      }
    )
  }
}

declare var test: number => string

wrap(test, () => { console.log('Side Effect!') })(5)
````

**Comment by evollu** [comment]
it work! Thanks!
