### ISSUE TITLE
$ObjMap allows for incorrect typing sometimes

### ISSUE THREAD

**Issue by danwang** [facebook/flow#3387]
When using `$ObjMap`, I'm able to write a function that converts from a type to another but at runtime compiles to (basically) the identity function:

([Flow try link](https://flowtype.org/try/#0MYewdgzgLgBMAWBDMBzApgJxgXhgHgEEAaGAIQD4AKASzAAcBXKALhgIEpXSdyYBvAFAwYGNFAYYwMSn1qMoAX1YASAPIAjAFYBZRHTyz6TVgQUlKiE+x5ly7AHRymAhQG4hwz8IGUEydBiUlACMrGAMALbqmOycMNAYtCjsrkA))

```jsx
const changer = <A, B>(input: A): B => {
  return ({input}: $ObjMap<{input: A}, (a: A) => B>).input
};
        
(changer((1: number)): string);
```

I don't think I've introduced any `any` types through things like `Object` or Function`, but with this I'm able to cast arbitrary types by wrapping in an intermediate object.

I have another problem, which is that I'm trying to write a configurable HOC that takes in an object with a shape and puts props with a specific type according to the shape. Here's an example in Flow (with some implementation stubbed out as `any`):

([Flow try link](https://flowtype.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoGATzCTgFkUwB5TAHgBUA+OAXjgDeAbQDWSKgC44AZxhRgAOwDmAXSkcAvhWq04AYQgLMwJXwZNWbBQFcQAIyRQu2mnQ5QUC6ZmghOPfgASZjsAK0YwTgAaOAAKAEo+Hll5ZWdySlc4AAlmPTY9KQMjExiABRwwaXUPLx8oPz0uALjyODi0XEgFJAUYKWR0GD0AGxRpaTYKiCquRN4eQYxR8cnAgBFgTHZpqpj3T29fAuaucniKck6vLDMCosNjJXKpENCkDC5Y66ei+Klcvk9OUAjxYjYRiMpJ4qBcMmgxhM4AAhcZ0JAADxgvQAJtJEMQYAA6AzgQy9eACNpwMCVaqCantHwQKR2CAQEaoBRRakach89rtciYWICZlSACMGnisVR0iQ8SAA))

```jsx
import React from 'react';
type MapOf<T> = {[key: string]: T};
type Config = MapOf<number>;
type Transform<T> = $ObjMap<T, () => string>;

type HOC<C: Config, Props: Transform<C>> = (
  (component: ReactClass<Props>) => ReactClass<$Diff<Props, Transform<C>>>
);

const f = <C: Config, P: Object>(config: C): HOC<C, P> => (null: any);

class Base extends React.Component {
  props: {
    foo: boolean,
  }
}
    
f({foo: 1})(Base)
```

In this example, given a configuration of `{foo: 1}`, I want to enforce that the component passed in (`Base`) must prop types of at least `{foo: string}`.

With this example, I expect flow check to fail because `Base` has type `ReactClass<{foo: boolean}>` which is incompatible with expected `ReactClass<{foo: string}>`. Is there a better way to express this?

Thanks,
Dan

**Comment by danwang** [comment]
Here's another example of how `$ObjMap` can produce seemingly incorrect results:

([Flow try link](https://flowtype.org/try/#0C4TwDgpgBAglC8UDeAfAhgLigOwK4FsAjCAJxQF8BuAKFEigFk0xIATBKAEgHlCArJmAA8MADRQAFAEoEAPigBnYCQCW2AOayaEpJijLcEcYSwGI5LILZSgA))

```jsx
type A = {|a: number|};
type Mapped = $ObjMap<A, () => string>;
({a: true, b: true}: Mapped)
```

I'd expect the last line in this to fail for two reasons:
- `a` property should have type `string`
- `b` property is invalid in `Mapped`

**Comment by asolove-stripe** [comment]
@danwang As of Flow 55, the simple example above is now working. There is a type error for `a` being a boolean instead of a string. And although the default type for `$ObjMap` is a non-exact object, you can ask for an exact object to also get a type error on the `b` key:

```js
type A = {|a: number|};
type Mapped = $Exact<$ObjMap<A, () => string>>;
({a: true, b: true}: Mapped)
```

**Comment by SamChou19815** [comment]
This now errors
