### ISSUE TITLE
flow install should fail if required libraries are not available

### ISSUE THREAD

**Issue by mattkime** [facebook/flow#3397]
installing flow on the official docker images ( https://hub.docker.com/_/node/ ) succeeds but you're unable to run flow due to missing dependencies. ( must `apt-get install -y ocaml libelf-dev` )

it should fail instead. 

also useful - a way to tell if the required dependencies are available before installing.

**Comment by vkurchatkin** [comment]
How do you install Flow?

**Comment by mattkime** [comment]
@vkurchatkin its necessary to extend the base node image as shown here - https://github.com/meetup/node-flow/blob/master/Dockerfile

and then its installed via 'npm install'

**Comment by mattkime** [comment]
Actually, it would be preferable if flow did not rely on any external libraries although i assume there's some degree of difficulty there.

**Comment by vkurchatkin** [comment]
If you you install it as `flow-bin` from npm then it's better to report this issue there

**Comment by mattkime** [comment]
@vkurchatkin sorry, report it to which project?

**Comment by vkurchatkin** [comment]
This one: https://github.com/flowtype/flow-bin

**Comment by mattkime** [comment]
ah, thank you!
