### ISSUE TITLE
Is it possible to cast an Object to an exact type?

### ISSUE THREAD

**Issue by ml9951** [facebook/flow#3398]
I asked this same question on [StackOverflow](http://stackoverflow.com/questions/42288594/is-it-possible-to-cast-an-object-to-an-exact-type-in-flow), but thought I'd post it here too.

I'm wondering how one might go about casting an Object to a user defined exact type in Flow. For example:

```JS
//@flow
type exactType = {|x : number|}

function test(a : Object) : exactType {
  if(typeof(a.x) === 'string'){
    return (a : exactType);
  }
  throw new Error('Incorrect type!')
}
```

Is it possible to write such a function? I.e. is it possible to convince the type checker that parameter `a` has only a single field named `x` with type `number`?

**Comment by nmote** [comment]
Answered on SO
