### ISSUE TITLE
Improve reporting of JSX element type error

### ISSUE THREAD

**Issue by kdojeteri** [facebook/flow#3401]
The current error log does not help very much in recognizing type errors in JSX when it comes to tags. A more complex version of the following example got me wondering why the heck Flow needs `BaseKitten` to be compatible with `React.Component`.

```js
// @flow

import {Component} from 'react'

declare class BaseKitten {
  props: {
    color?: string
  };
}
    
function renderKitten(Kitten: Class<BaseKitten>, props) {
  // Play with Kitten and props
  
  return <Kitten {...props}/>;
}
```

```
11: function renderKitten(Kitten: Class<BaseKitten>, props) {
                                        ^ BaseKitten. This type is incompatible with
[LIB] static/v0.39.0/flowlib/react.js:105: type _ReactClass<DefaultProps, Props, Config: $Diff<Props, DefaultProps>, C: React$Component<DefaultProps, Props, any>> = Class<C>;
                                                                                                                        ^ React$Component
```

To improve the error log, I suggest adding a line pointing to the JSX element that infringes upon the declared type. Something like this instead would go a long way:

```
14:   return <Kitten {...props}/>;
              ^ Kitten. JSX tag class is incompatible with
[LIB] static/v0.39.0/flowlib/react.js:105: type _ReactClass<DefaultProps, Props, Config: $Diff<Props, DefaultProps>, C: React$Component<DefaultProps, Props, any>> = Class<C>;
                                                                                                                        ^ React$Component
```

**Comment by asolove** [comment]
What do you expect to happen when you render `<BaseKitten />` in this case? JSX tags like this work with two types of values for the tag name. 

- One type is pure functions, which take props as inputs and returns more JSX as its output.
- The other option is Components, which inherit a bunch of behavior from React and ultimately return their rendered output in a `render` method.

Since `BaseKitten` is neither a functional component nor a full React component, it's not clear what should happen when it's used in a JSX tag.

I'm sure the real code is more complex than this and there are good reasons why it needs to do this. If you tell me what the rest of the code's constraints are and what you expect to happen, maybe we can find a creative solution that makes everything work.

**Comment by Peping** [comment]
Here's a different example to illustrate my actual issue.
[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdyAJkWdCY6JyQM79QAIQFEA0ily4iAO1ABvRKFAZqGfgC5Fylb1hxsAfm39c2FLIDmugL4BuRLd0rEkAK6yKKWPICiAB4kmNBEAIwAFJLSctoAwlyCADyi-BJSMrIAfAA0qur8AJQ6Koy47tjySdGZigB0DWqwGrbAWY7OeqBunt6+oIHBGKEATFEZsaAJAvwpYjVyufnNRSWgZRXyxOS4dWSMJDJ+oWhyuOMxsnlNGoUdQA)
```js
// @flow
import React from 'react'

declare class BaseKitten {
  props: {
    color?: string
  };
}
    
function Example1(Kitten: Class<BaseKitten>, props) {
  return <Kitten {...props}/>;
}
    
function Example2(Kitten: Class<BaseKitten>, props) {
  return React.createElement(Kitten, props);
}
```

The error output says 
```
10: function Example1(Kitten: Class<BaseKitten>, props) {
                              ^ BaseKitten. This type is incompatible with
10: function Example1(Kitten: Class<BaseKitten>, props) {
                              ^ React$Component
--------------------------------------
15:   return React.createElement(Kitten, props);
                                 ^ BaseKitten. This type is incompatible with
15:   return React.createElement(Kitten, props);
                                 ^ React$Component
```

Notice that in Example1 the arrow points to the parameter declaration, but in Example2, it **points to the place where the actual error occurred.** I'd expect the error to always point to the origin of the error, but in case of JSX, it doesn't. This is what I'd like to see fixed. 

Is there something I don't see that's preventing this from happening?

**Comment by asolove** [comment]
Ah, ok, that makes sense. Thanks for clarifying.

Issues like this are pretty common in Flow. The place where the typing algorithm happens to notice an inconsistency is not reliably the place where the code needs to change. If you have specific, more complex cases like this, you can use `flow check --traces 10` to get more information about all the reasoning that led flow to find this error, and the place where code should change usually shows up in there.

(/cc @calebmer for "Confusing error message location" label)

**Comment by SamChou19815** [comment]
The error messages should be much better now.
