### ISSUE TITLE
How to mixin type?

### ISSUE THREAD

**Issue by shineli1984** [facebook/flow#3402]
For the following:
```
// @flow

type Maybe<A> = Just<A> | Nothing

interface Functor<A> {
  map<B, FB: Functor<B>>(f: (a: A) => B) : FB
}

class Just<A> {
  value: A

  constructor(x: A) {
    this.value = x
  }

  map(f) {
    return new Just(f(this.value))
  }
}

class Nothing {
  map(_) {
    return this
  }
}

const fromNullable = <A>(v: ?A): Maybe<A> => {
  if (v) {
    return new Just(v)
  }
  return new Nothing()
}
```

How do I indicate the value produced by `fromNullable` is a `Functor` other than doing:
```
const maybeValue: Functor<string> = fromNullable('123')
```

I'm looking for a way to say Maybe is a Functor before any object of Maybe is produced.

**Comment by SamChou19815** [comment]
https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZlduuSMTBJC-Mgz4sHwNSBos6A6u9w1mbGqJUoBaCRHEzrcDEgBrbAk62mPhXFxJ91v7x+fRHEp3gxCKBgNpUU7nAF5KBQA7tEhUJ4VJqmDA+SEgIEwsBwhHHCCMTZQbjHOoYCrooHwmDYY4Ie5HSgkY5kCQM7ZXKH5E7MdJwMgAgC+-EgGiSAHoxQACAACMCIAHcADpQZVnYySgCydBwAB4AIIAPklAF5JQApfISfVGgA+koAchAJLUKghrcrlRUGVxsZKAGJA5QQSjWyXAZWSyUZRg6gBCBoAFDBkJKExgU3qAJQmo2x7MpgPAtIh+PKgUe4G4DAkEjmy2hsyMNreAL+wPF0PhqCRpq4GQZiuR2z2aRBygJ+QZ7NdyOR518qy9mQmyXyCOS8sq7tRjAx+NJlNpqc5yV5yUF9vBuNGmezlgSISUbsw+V1+xJhPzkiL7gyTOZ9dN03ZUQWrWtHXnKA3UNSVG2bCxa0LMdO3XaNrwTfAUyKEo2EzC8iyveMw3XSN70fZ9sFfCCXSghNMwAbkAssK2HCRJRgSh0ntbQqzQNoV2tBMGhTAB+LMUy1WhdRg40b3XOAYFTBppxIyUyKfSUXzfCQhIA7dN1I+5yM0yiHSdGiEDostchABoTBIOBoCSBoAAYrAAJgAFgAZisFyQAFIA
