### ISSUE TITLE
`some incompatible instantiation of` when checking polymorphic functions

### ISSUE THREAD

**Issue by ghost** [facebook/flow#3403]
I have no idea what I am doing wrong, but when trying to work with polymorphic functions I keep hitting the same wall of `some incompatible instantiation of`. Any idea what I am doing wrong?

[Example](https://flowtype.org/try/#0C4TwDgpgBAogjgVwIYBsDOAhEUC8UA8A8gEYBWANFAGqoIQB8AFCabvdbRJTSnQJRsozMoOIB7MSghIAdnwBQEAB5gxAJ2BQAxmJlpNERKkwgAXLCPosuIQDNKAN04Cc7RmJGuot92Rc48J14IPiA).

```
type EqualsBy = <Obj, Value>(Obj => Value, Value) => (Obj => boolean)
export const equalsBy: EqualsBy = (f, value) => (obj => f(obj) === value)
```

EDIT:
Easier [example](https://flowtype.org/try/#0C4TwDgpgBAogjgVwIYBsDOAhEUC8UA8A8gEYBWANFAGqoIQB8AFCabvdbRJTSnZSwEo2UYgHtRKCEgB2AKAgAPMKIBOwKAGNR0tOoiJUmEAC5YB9FlxRGAM0oA3TpVFkhOdo97QcPqDcYupAJAA) with same problem:
```
type EqualsBy = <Obj, Value>(Obj => Value, Value, Obj) => boolean
export const equalsBy: EqualsBy = (f, value, obj) => value === f(obj)
```

**Comment by vkurchatkin** [comment]
You can't assign non-polymorphic function to a polymorphic type. Something like this works:

```js
export const equalsBy: EqualsBy = <Obj, Value>(f: (Obj => Value), value: Value): (Obj => boolean) => (obj => f(obj) === value)
```

**Comment by MoeSattler** [comment]
> `export const equalsBy: EqualsBy = <Obj, Value>(f: (Obj => Value), value: Value): (Obj => boolean) => (obj => f(obj) === value)`
Thanks, that works. Unfortunately, it is even less readable. 

>You can't assign non-polymorphic function to a polymorphic type. 
Why is that?

**Comment by vkurchatkin** [comment]
Well, that's just the way Flow works. It never infers polymorphic functions

**Comment by MoeSattler** [comment]
@vkurchatkin Ahh ok, thank you. I am new to flow type, and I find it sometimes a bit complicated. 
Could you point me to the correct page in the docs? I couldn't find it :(

**Comment by vkurchatkin** [comment]
Don't think it's mentioned, although it probably should be

**Comment by iclanzan** [comment]
> It never infers polymorphic functions

This is the biggest gripe I have with Flow.

**Comment by SamChou19815** [comment]
We now require annotations, so it should be no longer confusing.
