### ISSUE TITLE
`setState` type is unsound

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3404]
Example:

```js
type State = {
  foo: string,
  bar: number
}

declare function setState(partialState: $Shape<State>): void;

const state: { foo: string } = { foo: 'foo', bar: 'boom' };

setState(state);
```

**Comment by jesseschalken** [comment]
To solve this, should `$Shape<..>` only accept exact object types?

**Comment by vkurchatkin** [comment]
> To solve this, should $Shape<..> only accept exact object types?

Yep. I think this shouldn't really break much code as people mostly use `setState` with literals

**Comment by masaeedu** [comment]
@jesseschalken Not understanding how that fixes the issue. Is this a correct interpretation of what you're suggesting?

```
// If this type isn't exact...
type State = {|
  foo: string,
  bar: number
|}

// ...error over here
declare function setState(partialState: $Shape<State>): void;

const state: { foo: string } = { foo: 'foo', bar: 'boom' };

setState(state);
```

**Comment by jesseschalken** [comment]
@masaeedu I mean the type `{ foo: string }` would not be compatible with `$Shape<State>` (regardless of what `Shape` is) because `{ foo: string }` is not exact. I've adjusted my comment to be more precise.

**Comment by tonai** [comment]
Is this related to the following error I have in a React component ?
```jsx
// @flow
import React, { PureComponent } from 'react';

type CustomType = {
  prop: string
};

type Props = { data: CustomType };
type State = null | CustomType;

/********** Stateless component **********/
export class Component extends PureComponent<Props, State> {
  state = null;

  componentDidMount() {
    this.setState(this.props.data); // Flow: Cannot call `this.setState` with `this.props.data` bound to `partialState` because property `prop` is missing in `CustomType` [1] but exists in `State` [2].
  }
}
```

**Comment by SamChou19815** [comment]
Now we change it to use `Partial` instead of `$Shape`, it should be sound now.
