### ISSUE TITLE
In-method argument suggestion

### ISSUE THREAD

**Issue by aight8** [facebook/flow#3406]
It would be state-of-the-art if flow could support information about the current argument signature (of the cursor position).
The argument on the current cursor position should be marked also - so it can be bolded or colorized by the IDE.

**Comment by asolove** [comment]
Hey @aight8, is this roughly what you mean? If not, can you explain what is missing? This is the way the current VSCode integration works, it's pretty spiffy.

<img width="516" alt="screen shot 2017-08-21 at 4 41 26 pm" src="https://user-images.githubusercontent.com/8495/29541184-b3c2c808-868f-11e7-955f-893bdfc80ca9.png">
