### ISSUE TITLE
Autocompletion for built-in types

### ISSUE THREAD

**Issue by aight8** [facebook/flow#3407]
There are several built-in types. It were nice and state-of-the-art if flow could suggest those types while typing. (like typescript)

```
let x: Ob|
```

Ctrl+Space at | in the editor (or just fetch suggestion from flow server).

Should return "Object" or any other built-int type (or even declared types which match).

Or:
```
$Flow|
```
this would list all the built in types which starts with $Flow.

This would be a useful feature, and would make flow much better, like intelli-sense, from **MicroSoft**

**Comment by asolove** [comment]
@aight8 Flow now has a number of great [editor integrations](https://flow.org/en/docs/editors/) that offer various forms of autocomplete and other tools.. I personally can highly recommend the VSCode one.

If you have a specific question about those integrations, I'm happy to try to help, but I think this issue can be closed as not a problem with the Flow code itself.
