### ISSUE TITLE
Type check by property is failing

### ISSUE THREAD

**Issue by dfleury** [facebook/flow#3413]
I was expecting that checking by a required prop would be enough to Flow understand that a variable fits a type, but I'm getting an error:

```javascript
/* @flow */

type duke = { title: 'Sir' }
type maybeDuke = { title?: 'Sir' }

function forward(foo: maybeDuke) {
  if (foo.title === 'Sir')
    doSomething(foo)
}

function doSomething(foo: duke) {}
```

```
8:     doSomething(foo)
                   ^ object type. This type is incompatible with the expected param type of
11: function doSomething(foo: duke) {}
                              ^ object type
```

I've tested the undocumented helper $Supertype<T> and it seems to silence the error. At the same time, if I remove the `if (foo.title === 'Sir')` condition, I got no messages about a possible violation of foo be not compatible with `duke` type.
```javascript
function doSomething(foo: $Supertype<duke>) {}
```

So I'm in doubt if i'm doing right or there are a better way to accomplish that...

**Comment by vkurchatkin** [comment]
What you are trying to do is unsafe, because `title` might be deleted in the future

**Comment by dfleury** [comment]
Do I need to copy foo or similar?

**Comment by mwalkerwells** [comment]
Think of...
````js
type duke = { title: 'Sir' }
type maybeDuke = { title?: 'Sir' }
````
...as the same thing as
````js
type duke = { title: 'Sir' }
type maybeDuke = { title: 'Sir' | void }
````

A few things...
• Objects are invariant by default
• ``'Sir' | void`` is a supertype of ``'Sir'``
• Functions that accept objects with supertypes of some properties, need to be marked as write-only or contravariant with a ``-``.

Updating ``doSomething`` to the following makes this type check, but you can only write to ``foo.title``, not read from it.
``
function doSomething(foo: { -title: 'Sir' }) {}
``

An alternative would be to move the null check into ``doSomething``...
````js
function doSomething(foo: { title?: 'Sir' }) {}
````
