### ISSUE TITLE
Cannot use Unions with Symbols

### ISSUE THREAD

**Issue by StreetStrider** [facebook/flow#3416]
Flow: 0.39.0.

I'm trying to implement something like `Maybe<T>` but with Symbols.
[flow try](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAdhgIYDGGeAJgDwAqAfGALxgNgA+YAylgFsARnBgBudNnx8AlgHNiZDAFcATnlTsA2kVKVq9AM4ZVM4nKYAaMMWXC8qsAF1UPHbfuOnE1FGXEqGThiMCg4ODAACgA6WLJVOUMALlkFJTU8AEpUAG9UAEhgYDB4xLA4R1K7PFJDQDICVABfdAA3eN1yKjY+QREYSIByEk6MAezfcMGyAesARmywuEjh-TmFyfnUIA)
```typescript
/* @flow */
type Intacted<T> = T | Symbol;

type Signature
= [ Intacted<string>, number ]
| [ number ];

function foo (...args: Signature)
{
	// args or arguments…
}

var Intact = Symbol('Intact')

foo('a', 1)
foo(Intact, 1)
foo(1)
```
I'm expecting all three invocations to typecheck. However `Intacted` var is checked only against `Symbol` and not `string` (I do not know why). Same if I use verbatim `string | Symbol` or `Symbol | string`.

As a minimum solution I would glad if this will work. As a 100% solution it would be awesome to support literal types on top of Symbols (Symbols is truely a literal type).

----

To workaround I've invented such hack:
[try flow](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKAlgOYB2AhhgK4BOeqAvGANpgDOGdx5pANGHI0AtgCM8dMAF1UAHzZEs4uDEHDxkmfMUaJU6QG50UGuQDGGYnHJgocOGAAUAOjeU6pDgC4iZKrQMAJSoAN6oAJDAwGAeXmBwUnGieOQYHIBkBKgAvugAbh5gAJJplJZgLITKYqpOAOQlGGUYdSGo9nD1lHWCAIwhHU6NzX0DDk79qEA)
```typescript
/* @flow */

type Signature
= [ string, number ]
| [ Symbol, number ] // as an Intacted<string>
| [ number ];

function foo (...args: Signature)
{
	// args or arguments…
}

var Intact = Symbol('Intact')

foo('a', 1)
foo(Intact, 1)
foo(1)
```

but in that case Flow strangely can't choose which variant to pick and asks me to merge my declarations. And If I do I got the first issue again. :confused:

**Comment by mwalkerwells** [comment]
``...args`` needs to be an Array<T> to type n arguments, n=1|2. Not sure what you're trying to accomplish here, but if ``foo`` needs to take 1 or 2 args, you could type it as:

**Option 1**
````js
type Intacted<T> = T | Symbol

declare var foo :
	& ((argA: Intacted<string>, argB: number, ...rest: Array<void>) => void)
	& ((argA: number, ...rest: Array<void>) => void)
````

**Option 2**
````js
type Intacted<T> = T | Symbol
type Signature = Intacted<string> | number
declare function foo (...args: Array<Signature>): void
````

**Comment by StreetStrider** [comment]
@mwalkerwells, hello. Thanks for answer.
I'm trying to create multimethod or overload function to work as such:
```
foo(string, number)
foo(number)
```
with the possible of first argument being Intacted:
```
foo(Intacted<string>, number)
foo(number)
```

Before 0.39 I was using the same mechanism you mention in Option 1. That seemes work, but in 0.39 release notes the following features had been mentioned:
> - Flow now supports constant-folding of tuple types. In general this means that Flow can now better understand rest elements and array-spreads when tuples are involved.
> - Flow now supports spreading types that are iterable (other than just Arrays).

I try to switch to it because it would grant the code a better view, than Option 1, especially since my return type is not varying. Take a look at `Signature`, it is much more readable (I think).

The problem with Option 1 or with new tuple feature (both works OK for function overloading), that Flow likely stops its analysis when faced `Symbol` in union. 
So it can't typecheck `string` against `string | Symbol`.

**Comment by mwalkerwells** [comment]
> Before 0.39 I was using the same mechanism you mention in Option 1. That seemes work, but in 0.39 release notes the following features had been mentioned:

Ah, didn't know this! This distracted me from the problem...

> both works OK for function overloading

hmmmm....ok, I see the issue now...


You need...
````js
var test: Intacted<string> = 'a'
foo(test, 1)
````
...not
````js
foo('', 1)
````

Arrays and Tuples are invariant. This example also does not work:
````js
declare function foo(...rest: [ ?string, number ]): void

foo('a', 5)
````

**Comment by mwalkerwells** [comment]
Invariant meaning that you cannot use Supertypes or Subtypes.

While an aside, even though the documentation says Arrays are invariant ($ReadOnlyArray (covariant) was recently added), there are no errors on this example (leaving me confused...):

````js
function foo(...rest: Array<?string>): void {
  arguments.forEach(item => { item = null })
}

var __optionalString: ?string = 'a'
var __string: string = 'a'
var __stringLiteral: 'a' = 'a'

foo(__optionalString, __string, __stringLiteral, 'a')

````

**Comment by StreetStrider** [comment]
@mwalkerwells, your solution works. Mentioning specific type do the trick indeed.
I can do it even inline, like `foo(('a': Intacted<string>), 1)`, strangely, I don't need to do this with Symbols: `foo(Intact, 1)` just works (maybe for the same reason your last example works).
Sometimes I stumble upon all this in/co/contra-variance biz, they are not a often part of my practice. Thanks for helping this out.
