### ISSUE TITLE
Flow failing to recognise null/undefined check in function.

### ISSUE THREAD

**Issue by chris-cooper** [facebook/flow#3417]
Repro [here](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wB+AeQCMArAUwIEp6BnfACdC2AOZgA3qjBhCUMDTABeJWGyYYMbpOkywgjvkyDSAcgCeHPqYDcugL66DRk2GoA6AcLEA3AIYwmBx2jhg4BMSkhHwAcoQwlHxwALaGABYiovTM7Fz4vGAsFDAcfqRSMs7GpEmp+BliyqrqmiHoWHhEJGQUAEw02aycPPxCmToycgrRcQnU3NoVelWuFla2Dk6G1W6eY74BQW1AA).  foo() is OK, foo2() errors.  This prohibits the use of e.g. lodash isNil().

**Comment by homywu** [comment]
I have exactly the same issue here, anybody help?
my flow version is 0.38.0.

**Comment by AugustinLF** [comment]
Flow has issues with predicate functions, see #34. However, is is possible to annotate a function as helping for refinements, with keyword `%checks`, see this [example](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wB+AeQCMArAUwIEp6BnfACdC2AOZgA3qjBhCUMDTABeJWGyYYMbpOkywgjvkyDSAcgCeHPqYDcugL66DRk2GoA6AcLEA3AIYwmBx2jhg4BMSkhHwAcoQwlHxwALaGABYiovTM7Fz4vGAApLhpXADWfDoyzsakSan4GWLKquqaIehYeEQkZBQATDTZrJw8-EKZVbLylNFxCdTc2lJ6+oa1YBZWtg5O664eXpn+gcGojkA).

**Comment by defdata** [comment]
Any updates on a workaround? I'm trying to use lodash's isNil and flow doesn't seem to recognize the check.

**Comment by WhatIfWeDigDeeper** [comment]
Ran into same problem with Flow not understanding Lodash's isNil check.  I even added the [flow type](https://github.com/flowtype/flow-typed) for Lodash.  It has a generated signature of

`isNil(value: any): boolean`

Thanks

**Comment by greg-murray-volusion** [comment]
Wonder whether supporting some kind of attribute in the flow type file would be an option to indicate to Flow that the method does null checking.  Perhaps using the linting comments to indicate kind of like the skip on sketchy null, but in the reverse direction.

I just prefer the readability of functions.  Thank you.

**Comment by adeperio** [comment]
This is getting me too. I don't think the attribute suggestion is optimal. I think Flow should just be able to check this directly, like in other static typed languages.

**Comment by mrkev** [comment]
[this works](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wB+AeQCMArAUwIEp6BnfACdC2AOZgA3qjBhCUMDTABeJWGyYYMbpOkywgjvkyDSAcgCeHPqYDcugL66DRk2GoA6AcLEA3AIYwmBx2jhg4BMSkhHwAcoQwlHxwALaGABYiovTM7Fz4vGAsFDAcfqQApLhpXADWfDoyzsakSan4GWLKquqaIehYeEQkZBQATDTZrJw8-EKZDbLylNFxCdTc2lJ6+obNYBZWtg5Ou64eXpn+gcGojkA).

**Comment by mrkev** [comment]
Adding to this: my guess is `%checks` is probably less performant, and not all functions that return booleans are doing refinements, so there's probably some performance gain from explicitly enabling the extra complexity.

**Comment by Brianzchen** [comment]
Using `%checks` is the right approach here and answers the initial question.

In regards to `isNil`, flow-typed has since added an [overloaded def](https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/lodash_v4.x.x/flow_v0.104.x-/lodash_v4.x.x.js#L900) so that it can handle type refinement so testing with the below code would work.

```
// @flow
import { isNil } from 'lodash';

function t(a?: boolean): boolean {
  if (isNil(a)) {
    return false;
  }
  return a;
}
```
