### ISSUE TITLE
Wrong error location for an invalid functional react component

### ISSUE THREAD

**Issue by AriaMinaei** [facebook/flow#3419]
In today's last commit 72327c893c04b9e4c3d862ca7f815d386c7e73b5, the following code produces a correct error in the wrong location:

```
// @flow

type FunctionalComponent<Props> = (props: Props) => ?React$Element<any>;

// The error appears in this line under 'foo':
const InvalidFunctionalComponent = () => 'foo';

// but it should appear here under InvalidFunctionalComponent:
(function(a: FunctionalComponent<any>){})(InvalidFunctionalComponent);
```

[Playground link](https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMQK4B2AxigJayECG0AwrALYaVaEoA8ACgE6wYDOAPlABeUAAoMvAQC5QPPvwCUo4QH4ASliqkAJAFFoWBqw5VCaQQG5kIUABUAFjizde3UFQzYq3fqDJCUBRHMn9oQJwiABNXUABySFhYeJlEYkp+FFAASUIANxoyaIISckoaeiYWNlEJFRFhROT4m0Q7ACN8bLJs-kdYfGhoz29tD2duKMJYjzzCiJKiUgpqOkZmQlM08Uhl8sJxKjlSlYr16q22dnNLJQBvAF8lcXmipbLVyo2alCUrIA)

**Comment by asolove** [comment]
Just to be clear, I don't think this has anything specifically to do with react. It's just a question of the order in which type inference happens for polymorphic types and functions. After a little jiggering around, here's [a smaller, non-React example](https://flow.org/try/#0C4TwDgpgBAKgFgSwHYHMQGED2SDOwBOArgMbCb4A8AGgHxQC8UAFAJQN1UDcAUKJFADlCAWwBGEfFlwESZfA1iJUGbHiKlyFJCPH4aPbsVXAoASSQA3AIYAbBABN4yNFLWzyC1uygAiAGaYmD4GTH6ESKQI2ExWAFyCOhKuMhr4LADeAL4sTObWdo5KLsbqciycQA):

```js
type ThingyConstructor<X> = () => X;
type NumberConstructor = ThingyConstructor<number>;

const InvalidThingyConstructor = () => "foo";

(function(a: NumberConstructor){})(InvalidThingyConstructor);
```

(@calebmer if there are plans to try to fix them, we might want to start a label for "confusing error location" type issues. If not, we should probably write a lengthy blog post on finding weird error locations and using traces, and then close a lot of issues like this.)

**Comment by samwgoldman** [comment]
Fixed in master. Error is now:

```
Error: test.js:9
  9: (function(a: FunctionalComponent<any>){})(InvalidFunctionalComponent);
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with the expected param type of
  9: (function(a: FunctionalComponent<any>){})(InvalidFunctionalComponent);
                  ^^^^^^^^^^^^^^^^^^^^^^^^ function type
  This parameter is incompatible:
      6: const InvalidFunctionalComponent = () => 'foo';
                                                  ^^^^^ string. Inexact type is incompatible with exact type
      3: type FunctionalComponent<Props> = (props: Props) => ?React$Element<any>;
                                                              ^^^^^^^^^^^^^^^^^^ exact type: object type
```
