### ISSUE TITLE
stuck at merging inference

### ISSUE THREAD

**Issue by chrisblossom** [facebook/flow#3430]
Flow gets stuck on ``merging inference`` on startup after upgrading to ``v0.39/v0.40``. ``v0.38`` and prior did not have this issue. I wasn't able to find a good way to debug what is going on, please advise how I can investigate further.

```
➜  ~ cat /private/tmp/flow/zSUserszSchriszSgithubzStruewell.log
[2017-02-25 09:15:59] Initializing Server (This might take some time)
[2017-02-25 09:15:59] executable=/Users/chris/github/app/node_modules/flow-bin/flow-osx-v0.40.0/flow
[2017-02-25 09:15:59] version=0.40.0
[2017-02-25 09:15:59] Parsing
[2017-02-25 09:16:03] Building package heap
[2017-02-25 09:16:03] Loading libraries
[2017-02-25 09:16:04] Running local inference
[2017-02-25 09:16:06] Re-resolving directly dependent files
[2017-02-25 09:16:06] Calculating dependencies
[2017-02-25 09:16:06] Merging
➜  ~
```

**Comment by avikchaudhuri** [comment]
@chrisblossom Need more context. Can you share your code, or selectively change `@flow` to `@noflow` in your files until you can share a small repro?

**Comment by chrisblossom** [comment]
@avikchaudhuri thanks for the response. I am unable to share as it is an internal web app that is decent in size. 

Was hoping for a suggestion on putting flow into some sort of debug mode that would tell me / hint to which file is causing the issue.

**Comment by natenorberg** [comment]
We just had the same problem. We had to do "find all and replace" for `// @flow` directory by directory until we narrowed it down to one file. Then we commented out the file and uncommented it until it started hanging again.

What ended up fixing it was when we added type definitions to the args of a function. I'm not quite sure why it was causing problems though.

**Comment by chrisblossom** [comment]
Found and fixed by removing a function annotation and then adding // $FlowIssue to suppress the missing annotation error.

Here is an example of the issue:
https://github.com/chrisblossom/flow-3430

**Comment by avikchaudhuri** [comment]
Excellent, thanks for the shall repro. I'll take a look.

**Comment by billschaller** [comment]
Workaround: use concat

```js
foo = foo.concat([fun()]);
// TODO re-enable in flow 0.42
// foo = [...foo, fun()];
```

**Comment by philikon** [comment]
Your reproduction seems to touch the intersection of rest args and Array spread, much like what I described in #3370. #3443 is another description of the same issue with a minimalist repro case. The problem seems to go away when you add type annotations to the rest args explicitly.

With two new bug reports today (#3526, #3528) that might very well be related to this issue, I hope this gets fixed soon.

**Comment by yqz0203** [comment]
I belive it's because of depends recursively.
