### ISSUE TITLE
Flow doesn't warn about an undefined variable

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3432]
Background: I refactored some code and what used to be available directly as a variable because it was obtained using a destructuring assignment that extracted the value from within an object now had to be gotten from the object.

Problem: I missed one access to the variable - because Flow did not warn me about the variable `status` having not been defined:

```javascript
if (status === "foobar") {

}
```

I had to change that to `someObject.status` (EDIT: but this is just part of my background story explanation and otherwise not relevant for the ticket, the "object" part of my explanation is just that this is how I ended up there, but it's really just about the implicitly global variable -- not declared anywhere - that should raise an alarm).

Since attempting to run the code results in a `ReferenceError: status is not defined`, shouldn't Flow find that problem sooner?

Tiny demo project attached (see lib/test.js for the single statement): [Test.zip](https://github.com/facebook/flow/files/801944/Test.zip)

**Comment by jesseschalken** [comment]
Is this the same as #3318?

**Comment by lll000111** [comment]
No, the object here is just the background story how I git caught. The essence is that an undeclared variable isn't noticed. Is there a switch I forgot to set that implicit globals are errors?

**Comment by jesseschalken** [comment]
Apparently there is a global variable called `status`: https://github.com/facebook/flow/blob/a6f8432df0f5443cf37199c685136a910868ebee/lib/dom.js#L3108

If that is a legitimate global variable, I'm not sure what Flow can do to help.

**Comment by lll000111** [comment]
None of these trigger anything:

```javascript
'use strict';

if (status === "foobar") {

}

if (undefinedVariable === "foobar") {

}

if (somethingVeryWeird === "foobar") {

}
```

**Comment by jesseschalken** [comment]
[try flow](https://flowtype.org/try/#0OQVwzgpgBGAuBOBLAxrYBuAUJxAzKAFHAIazhQC8VUARLgPb0BGx8NAlFAN7YC+2eQiAB2AEwi5EwiKIBqrRMSYAbaFQq0GzVh258B+IvQC2EWAAspAc1kR4ATwDqERPFGVqdRizacemXiA)
```
7: if (undefinedVariable === "foobar") {
       ^ identifier `undefinedVariable`. Could not resolve name
11: if (somethingVeryWeird === "foobar") {
        ^ identifier `somethingVeryWeird`. Could not resolve name
```

**Comment by lll000111** [comment]
```javascript
me@me-MAINPC MINGW64 ~
$ cd ~/Projects/Test

me@me-MAINPC MINGW64 ~/Projects/Test
$ cat .flowconfig
[ignore]

[include]
./lib/*.js

[libs]
.flowDecls/

[options]
module.ignore_non_literal_requires=true


me@me-MAINPC MINGW64 ~/Projects/Test
$ flow --version
Warning: `flow --version` is deprecated in favor of `flow version`
Flow, a static type checker for JavaScript, version 0.39.0

me@me-MAINPC MINGW64 ~/Projects/Test
$ flow lib/test.js
Launching Flow server for C:\Users\me\OneDrive\Projects\Test
Spawned flow server (pid=7364)
Logs will go to C:\Users\me\AppData\Local\Temp\flow\CzCzBUserszBmezBOneDrivezBProjectszBTest.log
No errors!

me@me-MAINPC MINGW64 ~/Projects/Test
$ cat lib/test.js
'use strict';

if (status === "foobar") {

}

if (undefinedVariable === "foobar") {

}

if (somethingVeryWeird === "foobar") {

}
```

**Comment by lll000111** [comment]
_The `// @flow` comment at the top of the file was missing...._

Anyway, I'm using node.js so there is no `status` variable. I also think accidentally using a global variable, especially one with a common name like "status", is something I'd like to be warned about.

**Comment by nmn** [comment]
Closing as the source of the bug seems to have been found.

(@lll000111 I'll make a separate feature request to allow overriding the core type defs so you can use Flow without the browser types when working in Node.)
