### ISSUE TITLE
Extend maybe type, maybe...

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/flow#3433]
Sorry if it was discussed before or it doesn't make any sense, but:

```js
?string -> string | null
??string -> string | null | void
```

Thoughts?

**Comment by jesseschalken** [comment]
While I agree that `?T` should mean `T | null` (see https://github.com/Microsoft/TypeScript/issues/7426#issuecomment-195743448), I think that ship has already sailed.

I'm not sure how the Flow team decided `?T` should mean `T | null | void`, but the JavaScript community is so chock-full with disagreement on the purpose of `null` and `undefined` that it's probably impossible to change Flow's shorthand now that it's already been implemented.

**Comment by nmn** [comment]
I don't think this change is worth making anymore as it would probably cause more confusion than good. Further, I don't think bike-shedding over this is going to be productive as you CAN use `string | null` if that's what you need.
