### ISSUE TITLE
Const as type

### ISSUE THREAD

**Issue by lasekio** [facebook/flow#3439]
If this works:
```js
// @flow 
type UpdateAction = {
  type : "UPDATE_ACTION",
};
```
I would like to use constant as type like that:

```js
// @flow 

export const UPDATE_ACTION = "UPDATE_ACTION";

type UpdateAction = {
  type : UPDATE_ACTION,
};
```

So I can use const in rest of my app.

**Comment by nmote** [comment]
There is currently syntax for this. You can write 

```js
// @flow 

export const UPDATE_ACTION = "UPDATE_ACTION";

type UpdateAction = {
  type: typeof UPDATE_ACTION,
};
```

Unfortunately, Flow considers `typeof UPDATE_ACTION` to be `string`, if I remember correctly. I'm not sure why, but experience tells me that there is usually some gotcha that I haven't thought of in cases like this. Maybe one of the type system experts can weigh in.

**Comment by laskos** [comment]
@nmote I know `typeof` syntax, but it's not that case. `typeof UPDATE_ACTION ` is `string` and it is expected and correct. String could be a type itself as I've shown in the first example.

**Comment by philikon** [comment]
What about declaring `UPDATE_ACTION` *not* to be a string but a literal?
```
export const UPDATE_ACTION: "UPDATE_ACTION" = "UPDATE_ACTION";
```

A little repetitive, but at least it keeps the repetition confined to just that one line :)

**Comment by nmn** [comment]
Here's another trick that works to reduce the amount of code duplication:

https://gist.github.com/rendro/4c9f4ddea8133bbddc3df427a8f62b9e

**Comment by SamChou19815** [comment]
We are unlikely to support this. However, we might support something like `as const` in TS.
