### ISSUE TITLE
Destructing a constructor parameter and assigning

### ISSUE THREAD

**Issue by iddan** [facebook/flow#3441]
```JavaScript
export default class Analyst {
  
  transactions : Array<string>;

  constructor({ transactions }) {
    this.transactions = transactions;
  }
}
```
errors:
```
5:   constructor({ transactions }) {
                 ^ destructuring. Missing annotation
```
tested on https://flowtype.org/try (v0.40.0)
When removing export default it works

**Comment by vkurchatkin** [comment]
You need to provide type annotation for functions or class methods if you export them

**Comment by iddan** [comment]
It is a constructor, obviously it returns `this`

**Comment by vkurchatkin** [comment]
> And transactions can be inferred from being assigned to a typed property

It can, but it isn't. You have to specify it explicitly

**Comment by iddan** [comment]
Well, that's my issue

**Comment by nmote** [comment]
This is done for performance reasons. Requiring type annotations on exports allows Flow to perform type inference separately within each file, which makes it easily parallelizable.
