### ISSUE TITLE
Strange error with unions and intersections

### ISSUE THREAD

**Issue by yury** [facebook/flow#3452]
```
/* @flow */

type AType = {
  +a: number
}

type BType = {
  +b: number
} & AType
  
type CType = {
  +c: number
} & AType // <--- 1. if removed & AType here - ok

type BlaType = AType | BType | CType // <--- 2. if CType is removed from BlaType - ok

let x: BlaType = { a: 1 }
if (x.b != null) { // <--- Why Error?: property `b`. Property cannot be ...
  console.log(x.b)
}

```

[try flow](
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAKrgQLxgDeqYYA1AIYBcYAdgK4C2ARngE6oAvumz4wAIVLjKNOvR6tOvAcLAAyItLy0wmMmADC2sLN30Axku59BQjVoPBgYADwBaT2ACMAOjAAllBg-HhccABueAAmDiQGABYCBO5gcADWogYSMIwmlPHiAD6SJiXGTi4eXgBM-kFGJgEAziFhkTFgUPxwXJK5JqkZ6DB4GGAAHqw5eQayYCw+YCINABQTvjxgAISUnDAwAJTUYM5unqkA6glYYACi-D38APysOD34-NhgAAY8P-4AAofATfCyMNhsODjPhgXzw3QWOBsZpwUa+eAAc3Wm0OwlQQA)

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2969
