### ISSUE TITLE
Allows type annotation inside array destructuring, but does not check it

### ISSUE THREAD

**Issue by andy-ms** [facebook/flow#3455]
```js
const one: number = "one"; // Error
const [two: number] = ["two"]; // No error
```

Expected either a syntax error or a type error.
Related: #235.

**Comment by nmn** [comment]
I think this should be syntax error. The right way to write this would be:

```typescript
 const [two]:[number] = ["two"]; // No error
```

**Comment by vkurchatkin** [comment]
> I think this should be syntax error.

But why? There is no conflict here

**Comment by nmn** [comment]
I just feel like since this syntax won't work with Objects, adding it for Arrays just makes things more confusing.

**Comment by lll000111** [comment]
Discussion probably belongs to https://github.com/facebook/flow/issues/235

**Comment by SamChou19815** [comment]
We now error on this syntax.
