### ISSUE TITLE
Unnecessary null check required after equality comparison with known-non-null object

### ISSUE THREAD

**Issue by mstange** [facebook/flow#3456]
Sample code:

```js
// @flow

type Marker = {
  time: number,
}

function createMarker(): Marker|null {
  return { time: 4 };
}

function compareMarker(marker1: Marker|null) {
  if (marker1 !== null) {
    const marker2 = createMarker();
    if (marker1 === marker2) {
      console.log(marker1.time); // flow allows this, good.
      console.log(marker2.time); // flow complains about marker2 possibly being null
    }
  }
}
```

It would be nice if flow could figure out by itself that the access to `marker2.time` doesn't require another null check. It knows that `marker1` is of type `Marker` because `marker1` is null-checked; and it knows that `marker1` is equal to `marker2`.

**Comment by nmn** [comment]
Someone else will have to back me up on this, but this seems like an edge-case that would be super hard to actually implement and so I don't see this happening any time soon.

@mstange would love to know a reason why this is actually slowing you down.

**Comment by mstange** [comment]
It's not actually slowing me down. It just means I need to add an extra if condition, and readers of the code might be confused as to why that check is there, when it's fairly obvious that it's not needed.

If this is too much of an edge case, don't worry about it. I filed this bug because I thought it might have been an oversight that's easy to fix.

**Comment by alex-deas** [comment]
I'm torn between this; on the one hand I want type checkers to be unobtrusive and stay out of the way; however, I'm not sure if there's any need to support this type of situation as the primary cases in which I can think such code would arise is when a situation is trying to be 'too clever'

**Comment by mstange** [comment]
Here's [the actual code](https://github.com/devtools-html/perf.html/blob/6990f728369b32f66db27a9deb10a7a193dc57d6/src/content/components/IntervalMarkerOverview.js#L122) where I ran into this. Not sure if this is trying to be too clever.

**Comment by lgraziani2712** [comment]
Here is another strange behavior around null values:

```jsx
// @flow

const ONE = 1;
const MIN = 0;
const MAX = 9;

function getRandomInt(rawMin: number, max: number) {
  const min = rawMin + ONE;

  return Math.floor(Math.random() * (max - min)) + min;
}

export const randomizeActorsConfig = (statics: Array<number | null>, accesses: Array<number>) => {
  const definedRanges = accesses.map((actorPosition) => ({
    min: statics[actorPosition - ONE] !== null ? statics[actorPosition - ONE] : MIN - ONE,
    max: statics[actorPosition + ONE] !== null ? statics[actorPosition + ONE] : MAX + ONE,
  }));

  return () => (
    definedRanges.map(({ min, max }) => (getRandomInt(min, max)))
                                                       ^ null. This type is incompatible with the expected param type of
  );
};
```

Here is the link to the flow.org/try: https://goo.gl/vrpgMy

By the way, for cases like these I use my custom supress_comment: `$FlowDoNotDisturb` 😝 and a link to an issue.

**Comment by lgraziani2712** [comment]
I found another issue related to this but with Maps:

```jsx
function needObject(obj: Object) {
//                       ^ object type
  // do something
}
function MapHasABug(map: Map<string, Object>, key: string) {
  if(map.has(key)) {
    needObject(map.get(key));
//             ^ undefined. This type is incompatible with the expected param type of
  }
}
```

Here is the link to the flow.org/try: https://goo.gl/1Ge6nB

**Comment by nmn** [comment]
There's some work happening to add something like `%checks` for functions that refine types. that will help with the last case.

**Comment by johngeorgewright** [comment]
I just ran in to the same problem as @lgraziani2712.

I can see there is now documentation for `%checks`. How does this solve the problem? Use another function instead of `Map.has`?

```javascript
const hasMap = (key: string, map: Map<string, Object>): %checks =>
  map.has(key)
```
