### ISSUE TITLE
Iterator implementations are unable to satisfy Iterator interface

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#3457]
I am pretty much unable to implement to implement iterator that would satisfy flow, here is an [example code](https://flowtype.org/try/#0MYGwhgzhAEBiCWIAuBTATigJgSVWsSA9mtADxgB80A3gFDTQAOAXABTwB2jArks2AEpoAXioAjQoRAowHetAiFuaYCmYB+XOgLFyFeQAED8PDrSshdBgwxJlHaEgAW8CPIC+8jigAeSCzTyDMCEHBBINIrKqgA0TO4iji5u1tAA7i7S0KxRKiiWQdYhYREYENzIibmqAHTefhaFDPAAZtllFUg1mKH5gampzq411SiJHBUgTdZiGGAA1tMJKCAQY1YDwaHhNABuYCDcKAnC0B3I081trIys+4f5BZuptvZ7B0dxPd7MLQdrCUu0E8mxB1jBNhQdjQDmo3zUSDQRzBnk8tF8jGIEWKOxaiDwiT02RY7C4vH4QlE0AkUhkHDiJm0RDQzC0+GZegErNMHMoIioGxxETxyHQWHGKDScHxYpwPOI8hFeCwIyUeUSjPZCoYStlNUYiUY8leMOguowmFo7iAA) inlined below for convenience 

```js
class FilteredIterator <a> {
  p:(input:a) => boolean
  source:?Iterator<a>
  @@iterator() {
    return this
  }
  next() {
    const {source, p} = this
    while (source) {
      const result = source.next()
      if (result.done) {
        this.source = null
        break
      } else {
        const {value} = result
        if (p(value)) {
          return {value, done:false} 
        }
      }
    }
    return {done:true}
  }
}

export const filter = <a> (p:(input:a) => boolean, iterator:Iterator<a>):Iterator<a> => {
  const filtered = new FilteredIterator
  filtered.source = iterator
  filtered.p = p
  return filtered
}
```

Flow reports following error:

```
    return {value, done:false} 
                         ^ object literal. This type is incompatible with
    [LIB] static/v0.41.0/flowlib/core.js:531:   | { done: false, value: Yield };
                                                  ^ object type
```

**Comment by vkurchatkin** [comment]
You have to add some explicit annotations:

```js
class FilteredIterator <a> {
  p:(input:a) => boolean
  source:?Iterator<a>
  @@iterator(): $Iterator<a,void,void> { // <-- HERE
    return this
  }
  next():IteratorResult<a, void> { // <-- AND HERE
    const {source, p} = this
    while (source) {
      const result = source.next()
      if (result.done) {
        this.source = null
        break
      } else {
        const {value} = result
        if (p(value)) {
          return {value, done:false} 
        }
      }
    }
    return {done:true}
  }
```

**Comment by Gozala** [comment]
Thanks @vkurchatkin, that does indeed fixes it! Never the less isn't flow's inability to infer this is still a bug ? For the very least please consider amending error messages with suggestion to add explicit annotations.

**Comment by Gozala** [comment]
Also worth noting that if I do entype base class all subclasses still need explicit annotations or they still fail to type check.
