### ISSUE TITLE
Incorrect "Possibly null value" error

### ISSUE THREAD

**Issue by johnryan** [facebook/flow#3458]
I was wondering if there is any way to handle a scenario where there is already a null check encapsulated in a different function. A simplified example:

```
startTheCar() {
  if (this.carIsReady()){
    this.engine.start(); //error here method cannot be called on possibly null value
  }
}

carIsReady() {
  return (this.engine != null)
}
```

**Comment by nmn** [comment]
This isn't currently possible. But it's feature that is being worked on.

For now the workaround is to rely on return values instead.

```typescript
startTheCar() {
  var engine: ?Engine = this.getEngineIfReady();
  engine && engine.start();
}

getEngineIfReady(): ?Engine {
  return this.engine;
}
```
