### ISSUE TITLE
Contradiction in documentation for providing too few arguments to a function and incorrect use of "closure"

### ISSUE THREAD

**Issue by mheiber** [facebook/flow#346]
I think there may be a contradiction in the documentation for providing too few arguments to a function:
https://github.com/facebook/flow/blob/gh-pages/docs/01-functions.md#too-few-arguments

>Flow produces an error whenever a call provides too few arguments to a function. On the other hand, **too many arguments  is fine**, which is why Flow does not complain on most uses of builtin [sic] primitives like Array, whose methods are often called with closures that **take fewer parameters than prescribed**. [emphasis added]

I assume that what the author has in mind are calls to array methods like this: `[1,2,3].map(function(item){console.log(item);});` The function passed to `map` receives three arguments, but only has one parameter. This case is not one of too few arguments being provided: it's a case of too *many* being provided.

Also, I think the author meant "anonymous function" and not "closure."

**Comment by avikchaudhuri** [comment]
Can't see the contradiction. Your map call would be fine, which is consistent with what is said in the docs: too many args is fine. And too many args = fewer params.
