### ISSUE TITLE
export is sealing an un-sealed object

### ISSUE THREAD

**Issue by yonatanmn** [facebook/flow#3464]
when I have one file, dynamically adding methods works fine:
```js
// FILE1.JS
const api = {};
function testFunc(x: string){
  ...
}
api.testFunc = testFunc;
api.testFunc(890);  
// throws error as expected: 
// "number. This type is incompatible with the expected param type of string"

```
if I move `api` to other file, I get an error.
```js
// API.js
export default {};

// FILE1.JS
import api from './api';
function testFunc(x: string) {
...
}
api.testFunc = testFunc; // I get error here - "Property not found in object literal"
```

and if I add annotation
```js
// API.js
const api: Object = {}; 
export default api;

// FILE1.JS
import api from './api';
function testFunc(x: string){
  ...
}
api.testFunc = testFunc;
api.testFunc (890);  
// no error thrown
```
No more errors...

Maybe I'm missing something, it looks quite incoherent. 
 
the behaviour that I expected: dynamic non sealed objects ('empty object literal', see [here](https://flowtype.org/docs/objects.html#sealed-object-types)) will know to infer the properties as expected, whether in same file or exported. 

Hope it's not something I'm missing, quite new with Flow.

**Comment by vkurchatkin** [comment]
That's by design, objects are only sealed in the same file where they are created

**Comment by yonatanmn** [comment]
so what can i do in this case?

**Comment by nmn** [comment]
@yonatanmn You already have the answer which is to put a type annotation on the object.

You could choose to use more exact types instead of just `Object` but that depends on your use-case. Please ask on StackOverflow with further questions.
