### ISSUE TITLE
How to focus DOM Node after using ReactDOM.findDOMNode?

### ISSUE THREAD

**Issue by pbomb** [facebook/flow#3465]
After upgrading to flow 0.41.0, we're getting flow errors about calling `focus()` on the return value from `ReactDOM.findDOMNode` because the definition now states that the return value is `null | Element | Text`. After verifying it's not null, how do I correctly refine its type from `Element | Text` to `Element` so I can call `focus()` on it?

**Comment by pbomb** [comment]
Also, how would one refine from Element to HTMLElement, which is where focus() and other useful methods/properties are?

**Comment by pbomb** [comment]
Just following up, it looks like the only way to get from `React.findDOMNode` to an `HTMLElement` is by casting to any. At least, that's what the findDOMNode function in React does itself.

I assume flow is capable (although it's not yet implemented) of knowing that inside of `if (elementOrText.nodeType === 1)`, it can be refined as Element instead of Text, which would have nodeType === 3. Is that true? However, even if we can refine it to Element properly, we'd need a similar way of refining from Element to HTMLElement.

For large codebases that use findDOMNode in multiple places, it seems like the best approach would be to have a utility function that casts to any and back to HTMLElement, maybe something like this:
```
export function findHTMLElement(node: null | Element | Text): null | HTMLElement {
  if (node && node.nodeType === 1) {
    return (node: any);
  }
  return null;
}
```
Does this seem reasonable? Or do you think there is a better way of dealing with `findDOMNode`?

**Comment by echenley** [comment]
Further, our use case requires properties from [`HTMLMediaElement`](https://github.com/facebook/flow/blob/master/lib/dom.js#L2502):

```
class Audio extends Component {
  playSound() {
    ReactDOM.findDOMNode(this).play()
  }

  render() {
    return (
      <audio
        autoPlay={ false }
        src="sound.mp3"
      />
    )
  }
}
```

**Comment by nmn** [comment]
@echenley This is actually the correct behavior. There is not enough type information to know what the type of `ReactDOM.findDOMNode(this)` should be. Plus the component may or may not be mounted so it's an optional.

Do something like this:

```
playSound() {
  const el = ReactDOM.findDOMNode(this);
  el && el.play && el.play();
}
```

**Comment by echenley** [comment]
@nmn Ah, interesting, thanks. Looks like you also have to check that `typeof audioEl.play === 'function'`.

**Comment by nmn** [comment]
@echenley See updated comment. The instanceof check is good enough.

**Comment by echenley** [comment]
Excellent, thanks!

**Comment by pbomb** [comment]
Cool, thanks for providing a solution, @nmn
