### ISSUE TITLE
React incorrect props behavior

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3467]
I can't reproduce this on lowtype.org/try, but this fails locally:

```js
import React from 'react';

class View extends React.Component {
  props: {
    style: '1' | '2'
  }
};

<View style={('1': '1')}/>
```

Output:

```js
  7:     style: '1' | '2'
                      ^^^ string literal `2`. Expected string literal `1`, got `2` instead
 11: <View style={('1': '1')}/>
                        ^^^ string literal `1`
```

It behaves as if props are plain object

**Comment by vkurchatkin** [comment]
This happened because I redefined `type ReactClass` in a libdef. Still weird

**Comment by asolove** [comment]
It seems like this might be closable or might need a title/description change to reflect the specific case where you ran into it.

**Comment by vkurchatkin** [comment]
@asolove sure, this requires investigating. At the very least it is most likely to be unrelated to React.

**Comment by SamChou19815** [comment]
We now require explicit type argument for React.Component, which should fix this.
