### ISSUE TITLE
Bug with Type of Object Map Values for Exact Values

### ISSUE THREAD

**Issue by Nasafato** [facebook/flow#3469]
I'm using Flow v0.41.

So I have an Object type that functions as a map:
```js
type State = {
  [cardId: string]: Card
}
```

If I define the Card type as an exact type:
```js
type Card = {|
  id: string,
  columnId: string,
  rowId: string,
  name: string,
  visible: boolean,
|}
```
then Flow says the type of State is:

> ```
> type State = {
>     [cardId: string]: any;
> }
> ```

But if I just make Card a regular object instead of an exact object, Flow confirms its type is as expected:

> ```js
> type State = {
>     [cardId: string]: {
>         id: string;
>         columnId: string;
>         rowId: string;
>         name: string;
>         visible: boolean;
>     };
> }
> ```

**Comment by SamChou19815** [comment]
This issue is likely fixed a long time ago
