### ISSUE TITLE
CustomEvent type cannot be used with addEventListener

### ISSUE THREAD

**Issue by deecewan** [facebook/flow#3472]
I have a function that dispatches a `CustomEvent`.  I then do things based on what the `detail` is from the custom event.  Unfortunately `EventTarget#addEventListener`'s `EventHandler` only accepts an `Event`.  

Example that might make more sense:

```js
// @flow

function eventHandler(e: CustomEvent) {
  if (e.detail.body === 'Specific Text') {
    // perform a certain action
  }
}

document.addEventListener('eventType', eventHandler);

const ce = new CustomEvent('eventType', {
  detail: { body: 'Specific Text' },
});

document.dispatchEvent(ce);
```

I either get an error on my usage of `eventHandler` when I `e` is a `CustomEvent`, or an error checking `e.detail` if `e` is an `Event`.

I'll have a crack at changing this, but I've only just started using flow, so I'll probably come up short.

**Comment by nmn** [comment]
This is because of the in-built types for `document.addEventListener`.

You have a few ways of working around it.

1. You could override the types for `document.addEventListener`:
```
(document.addEventListener: Function)('eventType', eventHandler);
```

2. You can just use a ` // $FlowFixMe` comment and ignore it.

3. You use a more open-ended type for your function:
```
function eventHandler(e: mixed) {
  if (e instanceof CustomEvent){
    if (e.detail.body === 'Specific Text') {
      // perform a certain action
    }
  }
}
```

**Comment by deecewan** [comment]
I get that.  But I think that surely, if `EventHandler` can accept the `CustomEvent` (which is a subclass of `Event` that just takes a detail), then the `EventHandler` definition should take either `Event` or `CustomEvent`.

**Comment by nmn** [comment]
@deecewan I guessed I missed the part where CustomEvent is a subclass of Event. Then it might be an error to do with property variance: https://flowtype.org/blog/2016/10/04/Property-Variance.html

Still, this is something that I'll look into. Reopening.

**Comment by iddan** [comment]
Why is this closed? @nmn. `document.addEventListener()` should accept any string as event type for custom events.

**Comment by goodmind** [comment]
This can't be fixed either any string will be always custom event or just event

**Comment by doasync** [comment]
> This can't be fixed either any string will be always custom event or just event

Here is the fix (see revisions): https://gist.github.com/doasync/00fd970ce06dffc6ef9c32c5f5909d17
