### ISSUE TITLE
Unexpected error location when returning incorrect type

### ISSUE THREAD

**Issue by ajhyndman** [facebook/flow#3473]
I've tried to assemble a pretty minimal example below.

In the example, our type definition of filter isn't smart enough to know that the result we're returning is now a list of ConcreteA.  Flow thinks that our function is returning a Array<ConcreteA | ConcreteB>.  That's not ideal, but not the issue I'm trying to flag here.

I expected an error pointing to the function's return type annotation, but instead I get errors on the type keys in both of my type definitions.

```js
// @flow
type ConcreteA = {
  type: 'A';
  body: Object;
};

type ConcreteB = {
  type: 'B';
  body: Object;
};

export default function myFilter(
  parameter: Array<ConcreteA | ConcreteB>
): Array<ConcreteA> {
  return parameter.filter(listItem => listItem.type === 'A');
}

declare var input: Array<ConcreteA | ConcreteB>;

export const x = myFilter(input);

```

Output:

```bash
local_modules/ms-utils/misc/removeMe.jsx:3
  3:   type: 'A';
             ^^^ string literal `A`. Expected string literal `B`, got `A` instead
  8:   type: 'B';
             ^^^ string literal `B`

local_modules/ms-utils/misc/removeMe.jsx:8
  8:   type: 'B';
             ^^^ string literal `B`. Expected string literal `A`, got `B` instead
  3:   type: 'A';
             ^^^ string literal `A`
```

There are a couple reasons this is awkward for me:

* It's harder to figure out what I did wrong in a more complex context
* I can't use a `// $FlowIssue` comment as a workaround, because the errors are located on the type definition itself

I hope the above all makes sense.  Thanks for everyone's awesome work!

**Comment by jagreehal** [comment]
Not sure why filter doesn't work but reduce does.

```
return parameter.reduce((arr, listItem) => {
    if (listItem.type === 'A') {
      arr.push(listItem);
    }
    return arr;
}, []);
```

**Comment by ajhyndman** [comment]
Thanks, workarounds are nice.  Filter's type definition is not the issue I'm trying to flag in this issue, though.

**Comment by nmn** [comment]
Another tip is to increase the number of traces for type errors. That way, even though the order can be wrong, the obvious location usually gets marked as an error.

**Comment by ajhyndman** [comment]
Oh, I wasn't even aware of that feature!  Thanks, I expect to get some good payout from that.

**Comment by nmn** [comment]
Closing as this issue is part of just a general `improve error reporting` request.
