### ISSUE TITLE
Problem with array type validation?

### ISSUE THREAD

**Issue by Skurkify** [facebook/flow#3476]
[Live Try Flow Example](https://flowtype.org/try/#0C4TwDgpgBAKuEwBYEsB2BzKBeKBvAUFFMgCYBcUqArgLYBGEATvgL776iSzwAKTAzgHtU2PIWLlKtBowA041AEMaECv2CM06VuwD0uqAGFF-aAEZ8AY2HqokRkNQU4kPg+GjcEimdmVlqlAA5ABKIIqoQVAsANxWNsBQwCgYzvBIWqL2jnH4+kYm0ABM8ai2kIJgADaBLhBujgDaALqijdnCzXHWZYnJWvxpkBkYLVkQlTW5+QDqiCBQJIIQ-AWmUGZ2Jqt0VInG60VQAGaKyFUA-EA)
```
type TypeThing = {
  id: number
}

type TypePerson = {
  id: number,
  name: string
}

// Case 1
const person: TypePerson = { id: 1, name: 'Ryan' };
const thing: TypeThing = person;

// Case 2
const people: TypePerson[] = [person];
const things: TypeThing[] = people;

// Why does Case 1 pass but Case 2 fail?
```
Flow has no issues with Case 1, but does complain during Case 2 stating that "property name does not exist in TypeThing".

Why does Flow complain during Case 2, but not Case 1? Does type validation behave differently when Arrays are involved? Is this intended behavior?

**Comment by mwalkerwells** [comment]
Arrays are invariant: https://flowtype.org/docs/arrays.html

**Comment by mwalkerwells** [comment]
``TypePerson`` is a subclass (or a more specific type) of ``TypeThing``. Case 2 assumes that arrays are covariant.

**Comment by nmn** [comment]
If you use `$ReadOnlyArray` instead of `Array` things will work fine.

```typescript
type TypeThing = {
  id: number
}

type TypePerson = {
  id: number,
  name: string
}

// Case 1
const person: TypePerson = { id: 1, name: 'Ryan' };
const thing: TypeThing = person;

// Case 2
const people: $ReadOnlyArray<TypePerson> = [person];
const things: $ReadOnlyArray<TypeThing> = people;
```

**Comment by Skurkify** [comment]
Thanks for the great information and a solution. I appreciate it.

**Comment by hmillison** [comment]
@nmn is there a reason why things like `$ReadOnlyArray` and `$Keys` are not in the Flow documentation?

**Comment by nmn** [comment]
@hmillison Yes because the documentation is old. But it is being worked on.
