### ISSUE TITLE
no error when accessing undefined property on sealed object

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#3482]
Please consider the following example: https://flowtype.org/try/#0C4TwDgpgBAglC8UDeAoKUCGAuKA7ArgLYBGEATgDRpTE4DOwZAlrgOYoC+KKAZvrgGNgTAPa5MGMAAoWYfMBwwAlKihMeM3HOAA6ASupQBYuiIA2EHWZGtN2vUoDcaLmq3ydAEwRQAzM64UY1wGN21FHyRsAEYKGhwAcgALCDNrBI5nDEk7eScgA

Why do I get an error on accessing input.d but not when accessing input.c? I have refactored my code and renamed one of the properties and would expect problems on all checks for the old property name.

**Comment by nmn** [comment]
This is intended as reading an undefined value essentially gives you undefined. You're only logging it. If you tried to use the value as a non-null value Flow would catch it.

**Comment by hmeerlo** [comment]
@nmn Sorry but I completely disagree. The object is sealed for a reason, I know what the properties of the given object are. It can never be intentional to reference a property which is not part of my type annotation.

**Comment by jeroenwienk** [comment]
I'm having the same issue as @hmeerlo. I would expect the if statement to give me an error. I have never defined ID in my type so why would I reference it?. If I do the same check with a function then I would get an error. 

On multiple occasions I have changed some property name and every if statement that checks if the old property is defined gives no errors.

[example](https://flowtype.org/try/#0C4TwDgpgBAqgzhATlAvFA3gKClAlgEwC4oA7AVwFsAjJAGm1IEMKJi5hFcSBzTAX0yYAxgHsS7KGQSI4xAIKJEjEAB54SAHyooAbQbomLYgHIAUiIAWJY7TxEoARih96OAyWasoZkRBt3iACZnTABdAG5BADMyEiFgXDEoKK58dUQACikkYnSASiw8KKgs6QA6AEkAETyMBigAegaiqGALXDhJaSgLRk7GEihqqAB3aDA+ztxgKEZEEVj8VpFZkhE2pGTYoXqmqCoyGbHRhYAbJe4IGbWoJHmZVt6Z4Y7VyRIAazWRwbB5yEQoHqEzgcHSpSQeUiOCgu2aUi43GWAGUOIioPhfJ1uLgAG7QFhvO4iRD1UTiGbAESozg8bTZRCVKplKk0xEZKHYAQ4bC4YoZDpVCApEgQfAQxnVPK1QoASD2IwsIBOZHOQ1IEDFywxwq40EYWziCSSVKgl0pFmgiAgcFVz1GA2AwMm4IZnOcsIEmBiRsSg0FutF4raiJlmFl1uAZEQgxDdIAhCg0ORTqcoAAydOPdGJtCLQNiyJen3xP1QEFg6QS3LSMP8aKpcEGAjEBy2DxGbzmKzGZxQoA)
