### ISSUE TITLE
Can't cast map/array of subclasses to map/array of base classes

### ISSUE THREAD

**Issue by bdrobinsonbbc** [facebook/flow#3485]
When I do

```js
class A {}

class B extends A {}

const bMap: Map<string, B> = new Map()
const aMap: Map<string, A> = bMap
```

I get an error saying that `A` is incompatible with `B`. The same also seems to apply to arrays. I feel like it ought to be possible to cast in this way, since flow is happy for me to do

```js
const a: A = new B()
```

as it can recognise that `B` is a subclass of `A` and so is a valid operation.

Is this something that just hasn't been implemented yet, or is there a good reason it won't let me do this? I'm aware I could get around it by cloning the Map.

**Comment by vkurchatkin** [comment]
Yes, there is a good reason for this behaviour. [This](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)) Wikipedia article explains it pretty well.

**Comment by nmn** [comment]
@bdrobinsonbbc A short reason of why that doesn't work is because Map is mutable. This means that if you can add `A` elements to the Map from string to `A`. But an A may or may not be a B, and it would be a type error.

Making your collection type immutable (or covariant) will allow what you're trying to do.

Here's an example:
```typescript
class A {}

class B extends A {}

const bMap: $ReadOnlyArray<B> = [new B]
const aMap: $ReadOnlyArray<A> = bMap
```

This has no errors. But if you replace `$ReadOnlyArray` with the mutable `Array` you'll get familiar type errors.

Hope that helps.

**Comment by bdrobinsonbbc** [comment]
Thanks for the tip on `$ReadOnlyArray`, that's very useful. Does Flow have a `$ReadOnlyMap` for an ES6 `Map`?

**Comment by nmn** [comment]
@bdrobinsonbbc I don't think so. Currently ReadOnly versions exist for plain Arrays and Objects.

There are some other issues in Flow itself before it will make sense to make more ReadOnly types.

However, it might be possible to create a ReadOnlyMap type yourself. I'll look into it.

**Comment by bdrobinsonbbc** [comment]
That's good to know. Yeah I wondered the same thing last night and had a go at implementing it myself (taking cues from the implementation of `$ReadOnlyArray`) - this is what I ended up with. Worth a PR?

```js
declare class $ReadOnlyMap<K, +V> {
    @@iterator(): Iterator<[K, V]>;
    constructor(iterable: ?Iterable<[K, V]>): void;
    entries(): Iterator<[K, V]>;
    forEach(callbackfn: (value: V, index: K, map: $ReadOnlyMap<K, V>) => mixed, thisArg?: any): void;
    get(key: K): V | void;
    has(key: K): boolean;
    keys(): Iterator<K>;
    size: number;
    values(): Iterator<V>;
    // Multiple Indexers not yet supported
    [key: $SymbolToStringTag | $SymbolSpecies]: Function;
}

declare class Map<K, V> extends $ReadOnlyMap<K, V> {
    clear(): void;
    delete(key: K): boolean;
    forEach(callbackfn: (value: V, index: K, map: Map<K, V>) => mixed, thisArg?: any): void;
    set(key: K, value: V): Map<K, V>;
}
```

**Comment by nmn** [comment]
@bdrobinsonbbc Did you check if it works? If yes, then it's worth a PR.

**Comment by nmn** [comment]
@bdrobinsonbbc Just tried your code and it seems to work. However, Map seems to work too:

```
class Animal {
  name: string
}

class Cat extends Animal {
  breed: string
}

declare var cat: Cat;

declare var catMap: Map<string, Cat>;

var animalMap = catMap;
```

No errors.
