### ISSUE TITLE
declare class X implements Y - syntax error.

### ISSUE THREAD

**Issue by leebyron** [facebook/flow#3489]
I expected to be able to declare a class which implements an interface, but Flow is missing syntax for that.

```js
// @flow

interface Foo {
  equals(other: mixed): boolean
}

class Bar implements Foo {
  equals(other: mixed): boolean {
  	return true
  }
}

declare class Bar implements Foo { // <-- Flow thinks implements is a syntax error
  equals(other: mixed): boolean;
}
```

Check out the try demo: https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAYrLKAN6KihYCOArvtAM4AUsGAFrgFygAtigAeWACYBKQQCMK0LPjSIAvskLR8bNqABC+HKBRCADoqFZMu8pRp1GLdl14DhYyTNDzYi5dVpQAEgcLAwmHDRQDBwmLED1dUQJLE1DEjSdfUNjMwsrDBsKAIdmVk5uPhxBEXFpOQUlNABuNUQgA

**Comment by samwgoldman** [comment]
FWIW, there is no *need* to declare conforming interfaces, because Flow will structurally allow instances of Bar to appear in positions expecting Foo. However, there is a small perf optimization where we can avoid structural checks entirely when the implemented interfaces are declared, so this is worth supporting.

**Comment by miracle2k** [comment]
My expectation was that

```
interface Foo {
  equals(other: mixed): boolean
}

declare class Bar implements Foo { 
}
```

will declare a class ``Bar`` that was a method ``equals``, i.e. this syntax allows me to inject methods into the class declaration.

**Comment by alexeyraspopov** [comment]
Just got the same issue. `v0.57.3`.

```javascript
declare export class Store implements Listener {}
```

Fails with "unexpected identifier" error for `implements`.

**Comment by jedwards1211** [comment]
@samwgoldman `declare interface Bar extends Foo` would work equally well here right?
The other advantage of explicitly inheriting from `Foo` in the declaration is you don't have to redeclare all the members from `Foo`.

**Comment by micha149** [comment]
Same issue here with flow 0.61.0

```
 62: declare class Matrix4 implements Matrix {
                           ^^^^^^^^^^ Unexpected identifier
```

@miracle2k wrote:
> My expectation was that
> 
> interface Foo {
>   equals(other: mixed): boolean
> }
> 
> declare class Bar implements Foo { 
> }
> will declare a class Bar that has a method equals, i.e. this syntax allows me to inject methods into the class declaration.

Thats not what I expect. I expect an error, because your class `Bar` has no method `equals()`

**Comment by jedwards1211** [comment]
@miracle2k what language are you coming from?  I know `implements` doesn't do that in Java.

**Comment by samwgoldman** [comment]
Support added in 18da70a3cd11afb969eaeaec771ddb1ab658eae7
