### ISSUE TITLE
Type alias declarations

### ISSUE THREAD

**Issue by popham** [facebook/flow#349]
Similar to #110, but not the same.  I've got a plain old data object that I'd like to declare, e.g.

```
declare module a {
  declare type Datum = {
    segment: Buffer,
    position: number
  }
}
```

Any plans for support?

**Comment by samwgoldman** [comment]
0.10.0 has export type and import type functionality. @jeffmo Is there a corresponding declaration format? Is one planned?

**Comment by jeffmo** [comment]
I'd like to make this work, yes ('declare type' makes an exported type alias similar to what 'export type' does in real modules). I have other things higher up in the queue ATM so no plans at the moment -- but very much want to see it happen.

TBH this shouldn't be *too* difficult if anyone has some time and wants to take a stab at a PR

**Comment by ThomWright** [comment]
:+1: I also need this.

**Comment by jeffmo** [comment]
This is currently being worked on over in https://github.com/facebook/flow/pull/569 -- let's track it there
