### ISSUE TITLE
React.Component `defaultProps` not validated by flow

### ISSUE THREAD

**Issue by EvHaus** [facebook/flow#3499]
Using flow 0.41.0, with the following code:

```javascript
import React, {Component} from 'react';

export default class MyComponent extends Component {
	props: {
		someValue: string
	};

	static defaultProps = {
		someValue: 123
	};

	render () { ... }
}
```

I expected flow to alert me that `someValue` is defined as a `Number` when it should be `string`. But it does not warn me at all.

**Comment by nmn** [comment]
`$Diff` should error if the second param is not strictly a sub-object of the first param.

**Comment by mwalkerwells** [comment]
@nmn Which ``$Diff`` are you talking about? Looking at the library definition, ``props`` and ``defaultProps`` are not inter-dependent: https://github.com/facebook/flow/blob/master/lib/react.js

Also, you could make the case that a polymorphic class like this should infer that the type is ``{ someValue: 123 | string }``.

**Comment by nmn** [comment]
@mwalkerwells $Diff is used to create the prop requirements for a React Component. This way props that exist as defaultProps don't need to passed at the call-site.

Also, the types here are not inferred they are defined for `props` so inferring `{ someValue: 123 | string }` makes no sense.

**Comment by mwalkerwells** [comment]
> $Diff is used to create the prop requirements for a React Component.
Can you link to this in the React.Component library definition?

**Comment by nmn** [comment]
@mwalkerwells It's kind of in the Flow internals. But this gets close: https://github.com/facebook/flow/blob/master/lib/react.js#L97

**Comment by asolove** [comment]
There were a number of issues with the relationship of props and default props that have been fixed in Flow v0.53. 

I slightly updated the original code and [it now type-checks fine](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAETY32sDcyuAnhiqgACkwzkAvKADeiUKFLMqANWLQArlQBci3NhQA7AOaIAvr0RUAHljygAJlUjEN0fLWhlyAWX4BhZixDKkN8G1xQh3JqOlwAOkDMWBCwgB4xWAkAGkIAPllEAEgMcVJdOSKipTRVdS1dUn0jUyKLZGrcYlwUWkdnV3dMiVBpSurlNU0dUABGACYAZmL24o5DJ2xQAAoASllQDlwNbENQNIcUADdgArNzIA) in Flow v0.53.

As a result, I think this can now be closed. (/cc @calebmer)

**Comment by calebmer** [comment]
One thing worth noting is that we only check `defaultProps` when you create an element from your component. This is ok:

```js
import * as React from 'react';

class MyComponent extends React.Component<{prop: number}> {
  static defaultProps = {
    prop: 'foo',
  };
}
```

However, you get an error when you add `<MyComponent />`. This mirrors React’s runtime behavior 😊

https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugLICeAwiZAHZY+8LAA8YggCbpseGADoe4CAKEAeAN5hiYAFxw+AVxAAjLFAC+APjjq6cOKhjIYwXHAlYCyA0xgAFbXQAXhs7ezgtCF1yAggIMgAaMPN6cwZVTkV+QXgAeksaIA

**Comment by fragosti** [comment]
@calebmer I'm confused about "mirrors React's runtime behavior" being a good thing. Seems like it should be possible to check this type of thing without instantiating a component? This come up a lot if you have React component packages.
