### ISSUE TITLE
interface as a return type results in string

### ISSUE THREAD

**Issue by alexfedoseev** [facebook/flow#3501]
I want to use `Immutable.Record` to create enums, so I can catch access to the undefned keys in the editor + on CI.

It works great with the `Record` only: https://cl.ly/jWKr

But when I extend it with some methods, it works in runtime, but typedefs don't work:

```js
/* @flow */

import { Record } from 'immutable';

interface $Enum<T: {}> extends Record<T> {
  items: Function;
  fromValue: Function;
}

const createEnum = <T: {}>(items: T): $Enum<T> => {
  class Enum extends Record(items) {
    items = () => this.toArray();
    fromValue = value => this.find(item => item.value === value);
  }

  return new Enum();
};

const MyEnum = createEnum({
  A: { id: 1, value: 'a' },
  B: { id: 2, value: 'b' },
});

const A = MyEnum.get('A');
//        ^
//        string
```

For some reason flow thinks that `MyEnum` is a `string` and I can't find explanation why.

**Comment by vkurchatkin** [comment]
You have to choose a name other than `$Enum`. `$Enum` is a name of a builtin type

**Comment by alexfedoseev** [comment]
Oh, what a bummer! Thanks, now it works 👍
