### ISSUE TITLE
Index access of `Array<T>` should return type `?T` not `T`

### ISSUE THREAD

**Issue by boris-marinov** [facebook/flow#3508]
```javascript
const arr= [1, 2, 3]
const undef = arr[100]
````
In this case `undef` has type number, but it is actually undefined.

https://github.com/facebook/flow/blob/master/lib/core.js#L261

**Comment by vkurchatkin** [comment]
This would be very impractical, e. g. you'd have to check result each time in a `for` loop.

**Comment by boris-marinov** [comment]
In many cases, there is no problem, e.g. if you use `map`, `forEach` etc.

**Comment by nmn** [comment]
I actually agree with @boris-marinov on this.

**Comment by boris-marinov** [comment]
I understand that being able to typecheck existing code is your priority, but I think type safety should be an even a bigger one.

**Comment by vkurchatkin** [comment]
I generally support making things as safe as possible, but this is th exception. I guess we could propose adding safe version of array

**Comment by boris-marinov** [comment]
Not a bad idea. Maybe we can also have this for `ReadOnlyArray`?

**Comment by boris-marinov** [comment]
You cannot have safety if you have exceptions. Example: `null`.

**Comment by boris-marinov** [comment]
So is this dead? How do I propose adding a safe version of `Array`?
