### ISSUE TITLE
it doesn't work (Error initializing: Operation not permitted) & annoying so-called docs 

### ISSUE THREAD

**Issue by raould** [facebook/flow#351]
Ubuntu 14.04 lts / 32 bit / intel
flow 0.7.0
built locally from github sources
ocaml version 4.01.0

(a) http://flowtype.org/, you know, those very first docs that i would follow?! does not say i have to do "flow init" -- but apparently i do. so how about saying that up front in the docs?!

(b) when i try to copy and paste from http://flowtype.org/ i get the line #s as well. annoying.

(c) when i try to actually run just "flow" (note how this apparently doesn't match what i see in other places where i'm told to run "flow check", shesh) then i get an infinite not-really-working loop (see below).

(d) if i try "flow check" then i get "Error initializing: Operation not permitted". 

(e) ??? no profit here, that's for sure.

Flow server launched for /home/superman/Dev/FlowTest
Spawned flow server (child pid=26630)
Logs will go to /tmp/flow_superman/superman-zShomezSsupermanzSDevzSFlowTest.log
The flow server will be ready in a moment.
Flow server launched for /home/superman/Dev/FlowTest
Spawned flow server (child pid=26647)
Logs will go to /tmp/flow_superman/superman-zShomezSsupermanzSDevzSFlowTest.log
The flow server will be ready in a moment.
Error: flow server is busy
Flow server launched for /home/superman/Dev/FlowTest
Spawned flow server (child pid=26664)
Logs will go to /tmp/flow_superman/superman-zShomezSsupermanzSDevzSFlowTest.log
The flow server will be ready in a moment.
Flow server launched for /home/superman/Dev/FlowTest
Spawned flow server (child pid=26681)
Logs will go to /tmp/flow_superman/superman-zShomezSsupermanzSDevzSFlowTest.log
The flow server will be ready in a moment.

**Comment by mroch** [comment]
for (e), check out the log file (/tmp/flow_superman/superman-zShomezSsupermanzSDevzSFlowTest.log). it's probably the same issue as (d) causing the server to not start so it keeps trying.

**Comment by samwgoldman** [comment]
@raould are you still having issues?

**Comment by pwlmaciejewski** [comment]
Hey guys! I have the same issue on my Linux Mint 17.1 Cinnamon 32-bit:

```
~/f/e/02_TypeAnnotations (master) $ flow --version
Flow, a static type checker for JavaScript, version 0.10.0
```

```
~/f/e/02_TypeAnnotations (master) $ flow check
Error initializing: Operation not permitted
```

```
~/f/e/02_TypeAnnotations (master) $ flow
Flow server launched for /home/fragphace/flow/examples/02_TypeAnnotations
Spawned flow server (child pid=22031)
Logs will go to /tmp/flow/zShomezSfragphacezSflowzSexampleszS02_TypeAnnotations.log
The flow server will be ready in a moment.
Flow server launched for /home/fragphace/flow/examples/02_TypeAnnotations
Spawned flow server (child pid=22057)
Logs will go to /tmp/flow/zShomezSfragphacezSflowzSexampleszS02_TypeAnnotations.log
The flow server will be ready in a moment.
Error: flow server is busy
Flow server launched for /home/fragphace/flow/examples/02_TypeAnnotations
Spawned flow server (child pid=22084)
Logs will go to /tmp/flow/zShomezSfragphacezSflowzSexampleszS02_TypeAnnotations.log
The flow server will be ready in a moment.
^Cfish: Job 1, 'flow' terminated by signal SIGINT (Quit request from job control (^C))
```

On the other hand, `flow init` seems to be working fine.
Ah, btw. logs: 

```
~/f/e/02_TypeAnnotations (master) $ cat /tmp/flow/zShomezSfragphacezSflowzSexampleszS02_TypeAnnotations.log
Error initializing: Operation not permitted
```

**Comment by sagotch** [comment]
Same probleme here, with `Ubuntu 14.04.2 LTS - 32 bits` and `flow 0.11.0`.

Could the 32-bits arch be the problem? `flow` is supposed to work with Linux 64 bits, but there is no information about Linux 32 bits...

**Comment by samwgoldman** [comment]
Documentation is something we know we need to improve, but the [getting started guide](http://flowtype.org/docs/new-project.html) does direct you to run `flow init` as a first step.

Regarding the 32-bit incompatibility, that's already being tracked in #270.
