### ISSUE TITLE
Flow cannot find .flowconfig in Windows looking in Samba share

### ISSUE THREAD

**Issue by jslauthor** [facebook/flow#3510]
Hi all,

My setup: Windows 10 Host (Sublime IDE Win64), Ubuntu VirtualBox Guest sharing my node project via Samba. For whatever reason, the Windows Flow binary is having an issue seeing `.flowconfig` when connected to the samba share. Below is the app root which contains the `.flowconfig`:

![image](https://cloud.githubusercontent.com/assets/224192/23880349/54ca6bd8-0810-11e7-85d8-d02fbe18ca0c.png)

I made sure to `hide dot file = false` in my `smb.conf`. `.flowconfig` displays when listing the directory files in cmd and Powershell. Any ideas? My only hope at this point is to run a flow server _inside_ Ubuntu and write a proxy so SublimeLinter-Flow can connect to it somehow.

![image](https://cloud.githubusercontent.com/assets/224192/23880394/b256c13e-0810-11e7-93d4-0acbd8284772.png)

**Comment by nmn** [comment]
Not a proper fix, but running Flow inside Ubuntu and using Nuclide will work for you.

**Comment by jslauthor** [comment]
Thanks @nmn, but I'm trying to avoid dev'ing inside VirtualBox as Windows performs much, much better. Looking now to tunnel flow via SSH and trick SublimeLinter-flow into thinking it's the standard command line binary.

**Comment by jslauthor** [comment]
It turns out there's a bug with `flow.exe` where it cannot read `.flowconfig` if the app's root is at the root of a mapped drive since it includes the drive letter. Nesting the app's folder fixes it.

**Comment by SamChou19815** [comment]
It might have been fixed a while ago
