### ISSUE TITLE
Merging two types and polymorphism

### ISSUE THREAD

**Issue by gajus** [facebook/flow#3513]
Maybe I don't understand how polymorphism works, but I am expecting this to enable me to merge two objects of the same type:

```js
// @flow

export default <StateType>(state: StateType, change: StateType): StateType => {
  if (typeof state !== 'object' && state !== null) {
    throw new Error('Unexpected state.');
  }

  return {
    ...state,
    ...change
  };
};

```

Instead, I am getting an error:

```
8:   return {            ^ object literal. Expected object instead of
10:     ...change           ^ StateType

```

https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1ACYqQCGArtPgDwDKuJuKAKgJ4YoB8AFAM72MAuUHQbM2KADSgAxgAsSAOwDmKISMat2ASjX8x7UAF4OoAN6JQoAJaRQXXONi2+o0AEJDh0AHJYAIwArFGlcb1AAMnDQF0Z3T1AFCmgtMwtLUFxZbAQElHhQAFFsbOwubwBVBXR2EJQCaL0AOm8tAG40gF9kS2wUXDJsBVT00EaxmMk0yzHGuUUVTvaO9qA

**Comment by nmn** [comment]
You just have to constrain your generic to always be an Object.

```typescript
// @flow

export default <StateType: Object>(state: StateType, change: StateType): StateType => {
  if (typeof state !== 'object' && state !== null) {
    throw new Error('Unexpected state.');
  }

  return {
    ...state,
    ...change
  };
};
```

**Comment by gajus** [comment]
Doesn't `typeof state !== 'object'` do the same in this case?

**Comment by nmn** [comment]
Actually no. Because typeof an Array is also `object`.
