### ISSUE TITLE
Flowjs with magic curried methods

### ISSUE THREAD

**Issue by mhaddon** [facebook/flow#3515]
VueX has a feature where you can have a bunch of methods that access information in the store.

The methods can look like this (example without flowjs for simplicity): 

```
const getters = {
    exampleGetter(state) {
        return state.item;
    }
}
```

You can  then call it like this.
getters.exampleGetter
Note there is no (). VueX automagically processes the result for me.

Here is another example:

```
const getters = {
    exampleGetter(state) {
        return state.item;
    },
    compareExampleGetter: (getters) => (value) => {
        return value === getters.exampleGetter;
    } 
}
```

Now i can call this by doing: getters.compareExampleGetter("test"), and it will tell me if it matches the response from exampleGetter.

But no matter what i do. FlowJS is completely unable to understand the getters object.

I cannot do (getters: getters), as that is referencing getters before it is initialised. 

I have tried declaring an interface that lists all the possible methods and doing (getters: getterinterface), but this doesnt work because of this:

if i do:
```

declare interface getterInterface {
    exampleGetter: string;
    compareExampleGetter(value: string): boolean;
}

const getters: getterInterface = {
    exampleGetter(state: stateInterface) {
        return state.item;
    },
    compareExampleGetter: (getters: getterInterface) => (value: string): boolean => {
        return value === getters.exampleGetter;
    } 
}

```
i get an error like this:
undefined (too few arguments, expected default/rest parameters)

**Comment by mwalkerwells** [comment]
If you can narrow this down to a specific question, I'd love to help!

**Comment by mhaddon** [comment]
The specific question is how I can tell flow that the method is automagically curried.

I want to be able to tell flow that:

```
exampleGetter(state: stateInterface) {
        return state.item;
    },
```

Is a variable that returns a string, not a method.

Or that 

```
compareExampleGetter: (getters: getterInterface) => (value: string): boolean => {
        return value === getters.exampleGetter;
    } 
```

Is a method that returns a boolean, not a method that returns a function.

**Comment by mwalkerwells** [comment]
I'm unfamiliar with VueX & am not sure what how ``stateInterface`` is modeled, but for exampleGetter, I'd model it like:
````js
exampleGetter<U: { item: string }>(state: T) {
        return state.item;
    },
````

**Comment by SamChou19815** [comment]
This should be solved by `$ObjMap`
