### ISSUE TITLE
Technical documentation generation?

### ISSUE THREAD

**Issue by balupton** [facebook/flow#352]
I see a lot about flow supporting jsdoc annotations (#3), but what about documentation being generated from flow types (so the other way around).

For instance, it would be nice if instead of doing:

``` javascript
/**
 * Do something
 * @param {String} foo The first argument
 * @param {Any} bar The second argument
 * @return {Array} The thing that is returned
 */
function (foo, bar) {}
```

We could do the following using JSDoc:

``` javascript
/**
 * Do something
 * @param foo The first argument
 * @param bar The second argument
 * @return The thing that is returned
 */
function (foo: string, bar: any): array {}
```

Or using [tomdoc](http://tomdoc.org):

``` javascript
// Public: Do something
//
// foo - The first argument
// bar - The second argument
//
// The thing that is returned
function (foo: string, bar: any): array {}
```

There's a discussion over at docchi here about their support: https://github.com/daliwali/docchi/issues/2

Would be cool to have this issue to talk about implementations in other documentation generators.

**Comment by pcj** [comment]
I'm interesting in working on this kind of tool.  Never used OCaml.  

Core flow developers: where in the source is a good starting point to examine the AST after parsing?  For example, in closure compiler one can implement a CompilerPass and walk the AST with bottom or top-down visitor pattern.  Is there a similar location in the flow code for that?  

Also, closure compiler has core classes Node, JSDocInfo, JSType, etc.  Are there similar objects in flow?

Also, while the /*:: */ style syntax is interesting for the communication of human -> machine (comments provide information to the compiler), does it support human -> human?  jsdoc provides both (for example, explaining the meaning/usage of a parameter, not just its type.

**Comment by samwgoldman** [comment]
Not a core developer, but the AST is defined in [src/parser/spider_monkey_ast.ml](https://github.com/facebook/flow/blob/master/src/parser/spider_monkey_ast.ml) and the code in [src/typing/type_inference_js.ml](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml) walks to AST and creates flows which are processed in [src/typing/flow_js.ml](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml).

**Comment by samwgoldman** [comment]
Oh, and [the parser tools](https://github.com/facebook/flow/tree/master/src/parser/tools) will probably help a lot, too.

**Comment by pcj** [comment]
Great!  Just read https://ocaml.org/learn/tutorials/basics.html, nicely written.

**Comment by cameron-martin** [comment]
Yes, generating JSDoc annotations from flow annotations would be really useful, since flow annotations are typchecked and make use of type inference.

**Comment by balupton** [comment]
For what it's worth, I moved to https://github.com/documentationjs/documentation for generating my docs. Which supports flow type annotations for generating docs

However, it doesn't support flow type comments, which is what I use:
https://github.com/documentationjs/documentation/issues/306

**Comment by cameron-martin** [comment]
I tried using this, but it generates blank documentation. I am running `documentation build src/speedball.js` on [this file][speedball], but it just returns an empty array, `[]`.

I should probably file an issue, unless I'm using it wrong.

[speedball]: https://github.com/cameron-martin/speedball/blob/master/src/speedball.js

**Comment by balupton** [comment]
@cameron-martin I use `documentation build -f html -o ./docs -g --shallow ./source/**.js`

https://github.com/bevry/base/blob/24a50e71b7e9e607eb9c922470c688e0b126237e/package.json#L64

**Comment by cameron-martin** [comment]
I get the same thing unfortunately. I've [filed a bug report][bug].

[bug]: https://github.com/documentationjs/documentation/issues/424

**Comment by freddi301** [comment]
try ```documentation.js build --document-exported``` do not want type any jsdoc comments

**Comment by Kalmuraee** [comment]
I would love to see that

**Comment by balupton** [comment]
Closing as there are solutions above
