### ISSUE TITLE
Flow fails checking against imported interface, but not when declared locally

### ISSUE THREAD

**Issue by billschaller** [facebook/flow#3520]
I have a generic interface Provider<T: Configuration> referenced as a constructor parameter for a generic class ProviderCollection<T: Configuration>. When Provider is declared in the same file as ProviderCollection, flow correctly checks a union type of subtypes of Configuration as the input to a method on ProviderCollection. When I import the Provider type from another module, flow throws errors about members of the union of Configuration types.

Gist: https://gist.github.com/billschaller/2942ba31edb134cc94715f137ce6ac20

CC: @gabelevi

**Comment by mosesoak** [comment]
I've repro'd this – an imported interface does not function. I see:

- incorrectly setting a variable typed to the interface does not produce an error
- incorrectly setting a property of the interface-typed object does not produce an error

This means flow is failing to do basic type-checking in our current projects – please prioritize!

**Comment by SamChou19815** [comment]
All these import issues should be fixed after types-first
