### ISSUE TITLE
Flowtype hangs for linux starting from v.0.39.0

### ISSUE THREAD

**Issue by sepo-one** [facebook/flow#3526]
Sorry if a dup.

STR:

update flow-bin to any version starting from 0.39.0
run flow for the project
When comes to local[inference] after about 5 mins system resources are all eaten by flow process.

ENV:
This was reproduced on linux (ubuntu 16) and mac.

Project config:
We're having quite some node_modules but exclude them and are using flow-typed stubs.

Any other details should i supply ?

**Comment by philikon** [comment]
I suspect this is related to the multiflow change regarding rest args introduced in 0.39. I'm seeing something similar. See #3370 and #3443 for a very minimal reproduction.

If you're using `...args` without type declarations anywhere in your code, try adding them and see if the problem goes away. If that's it, we should dedupe this to #3370 / #3443 and escalate to @gabelevi.

**Comment by sepo-one** [comment]
0.45.0, problem still there :(

**Comment by mrkev** [comment]
Is the problem still present?

**Comment by sepo-one** [comment]
no, not anymore
