### ISSUE TITLE
InstanceT poly type constraints are unresolved, causing type-at-pos to return incomplete info

### ISSUE THREAD

**Issue by billschaller** [facebook/flow#3527]
Constructor calls result in InstanceT with unresolved constraints, making a call to type-at-pos to return just the class name as the type, rather than a type app, as you might expect.

Is there some reason InstanceT has unresolved type args in this case? I would think this is pretty clear...

Example:
plain-construct.js:
```js
// @flow
declare class test<T> {
  constructor(param: T): void;
}

const a = new test(1);
```

Observed:
```
billschalle-mbp:flow-fiddle billschaller$ flow type-at-pos plain-construct.js 6 7
test
/Users/billschaller/Desktop/tracery/flow-fiddle/plain-construct.js:6:7,6:7
...
```

Expected:
```
billschalle-mbp:flow-fiddle billschaller$ flow type-at-pos plain-construct.js 6 7
test<number>
/Users/billschaller/Desktop/tracery/flow-fiddle/plain-construct.js:6:7,6:7
...
```

With a static constructor or any function that is explicitly annotated as returning a TypeAppT, type-at-pos works fine.

static-construct.js:
```js
// @flow
declare class test<T> {
  static <U>(param: U): test<U>;
}

const a = test(1);
```

Observed as expected:
```billschalle-mbp:flow-fiddle billschaller$ flow type-at-pos static-construct.js 6 7
test<number>
/Users/billschaller/Desktop/tracery/flow-fiddle/static-construct.js:6:7,6:7
```

**Comment by SamChou19815** [comment]
It now shows the right type
