### ISSUE TITLE
No good way to exactly type props and protect from typos

### ISSUE THREAD

**Issue by niieani** [facebook/flow#3531]
After being struck by Flow not complaining about a number of typos I've had (I've not used exact types), I've been trying to design a system which would allow one to catch those, while at the same time enforcing the required properties. 

Using React, one often reuses properties, pushing them down the tree, so it makes sense to me to break those properties down into smaller types, which are then merged. The problem is, you cannot use `$Exact` on an intersection type, nor can you intersect two `$Exact` types. `$Shape` _almost_ solves the problem, but it has the annoying side effect (for this use case, at least) of making every property optional.

If we had `$Shape` which kept the required properties, but only made sure that you don't add any _extra_ properties, this problem would be solved.

Here's [a little exploration](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM4CCYAvGAN7F4COArgJZMAmYAXGACM4cGHgCGAOwC+mXARJlyAIVoMyGdnAliYAfj6DhoyTNTBgYBOxgwwO+Emw445XmYtOCAMXbbbdBQpqADIiUgoldHMwcjgAWwIoMWtfAHMwDDxyDHIwHDFycgAaGPiCfMK0sCTrN2jPMB8-VQASAFEADzEAYwwAHkCqMFDBpQA+KIs8ADc8YiwMAAsqmphXdwy5Rt8dVs6e-sHKMeGwdq7egfDlCY3usQxuxazN5xKBVgwwOLEAaxeAORMNicPBcAFgdSaPx1DxbJq7OgtADKizE+CuihCYUU40mkIkMCwljExIwcDAqTwXyW7Fy5MscGIv3enzAs3mYG68Rwog6dgkPC4dN5pNyc1IxFyvgyz0spAk6VF3ReAAotK8sgBKWGa7bNJGo9F4TFBU6jE4ja7Y0b45EACQA8gBVAAyABFGpQAJKutyiL44a4AdXYS0dOAwABVcBT+Aj-AxgRxuPwMMRWHgSk44GmM1nIZHoTo85mZAG8iGw4s4J8I9HYwYE6pGCwU2DSwWc53y9TK4pQ+HIwA5OAAJRYTZ2ifoUK0JYy+d7garS1rGHro4nzCnBoYpmiDpdHqIlGRyP9faDA+r9d3iKTbdBXE7JTnMMXZdQFevFEHNbrSN7xnZNnx7VAgA) of the problem and the many solutions that occurred to me:

```ts
/* @flow */

type PropsA = {required : boolean}
type PropsB = {optional? : boolean}

// will allow typos:
// type Final = PropsA & PropsB

// some failing tests pass, some passing fail:
// type Final = $Exact<PropsA & PropsB>

// everything fails:
// type Final = $Exact<PropsA> & $Exact<PropsB>

// catches typo, but makes 'required' optional:
// type Final = $Shape<PropsA & PropsB>

// only way to get this to work, but very complex and displays errors in the wrong places (on types):
// type Final = $Shape<PropsA & PropsB> & PropsA & PropsB

// SHOULD FAIL:
let propsWithOptTypo : Final = {required: true, typo: true, optional: true}
let propsWithoutOptTypo : Final = {required: true, typo: true}
let propsWithOptNoReq : Final = {optional: true}
let propsWithoutOptNoReq : Final = {}

// SHOULD PASS:
let propsWithOpt : Final = {required: true, optional: true}
let propsWithoutOpt : Final = {required: true}
```

**Comment by niieani** [comment]
Using the new object type spread https://github.com/facebook/flow/commit/ad443dc92879ae21705d4c61b942ba2f8ad61e4d I've managed to come up with this:

```ts
type PropsA = $Exact<{required : boolean}>
type PropsB = $Exact<{optional? : boolean}>
type Final = $Exact<{...PropsA, ...PropsB}>
```

But I'm curious, why does each part of the spread have to also be `$Exact`? For some reason, just doing spread, makes all properties optional, but spreading an `$Exact` does not. :)

**Comment by vkurchatkin** [comment]
Closing, see https://github.com/facebook/flow/issues/3534
