### ISSUE TITLE
Can I override types?

### ISSUE THREAD

**Issue by philiiiiiipp** [facebook/flow#3532]
I quite often send data over a REST api which causes e.g. Date objects to be converted to strings. Currently I handle this like so:
```
type A = { many more properties }  
type A_server = { time: Date } & A;  
type A_client = { time: string } & A;
```
Is there a way to override types?

**Comment by DanielRosenwasser** [comment]
Because our issue tracker has as much traffic as it does, StackOverflow may be a better venue in the future.

Since you're here though, I won't turn you away. 😄 Consider a pattern such as the following

```ts
export interface ABase {
  time: Data | string;
  // stuff
}

export interface AServer extends ABase {
  time: Date;
}

export interface AClient extends ABase {
  time: string;
}
```

**Comment by nmn** [comment]
You could always do: `{time: Date | string}`;

I don't think you can override types. That wouldn't work with the model where any type can depend on any type anywhere in the file.
