### ISSUE TITLE
CoffeeScript now works with FlowType

### ISSUE THREAD

**Issue by eduveks** [facebook/flow#354]
I've did some experiences to code in CoffeeScript and use FlowType to validate my code.

Until now only coffee-to-typescript helps me to make this work:
https://github.com/palantir/coffeescript-to-typescript

My code in CoffeeScript:
```
### @flow ###
a = 1
foo1 = (y) -> y * 10
foo1('abc')
foo2 = (x, y) ->
  x * y is 5
foo2('Hello', '42')
class Bob
  calculate: (x) ->
    x * x
b = new Bob()
b.calculate('4abc')
```
Now run:
```
$ coffee-to-typescript -cma index.coffee
```
Compile the final JavaScript code:
```
$ tsc index.ts
```
Now Flow works like a charm:
```
$ flow
```
>index.js:7:6,10: string
>This type is incompatible with
>  index.js:5:12,17: number
>
>index.js:11:6,12: string
>This type is incompatible with
>  index.js:9:12,16: number

>index.js:11:15,18: string
>This type is incompatible with
>  index.js:9:12,16: number
>
>index.js:21:13,18: string
>This type is incompatible with
>  index.js:16:16,20: number
>
>Found 4 errors

Finally a miracle! :D

**Comment by samwgoldman** [comment]
This is cool! You should write a blog post about it—I'm not sure many people are going to learn the technique browsing the issues. In any event, this isn't quite the best forum & it seems like there is no issue or feature request here, so I'm going to close this out.
