### ISSUE TITLE
union types not type checking properly when used with Objects and primitives

### ISSUE THREAD

**Issue by haasDev** [facebook/flow#3540]
I currently have the following type aliases on a react Component.

```
type OptionObjectType = {
  text: string,
  value: string
};

type OptionType = string | OptionObjectType;
```

when I pass in an array of strings to the component I get the following error.

`React element object type. this type is incompatible ^^^^^^string.`

I expect that it would recognize that it can either be object or string.

**Comment by asolove** [comment]
This code seems to work for me:

```js
type OptionObjectType = {
  text: string,
  value: string
};

type OptionType = string | OptionObjectType;

let options: Array<OptionType> = ["styff", "things"]
```

So I would guess there is something else going on in the surrounding code causing Flow to guess a different type?

This happened a while ago so I doubt you still have the code handy. I'm going to close this issue, but if you see the same thing again and can share the surroundings I'm happy to reopen and discuss.
