### ISSUE TITLE
Flow should only report errors from my code - I don't care about node_modules warnings

### ISSUE THREAD

**Issue by jaredly** [facebook/flow#3542]
It's super weird to me that flow feels the need to tell me about errors in required modules.
Currently it's **super** anti-user, and I've talked to several people who tried flow, but gave up after seeing a ton of errors in node_modules libraries -- why should they care about that?
I can think of two possible modes of operation:
1) suppress all errors in node_modules by default, and only show them if an option is set
2) just **don't check** node_modules files. If they're flow typed, then all exported functions will have signatures, and flow should just accept those signatures as correct (again, maybe unless a flag is set?)

I really just want to write code, and I'm more likely to just dump flow entirely than try to get some module to fix their flow types.

**Comment by jesseschalken** [comment]
See #869
