### ISSUE TITLE
Use of $Keys anywhere in a type hierarchy makes type-at-pos return <unknown>

### ISSUE THREAD

**Issue by billschaller** [facebook/flow#3545]
As the title states, using $Keys anywhere in the hierarchy of a type causes type-at-pos on any instance of that type to return \<unknown\>.

Repro:
type-at-pos-repro.js
```js
// @flow
const A = 'A';
const B = 'B';
const C = 'C';
const types = {
  A,
  B,
  C,
};
//export type ValidType = 'A' | 'B' | 'C'; // Swapping this line for the next causes type-at-pos to work right.
export type ValidType = $Keys<typeof types>;
export type TypedObject = {
  type: ValidType,
  trueOrFalse: boolean,
};

const a = {type: 'A', trueOrFalse: false};
(a: TypedObject)
```

```
billschalle-mbp:flow-fiddle billschaller$ flow type-at-pos --strip-root type-at-pos-repro.js 17 7
(unknown)
type-at-pos-repro.js:17:7,17:7

See the following locations:
type-at-pos-repro.js:17:11-41:
object literal
```

Type-at-pos is a pretty important part of the nuclide-flow workflow, so this seems pretty impactful.

**Comment by billschaller** [comment]
Note: This type-checks OK, and if you try to cast an invalid shape as `TypedObject`, it does error.

**Comment by Aldredcz** [comment]
:+1: Also noticed. It's a pity, because utility types are very powerful, but this issue degrades the whole experience.

**Comment by darichey** [comment]
This works now.
