### ISSUE TITLE
Support $Keys<T> on generic types

### ISSUE THREAD

**Issue by bgdavidx** [facebook/flow#3546]
This code fails:

```
class Test<T> {

  f: { [k:$Keys<T>]: number }

  set(key: $Keys<T>) {
    this.f[key] = 1
  }

}
```

with the following error:

```
assignment of computed property/element
Computed property/element cannot be assigned on
T
```

I expected it to be able to typecheck the key parameter passed to the set function to validate that it actually is a key of T.

**Comment by rsolomon** [comment]
Flow doesn't know if `T` is of type `Object`. If you inform it via bounded polymorphism that `T` is guaranteed to be an Object, then you should be able to get what you need:

```
class Test<T: {}> {

  f: { [k:$Keys<T>]: number }

  set(key: $Keys<T>) {
    this.f[key] = 1
  }

}
```

**Comment by vkurchatkin** [comment]
This doesn't really work, though

**Comment by vkurchatkin** [comment]
You should never use `Object` as upper bound, it is unsafe

**Comment by nmn** [comment]
It does work though:
https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXAHkIC4wB5AIwCtiMyA+MAb3TDClpcwAbQDW1ACQBpYgE9cVdgF1aAOwCuAWwbEATmAC+vMLmJkAFKLm1pchYXYBKbqj58yACwCWuAHRQxOSUwAF4wAEZXQ1QjVAATVhxdYjAAN2x9MloScgoubAAHAphiWnJdL1UAcwAaMAZsGBgysgrqg3YAbnQyX1MLAHJC4uIBxx6+s3MBhqaxif7p3DioedReqF9hku71-y3lqG6gA

**Comment by vkurchatkin** [comment]
Works from outside, but not from inside:

```js
class Test<T: Object> {

  f: { [k:$Keys<T>]: number }

  set(key: $Keys<T>) {
    this.f['foo'] = 1 // no error
  }
}

```

**Comment by nmn** [comment]
Fair enough. Should this be treated as a bug then?

**Comment by nmn** [comment]
Fair enough. Should this be treated as a bug then?

**Comment by vkurchatkin** [comment]
Not really, `{}` instead of `Object` also fixes the problem, but without such issue

**Comment by nmn** [comment]
@vkurchatkin I didn't know that. My bad then. I edited the comment.
