### ISSUE TITLE
Inconsistent handling of `$Shape`

### ISSUE THREAD

**Issue by matthewowen** [facebook/flow#3550]
Here's an example of the issue I'm running into:

```js
// @flow

type MyLovelyType = {
  foo: string,
  bar: number,
};

function takesAShape(shape: $Shape<MyLovelyType>) {
  takeMyLovelyInstance(shape); // Does not error but should, value is not necessarily a full instance.
  takeANumber(shape.foo); // Errors: string. This type is incompatible with the expected param type of number
  takeANumber(shape.bar); // Does not error, but should: value could be null
}

function takeANumber(number: number) {
  return;
};

function takeMyLovelyInstance(myLovelyInstance: MyLovelyType) {
  return;
}

takesAShape({foo: 1}); // Errors: number. This type is incompatible with string
```

Given that signatures which use `$Shape` correctly check that the types of provided key-value pairs, and admit the possibility of nulls, I'd expect that usages of objects declared as `$Shape` would also admit the possibility of their properties being null.

There's some lack of clarity about whether `$` prefixed methods are public or not. If they're not public, is there a better way to express "the types of the properties on this object must meet the definition of this type, but fields may be omitted"?

**Comment by jcready** [comment]
Does replacing `$Shape<MyLovelyType>` with `$Rest<MyLovelyType, {}>` work for you?

**Comment by bradennapier** [comment]
You can also try a trick liek `$Shape<{ ...MyType }>` which I have found useful in a few circmustances (although largely when handling opaque types and wanting to make them not opaque).

**Comment by gkz** [comment]
Try using `$Partial` instead: https://flow.org/en/docs/types/utilities/#toc-partial

It errors on all the places you specified above.
