### ISSUE TITLE
Cannot type React HoC that injects multiple arbitrary (generic-typed) props

### ISSUE THREAD

**Issue by rsolomon** [facebook/flow#3551]
This is related to #3246 , but I wanted to shift the conversation away from why exactly `$Diff` doesn't work as expected, and onto how we can properly type a React HoC that allows for the injection of more than one generic props object.

A pared down, failing example case that follows the examples found in the [documentation](https://flowtype.org/docs/react.html#higher-order-components):

```
import React from 'react';

declare function injectArbitraryObjects<Props, C: React$Component<*, Props, *>, ObjA, ObjB>(
  Komponent: Class<C>,
  objA: ObjA,
  objB: ObjB,
): Class<React$Component<void, $Diff<Props, ObjA & ObjB>, void>>;

class FirstClass extends React.Component {
 props: {
   foo: boolean,
   bar: number,
   baz: string,
   bing: 'bong',
 };
}

const NewComponent = injectArbitraryObjects(FirstClass, { foo: true }, { bar: 5 });

<NewComponent baz="test" bing="bong" />
```

Depending on the order of the union provided to `$Diff`, this will fail with one of the 2 following errors:

```
12: props: {            ^ property `bar`. Property not found in
22: <NewComponent baz="test" bing="bong" />    ^ props of React element `NewComponent`
```

or

```
12:  props: {            ^ property `foo`. Property not found in
22: <NewComponent baz="test" bing="bong" />    ^ props of React element `NewComponent`
```

I wouldn't be surprised if this issue stems from a misunderstanding of what `$Diff` really is under the hood. I'm both interested in learning if that is the case, and also what possible solution there might be to solve this relatively common problem.

**Comment by nmn** [comment]
This works:

```typescript
declare function injectArbitraryObjects<Props, C: React$Component<*, Props, *>, ObjA: Object, ObjB: Object>(
  Komponent: Class<C>,
  objA: ObjA,
  objB: ObjB,
): Class<React$Component<void, $Diff<$Diff<Props, ObjA>, ObjB>, void>>;
```

So, I'm guessing there is something wrong with using an intersection type as the second argument for `$Diff` which does make some sense.

Think that `$Diff<$Diff<Props, ObjA>, ObjB>` and $Diff<Props, {...ObjA, ...ObjB}>` should do the same thing. But the second of the two doesn't work right now.

**Comment by rsolomon** [comment]
Wow, you know when you look at something so long that you can't even see that a solution is right in front of you?

The nested `$Diff`, while not ideal, is absolutely a great workaround for now. Thanks for the workaround! Should I leave this open, since it does appear that there is a Flow bug here?

**Comment by asolove** [comment]
There is already a separate issue abut Diff and type object spread, so I'm going to close this as the specific problem has a workaround and the general issue is discussed elsewhere.
