### ISSUE TITLE
regex String .match flow type wrong

### ISSUE THREAD

**Issue by derektli** [facebook/flow#3554]
Currently it's defined as `?Array<string>` for return type.
However, the returned object is something like
`["12:12a", "a", index: 0, input: "12:12a"]`
https://github.com/facebook/flow/blob/v0.41.0/lib/core.js#L286

**Comment by SanichKotikov** [comment]
Hi. Is there any way to override this in local project?

**Comment by samwgoldman** [comment]
`String.prototype.match` will return `null` if there is no match. For example, `"abc".match(/foo/)` evaluates to `null`.

**Comment by gabelevi** [comment]
@samwgoldman - this is the array extending thing we discussed last week.

Someone tried to improve it in https://github.com/facebook/flow/commit/9611080b787711a392b8d5548241ecb4ed784e6b but I had to revert in https://github.com/facebook/flow/commit/3107fb3394cce82abd3c964e992d1178da33fb2d 😢

**Comment by SanichKotikov** [comment]
I suppose it must be something like this:

```ts
declare class RegExpMatchArray extends Array<string> {
    index?: number;
    input?: string;
}
```

and

```ts
match(regexp: string | RegExp): RegExpMatchArray | null;
```

**Comment by samwgoldman** [comment]
oh, I misunderstood the original post. sorry about that.

**Comment by derektli** [comment]
so maybe re-open this issue? 
thanks @samwgoldman!

**Comment by julienw** [comment]
I'd use:
 ```
declare class RegExpMatchArray extends Array<string> {
    index: number;
    input: string;
}
```

and

```
match(needle: string | RegExp): Array<String> | RegExpMatchArray | null;
```

and for `RegExp.prototype`:
```
exec(haystack: string): RegExpMatchArray | null;
```

**Comment by qm3ster** [comment]
A common usecase is to check that a match result is not null, and then use array destructuring to get the capture groups, like:
```js
lines.map(x => x.match(regex:RegExp))
    .filter(x => x !== null)
    .map(func:([string, string, string])=>({a: string, b: number, c: boolean})))
```
This causes a collision between `Array<string>` and some tuple of `[string,...,string]` sort.
How can I solve this without casting through any? Only by writing typechecks for each string even though the entire match either succeeded or failed?

**Comment by julienw** [comment]
@sm3ster your fundamental issue is that Flow doesn't understand properly the `filter` step and so doesn't rule out null results. [See here](https://flow.org/try/#0G4QwTgBANglgdgUwM4QLwQNoQORIC5jwDmAjNgDQ76FxEBM2EAugNwBQbsiSAdALYgADgAoAHmgB8EUfxB4AxgAthAemoqAlBrYRdEHgDMYUPAjBjJ07Xv0CRwjCEoAjSvKYbLwgN5OIriHkAXy0gA)

I believe this is another issue than this one.

**Comment by qm3ster** [comment]
@julienw, I already refactored the filter+map into a reduce (ew tho).
The issue is with the signature of `func`:
If I say it takes an `Array<string>` (which `string#match(RegExp)` currently claims to output) I am be accused of unsafe array index access;
But if I declare it as any specific tuple it is incompatible with an `Array<string>`

Both are silly, but understandable since flow doesn't understand the structure of `RegExp`s, which is what dictates the size of the tuple: 
```
string.match(regexpWithNoCaptureGroups): null | [string]
string.match(regexpWith1CaptureGroup):   null | [string, string]
string.match(regexpWith2CaptureGroups):  null | [string, string, string]
string.match(regexpWith3CaptureGroups):  null | [string, string, string, string]
// etc
```

Me, I need a better way to cast from arrays to tuples.

I understand the issue I am commenting in is also about the named properties `index` and `input`, but considering that unlike JS itself flow introduces Tuple types, `Array<string>` might not be a good return type even with extra properties.

**Comment by julienw** [comment]
I'm surprised, as from my testing I thought Flow let's you do whatever you want when converting from string arrays to string tuples. [See this for example](https://flow.org/try/#0G4QwTgBANglgdgUwM4C4IEExhATwDxIAuY8A5gHwQC8EA2hAORElykCMDANI82QEwMIAXQDcAKDGhItENwBG3AMZDq0eMnFjFAezhJtUBADoo20gAoQJhK0IALAJTideg8dMW5124+e79hiZm5orepPZOQA).

**Comment by qm3ster** [comment]
You're right, I can't recreate this anymore today. I will delete the comments.

**Comment by akleiber** [comment]
Hm now I get back `undefined` :-( Why would that be `undefined`? https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBnABxkPwElsAVAJ0KoFN8ywAKQ7CzPgBc5fC2wBzAJQiAgkyYBDAJ4AeMmL4SAfGADeqMGFwkNYTe05gAvGD4D8AOgC2i-LgAW3YI70BGABoAZgBfYGl0I0IoHgsYDi5rJLBsTBgYKX1DI3MPJkQUtiQAUQU4Jm4AA1xFbGw4fHIqGjAAEj17QRC7bHw4cxZLMkqpbJDIsCYOTCZSOITUEKA

**Comment by madbence** [comment]
`?T` means `T | null | undefined`, you only handled the `null` case in your example (ie. use `==` instead of `===` to fix it).

**Comment by michaelhogg** [comment]
Also see:

* Duplicate issue #2450 – Native String#match declaration incorrect
* PR #3007 – Fixes String#match and RegExp#exec declarations
* PR #3359 – Add new lib def for String#match() result

**Comment by KevinGrandon** [comment]
Seems like the landscape has changed a bit in the last year. Opened a PR to try something like this: https://github.com/facebook/flow/pull/6790
