### ISSUE TITLE
Non-trivial but still simple case of instantiated value considered as "undefined"

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3556]
The following code admittedly isn't the absolutely most simple case, which would be accessing a value inside an `if ` that ensures it exists. However, it still is pretty simple, and adding another `if` around the second expression seems highly wasteful to me. I know Flow is supposed to at least cover the trivial case only, but this, where I make sure there is a value before accessing it, seems like a common enough pattern?

Note: This code is 100% synchronous, I understand why the same pattern with async. function access is not supported.

I realize covering this is much more complicated than that most simple case already mentioned, but apart from adding a `//$FlowFixMe` comment, or adding a second and obviously useless `if` around the access, what other options are there? I think Flow being able to recognize the pattern would be the best option.

```javascript
// @flow
'use strict';

const handlers: Map<string, Map<Function, Array<*>>> = new Map();

if (!handlers.has('type')) {
    handlers.set('type', new Map());
}

handlers
.get('type')
.set(() => {}, [1,2,3]);
```

Flow output:

```
test.js:10
 10: handlers
     ^ call of method `set`. Method cannot be called on possibly undefined value
 10: handlers
     ^ undefined
```

**Comment by lll000111** [comment]
Okay, for the record, I'm undecided. I "fixed" it by rewriting the code to have a different flow and structure:

```javascript
// @flow
'use strict';

const handlers: Map<string, Map<Function, Array<*>>> = new Map();

let handler = handlers.get(type);

if (!handler) {
    handler = new Map();
    handlers.set(type, handler);
}

handler.set(() => {}, [1,2,3]);
```

Yes, all those little issues can be worked around, that's obvious. The less I have to code for the type-tool the better though. So maybe this ticket isn't the highest priority, but if at some point more and more thus far unsupported patterns would work that would be nice....

**Comment by SamChou19815** [comment]
We no longer supports existential types, so this issue is moot.
