### ISSUE TITLE
Object spread causes unknown properties to be ignored

### ISSUE THREAD

**Issue by Naddiseo** [facebook/flow#3557]
I'm probably missing something here, but here is a scenario that I think flow should detect, but doesn't:

```js
// @flow

type Ret = {|
    prop: string,
|};

function fn({ data }): Ret {
  return {
    // this property is obviously not a member of `Ret`
    invalid: 'world',
    ...data
  };
}

```
https://flowtype.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AJSyqALygDeAPoqNaBgE6wYBcoAzinQJYB2A5gDSJyAXwDcySAFduAYxSdY3UJG4AKUqAAmAQxTbQwgJQt8hUlVB0CkukvM1QIUCgAWnVrQbY66UO9CwAEYAbgqSrNBooNywhPoAtljxgVh0AZCgAAammRbUPMHa0JyaLADk8LB00Jplgg4AdE06ehZiiMKIQA

**Comment by SamChou19815** [comment]
Now we require annotation on data
