### ISSUE TITLE
Q: How can I tell Flow that a function returns a type (one of many disjoint union types)?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3560]
I have thought about this and tried many things for many weeks, on and off.

My problem is that I use disjoint union types - and I have *a lot* of them, not just two. I save (Javascript) objects in storage that all look similar: 

```javascript
{
    type: 'TypeString',
    data: {<different properties depending on type>}
}
```

So `type` is the type identifying string.

The problem: I have only one function that reads them from storage - so that function returns one 20 different types.

Now I don't want to have the same type checking code everywhere I load an object. But I don't know how I can get that code into the `getObject` function itself! I would add a string parameter for the `obj.type` type-switch property to check against, but how would I connect that with the return type of the function? How would I be able to tell Flow that the function returns a concrete type now?

The function how I imagine it:

```javascript
const getObjectAsObject = function (fileName: string, type?: string): Promise<ObjectTypesUnion> {
    return getObjectAsString(fileName)
    .then((s: string) => {
        const obj: ObjectTypesUnion = MicrodataToObject.convert(s);

        if (!type || obj.type === type) {
            return obj;
        } else {
            throw new Error(`Wrong type: expected ${type}, got ${obj.type}`);
        }
    });
};
```

I know this doesn't work, I declare the returned parameter as of the type of the entire union. But how can I do otherwise? I just don't see a way except with lots of very wasteful code! But this whole thing in seems to me based on a common generic problem and not at all uniquely my problem.

A function potentially returning many types, but depending on a parameter returning a concrete type. Only that in the case of disjoint unions, or actually in any case where I get an object from storage, or even more generically where I create a type without having that same type in the input list, I cannot use the usual "generics" syntax, which as far as I can see is 100% dependent on having the exact desired type 
in the parameters! Or how would I use generics here? I have a string as input, which is used to select the type from the union list. I don't see a way with generics either.

So that I can assign the object I get from that function to a variable of the concrete type instead of the union type. After all, the check of the type switch property was made!

```javascript
// GrantObj is part of the union ObjectTypesUnion
const grantObj: GrantObj = getObjectAsObject(hash, 'Grant');
```

**Comment by mwalkerwells** [comment]
Didn't have time to digest your entire post, but based on your code example, I think this is what you're looking for:

````js
type DataType = 'type1' | 'type2'

type ObjectTypesUnion<Data: {}> = {
  type: DataType,
  data: Data,
}

declare var getObjectAsString: string => Promise<string>
declare var MicrodataToObject: { convert: (string) => ObjectTypesUnion<*> }

const getObjectAsObject = function (fileName: string, type?: DataType): Promise<ObjectTypesUnion<*>> {
  return getObjectAsString(fileName)
    .then(stringValue => {
  
      const obj = MicrodataToObject.convert(stringValue)

      if (!type || obj.type === type) {
        return obj;
      } else {
        throw new Error(`Wrong type: expected ${type}, got ${obj.type}`);
      }
    });
};
````

https://flowtype.org/try/#0C4TwDgpgBAIghsOAVc0C8UDkpIEZNQA+WOEATJgFCWlQDyARgFYQDGwKkAzgKoB2ASwD2fADzxEALigBvAL4A+KBhmUoUUtInJUASAA0aqABMEcLWcNzqxtgBs4AJ2gA3J1ADmEYIxbsAglwAysCOAnwe0lyh4R7KSgAKjkIAtgJcEKLRYREKlLasDs5Qbo5QALICrMmmiEhCvmzA0jJQrCIuEI7NUAAU2bEAlPH0zE2cELyCIqIAVErWlO180Z7ejQFcG8DKUABmAK587MJ8fXsCdhAAcnApEFExEfoaqAD8FnWog9JJqemZbYTKanOYKJSqdTOYAHRxnLw+MabEI5Dy9C5XW73QZGdQAOmAAAsIHx+k8PAA1OB2A7oCFGXHqNoiVZCZi7SrVIS1ZANJHAPHLTrdMmoqk0iA4xnqAR7PoAQlohGIbKYBNQyjQGFIw0hTP10NhZ1VAG5pVA5FAIHYMrJzeoickAO5QPgQF0AUUcyUcvQABgB1ZIRV6QaQQAAekHYEGMUAAJDJSHIXh4hDtE6r1ZA5H7Bmb9eprPq5PnKHITUA

**Comment by lll000111** [comment]
@mwalkerwells 

Thanks! Not sure it works like that though. Two questions:

1) How would I use this? Assign a result from the function to a variable with only one concrete type?
Something like

    const type2Result: Promise<ObjectTypesUnion<type2>> = getObjectAsObject('filename', 'type2');

(This example is obviously wrong).

2) The "data" object has different properties. Example:

```javascript
export type AccessObj = {|
    type: 'Access',
    data: {
        object: ReferenceObj,
        grant?: Array<ReferenceObj>
    }
|};

export type ChumObj = {|
    type: 'Chum',
    data: {
        name: string,
        person: [string, string],
        instance: [string, string],
        password: [string, string],
        host: [string, string],
        port: [number, number],
        atob?: Array<LinkObj>,
        btoa?: Array<LinkObj>
    }
|};

export type GrantObj = {|
    type: 'Grant',
    data: {
        accessIsGrantedTo: Array<ReferenceObj>
    }
|};

...(etc.)
```

The whole reason I want to have concrete types is so that when I have one those properties get checked. I don't see how I get this into the example?

Here is what I had previously, where I indeed did have the "data" part as the parameter, and it caused me nothing but grieve and since the 0.42 update nothing but errors (worked previously):

```javascript
export type OneObject<T: OneObjectTypes> = {|
    type: OneObjectTypeNames,
    data: T
|};

export type AccessT = {|
    object: OneObject<Reference>,
    grant?: Array<OneObject<Reference>>
|};

...(etc.)
```

Then I'd use it like this:

```javascript
const grantObjs: OneObject<Grant>[] = await Promise.all(
    Array.from(grantHashes).map(StorageUnversionedObjects.getObjectAsObject)
);
```

But that is no longer possible since the latest Flow update since the `getObjectAsObject` since the function is defined as

```javascript
module.exports.getObjectAsObject = function (hash: string): Promise<OneObject<*>> {
    return getObjectAsString(hash)
    .then(MicrodataToObject.convert);
};
```

Without a parameter - but I *did* try this with a type parameter and it blew up all over the place, so I was glad that Flow accepted the above. Until now.

**Comment by jesseschalken** [comment]
It's probably not as concise as you'd like, but you can do the type check on one line like this:

```js

const getObjectAsObject = function (fileName: string): Promise<ObjectTypesUnion> {
    return getObjectAsString(fileName).then(s => MicrodataToObject.convert(s));
};

function nope<T>(msg: string = 'not gooood'): T {
  throw new Error(msg);
}

const grantObj: GrantObj = getObjectAsObject(hash).then(x => x.type === 'Grant' ? x : nope());
```

And possibly extract `const assertGrant = x => x.type === 'Grant' ? x : nope()` for reuse.

**Comment by lll000111** [comment]
Thanks, I managed to implement it, using a disjoint union type and some generics for meta-types (with the concrete instances of the union as parameter). I even found two or three errors in the code.
