### ISSUE TITLE
Catch access undefined property on sealed objects

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#3562]
Since #3482 has been closed without any further comment, I would like to know how to catch reading non-existent properties on sealed objects. See this example:

https://flowtype.org/try/#0C4TwDgpgBAglC8UDeAoKUCGAuKA7ArgLYBGEATgDRpTE4DOwZAlrgOYoC+KKAZvrgGNgTAPa5MGMAAoWYfMBwwAlKihMeM3HOAA6ASupQBYuiIA2EHWZGtN2vUoDcaLmq3ydAEwRQAzM64UY1wGN21FHyRsAEYKGhwAcgALCDNrBI5nDEk7eScgA

How would we catch the obvious error of reading ```input.c``` on the sealed object which has no property c? It can never be intentional to read the property, so it must be an error.

**Comment by hmeerlo** [comment]
Ok then let's start a bit more generic discussion: 

**is the sole purpose of flowtype to catch runtime errors, or is its purpose to improve the overall quality of Javascript code?**

Please enlighten me, because this problem has bitten me in the ass so often now that I'm questioning whether the effort of adding flowtype definitions is justified by what it gives back to me.

This gives no errors:
```
type A = {
  a: number
}

function aap(input: A){
  if(input.a.wtf === 1){
    console.log("Que pasa?");
  }
}
```

**Comment by hmeerlo** [comment]
Is there really nobody with an opinion on this? If Flow would have supported this case it would have saved me countless hours of debugging.

**Comment by nmn** [comment]
The behavior you want used to be the default. But it was decided that you should be able to check for unknown keys on an object in conditionals. That's the behavior you're seeing now. I don't see any problem here.

Also, I'm not exactly sure what your problem is exactly.

**Comment by hmeerlo** [comment]
@nmn What is the purpose of supplying the type A in the example above then? I expected the ```input``` to be a sealed object. And there should absolutely be no use-case for checking unknown keys on a sealed object, there is no way of justifying that in my opinion. I really would like to know a single use-case for somebody who needs the current behavior so I can revise my opinion if needed.

Could the previous default behavior be made optional?

**Comment by SamChou19815** [comment]
This now correctly errors
