### ISSUE TITLE
Flow config in package.json.

### ISSUE THREAD

**Issue by strctr** [facebook/flow#3569]
Add ability to define flow config inside `package.json`.

**Comment by anton-kabysh** [comment]
IMHO, this is important to follow best JS development practices, even if tool written in other language than JS. The other request is to replace OCaml regex with regular JS regex to avoid confusion when have to configure `.flowconfig`.

**Comment by trevordmiller** [comment]
I would also like to see this. I'm able to put other configs (babel, eslint, etc.) in package.json and prefer that over lots of config files in the project root.

**Comment by damianobarbati** [comment]
+1

**Comment by 0xdevalias** [comment]
For reference/easier findability, these are the `flowconfig` related issues/suggestions I found that would bring it in line with other tools like `eslint`, `babel`, `webpack`, etc:

- https://github.com/facebook/flow/issues/4115 : What about `.flowconfig.js`
https://github.com/facebook/flow/issues/153 : `.flowconfig` should use json
- https://github.com/facebook/flow/issues/238 : `.flowconfig` should recursively consider other `.flowconfig` files
- https://github.com/facebook/flow/issues/3569 : Flow config in `package.json`
