### ISSUE TITLE
Incorrect Event type for XMLHttpRequest.onload

### ISSUE THREAD

**Issue by danvk** [facebook/flow#357]
In [bom.js][], the `onload` event of `XMLHttpRequest` is declared as:

```
declare class XMLHttpRequest extends EventTarget {
  onload: (ev: Event) => any;
}
```

According to the [XHR spec][spec], the event parameter should have type `ProgressEvent`.

In most browsers the argument to the `load` event does, indeed have `lengthComputible` and `total` properties, but Flow will complain if you try to access them or typecast the parameter.

[bom.js]: https://github.com/facebook/flow/blob/master/lib/bom.js#L158
[spec]: https://xhr.spec.whatwg.org/#events

**Comment by thejameskyle** [comment]
Looks like this has been fixed https://github.com/facebook/flow/blob/d1fce29bca605cced3cdd9bb6a8efec6b8cdf61f/lib/bom.js#L292
