### ISSUE TITLE
Trouble typechecking Props with React

### ISSUE THREAD

**Issue by fandy** [facebook/flow#3571]
I expected Flow to pick up on `React.ReactNode` as a type which I can typecheck with. Why doesn't this work?

```
// @flow

import * as React from 'react'

import styles from './Node.css'

export default class Node extends React.PureComponent {
	props: {
		children?: React.ReactNode
	}

	render() {
		return (
			<div className={styles.Node}>
				{this.props.children}
			</div>
		)
	}
}
```

<img width="618" alt="screen shot 2017-03-26 at 5 36 57 pm" src="https://cloud.githubusercontent.com/assets/19108762/24335416/e8a2a98a-124a-11e7-83fc-76cec63362e8.png">

**Comment by omaroskars** [comment]
Have you tried React$Element<*> ?

**Comment by nmn** [comment]
you need to use `React.Element<any>` or `React$Element<any>`.

**Comment by fandy** [comment]
I'm getting a 
```
[flow] [flow] property `children` (Property not found in props of React element `ContextBar` See also: React element `ContextBar`)
```
