### ISSUE TITLE
Feature Request: Object type spread onto classes

### ISSUE THREAD

**Issue by aldendaniels** [facebook/flow#3572]
The latest release of flow supports spreading object types:

```javascript
type Type1 = {a: number};
type Type2 = {...Type1, b: number};
```

If we could do the same for classes, the following would be possible:

```javascript
type Data = {a: number};

class MyClass {
  ...Data,
  constructor(data: Data) {
    Object.assign(this, data);
  }
}
```

This is a common pattern at my company and I expect elsewhere

**Comment by vkurchatkin** [comment]
Object spread doesn't do what you think it does. It doesn't just copy properties, but it implements a type of a result of object spread operation. In that light what you propose makes little sense

**Comment by aldendaniels** [comment]
@vkurchatkin I see, thanks for clarifying - closing.

I was hoping that the new spread feature would solve https://github.com/facebook/flow/issues/3211, but it makes sense that you want to limit this to correctly model the behavior of the JS spread operator.
