### ISSUE TITLE
Required module not found 

### ISSUE THREAD

**Issue by ikzjfr0** [facebook/flow#3573]
My project is organized in the following way

```
.flowconfig app
app/inventory/date-actions
app/example/index.js 
```

In index.js file, I can see an error "Required module not found", if i do like this 

`import setStartDateTo from 'app/inventory/date-actions';`

I know, if I use relative path like the way below, it seems to be fine. 

`import a from '../inventory/date-actions';`

The first kind of import way exists widely in my project, so obviously I don't want to change them and hope  the .flowconfig file can deal with the problem.

The potential solution seems to use “module.name_mapper”. But really don't know how to write its regex in Flow?

Thanks

**Comment by wgao19** [comment]
```
module.name_mapper='^app\/\(.*\)$' -> '<PROJECT_ROOT>/app/\1'
```
