### ISSUE TITLE
ref: property not found

### ISSUE THREAD

**Issue by pvinis** [facebook/flow#3575]
hello. i have a very simple react native component, and i assign a ref with `ref={r => this.label = r}`. then i also have a function where inside i do things to `this.label`.

now flow complains that property label is not found.

**Comment by nmn** [comment]
Add a type def for `label`.

**Comment by samwgoldman** [comment]
Yeah, what @nmn said. Without more information it's hard to say what's going wrong. Feel free to re-open with a repro case.

**Comment by pvinis** [comment]
so like `﻿﻿ref={r => this.label: string = r}`? where do i set the type? and what type is a ref?

**Comment by mech** [comment]
Do we do it like this?

```js
class Login extends Component {
  props: Props
  email: HTMLInputElement
  password: HTMLInputElement

  render() {
    <input type="email" placeholder="Email" ref={(input) => { this.email = input }} />
    <input type="password" placeholder="Password" ref={(input) => { this.password = input }} />
  }
}
```

**Comment by pvinis** [comment]
ah cool. i will try it and report back. thanks.

**Comment by robquesada** [comment]
Is think that solution is only possible when using React classes, is there a chance of doing this in stateless functional components?

```
function Login = ({ email, password }) => (
  <input type="email" placeholder="Email" ref={(input) => { this.email = input }} />
  <input type="password" placeholder="Password" ref={(input) => { this.password = input }} />
)
```

The above example will trigger `property 'email'. Property not found in ^^^^ global object`
