### ISSUE TITLE
Flow check --all: Infinite run

### ISSUE THREAD

**Issue by omaroskars** [facebook/flow#3576]
I recently noticed that flow was consuming all of my memory and running indefinitely.

I ended up adding `/* @flow */` comment to all my js files and running `flow check` trying to find a bug in my code but in ran successfully

I then changed back to running `flow check --all` which ran indefinitely and consumed all of my memory.

My project is build with react + webpack and I'm currently using flow 0.42.0 but I also ran into this problem on 0.34.0.

~~I'm running flow on a Windows 10 machine but my co-worker seems to have no problem on a Mac machine~~

The problem exists on both Windows and Mac machines

**Comment by steida** [comment]
The same for .flowconfig

**Comment by samwgoldman** [comment]
@omaroskars Your coworker can use `flow check --all` on the same repo and get results? That is, the only variable is Windows vs. Mac?

**Comment by gingermusketeer** [comment]
Seem to be having a similar problem with a react+webpack project I am working on. After running for a short amount of time it looks like the main flow process is using a lot of RAM. Not sure if that is expected.
![screen shot 2017-03-31 at 1 55 37 pm](https://cloud.githubusercontent.com/assets/1177034/24549695/da1de9dc-161a-11e7-820a-c3846e7dcd38.png)

Let me know if I can provide any more info.

**Comment by omaroskars** [comment]
@samwgoldman no he also encounters this problem now.

@gingermusketeer Im also working on a react + webpack project.

**Comment by ksmth** [comment]
For me the same behaviour is happening for `flow check` and `flow check --show-all-errors`.

**Comment by jsg2021** [comment]
I'm hitting this as well. I don't want to add the pragma to all my files...so I set all=true in the config... my machine started to die... 😅   I then added node_modules to ignore and it completes, but I feel like I lose something (plus modules can't be resolved...)

**Comment by ADagen** [comment]
> The problem exists on both Windows and Mac machines

Same on Ubuntu@17.04 (nodejs@9.2.0, flow@0.59.0)

**Comment by JCMais** [comment]
Same issue here, process starts consuming enormous amounts of memory, and keeps running forever.

Just `flow check` works correctly.

**Comment by SamChou19815** [comment]
This issue was likely fixed a while ago.
