### ISSUE TITLE
Support for single-line flotate comment syntax?

### ISSUE THREAD

**Issue by af** [facebook/flow#358]
Hi, I was excited to read that [flotate syntax is now supported by Flow](http://flowtype.org/blog/2015/02/20/Flow-Comments.html). However I'm unable to get one of flotate's examples working with Flow 0.7. From the [flotate README](https://github.com/jareware/flotate):

``` javascript
/* @flow */
/*: (x: string, y: number): boolean */
function foo(x, y) {
    return x.length * y === 5;
}
foo('Hello', 42);
```

I tried this with and without changing the comment prefix in the second line to `/**:` (as described in the Flow blogpost linked above). With the Flow-style comment prefix I get the following error:

```
/Users/aaron/code/flow-tests/test.js:2:16,16: Unexpected token ,

Found 1 error
```

Is this style of flotate comment syntax supported?

**Comment by ianobermiller** [comment]
I don't think the single line declaration above the function is supported, only inline declarations:

```js
/* @flow */
function foo(x /*: string*/, y /*: number*/) /*: boolean*/ {
    return x.length * y === 5;
}
foo('Hello', 42);

**Comment by af** [comment]
@ianobermiller ok that explains things! Is adding support for this under consideration at all? IMO it's a cleaner approach for those of us who don't want to go for the full-blown transpiled flow syntax.

**Comment by ianobermiller** [comment]
I agree that it's nicer, all the slashes and asterisks really wear on your
after a while! Only issue with the single line syntax is that you can't use
it on anonymous functions, whereas the inline syntax should still work.
But, with Flow's inference, you rarely need to add typing to anonymous or
fat-arrows.

I

**Comment by NoumanSaleem** [comment]
Would prefer this syntax as well. +1

**Comment by Zolmeister** [comment]
+1

**Comment by corykrug** [comment]
I really want to use flow, but the current comment style style is fairly hard on the eyes. Would love to see something like @af's example which was part of the original flotate syntax:

        /* @flow */
        /*: (x: string, y: number): boolean */
        function foo(x, y) {
            return x.length * y === 5;
        }
        foo('Hello', 42);

**Comment by ianobermiller** [comment]
@corykrug why not use normal annotations and then Babel to strip them?

**Comment by samwgoldman** [comment]
You can even use a [babel plugin](https://github.com/babel-plugins/babel-plugin-flow-comments) to translate builtin annotations to javascript comments, so you can have the best of both worlds!

**Comment by jdelStrother** [comment]
For me, using regular flow syntax and then stripping doesn't work because
we have a number of tools that can't parse files containing
flow-annotations (eg eslint)

**Comment by ianobermiller** [comment]
@jdelStrother eslint works fine when you use the `babel-eslint` parser

**Comment by avikchaudhuri** [comment]
cc @gabelevi

**Comment by mattferrin** [comment]
If this is done, and I hope it is, I would suggest a slight modification to @af's syntax.
```js
/* @flow */
function foo(x, y) {
/*: (x: string, y: number): boolean */
    return x.length * y === 5;
}
foo('Hello', 42);
```

I wouldn't do this, except maybe as afterthought sugar:
```js
function foo(x, y) {
/*: (string number) boolean */
    return x.length * y === 5;
}
foo('Hello', 42);
```
Because it might be nice/handy to know your comment is literally drop in replacement code.


(The target benefit of my suggestion being that it's easier to add to inline or first class functions.)

**Comment by toastal** [comment]
+1… I was going to use flow from a project seeing that flotate was pulled in, but the current comment option is ugly and make the code less clear and not concise--especially compared to other languages with type signatures / Hindley-Milner type annotations.

**Comment by paulyoung** [comment]
I've been working on something that relates to this. I might have something to share soon.

**Comment by ngduc** [comment]
+1
I'm so happy to see Flow adopted Flotate syntax
but it's sad to see Flow does not support this nice inline syntax:
```
/* @flow */
/*: (x: string, y: number): boolean */
function foo(x, y) {}
```

**Comment by cullophid** [comment]
👍

**Comment by justmiller** [comment]
👍

**Comment by rickmed** [comment]
+1

**Comment by Gaafar** [comment]
Is there any progress on this request? It will make life much easier for server side development as it can work without any build system. 

Can someone from the maintainers please provide a high level view of how this can be implemented and the estimated effort so maybe someone else can start working on it?

**Comment by iclanzan** [comment]
Right now I am annotating functions like this:

```js
type Foo = string => number
const foo: Foo = x => x.length
```

It would be much cleaner (and easier since I don’t have to come up with names for every function type) to do it like this:

```js
foo: string => number
const foo = x => x.length
```

**Comment by zhaoyao91** [comment]
I would suggest define this syntax as meaning of `define the following name as this type`, so the usage is extremely expanded. For example:

```
/*: string */
const name = 'Bob'

/*: (a: number, b: number) => number */
function add(a, b) {
  return a + b
}

// this define a context or namespace so the helper type will not leak out to the file scope
// note the last line or last definition always mean `define the following name as this type`
/*:
type Options = {
  id: string,
  years: number
}

type Person = {
  name: string,
  age: number
}

(Options) => Person
*/
function growPerson(options) {
  const person = findPersonById(options.id)
  person.age += options.year
  return person
}
```

Note I user `=>` instead of `:` mentioned above to indicate return type because Flow already has definition of [function type](https://flow.org/en/docs/types/functions/#toc-function-types).

By this way, we can write really clean plain js code by separating the type definition from the code implementation while keep not Invading the original es syntax so we don't need any compilation.

**Comment by zapolnoch** [comment]
Maybe we can adapt [declare function syntax](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-global-function) for our needs? For example like this:
```js
/*:: function foo (x: string, y: number): boolean */
function foo (x, y) {
    return x.length * y === 5;
}
```
The absence of the ``declare`` keyword will mean that the function is not global.

**Comment by SamChou19815** [comment]
We are unlikely to support for comment syntax, since we already have a lot of issues getting them printed correctly in prettier.
