### ISSUE TITLE
[docs] vscode-flow extension link point to 404

### ISSUE THREAD

**Issue by stunaz** [facebook/flow#3584]
from this page: https://flow.org/en/docs/editors/vscode/

`vscode-flow` extension link points to 404

**Comment by samwgoldman** [comment]
Thanks! Looks like that link should point here: https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode

**Comment by stunaz** [comment]
Not really, that's the official Facebook link. Looks like it was meant to something which is no longer available

**Comment by mroch** [comment]
https://github.com/rtorr/vscode-flow

should delete the link, i guess. wonder why @rtorr deprecated it?

**Comment by rtorr** [comment]
I deprecated it so we would have less of a community split/time to maintain.

**Comment by rtorr** [comment]
https://github.com/facebook/flow/pull/3626
