### ISSUE TITLE
Little error in docs

### ISSUE THREAD

**Issue by volosovich** [facebook/flow#3588]
Hello
Please check possible error in page https://flowtype.org/en/docs/install/
When you switch from "yarn" to "npm" and back, need to change "prepublish" - line
From
`"prepublish": "yarn run build"` (when yarn selected)
to
`"prepublish": "npm run build" `(when npm selected)
and back

PS Sorry, I don't understand how change your code on this page and send pull request.

**Comment by gabro** [comment]
@volosovich I gave it a try in https://github.com/facebook/flow/pull/3594
