### ISSUE TITLE
import type X hides "X is not defined" errors

### ISSUE THREAD

**Issue by danvk** [facebook/flow#359]
The following pair of files should produce an error:

```javascript
// point.js
/** @flow */
class Point {}; module.exports = Point;

// test.js
/**@flow*/
import type * as Point from './point';

function f(p: Point) {
  return new Point();  // <--- XXX
}
```

because `Point` is used directly, whereas only its type was imported.

Interestingly, referencing `Point` outside of a function _does_ cause an error:

```javascript
/**@flow*/
import type * as Point from './point';

var p = new Point();  // identifier Point, Unknown global name
```

**Comment by danvk** [comment]
(I'm on flow 0.6.0)

**Comment by gabelevi** [comment]
Yeah, this is a real live bug.

```JavaScript
/**
 * @flow
 */

import type * as Point from 'Gabe';

Point;  // Flow notices this error

function f() {
  Point;  // Flow misses this error
}
```

**Comment by jeffmo** [comment]
Found the issue! Luckily it's fairly simple -- should have the fix ready to go out with our deploy tomorrow

**Comment by danvk** [comment]
Did the fix not make it into today's cut? I'm still seeing the same behavior as before with flow 0.9.0.

**Comment by jeffmo** [comment]
Hmm, no it went out today: https://github.com/facebook/flow/commit/838bda42c6fa2596f87f2086e66ca6e56683a8ca#diff-3d51302de71cbe8aaafc879282ca9884R23

**Comment by danvk** [comment]
Nevermind, I'm seeing it now. Sorry for the false alarm.

**Comment by jeffmo** [comment]
phew!
