### ISSUE TITLE
if-tests for optional fields allow invalid fields

### ISSUE THREAD

**Issue by gabor** [facebook/flow#3591]
```
type T = {
  name: ?string,
};

const t:T = {
  name: 'x',
};

if(t.name2) { // this does not fail
  console.log(42);
}

const q = t.name2; // this does fail
```

i'd like to get an error when i access an invalid-field, even in if-tests.
but seeing this behavior, i am guessing, that  the if-tests are a special construct for flowtype, and it says my object has an extra attribute?

anyway, what is the correct way to do this? i must do the if-test, because the name-field is optional. but if i do the if-test, then flowtype will not warn me if i do a typo in the field-name. not in the test, and not inside the if-branch.

i know i can do this:
```
type Exact<T> = T & $Shape<T>;

const t:Exact<T> = {
  name: 'x',
};

if(t.name2) { // it now fails as i wanted
  console.log(42);
}
```
and now it fails as i expected...but ... is this the recommended approach?
should i start to use this construct everywhere?
and if the answer is yes, why isn't this the default behavior? :)

i'd like to use flowtype the 'idiomatic' way, and i wonder if that dollar-shape-magic-thing is really the idiomatic way to handle such problems.

**Comment by madbence** [comment]
funny, but `type Exact<T> = T & T` triggers the same behavior :smile_cat:, there is definitely an inconsistency (you can access missing properties of an object, but you are not allowed to do the same in case of intersection types)

**Comment by samwgoldman** [comment]
This is by design. We used to be stricter here, but @gabelevi convinced us all that this behavior was better.

**Comment by nmn** [comment]
I agree that this is good. Flow by default allows extra keys on object types. (unless you use exact types)

With that in mind, it only makes sense that we should be able to look for extra keys on objects that don't explicitly have them typed.

**Comment by vkurchatkin** [comment]
> With that in mind, it only makes sense that we should be able to look for extra keys on objects that don't explicitly have them typed.

If that's the case, then we should be able to access extra keys in all other contexts. It's unclear why it's permitted only in conditions.

**Comment by madbence** [comment]
> Flow by default allows extra keys on object types. (unless you use exact types)

```js
type T = {| name: ?string |};

const t: T = { name: 'x' };

if (t.name2) {
  console.log(42);
}
```

this should fail then? (or you mean _writing_ to extra keys?)

**Comment by gabor** [comment]
@samwgoldman ok, i understand. what is the idiomatic way to handle optional attributes?

**Comment by nmn** [comment]
@vkurchatkin In a way, I think extra keys should be allowed everywhere. But they should not have a non-void type until it is tested for. perhaps something like `?mixed`.

**Comment by vkurchatkin** [comment]
Could be just `mixed`. But I disagree in general, I think this has no use and is a constant source of bugs.

**Comment by gabor** [comment]
ping?

**Comment by gabelevi** [comment]
This behavior was finally changed in 0.68 😁 

https://medium.com/flow-type/new-flow-errors-on-unknown-property-access-in-conditionals-461da66ea10
