### ISSUE TITLE
switch vs if behaviour unexpected

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#3592]
Please see this example: https://flowtype.org/try/#0C4TwDgpgBAglC8UDeAoKVSQFxQOQ1wBo0oBDHAOwFcBbAIwgCcUBfFFTaAIQWRM5y4uREnRwBnYIwCWFAOat2nKAGFecAD5QuAbnYAzKhQDGwaQHsKGCJIAUYUo1I0cKgJSp00-fcfOAdMrwwXgEHiQAkIwQwFSMVg5ONP6kOlAkbF4+iQFBIUK44ehRMXEJfsmpUAD01VAAPAC0zY0YABbS4lD6pNIANl3G5ozRpn0g6eiZUOIA7tLAxm2+SYHgEEXoUMak4tD4uFgkW1DRsfFQOZV6Jzt7eMJHJ+hnZZcVKWm1DS2twB1dcRtcxUPoAE26vT6UAAklA5FQbOIAPwZVhAA

Why doesn't the switch example behave the same as the if counterpart?

**Comment by vkurchatkin** [comment]
This works because the whole `switch` clause is unreachable. Without ifs this works as expected

**Comment by hmeerlo** [comment]
@vkurchatkin thanks, should have seen that myself
