### ISSUE TITLE
When are annotations stripped?

### ISSUE THREAD

**Issue by brycepj** [facebook/flow#361]
I feel like the answer must be obvious, but I've been poking around the docs, and can't find anything about it. 

I've used the `/* @flow* /` annotation, as well as various type annotations in the file itself, and checked it with `flow check`. But clearly all the type annotations I'm adding to my code won't let it run. 

e.g. with typescript, `.ts` files are compiled into `.js` files.

**Comment by ianobermiller** [comment]
This is covered in [Running Flow code](http://flowtype.org/docs/running.html). [Babel](https://babeljs.io/) is probably the most recommended way right now.

**Comment by brycepj** [comment]
I guess comparing Flow to TypeScript isn't very accurate then -- they're not really in the same class of tooling. 

Is handling a transform/compile step something that's on the horizon for Flow?

**Comment by wayneseymour** [comment]
I just spent 15 minutes trying to see how to compile down too!  (doh)

**Comment by wayneseymour** [comment]
Thanks @ianobermiller

**Comment by samwgoldman** [comment]
@brycepj Is this issue resolved?
