### ISSUE TITLE
Confused about the relationships between subtype and subset

### ISSUE THREAD

**Issue by ioslh** [facebook/flow#3612]
When I reading [this article](https://flow.org/en/docs/lang/subtypes/) on flow.org, I am totally confused.

Original Content: 
> so a single number (such as 42) would be a subtype of the number type.

My Conclusion: 
> a single number is a subtype of the number type; Obviously, a single number is a subset of the number type. From which we can conclude: A is subset of B, then A is subtype of B.

BUT, in the following paragraph it says:
> the relationships between “subsets” and “subtypes” are inverted

When it comes to the following example:
```flow
// @flow
function method(val: 1 | 2 | 3 | 4 | 5) {
  // ...
}
```
The function `method` expects the numbers 1 through 5, any subtype of that set will be acceptable.
According to the `... inverted` conclusion,  `1 | 2 | 3 | 4 | 5 | 6 | 7 ` maybe a good one, but that's not reasonable.

Am I totally misunderstood something?

**Comment by samwgoldman** [comment]
I agree this documentation is confusing. Subset of inhabitants and subtype are definitely not inverted.

```
// @flow
type A = 1 | 2;
type B = 1 | 2 | 3;
declare var a: A;
declare var b: B;
(a: B); // OK: A is a subtype *and* a subset of B
(b: A); // Error: B is a superset, not a subtype of A
```

I think there might be confusion due to object types, where `{}` :> `{x:T} :> `{x:T, y:U}` — the type with "more" declared properties is the subtype.

Thanks for pointing this out! We should fix this right away :)

**Comment by mwalkerwells** [comment]
@samwgoldman Close?
