### ISSUE TITLE
Flow does not respect immutability of $ReadOnlyArray

### ISSUE THREAD

**Issue by gajus** [facebook/flow#3615]
Here is the code reproducing the issue:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWVgG4CWWASlgM4Cu0KAKpjgLygDeAPoqKANQBOlGvUYAuUAHIAtoRLjE7AL4BuZOmygAalgB2VMoNoN1LDl14Dqh0RII69cxStSNQ5S8ONn8xfe6M5Obi1dXyF-JwBjWG0KFFAAcywUNyEKUBYACgBKMQAScgBDABMAeW1oNABBPj4CtAAeFKtsAD50ttYzARQqPm1QAG0zbk7uMdALMOspGSw5cYUzAF0VZWQomLjIWD5JApRvEnTQDOkfJpQKPMLS8qqauvrD0OasFqz2ti6k3v6zkguFFWkWisVA8D4RBQL0uxwyk1oV1A+SwxTKFWqtQaF3870+o1AREgJwRlwAdNAdPEUAALdJMFgABg+BO4tL4CFA2iw8FAAFEajsMuIAKrcgAe2Ai0KKoFi+ywZPEWRU3EWZiJJIMlwGjKWZNJ-npLBmPmVX3G2z4Jw2YNJoFgxNJFBZwzGmvh2oN2qNAEIGRJ-nNXeNxuzOdzeQKOXxhWKsJKsNKsLL5dClSq3Wq3erxiBQHQaUQ0uH4GkqBKpTLQFhBXwyW78-HE8nZQAjJMFKgUHDO0ARAr9aIVfvRFAFIj9AoTbUO4lqHAAIiDi4blp2ewOs097hdTjzYAAQlQ4rTi+CdgBrK6NsBWzfPDIDZ26pZLTO30CVbSys9peBXjeB6gFaNqgnE9qOjOu4hmM+bcB6pLen4LgMiaQbmqyoDwWM977I+z7au+qpwWA2bAYs2ZrIgEJQjCFAZIkyTagxWSZkAA

```js
// @flow

type MovieResultType = {|
  +resultType: 'movie'
|};

type VenueResultType = {|
  +resultType: 'venue'
|};

type ResultType =
  MovieResultType |
  VenueResultType;

const getResults = (): $ReadOnlyArray<ResultType> => {
  return [
    {
      resultType: 'movie'
    }
  ];
};

const formatMovie = (movieResults: $ReadOnlyArray<MovieResultType>) => {
  return movieResults;
};

const writeResults = (results: $ReadOnlyArray<ResultType>) => {
  if (results.length === 0) {
    throw new Error('Unexpected state.');
  }

  if (results[0].resultType === 'movie') {
    for (const result of results) {
      if (result.resultType !== 'movie') {
        throw new Error('Unexpected state.');
      }
    }

    // This throws unexpected error.
    // Unexpected because results can only contain a result of type "movie".
    formatMovie(results);

    // But this works:
    // formatMovie([results[0]]);

    // And this works:
    // for (const result of results) {
    //   if (result.resultType === 'movie') {
    //     formatMovie([result]);
    //   }
    // }
  }
};

writeResults(getResults());

```

Error:

```
8:   +resultType: 'venue'                  ^ string literal `venue`. Expected string literal `movie`, got `venue` instead
4:   +resultType: 'movie'                  ^ string literal `movie`

```

**Comment by gajus** [comment]
Because I am doing:

```js
for (const result of results) {
  if (result.resultType !== 'movie') {
    throw new Error('Unexpected state.');
  }
}

```

There is no way `formatMovie(results)` can be getting anything else that is not of `MovieResultType` shape.

As expected:

```js
formatMovie([results[0]]);
```

Does not produce an error.


As expected:

```js
for (const result of results) {
  if (result.resultType === 'movie') {
    formatMovie([result]);
  }
}
```

Does not produce an error.

Therefore, neither should:

```js
for (const result of results) {
  if (result.resultType !== 'movie') {
    throw new Error('Unexpected state.');
  }
}

formatMovie(results);

```

**Comment by vkurchatkin** [comment]
`$ReadOnlyArray` is not immutable, it's just a read-only reference to a possibly mutable array. While your loop proves that the array only contains `MovieResultType` now, but this can change in the future. As a rule, you can never refine  type of an array, even read-only one.

**Comment by gajus** [comment]
> While your loop proves that the array only contains MovieResultType now [..]

I still don't comprehend what is the reason it throws an error in this particular case. As you said, I did check that *at the moment*, the array is what it is.

This after all works.

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWVgG4CWWASlgM4Cu0KAKpjgLygDeAPoqKANQBOlGvUYAuUAHIAtoRLjE7AL4BuZOmygAalgB2VMoNoN1LDl14Dqh0RII69cxStSNQ5S8ONn8xfe6M5Obi1dXyF-JwBjWG0KFFAAcywUNyEKUBYACgBKMQAScgBDABMAeW1oNABBPj4CtAAeFKtsAD50ttYzARQqPm1QAG0zbk7uMdALMOspGSw5cYUzAF0VZWQomLjIWD5JApRvEnTQDOkfJpQKPMLS8qqauvrD0OasFqz2ti6k3v6zkguFFWkWisVA8D4RBQL0uxwyk1oV1A+SwxTKFWqtQaF3870+o1AREgJwRlwAdNAdPEUAALdJMFgABg+BO4tL4CFA2iw8FAAFEajsMuIAKrcgAe2Ai0KKoFi+ywZPEWRU3EWZiJJIMlwGjKWZNJ-npLBmPmVX3GGzB3PggOOAxWw1ATu2fBOVripNAsGJpIoLKd3E18O1Bu1RoZJv+cwD43GNsBZIwVAoNJD7hVgdAiwWyHGrr2B1mGQT2v9quziDWiAhUJhFAyiWSZeymaAA

Could you share an example of how array can mutate before being processed by `formatMovie`? All the code is in the same event cycle; I don't see it.

**Comment by vkurchatkin** [comment]
Here is an example: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWVgG4CWWASlgM4Cu0KAKpjgLygDeAPoqKANQBOlGvUYAuUAHIAtoRLjE7AL4BuZOmygAalgB2VMoNoN1LDl14Dqh0RII69cxStSNQ5S8ONn8xfe6M5Obi1dXyF-J0QAY1htChRQSFg+SQBDFG8SUBYACmkfNyEKMQASchSAEwB5bWg0AEE+PhS0AB4M0KtsAD4ASiyutjMKLHoiSSxYKhRs7L6mAdYzbiJIUFyZDpQKAG0ABgBdADoLMJcAQiYWKQ3xPsXuB9A8kgLaHYPjgw8sQ4AjWFgklmKkeCjMCgANABGXaw3Y9EGgMwCFBUPjaJ4bV5bFTKZDRWLxeB8IgoTYULJrE5vEplKo1eqNZotbH+Xr9QbLVbZalbQ7QHQAcxQAAsspdQPDOQ9RXwEKBtFh4KAAKKNJLZcQAVUVAA9sJEyeVQHE0j9boiwWYVlSvu8jrz-OKrs8sLdpdxEnw1gS4qBeaBYKteRQ7ksHjaeV9Pn5zhLrj53fdHjKRXLlYrlWq5XxNTqsPqsIasMbTWTDhbw9wwaDkI8val0hso+5Q5bEHiojE-SHKdszMnuI7rAnZODEPsIsTSeSW4UEYgQ4cqLERStpsnh9gxOJbCE5AoeoggA

**Comment by gajus** [comment]
This is no different from me doing this:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWVgG4CWWASlgM4Cu0KAKpjgLygDeAPoqKANQBOlGvUYAuUAHIAtoRLjE7AL4BuZOmygAalgB2VMoNoN1LDl14Dqh0RII69cxStSNQ5S8ONn8xfe6M5Obi1dXyF-JwBjWG0KFFAAcywUNyEKUBYACgBKMQAScgBDABMAeW1oNABBPj4CtAAeFKtsAD50ttYzKJi4i1T00ABtM25O7nHQPuasMSkZLDkJhTMAXRVuMwokuiJJLFgqFAzs9rYzAEgplApBgAYVgDor-wHxWxDxddAFABpQAEZbkCsl8zAIUFQ+NpJgZriplMhurFQJBYHxJAUUN4SAMMtIfE1rnlCqVylUanV6tjQtMWllTmMYRCoaB8SRCRR4ZFosj4HwiCgaddcVcKMSsMUyhVqrUGoT-HSGWYiJBQBlRQ9oDp4igABbpJgsW70xncPV8BCgbRYeCgACiNTRGXEAFVrQAPbARQVFUCxTFYB7iEFmZbK1Xq2E3e5PWEvQ0sOY+YNnCZIuLW+AcgaDNYjUD51F8NXpmHuUCwVWik357gqtVXWN+FwJiRshY1iYTTMch4YKgUXWR9whrvffNhiZFjFY+YZHtR0fjhGIPkCoUUDKJZJR7IhoA

The end result is the same (Just no Flow errors).

**Comment by vkurchatkin** [comment]
Well, that seems to be a bug

**Comment by SamChou19815** [comment]
Expected as Flow won't be able to support all possible refinement logic.
