### ISSUE TITLE
Subtypes for strings do not work with literal types 

### ISSUE THREAD

**Issue by LegNeato** [facebook/flow#3618]
Repro:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAEsQM4DqxBW2A5nWAN6phgLNWWDgC4wAQQIFiATwA8TFuwB8AGlQBfXmF44ZABwqKhbMAF5u20nAAmeMXRwF26vgFs8dOsTZ4A-A5OLpoA3Oh6hmAMABbE+ABuhMbs5pZ81nZiAOQAYgDyeQCMWWAAPmC5BQBMWa5gHl4+-oHOwuoaYaikMPScMXF4iQRgGG76MHgeuJw09MnCnDx8AkoLYpLS8v0JSYIqqQDaALphGkA

I know I can make `Warning` generic, but I would expect this to typecheck as-is. Flow should know that `WhateverWarning` is a subtype of `Warning`. That is, that `'FOO1' | 'FOO2'` is a subtype of `string`.

**Comment by vkurchatkin** [comment]
You need to add a bunch of covariance sigils to make this work: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAEsQM4DqxBW2A5nWAN6phgDUCZqywcAXGAAkAJTzEAJgHksMAJ4BBAgWKqAPExbsAfABpUAX15heOVQAcKBkWzABeblf6k48vBLo4BOxmfAC2eHR0xGx4APz+gcEWANzotg5gDAAWxPgAboRO7G4efF4+fmAA5ABiiooAjFVgAD7VdYoATFUhYOGR0XEJQaJm5qmopDD0nNm5eAUEYBihdjB44bicNPRFopw8fEKG+xIyckoqGlo6+jn5hcLGJQDaALqplqhAA

**Comment by LegNeato** [comment]
Thanks! If that's the case, shouldn't it warn me of the covariance like it does for constructors?
