### ISSUE TITLE
PropTypes.shape behaviour changed between versions

### ISSUE THREAD

**Issue by smozely** [facebook/flow#3621]
Hey there, somewhere between 0.38.0 and 0.42.0 it seems this behaviour changes, just question if this is a bug or the change was expected?

In 0.38.0 this works 

store-shape.js
```
export default PropTypes.shape({
  subscribe: PropTypes.func.isRequired,
  dispatch: PropTypes.func.isRequired,
  getState: PropTypes.func.isRequired
});
```

some-component.js
```
  // @flow weak
 
  return React.createClass({
    propTypes: {
      store: StoreShape.isRequired
    }

 ... somewhere else ...
this.props.store.getState(); // Does this line error
```

But after upgrading to 0.42.0 that line will now error ...
> Flow: call of method `getState`. Method cannot be called on possibly undefined value undefined

I found that if I inline the definition it won't pick that error up ... 
```
  return React.createClass({
    propTypes: {
      store: PropTypes.shape({
        subscribe: PropTypes.func.isRequired,
        dispatch: PropTypes.func.isRequired,
        getState: PropTypes.func.isRequired
      }).isRequired
   }
```

We are just introducing flow to our codebase, hence old style `React.createClass`

**Comment by samwgoldman** [comment]
Hmm, sounds like something could be up. We changed a bunch of stuff with React.createClass in 0.42, but what you're describing definitely doesn't sound right.

I tried to reproduce with the information provided here, but I can't. Can you share a repro case that exhibits the issue so I can debug? Thanks.

This is what I tried:

```
const React = require("react");
const {PropTypes} = React;

const StoreShape = PropTypes.shape({
  subscribe: PropTypes.func.isRequired,
  dispatch: PropTypes.func.isRequired,
  getState: PropTypes.func.isRequired,
});

React.createClass({
  propTypes: {
      store: StoreShape.isRequired,
  },
  m() {
    this.props.store.getState();
  },
});
```

**Comment by smozely** [comment]
Hi @samwgoldman ... sorry for delay ... ok found the thing, and its not a big issue (or even a issue at all)

First your example worked, but in my case StoreShape is defined in another file, then I realised that my store-shape file doesn't have `// @flow` at the top. 

Doh! ... I've been bitten by that lots as we are migrating more and more stuff to use flow.

That said the behaviour for did change between versions, so I feel slightly less silly for making the mistake here. And guessing the current behaviour should be expected.

Apologies for the false alarm
