### ISSUE TITLE
How to get the return type of a function

### ISSUE THREAD

**Issue by srajko** [facebook/flow#3628]
Is it possible to get the return type of a function?  Something along the lines of the following:

```
type returnsAString = () => string

type returnType = $ReturnType<returnsAString> // returnType = string
```

**Comment by nmn** [comment]
You can write your own type for this.

Specially if you know the type of the arguments. Here's an example:

1. Function with no arguments:
```typescript
type _Return0Type<R, F: () => R> = R;
type $Return0Type<F: Function> = _Return0Type<*, F>;

type returnsAString = () => string

type returnType = $Return0Type<returnsAString> // returnType = string
```

Of course, since it relies on `*` it won't always work perfectly. But it should work for most cases just fine.

**Comment by srajko** [comment]
@nmn thank you, that is super helpful!

To get around needing to know the type of arguments, I'm using
```
type _ReturnType<R, F: (...args: any) => R> = R;
type $ReturnType<F: Function> = _ReturnType<*, F>;
```
(so far, so good)
