### ISSUE TITLE
FlowType does't show error when mismatched types are: + or === 

### ISSUE THREAD

**Issue by giantelk** [facebook/flow#363]
In the example on the FlowType home page, change the `*` to a `+`. It doesn't find any errors:

```
function foo(x) {
  return x + 10;
}

foo('Hello, world!');
```

Same issue if you compare mismatched types for equality `===` i.e.

```
function foo(x) {
   if (x === 10) {
       // Do something.   
   }
}
```

This finds the error if you type the parameter i.e. `function foo(x: number)`. Would of thought if flow can catch `*` without strong typing, it would also catch `+` and `===`.

**Comment by samwgoldman** [comment]
The behavior in your first example is specifically documented [here](http://flowtype.org/docs/type-annotations.html#simple-example).

For your second example, it isn't clear to me what you expect. Could you show me a full example (including some code that calls `foo`), and the actual outcome vs. your expectation?

**Comment by giantelk** [comment]
My example #2 is calling foo with a string when is should in an integer i.e.:

```
foo('Hello, world!');

function foo(x) {
   if (x === 10) {
       // Do something.   
   }
}
```

**Comment by samwgoldman** [comment]
@giantelk You didn't specify what you expected to happen, but that is not an error as-is.

Flow is very smart, and within the then-block of the if-statement, flow realizes that x is a number. However, the function foo is still defined over all types, it just returns undefined.

If you want foo to reject all x except numbers, you need to annotate the function argument with the expected type.

Does that make sense? Do you still believe that flow should behave differently than it does now?

**Comment by giantelk** [comment]
I'm asking why Flow cannot trap this by jus using @flow, without annotations.

**Comment by mroch** [comment]
Flow's not trying to enforce "good programming," it's trying to enforce that the program is valid. Your example sounds like a job for a linter. I'd love to see a type-aware linter built on top of flow that could catch something like this (if you wanted it to), but I don't see flow enforcing this.
