### ISSUE TITLE
Replace Flow-Parser with Babylon

### ISSUE THREAD

**Issue by rattrayalex** [facebook/flow#3631]
Hi, 

I'm not sure if you're interested in this, already planning on it, or have already decided not to implement. 

Now that Babylon can produce an ESTree-compliant AST, its output could be used in place of the current OCaml parser. This might reduce redundant efforts (eg; in fixing parser edge-cases) and make it easier for Flow to add new ES7 features in the future. 

Performance might be worse (FFI overhead, JS speed, serialization, etc), and there might be advantages to parsing within OCaml that I'm not aware of. 

Is this something the team is interested in?

**Comment by nmote** [comment]
Performance is extremely important and I think that the cost of a parser running in JS would be unacceptable.

Plus, it would complicate the install process for end users. Most people using Flow probably have node installed, but we would have to make sure, and we would also have to worry about node versioning issues.

**Comment by rattrayalex** [comment]
Makes sense! Thanks @nmote !
