### ISSUE TITLE
Disjoint union: Flow doesn't recognize this is a type check

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3633]
I have a key/value storage that stores objects of the form

```
{
    type: 'Access' | 'Chum' | 'Email' | 'Mailbox' | 'Person' | ...
    data: {
        ...key/value properties depend on the "type"....
    }
}
```

The type `MyObjectTypeNames` is the union of the type strings.

The type `MyObjectTypes` is the union of all the object types above, each one defined individually, all following the same pattern.

Now when I get such an object from storage I want to be able to do so with type information - obviously a normal raw "getStuffFromStorahge" function can only return one and the same thing, the type checker doesn't know what kind of object there is going to come.

So I made a function thus:

```javascript
const getObjectAsObjectWithType = function <T: MyObjectTypes> (
    hash: string,
    type: MyObjectTypeNames
): Promise<T> {
    return getObjectAsString(hash)  // returns HTML microdata string
    .then(MicrodataToObject.convert)  // returns type "MyObjectTypes"
    .then((obj: MyObjectTypes) => {
        if (obj.type === type) {
            return obj;
        } else {
            throw new TypeError('Wrong type');
        }
    });
};
```

This forces the type to be the desired one. However, I had to use a "to-any-then-to-type" type cast to get this working:

```javascript
            return ((obj: any): T);
```

This works just the same and obviously guarantees that the returned object has the desired type. But how can I tell Flow without the `any` in there?

Second (or the same question?), I don't see a way to use the `type` string parameter for the generics parameter, but this is EXACTLY what I would need with any disjoint union type. Those generics only work when I already have an object of the desired type in the parameter list, not useful in this situation.

So the parameterization of the generic type seems useless for this function, since the `type` string is not used, but if I only use `OneObjectTypes` as the return type it won't work either.

Strange enough, or even more strange, I have another, similar and more complex function for objects stored with more context that uses this exact same method to ensure the returned type, and there the above works without introducing `any`.

**Comment by madbence** [comment]
in your example, `type` is a union type, so the test for `obj.type` cannot really help you. Type refining i guess right now works only with comparisons with literals (`if (type === 'foo')`), and checking for existence (`if (foo)`).

my best shot would be something like this:

```js
// @flow

type Foo = { type: 'foo' };
type Bar = { type: 'bar' };
type MyType = Foo | Bar;

const store: { [string]: MyType } = {
  foo: { type: 'foo' },
  bar: { type: 'bar' },
};

function get<T: MyType>(hash: string, type: $PropertyType<T, 'type'>): T {
  const obj = store[hash];
  if (obj.type === type) {
    return obj;
  }
  throw new TypeError('Whoops!');
}

const res: Foo = get('foo', 'foo');
const res: Bar = get('foo', 'foo'); // this should fail...
```

**Comment by lll000111** [comment]
> in your example, type is a union type

No it isn't. I wrote

> The type MyObjectTypes is the union of all the object types above, each one defined individually, all following the same pattern.

So the `type` property on each and every object is a fixed string literal, and the `type` variable used to compare against is a fixed string literal too.

Sorry if that wasn't clear enough. the full example code would be much larger so I abbreviated the example and used text to explain.

**Comment by madbence** [comment]
> The type `MyObjectTypeNames` is the union of the type strings.

the `type` argument in `getObjectAsObjectWithType` has type of `MyObjectTypeNames`, so it's a union type. if `type` is a union type, flow cannot refine the type of `obj.type`, because it has no idea what will be the concrete value of `type`. if it's `$PropertyType<T, 'type'>`, it could reason that `type` has a type of `'foo'` when `T` is `Foo`, and therefore `obj.type === type` can be true only when `obj.type === 'foo'` and therefore returning `obj` has the correct type `Foo`.

here's a simpler example:

```js
type Foo = { type: 'foo' };
type Bar = { type: 'bar' };
type Union = Foo | Bar;

// function get<T: Union>(type: 'foo' | 'bar'): T {
function get<T: Union>(type: $PropertyType<T, 'type'>): T {
  const obj: Union = { type: 'bar' };
  if (obj.type === type) {
    return obj;
  }
  throw new Error('whoops');
}

const foo: Foo = get('foo');
const bar: Bar = get('foo'); // this should fail...
```

the latter call should fail, because `T` is `Bar`, but then `get` should only accept `'bar'` as a parameter.

**Comment by madbence** [comment]
> This is a very different situation with real storage. I get a string that I have to convert to some object. In your code the object is right there to be statically checked. I don't have that luxury,

you annotated your code with `(obj: OneObjectTypes) => ...` (but i have no idea what `OneObjectTypes`, it should be `MyObjectTypes`), so your store is checked as well.

**Comment by lll000111** [comment]
> the type argument in getObjectAsObjectWithType has type of MyObjectTypeNames, so it's a union type.

Well of course! That can be any of those strings! Do you want me to use one function per type??? No thanks.

**Comment by lll000111** [comment]
`type: $PropertyType<T, 'type'>` indeed was the key to get this done. 

Thanks!
