### ISSUE TITLE
Static and instance methods returning Self

### ISSUE THREAD

**Issue by zaiddag** [facebook/flow#3636]
Significantly useful pattern, particularly for models/ORMs

class Model
Model.get returns Promise<Self>
Model.query return Promise<[Self]>
Model.prototype.save return Promise<Self>

class User extends Model

User gains Model methods, with returns already actually being user objects

Flow needs to support this

**Comment by madbence** [comment]
afaik it's supported with the `this` type:

```js
class Model {
  static stored: this;
  static get(): this { return this.stored; }
}

class User extends Model {}
class Foo extends Model {}

const user: User = User.get();
const foo: Foo = User.get(); // fails, because `User.get()` returns `User`
```
