### ISSUE TITLE
Infer string enum from the result of string concatenation

### ISSUE THREAD

**Issue by szdavid92** [facebook/flow#3637]
Currently flow cannot infer that the result of string concatenation is a string enum value:

```js
type command = 'go_in' | 'go_out'

const com1: command = 'go_in' // OK
const com2: command = 'go_' + 'in' // Error
const createCommand = (dir: 'in' | 'out'): command => `go_${dir}` // Error
```

[Demo](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDGcAtiQIYB2AJmALxgDkA5nAPoCWljYAPk6zZwArhkbpilAM4YipAIwAuOWSq0GLdl3GSZKgEzLiqmvQHseAaibbUu2YQBOechjwBhUhVMMAFNQ5HZUZtPiYRMQBKIy81egA+MAADQQASAG8AxwBfJPR81CA)

**Comment by vkurchatkin** [comment]
I'd say that while something like this is possible, it's out of scope of Flow.
