### ISSUE TITLE
Classes returned by function closures

### ISSUE THREAD

**Issue by mightyguava** [facebook/flow#3639]
I can't seem to figure out how to reference types of classes written in the pattern, where I want to closurize some dependencies into a factory function for classes, see below:

```javascript
// models.js
module.exports = function makeModels(db: Database) {
  class Car {
    constructor() {}
    drive() {...}
    static findCar(id): string {
       return new Car(db.find("car", id));
    }
  }
  return {Car}
  class Plane {
    constructor() {}
    fly() {...}
    static findPlane(id): string {
       return new Plane(db.find("car", id));
    }
  }
  return {Car, Plane}
}

// controller.js
import type Models from './models'

module.exports = function makeController(models: <What type is this?>) {
  function driveMyCar(id) {
    models.Car.findCar(id).drive();
  }
}

// index.js <= Entry point
let db = require('my-database');
let models = require('./models')(db);
let controller = require('./controller')(models);
controller.driveMyCar("123");
```

In `controller.js`, I don't know how to annotate the type for `models` as the argument to the `makeController` function.

- I can't use `Models` since it actually references the `makeModels` function that returns `models`.
- I can't reference the `Car` class since it's scoped inside the `makeModels` function
- I thought about writing an interface type for `Car` and `Plane`, and annotating the `makeModels` function as returning classes implementing the interface types, and exporting a type alias for that return value for `controller.js` to use, but not sure how to deal with the `static` methods
- I _think_ there's probably a way to declare the static and non-static methods of all the `Plane` and `Car` classes as a class type outside the function scope and annotate that `makeController` returns an object matching those classes... I think.... But that would be quite a bit of code duplication.

I'm pretty new to flow so there's probably a much easier way I'm not seeing. Hopefully you can help?

**Comment by madbence** [comment]
i'd export the interfaces (afaik static methods are supported), and return classes in `makeModels` that implement them, but something like this should work (it's not working, i don't know why... :crying_cat_face: ):

```js
function makeModels(db: any) {
  class Car {
    constructor() {}
    drive() {}
    static findCar(id): Car {
       return new Car(db.find("car", id));
    }
  }
  class Plane {
    constructor() {}
    fly() {}
    static findPlane(id): Plane {
       return new Plane(db.find("car", id));
    }
  }
  return {Car, Plane};
}

type MakeModelRet<T, V: (db: any) => T> = T;
type Models = {
  Car: $PropertyType<MakeModelRet<*, makeModels>, 'Car'>,
  Plane: $PropertyType<MakeModelRet<*, makeModels>, 'Plane'>,
};

function makeControllers(models: Models) {
  function driveMyCar(id) {
    models.Car.findCar(id).drive();
  }
}

let db = {};
let models = makeModels(db);
let controller = makeControllers(models);
controller.driveMyCar("123");
```

https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYGsCmBZOATTAGwGcAKPAIwC5FUwBPASkQG8AoRRCQ1Y4xAMKoATqw6cuCYlGEhocYaWYsAvuM55hMAG6YlrNRMTTUsCImAwweIYph5GNW2KMThmKCGFIwmAO6CIuQUAHSW1qQARBAikQA0iPaMjADc6oiGGeLcvPwACjy+LhIQUjJyUAr6qunAhPTVmZwmZhZWeAV0ekk0nUXsrpzunt6IvgF9epRh7VEADl3xiQ6p6ZmZw15ILLYJkyppamxQ9HOYiNgYOPhEAEoeADwAKgkAajTBNHRMiAC8AHyIJ6A35AtInM4XG4kP7FWw0AAkeWEcDOwhOT1OmAelywuAIhHuUAeACoEmg8dDiP8EgByWy0mniSaI5GozDo+iYs44q74u6PMkoPlUmmIWmTRlxNgHNhsUCQWAIYVYAQIGRwQiEDlkZBUmj8kjKcQK6DwJCaHQ4ei2UhJYqcPUE4ghWwzay2pIhS26JRpThqI7aqCISiw1RpYMoKmwinXZ3BVZR0pgDVajmxq5q1Mo9PCXVU1YptPa4TerS6bA2oKRACMACYAMyRVJAA

**Comment by mightyguava** [comment]
Ah nice, I think I understand what you are trying to do there. Strange that there's no utility type for referencing the a return type of a function.

But yeah... I can't understand why that doesn't work either. The error message is not making sense to me.

```
19: type MakeModelRet<T, V: (db: any) => T> = T;
                            ^ function type. Callable signature not found in
22:   Plane: $PropertyType<MakeModelRet<*, makeModels>, 'Plane'>,
                                           ^ prototype
```

**Comment by madbence** [comment]
yay, i was able to resolve the issue, `makeModel` is a value, and you need the type of that, so `typeof makeModel`.

```js
function makeModels(db: any) {
  class Car {
    constructor() {}
    drive() {}
    static findCar(id): Car {
       return new Car(db.find("car", id));
    }
  }
  class Plane {
    constructor() {}
    fly() {}
    static findPlane(id): Plane {
       return new Plane(db.find("pane", id));
    }
  }
  return {Car, Plane};
}

type MakeModelRet<T, V: (db: any) => T> = T;
type Models = {
  Car: $PropertyType<MakeModelRet<*, typeof makeModels>, 'Car'>,
  Plane: $PropertyType<MakeModelRet<*, typeof makeModels>, 'Plane'>,
};

function makeControllers(models: Models) {
  return {
    driveMyCar(id) {
      models.Car.findCar(id).drive();
    }
  };
}

let db = {};
let models = makeModels(db);
let controller = makeControllers(models);
controller.driveMyCar("123");
```

https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYGsCmBZOATTAGwGcAKPAIwC5FUwBPASkQG8AoRRCQ1Y4xAMKoATqw6cuCYlGEhocYaWYsAvuM55hMAG6YlrNRMTTUsCImAwweIYph5GNW2KMThmKCGFIwmAO6CIuQUAHSW1qQARBAikQA0iPaMjADc6oiGGeLcvPwACjy+LhIQUjJyUAr6qunAhPTVmZwmZhZWeAV0ekk0nUXsrpzunt6IvgF9epRh7VEADl3xiQ6p6ZmZw15ILLYJkyppamxQ9HOYiNgYOPhEAEoeADwAKgkAajTBNHRMiAC8AHyIJ6A35AtInM4XG4kP7FWw0AAkeWEcDOwhOT1OmAelywuAIhHuUAeACoEhDMHBgCgrviiMR-gkAOS2JmM8STRHI1GYdH0TFnHG06FE0nkrFUml46EM5mTNlxNgHNhsUCQWAIKWYAQIGRwQiEXlkZAymh0kjKcSbUYDCSaHQ4ei2UhJYpGE0E4ghWwzazOpIhe26JRpIzrQ4qw1QRCUWGqNJRlAy2FoaWe4KrROlMB6g28lNXHU5lF54TGmWrbO5w3CQNaXTYJ1BSIARgATABmSKpIA

**Comment by mightyguava** [comment]
Oh, that makes a lot of sense. Let me try plugging this into real code 😄

**Comment by mightyguava** [comment]
Amazing! I think it worked! Thanks @madbence
