### ISSUE TITLE
Class field type safety

### ISSUE THREAD

**Issue by dszakallas** [facebook/flow#3640]
I was wondering about how Flow can possibly support public class fields if the [proposal](https://tc39.github.io/proposal-class-public-fields/) solidifies as it is, without leaving ambiguity whether the programmer meant a PublicFieldDefinition without Initializer + a type annotation; or the whole definition to be stripped out.

Currently the whole definition is stripped out:

```js
/* @flow */
class Person {
  age: number;
}
```
transpiles to
```js
class Person { }
```
[Babel sandbox](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017%2Creact&targets=&browsers=&builtIns=false&code=%2F*%20%40flow%20*%2F%0A%0Aclass%20Person%20%7B%0A%20%20age%3A%20number%3B%0A%7D%0A)

However once that proposal lands in the standard another possible target can be
```js
class Person {
  age;
}
```
which AFAIK has slightly different runtime semantics. This even means to me that `age: number` can't actually pass type check as you can't initialize a `number` to `undefined` as is the case specified in the proposal.

The other interesting thing is that the upmost code passes type check, so currently Flow turns a blind eye to uninitialized class fields. This is apparent here:
```js
/* @flow */

class Person {
  age: number;
}

const p = new Person();

(p.age: number);
console.log(p.age);
```
Asserting p.age as a number passes, regardless it is `undefined`.
[Babel sandbox](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2017%2Creact&targets=&browsers=&builtIns=false&code=%2F*%20%40flow%20*%2F%0A%0Aclass%20Person%20%7B%0A%20%20age%3A%20number%3B%0A%7D%0A%0Aconst%20p%20%3D%20new%20Person()%3B%0A%0A(p.age%3A%20number)%3B%0Aconsole.log(p.age)%3B%0A) [Flow sandbox](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsABQFMAnXOAOzAG9UwxsBzYgLjEoFcBbAIzIDcqAL7oMVXABcwABzABeDsSQlyVABQBKIanUyAdMzYce-UtswS4MYvvhM9hlhfSvXQA)

I'm just curious about if this is a known issue that is going to be rectified once the proposal lands, and also how you plan to resolve the mentioned ambiguity.

**Comment by SamChou19815** [comment]
We now let you do

```
class Person {
  declare age: number;
}
```

If you want the extra safety.
