### ISSUE TITLE
"try flow" is broken with latest (default) version v0.43.0

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#3647]
see: https://flow.org/try/

**Comment by Daniel15** [comment]
I'm seeing this too, looks like the 0.43.0 JavaScript is throwing 404 errors.

**Comment by mroch** [comment]
so, to prevent the site from being reverted to the release branch, I made Travis stop publishing the site on tags. this also prevented travis from uploading the 0.43.0 flow.js build (duh!)

we'll have to manually upload it, and fix deploying the JS on tags

**Comment by mroch** [comment]
manually uploaded it for now
