### ISSUE TITLE
Calling a function without arguments passes typecheck in case of variadic argument list

### ISSUE THREAD

**Issue by dszakallas** [facebook/flow#3648]
I was just about to [submit a definition](https://travis-ci.org/flowtype/flow-typed/jobs/218183185) to flow-typed when I encountered this bug:

```js
function emit(event: string, ...params: any[]) {}
emit('something');
// $ExpectError
emit(); // this line passes type check !!!

function emit2(event: string) {}
emit2('something');
// $ExpectError
emit2(); // Error: too few parameters
```

[Flow sandbox](https://flow.org/try/#0GYVwdgxgLglg9mABAUwLYygCmQN2WKALkQGcoAnGMAcwBpEA6JgBwENzXUTjWwBPANoBdAJSIA3gF8AUGgyYA5CTipkUABZVqCkQG5pAegOIAJAFEAHs2TQz5cnHKz0WPYiOIA7ur6IAJnDIJIgaMMFsJCQA-DHS0qCQsAgoLgBM2HgExGSUNGJSzhjpSipqmjQ6+h7mVjZQdg5OclDpenHtQA)

Seems like the normal parameters aren't checked in case of a variadic parameter pack.

**Comment by vkurchatkin** [comment]
cc @avikchaudhuri seems to be a bug in multiflow

**Comment by vkurchatkin** [comment]
Sorry, meant to cc @gabelevi

**Comment by SamChou19815** [comment]
this now correctly errors
