### ISSUE TITLE
Spread Type: Unable to spread exact object into non-exact object

### ISSUE THREAD

**Issue by benderTheCrime** [facebook/flow#3652]
With flow 0.42.0 I seem unable to spread any type.

I have a type:
```javascript
export type Foo = {
    name: string,
};

export type Bar = Foo & {
    type: string,
};
```

When I try to spread Foo onto Bar:
```javascript
export type Bar = {
    ...Foo,
    type: string,
};
```

I get a host of exceptions. Surprisingly enough, I also get exceptions when I do:
```javascript
export type Bar = {
    ...{ name: string },
    type: string,
};
```

Which leads me to believe that type spreading is not working at all. 

I have:
- made sure 0.42.0 is installed
- made sure that version is reflected in my .flowconfig
- stopped all running background processes
- reinstalled flow-bin many times
- boiled this down to the idiomatic type above and used it in a single place

Am I not doing something I should be?

**Comment by vkurchatkin** [comment]
What errors do you get?

**Comment by benderTheCrime** [comment]
"obj.name undefined. This type is incompatible with the expected param type of string."

I'll get better console output for you shortly. This also seems to be working perfectly fine on the flow site "Try":

https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBiEJwLxwN4BQcxcAdgIYC2wAXHAM4xQCWpA5gDQEC+A3AQVCRYCZKgBC5KDnxE4ASAB0yjBC4lRKOoxbsufAQDMArqQDGMZhFJxDmABQQARgCs6kqAEpZGs9foQADbAioEQbI6uihTUHHDOLopIKJ783EYOeGRUtHAA5CB5ccm5eYh5cNypQA

**Comment by vkurchatkin** [comment]
This is expected behaviour. You need to wrap objects in `$Exact`:

```js
type Bar = {
  	...$Exact<Foo>,
    type: string,
};
```
