### ISSUE TITLE
Intersection type does not work in React Props

### ISSUE THREAD

**Issue by excitement-engineer** [facebook/flow#3657]
I am using flow in my react application to define the type of the props as an intersection of two objects:

```js
type ErrorHandler= {
   error: {
      display: () => void
   }
}

type Props =
  & {
    accountId: string
  }
  & ErrorHandler;
```

However, flow is not typechecking my code.

For example, the following incorrect statement does not produce a flow error

```js
const id = this.props.account.id // Should give error
```

If I subsequently define my props as follows then flow works again/

```js
type Props = {
    accountId: string,
    error: {
        display: () => void
    }
}
```

Is this a bug in flow or am I making a mistake here?

**Comment by STRML** [comment]
This throws correctly in [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgCiWVLAAliAOwAm0QllABeUAG9EoFdMEAuRcpU7xyAM7poxDpoAUASjkA+UADdYycdtABfRO-ZceABSrp9OS0VMlJYAFdRHABJcU19HCxkUQBzD1AAMj4BbBEJKSxWRFJjfUCAYWpMUUIo0EIADxxa8UCiMhwAOkqMWBq6pRVtdH99TT9YANYVBglpS2CdMNEE0CcgnAALA06Ryf1O0IiozvWQUABlTYjocVAU5DseNWxtd1cgA), so your error may be elsewhere.

Be sure you're running the latest version.

Also try the new spread properties!

```jsx
type Props = {
  accountId: string,
  ...ErrorHandler
}
```

**Comment by nmn** [comment]
Also, mark all your keys on your Prop types as covariant (read-only) and some of the errors will go away.

```
type ErrorHandler= {
   +error: {
      +display: () => void
   }
}

type Props =
  & {
    +accountId: string
  }
  & ErrorHandler;
```

**Comment by excitement-engineer** [comment]
It seems like a bug on my side, I will check it out! Thanks a lot for your help, I appreciate it:)
