### ISSUE TITLE
Cannot be compared to 'break' in async do/while loop

### ISSUE THREAD

**Issue by STRML** [facebook/flow#3660]
Do-while loops appear to have a few oddities; seems to be mistaking the `retries` var for the last token in whatever the last statement of the `try` was. Forgive the mostly nonsensical function, I am attempting to make as minimal a case as possible.

[Example 1](https://flow.org/try/#0IYZwngdgxgBAZgV2gFwJYHsIwE4FNnZgDC6AtqcBACYA8AKgHwAUUZF1AXDEwJQwC8DGAAVsZVCFz0GPLqPGTpMAN4AoGDAA2+GMGTJcpAA7IBMAAwBudTFYQQpvAVS4QZgKzWN20+gTIuOi8YKnQVGw0CMHCNWJg-U35dAHdgVFNWckoqXmC4gCM8YABrPJgAX1s9KAALblw+ZXKbSuSa1G1uAGouvQNjUxocfGwXEB5gpwRsLATrcqA)

```jsx
async function retryCommand<T>(command: () => Promise<T>): Promise<T> {
  let attempt = 0;
  const retries = 5;
  let out: T;
  do {
    try {
      out = await command();
      break;
    } catch (e) {}
  } while (++attempt < retries);
  return out;
}
```

```
10:   } while (++attempt < retries);
               ^ number. This type cannot be compared to
10:   } while (++attempt < retries);
                           ^ break
11:   return out;
             ^ uninitialized variable. This type is incompatible with
1: async function retryCommand<T>(command: () => Promise<T>): Promise<T> {   ^ some incompatible instantiation of `T`
```

[Example 2](https://flow.org/try/#0IYZwngdgxgBAZgV2gFwJYHsIwE4FNnZgDC6AtqcBACYA8AKgHwAUUZF1AXDEwJQwC8DGAAVsZVCFz0GPLqPGTpMAN4AoGDAA2+GMGTJcpAA7IBMAAwBudTFYQQpvAVS4QZgKzWNVdCpsanBGwsYAB3YFRTVnJKKl4vGABfGFCAC1RtbgBqLL0DY1MaHHxsFxAea0SgA)

```jsx
async function retryCommand<T>(command: () => Promise<T>): Promise<T> {
  let attempt = 0;
  const retries = 5;
  do {
    return await command();
  } while (++attempt < retries);
}
```

```
6:   } while (++attempt < retries);
              ^ number. This type cannot be compared to
6:   } while (++attempt < retries);
                          ^ return
```

**Comment by SamChou19815** [comment]
This was fixed a while ago.
