### ISSUE TITLE
`|` condition of two types

### ISSUE THREAD

**Issue by evollu** [facebook/flow#3662]
when I have type definition like this 
```
/* @flow */

const CONVERSION_TABLE = {
  m: 1
};

function test(from: {x: string} | {y: number}) {
    if (from.x) {
       CONVERSION_TABLE[from.x];
    }
}
```
flow throws error at `CONVERSION_TABLE[from.x];`
example link here
https://tryflow.org/?code=LyogQGZsb3cgKi8KCmNvbnN0IENPTlZFUlNJT05fVEFCTEUgPSB7CiAgbTogMQp9OwoKZnVuY3Rpb24gdGVzdChmcm9tOiB7eDogc3RyaW5nfSB8IHt5OiBudW1iZXJ9KSB7CiAgICBpZiAoZnJvbS54KSB7CiAgICAgICBDT05WRVJTSU9OX1RBQkxFW2Zyb20ueF07CiAgICB9Cn0K

Anyway to make this code work?

**Comment by tntmarket** [comment]
Should {x: string} and {y: number} be disjoint? If so, then checking that **from.x** is defined isn't enough to determine that **from** is the 1st case. https://flow.org/en/docs/types/unions/#toc-disjoint-unions-with-exact-types explains why.

Does this:

```javascript
function test(from: {|x: string|} | {|y: number|}) {
    if (from.x) {
       CONVERSION_TABLE[from.x];
    }
}
```

do what you want?

**Comment by evollu** [comment]
@tntmarket Thanks that case works. But mine is actually more complicated than that
Can you check this?
https://tryflow.org/?code=Y29uc3QgQ09OVkVSU0lPTl9UQUJMRSA9IHsKICBtOiAxCn07CgpmdW5jdGlvbiB0ZXN0KGZyb206IHt4OiBzdHJpbmcsIHk/OiB2b2lkfSB8IHt4Pzogdm9pZCwgeTogc3RyaW5nfSB8IHt4OiBzdHJpbmcsIHk6IHN0cmluZ30pIHsKICAgIGlmIChmcm9tLnkpIHsKICAgICAgICBDT05WRVJTSU9OX1RBQkxFW2Zyb20ueV07CiAgICB9IGVsc2UgewogICAgICAgIENPTlZFUlNJT05fVEFCTEVbZnJvbS54XTsKICAgIH0KfQoKdGVzdCh7CiAgICB4OiAnMTEnLAogICAgejogJzIyJwp9KQoKdGVzdCh7CiAgICB5OiAnMTEnLAogICAgejogJzIyJwp9KQoKdGVzdCh7CiAgICB5OiAnMTEnLAogICAgeDogJzExJywKICAgIHo6ICcyMicKfSk=

**Comment by SamChou19815** [comment]
This kind of dynamic pattern won't be supported
