### ISSUE TITLE
Property type inferred as unknown in conditional expression

### ISSUE THREAD

**Issue by vaskevich** [facebook/flow#3667]
Here's a simple repro:

```
class MyStruct {
  method() {
    alert(this.someProp);  // Results in error: property `someProp`. Property not found in MyStruct

    if (this.someProp && this.someProp.length) {  // Works fine.
      alert(this.someProp.length);  // No errors here.
    }
  }
}
```

Accessing an undefined property directly results in an error, but works fine in conditionals expressions. The interesting thing is that `type-at-pos` reports the first instance of `this` in the conditional to be of type `MyStruct`, but the second instance of it to be `(unknown)`. Is this behavior expected, and/or is there a way to prevent it (i.e., throw an error)? Thanks.

EDIT: related to #1810, #1954

**Comment by kevinbarabash** [comment]
A colleague of mine just ran into this issue.  It would be nice if `flow` raised errors on any undeclared member instance inside a class.
