### ISSUE TITLE
This type is incompatible with null

### ISSUE THREAD

**Issue by ummahusla** [facebook/flow#3669]
Possible there is a simple solution, but clearly seems I missing something. Any ideas what prop type should I use here?

```
  state: { focusedInput: string }
  constructor(props: FilterProps) {
    super(props);
    this.state = {
      focusedInput: null
    }
  }
```

____

![](https://d3uepj124s5rcx.cloudfront.net/items/220U3Q3f3X1F2q040J1J/%5B5b93857b1cac762815eeeea077e7e4cb%5D_Image%25202017-04-06%2520at%25207.59.23%2520AM.png?v=dca2adee)

**Comment by ummahusla** [comment]
Ah, seems like using type `null` sort it out. 


```
state: { focusedInput: null }
```

**Comment by madbence** [comment]
you probably want to use `?string` ([maybe type]) to allow both `null`/`undefined` and `string` values as well.

[maybe type]: https://flow.org/en/docs/types/maybe/

**Comment by ummahusla** [comment]
@madbence Thanks for the suggestion!

**Comment by sibelius** [comment]
can I have a `?string` as a return type?

**Comment by madbence** [comment]
@sibelius sure, eg.:

```js
function maybeString(): ?string {
  return null;
}
```
