### ISSUE TITLE
type-check for the method of an object doesn't work

### ISSUE THREAD

**Issue by bupthly** [facebook/flow#3670]
I want to use flow in my project based on backbone.

for example:
```
var Manage = Backbone.View.extend({
     initialize: function() {
          ......
     },

     test(x: number) {
           return x + 1;
     },

     foo() {
           this.test('abc');
     },

     render() {
         .....
     }
});
```

it's expected that flow gives me the error infomation. But the result is no errors

![image](https://cloud.githubusercontent.com/assets/8244259/24748111/3e97c416-1af1-11e7-85f9-ec5002a6c3bc.png)

so is there a solution for this problem?

**Comment by nmn** [comment]
The problem here is probably that `Backbone.view.extend` isn't typed.

Something like this might work:

```typescript
class BackboneView {
  on(event: string, handler: Function): void;
  off(event: string, handler: Function): void;
  ...
}

declare var Backbone: {
  ...,
  View: {
    extend<T: {}>(config: T): BackboneView & T;
  }
}
```
