### ISSUE TITLE
Subtypes: Invariant Object with Covariant Object Property

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3673]
Passing both ```baz``` & ```quox``` should be safe?

````js
// @flow

function logNestedValue(value: { foo: { +bar: ?string }}): void {
  if (value.foo.bar) {
    console.log(value.foo.bar)
  }
}

declare var baz: { foo: { +bar: string }}
declare var quox: { foo: { bar: string }}
  
logNestedValue(baz) // Error
logNestedValue(quox) // Error
````

**Comment by vkurchatkin** [comment]
No, this is expected. You need to covariance on the top level

**Comment by mwalkerwells** [comment]
Was hoping that wasn't the case. :/

Since ```props``` is invariant for ```React$Component``` I was hoping I could do this...
````js
declare var mapComponents: <T>(Class<React$Component<void, { +value: T }, *>>) => void
                             
declare var A: Class<React$Component<void, { value: string }, *>>
declare var B: Class<React$Component<void, { value: number }, *>>
                             
mapComponents(A, B)
````

```props``` expands to be ```{ +value: string | number }```, but neither ```{ value: string }``` or ```{ value: number }``` are a subtype when it's invariant.

**Comment by vkurchatkin** [comment]
Ideally props should be covariant

**Comment by mwalkerwells** [comment]
I've thought of submitting a PR for that. You think they'd accept?

**Comment by mwalkerwells** [comment]
Is it somehow unsafe to have the ```{}``` type be a composition of any ```{}``` property types?

**Comment by vkurchatkin** [comment]
> I've thought of submitting a PR for that. You think they'd accept?

No idea

> Is it somehow unsafe to have the {} type be a composition of any {} property types?

Not sure what you mean

**Comment by mwalkerwells** [comment]
While currently not supported, is it somehow unsafe for the object type to be a function of the variance of each key?

````js
declare var foo: (
{ level1:
  { level2:
    { baz: string,
      +quox: ?string,
    }
  }
}) => void

declare var bar:
{ level1:
  { level2:
    { baz: string,
      quox: string, // <– Not ?string
    }
  }
}

foo(bar)
````

**Comment by vkurchatkin** [comment]
Property variance determines object variance wrt to type of this property. By default objects are invariant wrt to all properties, so you all properties must have exactly the same types.

Answering you question: yes, this is not allowed because this is unsafe. All properties without `+` are mutable, so it's easy to violate subtyping assumptions.

**Comment by mwalkerwells** [comment]
I'd argue that ````{ baz: string, +quox: ?string }```` should not be considered the same type as ````{ baz: string, quox: ?string }````.

If it wasn't considered the same, ```Line #17``` below would error and ```foo(bar)``` above would work.

````js
declare var level2Covariant: { baz: string, +quox: ?string }
declare var level2Invariant: { baz: string, quox: ?string }

type Levels =
{ level1:
  { level2:
    { baz: string,
      +quox: ?string,
    }
  }
}

function foo(value: Levels): void {
  
  const { level1 } = value  
  level1.level2 = level2Covariant
  level1.level2 = level2Invariant // Line #17
}
````

Since @samwgoldman wrote the blog post, I'm curious if he has thoughts... 😃
https://flow.org/blog/2016/10/04/Property-Variance/

**Comment by vkurchatkin** [comment]
They are not considered the same, covariant is a supertype of invariant:

```js
declare var x: { foo: string };
declare var y: { +foo: string };

(x: { +foo: string }); // Ok
(y: { foo: string }); // Error
```

**Comment by mwalkerwells** [comment]
So what am I missing? Is ```level1.level2 = level2Invariant``` not erroring a bug then? ```level2``` should be invariant.

Both your example...
> ````js
> declare var x: { foo: string };
> declare var y: { +foo: string };
> 
> (x: { +foo: string }); // Ok
> (y: { foo: string }); // Error
> ````
and ```level1.level2 = level2Invariant``` shouldn't work.

**Comment by vkurchatkin** [comment]
Indeed, this is either bug or some weird exception to invariance

**Comment by vkurchatkin** [comment]
Oh, actually, no, this makes sense. When you write to a property you don't have to provide exactly the same type, it's enough to provide a subtype.

**Comment by mwalkerwells** [comment]
Learned something new today, thanks @vkurchatkin!
