### ISSUE TITLE
CTRL+Click is not working and also flow coverage is not showing in Atom status bar

### ISSUE THREAD

**Issue by ugendrang** [facebook/flow#3675]
CTRL+Click is not working and also flow coverage is not showing in Atom status bar. It looks flow is not working, kindly assist.

Environment:
Atom version: 1.15.0
flow: flow-win64-v0.43.1
OS: Windows 10

My project's .flowconfig file includes below line and included the flow-win64-v0.43.1 file path in Environment Variable
[version]
^0.43.1

**Comment by nmn** [comment]
This is a bug for Nuclide not flow. Flow is only a CLI tool.
