### ISSUE TITLE
$UnsoundValues<O> WANTED Dead or Alive

### ISSUE THREAD

**Issue by freddi301** [facebook/flow#3677]
As reading other issues and proposals, if a sound version is far in the future at least give us (library writers) an unsound version

**Comment by nmn** [comment]
Here you go. Unsound version of values. Will check the type given in. But won't let you edit objects etc.
https://gist.github.com/nmn/b20a92e848c68d88f7fdb8353c71b1ca

**Comment by freddi301** [comment]
I already know about that, but is there a way to make a thing like this work with an unsound version of $Values?

```javascript
type $Object<V> = {+[key: string]: V}
type _$Values<V, O: $Object<V>> = V
type $Values<O: Object> = _$Values<*, O>

type Action<State, Handlers> = $Values<$ObjMapi<Handlers, <P, T>
  (type: T, handler: (state: State, payload: P) => State) => { type: T, payload: P }
>>

declare function createReducer<
  State, Handlers: {[key:string]: (state: State, action: *) => State}
>(actionHandlers: Handlers): (state: State, action: Action<State, Handlers>) => State;

const red = createReducer({
  inc: (state: number, payload: number) => state + payload,
  setStr: (state, payload: string) => parseInt(payload)
});

red(5, { type: 'inc', payload: 5 }) // shouldn't be error

red(5, { type: 'inc', payload: '5' }) // shouldn't be error

red(5, { type: 'unc', payload: 5 }) // shoudl be error un 'type'
```

**Comment by vkurchatkin** [comment]
Just to clarify: there is nothing unsound about `$Values` itself, it is unsound to make `Object.values` return `$Values` of inexact object

**Comment by freddi301** [comment]
So where is the problem of implementing $Values? At least for object literals

**Comment by vkurchatkin** [comment]
I don't think that there is a problem. As you can see, you can even implement it yourself

**Comment by freddi301** [comment]
Yes you can implement It in userland but cant use resulting type sa you can
see in the example

Il Mer 12 Apr 2017 14:04 Vladimir Kurchatkin <notifications@github.com> ha
scritto:

**Comment by billschaller** [comment]
Duplicates #2174
