### ISSUE TITLE
Correct way to type React events

### ISSUE THREAD

**Issue by gcazaciuc** [facebook/flow#368]
I have the following code:

 handleChange: function(event:SyntheticEvent): void {
         var el = event.target;
         this.props.setNewLanguage(el.value);
    }

Can you please advise on the correct way of typing this function so that it doesn't throw a type error accessing el.value.

I've found that using an union type works var el:HTMLInputElement|EventTarget but I'm not convinced that this is the correct way to type it. 
Typing it as only var el:HTMLInputElement = event.target throws a type error.

**Comment by samwgoldman** [comment]
You could cast `event.target` to be a `HTMLInputElement` or you could do a [dynamic type test](http://flowtype.org/docs/dynamic-type-tests.html), also called a type refinement to see if `event.target` is-a `HTMLInputElement` and handle the else clause as an error.

**Comment by gcazaciuc** [comment]
Thank you very much for the suggestions. Using dynamic type test makes sense to me but  I'm not quite clear  on how to do the cast( and haven't found a suggestion in the docs).

**Comment by samwgoldman** [comment]
Turns out I was wrong about casting (there's a blog post describing it). Dynamic type test is the way to go, IMO.

**Comment by samwgoldman** [comment]
@gcazaciuc are you still having this issue?

**Comment by gcazaciuc** [comment]
It was resolved by checking if the event.target is instanceof HTMLElement before accesing data on it. It seems like flow is smart enough to detect than inside that if statement event.target must be of type HTMLElement. Thanks for your support( and looking forward for let/const in flow :)  )

**Comment by rosskevin** [comment]
Relates to #218 

I'd hate to have to sprinkle this dynamic type test code into every event handler:

```javascript
function myEventHandler(e: Event) {
  // We only know that e.target is an EventTarget
  e.target.value;
  if (e.target instanceof HTMLInputElement) {
    // Now we know it's an <input />, with a `value` property.
    businessLogic(e.target.value);
  } else {
    // error handling
  }
}
```

Is there a way I can define my own `type` that extends `Event` and sets a static expectation of `HTMLInputElement`?

**Comment by rosskevin** [comment]
Here is my current dynamic polymorphic method hack to shorten up usage:

```javascript
// events.js
export function target<E> (e:Event, t:E):E {
  if (e.target instanceof E) {
    // Now we know it's an <input />, with a `value` property.
    return e.target
  } else {
    throw new Error(`Expected Event target to be ${E} but found ${typeof e.target}`)
  }
}
```

Called like:
```javascript
import Events from '../../../utils/events'
Events.target(e, HTMLInputElement).checked
```

This appears to work.  More convenience methods could be added in events.js to shorten it further.

**Comment by gnoff** [comment]
@rosskevin have you tried this in flow 0.32? It doesn't seem to work for me, confirming here, this is the same error I get locally running 0.32: 

https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sx8BDAJwHMBTfAHgFEA+MACloC4mA3W7PgA0ZHgEoeYAN6owYQlA60AdBRr152AM4U8tOIvxjpsuWGDAwAOURgEtMAGtstwvgDkWsOVINC2AAdMfHMWEQQ3AAtvMAADXnIYTFpYsADKOADaSnwAT2VTOUp6TEpSFTU6fFMAXzBaGC0HGTMySIykbFokJkoMynZYpgAPLIJaABMwPgEQyo18ODAAIwcAEil8OuXgsCg4HCmNvKyDetUqKprYsVrUGvQMHAJiUiqANUTkgDEMgFsACqXeicfiCLjTMFGExFEplMjA-Cg2YiAASAIAsgAZACSgWCTBgtD+szEygSSVo9yAA

**Comment by rosskevin** [comment]
@gnoff what I found out after writing that is that the second param must be available at runtime.  If the second param is just a declared type for flow, it will error at runtime.  I double checked and the code I had originally needed this code was refactored, so as of late I am not using it.

**Comment by rosskevin** [comment]
@gnoff this was my latest bit of code I used in this manner, it's a bit more paranoid:

```javascript
export default function coerce<E>(o: any, t: E): E {
  if (t === undefined) {
    throw new Error('Type given is undefined, it must be available at runtime.  ' +
      `Did you pass in a flow-only type? Arguments: (${o}, ${t})`);
  }

  if (o instanceof t) {
    return o;
  } else {
    throw new Error(`${typeof o} was not expected.`);  // remember we don't have the type at runtime
  }
}
```

**Comment by vincaslt** [comment]
For anyone stumbling on this issue, there is a clean way of achieving this now:

```
_onTextChange = ({ target }: SyntheticInputEvent) => {
  this.setState({ text: target.value })
}
```

**Comment by jakewtaylor** [comment]
This must have changed again since @vincaslt's post - the `SyntheticInputEvent` type is now a parameterized generic type (I think that's the right terminology):

```JSX
type Props = {};
type State = { value: string };

class MyInput extends React.Component<Props, State> {
    state = { value: '' };

    handleChange = (e: SyntheticInputEvent<HTMLInputElement>) => {
        const { value } = e.target;
        this.setState({ value });
    }

    render () {
        return (
            <input
                type="text"
                value={this.state.value}
                onChange={this.handleChange}
            />
        );
    }
}
```

**Comment by stevematdavies** [comment]
```
const clickHandler = (e: SyntheticEvent<HTMLInputElement>)  => { 
    e.preventDefault()
}

```
`Uncaught TypeError: e.preventDefault is not a function`

**Comment by slushman** [comment]
I specified preventDefault as a Function within the event object:

```
const clickHandler = (e: { 
    preventDefault: Function
}) => {
    e.preventDefault() 
}
```

You could also create an event object type and specify that e is that type of object:

```
type eventObject = {
    preventDefault: Function,
};

const clickHandler = (e: eventObject) => {
    e.preventDefault() 
}
```

At least, both of those worked for me.
