### ISSUE TITLE
Spreading a type marks the type's properties as possibly undefined

### ISSUE THREAD

**Issue by tgriesser** [facebook/flow#3681]
Not sure if I'm misunderstanding the intended behavior here, but I thought this would work:

```js
/* @flow */

type x = {
   a(): Promise<any>
};

type y = {
   ...x
}

function foo(x: y) {
  return x.a()
}
```

```js
12:   return x.a()             ^ call of method `a`. Function cannot be called on possibly undefined value
4:    a(): Promise<any>      ^ undefined
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAeYAvGAN6pjUCGAFAJQBcYACgE5wC2AlgM54APDQB2WAHyoAvgG502fGCykKVagDpNhaeigBXEQGMMPOCLBQ4cOoRZYGq6uzwY97c4XX0GOoA

**Comment by tgriesser** [comment]
Nevermind, just saw https://github.com/facebook/flow/issues/3666 - will wait for docs here

**Comment by vkurchatkin** [comment]
The fix is to wrap all spreads with `$Exact` like this:

```js
type y = {
   ...$Exact<x>
}
```
