### ISSUE TITLE
generic functions

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#3684]
Should Flow report an error for the last line below because the arguments are not the same type?
```js
// @flow
function printPair<T>(p1: T, p2: T): void {
  console.log(`${String(p1)} and ${String(p2)}`);
}
printPair('one', 2);
```

**Comment by vkurchatkin** [comment]
No, it should. Flow infers that `T` is `string | number`

**Comment by mvolkmann** [comment]
How do I tell it that I want both arguments to be the same type?

**Comment by vkurchatkin** [comment]
You can't. I understand what you mean, but it's even hard to describe it formally. In your example arguments ARE of the same type, technically.

**Comment by madbence** [comment]
imho something like this should bind `T` to `string`, but flow is complaining:

```js
function printPair<T>(p1: T, p2: T): void {
  console.log(`${String(p1)} and ${String(p2)}`);
}
type PairPrinter = typeof printPair;

(printPair: PairPrinter<string>)('one', 2);
```

https://flow.org/try/#0GYVwdgxgLglg9mABABwE4zFACgQxqgHgBUA+ACmQEYAuRIgGhQCZaiBKWgNzhgBNEA3gChEiCAgDOcADYBTAHTS4AczIADACQCAylHRhVVNgF9EOMPy279hpibVsA3EONCoAT2SzEufFn1QsqiIALyIHl5wwCgBvqjOQhSxeKi0cf4YgYQSehjKJGxkAOQIskWMdo5AA

**Comment by vkurchatkin** [comment]
Polymorphic functions and generic function types are not this same:

```js
type A = <T>(T) => void; // polymorphic function
type B<T> = (T) => void; // generic type
```

**Comment by madbence** [comment]
oh, you're right 😺 , then this will do the trick:

```js
function printPair<T>(p1: T, p2: T): void {
  console.log(`${String(p1)} and ${String(p2)}`);
}
type PairPrinter<T> = (T, T) => void;

(printPair: PairPrinter<string>)('one', 2);
```

```
6: (printPair: PairPrinter<string>)('one', 2);
                                           ^ number. This type is incompatible with the expected param type of
6: (printPair: PairPrinter<string>)('one', 2);
                           ^ string
```

https://flow.org/try/#0GYVwdgxgLglg9mABABwE4zFACgQxqgHgBUA+ACmQEYAuRIgGhQCZaiBKWgNzhgBNEA3gChEiCAgDOcADYBTAHTS4AczIADACQCAylHRhVVNgF9EOMPy279hpibVsA3EONCoAT2SzEufFn1QsoSkiAC8iGQMdGxhJIjcfM5CFAG+qLRp-hiBhBJ6GMokbGQA5AiyJYx2jkA
