### ISSUE TITLE
Named import from module `react` This module has no named export called `Component`.

### ISSUE THREAD

**Issue by neurosnap** [facebook/flow#3685]
Is there a way to get around this warning?

```js
import { Component } from 'react';

class Something extends Component {}
```

Named import from module `react` This module has no named export called `Component`.

**Comment by keplersj** [comment]
After updating I'm getting this on the latest flow `flow-bin` as well

**Comment by keplersj** [comment]
Hmm... I attempted downgrading Flow to see if this is truly a regression and it doesn't look to be. The issue emerged during a transition from Meteor to next.js.

**Comment by nmn** [comment]
Cannot reproduce: [LINK](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeAwnDnAHalsEC+YUeLMAHI8FakIDcqVJRjkAzvLAANMKQAeBTgBMlzVhy4AeAG5x02uvW50zFgHwNUYMKLbbSeABQBKBt1RuIA)

**Comment by keplersj** [comment]
Issue disappears when all libdefs installed with `flow-typed` are removed. Looking for the troublesome libdef right now.

**Comment by keplersj** [comment]
The new `styled-components` libdef (added in flowtype/flow-typed#745) would appear to be causing the issue for me.

**Comment by keplersj** [comment]
The issue come from the next.js libdef from `flow-typed`. The libdef has a `import type { Component } from 'react';` outside of a `declare module` block. The messes up the type checker in a major nearly untraceable way.

**Comment by jsg2021** [comment]
`Component` is not a named export of react. It is a property on the default export... transpilers allow this to work for commonjs modules because of their interop, but it's technically incorrect.

**Comment by neurosnap** [comment]
My issue was a libdef like @keplersj suggested.

**Comment by zachariahtimothy** [comment]
I too had this issue on a next.js project as @keplersj  mentioned. I downgraded to flow-bin@^0.53.0 and the trouble is gone as done in the [este](https://github.com/este/este/blob/master/package.json) project.
