### ISSUE TITLE
"try flow" is broken with latest (default) version v0.43.1

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#3686]
Like same issue as https://github.com/facebook/flow/issues/3647

**Comment by bvaughn** [comment]
FWIW manually selecting v0.43.0 fixes the repl. Still lots of console errors though, and deep links don't work (since they default to v0.43.1)

**Comment by nmote** [comment]
This is fixed now. Same cause as #3647, but the fix wasn't cherry picked onto the 0.43 release branch so the same problem occurred with the 0.43.1 release. @mroch manually uploaded and the proper fix is in master so future releases should be deployed automatically.
