### ISSUE TITLE
No entry for `Object.prototype.toString` in lib/core.js

### ISSUE THREAD

**Issue by bolinfest** [facebook/flow#369]
In fact, there is no mention of `toString` anywhere in lib/core.js. Is there any reason why it's omitted? If so, it would be good to document it in there.

I don't believe this is related to https://github.com/facebook/flow/issues/244.

**Comment by samwgoldman** [comment]
@bolinfest What specific issue are you having using toString? It might not be in lib/core.js, but can you provide an example where flow doesn't type check actual JS as you expect?

**Comment by mroch** [comment]
Closed by https://github.com/facebook/flow/commit/945caad4ec203cafd096f08a7d5d40ad0d36b8c0
