### ISSUE TITLE
Event returnValue not found

### ISSUE THREAD

**Issue by lizzzp1** [facebook/flow#3690]
event.returnValue = false;
             ^^^^^^^^^^^ property `returnValue`. Property not found in
 event.returnValue = false;
       ^^^^^ Event

**Comment by madbence** [comment]
you should use `event.preventDefault()` instead of this [deprecated feature](https://developer.mozilla.org/en-US/docs/Web/API/Event/returnValue).

**Comment by lizzzp1** [comment]
Got it. Thanks
