### ISSUE TITLE
All of the Math methods take strings

### ISSUE THREAD

**Issue by benderTheCrime** [facebook/flow#3691]
I'm not exactly sure how far this goes back in terms of flow versions. Currently, I'm using 0.41.0. It looks like none of the Math methods are configured to take strings.

```bash
 10:     [key: string]: (...args: Array<string>) => number,
                                        ^^^^^^ string. This type is incompatible with
169:     pow(x: number, y: number): number;
                           ^^^^^^ number. See lib: /private/tmp/flow/flowlib_cbd137c/core.js:169
```

**Comment by vkurchatkin** [comment]
Well, obviously `Math` is supposed to be used only with numbers, so this makes sense

**Comment by benderTheCrime** [comment]
If Math was _obviously_ meant to only be used with numbers, then why do the Methods work with strings. All of them, given numbers or strings, perform a Math operation and return a number. 

This somewhat raises an interesting question: Is the purpose of the core library to type methods on JavaScript primordial objects in the manner which the team believes those methods should be used or to type those methods based on the types of the arguments they actually take and values they return?

**Comment by vkurchatkin** [comment]
> If Math was obviously meant to only be used with numbers, then why do the Methods work with strings?

Because that's the javascript way. `'3' * '4'` also works, but you shouldn't do this.

>  Is the purpose of the core library to type methods on JavaScript primordial objects in the manner which the team believes those methods should be used or to type those methods based on the types of the arguments they actually take and values they return?

It's definitely the former. One could argue that all functions is javascript work with arbitrary arguments, so the latter wouldn't be useful.

**Comment by benderTheCrime** [comment]
I mean that's just the way that the operator behaves. I would expect that any program used to statically analyze the JavaScript for `"1" + "2"` would also understand that the "+" operator treats strings preferentially as well, but if I give it two numeric operands, the result will be a number. 

Your example also works with either strings or numbers, which is why I would expect if someone had a method that performed that expression they would have to type the inputs either explicitly as strings or as numbers or some union of both types and still yield numeric results.

Your answer is perfectly fine if it is the choice of the maintainers of flow is to explicitly prohibit the use of certain methods given some arguments and only allow them in the ways that are prescribed by the core type library, but it's technically incorrect (the best kind of incorrect) as that method does indeed take other types.

It's tantamount to determining that `Array.prototype.concat` should only take array-like arguments despite the fact that it will take any argument.

**Comment by nmn** [comment]
Something working is not the same as it being type-safe.
