### ISSUE TITLE
Export x from './y' results in unexpected identifier error

### ISSUE THREAD

**Issue by 0x80** [facebook/flow#3706]
If I write something like `export a from './a'` Flow gives me `Unexpected identifier`. Same if I write

```javascript
import a from './a'
export a
```

Can I work around this? 

I'm using 0.43

**Comment by 0x80** [comment]
I have since learned that export `export a from './a'` is sugar for `export {default as a} from './a'`. Flow understands this, so that solves it for me.

Still the new syntax should be supported at some point, if the proposal is mature enough. 

And the fact that Flow trips over 
```
import a from './a'
export a
```
 stil makes it a bug I suspect

**Comment by Ai01** [comment]
l meet this problem too.Did you find some solutions ?@0x80

**Comment by 0x80** [comment]
@Ai01 for me the solution was to write `export {default as a} from './a'`. So without the shorthand syntax. I haven't tried the other syntax since.

**Comment by Ai01** [comment]
@0x80 l know. thank you very much.

**Comment by Ai01** [comment]
is this a bug or not?

**Comment by 0x80** [comment]
If there are multiple valid ways of writing the same thing and one is resulting in a type error then I'd consider this a bug yes. But I don't think the sugar syntax made it into the official standard yet, so in that sense it's simply not supported yet I assume.

**Comment by TrySound** [comment]
It's not a bug guys. Just invalid syntax
```js
import a from './a.js';

export {
  a
};
export const b = a;
export default a;
```
http://2ality.com/2014/09/es6-modules-final.html
