### ISSUE TITLE
Missing props error in React component points to definition instead of instance

### ISSUE THREAD

**Issue by 0x80** [facebook/flow#3707]
Considering the following React component:

```javascript
/* @flow */
import React from 'react'

type Props = {
  msg: string
};

const A = (props: Props) => {
  return (
    <div>
      A says: {props.msg}
    </div>
  )
}

export default A
```

If you instantiate the component without props, like `<A/>`, you get an error in the component source file underlining `(props: Props)` and stating: `[flow] property `msg` (Property not found in props of React element `A` See also: React element `A`)`. 

I find this confusing because the error doesn't point to the instance of A but the source file. For a while I thought I was defining the Props type wrongly. The file using the instance of `<A/>` wrongly doesn't show any error.

**Comment by mouton-rebelle** [comment]
Just lost 1h on that one. 
Gonna go back to PropTypes for now

**Comment by FezVrasta** [comment]
What's the solution then?

**Comment by mouton-rebelle** [comment]
I have now idea how Flow works and how difficult it is to achieve, but the errors should pop where the component is instancied, not on the component declaration

**Comment by AugustinLF** [comment]
The file underlined in your text editor is indeed the wrong one, however, if you run `flow` in your console, you'll get a more precise error message, which also indicates where the component is wrongly instantiated.

**Comment by koskh** [comment]
I have this problem in last Webstorm 2017.2 Errors appear on definition file.
In prev version (2017.1.4) errors are in right place (on editor page of in instance file)

so I use prev version

**Comment by charlie-axsy** [comment]
As mentioned above, this is an IDE problem.  The Flow binary is outputting a descriptive error to the console but it is being misinterpreted by the IDE.

**Comment by SpearThruster** [comment]
Yep wasted 1 hour on this as well...

**Comment by cdomigan** [comment]
Here's the WebStorm ticket:
https://youtrack.jetbrains.com/issue/WEB-28062

**Comment by SamChou19815** [comment]
The issue is probably fixed a long time ago
