### ISSUE TITLE
feature request: way to just ignore certain imports rather than mapping them to empty module

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#3709]
So #345 was marked closed, but I don't think the solution is really ideal.

This feels like a hack:
```
module.name_mapper='^\.sass' -> 'empty/object'
```
Moreover, I don't want to have to depend on `empty`, or have a silly empty module in my project, just to prevent flow from erroring on sass imports.  How about if we could just do
```
module.ignore='^\.sass'
```
and it would ignore imports ending in `.sass` altogether?

**Comment by nmn** [comment]
You can use the name_mapper and just add a line to your [lib] files. You don't have to use an empty module.

**Comment by jedwards1211** [comment]
What would I add to the [lib] section?  I thought that has to refer to modules on disk.

I'd say it should treat the exports of an ignored module as `any`, so that it causes no problems. Would not be impossible to use.  If users wanted more specific typing, they could use `name_mapper`.  Besides, I would only use this for cases like
```js
import './styles.sass'
```
Where I'm not using the exports of the module anyway.

**Comment by nmn** [comment]
You can add a module definition for any module in your [lib] section. Flow will use that even if you don't have an actual file for it.
