### ISSUE TITLE
Static properties do not inherit into derived classes

### ISSUE THREAD

**Issue by popham** [facebook/flow#371]
The following typechecks without error:

```
class X {
  static A: number;
}
X.A = 5;

class Y extends X {
  static A: string;
}
Y.A = "asdf";
```

Based on http://www.2ality.com/2015/02/es6-classes-final.html#prototype_chains, I expect the `A` declaration from X to inherit into Y.  From ES6's release candidate 3, `14.5.14 Runtime Semantics: ClassDefinitionEvaluation`:

* Let `superclass` be the result of evaluating `ClassHeritage`.
* Let `constructorParent` be `superclass`.
* Let `constructorInfo` be the result of performing DefineMethod for `constructor` with arguments `proto` and `constructorParent` as the optional `functionPrototype` argument.
* Let `F` be `constructorInfo.[[closure]]`.
* return `F`.

**Comment by avikchaudhuri** [comment]
This has been fixed, closing.

**Comment by idris** [comment]
@avikchaudhuri I'm having a similar issue, but using `declare class` instead of just `class`.  Was this fixed for `declare class` as well?  It seems statics are not being inherited when using `extends`
