### ISSUE TITLE
$Shape does not preserve covariance

### ISSUE THREAD

**Issue by ForbesLindesay** [facebook/flow#3713]
e.g.

```js
/* @flow */

type State= {+foo: number};
function setState(state: $Shape<State>) {
}
setState(({foo: 10}: State));
```

produces the error:

```
4: function setState(state: $Shape<State>) {
                                   ^ object type. Covariant property `foo` incompatible with contravariant use in
4: function setState(state: $Shape<State>) {
                                   ^ State
```

Even though all usage of the `foo` property is covariant.

**Comment by nmn** [comment]
$Shape is an experimental feature for very specific use-cases.

**Comment by ForbesLindesay** [comment]
Yes, but it's used internally by React, so this prevents you marking parts of your state as co-variant.  I get that `$Shape` is only for special use cases, but the inconsistencies when using things like `$Shape<T>, `$Exact<T>` and `ReactClass<T>` are causing a lot of pain for me.  It's death from a thousand cuts.  I get that they each seem low-priority, but collectively they have a big impact on the developer experience.

**Comment by TrySound** [comment]
Seems like fixed
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhngLxgDeA1FHHAFxgB2ArgLYBGeATgF8A3KijtWAYwwBLOKzABnPBmJk8ACgWlyLACSEAFiXwAeVeQB8AShqoBqJSu0b11BszABGAAwCW5vCsrISA
