### ISSUE TITLE
Different result with/without an intermediary variable

### ISSUE THREAD

**Issue by julienw** [facebook/flow#3715]
With the following code, you'll see a result will be different depending on whether we use an intermediary variable or not. The intermediary variable itself doesn't seem much linked to the actual error.

```javascript
/* @flow */

function getSet(): Set<string> {
  return new Set();
}

type Node = {
  thing: string | null,
};

const node: Node = { thing: "thing" };

if (node.thing !== null) {
  let result = getSet().has(node.thing); // error (incorrect)
}

// But:
const mySet = getSet();
if (node.thing !== null) {
  let result = mySet.has(node.thing); // no error ! (correct)
}
let result = mySet.has(node.thing); // error (correct)
```
[You can try live online](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBzAU3wGUqAKASgC4xb8AeAZ3wCdDsyAPjABvVGDA8qmHqWwUkbRgG5UAX3T4AngAcKYAHJwAJvoC8o8WHwALfmRbc+AsAB8w2TDBgAadatRcEm4PEwoWI1MwCxFrOwEWACJbe0SwNQDCKDA6bDCAOhSXAEIzC09vBksASBgqSQpOL3xo8iolBnybAENOXIKisgZlMGBgMAoeHjgeHP4gqYoCBnV0MbAAIUx8JkDgloBbLTZWyhp6YdQsnLzTQviyMFLyrxgqsVr6qSaYFosjthdXr9O6DYajcZ5CZTGZPHILKTLVZ1FrfZqtAFUIF9W4Ue72cHrSbTWZ0BFLfArIA).

**Comment by vkurchatkin** [comment]
That's by design. `getSet()` could mutate `node`, so refinement is invalidated

**Comment by julienw** [comment]
I see; is it something difficult to statically catch ?
