### ISSUE TITLE
No error when referencing an invalid union type in an if statement

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#3717]
I expect this if statement to trigger an error since `'disabled'` is not a possible value for `info.status` but it runs without any errors:

````js
type Info = {|
  status: 'on' | 'off',
|}

const info: Info = {status: 'on'};

if (info.status === 'disabled') {
  console.log('The thing is disabled');
}
````

Curiously, if I add the following code, it triggers an error as expected:
````js
function setStatus(status: $PropertyType<Info, 'status'>) {
  console.log('about to set status:', status);
}

setStatus('disabled');
````
````
index.js:17
 17: setStatus('disabled');
               ^^^^^^^^^^ string. This type is incompatible with the expected param type of
 13: function setStatus(status: $PropertyType<Info, 'status'>) {
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string enum
````
Am I misunderstanding the Union type? I checked the if statement with `flow type-at-pos` and it is correctly following the `Info` type.

I am using flow **0.43.1**

**Comment by madbence** [comment]
afaik the goal of flow is to catch possible runtime errors earlier, so i guess it's totally fine compare `info.status` with `'disabled'`. fyi you can enforce typechecking with this (yeah, it looks ugly...):

```js
if (info.status === ('disabled': $PropertyType<Info, 'status'>)) {
  console.log('The thing is disabled');
}
```

**Comment by Brianzchen** [comment]
This is indeed a bug as the code is unsound. But is has now been fixed and correctly throws errors
