### ISSUE TITLE
const/let support not working 

### ISSUE THREAD

**Issue by reichert621** [facebook/flow#3718]
I'm a bit confused because I'm using the latest version of `flow-bin` and the docs say that `const` and `let` are supported, but when I run `flow` I'm getting `Unsupported variable declaration` errors.

My setup:

`package.json`
```json
{
  "name": "flow",
  "version": "1.0.0",
  "main": "index.js",
  "devDependencies": {
    "flow-bin": "^0.43.1"
  }
}
```

`.flowconfig`
```
[ignore]

[include]

[libs]

[options]
```
`index.js`
```javascript
// @flow
const str = 'Hello world!';
```
Output:
```
$ flow

/src/index.js:2:1,27:
Unsupported variable declaration: const

/src/index.js:2:7,9: var str
Could not resolve name

Found 2 errors
```
I feel like I'm probably just missing something super obvious, but right now I'm stumped 😞

**Comment by madbence** [comment]
are you sure that that the `flow` binary is `0.43.1`? usually, the stuff you install locally is not available in your shell `PATH`, so maybe you are using a globally installed (older) version?

**Comment by reichert621** [comment]
My god I'm an idiot. Must've installed it globally a while back and forgot about it...
```
$ flow --version
Flow, a static type checker for JavaScript, version 0.14.0
$ node_modules/.bin/flow --version
Flow, a static type checker for JavaScript, version 0.43.1
```
Thanks @madbence!
