### ISSUE TITLE
gelf.h: No such file or directory

### ISSUE THREAD

**Issue by Raynos** [facebook/flow#372]
`flow` needs more then just `opam` to compile.

I tried installing `opam` and running `make`; looks like I need a gelf.h file.

I can install `libelf-dev` to  work around this. Can we update the README to mention this edge case ?

As a seperate question, why does a javascript type checker need to read elf files ? It's probably for this `hack` IDE support stuff.

**Comment by popham** [comment]
For part 2, the `elf` dependence allows the library tarball to be bundled into the executable.  This line from the Makefile does the deed:

```
objcopy --add-section flowlib=bin/flowlib.tar.gz _build/src/flow.native bin/flow
```

I don't know if there's anything else going on with `elf`.

**Comment by gabelevi** [comment]
I've removed the libelf dependency, so I'm going to close this task out.
