### ISSUE TITLE
Did not raise an error if it didn't match the disjoint union

### ISSUE THREAD

**Issue by xareelee** [facebook/flow#3720]
A disjoint union `Action` is declared. When using `if ... else ...` for the disjoint union, it did not raise an error if it didn't match the disjoint union definition.

```js
// @flow

type UserData = {|
  username: string
|};

type Action =
  | {| type: 'LOGIN', payload: UserData |}
  | {| type: 'LOGOUT' |}
  ;

function reduce(state: mixed, action: Action) {
  if (action.type === 'LOGINGG') {  // No this action.type. It should raise error.
    const userData = action.payload;
    console.log(userData.username);
    return state;
  }
  //...
}
```

The `if` block in the syntax `if (action.type === 'LOGINGG') {}` should never be executed, because the action type `LOGINGG` doesn't exist. I think Flow should tell this error.

**Comment by AugustinLF** [comment]
Yep, that's a known area of improvement, there are improvements to do about reachability, you'll also find this problem with a switch/case. See #2399 for instance.
