### ISSUE TITLE
Support prop-types module

### ISSUE THREAD

**Issue by milesj** [facebook/flow#3727]
Now that React `prop-types` are their own module, the current definitions do not work. I currently solve this with the following def in my project.

```
declare module 'prop-types' {
  import typeof { PropTypes } from 'react';

  declare export default PropTypes;
}
```

**Comment by samwgoldman** [comment]
We're adding definitions to flow-typed: https://github.com/flowtype/flow-typed/pull/773

In the mean time, you can use those definitions in your own project. We made sure to have Flow support for prop-types and createClass before the React team deprecated them :)

**Comment by milesj** [comment]
Awesome, thanks for the link!

**Comment by slorenzo** [comment]
I'm using Flow 0.44.1 and React 15.5.4.
In the console appear the following warning

> Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Is there any way to avoid this warning?

**Comment by milesj** [comment]
@slorenzo Migrate to the new `prop-types` module? https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.proptypes

**Comment by slorenzo** [comment]
@milesj I installed this new `prop-types` module.
But I don't know how I can use this module because I use the "Flow way" to add my `props`.

For example:
```
 /* @flow */

import React, { Component } from 'react';
import PropTypes from 'prop-types';

type Props = {
  foo: string,
};

type State = {
  text: string,
};

class myApp extends Component {
  static defaultProps = {
    foo: 'bar'
  }
  props: Props;
  state: State;

  constructor(): void {
    super();
    this.state = {
      text: 'Hello world'
    };
  }

  render() {
    return (
      <h2>{this.state.text}</h2>
    );
  }
}
```

In this way, the warning still appears.

**Comment by milesj** [comment]
Some dependency you use probably hasn't migrated yet.

**Comment by yocharitha** [comment]
Installed flow-typed with `yarn flow-typed install` but prop-types didn't get installed automatically inside the flow-typed folder. So I explicitly installed propptype with `yarn flow-typed install prop-types@15.7.2`. now it works fine
