### ISSUE TITLE
JSON.stringify may also be undefined

### ISSUE THREAD

**Issue by xjamundx** [facebook/flow#3729]
```
> JSON.stringify(undefined)
undefined     
```

But in flow I can do this:
```
var y: string = JSON.stringify(undefined)
```
Which will make `y` as `undefined` which is too bad.

**Comment by deecewan** [comment]
As an aside, this seems like weird behaviour, right?

```
> JSON.stringify(undefined)    
< undefined
> JSON.stringify()    
< undefined
> JSON.stringify(null) 
< "null"
```

I'd probably expect it to be an empty string, I guess.

**Comment by goodmind** [comment]
Fixed by https://github.com/facebook/flow/pull/7447
