### ISSUE TITLE
"flow find-refs" only for one file?

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#3730]
If I run `flow find-refs some-file-path some-line-number some-column-number` where that refers to the name in the definition of an exported function, shouldn't it find all references to that function in all files in my application? It seems to only find references in that one file.

**Comment by philippotto** [comment]
I'm also interested in this. This would be very useful for tooling.

**Comment by gopar** [comment]
There's a beta flag for that out already `--global` (read from #2398 ) 
But sadly isn't that robust yet :(

Looking forward this as well \o/

**Comment by nmote** [comment]
Yes, please use the `--global` flag for this. There are still a few known issues but it should be fairly usable, and I will continue to improve it over the course of the next few months.
