### ISSUE TITLE
Command failed with exit code 2 when having nock as dependency

### ISSUE THREAD

**Issue by emilbaekdahl** [facebook/flow#3739]
So when I have `nock` as a dependency and run `flow` I get the following
```
node_modules/nock/node_modules/changelog/examples/node.json:2
  2: ==========
        ^^^ Unexpected token ===


Found 1 error
error Command failed with exit code 2.
```
If I remove `nock`, everything works fine.

**Comment by nmote** [comment]
Looks like they ship with a JSON file that has a syntax error in it. I recommend that you use flow-typed for this module, rather than having Flow try to do its best with what is in `node_modules`:

https://github.com/flowtype/flow-typed
