### ISSUE TITLE
Adding a token to the lexer causes a very large memory leak.

### ISSUE THREAD

**Issue by Raynos** [facebook/flow#374]
I'm trying to add a feature to flow in a branch that's adding a new token to the lexer. This looks like

``` diff
diff --git a/src/parser/lexer_flow.mll b/src/parser/lexer_flow.mll
index c2d5c55..d3ace25 100644
--- a/src/parser/lexer_flow.mll
+++ b/src/parser/lexer_flow.mll
@@ -76,6 +76,7 @@
     | T_YIELD
     | T_DEBUGGER
     | T_DECLARE
+    | T_CONSTRUCTOR
     | T_TYPE
     (* Operators *)
     | T_RSHIFT3_ASSIGN
@@ -212,6 +213,7 @@
     | T_YIELD -> "yield"
     | T_DEBUGGER -> "debugger"
     | T_DECLARE -> "declare"
+    | T_CONSTRUCTOR -> "constructor"
     | T_TYPE -> "type"
     | T_LCURLY -> "{"
     | T_RCURLY -> "}"
@@ -490,6 +492,7 @@
       "yield", T_YIELD;
       "debugger", T_DEBUGGER;
       "declare", T_DECLARE;
+      "constructor", T_CONSTRUCTOR;
       "type", T_TYPE;
     ]
   let _ = List.iter (fun (key, token) -> Hashtbl.add type_keywords key token)
```

I was suprised that when i ran my local flow binary against a test program that the flow binary was stuck at 100% CPU.

I was even more suprised that it caused the flow binary to leak 100s of MB per second.

I'm pretty sure it's a bug for me to add a lexing token and then not handle it in the match statements in the parser but i'm suprised that it causes flow to run out of memory. What's even worse is that my laptop quickly freezes as flow takes up all the memory on my laptop.

**Comment by gkz** [comment]
Let us know if you're still having this problem.
