### ISSUE TITLE
Clarify that Boolean(x) and new Boolean(x) are different types

### ISSUE THREAD

**Issue by k15a** [facebook/flow#3748]
In the [documentation](https://flow.org/en/docs/types/primitives/) it's not clear that `Boolean(x)` and `new Boolean(x)` are of different types. This is true for every primitive constructor.

I think it should be clarified that this is the way primitive types work:
```JS
const bool: boolean = Boolean(true)
const Bool: Boolean = new Boolean(true)
```

I am happy to send a PR to add some more examples.

**Comment by vkurchatkin** [comment]
This has nothing to do with Flow, this is just how JS works

**Comment by k15a** [comment]
Yeah I know that this is JS behaviour. In my opinion the following lines can confuse users who doesn't know the fact that `Boolean(x)` and `new Boolean(x)` behave differently.

> A `boolean` is a literal value like `true` or `false` or the result of an expression like `a === b`.
A `Boolean` is a wrapper object created by the global `Boolean(x)` constructor.

I think something like this could prevent some confusion.

> A `boolean` is a literal value like `true` or `false`, the result of the `Boolean(x)` function or the result of an expression like `a === b`.
A `Boolean` is a wrapper object created by the global `new Boolean(x)` constructor.

**Comment by vkurchatkin** [comment]
Agreed, `Boolean(x)` is a bit confusing here
