### ISSUE TITLE
Null-only type annotation

### ISSUE THREAD

**Issue by popham** [facebook/flow#375]
I've got a generic class that I want to parametrize by `null`:

```
class List<T> {
  get(index: uint32): T {  throw new Error("Not implemented"); }
  // Map, For Each, Reduce, etc. (`core/lib`'s `Array` analogues)
}
```

```
class NullList extends List<null> { // NG
  get(index) {
    if (this.isOutside(index)) throw new RangeError();
    return null;
  }
}
```

I'll grant that the `NullList` is a boring edge case.  For now I'm vacillating between a `NullList` implementation with `T=void` + `return undefined` and defering to the base class's `get`.  Have I missed a mechanism to specify a null-only type?

**Comment by samwgoldman** [comment]
This seems like a decent beginner bug to me, but I'm curious why `T=void` + `return` is insufficient. It seems more idiomatic to me.

**Comment by popham** [comment]
Just my particular brand of OCD.

It's for [a serialization protocol](https://capnproto.org/language.html#built-in-types) that provides a Void type.  The protocol includes "List(Void)" which has a length.  When I get a member from such a list, the value is fixed as Void, not uninitialized.  In my mind, this implies that the type is `null`, not `undefined`.  (I could remove getters and setters from "List(Void)", but I want the API to mirror the C++ API as close as possible and it has Void getters and setters.)

**Comment by popham** [comment]
I was hoping for a signal whether this is a missing feature or somebody's darling design decision.  I dislike the `?number` syntax for `maybe` types, especially when mixed with the optional-function-parameter syntax--I would prefer `number | null` if the syntax were supported.

Does a type `null` offend somebody with veto authority?  If not, then

* Should the type algebra admit `number | null`?
* Should `type NullT = ?number & ?string` yield the equivalent to type `null`?  I tried this as a workaround, but it didn't work.
