### ISSUE TITLE
Upgrading from 0.44.0 to 0.44.1 breaks Linux execution

### ISSUE THREAD

**Issue by EvNaverniouk** [facebook/flow#3753]
After upgrading from 0.44.0 to 0.44.1, all our Flowtype servers are failing to run on the Linux platform (no issues on Mac).

The error returned is:

```
Could not locate flowlib files
Could not start Flow server!
```

Rolling back to 0.44.0 makes the error go away.

**Comment by gabelevi** [comment]
After investigating, I found the linux build for v0.44.1 that TravisCI uploaded was for some reason a bad build. I uploaded a good build to the GitHub release page for v0.44.1 and published flow-bin@0.44.2, which contains the good build.

This should be resolved now, but if it isn't for anyone please re-open!

**Comment by EvNaverniouk** [comment]
Thanks 0.44.2 fixes the issue.

**Comment by kennethaa** [comment]
Can confirm the same.
