### ISSUE TITLE
Flow type checking within objects

### ISSUE THREAD

**Issue by RoHePu** [facebook/flow#3754]
Hi Flow Developer Team,

we love flow and we would like to use it in one of our web projects. Meanwhile our project is very big, so that we intend to introduce flow file by file. Adapting a small test file, we realized that flow seems to misunderstand the class definitions of the UI framework we use.
Most of our JavaScript files look like the following example:

```javascript
/** one of our ui elements **/
framework.ui.controller("some_unique_id", {
    foo: function() {
        this.bar("some string");
    },
      bar: function (n: number): number {
          return n * n;
    }
});
```

There is no library definition for the UI framework we use, thus I tried to define a small definition on my own:

```javascript
/* @flow */

/** library definition */
declare class framework{
    static ui : UI;
};

declare class UI{
  controller(bla : string, obj: {}): {};
};


/** one of our ui elements **/
framework.ui.controller("some_unique_id", {
    foo: function() {
        this.bar("some string");
    },
      bar: function (n: number): number {
          return n * n;
    }
});
```
The expected behavior we would like to see is that flow shows an error on line `this.bar("some string");` because `bar` is expecting a number. Unfortunately, flow shows no errors. Giving flow a plain function definition it points to the expected error:

```javascript
/* @flow */

/** using a plain function it shows an error message **/
function square(n: number): number {
  return n * n;
}

square("some string");
```

You can find a flow try link [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVpwwJYCMBOAhvgJ5gAmAplNgHbYAu2ctyaVAxjMZWF4QGcBYKEQC2lBHHwBrAN6owSsAIaEmHMAFdsYAFxgAqgEkA3KgC+51J275e-IUeMKlHFg3xwYMSvgAUuNz6Kp50AOYANGBwuABWBnIWAJSJVpbWGCDgLLxwUDFa+Nq6lL4StAzC2WiihBJSsgB0Ok3ulV4+fv4ARAJwEgD6WvQAjlqUg9jkPdGuylBwcAZQIxxMLP7JYPPKygwAFtgCTbjEvf0SofgRPcnmexaRintgZ-graxus-rQGtFoxLg-KkwACgX4di9Xsp7AwiqxWOBaA9lBZLPd0FisuAtAIImBCGAAA7cOgiL7MViMFQHRDCQisPxeYoSISEcK8GqoVa0dZUlTjHi-f6A4H4UHg8VQpRwhFg5Bg8zo1ACIX2C4DXiqG60cJ3UxAA).

Is there a way to get flow to do the type checking within the object?

Thank you for your Help :)
Robin

**Comment by mwalkerwells** [comment]
```js
/* @flow */

class FooBar {
  foo(): void {
    this.bar("some string")
  }
  bar(n: number): number {
    return n * n
  }
}

/** library definition */
declare class framework{
    static ui : UI
};

declare class UI{
  controller(bla : string, obj: FooBar): {}
};


/** one of our ui elements **/
framework.ui.controller("some_unique_id", new FooBar())
```

**Comment by RoHePu** [comment]
Oh thank you a lot! I will test it in the productive code immediately  :D
