### ISSUE TITLE
Subtyping issues

### ISSUE THREAD

**Issue by Ptival** [facebook/flow#376]
This might be related to #289 

```
/* @flow */

declare class Parent {
  get<T:Parent>(): T;
}

declare class Child extends Parent {
  get<T:Child>(): Child;
}

declare function f(c: Child): number;

var c = new Child();
var i : number = f(c.get());

var p = new Parent();
var j : number = f(p.get());
```

It would be nice if I could write the Child version of get without parameterizing over a type T since I am trying to specialize the polymorphic version into a monomorphic one. I understand this might be troublesome.

However, I'm also surprised that the j line is not flagged as incorrect.

**Comment by avikchaudhuri** [comment]
This will be fixed in an upcoming diff. The override should be incorrect, as you point out. The j line, however, is not incorrect. Parent#get is a magic method that can return any subtype of Parent, e.g. Child.
