### ISSUE TITLE
Confusing error message when combining async functions and Promise return types

### ISSUE THREAD

**Issue by danielalves** [facebook/flow#3762]
When declaring:
```js
function test() : Promise<number> {
  // Missing return statement
}
```
I get the following output:
```
 13: function test() : Promise<number> {
                       ^^^^^^^^^^^^^^^ Promise. This type is incompatible with an implicitly-returned undefined.
```
Which is kind of the default wrong return type error message. But, when I declare:
```js
// Just added the "async"
async function test() : Promise<number> {
  // Missing return statement
}
```
I get this:
```
 13: async function test() : Promise<number> {
                             ^^^^^^^^^^^^^^^ undefined. This type is incompatible with
 13: async function test() : Promise<number> {
                                     ^^^^^^ number
```
And that is the confusing message. Just by reading it, it looks like that Promises are not compatible with numbers (but, of course, they are) or that something is resolving to `undefined`. Finally, the issue above only happens with Promises, since using Arrays:
```js
async function test() : Array<number> {
  // Missing return statement
}
``` 
gets me the expected error message:
```
 13: async function test() : Array<number> {
                             ^^^^^^^^^^^^^ array type. This type is incompatible with an implicitly-returned Promise.
```

I don't know if this is intended, if I'm missing something or if this is in fact a bug, but I thought it would be worth noting anyway =)

I'm using flow version `0.44.1` on macOS Sierra.

**Comment by vkurchatkin** [comment]
This work as expected. When you omit return in async function it is equivalent to `Promise<void>`
