### ISSUE TITLE
No way to type module.exports = function in .js.flow files?

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#3764]
I have a `foo` package with a main module at `./src/index.js`:

```js
module.exports = function foo() {}
```

I also want to put a typedef for it in `./src/index.js.flow`.  But how?

If I do:
```js
declare export default function foo(): void;
```
Then the following happens:
```js
import foo from 'foo'
foo() // okay

require('foo')() // error: Callable signature not found in exports
```

I also tried `declare var exports` to no avail.  Is there any way to accomplish this?  I know that in another project I can declare
```js
declare module 'foo' {
  declare function exports(): void;
}
```
But I want the correct type defs in `foo`'s own `.js.flow` file.

**Comment by jedwards1211** [comment]
Nevermind, I discovered that I can do
```js
declare function foo(): void;
declare module.exports: typeof foo;
```

I can no longer find any documentation for `.js.flow` files...I'll look into opening an issue for that.

**Comment by mmcgahan** [comment]
This would be helpful to add to the flow docs here https://flow.org/en/docs/libdefs/creation/ - I can kind of see how you might be able to infer the solution from the docs, but it's not at all obvious. Thanks @jedwards1211
