### ISSUE TITLE
Regexp.test does not accept undefined

### ISSUE THREAD

**Issue by zachdini** [facebook/flow#3765]
I'm currently using flow version 44 however I'm not sure if this is a new development or not.

When trying to do
```
return REGEXP.test(value);
```
where value is of type `any`, I get the flow error:
```
 16:     return PATTERN.test(value);
                             ^^^^^ undefined. This type is incompatible with the expected param type of
396:     test(string: string): boolean;
                      ^^^^^^ string. See lib: /private/tmp/flow/flowlib_3aa0c0d2/core.js:396
```

Since Regep.test can accept an undefined value as part of JavaScript, why does flow define it as only accepting a string? Can this be updated?

**Comment by nmn** [comment]
Javascript accepts any type pretty much everywhere. The point of flow is to use the types that actually make sense. As such, RegExp.test is defined as `test(string: string): boolean`.

So, it requires a string, and undefined won't work. Further, RegExp.test will never give you anything meaningful with undefined anyway, so I'm not sure why you would need it to work.
