### ISSUE TITLE
Flow does not catch interface incompatibility 

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#3768]
Here is a simplified [example to reproduce][example] the issue, also inlined below for convenience: 

```js
// @flow

export interface Continue <a, b> {
  continue(ok:a):b
}

class Chain <a, b> {
  handler:Continue<a, b>
  constructor(handler:Continue<a, b>) {
    this.handler = handler
  }
}

class Then <a, b> {
  continue:(input:a) => b
  toFrame():Chain<a, b> {
    return new Chain(this.continue) // <- should be an error here!!
  }
}
```

Flow does not catches an error that I have introduced when I modified an interface of `Chain` class from taking a function to continue to an object with method `continue`.

It is also worth mentioning that if I [change `Continue` to be a type][example error] flow reports an error as expected, which I found surprising. Unfortunately I to use `implements Continue<a, b>` it needs to be an interface.

[example]:https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1AJYB2uK2kAhgMYqgDCsJxArrQDwUA0oARgHygA3olCgqjXCxQAKWAGsAXBQCUCnogC+yKtAoBnPfQAWFYqA7d+QkaBNEAJtDIKGTIqwu8+N8UT25sZipcHGk7R2dXSXcUT35la1FRXCMCPQA6cKdsUABeWwoHbJstLUQdfUMAFSMUInMuL0SxCSkFaWIMZlwlBNyBdWTYADFsCgBbGVU6E2I4gWEk0GwUXGZseqIUeGNTImkUtPTfaNYEkHMAWlA9I1hmaHteWkLQMmwcWzIUAEIfks0QA
[example error]:https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgDCsAdrgJaUCupAPAIYA0oARgHygC8oAN6JQoAMZVaDFAApYAawBcLAJSLOiAL7Ix0FgGd95ABYs6oVhx5CRoU5QAm0FNkUVqdRpa7dbEyvq42PRiuDgy9k4ubpKeKN48KjaiorjGNPoAdJHO2Px2LI65ttraiLoGRgAqxiiUFuw+yeKx0ooydBj0uMpJfLwaqbAAYtgsALayamSmdAm8wimg2Ci49Nj1lCjwJmaUMmkZmf5SjEkgFgC0oPrGsPTQDlykhaAu2Dh2LigAhD8lWiAA

**Comment by vkurchatkin** [comment]
Simpler example:

```js
interface T1 {
  foo: string;
}

type T2 = {
  foo: string;
}

var a: T1 = (() => {}: () => void); // no error
var b: T2 = (() => {}: () => void); // error
```
