### ISSUE TITLE
consider renaming `empty` type to `never` for ts compatibility 

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#3770]
It seems that typescript has a [`never`](https://www.typescriptlang.org/docs/handbook/basic-types.html#never) type in place of recently introduced and undocumented `empty` type in flow. Given there has being an effort to keep syntax more or less compatible it would be nice to also rename `empty` to `never` or at least have it as an available alias.

**Comment by vkurchatkin** [comment]
I don't think this will do much in terms of compatibility, this train is long gone. Also empty type is a pretty common term: https://en.wikipedia.org/wiki/Bottom_type
