### ISSUE TITLE
Flow could decide which case to select when extending disjoint union

### ISSUE THREAD

**Issue by k15a** [facebook/flow#3771]
There are cases when flow can decide which case to select when working with disjoint unions.

For example at:
```JS
/* @flow */

type Success = { success: true }
type Failure = { success: false }

type Result = Success | Failure

function extend(result: Result): Result {
	return {
	    	...result,
		foo: 'bar'
	}
}
```

Flow errors with:
```
9: 	return {
           ^ object literal. Could not decide which case to select
8: function extend(result: Result): Result {
                                    ^ union type
```

But if I am not missing something here, the only option for the return type is the same as the incoming type.

A more advanced example would be:
```JS
/* @flow */

type Success = { success: true }
type Failure = { success: false }

type Result = Success | Failure

function extend(result: Result): Result {
	return {
		...result,
		success: !result.success,
		foo: 'bar'
	}
}
```
Where the return type would be the opposite of the incoming type.

I don't know if this use case is very common so it might not be worth to add this feature because there is a workaround.

**Comment by mwalkerwells** [comment]
```Result``` is not a disjoint union: https://flow.org/en/docs/types/unions/#toc-disjoint-unions. You have no "tagged property" to refine the union.

**Comment by k15a** [comment]
Could you please explain why `success` isn't a "tagged property"?

**Comment by madbence** [comment]
seems like a refinement invalidation (?) bug to me:

```js
type Success = { success: true }
type Failure = { success: false }

type Result = Success | Failure;

function good(result: Result): Result {
  if (result.success) {
    return {
      success: (result.success: true),
    };
  }
  return result;
}

function bad(result: Result): Result {
  if (result.success) {
    return {
      success: result.success,
    };
  }
  return result;
}
```

[try flow](https://flow.org/try/#0C4TwDgpgBAygrgYwRAziqBeKBvKLHJoBcUwATnNAL4BQokUAYgIYCWANnGdFrvkqhQkAZs3YpqNOuGgAlVHHbBMsAoKgAfJm07cA3FOFwAdgmCsA9sagBzCxYAmACm74lJeW+ABKDwqU4NFBQrMJQLv7AAHT8hCjegcHB3MBc1thBScGxgiQRXjFqxKQUEN4ANJnBVAbVmSlpUK6KwAa0NEam5lZQAEbMzs3uUJ4tviORiSFh+S2FAmgJGVkNZOlVSTnFQ9FbKJVZNZm0yRCpa02RbUA)

**Comment by SamChou19815** [comment]
this now works, when the object type is inexact
