### ISSUE TITLE
Since 0.39 version flow stops responding

### ISSUE THREAD

**Issue by nkt** [facebook/flow#3772]
I can't update flow in my projects since 0.39 version. I've tried to collect logs using `--verbose` flag, but when the log increased to 5GB I've stoped flow process.
Build example: https://circleci.com/gh/dialogs/dialog-web-components/1018
I guess this issue related to #3430

**Comment by nkt** [comment]
Fix was a pretty simple:
```diff
-export type SelectorState<T> = {
+export interface SelectorState<T> {
```
https://github.com/dialogs/dialog-web-components/commit/438c2fa98d5929936feaa0d987fb482fa6a968de

**Comment by vkurchatkin** [comment]
Here is a minimal repro:

```js
type A<T> = {
  a(): A<T>;
  b(): A<T>;
  c(): A<T>;
  d(): A<T>;
}


declare class Foo {
  a(): Foo;
  b(): Foo;
  c(): Foo;
  d(): Foo;
}

(new Foo(): A<any>);
```

You need at least 4 methods to trigger this error. If you leave 3 methods it terminates, but still takes noticeably more time than 2 methods.  Changing type to interface indeed fixes the problem.

**Comment by vkurchatkin** [comment]
Even simpler:

```js
type A = {
  a: A;
  b: A;
  c: A;
};

type B = {
  a: B;
  b: B;
  c: B;
};

declare var a: A;

(a: B);
```

For some reason, 3 props are enough in this instance.

**Comment by samwgoldman** [comment]
Thanks for the report @nkt and for the trivial repro @vkurchatkin!

I was able to mitigate the issue by changing the FlowConstraint cache to consider `(l, UseT (use_op, u_def))` to ignore the `use_op`, which in this example is `PropertyCompatibility` for the property-wise constraints.

I haven't convinced myself that's OK in general, so I'll spend more time investigating, but seems promising. cc @mroch @avikchaudhuri
