### ISSUE TITLE
flow "forgets" type after returning value from spread

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#3775]
Apologies I'm not able to describe the issue in exact terms or this may be by design but the following is what seems to be unexpected behavior.

````js
type Container = {foo: {bar: string}};
const container: Container = {foo: {bar: 'bar'}};
const {unknownProp1} = container.foo; // error (expected)
container.foo = {...container.foo};
const {unknownProp2} = container.foo; // no error (unexpected)
````

see [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AYVgHYoCGAlgVgE6gC8oA3pLLAFwMBGxlbAzipeQDmAX2EBuRAGNCfUNKJkK3PIRLkqtBk1YcubAOSdK+0RPmz6AVwIBrAggIAFSrAwBGYZvlqlAOm1ioCCgVC7UABRYAB7YkihYACYAlFKqilT+zJr0vrne6ZSZsOKpBBbWdg7OrgBMnnT56oUBQWD2IZRhoOHW0bHxyUA) example

**Comment by Brianzchen** [comment]
Closing, this now correctly throws errors on second case.
