### ISSUE TITLE
Dangerous array (tuple) destructuring

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#3777]
```js
const [a, b] = {}
;(a.foo: string)

const [c, d] = () => {}
;(c.foo: string)

const [e, f] = []
;(e.foo: string)
```
[Try](https://flow.org/try/#0MYewdgzgLgBA2gQwDQwEYF0YF4YG8C+AUANwAUCAdAGYggBcM0ATgJZgDmAlIYaJLHGAoAJphylO2AHx4iZYNVoNmbLjz7R4AUxRUx8dCVJbF9RlFYduQA)

For comparison, all these cases are [reported in TypeScript](https://www.typescriptlang.org/play/index.html#src=const%20%5Ba%2C%20b%5D%20%3D%20%7B%7D%0D%0A%0D%0Aconst%20%5Bc%2C%20d%5D%20%3D%20()%20%3D%3E%20%7B%7D%0D%0A%0D%0Aconst%20%5Be%2C%20f%5D%20%3D%20%5B%5D)

Related #733 #1512 #2612

**Comment by minedeljkovic** [comment]
@vkurchatkin what is 3rd case:
```js
const [e, f] = []
;(e.foo: string)
```
duplicate of? I would like to follow that issue.

**Comment by vkurchatkin** [comment]
I think it's by design actually:

```js
const a = []; // Array<any>
(a[1]:string);
```
