### ISSUE TITLE
Disjoint Unions in switch block and bad case doesn't error

### ISSUE THREAD

**Issue by BrianGenisio** [facebook/flow#3778]
If I create a disjoint union type and reference a valid case, Flow does a good job type checking.  If, however, I use a case which should always fail (thinking about typos, mostly), then the result acts as if it is untyped.  I'd expect an error in this case:

```js
/* @flow */
type Item = {
  id: string,
  name: string,
};

type ActionType = {
  type: "CREATE_ITEM",
  item: Item,
} | {
  type: "UPDATE_NAME",
  name: string,
};
  
function itemReducer(state: Item, action: ActionType): ?Item {
   switch(action.type) {
      case "CREATE_ITEM":
        return {...action.item};
        
      case "UPDATE_NAME":
        return {...state, name: action.name};
      
      // I'd expect this to raise a Flow error!
      case "INVALID_CASE":
        return {...state, name: action.badProperty};
        
      default:
        return state;
    }
}
```

[Example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCS6uAtmALxgDeqYYAlgCYBcYAzugE70B2A5gBpaYHgEMSuVh278hAXwDcqDDnwBBAMbp6cHgBVVFasKx5WAIgDCAJQCiavbYD6BRwFlzQuvWIlWRUnkwAB9jOlNJMHMAVQAFABEHZwA5NTdbT2ExCSkuXkFURWFUKABXHi0dHgZfa1xGUo1cTgAKDlFif18BMFFK3VZNbV0DPABKVgB+ALIaMABINgQfDQALFr7hngA6CLGwukONUTZ8Kzskl3dzZmFDw85cdFLOaqptj82q7Z9SIvv7ncjicznFEo4nKl0jcgfdHs9XtQPtt2sQetlIl9dNsMf8AbCwMBgIQAOSMMC4AAeeC0YHQq3obDpcDAnFEjPwojAADF4Ehmpw4JwAIQE46nKIEZIANTUABkCPEnJY1ABlDK3AEPJ4vN7I1G4dHiTH9HYAI1EjFigrwnCweK1BMYuCgolKMHQmq1rJ1iINSnuckKQA)

Is my expectation wrong?  Or is this a bug?

**Comment by AugustinLF** [comment]
You're right! It is a known issue, see #2399 or #3720 :)

**Comment by Brianzchen** [comment]
Closing issue, the example now correctly throws an error.
