### ISSUE TITLE
Flow type checking seems to be off

### ISSUE THREAD

**Issue by mannyhenri** [facebook/flow#3780]
In the below code with Flow, I'm getting no errors when running flow even if I change the ID type to string when it is always getting a number from the array of object literals I'm passing to this stateless react component. Am I missing something? It seems as if Flow isn't really checking my types of the object item. And yes I do have // @flow at the top of this file

```
type Item = {
  item: {
    id: number,
    title: string,
    category: string,
    description: string,
    link: string,
    release_date: string,
    views: string,
    image: string,
 }
}

// beggining of my react stateless component
const Single = (({ item }: Item ) => ...
```

**Comment by madbence** [comment]
you have to add `// @flow` where you use your `<Single />` component (not just to the file where you define it). [imho flow works as expected in this case](https://flow.org/try/#0C4TwDgpgBAksEFsoF4oG8BQUoEt4IC50ttcATIgOwFcEAjCAJwBoTtg8AbCIgZ2EY5KAc1akoAYwCG8YQHtGIPgKGi2UMhF4TBYDnMrLBIsaU5CA1kdWnsjCNym8IAfTIyeUfsbXiAbjgQAO681ibqOAhSwp7eNlgAvhhJGAD0qVAMwsJCqlByAGZQCCBQ9lISwF7AHty8vJJyCGAGEJTAGBIG-FAAyqrcKFAAFGi4+FAJRHCIUACUKAB8UAA8vGBSlItoeIgAdAg49aoJK6nrm4sYnd1VXe1SQkxDwyQrZDh+V+Ir-SKDuwQyDGaASkygqW+q1SHy+GDmAG4gA)

**Comment by mannyhenri** [comment]
@madbence and it is... `// @flow` is on all my components

**Comment by madbence** [comment]
can you provide a minimal working example to demonstrate this bug?

**Comment by Brianzchen** [comment]
Closing, abandoned issue
