### ISSUE TITLE
Intersection on function type

### ISSUE THREAD

**Issue by jeffijoe** [facebook/flow#3781]
I have a [JS library](https://github.com/jeffijoe/mobx-task) where I make heavy use of adding properties to functions.

In the playground I was trying out the concept and I can't get it to type check properly.

![image](https://cloud.githubusercontent.com/assets/2505474/25269150/babaa622-267b-11e7-980b-5b1f4fbf71df.png)

```js
/* @flow */

type Task<FN> = FN & {
  lastError: ?Error
}

function task <T>(inner: T): Task<T> {
  function wrapped () {
    try {
      return (inner: any).apply(this, arguments)
    } catch (err) {
      wrapped.lastError = err
    }
    
  }
  
  return (wrapped: any) // only way to get it to not fail here
}

const t = task((str) => 'Hello ' + str.substring(1))
console.log(t('sworld')) // good
console.log(t(123)) // type error, also good, works as expected

console.log(t.hahahBugOff(123)) // ... what? No error?
```

Am I doing something wrong or is this simply not possible?

**Comment by mwalkerwells** [comment]
I believe this is what you're looking for?

You're returning a function that takes a **subtype** of the original input and an optional **supertype** of the output.

```js
type Task<Fn> = Fn & {
  lastError?: Error,
}

function task<
  Input,
  Output,
  InputSubtype: Input,
  OutputSubtype: Output,
>(inner: Input => OutputSubtype): Task<InputSubtype => ?Output> {
  return function wrapper(...rest) {
    try {
      return inner.apply(this, rest)
    } catch (err) {
      wrapper.lastError = err
    }
  }
}
```
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAhgM4DWAPAGIB2AfGALxh1gBkYA3qmGDGQwBRAE4i4IgPwAuMKPEiANKgC+6KAFdaAYwwBLOLTAYyVXmACStHBozK+AeVs275qy4DKGgEbZ8s91t7MCcMTx8-PFlQl1R6AAo9Wlo8EQDrW2ZGGNsvX1w8AEpZEgpKQIw8yKywSRyMRh4+ETwMDREjTR19QzAEEWIcfBF4gDpxltIMQu5zPgwRLFm+FbAWto6wJJSRUcGcGCx4jAALPVJFNbwpwrmwFTBtYgxtE7B41JEZptW+gaHUqMBFN5BJmGBPnc1Hw1CogA)

**Comment by mwalkerwells** [comment]
Also, ```console.log``` can take an ```Array<any>```, so it's not really a great way to test types.
```js
log(...data: Array<any>): void;
```
https://github.com/facebook/flow/blob/master/lib/core.js#L852


Regarding the last line of your code, it looks like Flow just doesn't type check properties on functions by default. For example, this does not error:
```js
declare var foo: string => number
foo.bar.baz
```

You can be more explicit than the default behavior though...
```js
type Task<T, U> = {
  (T): U,
  lastError?: Error,
}

function task<
  Input,
  Output,
  InputSubtype: Input,
  OutputSubtype: Output,
>(inner: Input => OutputSubtype): Task<InputSubtype, ?Output> {
  return function wrapper(...rest) {
    try {
      return inner.apply(this, rest)
    } catch (err) {
      wrapper.lastError = err
    }
  }
}
```

**Comment by jeffijoe** [comment]
Your last example seems to be more of what I want, but I need the `Task` to take the signature of the input function. `Task<T, U>` means a function with 1 parameter, whereas I want it to be based on whatever is passed in. Is that possible?

**Comment by mwalkerwells** [comment]
If you wondering if you can express ```{ (A): B, prop: C }``` as an intersection ```Fn & { prop: C }``` & retain all the type information / safety my example ```Task<InputSubtype, ?Output>``` provides, I believe the answer is no.

You may be able to do this with classes though...

**Comment by mwalkerwells** [comment]
I say classes (or interfaces), because it would allow you to express a "callable" object. Something like...
```js
class Task<T> {
  static lastError: void | Error;
  constructor: T;
}
```

If this works for you, I'd be curious. Please post an example. 😃

**Comment by jeffijoe** [comment]
I basically want to add typings to https://github.com/jeffijoe/mobx-task - it works by returning a wrapped function with additional properties. 😄

**Comment by jeffijoe** [comment]
@mwalkerwells class didn't do the trick I'm afraid.

**Comment by nmn** [comment]
I extented @mwalkerwells 's example to work with generalized list of arguments. See if this works for you.

```typescript
/* @flow */

type Task<Fn> = Fn & {
  lastError?: Error,
}

function task<
  Input: $ReadOnlyArray<*>,
  Output,
  OutputSubtype: Output
>(inner: (...rest: Input) => OutputSubtype): Task<(...rest: Input) => ?Output> {
  return function wrapper(...rest) {
    try {
      return inner.apply(this, rest)
    } catch (err) {
      wrapper.lastError = err
    }
  }
}
```


[LINK](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAhgM4DWAPAGIB2AfGALxh1gBkYA3qmGDGQwBRAE4i4IgPwAuMKPEiANKgC+6KAFdaAYwwBLOLTAYyVXmACStHBoyyAJACU8xACYB5WjCwBBMcSxKEHplPndbGwxQsHCMSIBlDQAjbHxZWMjUegAKPVpaPBFZbIA6MpE8UjtLa1sASmZGDNtElNw8OtkSCkpS8srqq0iGpkZJZoxGHj4KjA0RI00dfUMwBBFiHHwRPpKKqobpvmMRLG5zY7BZ+aM8gpESzZxvbIwACz1SRSuBuouwFRgbTEDDaN5gbKFESHf58dZPQolARVeQSZhgKH-NR8NQqIA)

**Comment by jeffijoe** [comment]
That loses type checking on the function properties.

I can get this working in TypeScript:

```ts
interface ITask { 
    lastError?: Error
}

interface ITaskFactory {
    <T extends Function>(fn: T): T & ITask;
}

const task: ITaskFactory = function (inner: Function) {
    const wrapped: any = function wrapped() {
        try {
            return inner.apply(this, arguments)
        } catch (err) { 
            (wrapped as any).lastError = err
        }

    }

    wrapped.lastError = null
    return wrapped
}

const t = task((str: string) => str.length)
t('hello') // good
t(123) // error, good
console.log(t.lastError) // good
console.log(t.haha) // error, good
```

Trying to do the same in Flow:

```js
interface Task {
  lastError: ?Error
}

function task<T: Function>(inner: T): T & Task {
  function wrapped () {
    try {
      return inner.apply(this, arguments)
    } catch (err) {
      wrapped.lastError = err
      throw err
    }
  }
  wrapped.lastError = null
  return (wrapped: any)
}

const t = task((str) => str.substring(2))

t('Hello') // good
t(123) // error, good
console.log(t.lastError) // good
console.log(t.haha) // no error, not good
```

So it seems TypeScript can figure it out. Any ideas?

**Comment by nmn** [comment]
> That loses type checking on the function properties.
can you send me an example?

Also, translating your Typescript to Flow syntax seems to do what you want:
[LINK](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgJIBU4GcDWyDeyAUMqcgDbZgCiUUA9lAPwBcytDURAvkUaJFiIUGbDgBiiMIwCeBEmQA86NuICuIBGGD0QAPgAUMEG3QBKU8gBkaTLgDcPPgl1YwyMGLajckrbOQAXmQYDS0dEGQDUBBoVTDtXTN5MmQXEDdkAHcoOAAHPIgAEzY4EDlg0M1EyJz8wqKDZPwFVNIwKDkWtp7kKAgwNShImOgAOnryGQMwAAtgLAAaZDgoAHM1AFsIcCwzVrbuNLgwBFmo6Chm4l62gzqC4pYymTMxyjcORiDkS4PU3gHQGpB4Nd5UL5QH4gNTkcgHfqDYbZXKPIpOIjpTLuYKeXAGAxuKBsImgNbJQJ6ZBE947NZzfZgAwAclmEDh9GZyQA9NzkGt6PR0UyAIwAJgAzDy+ZdGMsBULMa56OQIO96GsZuDPnRGNL+YL0ViVWryBqtbM4Jb9bKoPLDUA)

**Comment by nmn** [comment]
Here, this works. Like I did in my previous  example:

```typescript
type ITask<I: $ReadOnlyArray<mixed>, O> = {
    (...r: I): O,
    lastError?: Error
}

function task <I: $ReadOnlyArray<mixed>, O>(inner: (...r: I) => O): ITask<I, O> {
    const wrapped: any = function wrapped() {
        try {
            return (inner: any).apply(this, arguments)
        } catch (err) { 
            (wrapped:any).lastError = err
        }

    }

    wrapped.lastError = null
    return wrapped
}

const t = task((str: string) => str.length)
t('hello') // good
t(123) // error, good
t(true) // error, good
console.log(t.lastError) // good
console.log(t.haha) // error, good
```

[LINK](https://flow.org/try/#0C4TwDgpgBAkgKgQwM4GsA8MBcUAkAlCBAEwHkA7AGxAEEAnWhENAWwEsAPCIgPgBooS3KAF4oAbwBQUaVAAUAOkW1sMAJTYSvKTIrJgAUXoB7WgH5sh2iYkBfCRIBmAVzIBjYKyNkowZCigY2PiEpJQ09IwsHFx8AtyyrGRkEMpyivKpaiJCJOqwiKgY-ILi2tKuXkjAUADuDGCQRNgIZCAiUM5uHl619Y2yqqUywz60bZIjk1C0EMBOtN4JSSnNraryCA1UssAAFqxI-Ai0AOZOzBBkwEiqZSM2UK4IwK67cim0g2JQd1NydZtGpgWiB1roqpYTO0Pr8ZHY7vDhgCGlx5OCDMZaO0yE4KBQ7jM5gteoCuLZ7BUyFUfO1fKhZLIqqkmYkToNhEImWjLic9rdgLIAOS7CB4oyCwYAeklUBORiMRAkAoAjAAmADMUplHxM-DlCqVO1oTggWqgOtoevlispSCMFAgaKMJx2aL0kM+UGlsutElt9sdFGdrt2CFDZotVoVQA)

**Comment by nmn** [comment]
Although, to actually be type-safe, you should change `ITask`'s type to this:
```typescript
type ITask<I: $ReadOnlyArray<mixed>, O> = {
    (...r: I): ?O,
    lastError?: Error
}
```

This is because the function `task` will sometimes return undefined even if the original function never did.

**Comment by jeffijoe** [comment]
Dang, that's a mouthful! 😄 

Thanks! Do you think you could walk me through the generics part?

**Comment by nmn** [comment]
Sure,

The important part to understand is that `Tuple` types are a subtype of `$ReadOnlyArray<mixed>`.

So:
```
function task <
  I: $ReadOnlyArray<mixed>, // I is a generic "LIST" of arguments.
  O // O is the Return type of your input function.
>(
  inner: (...r: I) => O // since I was a list, we can use the spread operator to use it.
): ITask<I, O> { ... }
```

Does that make sense?

**Comment by jeffijoe** [comment]
Yeah, thanks!

So how come Flow wouldn't be able to do this the same way TypeScript does? From what I hear Flow prides itself by being more strict, so it surprised me that in this case, TypeScript was more strict. 😼

**Comment by nmn** [comment]
Well the problem is with the way the `&` works. It's a little more nuanced in Flow. This is there reason the object spread was added to Flow.

**Comment by jeffijoe** [comment]
Alright, thank you very much! Should I leave this open for potential future improvements to this use case or is this the official way to do this?

**Comment by nmn** [comment]
Let's leave this open as a `Function & Object` expression should probably work too.

**Comment by mwalkerwells** [comment]
@jeffijoe Saw https://github.com/facebook/flow/issues/2966 so I thought I'd chime in here.

```js
/* @flow */

type Task<Fn> = {
  $call: Fn,
  lastError?: Error,
}

function task <T: Function>(inner: T): Task<T> {
  return ((function wrapped(...rest) {
    try {
      return inner.apply(this, rest)
    } catch (err) {
      wrapped.lastError = err
    }
  }): any)
}

const sayHello: (string => string) = value => 'Hello ' + value.substring(1)

const t = task(sayHello)

t('sworld') // ✅
t(123) // ❌
t.hahahBugOff(123) // ❌
```

Still have one ```any``` that I can't get rid of, but works like you'd expect & it's simple. ```$call``` is a private API, so who knows how it'll work in the future...

**Comment by jeffijoe** [comment]
@mwalkerwells if it's private then I'm not even gonna bother. 😄

**Comment by mwalkerwells** [comment]
Anything marked with ```$``` is technically private, but they're a necessity with Flow.

**Comment by jeffijoe** [comment]
Sure but if there's talk of removing it?
