### ISSUE TITLE
Function Unions and Refinements

### ISSUE THREAD

**Issue by k15a** [facebook/flow#3782]
Hey everyone,

I have a function which will return either another function when called with zero arguments or a string when called with one argument.
For this function I've created the type `type Func = (() => Func) | ((string) => string)`.

I now want to create another function `execFunc` which will take one of the previous functions and a string. It returns a string when the function is of the type `((string) => string)` or recurses into the functions otherwise.
This can be done with the `function.length` property in JavaScript.
```JS
function execFunc(fn: Func, input: string): string {
	if (fn.length === 0) {
		return execFunc(fn(), input)
	}

	return fn(input)
}
```

If I am now calling this function with `execFunction(() => () => str => str, 'foo')` which should in the end return `'foo'`. The problem here is that it seems like flow doesn't understand the difference between `() => Func` and `(string) => string` and therefore the `fn.length` refinement isn't working as well.

I would like to know if this is a problem with my code or if this is something flow can't handle at the moment. Does anyone has a hint how to make this work with flow?

[Example without Flow](https://jsbin.com/zifomaj/edit?js,console)
[Flow Repl](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMQK4B2AxqALygAUlAlOQHx5HF0A+VlAzigE4CWhAOZ0yjbvyE1kkZij6xCoLAA8sxAiUqRCALiYkANKAEZ8KPeIHCLvK6ADeiAJB9IVbQDpoWISgAW5GQUAAx0jk5OPFgo+DyKKmoaxFqEtEYmZlJOAL7IkdGxitqUGShSuYjECpyw3l6wgpQJ6szU4jYS1qCWQgzdvEYA5JCwsIM0UlWENXVwjc1J1DR6SX1cvB1Wy-2dfeJDI2MTiEA)

**Comment by vkurchatkin** [comment]
Using `fn.length` for refinement is unsafe. If you still want to use it, do it with `any`:

```js
function execFunc(fn: Func, input: string): string {
	if (fn.length === 0) {
		return execFunc((fn: any)(), input)
	}

	return (fn: any)(input)
}
```
