### ISSUE TITLE
Issue with `${generator.next().value}`

### ISSUE THREAD

**Issue by karlis-repsons** [facebook/flow#3783]
Flow reports error:

![image](https://cloud.githubusercontent.com/assets/27850284/25270050/d0201edc-2687-11e7-9b56-448574fe12e0.png)

> [flow] [flow] undefined (This type cannot be coerced to string)
> (property) IteratorResult<any>.value: any
> [Flow]
> value: number | void | void

The code executes fine. Is there something wrong with it or we see a flow bug? (I installed latest flow etc. just yesterday.)

The same code for copying:
`// @flow

function * fibonacciSequenceMaker(first, second) {
  let [previous, current] = [first, second];
  yield previous; yield current;
  while (true) {
    [previous, current] = [current, previous + current];
    yield current;
  }
}

function * fibonacciSequenceEvensMaker(first, second, filter) {
  for (let thisResult of fibonacciSequenceMaker(first, second))
    if (filter(thisResult)) yield thisResult;
}

let result = '';
let generator = fibonacciSequenceEvensMaker(2, 7, (v) => v%2 === 0);
for (let i = 0; i < 20; i++) result += `${generator.next().value}, `;
console.log(result);
`

**Comment by rafales** [comment]
`value` may be actually `undefined` (When `done` is `true`). You either need to check if it's not undefined or check if `done` is false.

**Comment by karlis-repsons** [comment]
That makes the warning gone:
![image](https://cloud.githubusercontent.com/assets/27850284/25281712/d85436cc-26b6-11e7-8ede-df965d51c133.png)
However, the generator is intended as infinite one. Can you give example how "done" could be true in the same code?

**Comment by rafales** [comment]
@karlis-repsons flow doesn't know that this is an infinite generator, therefore it thinks that value may be undefined.

**Comment by karlis-repsons** [comment]
Ok, so this would be asking too much: add infinite generators detection to Flow?

**Comment by rafales** [comment]
Don't know, but you can tell flow that you know for sure that it's not null:

```
import invariant from 'invariant';

// ...
const value = generator.next().value;
invariant(value != null, 'this should never be null');
```

or

```
const value = generator.next().value;
if (value == null) { throw new Error('this should never be null') }
```

**Comment by karlis-repsons** [comment]
I am too not sure if Flow should try to detect simple infinite generators. But since they could become complicated, thanks for the tip to use invariant.

**Comment by vkurchatkin** [comment]
> Ok, so this would be asking too much: add infinite generators detection to Flow?

That's not just complicated, that's truly impossible: https://en.wikipedia.org/wiki/Halting_problem
