### ISSUE TITLE
Add type definitions for Notification 

### ISSUE THREAD

**Issue by singhshashi** [facebook/flow#3784]
Currently, there is no type definition in flow for Notification API, thus when using Notification  

```
let idleNotification = new Notification('User is idle',
      {body:'User has been idle'});
```
flow throws the following error. 

`identifier `Notification`. Could not resolve name`

Could we please add this in the next release? 
See [Notification API doc in Mozilla](https://developer.mozilla.org/en-US/docs/Web/API/notification)

**Comment by mwalkerwells** [comment]
Submit a PR 😃
https://github.com/facebook/flow/blob/master/lib/dom.js

**Comment by singhshashi** [comment]
@mwalkerwells I have submitted a PR, but its just lying there and changes are not getting merged. Could you please have a look at it?

**Comment by charlag** [comment]
As far as I know, all keys for options are optional.
