### ISSUE TITLE
Refinement of maybe properties only lasts one line

### ISSUE THREAD

**Issue by zandaleph** [facebook/flow#3786]
The following code works as expected:

```
function consumer(val: string) {}

function example1(foo: {bar: ?string}) {
  if (foo.bar) {
    consumer(foo.bar);
  }
}
```

However, the next example uses the refined `foo.bar` twice, and the second use is unexpectedly an error:

```
function example2(foo: {bar: ?string}) {
  if (foo.bar) {
    consumer(foo.bar);  // works
    consumer(foo.bar);  // error!
  }
}
```

Worse, any function use before accessing `foo.bar` seems to invalidate the refinement:

```
function doNothing() {}

function example4(foo: {bar: ?string}) {
  if (foo.bar) {
    doNothing();
    consumer(foo.bar);  // error!
  }
}
```

As I wrote up this issue I realized that in some frustrating bozo-code universes, `consumer(foo.bar)` or `doNothing()` could modify `foo` to remove `bar`, thus invalidating the refinement.  However, when I first stumbled across it I was sure it was a bug.  Could you add something about this surprising behavior to the Maybe types docs at https://flow.org/en/docs/types/maybe/ ?

FWIW, capturing the value in a local variable solves both the Flow errors and the pathological case Flow is worried about:

```
function workingExample(foo: {bar: ?string}) {
  if (foo.bar) {
    var localBar = foo.bar;
    doNothing();
    consumer(localBar);  // works
  }
}
```

**Comment by AugustinLF** [comment]
Flow is pessimistic about refinements, and considers that any function call might make your previous assertion invalid. Therefore, a function call invalidates refinements. See the [Refinement Invalidations](https://flow.org/en/docs/lang/refinements/) section of the docs.

**Comment by zandaleph** [comment]
I spent an hour figuring this our instead of finding this on the last page of the docs.  Please add a link to Refinement Invalidations from the Maybe Type docs.

**Comment by mwalkerwells** [comment]
@AugustinLF Click "Edit this page" on https://flow.org/en/docs/lang/refinements/ and submit a PR. 😃

**Comment by gkz** [comment]
This is explained here: https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations
