### ISSUE TITLE
Strange behavior with optional property

### ISSUE THREAD

**Issue by micaste** [facebook/flow#3787]
Hi,

I am encoutering a strange issue that has to do with the inference of the type returned by a function I believe. Here is the code that does not work:
```
// @flow

type Properties = {|
  load?: (payload: { context: "a" }) => void
|};

const getPayload = function() {// => typing this function does not help
  return {
    context: "a"
  };
};
// Cast some elements
const actions: Array<Properties> = ([{}]: Array<any>);

actions.forEach(action => {
  action.load ? action.load(getPayload()) : undefined; // => gives an error
  //action.load ? action.load({context: "a"}) : undefined; // => does not give an error
});
```

Gives the following error:
```
16:   action.load ? action.load(getPayload()) : undefined; // => gives an error
                            ^ call of method `load`. Function cannot be called on possibly undefined value
4:   load?: (payload: { context: "a" }) => void
                ^ undefined
```

The error thrown seems to have to deal with the fact that load is an optional property on the type. I am checking if the property is defined before calling it though.
If I make the property `load` non-optional on ActionProperties, then I have no more error.

Interestingly enough, if I replace `getActionPayload()` by what it returns, I have no more error => How does it have an impact ? If the issue has to do with the optional property `load`, why would removing the function call change anything  ?

[Here is the fiddle to play with it](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQE6zb4oCWWAzqALygDeAPoqKHAIYAmA-AFygAUGNmnYc+dUAGNYAOxRYAHij4AiNitABfAJQ0AfKABusUh0QNNAbmTSZFFKADmWFLmGiaoSAFcZksrL8unQg+qDoGKQyjuEAFqRUPn4BMqAcsJSgMrAOsVjQGMyg+C7e+Kl0RSy28kqq6kVWiE2hAMJs9qAUsAC2OPlYfXIUiLadbP6kshR8AIL4+MIAPAREWCTkFAa0-ADadJoAunMLy2wyaHra1ogTKRQAdJCw+ACiE7H8d1Op1AaVLG+sgeHi4oCBMhBsE4-Gcrnc0I4QV0fF8HCwkCiWA4llAoT+TlIhky51A60I+CKIAhUM4oDBNNE-DoNUUylAahUOlAqJk6MxMmxuPxBnSmWyDkcRJwpPJL2a10QQA)

Thanks for your help

**Comment by Gasparila** [comment]
Check out Refinement Invalidations section of https://flow.org/en/docs/lang/refinements/
Because of Javascript scoping, Flow has to make the assumption that any function call can make any variable null if the variable is nullable.
Here are some solutions:
* Save off the payload into a variable:
```
actions.forEach(action => {
  const payload = getPayload();
  action.load ? action.load(payload) : undefined;
});
```
* Save off the load function (kind of weird)
```
actions.forEach(action => {
  const load = action.load;
  load ? load(getPayload()) : undefined;
});
```

**Comment by micaste** [comment]
Wow, thanks. I had read the docs but I guess that this concept takes some time to get used to... It would be obvious in the case where `action` is passed as a parameter to `getPayload`, but thinking that `getPayload` would mutate a variable accessed through the function scope is very pessimistic.

I understand why Flow would work like that, but I think that this particular detail raises the bar A LOT for beginners. I wouldn't have been surprised if Flow was just not supporting that edge-case.

Thanks for your quick help and sorry for the trouble.
