### ISSUE TITLE
Inconsistent Type Alias Existential (*) Type Resolution

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3789]
```foo1``` does not error, but ```foo2``` does... 

Does the location of the existential type "resolution" matter? (function call vs. type alias)

Is this a bug or the intended behavior?

```js
/* @flow */

declare var bar: [[string], string]
declare var baz: [[number], number]

type Tuple<T> = [[*], T]

function foo1<T>(...rest: Array<Tuple<$Subtype<T>>>): Array<T> {
  return rest.map(item => item[1])
}

function foo2<T>(...rest: Array<[[*], $Subtype<T>]>): Array<T> {
  return rest.map(item => item[1])
}

foo1(bar, baz) // <— No Error
foo2(bar, baz)
```

**Comment by vkurchatkin** [comment]
Just curious, why are you using `$Subtype`?

**Comment by mwalkerwells** [comment]
Because there's no way to express a covariant tuple...

**Comment by mwalkerwells** [comment]
Unless this is either unsafe in some way or ```$ReadOnlyTuple``` exists already...

This is basically what I am trying to express with ```[$Subtype<T>]```:
```js
[T] <: [U] 
// ...if
T <: U
```

Although, I'm more mystified by the "resolution" behavior here. You understand what is going on?

**Comment by vkurchatkin** [comment]
Well, `$Subtype` is definitely unsafe.

> Although, I'm more mystified by the "resolution" behavior here. You understand what is going on?

Here is a simpler version of your code:

```js
declare var bar: [string]
declare var baz: [number]

function foo1(...rest: Array<[*]>) {}

type X<A> = [*];
function foo2(...rest: Array<X<string>>) {}


foo1(bar, baz);
foo2(bar, baz)
```

I suspect that for when processing rest arguments Flow instantiates `X<string>` for each argument, thus preventing unification. Not even sure if this is good or bad

**Comment by mwalkerwells** [comment]
I guess I know that ```[$Subtype<T>]``` is unsafe, but if ```$ReadOnlyTuple``` did exist, that would be conceptually safe, correct?

**Comment by vkurchatkin** [comment]
I mean `$Subtype` is just unsafe on its own, it's basically one side of `any`:

```js
declare var x: $Subtype<number>;
x();
```

**Comment by mwalkerwells** [comment]
Yeah, I try to be careful with it...but it is useful sometimes. This is how I commonly use it:
```js

type Invariant<T> = { value: T }
function foo<T>(...rest: Array<Invariant<$Subtype<T>>>): Array<T> {
  return rest.map(item => item.value)
}

declare var bar: Invariant<string>
declare var baz: Invariant<number>
  
(foo(bar, baz): Array<string | number >)
```
