### ISSUE TITLE
Unexpected behavior with nested objects

### ISSUE THREAD

**Issue by scyclow** [facebook/flow#3799]
I get no errors with the following code:
```
// @flow
const obj = {}
const { a: { b: { c } } } = obj
const d = obj.a.b.c

// => No errors!
```
This seems like it could be because `obj` is an unsealed object, but this still strikes me as very unexpected behavior.

**Comment by mwalkerwells** [comment]
Flow infers that ```obj``` is an ```Object```, which is the same as ```any```, bound by ```{}``` (object literal).

You can use flow-inspect (https://github.com/flowtype/flow-inspect) to see the inferred Flow type. This is the type for ```obj```:
```js
ObjT (object) @ 0,1 - 0,0
  type: {
    flags: {
      frozen: false
      sealed: false
      exact: true
    }
    propTypes: [
      .a
        prop: {
          field: EmptyT (empty) @ 0,1 - 0,0
          polarity: Neutral
        }
    ]
    prototype: AnyT (any) @ 0,1 - 0,0
  }
```

If you don't want it to infer ```Object```, you can be more specific and get the error your expect. ```const obj: {} = {}```.

**Comment by SamChou19815** [comment]
This now correctly errors
