### ISSUE TITLE
Support optional properties in objects

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#38]
If I have the following type:

```js
type MyType = {
  a: ?any;
  b: ?any;
}
```

And the following instance of it:
 
```js
var myThing : MyType = {
  a: 'hello'
};
```

Flow will find the following error:

```
/Users/tboyt/Coding/mode7/src/Foo.js:2:15,5:1: property b
Property not found in
  /Users/tboyt/Coding/mode7/src/Foo.js:7:24,9:1: object literal
```

This makes sense, given that the maybe type is intended to be either the given type or `null`, not the type or `undefined`. However, not being able to define a property as entirely optional - e.g., being either a specific type or `undefined` - seems like a big missing feature.

For an example use case, imagine an API with a constructor that uses a hash of keyword arguments, most of which are optional. It would be great to be able to enforce the types of those arguments, *if present*, using Flow, and ignore missing arguments.

**Comment by gcanti** [comment]
+1

**Comment by gcanti** [comment]
As for v0.4 this issue seems fixed:

```js
/* @flow */

var x: {a?: string;} = {}; // ok!
```

**Comment by samwgoldman** [comment]
Can this be closed?

**Comment by samwgoldman** [comment]
Closing. Please reopen if this is still an issue.

**Comment by romulof** [comment]
```es6
const config = {
  baseURL: apiUrl,
};

if (accessToken) { // <-- property `headers`. Property not found in object literal
  config.headers = {
    Authorization: `Bearer ${accessToken}`,
  };
}
```

Do I have to manually add type hints to `config` to suppress this error message?

**Comment by Baba43** [comment]
Does not seem to be fixed or what am I doing wrong?

```javascript
export type AsyncObjectMeta = {
  updating: boolean,
  updateError: ?Error,
  updateSuccess: ?Date,
}

export type GeneralSettingsType = {
  allowAdd: boolean,
  allowManage: boolean,
  _allowAdd: ?AsyncObjectMeta,
  _allowManage: ?AsyncObjectMeta,
}

const test: GeneralSettingsType = {
  allowAdd: true,
  allowManage: false,
};
```

Errors from Flow `0.35.0` 

> Error:(6, 17) Flow: property `_allowAdd`. Property not found in object literal 
Error:(6, 17) Flow: property `_allowManage`. Property not found in object literal

**Comment by jwebcat** [comment]
I know this is an old issue but just in case someone else is curious about the comment of @romulof you have to type the object like so:

```js
const config : Object = {
  baseURL: "apiUrl",
};
```

and no more error voila

**Comment by foobar8675** [comment]
I know this is old, but am running into the case where I am checking a property that does not exist in a flow type.
```
var x: {a?: string;} = {}; // ok!
if (x.b ==="something") { 
  // do something
}
```
I think it would be helpful if this also gave an error.
