### ISSUE TITLE
"non-string literal property keys not supported"

### ISSUE THREAD

**Issue by redchair123** [facebook/flow#380]
```
var x = {
    1234:"a",
    5678:"b"
}
```

Flow generates an error per integer key.

According to [11.1.5 of ECMA-262](http://www.ecma-international.org/ecma-262/5.1/#sec-11.1.5) this is a perfectly valid construct.

EDIT: @jgrund 's solution in https://github.com/facebook/flow/issues/380#issuecomment-224380551 works well

**Comment by fatboysuns** [comment]
Another example when I run it on a jquery javascript.
$.ajax({
                url: url,
                dataType: 'html',
                success: function(data) {
                   //do something
                },
                error: function(data) {
// something else
                },
// This is the line Flow complains
                statusCode: {
                    404: function() {
                         alert('404');
                    }
                }
            });

**Comment by gabelevi** [comment]
Number literals are annoying, since we need to canonicalize them. We should probably just bite the bullet and implement the algorithm. CC @mroch

**Comment by julianacipa** [comment]
Any update on this issue?

**Comment by Zaba999** [comment]
:+1: Is there any progress with this issue? I really need this one :)

**Comment by jgrund** [comment]
As a really awful hack:

```
var x = {
    [1234]:"a",
    [5678]:"b"
}
```

**Comment by rosskevin** [comment]
ugh.  I too need this.

**Comment by StreetStrider** [comment]
The issue still bothers. Tried to typecast to something like `{[n: number]: mixed}` — not working. Even if it did, it's such a crazy workaround for such a small thing.

**Comment by Niggler** [comment]
Any progress?

**Comment by danpantry** [comment]
Playing devils advocate here: All keys on an object will be implicitly converted to a string. I like that this error is explicit about that behaviour (even if the error is not very well defined).

**Comment by lenovouser** [comment]
Any plans to fix this? This should't throw an error

**Comment by arhtudormorar** [comment]
This is working for me:

```
type PropsType = {
	[key: string]: string
}

let currencyId = 1,
    currencyCode = "RON";

let currencies: PropsType = {
	[currencyId.toString()]: currencyCode
}
```

**Comment by Niggler** [comment]
We've internally decided to move away from flow.  @jgrund 's array hack works well

**Comment by StreetStrider** [comment]
@Niggler, please, reopen the ticket. There're plenty of people who still interested in this. Let maintainers see the interest.

**Comment by Niggler** [comment]
@StreetStrider it's nearly 2 years since this issue was first raised.  Contributor first commented 22 months ago, so there's definitely nonzero awareness of the issue.  But at this point, you're better off switching to another typed JS alternative

**Comment by szdavid92** [comment]
@Niggler if this were valid:
```js
export type Obj = {
  '0': number,
  56e-13214125: string
};
```
would you expect
```js
const x: Obj = { '0': 0, 56e-13214125: 'hello' };
(x['0']: number);
```
to pass or fail?

Note, that
```
> { '0': 0, 56e-13214125: 'hello' }
{ '0': 'hello' }
```

**Comment by ndbroadbent** [comment]
@szdavid92 I would expect Flow to just understand that all object keys are strings. 

```js 
a = {
  56e-13214125: 'abc'
}
// => Object {0: "abc"}

a[0]
// => "abc"

a['0']
// => "abc"
```

That seems pretty straightforward to me. Flow should just understand that `{ 0: 'abc' }` is an object with a type of `{ string: string }`. If you need integers as keys, then you have to use a Map (or an array).

I can see how this might trip up some people who are new to JS, but I think there should be an option to disable this warning when you are familiar with JS objects.

For now, I've disabled my `quote-props` rule in eslint, but I would love to turn that back on and disable the warning in Flow.

**Comment by madou** [comment]
this would be fantastic if it was supported.

**Comment by bradennapier** [comment]
Still not supported?

**Comment by Niggler** [comment]
@szdavid92 @ndbroadbent your points are well taken, but it's clear this issue isn't a priority for flow devs.  In that situation it's better to either move away from flow or find a workaround.  The array trick works, and combined with the comment form you can do the trick without affecting the resulting JS code:

```js
var x = {
    /*::[*/ 1234 /*::]*/:"a",
    /*::[*/ 5678 /*::]*/:"b"
}
```

**Comment by chyzwar** [comment]
If there is a fundamental issue in the flow that prevents this?

**Comment by etayluz** [comment]
Hey why isn't this addressed yet?

**Comment by mroch** [comment]
this isn't as trivial as it seems, as @gabelevi and @szdavid92 point out above. to support numeric keys, we need to implement ecmascript's NumberToString, which is highly complicated: https://tc39.github.io/ecma262/#sec-tostring-applied-to-the-number-type

I published [ocaml-dtoa](https://github.com/flowtype/ocaml-dtoa) a while back which we can use for this, so I'd say the major blocker to supporting numbers is fixed (and we don't intend to support other objects as keys).

**Comment by etayluz** [comment]
So what if it's complicated? You work for Facebook. Make shit happen

**Comment by wcandillon** [comment]
I'm writing a flow type definition for the mui-org/material-ui and I am hitting this issue as well.

**Comment by jgcmarins** [comment]
@wcandillon is this open source?

**Comment by wcandillon** [comment]
@jgcmarins Thank you so much for asking 🙌🏻

I've put the current state in the following repository: https://github.com/wcandillon/material-ui-flow
I could really use some help as I'm not sure how to translate of the utility types from TypeScript to Flow

cc: @mastertinner @nathantalewis @bugzpodder

**Comment by hcatlin** [comment]
Use a `Map`

**Comment by syzer** [comment]
@hcatlin this is shorter notation:
```js
{ 0: 'aaa', 1: 'bbb' } 
```
than this:
```js
new Map([[0, 'aaaa'], [1, 'bbbb']])
```
so IMHO it should be supported

**Comment by lucasjohnston** [comment]
This has been open since 2015, this is a tad ridiculous - why is this still not supported?

**Comment by goodmind** [comment]
I opened PR for this #7593 using library [ocaml-dtoa](https://github.com/flowtype/ocaml-dtoa) that @mroch suggested

**Comment by dominikabieder** [comment]
I've upgraded prettier which prompted me to drop the quotes const X = { 2: "1" }, but flow is complaining. any advice?

**Comment by Brianzchen** [comment]
> I've upgraded prettier which prompted me to drop the quotes const X = { 2: "1" }, but flow is complaining. any advice?

Given that prettier doesn't have an option to configure this, probably the easiest solution to to write your obj as the following to retain the key as a string value.
```
const X = { ['2']: '1' }
```
I'd actually consider taking this up with the prettier team, since on their homepage they apparently support Flow

**Comment by nemoDreamer** [comment]
Making it a `Map` does seem like the more modern approach. Worked nicely for me because I had fixed integer keys and nothing else:

```diff
@@ -20,24 +25,24 @@ describe("utils", () => {
     describe("resolveDiceRoll", () => {
       const specs = {
         [PLAYER_0]: {
-          near: {
-            1: 4,
-            6: 9,
-          },
-          far: {
-            1: 0,
-            6: 5,
-          },
+          near: new Map([
+            [1, 4],
+            [6, 9],
+          ]),
+          far: new Map([
+            [1, 0],
+            [6, 5],
+          ]),
         },
         [PLAYER_1]: {
```

**Comment by jamesqo** [comment]
It's kind of ridiculous that this issue is still present in 2021...

**Comment by ayroblu** [comment]
Hey, I encountered this and tried it out:

```
> var a = { 1: 'hi'}
undefined
> a['1']
'hi'
> a[1]
'hi'
> var a = { 1: 'hi', '1': 'bye' }
undefined
> a
{ '1': 'bye' }
```

I think flow's decision here is correct? Perhaps inconvenient, but knowing the above I wouldn't use number types
