### ISSUE TITLE
Name map that allows for (folder/folder.js) to be resolved rather than (folder/index.js)

### ISSUE THREAD

**Issue by natew** [facebook/flow#3803]
This seems to require some way to essentially validate that the `folder/file` are the same name:

```
module.name_mapper='\(\1\)/\(\2\).js$ -> ...
```

Not really sure how you'd define this in regex actually.

Basically goal would be to support this:

https://github.com/elastic/webpack-directory-name-as-main

Where you could write:

```js
import x from './editor'

// resolves to ./editor/editor.js
```

**Comment by vkurchatkin** [comment]
> Not really sure how you'd define this in regex actually.

You can't, but it seems that you what you want is exactly the opposite

**Comment by natew** [comment]
Something like this then?

```
module.name_mapper='\(\1\)/\(\2\).js$ -> '\1/\1.js'
```

**Comment by vkurchatkin** [comment]
Something like:

```
module.name_mapper='\./\(\1\)$' -> '\1/\1.js'
```

**Comment by natew** [comment]
Thank you!
