### ISSUE TITLE
Disjoint Unions Refinements don't work

### ISSUE THREAD

**Issue by Mohamed-Abo-El-Soud** [facebook/flow#3804]
So I was looking at the Disjoint unions in the docs and it gives this example:

```
// @flow
type Success = { success: true, value: boolean };
type Failed  = { success: false, error: string };

type Response = Success | Failed;

function handleResponse(response: Response) {
  if (response.success) {
    var value: boolean = response.value; // Works!
  } else {
    var error: string = response.error; // Works!
  }
}
```

so I extended it to do this:
```
// @flow
type Success = { success: true, value: boolean };
type Failed  = { success: false, error: string };

type Response = Success | Failed;

function handleResponse(response: Response) {
  if (response.success) {
    // var value: boolean = response.value; // Works!
    var successResponse:Success = response;
  } else {
    // var error: string = response.error; // Works!
    var failedResponse:Failed = response;
  }
}
```

And no errors, so, so far so good. But then I applied my own code to my own example, which is quite similar:

```
type singlePerson = {
  married: false,
  dreamSpouse: string,
}
type marriedPerson = {
  married: true,
  spouse: string,
}

type person = singlePerson | marriedPerson;
function parsePerson(guy: person) {
  if(guy.married){
    var spouse: string = guy.spouse;
    var marriedDude:marriedPerson = guy;
  } else {
    var dreamSpouse:string = guy.dreamSpouse;
    var marriedDude:singlePerson = guy;
  }
}

parsePerson({married: true, spouse: "Jess Crowe"});
```
And low and behold, errors like:
```
3:   married: false,
              ^ boolean literal `false`. Expected boolean literal `true`, got `false` instead
7:   married: true,
              ^ boolean literal `true`
7:   married: true,
              ^ boolean literal `true`. Expected boolean literal `false`, got `true` instead
3:   married: false,
              ^ boolean literal `false`
15:     var marriedDude:marriedPerson = guy;
                        ^ property `spouse`. Property not found in
18:     var marriedDude:singlePerson = guy;
                        ^ object type
15:     var marriedDude:marriedPerson = guy;
                        ^ property `spouse`. Property not found in
18:     var marriedDude:singlePerson = guy;
                                       ^ object type
18:     var marriedDude:singlePerson = guy;
                        ^ property `dreamSpouse`. Property not found in
15:     var marriedDude:marriedPerson = guy;
                        ^ object type
```

I don't understand why am I getting these errors for this? Feel free to try this yourself at: 
https://flow.org/try/#0FAFwngDgpgBAzgSwHYHMA2UAKUBOcD2SMAvDAN7AwwC2AhjjglACYBcMAZrWnFADSUYzHFFrUAyhHwBXXuzghGqAQF9QkWHQZNm2PIRLlBWxi3aLp-QXCmyo8xchSrg66DGj6ipRKgx6CIgAfGnpTXVxAgG5gDmkkAGMQBAMIel4AwgAKFGkwdk9AgEojKgQOHLyAOhMdIooqKgA3enhbOXhHVENcsCqbGV4YxpgWnFDtFgARaWZ7WpZM7xhe4ZgVGCgeWAbGsaERMUlB+wUlFB7q4VEJdqg15taF5hm51l90LEiDUlXBNTUwDSeC+XiyZGe5hwlj4bRO7AARAApKBwOAwADCOHwAHcoAiVEUYq5wO5xNIEglUejSGR4BSqWioTDRtxLOwAEb4fAYWhEFQxUmwABitAQGGYVFp9Mp1PYXG2sNw2JwDnO62JQpgACVUVIkLxDOTZWiYCFReKWMS4olkgYABZ85gYXUDA1QLIiN0dV363glXblGCevWEXj9BnUgOCKgAeljrPGLTQ7JgXJ5omWXr9UCqycsURg8ZgAHV8DgANZwACEMcTMsZcF9YfsxsbhmzLbWGy2ht2cYT+2V5bVTg7ofdVWHOELxbLlZrdf2XEtzGb7tYFol4+993+wEBQA

**Comment by madbence** [comment]
@Mohamed-Abo-El-Soud `var` is function-scoped, you cannot declare `marriedDude` once as `marriedPerson` and then as `singlePerson`. use `const` or `let` instead. [see this post for more details](http://2ality.com/2015/02/es6-scoping.html)

**Comment by Mohamed-Abo-El-Soud** [comment]
I think I figured out the problem.

I used the same variable `marriedDude:marriedPerson` and `marriedDude:singlePerson` in both cases of the control flow.
