### ISSUE TITLE
Object value checking fails with aliased indexed types

### ISSUE THREAD

**Issue by shinster** [facebook/flow#3808]
Flow version 0.44.1
```javascript
type Obj<T> = { [string]: T }

const foo: Obj<string> = { hi: '' }
const bar: Obj<number> = foo // No errors

const baz: { [string]: number } = foo // Has errors
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFYA8AKgHxgC8YA3mANoDOGATgJYB2A5gF0AXGEpgAvugDGcXhzBQ4cUSQoceA2g2YALbqIDkhyalnyMYYgENOqsuV4BXALbE8nbYuXpgwMOYKNgBeoszsXHxCos5uHpL03nCoQA

**Comment by SamChou19815** [comment]
now it correctly errors
