### ISSUE TITLE
Instances of `typeof` spec'd types cannot be assigned to many feasible, explicitly typed variables

### ISSUE THREAD

**Issue by popham** [facebook/flow#381]
The `typeof` type operator doesn't play nice with inheritance.  Since ES6 classes inherit static methods, I think that `aX` and `bX` below should typecheck.

```
class Base {}
class Derived extends Base {}

var A: typeof Base = Derived;
var B: typeof Derived = Derived;

var a1: Derived = new A(); // Legitimate NG
var a2: Base = new A(); // NG
var a3: A = new A(); // NG

var b1: Derived = new B(); // OK
var b2: Base = new B(); // NG
var b3: B = new B(); // OK
```

I came across this problem while creating a class factory function that also fails:

```
function bindParams(P1): typeof Base {
  class T extends Base {
    static params() {
      return [P1];
    }
  }
  return T; // NG
}
```

**Comment by loganlinn** [comment]
I am running into this limitation as well. My use case is trying to make a function declaration for [Immutable.js's Record function](http://facebook.github.io/immutable-js/docs/#/Record) that returns a new class.

**Comment by popham** [comment]
Maybe I should have mentioned my use case also?  I'm migrating a [serialization library](https://github.com/capnp-js/serialization) to ES6+BabelJS+Flow, and I need this to (nicely) support [generics](https://capnproto.org/language.html#generic-types), e.g.

```
class SomeGeneric {
    static bindParams(T, U) {
        class BoundGeneric extends Base {
            static params() {
                return [P1];
            }
            // ...
        }
        return SomeGeneric;
    }
}
```

**Comment by popham** [comment]
Looks like these uses belong to the `Class<T>`-syntax now.  I don't see much value in any thread members beyond the first, so I'm closing this and opening an updated issue.
