### ISSUE TITLE
function return type disambiguation

### ISSUE THREAD

**Issue by slicejunk** [facebook/flow#3817]
is there an obvious solution for this kind of pattern ?

```js
// @flow
function getSomething(name: 'string'): Object | number {
  switch (name) {
    case 'object' : return new Object();
    case 'number' : return Math.random();
    default : throw new Error();
  }

}


const foo: Object      = getSomething('object');
```

casting every time the return type ```((foo: Object): any))``` is painful.

https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaAOYCmWAyrALakAWOahAFGgIbUBcoA5LAEYBWxbF1AAfbmhSVexAE5cAlJwDyAoVjGhJ0uaADeiUKADO8HFgw1QzNsQX7DR0BhbHi3PoOGhOs0ilkCNGJ4UFUvLEYFAG5HIxc3CSkZeR9QPywAggBZFiwaADpZFjQAEyoo2KdQUuJIFhRoDU582QQtENAAUVk22UrHAF9ERGGRjHxjDUhYWBU1bGqjAF4iUgpqfPomHgWsRWigA

**Comment by nmn** [comment]
There is only one way around this currently:

```typescript
const _getSomething: any = function(name) {...};

const getSomething:
  & ((name: 'object') => Object)
  & ((name: 'number') => number) = _getSomething;
```

I know this isn't ideal, but it does work.

**Comment by SamChou19815** [comment]
The comment above is the right solution
