### ISSUE TITLE
Unsafe Prop on Function Type

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#3824]
After answering a question asked in https://github.com/facebook/flow/issues/3799, I decided to look into the defaults for functions. They are merely callable objects after all...

What is the reasoning for this behavior?

**Not Expected**
```js
declare var foo: string => void
foo.unsafe // <— No Error
```

**Expected**
```js
declare var foo: { (string): void }
foo.unsafe // Error: "Property not found"
```

**Expected** (...similar to ```Object```)
```js
declare var foo: Function
foo.unsafe // <— No Error
```

**Comment by vkurchatkin** [comment]
This is duplicate, so closing. AFAIK there is no good reason for this behaviour, except for `Function`, probably

**Comment by mwalkerwells** [comment]
Agreed re: ```Function```. Do you have the duplicate issue #?

**Comment by vkurchatkin** [comment]
https://github.com/facebook/flow/issues/106

It's so old that it probably predates intersections and was included to support adding properties to functions
