### ISSUE TITLE
cannot type check inside if-else statement

### ISSUE THREAD

**Issue by JunyuanZheng** [facebook/flow#3826]
Hi,

I am transferring from TypeScript to Flow. Here is part of the code:

I defined cursorPosition like this:
```
const cursorPosition: CursorPositionType = this.props.cursorPosition;
```

And the `CursorPositionType` is:
```
export type CursorPositionType = {
  x: number,
  y: number,
  isOutside: boolean,
}
```
My testing code is:
```
if (!cursorPosition.isOutside && cursorPositionTime >= start && cursorPositionTime < start + offset)
```

If I change `isOutside` to `isInside`, Flow does not throw an error. However, if I do something like:
```
const abc = cursorPosition.isInside;
```

Then Flow can detect the error.

Is there a bug or my Babel configuration is wrong?

Thanks!

**Comment by JunyuanZheng** [comment]
Reproduce this issue in: https://flow.org/try/
```
/* @flow */

type CursorPositionType = {
  x: number,
  y: number,
  isOutside: boolean,
}

let abc;

const cursorPosition: CursorPositionType = {
  x: 10,
  y: 20,
  isOutside: true,
}

if (!cursorPosition.isInside) {
  const ghi = 1;
}

const def = cursorPosition.isInside;
```

**Comment by JunyuanZheng** [comment]
I figure out why this happened.

For flow `if(cursorPosition.isInside)` actually doesn't matter, if `isInside` exist it will be true, otherwise it will be false. So basically this statement is correct. However, if you want to change the value, it will know the variable assignment is illegal.

But my question is, is this a good feature?  because I have defined a type, so this should be a strict rule.

**Comment by SamChou19815** [comment]
This now correctly errors.
