### ISSUE TITLE
Flow doesn't report errors when accessing properties of an empty object

### ISSUE THREAD

**Issue by andreypopp** [facebook/flow#3827]
```
// @flow

let notOk = {};
notOk.a.b; // missing an error!
```

See for repro:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMA7ObAeQGswBeMAbwF8BuVA4kgOgEMWAjOsYYMALYBLAM4iheAOZg2eMJgBOCuAoCE6LLjhlKVNgC4wAFgBM9VNq4MgA

**Comment by vkurchatkin** [comment]
This is mentioned in docs: https://flow.org/en/docs/types/objects/#toc-unknown-property-lookup-on-unsealed-objects-is-unsafe

**Comment by andreypopp** [comment]
Yeah, I can see that now.

**Comment by andreypopp** [comment]
What's surprising is that if I add a type annotation (also unsealed) it can catch such error:
```

let notOk: {c: number} = {c: 43};
notOk.a.b; // error here, ok
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMA7ObAeQGsAuMAbwGMK8BXAWwCNMAnAXzAF4rawALAGYOAblQFiJAHQBDac1FhgwMIwCWAZ03q8AczCy8YdmzhsAhOiy44JHlVkUBAJjGo7C8UA

**Comment by andreypopp** [comment]
Ok, I think I'm misunderstanding what "unsealed" objects are.
