### ISSUE TITLE
Incorrect parsing of array destructuring

### ISSUE THREAD

**Issue by fortes** [facebook/flow#3831]
This code is being incorrectly parsed:

```js
const [one, two = null, three = null] = arr;
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQBDATq0BeUBtAjADQBMBAzALoDciAxrAHYDOALrgwKYGjPyxaj0ArtGhdmAC1Tt2-ISPL80qakA

Hit this issue with prettier: https://github.com/prettier/prettier/issues/1457 -- which outputs the following AST:

```js
const [one, two = (null, (three = null))] = arr;
```

**Comment by vkurchatkin** [comment]
Duplicate of https://github.com/facebook/flow/issues/1985
