### ISSUE TITLE
Exact object type does not catch missing function arguments

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#3832]
With an exact object type representing function arguments, Flow does not report an error if one of those arguments is missing.

Here is an example:
````js
/* @flow */

type LogParams = {|
  verbose: boolean,
  message: string,
|};

function log({ verbose }: LogParams) {
  // do some logging...
}
````

Since the `log()` signature is missing the `message` parameter, Flow should report an error but it does not.

If I *call* the function with a missing `message` parameter, Flow will report an error as expected:
````js
log({ verbose: true });
````
````
index.js:12
 12: log({ verbose: true });
     ^^^^^^^^^^^^^^^^^^^^^^ function call
  8: function log({ verbose }: LogParams) {
                               ^^^^^^^^^ property `message`. Property not found in
 12: log({ verbose: true });
         ^^^^^^^^^^^^^^^^^ object literal
````
However, if I fix the the code to `log({ message: 'an error', verbose: true })` then *the `message` parameter will be ignored* since the function destructuring has a typo. Flow should report an error about the missing function parameter.

I know that partial destructuring is a feature of ES but is there a way to make Flow report errors for function arguments?

**flow version: 0.45.0**

**Comment by vkurchatkin** [comment]
It's ok not to use all fields from an object. Forbidding this seems counterproductive.

**Comment by kumar303** [comment]
Hmm, I suppose so. Is there no other way to express *required* function arguments of an object type?

**Comment by kumar303** [comment]
Maybe [`strict_call_arity`](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/) will do what I want? I can't tell from that blog post if it will enforce exact objects (as arguments) or not though.

**Comment by vkurchatkin** [comment]
No, arity has nothing to do with this

**Comment by samwgoldman** [comment]
This is working as intended. Realistically, you're going to realize you need `message` when you go to actually write body of the `log` function.
