### ISSUE TITLE
Dynamic import errors without assignment

### ISSUE THREAD

**Issue by jonasi** [facebook/flow#3841]
Dynamic import (e.g. `import('abc')`) still gives an `Unexpected token import` error unless the promise is assigned to a variable.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodxhgXATgawGdUBjOAO0IBcwBLAWwAcwBeOpvKgCgHIBDAEYkeASgDcqBowB0VABYBTcl3pwAJqwB8YMpTgwF0+AHMV6kQBowC3Li06KhfYZNcbuEePSpMYNXAVCch4aHAJJDlxufiFRWUVlVQ0WbV0nAyM4UyTLa1t7NOdM03dPMSA

```js
// works
const imp = import('abc');
imp.then(mod => console.log(mod), err => console.log(err));


// doesn't work
import('abc').then(mod => console.log(mod), err => console.log(err));
```

**Comment by vjeux** [comment]
Should this be closed @mikaelbr?

**Comment by mikaelbr** [comment]
Yep. Should be working with the changes from 3eaa8faa48ad796d680c00d9677f953189c4075f
