### ISSUE TITLE
Generic React HOC 2

### ISSUE THREAD

**Issue by Diokuz** [facebook/flow#3842]
https://github.com/facebook/flow/issues/2521

Solution from the issue above is not working when I add `export` keyword to the wrapped component: 

```
export const MyPureComponent = pureRender(MyComponent);
```

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50yAPPIsFACuAOxoY4IsDiGtyIgCZl8AHgAKALgDyAIwBWZGgBowAZQ1gA3gF8AfAApUYMAHV8FHDjIKAwgzwiZCKEFj4wFADOESrk1IQAdH64kkGEKhQiAJ4maiamtrZGqACUoeFRMWwJSQGpKgBucBgKOXkFVk5grISyUlTlEWBqsmTySqwKYLyEQQqDsTSJ-inBDU0tQ20dzs449DgRFmpcO2ARhBQzFqYnOxEAFnBCML7LgcEAqjgKl2T2gTxCGp9odNmAAYRTBcrmZSmAdHA4DBKFJLJ0AJDOYDAQQEMAYGAwITndyEDD1MjSWR4CJkQaSGCZTqnKB4+xUSTnMAAazImXxUghwLgB2K21OOwwUDA-2mwoOAG1eZkALpgACEAF5NWBCPcMBF4nsRRElXyVWK0RKJd1err8EIyLdrdZmTtXdbWfgZRyRFzlQLwdMob9LW7TlKZRCQzMzaqNdrdfrDedfnGLeLrc5bfgpIQHU7w+6ix6bWQernBBQYLTnWBS9nZsp7GHrTmpCo3B4vK9ku9iJZ4kO9QajSDrGBgLY66XrFxXahCJkvGAALKZeWDHVW3FwCwkjAiADmRWcOgo+AsIiEWB0yiKc8Xy8p65jlO3nQAjkIeBYEUiUQfLhUH6SJBnXGoVmIaZZnmKolj7OpGmaEx103VDMjfWxxWNA4LDQkFblTGFX2hQtG0UZs4QWBIAFFkSwOoMkybCd0bCspEca0VAUclbCLZxLBHQ1cMNVk4AbCUhOTMcTXic98Ek05pNHUT5IoAAvLFwGUehvRQesBKsYT4mIsh4m-HglJ2FSUzIiyhB-ScdPwPTkBxayVGAXj6n405iluV0F14fhiF9Lk0JGSD+zAHUZDkJt8HsCC3lSALUBUSLWGi1Jd01JgADFESYeEL01SwABYACYJynLhMo3KLUuCPLCuK0r8Hy6qSrqyccV0ggMqysgcpa8T8qKuAeunLMdmxKZXMGhrhmy5riAocqAEZapm2aJXmgb8HQIA)

It generates two more errors:

```
55: export const MyPureComponent = pureRender(MyComponent);
                                   ^ type parameter `P` of function call. Missing annotation
55: export const MyPureComponent = pureRender(MyComponent);
                                   ^ type parameter `S` of function call. Missing annotation
```

without `export` it works well, but I need to export my component

What should I change in the code to fix that errors?

Maybe there is an official way to wrap components?

**Comment by Diokuz** [comment]
Looks like it is because if that line:
```
): Class<React.Component<void, Props, S>> {
```
For some reasons _flow_ fails to understand what is `P` and `S` if `export` word is used.

Is it a bug?

**Comment by Diokuz** [comment]
I found solution:
```
export const MyPureComponent: Class<React.Component<any, MyProps, MyState>> = pureRender(MyComponent);
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50yAPPIsFACuAOxoY4IsDiGtyIgCZl8AHgAKALgDyAIwBWZGgBowAZQ1gA3gF8AfAApUYMAHV8FHDjIKAwgzwiZCKEFj4wFADOESrk1IQAdH64kkGEKhQiAJ4maiamtrZGqACUoeFRMWwJSQGpKgBucBgKOXkFVk5grISyUlTlEWBqsmTySqwKYLyEQQqDsTSJ-inBDU0tQ20dzs449DgRFmpcO2ARhBQzFqYnOxEAFnBCML7LgcEAqjgKl2T2gTxCGp9odNmAAYRTBcrmZSmAdHA4DBKFJLJ0AJDOYDAQQEMAYGAwITndyEDD1MjSWR4CJkQaSGCZTqnKB4+xUSTnMAAazImXxUghwLgB2K21OOwwUDA-2mwoOAG1eZkALpgACEAF5NWBCPcMBF4nsRRElXyVWK0RKJd1err8EIyLdrdZmTtXdbWfgZRyRFzlQLwdMob9LW7TlKZRCQzMzaqNdrdfrDedfnGLeLrc5bfgpIQHU7w+6ix6bWQernBBQYLTnWBS9nZsp7GHrTmpCo3B4vK9ku9iJZ4kO9QajSDrGBgLY66XrFxXahCJkvGAALKZeWDHVW3FwCwkjAiADmRWcOgo+AsIiEWB0yiKc8Xy8p65jlO3nQAjkIeBYEUiUQfLhUH6SJBnXGoVmIaZZnmKolj7OpGmaEx103VDMjfWxxWNA4LDQkFblTGFX2hQtG0UZs4QWBIAFFkSwOoMkybCd0bCspEca0VAUclbCLZxLBHQ1cMNVk4AbCUhOTMcTXic98Ek05pNHUT5IoAAvLFwGUehvRQesBKsYT4mIsh4m-HglJ2FSUzIiyhB-ScdPwPTkBxayVGAXj6n405iluV0F14fhiF9Lk0JGSD+zKMDKjiBDalWZiMPQtdMLI9odRkOQm3wewILeVIAtQFRItYaLUl3TUmAAMURJh4QvTVLAAFgAJgnKcuDKjcoqK4JqrqhqmvwGqOsa7rJxxXSCFK8qyEqwbxJq+q4Em6csx2bEplcubeuGCqBuICgWoARi6zatolHbZvwdAgA

Is there any official Facebook's way to cover HOC by flow typings?

Anyway, this issue could be closed now.

**Comment by cdomigan** [comment]
> Is there any official Facebook's way to cover HOC by flow typings?

I would love to know this too! There used to be documentation on flow.org but this has been removed :/
