### ISSUE TITLE
Type checking lost after indirect import

### ISSUE THREAD

**Issue by Palisand** [facebook/flow#3845]
Take the following directory structure:
```
items
├── Item1
│   ├── Item1.js
│   └── index.js
├── Item2
│   ├── Item2.js
│   └── index.js
│
│  ...
│
└── index.js
```

Suppose _items/index.js_ looks like this:
``` javascript
import Item1 from "./Item1";
import item2 from "./Item2";
...

export {
  Item1,
  Item2,
  ...
};
```

and _Item1/index.js_ looks like this:
``` javascript
import Item1 from "./Item1";

export default Item1;
```

Now, if _Item1.js_ contains a type-annotated function like so:
``` javascript
// @flow

const Item1 = (num: number) => {
  console.log(num)
};

export default Item1;
```

Flow will succeed in reporting an error when attempting to use the function in the following manner
``` javascript
import Item1 from ".../items/Item1/Item1"; // from first export (not from any index.js)

Item1("string");
```
**but will fail** when importing from _items/index.js_ or _Item1/index.js_:
``` javascript
 import {Item1} from ".../items";
```
``` javascript
 import Item1 from ".../items/Item1";
```

Does anyone know what could be the cause of this and if there is any solution besides "direct" imports?

**Comment by vkurchatkin** [comment]
This seems to be working as expected. It should be

```js
 import {Item1} from ".../items";
```

and

```js
 import Item1 from ".../items/Item1";
```

**Comment by Palisand** [comment]
Yessir, that was a typo on my part. The real issue was that I had stupidly forgot to flag the `index.js` files.

**Comment by basbz** [comment]
Lifesaver... Was experiencing the same issue. Then was wondering what was meant with `flag` ... `@flow` in my case 😅
