### ISSUE TITLE
Flow incorrectly type checks imported types

### ISSUE THREAD

**Issue by jameskraus** [facebook/flow#3855]
Flow will incorrectly type check a file if some of the types are imported vs if they are inlined. I've created a repo to show the behavior. 
https://github.com/jameskraus/flow-import-bug
Flow will throw errors for `importing-generics.js` but not `all-in-one.js`

This applies to v0.45.0

**Comment by gabelevi** [comment]
Thanks for the repro repo! @samwgoldman & @avikchaudhuri - it kind of looks like some bad interaction between object spreads and speculative matching. Does this look familiar?

Here's the error when I clone the repo:

```
importing-generics.js:19
 19: type MaybeExtraData<T> = MaybeWithExtraData<T> | MaybeWithoutExtraData<T>
                              ^^^^^^^^^^^^^^^^^^^^^ property `extraData`. Property not found in
 29: const WithoutExtraData: MaybeExtraData<number> = {
                                                      ^ object literal

importing-generics.js:31
 31:   hasExtraData: myFalse,
                     ^^^^^^^ string literal `myFalse`. Expected string literal `myTrue`, got `myFalse` instead
 10:   hasExtraData: typeof myTrue,
                     ^^^^^^^^^^^^^ string literal `myTrue`
```

For some reason it's incorrectly choosing the first element of the union. This behavior is triggered by spreading an imported object type.

**Comment by samwgoldman** [comment]
Hmm, I'll take a look.

**Comment by Brianzchen** [comment]
This works fine in current version, tested 0.136.0
