### ISSUE TITLE
Is it possible to refer to a property of a type?

### ISSUE THREAD

**Issue by philippotto** [facebook/flow#3867]
I would like to write a generic setter function which receives the property name as a string and the property value as type T which should conform to the type determined by the property name.

Something like this would be nice:

```js
/* @flow */

type t = {
  a: string,
  b: number,
}

const obj: t = {
  a: "hi",
  b: 1,
};

// Syntax error since t[k] doesn't work
function change<k: $Keys<t>>(key: k, value: t[k]) {
  obj[key] = value;
}

change("a", "...");
change("b", 1324);
change("b", "..."); // should fail
```

Is there a way to achieve this?

**Comment by agentcooper** [comment]
I've never actually used it, but probably `$PropertyType` is the thing you want: https://flow.org/en/docs/types/utilities/#toc-propertytype.

**Comment by philippotto** [comment]
Thanks for the pointer! I had looked through the utilities, but apparently I overlooked this.

However, I guess, I have to wait until $PropertyType allows the second parameter to be a non-string. Since this is sort of tracked in https://github.com/facebook/flow/issues/2310, I'll close this issue.
