### ISSUE TITLE
v0.45.0 - malformed warning during flow check

### ISSUE THREAD

**Issue by Igor-Vuk** [facebook/flow#3870]
After upgrading to v0.45.0 I am getting this two warnings every time I run flow check
..\node_modules\node-uuid\lib\sha1-browser.js is malformed
..\node_modules\weinre\web\client\nls\English.lproj\llocalizedStrings.js is malformed

what is this about,? can I remove it?

Thanks

**Comment by vkurchatkin** [comment]
Most likely this has something to do with new unicode lexer

**Comment by gabelevi** [comment]
Yeah, these files themselves are not encoded in valid UTF8. You can probably add those files to your ignore. I think in the future, Flow will try to deal with malformed files in some better way. At the moment, it can't even read them, so it just emits a warning

**Comment by mroch** [comment]
#3814 is tracking what to do about malformed files
