### ISSUE TITLE
Using `{}` instead of `Object`

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#3872]
I want a field to accept an object of arbitrary shape. Is `foo: {}` any safer then `foo: Object`, which is considered dangerous? Or maybe `foo: {[string]: mixed}` have some advantages?

**Comment by nmn** [comment]
You want to use `{}`. `Object` is more like `any` but only for objects.

**Comment by Hypnosphi** [comment]
>You want to use {}

OK, so what's the difference exactly? Is there any value that is an `Object` but isn't a `{}`?

**Comment by mwalkerwells** [comment]
```Object``` is a ```supertype``` and ```subtype``` of any ```Object```. So as @nmn said, it's the same as ```any``` bounded to ```objects.

This is how I'd type your example...
```js
type Foo<T: {}> = {
  foo: T,
}
```
