### ISSUE TITLE
Can't parse destructuring in `catch`

### ISSUE THREAD

**Issue by anmonteiro** [facebook/flow#3874]
Minimal repro:

```js
try {
  console.log('foo');
}
catch({message}){
}
```

Errors with:

```
6: catch({message}){
         ^ Unexpected token {
```

Online:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXATgTzAb1TDAGM4A7AZzhgFMA6eAcwAoByKOONgSgG5UAX1QkAhhhIALFvgC2tSpVFNagnoWFA

**Comment by kyledetella** [comment]
I came across this same issue using Prettier ([example](https://prettier.github.io/prettier/#%7B%22content%22%3A%22%2F*%20%40flow%20*%2F%5Cn%5Cntry%20%7B%5Cn%20%20console.log('foo')%3B%5Cn%7D%5Cncatch(%7Bmessage%7D)%7B%5Cn%7D%5Cn%22%2C%22options%22%3A%7B%22printWidth%22%3A80%2C%22tabWidth%22%3A2%2C%22singleQuote%22%3Afalse%2C%22trailingComma%22%3A%22none%22%2C%22bracketSpacing%22%3Atrue%2C%22jsxBracketSameLine%22%3Afalse%2C%22parser%22%3A%22flow%22%2C%22semi%22%3Atrue%2C%22useTabs%22%3Afalse%2C%22doc%22%3Afalse%7D%7D)) with the flow parser enabled.

**Comment by goodmind** [comment]
I think this was fixed
