### ISSUE TITLE
$ObjMap is not resulting with an error on method call

### ISSUE THREAD

**Issue by michalkvasnicak** [facebook/flow#3886]
Given following example:

```js
/* @flow */

import React from 'react';

type Mutations = {
    [key: string]: () => () => any
}
    
type Observable<T> = {
    currentResult(): { data: T }
}
      
type Queries = {
    [key: string]: () => Observable<number>,      
}
      
type Props<T1: Queries, T2: Mutations> = {
    queries: T1,
    mutations: T2,
    render(
        queries: $ObjMap<T1, <V>(() => Observable<V>) => { data: V }>, 
        mutations: $ObjMap<T2, <V>(() => V) => V>
    ): any
}

class Test extends React.Component<void, Props<*, *>, void> {
    render() {
        const { mutations, queries, render } = this.props;
      	
        const mappedQueries = Object.keys(queries).reduce(
        	(res, name) => ({ 
                    ...res, 
                    [name]: queries[name]().currentResult() 
                }), 
                {}
        );
      	const mappedMutations = Object.keys(mutations).reduce(
        	(res, name) => ({ 
                    ...res, 
                    [name]: mutations[name]() 
                }), 
                {}
        );
      	
        return render(mappedQueries, mappedMutations);
    }               
}
               
(<Test 
   mutations={{ 
       c: () => () => true 
   }} 
   queries={{ 
      a: () => ({ 
          currentResult: () => ({ data: 1 }) 
      }) 
   }} 
   render={(queries, mutations) => {
	const a: boolean = mutations.c();
        const t: number = queries.a.data;
        const e: boolean = queries.a.data; // flow error
   }} 
/>);
              
(<Test
   mutations={{}} 
   queries={{}} 
   render={(queries, mutations) => {
      mutations.notExisting(); // should result in typecheck error?
      const test: boolean = queries.a; // should result in typecheck error?
   }} 
/>);
```
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAFkAroQqEMcAHYBnMAF4wAb1QBIANoBrMjwBcYGYXwYpAcwC6+gBQBKBQD4wth2ApSeqAL6owvsKl5+MAB5ACMZMnwANwpQmDIAHgAVR0UVXyphfFYpQnIZYRhCW30lMAATcQp9JLBvbz8-AL4BAEVhSIwyOTS1LR19Q2MzSyc7eUcwiOjY+ISpYSxQyPsAGkbfLx8N5qCABXocGWSARn12zu71pIAmfRExCWkZVOVt3wBHDuNumpPVtRYUTiSSyGo3AGNHLlSJWL6XGT6AAkYQAVoIKDhTusEgA1exWZwTELhSIxOKJfHjRxlSpifS4uprMBAx6gxFgFGhdGY5IQsB4glExy46lgKn6NwebyoKgwCgyORJbrEMgAD0IZCk5Tk5GohAAdABhBh4KRawgJKJwDDldYHOBHBIgdYgZnW200tTQ2F2dJ+VRUZ7EMqskHPdbwn4ydY+-B1BRgQgACwwMgNOEOMi4GzAqneAaDsmIWEx-HKF2jibRZBoBu0PBkcO+XRkNgNrHKwioZCsBcaqisrBjYCkFCwZDFVjKBtnw-W6jHE9GUdbi-HZHMtgNmWyFvyhWKdk8NnWSgaubANhzG0DwZZZbI5Qe4dk1e5tcNDabYaesnbnbdr2-YBkOVyjhuU4znO4Hrsu+i-uycGbs4J5nheubXiB+a5qwhBZFIYBxlYpY4OWlatuspHli+f5tjevieJezFbMxl6oFYyQqv4fiIc88hKGUVDWFOYpGB0dRMe8q7dAJZTVGMLjTmAu45Hk3SHiJSm0lU+gnHUx7HlJfhxgJzYIlRwJ0WKKh3sWrj6KEcBwPEbiJnxsg7rYDEqfehD6AsSyRImMnphQBp0hQPlFoYYBkI5zmuYRiihQa4WRRwYDAMAYCwIgcXZAQXhMcA9hYWxOyccqhjvB5MhyZ4xmfC2smCY1PG+KZSjmdGllss8NkgXVBpSHAhAAKJqmmEhmN5WU5ZE9D4AA-CBMXEJqhgJS5lDJWAqVRfNBVLat7WleVFWXkAA)

Flow type check for first render of `<Test />` component with `queries` and `mutations` defined is correct.

But in second render where `queries` or `mutations` are empty objects aren't any errors. Is this correct behaviour or is it bug?

**Comment by SamChou19815** [comment]
Flow will now error on this example.
