### ISSUE TITLE
boolean clause allows unknown properties to be referenced

### ISSUE THREAD

**Issue by rsolomon** [facebook/flow#3887]
Take the following type and function definition:

```
type User = { id: string };

function getUserName(user: User) {
  return user.name; 
}
```

As expected, Flow catches the following issue:

```
10:   return user.name; 
                  ^ property `name`. Property not found in
10:   return user.name; 
             ^ object type
```

However, modify the function just a bit:

```
function getUserName(user: User) {
  return user.name || 'No name!'; 
}
```

Flow no longer catches the fact that `name` is not a known property of `user`.

I believe that Flow should be warning about this code regardless of if it is safe to execute or not. At the very least, `user.name` would be a dead code path as far as the type definition is concerned.

**Comment by sdwio** [comment]
This can lead to hard to debug problems with simple typos
```
fn( {
  callback : () => console.warn( "This will never be called" ),
  doSomething : true
} )

function fn( a: { doSomething: boolean, callback: () => void } ) {
  if ( a.doSmoething ) {
    a.callback()
  }
}
```

**Comment by bcardiff** [comment]
As a workaround a cast expression can be added to force a check.

```js
type User = { id: string };

function getUserName(user: User) : string {
  return (user.name : ?string) || 'No name!'; 
  //           ^ property `name`. Property not found in
}
```

I just came across this while willing to check that a `if (obj.field) { ... }` expression does not have a typo in the `filed`. Doing `if ((obj.field : boolean)) { ... }` is my workaround, but I would vouch for a safer check by default.

**Comment by Brianzchen** [comment]
Issue [resolved](https://flow.org/try/#0C4TwDgpgBAqgzhATlAvFA3lAlgEwFxRzCJYB2A5lAL4DcAUHQGYCupAxsFgPalTkTB4SAHIBDALYQAFMwSICQxAEoMdKFEQDmiXrKQA6UhIg0odKgxbtOPPgMVjJAJhlyFclejUatOqHsRDYygAHxCoAHJhLigjSQBCCNNzIA)
