### ISSUE TITLE
Order significance with declare

### ISSUE THREAD

**Issue by LoganBarnett** [facebook/flow#3888]
I'm encountering some trouble with `declare` that seems to be related to the order in which things are declared. I expect declaration order should not matter. In this example it would be difficult to rearrange the order without changing the semantics of the declaration.

```
declare module M {
  declare function bar(foo: B): void;
  
  declare class A {
    foo: bar;
  }

  declare class B extends A {
  }
}
```
produces
```
5:   declare function bar(foo: B): void;
                               ^ identifier `B`. Could not resolve name
```

This seems to be specific to declarations. Here is the non-decl style:
```
type Fn = (foo: D) => void

class C {
  foo: Fn
}

class D extends C {}
```
The example above passes the type checker.

Am I missing something here? Tested against 0.45.0 [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodATApgYxgQwCcswBbODAVxhIFkwBvVMMbPIkqSgOxwBcAlnG5gARkQAUUOHABcYAEIBKeQDc4AjAG5mYXWwLEw7AM4mwAQUa6W0uWKI6WAX3QsDHYwTOKwWAB58WNwY5lZMLqiuqHwAngAOJABiIgC8YFIy8gAiSmCpAHxg6propuYAwta2WWApUWXe5tl+gcGhYFUMzkA).

**Comment by SamChou19815** [comment]
This should be fixed now
