### ISSUE TITLE
String concatenation messes up string enum logic.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#3890]
Here's a contrived example:

```js
const foo = false
type Flags = 'g' | 'gi'
const myFlags: Flags = `g${foo ? 'i' : ''}`
```
Yields the error `Error: Flow: string. This type is incompatible with string enum`

My actual use case:

```js
function foo(str, regex) {
  const regexFlags = `g${regex.ignoreCase ? 'i' : ''}${regex.multiLine ? 'm' : ''}`
  const globalRegex = (regex.global) ? regex : new RegExp(regex.source, regexFlags)
  ...
}
```

Same error. Is this a shortcoming of Flow, or am I doing something wrong?

**Comment by vkurchatkin** [comment]
Flow doesn't actually execute code, so it has no way of knowing what result of  `g${foo ? 'i' : ''}` is.

**Comment by AndrewSouthpaw** [comment]
Is there a way to tell Flow to not worry about it?

**Comment by vkurchatkin** [comment]
Yes, use `any` like this:

```js
const myFlags: Flags = (`g${foo ? 'i' : ''}`: any)
```

**Comment by AndrewSouthpaw** [comment]
Brilliant, thanks so much for your help! I'm new to Flow. :)
