### ISSUE TITLE
Strange $Diff behaviour

### ISSUE THREAD

**Issue by dmnd** [facebook/flow#3897]
[Try flow example](https://flow.org/try/#0C4TwDgpgBA6glsAFgSQCJQLxQN4CgpRwAmAXFAHYCuAtgEYQBOANPlMAgDYRkDOwDccgHMWAXwDcuXAHppUAHIQAHsCZsA7gHsomsO03keUAGaaGUagEMA1oKFRLUAG6MecA1HUJEmysAfkhEQAdDJyyGyIgtaREDzQlgzQEACOlHBOllzk-qCQPGq0flAAYhya6lBEcDyWQklxoXnQ8Ei+wMhEAGpwlqhwxsaYUAAk-YMAPK0oqGrYxGRUdIyiAHySzbDe7Z09lgDy1DVuHljY7MBcvPx2ElKyUACCPG5C5HYOW21+u72Hx+5AsBtI5pjtur1xkMtAxrDxQgBjAx8KBKMhgn4QvoDIZYAAU5043CgAHISaJ0dtMXt-i9AQBKSRhKAAIWKljpbw+oKpHSxULYIK+PmpfyOdI8RE0cQommAwQVuCRhn8IEp3z5NPFJ0C+MJl2JZIpwvBeyhjKAA)

```js
type WithID = {
  id: number,
  title: string,
};

// Next, two options for making a version without an id.
// I think these are equivalent types, but Flow disagrees.
type WithoutIdViaDiff = $Diff<WithID, {id: number}>;
type WithoutIdViaOmission = {title: string};

// Assigning a WithoutIdViaOmission to a WithoutIdViaDiff works.
const x: WithoutIdViaDiff = ({title: ''}: WithoutIdViaOmission);

// But assigning a WithoutIdViaDiff to a WithoutIdViaOmission does not...
const y: WithoutIdViaOmission = ({title: ''}: WithoutIdViaDiff);
```

Interestingly, the error says 

```
15: const y: WithoutIdViaOmission = ({title: ''}: WithoutIdViaDiff);
                                     ^ WithID. This type is incompatible with
15: const y: WithoutIdViaOmission = ({title: ''}: WithoutIdViaDiff);
             ^ object type
```

It's interpreting `({title: ''}: WithoutIdViaDiff)` as having type `WithID` even though there's an inline type annotation. Strange.

**Comment by madbence** [comment]
maybe it's a bug? even the [example in the docs](https://flow.org/en/docs/types/utilities/#toc-diff) is failing:

```js
type Props = { name: string, age: number };
type DefaultProps = { age: number };
type RequiredProps = $Diff<Props, DefaultProps>;

function setProps(props: RequiredProps) {
  props.name;
}
```

```
6:   props.name;
           ^ property `name`. Property cannot be accessed on
6:   props.name;
     ^ Props
```

**Comment by nmn** [comment]
It's a known limitation of `$Diff` right now. It can only be used as a requirement and not for usage. There is some work being done to improve the situation. Sadly, it's not an easy problem.
