### ISSUE TITLE
Catch-22 edge case for Flow; decorators and prop types clashing

### ISSUE THREAD

**Issue by ffxsam** [facebook/flow#3904]
First off: hats off to the Flow team. Seriously amazing work. My team and I have been discussing using this on our project, and decided it was a good idea. But disappointingly I've hit a brick wall and I'm not sure how to proceed.

Let's say I have a component that renders out:

    <Person name="Bob" age={33} />

The component looks like this (entire module below):

```js
// @flow

import React, { Component } from 'react';
import injectSheet from 'react-jss';
import PropTypes from 'prop-types';
import type { Styles } from '/imports/types';

const styles: Styles = {
  root: {
    fontWeight: 'bold',
  },
};

@injectSheet(styles)
class Person extends Component {
  props: {
    classes: Styles,
    name: string,
    age: number,
  };

  render() {
    const { classes } = this.props;

    return (
      <div className={classes.root}>
        {this.props.name} is {this.props.age}
      </div>
    );
  }
}

export default Person;
```

I get a Flow error because in my first component, I'm not passing `classes` in. But I don't need to, obviously, since the `jss` HOC is doing that. The only solution is to not use decorators and instead do `export default injectSheet(styles)(Person)`, but then I lose type-checking and Flow thinks this is valid:

    <Person name="Bob" age="dunno" />

What's the proper course of action in this case?

**Comment by nmn** [comment]
1. You already know the fix, you need to not use decorators and use `export default injectSheet(styles)(Person)` instead.

The other part of that is that you need to add types for `injectSheet`. You should probably read the Higher Order Components part of the docs, but this is more or less what you want the types to be:

```typescript
type

declare module 'react-jss' {
  declare var exports: (styles: Styles) =>
    <D, P, C: React.Component<D, P, any>>(component: Class<C>) =>
      Class<React.Component<D, $Diff<P, {classes: Styles}>, any>>;
}
```

**Comment by ffxsam** [comment]
I tried wrapping my head around declaring types for HOCs but I don't get it. I barely even understand generics (I don't experience in any language that uses them), so I'm really struggling here.

BTW, did you mean `React$Component` above?

**Comment by nmn** [comment]
@ffxsam I can't give you a full tutorial on generics here, but when you read `<D, P>` say it like `for some types D and P`. Of course in my example, `D` is some type for `DefaultProps` and `P` is the type for Props. But since we are writing the function for all components we say for any types `D` and `P`.

Also `React$Component` and `React.Component` are inter-changeable. The only difference being that the latter requires you to import `React`.

**Comment by ffxsam** [comment]
@nmn Thank you, your libdef worked. I'll have to ponder on that (and generics).

Side note: is there some sort of way to dump types to the console? e.g.

```js
type SomeType = {
  ...
};

console.log(SomeType); // obviously won't work
```
