### ISSUE TITLE
Implied true boolean value not checked properly

### ISSUE THREAD

**Issue by ffxsam** [facebook/flow#3909]
If I have a `Person` component that takes a name as a string, Flow correctly shows this as invalid:

    <Person name={true} />

However, this passes even though it's the same effect as above:

    <Person name />

**Comment by asolove** [comment]
This has been fixed in v0.53: [see example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugApZSoQB2cWADxhYeAE3TY8MAHQBhEpB4iYAHgQAaBAD44Abzpw4lMZwAUASj0HDRrDACuUPitHAAblt0wAFsFTSwYjB-HmQQLABfFQB6Vw9rQwAfBhUOLl44UPC4aK0gA)

(I think this issue can be closed, @calebmer)
