### ISSUE TITLE
Typechecking for dependency injection?

### ISSUE THREAD

**Issue by pyros2097** [facebook/flow#3916]
I use dependency injection in my code like given below. Is there some way I can typecheck the dependencies without importing the types. Basically I know logger implements the Log Interface so can I equate logger = type Logger interface somewhere in flow's configuration so that I could get type checking and code completion. Or would I have to manually parse this code and and fill in the type information and pass it to flow, since for the purpose of injecting the parameters I get the toString() of the function and regex match its params to the services map.
```js
module.exports = (
  logger,
  config,
  http
) => {
  const server = http.createServer((req, res) => {
    logger.info('Request: ', req.url)
  })
  return {
    start: () => {
      logger.info('Server starting on port 3000')
      return server.listen(3000, (err) => {
        if (err) {
          return logger.error('Server startup failed', err)
        }
        logger.info('Server shutdown successfully')
      })
    },
  }
}
```

**Comment by madbence** [comment]
I'd refactor your code into something like this:

```js
import type {Dependencies} from '...';
module.exports = ({logger, config, http}: Dependencies) => {
  // ...
};
```

If you want to keep your angular-style dependency injection, you have to annotate every parameter manually.

**Comment by pyros2097** [comment]
hmm... seems nice... I guess this is the only way to solve this for now.

**Comment by madbence** [comment]
also, this way you can avoid the `toString()` parse :sparkles: magic :sparkles:
