### ISSUE TITLE
Refinements do not work with destructuring

### ISSUE THREAD

**Issue by echenley** [facebook/flow#3918]
```js
type LoadingProps = { isLoading: true, item: null }
type LoadedProps = { isLoading: false, item: { id: string } }
type Props = LoadingProps | LoadedProps

const Works = (props: Props) => {
  return props.isLoading ? null : props.item.id
}

const DoesNotWork = ({ isLoading, item }: Props) => {
  return isLoading ? null : item.id
}
```

https://flow.org/try/#0C4TwDgpgBAMg9gQwCYEsB2BzACgJzmAZygF4oBvKFA+ZdDALimBwFcIAaJlAYwGsJgjNCwA2IqAF8AUKEixESCElz4ipClRqpMjAGYIRBDlz4DGGpIwLM6kyTPDQVhEvNqZnRAD5vFyvIRSUtxwaNZQAOpwOLxqUAAUYAEEjJ4AlCQAfORSUFA4Aiw4aFBJqgB0mgq2APxQwmJQjGWE5cA8-MCVSFLSwaHhACJwEAQAcnDAUTGu8RrU1Zic7abAkqnJGcTZZLn5hcWUC+4YUHUN4owrnd29UkA

**Comment by jfirebaugh** [comment]
This is the same issue as #3932, #5212, and other dupes.

**Comment by goodmind** [comment]
Duplicate of #3932
