### ISSUE TITLE
`super` broken within class static methods

### ISSUE THREAD

**Issue by popham** [facebook/flow#392]
The following doesn't typecheck.

```
class A {
  static a(): number {
    return 5;
  }
}

class B extends A {
  static a() {
    return super.a() + 10; // NG by Flow
    // Fails with "Method cannot be called on ...empty super object"
  }
}
```

The `super.a()` should resolve to `A.a()` (see http://www.2ality.com/2015/02/es6-classes-final.html#the_prototype_of_a_subclass_is_the_superclass or trace DefineMethod(constructor, proto, functionPrototype=constructorParent) from `14.5.12`, ES6 release candidate 3).

**Comment by avikchaudhuri** [comment]
This has been fixed, closing.
