### ISSUE TITLE
CLI option "get-importers" isn't available

### ISSUE THREAD

**Issue by scottambroseio** [facebook/flow#3920]
Hey all,

According to https://flow.org/en/docs/cli/, the flow-cli has a `get-importers` cli flag which "Gets a list of all importers for one or more given modules". This option doesn't seem to be available on the cli.

Expected: Either for the option to be available and usable as described, or for the documentation to be updated to reflect the command not being available / removed in version X / not available on Windows etc.

Here's a section of my output from running `flow --help`, where `get-importers` isn't listed.

![missing](https://cloud.githubusercontent.com/assets/7337433/25950974/37afb572-3654-11e7-91ae-9c96813da739.png)

Flow, a static type checker for JavaScript, version 0.45.0
OS Windows 10

**Comment by bradencanderson** [comment]
The 0.41.0 release notes say:

> `flow get-importers` has been removed. It was rarely used and added an incredible amount of complexity to the codebase

**Comment by scottrangerio** [comment]
Ah, that makes sense, thanks for the clarification.

**Comment by Overload119** [comment]
Documentation should be removed then.

**Comment by bannier** [comment]
Is there an alternative way to get those importers ? All I can think of is using webpack stats.

**Comment by bradencanderson** [comment]
You could remove a file and look at the errors that show up :)

**Comment by SamChou19815** [comment]
The doc no longer says such command exist.
