### ISSUE TITLE
Need a mechanism to make flow ignore certain properties on objects

### ISSUE THREAD

**Issue by evelant** [facebook/flow#3923]
I have a type for the data that I insert into my database.

Example:
```
type MyType = {
   _id: string,
   myValue: string
}
```
When I insert the data I don't want to include the _id because it is generated by the database. When I fetch the data I want to assume that the _id property is always set. I cannot do this with flow as far as I can see.

I tried setting up my insert function as follows in an attempt to allow an object without an _id to be inserted, but an intersection with the optional property does not seem to override the original property.

```insert(doc: (T & {_id?: string}), callback?: Function): string,```

The only solution I can see would be to have two separate types, one with an _id and one without then change my insert function to take the one without, but that feels like a kludge. Shouldn't I be able to tell flow "completely ignore this property on this type"?

**Comment by vkurchatkin** [comment]
Try something like this:

```js
declare class Collection<Doc> {
  fetch(id: string): {| ...$Exact<Doc>, _id: string |},
  insert(doc: {| ...$Exact<Doc>, _id?: string |}): {|...$Exact<Doc>, _id: string |},
}

type Doc = {
  foo: string,
};

declare var collection: Collection<Doc>;
const doc = collection.insert({ foo: 'bar' });
const id: string = doc._id;
```
