### ISSUE TITLE
Why is NPM module not found?

### ISSUE THREAD

**Issue by barbu110** [facebook/flow#3924]
I have flow version `0.46.0` and the following `.flowconfig` located in the root of my project:

```
[ignore]
.*/node_modules/.*

[include]

[libs]

[options]
module.name_mapper='^styles\/.*' -> '<PROJECT_ROOT>/build-helpers/flow/StyleImport.js'

esproposal.decorators=ignore
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
```

Now here is a file that gives errors:

```js
/**
 * @flow
 */

import CSSModules from 'react-css-modules';
```

When I run `flow` I get:

```
  9: import CSSModules from 'react-css-modules';
                            ^^^^^^^^^^^^^^^^^^^ react-css-modules. Required module not found
```
although I have `react-css-modules` installed and even saved in `package.json`. Is this because there are no type declarations for this library?

**Comment by gaastonsr** [comment]
I'm new to flow but I think it's because you're ignoring node_modules.

Have you tried 

```
$ npm install -g flow-typed
$ cd /path/to/my/project
$ npm install
$ flow-typed install
```

**Comment by barbu110** [comment]
Apparently, the module was not found because of the issue stated in #869. Shortly, there is no way to ignore a directory/file without completely eliminate it from equation.

The reason why I wanted to ignore `node_modules` was the large number of errors coming from libraries that I don't own, but this seems to make `flow` think they don't exist at all, instead of simply not typechecking them.

**Comment by gaastonsr** [comment]
I think if you do flow-typed it will mock all your dependencies.

**Comment by barbu110** [comment]
`flow-typed` only has type definitions for some _select_ libraries. I would still have to write my own definitions for the rest 75% of the libraries

**Comment by gaastonsr** [comment]
I think it will generate `any`-typed stubs for untyped dependencies...

**Comment by barbu110** [comment]
Apparently there is [this](https://github.com/flowtype/flow-typed/blob/master/cli/src/commands/create-stub.js). I haven't tested it or read it, but I think that's what it does.

**Comment by TrySound** [comment]
Just STOP ignoring whole `node_modules`. If you have some broken types, add them to `[untyped]` section which works similar to `[ignore]` but treats matched modules as `any`.

This probably can be closed.
/cc @vkurchatkin
