### ISSUE TITLE
Run script for require replacement instead of module.name_mapper

### ISSUE THREAD

**Issue by barbu110** [facebook/flow#3926]
I am working on a project which works with Node libraries via NPM. Since it got pretty big, I wrote a library that does some kind of named module `require` (like Haste does). 

Since I have a hybrid, I cannot use

    module.system=haste

Because React will start pumping errors, and cannot use

    module.system=node

because my Haste modules will not be recognised. Implementing a `module.rename_script` option in configuration would be nice so as to be run for each `require`d module and `export` the correct require reference. 

I could take this on so I can push a PR but I have no idea where to start. So, if you guys don't have the time to solve it, I would like to be given some indications. Thank you!

**Comment by SamChou19815** [comment]
We are unlikely to support this due to arbitrary code execution concerns, and because Flow is written in OCaml.
