### ISSUE TITLE
Flow doesn't track return statement correctly when using `Object.keys`

### ISSUE THREAD

**Issue by EvNaverniouk** [facebook/flow#3927]
The following code:

```
/* @flow */

const a = function (obj: ?{}) {
 if (!obj) return null;
  
 Object.keys(obj).forEach((key) => {
	console.log(obj[key]);
 })
}
```

Returns the following flow type errors:

```
7: 	console.log(obj[key]);
                ^ access of computed property/element. Computed property/element cannot be accessed on possibly null value
7: 	console.log(obj[key]);
                ^ null
7: 	console.log(obj[key]);
                ^ access of computed property/element. Computed property/element cannot be accessed on possibly undefined value
7: 	console.log(obj[key]);
                ^ undefined
```

Which makes no sense because there is absolutely no way `obj` can be `null` inside the `Object.keys` loop since it was escaped using the `if` statement above.

Reproduced here: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMwBeMKAV2w3wEscwAKOAIwCsAuMAfgG8AvgEowfVGDpRmAQjbsRAJwCm+SguxhslGDADc4sOIDyHJbQB0AayUBPXCw5DzUOAoCiRDAAsmTazZFSAD5RVABILDw4GCVzeABzB3YAbX8AXSF9MGFUAVQgA

**Comment by gaastonsr** [comment]
I've been testing flow and this is the type of things that disappoint me.

Anyway, the [solution](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMwBeMKAV2w3wEscwAKOAIwCsAuMAfgG8AvgEowfVGDBY8hOGTBt2AbnFgVdKM1mly2SjBgixEiQCcApvkonsyiQJWqJAeQ5naAOgDWZgJ64WQu5QcCYAokQYABZMTN4+IqQAfKIOUrhwMGbu8ADmLADacQC6QrZgwsr2QA) and [explanation](http://stackoverflow.com/questions/41234392/possibly-undefined-value-how-to-make-null-safe).

**Comment by EvNaverniouk** [comment]
@gaastonsr Thanks for that. The proposed solution feel messy to me. I just ended up doing this instead:

```
/* @flow */

const a = function (obj: ?{}) {
 if (!obj) return null;
  
 Object.keys(obj).forEach((key) => {
	if (obj && obj[key]) console.log(obj[key]);
 })
}
```
