### ISSUE TITLE
After 0.46 change to rejected promises incorrect errors are shown

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#3928]
As far as I can tell the code below does not have the errors Flow 0.46 claims. It seems impossible to me that those types mix.

The code in `serialize` is written so that there are two paths: One that is used only internally, and one that is returned. Internally rejected promises are caught, *but those are never returned*! The purpose is to prevent a rejected promise from canceling the serialization chain. But the returned promises *are* rejected!

Flow wants me to add "`| Error`" to the return type of function `append1To1Entry`, but that's wrong, it cannot happen as far as I can see. The code below includes demo code that shows that rejected promises indeed don't lead to the return of an `Error` object. Only `string` is returned if the promise resolves.

The return type of the serialized function is *never* the `Error` object from the purely serialization-function-internal transformation of rejected promises to `Error` objects, that remains within the serializer and is not leaked.

```javascript
// @flow
'use strict';

type PromiseFn = (...args: Array<*>) => Promise<*>;

// Helper for the demo to get soime delay.
const wait = function (delay: number, passThroughArg?: *): Promise<*> {
    return new Promise(resolve => setTimeout(() => resolve(passThroughArg), delay));
};

/* *****************************************************************************************
 * START CORE FUNCTIONS
 */

const serialize = function (...functions: PromiseFn[]): Promise<*> {
    let p = functions.shift()();
    if (typeof p !== 'object' || typeof p.then !== 'function') {
        p = Promise.resolve(p);
    }
    let lastPromise: Promise<*> = p;
    p = p.catch((err: Error) => err);
    while (functions.length > 0) {
        p = p.then(functions.shift());
        lastPromise = p;
        p = p.catch((err: Error) => err);
    }
    return lastPromise;
};

const promiseTypes: Map<string, Promise<any>> = new Map();

const serializeWithType = function (type: string, ...functions: PromiseFn[]): Promise<*> {
    let p: ?Promise<*> = promiseTypes.get(type);
    if (p === undefined || p === null) {
        p = serialize(...functions);
    } else {
        p = serialize((pp => () => pp)(p), ...functions);
    }
    promiseTypes.set(type, p);
    return p;
};

/*
 * END CORE FUNCTIONS
 * *****************************************************************************************/

// Function that demos the functionality and shows Flow concrete code to check
// the above functions against
// Flow wants me to add " | Error" to the return type - WHICH IS WRONG
const append1To1Entry = function (arg): Promise<string> {
    return serializeWithType(
        'Storage.write',
        () => wait(100).then(
            () => arg ?
                Promise.resolve('Yep!') :
                Promise.reject(new Error('Mistakes were made'))
        )
    );
};

// Runtime demo showing that a rejected promise indeed rejects and that only "string" is
// returned by resolving promises
append1To1Entry(true)
.then(v => console.log('RESOLVED', v))
.catch(err => console.error('REJECTED', err));

append1To1Entry(false)
.then(v => console.log('RESOLVED', v))
.catch(err => console.error('REJECTED', err));
```

Flow errors:

```
$ flow check
src/test.js:21
 21:     p = p.catch((err: Error) => err);
                                     ^^^ Error. This type is incompatible with
 48: const append1To1Entry = function (arg): Promise<string> {
                                                     ^^^^^^ string

src/test.js:25
 25:         p = p.catch((err: Error) => err);
                                         ^^^ Error. This type is incompatible with
 48: const append1To1Entry = function (arg): Promise<string> {
                                                     ^^^^^^ string

Found 2 errors
```

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/1576

**Comment by lll000111** [comment]
Is this really the issue?

Apart from the referenced "duplicate" being a ticket from last year and this problem only occurring with the very recent Flow 0.46, my point is that it isn't even *relevant*!  The issue Flow thinks it detects is on an object that is never returned to the outside!

**Comment by vkurchatkin** [comment]
I guess it's something else then. Can you make a smaller example?

**Comment by lll000111** [comment]
I'm not sure this is actually fixable since it's how Flow works, after giving it some thought. The problem is entirely in the `serialize` function (you can ignore all else, so much for the "smaller example").

As I see it, Flow finds all possible types that a given variable can get. From Flow's perspective it is entirely reasonable to say "Variable p can point to Promises that resolves with an `Error` object". I think it would take a lot of code changes to Flow to do much more checking on the Javascript code to find that when variable `p` is assigned to variable `lastPromise` it can never had an `Error` value. This would mean Flow doesn't just look at all possible values but also looks at *when* and *where* assignments to variables are made.

**Comment by lll000111** [comment]
The test code can be cut down to this:

`´´javascript
// @flow
'use strict';

type PromiseFn = (...args: Array<*>) => Promise<*>;

const serialize = function (...functions: PromiseFn[]): Promise<*> {
    let p = functions.shift()();
    if (typeof p !== 'object' || typeof p.then !== 'function') {
        p = Promise.resolve(p);
    }
    let lastPromise: Promise<*> = p;
    p = p.catch((err: Error) => err);
    while (functions.length > 0) {
        p = p.then(functions.shift());
        lastPromise = p;
        p = p.catch((err: Error) => err);
    }
    return lastPromise;
};

const append1To1Entry = function (arg): Promise<string> {
    return serialize(
        () => arg ?
            Promise.resolve('Yep!') :
            Promise.reject(new Error('Mistakes were made'))
    );
};

append1To1Entry(true)
.then(v => console.log('RESOLVED', v))
.catch(err => console.error('REJECTED', err));

append1To1Entry(false)
.then(v => console.log('RESOLVED', v))
.catch(err => console.error('REJECTED', err));
`´´

**Comment by gabelevi** [comment]
Thanks for reaching out! I think your problem is that you're trying to write a generic function `serialize` without using generics. Try [something like this](https://flow.org/try/#0MYewdgzgLgBBCmAnAlgQwDbIF7xgXhgDMBXMYKZcAHgBUA+GACgDpWSyLwIAuGAQUSJUATyqMAlPgYAFRCAC2yBLTp1xvWQqXwVMAN4AoGMZjp4sAA74ipcpUjMIAC2SEoEiQG4jJs7HSo0JqKCNYW3iYwVgQWzMCoUMBOjIxIiLwAooIgiJJ4DGniESYA7i5mTOx2XMxmYADmUE4wDAAMkoaRkdFRzE3wYIxVnA7Oru7iRT5dpoFQwdphxTM9sfGJyamCmdm5UjCFyzAAvtMwiObEiGCzQXIh8N7H3gagkLCoFhYDACYAjDQQH8MmAoIhhNZhvYmKhEPV1DAFspoCgGgxOiYLlArjcECgMNh4IwzpEJPskfBmBcICB0AA3IkAckIIBAjPEZymzyAA).

The `*` auto-inference operator is a little tricky. It has a bunch of gotchas, so I'd recommend avoiding it as much as possible.

The change to `Promise.prototype.catch` (https://github.com/facebook/flow/commit/eb541555faf2e5e2dbddd6d4bf9633870a925fa7) looks right to me, so I don't think there was a regression.

**Comment by lll000111** [comment]
@gabelevi  Independent of the likely merits of your points, that isn't the issue.

**Comment by lll000111** [comment]
@gabelevi Thanks, but now try that with the more complete example I started with... :-(

**Comment by gabelevi** [comment]
[Works for me](https://flow.org/try/#0C4TwDgpgBACgTgewLYEsDOEBiA7APAFQD4oBeKACgDpqBDOAczQC4oBBOOGkXVADwgAmhAJSli8ZOggFCAbgBQ8gPRKoACQgAbSHCgAzBLuAALaAIhIEUYFfoRgUNAhRIzWrpXkBjBNjQOAdxoUBzI9AFdsL2AUXxkKc00uFmxwpAAjCDgAGigwGjQ0fGNEcPpjdnoWfGEWCVQMeIBveSg2qDh7cLhsKGwIANhEBohyTqdNADdoEmIMYHwXCARw4HJyUVmOiAnp8nzC4tLyyuFcxK5hYQUAXwVlACooB5fXt-ePz6-vn9+-39aTwAyvhWAAlfBQADCAHkwQBRKCYACqADkofgAJIw1FAwFKRQ+PwODBwFA0TQoABeM30kWisTwRAo1EoESiMV8zCGkgwOBkAG0ALq1HkjZqtdqaex5Uh0jmMtCUNDGFB6NbCDYKdpQNUUUCQBB6WUAQhIZAA5Ah0gArCDRC1QAA+Tus4GWxrAlBMEF6Zst7IZvgtohaOp1YDl9SklHGCCmozA10lbRuKag0ocSX80YwcrA2vakbIXq8NGAXmM6yycBY8I4hk2xBryZ1AVV0oogc5fko0uw9BMUGIAAZQ+mI-nvaZsORu4rlar1RtW+G2tngLnaQWJ0Wp2WK1XyDW6w24E2oC3C6n051gN1ehut7d7kT-HlhlJ8O7uQBZGhgLg-hkgOuRbrgNDYCAhDEGQ-SDP+YBaoSXIklk5KUjSADqITGN+kByvOcTMuQBoQCwwEoKBUCskRfh1J+fJMoQwqiuBzJhlKMpgCwAD84EPLBH68hA+E7JQdhrGRq5tHq+ykOaUCROYehUYIzqusWimpJomjjmubTFo46EUtSoy0fSPZoDJUA3Jemh5pxa5GaSGFmesYDFsQGxiHkSb7GcNHUHR1nXrZ6ZgIxok-sq9ike6uRJmFd4PnkL6KEoDyAlA8KogAItCcKIii6JYjieLPM8-zVTVtV1f8BLKKomCWYy1jGOWUDmJYaDtdAdGmaAUCQQIjjGAgAS9ZgmgTVARJeHe0A+OY1hWJW9oANZNX1w3pAg0zykGfjDfQwTEtt02zUE2DAL1rircNAijQARM6OVnq9Ng7SlPRugRAC0UBYWomJQmoUCYkCQNgjiADi3iocNnm+gIACM+AIKj8I3XAICEa1vgUHQ9BsVFQHACB9DEE52z3r9rmmdhuFieQu5tBaQI2JwdiUAEZLABAFrZGzFAXkEITkKjI5jtOvqswZ4Y+VsxNQLxIsK1usY7PGewWgAmhAYAmiGUBMOrBma50drROQ8HvYgcDkBav7oMANAbTsUABFk0BIDQ5ghsIItBzqyZ3BlqhgpEMT3d1VgqhNVH0O1nU0Ns1sC6NkUibq2DmOpVv2rdw15ynDi+JoePPZRA6veg20-f0o3pHjcZTEnwkjGg8gAZAefo5j2MUyApFwOEEBB7Ls6TL5b7xhAfYIPQTsIkCMIADIAGrwnlQtQJMVzyJQB6VseHCz1y8+UDWhgr-CABS8IYjve8tsmPfI-3GNYzjI96BSGBJ4+mnhfPwV8ZrLwtKvDe29d65APpPE+VYaygImAvG+jsoEPyfvgF+uQ36yCAA)

* I added generics to most things
* I removed the type annotation from `p` inside of `serialize`. `Promise<T>` would be wrong, thanks to the `p = p.catch(...)` calls. `let p: Promise<*> = functions.shift()();` was probably over-eagerly choosing `T` for the `*` thanks to that assignment.

**Comment by lll000111** [comment]
I could no use the `type` type, so I inlined that little type (the `args` were not needed anyway). I had to make a few changes to other functions elsewhere too. Works now.

**Comment by lll000111** [comment]
Incidentally, for the record and to illustrate a point, it seems Flow behaves differently when using generics.

For example, I "generified" all functions in that promise-helpers module from which the serializer function above is from. One of them was:

```js
// Original header:   function     (delay: number, passThroughArg: *): Promise<*> {
module.exports.wait = function <T> (delay: number, passThroughArg: T): Promise<T> {
    return new Promise(resolve =>
        setTimeout(
            () => resolve(passThroughArg),
            delay
        )
    );
};
```

I tried to check if I still got error messages when doing something like below which sends a number to a function that wants a string:

```js
wait(100, 42).then((arg: string) => {...});
```

I got a much better error message using the generics version of `wait`. Compare (first the error from the "*"-type version, then the error from the version with generics):

```
src/promise-helpers.js:29
 29:             () => resolve(passThroughArg),
                               ^^^^^^^^^^^^^^ undefined. This type is incompatible with the expected param type of
198:         await PromiseHelpers.wait(100, 1).then((arg: string) => PromiseHelpers.retry(
                                                          ^^^^^^ string. See: src/storage-access.js:198

Found 1 error
```

So it does show an error, but what's that `undefined`, and why does it show an error inside the `wait` function? The next one is *much* better:

```
src/storage-access.js:198
198:         await PromiseHelpers.wait(100, 1).then((arg: string) => PromiseHelpers.retry(
                                            ^ number. This type is incompatible with the expected param type of
198:         await PromiseHelpers.wait(100, 1).then((arg: string) => PromiseHelpers.retry(
                                                          ^^^^^^ string

Found 1 error
```

This message shows the actual error and the correct locations in the code.

*However*: Flow did not get any more information by switching to generics as far as I can see. Sure, I make the _claim_ that the returned promise-type is the same as the one from the `passThrough` argument, something that wasn't there before. But Flow still has to check that this is true, and that should be the same checks compared to the "*"-type?
