### ISSUE TITLE
Add ability to annotate the export of a module

### ISSUE THREAD

**Issue by gajus** [facebook/flow#3930]
I have project that consists of many site-specific instructions that share a common interface, e.g.

```js
/site/site-a.js
/site/site-b.js
/site/site-c.js
/site/site-d.js
/site/site-e.js

```

Each of the files export the same methods, e.g. `doA`, `doB`, `doC`.

As a result, I now need to add type annotations to each file and each method, e.g.

```js
import type {DoAType, DoBType, DoCType} from './types';

export const doA: DoAType = () => {};
export const doB: DoBType = () => {};
export const doC: DoCType = () => {};

```

This creates a lot of redundancy and it does not guard against missing methods.

What I'd like to do is to able to annotate export interface of a module, e.g.

```js
import {DoModuleType} from './types';

declare exports DoModuleType;

export const doA = () => {};
export const doB = () => {};
export const doC = () => {};

```

Where `DoModuleType` is:

```js
type DoModuleType = {|
  +doA: DoAType,
  +doB: DoBType,
  +doC: DoCType
|};

```

**Comment by gajus** [comment]
I've been looking into the docs of https://flow.org/en/docs/libdefs/creation/#declaring-a-module-a-classtoc-idtoc-declaring-a-module-hreftoc-declaring-a-modulea, but as far as I understand, these can be used only to declare export types of named module imports. Not the current module.

**Comment by billschaller** [comment]
Flow doesn't support typing a module itself, and given that the 'type' of a module (es6, commonJS) is defined by the export format, I don't think this is a good feature candidate.

You could just do:
```js
import type {DoModuleType} from './types';
export const doA = () => {};
export const doB = () => {};
export const doC = () => {};
const module: DoModuleType = {doA, doB, doC};
export default module;
```

That would cover type checking within the module, and would allow you to do:
```js
import type {DoModuleType} from './types';
import ModuleA from './ModuleA';
(ModuleA: DoModuleType); // OK
```
