### ISSUE TITLE
Custom string value validation

### ISSUE THREAD

**Issue by kof** [facebook/flow#3933]
Use case
When writing cssinjs, currently we can validate only properties and simple values. When a string value is composed out of multiple strings for e.g. `{border: '1px solid red'}`, we can only tell the value should be a string. What we would like to tell is much more, basically it could use a full CSS value parser.

**Comment by billschaller** [comment]
Given the wide variety of things you *could* want to check a string for, this is outside the scope of Flow and should be handled in userland.

**Comment by kof** [comment]
I was asking for a hook that allows to implement any custom validation in USERLAND. Or is this already possible?

**Comment by billschaller** [comment]
Flow is a *static* type checker. You can statically validate that a value is a literal, or that a value is a specific type, but you can't statically check the contents of a value.

**Comment by kof** [comment]
What if we could have a custom type defined in the user land, which checks whatever is needed, not just primitives typeof check?

**Comment by billschaller** [comment]
You mean you would want to write some sort of OCaml module to do your custom type check?

Can you give an example of how you would want to write and use that?

**Comment by kof** [comment]
Something like this:

```js
defineType('CssValue', (value) => {
  if (typeof value === 'string') {
    parse(value)  // throws if value is invalid
  }
})

type style = {
  border: CssValue
}

{
  border: '1px solid red'
}: style
```

**Comment by TrySound** [comment]
@kof It looks like opaque types in the next flow version. But it will require to use function wich returns such type.
/cc @andreypopp

**Comment by billschaller** [comment]
This would require Flow to actually execute the javascript code it is analyzing. AFAIK that's not on the roadmap.
