### ISSUE TITLE
Cannot refine maybe type on object if method is called prior

### ISSUE THREAD

**Issue by magicmark** [facebook/flow#3935]
#I've come across some weird behaviour trying to refine maybe types, following the example [here](https://flow.org/en/docs/types/maybe/#toc-refining-maybe-types).

Consider the following reproducible example:

```javascript
// @flow
type FooContainer = {
    getFoo: () => string,
}

const myFooContainer = {
    getFoo: () => 'foo'
};

const sayMsgs = (msg1: string, msg2: string) => {
    console.log(`msg1: ${msg1}`);
    console.log(`msg2: ${msg2}`);
}

class App {
    fooContainer: ?FooContainer = myFooContainer;

    sayFoo () {
        const getAnotherMessage = () => 'another message';

        if (this.fooContainer !== null && this.fooContainer !== undefined) {
            /**
             * Works:
             *
             * sayMsgs(
             *     'a message',
             *     this.fooContainer.getFoo(),
             * );
             */

            // Does not work:
            sayMsgs(
                getAnotherMessage(),
                this.fooContainer.getFoo(),
            );
        }
    }
}
```

Running flow with latest version (0.46.0) produces the following error:
```
test.js:34
 34:                 this.myFooContainer.getFoo(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `getFoo`. Method cannot be called on possibly null value
 34:                 this.myFooContainer.getFoo(),
                     ^^^^^^^^^^^^^^^^^^^ null

test.js:34
 34:                 this.myFooContainer.getFoo(),
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `getFoo`. Method cannot be called on possibly undefined value
 34:                 this.myFooContainer.getFoo(),
                     ^^^^^^^^^^^^^^^^^^^ undefined
```

Changing the method call `getAnotherMessage()` to a string fixes the issue. This is clearly unrelated to the line below, so it looks like a bug to me?

Thanks!

**Comment by magicmark** [comment]
fwiw doing something like this appears to 'fix' the issue:

```javascript
const fooContainer = this.fooContainer;
sayMsgs(
    getAnotherMessage(),
    fooContainer.getFoo(),
);
```

**Comment by samwgoldman** [comment]
This is documented behavior: https://flow.org/en/docs/lang/refinements/

**Comment by borela** [comment]
@samwgoldman [Why is the error being triggered by the line before the one that shows the error? In his example](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagGK1gMKwB2yAhgJbGYBOoAvKAN6KhugDmmyesAXKAAUASgYA+UAGdkNKhwA0iAL6JEAYxLTQAW1S8ipStTqMW7Tt14CR40AHJI+O8oDcqjcS2SyqALKSOSQYhbQCARgFpWWIFHQCAJkiZOVF6CTN2D0lYaEwAOjgOQQADUI4I0AASJjKwpWLhN3MsnPzCkrLEqpqE+sbld2gySSCAQXR0ZlZ2R0IScipaAQB+fXmjWmDdNcNFmjdptm89fCFRDPM2LOQLZFHiWGQAC1pfTBGyLmCbNPsyB+em20728XDsB0u7AokCEzwokjyswMC2MoAAhPRGMQAK7QaCgABkBNAcIRSPWe3RmNA2OIABNMJBFnTzodIewQKAAOqwGgAa0kbPZoGAACpRcAhcLjv5AoIpcL2HYyDoQZ9MHZFIrhaTEfhkRsaHkuDx8CItdq2P1LSLxZKFZdOQARWDvUAA0DwXl8vIO8xiiV+9gygKSeU28wm+6PF40N4fLjmoOQ3Xk3bGY2WM3CC3a62WgOS4UqcwqJRAA) You can see that changing the previous argument from `'a message'` to `getAnotherMessage()` *causes flow to complain on the next argument* `this.fooContainer.getFoo()` which was used before and flow didn't show any errors.
