### ISSUE TITLE
Arguments to tagged templates are not checked

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3936]
This should be an error:

```js
declare function foo(a: Array<string>, b: string): string;

foo`x${1}`;
```

**Comment by bwestergard** [comment]
Relatedly, can we ensure that if treated as a variadic function, that arguments `1..N` have a given type? This, for instance, should error:

```js
function myTag(strings, ...exps: Array<number>) {
  return exps.reduce((a, b) = a + b, 0)
}

var output = myTag`foo ${ null } bar ${ 3 }`;

console.log(output);
```

https://flow.org/try/#0GYVwdgxgLglg9mABAWwJ4BUCGBzAFAZygCcYxt8AaRAOloFMAPAB3wC5EBBIozVAHjAhkAIzpEAfAEpEAbwBQjFnIC+cuQDdMRRHBBQmexAF4UGHAANgcOIgAkMxIIA2TxMsTCtdhwGY35gG41CAR8OCc6aic4PF19PUkAoA

**Comment by sibelius** [comment]
this would be good for styled-components

any progress on this?

**Comment by mroch** [comment]
fix incoming

**Comment by kitten** [comment]
@mroch I'd like to say thank you for fixing this ❤️ I tried to fix this myself before but I've only ever dived into the parser implementation. I knew it was going to be a short fix but wow! I'm glad that it's finally going to be possible to properly implement styled-components/emotion Flow typings 🥳
