### ISSUE TITLE
Property not found in X

### ISSUE THREAD

**Issue by svipas** [facebook/flow#3938]
Hello,

my suggestions is, if property not found and we're creating it, don't throw an error. For e.g.

```javascript
const obj = { a: '1' };
obj.b = '2';
```

As you can see I'm adding `b` property in `obj` and I'm getting error. My suggestion is to create new config which will ignore these errors (talking about `.flowconfig` and/or CLI arg) or ignore it by default, because I don't care if it not found, I'm creating it :smile:

I know we have workaround to make it like this: 
```javascript
(obj: any).b = '2';
```
But seriously write this every time?

P.S. The autocomplete will be also very good, if Flow will be able to recognize new added property, because even if it's added autocomplete doesn't shows it.

**Comment by Brianzchen** [comment]
When you do `const obj = { a: '1' };`, `obj` is implicitly defined as `{| a: string |}`. From a standpoint of soundness this is good and helps to prevent bugs in the future. 

Though if you want to make it dynamic, you can either type an object like the [try](https://flow.org/try/#0C4TwDgpgBAIiB2BDAtgSwMYHkBGArAKlALxQDeUAUFFIgFxQDOwATqvAOYA0VU2A-PSasO3AL4BuChXQB7eEygy89OEjRY8hEuTpQA5AEY9UCRSW4AdNmL6ATHsnS5CgK7yIiADYQAJjdKmbgwe3j4WiDaGDhRBIb5WkfbiQA) or use unsealed objects, though is generally considered unsafe and defeats the purpose of flow
https://flow.org/en/docs/types/objects/#toc-unsealed-objects
