### ISSUE TITLE
Error objects in template strings trigger flow errors

### ISSUE THREAD

**Issue by julienw** [facebook/flow#3939]
Example triggering a flow error:
```javascript
`${new Error('test')}`
```

The error is
```
    3: `${new Error('test')}`
          ^ Error. This type cannot be coerced to
    3: `${new Error('test')}`
       ^ string
```

But Error objects do have a toString method, so it can actually be coerced to a string.

Previous example in Firefox gives `"Error: test"`.

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/2814

**Comment by julienw** [comment]
Thanks. This is a little bit different to #2814 though: indeed we _do_ know that Error objects have a useful `toString` method, and being able to coerce it in templates brings more clarity than explicit coercion.
