### ISSUE TITLE
How to use Flow to enforce missing prop types

### ISSUE THREAD

**Issue by rahulthewall** [facebook/flow#3941]
The flow definition

    declare type ReactComponent<Props> = Class<React$Component<void, Props, *>> | (props: Props) => React$Element<*>;

The Title Component

    /* @flow */
    import React from 'react';
    import Helmet from 'react-helmet';
    import withStyles from 'isomorphic-style-loader/lib/withStyles';
    import styles from './Title.css';
    
    type Props = {
    	title: string,
    	subTitle?: string,
    };
    
    function Title({ title, subTitle }: Props) {
    	return (
    		<section>
    			<Helmet title={title} />
    			<h1>{title}</h1>
    			{subTitle && <h2>{subTitle}</h2>}
    		</section>
    	);
    }
    
    export default (withStyles(styles)(Title): ReactComponent<Props>);

So, now we have a Title Component that takes two props, both strings, with one of them being optional.

I then try to use the above component in another component. 

    /* @flow */
    import React from 'react';
    import withStyles from 'isomorphic-style-loader/lib/withStyles';
    import styles from './TextureDetail.css';
    import Title from '../../Title';
    
    type Props = {
    	postData: Map<*, *>,
    	postTags: Array<*>,
    };
    
    function TextureDetail() {
    	return (
    		<div>
    			<Title />
    		</div>
    	);
    }
    
    export default (withStyles(styles)(TextureDetail): ReactComponent<Props>);

In this instance I expect flow to complain that I am using the component Title without the required props, but it does not do so. How do I configure flow that it actually checks for required types. 

P.S. Apologies for asking it here, but I didn't get a response on SO: http://stackoverflow.com/questions/43936554/how-to-use-flow-to-enforce-missing-prop-types

**Comment by peteraba** [comment]
I had this issue until I enabled flow checking in webpack: https://www.npmjs.com/package/flow-babel-webpack-plugin and setup my IDE to use the installed flow binary.
