### ISSUE TITLE
get-def is cascading to the library definition when using a HOC (since v0.46)

### ISSUE THREAD

**Issue by ericm546** [facebook/flow#3942]
Since 0.46, "jump to definition" is cascading to the definition of a component rather than the last assignment. I love this change, but it cause an issue when using a HOC. 
In the following example, if in the file ParentComponent, I jump to the definition of ChildComponent, I'm redirected to the flow-typed file of react-redux 
```javascript
//ChildComponent
import { connect } from 'react-redux';
import type { Connector } from 'react-redux';
class ChildComponent extends React.Component {}
const connector: Connector<OwnProps, Props> = connect();
export default connector(ChildComponent);

//ParentComponent
import ChildComponent;
export default () => <ChildComponent />
```

**Comment by SamChou19815** [comment]
This is expected change. In the last year, get-def behavior is now more predictable that it will always jump to names.
