### ISSUE TITLE
mixed check for object fails if in another function

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#3943]
```js
// @flow

function foo(value: mixed) {
  // This works.
  if (value === null || typeof value !== 'object') return;
  // Flow doesn't complain about the next line
  // because if knows value is an object.
  Object.keys(value).forEach(key => console.log(key));
}

function isObject(value: mixed) {
  return typeof value === 'object' && value !== null;
}

function bar(value: mixed) {
  // This does not work despite using the same logic,
  // just moved to another function (isObject).
  if (!isObject(value)) return;
  // Flow complains about the next line with
  // "Expected object instead of mixed"
  Object.keys(value).forEach(key => console.log(key));
}

foo({a: 1});
bar({a: 1});
```

**Comment by Brianzchen** [comment]
This is not a bug and is to do with predicate functions, adding `: boolean %checks` solves the issue
https://flow.org/en/docs/types/functions/#toc-predicate-functions

https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqJLLABQBuAhtKgKYBcoAtrgB60AmAlKAN6KhQIUABUAFrgDOoeLABOAa0kA6AaFyRQFanVABeA6HSpo0UAB9zobAE8ADrViaqNWqACEhgOSwARgCtaHC8eOVpsVDl0AG41YQAxOHhQDlhaSXQvbFBMWCY7aEpcQkpfWFRs7DE3dFpWbOhi2jiwXyDKVEk3DVAFdARpF10pUEpCP0CcVUEAeQCg7GUFWhtJbVcuZWI5AFFKTDFSZZt9AD4cgklYaFplOABzI5WuLliAX2Q0LDwCdUk5ybYdZ0RgsdjcRhla60MagACkByCSj4ajCESi1nsjmcOjcBj0oB882CoAAZKTQEM3J4CcZTO9PhgcPhCL5KHJgQxmGxODx+IJhOIRql0kZYNlZIoUuk7LhsG5OsV7tZqqBJJQmG4HrhMAAaFqgfydbJMWDkTjWWCjfpVWhyIhMn6EUhSAELTZqHqkdyu4lAqkvUBoyIxA2JBAXfKFYrSUrlSqq2r1UCNWoyOViA0AIh2rAcOAtEwW6nQknllA4oCc3PBWbUbqmxzWAa28j2ByeJz051ypehd1gj2OLwZKBIpF4lEYAEY3q9EGyOZOZ3PokA
