### ISSUE TITLE
Contravariant object parameters don't work well for optional object keys

### ISSUE THREAD

**Issue by mkawalec** [facebook/flow#3947]
Consider the following code https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgE4DOGYAvGAN6phgBueFxcAdgFxicCuAWwBGbVAF8A3Omz4wAZTwBjLgBMa9RizbkOnAPy8BIsePRR+nJRj1gcpYpwwAKHAENSbwb0UrOqgEpNJmIoMGdZPDgw909BADpWdi4aaloAcmNRUnSghiYASD9yOBg8ePgAc1cPL0SdPQDpJnEwPBhyAnymMGLS8qrndNV+d1zmsDMzVGKqYRg3XhIKKlpupN0uXgBGAGZdgHYJdHtHF3m3JqA

What I expect is happening here is that `version: number` is not more general than `version?: number` so contravariance requirement breaks and Flow complains. However, any function that accepts `version?: number` can by definition accept `version`s that are non-optional.

**Comment by vkurchatkin** [comment]
You should make the property covariant to make this work:

```js
type Second = {
  +version?: number
}
```

**Comment by mkawalec** [comment]
While this is a bypass, shouldn't flow do it by default? Function accepting `version?` can always handle `version` @vkurchatkin

**Comment by nmn** [comment]
@mkawalec If you don't make the object covariant your code can have a type error. Here's a demo:

```typescript
/* @flow */

type First = {
  version: number
};

type Second = {
  version?: number
}

function print(param: Second) {
  if (typeof param.version === 'number') {
  	console.log(param.version);
  } else {
    console.log('dupa');
  }
  param.version = null; // allowed here as Second has version as nullable.
}

const bla: First = {
  version: 1337
}

print(bla);
// bla is no longer of type First, because print mutated it.
// Therefore type-error.
```

Since, objects can be mutated, you can assume sub-type relationship in places. Flow can't automatically figure out whether or not you are mutating an object in a function. So you have to make things as covariant to help Flow out.

**Comment by mkawalec** [comment]
It makes sense, thanks for the explanation. I guess I'm missing Haskell even more now :P
