### ISSUE TITLE
Union between Type and Array of Type

### ISSUE THREAD

**Issue by yoiang** [facebook/flow#3948]
Hello! 
I apologize if this is a duplicate, I spent the last 7 minutes trying to find a previously existing issue.

I have a situation where I'd like to accept a single instance of an object type or multiple instances of the same type. In actuality this occurs also occurs if different object types are being used in the two parts of the union type.

The issue is that I cannot figure out how to correctly cast for the non-array possibility. The example below throws the error: `Array type. Inexact type is incompatible with exact type: object type`

Thanks for any help in advance!

``` javascript
// @flow

type ExampleType = {|
    member1: string,
    member2: Object,
    member3 : ?string
|};

function example(param : ExampleType | Array<ExampleType>) : ?string {
	
	let result: ?string;

	if (param.member1) {
		result = param.member3; // Errors: still thinks it is an array type
	} else if (Array.isArray(param) && param.length > 0) {
		result = param[0].member3;
	}

	return result;
}
```

**Comment by vkurchatkin** [comment]
Use `Array.isArray` instead

**Comment by yoiang** [comment]
@vkurchatkin the above example does use `Array.isArray` to determine the `array` type (see the `else if`), the issue is with the first branch of the `if` statement. The `result = param.member3;` gives an error assuming `param` is an `array`.

**Comment by samwgoldman** [comment]
`param.member1` is not a supported refinement for this kind of union type, so Flow doesn't understand that `param.member1`'s truthiness implies that `param` is `ExampleType`.

Instead, use `Array.isArray(param)` and switch the conditional and alternate branches.

Lastly, `param.member1` would still fail if `param` was `ExampleType` if `member1` was the empty string, which is false-y.

**Comment by yoiang** [comment]
@samwgoldman Thanks so much for your help!

Ah I see, so 
```javascript
	if (Array.isArray(param)) {
		if (param.length > 0) {
			result = param[0].member3;
		}
	} else {
		result = param.member3; 
	}
```

It would be great if that was clarified in the documentation, I could see if being useful to others!

Regarding not supporting `param.member1` refinement it did appear to work and even differentiate a third type in the union:
```javascript
type Example2 = {|
    member4: string,
    member5: number
|};
```

```javascript
if (Array.isArray(param)) {
		result = param[0].member3;
	} else if (param.member1) {
		result = param.member3; 
	} else if (param.member4) {
		result = param.member4;
		result = param.member5; // As expected an Incompatible Type error
	}
```

By work I mean that Flow was able to differentiate accessing members vs invalid fields and their types.

Regarding using `param.member1` or any member as refinement I forgot that Flow is just sitting on top of Javascript giving me feedback, it isn't adding any special sugar and the conditional helps cue Flow but is just a dang normal Javascript frustrating conditional ;)
