### ISSUE TITLE
Feature request: statically prevent unbound `this`

### ISSUE THREAD

**Issue by dmnd** [facebook/flow#3949]
One issue that pops up a lot in Javascript (especially with newcomers) is the use of `this`. It's common for people to forget to bind a function to `this` before using it as a callback. E.g.

```js
class Foo {
  something = {s: "a string"};

  f() {
    console.log(this.something.s);
  }
}

const c = new Foo();
c.f(); // ok

// NPE:
setTimeout(c.f, 1000);

// NPE:
const f = c.f;
f(); 
```

Is there any way for Flow to help with this problem? It'd be really nice if Flow could infer that `f` is called without `this` in these situations, similar to how flow will prevent you from calling a function without a required parameter. Can `this` be modeled as another parameter?

**Comment by danwang** [comment]
This is unnecessary in ES6:

```jsx
class Foo {
  something = {s: 'a string'};
  f = () => console.log(this.something.s);
}
const c = new Foo();
c.f();

setTimeout(c.f, 1000);
const f = c.f;
f();
```

The `f = () =>` syntax means "create a function that resolves all terms lexically".
The `f()` syntax means "create a function that resolves all terms lexically, _except_ for `this`, which is resolved dynamically."

**Comment by dmnd** [comment]
@danwang that's not ES6 or even ES7. 

Class property initializer syntax is only stage 2 and "methods" defined that way are very different from real methods because they don't end up on the prototype. E.g. in your example `F.prototype.f` is `undefined`. Instead, each instance of `F` has its own copy of that function.

**Comment by danwang** [comment]
What do you need to use the prototype for? (if the prototype is never used by the programmer, it has the same semantics as a correctly bound method)

**Comment by dmnd** [comment]
[@calebmer's tweet](https://twitter.com/calebmer/status/905051756157050880) made me realise that this is likely a duplicate of #452. Closing!
