### ISSUE TITLE
strict checking function arity bug (false positive?)

### ISSUE THREAD

**Issue by lloiser** [facebook/flow#3951]
With version 0.47.0 flow will introduce strict checking of function call arity.

This has some problems if you have functions inside an array. E.g. a list of validations to run for an object.

Here is an example:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAC4CeADgQApq4DOsAdqALygDeioo92AtmgFygahXAEt6AcwDcHUNgkCuAVx4AjajIC+M9FjwES5UADVs0USmyFRDAPKlrDGszaye4gIIKA-IPor1XERNZEglegxHRgA3MwsrNAA5XjQAClJBKloGAEpBVVhYaDRsRnZOfEIlXEZSADpuPlAAQiYWACJ2rVDwyJsYuMtCNC80jNAsunoAGlBYQVNzIf77KJo80AKikrLZUUhQVMM0WAPYOvd6UeY20Hb-NWp2nNdOCrQqmtB6+QIAPjmF08ChknBC70+jBESjQ3UQGCchCIsFIogwi3ihFgtBcAG1ZLElglknxpgTBglRogALoyeGI76ZahTFzlLgpQTtABSsAAFvR2mTOL9BAAWABMwRkCPowjmCwpUVW-WcLFY2mQWNR6MV2JodUg2IAotgMLzUmEIlFUoTMWgXmzbUMxrNYDktO6gA

Note: at the moment you might have to select "master" in the select box in the top right corner to see the error

The JSON representation also contains an `extra` property that contains more details about the error. Would be nice if this is shown on the playground too.

**Comment by Leeds-eBooks** [comment]
I agree this is a problem but weirdly for me the repl shows "no errors" even on `master`. In any case, I think there should be a zero-cost escape hatch for function arity, other than declaring an arg you're not going to use which makes things like eslint complain.

**Comment by SamChou19815** [comment]
Expected behavior
