### ISSUE TITLE
Unsuppressable (and confusing) error: "This type is incompatible with some incompatible instantiation"

### ISSUE THREAD

**Issue by joewalker** [facebook/flow#3954]
Reduced case:

```
// @flow
import * as Immutable from 'immutable';

/**
 * list.setSize(max) that doesn't pad, and does add an elipsis value
 */
export function elide<T>(list: Immutable.List<T>, maxLen: number, ellipsis: T)
                          : Immutable.List<T> {
  return (list.size <= maxLen) ?
          list :
          list.setSize(maxLen - 1).push(ellipsis);
}
```

The error looks like this:

```
$ flow
node_modules/immutable/dist/immutable.js.flow:436
436:   setSize(size: number): List<?T>;
                                   ^^ null. This type is incompatible with
  7: export function elide<T>(list: Immutable.List<T>, maxLen: number, ellipsis: T)
            ^ some incompatible instantiation of `T`. See: web/util/elide.js:7

node_modules/immutable/dist/immutable.js.flow:436
436:   setSize(size: number): List<?T>;
                                   ^^ undefined. This type is incompatible with
  7: export function elide<T>(list: Immutable.List<T>, maxLen: number, ellipsis: T)
            ^ some incompatible instantiation of `T`. See: web/util/elide.js:7

Found 2 errors
```

I understand that setSize() has to return `List<?T>` because it might pad, and that it's too hard to infer that in this case. The question is - how to get rid of the error?

Since the error is reported in `modules/immutable/dist/immutable.js.flow` it's not simple to `// $FlowIssue` your way out. I've looked at various means of casting, none of which solve the problem, so I'm left not using setSize().

The real issue is that the error is reported in the wrong class, which in this case happens to be hard to edit.
A sub-issue is that it's not easy to correct the problem with a cast

**Comment by PCreations** [comment]
You should update your immutable.js package, this has been edited two months ago : https://github.com/facebook/immutable-js/commit/ff90a97accb76f10d1b84455847c8c59a8427dc2#diff-45e31ae21d8bf236f04e33ca7a713a03L438

**Comment by joewalker** [comment]
> You should update your immutable.js package, this has been edited two months ago : facebook/immutable-js@ff90a97#diff-45e31ae21d8bf236f04e33ca7a713a03L438

For the benefit of anyone else - this isn't in the current release of Immutable, you need to jump to an RC release of 4.0.
