### ISSUE TITLE
exact object types

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#3957]
There is an example at https://flow.org/en/docs/types/objects/#exact-object-types-a-classtoc-idtoc-exact-object-types-hreftoc-exact-object-typesa that says this should give an error, but it doesn't for me.

```js
// @flow
var foo: {| foo: string |} = { foo: "Hello", bar: "World!" }; // Error!
```

**Comment by AugustinLF** [comment]
It does [give an error](https://flow.org/try/#0PTAEAEDMBsHsHcBQA3AhgJ1JWsBcoBvAHyx3wGcAXdASwDsBzUIgX1AF5DS9QAiACQCm0OLwA0oAEYZ8vAOqx00ACYBCXqBYBuUCFABRdOkWqgAl) to me, what version of flow are you using?

**Comment by mvolkmann** [comment]
Nevermind. It's an issue with using Flow through the Vim plugin ALE.
When I run flow from the command-line, it does flag the error.
