### ISSUE TITLE
Property cannot be assigned on possibly null value

### ISSUE THREAD

**Issue by kovalenko-sb** [facebook/flow#3961]
When I run flow on code

```
// @flow
type ItemType = { 
	value: null | {
		uid: string,
		name: string
	} 
};
var item: ItemType = { value: null };

function getItemName() {
	return 'test';
}

if (item.value !== null) {
	var itemName = getItemName();
	item.value.name = itemName;
}
```

I get error

`item.value.name = itemName;
                            ^^^^ property 'name'. Property cannot be assigned on possibly null value`

But if I change this line

`var itemName = getItemName();`

to another 

`var itemName = 'test';`

then there is no errors from flow.

It seems that if there was a call of any function right after check and before usage of possibility null variable it throws error

**Comment by vkurchatkin** [comment]
> It seems that if there was a call of any function right after check and before usage of possibility null variable it throws error

This is intentional. See: https://flow.org/en/docs/lang/refinements/

**Comment by kovalenko-sb** [comment]
Thank you! Sorry I've missed this part of documentation
