### ISSUE TITLE
Flow claims buffers can't be coerced to strings

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#3962]
I'm not 100% sure if this is a bug or intended behaviour, but I was surprised by this (see [tryflow](https://flow.org/try/#0MYewdgzgLgBAZiEMC8MwFMDuMBCBXOOdAJwAoByTEYgGwBNyBKAbgChXRIQb0A6GkAHNSAAwAW6GgJgASAN4IQAXxGMgA)):

```js
const thing = new Buffer('world');
console.log(`hello ${thing}!`);
```

```
2: console.log(`hello ${thing}!`);
                        ^ Buffer. This type cannot be coerced to
2: console.log(`hello ${thing}!`);
               ^ string
```

But Node buffers can be coerced to strings. `String(buffer)` or `buffer.toString()` both work fine, as does interpolating a buffer into a template string.

**Comment by vkurchatkin** [comment]
This is intended behaviour. You should call `toString` explicitly.
