### ISSUE TITLE
Switch does not catch type errors

### ISSUE THREAD

**Issue by arv** [facebook/flow#3965]
I was expecting switch statements to warn me of impossible cases.

```js
/* @flow */

type T = {key: 'a'} | {key: 'b'};

function f(v: T) {
  switch (v) {
    case 'a': // This is NOT flagged
  }
}
```

[Try it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAN4DWeWAXGAOQCGDAvmAD4XV2MBGbANzooAVwB2AYwwBLOOLBQAFADd6hAJQVUYMAGcEMjJIAWYVVvI7dYSUz0FmDWtdao3qIA)

It seems to work with simpler cases like this:

```js
/* @flow */

type T = 'a' | 'b';

function f(v: T) {
  switch (v) {
    case 'c': // This is correctly flagged
  }
}
```

[Try it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAOQCG5YAPhQEbkDc6UArgHYDGGAlnE5goACgBuALiIBKMAG9UYMAGcEfDNwAWYcbIVKl3SsoLlu5CYrABfVLdRA)

**Comment by arv** [comment]
Maybe duplicate of https://github.com/facebook/flow/issues/2395 ?

**Comment by vkurchatkin** [comment]
In general Flow doesn't warn on unreachable blocks of code. There is definitely an issue for that.

**Comment by Brianzchen** [comment]
Your first case now throws errors, which means this case is solved, changing your first example to `switch (v.key) {` removes the error which is expected.
