### ISSUE TITLE
Document .js.flow files?

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#3966]
In the [docs](https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-module):

> ...check out the docs on [.js.flow](#) files.

But that link has `href="javascript:alert(&quot;TODO&quot;)"` :)

It's been like that for a few months. Currently I can't find any authoritative information on how `.js.flow` files work. I'm guessing this is the preferred way for a published module to include its own libdef out of the box, but some more details and examples would be really useful.

**Comment by rosskevin** [comment]
@callumlocke agreed on the need or docs, here are related issues that are open:
https://github.com/facebook/flow/issues/1996#issuecomment-230919868
#2420

We have done this with `material-ui` on the `next` branch with success.  It uses the `flowCopySource`:
https://github.com/callemall/material-ui/blob/next/scripts/copy-files.js#L85

**Comment by AndersDJohnson** [comment]
Related https://github.com/facebook/flow/issues/3609.

**Comment by LoganBarnett** [comment]
Per @AndersDJohnson this looks like a dupe of #3609. @callumlocke can we close this ticket and move any further discussion there?

**Comment by callumlocke** [comment]
Closing in favour of #3609
