### ISSUE TITLE
Flow gives incorrect answers when converting SFC to ES6 classes

### ISSUE THREAD

**Issue by danwang** [facebook/flow#3969]
Hi!

I have a typedef for a function that converts a stateless functional component (SFC) to an ES6 class of the same props. ([flow try link](https://flow.org/try/#0C4TwDgpgBAKgTgQwHYGcBmB7OBbKBeKAHgAUA+ACmP1KgH4AlCBAY2ABIBRAGwmwiWCFkIUgEpqUAMJcEKFIUYt2kjNjAYk-QcIA0UYnuGlSAbgBQoSPrgYwKfFADeAHwQAuKEgCu2AEYQ4ZwBfczNmDRRgWA94ZHQsXAJyby4uD2FRc3DUKJU1DS0HGHJyMA9iGztxPBoUrkyzMwB6JqgAQVSoDDQoYAALCBRoFD6MLy4AEygAmzgzQjz1TQEoJtN5xYKVhDwAIlkJtF3V0yA))

```jsx
type Transform = <P>(P => ?React$Element<any>) => Class<React$Component<any, P, any>>;
type Props = {|a: number|};

const T: Transform = (null: any);
const Component = T((p: Props) => null);

// All of these should error
<Component />;
<Component a="asdf" />;
```

On version 0.45.0, there is no error (although I think there should be).
On version 0.46.0, it prints "Internal error: Not_found"

Is there a better way to do this? I need this to deal with HOCs because the double representation of SFCs/Class<React$Component> breaks Flow left and right, so I will type my HOCs as only accepting the ES6 class sort.

**Comment by danwang** [comment]
Update: It looks like that Flow is unable to recognize `(p: Props) => null` as a React component.

I made these following edits which work ([flow try link](https://flow.org/try/#0C4TwDgpgBAKgTgQwHYGcBmB7OBbKBeKAHgAUAuKAbwF8A+ACmPxqgH4AlCBAY2ABIBRADYRsEJMELIQNAJRMoAYUEIUKQh258FGbGAxIxE6gBooxU9Ro0A3AChQkM3AxgU+SgB8E5JAFdsAEYQcB5UdrZc+ijAsOTwyOhYuAR0foKC5FIydpGoMdq6+obuMHR0YOTEzq5yeMyEACYAlgBuNIQA9M1t2ba2HR1QAILpUBhoUMAAFhAo0ChTGL6CDVDBznC2hAV6BuJQHTZbO0X7CHgARCoNaBcHNkA)):
- Return a ReactElement
- Change the `any`s to `{}`

**Comment by turadg** [comment]
I ran into a similar issue when updating from 0.45 to 0.47,
```
        <Text>
          {this.isSchool()
            ? <Image
                src={require(`assets/images/school.svg`)}
              />
            : <Image
                src={require(`assets/images/district.svg`)}
              />}
        </Text>
```
That caused "Internal error: Not_found".

A workaround was to move the ternary condition out of the JSX expression by setting `const imgSrc` above.

**Comment by Brianzchen** [comment]
Issue not relevant anymore to the current state of flow, `React$Component` does not accept 3 parameters currently.
