### ISSUE TITLE
'this should not take long'

### ISSUE THREAD

**Issue by hmeerlo** [facebook/flow#3970]
Please remove the 'this should not take long' remark while running flow. First of all 'long' is a very subjective property and for me it does take very long (subjectively measured of course :-)). It very often takes more than a minute, which is not weird because it completely depends on the size of the project.

**Comment by hmeerlo** [comment]
Ok, came back to my own issue once again. It takes very long and there is no way to know why. A ```flow check``` takes more than 5 minutes on my project and a ```flow status``` very often takes more than 2 minutes. But it is impossible for me to analyze why this is the case. So it would be good to change the message to 'this can take a while'

**Comment by billschaller** [comment]
Totally valid.

**Comment by mrkev** [comment]
This issue should be closed by https://github.com/facebook/flow/commit/46b585269bbdc5e8258c0686515955844419fd1e
