### ISSUE TITLE
Generic function type

### ISSUE THREAD

**Issue by xareelee** [facebook/flow#3971]
I have two functions:

```js
// declare function a
function a() {...}

// declare function b
const b = () => {...}
```

and I want to specify a variable with a generic `function` type:

```js
// @flow
// x should be function type
const x: function = a

// y should be function type
const y: function = b
```

then it shows that `function` is an `Unexpected token`.

How can I indicate a variable to be a function (don't care the param/input and return/output)?

**Comment by vkurchatkin** [comment]
It's `Function`, with capital `F`;

**Comment by xareelee** [comment]
Indeed, my bad.
