### ISSUE TITLE
Spread operator on a function should not be allowed

### ISSUE THREAD

**Issue by singpolyma-shopify** [facebook/flow#3973]
This code:

```
// @flow
const x = [];
const y : Array<{ hello: string }> = [...x.concat, { hello: "there" }];
```

Passes flow currently, however the result of `...x.concat` is `undefined` which results in a value being assigned to `y` that violates the type.

**Comment by vkurchatkin** [comment]
This is caused by https://github.com/facebook/flow/issues/106
