### ISSUE TITLE
Question: "Special" strings

### ISSUE THREAD

**Issue by suchipi** [facebook/flow#3975]
I have several types in my codebase which represent strings with special meaning; they're used to document the response from our server API. They're all just aliases for string; they look like this:
```js
// String that can be shown directly to the user
type HumanReadableString = string;

// Represents an ISO8601 datetime string
type DateString = string;
```

While useful for documentation, currently flow treats them no differently than normal strings. Is it possible to make flow consider these "more specific" than strings? That is, my desired functionality is:
```js
function parseDate(dateString: DateString): Date { /* ... */ }
const someDateString: DateString = "2017-05-18T14:02:04+00:00";
const notADateString = "foo";

parseDate(someDateString);
// $ExpectError
parseDate(notADateString);
```

"More specific strings" could also be useful in these situations:
* String that is escaped and safe to insert into html
* Template string (handlebars or etc)
* String that has been URI-escaped
* JSON string that will be a certain shape when parsed (`const str: JSONString<{ foo: string }> = "{\"foo\":\"bar\"}"`)

**Comment by singpolyma-shopify** [comment]
This sounds like basically the equivalent of Haskell's `newtype` and it could be very useful to have.  Flow could do it, but it would require rewriting more invasive than just removing type annotations at build time (would have to erase constructors, etc).  You can emulate this yourself with classes of course, but unless there's an erasing feature you'll pay a (perhaps small enough to be ok) performance penalty for that.

**Comment by suchipi** [comment]
Wrapping and unwrapping the values works, but it can be a bit tedious, especially when they're deeply nested; as an example, imagine I want to use the following type in my system, which represents an API response for some endpoint:
```js
class StringWrapper {
  constructor(value) {
    this._value = value;
  }

  toString() {
    return this._value;
  }
}

class HumanReadableString extends StringWrapper {}
class DateString extends StringWrapper {}

type System = {
  current_state?: {
    status?: HumanReadableString, // instance of wrapper class
    last_updated?: DateString, // instance of wrapper class
  },
};
```
My API would actually respond with strings, of course:
```js
type SystemAPIResponse = {
  current_state?: {
    status?: string,
    last_updated?: string,
  },
};
```
And I'd have to go to each path and convert it to the wrapped value, but only if it's present:
```js
if (response.current_state != null && response.current_state.status != null) {
  response.current_state.status = new HumanReadableString(response.current_state.status);
  // Or, if I don't want to mutate response.current_state, there's a bit more involved

  // Do likewise for last_updated, etc
}
```

A real API would hopefully not have every property as optional, but hopefully this illustrates the ergonomic pain points around using wrapper classes to track this information.

**Comment by suchipi** [comment]
I believe this can be accomplished using [Opaque Types](https://flow.org/en/docs/types/opaque-types/).

**Comment by jsatk** [comment]
@suchipi I too have this question and came across Opaque Types. However, I'm still unclear on how one could go about defining `type ISOString = "YYYY-MM-DDTHH:MM:SS.sssZ";` Meaning if I say `const dateStr: ISOString = "foo bar"` it'd throw a warning letting me know it didn't confirm to the right format. Is this possible with Opaque Types?

**Comment by suchipi** [comment]
No; you'd have to do something like make a `makeISOString` function that returns your opaque type and use that everywhere instead of string literals:
```ts
opaque type ISOString = string;

function padLeft(input: number, amount: number = 2): string {
  return String(input).padStart(amount, "0");
}

export function makeISOString(
  year: number,
  month: number,
  day: number,
  hour: number,
  minute: number,
  seconds: number,
  ms: number
): ISOString {
  return [
    padLeft(year, 4),
    "-",
    padLeft(month),
    "-",
    padLeft(day),
    "T",
    padLeft(hour),
    ":",
    padLeft(minute),
    ":",
    padLeft(seconds),
    ".",
    padLeft(ms, 3),
    "Z"
  ].join("");
}
```
[Try Flow link](https://flow.org/try/#0PYBwhgjgrgpgBAFwJ4ngSQMoHkAiYHwC8cAzggE4CWAdgOYDcAUIwGZTUDGClw1c4AEwAyMFggAUNEFAQAuONSgBbAEYxyAGjhglwdnIXK15OMQBMASnlkqdOAG9GcOORgIo5Phgo1ak6tIIFgB0gt5g5BI6etQIWgBEAAzxFkwAvswwAB4gwJFwbJzcvHBKYADWMJi4+DDiTnBIMBHyiqrqGg26sQAWrUYdDQJgSP3tmg09euRjxp3OSjQyMLODziQwHLwCJKsTC7uG44xWcNV4BA4Nru6ecADaDc6CImLiTRFaACwW885w8QAtPE-s8wMJRBJugger8ngDgaD+ODXhJhkg4f8AQAVEHwl6Q8RTDyY-7xWR4rEEt6LRQEUnOcmU-7UiQbLbUHYMgHBZlgiE0khaADM3PiAC14g0ALrBABWwBo4niKXSzCAA)

**Comment by jsatk** [comment]
@suchipi OMG! You're incredibly kind. This is super thorough. Thank you for helping this random stranger out.

**Comment by jsatk** [comment]
@suchipi OMG! You're incredibly kind. This is super thorough. Thank you for helping this random stranger out.
