### ISSUE TITLE
Unable to refine type value based on checks in an ES6 class constructor

### ISSUE THREAD

**Issue by dstaley** [facebook/flow#3979]
It seems like Flow is unable to correctly determine the type of something that has been refined in the constructor of an ES6 class.

```js
type Value = {
  prop: number | string
};

class Doubler {
  value: Value;

  constructor(v: Value) {
    this.value = v; // number | string

    if (typeof this.value.prop === "string") {
      // Inside this block, Flow knows this.value is a string.
      this.value.prop = parseInt(this.value.prop /* string */, 10);
    }
  }

  doubleValue() {
    // Flow doesn't understand that it's impossible for this.value to be
    // anything other than a number at this point.
    return this.value.prop /* number | string */ * 2;
  }
}
```

(I realize that in this particular example it's easy to just redefine the type of `value` for `Doubler`, but this is a purposefully-contrived example; I'm running into this issue with a deeply nested property of a complex type.)

As a developer, I would expect Flow to remember that at the conclusion of the constructor, `value` is a number unless another method has the potential to modify the type.

**Comment by madbence** [comment]
refinements are pessimistic, even an (unrelated) function call invalidates them. `this.value.prop` can be modified from the outside, so Flow cannot make any assumptions about it.
