### ISSUE TITLE
`React.Component` must declare type for `static defaultProps` for `props` type checking to work

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#398]
```javascript
/* @flow */

var React = require("React")

class Example extends React.Component {
  props: { bar: string };

  render() {
    return <div>{this.props.bar}</div>
  }
}

React.render(
  <Example foo="foo" />,
  document.body
)
```
```
|| No errors!
```

If I wrote this with `React.createClass` and used `propTypes`, the `createElement` call would fail. I'm really excited about the `React.Component` version because I can use more specific types, e.g., `(foo: string) => void` instead of `PropTypes.func`.

Happy to hack on this if someone could point me in the right direction.

**Comment by jeffmo** [comment]
cc @avikchaudhuri who has done most of the React-oriented work for Flow

**Comment by samwgoldman** [comment]
This is still an issue as of 0.11.0. How is facebook using React with flow without this? Just propTypes?

**Comment by avikchaudhuri** [comment]
Yikes, currently you need to specify static defaultProps: { } too for this to error out. What's missing is a way to tell Flow that a missing defaultProps is the same as an empty defaultProps.

**Comment by samwgoldman** [comment]
Ah! Well, having a workaround is excellent for now. Thanks!

**Comment by samwgoldman** [comment]
Maybe something like `$Default<D,{}>`, which flows into `{}` if `D` is open?

**Comment by rogergl** [comment]
I have the same problem and I tried the given workaround:
   
    class ActivityButton extends React.Component {

      props: {
          text: string,
          loading: Boolean,
          onPress: () => void
      };

      defaultProps: {
      };

      constructor(props) {
          super(props);
      }

and I use it like this:

    <View style={{marginBottom: 56}}>
         <ActivityButton
              text="Sync"
              loadinguu1={this.state.isLoading}
              onPress={this._onSync.bind(this)}/>
       </View>

But the result is: no errors

**Comment by samwgoldman** [comment]
@rogergl `static defaultProps`, not just `defaultProps`.

**Comment by rogergl** [comment]
I made the following change:

    type TABProps = {
        text: string,
        loading: Boolean,
        onPress: () => void
    };
  
    class ActivityButton extends React.Component {
      props: TABProps;
      static defaultProps: {};
      constructor(props:TABProps) {
         super(props);
    }

But the only error I get now, after upgrading flow to 0.11, is in react-native/Libraries/CameraRoll/CameraRoll.js:154:

**Comment by samwgoldman** [comment]
Can you show the full error message? It's pretty hard to tell what's going on from that, and it seems like there is more at play that just the pasted code, since CameraRoll isn't referenced anywhere in what you've shown.

**Comment by rogergl** [comment]
The full error message is:

    /Users/roger/Documents/AwesomeProject/node_modules/react-      
    native/Libraries/CameraRoll/CameraRoll.js:154:1,50: assignment of property GroupTypesOptions 
    Property not found in
    /Users/roger/Documents/AwesomeProject/node_modules/react-
    native/Libraries/CameraRoll/CameraRoll.js:94:7,16: statics of CameraRoll

But it think that this is just a React-Native problem. The main problem is that the wrong attribute in ActivityButton is not caught (loadinguu1 instead of loading).

**Comment by samwgoldman** [comment]
@avikchaudhuri I was able to use your ObjTestT to make this work in #494.

**Comment by oguzbilgic** [comment]
I don't think this is written anywhere in the docs, I spend hours and was about to give up.
