### ISSUE TITLE
Flow import does not recognize `module` option in package.json

### ISSUE THREAD

**Issue by limscoder** [facebook/flow#3980]
When importing a module from a package Flow correctly follows the `main` option defined in the package's `package.json` file, but does not recognize the `module` option. 

```javascript
{
  "main": "dist/umd/index.js",
  "module": "dist/es/index.js"
  ...
}
```

Webpack and Rollup prefer the `module` option when defined.

More info: https://github.com/nodejs/node-eps/blob/master/002-es6-modules.md#51-determining-if-source-is-an-es-module

In my use case `main` points to a built UMD module, while `module` points to individual modules. It's easier to ship `.flow` files alongside individual modules, but that doesn't work because Flow import doesn't recognize `module` config.

Happens with v0.46.

**Comment by steelbrain** [comment]
Related https://github.com/facebook/flow/issues/2675

**Comment by TrySound** [comment]
You might don't need to look for `module` field. Use this way
```js
{
  "main": "./lib/index.js",
  "module": "./esm/index.js",
  "files": ["lib", "esm", "src"],
  "scripts": {
    "build:flow": "echo \"// @flow\\n\\nexport * from '../src';\" > lib/index.js.flow"
  }
}
```

This probably can be closed.
/cc @vkurchatkin
