### ISSUE TITLE
Flow thinks a nullable function argument can be undefined

### ISSUE THREAD

**Issue by rsolomon** [facebook/flow#3981]
I might just be being daft here, but I feel like the following should know that `num` is only ever going to be `null` or a `number`, not `undefined`:

```
function test(num: ?number): string {
  if (num === null) {
    return '---'; 
  }
  
  return num.toString();
}
```

Errors: 

```
8:   return num.toString();
            ^ call of method `toString`. Method cannot be called on possibly undefined value
8:   return num.toString();
            ^ undefined
```

Shouldn't it only catch `num` as possibly undefined if `num` is defined as `num?:` ?

**Comment by danwang** [comment]
https://flow.org/en/docs/types/maybe/

> Maybe types accept the provided type as well as null or undefined. So ?number would mean number, null, or undefined.

You can fix this with

```jsx
const test = (num: number | null): string => {...}
```

**Comment by rsolomon** [comment]
Ah I guess that makes sense. Why does it not match the paradigm used in object type declarations, where:

`foo?: bar` means optional and

`foo: ?bar` means nullable and

`foo?: ?bar` means maybe?

**Comment by danwang** [comment]
It matches.

https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUCGAuKB+AdgK4C2ARhAE4A0KAvgNwooAUS2Uh+AJhAGYCW+CF1o4YASkat2RADazRsSSzY4AjIon0gA

The `key?` syntax is the specific to objects and means "optional presence of a key" (it says nothing about the value)

**Comment by rsolomon** [comment]
😥  Totally makes sense... can't believe I've had a misunderstanding about this core bit of functionality all this time. Thanks for taking the time to school me.
