### ISSUE TITLE
React - Component's defaultProps are causing incorrect typecheck

### ISSUE THREAD

**Issue by michalkvasnicak** [facebook/flow#3986]
I don't know if this is bug or not, but when I use `defaultProps` in component, typechecking stops to work for `render` callback. Maybe I misunderstood how to handle default props in flow.

Here is example how to reproduce this error:

```js
/* @flow */

import React from 'react';

type Data<T> = { data: T };

type Observable<T> = { result: () => T };

type Queries = {
  [key: string]: () => Observable<any>,
}

type DefaultProps = {
  queries: Queries
}

type Props<Q: Queries> = {
  queries: Q,
  render: (
    queries: $ObjMap<Q, <T>(() => Observable<T>) => Data<$ObjMap<T, <A>(A) => ?A>>>
  ) => React$Element<*>,
}
                 
class InvalidComponent extends React.Component<DefaultProps, Props<*>, void> {
  /* somehow this will pass through validation and ignore passed queries using queries prop */
  static defaultProps = {
      queries: {},
  };                
}                 

class ValidComponent extends React.Component<void, Props<*>, void> {}
                   
const queries: { test: () => Observable<{ id: number }>} = ({}: any);
                   
<ValidComponent 
  queries={queries}
  render={(q) => {
    (q.test.data.id: ?number);
    // $ExpectError
    (q.test.data.id: number); // causes error
    // $ExpectError
    (q.test.data.id: string); // causes error
    return <div />;
  }} 
/>;
                     
<InvalidComponent 
  queries={queries}
  render={(q) => {
     // typecheck is not working because of defaultProps
     (q.test.data.id: ?number);
     // $ExpectError
     (q.test.data.id: number); // causes error
     // $ExpectError
     (q.test.data.id: string); // causes error
     return <div />;
  }} 
/>;
```
[Try above example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsABEKhCgB4AKgD4wAXjABvMABMRFAFxgJYAL5dUvfmADyAIwDOZfADcKpmGUkz5S1uYCuMQpoAUASjkZbT1uPgEARXcrDDJzOUVUAEgAbQBrMh5Nc0J8DAA7AHMAXV8A2RkzSxs7BzEKPJ4pABpUHVCjQTIoCk9CAAV6HDiXJIBHKNzYzUjo2Nb2gQG4IbFw6YmY82cExPHZ82mWsDBE1jzlK189yYOwABIzACsAWQocVaawJx9-QJMLKy2eyOaRlGTCURiB6mF5vSSfMQAQSkPkRYLAAH5kVIpOjyNRCHcAKIOLBkPKEMQgZrzY50+kMumoKgwCjmOIASTythgGGUAGEGHg8uTiGQAB6EcnKOL4mgAOkFuDgIopYk63V6SyGn215ipzTA1jgfJkCiSoDA5gYZAAFogwIRbRg4ggMDAYGAcGy4k76O4CrajRReapCBgVWB6sowBgCnkCAJveyyDHrpswO5zPkCmB07EvYNkGhEtkRBgqCouj0vHr4ubGfnbgodEc6XpGZ2mTou730CyfWAAGohvlK4WisASqXnWVsQiKoUq0ViY183WDfXUz5r5Rmtq9w-MlXZPMbKaKR2xbxgX7lf5VIG1JR8zR5dxYUxWXRSHvyHwtpo9Q8H4XCHn2YgjqG47LhSYCoMcTayAoTYHmAZwXPgyE+KM6LmokOHylK2TymGFDyq+mLvp+VigRawD3ES4r8DQRL4PQ+BJIRxELmRFHKG+H5fvgoFgMADFUD0lhxFYHEIXS4mMcxZCsexBDycc3HXqRaj8VkOQ5qJimSVmBayepxynGQhDuPgeRfMoGDWGJUhgboPaoMArkaeBnaoGIXI8mOS6qsQ8lISh57mGhGFWNhuF-PhimGCptoqaksZxAmxAIAQqQ5mAX4mZYYBwFAVaarWm5caMRHaXxlEYtRwl0YkinEspqlyQRtU8Tpoh6WAzW0RwYkSVJZlqZx9LtUxLGEGxcn0lpJENQJVoGYURnjaZMlTfJVk2XZDlOS5bk6B5XkcEAA)

**Comment by asolove** [comment]
Hi, @michalkvasnicak! I'm not very familiar with this code pattern using Observables, so I'm having a hard time understanding what you want to happen and possibly also what you were seeing when you ran this back in May.

I made some [slight changes to the code to update to Flow v0.53](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudQgE8cNMABFShUgB4AKgD4wAXjABvMABNJpAFxhZYAL79UQkWADyAI3I18AN1JWYNOYpXqu5AK4xCegAoASmVFA2MBYVEARW87DBpKD1QwMABtAGsaQT1yQnwMADsAcwBdQJClRWtbBycXaVJCwXkAGlRDSPMxGihSX0IABRYcJLUUsABHOILEvVj4xI6u0WG4Uelo+ZmE8ndx1OnF8nn21K5CjTtAicOdubAAEmsAKwBZUhxN1rA3AODQpYbHZHM5XApKooJFJpM8rO9PnIftIAILyAIoyFgAD8aPk8gmWNoDEIjwAoi4sDRCoRpCA2stUkzmSymah6DAKJQAJKFRwwDAaADCrDwhWptIUYBoAA9CNSNJRiYwAHQi3BwcU06RrDb0n72OCCxSqCagMDkVg0AAWiDAhGtGEoCAwMBgYBwXPt1pY3mK1rA-MFkgwmrIlzAGGKhQIok95FsGim90o3nIRWKyeOHpGyDQqTyIfoml6-T8urGptZR1mJzUhjORl4rJbbMMrY76A5XoAaqQBcLRZqJdK5QqldxCGqh1raRW6W1A0aNCbOh31+zNXks7W9Op5XkKoCaiD6q51IK9IVvFgrHYjPJ2yoAqpDHomoIgiZ16lpH2B+qYojhMNa7EoqigYka5gBcVz4OBASTFiVZMohKoHlOWhSCql44tet52F+txgMAwBPGSMoiIwZL4Cw+DEWhGEqlhpA4RoV43ne+BfiRZH0P0tiUHYdHEaR5GUTQ1G0QQDGTOhiSYdobG5PkGY8WJ-Fpok0rSfRzJcIQ3j4IUvwaBg9gkfI-CpIY7aoMAVnEa2qDSLyQaDhqs5gCBKbgZB5DQbBdgIUhgIoUyYlmJJ1qSRkkaUDGxAIAQGQZmAd6abYYBwFAJZ9AMFZOYxCnMUpuHYvhXFESyYnkhJUkiSyxV5KV2G4ZVhHNhpAnacJMk1WRdVUYQNGNcyzWKW17EWqpJTqXxPVCbpTkGUZJnSGZFkOdZRh2dtQA).

After those changes, I now see errors on all the lines that you marked `$ExpectError`. It seems to me like all those errors are correct. What do you expect to see different from this?

**Comment by SamChou19815** [comment]
Closing since the example uses existential type that's no longer supported.
