### ISSUE TITLE
Type inference doesn't work with inline function

### ISSUE THREAD

**Issue by zaaack** [facebook/flow#3989]
e.g.

```js
// @flow

function func1(arr?: Array<string>) {
  return arr && arr.map(item => item)
}
// No errors

function func2(arr?: Array<string>) {
  if (arr) {
	return () => arr.map(item => item)
  }
}
// 11: 	return () => arr.map(item => item)                  
//                                      ^ call of method `map`. Method cannot be called on possibly undefined value
// 11: 	return () => arr.map(item => item)
//                                    ^ undefined

function func3(arr?: Array<string>) {
  return () => arr && arr.map(item => item)
}
// No errors

```

https://flow.org/try/#0PTAEAEDMBsHsHcBQzIFcB2BjALgS1uqGlgIwAUAhgE5UD8AXKAII0UCeAPAM7ZW7oBzAHwBKUAG9EoUFQCm2VFULUqoAGRrQKgHQBbCgAcyubLN2gAvENAmzIxAF9kiYjnyFXAJko0GzVpw8fIKiElI2kKA+VGKSAJByCkpRYlZaNHqGxqbmaba69tJOTigYbgREZQDM0X4sVOzcvPzCseGJioRkqdYq6po6+kb5ltb59g5AA

**Comment by itamar244** [comment]
Flow is working perfectly fine, you just have misunderstood your code.

 - The first method will return either `undefined` if arr is undefined or the or a shallow copy of the array (`arr.map(item => item)`). 

 - The second method will return will return either `undefined` if arr is undefined or a function which returns shallow copy of arr if arr is defined. but because arr isn't a constant it can be reassigned and flow can't tell if it was reassigned to `undefined` or not, than it will throw an error.

- The third method will always return a method which return arr, which is either undefined or array.

```javascript
function func1(arr?: Array<string>): Array<string> | void {
  return arr && arr.map(item => item)
}

function func2(arr?: Array<string>): () => Array<string> | void {
  if (arr) {
    return () => (
      /* flow can't tell if arr is defined in here because it is in another scope,
       * and in some place in this
       * function or in the outer function arr could be reassigned to undefined */
      arr.map(item => item)
    )
  }
}

function func3(arr?: Array<string>): () => Array<string> | void {
  return () => arr && arr.map(item => item)
  // could be written like this: return () => arr
}
```

**Comment by zaaack** [comment]
@iamchenxin Thanks! I think I get it.

**Comment by zaaack** [comment]
@itamar244 Sorry for my unclear demo, actually the situation is more complicated in my real code:

```js
function func(includes?: ?Array<string>) {
   let names = ['a', 'b', 'c']
  if (includes) {
    names = names.filter(name => includes ? includes.indexOf(name) !== -1 : true)
  }
}

/* flow errors:
names = names.filter(name => includes.indexOf(name) !== -1)
                                    ^ call of method `indexOf`. Method cannot be called on possibly null value
7:     names = names.filter(name => includes.indexOf(name) !== -1)
                                    ^ null
*/
```

Although the array function is in another scope, but it is called immediately and won't cause any error in this case

https://flow.org/try/#0PTAEAEDMBsHsHcBQzIFcB2BjALgS1uqGlgBS5bSoAmApgM4D8AXKAwIIBOHAhgJ4A8dbB3IBzAHwBKUAG9EoBdBrZQ6bgFt6oALygA2gHJuBgDSgDAI1PnMBgLrzQuSKDIVq9aXIUK1mujqqGvQAdJC40Ng0HCR+NDriTu60dCHktAAeAPKQscHSAITaugC0AIySjgC+iFVAA

**Comment by itamar244** [comment]
you could also write 
```javascript
names = names.filter(name => (
  include = null,
  include.indexOf(name) !== -1
))
```

which will set include to null and will crash. what I meant to say is flow can't keep knowing for sure that the the value inside the if statement is true after one expression.
to solve this you can do
```javascript
const tmpInclude = include
if (tmpInclude) {
  names = names.filter(name => tmpInclude.indexOf(name) !== -1)
}
```

**Comment by zaaack** [comment]
Thanks, learn a new way to get rid of flow type check. I have write too much any type casting before.
