### ISSUE TITLE
Not understanding German umlauts

### ISSUE THREAD

**Issue by Adertoilop** [facebook/flow#3991]
The app works fine, I'm just getting a flow error whenever there's an umlaut in the filename:

![2017-05-21 5](https://cloud.githubusercontent.com/assets/25416420/26282917/d8482d92-3e1b-11e7-90cf-cb3c94167ce8.png)

**Comment by itamar244** [comment]
Why would you code not in English. it will make your program only available to people who know German and programming languages reserved words are in English so this make your have two languages to bear.
My native language isn't English but I still program only in English

**Comment by Adertoilop** [comment]
Of course, I could do that, but that's not the point, is it?
It feels forced to me to translate everything just to avoid errors, especially since flow is the only part of my workflow that doesn't like it.

**Comment by Brianzchen** [comment]
Looks like it works fine now and will close issue. From the screenshot I tested with `ä`  char

<img width="365" alt="Screen Shot 2020-11-01 at 1 41 41 pm" src="https://user-images.githubusercontent.com/12436524/97794009-0d391580-1c48-11eb-92d0-16e489b40057.png">
