### ISSUE TITLE
Extend Object types

### ISSUE THREAD

**Issue by xareelee** [facebook/flow#3993]
How can I define an `Object` type extending another `Object` type?

For example

```js
type Foo = {
  a: string,
  b: number,
}

// The type Bar just extends type Foo, but it is verbose and error-prone when refactoring.
type  Bar = {
  a: string,
  b: number,
  i: string,
  j: number,
}

// pseudo code: demonstrate how I want to declare the extended object type using ES6 syntax
type  Bar = {
  ...Foo,   // extend the Object type from type Foo
  i: string,
  j: number,
}
```

I did not find this feature in the docs https://flow.org/en/docs/types/objects/.

**Comment by agentcooper** [comment]
Check intersections types.

```js
/* @flow */

type Point = {
  x: number;
  y: number;
}

const p: Point = { x: 1, y: 2 };

type PointWithAngle = Point & { angle: number };

const pa: PointWithAngle = { x: 3, y: 4, angle: 30 };
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKcAlgHYZgC8YA3qmGAB4BcYZArgLYBGeATgG4GYLG068BwgL7oAxnDIBnSjjbFylGrWZsAjABpRbAExhpwzLgIaKAdRIYAFgEEyAcxgEatygDI6MABDDy9xbj5+c0sFZVUg9VJ7R1dQ70DWMABmIzEwABYjEM88NiyABmigA

**Comment by xareelee** [comment]
@agentcooper Thanks!

I did not notice this doc section.
