### ISSUE TITLE
Property refinement interacts badly with `break` and `continue`

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#3995]
This works as expected:

```js
declare var x: Array<{ foo: ?string }>;

for (const y of x) {
  if (!y.foo) throw 0;
  y.foo.toLowerCase();
}
```

This doesn't:

```js
declare var x: Array<{ foo: ?string }>;

for (const y of x) {
  if (!y.foo) break;
  y.foo.toLowerCase();
}
```

```js
declare var x: Array<{ foo: ?string }>;

for (const y of x) {
  if (!y.foo) continue;
  y.foo.toLowerCase();
}
```

On the other hand, `break` and `continue` work for other refinements:

```js
declare var x: Array<string | number>;

for (const y of x) {
  if (typeof y !== 'string') continue;
  y.toLowerCase();
}
```

**Comment by M-TGH** [comment]
Encountered this problem, bit disappointed in the inactivity. 😞

[Here's a flowtry link for those wanting to take a peek at it there.](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAG56gAeAXKAIK67YCeAPAN6iSyyUD8AzgC64AlgDsA5qAC+APgDcyEKADqsXAGse5RO1ygAFBljD+oeqFiQyASlDNEoUIIu6AhPQB07WNb4ALXAlAABjl7d083PlgAGQQ0XABhbB40XUs5CXkwABFYUGFYPlB4FVVNbT0DI0LTcysbOwcnVw8Oa0q+EQBXNBCTFtgI6NiEpJS0xAytFQrDYxqLUmtbe0c9Zs9rACN8bFVesI5BmPg4xOTU9KA)

Addition: Also an issue for `for...in` loops.

**Comment by SamChou19815** [comment]
Now all of them work.
