### ISSUE TITLE
Better error messages for Array mutability errors

### ISSUE THREAD

**Issue by sebasgarcep** [facebook/flow#3998]
```javascript
/* @flow */

type EnumType = 'variant1' | 'variant2';

const enumArray: Array<EnumType> = ['variant1'];

type ArbitraryObject = {
  arbitraryArray: Array<string>,
};

const arbitraryObjectCollection: Array<ArbitraryObject> = [
  {
  	arbitraryArray: [...enumArray],
  }
];

const arbitraryObjectCollectionError: Array<ArbitraryObject> = [
  {
  	arbitraryArray: enumArray,
  }
];
```
I ran into the previous error and it struck me out as odd. After a while I found out the answer: the previous snippet errors out at the end because if the following happens:

```
arbitraryObjectCollectionError.arbitraryArray.push('random_string');
```
then the type constraint is broken. That's fine. What's not is that the error reports with the following message:
```
string This type is incompatible with string enum
```
which on first glance doesn't make much sense. A better option might be something alone the lines of:
```
enumArray is mutable and therefore cannot be passed safely to places with different type constraints. Consider cloning the array to pass it around
```
I can help with a pull request if someone points me in the right direction.

**Comment by SamChou19815** [comment]
Fixed by https://github.com/facebook/flow/commit/9a1796ad0047fbfa3ff4b6b69e4b8809390b7482
