### ISSUE TITLE
Type spread operator makes everything optional

### ISSUE THREAD

**Issue by danwang** [facebook/flow#3999]
When using the spread operator on types, it produces a record type where every field is optional ([flow try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeBDAXFAdgVwLYCMIAnAXwG4AoUSKAIQWQDpmZyKKAKVDbTAEwgAzAJaYIfEhloBKMkA))

**Comment by samwgoldman** [comment]
See explanation in #3534. Sorry about the lack of docs—will fix asap.
