### ISSUE TITLE
Extract `default` property from ModuleNamespace obj Unknown global name

### ISSUE THREAD

**Issue by sporto** [facebook/flow#400]
Given this file:

```js
/* @flow */

var React   = require('react');

class Comp extends React.Component {

	render() {
		return (
			<i className="fa fa-spinner fa-spin"></i>
		)
	}

}

module.exports = Comp;
```

When I replace `require` for `import`:

```
/* @flow */

import React from 'react';

class Comp extends React.Component {

	render() {
		return (
			<i className="fa fa-spinner fa-spin"></i>
		)
	}

}

module.exports = Comp;

```

I get this error:

```
.../Loader.jsx:3:1,26: Extract `default` property from ModuleNamespace obj
Unknown global name
```

What does this mean? How to fix it?

**Comment by jeffmo** [comment]
Ah this is because the 'react' module is not defined in terms of a default export. Instead it's defined with named exports.

In your second example, what you probably want instead is:

```
/* @flow */

import {Component} from 'react';

class Comp extends Component {

	render() {
		return (
			<i className="fa fa-spinner fa-spin"></i>
		)
	}

}

module.exports = Comp;

```

**Comment by jeffmo** [comment]
It's now completely clear to me that this error message is horribly unclear, though (this is my fault) -- so I will use this issue to track cleaning that up.

**Comment by jeffmo** [comment]
Here's a quick pull request with some updates to various error messages that I hope will make them more clear: https://github.com/facebook/flow/pull/401

**Comment by samwgoldman** [comment]
Cleaning up the error messages will definitely help. However, shouldn't we be able to write `import React from "react"`? Isn't this a bug in in `lib/react.js`?

**Comment by jeffmo** [comment]
@samwgoldman: I'm not actually sure if that's what we want here (though it's really up to the React crew to decide how they want to expose the interface). React is currently set up as a module with a bag of named exports. In ES6, the intended mechanism for importing from such a bag (i.e. the equivalent of `var React = require('react'); React.Component;` in ES6 would be `import * as React from "react"; React.Component;`. This should work as-is/already.

Default exports are strictly separate from the "module namespace object" in the ES6 module system (whereas in CJS they're kind of conceptually interchanged). We do have a CommonJS compatibility layer that maps overrides of `module.exports` to *look* like a default export (from the perspective of an ES6 import) -- but that's sort of a compatibility feature intended to manage long-tail support for CJS.

**Comment by samwgoldman** [comment]
I understand. I guess it's a babel or browserify issue, but `import * as React from "react"` doesn't seem to work for me, but flow does identify the correct types for functionality imported this way.

**Comment by jeffmo** [comment]
Hmm, yea it seems the Babel ES6<->CJS interop doesn't actually attempt to copy static properties from a CJS exports object on to the ES6 module namespace object. IIRC from speaking with @sebmck a little while ago, I think this is just to simplify the CJS interop story.

@sebmck: Any reason Babel couldn't or shouldn't copy "static" keys from a foreign `exports` object over to the namespace object when doing an `import * as` from a CJS module?

https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&playground=false&code=import%20*%20as%20React%20from%20%22react%22%3B

**Comment by samwgoldman** [comment]
For what it's worth, I made a small test case with babel and browserify: https://github.com/samwgoldman/babel-browserify-commonjs-compat

**Comment by jeffmo** [comment]
@samwgoldman: Your example is slightly different because `commonjs.js` exports a function (instead of an object whose keys are the intended "named" exports like React does).

Doing `import * as cjs from "./commonjs.js"` should in this case (per all systems, I believe) give you an object that looks something like: `{default: function() { alert('foo!'); }}`

For a system like React, a comparable test case might have commonjs.js do something like this:

```
module.exports = {
  foo: function() { alert('foo!'); },
  bar: function() { alert('bar!'); },
};
```

**Comment by samwgoldman** [comment]
Ah, I really should read up on ES6 modules, then. Sorry for the noise!

**Comment by jeffmo** [comment]
No worries! Always happy to talk it through.

The CJS<->ES6 interop story is pretty subjective though...there's not necessarily one prescribed right or wrong way to do it. It would be really nice if Flow and Babel had close enough interop stories though for most (or all?) cases, so these kinds of things are still valuable to report.

**Comment by sporto** [comment]
I don't think this is an issue with how React exports itself. For me `import React from 'react'` works just fine with Babel + Webpack in my application, is just Flow that complains.

**Comment by sporto** [comment]
Also, on a side note, doing:

```
import {Component} from 'react';

class Comp extends Component {
	render () {
		<section>...</section>
	}
}

module.exports = Comp;
```

When using webpack + babel this JSX expands to:

```
...

	_createClass(Comp, [{
		key: "render",
		value: function render() {
			return React.createElement(
				"section",
				{  },
				"..."
			);
		}
	}]);

...
```

Note `React.createElement`, so then I get `React is not defined` in the browser.

**Comment by jeffmo** [comment]
I see. Ok, I suppose we just need to update the Flow interface definition for React to indicate that it also exports all of its APIs via a default export that's an object that matches the named exports.

This will be repetitive with the current declare syntax, but doable. I'll take a closer look tomorrow

**Comment by jeffmo** [comment]
On second thought: A more thorough fix is just to ensure that interface definitions follow the same CJS interop rules as regular CJS modules do for now.

**Comment by sebmck** [comment]
@jeffmo 

> Any reason Babel couldn't or shouldn't copy "static" keys from a foreign exports object over to the namespace object when doing an import * as from a CJS module?

Not really, but it really should.

**Comment by jeffmo** [comment]
@sebmck: Cool, I'll see if I can whip up a PR really quick

**Comment by jeffmo** [comment]
Ok, PR #405 should make modules specified by an interface definition work through the same ES6/CommonJS interop channel that modules defined directly work.

The tldr is that this should enable `import React from "react"` to work in the same way it does for Babel and Browserify. I'll close this issue once that PR gets merged

**Comment by jeffmo** [comment]
(cc @jergason who I think was asking about this a week or two ago as well)

**Comment by jeffmo** [comment]
Fix will go out with the next release
