### ISSUE TITLE
Return type of Object.keys should be parameterized of key type of argument.

### ISSUE THREAD

**Issue by emdash** [facebook/flow#4001]
For example, in a dictionary type:
`
type DictionaryKeys = "foo" | "bar" | "baz";
type MyDict = {[DictionaryKeys]: Object};
function keysOf(d: MyDict) => Object.keys(d);
`
`keysOf` should have a return type of `Array<DictionaryKeys>` rather than `Array<String>.

I feel this should also apply to the iteration variable in a `for...in` loop, so long as you're iterating over a dictionary, or exact object type, perhaps also assuming you apply the `hasOwnProperty` refinement.

**Comment by pauloborges** [comment]
Example:

```js
type MyEnum = 'foo' | 'bar';
type MyObj = {
  [MyEnum]: number
};

const myObj: MyObj = {
  foo: 1,
  bar: 2
};

Object.keys(myObj).forEach(key => console.log(myObj[key]));
```

Error:

```
11: Object.keys(myObj).forEach(key => console.log(myObj[key]));
                                                        ^ string. This type is incompatible with
3:   [MyEnum]: number
      ^ string enum
```

https://flow.org/try/#0C4TwDgpgBAsiCiA7ArgWygXigcgGYHt9soAfHAIwEMAnbAbgChRJYQB5cgK0ygG8GoUANpwkaALoAuKClTkI1BgF9GDAMb5EAZ2BRU7LtLgduWfoIL5pARgA0AqFWrSATMtUmIa4ADoA1hAgWgAU+iYAlD4E1PCUagAWwQEgmAB8UBra+AA2ED7Z+ADmoQacQsni4eF0QA

**Comment by pauloborges** [comment]
The only way I found to circumvent this issue is to double cast it, first to `any`, and then to the proper type:

```js
Object.keys(myObj).forEach(key => {
  const myKey = ((key: any): MyEnum);
  console.log(myObj[myKey]);
});
```

Is there a better way to do this? Is it intended or a defect?

**Comment by SamChou19815** [comment]
They should have good types now.
