### ISSUE TITLE
How to cast node's require ... 

### ISSUE THREAD

**Issue by ClaudiuOctavianMuresan** [facebook/flow#4004]
Context:
Flow coverage reports uncovered code in Visual Studio Code (using Flow Language Support extension at version 0.7.0) for the "require" statement:

```
const PROCESS_PLAN_DEFINITIONS = 'plugins.json'; 
const processPlanDefinitions: Array<ProcessPlanDefinition> = require(PROCESS_PLAN_DEFINITIONS);
```

Is there a way I can cast the require return type to desired type?
I am using flow at version 0.44.1

**Comment by SamChou19815** [comment]
We now error on non-literal require. The only way is to suppress.
