### ISSUE TITLE
$ObjMap and splat gives incorrect results

### ISSUE THREAD

**Issue by danwang** [facebook/flow#4007]
When splatting the result of an `$ObjMap`, I seem to lose type safety ([flow try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeBDAXFAdgVwLYCMIAnAXwG4AoUSKAIQWQDpmASAeXwCsBZFMAHhgAaKPwAqAPgAUYgJQIJsIkRQhxEieSrhoAYQZJmjFgFEAHigDGwfuy68Bw0ZJnz4imMtXqNW6tAARAyM7Hj5bcysbGAkRdVcFJRU1SU1KfygTYNZI61sOMIFTCzyYuJc5RM9knzSKCilUDAByFGaSDFpZSkb0KFb2jF1uhqb+to6oAJHelomME26gA)):

```jsx
type A = {a: number};
type B = {...$ObjMap<A, <T>(T) => Array<T>>};
type C = {...$Exact<$ObjMap<A, <T>(T) => Array<T>>>};
type D = {...$ObjMap<$Exact<A>, <T>(T) => Array<T>>};
type E = {...$Exact<$ObjMap<$Exact<A>, <T>(T) => Array<T>>>};

({a: 'a'}: B);
({a: 'a'}: C);
({a: 'a'}: D);
({a: 'a'}: E);
```

It seems like no matter what combination of `$Exact` used (see https://github.com/facebook/flow/issues/3999), it says "No error!"

**Comment by asolove-stripe** [comment]
As of Flow 55, all of these now error and give messages that _seem_ right to me.
