### ISSUE TITLE
React components cannot handle defaultProps declared with intersection type

### ISSUE THREAD

**Issue by danwang** [facebook/flow#4008]
When using `Class<React$Component<...>>` with an intersection type as the object, Flow fails to recognize the default props. ([flow try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeBDAXFAdgVwLYCMIAnAXwG4AoUSKAIQWXwxwOPIqvGgAUiB7MAGcGSClCjoseQkQA0YqEyms5FdpxoBhPrjB9METMAAqDTQBsUgwQB4AShBQBjYABJtu-YeA24AMjpZKF4BQSCUTBAAPijKJ31BYCgPPQMjDBSvI1NEAAocc3MMCJAASkobTLSkgHpYoA))

```jsx
type A = {a: number};
type B = {b: number};

type Props = {
  a: number,
  b: number,
};

type ComponentT = Class<React$Component<A & B, Props, any>>;
const Component: ComponentT = (null: any);
<Component />;
```

On version 0.46.0, Flow errors with `. Internal error: Not_found`
On version 0.45.0, there's a type error saying that `b` was not passed in as a prop.

**Comment by asolove** [comment]
In Flow v0.53, the default props are no longer part of the type signature of the `Component`, and a number of default prop type bugs have been fixed.

[When I update this code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudQgE8cNMAEEwAXjABvUgC4wAOwCuWAEY18AX35CRYAEJTZ6xao1bdA4aIAKLHJWkzUYMubWb8AGjdgzZS8tP2tUGBpiABMaKFIVGEJyRQkAMiMTV3cFMAAmP3dAgGZUMIjiAFlBAGFWPCUaJWJpAAo5HwDtAEopAD4wAB4ojAA3XrltGXVtAeBhsf4q2tw4BqaAOhi4hMIHOCcTLfjE8n5UAaW61cbCYF6gA) to 53, it type checks as expected.

So I think this issue can now be closed. (/cc @calebmer)
