### ISSUE TITLE
Indexer prevents property lookup on classes and interfaces

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#4014]
Example:

```js
declare class X {
  foo: string,
  [number]: number
};

declare var x: X;

x.foo; // ok
x[1]; // ok
x['foo']; // error
```

This works fine with object types.

**Comment by aksuska** [comment]
+1

**Comment by moeen-basra** [comment]
```
class Model {
 setKey(value: string | number): void {
    this[this.PRIMARY_KEY] = value
  }

  getKey(): string | number {
    return this[this.PRIMARY_KEY]
  }
}
```

**Comment by bradennapier** [comment]
FYI that the fix for this currently is to extend the class with `Object`

```
declare class X extends Object {
  foo: string,
  [number]: number
};
```

**Comment by manjunath-satyamurthy** [comment]
I faced a similar issue. 

`//@flow
type x = {y?: {[k:string]: string}}

let y: x = {'y':{'a': 'b'}}

let test = y.y !== undefined ? Object.keys(y.y).map(l=> y.y[l]) : null
`
Flow finds this to be invalid.
Error message:
`Cannot get `y.y[l]` because an indexer property is missing in undefined [1]`

I circumvented this problem by making a redundant check.

`
if (y.y !== undefined){
    let test = Object.keys(y.y).map(l => {
        if (y.y!== undefined && l in y.y){ // y.y !== undefined is redundant
            return y.y[l]
        }
    })
}

`

**Comment by M-TGH** [comment]
The workaround seems to have been murdered with `flow@0.81.0`; see [flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAOTgEkA7AEwFMAPKgJzAG9UwwBIAB3rk4YBcAngC4wufvQCWZAOZgAvGADkAQTAAFHn3pClAblTtDMqvwAqACyqbeAwQAoAlCzauw9UwFd6ZMPwuSuADaSty2OoJKALp6YMDAYIC8G4BEe6yuAL6omajxYABicDDwCNJynrhUFH5wYAhw9ADWYAA8YAAcAIzVYNhFiGDlpWAYcAC2nJ78lWBh2vySVARwvtjDOPiY6wQqZOTUdPQA6pL+bQAMYLRTlAQA8gBGAFZUGPzMaVxadqLiUrIKyjUNjmkQMRnYJnMVmBdicLjc7i8Pj8AWCoS+EWisVyKTAACUSOowId6g1sDxPJQwLBEBBmmcAHQAZgA7AyLgBaanFCCM87stJsTLZXIkzwwKr3KhgMiSDDSyRQFGBWqk6YkMSeTicOAVYSbPDbXaUWgMY7+JkAFgATMw4gkAMJbMDSfYMAhSoa4LU6nTTaRgRlW63sl0ER7lN6rEoSsAyTyLXAAGhdbxG4sl0tWADd3ZJlpdyTAFox6mAcFN6B8gr9SlFRKNJHQKNiEikPrNvmIJENFKoNBjdGDjKZLNZBw5nILXB5+N5fP5AiFO5iYtPhehcgAhZblS70Hj0WKUkajUZUMhvKBljBWDANIb2U-ny-Tfg1MhwN73eDYN7+aUGEPAhi3ERwchAVBpErKBsHlMAHmeV5yBguDpXhdgax7WR6zARtmwMbIsENMAdj2U16BQhhYPgyRxhgKgX34O4nhefgqPoGiqBcT5wiEH5sLkPsgQnfRDBHKFxz4yd4TcWd52VNEV10Nc3A3FAgA)

Any updates on this issue/other workarounds that don't involve completely dropping the use of classes?
