### ISSUE TITLE
Spread is unsound when combined with union types.

### ISSUE THREAD

**Issue by pythonesque** [facebook/flow#4016]
Small testcase:

```
type Foo =
  | { tag: 'Foo', foo: number}
  | { tag: 'Bar', bar: number }

const f : Foo = { tag: 'Bar', bar: 0 }

const b = {...f}
console.log(b.foo.toString())
```

b.foo is, of course, undefined and this will fail at runtime.  Flow correctly reports an error if you assign b to f directly instead of using spread.

The root cause of this issue seems to be that spread is inferring the type `{ tag: 'Foo' | 'Bar', bar: number, foo: number }` which is definitely incorrect here.

I realize that spread has a lot of issues and frequently can't infer a type when it *is* valid, but it seems substantially worse to me for a test case that uses only core JavaScript, explicitly annotates its type, and doesn't include anything that should be hard to track (like array accesses or property reassignment) to invalidate your program's correctness guarantees.

**Comment by SamChou19815** [comment]
We now error on this
