### ISSUE TITLE
Should flow be able to infer an error with Object.keys(obj) > 1?

### ISSUE THREAD

**Issue by guyellis** [facebook/flow#402]
I'm new to flow but I would have expected the following to have been caught by `flow check` without any special flow markup or interface files supplied:

```javascript
var obj = {
	one: 'one',
	two: 'two'
};

// Forgot to add length after Object.keys(obj)
var isBig = Object.keys(obj) > 1;

console.log(isBig);
// false but should be true.
```

For example, if I create that as a .ts file and run TypeScript against it then it produces:

`error TS2365: Operator '>' cannot be applied to types 'string[]' and 'number'.`

**Comment by mroch** [comment]
I think flow does catch this.

```
$ echo "Object.keys({one: 'one'}) > 1" | flow check-contents

-:1:1,29: relational comparison
Relational comparison with number may involve unintended type conversions of
-:1:1,25: Object.keys

Found 1 error
```

We may have fixed it recently, or it could be that flow is actually ignoring the whole file. Try adding `/* @flow */` to the top of the file, or running `flow check --all`.
