### ISSUE TITLE
Object type with indexer, saved to a variable, throws a syntax error

### ISSUE THREAD

**Issue by chrisregner** [facebook/flow#4022]
I've searched for a while but I can't figure out what I am doing wrong. This:

    @flow
    type PrefixesShape = {
        [string]: {
                [string]: string
        }
    }

throws this:

    file.js:3

        3:    [string]: {
                     ^ Unexpected token ]

**Comment by vkurchatkin** [comment]
You are probably using older version of Flow, try updating

**Comment by chrisregner-com** [comment]
Hmm, I'm not sure. I'm currently using v0.46.0, should I upgrade to v0.47.0?

**Comment by chrisregner-com** [comment]
Even the colon here (the one in line 3 `prefixToCssmods?: {`) throws syntax error. I'm using gulp-flowtype. Weird, I must have missed something.

    const convertCssModuleClassnames =
        (
            prefixToCssmods?: {
                [string]: {
                    [string]: string
                }
            }
        ) => (classNames?: string): string => (
            prefixToCssmods && classNames
            ? classNames.split(' ').map((className) => {
                let convertedClassname

                Object.keys(prefixToCssmods).forEach((prefix) => {
                    const regexp = new RegExp(`^${prefix}`)

                    if (regexp.test(className)) {
                        convertedClassname = prefixToCssmods[prefix][className.replace(regexp, '')]
                    }
                })

                return convertedClassname ? `${convertedClassname} ${className}` : className
            }).join(' ')
            : classNames
        )

**Comment by vkurchatkin** [comment]
Can you reproduce it on https://flow.org/try/ ?

**Comment by chrisregner-com** [comment]
[Here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnlAJYAeeAzgMoAWAhvmALxgDeqYYA2jQzFyAOwDmAXQBcXHv0HDx0sAtFi5AX1RbUAYzgjBYfSIBueYhgDCNGgFk4AEwCuMPFZhNbIpgFtachwAFDikFJQAKnA2NL5ONAD8MiRkVLSMLHgAlOwAfGBBup62AHJ+tEkqQmpZMqriCeyyvLzkUAWhqZHRtnGONGAAZIPGxTRl-jQ53C0tRV7j5TQAdDQ4MOQYQQDkYNtZy74sQYVjE9l5zbMtbhjGBuaWeI4eCz7+6NctAPIARgBWeF0GGWAGs8FgaCEwlQojE+lNllA4MQAKJMXQME6dcI5Nj5GZfOYGIykMR4Sg4JoiPBIABKeDEqMpQQABgA9AAknBxVA0rKynyJrXaQTJFJwywwtC281K5Sy0zkwt4Jke0peY3eBA4vO68PifD1Ej4csW-mWpHWGLwYsZEoANHt9hJlUStMKNIK3bNSBhnMQRPczBYNa9vOUwI1Wdy1aHnuGaNqNGBY2dyvywDIzecfWAvct-nBRDs9oLZim8DAaAQ2gUc0slV8-QGgw3Jm6PfmgA) it is. I suspect Flow doesn't support curried arrow functions well yet, does it?

**Comment by chrisregner-com** [comment]
[Here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnlAJYAeeAzgMoAWAhvmALxgDeqYYA2jQzFyAOwDmAXQBcXHv0HDx0sAtFi5AX1RbUUAK4iAxhnJwRYQ2YBueYhgDCNGgFk4AEz0w89mEycimAFtaAAocUgpKABU4RxpA9xoAfhkSMipaRhY8AEoZfSMTM1leUgw9YnMC41MREMNfJwA5INoUlSE1PI7FMRLeMHIoMDCIqhi4hLcaMAAyWYtGmhbgmhz+gcW-ZdaaADoaHBhyDBCAcjAznL3AlhD6pZXc9gA+Dc2wLwwLa1sMPDcPm2AWC6A+AwA8gAjABWeGMewA1ngsDRRulorEnFM1nsoHBiABRJiGBj3cIY9ZsN7ccGbSwiQRgUhiPCUHDsMAiPBIABKeDEhPZIQABgA9AAknApkQ0IpyYLpvCGIxZbJwe3+gge2yeOXWtKVAwZNjsAKB-lanJl4yx8USfBtlAkfAautae1IRxJeBCavZABpLlcJHIlVpwwqwx8yhVzCa-ualiCCEkwCKpQmzYDk60NGBM488yKwDI3c1WtHeBprjC4KJzpcFZt83gYDQCCqdRXVgaq8y8OVKlse7RoxGBtHY8OzmdNNogA), I've used non-arrow functions for my creating my curried function. It seems that curried functions aren't well yet regardless if it's arrow or not.

**Comment by chrisregner-com** [comment]
Anyway, it seems to be proved that my original issue isn't of Flow itself. Thanks.

> I've searched for a while but I can't figure out what I am doing wrong. This:
> 
>     @flow
>     type PrefixesShape = {
>         [string]: {
>                 [string]: string
>         }
>     }
> 
> throws this:
> 
>     file.js:3
> 
>         3:    [string]: {
>                      ^ Unexpected token ]
