### ISSUE TITLE
How to seal functions ?

### ISSUE THREAD

**Issue by PCreations** [facebook/flow#4026]
Functions seems to be unsealed by default, thus making call to undefined property on them possible : 
```

declare function bar(): () => void;
declare function baz(): number;

bar().nonExistentMethod(); // flow doesn't complain here (but it obviously should)
baz().nonExistentMethod(); // but does here (as expected)
```

https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwCNYAKASgC54z4BeAPngDcctgBuAKFElgRXWx5CUAF5lKqZAFsCIGJw5EYZAHSo8AUQAeWAM4YQqDAFkQGABY5gZTkTGk1mnfsMmzl66TZA

**Comment by madbence** [comment]
that's a very old issue (#106) :crying_cat_face:

**Comment by PCreations** [comment]
Oh ! Good catch, didn't find it when searching for similar issue. I'm gonna close it so.
