### ISSUE TITLE
Is it possible to spread an object type to the class declaration?

### ISSUE THREAD

**Issue by nodkz** [facebook/flow#4028]
I try to describe mongoose models. 
Model has a list of fields, which can be passed to the constructor, also it can be accessed via getters and setters:
```js
const user = new User({ name: 'John' });
user.name; // get string;
user.age = 30; // set int
```

I want to describe fields one time as a Type. And use this type in `constructor` and spread it as props in the class. Something like this:
```js
declare type UserFields = {
  name: string,
  age?: number,
  // and 55 fields more
}

declare class User {
   ...UserFields;  // <----- how to spread a type to the class props?
   constructor(data?: UserFields);
   someOtherProp: string,  
   findOne(): User,
}
```

Thanks.

**Comment by agentcooper** [comment]
I hope this is close enough.

```js
declare class UserFields {
  name: string;
  age?: number;
}

declare class User extends UserFields {
   constructor(data?: $Shape<UserFields>): User;
   someOtherProp: string;
   findOne(): User;
}

const user1 = new User();
const user2 = new User({ name: 'Jack' });

// $ExpectError
const user3 = new User({ rubbish: 'Jack' });

console.log(user1.name);
console.log(user2.someOtherProp);

// $ExpectError
console.log(user1.rubbish);
```

[Try](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwKrJDAYgSxAmDQG8AoeeAOygFsQAueZAFxjyoHMBuC+KTiAD8TKgFdaAI2y8AvmTKgkcRNFQYsMeCAAeLEFWIbs+QkfKVEAeyqsYYsCyswAFMCgsoI+ABIAygAWUAAOIAA8mCYERMgAfACUTJEwvJbIVvQA8iwB2AAKMFbBTHYcPHzwAGYcwJlUIC6Jxilk8mRgNqzwYpoAjPAAvNQgAO7NjbwdtizdmgBMg8NjyS4k1HSM8ADkAFJQYADWW-Cy8bxkAPQXvgCiOqGONzCFMO2dMz3YAMyL9cuaq3g9kkkjwyACTF2+yOJzOCim6QgIAAdBArJwXJ8YL1kTR6HCEVYkaj0Zj5sj0lkcvlCsE4Zdrj47g8WE8Xm9bESUWiMViccDQeCzkA).

**Comment by nodkz** [comment]
@agentcooper yay!
Thank you very much. Exactly what is needed.
