### ISSUE TITLE
Failure internal error package node_modules/react/package.json not found

### ISSUE THREAD

**Issue by seanhess** [facebook/flow#403]
I'm getting a weird error saying it can't find react's package.json:

```
/Users/seanhess/projects/serials/web/app/admin/source.js:
Failure("internal error: package /Users/seanhess/projects/serials/node_modules/react/package.json not found")
```

I'm on flow 0.9.2 (but I've had problems since 0.8.0). My project is here: https://github.com/seanhess/serials. 

It's strange because if I just run `flow` I don't get any errors, but if I run `flow file.js` I get the error. 

```
serials> flow
No errors!

serials> flow web/index.js

/Users/seanhess/projects/serials/web/app/admin/admin.js:
Failure("internal error: package /Users/seanhess/projects/serials/node_modules/react/package.json not found")

... repeated 7 times: each time I import react
```

It seems similar to this issue in react-native: https://github.com/facebook/react-native/issues/938

**Comment by seanhess** [comment]
Note that I've tried deleting node_modules and reinstalling, it doesn't help.

**Comment by gcazaciuc** [comment]
Not sure about the exact root cause for the issue but i've come across it and the issue seems to be in the fact that flow didn't seem to understand where the react modules resides.
So what i did was to put flowconfig one directory deeper that node_modules folder is and change it to something like( [include] section is the relevant part ):
[ignore]
.*/test/*
.*/css/*
[include]
../node_modules/react/*
../node_modules/react-intl/*
../node_modules/react-router/*
[libs]
../interfaces/*

[options]

However I'm not entirely sure that this is the way to go or if it's a bug from within Flow.

**Comment by samwgoldman** [comment]
I've run into this before, and it seems to go away if I stop and re-start the flow server.

**Comment by samwgoldman** [comment]
This seems to happen when node_modules is included in the [ignore] section of .flowconfig. It's not super clear to me why people need to ignore node_modules, but right now people are suggesting weird/wrong fixes for this issue, like "breaking" the require statements to be in the form: `require('' + 'foo')`.

**Comment by seanhess** [comment]
@samwgoldman Restarting doesn't make it go away. 

Also note that in the linked project I'm only ignoring `.*node_modules/webpack.*`, not the whole node_modules folder. 

I tried removing that ignore to see if it fixed it, but it didn't. I still get no errors when I run `flow` and many errors about react's package.json missing when I run `flow <file.js>`

**Comment by samwgoldman** [comment]
@seanhess Thanks for the clarification. Do you have a reduced test case you can share? It seems there are a few different issues here, and it'll be helpful to be able to reproduce your issue specifically.

**Comment by seanhess** [comment]
Here's my project: https://github.com/seanhess/serials. 

```
> git clone git@github.com:seanhess/serials.git
> cd serials
> npm install
> flow
> flow web/app/admin/source.js
```

Does that help? You will see "No Errors!" on the first `flow`, and a bunch of errors on the second.

**Comment by seanhess** [comment]
I figured it out! 

I had accidentally put an empty `.flowconfig` file in the subdirectory `web` with different settings. So flow would start 2 servers: one in my root folder, which was reporting "No Errors", and one in my `web` directory, which reported different errors on `flow web/**.js`.

I removed the 2nd `.flowconfig` file and I'm getting consistent errors again. Hooray!

**Comment by grabbou** [comment]
@samwgoldman but when node_modules are not ignored, I get lots of `react-native` and other libraries errors, like:
```
react-native/Libraries/AppRegistry/AppRegistry.js:14:17,36: invariant
Required module not found
```

**Comment by abritinthebay** [comment]
I'm still getting this, no solution so far. It's actually failing on Reflux for me (atm) but none of the above works.

**Comment by abritinthebay** [comment]
solved it on my end - adding the node_modules dir into [include] fixes it.
