### ISSUE TITLE
Indexer mismatch ignored in async function

### ISSUE THREAD

**Issue by mjomble** [facebook/flow#4033]
Flow 0.47.0 [does not report any errors](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKMoFkCGY4C8cA3nANoDOmAlgHYDmAugFxxVR31wC+AUKJFgJkqAHIBXALa58RUpRoMWcWlIBGwKD168AxhFpU4IVhmx5CJOADMIEVgHIcD7fsPxrlnBUS1dcAAoASlYJaQsCAD5jXiA) in this code:

```javascript
export type StrMap = { [string]: string }
export type NumMap = { [string]: number }

const x: StrMap = { foo: 'a' }
const f = async (): NumMap => x
```

despite the StrMap / NumMap mismatch. Or the fact that the return type should probably be wrapped in `Promise<...>`
However, if the function is not asynchronous, [the mismatch is caught](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKMoFkCGY4C8cA3nANoDOmAlgHYDmAugFxxVR31wC+AUKJFgJkqAHIBXALa58RUpRoMWcWlIBGwKD168AxhFpU4IVhmx5CJOADMIEVgHIcD7fsPxrlgBQBKVhOkLAgA+Y14gA):

```javascript
export type StrMap = { [string]: string }
export type NumMap = { [string]: number }

const x: StrMap = { foo: 'a' }
const f = (): NumMap => x

----

1: export type StrMap = { [string]: string }
                                    ^ string. This type is incompatible with the expected return type of
2: export type NumMap = { [string]: number }
                                    ^ number
2: export type NumMap = { [string]: number }
                                    ^ number. This type is incompatible with the expected return type of
1: export type StrMap = { [string]: string }
                                    ^ string
```

**Comment by agentcooper** [comment]
`f` returns a Promise, so this works:

```js
export type StrMap = { [string]: string }
export type NumMap = { [string]: number }

const x: StrMap = { foo: 'a' }

// $ExpectError
const f = async (): Promise<NumMap> => x
```

**Comment by dpatti** [comment]
I think the more general issue is matching class instances with indexer objects. Specifically:

```js
type StrMap = { [string]: string };

class Foo {
  bar() {};
}

const x: StrMap = new Foo(); // ok?
const s: string = x.bar; // ok?
```

At this point, `s` is typed as a `string`, but is definitely a `Function`. This is related to the original issue because flow is matching the implicit `Promise<StrMap>` return against the `NumMap` and not erroring.

**Comment by SamChou19815** [comment]
This was fixed a while ago.
