### ISSUE TITLE
Incompatible Type Error Union Types

### ISSUE THREAD

**Issue by richbai90** [facebook/flow#4034]
Why is this union type an error?

    type Data = number[] | {}[] | Array<{}[]> | Array<number[]>

When I go to check my code it gives the following

```
build/js/helpers.js:2
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                 ^^^^^^ number. This type is incompatible with
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                            ^^ object type

build/js/helpers.js:2
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                 ^^^^^^ number. This type is incompatible with
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                                         ^^^^ array type

build/js/helpers.js:2
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                 ^^^^^^ number. This type is incompatible with
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                                                       ^^^^^^^^ array type

build/js/helpers.js:2
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                            ^^ object type. This type is incompatible with
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                 ^^^^^^ number

build/js/helpers.js:2
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                                         ^^^^ array type. This type is incompatible with
  2: type Data = number[] | {}[] | Array<{}[]> | Array<number[]>
                 ^^^^^^ number
```

**Comment by madbence** [comment]
can you reproduce it in [flow try](https://flow.org/try/#0C4TwDgpgBAIghsOUC8UB2BXAtgIwgJwG0BdKAHygG8BfE8qAQX3zhAB4aSA+epl9zLgLcA3EA)?

**Comment by richbai90** [comment]
I've updated the example with my code causing problems. Check out this [flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagCIENk9QBeUAOwFcBbAI0wCcBtAXVAB9QBvAXxfdACC9enlQAeHiwB8-ISPGVaDaYkSYAHulj1koACaZIeCtF2dEoUOnqZ0+QgAo9BIgC5cLgDQXLodQIBjAMwAZxDtUHcHHn5FOnoAShIZOIZ+EOR6AEsyAHN+e0xvX1BUQOCwiKiYjlTE5PJqeOLfZCyqbHcaWFhoTDwyElAjaBCin0s2joAxbSoCSNAM7LzYk2ghymhoJPMSkFAAYRsCTABRYW0ACQG9PvoJ4YoyALbYQYAFPBEO5AYAWSyIXmyACAAszupgug3mQHB0wnhcp0lpkcrkku4AG6wLJ6LiPSZgoEAOgRISR2FI5MpAG5CaBkMSQiSyHgOkMAORfH6YP70QHAgjgyHQ2Gc+klbiqEpZSCgBxTbAAMmVoAAhErZvQQbsGUz6AgFWRMPBQDz2XyAUCQSKobZYQ5OVq5gsyLBdNZYFi8Zh8fAskzGe1sDAkUs+YzYIz6BRMJyEglJb5pY8Au8MqB5ughk5FgB5GgAK0wrzWSnonlAWUWdSSxBkexKoHTZEzzkIZz6VCGPGTsvliowmFg8vxxAnoE5sGLpeQCYJzd8coVehJreWFFeEQnpE5clEC6bS8sNmQFHogzX2fheHQSYZlmlJ+rg6VepflhXipD2pBGsnTlbFgcEj0fZsN09b4xgAFRDIYlR5MYfxmV1kAfT9fA7PAu0wKgSXUIZ0GgzA4I6Bx-CCUJwnoJxE37T9sNw-DUCGMoqMqWi9Awz9uFATBRmwY9GJcZiCM2U0PD+Cjymo7Q6J4zCmO7ElWNIdiKhouiGKXZ8Tz4gSxkXETOxUwjSEozT5O4nTm2UvDVLY2TOO08C9KlfjBOMpd7Pw8zq1syxfMc0g9Fs9zfDPC8r1E7sGO4BjIOGNC-j0ewiFClwyTvW97wYqLL2SnUCFS9LGAABmYdcM0yLdkB3QCD1QTlQAAfiKkFSpcRZGEgFK-XS5hk24bwEqAA)

And here's a [fiddle](https://jsfiddle.net/L6kyk1tu/2/) of how it is meant to work

**Comment by agentcooper** [comment]
I tried to rewrite your types in a DRY way. [I think it works now](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFVALygDyARgFZYDGKoAPqAHYCuAtqVgE72gCCnnAIZoAPGUo0eLdlwB8ydNlAARQSkGE+A4SNzzEWAB4ZYnWgBMskQc2i0A3olCgMnLBlXqAFObUaAXCp+ADROzqCGvFRUWADOsaaggV64AJSEskxsHNwMsSicAJaMAOY8nlih4aBoUTHxiclpGVkynFXhKIWsOIGksLDQWIKMmtbQsZVhzl09AGKmrGpJoPlFpVK20Jos0NDpjtUgoADCbmpYAKICpgASI+ZDnNOgkMyMNIWwowAKgkI9FBcACyhViSxQVAAFpdDDEMF1vl4evFBCVeqsCsUSulAgA3WCFcygQ7VUAoKFggB0KNiaJwRFp9IA3C8ZpTYlTGIIepoAOR-AFYIGcUHgtTQ2HwxGMPms6oAX2Q1UKkFAXlmOAAZFrQABCTULTgQg5s8lQzgIdWMLDwUCCnnCkFgiGSuHuGVePmGxbLRiwWiuWB4olYYnwQoU8ndHAwNGrYXk2DkzjMLB81KpeXhJUvKjffKgJYYTQ+Fa4YKgQoraQ5dIETKk6r5xiF3zqS5DViaewK7MqtUazBYWBq4kECegPmwCjUFAZklm5yq9XmKkttbMGiJCdEPn8IRoBdNsnONwoZicUZr4vIwQYLNL0BK0-Lwea02v8IrjUxo0Q-VJz5dxYGhY8nyOYAN0Df5JlwGNNE1QVJl-eZfRQR8v0g9tBE7LBWCpQxNAwWCsHgnovEiaI4gSTgfEzfssJwvCCLQTRamoho6PMTCsIVUAsAmHATy-Ziu0InZbSCIFKLqGjTHo3isNAMT8KpNiiA4+paPoxjTxfV9+MEyZF2U1SCKIogqO0hSeL0slzPU9i5K43SnwMxUBKE0zX0cyyq3s5xHI0lT7I88Jz0va8-BYxi+zzAtaEgdCgXMTwNCIHCaXvO8H0YyKr1eFKw3SgBtAAGABdddEtTbduF3KcD2EPlQAAfiK401FS9KVlK5KupQHq-Eq7MFVCPsgA).

Also `Array.isArray(arr)` is nicer than `arr.constructor === 'Array'`.

**Comment by richbai90** [comment]
That did it. Thanks for the help. One question though, is it better to use an object literal or an Object wrapper? I read somewhere that since Object is a superclass of many javascript types, it could reference pretty much anything. I don't know if that's the case or not though.
