### ISSUE TITLE
toLocaleString has incorrect arity

### ISSUE THREAD

**Issue by idris** [facebook/flow#4036]
`(123).toLocaleString([], { maximumSignificantDigits: 3 });` should not throw an error.  In fact it appears here in the Flow docs: https://flow.org/en/docs/types/unions/#toc-unions-refinements

Currently (even in the docs!) Flow throws an `unused function argument` error if you pass any parameters to `toLocaleString`.

**Comment by leviroth** [comment]
I'd like to give this a shot.

**Comment by zaggy** [comment]
This is actually a nasty bug. Is there any workarounds?
