### ISSUE TITLE
Flow complains about undefined within an "if" that guards against just that

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4040]
Flow 0.46 (Windows)

Two issues in one: 

1) The complaint about `undefined` inside an `if` statement that guards against just that

2) That this error only occurs when some other completely unrelated element inside the same string exists (function `fn1`: error, function `fn2`: no error)

```javascript
// @flow
'use strict';

type MyRule = {|
    jsType?: string
|};

const fn1 = function (rule: MyRule): void {
    const jsTypeStrings = ['string', 'boolean', 'number', 'object'];

    if (rule.jsType !== undefined) {
        throw new TypeError(
            `Must be ${jsTypeStrings.toString()} but is ${rule.jsType}`
        );
    }
};

const fn2 = function (rule: MyRule): void {
    if (rule.jsType !== undefined) {
        throw new TypeError(
            `Is ${rule.jsType}`
        );
    }
};
```

Leads to an error inside `fn1` but not inside `fn2`

```
$ flow check
src/test.js:13
13: `Must be ${jsTypeStrings.toString()} but is ${rule.jsType}`
                                                  ^^^^^^^^^^^ undefined. This type cannot be coerced to
13: `Must be ${jsTypeStrings.toString()} but is ${rule.jsType}`
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string

Found 1 error
```

<br>

[**Link to demo**](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxiVo1ByAVwGcBTMIgFwCcBLAYwrwG50KBPABzIFk2AlAjDIBeMAG8APqjAywAKyIAVTiQD8ALnLUaAOwDmqCQF8WqOnB2UwUHQEYwoqAR0MaFsAAoqgkpt4ChAEpNADc4GgATcWlZc0sKeSUVAGVtfSIHMABtPEpafTwAGjA8ACM4OCEAQx0ikp0CAFtSkio6vDhSuRIGPABdU1kwGihPbyEAOgVlLjAAQmFRZwiSKF0SCMDooaGKAAsqRDAdEiQZkgBRKkOqDxidnYADbmIElrAAEjFplLS9IgmFDgqXyeg8gSMYFKBASNAyX3GJCmSS4Rke9x2gRYQyMqBM6DiVhsACZMk4XBQ3Doxj4-PwfMEwGFIttZCMaZMfrMFksdCs1idNqyHvtDkgTmcVFcbncHg9HgBJeFiRHI85ojFDLEY3H4oA)

<br>

**EDIT:**

When I use a modified `fn1` I find that anything that does a string-conversion somewhere else in the string triggers the error, for example

```javascript
const fn1 = function (rule: MyRule): void {
    if (rule.jsType !== undefined) {
        throw new TypeError(
            `Must be ${String('string')} but is ${rule.jsType}`
        );
    }
};
```

shows the error too but

```javascript
const fn1 = function (rule: MyRule): void {
    if (rule.jsType !== undefined) {
        throw new TypeError(
            `Must be ${'string'} but is ${rule.jsType}`
        );
    }
};
```

does not.

**Comment by madbence** [comment]
the problem is that type refinements are very brittle, ie. they are invalidated if you call another function (in your case `jsTypeStrings.toString()`). the workaround is to store the refined value in a const variable:

```js
const fn1 = function (rule: MyRule): void {
    const jsTypeStrings = ['string', 'boolean', 'number', 'object'];

    if (rule.jsType !== undefined) {
      	const type = rule.jsType;
        throw new TypeError(
            `Must be ${jsTypeStrings.toString()} but is ${type}`
        );
    }
};
```

[Type refinements in the docs](https://flow.org/en/docs/lang/refinements/)
