### ISSUE TITLE
is it possible to destructure types to create new types?

### ISSUE THREAD

**Issue by zhirzh** [facebook/flow#4044]
If I have 2 types as shown, is there a better way to declare them, instead of re-writing `Foo` structure in `FooBar`?

```
type Foo = {
  a: string,
  b: string,
};

type FooBar = {
  a: string,
  b: string,

  c: string,
};
```

Something like:

```
type Foo = {
  a: string,
  b: string,
};

type FooBar = {
  ...Foo,

  c: string,
};
```

**Comment by Connormiha** [comment]
@zhirzh 
```js
type Foo = {
  a: string,
  b: string,
};

type FooBar = {
  c: string,
} & Foo;
```

**Comment by niieani** [comment]
@zhirzh yes, your 2nd example is valid Flow. You might want to make `Foo` a strict type though so it behaves as you thought it would.

**Comment by madbence** [comment]
@niieani if you mean that `Foo` should be `$Exact<Foo>` (ie. `{| ... |}`), that's not going to work, since `FooBar` will be the bottom type (called `empty` in flow), because there's no object that only has `a` and `b` but also has `c`. [try flow](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPgKClAhgLigGdgAnASwDsBzAGmygCNCSKb70BfAbk01EiwEAIVylkaBgGMWZKnUycoAMiFxemABSo8hAOS49tJvsZGoMqHql6onQvDijSASiA)

**Comment by zhirzh** [comment]
@niieani I was asking for destructuring flow types, not JS objects that use those types. The example you show does the latter.
@Connormiha got it right.

here's what I mean

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeiooAhgFwDOKATgJYB2A5gDQWgBG9TNl0QBfANzJ02PAQBCVRgEZiZHgDoN+WN0o8AxjVAMWHbuMmYcW+YwBMKraABkZUAaOCOoc4j2xWDKAAHobWCsokpOZ+ASigaKFyCvaR5kA)

notice that `type FooBar1` only checks for missing property `c`. But `type FooBar2` checks for property `c` **and** all the properties of `type Foo`.

**Comment by niieani** [comment]
@zhirzh this is what I answered too, destructuring, not JS object. @Connormiha's example is not destructuring, but an intersection, which behaves differently.

See `FooBar1` in [this example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeiooAhgFwDOKATgJYB2A5gDQWgBG9TNl0QBfANzJ02PAQBCVRgEZiZHgDoNAEgCiADyoBjFAB58sAHzdKBmqAYsO3ccgOxWDULttn5SlaWcgA) works exactly as you wanted it to, with missing properties: `a`, `b` and `c`.
