### ISSUE TITLE
Flow ignores attribute overwritten with the spread operator (example included)

### ISSUE THREAD

**Issue by debrice** [facebook/flow#4045]
It seems that when the spread operator is being used to extend a value, flow somewhat can't identify the presence of a sub-attribute.

[Problem is reproduced here on the flow try page](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhgHZYBiccARsQE5gC8YA3qmGFNXfQFxsOnMADdiMAK54AzgICC9esSwAeaRnoBLUgHMAfEIC+qQwG502fGADypPFVoNmgzt0f8XwsZLwD1W3SMTc1RgYDAAVWkZMAwACwJ4HU0AYzA4KDAAWzJKHgZCPHi4ABMwGixQ8JwYYhTtHTBNDGkwaQaYAgYdCSy8UgwmgbgwMlHFZVQoCVIUjE04UnS7B15C4pKAChwGYiyBW3t8+gBKTxTF9TAdpSyqehJyZ3ZhMAA6D5u9gBohV2OBC9XqJxFJZGAANpfLJvNy8N7eKQAXT+YGMnDMQnoRQk9CWOXIqwKRTipW2uzucAeuRO5mMUxmcwW+NyRIeJLJ0IEjzy7jOQOxGFxS2hsOOCNBMjenV08Tp6EWR3c61JW1YXABbBBPgEACIMDIMLq0WjaagCby1hy1Rr3IDtWCBBD9YbdUiTYZaUA)

```js
/* @flow */

type ManyFoobar = {
  foobar: {
    values: Array<string>
  }
};

type OneFoobar = {
  foobar: {
    value: string
  }
};

// Uses the logic of manyFoobarMethod by
// placing its single argument into an array
function oneFoobarMethod(param: OneFoobar) {
  const paramForMany = {
    ...param,
    foobar: {
      values: [param.foobar.value]
    }
  };
  return manyFoobarMethod(paramForMany);
}

function manyFoobarMethod(param: ManyFoobar) {
  return param.foobar.values.length;
}

oneFoobarMethod({ foobar: { value: "test" } });
manyFoobarMethod({ foobar: { values: ["test"] } });
```

triggers this error:

```
4:   foobar: {
             ^ property `values`. Property not found in
10:   foobar: {
              ^ object type
```

**Comment by agentcooper** [comment]
Possible workaround:

```js
function oneFoobarMethod(param: OneFoobar) {
  const { foobar, ...rest } = param;

  const paramForMany: ManyFoobar = {
    ...rest,
    foobar: {
      values: [param.foobar.value],
    },
  };

  return manyFoobarMethod(paramForMany);
}

```

**Comment by debrice** [comment]
@agentcooper it seems indeed that while your technique yields the same result, flow is inferring the value differently and does not error out. Hopefully this gives more insight about the bug.

**Comment by villesau** [comment]
This fixes the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
