### ISSUE TITLE
Flow taking all the memory

### ISSUE THREAD

**Issue by leofle** [facebook/flow#4046]
I'm using Atom 1.17.1 for windows and Flow 0.41.0
![flow](https://cloud.githubusercontent.com/assets/2674606/26526480/41219a74-4385-11e7-87d3-57ea14e413e7.PNG)

on the bottom of Atom i can see a loader saying: "Flow server initializing..." but never goes away.
someone ?

**Comment by lll000111** [comment]
What about newer Flow versions (0.47 is current)? What about some context, like the size of your project (files, LoC)? How does the disk activity look like (using the "Resource Monitor"), what is it writing/reading?

**Comment by awestroke** [comment]
I have the same problem, running Windows 10 and Flow 0.47.0

**Comment by barbalex** [comment]
This seems to be rather prominent in the issues. Maybe related issues found after a five minute search:

- https://github.com/facebook/flow/issues/5271
- https://github.com/facebook/flow/issues/4370
- https://github.com/facebook/flow/issues/4070
- https://github.com/facebook/flow/issues/4046
- https://github.com/facebook/flow/issues/3565
- https://github.com/facebook/flow/issues/3370
- https://github.com/facebook/flow/issues/2152

**Comment by JofArnold** [comment]
See my comment here for one way of preventing this: https://github.com/facebook/flow/issues/2152#issuecomment-366221060

**Comment by mrkev** [comment]
Closing since there's other issues discussing this in greater detail. This should probably continue on #2152.
