### ISSUE TITLE
Bug: unable to refine tuples of different arity

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/flow#4050]
I would expect the following to work:

```ts
// @flow

type ImportantThing = string;
type SomeTuple = [ImportantThing];
type OtherTuple = [*, ImportantThing, *];

function getImportantThing (args: SomeTuple | OtherTuple) {
	return args[1] ? args[1] : args[0];
}
```

but instead I get:

```
8: 	return args[1] ? args[1] : args[0];
           ^ access of computed property/element. Out of bound access. This tuple has 1 elements and you tried to access index 1 of
8: 	return args[1] ? args[1] : args[0];
           ^ tuple type
```

I've been unable to find a way to refine tuples of different arity. (Hope I'm not missing something obvious.)

**Comment by lll000111** [comment]
[Link to a demo, even more stripped down to the essentials.](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZVgLZYAqArhtDgLygDaAzigE4CWAdgOYC6A3KpjgDyKABZYmZCtTqNWnADShZ7bn0SRSbAMYoWsNqA5YUASQIZYTFAEM2KYiJWgAFNaYd6ALjyES5SqAAPqDCYhL+WACU3gBGsLCUtqAA3ogAkEzGpEwG6NiwkKBuHrQAjFygVFWgAOSaACZYkOxY9TV8AL6IQA)

**Comment by mike-marcacci** [comment]
Ah yes, thanks for that catch on the example! You're right about trying both the `.length` and `typeof` strategies, which also failed for me.

**Comment by popham** [comment]
Your attempted refinement on `args[1]` must always fail because `""` is falsy versus `"a"` which is truthy.

**Comment by mike-marcacci** [comment]
@popham I do see how that could be the case, but look it @lll000111's example which uses `typeof` and still holds true.

**Comment by popham** [comment]
Out of bounds access on tuples is an error, so that will not type check either. I imagine the idiom will be refinement on length:

```js
type SomeTuple = [string];
type OtherTuple = [string, string];

function getImportantThing (args: SomeTuple | OtherTuple): string {
  return args.length === 0 ? args[0] : args[1];
}
```

**Comment by mike-marcacci** [comment]
Yes, we've tried that too :-/ (see above). [Here's your suggestion in the playground.](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZVgLZYAqArhtDgLygDaAzigE4CWAdgOYC6A3KpjgDyKABZYmZCtTqNWnADShZ7bn0SRSbAMYoWsNqA5YUASQIZYTFAEM2KYiJWgAFNaYd6ALjyES5SqAAPqDCYhL+WACU3sqcoADeiKCgTMakTAZuHgB0lJyioFRFoAAMoAD8oFn0tCVcoN7VtACMvIgAvkA)

I would be OK using any of the above strategies, but there appears to be a more fundamental bug at the moment. For now I'm just casting everything through `any` wherever I encounter this bug to avoid the error, but that's not much of a long term solution.

**Comment by ryanscottaudio** [comment]
has there been any activity on this? seems like it hasn't been marked as a bug

**Comment by anru** [comment]
related to #4556

**Comment by gkz** [comment]
For tuples of different arity you can refine using a `.length` check: 
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZVgLZYAqArhtDgLygDaAzigE4CWAdgOYC6A3KpjgDyKABZYmZCtTptSBAEbiANKHmxYlAIZteySKTYBjFC1htQHLCgCSBDLCYptKYiPYdQACk1MO9AFx4hCTklKAAPqDCYhKhWACUgQBusCwAJqAA3ogAkCyQXj5+AHSUnKKgVFWgAIzxWYigTc1N3r70tAAMXIGMrJzxuQC+oFjQ9DjZOTltfl09oLIK4vF807MdNQtqGljagzlDiEdAA
