### ISSUE TITLE
bug in Object.entries

### ISSUE THREAD

**Issue by toxic-johann** [facebook/flow#4052]
[reproduce link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYBAzgPIBGAVgKb5gAUctAXGAIZYCeAlBypw4MOtzABSHAAsGAazJgA3qjBhgwUrk5k6YOFC4AnI4jCZchYlywATY0c49VYI3TwYjJPDwAOdA31aMABeMLAAclZ6fAiwADJ4lzVqGLwWWj5Q8OiEpLU1AGU8IwIsAHMMmiywkMiAbWiGPDBU5oBdOMTksABCH39A3N7wiIt8Iiwu-ILegEETJwA6cgXHHiq+AG5UAF9UdGwJ6zw6MjwARmYAN04YLJU1Aigmcjb8Jlv7h56cYjIRHQlvBKl8luV3AAaMBg3R4Pgufb7Q6WSZgU7nZjRDjveHKFy4pZ0LAlAhnTYuJZQOBGACinBkTCY9TkdB40K+7RqAD58QVSC83rRmp87nwfvy1H8sADRMC4KC7uCoTClXCEfz9mpdgjdkA)

It seems if i run Object.entries, some type check will be lost.

In code below
```
/* @flow */
function isObject (obj: any): boolean %checks {
  // incase of arrow function and array
  return typeof obj === 'object' &&
    Object(obj) === obj &&
    String(obj) === '[object Object]' &&
    !typeof obj !== 'function' &&
    !Array.isArray(obj);
}

function test1 (val) {
  if(isObject(val)) {
    console.log(val.get, val.set)
  }
}

function test (obj: Object) {
  Object.entries(obj)
  .forEach(([key, val]) => {
    if(isObject(val)) {
      console.log(val.get, val.set)
    }
  })
}
```

the test Function will throw error

```
21:       console.log(val.get, val.set)
                          ^ property `get`. Property cannot be accessed on possibly null value
21:       console.log(val.get, val.set)
                      ^ null
```

**Comment by vkurchatkin** [comment]
Just check that obj is not `null` explicitly.

**Comment by toxic-johann** [comment]
@vkurchatkin of course it can be fixed in this way. But that's strange, isObject has already checked the `null`, and it run well in test1. That seems not a good idea to check again and again.

**Comment by vkurchatkin** [comment]
@toxic-johann well, it doesn't really check that. It checks `String(obj)`, but this is not supported

**Comment by toxic-johann** [comment]
@vkurchatkin ok, thanks~
