### ISSUE TITLE
Allow to override args in inherited methods by `string enum` for `string` type

### ISSUE THREAD

**Issue by nodkz** [facebook/flow#4054]
I have `UserApi` which extends `fbemitter` which accepts any string as `eventType` for `emit` and `addListener` methods. In my class, I want to restrict `string` by fixed enum set of strings, eg `'login' | 'logout'`. 

Live example below provide such errors:
```
8:     addListener(eventType: string, listener: Function, context?: any): EventSubscription;
                              ^ string. This type is incompatible with the expected param type of
40:   addListener(eventType: EventTypes, listener: Function, context?: any): EventSubscription {
                             ^ string enum

13:     emit(eventType: string, ...data: any[]): void;
                        ^ string. This type is incompatible with the expected param type of
37:   emit(eventType: EventTypes, ...data: any[]): void {
                      ^ string enum
```

[Try live following code](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwKIDcQDsAuAygK4BGyYMAlgA56UD2O8A3gFDwfwSXJ64gwAXPABiRHGDqMA3O05hGfAB55hUHAE9ZneHAC29bAAoAlMMz1KwWQF9WrUEjiJoqDNnzo9lPHxgs5DihgYAAZHj4cASMQDzwAFQ1qEGFeKhwAcwAaLgj+IVFxSQYcHIV8EBUAfjVNM3dcQlJyKloS7U5GMBAYuMTk1Lx07NzefOExCSlSxEVKvBr4dQ16rEbiMgoaaY6OfUMQAEEICHCxqJhkXsb+kEW0ykz6iytd3RADbABhIhg4fDOkWiz0s1kCoyBl2u+Fug2G9UmxUYAG0ALpvD4+aEJJIpeAPTI5AB0JOAUDwUFqGjRINerDsDnA0GcBmARAgCAA5AAzEiY3wCTkBDiOZkIVnskBEyrUegwPDIYRsHRrTzeAUFPC4+jchpqnx+LJyGy2ewAejN8AAJCIIPQAO4iShKACyeKgGX8yCI1GocFQJVmej0jXgwHoIDQOHoeHg9rlAGtWBb4JQ9LL5Sw9XgvAaBPAbPBuTB6Hp4Dy+eq-JyOqwZXLY1rktnbmgALzlu0ZR5CgA+nfoGXoRDwNfs9czoG5UHZsaQbgAqsgBIdqJR4PNcMA0Kqc1X88quIPHqZhZwUySichSwgFKBwXgABY8aXqoycrs9kzSeAp+hJnQnxffl30-HAACZOW-X9LXQJRkkkEBgA3P45WNOQ5BTAA1SgoCDEN8CWHBowpaY0CGDR4Dweh4D0KAEwQAkMio3FaLlRihkoRCYAwjgzQAKngQRBDkEDYhuXFhF3VtiVJclKSI6lUVpZDDz2EA8F+JhvWSGBXyxcSYVxWSiTJClv2NDpgjCPILmxWEW1xZAcm4c4BAmIppjKOZqipVY4g2FptkDNT3k0mBtJ9AQiWswF8ns4yIXybyKhUCyOBNOR+LNekgA)
```js
declare class EventSubscription {
    listener: Function;
    context: any;
    remove(): void;
}

declare class EventEmitter {
    addListener(eventType: string, listener: Function, context?: any): EventSubscription;
    once(eventType: string, listener: Function, context?: any): EventSubscription;
    removeAllListeners(eventType?: string): void;
    removeCurrentListener(): void;
    listeners(eventType: string): Function[];
    emit(eventType: string, ...data: any[]): void;
}

declare module 'fbemitter' {
  declare module.exports: {
    EventEmitter: typeof EventEmitter,
  };
}

// $FlowFixMe: agr suppression comment does not work
// import { EventEmitter } from 'fbemitter';
  
export type EventTypes = 'login' | 'logout';

export default class UserApi extends EventEmitter {
  login() {
    // ...some code
    this.emit('login'); // ok
    this.emit('login2'); // Expected error
  }
  
  // Via comment annotations try to make string type more stricter
  
  /* ::
  emit(eventType: EventTypes, ...data: any[]): void {
    return super.emit(eventType, ...data);
  };
  addListener(eventType: EventTypes, listener: Function, context?: any): EventSubscription {
    return super.addListener(eventType, listener, context);
  };
  */
}
```

How can it be done? Thanks In advice.

**Comment by lll000111** [comment]
>  In my class, I want to restrict string by fixed enum set of strings, eg 'login' | 'logout'.

I have a very similar use case!

I have a disjoint union of objects which have a `type` property (string) in common which is the type-property for the union. The set of types inside my library (the project) is limited, but apps using the library can add their own.

I tell my functions to accept that disjoint union as input and use a generic parameter for the concrete type. **Problem:** I don't know what types applications are going to add so I can't write them into my disjoint union type!

If instead of the disjoint union I use a generic object type with only a general `type` string property I lose the type checks: Inside my library code the exact type matters for a lot of paths

My hack/workaround/"solution":

I put those types that need to be extended by the app using my library into a library definition file instead of into my source code. Then I tell the app developers to copy that file into their own `f./flow-typed/`  folder and extend it.

The clean solution would be to have extensible types, for example an app could add its own types to the disjoint union type I created.

**Comment by vkurchatkin** [comment]
This doesn't make sense from type system's point of view. Since subclass is as subtype of the parent class, methods of the subclass should be subtypes of the methods of the parent class.

**Comment by LoganBarnett** [comment]
@lll000111 We did a similar thing for this for a generalized async helper in Redux. We needed to include multiple sources to compose all of the app's action types. Using a little bit of polymorphic types did the trick: [flow.org/try](https://flow.org/try/#0C4TwDgpgBAsiCqA7Alge0QHgCoD4oF4AoKKAHygHIAzVVC4sygIwEMAnek8rQw0SKAFEAHsAhtELADZI0iAg3IVWAL06MKARwCuw+n3DQAgmDCz0BWAhToMIsROnnEOBoQDG6AM7AoLS9S09J6IPlBMATp6vFTaiO7AclAAJqhGWAAWyIgA5gAULABcUCZmNogAlMWI2gC2TOJQAN4MXgDuyMDuGQUVzQwAkO4sXtCBdIUMJCRsEMDaElAADFNQw6PM7BST09Oz84sAjKvrY6rbqzNzC-IATIQA9A9QAEoQOsizyZRRFFBUbFQtSgwAy0AgiESsygcTkADpHs8kJ5arUIb4WIhvqDoPxoN0IO4ANZQMAjUZeBFPXanH66C7U3ZQfY3KAAZlWyQgVBY2ikwB2TIKxQgtTAoAqlxBGUBbSgiAgcsEbEBbDyFDisxY3RYTCkEAokpIAF9CMagA)

``` javascript
type MyUnion<T> =
  | 'foo'
  | 'bar'
  | T

type ExternalUnion =
  | 'baz'
  | 'qux'

type AppUnion = MyUnion<ExternalUnion>
  
const a = 'foo'
const b = 'qux'

function doAThing(a: AppUnion): number {
  switch(a) {
  	case 'foo':
      return 0
    case 'bar':
      return 1
    case 'baz':
      return 2
// Required 'qux' from the entire union.
// Uncomment and the type check passes.
//    case 'qux':
//      return 3
    default:
      (a: empty)
      throw new Error('unreachable')
  }
}
```

**Comment by lll000111** [comment]
@LoganBarnett Yes, that is exactly what I ended up doing too.

**Comment by LoganBarnett** [comment]
@nodkz In the try link you provided (running v0.60.1), this seems to give you the error you wanted with `emit('login2')`, but the original errors you posted are still there. I don't know that Flow _should_ permit what you have. The changes you have break the `EventEmitter` interface, so `UserApi` can no longer be considered an `EventEmitter`. Does that make sense?

**Comment by nodkz** [comment]
I just want to make `string` type stricter via `enum string`. I don't feel that it breaks `EventEmitter` interface. Parent class just restrict acceptable values for `emit` and `addListener`.

It may work almost like `$ReadOnlyArray` is a superclass for `Array`.  `enum string` as a superclass for `string`... Maybe I'm wrong.

Anyway, there are several ways to solve this problem:
1. Change declarations for `EventEmitter`, add generic `EventEmitter<T =string>`
2. Add new methods with type restriction, eg. `emitEvent`, `listenEvent`.

**Comment by SamChou19815** [comment]
This is not safe due to variance, so Flow's behavior is right here.
