### ISSUE TITLE
How to add methods to the flow-typed definition of a module

### ISSUE THREAD

**Issue by doberkofler** [facebook/flow#4055]
I'm using the flow-typed definition file for jQuery but need to add the definitions for certain jQuery plugins and see no way on how to do this ?

More generally speaking, let's say an npm module has an external flow-typed definition file that looks something like this:

```
declare class LibStatic {
  func1(): string;
}

declare module 'lib' {
  declare var exports: LibStatic;
}
```

declare var globalLib: LibStatic;
How would I customize the external flow-typed definition file, if a new method func2 needs is dynamically added to LibStatic ?

**Comment by aleclarson** [comment]
Not currently possible, I think.

Here's my proposal: #5364

The solution *would* be:

```js
const lib = require('lib')

extend typeof lib {
  func2(): string {
    // ...
  }
}
```

**Comment by doberkofler** [comment]
@aleclarson I personally would prefer what typescript refers to as _merging_.
https://www.typescriptlang.org/docs/handbook/declaration-merging.html
