### ISSUE TITLE
Provide way to use flow with jsx-control-statements plugin

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#4057]
There is a popular repo - https://github.com/AlexGilleran/jsx-control-statements

This lib gives possibility to write jsx like this:

```jsx
<If condition={foo}>
   {foo.bar}
</If>
```

But if foo is nullable, flow can't understand that there's a check. Can I declare such checks somehow on project or `jsx-control-statements` level?

**Comment by gajus** [comment]
I think what you are looking for is covered in this issue https://github.com/facebook/flow/issues/34

**Comment by apsavin** [comment]
Oh, thanks, sorry fo a duplicate

**Comment by apsavin** [comment]
We can't use predicate types to handle described case, because `jsx-control-statements` changes semantic of JSX and introduces custom control flow.

@vkurchatkin said:

> The only thing that Flow can do to make this work is support custom source preprocessing

And there's some idea from @AriaMinaei 

> Having flow consume an [ESTree-compatible AST](https://github.com/facebook/flow/issues/1515#issuecomment-290905838)  would open up that possibility, and much more.

**Comment by vkurchatkin** [comment]
This issue is too specific, let's continue this discussion in https://github.com/facebook/flow/issues/1515
