### ISSUE TITLE
Missing callback in ReactDOM render() method

### ISSUE THREAD

**Issue by kuuup-at-work** [facebook/flow#4060]
See https://facebook.github.io/react/docs/react-dom.html#render for the api of `ReactDOM.render`: You can pass an optional callback to `render` but this argument is missing in flow declarations. Since 0.47 flow gives you an error about `render` not expecting more than 2 arguments.

**Comment by pastak** [comment]
I just faced same problem too.

**Comment by claudiopro** [comment]
Hey @pastak sorry for overlapping 😇

**Comment by kuuup-at-work** [comment]
Why can't I find these changes in 0.48.0?
