### ISSUE TITLE
How are you supposed to use Object Unions?

### ISSUE THREAD

**Issue by rossPatton** [facebook/flow#4067]
I have 2 data structures. One that represents birth control methods, and another that represents typical drugs. The details don't really matter, but both data structures are similar but differ in a few distinct ways

Both of these data structures are used to render content via generic react components that for legacy reasons take either data type and just render slightly different content depending on the structure

Because this is a common case, I created a type that looks like this:

```
type exampleMethod = {|
  name: 'name';
  ...otherValues
|}

type exampleDrug = {|
  name: 'name';
  ...otherValues
|}

type unionType = exampleMethod | exampleDrug;
```

Now, attempting to actually use this predictably blows up my flow error log. My issue, is that even when I check at every case for values that are unique to one exact `Object` or the other, flow doesn't seem to understand. It always checks for consistency across both objects, which seems completely counter to the point of a union here. So I had an idea to create some simple flags to tell the objects apart:

```
type exampleMethod = {|
  name: 'name';
  isDrug: false;
  isMethod: true;
  ...otherValues
|}

type exampleDrug = {|
  name: 'name';
  isDrug: false;
  isMethod: false;
  ...otherValues
|}

type unionType = exampleMethod | exampleDrug;
```

I added both flags to both types because flow complains about non-existent properties when I don't, even if all i'm doing is de-structuring before I do a typeof check

A rendering example:

```
treatments.map((treatment: tUnionType, i) => {
  const {isMethod} = treatment;
  if (isMethod) {
    return <span />;
  }

  return <span />;
});
```

That's a really bare example, but in this case I could expect that flow would understand that by checking for a truthy `isMethod` I am narrowing down the union to just `exampleDrug`, but this is not the case. When I do this, I get the `inconsistent use of library definitions` error. This is because it complains about there being a potentially falsy state to `isMethod` (which conflicts with one of the unions)

I know that my types here are getting complicated, but unfortunately the data is complicated. I would really like this to work, because in many places I am just resorting to clobbering the types with primitives like `Object` because using unions for anything more than strings or numbers seems like an exercise in futility

In the more specific components that take one object type or the other, everything works great and flow is very useful. The second it gets more complicated (and admittedly, I could split things up, but at this point that would entail redoing a large part of the codebase), flow seems to be more trouble than it's worth

Am I just doing it wrong?

**Comment by barbu110** [comment]
Hello!
Take this example:

```js
type Person = {
  name: string,
};
function sayMyName(p: Person): string {
  return p.name;
}

sayMyName({
  name: 'Victor'.
  country: 'Something',
}); // works
```

Now if you will change this type to be exact, like this
```js
type Person = {|
  name: string,
|};
function sayMyName(p: Person): string {
  return p.name;
}

sayMyName({
  name: 'Victor'.
  country: 'Something',
}); // doesn't work, because 'country' is not a property of Person.
```
You can read about exact object types [here](https://flow.org/en/docs/types/objects/#toc-exact-object-types).

Now about unions. An object union type will be deduced by some given props that are distinct. So take this example from the [docs](https://flow.org/en/docs/types/unions/#toc-disjoint-unions-with-exact-types) and you will get it, I believe.
```js
type Success = { success: true, value: boolean };
type Failed  = { error: true, message: string };

function handleResponse(response:  Success | Failed) {
  if (response.success) {
    // $ExpectError
    var value: boolean = response.value; // Error!
  }
}
```

This statement from the docs linked above should help you:

 > Disjoint unions require you to use a single property to distinguish each object type. You cannot distinguish two different objects by different properties.

Hope this helps

**Comment by rossPatton** [comment]
I've read those docs thoroughly and i'm doing exactly as described. I just attempted to narrow down to just one flag (isMethod), but that does not work either. I use exact types in a lot of places, it's just when they're used together as a Union type does it cause problems

here is an example

```
const {isMethod, name} = this.props.data;

    let nameForRender = name;
    if (isMethod) {
      nameForRender = data.nameFriendly;
    } else {
      nameForRender = data.nameCombined;
    }
```

`nameFriendly` is a key specific to methods, and `nameCombined` is a key specific to drugs. `isMethod` is always true on methods, and always false on drugs. Why does this extremely simple example fail? It makes no sense to me

The difficulty in using this feature is tempting to go back to what we were doing before - just clobbering everything with `Object` to save our sanity, which is obviously not desirable

**Comment by TiddoLangerak** [comment]
I think what you're running into is that flow only refines when you access the property directly on the object, but not when you first re-assign it to a different variable:

```js
type A = {
  type : 'A',
  a : number
};
type B = {
  type : 'B',
  b : number
};
type AB = A | B;

function valid(ab : AB) {
  if (ab.type === 'A') {
    const x : number = ab.a;
  } else {
    const x : number = ab.b;
  }
}

function invalid(ab: AB) {
  const type = ab.type;
  if (type === 'A') {
    // $ExpectError
    const x : number = ab.a;
  } else {
    // $ExpectError
    const x : number = ab.b;
  }
}
```

So in your first example, try this instead:

```js
treatments.map((treatment: tUnionType, i) => {
  if (treatment.isMethod) {
    return <span />;
  }

  return <span />;
});
```

**Comment by Mathspy** [comment]
There are three possibilities here:
- This issue is due to what Tiddo explained above and there's nothing actionable here
- This issue is indeed somehow related to https://github.com/facebook/flow/issues/7912 in which case we can continue tracking it there and close this as duplicate
- This is an unrelated and maybe unresolved issue but there's no minimal example or a repo link as well as being from 2017 (so most likely irrelevant to author)

In all of those cases I think it'd be safe to close it
@goodmind
