### ISSUE TITLE
typeof-like thing for functions, but change return-type to void

### ISSUE THREAD

**Issue by gabor** [facebook/flow#4074]
hi,

if i use `typeof` on a function, then it copies both the function-arguments-types and the return-type. is there a way to only copy the function-arguments-types, but make the return-type `void`?

example:

```
function a(x:string, y:number):number { ... }

type B = magicmagic a;
// at this point B is (string,number)=>void
```

the reason is Redux. it wraps functions and the wrapped-function has the same arguments as the original function, but the return-type gets changed to void.

**Comment by madbence** [comment]
i'm not sure how to do it with arbitrary number of params, but here's a somewhat buggy version:

```js
type _VoidRet2<A, B, F: (A, B) => any> = (A, B) => void;
type VoidRet2<F> = _VoidRet2<*, *, F>;

declare var action: (string, number) => string;

(((a: string, b: number) => a): VoidRet2<typeof action>);
(((a: string, b: number) => undefined): VoidRet2<typeof action>);
(((a: string, b: string) => undefined): VoidRet2<typeof action>); // should be an error
```

**Comment by wiscat** [comment]
it works, but is it recommended way?

**Comment by markusjwetzel** [comment]
@gabor Did you find a solution? I have the exact same problem with Redux.

**Comment by gabor** [comment]
@markusjwetzel no, no better solution found :( another way is to use the type of the original function and just accept that the return-type is incorrect.

**Comment by goodmind** [comment]
It's [possible](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqAIYAUAHgFygDO2ATrugOYA0oAnleqgLYBGAUzoBKLr0F1QAb1B0B2VHUIAGUAF9k2dgAcBoACQBBOk14D02agB4AYgD5QAXgMBhItGhWrhuyUhUAbRIAOlCiE2oqQ2EnByJ0dgBdGMcHQzYArV1YSGJEu00dPRsnUBCwiKojEzMLayyBHOI7FIcAN1hcABNEUFBETAJaUAALAU5QEucSIjF+ITYJ2gZmVule2XlFQgBGRDUgA)

```js
// @flow

function a(x: string, y: number): number { return 0 }

type $Arguments<F> = $Call<<A>(f: [(...args: A) => any]) => A, [typeof a]>

type F = (...args: $Arguments<typeof a>) => void
  
const hey: F = (a: number, y: string) => { // error
  return 1 // error
}
```
