### ISSUE TITLE
Property cannot be assigned on possibly undefined value

### ISSUE THREAD

**Issue by Joneser** [facebook/flow#4078]
With version 0.45.0, I am running into an issue with regards to setting a field on a nested object.
The comment below indicates where the error is occuring (cannot set 'authorization' on possibly undefined value 'params.headers')
```
function myFunction() {
return {
        request(params: Object) {
            return new Promise((resolve) => {
                params.headers = params.headers || {};
                params.headers.authorization = 'Bearer <token>'; // error here
                resolve(params);
            });
        },
    };
}
```
This error can be avoided by changing the two assignment lines inside the promise to be the following:
```
params.headers = params.headers || {};
const modifiedHeaders = params.headers;
modifiedHeaders.authorization = 'Bearer <token>';
params.headers = modifiedHeaders;
```
This should not be the case, as it doesn't change the structure of the object, it just prevents us referencing a field 3 levels deep.

**Comment by AugustinLF** [comment]
Hmmm, I cannot reproduce your error, in this example, [it does work](SRgKAd0QAFMnGQwOFXLkoc4AGwBuFQgF4AfMRLK3jfoOEA6ABYU+ABMKMg5Ee0RPIQ4-AODQxAAfROIAXwBuV3c3KJ9-IJCYvhAoXzgyGAAvPlgEcMQAcgAhAMoyRAAeKDgAawowRwb0xAB6EcQQ-Xb-SizspXMrW14BaPxM+YZU9bmlVIAaXYySVKA). Perhaps could you provide us with a https://flow.org/try/ example?

**Comment by SamChou19815** [comment]
This no longer errors.
