### ISSUE TITLE
Flow incorrectly reports possibly null value

### ISSUE THREAD

**Issue by johnryan** [facebook/flow#4082]
For some reason flow reports a value as being possibly null when referencing other functions in a class even if they are checked for null . 

See example: [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAwnDnAHantEC+YUeVmADkeCtWEBuVKkoxyAZwVgAKqQVFSADwJcAJspZtO3BqjBgFrUmSgAuMAH4AEioCyAGQCiMUpi4E0uZgAOakBABq5DAArqQAFACUDuwxmABGpHhmFhZiBDF47GAADNIWPDLAwAAiAPJeAMoAcipgAOp1xADSwXpwKgAW6OwhSTm56FBg8QTDCgB0Vv62iRO5YJQcGmCDpOghg0QAvGBz6IthkdFxSeUbZ-NL1rZLBACevgt7B0dgpwADAAk9B+hwIPAB9wqwUqqGqnR6jT6cAAguw4HMskMRmM1vRghYpjNzotljZSFB8YTclt2DswX9TmUaRZSc8VpS3p9SN99uD-mBgaD+UdIdCwJUYageEA)

**Comment by AugustinLF** [comment]
Flow is pessimistic about [refinements](https://flow.org/en/docs/lang/refinements/), which means that it considers that any function call could invalidate any previous refinement (what if `this.getValue()` would set someRef to null?.

In this case, [you can move the function call before your check](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAwnDnAHantEC+YUeVmADkeCtWEBuVKkoxyAZwVgAKqQVFSADwJcAJspZtO3BqjBgFrUmSgAuMAH4AEioCyAGQCiMUpi4E0uZgAOakBABq5DAArqQAFACUDuwxmABGpHhmFhZiBDF47GAADNIWPDLAwAAiAPJeAMoAcipgAOp1xADSwXpwKgAW6OwhSTm5FpQcGmCDpOghg0QAvGAEwwoAdGGR0XFJ5bnoUGDxG+jbVv62iROTF1fWtlsaAJ6+W-OLy2BrAAYAEno3yWBB4-yOFWClVQ1U6PUafTgAEF2HANlkhiMxnd6MELCczo9Xs9SFA8QTctN2LNQb81mUqRYSdcbOTXgQPqQvgswX8wECQXzlhCoWBKtDUDwgA).

**Comment by johnryan** [comment]
ah, fascinating...thanks for the clarification
