### ISSUE TITLE
Breaks and control flow analysis

### ISSUE THREAD

**Issue by calebmer** [facebook/flow#4088]
I would expect the following code to typecheck without error: 

```js
/* @flow */

const bool: boolean = false;

while (true) {
  let a;
  
  if (bool) {
    a = 5;
  } else {
    break;
  }
  
  numbersOnly(a);
}

function numbersOnly(n: number) {
  console.log(n);
}
```

By the time `numbersOnly(a)` is reached, `a` has been initialized. The other option is we break out of the while loop. However instead you get the error:

```
14:   numbersOnly(a);
                  ^ possibly uninitialized variable. This type is incompatible with the expected param type of
17: function numbersOnly(n: number) {
                            ^ number
```

Is this a bug, or am I missing something?

[flow.org try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMAjOOGALn0KwEMA7MAXjCgpgGdMBudBACwEsswAFNgBOAV0wBKMAG9UYMFlwUO8uWB5RBBIlNnz5FOmACsKsAF8wmFphlr5eYZgoBrM+bVqqogLZ5MwswA8lQwAJ4CFBIcHqhQolQAxtg8cDTefgHBoRFUpBn+wrpqiWnMRJgAdPAA5gJU0ajmQA)

**Comment by cakoose** [comment]
Running into something similar:

```typescript
/* @flow */

declare function read(): number;

function f(): number {
  for (;;) {
    const n = read();
    if (n === 0) return 1;
  }
}

function f(): number {
  while (true) {
    const n = read();
    if (n === 0) return 1;
  }
}
```

flow.org/try output ([link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsY-DACgEoAuMCsgWwBGWQgG505KnQakO3XoOFgA3qjCk4hMKxEj2y1WrA4GAZ2o8wAXiZYWHMYbC0oWxpfdgADHuLUyhRgBGBzAAX1Rw1AkaekYoWR5+IU0VNQQAC1oYElZqQjIsPVTDYwozC2tmNnYQtWdXKw9vGz8AsGCDcNCgA)):
```
5: function f(): number {
                 ^ number. This type is incompatible with an implicitly-returned undefined.
12: function f(): number {
                  ^ number. This type is incompatible with an implicitly-returned undefined.
```

I can add a useless `return 0` after the loop to make the error go away.  But then our ESLint setup starts complaining about dead code.

**Comment by goodmind** [comment]
Simplest example

```js
function loop(): empty {
  while (true) {}
}
```

**Comment by mjwach** [comment]
Here are some more simple test cases in which Flow oddly fails to understand that a variable has very obviously been initialized:

```JavaScript
    /* @flow */
    
    {
      let x;
      x = 3;
      let y = x + 4;
    }
    
    {
      let x;
      if (true)
        x = 3;
      let y = x + 4; // flow thinks x may be uninitialized :(
    }
    
    {
      let x;
      let z = 0;
      while (true)
      {
        x = 3;
        ++z;
        if (z > 2) break;
      }
      let y = x + 4; // flow thinks x may be uninitialized :(
    }
    
    {
      let x;
      for (let z = 0; true; ++z)
      {
        x = 3;
        if (z > 2) break;
      }
      let y = x + 4; // flow thinks x may be uninitialized :(
    }
    
    {
      let x;
      let z = 7;
      if (typeof z === "number")
        x = 3;
      let y = x + 4; // flow thinks x may be uninitialized :(
    }
    
    {
      let x;
      let z = 6 + 7;
      if (z > 8)
        x = 3;
      let y = x + 4; // flow thinks x may be uninitialized :(
    }

**Comment by cakoose** [comment]
@mjwatch: The examples you've listed are a little different.  They're data-dependent in a way that Flow (and most static type systems) don't attempt to handle.  Would recommend filing as a separate bug.

**Comment by mjwach** [comment]
I don't see any significant dependence on runtime values except in my last example (z = 6 + 7 followed by z > 8).  That one, yes, I don't really expect Flow to handle.  It's just there in case somebody felt ambitious.

The while(true) and for(...; true; ...) examples are the really important ones.  I expect Flow to be smart enough to understand that the value "true" is always true.

**Comment by cakoose** [comment]
Yeah, the infinite loop examples are very similar to the original issue report.

`if (true)` feels like more of a stretch, and the last two examples require a type of analysis that I don't think Flow will even attempt to perform.  They're different enough that I think a separate issue makes more sense.

**Comment by SamChou19815** [comment]
This now works.
