### ISSUE TITLE
Feature request: add the empty set

### ISSUE THREAD

**Issue by danwang** [facebook/flow#4089]
It'd be nice to have a type like `nothing` that represents the empty set.

For example, for all types `A`:
- `A | nothing` is the same as `A`
- `A & nothing` is the same as `nothing`

This is useful for defining things like `none: Option<nothing>` or `nil: List<nothing>` if `Option` / `List` are covariant

**Comment by samwgoldman** [comment]
`empty`

**Comment by danwang** [comment]
Thanks!
