### ISSUE TITLE
Error message lost across modules

### ISSUE THREAD

**Issue by danvk** [facebook/flow#409]
This code:

```javascript
/** @flow */
// test.js
function foo() {
  var u8 = new Uint8Array([0, 1]);
  other(u8.buffer, 0);  // XXX passing ArrayBuffer, not Uint8Array
}

function other(u8: Uint8Array, offset: number): number {
  return u8[offset];
}
```

produces a useful error message and a non-useful error message:

```
/Users/danvk/code/toy-flow/test.js: inconsistent use of library definitions
  /.../lib/core.js:365:13,23: ArrayBuffer
This type is incompatible with
  /.../core.js:385:1,394:1: Uint8Array

/Users/danvk/code/toy-flow/test.js:9:10,19: access of computed property/element
Indexable signature not found in
  /.../lib/core.js:365:13,23: ArrayBuffer

Found 2 errors
```

The first error is the useful one: `ArrayBuffer` is incompatible with `Uint8Array` (Flow doesn't include the line number for the error because of #329). The second error comes from passing an `ArrayBuffer` to `other()` anyway, despite the fact that its parameter is explicitly declared to be a `Uint8Array`. This error should be suppressed.

This isn't great but it's workable. However, if I move `other()` to a separate module, I lose the useful error message and get only the second one:

```javascript
/** @flow */
// test.js
var other = require('./other');
function foo() {
  var u8 = new Uint8Array([0, 1]);
  other(u8.buffer, 0);  // XXX passing ArrayBuffer, not Uint8Array
}

/** @flow */
// other.js
function other(u8: Uint8Array, offset: number): number {
  return u8[offset];
}

module.exports = other;
```

Type checking these two modules produces only one error:

```
/Users/danvk/code/toy-flow/other.js:4:10,19: access of computed property/element
Indexable signature not found in
  /.../lib/core.js:365:13,23: ArrayBuffer

Found 1 error
```

This is much harder to debug, since `test.js` (where the mistake actually is) isn't even mentioned in the error message.

**Comment by danvk** [comment]
This is still an issue as of flow 0.11.0, which fixed #329.

I _can_ get the relevant line to appear if I run `flow check --traces 3 test.js`, but no lower level of traces.

**Comment by bhosmer** [comment]
Thanks for this Dan - still working on the error system, of course - I'll post an update on progress here. Appreciate the test case!

**Comment by danvk** [comment]
The errors for this are perfect as of Flow 0.17.

The one module case now only shows the useful error:

```
test.js:5
  5:   other(u8.buffer, 0);  // XXX passing ArrayBuffer, not Uint8Array
             ^^^^^^^^^ ArrayBuffer. This type is incompatible with
  8: function other(u8: Uint8Array, offset: number): number {
                        ^^^^^^^^^^ Uint8Array
```

And the two module error is also entirely useful:

```
test.js:7
  7:   other(u8.buffer, 0);  // XXX passing ArrayBuffer, not Uint8Array
             ^^^^^^^^^ property `buffer`
  7:   other(u8.buffer, 0);  // XXX passing ArrayBuffer, not Uint8Array
             ^^^^^^^^^ ArrayBuffer. This type is incompatible with
  3: function other(u8: Uint8Array, offset: number): number {
                        ^^^^^^^^^^ Uint8Array. See: other.js:3
```
