### ISSUE TITLE
Document `empty` type

### ISSUE THREAD

**Issue by danwang** [facebook/flow#4090]

**Comment by roryokane** [comment]
The `empty` type is described in #2225, the issue that asked for it to be implemented. It’s a “type that is not satisfied by any value”. It’s the equivalent of [`never`](https://www.typescriptlang.org/docs/handbook/basic-types.html#never) in TypeScript.

**Comment by wuweiweiwu** [comment]
@samwgoldman  @roryokane  Can i take this?

**Comment by rpivo** [comment]
What's the status of this? It looks like there is an open PR that was never merged. I'd be happy to work more on this if it's needed.

**Comment by roryokane** [comment]
The new documentation for the `empty` type is online at https://flow.org/en/docs/types/empty/.

**Comment by gkz** [comment]
Seems to have a bug rendering. I can fix that. The beta site renders fine in the meantime: https://beta.flow.org/en/docs/types/empty/

**Comment by gkz** [comment]
Fixed with cad9f2531285bf6fcdf6d25e8b5a1e4626b53a14
