### ISSUE TITLE
Is flow.js (the compiled-to-js version of Flow) published anywhere?

### ISSUE THREAD

**Issue by inlinestyle** [facebook/flow#4092]
I was really happy to discover that Flow is runnable in the browser with the `flow.js` bin a la https://flow.org/try/.

I haven't been able to find it published anywhere (unless you count https://flow.org/static/v0.47.0/flow.js) for easy external use though. Am I not looking hard enough or is it really not on `npm`?

Followup question if the answer is "no": are there any plans to publish `flow.js`? I think it would be a nice additional offering, for very low extra effort!

**Comment by mroch** [comment]
yep, https://www.npmjs.com/package/flow-parser!

**Comment by inlinestyle** [comment]
@mroch I get that `flow-parser` comes with the parser, but I was under the impression it did *not* include the type checker. Is there an option to turn on type checking?
