### ISSUE TITLE
createMediaSource should expect a parameter

### ISSUE THREAD

**Issue by v4n** [facebook/flow#4095]
Using `AudioContext.createMediaStreamSource` with a parameter results in flow complaining:

```
createMediaStreamSource(): MediaStreamAudioSourceNode;
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function type expects no arguments. See lib: /private/tmp/flow/flowlib_152ee7a3/bom.js:594
```

`createMediaStreamSource` is supposed to expect an argument https://webaudio.github.io/web-audio-api/#widl-AudioContext-createMediaStreamSource-MediaStreamAudioSourceNode-MediaStream-mediaStream

**Comment by pinkstrings** [comment]
This was fixed in 469518a
