### ISSUE TITLE
Declared value still seen as undefined by Flow

### ISSUE THREAD

**Issue by faure-finimize** [facebook/flow#4098]
For some reason, Flow is telling me a value I've shielded against is still undefined, see screenshot.

I'm using Flow version 0.47.0

![image](https://cloud.githubusercontent.com/assets/24221728/26783378/c06079ac-49ef-11e7-8597-6f349c07407c.png)

**Comment by AugustinLF** [comment]
Flow is pessimistic about [refinements](https://flow.org/en/docs/lang/refinements/), which means that it considers that any function call could invalidate any previous refinement (what if `roundToDP` would set `timeSolutionDetails.unit` to void?).

To avoid this problem, you can do something like:
```javascript
if (timeSolutionDetails.unit === undefined) {}
else {
const unit = timeSolutionDetails.unit;
results.timeSolutionsDisplay = roundToDP(processedTimeSolution, 0) + ' ' + unit
}
```

If this still doesn't work, could you provide a working https://flowtype.org/try/ example? :)

**Comment by faure-finimize** [comment]
@AugustinLF it didn't work, here's some sample code.

https://flow.org/try/#0C4TwDgpgBA9gRgKwgY2AFXNAvFA3gKCijBgGdSBLOAGwgDUBDagVwgH4AuKU4AJwoB2Ac3wBffPmQwBPKAObVqAeUQp0mKDlzjJ02QFsYyANYAxZgNQVpmqAAoAlJoB8UAOSGT3PoKFuJEAAeJLzAUFIyYcAQPOaWwNYCtnagkAAmKkioXPBZ6pC28oqZahiQTliuBEQRsrwxCmFc1URQ9aSNEGmMLOxcPPzChFCittrDwxQAZvapXSWomlg4FmkQU4JdTi1E7Y0AdHvU0d1MrLaeZhZW0o7DoxDUpNA74XphJORUtD3nOHMZVSofafSg0ehnCDDXYNY6HWEnX7YKCXOI3ASOKAAamIZDBP0h9wmMOAzF4SSOwDEQA

**Comment by AugustinLF** [comment]
In your example, you test against `typedObject`, instead of `typedObject.possibleValue`.

This [works](https://flow.org/try/#0C4TwDgpgBA9gRgKwgY2AFXNAvFA3gKCijBgGdSBLOAGwgDUBDagVwgH4AuKU4AJwoB2Ac3wBffPmQwBPKAObVqAeUQp0mKDlzjJ02QFsYyANYAxZgNQVpmqAAoAlJoB8UAOSGT3PoKFuJEAAeJLzAUFIyYcAQPOaWwNYCtnagkAAmKkioXPBZ6pC28oqZahiQTliuBEQRsrwxCmFc1URQ9aSNEGmMLOxcPPzChFCittrDwxQAZvapXSWoAHQk5FS0PayaWDgWaRBTgl1OLUTtjYtn1NHdTJs4nmYWVtKOw6MQ1KTQJ+F6YSuUGj0W7YKBzDKqJYAtbA3rDU4NK4XRHXDagh5xZ4CRxQADUxDIgPWILeEwRwGYvCSl2AYiAA).

**Comment by faure-finimize** [comment]
@AugustinLF good catch, it does work in the playground but it doesn't work in my system

![image](https://cloud.githubusercontent.com/assets/24221728/26785123/d34b3b70-49f8-11e7-803b-69add61585a8.png)

```
src/goalsFramework/goalSolver.js:317
317: 				results.solutionDisplay = roundToDP(processedTimeSolution, 0) + ' ' + timeSolutionDetails.unit
     				                                                                      ^^^^^^^^^^^^^^^^^^^^^^^^ undefined. This type cannot be added to
317: 				results.solutionDisplay = roundToDP(processedTimeSolution, 0) + ' ' + timeSolutionDetails.unit
     				                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ string
```

**Comment by faure-finimize** [comment]
Actually, it does work when I run `yarn flow` in the terminal but for some reason the flow plugin in VSCode isn't running properly.

**Comment by AugustinLF** [comment]
Hmmm, sometimes the vscode plugin takes a bit to catch up, but it's usually fine! I would then suggest you to close this issue and open one in the plugin's repo!

**Comment by faure-finimize** [comment]
I'm closing this. Your initial suggestion did help @AugustinLF, many thanks!
