### ISSUE TITLE
No error for invalid returned type; Type being inferred incorrectly

### ISSUE THREAD

**Issue by sargun** [facebook/flow#4105]
```

export const Actions = {
    ADD_TODO: 'ADD_TODO',
    REMOVE_TODO: 'REMOVE_TODO',
    TOGGLE_TODO: 'TOGGLE_TODO',
    COMPLETE_TODO: 'COMPLETE_TODO',
    SET_VISIBILITY_FILTER : 'SET_VISIBILITY_FILTER'
};

export type ActionType = $Keys<typeof Actions>;

export type idx = number;

export type CompleteTodo = {
    type: typeof Actions.COMPLETE_TODO,
    id: idx
}

export type AddTodo = {
    type: typeof Actions.ADD_TODO,
    text: string,
}

export type Action = CompleteTodo | AddTodo


export function addTodo(id: idx): AddTodo {
    return {
        type: Actions.COMPLETE_TODO,
        id: id
    }
};

```

See, the function `addTodo`, is meant to return `AddTodo`, who's property, `type` should be `typeof Actions.ADD_TODO`, instead, it returns `Actions.COMPLETE_TODO`. This is invalid.

**Comment by sargun** [comment]
It seems like `typeof Actions.COMPLETE_TODO` isn't setting up a type refinement, and instead just being treated as a string

**Comment by agentcooper** [comment]
Trying to reproduce, I correctly get an error for `addTodo`: https://flow.org/try/#0KYDwDg9gTgLgBAYwgOwM7wIIJgSxauAXjgG8AoOSuDAERoH0AVAeRuYC44ByWhltrgBoKVAEoBRALLMAauKasO3CdLkKBwqnBYBxHQBl5-JV10GjioSMoBhZpIAKhxhbacudx89fMrWgMrijPQyAJL+oQBCofqhjACa9ABiMS6icO6BwWER0bEJyaniolxkAL4A3GRkoJCwcDAAnmDA1Nh4yIzNrcQAJADSwI2oADxNLRAAZm24+AB8VTXg0PDjrTgAJiBEcMgArgC2AEbAUIu1Kw3dcDYQB2AANsAwwIwQGxA75FprnGtTMw6qAAdJ4nEEfJoqJtOJsQOVqhd6mtqBsNm8Pl9rFcWn9ugCsLM0MDeOpmFDKC8QDBOOgoDhkABzYRlRHLZHXQkdHa3e5PF4Yz4AH1R6PeEGqSzq8Eme2Q7RQcAAhmjBQAKGFwOEASk4GFV4tI2Kgzz2UGQRq0P26eoVxLB3jJFKtms22NZlTIQA

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2639
