### ISSUE TITLE
Internal Error while running gen-flow-files

### ISSUE THREAD

**Issue by njakob** [facebook/flow#4106]
Seems the internal error `Internal Error: Unexpected method type: IntersectionT` is raised while running `flow gen-flow-files` on the following piece of code. Usage of `Buffer` type seems to be issue.

However, the type checking the same code with `flow check` is perfectly fine.

```js
/* @flow */

export default function foo(buffer: Buffer): string {
  return buffer.toString('utf8');
}
```

Flow version 0.47.0 with empty configuration file.

**Comment by TrySound** [comment]
gen-flow-files is removed. A replacement is coming soon.
