### ISSUE TITLE
Cant reuse check for union type saved into variable

### ISSUE THREAD

**Issue by iam4x** [facebook/flow#4108]
This will return a flow error:

> call of method `map`. Method cannot be called on possibly null value null

```js
function (children: null | Array<string>) {
  const hasChildren = children && Array.isArray(children) && children.length > 0;
  return `
    Hello world!
    ${hasChildren ? children.map(c => `Hello ${c}!`).join('\n') : ''}
  `;
}
```

Here is the try flow example: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKAbzFwAtCYATAJwFNSBfALjFoZM2nPtkwwYYAD5gAgq1YBDAJ4AeAM75WhbAHMAfGC4BKPpu17+qMHRKaw9ReoDCjFh1IBeOQpUA6QnV5JWVKQXdOYzAAMmi6N2FsPxhOXXx6MEMABgBuazB8jnxMVlIAA3ybAAl2CTgwBDhWFgBCSrAAEmpHFwSPMAB+eKEPPwBbRQAHMLBPQzKaus7qXC4WsuM-ACs4HUoAcgAdbH2ovn39rnyyvKugA

How to re-use a check?

**Comment by agentcooper** [comment]
There is an undocumented `%checks`:

```js
/* @flow */

const hasChildren = (children): %checks => Array.isArray(children) && children.length > 0;

function foo({ children }: { children: null | Array<string> }): string {
  return `
    Hello world!
    ${hasChildren(children) ? children.map(c => `Hello ${c}!`).join('\n') : ''}
  `;
}
```
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAAsBDXAYSIEsYATAJwFNswBeMACg2rqewEoAXGACk3RhgDWuNgD4wAQXr0SATwB0VXEpWquPBs35gAZCbDcah7OpjMA5viJh5ABgDc6KAFdsGfFQ4YFBwcBwA3hYGfGAAvsKRlrzMwtjeMDBgAD6KymoAPAT0VNj28rFCYEUl9mDhqGBgTPje9CwABg2NYAASjBlwYAhw9HQAhF2NACThpBTRzPpWfMYA-FHLzOoAtiQADlxyYO19A2AzGLFj7fzqAFZwJRwA5AA62M-Gws-PsV3tnliQA).

But there is definitely something buggy going on in your example.

**Comment by iam4x** [comment]
My use-case is more complicated than this repro case, I would like to re-use this checks multiple time in the function body. It's unconvenient that we have to call this check function n times in the original body function.

Thank's for the answer.

**Comment by SamChou19815** [comment]
This is out of scope for refinements
