### ISSUE TITLE
Cannot refine arity with function.length property

### ISSUE THREAD

**Issue by tmcw** [facebook/flow#4109]
I'm trying to upgrade a large project to flow 0.47, and have a set of methods called with either 2 or 3 arguments. I've tried using [the spread workaround](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/) documented in the blog post, but that conflicts with my eslint configuration and I'd like to find something that doesn't require a change to every function with <2 arguments.

Ideally I'd be able to switch between calling a method that takes 2 arguments versus 3 arguments by relying on the `.length` property. I'm not sure why, but [this doesn't seem to work](https://flow.org/try/#0G4QwTgBAZgdhC8EAUIA0EBGBKBA+CIEA1JgFCkCWUysAdADYCmMA5gC4AWCiAzDgN6kAkLCQBGdACZ0fANykAvkA) - the link previously being a check to the `.length` property of a function, that gives the function's arity. In this case, since `fn.length === 3` would evaluate to `false`, the function would never be called, but Flow still reports an error as if the function would be called.

Here's [the file I'm trying to upgrade](https://github.com/documentationjs/documentation/blob/master/src/parse.js): each function takes `(result, ?tag, ?key)`. The options look somewhat dire:

* Adding `tag, key` to every function causes eslint to complain because of `no-unused-vars`. I'd rather keep that rule in place.
* Relying on `.length` doesn't signal anything to Flow.
* Maybe I could bundle up the arguments into an object, so every method receives an object. That seems kind of silly.
* I could segregate this big object of functions into different objects of each arity. That seems wrong.

**Comment by vkurchatkin** [comment]
Suing `function.length` for refinements is really unsafe. Instead of using spread workaround you can  manually safely cast your function:

```js
var fn = (a, b) => a + b

if (fn.length == 3) {
	(fn: (number, number, number) => number)(1, 2, 3);
}
```

**Comment by tmcw** [comment]
Unfortunately I don't think that's sufficient either: test case for fewer arguments https://flow.org/try/#0G4QwTgBAZgdhC8EAUIBcEYFcC2AjApmADQS7pZ6EkDG5OBYAlAgHwQgQDUpXE1AUPwCWUZLAB0AG3wwA5gBcAFgkQAmZgG9+ASCSx0SCgxJHCzeG1NMkARhLqA3PwC+QA

```js
var fn = (a: number, b: number, c: number) => a + b + c

if (fn.length == 2) {
	(fn: (number, number) => number)(1, 2);
}
```

Produces

```
4: 	(fn: (number, number) => number)(1, 2);
         ^ undefined (too few arguments, expected default/rest parameters). This type is incompatible with
1: var fn = (a: number, b: number, c: number) => a + b + c
                                      ^ number
```

**Comment by vkurchatkin** [comment]
This wouldn't work in any case, because `fn` requires at least three arguments.

**Comment by tmcw** [comment]
In this case, though, `fn` wouldn't be run. `fn.length == 2` tests for whether it requires 2 arguments or another arity, and doesn't run it because it requires 3. It's possible to refine / re-annotate a method that takes n arguments into one that takes `n + 1`, but not to test for whether a function takes `n` arguments and run it if it does.

**Comment by vkurchatkin** [comment]
The bottomline is that Flow doesn't take runtime arity into account, because it doesn't correlate much with static arity.

Some examples:

```js
const fn1: (number) => void = () => {}; // static arity 1, runtime arity 0
const fn2: () => void = (x) => {}; // static arity 0, runtime arity 1
```

**Comment by tmcw** [comment]
There isn't any way to test for static arity, though, right? So really flow doesn't allow any sort of arity-related type refinement, like it does with `typeof` checks. Maybe I can... define a new type that extends Function? Otherwise I'll need to just rewrite the way that I do this handling entirely, which is kind of unfortunate because what this file is doing is a pretty useful and common javascript pattern.

**Comment by vkurchatkin** [comment]
@tmcw can you point me to exact line that is not working?

**Comment by mrkev** [comment]
Hmmm.

#### 1. It would be cool if flow could refine on arity.

I can see it being useful for union types or `Function` values.

#### 2. In your particular case, IMO you don't need to refine on arity.

You ARE writing functions that could have unused arguments. That's a conscious choice you made and you want to keep for the sake of your API. ESLint should complain at you because semantically that's what you are doing, but that's fine because having unused variables is a stylistic preference, not a mistake. In my opinion it's not something to consider rewriting your application around-- if you want to have unused arguments disable ESLint for those cases.

#### 3. There's a workaround

https://flow.org/try/#0G4QwTgBAZgdhC8EAUA6N4DmBnAlAgfBAN4C+AUGQJZTKwoA2ApjBgC4AWCiATHkWQEhYSAIwAaCLwDcZEkA
