### ISSUE TITLE
Feature request: Rewrite error messages to include variable identifiers

### ISSUE THREAD

**Issue by m1sta** [facebook/flow#411]
It'd be great if error messages were reformatted to include variable identifiers such that this...

```
hello.js:5:5,19: string
This type is incompatible with
  hello.js:3:10,15: number
```

...would instead look something like...

```
hello.js:5:5,19: function 'foo' called with parameter 'x' as a string however
  hello.js:3:10,15: the definition of function 'foo' implies that 'x' be a number
```

Related to #401

**Comment by avikchaudhuri** [comment]
There are some lines of ongoing work in this space. One involves traces (try doing check --traces 2, e.g.) which give additional intermediate locations involved. Another remembers the operation that triggers the error: it currently only does this in a few places, but the set is growing. Together, they should give you the info you want.

**Comment by nmn** [comment]
The error messages now show you the actual code where the error occurred. At least this issue is resolved.
