### ISSUE TITLE
Making a sealed empty object

### ISSUE THREAD

**Issue by rbalicki2** [facebook/flow#4112]
Flow's docs say: `When you create an object without any properties, you create an unsealed object type in Flow. ` Is it possible to create a sealed object without properties?

My use case is as follows. I want to initialize `state` to an empty object, and give state the following type:

    type EmployeesViewState = {|
      employeesRequest?: Request<Array<Employee>>,
      geosRequest?: Request<Array<Geo>>,
    |};

The error I get when I try to assign an empty object is 

     33:   state: EmployeesViewState = {};
                                       ^^ object literal. Inexact type is incompatible with exact type
     33:   state: EmployeesViewState = {};
                  ^^^^^^^^^^^^^^^^^^ exact type: object type

Of course, since I don't have the requests available yet, I cannot assign them. I also can't assign `undefined` to the object because the state is defined with pipes, i.e. it is an exact type.

I can trick flow by saying `const a: any = {}; state = a;` but that seems really hacky. Any other ways of tackling this issue?

**Comment by samwgoldman** [comment]
In the medium term, we're hoping to fix things such that `({} | {| p?: T |})` will type check, but until then the kinda gross workaround is to declare a module that exports an empty object, then use that instead of an empty object literal.

**Comment by rbalicki2** [comment]
Thank you. That is an ugly workaround!

**Comment by keithkml** [comment]
Hi, why was this issue closed? I don't believe it's been resolved.

**Comment by eric-burel** [comment]
Hi, same here, I don't think this is fixed. Shouldn't Flow consider the empty object to be sealed when its type is explicitely the empty sealed object `{||}` ?
