### ISSUE TITLE
What about .flowconfig.js ?

### ISSUE THREAD

**Issue by KROT47** [facebook/flow#4115]
As you can understand some flow config may depend on project config, so it will be useful to have an opportunity to dynamically create flow config.

A good example is [eslint config](http://eslint.org/docs/user-guide/configuring) in form of .eslintrc.js

**Comment by 0xdevalias** [comment]
For reference/easier findability, these are the `flowconfig` related issues/suggestions I found that would bring it in line with other tools like `eslint`, `babel`, `webpack`, etc:

- https://github.com/facebook/flow/issues/4115 : What about `.flowconfig.js`
https://github.com/facebook/flow/issues/153 : `.flowconfig` should use json
- https://github.com/facebook/flow/issues/238 : `.flowconfig` should recursively consider other `.flowconfig` files
- https://github.com/facebook/flow/issues/3569 : Flow config in `package.json`

**Comment by TrySound** [comment]
Flow is written in ocaml. Adding node.js runtime may negatively affect performance and increase complexity.
