### ISSUE TITLE
promisify is not found in 'utils'

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/flow#4116]
http://2ality.com/2017/05/util-promisify.html

Need to update flow defs

**Comment by aprisniak** [comment]
The same issue.

```
import { promisify } from 'util';
              ^^^^^^^^^ Named import from module `util`. This module has no named export called `promisify`.
```

**Comment by vith** [comment]
found a related PR: https://github.com/facebook/flow/pull/4176

**Comment by jokeyrhyme** [comment]
I'm toying with something like this for the moment, seems to work, and I'll just keep adding more possibilities to it as I encounter missing cases:

```
declare module 'util' {
  declare var promisify:
    <TResult>((Error, TResult) => void) =>
      () => Promise<TResult> |
    <TArg1, TResult>(TArg1, (Error, TResult) => void) =>
      (TArg1) => Promise<TResult> |
    <TArg1, TArg2, TResult>(TArg1, ? TArg2, (Error, TResult) => void) =>
      (TArg1, TArg2) => Promise<TResult>;
}
```

It would be terrific if we could put spread arguments at the beginning of a function's arguments list instead of only at the end

**Comment by jcready** [comment]
I'm not sure how it would be possible to type `util.promisify` correctly based on [how it works internally](https://github.com/nodejs/node/blob/master/lib/internal/util.js#L201-L258). If a function passed to it has one of two special symbols on it, the result is totally different. And Flow doesn't exactly handle symbols gracefully, let alone functions with defined symbol properties.

**Comment by dckc** [comment]
This fixed in d717d37 on Aug 1, 2017 in #4176, no?

The type isn't very useful... I noted my approach in the discussion in #4176.

**Comment by Mathspy** [comment]
@goodmind This been fixed indeed as shown from comment above

**Comment by goodmind** [comment]
@Mathspy Type is `any` basically
