### ISSUE TITLE
bluebird and flow: Promise.map over Object.keys()

### ISSUE THREAD

**Issue by Kiechlus** [facebook/flow#4121]
[Please refer to this example.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBCuuATmALxgDeqYYARiQIYB2AJgFxgDO6JAliwDmAGlpgmMAMZwAFnBhcWAVwC29UmIC+GHPgDqTdKQrVxjVpx59BosKh1Y8YACICWAa26madDaS4iTXEEIwCwQ2MSB1RUKGUWKXR+OBYwAA9MAC8ACjZ3LzAuN0EvAEozOgB5egArXCSAOg9cTG48gu4yxtUmbA7SgDkmVXxyAD5KuhkWXjB80tMFz24AbWWPYdGAXXF5gsaLdgBuMGBgVzhcbhYAcnQwdFkSRAlvXHS8JNw2PY3GyQyeQwU7nMAAFWeiG8THenwaxl+dC0ZXE4hmcwACi9VPxuGMwCRcABHZT8Ik5W70GDKXD0clsW5lY7ibFwXH4np9HI1epNFptAYrMoifZDEZjSa+OhgDEPDZLTrrApbXDbFkysWeAHSOQKUEXFxXG73R5QpD0ZQPbjyZQwNgAQnEKIcQA
)

Flow surprised me that it can infer everything in `Object.keys(...).map`. However, I need the same for [Promise.map](http://bluebirdjs.com/docs/api/promise.map.html), where it does not work anymore. 

Extract from the whole example: 

    const Promise = require('bluebird');
    Promise.map(Object.keys(drinks), drinkName => {
       const drink = drinks[drinkName];
       drink.alcohol; // Doesn't throw but should!
    })

**Comment by agentcooper** [comment]
Did you try adding type definitions for Bluebird?

They are available through [flow-typed](https://github.com/flowtype/flow-typed):
https://github.com/flowtype/flow-typed/blob/master/definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js#L76-L80

Otherwise you can just type `drinkName` in the `Promise.map`:

```js
  Promise.map(Object.keys(drinks), (drinkName: $Keys<Drinks>) => {
    const drink = drinks[drinkName];
    drink.alcohol; // correctly shows the error
  })
```

**Comment by Kiechlus** [comment]
Wow, that flow-typed works like a charm. However, the [library we use](https://theintern.github.io/) uses an [asynchronous module loader (AMD)](http://dojotoolkit.org/reference-guide/1.10/loader/amd.html#loader-amd).

Any idea how to get flow and flow-typed working with such an AMD as in [this example?](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgJIDsDGMArgCYCmYARsWZQJYBOJYCdALgBZiyIC0bATwAOZEunxxcAZzZgACgzgBbOlIoBeMAzIBHIozIAKAOTUitRiWMBKANyoFy1WQB0ADwEAvMJjAAVDkUEKTAAQxCyNxF8NlF0XwAJRDA2ODAiNW54JFSAczJOMgYWdi4AQQBZABEAfnRyKDpcIwBtHywAoJDKIlkpDjgiGGZcODYXVDAwYybYhlxgEjgAKzhgUfIAQjMLJmMAGlQAXX3uIgI2OkkwQ0cVNWswAG9J+UV71w9vXyq4MilcMZZJwglRemB+oNhptUABfaxAA)

    define([ // Throws but should not.
      'intern/dojo/node!bluebird',
    ], function (Promise) {
      Promise.xyz // Doesn't throw but should!
    })

**Comment by agentcooper** [comment]
You can try using comments, so that `BluebirdPromise` will be visible by Flow (more: https://flow.org/en/docs/types/comments/).

I did not test this:

```js
/*::
const BluebirdPromise = require('bluebird');
*/

define([
  'intern/dojo/node!bluebird',
], function (Promise: BluebirdPromise) {
  Promise.xyz();
})
```

**Comment by Kiechlus** [comment]
Getting closer and closer. It recognizes the bluebird functions now, but doesn't accept the arguments of `Promise.map` (while it works fine in a non-AMD-way).

![image](https://user-images.githubusercontent.com/9875731/26926021-2d961154-4c4c-11e7-9f58-6854c992b6d8.png)

**Comment by agentcooper** [comment]
Is the type of `Promise.map` inferred correctly?

With flow-typed definitions in place, maybe you can try using [`Bluebird$Promise`](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js#L50) instead of the comment trick:

```js
define([
  'intern/dojo/node!bluebird',
], function (Promise: Bluebird$Promise<*>) {
  Promise.xyz();
})
```

**Comment by Kiechlus** [comment]
Unfortunately, that didn't help. It uses [this map](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js#L153)  instead of [the real definition of map](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/bluebird_v3.x.x/flow_v0.33.x-/bluebird_v3.x.x.js#L76).

**Comment by agentcooper** [comment]
Use `Class<BluebirdPromise<*>>`.

<img width="981" alt="screen shot 2017-06-08 at 13 50 13" src="https://user-images.githubusercontent.com/794591/26927282-872997e0-4c51-11e7-9911-783c73725690.png">

**Comment by Kiechlus** [comment]
Thank you a lot for your help, @agentcooper !!
