### ISSUE TITLE
Dynamic $PropertyType<> key

### ISSUE THREAD

**Issue by yachaka** [facebook/flow#4122]
Hi,

I have a `User` object:
```js
type User = {
  name: string,
};
```
That has a `get()` function, that takes in parameter the key of an attribute on `User` and returns this attribute.
The function get is

```js
User.prototype.get = (prop) => {
  return this[prop];
};
```

How can I write this fonction definition ?
Here's what I got so far:

```js
type User = {
  name: string,
  get: (k: $Keys<User>) => any, // How can I change any to the correct property type ?
  // It would be great if I could do `get: (k: $Keys<User>) => $PropertyType<User, k>`
};
```

Thanks :)

---
[Associated StackOverflow post](https://stackoverflow.com/questions/44392642/flowtype-return-type-of-function-k-objk).

**Comment by agentcooper** [comment]
[> As of Flow v0.36.0, x must be a literal string. In future versions, x may be allowed to be any type, as long as that type exists on the keys of T.](https://flow.org/en/docs/types/utilities/#toc-propertytype)

We all are waiting for https://github.com/facebook/flow/pull/2952 :-)

**Comment by szagi3891** [comment]
@agentcooper 
Do you know why we still have to wait for this PR? :/

**Comment by madbence** [comment]
`$ElementType<T, K>` landed, i guess this issue can be closed :tada:
