### ISSUE TITLE
$Keys<> and $Subtype<> question

### ISSUE THREAD

**Issue by rkurbatov** [facebook/flow#4124]
This code doesn't work.

```
const topLevelReducers = {
  account: {},
  analytics: {},
  content: {},
}

type TopLevelReducers = $Keys<typeof topLevelReducers>  | 'version'
type Whitelist = Array<string>
function f(a: Whitelist) { console.log(a) }
const x: Array<TopLevelReducers> = [ 'account' ]

f(x)
```

```
8: type Whitelist = Array<string>
                          ^ string. This type is incompatible with
10: const x: Array<TopLevelReducers> = [ 'account' ]
                   ^ union: key set | string literal `version`
```

https://flow.org/try/#0MYewdgzgLgBFIAcAyBTAbigNgJRQEwFdgUAnCGAXhgG8AoGGAQ2FALCgC4aBfAGnqZhGmAJ5QAlsAhdqfAaHYp2Mud1q0oIhChgAVRKgw58RUuSoASANIoREADybtIAGZwD6LLkLEyAPgYAHxgAcgwycXAQ9ScdAHUAC3EoLHFoShgAQRISRhF7aBJxMABzPwFaFzZgCXAYFwAKRi5E5NToAEoaGAUIEEwUADpMEBKmrrVaXtgADy5s3Pz9ZE9jHzMAqgBtUOZWdhCYAF11RpmOoA

Can $Keys<T> be treated as the union of string values? Or how else we can redefine type so

f(x: Array<string>) could work with y: Array<$Keys<SomeObject>> as an argument?

**Comment by rkurbatov** [comment]
https://flow.org/try/#0MYewdgzgLgBFIAcAyBTAbigNgJRQEwFdgUAnCGAXhgG8AoGGAQ2FALCgC4aBfAGnqZhGmAJ5QAlsAhdqfAaHYp2Mud1q0oIhChgAVRKgw58RUuSoASANIoREADybtIAGZwD6LLkLEyAPhgAHxgAcgwycXAQ9ScdAHUAC3EoLHFoShgAQRISRhF7aBJxMABzPwFaFzZgCXAYFwAKRi5E5NToAEoaGAUIEEwUADpMEBKmrrVaXtgADy5s3Pz9ZE9jHzMAqgBtUOZWdhDeUPCISLAQmABddSqwGrOexmgm+Zy8+2XDLxNfCD8O16LApQIqlAJ0ACQJBQUAIJDATEGAFtGAgGgBlEHFEodWiTRrAJ5QBozDq4oA

Solution with type casting is working but that's pretty ugly.

**Comment by rkurbatov** [comment]
It's more $Subtype<> question as I understand. So:

```
const topLevelReducers = {
  account: {},
  analytics: {},
  content: {},
}

type TopLevelReducers = $Keys<typeof topLevelReducers> | 'version'
type Whitelist = Array<$Subtype<string>> // <-- works while Array<string> doesn't
function f(a: Whitelist) { console.log(a) }
const x: Array<TopLevelReducers> = [ 'account', 'version' ]
f(x)
```

the question is how Array<string> differs from Array<$Subtpe<string>>? Why this refinement works?

**Comment by rt2zz** [comment]
👍, very curious to understand how `Array<$Subtype<string>>` differs from `Array<string>`, and why this resolves the issue.

**Comment by agentcooper** [comment]
It seems like a variance problem.

You can use `$ReadOnlyArray`:

```js
type Whitelist = $ReadOnlyArray<string>;
```

**Comment by rkurbatov** [comment]
Hm... Thanks!

**Comment by TrySound** [comment]
Subtype is deprecated utility type
