### ISSUE TITLE
React$Element<any> or React.Element<*>

### ISSUE THREAD

**Issue by steida** [facebook/flow#4130]
I would love to know final official recommendation how we should type element. Thank you.

**Comment by awestroke** [comment]
`any` allows any type, `*` tries to infer a single type statically -- so it depends on what you need.
If you need the variable to hold a react element regardless of props, use `any`. If you need to be sure the props are always the same, use `*`.

**Comment by dmnd** [comment]
I'd love to see this documented too. How to type a React Element is conspicuously missing from the [Flow + React](https://flow.org/en/docs/frameworks/react/) page in the docs.

I've seen React$Element, React.Element, React<Element>

**Comment by youngzhaosignifyd** [comment]
@dmnd:

The updated doc now explains the difference between `React$Element<*>`, `React.Element<*>` (basically they are the same). This is based on flow v0.53.1:

`import React from 'react'` doesn't exposes the React types anymore. So if you want to use `React.Element<*>`, you need to use `import * as React from 'react'`.

These will all work
```
// I think this the better
import React from 'react';
import type { Element } from 'react';
const test: Element<*> = <div />;
```
```
import * as React from 'react';
const test: React.Element<*> = <div />;
```
```
import React from 'react';
const test: React$Element<*> = <div />; // React$Element is a global type
```

This doesn't work anymore
```
import React from 'react';
const test: React.Element<*> = <div />;
```

Doc: https://flow.org/en/docs/react/types/#toc-react-element
React$Element: https://github.com/facebook/flow/blob/master/lib/react.js#L159
Element: https://github.com/facebook/flow/blob/master/lib/react.js#L209

**Comment by dmnd** [comment]
Excellent, thanks @youngzhaosignifyd. I think we can probably consider this issues closed now @steida
