### ISSUE TITLE
Flow Comments: problems with Optional Parameters?

### ISSUE THREAD

**Issue by Kiechlus** [facebook/flow#4132]
[Please see the whole example here.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swATAJ0OwGsAKAQwFs4d9QB+ALjG0yYBGAUwooAlGADeAXzDBgYAJL4wCOBRoBnVQAshpRWCYMaQsAAcGFIU3wjeJALRxzREgxgYcBYqUrUaADl1YxhGFjZuXn5hCgkZdH9aOgByfDg4I0xcHRSxAG45BQAROCFNbDSwfB0KRDABTBVNHVYYMlQkoJCPVKEAN30jdSE8wqKwABVaxG0GbSEAD3MhAiEyIA)

Extract from the example:

    function drink(amount/*?: number*/) {} // It works when I make paramter non-optional
    drink('too much'); // Doesn't throw but should

**Comment by madbence** [comment]
as mentioned in the [docs](https://flow.org/en/docs/types/comments/#toc-comment-type-annotation), you have to use the include comment form, ie `function drink(amount/*:: ?: number*/) { ...`.

**Comment by Kiechlus** [comment]
ups, thx
