### ISSUE TITLE
Lots of missed errors in if statements over object keys

### ISSUE THREAD

**Issue by jamesisaac** [facebook/flow#4134]
**Update:** It's been pointed out that technically the code below is free from errors, but only because it practically all evaluates by Flow as unreachable.  Please see the discussion below on how it would be good for Flow to flag this case, rather than silently ignore.

---

I found a simple type error in my codebase and was surprised that Flow hadn't picked it up.  So I started playing around with even simpler cases, and confused why Flow is missing out on several obvious errors?  See the example below (I count 6 missed errors):

```js
/* @flow */

type Person = {
  name: string,
}

function f(person: Person): boolean {
  if (person === 'Alice') {
    return person
  } else if (person === 'Bob') {
    return person.age
  } else if (person.foo === 3) {
    return true
  } else if (person.name.zzz === 'John') {
    return true
  } else {
    return false
  }
}

// No errors!
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKeATgM5wB2YAvGAN6phiUCGAtngFxhkYkBLSgHMANKgC+6KAFdKAYwwCqYKAAp85Kj2JbKASh4AjOHBh5W1RswFQwG0hWo0XYAOQBBGAPl43+hiZmMBI8DBkSak0nIIkwPBgyAlt7aJUXOjcAITgjf0DgkLCIqMcqADpWYTxY+MTkuwc9cqhTWlcAZgDrYNDwyLB+GRrmOISksBSmp3K2TnKALyX2zIApOAALSnye5j6SwZJh2vGCXaL+6ihWetjJIA

I thought this might be something to do with not using exact object types, but that actually introduced even more missed errors (I count 2 additional, so 8 total):

```js
/* @flow */

type Person = {|
  name: string,
|}

function f(person: Person): boolean {
  if (person === 'Alice') {
    return person
  } else if (person === 'Bob') {
    return person.age
  } else if (person.foo === 3) {
    return person.foo // <-- new error
  } else if (person.name.zzz === 'Chris') {
    return true
  } else {
    return person.namez || true // <-- new error
  }
}

// No errors!
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKeATgM5wB2YAvGAN4A+qYYlAhgLZ4BcYZGEgEtKAcwA0qRgF90UAK6UAxhiFUwUABT5yVPsV2UAlHwBGcODDztq9FmCFQw20hWo0PYAOQBBGEKU8LyMGe1YSPAx5EmodN3tpMDwYMgJHZzj1DzovACE4U2DQ1nDI6NjXKgA6dlE8BKSUtKcXQyqoC1pPAGYQuxKwCKiYsEzKds7gYDAAHgBaObY8JFISOBIG5NSHFrGqjm4qgC8TrpyAYQALYTIi-pKh8rBBeXrWRK2Ce9LhiraDvBHMCMRjPEivMBTWYLJYrEhrDbvVDSIA

Please advise if there is something I can do to improve the type error detection on this type of code?  The return type doesn't have to be `boolean`, same thing happens with `string` for example.  So this is the type of slip up that could very easily lead to run-time errors.

**Comment by gcazaciuc** [comment]
You declared "person" as an object of type Person.
So "person" can NEVER be a string, as such checks like "if (person === 'Bob')" will never be true. 
The same for "person.foo === 3" etc because person doesn't have a foo property.

It seems Flow detects that and considers the respective returns as unreachable, as such no need to error.

**Comment by jamesisaac** [comment]
@gcazaciuc Ahhh I see, thanks.  Yes that explains why none of the contents of the if-cases are picked up.

So it is not part of Flow's goal to warn about testing an object as the wrong type, or accessing properties which are known not to exist as long as the statement can just evaluate to false?

I seem to remember it previously picking up things like that, or am I mistaken?  Surely it would be helpful to warn about these logically impossible if-checks?

**Comment by jamesisaac** [comment]
I mean, if this was a real example, the most likely case is that I got my type definition wrong, and I meant to type `type Person = { name: string } | string`, not that I wanted 90% of my codebase to be logically impossible dead code which Flow silently ignores.

Would surely be helpful if it gave some indication of that, rather than giving the same output as if the code was 100% valid.

**Comment by gcazaciuc** [comment]
Yeah, i believe it would be a really cool and usefull feature to flag un-reachable code.

**Comment by jamesisaac** [comment]
Yup.  It already flags code after `return` as an unreachable code error, so cases like this would be a nice addition.

The only situation I can think of where I intentionally have unreachable blocks would be creating a run-time error if code from an external source doesn't match what's expected.  So perhaps something to skip blocks like the last one here (e.g. because I was explicit about using the `empty` type, it shows I expected it to be unreachable):

```js
type Status = 'online' | 'away'

function f(status: Status): number {
  if (status === 'online') {
    return 10
  } else if (status === 'away') {
    return 20
  } else {
    (status: empty)
    throw new Error(`Server provided unexpected status: ${status}`)
  }
}
```

**Comment by jamesisaac** [comment]
@gcazaciuc Re the points added in your edit: I see the point of duck-typing when it's to determine which of several possible types a value is (`type Foo = string | number`), or just to confirm that the value is indeed what it's expected to be.

But surely the sort of checking I was doing in my original post completely go against the point of Flow?  Why would you ever be duck-typing to a type which is completely undocumented by the type definitions and evaluates to unreachable?

**Comment by jamesisaac** [comment]
Never mind.  Thinking about it more, I can see why you might want to test (negatively) against a property that is known to not exist, just to confirm the value type is as expected.  I guess the duck-typing checks in my original post wouldn't be a real problem if, like you said, there was a way to flag unreachable code.

**Comment by hmeerlo** [comment]
I once tried to start a discussion on this, but nobody seemed to have an opinion on it: https://github.com/facebook/flow/issues/3562

**Comment by miracle2k** [comment]
There is obviously a case to be made about both behaviours, but I definitely miss flow flagging this kind of issue for me.

**Comment by goodmind** [comment]
Related #2282, #2723

**Comment by SamChou19815** [comment]
These now errors.
