### ISSUE TITLE
Property not found from subclass - how to annotate?

### ISSUE THREAD

**Issue by alinex** [facebook/flow#4135]
How to annotate the following to work without errors?

    /* @flow */
    
    class A {
      x():A {
        return this;
      }
    }
    
    class B extends A {
      y():B {
        return this;
      }
    }

    var w = new B();
    
    w.x().y();

It gives the error: Property not found in A

Try it only: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwwAPACgEoAuYsiigJwFMAXAV1YDswnABYBLXAG5yYAL6pZmHPjAAhMO0qd2fACYEmUgJ516q5iw49+g0RKmz5AN2yswSALxg+7JMrqTUCAB0NLSBRrT+QA

Please correct my code and give me a running example of it.

**Comment by agentcooper** [comment]
[Use `this` as a return type](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwwAPACgEoAuMAFwAsBLAsiigJwFMmAVx4A7Zu1wBucmAC+qeZhz4wAITB9KTPiIAmBYlzABPOo1YdSM3gOFiLUmfMUA3bDzBIAvGBF8kqnTSqAgAdDS0oaa0wUA).

Can't find docs about it, here are some [examples](https://github.com/facebook/flow/blob/dd0603e9d8c9d5fb99a40f0b179a4d6a2b9e66b7/tests/this_type/test.js#L32).

**Comment by vkurchatkin** [comment]
> Use this as a return type

I wouldn't recommend it, it's very unsafe

**Comment by samwgoldman** [comment]
> I wouldn't recommend it, it's very unsafe

I'm now aware of any known unsoundness here. Can you expand on this?

**Comment by vkurchatkin** [comment]
@samwgoldman https://github.com/facebook/flow/issues/2998, although is not as bad as I thought

**Comment by alinex** [comment]
@agentcooper thanks, that works
hopefully the documentation for flow may be optimized with more examples like this in the future
