### ISSUE TITLE
Extending a subclass of React.Component

### ISSUE THREAD

**Issue by dounan** [facebook/flow#4136]
I'm having some trouble getting flow to type check the props when rendering a component that has the following class structure: `React.Component > CustomComponent > MyComponent`

This is being rendered by a `Implementor` component with the wrong props, but flow is not catching it. Any ideas on how to define `CustomComponent` such that flow catches these errors?

The only way I can get this to work is to define `MyComponent` with explicit types:

```
class MyComponent extends CustomComponent<void, Props, void> {
```

But I would like to support the following syntax:
```
class MyComponent extends CustomComponent {
  props: Props
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAAV6OAM5gAvGADeqMGFEMyAOQCuWAEZl8ALjAA7dVvwAaVAF8uqKjAqjxAYVWjCDBwzz6y+wgB4AIiZCQQDKAHxgZAAehN4AJuLk1IQAdO64cF4+AUGCoRGy8i4UhBhUYHFkUBSqMITCcGJ6-lzyOCKieoKtCoQlZHohXOboNnbiALI86Z7exNGx+glgTi5uHplzMnJg7Y2dQh1W8qxL2gAUAJTb8idkhKr4+mDnO7dgvnEYAG5h0oQACwwohSezEKUUWBURm05l8wC+vzeYEuPRGI2stnsYAAkrgYGQoT4CJEYvFEmxUjNNj4bmBTpV8Fc6fJgMBSPFtBh9ABzMBTalZYgIDCAuCqYiAgSQ6GabS7EQKAHimBxelkUS1YjcsAUMCwRCRfD0fDI1gPJ4vZHyT4-MLW26+AUbIVgYD2942hF25Gonbo1BAA

**Comment by agentcooper** [comment]
[`type $DefaultPropsOf<Config> = any`](https://github.com/facebook/flow/blob/2f188497568ba28e8d28736f1ca7501eb9680212/lib/react.js#L107) seems to be the problem.

You can add `static defaultProps: void;` to `MyComponent`.

**Comment by dounan** [comment]
Thanks for pointing me to that link! I'll just do what React does internally and use `$Abstract`.
Here is some more info on what it does:
https://github.com/facebook/flow/issues/2464#issuecomment-248749163

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAAV6OAM5gAvGADeqMGFEMyAOQCuWAEZl8ALjAA7dVvwAaVAF8uqKjAqjxAYVWjCDBwzz6y+wgB4AIiZCQQDKAHxgZAAehN4AJuLk1IQAdO64cF4+AUGCoRGy8i4UhBhUYHFkUBSqMITCcGJ6ACQAghou+MkBYVzyOCKieoJ9CoQlZC3tnd3hXOboNnbiALI86Z7exNGx+glgTi5uHplbMnJgA41DQoNW8qx72gAUAJTn8g9khKr4+mDPC6fMC+OIYABuYWkhAAFhhRCkrmIUoosCojNpzL5gGDIUCwK9RgsFtZbPYwABJXAwMhonwESIxeKJNipDanHwfMCPSr4N5c+TAYCkeLaDD6ADmYDW7KyxAQGFhcFUxFhAlR6M02kuIgUMOVMDi3LIolqxHFYAoYFgiEi+Ho+HxrB+fwB+PkoIhYXdn18MpOcoUSjUWvwEmk1RgojI5jAwG9wI9OK9+MJF2JqCAA
