### ISSUE TITLE
@@ syntax

### ISSUE THREAD

**Issue by borela** [facebook/flow#4137]
In the repo, [there are some instances of the `@@` syntax](https://github.com/facebook/flow/blob/3e4d5898b18c1272b0ffdb58132950db7307a2e5/tests/call_caching1/lib/core.js). Is this related to the well known symbols? I couldn't find it in the documentation.

Thanks

**Comment by zaaack** [comment]
Because it's not a part of flow, its simple javascript built-in method, see: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/@@iterator
