### ISSUE TITLE
Autocomplete class inherted static properties not working？

### ISSUE THREAD

**Issue by zaaack** [facebook/flow#4140]
```js
// @flow
class A {
  static aa: number = 1
}

class B extends A {
  static bb = 2
}

B.
```

```sh
$ flow autocomplete 10 3 < ./Test.js
bb number
name string
```

**Comment by zaaack** [comment]
It's an importance feature for back-end code!

**Comment by zaaack** [comment]
I'm a new bee in OCaml, and only find adding this three lines after this line, https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L10414
and remove L10466, L10486, flow can autocomplete not just the static members of the class, but also the instance members of it's super class (still no static members) 
```OCaml
| ThisClassT (_, t)
    | DefT (_, ClassT t) ->
        extract cx t
```

I don't know how to debug or print the type of this project, hoping some OCaml expert can help.

**Comment by mroch** [comment]
pretty sure this works these days!
