### ISSUE TITLE
How to annotate Object.create and Object.assign calls?

### ISSUE THREAD

**Issue by alinex** [facebook/flow#4142]
Please check this: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwwBzAUwBcws4A7agCgEoAuMWgCwEsCZChQBOdAK6imYAPIAjAFbUMtAHR5c-Sk1YLlqtRnHZabPoPYAaHgNztyYAL6oXmHPjAAhMNQAeZkwAJgTEJG4AbtiiYPJgALxgLEheHADcqFExGAmxRvAsqEA

In the following code I get an error on my `clone` call:

    /* @flow */

    class A {
      get clone(): this {
         return Object.assign(Object.create(this), this)
      }
    }

    class B extends A {}

    var b = new B()
    var c = b.clone

I get an error: Covariant property `clone` incompatible with contravariant use in call of method `assign`.

How to annotate this, please correct my example.

**Comment by madbence** [comment]
It's not a very nice solution, but you can cast `Object.create(this)` to any. the `clone` getter is still going to have the right signature (it will return `this`), and no unsafe `any` will be leaked.

btw why are you using `Object.create(this)`? `Object.create(null)` or `{}` would be enough.

**Comment by alinex** [comment]
I tried all examples but neither was valid for flow:
- `return Object.assign(Object.create(null), this)`
- `return Object.assign({}, this)`

Please give me a complete example using https://flow.org/try/ how to make a working clone method which is valid in flow, too.

**Comment by alinex** [comment]
I got it working now (by casting to any):

    /* @flow */

    class A {
      get clone(): this {
         return Object.assign((Object.create(this): any), this)
      }
    }

    class B extends A {}

    var b = new B()
    var c = b.clone
