### ISSUE TITLE
flow in webstorm

### ISSUE THREAD

**Issue by ghost** [facebook/flow#4145]
why webstorm highlight the flowing code:

`
type ObjectAlias = {
    property: string,
    func : (arg?:string)=>number
};
`
![image](https://user-images.githubusercontent.com/14992986/27027674-9ea9cdf8-4f77-11e7-9a6c-bf2678a387b2.png)

**Comment by gogile** [comment]
eslint is disable

![image](https://user-images.githubusercontent.com/14992986/27133241-c1f867be-5126-11e7-9265-26e12d19f8e2.png)

as a real example when I open the parse SDK (https://github.com/parse-community/Parse-SDK-JS) in webstorm I get same error at CoreManger.js

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
