### ISSUE TITLE
Typo in lib/dom.js

### ISSUE THREAD

**Issue by zaygraveyard** [facebook/flow#4156]
Typo in [lib/dom.js:600](https://github.com/facebook/flow/blob/v0.48/lib/dom.js#L600)
`createElement(tagName: 'thead' | 'tfoot', 'tbody'): HTMLTableSectionElement;`
should be
`createElement(tagName: 'thead' | 'tfoot' | 'tbody'): HTMLTableSectionElement;`

**Comment by pronebird** [comment]
Send PR?

**Comment by zaygraveyard** [comment]
PR at #4159
