### ISSUE TITLE
gen-flow-files fails with "Error merging contexts"

### ISSUE THREAD

**Issue by faassen** [facebook/flow#4157]
I tried using gen-flow-files today on my recently flowed project. It works fine when I execute it against individual files (including routes.js, where it reports an error). But when I try:

```
yarn flow -- gen-flow-files src/ --out-dir experiment/
```

then it falls over with this output:

```
Found 17 files, generating libdefs...
Error: Failure("Error merging contexts: Failure(\"find_root: tvar 54444 not found in file .../src/routes.js\")")
error Command failed with exit code 110.
```

"yarn flow" is clean.

```
yarn flow -- gen-flow-files src/routes.js 
```

also produces the flow file.

I wish I could give a better bug report but so far I have no idea how to reproduce it without the whole of my project. I am reporting it in the hope that the error message gives somebody a clue as to what might be wrong.

**Comment by agentcooper** [comment]
`gen-flow-files` is very buggy at this point. If you want to publish your declarations to npm, [`flow-copy-source`](https://github.com/AgentME/flow-copy-source) is more reliable.

**Comment by TrySound** [comment]
gen-flow-files is removed. A replacement is coming soon.
