### ISSUE TITLE
setState/$Shape play very inconsistently with React$Element

### ISSUE THREAD

**Issue by acrylic-origami** [facebook/flow#4162]
I had always thought that `React$Element` was a pretty weak type since, unlike `React$Component`, it doesn't look to be generic on the prop, state or defaultProp types. However, trying to store some elements in state has produced some unexpected errors that almost suggest that `setState` or `$Shape` peer into `React$Element` props?

[This is the base case of the error.](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IqdMQM6egBissUIQAeOQgDsAJjyJkcAOgDC1TOIl4A3olCh0VdJwBcoLToCQkAcfEBXVACNCWbaAC+rHZxzExx06DNCaEJjAH5ZcgASAFFg1HUAHgAqAD4XdxdOakIAfQALYilgrAAKUlgpZBxkCuN7AWgASmMAN1hkSRMXHWRIMorJKprxRu6dUBw85E55TkIcAGVvMRKNIWDjBMGW0GAUt0aPcaC5sZ1J6dn5pZ9CVfWQ0ASAIWIsUHs3gF4NABYAJlcu32rkO6UQrjYHG4oFe7xEYikMkYCmUGAq6i6Oj0sAMfjGnyw1jsjmcOgyriAA) However, if I replace `Bar` with `Foo` (the self class), [the error disappears](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IqdMQM6egBissUIQAeOQgDsAJjyJkcAOgDC1TOIl4A3olCh0VdJwBcoLToCQkAcfEBXVACNCWbaAC+rHZxzExx06DNCaEJjAH5ZcgASAFFg1HUAHgAqAD4XdxdOakIAfQALYilgrAAKUlgpZBxkCuN7AWgASmMAN1hkSRMXHWRIMorJKprxRu6dUBw85E55TkIcAGVvMRKNIWDjBMGW0GAUt0aPcaC5sZ1J6dn5pZ9CVfWQ0AT+QUtYAF4NABYAJldd-auQ7pRCuNgcbigABCxCwQlEEmkBEYCmUGAq6i6Oj0sAMfjG9lh1jsjmcOgyriAA). In fact, it seems if the self class is set anywhere, even in an unreachable block [the error disappears](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IqdMQM6egBissUIQAeOQgDsAJjyJkcAOgDC1TOIl4A3olCh0VdJwBcoLToCQkAcfEBXVACNCWbaAC+rHZxzExx06DNCaEJjAH5ZcgASAFFg1HUAHgAqAD4XdxdOakIAfQALYilgrAAKUlgpZBxkCuN7AWgASmMAN1hkSRMXHWRIMorJKprxRu6dUBw85E55TkIcAGVvMRKNIWDjBMGW0GAUt0aPcaC5sZ1J6dn5pZ9CVfWQ0ASAIWIsUHs3gF4NABYAJlcu32rkO6Uy2RysEmTnyhUkxRKzVAbQ6XXGoF6JUgxGgc1GGPOUxmc0WyzuayCjwS-EEllgPwBQL2ByOrkQ7PYXB4r3eIjEUhkjAUygwFXU6N0+iMkp0nyw1jsjmcOgyriAA). I don't really know what to make of it; is there something about the React rendering pipeline going on here that I'm missing?

**Comment by awestroke** [comment]
`*` means the generic argument will be inferred statically. 
The generic type argument specifies the type of the props we send in.
If you do not send in the exact same props each time, you will have to specify `any` or some kind of union.
`ele: ?React$Element<any>` works.

**Comment by acrylic-origami** [comment]
@awestroke I figured there was some behind-the-scenes magic with `$PropsOf` [right?]. I can't quite glean how far that goes from [this comment](https://github.com/facebook/flow/blob/2f188497568ba28e8d28736f1ca7501eb9680212/lib/react.js#L100); it looks otherwise that `$PropsOf = any`. Since `React$Element` is invariant on the prop type, is `$PropsOf<any>` special-cased to match every prop type?

Are the last two examples consistent with exact prop matching? I don't see it.

**Comment by SamChou19815** [comment]
React.setState no longer uses now deprecated $Shape
