### ISSUE TITLE
"Missing annotation" error in imported file prevents further errors

### ISSUE THREAD

**Issue by tushar-singh** [facebook/flow#4164]
one.js
```javascript
// @flow
export const foo = (arg: number) => {};
export const bar = (arg) => {}; // parameter `arg`. Missing annotation
```

two.js
```javascript
// @flow
import { foo } from './one';

foo(); // no errors
```

In this case `foo()` doesn't show any errors/warnings.
However, if i add the missing annotation in `one.js`, it works as expected and shows _"undefined (too few arguments, expected default/rest parameters)"_ in two.js

I doubt this is expected behaviour. Is it?

**Comment by SamChou19815** [comment]
This is probably fixed a while ago.
