### ISSUE TITLE
Module system haste appears to be deprecated, but somehow causes some regex to pass that fail in default (node)

### ISSUE THREAD

**Issue by cpietrzykowski** [facebook/flow#4167]
There are a whole pile of issues with a lot of contradictory and false information. Including issues that remain open after a year. In the same thread there are "this works", "this doesn't work".

Would really appreciate a formal/officially supported (by the flow crew) method in how to ignore "Required module not found" errors -- specifically related to webpack (non-js) imports.

Ref: https://github.com/facebookarchive/node-haste

Edit:
I've found a great writeup on the difference between haste and node module systems, https://github.com/facebook/flow/pull/1801#issuecomment-219756526

**Comment by SamChou19815** [comment]
We don't plan to document/support haste outside of FB
