### ISSUE TITLE
Union of sealed objects is failing to distinguish using a refinement property

### ISSUE THREAD

**Issue by gajus** [facebook/flow#4168]
```js
type VenueResultType = {|
  +country: string,
  +name: string,
  +nid: string,
  +url: string
|};

type MovieResultType = {|
  +blob: string,
  +name: string,
  +url: string
|};

type AuditoriumResultType = {|
  +name: string,
  +nid: string
|};

type ScrapeDataResultSetType =
  {|
    +data: $ReadOnlyArray<VenueResultType>,
    +targetData: 'venues'
  |} |
  {|
    +data: $ReadOnlyArray<MovieResultType>,
    +targetData: 'movies'
  |} |
  {|
    +data: AuditoriumResultType,
    +targetData: 'auditorium'
  |};

const doSomething = (): any => {};

const scrapeData = (
  targetData: string
): ScrapeDataResultSetType => {
  let result;

  switch (targetData) {
  case 'venues':
    result = {
      data: doSomething(),
      targetData: 'venues'
    };
    break;
  case 'movies':
    result = {
      data: doSomething(),
      targetData: 'movies'
    };
    break;
  case 'auditorium':
    result = {
      data: doSomething(),
      targetData: 'auditorium'
    };
    break;
  default:
    throw new Error('Unexpected task.');
  }

  return result;
};

let result = scrapeData('venues');
  
if (!Array.isArray(result.data)) {
  throw new Error();
}

result.data.filter(() => {
  return false;
});

```

https://flow.org/try/#0C4TwDgpgBAahB2BXCAlCBnRAbYAVc0AvFAN4A+AUFFANQDGA9ovMAE4gBcU6bAlvAHMANFVrwAhgFsIXHq37DRNeLwAmsvoJHUaiVlg3zBFMgF8A3BQqhIUALIMAbr1QZseAlGLklAIywMvoYK2mJSMtyaijp6BpFGAiYWVjbQAIKIqrzADPKIkmiYOPi23pQ6EtLBWkoq6vEKSZbWngDKdKzikAAi4sDihe6tEB6loj7UOqp94lwAJGjiqgDy8FggaaydIAA8cEiuRaMQAHyhOv2sAiO9-VwA5I4IyOj3omZQ5aRfUzPziys1hstuJdg5nId3CVTudaJdrsBbrMoPdJE4XK93qZPuMfrRpncoBksjk8gU3MUCLCaPCbn8UeJMtlcrx8m9qGZmox4DwoKoGK0GNJgAALBReKAACgAlFxxPAQF4TqRkhRubz0B0uhAkRLJaJaYj6XJGrKoO1Oj0ZoMcMNjkrSKIsCMoKwKcBmtR0AB3bJ0EVSw1I6WO6h0cToaCPZ4Ye4cUTUN1HCUkBOTAnI-mC4ViwQy2HUIP06MHTGTKDJcu+N3iADWljDEajaIhr3j5aT7hTaeoGa4WaFI1zAnzPagRcJqPRsbTlcm1YgdYbUHDkYZTNJrMkcbTnZw3fLvfpA5zClHh-H4iudMnjJJLLZs+X1AXS9EqggADNGTh25NRawDDelA8AQMBACiWy5JK9wAKqgQAHpAdDABAqiXugtYAHT3NKy6mFYiYjHo8Cuu6liqs6wBkcmxCapaOozDBTylrhy4ULwn5SgAhJs2xYbw6B8aCkp7sAWEZtKIapoWIqAcBoEQVBrAyhRVhiRJMxYZ+vA4BAKkyg6MlkcAJFQN+WCRhReFAA

The `targetData` is being used here as a refinement property. The objects are sealed. I expect no errors in this case.

Appears to be a bug.

**Comment by gajus** [comment]
@samwgoldman Can this be marked as a bug, please?

**Comment by gkz** [comment]
We do not error here anymore
