### ISSUE TITLE
Flow with React-if

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#4170]
Hi,

I use `react-if` to conditionally render React elements. A very simple example does not compile properly because Flow is unaware of conditional rendering with `react-if`. Is there any way to tweak Flow to understand `If`, `Then` and `Else` nodes the same way it understands normal branching in code? If not is there any workaround?

Example:

```
<Container>
  <If condition={ error }>
  <Then>{ () => this.renderError(error) }</Then>
  <Else>{ () => this.renderCats() }</Else>
  </If>
</Container>
```

**Comment by TrySound** [comment]
There is not way to force flow to understand custom logic "operators".

This probably can be closed.
/cc @vkurchatkin

**Comment by pronebird** [comment]
Yeah that’s probably an edge car that would be hard to support.
