### ISSUE TITLE
Ignore optional deps

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#4171]
Please introduce a way to ignore an error `Required module not found`. I have a platform-dependent code that needs to be ignored.

**Comment by agentcooper** [comment]
I think you can use [`module.name_mapper `](https://flow.org/en/docs/config/options/#modulenamemapper-regex---string-a-classtoc-idtoc-module-name-mapper-regex-string-hreftoc-module-name-mapper-regex-stringa) for that.

**Comment by agentcooper** [comment]
@pronebird if you have `require('module-x')` you can create an empty file `empty.js` and add following line to `.flowconfig`:

```
module.name_mapper='^module-x$' -> '<PROJECT_ROOT>/empty.js'
```

Now Flow will ignore `module-x`.

**Comment by pronebird** [comment]
@agentcooper that's pretty neat, thanks. But will it ignore that for all platforms? I only need to ignore that module for certain platforms where the module is not available..

**Comment by pronebird** [comment]
Using suppression comment on `require()` produced `[flow] Error suppressing comment (Unused suppression)`. I've tried to use `$FlowFixMe` twice but it didn't suppress the suppression error.

**Comment by pronebird** [comment]
Hey guys any progress on this? Kind of annoying, I have two modules now and it's still the case. I have flow annotations for the optional module so I don't want to ignore it. I'd like annotations to work.
