### ISSUE TITLE
property `key` of object literal. Property not found - when using react cloneElement

### ISSUE THREAD

**Issue by rosskevin** [facebook/flow#4172]
[Example with v0.48](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeaA2EAdkgKL5IhJEwC+cAZlBCHAORSoZsBQoksODACeYJLnKVqdRs1YcuMXjzTEAzvADK-CnAC8cABRhmYNQC5ctAJT6AfLh5w4nGAFcoRI0+dwAPAAmwABudgwQEH4A9EGhPtY8tDzJAIJQUCjCAHRMLIZpGcKGAMzW1lkgKGCGhsEo+G5I2MBEAUgAHrZ6dj4ExGQUVDSGftrgFFF22Dg+zgDWSMKWLW3tmD4269ZAA) - was not an error in 0.46, but started in 0.47.

```
12:   cloneElement(<Simple/>, {                              ^ property `key` of object literal. Property not found in
12:   cloneElement(<Simple/>, {
                   ^ props of React element `Simple`
```

```js
import React, {cloneElement} from 'react'
import type {Element} from 'react'

const Simple = (props: {}) => {
  return (
    <div>foo</div>
  )
}


Array.from(Array(3)).map((value, index) =>
  cloneElement(<Simple/>, {
    key: index,
  }),
)
```

**Comment by asolove** [comment]
This works fine in v0.53. I think this issue can be closed (@calebmer).
