### ISSUE TITLE
Order matters for intersection types

### ISSUE THREAD

**Issue by Diggsey** [facebook/flow#4178]
Given these type aliases:
```
type Foo = {
  foo_type: "A" | "B"
}

type FooA = {
  foo_type: "A"
}
```

This line will validate:
`var foo: FooA & Foo = {foo_type: "A"}`

But this will not:
`var foo: Foo & FooA = {foo_type: "A"}`

The intersection operator should be commutative.

**Comment by rsolomon** [comment]
Upon testing this using Try Flow, [both lines look to validate fine](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKAzBB9USALigCIBBUqAHzICFT0BfddQ6eOc5NTHfdiQqMWAelEAVABYBLAM5QANjIB20AO4zFiqADcAhsoAm+4BCLoDAJ35wSnbgDJYCHqlxwC4c2Uot04nQArsBQwLIKmtpQKnDAFta29q7ODm4eXsS+pExAA).

**Comment by Diggsey** [comment]
@rsolomo The presence of the first line causes both to succeed. Remove the first line, or rename the variable in the second line and you will see the failure. The first line on its own succeeds.

**Comment by Mathspy** [comment]
I assume what the author of the issue meant was that this will error as expected (because the intersection should be only "A"):
```js
var foo: FooA & Foo = {foo_type: "B"}
```

But this will not:
```js
var foo: Foo & FooA = {foo_type: "B"}
```

But both of them produce the same error since [v0.37.0](https://github.com/facebook/flow/releases/tag/v0.37.0) so I am inclined to believe this is a misunderstanding of some sort from the author

@goodmind Closeable

**Comment by goodmind** [comment]
@Mathspy
https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKAzBB9USALigCIBBUqAHzICFT0BfddQ6eOc5NTHfdiQqMWAelEAVABYBLAM5QANjIB20AO4zFiqADcAhsoAm+4BCLoDAJ35wSnbgDJYCHqlxwC4c2Uot04nQArsBQwLIKmtpQKnDAFtZQAEb6Vvauzg5uHl7EvqRMQA

**Comment by Diggsey** [comment]
@Mathspy that's not what I meant, see the link above.

**Comment by Mathspy** [comment]
Oh I see, my apologises!

**Comment by SamChou19815** [comment]
now both work
