### ISSUE TITLE
Optional fields do not unify with required fields

### ISSUE THREAD

**Issue by Diggsey** [facebook/flow#4179]
This validates:
```
type Foo = {
  foo_type: "A" | "B"
}

type FooA = {
  foo_type: "A"
}

var foo: FooA & Foo = {foo_type: "A"}
```

But this does not:
```
type Foo = {
  foo_type: "A" | "B"
}

type FooA = {
  foo_type?: "A"
}

var foo: FooA & Foo = {foo_type: "A"}
```

Despite the fact that the object literal meets both criteria.

**Comment by supersonicclay** [comment]
I'm seeing the same. And they don't even need to be different types. This repros as well.

```
// @flow

type MaybeIdentified = {
  id?: string,
  name: string,
};

type Identified = {
  id: string,
  name: string,
}

const thing1: Identified = {id: 'abc', name: 'def'};
const thing2: MaybeIdentified = thing1; // This fails even though thing1 satisfies thing2's type
```

[try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWQIZoBGWAkgCZYB2KAlpLVuaALygDeioot5A-AC5QAZxQAnWlQDmAGi6gq+ALZYhoidLkBfANzJ02UBWp0GTVh3m814ybPmKVNjfa3IAxrCqjQKABZ2AIxCxjT0jMxs7NagAOT4RO6xMgrKqnGUkLG6iJ7eKL4B0gBMQgTEZJRhZpGFQTqgIKAAKgHCoJD4tNDtWABu1IWwAK5SfnXSgSL4dMJm7f52xbELmFiIQA)

**Comment by supersonicclay** [comment]
However, it appears that using `$Shape` works to unify a required property with an optional property.

```
type Identified = {
  id: string,
  name: string,
}

type MaybeIdentified = {
  id?: string,
  name: string,
};
type MaybeIdentified2 = $Shape<Identified>;

const thing1: Identified = {id: 'abc', name: 'def'};
const thing2: MaybeIdentified = thing1; // This fails even though thing1 satisfies thing2's type
const thing3: MaybeIdentified2 = thing1; // This works though
```

**Comment by supersonicclay** [comment]
Another weird workaround is to not initialize inline. This validates:

```
// @flow

type MaybeIdentified = {
  name: string,
  id?: string,
};

type Identified = {
  name: string,
  id: string,
}

let thing1: Identified;
thing1 = {id: 'abc', name: 'def'};
const thing2: MaybeIdentified = thing1; // This now works
```

[try link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWQIZoBGWAkgCZYB2KAlpLVuaALygDeiooV+AtlgBcoAM4oATrSoBzADRdQtcgH5hYyTPkBfANzJ02UBWp0GTVhwW8BaiVLkKltjQ63JoWFKBQALewEZhYxp6RnI9XwCLdidQAHJ8IgBjONkefiF4ykg43UQk2Coxbz8ZACZhAmIyShCzZjZImX8dUBBQABU-EVBIfFpoHqwAN2oS2ABXaR8SqJF8OhEzHqbpMriVzCxEIA)

**Comment by vkurchatkin** [comment]
This is expected because properties are mutable and invariant. You need to make the property invariant to make this work:

```js
type MaybeIdentified = {
  name: string,
  +id?: string,
};

```

**Comment by Diggsey** [comment]
@vkurchatkin please reopen the issue, making the properties read-only does not work:

https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBqAZggfVEgC4oAiAQXKgB8KAhc9AX3XWOnjkuTUxz44RcBAD8ZKszboAbgEMATlCFluvAGSwEfVEJGkK1NkA

```javascript
type Foo = {
  +foo_type: "A" | "B"
}

type FooA = {
  +foo_type?: "A"
}

var foo: FooA & Foo = {foo_type: "A"}
```

**Comment by supersonicclay** [comment]
Also, this makes the property read-only in the type with the optional property which is not desirable in my case... Is there a way to achieve covariance without requiring it be read only?

**Comment by supersonicclay** [comment]
Disregard my comments about wanting writable covariant properties. I see this has been discussed ad nauseam in at least this issue:
https://github.com/facebook/flow/issues/3866

But it seems that this should be a bug:
```
let thing1: Identified;
thing1 = {id: 'abc', name: 'def'};
const thing2: MaybeIdentified = thing1; // This validates, but I think it should be an error
```
