### ISSUE TITLE
Warn about unused variables

### ISSUE THREAD

**Issue by kevinburke** [facebook/flow#418]
I'm trying to test out flow by creating a single file in an existing project:
##### unused.js

``` javascript
/* @flow */

var foo = function() {
    var b;
    b = 3;
    return 7;
};
foo();
```

I tried checking this with `flow check unused.js`, and expected Flow to warn about the variable `b`, since it's not being used by anything. I didn't see a warning.

(In addition it was a little confusing that I couldn't just run Flow on a single file - I understand the default is to run it on a directory, but it would have been nice to specify a single file for testing purposes).

**Comment by samwgoldman** [comment]
This could be a neat feature, but I'd just like to point out that jslint/eslint does this already. If you can manage to integrate those into your workflow, you could get this functionality today.

**Comment by jeffmo** [comment]
Integrating these kinds of lint-oriented errors/warnings makes sense to me in the longer term, but as @samwgoldman points out -- there exist tools that do this quite well already, so we haven't focused on it too much. Right now the priority queue for the mainline efforts on Flow is a little more focused toward features that help find bugs in the program that might cause the program not to execute as expected.

I'll tag this as a wishlist feature to keep it on the radar, but unfortunately it isn't currently on the team roadmap.

**Comment by danvk** [comment]
[jsxhint][1] is a good option for projects using Flow, since it can strip types and apply all the same transformations that flow understands. Here's a [script][2] I use to lint my flow project—it also checks for missing `@flow` annotations.

[1]: https://github.com/STRML/JSXHint/
[2]: https://github.com/hammerlab/pileup.js/blob/b2efcb6eeb77df200575cf2f6299ee23712f7b7b/scripts/lint.sh

**Comment by TrySound** [comment]
I would be happy to remove eslint with its flowtype and react plugins which are used only to detect unused vars.
Also eslint errors on using object rest operator to remove props. Would be good to consider this case as valid.
```js
const { a, b, ...props } = this.props;
render(props);
```

**Comment by trsh** [comment]
+1

**Comment by rattrayalex-stripe** [comment]
I would be interested in warning about exports that are not imported anywhere in the project.

**Comment by SamChou19815** [comment]
It's unlikely that Flow will add additional syntax only lints that can be done in eslint easily.
