### ISSUE TITLE
Cast Array<string> to Array<?string>

### ISSUE THREAD

**Issue by yachaka** [facebook/flow#4180]
I wanna cast an `Array<string>` to an `Array<?string>`. Why isn't this possible?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBjOA7AzgFzAICcBLbAc1wC4wBBY4gQwE8AeE8igPjAF4wAbQDkACQCmMeMIA0YYQHU4xGABNhAXQDcmHATABbVgCNxAZXxlKNeo1ZsA-J0q8BzqgDpcMUhnEAKAEotIA

**Comment by madbence** [comment]
tldr: cast to `$ReadOnlyArray<?string>`.

If you try to cast it to `Array<?string>`, writing `null` or `undefined` would be possible, which would violate the original constraint. `$ReadOnlyArray<?string>` is read-only, so it's safe to use (you cannot write `null` or `undefined` to it). Obviously, when you use `slice`, there is no reference to that original `Array<string>`, so you can safely use an `any` cast to bypass this restriction (ie. `(((string.slice()): any): Array<string>)`)

**Comment by yachaka** [comment]
@madbence Thanks your comment.

My goal here was though to effectively push `null` to it, but with a clone (with `.slice()`).  
So I think I'll stick with `((strings.slice()): any): Array<string>)`.
But this seems a bit hacky, do you think so?

Shouldn't it be allowed to do
```js
const strings: Array<string> = ['Hello', 'World'];
const maybeStrings: Array<?string> = strings.slice();
maybeStrings.push(null);
```

As `maybeStrings` is a clone of `strings`, `strings` isn't being mutated. [Though this code throws an error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBjOA7AzgFzAICcBLbAc1wC4wBBY4gQwE8AeE8igPjAF4wAbQDkACQCmMeMIA0YYQHU4xGABNhAXQDcqLHkIBbVgCNxAZXxlKNeo1ZsA-J0q8BzqgDpcMUhnEAKAEodIxZTCytPAAcAV1wAC39sGKlgoA).

**Comment by Mathspy** [comment]
```js
/* @flow */

const strings: Array<string> = ['Hello', 'World'];
const maybeStrings: Array<?string> = Array.from(strings);
maybeStrings.push(null);
```
[This works fine](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAICcBLbAc1wC4wBBY4gQwE8AeE8igPjAF4wAbQDkACQCmMeMIA0YYQHU4xGABNhAXQDcmHATABbVgCNxAZXxlKNeo1ZsA-J0q8BDZiwB0UYnAMAKZyoASh0jFlMLKypPAAcAV1wAC39seKlQoA)

Not sure if `slice(0)` or `slice()` should allow this behaviour or forcing upcasting to be done using Array.from is fine (if the latter this can be closed)

@goodmind
