### ISSUE TITLE
if formation is error,how to resolve it

### ISSUE THREAD

**Issue by hetchzhao** [facebook/flow#4185]
![image](https://user-images.githubusercontent.com/6813909/27208494-97faddf4-5278-11e7-879f-ddab153727c9.png)
how to fix the error when code runs.can I try catch this error to resolve it?

**Comment by madbence** [comment]
_flow_ is not a runtime checker, `obj.bar` is just an invalid property access, it produces no runtime error, it just evaluates to `undefined`, so there is nothing to catch.

you can suppress the error with [`// $FlowFixMe`](https://flow.org/en/docs/config/options/#toc-suppress-comment-regex)
