### ISSUE TITLE
Cannot import module in module definition without error or warning

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#4188]
Few `wat?!` cases from my `electron.js.flow` that I think should be addressed in flow or please correct me If I do something wrong.

1. WARNING: 'EventEmitter' is defined but never used. (no-unused-vars) - That works but `wat?!`

```
// @flow
import EventEmitter from 'events'; // WARNING
declare module 'electron' {
  declare class Tray extends EventEmitter {
  }
}
```

2. ERROR: Imports within a `declare module` body must always be `import type` or `import typeof`!'

```
// @flow
declare module 'electron' {
  import EventEmitter from 'events'; // ERROR
  declare class Tray extends EventEmitter {
  }
}
```

3. OK. ERROR: EventEmitter (type referenced from value position type EventEmitter)

```
// @flow
declare module 'electron' {
  import type EventEmitter from 'events';
  declare class Tray extends EventEmitter { // ERROR
  }
}
```

**Comment by agentcooper** [comment]
`no-unused-vars` seems to come from ESLint, not Flow.

**Comment by pronebird** [comment]
@agentcooper ah good point! So weird that ESLint checks `.flow` files.
