### ISSUE TITLE
Shouldn't Flow report a mismatch between Array<Array<...>> and Array<...> here?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4194]
Flow version 0.48

`findSomething` returns an array, so calling that function within a `.map()` should return an array of arrays. However, Flow does not complain about my designation of a simple array as return value (line 12, outer `.map()`).

[Try the code](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKLGwB2eo+mxhADtgLygDaio-oAN6FcmALat8sVgC5QycQENC0ZAF8ANHwHDREqbPm1FYzOq0ChI8ZOlzkWYkzJrEAXUrU6DSIVoATAGVYU1wACz8Ac1AuAApYACMAKzkAeWTmXABKOQBBfHxFAE8AHnSkzIA+GOrBbX5nVHxaRmY2THrQADoxRVZY2PxUaEw0jNIc0HzC0vKqms7LRKSu6zF0RYEevoH0VATysYqJvILisvHcao5q3wDg0IjaSNi9g+SsrM3+EG6mf1QxEwA0kmAAbqcZhdjlcNKBiE18JDznNSJUsjVQKCwV0aLRiIpcLEEQVPp0vpYuv9AcDYtjkbNLpU4SSkVMzoyYejMdjcXQCUTWZ9KGpKEA) (**EDIT:** See revised code example link below in a comment, without the generic `Object`)

```javascript
// @flow
'use strict';

const recipe = [
    {itemprop: 'email'},
    {itemprop: 'name'},
    {itemprop: 'secret'}
];

const findSomething = (obj: Object): Array<Object> => {
    return recipe
    .map((rule: Object): Array<Object> =>
        obj.items
        .map((subObj: Object): Array<Object> => findSomething(subObj))
        // .reduce((prev: Array<Object>, curr: Array<Object>) => prev.concat(curr))
    )
    .reduce((prev: Array<Object>, curr: Array<Object>) => prev.concat(curr));
};
```

EDIT: Note that in my actual code all types that here are `Object` are concrete Flow types, three of them, that I defined with `{|...|}`.

**Comment by jesseschalken** [comment]
If you change `obj: Object` to `obj: {items: Object[]}`, you get the error you want.

It seems Flow allows you to access any property on something of type `Object` with the result being `any`, so `obj.items` is `any` and so the result of the `obj.items.map(..)` is `any`, which is compatible with `Array<Object>`.

**Comment by lll000111** [comment]
But a) I can't do that in the complete example, b) that looks pretty random and should not have any influence on the result.

**Comment by jesseschalken** [comment]
I don't know why accessing properties on `Object` results in `any`. I'm just explaining what's happening. You can call that a bug and consider this the bug report for it if you want.

> Also, it does know it's an array that creates an array => array of arrays.

No it doesn't. It knows the mapping callback produces `Array<Object>` because that's what you wrote, but it doesn't know that you're calling `Array.prototype.map` because `obj.items` is `any`, so the result of the method call is `any`.

**Comment by lll000111** [comment]
> No it doesn't. 

Yes it does. It maps over an array calling a function that returns an array. That creates an array of arrays.

**Comment by vkurchatkin** [comment]
This code looks perfectly fine to me.  Can you come up with a simpler example and without `Object`?

**Comment by jesseschalken** [comment]
> Yes it does. It maps over an array calling a function that returns an array. That creates an array of arrays.

Please actually read what I write before sending a response:

> it doesn't know that you're calling `Array.prototype.map` because obj.items is any, so the result of the method call is `any`.

Change `map` to `mpap`. It still passes. It doesn't even know the object you're calling `map` on is an `Array`.

**Comment by jesseschalken** [comment]
@vkurchatkin His problem is just a more complicated version of [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKLGwB2eokhtAJgMqwC2muAFswHNQAXlAAKWACMAVgC5QAeRmZSAShEA+UAG9EoUFOkA6SdACGvE7GtH4Z+-coBfSkA).

**Comment by lll000111** [comment]
@vkurchatkin I did, see comment just above yours.

**Comment by jesseschalken** [comment]
Ugh, okay, you've edited your comment. Nevermind.

**Comment by jesseschalken** [comment]
Your new problem is that `obj[rule.itemprop]` is `any`, because for some reason indexing into an object without an index signature produces `any`.

**Comment by lll000111** [comment]
Just to say this too, of course the code is nonsensical at this point since without more code executing it won't lead to any good result. I simply cut all code from my actual code until I could still reproduce the error but looking at *just the types* that was wrong. Flow won't try to run the code after all. But if necessary I can make the example much larger so that when it executes it produces something. That should not be necessary?

**Comment by lll000111** [comment]
> Your new problem is that obj[rule.itemprop] is any, because for some reason indexing into an object without an index signature produces any.

Indeed, I see. That sucks. 

I tried this: [Code link](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKK4CeADtgPIBGAVpqQEqrSbqgBeUAG8APolCTQhXJgC2dfLDoAuHAUIA7AOaJRAX0rV62AILFifdC1aCR4qaFoM1yc5fTpkAGglTYbBy4apyYkJj4mJqWNr6O2vgAhpq4APxqpvhJNAA8oeGR0Zg2AHx6hlTO2PkRUTFsdmJ+klWuNYWWPs2gkQV1mGp4RDpxUriJ+NqYuAAqJoMaI92EACYLw9q+BkZVoACyNDZBcwz8Qu5WNqCioO39NkbEsJp4PRyEDHYA2t3CMvKKZSueSJQjQZD6UaSP6yBRKVSgZCaRJyTAQqEif5woGIrDESJkfSIAC6j2er0gWhWAGVYKjcAALLTaOwACgCrDUByOpBOfAAlBksolcnciqVBCURN0Cah8Jo3sQPphugA6OSJOis1n4HgDUA83DcXjoQWgTLZPJhWrithSgRS4TdRyESCgVkWkWqwjoT00dlsL663je2GAujE-n86WOWNSWXy0AcoN60MA+HE51x0DqzXa9CoZg2LmHQK8kymoWWsX1Vj2qWUzQ0unTJk6VkFotsKOUbOxkA5yIrVCWbWKTAANyrIpyhpK3lAxDl+GnuTn0YdoHHE9VT2iiVwrKXWSjWck+lAmGgWBjffj0zlCq+pLPoCJjn0-LVQ5HmDHkSnc1hVFa0OmKO0F2PFcgOrUD7jtDcpW3XdnmIA8j2XHtEAqIA) (wrapping it with `Array.isArray()`), same result. It should at least use the "it is an array" information I'd say.

**Comment by SamChou19815** [comment]
Expected since Object is any
