### ISSUE TITLE
`export default const...` as described in the docs fails

### ISSUE THREAD

**Issue by popham** [facebook/flow#4203]
The export statement `export default const myNumber = 42;` from [docs/types/modules](https://flow.org/en/docs/types/modules/) yields an error for all of the Try Flow tags that are exposed:

```
    1: export default const myNumber = 42;
                      ^ Unexpected token const
```

According to 15.2.3.11, `export default` with an `AssignmentExpression` is admissible.

**Comment by popham** [comment]
Work around:

```
const myNumber = 42;
export default myNumber;
```

**Comment by jeffmo** [comment]
`export default` Doesn't permit a statement, only an expression. It does support a "HoistableDeclaration", but that consists only of a function or class definition.

**Comment by jeffmo** [comment]
(Note that `const myNumber = 42 ` is not a `AssignmentExpression `, it's a `VariableDeclaration` which is a statement)

**Comment by popham** [comment]
10-4. Thanks. I'll PR a fix for the docs at some point today.
