### ISSUE TITLE
$ElementType works incorrectly with unions

### ISSUE THREAD

**Issue by vkurchatkin** [facebook/flow#4211]
[Example](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AuAueBtAdgVwFsAjEGAGngGdUYBLHAcwF0BuAKFQE8AHBAFXgBeeABIAohBAEQOVHx4gAPF14B7AGZoKABngAfeAEYAfOzahIsBMhhJMfMwApEmfMVL6qNegwCULeAB6QPgAeQBpCjBVGDgwVDY2RwBydVVVZPt-IJCxWJiKemjY8ATzcGg4JBQAD0xqOkZ4ADJ4NxIYJzr4Pmzg+AB3GIBrSkSgA):

```js
declare var t: [number, string];
type T = $ElementType<typeof t, 0 | 1>;
declare var v: T;
(v: number | string); // OK, correct

('foo': T); // Error, incorrect

declare var x: string & number;

(x: T); // works
```

`T` is expected to be equivalent to `string | number`. Instead it works as `string & number` in upper bound position.

**Comment by Bannerets** [comment]
`$ElementType<O, T | U>` works as a normal union after explicit conversion:

```js
type O = { a: 3, b: 's', c: 5 }

type T = $ElementType<O, 'a' | 'b'>

declare var t: T;

;(3: T) // error
;('s': T) // error

const a = (t: 3 | 's') // ok

;(3: typeof a) // ok
;('s': typeof a) // ok
```

https://flow.org/try/#0C4TwDgpgBA8lC8UDeUCGAuKBmANFARpgOQDOReAxpgKxQC+AUA6JFACoJQAkAogDYQAthAB2wNuAgAeGHiKoiUAD5Qi+IgD4mAEwgU+qAE7QAbkajBMbANxNrACixWAlFAD0bqBEOGA9oYYHUiIXd09vPwCGCl8REmA0TntLbGVVMlcPKF8AaztHTBYIXwAzNEzPXMD7YMLJUvKw7JygA

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
