### ISSUE TITLE
Battery consumption question.

### ISSUE THREAD

**Issue by TheBox193** [facebook/flow#4212]
I'm using Atom 1.18.0 with Nuclide 0.232.0 and Flow 0.46.0.

Any thoughts on battery consumption when running flow? I'm not sure where to start debugging.
![image](https://user-images.githubusercontent.com/220755/27345919-face4d4a-55b0-11e7-8f1d-e9c9cd7ff889.png)

**Comment by asolove** [comment]
Huh, interesting. I know there used to be issues where multiple flow servers could spin up and just sit in the background. Is this still happening for you? Can you check your activity monitor and see if you have lots of node/flow processes sitting around?

**Comment by TheBox193** [comment]
This seems to be a non-issue for us now. For anyone else that finds this thread, from what I recall we had a circular dependency that hurt Flow's performance significantly. Tracing it down may have been our fix. However I could be mistaken. 👍
