### ISSUE TITLE
Incorrect types when using reduce on an array of typed Objects and an Object accumulator whose values are Promises

### ISSUE THREAD

**Issue by eduardoramirez** [facebook/flow#4214]
I encountered an issue while reducing over an array of typed objects with an accumulator that is an object of strings to promises. A naive example of this:

```javascript
type MyType = {
  x: boolean,
};

function foo(): Promise<number> {
  return Promise.resolve(1);
};

[{x: true}, {x: false}].reduce((acc: {[string]: Promise<number>}, b: MyType): {[string]: Promise<number>} => {
  acc['key'] = foo();
  return acc;
}, {});
```
(The flow try for the above is [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCyWAKrgQLxgDeqYYAHgFxgBGccMeAhgHYA0qAL4BudFACuvAMYYAlnF5goHABQBKFgAUATnAC2cgM54APLwn7WeHQD4adMDrwYJOpboPG8AOmdHOADc8VQBGdTFRdFQAbWpmMAwdCTwhfhoEqG4YEyEAXT88ABMJaRDVbhZqGKMkuV4AczztPUMTc0trOzS2FmIyfE0aGrrG5rBPNrMLKxtbITAKe1p6bhiAcgBrPCx1vMXlNQjHZ1d3MG5I9OohY6A))

the above causes a compile error saying that the type of `x` (`boolean`) is incompatible with `Promise<number>`. It somehow thinks that the type of the value in the object of the accumulator should be the type of the value of the object of the current element in the reduce function, which is incorrect. The accumulator is assigned to the return value of a function that returns `Promise<number>` not `boolean`.

Looking further, it seems like its an issue when the reduce function returns an Object accumulator whose value is a `Promise` and the collection is a typed object. So the most basic case (which also throws a compile error):

```javascript 
[].reduce((a: {[string]: Promise<number>}, b: {y: boolean}): {[string]: Promise<number>} => {
  return a;
}, {});
```
(The flow try for the above is [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBtAugOgE4CmAJgK4DGBAFJQIYBcYA3hgM4AueAlgHYDmWDAAp44AW04sCAHm4lRAIwJ4AfAF8ANGHkNGATwby4cGARrdVASh2sOPfkJHjJMuYpWqwAXmVNUASEI2EjxuMBoAblQNJktIoA))

Moreover, when reducing over basic types it works fine

```javascript 
[].reduce((a: {[string]: Promise<number>}, b: boolean): {[string]: Promise<number>} => {
  return a;
}, {});
```
(The flow try for the above is [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBtAugOgE4CmAJgK4DGBAFJQIYBcYA3hgM4AueAlgHYDmWDAAp44AW04sCAHm4lRAIwJ4AfAF8ANGHkN5cODAI1uASgbN2XPgLDCxE6bIVK1YALzKmqMGEJsSebjAaAG5UDSZVY2CgA))

cc @iraAlor

**Comment by goodmind** [comment]
Fixed in https://github.com/facebook/flow/commit/9edb45d7955f514fd4110cb9a035a3637bf28f43
