### ISSUE TITLE
$Keys types values missing in autocomplete

### ISSUE THREAD

**Issue by kylpo** [facebook/flow#4215]
Using Atom's Nuclide and vim's vim-flow, autocompletion does not show values for a type created from `$Keys`.

Below shows the `Explicit` type popup **working as expected** in Nuclide:
<img width="410" alt="working-popup-of-type" src="https://user-images.githubusercontent.com/720177/27366015-3ce0f0c4-55f8-11e7-83fe-14df18fd07a6.png">

Below shows `From$Keys` **not working as expected**. There aren't any autocompletion values for `From$Keys`:
<img width="544" alt="empty-autocomplete" src="https://user-images.githubusercontent.com/720177/27366032-5d501db2-55f8-11e7-9fac-0b143efef94c.png">

After finding a similar issue (https://github.com/facebook/flow/issues/2588) and PR (https://github.com/facebook/flow/pull/2965) with `$Exact`,  I believe `$Keys` is not yet implemented for autocompletion. This line and the comment above it look relevant: https://github.com/facebook/flow/blob/master/src/typing/type_printer.ml#L249

[Here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHjjAJYDG5GYAvGAOQASAko2AD5MBCAmoUbpgwMAGUAFogDOYbPjBwAdmCkA3PACdUlZdNqUAXEVIVqtBi3bode2gGEA8gBlHAJXpgA3qjBgAYgCsxowAxFCBERGMADS+YPb2IaGUqWmxqAC+6PIE-ppwALYAJADSeFiyDGUV0gA8uXBQCS7uAHzCogAmcHiylACGGJQSchLksloFmjFg0nAB8EgIcJoA1tK2SvpgAEbG+UU1lZ6MSnAYALRqAxRdl1Crl7lCqCJ7AK60PX1gAHKOAAqcykSFyihU6i0Wx2AwOBRK5ROliCr3eAyUXTAP1kAOB0lBclwBGUYAGXyKZDwGDwb1Eum2BnhRyRVTAqCAA) is the code in flow.org/try

**Comment by Peeja** [comment]
Does autocomplete ever give you completion for literal values? I'd love it to, but I haven't seen that happen in any context yet.

```js
type Foo = 'Bar' | 'Baz';
const f: Foo = <{Insertion Point}>
```

In Atom, Flow doesn't appear to provide any completion for the above.

**Comment by a7madgamal** [comment]
any workarounds? I REALLY need this :(
