### ISSUE TITLE
type with Maybe props doesn't allow type with Non-Maybe props

### ISSUE THREAD

**Issue by MoeSattler** [facebook/flow#4216]
Why does flow throw errors here?        
```
    type MaybeProp = {
      prop: ?number,
    }
    
    type DefinetlyProp = {
      prop: number,
    }
    
    
    const requireMaybe = (u: MaybeProp) => console.log(u)
    const requireDefinetly = (u: DefinetlyProp) => requireMaybe(u)
```

https://flow.org/try/#0FDAuE8AcFMAIFkCG4BG0AKAnA9pWBeWAb2Flkh0gC5YB+AOwFcBbNTAGmAF8QIZYAItABmAS3rRQAG3BZcBYqXKUaTVtA7cQwAMbZ6AZ1CxM0AI6NRppKjiEAFIxo20cyAEoCAPlh7D2KWgAOilsAHNHd119IxNzS1MhMQlpcAVHGiTxSRk3T3wfUwsraBdoSKA

It seems like that a function, that can handle maybe properties, should also be able to handle the same properties when they are definetly defined.

Any way to work around this?

**Comment by madbence** [comment]
define `prop` in `MaybeProp` as _read-only_, ie:

```js
type MaybeProp = {
  +prop: ?number,
}
```

If `prop` is not read-only, `requireMaybe` would be able to assign `null` or `undefined` to `prop`, which would violate the `DefinetlyProp` constraint in `requireDefinetly`. read about variance more [here](https://flow.org/blog/2016/10/04/Property-Variance/).

**Comment by MoeSattler** [comment]
@madbence makes sense, thanks!
