### ISSUE TITLE
Incorrect location with angry emoji 😡

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#4219]
http://astexplorer.net/#/gist/d99bf2869de5ec632838bb1ce8921357/34caa181cf7ef3a65bd2df7efb4d564a6a97c6cd

![image](https://user-images.githubusercontent.com/197597/27410508-e5dfb224-569c-11e7-8e76-95de04092b47.png)

Found in https://github.com/prettier/prettier/issues/2091

**Comment by markbrouch** [comment]
```js
// 🚧 TODO: Fix this bug please 😛
```

**Comment by TiddoLangerak** [comment]
I'm not so sure if this is actually a bug in flow: the ranges flow give are correct if you interpret the file as UTF-8. Most likely the issue with both prettier and AST explorer is that they use JavaScript to parse the code, and JavaScript uses UTF-16 to represent strings. An emoji in UTF-16 has a length of 2, while it has a length of 1 in UTF-8. So I don't think this is necessarily a bug in flow, but more so a disagreement on which character encoding to use when parsing JavaScript files.

**Comment by vjeux** [comment]
Flow, in this case, is used as a parser for JavaScript and outputs an AST that is consumed by JavaScript. The expectations to me is that it adopts JavaScript's decision of what the length of strings is. Especially when every other parser (since they happened to be written in JavaScript) use UTF-16 lengths.

I understand that it's probably painful on your end to support this as flow is written in OCaml and UTF-16 support is probably uncommon.

**Comment by SamChou19815** [comment]
This seems to have correct location now.
