### ISSUE TITLE
Flow should output an error for dynamic properties added to a exact object types

### ISSUE THREAD

**Issue by julienw** [facebook/flow#4222]
See the following code:
```javascript
export type Filter = {|
  property: boolean,
|};

const filter: Filter = {
  property: true,
};

const str: string = 'PROPERTY';

filter[str] = false; // NOK not found
filter['PROPERTY'] = false; // OK correctly found

// My real-life issue
switch(str.toLowerCase()) {
  case 'property':
    filter[str] = false; // NOK should be an error, but it isn't
    break;
}
```
[See live result on try](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBiBLANjYU4C8cA3gD4BQccYUEKsiAXHAEYQRbACGAdgDTlSAXwDc5cgGMIPAM7wAZtlxRmmHHkIlK1WvSTMYUAK7ABo8VNnw5KuDYw8A5poDkABQBKAeTcBRDwAqAJouYuSK6lAA2jYAupryXFgywCJwAPTpcDwQChBGPAAm4Up4Ue7efoEh8USJyakZWVJQUMASMFiIcPL5ReKZcACy3W1JALRYGPKoGDIyJuQyAO4YMBIAFgAUNgB0MBAAMhDLeADCXClbAJTXWlQSl6guNHR4SC6M2lQRyjGGtR6SRSaUGMg2+SwhVYqF4cDwtCgfFYRngazgcx4Lhg31YYwA1mIhOQgA)

**Comment by asolove** [comment]
It's definitely possible that exactly-typed objects should just not allow using the `[]` syntax at all. But given that it allows it sometimes, there's not much it can do to distinguish safe from unsafe uses on arbitrary runtime strings.

I'm more curious if we can help cover this code with types in some other way. For example: why do you use the square bracket syntax (dynamic property setting) when you have just looked up the value of the key and could just say `filter.property = str`? I'm sure the real code is more complex than this and so there's a good reason for it. If you can share more about that code, maybe we can come up with a creative solution so everything is safely covered by types.

**Comment by julienw** [comment]
It was some months ago :) but I think it was sharing the same body for different cases, something like this:
```javascript
export type Filter = {|
  property1: boolean,
  property2: boolean,
|};

// ... str could be "Property1" or "Property2".

switch(str.toLowerCase()) {
  case 'property1':
  case 'property2':
    filter[str] = false;
    break;
}
```

I was in the middle of refactoring something and I rely on Flow (probably more than I should :) ) to give me the places where I missed something. In the case here I missed that `str` could have any case and not just the specific case I wanted. I was surprised that Flow didn't error on this.

**Comment by SamChou19815** [comment]
This now errors.
