### ISSUE TITLE
Implicitly-returned undefined when using string enums

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#4224]
Switchthat covers all string enum keys and returns in each case should never complain about implicit undefined returned from a function. 

Currently it throws a validation error:

> getStyle(): Style {
> ^^^^^ string enum. This type is incompatible with an implicitly-returned undefined.

There is no way this function returns undefined if each case returns a value and switch covers all cases.

```
  export type ConnectionState = 'disconnected' | 'connecting' | 'connected';
  
  // ...

  props: {
    status: ConnectionStatus
  }
  getStyle(): Style {
    switch(this.props.status) {
    case 'connecting':
    case 'disconnected':
      return 'error';
    case 'connected':
      return 'success';
    }
  }
```

**Comment by popham** [comment]
Known issue: https://github.com/facebook/flow/issues/2400. There's a quirk that I've noticed where returning the refined variable silences the error and notices when the switch is non-exhaustive, e.g.

```js
export type ConnectionState = 'disconnected' | 'connecting' | 'connected';
export type Style = "error" | "success";

const k: {
  props: {
    status: ConnectionState
  },
  getStyle():Style
} = {
  props: {
    status: "disconnected"
  },
  getStyle(): Style {
    const status: ConnectionState = this.props.status;
    switch(status) {
    case 'connecting':
    case 'disconnected':
      return 'error';
    case 'connected':
      return 'success';
    }
    return status; // no error, and add another member to 
                   // `ConnectionState` and observe the resultant error
  }
}
```

(I unexpectedly noticed that `this` was any-typed in the body of `getStyle`, hence the assignment+cast.)

**Comment by popham** [comment]
A `default:` also suppresses the errors. I've avoided this solution because I want errors when `ConnectionState` gets more members added, but I just realized that a `(status: 'connected');` statement can assert that `default:` contains one and only one possibility, e.g.

```js
switch(status) {
  case 'connecting':
  case 'disconnected':
    return 'error';
  default:
    (status: 'connected');
    return 'success';
}
```

I think that this is a better work around.

**Comment by pronebird** [comment]
@popham sounds like a good workaround. Btw, shouldn't it report that the switch-case does not cover all of the possible combinations in case when new values are being added to the enum?

**Comment by popham** [comment]
It will report these missed cases. [Try it](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDCEB2ngGMYCWWAyjAIYyoC8cA5ACYEDOuWO+w9tcAPna9jyFMAc259aA9pS686ZJvQBmtANwAoUJFgJkqUogA21OACJgUKNFNzTTAK65cwJk1Mb1ApvADWALjgAb3U4ODArMCYA4NDQ7wp7KPQ2ISJMUgpgELgAXwAabJFgGANjAAoASj9SrJy4GhiwiKTGuPIYRIDTRhYUjnpTbPzC4prKgJqg7NCveHiOpIxBfDSMynqEAAtmADpwiEid+cSNWLgmAHcCGFxNuDLjpgqps9wFVEk+4TE-abg3pgfHpSIScWi-M6hKDFexQTB0CxWKBqP70YBKMj2QwwCGQh7tTr8L5giqnSHQjpwugOJwuJgos45IbqHJAA). The error message is somewhat obscure if you don't recognize the pattern, so I would recommend a comment in the code.
