### ISSUE TITLE
Map.get() flow check fail

### ISSUE THREAD

**Issue by netmindms** [facebook/flow#4226]
The following sample code causes a flow-check error.
I can't any information for this error.
```
class UserDb {
    userMap: Map<string, string>;
    constructor() {
        this.userMap = new Map();
    }

    getUserGam(id: string) : string {
        return this.userMap.get(id); //  ==>  Flow check error is caused by this line.
    }
}
```
Anybody help me ?

**Comment by agentcooper** [comment]
Get type signature is [`get(key: K): V | void;`](https://github.com/facebook/flow/blob/fa77d91c52ecc68d17ff0c82c94613abbb10499b/lib/core.js#L601). If you want to keep `string` as a return type of `getUserGam`, then you'll need a default value:
```
getUserGam(id: string): string {
  const user = this.userMap.get(id);
  return user || "default";
}
```

**Comment by netmindms** [comment]
Oh Thanks. It works.
