### ISSUE TITLE
False positive for React props with exact object type.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#4231]
https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYCg20AbFAZ17gAxCBDhIAHjDIATAQSKlyuNnDhg6YXgC5cAHxWq4AIxRQdxAK4gjSKAd0UDqg82LTbACgCUyw3GYwFlDEcB5OhgA8wqImUAC8OADMVAD0AHzhXgaOFEA

Expected: no errors.

It is necessary to remove the exact object type in order to work.

**Comment by lydell** [comment]
This seems to be working in Flow 0.53: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24A2a6AYhBHFgB4xYB2AE3TY8MAHQBhEpD78YAHgDeAHxpw4AI2RQAXHD4BXEBqxQaygL4A+OIrXq49yoNMAKAJS376yjANQ+OFdvB3k2Di0oAF5FAGYLOAB6KxD3ewsaCyA

**Comment by asolove** [comment]
Yeah, this was allowed by the improvements in 0.53. I think we can close this issue.

**Comment by AndrewSouthpaw** [comment]
Thank you! Closing.
