### ISSUE TITLE
React component function props don't check function type signature

### ISSUE THREAD

**Issue by jergason** [facebook/flow#4236]
When declaring props on React components, Flow doesn't seem to be checking the type signature of function props.

Here is an example.

```
/* @flow */
import React, { Component } from 'react';

type Props = {
  aFunc: (id: string, foo: number) => void
}

class Stuff extends Component {
  props: Props;
  render() {
    return <div onClick={() => this.props.aFunc('123', 123)}>wassup</div>
  }
}

function Beans() {
  return <Stuff aFunc={function() {}} />
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAwnDnAHantEC+YUeVmADkeCtWEBuVKgIBPbKTAAFQdgDOYALwNUYMOQBiAV3aUAXGAAU6ACaX1BPOnYBzOlDhxL7Y5gBGpHgAlNoAfGAAbnB2qDwylDDk6poAygTGUFBgpAAeBFy2mixsnNy6+thq6paqcBrS+mLstkFWofR6+mBiGXjsYAA8ABYAjGAcTDDolADWWvTt4WAEw+jqAHRV9ZtGppRWwqMATADMwnQnp8E8YQjJ6sbYg8BjYV3x8ahQ+wToHGAAEIUdjqJadJqkPoDQbpTLZPZmBY-Mx-Djgnh8YDvHhAA

In this example, I'd expect Flow to give an error complaining that `aFunc` is not the correct type of function, since it doesn't have the right type signature. Instead, I see no errors. Am I doing something wrong?

**Comment by jergason** [comment]
https://twitter.com/homborg/status/879718362510700544 mentions that this is apparently because of function subtyping in flow (see https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/), so it looks like this is expected, though surprising to me, behavior.

**Comment by apolishch** [comment]
Is there a recommended way to enforce tighter types in this instance?
