### ISSUE TITLE
Can't not export an interface

### ISSUE THREAD

**Issue by Hosar** [facebook/flow#4241]
**Given a normal interface:**
```
interface IMyInterface {
  doSomething(): string;
};

export default IMyInterface;
```
**I'm getting:**
[flow] IMyInterface (type referenced from value position type IMyInterface)

**Expected result**
Should be able to export the interface, so I can use it in different places (e.g. test and production code)

**Comment by TrySound** [comment]
@Hosar Did you try to use named export and how do you import this interface?

**Comment by borela** [comment]
@TrySound [`export default` is not working for interfaces or type aliases](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAsgJ6W6EnlgDeqYYAJnAMpwBbPDgAW2AOYAKAJQAuMAGccBCagC+6HLQAOFfkIAqOvAEEYGYgrABeRcokAfJSqziA2gF10eAB7a4BDjceCQArjBB+nhGumYWCqjAwGC+-oHBYRFUdAz4RGR4QA).

**Comment by TrySound** [comment]
I guess the problem here is es modules compatibility. Default is value, not live binding (getter), so semantically better prevent using types as values.

**Comment by Hosar** [comment]
it works if I use only **export**, instead of **export default**

**Comment by TrySound** [comment]
@Hosar Yep. That's what we are talking about.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
