### ISSUE TITLE
Array value swapping with destructuring does not work

### ISSUE THREAD

**Issue by petejkim** [facebook/flow#4245]
```
/* @flow */

const x: number[] = [1, 2, 3];

[x[0], x[1]] = [x[1], x[0]]
````

Causes Flow errors.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAA8AuMbAVwFsAjAUwCcBtAXTAF4wmBGAGjABM-AMwsA3OiZEmABhb9p3Fm05Se84rOVA

**Comment by madbence** [comment]
you need to add a `;` manually, because ASI doesn't work when you start a line with `[`.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAA8AuMbAVwFsAjAUwCcBtAXTAF4wmBGAGjABM-AMwsA3OiZEmABhb9p3Fm05Se84rOVA

also, duplicate of #3073 #3268

**Comment by petejkim** [comment]
@madbence Right, my mistake. I understand that this is a duplicate issue, closing this.
