### ISSUE TITLE
Flow frequently lagging, showing old status and needs restarting

### ISSUE THREAD

**Issue by xerq** [facebook/flow#4248]
**OS**: Manjaro 17.02
**Kernel**: 4.9.33-1-MANJARO
**Flow**: v0.48.0
**Node**: v8.1.1
**NPM**: 5.0.3
**Editor**: Visual Studio Code v1.13.1
**Plugin** for Flow support in the editor: [Flow Language Support](https://marketplace.visualstudio.com/items?itemName=flowtype.flow-for-vscode)
`package.json` **script** for `flow`:  `"flow": "flow"`

Hi. I'm using Flow in my projects and it's great, but I sometimes need to restart the flow by running `npm run flow stop` and `npm run flow status`(once it didn't even let me stop the server).

The reason I need to restart Flow is because it sometimes doesn't update it's status after I save a file, which is pretty annoying.

Here is a recent code that required restarting the `flow` server after saving the file:
```javascript
// @flow

class someclass {
    login: string;
    password: string;
    token: string;
}

export default someclass;
```
The output of `npm run flow status` for this was:
```bash
> somename@0.0.0 flow /home/xerq/Documents/Projects/Free/somefolder-back
> flow

src/lib/somefolder/index.js:4
  4:     login: string;
                      ^ Unexpected token ,
```

To fix this I can also just wait few minutes and the status will finally update.

The status is the same in Visual Studio Code as when running `npm run flow status`.

Also some thing that may help:
My `devDependencies` in `package.json`:
```javascript
"devDependencies": {
    "babel-cli": "^6.24.1",
    "babel-eslint": "^7.2.3",
    "babel-plugin-transform-runtime": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-es2016": "^6.24.1",
    "babel-preset-es2017": "^6.24.1",
    "babel-preset-flow": "^6.23.0",
    "chai": "^4.0.2",
    "eslint": "^3.19.0",
    "eslint-plugin-flowtype": "^2.34.0",
    "flow-bin": "^0.48.0",
    "mocha": "^3.4.2",
    "nodemon": "^1.11.0"
  },
```
`.eslintrc.json`:
```javascript
{
    "env": {
        "node": true,
        "commonjs": true,
        "mocha": true,
        "es6": true
    },
    "extends": [
        "eslint:recommended",
        "plugin:flowtype/recommended"
    ],
    "parser": "babel-eslint",
    "parserOptions": {
        "ecmaVersion": 8,
        "sourceType": "module"
    },
    "plugins": [
        "flowtype"
    ],
    "rules": {
        "indent": [
            "error",
            4,
            {
                "SwitchCase": 1
            }
        ],
        "linebreak-style": [
            "error",
            "unix"
        ],
        "quotes": [
            "error",
            "double"
        ],
        "semi": [
            "error",
            "always"
        ],
        "no-console": "off",
        "no-var": "error",
        "space-before-blocks": "error",
        "arrow-spacing": "error",
        "keyword-spacing": "error",
        "brace-style": ["error", "stroustrup"]
    }
}
```
`.babelrc`:
```javascript
{
    "presets": ["es2015", "es2016", "es2017", "flow"],
    "plugins": ["transform-runtime"]
}
```

Code that the  `flow status` was originally(before changing to correct) showing error of:
```javascript
// @flow

class someclass {
    login: string,
    password: string,
    token: string
}

export default someclass;
```

**Comment by xerq** [comment]
I have discovered that it runs much better if I run the `npm run flow server` with `sudo`.
I had similar issue with `nodemon`, which I also solved by running the command with `sudo`. The error of `nodemon` was:
```bash
[nodemon] Internal watch failed: watch /home/xerq/Documents/Projects/Free/somefolder ENOSPC
```
I googled `ENOSPC` and it means that there is no enough space left on the drive. But there is. All my partitions have at least few GBs of free space.

**Comment by tempname11** [comment]
@xerq check this issue (and my last comment there) out for a potentially better solution: https://github.com/facebook/flow/issues/1491

**Comment by xerq** [comment]
@tempname11 thanks, but apparently that doesn't work for me. The sudo method seems to work pretty well though.

**Comment by lll000111** [comment]
@xerq If it's related to watches and you are on Linux you have to use the sysctl interface to increase the nr. of available watches. I think they are limited per user. I found a few posts about this when googling for "ENOSPC" errors.

**Comment by sirpy** [comment]
i've found this might be related to exhausting the inotify resources on linux which is limited for a user vs root
on ubuntu you can change your /etc/sysctl.conf
fs.inotify.max_user_watches = 32768 (originally 8126)

**Comment by SamChou19815** [comment]
This was likely fixed a while ago.
