### ISSUE TITLE
Array access on object not an error

### ISSUE THREAD

**Issue by houshuang** [facebook/flow#4249]
Trying to access a key of an object that does not exist gives a Flow error, but trying to access it as an array does not. Is there ever a valid reason for accessing an Object as an Array? (We just switched the return type of a function from an array of two values to an object, and expected Flow to tell us which functions we needed to update, but it didn't. We missed one, and I just ran into an error now).

```
const a = {name: 'helo'}
a.nom # error
a[1] # no problem
```

**Comment by popham** [comment]
JavaScript allows you to use array access on objects. Flow has ambitions to support JavaScript "as it is," so Flow allows array access on objects. An exact type could solve your problems, but it'll take explicit annotations:

```js
const a: {|name: string|} = {name: 'helo'};
a.nom //error
a[1] //error
```

If you've been using unannotated arrays, then Flow was typing them as tuples which behave a lot like exact typed objects.

**Comment by SamChou19815** [comment]
It's now both erroring
