### ISSUE TITLE
Typing a const breaks its usage in type refinement

### ISSUE THREAD

**Issue by ericsoco** [facebook/flow#4250]
[REPL here](https://flow.org/try/#0C4TwDgpgBAYgTgVwJbCgXigbwFBSgayQDsATKALigHIAzRFKgGlygGMB7AG3bgqgGdgcYgHNsAXwDc2bKEhQAahBERgAQwBGnaBhx5CpPlQBuy1Zu1MW-CGv7sifQcKJipMjkUFRg7ALZqvnzwyKi6LAYklLT0wFZ4HNxw0XAQJFQS0tie3sAAFqIAkkQAsiAAymqcamSUIShQAD6KZupaOj7+gexZOagwAEoAqoUAKgD6ANKFAHIAIujUdKFUkgCQG2sA9FtQAO48+PxQADrsW9g7fbDDY1OzC5TOoosxK+s7UDRqSJzH5AAKDwObw2OwORb5IqlCpVGoAOki6DQGEGIwm03mUAA-D4Cq5imVKtUSPDEjwjAgiPgiOw9kRVtggA)

```
type Fruit = {
  kind : 'fruit',
  color : string
};

type Vegetable = {
  kind : 'vegetable',
  season : string
};

const tomato : Fruit = {
  kind: 'fruit',
  color: 'red'
};

const thingInMySalad : Fruit | Vegetable = tomato;

const FRUIT_KIND = 'fruit';				// works \o/
//const FRUIT_KIND : string = 'fruit';	// fails :(

const color = thingInMySalad.kind === FRUIT_KIND ? thingInMySalad.color : 'probably green?';
```

I understand that typing `FRUIT_KIND` to a `string` is, in effect, broadening the type to any string (from a string literal), and that Flow therefore cannot guarantee that `thingInMySalad` after the `kind` check is a `Fruit`. So, it makes sense that Flow would complain here.

However, this is pretty counterintuitive -- I have to intentionally avoid typing `FRUIT_KIND` to achieve type safety below. Since `FRUIT_KIND` is a `const`, it's immutable and therefore Flow should be able to use it to refine type.

At the very least, if the above is not possible, a warning would be helpful.

/cc @btford

**Comment by mwalkerwells** [comment]
A string literal is a subtype of ``string``. Therefore the type of ``FRUIT_KIND`` is actually ``'fruit'``.

```js
const FRUIT_KIND: 'fruit' = 'fruit'
```

Alternative example: A number literal is a subtype of ``number``. So ``5`` is a subtype of ``number``.

**Comment by btford** [comment]
For a `let` assignment, it makes sense that you might want declare `FRUIT_KIND` a `string`, so that you can catch future incorrect assignments.

For a `const`, this is somewhat surprising. I can't think of any case that you'd want to cast a literal string to `string`, since the literal is already a subtype of `string`.

I think it would at least be reasonable for Flow to issue a warning for `const` literals literal types manually being widened.

**Comment by SamChou19815** [comment]
now both work
