### ISSUE TITLE
mixed array errors on typed array

### ISSUE THREAD

**Issue by alex-deas** [facebook/flow#4253]
Functions with a parameter annotations with `mixed[]` error when passed a primitive array as in the following:

```javascript
const f = (xs: mixed[]) => {};

const stringArray: string[] = ['abc', 'def'];

f(stringArray); // ERROR
```

Expected that as `string[]` is part of the union for `mixed[]` that it does not error on a typed array.

[Example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjAF4wAKAD1wC4wBbAS0oFMATAbQF0BKUgPjABvAL4BudFjyEArtnwBPAA7sAggCd1AQwWkwHAORaARhgMAaMAbYsoBrhKkEGzNZp10mrTlz2GTZpbWtvaYOM4E6ozYAOYa2gp0kdEx3H5GphZWNnYOYdJg2DL0xizq8R6FxaXqaWQcAIyWAEyWAMx5qFDkcooqbBUKPGJgwMBgAPIA0l3kXm4Jw2DLY5Mz3cmxg0uj4wCiAEoHEwezRSVl2yO7YIfHp0A)

**Comment by madbence** [comment]
Use `$ReadOnlyArray<mixed>` instead of `Array<mixed>` (`mixed[]`):

```js
const f = (xs: $ReadOnlyArray<mixed>) => {};
```

see #4180 #4251 #3869 #3696 for explanation ([variance](https://flow.org/blog/2016/10/04/Property-Variance/))
