### ISSUE TITLE
get keys of object type as an array of names

### ISSUE THREAD

**Issue by pvinis** [facebook/flow#4255]
i will ask with an example. i have this.
```
type IconProps = {
  size: number,
  color: string,
}
```
and i want to be able to get `['size', 'color']` from the above.

how could i do that?

i need it in one case for example that i have a bunch of props, and i only want to get the ones for an icon, so i can to `R.pick(<insert what i need here>, this.props)`.

**Comment by vkurchatkin** [comment]
You can't create a value based on a type since types don't exist at runtime

**Comment by pvinis** [comment]
but while they are being stripped, they can replace some like `$GetKeys<IconProps>` or something, into this array i want?

**Comment by pvinis** [comment]
but while they are being stripped, they can replace some like `$GetKeys<IconProps>` or something, into this array i want?

**Comment by vkurchatkin** [comment]
Stripping is usually done by Babel, but it doesn't have access to type information

**Comment by pvinis** [comment]
so even though everything i need is there, we cannot have like a macro thing to do replacement?

how would you suggest doing that with what we have?

my example is like this
```
type IconProps = {
  size: number,
  color: string,
}

type BatteryIconProps = {
  ...View.propTypes,
  ...IconProps,
}

class BatteryIcon extends PureComponent {
  render() {
    return (
      <View
        {...R.pick(View.propTypes.keys, this.props)}
      >
        <Icon {...R.pick(<here goes what i need>, this.props)}
      </View>
    )
  }
}
```
any ideas?

**Comment by vkurchatkin** [comment]
I don't see the need to call `pick` at all, just pass all the props

**Comment by pvinis** [comment]
pass all props to both? thats not what i want. then both components have both. so they have unneeded props, and what if there is a name overlap? i prefer sending what i need to send. right?

**Comment by vkurchatkin** [comment]
> what if there is a name overlap

If there is a name overlap, then your `pick` approach would have the same result

**Comment by pvinis** [comment]
ok sure. but that's one part of what I said. what about not leaking all the props everywhere?

**Comment by CMCDragonkai** [comment]
What about a tuple of all the keys within an object. There's already `$Keys<T>`, why not `$KeysTuple<T>`?

**Comment by SamChou19815** [comment]
Yeah we do not plan to support something like this that depends on the order.
