### ISSUE TITLE
flow-bin 0.49.x not available on npm

### ISSUE THREAD

**Issue by rsolomon** [facebook/flow#4259]
According to the [flow releases page](https://github.com/facebook/flow/releases), 0.49.0 was released 2 days ago, and 0.49.1 about a day ago. Usually these releases are available almost immediately on npm, so I'm throwing this out there in case something might be wrong with the deployment pipeline.

**Comment by omerzach** [comment]
Looks like it's up now.

**Comment by rsolomon** [comment]
Issue is fixed!
