### ISSUE TITLE
Given "type T = ?{…}" how can I get "type U = {…}", i.e., "type U = T \setminus null \setminus undefined"?

### ISSUE THREAD

**Issue by omerzach** [facebook/flow#4260]
Relay generates nice Flow types for me like

```
type T = {| user: ?{ firstName: string } |};
```
.

I'd like to be able to say a component accepts `{ firstName: string }` without hard-coding the `firstName: string` in. I can use `type U = $PropertyType<T, "user">` to dynamically get `type U = ?{ firstName: string }`, but would like another operator to let me require that the object is not `null` or `undefined`? Is there anything like this? It looks like `$Diff<A, B>` almost does this, but only works when `A` and `B` are both `Object`s.

**Comment by samwgoldman** [comment]
`$NonMaybeType<$PropertyType<T,"user">>` should give you what you want.

**Comment by omerzach** [comment]
Perfect!

**Comment by madbence** [comment]
i used this until i've heard about `$NonMaybeType` :smiley_cat: :

```js
type _Definitely<T, U: ?T> = T;
type Definitely<T> = _Definitely<*, T>;

type T = {| user: ?{ firstName: string } |};
type U = Definitely<$PropertyType<T, 'user'>>;

({ firstName: 'foo' }: U);
```

**Comment by omerzach** [comment]
Should I add that to https://flow.org/en/docs/types/utilities/ or is it documented somewhere else?

**Comment by SamChou19815** [comment]
This is now documented.
