### ISSUE TITLE
$ReadOnly<> for Objects

### ISSUE THREAD

**Issue by yachaka** [facebook/flow#4267]
Hi,

As far as I know, if I check for the existence of an optional property, Flow will not complain for the rest of my function if I try to access this property. But if I pass it as a parameter to a function in-between, Flow will reset anything it infered about it.

For example,
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgZgC8YA3qmGHDhgJZwB2AhjAFxgD8AzhgE51GAcwA0qAL4BudAGMmvMAFssAeQBGAKw5FSFKjXpNWHRgFcYMMVPRRTjGYcZgAJnADKGABYAKOJoCU5JRgfHgYpnxO0uLodFBg3srqGgB0BgwsMGAAhMSkZhaBei7uXomqAdJUcozccDB4KfBC5clptBmsTXjCXv7RQA
```js
/* @flow */

type t = {
  optional: ?string,
};

const myObj: t = {
  optional: null,
};

function doSth(obj) {
  return ;
}

if (myObj.optional !== null && myObj.optional !== undefined) {
  console.log(myObj.optional.length); // No error
  doSth(myObj);
  console.log(myObj.optional.length); // Error
}
```
One solution would be to able to type the object as a ReadOnly object, like this is already the case for arrays : `$ReadOnly<{ ... }>`. This way, flow could assume nothing in the object is being changed.

Is this something planned? Do you see any other solutions?

**Comment by popham** [comment]
This is proper refinement behavior. Suppose `doSth` looked like

```js
doSth(obj) {
  delete obj.optional;
}
```

Someday Flow could pass your use case for covariant fields, e.g. `type t = {+optional: ?string};`, but it currently doesn't. And `myObj.optional != null` is adequate for your purposes.

**Comment by yachaka** [comment]
@popham The workaround seems ok for now :) Thank you.

What do you think about a `$ReadOnly<>`  utility type?

**Comment by popham** [comment]
I would use it, but I don't find the local variable solution especially intrusive.

**Comment by Andarist** [comment]
`$ReadOnly` found its way to `flow`. I think you can close the issue as it seems to be solved.
