### ISSUE TITLE
function that takes argument with multiple possible types throws error

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#4270]
```js
/* @flow */

type Props = {
  width: string | number,
};

function fun({
  width = '30em',
}: Props) {
  return width;
}
```

It complains with:

```
8:   width = '30em',
     ^ number. This type is incompatible with
8:   width = '30em',
     ^ string
8:   width = '30em',
     ^ string. This type is incompatible with
8:   width = '30em',
     ^ number
8:   width = '30em',
             ^ string. This type is incompatible with
8:   width = '30em',
     ^ number
```

[repro](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGAgJYAmGAFgPwBcYAdgFcAtgCM8xMAB8w5DMWb8A5gBpUAXwDc6KIP4BjDMzj8wu-gAp6jFuw7UwAcgDMABjzDHa9XxJlyAJR0DGDEeBiCxKa2nNrqQA)

**post updated**

**Comment by steelbrain** [comment]
It's actually correctly saying that, the repro fails on even babel parsing. [link](https://babeljs.io/repl/#?babili=false&evaluate=true&lineWrap=false&presets=es2015%2Creact%2Cstage-2&targets=&browsers=&builtIns=false&debug=false&code_lz=PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGAgJYAmGAFgFxjkbHMAdgHMwAHzCCArgFsARnmIAaVAF8A3OihTBAYwzM4gsAFksAYTgycRvIIwAKeoxbtuYAOQBmAAx4ZHiqqPCRk5ACUdAxgxHgYUsTGADyszABuvNgweFS0tExsnGCqqmDAAHxqQA)

What you want to do is
```js
/* @flow */

type Props = {
  width: string | number,
};

function MyComponent({
  width = '30rem',
}: Props) {
  return <div style={{ width }} />
}
```

**Comment by FezVrasta** [comment]
Sorry it was a typo... On my project it failing the code you provided.
I'm going to try to reproduce it

**Comment by FezVrasta** [comment]
I updated the repro fixing the typo, the correct error is shown now
