### ISSUE TITLE
Flow is unsound. Unable to differentiate between arrow functions and class constructors.

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4273]
```js
const functionNotClass = (input) => true;
(functionNotClass: Class<any>); // no errors from Flow
const gonnaTrustFlow = new functionNotClass()
// runtime Uncaught TypeError: functionNotClass is not a constructor

class ClassNotFunction extends Error {}
(ClassNotFunction: () => Error); // no errors from Flow
const gonnaTrustFlowAgain : Error = ClassNotFunction()
// runtime Uncaught TypeError: Class constructor ClassNotFunction cannot be invoked without 'new'
```

[Try flow](https://flow.org/try/#0MYewdgzgLgBAZgVzMKBLcA5EUDCAbAQwghgF4YAKVMABwSgEoyA+GKAJwQFMBuAKAqJkaTNnxEIALhjjiAHgJgAnswY8YAeg0wwIGF3bsQ7EnCMBbGADE8IAO59QkWAHNwYAgBVO0G-bI6XHbwSCjoYFi4hMQUDHxaMJxgaOZcMACqyAQILgAWsJ5KNFwAoobG0kJholESMKgkurAEME7QnCjGfI7RJLIQkVahImD6AB5QXGAAJiRlRuwwAN4AvgL9g8Ph0rEsMPPGaprauvrlJvAW1rYOba7uXj5QfnYAgi4E1DDSB4vkG9ghsJwrF4tokik0plgNk8gUiqVztJ+q1wO0EJ1FgDnltwK1FE0YAAjNLUABuIAA1lxpjA7KgoLkQPQYAByMBBVlAA)

**Comment by SamChou19815** [comment]
This is fixed a while ago.
