### ISSUE TITLE
Object spread doesn't seem to behave as expected

### ISSUE THREAD

**Issue by chrisirhc** [facebook/flow#4274]
Repro ([link](https://flow.org/try/#0C4TwDgpgBAwglqAMgewMYENh2QOygXigG8AoKKOAEwC4oBnYAJzhwHMAaMqUSWgclQIQfEgF8A3CR7QYyAK44mIFBiy4CxLlVoNmbTuWn9U8xY2FjJJEzgZR0UWvCRpM2HAG0Auho9FtUHwAjHzs3OAQxkJ8ol6SNnYARo6wpkoqbrjeGugAdAC26GAAFAAeBAB8UMVEuXWlYUaBJgpKMQCU7eJAA)):
```js
// @flow
type CityLocation = {
  id: string,
  type: 'city'
};
type CountryLocation = {
  id: string,
  type: 'country'
};

const a : CityLocation[] = [{id: '1', type: 'city'}];
const b : CountryLocation[] = a.map(x => ({...x, type: 'country'}));
```

Gives an error:
```
3:   type: 'city'           ^ string literal `city`. Expected string literal `country`, got `city` instead
7:   type: 'country'           ^ string literal `country`
```

No error from the following where it's should warn/error ([link](
https://flow.org/try/#0C4TwDgpgBAwglqAMgewMYENh2QOygXigG8AoKKOAEwC4oBnYAJzhwHMAaMqUSWgclQIQfEgF8A3CR7QYyAK44mIFBiy4CxLlVoNmbTuWn9U8xY2FjJJEzgZR0UWvCRpM2HAG0Auho9FtUHwAjHzs3OAQxkJ8ol6SNnYARo6wpkoqbrjeGugAdAC26GAAFAAeBAB8UMVERoEmCkqhULmtpaIAlB3iQA)):
```js
// @flow
type CityLocation = {
  id: string,
  type: 'city'
};
type CountryLocation = {
  id: string,
  type: 'country'
};

const a : CityLocation[] = [{id: '1', type: 'city'}];
const b : CountryLocation[] = a.map(x => ({type: 'country', ...x}));
```

---

Reproduction links (in case it was easy to miss above):
https://flow.org/try/#0C4TwDgpgBAwglqAMgewMYENh2QOygXigG8AoKKOAEwC4oBnYAJzhwHMAaMqUSWgclQIQfEgF8A3CR7QYyAK44mIFBiy4CxLlVoNmbTuWn9U8xY2FjJJEzgZR0UWvCRpM2HAG0Auho9FtUHwAjHzs3OAQxkJ8ol6SNnYARo6wpkoqbrjeGugAdAC26GAAFAAeBAB8UMVEuXWlYUaBJgpKMQCU7eJAA

https://flow.org/try/#0C4TwDgpgBAwglqAMgewMYENh2QOygXigG8AoKKOAEwC4oBnYAJzhwHMAaMqUSWgclQIQfEgF8A3CR7QYyAK44mIFBiy4CxLlVoNmbTuWn9U8xY2FjJJEzgZR0UWvCRpM2HAG0Auho9FtUHwAjHzs3OAQxkJ8ol6SNnYARo6wpkoqbrjeGugAdAC26GAAFAAeBAB8UMVERoEmCkqhULmtpaIAlB3iQA

---

This does work though:
```
const a : CityLocation[] = [{id: '1', type: 'city'}];
const b : CountryLocation[] = a.map(({type, ...x}) => ({...x, type: 'country'}));
```

**Comment by ericsoco** [comment]
[Slightly more legible repro](https://flow.org/try/#0C4TwDgpgBAwglqAMgewMYENh2QOygXigG8AoKKOAEwC4oBnYAJzhwHMAaMqUSWgclQIQfEgF8A3CR7QYyAK44mIFBiy4CxLlVoNmbTuWn9U8xY2FjJJEzgZR0UWvCRpM2PISLaofAIx92bnAIYyE+CWtcOwAjR1hTJRU3dU8AOnT0QO8-AKDeHxMFJXDJIA):

```
type CityLocation = {
  id: string,
  type: 'city'
};
type CountryLocation = {
  id: string,
  type: 'country'
};

const a : CityLocation = {id: '1', type: 'city'};
const b : CountryLocation = {...a, id: '1', type: 'country'};
```
```
3:   type: 'city'
           ^ string literal `city`. Expected string literal `country`, got `city` instead
7:   type: 'country'
           ^ string literal `country`
```

**Comment by ericsoco** [comment]
[Looks like](https://flow.org/try/#0C4TwDgpgBAwglqAMgewMYENh2QOygXigG8AoKKOAEwC4oBnYAJzhwHMAaMqUSWgclQIQfEgF8A3CR7QYyAK44mIFBiy4CxLlVoNmbTuWn9U8xY2FjJJEzgZQAZsmQai2qHwCMfdt3AR+jsh8Eta4dgBGULSyCkoqmNh4hEQAdGmBPm6e3r687iax5sGSQA) Flow is typing the object being spread instead of the resulting object (after the spread):

```
type CityLocation = {
  id: string,
  type: 'city'
};
type CountryLocation = {
  id: string,
  type: 'country'
};

const foo = {id: '1', type: 'foo'};
const b : CountryLocation = {...foo, id: '1', type: 'country'};

```
```
10: const foo = {id: '1', type: 'foo'};
                                ^ string. Expected string literal `country`, got `foo` instead
7:   type: 'country'
           ^ string literal `country`
```

**Comment by villesau** [comment]
this will fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
These examples have the expected behavior in master
