### ISSUE TITLE
Flow doesn't error on invalid static of function within the same module

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#4276]
When accessing a non-existing property on a function that is defined in the same file, flow doesn't complain. E.g.:

```js
function f(){}

f.foo.bar(); //no error
```

[On flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqJABQCUoA3ogL7KQB0kss9ARgIYBOZA3EA)

Flow *does* complain correctly when the function is defined in a different file:

```js
// a.js
export function f(){}

// b.js
import { f } from './a';
f.foo.bar(); //property not found in statics of function
```

**Comment by gkz** [comment]
Fixed 0.190
