### ISSUE TITLE
Flow cannot find property of subclass

### ISSUE THREAD

**Issue by Calamari** [facebook/flow#4277]
Given this code (see also on flow.org/try: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwwA7AJwC4qBXAWwCMBTa8sLjOS3AC7UGGAXGpgAFDQCUpLhQEALAJa4AdDTABeKtQDcXAL6oTmHPjAAhMGwAeAtpQAmBYmQpQ4ceoOorKAHMuHj4-ETEJaWoAGjAvODkPCjBcBgAHDmiZQxSwZTV1BJ1471ywIwpTdCw8Ais8NnkKFUcmekJQ-iEI8SlWtnaiJIV81Q0BphLJ8pMzWssGiXtHF3rG5rBebuFRPslJ+isRvLTM6gO2nOMQihYcKRlfIQDAzYpqNgEGakoxwsmRTKNyMQA)

```
/* @flow */

class A {
  nr: number
  
  constructor (nr) {
    this.nr = nr;
  }
}

class B extends A {
  foo: string
  
  constructor (nr, foo) {
    super(nr);
    this.foo = foo;
  }  
}

class Base {
  item: A
  constructor (item: A) {
    this.item = item;
  }
}

class Bar extends Base {
  constructor (item: B) {
    super(item);
  }
  
  bla (): string {
    return this.item.foo;
  }
}
```

It reports the `foo` property within the `bla`-method as not found:
```
33:     return this.item.foo;
                         ^ property `foo`. Property not found in
33:     return this.item.foo;
               ^ A
```

I would expect that flow can infer foo as being a string, because the item is given in the constructor as being a type of B (which is a subclass of A). Also redeclaring `item: B` in class `Bar` leads to different errors.

This makes inheritance pretty hard to implement using flowtype.

**Comment by vkurchatkin** [comment]
`item` is explicitly annotated as `A`, so it's always going to be `A`. What you can do is make `Base` generic:

```js
class Base<T> {
  item: T
  constructor (item: T) {
    this.item = item;
  }
}
```

In this case `T` is not a concrete type and is going to be inferred.

**Comment by Calamari** [comment]
Thanks for the response.
That works around my problem. But to understand it: Without generics, it was never suppose to work?

If that's the case, you can close this issue.

**Comment by vkurchatkin** [comment]
>  Without generics, it was never suppose to work?

No, it wasn't.
