### ISSUE TITLE
Flow is not type checking correctly unless I restart the flow server everytime

### ISSUE THREAD

**Issue by juanmagalhaes** [facebook/flow#4278]
When I start flow server it does the typechecking correctly but as I change my code and save it is not validating my code again unless I restart flow server.

I am using `flow 0.48.0` I am also using the plugin for vim and my OS is a Manjaro 17.

**Comment by juanmagalhaes** [comment]
Thanks to this issue https://github.com/facebook/flow/issues/4248, I found out that it is working correctly when I run `yarn flow` with sudo

**Comment by tempname11** [comment]
@juanmagalhaes check this issue (and my last comment there) out for a potentially better solution: https://github.com/facebook/flow/issues/1491

**Comment by SamChou19815** [comment]
This is likely fixed a long time ago
