### ISSUE TITLE
child_process$ChildProcess does not extend EventEmitter

### ISSUE THREAD

**Issue by bolinfest** [facebook/flow#428]
The definition for `child_process$ChildProcess` does not reflect that it extends `EventEmitter`:

```
type child_process$ChildProcess = {
  stdin: stream$Stream;
  stdout: stream$Stream;
  stderr: stream$Stream;
  pid: number;
  connected: boolean;

  disconnect(): void;
  kill(signal?: string): void;
  send(message: Object, sendHandle?: child_process$Handle): void;
}
```

As such, Flow is complaining when I invoke the `on()` method of my `ChildProcess`.

I'm not sure if there's any way to express this other than copy/pasting the methods of `EventEmitter` in to the `child_process$ChildProcess` declaration.

**Comment by popham** [comment]
Can you declare it as a class that derives from `EventEmitter`?  Check out `lib/node.js`:

```js
// TODO: This is copypasta of the EventEmitter class signature exported from the
//       `events` module. The only reason this exists is because other module
//       interface definitions need to reference this type structure -- but
//       referencing type structures defined in other modules isn't possible at
//       the time of this writing.
declare class events$EventEmitter {
  static listenerCount(emitter: events$EventEmitter, event: string): number;

  addListener(event: string, listener: Function): events$EventEmitter;
  emit(event: string, ...args:Array<any>): boolean;
  listeners(event: string): Array<Function>;
  on(event: string, listener: (data: any) => void): events$EventEmitter;
  once(event: string, listener: Function): events$EventEmitter;
  removeAllListeners(events?: Array<string>): events$EventEmitter;
  removeListener(event: string, listener: Function): events$EventEmitter;
  setMaxListeners(n: number): void;
}
```

Since `child_process` gets defined in the same module, you can change the `type child_process$ChildProcess ...` to `class child_process$ChildProcess extends events$EventEmitter ...`.  There are examples in that do that within `lib/node.js`, the same file that needs fixing.

**Comment by ssorallen** [comment]
It looks like this was fixed in commit https://github.com/facebook/flow/commit/d83c1637e4afdf0a4ce0ee3c9b913ad1c31db459. ChildProcess now extends EventEmitter.

**Comment by philikon** [comment]
Looks like this can be closed.
