### ISSUE TITLE
Support for separate type declarations

### ISSUE THREAD

**Issue by jaredloomis** [facebook/flow#4281]
I began adopting flow into an existing codebase and immediately began running into problems with formatting. I have existing code that is properly formatted without types, but when I start adding types to function parameters, the formatting quickly gets messy. I know a solution to this problem! Compare the following:

```javascript
export const findPath = (graphData: Map<PageID, Map<PageID, [Step]>>, start: PageID, finish: PageID) => {...}
```
And
```javascript
//:: findPath: (Map<PageID, Map<PageID, [Step]>>, PageID, PageID) => [PageID]
export const findPath = (graphData, start, finish) => {...}
```

The second is much clearer, and keeps the type declaration separate from the implementation (as in Haskell)

- Is there any way to mimic this without too much effort (and without declaration files)?
- Would this feature be best implemented as a feature addition to flow itself, or as an addon/library of some sort?

**Comment by borela** [comment]
[You can use type aliases:](https://flow.org/en/docs/types/aliases/#type-alias-syntax-a-classtoc-idtoc-type-alias-syntax-hreftoc-type-alias-syntaxa)

```js
type GraphData = Map<PageID, Map<PageID, [Step]>>
export const findPath = (graphData: GraphData, start: PageID, finish: PageID) => {...}
```
