### ISSUE TITLE
Flow nontermination issue

### ISSUE THREAD

**Issue by dmnd** [facebook/flow#4282]
```js
import React from "react";

type T = "a" | "b" | "c" | "d" | "e" | "f" | "g";
function enumFn(): T {}

export default React.createClass({
  propTypes: {
    mode: React.PropTypes.oneOf([
      enumFn("a"),
      enumFn("b"),
      enumFn("c"),
      enumFn("d"),
      enumFn("e"),
      enumFn("f"),
      enumFn("g"),
    ]),
  },
});
```

If I call `flow coverage` on this code it "never" terminates. It does terminate if you delete some of the `oneOf` options so perhaps superlinear complexity is to blame. Either way it causes Flow to become nonresponsive and to hit 100% CPU for a long time.

No https://flow.org/try/ link because it crashes the tab.

**Comment by zgotsch** [comment]
The memory usage of Flow also monotonically increases when merging inference for this code.
