### ISSUE TITLE
"This type is incompatible with some incompatible instantiation of ..." isn't helpful

### ISSUE THREAD

**Issue by dchambers** [facebook/flow#4285]
Flow has an error (`This type is incompatible with some incompatible instantiation of ...`, and variations of it) that provides no helpful information for understanding the source of the problem. In this regard, it's very much like IE6's much maligned `undefined is not an object` error.

It would be **really really** helpful if some tidbit of information could be provided to explain the source of the incompatibility since it's otherwise very hard (or impossible) to understand what Flow has taken objection to.

Thanks heaps peeps! 😀

**Comment by mrkev** [comment]
Looking through the code I can't seem to be able to find that string anymore. Guessing it got fixed 🙂
