### ISSUE TITLE
Question: branches in fuction types.

### ISSUE THREAD

**Issue by punksta** [facebook/flow#4286]
All function types [examples(flow.org)](https://flow.org/en/docs/types/functions/#toc-function-types) in documentation have brackets `(` `)` over argument type. But types without branches also valid.
```
type ObjectToString = (Object) => string; 
type ObjectToStringNoBranches = Object => string;
```
Is it bug of flow parser or one some examples are missing in docs?

**Comment by asolove** [comment]
I'm pretty sure this is just a stylistic choice. Prettier always uses parentheses when it goes over the code, and they stay consistent if you add a second parameter or want to provide documentation about the parameter's name.

Unless this is resulting in weird behavior, I think we can close this issue.

**Comment by punksta** [comment]
@asolove Hello. The problem is: different tools, plugins and ide can understand it in different ways. For example webstorm plugin does not support `Object => string;`. But https://github.com/prettier/prettier remove branches over type. Maybe it's good idea to provide example for both variants.

**Comment by asolove** [comment]
What does Webstorm say/do for the parentheses-less version? Sounds like a bug to file with the grammar they use.

**Comment by punksta** [comment]
@asolove perhaps. Flow has published gramar? 
![image](https://user-images.githubusercontent.com/13404754/29576267-e404a028-876f-11e7-82ec-866a711117e2.png)

**Comment by asolove** [comment]
Well, the VSCode integration at least just gets information from the flow cli about syntax and type errors. My best guess is that here, WebStorm is layering on something else, like a TypeScript grammar, or something else not-flow-specific. I don't know WS well enough to say 😢.
