### ISSUE TITLE
Imported types doesn't seem to work

### ISSUE THREAD

**Issue by richthegeek** [facebook/flow#4288]
types.js:
```javascript
export type Settings = {
  port: number
}
```

settings.js:
```javascript
import type {Settings} from './types';

let settings : Settings = {
  port: 'string'
}
module.exports = settings;
```

I'd expect this to produce an error, but running `flow` or `flow check` results in 'No errors!'

**Comment by richthegeek** [comment]
Simplifying it even further:
```javascript
export type Port = number;
```

```javascript
import type {Port} from './types;
let port : Port = 'string'
```

Still no error produced with Flow 0.49.1

**Comment by vkurchatkin** [comment]
Do you have `// @flow` on top of your files?

**Comment by richthegeek** [comment]
Ah, facepalm. Not in `types.js`...

However, I'd expect `flow` to produce an error if it can't find a referenced type?

**Comment by vkurchatkin** [comment]
I think there is an issue for that somewhere
