### ISSUE TITLE
$Diff with bound generic types

### ISSUE THREAD

**Issue by dounan** [facebook/flow#4289]
Not really sure how to describe this one, but here is an example to illustrate the issue.

The following  [works as expected](https://flow.org/try/#0GYVwdgxgLglg9mABMOcA8BBAXIg3gXwBpEAhHAgPgAoBDHDYgIxxIEocqASAERmGEzESFRAF4RANzgwAJqzwAoRIgBOAUyggVSUJFgIqEebiWJ8C8wpRwquOogCMTHAHJGLonmaI3H1rfsHfFYAbgUgA):
```
function foo<A: {}, B: {}>(a: A, b: B): ($Diff<A, B> => void) {
  return function(c) {
  }
}

foo({a: 1, b: 'b'}, {b: 'b'})({a: 1});
```

However, if you add the `$Diff` type to `c`, then [it breaks](https://flow.org/try/#0GYVwdgxgLglg9mABMOcA8BBAXIg3gXwBpEAhHAgPgAoBDHDYgIxxIEocqASAERmGEzESFRAF4RANzgwAJqzwAoRIgBOAUyggVSUJFgIqEHDz4CGpCvNxLE+BXYUo4VXHUQBGJjgDkjb0TxmRF9-Vhc3d3xWAG4FIA):

```
function foo<A: {}, B: {}>(a: A, b: B): ($Diff<A, B> => void) {
  return function(c: $Diff<A, B>) {
  }
}

foo({a: 1, b: 'b'}, {b: 'b'})({a: 1});
```

**Comment by donnanicolas** [comment]
Related https://github.com/facebook/flow/issues/4461

**Comment by SamChou19815** [comment]
It seems to work now
