### ISSUE TITLE
Property not found in data

### ISSUE THREAD

**Issue by johhansantana** [facebook/flow#4295]
Hello, I'm learning to use flow this is my second day using it and I have an error that I can't see to get fixed.

<img width="815" alt="screen shot 2017-07-01 at 5 03 03 pm" src="https://user-images.githubusercontent.com/9933887/27765457-2c6e2240-5e7f-11e7-8ff1-4913b7ea5ad4.png">

I was wondering if someone could clarify how to fix this warning?

**Comment by TrySound** [comment]
@johhansantana That's because you are trying to access data property of promise, not response itself. Promise has only then and catch props.
