### ISSUE TITLE
Tuple Disjoint Union Refinement

### ISSUE THREAD

**Issue by mwalkerwells** [facebook/flow#4296]
Taking the example from the Flow.org page...

https://flow.org/en/docs/types/unions/#unions--refinements-a-classtoc-idtoc-unions-refinements-hreftoc-unions-refinements

...and using Tuples instead of Object Literals...

```js
// @flow
type Success = [ true, boolean ]
type Failed  = [ false, string ]

type Response = Success | Failed;

function handleResponse([ success, value ]: Response) {
  if (success) {
    var value: boolean = value
  } else {
    var message: string = success
  }
}
```

...it blows up:

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMoFcBjAzAZxNAF5QBtUZAJz0wBpQAjWWaTAQwDtQAXRQZsAMR4BLbgBNQlGqEg9oJFqBINJfAOZDEIrKABKpdLD5qF+IqXIAfUBOmYZAbgOQ8fAskkXQAAt+GW5TEnNLTAAKWhJCYjJWADcVJiEALhMzCzUASlAAb0R5SUhQaPjbMgLi+XlU+lBU6CYsji5eASoWphLQAF9QTFVsOvrG0ABbOx4dTCzNem09KirEkn6BxAGgA

**Comment by egauderman** [comment]
+1 because I have heard that tuples are faster than object literals.  Is this true in others' experience?

**Comment by suchipi** [comment]
Here is another example:

```ts
// want to be able to doThing("addNumbers", 1, 2) and doThing("print", "string")

const doThing = <T: ["addNumbers", number, number] | ["print", string]>(...args: T) => {
  const [cmd, rest] = args;
  if (cmd === "addNumbers") {
    (rest[0]: number);
  }
};

// $ExpectError
doThing("foo");
        
doThing("addNumbers", 1, 2);
        
doThing("print", "foo");
```

https://flow.org/try/#0PTAEHcEMDsBdVge1AIwKakigNhpoATRAFQAsBLaAcwAoAiSAggOQFcBbdAJwGc6AaUAEZBAJgCUmaAUIkK1egAculWANB0esFdTriAUPoDGiaFtllKVUAF5QAHmIAuUAG0GTNpzS910DtyC-t5cALqgAD5udMqq6lo6VKEAfDQAdBmQXFQ8LsSSNsmgAN76oKAmZvCuRuwEglxoWuF2WTkA3GWg5ABmoDS1MjbDGowsAT58kqXl5TSNWq4ADKEuwdzineUAvvrbnfogoAAkAKIAHopoRrCnXFyIXPpElgp0PYiIeluzv89yVnoYy83D4ghEoAkP1+5X+r1oMR0akE70+330QA
