### ISSUE TITLE
Class property type check extension

### ISSUE THREAD

**Issue by borela** [facebook/flow#4297]
Consider this class:

```js
import React, { Component } from 'react'

@someDecorator
class SomeClass extends Component {
  props: {
    someProperty1:number,
    someProperty2:number
  }
}
```

Now imagine that `@someDecorator` modifies this class to expect a new property `someProperty3`, that props declaration is not available on the class's prototype, is it possible to extend that check?

**Comment by SamChou19815** [comment]
We are unlikely to support type-changing decorators.
