### ISSUE TITLE
relationship with JSDoc?

### ISSUE THREAD

**Issue by stevemao** [facebook/flow#43]
It would be great if the readme or wiki states the differences/similarities between JSDoc (or any other tools) and flow. Thanks

**Comment by cletusw** [comment]
@avikchaudhuri Perhaps this needs to be reopened since #3 has been merged and closed, but without JSDoc support.

**Comment by ianwsperber** [comment]
I agree with @cletusw that this issue should be reopened. Being able to use comments for flow types is very nice, but being able to use JSDoc syntax would make flow easily available to existing codebases. Also I still like writing JSDocs to document my functions regardless of the typing benefit, so it seems like it would be duplicate work to have both comment types.

**Comment by StoneCypher** [comment]
Please read the merged ticket.  Jsdoc docblock comments are explained there.  They went with flowtate instead.

**Comment by mhagmajer** [comment]
There is also a problem that JSDoc won't event generate docs for code with flow annotations.

**Comment by metrofun** [comment]
This feature request is like 2 years old, so is there any plans to support JSDoc or it is off the roadmap?

**Comment by cameron-martin** [comment]
I think it would be useful to have a tool to generate/augment JSDoc annotations using flow's typechecker, rather than doing it the other way round. This way, documentation could be generated using JSDoc's documentation generator, but using flow's way more reliable type information.

**Comment by tonygentilcore** [comment]
I was looking for something similar and stumbled upon https://github.com/Kegsay/flow-jsdoc . Thought I'd leave it here in case it's useful to anyone.

**Comment by jedwards1211** [comment]
The thing that frustrates me is that the syntax for `@param` types in JSDoc is different than in Flow.  I'd rather be able to put Flowtype types in my JSDoc, or that someone create a new documentation format altogether that's based upon Flowtype.

**Comment by nmn** [comment]
@jedwards1211 I think a proper flow-types codebase and the `gen-flow-files` command can just replace JSDoc altogether for types.

And, Documentation.js understands Flow so we shouldn't need JSDoc at all.

**Comment by jedwards1211** [comment]
@nmn ah, cool.  Though last I tried `gen-flow-files`/read about it in the changelog it was a pretty buggy, preliminary implementation.

**Comment by nmn** [comment]
@jedwards1211 Yeah `gen-flow-files` is still experimental, but at least its being worked on. I don't think JSDoc understanding has as much utility. Using JSDoc to add types is way less expressive than using Flow. At best, Flow should just treat leading comments before Functions as documentation. The type information doesn't belong in JSDoc.

---
@avikchaudhuri I don't think this is an important enough use-case and we should close it.

**Comment by StoneCypher** [comment]
@jedwards1211 - documentation.js has native support for flow notation

**Comment by davidrapin** [comment]
@nmn the fact that you believe that "type information doesn't belong in JSDoc" might not be relevant here.
Most JS projects use JSDoc for type annotation, because that's how you get your IDE to become helpful. That's just a fact, things are done that way, whether we think its the right way or not.

The TypeScript complier [added the ability to parse JSDoc annotation](https://github.com/Microsoft/TypeScript/wiki/JSDoc-support-in-JavaScript) some time ago, and it makes a lot of sense: pure JS projects that had JSDoc type annotations are now able to be validated by the TypeScript compiler. That's a huge step forward.

It would be great to see Flow do the same.

**Comment by jedwards1211** [comment]
@davidrapin that's cool, but I bet there ended up being a lot of accidental errors from that approach?  Because I would assume the types in a lot of JSDoc, being unchecked by a tool like Flow or TypeScript, tend to have a lot of mistakes...

**Comment by davidrapin** [comment]
@jedwards1211 Indeed, very good point. It induced some JSDoc-cleanup sessions on projects I'm involved with, but nothing we couldn't manage. It was worth it!

**Comment by sobolevn** [comment]
In my point of view, the most useful workflow is:
1. Conditionally parse `jsdoc` for types (off by default)
2. Generated stubs for this file with the parsed types
3. User can modify these types as usual

What advantages I see here:
- Possibility to fix wrong types declared in the docs
- Nothing will break by default (as it should not break because of the comments)
- We can still use existing type information

Do you see any cons in this solution?

**Comment by jedwards1211** [comment]
@davidrapin also, IDE support for flow type information was just behind relative to JSDoc.  I'm pretty sure that WebStorm already understands flow types just as well as JSDoc, though I'm not sure.  So JSDoc won't be the most ideal tool for IDE comprehension for long.

**Comment by StoneCypher** [comment]
What they're talking about is pulling the flow types into the docs so that humans can read them, not so that the documentation checker can evaluate them

it's so that we don't have to type `* @param foo {type} - bar` when that's already known

**Comment by jedwards1211** [comment]
@StoneCypher I was referring to what David said, which I think other folks are advocating against:
> The TypeScript complier added the ability to parse JSDoc annotation some time ago, and it makes a lot of sense: pure JS projects that had JSDoc type annotations are now able to be validated by the TypeScript compiler. That's a huge step forward.
>It would be great to see Flow do the same.

**Comment by StoneCypher** [comment]
My response quite clearly expresses an understanding of that.

The reason that basically every documentation generator except this one supports at least one of the type systems at this point is that nobody wants to duplicate that information for their documentation.

Please re-read what I said to you, @jedwards1211.  People should not be pushing back against this based on a faulty understanding of what's being requested.

There is a reason that every other documentation generator does this.
