### ISSUE TITLE
Request: Value of $Keys<T>, at least one to one

### ISSUE THREAD

**Issue by zaiddag** [facebook/flow#4300]
Simplest and most useful example:

```
type Record = {id: string}
let records: Record[] = []
let record_ids: string[] = _.map(records, 'id')
```
Syntax (taking from Typescript)

```
map<T, K : $Keys<T>>(records: T[], key: K): T[K]
```

**Comment by madbence** [comment]
`$ElementType<T, K>` (new in flow 0.49 afaik) is somewhat similar to `T[K]`:

```js
declare function map<T, K : $Keys<T>>(records: T[], key: K): $ElementType<T, K>[];
declare var records: Record[];
type Record = {id: number, title: string}

(map(records, 'id'): number[]);
(map(records, 'title'): string[]);
```

[flow try](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsoAHAHgBUAaeAaXgC54ASGkATwGcKA+bgCjhgcMYB0bkA2gF1qAa3aMaASkZMAohBAEQqDOTbEQFajW7SA3AChQkWAgBuseIOGjGAJXCuLljAYSeQiLwALzwAN5YwIyoyAQARiAw1NgYmowcGDBYqADmAL6WlnxExAJeIhzUAORR1SrwsQlJ0kpWJSTlQaI1qZr1GVk5ua3mQA)

**Comment by TrySound** [comment]
@madbence Isn't it called [$PropertyType](https://flow.org/en/docs/types/utilities/#propertytypet-x-a-classtoc-idtoc-propertytype-hreftoc-propertytypea)?

**Comment by madbence** [comment]
@TrySound `$PropertyType` only supports string literals as keys (you get an `expected object type and string literal as arguments to $PropertyType` error)

**Comment by zaiddag** [comment]
@madbence @TrySound Wow, very nice. $ElementType not listed in docs yet. Much appreciated sir.
