### ISSUE TITLE
use flow as header files?

### ISSUE THREAD

**Issue by lifeiscontent** [facebook/flow#4301]
Is there a way where I can have files like the following work with flow?

**src/components/ComponentA/index.js**
``` js
import React from 'react';
const ComponentA = (props) => {
  return <div>{{props.title}}</div>
}
```
**src/components/ComponentA/index.flow.js**
``` js
declare module "src/components/ComponentA" {
  declare function ComponentA({title: string}): React$Element
}
```

I'm not sure if this is the right syntax if this exists, but it if does, that sure would be nice! :)

that way I can use flow, and leave everything as JS.

**Comment by TrySound** [comment]
@lifeiscontent Why not just use comment syntax?

**Comment by lifeiscontent** [comment]
@TrySound because they're comments, not code.

**Comment by TrySound** [comment]
Well, you don't want code, you want files. :)

**Comment by TrySound** [comment]
I woudn't say thanks when I see such code. Reading two files with the same things is difficult. Writing is more difficult. One of the main purpose of flow is too be soundness with less custom syntax. Doing what you want will break both by more boilerplate and lack of desires to type own code.

**Comment by lifeiscontent** [comment]
@TrySound can you illustrate an example of what the file would look like with comment syntax?

**Comment by TrySound** [comment]
Similar
https://flow.org/en/docs/types/comments/

**Comment by AugustinLF** [comment]
If you look to how header files work in OCaml for instance, or [interfaces](https://realworldocaml.org/v1/en/html/files-modules-and-programs.html) (`.mli`), they do offer an interesting feature. First of all, whatever you write in the interface is a constraint for your source, so any signature declared in the interface must match the source. This can be interesting if you do want to type your file boundaries, without obfuscating the source (which is sometimes a problem with flow, I find that complex function typings can be really hard to read).

Moreover, the interface also works when another file imports something declared in your typed module. Lastly, the interface also "hides" the internal implementation of your file, forcing the user to only consume what is declared in the interface file.

Right now, flow only supports the second behaviour declared, with the use of `.flow.js` files, your interface files won't assert that what you wrote in your source is valid.

**Comment by lifeiscontent** [comment]
@AugustinLF yeah, I feel like as a library author if authors just added flow.js files they could just be read from the repo directly and thus not need to submit to flow-typed repo, also having all source typed without writing non-js code is a benefit I see, for example if you wanted to move away from flow you'd literally just trash all files named `*.flow.js`

**Comment by AugustinLF** [comment]
As a library author, this solution is already there for you, `*.flow.js` files do exist, that's how a lot of libraries do embed their typings (actually, most of them generate the `*.flow.js` files from their typed sources). That's actually the main point of the `*.flow.js` file now, that, and being able to add types to a file in your app which source is too complicated to type (I managed to get the typings right with a `*.flow.js` file, while failing too properly annotate the source).

But sadly, two files, each having a `*.flow.js` file won't be able to work together (I mean, there won't be any type checks between them).
