### ISSUE TITLE
Support optional chaining

### ISSUE THREAD

**Issue by vjpr** [facebook/flow#4303]
When could we expect optional chaining support.

It will be released soon with babel@7.

https://github.com/babel/babylon/pull/545

**Comment by 7ynk3r** [comment]
this is super important to make the code more readable.

**Comment by eshikerya** [comment]
this feature is really important for project i am working for. waiting for implementation!

**Comment by suparngp** [comment]
This is really important for dealing with JSON responses without having to write a plethora of null checks. +1

**Comment by alangpierce** [comment]
Note that optional chaining is still a stage 1 proposal and has gone through a number of changes since the Babel plugin was implemented. It's very likely that there will be changes to both the syntax and the behavior before the final JS feature is released.

See various other discussions:
https://github.com/tc39/proposal-optional-chaining
https://github.com/rwaldron/tc39-notes
https://github.com/Microsoft/TypeScript/issues/16

**Comment by nodkz** [comment]
Can be a simple case of optional chaining (`optional static property access`) implemented today under option's flag `esproposal` or `experemental`?

I say about simple property reading from nested objects `a?.b?.c`, which will be an amazing improvement in the code for React components. Eg when reading graphql responses. 

And leave dynamic and function/method calls uncovered while it in stage-1.

**Comment by nodkz** [comment]
Can be a simple case of optional chaining (optional static property access) implemented today under option's flag esproposal or experemental?

I say about simple property reading from nested objects a?.b?.c, which will be an amazing improvement in the code for React components. Eg when reading graphql responses.

And leave dynamic and function/method calls uncovered while it in stage-1.

cc @calebmer @mroch

**Comment by zanettin** [comment]
> which will be an amazing improvement in the code for React components. Eg when reading graphql responses.

would love to see that! we could remove tons of code and checks if flow also supports this syntax. thanks @nodkz and @alangpierce for having an eye on that.

**Comment by cloudkite** [comment]
looks like this will be in the next version 🎉https://github.com/facebook/flow/commit/763ffb509b237e2358bbace871732ee3e2bd623b

**Comment by niieani** [comment]
@cloudkite looks like only parsing will be supported. Type support [isn't landing](https://github.com/facebook/flow/blob/763ffb509b237e2358bbace871732ee3e2bd623b/website/en/docs/config/options.md#esproposaloptional_chaining-ignorewarn-), as the feature has been marked as experimental.

**Comment by fishythefish** [comment]
I've added (most) type support for optional chaining in 0.71.0 (gated behind the `esproposal.optional_chaining` flag). The exception is that you'll get a Flow error if you try to call a member expression where the call and/or member is part of an optional chain. Once I get optional chaining to play nice with our implementation of methods, I'll remove this restriction.

**Comment by houshuang** [comment]
This is amazing, I've been waiting for this.

In the following situation it complains about dash.exampleLogs[x] on line 319 because dash.exampleLogs might be undefined, however given that this code will only run if line 318 is true, shouldn't Flow realize that this cannot be undefined in this context?

```js
Cannot get dash.exampleLogs[x] because an indexer property is missing in undefined [1].

     frog/imports/ui/Preview/ShowDashExample.js
     316│               const dash = aTdashs[this.state.example];
     317│               let data;
     318│               if (dash?.exampleLogs?.[x].type === 'state') {
     319│                 data = dash.exampleLogs[x].state;
     320│               } else if (dash.prepareDataForDisplay) {
     321│                 data = dash.prepareDataForDisplay(
     322│                   dash.initData,

     frog-utils/dist/types.js.flow
 [1] 157│     | {
     158│         type: 'logs',
     159│         title: string,
     160│         path: string,
     161│         activityMerge?: Object,
     162│         instances?: number
     163│       }
     164│     | { title: string, type: 'state', activityMerge?: Object, state: any }
     165│   )[]

```

**Comment by fishythefish** [comment]
@houshuang We could potentially do that, but Flow doesn't currently perform that refinement.

**Comment by mrkev** [comment]
@houshuang feel free to create a separate issue to track and discuss that

**Comment by murrayju** [comment]
@houshuang @fishythefish @mrkev was a separate issue ever created? I too am finding it hard to make use of optional chaining when flow complains that I haven't checked for `null` (when I have).

**Comment by mrkev** [comment]
I haven't seen one.

**Comment by 0rvar** [comment]
Babel 7 RC has been released - it would be nice to have this and null coalescing ready when Babel 7 is fully released

**Comment by 0rvar** [comment]
Babel 7 is being released this week:
https://twitter.com/left_pad/status/1031700991186489344

**Comment by bsmith-cycorp** [comment]
Any progress on this? Babel 7 is now fully released: https://babeljs.io/blog/2018/08/27/7.0.0

**Comment by vicapow** [comment]
@eshikerya If typing is broken, that would be an issue but as far as I've seen, typing when using optional chaining is working as expected. Here's an example. Could you provide an example that demonstrates the issue you're seeing?

````js
function func(prop1 : ? { prop2?: string }) {
  return prop1?.prop2;
}

// no error
(func({bar: { bar : 'wow' }}): ?string);
// errors as expected
(func({bar: { bar : 'wow' }}): ?number);
````

**Comment by vicapow** [comment]
cc @samwgoldman or @avikchaudhuri

**Comment by bsmith-cycorp** [comment]
@vicapow it seems that basic property access work, but methods do not:
![solo_react_js_ ___svn_cyc_doc_app_src_cyc-ui](https://user-images.githubusercontent.com/25161635/44811378-280c2d00-ab9a-11e8-98fd-3e048e0d4e4b.png)

**Comment by eshikerya** [comment]
with flow@0.78 it works as expected
```javascript
type Dictionary<K, V> = { [id: K]: V };

type enmWorkspaceUserRoleType =
  | "Nobody"
  | "Resource"
  | "Spectator"
  | "Participant"
  | "Leader"
  | "Owner";

type WorkspaceUserInfoType = {
  id: ID,
  name: string,
  role: enmWorkspaceUserRoleType
};
type WorkspaceInfoType = {
  id: ID,
  name: string,
  workspaceUser?: WorkspaceUserInfoType
};

const workspaces: Dictionary1<string, WorkspaceInfoType> = {
  testId: {
    id: "testId",
    name: "Test Workspace",
    workspaceUser: {
      id: "userId",
      name: "Test User",
      role: "Owner"
    }
  }
};

console.log(workspaces.testId?.workspaceUser?.role);
```

expected error will be reported in case:
```javascript
console.log(workspaces.testId?.workspaceUser.role);

Cannot get `items[id]?.workspaceUser.role` because property `role` is missing in undefined [1]. [1]
```

**Comment by fishythefish** [comment]
Feasible, but low priority. (As usual, PRs are welcome!)

**Comment by smikhalevski** [comment]
@fishythefish optional chaining fails when used with $Call. This does work as expected:

```js
type A = ?{aaa: string};
declare var eee: A;

let www = eee?.aaa; // No error here
```
[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAPwDeAhrQFxgDOGATgJYB2A5gL4DcqACZ4AxjGosCANwlg88hoQGoYeDGASbSc+eQB0tanzDBgYAHJw5LFnBZgAFnklA)

This fails:

```js
type F = <T>(T) => ?{aaa: T};
type O<T> = $Call<F, T>;

declare var bbb: O<string>;
let ccc = bbb?.aaa; // Woops! An error!
```
[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiYAvGADwAqAfABSUCUp1YA-AN4CG3AXGJQF8A3JlwEA8lRZkAJAGFOMGOUIAaftRGoAJngDGMTgCcCAN2NgARtb6SAzhiMBLAHYBzTahh4MYPf9Ira1YAOm5OESA)

Why didn't optional chaining prevent an error from being raised?

**Comment by fishythefish** [comment]
That's an interesting case. The `$` types are typically evaluated lazily, so I believe what's happening here is that when the `?.` is checked, the LHS is seen to be some opaque `CallT` type. Flow doesn't recognize this as containing `null` or `undefined` values, so it ignores that branch and tries to proceed with the usual property access. This eventually forces the evaluation of the `$Call`, and Flow complains because we're now trying to perform a property lookup on a nullable type. `?.` should force the evaluation of its LHS earlier. I'll look into this case further.

**Comment by cloudkite** [comment]
@fishythefish Thanks for working on optional chaining its a really awesome feature!

In regards to $Call it seems very flakey do you have any insight on whether this is meant to work or why it doesnt? https://github.com/facebook/flow/issues/6506

**Comment by villesau** [comment]
@fishythefish have you implemented the unnecessary optional chaining linting rule? Would it be feasible to add an exception to it if object type is `{[id: string]: {a: number}}` (see https://github.com/facebook/flow/issues/6980 )? IMO proper fix would be to make result maybe type but just thinking about alternatives.

**Comment by fishythefish** [comment]
@villesau Yes, it was in the [v0.74 changelog](https://github.com/facebook/flow/releases/tag/v0.74.0) and you can find it in the [docs](https://flow.org/en/docs/linting/rule-reference/#toc-unnecessary-optional-chain).

We're unlikely to add such an exception right now. It's only a lint, so feel free to suppress or disable it if it makes sense for you. As with array access, it is the programmer's responsibility to ensure that they're looking up a valid key.

**Comment by villesau** [comment]
@fishythefish I think the lint is maybe the best part of the whole functionality :D It enforces consistency between checks and types: Otherwise the types are much more likely to rot if they don't match conditions. It revealed already after couple of weeks of optional chaining usage many types that didn't had maybe type when they should have had, and vice versa unnecessary checks. But if it does not work with `{[id: string]: SomeType}`, that makes it much more difficult to use.

I find array access very different. With array access it is easy to know what is the last available index and stay secure. With arbitrary key access, you don't have such privilege, and the linting rule prevents easy checks. With object on the other hand, you can define finite amount of possible keys if you want to make it more secure.

**Comment by SimplyComplexable** [comment]
Just reviewed [the thread](https://github.com/tc39/proposal-optional-chaining/issues/59) where optional chaining and methods was being discussed. It looks like they've resolved to keep the syntax as is, according to the most recent comment. With this in mind, could we revisit implementing this functionality in flow?

**Comment by gnmerritt** [comment]
Are we at the point where an implementation PR would be accepted? I'd be happy to take a shot at getting it working if that's the only hurdle left.

**Comment by mrkev** [comment]
IIRC this was waiting for the proposal to go through, though I might be wrong. Someone in the team might know better. @dsainati1

**Comment by dsainati1** [comment]
I'm not an expert on this unfortunately so I don't have any new information.

**Comment by mrkev** [comment]
@dsainati1 who would know if this is something that can be added?

**Comment by dsainati1** [comment]
Not sure honestly. Maybe @nmote?

**Comment by elquimista** [comment]
Optional chaining has been brought to stage-2 yesterday. Can we move forward now, Flow?

https://github.com/tc39/proposals/commit/effb785bc27388152e3bd307c5189c676ba478eb
https://github.com/tc39/proposal-optional-chaining/issues/83#issuecomment-499145723

**Comment by kenrick95** [comment]
Update: Optional chaining has moved to Stage 3

https://github.com/tc39/proposals/commit/25f8d6a4db03bcdd2cfd49bf32e312ce80e1c80e
https://github.com/tc39/proposal-optional-chaining/commit/73cf9852a2eba6d281fbfa98f848aca1b50f43a3

**Comment by goodmind** [comment]
@kenrick95 that was fast

**Comment by goodmind** [comment]
@mroch is it possible to support optional calls?

**Comment by gajus** [comment]
It is not supported by v8.

https://v8.dev/features/optional-chaining

**Comment by gajus** [comment]
Sorry – typo. It was supposed to say:

> It is _now_ supported by v8.

Edited.

**Comment by nmote** [comment]
At this point it's just a matter of prioritization. The worry with implementing early-stage proposals is that we will implement something that does not match the final specification of the feature, leading to a painful non-backwards-compatible change down the road. At this point, I wouldn't worry about that with optional chaining.

**Comment by lxe** [comment]
Is it possible to change that error into a warning?

**Comment by TrySound** [comment]
@ovidb Flow supports both for a long time. Optional calls support was introduced in the latest release.

**Comment by ovidb** [comment]
> @ovidb Flow supports both for a long time. Optional calls support was introduced in the latest release.

I apologise for not checking the release notes, but I am on the latest version and he reason I thought it's still not supported is because whenever you use optional chaining inside an if statement, flow doesn't seem to understand that maybe value has been checked for. Is this a bug or a known fact?

https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AhgGygXigbwCgBINAfgC58CooiiAjSgZ2ACcEUBzAGmIF8CAggDMArigDGiVFGAQWcaegwAKJPGTLKizZgCUVIgmFQ1G1JgB0ZS-QOEajx+qVW0ty8CQBlNh04qegDc1I4CAk5OoZEE0U5AA

On the bright side, thanks for letting us know that calls support is now working. Thats amazing news!!!

**Comment by mAAdhaTTah** [comment]
@ovidb This works: https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AhgGygXigbwCgoo0B+ALnyKgEgAjSgZ2ACcEUBzAGmoF8D+BAGYBXFAGNEqKMAjM4U9BgAUSeMiWUFGzAEoqxNYswA6MibongSAMqt2HZboDc1BEKir1qU2igBCXBQRDAx9QmIaIx0MMwsrW3tOJ1difl4gA Must be something about using optional chaining in conditionals.

**Comment by TrySound** [comment]
Yes, currently refinement is not preserved. So you need to cache optional chaining result in variable or use null check in if statement.

**Comment by TrySound** [comment]
https://github.com/facebook/flow/issues/6613

**Comment by gnprice** [comment]
FTR in case it's helpful for anyone else, it looks like [v0.112.0](https://github.com/facebook/flow/blob/master/Changelog.md#01120) was the release that introduced support for method calls in optional chains.

I determined that using this handy demo from a comment above:

> This works: https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AhgGygXigbwCgoo0B+ALnyKgEgAjSgZ2ACcEUBzAGmoF8D+BAGYBXFAGNEqKMAjM4U9BgAUSeMiWUFGzAEoqxNYswA6MibongSAMqt2HZboDc1BEKir1qU2igBCXBQRDAx9QmIaIx0MMwsrW3tOJ1difl4gA

and a quick binary search. It's also mentioned in the release notes under v0.112.0, though not very definitively.
