### ISSUE TITLE
How to fix import alias for Flow: !/components/layout. Required module not found 

### ISSUE THREAD

**Issue by johhansantana** [facebook/flow#4304]
<img width="472" alt="screen shot 2017-07-03 at 10 58 51 am" src="https://user-images.githubusercontent.com/9933887/27798416-20158c70-5fdf-11e7-9e7e-4b293ca32ee7.png">

I have `!` as alias for root folder of project using:

```javascript
  "env": {
    "development": {
      "presets": ["next/babel", "flow"],
      "plugins": [
        ["babel-plugin-root-import", [
          {
            "rootPathPrefix": "!"
          }
        ]]
      ]
    },
...
```

Is there a way to fix this with flow?

**Comment by AugustinLF** [comment]
If I'm not mistaking, what you're looking for is the [`module.name_mapper`](https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string)  option of `.flowconfig`. I'm sorry I never used and suck with regex, but this is supposed to work!

**Comment by johhansantana** [comment]
@AugustinLF thanks! I'm not very good with regex either :( I'll play around and see if I get it to work.

**Comment by johhansantana** [comment]
got it working with
```
[options]
module.name_mapper='!'->'<PROJECT_ROOT>'
```
