### ISSUE TITLE
Suggestion: Utility type to unwrap maybe types?

### ISSUE THREAD

**Issue by dmnd** [facebook/flow#4306]
This came up while using Flow types generated by relay-compiler.

Here's a complex generated type I'd rather not repeat. Note that it's nullable:
```js
type GeneratedType = ?{|
  // something complex... elided
|};
```

In my own code, I want the same type, but I don't want it to be nullable. I can't figure out how to do that though, so I have to copy/paste the entire type. 

It would be nice if Flow had a utility type that let me "unwrap" the nullability:

```js
type MyType = $UnwrapMaybe<GeneratedType>;
```

See also the Relay issue https://github.com/facebook/relay/issues/1935. If Relay generated decomposed types I wouldn't be asking for this Flow utility type, but I think it's probably useful elsewhere too.

**Comment by madbence** [comment]
flow has `$NonMaybeType<T>` :wink: (yup, it's not documnted :crying_cat_face:)

**Comment by dmnd** [comment]
Oh awesome, thanks @madbence. I'll close this in favour of #4260
