### ISSUE TITLE
Missed type for React component while spread types

### ISSUE THREAD

**Issue by hlomzik** [facebook/flow#4307]
There are strange errors when you pass component as argument of type with spread (`Test2`). And even more strange errors if such type contains more spreads in it.

```
function Test2({ component: C }: Props) {
  return <div><C/></div>
}
```

Works well if you just have `component: typeof Component` in type definition. But became weird if such definition came in via spread: `{ ...{ component: typeof Component } }`. And weirder if you use multiple spread: `{ ...HereIsComponent, ...{} }`.

Minimalistic example:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAwnDnAHantEC+YUeVmADkeCtWGpUBAJ7ZSYAPIEAFqTwAFQdgDOYALwNUYMAVI6CAfgBcYC3nTsA5qh5TZ8sFri6DRk5SsuJzctgAUHqRwUMxBHFwEAJRgAD5gAGIAruzU6Byu7nIK3roAjH4lOoWelQBMfvTGYAB0rZU0BdJFXto6AMwNTa3N7UOtymqavR1uqFDZuRxgACrmBKVhjIFsIQS2TGA8tpWlyY0mYgSZeOxgADwAJugAbgB8d0zA78BPb2DAwDACHwAGs9AhSDAYJ15jkCHlbqsLLVNmBtsEEvtDsderUzk1Ltdbo8Xu9Pt9fq9-oCAKLEYhgbIPUhQRykB4whbwpZIgh9VHo+KhZjYno+fr4i6kK43e6Uj5fO4-UnUsB0hnZEHsRC3SJgADUjPYzNZnA5biAA

*I use `component: C` because React requires custom elements' names to be capitalized.

**Comment by draganSm** [comment]
@hlomzik based on https://github.com/facebook/flow/issues/1326 spread operator is not supported in type definition.

**Comment by goodmind** [comment]
This works fine if you make all of objects exact
