### ISSUE TITLE
Computed property cannot be assigned with String

### ISSUE THREAD

**Issue by boopathi** [facebook/flow#4310]
Input:

```js
function a (values: Array<String> = []) {
  return values.reduce(
    (acc, cur) => Object.assign(acc, { [cur]: cur }),
    {}
  );
}
```

Error:

```txt
3:     (acc, cur) => Object.assign(acc, { [cur]: cur }),
                                        ^ object literal. Computed property cannot be assigned with
3:     (acc, cur) => Object.assign(acc, { [cur]: cur }),
                                           ^ String
```

[REPL](https://flow.org/try/#0GYVwdgxgLglg9mABAQ0QCgG7IDYgKYDOAXIgIIBO5yAngDwDKU5MYA5gHyIC8iA2gLoBKRAG8AUIkTk8UEOSRZchAHTSAJiAh40EyemQQIAGkQQ5wrpwDyAIwBWeaMuQECMVmDQHjovmfL8JP6IAL6CRrqSIiG6ggDcYjFAA)

Similar issue: #3258

**Comment by madbence** [comment]
workaround (`string` instead of `String`):

```js
function a(values: Array<string> = []): { [string]: string } {
  return values.reduce(
    (acc, cur) => Object.assign(acc, { [cur]: cur }),
    {}
  );
}
```

(i've added the annotation for the return type too, because flow wasn't able to infer it)

**Comment by AMongeMoreno** [comment]
Is there any plan on adding this? It is quite bad that we can't use computed properties as keys ...

**Comment by goodmind** [comment]
I think you shouldn't use `String`

**Comment by seantcanavan** [comment]
This is happening for me with the `?boolean` type even though my map contains values for `true`, `false,` and `null`, all 3 types a `?boolean` can take.

**Comment by SamChou19815** [comment]
We banned this pattern since we removed support for unsealed objects
