### ISSUE TITLE
Impossible to have typed key and value on typed object.

### ISSUE THREAD

**Issue by steida** [facebook/flow#4313]
This is invalid. When I remove $Keys, key can be anything. How to restrict key and value types?

```
type Form = {
  name: string,
  age: number,
}

const form1: Form = { name: 'Joe', age: 42 }

const setFormProp = (prop: $Keys<Form>) => value => {
  const form2: Form = { ...form1, [prop]: value }
}

// But how to check prop? This should be valid.
setFormProp('name')('1');
```

**Comment by steida** [comment]
Covariants with the spread. No.

https://flow.org/try/#0C4TwDgpgBAYg9gJwLZQLxQN4CgpQNQB2AhkhAFxQDOwCAlgQOYA0O+RD5UBArkgEYQELAL5YsAYzgFqUAGaIkARgrxkaTFxKcA5ACk4EbUyjtOAFgBMUURKkzKEYKqQAFBHDDqw7z6gB8UABuRAA23ND+mKyS0sByChYqCuoYUAB0GfLIisYA2t4eALoUwWHQojYOTgpuHgAU2sSk2gCUDS4QYEStANxAA

**Comment by steida** [comment]
OK, we can't use covariants. Still, how to detect the wrong prop?

https://flow.org/try/#0C4TwDgpgBAYg9gJwLZQLxQN4CgpQHYCGSEAXFAM7AICWeA5gDQ5QF2n4CuSARhAkwF8sWAMZw8lKADNESAIxl4yNJnxF2AcgBScCBoYs2ZACwAmKENHjJ5CMCVIACgjhgVACjAuwASjQA+KAA3AgAbDmhUQOxcMQlgaVlTRVkVDCgAOiyZZDkDAG0vVwBdMhDw6CFLAHpqqAA1MIioanIoEQALCBEAawgAEwysWtt7WWdXdw1CYg0fdzkfAG5hWqgAIQ4EjrgAdyhgOHau3qgisAB+LFGHCbApmYg9eY1HCDACOaWgA

**Comment by steida** [comment]
But how to check invalid prop? This should be valid I guess.

https://flow.org/try/#0C4TwDgpgBAYg9gJwLZQLxQN4CgpQHYCGSEAXFAM7AICWeA5gDQ5QF2n4CuSARhAkwF8sWAMZw8lKADNESAIxl4yNJnxF2AcgBScCBoYs2ZACwAmKENHjJ5CMCVIACgjhgVACjAuwZACQBpCBByAB4HAD4ASjRwqAA3AgAbDmhUWOxcMQlgaVlTRVkVDCgAOjKZZDkDAG0vVwBdMgTk6CFLAHp2qAAhDhyACzgAdyhgOCgRfogRAGsoOrAAfigAFX7qcgpBjkSAEyheeKTqXZKsW3tZZ1d3DUJiDUjbuUeAbiA

**Comment by steida** [comment]
Some people suggest undocumented $Shape, which doesn't work with covariants and type inference seems to be broken.

Maybe I am wrong, but it looks like it's impossible to set key value on typed object with Flow type. What am I doing wrong? Thank you.

**Comment by madbence** [comment]
you can totally do that:

```js
type Form = {
  name: string,
  age: number,
};

const form1: Form = { name: 'Joe', age: 42 };

const setFormProp = <T: $Keys<Form>>(prop: T): (($ElementType<Form, T>) => Form) => value => (({ ...form1, [prop]: value }: any): Form)

// But how to check prop? This should be valid.
setFormProp('name')(42); // error
setFormProp('name')('Joe');
setFormProp('age')(42);
setFormProp('age')('Joe'); // error
```

the only annoying part is the assign part, where flow cannot recognize that `[prop]: value` is actually valid (that's why i've used the `any` cast)

**Comment by steida** [comment]
@madbence Thank you. Wasn't aware of undocumented types.

**Comment by steida** [comment]
This is real life example:

```jsx
// @flow
import type { Dispatch, Form, State } from '../types';
import type { PostFormFields } from '../reducers/posts';
import Box from './Box';
import TextInput from './TextInput';
import { connect } from 'react-redux';
import { initialFormId } from '../lib/form';
import { temp } from '../lib/temp';

type CreatePostProps = {
  form: Form<PostFormFields>,
  dispatch: Dispatch,
};

const CreatePost = ({ form, dispatch }: CreatePostProps) => {
  const disabled = temp(form.disabled);
  // How to type prop and value?
  const setPostForm = prop => value => {
    dispatch({
      type: 'SET_POST_FORM',
      fields: { ...form.fields, [prop]: value },
    });
  };
  const handleSubmitEditing = () => {
    if (!form.fields.text.trim()) return;
    dispatch({ type: 'CREATE_POST', fields: form.fields });
  };
  return (
    <Box marginBottom={1}>
      <TextInput
        disabled={disabled}
        label="New Post"
        onChange={setPostForm('text')}
        onSubmitEditing={handleSubmitEditing}
        placeholder="Say thing"
        value={form.fields.text}
      />
    </Box>
  );
};

export default connect(
  ({ posts: { form } }: State, { id = initialFormId }) => ({
    form: form.changed[id] || form.initial,
  }),
)(CreatePost);
```

**Comment by steida** [comment]
The same pattern elsewhere. Flow can't recognize proper key and value. And error popup isn't rendered properly.

![screen shot 2017-07-22 at 21 53 11](https://user-images.githubusercontent.com/66249/28494226-3439f30a-6f28-11e7-9b8e-c4668f3fb5c0.png)
