### ISSUE TITLE
Existential type alias

### ISSUE THREAD

**Issue by istarkov** [facebook/flow#4316]
I'm trying to create an alias for existential type, but type alias works in different manner in some cases.

Here [https://flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAdgDwCSxANGAPICuGAfGALxgAUAhgFxiUBKNiwYYA3JlwESAQRgBLLgGdSAFRbsSamiCYTUAYzjElGMFGJ8txegFsARngBOOjZ15gbD50NYsuYADUYACMEkYmZhYA+gBuXDBs5sQcAAwCYmDAwMlxCWAAFspg2Piedo5O6BGmYFwWVsRyiipelW7cfG0+wnVBoeHGtfXEeYnsI2kZWTkjY4XFpQRcxFjoHDHxMHymTvLEAObT2Z5wZitYYEpwYAYrAORmjrfKGHgAJqjcmwk8u-tHTInO6mD5gABMVwwe0OYDwynkMDWQA) the example.

```javascript
type Fn<In, Out> = (a: In) => Out;
type FnAlias<T> = Fn<T, *>;

const fn: Fn<number, *> = (a: number) => a + 1;
const fn_val = fn(0); // fn_val has type number

const afn: FnAlias<number> = (a: number) => a + 1;
const afn_val = afn(0); // afn_val has type any

(fn_val: string); // not any so can't be casted
(afn_val:string); // casted 2 string easily
```

for `fn_val` flowtype infer `number` type, but using alias it gives `any` for `afn_val`.

Not sure this is a bug, but can you explain what happens here if not.

PS:

more simple than above and does not work also

```js
type Fn<In, Out = *> = (a: In) => Out;

const fn: Fn<number, *> = a => a + 1;
const fnVal = fn(0); // fn_val has type number

const afn: Fn<number> = a => a + 1;
const afnVal = afn(0); // afn_val has type any
```

**Comment by asolove** [comment]
This is a really interesting question and highlights some confusion that many of us have experienced with existential types.

I think the key thing is to distinguish between what type variables do and what the `*` operator does.

In the code:

```js
type Fn<In, Out> = (a: In) => Out;
```

The `Fn` is not a type, but a type constructor. It says that for any two types that are passed in as type arguments, it will return a new type that represents a function that accepts an `In` argument and returns an `Out` result.

So when you see type variables in a type constructor, each variable stands for an infinite number of particular types that we could use in them.

In contrast, `*` stands for exactly one specific type in each place that it's used.

So when you say:

```js
const fn: Fn<number, *> = a => a + 1;
``

Flow knows it needs to fill in some type for the return value of the function. Using type inference, it can figure out the function returns a `number`, and so it substitutes `number` for `*`.

Similarly, when you say:

```js
type Fn<In, Out> = (a: In) => Out;
type FnAlias<T> = Fn<T, *>;
```

Flow has to find exactly one type to fill in the `*`. In this case, since `Fn<T>` represents "the set of all functions that accept an argument of type T", Flow can't know anything about the return type of the function. After all, the functions in that set might return _anything_. So Flow infers that the `*` should be replaced with `any`.

So now, maybe that explains why you can't do this, but it probably doesn't help solve your problem! Why did you want to have a type that means "the set of all functions that accept an argument of type T but where we don't know the return type"? It seems like you usually do need to know the return type of the function in order to be able to do something with the answer it returns. If there's some detail of the code that makes the `FnAlias` type necessary, it would help if you could share that so we can try to work around it.

**Comment by istarkov** [comment]
Thank you for your explanation! 

The only use case for me is somehow visually prettify the type definition of recompose HOCs type definition. (so there is no need to waste your time on thing which does not affects anything)

https://github.com/acdlite/recompose/tree/master/types#how-it-works

To get instead of this
```
const enhance:HOC<*, EnhancedComponentProps> = 
```

Something like
```
const enhance:HOC<EnhancedComponentProps> = 
```

It's easier to allow flow infer base component type (_like return type at example above_) instead of writing it every time.

I'll close this, Thank you again!
