### ISSUE TITLE
Union types in prop types aren't handled properly in functional React components using destructured props

### ISSUE THREAD

**Issue by omninonsense** [facebook/flow#4317]
It seems that flow doesn't properly check union types inside functional React components with destructured props prop names and default values. Not sure if this is only isolated to the destructured props syntax, though.

Minimal example:

~~~javascript
// @flow
import React from 'react'

declare type $project$Component$props = {
  unionProp?: number | string
}

export default ({ unionProp = 10 } : $project$Component$props ) =>
  <div>{unionProp}</div>
~~~

and the errors which it generates:

~~~
src/components/TestComponent.jsx:8
  8: export default ({ unionProp = 10 } : $project$Component$props ) =>
                       ^^^^^^^^^ number. This type is incompatible with
  8: export default ({ unionProp = 10 } : $project$Component$props ) =>
                       ^^^^^^^^^ string

src/components/TestComponent.jsx:8
  8: export default ({ unionProp = 10 } : $project$Component$props ) =>
                       ^^^^^^^^^ string. This type is incompatible with
  8: export default ({ unionProp = 10 } : $project$Component$props ) =>
                       ^^^^^^^^^ number


Found 2 errors
~~~

Changing the prop type to `unionProp?: mixed` fixes the error, but I am not sure it's the right way of doing things. Fairly new to using Flow, so I'm not ruling out that I'm doing something wrong, but to me this seems like this is something that should work.

Posted the [same code on flow.org/try][floworg-try] if someone wants to play with it.

[floworg-try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tiiAJoadMQ6DgJ7pCoACToqAKw45hAYWqYAdoQXSxsdAGdQAXlABvRKFABXBclgKAClXQB+AFygFx1ACNCWUAB9QGnFmQFAHNEAF8WQgAPTFxQdkhiY2g8AAo9EzMLa3UdUABGAAZQUNBHUQkpWXkLZVUbLQBKHQA+Q1AAHlZkADdmvVNzKxtQ9uAu3sQgA

**Comment by jstejada** [comment]
I am also seeing this error when using it with functional components

**Comment by macklinu** [comment]
I believe this is related to https://github.com/facebook/flow/issues/2093.

**Comment by omninonsense** [comment]
@macklinu Your're right! It seems to be the same issue. Since that one is older and properly tagged. So, I'll close this one. Cheers!
