### ISSUE TITLE
Flow must require import type for interfaces as it does with other types

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4319]
Not sure if this is a documentation bug or something different, but it's really confusing that for interfaces can't be imported via `import type {MyInterface}` or the fact that they can be imported via `import {MyInterface}` it also makes it more problematic to switch between type & interface.

**Comment by TrySound** [comment]
@Gozala You can't import interfaces via `import type { }` ? The only restriction here is ability to remove right statements without type knowledge. Babel just removes what it can see. `import type {}` will be removed, `import {}` won't.

**Comment by Gozala** [comment]
> @Gozala You can't import interfaces via import type { } ? The only restriction here is ability to remove right statements without type knowledge. Babel just removes what it can see. import type {} will be removed, import {} won't.

You are right, I was mistaken you can import interfaces with `import type {MyInterface}` and also that babel fails to remove those imports which is also how I run into this issue.

I'm updating issue title, I think flow should enforce `import type ` on interfaces as it does with other types.

**Comment by SamChou19815** [comment]
This is now strictly validated
