### ISSUE TITLE
Function interface does not validate functions just uses of it

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4320]
Here is an [example code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gBiWYAPNgA4CuOANGHC8zgHxgDeqMGAAUjFgEoAXJxzdUAX3Sk4WAM44wxKdVpYmAWwBGhdhoLYA5nwC8YGjb40A1GACMqIA) that passes type checker even though function is clearly does not match an interface:

```js
/* @flow */

interface Fn <input, output> {
  (input):output
}

const a:Fn<number, string> = n => n + 1
```

Also worth noting that if function is type annotated like `(n:number):number => n + 1` type checker reports mismatch.

**Comment by vkurchatkin** [comment]
I suspect that this is only supposed to be used in type declarations in covariant positions.

**Comment by SamChou19815** [comment]
It's now errors
