### ISSUE TITLE
Strict function call arity check not working

### ISSUE THREAD

**Issue by straku** [facebook/flow#4324]
Hi, it seems that strict function call arity check introduced in version [`0.47.0`](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/) doesn't work with later versions (`>= 0.48.0`).

Example code:
```
function add(a: number, b: number) {
  return a + b;
}

add(10, 15, 20);
```
It doesn't produce any errors with version different than `0.47.0`.

Try flow example:
https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqAIYAmJAFEQFyjqoC2ARgKYBOANKIzXU2wJSgA3olChWzbKlaEioANRcA3IgC+yUhQCMABk5aArJwBMO-kqA

Any ideas?

**Comment by stevemolitor** [comment]
I _am_ seeing stricty function call arity errors locally as expected, but not on 'try flow'. 

According to this blog post, the `experimental.strict_call_arity` options was supposed to be removed in `0.47.0`: https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity.

But apparently it was not. If I add `experimental.strict_call_arity=false` to my `.flowconfig`, the example code from @straku above checks without errors. If I change the option to `true` or remove it completely, I do get 'unused function argument` errors as expected.

I'm using `0.48.0`. But I'm seeing lots of references to the flag on `master`, for example here:

https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L9215

So I'm guessing that the flag was actually left around, and that try flow is explicitly setting it to `false`?

**Comment by samwgoldman** [comment]
Yeah :( https://github.com/facebook/flow/blob/21e332775e7f21b67726f07ddeb3c36cdf242456/src/flow_dot_js.ml#L103

Want to send a PR?

**Comment by stevemolitor** [comment]
@samwgoldman A PR to set the flag you linked to from `false` to `true`? Or a flag to remove all references to `enforce_strict_call_arity`? I could whip up the former pretty quickly; not sure about the latter. ;)

**Comment by samwgoldman** [comment]
The former is fine — you could do it on GitHub, even!

**Comment by stevemolitor** [comment]
Thanks @samwgoldman for the quick response. PR here: #4478

**Comment by BossGrand** [comment]
Incase anyone else comes to this issue looking for docs on how to do this

https://flow.org/en/docs/lang/width-subtyping/
