### ISSUE TITLE
`in operator` not working

### ISSUE THREAD

**Issue by yfr** [facebook/flow#4329]
Why does flow don't get the check with the `in operator` https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/in ?

This works fine: 
```js
if (navigator.serviceWorker) {
  navigator.serviceWorker.register('/service-worker.js');
}
```

This throws an error: 
`call of method 'register'. Method cannot be called on possibly undefined value`

```js
if (serviceWorker in navigator) {
  navigator.serviceWorker.register('/service-worker.js');
}
```

[example](https://flow.org/try/#0JYMwBAFAdghgbsA5jALgewE4DoDOBTDBAYzwHVMBrAgSjAG8AoMMWBZdbfQ4E8jK7BjyJgOFAQgByAPRdieALQB3SgSwArHJOoBuBgF8GDUJDk8yqjGGBQW8JKky1GzVg464C8vgKxCRYhIyZiTKlhpaugYMQA)

**Comment by jcready** [comment]
Just because a property exists on an object does not imply that its value isn't `undefined`. Also you need quotes around the left-hand side of the `in` operator.

```js
type A = { b?: function }
const a : A = { b: undefined }
assert('b' in a) // passes
```

**Comment by yfr** [comment]
Ah sure. Thanks! And of course the
Quotes where missing.

**Comment by elchinillo** [comment]
What about something like:

const obj = { test: true };
const key: 'test' | 'bad' = 'test';

const result = key in obj ? obj[key] : false;

Flow will give an error even though we know "key in obj" is true

**Comment by mrkev** [comment]
@elchinillo the error you get is

```
4: const result = key in obj ? obj[key] : false;
                                   ^ Cannot get `obj[key]` because property `bad` is missing in object literal [1].
References:
1: const obj = { test: true };
               ^ [1]
```

which is accurate. Even though key is 'test', with your type definition you're telling flow it could also be 'bad', which forces it to assume `obj['bad']` is a possible access.

Notice removing the 'bad' option on the key type [works](https://flow.org/try/#0MYewdgzgLgBCBGArGBeGBvGUCm0BcWATgK7YwC+A3AFCiSwDW2AngQOQ7Ruowe5RsatcNBiFcxADaw0TZjACWYOEhgB+FYgDacgLowCAMwCGkiNiFA).
