### ISSUE TITLE
Please never remove the `--version` argument

### ISSUE THREAD

**Issue by w0rp** [facebook/flow#4330]
When you run `flow --version`, it tells you that it is deprecated in favour of `flow version` in newer Flow versions. This implies that `--version` will eventually be removed. I would like to suggest that `--version` is _never_ removed from `flow`.

I integrate `flow` with my Vim plugin `ALE`, and I need to check the version of Flow to know which arguments are supported, as someone might be running version `0.49.1`, or `0.27.0`. If `--version` is ever removed, then at best I'll have to write `flow --version; flow version` and try and parse the version number from the combined output.

**Comment by andreypopp** [comment]
In addition to that, `cmd --version` is a widely adopted convention and I usually automatically reach for `cmd --version` when trying to check the command's version.

**Comment by eedrah** [comment]
I completely agree - it seems like it's a pretty strong standard among almost all CLIs that `--version` will give you the version number. Many tools and people use this without thought. A user should not have to consult the documentation or help to look for the command when there seems to already be a community standard.

(Though I do appreciate why there is also a command `version` to allow for further options.)

I've created a pull request to un-deprecate this.

**Comment by nmote** [comment]
Okay
