### ISSUE TITLE
Can't cast object with strict property into object with maybe property

### ISSUE THREAD

**Issue by dapetcu21** [facebook/flow#4332]
I don't exactly know what the terminology for this situation is, but following snippet does not work although it intuitively should:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phhRxwBcYA-AHYCuAtgEZ4BOqAX3TZ8YAEKkKVGnUbtufQegDGcFgGcMYLgDUAhjDZ5GEsuRkMwARgBMYIao1a9+w8aKTdBowG4gA

**Comment by madbence** [comment]
if that's allowed, you'd be able to do `aValue.foo = null`, and that would violate the constraint in `B`. but if you promise that you won't write anything from to it, it works:

```js
type A = {
  +foo: ?number
}

type B = {
  foo: number
}

const bValue: B = { foo: 12 }
const aValue: A = bValue;
```

you can read about variance [here](https://flow.org/blog/2016/10/04/Property-Variance/)
