### ISSUE TITLE
Given a type `Array<T>`, how can I get type `T`?

### ISSUE THREAD

**Issue by omerzach** [facebook/flow#4336]
Given `type T = ?U` I can use `$NonMaybeType<U>` to get `foo`. This is useful when `U` is an on-trivial type that was generated by something like Relay. 

Is there an equivalent for `Array`s? That is, given a `type T = Array<U>`, I want an operator `$UnwrapArrayType` for which `$UnwrapArrayType<T>` gives me `U`.

**Comment by madbence** [comment]
afaik there is no built-in for that, but you can write your own type:

```js
type _$UnwrapArrayType<T, U: T[]> = T;
type $UnwrapArrayType<T> = _$UnwrapArrayType<*, T>;

type Foo = { foo: number };
type FooArray = Foo[];

declare var f: FooArray;
(f[0]: $UnwrapArrayType<FooArray>)
```

**Comment by vkurchatkin** [comment]
`$ElementType` does what you want:

```js
type X = Array<number>;
type X_ = $ElementType<X, number>;
```
