### ISSUE TITLE
Bug in types inherited from object spread

### ISSUE THREAD

**Issue by anfedorov** [facebook/flow#4338]
The following [fails the type checker](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzADwC4wBvVMMAB2IGcAXHASwDsBzMAHzGYFcBbAEYBTHABpUAXwDc6bHihgAvGAAUASiUA+MMGBgcfMHQAWjGmBgshRuGCiN8qMhTlhby52ACQ1MAAZxCgoAOlD8QLAJSSA) regardless of whether `p: 0` or `p: "a"`.

```
/* @flow */

var x: {
  p: string | number,
};

var f = () => {
  var o = {
    p: 0,  // <- this value fails type-check
    ...x,
  }
}
```

It also passes type check when it's in the same scope (i.e. when it's not wrapped in `f`).

**Comment by vkurchatkin** [comment]
Workaround:

```js
var o = {
  	p: (0: string | number),
    ...x,
  }
```

**Comment by anfedorov** [comment]
Thanks. I hope this can get fixed in the typechecker, as well?

**Comment by vkurchatkin** [comment]
@anfedorov yes, ideally. I would classify this as a bug.

**Comment by villesau** [comment]
This fixes it: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
