### ISSUE TITLE
Flow does not support subtyping for nested objects

### ISSUE THREAD

**Issue by Stralos** [facebook/flow#4339]
Flow subtyping works only for the first level of object props. Any prop that is being subtyped bellow the root level of the object shows an error message: **'This type is incompatible with the expected param type of'** even if the passed object has all the required properties. 

code example 
```
/* @flow */
type BodyProps = {
language: {
	text: {
    	header: string,
    	footer: string
  	}
  }
}
const Body = (props : BodyProps) => {
  return (
    <div>
      <Header {...props}/>
    </div>  
  );
};

type HeaderProps = {
  language: {
    text: {
  		header: string
  	}
  }
}
const Header = (props : HeaderProps) => {
  return (
    <div> {props.language.text.header} </div>
  )
}
```

**Comment by vkurchatkin** [comment]
This is because properties are invariant by default. You need to make `text` covariant like this:
```js
type HeaderProps = {
  language: {
    +text: {
  		header: string
  	}
  }
}
```
