### ISSUE TITLE
Declaring types in libdef does not detect some errors, declaring them locally works well

### ISSUE THREAD

**Issue by istarkov** [facebook/flow#4342]
As an example `compose` function
[here](
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMzwDGAhjACQCqAdsQE6YBiVAPAIIA0YASgHxgC8YABTEAXGFYBKAXy4BuVBhz4ipMgGE4AW2xwAzvkGowwtpwBCndTyHGTYAEaFxq8tTqMWlsNfZ2TxA4ucCRuNPRMZmDmPH72YAB0SbS4eujirLS0xJjMAG5wAJYAJjx20vx8rpThnlHW0gBkdkJRMbbxgcGhNR6RHNGx-onJqekSWTn5RaXlMgQhau4RLAMxkgqoxbiEMHT4eXRghNq6Bt1qmjr6uArxSng+p2x8giIZFXwFJQpYjwASAHl1G1XsIxE8dC9PpDsMwYpsoABXKiEdCFOBUMBaTAAUSoAAtiKjcLRQUItMRsHhaOJzPMpOIgSC1nwAN52FLoJG0LFCE46cRXOGsHgwoTYWhwbB6OkwgXYClUmkSqUyyQbVAAX0UJyoaTA6AJhT0ABE4KkAHJwdAAdTgtAA1kzgcwQJw2WBsOIqEitA5SZxcOI0rRClQAOZgLVghU3DrYvGE4mEUmq6V6eZCDnxb1gAAGZDZkozCWwyDAAGYtfm4tGNXWcfiiSTaOmZVmc-Y8yWZWWwABqMAAJjrJmcYAAssQjQkpSjiu29GXJHWtRrUJqgA) works well 

But if I move `compose` definition into library definition like [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMzwDGAhjACQCqAdsQE6YBiVAPAIIA0YASgHxgC8YABTEAXGFYBKAXy4BuVBhz4ipMgGE4AW2xwAzvkGowwtpwBCndTyHGTYAEaFxq8tTqMWlsNfZ2TxA4ucCRuNPRMZmDmPH72YAB0SbS4eujirLS0xJjMAG5wAJYAJjx20vx8rpThnlHW0gBkdkJRMbbxgcGhNR6RHNGx-onJqekSWTn5RaXlMgQhau4RLAMxkgqoxbiEMHT4WnDFAK4w+ADkKYTaugbnYADedtu7+2B5dGDXOvq43WqaH4GBQAX2GqEKP1o6EeXxuvzAILAUFo2jAlx28Lucni4KweB8NzYfEEIgyFT4BRKCnx+AAEgB5dRtEnCMSEnTEikc7DMGKbKDHKiEdCFOBUMBaTAAUSoAAtiMLcLQWUItMRsHhaOJzPMpOJGcy1nwniYUuhjrQJUJvthxIDeaweNyhNhUdg9Druba1Rqta73XpJBtUGDUNcqGkwOg5YU9AAROCpABycHQAHU4LQANYGpnMECcB5gO1gKjHLQOZWcP5gNK0QpUADmiNZtt+HUlMvlisIyoDcA98yEpvspYABmQHm7B3oEthkGAAMwg8dxRHB9dS2UKpW0AdDyrCUcmUszj3zsAAajAACZ1yZnGAALLEGMJVFC4oHufYSTrkFg1QEMgA) in some situation flow stopped to detect some errors. 
(It works well for a lot of other situations but don't work with current)

**Comment by calebmer** [comment]
I’m not sure if `declare module` works outside of library definition files. Could you put together an example in a small GitHub repo?

**Comment by istarkov** [comment]
@calebmer thank you for help, seems like you are right and declare module does not work inside `/try`
here https://github.com/istarkov/flow-compose-error is the example to reproduce a problem
It's different from above - but with the near same behaviour - errors depend on where compose is defined. 
Here is the partial copy of above project README.

`src/goodCompose.js` uses internally defined compose

`src/badCompose.js` uses `libdef flow-typed/recompose` for compose

Except `compose` definition both files share the same code.

After run `yarn flow` we see good error for internally defined Compose, and something strange for libdef compose

See screenshots

## src/goodCompose.js

![image](https://user-images.githubusercontent.com/5077042/28540848-6de8f504-70bf-11e7-977f-4db33c060bc0.png)

## src/badCompose.js

![image](https://user-images.githubusercontent.com/5077042/28540821-590509ac-70bf-11e7-8983-bdd298400627.png)

**Comment by calebmer** [comment]
You are actually getting the expected error here 😊

`Math.round()` takes a number, but your first enhancer returns a string for `p`.

I agree that this error message is way to hard to diagnose, though 😖

**Comment by istarkov** [comment]
The problem is not in error, the problem that it different for the same compose definition, and depends on compose location.
And in one case error is easily readable, and not in the other

**Comment by sibelius** [comment]
is this still valid?

**Comment by SamChou19815** [comment]
The difference between libdef and local mode should be fixed a long time ago
