### ISSUE TITLE
Type mixed incompatible with array type if object property value

### ISSUE THREAD

**Issue by floriangosse** [facebook/flow#4345]
If I have mixed as a type of an object property value and define a type which is more explicit flow declares it as an error.

[Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgCoAsCWBnU9YAnAaxwC5EAXATwAcBTUAWVAF5QBbLAD3oBMA3FTqMAgm1AA7AK7RooAD6gclQlkkBzANoBdIYgDGsSStABDAIxlQ49jLlCjJyuYBM126C0ByAG5noaXoLbwAaUD8AoNdvPWRIaUkDSixjTjNiYNAACg5rJgBKUABvRFBQJxxYaHoAOjgNXIKhAF9kDgzg7MtmxA7Mi27XXuRUTFxQPlh6HElvFwISChoGUAAFM0IzDjx2UvLy2kJYWitOHn5EFv0VxgA1KJmJfYOjk7P7eSUVNU1dK-0lRc-kCM2sD1BuxKiAAkG9TtYfCCgiFwpFQTEdAD4olkqlJOlMq4crRNttyOsyTsiqUYZVqnUGtlSVtqa12p1XNlkTMRoggA)

**Comment by vkurchatkin** [comment]
You need to make properties covariant:

```js
type Params = {
    +prop1: mixed
};
```

**Comment by floriangosse** [comment]
And what if I want to change `prop1`?

**Comment by vkurchatkin** [comment]
That would be unsafe
