### ISSUE TITLE
Type information is lost in const/var

### ISSUE THREAD

**Issue by chrisui** [facebook/flow#4349]
The following code

```js
/* @flow */

function foo(team: ?{subvar: string}) {
  const show = team != null;
  
  return show ? team.subvar : '';
}
```

fails with errors

```
6:   return show ? team.subvar : '';
                        ^ property `subvar`. Property cannot be accessed on possibly null value
6:   return show ? team.subvar : '';
                   ^ null
6:   return show ? team.subvar : '';
                        ^ property `subvar`. Property cannot be accessed on possibly undefined value
6:   return show ? team.subvar : '';
                   ^ undefined
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKfAUwEMBbALjAH4BvAZ0wCMA3OgCcWnfIMLYA5gF8AlGHaowYXCVFhOAC0RgAvGFqMwAQn3ZMMGAG4lYW4Jr5Mg0lp2sD9BgDpu-IWAsAORBNtJAA

I'd expect flow to understand that the branch around constant `show` meant team must be `{subvar: string}` and not `null` or `void`.

As expected without extracting the variable `show` flow works as expected.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKfAUwEMBbALjAH4BvAZ0wCMA3OgCcWnfIMLYA5gF8AlGHaowYQTXyZBpWozABCALxhsmGDDZhtDAHTd+QsCwDkjgNyppQA

**Comment by SamChou19815** [comment]
This kind of refinements are out of scope.
