### ISSUE TITLE
"flow port" fails on "@type" JSDoc annotation within a function

### ISSUE THREAD

**Issue by ameenetemady** [facebook/flow#435]
running "flow port" fails when a function body contains a "@type" annotation. For example this fails:

``` javascript
/**
  @param {number} x
  @return {number}
 */
function square(x) {
  /**  @type {number}  */
  var y = x*x;
  return y;
}
square(5);
```

Removing it, will work.
Is this a known issue?

**Comment by avikchaudhuri** [comment]
flow port supports an ad hoc subset of JSDoc. This is a known issue.

**Comment by mroch** [comment]
this command has rotted in the past few years so we removed it. if there's still interest, it should be rebuilt on top of newer capabilities we're building around comment parsing and type printing.
