### ISSUE TITLE
Object.assign throws false positives

### ISSUE THREAD

**Issue by anfedorov** [facebook/flow#4354]
False positive errors when [typechecking](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAN6phgAeAXGAEZxwyoC+6AbgIYBOYDKTAB5RgCs8AYwwA6HgGcFASwDmAOwAUVCmCwMMfAK4F2AGh3laDKDxgLTFsAEogA) code using `Object.assign`, e.g.:

    /* @flow */

    type T = {
      x: bool
    }

    var o = Object.assign(
      { y: true },
      { x: false },
     )

Reports error

    7: var t = Object.assign(
               ^ property `x` of object literal. Property not found in
    8:   { y: true },
         ^ object literal

**Comment by asolove** [comment]
Note that there are also [false negative issues with Object.assign](https://github.com/facebook/flow/issues/2124).

**Comment by SamChou19815** [comment]
Unlikely to fix. Use spread instead.
