### ISSUE TITLE
can not use the word "static" as an export

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4355]
![image](https://user-images.githubusercontent.com/15365418/28045745-cfe76790-6593-11e7-99dd-1430bbf92961.png)

The seamless-immutable library exports a "static" value to be used like so:

```js
import { static as Immutable } from 'seamless-immutable'
```

however flow does not allow creating a flow-type definition for this in any way.

**Comment by goodmind** [comment]
I think it's impossible to name variable `static` in Babel too
