### ISSUE TITLE
Proposal: Add $Recurse<N> utility type so type-at-pos can accurately display recursive types

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4358]
It is already possible to create recursive types in flow, for example:

```js
type T = { t: T };
const t = {};
t.t = t;
(t: T);
```

Since type-at-pos has to output types that would be valid for pasting anywhere, it is unable to output `{ t: T }` because `T` would be an invalid type identifier in any other file. **Instead the output is as follows: `{ t: any }`** which — while *technically* a valid type that can be pasted anywhere — ends up dropping a bunch of important type information in the process by using `any`. This proposed utility type would allow type-at-pos to output types that would be valid anywhere while maintaining the recursive type information.

## `$Recurse<N>`

`N` is a positive integer literal representing the number of "steps" up the object/array chain this type represents. For example:

```js
type T = { t: $Recurse<1> };
const t = {};
t.t = t;
(t: T);
```

```
              ┌──── N ─┐
{ t: $Recurse<N> }     │
└────────────────┘  1 ─┘
```

Nested recursion:

```js
type ABC = { a: { b: { c: $Recurse<3> } } };
const foo = { a: { b: {} } };
foo.a.b.c = foo;
(foo: ABC);
```

```
                        ┌──────── N ─┐
{ a: { b: { c: $Recurse<N> } } }     │
          └────────────────┘      1 ─┤
     └───────────────────────┘    2 ─┤
└──────────────────────────────┘  3 ─┘
```

Works with arrays and tuples as well:

```js
type RecursiveTupleArray = [ number, ?Array<$Recurse<2>>, null ];
const ref = [ [ 1, null, null ] ]
const foo: RecursiveTupleArray = [2, ref, null];
ref.push(foo);
```

```
                          ┌─────────── N ─┐
[ number, ?Array<$Recurse<N>>, null ]     │
           └────────────────┘          1 ─┤
└───────────────────────────────────┘  2 ─┘
```

Also note that the recursion is for the types and does not have to have javascript referential equality like in the examples above, this would work just as well:

```js
type MathExpressionNode = {|
  type: 'MathExpression',
  op: '+' | '-' | '*' | '/',
  left: MathExpressionNode | number,
  right: MathExpressionNode | number,
|}

const additionNode: MathExpressionNode = {
  type: 'MathExpression',
  op: '+',
  left: 5,
  right: {
    type: 'MathExpression',
    op: '*',
    left: {
      type: 'MathExpression',
      op: '-',
      left: 7,
      right: 1
    },
    right: 2
  }
}
```

Running `flow type-at-pos index.js 8 7` should output:

```js
{|left: number | $Recurse<1>, op: '*' | '+' | '-' | '/', right: number | $Recurse<1>, type: 'MathExpression'|}
```

Instead of what it does now:

```js
{|left: number | any, op: '*' | '+' | '-' | '/', right: number | any, type: 'MathExpression'|}
```

<details>
<summary>original text</summary>
<blockquote>
Minimal case: <a href="https://flow.org/try/#0C4TwDgpgBAKlC8UDeVgC5ZQL4G4BQAxgPYB2AzsKgsrnsAHSWLD4AU6sAlDkA">try flow</a>

```js
type T = { t: T };
const t = {};
t.t = t;
(t: T);
```

The result of `type-at-pos index.js 4 2` is `{t: any}`

Ideally the displayed type information would use the identifier for the type itself when a recursive type was found (e.g. `{t: T}`) or something to signify that it is a recursive type and **not** in fact `any`: `{t: self}`, `{t: recursive}`, or really anything other than `any`.
</blockquote>
</details>

**Comment by vkurchatkin** [comment]
> that it is a recursive type and not in fact any: {t: self}, {t: recursive}

The problem with this approach that it's not going to be a valid type that you can paste in your code somewhere.

**Comment by jcready** [comment]
Is that the intended purpose of type-at-pos? I ask because I nuclide is using the same functionality to display autocomplete and tooltip type hints, so having it report that some type is `any` when it is in fact just recusive is rather frustrating.

Additionally it seems rather pointless to display `any` instead of `self` or `recursive` or even `T` (the identifier for the type itself) for the sake of a valid type you can paste into your code *anywhere*. Because you could just make type-at-pos just just always output `any` and it would be "valid". I'd rather it either produce a valid type I could paste anywhere *in the same file* (meaning you could use `T`). Or possibly provide some CLI flag for it so that nuclide could hook into it for much more helpful type hints.

**Comment by jcready** [comment]
Alternately a new utility type could be introduced: `$Recurse<N>` where `N` is any positive integer representing how many steps up the object chain this type represents.

```js
type T = { a: { b: { c: $Recurse<3> } } };
const t = { a: { b: {} } };
t.a.b.c = t;
(t: T);
```

This would allow type-at-pos to output types that would be valid anywhere while maintaining the recursive information. From my first example the output would be `{t: $Recurse<1>}`.

**Comment by jcready** [comment]
> The problem with this approach that it's not going to be a valid type that you can paste in your code somewhere.

@vkurchatkin using polymorphic types already breaks this rule. **[Try Flow](https://flow.org/try/#0PTAEDMHtIOgKwM4CgAuBPADgU1AMWgDwAqAfKALygDeE0AXKEaAL5IAmWAxgDYCGATjgBuA2pAb5IBAIwkgA)**

```js
// foo.js
type Foo<T> = { foo: T }
declare var foo: Foo<1>
```

```
$ flow type-at-pos foo.js 3 15
Foo<1>
foo.js:3:13,3:23

See the following locations:
foo.js:3:18-23:
type application of polymorphic type: type `Foo`
```

If the goal of `type-at-pos` is to simply produce a type that is valid **within the current file**, then why not simply use the actual type identifier for recursive types in place of `any`?

**Comment by jcready** [comment]
Interfaces also appear to break this rule:

```js
interface T { t: T };
const t = {};
t.t = t;
(t: T); // type-at-pos returns: {t: T}
```
