### ISSUE TITLE
React defaultProps should behave the same as functional component argument destructuring

### ISSUE THREAD

**Issue by dounan** [facebook/flow#4359]
From [the docs](https://flow.org/en/docs/frameworks/react/#toc-adding-types-for-react-component-props):

> Note: You don’t have to mark your defaultProps as optional properties in your props. Flow knows how to handle them properly.

This seems like the wrong choice to me. IMO it would be better if you explicitly mark props that are optional as optional, and have `defaultProps` refine the types of the properties on `this.props`. There are two advantages to this behavior:
1. The "public" api of the component is faithfully represented by the type of `props`.
2. This is the current behavior when using functional components with default props (via destructuring).

More details and example here:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAAV6OAM5gAvGADeqMGBz0AbhgAmZVQCEeAETJQKAVxiFhcHAH4AXGAB2hrACMy+ADSoAvl1RRDtmhhwtmAAYrYAwgx4tmS2hAAU0opwKupauvpGJmY4kmAAjB42OaIAlDJyYMDAYADqBADW4hTiZAAe-DQaAHRgAKJKsWCEABZwhgDmI8zJqRraegbGpiJMYBji5oSBthQwrmCwiJXVYFQErDQwPGCsUBgx4hjEji0aYEHDIwLqSyZgSj2hjI3RONUAvBuAAD3KudbKJiLYbPYnC48rM1PMMn8VuYuB50FQYC1xOEiaJRJFcEFYsR2oRYqpxORqIRupTojSKvJ4RRtlQwL8sjixHkksoMelFkKcjZClx5MkxMURKJ5bcGS54uVZPJ5KcAJJgBDjGCqMDtTrEUYbYZwI2NA6OQzEZ4CuBkUS2Jis0LwJBQAhUD1gHjjW1gLAUBpkSp6mrotILTLLHJ2IIAWi2Oz2BwIEYo9j213V9xi61pg3wPG2WAEocMsaqNUMogEz1BuqbYHBgCI9xuw+F2JEOZz4PLW0TdRWThOYqUpkRq-H4oA

**Comment by asolove** [comment]
I think with the changes to `Component` typing, the ship may have sailed on this. `Component<Props, State>` now pretty clearly defines that `Props` is the "internal type" of the props after getting the defaults merged in.

Similarly, functional components can now have a `defaultProps` property that works the same as a React Component's.

I think [this updated example of your code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG51CBPHMsAAV6OAM5gAvGADeqMGBz0AbhgAmZVQCEeAETJQKAVxiFhcHAC4wAO0NYARmXwAaVAF8uqKIes0McazAAMWsAYQY8azJrQgAKaUU4FXUtXX0jEzMcNyss0QBKGTkwYGAwAHUCAGtxCnEyAA9+Gg0AOjAAUSVosEIACzhDAHM+5kTkjW09A2NTESYwDHFzQn9rChhnMFhEYtKwKgJWGhgeMFYoDCjxDGJ7Oo0wAN6+gXUZkzAlDcMyVr2yoBeDcAAHvFQ7WUTEaxWWwOJySBTKNSTNIfObmLhuVAhcK4ALRQitd4ZdFiBEJJEpKbpWZZKwARg86AAPDiIviYsAAHzoKgwOriUL80SiXGRAlgRqEaKqcTkaiEsUcwjMvJbEBcorySEUVZUMDE2kicRSClJZGpaYkulgRlceSsazqfCxQqyeTyfYASTACEGMFUkqaZBoLyWvTgvuqW3shmItwNcDIomsTEJwXgSCgBCoybAPEGEbAWAoVTIxU9ZXGFupaKyNgCAFoVmsNlsCMWKLYNqdzvorgIE2RuvgeKssAIC4YKyUyoZRIPCTP9oDAER7M-BkJsMLsjnwCP6S1aiTEx8pKKtRoxxSxWNQzKFAqVUU5PKAA) shows that the interface is now pretty consistent between functional and class-based Components.

**Comment by dounan** [comment]
Yep, Flow 0.53 fixes this nicely. Especially nice that we don't have to specify typing for defaultProps anymore since that was just redundant. Closing
