### ISSUE TITLE
Add an option to preserve colors when piping into less

### ISSUE THREAD

**Issue by Ptival** [facebook/flow#436]
Most programs provide a way of saving color information when piping the output, in order to use with a following color-aware command, for instance:

    grep --color=always

or

    git diff --color=always | less -r

It would be nice for flow check to have a similar flag.

**Comment by mroch** [comment]
heh, I knew this would come up one day. we should definitely add it. naming it will be harder, though.

see the commit message in https://github.com/facebook/flow/commit/d31e06116aa7c205b27640f1509f3af73a0c2d1c

**Comment by mroch** [comment]
for the record, i think hack's and flow's CLIs are different enough, and `--color` meaning output coloring is common enough, that we should just call it `--color` and diverge from hack here.
