### ISSUE TITLE
$ReadOnlyArray and type-at-pos

### ISSUE THREAD

**Issue by mpal9000** [facebook/flow#4361]
Hello, `flow type-at-pos ...` returns "(unknown)" for each `const` below.

```javascript
const readOnlyArray:$ReadOnlyArray<string|number> = ['a', 2]

type Obj = {a:string, b:number, c:$ReadOnlyArray<string>}
const obj:Obj = {a: 'A', b: 2, c: ['C']}

type Tuple = [string, number, $ReadOnlyArray<string>]
const tuple:Tuple = ['A', 2, ['C']]

type Arr = Array<string|number|$ReadOnlyArray<string>>
const arr:Arr = ['A', 2, ['C']]
```

**Comment by jcready** [comment]
Looks to have been resolved by https://github.com/facebook/flow/commit/0338b898d4e14124c5e16f7bf4ea4c1b8345843f

**Comment by istarkov** [comment]
Want to add that I have the same issues in projects with modern relay inside. As flow type of lists etc generated by modern all are ReadOnlyArrays.

**Comment by darichey** [comment]
This works now.
