### ISSUE TITLE
"unexpected token import" on dynamic import

### ISSUE THREAD

**Issue by barbalex** [facebook/flow#4362]
Seems like dynamic imports should work since https://github.com/facebook/flow/pull/3544.

So I must be doing something wrong in my first dynamic import here:

    // @flow
    import Loadable from 'react-loadable'

    import LoadingComponent from './LoadingComponent'

    const AsyncActors = Loadable({
      loader: () => import('./Actors'),
      loading: LoadingComponent,
    })

    export default AsyncActors

This code provokes "unexpected token import" on the import statement.

I am using flow-bin v0.49.1.

**Comment by barbalex** [comment]
This still happens with flow-bin v0.53.1

**Comment by rkurbatov** [comment]
I use 'babel-plugin-dynamic-import-node' for jest babel config and `babel-plugin-syntax-dynamic-import` for webpack. That helps.

**Comment by barbalex** [comment]
Thanks. But I don't want to eject from create-react-app.

**Comment by joaquindk** [comment]
I'm getting the same issue with dynamic imports, despite using the babel plugins. Is this being looked into?

**Comment by TrySound** [comment]
@joaquindk Is the problem with flow or babel?

**Comment by joaquindk** [comment]
Definitely flow @TrySound

**Comment by TrySound** [comment]
The latest version do not shows unexpected token
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgFwBQDkAdMAM6xoCmuAFigHYDmhAlEA

**Comment by joaquindk** [comment]
Nice! Thanks @TrySound

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
