### ISSUE TITLE
[Proposal] $ExtractReturnType<> for a function

### ISSUE THREAD

**Issue by ericapply** [facebook/flow#4363]
Currently there is no way to extract a return type of a function.
For instance, if you have 
```
const mapStateToProps = (state, props) => ({
  booking: selectors.getBooking(state),
  listNavBar: selectors.getListNavBar(state),
})
```
and selectors.getBooking returns `BookingState` and selectors.getListNavBar returns `ListNavBarState`
then I want `$ExtractReturnType<mapStateToProps>` to be resolved to type equivalent to following
```
type MapStateToPropsType = {
   booking: BookingState,
   listNavBar: ListNavBarState,
}
```

**Comment by TrySound** [comment]
Redux problems can be solved with generics. The bad thing right now is intersection
https://github.com/facebook/flow/issues/4325

**Comment by Andarist** [comment]
This could be useful for other cases too I think, kinda working like `typeof` types, but just extracting part of what `typeof` would have returned.

**Comment by freddi301** [comment]
seems to work with 0.50.0

```javascript
function extractedReturnType(x: number, y: string) {
  return {
    name: 'fred',
    age: 5,
    backpack: ['hello', 34]
  }
}

type $ReturnType<T, F: (...args: any) => T> = T;

const x = extractedReturnType(4, '');

declare var y: $ReturnType<*, typeof extractedReturnType>;

(y.name: string);
(y.name: number); // Error
```

**Comment by sibelius** [comment]
You can also use $Call helper

```
type $ReturnType<Fn> = $Call<<T>((...Iterable<any>) => T) => T, Fn>

type y = $ReturnType<typeof extractedReturnType>;
```

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
