### ISSUE TITLE
Generic types in chain of arrow types

### ISSUE THREAD

**Issue by punksta** [facebook/flow#4369]
we can write chain of arrow types; 
```
type t = {u: number};
type foo = (t) => (t) => /*...*/ t
```

sometimes T has generic type: 
```
type t<G> = { u: G }
type foo = <Bar>(t<Bar>) => (t<Bar>) => /*...*/ t<Bar>
```
And let's say we have  `<Bar>(t<Bar>) => E ` where `E` is some chain or arrow types. In this case: `Bar` should be acceptable in any generic types of expression `E` in 

<B>example :</B>

I want add generic type to next function with saving ability to write type of function;

```
const mergeNumbers: (Array<number>) => (Array<number>) => Array<number> = 
    (first: Array<number>) => (second: Array<number>) => [...first, ...second]

let  result : Array<number> = mergeNumbers([1])([2])
```

All my variants does not work:

1. `some incompatible instantiation of T`
```
const mergeLists: <T>(Array<T>) => (Array<T>) => Array<T> = <T>(first: Array<T>) => 
    (second: Array<T>) => [...first, ...second]
```
2. `identifier T. Could not resolve name `
```
const mergeLists2 : <T>(Array<T>) => (Array<T>) => Array<T> = (first: Array<T>) => 
    (second: Array<T>) => [...first, ...second] 
```
3. `some incompatible instantiation of  T ` for second apply of `[""]`
```
const mergeLists3 = <T> (first: Array<T>) =>  (second: Array<T>) => [...first, ...second]      

const showuldWork3 = mergeLists3([""])([""])
```

**Comment by mwalkerwells** [comment]
```js
type MergeLists2<T, U: T> = (Array<U>) => (Array<U>) => Array<T>

const mergeLists2: MergeLists2<*, *> = (first) => (second) => ([...first, ...second])
const foo2: Array<string | number> = mergeLists2([1, 2])(['', ''])
```

**Comment by norbertpy** [comment]
@mwalkerwells Will not work if you use the type twice:

```javascript
type MergeLists2<T, U: T> = (Array<U>) => (Array<U>) => Array<T>

const mergeLists2: MergeLists2<*, *> = (first) => (second) => ([...first, ...second])
const foo2: Array<number> = mergeLists2([1, 2])([3, 4])
const foo3: Array<string> = mergeLists2(['a', 'b'])(['c', 'd']);
```
See [flow.org/try/#...][1]
Stackoverflow question: [flow generic type for function expression][2]

[1]: https://flow.org/try/#0C4TwDgpgBAshBOBzCAZAlgZ2BgTAHgBUAaKAVQC4oCA+KAXigAoBBeeAQxD1OoEp7aLNp258BUVhy40AUDIDGAewB2WKAFsEydFlyU4SVJmz4AVCVO0GjAGZp4WfnUEYIS5QBMnggNoA6ALsHYBIAv1d3DwBdXjl3NRtFRRxKSRFlAFd1ACMEKw0tI10cRh8ARhIcGNKAZhIAFhiFFQSkmtThLix4NGVEfM1DHRNSgHJ2UZJR7NHqn1H5SahRj1neAG4gA

[2]: https://stackoverflow.com/q/46596235/4228942
