### ISSUE TITLE
Inconsistent behavior when passing `undefined` to a function

### ISSUE THREAD

**Issue by danvk** [facebook/flow#437]
@gabelevi points out that [this doesn't type check][1]:

```javascript
function foo(x?: number) {}

function bar() {
    foo(undefined);
}
```

It seems like it should.

There is an observable distinction between `foo(undefined)` and `foo()` in that `arguments.length` will have a different value. So there is an argument that the current behavior isn't totally wrong. But distinguishing between an explicit and implicit `undefined` is generally considered bad API design.

From IRC:

danvk: flow-help: I’m puzzled by the error in this gist: https://gist.github.com/danvk/894d978ee9229400b72c
danvk: I’m passing a value that’s Object|undefined to a constructor that expects an optional Object parameter
danvk: which seems like it should be OK
glevi: Like this is an error: http://tryflow.org/#90ca4cbbaf98fe3d5c14eb8a8e2c53e1
glevi: But this is not: http://tryflow.org/#434a04ebff6649df1f66f222e453c75d
glevi: danvk: Sure...we seem to be somewhat inconsistent with what we let flow into an optional param...this doesn't work either: http://tryflow.org/#c788cea5d233f6449ee51b6d75297dbf

[1]: http://tryflow.org/#c788cea5d233f6449ee51b6d75297dbf

**Comment by danvk** [comment]
> danvk: the issue boils down to whether explicit and implicit undefined should be considered the same thing
> glevi: danvk: I used to think no and then I read the default parameter spec and now I think they should be...I'm just not happy about it

**Comment by mroch** [comment]
it seems to me that if we don't allow this, then multiple optional params, e.g. `function foo(x?: number, y?: number) {}` are significantly less useful... you can only do (pseudo-signature) `foo([x[, y]])`, not `foo([x], [y])`.

`foo(undefined, 123)` seems like a reasonable thing to want to do.

**Comment by samwgoldman** [comment]
This is also an issue for parameters with default values:

```javascript
/* @flow */

function test(foo = "bar"): string {
    return foo;
}

test(undefined) // False failure: undefined ~> string
```
