### ISSUE TITLE
Is it possible to coerce a generic from optional to required?

### ISSUE THREAD

**Issue by zyklus** [facebook/flow#4379]
e.g.

```js
function getEnforce<T>(data: T): T {
  if (data == null) {
    throw 'data is required';
  } else {
    return data;
  }
}

function takesAString(data: string) {
}

const foo: ?string = 'asdf';

takesAString(getEnforce(foo));
```

I effectively want:

```js
function getEnforce(data: ?string): string {
```

but retaining the generic as well.

**Comment by jcready** [comment]
```js
function getEnforce<T>(data: ?T): $NonMaybeType<T> {
  if (data == null) {
    throw 'data is required';
  } else {
    return data;
  }
}
```

[Try Flow](https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZQKJmHAThVAHgBUA+ACgBMBDKagLkQH5iBKRgEgDkEBZagJ4AjVMQEAHImUQBvAFCJEMYIiq1qiALybEYEABt9rWQsWIoAC1xwA7ogDkNOkoDOiXKgCOIGB8r2AblMAX0RUfRdUEzN3dBBcJCdqIMVguTS5UEhYBHNqAGtUFwBBAGUoXBgwZDU6RhcKquRjeQyIBAbEHDhGJgbK6q0HahdKYEC5OTpCkvKBmrRMbDwCcm7WVgCgA)

**Comment by zyklus** [comment]
lol, I was trying to make the <T> optional, whoops!!  thanks
