### ISSUE TITLE
documentation is missing new features from blog

### ISSUE THREAD

**Issue by weakish** [facebook/flow#438]
The following features mentioned in blog is missing in document:
- [ ] Import type
- [ ] Type cast
- [ ] Flow comments
- [ ] Bounded polymorphism

**Comment by avikchaudhuri** [comment]
Yeah, doc updates are long overdue :( Will get to them soon.

**Comment by mrjackdavis** [comment]
8 months later...
As a newcomer to flow, I've found the docs quite hard to understand.

**Comment by nmn** [comment]
@mrjackdavis Soon now.

**Comment by vkurchatkin** [comment]
New documentation seems to cover everything on the list
