### ISSUE TITLE
Declare currentTarget as HTMLInputElement in SyntheticInputEvent

### ISSUE THREAD

**Issue by Derrik** [facebook/flow#4381]
target is set to be an HTMLInputElement but not currentTarget. 
https://github.com/facebook/flow/search?utf8=%E2%9C%93&q=SyntheticInputEvent&type=

Is this by design or a bug? 

Thanks!

**Comment by jcready** [comment]
Because `target` is the source of the event while `currentTarget` is the element the event listener is attached to. So it is guaranteed that `target` will be an `HTMLInputElement`, but `currentTarget` could be either an `HTMLInputElement` or any `HTMLElement` that can contain an `HTMLInputElement`.

**Comment by Derrik** [comment]
Gotcha, that makes sense. Thanks.
