### ISSUE TITLE
flow init command not found after installing flow on my project

### ISSUE THREAD

**Issue by Hayko1994** [facebook/flow#4382]
I used npm for installing while the second command  node_modules/.bin/flow
 shows not found and after that flow init not found as well. In the package.json of my project I've found flow bin. What can cause this problem?

**Comment by gopaldevra** [comment]
Getting the same error?

**Comment by jimmythai** [comment]
@Hayko1994 @gopaldevra 
The same error occurred to my project, but I found a solution for it.
Try the code below. Cheers.

```
$ yarn add --dev flow-bin
$ node_modules/.bin/flow init
$ yarn run flow
```

**Comment by abharvey** [comment]
or with npm make sure you `npm run flow` and have the flow added to your scripts in package.json

**Comment by RayOconnor** [comment]
I was getting this error in the flow window despite having flow working via the terminal...

`Error:Timeout on starting language service process`

I downloaded the most recent version of phpStorm and the problem resolved itself.

**Comment by freedom9x** [comment]
Or just add flow-bin to global:
```
$ yarn global add flow-bin
$ flow init
```

**Comment by gknifefight** [comment]
> Or just add flow-bin to global:
> 
> ```
> $ yarn global add flow-bin
> $ flow init
> ```

@freedom9x - Realize this is a bit dated, but for google sake adding what I found after looking through this thread.  

From:  https://flow.org/en/docs/install/
"Flow works best when installed per-project with explicit versioning rather than globally."
"Note: you may need to run` yarn run flow init` before executing` yarn run flow`."

**Comment by intoro** [comment]
If it is installed in the project directory I had to use the command with the path:
`node_modules/.bin/flow -help`

or

`node_modules/.bin/flow -help`

**Comment by SamChou19815** [comment]
Not a flow issue

**Comment by Sahar-Nosrati-shanjani** [comment]
Please help me also,
the flow can not be added to package.json according to instructions and npm run flow does not work. What should I do?
