### ISSUE TITLE
Export types to JSON

### ISSUE THREAD

**Issue by anthonymuau** [facebook/flow#4385]
There is an issue with flow in that there's no way to export the flow types out to something like JSON.

The use case for us is for documentation, where we want to re-use the types to automate various aspects of our docs.

**Comment by TiddoLangerak** [comment]
I'm not sure if it's sufficient, but `flow ast [file]` gives a JSON ast with type annotations. Maybe you can use that to generate the documentation? It doesn't contain inferred types though, only explicit types.

**Comment by anthonymuau** [comment]
@TiddoLangerak That is what I was looking for! Thank you!
