### ISSUE TITLE
[possible inconsistency] Bounded generics

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#4387]
Not working:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAiAlgM44CGGAxgBYA8AggFxgDeY2+rpGATsQB2AczABfAHxgAvGAAUFahmJxBrRgEoZUxgG50XAgGUMcPniZTZbVAEgAJmUo1arEuSp1L+sfsy4CACU8ewBXajw+Sxl5RWVVdS1pHT8oUMElFUEwanMqPBMzC0YJOXMwiL5WYIrIyw1WQvNom1tzDFC+bJswMFsHJ09aBUzVLQ52zuy4rPEAGjsxVCWgA

Working:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAJgUwMYwIYBOmYAtnOgK4zEDkRlAHjWAN6qphha6HEAuATwAOxACIBLAM5C8fbAAsAPAEEAXKzCCR6yXwLiAdgHMwAXwB8YALxgAFHmx9xcA+uUBKa5eUBudp258Ik1hYgBlPjgiFUsbNk4ErikZOXl1CWlZBRi-TlM-Di4cIP5QsAAlTEpsTAIY6zsHJxc3TytvAoDi3jAoCgNHZwMwbCJZTAiozBjbegoagnVK6tqY93VJ6OVzP1MgA

The only difference is the context in which those typings are used, one is libdef and one is flow-typed javascript.

**Comment by vkurchatkin** [comment]
You need to upper bound to the function:

```js
unction createStore<A: { type: string }>(reducer: Reducer<A>): Store<A> {
	return {
  		dispatch(action) { return action },
	}
}
```

**Comment by Andarist** [comment]
@vkurchatkin yeah, ive managed to do that before, what my issue was about is that when declaring a libdef file the same usage PASSES just fine, but in the files with actual implementation it does not and I think this is an indication of the problem, or am I missing something?

**Comment by Andarist** [comment]
@vkurchatkin could u please take a look at this issue once again?
