### ISSUE TITLE
Disjoint unions using function

### ISSUE THREAD

**Issue by JuliaSklyar** [facebook/flow#4390]
Disjoint Unions won't work if use function.
Next code gives me an error, because I use `isTypeNumber` function for disjointing.
But `if (post[0].type === 'number')` line will fix it.

```js
type FirstContent = { id: number, type: 'number' };
type SecondContent = { text: string, type: 'string' };
type Content = FirstContent | SecondContent;
type Post = Array<Content>;
const post: Post = [{ id: 1, type: 'number'}, { text: 'text', type: 'string' }];

const isTypeNumber = (block: Content): boolean => block.type === 'number';

//if (post[0].type === 'number') {
if (isTypeNumber(post[0])) {
  console.log(post[0].id);
}
```

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgE4DOGAwnAHYZ71gC8YA3sQCYBcYtArgFsARnlIAaMNny8A5AJFjZAXwDcmXAQDKeAMZ1ONeowwt2DAB4ZelUsVoBzSdLxzb9hyvUuwRhk1YSCmo6f1MAHzAdfVpDUJNvTTAABThKMwBBUlIAQywAHj8TAD51GPScNOsUqrMAbTYwLl4ARmdNOQVRUhVJNktq2QHZdpkwWXdHFQBddVRy02JyABVNADkhbrMACmF4XQBrXiL6AEpeYTg4GDwc2hZisD24Q4A6H2ZP8a6lOeBgYhQMDbSqUOoABmm7ySn1Y8k2SlO7FQgOBS1W+A2ilIIKqEOmpyRbFQYDA5WueFe8AcuLBkNeXFO6mUqCAA)

It's important for our current project. We added `flow` into existing code base, where quite a lot of such boolean return functions checking type of content.

**Comment by vkurchatkin** [comment]
`%checks` should solve this:

```js
const isTypeNumber = (block: Content):boolean %checks  => block.type === 'number';
```

**Comment by JuliaSklyar** [comment]
Thanks Vladimir, it helped!

**Comment by JuliaSklyar** [comment]
Do you think I can find description of '%checks' annotation in the documentation?

**Comment by vkurchatkin** [comment]
No, it's not there yet

**Comment by ntomallen** [comment]
What does %checks do then?

**Comment by mrkev** [comment]
It tells flow a function does a refinement on it's arguments, iirc 👍
