### ISSUE TITLE
React Native composable Stylesheets

### ISSUE THREAD

**Issue by ayroblu** [facebook/flow#4394]
Flow version: 0.47.0

I write some styles like:

``` javascript
const styles = StyleSheet.create({
  text: {
    color: 'red'
  }
})
styles.subText = StyleSheet.flatten([styles.text, {fontSize: 14}])
```

Flow doesn't recognise this. I then tried:

``` javascript
const preStyles = {
  text: {
    color: 'red'
  }
}
preStyles.subText = {...styles.text, fontSize: 14}
const styles = StyleSheet.create(preStyles)
```

Also, isn't supported. Would like either, or both of these syntaxes to be supported. 
The actual error I get (variables have slightly different names):

![](https://puu.sh/wKIhh/1e311e309f.png)

**Comment by jcready** [comment]
The former isn't supported because [react-native defines the keys which can exist on a StyleSheet instance](https://github.com/facebook/react-native/blob/master/Libraries/StyleSheet/StyleSheet.js#L21-L22) when you create it. Not sure why the latter wouldn't be supported.

**Comment by SamChou19815** [comment]
This is not going to be supported since we don't support dynamically changing the object shape after initialization
