### ISSUE TITLE
module.name_mapper does not work

### ISSUE THREAD

**Issue by barbu110** [facebook/flow#4397]
I have the following `.flowconfig` fragment from my file:

```
[options]
module.name_mapper='styles\/.+' -> '<PROJECT_ROOT>/build-system/flow/StyleImport'
```

The file at `<PROJECT_ROOT/build-system/flow/StyleImport` looks like this:

```js
/* @flow */

type StyleModule = { [ key: string ]: string };
const emptyStyleModule: StyleModule = {};

export default emptyStyleModule;
```

However, when I run `npm run flow`, I get the following message, for every `import` of this kind:

```
resources/client/ui/PageletNavigation.js:10
 10: import FlexStyles from 'styles/FlexUtils';
                            ^^^^^^^^^^^^^^^^^^ styles/FlexUtils. Required module not found
```

What is wrong?

**Comment by billschaller** [comment]
What version are you using? Can you try adding the file extension to the mapping?
