### ISSUE TITLE
props of React element Hello. This type is incompatible with props of React element Hello: possible circular dependency issue?

### ISSUE THREAD

**Issue by hackhat** [facebook/flow#4404]
Min example:
In some place I have `<C fn={() => 4}/>`  and in another `<C fn={() => {}}/>` flow complains that the returns are not of the same type. What is even stranger is that this only happens when I import some files and stop complaining when I remove the import...

Not sure why it happens but here it is.

Environment:

 - StudentClassroom uses HomeworkList
 - Overview uses HomeworkList
 - HomeworkList has no props

```
// @flow
import React from 'react';
import withStyles from 'isomorphic-style-loader/lib/withStyles';
import {connect} from 'react-redux';
import {sortBy} from 'lodash';
import s from './HomeworkList.scss';
import type {User} from '../../flow';

class HomeworkList extends React.Component {
  props: {};

  render() {
    return null;
  }
}

const mapStateToProps = (state, ownProps) => {
  return {};
};

export default connect(mapStateToProps)(withStyles(s)(HomeworkList));
```

And the error is:

![image](https://user-images.githubusercontent.com/11173732/28299206-c974e586-6b6f-11e7-91e6-dde5e116464b.png)

![image](https://user-images.githubusercontent.com/11173732/28299314-5f87ad9c-6b70-11e7-8f9b-3422bd75b762.png)

Not sure why the error from `StudentClassroom.js:39` that `props of React element "HomeworkList". This type is incompatible with 21: export default connect(mapStateToProps)(...` has anything to do with how another component `Overview.js:36` is using the component `HomeworkList`.

Something like this:
```
/* @flow */

const C = (props:{fn: Function}) => {
    return null;
}

const A = () => {
	return <C fn={() => 4}/>
}

const B = () => {
	return <C fn={() => {}}/>
}
```

or 

```
/* @flow */

const C = (props:{fn?: Function}) => {
    return null;
}

const A = () => {
	return <C fn={() => 4}/>
}

const B = () => {
	return <C/>
}
```

But doesn't error here.

**Possible ways to fix**

 - If I remove the props from overview it stop having this recursive error.
 - If I remove the `import type {User} from '../../flow';` from the file also removes the error;
 - If the component `HomeworkList` is only used in one place no error (imports are still there, just not used); If is used in 2 places error!

Is a very very strange error and hard to debug.

**Comment by hackhat** [comment]
Debugging and some previous commits looks like this:

![image](https://user-images.githubusercontent.com/11173732/28389961-1b0d2b54-6cd0-11e7-8967-903b3aab87c9.png)

props of React element `HomeworkList`. This type is incompatible with props of React element `HomeworkList`. See: src/components/TeacherClassroom/TeacherClassroom.js:53
  Property `getAddHomeworkButtonProps` is incompatible: object literal. This type is incompatible with undefined. See: src/components/TeacherClassroom/TeacherClassroom.js:55

This has some recursion, not sure I understand why?

**Comment by hackhat** [comment]
![image](https://user-images.githubusercontent.com/11173732/28390509-43f33246-6cd2-11e7-9c5c-9f91e8e95006.png)
For example here is complaining that client A of component HomeworkList returns undefined and is not compatible to client B of component HomeworkList that returns an object.. doesnt make sense. why flow checks who the users/clients of a component to be the same?

**Comment by hackhat** [comment]
![image](https://user-images.githubusercontent.com/11173732/28390645-d1b672e6-6cd2-11e7-9f20-a2d1f7752b52.png)

So yes, flow tries to have all the users of the component with the same return on the function. You can see here where I try to return 2 in one example and undefined in another.

if all users that provides the function returns a number (2, 3) flow doesnt complain...

**Comment by hackhat** [comment]
Can't believe that fixed.

**Comment by billschaller** [comment]
So... did you fix this yourself?

**Comment by hackhat** [comment]
Yes I did. You can see the previous comments how has been solved (quite long explanation). But I think is still a bug in flow type.

**Comment by billschaller** [comment]
@hackhat Can you create a repro for the bug using https://flow.org/try/ ?

**Comment by hackhat** [comment]
@billschaller I'm afraid not, this was happening in a large project and I couldn't figure out how many things  must be there to reproduce this bug. :/ I wish I could.

**Comment by hackhat** [comment]
Got this issue again

![image](https://user-images.githubusercontent.com/11173732/28823692-c818fd42-76b6-11e7-91b5-2a16266aeef6.png)

I will try to investigate a bit more and reproduce.

**Comment by hackhat** [comment]
Again I can't reproduce in the /try/ I think it might be related to multiple files. Here is something that should fail if would be in different files.

```
/* @flow */
import React from 'react';

class NotificationList extends React.Component {
  props: {
    viewportSizeType: string,
    studentId?: string,
  };
  render(){return null}

  }
    
    
 const Comp = () => {
  
  return (
    <div>
    	<NotificationList viewportSizeType="x"/>
    </div>
    
    )
  }
    
 const Comp2 = () => {
  
  return (
    <div>
    	<NotificationList viewportSizeType="x" studentId="xx"/>
    </div>
    
    )
  }
```

**Comment by hackhat** [comment]
If you look at 
![image](https://user-images.githubusercontent.com/11173732/28823989-070d9c82-76b8-11e7-8cb2-1497eee94fce.png)

you notice that flow is trying to validate the props of first usage with the props from the second usage, crazy right? Should validate the props with whatever is defined in the component used.

**Comment by hackhat** [comment]
Got it, now only fails when the `connect` is there:

```
class NotificationList extends React.Component {
  props: {
  };
}

const mapStateToProps = (state, ownProps) => {
  return {};
};

export default connect(mapStateToProps)(NotificationList);
```

**Comment by hackhat** [comment]
To fix this issue I need to use my component with all optional props `<NotificationsList viewportSizeType="small" organizationId={void 0} classroomId={void 0} homeworkId={void 0} studentId={void 0}/>`

**Comment by hackhat** [comment]
Fixed then joined all these props under a object in a single prop and getting the same error again. I found another workaround:

```
let ExportedComponent = connect(mapStateToProps)(withStyles(s)(NotificationsList));
/*:: ExportedComponent = NotificationsList; */
export default ExportedComponent;
```

Not sure if people are happy with this hack, but seems like flow doesn't check props set in the `mapStateToProps` anyway.

**Comment by asolove** [comment]
@hackhat I'm having a hard time reading through all the history here and figuring out what exactly is still the open question/complaint. Can you please put together a minimal example based on your current example so we can help you get an answer or categorize this?

**Comment by hackhat** [comment]
@asolove I'm sorry but I can't figure out what is the problem, happens when I import some files. I tried to create a small project just to reproduce but doesn't happen :/ 

by the way I got the error again a few days ago.

**Comment by asolove** [comment]
Can you tell us a little more about the new error? I assume the code isn't sharable publicly, but would you be willing to do screen sharing so we could debug it? I'm happy to promise/sign that I won't share any details of the code other the Flow issue.

**Comment by asolove** [comment]
When you recently got the error, was there a circular dependency again? This is an issue that has been reported before, even if one side is a code dependency and the other side is a type dependency.

**Comment by hackhat** [comment]
Not sure if is exactly the same error but while working on something else I found this issue too:

[Option A:](https://flow.org/try/#0MYewdgzgLgBBCmAnAbgS2PCAWGBeGA3gFAwwCGAXDABRmIDmEVBAFvAJ5VgCuAtgEZIAvgEpmlGDwHC8APkIlSMRPCjdEYBUqUSAzDgBU5BhAB0bdgBpFpIQG5FQ66X5VaJ5mwA2XkFWiIqGD0osyucFCBwUJyWkoqahpx2uEABhAAJhmpMADUxozm8D4gzkr2jtYVRKCQsABmYDj4ZBDsYMA0ZD4AgiYiscSkCeqaCCjomFgA2t1efYUA1hwAurS9JqZ0jCIO1US0bR00A7jyQzC10DDI3dzwPXjkAO5kqA1N1ATLnDCpZKlLAUmIQLFQsEJRA5SNRbl57j0tlw+IJELsYAB6DFwFggbheDIwAByAHkACowepvLyKLE0OEIpERKL0dF0iC4-GEqmoGm07FXWAM+AAISeZFe70pn2+HCoqX4gOBnmKvnlEAgqUhu359LuotM4QCQVZdkx2I5eIJxPJlOputh+pFhuR0jRZvZnOtPJpomouyAA)
```
const services4 = {
  a: (args: {hey: number}): {a: number} => {
    return {
      a: 34 * args.hey,
    };
  },
  b: (args: {hello: string}): {b: string} => {
    return {
      b: `sdd` + args.hello,
    };
  },
};

const fn4 = async (allArgs) => {
  return services4[allArgs.key](allArgs.args);
};


(async () => {
  const valueA = await fn4({key: `a`, args: {hey: 4}});
  (valueA.a: number); // should NOT fail
  // (valueA.a: string); // should fail

  // const valueB = await fn4({key: `b`, args: {hello: `ss`}}); // < ========= commented out in option A
  // (valueB.b: string); // should NOT fail
  // (valueB.b: number); // should fail
})();
```
Has no errors, which is fine!

[But if I uncomment that line I get this error in option B:](https://flow.org/try/#0MYewdgzgLgBBCmAnAbgS2PCAWGBeGA3gFAwwCGAXDABRmIDmEVBAFvAJ5VgCuAtgEZIAvgEpmlGDwHC8APkIlSMRPCjdEYBUqUSAzDgBU5BhAB0bdgBpFpIQG5FQ66X5VaJ5mwA2XkFWiIqGD0osyucFCBwUJyWkoqahpx2uEABhAAJhmpMADUxozm8D4gzkr2jtYVRKCQsABmYDj4ZBDsYMA0ZD4AgiYiscSkCeqaCCjomFgA2t1efYUA1hwAurS9JqZ0jCIO1US0bR00A7jyQzC10DDI3dzwPXjkAO5kqA1N1ATLnDCpZKlLAUmIQLFQsEJRA5SNRbl57j0tlw+IJELsYAB6DFwFggbheDIwAByAHkACowepvLyKLE0OEIpERKL0dF0iC4-GEqmoGmKK6wBnwABCTzIr3elM+3w4VFS-EBwM8xV8cogEFSkN2tOxsLuItM4QCQVZdkx2I5eIJxPJlOpOvp+uFhuR0jRZvZnOtPJpomouyAA)

```
2:   a: (args: {hey: number}): {a: number} => {
               ^ property `hey`. Property not found in
15:   return services4[allArgs.key](allArgs.args);
                                    ^ object literal
7:   b: (args: {hello: string}): {b: string} => {
               ^ property `hello`. Property not found in
15:   return services4[allArgs.key](allArgs.args);
                                    ^ object literal
21:   (valueA.a: number); // should NOT fail
              ^ property `a`. Property not found in
21:   (valueA.a: number); // should NOT fail
       ^ object type
```

Why not it cares about what properties are where? Is a more basic version of the error I had with react components, but looks similar.

**Comment by asolove** [comment]
When you have problems to debug like this, it can help to start adding type annotations to things. In part because then Flow can tell you if it got something different than you expected, but also in part to see whether the idea you want Flow to figure out is even expressible in this type system.

In this case, with the things commented out as you did, Flow uses the one call to `fn4` to guess a type like `({key: "a", args: {hey: number}) => {a: number}`. When you uncomment the second call to `fn4`, Flow freaks out a bit because it doesn't match that. It now knows that it needs to handle the a and b cases, but isn't exactly sure of their relationship. Indeed, just trying to state the relationship in words is a bit tricky. There are two cases for both the inputs and the outputs, but the two are connected, so that `fn4` really has two alternate signatures.

Here's one way to represent those two signatures to Flow:

```js
/*:: 
	declare function fn4({key: 'a', args: {hey: number}}): {a: number}
	declare function fn4({key: 'b', args: {hello: string}}): {b: string}
*/
```

But I think this is beyond what we can expect Flow to be able to infer on its own.

**Comment by hackhat** [comment]
Thanks, might be useful if you can explain in more detail how you debugged.

Also can you explain how by adding a new call to a function can mess up the whole function definition, to me that makes 0 sense...

**Comment by asolove** [comment]
It's not that a second call messes it up, but that it teaches Flow that something complex is going on. After the first call, Flow makes a reasonable guess about the function's type that works for that call but isn't actually the full type. The second call exposes that the function's type is actually more complex and Flow doesn't want to start guessing, so it wants you to annotate the type. This is usually useful behavior, since the last thing we want to do is have Flow infer a type that makes our code correct by just accepting whatever we pass into a function.

**Comment by hackhat** [comment]
So flow figures out how a function is defined based on how it is used?

**Comment by asolove** [comment]
Within one module, yes. If the type isn't given explicitly on the function, flow infers it based on uses.

**Comment by hackhat** [comment]
Ok, thanks. Again I'm getting this error. Do you see anything that might be causing this? Here are the elements that might affect the error.

## Error:

![image](https://user-images.githubusercontent.com/11173732/29925368-09bb9350-8e58-11e7-9a90-d07bd5b48ee9.png)


## Usages:

src/components/popups/RequestDemo/RequestDemo.js:62

![image](https://user-images.githubusercontent.com/11173732/29925172-62df3758-8e57-11e7-8378-405564828cd9.png)

src/components/tokens/InviteTeacherToOrganization/InviteTeacherToOrganization.js:36

![image](https://user-images.githubusercontent.com/11173732/29925292-c721e8dc-8e57-11e7-9530-ba268582119b.png)

src/components/pages/LandingPageC/LandingPageC.js:66

and

src/components/pages/LandingPageC/LandingPageC.js:61

![image](https://user-images.githubusercontent.com/11173732/29925323-e781d380-8e57-11e7-9fb2-40bf091a1ff2.png)


## DashboardButton definition:

![image](https://user-images.githubusercontent.com/11173732/29925239-920d9f42-8e57-11e7-90b9-cd2de7cb0eda.png)

...

![image](https://user-images.githubusercontent.com/11173732/29925225-8805dafa-8e57-11e7-8beb-ea456c345002.png)

**Comment by asolove** [comment]
The question seems to boil down to what are the required props for that component. Can you post what flow thinks the prop type should be? I see several props that aren’t supplied in some of those usages, but maybe they are supplied from the wrapping HoCs. I would try annotating the export of DashboardButton to check its what you expect. 

It looks like you’re using flow < 0.52, which had a notoriously complex method for typing react components. It might be worth trying 0.53 or newer. You’ll have to move some annotations on the react components, but a lot of bugs were fixed and the errors should be more sensible.

**Comment by hackhat** [comment]
@asolove I've tried 0.53 but in my project had more than 6k errors, which is too much to migrate :/ I might think about it in the future, but the breaking changes are too big so I will stay on 0.52 for now.

The dashboardButton looks like this

![image](https://user-images.githubusercontent.com/11173732/29975664-1e866404-8f2f-11e7-8e28-43010c35ab2e.png)

![image](https://user-images.githubusercontent.com/11173732/29975670-2526ee28-8f2f-11e7-8d7d-46b95133c67a.png)

> Can you post what flow thinks the prop type should be?

How can I do that?

**Comment by asolove** [comment]
To ask Flow for the required props, you should be able to use whatever flow integration is in your editor. I know in VSCode I can just mouseover a variable and it shows me its type, which includes the type of the props on a component. If your editor doesn't do that, you can also use `flow type-at-pos` with the file name, line, and column number. If that doesn't help, you could try just making a jsx expression using the component and see what props you have to add to it before flow doesn't throw an error. 

 I am guessing it's the `& $PropertyType` but that might be causing trouble. Curious what actual keys/values that expects.
