### ISSUE TITLE
Do not require annotations for function parameters with defaults

### ISSUE THREAD

**Issue by TrySound** [facebook/flow#4408]
Now this code fails with `parameter `a`. Missing annotation`
```ts
export const fn = (a = '') => {};
```
But `a` can be inferred based on type of default.
Class properties do not require annotations with initialized prop.
```js
export class A {
  a = '';
}
```

**Comment by jcready** [comment]
The question is what type should flow infer from the default argument. Should it infer `string` as the type or the string literal `''`? I assume it would use the same method it uses for `typeof`, but I'm not sure.

**Comment by TrySound** [comment]
It should be consistent to class properties inferring.
