### ISSUE TITLE
$Values not working properly

### ISSUE THREAD

**Issue by andykais** [facebook/flow#4411]
Going over changelog for 0.50.0, `$Values` is implemented. However, both on my local machine (`flow version` reports 0.50.0) and on `master` on [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAGEAJAQQDkBxAUQH0AZAeSLIBUBJJisAXjADkAQwAOI4CKEBzAKbBSlWoxbsuFAZhwEwANyEwArjJJwYAExkAnPmADexctXrNWnbmAC+qfAE8RMsDYATQAFegUnZVc1GwASADV9I1wAHl9-OChdJONTC0sAPnQsPEIADwAuQNDwxyUXVXd+ATKBIA) $Values does not report errors when a variable typed with $Values of an object do not match any of them

**Comment by vkurchatkin** [comment]
In your example `CHANGE_LOCATION` has type `string`, so everything works as expected. See: https://github.com/facebook/flow/issues/2639

**Comment by andykais** [comment]
I guess I misunderstood the purpose of $Values, is its expected behaviour not as described in this [issue](https://github.com/facebook/flow/issues/627)?

**Comment by seveibar** [comment]
Values doesn't seem to be the issue here, if you change your example from...

```javascript
/* @flow */

const CHANGE_LOCATION = 'app/page/CHANGE_LOCATION'
const valueHolder = { CHANGE_LOCATION }
type TYPE_CHANGE_LOCATION = $Values<typeof valueHolder>

const x: TYPE_CHANGE_LOCATION = 'x'
```

to

```javascript
/* @flow */

const CHANGE_LOCATION:'app/page/CHANGE_LOCATION' = 'app/page/CHANGE_LOCATION'
const valueHolder = { CHANGE_LOCATION }
type TYPE_CHANGE_LOCATION = $Values<typeof valueHolder>

const x: TYPE_CHANGE_LOCATION = 'x'
```

You'll get the expected error,

```
7: const x: TYPE_CHANGE_LOCATION = 'x'                                   ^ string. Expected string literal `app/page/CHANGE_LOCATION`, got `x` instead
7: const x: TYPE_CHANGE_LOCATION = 'x'
            ^ string literal `app/page/CHANGE_LOCATION`
```

The real question here is: Should flow be making the string literal assignment the type of the string (if I've phrased that correctly)?
