### ISSUE TITLE
Objects as maps do not handle Generic Function Types as values

### ISSUE THREAD

**Issue by graphan** [facebook/flow#4419]
Here example: https://flow.org/try/#0C4TwDgpgBAggxsAlgewHYGEBOECGxmYDOUAvFAN4BQUUA2ocJoqgOYC6AXFADwAqAfAAowOTDgC2XXgEpS-ClFCQuDJqwA0UESAA2yHABMA-FKgBfSmYDclSnDQMoOBClS9wEYmSo1nSNACMXAAGfq4BwerUTi5oAEwhYfHBllY0NNEZ9qiOSTlc8P4Y2HgEXhTReUFQgrIk8oI+6UoQXHnukIQAdFXRZtJRvrGoCTUiYpJQqswsdQ1NNC1twx2ePcNxg+naeoZc4xJ90qlAA

**Comment by billschaller** [comment]
I don't think the ActionCreators type could actually be usable as you want - You could type the ActionCreators as an object with all the properties specified, but dynamically constructing the ActionCreators type at runtime using generics isn't possible currently.

This is about as close as you can get I think: https://flow.org/try/#0C4TwDgpgBAggxsAlgewHYGEBOECGxmYA8AKgHxQC8UAFGDpjgLYBcUxAlJeQN5SiSsAzsEyJUAcwA0UOiAA2yHABMA-K2IBfANwAoHf2jwkaLLnyZBlKNx1QoAbQDWEEEJFjxAXVZGUGbHgEhDioIKSSOtp6cGjCUDgIfsTgEJZUNnYJxqgAjKwABll+OfkRmYloAEwFRVX5kVp2drZNOjGocbUdPhX+ZgRp1i1deTScFOTUGU0GrF3JkIIAdCMtGuxl8b3VNHQMLFDCohLjk9N2s1vZC6kr25t2sgrKrHtMaxvDvQDMrLT0TFYACNkMg5LhUKcaOc+ClWDlpAB6RFQACaEDA0mAAAtMMgAO6WEJQCCYPGYJYtR44eSKJSvAGMD4NIA
