### ISSUE TITLE
Flow picks @providesModule from code comments (instead of file header)

### ISSUE THREAD

**Issue by frantic** [facebook/flow#442]
![screen shot 2015-05-08 at 11 00 01 am](https://cloud.githubusercontent.com/assets/192222/7542461/a8faff78-f571-11e4-9526-72d566b3b0ff.png)

**Comment by gabelevi** [comment]
:laughing: :laughing: :laughing: 

This is awesome. I think Flow [looks at the first comment](https://github.com/facebook/flow/blob/595d993bc6b7e4d55cea998d0477e185f12ab0c6/src/typing/module_js.ml#L58), but doesn't really check if the first comment is at the beginning of the file. Should be an easy fix :)

**Comment by avikchaudhuri** [comment]
Haha :)

**Comment by gabelevi** [comment]
Thanks for fixing this @bhosmer!
