### ISSUE TITLE
Flow misses type checks but React.PropTypes catches it

### ISSUE THREAD

**Issue by Xeoncross** [facebook/flow#4421]
In the following example I'm using Flow with React. I'm new to Flow and noticed that Flow doesn't catch the following string -> int conversion but React does. Am I doing something wrong? I assumed flow would track `props` and notice that `state.age` !== `props.age`.

```
// @flow

import React, { PropTypes } from 'react'

// In the following component we will see 'age' used as both a string and int

// These could instead be inline below (instead of pre-defined like this)
type FlowProps = {name: string, age: string}
type FlowState = {name: string, age: number}

class App extends React.Component {

  // For React (comment this out and everything 'works')
  static propTypes = {
    name: PropTypes.string,
    age: PropTypes.number
  }

  static defaultProps: FlowProps = {
    name: '',
    age: "foo"
  }

  // For Flow
  state: FlowState
  props: FlowState

  constructor(props: FlowState){
    super()
    this.state = {
      name: "bar",
      age: props.age // Flow misses this, but React.PropTypes catches it
    }
  }

  render () {
    return (
      <div>
        <Greet name={this.state.name} age={this.state.age}></Greet>
      </div>
    )
  }
}

const Greet = (props) => (<h1>{props.name} is {props.age}</h1>)

export default App;

```

**Comment by calebmer** [comment]
In your constructor, you’ve annotated `props` with the type `FlowState` 😊

```js
  constructor(props: FlowState) {
    super()
    this.state = {
      name: "bar",
      age: props.age // Flow misses this, but React.PropTypes catches it
    }
  }
```

Try changing it to `FlowProps` and let me know if you still have an issue 👍

**Comment by Xeoncross** [comment]
While that is a simple way to solve this problem. I used `FlowState` instead of `FlowProps` to show flow doesn't catch this type error. What is the point of a type system if it doesn't catch type errors?

**Comment by calebmer** [comment]
Flow checks that your `super()` call has the correct type, but not your constructor arguments. For instance you could have:

```js
class B { constructor(x: string) {} }
class A extends B { constructor(x: number) { super(x.toString()) } }
```

This would be an excellent place to add a lint error 😊

**Comment by Xeoncross** [comment]
I don't see a feature request for supporting [constructor arguments](https://github.com/facebook/flow/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20constructor%20arguments). Should I change the title?

**Comment by calebmer** [comment]
Maybe a good place to submit the feature request would be: https://yarn.fyi/eslint-plugin-flow 😊
