### ISSUE TITLE
Name is already bound when exporting an imported value in gen-flow-files file

### ISSUE THREAD

**Issue by pnevyk** [facebook/flow#4423]
If I import a module and try to export the value with the same name, generated file contains the import as well as declare statement so it results into `name is already bound` error. Here are example files:

```js
// foo.js
// @flow

type Dummy = mixed;
export default function foo(value: Dummy): Dummy {
    return value;
}
```

```js
// index.js
// @flow

import foo from './foo';
export { foo };
```

```js
// index.js.flow
// @flow

import foo from "./foo";
declare export function foo(value: mixed): mixed;
```

I think that the import statement in generated file is unnecessary since all named types are replaced with their actual definitions (see Dummy) and I cannot think about a use case where it has to be present (but I could be wrong).

**Comment by TrySound** [comment]
gen-flow-files is removed. A replacement is coming soon.
