### ISSUE TITLE
[feature] $ArrayMap

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#4424]
**Disclaimer** - I know that those methods are somewhat unstable now, but they still are useful

Im a little bit surprised that there is `$ObjMap`, `$ObjMapi` and `$TupleMap` but there is no `$ArrayMap`. Is there any particular reason for this? Would it make sense to have it implemented?

**Comment by TiddoLangerak** [comment]
I don't think you need an `$ArrayMap`, because elements in an array have the same type. This means you can express an `$ArrayMap` using normal generics. E.g.:

```javascript
type OptionalArray<I, A : Array<I>> = Array<?I>;

type OptionalNumberArray = OptionalArray<*, Array<Number>>;
const x : OptionalNumberArray = [1,null,3];
const z : OptionalNumberArray = [1, 'a', 3]; //error
```

**Comment by Andarist** [comment]
@TiddoLangerak thanks for the answer, u are right about restriction on the array having the same type, kinda forgot about this

But now im wondering how a function such as `Promise.all` can be expressed correctly (my 'idea' about $ArrayMap came from the attempts to type `Future.all` which for the sake of arguments we can treat the same as `Promise.all`). The problem is that I would like to type this in a manner that it accepts `Array<Promise<T>>` as input and outputs something close to `Promise<Array<T>>`, but preserving the original types.

I finally dug up the typings of Promises in flow and created this:
```js
type ExtractFutureType = <T>(Future<T>) => T
static all<R, A: Array<Future<R>>>(futures: A): $TupleMap<A, ExtractFutureType>
```

but still using `$TupleMap` here felt weird and also im completely unsure if I made this correctly

**Comment by billschaller** [comment]
I don't think this can work like you want it to - $TupleMap probably should just error when applied to an array, but [this snippet](https://flow.org/try/#0C4TwDgpgBAYgrsOAnCAeAKgPigXigbwDcBDAGzggC4p0BfAbgChHRIoBRAD2CWIGNg8RCnThoeDJgAUQ5GiwBKXNnRMAJhD6liKKADM4AOwEBLAPaGoZUqgBKAGigBBak6S8QqWSjuY-Ug2EIAGdXBWoAEnQ4MFIIAFliMFQnRy4efkEEOVFITCYoQqLGAHoSqDjgYKhgiGgTPSgTYCgAdzMkAGtgxg0tHWgSJCtqbzRgnhNDAHN83s1tXSGoACNR7J9DOABbFYgkOcqrd1woAG0AXSYdJAA6MDhggAspYgVr93vHl5X3xj4LBMoNskpA1G5hnhrK93H95v0ljpjkgxgBVQzmQyudzETxjVATJBTWZQAA+sA2aC2u32fiYAMMQJBYDBELRGIsp2hN3ZmPeUDKUGATyQZla1T2fGIj3qLSlhgA5HKzGQQnxoEZMUKxPDFoMkczWe5eRYAEyRaKxBJJVCsCBmRqGiDg42U9GYtLcXgCMa5CD5AXlYIdFoOqBmTqMKROl0ot0cwyms4ABgu1BWZjMcWIhiUgoAcmZII5WhAFYRoKQzEC7T0ivWoLqBlBljzKQB5PTuizYjxeSkEyYzMlQal7A5zBlM0HOtkdrsJrmkUgwuNBTvd3P0QNQADKdW21WAZjaHUj0ZnsbGG4TKbTNSH0xHY-2-MFAE1cY5DCf9qKkFGMZzuuC6YmcACM94ZlmEA5m+5TCqK4pWJYf4dFY1QQJwkACM6QA) shows that there are some issues with what you want.

The best you can do with $TupleMap is actually the same as what you could do without it.

A. You can't turn `Array<Future<X> | Future<Y>>` into `Array<X | Y>`
B. You *can* turn `Array<Future<X | Y>>` into `Array<X | Y>`

I've tried declaring a function that can do A using some very complicated type wrangling, but even though you can cajole Flow into giving you something that looks like what you want, it isn't type safe and loses type information.

**Comment by Andarist** [comment]
@billschaller how is my example different than this - https://github.com/facebook/flow/blob/0d5e954fcc631b3e0705b02d5305e0be65cec18e/lib/core.js#L677 ? I mean, this is how Promises are typed by flow team. I would like to understand the difference and how to use typings in such cases properly.

**Comment by billschaller** [comment]
Actually, it does seem to work: [snip](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwGIFcAum4B4BqAFQD54BvAXwG4AoAegfmwE8AHBLXAk8gXkoA3KBEwgAXPGK14TeADkA9pwA08JQDsIreAHclMANZo9AS2wALRNFQsOIZHTptO0h8Qf4y8QRRFiktJULg7wAKIAHtgwUGDY3Hggnm6C3qQAFIkEZACUvuTE9KBIcPAAZpia8WZa8KIQ+ABK6gCCUq0wsaz42SDNpIMZlTyOHblSACTEmOwQIACyUOz4repRMXEJOEkpIKT08vPYaMggCGbl8Bb6hiZ0JdBlIjD1Un34yDFmmgDmBw9wE8EC94AAjd47AiaTAAWzBIBgAMesBBsEQkNG3g8XjBSiU8ygmkG9GO9S6vngAG0ALr0WAwAB07EwyEsGSguXpXWZrPZYK5dAZvLZGTAgrAWi+8Fhy04wE6r0EDQ5XUFGVl7HliqpAAYaVIvjAfr94AAfeAw+GI83uTh7fB4gkgImkdWa7VdDpdKA9I0m21WhGvC17B1OwnEt30IA)

So if we did have a $ArrayMap, it would just be an alias for $TupleMap.

**Comment by Andarist** [comment]
Interesting, so even though the naming comes from `tuple` it works on any 'arrays', not only on those with fixed size.

However - I guess what I REALLY would want to is for this part to type check ([snip](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwGIFcAum4B4BqAFQD54BvAXwG4AoAegfmwE8AHBLXAk8gXkoA3KBEwgAXPGK14TeADkA9pwA08JQDsIreAHclMANZo9AS2wALRNFQsOIZHTptO0h8Qf4y8QRRFiktJULg7wAKIAHtgwUGDY3Hggnm6C3qQAFIkEZACUvuTE9KBIcPAAZpia8WZa8KIQ+ABK6gCCUq0wsaz42SDNpIMZlTyOHblSACTEmOwQIACyUOz4repRMXEJOEkpIKT08vPYaMggCGbl8Bb6hiZ0JdBlIjD1Un34yDFmmgDmBw9wE8EC94AAjd47AiaTAAWzBIBgAMesBBsEQkNG3g8XjBSiU8ygmkG9GO9S6vngAG0ALr0WAwAB07EwyEsGSguXpXWZrPZYK5dAZvLZGTAgrAWi+8Fhy04wE6r0EDQ5XUF8A1mo1dAysvY8sVVIADDSpF8YD9foLdXKQAqulSAIym+Aw+GI616g0OgBMLr2e3weIJICJpEFdCAA)):
```js
(mappedArr[0]: string);
(mappedArr[1]: number);
(mappedArr[2]: TypeType<boolean>);
```

Just like [`$ObjMap`](https://flow.org/en/docs/types/utilities/#toc-objmap) does for, well, objects and it correctly type checks on different properties. So in my desired situation the same would happen, just for indices.

Therefore `$ArrayMap` may not be the best name for this (as @TiddoLangerak has noticed). `$TupleMap` is better suited for this as tuples are designed to have various types on different indices, however what I want would have to work on dynamic lengths and not on the fixed length (like tuples do) + ofc keep pairing indices with types.

**Comment by billschaller** [comment]
@Andarist you can only do that with tuple types. By design, array types don't assign specific types to specific indices, because there's no way to guarantee safety in that case.

**Comment by Andarist** [comment]
Yeah, thats why I said `$TupleMap` seems more appropriate for this.

Thought that it still doesn't work correctly with `$TupleMap`, but constructing the tuple and passing it to the function in place like this:
```
const mappedArr = all([a,b,c]);
```
seems to be good. I could document `$TupleMap` a little bit with exactly this use case (`Promise.all`) - aint sure how stable it is and what are the plans for those methods. Would love to get some kind of green light beforehand.

**Comment by Andarist** [comment]
`$TupleMap` is intended to work on `Array` types. Closing this.
