### ISSUE TITLE
Document property variance notation

### ISSUE THREAD

**Issue by aruediger** [facebook/flow#4426]
The `+`/`-` prefix notation is mentioned in the [redux docs](https://github.com/facebook/flow/blob/master/website/en/docs/frameworks/redux.md) and [this blog post](https://github.com/facebook/flow/blob/master/website/_posts/2016-10-04-Property-Variance.md) but nowhere in the docs on variance. (At least I wasn't able to find them.)

**Comment by asolove** [comment]
Oh wow, thanks for pointing this out. There is actually mention of it in the [interface variance](https://flow.org/en/docs/types/interfaces/#toc-interface-property-variance-read-only-and-write-only) section, but it's not clear that you should have to read that section to understand how variance annotations work elsewhere.

I know there is a lot of interest in improving the education around variance issues. I'm working on a blog post and will also look for ways to add this to the docs somewhere more obvious.

**Comment by jgebhardt** [comment]
Ironically, https://flow.org/en/docs/lang/depth-subtyping/ mentions the covariance syntax, while https://flow.org/en/docs/lang/variance/ does not.

**Comment by gkz** [comment]
Fixed in 43199f1287474307d7e02745daad794be8057da9 and aec9b7999f1246404277722678d1baf2e32b5deb
