### ISSUE TITLE
Make something like definitelytyped for Flow

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#443]
To be really useful, Flow needs something like DefinitelyTyped (which is only for TypeScript).

TypeScript and Flow annotations are *similar*, but not fully compatible. I think it would be more practical if Flow devs started something like that, rather than just try to converge the two systems (which can make years, while Flow definition database can be done quickly).

**Comment by impinball** [comment]
There's also #72, which is about approaching the problem from the other side, making existing TypeScript definitions work with Flow (nothing about the syntax, though).

**Comment by avikchaudhuri** [comment]
A tool to convert .d.ts to Flow declarations has been on our future plan list for some time now (see http://flowtype.org/docs/coming-soon.html#_), and can be used to populate an initial repository if that's what the community wants to do. Expect an update on the tool within the next couple of months.

**Comment by samwgoldman** [comment]
Merging with #7

**Comment by turadg** [comment]
TypeScript : Flow :: https://github.com/DefinitelyTyped/DefinitelyTyped : https://github.com/flowtype/flow-typed

**Comment by runn1ng** [comment]
Oh, what I meant by this issue is something like https://github.com/flowtype/flow-typed being created

Since that exists now, I am happy :D

**Comment by danpantry** [comment]
Honestly, I think trying to make a "flow" copy of this was a mistake. The types in DefinitelyTyped/`@types/****` repos on npm should be made to work with both languages to prevent further fragmentation.

**Comment by runn1ng** [comment]
TypeScript and Flowtype are in the end very different systems and the similarity is only on the surface. I am not sure if this would be even possible.
