### ISSUE TITLE
$ElementType<T, K> indexable signature not found for Class

### ISSUE THREAD

**Issue by reaperdtme** [facebook/flow#4431]
$ElementType unable to run on classes.

``
declare class Lo {
	mapp<T, K : $Keys<T>>(array: T[], prop: K): $ElementType<T, K>[];
}
class Device {
    push_token: string
}
let devices: Device[] = []
let tokens = _.compact(_.mapp(devices, 'push_token'))
``
Errors with:
```
element type
Indexable signature not found in Device
```

Currently seeing this error on all my Class usage with $ElementType. Records are working fine.

**Comment by jeffijoe** [comment]
Same issue, I am trying to create a simple `ReadOnly` type:

```
type ReadOnly<T> = {
  +[key: string]: $ElementType<T, key>
}
```

Additionally, I get `identifier `key` (Could not resolve name)` for the usage of `key` .

**Comment by jcready** [comment]
@jeffijoe that's not an issue with `$ElementType`, the only identifiers you can use must be declared in between the first set of angle brackets, like you've done with `T`. Something like:

```js
type ReadOnly<T, K> = {
  +[K]: $ElementType<T, K>
}
```

Obviously that doesn't do what you want, but that's an unrelated issue.

**Comment by jcready** [comment]
@kidcosmic oddly enough, you can work around your issue by changing your `Device` class to `extend Object`:

[Try flow](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwFsoAHY+AHgBUAaeAaQC54ASOkATwGcqA+H+ABSwYUdk0oBtALq1iMHMSZ0AlE2YBRCCAIhUGSu2IgqtOj2kBuAFBXIUTp3gAREADcsYBCAAeGXcEcAeQAjACtwDHgAbyt4eGJkTgALAH0MHABrXSZODBgsVABzKwBfGy1I0HdPTiYXapBpeABeeGlbPFz4KBbCEmIBKo8QTloAcgTktMzdMeVrIRy8gsLpeaA)

```js
declare function mapp <T, K: $Keys<T>> (array: T[], prop: K): $ElementType<T, K>[];

class Device extends Object {
  push_token: string
}

let devices: Device[] = []
const a = mapp(devices, 'push_token');
(a: string[]);
```

**Comment by kidcosmic** [comment]
@jcready oh lol there goes 40+ flow errors.
much appreciated sir.

**Comment by jeffijoe** [comment]
@jcready Having the class extend from Object just to get index signature based types working seems a bit weird, is this classified as a bug?

**Comment by jcready** [comment]
@jeffijoe I would certainly classify it that way. Especially considering **all** classes in javascript extend `Object` already.

**Comment by loyd** [comment]
Some progress on this?

**Comment by goodmind** [comment]
Workaround

```js
class D {
  x: number
}

type S = $ElementType<$ReadOnly<D>, 'x'>
  
const m: S = ''
```

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
