### ISSUE TITLE
new RegExp(expression, flag) does not accept empty string as flag

### ISSUE THREAD

**Issue by lwchkg** [facebook/flow#4435]
Offending code: `new RegExp(".*", "");`

Expected behavior: accept the syntax (regular expression with no flags).
Actual behavior: rejected

This affects the following syntax, which creates either a case sensitive or case insensitive RegExp depending on the value of `caseInsensitive`:
```
const regex = new RegExp(expression, caseInsensitive ? "i" : "")
```

**Comment by billschaller** [comment]
RegExp constructor should accept empty string. See spec: https://tc39.github.io/ecma262/#sec-regexpinitialize

**Comment by iboss-ptk** [comment]
Seems like this issue has already been resolved on master. The regexp flag is currently defined using `$CharSet` which includes empty string already.

```js
type RegExp$flags = $CharSet<"gimsuy">
```

```js
declare class RegExp {
    ...
    constructor(pattern: string | RegExp, flags?: RegExp$flags): RegExp;
    ...
}
```
