### ISSUE TITLE
property `@@iterator` of $Iterable. Property not found in rest of object pattern

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#4436]
I have the following function that collects arguments into array of dictionaries:

```
const renderMergedProps = (component: ReactClass<*>, ...rest: Array<Object>): React.Element<*> => {
  const finalProps = Object.assign({}, componentProps, ...rest);
  return (
    <component { ...finalProps } />
  );
};
```

Calling this code causes some obscure error:

```
33:         return renderMergedProps(component, routeProps, ...rest);
                                                               ^ property `@@iterator` of $Iterable. Property not found in
33:         return renderMergedProps(component, routeProps, ...rest);
                                                               ^ rest of object pattern
```

Reproduced here:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50yAPPIsIQCeOMqTgBXQmQAK9HAGcwAXjABvAL5dUVGBQVKSk6WF7SAdgBNDbQgDoAwgzzmy54mtRgwrK2XwAFACU6l7e3qyEEvjmYAA8lhgAbmDAAHxc3hqo2Tp6BmAAygxkRlJkDvlKZm7WpLaOznCu7qERtf7BbeE+ZFEx8Ykp6Zlg2blQEuY0GM1gWBQA1qXGZAoBVE0thHJwigBc4uW7ikGH5NT2AKIwZFhuhHEgad3AwGAAsv4A5mI48koKFZen58GBNrhmg8wptzApiL5LP4vvhfpYTkpVBstg9zrZKvoFE80gAaMB2CmseGHACC+HwFCEcQA8gAjABWZBoaTO9UudhudwexJUL08PVh8LAUAw5goMAxKjAbM5NDshIw33MAU0ZIhLgeGLJFLsVMIQVG7X6sQCYR6cX1UNaanJFJlcoVALGqTSdrAFrCWnQ3je9VBShwElZMAwVB8qzCod4FFwt0OcRkUZjVDKJhwFEIAAtlAAiYAl8E49zKF0fIROSHbb3pGHNKWZ6Ox3NiLEux3bY2UtbEDSHPtVwh4y4EgwijQhZRiv2RaI2v3eOLd9Qms0aEFI-A1sABejHAELpc9HorgaI5E-MjogHYxsPMmn6RG12m4cBq9jPcWx6P8xm0K1V2PP0MyzLtVlMHhLkrV9qxdYp7m7GclEA31vADDQgA

**Comment by billschaller** [comment]
[Looks like a bug in your implementation](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50yAPPIsIQCeOMqTgBXQmQAK9HAGcwAXjABvAL5dUVGBQVKSk6WF7SAdgBNDbQgDoAwgzzmy54mtRgwrK2XwAFACU6l7e3qyEEvjmYAA8lhgAbmDAAHxc3hqo2Tp6BmAAygxkRlJkDvlKZm7WpLaOznCu7qERtf7BbeE+ZFEx8Ykp6Zlg2blQEuY0GM1gWBQA1qXGZAoBVE0thHJwigBc4uW7iiGe3sDAYACy-gDmYjjyShRWvX74YJu4zW6EYZtzApiL5LP5bvgHpYTkpVBstn9DuRqIRKvoFHEQGkADRgOz41jAw4AQXw+AoQjiAHkAEYAKzINDSIWUaW63kBwLAUAw5goMBhKjAtIZNDs6Iwd3MAU0uO+Lj+MNx+LshMIQVG7X6sQCYR6cXlv1aajx+J5fIFzzGqTSerAGrCWnQFyu5A+ShwEhpMAwVB8qzCl1MPAouBgZEOcRkXp9VDKJhwFEIAAtlAAiYBpr4I9zKE3XIROH7ba3pAHNLnR72++NiOEmw3bZUEtbEDSHBs5whI2xogyYtkaFls87hSLRHV27xxWvqFVqjTvMH4PNgAL0Y7PYehIM9Md9CdL8H3MjQ57w4t-XEb6RK02q1sa1JXOIAWnfYAQybgewUAEIp33bUj3wCEoRhC8FXca9VjvNUHT3MZFzLHoELGbQtUPXV9SrWNZ14FFs0vXMTWKLAVnKPslGQ21vAdDQgA)

**Comment by pronebird** [comment]
Oh snap! Thanks @billschaller!
