### ISSUE TITLE
Allow $Keys<T> to work on Arrays or provide new $Indices<T> utility type

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4438]
I'm not sure how else I could write this function:

```js
function get <T: *, K: $Keys<T>, N: $ElementType<T, K>> (thing: T, key: K) : ?N {
  if (thing && typeof thing === 'object') {
    return thing[key]
  }
}

const a : [number, string, boolean] = [1, 'string', false]
get(a, 0)
```

[Try flow](https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZUQHgCoC5EBUANIgNL4AkpqAngM44B8JAcpQKIA2qAtqmFGw0ADqhwlSjRogAUUABYwwyfNhIBrWvlIBKRPgD8LRAG8AUIkQxgshUuSIAZI8RQRqODbvLEAXn+IAORwAEYAVqjQgXrmlpYATugg8UjeyADamjQAuhaIAL5mhWYQCHQYAIb6iOlgIDwhqPEk5fH2JCFwcNwVYNl+NQCMJIGt9oEkwBWcdKi5aFAyFSQADDpAA) (You have to set the version to "master" or "v0.49.1" because "v0.50.0" doesn't recognize `$ElementType` for some reason)

**Comment by lll000111** [comment]
I hate it when somebody replies to my own questions/tickets not with a solution but with "why?" or suggestions to do something else instead. But here I go: Why? What are you trying to accomplish? These seems way too generic, like trying to find the one type definition that could be used for the universe and always be correct. Are you trying to access an array? Then the index is `number`. There are no checks of the returned type in your code, so the return type actually is something unconcrete like "`mixed`" or "`*`". Why even bother trying to have that return type (here: "`?N`" then?

**Comment by jcready** [comment]
This was a minimal example so that it would be easier to understand. Is there a reason why Objects get `$Keys<T>` but Arrays can't have a similar utility type or even just have `$Keys<T>` also work on Arrays? `Object.keys()` works on Arrays (albeit while casting the indices to strings). There are only two main native data structures provided by JS: Objects and Arrays. It just seems odd that flow would provide these nice utility types for one, but not the other.

**Comment by lll000111** [comment]
>  Is there a reason why Objects get $Keys<T> but Arrays can't have a similar utility type

Well, it's not needed, the index into an array is `number`?

> Object.keys() works on Arrays 

I consider that a bad thing. Something being possible does not mean it should be used.

**Comment by jcready** [comment]
> This is not possible or useful to do with arrays - do you know the exact numbers that go into an array during compile time?

I was under the impression that's what tuples were for, like in my example.

**Comment by lll000111** [comment]
I'll remove my comments because I said what I wanted to say, you read it, and it you still want to do whatever it is that you want to do it's none of my business but between you and the package owners.

**Comment by lll000111** [comment]
I'll remove my comments because I said what I wanted to say, you read it, and it you still want to do whatever it is that you want to do it's none of my business but between you and the package owners.

> I was under the impression that's what tuples were for, like in my example.

To access different types in a tuple you simply write

```javascript
const a : [number, string, boolean] = [1, 'string', false]
a[0] = 2;
a[1] = 'foo';
a[2] = true;
```

**Comment by pronebird** [comment]
If you use literal array or tuple then you know number of elements ahead of time. Just access tuple directly and Flow will automatically warn you when you go out of bounds.

**Comment by billschaller** [comment]
You can actually do this by leaving the annotations off:

```js
/* @flow */

function get(foo, index): number {
  return foo[index];
}

const t: [number, number] = [1, 2];
const a = get(t, 1); // OK
const b = get(t, 2); // error
```
