### ISSUE TITLE
$Values<T> type is not documented

### ISSUE THREAD

**Issue by denisw** [facebook/flow#4442]
The new $Values<T> type introduced in Flow 0.51.0 is not mentioned anywhere in the docs. I would have expected a section on it on the "Utility Types" page.

**Comment by Andarist** [comment]
Would start from mergin this - https://github.com/facebook/flow/pull/4386 . Publishing even such 'useless' info may be an incentive for an outside contributor to pitch in.

**Comment by mrkev** [comment]
Seems to be documented now: https://flow.org/en/docs/types/utilities/#toc-values
