### ISSUE TITLE
get-def consumes all the CPU on Windows

### ISSUE THREAD

**Issue by lgraziani2712** [facebook/flow#4445]
### Feature or bug?

- Bug.

### Description

Every time I try to jump to a definition, multiple node processes spawn and freeze my PC:

![PC 100% CPU](https://user-images.githubusercontent.com/15050200/28091278-9bb9caf8-6665-11e7-9bcc-8173964149d4.png)

I also reported this here https://github.com/steelbrain/flow-ide/issues/103.

Is something I can do to give you more information? Like a debug report?

### Tech details

- OS: Windows 10.
- IDE: Atom 1.19.0-beta4.
- Atom plugin: flow-ide: https://github.com/steelbrain/flow-ide/

Thank you for your work!

**Comment by billschaller** [comment]
The flow binary will show up in windows as flow.exe. This is not a flow issue, it seems as though it is an issue with the plugin you're using.

**Comment by leos** [comment]
@billschaller - What's the proper way to discover the location of `flow.exe`? It sits in a version specific directory and there's no shortcut created by the npm installer.

Invoking `./bin/flow.cmd` doesn't execute `flow.exe`, it calls `node.exe` with arguments leading to a much slower execution and the problem @lgraziani2712 is facing.
