### ISSUE TITLE
Arrow function in callback doesn't care about argument numbers

### ISSUE THREAD

**Issue by abs-zero** [facebook/flow#4447]
I am trying to write a lib definition. Here's a [flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOC0uOAChYA8AuMAZ2sNoUA5gBowAT258BwgJRgAvAD5e-QUNlS1w1GFRRmbLqpkbFK9vODAwAYXwwYAI3w4A1mAS1qACzAMYcX8KEiIhMgBbLApqMCcyWJ4fODIYDDAQrHTqBDh0IA) for contrived example:
```
/* @flow */

declare function foo((x: string, y: string) => string): string // y is not optional
 
foo((x: string) => x) // Callback with only one argument type checks but should need two
```
is this intended or a bug?

**Comment by abs-zero** [comment]
Another [flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOC0uOAChYE8AuMAZ2sNoUA5gBowAD24B5AEYArXNQCUYALwA+MLIU0l0+YtTV2ABxIAtNWADeqMGBOE4J7nwHDUAX1RRmbAF5ikmDmKho2xNRkhIzWnp4qwMBgxmZgOAAWuADWPGAIWYziYLR5OHAAtiZkMDxwhOzo2HhEJORUdAxMcABMbFy8-IKiEgD8+jrKaprainpaBjRGpiQAGla29o7OrkMe3r69AUHcq2Ga1pHRsfGJyQAicFh5FHDUKSvpWTjZ+YUSJTyzk6FHwMFQQA):
```js
declare function foo((y: string, x: Object) => Object): Object
type Z = {
  prop: string
}
foo((z, x: Z) => {return {}}) // type checks when x is compulsory

declare function foo2((y: string, x?: Object) => Object): Object
type X = {
  prop: string
}
foo2((z, x: X) => {return {}}) // Does not type check when x is optional
```
Is this related?

**Comment by AugustinLF** [comment]
That seems correct to me, if you look at the blog post about [strict function call arity](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/). You expect `foo` to be called with one argument, which is correct. You say that this argument is a function that takes two params, you pass one which takes only one, that is correct, since a function with an arity of one is a subtype of one that has an arity of two.

What you would like would for instance makes it cumbersome to write `[].map`, where you would have to write `const double = arr => arr.map((val, index, total) => val * 2)` to make it correct.

Your second example seems to me to be another problem, probably still a subtyping issue, but I don't think I can explain it :/

**Comment by abs-zero** [comment]
@AugustinLF 
Now I understand, thanks! So, does this mean having an optional parameter is unnecessary in a callback?

And for the second example, should I make a separate issue? Or it's not an issue at all?

**Comment by AugustinLF** [comment]
Hmmm, it's necessary if indeed the foo callback doesn't receive all its arguments all the time. If for instance, in some cases `array.map` would receive the index, we would need to annote its signature as `map((val: T, index?: number) => ...)`. What you don't need to annotate is the fact that your use doesn't have to use all the params.

Shortly, you specifiy what are the params that foo passes to its callback, not what you want the user to use (he/she is free to ignore them :) ).

And I actually understood your second example, there's no issue. You say that `foo2` can call its callback with a maybe `Object`, which means that on the user-land, it's not safe to assume that x is defined. Here, flow does what you expect it too, warn the user that x might be null.

Overall, I think your problem with these two cases is that you mix up the fact that here you're providing typings for people consuming the foo api, and not the people writing the API!

**Comment by abs-zero** [comment]
Now it's clear. Thanks for the detailed explanation!

**Comment by billschaller** [comment]
Seems this exposes a parsing error.

```js
/* @flow */

declare function bar((x: string, y: string) => string): string; // Should be a parse error at second paren, but isn't
```

**Comment by billschaller** [comment]
closing in favor of #4452
