### ISSUE TITLE
Checking of React props works only in same module

### ISSUE THREAD

**Issue by martinschayna** [facebook/flow#4448]
Sorry, can't be reproduced on https://flow.org/try/ because it happens between two modules.

Inherited props aren't checked by Flow when component extends from imported component. When both component classes are in the same module, inherited props are properly checked.  

module1.js:
```javascript
import React from "react";

type Props = { prop: string };

export class Comp extends React.Component<void, Props, void> {};

class BaseComp extends Comp {
  render() {
    return <div>{this.props.otherProp}</div>;  // <--- Flow found this error, OK
  }
}
```
module2.js:
```javascript
import { Comp } from "./module1.js";

class OtherComp extends Comp {
  render() {
    return <div>{this.props.otherProps}</div>;  // <--- Flow didn't find this :(
  }
}
```
flow-bin@0.50.0
react@15.6.1

**Comment by billschaller** [comment]
Does it work if you define your base class as follows?
```js
export class Comp extends React.Component {
  props: Props;
};
```

**Comment by martinschayna** [comment]
Unfortunately it doesn't work either. Same symptoms as with generic types, works in the same module, but don't in other module.

**Comment by martinschayna** [comment]
Sorry, finally I figured it out. It was completely my fault :disappointed:, missing `// @flow` annotation in one of my files.

Flow is working as expected, i.e. great.

Closing.
