### ISSUE TITLE
Combining array destructing and union type does not work

### ISSUE THREAD

**Issue by kjirou** [facebook/flow#4449]
These are working:

```js
const [value1]: ['A'] = ['A'];
const [value2_1]: ['A' | 'B'] = ['A'];
const [value2_2]: ['A' | 'B'] = ['B'];
const value3_1: ['A'] | ['B'] = ['A'];
const value3_2: ['A'] | ['B'] = ['B'];
```

But, this is an error.

```js
const [value4]: ['A'] | ['B'] = ['A'];
```

Try Flow:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqA2gG4CG0ArgKYCMAugFz4DkAgg9aALyMvUDcqGOfMTLkATAH0a9PMwagAPqAYAhVhy6s+aLLkIkKE0XQ0KlqtpxnmtA3MIoBmSdNltFVtZdc2doe+SdRF25TDwtGa2RtQT0RABZjGRD3FU8NXiA

In addition, I used `flow-bin@0.51.0`.

Thanks.

**Comment by SamChou19815** [comment]
now all of them work
