### ISSUE TITLE
Parser doesn't catch invalid function declaration.

### ISSUE THREAD

**Issue by billschaller** [facebook/flow#4452]
See [snippet](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCWAzmACZwCmxALrgE6JgCGYADo7YeWObfbQFyooAVwB2AYyr44osFDhwAFIoAe-MISq18ogOYAaMAE91m7XoCUYALwA+DVp26Lpx3rABvVGDC1yVYVpZAHJggG5UAF90TBwCYkJcOGEYEjAAIy5mNg4uHj4mKg1ycRk0nPJRQ3ThIqJRYKpBEhKYdi4RCSkZDPZlNQdzA2NXIas7QacXSb0IoA)

```js
// This does throw a parse error:
function foo((x: string, y: string) => string): string {
  return '';
}

// This should be a parse error at second paren, but isn't:
declare function bar((x: string, y: string) => string): string;

```

**Comment by billschaller** [comment]
@mroch I wonder if we could generate a completeness test suite for declarations?

**Comment by vkurchatkin** [comment]
@billschaller this looks fine to me since declaration doesn't require argument names
