### ISSUE TITLE
Call of method reduce. Function cannot be called on any member of intersection type intersection

### ISSUE THREAD

**Issue by klimashkin** [facebook/flow#4456]
Trying to type simple function that converts array of objects into object of objects by key prop
```javascript
function arrToObject(arr) {
  return arr.reduce((result, item) => {
    result[item.key] = item;

    return result;
  }, {});
}

arrToObject([{key: 'one'}, {key: 'two'}]); // -> {one: {key: 'one'}, two: {key: 'two'}}
```

Typed version:
```javascript
function arrToObject<T: {key: string}, R: {[string]: T}>(list: Array<T>): R {
  return list.reduce((result: R, item: T): R => {
    result[item.key] = item;

    return result;
  }, {});
}
```
And I get error:
`Flow: call of method `reduce`. Function cannot be called on any member of intersection type intersection`

On flow.org/try:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgMJwHYBuApgE5gCGJJ5AnmHFPQEYBWRAxgC4DOYAlnk5xmbLvUZxWHHqigBXPFz74KVACpwA8lK4AeNQC4wAbwDWRGke6cSAgOYBfADRgASkeMBta7bx2AukZqDgB8ABQwfNZGAIJUtPohAJRGriaoYGAkRJxyJHhgkdYAdNkAJnLsRGFh2dxyMJypLnycRAC2QSluYAC8IemZmXUNnJ6tHcXmNP59-G3tANzoQ1k5eQUjjcuZziYOScsOQA

**Comment by dsacramone** [comment]
Were you able to solve this?

**Comment by adius** [comment]
I get a similar error

**Comment by jcready** [comment]
Strangely, if you drop the `R` type alias everything appears to work:

```js
function arrToObject <T: { key: string }> (list: Array<T>): { [string]: T } {
  return list.reduce((result, item: T) => {
    result[item.key] = item;
    return result;
  }, {});
}
```

**Comment by asolove** [comment]
Have you tried $ReadOnlyArray? I could see variance causing the original issue because of that array argument.

**Comment by bsaphier** [comment]
+1
my code:
`  const res = arrayInScope.reduce((a: string, b: string): number => (objectInScope[a].value + objectInScope[b].objectInScope) / arrayInScope.length);
`
throws this linter error:
`[flow] call of method `reduce` (Function cannot be called on any member of intersection type intersection Member 1: function type Error: function This type is incompatible with the expected param type of function type Member 2: polymorphic type: function type Error: function This type is incompatible with the expected param type of function type)
`

my .flowconfig:
`[ignore]
; We fork some components by platform
.*/*[.]android.js

; Ignore "BUCK" generated dirs
<PROJECT_ROOT>/\.buckd/

; Ignore unexpected extra "@providesModule"
.*/node_modules/.*/node_modules/fbjs/.*

; Ignore duplicate module providers
; For RN Apps installed via npm, "Libraries" folder is inside
; "node_modules/react-native" but in the source repo it is in the root
.*/Libraries/react-native/React.js

; Ignore polyfills
.*/Libraries/polyfills/.*

[include]

[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
node_modules/react-native/flow/

[options]
emoji=true

module.system=haste

munge_underscores=true

module.name_mapper='^[./a-zA-Z0-9$_-]+\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'

suppress_type=$FlowIssue
suppress_type=$FlowFixMe
suppress_type=$FlowFixMeProps
suppress_type=$FlowFixMeState
suppress_type=$FixMe

suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe\\($\\|[^(]\\|(\\(>=0\\.\\(5[0-6]\\|[1-4][0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue\\((\\(>=0\\.\\(5[0-6]\\|[1-4][0-9]\\|[0-9]\\).[0-9]\\)? *\\(site=[a-z,_]*react_native[a-z,_]*\\)?)\\)?:? #[0-9]+
suppress_comment=\\(.\\|\n\\)*\\$FlowFixedInNextDeploy
suppress_comment=\\(.\\|\n\\)*\\$FlowExpectedError

unsafe.enable_getters_and_setters=true

[version]
^0.56.0
`

**Comment by SamChou19815** [comment]
Now the error message is better
