### ISSUE TITLE
Function call seems to make Flow forget non-null check in `if` branch

### ISSUE THREAD

**Issue by benjie** [facebook/flow#4458]
Inside an `if (data.c) {...}` branch Flow can forget that `data.c` is not null if a function is called.

Reproduction:

https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBnKAnAXIrbGMAcwEp9DiTEBvAKEUWwFMoRslDEBqRAIgDuACwCGUFgDcW2fgG56AX3r0oATwAOLRAEEAQgGFEAXjqNEEfAH4A2lVIAaRACNUAGxaiwAXSUqPUIgAJuKi+PpGpgxMlog2AOQocPFOOCAsvooK9AHBoQBM1hHZMMCIaCFQogB0EGRmTJWi+SYNTBb4NubtyKgVobU2AAzeZA7d7U2DAIy+PXOIWUpAA

Passes if you alias `const c = data.c`:

https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBnKAnAXIrbGMAcwEp9DiTEBvAKEUWwFMoRslDEBqRAIgDuACwCGUFgDcW2fgG56AX3r0oATwAOLRAEEAQgGFEAXjqNEEfAH4A2lVIAaRACNUAGxaiwAXSUqPUIgAJuKi+PpGpgxMlog2AOQocPFOOCAsvooK9AHBoQBM1hHZMMCIaCFQogB0EGRmMQhYFiZ5VbXmlaL5rdFMFvg25v3IqGgQNgAM3mQOw-0TAIy+IyuIWUpAA

Also passes if you skip the function call (non-equivalent functionality):

https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBnKAnAXIrbGMAcwEp9DiTEBvAKEUWwFMoRslDEBqRAIgDuACwCGUFgDcW2fgG56AX3r0oATwAOLRAEEAQgGFEAXjqNEEfAH4A2lVIAaRACNUAGxaiwAXSUqPUIgAJuKi+PpGpgxMlog2AOQocPFOOCAsvooK9AHBoQBM1hHZMMCIaCFQogB0EGRmTJWi+SYNTBb4NubteVW1NgAM3g7d7U39AIy+PdOIWUpAA

```js
function foo(str: string): string {
  return str + "whatever";
}

type ABC = {
  c: ?[string, boolean]
}

let data: ABC = {
  c: ['foo', true]
};

let data2: ?ABC;

if (data.c) {
  data2 = {
    c: [
      foo(data.c[0]),
      data.c[1]
    ]
  };
}
```

```
 data.c[1]          ^ access of computed property/element. Computed property/element cannot be accessed on possibly null value
19:       data.c[1]
          ^ null
19:       data.c[1]          ^ access of computed property/element. Computed property/element cannot be accessed on possibly undefined value
19:       data.c[1]
          ^ undefined
```

**Comment by AugustinLF** [comment]
Yep, that's a common issue, Flow is pessimistic about [refinements (see the Refinement Invalidations section)](https://flow.org/en/docs/lang/refinements/), it considers that your `foo` call might (for instance) set `data.c` to null.

**Comment by benjie** [comment]
Thanks @AugustinLF - I see now that Flow cannot detect that I am not pulling the rug out from under it in `foo()` so plays it safe.

**Comment by jcready** [comment]
@AugustinLF but in this case flow knows the entire function body of `foo()` and can plainly see that there is nothing which would invalidate the prior null check. I would expect flow to only be pessimistic about function calls of which it cannot see the body.

**Comment by AugustinLF** [comment]
@jcready You're technically right, however, this is something that flow doesn't handle at all for the moment, flow does consider that any function call (even a simple `console.log()` might invalidate a check, and therefore invalidate the refinements.

If I'm right, there are some requests to be able to annotate a function as pure, but it's not being worked on!

**Comment by jcready** [comment]
@AugustinLF that's too bad. Is there any place to see a roadmap of what the flow team is currently working on? Like, which features or bugs are actively being worked on?

In either case, I would definitely think that being more clever with refinement invalidations should be close to the top of that list as it needlessly forces users to duplicate refinements if there is any function call (even ones where flow can see the full function body and know that refinements weren't invalidated). I can totally understand flow not trusting third-party functions which either weren't flow checked or were annotated using libdefs and in those cases I agree that some kind of `%pure` function annotation would be desirable. But for functions inside files that are explicitly flow checked with `// @flow` at the top should be able to be implicitly deemed "pure" by flow and not invalidate refinements when invoked.
