### ISSUE TITLE
Unexpected token

### ISSUE THREAD

**Issue by ivanherczeg** [facebook/flow#4460]
Freshly installed Flow 0.51.0 constantly dies from default by parsing json files in my working directory.

**testfile.json:**
```
{<% var ngVer = "1.6.5" %>
...
}
```

**$ flow**
> Error: testfile.json:1
>   1: {<% var ngVer = "1.4.0" %>
>       ^ Unexpected token <
> 
> 
> Found 1 error

Why is Flow parsing json files by default? Is that a normal behaviour?

**Comment by btford** [comment]
Yes. You should add this file to your `.flowconfig`'s ignore section.

**Comment by ivanherczeg** [comment]
All righty. Thanks.
