### ISSUE TITLE
Issue with some incompatible instantiation of `P`

### ISSUE THREAD

**Issue by nickydonna** [facebook/flow#4461]
I don't know if this is a bug (I don't think so) but I'm really stucked with this:

Link to [Flow Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3qAMKwawB2hzeAvqJFo6AORYS5fgG5EiEKAAKoALQA+Gb3QBnSWAAi8pZsKRiAV2h5pK9VIDKO0JZzEchCTgCe6QrfuPQAXhqJQUDhiABNkZgBzAC5QACNYWGgSZgoA0CEeQlUAC3DouISk4hTEDnFEV3dQADFDZnJkFgYmVnYAHmklPwAKdHMY6QBKXyUAfiIyHAASAFEk1DYcNuKXBXFKjzpoYlVVZsxWpc0qaSpLLvpt3baJ8in9lkW245kzhTWKt03GA8WAFS+zxOb18lx2ex+j3aL1OtiUAB8anUGk1IYcOh8NqAAOrIHDZAAyyEghFILlISQehy24IxvjSNN2VKeADdYMgQlQpppiZAOmcvIQFAKHELyqQWKo8PA8YTiaTyUlQUDXnDunQMDFmewAe4VbDzoMYrj8USSWSKYRtThGao6T4lNQJIEKeCcbKzQrLaBCAAPRzMEKqehoxb+QKBVCwOqOEIxeKJZLlCOgPqwNQxbm8-meUUfFNS0UxOyi0FOlOBYJhSIxHBYQyEVIV9L6IQ5PIxAzQVROFNlZ0RiUtRa46DQACqzCjMe6w3LFfxyFUADpp+xCCFQV2e+I+wPAjsXPVQKRiGOAPLMACy0fYs-DFYlzClNFALBvMdAXD8i5XabUu4VsSoDdAAhO+t44MMQg4IYWDMIBKZ1i4D7NsQ8DEHib7XpB3S-su-6qIMiFAZAeG5Cua6xnOaTNoE+E9jgJaON0tBVh23Bnj2X7EbRFYcPuEYCc2p44KQ2QgYQNF0aAxLkUuq6QRu0kyaADGEExgqsUEsChBx24eBwvEycJdH4rw8A+iRgSmTZglDr87A8iEH53ipSEUYpMYbqCdYNtZameaeF44TOxlCcmEZCIGhBYPe84pk+L5sbp1YRFQGRtrkkRfr5nmFo4AUwXBzAgXxKZtBq6DlRW7GRD41B1REtl0ZlWTZREDVte2kQtc21DLoN+GEX1EbAAoNXhXZdlpMV8Huqa8oWkk4j9ogfqYLgoAhPoRgmKAMqLeaiqEOIQA)

The issue seems to be that Flow doesn't understand that `P` can be an object. Please help

**Comment by SamChou19815** [comment]
The repro is quite old so the libdef has drifted a lot, so it's unclear what exactly is the issue.
