### ISSUE TITLE
Do we really need DefaultProps type in react?

### ISSUE THREAD

**Issue by klimashkin** [facebook/flow#4462]
Type for DefaultProps seems redundant, makes code bloated and sometimes leads to unexpected behavior.

The most common issue is that Props types are being replaced by Default types, which people don't expect:
```javascript
/* @flow */
import React, { Component } from 'react';

type PropsType = {title: boolean | string};
const defaultProps = {title: true};

class A extends Component<typeof defaultProps, PropsType, void> {
  props: PropsType;
  static defaultProps = defaultProps;

  render() {
    let title;

    if (this.props.title === true) {
      title = 'I am a div';
    } else if (this.props.title) {
      title = this.props.title;
    }
      
    return <div title={title}/>
  }
}

<A title='I am a custom title'/>
```
```
24: <A title='I am a custom title'/>
             ^ string. This type is incompatible with
5: const defaultProps = {title: true};
                                ^ boolean
```

So we have to write
```javascript
/* @flow */
import React, { Component } from 'react';

type PropsType = {title: boolean | string};
type DefaultPropsType = {title: boolean | string};

class A extends Component<DefaultPropsType, PropsType, void> {
  props: PropsType;
  static defaultProps = {title: true};

  render() {
    let title;

    if (this.props.title === true) {
      title = 'I am a div';
    } else if (this.props.title) {
      title = this.props.title;
    }
      
    return <div title={title}/>
  }
}

<A title='I am a title'/>
```
So we ended up repeating ourselves specifying props and types for them twice (say hello to DRY)
We can workaround and write 
```javascript
type PropsType = {title: boolean | string};
type DefaultPropsType = {title: $PropertyType<PropsType, 'title'>};
```
to stop repeating types definitions at least.

But why?
Example above is simple with one prop and one defaultProp. But we have components with dozens of props and dozen of defaults. And it looks really ugly.

Values in default props can't have different type from PropsType, and flow should just validate values in `static defaultProps = {}` so they have right type.
It will make codebase much clearer and eliminate common developers confusion about $Diff<PropsType, DefaultPropsType> behavior.

**Comment by vkurchatkin** [comment]
`DefaultProps` is required, because type of `this.props` depends on it

**Comment by klimashkin** [comment]
@vkurchatkin 
But flow sees what props has default values and can infer types in `static defaultProps`

**Comment by klimashkin** [comment]
> DefaultProps is required, because type of this.props depends on it
Moreover why do we need to specify types for default drops in PropsType if anyway they are replaced by DefaultPropsType?

**Comment by Hypnosphi** [comment]
> The most common issue is that Props types are being replaced by Default types, which people don't expect

This looks like a bug in `$DIff`

**Comment by peterpme** [comment]
:wave: I'm running into the same issue. Any help in the right solution would be appreciated! Thanks!

**Comment by vkurchatkin** [comment]
@etrepum what problems are you referring to?

**Comment by etrepum** [comment]
Some examples: #4644, #4848

**Comment by SamChou19815** [comment]
Now `React.Component` no longer has a type parameter for `DefaultProps`
