### ISSUE TITLE
Array prototype functions error out on disjoint union

### ISSUE THREAD

**Issue by chrisirhc** [facebook/flow#4465]
Not sure why Array.prototype methods like forEach cause an error like the following in the following examples:
```
2: type X = {type: 'x'};
                   ^ string literal `x`. Expected string literal `y`, got `x` instead
3: type Y = {type: 'y'};
                   ^ string literal `y`
3: type Y = {type: 'y'};
                   ^ string literal `y`. Expected string literal `x`, got `y` instead
2: type X = {type: 'x'};
                   ^ string literal `x`
```

[Has error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYY3o5r2e7-gwo49AKABcBPABwFMwANMAXjAG8q6AuMAcgA9eAXwDcFGvQCaLdp1o9elYWNJQArgDsAxuQCWcDWHK0AzuQAUANx4BBAE52AhpQA8DAHxgAPmHtPXku4AlOykaJYAdFBwdgCijloAFubmIcyeGmowMEFiQkA):
```javascript
/* @flow */                                                                                                                           
type X = {type: 'x'};
type Y = {type: 'y'};

function test(v: Array<X> | Array<Y>) {
  v.forEach(() => null);
}
```

[No error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYY3o5r2e7-gwo49AKABcBPABwFMwANMAXjAG8q6AuMAcgA9eAXwDcFGvQCaLdp1o9elYWNJQArgDsAxuQCWcDWHK0AzuQAUANx4BBAE52AhpQA8TAD5hJAPgCU7UjRLADooODsAUUctAAtzc39mbzANNRgYXzEhIA):
```javascript
/* @flow */                                                                                                                           
type X = {type: 'x'};
type Y = {type: 'y'};

function test(v: Array<X | Y>) {
  v.forEach(() => null);
}
```

[No error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYY3o5r2e7-gwo49AKABcBPABwFMwANMAXjAG8q6AuMAcgA9eAXwDcFGvQCaLdp1o9elYWNJQArgDsAxuQCWcDWHK0AzuQAUANx4BBAE52AhpQA8DAHxgAPmHtPXku4AlOykaFBwdmDmMLTkYAD6lmBwUGCWIWxh6FoGJnCxAHTwAObmvAAmcGAacOQAFroaJbxBYmhCpEJAA):
```javascript
/* @flow */                                                                                                                           
type X = {type: 'x'};
type Y = {type: 'y'};

function test(v: Array<X> | Array<Y>) {
  for (let _v of v) {
    console.log('do nothing');
  }
}
```

**Comment by btford** [comment]
Worth noting that using exact types in each of these cases seems to show the same incorrect behavior.

**Comment by Hypnosphi** [comment]
[Also no error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYY3o5r2e7-gwo49AKABcBPABwFMwANMAXjAG8q6AuMAcgA9eAXwDcFGvQCaLdp1o9elYWNJQArgDsAxuQCWcDWHK0AzuQAUANx4BBAE52AhpQA8DAHxgAPmHtPXku4AlOykaFBwdmDmWgZmYLrGALZgcFBgliFsYWAAkLEaJnAwtAB08ADm5om0SUE5QqRCQA):
```
/* @flow */                                                                                                                           
type X = {type: 'x'};
type Y = {type: 'y'};

function test(v: Array<X> | Array<Y>) {
  for (const item of v) {
  	console.log(item)
  }
}
```

**Comment by SamChou19815** [comment]
This now works
