### ISSUE TITLE
Validation silently failing for libs that export types

### ISSUE THREAD

**Issue by Rovack** [facebook/flow#4466]
Assuming I have the following file in my "/flow" directory (which is under `[libs]` in my .flowconfig):
```
// @flow
type Foo = {
  bar : strng,
};
```

Clearly I have a typo, and the type "strng" is not actually defined anywhere.
Normally, when I run flow validation, I'd expect to get the error: ``identifier `strng`. Could not resolve name``.

However, if the file is instead:
```
// @flow
type Foo = {
  bar : strng,
};
export type Baz = {};
```
Flow validation passes successfully and shows no errors, despite the typo.
It appears that at that point, any variable throughout my codebase annotated with `Foo` will accept _any_ value, of any type, for the `bar` property.

This all means validation is essentially silently failing.

It's very strange that this only seems to be happening when I have an exported type in the same lib 
file as the typo (even if it's not the broken type itself that's exported).

**Flow version**: 0.42.0.

If my full flowconfig could be of use, I'd be happy to attach it (for the most part, though, it's just the standard config that React Native generates).

**Comment by Rovack** [comment]
I take it nobody has any ideas for why this might be happening, or how it could be solved?

**Comment by jbrown215** [comment]
Hey @Rovack 

Some thoughts about what might be happening here:

I'm not sure why you need the `export type Baz...` to run into this issue. I was able to do it without that line.

Flow doesn't type check library definitions-- it trusts that they are correct. When Flow saw you mention some type `strng`, it tried to find where it was defined. I bet that flow just defaulted to `any` when it couldn't find what `strng` meant.

Maybe it would be possible to add a warning when this happens. @ballardrog, what do you think?

**Comment by ballardrog** [comment]
When I was reproducing this locally, I noticed that the error does show up over the persistent connection, even though it doesn't show up in the CLI. (Also, I didn't need the `export type Baz...`, either.)

I'm all for having this show up as a type error in the CLI, although there might be a reason for it being this way that I just don't know about.

cc @samwgoldman

**Comment by Rovack** [comment]
@ballardrog @samwgoldman So, 6 weeks later, is it safe to assume there is no significant reason? :)

It would be really great if this could be fixed, since as it stands we've encountered many cases where type errors existed (and in some cases _many_ errors, where the non-existent type was part of a larger union type), but we failed to discover them for weeks/months, until a minor typo happened to be noticed and fixed.

**Comment by Rovack** [comment]
More like 6 months now...
Oh well, anyway the organization has now switched to TypeScript.

**Comment by mwiencek** [comment]
@jbrown215 Hi, I ran into this issue today in a project I work on, and it was indeed triggered by the presence of `export` for me too. I created a minimal test case reproducing the issue at https://github.com/mwiencek/flow-issue-4466

**Comment by SamChou19815** [comment]
This should now error
