### ISSUE TITLE
Error when cast a mixed(?Object | ?Array<Object>) type to a flow type alias(an object)

### ISSUE THREAD

**Issue by jaybowong** [facebook/flow#4467]
[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgBKeAzjnAHYkEC8YA3qmM2HgE5txsCypJAhgHM8ALjAB+EhjYBLCoIA0TFgBN+GfmPEB5AEYArPAGMMYAD4SAgh35YAPHsMmAfGGDAwASQwByEmG0AaTAEAAs8Ci8wAFdqCX4KLDA5KTx+FTA4KCsbe0djDGdUAF9MXAIAVWo2TwooODA6RhYwCn4AW1EwKVl5JRbhChV2MQpo9t12EvQjGH4SfwAxeAQAUQ4uBnQWgH1h9oa6AAo2UnIqLuIySmoASkbXZpaWIxvTWPZa+oBGRrAjk5nG54AB0ag0WnyJluWiqnzqcFuAG5lM8wK8qO9ql84AAmP6A64XMHqTQSKEYZGosClFolIA)

It's OK when I use `?any` instead of `?Array<Object>`.

**Comment by SamChou19815** [comment]
This now works.
