### ISSUE TITLE
Generic "object as map" type isn't checked properly

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#4469]
```
/* @flow */
type Hash<T> = {[string]: T}

const f = (val: Hash<number>): Hash<string> => val
```

gives no errors: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwASAhgM4AWAPACoB8YAvGAN4DaJ6ATgJYB2A5gF0AXGCoBfVKgDGcHuzBQGYABQA3IjBHFyFHgFcAtgCNcHGgEotpSu27869OupiogA

If I change it to explicit
```
/* @flow */
const f = (val: {[string]: number}): {[string]: string} => val
```

It gives the expected error:
```
2: const f = (val: {[string]: number}): {[string]: string} => val
                              ^ number. This type is incompatible with the expected return type of
2: const f = (val: {[string]: number}): {[string]: string} => val
                                                   ^ string
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5hRgC8YAFAG4CGMAXGAN4Da+ATgJZYDmAuvVgFcAtgCMApqwC+ASnrM2nXvQXdJJAHxhqMVEA

**Comment by kangax** [comment]
This seems to be fixed now (on flow.org/try, using 0.85)
