### ISSUE TITLE
Add MediaQueryList type definitions

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#4470]
Flow seems not to recognise these standard interfaces, which are [widely supported](http://caniuse.com/#search=matchMedia) in browsers:

- [MediaQueryList](https://developer.mozilla.org/en/docs/Web/API/MediaQueryList)
- [MediaQueryListEvent](https://developer.mozilla.org/en/docs/Web/API/MediaQueryListEvent)
- [MediaQueryListListener](https://developer.mozilla.org/en/docs/Web/API/MediaQueryListListener)

I'm currently using this in a libdef in the root of my project:

```js
declare type MediaQueryListEvent = {
  matches: boolean,
  media: string,
};

declare type MediaQueryListListener = MediaQueryListEvent => void;

declare type MediaQueryList = {
  matches: boolean,
  media: string,
  addListener: MediaQueryListListener => void,
  removeListener: MediaQueryListListener => void,
};
```

Happy to PR if someone can guide me – should it go in the [BOM](https://github.com/facebook/flow/edit/master/lib/bom.js) file? Is it correct? Should I also add a declaration for [window.matchMedia](https://developer.mozilla.org/en-US/docs/Web/API/Window/matchMedia), and how?

**Comment by asolove** [comment]
@calebmer Needs label: Library definitions

**Comment by calebmer** [comment]
We’d love to merge a PR if you want to fix this 😊
