### ISSUE TITLE
Callable signature not found in prototype

### ISSUE THREAD

**Issue by zerkalica** [facebook/flow#4473]
How to extract argument signature from function?

```js
type _PropsOf<Props, C: (props: Props, state?: any) => any> = Props;
type PropsOf<C> = _PropsOf<*, C>


function a(props: {some: number}, state: any): any {
    return 123
}

// some not checked
const b: PropsOf<typeof a> = {some: '123'}

//  Callable signature not found in prototype
const c: PropsOf<a> = {some: '123'}
```

[flow/try](https://flow.org/try/#0C4TwDgpgBA+gCgJwPZgM4HkBmAeRLUA0UAwgFxQAUYya5eaRqwAhsBAPznMB2IAlFAC8APig8QowVHqoA3AChQkaTQw5ik2DKzYAVEQ3yjmAK7cAxsACWSbmKqryAb1RIAthHLcTbgEYQEAF9GFjYuXj5wkCgneSh4qAQIYBMEOwBGACYAZnlAowB6AqhXDyhuJGAocwALCHMAawgAE3lzWyYoXzpVHSUIJEwxTRd3TygAcizsifz5IvjiZgAbZeZfZehUKwBzblZU6AqqzCQzZqgrO2pKyvAINo6q8x78HWYR0vGpnNn5IA)

**Comment by goodmind** [comment]
This is possible with `$Call`

```js
type PropsOf<F> = $Call<
  <Props>(f: (props: Props, state?: any) => any) => Props & Props,
  F
>;


function a(props: {some: number}, state) {
    return 123
}

const b: PropsOf<typeof a> = {some: '123'}
```

[Try Flow](https://flow.org/try/#0C4TwDgpgBACgTgezAZwPIDMA8AxAfFAXigBIBhAQwBtLMAoKKTeJZXACnQC4o2xEVuzFABooyYOWAQA-N3IA7EAEpC+BctWx+yKADItLYfSjZauANy0r6AK7yAxsACWCeVHK9t3AN7IEAWwhueRt-ACMIOABfUXFJCBVvYwY4CGAbODcARgAmAGZaKKt7V3EoMMFtDExQSAR0d3wiXwCgqAByXLz2oqA)
