### ISSUE TITLE
Namespacing types?

### ISSUE THREAD

**Issue by mindeavor** [facebook/flow#448]
Is it possible to namespace types? I'm trying to declare a namespaced type in `[libs]` and use it across multiple files.

Here's what I have:

```javascript
declare module MyApp {
  type User = {
    id: string;
    name: string;
  }
  // etc.
}
```

but it throws this error:

    /Users/me/my-app/types/app-types.js:2:3,6: Unexpected token type

Is there a better way to do this?

**Comment by samwgoldman** [comment]
Right now you need to declare types at the top level of the declaration file, but you can reference them inside a declared module. If you need to namespace your types, I've often seen a naming scheme like `type MyApp$User`, but that's not necessary if you don't have a lot of types.

**Comment by samwgoldman** [comment]
@mindeavor Are you still having an issue here?

**Comment by mindeavor** [comment]
That workaround is acceptable, thanks.
