### ISSUE TITLE
Use of $ReadOnlyArray<T> within a type causes type-at-pos to return (unknown) for entire type

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4480]
[Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagGK1qALygDeoA2gM7IBOAlgHYDmAugFygAkASpgIYATAPINoqAII0afVAB5q9ZgD5QAX0QBjWA2qhI+UBzwFiZfbA7kA5ACM+NKyzWIUGbACF7RUhQWNWHJLScn7Kzlo6yKB2NIagnrGm0faWVuaOakA)

```js
// @flow
type Foo = { [string]: $ReadOnlyArray<string> }
const foo : Foo = { foo: ['bar'] }

type Bar = { [string]: Array<string> }
const bar : Bar = { bar: ['foo'] }
```

In the above, `foo` is typed as `(unknown)` whereas `bar` is typed as `{[_: string]: Array<string>,}`

```
$ flow type-at-pos index.js 3 7
(unknown)
index.js:3:7,3:15

See the following locations:
index.js:3:13-15:
Foo
```

```
$ flow type-at-pos index.js 6 7
{[_: string]: Array<string>,}
index.js:6:7,6:15

See the following locations:
index.js:6:13-15:
Bar
```

**Comment by mpal9000** [comment]
#4361

**Comment by asolove** [comment]
Closing this as a dup of #4361, so let's discuss over there.
