### ISSUE TITLE
Intersection with a disjoint Union

### ISSUE THREAD

**Issue by yachaka** [facebook/flow#4482]
How can I make an intersection of an object and a disjoint Union ?
To specify that the object always have a set of property, and additionnaly either this set or this set:
```js
/* @flow */

type O = {
  str: string,
  num: number,
};

type PossibleProps = {
  prop1: string,
  prop2: string,
};

type OtherProps = {
  prop3: string,
  prop4: string,
};

type T = O & (PossibleProps | OtherProps);

function fn(o: T) {
  if (o.prop1) {  // flow error :s
    return o.prop2;
  }
}
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyYAvGAN6phgDOGATgFy0MCWAdgOYA0VY7AVwC2zQUIBGeerwC+AbnTZ8YAApwaNVuJh4V9ODhqkKfHPpwBGZnXocep8wCZrbLrIWZcBQhgAWUvQMjMkpqMwMAZhdbNwcDABZou3dFLzAAFWNiADIwAAo1DS0dQMMwAB8iPwDzGgBKDygBdgBjDFY4djAodjy4ZnS6k2pWKHy4ADpwyyHQ6jB6PAwBei7J6ccFahlUGSA

**Comment by rsolomon** [comment]
[Disjoint unions](https://flow.org/en/docs/types/unions/#toc-disjoint-unions) must be tagged by a single property for refinement. It does still seem to be an issue with intersections though, so you could distribute the unioned type, ex:

```
type O = {
  str: string,
  num: number,
};

type PossibleProps = {
  type: 'type1',
  prop1: string,
  prop2: string,
};

type OtherProps = {
  type: 'type2',
  prop3: string,
  prop4: string,
};

type T = (O & PossibleProps) | (O & OtherProps);

function fn(o: T) {
  if (o.type === 'type1') {
    return o.prop2;
  }
}
```

[On flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyYAvGAN6phgDOGATgFy0MCWAdgOYA0VY7AVwC2zQUIBGeerwC+AbnTZ8YAApwaNVuJh4V9ODhqkKfJXmYByMwEYLvajn05rzOvQ48+jgwCZXbLlkFTFwCQgwACyk9AyMySmozSzMfOy8nAGZ-d0D0gwAWbI8gxVCwABVjAApiADJVdU1tXScaAEowAB8wGrB68Kj6GMM24KgBdgBjDFY4djAodiq4ZnKOhLBWKB64ADozUhIyK1Dbdb5qejwMAXp5ve8cHwVqGVQZIA)

**Comment by asolove** [comment]
The above answer is right that you need a distinguishing key. Remember that object types aren't exclusive. An object can be of type `PossibleProps` and just happen to also have a `prop3` key on it, so that test isn't proof of which type we have in the code.
