### ISSUE TITLE
Bug: Flow accepts function in recursive property type

### ISSUE THREAD

**Issue by aeruhxi** [facebook/flow#4484]
[flow-try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAaYAvAN6phgAeA-AFxgB2ArgLYBGeATgDSVgsDZuy58BAbWqMAzhm4BLJgHMAurPlLlYAD4jOPXUVQBfMOgAmeAMYwAhtwJQWTaxgVwmYKHDgAKaSIASkYANzgFC3Qffz8g0gA+MAAmeOBgMAQACyxmODAebjhuWlQgA)

Why is `foo` accepting function in this case? Is this a bug or intended?

```js
/* @flow */

type X ={
  x?: number,
  y?: number,
  [x: string]: string | number | X
} 

declare function foo(x: X): void

foo(() => 2) // why no error?
```

**Comment by jcready** [comment]
This has nothing to do with recursive types, and everything to do with the fact that functions are objects. [This passes as well](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDyARgFZgC8YA3gL6pQCuAdgMboCWcTYU3AFAEpqdPrwBchUgKA) and I believe is working as intended:

```js
/* @flow */
type Obj = {}
function fn () {}
(fn: Obj) // no errors
```

However if you define just one non-maybe property on your object type then flow will complain:

```js
/* @flow */
type Obj = { x: number }
function fn () {}
(fn: Obj)

// Flow error
4: (fn: Obj)
        ^ property `x` of object type. Property not found in
4: (fn: Obj)
    ^ function
```

But you can then still pass in a function so long as it has that property on it:

```js
/* @flow */
type Obj = { x: number }
function fn () {}
fn.x = 1;
(fn: Obj) // no errors
```

For some reason flow [**does** make a distinction between arrays and objects](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDyARgFZgC8YA3gL6oDGcAdgM7pgCGATlxWANoBdANyoAFNy4AuQqQCUQA) (even though arrays are also objects):

```js
/* @flow */
type Obj = {}
const arr = [];
(arr: Obj)

// Flow error
4: (arr: Obj)
    ^ empty array literal. This type is incompatible with
4: (arr: Obj)
         ^ object type
```

**Comment by abs-zero** [comment]
Yup functions are objects but to get around that, I did put ` [x: string]: string | number | X`..
Also, if I do
```
/* @flow */

type X ={
  x?: number,
  y?: number,
  [x: string]: string | number // removed X
} 

declare function foo(x: X): void

foo(() => 2) // error now
```

**Comment by jcready** [comment]
You can also [trick flow into thinking a plain object is a function](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5hwBGAVmALxgDeYAJOgIYwwBcYAFAJTkB8VAvmH4BuVO2Ik2AMQCuWdHgCW2TkA) by adding a `$call` key whose value is a function to it:

```js
/* @flow */
const obj = { $call: ()=>{} };
(obj: Function)
```

**Comment by jcready** [comment]
@abs-zero you can "fix" your type definition by doing this:

```js
/* @flow */

type X = {
  $call?: empty, // important bit
  x?: number,
  y?: number,
  [x: string]: string | number | X
}

declare function foo(x: X): void

foo(() => 2)

// Flow error
12: foo(() => 2)
        ^ statics of function. This type is incompatible with the expected param type of
10: declare function foo(x: X): void
                            ^ object type
```

**Comment by abs-zero** [comment]
Oh thanks! I am going to try this.

**Comment by abs-zero** [comment]
Just to be clear if it a bug or not, 
```
Why is foo accepting function in this case? Is this a bug or intended?

/* @flow */

type X ={
  x?: number,
  y?: number,
  [x: string]: string | number // remove X
} 

declare function foo(x: X): void

foo(() => 2) // error
```
So, I thought if this has something to do with recursive. Typescript doesn't seem to show this behavior.

**Comment by jcready** [comment]
Yeah, you're right. There is something weird going on with the recursive type there. One [rather annoying issue](https://github.com/facebook/flow/issues/4358) with flow's type-at-pos is that it reports recursive types as `any`. In fact, it reports your `X` type as the following (note the `any` at the end):

```js
{x?: number, y?: number, [x: string]: number | string | any,}
```

I thought the recursive type checking was still working properly though. I assumed that it was just the output of type-at-pos that was inaccurate, and that the actual type checking was still sound. But maybe I'm wrong.

**Comment by SamChou19815** [comment]
It errors now
