### ISSUE TITLE
[suggestion] Blog and other such docs

### ISSUE THREAD

**Issue by bodawei** [facebook/flow#4486]
Recently, I did a comparison between Flow and TypeScript at my company. One of the places where flow showed up less well by comparison was in some of the information surrounding it.  For instance, there is very little in the Blog about new features (I do see Jordan Brown made a new post a couple days ago.  Keep it up!), and little insight into where the project is going (roadmap, goals, what is in and what is out of consideration etc).  I think it would help the Flow effort to do a bit more in this arena!

**Comment by asolove** [comment]
In the last month, I think this has really improved with more blog posts, a new blog on Medium that should be more friendly, and also more community communication stuff going on. Based on that, I think I'm going to close this issue as having been pretty well improved this month.
