### ISSUE TITLE
Difference adding Union on Type vs accepting as UNION parameters

### ISSUE THREAD

**Issue by lvdang** [facebook/flow#4491]
Is there a difference with passing via UNION with string vs passing in with as a type? I get an error with I pass with type but if I pass as function no errors. 

try in : https://flow.org/try

1) ERROR

```js
/* @flow */
import {PureComponent} from 'react';

type UnsealedObjectType = {};

type ParamsOptionsType = string | number | UnsealedObjectType;

type ParamsType = { [string]: ParamsOptionsType};

 
type NavigateToType = {
  to: string,
  params?: ParamsType,
  options?: ParamsType,
  pageName: string, 
};

type NavigateArgsTwoType = NavigateToType | string;

function navigate(arg: NavigateArgsTwoType) {
    if (typeof arg === 'string') {
      arg = {to: arg, pageName: '', params: {}, optons: {}};
    }
   let {params = {}, to, options = {}, pageName}: NavigateArgsTwoType = arg;  
}


navigate({to: 'hello', params: { name: 'helloWorld'} , options: { }, pageName: 'somePage'});
```

2) WORKS - using UNION | string in function

```js
/* @flow */
import {PureComponent} from 'react';

type UnsealedObjectType = {};

type ParamsOptionsType = string | number | UnsealedObjectType;

type ParamsType = { [string]: ParamsOptionsType};

 
type NavigateToType = {
  to: string,
  params?: ParamsType,
  options?: ParamsType,
  pageName: string, 
};

type NavigateArgsTwoType = NavigateToType;

function navigate(arg: NavigateArgsTwoType | string)  {
    if (typeof arg === 'string') {
      arg = {to: arg, pageName: '', params: {}, optons: {}};
    }
   let {params = {}, to, options = {}, pageName}: NavigateArgsTwoType = arg;  
}


navigate({to: 'hello', params: { name: 'helloWorld'} , options: { }, pageName: 'somePage'});
```

**Comment by DanielHeath** [comment]
It'd help if you posted those as regular try-flow links: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYA3gAoCueApgMJw5wB2VjBAvmFHvWAOTUBDAMYFeAblSoCAT2xUwAVUYBnKgJhUAJgHkARgCsqIgCqz5AXhJsJUs2FIC8AzMu3YC6JstNywl5QR46IwA5mAAPmCM5Ji6VHgRiipqGjoGRgQ+VDYyvg5OLll+JGAA2gFBoQC6AFz2js6u7p4qWdaSufIAcgIAbughAgRUxnBFlsRScHUVwSEANKjYDS4A-HX5jVmLcM1e6-UF3maLyyFUPZhUM4Fzi+22vj39g8MAgngh3ghjdpbPAyGI1+vkis1CNig5EYIhaUT6gOGAApHCE6gDXlQPl9jD8sgBKEgYKBgJGdOAk1F+cyWXjgkK8QmTKkTAjTMCo+ZgM4XZzXPi8LnLI51YhsLm7NkqUVsdpsVAaIjEYWNYpirlsiV7FRq8XcgTnS5UNjohGY7HfEEWDmfCTy1CMM1ApHENl1XgACyoMHggv1IpKjqu7q9PrgAHV8DBNLwOFqPF5RWA9Tyje7lPQqA5zrH8RIgA and https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYA3gAoCueApgMJw5wB2VjBAvmFHvWAOTUBDAMYFeAblSoCAT2xUwAVUYBnKgJhUAJgHkARgCsqIgCqz5AXhJsJUs2FIC8AzMu3YC6JstNywl5QR46IwA5mAAPmCM5Ji6VHgRiipqGjoGRgQ+VDYyvg5OLll+JGAA2gFBoQC6AFz2js6u7p4qWdaSufIAcgIAbughAgRUxnBFlsRScHUVwSEANKjYDS4A-HX5jVmLcM1e6-UF3maLyyFUPZhUM4Fzi+22vj39g8MAgngh3ghjdpbPAyGI1+chsUHIjBELSifUBwwAFI4QnUAa8qB8vsYfkVIrNQgBKEgYKBgeGdOAkpF+cyWXh4kK8QmTKkTAjTMBI+ZgM4XZzXPi8LnLI51YhsLm7NkqUVsdpsVAaIjEYWNYpirlsiV7FRq8XcgTnS5UNgo2FojHfEEWDmfCTy1CMM1A+HENl1XgACyoMHggv1IpKjqu7q9PrgAHV8DBNLwOFqPF5RWA9Tyje7lPQqA5zrH8WIgA

**Comment by lvdang** [comment]
thank you for the information

**Comment by asolove** [comment]
I think you may have been looking at the wrong line. This is the line that's the problem:

```js
   let {params = {}, to, options = {}, pageName}: NavigateArgsTwoType = arg; 
```

In the working case, `NavigateArgsTwoType` is just `NavigateToType`, which is an object and allowed to be destructured. In the case that errors, that type also allows just `string`, which can't be destructured.

If you change that line to

```js
   let {params = {}, to, options = {}, pageName}: NavigateToType = arg;  
```

then the code works either way.

**Comment by lvdang** [comment]
@asolove - thanks. I see your point.
