### ISSUE TITLE
The Promise type is incorrectly defined

### ISSUE THREAD

**Issue by alexandru** [facebook/flow#4498]
Currently here: https://github.com/facebook/flow/blob/master/lib/core.js#L660

Problems:

1. `Promise` SHOULD NOT be defined as a class, because it forces nominal typing
2. `Promise` should be an interface, not a constructor, with only `then` and `catch` methods and that's it

Currently the definition is as follows:

```typescript
declare class Promise<+R> {
    constructor(callback: (
      resolve: (result: Promise<R> | R) => void,
      reject:  (error: any) => void
    ) => mixed): void;

    then<U>(
      onFulfill?: (value: R) => Promise<U> | U,
      onReject?: (error: any) => Promise<U> | U
    ): Promise<U>;

    catch<U>(
      onReject?: (error: any) => Promise<U> | U
    ): Promise<R | U>;

    static resolve<T>(object: Promise<T> | T): Promise<T>;
    static reject<T>(error?: any): Promise<T>;
    static all<Elem, T:Iterable<Elem>>(promises: T): Promise<$TupleMap<T, typeof $await>>;
    static race<T, Elem: Promise<T> | T>(promises: Array<Elem>): Promise<T>;
}
```

This type is then forced on `async` methods as well.

Which means that it is impossible to define custom async types according to the [Promises/A+](https://promisesaplus.com/) specification.

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2171
