### ISSUE TITLE
No error: hash-map object expected but Map object provided

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4499]
I get it that everything is an object - but ["Objects as maps" is a special type that even got its own syntax](https://flow.org/en/docs/types/objects/#objects-as-maps-a-classtoc-idtoc-objects-as-maps-hreftoc-objects-as-mapsa).

Below function `fn` expects such an "object as map", but when I call the function with a `Map` as parameter there is no error. The wrong kind of object-map does produce an error.

[Try it.](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKLGwB2eoktoAvKABRb4BuJm6ALlABvANp4itAOYBdIQDFUtUoToBfAJRCALACZWAPhGJQp0Pky5U+ZnsprKiEKADyAawCGAT1ABaUACi+Piw+AB01HQMALYAjKwiyJCwsMhCkB7QWA6ITOxxGo7OAHIugQBK5S7lAPx1kfS4oNH6bLSY8KAAsh4ADuyFubT5uoNOYKUVVbX1NI3NAMxCPb0APLSo0QBGmPgANDgEhNJGbR3dfQOUedELg0A)

```javascript
// @flow
'use strict';

const fn = (services: {[string]: Function}): void => {
    //...
};

// Okay - Error.
const m1 = {'foo': false};
fn(m1);

// NO ERROR???
const m2 = new Map();
fn(m2);

// NO ERROR???
const m3: Map<number, string> = new Map();
fn(m3);
```

**Comment by jcready** [comment]
You can work around this by changing your function annotation to [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AEgArQCGAlgHYDyARgFYA8AKgHygC8oDoAZKAN6gBqAMawyAZxQAnAK5CUsSQH4AXKCwBbDOlABfRCPEpQkMm1AAKMVkkA3EkKxjVBYuWr1eAbQmTyAcwBdVQAxaTI5ElEdJgBKVRtYEgATNhZeHQBuZBNzXkhYWGUTHRiM0BBQDCIxKzFEHLyCoqJoKxLysGtJBXqyczIseFAAWSIMcxjSjrVJbskgA):

```js
// @flow

type $PlainObj<T> = T & { +constructor?: empty }
const fn = (services: $PlainObj<{[string]: Function}>): void => {};

fn({foo:fn}); // passes
fn({foo:false}) // error
fn(new Map()); // error
```

**Comment by asolove** [comment]
Hmm, this is presumably caused by the `Object` typings having the line `[key:any]: any;`. Hard to see how that can changed to disallow this but allow the existing ergonomics of working with plain objects.

**Comment by SamChou19815** [comment]
Now errors.
