### ISSUE TITLE
Flow 0.11.0 Sigsegv

### ISSUE THREAD

**Issue by DavidHarrison** [facebook/flow#450]
On Ubuntu 14.04 LTS, Flow 0.10.0 works well, however Flow 0.11.0 does large amounts of disk IO, and complains that the server is still initializing:
```
Error: flow server is busyzing. If it was just started this can take some time. Retrying... \
Error: flow server is busyzing. If it was just started this can take some time. Retrying... /
Error: flow server is busyzing. If it was just started this can take some time. Retrying... \
Out of retries, exiting!lizing. If it was just started this can take some time. Retrying... /
(Note that the message is originally flow server still initializing. If it was ..., before it is overwritten by Error: flow server is busy).
```

Looking at the log, it appears to be failing because of a sigsegv somewhere (not clear where) in the program:
```
[2015-05-16 20:07:10] Initializing Server (This might take some time)                                                        
[2015-05-16 20:07:10] executable=/media/Data/School/CompSci/client/flow/flow                                                 
[2015-05-16 20:07:10] version=0.11.0                                                                                         
Worker interrupted with signal: sigsegv                                                                                      
Fatal error: exception End_of_file                                                                                           
Fatal error: exception End_of_file
```

**Comment by bhosmer** [comment]
Hi David - thanks for reporting this. The sigsegvs are coming from the multiple child worker processes terminating: usually, this means they have either run out of memory or overflowed their stack. It sounds like you may have provoked the type checker into going into infinite recursion.

Unfortunately it will be difficult to troubleshoot this without a reproducible case (we're not seeing it on any of our tests or in-house code). Is it possible for you to narrow down your situation, or failing that, bundle up the whole project and send it to us? If either is possible, that would be a great help. Thanks!

**Comment by DavidHarrison** [comment]
I've re-factored the code since filing the report, and it now seems to be type-checking well under 0.11.0, so it may take a while before I can isolate a test case. Thanks!

**Comment by DavidHarrison** [comment]
The problem seems to come from my omitting type variables from class types in a union. The following code was causing the problem:
```javascript
/* @flow */
'use strict';

class Left<T> {
    val: T;
    constructor(v: T): void {
        this.val = v;
    }
}

class Right<T> {
    val: T;
    constructor(v: T): void {
        this.val = v;
    }
}

/* This is the source of the issue, it can be corrected with
 * Either<A, B> = (Left<A> | Right<B>) */
export type Either<A, B> = (Left | Right);

/*
export function left<A, B>(v: A): Either<A, B> {
    return new Left(v);
}

export function right<A, B>(v: B): Either<A, B> {
    return new Right(v);
}

export function either<A, B, C>(x: Either<A, B>, f: (l: A) => C, g: (r: B) => C): C {
    return (x instanceof Left) ? f(x.val) : g(x.val);
}
*/

export function mapLeft<A, B, C>(x: Either<A, B>, f: (l: A) => C): Either<C, B> {
    if (x instanceof Left) {
        return new Left(f(x.val));
    }
    return this;
}

export function mapRight<A, B, C>(x: Either<A, B>, f: (r: B) => C): Either<A, C> {
    if (x instanceof Right) {
        return new Right(f(x.val));
    }
    return this;
}
```

However, the issue only comes up when both `mapLeft` and `mapRight` are uncommented. If only `mapRight` is uncommented, it reports:
```
/media/Data/School/CompSci/flow-bug/either.js:11:7,11: Right
This type is incompatible with
/media/Data/School/CompSci/flow-bug/either.js:18:29,40: union type
```

**Comment by bhosmer** [comment]
Beautiful! Thanks so much for this David. Will update here with progress.

**Comment by DavidHarrison** [comment]
Thank you! Let me know if there is any way I can help.

**Comment by samwgoldman** [comment]
I'm no longer able to reproduce this. @DavidHarrison, are you still running into this issue?
