### ISSUE TITLE
Some errors appear only after some other are fixed

### ISSUE THREAD

**Issue by hackhat** [facebook/flow#4501]
Inside a component:

```
  _markAsRead = (notificationToUserId: string) => async (e) => {
    //                                                   ^ parameter `e`. Missing annotation
    e.preventDefault();
    e.stopPropagation();
    await this.context.callActionDispatcher(`notification.markAsRead`, {notificationToUserId});
  }

```

I got only one issue: `^ parameter `e`. Missing annotation`.

Once I fix this error like this:

```
  _markAsRead = (notificationToUserId: string) => async (e: SyntheticMouseEvent) => {
    e.preventDefault();
    e.stopPropagation();
    await this.context.callActionDispatcher(`notification.markAsRead`, {notificationToUserId});
  }
```

Now I get 21 more errors.

**Comment by asolove** [comment]
I'll defer to someone who knows the typing rules better to give this a complete answer, but I believe  this is unavoidable. Because of the way flow does type inference, if required annotations aren't present but it continued on anyways, it would get meaningless or even more type errors. Asking you to fill in what's required is probably better than making you dig through a bigger pile of mostly-meaningless errors all caused by it being missing.

**Comment by hackhat** [comment]
@asolove This is not a normal behaviour in flow. Normally it shows all the errors that have, maybe it says that there are more and are hidden. In this case the errors are not shown at all, is not even saying there are more errors. Also the errors are in another file and not really related to this missing annotation.

**Comment by asolove** [comment]
I have a mental model for this. But I admit my understanding of the Flow codebase is very fresh, so it might be wrong.

The way I think about it is that there's a difference between a type error and a missing required annotation, similar to the difference between a runtime error in your JavaScript and a syntax error.

A syntax error prevents the code from being parsed, so it never even starts to run, whereas a runtime error happens after it's already running, and some stuff can continue.

Similarly, I believe Flow has one phase of building the type dependency graph and another for actually running type inference and checking. If required annotations are missing, it can't build the graph and therefore can't even start checking the types. But if the graph can be build, then lots of errors can be found at the same time.

Maybe someone from the Flow core team can chime in on whether I've got that right :)

**Comment by hackhat** [comment]
Why has been closed? @asolove

**Comment by asolove** [comment]
As explained above, this is expected behavior and not a bug.

**Comment by hackhat** [comment]
ok
