### ISSUE TITLE
Feature Request: Error when using Promise in conditional

### ISSUE THREAD

**Issue by STRML** [facebook/flow#4502]
Imagine the following use case:

```js
class User {
  hasRole(string): boolean
}
```

And the code:

```js
if (user.hasRole('foo')) { ... }
```

Now imagine User is refactored to hit, say, a database:

```js
class User {
  hasRole(string): Promise<boolean>
}
```

The above code will still typecheck and in practice will always be taken, because Promises are truthy.

It would be great if this were an error by default, that could be overridden in the rare case you actually want to test the truthiness of a Promise by wrapping in `Boolean(...)`.

**Comment by vkurchatkin** [comment]
Closing in favor of issues regarding reachability

**Comment by STRML** [comment]
Thanks, missed in search, for those who find this please see #3862.
