### ISSUE TITLE
Not_found error from type-at-pos

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4508]
Flow v0.51.0

```sh
$ flow type-at-pos file.js 98 21
Not_found
Raised at file "map.ml", line 122, characters 16-25
Called from file "list.ml", line 88, characters 24-34
Called from file "set.ml", line 325, characters 37-58
```

**Comment by jcready** [comment]
Switching back to Flow v0.49.1 seems to have fixed the problem. So there must be some regression between those versions.

**Comment by asolove** [comment]
Is the file itself sharable (even if only privately to me?)? It's hard to debug otherwise since type at pos seems to work in general for me.
