### ISSUE TITLE
Covariant member of tuple

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#4509]
Is there a way to annotate covariant member of tuple, similarly to [covariant object properties](https://flow.org/en/docs/lang/depth-subtyping/)?
(In context of ADTs tuple and record are analogous types i.e. a product type)

Extended example from [docs](https://flow.org/en/docs/lang/depth-subtyping/):
```js
class Person { name: string }
class Employee extends Person { department: string }

var employee: { who: Employee } = { who: new Employee };
var person: { +who: Person } = employee;

var employeeTuple: [Employee, number] = [new Employee, 1]
var personTuple: [Person, number] = employeeTuple // Error!
```
[Try flow](https://flow.org/try/#0MYGwhgzhAEAKCmAnCB7AdtA3tNYC28AXNBAC6ICWaA5tAL4BQokMAongA4goCe880eAA9S8NABMYCZOizRx8DmESkCaUsTKUa9BgwBuywZ258icgO4ALFMXZde-etAC8lm8TTwL0e6ad0ANwGRhxIqGjE2ADU1rZw4bJ0rsYOZsEhiKn+8AAqAK5c5gDafo7wADQ4+XgARkgAuinFXj5lZlUAjA2Z0GEyaAVFxMXSEVVoNfWITW7wJuVDIAIA9Cu+iIgoiACEQA)

Analogous  way would be to mark first member as covariant like:
```js
var employeeTuple: [+Employee, number] = [new Employee, 1]
var personTuple: [Person, number] = employeeTuple // This would type check since first member of employeeTuple is covariant
```
This syntax is not currently supported in Flow.

Readonly tuple would also be enough for our use case, but I am not sure there is such a thing.

**Comment by asolove** [comment]
This looks like a great request. It's odd that tuples get neither the property variance of records nor at least the read-only option like arrays.

**Comment by wchargin** [comment]
Support. Tuple read/write semantics seem kind of weird: they are mutable (`t[0] = "hello"` is okay), but only support read-only array properties (`t.fill("wat")` gives "property `fill` missing in `$ReadOnlyArray`", as described in [the docs][1]). Having covariance annotations or `$ReadOnlyTuple<SomeNormalTuple>` would be nice.

[1]: https://flow.org/en/docs/types/tuples/#toc-cannot-use-mutating-array-methods-on-tuples

**Comment by Bannerets** [comment]
Read-only tuples would be useful in iterators:

```js
// `Iterator` is defined as `type Iterator<+T> = ...`
class SomeReadOnlyMap<K, +V> {
  values(): Iterator<V> { ... } // ok
  entries(): Iterator<[K, V]> // error, something like `$ReadOnlyTuple<K, V>` is required
}
```
