### ISSUE TITLE
flow doesn't consider that function redeclaration is hides previous declaration

### ISSUE THREAD

**Issue by vlastachu** [facebook/flow#4511]
https://flow.org/try/#0PTBmFcDsGMBcEsD2kAE1EFsAOiDOBTAHgBUAaFAJXOIDUBDAG3H2oEEAnAc1wC4UBJWPnZ0ARgyLEUAXgB8lWbIAUoSHyUA6LcQ7cAlDPm1Gzclo10uvFDqt6+xpvhQBvAFAgUKdvljh2qKqaWpb6ANwewAC+brEQMAjIKPAAJiTKsA72Nq5uXj5+ASiwETFu8XBIqKlKmSiQ4Biiwtm4sOzwkJy5+b7+qABEDIgMA6Wx6JC4I-gaw5xKNQMDenoRk9MSc4gLNQCMqxGRG7AoAB58bR1dMmiYOARKGACeAGKQ5AAsAEzkAOSQRBYfB-NZuIA
```
function id<T>(t: T): T {
  return t;
}

function id(t: number): string {
  return "lol";
}
```
Well, at first you may notice that something wrong in this types, because `number -> string` is not `T -> T`. But this is can be explained by Flow politics that Flow is plain js with type annotations and everything is ok with this rule. So this code obviously compiles into:
```
function id(t) {
  return t;
}

function id(t) {
  return "lol";
}
```

The problem in the next line: 
```
console.log(id(""));
```
At this line called second function `id` which body was written with constraint that `t` can be only `number`. String was passed as int and flow says "No errors!".

**Comment by asolove** [comment]
I would guess the issue here is that in library definitions, and some other contexts we want to allow multiple type signatures for a single function. But obviously, if they are two function declarations with implementation code, we should get a type error.

**Comment by SamChou19815** [comment]
Flow decides to be stricter in this case
