### ISSUE TITLE
ElementType

### ISSUE THREAD

**Issue by philippotto** [facebook/flow#4513]
The following code doesn't typecheck for me:
```js
export type SomeType = {
  aString: string,
  aNumber: number,
};

function f2<S: $Keys<SomeType>>(
  propertyName: S,
  value: $ElementType<SomeType, S>,
) {
  
};

function f1<S: $Keys<SomeType>>(
  propertyName: S,
  value: $ElementType<SomeType, S>,
) {
  f2(propertyName, value);
};

f1("aNumber",  2);
```

[Try](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKEC2wAqzUC8cA3gFBxwCGaMUAlgHYDmAXHAM62NMA05VAOQCumAEbAobBiPFQ+AXwDcpUgDMhDAMYw6EBnFUAmADxo2AEgDSwRO1NZc+AHxOAFPzBQIKWIgGVsNjQ+CgA3SgAbIWALAFEI4GwGGDwUe2xU4B50Jz4AShJ+UiUVdS0dPQMARlMLa1t0xxQXdwpPbwkkf0D0ELhwqJi4c3jE4GTMxszstFzSArIKI1d2ny6ArP7I6LzlErUq1wAiSmExCSPsuENdoA)

If f1 doesn't call f2 it typechecks. Am I missing something here?

**Comment by asolove** [comment]
This is caused by a specific issue with $ElementType reported here: https://github.com/facebook/flow/issues/4211 Going to close here and encourage discussion over there.
