### ISSUE TITLE
Width subtyping fails when type is an array

### ISSUE THREAD

**Issue by rosskevin** [facebook/flow#4516]
[Reproduction](https://flow.org/try/#0PTAEHcEsBMBcAtQGcCuAjWBPADpAdgOajQD2ApkngOSwQkBOA1hJAi2wIZ6gCC99HTAB4UeSCTwA+AFAhQASHixY2JAC4QAMwA2JcADoGBYGTzBSAYyTBtXY1DjwAtKgw58x6bLABlDgFtsbTJQCwlYMgAPWDVebh4UWBIAYRJA4IjQtOwJU1hpLGwQnxQCAgpYcW4AXlAAb1AI6NikWHoPABpQADcObRQyFraPUABfUAAfZGHCLzlwBkYkaU1RC0qJUHLYErKKqoA1PoGAClQ91qrY3fLLiQBKeulQUHoyWBR6bkKyEk1kUq3DY1aq1KitdqEKigAD8AIuwNALUB+wk+ia+VGczAL1xePxBMJROJRM0HEg2iQoHgZDe+hWa0RmgpEXoACFMAAVKK0E74bCJbnNaaQghdc5AqrqXj8QRCG6oqSPOrPV7vT7cKhoDj0KjSLHeUB+dIhMJ4DGxHigABKZAIVVC8BIJCQtMa8A4tBQrqpCBCAD1AwkkqkTZkwoFcuaCjgQrb7Ztag0LSLOj1joNU4QxtIza01Qm8NK+AJhPGqpJQLUANp1FNUADqHCQ8A8SWoXV6-UzjZ4VFGAF0vIaHGxXIURgsmFTNkgPMFQKwyP5QKIqtJtgq7ngjt2Tm9C0hqwAGAf3bGgABU15vN5HMDH6An2dIFFAADkAPKcuhMUCbJcV3wOdoBCHVSxWFlaQ5IVYBOKhNGdKgugPKV7iAA)

```javascript
// width subtyping doesn't work with with an Array<union>
// 	https://flow.org/en/docs/lang/width-subtyping/

// Sample context: An AutoComplete component
type Suggestion = { text: string, value: string } | string

// works
function getSuggestionValue(suggestion: Suggestion) {
  return typeof suggestion === 'string' ? suggestion : suggestion.text
}

//                                                     fails here.
function filterByText (inputText: string, suggestions: Array<Suggestion>) {
  return 'bar'
}

// Sample context: A Region chooser that uses the ^^^AutoComplete component
type Region = { text: string, value: string }
const regions: Array<Region> = [{text: 'Washington', value: 'WA'}]


// width subtyping works on single item union
getSuggestionValue(regions[0])

// *********
// width subtyping does NOT work on item inside array
filterByText('foo', regions)
```

Perhaps I'm missing something, but I see no reason why width subtyping works on an individual parameter, but fails in a typed Array.

Bug or misunderstanding?

**Comment by AugustinLF** [comment]
Here, you need to use a `$ReadOnlyArray`! Indeed, you pass regions to filterByText, but filterByText could add some strings to the array, since it works with suggestions.

**Comment by jbrown215** [comment]
@AugustinLF is correct-- this is not a bug.

https://github.com/facebook/flow/issues/4483 for more info :)
