### ISSUE TITLE
Cannot intersect type having an indexer to add properties

### ISSUE THREAD

**Issue by DullReferenceException** [facebook/flow#4518]
I'm not sure if this is a bug or a limitation, but this doesn't work quite right:

```flow
type TimingType = 'navigation' | 'frame' | 'mark' | 'measure' | 'navigation' | 'resource' | 'server';

type RequiredProps = {
  collectionURL: string
};

type DefaultProps = {
  maxSendRate: number,
  [TimingType]: boolean
};

type Props = RequiredProps & DefaultProps;
```

Specifically, Flow doesn't like `collectionURL` having a type of `string`, I assume because the indexer type assumes anything not defined in the object is of the index type. Is there a way to "merge" an object type with an indexer with another object type? Basically, I'd like `Props` to "extend" `DefaultProps` with `RequiredProps`.

**Comment by DullReferenceException** [comment]
This _almost_ works:

```flow
interface Props extends DefaultProps {
  collectionURL: string
}

interface DefaultProps {
  maxSendRate: number,
  [TimingType]: boolean
}
```

...but when I try to have an instance of `DefaultProps`:

```flow
PerfCollector.defaultProps = {
  maxSendRate: 1000,
  frame: true,
  mark: true,
  measure: true,
  navigation: true,
  resource: true,
  server: true,
};
```

...I get a bizarre error:

> Flow: property `$key` of DefaultProps. Indexable signature not found in object literal 
> Flow: property `$value` of DefaultProps. Indexable signature not found in object literal

**Comment by adalbert-h** [comment]
I encountered same or very similar issue. It can be reproduced with a simple example.

Given a single file with following content:

```js
// @flow

interface Foo {
    bar: string,
    [key: string]: string
}

const foo: Foo = {
    bar: 'bar'
};
```

Then Flow outputs:

```
example.js:8
  8: const foo: Foo = {
                ^^^ property `$key` of Foo. Indexable signature not found in
  8: const foo: Foo = {
                      ^ object literal

example.js:8
  8: const foo: Foo = {
                ^^^ property `$value` of Foo. Indexable signature not found in
  8: const foo: Foo = {
                      ^ object literal
```

**Comment by weizongqi1990** [comment]
Has the problem been solved? @DullReferenceException @adalbert-h

**Comment by adalbert-h** [comment]
I updated flow-bin to latest (0.53.0) version but I still see the same issue for my example.

**Comment by austindonisan** [comment]
I'm guessing this is intentional. Setting 'collectionURL' to an arbitrary string is allowed by one type and disallowed by other, so an intersection type is impossible.

**Comment by gkz** [comment]
Works now: https://flow.org/try#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyMTXpyOnE2goLcegHTksRk0IPHT5y-JsYdpSkzoYm+AhEWGhCKmZ6lgC+6hAi1GEYAAQAKhRwUAjZ3pkAvJkA5FBYAG6IWDpQ5ZkAPhUwaFiUTa3lrmgA1t0VlAxEmEOVNXUNE5j0EGNgGBOWaNWB5QDcADpQuxmZAEoYAI5EcJhCAApoEEb0pZnAu5mZkDQ0GHhw0ACqhwAZZCZegyfIIXaJHZ7UjFAAionEkhudweZWeUFerk4AGUFEJDvUMMDFOReIFWC9MgBtXLkcFFEwAXWBvAgEE+WBhUN2+2KKPuj2OZwuGGut0FADJMgixBJcAL6NDdiIwHRMG9oKDMkYJfRgYrlVBdainO9Pt8-oDoSb7k52p0MJs2CB1mgmNBqNUAAxOABM3oAHE4AIwgRJAA
