### ISSUE TITLE
Type refinement doesn't work with `Array.find`

### ISSUE THREAD

**Issue by NameFILIP** [facebook/flow#4519]
```js
// @flow
type Action1 = {
  type: 'Action1', 
  payload: { 
    something: string 
  }
};

type Action2 = {
  type: 'Action2', 
  payload: { 
    somethingElse: string 
  }
};

type Action = Action1 | Action2;

const arr = ['abc', 'cde'];

function reducer(state, action: Action) {
  if (action.type === 'Action1') {
	// Doesn't work
    const result = arr.find(str => str === action.payload.something);
    return result;
  }
}

function reducer2(state, action: Action) {
  if (action.type === 'Action1') {
    const testString = action.payload.something;
	// Works
    const result = arr.find(str => str === testString);
    return result;
  }
}
```

[Try It](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIIGNkBLWAOwEZQBeUAb0VFDSwC5QByfI0stgGlHqh0AQ1RxhAE1Y0BDBgGdYAW0zIAFoRIBzVvOQAnTVtmgAvolMBuRCgzZOxEgCYqtQU0ysOBR074mRMVhJaRMFZVUNbQBRaHlPUD1DbRNzKxsPXB9SVwduUAAfLK5na0Q8Uj1QYX19VwBtNmEAIzx-NjwJTDYAXTLIAFcSbJJQfUwJAbxMfQAKPWFkTH5hEdY8kgBKNwZCSFBZ1ZKAOkzKc-YNnm26AEgQUAARWEx5EjZkUHhYfQBrQQYFRIVXG8gG0E+1Bq+mOkE0EnmBioAD5EkjzlCRsdAuIJMdFCp1EZNtY5GNVAN9KNQeDkKSzBYbINhiVyZNpvonIjFstqmtio4boI9gcjo5TnYqBdvCVrjs5ECqks9ABlAxGVxi0jY0S4-ERInaaz3MAAdR+v3kANAis+NIhmtqsPhiLqlFRSSl1GVyDVyS0JOt42QlOpr1p9LSQA)

**Comment by mroch** [comment]
https://github.com/facebook/flow/issues/282
