### ISSUE TITLE
Property cannot be accessed on any member of intersection type when using "intersection type"

### ISSUE THREAD

**Issue by hackhat** [facebook/flow#4522]
Definition:

![image](https://user-images.githubusercontent.com/11173732/28915805-36d69dca-7838-11e7-9f84-3222cf8a7b16.png)

Usage by refining the type:
![image](https://user-images.githubusercontent.com/11173732/28915895-6726bea6-7838-11e7-8e2c-f8b8a5ba7311.png)

Error:
![image](https://user-images.githubusercontent.com/11173732/28915865-585b5378-7838-11e7-92db-c338ac53ad02.png)

If I change the definition to (notice I removed the `_NotificationCommon &`):

![image](https://user-images.githubusercontent.com/11173732/28915938-8becee68-7838-11e7-969a-eb94cc32bf8f.png)

No more error.

**Comment by g3r4n** [comment]
Can you share an example ?
I try from my end and it seems to work : 
[https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeioAlgCagBcoAzsgE5kB2A5ogL6IobYBCBXKABkxUgGNYLZJhk1xoUAAtYAW0zxYjANYKWAVzUAjTIwA0pJQwMU5yBQ2btLS0BOgBDOnUax1jkysHKDc3IhSLAygxgqChCRKlNQA5JQpru7SsjLUiW6qGlq6CgBM5qBW1si29gopbADMjAAsLCmgmUoe3r7+arQpsMjKZilWYTyR0UQq6praOuY2dvKcQsYAdJE5yADcQA](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeioAlgCagBcoAzsgE5kB2A5ogL6IobYBCBXKABkxUgGNYLZJhk1xoUAAtYAW0zxYjANYKWAVzUAjTIwA0pJQwMU5yBQ2btLS0BOgBDOnUax1jkysHKDc3IhSLAygxgqChCRKlNQA5JQpru7SsjLUiW6qGlq6CgBM5qBW1si29gopbADMjAAsLCmgmUoe3r7+arQpsMjKZilWYTyR0UQq6praOuY2dvKcQsYAdJE5yADcQA)

**Comment by hackhat** [comment]
@g3r4n I can't reproduce too. There might be 2 reasons:

 - flow try is not using the exact code to validate
 - some other files affect the flow in my code base but I can't figure out which

**Comment by hackhat** [comment]
@g3r4n 
By the way the example is more like this:

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMKwLb6wB2oAvKAN6KgCWAJqAFygDOyATrcQOaIC+iFBmwBBcrgJFSAMio00WFgHIAhsoA0NAMYlkmYsmbzQpgBYFM8WBwDWAJmPEArvgBGmDltNtkz+gbIjizsXLzeptrQqqysHLAEwb5hfKCCgsJYoABCEniEJKBy1KCKmCpumjp6gcYl5pbWdk6uHl40puz+tSGc3DwRoFExcQn4xqH9NOlCZaAA4gaetNoS4gA+OUK6xOygbkyLxMurFPUMTMoMVaZlFTdDNYZM9Q34Vja2xvYaoB2dfgChmMyh4AGYOAAWYjKUCDIbRWLxAgqWDIMyeZQdGaIWiQAAUbgAdHMyGTQAADNwUgCUrx2e0ooAs7yatg0XSBRn4EmJO30hgA3AIgA

```
// @flow
type Common = {
 id : string
}

type A = Common & {
 type: 'a',
 content : {
   homework2 : number,
   student2 : string,
   classroom2 : string
 }
}

type B = Common & {
 type: 'b',
 content : {
   homework : number,
   student : string,
   classroom : string
 }
}

type Generic = A | B

const b:Generic = {
  id:'id',
  type: 'b',
  content:{
    homework : 2, 
    student : 'g3r4n' ,
    classroom: 'other'
  }
}

if(b.type === `b`){
   const { homework,student } = b.content;
}
```

**Comment by asolove** [comment]
All the examples in here seem to work for me. Can you give us some more detail about the context in which this happens? It's hard for me to guess how to make it break in the same way you saw.

**Comment by hackhat** [comment]
I cannot reproduce outside of my project. The most similar scenario is this https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMKwLb6wB2oAvKAN6KgCWAJqAFygDOyATrcQOaIC+iFBmwBBcrgJFSAMio00WFgHIAhsoA0NAMYlkmYsmbzQpgBYFM8WBwDWAJmPEArvgBGmDltNtkz+gbIjizsXLzeptrQqqysHLAEwb5hfKCCgsJYoABCEniEJKBy1KCKmCpumjp6gcYl5pbWdk6uHl40puz+tSGc3DwRoFExcQn4xqH9NOlCZaAA4gaetNoS4gA+OUK6xOygbkyLxMurFPUMTMoMVaZlFTdDNYZM9Q34Vja2xvYaoB2dfgChmMyh4AGYOAAWYjKUCDIbRWLxAgqWDIMyeZQdGaIWiQAAUbgAdHMyGTQAADNwUgCUrx2e0ooAs7yatg0XSBRn4EmJO30hgA3AIgA but it doesn't break there. Maybe needs more files, maybe something in the project affects it.

**Comment by asolove** [comment]
Is there anything more you van share? Or can you try removing references to this stuff until you discover which one causes this message? Or are you willing to screenshare with me so I can help you poke at it? Otherwise it's going to be very hard for us to track this down.

**Comment by hackhat** [comment]
Ok I will close then.
