### ISSUE TITLE
assert() won't work

### ISSUE THREAD

**Issue by enobufs** [facebook/flow#453]
I have noticed that assert() function (from node.js' stock assert module) does not seem to work:

```js
/* @flow */
var assert = require('assert');
assert('abc', true);
```
If you use `ok` property, flow can detect the type error correctly:

```js
/* @flow */
var assert = require('assert');
assert.ok('abc', true);
```

In fact, even giving a correct code like below, flow complains with message, "Could not resolve name":
```js
/* @flow */
var assert = require('assert');
assert(true); // <== this is correct
```

**Comment by samwgoldman** [comment]
It's true that `lib/node.js` does not define the `assert` module correctly. Currently flow does not recognize that the module's export is a "callable object," a.k.a. a function with properties. Instead, the export is declared to be an object with `fail`, `ok`, `equal`, etc. properties.

I am not certain whether it is currently possible to declare this kind of export with the existing syntax, so for now the only workaround is to use the `ok` form. Sorry about the inconvenience.

**Comment by samwgoldman** [comment]
@gabelevi showed me how to declare callable object signatures, so this is fixed in #445.

**Comment by enobufs** [comment]
Could you please show me how it (what @gabelve showed you) can be declared? I am having hard time writing interfaces for other (custom) modules too, where the exports being a function object, or a class - same thing. Thanks!

**Comment by samwgoldman** [comment]
@enobufs Does the code change in #445 serve as an adequate example?

**Comment by samwgoldman** [comment]
Oops! Not #445... The correct PR is #455. Sorry!

**Comment by enobufs** [comment]
Awesome!
I came across #73 last night and I am wondering if that could also be resolved with the similar way?
Thank you.

**Comment by samwgoldman** [comment]
Thanks for the pointer to that issue! Looks like the special `exports` declaration will solve that one as well. Cheers!

**Comment by samwgoldman** [comment]
@enobufs The fix for this has landed in master, and should be included in the next release. Thanks for the report!

**Comment by qm3ster** [comment]
Question: shouldn't `assert`/`assert.ok` strip maybe types to their inner types? assert can never return undefined, right?
