### ISSUE TITLE
Opaque types are casted back to super types in the imported modules

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4532]
Unfortunately to reproduce this you need two different modules there for it is impossible to include https://flow.org/try/ example, so instead posting it here:

# `./Integer.js`
```js
/* @flow */

export opaque type integer:number = number

export const floor = (n:number):integer =>
  Math.floor(n)
``` 

# `./Other.js`
```js
/* @flow */

import { type integer, floor } from "./Integer"

export const parseInteger = (input: string): ?integer => {
  const value = parseInt(input)
  return value === value ? floor(value) : null
//                         ^ number (This type is incompatible with the expected return type of opaque type `integer`)
}
```

It is really odd that `floor(value)` is casted back to `number`, I would expect code here to work given that `floor(value)` returns `integer` which is returned back from `parseInteger` without doing anything to it.

**Comment by jbrown215** [comment]
Thanks for bringing this to our attention!

It looks like the rule for converting an opaque type to its supertype comes before the rule for maybe types in the giant __flow pattern match. This means that `floor(value)`'s type was being converted to number before it even considered that it was matching against ?integer.

To fix this, I'm moving down the Opaque type rules in the pattern match and adding your test case.

**Comment by mruzekw** [comment]
Was the fix for this merged?

**Comment by jbrown215** [comment]
Yes. It's out in v53.0
