### ISSUE TITLE
Cannot use Interface as a generic type.

### ISSUE THREAD

**Issue by MrHus** [facebook/flow#4533]
The following code defines a type Page which has content of type T.
When declaring that T is an interface I get an unexpected error.

```js
// @flow

type Page<T> = {
  content: Array<T>
};

interface Serializable {
  serialize(): string 
}
  
class User implements Serializable {
  serialize() {
     return "Mike"; 
  }
}

const users: Page<User> = { 
  content: [new User(), new User()]
};

function doSerialize(page: Page<Serializable>) {
  page.content.forEach((item) => { 
    console.log(item.serialize());
  });
}

doSerialize(users);
```

It gives the following error:

`^ Serializable. This type is incompatible with Page<User>`

You would expect that the above code is fine since the User implements the interface,
and therefore matches the type of doSerialize argument, but it does not for some reason.

See it live here:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQIYDmWAPACoB8oAvKAN6KigDGsAdilhwFygCCAJwH405CogC+AbmQBLDlgGR8zHAGVFs-NFkAvfACNoOBkwDOm7XqwAKAJS8zKAfMKhJjd82j4zZ0ACqFgKgsgC2GMZhXCj+Gi5W+kYmnsFaOrq2dvSeTKACWCgArgJsoABEALKyANZY5VLuTBIeiKxsTqBFwWa8BMQkQYpUtHRNLOycPKAA2mxY8IHB9gA0oPOLQwL2ALqSMoiQRWzMKLLsoAAmsPHp1jYYRFh9TyS3iYbGFNmmoI-EADp2lMUADILABABRFQACxsNlknDC2WoVDGuQmHVgxgBcEICKRALSiSydhkzTJrWu7wytm6ijMZKAA

**Comment by TiddoLangerak** [comment]
The error is correct. Consider if flow didn't complain about this, then the following would be valid:

```javascript
class NoUser implements Serializable {
  /* snip */
}
function mutatePage(page: Page<Serializable>) {
  page.content.push(new NoUser());
}
mutatePage(users); //oh oh, we now have both `User`s and `NoUser`s in a `Page<User>`
```

You can fix this by using bounded polymorphism:

```javascript

function doSerialize<T: Serializable>(page : Page<T>) {
  /* snip */
}
```

**Comment by MrHus** [comment]
But when you say that NoUser implements Serializable doesn't that mean that it is required to implement `serialize(): string`. If not what is the point of the interface?

**Comment by TiddoLangerak** [comment]
Yes, but it breaks down when we have more properties. Consider this more complete example:

```
class User implements Serializable {
  constructor(name) { this.name = name; }
  name : string
  serialize() {
    return this.string;
  }
}

class Car implements Serializable {
  constructor(model) { this.model = model; }
  model : string
  serialize() {
    return this.model;
  }
}

function mutatePage(page: Page<Serializable>) {
  page.content.push(new Car("Ford"));
}

const userPage : Page<User> = { 
  content: [new User("MrHus"), new User("Tiddo")]
};

mutatePage(userPage);

// At this point `userPage` no longer only contains users, it also contains a car

// And here problems start to arise: we think we only have users, but in reality we also have a car which doesn't have a name property.
const names = userPage.content.map(user => user.name); 
```
