### ISSUE TITLE
How to refine union with a function type?

### ISSUE THREAD

**Issue by antoine1fr** [facebook/flow#4534]
How can I refine a value of the following `Value` type for the third case (`() => Value`)?

```
type Value =
  | number
  | string
  | () => Value;
```

For now I'm refining by being exhaustive and putting my code in the last branch, like follow, but it's not always practical:

```
if (typeof value === "number")
  ...
else if (typeof value === "string")
  ...
else
  code for () => Value values here
```

**Comment by MrHus** [comment]
How about `typeof value === "function"`

**Comment by antoine1fr** [comment]
@MrHus thanks! Isn't there any way to be more precise? For example I can have multiple function signatures in my union. I thought of using disjoint unions with sentinels, but I'm wondering if there is a way to refine using the signature instead of a sentinel.

**Comment by asolove** [comment]
There isn't a way to directly tell the argument or return types of funvtions via type checks at runtime, so I think wrapping them in objects with sentinels is a better approach.

Given that and the lack of activity on this issue, I'm going to close it. Happy to reopen if there's something more to discuss.
