### ISSUE TITLE
Higher order function "forcing" to disable strict_call_arity in my use case

### ISSUE THREAD

**Issue by dmail** [facebook/flow#4536]
I'm very new to flow and trying to get into it gradually.
It means I'm trying to benefit from its power without writing type annotation.

My issue is that the following

```javascript
// @flow

const wrap = (fn) => (...args) => fn(...args)
const wrapped = wrap(() => {})
wrapped(10)
```

Outputs the error
```
Error: test.js:5
  5: wrapped(10)
             ^^ unused function argument
    4: const wrapped = wrap(() => {})
                            ^^^^^^^^ function expects no arguments
```

Replacing `(fn)`by `(fn: Function)` seems to be what you expect from me. As I want to avoid type annotation that's not something I want to do for now.
Disabling `strict_call_arity` makes me sad, do I have an other choice ?

**Comment by TiddoLangerak** [comment]
You get this error because the `wrapped` function actually doesn't take any arguments: the `wrapped` function takes as much arguments as the function it wraps, which in this case is 0.  If instead you use `const wrapped = wrap(arg => {})` then you'll see that wrapped accepts one argument.

**Comment by dmail** [comment]
I see but how would you do in that case:

```javascript
const guard = (predicate, guardedFn) => (...args) => predicate(...args) ? guardedFn(...args) : undefined
```
```javascript
guard(
  () => false,
  (v) => v
)(10)
```
leading to:
```javascript
 8: )(10)
       ^^ unused function argument
    6:   () => false,
         ^^^^^^^^^^^ function expects no arguments
```
, or
```javascript
guard(
  (a) => a === 'foo',
  (a, b) => a + b
)
```
leading to:
```
  8: )('a', 'b')
            ^^^ unused function argument
    6:   (a) => a === 'foo',
         ^^^^^^^^^^^^^^^^^^ function expects no more than 1 argument
```

**Comment by TiddoLangerak** [comment]
I doubt if it's possible to type `guard` in such a way that it accepts a different arity for the predicate as for the guarded function. So I think you'll either need to make the signatures match, or use a `...rest` parameter. (but maybe some smarter people know some better trick)

**Comment by dmail** [comment]
Making signatures match for the sole purpose of satisfying flow would make eslint `no-unused-variables` yell at me and people reading my code would wonder why I'm having unused rest params everywhere.
Maybe that's still how it should be accomplished.

Thank you for the fast responses and help :)

**Comment by asolove** [comment]
The common idiom for arguments you have to declare but not use is to give them names starting with underscore. I think that might be the right solution here. There is a way to generate a type for this but it requires some fancy Flow declarations, whereas your stated goal is to avoid that. So I think this is the best Flow will be able to do.
