### ISSUE TITLE
Instance property type is erased, when assigned inside constructor

### ISSUE THREAD

**Issue by RomanSaveljev** [facebook/flow#4537]
I was able to reduce my problem to the following snippet (reproduces with [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAYWwDsAROASQBcwBvVMJsAEyuoAoBKALjADc4ASxb0AvqgmooAVxIZqQuCTAAPKHABOAWw5wARgCs+xcu15gA8kYCmC+o2aab1GZpUHDAbknoseAgAhB2YwAH1sE1IKGkcmMP0os1jQsIwkmOo48JY+EhltfRtNbLCbDPZsjGVcak0ZBS0OSKJo8xDQ5lwZAAdi7mzQmBcwRNbk2gBeNQ0dZq5B5moACyFcADoEsGn1LV1sBc7mfXXVM7BgYDAAUU1NLTA1sBtVPoUbUWXim0WmFbXNiczqoLlcAOrLACejwIJDgzzuDy+zgA-NkJFISDYkIEOFikKZMtwuJtsKdzpcbojNDDnq87NQPmBkT8gA)):

```js
/* @flow */

class CanDoIt {
    doIt(): void {}
}

function xform(obj: CanDoIt): Object {
    return obj;
}

class B {
    _a: CanDoIt
    _b: CanDoIt
    _c: CanDoIt
    _d: number
    _e: CanDoIt
    constructor(a: CanDoIt) {
        super()
        let b: CanDoIt = xform(a)
        this._b = xform(a)
        b.xxx // Error is expected here
        this._b.xxx // Why is no error here?
    }
}

new B(new CanDoIt())._a.xxx // Error is expected here
```

Somehow, Flow begins to see `this._b` type as more generic. Because `Object` allows any property, `CanDoIt` is compatible with it, i.e. every `CanDoIt` is an `Object`. But not every `Object` is a `CanDoIt`. Checker seems to think otherwise?

Easy workaround is to cast value returned by `xform`, like so:

```js
this._b = (xform(a): CanDoIt)
```

To me this seems like a bad choice, because I have to know `xform` returns widened type.

**Comment by RomanSaveljev** [comment]
I am very new to Flow, so this report might be a user error. Thanks for the great tool nevertheless!

**Comment by asolove** [comment]
This behavior is expected. A good way to see why is to try changing the `let b` line to not have an explicit type declaration and notice that the error goes away. In short, explicitly setting the value's type changes how it can be used and this is one of those ways.
