### ISSUE TITLE
Flow insist on checking entire home directory

### ISSUE THREAD

**Issue by nadeemja** [facebook/flow#4538]
Hi,

I have 0.52.0 running.

I ran `flow init`, which created a .flowconfig in my /app folder.

Problem is, no matter what I do, flow insists on scanning my entire home folder (~/). 

What is going on?

**Comment by mroch** [comment]
`flow ls` should tell you why it's seeing each file. does that help?

**Comment by asolove** [comment]
@nadeemja did you get this fixed or figure out why it was happening?

**Comment by nadeemja** [comment]
Hi! 

Sorry for the long silence. 

Before posting this issue I did run flow ls. It gave me a huge list of files - essentially my entire home directory and all subfolders. 

However, I couldn't see a reason stated anywhere for their inclusion. What does it look like? 

I can try again with the latest version and share my results :)

**Comment by asolove** [comment]
Is it possible any folder under `/app` have symlinks back up into your home folder? That might cause this.

**Comment by mrkev** [comment]
Closing since there has been no response in a while.
