### ISSUE TITLE
Disjoint union type for React props does not work.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#4539]
I'm pretty sure this is a [bug](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3qAAoCuWhAwrBrAHaGd4C+oSFnagA5MzI5RiRDgCe6QvWHoAzgBVQAXlAAfGolChVOQugByDVACNCWAFygAjHtABmVwBYKiAfuqGxqYWVrYOoABMPkaEACbIOACqqnaqiVjQjiZYyJwA5j58MoQAHpi4oKTQxKqqoCwAFoSkANbQyCYAysGgpaacsXWMzGwc3LwGRugqqo50M+oyRswDdgAUAJSTRqDIkKBrOA0dAHTTsGonJmaWNnbaWjoRWwE7O6RcJjS98UkpWGkMqABDojqdzmpAm9mDgmJwDlC3qAADzWBg4HBcRFI0CmEo4LQAIk6xAAboRCdikVwWO1WlpqJttAA+SqfWDQQgnOB5NZxBLJVLpaAbIo4ozAZlUjaIsU7GFwlHxUnM8ywPDXdCRZHAZVSoxFIoyRClcp4Ko1OoAcUIGNyeW6xFwcUazTaHTwfR4g3oTFY7Ew4zwr1AENmNCNy296xeiIVWHhaypyL1VKMyNdrXaXWCaZ2mtuYQZETl4p+Av+gOgROAqmAEQiwAYlfrDYAnAAGE4AK1UXEpZcleYzTSzHu6ZlAeaMBdCdgZnlLSKHOJ1qbeMoNvkQQA).

I have a component with a disjoint union as prop types. It either has `stepNumber` of `1, 3, 4` or `2`, but for some reason Flow complains about being unable to decide which case to use when I have a `ChecklistStep` with `stepNumber={2}`.

Looks like a bug, but maybe I'm missing something?

**Comment by asolove** [comment]
If I [change your code](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3qAAoCuWhAwrBrAHaGd4C+oSFnagA5MzI5RiRDgCe6QvWHoAzgBVQAXlAAfGolChVOQugByDVACNCWAFygAjHtABmVwBYKiAfuqGxqYWVrYOoABMPkaEACbIOACqqnaqiVjQjiZYyJwA5j58MoQAHpi4oKTQxKqqoCwAFoSkANbQyCYAysGgpaacsXWMzGwc3LwAPHQqGlQAVAB8BkbMA3YAFACUy0agyJCg6zgNHQB06DOnJmaWNnbaWjoR2wG7u6RcJjS98UkpWGkMqABDpjmcLrA1IE3swcExOIdoW9QBNrAwcDguEjkaBTCUcFoAESdYgAN0IhOxyK4LHarS01C22iWH04qlg0EIpzgeXWcQSyVS6WgmyKOKMwAWVM2SLFu1h8JR8VJC3MsDw13QkQmwGVUqMRSKMkQpXKeCqNTqAHFCBjcnlusRcHFGs02h08H0eIN6ExWOxMOMcBM5vMlq9QKtYhsXkiFVgEesqRM9VSjBNXa12l1gmndprbmEGRE5eKfgL-oDoETgKpgBEIsAGJX6w2AJwABlOACt2ZxKWXJXmM00sx7umZQHmjAXQnYGZ5S8ihzidam3jKDb5EEA) to upgrade to v0.53.1, it seems to be working now. In v53, you do have to change the way you declare the prop types, but as a result several weird cases like this were fixed.
