### ISSUE TITLE
Allow to disable module boundary typing

### ISSUE THREAD

**Issue by dmail** [facebook/flow#4540]
There is a rule saying I must type my module boundaries (https://flow.org/en/docs/types/#module-boundaries).
It means that when I run flow on an existing non typed project I get a bunch of errors from flow because my module boundaries are not typed.

Flow could be used on untyped JavaScript project without this rule.

Could you consider an option like `module.boundaries_force_typing = false` ?

**Comment by asolove** [comment]
What is your goal that this would help accomplish? Without module annotations, Flow is going to guess `any` for a lot of things, and therefore is unlikely to find any but the most obvious bugs.

**Comment by dmail** [comment]
Referencing an undefined property, calling a function with less/more arguments than expected are common and obvious bugs that flow excels to detect. 
The purpose is exactly to find most obvious bugs without having to type annotate an entire project.

**Comment by asolove** [comment]
Without annotations at module boundaries, flow is going to either guess wrong a lot and give false errors, or over generalize and assume things are any type, failing to catch obvious errors. Even people adding flow annotations to previously untyped code frequently end up with these problems and it would be far worse without any annotations.  Overall, I don’t think you’d find it much use for this purpose.

**Comment by vkurchatkin** [comment]
@asolove no, that is not supposed to happen. It should just work as if it was one big file.
