### ISSUE TITLE
Is there any (planned) support for pluggability at compile time?

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/flow#4548]
Hey guys, we have a codebase that we've adopted Flow on, and as we adopt Flow for new projects, one thing has come up: it's kind of awkward working around dependency injection.  I was hoping that I could implement a DI container based on using Flow type definitions that does code injection at compile time and (optionally) lookups at runtime, but from what I can tell, I can only get access to the annotation as text.  It would be helpful if I could plug into Flow's typesystem at compile time: as it is now, I think I can do simple injection based on an interface, but it would be amazing if I could plug into Flow and do more complex injections based on computed types.  For example if I have `interface A` and `interface B extends A`.  If I allow the user to specify an implementation for `interface A`, it would be nice if requested injections for `B` injected `A` instead, but I'd need to be able to look at the interface as a type, rather than just as a string.  In a perfect world, I'd be able to inject inferred types as well, but I think that might be a pipe dream.

I couldn't find anything mentioned anywhere about this, so I figured I'd ask.  If it's not planned, go ahead and close this and I'll work with what I have.  Thanks for your time, and for this awesome project!

**Comment by madbence** [comment]
`flow` is not a compiler, so it can't really do anything with your code. i'd write a babel plugin instead. `babylon` can parse type annotations, and it can rewrite your AST.
