### ISSUE TITLE
Optional argument refinement should not be invalidated

### ISSUE THREAD

**Issue by weijarz** [facebook/flow#4549]
<https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaJDtFgKYBOoAFAIYBcoAgueTQJ4A8aKAtgEYUAfABpQaAPwNu-CgEpQAb0ShQOSNQIBCALxiU0aPKUqV5UlhTkCNAHRESFKjjI9Q2wapegPaWctAAvohBQA>

```js
// @flow
function filter (a: Array<number>, n?: number) {
  if (n != null) {
    return a.filter(item => item > n)
  }
}
```
```
    4:     return a.filter(item => item > n)
                                          ^ undefined. This type cannot be compared to
    4:     return a.filter(item => item > n)
                                   ^ number
```

**Comment by madbence** [comment]
tl;dr:

```js
// @flow
function filter (a: Array<number>, n?: number) {
  if (n != null) {
    const _n = n
    return a.filter(item => item > _n)
  }
}
```

but i think this is a real error that should be fixed. if `n` was passed to the function, it's impossible to change it back to `undefined` (because it's `number`).

**Comment by jcready** [comment]
@madbence this isn't an error, but simply refinement invalidation. Function parameters aren't treated as constants (unless you turn `experimental.const_params` on in your .flowconfig) and can be changed. Flow sees there is a function call (e.g. `a.filter()`) and pesimisticly invalidates the null check on `n`.

**Comment by madbence** [comment]
@jcready i know, but in this case `n` is not `?number` but an optional argument. if the argument was passed, it's a `number` and you cannot assign `null` or `undefined` to it later.

**Comment by jcready** [comment]
@madbence unfortunately the only real difference between putting the `?` before or after the colon is whether or not it allows `null`. Passing in `undefined` as the argument is identical to not passing the argument at as far as flow is concerned. This means that `n` can still be reassigned to `undefined` inside `a.filter()` (even thought we know that isn't happening).

```js
declare function before (_?: number) : void
before()
before(1)
before(null) // error
before(undefined)

declare function after  (_ :?number) : void
after()
after(1)
after(null)
after(undefined)
```

When applied to objects and object types, the only additional difference is whether or not the key needs to exist on the object.

```js
// @flow
type Before = { _?: number };
type After  = { _ :?number };

// Property does not have to exist, can only be: number | void
({}: Before);
({ _: 1 }: Before);
({ _: null }: Before); // error
({ _: undefined }: Before);

// Property must exist, but can be: number | null | void
({}: After); // error
({ _: 1 }: After);
({ _: null }: After);
({ _: undefined }: After);
```

**Comment by jcready** [comment]
I have figured out a way to sort of work around this:

```js
// @flow
function filter (a: Array<number>, ...args: Array<number | empty>) {
  if (args[0] != null) {
    return a.filter(item => item > args[0])
  }
}

filter([1])
filter([1], 1)
filter([1], null) // error
filter([1], undefined) // error
```

Unfortunately this only really works when the last argument is the only optional one.

**Comment by lll000111** [comment]
@jcready 

> `$ReadOnlyArray`

Where do you find all this stuff, do you look at the Flow sources? Unfortunately I have zero desire to learn OCaml only to find the many undocumented features in Flow.

**Comment by jcready** [comment]
@lll000111 yeah, but in this case you don't have to be able to read OCaml since [`$ReadOnlyArray` is just a flow libdef](https://github.com/facebook/flow/blob/18a237e2aa3712ad3566c2f9fc1a530dea2666b9/lib/core.js#L199-L239).

**Comment by lll000111** [comment]
@jcready So we have a mix of `$...` things, some internal, some just normal Flow interface/class types, or are _all_ of those just classes: https://flow.org/en/docs/types/utilities/

**Comment by SamChou19815** [comment]
This now works.
