### ISSUE TITLE
Object.keys map and access with key

### ISSUE THREAD

**Issue by Soweyln** [facebook/flow#4553]
Got error for: `Object.keys(abc).map(key => abc[key]);`
Any idea why?

Link for try:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqNBXdbAJwE8BhWAEwFNNQBeUAb0VFH0wC5QByT3gBo2oAEbEevcUMQBfANzJspAA41QsFdgCWGekwAkAaRqlMAHmVrYkPLEIkK1OgD5FV9Zp16AsgEMVRhYAbQBrUx4vXSwAXR50fABbURpiBWQ0LFw-URRIrWjMf0CmZn5MXh4ARkE+aR4AJnTEAHlRACsaFGwAOnCzAAoclABKHsSAge1sGkTGF1Bh4OnZmJH5IA

**Comment by Soweyln** [comment]
I do need to do more complicated stuff using key.

**Comment by jcready** [comment]
This would work if the [core definition for `Object.keys()`](https://github.com/facebook/flow/blob/master/lib/core.js#L48) was changed to this:

```js
static keys <T> (o: { +[key: T]: any }): Array<T>;
static keys(o: any): Array<string>;
```

[Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJlgM5GgDyARgFagDeiojoRALliwJbqgDWqAnqQA8AFQB8oABSwAXHVABqANp9+ckQF05WAHb9QAXwCUcgII4cWfqLEBuBk1bsuvAUWna9J0OcvXWOBw6AOZ2iAaIiOiwOqwEsACuOiw4-ADCsGikALx0DglEcgDkBUUANA4UOMVV5eH2iCz8AA74sM2cMTmgACQA0m5CTa2wkPFJKemZqERhw20dHF0AsljNoLm0KgJy7Z2xWqA6CQC2FKg4Bg3RsSygWBTou4sraxt0JURFcgCMZaBFWpyABMV0ilCoADpVO4HugjJCTmtJBwWKgThsJHClKj0RojLYgA)

I've added this to [my PR](https://github.com/facebook/flow/pull/4527) along with better definitions for `Object.entries()` and `Object.values()`.

**Comment by asolove** [comment]
For now, the typing is actually correct as is because objects are allowed to have extra keys. There is some discussion of why changing this would currently be invalid, and of the teams effort to make this work in the future for exact object, [in this PR](https://github.com/facebook/flow/pull/4527#issuecomment-320794985).
