### ISSUE TITLE
Bug: Refinement of tuple length does not work

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4556]
[Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagPIDtsBeUAbQEM9UBdFDbAFXllGPMoBpQLrFFIBXPAGNkAS1h5QEzDgBOjWAApk-dNEwAuXAVAAfUAoCUoAN6JQoUZFDLV6gHTq8Ac2QALFoWIAmY2YsWKmqYJACMNBYAvoiRQA)

```js
// @flow
type One = [any]
type Two = [any, any]

function oneOrTwo(tuple: One | Two) {
  if (tuple.length === 2) {
    tuple[1] // results in flow error, but shouldn't
  }
}
```

**Comment by stevemolitor** [comment]
I got bit by the same bug today.

**Comment by anru** [comment]
Also [this example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA2gOSwB2WlAuqAD4WUryyUA0oNArgFsARlgBODZNCwpQAZwBceQsVBkqtepMQBLSKAAUc8gAYmJC6HadKASlABvRKHnkAjJIC+QA) should be relevant too:

```es
// @flow

type State = ['one'] | ['two', number]

let s: State = ['one']

if (s[0] === 'two') {
  s[1]
}
```

**Comment by gkz** [comment]
Works now
