### ISSUE TITLE
Issues with "typeof"?

### ISSUE THREAD

**Issue by jpommerening** [facebook/flow#4557]
Minimal example ([flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDK6AhuvgLxgDeqYYAHgFxgB2ArgLYBGuATqgF8A3Kgw58AcVzoyvMJSKkKAPlacevEaihsWAY3QBLOCzAdiAa1xSZfABRM13PmAA+YO4rLzV7Z7wBKMADmG1lqWjBeaTZeUyw8OCgGeXJKAHI-DXSwAH4PDyDyVXpgsGZ6EQFUIA)):

```js
/* @flow */
type State = {
  x: number
};

type Getter = State => number;

function makeGetter(x: number | (State => number) ): Getter {
  return typeof x === 'number' ? ( () => x ) : x;
}
```

Output:
```
9:   return typeof x === 'number' ? ( () => x ) : x;
                                            ^ function type. This type is incompatible with the expected return type of
6: type Getter = State => number;
                          ^ number
```

I read this as flow telling me that I can't return `( () => x )` because `x` might be a `Getter`, which I'm trying to check with the `typeof` operation in the ternary's condition.

I tried to use `if` instead, but [no luck](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDK6AhuvgLxgDeqYYAHgFxgB2ArgLYBGuATqgF8A3Kgw58AcVzoyvMJSKkKAPlacevEaihsWAY3QBLOCzAdiAa1xSZfABRM13PmAA+YO4rLzV7Z7wBKMADmG1lqWjBDKA8sPDgY+nlySgByPw1UoJo6Ol5pNl5TOyDyVXoROgFI3BgAZ3wc3Pz0QtMKyOrqoA).

Am I missing something?

**Comment by AugustinLF** [comment]
Flow considers that any function param can be reassigned, which means that x is not a constant. There are two ways to do what you want, or you [assign x to a constant](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDK6AhuvgLxgDeqYYAHgFxgB2ArgLYBGuATqgF8A3Kgw58AcVzoyvMJSKkKAPlacevEaihsWAY3QBLOCzAdiAa1xSZfABRM13PmAA+YO4rLzV7Z7wBKMADmG1lqWjA9EwBndDAAfXp5BkjeaTZeUyw8OChE5PIisAByPw0SsAB+Dw8g8lUk4LBmJJEBVCA), or use the `.flowconfig` param [experimental.const_params=true](https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean) which means that it will consider every function param as constant.

**Comment by jpommerening** [comment]
@AugustinLF thanks! This makes sense :)
