### ISSUE TITLE
Flow does not report arity missmatch if function type is defined with spread

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4561]
Here is an [example code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFsBDABwBUBXMmAUzAF4wAeEgLgEl86AnEgEb0WIAHwAaMANFgAFPhr12JSVHayAdFpK8A5rmUBKJjIGH2Ak6jBgomrQtp1D6UpUV1ZAbQCMkgEQAUiQYANb+ALqSsgCWACbs2FREAnzGjDKyAN7xAL6GLm7UTt5+YABMUXLxicmpvJLYJER07AS8Mdi66Zk5cY3NdPkuwMA24xM2AHpgSSl8GmAUABYxuGD4AJ5kDGtgnVhEZCT4MUIMCDH4yxvLDHQAHjsYPHFgx-xEG9sMcFBg7U6ulQRQ8pQCwTCkWiNTm9QGLTa+A6XR6cj6CKGBRB5GK9HBYCCIXCVViCThfExSJRukkMBIBGpQLR2XimLpDPww1Qo0mfP5AsFQsmMyo2DidCgnTob3kcDgtjoSB0umSdGw+Fwkkez1eYAlUBIVBg+GAvDoBHeOkGPF4uEMGiAA):

```js
/* @flow */

const mapTuple = <a:Iterable<*>, b> (tuple:a, f:(...args:a) => b):b =>
  f(...tuple)

mapTuple([1, "Jack"], (id:number) => ({id}))
mapTuple([1, 2], (id:number, name:string) => ({id, name}))
//           ^ number. This type is incompatible with the expected param type of string
mapTuple([1, "Jack"], (id:number, name:string) => ({id, name}))
mapTuple([1, "Jack"], (id:number, name:string, last:string) => ({id, name, last}))
//                                                  ^ undefined (too few arguments, expected default/rest parameters).
```

I would expect to get an error an on first call to `mapTuple` as well as given function does not have argument for second item of the tuple. It's worth noting that flow does report error if argument types don't miss-match or if function expects more arguments like in last call, although error there is pretty confusing.

**Comment by vkurchatkin** [comment]
Subtyping rules for functions haven't change, so a function that accepts less argument is a subtype of a function that accepts more arguments:

```js
declare function test((number, string) => void): void;
test(() => {}); // no error
```

**Comment by Gozala** [comment]
> Subtyping rules for functions haven't change, so a function that accepts less argument is a subtype of a function that accepts more arguments:
> 
> declare function test((number, string) => void): void;
> test(() => {}); // no error

Thanks for explanation. Is there a way to request an exact function then ? I tried `& {length: 2}` and interfaces like `interface F2 <a, b, x> { () => empty, (empty) => empty, (a, b) => x }` but neither works.

**Comment by Gozala** [comment]
Closing this in favor of #4822
