### ISSUE TITLE
Add `not<T>` type

### ISSUE THREAD

**Issue by Mtnt** [facebook/flow#4562]
Sometimes we need to annotate a function that takes all types except some one (or several), i.e. `declare isString(string): true; declare isString($Not<string>): false`

**Comment by madbence** [comment]
i'm not familiar with flow internals, but i guess it works like every other language that uses pattern matching: the first match will be used.

```js
declare function isString(s: string): true;
declare function isString(s: any): false;

(isString('foo'): true);
(isString(3): false);
```

**Comment by vkurchatkin** [comment]
@Mtnt Do you have another example in mind? This example is too contrived, i.e. `isString` should definitely be defined as `isString(mixed): boolean`.

**Comment by Mtnt** [comment]
@madbence , did you try your code? https://goo.gl/CpFu2v - it does not work

@vkurchatkin , no I haven`t. But it is not contrived example, it`a the declarations inside the `flow-typed` for `lodash`. There are several types for a negative result, but not all. For example, $ReadOnlyArray is absent there.
I know, that I can use `%checks` for these purposes, but I`m not quite sure about all checks will be caught by flow right. Besides, it`s not convenient to maintain a function and the `%checks` declaration for it.

**Comment by jcready** [comment]
I want to accept any function, but not class constructors.

**Comment by jcready** [comment]
@Mtnt for your lodash example, you can probably replace any `Array<T>` annotation in any function parameters list with `$ReadOnlyArray<T>` since I believe all arrays will flow into the read only array and I'm almost positive that lodash never manipulates the arrays directly so it should be type safe.

**Comment by vkurchatkin** [comment]
> But it is not contrived example, it`s the declarations inside the flow-typed for lodash

Well, they shouldn't be doing that. For all practical purposes `isString(mixed): boolean` is the right type.

**Comment by Mtnt** [comment]
@jcready no, you are wrong - some lodash methods mutates incoming arrays and objects. But, lets stop offtopic.

@vkurchatkin maybe they shouldn\`t, I don\`t wanna argue. But will you really be deaf for other arguments? `isString(mixed): boolean` breakes down refinement, `%checks` is hard to maintain (what about DRY?).

**Comment by vkurchatkin** [comment]
@Mtnt I see you point. You assume that if you define `isString` like this, then refinements will work. That is not true.

**Comment by vkurchatkin** [comment]
E. g. this doesn't work:

```js
declare function test(number): true;
declare function test(string): false;

function foo(x: number | string) { 
  if (test(x)) {
  	x.toFixed();
  } else {
  	x.toUpperCase();
  }
}
```

Overloads has nothing to do with refinements.

**Comment by Mtnt** [comment]
@vkurchatkin oh... I was sure... my bad, sorry. So, I don`t have any arguments more.

Seems like I have no choice and I forced to use `%checks`.
