### ISSUE TITLE
[bug] destructured arg with disjoint type and default given

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#4569]
Can be seen here https://goo.gl/AAT8c3 and confirmed being a bug [here](https://twitter.com/calebmer/status/895266347210358784). Opening this issue as a reference.

**Comment by mwalkerwells** [comment]
https://github.com/facebook/flow/issues/4575#issuecomment-322082784

**Comment by goodmind** [comment]
Duplicate of #2093
