### ISSUE TITLE
Polymorphic classes declared as "exports" do not respect type parameter

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#457]
Given the lib definitions:

```
declare module "ex1" {
  declare var exports: string;
}

declare module "ex2" {
  declare class exports {
    constructor(x: string): void;
  }
}

declare module "ex3" {
  declare class exports<T> {
    constructor(x: T): void;
  }
}

declare module "ex4" {
  declare class NotExports<T> {
    constructor(x: T): void;
  }
}
```

and the code:

```
/* @flow */

var ex1: number = require("ex1") // not ok -- errors as expected

var ex2 = require("ex2")
new ex2(1) // nto ok -- errors as expected

var ex3 = require("ex3")
var ex3inst: ex3<string> = new ex3(1) // not ok -- no error

var ex4 = require("ex4")
var ex4inst: ex4.NotExports<string> = new ex4.NotExports(1) // not ok -- errors as expected
```

Flow is only able to detect errors for examples 1, 2, and 4—not 3:

```
test2.js|12 col 39 error|  constructor call
|| Error:
test2.js|12 col 58 error|  number
|| This type is incompatible with
test2.js|12 col 29 error|  string
|| 
test2.js|3 col 10 error|  number
|| This type is incompatible with
lib/examples.js|2 col 24 error|  string
|| 
test2.js|6 col 1 error|  constructor call
|| Error:
test2.js|6 col 9 error|  number
|| This type is incompatible with
lib/examples.js|7 col 20 error|  string
|| 
```

**Comment by samwgoldman** [comment]
@jeffmo I think you're probably the most familiar with this stuff :)

**Comment by jeffmo** [comment]
It just so happens I have a (not-so-small) refactoring that I'm working on that cleans up the means by which we store exports and send them around between modules.

When I run this example with my local patches I'm able to get the proper error on your example3 scenario. I haven't sent the diff out yet (basically in the cleanup phase right now), but it should be ready for review....hopefully tomorrow? Then just a few days to get it landed

Thanks for finding such a simple repro case, btw! I'm hoping this refactoring should fix up several other little quirks with how exports work as well.

**Comment by samwgoldman** [comment]
:cool:

**Comment by jeffmo** [comment]
Aforementioned diff finally landed here: https://github.com/facebook/flow/commit/9e36f79aec83df97f98cef8cb29002cb8dd0f8b7
