### ISSUE TITLE
Internal error: merge_job exception

### ISSUE THREAD

**Issue by dounan** [facebook/flow#4572]
Getting some internal exceptions when using the following things together:
- Imported type
- Class properties
- Overloaded functions

Below is a reproduction of the bug, but it requires multiple files:
https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXxwDcQYIcpRgAxVAHgEEAaeAIQD4AKRALng-oCU8ALxtWzTAA9eAWyySQwAb3oixLANwAoUJFgIU6bHgLFS5SjQbN2XXvyGjx8KbPmLmUFcr6P12rQB6QPgAFQALBAwATwAHBBlkAGcMeAAjBCwZWJwYDEUkGBwZeChUHAxImHgZHGBkCBAtLJy8+ABvGPj4ehgAcwBfQuL4ACIAOkCk4pAAWTqGkFGAwIAqIJCASVQkrFB4aZk5hcbmEElW1MqouKbzy-guhF6+kXhUZBkMmG1VwK0tHokkl4LNogBhaDAjpaeBIVAcITtWFwlx4FIENIAKxU-TeAEZtKjTCQyBRFDQOJUsElxohUPjmNSkswcNiBETUURSRYKQjmXTUAAmJnhGms9mcgYolHBMKRJIIcJQYiPHDpBBAkGxIrxPJYEBJFH0-FvDhsnE9fp+DoDTn0oVmi24vo29p2rTSoA

![image](https://user-images.githubusercontent.com/1095431/29189535-c3f2eba8-7dcb-11e7-91a4-218482b873ca.png)

**Comment by bradennapier** [comment]
Also running into this

**Comment by leidegre** [comment]
Same here' flow isn't checking and fails on first `// @flow` comment with the following error messages

~~~
Internal error: merge_job exception: Utils_js.Key_not_found("LeaderHeap", "c:\\Users\\leidegre\\Source\\Repos\\tessin-web\\src\\shared\\actions.js")
Raised at file "map.ml", line 122, characters 16-25
Called from file ".\hack\utils\collections\myMap.ml", line 15, characters 13-23
~~~

This wasn't an issue in past versions of flow, some kind of regression I think.

**Comment by macs91** [comment]
I have the same issue too.. Someone managed to solve it?

**Comment by SleepWalker** [comment]
@macs91 did you tried to restart the flow server? In my case that was solved an issue.

**Comment by leidegre** [comment]
I just went back to an older version of flow.

**Comment by macs91** [comment]
@SleepWalker I got it fixed, but I don't know how 🤔

**Comment by Maxincredible52** [comment]
> I just went back to an older version of flow.

that fixed it for me as well
