### ISSUE TITLE
Export interface: Unexpected token

### ISSUE THREAD

**Issue by rico345100** [facebook/flow#4574]
If this is a bug, please try reproducing using https://flow.org/try/.
> https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gCSACkfkQLYDOYA3qmGANqPb5YDmAXQBcYHn0z9UAXwDcqVLgAeABzj5sYLHkKly1Wg0aygA

When I run this:

```javascript
interface IParams {
	[string]: number|string|Date
};

export interface IParams;
```

It prints this:
```bash
export interface IParams;
                             ^ Unexpected token ;
```

export IParams doesn't work either. How do I export IParams?

**Comment by TrySound** [comment]
@rico345100 Interfaces are types too
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gCSACkfkQLYDOYA3qmGANqPb5YDmAXQBcYHn0z9UAXwDcqVLgAeABzj5sYbAE8V5Nh2q0GjGbKA

**Comment by TrySound** [comment]
or
```ts
export interface IParams {
  [string]: string
};
```
