### ISSUE TITLE
Proposal: $Map type

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#4576]
We already have an `$ObjMap`, `$ObjMapi` and `$TupleMap`, but strangely enough the basic `$Map` is missing. This could look like this:

```javascript
type ArrayItem<A> = $Map<A, <V>(Array<V>) => V>;

type StringArray = Array<string>;
type StringArrayItem = ArrayItem<StringArray>;

type ReturnType<F> = $Map<F, <R>((any) => R) => R>;

type MyFunction = string => boolean;
type MyFunctionReturn = ReturnType<MyFunction>;
```

All of this is currently already possible as well, but it requires abuse of the existential operator, and I personally think the definitions look a lot more magical as well (especially for more complex cases):

```javascript
type ArrayItem<I, A: Array<I>> = I
type StringArray = Array<string>;
type StringArrayItem = ArrayItem<*, StringArray>;


type ReturnType<R, F : any => R> = R;

type MyFunction = string => boolean;
type MyFunctionReturn = ReturnType<*, MyFunction>;
```

I think having an explicit `$Map` makes this a lot more clear, especially for beginners. 

FWIW: the `$Map` type can already be implemented purely in flow through `$ObjMap` (but I still think it would be useful to have it embedded in flow):

```javascript
type $Map<V, F> = $PropertyType<$ObjMap<{ v : V }, F>, 'v'>;
```

**Comment by tempname11** [comment]
I think you're looking for `$Call`:
```js
// basic version:
type ReturnType<F> = $Call<F, any>

// for any amount of arguments: 
type ReturnType<F> = $Call<<ARGS, RET>((...ARGS) => RET) => RET, F>
```
Hope this helps!

**Comment by TiddoLangerak** [comment]
Yes, `$Call` is indeed exactly the same as my proposed `$Map`. This issue can be closed!

**Comment by lydell** [comment]
@TiddoLangerak GitHub pro-tip: The person who opened an issue also has permission to close it!
