### ISSUE TITLE
Maybe type that has been given a definite value in parent scope is still a Maybe type in child scope

### ISSUE THREAD

**Issue by nordfjord** [facebook/flow#4579]
If this is a bug, please try reproducing using https://flow.org/try/.

https://flow.org/try/#0C4TwDgpgBAogNgeTMAzlAvFA3gKClASBQHsBbCYACwEsA7AcwH4AuKAQQCcOBDEAHhTAOdegD4cAXwDcOHADMArrQDGwasVpQAJsQDKwBXLkAKLCXJURE1vCSoAlNjxRqcqMfMUaDDJloK4OEdPSx9MAG0AXRl8ZxDvegA6OWIOGG5lSg8hDFEoZQ0SOAhEuGJ6bI57exioZw4KBQ5NWggAdygABQ4yahQIY2MGooA3CAAaKAaAKwhVe3Q83HwiMi8RZNT0zOzqQIBJWgAVSghdbnIAYQ1gCAAPYFz8wuJi0vLdg+PT86ub++A1VqEnskiAA

the variable `something` is definitely an `Array<String>` at the time of the execution of the inner function. Yet flow warns that it might be void.

**Comment by jcready** [comment]
This due to refinement invalidation. The `something` variable is not declared as a constant and therefore can be reassigned in any function call. Create a `const` referring to `something` just before the forEach line and your errors will go away.

**Comment by nordfjord** [comment]
it can only be reassigned inside the doStuff closure.

In any case then this should produce an error which it doesn't

https://flow.org/try/#0C4TwDgpgBAogNgeTMAzlAvFA3gKClASBQHsBbCYACwEsA7AcwH4AuKAQQCcOBDEAHhTAOdegD4cAXwDcOHADMArrQDGwasVpQAJsQDKwBXLkAKYshSt4SVAEpseKHApQS5KiIxQzqAHSuKNAxQAISYtApwcFCMXuZ+ZAEerADaALoy+A7+7gw+csQcMNzKlMaCHBiiUMoaJE4+cMT0ZUI2NhlQDhwUChyatBAA7lAAChxk1CgQxsbddQBuEAA0UN0AVhCqNuhVuPhECTn0eQVFJS3UkQCStAAqlBC63OQAwhrAEAAewJXVtcT1RrNQSXOA3e6PZ4QN60D7fNodCQ2SRAA

**Comment by asolove** [comment]
This looks like the correct behavior to me in both examples. The first example errors as expected due to [refinement invalidation](https://flow.org/en/docs/lang/refinements/). The second example passes as expected because the inferred type of `something` in that case is always an array. Because it's not an optional, it does not need refinement and is guaranteed to never be set to null.
