### ISSUE TITLE
Object literal {} incompatible with $Exact<{}>

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4582]
```js
type T = $Exact<{}>;
const t: T = {} // flow error
```

The only work around seems to be to replace `$Exact<{}>` with `{ [any]: empty }`

```js
type E = { [any]: empty }
const e: E = {}
```

**Comment by mwalkerwells** [comment]
Or to simplify without an alias...
```js
const foo: {| bar: 'bar' |} = { bar: 'bar' }

const fooError: {||} = {}
```
```js
4: const fooError: {||} = {}
                          ^ object literal. Inexact type is incompatible with exact type
4: const fooError: {||} = {}
                   ^ exact type: object type
```

You're right, this is a surprising behavior.

**Comment by asolove** [comment]
This is a surprising bug. I was curious if I could find another way to exactly type an empty object, and came up with:

```js
type Empty = $Diff<{a: string}, {a: string}>;
const huh = (ob: Empty) => ob;
huh({}); // works, as expected
huh({a: 2}) // errors, as expected
```

So that's a sorta workaround if you need it immediately.

**Comment by mhagmajer** [comment]
+1

**Comment by hon2a** [comment]
I encountered this when trying to assign an empty object to an exact type defined with an indexer.

```javascript
type Exact = {|
  [KeyType]: ValueType
|};
```

Seems like this can be resolved by defining the type as

```javascript
type PossiblyEmptyExact = Exact | {};
```

**Comment by marcianx** [comment]
That's not a better workaround since `{}` is a superclass of _all_ structs. Consequently,
```
type Foo = {| bar: number |} | {};
const foo: Foo = {bar: "baz"};
```
is happily [accepted by the compiler](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPlARgQwE4BcUAdgK4C2WEeU6AvrWnQNwBQAxnMQM7BQBmCIvEQpUuQlABEuAF5SWrIA).

Using a non-exact type [would be more type-safe](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvARgQwE4C4oB2ArgLboTYC+A3AFADGcBAzsFAGYL7yIoY74ARFgBegmrSA).

**Comment by hon2a** [comment]
@marcianx: Thanks. Seems like I was so happy it worked, I didn't think it through.

**Comment by marcianx** [comment]
@hon2a https://github.com/facebook/flow/issues/5688 has two workarounds. I've used the `$Shape` one successfully for my workaround.
```
type Foo = $Shape<{bar: number}>;
const foo1: Foo = {bar: "baz"}; // wrong field type
const foo2: Foo = {qux: "baz"}; // property missing
```

**Comment by mhagmajer** [comment]
Guys, please beware of this issue with shapes: https://github.com/facebook/flow/issues/5884. The currently accept `null` and `undefined`.

**Comment by hon2a** [comment]
@marcianx: `$Shape` allows objects with some of the properties missing.

```javascript
type T = $Shape<{ a: number, b: number }>;
const partial: T = { a: 1 }; // no errors
```

In my case `$Shape` is of no use as I need this for maps (defined with an indexer, e.g. `type T = {| [KeyType]: ValueType |}`).

**Comment by marcianx** [comment]
@mhagmajer Thanks for pointing this out! The easy workaround for this is to ensure that this is an object via `& {}`.
```
type Foo = $Shape<{bar: number}> & {};
const foo: Foo = null; // null is incompatible
```

@hon2a Thanks for mentioning. I should have explicitly mentioned this -- indeed, this workaround is *only* for the case where you wish *all* fields to be optional (which was my case when I ran into this bug).

**Comment by AlexanderShushunov** [comment]
I think this code does not work for the same reason.  
```javascript
type T =  {|a?: number|};
const t: T = {};
```

**Comment by vkurchatkin** [comment]
Closing in favour of https://github.com/facebook/flow/issues/2977
