### ISSUE TITLE
Flow is confused when a method is overloaded with a different signature

### ISSUE THREAD

**Issue by dperetti** [facebook/flow#4585]
Consider the [following scenario](https://flow.org/try/#0FAYwNghgzlAEBC0CmsDexaxACwgOwHMkAKANwjAFckAuWKAFwCcBLQgShtIHsWATNBlgBfYKNCQYsAIKwkADwZI8fOIigp0mHPiJkK1Oo1aEANLG4AHBi2546AI27cwSfJ1g9+gzKOFA):
```js
class Base {
  change(value: string):void {
  }
}

class A extends Base {
  change(value: string, option: boolean): void {
  }
}
```
It shouldn't be an issue but Flow complains with:
```
undefined (too few arguments, expected default/rest parameters). This type is incompatible with
9:   change(value: string, option: boolean): void {
```

**Comment by mwalkerwells** [comment]
In order for ``class A`` to be a subtype of ``class B``,  any overridden methods must also also be a corresponding subtype. Fn1 is a subtype of Fn2, if the input of Fn1 is a supertype of the input of Fn2 (contravariant) and the output of Fn1 is is a subtype of the output of Fn2 (covariant).

https://github.com/facebook/flow/pull/3620

Given this type hierarchy...
``?string :> string :> 'foo'``  ...and... ``?number :> number :> 0``

...this is valid:
```js
class Base {
  change(value: string): ?number {
  }
}

class A extends Base {
  change(value: ?string): number {
    return 0
  }
}
```

**Comment by dperetti** [comment]
No, [this blog post](https://www.codeproject.com/Articles/797997/JavaScript-Does-NOT-Support-Method-Overloading-Tha) helped me to understand that this is actually because of the way javascript natively overrides (or actually doesn't) methods.
The method parameters are natively an Array, and Flow obviously sees identical functions and expects their parameters / arrays to match.
This is an edge case, but I think this is a real issue since it seems to be valid to override a method with a different signature, even though it's probably not really a good programming practice.

**Comment by mwalkerwells** [comment]
> valid to override a method with a different signature
It's only valid to override a method with a subtype of the method of the parent.

Outside of mutating the the class, can you construct an example where this is not safe?

**Comment by dperetti** [comment]
> It's only valid to override a method with a subtype of the method of the parent.
Do you mean my initial example, flow aside, is not ES2015 valid ? It compiles and works as expected.

**Comment by mwalkerwells** [comment]
Correct. Your initial example is unsafe:

```js
class Animal {
  change(value: string):void {
  }
}

class Dog extends Animal {
  change(value: string, option: boolean): void {
    // option is undefined!
  }
}

function needsAnimal(value: Animal): void {
  value.change('')
}

const mayDog = new Dog()

needsAnimal(mayDog)
```

**Comment by mwalkerwells** [comment]
But this is safe:

```js
class Animal {
  change(value: string, option: boolean):void {
  }
}

class Dog extends Animal {
  change(value: string): void {
    // all good!
  }
}

function needsAnimal(value: Animal): void {
  value.change('', true)
}

const myDog = new Dog()

needsAnimal(myDog)
```

**Comment by dperetti** [comment]
Unsafe, but valid 😉
And actually, in my project, `change()` was actually private, therefore perfectly valid to use !
Again, I think the Flow error could be more helpful, but I'm closing the issue anyway, cf #4590 !!
