### ISSUE TITLE
Exact object type property not checked inside if

### ISSUE THREAD

**Issue by juanibiapina** [facebook/flow#4592]
```javascript
/* @flow */

type Action = {| type: "A" |}

const action: Action = { type: "A" };

if (action.asdfasdfasdf === "A") {}
```

`action.asdfasdfasdf` doesn't exist. Shouldn't it error?

**Comment by juanibiapina** [comment]
Even simpler without the union:

```javascript
/* @flow */

type Action = {| type: "A" |}

function foo(action: Action): string {
  if (action.asdfasdfasdf === "A") {
    return "1";
  }
  
  return "2";
}
```

**Comment by mwalkerwells** [comment]
This is expected (at least for non-exact object types) an allows for type refining: https://flow.org/en/docs/lang/refinements/#refinement-invalidations

You could argue that this should error for exact types, although this is safe.

**Comment by juanibiapina** [comment]
Exact types cannot have extra properties, so this is conceptually wrong. In practice the if will always evaluate to false, which is very unexpected in practice. This case is most of the time a programmer error that I would expect the type system to point out.

I don't see how refinement invalidations have anything to do with it. There are no functions calls in the example.

**Comment by dperetti** [comment]
I was hit by this multiple times.
Typically:

```js
  handleKeyDown(e: SyntheticEvent) {
    if (e.keyCode === 38) {
      e.preventDefault()
    }
  }
```
No error is reported, in spite of keyCode not being part of SyntheticEvent...
This one is not a nitpicky issue. It's a real shortcoming !

**Comment by juanibiapina** [comment]
Closing this since the project has too many open issues to be useful.
