### ISSUE TITLE
Adding `// @flow` affects type inference on project with all=true in config

### ISSUE THREAD

**Issue by irnc** [facebook/flow#4595]
Having two files `fn-with-at-flow.js` and `fn-without-at-flow.js` defined as follows I expect that types inferred for function expressions would be the same given the server started as `flow server --all`

```js
// @flow
() => 42
```

```js
() => 42
```

Nevertheless, in first case `flow type-at-pos` reports `() => number`, while the second type is inferred as `() => any`. Is it intended inconsistency?

**Comment by asolove** [comment]
Hey @irnc, how are you viewing the inferred type of the second file? I assume using an editor like VSCode or Vim with a flow integration? I just tried this with v0.53.1 in VSCode, and I get an inference of `() => number` regardless of the `@flow` comment.

I'm happy to try with a different editor or flow version if that's how I could reproduce it.

**Comment by irnc** [comment]
I am looking at inferred type using `flow type-at-pos fn-without-at-flow.js 1 1`.

Given the `.flowconfig` containing `all=true` option, I installed different `flow-bin` packages using `npm i -g flow-bin@VERSION` and run aforementioned `type-at-pos` command.

```
[options]
all=true
```

Last version of Flow reporting `() => number` is 0.46.0, starting from 0.47.0 Flow always reports `() => any` (the same with 0.53.1).

Looking into release notes for 0.47.0, I found maybe relevant note:

> There are a bunch of flow commands that will quickly try to check a single file, like autocomplete, get-def, check-contents, etc. We're trying to clean up what happens when these commands are given a file with @flow, @noflow, or no pragma. v0.47.0 contains a change intended to avoid doing extra work for files with @noflow or no pragma at all. v0.48.0 should continue to address this.

https://github.com/facebook/flow/releases/tag/v0.47.0

**Comment by darichey** [comment]
This works now.
