### ISSUE TITLE
Intersection with any doesn't work

### ISSUE THREAD

**Issue by AtnNn** [facebook/flow#4598]
The following code passes type checking with no errors.

```
var c: any & void = undefined;
c.foo;
```

I expected it to report the same error as this code, "Property cannot be accessed on possibly undefined value".

```
var d: void = undefined;
d.foo;
```

[Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAhgFz7oCeoAZKAN4A+okssR6ArgLYBGApgE6g0BfUAF5qDJqACMAgNyoMOUByKhVa2vUbN23PoJFitU2YjwA6Dnh4zQIUJgAWsFtAAmoXj1g9EHC1bk1ILVEADcrUBQiPFIKUFDYAEt3URZ0Vy5IRPQuVzlwvlcVYITkgzSMrJy85BQzcRs7R2c3Dx4vH1d6xjlEO3RYbC5QbAc8XFHEzFBXWC5pz28CVAMqcSJpOSA)

**Comment by vkurchatkin** [comment]
This works the way it is supposed to. You can access `.foo` on `any`, so it is OK to access it on intersection of `any`.
