### ISSUE TITLE
Opaque Types aren't working as child elements in React/JSX

### ISSUE THREAD

**Issue by johnhaley81** [facebook/flow#4599]
> If this is a bug, please try reproducing using https://flow.org/try/.

I don't know how I can show this off correctly in the REPL since it's using opaque types.

Let's say you're creating a menu system and you only want a `Menu` to be able to accept `MenuItems` and not just any old `React.Element<*>`. You'd make something like:

### Menu.jsx
```javascript
// @flow

import { type MenuItemType } from './MenuItem';

export default ({ children } : { children: MenuItemType[] }) => (
  <ul>
    {children}
  </ul>
);
```

### MenuItem.jsx
```javascript
// @flow

export opaque type MenuItemType: React.Element<*> = React.Element<*>

export default (props: any): MenuItemType => (
  <li {...props} />
);
```

### MakeMenu.jsx
```javascript
// @flow

import Menu from './Menu';
import MenuItem from './MenuItem';

export const goodMakeMenu = () => (
  <Menu>
    <MenuItem>Option 1</MenuItem>
  </Menu>
);

// ************************************
// * This should error but it doesn't *
// ************************************
export const badMakeMenu = () => (
  <Menu>
    <li>Option 1</li>
  </Menu>
);
```

Opaque types are amazing and I would love to be able to use them to create a component API that's expressive. I mean you still _can_ but you can break that guarantee without knowing it.

**Comment by jbrown215** [comment]
Hey!

This looks like a really awesome use case for opaque types. I'll dig into this a bit today and see what's going on

**Comment by jbrown215** [comment]
Ok, after some experimentation with the version `0.53.0`, I think the new way flow models react does a better job here than opaque types ever could.

Here's the code I have:
```
import * as React from 'react';

class MenuItemClass extends React.Component<{}> {}
class NonMenuItem extends React.Component<{}> {}

type Props = {
  children: React.ChildrenArray<React.Element<typeof MenuItemClass>>
};

class Menu extends React.Component<Props> {}

<Menu>
  <MenuItemClass />
  <MenuItemClass />
  <NonMenuItem />
</Menu>;
```

Flow throws an error at `<NonMenuItem />` :D!! 

thanks @calebmer for these awesome changes!

**Comment by johnhaley81** [comment]
@jbrown215 would that also work for stateless functional components?

**Comment by jbrown215** [comment]
Hmm, I'm not quite sure. Maybe opaque types would come in handy there. Back to investigating :D

**Comment by johnhaley81** [comment]
Hah, thanks man :)

**Comment by jbrown215** [comment]
Ok, I think I have the behavior you're looking for w/ stateless functional components + opaque types + `0.53.0`'s typing for react children

## Menu.js
```js
import * as React from 'react';
import {MenuItem} from './MenuItem';

const Menu = ( { children }: 
    { children: React.ChildrenArray<React.Element<typeof MenuItem>> }) => (
  <ul>
    {children}
  </ul>
)

export const goodMakeMenu = () => (
  <Menu>
    <MenuItem />
  </Menu>
);

// ************************************
// *  This should error and it does   *
// ************************************
export const badMakeMenu = () => (
  <Menu>
    <li />
  </Menu>
);
```

## MenuItem.js
```js
//@flow

import * as React from 'react';

opaque type MenuItemType: React.Node = React.Node;

export const MenuItem = (props: any): MenuItemType => (
  <li {...props} />
)
```

**Comment by johnhaley81** [comment]
That is awesome! Is 0.53 pretty stable? Or is there an issue to track the release of it?

**Comment by jbrown215** [comment]
I think it was just released: https://twitter.com/flowtype/status/897833240559460352
I used `brew install flow` to when I was working on these examples :)
