### ISSUE TITLE
Flow type-checking fails depending on style of constructor

### ISSUE THREAD

**Issue by gilbert** [facebook/flow#460]
The following code type checks correctly:

``` javascript
function controller () {
  var ctrl = {
    mode: 'show',
    updateMode: function (newMode) { ctrl.mode = newMode }
  }
  return ctrl
}

function view (ctrl) {
  ctrl.updateMode('edit')
  ctrl.idontexist()
}

view(controller(), { testContent: 'hello' }) // type error, yay!
```

But if you use this style, no type errors are thrown:

``` javascript
/* @flow */

function controller () {
  var ctrl = {}
  ctrl.mode = 'show'
  ctrl.updateMode = function (newMode) { ctrl.mode = newMode }
  return ctrl
}

function view (ctrl) {
  ctrl.updateMode('edit')
  ctrl.idontexist()
}

view(controller(), { testContent: 'hello' }) // <-- no type error?
```

**Comment by samwgoldman** [comment]
A much simpler test case. Note that this behavior is unfortunate, but afaict flow makes this tradeoff intentionally to cope with the fact that object types can dynamically extend. I feel like flow could be more sophisticated in how it navigates this tradeoff, but I'm not experienced enough with this particular problem to propose any solution.

```javascript
/* @flow */
var o = {}
o.idontxist() // no error
```

**Comment by bhosmer** [comment]
Thanks both. Sam you're right that the *order* in which props are added is not tracked, so we may miss get-before-set errors. But we should be detecting gets on props that are never set. Will investigate.

**Comment by bhosmer** [comment]
Should probably note that I'm talking about unsealed objects here. Sealed objects don't have the wait-and-see behavior I described above.

**Comment by gkz** [comment]
Fixed: https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c
