### ISSUE TITLE
Extra null in array destructuring

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#4605]
```js
var [...rest, last] = [1, 2, 3]
```

is being parsed as

```js
[RestElement, null, Identifier]
```

in Flow parser 0.51.0.

This makes prettier re-print is as

```js
var [...rest, , last] = [1, 2, 3];
```

https://github.com/prettier/prettier/issues/2626

cc @mroch

**Comment by mroch** [comment]
[...rest, anything] is a syntax error :) the null is clowny, though.

recently fixed in 2ae7d2316629ba9f8492ceaacd5544068a3ac6f7 and 1eb5b9c33dc717a90e6f577a2ba377aadb89c304
