### ISSUE TITLE
Any class instance seems to be able to be used as any object-as-map type

### ISSUE THREAD

**Issue by drifkin** [facebook/flow#4607]
(I tried searching for similar issues, and was unable to find any. I'm not sure if this behavior is known, but it was very unexpected to me, so I'm opening this issue.)

The following gives no error, even though we're passing a class instance to something that expects to take a particular object-as-map type:

```javascript
/* @flow */

class SomeClass {
  numField: number
  someFunc(): void {}
}

function takesAMap(map: {[name: string]: number}) {
}

function takesSomeClass(theInstance: SomeClass) {
  takesAMap(theInstance);
}
```
<https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAZTgFsBTAYR3zAG9UwwA7AVxIDEBLMmAEwC5mbAEZkATgzC5SZdiyYYAFAEpBANzidedAL6o9qKPIwAXTnCZgT2ANZlcAQQCy2AA6KSbwbQDaTbOSCuCZinEwA5gC6gqwkomI6ynT66EYKZhZWtvbE5FR4uIomABZkAJJMwdgKZIK5lNS4SfSM1naOLu4l5ZXWNcoA3PpAA>

As far as I can tell, any class properties and fields can exist in `SomeClass`, and there will still be no error.

On the other hand, when passing a non-class object type to something expecting an object-as-map type, the object type seems to matter.

The following has an error (:

```javascript
/* @flow */

declare type SomeObj = {|
   a: string,
   b: number
|};

class SomeClass {
}

function takesAMap(map: {[name: string]: number}) {
}

function takesSomeObj(obj: SomeObj) {
  takesAMap(obj);
}
```
<https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSBlOAWywHkAjAKzAF4wBvAH1Rgh+AFxgAzqUIBLAHYBzADSChLMbICu9FlkKo+AXwDc6PPnHiwdRgGECF3qgPooG2TlLS4ssvgDWWOIAggCy+JQAFPThYjwA2rL4jGKSMgoAuupaOoQGAJSOzqiu7p7evgHi1szsEXDsYtWsbAU8KqT+gaHhdex5JgZAA>

The error:

```
4:    a: string,
         ^ string. This type is incompatible with the expected param type of
11: function takesAMap(map: {[name: string]: number}) {
                                             ^ number
11: function takesAMap(map: {[name: string]: number}) {
                                             ^ number. This type is incompatible with the expected param type of
4:    a: string,
         ^ string
```

On the other hand, if the object type only has fields that match the expected property type, there is no error:

```javascript
/* @flow */

declare type SomeObj = {|
   b: number
|};

class SomeClass {
}

function takesAMap(map: {[name: string]: number}) {
}

function takesSomeObj(obj: SomeObj) {
  takesAMap(obj);
}
```
<https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSBlOAWywHkAjAKzAF4wBvAH1RghLAFxgAdgFd6LLIVR8AvgG50efAGcNYOowDCBLb1SL0USeJykAlnHFl8AaywaAggFl8lABT0vYngBtcXxGMQ1SQmtxAHMAXTEpGTlFAEpjU1RzSxs7B2cNXWZ2bzh2MSLWNnSeQXyXDy9S9lTVRSA>

**Comment by lll000111** [comment]
> I tried searching for similar issues, and was unable to find any. 

https://github.com/facebook/flow/issues/4499

**Comment by asolove** [comment]
I'm going to close this and envourage discussion over in #4499.
