### ISSUE TITLE
Lint: sketchy-null-string: partially wrong error message?

### ISSUE THREAD

**Issue by stouf** [facebook/flow#4608]
The following code

```js
'use strict';

// @flow

function sayHi(info: { name?: string }) {
  return `Hi ${info.name ? info.name : ''}!`;
}

sayHi({});
sayHi({ name: 'foo' });
```

with the following configuration

```
[ignore]

[include]

[libs]

[lints]
all=warn

[options]
include_warnings=true
```

gives me the following warning with Flow v0.52.0:

```
» flow
Warning: index.js:6
  6:   return `Hi ${info.name ? info.name : ''}!`;
                    ^^^^^^^^^ sketchy-null-string: Sketchy null check on string value. Perhaps you meant to check for null instead of for existence?
    6:   return `Hi ${info.name ? info.name : ''}!`;
                      ^^^^^^^^^ Potentially null/undefined value.
    6:   return `Hi ${info.name ? info.name : ''}!`;
                      ^^^^^^^^^ Potentially "" value.


Found 1 warning
```

Am I missing something? Flow seems to be confusing maybe type and optional property here doesn't it?

**Comment by TrySound** [comment]
@stouf The message is quite descriptive. `Potentially "" value` means that you should check empty string which can be valid value.

**Comment by stouf** [comment]
@TrySound Thanks for replying :)
The message is indeed descriptive, but seems wrong to me.

> sketchy-null-string: Sketchy null check on string value. Perhaps you meant to check for null instead of for existence?

Given that `name` is an optional property on `info` and not a maybe type, I think I must check for the existence of that property first.

> Potentially null/undefined value.

As written above, `name` is not a maybe type, so it should not `null` nor `undefined`.

> Potentially "" value.

Yep, that's correct, but I don't think this should be a warning.
It could be that Flow thinks `name` is maybe type and therefore, since the expression `info.name` would be falsy if the property `name` doesn't exist, is an empty string, is `null` or is `undefined`, Flow is suggesting us to deal with all these cases independently.

Perhaps I'm missing something here?

**Comment by stouf** [comment]
According to the [documentation](https://flow.org/en/docs/linting/rule-reference/#toc-sketchy-null), it seems that this is just the expected behavior since empty strings are evaluated as a falsy values.

> Triggers when you do an existence check on a value that can be either null/undefined or falsey.

At first, I didn't get why Flow would show warnings for possible empty values but it's actually easy to imagine situations where it would be useful. For example,

```js
function sayHi(info: { name?: string }) {
  if (!info.name) {
    throw new Error('Please provide a name');
  }
  if (info.name.length === 0) {
    // This case will always be caught by the if previous statement
    throw new Error('Empty name not allowed');
  }
  return `Hi ${info.name}!`;
}
```


The message about `info.name` potentially being `null` or `undefined` still seems wrong to me though..?
(I'm renaming the issue to re-center the discussion on this).
