### ISSUE TITLE
Syntax highlighting appears to be breaking on VSCode

### ISSUE THREAD

**Issue by tkshnwesper** [facebook/flow#4612]
I was not sure whether I should post this here or in vscode's issues, but I just thought I will post here to start with.

![](https://image.prntscr.com/image/mE-fvZTPQK6CLdfGdDmycg.png)

I observed that it breaks when I annotate like this:
```js
state = {
  uploadProgress: (null: *),
  imgUrl: (null: string | null),
}
```

**Comment by TrySound** [comment]
@tkshnwesper It's the problem of vscode plugin not flow itself.
