### ISSUE TITLE
Fails to understand `oneOf` React prop-types

### ISSUE THREAD

**Issue by Tomekmularczyk** [facebook/flow#4614]
I have a component with prop-types:

```
class OptionPane extends React.Component {
  static defaultProps = {};

  render() {
    return (
        ...
    );
  }
}

OptionPane.propTypes = {
  option: Types.oneOfType([Types.string, Types.bool]),
};

OptionPane.defaultProps = {
  option: false,
};

export default OptionPane;

```

Then later when I use this component I get error:
![zrzut ekranu 2017-08-16 o 10 34 06](https://user-images.githubusercontent.com/12544704/29354611-73cb27ba-826e-11e7-98e2-309b90909de3.png)

The same happens when I declare props like this: 

```
type Props = {
  option: string | boolean,
}

class OptionPane extends React.Component {
  static defaultProps = {
    option: false,
  };

  props: Props;

```

**Comment by asolove** [comment]
I tried to [recreate the bottom code example that's just flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwIYGMAgA7AFxxUMKMEkBzOAB84AIwgQANjkkAaOgF8GuXWnQB5MRMntkktlgAeMLJIAm6bHhgAdADCJJDOkjAAPJyiqAB8AkJyMMjiuHBeWATIAK66MDHccHyCwsKi4lKy2bqoWMbCJvRmdJG2lQ5ObBX2PABEMAAWSspMfQD0cUA). I get the error you describe in v0.52, but it works correctly in v0.53.1.

If you need this to work and your codebase is stuck in v0.52, you can also provide explicit information about the types for the component's default props and props, [like this](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwIYGMAgA7AFxxUMKMEkBzOAB84AIwgQANjkkAaOgF8GuXWnQB5MRMntkktlgAeMLJIAm6bHhgAdADCJJDOkjAAPPyi4lKy8ooqatp6JoYcXKgZzKwQBHAArt5YBEpYXgB8AkJyMMjiuHBepciFujCcorw1wsKx9rIEyLqoWMbCJvRmdJG2cQ5ObANSPABEMAAWSspMawD0lUA) (Note that you need to switch Try Flow to using v0.52 for that to not error.)

The jump from 52->53 forces you to be explicit about the types of the props, but as a result fixes a bunch of bugs or confusing behavior that happened when Flow inferred the prop and default prop types before.
