### ISSUE TITLE
Union of object literals : a case where refinement is not very smart

### ISSUE THREAD

**Issue by dperetti** [facebook/flow#4616]
[Try Flow](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCSNgFsAqzUC8AUHHAD5wDeFSKAXHAOSYgyPkC+J5VN+DjAM6Yw7Ml1IVqCfkwDGEACbBGAGgQQA1sAB2DYVACWOgOaduAbiJEAZgFcdcmIYg64xwcFgZsACkUAhjABDD64+ACUVERctg5OLm4AFgE6igA2wABywADuYb4wAixsPEIiYvJKKlGU3IY2cIVwBK1MJYy13O46nt6YWL6UMvQIcBwR3FwcQA).
```js
export type ItemType =
  | {| type: 'text' |}
  | {| type: 'step' |}
  | {| type: 'code', token: string |}
  ;

function insertItem(data: ItemType) {
}

function handleNewItem(t: 'text' | 'step' | 'code') {
  if (t === 'text') {
   insertItem({ type: t })
  }
}
```

```
12:    insertItem({ type: t })
                  ^ object literal. Could not decide which case to select
7: function insertItem(data: ItemType) {
                             ^ union type
```

**Comment by dperetti** [comment]
[Another example](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCSNgFsAqzUC8AUHHAD5wDeFA1gJYB2AJgFxwDkmIM75AviXJVajVhwDOmMLzIDSAbiJEAxhAaS49ZnAIcuPFWo1MAjGwzY8KHVU2i4fOAHoncAO7Qa4pXQBmcAAotJh0CXU5QHgBKKkFVdXgmACZzTFx8G0o7bUcXOCYIYHEGTndPIgEiIA):
```js
export type ItemType =
  | {| kind: 'text' |}
  | {| kind: 'step' |}
  ;

const kind = 'text'
const d1: ItemType = { kind } // works

if (kind === 'text') {
  const d2: ItemType = { kind } // doesn't work
}
```
Weird !

**Comment by vkurchatkin** [comment]
I agree that this is a bug, but something like this most likely has been reported before

**Comment by SEAPUNK** [comment]
Also happens without exact types.

```js
// @flow

type A = { a: 'A' };

type B = { a: 'B' };

type AB = A | B;

function asdf(a: string): AB {
  switch (a) {
    case 'A':
      return {
        a,
      };
  }
  throw new Error('nope');
}
```

**Comment by asolove** [comment]
This is very similar to #4683, #4685, #4669. We've had a ton of reports on behavior like this with unions of objects that have the same property but different string literals. Might be a good topic for docs of what does(n't) work and why.

**Comment by SamChou19815** [comment]
this now works
