### ISSUE TITLE
disjoint unions forget type in switch case on anonymous function

### ISSUE THREAD

**Issue by andykais** [facebook/flow#4623]
[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5gCGAXGAHYCuAtgEZ4BOANGNvnQHJCAsAF9MuAgCFSFMKzpM2nHnzyCpI8RPxEAxhgCWcerOIAfMFPR6TAZwzUOHKllkBtAIxcATFwDMALroUIz0BsamUGAAFFQRJnSECfQAlBSoYGB2CIYYegAWsfFGJgB0aunkmVlgelR2BEICNDW18hx4VADWANxtdQ1Nmq3tWcDAYIbhcM54BgNZVM6uZcxUODEAblQwpAB8GWO1O3sk59QpZayLYqm3yy5YaxvbuwdHx1PRcVdqpBcBJp0qcAWQSpFrrdRPdjhM6rNOgYAIS3Wz0OxwGB4MrwADmv1K9GusLGrE6PX67QAJngoFRGDAMKMyRS+jVxKIgA)

This is a simplified example of a reducer, flow does not understand that the type of `action` has been chosen outside the filter function, but works as expected on the `console.log` line

tested on both `0.52` and `0.53`

**Comment by madbence** [comment]
refinements are invalidated in callbacks (as flow cannot assume, that when you call your callback, `action.type` will be still `B`).

you can save the refined value inside the switch case, and use that value inside `.map`.

```js
type A = { a: number, type: 'A' }
type B = { b: number, type: 'B' }

type Action = A | B

const array = [1,2,3]

function f (action: Action) {
  switch (action.type) {
    case 'A':
      break;
    case 'B':
      const a: B = action;
      array.map(val => {
        val === a.b
      });
      break;
    default:
      break;
  }
}
```

**Comment by andykais** [comment]
good tip, that solves my problem. This still feels like an issue that can be addressed in the future however 

(Ill remove the [bug] from title)
