### ISSUE TITLE
hanging on specific file change on v0.53

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#4624]
I have a specific line that I can change in my project to get flow to hang 100% of the time (it jumps to 100% CPU and does nothing, I've let it sit for 30 min).  I'd be happy to share any info I can, but the last thing the logs show are just:

```
[2017-08-17 00:33:47] Merging
[2017-08-17 00:33:47] sending (2 errors) and (warnings from 0 files) to 0 subscribed clients (of 0 total)
```

Is there a way to turn on more verbose logging so that I can put up a proper issue without sharing my entire project?  I've tried trimming it down to a smaller use case but can't figure out what's actually causing it, it seems to need >70% of the file as well as required modules to repro.

**Comment by weijarz** [comment]
I have encountered 100% disk read/writes makes OS freeze after upgraded to 0.53.

**Comment by zyklus** [comment]
For me it's not an OS freeze, flow just jumps to 100% CPU on a single thread
