### ISSUE TITLE
$Diff is buggy when used with type spread

### ISSUE THREAD

**Issue by Awpteamoose** [facebook/flow#4638]
```javascript
type A = {
  a1: number,
  a2: number
};

type B = {
  b1: boolean,
  b2: boolean,
};

type Mix<T1, T2> = {
  ...$Exact<T1>,
  ...$Exact<T2>,
};

type AB = Mix<A, B>;

const doSmthAB = (ab: AB) => {
  console.log(ab.a1); // No errors!
};

const doSmthA = (a: $Diff<AB, B>) => {
  console.log(a.a1); // property `a1`. Property cannot be accessed on `AB`
};
```
[flow.org/try](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUCGBGAXFAdgK4C2ARhAE4A0amATHkWZSgL4DcKKokUAQgmS1SuKKQD24gDYQM+GulIMxkmXJocuPaAFkAlgA8APABUsVKCboA+QanQA6JwBIAogYwBjYKazWFUE4Obh7epjYanNzg0DACiPrGMBZ81lGe4vgAzsBQACbiAMrEwAAWcYIAFBikeHEAlAi29lAZ2dIQDlLiAObVpA7Y9exQAPSjUABy4lCUFOIUWQCEbOmZOflFJeVVGHjOACJ6AGbHRnEp1o3wzbRtWR1dvdWDWMNjE2DzkBSgUAAG2H+DigAAVvpQ-p45PhxLlyJhPJ4IFkshA8lBMgC4v9VkA)

**Comment by SamChou19815** [comment]
The issue is fixed a long time ago
