### ISSUE TITLE
React.Children.map errs with read-only type message

### ISSUE THREAD

**Issue by danrot** [facebook/flow#4648]
I was very happy about hearing about the new feature for typing react children, but it doesn't seem to work in combination with `React.Children.map`, or at least I don't know how to get it working. I have prepared two examples to illustrate that:

[The first one](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcGO+RBAntlJgA3gGEAFuhgATFgDsAgnjzk+AGjABRGKUyk5BAL5ha9JiyoEOqVP0FgJU6QEYACnWwBnMAF4RqMDAAN3IYAFdSZwAuME8CPHQ5AHNUQ05UShhyT29HGTBSAA8CfWlvMksAOlF6XDl9AgAePJd3OC8APgAC4VSbOyFXcnkCNq9ff0DKSRl5GJb5JRU+Ru1dBsaBuCgHGekOjtT0zOzvIZGC4tLy1gJq2rh6g0bzhrHPDsmweWlSPAAKACUX0CFWo1T28kqmHI2H+BEknkq2A8SOmTnkGn+6JkwJ8n16gSJRMoj08cB0lXgSWxe2RqMBnGJhkZATAhlSQA) shows that flow complains as soon as I am accessing a property of the untyped `child` parameter in the callback of `React.Children.map`. I am not sure how that should work out...

I have also tried to type the parameter, as shown in the [second example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcGO+RBAntlJgA3gGEAFuhgATFgDsAgnjzk+AGjABRGKUyk5BAL5ha9JiyoEOqVP0FgJU6QEYACnWwBnMAF4RqMDAAN3IYAFdSZwAuME8CPHQ5AHNUQ05UShhyT29HGTBSAA8CfWlvMksAOlF6XDl9AgAePJd3OC8APgAC4VSbOyFXcnkCNq9ff0DKSRl5GJb5JRU+Ru1dBsaBuCgHGekOjtT0zOzvIZGC4tLy1gJq2rh6g0bzhrHPDsmweWlSPAAKACUX0CFWo1T28kqmHI2H+BEknkq2A8SOmTnkGn+6JkMTWemeWx2LQ6wJ8n16gSpVMoj08cB0lXgSWxe2RqMBnGphk5ATAhlSQA) I get an even stranger error including some `$NonMaybeType`, which I absolutely don't understand (should just not be `null`, as far as I see...). But in an ideal world that shouldn't be necessary at all, because flow can interfere the type, right?

Any help is appreciated 😃

**Comment by calebmer** [comment]
Thanks for reporting! This is a bug. We’ll have a fix out in the next version of Flow 😊
