### ISSUE TITLE
Literal object with dynamic keys does not type check on deeper levels / import issues

### ISSUE THREAD

**Issue by comatory** [facebook/flow#4649]
Hello,
I would use the editor on Flow website but actually my issue isn't reproducible there. There are actually two things that does not seem to work for me:

- Typechecking on literal object with dynamic keys on second level
- Type defined in separate file is not picked up, unless I include constants in the same file, that I'm trying to typecheck.

Let me elaborate more on this so you understand more. Please see my code [on my Github](https://github.com/comatory/flow-error-example) so I can explain this in more detail.

You can run flow with script `yarn flow`. I use flow v. `0.51.0`

I have three files, all of them are typechecked with Flow:

1. `keymap.js` - contains literal object. The keys on the object are dynamic, the key name is taken from constant object in `keymap-constants.js`. So it uses `SELECTORS` and `ACTIONS` objects to name the keys. I import these constants / enums in this file so I can use them.

2. `keymap-constants.js` contains previously mentioned constants and enum objects. I export them so they can be used in `keymap.js` and `keymap.types.js`.

3. `keymap.types.js` is where type definitions are stored. These are then imported into `keymap.js` file. I also import enum objects. This is the place where I define `Keymap` type which is used in `keymap.js`.

There are two branches in the repo. The repo `master` is my current setup and also contains notes where I expect typechecking to be be working.

So it seems that the type `Keymap` actually works, as it checks, whether the key name is included in `SELECTORS` enum object. You can check this by uncommenting line no. 13. and type check error will be brought up.

The thing that does not seem  to work at all, is typechecking on deeper level of the object. It seems like type `KeymapItem` which is part of type `Keymap` is ignored. Line 33 is where I would expect for error to be thrown because name `'something'` of that key does not exist in `ACTIONS` enum object.

What is interesting however, is that the name gets checked when I don't use literal key (like `'something'`) but I try to use invalid key on `ACTIONS` enum object, you can see this when you uncomment line 40.

The other branch named `working-example` shows another strange behaviour. I copied the constants from `keymap-constants.js` to `keymap.js` file and suddenly `KeymaptItem` type is triggered. You can see that I forgot to add to `KeymapItem` type definition, that value can also be array of strings. However it still does not solve the issue with key names.

I'm pretty sure that this should work since I tried recreating it in online editor:

https://flow.org/try/#0MYewdgzgLgBA4gUQHIIEoEEAyMC8MDkiKGm+AUKJLAMoCqAQrgXfeReNDOk-uuZZ0Z58rMuyoxqCTAgDCAFQDyqakwDeZGPGRosAGk2SGBgL5iBNBqrwat6A1vqmxWslACeABwCmkgK4ARgCSUN4AtuqGANoAJADS3u4QADwePiAAZkb01AB8ALoAXDBgfmEB3gBOzm5eviHhkVqxCUmpdZmS0nJKKgXF1IENYTUWMACGxcNNMFFSMgrK1AB0RLqYRTBqc1bL6JsAzGZm4pwBU6ERNtHzPUurOiSbavgAHvjF+O74x2JAA

**Comment by Zenwolf** [comment]
I am also having a similar problem. I was going to put this up as a new bug, but I believe this is the same issue as reported here. My details are below.

Summary
=======
I believe that I found a bug where certain code is typed correctly when it is in the same file, but it is typed incorrectly when some of the code is imported from a different file, even though both files are Flow typed.

Environment
===========

Flow version: 0.57.3


Working Case
============

The code below correctly reports a Flow error as expected, and can be verified at https://flow.org/try/

Code
----
```js
// @flow

type UIStateType = 'active' | 'inactive';

const State = {
  ACTIVE: 'active',
  INACTIVE: 'inactive'
};

interface StateInteractions {
  handleError(error: Error): void,
  handleUserActivity(): void
}

type UIStates = {
  [UIStateType]: StateInteractions
};

const states: UIStates = {
  [State.ACTIVE]: {} // Correct Flow error -- missing interface methods
};
```

Error
-----
```text
19:   [State.ACTIVE]: {}                      ^ object literal. This type is incompatible with
15:   [UIStateType]: StateInteractions                     ^ StateInteractions
Property `handleError` is incompatible:
15:   [UIStateType]: StateInteractions                     ^ property `handleError` of StateInteractions. Property not found in
19:   [State.ACTIVE]: {}                      ^ object literal
19:   [State.ACTIVE]: {}                      ^ object literal. This type is incompatible with
15:   [UIStateType]: StateInteractions                     ^ StateInteractions
Property `handleUserActivity` is incompatible:
15:   [UIStateType]: StateInteractions                     ^ property `handleUserActivity` of StateInteractions. Property not found in
19:   [State.ACTIVE]: {}                      ^ object literal
```


Bug Case
========

When the `State` enum is put into a separate file, and required by another, Flow seems to lose track of what values are on the `State` enum and Flow reports no error.

file1.js
------
```js
// @flow

export type UIStateType = 'active' | 'inactive';

const State: {[string]: UIStateType} = {
  ACTIVE: 'active',
  INACTIVE: 'inactive'
};

module.exports = State;
```

file2.js
------
```js
// @flow

import type {UIStateType} from './file1.js';

const State = require('./file1.js');

interface StateInteractions {
  handleError(error: Error): void,
  handleUserActivity(): void
}

type UIStates = {
  [UIStateType]: StateInteractions
};

const states: UIStates = {
  [State.ACTIVE]: {} // no Flow error! Missing interface methods!
};
```

**Comment by lxgreen** [comment]
I have exact same issue: if a constant string imported from another file used as a map key, then the map value is not typechecked!

**Comment by Zenwolf** [comment]
I re-tested this in Flow version `0.73.0`, and my two-file example above now correctly throws an error:

```text
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ file2.js:17:19

Cannot assign object literal to states because:
 • property handleError is missing in object literal [1] but exists in StateInteractions [2] in property active.
 • property handleUserActivity is missing in object literal [1] but exists in StateInteractions [2] in property
   active.

 [2] 13│   [UIStateType]: StateInteractions
     14│ };
     15│
     16│ const states: UIStates = {
 [1] 17│   [State.ACTIVE]: {} // no Flow error! Missing interface methods!
     18│ };
     19│
     20│
```
