### ISSUE TITLE
React.StatelessFunctionalComponent<Props> type arguments errors

### ISSUE THREAD

**Issue by apalm** [facebook/flow#4650]
Using the new `React.StatelessFunctionalComponent<Props>` type, I tried to declare a component like this:

```js
type FooProps = {| size?: 1 | 2 | 3 |};
const Foo: React.StatelessFunctionalComponent<FooProps> = props => /* component definition */
```
but this resulted in the following errors:

```
9: const Foo: React.StatelessFunctionalComponent<FooProps> = props =>
              ^ type application of StatelessFunctionalComponent. Too few type arguments. Expected at least 2
[LIB] static/v0.53.1/flowlib/react.js:204:   declare export type StatelessFunctionalComponent<P, C> =
                                                                                              ^ See type parameters of definition here
9: const Foo: React.StatelessFunctionalComponent<FooProps> = props =>
              ^ type application of polymorphic type: type `React$StatelessFunctionalComponent`. Too many type arguments. Expected at most 1
[LIB] static/v0.53.1/flowlib/react.js:124: declare type React$StatelessFunctionalComponent<Props> = {
                                                                                           ^ See type parameters of definition here
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAETY32sDcytsAO1L5aoALyVOuAHS0OxXFQCi0KmioDcvRLgCeGKqABisWAAUmGchIDeAH0ShQpFAC8qAfgBcoAIyg7UAAmANAAZkQ7AF9tfiF8E1gfajoZAGVcBSpVUlIjAFcBehRBYmgAYWYsAQ1cAB5Ei1grAD5xUAxLaxbHUFoAClYAExQAN1YAGlAbXqdhXVUfGacV0AALKhQAczXcH07m0mkXdwDA3wnZlfgUIdw1-a7jt0M7c6uo3qiASm0qAA8sHhQEMqJBiPloAlTLwgA

Is declaring components like this not supported, or am I missing something?

**Comment by asolove** [comment]
I think the bug is that StatelessFuntionalComponent is first [defined with just one polymorphic type variable for Props](https://github.com/facebook/flow/blob/5cf9c2243946d36fb26de91a1fcd204d54d69351/lib/react.js#L124) but then [exported with two type variables](https://github.com/facebook/flow/blob/5cf9c2243946d36fb26de91a1fcd204d54d69351/lib/react.js#L204), including one for context type.

**Comment by silvenon** [comment]
I'm also slightly confused by the fact that their [example for stateless components](https://flow.org/en/docs/react/components/#toc-stateless-functional-components) doesn't use the `StatelessFunctionalComponent` type.
