### ISSUE TITLE
Bad error location from RHS of binary expr in conditional

### ISSUE THREAD

**Issue by mroch** [facebook/flow#4651]
```js
/* @flow */
if (x && y) {
}
```

reports a spurious error pointing at the whole if statement, in addition to the two legitimate errors pointing at `x` and `y`:

```
2: if (x && y) {
   ^ identifier `y`. Could not resolve name
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLKYAUAPMAMkLAE8BKMAb1QF91hgwAjOAFwAswCBDAOwAmZMDwBOAUzABXPhIDOcGADdxAgDQspbMJ3ESA5HJFg5ABymiMcKUb2i4o1IxGstYAAal3YU3Ax82fwBzEW1dMAQORUksEzYeNnEAW3EAoA

**Comment by asolove-stripe** [comment]
Just a note that this is still present in v0.55.

**Comment by SamChou19815** [comment]
Now we have better names.
