### ISSUE TITLE
Types that related to React seems to behave any type

### ISSUE THREAD

**Issue by kogai** [facebook/flow#4656]
In type definition of third party libraries with `flow-typed`, using a type that related to `React` seems to behave `any` type.
It happens after `0.53.x`

I don't know how to reproduce on [playground](https://flow.org/try/), so I indicated code below.
More detailed code can be checked in [my repository](https://github.com/kogai/flow-sandbox)

```javascript
// flow-typed/npm/sample_v0.x.x.js
import * as React from 'react';
declare module "sample" {
  declare export type T = React.ComponentType<*>;
  declare export type U = number;
}
```

```javascript
// mycode.js
import type {T, U} from 'sample';

const t: T = ""; // Expect error here.
const u: U = ""; // Expect error here too, and actualy error occured correctory.
const v: React.ComponentType<*> = ""; // And error occured correctory here too.
```

**Comment by SamChou19815** [comment]
Existential type was dead
