### ISSUE TITLE
How to use flow and jsx without importing react in 0.53?

### ISSUE THREAD

**Issue by zerkalica** [facebook/flow#4657]
Flowtype now react-only? In 0.53 above example generates error: "identifier `React`. Could not resolve name"

```js
// import React from 'react'

function A(
  props: {a: string;}
) {
  return <div>{props.a}</div>
}

<A a='123' />
```

[try](https://flow.org/try/#0PTAEEsFsAcHsCcAuoBKBTAhgY2QM3rJKAOTyY7EBQluArgHY7iz2gCCAFJaKNAdAGcAXKADeGEQMTxw9AOYBuAL6UAlGO6gyiWvFYAeACbgAbgD5RfWIIB0GJfuDHzlFZX1tQGALzEAjABMAMzEoMBmlEA)

How to use power of flowtype in jsx pure components without importing react?

**Comment by samwgoldman** [comment]
Flow has support for the `@jsx` pragma, but it doesn't work on TryFlow.

See https://github.com/facebook/flow/blob/master/newtests/jsx_pragma/test.js

**Comment by zerkalica** [comment]
Ok, this workaround works:

```js
//@flow
// @jsx Bar

function Bar<Props>(component: ((props: Props, ...x: any[]) => any) | string, props: Props, ...childs: any[]) {}

function A(
  props: {a: string;}
) {
  return <div>{props.a}</div>
}

<A a="1" />
```

But how to do same without placing ``` @jsx ``` in each file and without importing Bar?

**Comment by vkurchatkin** [comment]
@zerkalica Why do you need it? It won't work without importing `React` anyway.

**Comment by zerkalica** [comment]
@vkurchatkin 

1. Autoimporting react [babel-plugin-react-require](https://www.npmjs.com/package/babel-plugin-react-require)
2. Simple bridge to react-like jsx-compatible frameworks, like [ivi](https://github.com/marvinhagemeister/babel-plugin-ivi-jsx), [vue-jsx](https://github.com/vuejs/babel-plugin-transform-vue-jsx)
3. Framework lockin
4. My experiments with react-free statefull flow-compatible component

[Simple counter](https://github.com/zerkalica/rdi-examples/blob/master/src/examples/counter.js):

```js
class Counter {
    @mem value = 0
}

export function CounterView(
    _: {},
    {counter}: {
        counter: Counter
    }
) {
    return <div>
        <div>
            Count: {counter.value}
        </div>
        <button onClick={() => { counter.value++ }}>Add</button>
        <button onClick={() => { counter.value = ('error': any) }}>Gen error</button>
    </div>
}
CounterView.deps = [{counter: Counter}]
```

**Comment by vkurchatkin** [comment]
I guess the easiest way would be do declare global `React`.

**Comment by zerkalica** [comment]
Do you now how to do that?

I try:
```
// flow-typed/react-stub.js

// @flow
import R from 'react'
declare var React: R
```


```
// test.js
//@flow

function A(
  props: {a: string;}
) {
  return <div>{props.a}</div>
}

<A a={1} />
```

flow does not check errors:

$flow check
Found 0 errors

**Comment by vkurchatkin** [comment]
Try this: `declare var React: $Exports<'react'>;`

**Comment by zerkalica** [comment]
It works, thank you.

**Comment by nucleartide** [comment]
@vkurchatkin's solution works great, but are there any docs for the @jsx pragma? @samwgoldman

**Comment by sobolevn** [comment]
I was using this trick to work with `flow` and `vue`.
https://github.com/wemake-services/wemake-vue-template/blob/c203e751f9d9ed9cfc411a4cdf56d35fe8a2dda7/template/client/components/ActionBar.vue#L3

Since `0.76` it is not working any more. https://github.com/wemake-services/wemake-vue-template/pull/645

Are there any ideas how to fix it now?

**Comment by mrkev** [comment]
@sobolevn, @nucleartide I recommend opening a new issue

**Comment by sobolevn** [comment]
Still no solution https://github.com/facebook/flow/issues/6626

**Comment by CarmelK** [comment]
I found this clean way to work for me, in your .flowconfig file add `react.runtime=automatic` under `[options]`.
