### ISSUE TITLE
`flow suggest` doesn't work well with arrow functions

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#466]
If you run `flow suggest` on this code:

``` js
/* @flow */
var subtract = (a, b) => a - b
```

It will output:

``` diff
--- old
+++ new
@@ -1,3 +1,3 @@
 /* @flow */

-var subtract = (a, b) => a - b
+var subtract = (a, b) => : numbera - b
```

The suggested code won't work even if I add a whitespace after `: number`.

**Comment by impinball** [comment]
Basically, `flow suggest` is emitting invalid code. It should, AFAICT, emit "new" as something like one of these:

```js
var subtract = (a: number, b: number) => a - b
var subtract: (number, number) => number = (a, b) => a - b
```

These are just educated guesses, as I don't use that feature of Flow.

**Comment by kevgathuku** [comment]
I'm also experiencing a similar problem with arrow functions:
Running flow suggest on this code:
```javascript
/* @flow */
var f = (x: number) => x * 2;
```
gives me the following suggestion:
```diff
--- old
+++ new
@@ -1,5 +1,5 @@
 /* @flow */
-var f = (x: number) => x * 2;
+var f: (x: number) => number = (x: number) => x * 2: number;
```
which is not the correct format.
A funny thing I noticed is that running `flow suggest` on the code it has suggested, i.e.
 ```var f: (x: number) => number = (x: number) => x * 2: number;```
gives the following suggestion:
```diff
--- old
+++ new
@@ -1,5 +1,5 @@
 /* @flow */
-var f: (x: number) => number = (x: number) => x * 2: number;
+var f: (x: number) => number = (x: number) => x * 2: number: number;
```
It just seems to be adding one more `number;` each time it is run

**Comment by panagosg7** [comment]
The issue with arrow functions has been resolved.

I tested `flow suggest` on:
```js
var f = (x: number) => x * 2;

var subtract = (a, b) => a - b

module.exports = {
  delete: (next) => {
    next();
  }
};
```
and got:
```js
var f = ((x: number): number => x * 2);

var subtract = ((a, b): number => a - b);

module.exports = {
  delete: (next: any): void => {
    next();
  },
};
```
