### ISSUE TITLE
clarify if using Flow is under Facebook’s BSD+Patents License

### ISSUE THREAD

**Issue by gdi2290** [facebook/flow#4661]
due to recent news, I think it would help a lot of developers if it was clear that using the Flow or using the language is under Facebook’s BSD+Patents License or not. For example, jsx is under another repo with a Creative Commons Attribution 4.0 International License so it's clear that anyone can use the jsx language.

**Comment by asolove** [comment]
The answer is that yes, the patent license is included. This is indicated in the Readme and by the inclusion of the [Patents license](https://github.com/facebook/flow/blob/master/PATENTS) in the root of the repo.
