### ISSUE TITLE
Odd error in official example for $ObjMap<T, F>

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4663]
The last example for [`$ObjMap<T, F>`](https://flow.org/en/docs/types/utilities/#toc-objmap):

```js
declare function props<A, O: { [key: string]: A }>(promises: O): Promise<$ObjMap<O, typeof $await>>;

const promises = { a: Promise.resolve(42) };
props(promises).then(o => {
  (o.a: 42); // Ok
  // $ExpectError
  (o.a: 43); // Error, flow knows it's 42
});
```

Reports this error ([Try Flow](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcYcCBnAHgEEAaeAeQC54BveAbQGsQBPJ0jGFlQBzALpNK8AL4A+ABREcAWyykQpJnQCUTAArEVa8gBI6AIwBWAWSgFydWhm4EQORPGNQA7lCwYZMgDcAFDBYHj8hAaq6vAAvCzwUHrRagB0cKQ4EABuIHIALABMWtIhimQKqepaaRgAFiCocjjxMizB8PAtacnwxVqB8AD0w-QcnSNjxgCiAB4umDMwxDCTPX0FAMyDU-DLq7SIEDhe8Byop6TwfgDk18XBUoNAA)):

```
3: const promises = { a: Promise.resolve(42) };
                         ^ Promise. This type is incompatible with
[LIB] static/v0.53.1/flowlib/core.js:682: declare function $await<T>(p: Promise<T> | T): T;
                                                                        ^ union: type application of class `Promise` | type parameter `T` of object map
```

If however you change `Promise.resolve(42)` to `(async(n)=>n)(42)` the error changes to something that actually makes sense ([Try Flow](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwAcYcCBnAHgEEAaeAeQC54BveAbQGsQBPJ0jGFlQBzALpNK8AL4A+ABREcAWyykQpJnQCUTAArEVa8gBI6AIwBWAWSgFydWhm4EQORPGNQA7lCwYZMgDcAFDBYHj8hAaq6vAAvCzwUExyUKTc6HKoWnEy2XIALABMWtIhimQK0WqkWgB0GAAWIKhyOPEyLMHw8G11yfDFWoHwAPSj9BzdYxPGAKIAHi6YczDEMNN9AwUAzMMz8KvrtIgQOF7wHKjnpPB+AOS3xcFSw0A)):

```
7:   (o.a: 43); // Error, flow knows it's 42
      ^ number. Expected number literal `43`, got `42` instead
7:   (o.a: 43); // Error, flow knows it's 42
           ^ number literal `43`
```

Is there a reason the error changes when both `Promise.resolve(42)` and `(async(n)=>n)(42)` should be equivalent?

**Comment by asolove** [comment]
Ooh, interesting. I think this just boils down to the order in which the type inferencing happens.

For example, if I use the `async` version but add a type to `promises`, I get the same, slightly cryptic message that you originally got with the `Promise.resolve` version.

```js
declare function props<A, O: { [key: string]: A }>(promises: O): Promise<$ObjMap<O, typeof $await>>;

const promises: {[key:string] : Promise<42>} = { a: (async(n)=>n)(42) };
props(promises).then(o => {
  (o.a: 43); // Error, flow knows it's 42
});
```

(/cc @calebmer this could use a label for our collection of confusing error message locations)

**Comment by jcready** [comment]
Appears to have been fixed.

**Comment by goldhand** [comment]
I think this might be related, the other example with [$ObjMap](https://flow.org/en/docs/types/utilities/#toc-objmap) has errors too.

```js
type ExtractReturnType = <V>(() => V) => V

function run<A, O: {[key: string]: () => A}>(o: O): $ObjMap<O, ExtractReturnType> {
  return Object.keys(o).reduce((acc, k) => Object.assign(acc, { [k]: o[k]() }), {});
}

const o = {
  a: () => true,
  b: () => 'foo'
};

(run(o).a: boolean); // Ok
(run(o).b: string);  // Ok
```

Reports this error ([Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCiAHugE4CGAxugEq7oCupAdgCo74C8YAPAGoA+ABRCAlGE4CwfcZOmpUUBs2oBLOMzCllPAIIAaMAHkAXGADeAbQDWuTGYDOZVcwDmAXTNiJU3QF9hODMjUTMAEiMAIwArAFlybB4jQ2IyKlp6JjYOKXNUMC1MlmMY3GoAOltMByE4UXLSXAATBkpcESpKQ2tZKSjosvRy8gcHVVdmIU7DczAbTzA4ee8-URnVgG5UPwVKDSdFiQt8sHIvXrAyBlx9E8jznzAAcig4OCftrdQhbUm64bMkTeMFw5GYog2YGAwGM1m+v1q9XuYCcpBcrghBWhsKAA))

```
9:   a: () => true,
              ^ Cannot return `true` because string [1] is incompatible with boolean [2].
References:
10:   b: () => 'foo'               ^ [1]: string
9:   a: () => true,
              ^ [2]: boolean
10:   b: () => 'foo'               ^ Cannot return `'foo'` because boolean [1] is incompatible with string [2].
References:
9:   a: () => true,
              ^ [1]: boolean
10:   b: () => 'foo'               ^ [2]: string
```
*Also note that you will need to select a version other than `v0.65.0` as it seems to not be working in the browser*
