### ISSUE TITLE
flow-upgrade replaces all end-of-file LF (and only those) with CRLF

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4666]
In my (already clean for Flow 0.53) code the command replaced ALL end-of-file newlines (and only those!) that in my project are Unix-style LF with CRLF.

flow-upgrade should not change existing newline style.

<br>
<hr>

PS: It also made this change, adding an additional set of parentheses around a logical expression that already has them:

```diff
@@ -195,10 +195,9 @@ const convertBasicType = function (rule: RecipeRuleObj, values: Array<any>): str
             if (
                 (
                     // Using an explicit check to satisfy Flow, the variable is "boolean | undefined".
-                    rule.hashLink === true ||
+                    (rule.hashLink === true ||
                     rule.idLink === true ||
-                    rule.clobLink === true ||
-                    rule.blobLink === true
+                    rule.clobLink === true || rule.blobLink === true)
                 ) &&
                 !CRYPTO_HASH_RE.test(v)
             ) {
```

**Comment by SamChou19815** [comment]
We try the best to maintain current style, but we never try to be perfect. If you really care, use prettier.
