### ISSUE TITLE
Provide a way to type functions declarations similar to functions expressions

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#4668]
Hi!

Now I have a very convenient way to add types to functions expressions:

```
type MyFuncType = number => number;
const myFunc: MyFuncType = (a) = a * a;
```

It would be nice if I can reuse the same type with function declaration.
Something like this:

```
function myFunc: MyFuncType(a) {
  return a * a;
}
```

**Comment by tirli** [comment]
@apsavin+1, but for now, you can use
```
const myFunc: MyFuncType = function myFunc(a) {
  return a * a;
}
```

**Comment by apsavin** [comment]
@tirli Thanks for the tip! But your example is about function expression anyway (it can help in many cases though).
