### ISSUE TITLE
Object union with string literal property is incorrectly typed as string, but union of string literals as property is typed correctly.

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4669]
```js
type A = { t: 'a' }
type B = { t: 'b' }
declare var test: A | B
test.t
```

Running `type-at-pos index.js 4 6` for the above returns **`string`** ([Try Flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeVgC4oHICGmoF8AoUSKAIQWVQ0wCM8iATCAYwBtsAnaANy9QgBndLCgAfcsSHAAdMCA))

```js
type A  = { t: 'a' }
type BC = { t: 'b' | 'c' }
declare var test: A | BC
test.t
```

Running `type-at-pos index.js 4 6` for the above returns **`string | 'b' | 'c'`** ([Try Flow](https://flow.org/try/#0C4TwDgpgBAglUF4oG8rAFxQOQEMtQF8AoUSKAIQGFEU1MsAjfAH2wGN9iATCNgGxwAnaADchaCAGcMsKKyokpwAHTAgA))

```js
type AA = { t: 'a' | 'a' }
type BC = { t: 'b' | 'c' }
declare var test: AA | BC
test.t
```

Running `type-at-pos index.js 4 6` for the above returns **`'a' | 'b' | 'c'`** ([Try Flow](https://flow.org/try/#0C4TwDgpgBAgjUF4oG8rAFxQOQEMtQB9s8oBfAKFEigCEBhRFNTLAI3yKwGN8KATCFwA2OAE7QAbmLQQAzhljwi9SnOAA6YEA))

Sorry for the title gore, but it's a little difficult to summarize the situation. It seems like my best option for proper type hints is to make every string literal property a union of the same string literal, otherwise I end up with `string` as the type every time.

**Comment by asolove** [comment]
What version of flow are you running? On my computer, using Flow v0.53, on the first example, I get:

```
string
string-disjunction.js:4:1,4:6

See the following locations:
string-disjunction.js:4:1-6:
string literal `b`
string-disjunction.js:4:1-6:
string literal `a`
```

And the VSCode editor integration parses that to show a type hint of `(property) t: "a" | "b"`.

Are you on a different version of Flow? Do you not see the extra output from `type-at-pos`?

**Comment by jcready** [comment]
This is in Atom/Nuclide as well as flow.org/try (hence why I linked to them, just move the cursor in between the `.` and the `t`)

**Comment by asolove** [comment]
Oh, wow, TIL, I had never noticed the type hints at the bottom of Try Flow.

In any event, I suspect this means there is an oversight in Try Flow, and possibly other editor integrations, that doesn't read the follow-up information passed back from flow. Let me see if I can at least track down where this happens for Try Flow to verify that guess.

**Comment by jcready** [comment]
@asolove I'm not sure why it is up to the consumer of type-at-pos to extract extra information beyond the first line to get the most specific type. The type-at-pos utility should be outputting the most specific type it can in its top-line output, and in this case it knows that the type is a union of two string literals ('a' and 'b'), it should output `'a' | 'b'`, not `string`.

**Comment by asolove** [comment]
I mean yeah, I dunno. I would guess this is the general solution for unions because there are more complicated possibilities, so it needs to be able to tell you the file location and type of all the alternatives in case they are classes or interfaces or something else more complicated.

**Comment by asolove** [comment]
Ok, still working on the editor bit. But there clearly is something larger here with flow's internals about unions of objects with unions of values.

For example:

```js

There is also a bug on the flip side of this where it allows things it shouldn't allow for union properties that should be specific values:

```js
export type Apple = { type: 'apple' };
export type Oranges = { type: 'oranges' };

export type Fruit = Apple | Oranges;

let x: $PropertyType<Fruit, "type"> = "stuff"; // This type checks, but shouldn't
```

But if the `type` properties are already enums, then Flow checks it correctly!

```js
export type Apple = { type: 'apple' | 'Apple' };
export type Oranges = { type: 'oranges' | 'orange' };

export type Fruit = Apple | Oranges;

let x: $PropertyType<Fruit, "type"> = "stuff"; // type error, as it should be
```

**Comment by jcready** [comment]
> But there clearly is something larger here with flow's internals about unions of objects with unions of values.

Based on your examples I'd say the problem is with unions of objects with literal values, things seem to work as expected when you have unions of objects with unions of values.

**Comment by jcready** [comment]
Appears to have been fixed.
