### ISSUE TITLE
How to link externally to the parser module?

### ISSUE THREAD

**Issue by dorafmon** [facebook/flow#467]
Hi, I have some project that needs to use a javascript parser written in OCaml and I am just wondering if I can link to the flow parser externally? How should I do it? Thanks.

**Comment by samwgoldman** [comment]
Does anything in the parser directory help? https://github.com/facebook/flow/tree/master/src/parser

It looks like you should be able to compile the parser as a library and link that into your project.

**Comment by samwgoldman** [comment]
If you're still having trouble with this, please re-open. Thanks!
