### ISSUE TITLE
[Feature] $Arguments<func>

### ISSUE THREAD

**Issue by lkoba** [facebook/flow#4672]
Sometimes it's necessary to accept the same arguments as another function but provide a different return type.

Having an $Arguments<> utility would help avoid boilerplate.

Given:
```
function funcOne(string, number, string): string {
    let result = "";
    // magic ...
    return result;
}

type FuncOneType = typeof funcOne;
```

Right now, the way to define a function type with the same arguments but void return type requires defining a function that will never be used:
```
const funcOneButReturnsVoid = (...args) => {funcOne(...args)};
type FuncOneTypeReturnsVoid = typeof funcOneButReturnsVoid;
```

With $Arguments it would be:
```
type FuncOneTypeReturnsVoid = $Arguments<funcOne> => void;
```

There's probably some way to achieve this, but I went through a lot of resources and flow's source code before coming here. If there is, I apologize in advance.

**Comment by asolove** [comment]
Hey there! Can you give some more context on the situation where you'd want to do this? In my experience, when two functions share an input type, it's usually because that type is meaningful elsewhere in my program, so I give it a name and refer to that name in both function declarations. I'm trying to think of why I'd want one function to have the same argument types as another but not give them names, and I can't think of one, but I'd love to hear more about your use case.

Also, I was curious about your second block of code, and after poking at it, I don't think it does what you describe. When I use that code and ask flow what type `FuncOneTypeReturnsVoid` is, it says: `(...args: any[]) => void`. Flow hasn't made up a new type with the same argument types, it's just thrown up its hands and said "it can be anything". 

I don't think there is currently any way to represent the idea of "the types of the arguments to a certain function". But I'd love to hear more about why you need that and maybe we can come up with a creative solution.

**Comment by lkoba** [comment]
I'm using the container/component pattern with React and Redux.

Let's say we have a Component that expects a function that opens a Product's page. The properties it expects are defined like this:
```
type Props = {
   openProductPage: (productId: string) => void,
}
```

There's usually an Action creation function that most of the time matches the arguments exactly, but it returns an Action instead. The Container dispatches this Action to be processed by reductors, sagas, etc. The signature would be `openProductPage(productId: string) => Action`. You can see that it's almost the same, but the return type changes. This is not an issue because the call is wrapped by the Container `(productId) => dispatch(openProductPage(productId))` when sent to the Component. The signature matches and everyone is happy.

Now. The issue here is that replicating the function arguments on each Props where it's expected is a maintenance problem. If you change an argument in an action creator, you have fix dispatch wrappers, then the Props and then the Component. We automated the dispatch wrapping to simplify one step and we would love to be able to simplify the Component properties definition doing something like:
```
type Props = {
   openProductPage: $Arguments<actions.openProductPage> => void,
}
```

This way, if we modify the action creation function arguments, we can skip directly to fixing the code.

The alternative for my use case is to encapsulate all arguments for each action creator in an object and define a type for each one, that way the Component could expect something like: 
```
type Props = {
  openProductPage: (OpenProductOptions) => void
}
```

Still, $Arguments would be less traumatic so I wanted to make sure that it wasn't available in other form.

**Comment by lttb** [comment]
@lkoba maybe this declaration could help?

https://goo.gl/FVzFVc

```js
declare function arguments<A>((A) => any): [A]
declare function arguments<A, B>((A, B) => any): [A, B]
declare function arguments<A, B, C>((A, B, C) => any): [A, B, C]

type Arguments<T> = $Call<typeof arguments, T>

type Fn1 = (?string) => void
type Fn2 = (string, number) => void

let a

;((a = [1]): Arguments<Fn1>) // error
;((a = [undefined]): Arguments<Fn1>)
;((a = ['x']): Arguments<Fn1>)
;((a = ['a', 1]): Arguments<Fn2>)
```

**Comment by evansiroky** [comment]
@lttb's example is very helpful, but doesn't work for functions with 0 arguments.  I tried to make it do that in [this try flow](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtX1gHNkBbEVDAZwB4BBAPgApGBKeAXnoNQE8WAueAG0AugChQkWAhTpseAjGJkKNBs1ptO3PoKG1xk6HCRpMufEVLkqdADTwAQk0a0HjrVyi8Bwt08NwYxkzeUsla1V7JwcAYRd-RzjPHV99dzjAqRNZcwUrFVtEuIcAEQSM+FiylO9dP0rq+FLxMQweAAcEWgjCmgAVLnZ4ABJYqAgIanaunERFZRtKB0GxMVyw03QAeVQQRihBSgwYLFRCBwAjQVRSS5AYBzAjk7PCX2PT8-gAbzF4AHwCAgDDwOCUZAQUHDABEMIA3P9AQB6ZHwEhQQhYMDwAB0+KRALgGGQMHw4MhGERAF9CfA2p0EAAxMy7EAAJRBpNQ-UZHFG40m1AAogAPE5QTCcklk3ldBwzEBzLZgNn0BldeAsnZ7OUcrlkygANRwWGA-MY+NxREogh6iyiiuVuTVKW1qr20u5esRYjAeGO8FFgndbL1XsNJrNFqgV1qa1FjAA5KKkw4AIwOFNJli4iGXT6MdNsVHwHAAazEiezGYzJbRDxgOBgdLEpZOPHgGBw8AA7jAoB14Gd4B0myQsJQQK2NhYwQbUGz4KwbncHr86USF-B02JaetQnOoMBgEvGLcSKuSPcYL4LzeN4DAcTufAL-AANQ7vdrRXwMUSlKC56vy1Dsg46iWviNp2jAA48HQ9ApOyyEasyZgAOoDh0XTAAAkqgAAK46TiA1BMkMy5WjB8D2pEtgUSkxE4BOU7UGMExTABA5ATKPKMg4FH0L6-qoIGPAhph2G4QRzGsWRTrzC+ZJqhaKR7L28ByaRzDgjgEAAG4gCkPx6YZ+zKYueysCw1IsH6AaggAXpJ6BYYOMlESRbGKQQJ6qcMjAGRM6kgJp2lTrpICUPpRkmWZRkHP51nBRALC2fZYg8KwuIYAAFuQ56kBwXDvl+xbwKWFZZTl+WFe+2gXnmyAFicRbpZVDZwc2YhOYwABMuZ1agRUkCVb7FeV9ZlpWfWDblBUjQ1pWkM1rUwO102Ns2QA), but I'm not sure if it fully works.

Also, see this example for wrapping in a promise:

```javascript
// try to wrap in promise
    
function returnOne (): number {
      return 1
}

function addOne (num: number): number {
      return num + 1
}

type ExtractReturnType = <R, A>((...args: Array<A>) => R) => R
type FuncWrappedInPromise<F> = (...args: Arguments<F>) => Promise<$Call<ExtractReturnType, F>>;

const y: FuncWrappedInPromise<typeof returnOne> = () => new Promise((resolve) => {resolve(returnOne())})
const z: FuncWrappedInPromise<typeof addOne> = (val) => new Promise((resolve) => {resolve(addOne(val))})

y().then(num => num + 1) // should be ok, but is not :(
z(2).then(num => num + 1) // ok
z(2).then(num => num.substr(1)) // error
```

**Comment by lttb** [comment]
Hi @evansiroky!

Excuse me for that example, I just missed the declaration without the arguments there.
This is the correct implementation:

```js
declare function arguments<A>(() => any): []
declare function arguments<A>((A) => any): [A]
declare function arguments<A, B>((A, B) => any): [A, B]
declare function arguments<A, B, C>((A, B, C) => any): [A, B, C]
declare function arguments<A, B, C>((A, B, C, D) => any): [A, B, C, D]
declare function arguments<A, B, C>((A, B, C, D, E) => any): [A, B, C, D, E]
```
[Try here](https://flow.org/try/#0PTAEBcCcE8Ie1Ad0gQwA6gJYDtRsnALaYDOApgFCjWgUAmZAxgDYqRmgBmArto+Jji42Ac26Ey2cCQA8AQQB8ACiUBKUAF4FoFNmiqAXKADaAXXpNW7Lr36DhkMRKmzFKueq069hk3PMMLGwcPHwCQjqO4pLS8gA0oABCykpyCYme2rr6RsZpSQGWwTZh9pFOMa7pCQDCKfmJtZneOX7VoDXmFODQaBxyUc6xACraGqAAJDUozMwyPX1wnOXRLgmjFBShdhHs4NyQ2ADy2BxqRtjiAEZkkKAA3lQ01HsHuACMFAC+m9vhwnQ6CczpdCBdrrdfKCbndHs8XmR9odQKDQABqUCfH7dXocACiAA8oCh+AAlRFvYa4zSgGSkhJuJQAOhZohIRgGqGg8gUzVJfJxfVAADFbAB1VBoPp0ACS2AACgRiOQZMKxqBmazHOzQAMKi5VbzNNpFURSGQZFMZnNCcSyRTDlS+gk1QoANybRhCEjgUDQIyivgS9DSuWm5UWhZkJagV6HYHqtTGlFkRCgcPmlTsEhwZgANzIzXu2dzBaUceOpzUqi+qgoXuwPtAAC8A+LJaGFUrzfNcTGUICEzSlHmZs1TmmM+Qs2Qc-nC8ni7PS2QlAOgVXR8xVDW6xRoGomeAABaSJSoryojHvdQgUAkY9wbjMOigG6gOAAawSV24vtIKJwL6BhKBQzZKAATKoR6ntg57iMmV6YreYBfmBkHQSeZ4XtooJMiQ3BXD6kBKDeKGgLcBCQEAA)

You might also find this type useful: https://github.com/lttb/flown/blob/master/src/Arguments/index.js
It's a bit more complex, but the base idea is the same

**Comment by mike1808** [comment]
@lttb I came up to the same solution however it doesn't work for optional arguments in the function. 

[Try here](https://flow.org/try/#0PTAEBcCcE8Ie1Ad0gQwA6gJYDtRsnALaYDOApgFCjWgUAmZAxgDYqRmgBmArto+Jji42Ac26Ey2cCQA8AQQB8ACiVyAlKAC8C0CmzQ1ALlABtOQF16TVuy69+g4ZDESpsuQBpQAIWWqv3hrauvpGpp4+lgwsbBw8fAJCus7iktLyAV4Awn4R3tlBOnoGxmaZoFmWFODQaBxyKa7pACo6mqAAJFkozMwyNXVwnMkuaSRerRQU8Q5JJOJKKMbY4gBGZJBeqwD8y2sbWqAADGErhOuQoADeVKDs4NyQwqAA1KCrANwUAL5TAxwAUQAHlAUPwAEpkB5PZq1DjtGTgryKFQAOnRohIxgaqGg8gUhVA4MJ4KmM0SuEYcDQ0AAYvYKTJacZ6QlHMpONgWRobjQaPdHrglOjUZjsY0xkyCcZgaCIVDBbC6lKtDpOcKMc4SGovr8+RQqdgSOBQPNCFlqbB2lSaazZtglGadbdqBQzRaaUoAIxeABMaiAA)

**Comment by bcherny** [comment]
Following up on this, here's a version that supports any number of arguments:

```
type $Arguments<F> = $Call<
  <A: $ReadOnlyArray<mixed>>((...A) => mixed) => A,
  F
>;
```

**Comment by Ricardo-Marques** [comment]
Solution above seems to resolve to `any`

https://flow.org/try/#0AQFwngDgpsAkCCAnA5gVwLZQHYgM4B4AxAPmAF44BhAQwBtb8AoYYfeALjgCUpqATAPJZaYJImph86AJYAPKH2LEAFMoB0G+AEpypGfL46ypeABpmwQo2IBuRvYBmqLAGMQ0gPZZg-QVhjKWBicQegARlCIWiEYEYjAAN4WLCyIUCCoiN6hwADUwACMjAC+9owuXrggPii4BZwIKBjYePjg0B4OPnx+UKQUAOTUA0A

**Comment by magicmark** [comment]
I ran into a case where this approach seems lossy somehow when combined with spread syntax

(It may be unrelated or I'm doing something dumb, but still, fwiw: https://stackoverflow.com/questions/57847208/how-can-i-get-the-arguments-to-a-function-in-a-non-lossy-way-with-flow)
