### ISSUE TITLE
Where are the React Flow types defined?

### ISSUE THREAD

**Issue by debel88** [facebook/flow#4677]
The React Flow Types described [in the documentation](https://flow.org/en/docs/react/types/) do not seem to be defined in the React codebase. Therefore, how can Flow parse those types ?

**Comment by TrySound** [comment]
There're several built in definitions
https://github.com/facebook/flow/blob/master/lib/react.js

**Comment by debel88** [comment]
Thanks! So, I guess that Flow injects those types automatically into React exports when it encounters `import * as React from 'react'` ?

**Comment by ghostd** [comment]
The behavior is described here:
https://flow.org/en/docs/react/types/
```
These types are all exported as named type exports from the react module. If you want to access them as members on the React object (e.g. React.Node or React.StatelessFunctionalComponent) and you are importing React as an ES module then you should import React as a namespace...
```

**Comment by debel88** [comment]
The statement you just quoted is precisely what is confusing. 

It claims that these types are exported from the react module. In reality, they are not. They are defined in the source code of flow, and during flow validation they are considered as exported by React (if I get the thing correctly)

IMHO, I think the doc should be updated accordingly.

**Comment by TrySound** [comment]
@debel88 They are the same as https://github.com/flowtype/flow-typed, but distributed with flow.

**Comment by debel88** [comment]
Indeed. Now I get it, thank you all for your replies
