### ISSUE TITLE
Spreading object breaks optional enum

### ISSUE THREAD

**Issue by leoselig** [facebook/flow#4682]
The following very simple snippet shows an error which, I am very certain, is wrong.
When fiddling with it a bit, it seems to be related to 2 conditions:
- the type of `field` allowing `null`, hence being an optional
- the `state` (that should have a valid `field`) being spread into the `return` value

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYpYAqmOAvKAN6KiiQCWW0AJgFygDkAogHIBVALIB9AGoBBADICeXUAB9QAOwCu0aIgC+AbmRYAHhlgAnFKFZZIBdecirlAYxSNYyhrFgAKOqADOhMSc+ESk5IgAlDS+JlgoqibutPT0TCwcKurQADS+9AB0hQGhoCCgsQC2sABuOCgAFox+oATKrP5YOMqwoFgmJqZ+vrraiEA

I ran into this when writing a new redux reducer (though I did not understand yet why this never happened before).

Tested on Flow Try on `master`, `0.53.1`, `0.53.0`, `0.52.0`, `0.51.1`, `0.51.0`

**Comment by asolove** [comment]
I tend to agree I would expect this to work. If you need a workaround right away, [this small change](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYpYAqmOAvKAN6KiiQCWW0AJgFygDkAogHIBVALIB9AGoBBADICeXUAB9QAOwCu0aIgC+AbmRYAHhlgAnFKFZZIBdecirlAYxSNYyhrFgAKOqADOhMSc+ESk5IgAlDS+0FjmBpy8gqKSMnKKKurQoFRqGnr0JnGqJu609PRMLBygBgA0vvQAdC0BoaAgoEUAtrAAbjgoABaMfqAEyqz+WDjKsKBYJiamfr662ohAA) is ugly but makes everything work as expected.

**Comment by leoselig** [comment]
@asolove 
Your curiosity...
> why you would set a value for a field in the same object where you then spread in an object that will definitely override the value for that field

actually answered mine...

> though I did not understand yet why this never happened before).

I indeed did not mean to spread this way and fixing the order fixes the issue for me

Anyway, I strongly believe there is a defect and this is **one** bug it might trigger

**Comment by asolove** [comment]
Yeah, could be: if you find another case let us know!

**Comment by leoselig** [comment]
@asolove Long time no... read
So I hit another use case – this time my workaround does not make sense for me

See this example: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWSwM4ECGA5lgCqY4C8oA3oqKALaEnkBcoBKATgEsAdqQA0THgGNY2bgH5egkYgC+AbmRYAHhlh8UoSAFchklANhDQkvlmIos+ImSwAxYgOgEAFPVAA6QNgANyw+QQATHBVuABIAZQALYmwAHicOSmoAPgBKbgyXKmwGCVsUIz4rRmZmNmcuUAAiSGIAaxx6zKbxWqkZLG4hI2hoXtrA-xCwyKwJdVVNHT0DY1NzS2tbe0d2FwB1PTafP0np8IEo0BjQBOS0wvJirDyCvafqUuZyyuqJOveg2arQ6rEBPX+-VkoGGo3mGhUiCAA

As you can see, as opposed to my initial example, I now really want to spread last, not first, since I am overriding the values

**Comment by villesau** [comment]
I think this fixes the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
