### ISSUE TITLE
(0.53.1) Problems with recommended HOC typing

### ISSUE THREAD

**Issue by danwang** [facebook/flow#4686]
Hi!

Thanks so much for the work with React types in version 0.53.0+! It looks very promising.

I've been using the recommended way to make a HOC that injects a prop, but I get two problems. [flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwCECAC44AOwCuIAEZYoAGiFx5yKJNkKlqgL706uADZp0AFSyoYAYRKQpWKfCwAPGM4Am6bHhgAdPbgEE4uADycENwAfAJqNsgwwLhwXlgEyDImMFHccHyCwsKiEnAAzKrF6pqSlWqGapRS6VAFcAAUAJQFcbImJvT6DLihNnDAUgBWWPgAYmLtkVyokvz6MR22kn74QQ6hzjAWLFjh-KXacopQ+nAAZBwrMV07VIHBjkcnrMvRqHEeHEOv0TJJkFImF16NVqsYxvAAJLTWaeLztSYzeZiDpWGyfQ4uaF0AD0JLgFgAFsB0JS0CgpHAlMQVEyAG7OOAwSkQGQAc0pNTadPQyDSGSyOTgYC4dHCyKxaLgJJiRjJFOptPpUggTKgLPUMngqB52XRilwWVQbFKE3Q3LYAHdiFI+VzTnKFaisOjSjwAERoLwEf1Cnj8cp3FU0IA)
1. Default props are not respected, so props that were default in the original component are no longer default in the enhanced one.
2. Injecting props removes the type on the prop. We intend to make the HOC add the prop only if a value wasn't passed in, so we still want to retain the type of the injected prop.

```jsx
import * as React from 'react';

type Props = {
  foo: number,
  bar: number,
};

class TestComponent extends React.Component<Props> {
  static defaultProps = {
    foo: 3,
    bar: 3,
  };
  render = () => null;
}

const injectFoo = <Props: {}>(C: React.ComponentType<{foo: number} & Props>): React.ComponentType<Props> => (null: any);
        
const Injected = injectFoo(TestComponent);
// This has an error, even though bar has a default prop
<Injected />;

// This has no error but should because foo is the wrong type
<Injected foo="asdf" bar={3} />;
```

**Comment by asolove** [comment]
Can you share the actual implementation of `injectFoo`? I think the problem can be solved if we can let Flow infer the type parameter to use in the return type. (`React.ComponentType<*>` instead of `React.ComponentType<Props>`), but right now Flow can't do accurate inference because of the fake `any` return.

**Comment by danwang-stripe** [comment]
Sure: [flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwCECAC44AOwCuIAEZYoAGiFx5yKJNkKlqgL706uADZp0AFSyoYAYRKQpWKfCwAPGM4Am6bHhgAdPbgEE4uADycENwAfAJqNsgwwLhwXlgEyDImMFHccHyCwsKiEnAAzKrF6pqSlWqGapRS6VAFcAAUAJQFcbImJvT6DLihNnDAUgBWWPgAYmLtkVyokvz6MR22kn74QQ6hzjAWLFjh-KXacopQ+nAAZBwrMV07VIHBjkcnrOEIcTw4kU4JQYDIoFJOmAVpI8qgeoC4OFbAIAmjodFUHdSjx+OU7gB6GJDeijKTjACS01mni87UmM3mYg6Vhsn0OLi69AJBLgFgAFsB0Py0ChIUpiCo4FgAG7OOAwfkQGQAc35NTaIvQyDSGSyOTgGLAdHCVMZtLgRKMPL5guFoqkEGlUEl6hk8FQSuydMUuCyqDYpQm6EVbAA7sQpCqFacTWaaVg6TiAERoLwEZMa3H4y3EoA)

This results in suppression of errors (it picks an overly permissive type for the `*`)

**Comment by AriaMinaei** [comment]
This is how I could get it to work: [flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdWAHpLHDAJ5hZwDCJkAHZZBMAOrAYACwAiWAsgCuAGxgAFYmFQAeOQpXrNqAFxwA3gF8ANHA0QtAPjgBeOnExUYAOn7gIw0QAVLixtO0c4ADJzABN5JVVwkzg9BMN7VAt6OgB6BAQ3JAAJLEo4YHRkOABzEVLgXHYQuAJoOCKAeV4TQsK4AEl4GGQAayx0GAB3CCbuODBkKGQQLBhS5OwAR0VgShiklEEY22IAN2A4-aNexA9t3awrjNNAqR4CYEFkZThJpbBuMdcAJ-CJ4JNgMofsJHncdnskjZPigYjFJMB-OwZpJ0BBJoJ5tdbnZzpcki83i1Pt9fv9AXBgX4AuDIdCIPAYccSRdHoi4AAjLC4JSoHjSHidXi-VmEiCksVvUgwGbi8qCYRQBkg5mFHKMFjQIbNIrAapvKAdKBxKC+IRg7RbeG8ow2blkoxOVzuaIACm0ltN1OUfNSBiSDh9jLtolMttBogk0lDiSMuniYZdcAD1SD4YAlC4HG53CXsHhvHHmcFuA6sPcEUYonAACQyYAEAjaVvtzvZ3OZt3OjIOGzJ9KOBx54u+-1QQNfYMeyPasGmMv4HwroIhWfz775wsecubplg6uhR0PJ5aJvdju7nMLvmD6+oByT7J0ThzA7OczF1oIFMQRFBAQUoCsYt+UWYDQPAyD3GggAvWCwNKSCsgYXBlDQdBAnGGBKzBOBmDWI50HXCstxgMJM1OCALicMxi1QYYYAaOA4n0FMMhcf8SxaCAgLgABmBCS2gqBTDE4tMPcSgjlKPifQLZwnBAqF6EwuhgUEVi1QAKyFGAADEhNME0zVKS1rSI0RtEsGwzEA1DwIsT04B9XhTGQQQODzHy-MPZj5NWRQoAJH0wCMUwklUpxtClMwvBS6KMgsQSIGcMwRIynIHC0+hdP0-pBCM-BYT-T5ytMoSfXw1i7JgPNsm0UqathZDsoARgABjygqGByHItSgSh8GUDgSLG6BUDoNqyuM2FAOcAAiNAYgIVaBUWbLcp2pCev6uB8poIA)

**Comment by asolove** [comment]
See the related discussion in: https://github.com/facebook/flow/issues/4644

**Comment by asolove** [comment]
I think I'm going to close this and encourage everyone to discuss HoC typing strategies in the linked issue to avoid splitting the conversation. If there's something specific to this one case that can't be solved by the HoC approach over there, let me know and I'm happy to reopen this!
