### ISSUE TITLE
Flow doesn't type-check objects wrapped in Object.freeze

### ISSUE THREAD

**Issue by ccapndave** [facebook/flow#469]
I often wrap my public APIs in an `Object.freeze` call to protect them from unintended fiddling.  However, it seems that if an object is wrapped like this Flow no longer does any type checking on the returned object instead of inferring that the output type of `Object.freeze` should be the same as the input type.

```js
type MyObjType = { foo: number };

// Flow catches a type error here
function createObj(): MyObjType {
  return {
    foo: "I'm not a number!"
  };
}

// ... but not here
function createFrozenObj(): MyObjType {
  return Object.freeze({
    foo: "I'm not a number!"
  });
}
```

**Comment by samwgoldman** [comment]
@ccapndave What version of flow are you using? With 0.11.0, your example is flagged as a type error.

(In fact, Flow doth complain too much, as it attempts to unify the types, so I see two type errors instead of one.)

**Comment by ccapndave** [comment]
As far as I can tell I'm using 0.11.0 (its part of a gulp pipeline using gulp-flowtype).  I'm also using Babel to convert from ES6 to ES5 (with the flow blacklisting).

I'd made a toy example to illustrate the problem, but here is my real code in case it makes a difference:

```js
/* @flow */
import I from 'immutable'

/*::
type Tour = {
  setRoute: number
}
*/

/*:: createTour: Tour => Tour */
const createTour = (tour) => Object.freeze({
  setRoute: (coordinates) => tour.setIn(['route', 'coordinates'], coordinates
});

export default function()/*: Tour */ {
  return createTour(
    I.fromJS({
      route: {
        coordinates: []
      }
    })
  );
}
```

This passes with 0 errors, but if I remove the `Object.freeze` it gives:

/app/src/models/tours.js(11,16): function - This type is incompatible with
/prototype/build_flow/models/tours.js(18,13): number
  ✖  2 errors

**Comment by samwgoldman** [comment]
Could it be the syntax error? You're missing a closing paren in the `tour.setIn` call.

I tested by just changing your `const` to a `var` and after fixing the syntax error I see the expected error.

If it's not that, can you track down the exact source that is actually parsed and checked by flow? Maybe a transform is changing the source into something that is actually tripping up flow.

**Comment by ccapndave** [comment]
Sorry - that was just a typo specially for github (now updated).  Changing the const to a var didn't make any difference for me; I am just going to triple check that my pipeline is using 0.11.0 and not somehow using 0.10.0 as this is starting to seem very suspicious :)

**Comment by ccapndave** [comment]
Ok, I'm definitely using 0.11.0, but actually the transpiled code has done something to `Object.freeze`; here is what it looks like:
```js
/* @flow */
'use strict';

var _Object$defineProperty = require('babel-runtime/core-js/object/define-property')['default'];

var _Object$freeze = require('babel-runtime/core-js/object/freeze')['default'];

var _interopRequireDefault = require('babel-runtime/helpers/interop-require-default')['default'];

_Object$defineProperty(exports, '__esModule', {
  value: true
});

var _immutable = require('immutable');

var _immutable2 = _interopRequireDefault(_immutable);

/*::
type Tour = {
  setRoute: number
}
*/

var createTour = function createTour(tour) {
  return _Object$freeze({
    setRoute: function setRoute(coordinates) {
      return tour.setIn(['route', 'coordinates'], coordinates);
    }
  });
};

exports['default'] = function () /*: Tour */{
  return createTour(_immutable2['default'].fromJS({
    route: {
      coordinates: []
    }
  }));
};

module.exports = exports['default'];
//# sourceMappingURL=../models/tours.js.map
```

**Comment by ccapndave** [comment]
Ah, I figured out that I was using the 'babel-runtime' transformer which was putting in all these polyfills and breaking type checking.  Removing it gives me the (double) error as expected.  Sorry about that!

**Comment by samwgoldman** [comment]
Ah, well this makes sense. Unfortunately, flow only understands exactly `Object.freeze(...)`. The logic is actually encoded in the type checker itself by pattern matching on the JS AST for specifically that function call. The indirection here prevents flow from recognizing what is going on.

To be honest, fixing this seems out of scope. I think our efforts would be better focused supporting the ES6 features directly so that you can run flow on your pre-transpiled source.

As I was writing my response, I see you found a suitable workaround for the issue. Thanks for sharing that with future readers! Future readers, hopefully we've managed to build support for all the ES6 (and 7) features by the time you see this.
