### ISSUE TITLE
HOC props are required to be present in wrapped component Props type

### ISSUE THREAD

**Issue by TLadd** [facebook/flow#4692]
When using the new way of typing HOC's in v0.53.0, it is required that all injected properties are present in the Props definition of the Component that is being wrapped. For instance, not having bar in Props for MyComponent causes an error in [this example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINApBAKyr0ACkwwAeBbAykAXKADeAXwB8ACkShQAYWZZBVQbi3U6uAHQXMYm7gAqATwxUl2qCQsLBagvxoAEZU2AA0oJHE2GER0diguqAAZKCq6vqxiACU9pzOrlYePn4qiqT6OiagHLj82OICwrii4gDq2MQYftgV7raGGHVaeaRFjaamLW3iSqPWtjpOW5NqpJnBsAC82gAsAEyZidjHAIwADHeZwPq8prq8usi00GTkALLeNYeUBUAAeuBsABNyA56C5LGNcAEmsQUlEYoVTJE0WlMUEQjiMYgDDpPohaGJSPgAQBRQQAC2IwiokKBG0OEmkslweUMALZuCKvEQIFAvSooEhYlY+GsLNAuFgoAwv05oAABgd1SCAG42BX02D8ADm9I1-IR61w2o4AEd+CgOOQUM5EEpaQymbQWQKSLdLscLqBntwgA)

Some HOC's inject quite a few properties into a component, but I may only care about utilizing one or two of them. Is it possible to create a type definition for an HOC that does not require the user to include every prop that is injected?

**Comment by asolove** [comment]
I _think_ this is the same problem as in #4644. The solution there will probably work here too.

**Comment by TLadd** [comment]
At least one difference is that setting the props as optional in the HOC definition does not seem to fix it as it does in #4644. [Example.](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINApBAKyr0ACkwwAeBbAykAXKADeAXwB8ACkShQAYWZZBVQbi3U6uAHQXMYm7gAqATwxUl2qCQsLBagvxoAEZU2AA0oJHE2AD8YRHR2KC6oABkoKrq+rGIAJT2nM6uVh4+fiqKpPo6JqAcuPzY4gLCuKLiAOrYxBh+2FXutoYYDVoFpCXNpqZtHeJK49a2Ok4702qk2cGwALzaACwATNmJ2KcAjAAMD9nA+rymury6yLTQZOQAWW8Gw8oCoAA9cDYACbkBz0FyWCa4AItYhpKIxYqmSIYjLYoIhPFYxAGHTfRC0MSkfBAgCiggAFsRhFRoSCtscJNJZLgCoYgRzcCVeIgQKB+lRQNCxKx8NY2aBcLBQBh-tzQAADI6asEANxsSsZsH4AHNGVrBUjNrhdRwAI78FAccgoZyIJT0pks2hsoUke7XU5XUCvbhAA)

I get why it's an error; the HOC definition is saying that the input component should have an optional bar prop and the component I'm passing doesn't have a bar prop specified. Just sure would be convenient if there was a way to specify _if it has these props, they are this type, but it may only have a subset of them and that is okay_.

**Comment by asolove** [comment]
Oh! Feels like something that could be solved with `$Shape`.

**Comment by TLadd** [comment]
Yeah, that was one of the first things I tried because it did seem appropriate, but I get the same error using $Shape as well. [Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINApBAKyr0ACkwwAeBbAykAXKADeAXwB8ACkShQAYWZZBVQbi3U6uAHQXMYm7gAqATwxUlACQAygAWxH5K2qCQsLBagvxoAEZU2AA0oEnE2PGJKdigBqAAZKCq6vppiACU9pzOrlYePhHlpPo6JqAcuPzY4gLCuKLiAOrY4X7Yje62hhiKmmWL1Z2mpj194koz1rY6TocLaqS60bEAvNoALABMZ1nYVwCMAAyvZ8D6vKa6vLrIWjQMjkACy3l2HlAVAAHrgbAATcgOeguSyzXCRLrEXLJVJVUxJXH5AnnOKgBJ49KIIp6QFiUj4cEAUUEYWEVARkP2Fwk0lkuHKhnB3Nw1V4iBAoFGVFACLErHw1k5oFwsFAGBBfNAAAMYrAddCAG42VUhWD8ADmIV1IvRe1who4AEd+CgOOQUM5EEoWWziByufaocQXg8rvdQF9uEA)

```
// @flow

import * as React from 'react';

function injectProp<Props: {}>(
  Component: React.ComponentType<$Shape<{ foo: number, bar: number }> & Props>,
): React.ComponentType<Props> {
  return function WrapperComponent(props: Props) {
    return <Component {...props} foo={42} bar={100} />;
  };
}

class MyComponent extends React.Component<{
  a: number,
  b: number,
  foo: number,
}> {}

const MyEnhancedComponent = injectProp(MyComponent);

// We don't need to pass in `foo` even though `MyComponent` requires it.
<MyEnhancedComponent a={1} b={2} />;
```

**Comment by asolove** [comment]
If I make a small change to that example, by replacing the intersection type with a type spread, it works:

```js
// @flow

import * as React from 'react';

function injectProp<Props: {}>(
  Component: React.ComponentType<{ foo: number, bar?: number, ...Props }>,
): React.ComponentType<Props> {
  return function WrapperComponent(props: Props) {
    return <Component {...props} foo={42} bar={100} />;
  };
}

class MyComponent extends React.Component<{
  a: number,
  b: number,
  foo: number,
}> {}

const MyEnhancedComponent = injectProp(MyComponent);

// We don't need to pass in `foo` even though `MyComponent` requires it.
<MyEnhancedComponent a={1} b={2} />;
```

Let me know if that handles what you're looking for.

**Comment by TLadd** [comment]
That does appear to work; bar doesn't even need to be optional in the HOC definition ([example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINApBAKyr0ACkwwAeBbAykAXKADeAXwB8ACkShQAYWZZBVQbi3U6uAHQXMYm7gAqATwxUl2qCQsLBagvxoAEZU2AA0oJHE2GER0XGgTpmq6qAGsYgAlPaczq5WHj5+Koqk+jomoBy4-NjiAsK4ouIA6tjEGH7YZe62hhg1WtmkBfWmpk0t4krD1rY6mU7jaqS6QSEAvNoALABMu4nYhwCMAAw3u8D6vKa6vLrItNBk5ACy3iseUBUAAeuBsABNyA56C5LCNcAEGsQUlEYvlTJEUWl0XtQqBwqi4ogDDp3ohaGJSPg-gBRQQAC2Iwio4IBa32Emkslw2UMfzZuAKvEQIFA3SooHBYlY+GsLNAuFgoAw305oAABsFYOqgQA3GwK+mwfgAc3pGv5cNWuB1HAAjvwUBxyChnIglLSGUzaCyBSRrudDmdQI9uEA)). Thanks! Not quite sure I understand why this works vs intersection, but I'm pretty unaware of the differences between type spread and intersection in general.

**Comment by TLadd** [comment]
It does appear that there are some negative consequences to this approach though

```
// @flow

import * as React from 'react';

function injectProp<Props: {}>(
  Component: React.ComponentType<{ foo: number, bar: number, ...Props }>,
): React.ComponentType<Props> {
  return function WrapperComponent(props: Props) {
    return <Component {...props} foo={42} bar="100" />;
  };
}

class MyComponent extends React.Component<{
  a: number,
  b: number,
  foo: number,
  bar: number,
}> {}

const MyEnhancedComponent = injectProp(MyComponent);

// We don't need to pass in `foo` even though `MyComponent` requires it.
<MyEnhancedComponent a={1} b={2} />;
```

I am now able to pass a string in the HOC for bar and it doesn't catch the type error.

**Comment by TLadd** [comment]
I believe this has been fixed since I filed the issue. I haven't had issues typing HOC's since React.ElementConfig was added: https://flow.org/en/docs/react/hoc/#toc-supporting-defaultprops-with-react-elementconfig
