### ISSUE TITLE
Function interface A extending interface B does not seem to inherit B's properties 

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4695]
Here is an example [illustrating this issue](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gAKxBAzoQDzEB8YA3qmGAA430AU2bgFccALlo4C2AOYBKMQH5iqAL7ps+ImQoBhOAFsARtmI44BME1Z4AHviwATWlT6MW7TmEFYR4ydJY8koq6qiOeKQwNBQAbjQ8bgRi+sam5gQMAbLM6Lx0hAB0+QIA5FBwcKVyQA):

```js
/* @flow */

interface Parser<a> {
  parse(input:string):?a
}

interface Combinator <a> extends Parser<a> {
  (input:string):?a
}

declare var parser:Combinator<string>

parser.parse('foo')
//     ^ property `parse`. Property not found in  Object
```

**Comment by Mocha--** [comment]
Any workaround for this issue? I got it as well.

**Comment by SamChou19815** [comment]
this now works
