### ISSUE TITLE
React.ChildrenArray<*> is Inexact type

### ISSUE THREAD

**Issue by n006r** [facebook/flow#4698]
I want to make something with child nodes of React component (for example clone it with extended props). And get an error `read-only array type. Inexact type is incompatible with exact type`.

simple code example:

    const Foo = () => (
    	<div>hello</div> 
    );
    
    const Bar = (props:{children: React.ChildrenArray<React.Element<*>>}) => (
      <div>
        {
          React.Children.map(
            props.children,
            (child) => React.cloneElement(child, {testprop: 1})
          )
        }
      </div>
    );
    
    <Bar>
      <Foo />
      <Foo />
    </Bar>
[example on flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnTgA7MkQBicOGAC8YABQBKGQD55qAJAAeACboAbsoAW1GPE3BdBsKgV8Bw0WABCJPDPnZm2MgC4A3nSG6DDanEI+VFwEAHQAwkEhYQCCeHgkAJ6aNPQxAKIw1JjUQgSaIMrKAL5K0qpyqGBgOvrKDY1gfm3tkTlxCaHF0Zgk2PXd3Z5w3tGBwQNCADRd43KzITWq2Qwz8ELU+YXFBKv9Cx0E1KKT2BEAjNXLjQrLlW3mlq22-JoueK2NmgkUmA-yaQLAINQ5l+yiAA)

Is it bug, or I setting types wrong?

**Comment by asolove** [comment]
This seems to be the same issue described in #4625, which the team has said will be fixed shortly.

**Comment by EvHaus** [comment]
Looks like this is fixed in Flow 0.54
