### ISSUE TITLE
Flow doesn't correctly infer nested array

### ISSUE THREAD

**Issue by maartenschumacher** [facebook/flow#4699]
I'm trying to type a function that recursively flattens a nested array:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOC0g66rCgHgBUA+ACgA8AzgC4wAQUKF8AT3YSps+TK7dVASlFLZPANyZcBYqUo16jWPhZsVAkeMnKtK7hvsKVe1DgaDqYfJoOikFyIb6EtBQA5qrcYAC8YADaKQDkqQC6WV4+fgBGCclpmdk5FL5g-IHu4ZExhRZWFLz4amUV0tXKtdFxiY2szXlqQA

It works when I explicitly annotate the nested array, but it doesn't work when I don't.

**Comment by SamChou19815** [comment]
Now both work
