### ISSUE TITLE
Add ability to import/export type definitions

### ISSUE THREAD

**Issue by thomasboyt** [facebook/flow#47]
This was discussed this briefly in IRC ([log](https://botbot.me/freenode/flowtype/2014-11-19/?msg=25762495&page=1)), and it seems like it'll require some new syntax, likely something to the effect of:

```js
import type { MyType } from "./SomeModule";
```

This can be easily compiled out of the final output, and use the same path resolution as a regular module import would. The syntax might be a bit confusing when part of a CommonJS module, but on the plus side it has parity with ES6 module syntax.

Rather than add new export syntax, it should be okay to implicitly export all the types in a file (since you have to specify which exactly ones you're importing anyways).

**Comment by samwgoldman** [comment]
`import type` has existed for a while now, and has been written about on the blog: http://flowtype.org/blog/2015/02/18/Import-Types.html

Can this be closed, or is there an unresolved issue here?

**Comment by mroch** [comment]
gonna close, reopen if there's still an issue
