### ISSUE TITLE
displayName property is not found in React HoC

### ISSUE THREAD

**Issue by avaly** [facebook/flow#4700]
When building React higher-order components, it's useful to set a `displayName` like this:

```js
WrapperComponent.displayName = `Wrapped(${Component.displayName})`;
```

However Flow `0.53.1` complains that `displayName` is not found.

Test case:

https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdBArgHb7AQtwDuUyYAHgAKxMKgBccAN4BfAHwAKOnDgBhEpBZYWMSdjwwAdOvCdtMACoBPMFmGjUcgDR0AlHqpGTm89dv2IMTlpZThmNhgOLgB1PjBbKG8zHQUwB0kRQNRXEJUVShgmKC4BJK0daUMqtKyZOAB6OXoVGWa4WP4EsvNDABNgVDAAG2QrADlkECw4AF44AAMO+KxehQASKW6dPoHh0YmpmVd5toKimLiujWSYehkGXBHUdABZKy34LAAPGG1e9H0+GM13KMAEsmCsjo9XqcAsAAsBjxgEMhnAWBBCMAvnAYPDplgoMQoNDYW8PjtBiNxpNpnMyOSQeZaA9OKh4G8AKIseHINgrD6zHhxBSM0yg1z0Lk8vm4AVM7b9Kn7Wk0IA

**Comment by asolove** [comment]
I think this was resolved by this recent commit: https://github.com/facebook/flow/commit/de37062ea21cb4055d3f1b01bdbaa76461140fc8 which added `displayName` to the `StatelessFunctionalComponent` type, which is what this function is inferred as.

**Comment by avaly** [comment]
This works as of Flow `0.54.0`
