### ISSUE TITLE
How to declare single-function module sufficiently specifically?

### ISSUE THREAD

**Issue by Harrisonbro** [facebook/flow#4703]
I want to include [`lodash.isstring`](https://www.npmjs.com/package/lodash.isstring) in a project using Flow. In the flow type library, there is a great definition file for the whole of Lodash which includes [this code](https://github.com/flowtype/flow-typed/blob/6b8370bc711addc09acdaeb4688173f1814127cc/definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js#L597-L600):

```js
isString(value: string): true, 
isString( 
  value: number | boolean | Function | void | null | Object | Array<any> 
): false, 
```

Those two definitions for that same `isString` class method will, I'm assuming, tell Flow that if you call `Lodash.isString` with a string it will return `true` and if you call it with anything else it will return `false`. 

I'd like to do the same when using [`lodash.isstring`](https://www.npmjs.com/package/lodash.isstring) by itself but can't see how to do that. So far the best I can come up with is this:

```js
declare module 'lodash.isempty' {
    declare module.exports : (value : any) => boolean;
}
```

However, that doesn't prevent Flow throwing errors for code like this:

```js
/* @flow */

class MyClass {
    myMethod (myString : ? string) {
        if (isString(myString)) {
            bar.myString = myString.trim();
                        // ^^^^^^^^ call of method `trim`: Method cannot be called on possibly null value 'null'
        }
    }
}
```

(see [this live example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsWgZwGVrDaKBzACgDd8MMiQBcYfBQCeASjDiARnDgwskgNzo8+ZszABZKQGECusAG9UYMAFsp+rNQAWcDGF532nHvLAB+MGYOLm45S2trHAYgsAUiMABeC09gnnEAcnSAX00rCNoodxYvEI8pEp4ZMLyI2KIAOhTvbkTbctTueuCbXhlNWqy8waygA) of the code above on [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswoBXAOxwBcBLOCsWgZwGVrDaKBzACgDd8MMiQBcYfBQCeASjDiARnDgwskgNzo8+ZszABZKQGECusAG9UYMAFsp+rNQAWcDGF532nHvLAB+MGYOLm45S2trHAYgsAUiMABeC09gnnEAcnSAX00rCNoodxYvEI8pEp4ZMLyI2KIAOhTvbkTbctTueuCbXhlNWqy8waygA))

Is it possible to define a single-function module in the same way that [Lodash's full flow library definition](https://github.com/flowtype/flow-typed/blob/6b8370bc711addc09acdaeb4688173f1814127cc/definitions/npm/lodash_v4.x.x/flow_v0.47.x-/lodash_v4.x.x.js#L597-598) does?

**Comment by jcready** [comment]
As far as I know you cannot define predicate (`%checks`) functions in flow library definitions. If lodash itself was built with flow it could do something like this:

```js
const isString = (input: mixed) : boolean %checks => typeof input === 'string'
```

The lodash library definition is wrong anyhow. It doesn't accept `mixed` types for the second case. It would make more sense if the second version's `value` was typed as `any`, but it's likely unsound regardless.

**Comment by Harrisonbro** [comment]
OK, thanks for clarifying. Can you think of any way to sort out that `call of method 'trim'` error, or do I just need to stick a `// $FlowFixMe` on it?

**Comment by jcready** [comment]
You could just replace lodash's `isString()` function with the one I provided. Or just put `typeof myString === 'string'` directly in your if statement.

**Comment by Harrisonbro** [comment]
> Or just put `typeof myString === 'string'` directly in your if statement.

Yep, this is clearly the right option! Too focussed on making flow work to see the obvious answer... Thanks!
