### ISSUE TITLE
Function with annotated return value hides errors for the returned class

### ISSUE THREAD

**Issue by ubershmekel** [facebook/flow#4705]
> No errors!

```
// @flow

class MyClass {
  async simple({a, b}) {
    return [a, b];
  }
}

export function getdb(): MyClass {
  return new MyClass();
}
```

While the following does get an error when the function return value annotation is missing:

>4:   async simple({a, b}) {
>                  ^ destructuring. Missing annotation

```
// @flow

class MyClass {
  async simple({a, b}) {
    return [a, b];
  }
}

export function getdb() {
  return new MyClass();
}
```

This seems as though flow is stricter on non-exported classes, or somehow its inference type checking is better than the annotated.

See https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToCyBPAYQ21AG9FRQt8A7FUTASwFsAHaAUwAoz0AaUACMAvgEpylKqABOnAC4BXGbVABtAcIC6AbikjEBxCE4APNrBnzQkRfXlNYqgOYKAJkO5iAXHiIkcCjMLKxs7FAcnUFd5Dy9JKjklFVBaTng-YixMLz0DIA

**Comment by Mathspy** [comment]
This has been fixed in [v0.98.0](https://github.com/facebook/flow/releases/tag/v0.98.0). Both of these throw the same error now

@goodmind
