### ISSUE TITLE
Flow arity errors are squelched across projects when a function class is annotated

### ISSUE THREAD

**Issue by ubershmekel** [facebook/flow#4706]
I've created a repo that reproduces this issue at https://github.com/ubershmekel/flownoerror

Although this issue requires annotating a function to reproduce like https://github.com/facebook/flow/issues/4705 the results are a bit different - a lack of arity checking. You'd expect when running `flow` in `myapp` that it would show an error but it doesn't.

**Comment by ubershmekel** [comment]
When my function is annotated - vs code can jump to class method definitions but can't detect arity mistakes. When the function isn't annotated I get arity type checking but not jump to definition. :(

**Comment by SamChou19815** [comment]
Closing since Flow should now behave much more predictably since we will require annotations for exports.
