### ISSUE TITLE
Defined state type, but returns error saying prop is required but undefined error.

### ISSUE THREAD

**Issue by WonSong** [facebook/flow#4707]
I feel this isn't really flow issue, but couldn't find a solution.

Getting this prop type issue:

![image](https://user-images.githubusercontent.com/5981331/29683660-f3079472-88c3-11e7-8f6c-8e4c8aa6788a.png)

with following code:

``` javascript

// @flow

...

type State = {
  currentPage: number
};

class Table extends React.Component<Props, State> {

  state = {
    currentPage: 1
  }

  ...
}
```
I don't have a prop called currentPage, and i am not doing ```this.props.currentPage``` any where.

Any guidance is appreciated!

**Comment by asolove** [comment]
What is the type `Props`?

Also, where are you seeing that message? It looks like a console message in the browser, which would be coming from React PropTypes, not from Flow's static type checking. Is it possible that you've defined a `Table.propTypes` that expects `currentPage` to exist?

**Comment by WonSong** [comment]
As I mentioned in the question, Props does not have currentPage, and no where in code I try to access props.currentPage. This happens with all my react components that I have state. I should try removing some babel presets, and see if that fixes.

**Comment by WonSong** [comment]
Turns out, removing  "plugins": ["flow-react-proptypes"] from my babelrc fixed the issue. Probalby an issue with that plugin. Thanks.

**Comment by asolove** [comment]
Glad that fixed it. Since this isn't a flow issue, I think we can close it.

**Comment by lvdang** [comment]
@WonSong  - did you add "flow-react-prototypes" back for the newest npm for babel-plugin-flow-react-proptypes

**Comment by lvdang** [comment]
@WonSong  - I am having the same issue like you.

**Comment by lvdang** [comment]
@WonSong - I did the same by removing 'flow-react-proptypes' then it worked. What Flow version are you using? I am on v57.3

**Comment by HebleV** [comment]
Thank @asolove Your first comment helped me in solving a similar problem.

**Comment by ynuska** [comment]
Hi, recently I start having this error. I'm using 24.0.0 version of  "babel-plugin-flow-react-proptypes". by removing it I've solved the problem, but I would like to use this plugin. Anybody found another approach to solve this problem ?
