### ISSUE TITLE
No expected errors when using dynamic injection

### ISSUE THREAD

**Issue by greenSnot** [facebook/flow#4708]
[demo](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxcAnAUwEN9KBBACgEowBvVMMK-Tc0jly7UAXGABMAZgAsnMAF8A3KiXoseIiTDUADjpgBPAEIAeACpi28gHyMo2MQDEcBYtlaDulXvzCMAdIHU5ADmAM6sALzW7HJcMN5gAB5gkWD2AUGhEcpCXj4CcUKB-kkANEVcAEZiAIxSRapc8iroAG7BZKnaeoZGjBQ0dPTMLMq4-gCOYMDAYJTk5HDkYGEAFnCYMAAmYFWUYGsLlEA])
```

/* @flow */

function createA() {
  return {
    a: 234
  };
};

function applyB<T: {}>(fn: Function) {
  return (...args) => {
    let x = fn(...args);
    return {
      ...x,
      b: 123
    };
  }
}

var c = applyB(createA)();
c.q // error should be here
```

**Comment by asolove** [comment]
I think the issue here is that without type annotations, Flow is defaulting to using `any` types in several places. By marking `fn` as `Function`, for example, Flow has no idea what the return type should be. As a result, the return type of `applyB` is currently just `Object`, and it's allowable to look for a property `q` on an object. I think you'll need to add types to `applyB` to help Flow figure out what you expect.

I tried to get this working, but couldn't get the last step. Here's where I got:

```js
function createA(): { a: number } {
  return {
    a: 234
  };
};

function applyB<R: {}> (
  fn: (...args: any) => R
): (...args: any) => { ...R, b: number } {
  return (...args) => {
    let x: R = fn(...args);
    let vals: {...R, b:number} = {
      ...x,
      b: 123
    }
    return vals;
  }
}

let step1: (...args: any) => { a:number } = createA;
let step2: (...args: any) => { a:number, b: number } = applyB(step1);
                              
var c = step2();
c.q // error should be here
```

Which does error on the use of `c.q`, but also says I'm not allowed to spread the `R` type. Seems like this should work, though...

**Comment by greenSnot** [comment]
@asolove  solved! Thanks
```
function createA(): { a: number } {
  return {
    a: 234
  };
};

function applyB<R: {}> (
  fn: (...args: any) => R
): (...args: any) => R & {b: number } {
  return (...args) => {
    let x: R = fn(...args);
    let vals: R & {b:number} = {
      ...x,
      b: 123
    }
    return vals;
  }
}

let step1: (...args: any) => { a:number } = createA;
let step2: (...args: any) => { a:number, b: number } = applyB(step1);
                              
var c = step2();
c.q // error should be here
```

**Comment by asolove** [comment]
Awesome! I guess I don't have a good intuition about why `R & {b:number}` works here and spread type isn't allowed. I often have to do the opposite transformation...

**Comment by greenSnot** [comment]
@asolove Well, there will be an new issue
```
function createA(): { a: number } {
  return {
    a: 234
  };
};

function applyB<R: {}> (
  fn: (...args: any) => R
): (...args: any) => R & {b: number } {
  return (...args) => {
    let x: R = fn(...args);
    let vals: R & {b:number} = {
      ...x,
      b: 123
    }
    return vals;
  }
}

let step1: (...args: any) => { a:number } = createA;
let step2: (...args: any) => { a:number, b: number } = applyB(step1);
                              
var c = step2(1,2,3);// error should be here
c.q // error should be here
```

**Comment by asolove** [comment]
Yeah, this is just going to be a problem that I don't think we can fix. There is currently no way to refer to "all the arguments of a function" as a single type. What I would normally do in this case is cast the function returned by `applyB` to the specific type that it ought to have.

**Comment by greenSnot** [comment]
move to #4810
