### ISSUE TITLE
Is "Bounded Polymorphism" supported via "Flow Comments"

### ISSUE THREAD

**Issue by tychotatitscheff** [facebook/flow#471]
Hi, 

the documentation doesn't make it clear whether **flow comments (0.4.0)** provides support for **bounded polymorphism (0.5.0)**.
If it does, is it possible to provide update to both post ?

best regards.

**Comment by jeffmo** [comment]
Yes, all Flow annotation syntax-extensions, including bounded polymorphism, should work with the flow comments feature. This will also be true for any annotation syntax that may get added in the future as well.
