### ISSUE TITLE
iteratable variable at for ...in can be only string

### ISSUE THREAD

**Issue by n06rin** [facebook/flow#4715]
I'm using object as map. And as keys of that map I have a enum type. That notated as described here: https://flow.org/en/docs/types/objects/#toc-objects-as-maps

But flow think that in for...in variable can be only string type. Maybe that is good, but maybe exist workaround to define iteratable variable as enum type?

simple example

    type sEnum = 'foo' | 'bar';
    
    const iterObj: {[sEnum]: number} = {foo: 1, bar: 2};
    
    for(const i: sEnum in iterObj) {
      console.log('hey, we get ', i);
    }
[live example at flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDOAogHYCuAtmALxgDkUccdYAPvQEYCGATnQNypUAYzgkC6MAEt0uHgHkOAKwBcYAN4BtYuQoBdNbo5yAvjQ2M4agIwAaMNx5qATCcGpGPABSjxkqWo6lNIk0rIKygCUGqhgYL4EcDC4AHTwAOZedAAWuJj2CPjpuJJ09lKRgiZAA)

I was try to find another way, but this is not working too:

    Object.keys(iterObj).map((k: sEnum) => ({[k]: 0}))

[another example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDOAogHYCuAtmALxgDkUccdYAPvQEYCGATnQNypUAYzgkC6MAEt0uHgHkOAKwBcYAN4BtYuQoBdNbo5yAvjQ2M4agIwAaMNx5qATCcGpFS3MPQA6ANa4mAQAFDJyngCUvhRc2CEh-mo6lJE0AHxgIVr+BmAADCaRkUA)

[MDN article about for ... in](developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for...in)

**Comment by lll000111** [comment]
The `Object.keys` example is "works as expected", unfortunately. That function has a return type of "string", the object that goes into it is not examined as far as I can tell - I had the same problem with `Object.keys` and the only solution if I didn't want to accept the naked "string" result from that function was [type casting](https://flow.org/en/docs/types/casting/).

**Comment by n06rin** [comment]
@lll000111 thank you, that works. And for my case I don't have any side-effect. But code start to look a little tricky.

So, I need to close issue, if that is not a bug or something?

**Comment by lll000111** [comment]
Yes, I would close it. Looking deeper into what functions are actually doing would be "nice to have" in many places where the information seems easily accessible to a human eye, but that's obvious enough and of the wishlist of many and also so generic that I think it doesn't need another open issue.
