### ISSUE TITLE
idx() callbacks may only access properties on the callback parameter!

### ISSUE THREAD

**Issue by xareelee** [facebook/flow#4729]
The following code raises a [flowtype](https://flowtype.org/) error when using [idx](https://github.com/facebookincubator/idx) with [immutable.js](https://github.com/facebook/immutable-js/):

```js
// `state` is obtained from redux store
// `state.user` is an immutable object; you need to use `getIn()` to access properties
const token = idx(state, _ => _.user.getIn(['userInfo', 'token']));
```

The flowtype shows the error:

```
 81:   const countryCode = idx(state, _ => _.country.getIn(['selectCountry', 'countryCode']));
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ function call. idx() callbacks may only access properties on the callback parameter!
```

I need to change code to this to suppress flowtype warnings:

```js
const tokenS = idx(state, _ => _.user.getIn);
const token = (tokenS) ? tokenS(['userInfo', 'token']) : undefined;
```

It makes no sense to write such code.

**Comment by asolove** [comment]
Is there a reason why you want to use Immutable's `getIn` inside of `idx`? The example code here could just be replaced with `user.getIn(["userInfo", "token"])`, which is already safe in the case where those nested keys might not exist.

I suppose you might want to use the two together in a case where some of the nested objects were plain JS objects.

In any event, the machinery that `idx` uses to make the nested lookup safe only works when accessing nested properties. It doesn't work when accessing inherited methods like `getIn`. So I don't think your request to make this work is going to happen. But if you can tell me more about the specific situation you're in, I bet we can find a creative solution that solves it.

**Comment by rocketraman** [comment]
Doing a null-safe chained access with functional methods is not an unusual thing. For example, given an object `err` that possibly contains a property `graphQLErrors` which is an array, one value of which possibly contains a property `userMessage`, we want to extract the first `userMessage`. One would think one could do:

```
let msg = idx(err, _ => _.graphQLErrors.find(e => e.userMessage).userMessage)
```

In languages that support the null-safe operator, like Kotlin or C# this would translate exactly to:

```
err.graphQLErrors?.find(e => e.userMessage)?.userMessage
```
