### ISSUE TITLE
Function cannot be called on possibly undefined value

### ISSUE THREAD

**Issue by adamdonahue** [facebook/flow#4731]
I'm having no luck typing this pattern.  

The following works:

```javascript
type Props = {
  onChange: (string) => void
}

class Field extends Component<Props> {
  static defaultProps = {
    onChange: noop
  }

  onChange = (e) => {
     const value = e.target.value;
     this.props.onChange(value);
  }
```

But if I make the `onChange` property optional 

```javascript
type Props = {
  onChange?: (string | null) => void
}
```

I get an error `Function cannot be called on possibly undefined value`.  Now this seems to me to mean that a specific null or undefined value is passed as an `onChange` handler here.  Unfortunately, the "obvious" check here doesn't seem to work:

```
    if (this.props.onChange !== undefined && this.props.onChange !== null)
      this.props.onChange(value);
```

But this code does:

```
   let onChange = this.props.onChange || noop;
   onChange(value)
```

Is this due to Flow's type checking implementation?  Is the assignment here required?

**Comment by jcready** [comment]
```js
if (this.props.onChange) this.props.onChange(value)
```

**Comment by adamdonahue** [comment]
That was my first attempt, and it didn't work.

**Comment by asolove** [comment]
You closed this yourself before I could poke at it any more. Did you find the reason for the problem?

**Comment by adamdonahue** [comment]
This, for example, does not pass:

Type:
```
  createSubObject?: (string, string) => null,
```

Code:
```
  createSubObject = (subObject: string) => {
    if (!this.props.createSubObject)
      return;
    Promise.all(
      this.props.things.map(({ id }) => {
        return this.props.createSubObject(id, subObject);
      })
    );
  };
```

If I put the test directly above the call, then it passes, but that means I have to call on the Promise even when there's no action to bother calling.

**Comment by adamdonahue** [comment]
Actually no -- same error regardless of where I put the test.
