### ISSUE TITLE
Flow does not understand tagged template string parameters

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#4732]
````js
/* @flow */

const myTag = (strings: Array<string>, ...expressions: Array<number>) => '';
myTag`${"foo"}`; // Expected error 'number expected but found string' but no error reported.
````
[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFsBPAFQEMBzMAXjAAoCAnAS2ytwC4wBBZ5hRIAeFuyoA+ADRgAdPICmADwAOzBblysc3PgKHDsAVyIAjBcwkBKOhLAByewG5UpSlQAGAEgDeAIig4OD8AXw8nMGBgMABRVQUMQgtmOGYeP2MzCzBlFQT8BQATPzBTI0JsHAUwdRVUgsLZIA)

**Comment by vicapow** [comment]
This is blocking: https://github.com/flowtype/flow-typed/issues/1183

**Comment by asolove** [comment]
Just adding some links to related issues: #3936, #2616, appears in a todo list in #560.

**Comment by vkurchatkin** [comment]
#3936 should be super-easy

**Comment by vicapow** [comment]
woo! sweet.
