### ISSUE TITLE
A better way to handle redux action types?

### ISSUE THREAD

**Issue by yourfavorite** [facebook/flow#4737]
I've been trying to work flow into a react-redux project but getting flow to interact smoothly with Redux actions is proving difficult. The issue is that each reducer needs to be aware of every single action type in order to work without error. This wouldn't be a huge problem for a simple app, but for a larger app, especially one that uses modules like react-router and react-redux-form, we're looking at a lot of different actions that need typing.

[Here is an example of a working isolated reducer.](https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AGQPICCAIgPoAKASgKIBiAyqfQKoDCr199oAvKAOQESFGgyZsOXfgG4U6bKGblihACrURdXgKUr1m2jMSIsATwAOAU1ABDVRet8A3olCgA1GasAuUNgBOAJZoAOaIAL6yiJYAHuaw-jhe1jbIWIHo9lbaLm6eDr7JsJB4RGRUdIws7Jz0ADSuoOb+lpAYvoT+-jamADxOpIEAJr4BwSF1oABuNtAArpa+Nmim4QB8EaAAPqC5HsmFDsWKymoaFbQNbsOjWEGhV9OzC0srEVGx8YmgQ602c9AcAAKbA2LCLXbhHLhSapdLoJZpDJoLKWACUvDWu0aGHggSwyAAFqAgXDkQA6ZIYvZuZA2DDWITlURVCS1Xw0tygVCYHBoSzwehYMGOSGyLlcsnocnNVoYcmQBLUVKEoHmTHYiUS-mC4XggDa5nJgyGAF1tEaZvNLOKteE0baJS0sHN-GhQDqhSLHaBwo1afTrLozgYOf6uc7Xe6nKByXHQeDJvqpWhycNTYj4amrQtfT6-RLfpB-oDvOG3JG3X49TbGn7IkA) This works great by itself, but when put into an app with other reducers, it will error out because right now this reducer only expects one of two action types (LOAD_PREFS_SUCCESS and UPDATE_PREF).

We can get around this error by adding a generic type to our actionType as a catch all. [This however produces flow errors as seen here.](https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AGQPICCAIgPoAKASgKIBiAyqfQKoDCr199oAvKAOQESFGgyZsOXfgG4U6bKGblihACrURdXgKUr1m2jMSIsATwAOAU1ABDVRet8A3olCgA1GasAuUNgBOAJZoAOaIAL6yiJYAHuaw-jhe1jbIWIHo9lbaLm6eDr7JsJB4RGRUdIws7Jz0ADSuoOb+lpAYvoT+-jamADxOpIEAJr4BwSF1oABuNtAArpa+Nmim4QB8EaAAPqC5HsmFDsWKymoaFbQNbsOjWEGhV9OzC0srmzt2DlGx8YmgQ60bHNoDgABTYGxYRa7cI5cKTVLpdBLNIZNBZSwASl4a12jQw8ECWGQAAtQKDEWiAHTJbF7NzIGwYaxCcqiKoSWq+eluUCoTA4NCWeD0LCQxww2S83mU9BU5qtDBUyAJaipEmg8w4vHS6VCkViqEAbXMVMGQwAutpTTN5pYpbrwpiHdKWlg5v40KB9aLxS7QOFGgymdZdGcDNyg7y3R6vU5QFTExCoZMjbK0FThhaUUiM7aFgH-YHpQDIECQd4o24Y56-Ib7Y1A5EgA)

Is there a better way to handle action types in flow?

**Comment by asolove** [comment]
If you can't define a variant for all the actions, maybe try adding a fake extra case to the action variant. That would force you to define a default case in the reducer. Here's one ugly way to do it:

```js
// @flow
const LOAD_PREFS_SUCCESS = 'LOAD_PREFS_SUCCESS';
const UPDATE_PREF = 'UPDATE_PREF';

export type actionType = {
  +type: typeof LOAD_PREFS_SUCCESS,
  prefs: Array<{_id: string, value: any}>
} | {
  +type: typeof UPDATE_PREF,
  id: string,
  value: any
} | {type: "Anything_Else"};

export default (state: {} = {}, action: actionType) => {
  switch (action.type) {
    case LOAD_PREFS_SUCCESS: {
      const newState = {};
      action.prefs.forEach(p => {
        newState[p._id] = p.value;
      });
      return newState;
    }
    case UPDATE_PREF: {
      return { ...state, [action.id]: action.value };
    }
    default:
      return state;
  }
};
```

**Comment by yourfavorite** [comment]
Not pretty, but that seems to produce no errors. Thanks. Going to use the following for now.

```
export type actionType = {
  +type: typeof LOAD_PREFS_SUCCESS,
  prefs: Array<{_id: string, value: any}>
} | {
  +type: typeof UPDATE_PREF,
  id: string,
  value: any
} | { type: "FLOW_CATCH_ALL" };
```

**Comment by yourfavorite** [comment]
I think I spoke too soon. It appeared to be working earlier but I guess I was looking at the wrong window. When I use the action type above and run my app, I get the following error when the application starts. Action type being run is `@@redux/INIT`

```
Uncaught TypeError: action must be one of: {
  type: string;
  prefs: Array<{
    _id: string;
    value: any;
  }>;
} | {
  type: string;
  id: string;
  value: any;
} | {
  type: "FLOW_CATCH_ALL";
}

Expected: {
  type: string;
  prefs: Array<{
    _id: string;
    value: any;
  }>;
} | {
  type: string;
  id: string;
  value: any;
} | {
  type: "FLOW_CATCH_ALL";
}

Actual: {
  type: string;
}


    at module.exports../app/reducers/prefs.js._flowRuntime2.default.annotate (http://localhost:1212/dist/renderer.dev.js:4432:54)
    at eval (webpack:///./node_modules/redux/es/combineReducers.js?:45:24)
    at Array.forEach (native)
    at assertReducerShape (webpack:///./node_modules/redux/es/combineReducers.js?:43:25)
    at combineReducers (webpack:///./node_modules/redux/es/combineReducers.js?:99:5)
    at Object../app/reducers/index.js (http://localhost:1212/dist/renderer.dev.js:4183:48)
    at __webpack_require__ (http://localhost:1212/dist/renderer.dev.js:671:30)
    at fn (http://localhost:1212/dist/renderer.dev.js:89:20)
    at Object../app/store/configureStore.dev.js (http://localhost:1212/dist/renderer.dev.js:4851:17)
    at __webpack_require__ (http://localhost:1212/dist/renderer.dev.js:671:30)
```

**Comment by asolove** [comment]
Oh, looks like you're using flow-runtime. That's going to add an interesting wrinkle to this. I'm not sure it's doable to get both static and runtime checking to work if we can't explicitly specify all the possible actions. Hmm...

**Comment by yourfavorite** [comment]
Ah yes, sorry for not clarifying that. While I see value in both, I think static seems to be a cleaner solution (ie - don't have to include generic type: string). I'll probably just remove flow-runtime from the project for now.

I hope there is an easier usage of both static and runtime with redux in the future.

**Comment by asolove** [comment]
Might also be worth checking if the libraries generating these actions have libdefs that export a type for all the actions they throw. And if not, maybe open an issue or PR to make it happen. Would be nice to be able to say: all the actions from these three libs, plus my custom actions and get solid types.

**Comment by yourfavorite** [comment]
Thanks to @csprance for the tip, but you can use this as a generic type that will still allow you type check your actions for the given reducer:

```javascript
type BaseReduxAction = { type: $Subtype<string> };
```

So in my case the final action type would look like this:
```javascript
export type actionType = {
  +type: typeof LOAD_PREFS_SUCCESS,
  prefs: Array<{_id: string, value: any}>
} | {
  +type: typeof UPDATE_PREF,
  id: string,
  value: any
} | { type: $Subtype<string> };
```

Hope this helps someone else running into this problem!

**Comment by Hypnosphi** [comment]
> `+type: typeof LOAD_PREFS_SUCCESS`

This is actually not different from `+type: string`. This produces no errors in Flow:

```
const x = 'X';
const y: typeof x = 'Y';
```

See https://github.com/facebook/flow/issues/2639

**Comment by Hypnosphi** [comment]
Workaround is described here:
https://github.com/facebook/flow/issues/2377#issuecomment-262894389

In your case it should be
```
const LOAD_PREFS_SUCCESS: 'LOAD_PREFS_SUCCESS' = 'LOAD_PREFS_SUCCESS';
const UPDATE_PREF: 'UPDATE_PREF' = 'UPDATE_PREF';
```
