### ISSUE TITLE
Access of unitialized variable should be prohibited in a closure.

### ISSUE THREAD

**Issue by nmote** [facebook/flow#4739]
Flow v0.53.1 does not error on this code:

```
let bar;
(() => console.log(bar.length))();
```

At runtime (in node) it fails with `TypeError: Cannot read property 'length' of undefined`

Flow correctly issues an error with the following code:

```
let bar;
console.log(bar.length);
```

**Comment by vkurchatkin** [comment]
This is an obvious error. How about this:

```js
let bar;
(() => console.log(bar.length))();
bar = { length: 1 };
```

**Comment by SamChou19815** [comment]
Flow now can detect the OP's issue. The second issue is unsound by design.
