### ISSUE TITLE
Doesn't handle destructure assignment with defaults of disjoint union types

### ISSUE THREAD

**Issue by haf** [facebook/flow#4740]
Here's the question where I solved found your bug for you.

I've opened a new issue because @asolove closed the old one. Feel free to do whatever you want with it, I don't want to talk to you stuck-up people any more and have unsubscribed from notifications.

https://stackoverflow.com/questions/45391364/discriminated-disjoint-unions-in-flow

[![Sample errors][1]][1]

    app/components/commands/types.js:117
    117:   { state: 'state-retries-timeout',
                    ^^^^^^^^^^^^^^^^^^^^^^^ string literal `state-retries-timeout`. Expected string literal `state-initial`, got `state-retries-timeout` instead
     60:   { state: 'state-initial', touched: boolean }

Solution:

```js
  const {
    label,
    className,
    htmlFor,
    children,
    valueState, // = initial, // would fail
    labelOnTop = false,
    grouped = false,
  } = props;
  const vs = valueState || initial; // default here instead of .. above
```

  [1]: https://i.stack.imgur.com/D2HZ2.png

**Comment by asolove** [comment]
I'm sorry you had this problem. It definitely sucks when Flow gives you an error in a confusing place and you have to track it down.

Do you think this solution represents a bug in Flow? It's hard for me to tell whether you're saying flow is doing this wrong or if you think the solution you found means Flow was right and you found a way to make it type check.

**Comment by asolove** [comment]
I'm happy to discuss this further if anyone wants to, but as the author has said he doesn't want to discuss any more, I'm going to call this closed for now.

**Comment by haf** [comment]
It's a bug in flow, like a bug report like this suggests. Why would I create an issue if I have a question (about the same thing none the less) after having you repeatedly tell me to ** off and ask questions at StackOverflow?

You should really consider adding a line telling users about how to increase logging in Flow; in particular what 'line' of functions it analysed to come up with a given 'invalid usage'.
