### ISSUE TITLE
Object.create of valid object: Flow errors despite "any" cast

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4742]
## Description

I already use an `any` cast for the result, so the assignment to the variable is not the issue but what is reported _inside_ the property descriptor.

Flow insists on `value` being present in the property descriptor &mdash; which is not just unnecessary, **it is a Javascript error** (`TypeError: Invalid property descriptor. Cannot both specify accessors and a value or writable attribute`)!

## Code

```javascript
// @flow
'use strict';

type SimpleReadStream = {|  // EDIT: turns out this type is irrelevant, same outcome without it
    ondata?: null | (data: string) => void
|};

const o: SimpleReadStream = (Object.create(
    null,
    {
        ondata: {
            enumerable: true,
            configurable: false,
            //value: null,  // no Flow error with this - but now it's a Javascript error
            get: function () {
                return this.ondata || null;
            },
            set: function (fn: null | (data: string) => void) {
                this.ondata = fn;
            }
        }
    }): any);
```

## Errors

Also, the error message, while it is the same one, looks different in command-line Flow and in Flow-Try for some reason (more context?). Below the command line version.

```
Error: src/main.js:10
                                  v-------------
 10: const o: SimpleReadStream = (Object.create(
 11:     null,
 12:     {
...:
 24:     }): any);
         -^ .ondata of Object.create. Property not found in
                     v
 13:         ondata: {
 14:             enumerable: true,
 15:             configurable: false,
...:
 23:         }
             ^ object literal

Found 1 error
```

## Flow Try

[**Flow Try link**](https://flow.org/try/#0C4TwDgpgBAyglgWzAGwgJQgQwCY2AJywSgF4oBvAHwCgo6oB7AO202EwH4AuKJgV2TIolKAApW7HgGcCcJgHMAlKQB8UAG4M42apQC+AbmrUA9CagAVABbRQkKAGNMTKACNohBA3URsUALRQUpgIHhBSAsDGDswyjDzwSKgYOHiEIaRiAPKuAFYQDsAAdA7pwBCitPT8ggA0VXTkDfR0zBKYPE0t3fQQ-KH4mK6oPAR8EPU9PTFMAGZw8nyDwxA8s5jIUhPNU1Bm6hvjPDXIk7v08hDAa3xMhXDMYspd5z2EwEsuwFZwUkVtbEwwhEJyMrzoejOry21ygs1u90eolmTGOAiEInEgOksgUyhIak02meO3B31+-xYgMyKLB4L0pIhzT0ih4zhAiiMQA)

## Updates / Modifications

- Removing `SimpleReadStream` type changes nothing, type or no type, same result

- It is the same when using `Object.defineProperty` &mdash; [Flow Try example using `Object.defineProperty](https://flow.org/try/#0MYewdgzgLgBCMF4YG8C+BuAUJg8gIwCsBTYKAOgBMiAzASzCIAUAnEAByOagE8AKEADQwA5NRAhhQ5JhiyYRMAFcAtpwCGeADZEAXDCjNFRATLkBzIlD28AlIgB8+gBa0IZMfAA+nmAEYTcjAQlnrUimCktOAwvGB20oGBUC5uHogwYFiBqJioNlhAA)

## Related

- https://github.com/facebook/flow/issues/285
- https://github.com/facebook/flow/issues/133

Opened Feb. 2015... How does anyone use those very basic Javascript functions? It's not even a single error, so more than one Flow error suppressing comment is needed.

Setting `.flowconfig` option `unsafe.enable_getters_and_setters=true` doesn't change anything (I only tried the `Object.defineProperty` example).

**Comment by lll000111** [comment]
I'll close this until I figure out what is left after I fix the `this`-arrow-function issue where Flow is actually right.

**Comment by asolove** [comment]
It looks like `create` is handled explicitly inside Flow's core (it isn't just a libdef like many other JS primitives.) And from trying to read the code, it just handles the value case and doesn't even consider the getter setter case. I don't currently know enough to fix, maybe the core team can comment whether doing that is something they're interested in (/cc @calebmer)
