### ISSUE TITLE
Ignores React prop types for createClass between modules

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#475]
Flowtype only checks prop types for pre-0.13 React classes defined in the same file.
See this short and simplified example below for details.

`welcome.jsx`
```javascript
/* @flow */

var React = require('react');

var Welcome = React.createClass({
  propTypes: {
    name: React.PropTypes.string.isRequired,
  },

  render: function(): any {
    return <b>{this.props.name}</b>;
  },
});

module.exports = Welcome;
```

`main.jsx`
```javascript
/* @flow */

var React = require('react');

var Welcome = require('./welcome');

var WelcomeLocal = React.createClass({
  propTypes: {
    name: React.PropTypes.string.isRequired,
  },

  render: function(): any {
    return <b>{this.props.name}</b>;
  },
});

type PropTypes = {
  name: string,
};

class WelcomeLocalClass extends React.Component<any, PropTypes, any> {
  render() {
    return <b>{this.props.name}</b>;
  }
};


var Main = React.createClass({
  render: function() {
    return <div>
      <Welcome />
      <WelcomeLocal /> {/* only this one fires */}
      <WelcomeLocalClass />
    </div>;
  },
});
```

`flowtype`
```
[...]/main.jsx:32:7,22: React element: WelcomeLocal
Error:
[...]/main.jsx:8:3,11: property name
Property not found in
[...]/main.jsx:32:7,22: type parameter D of React element: WelcomeLocal

Found 1 error
```

Expecting errors should include all three components: `Welcome`, `WelcomeLocal` and `WelcomeLocalClass`.

**Comment by mhagmajer** [comment]
CC @avikchaudhuri, who I believe worked on React support for Flow

**Comment by samwgoldman** [comment]
For the imported Welcome component, I can confirm that prop checking stops working across module boundaries (it does work within the same file).

Regarding your WelcomeLocalClass implementation, I am able to get type checking with this equivalent construction:

```javascript
class WelcomeLocalClass extends React.Component {
  props: PropTypes;
  static defaultProps: {};

  render() {
    return <b>{this.props.name}</b>;
  }
};
```

Curiously, the React.Component subclass does type check across module boundaries. Not sure what's going on there.

**Comment by mhagmajer** [comment]
Thanks @samwgoldman for your response! Prop types in components based on ES6 classes do in fact type check correctly with the syntax you suggested. Interestingly enough if that `defaultProps` declaration is required for this to work.

I also found out that flow is okay with specifying undeclared props, eg.
```javascript
<Welcome noSuchProp="lorem ipsum" />
```
does not raise errors.

**Comment by samwgoldman** [comment]
Yeah, you need to declare `defaultProps` until #398 is resolved.

Regarding undeclared props, that's expected, just as `var x: { y: number } = { y: 1, z: 2 }` is legal.

There is still the issue of `createClass` proptype checking between modules, so please keep this open. :)

**Comment by samwgoldman** [comment]
I tested this against a recent commit on `master` and the last remaining issue here appears to be resolved.

**Comment by samwgoldman** [comment]
This is fixed in 0.13. Please reopen if you continue to have issues after upgrading.

**Comment by josebalius** [comment]
@samwgoldman Maybe I am missing something but how does this work with ES6 classes?

Here is my test case

Test.js
```
/* @flow */
import React from 'react';

class Test extends React.Component {
  render(): React.Element {
    return <div>{this.props.name}</div>
  }
}

Test.propTypes = {
  name: React.PropTypes.string.isRequired
}

export default Test;
```

Test2.js
```
/* @flow */
import React from 'react';
import Test from './Test';

class Test2 extends React.Component {
  render(): React.Element {
    return <div><Test /></div>
  }
}

export default Test2;
```

I get No Errors from Flow.

**Comment by josebalius** [comment]
@samwgoldman any chance to take a look at this :) ?

**Comment by josebalius** [comment]
or should i open a new issue to not clutter this one?

**Comment by samwgoldman** [comment]
@joelbeales Yeah, open up another issue. I don't think Flow even processes the propTypes data for class-based components, favoring annotation with Flow types instead.
