### ISSUE TITLE
Flow stuck at "flow is still initializing"

### ISSUE THREAD

**Issue by davidbarker** [facebook/flow#4753]
I've been trying to set up Flow on a reasonably large project, but it seems to hang when running `flow`. (macOS, Flow version 0.53.1)

```
Launching Flow server for [...]
Spawned flow server (pid=8116)
Logs will go to /private/tmp/flow/[...].log
Launching Flow server for [...]
Spawned flow server (pid=8938)
Logs will go to /private/tmp/flow/[...].log
Launching Flow server for [...]
Spawned flow server (pid=9967)
Logs will go to /private/tmp/flow/[...].log
flow is still initializing; this can take some time. [parsing] \
```

I left it to run for over 10 minutes, but had to stop it as it seemed to use 15GB of my disk which didn't become free until I restarted.

My `.flowconfig` is as follows:
```
[ignore]
.*node_modules/.*
.*public/.*
.*vendor/.*
[include]

[libs]

[lints]

[options]
```

I got it working on a much smaller project. It took about 30 seconds to initialize and then all was fine. It doesn't seem to want to run on this larger project, however.

**Comment by maicol07** [comment]
I have the same issue

**Comment by SamChou19815** [comment]
The issue was likely fixed a long time ago
