### ISSUE TITLE
False error when having the same successive object names in a tree and using it in a function

### ISSUE THREAD

**Issue by jsiebern** [facebook/flow#4755]
Hi,

I'd like to report a bug I encountered today. When I have an object structured like `event.data.data` flow at first determines its type correctly ( in my example code: `Array<string>` ), if I try to use it inside a function though, flow throws an error. Oddly enough, if I reference it outside that function and assign it to a new variable, it suddenly will work inside the function.

I have used https://flow.org/try for the following code so its replicable:

```javascript
/* @flow */

// -- Attendee Names

declare type PM$Attendee = {
    name: string,
    color: string,
};

declare type PM$ServerUpdate$Event$AttendeeNames$Mode$Data = {
    mode: 'add_data' | 'remove_data',
    data: Array<PM$Attendee>,
    num: number
};
declare type PM$ServerUpdate$Event$AttendeeNames$Mode$Simple = {
    mode: 'add' | 'remove',
    data: Array<string>,
    num: number
};
declare type PM$ServerUpdate$Event$AttendeeNames$Mode = 
    | PM$ServerUpdate$Event$AttendeeNames$Mode$Simple
    | PM$ServerUpdate$Event$AttendeeNames$Mode$Data
;
declare type PM$ServerUpdate$Event$AttendeeNames = {
    type: 'ATTENDEE_NAMES',
    data: PM$ServerUpdate$Event$AttendeeNames$Mode
};

let testData: Array<PM$Attendee> = [
  { name: 'test', color: '#000000' },
  { name: 'test2', color: '#000000' }
];

const event: PM$ServerUpdate$Event$AttendeeNames = {
	type: 'ATTENDEE_NAMES',
  	data: {
    	mode: 'remove',
      	data: [
        	'test2'
        ],
      	num: 1
    }
};


switch (event.data.mode) {
  case 'remove': {
    	
    // Doesn't work
    testData = testData.filter(attendee => event.data.data.indexOf(attendee.name));
    
    // Does work
    const data = event.data.data;
    testData = testData.filter(attendee => data.indexOf(attendee.name));
    
  	break;
  }
}
```
I think it then sees the second in `event.data.data` basically as the first for some reason. Am I doing something wrong or is this really a bug?

Thank you, love flow so far :)

**Comment by asolove** [comment]
This is a confusing but actually correct behavior called refinement invalidation. You can read more about that at: https://flow.org/en/docs/lang/refinements/

Basically, since flow doesn’t know when the anonymous function will be called, it doesn’t know that th variable won’t have been changed before then. So it has to “forget” the more specific information it learned from the switch test and assume the variable may have changed to be anything that its type allows.

**Comment by jsiebern** [comment]
I never would have guessed that, thank you so much for clearing this up & your efforts for writing this detailed answer - it is much appreciated!
