### ISSUE TITLE
Missing props added by React.cloneElement

### ISSUE THREAD

**Issue by k15a** [facebook/flow#4756]
We are using some weird containers at work which will pass props to the children implicitly. Every time, we use such a container Flow warns that the components are missing some props which are added by React.cloneElement from the parent. [Example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA0wCeYWcACsWOgLxwDeNASFwALYABsAJpQB2ALkxUYAOgDCoyTICCUKMgYAebHmUBRMVhBZpMfY2YQCcAEIA+FwBoaAXzq4I01HhNOB4ACl44EXEpKzgveXYITgBKEJc+QUoYAFcoaThQwQF9CWAANxcigV4jfFV1GOklEGQwUKiNK3dIhrSMgQGBWuVcMX8sMwsrGHaG7v5BgeR5AEZPRYEAI3kAJnXBr2Sqw58B-QB6UorBI58aPwD4JxCCiORuzbj5N-lpbJBNlgoB9fv9AVA4slQQCgX0FllcvlkHAANRwTbeXz+QLOMTZT5hVJcSrFTQk4rPc4ki5kmhAA)

Is there a good way to stop Flow from warning about missing props?

```js
import * as React from 'react'

type Props = {
	children: React.ChildrenArray<React.Element<typeof B>>,
}

const A = ({ children }: Props) => {
	return (
		<div>
			{React.Children.map(children, child => {
				React.cloneElement(child, {
					a: 1,
					b: 2,
				})
			})}
		</div>
	)
}

const B = ({ a, b }: { a: number, b: number }): number => {
	return a + b
}

const Blub = () =>
	<A>
		<B />
	</A>
```

**Comment by mimccio** [comment]
Same issue.

**Comment by mimccio** [comment]
Looks like it works if you pas the children element as the children prop

```javascript
<Container children={Element} />
```

rather than 

```javascript
<Container>
    <Element />
</Container />
```

- https://github.com/facebook/flow/issues/1820
- https://github.com/facebook/flow/issues/1355
- https://github.com/facebook/flow/issues/892

**Comment by danrot** [comment]
The only workaround I've found so far is to make these props optional with the question mark. Is there no better way currently to fix that?

**Comment by SamChou19815** [comment]
We won't support arbitrary dynamic patterns like this.
