### ISSUE TITLE
Union type(Enum) in property cannot be inferred when compare or switch

### ISSUE THREAD

**Issue by zaaack** [facebook/flow#4757]
Here is flow: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIIGNkBLWAO1AF5QBvRUUNLALlACIAxAUQBUBhACQD6ABQ4A5ACIBJUQHEWoAD6tOvQQGUAqjx4c1a+Uvbd+AtjkkAZDQCUOLRAF9EiSAFcSBYmQBOmACaueJjeABQAzsgAhsiY5FQOADSgkZ6kzPhEpACU1LSghJCgISmZJAB0DNjk1aAA5JG1WTR0oE50YfCEyHgAFkUlXhUYmDnNLXiRYdi1KiYiEtIytYx5LaAgZZurLb7Irt5kEdGY2xNTdbOCZpaEtsvbdBtba3S7+4dRMXltoG8HoEcvg4gA

Here is typescript: http://www.typescriptlang.org/play/index.html#src=type%20Action%20%3D%20%7B%0D%0A%20%20type%3A%20%22FETCH_PENDING%22%20%7C%20%22FETCH_SUCCESS%22%20%7C%20%22FETCH_FAILURE%22%0D%0A%7D%0D%0A%0D%0Afunction%20reducer(state%3D%7B%7D%2C%20action%3A%20Action)%20%7B%0D%0A%20%20if%20(action.type%20%3D%3D%3D%20'a')%7B%0D%0A%20%20%20%7D%0D%0A%20%20switch%20(action.type)%20%7B%0D%0A%20%20%20%20case%20'FETCH_PENDING'%3A%0D%0A%20%20%20%20%20%20%2F%2F...%0D%0A%20%20%20%20%20%20return%20state%0D%0A%20%20%20%20case%20'FETCH_FAILiRE'%3A%0D%0A%20%20%20%20%20%20%2F%2F...%0D%0A%20%20%20%20%20%20return%20state%0D%0A%20%20%7D%0D%0A%20%20return%20state%0D%0A%7D

**Comment by TrySound** [comment]
@zaaack It's inferred. And code is correct. Flow doesn't throw on unreachable code yet.

**Comment by zaaack** [comment]
@TrySound  see this: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQQMYoCWsAdqALyKigA+oA3qOtgFygBEAYgKIAqAYQASAfQAKPAHIARAJKSA4hwA0oALZYUAQ3YMiAE3YBnFACcipAOYBfUNep1GzTFnbd+wkQGUAqgIE8Xl4qoBhaaHBahk7EKNCuoCbmVnZ2DvRMLAnugqJcuLIAMrIASjwhWKamsKa66lhGRlqWCUkWlqn2iJAArqSEJOSmWPo9+JUAFCZaKFgUDNaqWgNk7ATEZACUjIgAkEbwRCj4ABagE8sbpAB0WdsMe7v4WkY4AOS8ueJScopvrA4aDRLoNrhptNcDI9diBrnDocMUD1TORprNHs9XqAPh48gVCj4yv9AUDdk8yEZYPFrnBLBcVjdKtVTGCGk0WptobD4WTdojkajtOjdvY+ZoBYkhVhENYgA

**Comment by zaaack** [comment]
Ref to this issue might be relevant: https://github.com/facebook/flow/issues/4347

**Comment by TrySound** [comment]
Flow performs type checking, but does not compare literals there. Correct, because that code will never fail in runtime, because such code is unreachable.

**Comment by zaaack** [comment]
@TrySound Got, but in the referenced issue flow do compare literals, just not as good as typescript do.

**Comment by TrySound** [comment]
Yeah, that's weird.
