### ISSUE TITLE
Problem with dynamic code

### ISSUE THREAD

**Issue by rpominov** [facebook/flow#476]
I'm having a problem with annotating following piece of code:

```js
type Comparator<T> = (a: T, b: T) => boolean
type Callback<T> = (x: T) => void

function skipDuplicates<T>(comp: Comparator<T>, cb: Callback<T>): Callback<T> {
  var hasPrev = false
  var prevX
  return (x) => {
    if (!hasPrev || !comp(prevX, x)) {
      hasPrev = true
      prevX = x
      cb(x)
    }
  }
}
```

Flow outputs:
```
$ flow

/Users/anon/projects/my/fluce/src/_.js:72:22,35: function call
Error:
/Users/anon/projects/my/fluce/src/_.js:70:7,11: undefined
This type is incompatible with
/Users/anon/projects/my/fluce/src/_.js:68:1,78:1: some incompatible instantiation of T

Found 1 error
```

As I understand Flow can't infer type of `prevX` based on value of `hasPrev` flag. 

I tried following, but get a error `"identifier T Could not resolve name"`:
```js
var prevX: ?T = null
```

Is there a way to annotate/rewrite a code like this so it would correctly type check?

Thanks!

**Comment by samwgoldman** [comment]
The issue here is that flow (correctly, afaict) infers `prevX` to be `?T`, but `Comparator<T>`'s first argument is non-optional. You can fix this by making it optional, but that might pose a problem if the concrete type of `T` ends up being a maybe type itself.

**Comment by samwgoldman** [comment]
FWIW, this issue doesn't really have to do with generic types or closures. It's a refinement issue. Flow doesn't recognize the relationship between `prevX` and `hasPrev`. I'm not sure it's realistic for flow to recognize this, but maybe someone cleverer than I knows a way.

**Comment by rpominov** [comment]
I see, if I change comparator type to `(a: ?T, b: T) => boolean` it indeed works! But I actually need the relationship between `prevX` and `hasPrev` to be recognized. But I agree this probably unrealistic for static analysis.

Thank you for clarifications!

**Comment by rpominov** [comment]
Still have an issue with it in the calling-side:

```js
type Comparator<T> = (a: ?T, b: T) => boolean
type Callback<T> = (x: T) => void

function skipDuplicates<T>(comp: Comparator<T>, cb: Callback<T>): Callback<T> {
  var hasPrev = false
  var prevX
  return (x) => {
    if (!hasPrev || !comp(prevX, x)) {
      hasPrev = true
      prevX = x
      cb(x)
    }
  }
}

var cb = skipDuplicates(
  (a, b) => Math.round(a) === Math.round(b),
  (x) => console.log(x)
)
```

![image](https://cloud.githubusercontent.com/assets/825702/7870640/645aec48-0593-11e5-9db8-3d7b12135958.png)

What is the general advise in cases like that, when flow can analyze dynamic code? Can I tell flow somehow what type `prevX` has in the expression `!comp(prevX, x)`?

**Comment by samwgoldman** [comment]
Well, now you've explicitly annotated that first parameter as a maybe type,
so you need to check if it's null first—You shifted the burden onto the
call site. Can you see how that follows from the type signature?

The ideal type of comparator should not have a maybe type in it, but you'll
have to reformulate the definition of skipDuplicates to make that possible.
I haven't spent any time trying to write a skipDuplicates that flow
considers type safe with the ideal comparator type, but I'm confident it's
possible.

**Comment by rpominov** [comment]
I see, but is there any general solution for that king of issues? Can it be solved by adding an annotation, something like `!comp((prevX: T), x)` (won't work)?

**Comment by rpominov** [comment]
Or perhaps any plans to add such feature?

**Comment by samwgoldman** [comment]
Since flow believes prevX to be `?T`, you can't use a type cast because down-casting is not supported and will not be supported, because it isn't sound.

There are two possible solutions: flow can become intelligent enough to recognize the dependency between hasPrev and prevX -or- you can reformulate the function differently s.t. flow infers the correct type.

**Comment by samwgoldman** [comment]
Here's some code that will type check. Not the most straightforward, I admit!

```javascript
/* @flow */

type Comparator<T> = (a: T, b: T) => boolean
type Callback<T> = (x: T) => void

type Maybe<T> = (none: () => void, some: (x: T) => void) => void;

function skipDuplicates<T>(comp: Comparator<T>, cb: Callback<T>): Callback<T> {
  var prev  = (none, some) => none()
  return (x) => {
    prev(
      () => cb(x),
      (prev) => {
        if (!comp(prev, x)) {
          cb(x)
        }
      }
    )
    prev = (some, none) => some(x)
  }
}

var cb = skipDuplicates(
  (a, b) => Math.round(a) === Math.round(b),
  (x) => console.log(x)
)
```

**Comment by rpominov** [comment]
Not straightforward indeed, I'm still in the process of digesting it :)

Easier solution would be to change `if` expression to `!hasPrev || (prevX !== undefined && !comp(prevX, x))`, it will be repetitive for programmer, but Flow will "get" what going on.

> Since flow believes prevX to be ?T, you can't use a type cast because down-casting is not supported and will not be supported, because it isn't sound.

I guess, this is what I'm actually looking for. Could you briefly explain why this is a "bad thing", or direct me to some resources from which I could learn about it?

**Comment by samwgoldman** [comment]
Well, downcasting in this case is what you want, because you're smarter than the type inference engine and you know what the precise type is. In general however, downcasting could be wrong and lead to runtime errors.

```
var foo: number =  ("not a number" : number);
foo.toFixed(); // BOOM
```

**Comment by rpominov** [comment]
Same can be achieved with `any`.

```
var foo: number =  ("not a number" : any);
foo.toFixed(); // BOOM
```

Having an option between downcasting and `any` might be better than having only `any`, in my opinion. In both cases programmer take responsibility, but with downcasting Flow still we be able to perform some checks at least.

**Comment by samwgoldman** [comment]
Yeah, `any` is the only sanctioned escape hatch. If you really *really* want to downcast, you can:

`!comp(((prevX : any ) : T), x)?` or similar.

In this case, it's pretty clear that this is actually correct. I agree in general with programmer responsibility, but I think that hard casting like this should be discouraged, and disallowing downcasting indicates that you really really shouldn't do it unless you have a good reason.

Even in this instance, I would sooner rewrite `skipDuplicates` than do a hard cast through `any`, even if it is sound to do in this instance.

**Comment by rpominov** [comment]
Oh, cool. And I like that it looks explicit. I may will use this when stuck harder :)

A side question, though:
![image](https://cloud.githubusercontent.com/assets/825702/7871949/5e74a068-059c-11e5-865c-94fa52f48ece.png)

looks like it not allowed to use `T` in function body. Is there any plans to add this feature?

**Comment by samwgoldman** [comment]
Yeah, that is a separate issue. Sorry that you keep running into stuff here. See #160 for that specific issue. In this case, it should work to just cast to any, so you don't need to reference T at all.

**Comment by rpominov** [comment]
Ok, thank you!

**Comment by samwgoldman** [comment]
Glad we found something that works! I should have thought of `any` sooner :)
