### ISSUE TITLE
Does not support Array.prototype.includes

### ISSUE THREAD

**Issue by Palisand** [facebook/flow#4761]
[flowtry-demo](https://flow.org/try/#0PTAECcFMFsHsDdKgC4AsCWBnUAzArgHYDGy6sBoAhgQCYqqRSgDu6ANm6AEZIGyiNwscJgBQ+YqXK5YsAEKUaACi6VwALlAAiVQC8toAD7aAjngAeB41rMWrpvHn0BKUAG9RoCJGR5wFAG0dSn0AGgdLAF0AOnRiNjwaSEwVNVcAflAlTy93HNzuEM0ARlD83LNzTQAmMoKAXwDVcEic101sgo8Cr1sq0ABmOp7bXU0AFmGvRubWr2dRetFxQhIyChxZAHFZZWbNYP0jCPsbR0tjs6ctV27vX39C8FAAXjftPStjZtf3s4vMp1cncCnoSlMKhYahCZmo5qB2llyiDIVDBhDeo4xqBJuVYS02otREA)
``` javascript
// remove this function and there will be no errors
function fooBad(bar: "baz" | "qux" | "quux" | "quuz") {
  return ["baz", "qux"].includes(bar) ? (  // flow does NOT understand
    {
      baz: 1,
      qux: 2,
    }[bar]
  ) : (
    {
      quux: 3,
      quuz: 4,
    }[bar]
  )
}

function fooGood(bar: "baz" | "qux" | "quux" | "quuz") {
  return bar === "baz" || bar === "qux" ? (  // flow understands just fine
    {
      baz: 1,
      qux: 2,
    }[bar]
  ) : (
    {
      quux: 3,
      quuz: 4,
    }[bar]
  )
}

```

**Comment by asolove** [comment]
Hmm, I think it’s unlikely this would get implemented. Note that it could only possibly work for array literals with string literals inside. Calling includes on a variable or anything else that does calculation at runtime would prevent us from doing any analysis at type checking time. Since flow can only check static sets of cases anyways, using array includes doesn’t buy you much over the equality checks.

**Comment by Palisand** [comment]
@asolove My only reason for preferring `.includes` is that I don't have to repeat `bar ===`. For this posted example, I used a shorter list of unioned literals than my real-world scenario. Is there an alternative that provides the conciseness of using `.includes` but can be understood by flow?

**Comment by asolove** [comment]
I don’t think so, sorry. I often break these into multi line if conditions if there are a bunch of them. Do you mind if I close this issue?

**Comment by Palisand** [comment]
It's all good, thanks for the info.
