### ISSUE TITLE
Impossible to use Flow without having to constantly restart the server

### ISSUE THREAD

**Issue by ghost** [facebook/flow#4769]
There are already a couple of open issues on the topic: #4278 #2789 and #4248 

I'm running on a mac, and none of the proposed solution there worked for me. This means that I simply can't use Flow at all. Restarting the server on every file save is just not feasible.

What I would like to know is if this issue is fixable, and if I should bother investigating more.

**Comment by asolove** [comment]
Can you post some details about your set? OS version, flow version, etc.? Also anything else relavant to the environment: running in a VM? docker? etc. 

There's something specific going on because many folks use flow on Mac without this problem, so I think we need more info to track it down.

**Comment by piotryordanov** [comment]
Apology for the lack of information. 

So, I'm running it on `MacOs Sierra v10.12.5` with `flow 0.54.0`. My node version is `v.8.4.0`.
I'm not running any VM, docker or other stuff.

I installed flow globally and locally using both npm and yarn, and tried running it from both local and global locations, with the same result :(

**Comment by Brianzchen** [comment]
3 years late, but is this still an issue? Flow tends to restart if certain things are changed. in particular, files in your lib directory (flow-typed) or changes to `.flowconfig`. Simply changing source code should not cause a restart.

**Comment by SamChou19815** [comment]
The issue was likely fixed a long time ago.
