### ISSUE TITLE
Missing declarations for WebGLRenderingContext

### ISSUE THREAD

**Issue by motiz88** [facebook/flow#477]
I intend to submit a PR with my own declarations soonish. I'm auto-generating them from https://www.khronos.org/registry/webgl/specs/latest/1.0/webgl.idl.

**Comment by gre** [comment]
@motiz88 have you put your own declarations somewhere? any update on getting this in?
Thanks :)

**Comment by gre** [comment]
@motiz88 i've submitted a PR
