### ISSUE TITLE
React.isValidElement not smart enough to escape `null` and `undefined` values

### ISSUE THREAD

**Issue by EvHaus** [facebook/flow#4775]
Using Flow `0.54.0`, it appears that `React.isValidElement` isn't smart enough to ensure that `null` and `undefined` values aren't escaped. Consider this code (https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqgQCe2amAAKzbGQAqw0QF4wAb1RgAkHQAW6GABNOAOwD8ALipcCAOgBycXaNQBffnRjkKAWUEBhFrgPUBkTUAB4EgboUNPRWvjhwAUEAPBJwUrIiAHzKqmCG9nhgABQAlGbRDDZ2oipg6nQJZERKWjr6gY5gigTaZJbYkmR8qGqcBACueAbmMZbe2nqGllD4AKL0mkWti4EANMXUMNSYgQTlFlX2JV3ZKmpq6FDFFVboZABqJDDouqtHJ0EiodjqcStcxpNpgZxjAYHw6gj1I8Dv9Tv1BpYyCxqD10AYAOZdeTdPDjajgnGQsBJXToABuYGAmT4akREKm1LI2BI0yZ8IRjhKuWcjiAA):

```javascript
// @flow

import * as React from 'react';

type PropsType = {
 	children?: React.Node 
}

class MyComponent extends React.Component<PropsType> {
  render (): React.Node {
  	const {children} = this.props;

	return React.Children.forEach(children, (element: React.Node) => {
		if (React.isValidElement(element)) return null;

		// Flow throws an error on this line even though it's completely safe
		if (element.props.something === true) return <div />;

		return <span />;
    })
  }
}
```

Flow throws:

```
14:       	if (element.props.something === true) return <div />;
                       ^ property `props`. Property cannot be accessed on possibly null value
14:       	if (element.props.something === true) return <div />;
               ^ null
```

However, this is not a valid error since `isValidElement` will do a check for `null` values and return `false` in that case, so by the time Javascript reaches line 14 there is no way that `element` would be `null`. So the Flow type error is a false positive.

**Comment by FezVrasta** [comment]
So really nobody ever cared to drop a comment on this? Is there some solution for this problem or we just have to monkeypatch it?

**Comment by apsavin** [comment]
Well, I think it's possible to annotate this function so flow will know that it returns `false`  for `null` and `undefined`.

**Comment by Brianzchen** [comment]
Will close this in favour of #6392 to consolidate any discussion and which covers the wider issue of `React.isValidElement` not supporting type refinement at all.
