### ISSUE TITLE
React.Children handlers shouldn't expect fragments

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#4781]
@calebmer looks like the added typings for Children doesn't handle some common cases well. Say I want to do something only with element children (filtering out strings, nulls etc.): 

```
import * as React from 'react';

function handleChildren(children: React.Node) {
  React.Children.forEach(children, child => {
    if (child && typeof child === 'object') {
  	  (child: React.Element<*>);
    }
  });
}
```

Unfortunately this leads to an [error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqlACuAOwbo4wsAAsSwgCYxqAYSnoYczsIAUdVes0AuKlwIA6AHJw51AJRgA3qjDH6ZlWo3VhpqPgCi9FI6ep7CADRguh5gALwAfA5OzmDoUGDB0QBkmWAEAJ7Y1HBpUeqxMTHscABGAFbU3HaOzgCQzhnqRjSupn6KmF4EADwgcTZ8yWAAvklT46gzQA) because the infered type of `child` is `React.Node`, which includes `Iterable<React.Node>` (fragment). In fact, it never happens, because `React.Children` flattens all the nested arrays

Related: https://github.com/facebook/flow/pull/4340

**Comment by Brianzchen** [comment]
Fixed in current version, tested in 0.132.0
