### ISSUE TITLE
$Values should be a parallel of $Keys

### ISSUE THREAD

**Issue by joewalker** [facebook/flow#4784]
I'd expect `$Values<something>` to work as a parallel of `$Keys<something>`, but it appears to be much weaker.

In this example `k2` is constrained by the keys of `LABEL` and `v2` by the values. `v2` is allowed to be any string where `k2` is only allowed to be `'a' | 'b'`.

```
export const LABEL = {
  a: 'A',
  b: 'B',
};

type LabelKeys = $Keys<typeof LABEL>; /* 'a' | 'b' */

const k1: LabelKeys = 'a';

// Expected error - there is no key 'x'
//const k2: LabelKeys = 'x';

type LabelValues = $Values<typeof LABEL>; /* expecting 'A' | 'B' */

const v1: LabelValues = 'A';

// Expected error - there is no value 'X'
const v2: LabelValues = 'X';
```

I'm using Flow 0.54.0. flow.org/try link:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwBjOAOwGdiAZAQQCEBRGsAXjAG9UwwBDAFxgA5HWEAaHmABGQ4QwmoAvgG50hAJ44MYGn2kYYAaQwbK7MABITZgDybtcKLsYsAfCrCgRfYWAA+ItJ+KOhkVMQA1gCMQnoGxqbmHMK+aqjAwGBMuBgkhBgAJmAY+PgEYAC0YIQAFqU6AJbm5HBgkaYiWMIZwOHU7QBMcfqGNsldwukOOvGGAGp8MACuGBOWiytr9loYTi7MNB5e4Nja+Y3kAOYiYgEiCshoqP3EAG6xuqMwm6sTolN0Jlsrl8kUSmUKtU6g0wM0wK0wG8lqsRAANHqvJHDL4JX5rCzCDFqIA

**Comment by vkurchatkin** [comment]
Type of `LABEL` is inferred as `{ a: string, b: string }`, hence this behaviour.

**Comment by bradennapier** [comment]
And thus we need a way of changing that behavior.  We HAVE to use typeof here but we don't want that, we want to use the actual types here.

**Comment by villesau** [comment]
@vkurchatkin is there some other way to achieve the desired behaviour then? If not, I wouldn't say this issue should be closed. That's something our team has been struggling with too.

**Comment by joewalker** [comment]
I suppose what @vkurchatkin is saying is that `typeof LABEL` can't easily be inferred as `{ a: 'A', b: 'B' }` because (to use the example above) `LABEL.a = 'X';` is allowed within flow's type system.

It's not obvious that `$Values` isn't a parallel of `$Keys` though, even if they can't be made to parallel each other perhaps more could be done to explain the asymmetry.

**Comment by villesau** [comment]
Yep true. But that practically also makes the $Values pretty much useless. I can't think of too many use cases where inferred string type is enough for cases where $Values is meant to be used.

**Comment by vkurchatkin** [comment]
This is what works on master branch:

```js
const T = Object.freeze({
  a: 'A',
  b: 'B',
});

type Enum = $Values<typeof T>;

('X': Enum) // Error
```
