### ISSUE TITLE
flow-upgrade: Default import with named imports can be invalid and break

### ISSUE THREAD

**Issue by valscion** [facebook/flow#4786]
Hi! We're in the process of upgrading from 0.52 to 0.53. Thank you SO MUCH for creating the codemods to ease the upgrade!

I came across one case that causes quite a lot of flow errors in our codebase after running the codemod. I have a strong feeling that we could fix these with the upgrade codemods themselves.

We've got a few components that both import `React` from the default export as well as import `Component` as a named export. Like so:

```js
/* @flow */
import React, { Component } from 'react';

export default class SomeComponent extends Component {
  props: {
    children?: React$Element<*>
  };
  // ...
}
```

Currently the codemod outputs code that looks like this:

```js
/* @flow */
import React, { Component } from 'react';

export default class SomeComponent extends Component<{
  children?: React.Element<any>
}> {
  // ...
}
```

This causes type checks to fail, as we now have `import React from 'react';` instead of `import * as React from 'react';`. Here's an example error we've got:

```
Error: app/assets/javascripts/common/components/ContentHider.js:25
 25: export const createContentHider = (HiderComponent: React.ComponentType<*>) => {
                                                        ^^^^^^^^^^^^^^^^^^^^^^ ComponentType. Property not found in
                              v-
233:   declare export default {|
234:     +DOM: typeof DOM,
235:     +PropTypes: typeof PropTypes,
...:
247:   |};
       -^ object type. See lib: /private/tmp/flow/flowlib_3e2ef16f/react.js:233
```

And this is because the original source has this code:

```js
/* @flow */
import React, { Component } from 'react';
// ...
export const createContentHider = (HiderComponent: React.ComponentType<*>) => {
```

I can see that the existing snapshots also have this very same case with probably incorrect implementation:

https://github.com/facebook/flow/blob/bafcbde69953a0ae2d34dea5fadfdb03517b8a42/packages/flow-upgrade/src/upgrades/0.53.0/ReactUtilityTypes/__tests__/__snapshots__/codemod-test.js.snap#L31-L43

Specifically, here the `React.Element` won't be discovered by flow correctly, as the default export of `react` package does not have the `Element` property.

---

There are likely many ways to fix this case. I've outlined some suggestions below and would appreciate your input on their viability and what you'd prefer to see.

As a reminder, here's the input to these suggestions:

```js
/* @flow */
import React, { Component } from 'react';

export default class SomeComponent extends Component {
  props: {
    children?: React$Element<*>
  };
  // ...
}
```

## A. Remove the named imports and fetch them directly from `React.X`

```js
/* @flow */
import * as React from 'react';

export default class SomeComponent extends React.Component<{
  children?: React.Element<any>
}> {
  // ...
}
```

```diff
-import React, { Component } from 'react';
+import * as React from 'react';
```

```diff
-export default class SomeComponent extends Component<{
+export default class SomeComponent extends React.Component<{
```

# B. Add explicit type imports for new types

```js
/* @flow */
import React, { Component } from 'react';
import type { Element as ReactElement } from 'react';

export default class SomeComponent extends Component<{
  children?: ReactElement<any>
}> {
  // ...
}
```

* Add new line: `import type { Element as ReactElement } from 'react';`
* Output `ReactElement<any>` instead of `React.Element<any>`

This would naturally look ahead to what `React.X` helper types are used and then import those specifically.

We don't have to prefix the imported types with `React` but I think it would make the new code more clear.

# C. Import new types together with the existing import

This is practically the same as suggestion B but with only one `import` line:

```js
/* @flow */
import React, {
  Component,
  type Element as ReactElement
} from 'react';

export default class SomeComponent extends Component<{
  children?: ReactElement<any>
}> {
  // ...
}
```

* Add `type Element as ReactElement` to the list of named imports from `react` package
* * Output `ReactElement<any>` instead of `React.Element<any>`

---

I'd be open to taking a crack at modifying these codemods to support whatever we'd like to see. I've played around with codemods and ASTs before but haven't really used them to more complex scenarios. I'd appreciate any implementation suggestions :relaxed:

Thanks for your time! I'm looking forward to analyzing the new flow errors we now have. I might even discover new cases which the codemod could handle if just implemented. Do you think it's a good idea for me to open issues like these if I discover related cases?

**Comment by valscion** [comment]
I managed to implement strategy A in #4792 that would fix this issue. I went with that, because it seemed to be the most straightforward implementation-wise plus now the modified code looks similar as documented over at https://flow.org/en/docs/react/components/

**Comment by siladu** [comment]
I'm getting flow problems when using 
```javascript
import React, { Component } from 'react';
```
with 
```javascript
export default class SomeComponent extends Component<Props, State>
```
It is fixed when you do this instead:
```javascript
export default class SomeComponent extends React.Component<Props, State>
```
However, without flow, the two class declarations should be identical, so it seems to me that flow should support both these ways as well.

Thanks for #4792 @valscion, however just updating the codemod would not fix things in my use case. It seems like flow should support this directly.

**Comment by valscion** [comment]
@siladu strange, both of your  pieces of code work for me, although I do use a bit old version of flow.

Your issue seems to be different compared to what I have here. Could you perhaps create your own issue, and maybe create a small reproduction case for your error? It does seem strange if the error you have is really there.
