### ISSUE TITLE
Cannot use inline `export default class X` ES6 syntax 

### ISSUE THREAD

**Issue by pveyes** [facebook/flow#479]
Import and export statements work fine, but I cannot use inline export default syntax

This will fail:
```js
import React from 'react';

export default class X extends React.Component {

}
```

But this worked
```js
import React from 'react';

class X extends React.Component {

}

export default X;
```

Not really big deal, but fix will be nice (y)

**Comment by samwgoldman** [comment]
Yeah, no reason we can't support this. I know @jeffmo has some WIP that makes big changes to modules, so I'm hesitant to look into fixing it right now. Jeff, can you weigh in?

**Comment by jeffmo** [comment]
Yea I think this is unrelated to my changes and is just a small parser TODO IIRC...

I'm going to go HAM on my modules stuff today, so if I still have the time and energy later maybe I can tackle this too.

(I'd be happy to defer to someone else if they want to take a crack at this, though -- I think it should be fairly simple)

**Comment by samwgoldman** [comment]
I'm going AFK in a few hours, but yeah, I'm interested in tackling this if you don't get to it. Just let me know if you fix it. :)

**Comment by jeffmo** [comment]
FYI I haven't gotten to this yet and need to take a break for a bit, so I'll leave it for you today in case you want to grab it.

I should be back around later tonight or tomorrow if you haven't had a chance to do it yet -- I don't think it'll take too much work, though.

**Comment by samwgoldman** [comment]
#485

**Comment by mroch** [comment]
@samwgoldman, can you confirm and close?

**Comment by samwgoldman** [comment]
@mroch I can't close this, but I can confirm that this behavior is now functioning correctly.
