### ISSUE TITLE
Issue calling possible undefined value even after test.

### ISSUE THREAD

**Issue by adamdonahue** [facebook/flow#4793]
Why is this failing validation?  Seems like an error:

Type:

```javascript
type Column = {|
    aggregator?: Array<Row> => Value
|}
```

Code:

```javascript
columns.map(column => {
  if (!column.aggregator)
    return;
  const summaryValue = column.aggregator(map(rows, column.columnName));
  // ...
})
```

I get 
```
call of method `aggregator`. Function cannot be called on possibly undefined value.
```

I can't seem to get around this unless I make the type non-optional, but it _is_ optional.

**Comment by adamdonahue** [comment]
Annoyingly, this works:

```javascript
const aggregator = column.aggregator;
const summaryValue = aggregator(map(rows, column.columnName));
```

**Comment by jcready** [comment]
I believe this is due to refinement invalidation when calling the inner-most `map()` function. Since that is evaluated before the call to `column.aggregator()`, flow doesn't know if the `map()` function sets `column.aggregator` to `undefined` so it invalidates your prior null-check.

**Comment by adamdonahue** [comment]
Thanks.  That keeps biting me.

**Comment by adamdonahue** [comment]
Actually, taking a closer look at this, how could the map update `column.aggregator`?  It doesn't receive `column` as a parameter.

**Comment by asolove** [comment]
It’s not that the map could update it, but that for all flow knows, the closure passed to map may be called asynchronously later. When that happens arbitrarily in the future, other code may have changed the variable’s value. This is definitely kinda lame since in practice that may not happen, but it is necessary for flow to guarantee correctness when closures capture a variable. I know there is a proposal for a way to mark certain common functions that receive closures, like map, as special and always called synchronously.

**Comment by wichert** [comment]
I have another example of this:

```javascript
      if (this.onSessionChange) {
        this.onSessionChange(privateToPublicSessionInfo(info));
      }
```

which results in:

```
 36:         this.onSessionChange(privateToPublicSessionInfo(info));
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `onSessionChange`. Function cannot be called on possibly null value
 36:         this.onSessionChange(privateToPublicSessionInfo(info));
             ^^^^^^^^^^^^^^^^^^^^ null
```

Using an extra assignment inside the `if` does not work:

```javascript
      if (this.onSessionChange) {
        const d = privateToPublicSessionInfo(info);
        this.onSessionChange(d);
      }
```

That still generates the same error. Moving the inside before the `if` does work:

```javascript
      const d = privateToPublicSessionInfo(info);
      if (this.onSessionChange) {
        this.onSessionChange(d);
      }
```
