### ISSUE TITLE
Expose "set object key" in a utility type?

### ISSUE THREAD

**Issue by mkscrg** [facebook/flow#4794]
Flow understands when a new key is added to an object:

```js
const o = { foo: 'hello' };
o.bar = 42;
console.log(o.bar); // all good! Flow knows about the key `bar`
```

But (AFAIK) it's impossible to write a well-typed generic function for setting a key. It might work if we exposed a `$SetKey` utility:

```js
function setProp<O: {}, K: string, V>(o: O, k: K, v: V): $SetKey<O, K, V> {
  return { ...o, [k]: v };
}
```

Thoughts? Am I missing something, and this is actually possible today?

#### Background

I'd like to define types for a binary parsing library with syntax like

```js
const p = new Parser()
  .int16("id")
  .nullTermString("name");

const b = Buffer.from([ 0x04, 0xD2, 0x46, 0x6C, 0x6F, 0x77, 0x00 ]);
console.log(p.parse(b)); // { id: 1234, name: 'Flow' }
```

But this requires using string literals as keys in object types, e.g.

```
declare class Parser<T: {}> {
  int16<K: string>(k: K): Parser<$SetKey<T, K, number>>;
  nullTermString<K: string>(k: K): Parser<$SetKey<T, K, string>>;
}
```

**Comment by madbence** [comment]
@mkscrg `O & { [K]: V }` _should_ work, but right now `K` is always `string`, even if you pass a string literal to `setProp`, so it becomes `O & { [string: V }` which is not very useful :crying_cat_face: 

maybe (?) see #2639 #4175 #4748
