### ISSUE TITLE
assignment of computed property

### ISSUE THREAD

**Issue by rico345100** [facebook/flow#4795]
If this is a bug, please try reproducing using https://flow.org/try/.

I have this code:

```javascript
type HttpRequestData = {
	url:string,
	method:string,
	headers?:Object,
	body?:string,
};

function request(options: HttpRequestData) {
  options.headers = options.headers || {};
		
  options.headers['Accept'] = 'application/json';
  options.headers['Content-Type'] = 'application/json';    << Error
}
```

It gives me this error:
> assignment of computed property/element. Computed property/element cannot be assigned on possibly undefined value

I didn't used computed property. Also when I comment that line, it works. Why it passes with headers['Accept'] part that has same syntax?

https://flow.org/try/#0C4TwDgpgBAEsxgEoQI4FcIGdgBECGweUAvFAN4BQAkGgE4A2AXNrQJYB2A5gDTUC2EYAAsA9gBNmwNl15UhEPGIi1MAfkYB5AEYArCAGNgsreJDqWHHhQC+AbgoUAZmnaHWI9lFqoM2ABQiYMDu7JiMsPBIPli4BHgAlOQUUFCBwR6YAHTyisqYJKlBIVk5SipQAD4V5HbUVMmF6aHZCmWYANoA5ACC+voQQZ0AugWdeGBg9Kz6BCEA9DqYHp32KWnFLbkqXQDCHsAQ7MAAtAAq4BDDo+OT07MeC0vsKzZAA

**Comment by SamChou19815** [comment]
This kind of dynamic pattern won't be supported.
