### ISSUE TITLE
custom NODE_PATH and requires

### ISSUE THREAD

**Issue by nnarhinen** [facebook/flow#48]
Given following files:

env.js:
```js
var path  = require('path');
process.env.NODE_PATH = process.env.NODE_PATH + ':' + path.join(__dirname, 'lib');
require('module').Module._initPaths();
```

app.js
```js
/**
 * @flow
 */
require('./env');
var Model = require('models/Foo');
```

lib/models/Foo.js:
```js
module.exports = {};
```

running `flow` prints

```
/Users/nnarhinen/projects/flowtest/app.js:.... models/Foo
Required module not found
```

Also I tried to give NODE_PATH env-var when running flow. Not helping.

**Comment by vjpr** [comment]
+1

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by dmnd** [comment]
I think this issue can be closed after `module.system.node.resolve_dirname` was added in [0.18.1](https://github.com/facebook/flow/blob/master/Changelog.md#v0181).

Docs are scarce but check the `.flowconfig` in the test in e1e301ce1502bd3de41a1370610b93bfc1cd3cbb to see how it's used.

**Comment by samwgoldman** [comment]
Thanks @dmnd. I think you're right that `.flowconfig` option will solve the problem outlined here. We have a few features here that need to be documented, and we already have tasks to add that.

**Comment by frontsideair** [comment]
I'm using `nix` package manager to generate the environment, which installs node packages to a folder and sets the `NODE_PATH` env var to that folder. We don't want to create a `node_modules` symlink in the working directory so we're doing all sorts of crazy hacks to make it work.

If flow can check `NODE_PATH` in addition to `node_modules` in the working directory or it could accept a command line flag for `resolve_dirname`, it would make our workflow much better.

**Comment by frontsideair** [comment]
I hit this problem again, and it was weird to see my comment is the last thing on the issue. I hope this can be implemented.

**Comment by Asgator** [comment]
@frontsideair me to

**Comment by Asgator** [comment]
@frontsideair look that, i finded
https://flow.org/en/docs/config/options/#toc-module-system-node-resolve-dirname-string

**Comment by kunokdev** [comment]
as @dmnd mentioned; for these too lazy to search through commit changes, this worked for:
```
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src
```

**Comment by kirushi** [comment]
The following coupled with a .env having NODE_PATH=src/ doesn't return any errors on flow (albeit there being many purposely placed errors)

`[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src`

**Comment by MatrixFrog** [comment]
@kirushi I was doing something very similar, but I discovered that actually can hide errors from you. See https://github.com/facebook/flow/issues/5647#issuecomment-357536444 -- I switched to

`module.name_mapper='^\(.*\)' -> '<PROJECT_ROOT>/src/\1'`

**Comment by bogdosarov** [comment]
In my case works:
```
module.name_mapper='^\(.*\)' -> '<PROJECT_ROOT>/src/\1'
module.file_ext=.jsx
module.file_ext=.js
```
