### ISSUE TITLE
Recognize react components by its type property

### ISSUE THREAD

**Issue by danrot** [facebook/flow#4800]
I have a react component, which has multiple other react components as child. Not all of the child components have the same type, and I'd loop over them using the `React.Children` methods and check each components `type` property, to know what kind of component I am talking to.

The thing is, that flow doesn't seem to know about the `type` property, and therefore is not able to properly check based on it. So even if I have tested the `type` property I can't access the corresponding `props` of the component.

I have also built the smallest possible example here: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcGO+RBAntlJgA3gGEAFuhgATFgDsAgnjzk+AGjABRGKUyk5BAL5ha9JiyoEOqVP0FgJU6QEYACnWwBnMAF4RqMDAAN3IYAFdSZwAuME8CPHQ5AHNUQ05UShhyT29HGWcwUgAPAn1pbzJLADpRelw5fQIAHjyXdzgvAD4AAuFUmzshVoAmdq9ff0CQ8NJhmLiE5NT0zOzcyRlhwpKyitYCGrq4BoMWjelRj08evsMBgSFXcnkCMe8-PsDKc-kY1vklCo+E1tLpGk1BnAoA5zgUAD7dSHQkadTrLGyrHJgJ4vbalOTlEj7Q7cE7NHGNN6dSZgeTSUh4AAUAEoaYFKtQaj99FVMORsIyCJJPFVsFcqt8nPINIzJTJWT5qZ8wABIQKBdDQ2XnKqDXw+PytZys5Xqs3qyjHTxwHRVeBJbVOUXi6YRY2cc3qu6BNXqzVgR0yXUPfWG87DE0BT3my1ya22+2B6TOjoi12zZke6Per2ZqN3QxAA

**Comment by jcready** [comment]
Change your refinements to use `instanceof` instead:

```js
class Parent extends React.Component<ParentProps> {
  render() {
    React.Children.map(this.props.children, (child) => {
      if (child instanceof Child1) {
        console.log(child.props.value1);
      }
      if (child instanceof Child2) {
        console.log(child.props.value2);
      }
    });
  }
}
```

**Comment by danrot** [comment]
It looks to me like this is not recognizing any failures afterwards... So even if I access non-existing properties in the `console.log` it is not failing.

**Comment by SamChou19815** [comment]
We now intentionally make the React.Element opaque, and started its deprecation
