### ISSUE TITLE
Flow 0.54.0 fails on travis with EACCESS error

### ISSUE THREAD

**Issue by danrot** [facebook/flow#4801]
It seems that since you've released flow 0.54.0 travis fails on my build with an EACCESS error. Any idea why this is happening?

It works on my local machine, but on travis I get the following error: https://travis-ci.org/sulu/sulu/jobs/271668230#L522

**Comment by erikras** [comment]
[:sadtrombone:](https://www.sadtrombone.com/?autoplay=true) – [Ditto here](https://travis-ci.org/erikras/redux-form/jobs/271805589).

**Comment by danrot** [comment]
Glad that it seems that it is not my error 🙈

**Comment by asolove** [comment]
Can people having this problem please report npm/yarn versions, os and version, etc.?

Install worked for me so there must be some pattern to who it doesn’t work for.

**Comment by danrot** [comment]
@asolove It is working on my locale machine using Mac OSX 10.11.6 and NPM 5.3.0. However, it doesn't work on travis (Ubuntu 14.04.5 LTS, Node 8.4.0 and NPM 5.3 installed using NVM).

**Comment by budde377** [comment]
Seeing the same in docker (on travis). Base image *debian:stretch-slim*, node v8.1.4, npm v5.4.0, and flow v0.52.0.

**Comment by danrot** [comment]
Tried to downgrade to flow 0.53.1 and it didn't seem to help... Might this be a travis issue? Would be interesting to know if there is somebody having the same issue on a non-travis environment...

**Comment by vkurchatkin** [comment]
This is a problem with npm, not with Flow. See https://github.com/facebook/flow/issues/4733

**Comment by gabelevi** [comment]
Having looked into this, I agree with @vkurchatkin 

If I download and look at the flow-bin@0.54.0 tarball (`npm pack flow-bin@0.54.0`), all the binaries are correctly marked as executable. The explanation on https://github.com/npm/npm/issues/18324#issuecomment-327081533 explains that they re-wrote how npm extracts packages and that it was accidentally stripping executable flags.
