### ISSUE TITLE
$ElementType in function parameters needs to be "delegated"

### ISSUE THREAD

**Issue by nicolo-ribaudo** [facebook/flow#4804]
## Input code
https://flow.org/try/#0GYVwdgxgLglg9mABAZwKZQIwB4DyAuRHAIwCtVoAaRAaQIBJrUBPZXAPjYAo5SCcqA1swLUqANwCGAGxCp6AUSmoAtqjBQAKkwAOqXFWpsAlIgDeAKESIeJANpCmAXUQBeRJJmoA3OYC+58ygdVEQAfUUVNU1grABBKgAhNldEOgjVdS1dOMS2c1BIWAQUdAAmXD5ScigDekYWdi4bPkFhGnFpWQJwpQzo7P4aYzNLa1J7Zmc3D1kff3NJACcxkhTTRAkCDCoiAgAiZD3EXx9zNExuUio9iT3rw6Mfc9LLkmvb+73H8yA
```js
function set1<O: Object, K: $Keys<O>>(obj: O, key: K, value: $ElementType<O, K>) {
  obj[key] = value;
}

type _ElementType<A, B> = $ElementType<A, B>
function set2<O: Object, K: $Keys<O>>(obj: O, key: K, value: _ElementType<O, K>) {
  obj[key] = value;
}

var obj = { a: 1, b: "s" };

set1(obj, "a", "s");
set2(obj, "a", "s");
```

## Expected result
Both set1 and set2 should report an error, since obj.a is a number.

## Actual result
Flow only complains about set2, not about set1.

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
