### ISSUE TITLE
[0.54.0] treats internal and exported Map differently - bug

### ISSUE THREAD

**Issue by rosskevin** [facebook/flow#4805]
[Reproduction](https://flow.org/try/#0MYewdgzgLgBAtjAvDMBTA7jAsgQwA4AUAlAFAmoAeeIATrKJLBUihtvsUA)

```javascript
const m = new Map()

export const x = new Map()
```

```
3: export const x = new Map()                    ^ type parameter `K` of constructor call. Missing annotation
3: export const x = new Map()                    ^ type parameter `V` of constructor call. Missing annotation
```

With that said, I couldn't find a syntax that would actually remove this error either (other than suppression)

**Comment by vkurchatkin** [comment]
The right syntax is `export const x: Map<string, string> = new Map()`

**Comment by asolove** [comment]
It does seem like the error message should be clearer that you need to annotate the exported value. As is, the error references V and K, which don’t actually appear in the program source.
