### ISSUE TITLE
Any way to specify types for receivers?

### ISSUE THREAD

**Issue by marcianx** [facebook/flow#4809]
I'm porting some code that happens to use the following pattern at the moment:

```javascript
function foo() {
  this.bar();
}
```

Is there any way to specify the receiver's type (type of `this`) for `foo`? I didn't run across it in the docs, but I could have missed it.

**Comment by marcianx** [comment]
And actually, there's a bug in the compiler:
https://flow.org/try/#0PTAEBUAsEsGdQG4FMBOtoHsB2oDm1l4BDUABxQ1NVAGMMBbU6AG2tQpVCICMMBXAC4AoEKAAG3IijGgsGAaG5JoWXKAAmSAGYqk60NnECYsGUXjQFsSP2bqAdCOBa+WGgMw4tGDAAoAlKAA3k6goMZw9pIoAQDcTgC+QqEAogAepMzQNJbMAJ6gsFQ5WnkqasZIoC5uHoYCeVQANKA2AO5IyChNobB8pORIsLBD4Sag7BjdoG0wNJCgcKCusPxYDkJ0WLAK3hgAXKABoAC8AHyIGND6J9Wu7p7HIWERsFFScUIJ8Xv2NETMZhxUCiay2fRaIgsACEoV+-0BviC0UOx3OwQSCX8sRBYD6NBoSD0sCAA

```javascript
// This version gives a proper compiler error about
// `bar` not being defined on `this` as it should.
//function foo() {
//  this.bar();
//}

// Explicitly specifying the function type, however,
// suppresses this error, which is unsound.
const foo: () => void = function() {
  this.bar();
};
foo.call(); // should fail!
// foo.call({bar: () => {}}); // succeeds
```

**Comment by SamChou19815** [comment]
https://flow.org/en/docs/types/functions/#this-parameter
