### ISSUE TITLE
incompatible instantiation error for React HOC that injects a merged object into a Component

### ISSUE THREAD

**Issue by PeteJodo** [facebook/flow#4814]
~~Attempting to reduce this example to a simpler test case but haven't come up with anything yet~~
Added a reduced example below

Example 1:
```jsx
import * as React from 'react';

function mergeTheme<Props: {}, T: { [className: string]: string }>(
// ^ some incompatible instantiation of `Props`
    Component: React.ComponentType<{ theme: T } & Props>,
    injectedTheme: T
): React.ComponentType<{ theme?: $Subtype<T> } & Props> {
    const Themed = (props: { theme?: $Subtype<T> } & Props) => {
        let theme: T = injectedTheme;
        if (props && props.theme) {
            const passedTheme: $Subtype<T> = props.theme;
            theme = Object.keys(passedTheme)
                .filter((key: string) => !!injectedTheme[key])
                .reduce((accum: T, key: string) => {
              	    // actually using classnames here
                    accum[key] = `${passedTheme[key]} ${injectedTheme[key]}`;
                    return accum;
                }, { ...passedTheme, ...injectedTheme });
        }
        return <Component {...props} theme={theme} />;
        // ^ props of React element `Component`. This type is incompatible with
    };
    return Themed;
}
```

Example 2:
```jsx
function mergeTheme2<Props: {}, T: { [className: string]: string }>(
// ^ some incompatible instantiation of `Props`
    Component: React.ComponentType<{ theme: T } & Props>,
    injectedTheme: T
): React.ComponentType<{ theme?: $Subtype<T> } & Props> {
    const Themed = (props: { theme?: $Subtype<T> } & Props) => {
        let theme: T = injectedTheme;
        // ^ some incompatible instantiation of `T`
        if (props && props.theme) {
            const passedTheme: $Subtype<T> = props.theme;
            const themeKeys = Object.keys(injectedTheme);
            theme = themeKeys.reduce((accum, key) => {
            // ^ object literal. This type is incompatible with
                const passedThemeClass: ?string = passedTheme[key];
                if (passedThemeClass) {
	            // actually using classnames here
                    accum[key] = `${passedTheme[key]} ${injectedTheme[key]}`;
                    return accum;
                }
                accum[key] = injectedTheme[key];
                return accum;
            }, {});
        }
        return <Component {...props} theme={theme} />;
        // ^ props of React element `Component`. This type is incompatible with
    };
    return Themed;
}
```
Example of how it is getting used:
```jsx
type MyProps = { someProp: number, theme: {| someClass: string, anotherClass: string |} };
class MyComponent extends React.Component<MyProps> {}

const MyThemedComponent = mergeTheme(MyComponent, { someClass: 'foo', anotherClass: 'hello' });

const el = <MyThemedComponent someProp={1} theme={{ someClass: 'bar' }} />;
// the theme prop received by MyComponent is { someClass: 'foo bar', anotherClass: 'hello' }
```

[Link to TryFlow!](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINBoq2AOZUAKgAsqkgDwAFJhlIAuUAG8AvgBpQc3XtABtWtDKkAcsUm7SubCkHSAui7cfpoAYAfAAUiKARoADCzFiCVIK4utR0uAB0MZhiCbhyAJ4YVCoWuErOpoGgAGSgGrBaQUbhkR4AVlT0VAAmispUunKIAJTJnOmZcTn5hcWgpX0A-LoAJADK-ABGuAVFckGVNXUN+s0RtGKupmXdoAC8oCEYmjr6c9dLoGub2zN7B7XPIZ3fZ6U6RCLQKj4eblOR3UBtDq4bq9SS8cHglCQB5PerkKo1XFaNIwqhA0EYymgc6CS4YOwo64rdZbHYqP73ImkEnXdFU8Gk+EAeQ27XoaQA1lQ8qRHgyetchmD+eC0pAUNBkdgQiEpXlfO5PEDbvsAISmxGdBV9Sx6rxKlVUtIcLr8WhUHV0Wj8NADEx6g3+Y0g5UqgCQYZAJHo-GI0GgeVA-FI-mptlIpEETio5CUHFDjvBXp9tulXnhAANlnp6RnGTa7QZPnpLcjrZJS3kvAYK3zC1SOLh+NhxMW0H3+4ETBY0rPa6R65ITLO0q3F1RAkMJ+CDAXQIPh+IVBNsol9CuuU3Sbc9KSm8AghODBODyOrn0urxd4gBMJcKJxEkGR5GuAAmdRnnMYxTHMKwbDsRxylcQ1vEDTxAlCMET3iRJRlSDJYlPXI2RKJkKibQ5nkaME13bfpTGGPDxWwqYSLeRZmW+Nk-gogE8RDcEaUuVEbnuR5INeUkPi+Vlfn2XijlIYMTn5SFoTIuF7lokTtxabFxLxapCWeHk+nJPdBIufB53XTjZN2fZORM0ldMpIT1L6ABpaVyHuEUxXSPVZW0xVXIxQV7lJbyZWdbo3Q9EIx39aVlIpSczis0AbLoqJ0xeBZkNTTl5REzsvDC-ksRxErrlyuxzIjRqo1SWN40TZNU3gjMs0kXMpCoCzCzHMrK2rbLSsbZsQobMsewqwtX1HWhvXHQbKV3dKImGu14Wmjs7XmylFujFbDqnfQDC3PcNoHKFD1AY9CJw-A9AvZ4r2uG871AB8nxfO63xEz9EAMIA)

**Comment by asolove** [comment]
Have you tried using `{ theme: T, ...Props}` instead of the & type? That is often worth trying. Sorry I’m on mobile so I can’t check myself.

**Comment by PeteJodo** [comment]
I get a couple new errors but I believe the important one is: `Cannot spread properties from some incompatible instantiation of "Props"`

`incompatible instantiation of "Props"` is what confuses me. The `Props` type isn't touched within the `if->reduce` logic. I had originally thought it was my own bug in that code block rather than a flow bug but I'm not sure now.

**Comment by PeteJodo** [comment]
Here's a [reduced example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32sDcykArgDt6KWINBoq2AOZUAKgAsqkgDwAFJhlIAuUAG8AvgBpQc3XtABtWtDKkAcsUm7SubCkHSAui7cfpoAYAfAAUiKARoADCzFiCVIK4utR0uAB0MZhiCbhyAJ4YVCoWuErOpoGgAGSgGrBaQUbhkR4AVlT0VAAmispUunKIAJTJnOmZcTn5hcWgpX0A-LoAJADK-ABGuAVFckGVNXUN+s0RtGKupmXdoAC8oCEYmjr6c9dLoGub2zN7B7XPIZ3fZ6U6RCLQKj4eblOR3UBtDq4bq9SS8cHgji4fjYcQqCbZRL6NIkp71UgGN59W56GFUSnAILoyIGZkRLE48So7q8AyIIA)

```jsx
// @flow

import * as React from 'react';

function mergeTheme<Props: {}, T: { [className: string]: string }>(
    Component: React.ComponentType<{ theme: T } & Props>,
    injectedTheme: T
): React.ComponentType<{ theme?: $Subtype<T> } & Props> {
    const Themed = (props: { theme?: $Subtype<T> } & Props) => {
        let theme: T = injectedTheme;
        return <Component {...props} theme={theme} />;
    };
    return Themed;
}
```

**Comment by PeteJodo** [comment]
Yeah I'm just a dummy. I'm using `$Subtype` instead of `$Shape`. Using `$Shape` fixes everything.
