### ISSUE TITLE
Bug: Recursion limit exceeded since v0.54

### ISSUE THREAD

**Issue by nvie** [facebook/flow#4816]
We've hit a weird issue when trying to upgrade to Flow v0.54 (same goes for v0.54.1 and `master`), where a piece of code makes Flow hit a recursion limit.  I've not fully understood the underlying issue yet, but here's an example that illustrates the issue.

[Example to reproduce.](https://flow.org/try/#0GYVwdgxgLglg9mAVAAhgJwIZgOYFMAUAzlBmlAFzJggC2ARrmgDTLFwAOl19jLxunKrQZoAlJQCSURhjoAbXAB5uIgHzIA3gChku5AqhVkAXlYkyAbh16A7gAsYC5PjDJFZjqM3W9egJ4wuHIAJlRWAJC+rgDUpvzsVr4AvlopWqCQsAjImDgExKQUQjzMHoIqvGYCXMKM4sgAgmiYfsq1aOravmi4UCBorgDaAHSj6Fh4ROZQfFAcswKiALpWaRnQ8EjI7Iw0ICRZYISKACqq+DDSmPK4kleyCqeqLGgA-DUl9VIyN6eDS50fMgAPSIRBA5AoAByAHkTgBRcgQlAnOy4VA0dgKGi4MAHTbIBhyOA2VCEZDBdC4aByPyEuDNEm4ULANBwGjIKBo5AABT8XIQyLMWGCpFCchgdEwaD8LBgrgw+nluAAtHQ-CqJWB0VBcoQ5BhDsNkcCgQZtnA4HITMgRmN7jcVmbekZTOxLXJhgocFzEno0DaoH4dnBgDkTMZTABycDBXDAZXBKPIV5GShoKxAmBh-AB9RgLxdXz+3r9MB+3RpXzA4HIFX1huNpvNluttvtjstrRAmvIVEwcla9E2BkAa2ZyAT2uQ4Fg1oAbgAGYYAVgALMKyBOIHY4KP5dhkNlLsgbJc7MgAERglAAJWp-UIBIlNBPuAAHhBcMyJzfL87DHlSkv3JUw7WGcY8nwRcWDAFgAEZlkzatawACSZedKkIGwMHYdgD05bkh2QWQ4Ewo99knBlCPRMAEE1DAAC86QgDA5GtIkSWQGgMHHckADFiVJJdVw3Ec0FHEjsAweUe1rc0gJgECbVySYYKoBDRGQvRe07PT9IMwyG27XxzQgPwIAUQgPhEf4bXAyDJjgowVRyFgVUQp1TJdd0rTwKArhtGATHUXy5EGGAnSBAIglCRSQOGfUlIIdSxGGHj2HwML-KuLSgXsRx0RcZB1EXQsIT0MyFCweF30uSg6A9XAsEDNAQFwCti2Aaj8AUo8w1UggA1c+D3NGutEPK4tpuQczLNwQgIqWOtTHgzqZtQHM5qspaI1MMrvA2jb4oWoKwGAhaKqO4tEolL9oLlUQruuvRhggBBWKgC5zuSwhbuSi5kGiZBJuel7kDej7DW+i6-qS+6YDlIGQdEPLwd8baFt20xXFcmB1pmpJkCCQh0SLdH9BdAArGzGBtTHFsi7SKfNQZ2BYABHZawJOxmfoS71sC5OtkCppY5X5rHIq8inUElxnue2Anrt5iL5a9XEhYvVyxZtDnlaOmKQjl2H-vu1LRHS3Cso9HK6gNjb5pqurDFMYA2NJh2ZqlZrRy9ytnqrGbs2cJ2wFqy4ppeno+gGA2UmSVItCAA)

v0.53: **no issues**.
v0.54: **error**.

What might be an interesting hint is the finding in the block in line 27 - 35.

(Sorry that the code is a little noisy—I haven't been able to make the example smaller yet.)

**Comment by samwgoldman** [comment]
Sorry about that. You can add an `number[]` annotation to `indices` to work around the issue for now.

**Comment by nvie** [comment]
Thanks, that indeed solved our immediate issue.  We used this pattern of `[...lazyIterable()]` in multiple places in our code base, but this is the only instance that triggered the recursion limit… ¯\\\_(ツ)\_/¯

Let me know if there's anything else I can do to help to get this resolved.

**Comment by samwgoldman** [comment]
Extracting a repro case is already incredibly helpful :)
