### ISSUE TITLE
Re-constructed objects should pass for exact types

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#4818]
When re-constructing an object it should pass as an exact type but it does not. This is a common pattern. An example use case would be removing undefined properties with a utility function like:

```js
function removeUndefinedProps(object) {
  const newObject = {};
  Object.keys(object).forEach((key) => {
    if (typeof object[key] !== 'undefined') {
      newObject[key] = object[key];
    }
  });
  return newObject;
}
```

Even though this function *begins* with an empty object it returns one that would be compatible with the exact type of the original.

Here is a [full example with Try Flow](https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwD4CgooAzASyWAH1UBDAWwgC4pFh5TUBzAGkKgBsaravSYs2HHn2I0AbsnbAIlAMbJ+CgPzNW7Lr1wBfANz58a1KyiQkaTDmnlhtBswDkAKRqoIb3kUFnUXcAZWQGYAALST9pOQVSJVV1BWYAV1QAEwgyH0zeEzNiDJVgUjt4CDpkWQgAVSycjghMmHhkMEQACmQAIwArCFKASgciCysfAHcAeQGh4HtsQqI5wdKAOgBrCBBuvvXgYY3iBQBRGhVIrq6dkFGMAD4xoihSYigu0EhkD4OFgDadwAulAAIQYLBuDLZXItNyjbB8V5QaZrQEg+z-UpA3bA0wowx8QzDAlQSrANLwdBo+alUxE8xoSYQKZwWyoZjslDoLCVaq1Bqw5qtdqdLo2HmkoA) that reproduces the error shown below.

```
23: const newPerson: Person = removeUndefinedProps(person);
                              ^ object literal. Inexact type is incompatible with exact type
23: const newPerson: Person = removeUndefinedProps(person);
                     ^ exact type: object type
```

<details>
  <summary>Code</summary>

```js
type Person = {|
  first_name: string,
  last_name: string,
  favorite_color?: string,
|};

const person = {
  first_name: 'Jane',
  last_name: 'Something',
  favorite_color: undefined,
};

function removeUndefinedProps(object) {
  const newObject = {};
  Object.keys(object).forEach((key) => {
    if (typeof object[key] !== 'undefined') {
      newObject[key] = object[key];
    }
  });
  return newObject;
}

const newPerson: Person = removeUndefinedProps(person);
```

</details>

**Comment by vkurchatkin** [comment]
It is not possible to either infer or verify such typ for this function. You have to declare it explicitly, although you should understand that this is unsafe.

**Comment by kumar303** [comment]
Thanks for the explanation. It seems odd to me that using placeholders for the object will pass Flow checks. Why wouldn't both cases work? I guess because it's not possible to infer the assignment of `newObject[key] = object[key]`?

Here is a [Try Flow](https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwD4CgooAzASyWAH1UBDAWwgC4pFh5TUBzAGkKgBsaravSYs2HHn2I0AbsnbAIlAMbJ+CgPzNW7Lr1wBfANz58a1KyiQkaTDmnlhtBswDkAKRqoIb3kUFnUXcAZWQGYAALST9pOQVSJVV1BWYAV1QAEwgyH0zeEzNiDJVgUjt4CDpkWQgAVSycjghMmHhkMEQACmQAIwArCFKASgciCysfAHcAeQGh4HtsPiIAelWoABVIiERoMEEVCEj1bKQoKdJ+fmtK2tRFmigAMQ0pqAR2+AA6FZInKguMRuA40I4nfhnWJEAJCQHBKAgw7HU4IaEwmTyRTKNQaeDpRq5Fr+KCFIhzQalb4AawgIG6fUpwGG32ICgAomDIl0urSQKMMAA+MYw0jEKBdUCQZDixkLADafIAulAAIQYLBuDLZImZNyjZYwmHTCkK5X2OWlRV0pWmI2GPiGYZ2qCVYBpeDoE3zUqmB3mNCTCBTOC2VDMUModBYSrVWoNHXNVrtTpdGxR51AA) example with placeholders added.

<details>
  <summary>Code</summary>

```js
type Person = {|
  first_name: string,
  last_name: string,
  favorite_color?: string,
|};

const person = {
  first_name: 'Jane',
  last_name: 'Something',
  favorite_color: undefined,
};

function removeUndefinedProps(object) {
  const newObject = {
    // These placeholders will prevent a Flow error.
    first_name: 'placeholder',
    last_name: 'placeholder',
    favorite_color: undefined,
  };
  Object.keys(object).forEach((key) => {
    if (typeof object[key] !== 'undefined') {
      newObject[key] = object[key];
    }
  });
  return newObject;
}

const newPerson: Person = removeUndefinedProps(person);
```

</details>

**Comment by SamChou19815** [comment]
This pattern of dynamic object init won't be supported
