### ISSUE TITLE
Provide option for defining functions with exact arguments

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#4822]
Currently flow allows passing functions with less arguments in place function with more arguments given the [function subtyping rules](https://flow.org/blog/2017/05/07/Strict-Function-Call-Arity/#function-subtyping). I am not what is the reasoning behind current behavior (It seems that Array.prototype.map could use `callbackFn` interface with multiple different signatures) but I would really like to have an option to define a function that would accept function argument with an exact number of arguments and no less.

**Comment by vkurchatkin** [comment]
Can you explain what is your use case?

**Comment by Gozala** [comment]
@vkurchatkin Here is the [library I've being working on](https://github.com/gozala/route.flow) for type safe routing. Idea is to be able to define routes like:

```js
const calculator = Route
  .Root
  .segment("calculator")
  .param(Route.Float)
  .segment("+")
  .param(Route.Float)
```

And to match location with a route like:

```js
calculator.decode(window.location, (a:number, b:number) => {
  // ...
})
```

There is also part in regards to formatting links like `calculator.format(2, 3)` but that's not really important. **Important** detail is that library wants to more type friendly alternative to existing routing libraries and to do so type checker should be able to catch any miss-match between routes and handlers. For example if after refactoring another route parameter was added to the existing route I'd like type checker to be able to outline all cases handlers that were not updated to handle added parameter.
