### ISSUE TITLE
Flow 0.54 breaks our attempt at a "non-maybe" type

### ISSUE THREAD

**Issue by nvie** [facebook/flow#4823]
We use a function to strip out any potential `undefined`s from arrays, like so:

```javascript
function compact<T>(iterable: Iterable<Maybe<T>>): Array<T>
```

**Since 0.54, this seems to break** and the inferred type for the function allows undefineds to "slip through" somehow.  Before Flow 0.54, this behaved as we intended it.

[Example illustrating the problem.](https://flow.org/try/#0C4TwDgpgBAsghiARhAPAFQHxQLxTVAHygDcB7ASwBMBuAKHogA8xSAnYKAMwFcA7AY2DlSvKP1IBbMHEHoMACnLAIrOIgA2EAFxQAkstUbU8JKkwYAlDoCCrVSDlQA3rShuomjqwgBnbuo5cAG0AXTp3LjYoeU8oJQgJKFJOOIM1TQtnVwj3chTFZUSAQmxcPkoITnJeCEpMlxzGqG8-AIA6MG4fAAsChItwpoBfbLcRiO9gblZRFv9gOhHaAHplqAB1NgBrHzjRADF1UgB3KAAGNoBWAGYVtYAhbzgdvahDk-OrgBZaeXEpGTAeRBACMABooAAmCHlSrVWoQr4hKxQWz2FC8bgSZCsSx0IA)

Please run the example against 0.53 and 0.54 and see the difference.

Do you consider this a bug in 0.54, or is there a better way of annotating this function that I'm unaware of?

**Comment by AugustinLF** [comment]
Hmmm, I might be missing something, but is there any reason not to use the built-in maybe, `?T`? [This works for instance](https://flow.org/try/#0KYDwDg9gTgLgBAMwK4DsDGMCWEVzRAWzAEMMAeAFQD4AKTGYKYgIwBtgAuOASQabeBkA-NQCUXAIJQmAT0pU4AbwBQcNXHbwowAM5JW8ALxwA2gF0A3KvUJocGprj1gBOBARO+LdqKXX16pgedAyuAITGqAAmwAiYKMBRvioBqeraegYAdGBIOgAWIS6iVmlqAL7+cJUB2jBIULgZ+jBWlcoA9B1wAOrQANY6TrgAYqwQAO5wAAxZAKwAzJ3dAELaxIPDcGOTM-MALMo0+ESkMDQmAIwANHAATLfRsfGJt-tm4nBSsmQoSATMRhUErKIA): `function compact<T>(iterable: Iterable<?T>): Array<T>`. Note that I switched the test for a `item != undefined` instead of `item !== undefined`, if you'd rather stay with the strict equality, you can test against both `undefined` and `null`.

**Comment by vkurchatkin** [comment]
This looks very brittle at best. You assume that `T` should always be inferred as not `Maybe<Something>`, but this is not guaranteed.

**Comment by nvie** [comment]
Thanks for the quick suggestion, @AugustinLF.  We've been using our Maybe type everywhere, mostly since we just prefer a single "missing value" type rather than two.  We don't use `null` in our codebase at all.  Your modified version will open up the function to accept nulls as inputs, which is something we'd like to avoid.

I'm not looking for an immediate workaround, but more interested to understand _why_ this is a problem since 0.54, as it may indicate a bug.  As @vkurchatkin just mentioned (thanks!), this is indeed an assumption I'm well aware of.  I guess I'm looking for a better way to express it.

@vkurchatkin I understand how it leads to the error, but… how do you explain the difference between my version and @AugustinLF's example?  Shouldn't that have the same behaviour?

**Comment by vkurchatkin** [comment]
> Shouldn't that have the same behaviour?

@AugustinLF's version is just as brittle, it just seems to work at this time

**Comment by nvie** [comment]
@vkurchatkin Is there an expression or utility type that would let me express "any `<Something>` except when `void`"?  Ideally something like:

`function compact<T: $NonVoid>(iterable: Iterable<Maybe<T>>): Array<T>`

Where `$NonVoid` would basically be like "any type without a void member in its union".  That way, if Flow tries to infer `Maybe<Something>` (= introducing a void member in its union type), then this extra condition would prevent it and it would capture the intent here more strictly.

The question thus becomes… would something like the `$NonVoid` type be possible—or does something like it exist already?

**Comment by jcready** [comment]
Does this not work for you?

```js
function compact<T>(iterable: Iterable<Maybe<T>>): Array<$NonMaybeType<T>>
```

**Comment by nvie** [comment]
Wow. Consider mind = blown! TIL about the existence of `$NonMaybeType`. Why isn't this useful thing documented on the Utility Types doc page? This is a life-saver. Thanks, @jcready!

**Comment by jcready** [comment]
@nvie that is an **excellent** question. [It seems that having up-to-date documentation is not one of the flow team's goals.](https://github.com/facebook/flow/issues/2464#issuecomment-326271329)
