### ISSUE TITLE
React.cloneElement props errors when applied to unions of class components

### ISSUE THREAD

**Issue by avaly** [facebook/flow#4824]
It seems that `React.cloneElement` is throwing some unexpected errors when applied on children defined as `React.ChildrenArray<React.Element<typeof Foo | typeof Bar>>`.

1. The first error is that the props from `Foo` are not found in `Bar` and vice-versa.
1. The second error is that the new prop added via `cloneElemenet` (`ham`) is not found in the props of `Foo` or `Bar`.

This only happens when `Foo` and `Bar` are declared as class components.

```js
class Foo extends React.Component<{ foo: string }> {
  render() {
  	return <div>{this.props.foo}</div>;
  }
}

class Bar extends React.Component<{ bar: string }> {
  render() {
  	return <div>{this.props.bar}</div>;
  }
}

type ChildElement = React.Element<typeof Foo | typeof Bar>;

class Parent extends React.Component<{
  children: React.ChildrenArray<ChildElement>
}> {
  render() {
    return <div>{
      React.Children.map(this.props.children, child => {
        return React.cloneElement(child, { ham: 123 });
      })  
    }</div>;
  }
}
```

See [class component example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugGIQRxYAeMWAOwAm6bHhgA6AMIlIAwTAA8AbzgFOALjioYUYAIDmcAL4A+OMrpw4lYVigAKAJQWrcAJCUYAVygC4ikLAAG6myjAAFsCoEmDEYDHqEMaKAPRBofTWxnQ5jCyo6ABCyFDcfIIimFSSMuAQ8gJKqgBGpVo6eoYm5pbWtkL2zq7Wnlg+fgEZYZHRsfExbVAp6SGmWSa5DDAAnmBYcFJRTEIAokxYIApwALzV4hLnlwqKu-sQBHAcXAA+cG9YD5wEpQdYMZisOAABVK114-GEohq0lkDRefTguGOQlsWjE+Gk2NsAEEoFBkDtFEdgCcnlcmqZcr03AMhi4Mf1xr5-IE1hzrPcCdSTrYJCBkGAHLMYnEIAkJFiaTjBAAaTHY27MgXamxcyb4yTMNF0hQORUnNWqCLIEBaACMACYAMwmJwbbXGFxwNzZNLTDY5PKKb5qTg3ABE-B04bgqTBwc4oYgEajMBj1pAN2Ujqdxlj61jqTgAHdoABrVB0RQguBLFNYaP5+jV0q10r1xsZrM5vNxmiFkvl1BAA)

As soon as you convert them to functional components, there are no more errors:

See [functional component example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdBArgHb7AQtwBiEEAFGGJhUALjgBvOAT7jUMKMBYBzOAF8AlJLpw4lGEyhcAPABNgANwB8EoRBEA6GRDXGA9Oev01DZmxgcXABCyFCCwmKScABGoXIKSqqa2rr6hiaeNnaOsVCuHpZW3gwwAJ5gWHAAwgAWwAA2pgCi9VggWCzwALyYVDAOLW0dMMZlFRAEPHxwAD5wY1gTcCFQRQy49WjoAAqhw3BYAB4wHabo2Hj9VSSQLMPGEjpwuHWNlCziF-gOtQ2m7wBBKBQZClYy-RqDdqdKx0NRWFJ6U5YMJaR66VJYAxGOBmQrojG6L5XV7-DoOEDIMD8GB1VAObL0l5-d4AGmepLgXQRBMJmOxXGJDg2nCwUOG-GZjXZUhqyBA4gAjAAmADM6g09D5Gt0T10+UyWvUcIYxl4EGkfC6ACITvJrXA3GszdNnDa7TAHXKQF0JCrVWpHUVHW44AB3aAAa1QdGMKxioXdWHtQfocdCCagSZT3t9-sDTpoIfDUdQQA)

Tested on Flow v0.54.1

**Comment by avaly** [comment]
This is still an issue with Flow 0.79.1:

1. The first original error is no longer present
2. The second error is still thrown when calling `React.cloneElement(child, { ham: 123 })`

Since the original `Foo` and `Bar` components were defined with props as inexact objects, adding a new `ham` prop should be valid.

**Comment by danielo515** [comment]
This problem happens to me with a property that is declared only in one of the components, but I'm using Functional components, not class ones.
What is the workaround?

**Comment by danielo515** [comment]
In fact, you can not do `React.cloneElement(child, { foo: 123 })`, but foo is a valid prop on Foo component props. [Take a look here](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdBArgHb7AQtwBiEEAFGGJhUALjgBvOAT7jUMKMBYBzOAF8AlJLpw4lGEyhcAPABNgANwB8EoRBEA6GRDXGA9Oev01DZmxgcXABCyFCCwmKScABGoXIKSqqa2rr6hiaeNnaOsVCuHpZW3gwwAJ5gWHAAwgAWwAA2pgCi9VggWCzwALyYVDAOLW0dMMZlFRAEPHxwAD5wY1gTcCFQRQy49WjoAAqhw3BYAB4wHabo2Hj9VSSQLMPGEjpwuHWNlCziF-gOtQ2m7wBBKBQZClYy-RqDdqdKx0NRWFJ6U5YMJaR66VJYAxGOBmQrojG6L5XV7-DoOEDIMD8GB1VAObL0l5-d4AGmepLgXQRBMJmOxXGJDg2nCwUOG-GZjXZUmc4gAjAAmADM6g09D5at0T10+UyGvUcIYxl4EGkfC6ACITvJLXA3GsTdNnFabTA7TVkCAuhIlcq1Paiva3HAAO7QADWqDoxhWMVCrqwtsD9FjoXjUETyc93t9KoDDpowbDkdQQA)

**Comment by danielo515** [comment]
And here I am again, trying to find a solution to this problem and finding only myself asking...

**Comment by SamChou19815** [comment]
now it works
