### ISSUE TITLE
[question] object subtypings

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#4826]
[Playground link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AUQLYCWKoAvKAN6hYBuWAdigFygDkAhgEYDGroAvqAA+lanUYtWAEyyQ+-VJhwBBMqPxpJy+cm6x6AZxIZ2AJwNZV5ABQm0cdlICULKqawGWqwaQB8oawpEUFB3T3VNNm0BRH4nXX0jUBNzLABlLFM6UwAlDwxEnBt0bAAaZPZ7WEcXUTCWdno0cqwiFAMAfi9TU0qAHgJifx9-IIBIA3hibgALAJKsJ0pgkNXudgso1iYV1dX3FABXU3oK1OVbSodnXdWZSHZD6GZbvZQZ0wRQeix4PB7YKZrPExgp+EA)

Is my reasoning wrong? I thought this should be completely legal and Im not sure how to restructure my code to satisfy flow's type checking nor whats exact reasoning is used here and why such case is forbidden.

**Comment by jcready** [comment]
This does seem like a bug. [Here's a simplified test case](https://flow.org/try/#0C4TwDgpgBAglC8UDeUBmB7dAuKBDAdiADRQBGuATgPw4EhQC+AUKJFAEILJqa2GNMmAY3T4AzsChCccRAAoUGbFACMjHOwCUUAPQ6oYgBboArgBsAJlDC4xYkqROTUZ9AHcoEChXQUowQx83fCA):

```js
type A = { foo: any, bar?: any }
type B = { foo: any }

const c: A = ({ foo: 1 }: B) // should pass, but flow error thrown
```

**Comment by vkurchatkin** [comment]
Not a bug. Supertypes can't have more properties, even optional ones.

**Comment by jcready** [comment]
Welp, in either case @Andarist you can resolve your issue by dropping the return annotation from your `parseA` function.

```js
const parseA = (payload) => ({
  res: { my: 'A' }
})
```

**Comment by Andarist** [comment]
> Not a bug. Supertypes can't have more properties, even optional ones.

Kinda weird in such scenario. Thinking about it it is a valid scenario (at least in my had) to have ur code structured this way - nothing weird about it, but cannot type it properly without 'hacks' (what @jcready mentions)

@jcready 
Ive dropped return annotations for now, but I would very like have them there to keep extra safety net. 

Ive also thought about adding such 'dumb' `any` or even adding this optional property in those returned types, but its super weird when I know that only `{ res }` will be returned, so it felt too much like a hackery.
