### ISSUE TITLE
Disjoint unions fail when destructuring tagging property

### ISSUE THREAD

**Issue by avaly** [facebook/flow#4828]
The following typing triggers an error in the `reducerFails` reducer where we access the `action.type` after a destructuring operation. Flow should apply the same logic as it does for the case in `reducerPasses`.

```js
type Action = 
  | { type: 'FOO' }
  | { type: 'BAR', payload: {} };

function reducerPasses(action: Action) {
  if (action.type === 'BAR') {
    return { ...action.payload };
  }
  return action;
}

function reducerFails(action: Action) {
  const { type } = action;
  if (type === 'BAR') {
    return { ...action.payload };
  }
  return action;
}
```

See [example code](https://flow.org/try/#0C4TwDgpgBAggxsAlgewHZQLxQFBSgHygG8pRIAuKAcgDEB5OqqAX1wONPAkqoCEYASlQA0UMAEMQAG2TiAJpSLMWAbmzYAZgFdUCFOgBOEOVrgQDABXEBnaxGsAKcXrSV4SNAEpibRBqhOLqgAdGTQGBHU-ELeRGx4RsBaBugkwenOHiES0rJyqmysCRBJKVCZ+mqsmjpBUEYmZgY04ohSjhWusEGxbHBo1sAcYSyY5UFqeH4BIxFYfIJUvXjFpalQ6cGd2ZIy8gV4RfUlyejbVUA)

Reference docs: https://flow.org/en/docs/types/unions/#toc-disjoint-unions

**Comment by vkurchatkin** [comment]
This is expected. At this point `type` is basically `'FOO' | 'BAR'`. Flow doesn't keep track of the fact, that it is somehow related to `Action`.

**Comment by avaly** [comment]
It's weird that Flow can not make the connection between the desctructured `type` and `action.type` and figure out what `action` is at that point.

But if this is the intended use case for disjoint unions and refinements, at least this can be highlighted in the docs section for disjoint unions (I can't find any mention of this requirement), in order to not confuse other folks. @vkurchatkin what do you think?

**Comment by mgtitimoli** [comment]
@vkurchatkin is there any near plan to support destructuring for disjoint unions, should a proposal be created for this?
