### ISSUE TITLE
Ability to reference modules in declarations (Meteor)

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#483]
Meteor resolves dependencies by loading files in specific order into the global namespace. Is there a way I could tell flow that `React` (the module) is already available in scope? I'd like to add something like the following into my declarations:

```javascript
declare var React = require('react');
```

where `'react'` identifies the module.

**Comment by jeffmo** [comment]
There is an undocumented type annotation you can use called `$Exports<'MyModule'>` which represents the type of a module's exports. You can see it in use here (used effectively for aliasing the 'React' module to a lowercase 'react'):

https://github.com/facebook/flow/blob/master/lib/react.js#L184

In the future we may remove that particular usage of the annotation soon, but I don't think we'll remove the special annotation until we have a more first-class replacement for it (like `export ... from ...` syntax in module declarations).

**Comment by mhagmajer** [comment]
Thanks for your response, @jeffmo!

I've played with `declare var React: $Exports<'react'>;` and found out that it has slightly different semantics than `var React = require('react')` when used for cross-module checks. Here is an example:

`main.jsx`
```javascript
/* @flow */

var React = require('react');

var Welcome = require('./welcome');
var Welcome2 = require('./welcome2');

class Main extends React.Component {
  render(): any {
    return <div>
      <Welcome />
      <Welcome2 /> {/* no error */}
    </div>;
  }
};
```

`welcome.jsx`
```javascript
/* @flow */

var React = require('react');

class Welcome extends React.Component {
  props: {
    name: string,
  };
  static defaultProps: {};

  render(): any {
    return <b>{this.props.name}</b>;
  }
};

module.exports = Welcome;
```

`welcome2.jsx`
```javascript
/* @flow */

declare var React: $Exports<'react'>;

class Welcome2 extends React.Component {
  props: {
    name: string,
  };
  static defaultProps: {};

  render(): any {
    return <b>{this.props.name}</b>;
  }
};

module.exports = Welcome2;
```

`flow output`
```
[...]/welcome.jsx:6:10,8:3: property name
Property not found in
[...]/main.jsx:12:7,17: type parameter D of React element: Welcome

Found 1 error
```

I found that the following is a viable workaround although it has some runtime effects that I'd prefer to avoid:

```
var _React = require('react');
declare var React: typeof _React;
```

Also, the constructions above works only if included in all the files that use React. If I put it in declarations files it wouldn't do the prop types validation.

**Comment by mhagmajer** [comment]
Also `$Exports<M>` doesn't seem see modules specified by paths:

```javascript
var Welcome = require('./welcome'); // ok
declare var Welcome: $Exports<'./welcome'>; // exports of module ./welcome
// Required module not found
```
