### ISSUE TITLE
Flow does not understand default function parameters

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#4831]
Example: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBDACgCMwBeMAbQF0BKMAb1TDACcBTfJh6kqAOgC2ZAA4UKADza0AfGDnJVLANyoAvulwkAzvjC46YbJhgxtqSri1A

**Code:**
```
/* @flow */

function a(b = []) {
  return b.map((x) => x * x);
}

const c = null;

a(c);
```

**Actual result:**
```
4:   return b.map((x) => x * x);
            ^ call of method `map`. Method cannot be called on possibly null value
4:   return b.map((x) => x * x);
            ^ null
```

**Expected result:**
```
No errors
```

**Comment by xdissent** [comment]
Default arguments aren't applied with `null`, only `undefined`.

**Comment by apsavin** [comment]
Oh, you're right, thanks.
