### ISSUE TITLE
Can't access properties on rest pattern of map-like object (new in 0.54)

### ISSUE THREAD

**Issue by dotch** [facebook/flow#4832]
When using destructuring with a rest parameter on a map-like object type, flow 0.54 seems to treat the `...rest`'s type to not be map-like or accept property accesses. (It previously worked in 0.53). [Try Flow](https://flow.org/try/#0FAFwngDgpgBA8hEBLA9gOwM4wLwwN4DUA2gNZRgBcMGIATkmgOYC6VN9TAvgNzDAA2UEDBRUEydFlx4AHlQBEM+QBoYlGPLDyeAofhmqAdMdpQanHCN7BTNQ2G5A) example:

```JS
type Options = {+[key: string]: string};

let o: Options = {x: "x", y: "y"};
let {x, ...rest} = o;

rest.y; // Error: No property y on rest pattern
```

Though flow does seem to accept setting the rest pattern match back to a map object and then accessing properties on that:

```js
type Options = {+[key: string]: string};

let o: Options = {x: "x", y: "y"};
let {x, ...rest} = o;

let r: {[key: string]: string} = rest;
r.y
```

**Comment by taion** [comment]
I'm hitting this as well: https://flow.org/try/#0MYewdgzgLgBAtgQwA4C4YG8YG1oCcCWYA5gLppz4AeApgCYwC+MAvBjAEYK5oDMjA3AChQkWJgB0k3NWiMW8ZPyA

This can be demonstrated with something as minimal as:

```js
const map: { [string]: mixed } = { bar: 3 };
const { ...rest } = map;
```

The type on `rest` is inferred as `{}`, rather than `{ [string]: mixed }`.

**Comment by SamChou19815** [comment]
this now works
