### ISSUE TITLE
Failing test cases for $Call

### ISSUE THREAD

**Issue by AriaMinaei** [facebook/flow#4833]
Here are a few failing cases for `$Call` as of a2878dc0ac6e986678eebf543b9bd2afe37215da:

```javascript
function makeArray<V>(v: V): Array<V> {
  return [v]
}

(makeArray('foo'): Array<string>); // Pass
(makeArray('foo'): Array<number>); // Pass: Errors correctly
(makeArray('foo'): string); // Pass: Errors correctly

(['foo']: $Call<typeof makeArray, string>); // Pass
(10: $Call<typeof makeArray, string>); // Pass: Errors correctly
([10]: $Call<typeof makeArray, string>); // Fail: Should error, but doesn't

type RandomTypeConvertorFn = 
  (<V, A: Array<V>>(a: A) => {[key: string]: V}) &
  (<O: {}>(o: O) => $ObjMap<O, typeof makeArray>)

({a: 'foo'}: $Call<RandomTypeConvertorFn, Array<string>>); // Pass
({str: ['str'], num: [10]}: $Call<RandomTypeConvertorFn, {str: string, num: number}>); // Pass
({str: [10], num: ['str']}: $Call<RandomTypeConvertorFn, {str: string, num: number}>); // Fail: Should error, but doesn't
```

**Comment by AriaMinaei** [comment]
`$Call` can open up some very nice metaprogramming opportunities, but atm, there are too many cases where it produces the wrong signature, so it's only usable for very basic use-cases.

@calebmer If you guys plan to improve it, then I'll happily spend some time and put together minimal test cases that demonstrate the bugs.

**Comment by apsavin** [comment]
@calebmer one more [wrong case](https://flow.org/try/#0C4TwDgpgBAwghgGwRATlAvFAPAQQDRQBiAjAHwAUJAlBqVOTjenQCTxJYkE6kDcAUPwAmEAMYI4KaADdJUALZwA1hEIA7AFyxEyFAKgGo-WWgBmGBctVry5AB5M6dqACooDgSahSAzlrUArvIARqgWpuQATFSecgDmFooq6rYOtFAABiwA3nYAvhkxxnK+Wj7AKACWagmYcVExQA)

```js
type Caller = <A, F1>(F1) => (A) => $Call<F1, A>;

declare var makeFn: Caller;
    
var f = makeFn((x) => x * x);
var res: number = f(2);
var g = makeFn((x) => `${x}`);
var res: string = g(2);
```

Currently flow reports errors in the code above, but as far as I understand, should not.

**Comment by AriaMinaei** [comment]
Another case, from [this conversation](https://twitter.com/ariaminaei/status/916358528620736512).

```javascript
// @flow

interface ReactiveObj<O: {}> {
  prop<K: $Keys<O>>(K): $Call<DecideType, $ElementType<O, K>>
}

interface ReactiveArray<V> {
  index(number): $Call<DecideType, V>
}

interface ReactiveBox<V> {
  unbox(): V
}

type DecideType =
  & (<O: {}>(O) => ReactiveObj<O>)
  & (<V, A: Array<V>>(A) => ReactiveArray<V>)
  & (<V>(V) => ReactiveBox<V>);

type TestObject = {
  str: string,
  obj: {
    strInObj: string,
    numberInObj: number,
    arrayInObj: Array<number>,
  }
};

type TestObjectReactified = $Call<DecideType, TestObject>;

declare var testObj: TestObjectReactified;

(testObj.prop('str'): ReactiveBox<string>);

// $FlowExpectError This line causes two separate errors, only one of which gets silenced
(testObj.prop('str'): ReactiveBox<number>);

// This should not be an error, but it is:
(testObj.prop('obj').prop('strInObj'));

// This should also pass, but it doesn't:
(testObj.prop('obj').prop('numberInObj'): ReactiveBox<number>);

// $FlowExpectError This errors, but for the wrong reason:
(testObj.prop('obj').prop('numberInObj'): ReactiveBox<string>);
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoASlkRigG5YDyARgFYA8dAXKAN4C+AfN0ShQABxywRLANKcAJFKwBPAM5s+fABRSAlHIDC+aNBYARLIRQATLABVFIrABpQsgKLQsAWyyY7Dts5S6og8yOjYeEQk5JQ0WACCODj4iiwAagJcQqDo1gAeGmgArp4MuLouBkam5la29k6gGSFhmLgExGQUhFS0AEKweemZ2UVoDIMaFWktiBgNoGYW1n4kALzZAGSgGmycvJp02qBrAjE9cYysdHzaWzvpzvGcicmpGZrxx6ddsbSvKWGd2E212GQ0aW+Z26vSwAyGGW0AG5kPMHKAbFhlBgruYMCdBMJsThOMT0ABzRzZWDMfbZIkYHAASTQV1JjIpVOEwmKpVwLLZoF5ZRwXO5+CSKQFtNAANSwtwfDFoR4KLmC0x2NxPXOVEgKCwlgJsiqxiWdVWzk1OOYeL4aushGgEpI1AloGwWpl1u1GF1KH1hrVGk9NqYADoxBINAByYkxir+-qDFhktDk25qkAuABicHgrjyDh6riSsBwGIAFihlKBoOgSIR8EVlFiPfBYKBWyIJfhsKBcOIcMpnLA0NBFKAxyRYJBQPBq4RK6ByVgMLXlCgPGhiJZECGsWHI+IRLH44mYXF4SwFThM8hszZqxvK7AitAjWhYPiyqB8GgBzLUVQAYIp8RQcDlHYfdQyuY9oxjGkmATeDTzjRlpWQ7RkQfMAnxrLtX3fI1DGUTse2UEcQLAnJ8UsWAsTQGMMGgg8vQjKM0KQlDONjW9MITTgkzhFNb3vRBs1kPMEELYsMFLIcqwIwdyyo0D8UgcsPUrEh4HEdNQBwCgyLQVjYOYVDY247RLJjfjWWYQTfguZMhjTDMcKAA)

**Comment by dwb** [comment]
I'm sure this closely related to the cases already posted, but this one has an interesting property which might help trace the bug. Commenting line 14 results in no errors, but also uncommenting line 6. If you then add another property to the object (with a third type, such as `boolean`) and add a corresponding `fn(obj, 'foo')` call, three duplicate function declarations are required for "no errors".

Given this, I feel like if I knew about Flow internals I'd know pretty much exactly what's going on, but I don't so leaving it here for someone who does.

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoCcCeYArgHYDGcAtpQKYkAuAliQOZgzM1gBsANGHFxgK1Ok1btOYAIwAWAHToAJjTIwAhri5RSZJnBJgoJADwB5AFxgzAIwBWq+vwDSVgM71czFgD4AFHBWZvwA1lbOAJRWACQAwuowMCYm2P7YEWAAvD44-NEAojA0tAzY+AAONOYuPj4YWCpqmtq6+obG5kH2ji7unt7+gdah4VFgcQlJKWkZ2bnjhcViZZXVYM616BQkHgL2WWAA3qhgYCTqtFYA5ABS6iQ0V7wnYOosNFYATADMzwC+6AA3H5jAF7PwrudaFcxh4vKwIqhgaC4OCwFc3o8xiQiJQbDRcBEgA)
