### ISSUE TITLE
Specifying method return type suppresses errors 

### ISSUE THREAD

**Issue by uforic** [facebook/flow#4835]
On flow.org/try, the following example throws expected errors, since the array of strings is not an array of type foo:

```
// @flow

type foo = {
	a: number
}

function method1<T>(items: Array<T>) {
    return items.slice(0, 1);
 }

function method2(arg: Array<foo>) {}

var var1 = (["array", "of", "strings"]: Array<any>);

const meth1return = method1(var1);
method2(meth1return)
```
By adding a return type of method1, the errors go away:
```
// @flow

type foo = {
	a: number
}

function method1<T>(items: Array<T>): Array<T> {
    return items.slice(0, 1);
 }

function method2(arg: Array<foo>) {}

var var1 = (["array", "of", "strings"]: Array<any>);

const meth1return = method1(var1);
method2(meth1return)
```

In my IDE, in both cases, the flux created tooltip is indicating it believes that method1 output and array of T, so it's very odd that specifying that as a return type would suppress the syntax error.

Tagging: @dmnd

**Comment by dmnd** [comment]
I'm surprised that first example gives a type error given the `Array<any>` annotation. 

`items.slice` returns `typeof items` which I think should is `Array<any>`. But if that were the case, the call to `method2` wouldn't error. So something surprising is going on.

**Comment by SamChou19815** [comment]
We now always require return annotations on generic functions.
