### ISSUE TITLE
Trailing comma after rest parameter not handled correctly

### ISSUE THREAD

**Issue by Daniel15** [facebook/flow#4836]
```
class Foo {
  hello(
    name: string,
  ) { }
  
  works<TOutput>(
    ...extraProps: Array<any>
  ): void { }

  fails<TOutput>(
    ...extraProps: Array<any>,
  ): void { }
}
```

Throws:
```
11:     ...extraProps: Array<any>,
                                 ^ Rest parameter must be final parameter of an argument list
11:     ...extraProps: Array<any>,
                                 ^ Unexpected token ,
12:   ): void { }
      ^ Unexpected token )
12:   ): void { }
       ^ Unexpected token :
13: }     ^ Unexpected end of input
```

Tryflow: https://dl.vc/1d

**Comment by samwgoldman** [comment]
AFAIK, it's the correct behavior to error on the trailing comma here, but we should swallow the comma so we don't barf on the rest of the file.

cc @mroch

**Comment by asolove** [comment]
Just as a point of reference, node currently errors on the trailing comma, while babel allows it.

**Comment by Daniel15** [comment]
@asolove I don't think trailing commas are standard (yet) so Node.js would likely error on them even when not using rest parameters.

**Comment by lll000111** [comment]
@Daniel15 Testing node.js 8.4.0:

Works:
```js
function demo(arg1,) {}
```

Doesn't work:
```js
function demo(...args,) {}
```

**Comment by Daniel15** [comment]
> Works:
> ```
> function demo(arg1,) {}
> ```

Oh cool, i didn't know that it was standard now :D

**Comment by jcready** [comment]
> But it means that formatting is inconsistent and trailing commas can't actually be used everywhere :(

What is the desire to use trailing comma after a rest parameter? Unlike normal formal parameters, if you tried to add another parameter after a rest parameter it will be syntactically incorrect.

**Comment by Daniel15** [comment]
>What is the desire to use trailing comma after a rest parameter?

Consistent formatting. "Always use trailing commas" is easier than "always use trailing commas except for after a rest parameter"

**Comment by lll000111** [comment]
But when formatting conflicts with semantics the latter should always come first. A comma after a rest parameter is just plain wrong, semantically.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
