### ISSUE TITLE
Refining React Component Types

### ISSUE THREAD

**Issue by deecewan** [facebook/flow#4838]
[Example at try flow](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkiVgQBbAA2AJlOdjAJ5hLV2PkCCUUFKxbtOAUVpIQ5eAF84AMyhE4AciboYqgNwAoXQoCuJDMFJwAYhAgAKAJS5dcOExiGoJODYA89YADcAPisIAEJvAHo-ILs9WX0QgDo-AGcwWiEAORRpOABeNRCdfTQMlJS4ACEUKDgkAA8YcnoKwmIyCm8cWUDHZxSYFBhgNDhU9KyczgLVaqhipxdmpCh7Pucltw8vXwDAufCovdjF+PjdNg4qmoAVUXy4CSkZb0ukCAVrqEC9N8trO5XApPaSdN4ff4QH76IwmYbmADugjAcxsACMagAuL6ApAOHCLVzuTw+aL7GpwAC0uAxUFkkTJJ3OsNMiORIRsCms2JCuPxhKQWxJuyCISpuC5EHpRxicX0fwACsowClcQ8Cc40DQGEwSNj8NqeCR+IJWN45mqAD6Q3GBXTM4yszwgFBgA3cGzAJogbEW+7W3mifnOYCfT3exJvZLANIZVjZXJ5JNqOaqYMbInbJGu1FeqQnZznZyZzzZsAcvMgJkwx3wzwAdWRHFWYGVKWxSogKr56xLXkWzhFdo2Gxw7p15ESLrANlbXZSiS13F12Gn4-odniI4Ze0W1ZHzgHGyAA)

Looking to refine some components that get passed into a function.
Essentially, I want to refine which components are passed in so I can call some helper function on them.

For example, if I wanted to display some children in different ways depending on type. I thought that maybe giving a static property, like `displayName` would let me refine.

```js
import React, { Component, Children, type ChildrenArray, type Element } from 'react';

function Foo() {
  return (<div>Foo!</div>);
}

Foo.displayName = 'Foo';

class Bar extends Component<{}> {
  static displayName = 'Bar';

  render() {
    return (<div>Bar!</div>);
  }
}

type BarType = Element<typeof Bar>;
type FooType = Element<typeof Foo>;

function wrapBar(bar: BarType) {
  return (<div>Bar - {bar}</div>);
}

function wrapFoo(foo: FooType) {
  return (<div>Foo - {foo}</div>);
}

type PropsType = {
  children: ChildrenArray<BarType | FooType>
}

function mapChild(item: BarType | FooType) {
  if (item.type.displayName === 'Bar') {
    return wrapBar(item);
  }

  return wrapFoo(item);
}

function Wrapper(props: PropsType) {
  return (
    <div>
      {Children.map(props.children, mapChild)}
    </div>
  );
}
```

See the [try flow example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkiVgQBbAA2AJlOdjAJ5hLV2PkCCUUFKxbtOAUVpIQ5eAF84AMyhE4AciboYqgNwAoXQoCuJDMFJwAYhAgAKAJS5dcOExiGoJODYA89YADcAPisIAEJvAHo-ILs9WX0QgDo-AGcwWiEAORRpOABeNRCdfTQMlJS4ACEUKDgkAA8YcnoKwmIyCm8cWUDHZxSYFBhgNDhU9KyczgLVaqhipxdmpCh7Pucltw8vXwDAufCovdjF+PjdNg4qmoAVUXy4CSkZb0ukCAVrqEC9N8trO5XApPaSdN4ff4QH76IwmYbmADugjAcxsACMagAuL6ApAOHCLVzuTw+aL7GpwAC0uAxUFkkTJJ3OsNMiORIRsCms2JCuPxhKQWxJuyCISpuC5EHpRxicX0fwACsowClcQ8Cc40DQGEwSNj8NqeCR+IJWN45mqAD6Q3GBXTM4yszwgFBgA3cGzAJogbEW+7W3mifnOYCfT3exJvZLANIZVjZXJ5JNqOaqYMbInbJGu1FeqQnZznZyZzzZsAcvMgJkwx3wzwAdWRHFWYGVKWxSogKr56xLXkWzhFdo2Gxw7p15ESLrANlbXZSiS13F12Gn4-odniI4Ze0W1ZHzgHGyAA) for the errors. 

There is every chance I'm going about this the wrong way. Any advice?

**Comment by jcready** [comment]
Does this not work for you?

```js
if (item instanceof Bar) {
```

**Comment by deecewan** [comment]
it does not, because they're instances of React Elements, not instances of the class.

i've also tried `item.type.prototype instanceof Bar`, etc. Still doesn't refine the type.

**Comment by SamChou19815** [comment]
We don't intend to support this pattern of inspecting react internals
