### ISSUE TITLE
Indexer Property Subtypes

### ISSUE THREAD

**Issue by ddgromit** [facebook/flow#4843]
Objects created with indexer properties can't be matched to other objects created with indexer properties unless both the keys and the values are identical.  Subtyping does not work with indexer properties:

```js
// FAILS: keys don't match exactly
function testStringToMixedKeys(strObject: { [string]: number }) {
  (strObject: { [mixed]: number })
}

// FAILS: keys don't match exactly
function testStringUnionToStringKeys(strObject: { [('a' | 'b')]: number }) {
  (strObject: { [string]: number })
}

// FAILS: values don't match exactly
function testNumberToMixedValues(strObject: { [string]: number }) {
  (strObject: { [string]: mixed })
}
```

Even though calling $Keys on an object with indexer properties does allow matching:
```js
// WORKS: calling $Keys on an object resolves correctly
function testObjectKeysSubtyping(keys: $Keys<{ [string]: number }>) {
  (keys: mixed);
}
```

[Flow Try](https://flow.org/try/#0FAehAIDEEEEkBkDKAucBrApgTwM7gCYD2AdgOQAu4AtgIbkDGAFuBgB433kA2WwAZgFdinAJYlw5DDnKJyAJxHEA5gBVCAWRGsM+ANLYcACmlyA8gCMAVhk6oA3uADaJxUoC6qYgKrmMc8AC+AJTgdsDg4MbyFta2oU5UWjoe4F4+foFBwAHAoBAwCCjoBgQkFNR0TCzsnDz8QqLiktKyCsoAqsRixGqtrvq4UWZWNuT2ToakNKTgAD7gpOakQSlpvv7BoeGRJjGj487yrqve65nZuWBQcEioAG40XAJSpWSUtAzMbBzcvILC5G6EikMiOyjUmm0+AAao9nkZdiM4g5Dm13J5ThlNmEIkM9sinC5lClElDzjk8uAAOqmABKuiK9EeXFc4AAJAM8OIaMRwIQkZQ5FJCFw7i96IQ5ELan8GoCmiD8eROYgBOZyFgAA6uQyYXCoDkGAA8KKJ6NSmI2AD4QjjInqcKhSToggBuC5AA)

This problem comes up with functions that iterate over generic objects with `Object.keys` and return objects that have the same keys.  e.g. #3325

**Comment by asolove** [comment]
Just a note to say that I think the first failure is expected, though the second one seems like a bug to me. An object that only takes a or b as keys cannot be considered a subtype of an object that takes any string key, because it can't be used safely in all the places that the other can.

**Comment by jtbandes** [comment]
Similarly, I'm trying to express an object that can have indices assigned to `interface A { [n: number]: number; }` and finding that I can't downcast this to `interface B { [n: 0 | 1]: number; }`. It seems that any `A` object should be able to be "safely" treated as a `B`, yet `function(x: A): B { return x; }` [doesn't work](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCCYA3qmGANpYBcYWArgLYBGhAum069CAblQBfTLkIlyYAEK16TVmAAMYAD5gAjIPbc+BcVNRQOWUjgxwsYKHDgAKAB5tKASjZK6DAng4HAT2rqaoQA).

**Comment by gkz** [comment]
This is expected - mark the supertype as read only and it works: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyMTXpyOnE2goLcegHTksRk0IPHT5y-JsYdpSkzoYm+AhEWGhCKmZ6lgC+6hAi1AA6UAD0WQAEAGIAggCSADIAysi5ANYY-PS5QtAA5Li5rrhgABa5XDw0-JkwJHhw0Lm4GPS45TJwUAgAKhAAsnCcGEIA0nX0ABTTaADyvABWGHhVwLkA2ofzCAC6VYrkvIG5iQCUucCZubkDjITudLr9cgBqG7kdabZ65V7vNCfL6ZRKZTI5AolCpVWr1RotNodbq9bh4AZDEY6KATKYzOYLACqUDGUGWszsCx29SBxzOF1wV1ue2aWGauQAPrlmrxml94YiPt9fv9AYcQYLhVD7gtFUokSi0RjsnkimVKrkAG56IhTQlQVrtLCdHp9CmDWDUtl06ach7LNYbIQANVtUz5mrB1zujKeLwNyp+f1p6uBAujkNjXPj7VhQiNUHRUExeQA6kcAEpbS1gPQ0B65AAkPIa4ywtIgGbamHoEBoVvtkDQmA9VKgo3Gk2mUdwrfKRF4YQee3x9CqLd2AB4Y7rc0rkYkAHzJtWr3ZVGHBr4AbmNUDYIEHaCY0GoVoADE4AEwfgAcTgAIwgIkQA
