### ISSUE TITLE
Tuple incompatible with array

### ISSUE THREAD

**Issue by chrbala** [facebook/flow#4844]
Repro:
```javascript
/* @flow */

type TupleType = [string, string];
const concat = (input: Array<string>): string => input.join(' ');

const myTuple: TupleType = ['hello', 'goodbye'];
concat(myTuple);
```
Results in:
```
7: concat(myTuple);
          ^ tuple type. This type is incompatible with the expected param type of
4: const concat = (input: Array<string>): string => input.join(' ');
                          ^ array type
```

It seems like tuples should be able to flow into arrays of the same type. What is the reasoning behind this design? Is there a good way to fix this with different type signatures? The best solution I've found (aside from the $FlowFixMe comment) is to run ``concat([...myTuple]);``, but that's less than ideal because it's negatively impacting runtime performance.

Using flow 0.54.1

**Comment by vkurchatkin** [comment]
You need to use `$ReadOnlyArray` instead, otherwise it would be possible to mutate length of the tuple:

```js
type TupleType = [string, string];
const concat = (input: $ReadOnlyArray<string>): string => input.join(' ');

const myTuple: TupleType = ['hello', 'goodbye'];
concat(myTuple);
```
