### ISSUE TITLE
remove disinformation from flow.org

### ISSUE THREAD

**Issue by hrgdavor** [facebook/flow#4845]
remove/change following statement from flow.org 

> > Flow is designed to understand idiomatic JavaScript. It understands common JavaScript patterns and many of the weird things we JavaScript developers love to do.

Reason: since there is no official response about issue #396 , and the sentiment is that there is no plan to support the feature. The issue is from "Apr 17, 2015" is a deal breaker for many using this pattern.

**Comment by vkurchatkin** [comment]
I don't see a problem with this quote. Flow indeed supports many, but not all of the existing patterns. That said, the way of achieving https://github.com/facebook/flow/issues/396 is rather simple: you can put all the declarations your need alongside your code and edit them the way you want.

**Comment by hrgdavor** [comment]
@vkurchatkin I added this ticket just to confirm if there is intention to ever implement #396. It would be nice if you could mark #396 as "wont-fix" so those that are interestd know it.

Workarround you mentioned is pretty vague and sounds like maintenance nightmare. Sorry for aggressive ticket title, I just wanted to know if I should hope for a fix.

I was very excited about flow, and tried it on some sample code. Dissapoited that a such a common and useful pattern is being ignored, it is just not worth the hassle.

I turned notifications for #396 hoping that in few years you might reconsider and someone implements it. :( :( :(

**Comment by vkurchatkin** [comment]
> It would be nice if you could mark #396 as "wont-fix" so those that are interestd know it.

I don't have authority to do so. /cc @calebmer

**Comment by ELLIOTTCABLE** [comment]
A huge :+1: here — while I'm relatively ambivalent on #396 (Facebook's team can direct the project as they see fit, of course! Their use-cases may not align with the rest of ours', and that's totally fine), *this* is a whole different matter.

It is genuinely a huge misrepresentation to tell JavaScript developers that Flow is “built to work around common JavaScript idioms”, and then to *not support literally the single most common JavaScript idiom.* Extension is more common than IIFEs, more common than other forms of prototypal inheritance, more common than literally anything except maybe Promises nowadays.

Seems like a trivial decision to me, at least from the outside: Remove the problematic claims from the homepage, be clear about your direction, and let's all work together not to waste one another's time. ☺️
