### ISSUE TITLE
import loader of flowtype for node

### ISSUE THREAD

**Issue by spoike** [facebook/flow#4847]
Are there any plans for an import loader for pure server-side node much like [@std/esm](https://github.com/standard-things/esm)? This will eliminate the need of running builds (such as babel) for node-only code.

I.e. that you should be able to do something like and type annotations in required modules won't bother node (other than validation errors):
```
require = require("flow-node-or-whatever")(module)
```

**Comment by TrySound** [comment]
There is [flow-remove-types](https://github.com/flowtype/flow-remove-types/#use-the-require-hook) to solves this.

This probably can be closed.
/cc @vkurchatkin
