### ISSUE TITLE
Provide a way to clever merge Props and defaultProps of an React Component

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#4848]
Code example:
```jsx
// @flow
import * as React from 'react';

type Props = {
  foo: number, // foo is required.
  bar: 'bar' | 'baz', // bar is not required: it's in the defaultProps
};

class MyComponent extends React.Component<Props> {
  static defaultProps = {
    bar: 'bar',
  };
}

// all's fine
<MyComponent foo={42} />;

// but how to type an object that will be passed to MyComponent via spread?

// 1. Obviously wrong way: flow will not try to understand how we will use myCompProps
// const myCompProps: Props = { foo: 42 }; // - property `bar` missed

// 2. Less obviously wrong way
// const myCompProps: $PropertyType<MyComponent, 'props'> = { foo: 42 }; // - property `bar` missed

<MyComponent {...myCompProps} />;
```

You can [try it](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciiOAnukqgACo3RkAvKADeiUKEixYALlAA7AK6oARpSwAaUCEXLQyMuwCOm5OwAmAOnmgdRLGpZusLUAB9WNwAvFiMTb3MydVg8a1sHNWQcFjJkdVAcAAthe0pIIk1oHDFYCUQAXx5EGmhSMgBZfgBhJkx1SnU8SgAPHA77MipaHEcWjFh2zoAeEokAPlkXEhwiHGQaUFz8wuLxKUWFBW9Pb1CXSoreEyJoaBTFNMpEKcaxto76ZUkZABYAJnKxjmVXCmjwmQQGVgGUEwiI6VgOgAVpQ6BlMqtQPBkLdXMJ0HVKPYoaBXq0Jh9QAA3ZBEUAkdDsIj2AD8VzAAEZHKAAPI6GmwTQkaD8LGMdQAcyxRH4ahgkOxuOieBwWFFOGhmnUuSwy3hxIh8CxwkV0FAQuEqGarVmJEQJhoE2WoCtb1taltoGkMlMqlA-1AlWMYAAtKBGaV9AJQAADbwxl0WEhE9mgP7cgAylBIZERAqFIrFEyl8Bl9rAjvUztdNr2agAJLMo-wACqwl7W8aTHBGFgRiQsBbe31qAMXZ5kruUmSOWc1jC2wHAYFAA)

So, we need a convinient way to create a type based on `Props` and `defaultProps`. It should be exactly like `Props`, but all props from `defaultProps` should be marked as optional.

**Comment by chrisdrackett** [comment]
I'm guessing this is the same issue, or at least similar:

```js
// @flow
import * as React from 'react';

type Props = {
  foo: number, // foo is required.
  bar: 'bar' | 'baz', // bar is not required: it's in the defaultProps
};

class MyComponent extends React.Component<Props> {
  static defaultProps = {
    bar: 'bar',
  };
}

// all's fine
<MyComponent foo={42} />;

function getComponent(compProps: Props) {
  return <MyComponent {...compProps} />
}

getComponent({foo: 2})
```

try flow link: [try it](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciiOAnukqgACo3RkAvKADeiUKEixYALlAA7AK6oARpSwAaUCEXLQyMuwCOm5OwAmAOnmgdRLGpZusLUAB9WNwAvFiMTb3MydVg8a1sHNWQcFjJkdVAcAAthe0pIIk1oHDFYCUQAXx5EGmhSMgBZfgBhJkx1SnU8SgAPHA77MipaHEcWjFh2zoAeEokAPlkXEhwiHGQaUFz8wuLxKUWFBW9Pb1CXSoreEyJoaBTFNMpEKcaxto76ZUkZABYAJnKxjmVUgmnUdGQE1AAHNKDg3hMPgAKGitWYkNTogCUB1A7Bwmiw6RezVaiM6skcVNRGHRgOAc0uiFh8LJkxwSJkSlUoABWN4iCAA)

**Comment by AndrewSouthpaw** [comment]
What [about this](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciiOAnukqgACo3RkAvKADeiUKEixYALlAA7AK6oARpSwAaUCEXLQyMuwCOm5OwAmAOnmgdRLGpZusLUAB9WNwAvFiMTb3MydVg8a1sHNWQcFjJkdVAcAAthe0pIIk1oHDFYCUQAXx4+QWEAETyCopKJUGk5BW9Pb18AryIQgwreGmhSMgBZfgBhJkx1SnU8SgAPHAX7MipaHEcZjFh5xYAeZpIAPlkXEhwiHGQaUFz8wuLxEjV656a31suFDvcXXcoRclSGiBMRGg0BSijSlEQR0mezmC3oykkMgALAAmcrGM5VcKaPCZBAZWAZGrEdKwHQAK0odAymVuoHgyGhrmE6DGlHsFNAyNmBzRoAAbsgiKASOh2ER7AB+XgmACMjlAAHkdJLYJoSNB+OzGOoAObsoj8NQwckcrnRPA4LBGnCUzTqXJYa5ED2gMnwdnCO3QUD64SoaazU4QsA0A7XUARlGnNSnX4yUyqUC40CVYxgAC0oDlpX0AlAAANvBXExYSPyVWAcRqADKUEhkOm6-WG40Hc3wS0x0Bx9QJpNRt5qAAkzTL-AAKjUkZH9occEYWCWJCwLm1M2oc2DEKPx6v0CnQNPashIJATm8jJ9Gq9Sud0wfszjc1UVyjRYssiOMBE4YKc+LAISQA)? It requires explicit typing of the default props, which stinks, and could get stale quickly, but at least it's a start...

**Comment by apsavin** [comment]
@AndrewSouthpaw Unfortunately it's not a right way, too, because it [makes components unsound](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciiOAnukqgACo3RkAvKADeiUKEixYALlAA7AK6oARpSwAaUCEXLQyMuwCOm5OwAmAOnmgdRLGpZusLUAB9WNwAvFiMTb3MydVg8a1sHNWQcFjJkdVAcAAthe0pIIk1oHDFYCUQAXx5EGmhSMgBZfgBhJkx1SnU8SgAPHA77MipaHEcWjFh2zoAeEokAPlkXEhwiHGQaUFz8wuLxKUWFBW9Pb1CXSoreEyJoaBTFNMpEKcaxto76ZUkZABYAJnKxjmVXCmjwmQQGVgGUEwiI6VgOgAVpQ6BlMqtQPBkLdXMJ0HVKPYoaBXq0Jh9QAA3ZBEUAkdDsIj2AD8VzAAEZHKAAPI6GmwTQkaD8LGMdQAcyxRH4ahgkOxuOieBwWFFOGhmnUuSwy3hxIh8CxwkV0FAQuEqGarVmJEQJhoE2WoCtb1taltoGkMlMqlA-1AlWMYAAtKBGaV9AJQAADbwxl0WEhE9mgP7cgAylBIZERAqFIrFEyl8Bl9rAjvUztdNr2agAJLMo-wACqwl7W8aTHBGFgRiQsBbe31qAMXcv0iGFYlZRhG-SMDyudyRczqR0YVbIHTQJ6V6ud9Du0D1gAiyEgkBmeyMAiEsEgpMPFM6ji2BSKtqHshH-r+RmOVhumA3xxw7N4XzwGRHBgmsMFtQFgGBIA)

**Comment by AndrewSouthpaw** [comment]
Hmm. How about combining `$Diff` and `$Shape` [in an intersection](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciiOAnukqgACo3RkAvKADeiUKEixYALlAA7AK6oARpSwAaUCEXLQyMuwCOm5OwAmAOnmgdRLGpZusLUAB9WNwAvFiMTb3MydVg8a1sHNWQcFjJkdVAcAAthe0pIIk1oHDFYCUQAXx5EGmhSMgBZfgBhJkx1SnU8SgAPHA77MipaHEcWjFh2zoAeEokAPlkXEhwiHGQaUFz8wuLxKUWFBW9Pb1CXSoreEyJoaBTFNMpEKcaxto76ZUkZABYAJnKxjmVXCmjwmQQGVgGUEwiI6VgOgAVpQ6BlMqtQPBkLdXMJ0HVKPYoaBXq0Jh9QAA3ZBEUAkdDsIj2AD8VzAAEZHKAAPI6GmwTQkaD8LGMdQAcyxRH4ahgkOxuOieBwWFFOGhmnUuSwy3hxIh8CxwkV0FAQuEqGarVmJEQJhoE2WoCtb1taltoGkMlMqlA-1AlWMYAAtKBGaV9AJQAADbwxl0WEhE9mgP7cgAylBIZERAqFIrFEyl8Bl9rAjvUztdNr2agAJLMo-wACqwl7W8aTHBGFgRiQsBbe31qAMXcv0iGFYlZRhG-SMDyudyRczqR0YVbIHTQJ6V6ud9Du0D1gAiyEgkBmeyMAiEsEgpMPFM6ji2BSKtoWADITwBlDEhGvUoSCHWQR39P4jGOVhujg3xxw7N4XzwGRHHQmsMFtQFgGBIA)?

**Comment by apsavin** [comment]
Hmmm, looks good, I'll try to use it in real codebase and see if it works on more cases.

Thank you very much!

**Comment by apsavin** [comment]
It works + we have [React.ElementConfig](https://flow.org/en/docs/react/types/#toc-react-elementconfig) now.
