### ISSUE TITLE
Union + $PropertyType not working properly

### ISSUE THREAD

**Issue by hackhat** [facebook/flow#4849]
Reproduce at : https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagGK1qALygDeoaWAXKAOST42gC+A3ChtgEICGATkaXIdqNAEZ9GrdllABVAHYBLWPIF4CAH1A9ebRAGMVAZ2ShulACQAFXrCy80AFQ4AeBcvkAaWhUw0AfAI0AEw0LKAgoEYAFrAArtAAJqCYvLa8BsamopY2dqlOru4q3jS+AQLB4ZGp6UZAA

Code: 

```
    // @flow
    type Foo = { type: 'foo' };
    type Bar = { type: 'bar' };
    type Union = Foo | Bar;

    const a:$PropertyType<Union, 'type'> = '2'; // should error
    const b:$PropertyType<Union, 'type'> = 2; // errors

```

I expect both to error, but only the second does.

**Comment by jonasi** [comment]
This appears to have been fixed as of v0.55.0
