### ISSUE TITLE
Do not ask for annotations of class methods when interface is in use

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#4852]
Given the code

```js
interface IFoo {
  method(p: string): string
}

export class Foo implements IFoo {
  method(s) {
    return s;
  }
}
```

**Actual result**: 
```
8:   method(s) {
            ^ parameter `s`. Missing annotation
```

**Expected result**: 
`No errors `

(all annotations are in the interface, no need to duplicate)

You can [try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAkgGKyygDeiAkALZYYAWsAJgBQAOAXKADOGHOgDmASgHDRaMYgC+yLAA8esHBlCFo+QYNCVqKRj2hZmmAxSq1EoUMzacugiXYcOcLAK440QgDc9qBKCkA)

**Comment by miracle2k** [comment]
See https://github.com/facebook/flow/issues/3798

**Comment by apsavin** [comment]
Yeah, it's the same, thanks
