### ISSUE TITLE
False positive: computed property names

### ISSUE THREAD

**Issue by ADagen** [facebook/flow#4861]
We have a number of constants to maintain property names we are retrieving from the REST API.

Since v 0.54.1 flow do not take in account computed properties emitting error "Property not found in object literal", [here is the example](https://flow.org/try/#0C4TwDgpgBAgg7hAzgewLYQCrmgXigbwCgooBjAGwEsIA7YALigCNllyIBDGgGmKkQgAnAG5DGLNpx6EAvgG5ChUshqJgUAMIAZAJIBRAHIZGawZRoBzKHgDkFanRsLlq9QGU9AJQBqXk8DNLaygbAREhJ0UXNTI0MABXYAgAEwMOdERGeCQ0TGxgohIAbW19IwBdRgD4iF5ijx8vSqgAMw5yAV55KJUYtQ5gSlI0jKyEFHQsSAK+e1oGKGravjDRQUY2juXuoA
).

With this code
```javascript
type AwesomeType = {
  client: boolean,
  server: boolean,
};

const CLIENT: string = 'client';
const SERVER: string = 'server';

const computedNames: AwesomeType = {
  [CLIENT]: true,
  [SERVER]: false,
};

const staticNames: AwesomeType = {
  client: true,
  server: false,
};
```
flow outputs
```
9: const computedNames: AwesomeType = {
                        ^ property `client`. Property not found in
9: const computedNames: AwesomeType = {                                      ^ object literal
9: const computedNames: AwesomeType = {
                        ^ property `server`. Property not found in
9: const computedNames: AwesomeType = {                                      ^ object literal
```

I have no idea why this false positive has not been replicated previously (flow's playground shows error even with 0.53.1 and with all available versions).

**Comment by ADagen** [comment]
This issue is reproduced even with v0.55.0

**Comment by goodmind** [comment]
This code is wrong, correct one is:
```js
type AwesomeType = {
  client: boolean,
  server: boolean,
};

const CLIENT: 'client' = 'client';
const SERVER: 'server' = 'server';

const computedNames: AwesomeType = {
  [CLIENT]: true,
  [SERVER]: false,
};

const staticNames: AwesomeType = {
  client: true,
  server: false,
};
```
