### ISSUE TITLE
React$Node does not seem to work for React.cloneElement?

### ISSUE THREAD

**Issue by ardok** [facebook/flow#4864]
[cloneElement React$Node Example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqBAntqWAAKdbAGcwAXjABvVGDCVSMGGQB2AE1Is8ALhKsCAEgBycTQBpUAX06pKcVaKIAVUk8lgAFNMXK1m7Ss9YTgxAEpJAD4ZOTB0KC9efjgE3xVSDS0tSQkpRigAV1VqdAdGCNl5eRYCArxVMFUC5U55Ky55eK80-yy8MAAyAbAk0hSFJXTM7Ry8uAAjACtSNkHhsioCADp0UQA1chh0dQBRGFJMDIJPHoyArTCK2PlgYDAACVIeczAeOAKwJpDmAEOgCAALMBQdAwAhadCqADmI3BAiKBVEpHUYGwInEqJYzzANTqDQ21C2lHgqlIZwuVxuk162h+0isYVaYHasS6jL8dz6axGfDGqSZApmAEJckxCsUCKVVOUYlViaRavVGs0YJzudV1aStS1rOwwKggA)

I think it's more on how to "check" for $Iterable type?

**Comment by max-mykhailenko** [comment]
Try to use  [React.Element<*>](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqBAntqWAAKdbAGcwAXjABvVGDCVSMGGQB2AE1Is8ALhKsCAEgCiMUplKqCAHhAA+ADSoAvp1SU4q0UQAqpb5JgABTSispqmtrOesJwYgCUknYycmDoUMG8-HAZYSqWkVqSElKMUACuqtTonoyJsvLyLATleKpgquXKnPLOXPLpwXkRWkUAZGNgWaQ5Ckr5GqN4xaVwAEYAVqRsYBP6VAQAdOiiAGrkMOjqpuaWBEHDBUvx9anywMBgABKkPA5gPDg5TAmguYAQ6AIAAswFB0DACFp0KoAOZTKECSrlUSkdRgbAicQYlhvMDNVrtMgHQ6UeCqUg3CxWB7zEbaf7SZzxHpgPqpQYs8JPbS7SbTWaPRYigCEJSYFSqBBqqjqKUaZNILTaHS6MB5fKamopOu6LnYYFQQA
) or more precise tag name inside
