### ISSUE TITLE
Internal Error merge_job exception

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4866]
When using nuclide my flow keeps crashing / breaking -- i have no idea how to reproduce it but is a widespread problem throughout the project whenever attempting to import types.  Been trying to figure out the exact time it occurs.

```
Internal error: merge_job exception: Utils_js.Key_not_found("LeaderHeap", "/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/app/shared/components/Dashboard/types/general.js")
Raised at file "map.ml", line 122, characters 16-25
```

Closing for now - in this specific case it actually couldnt find the type because i was looking in the wrong place, however this is not the case in other places so I will open another once i have a better example.

**Comment by mroch** [comment]
running flow with the `OCAMLRUNPARAM=b` environment set should give us a better stack trace, as in `OCAMLRUNPARAM=b flow status`

**Comment by bradennapier** [comment]
Yep, I am getting these errors all over my project... I follow where the error is, delete one thing or change one thing and it shows me antoher and i follow it and it fixes it every time then next time I open the file it happens again...

**Comment by haluvibe** [comment]
I also receive this error

**Comment by mroch** [comment]
this sort of issue should be fixed. please reopen again if not!
