### ISSUE TITLE
Why is this an error?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4868]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHgIYC2OMBAvGKmGAD5gAUAlGDQHxgAKAJzjkAlgGc8AHjEYBIgHYBzbg2b8hoidNkLlqljLlL0jVFACu8gMYYRceWChw4rYgC4iZStXYeSFKgIAb1URKDZiThDGRgE8DHMBB2IAblUAX1U4hKSwYlRM9CcXAHIACxES9lQgA

I have lots of issues when attempting to use union types, quite possibly due to user error. 

Whereas this is not an error

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHgIYC2OMBAvGKmGAD5gAKATnOQJYDOeAHl4Z23AHYBzAHwNmYYaMmyWACgCUYGlLace-ISPHTZqKAFcxAYwzc4YsFDhwVxAFxEylamvckKVAgBvWW4oMBcNYMZGdjwMM3Z7YgBuWQBfWVj4xLBiVAz0R2cAcgALbmK1VCA

**ERRORS**

```js
/* @flow */

type Example = 
  | () => Promise<string>
  | Promise<string>
  | string
  
  
function foo(x: Example): Example {
  if (x) {
    return x;
  }
  return x
}


foo('hi')

```

**NO Errors**

```js
/* @flow */

type Example = 
  | Promise<string>
  | string
  | () => Promise<string>
  
function foo(x: Example): Example {
  if (x) {
    return x;
  }
  return x
}


foo('hi')

```

When attempting to use this to allow providing many ways that we will eventually resolve an object, I have basically found no way to make it work:

```js
declare type RouteResolver$Route = {
  id: string,
  path: string,
  secure?: boolean,
  exact?: boolean,
  component?: RouteResolver$ResolveToComponent,
  routes?: RouteResolver$ResolveToRootRoutes
}

declare type RouteResolver$ResolveToComponent =
  | React.Component<*, *>
  | Promise<React.Component<*, *>>
  | () => React.Component<*, *>
  | () => Promise<React.Component<*, *>>
  | () => Promise<{ default: React.Component<*, *> }>

declare type RouteResolver$RoutesArray = Array<RouteResolver$Route>


declare type RouteResolver$ResolveToRoutes =
  | RouteResolver$RoutesArray
  | Promise<RouteResolver$RoutesArray>
  | Promise<{ default: RouteResolver$RoutesArray }>
  | () => RouteResolver$RoutesArray
  | () => Promise<RouteResolver$RoutesArray>
  | () => Promise<{ default: RouteResolver$RoutesArray }>

declare type RouteResolver$RootRoute = {
  SecurityProvider?: RouteResolver$ResolveToComponent,
  routes: RouteResolver$ResolveToRoutes
}

declare type RouteResolver$ResolveToRootRoutes =
  | RouteResolver$RootRoute
  | Promise<RouteResolver$RootRoute>
  | Promise<{ default: RouteResolver$RootRoute }>
  | () => RouteResolver$RootRoute
  | () => Promise<RouteResolver$RootRoute>
  | () => Promise<{ default: RouteResolver$RootRoute }>

```

Where essentially attempting to provide annotations for my React Route root resolver package.  Letting a user nest routes and embed various parts of the app based upon the path easily.

Here is an example of the routes object:

```js
/* @flow */

const RootRoutes: RouteResolver$RootRoute = {
  // The main routes expects an object rather than an array.  We can use this
  // to configure the routes and how they will behave.
  // When we are attempting to render a secured route the onSecureRequest will
  // be called.  This should provide a promise that resolves to a SecurityProvider
  // component which will wrap any secure routes.
  //
  // As we nest routes, new onSecureRequest properties will be used if provided, otherwise
  // any secure routes will use the first onSecureRequest
  SecurityProvider: () => import(/* webpackChunkName: "security" */ './screens/Login/Login'),
  routes: [
    {
      // The unique ID we want to assign to the route,
      // this will be used for values such as the "key"
      // property and similar.
      id: 'home',
      // What path pattern do we want to match this route for?
      // https://reacttraining.com/react-router/web/api/Route/path-string
      // https://www.npmjs.com/package/path-to-regexp
      path: '/',
      // Does the user have to be logged in to view this route?
      secure: false,
      // Does the url pattern need to match exactly?
      exact: true,
      // What static props do we want to provide the matching route ?
      // Provide a function that will return a promise that resolves
      // with the route and its dependencies.  This provides the layer
      // required to handle asynchronous / code split routes.
      //
      // If component is provided, it will be rendered when we have an exact
      // match (/dashboard).
      //
      // If it has child routes then they will be rendered as the components
      // children via an async component.
      // https://github.com/ctrlplusb/react-async-component
      component: () => import(/* webpackChunkName: "home" */ './screens/Home/Home'),
    },
    {
      id: 'dashboard',
      path: '/dashboard',
      secure: true,
      exact: false,
      component: () => import('./screens/Dashboard/Dashboard'),
      // If it has child routes then they will be rendered as the components
      // children via an async component.
      routes: () =>
        import('./screens/Dashboard/routes'),
    },
  ],
};

export default RootRoutes;

```

In that example one issue I have is that the `routes` does not work 

Guess this may be related to the other issue i reported come to think of it... if unions do not even work then i cant believe there aren't hundreds of reports for it? considering the example inthe link is simply `string | number`

https://github.com/facebook/flow/issues/4712

Specifically the signature I want is that "routes" can be provided as:

1. A function which resolves to an array of "routes"
2. An array of "routes"
3. A promise which will resolve to "routes"
4. A promise which resolves to a dynamic import result `{ default: $routesArray }`
4. A function which resolves to a promise which resolves to "routes"
5. A function which resolves to a promise which resolves to a dynamic import result 

And the same for providing asynchronously loaded components and widgets.

**Comment by bradennapier** [comment]
Ran into the issue again, here I very well could be doing something wrong... but essentially i am expecting a function is given that may have two or three arguments and based on that, will have specific props.  

I believe Flow simply is not paying attention to `Function.length` in this case?  It would appear it is not possible due to this bug with unions that is going on?  Even if I type it all I get errors.

Additionally, in the example, I have a typed example of the object but it throws an error anyway ($Selected)

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswAXATwAcSBhOAO3t1IHUBLDAcy1IBIBlLDGZYMYALxgA3qjBgAzkOZxC8gFzTZcsAG1FwnKRUBJACIb5pQm3qcAuhoBiAV3qG2DLQF8ANFvzuDOqa2roBpB70ZhZWNvZOroH03qheANzo2HhEJBTUYHSMzOxcPLyFTIaFUGycvOykABYACoRwlPISYAAUWpb4pFgaAPIARgBWzH5y+iIYGhXFHNx8ggaDGKgAlBIAfNK6OAyVG63tMda2DmD49ORg6Zm4BMRkVLTHS6V8i1UMNXUGo04M5SGcOl1ejNSAMhmAxpNDNMwJQ2h0NFJfH0lIZRAtPoYSisBDiNts9gcdEciriMOCLnFrrd7o9MM8cm98r9WMsytzqrUJFoAD4FAk877lcUCwFsJrg+QisU0iXE-n-Wr1OXA0EKp7ZV55D4qol8jWcLoyOTUk4AfnxJt5P2l5r8rKgiQiDDANuY3Sg9ASbi99B8NyS8nt8ImzB2Mi86A9wciZCwlm61IBDpOpud9ABca0bCgPQAhJnagA6X2GQuhYikZyEehgejOGAwFJyBtNlvdWa07NfYlrOY7cT7K3aYtliucaviuvaACQPebWjkCdCM4z5oXKsrwlsTQk4kkACYl-WeL2feKoaFtP2YYMRjHaxTd-mqzXSGAAGT-ne37zr+z6wmGA4bFsOzCqKmLIo+0hYkhWwZKEXhgEIihgDuc77ich5YMejSnpIADMV7aGuLZgRuj7ga+0aIqQYaou0wSYuOuz0UhX4AgRzAAUB+Fgf0gxsWi8iQaSogwWAcHIYhj4IbxYBofRW7aCky6pEAA

**Comment by goodmind** [comment]
This should use braces for functions
```js
type Example = 
  | (() => Promise<string>)
  | string
```
