### ISSUE TITLE
[React] Optional field with default value by defaultProps

### ISSUE THREAD

**Issue by ovr** [facebook/flow#4871]
Hey!

What i am going to do:

- Define optional property with default value by `static defaultProps`

```javascript
/* @flow */

import React, { PureComponent } from 'react';

type Props = {
    accept?: Array<string>
};

export default class DropZone extends PureComponent<Props, void> {
    static defaultProps = {
        accept: [
            'image/png',
            'image/jpeg',
        ]
    };

    onDrop = (event: SyntheticDragEvent<any>) => {
      	this.props.accept.indexOf('image/png');
    }
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8wAFAV3zIGE5c4A7Mn2IBfMFHw8wAcg7VCUgNzpCATxxkWEnAGcwAXkaowxsNSpkchAPwAuMAEF8+CioA82wvgx8A5gD5UYSVUMgAPPCIwABMyKApWGGIqGAptXQARLQAtfg0wwkEo3TYObl4BIVdmLW16ADc4DCi-QxMwDwpCDCpo2PjE6rgdfVa2kzMLQjsAbSMx+alsCh8yYBxfKVo5+bbFrGXVgCt1H03tsYBdc6D0Nv5MoZGACjI6wSmwAGUVIQALMi6VEyywAom9KhQ+Co-ABKfQtBjnYwASEIvww2gAdDgapiJpZMd4YqEAPJQJ57A5rDYwpRtYSBIA

![image](https://user-images.githubusercontent.com/572096/30374086-a0724ae4-98be-11e7-9e91-953c1659a512.png)

Unexpected result:

```
18:       	this.props.accept.indexOf('image/png');
           ^ call of method `indexOf`. Method cannot be called on possibly undefined value
18:       	this.props.accept.indexOf('image/png');
           ^ undefined
```

Thank

**Comment by apsavin** [comment]
@ovr you don't need to mark `accept` as optional in `Props`. `flow` will understand that it's optional from `defaultProps`.

But there's another issue: #4848

**Comment by silvenon** [comment]
I'm confused by the language used here and in the docs when it comes to default props:

> **Note**: You don’t need to make `foo` nullable in your `Props` type. Flow will make sure that `foo` is optional if you have a default prop for `foo`.

"You don't need to" makes it sound like it's ok either way, but the error above tells me that it isn't. I'm currently modifying some ESLint rules related to default props, should I warn against adding default props that are marked as optional in `Props`?

**Comment by apsavin** [comment]
I think you can read "You don't need to" as "You must not".

**Comment by apsavin** [comment]
@ovr Could you please close the issue?

**Comment by ovr** [comment]
Closed due @apsavin answer:

> @ovr you don't need to mark accept as optional in Props. flow will understand that it's optional from defaultProps.

Thank you @apsavin
