### ISSUE TITLE
$ExpectError ignored?

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#4877]
[repro](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcqqUArgHbV0cPmABicOAAoA3mEoALdDAAmLEQF8AXGGkKlq0n20BnAnnR8A5uoCUO1GDAsCPPCL0q1ndV2DAwACQAogAe2KTUQXh0eKgAPOJwAHzSAIzqccCJSUA)

Looks like `$ExpectError` stopped working after 0.52.0?

**Comment by lll000111** [comment]
The suppress comment is whatever you put into your .flowconfig

https://flow.org/en/docs/config/options/#toc-suppress-comment-regex

**Comment by FezVrasta** [comment]
Thanks!
