### ISSUE TITLE
Flow types become nullable when using spread syntax

### ISSUE THREAD

**Issue by johnryan** [facebook/flow#4878]
I've found a case when using the spread syntax to merge types that the resulting type ends up having nullable fields.

for example:
```
type A = {
  foo: string
}

type B = {
  ...A,
  bar: string
}

```

results in the B looking like this:

```
{
foo?: string,
bar: string
}
```

I created a contrived [example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdWAHpLHDAJ5hZwAiEAczgBeOAG86cOADpZAQQB2oZABsANJLgEArlADCEFdABccVDCjAFAjQF96jFtHiducAHIQFAZTCVkACb8QqISUgrIIFim5pbWGlI6+oYmZhZWNnT2DMysLlw8isoqIuKaEVEx6dZZDq48AArEYOihmtwwpgD8wXBZDPUeXr7+AU0QLaVhcB3dnj5+OEGCfbYMdDoK+MBeHpFYBuAAFH4TqKZiAG6qVXECtgCU05QwugpwADwBwJcAfGKnFrSa4qWwfAD03z+-Q22i2MB27waWBghzAcBOzXOcHGLQeZSkuC85nEMxRcFspUBqHoAEgXm9PlD-h04AAyNmfdz7NFwEHCAEo6QVLC2cG-MGQn6-GF0cHgrTQMwkHj+VC7MgishwABGWCJUXQyHeEwRXlUfNU2h4AHcABZYd5gNCoLABOBWPnAZBmRaBMwcBQwZBMOUKgCMpht0AA1ugdRw4NAAOQZMkwYX7OA24AwO1wZPJ2HwxFwADqsYyyNRJDA4Yx1NMuNQ+OmRIUJLE6YpVKxdIZUHeX2lgvgHK5PNrlpUAo6maicAAPouC8mxRKIcyYfK4JHs7H44ntKg09Ts7m7RBtPBUH73ahA8HQ5ttrsK1AY1WUWiAEwNrGmPMIxLM2raaO2nbdpSojUv2KKMsOfyjuynIfNyUS8vyo7zqK4qSluax0B81a8h0ArTCKpjJgAQhAOrJgkWi6AYRhQFROrEDaChFhS650EAA)

**Comment by choonkending** [comment]
I think it could be related to https://github.com/facebook/flow/issues/1326#issuecomment-298249845

I think the workaround now is to spread an exact object

```js
type B = {
    ...$Exact<A>,
    bar: string
};
```

**Comment by johnryan** [comment]
@choonkending thanks for the tip...However that raises a different issue [here](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdWAHpLHDAJ5hZwAiEAczgBeOAEEAdqGQAbOADI4Abzpw4AOk0ASAKJM8MADyTpMgHwAaVXAIBXKAGEIM6AC44qGFGASBVgL70jCzQ8Jzc4lIgsiLK1hLIIFjunt6+dIEM4TwACsRg6KIqatww7gD8-EIZDHYS+MAQEnA5WDBO4HAAFGD5qO55EAUAlHFquE2eynClcP6xvUOo9ACQlDD2zYYAJsAAbmZKs-KKpeoJSf6GAPS7BzV0dQ1NcADq0ADWPgKt7SRg3UWBQGfVGxTgEwkUyUMzacwWfVW602cB2+0OPThAEJRBJbDIZKMTrCYOdElgrrd0Q9DL8OgDSsIlOCLsk4AByABCEAARuyrGo7I5nG4OTziAB3CTs1T+fzXMx0IA)

Any suggestions?

**Comment by choonkending** [comment]
I've been struggling with intersections myself. And I think the workaround is to spread your generic type without intersections.

Would the following work for you? I noticed you were creating an intersection between Animal and Animal.
```js
export type Dog = {
  ...$Exact<Animal>,
  furColor: string,
};
```

**Comment by johnryan** [comment]
@choonkending that workaround works, thanks!
