### ISSUE TITLE
Flow does not allow Map.has() to refine type 

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4880]
```js
type MapValue = {|
                  	one: string,
                 	two: number
              	|}

const MyMap: Map<string, MapValue> = new Map()

function test(id: string): number | MapValue {
  if (MyMap.has(id)) {
  	return MyMap.get(id)
  }
  return 1
}
```

```
12:   	return MyMap.get(id)              ^ undefined. This type is incompatible with the expected return type of
10: function test(id: string): number | MapValue {
                               ^ union: number | MapValue
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhjgGrEwCuBAvGAN4A+qYb7Hn7AkHAHZ4AXGADOGAE4BLPgHMANKy5KeGBHGF8qAWwBGecYuUduTAL7oAxvzFEsJHMPsAeMVNlyipCtTwA+MPQCSPYAFACU6FBUfBYYkvxgGHhiIZIAJsKu0jJhGtp64mBMnuSUNIyKklBgIYR2pAB0ABbEIqlpYWEVbNzieBhU4ny29g0y-e0RbOZsfQNDYACMqOZAA

**Comment by lll000111** [comment]
I changed my `Map` object access coding style to ignore `has` and always use `get` right away, then check what I got.

**Comment by johngeorgewright** [comment]
I have a [similar problem](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCcAHmALxgDOGATgJYB2A5prgQCoAWTzF1dXm3xhuvKvwDKeDAB4xLAHzoAxjACGVCQEEMGeirABvVGDAAjUnioAuMAFl1OWcRIAaUTxZVlZs6bBaPABbOAA3PAU+AApLEjtXDwwvZjsogEo7SzgYPHVGYwCzIIwAV1oC5PoqADo46xquTVjSdLAAMnawKtr62uYZFpJ0moATPFyMPGiqlnSAgF9UJaA).

```typescript
type Box = string
type Thing = string
type Things = Set<Thing>

class Attic {
  boxes: Map<Box, Things>
    
  removeThing (box: Box, thing: Thing): boolean {
    return this.boxes.has(box) && this.boxes.get(box).delete(thing)
  }
}
```

```
11:     return this.boxes.has(box) && this.boxes.get(box).delete(thing)
                                                          ^ Cannot call `this.boxes.get(...).delete` because property `delete` is missing in undefined [1].
References:
[LIB] static/v0.67.1/flowlib/core.js:561:     get(key: K): V | void;
                                                               ^ [1]
```

I had to [rewrite it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCcAHmALxgDOGATgJYB2A5prgQCoAWTzF1dXm3xhuvKvwDKeDAB4xLAHzoAxjACGVCQEEMGeirABvVGDAAjUnioAuMAFl1OWcRIAaUTxZVlZs6bBaPABbOAA3PAU+AApLEjtXDwwvZjsogEo7SzgYPHVGYwCzFThGGjBk8X5KqgA6OOta5hlY0nSiwJkAV1oC7Hw4KAqUiQBCckoAci7GABM8KCY8WcmwADI14fFa+dyMPGjKlnazAF9Uc6A) as @lll000111 suggests:

```typescript
type Box = string
type Thing = string
type Things = Set<Thing>

class Attic {
  boxes: Map<Box, Things>
    
  removeThing (box: Box, thing: Thing): boolean {
    const things = this.boxes.get(box)
    return typeof things !== 'undefined' && things.delete(thing)
  }
}
```

So, you can get around it, but it's less than ideal.

**Comment by SamChou19815** [comment]
In general, we don't do type-based refinements.
