### ISSUE TITLE
React Node behaves unexpectedly

### ISSUE THREAD

**Issue by danielbartsch** [facebook/flow#4881]
Node should be allowed to be anything that can be rendered by React.

However, flow doesn't correctly work with it.

See (NodeX is the implementation of Node in the react code): https://flow.org/try/#0C4TwDgpgBAcg9gEwgDSgXgFBSgHygNzgEsEtcoA7AVwBsay8AjOOGiAQwocqoFtGIAJ24BnYIKIUA5twCibXhArBuASWBD2jNgB54SZAD4A3BgwBjOBTFQAZlQrmAjOigAKAJQAuWIhTpDKCcAJgBmCysbe0dg108ffWg0QJDQoA

**Comment by vkurchatkin** [comment]
You need to import the type like this:

```js
import { type Node } from 'react';
```

**Comment by danielbartsch** [comment]
Is there a list somewhere of types that are automatically 'imported' and those you have to import?

Such as `React$Element` in older versions of flow.
