### ISSUE TITLE
Promise type

### ISSUE THREAD

**Issue by LeonardoGentile** [facebook/flow#4882]
Hello,
forgive my ignorance, this a very simple (and probably silly) question: how to annotate a function returning a Promise?
I've read most of the official documentation and I haven't found a specific page dedicated to Promises. 
I've seen a couple of threads here on github but things are not clear to me. 

Also, when we specify a Promises return type how to specify the resolve/reject cases?

Thanks

**Comment by lll000111** [comment]
```js
function demo(): Promise<string> {
    return 'I love cats!';
}
```

**Comment by LeonardoGentile** [comment]
Thanks @lll000111 for the example!
Any link to the official documentation?

**Comment by lll000111** [comment]
You are looking at it (you opened in issue in the repo that holds the source).

https://github.com/facebook/flow/blob/master/lib/core.js#L594

**Comment by LeonardoGentile** [comment]
Yes, you are right, I was talking about https://flow.org/en/docs/
Probably it is still not there?

**Comment by lll000111** [comment]
Why don't you go ahead and update it? Contributors welcome :-)

**Comment by LeonardoGentile** [comment]
Yes I will, but having a very limited experience with Flow I will wait a bit before writing stupid things :]

**Comment by Noitidart** [comment]
Hey folks, this topic was extremely helpful to me. So I added a doc page per request - https://github.com/facebook/flow/pull/4927 - did I do that right?

**Comment by VladimirPittner** [comment]
Is there official documentation already? This is over 4months old issue but I still can not find the promises in docs :(.

**Comment by TrySound** [comment]
@VladimirPittner You won't find a lot of things which is hard to duplicate in docs. Just look at lib defs 
https://github.com/facebook/flow/blob/master/lib/core.js#L591

**Comment by VladimirPittner** [comment]
@TrySound sorry I do not understand what do you mean by 'hard to duplicate in docs'. If I would want to search for things in actual code, I would not look for documentation, but thanks.
PS: Why don't actually drop all docs and just read the code, its probably self explanatory ;).

**Comment by nickshanks** [comment]
> > how to specify the resolve/reject cases?
> 
> Reject: You don't - that's not a return type, that's an exception.

How should you specify what type of argument will be passed to .reject() then?

**Comment by lll000111** [comment]
By convention `reject` should _always_ get an `Error`. This is reflected in the standard definitions:

https://github.com/facebook/flow/blob/master/lib/core.js#L615

**Comment by LeonardoGentile** [comment]
I've just realized that #4927 was never merged and Promises are still not very well documented in the docs page. Is there any reason for that?

**Comment by NetOperatorWibby** [comment]
Sure glad I found this issue, I wasted two hours of my day trying different things.

**Comment by chmiiller** [comment]
Suffering from this in 2021

**Comment by LeonardoGentile** [comment]
@chmiiller considering the lack of interaction here it seems to me that not even at facebook they are using flow.
From a dev point of view I gave up on this

**Comment by NetOperatorWibby** [comment]
I've since moved onto TypeScript, it makes more sense.
