### ISSUE TITLE
Too few type arguments

### ISSUE THREAD

**Issue by erica93k** [facebook/flow#4883]
I have a simple component like this:

```
import React from 'react';

type Props = {
    name: string
};

export default class MyComponent extends React.Component<Props> {
    render() {
        return (<p>{this.props.name}</p>);
   }
}
```

I get the following error:

> React.Component (type application of property `Component`) Too few type arguments. Expected at least 3 DefaultProps, Props, State (See type parameters of definition here).

------------------

`"flow-bin": "^0.54.0"`

**Comment by AugustinLF** [comment]
That's weird, if you look at [this example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQMAnmFnAArFjoC8cA3nThC4AO2QgsALjioYUYCIDmdAL706WAB6RYcACZYCyAK4AbeLlNp0AWUYBhEpBFYR8LTFd702PDAB0juAQLm4APBwQXAB8-ILClCIGUAAUAJRxwllwlDDGUCJwKWFg0XwwABbAqP5gnDViEiphAPSlafTCKqpAA), it does typecheck. Are you sure that you don't also have a global version of flow that it not up to date?

**Comment by erica93k** [comment]
@AugustinLF It turns out I had `flow-bin@0.48.0` installed globally. Thank you!
