### ISSUE TITLE
React.Element polymorphic type does not accept a union of component types

### ISSUE THREAD

**Issue by bibekg** [facebook/flow#4890]
The [Flow+React docs](https://flow.org/en/docs/react/types/#toc-react-element) say that you can use `React.Element` with an explicit type defined, e.g. `React.Element<typeo Foo>`. It seems like it's not possible to use a union type of component types though.

### Minimal repro
```js
import * as React from 'react';

type FooPropsType = {
  a: string 
};

type BarPropsType = {
  z: number
};

type ComboType = typeof Foo | typeof Bar;

const Foo = (props: FooPropsType) => <div>{props.a}</div>;
const Bar = (props: BarPropsType) => <p>{props.z}</p>;

function SomeComponent(): React.Element<ComboType> {
  return Math.random() ? <Foo a='hello world'/> : <Bar z={1} />;
}
```

### Resulting errors
```
[LIB] static/v0.54.1/flowlib/react.js:161:   +props: React$ElementProps<ElementType>,
                                                     ^ property `a`. Property not found in
14: const Bar = (props: BarPropsType) => <p>{props.z}</p>;
                        ^ object type
14: const Bar = (props: BarPropsType) => <p>{props.z}</p>;
                        ^ property `z`. Property not found in
13: const Foo = (props: FooPropsType) => <div>{props.a}</div>;
                        ^ object type
```

[flow.org/try setup is here if you want to play around with it](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAGIQQAKxYqAFRZsAvHADedAJDIAXHFQwowAHYBzOHQC+9RsLgAhZFF4R+Q1nDGSpAL3kqAriABGWKNt3NLAVRXAIFWw8GABRABssECwVeDFvLAgCDi44AB84BKTDY11cQMUUiCs4AAowPlR5Th5KiywASisAPjgAHgATYAA3ZvEKs1QAOmQtNoB6Lt76fJVCoygS8sr5BdNzYSaRVrawPoH+Idsx8b3dAkcVfACVOABlEiwAYRJIFRiYUob5YPwhiKiHzaWWSNVaNkoMEcUFuAFlkDAABZDKDIFQdEhfOAAfnaNRQIjIiKw4XCxQA7tBwh0yONWvI2gs4LYROIAIxaOB0+haIA)

Am I doing something wrong or it has this just not been implemented yet?

**Comment by SamChou19815** [comment]
this now works
