### ISSUE TITLE
Spurious error with Array.includes()

### ISSUE THREAD

**Issue by whmountains** [facebook/flow#4891]
Flow is freaking out because the type `string` has values which are not a valid `RoomType`.  But that's the whole point of `Array.includes()`.  I wouldn't bother to check if I knew the answer would always be `true`.

```js
type RoomType = 'Blue' | 'Red' | 'Gray'
const rooms: Array<RoomType> = ['Blue', 'Red', 'Gray']
const room = Math.random() ? 'Blue' : 'foo'

// Error!
rooms.includes(room)
```

**Comment by asolove** [comment]
You can cast room to ‘any’ if you want to do this. Flow is telling you that there’s no reason to search for another type in an array of one type. This is generally a useful message, but if you explicitly want to check for something arbitrary, you’ll need to cast.

**Comment by whmountains** [comment]
I understand that flow would be right to warn me about checking for a completely unrelated type (i.e. a number in an array of strings.), but I don't see why that should apply to this case where `room` is clearly a superset of RoomType.

In other words, shouldn't this be a case of "Sorry, Flow isn't smart enough yet." rather than "Flow should never have this behavior!"?

Thanks

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
