### ISSUE TITLE
Flow is essentially completely broken....

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4895]
So been having tons of issues and thought it was me or my setup ... then I just tried in flow/try and its the same.  On top of unions not working pretty much at all anymore (ive posted multiple examples) now even the basic typing is not working...

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAdhngE7ECGMACuXPuRgJZ4DOYAvGAN4A+qMGBzk8ANxZwAruxhYAwgAs8AYwDWeACYAuMACM4cGHirEANELBVVrcVTK6DRk2cvD2GKswAaAfj1iaQBbfQp3MGC4cW09Q2NTC1R+AF8AbnQoaWJbKWIwVSNyLQAKAEo9XjAAD0CQsPJzMCw60IowFL5UAEgxDGlKPhq9AFYmrDBRjtQU9FUYKnZOABUODC6wFlIKahg9EjJKGnpGClYObg3hETFJGTlFFQ1YsCgadjwI4Rs7Bxe3mAfL5gTzeDA+PQABmBURiTgBQKs6XQ1zInnKV2uLCgYBKGCULHYADotoddkTQb4wABCLg8bJaPBQLbaMqY65gEzrVQDMSkHyXQpwYrlInVKwc4TY3E88h88FgAC0YAAjCMwAA+MD4wkk7ZHGAUry+Nm8CWS2YWiWzFJAA

```js
/* @flow */

type InternalProperties = {|
  previouslyChecked: boolean,
  activated: boolean,
  startX?: number,
  moved: boolean,
|};

function coord(): { x: number, y: number } {
	return { x: 5, y : 5 }
}

class Test {
 internal: InternalProperties = {
    previouslyChecked: false,
    activated: false,
    startX: 0,
    moved: false,
  };

   test() {
     if (this.internal.startX !== undefined) {
       let currentX = coord().x
        if (currentX - 15 > this.internal.startX) {
        }
     }
   }
}
```

```
if (currentX - 15 > this.internal.startX) {
                                ^ undefined. This type cannot be compared to
25:         if (currentX - 15 > this.internal.startX) {
                ^ number
```

**Comment by mroch** [comment]
this is described in the "Refinement Invalidations" section here: https://flow.org/en/docs/lang/refinements/

the `coord()` call on line 24 invalidates the check on the line above it because flow isn't sensitive enough to track what side-effects `coord` might have. this should work:

```
const startX = this.internal.startX;
if (startX !== undefined) {
  let currentX = coord().x
  if (currentX - 15 > startX) {
  }
}
```

**Comment by bradennapier** [comment]
yep realized that a few minutes later.  thanks @mroch !
