### ISSUE TITLE
process.stdin.isTTY triggers Property not found in stream$Readable

### ISSUE THREAD

**Issue by mitermayer** [facebook/flow#4897]
Add the following snippet  to the playground (https://flow.org/try/#0A4Jw9gxgpgzjB0MAuATAlgO3mmAVXAmkA)

```javascript
process.stdin.isTTY
```

triggers this error:

```
1: process.stdin.isTTY                 ^ property `isTTY`. Property not found in
1: process.stdin.isTTY
   ^ stream$Readable
```

This is pretty weird since it `process.stdin` is meant to be an union type of  (https://github.com/facebook/flow/blob/master/lib/node.js#L1959)

```javascript
  stdin : stream$Readable | tty$ReadStream;
```

And class `tty$ReadStream` implements `isTTY` (https://github.com/facebook/flow/blob/master/lib/node.js#L1500)

```javascript
declare class tty$ReadStream extends net$Socket {
  isRaw : boolean;
  setRawMode(mode : boolean) : void;
  isTTY : true
}
```

**Comment by jcready** [comment]
Duplicate #1825, #4487

**Comment by asolove** [comment]
Marked the older issue as accepting prs, and I’m happy to help if anyone wants to do it. Will track progress on that other one.
