### ISSUE TITLE
The combination of generic types and comment types does not work

### ISSUE THREAD

**Issue by kjirou** [facebook/flow#4898]
It is not working.
```
function identity/*:<T>*/(value/*: T*/)/*: T*/ {
  return value;
}
```

Interpreted like this.
```
 10:   function identity/*:<T>*/(value/*: T*/)/*: T*/ {
                        ^^^ Unexpected token /*:
```

Try flow:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgOIFMB2uATgJYDGYALgJ4AOuAzmCUwnEQNYn4DmqUAV3xlKJOPmYATAqJoAeACoA+ABQA3AIYwBuAFxgFASn0KwAb1RgwRXJQFEJm7bgDcqAL6oy4hpTD4BAFswAF4pGRIaFQBGQzcAwIA6SjgAMRIAD1xJFTj0DCwAYThAwJkqOkZmVnYuXn4hETEJDUkcjVB9BIAjYhQAGjBuzv8g3qIUQxGevqwLKxs7BzANMABqIbdPb3xfMAYg0JW2lQ1B7ryDpJT0rJy89EwDAAtcMG9A7u4NUXEwOCgYB4BGI5Aq9CYGnwkneJTK+D8NAhYEkcCq+DgfjYnAawl+EhI0gRkWoACZOoolCh1FodCMFJN6ShzJZrLZ7I5aa4PEA

Thanks.

**Comment by tempname11** [comment]
This works:

```js
function identity2/*::<T>*/(value/*: T*/)/*: T*/ {
  return value;
}
```
The single-colon `/*:` syntax preserves the colon, which is not what you need. Use `/*::` instead to only treat the comment contents as part of the code.

**Comment by kjirou** [comment]
Thank you very much!
