### ISSUE TITLE
When annotating with "%checks" I don't get an expected error from a type checking function

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4900]
I only get the expected error when I remove `%checks`.

```js
// @flow
'use strict';

type ReferenceObj = {
    type: 'Reference'
};

// REMOVE "%checks" AND YOU GET THE EXPECTED ERROR
function isReferenceObject (thing: mixed): boolean %checks {
    return typeof thing === 'object' && thing !== null && thing.type === 'Reference';
}

function demo (o: ReferenceObj): void {
    console.log(o.type);
}

const o = {type: 'Foo'};

if (isReferenceObject(o)) {
    demo(o);
}
```

[**Flow Try Link**](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKK4CeADtgEqaSb6YB2xmA8gEYArUAF5QAb0SgpoWgwBcoZM1bsumZIgC+lRCFCMAogFkeANQOgARAFJiAC0zEA1ukugAggDkAIqACaPACqoADiBgAqoOEAEhYGABoACgYAwuEGvgaMjDyMiJCoXLiEsByghOjKbJzc-AKOuKAAFLh2hBwA5goAtoQAHpgAJgCUCnywsNCYAIZltg7O6OKS0uy4qPhlspiwkDJtnSLCosiwgg3IoABkV-vtHaAAhMegHKjQ0Ne3rfcAdNtHE5VVTcChaKgFIolMqDTDdWDNWAKYE1XiCUagABusEIg2W0lAxFK6EmmF+cA6TVg-3omGGlE0VCJHDwoARojE2wUyAAYhNkNoqIQ9k0Kii1HUGlThsN8dJYfDpQzEEA)

**Comment by asolove** [comment]
Why do you expect an error? Looks right to me.

**Comment by lll000111** [comment]
Because the `demo` function expects a `ReferenceObj`?

**Comment by jcready** [comment]
Your `demo` function never gets called because your foo input returns false for your `ifReferencedObject` function. Without the `%checks` annotation flow doesn't know that the function is actually going to only allow the correct input through, hence the error.
