### ISSUE TITLE
Exact/superset => inexact/subset compatibility broken when wrapped in Array

### ISSUE THREAD

**Issue by scottnonnenberg** [facebook/flow#4901]
Given two types, like this:

```
type SingleFieldType = {
  single: number,
};

type FullObjectType = {|
  single: number,
  second: string,
  third: string,
|};
```

A `FullObjectType` can be supplied wherever a `SingleFieldType` is accepted, as you might expect. They both share that `single` field of type `number`. However, if you wrap these two types in an `Array` in your function parameter types, this compatibility goes away. Take a look at these complete examples on Try Flow:

- [Works](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZQJYB2A5tFgGL5bQAmAKpjgLygDeiooAzkaVgFyhCAVwC2AIywAnADSIAvgG5k6bKHLDo0APLiAVlgDGKBmpasAPh268ygkROlzOXI7EI1BXFFN7PQKAAW+FKe3D5+iBZKyIbu3qAAHqDm1jwkdqAAjHIxiHGECWgpbGm2AqAATP6uBWEA5LXuNPX+QSEN7aGtCsqIkMKExvjuoBi+hCgEGVgAFOl8gtN8lNT0jACUpZwFXLBkAHRwxPPlBwtkG8ryyANDKCOEYxMoGlq6BsanM4JvOvpGEybbbPIhTcrfPhXBTIcZg5ZkWaJaFwyYIuZoaGIECgyZ-D6ApEol74gFfTHKIA)
- [Doesn't work](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKAlgHYDmMeAYsXjACYAquBAvGAN6phgDOZSngBcYUgFcAtgCM8AJwA0qAL4BudNnxhq4mDADy0gFZ4AxhhZaOnAD49+gqqIkz5S3nzNxSDUXwxygu5gGAAWxHK+-AFBqDZq6Kbe-mAAHmAcANrcHo4iYACMSsoAuuqoSaQpWBlg2fYCFE5gAEzBnpVRAOQd3gxdwWER3UORAypl6FDipObE3mA4gaQYJE14ABSNQqIAgnJyAIZYADxrQrT0zKwAfACUXA15AHRQcHIAooemoRvEGHhJBkbmBKnw4FRnvByH8AZJntsqHc7uplFMZnMFksyBgdHpDCZzFs8nsDscTniDMYzBZbg8cotlqs8sT1iiVOhsStzlQNql2VzmesNlh2ahgMBGTjKQSaXyBUyZdSiaL1EA)

All the signatures are the same between these two examples, except for wrapping Arrays.

Is this expected? Is there a reason for this? Seems more like a bug than an intended behavior to me.

**Comment by vkurchatkin** [comment]
This is expected behaviour. Arrays if Flow are invariant by default. If you need covariant arrays, you should annotate them as `$ReadOnlyArray` instead of `Array`.
