### ISSUE TITLE
Higher Order Components cannot be exported

### ISSUE THREAD

**Issue by miracle2k** [facebook/flow#4905]
See: https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCocBDAZxwCUBTQgY13A2mRwHIMrbmBueecAVwB2tRNAE5EAgFYVaABQaoAPPOipiALhwBvAL4A+ABTwcOAMKN0AigKybKNLADpzaUdawAVAJ6oKirTjg0NCaAnzIAEYUGDg6OABkOCpqegA08ACUduxOLpbu3r7KCsR62sY4bFh8GGL8QlgiYgDqGISovhh5bjYGqCWaycQZ5SYmVTViit1WNtqOC-2qxHFB0AC8WgAsAExxwHrcJjrcOjzUkCSkALJeM+44FAAeWNYAJqT2tM4WPVj+FUIoXCUQw6RMEWBkWi4MCwShoPS+m0Z3g1FExFwtwAogIABaEIQUN73ObrcRSGRYZIGW6krAZbjwEA4ZoUHBvUTMXBWYk4LDQHCoK4UnAAAzWYseADdrPy8dA+ABzPHium-WZYKVsACOfEQbFIiCcvEEwlEcMFBhGWgqE1qOEUOPxhOoxPpRE2AEY4hFNnscAdTjxnuhsNpnQSiSSNe4TvAgA

Note that this is verbatim the sample from the docs. If you remove the last line, the export line, it works.

**Comment by jcready** [comment]
It is strange that you cannot export that w/o an annotation, but this should do the trick:

```js
export const MyEnhancedComponent: React.ComponentType<*> = injectProp(MyComponent);
```

**Comment by miracle2k** [comment]
So I tried that, and I was excited at first, but this does seem to lose the component enhancement.

Once I import this in a separate file:

```
import {MyEnhancedComponent} from './injectProp';

<MyEnhancedComponent a={1} b={2} 
```

This will cause an error ``property `foo`. Property not found in.``.

Now look at this:

```
// injectProp.js
//@flow
import * as React from 'react';

export function injectProp<Props: {}>(
  Component: React.ComponentType<{ foo: number } & Props>,
): React.ComponentType<Props> {
  return function WrapperComponent(props: Props) {
    return <Component {...props} foo={42} />;
  };
}
```

```
// component.js
//@flow
import {injectProp} from './typed-connect';
import * as React from 'react';

class MyComponent extends React.Component<{
  a: number,
  b: number,
  foo: number,
}> {}

export const MyEnhancedComponent = injectProp(MyComponent);


// THIS PASSES AS EXPECTED, foo is not required
console.log(<MyEnhancedComponent a={1} b={1} />);

// THIS FAILS AS EXPECTED, a is missing
console.log(<MyEnhancedComponent b={1} />);
```

```
// app.js
//@flow
import {MyEnhancedComponent} from './test';

// THIS PASSES!
<MyEnhancedComponent
/>

```

I tried really hard to implement a kind of redux ``@connect()``  that correctly removes ``dispatch`` and injected state props. But I can't get it to work.

flow-typed has redux-react typings that don't seem to work for me either, likely because the behaviour I am seeing as the same one as ``app.js``.

**Comment by apsavin** [comment]
I think it's related to #4709

**Comment by pugnascotia** [comment]
I have observed this too. I have to explicitly type my HOCs as follows, and using a wildcard for inference doesn't work

```javascript
export const MyEnhancedComponent: React.ComponentType<Props> = injectProp(MyComponent);
```

In my specific case, my HOC does not change the props but instead adds behaviour, calling a supplied callback function on a schedule. The function is passed the wrapped component's props, and I use Flow to ensure that only value props are be used in the function. If there is a type problem in the callback, instead of telling me the error, Flow says e.g.:

```
Cannot call schedule with FooComponents bound to WrappedComponent because
a callable signature is missing in statics of FooComponents [1] but exists in
React.StatelessFunctionalComponent [2].
```

This only happens if the HOC is exported directly. If I assign the HOC to a `const` and add a type annotation, I get the correct error from Flow.

**Comment by SamChou19815** [comment]
Types first will always require annotation
