### ISSUE TITLE
WebStorm console files path links

### ISSUE THREAD

**Issue by davydof** [facebook/flow#4906]
In flow-bin 0.50.0 the files links can be clicked.
![image](https://user-images.githubusercontent.com/10529679/30545819-693564e8-9c93-11e7-926c-cd012c0b2ca5.png)

In flow-bin 0.51.0 the files links can not be clicked.

![image](https://user-images.githubusercontent.com/10529679/30546046-29b2dce6-9c94-11e7-9e35-19e3e32e7ee2.png)

**Comment by adavidof** [comment]
breaking changes:
https://github.com/facebook/flow/blob/77c6bed34878a7904e97050ac6991dd7c9f80f17/src/common/errors/errors.ml#L942
