### ISSUE TITLE
Fuction declaration using type aliases

### ISSUE THREAD

**Issue by entropitor** [facebook/flow#4907]
It would be nice if we could declare e.g. an koa middleware function as such without having to annotate all parameters. 

So declare the function (as a whole) as matching a certain type alias

**Comment by lll000111** [comment]
Do you mean like this:

https://github.com/facebook/flow/blob/master/lib/node.js#L740

I picked a random list of functions in the bundled node.js definitions, inside the "fs" module definitions. There even is overloading, see `readDir` or `open`, for functions with a variable number of parameters.

**Comment by entropitor** [comment]
No I mean like 

```js
type renameType = (string, string, ?ErrnoError => void) => void
declare function rename: renameType
```
but preferably inline with the function

I'm mainly thinking about libraries like express, koa, redux, ... where you need to pass functions of a specific type to these libraries. If you export the function somewhere, you have to type it but it's annoying to type all parameters separately instead of just using the type alias from the library.

**Comment by asolove-stripe** [comment]
You can write out a function type and then export the function as a variable binding rather than a literal `function`, [like this](https://flow.org/try/#0C4TwDgpgBAysCGxoF4oG94C4oDsCuAtgEYQBOAvgNwBQokUAggMbACWA9jlKmnRNgCJ4OALTwWHHAKq1w0AEoQAJniZluUABQBnBEmxxEEADRRxbTtmYWcASm4A+WHog1qEAB5h2pYFCaculAEIIoqaqTYYarqqDoupuaS9shOukaUQA):

```
type State = {a: number};
type Action = {type: "an-action"};
type Reducer = (state: State, action: Action) => State;

export const myReducer: Reducer = (state, action) => state;
```

**Comment by entropitor** [comment]
So there is no way of doing this with the normal function syntax?

**Comment by asolove-stripe** [comment]
No, there isn't. You want to annotate the type of a while function value, and using `let` or `const` on a function value lets you do that. With a function declaration, it's not clear to me where the annotation could even go to provide the type of the whole function.

**Comment by entropitor** [comment]
I'm not sure where it would go, a seperate `declare` statement or something would be fine for me. I just prefer using the `function` syntax as I can name my functions then. As arrow functions and "old" functions have a different semantic, I find it weird that we can't both type them as a whole. Especially because js is such a functional language these days

**Comment by asolove-stripe** [comment]
@entropitor oh, yeah! `declare` seems to work for this:

```js
declare var reducer: Reducer;
export function reducer(state, action) {
  return state;
}
```
