### ISSUE TITLE
Providing the Wrong Type?!

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4914]
Originally posted this over at ide-flowtype but they said it was a flow bug so I am reporting here!  It would appear that flow is getting some information incorrect.  I am not sure if it is using a cached value or something, but the keys that are missing from the type are actually the first values I added to the type so that wouldn't make sense.

I am thinking perhaps this is due to Generators somehow?  Not sure how its getting only some of the values of this though.

Anyway,

I have a file:

```js
/* @flow */
import { put } from 'redux-saga/effects';

type NotificationAction = {|
  label: string,
  callback: () => void,
|};

type NotificationParams = {|
  title: string,
  message: string,
  uid?: number | string,
  level?: 'info' | 'warning' | 'success' | 'error',
  position?: 'tr' | 'tl' | 'tc' | 'br' | 'bl' | 'bc',
  autoDismiss?: number,
  dismissable?: boolean,
  action?: NotificationAction,
  children?: any,
  sfx?: string,
  say?: string,
  onAdd?: (notification: NotificationParams) => void,
  onRemove?: (notification: NotificationParams) => void,
|};

type NotifyUserAction = {|
  type: 'NOTIFY_USER',
  params: NotificationParams,
  sfx?: string,
  say?: string,
|};

export default function* notifyUser(params: NotificationParams): Generator<*, *, *> {
  const notificationAction: NotifyUserAction = {
    type: 'NOTIFY_USER',
    params,
  };
  yield put(notificationAction);
}
```

Then in a file that is using this, it does popup the type but it is incorrect:

![image](https://user-images.githubusercontent.com/15365418/30563890-1fc12cea-9c78-11e7-9500-c30aac5282cd.png)

When I run flow type-at-pos directly, I get similar results:

```
{"type":"{action?: {|callback: () => void, label: string|}, autoDismiss?: number, children?: any, dismissable?: boolean, level?: 'error' | 'info' | 'success' | 'warning', onAdd?: (notification: any) => void, onRemove?: (notification: any) => void, position?: 'bc' | 'bl' | 'br' | 'tc' | 'tl' | 'tr', say?: string, sfx?: string, uid?: number | string}","reasons":[],"loc":{"source":"/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/app/shared/processes/dash/console/console.js","type":"SourceFile","start":{"line":375,"column":27,"offset":10864},"end":{"line":380,"column":9,"offset":10994}},"path":"/Users/bradennapier/Desktop/Dash OS/IDE/projects/dash-desktop/app/shared/processes/dash/console/console.js","line":375,"endline":380,"start":27,"end":9}
```

What is interesting, is that if I make a value optional instead of required in this situation, it actually shows up!

![image](https://user-images.githubusercontent.com/15365418/30564023-7c1e9c52-9c78-11e7-9ab0-235c9351fd6e.png)

So it would appear that object types in parameters are stripping all required values.  

**If I make all values required, it simply fails all together!**

**Results are the same whether the object is exact or not**

**I tried renaming just in case somehow there was a conflict**

---

In addition, the errors are actually not reporting:

![image](https://user-images.githubusercontent.com/15365418/30564078-ad4dd662-9c78-11e7-844d-b1fe0eb7afca.png)

Flow does not report that there is an error with this (even though message and title are required values).  

However, if I go to the notify user script itself,

![image](https://user-images.githubusercontent.com/15365418/30564096-c29e1d60-9c78-11e7-9606-df555417436c.png)

It does appear to report the error that is occurring.  On that note - this is the worst part of flow... it is telling me that at least one caller of this function is doing it wrong... **but does not tell me where!!!**

**Comment by bradennapier** [comment]
I take back the Generator thing, I tried it without generator and I am getting the same result:

![image](https://user-images.githubusercontent.com/15365418/30564951-82de645c-9c7b-11e7-96fe-328dead8d0fa.png)

It appears that it simply will not report an object which has both optional and required properties.

**Comment by asolove-stripe** [comment]
Can you try replacing the stars in `Generator<*, *, *>` with the actual types you expect? I think Flow is just inferring a type different than you expect.

**Comment by bradennapier** [comment]
I did.  I show in the examples that I tried without Generators at all.

![image](https://user-images.githubusercontent.com/15365418/30605223-22a518cc-9d22-11e7-89e8-32660045c34f.png)

**Comment by bradennapier** [comment]
Can actually easily re-create it too.. 

Create two files


```js
/* @flow */

type Test = {|
  one: string,
  two?: number,
|};

export default function test(a: Test): Test {
  return a;
}
```

and two

```js
/* @flow */

import fn from './one';

function test() {
  fn({});
}

```

![image](https://user-images.githubusercontent.com/15365418/30605392-c372ce84-9d22-11e7-878a-d048d261d3a2.png)


![image](https://user-images.githubusercontent.com/15365418/30605400-c8e9c426-9d22-11e7-92ca-e0371b047268.png)

**Comment by asolove-stripe** [comment]
If I run those two files through flow, I get the error I would expect: 

<img width="792" alt="screen shot 2017-09-19 at 10 44 02 am" src="https://user-images.githubusercontent.com/31866720/30606738-901c3b38-9d27-11e7-930d-b58353f724bf.png">

**Comment by bradennapier** [comment]
Use flow type-at-pos on the object ---- On Tue, 19 Sep 2017 10:45:12 -0700  Adam Solove<notifications@github.com> wrote ----If I run those two files through flow, I get the error I would expect:   —You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.

**Comment by asolove-stripe** [comment]
For the usage of the function, I get

```
➜  flow flow type-at-pos src/generator/two.js 6 3
(a: {|one: string, two?: number|}) => {|one: string, two?: number|}
```

Which looks right to me. 

For the argument I get:

```
➜  flow flow type-at-pos src/generator/two.js 6 6
{two?: number}
```

Which is the maximal thing Flow can say when trying to get an empty object to match the expected argument type.

What would you expect to show up differently?

**Comment by bradennapier** [comment]
@asolove The function is annotated in a way that indicates that its first argument is an object the is of the type: `{| one: string, two?: number |}` which is an object that has a required key of "one" whic is a string and an optional key of two which is a number.

When composing the object in the first argument of the annotated function, the type that shows up omits the REQUIRED key all together from the type which is hinted and only shows the optional value.

Therefore, basic common  sense would say that it should return  `{| one: string, two?: number |}` rather than only the optional part of the object?  What good does that do?

**Comment by asolove-stripe** [comment]
It would be inaccurate to take the object `{}` and have type at pos show a type that isn't actually the type of that argument. It is showing you the right type for that object. That it isn't the type that it should be for the program to be valid doesn't really come into the question. So I don't think there is any chance that type at pos will change its behavior to show the desired type at that position rather than the real type.

That said, it's definitely frustrating for the editor to show you the real type rather than the expected type. At least in my IDE (Code), when typing in a function argument it shows the function signature and highlights the argument and type needed for the one I'm typing in. Sounds like you're using a different editor or extension that doesn't do that. So it might be a thing to improve there.

**Comment by bradennapier** [comment]
I am using ide-flowtype for Atom Editor.  I will bring it up again over there now that there is a better understanding of the issue at hand.  Thanks.
