### ISSUE TITLE
Does not handle [yield*] properly

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#4915]
Related to the other issue I just posted: https://github.com/facebook/flow/issues/4914

In the issue I show that the function reports the appropriate flow type whereas the object is showing incorrectly.

During that report I realized there was another bug.  

When using `yield*` it does not know the parameters of the given call.  However, if I use it as a normal function instead, it does properly annotate when highlighting the FUNCTION (it will never show the right object when highlighting the object - at which point all REQUIRED values are removed as discussed in #4914 ).

In the ide-flowtype package, it is still linking to the right place just not showing th eright flow type.  

** I get the same results if I use the cli with type-at-pos **

![image](https://user-images.githubusercontent.com/15365418/30565402-f9dfcbb2-9c7c-11e7-8e81-eed9f9b3887e.png)

**Comment by SamChou19815** [comment]
not enough info to repro
