### ISSUE TITLE
v0.55 release: where are the binaries?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4918]
https://github.com/facebook/flow/releases/tag/v0.55.0

Still no binaries.

**Comment by nmote** [comment]
The binaries are up now

**Comment by nmote** [comment]
Actually we are still missing the OS X build, sorry

**Comment by jcready** [comment]
The release notes also appear to have gotten mangled somehow. It now just says:

```
Avoid builtin lookups for trivial constraints involving ObjProtoT, Fu…

…nProtoT

Reviewed By: mroch

Differential Revision: D5847095

fbshipit-source-id: 2d7eec45402adc4bc2540a8a3ca76cf97490584d
```

**Comment by nmote** [comment]
Ugh, you're right. I'll fix it. In the meantime you can just look at the changelog at the root of the repo

**Comment by julienw** [comment]
I guess we're waiting for the other build to finish for npm publishing ?

**Comment by steida** [comment]
Any progress? Need to fix some code for tomorrow training :-)

**Comment by nmote** [comment]
I'd use 0.54.1 for now, some other issues came up with this release and I'll likely have to start on 0.55.1 today.

**Comment by nmote** [comment]
Okay, Travis has finished and the binaries are now up. It looks like the issue I identified was also present in 0.54.1 and it only manifests in specific circumstances so I will move forward with 0.55.0. I'll publish flow-bin shortly. Thanks for your patience, everyone.

**Comment by lll000111** [comment]
@nmote The text still is messed up. The text was fine - ironically, only until the first binary appeared....

**Comment by nmote** [comment]
I know, I'm going to get to it.

**Comment by nmote** [comment]
I think everything is in order now. I published `flow-bin` and I fixed the release notes on the release page. Let me know if I've missed anything else.
