### ISSUE TITLE
Interface files ignored 

### ISSUE THREAD

**Issue by almost** [facebook/flow#492]
I have [this file](https://gist.github.com/almost/896e09abda916aa55e60) in `interfaces/underscore.js` in my project and my `[libs]` section of `.flowconfig` is:

```
[libs]
node_modules/react-native/Libraries/react-native/react-native-interface.js
interfaces/
```

Yet I don't seem to be getting any type checking for my use of underscore. The following file fails to raise any flow errors:

```
// @flow
var _ = require('underscore');
_.blarg(99);
```

Any ideas what I'm doing wrong?

**Comment by avikchaudhuri** [comment]
Hmm, couldn't repro, I'm getting an error like:
/home/avik/test/issue-492.js:3:1,11: call of method blarg
Could not resolve name

**Comment by avikchaudhuri** [comment]
Are you sure this file is somewhere under the directory that contains .flowconfig and is not being ignored?

**Comment by samwgoldman** [comment]
I have no problem reproducing this if I run `npm install underscore` first, so that the `node_modules` directory exists. Pretty sure this is the same issue as #447.
