### ISSUE TITLE
Missing type is not detected by flow

### ISSUE THREAD

**Issue by steida** [facebook/flow#4921]
I have this code:

```js
import type { mePageQueryResponseFOO_BLA_BAR } from './__generated__/mePageQuery.graphql';
```
And missing type is not detected. I just spend an hour then I realized I renamed Relay Query.

**Comment by TiddoLangerak** [comment]
What version of flow are you running? This does seem to be working properly in the latest version (and if my memory serves me well it has been working well for many versions already).

**Comment by steida** [comment]
Rechecked with 0.54.1 Only coverage has changed without an error.

**Comment by awestroke** [comment]
I have noticed the same problem when the target file does not have `// @flow` at the top. Flow should warn when an import fails.

**Comment by TrySound** [comment]
This is a bug with untyped-type-import. This issue explains the problem better
https://github.com/facebook/flow/issues/7444
