### ISSUE TITLE
Inference doesn't work for Promises, sometimes

### ISSUE THREAD

**Issue by julienw** [facebook/flow#4923]
This actually comes from https://github.com/rpl/flow-coverage-report/ where the current master code fails to check with flow v0.54. [I made a PR there to fix this](https://github.com/rpl/flow-coverage-report/pull/116/files), but I don't get why Flow doesn't infer this properly.

I made a [reduced testcase on try](https://flow.org/try/#0GYVwdgxgLglg9mABAJwKZgCauQCQCoCyAMgEqoAOcyUAFHOVAPQBUiAXIgPIBGAVqtETNGASkQBvAFCJEMYIjoMAdMBgAbdAEMAtqkQAyfdJkn6UFeq26lMTKgAenYDQDkSpS7EA+ALyIADGJSJiioUCDISAAKyHDaMADOqEpo-NA0YKgA7ogAosixyDTGIS6qGmA6eomIYHBQoWqasABuelBwiFAAFnrksWlQACIwyBwuiADUJSGIANpmSv1wgyPIADSIi+VWqAC6Srxwtq6IALSInjMiIgDcxgC+ksagkLAIiAkg2tqayACeZEo1AAwggoOhaEEZmhwpFatlEDE4olUDQ0Ak4Go2ogfF4JDMZBAEAkGmhgVAAGKWKLNbq4y7kOkue6zRDEsCk0IU6kaMFgCEChkuDmCqAswmhTHYtHBNncqhUml09aSmTkxW81D8sWSh53Gb61mIJ4vcDQeBITERCCoIGKnWQmjQkKwiJITI5ZHxJLo1DSnF4glsjlcjXULWOoV+EXgyESkMkskUTXKnrCpk9BOzDFYto0OVs8NKjS0nqq+UKiOWKNQPUGkJGx7PGQaBpZTQwKlUe2guMC+7GBJZLsQemKcxQf7kVAukwQTRJS5fH5-f4uNiSjtdyk9lN9gWQhkr34A3tQWvO40hbhoTQAa2v7MXehc1uQtp2G63ne7yHPtbHnANp2vuF79lCT4yLeqAPk+WDAJoIBqFAm5FmE7pIrEPrJKkAi0J6eQFFQrgAKpgPedRZEgxZdNOqDjFMWzKFOM43Maprqhh8Lbn+AEQUoPToH6CS4vihbskmVYlqgZb0n4GIpGBWpyU+obJjyNYQQyinFpGEFqSSWLJGocAAOZ+pppYqtJ+mHgKDYmgapoOBSiAIUhKHBqEdhjD5WC4IQpBgZIDz3EAA).
```javascript
function renderHTMLReport(opt/* : Object */) {
  if (opt.filename &&
      opt.filename.indexOf('..') >= 0) {
    return Promise.reject(new Error(
      'filename is not relative to the projectDir: ' +
        [opt.projectDir, opt.filename].join(' - ')
    ));
  }

  function summaryReportContent() {
    return new Promise(resolve => {
      const reportFilePath = 'path';
      const reportFileContent = 'content';
      resolve({
        reportFilePath,
        reportFileContent
      });
    });
  }

  function sourceReportContent() {
    return new Promise(resolve => {
      const reportFileContent = 'content';
      const reportFilePath = 'path';
      resolve({
        reportFilePath,
        reportFileContent
      });
    });
  }

  let waitForReportContent;

  switch (opt.type) {
    case 'summary':
      waitForReportContent = summaryReportContent();
      break;
    case 'sourcefile':
      waitForReportContent = sourceReportContent();
      break;
    default:
      return Promise.reject(new Error('Unknown report type: ' + opt.type));
  }

  return waitForReportContent.then(res => {
    const reportFilePath = res.reportFilePath;
    const reportFileContent = res.reportFileContent;
    console.log(reportFilePath, reportFileContent);
  });
}

export default {
  render: renderHTMLReport
};
```

But [my try to reproduce from scratch](https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCjgB1ggSkQG8AoRRANwEMAnRHWuAWxjRQG5TzEZhFseeEgC8YxAHJgcOBKJkKFRizYpEIxGBQB3RAAUmrdplro4AG0pqRAPhI9FiU2gtXMCx4ulwAXJIBGdBIOigC+BFyO4ZGIoYgo5uz2jspG1vqGqgB0pgBWKNCYEgAWCeZwiNpwtOYAJnIxoTw8plAgtEipqlxNpDT0XUkaqBhFgbQNpIMoWVClYCbo6nYQCC7mM+UA5otoBBFAA) doesn't show any error.
```javascript
function test(option): Promise<*> {
  var promise;

  if (option === 'foo') {
    promise = new Promise(resolve => {
      resolve({
        foo: 'bar'
      });
    });
  } else {
    promise = Promise.reject('hello world');
  }
  
  return promise;
}

var promise = test('bar');
promise.then(res => console.log(res));
```

Other notes:
1. if I remove the export in the first example, then Flow passes.
2. in the second example, when I look at the infered type, I can see that `res` line 18 is properly infered as `{foo: string}`. However the `promise` line 5 is just a `Promise`, line 2 or 17 it doesn't give me anything. When I mark the function as returning `Promise<*>` then line 17 it's infered properly as `Promise<{foo: string}>`.

So I don't get why Flow properly infers `res` but not `promise` in the second example. And I don't get hwy the first example doesn't work unless I "help" Flow by typing the return value of `renderHTMLReport`.

Thanks !

**Comment by julienw** [comment]
My guess is Flow starts infering by looking at how a method is called, and then checks whether it works with the existing code. But in an exported function in a library we can't know how it's called so it can't infer properly.

**Comment by vkurchatkin** [comment]
Seems to be a regression:

```js
export const y = () => 1; // this is fine
export const x = () => Promise.resolve(1); // this isn't
```

**Comment by julienw** [comment]
I believe there is a similar bug with Map.

Any progress on this ?

**Comment by julienw** [comment]
Problem with Map:
This doesn't work:
```javascript
export const map = new Map();
map.set(1, 'foo');
```
This works:
```javascript
export const map: Map<*, *> = new Map();
map.set(1, 'foo');
```

In the first example, Flow see `map` is `Map`, and so it fails because now generic types should be explicitely specified. But because merely manually adding `<*, *>` makes it work, I think Flow should be able to do the same automatically.

**Comment by vkurchatkin** [comment]
@julienw this is not a bug, Flow requires explicit annotations for exports

**Comment by julienw** [comment]
I have a few questions:
1. How is it different than https://github.com/facebook/flow/issues/4923#issuecomment-330830217 where you said it's a bug ?

2. Flow can actually infer than `map` is a Map. Why can't it infer it's a `Map<*, *>` instead so that it can infer even more.
