### ISSUE TITLE
React: Props inference in class components

### ISSUE THREAD

**Issue by tempname11** [facebook/flow#4925]
Since 0.53, there doesn't seem to be a good way to define a component without either explicitly stating its props or losing the type inference. The first type argument of `React.Component` is now mandatory, and my first thought was to put `*` there to allow inference to happen. But that does not work. (component `X` in the example)

A more cunning way is `class Foo<T: *> extends React.Component<T> { ... }`, which in my limited testing did allow inference to happen, but unfortunately, the error messages only point to the component code, not the usage code, which limits the usefulness. (component `Y` in the example)

This is a bit unfortunate since it limits the ability to create small helper components quickly (and safely), like you would do with helper functions.

P.S. in fact, as I just checked, the functional components with inferred props also suffer from the same unhelpful error messages. So this might be a more general problem. (component `Z` in the example)

[Try here.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnRjkKADTDUAHgWoA7ACYUa9AgDoAwi1wzZBADwgAfGADeqMGE7zqeABQBKE2fNgCAC3RkV2Ztk9Q4cHzOFtQEAK54MmAyYTAwQWAAvqjJAkJkFACaugAqAFzIRpLS8opcqho4cNoyejlGpuaWctb2jsFuHl4+fgEJTaERUTFxCcmpdNVkRABaYAC8YDbecL4O8w1OK74q-oFOnOGR0bHxKfy6IsAGfJdge-PGAIyJ13youplvH5n3AY8vb4fGbfXRzB7PV43IA)

**Comment by asolove** [comment]
I’m pretty sure this is deliberate. The type inference on props pre v53 was useful in small cases but quickly led to surprising or incorrect results for anything larger or more complex. Requiring authors to declare the expected props resolved dozens of old issues on here (which I got to manually review and close!) so I doubt the prop inference is coming back soon.

**Comment by TrySound** [comment]
@tempname11 Is this still relevant?

**Comment by tempname11** [comment]
Yes, it is. Even on 0.67.1, the [try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnRjkKADTDUAHgWoA7ACYUa9AgDoAwi1wzZBADwgAfGADeqMGE7zqeABQBKE2fNgCAC3RkV2Ztk9Q4cHzOFtQEAK54MmAyYTAwQWAAvqjJAkJkFACaugAqAFzIRpLS8opcqho4cNoyejlGpuaWctb2jsFuHl4+fgEJTaERUTFxCcmpdNVkRABaYAC8YDbecL4O8w1OK74q-oFOnOGR0bHxKfy6IsAGfJdge-PGAIyJ13youplvH5n3AY8vb4fGbfXRzB7PV43IA) from above still suffers from the same problem:

This error message could be better (point to usage props instead of built-in lib):
```
    13:     this.props.foo;
                       ^ Cannot get `this.props.foo` because property `foo` is missing in props [1].
        References:
        [LIB] static/v0.67.1/flowlib/react.js:29:   props: Props;
                                                           ^ [1]
```

The second error message is actually good, so at least this problem is fixed.
```
    19:   props.foo;
                ^ Cannot get `props.foo` because property `foo` is missing in props [1].
        References:
        29: <Z/>;
            ^ [1]
```

Component "X" still typechecks, although it should not.

Ideally, all three cases would have an error message like the one from "Z" above.
