### ISSUE TITLE
Could not resolve name 'DOMStringMap'

### ISSUE THREAD

**Issue by MichaelDeBoey** [facebook/flow#4926]
What's the best way to resolve this one?
It's [in the standard API](https://developer.mozilla.org/en-US/docs/Web/API/DOMStringMap) so...

index.js:
```js
const rootElement = document.getElementsByClassName('root-element')[0];
ReactDOM.render(<App dataset={rootElement.dataset}/>, rootElement);
```

App.jsx:
```js
const App = ({dataset}: { dataset: DOMStringMap }) => (
  /* ... */
);
```

Flow error:
```bash
Error: src/App.jsx:19
 19: const App = ({dataset}: { dataset: DOMStringMap }) => (
                                        ^^^^^^^^^^^^ identifier `DOMStringMap`. Could not resolve name
```

**Comment by asolove** [comment]
This type needs to be defined in the flow standard typings for the browser environment. Shouldn’t be too hard but someone needs to do it. See lib/bom.js.

**Comment by lll000111** [comment]
This is related: https://github.com/facebook/flow/issues/3355 `DOMStringList` is _not_ an array of strings.

**Comment by MichaelDeBoey** [comment]
@asolove @jcready Any news on this one? 🙂
