### ISSUE TITLE
Flow gets confused about this use of generics plus union

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4929]
### Description

I have two different unions of objects (versioned and unversioned objects), and for each one a creation result (object) type "UnversionedObjectCreation" and "VersionedObjectCreation". They use a generics parameter to limit each one to the versioned or unversioned object types respectively.

Since they are similar (the versioned one has two more properties, otherwise they are the same) I also have a union of those two object creation types. This one has two generics parameters "(U, V)", one is "forwarded" to the unversioned, one to the versioned component of the union.

This mostly works, except for when I try to use a union of object types as generics parameter instead of only a single one. Out of this problem I created a tiny piece of code (compared to the original) that already gets equally confused (and confusing).

What I'm trying to do is to tell Flow that a particular function returns an array of results of (for example) of objects UV1, V1 and V2. It works when I have two "*" generic parameters, or two single object types. But I want `<UV1, V1 | V2>`, what is the problem?

### Code

If you remove the return type union and instead of `ResultType<V1 | V2>` write `ResultType<V1>` it works. But I want `v2Result` in there too.

```js
type V1 = {type: 'v1'};
type V2 = {type: 'v2'};

type MyUnion = V1 | V2;

type ResultType<T: MyUnion> = {|
    obj: T,
    objHash: string,
    idHash: string
|};

function demo (
    v1Result: ResultType<V1>,
    v2Result: ResultType<V2>
): Array<ResultType<V1 | V2>> {
    return [v1Result];
};
```

[**Flow Try Link nr. 1**](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKK4CeADtgGoCMoAvKAN60MBcoyAG7NkAX0o8mAJnZdJ-IVLET6TAMyzuqhYLXKqk0AFkaAVQB2hWOdktQAH1CMZjxmsrVVoAEqZ0qaFwAFVUAHiD+EwsrcwA+TXtEUGTQWAAjACt+IMR7cSpIVHNSGNAAE0wAW1hQAAoklOFff0D+ZoDgsJZYgBoG5MEpdtafPw6QhlDnWMQASn4AQXx8AEMaUOHOybtXKVj4zn7QfExcVHwbAG0mscCAXUp8oA)

### Error

```
Error: src/main.js:4
  4: type V1 = {type: 'v1'};
                      ^^^^ string literal `v1`. Expected string literal `v2`, got `v1` instead
  5: type V2 = {type: 'v2'};
                      ^^^^ string literal `v2`

Error: src/main.js:5
  5: type V2 = {type: 'v2'};
                      ^^^^ string literal `v2`. Expected string literal `v1`, got `v2` instead
  4: type V1 = {type: 'v1'};
                      ^^^^ string literal `v1`

Found 2 errors
```

### Modifications

Even smaller, I can leave out the array and just use

```js
function demo (
    v1Result: ResultType<V1>,
    v2Result: ResultType<V2>
): ResultType<V1 | V2> {
    return v1Result;
};
```

This plain-type version has no errors.

```js
function demo (
    v1Result: V1,
    v2Result: V2
): V1 | V2 {
    return v1Result;
};
```

<br>
<hr>

The above is the _very_ short version of what I really want to do. A slightly longer version with more verbose names that show the intended use:

[**Flow Try Link nr. 2**](https://flow.org/try/#0PTAEAFQMwGwewO4CgDkBXAzgU1BgLgE4CWAxnigNxJJ4CeADjgKoBqAjKALygDedjALlDoAbmxQBfKv2YsATF14yhouZKo0GOdor5aVY9Zsah5u5cJFqp1GaADyAOyxNHIrAQxE4zgCb2AIwArLDIAFS0MRVYOAB9QVjlpLQdnFg8vHyx-YNC8CMYo7h14+Q07V3dPbz9AkLIAYQIsAEM8GoAeMKEnFzcMmuy6vIKsDAA+XVikUFnQOGChMIAaGbmFoIAJFowACyF8YkcAc1XYm2NtAayc+rwm1vafLp6069rc8MjJ7h5pufmi1AKzWsw22z2B0IRBOqwBRF8EP2uGhJyQ53KKWGjWabU6TFefSqmQ+d1GGGWpkJ6WqN2x+W+XFBCX6tNJeQeeOeTEm-zmNJJQ0+91xT0cHRY4w0O1ojhI0DQcrFoF8WAAtnBQAAKZktAgEVhCACC+patA6lXeQrunLFFvY43GcLmeoI7GNpvNAsGtw5os6Dqduv18g9BDNEqtvpxjwDckdSAAlEIAAoEOBqojYDom8Pm+m2-HsSklUzxx28ZnNPBoAiOUAAbWZAIAdG3XexmQBdKg2IA)

<br>

**Comment by samwgoldman** [comment]
So, for some type `T<X>` and unrelated types `A` and `B`, is `T<A>` a subtype of `T<A|B>`?

It depends on the polarity of `X` in `T`. In your example, it's neutral, so invariance holds: `T<A> <: T<A|B> => A <: A|B && A|B <: A`. The `A|B <: A` part is untrue, and is the type error here.

If `X` had a positive polarity in `T`, then covariance would hold: `T<A> <: T<A|B> => A <: A|B`, and `A <: A|B` is trivially true.

All of that is a long-winded, overly technical way of saying put a `+` on the type parameter to `ResultType`, [like so](https://flow.org/try/#0C4TwDgpgBAagjFAvFA3qSAuKByAbnbAXwG4AodaGAJiVQqzyqLPPGgFkQBVAOwEsA9j1rwoAH1hUWFKACUIAZwCuAG2AAVNgB4A1OqydegngD5aKMaSjWoOgQCMAVlnUAaKzYeOAEgEMFABZYCsAATnw8AObuNlB8ACZ+gcFhEZGkYiSkpABmSjwAxsDGUPEQALYCUAAUHtb48spqWI2qGtrwJjE2uFStzXKKbZqQWtQmpACUWACCoaG+IFr97aOiEuNmKHVQoRDASqHCANoNQ2oAumRZQA).

**Comment by lll000111** [comment]
Works, great. But I don't understand what you just wrote, and I think that's the problem with this type stuff: It is FAR more complicated than the code it is supposed to annotate. To me it's simple: A union is when I want to tell the type system that something could be any of those things, and that's how it usually works.

Is the general rule then that in order to use a union of types as a generics parameter I have to use the "+", and without it it has to be a single parameter only?

**Comment by ElvenMonky** [comment]
For any T<X>, T<A|B> can only be a shortcut for T<A>|T<B>. It's logically impossible to implement T<X> to return something from A|B that is neither T<A> or T<B>. Prove me if I'm wrong.

**Comment by lll000111** [comment]
Here is a dot: 

.

Q.E.D, You are wrong. Prove me wrong!

**Comment by ElvenMonky** [comment]
Ever heard about math? Any constructive arguments?

**Comment by lll000111** [comment]
@ElvenMonky Keep talking to yourself &mdash; but please do so at home, little stupid child. Get out of my (closed!!!) issue.
