### ISSUE TITLE
Doing a regex test (of anything unrelated) after checking a property for "typeof === string" takes its status back to "mixed"

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#4933]
### Problem

I'm checking an unknown variable (might come from the network).

The problem occurs when checking a _property_ of the object &mdash; it does not occur when checking a variable.

I don't have any inner functions, just straight code, and I have a `typeof` check for string for the property `itemprop`.

The check works, but only for the immediately preceding next check (Flow would complain if the input into `regex.test()` was not a string). The presence of that regex test puts for some reason erases the result of the `typeof` string check!

### Code

```js
// @flow
'use strict';

function demo (thing: mixed): void {
    if (typeof thing !== 'object' || thing === null) {
        throw new TypeError(`Not an object but "${typeof thing}"`);
    }

    if (typeof thing.itemprop !== 'string') {
        throw new TypeError('foo');
    }

    // thing.itemprop IS A STRING FROM HERE ON

    // If this "if" does not exist - no problem. When it exists, thing.itemprop
    // in the next "if" causes Flow error "mixed. This type cannot be used"
    if (/[<>\s]+/.test(thing.itemprop)) {
        throw new TypeError('bar');
    }

    console.log('itemprop: "' + thing.itemprop);
    //                          ^^^^^^^^^^^^^^
    // mixed. This type cannot be used in an addition because
    // it is unknown whether it behaves like a string or a number.
}
```

Flow does not complain without the **string concatenation**, for example, `console.log(thing.itemprop)`, 

Equally, if I repeat the `typeof` string check if statement after the regex test it works too.

### Try

[**Flow Try Link**](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKKSoB2phstoAJpgLaygAUuAFoVoBzAFyh2hAB6YWASjEA3WIRagA3olBbQhSD1wBPAA6ZYe-oKGgAhAF5boZLABGAK0ylkoAD7fQF4VB7B1pUaGhZdU1tGP58BFBaTHhQABVjTABRfHj8bgADADlYXFAAQ2YXd1JQZ1RSgCIAEjVDEzN-AWEAXwb82UoY7qoY3X0MjoChADpCXA4jeKMbe0c8ImFkSI0Y2L54lKSU9JNs3O5kSFhYLcHtYeitEFAASXMBdFAG3QbWWExPrQSqBMJJCHhQABaRJcRYuaAcaagADqfEwzDmILBeHQABpOpZZvN2HCjI9QM9BJ1sElJI0fqBiGUMADQAAxOApTA5WD4L4SaQsJGpD7+DKMipA0rObAslgNcljbjAADaAB4AHwAHXQAF0ANTAabzPC8LozOYLJaybbkvYHRLJNIZM68i7OMr4W7kh4xYhMdCwBHTOBCC6WklLMQNLz6gnCIlW2BGAbk567DOZzMAPVzefz+bTYAFMmFora2CZtCltVlWFUVIq5RYLDmjGYMqZLKLOlK4NAdAA1kD4Mx4Gj+Nze7W+GUFKzoIRB9gyjgCJZQLzyolUOwZfhpohhkA)

The statement between the `typeof` check and the use of the property does not have to be another check of that same property, I can replace the regex check in the demo code below with `console.log(/[<>\s]+/.test("some string"));` and get the same result:

[**Alternative Flow Try Link**](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKKSoB2phstoAJpgLaygAUuAFoVoBzAFyh2hAB6YWASjEA3WIRagA3olBbQhSD1wBPAA6ZYe-oKGgAhAF5boZLABGAK0ylkoAD7fQF4VB7B1pUaGhZdU1tGP58BFBaTHhQABVjTABRfHj8bgADADlYXFAAQ2YXd1JQZ1RSgCIAEjVDEzN-AWEAXwb82UoY7qoY3X0MjoChADpCXA4jeKMbe0c8ImFkSI0Y2L54lKSU9JNs3O5kSFhYLcHtYeitEFAASXMBdFBoQWwWWExPrQSqBMJJCHhOph8NhwYkuIsXNAOI9QMQmOhYEjpnAhNxgABtAA8AD4ADroAC6AGpgNN5nhuA0MexsOtLA1ZAMRto0bQMVicRc5gslmIGl4qZ1LLN5uwEUYuTFnrsVarVQA9TVa7XalHPCTSFjTNIffwZVEVIGlZzYDAyHTMCrlFgsOaMZg24hlO16sBzHSfOgAayB8GY8D4mH4UJ01swfDKCgBX0IQewZRwBEsoFg+HKiVQ7Bt+GmiGGQA)

<br>

**Comment by vkurchatkin** [comment]
See: https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations

**Comment by lll000111** [comment]
@vkurchatkin  So are you telling me if I just do `console.log();` this magically invalidates the check? In which universe?
