### ISSUE TITLE
`import { type X }` has different runtime behaviour from `import type { X }`.

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#4935]
`import { type X }` results in a runtime import, while `import type { X }` does not:

```js
// in:
import { type X } from 'X';
import type { Y } from 'Y';

// out:
import 'X';
```

Is this intentional? I couldn't find it anywhere, and it surprised me a bit.

**Comment by jcready** [comment]
Flow isn’t a compiler so whatever is changing your input isn’t Flow.

**Comment by vkurchatkin** [comment]
I would say that it's not even obvious, what should happen in this case. Anyway, this should be reported to Babel issue tracker.

**Comment by TiddoLangerak** [comment]
I may hope though that this behaviour is dictated by flow, and not left up to the compiler. If compilers are free to interpret this however they see fit then different (versions of) compilers can result in different runtime behaviour, while still being "spec compliant". This might not be something to be fixed in flow source code, but this could at least be addressed in the spec/documentation (also quite important for users). That also makes it easier to file bugs at the appropriate places. E.g. I don't think the babel issue tracker is the right place to discuss what *should* happen since it merely follows the spec, but it is the right place to report a bug if it doesn't do what's explicitly defined in the spec.

**Comment by vkurchatkin** [comment]
I think that Babel is doing the right thing. `import { type X } from 'X';` is essentially interpreted as `import {} from 'X';`

**Comment by TiddoLangerak** [comment]
Ahh, that actually makes a lot of sense. I opened a PR to add this to the documentation as well, that might clarify things for other developers.
