### ISSUE TITLE
URLSearchParams constructors not all supported

### ISSUE THREAD

**Issue by newtang** [facebook/flow#4944]
URLSearchParams (under the Node url library) can take an [object or an iterable in the constructor](https://nodejs.org/api/url.html#url_constructor_new_urlsearchparams_obj). Only string is currently supported in the [current Flow class](https://github.com/facebook/flow/blob/v0.55.0/lib/node.js#L1621);

**Comment by ruyasan** [comment]
+1

The living spec calls for support for a sequence of pairs: https://url.spec.whatwg.org/#urlsearchparams

MDN also:
https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/URLSearchParams
