### ISSUE TITLE
Predicate functions using %checks unable to refine more than one thing

### ISSUE THREAD

**Issue by jcready** [facebook/flow#4948]
```js
/* @flow */

const isString = (x: mixed) : boolean %checks => typeof x === 'string'
const isObject = (x: mixed) : boolean %checks => typeof x === 'object' && !!x
const hasFoo1 = (x: mixed) : boolean %checks => typeof x === 'object' && !!x && typeof x.foo === 'string'
const hasFoo2 = (x: mixed) : boolean %checks => isObject(x) && isString(x.foo)

declare var x: mixed

if (typeof x === 'object' && !!x && typeof x.foo === 'string') {
  (x.foo: string) // passes
}

if (hasFoo1(x)) {
  (x.foo: string) // fails
}

if (isObject(x) && isString(x.foo)) {
  (x.foo: string) // passes
}

if (hasFoo2(x)) {
  (x.foo: string) // fails
}
```

([Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEtcBlfAJyOwHMwBeMACgA8AuMAWyJYFMATAJRgOAIzhwYvAIbYwAUgwALXhgDWuBgD4w+AJ4AHXnChgWDeowDkBKrSuYcBYrgDyogFarCjVh258QiJg4pIycooq6pr0OvpGJmYW1nCe3lZgAGSZYACEuSyOeIRK0rgAYhIAjAzM7Fw8AsJiElKyCsqqGtq6hsam5pYpaRj4Gdl5BVk58f1mAHRQEslgNpTUNA5YxWClFRIATLV+DYHNIa3hHVHdsS7uXqOswhMk5HY0rIsSguj8qjBpBReGAAG5Asz+Rr8dBEUxMWaJQaWVapR5jaaTcwTREDb5wFZrD5WYQAb1QYDq+I4tg2wmAwDABjKuF4uFQAF9YfC9pU4FVnmSKVSlnAaetaPTGVBpEQYOyuag4cwSA9vM9MW8JZ8WPjBELKV9ReKPlKmSy2ZzucxeYdBWByYbdcawLTJWAGWAZXKFUA))

**Comment by jcready** [comment]
@panagosg7 any ideas about this one?

**Comment by panagosg7** [comment]
Hi @jcready!

Sorry for taking this long on this one. Unfortunately, at the moment this mechanism only supports tests that refer to the top-level of a variable directly, and not some offset of an object variable, as is the case of the `typeof x.foo === 'string'` predicate.
