### ISSUE TITLE
^ StatelessComponent. Property not found in exports of "react"

### ISSUE THREAD

**Issue by gibbok** [facebook/flow#4949]
I receive two errors using flow and react when using annotation ReactElement and StatelessComponent :

Errors:
> ^ identifier ReactElement. Could not resolve name

and 

> ^ StatelessComponent. Property not found in

[Reproducible here](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0uKLCGUnRkAOxwBaACbISRAEbRKoIbFEBXIeMqQCwRDgCe6BQAVG6EgBUDCgLygA3olCgA1OKI5KALkUrUMylgANI4uHhgAssLeQr7+QSHOYejhRAAe0bEBwU7OyDSwQgDCsBqeMX5ZCfDUOAAWAQAi-DRYyOg4yAWeJDitQgDmiAC+PHwCwmKUQrLyispqGlr4Ooj5Qj2gAGLYlDSkOA1Eep5UtDgAdADKOO6U8iQkxRgFUzgAPCawZpaGAHygtgAFHZQG4PIFQElIkIIVC0hC8gVihoIdV3PUsE0SC02h0CqAhp5Pt8rABKE4cHAAUXkqFebyIQj0-2s-wcTnYOBUWCEoEBIScb0kADdfgLQG9gCKxU5ScNEJRUphcKDNEQVNA8Nt2Hseoc9IggA).

`
// @flow
import * as React from 'react'

/* eslint-disable no-undef */
type PropsType = {
  +date: number,
  +tempMin: number,
  +tempMax: number,
  +iconCode:number,
  +weatherDescription:string
}
/* eslint-enable no-undef */

const ForecastDay:React.StatelessComponent<PropsType> = ({ date, tempMin, tempMax, iconCode, weatherDescription }:PropsType):ReactElement<any> => {
  return (
    <div>
    </div>
  )
}
export default ForecastDay
`

My package.json:

> "dependencies": {
>     "babel": "6.23.0",
>     "babel-cli": "6.24.0",
>     "babel-preset-flow":"6.23.0",
>     "babel-core": "6.24.0",
>     "babel-loader": "6.4.1",
>     "babel-plugin-recharts": "1.1.0",
>     "babel-polyfill": "6.23.0",
>     "babel-preset-es2015": "6.24.0",
>     "babel-preset-react": "6.23.0",
>     "babel-preset-stage-2": "6.24.1",
>     "bower": "1.8.0",
>     "css-loader": "0.28.1",
>     "dot-prop-immutable": "1.3.1",
>     "extract-text-webpack-plugin": "2.1.0",
>     "file-loader": "0.11.1",
>     "flux-standard-action": "1.2.0",
>     "react": "15.6.1",
>     "react-dom": "15.6.1",
>     "react-redux": "5.0.6",
>     "react-router": "4.1.1",
>     "react-router-dom": "4.1.1",
>     "recharts": "0.22.4",
>     "redux": "3.6.0",
>     "redux-promise-middleware": "4.2.0",
>     "redux-thunk": "2.2.0",
>     "moment": "2.18.1",
>     "style-loader": "0.17.0",
>     "openlayers": "4.1.1",
>     "url-loader": "0.5.8",
>     "weather-icons": "1.3.2",
>     "webpack": "2.2.1",
>     "webpack-dev-server": "2.4.2"
>   },
>   "devDependencies": {
>     "babel-eslint": "8.0.0",
>     "enzyme": "2.9.1",
>     "enzyme-to-json": "1.5.1",
>     "eslint": "4.7.0",
>     "eslint-plugin-react": "6.10.0",
>     "jest": "21.1.0",
>     "jest-css-modules": "1.1.0",
>     "jest-enzyme": "3.8.2",
>     "react-addons-test-utils": "15.6.0",
>     "react-test-renderer": "15.6.1",
>     "redux-mock-store": "1.3.0",
>     "redux-test-utils": "0.1.2",
>     "sinon": "3.2.1",
>     "standard": "10.0.3",
>     "jest-cli":"21.1.0",
>     "fetch-mock":"5.12.2",
>     "flow-bin": "^0.55.0",
>     "flow-typed":"2.1.5",
>     "eslint-config-standard":"10.2.1",
>     "eslint-config-standard-flow": "1.0.1"
>   },
> 

Flow configuration file:

```
[ignore]
.*/node_modules/enzyme-matchers/.*
.*/node_modules/jest-enzyme/.*

[include]

[libs]

[lints]

[options]

```

**Comment by agentcooper** [comment]
Please check type definitions first. The type you want is called [StatelessFunctionalComponent](https://github.com/facebook/flow/blob/422821fd42c09c3ef609c60516fe754b601ea205/lib/react.js#L210).

Here is the [correct code](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0uKLCGUnRkAOxwBaACbISRAEbRKoIbFEBXIeMqQCwRDgCe6BQAVG6EgBUDCgLygA3olCgA1OKI5KALkUrUMylgANI4uHhgAssLeQr7+QSHOYejhRAAe0bEBwU7OyDSwQgDCsBqeMX5ZCfDUOAAWAQAi-DRYyOg4yAWeJDitQgDmiAC+PHwCwmKUQrLyispqGlr4Ooj5Qj2gAGLYlDSkOA1Eep5UtDgAdADKOO6U8iQkm2p0ndPQxRgFUzgAPCawZkshgAfKBbAAKOygNweQKgJKRIRwhFpOF5ArFDRw6ruepYJokFptDoFUBDTz-QFWACUJw4FwAovJUN8fkQhHpQdZQQ4nOwcCosEJQOCQk4fpIAG7AsWgH7AKUypzU4aISipTC4aGaIgqaB4bbsPY9Q56RBAA).
