### ISSUE TITLE
Allow declared class constructors to specify a non-void return type

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#495]
b99042b05a38cc72e7d147f33b38470d1bad715b made it possible for the inferred return type of a constructor to be non-void, but it seems that declared classes still can't specify a return type.

```
declare class D {
  constructor(): { x: number };
}

var d = new D();
d.x = "";
```

```
constructor call
Error:
object type
his type is incompatible with undefined

assignment of property x
Property not found in
D
```

This is useful for the "NamedConstructor" concept in IDL files. See #478.

**Comment by gabelevi** [comment]
I suppose I don't know for a fact that this is an easy fix. I'm just guessing :).

**Comment by samwgoldman** [comment]
I checked it out—agree it's pretty tractable. One thing I learned: an explicit `return undefined` *will* actually return an instance of the class, so we don't need to differentiate between explicit and implicit return types.

**Comment by avikchaudhuri** [comment]
Thanks for reporting, fix on the way.
