### ISSUE TITLE
Errors with `reselect` starting from v0.54

### ISSUE THREAD

**Issue by julienw** [facebook/flow#4959]
We have errors using reselect (I think) normally starting with v0.54. No issue with v0.53.1.

I managed to do a very reduced testcase [that you can also find on try](https://flow.org/try/#0C4TwDgpgBAyhA2EDGwD2AnAPAFRsAhsBADRTYAK6qYAzqdgEoQ0Cu8wAfFALxQDeAKCjCoAChoEiALjJ5CJKGCq0ZFZXSgA6bembAZ+AHYgA2gF0AlKqat2AbgEBfBwNCRYCZGnQBhXYQwefiEoHDkiekpqDUZmNmB6AEZ6ACYOURDhGk8UDESZOERcrFxJBTVopI5iTKhsou8UgpzvMLLI9VTq2t1bYAAxFkMkGQyREXx0AHN8smTa4UmpprIU2oseLli+kKsPBow2+Q7Ksht4jhdhI4iyKNp6c-YqsZF6rzzmg5Lw8vuYxLdca9eKDYajBZQJazbCJdabM5xdi7L4fH7tO6dRF9S5OFxuaC-IKCYQAM1QqAMxhqzgEAlJQxQAEtUIYoEQJKIkP4iIU0ajin4IAF0BsSVAkKyJHUmQBbMCIPnFILiMoFMp7CToJmGKYIgDk5NQ+ocwklhmlIPYSu8KqWMi1OqmmuA2t1BqNJrpZqlwAlqFlACMdRAACY2vJBbnC3ktDCvLJyhUQCPoGrApHAVPpqAWK7+i1+yVBkPhuPoFaq+Tq+QbbhcR3u3jR+SphP+kuGMOp+YZvqp3YORx0oA).

```javascript
type Selector<TState, TProps, TResult> = {
    (state: TState, props: TProps, ...rest: any[]): TResult;
};

type SelectorCreator = {
  <TState, TProps, TResult, T1, T2>(
    selector1: Selector<TState, TProps, T1>,
    selector2: Selector<TState, TProps, T2>,
    resultFunc: (
      arg1: T1,
      arg2: T2
    ) => TResult
  ): Selector<TState, TProps, TResult>;

  <TState, TProps, TResult, T1>(
    selector1: Selector<TState, TProps, T1>,
    resultFunc: (
      arg1: T1
    ) => TResult
  ): Selector<TState, TProps, TResult>;
};

type State = {
  foo: any,
};

function test(createSelector: SelectorCreator) {
  const simpleSelector = (state: State): string => 'foo';
  const resultSelector = (arg: string): string => 'foo';

  const combinedSelector1 = createSelector(
    simpleSelector,
    resultSelector,
  );

  const combinedSelector2: (state: State) => string = createSelector(
    combinedSelector1,
    resultSelector
  );
}
```

Error is:
```
    36:   const combinedSelector2: (state: State) => string = createSelector(
                                           ^ object type. This type is incompatible with the expected param type of
    29:   const resultSelector = (arg: string): string => 'foo';
                                       ^ string
```

There is an open issue about reselect from march in https://github.com/flowtype/flow-typed/issues/824 but I never got the issue they mentioned. There is also https://github.com/facebook/flow/issues/3024 that got no solution (but again I haven't encountered this issue before).

**Comment by jcready** [comment]
Seems to work if you flip the `SelectorCreator` order:

```js
type SelectorCreator = {
  <TState, TProps, TResult, T1>(
    selector1: Selector<TState, TProps, T1>,
    resultFunc: (
      arg1: T1
    ) => TResult
  ): Selector<TState, TProps, TResult>;

  <TState, TProps, TResult, T1, T2>(
    selector1: Selector<TState, TProps, T1>,
    selector2: Selector<TState, TProps, T2>,
    resultFunc: (
      arg1: T1,
      arg2: T2
    ) => TResult
  ): Selector<TState, TProps, TResult>;
};
```

**Comment by julienw** [comment]
Should reselect's libdef be updated ?

**Comment by thehogfather** [comment]
@julienw if you are keen, I'm working on type definitions for reselect. Trying to get more perspectives on how well it works on other peoples projects before I send a PR . Seems to be working for mine. See [here](https://github.com/thehogfather/flow-typed/blob/master/definitions/npm/reselect_v3.x.x/flow_v0.47.x-/reselect_v3.x.x.js) if you'd like to test it out.

**Comment by mattkauffman23** [comment]
@thehogfather just a single data point, but I had a number of issues with our selectors when upgrading to flow v0.55 using the official flow-typed lib defs. I replaced them with yours and was able to get flow to pass! Thank you!

**Comment by thehogfather** [comment]
@mattkauffman23 thanks for the feedback - i'll work on writing some tests and do a PR upstream.

**Comment by julienw** [comment]
This week is especially crazy for me so I'm focussing on the main things; I'll look at your PR next week !

**Comment by julienw** [comment]
From https://twitter.com/calebmer/status/915669304267350016, looks like it's good enough to add a `-` on the Selector's type.

**Comment by julienw** [comment]
@thehogfather have you moved your work elsewhere ?

I'll try to apply what @calebmer suggested.

**Comment by julienw** [comment]
[Here is another issue I have starting from v0.54](https://flow.org/try/#0C4TwDgpgBAyhA2EDGwD2AnAPAWgCo2AENgIAaKXABXVTAGdzcAlCOgV3mAD4oBeKAN4AoKKKgAKOkRIAuCgWJkoYGvTlVVDKADpd6VsDmEAdiADaAXQCU6lu04BuIQF8nQ0JFgJkadAGF9Ygw+QREoTHxpJQ1aLWZWDmBGAEZGACZGAGYucTDROm8UDGS5OEQirEjFRmpYlK5SPKgC8t800sLfCIUSGs10hqaWnwxMjtaMbqi+uopsxrEofXtgADE2YyQ5XMXRQnQAcxKKVKa9w-aKDLOofYOxuaarPh54lbCbLwnKnuja+kYdkSXDcoim1Qo-ziQM4KQGOzEwwqxzKIx+00h-ROg0WSLa4zR4N6mNmuDSOLEy0S6022xud2OuFOu1uF3UaSeLwoMOAHwJFSJfyxb2BoPCVWJMQB3ISsOxCPynWK-K6EqFpOSFNEVM4NK2Enph0ZyU5vFePL5X0Japm0pFnBBLjcHmgvxCAigADNUKgjKYoK4hEJPRsUABLVDGKAkKTiJCBEioioqjABCBBdDPYSiEObYARqM6tah8QAfTA+0IAFtjlJ0GHjAdyOXK1XLsY2FWAEYQTNyDvd3uhRb6YBsdBRgAsaScomcQdESEjUmaYarYEQSd8ITLUkUpSinzrDYOXIA5N7UGexUvjCul+vUBsACZb4L8ePpxNK9CSNcbiA33QchxGeM0oGnKxZygW8V1zfU3XAgce3QEJP0UICFVXddNx-BYxAfMAn2MV88KaIs9Q+aDFjCWDgGaKID0Ud0vR9OQLx9M8A2guilllQwoGQod+HgyRDycechCAA), after applying the fix in https://github.com/flowtype/flow-typed/pull/1329.

Error is:
```
    44:   const func: State => number = createSelector(
                      ^ undefined (too few arguments, expected default/rest parameters). This type is incompatible with the expected param type of
    37:   function resultFunc(_param1: string, _param2: number): number {
                                                        ^ number
```

This is a reduced testcase of what's happening with the latest reselect definition.
The error message makes no sense to me.

**Comment by julienw** [comment]
The error using master Flow makes more sense:
```
    37:   function resultFunc(_param1: string, _param2: number): number {
          ^ function. This type is incompatible with the expected param type of
    9:     selector3: Selector<TState, TProps, T3>,
                      ^ object type
        Callable property is incompatible:
            37:   function resultFunc(_param1: string, _param2: number): number {
                  ^ function. This type is incompatible with
            2:     (state: TState, props: TProps, ...rest: any[]): TResult;
                   ^ function type
                This parameter is incompatible:
                    44:   const func: State => number = createSelector(
                                      ^ undefined (too few arguments, expected default/rest parameters). This type is incompatible with
                    37:   function resultFunc(_param1: string, _param2: number): number {
                                                                        ^ number
```
I think this means Flow errors at the first possible selector creator even if the second possible selector creator works. I think reversing the order as said in a previous comment will fix it. Still investigating...

**Comment by julienw** [comment]
I have a PR at flow-typed in https://github.com/flowtype/flow-typed/pull/1406.
I still think Flow has a bug here, but at least we'll be able to work.

**Comment by thehogfather** [comment]
@julienw For your failing examples, the following type spec apparently works - without any need for rearranging the order of the selector types:
PS: how do you share the snippets from the `flowtype.org/try` url?
 
```js
type Selector<S, P, R> = (state: S, props: P, ...args: any[]) => R;

type OutputSelector<S, P, R, C> = Selector<S, P, R> & {
    resultFunc: C,
    recomputations: () => number,
    resetRecomputations: () => number
  };

type SelectorCreator = {
    /* one selector */
    <S, P, R1, T>(
      selector: Selector<S, P, R1>,
      combiner: (res: R1) => T
    ): OutputSelector<S, P, T, (res: R1) => T>,

    /* two selectors */
    <S, P, R1, R2, T>(
      selector1: Selector<S, P, R1>,
      selector2: Selector<S, P, R2>,
      combiner: (res1: R1, res2: R2) => T
    ): OutputSelector<S, P, T, (res1: R1, res2: R2) => T>,

    /* three selectors */
    <S, P, R1, R2, R3, T>(
      selector1: Selector<S, P, R1>,
      selector2: Selector<S, P, R2>,
      selector3: Selector<S, P, R3>,
      combiner: (res1: R1, res2: R2, res3: R3) => T
    ): OutputSelector<S, P, T, (res1: R1, res2: R2, res3: R3) => T>,

    /* four selectors */
    <S, P, R1, R2, R3, R4, T>(
      selector1: Selector<S, P, R1>,
      selector2: Selector<S, P, R2>,
      selector3: Selector<S, P, R3>,
      selector4: Selector<S, P, R4>,
      combiner: (res1: R1, res2: R2, res3: R3, res4: R4) => T
    ): OutputSelector<S, P, T, (res1: R1, res2: R2, res3: R3, res4: R4) => T>
  };
```

[Full spec here](https://github.com/thehogfather/flow-typed/blob/reselect-054%2B/definitions/npm/reselect_v3.x.x/flow_v0.47.x-/reselect_v3.x.x.js)

**Comment by julienw** [comment]
> @julienw For your failing examples, the following type spec apparently works - without any need for rearranging the order of the selector types:

Well, you rearranged the order in your example :) They're in the order: 1 selector, then 2 selectors, then 3 selectors, etc, while in the existing libdef it was the other way around.

Anyway, the PR landed !

>  PS: how do you share the snippets from the flowtype.org/try url?

I just copy/paste the full URL :) the full code is encoded as hash.

**Comment by thehogfather** [comment]
> I just copy/paste the full URL :) the full code is encoded as hash.

Awesome! thanks for that tip. I apparently hadn't noticed the url hash was changing all this while.

Perhaps I misunderstood the errors you were demonstrating though. The actual order of the selector types in my type definition is not why that example typechecks . See [here](https://flow.org/try/#0C4TwDgpgBAyhA2EDGwD2AnAPDANFACngEoB8UAvFABQDOwAhsBAFyx5jqpg2uFQB0g+ugDmPKPQB2IANoBdAJQUyRANwAodaEhQA8gFdgYQ3EQoM2PHyJ4AwmUqnkaLLgLEyAMigBvdVACodAgafXhgADF9SSRWWxx-QOCkVABbYwZgAEtUSXEqJXIySX1UgCMIdATAoJCIYCJkNIzGHLzWAuUoEvLKxIBfDS1waCdzdFtgxgwKX0SAgHoAKihgAAtg6BoEZwwaKCWF+ahLdygiAEZiACZiAGY8ABUSKmOA7bMXC9Yxl1PrC4kao1KAfXboa4-Hbjf43IFvUHQlx3KGfCxuax3eEgqApcpZSSVDrBGjfc5XWo0SHnW6UlHnO6FMiPY4KVgGIwmJHoqxPPBUElky54EnUoi0kn0oiMrrPYEBY7LVYAd1QiLR6H2h2OsPJNyeLwRYPGZN+PLOl2xIONLmpZtcvJpVpqeLKBKJ1EFrGFlLF1yZUBZNTZekMGXtuse-K9et93v9sudgUVK1yW256AORxqup9z1eOJtGFR4NzgPlgVd7vQxJC3ouAaDgRDHPDGcj0br5MbJE0AUGmmGOhgmWglB8UAAZqhUKwpCAoAP1JPoig2qsQsAqEgpkx7SXxpMINN0Eo-AEVzFsrlKWFIquqAB9MDCeipMl0dAEkR4Z+v1LUj0FSnqwQGVHMNTBMA+joJIUAACzXBo-Z9riuR0KCWTpIg9qzE+dCMCwsCjiGn7fl0ADk06oBRQwBCkeTAGh6SoNEAAmuGUDux57hmtBYWAOEZvyAaIQoyFoYxU6rj8o5dGBmZcbuED2gWgQ0AJQkahWeJgKxkgccJxwkneUQxIk4kIokDEYQRTCyYRswTtRrBUTOFGLhJNlMSZ4SgaUwGzJeSC0CRGj9EAA) for the reverse order. I think the distinguishing difference is in the Function type in OutputSelector Parametric argument - but a huge portion of flow is still a black box to me and as you said, the PR landed ;).

**Comment by julienw** [comment]
[Here is another example in the same vein](https://flow.org/try/#0C4TwDgpgBAyhA2EDGwD2AnAPAFRsAhsBADRTYAK6qYAzqdgEoQ0Cu8wAfFALxQDeAKCjCoAChoEiALjJ5CJKGCq0ZFZXSgA6bembAZ+AHYgA2gF0AlKqat2AbgEBfBwNCRYCZGnQBhXYQwefiEoHDkiekpqDUZmNmB6AEYOURDhGk8UDESZOEQsrFxJBTVopI5iNKhdW2AAMRZDJBlUkRF8dABzHLJEqoseLljakKsPfO8w4sj1eht4jgdhEKn5GbKyefYk+gAmFKqMiezczMmitbIo2nLKtqOvDF3T48LwkuuY-buRGviGpotKrCDrdVSJH5tUHPMi7fqDTZxdijF6PN7TK6zRG1RYCFYXCKYjbDeI7WH0ADMB3uZxO4zRq0JpRuvQqh1p6BheQZBI+WOw33ZrwpqIKjL5xKpkOqSPqjWaYmBUFBPWwEKV0NUu2lIK6IrIFPh3CGW2AKPpYt56xZJPYuOceLc0HeQUEwgAHjJDCwALYAIwg6B+IC9voD6CcLgAZvLgABLVCGKBECSiJD+Ijcgqi7x+CABdADN1QJCJiQy2oApBBURgDr4H09CToOOGTqkOvoBsw73+wNjXvhhEAFl2SxLZeAUBocZ9YEQWe8NYk8lyxTGzdbnQRACIo6hUDvx6XDOXS3PUI0ACaLwK8dP5zMc8Sz+cQW9BsQDY1QUcWY+TlAMaArAxQIoOgZBA+8gfq0IgznOC4ctK55gJehg3shVR-OwVajC4wgnuWOH6FAEHoEEwFIKIfBQJ6v7alAIYMVAjj-k4eJAA).

I know this is fixed by simply adding a `-` for `TState` in the `Selector` definition. But I'd like to point out what the error is for the member that should work:
```
13:   <TState, TProps, TResult, T1, T2>(
      ^ polymorphic type: function typeError:
41:   const simpleSelector = (state: State): string => "foo";
                             ^ function. This type is incompatible with the expected param type of
14:     selector1: Selector<TState, TProps, T1>,
                   ^ object type

    Callable property is incompatible:
        41:   const simpleSelector = (state: State): string => "foo";
                                     ^ function. This type is incompatible with
        2:     (state: TState, props: TProps, ...rest: any[]): TResult;
               ^ function type
            This parameter is incompatible:
                41:   const simpleSelector = (state: State): string => "foo";
                                                             ^ string. This type is incompatible with
                41:   const simpleSelector = (state: State): string => "foo";
                                                     ^ object type
```
Indeed I don't understand the error: why Flow does try to match `simpleSelector`'s return value's type with its argument's ? And why adding a variant for `TState` fixes it? Can someone explain this a little more?
Thanks!

**Comment by Mathspy** [comment]
I believe this issue was mostly about reselect's libdefs and there's nothing actionable for the Flow team themselves. If this is still relevant somehow it should be reopened on [FlowTyped](https://github.com/flow-typed/flow-typed) not here

@goodmind
