### ISSUE TITLE
Support optional fields for interfaces

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#496]
```
interface O { x?: number }
var o1: O = {} // ok
var o2: O = { x: 1 } // ok
var o3: O = { x: "" } // error string ~> number
```

I spent a bit of time trying to implement this by modifying `Type_inference_js.convert` to wrap interface fields types in an `OptionalT` when optional=true.

I got a stuck trying to make the above test cases pass. I determined that `Flow_js.structural_subtype` needed to create non-strict `LookupT`s for optional fields, which works in one direction, but some flow was forcing unification. I suspect it is the `ClassT ~> TypeT` flow.

(Edit: I had some extra commentary here connecting this issue to generators, but ultimately I think that I was mistaken that the issues I had there were connected to this. The above failing case does still apply, though.)

**Comment by gabelevi** [comment]
This threw me off too until I spoke to @avikchaudhuri. There's a covariance issue here. Consider this code:

```JavaScript
interface IHaveNullableX { x: ?number };
var myThing: { x: number };
(myThing: IHaveNullableX).x = null; // Uh oh I've put null somewhere bad
myThing.x++; // And now I can do bad things with null
```

It is true that `number` is a subtype of `?number`, so why isn't it safe to use subtyping on individual properties when doing structural subtyping? The answer is that object properties are not *covariant*. You can both read and write to them, so they are *invariant*. When doing structural subtyping of two objects, you need to unify the types of the properties in case people both read and write to the properties.

**Comment by samwgoldman** [comment]
Thanks for the explanation. It makes sense to me that object properties must be invariant because of mutation.

It also makes sense that optional types are *mostly* equivalent to maybe types.

```
type Optional = { x?: number }
var o1: Optional = {} // OK
var o2: Optional = { x: null } // Error: null ~> void | number
var o3: Optional = { x: undefined } // OK
var o3: Optional = { x: 0 } // OK

type Maybe = { x: ?number }
var m1: Maybe = {} // Error: x not found
var m2: Maybe = { x: null } // OK
var m3: Maybe = { x: undefined } // OK
var m3: Maybe = { x: 0 } // OK
```

I guess what I'm wondering here is: why are interfaces different from other object types? Surely the same invariance constraint applies to both.

```
interface IOptional { x?: number }
var o1: IOptional = {} // Error: x not found
var o2: IOptional = { x: null } // Error: null ~> number
var o3: IOptional = { x: undefined } // Errors: number ~> undefined; undefined ~> number
var o3: IOptional = { x: 0 } // OK

interface IMaybe { x: ?number }
var m1: IMaybe = {} // Error: x not found
var m2: IMaybe = { x: null } // OK
var m3: IMaybe = { x: undefined } // Errors: null ~> undefined; number ~> undefined
var m3: IMaybe = { x: 0 } // Errors: null ~> number; undefined ~> number
```

Yes, unification is partly responsible for the different. Object types have a special case that uses subtyping instead of unification [when it is safe to do so](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L1861). Interfaces don't have that.

I also think there is another issue. Why is the error for `var o1: IOptional = {}` complain about `x` missing when the property is marked optional? It seems that the `optional` field on the AST is [currently ignored](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L2032), whereas object types [wrap their optional properties](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L826).

So, two issues that are actually related. It doesn't help to use `OptionalT` for interfaces without the ability to also allow subtyping in the scenarios where it is safe to do so.

Whatever we do decide to do about this, it's problematic to me that optional parameters for interface declarations are noops, and fully equivalent to the non-optional form. It's unintuitive. At a minimum, we should error on that syntax if we can't support optional properties. They are even used in the [standard flowlib](https://github.com/facebook/flow/blob/master/lib/core.js#L292), as noops.

**Comment by avikchaudhuri** [comment]
@samwgoldman you're absolutely write about the last two points: 
(1) Optional fields shouldn't be ignored in interface / class declarations (easily fixed by wrapping with OptionalT, as you said). 
(2) Objects should match interface types with property subtyping where it can. I have a couple of diffs coming up that fix some issues with interfaces and structural subtyping of objects with them.

**Comment by avikchaudhuri** [comment]
Related to #514

**Comment by samwgoldman** [comment]
Related to #301

**Comment by samwgoldman** [comment]
@gabelevi fixed this one moments ago!
