### ISSUE TITLE
End_of_file / Invalid argument error and crash (reproducible)

### ISSUE THREAD

**Issue by mjomble** [facebook/flow#4960]
I use Flow and [Mercurial](https://www.mercurial-scm.org/) together on a project and found some issues with this combination, at least on my Windows 7 PC.

Whenever I use Mercurial to commit or revert a file monitored by Flow, it crashes the Flow server.
If I commit using [TortoiseHg](https://tortoisehg.bitbucket.io/), I get `Unhandled exception: Sys_error("Invalid argument")`.
If I commit using `hg` from the command line or revert using either tool, I get `Unhandled exception: End_of_file`.

It seems to be caused by specific file system operations which might also occur with software other than Mercurial. Perhaps #2268 has a similar cause.

I've also noticed that [Atom](https://atom.io/) has similar issues with Mercurial. If, for example, I have `test.js` open in Atom and revert its changes from TortoiseHg, the Atom tab changes to something like `test.js-bc906b5e` which hints that the file may have been temporarily moved/renamed and then replaced with a new one, perhaps as a workaround for file locking issues on Windows.

I can provide more specific details and steps if anyone's having problems reproducing the issue.

**Comment by mjomble** [comment]
Since the changelog for 0.58.0 mentioned "Gracefully handle crashes of the file watcher", I tested this again.

The error is now `dfind died (got exception: End_of_file)`

**Comment by mjomble** [comment]
In 0.60.1 it looks like this:

```
Dec  6 10:25:39.857 [error] Closing connection 'server #1' due to uncaught exception in read loop: Unix.Unix_error(Unix.EPIPE, "read", "")

Dec  6 10:25:40.325 [error] Flow server (pid 200) exited with code Dfind_died (99)
Dec  6 10:25:40.325 [info] Creating a new Flow server
Dec  6 10:26:19.766 [error] Closing connection 'server #2' due to uncaught exception in read loop: Unix.Unix_error(Unix.EPIPE, "read", "")

Dec  6 10:26:19.912 [error] Flow server (pid 292) exited with code Unknown_error (110)
Dec  6 10:26:19.912 [info] Monitor is exiting (Dying along with server)
Dec  6 10:26:19.913 [info] Broadcasting to threads and waiting 1 second for them to exit
```

It's now recovering from some errors by restarting the server automatically, but eventually still dies.

**Comment by mjomble** [comment]
Today I discovered that editing files via the Windows version of BeyondCompare also crashes the Flow server (0.61) with output similar to the previous comment.
Whereas edits from many other applications (for example Atom and Notepad2) don't.

**Comment by lll000111** [comment]
Flow 0.69, Windows 10

```
Mar 29 10:14:46.879 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Mar 29 10:14:46.879 [error] backtrace:
Mar 29 10:14:46.879 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Mar 29 10:14:46.879 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 501, characters 13-24
Mar 29 10:14:46.879 [error] Re-raised at file ".\src\monitor\connections\flowServerMonitorConnection.ml", line 152, characters 6-230
Mar 29 10:14:46.879 [error] 
```

**Comment by mroch** [comment]
we've fixed a lot of Windows issues this year and use Mercurial exclusively at Meta, so I'm hopeful this is resolved. I'm going to close this, please file new issues for anything that still crops up on recent versions (e.g. v0.185+). thanks!
