### ISSUE TITLE
$ElementType unexpected behaviour with object with more than one element

### ISSUE THREAD

**Issue by madjam002** [facebook/flow#4962]
When using `$ElementType` with an object with more than one element on a returned function inside a function with the generic, there is unexpected behaviour.

Example:
```js
const obj = {
  string: "test",
  number: 5,
}

type KeyType = $Keys<typeof obj>;

function selectValue<Key: KeyType>(key: Key) {
  return (callback: (value: $ElementType<typeof obj, Key>) => void) => {
    callback(obj[key])
  }
}

selectValue('number')(value => { const test: number = value }) // error
selectValue('string')(value => { const test: string = value }) // error
```

Flow try link to reproduce:
https://flow.org/try/#0MYewdgzgLgBCBGArGBeGBvAUDG0BOAlmAOYBcMARFAKbQUA02MYArgLbzV7kCsjAvpkxQAngAdqMANLURAFXGS0AEhkiIAHlESQAMzhIAfAG4hulmGBQC4XNQA21KwDUAhvZbUNa8moUTDAAoAa1lfWQBKDCY8aigWPDAYQOB3e3hXYGDyQIA3d09yZQBRRzZqMCh-L21qPQNEemlZQyiUQxhckAIAEzaOrBwcVPt0zODAhEQAbVCRAF0IpkFBTAgHJyg3D2pAgHJWDi49iLyCpQGYUEhYGmhyQ848VE7zmH4l9ccXc-38ImIJzOO1Ql2u0Bgdyg5H+JBe+RBH0wQA

Expected behaviour: no errors in the link above.

If you comment out the second element in the object, everything works as expected:
https://flow.org/try/#0MYewdgzgLgBCBGArGBeGBvAUDG0BOAlmAOYBcMARFAKbQUA02MA9M2AK4C281e5ArIwC+mTFACeAB2owA0tXEAVKTLQASeeIgAeCdJAAzOEgB8AblEH2YYFALhc1ADbVbANQCGT9tW2bymsrSJgAUANYKAQoAlBhMeNRQ7HhgMCHAXk7wHsBh5CEAbl4+5GoAoi6c1GBQQb561IbGiPRyCiaxKCYwBSAEACad3Vg4OBlOWTlhIQiIANoR4gC60UwiIpisEM6uUJ7e1CEA5BzcvEfRhcWqwzCgkLA00OSnPHioPdcwQqvbLu7XY74IjEC5XA6oW73aAwJ5QcjAkgfIoQn6YIA

**Comment by madjam002** [comment]
This could be related to #4211 but I'm not sure to be honest!

**Comment by masad-frost** [comment]
Here's a similar error (comments inside)
https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwFBSlQEMBbCALikWHgEtUBzAGnyiIYsIFcSAjBFgF8A3LlwAzLqgDGwWmigdgAHgDSlACSqIIRMrhI0APiMAKANY7KqplABuRADZdOGgKKOIZVMAAq4CH0EFFRbVSMASkoDEJxcAEhpNGooMGjghSw8AhzCUk4AcgB3ImACllyCdk4ARgAmCsqAbUsQAF1KB2cIWwB6Xqh6JPh4CFkoBHhkeFt3T28-AKDDUKhwwcQofnoGKBoIUogAEyhHWksoDQA1Jxc9GOMAOlYCQTF40eAueHQwUTfcP0oL4ABa0TbSEFjcxQIrTcyIXBKUwFYhkcpQArUOiMAoRKBA1DICYjaZQUzDUayCJIiDAFFoiAYmr4oGTMkU6ZU4ARIA

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
