### ISSUE TITLE
Transforming properties to covariant with $ObjMap

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#4963]
Is there a way to transform properties of an object type to covariant properties with $ObjMap?

Similarly to how you can use [typescript's mapped type](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#mapped-types) to define Readonly<T> type:
```js
type Readonly<T> = {
    readonly [P in keyof T]: T[P];
};
```

**Comment by vkurchatkin** [comment]
No, it's not possible for `$ObjMap`, it only works on types.
