### ISSUE TITLE
Flow covariance error

### ISSUE THREAD

**Issue by jajcek** [facebook/flow#4964]
It is the case written here https://github.com/facebook/flow/issues/3076. But I would to ask why we have to type this way:

```
class C {
  constructor() {
    this.method = this.method.bind(this);
  }
  method: () => void;
  method() {}
}
```

instead of writing just like this?

```
class C {
  constructor() {
    this.method = this.method.bind(this);
  }
  method(): void {}
}
```

Does the flow just not implement such feature or it can't do it this way because there is something nasty in JS which blocks flow to do it?

**Comment by vkurchatkin** [comment]
Methods are covariant by default to allow structural subtyping. For example, this works:

```js
class C {
  method(): number | string {
  	return 1;
  }
}

class B extends C {
	method(): number {
      return 1;
    }
}
```

If you make `method` invariant with the trick above, you are not going to be able to do that.
