### ISSUE TITLE
Is there a shorthand syntax to create an object with literal string types for the values?

### ISSUE THREAD

**Issue by ndbroadbent** [facebook/flow#4965]
I'm defining some constants in my app, like this:

```
export const STRING_CONDITION_TYPES: {|
  EQUALS: 'equals',
  CONTAINS: 'contains',
  STARTS_WITH: 'starts_with',
  ENDS_WITH: 'ends_with',
|} = {
  EQUALS: 'equals',
  CONTAINS: 'contains',
  STARTS_WITH: 'starts_with',
  ENDS_WITH: 'ends_with',
}
export type StringConditionType = $Values<typeof STRING_CONDITION_TYPES>
```

This is not DRY at all. Is there a shorter way of defining the `STRING_CONDITION_TYPES` object? I.e. Can I tell Flow to infer that all values are literal strings, instead of a generic `string` type?

If it's not possible in native Flow, would it possible to build a generic helper function using some utility types?

**Comment by ndbroadbent** [comment]
I feel like I'm making some progress... I've figured out how to get Flow to mark a variable as a string literal:

```js
function getLiteralValue<Key: string, Obj: Object>(obj: Obj, key: Key): $ElementType<Obj, Key> {
  return obj[key]
}
const val = getLiteralValue(STRING_CONDITION_TYPES, 'EQUALS')
```

Flow now knows that `val` can only be the type `'equals'`, instead of `string`.

```
[Flow]
val: 'equals'
```

Now how can I iterate over the keys in my object, and produce an object with the type:

```
{|
  EQUALS: 'equals',
  CONTAINS: 'contains',
  STARTS_WITH: 'starts_with',
  ENDS_WITH: 'ends_with',
|}
```

(i.e. literal string values, instead of the generic `string`.)

**Comment by ndbroadbent** [comment]
I really want to request a new Existential operator to infer literal types.

Right now you can write: `const CONDITION_TYPE_EQUALS = 'equals'` or `const CONDITION_TYPE_EQUALS: * = 'equals'`, and Flow will infer the type as `string`. I need an operator so that the type is infered as `'equals'`. It would be great if I could write something like the following:

```js
// Double asterisk
const CONDITION_TYPE_EQUALS: ** = 'equals'

// Or maybe a utility type:
const CONDITION_TYPE_EQUALS: $StringLiteral<*> = 'equals'
```

Also it would be really great if I could put the Existential operator inside `$Exact`, so that it automatically infers an exact object type. Then I could write something like:

```
export const STRING_CONDITION_TYPES: $Exact<$StringLiteral<*>> = {
  EQUALS: 'equals',
  CONTAINS: 'contains',
  STARTS_WITH: 'starts_with',
  ENDS_WITH: 'ends_with',
}
```

**Comment by josepot** [comment]
@ndbroadbent check this out, 

```js
function objToKeyLiteralsDict<O: {}>(o: O): $ObjMap<O, <V>(V) => $Keys<O>> {
  return Object.keys(o).reduce((acc, k) => Object.assign(acc, { [k]: k }), {});
}

const STRING_CONDITION_TYPES = objToKeyLiteralsDict({
  EQUALS: 'whatever',
  CONTAINS: 'doesn\'t',
  STARTS_WITH: 'matter',
  ENDS_WITH: ''
});

(STRING_CONDITION_TYPES.EQUALS: 'EQUALS'); // Works
(STRING_CONDITION_TYPES.CONTAINS: 'CONTAINS)'; // Works
(STRING_CONDITION_TYPES.STARTS_WITH: 'STARTS_WITH'); // Works
(STRING_CONDITION_TYPES.ENDS_WITH: 'ENDS_WITH'); // Works

STRING_CONDITION_TYPES.EQUALS = 'EQLS'; // Error
STRING_CONDITION_TYPES.EQLS = 'EQLS'; // Error
```

**Comment by joeybaker** [comment]
@ndbroadbent did you every come up with a solution to this aside from your feature proposal?

I played with [flow.org/try a bunch](https://flow.org/try/#0PTAEBcE8AcFNQDIEtywE4EMA2SBe8BeUAHgHkAuUAEgGUBXAIyjmIG8BtAa1kkoGdwaJADsA5gF1KwugFsG6UAB9QAoWIC+APk0AKAPYMAVpVIBKUAU3VSRgLIZoSMgBoSAaV1vzl6gFEssDKwwuAAKjCwLqAemgDcAFAgEBGIKOjYeIQkFNT0TBFsXDz8giISUrLyaEoqpRra+kYm3lZUNob20FHEAGq6PS2gfQlJzPDIqJg4+BbuxbVqoq7tJkawAMbgugbGoO2u3LzRPINU-oHBYQX7x5Ca8WND2HSwoXoT6VizUX06Axatc5BELhFikVx9B4pD5TTLfHLtDZbRq7MwA6x2Bw-Z6vd5pKZxeLxUAk0kk+LrPTCASgHCTDL4SgwhlZHbonYJClUmkARzoGSgAGE9Oh1rAACaUViKYmgACqADk3ArSAB1BWUADkdGEnGEegA7sJNc5ZQAhACCABEtQwMOKTbKLT1fAAlC0AcV8WowADd0qJYI6SQAxACSCu9oE1ADMREH4op1LM6Z9MjpWLLFcq1Rrozq9YbjaaSZabdG7Q6S6BnW7PVHNX6A0Hq+HI1q48IW-F1KYEmSB6AudTwKA+QLIAq9KhQgALV4RAASGD4PRxfAtfF8MmgUBT+JZGazSpV6q1Bf1RuDoDLtvt19r7q9Pv9mED17bDc73d7-cHA6Jf8AKAsl4hjHVNiQKlQEDcBmSwNcsBeYg3HmVQymWJo9jWTZtiwm5DkoVDIFMSgzgCYErjBIxXGIqxMxJNBYHAOg0GEUAdiKSBxB7YcaVgiZ4TwwxBkRTYADpDj4FFTHEpjxToMUdH0OhwAOQYGJAskmJYtjQFYcTDL0VTXC4SQYOY+DEJeFF1OTWUtPUVxWF7IlKRHDihFEWZNOzU8821XVL2Lc1rTvKsnRdJ8GybN9u1DCMv3jR11D40dxzpSAAGZZgElB9C8vsgA) and couldn't get things to work. It seems like there's a bug with `$ElementType` and `$ObjMap`.

**Comment by goodmind** [comment]
`Object.freeze` should work
