### ISSUE TITLE
[0.55] Object.create(null) This type is incompatible with object type

### ISSUE THREAD

**Issue by danez** [facebook/flow#4967]
as of flow 0.55 the following code started throwing an error, although it looks valid to me:

```js
var x: {[key: string]: string} = Object.create(null);
```
https://flow.org/try/#0G4QwTgBAHgXBDeBtA1gUwJ5wM4BcwEsA7AcwF1s8jiBfCAXggHkAjAK1QGMcA6DsVEDlQAKQgFcANhICUAbiA

This breaks graphql currently and everything that uses it as dependency: 
https://github.com/graphql/graphql-js/issues/1045

**Comment by danez** [comment]
I guess it is because of 1861dcc833f78738e9aa53b2a0f6f7c8af8a58ab, but that is just a wild guess. @samwgoldman

**Comment by smokku** [comment]
Why is this issue closed?
I am observing this bug in `0.71.0`.

**Comment by TLadd** [comment]
If anyone else comes across this in the future, you can look at how graphql-js solved this issue: https://github.com/graphql/graphql-js/pull/1048

Basically,  
```
var x: { [key: string]: string, __proto__: null } = Object.create(null);
```
