### ISSUE TITLE
Best way to define a type that's the same as another type without 1 prop

### ISSUE THREAD

**Issue by MichaelDeBoey** [facebook/flow#4969]
So I was wondering what's the best way to define this:
```js
type A = {
  propA: string,
  propB: string,
  propC: string,
}

type B = {
  propA: string,
  propB: string,
}
```

Is there something I can do like this for instance (I know the following doesn't work):
```js
type A = {
  propA: string,
  propB: string,
  propC: string,
}

type B = A - {propC}
```

**Comment by vkurchatkin** [comment]
On master you can do it with `$Rest`:

```js
type A = {
  propA: string,
  propB: string,
  propC: string,
}

type B = {...$Rest<$Exact<A>, {| propC: any |}>};
```

**Comment by MichaelDeBoey** [comment]
This gives an error :/
I'm using `flow-bin@0.55.0` in my project btw

**Comment by TiddoLangerak** [comment]
`$Diff<A, { propC : any }>` works as well.

**Comment by TiddoLangerak** [comment]
`$Diff<A, { propC : any }>` works as well, also in v0.55.

**Comment by MichaelDeBoey** [comment]
@vkurchatkin & @TiddoLangerak Thanks for the help!
Will take a look at https://flow.org/en/docs/types/utilities 🙂
