### ISSUE TITLE
Is it possible for flow not to require param names in function type declarations?

### ISSUE THREAD

**Issue by ide** [facebook/flow#497]
Basically I want to write this:
```js
type Handler = (Error, Result) => void;
```
instead of this:
```js
type Handler = (error: Error, result: Result) => void;
```

Is there a conflict with the grammar that requires the param names?

**Comment by gabelevi** [comment]
It's not the grammar that's the problem, it's the typescript compatibility. In typescript function types, it's the param type that is optional, not the name.

```JavaScript
(string, number) => void // When you write this
(string: any, number: any) => void // It means this
```

We would much prefer to make the names optional instead, but were hesitant to add another situation where a typescript type means something completely different in Flow. So yeah, we're still undecided here :/

**Comment by ide** [comment]
Woah, that's kind of bizarre. You'd think a type declaration would focus on types but I guess they had their reasons. Maybe `@flow` and `@flow typescript` is the solution here but that seems complicated to maintain and explain to people...
