### ISSUE TITLE
Confused About Bounded Polymorphism Syntax

### ISSUE THREAD

**Issue by derek-duncan** [facebook/flow#4970]
While reading about _Bounded Polymorphism and Generics_, I've been trying to apply the concepts to my function types. [In the generic type docs](https://flow.org/en/docs/types/generics/#toc-function-types-with-generics), it indicates that Bounded Generics can be used with arrow function declarations.

> You can use generics in the same places you’d add any other type in a function type (parameter or return types).
> `<T>(param: T) => T`

However, while [testing this example in Try Flow](https://flow.org/try/#0C4TwDgpgBAKhDOwoF4oG8BQUoEsAmEAdsDqAFxQA8MAfABRgCGATowLYUwCUKNsANBgC+AbizYoGAGYBXQgGMSAe0JRgCdczpdOG9OOYRgM5qswTcBYqRAUGLdj2R8mrNoOxDhQA), I'm getting errors about `incompatible initiation of T`. Here's the code I'm testing.

```javascript
// Type
type Example = {
  identity: <T>(param: T) => T,
};
    
// Implementation
function example(): Example {
  return {
    identity: (param) => param,
  }
}
```

In `type Example`, `<T>` is declared directly before the arrow function type, but that's what produces the error. Alternatively, it could be declared directly after `type Example` to resolve the error.

```javascript
type Example<T> = {
  identity: (param: T) => T
};
```
However, the `<T>` generic is no longer using Bounded Polymorphism on the `identity` function, and it must be given a value whenever `Example<string>` is used. This defeats the purpose of the generic for my use cases. I'm trying to preserve the `<T>(param: T) => T` functionality in my original example and the docs.

What am I missing? Thanks!

**Comment by vkurchatkin** [comment]
Flow can't infer polymorphic functions, so you have to annotate them explicitly:

```js
type Test = {
  identity: <T>(param: T) => T,
};
    
function tester(): Test {
  return {
    identity: <T>(param:T):T => param,
  }
}
```

**Comment by derek-duncan** [comment]
Oh, that makes sense, thank you. So is there any way to create a Type Alias for a polymorphic function? I'm trying to create a function type that I can import/export across files without redeclaring the type signature each time.

```
// file1.js
export type IdentityFn = <T>(x: T) => T;
const identity: IdentityFn = (fn) => (...args) => fn(...args);

// file2.js
import type { IdentityFn } from './file1.js';
const makeUtils = (identity: IdentityFn) => ({
  identity: identity,
});
```

**Comment by vkurchatkin** [comment]
`type IdentityFn = <T>(x: T) => T;` is fine. The only thing to remember is that in order to assign a function to this type you have to make it polymorphic explicitly.
