### ISSUE TITLE
`length` property not found in React.ChildrenArray

### ISSUE THREAD

**Issue by Palisand** [facebook/flow#4971]
**0.54.0**

For the following code where I apply a margin to every child except the last:
```javascript
import * as React from "react";

type Props = {
  children: React.ChildrenArray<React.Element<any>>,
}

const Group = ({children}: Props) => {
  const items = React.Children.map(children, (child, i) => (
    React.cloneElement(
      child,
      i < children.length - 1 ? {
        style: {marginBottom: 10}
      } : {}
    )
  ))
}
```
I receive the following flow error in flowtry:
```
11:       i < children.length - 1 ? {
                       ^ property `length`. Property not found in
[LIB] static/v0.55.0/flowlib/react.js:157: declare type React$Element<+ElementType: React$ElementType> = {|                                                                                                         ^ object type
```

Why does flow report that a `ChildrenArray` has no `length` property?

[flowtry link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdMAnmFnAArFjoC8cA3nThxcAC2AAbACaUAdgC5MVGADoAwuOlyAglCjImAHmx5VAUQlYQWWTEPJZTAHxOANHQC+DXBFmp4AOLEAK5gcHwAFPxikjI2HoqcENwAlOFOAkIivv5wwDBWvEqm6ppxsiogyGARMVo2rnC1ZY3AaTwZEVnCJvgquBK+WBZWNjBdwpMiLd2TwHCG07FyKpayAOYwonAAtHAAjHAA-JlTU-5Mlor8VVDrwLIAQhAwMCSK+wAMXmdwHnDXH6TFJZFIgrxAA)

**Comment by apalm** [comment]
Why not use [Children.count](https://facebook.github.io/react/docs/react-api.html#react.children.count)? `children` is supposed to be opaque.

**Comment by jenskuhrjorgensen** [comment]
Thanks @apalm - using `React.Children.count(children)` worked for me :D
