### ISSUE TITLE
Incompatible props when typing HOCs that are connected to Redux

### ISSUE THREAD

**Issue by Palisand** [facebook/flow#4972]
**0.54.0**

In the following higher-order component, I am `connect`ing the `Wrapper` component before returning it so that I can create components that have the means to check if a value stored in redux matches the value specified during invocation.

```javascript
import React, {Component} from "react";
import {connect} form "react-redux";
import type {ComponentType} from "react";

function enhance<Props: {}>(
  WrappedComponent: ComponentType<{foo: string, checkFoo: () => boolean} & Props>,
  foo: string
): ComponentType<{foo: string} & Props}> {

  const mapStateToProps = state => ({
    foo: state.foo,
  });
    
  class Wrapper extends Component<{foo: string} & Props> {

    /**
     * Returns true if `foo` from redux store matches `foo` supplied to this hoc
     */
    checkFoo = (): boolean => (
      this.props.foo === foo
    );

    render() {
      return (
        <WrappedComponent 
          {...this.props} 
          foo={this.props.foo} 
          checkFoo={this.checkFoo} 
        />
      )
    }
  }

  return connect(mapStateToProps)(Wrapper);
}

enhance(SomeComponent, "bar");
```
`SomeComponent.checkFoo()` will return `true` if the value for `foo` in the redux store is `"bar"`.

This works fine but I get a flow error stating that the **props of React element `WrappedComponent` are incompatible with some incompatible instantiation of `Props` in `enhance`**.

I'm not exactly sure if Redux or a hoc within a hoc is the culprit here, but I don't know what else it could be.

**Comment by johnhaley81** [comment]
Try changing `{foo: string, checkFoo: () => boolean} & Props` to `$Supertype<{Props & foo: string, checkFoo: () => boolean}>`. Note that the order of the intersection matters (although that is IMO a bug and it shouldn't). Related issue: https://github.com/facebook/flow/issues/4178

There's a lot of issues around spread and union types right now. I think this is related to https://github.com/facebook/flow/issues/1735

**Comment by Palisand** [comment]
@johnhaley81 `$Supertype<Props & {...}>` seems to have done the trick. What is this exactly? The docs just state ["Work in progress"]($Supertype<{Props & foo: string, checkFoo: () => boolean}>).

**Comment by johnhaley81** [comment]
So that got me thinking and I jumped over to an equivalent example I have and turns out `$Supertype` isn't needed at all. When I went over to flowtype.org/try I couldn't get any errors with it so I think the implementation of `$Supertype` might be wrong in flow. /shrug

Take it off and see if just switching the order fixes it for you.

**Comment by Palisand** [comment]
After seeing "/shrug", that got _me_ wondering if github has a shrug emoji, and wouldn't you know it: :man_shrugging:. Anyway, removing `$SuperType` and changing the order results in the same error I stated above. It's interesting that it's the same error even though the order is changed even though the flow docs [state the proper intersection order is `InjectedProps & Props`](https://flow.org/en/docs/react/hoc/#toc-injecting-props-with-a-higher-order-component). Reopening...

**Comment by johnhaley81** [comment]
Does [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3qAMKyawB2RLVouAnhkQ0yxsOAFV78AvqEjYmoAOTZSFeQG5kIUAFoduraABCRAOYoWoJdCIA3Eh1AADJQBMArgA8HoO88dLyuFouHl7ORGTQJNgkuCisAM7aejrIYRFR-Dx8oAAiKPEYMWQAFgCCAAoAkgA8pQB8oAC8oAAUAXEsAFygpQCUTQ2l6mmRSlziufmFuCW13XRZRN0AJADKrgBGi9XxuNhmxg0SDc15BUVlVbV16ogjGePZALIozs5W8BkVNavUpdQ5JqTc4zYrXE60RCgUDOKYXbo5dTQ4xEXCrXAxIgtXrdVbqCS3e5jRagdE4IjVX49AFAs7TWb1CE0KEwuGghFI0AotEY3BYnGk-GE8KjTITJ4kDDozEiWDlWQYeKU6gAeXK3RVGwAVuFOKt1aBNTqKBCWizdpjcZQWQgWPLYIqNeVEP1Gg0Wi0LXyraBbfbHYbyq6Gvr+gAfUnlYXpYniyV0i6y-1K-6BjXa3UAg1G3UnFkRj2wkElBFshl1ah+hXxJ3B3JB-P16Oix78J5EbAo5OU8pZ9PGzhq-uZ0DZjMmoFm6FeojJ3G9llF+nFOf163QqsOmuBl0DUfNh4kxgcIjufDNOi7cm43Dk6oAKmo96OB7G6XiiWPbAoRGcjGYwi4NUarUOUDSnnyLDOIkxABMs-5COwQFqg0zLTryKBkKAADq0QYHwf6CKwSHdPQkQftUsEUPBRGAdUYEViy3K4ZKBGVCwFosGQ-LdFRuA0QBSH0Yx0IYNWTrrqAM7dNYsCvIgEipCKh4TF+uq-ghxEcGRJAUSBo4QjpFEsmpP6EYJHDAb2BmIDcSkxmK2Smbe2BWaBposmQtEkYQyj8ZpgFiHwwm7m6AgsN+fLmYh2nkUq+lga+-Dvok9rWK8HbKj04Fnuw0G+XBAVCWhUkuUspJlVl9SSSUKDQM4SgsAA-N0djcApqGKXcyljJArhcbErCgGQ-h8mlGXYFOpXkgA0kQ3AtaV+wsMYknxJsc0Ld0uzLcYLrdONYSuY+oDPklrbhZFKoYINHFAiVGCuEoi0bLAsBWHYknwCguDFMQkAvW9H0sAp50kgAcq40DQECLBQzDEaya8519QNHTDawkW1KqYFTQAdATSi7N0pTYNE3DVEjzgNJo1TNPAOAANZRLA-W+JAOCgMUuC4I6ICmL9mx415aDAJA5BEK9sCM2LcDwMA+TrUQ8TAAATAAzAAbAADPtl26jgbmgGsrh8Hg4jVHQS7wsCy7XKAUgAGSBnUdndQ50j9RQ6NeRFupVTj1D6nUU1oJK0p8km4mgBKUq8kQUdbll+nB5JYcYAmoKJwGkPQ2nHZdtHufQJJDq3fEi3Odd5d685hv6SbZvbPqoDO1bZbFKWxZgvUDuty7dnQkPw8j6PY9j4gmjJDooAAKJQTCPUxB0iTT1oyAkhH-AXiyADUHOwNtewHNaBLIKj3tDewxR2Nx9HRzQB9H7txxTSx+Ead5HCkV-uBBRSNASjhEZgAMTet0bEe4pbAydqOasIlpDgKWgcWuv9-73y3KhZA0Jfa7FAOnLe2dEjNE9PHG8mI6wtBKtCJ+pVMR4wPpJCQvROTQk8nFHCeEzagAgnlT8v8MGKiwSyaEwB7z3hEdCe8vlcBPTunsVw-AUCQEcAfLwMg5DBHcNNMYYdQTK1UW9Lw618LQBQL+LgsAuDFHyFzWAZBJGnWAJIoBZBQFvUnAKaBpBzBhSmsPX6+Q8ZiS3AwjxjQImINgJIlh2Ch6NSOpA6h8TURyNaI4oe1R34ESKvYDJw8aAEzxoE+IwTqxSHyUPA+jQaAlLKaEg+FTx44OKMAsBsAal1Nce42ATSx7ADqBk3okjFLQi6tCJQsjsDmF9pFFoBD45EN6C0bJHZYkSCAA) work for you?

**Comment by Palisand** [comment]
That reports no errors, but you are using `$Supertype` on `connect`.

**Comment by johnhaley81** [comment]
I copypasta'ed that stuff from: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/react-redux_v5.x.x/flow_v0.53.x-/react-redux_v5.x.x.js

**Comment by azangru** [comment]
@Palisand Have you checked whether Flow correctly checks props of your enhanced component?

I was having a similar issue trying to write an enhancer that would inject certain props from the redux store into the component, and followed @johnhaley81's suggestion with $Supertype. Flow stopped complaining about the enhancer, but what I am now observing is that I can pass incorrect props to my enhanced component, and Flow will not catch it. It is super annoying.

_(Using v. 0.54 as well)_

**Comment by villesau** [comment]
React-redux libdefs have been rewritten since posting the issue so I assume this is no longer a problem.
