### ISSUE TITLE
Redux - Flow issue: Property not found in action (object type)

### ISSUE THREAD

**Issue by erica93k** [facebook/flow#4976]
```
// actions.js
export type ActionA = { type: 'A', a: number };
export type AcrtionB = { type: 'B', b: string };

// reducers.js
type ActionAB = ActionA | ActionB;

export function AB(state: ?string = null, action: ActionAB) {
  switch (action.type) {
    case 'A':
      return `${action.a}`; // ERROR: a (property `a`) Property not found in action (object type)
    case 'B':
      return action.b; // ERROR: b (property `b`) Property not found in action (object type)
    default:
      return state;
  }
}
```

I also tried like this: 
```
export function AB(state: ?string = null, action_: ActionAB) {
  const action = action_;
  switch (action.type) {
    case 'A':
      return `${action.a}`; 
    case 'B':
      return action.b; 
    default:
      return state;
  }
}
```

and like this:

```
export function AB(state: ?string = null, action: ActionAB) {
  const a = action.a;
  const b = action.b
  switch (action.type) {
    case 'A':
      return `${a}`; 
    case 'B':
      return b; 
    default:
      return state;
  }
}
```

And also tried adding this to `.flowconfig`: 
```
[options]
experimental.const_params=true
```

All the above result in the same error.

**Comment by julienw** [comment]
[This works for me](https://flow.org/try/#0PTAEEMGMBcEsHsB2BnAdAK2QKAKYA8AHeAJ2lGgE8CdQBBGBRW0AXlAG9yqcAuUAclr8ANBD6IArgFsARjmKgAvgG5chEmUrU6DJACFWHLtT789I0DL7JoxWIgDmS1VhChiOACYTI8tJiwtGno4JFoDNhDGZgAfHVDEPRd8IlJQADMJRF1EOj0AChtwaF5QAH4bO0dDSQAbWtEoBL4osL0ASg4sUFBkAHdYaEgAC1B8psZUIM72bp7QSHBkGkF+Hjn59xxoCWJcgAMAEnYJpFRwRX3lUDcAUQAle4B5e75wMYJieGpSClB98D7ToABS+P0ooEQ8DI6XgWU8oHsEByY3gMnQOBgxhw7Q2CyWK3M602PQ8Oz2yISqBk1zujxefBkHzB8gh+xkQNAoO+rL+UJhcMQCKRp1y+TRGKx0zxnhw6XAElq0GJJLJu1yRRKqh6iiwiiAA)

**Comment by erica93k** [comment]
@julienw I don't know if it matters, but I use constants as action types:

```
const A = 'A';
const B = 'B';

type ActionA = { type: A, a: number };
type ActionB = { type: B, b: string };

// reducers.js
type ActionAB = ActionA | ActionB;

export function AB(state: ?string = null, action: ActionAB) {
  switch (action.type) {
    case A:
      return `${action.a}`; // ERROR: a (property `a`) Property not found in action (object type)
    case B:
      return action.b; // ERROR: b (property `b`) Property not found in action (object type)
    default:
      return state;
  }
}
```

But this raises some other errors on *Try Flow*

**Comment by jcready** [comment]
You need to use `typeof` in your annoations:

```js
const A = 'A';
const B = 'B';

type ActionA = { type: typeof A, a: number };
type ActionB = { type: typeof B, b: string };
```

**Comment by julienw** [comment]
Or:
```javascript
type ActionA = { type: 'A', a: number };
type ActionB = { type: 'B', b: string };
```
because likely actions are not defined in the same location than the variables :)

**Comment by julienw** [comment]
see also https://flow.org/en/docs/react/redux/#toc-typing-redux-reducers

**Comment by erica93k** [comment]
@julienw That's the way I implemented it, but I get the *property not found* error

**Comment by erica93k** [comment]
I think one of the problems might be that I store the action types in a different file, and I have something like this in my *actions* file:

```
import * as types from './types';

export type TypeOne = { type: types.A | types.B, a: number };
```

**Comment by erica93k** [comment]
If I move them in the same file, I only get the error when I'm using *action.a* in a method. So that's might be the other problem.

Eg. 

```
return [action.a]; // this works fine

return [...state.filter(item => item !== action.a)]; // ERROR: Property not found
```

So, how do you deal with these situations?

**Comment by julienw** [comment]
maybe try with `import type` instead of just `import` ?

This would be a lot easier if you can put your code reproducing the problem in a separate github repository :)
Or have a "try URL" (from https://flow.org/try/) that reproduces the problem you have.

**Comment by erica93k** [comment]
@julienw  `import * as types from './types';` these are just action types (some strings), not flow types, so no need for `import **type**`

**Comment by erica93k** [comment]
I will put an example code somewhere later.

**Comment by erica93k** [comment]
You can reproduce the error [here](https://tryflow.org):

```
/* @flow */

type ActionA = { type: 'A', a: number };
type ActionB = { type: 'B', b: string };

type ActionAB = ActionA | ActionB;

export function AB(state: Array<string> = [], action: ActionAB) {
  switch (action.type) {
    case 'A':
      return [...state.filter(item => item !== `${action.a}`)]; // this doesn't work
    case 'B':
      return action.b; //this works
    default:
      return state;
  }
}
```

**Comment by julienw** [comment]
I think this is because flow considers `action` can be modified in a function call.
The solution is to extract `action.a` into its own variable.

[Here it works](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2hYAvGAN5jb4BcYA5IRwDRgCG7SgFcAtgCM8AJzABfANyZcBEuSoAhOo2bL2HdbzDj2AZwxSylAOZzFS-EVIVqm+quc0APo7WV1dvAAPHDgpDDAoYUonKiJ1AAozfgw8dkIpKX4sAB4zC2sAPi0AbQBdPn4YyjSqwnUASkZUMDATBDIMYgALMHjK3wA6FjxGhmaWsGJ+EwIuDnYxiYniKjMBLX7nAf5FJZapPAxhKUowYoGLpJSBqDIYFKl4jrxROiLn14BCWnp+etL5GBgMBmF0yCYwAATOB4EyUDjhBChADW4xasjRk2mswMrEx+0Ox1OmyoA3EgOBGDBEKRUmRJkxkLwUH4wnueL2YAORxOrQwyTwuzkqAxQA):
```javascript
/* @flow */

type ActionA = { type: 'A', a: number };
type ActionB = { type: 'B', b: string };

type ActionAB = ActionA | ActionB;

export function AB(state: Array<string> = [], action: ActionAB) {
  switch (action.type) {
    case 'A': {
      const a = action.a;
      return [...state.filter(item => item !== a)]; // this doesn't work
    }
    case 'B':
      return action.b; //this works
    default:
      return state;
  }
}
```

**Comment by erica93k** [comment]
@julienw I know it works on https://flow.org, but it does not on https://tryflow.org/ and my env. 

Extracting it into a const it only helps of the action types are in the same file. So this might be a flow issue.

**Comment by erica93k** [comment]
It seems that I was missing the `// @flow` line from my action types file. I did not know that it must be added there too.  It works now if I extract the fields to variables. Thanks @julienw !

**Comment by julienw** [comment]
Good :)
Indeed if a file is not covered, everything is `any` there.

I use https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-no-types-missing-file-annotation as a mean to avoid some of these issues. (although I'm not sure this would  have caught your particular issue here).
https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-valid-file-annotation could be useful too.

**Comment by tororudy** [comment]
I think it's related with this issue: https://github.com/facebook/flow/issues/5682

**Comment by AnshulMalik** [comment]
I got this error too, you can find it [here](https://flow.org/try/#0C4TwDgpgBAysCGxoF4oG8oGoBu8A2ArhAFxQBGA9hXhPAHZQC+A3AFCuiRQBiVAggGNgASwoNUGTJxJQARNwDyC2QBosAMyqlK1WnTUUwwUgGdgAJ2F0A5kzbSoAIXjnBIsVAlZppWY74ASqpYZC7aVDT0duwObqLiPPxC8VAAPk4ucWJsrOoEdMke5hAAJgQCEOYAFGaIMnB1avCFdKRZdACUpA1I6KxQUCYA7sLAAgAWUFXN7nQAdNIdfQMDAvAm0PJKsqT9KwPFwATmDHl0NQhITS0dbPtrG3L+QaSHxwwYc1+1V1C4hDIZvE5qFzNF9iUIOp4AQ8MY9vtpi1SBAALZGEC3BErN4nQaXCB3JisRjsM4tKBnC51boE66zNo3Wl1ZZQARiEy6OZ4CjWJGzOaGYBYg4QI54n6EklAA)

```
type State = { +value: boolean };

type FooAction = { +type: "FOO", +foo: boolean, opt?: string };
type BarAction = { +type: "BAR", +bar: boolean };

type Action = FooAction | BarAction;

function reducer(state: State, action: Action): State {
  switch (action.type) {
    case "FOO": 
      return fun(state, action);
    case "BAR": return { ...state, value: action.bar };
    default:
      (action: empty);
      return state;
  }
}

function fun(state: State, action: Action): State {
  console.log(action.opt);
  return state;
}
```


It throws this error `Cannot get `action.opt` because property `opt` is missing in `BarAction` [1].`
But it should not check for opt in BarAction right?

**Comment by hernanif1** [comment]
But [eslint] Unexpected lexical declaration in case block. (no-case-declarations)
Any other idea?

**Comment by BrunoQuaresma** [comment]
I have the same issue.

**Comment by julienw** [comment]
> But [eslint] Unexpected lexical declaration in case block. (no-case-declarations)

Usually when I use a `const` in a `case`, I create a lexical block, eg:
```js
case 'foo': {
  const bla = ...
  ...
  break;
}
case 'bar': ...
```

I don't know if this pleases eslint but at least this is cleaner :)

@BrunoQuaresma can you please detail more?

**Comment by BrunoQuaresma** [comment]
@julienw here is the link:

https://flow.org/try/#0MYewdgzgLgBAqgZQIIHECiB9AYmgKgYQAkMAlNARTjQVzQBEYBeGAckVUxwOLMutrosAUKEix26bHiIYEcfPjT16TVhM7TichUrr1ho6PGSSuMrEgCSAGRXM2Jjd2xXbgkeCPqMuSwFlqNBJLailnXioaOzVHH39A4NCzHgpIgQNPcVjfAIQgkIQwmW1FZQZ7bxyEgqKteVK9d0Msjjjc-KTNFxtoh1aqvMTC5O63YSEoAE8ABwBTeAgAQwBzWYAFRYAnRYBbCFUAbyEYGAATRcmIAC4YMABXHYAjWc2hAF8hCZn5rFmoYAAFkhgFAAJbgQ7HGBTOY3GGzEAAM2MrRGEX4KgAPtDvkiUZIBh1hl10VE6AAaKHTC4AGxAi1ONzgS1WG22exgADIYEcTidwPgQDtpjS-rMAPw3LB3MAg8FgKEfD5fOYwBB3YDAWYQCDAsEQ5i8nGw40I5HeEYlXRY014yrxQY1S31a0Uqm0+mMnlQk53FmzG4AeUeACtZiDKXyzhdrrcHs9XiclZ94TA0JtNiBNnr5ZCTvC4bjzbERhYegxsfC7dkHUTaqN6JGYNTJnSGTcjScdtr-TdoJtQWBlor3invjASLNThqXjmDWqNVqdXOwDBsenM9m5RDsb9-kDtwqVfMEFBFlB5oaoZtZss7jStkHQ+GoE2wd2IC9Qdqn2GQaPjxgPdAWZFZLwWMC2V2fZuSNd9tS-bVJRgR4QBAUVFjAJsBSFEUxWQ6VZX1BVlWaGBB1BMFFhpU9z3Ao0bzvB9Ng7N431BD9ENjA5kyEWYAA9pizWBERlQ8YBvactU2AAKKFoDom5aIvVQKKomizwvJsDlNclmw9BkYDeG5Jyk2dDyEABKJTNPmI0IAAd0owEYBk+FLO9KNgEWT98ScYoXTKK4fT5G8oDuTZV07KMYAAOnihStJCqNGPvR9PJiqN4tixLZli1LmKbTKTgAbRbNtTli85LgAXRucrPViv0wOSvkPky5UvJ8+Z7XaIZ6ytILWrCiKotak5styoqYvgz8Bx-DLirihLbPy280s2abMrKgzKuqiA6v01tGua1ZxqM1rOr5U5ZkRRZ7ygYLMpGyKYFykc3iAA

**Comment by julienw** [comment]
[this is how I'd do it](https://flow.org/try/#0MYewdgzgLgBAqgZQIIHECiB9AYmgKgYQAkMAlNARTjQVzQBEYBeGAckVUxwOLMutrosAUKEix26bHiIYEcfPjT16TVhM7TichUrr1ho6PGSSuMrEgCSAGRXM2Jjd2xXbgkeCPqMuSwFlqNBJLailnXioaOzVHH39A4NCzHgpIgQNPcVjfAIQgkIQwmW1FZQZ7bxyEgqKteVK9d0Msjjjc-KTNFxtoh1aqvMTC5O63YSEoAE8ABwBTeAgAQwBzWYAFRYAnRYBbCFUAbyEYGAATRcmIAC4YMABXHYAjWc2hAF8hCZn5rFmoYAAFkhgFAAJbgQ7HGBTOY3GGzEAAM2MrRGEX4KgAPtDvkiUZIBh1hl10VE6AAaKHTC4AGxAi1ONzgS1WG22exgADIYEcTidwPgQDtpjS-rMAPw3LB3MAg8FgKEfD5fOYwBB3YDAWYQCDAsEQ5i8nGw40I5HeEYlXRY014yrxQY1S31a0Uqm0+mMnlQk53FmzG4AeUeACtZiDKXyzhdrrcHs9XiclZ94TA0JtNiBNnr5ZCTvC4bjzbERhYegxsfC7dkHUTaqN6JGYNTJnSGTcjScdtr-TdoJtQWBlor3invjASLNThqXjmDWqNVqdXOwDBsenM9m5RDsb9-kDtwqVfMEFBFlB5oaoZtZss7jStkHQ+GoE2wd2IC9Qdqn2GQaPjxgPdAWZFZLwWMC2V2fZuSNd9tS-bVJRgR4QBAUVFjAJsBSFEUxWQ6VZX1BVlWaGBB1BMFFhpU9z3Ao0bzvB9Ng7N431BD9ENjA5kyEWYAA9pizWBERlQ8YBvactU2AAKKFoDom5aIvVQKKomizwvJtFkPG5Jyk2dDyEABKJTNPmI0IAAd0owEYBknTiIAOnhYzvSjYBFk-fEnGKF0yg7H0+TIg5mw9BkYDeVRHPlABuIKThvKA7k2VdOyjGAnKyhStISvlGPvR93IyqMsqcnLZicgrmKbEqTgAbRbNtTic85LgAXRuJrPScv0wLypM8o+KNhuCrz5ntdohnrK0AuKjzMh5MLW09SLosPeKSqSlK0oGzLsvM2qMvgz8Bx-ea6rKiqqtvQrNiOkrGvClq2ogTrlua3r-T20aRqC36zlmRFFnvKArjy7bUpgCqRzeIA)

My theory is that Flow isn't good enough to refine `payload` afterwards. But with the `switch` it knows how to refine `action`, and _then_ you can extract `payload` out of the refined action type.

**Comment by BrunoQuaresma** [comment]
Thanks @julienw !
