### ISSUE TITLE
Feature request: I way to specify a partial version of an object type

### ISSUE THREAD

**Issue by almost** [facebook/flow#498]
Say I have a type:

```
type State = {
  foo: string,
  bar: number
};
```

It would be really useful to be able to specify an update version of the type in which all the fields are optional.

```
type UpdateState = {
  foo?: string,
  bar?: number
}
```

For example in React the argument of setType should be an all optional version of the state type for the component.

Maybe syntax like `function setState(state: #State)`?

Does this sound feasible and/or a good idea? Or am I missing the obvious way to do this sort of thing already?

**Comment by samwgoldman** [comment]
What you are describing is implemented, but not documented or technically a "public" API. It's called `$Shape` and it's already used to type React's `setState` function. See [the definition in lib/react.js](https://github.com/facebook/flow/blob/8a34b0743850ea12a322c175112e18cc285f3da8/lib/react.js#L28).

You can find more about this and other types in [this awesome blog post](http://sitr.us/2015/05/31/advanced-features-in-flow.html).

**Comment by almost** [comment]
Thanks!

**Comment by StreetStrider** [comment]
@samwgoldman how am I supposed to get knowledge about this `$Shape` feature?

**Comment by ilias-t** [comment]
https://flow.org/en/docs/types/utilities/#toc-shape
