### ISSUE TITLE
Spread operator is not complete with intersection type

### ISSUE THREAD

**Issue by entropitor** [facebook/flow#4980]
This should not error but it does: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBGAhgM4EC8YA3qmGAB4BcYpGATgJYB2A5qgF902fIzBUS5MADIadMFhbcArgFtCedoMy4CAL3FEyBWbXqLWHHvyGoAbsXZhiLBobOMWAcgx42XgBp5CwBmINsHJ0IWAyoPADpE4iDzbyg4OC9BIA

```js
/* @flow */

type base = {
  x: string
}

type x = base & {
  y: number
}
type z = base & {
  y: string
}

var a: x = {
  x: 'test',
  y: 3,
}

var b: z = {
  ...a,
  y: 'foo'
}
```

The property `y` is overwritten so it shouldn't care about the type of `y` in `a`

**Comment by julienw** [comment]
While I think (like you) that Flow should be fine with this, [here is a possible workaround](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBGAhgM4EC8YA3qmGAB4BcYpGATgJYB2A5qgF902fIzBUS5MADIadMFhbcArgFtCedoMy4CAL3FEyBWbXqLWHHvyGoAbsXZhiLBobOMWAcgx42XgBp5CwBmINsHJ2oFALAAOgTSGE4AYzwAEwBBMAFDYgBue0ciFgMqDwS4pNSMzKDzbyg4OC9BIA).

```javascript
var { y, ...slicedA } = a;
var b: z = {
  ...slicedA,
  y: 'foo'
}
```

**Comment by johnhaley81** [comment]
@julienw that is unfortunately [not a sufficient workaround](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeokBAXKAM4oBOAlgHYDmoAvgNyqY4AhAIYNiZUACMRNes3Zde6bKGEAvMeSmqZjVhx7IlOfLGEM1G0ADobJgDTWbZhzatqDiAMawW9UGywUEzEAClIpBgctFxtKWE4aEzM1AEpiAD4KAmRvXxRQFCx6E0SCMQCggjDEUCzYGgByAEYGuxrJaVAGgCZW9q1GgGYGxE4U3i8fPwqzUNI4qKFVGKsIhLwCZKW0okyIidy-QvozGlmSGZFq2rjGlrbaiMbeh47tLuHR8Zyp-Mv1EhhBYdSKOVZLdZJESpDJvA6-ApFFBqM5LcqBNTXOp3PqPTo9XFvIYjMbcIA)

With [using intersection types](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeokBAXKAM4oBOAlgHYDmoAvgNyqY4AhAIYNiZUACMRNes3Zde6bKGEAvMeSmqZjVhx7IlOfLGGiSJ0ADIVIxfzwEzasZZtnrt1b0QBjWCz0oGxYKJYkABSkUgwANJJCqvEAdKmUsJw0Js6JAJTEAHwUBMj+gSigKFj0JlkEYiFhBFGIoMWwNADkAIydsa0JDF0ATH0DWl0AzJ2InLk+ZUGNHpGk6fFaKakxmY6mImr5REUxCwFBVfRmNCvBoWYtbeldvf1tMSNj74lTM3Nn5TuKBcq3Wgy2yS0u2yBzyhQS3lK5wql2BPy8DXuiUe7ReX0GnzeCN+s3mQA) you can at least get the elements from the first part of the intersection out using spread

**Comment by julienw** [comment]
Well he was actually using the intersection in his example above :) So I think we agree ;)

**Comment by entropitor** [comment]
It doesn't really matter whether it's an intersection or a spread in the definition of the types to me. It errors with both.

And I get that we can do something like the above but
a) we get an variable without a use (not ideal and gives errors in my linter)
b) the type system remains unsound

**Comment by nmote** [comment]
This is fixed in master
