### ISSUE TITLE
Type refinement doesn't work with the conditions in `while` loops

### ISSUE THREAD

**Issue by julienw** [facebook/flow#4983]
STR code:
```javascript
type Test = string | null;

function returnSomething(): Test {
  return 'foo';
}

let test;
while ((test = returnSomething()) !== null) {
  test.toLowerCase(); // call of method `toLowerCase`. Method cannot be called on possibly null value
}
```

[See this example online](https://flow.org/try/#0C4TwDgpgBAKhDOwoF4qIE4EsB2BzKAPlNgK4A2ZA3AFDUBmJ2AxsJgPbZToTAnrYBlNgFseACxy4AFAEoAXLARIA3tShcefTgHI6bNtpoBfWmR5RgSmgHcJZqFKmXEKDb35DRwCXlkyoAITIqKQU-qrqzsAAdMBsADJs1hDoAMIAhvAQssZAA)

**Comment by julienw** [comment]
Why ? Because this is a quite common idiom in some specific cases. The best-known is when iterting over regexp results:
```javascript
const re = /word/g;
let result;
while ((result = re.exec(input)) !== null) {
  // do something with result
}
```

So, yes, we can do otherwise (which I do now). But because this is a common idiom, and it shouldn't be more difficult to support than for `if` blocks, I believe Flow should support this too.

**Comment by jcready** [comment]
@lll000111

> Flow is designed to understand idiomatic JavaScript. It understands common JavaScript patterns and many of the weird things we JavaScript developers love to do.

**Comment by lll000111** [comment]
>  It understands common JavaScript patterns

And as we have seen, and as _you_ as a frequent commenter here of course knows (so what are you trying to do now?), the opinion about what constitutes "common JS patterns" of Flow are _much_ narrower than that of many programmers, from things such as `filter` to treating every single function as one that invalidates a type refinement.

> But because this is a common idiom

@julienw 

You are competing with a thousand other "nice to have" things, see list of issues. My attitude towards Flow has been shaped by what is actually **possible**, including the speed of development and the nr. of ignored issues. I did not say "close your ticket".

**Comment by julienw** [comment]
@lll000111 I understand this; I said that I _think_ this is not difficult to implement. Yet I don't know anything about how Flow internally works. In the end, this is not my call, I won't be able to implement this myself.

**Comment by julienw** [comment]
Upgrading to a newer Flow brought me the new typedef for `RegExp.prototype.exec`, which gave me this problem again.

[Here is a try exhibiting this issue](https://flow.org/try/#0CYUwxgNghgTiAEA3W84HMQA8Bc8BKIaAopgA4DcAUKJLAsjPAM4AuMurMAlgHZpUQQLeAFsoLMAAsqlAO6Sug+AAplYiZPgBeVISwA6LOGWcAlKfgBCLTp4BXCBAsBvSvHdgA9jyafB+iE80ZWdmFlgWXHUpfV5QTAAaeBAeYCjxGLiseABqUQzJAG0ABgBdAJS0Fk0AX1MqGsogA):

```javascript
declare var regex: RegExp;
declare var str: string;
let match;

while ((match = regex.exec(str)) !== null) {
   console.log({ start: match.index, end: match.index + match[0].length });
}
```

Error is:
```
    6:    console.log({ start: match.index, end: match.index + match[0].length });
                                     ^ Cannot get `match.index` because property `index` is missing in null [1].
        References:
        [LIB] ..//static/v0.79.1/flowlib/core.js:338:     exec(string: string): RegExp$matchResult | null;
                                                                                                     ^ [1]
    6:    console.log({ start: match.index, end: match.index + match[0].length });
                                                       ^ Cannot get `match.index` because property `index` is missing in null [1].
        References:
        [LIB] ..//static/v0.79.1/flowlib/core.js:338:     exec(string: string): RegExp$matchResult | null;
                                                                                                     ^ [1]
    6:    console.log({ start: match.index, end: match.index + match[0].length });
                                                                     ^ Cannot get `match[0]` because an indexer property is missing in null [1].
        References:
        [LIB] ..//static/v0.79.1/flowlib/core.js:338:     exec(string: string): RegExp$matchResult | null;
                                                                                                     ^ [1]
```

**Comment by nnmrts** [comment]
@julienw While I also think this should be implemented, look at this "workaround":

```js
const regex = /A/g;
const string = "ABABA";

let match;

while ((match = regex.exec(string))) {
	console.log({ start: match.index, end: match.index + match[0].length });
}
```

That works perfectly fine, because the while loop will stop on `null` AND flow also knows that, so type refinement works again.

[Try Flow Link](https://flow.org/try/#0MYewdgzgLgBATgUwOYIB4wLwwPQEFtIDcAUKJLNHAJZhKYwBEuAQi7gyQDYKwC2AhlGAALEsQDuwqtxgAKWQKHD6iFKgB0aBMFmUaSAJRGYAb2IBIMhBDd1nEElkmY0fnCgAuGIpHqaAEzQAGhgEMH8vH2E-cLQYAGpvQREAbQAGAF07MKQoZQBfAxJ8oA)

**Comment by julienw** [comment]
Oh, that's interesting! Thanks for this workaround!

**Comment by SamChou19815** [comment]
This is expected limitation
