### ISSUE TITLE
PATENTS still exists on the repository

### ISSUE THREAD

**Issue by riawiththesam** [facebook/flow#4985]
PATENTS still exists on the repository. It is when flow was licensed under BSD 3 + PATENTS.
Currently, Readme says Flow is MIT license. So I think PATENTS should be deleted.
Please let me know if there is a reason why PATENTS still exists.

* [update commit BSD3 to MIT](https://github.com/facebook/flow/commit/4eb62a5597d59174531d44e532c65daa25d8331b)
* [PATENTS](https://github.com/facebook/flow/blob/master/PATENTS)
* [case of React](https://github.com/facebook/react/commit/b765fb25ebc6e53bb8de2496d2828d9d01c2774b)

**Comment by mohitsinghs** [comment]
I actually created a pull request after noticing this. See #4977 . I hope someone explains the existence.

**Comment by nmote** [comment]
@gabelevi has a commit that's ready to land (and will probably land today) that removes it as well as cleans up a couple smaller things that were missed in the initial commit. Thanks for paying attention and for bearing with us while we complete this change!

**Comment by mohitsinghs** [comment]
Sounds good... Closing my pull request then.

**Comment by nmote** [comment]
Fixed in 55065bad5aa4d7e9b0266528bfd3c6af07a122c2

Sorry for the delay, we had to get clarification on something first. I think everything is squared away now.
