### ISSUE TITLE
Issue with Redux passing {type, foo} as Action parameter 

### ISSUE THREAD

**Issue by lvdang** [facebook/flow#4987]
If this is a bug, please try reproducing using https://flow.org/try/.
When using {type, foo} for the action. I am getting error below e.g. string literal BAR. Expected string literal FOO, got BAR instead HOWEVER if I use "action: Action" instead of {type, foo} works.

type State = {};
type FooAction = { type: "FOO", foo: string };
type BarAction = { type: "BAR", foo: boolean };

type Action = FooAction | BarAction;

function reducer(state: State, {type, foo}: Action): any {
switch (type) {
case "FOO": return { ...state, foo };
case "BAR": return { ...state, foo };
default:
return state;
}
}

// Errors

9: function reducer(state: State, {type, foo}: Action): any {
^ string literal BAR. Expected string literal FOO, got BAR instead
9: function reducer(state: State, {type, foo}: Action): any {
^ string literal FOO
9: function reducer(state: State, {type, foo}: Action): any {
^ string literal FOO. Expected string literal BAR, got FOO instead
9: function reducer(state: State, {type, foo}: Action): any {
^ string literal BAR
9: function reducer(state: State, {type, foo}: Action): any {
^ boolean. This type is incompatible with
9: function reducer(state: State, {type, foo}: Action): any {
^ string
9: function reducer(state: State, {type, foo}: Action): any {
^ string. This type is incompatible with
9: function reducer(state: State, {type, foo}: Action): any {
^ boolean
11: case "FOO": return { ...state, foo };
^ string literal FOO. This === check always fails because FOO is not the same string as BAR
9: function reducer(state: State, {type, foo}: Action): any {
^ string literal BAR

// Error
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA3gL4DcqmOAYrLAIIDGKAlrAHahnlQ6bAC5QAIgYB5KeIA0oSMzEBnFACdOPAOagadbKABCBdey69+FIfTHijLAErzFy0ACNm0LAT76DOObcfGRMrBzBoAA+xqZBvLSIkACuPBGW6lgAJslsWOoAFGpEWGL4JQrkwlgKSrCUYvE8AJRivmgUiKCgKvCcKGwAFqAF1c2d3d1sBCo4kjLiYpkoyep8ggB0W8XEtcx6tJOg07MSDs5LWCtr1lsbOzWusAddk1lYkATJ0Cgir0fLVZ8B6HPSISjIIA

// Works

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA3gL4DcqmOAYrLAIIDGKAlrAHahnlQ6bAC5QAIgYB5KeIA0oSMzEBnFACdOPAOagadbKABCBdey69+FIfTHijLAErzFy0ACNm0LAT76DOObcfGRMrBzBoAA+xqZBvLSIkACuPBGW6lgAJslsWOoAFGpEWGL4JQoE6Txi8TwAlGK+aBSIoKAq8JwobAAWoAVVFjwAdMJY9a3t7WwEKjiSMuJimSjJ6nyCI9vFxApKsE3VIwd6tNOgs-MSDs4rWGsb1tsju1j7bkPBJ8xnbdNZLCQAjJaAoET-C6rdZ8N7nPSISjIIA

**Comment by Mathspy** [comment]
This was fixed recently by [v0.103.0](https://github.com/facebook/flow/releases/tag/v0.103.0)

@goodmind
