### ISSUE TITLE
Can't assign `{ x : string }` to `{ x : string, y? : string }`

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#4988]
```js
// Consider:
type A = {
  x : string
};

type B = {
  x : string,
  y? : string
};

function takeB(b : B){}

//This is fine:
takeB({ x : '' });

// This is also fine
var b : B = { x : '' };

// But this isn't
var a : A = { x : '' };
takeB(a); // property 'y' not found in object type

// Neither is this
var b2 : B = a;

// But these are ok:
takeB({ ...a });
var b2 : B = { ...a };
```

AFAICT all operations here should be safe. Only if `A` would be closed then the above program would be unsound, but since `A` is open I can't see why it can't be used as `B`.

**Comment by vkurchatkin** [comment]
It can be used as `B`, because `A` can have a property named `y` of any type, not just string.

**Comment by TiddoLangerak** [comment]
Ahh, of course, I completely missed that. Thanks for the explanation!

**Comment by TiddoLangerak** [comment]
Follow up question: I still try to make something like the above work, but I can't figure out why the following solution isn't allowed:

```js
type A = {|
  x : string
|};

type B = {|
  x : string,
  +y? : string
|};

function takeB(b : B){}
const a : A  = { x : '' };
takeB(a);
```

Here I first made both A & B exact to ensure no additional incompatible properties are present (like @vkurchatkin mentioned was the problem in the original attempt), and then I made `y` covariant such that we ensure `takeB` can't set it, guaranteeing that if `b` stays a valid `A` even if uses as `B`. 

However, flow still complains that "property Y not found in object type", and I don't understand why. Do I still miss something?
