### ISSUE TITLE
Allow checking of .es6 files

### ISSUE THREAD

**Issue by mikz** [facebook/flow#499]
Currently flow supports just checking `*.js` and `*.jsx` files.

Consider supporting `*.es6` or just making it a configurable option.

https://github.com/facebook/flow/blob/8a34b0743850ea12a322c175112e18cc285f3da8/src/common/files_js.ml#L16-L19

**Comment by mroch** [comment]
good idea. I vote for making it configurable

**Comment by mroch** [comment]
Fixed by #562
