### ISSUE TITLE
Required module not found

### ISSUE THREAD

**Issue by kingaiakab** [facebook/flow#4991]
I use flow-typed for libdef, but it doesn't seem to work.

```
// @flow

import { Foo } from 'some-lib'; // ERROR: required module not found 
```

I have this in my `.flowconfig` file: 
```
[libs]
<PROJECT_ROOT>/flow-typed
```

And I have a file `flow-typed/some-lib.js`:

```
// @flow

declare module 'some-lib' {
  declare export var Foo: any;
}
```

Am I missing something?

**Comment by lll000111** [comment]
This is a ES 2015 `import` statement, not a Flow `import type` statement.

**Comment by erica93k** [comment]
But `flow-typed` should fix this error.

**Comment by lll000111** [comment]
> But flow-typed should fix this error.

No. Please read again what I wrote.

**Comment by erica93k** [comment]
I see. Do you know what could be the problem? It only gives the error for this package, which clearly exists.

**Comment by erica93k** [comment]
My problem is similar to [this](https://github.com/facebook/flow/issues/2092)

**Comment by TrySound** [comment]
@kingaiakab `some-lib` should actually exist in `node_modules`. flow-typed folder only adds types for it

This probably can be closed.
/cc @vkurchatkin
