### ISSUE TITLE
Flow v0.55 doesn't check properly in case of generics;

### ISSUE THREAD

**Issue by philipp-sorin** [facebook/flow#4994]
The code below emits no errors.

````
const response: Pageable<Array<SuggestEntity>> = await api.get(query, types, new PageRequest());
const content: Array<SuggestEntity> = response;
````

**Comment by jcready** [comment]
What is the definition for the`Pageable<T>` type? It would be valid if it returned `T` or `any` so your example alone doesn’t show a clear bug.

**Comment by philipp-sorin** [comment]
The definition is 
```
export type Pageable<T> = {
	content: Array<T>,
	last: boolean,
	totalElements: number,
	totalPages: number,
	numberOfElements: number,
	first: boolean,
	size: number,
	number: number,
}
```

**Comment by asolove-stripe** [comment]
@philipp-sorin When I recreate this [in Try Flow](https://flow.org/try/#0C4TwDgpgBAygrgcwRAzsAogO2AS1FAXijQCcdMEBuAKGogA8wB7E4KUSKABQENkeARgBsIAHgAqAPkJQA3tQCQAYybYI2AFxQAgiRI8QEyQBpFQnmi0CmTET0ymFwJsB5D0IgLbrgKLZjhPAQgSR2dXIV5kPygAoJDHOOCSAHkAMw8Ib2wYpITFNJwSSyhrWwh7RxQcAC8If0DkxMaQhvjQ6gBfWjS4TCVcVShkYAAKAEotKIrhMV19Q3gkVAxsPBBJaXkodgALEiYAdygAIkPdnmAIADcQqBxPMC8fS5xVADpPk5pu6hVMNBQEioZgA+rcPgzESieYGURLaKrXCgTYyEYTP6qQH-K6aHR6OEIlZYZEbGTAlCglAQShAA) an error definitely shows up.

I would guess that either `api.get` is returning an `any`, or else maybe this file is not being reviewed by flow. Can you give us more context?

**Comment by philipp-sorin** [comment]
Yeah, api.get returns any

**Comment by Mathspy** [comment]
Nothing actionable here as this actually does error in as demonstrated [above](https://flow.org/try/#0C4TwDgpgBAygrgcwRAzsAogO2AS1FAXijQCcdMEBuAKGogA8wB7E4KUSKABQENkeARgBsIAHgAqAPkJQA3tQCQAYybYI2AFxQAgiRI8QEyQBpFQnmi0CmTET0ymFwJsB5D0IgLbrgKLZjhPAQgSR2dXIV5kPygAoJDHOOCSAHkAMw8Ib2wYpITFNJwSSyhrWwh7RxQcAC8If0DkxMaQhvjQ6gBfWjS4TCVcVShkYAAKAEotKIrhMV19Q3gkVAxsPBBJaXkodgALEiYAdygAIkPdnmAIADcQqBxPMC8fS5xVADpPk5pu6hVMNBQEioZgA+rcPgzESieYGURLaKrXCgTYyEYTP6qQH-K6aHR6OEIlZYZEbGTAlCglAQShAA)

@goodmind This can safely be closed
