### ISSUE TITLE
react-dom16,createPortal is Error!

### ISSUE THREAD

**Issue by zenjava** [facebook/flow#4995]
"flow-bin": "^0.56.0",
    "react-dom": "^16.0.0",
    "react": "^16.0.0",

import { findDOMNode, createPortal,} from 'react-dom';
                           ^^^^^^^^^^^^ Named import from module `react-dom`. This module has no named export called `createPortal`.

**Comment by asolove** [comment]
Yeah, that isn’t in the 0.56 release. But is in master, so maybe will be in a release soon?

**Comment by zenjava** [comment]
Thanks, I use the master first.
