### ISSUE TITLE
Destructuring in callback to Object.entries(obj).map() mis-infers type

### ISSUE THREAD

**Issue by adimit** [facebook/flow#4997]
I can only reproduce the problem on my machine:

```
$ node_modules/flow-bin/flow-linux64-v0.56.0/flow version
Flow, a static type checker for JavaScript, version 0.56.0
```

In the following file, I'm trying to use a variable (`label` in the method `broken()` below) of type `Node` as a `children` prop for a React component. The component has type constraint `Node` on its `children` prop (of course) and the bound variable is incorrectly inferred as `mixed`.

```{javascript}
/* @flow */

import React from 'react';
import type { Node } from 'react';

type Props = {
  values: { [string]: Node },
};

class Foo extends React.Component<Props> {
  broken(): Array<Node> {
    return Object.entries(this.props.values).map(
      ([value: string, label: Node], index: number): Node => (
        <button>
          {label}
        </button>
      ),
    );
  }

  fixed(): Array<Node> {
    return Object.keys(this.props.values).map((value: string, index: number): Node => (
      <button>
        {this.props.values[value]}
      </button>
    ));
  }
}
```

Here's what I get when I run flow:

```
$ node_modules/flow-bin/flow-linux64-v0.56.0/flow
Error: src/Components/Example.jsx:14
 14:         <button>
             ^^^^^^^^ React element `button`
 14:         <button>
             ^^^^^^^^ React element `button`. This type is incompatible with
                v
170:     props: {
171:       children?: React$Node,
172:       [key: string]: any,
173:     },
         ^ object type. See lib: /tmp/flow/flowlib_3a1dbd85/react-dom.js:170
  Property `children` is incompatible:
     15:           {label}
                    ^^^^^ mixed. This type is incompatible with
    171:       children?: React$Node,
                          ^^^^^^^^^^ union: undefined | null | boolean | number | string | type application of type `React$Element` | type application of identifier `Iterable`. See lib: /tmp/flow/flowlib_3a1dbd85/react-dom.js:171
```

I tried [reproducing the problem online](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG5NcDjCBPHGTABvMADk4AE2EBfMHQbNW1Qp3QChYAAr0cAZzABeUajBgAbhRgBXMvoBcosAG19hfBgB2AcwC6TpIyYLIANKiyXKhUMBT6hgBicHBgZAAehGReUobkqgB0AMIMeF5ZhAA8unAGAHym5gBG9ADWWQAUAJROAIL4+BT8FUFk9SJm5mCshDb4XmAA8o0AVmQ0+eWe9u2EABYY+vk4eodWtvad+VgUOO0Tk2DtLmd2Tu6evqFgsY1kMIHSMh+L7eGRpJxeGxYX74boSQHGep3B4PCqNGyEQhwLy1e4o8wiH5-WR41HAdGY7G4-GdcIPTpccwkiZQDBpMhSLq9fqDYaAsZ46azeZLVbrNr8fQ7faHY41U7WOz6S7XW7tF5kN4ebw+EHZdIQqEwuEjRGPUlgNEYrE4i0EvYHI4nfIa-TPRVAkn4irk61UvGdBkTEmyIA), but I'm getting a JS error in the console (both Firefox and Chromium);

```Uncaught (in promise) … {t: 0, c: "Expected absolute location, got try-lib.js", l: 42} …```

It may be related to #4990

**Comment by samsch** [comment]
Here's a smaller reproduction. I just hit this issue myself. It looks like flow just sets the "values" output of Object.entries to `mixed` and drops all other type info.

```jsx
/* @flow */
type A = {
  [string]: Array<Object>,
};

const f = (a: A) => {
  Object.entries(a).forEach(([n, v]) => {
  	v.forEach(c => c);
  });
}
```
```
8:   	v.forEach(c => c);
      ^ call of method `forEach`. Method cannot be called on
8:   	v.forEach(c => c);
      ^ mixed
```
[Playground link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCCYAvGAN6phgDaAzugE4CWAdgOYC6AXIQwwIaYAPAHkARgCtcAY3QA+ADSoAvgG5UqaXBb0wUEmAAU-HgQCUJOeUphxU2QDpcLRk1y1jZh1DgMAovzSABaGhtQsCmAAbhwWxFYUVACQUd6+AcGG0pZg0mbqVMr5KqhAA)

**Comment by ksaxberg** [comment]
I've run into this issue several times as well, with [this](https://github.com/facebook/flow/blob/084bff3ec7d760b4ac5343fb929cc89f8116bc56/lib/core.js#L62) line being a direct cast to `mixed`, even when the object in question is a type like `samsch` posted above. It would be great to use inference here on the object type. Hopefully something like this would get the job done:

```js
function values<T: mixed>(obj: {[string]: T} | any): Array<T> {
  return (Object.values(obj): any); 
}

// Let's test it with an opaque type and a non-object.
opaque type Special = string;
const makeSpecial = (x: string): Special => x;

const test: {[string]: Special} = {
  a: makeSpecial('val')
};

const specialValues: Array<Special> = values(test);
const handleArrays = values([1, 2, 3]);
```
[Playground Link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swA3AQxkwFMBnAHgBUAuMAW0IA8aATAPgAUcAEYArNgG8A2nXwAnQtgDmAXTZMAvmAA+YCtgCeASjYBBefIqHm-MJNRgw8mvkzzSggPLiaBAHSU1PTC4qb6RsYA3GComujAwGAAMq4A5HRg+PT4YIS5CPkAFhFgcAAOFACOtFmG5TQRvPpg2CQAtKJifvj+qBXVtfj1jQDKDbiEVGAAvGByiipRqLgkchwUANY0435TMLNgglxsC0rK4buT0zN2XMsra7nZclKyCufqYFf72nMOTgobHYWx2E32gjSQTSxjiD1W2HWdHBVAAalRaHRzJZrAwflQ7HMgpjBC98NFHojckUDLwYDQLFZDJkiRiQtIAIwAGjAACYeQBmVTRIA)

**Comment by SavePointSam** [comment]
Running into this as well, appears to be related to https://github.com/facebook/flow/issues/2174. Even if I add types to the destructure in the map, I'm stuck

```js
// @flow

const TAB = Object.freeze({
  TAB1: "Tab 1",
  TAB2: "Tab 2"
});

type TabId = $Values<typeof TAB>;

const updateState = (nextTabId: TabId) => {};

const getTabs = () =>
  Object.entries(TAB).map(([key, value]) => ({
    onClick: () => updateState(value)
  }));

const getTabsWithTypes = () =>
  Object.entries(TAB).map(([key, value]: [string, TabId]) => ({
    onClick: () => updateState(value)
  }));
```

[Playground Link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAKgIIBCoAvKAPIBGAVgKYrYB0kATnXQF50AUA3olD5iARgBcoAER4AhlVAjJAGkHCiAJgnS5odZMQBfAJQBuZNgCeABzr45ASQAmZUABIAajOgBXOpgA8ljawkGoAfGaoGDig3laOMth0AMrYibbkPOh0AB7YslROEgVORmRhoHwGkWhYuADmdPlymC48ZaRhqtT0jEx06NisAJZ+PIRERkwAtjJWPDwA2gDWdBZKoABuXr4Auh0V-KpCGADC0MMoyxLt5bHx6anpPNs+dEaqxqbItTGNzVRMAB1YbYAAWeGsfjaB26tAYzAGQ1GmHGxCms3mS1W6y2OzouwkixwI3Q9Q2JUc+zuRyEJ3Q50u11At069wSSSeSRe+I+Qi+ZiAA)

**Comment by gkz** [comment]
With above commit, object types that have an indexer and no explicit properties (e.g. `{[string]: number}`) have the type of their dictionary values returned by `Object.values` (e.g. `Array<number>`), and similarly with `Object.entries`, except the first element of the tuple works exactly like `Object.keys` (in this case, `Array<[string, number]>`)
