### ISSUE TITLE
Types only checking when explicitly defined, unsound when implicit (inlined)

### ISSUE THREAD

**Issue by niieani** [facebook/flow#4998]
These two versions are semantically identical and differ only in the placement of types:
- working: [extracted types](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagEqYCYCuAxpgE4A8AKqAFygDOyZAlgHYDmoAvKAIZtUAGlABVHv0EA+CRQDydUAG80WRVQC+UgBSwsZPshaw2iuQEoeM0SgzYAsnwDWmPEVJkGsnIqUBtVUx6JlZOAF16NxJyCiktbTICaM9FHEtuGTl9Q2M2BgocKVs1LPIck3zC2Rpg5nYOEQV6FTt1UAAyUAASAGlMVEq4nT0yoxMzdMzssbYCkSpGqQBuYuxSgxm50AXQORleLoBhPmhoCi6AUWhMAFtMNmQqOy2qKUWVxGIK5FAb52x6I4XFEPF5eAkkqDJohQKBdNNctDYYl3OQGH4RhtcgA6QJheGjREfL55H74FgMdCGYgACwkfxc2iUMNAJiCcL0k1AAEYhCzkPBYPR4VyAOQAJlFfNhDEw0EgwpaWA0XMCfJVxO+rLY2F45Mp1JpTMC9FFbKloAAHvRuRrELodYpueYViBGDTYIRoPhQOQyLAyLR7WzFOKXZ8tQLYBJ9VTkLTjXZTVHRXbtFHFBLReG3QwPV6fX6A0GSUxQMgaYldaBY4bE1hk5XMJhU+HSz9ZfKYxS4wmlezRZ3IK2Vtoh5mh9nXWA857vb6yP7A-bx6bzeGgA)
- broken: [inline types](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagEqYCYCuAxpgE4A8AKqAFygDOyZAlgHYDmoAvKAIZtUAGlABVHv0EA+CRQDydUAG80WRVQC+UgBSwsZPshaw2iuQEoeM0YhChkAC0wNsyeLHsZn-MtjYJQfExIdgJQdmhQ2ltgVWwAWT4Aa0w8IlIyBlkcRSUAbTj6JlZOAF16NJJyCiktbV908iyKy24ZOX1DYzYGChwpGLjQDvIuk17+2Roi5nYOEQV6FS91UAAyUAASAGlMVAnanT1RoxMzVvbO07Y+kSoFqQBuFBWRg2vb0HvhmV5NgGE+NBoBRNgBRaCYAC2mDYyCoXk+VCkD2eiGI42QoChyWwvEQoFAfVyBS8MxKHHKuAIVUoh3qNIyzVwFwJROmjFmnAWuSG9BoGx2ewOdWO7265zMV26SIeVjZDVpDDyYrGbAAdHFSrppSZzGiMT0sfgWAx0IZiA4JDiUtolGyTJh6DqLqAAIxCNluWDOvSugDkACZ-Z7CS5oJBncssBpXXFPbGDZjQI6JCazRaHHbCqB-Y6Q6AAB70N2JxC6NjYEv6mKMBywQjQfCgchkWBkaIVqugQM1w1MezuNOm83IS3Zsm573+svab2KIP+mt2Bj1xvN1vt6L9rGOXx4wIjzMTrD0f17zCYGd95PhyDDjNjrPRp25u-X57aO8L9-LsCrhsmxbMg2w7ctvzPfMayAA)

The only change is that `MakeReducers` and `Operations` types are now inlined and the return type of `MakeReducers` is implicit. Note however that the returned function has _exactly_ the same signature as the type declared in the first version, i.e. the inferred type should be identical to the explicitly declared one.

**Comment by sibelius** [comment]
same on latest version

**Comment by SamChou19815** [comment]
Closing since the repro uses $Call which is no longer supported
