### ISSUE TITLE
Implement a Webpack loader

### ISSUE THREAD

**Issue by appsforartists** [facebook/flow#5]
We use [webpack](https://github.com/webpack/webpack) for transforming JSX to JS, dependency management, and concatenation.  It would be lovely if Flow was callable as a Webpack loader:

``` javascript
    {
      "test":   /\.jsx?$/,
      "loader": "react-hot-loader!flow-loader!jsx-loader?harmony"
    },
```

**Comment by bebraw** [comment]
@appsforartists Did you manage to find a good solution for this? [flowcheck-loader](https://www.npmjs.com/package/flowcheck-loader) works up to a point but fails with some advanced features (stage 1 decorators etc.).

**Comment by bebraw** [comment]
@appsforartists I figured out a workaround. You can try something like `loaders: ['react-hot', 'babel', 'flowcheck', 'babel?stage=0&blacklist=flow']`. See https://github.com/gcanti/flowcheck/issues/19 for further discussion.

**Comment by breandr** [comment]
Any update on a flow pre-loader?

**Comment by bebraw** [comment]
@breandr Check out [babel-plugin-typecheck](https://github.com/codemix/babel-plugin-typecheck). I feel that's a better alternative than flowcheck right now.

**Comment by StoneCypher** [comment]
I just dump babel results to disk before my packager gets started, in a build directory.  There's really no need for these preloaders and adapters.

**Comment by jedwards1211** [comment]
@bebraw Plus I'm guessing that flowcheck would slow down my app at least as much as React PropType checks (which come out at the top of my profiling results and make some mouse drag interactions laggy due to the complexity of my app).  So I'd rather just stick with compile-time checks right now.

**Comment by bebraw** [comment]
@jedwards1211 Flow is surprisingly fast in daemon mode actually. But yeah, even something like babel-plugin-typecheck is quite nice even if it's not exactly the same.

**Comment by jedwards1211** [comment]
@bebraw yes Flow is fast, but it has nothing to do with flowcheck does it?  As far as I understand flowcheck just runs JS code injected into your app to validate at runtime, rather than interacting with a Flow daemon in any way.  It's the runtime validation I'd expect to be slow, not the compile-time checks that Flow does.

**Comment by bebraw** [comment]
@jedwards1211 Correct. The runtime checks are pretty much equal to what you get with `propTypes` as far as I understand. It just generates some runtime asserts there. So it's nowhere near the same, but far better than nothing.

**Comment by artyomtrityak** [comment]
any flowtype webpack integration to see flow status results in webpack output ?

**Comment by StoneCypher** [comment]
please don't use github tickets for tech support

**Comment by jedwards1211** [comment]
It's at least possible to create a webpack plugin that execs `flow status` every time something is recompiled...I'll probably do that at some point if no one else does

**Comment by camjackson** [comment]
@jedwards1211 That's the sort of thing I came here looking for. At the moment I'm using eslint-loader for webpack to lint my code every time I change something. It would be awesome to integrate flowtype into that workflow, and see the output of `flow status` whenever webpack detects a change.

**Comment by camjackson** [comment]
Oh wait, I just found flow-status-webpack-plugin: [npm](https://www.npmjs.com/package/flow-status-webpack-plugin) | [github](https://github.com/diegodurli/flow-status-webpack-plugin)

**Comment by jedwards1211** [comment]
It figures someone would have done that by now -- thanks for pointing that out!

**Comment by jedwards1211** [comment]
@camjackson heh...I tried it but I don't always see the flow status output, and there is no github or issues link in that npm package, which is the only thing its author has published to npm.  I guess I'll e-mail him...

**Comment by camjackson** [comment]
@jedwards1211 Yeah it's annoying when npm doesn't link to github. I managed to find it though if you want to open an issue: https://github.com/diegodurli/flow-status-webpack-plugin

**Comment by jedwards1211** [comment]
@camjackson I did and made a fork; warning!! I would recommend using my fork until [my PR](https://github.com/diegodurli/flow-status-webpack-plugin/pull/2) gets merged, mainly because the `FlowStatusPlugin` constructor in the public package has the surprising side effect of restarting flow.

**Comment by moljac024** [comment]
@jedwards1211 As far as I can tell that plugin won't fail the webpack build if there are flow errors? Is there a plugin that can do that? I thought that would be the whole point of a webpack plugin for flow :D

**Comment by jedwards1211** [comment]
@moljac024 right, it doesn't fail the build, which would be helpful.
As an aside, these days instead of using that plugin I just use a separate swatch script (though I haven't figured out how to get it to preserve formatting and font weight):

```bash
#!/bin/bash
which wr || npm i -g wr
flow status
wr --exec "clear && printf '\e[3J'; flow status" src test
```

**Comment by moljac024** [comment]
I have implemented a basic version of the flow webpack plugin, that fails the build on errors. You can find it at my [fork](https://github.com/moljac024/flow-status-webpack-plugin), which isn't merged upstream yet.

**Comment by brunocodutra** [comment]
Meanwhile I decided to implement a true [[pre]-loader](https://www.npmjs.com/package/flow-bin-loader) that calls `flow check-contents` individually for each file matched and aborts on error.

```.sh
$ npm install --save-dev flow-bin flow-bin-loader
```

```.js
module.exports = {
  // ...
  module: {
    preLoaders: [
      // ...
      {
        test: /\.js$/,
        loader: 'flow-bin',
        exclude: /node_modules/,
      },
      // ...
    ]
  },
  // ...
}
```

The implementation is straightforward enough to fit here:

```.js
const spawn = require('child_process').spawn;

module.exports = function(source, map) {
  const cb = this.async();
  const flow = spawn(require('flow-bin'), ['check-contents']);

  let stdout = '';
  flow.stdout.on('data', (data) => {
    stdout += data;
  });

  flow.on('close', (code) => {
    if(code)
      console.log(stdout.replace(/^-(:[0-9]+.*)/, `${this.resourcePath}$1`));

    cb(code ? code : null, source, map);
  });

  flow.stdin.write(source)
  flow.stdin.end();
};
```

**Comment by bboysathish** [comment]
Still no loader available for flow with webpack ?

**Comment by brunocodutra** [comment]
@bboysathish did you try https://www.npmjs.com/package/flow-bin-loader?
