### ISSUE TITLE
Don't require classes to redefine properties of interfaces

### ISSUE THREAD

**Issue by arabold** [facebook/flow#5008]
## Feature Request

This is probably related to #3798 but I also different enough to hopefully justify a separate request. My use case is as follows:

I define the schema of an object using an interface:
```js
interface MySchema {
  foo: string;
  bar?: string;
}
```

When I implement this interface in a concrete object `MyObject`, I have to repeat all property definitions from `MySchema` again:
```js
class MyObject implements MySchema {
  foo: string; // <-- This shouldn't be necessary IMO
  bar: string; // <-- YUCK! `bar` has to exist now instead of being optional as in the interface

  doSomething() { ... }
}
```

I don't see why it should be necessary for classes to redefine all properties already defined in the interface. They should be usable right away. And by forcing `bar` in this example to be a mandatory property doesn't seem right either. I can make the value nullable but still, it's not how the interface was defined.

Using a base class instead of an interface is a possible workaround. However, this solves some of the issues but with the drawback of preventing multiple inheritance. E.g. it wouldn't be possible to have compound classes that implement multiple schema interfaces at the same time.

Should implementing an interface really require redefining all properties again? Or is there a way of having classes follow a certain type definition other than by using interfaces?

**Comment by samwgoldman** [comment]
I don't think this is different from #3798
