### ISSUE TITLE
Consistent location order for errors

### ISSUE THREAD

**Issue by seanhess** [facebook/flow#501]
I'm trying to improve error highlighting for vim. I'm stuck because `flow --json` has an inconsistent order for it's messages. They are always human readable, but not machine readable. 

For example, the following code: 

    // @flow
    type User = {name: string, age: number}
    var user:User = {name:"hello"}

Produces the following errors: 

    {
      "passed": false,
      "errors": [
        {
          "message": [
            {
              "descr": "property age\nProperty not found in",
              "code": 0,
              "path": "/Users/seanhess/sources/syntastic/test.js",
              "line": 2,
              "endline": 2,
              "start": 13,
              "end": 39
            },
            {
              "descr": "object literal",
              "code": 0,
              "path": "/Users/seanhess/sources/syntastic/test.js",
              "line": 3,
              "endline": 3,
              "start": 17,
              "end": 30
            }
          ]
        }
      ],
      "version": " May 12 2015 22:58:32"
    }

In this case, a text editor should really highlight line 3. But without reading the english description it has no way of distinguishing it from the errors produced in this case: 

    // @flow
    var name:string = "bob"
    name = 23

Errors: 

    {
      "passed": false,
      "errors": [
        {
          "message": [
            {
              "descr": "number\nThis type is incompatible with",
              "code": 0,
              "path": "/Users/seanhess/sources/syntastic/test.js",
              "line": 3,
              "endline": 3,
              "start": 8,
              "end": 9
            },
            {
              "descr": "string",
              "code": 0,
              "path": "/Users/seanhess/sources/syntastic/test.js",
              "line": 2,
              "endline": 2,
              "start": 10,
              "end": 15
            }
          ]
        }
      ],
      "version": " May 12 2015 22:58:32"
    }

In the above, the line to highlight is the first message, not the second. 

Can flow be altered to produce these messages in a consistent order? Is there a reliable algorithm to know which of the messages represents the real location of the error?

**Comment by gabelevi** [comment]
> Is there a reliable algorithm to know which of the messages represents the real location of the error?

This turns out to be a really hard problem. Ideally the first location would always be the location at which you the developer screwed up. Flow is doing data flow analysis, so it has a whole strack trace of locations. Figuring out which locations to use is really hard. It's much better than it used to be, but it still has some way to go. @bhosmer is working on it. Our main goal to make sure the error message is clear without having to fall back to `flow check --trace 10` for more context. 

Personally, I'm not sure if the idea of a "real location of an error" generalizes beyond simple examples. Even I, as a human software developer, often need to think about how to fix the code before I can figure out what is wrong.

**Comment by seanhess** [comment]
The one time it is obviously wrong is when a type alias doesn't match an assignment. In that case it never makes sense to refer to the type alias in first position. In fact, the only time a type alias can be wrong is a full-blown syntax error, so maybe defaulting to always showing type alias locations later in the error list would be better than what we have now.

**Comment by seanhess** [comment]
I would be willing to provide more test cases if it would help. Just let me know. Thanks!

**Comment by samwgoldman** [comment]
Just rechecked this and the error is now attributed to the incompatibility of the annotation on line 3 and the literal on line 3. I believe this issue is resolved.
