### ISSUE TITLE
Flow understands if but not ternary operator nor Array.includes

### ISSUE THREAD

**Issue by apsavin** [facebook/flow#5012]
[Try link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AJQCqgC8oA3oqKAIYD8AXKAM4oBOAlgHYDmANBaACN6oAIIsWVNAB5m7bgD4+AX2QhIAVw4BjFG1gdQWgBZYtAawAUnDOpQMxE6aQ5UAtlgYByKp9AAfUE8BTx5QADcqaHUPJlZOLiV5AEoGAjJEEABIFiwUdRYDa1sAOhyAE3UtLAsLWFtQ2AEAKyTieVALUmLuupRQgG1GpuKXdwBdBiGRtxwiOcCfUBpQKYionEnm4rXo4sYMaDYUCxDPJKUk0NILgG4M4BVEDW1dfUMTcysOGztRcUkpM4Zl5FgEgiFwpFogxZPFEik8IRyNlcvlCt8SuVKtVavUVs1WkR2uRKKTQJk2JAOlNRrN5t4zukyczQDk8gUmSzmd1ir1QvwuaTBltaRN8cMdlg+ILKEo7oKVGSUeyDCSZTy+aABVzhcNRZsJVCsHsDkcTjwztqyXLtUorrdEI8tPpmJDoMR3qZLP0xkkbkA)

This works:
```js
type RT = {
  a?: string,
  b?: Array<string>,
}

function check(input: Array<{ name: 'a' | 'b', value: string }>): RT {
  return input.reduce((out, obj) => {
    if (obj.name === 'a') {
      return {
        ...out,
        [obj.name]: obj.value,
      };
    }
    return {
      ...out,
      [obj.name]: obj.value.split(',')
    };
  }, {});
}

const val = check([]);
```

But this throws an Error:

```js
function check(input: Array<{ name: 'a' | 'b', value: string }>): RT {
  return input.reduce((out, obj) => {
    if (['a'].includes(obj.name)) {
      return {
        ...out,
        [obj.name]: obj.value,
      };
    }
    return {
      ...out,
      [obj.name]: obj.value.split(',')
    };
  }, {});
}
```

And this throws an Error, too:

```js
function check(input: Array<{ name: 'a' | 'b', value: string }>): RT {
  return input.reduce((out, obj) => ({
    ...out,
    [obj.name]: obj.name === 'a' ? obj.value : obj.value.split(','),
  }), {});
}
```

**Comment by apsavin** [comment]
The case with `Array.includes` is especially sad, because it forces to write long if clauses instead of short checks.

**Comment by ksaxberg** [comment]
This feature would be nice to have, even if it would require calling `Object.freeze` on the array.

**Comment by SamChou19815** [comment]
This dynamic object init pattern won't be supported
