### ISSUE TITLE
Unable to type cast casting Array<number> to recursive type

### ISSUE THREAD

**Issue by lPadier** [facebook/flow#5013]
```js
/* @flow */

type Recursive =
  | number
  | Array<Recursive>
  
const a = [1, 2];

// Works
const b: Array<number> = a;

// Works
const c: Recursive = a;

// Breaks due to sub typing issue
const d: Recursive = b;
```

[Example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAxgK4BOAzgJYBuBAvKmGAD5gB2ZAtgEZ4KLdmACCFCgEMsAHmLlq9PAD5hqEnE5UMYSWEZgA2gEYANGABMAXQDc6YMDAB1OBQDWVdZu1g+ALjEJaRlufkFlfV07VAdnVw8vLR0SAPlKWgZIyWjYgCEKPEkPMAATMgIMODAqMj4wbBwaTgBzMBoqGrwY4A0k0tTSdKVIvmjen0kLSJNTaxzHF3dPcZ08AYUMpl0LADoqVwwACgBKebB8wuKyiqr9ih0GptaMAAsCApqYHUkqQKlZUICCiqBwrMBQdZDTIGSZ7A6HQ6SUx8Y76CJ6AC0vlO9kcAHlOAQYE13ngcBQqmRaC16rgCCQfhhPA4ETNLFYAoDBIYrMdIYoGMdUEA)

**Comment by vkurchatkin** [comment]
This doesn't work, because `Array` is invariant. Consider using `$ReadOnlyArray` instead.

**Comment by lPadier** [comment]
Thanks for the quick response, this fixes the issue.
