### ISSUE TITLE
Type refinement is forgotten after setTimeout

### ISSUE THREAD

**Issue by whmountains** [facebook/flow#5016]
https://flow.org/try/#0MYewdgzgLgBANiA5jAvDAFANwFw2gJwEsxkAfGAQX3wEMBPAHgOMQD4BKVVmAbwCgYMQgDMMUOgAcApiFGZUKNAHJmJJZ36DB8tAG1MAXQEwAvseMQpUACqEAtjICuUdOk4puoSCDhSAdAiIWH4AViDE6EoANOrs7HxmfIHoAERQUtAp7EA

```js
const log = (v: string | Array<string>) => {
  if (typeof v === 'string') {
    v = [v]
  }
  
  setTimeout(() => console.log(v.join(',')))
}

log("test")
```

**Comment by Naddiseo** [comment]
Possibly a duplicate of #4941 ?

**Comment by goodmind** [comment]
Duplicate of #4941
