### ISSUE TITLE
flow-typed needs maintainers

### ISSUE THREAD

**Issue by Li0liQ** [facebook/flow#5020]
At the moment `flow-typed` is the suggested way of looking for flow definitions for libraries.
Unfortunately, it is currently [maintained](https://github.com/flowtype/flow-typed/issues/1296) by a single person.
I think, keeping definitions up-to-date is as essential to flow adoption as releasing new versions of flow. In fact, if popular libraries won't have up-to-date definitions available, developers may not be able to upgrade to the newer flow versions. That will make flow release frequency irrelevant - nobody will use it anyways.

Please, join [flow-typed](https://github.com/flowtype/flow-typed/issues/1296).

Another solution might be to come up with a way to piggy-back on TypeScript definitions if nobody wants to maintain `flow-typed`.

**Comment by stereobooster** [comment]
I wonder what are incompatibilities between type systems. TypeScript known to be unsound, but Flow is sound.

**Comment by jcready** [comment]
@stereobooster Flow is not sound. There are plenty of open issues here related to soundness. Flow simply *aims* to be sound, whereas TypeScript does not.

**Comment by stereobooster** [comment]
Yes this what I meant. Thank you for correction

**Comment by chrisgervang** [comment]
https://github.com/joarwilk/flowgen is a project that does a good job at outlining the differences between the two definition languages. The issues with converting between the two not very abstract issues, but concrete ones like "how do we convert namespaces from TS to objects in flow?"

**Comment by TrySound** [comment]
All discussions about flow-typed are moved into discord channel.
