### ISSUE TITLE
Spreading object types produces odd resultant types

### ISSUE THREAD

**Issue by jcready** [facebook/flow#5025]
```js
type Foo = { +foo: 'foo' }
type Bar = { +bar: 'bar' }
type FooBar = { ...Foo, ...Bar }

declare var foobar: FooBar;
(foobar.foo: string); // No error expected, got one anyways
foobar.bar = 'bar'; // Expected error, none produced
```

The type-at-pos for the `foobar` variable is ([Try Flow](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvKBqAZggXFAchzgKgF8AoUSKAIQEMAnZNTAIyfwI8dMuujw4DZinQA6SUIA0USeJHkKFACYQAxgBsm0AG5MoxHviEiA3BQAURpuOL4AzsEYBLAHYBzAJRmoAej8oADlECEZGOGYIAA9IdWAIFVkPOGAoODdoejcQAHd6EAcKG0ZxHhZuJgJfAKgAUViNBJUoMIjGWTcM6DAIlQBXdUSgA)):

```js
{bar?: mixed | 'bar', foo?: mixed | 'foo'}
```

So not only did spreading the objects cause the properties to lose their variance, but it also changed the types of those properties to become nullable unions with `mixed`. However, if I change both `Foo` and `Bar` to be exact object types, then flow gets the correct types of the properties, but still loses their variance:

```js
type Foo = {| +foo: 'foo' |}
type Bar = {| +bar: 'bar' |}
type FooBar = { ...Foo, ...Bar }

declare var foobar: FooBar;
(foobar.foo: string); // No error
foobar.bar = 'bar'; // Expected error, none produced
```

The type-at-pos for the `foobar` variable is ([Try Flow](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPlA1AMwQLigHI84ip0BfAKFEigCEBDAJ2TUywCNXCieW5KrXDR4cZmxSooAOnniANHPmSoNagBMIAYwA2raADdWUUgMLjJAbmoAKc61mlCAZ2AsAlgDsA5gEprKAB6YKgAOUQIFhY4FmpHFlkBdn5WIiDQqABRAA9IHWAITSho2JZlbzhvaDBYzQBXHWKgA)):

```js
{bar: 'bar', foo: 'foo'}
```

**Comment by TiddoLangerak** [comment]
I think the first problem is expected: type spread is supposed to model object spread behavior. If the type is not exact then flow cannot guarantee that spreading `Bar` won't overwrite properties from `Foo`. Hence, any property that's defined in `Foo` but not in `Bar` will get the type `mixed | <type in Foo>`.

**Comment by JanPeter** [comment]
I don't understand why `foobar.bar = 'bar'; // Expected error, none produced` should produce an error if the `Bar` type clearly states that the `bar` property should be assigned only the value `'bar'`. Sure you didn't mean `foobar.foo = 'bar'` should produce an error?

**Comment by TiddoLangerak** [comment]
`Bar.bar` is covariant, so it can't be assigned to. The covariance property is apparently dropped when spreading.

**Comment by jcready** [comment]
> If the type is not exact then flow cannot guarantee that spreading `Bar` won't overwrite properties from `Foo`

@TiddoLangerak we're talking about spreading the types here, not spreading an actual javascript object which would satisfy the types. While the type `{ foo: 'foo }` can be satisfied by javascript objects which contain more properties than just `foo`, the type itself doesn't. So spreading `{ ...Foo, ...Bar }` should produce the type `{foo: 'foo', bar: 'bar'}`. That type can be satisfied by javascript objects which contain properties other than `foo` or `bar`.

It also doesn't even make sense as an argument because spreading actual javascript objects actually produces the type I was expecting while spreading the object types:

```js
const foo = { foo: ('foo': 'foo') }
const bar = { bar: ('bar': 'bar') }
const foobar = { ...foo, ...bar }
```

The type-at-pos for the `foobar` constant is ([Try Flow](https://flow.org/try/#0MYewdgzgLgBAZiEMC8MDe9EC4YAoDkCI+Ohi+AlDAL4BQoksARgIYBOK6MrbOBPJGPgFU6DaJhA9OGAHTyiAGhjzZ06kA))

```js
{bar: 'bar', foo: 'foo'}
```

**Comment by vkurchatkin** [comment]
See explanation here: https://github.com/facebook/flow/issues/3534#issuecomment-287580240

**Comment by jcready** [comment]
@vkurchatkin so then to produce the object type I *actually* want (sans variance) I should do something like this?

```js
export type Foo = { foo: 'foo' }
export type Bar = { bar: 'bar' }
/*::
declare var foo: Foo
declare var bar: Bar
const DesiredType = { ...foo, ...bar }
*/
export type FooBar = typeof DesiredType
```

**Comment by vkurchatkin** [comment]
No, you can just do this:

```js
type FooBar = { ...$Exact<Foo>, ...$Exact<Bar> }
```

**Comment by jcready** [comment]
@vkurchatkin ahh, perfect. Is there any way to preserve the variance of the properties?

**Comment by vkurchatkin** [comment]
@jcready no, there is nothing you can do.

**Comment by jcready** [comment]
That's too bad, is it not possible to do (soundly or otherwise) or is it just something that hasn't been worked on yet?
