### ISSUE TITLE
Array.prototype.concat on nested arrays gives faulty error

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5026]
[Example of bug](https://flow.org/try/#0C4TwDgpgBAggTnAhiA8gM3kkBnKBeWBZAHkxO2DgEsA7AcwD4GBuAKFEkK3QFkqAPCABN8XcpVp0oAHzEhiFavSZtWAGwjAoiAFxzeA4aIDaAIgD2NCKYA0UM8ADu521FPAAFnAjWAundM0cwBXOFNfNg0tACM9MlQMIhwTM0s-OwdnV3cvH3CMwJCw3wjWVmjRaIA6AGNLGsRgAApjVKtw3wBKZigAel6oAAVg7A8IXE9oRCT7C3bfKEtgcyhJqAgaEXM0KGqyioJqupoG5tbEYwAGEq6e-qgAZQ8QtREwEY9Vse0Ztr9FmjLL7QDZbHbROzRYJaITmcY0ADkwCqrCAA)

As you can see, line 7 works whereas line 9 does not work, when they are the exact same code.
Flow seems to mess up on the extra [] around arrays inside concat(). When I ran into this live, it would tell me that `arrayOfArraysVar.concat([arrayVar])` was wrong, but `arrayOfArraysVar.concat(arrayVar)` was right. This is an incorrect interpretation of what is happening by Flow.

`arrayOfArraysVar.concat([arrayVar])` will push (without mutating) an array onto the end of `arrayOfArraysVar`, whereas `arrayOfArraysVar.concat(arrayVar)` will push the values of `arrayVar` onto the end of `arrayOfArraysVar`, no matter what type they are. When `arrayOfArraysVar` is typed as Array<Array<string>>, it will push just string onto the end when it should be pushing Array<string> onto the end.

The only fix I've found for this has been:
```
const before: Array<Array<string>> = etc1().slice(0);
const after: Array<Array<string>> = etc2();
for (let x: number = 0; x < after.length; x++) {
  before.push(after[x]);
}
return before;
```

Which is definitely less cool than the one-line alternative that does the same thing.

**Comment by jcready** [comment]
In your example `a` is an array containing `string | Array<string>`. You didn’t refine that `a[0]` is a `string` instead of an `Array<string>`.
