### ISSUE TITLE
Failed prop type with state?

### ISSUE THREAD

**Issue by riccardopiola** [facebook/flow#5029]
Ok so I recently updated flow to version 0.56 where it requires you to declare your Props and State for React components like so
`Component<Props, State>`

my component is the following:
```
// @flow
import * as React from 'react';
import ReactDOM from 'react-dom';
import RaisedButton from 'material-ui/RaisedButton';

type Props = {
  webProprieties: {
    src: string, // The url to go to
    useragent: 'mobile' | string // useragent, use 'mobile' for shorthand
  },
  autoLoadView: boolean, // Wheter to autoload the webview or display a button
  containerClassName?: string, // classNAme of the <div> container
  buttonSettings?: { // Settings for the button if autoload=false
    label: string,
    labelColor: string,
    backgroundColor: string
  },
  audioMuted?: boolean // Mute the audio
};
type State = {
  loaded: boolean
};

class WebView extends React.Component<Props, State> {
  static defaultProps = {
    containerClassName: '',
    buttonSettings: {
      label: 'LOAD',
      labelColor: '#ffffff',
      backgroundColor: 'rgb(201, 170, 113)'
    },
    audioMuted: false,
    autoLoadView: false
  }
  state = {
    loaded: false
  }
// other methods like render() etc...
}
```
Flow doesn't give me any errors but at runtime React does, with this message:
```
warning.js:33 Warning: Failed prop type: loaded must be true or false

Expected: boolean

Actual: void
```
Now I have a couple questions:
- Why does React complain about Failing propTypes when`value` is a property of `state`? Shouldn't it just check the Props?
- Why does it complain about the property 'loaded' being `void` when I clearly wrote `state = { loaded: false`?

I want to also highlight that the code works just fine and the property state.loaded is indeed set to true at runtime and I get no other error other that this warning

VERSIONS:
 - "flow-bin": "^0.56.0",
 - "flow-runtime": "^0.13.0",
 - "flow-typed": "^2.1.2",
 - "react": "^16.0.0",

OTHER INFO
This is a project running with electron 1.6.10

My setup is basically the exact same as described [here](https://flow.org/en/docs/react/components/#toc-adding-state)

**Comment by riccardopiola** [comment]
Ok I found a fix:
I just remove the flow type State altogether and now it looks like:
```
type = Props {
  // props types
}
class WebView extends React.Component<Props> {
  static defaultProps = {
    // defaultProps, no issue there
  }
  state = {
    loaded: false
  }
}
```
Now flow and React infer the state type from the state declaration in the Component itself

I would like some clarification on whether that this is the expected behaviour or not

**Comment by riccardopiola** [comment]
Ok, new update, my fix isn't really a fix, nor flow or React complain at runtime if I remove the State type from the class declaration.

But now Flow complains in the editor every time I interact with state,
there are error markings in the defaultState definition:
```
state = { 
  loaded: false
}
```
severity: 'Error'
message: 'object literal:  This type is incompatible with 'undefined'. See ./private/tmp/flow/flowlib_8af2734/react.js:27'

when I use setState:
`this.setState({ loaded: true });`'object literal:  This type is incompatible with the expected param type of 'union: undefined | function type'. See ./private/tmp/flow/flowlib_8af2734/react.js:36

and when I just read the state
`this.state.loaded` 'property `loaded`:  Property cannot be accessed on possibly undefined value 'undefined'.

Those are all expected errors since I did not declare a state type

Honestly if there were just a way to disable that annoying warning/error at runtime that I described in the first post I'd just go with that since the app works fine and the problem isn't really a problem, it's just really annoying that it pollutes that console with all those fake errors

**Comment by CharlesStover** [comment]
Have you tried declaring this.state in the constructor for your class?

Default props also has a type in React.Component<DefaultPropsType, PropsType, StateType>, though likely not relevant to this error.

I use the following without problem, so hopefully some change herein will fix your issue:
```
export type PropsType = {
  etc: 'etc'
};
export type StateType = {
  etc: 'etc';
};
class MyComponent extends React.Component<void, PropsType, StateType> {
  props: PropsType;
  state: StateType;

  constructor(props: PropsType) {
    super(props);
    this.state = { etc: 'etc' };
  }

  render(): React$Element<any> {
    return <div />;
  }
};
```

**Comment by riccardopiola** [comment]
It probably works for you because you use a version of flow prior to release 0.53.
As they explain in [this post](https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627) now you can only feed two types to React.Component (if I try to insert a third for DefaultProps it complain it has too many arguments and that the max is 2)

I also tried putting the initial state declaration in the constructor but I get the same exact result.

Oh and by the way I also tried putting the type declaration both next to React.Component and in the class itself (props: Props): doesn't change anything

The situation is kinda weird because:
- the error doesn't affect the application (it works fine), its just annoying to see all those warnings
- the error comes form React but if you just remove Flow and write a component the react way there is no issue
- this error happens only if I use flow >= 0.53 (Different syntax) if I downgrade to 0.48 for example and use the standard props: Props state: State in the class it all works perfectly

Unfortunately I can't really go back to an earlier version of flow because I would have to change a lot of files that I updated when I made the change to Flow 0.56

**Comment by steinarn** [comment]
I am experiencing the same problem (your setup + Electron 1.7.8). The only way I can get the console errors to disappear is to set all my state properties as optional.

`
export type PropsType = {
  etc: 'etc'
};
export type StateType = {
  etc?: 'etc';
};
class MyComponent extends React.Component<PropsType, StateType> {
  props: PropsType;
  state: StateType;

  constructor(props: PropsType) {
    super(props);
    this.state = { etc: 'etc' };
  }

  render(): React$Element<any> {
    return <div />;
  }
};
`

**Comment by riccardopiola** [comment]
I was starting to think I was the only one here, I think I'm gonna keep the types as required and make peace with the errors in the console, now I just load the app and then clear the console as soon as all my components mount, from this point it all works normally.

**Comment by colin-han** [comment]
@riccardopiola you are not only one. me too.  following is the call stack about this warning. Hope to help someone to detect this issue.
```
  | printWarning | @ | warning.js:36
  | warning | @ | warning.js:60
  | checkReactTypeSpec | @ | checkReactTypeSpec.js:78
  | validatePropTypes | @ | ReactElementValidator.js:160
  | createElement | @ | ReactElementValidator.js:214
  | patchedCreateElement | @ | patch.dev.js:164
  | render | @ | connectAdvanced.js:253
  | render | @ | createPrototypeProxy.js:44
  | (anonymous) | @ | ReactCompositeComponent.js:793
  | measureLifeCyclePerf | @ | ReactCompositeComponent.js:73
  | _renderValidatedComponentWithoutOwnerOrContext | @ | ReactCompositeComponent.js:792
  | _renderValidatedComponent | @ | ReactCompositeComponent.js:819
  | performInitialMount | @ | ReactCompositeComponent.js:359
...
```

**Comment by cbazureau** [comment]
@riccardopiola  i think it's linked to this issue on flow-runtime https://github.com/codemix/flow-runtime/issues/149.
