### ISSUE TITLE
Passing a more-specific Object type to a function with a less-specific type.

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5030]
[Reproduction](https://flow.org/try/#0PTAEBUAsEsGdQO4HsBOBreAzaA7ApgHQBQAxkjrAC6gBGoAvKABQCGAXKDgK4C2NeKAJQdufAaAA+oKilwBzBgD5QLANxEiICDHgATJHng4k1ZOmJkK1AJ4NmADw4BvUAG00eaxxnyAuiN5+FFAAX2FQF3dPb0pZHDl-TkDxKR940KVQe3UgA)

I'm trying to pass an Object with specific values (some number, some string) as a prop to a component that accepts any Object with numbers or strings as values, except I'm getting the error "number (This type is incompatible with strings)" and "string (This type is incompatible with number)."

This works fine if you pass specifically a number or specifically a string to a function that accepts number | string, but if you try to do this with Objects, you get this error.

Any advice? Is this a bug, or am I missing something obvious?

**Comment by AugustinLF** [comment]
This is a common error, Flow consider that your function could mutate your data, you can make it work by [annotating your object as covariant](https://flow.org/en/docs/lang/depth-subtyping/) see this correct [example](https://flow.org/try/#0PTAEBUAsEsGdQO4HsBOBreAzaA7ApgHQBQAxkjrAC6gBGoAvKABQCGAXKDgK4C2NeKAJQdufAaAA+oKilwBzBgD5QLANxEiICDHgATJHng4k1ZOmJkK1AJ4NmADw4BvUAGoA2mjzWOM+QF0RXn4UUABfYVAXDy8faUpZHDlAzmDxKT8k8KVQe3UgA) :)

**Comment by CharlesStover** [comment]
More specifically, I cannot get this to work with arrays:

```
type Specific = { a: number, b: string };

type Not = { +[key: string]: number | string };

const a: Specific = { a: 1, b: 'two' };
const b: Not = a;

const c: Array<Specific> = [a];
const d: Array<Not> = c;
```

The value I am passing as a prop to my component is Array<Specific>. The component itself has a PropType of Array<Not>.
The errors it's throwing are of no use. Despite changing it to covariant, I still get errors.

message: 'object type (This type is incompatible with object type Property `propertyName` is incompatible:)'

message: 'object type (Covariant property `propertyName` incompatible with invariant use in object type)'
