### ISSUE TITLE
How can you put type for async function?

### ISSUE THREAD

**Issue by dmrg2** [facebook/flow#5032]
Hello, I have a problem with async function and its type checking. For my function, it accepts async function as an argument.

`
export type myFunc = () => mixed;
...
const result = myFunc(asyncFunc());
`

It complains "async function. This type is incompatible with function."... How do you put type for async function? Is it available? AsyncFunc uses async/await.

**Comment by CharlesStover** [comment]
async/await I believe are just shorthand for promises, so your type will likely be Promise<Type>.

**Comment by dmrg2** [comment]
Thank you @CharlesStover    I tried following but it still complains even though I use Promise. Here is my full codes.

`
export type Action = { type: string};
export type Dispatch = (action: Action | Promise<Action>) => Promise<Action>;

...

dispatch(asyncFunc());
`

It gives me the same error: "asyncFunc is async function. This type is incompatible with Promise."

**Comment by CharlesStover** [comment]
asyncFunc is not a Promise<Action>, but a function that returns a Promise<Action>.

My asynchronous actions are as such:
`(dispatch: DispatchType, getState: () => ReduxStateType) => Promise<void>`

But it also depends on how you structure them. I wrote the action creator myself, so it may differ from whatever you are using.
My Promises do not return in my instances, as they just `dispatch(actionCreator())` as opposed to `return dispatch(actionCreator())`, which I believe would have the return type of Action that you are using.

**Comment by dmrg2** [comment]
Thank you so much @CharlesStover I think I fixed it!
