### ISSUE TITLE
`hydrate` method definition is not in `react-dom`

### ISSUE THREAD

**Issue by gabehayes** [facebook/flow#5035]
The definition for the new `hydrate` method in React 16 is not yet defined.

Given:
```
import { hydrate } from 'react-dom';
```

You will get the error:
```
Named import from module `react-dom`
This module has no named export called `hydrate`.
```

**Comment by JustFly1984** [comment]
I get this error in my project. Please help.

**Comment by gabehayes** [comment]
@JustFly1984 until this is patched, you can get around with the [suppress comment](https://flow.org/en/docs/config/options/#toc-suppress-comment-regex) which I believe defaults to `$FlowFixMe`.

**Comment by callumlocke** [comment]
I think this is an issue for react-dom, not Flow. Reported at https://github.com/facebook/react/issues/12175

**Comment by mrkev** [comment]
Added in https://github.com/facebook/flow/pull/5074
