### ISSUE TITLE
A type that says "must be nullable"

### ISSUE THREAD

**Issue by cakoose** [facebook/flow#5036]
In our codebase, we have an older utility function `every` with the following flow type:

```typescript
declare function every<V>(object: {[key: string]: V}, predicate?: V => boolean): boolean;
declare function every<V>(array: $Exact<?Array<V>>, predicate?: V => boolean): boolean;
```

We want to switch from using `every` to using `Array.prototype.every` in cases where the first argument is definitely not `null`/`undefined`:

```typescript
function f(a: ?Array<number>, b: Array<number>) {
    // This is ok:
    console.log(every(b, i => i > 1));
    // We want this to be disallowed in favor of 'a.every(...)'
    console.log(every(a, i => i > 1));
}
```

I wanted to see if I could get Flow to help find these cases.

I tried adding another overload to "catch" the non-nullable call-sites and return some garbage type:

```typescript
declare function every<V>(array: Array<V>, predicate?: V => boolean): $GarbageType;
```

But `$GarbageType` isn't a real thing, so this doesn't work.

I tried using `$Exact`, hoping it would disable subtyping for union types as it does for object types:

```typescript
declare function every<V>(array: $Exact<?Array<V>>, predicate?: V => boolean): boolean;
```

That didn't work either.

**Comment by popham** [comment]
Try `$NonMaybeType<Array<V>>`. I always go straight to `src/typing/type_annotation.ml` for the current set of utilities.

**Comment by asolove** [comment]
I can’t think of a way to do this directly in terms of flow. You might be able to write it as a longing rule that works by walking the ast?
