### ISSUE TITLE
Extending classes with proxied constructor causes false positive

### ISSUE THREAD

**Issue by kusmierz** [facebook/flow#5037]
Let's start from example:

```js
class Foo {
  constructor() {
    return new Proxy(this, {});
  }
}
class Bar extends Foo {}

const bar1: Foo = new Bar();
const bar2: Bar = new Bar();
```

which seems to be 100% correct from JS point of view, see http://runkit.com/akusmierz/github-facebook-flow-5037.

But for some reason, Flow thinks the Bar instance is only inherited from Foo...

https://flow.org/try/#0MYGwhgzhAEBiD29oG8BQ1rHgOwgFwCcBXYPeAgCgEoV0NoCBTPIg7abRgd2gAUD4ADwCeFPAAsAlhAA0KAL5UA3HXmo1oSDABCYAtEaC8jbABMYCJMjWosuPNABGegIwAuOImgBeDt2i6lMq2OPhOegBMHoE+fjyB1EpAA

**Comment by SamChou19815** [comment]
We now decide that non-void return of class constructors won't be supported
