### ISSUE TITLE
Type annotations (props) for components don't work 

### ISSUE THREAD

**Issue by aloifolia** [facebook/flow#5038]
I have the following code in my React Native app:

```javascript
type Props = {
  value: number,
};

class Foo extends Component<Props> {
                  ^^^^^^^^^ ^^^^^
  render() {
    return <Text>{this.props.value}</Text>;
  }
}
```
I am just getting started with flow type annotations. So maybe I am missing something crucial. Flow complains with the following error messages (VSCode shows 2):

```
[flow] object type (This type is incompatible with undefined. Did you forget to declare Props?)
[flow] undefined. Did you forget to declare Props? (This type is incompatible with object type)
```

I am using
```
flow-bin: 0.56.0
react: 16.0.0
react-native: 0.49.1
```
However, these messages already occurred before I updated (i.e. with flow-bin 0.49).

**Comment by CharlesStover** [comment]
I am getting [no errors](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQnMAnmEjgAFemADOcALy5OcOADcUAGwCuSAFxwSKkACMkUTJ0pdOaJSjESAYhAhwkADxjkAJhMLEyFADwiI4gB8MnIsJK4GABQAlCFycCwwKlAkcD6uwPKBODAAFsBiAHRgokWKqkiUPgD0GVlccpTGnEA) for this code.

**Comment by aloifolia** [comment]
OK, I just re-checked my example. As soon as I add additional type arguments for DefaultProps and State, the error messages vanish:

```javascript
class Foo extends Component<void, Props, void> {
```
