### ISSUE TITLE
Cannot make tuple flow to array

### ISSUE THREAD

**Issue by ryanscottaudio** [facebook/flow#5040]
I'd like to pass a tuple to a function that takes an array and uses Array.find(), but I'm not sure how to do that without having a tuple vs. array type mismatch. To my knowledge there's no way to do `Tuple<*>`, so I'm at a loss here; I'd rather not have to use `any`.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgByArgLYBGeATmALxgCMYAPmAEwtgDMA3JrgRIVqAZwAqxHDAL0A2kTKUqAGgXCVapWAC6fVAGM4AOxEYwUAJZGAJlzpgAFKjBgji0QC4wAQSpUAhlgAPEJKAHzKqACUXqHUnABucBbWdGGu7lQiAHSWNg5u6mkZRbRl3FF6hiZmhUoisZniktL2sgyqbKpcuuh5tgVNlUA

**Comment by vkurchatkin** [comment]
You can't pass tuple instead of `Array`, because arrays are mutable, which means that you can do e.g. `array.pop()`, which might invalidate the tuple. If you switch `Array` to `$ReadOnlyArray`, it'd work.

**Comment by ryanscottaudio** [comment]
that's great, thanks!
