### ISSUE TITLE
flow generic type for function expression

### ISSUE THREAD

**Issue by norbertpy** [facebook/flow#5045]
I asked this [flow generic type for function expression][1] question on stackoverflow then I noticed that I get the error in [flow.org/try/#0C4TwD...][2] but if I run `flow check` on the file with the same content it retrurns `0` error. Is this a bug in `flow/try`?

Basically I wanna have generic function type separate from my function definition:

```javascript
type H<T> = (input: T) => T;
const h:H<*> = i => i;

const hString: string = h('apple')
const hNumber: number = h(7);
```

[1]: https://stackoverflow.com/q/46596235/4228942
[2]: https://flow.org/try/#0C4TwDgpgBAEgPAFQHxQLxQBQEsB2YCuwAXFAgJRooIDcAUAMYD2OAzsFABZHwBUK6WSlCx0GzNpwDKwAE64A5iTZyc8tJwwByAIZgwAGwiayY1uw4A5fAFsARhBkkcN+zPUcMAdjKjaAM3wcemAsZigAK0QkbDxCEnJ4qABvWigoGQhgfBkcYVjgOgBfWlMJcOkVRShlBXVwrV0DIx9S9nCrOwcnFwc6rx8gA

**Comment by norbertpy** [comment]
It actually returns an error with `flow check`. So this is now more of a question than bug report.

**Comment by norbertpy** [comment]
Here is the weird [answer](https://stackoverflow.com/a/46840629/4228942)

**Comment by ndreckshage** [comment]
this stopped working in flow 0.72 :/

https://flow.org/try/#0C4TwDgpgBAEgPAFQHxQLxUQLigKiQCgEsA7MAV2GwQEo0UEBuAKAGMB7YgZ2CgAtN4eNFEJ0RzVh258AysABOJAObZui4kuG98AcgCGYMABsIO6pK49eAOTIBbAEYR52Yvafyt+AOzUGQA
