### ISSUE TITLE
code style of writing object types

### ISSUE THREAD

**Issue by itamar244** [facebook/flow#5046]
I have found two code styles of writing object types separators.
```javascript
// the comma way
type Foo = {
  bar: string,
  baz: string,
}

// the semicolon way
type Foo = {
  bar: string;
  baz: string;
}
```
which is the more common or better way?

**Comment by apsavin** [comment]
> you should use commas

https://flow.org/en/docs/types/objects/#toc-object-type-syntax

**Comment by itamar244** [comment]
thanks
