### ISSUE TITLE
`Property cannot be accessed on possibly undefined value` when access to object's key of map

### ISSUE THREAD

**Issue by sottar** [facebook/flow#5047]
When I access to object's key of map, the error that is ``` Property cannot be accessed on possibly undefined value ``` has occurred, even checked the map has key.

example code.
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFsAuMAWQEMAHAHgICcBLbAcwBowBvAawFMAnmUYtWAXwB8YALxhsfJFWoAKANqowYdZs0BySrvYadXMPyFhdAN0owArnwCCusGOMBdI5u07dAI0NjTVNzMmtbBwAhFzdNT1R3AEoAbnQmKDBlIgA6AAtKXGV9XUTE7mMsPEIbGABGYXxmNhlibNY+fCKDROzzVLdMHAIwGoBmBqbWFpz8wuKygH5W9s753sEwMN1UoA
Do you have any solutions to resolve this errors?

**Comment by jcready** [comment]
Flow doesn't count `Map#has()` as an actual predicate. Here's the workaround:

```js
const a = m.get('a')
if (a) {
  const val1: string = a.key;
}
```

**Comment by sottar** [comment]
I see. Thanks!

But val1's scope is in the ```if``` block by your code.
And here's not smart.
```js
const a = m.get('a')
let val1: string = '';
if (a) {
  val1 = a.key;
}
```
This is a tough one...

**Comment by jcready** [comment]
You can use a ternary:

```js
const a = m.get(‘a’)
const val1 = a ? a.key : ‘’
```

**Comment by sottar** [comment]
Surely!! Thanks ;)
