### ISSUE TITLE
Support for JSXSpreadChild

### ISSUE THREAD

**Issue by rattrayalex** [facebook/flow#5053]
Flow [does not yet parse](https://astexplorer.net/#/gist/12ae97958b0367dbc8d77c9c28058b16/16033faf078d8be79dda19259b3657eff15b4b7a) `JSXSpreadChild`, which [was added to JSX](https://github.com/facebook/jsx/pull/59) a while ago. It's also [in babylon](https://astexplorer.net/#/gist/12ae97958b0367dbc8d77c9c28058b16/783fa5a2e3b5cf2641a02203a391fd82ee72abb9) but not yet [esprima](https://github.com/jquery/esprima/issues/1819) or [acorn](https://github.com/RReverser/acorn-jsx/issues/75). 

```jsx
<Foo>{...children}</Foo>
```

cc @calebmer

**Comment by calebmer** [comment]
Yeah, lol, I wrote the PR to get this added to the spec 😊. Is there somewhere you would like to use this? This syntax is banned in React which is why we’ve been slow to support it.

**Comment by rattrayalex** [comment]
Banned in React? 

I was hoping to use it in a compile-to-js lang I'm working on, [LightScript](http://lightscript.org), which would use the syntax for "jsx comprehensions" (eg; `[...for x of arr: [x * 2]]` is valid LightScript, and I would like `{...for x of arr: <X x={x} />}` to be valid as well). 

In other words, I have no pressing need for this 😄

**Comment by TrySound** [comment]
Seems like this was introduced in [0.60](https://github.com/facebook/flow/blob/master/Changelog.md#parser-2)

This probably can be closed.
/cc @vkurchatkin
