### ISSUE TITLE
Intersection of inferred return types

### ISSUE THREAD

**Issue by AndersDJohnson** [facebook/flow#5056]
I can't get Flow to respect a type that's an intersection including inferred return types.

Using the extract return type trick from https://github.com/facebook/flow/issues/2618#issuecomment-253950975.

Major use case is for React + Redux apps so we can automate definition of `Props` for use in `React.Component` based on the return values of `mapStateToProps` and `mapDispatchToProps`.

Here's an example of an error not being detected when intersecting two inferred return types:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeGArgE4B2A+gDyEA0YAYgFxgAUAdDwIbkBzAM7sAguXK8stXpSwA+AJRgAvPKLqVRANyZcBYmSq0AKpqIkKNWiCZndYMHvxgAyhl4YCWgN6pHUHBw7JSkALYARnjkqAC+uqgAxnCUQhhgYbw47p54JnAACuRwOEKqnGm57DleymqcfgHslV5cgXBxignJqemZOAAiAJZCOJ6JABb5RSVlWhx16o1gvOwLquoA5LybcQnAwGAmEyNgieMTeGUABjjFpW1B16yoB9guM6Xlhla073hwKAZLI1PKFe5CeS6A5gABCpHSGBOZQAJnArpRNhgXv8wJ85hYjJQ-vpAcDsh4vNMIeoAGSE37-Mn9YajC7U2ZQ9A9NJgO6zdj41SoZY8Lj9UEc0ocZYBILsABMDH8jjAEX4a0WYE2J12jliimVjjFLJGYwwkylQgWe3Q-IeQIA1GAAIyvQ6uCZwUgwFFnC5gJEjF72oSPOBgZ1uoA

Or even when intersecting an inferred return type and a regular object type:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeGArgE4B2A+gDyEA0YAYgFxgAUAdDwIbkBzAM7sAguXK8stXpSwA+AJRgAvPKLqVRANyZcBYmSq0AKpqIkKNWiCZndYMHvxgAyhl4YCWgN6pHUHBw7JSkALYARnjkqAC+uqgAxnCUQhhgYbw47p54JnAACuRwOEKqnGm57DleymqcfgHslV5cgXBxignJqemZOAAiAJZCOJ6JABb5RSVlWhx16o1gvOwLquoA5LybcQnAwGAmEyNgieMTeGUABjjFpW1B16yoB9guM6Xlhla073hwKAZLI1PKFe5CeS6A5gABCpHSGBOZQAJnArpRNhgXv8wJ85hYjJQ-vpAcDsh4vNMIeoAGRgZarFikSiJDBDFJ7dA9NJgO6zdj41SoZY8Lj9UHU2YcZYBILsABMDH8jjAEX4a0WYE2J12jliimVjjF-WGowuUtKCy5qH5DyBAGowABGV6HVwTOCkGAos4XMBIkYvO1CR5wMBO11AA

Compare to intersection of regular object types, which does detect the error:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeGArgE4B2A+gDyEA0YAYgFxgAUAdDwIbkBzAM7sAguXK8stXpSwA+AJRgAvPKLqVRANyZcBYmSq0AKpqIkKNWiCZndYMHvxgAyhl4YCWgN6pHUHBw7JSkALYARnjkqAC+uqgAxnCUQhhgYbw47p54JnAACuRwOEKqnGm57DleymqcfgHslV5cgXBxignJqemZOAAiAJZCOJ6JABb5RSVlWhx16o1gvOwLquoA5LybcQnAwGAmEyNgieMTeGUABjjFpW1B16zOBDOl5T5gUCHhUeRgWJgABkYC+qxYpEoiQwQxSgO6KTSYDus3Y7zmqGWPC4-RqeUK9yEHGWASC7AATAx-I4wBF+GtFmBNiddo5YopqY4cf1hqMLtMiQs9uhUQ8oGAANRgACMqDFQkecClstQQA

**Comment by jtbandes** [comment]
I'm also having problems with **unions** of inferred return types:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgD6AogB4YBOAhgMYYBKeGArhQHYA8AQgDRgBiALjAAKAHQSqFAOYBnYVTZYA2gF0AlGAC8APjBc9W-QG5UeUjjgUMYbPjBlKtBk1ad+hoo+p1GLdhwgfB6mqDRwbLI2ABrCAOTRcdpgCXGm4ZE2AJrxWUlGcXmhwMAwTGAAXsLRyXF4FBRWaegZUWBUpMkA3lTVAL7pEW1UWN29YFkD6CVlNlRVtrh4cFDtnQA+i-gr7aNGPfH1jRRxU2FDc6SrRiKauqIHYNF96oOZu9eid3oij5Ov01K5XmAAZhN5nH43Bw7MtVh0oJ5HnUGk0pjNgRUAIzg8g+Fz+TiwnYjRFjQ6ok5TWbtCoAJlxTl8rgCxPhVz0mwhzMJMKWJKwZP24zibDgYCOVgA-DLTqYgA

**Comment by SamChou19815** [comment]
Closing since `*` is no longer supported
