### ISSUE TITLE
HOC: type parameter `Props` of function call. Missing annotation

### ISSUE THREAD

**Issue by eelkeh** [facebook/flow#5064]
```javascript
type ButtonProps = {
  children: React.Node,
  href: string,
  onClick: Function,
};

const Button = (props: ButtonProps) => (
  <a href={props.href} onClick={props.onClick}>
    <button
      type="submit"
    >
      <span>{props.children}</span>
    </button>
  </a>
);

function hoc<Props: {}>(
  Component: React.ComponentType<Props>,
): React.ComponentType<Props> {
  return function WrapperComponent(props: Props) {
    return <Component {...props} />;
  };
}

export default hoc(Button);
```

What I'm trying to achieve is a generic higher order component that can wrap _any_ class component as well as stateless functional components. Above simplified implementation is pretty much taken from https://flow.org/en/docs/react/hoc/.

This gives me the following error, which I don't fully understand as I'm under the impression that I'm following the example supplied in the docs:

```
type parameter `Props` of function call. Missing annotation
```

**Comment by apsavin** [comment]
Can you reproduce it on [try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQMAnmFnAEICuMMEAdgArEw6ALxwA3nThxcAC2AAbACaVeALkxUYAOgByEJVgA0UuLMoENqGFGC8A5iel8AwguC4A1hoBiHXvjAfCYAvvR0uHzW7Fw8vHBiABRgQqganNx8ghDCAJQJAHxwiaYAPMhmFiLiKTmo2uZYBCFwru5e1bXC2m0eniEFptKlAEaxfEPScEwsIgBEqBwjIMAwc5ODU1OlqGDIvAU1qdpyiipYvCGlAPS7+5vb12OZB2XXyIO54QT+gXxmEFwpWywg04gGJWkLhIkF4FxgGmweB00PAfHhABVmFhgakCiZcoitNpUbDMdjcXUipJpJQYBwoPEfgEYEF4gB1KDIMAsKCk9G8GDJVIaEGofI0qZ0hnxUr8uGCiTaZVdVAta4FejSMJ0EJAA) ?

**Comment by eelkeh** [comment]
[Reproducable example](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQMAnmFnAEICuMMEAdgArEw6ALxwA3nThxcAC2AAbACaVeALkxUYAOgByEJVgA0UuLMoENqGFGC8A5iel8AwguC4A1hoBiHXvjAfCYAvvR0uHzW7Fw8vHBiABRgQqganNx8ghDCAJQJAHxwiaYAPMhmFiLiKTmo2uZYBCFwru5e1bXC2m0eniEFptKlAEaxfEPScEwsIgBEqBwjIMAwc5ODU1OlqGDIvAU1qdpyiipYvCGlAPS7+5vb12OZB2XXyIO54QT+gXxmEFwpWywg04gGJWkLhIkF4FxgGmweB00PAfHhABVmFhgakCiZcoitNpUbDMdjcXUipJpJQYBwoPEfgEYEF4gB1KDIMAsKCk9G8GDJVIaEGofI0qZ0hnxUr8uGCiTaZVdVAta4FejSMJ0EJ0OhYAAekFgcEMBGQHAU8FkgMSGTiXyAA)

**Comment by eelkeh** [comment]
Is this a known bug?

**Comment by zgotsch** [comment]
See also this example: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdBArgHb7AQtzAsBWW+AArEwAHmEQwqAFxwA3gF8AfAAo6cOAGESkFlhYxZ2PDAB028J30wAKgE8wWUXLgEIEWSyYgARlihwCnAAZHASUkoANHQAlEZUZha61vaO4iKoSvLqcJQwTFBczGwwHFwA6lDIYI5QSVYGKmAZsuGoMdkaGnkFXKL1egbypiPNkqhBbhAAvHIALABMQQD0SvQaCvQKDLgANmjoALJ2A9ZwWAAeMPoAJujG+OY6DTDOOcie3n5Q0Ro+n75-L9XO4Ad9osp5Ns6LhOKh4McAKIsAAWyDYWBupyG024fAEMHCKmO2JgMXodGWyzg5SwcBunDI8D0mLgMAgcDABzxcAABlNeecAG76NkoiBMADmKL5JOegxggsoAEcmMBKOhgGY6KIkaj0bhMaSULMAIxBHyzJZwVYUy6QWD0rAEZBMXYIuzItEYrHy6w0IA

Which is literally the example given in the docs.

It is possible to export the HOC and use it in other modules without a Flow error.

**Comment by SamChou19815** [comment]
now it works
