### ISSUE TITLE
Passing object as polymorphic object-as-map produces error at the wrong place

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#5066]
Consider: 
 
```js
type ObjType = {
  n : number,
  s : string
};

declare var x : ObjType;

function asMap<T>(x : { [string] : T }) {};

asMap(x);
```

Gives as output:

```
2:   n : number,
         ^ number. This type is incompatible with the expected param type of
3:   s : string         ^ string
3:   s : string         ^ string. This type is incompatible with the expected param type of
2:   n : number,
         ^ number
```

As you can see, flow only points to the `ObjType`, and not to the call to `asMap` (this has cost me many hours in a real-world code base).

(aside: theoretically I see no reason why flow should not accept the above program, although I can image that flow cannot represent the type that T should resolve to. )

**Comment by SamChou19815** [comment]
now errors in the right place
