### ISSUE TITLE
How to allow a specific element, but also allows elements that return that specific element when rendered

### ISSUE THREAD

**Issue by JCMais** [facebook/flow#5068]
ref https://github.com/flowtype/flow-typed/issues/1237#issuecomment-335341925

On https://flow.org/en/docs/react/children/#toc-only-allowing-a-specific-element-type-as-children it's shown how to allow only one children of specific type, but what about if my component returns that exact type?

Let's say I want to only allow Text elements and scalar values for the react-native Text element, so we have:
```flow
type ReactOnlyElementTypeAsChildren<T> = void | null | boolean | number | string | React$Element<typeof Text>;
```
This works great, if I do:
```
function DumbComp() { return <View></View>; }
function MyComp() {
  return <Text><DumbComp>{/* ... /*}</DumbComp></Text>
}
```
it throws an error as expected
```
 Error: test.js:8
 22:       <Text><DumbComp>{/* ... /*}</DumbComp></Text>
                  ^^^^^^^^^ exact type: object type. This type is incompatible with ....
```
But what if my component returns a `<Text>` element? like
```
function DumbComp() { return <Text></Text>; }
```
The error is still there, as expected. But is there any way to make flow understand that?

**Comment by JCMais** [comment]
Bump, any ideas?

**Comment by TrySound** [comment]
@JCMais 
```js
function DumbComp({ children }) { return <Text>{children}</Text>; }
```

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by vkurchatkin** [comment]
@TrySound this seems like a valid feature request. As far as I know, there is no good way to do this.

**Comment by SamChou19815** [comment]
Now supported with render types
