### ISSUE TITLE
ignore flow issues from node_modules that aren't a direct dependency of the current project

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/flow#5069]
I've been following https://github.com/facebook/flow/issues/869 and I agree that ideally flow is less noisy about 3rd party code from the start. I think one thing that attracts a lot of people to flow is that they can add types slowly vs. having to fully adopt typescript.

One thing I've thought that might be nice is to only have flow check things in node_modules that are requirements of the current project. Right now I see flow errors from modules that I don't use, they are just used by things I use. This might be a good way to reduce some of the noise while not reducing any functionality.

**Comment by Vadorequest** [comment]
You could also had "node_modules" to the ignored folders in the .flowconfig file.

**Comment by TrySound** [comment]
This should be fixed in v0.57

This probably can be closed.
/cc @vkurchatkin
