### ISSUE TITLE
Can you use Flow with Node.js scripts/apps?

### ISSUE THREAD

**Issue by brycepj** [facebook/flow#507]
I just heard about Flow and am trying to wrap my head around it. What considerations would I need to take differently using this for a Node app, rather than browser code?

**Comment by jeffmo** [comment]
Node should work for node apps as well as browser apps (we assume the node/npm name resolution algorithm for modules by default).

We ship interface definition files for both web APIs and Node modules with Flow. It's worth noting that  these interface definitions have been filled out for the most part, but may not be fully complete. If you do run into some part of the interface definitions that we haven't built yet hopefully it should be easy to send that in as a PR: https://github.com/facebook/flow/blob/master/lib/node.js

**Comment by jeffmo** [comment]
Feel free to re-open this if you have more questions!

(or hop in #flowtype on irc.freenode.net if you want chat more directly)
