### ISSUE TITLE
Disjoint union - incorrect refinement to `any` for unknown keys

### ISSUE THREAD

**Issue by swansontec** [facebook/flow#5071]
Here is an ordinary disjoint union type:

```js
type Action =
  | { type: 'BLAH', payload: string }
  | { type: 'FOO', payload: number }
```

Trying to use the `payload` without refinement gives type errors, as expected:

```js
function error (action: Action): number {
  return action.payload // $ExpectError (string | number is incompatible with number)
}
```

*However*, if we refine the type using an invalid key, obvious type errors pass the checker:

```js
function noError (action: Action): number {
  if (action.type === 'OOPS_A_TYPO') {
    return action.payload // Should error, but passes!
  }
  return 0
}
```

Expected behavior: There is no refinement, so the payload remains `string | number` and an error occurs.

**Comment by swansontec** [comment]
I am also open to workaround ideas on this one.

**Comment by lll000111** [comment]
Well, the return of a number is guaranteed in your example, the refinement actually works: The `payload` is never returned. The error should be a different one, the entire `if` is redundant because it is `if (false)`.

**Comment by swansontec** [comment]
It looks like the latest version of flow (0.58.0) now throws an error for the original example:

```
if (action.type === 'OOPS_A_TYPO') {
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ object with property `type` that matches string literal `OOPS_A_TYPO`. This type is incompatible with
 11: export function noError (action: Action): number {
                                      ^^^^^^ union: object type(s)
```

With this in place, I think it is safe to say that this is no longer an issue - this is now invalid code, so it doesn't matter *what* Flow infers inside the `if` block.
