### ISSUE TITLE
Why there is no an error?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5072]
```
type Letters = { type: 'vowels' | 'consonants' };
function handle(letters: Letters) {
    switch(letters.type) {
        case 'xxx': return 'xxx';
    }
}
```

https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQN5VJAXFAOQBuA9gO4QA2KRUAPsQMZkB2K7Ahm8HVAF8A3ACgAZgFc2zYAEt2UABY8AJtQgAKdQmQpCcHagCU2EVHNQUFWcGaKt8RKgB0eCCaxmL35lxTQiAA9gokIkeAkkNmJgwKJRbwERASA

**Comment by TrySound** [comment]
Because your code is correct, however has one dead brunch.

https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQN5VJAXFAOQBuA9gO4QA2KRUAPsQMZkB2K7Ahm8HVAF8A3ACgAZgFc2zYAEt2UABY8AJtQgAKdQmQpCcHagCU++IlTYRUa1BQVZwZoq1ndAOjwQjlm76jMuFGgiAA8wokIkeAkkNmIwkKJRXwERASA

**Comment by budarin** [comment]
your code is not correct - return type of the function not a Letters type - just string
https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQN5VJAXFAOQBuA9gO4QA2KRUAPsQMZkB2K7Ahm8HVAF8A3ACgAZgFc2zYAEt2UABY8AJtQgAKdQmQpCcHagCUhAPwpgSWWwDm2EVEdQUFWcGaKt8RKgB0eCCN7JxCoZi4UaCIAD1iiQiR4CSQ2YljoolEQgREBIA

why there is no an error in case of 'xxx'???
there is no this value in Letters

**Comment by apsavin** [comment]
Well, you can try [this](https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQN5VJAXFAOQBuA9gO4QA2KRUAPsQMZkB2K7Ahm8HVAF8A3ACgAZgFc2zYAEt2UABY8AJtQgAKdQmQpCcHagCUhFMCSy2Ac2wio9qCgqzgzRVviJUAOjwQjtg5BUMxcKNBEAB7RRIRI8BJIbMTRkUSiQQIiAkA)

But you will be not satisfied [anyway](https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQN5VJAXFAOQBuA9gO4QA2KRUAPsQMZkB2K7Ahm8HVAF8A3ACgAZgFc2zYAEt2UABY8AJtQgAKdQmQpCcHagCUhFMCSy2Ac2wio9qCgqzgzRVviJUAOjwQjtg5BUMxcKNBEAB7RRIRI8BJIbMTRkUSiAJBBoeHE5FS0sVDxwInJRFxkEul2wfY5Eawc3Lx0cQlJxCgqSMA1QQIiAkA) I'm afraid.

Flow isn't ideal, there is a lot of work to do.

**Comment by budarin** [comment]
wrong sample - if i comment the case with ''xxx' - the error is there

**Comment by apsavin** [comment]
Sure, it's what I wanted to show by the second link.

**Comment by budarin** [comment]
I am not about it - here correct code about returned type

```
type Letters = { type: 'vowels' | 'consonants' };
function handle(letters: Letters): string {
    switch(letters.type) {
        case 'vowels': return 'xxx';
	case 'consonants': return 'xxx';
        case 'xxx': return 'xxx';
      	default: return '';
    }
}
```

https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQN5VJAXFAOQBuA9gO4QA2KRUAPsQMZkB2K7Ahm8HVAF8A3ACgAZgFc2zYAEt2UABY8AJtQgAKdQmQpCcHagCUhFMCSy2Ac2wio9qCgqzgzRVviJUAOjwQjtg5BUMxcKNCklDR0hEjwEkhsxAAeqUSiAJAZoeEs7JxsPHxEsfGJKWmiwQ45EanJJVBxwAlJRPXpdsEZKhBiXBLUwKUt5USdQQIiAkA

but there is no an error at ''xxx'

**Comment by apsavin** [comment]
Hmm, [this](https://flow.org/try/#0C4TwDgpgBAMhzAgJwM5QLxQOQDcD2A7hADYpZQA+2AxngHYr0CGdwZA3AFAAmE1xTJNByCoxeIlQAuWBOQouKAgEtg1ABYAKcQnkBKKAG9OUKNSYpoWAB62sM2gzziAdMTwBzTTbt6up80tsfCJSezN6Rld3Lx9rLD8TMwsrR0Y6FjZwtOcIN09vW3jEgF8gA) behaves correctly.

**Comment by apsavin** [comment]
Looks like a bug for me.

**Comment by TrySound** [comment]
@budarin @apsavin  It's not a bug. This code in runtime will never fail with correctly passed types. So nothing is wrong. Unreachable code is different type of analysis. Flow support it in quite limited way yet. Also this was already mentioned a few types in issues.

**Comment by budarin** [comment]
@TrySound thanks!
I've caught it!
