### ISSUE TITLE
React flow errors in new repo

### ISSUE THREAD

**Issue by altano** [facebook/flow#5073]
I must be daft but I can't get flow working in my new repo:

1. `create-react-app flow-react-test`
1. `cd flow-react-test`
1. As per the [create-react-app instructions](https://github.com/facebookincubator/create-react-app/blob/master/packages/react-scripts/template/README.md#adding-flow):
    1. `yarn add flow-bin`
    1. Add `"flow": "flow"` to the scripts section of my package.json.
    1. `yarn flow init`
    1. Add `// @flow` to src/App.js and src/index.js
1. `flow check`: 
```
PS C:\src\flow-react-test> flow check
Error: src/App.js:7
  7: class App extends Component {
                       ^^^^^^^^^ identifier `Component`. Too few type arguments. Expected at least 1
 27: declare class React$Component<Props, State = void> {
                                   ^^^^^^^^^^^^ See type parameters of definition here. See lib: C:\Users\alan\AppData\Local\Temp\flow\flowlib_2ee226c7\react.js:27

Found 1 error
```
1. Change `App` declaration to `class App extends Component<void>`
1. Re-run flow:
```
PS C:\src\flow-react-test> flow check
Error: src/index.js:9
  9: ReactDOM.render(<App />, document.getElementById('root'));
                     ^^^^^^^ React element `App`
  9: ReactDOM.render(<App />, document.getElementById('root'));
                     ^^^^^^^ props of React element `App`. This type is incompatible with
  7: class App extends Component<void> {
                                 ^^^^ undefined. See: src/App.js:7
Found 1 error
```

I got stuck here. How are no props incompatible with a Props type of `void`? What should I be doing instead?

**Comment by apsavin** [comment]
`class App extends Component<{}>` will work.

**Comment by altano** [comment]
That works but is not correct. That allows me to specify invalid props, e.g. this compiles:
```js
ReactDOM.render(<App face="TRUE" />, document.getElementById('root'));
```

**Comment by apsavin** [comment]
Try [this](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugIJhhxYAeMWAOwAm6bHhgA6AMIlIAwTAA8AbwA+qgL4A+OMroaGjCANTxkcALxwAFIo5cA9FoCU9IyfgAjSzbuc4BHhYFgBEACoYAKoAoiFwTq5AA)

**Comment by altano** [comment]
Oh yeah okay I guess that makes sense, so the properties in the JSX get transformed to a JS object and that is compared to the type, which needs to be an exact object type to have it error on my extra property. That makes sense, I just didn't think about it in those terms.

I've seen no documentation that mentions this: should [the React section of the flow docs](https://flow.org/en/docs/react/components/) be updated to include the no-props case and a section advocating using exact object types or is it there and I'm not seeing it?

And thank you so much for your help, @apsavin
