### ISSUE TITLE
Comparison of typeofs does not validate Flow types

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5076]
[Try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQMAnmFnAEICuMMEAdgArEw6ALxwA3nThxcAC2AAbACaVeALkxUYAOgByEJVgA0UuLMoENqGFGC8A5iel8AwguC4A1hoBiHXvjAfCYAvvR0uHzW7Fw8vHBiABRgQqganNx8ghDCAJQJAHxwiaYAPMhmFiLiKTmo2uZYBCFwru5e1bXC2m0eniEFptKlAEaxfEPScEwsIgBEqBwjIMAwc5ODU1OlqGDIvAU1qdpyiipYvCGlAPS7+5vb12OZB2XXyIO54QT+gXxmEFwpWywg04gGJWkLhIkF4FxgGmweB00PAfHhABVmFhgakCiZcoitNpUbDMdjcXUipJpJQYBwoPEfgEYEF4gB1KDIMAsKCk9G8GDJVIaEGofI0qZ0hnxUr8uGCiTaZVdVAta4FejSMJ0EJ0OhYAAekFgcEMBGQHAU8FkgNKGTiYoKiQdfC+QA)

```JS
// Number comparison
const num1: number = 1;
const num2: number = 2;
const num3: number = num1 < num2 ? 3 : 4;

// String comparison
const str1: string = 'one';
const str2: string = 'two';
const str3: string = str1 < str2 ? 'three' : 'four';

// number | string comparison
const x1: number | string = 1;
const x2: number | string = 2;

// Expected error: number cannot be compared to string in "x1 < x2"
// const x3: number | string = x1 < x2 ? 'three' : 'four';

// No error: typeof x1 matches typeof x2
if (typeof x1 === 'number' && typeof x2 === 'number') {
  const x3: number | string = x1 < x2 ? 'three' : 'four';
}

// No error: typeof x1 matches typeof x2
if (typeof x1 === 'string' && typeof x2 === 'string') {
  const x3: number | string = x1 < x2 ? 3 : 4;
}

// UNEXPECTED ERROR: typeof x1 matches typeof x2
// Received: cannot compare number to string
if (typeof x1 === typeof x2) {
  const x3: number | string = x1 < x2 ? 3 : 'four';
}
```

**Comment by CharlesStover** [comment]
Bumping this for any official response?

I want to be able to compare my strings to strings and numbers to numbers for sorting without it saying that I can't compare my strings to numbers.

**Comment by jdelStrother** [comment]
Anyone found a nice workaround for this?
