### ISSUE TITLE
Shadowing of nested objects with spread is incorrect

### ISSUE THREAD

**Issue by attitude** [facebook/flow#5078]
Following code works but Flow throws error `Property not found in object literal`

Code:
```
/* @flow */

const dP = {
  l: {
    a: '123'
  }
}

const p = {
  ...dP,
  l: {
    ...dP.l,
    a: '12312',
    b: 'adaf'
  }
}

const v = p.l.b
```

Result:
```
18: const v = p.l.b                  ^ property `b`. Property not found in
18: const v = p.l.b
              ^ object literal
```

**Comment by CharlesStover** [comment]
[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqueAjGALxgDeYAMgFw1gCGTAzhgE4CWAdgHMwAXxEBudAGM4fTmAAmABSbF85KtVRh6TTdu1swAclIAmAMxGtI1MPTZ8REqcrNGzQ516CANGABGHNz8QqLCEqjSshhgOCrOrnpgAHSpSj7W7knaqclKyXQZ+qxMJhZmRkX6gcYs8ixQVtp2dpEycgBuQd5CVDgFyf6oQA)

The exact error is occurring on the spread of dP. If you remove ...dP, [your error will disappear](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqueAjGALxgDeYAMgFw1gCGTAzhgE4CWAdgHMwAXxEBudAGM4fTmAAmABSbF85KtVRh6TTdu1swAclIAmAMxGtI1MImYSREqcrNGzQ516CANGABGHNz8QqJ2UjJyOCrOrno6NNbaAHSpSsl0PkmsTCYWZkZZ+gG5LPIsUFbawrb20rIYYABuQd5CVDgZyf6oQA).

There are a lot of weird errors with object spread. You may have to old-school copy your object with something like `for (key in dP)`

**Comment by attitude** [comment]
Thanks, the problem is clear. I would be just nice to have it available :)

**Comment by nmote** [comment]
This no longer errors in master
