### ISSUE TITLE
what's wrong in example?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5086]
```
// Works
function concat(a?: string, b?: string): string {
  if (a && b) {
  	return a + b;
  }
  return '';
}

// Exception!
function concat(a?: string, b?: string): string {
  let o = a && b;  
  if (o) {
  	return a + b;
  }
  return '';
}
```
functions are identical with function but in 2nd example we have errors

**Comment by TrySound** [comment]
@budarin In this moment refinements are not tracked outside of variables. There is operator to mark such case `%checks`, but it's experimental and may introduce more confusing. It's okay to just check conditions in all cases. Code becomes even more readable in most cases.

**Comment by budarin** [comment]
but if condition is big in length - it becomes messy (

**Comment by TrySound** [comment]
@budarin You can split in a few statements or add aliases for properties.

**Comment by budarin** [comment]
it's not clear for me - could you provide a sample, please

**Comment by budarin** [comment]
also calculating conditions as many times as we have cases to check - lead code to slow down

**Comment by TrySound** [comment]
```js
type Data = {
  id: ?string
};
const { id } = data;
if (typeof id === 'string') {
  console.log(id.slice(1))
}
```

**Comment by TrySound** [comment]
It's mostly not a bottle neck, just premature optimization. Javascript is fast enough. You can use typecasting for critical cases by `((prop: any): Something)` after that check, but at first keep still your app readable.

**Comment by budarin** [comment]
sorry, but your sample not about complicated conditions which are to be checked many times
we have a lot of code like this
```
const isCondition = cond1 && cond2 || (cond2 +1 ).toString().length() || ......
...
if (anotherCheck && isCondition) {.....}
if (VeryComplicatedCondition || isCondition) {...}
...
```
and so on - code becomes unreadable in case if we replace all precalculated conditions their full statements

**Comment by apsavin** [comment]
For me it's a bug.

There's an [example](https://flow.org/try/#0GYVwdgxgLglg9mABFATiKALAngCgIYA0iARgJQBcJccANgKZ5ICkEGdEA1gM6IDeAUIkQo6UECiQBCSXkQAyOYmnEA3PwC+-fqEiwEiCAgh4o+SgH4uqGGADmRYhasobtiomeu+gxDGCIcVHRsfAdSUm8hAEgRMQlEWQBqEjUhTSFY8SQAcmy1dSA) of how to use `%checks` just for reference.

**Comment by TrySound** [comment]
@apsavin It's javascript. Don't expect perfect typing in all cases. It's known restriction.
