### ISSUE TITLE
How to pass a generic type that isn't a parameter?

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5088]
I have a method that uses a flow type for its calculations, and that flow type changes depending on where that method is called.

```JS
const myFunc = <T: Type1 | Type2>(param: string): string => {
  otherFunc(({
    param: param
  }: T));
  return 'x';
};
```

I want to call myFunc<MyType>("some param") and also myFunc<MyOtherType>("some other param").

How do I do this? All the guides on generic types require that the generic type itself be passed as a parameter. If the parameter isn't the same type as the one I want to use in the method, I'm kind of at a loss for how to go about setting it.

**Comment by AugustinLF** [comment]
Could you show an example of what you'd like to typecheck, and why it doesn't? Because here it is not obvious what you'd like to do, especially since the generic is mostly (only?) useful to use the same type at several places, but here you use it only once!

**Comment by CharlesStover** [comment]
I do only want to use it once. Just like in the OP.

I want to pass an object of the type to another function, where the object is made by the parameter but not the same type as the parameter. In this case, the object will contain and enumerated type and the parameter will be one of the enumerated strings.

Type1 is "one" or "two" while Type 2 can be "one" or "three." I need to tell my function that the object it's creating and passing is going to be Type1 or Type2 so that it may validate that the enumerated field matches the string I passed it.

e.g. If I pass argument "one" I can tell it to create Type1 or Type2 without error, but if I pass "two," it should validate only an expected Type1 object and error if it expects Type2.

I can try to make a Try Flow example later if needed, on mobile.

**Comment by yqz0203** [comment]
@CharlesStover I used `interface` to realize it.
