### ISSUE TITLE
Filtering nulls from nullable Types doesn't produce non-nullable

### ISSUE THREAD

**Issue by yarray** [facebook/flow#509]
Hi,

It seems Array.prototype.filter with non-null guard can't produce an non-nullable types:

``` javascript

function f (v /* [number] */) /*: [number] */ {
    return v;
}

var a = [1,2,3,null,5,6,null];
var b = a.filter(function(x) {
    return x !== null;
});

f(b); // call of method filter Error: null This type is incompatible with ...

```

Is it an intended behavior or a bug?

**Comment by gabelevi** [comment]
This is a current limitation. Currently [Array.prototype.filter](https://github.com/facebook/flow/blob/master/lib/core.js#L156) is declared to return the same array type. I think we could improve this in an elegant way if we add the feature discussed in https://github.com/facebook/flow/issues/34. Something like

```JavaScript
filter<U>(
  callbackfn: (value: T, index: number, array: Array<T>) => x is U, 
  thisArg?: any,
): Array<U>;
```

So if you write a filter callback that returns true when x is a number you could write

```JavaScript
var b = a.filter(function(x): x is number { return x!= null; });
```

Maybe we could even infer the `x is number` return type!

In the mean time, I often write a helper function like this:

```JavaScript
function filterNullable<T>(input: Array<?T>): Array<T> {
  var ret = [];
  input.forEach(x => x != null && ret.push(x));
  return ret;
}
```

**Comment by yarray** [comment]
@gabelevi Thank you. The wrapper function is also what I'm doing now. Will be very glad if #34 can be implemented!

**Comment by runn1ng** [comment]
Ha, I just came here with this, and I actually wrote similar function (except using "map" that didn't do anything and "thrown" error on impossible nulls), but your version is better.

**Comment by samwgoldman** [comment]
We already have an issue for adding refinement annotation support over in #34. Can we close this and merge the discussion here with that issue?

**Comment by avikchaudhuri** [comment]
Merging with #34.
