### ISSUE TITLE
Allow specifying ignored directories

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#510]
In the .flowconfig, the [ignore] section takes a list of regexes, unlike the [include] and [libs] sections which take a list of directories relative to the .flowconfig.

My project's has a directory called "dist" that browserified javascript bundles get built into. I wanted to block this folder from being flow type-checked. I put `.*/dist/.*` into the [ignore] section of my flow config, but then that caused the line `import RSVP from 'rsvp';` to get a flow error:

```
.../src/lib/logger.js:6:18,23: rsvp.js
Required module not found
```

I was ready to tear out my hair until I noticed where rsvp.js is located: "node_modules/rsvp/dist/rsvp.js". My [ignore] rule was catching that. There doesn't appear to be a way for me to block just my dist/ directory without depending on the name of the directory this repository is in, because the ignore regexes are applied to the absolute path instead of the relative path.

Can [ignore] be changed so that relative directories can be specified too (so I can put "dist/" in), or so that the regexes are checked against both the absolute and relative paths (so I can put "dist/.*" in)?

**Comment by gabelevi** [comment]
Shouldn't be too hard to support...maybe we could do something like

    <root>/dist/.*

and just automatically substitute in the root path there. So if you're editing `/path/to/root/.flowconfig`, then that would be treated like the regex

    /path/to/root/dist/.*

Would that work for you?

**Comment by AgentME** [comment]
That would work for me, though I worry it complicates it by adding one more thing to think about while editing the .flowconfig. I did really like the idea of making the [ignore] section work more like [include] and [libs]. Not only is [ignore] different from them in that it's a regex, it would also have these often necessary variables that it's easy to forget to use.

**Comment by gabelevi** [comment]
Hmm...so internally what we'll need to do is to convert whatever is in the `[ignore]` section into a regex. @bhosmer did add support for `**` in those paths, so we probably could just convert

    relative/*/path/**/to/ignore

to

    /path/to/root/relative/[^/]*/path/.*/to/ignore

It would be a breaking config change, but hey, all our releases have a ton of breaking changes anyway :P

**Comment by AgentME** [comment]
What really makes me want to be able to specify relative directories in [ignore] is the fact that http://flowtype.org/docs/declarations.html tells you that your libs can't be monitored files, so if you have a libs directory inside your repository, you have to add the directory to your [libs] section as a relative path, and also to your [ignore] section as a regex against an absolute path:

```
[ignore]
.*/flow-libs/.*

[libs]
flow-libs/
```

Is it actually important that the libs directory is ignored?

**Comment by clark800** [comment]
I ran into this same problem. It's a nasty one; pretty tricky to figure out. +1 for making paths relative unless the first character is '/'.

**Comment by danvk** [comment]
Any solution here would be helpful. We recently had to work around this by [hard-coding][1] the name of our project directory in `.flowconfig`.

[1]: https://github.com/hammerlab/pileup.js/commit/59d5577d5e5880fc17198a57058d24adc01ee5d6#diff-a9d0201e8c5bdc946e54218bb9206174

**Comment by clark800** [comment]
So much developer time being wasted on this...

**Comment by Schmavery** [comment]
For anyone looking at this now, looks like it's been fixed with the addition of the \<PROJECT_ROOT> placeholder https://flowtype.org/docs/advanced-configuration.html#ignore

**Comment by aackerman** [comment]
@mroch or @samwgoldman I think this can be closed.

**Comment by m59peacemaker** [comment]
I'm on 0.32.0.

This config:

```
[include]
<PROJECT_ROOT>/src
```

Causes:

> Skipping /home/m59/code/my-project/<PROJECT_ROOT>/src: No such file or directory

**Comment by m59peacemaker** [comment]
Oh, I bet it's only for ignore and not include. Odd.

**Comment by AgentME** [comment]
With `<PROJECT_ROOT>` added and documented, then this issue is solved. Thanks!

**Comment by AgentME** [comment]
@m59peacemaker The other sections specify specific relative filenames or paths. [ignore] is the only section that takes a regex (applied to the absolute path) so that it can match many files, and `<PROJECT_ROOT>` is only needed for dealing with absolute paths.
