### ISSUE TITLE
Unused arguments warning is not polymorfic

### ISSUE THREAD

**Issue by TrySound** [facebook/flow#5109]
There are two cases
- passed function uses all arguments
- passed function uses one argument

Flow forces to use all arguments.

https://flow.org/try/#0MYewdgzgLgBATgUwCYFdgIIwwLwwBQCGAlDgHwwEDcAUNaJLIqugEw74EA0MARiduQIwA1Lxp1w0GAAc4IdBAjsmaBHDLUYMehBAAbBADo9IAOZ4V6OHgzcWRIuNnyEii8lUZH1ZwojvmBHtKIA

**Comment by vkurchatkin** [comment]
I think this is the expected behaviour. You can fix it by providing an explicit signature: https://flow.org/try/#0MYewdgzgLgBATgUwCYFdgIIwwLwwBQCGAlDgHwwEDcAUNaJLIqugEw74EA0MARiduQIwA1Lxp1w0GAAc4IdBAjs8TNAjgAufGBQBbHuu4796-uWMG4Z6jBj0IIADYIAdI5ABzFcjVw8GbhYiInFZeQRFb2ZMEOowhQgotSDKIA

**Comment by TrySound** [comment]
Oh, nice. Thanks.
