### ISSUE TITLE
Need a better error message when server fails to initialized when there's a parsing error in lib file

### ISSUE THREAD

**Issue by omarstreak** [facebook/flow#512]
.flowconfig
```
[ignore]
.*/libs/.*

[include]

[libs]
libs/

[options]
```

./libs/fail.js
```
declare class ExmapleClass {

	methodA: () => any

	methodB: () => any

}
```

(error is missing comma after methodA declaration). If you setup a simple structure like that and run "flow" you get the server trying a bunch of times and finally exiting. Looking at the log the parsing error comes up, not sure why the parsing error isn't just spit out when the server is initializing (and server shouldn't keep retrying when there's a parsing error).

**Comment by samwgoldman** [comment]
@bhosmer improved the situation for lib errors in a recent commit. I'll update here once that is released. Thanks for the report!

**Comment by samwgoldman** [comment]
0.13 is much more informative when declarations are invalid. Please reopen if you continue to have issues after upgrading.
