### ISSUE TITLE
Platform not supported?

### ISSUE THREAD

**Issue by EGM** [facebook/flow#5120]
Crashed and burned on my Linux device.

**Comment by TrySound** [comment]
@EGM Which linux?

**Comment by EGM** [comment]
Apparently not a good one. I was trying it out on my Android phone, Linux version 3.10.61-10809541 (dpi@SWDG4521) (gcc version 4.9 20150123 (prerelease) (GCC) ) #1 SMP PREEMPT Wed Aug 9 11:44:11 KST 2017
