### ISSUE TITLE
Kill Flow server process when webpack dev server exits

### ISSUE THREAD

**Issue by stevenalanstark** [facebook/flow#5124]
Hello,

I am using Flow with Babel and Webpack.

When I run the webpack dev server, it will first start the Flow server.

When I exit the webpack dev server, Flow is still running.

This means any time I need to change a Flow-typed interface, I need to close the webpack server, then find and kill the Flow server process. 

This is a cumbersome process, and IMO the Flow server should be killed when webpack is.

Sorry, I don't know enough about this to know HOW to go about this.

**Comment by TrySound** [comment]
@stevenalanstark Flow and webpack are not related to each other. You may kill flow by youself with `killall flow` on mac os x.

**Comment by stevenalanstark** [comment]
I realize that, but isn't there a way to close the itself if it's spawned by another process that dies? child process?

**Comment by TrySound** [comment]
I don't think Flow can be a child process

**Comment by LoganBarnett** [comment]
@stevenalanstark have you tried something akin to this in your `"scripts"`?

``` sh
webpack-dev-server; flow stop
```

Once `webpack-dev-server` terminates it will then run `flow stop`, which will tear down the server. You might also try `&&` insteaad of `;` but I don't know if that will work if `webpack-dev-server` exits with a non-zero error code (a crash, for example).

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
