### ISSUE TITLE
Function-based type refinement?

### ISSUE THREAD

**Issue by arahansen** [facebook/flow#5129]
I was wondering if this feature is possible, or is something planned for the future of flow?

As an example [(tryflow link)](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqLgM4DK2ATrugOYAUAbgIbSoCmAXKE+gJ4CUoAN6IAkBTbZUFQtl4AHNrEihmrNqAC820AHJilajV2IAvshCgAFk2Kg2FCrAoAaUACM2mVLY0wEoAAmsGzE6LrYoADW6AHwbLoMGhKQ1GyBoHKKoMqgAAaw7gBWAHRq7HmZsKAGVLQoGDj4hDSS5HX0hUVcQqos7Fy1RqAAPqDoqAC2nhSgpvyDhrTCiKBEKnQk7UZ0XWX9bPyCImtrElIyOcX76qtz9tDEGien59KEuoFskEyo0JHlBJ3czmSz+eCgDBfCgGHiBOzUaBpfJZJQqPaArQ6fRLYyVSDOTIKZLfNKTNjobCISzEWBuWL2RzOBpYPAEUCtbDbWi7Yo9PrqRYdUbjKYzOYLGq4lZrXAbVG5DEHLGaPRDWi6Y53M6Sd5XUqA4EPJ4y166y6fb6-f4C9gmNYgoA):

```js
// @flow

function isString(value: any) {
	return typeof value === 'string'
}

// has error, becuase flow doesn't know we've refined type of `obj.value` to string
function getString(obj: { value: string | number }): string {
  if (isString(obj.value)) {
    return obj.value
  } else {
    return 'default value'
  }
}
// flow understands inline `typeof obj.value === 'string'` for type refinement
// so, no error
function getString(obj: { value: string | number }): string {
  if (typeof obj.value === 'string') {
    return obj.value
  } else {
    return 'default value'
  }
}
```

I was hoping `isString` would refine the type of `obj.value` in the same way `typeof obj.value === 'string'` does.

**Comment by apsavin** [comment]
See #5087

**Comment by arahansen** [comment]
Wow! Exactly what I was looking for 😄 . is it possible to use `%checks` in libdefs? For example, I tried adding `%checks` to `isNil` within the lodash type definitions, and I get a runtime error from flow.

**Comment by apsavin** [comment]
What version of flow? Can you reproduce the error on https://flow.org/try ?

**Comment by arahansen** [comment]
Seems like the issue might be the fact that the function is treated as a class method. Should `%checks` work for class methods?
[tryflow](https://flow.org/try/#0PTAEDMBsHsHcFoAuBPADgUwCagM4EsBzAOwENEBXAJ3QC5QAOAZgE5GBWNgJgAZw3xwAdkaZGARk6CxAIzEA2TiUaNumZoPQAoEBBgIUGbADd0lfNCJ1G07nIAsjem2mDgMTCRwALAPpG7AHQAHsHAUHA+AHwAvEbcAXaCwZqamOgAxpAk1KAAttCY5JDooABE7p5epaAA3pqgoGmZ2SUGJQAq6LmoWYjoAMroiIh4RAQ4oNG19Q2g6DjpJBgA-HQASugEAKJBqAA0Mw3oRiSQ5GToq6Ab27sHs6B43dCUiDhXAPLSAFYZiPezUZ9SioaC9S7rTY7faHUAnSh4EjSYpXHCIBFjGYAXwA3CkGk0sjk2qB2pRyERFn0PqgRhYJlM6g9imNEF4rkRyLlpKYAQ1oLk8DhzERUejRgQ+bh0KhsmQXlcbtDQAAfXDizENXH4xoZImtNAlAAi6Gk0Ap6XQNLpRAZ02Z6BImAlVzNYMdRCluRIQQA6iQ8IgOVyeZQpeiA5AXXQ3cUSERsXiZoSWqASe0vJRoMNita8PTJvbZnHnWNXdB3fHw5RI9HQLGPYmdSniYbQAA5eZ9TAAQUoNeQAB52pFC32B4PxyQhyPIkmCXrUyTvYh0l55gBJYEXAZeF5s+PYKZfX7pRB4hfNVsYPJkNfzAAKWYwr2QW9MO-6e9eXkPhYA2miGKSqA8bIAAuheupXgaN6oM+pgoO+NZ9Lu+6-kQR7qsB87QfqaZth8T5YHgVLoJOeygB8o7RLCaoABT0ScZy0KAPaUQA1ugyB0EBEqUdAPx-HQHwAJSTKOYGiXRt6ruuODIZ+34HphMkrveOBPtAL5IduqFfuhh4yfB2mIW+enoGhP6HrhLawSUHyKahvqBl4Gw4EUiCDgAapRHyUWsNEySefwyXxmqzAxTGnOQrG+aAXE8dh-GgIJp6ICJ4nRKOayiVBdkETejkWeR1GFsVH7Oa57meYOYF+ZRYFzsmi7Xg5ABivQALJLE5lnDpRACqNFUX16AuWyNWQF59WkpRU5DsNzUtTBhUlMRzpkcOQUPFFzGxXQ7SUaMaRBHQnLcryoH9tOdALdtWWSUQyDSbtskaWNBnWapb3qfJWk6eZlWWV9KmYMZCGvp9ykYZgtmtfZoA+N5MVWkQkBAyh-UjoW0UsYdj15HgQRYPlCNraAKMsR86OYzu22FsjqM0xjY0M2q4UEGTq0kj4bM41M9GwoGXSHVKJ3oGdoAXaGUrZAOdDLPdI4zITgok3DK34SS-MjXzJXs1RQlnqqyVjNz2ttp1ZA9ag-NDTtkWgIxIu5GLjyYZL50hld8u3aASs3TOkSE-dw2vU7IVnmFGpc1rS5tgAwgKsooS8DOC677uu5wBMSfWFZxkQ8M822ttOenR2gMNkwyS7fRu3NHund7l1htdCtsUHD354NEcNGqJmA9DhmYSXltFeXemVw11eOwPzv0VnTeJbxscCcbGVUYTfcQ6ZUMlaDsPj6mzTCqAAAyBSVEWDQ6AtsJrhSHHbfRftJYHE4jpR+AAF4QtLH2lBRJ3W7srSIkQpTpBTiQM8A0OyKxHG-IOoCJzthDqg6c20oEWCpK-aQnhWLgMogEUh6Bii5HQEQN4mChxNRAV3L+psmpSmdAIUwVDLSv3forYhcJUbvFoQ9IR39YRsPABwyk6AABCwchYPAaDwgOxDYQNH2vMERkDVGPBKnQKmsUWZ01QttWEDD2j-nAqwvA7DqBSIml4bhKDSQWMouonAh0XGgGgd0OUiAFR0GTj4tOlBhHOMsWI58jjO6fywd-aWwY24MJUQ8TAz41iEC8F5JBSiYnB0oqKVuoYknd1ESktJGTEC+i8HgYoUT-a5OwaAeCJEyJXA2qRC4oTkmzFSdpKpNTyLZKcQ0uJzTNoXDadQcZfQuklK0Q8cANTIDwOGvIhROTukPHUXQQaUoGhomyEGQpvJtFUMwAk0MpiRGm2GlKRZmENyeyCK-bRGy5l7KaVMjpfRJktM6aUhR4Asy5EeadC5pgrmALbnck6F9PCIFBZLF5CiO71M2bMMZ3yAHtK2gChZwLEVBHBZQSFMsTkPB0KcREExoDgCRgEdcTpYSLLMFkyIyDongLMXc3ofQiDwIABrsqUfdcBpshXFKYWqIVPKyB8pNDKOpSUwIWMlbE+ZswoByqoSaWkXgOX+xVZY3UeriUMKNXc4FD4AxmFfrKPAZhNEMKjv8WEjLMBKt4XM7lwsnkfHAJ65R7z+H4ybkCgUhKzXHLDL6wMiJllDM5d6zR4tqGmBwH8fM-KkGkICO-dxjCsHgIwYWvJsIQC+heBxbI5pMKgApCMSAztc2pxIJQ4E7tW3ttMLnau4lYBVpwL64EGazxZtkdwsQKadHAwAfotGrMDYjjVWWh4QJ02ZosBOpBryp2luwa83t6KGgiyxnO5mtNdaQvReuswm6iDbvZbulNh6X0oqUG+hRp6dxXHnYYq9DwV0HrXWmu9Y6t1yOffuvFswSBHvea8xgn6HgkDsMhwEJVf0XsXbOkxgH0MVqrTWik2AG01ObaQrtQxTCdrlN2ygva+6gAHZQDiQ6QMjvvfYyd07vGtr8ZQAJMDgmzK-hqk9oHR02m4zu99e7j2gXg2Jj5fHfEvCE0E+UISVb4eg+Jj2nHwNEBk0+uT6HFFKfVR8j9emVPCa0xp-jldIjXoQxxjdRmTNrJQ-Jtz6zLOrvWUh2zry0MhZRap4Jjm1PaZc7p9F3xoCjEDSMyB0onOUDFMBBhnMpRZDRClrlYtYT5YRX6gNia0XBu2WGglTyo1QtlrCahDjKtJXMcagpjXTA+oeKgIoCbhXDL4bmtxVwivhYxQNnskBBsGo-nwtxTr0P9dmzNyAj7vOweG35rZAjzMzrPVh6ml6l1xdmEBmDq3IDra8+-K4HXXH7bCZRSLWmrjtQtDaMxLjYTXZ7Gy+bXrlOgFzRLDW43u5ksoCW9F-3AdvJB+DrAkOJzQ9h7t0A1B8gmEK8GzFrS6A4v+Rj5TsJqAmDvXjsTl39M4CjFwtrwOrPqkOcSyiZyGvopwPuLAhLqcs5q+0Bh0OpQ89eHzp5m3Xk7bJyioXHzv2oWOwY07uGdMXejWL3nmBCX+oF3kkNB1SQi6AdriXmA4Von50zoNIOhem+hbCcX3YrdldOtL99surPaIV9opXlkVcLqMdjc7DRHdNYeC7rAbu9cVaG0m+3qMCZa+dzrwaRA8AAEcDeiZ91H9Pmes+bcRyzgPAC8bG+F-ndWWBafhkjLn5d6HEAkC4k3tLXXof19hK3ri6SCCZI7-krnmO+-oAH5k-ptTbepcogTiZROvm4tJ-n2Y4-p+DIT1VkHC+flL7+TM5vk2GgUiza-XN+bUdFrmavwLd9gCVtY8RutZGm30RbXR6jgmm5UeBIx-tQdWEM-CDHjWzQ7H9PRbDEPLfHvB4EAh9SDMzE-WDALYDL9TDKAk7HDM9PDTXFAhAz3dZXzOXfzA7GzBTcvIPf9M7VzUg0-TPUA2TYg8gtAmDRRYLBTVDA7KgrA1XHA+mDXcPAjR-IjLMEjetahcjD-SjL-DtX-OQntHZQA1jdjWYBAu7EglnN7ATK4QJDLPPe-SQrNLzKDLgtg-TBoHQ-xUAfQmLPA4Qggxg4zVyZFFglAizcgzgzHKw+zXQ6LETIQ0AOA9Q5w0w5A8wrw8gsLBTawzLAIrTBw4I9DM-HPWfCbdFVIkvb3Q3XgymaA3WEIhg7PO7HIxpOIvQvw5zIoyQ3+PAVADvGoikOo1AUoxPMvTA0AQo9DWAVyc0BHMouJUbARa-YOGooIZzGQvNJxUVW-GowjZ-cQ1-KQ9-T-GsejWjdY7-AA5jIAh4CYygEvLQ3Izov9NXXA4-dFA4ognzVgng04go2g+LTHa4pA9wyIjw0Cbw+gjDWdag84wQsPZIlA14tw24z4uDKIiEmInwiA5XPg4PADfA9FBY6tJY0jFYijAIP-GjBQrY--ZQ3Y1Q2EA4zQ3jKo+I2wikww9AhoUk1w5g8Ej42IikyozTATJI8Yl4cI942EyEiE74tfB4CohIjkoIrkygHkpkvkiw6zQUowxRGEn43w9kmwuwwIoEmoloiiUAaRYVeTTxfk6RVVIRf8diXU8CfTbU806RSiROfUu6Q03tY041GzROE0-dM0yiW02wy0qUa070u0yiI0B0tiJ0ugF0xqYLd010sLI0D0+6L03UoM0AI0P02EAM5M2w4MyiLYUzd437d9Z0wsoLAJEslDOM8s2DNgOgLYCxOgrBJMn0xOHM0ALYdMjM+ol1eiIeQRfdFhI3eYUYuqZ6EtF1f0rszeBVVAHs58Psi1Qc+c56Z1TeKUVEl-DExtLEnEn-KuHcnYljNjTs1ohk0MzsNELAPhPI7olAloqU2DPdc87sD4p8y82E68p45EzHO808rbRRR8rsN85UxTOgV83sPk4LMCygzopExw9FH8tkMEh80CwC8C4C-kqCiClCi8tCoU2DMLTC4Cj89XTUl9ctMAZOWbe9R+WtRAbI9ok4v4hEmgkilc9KHBBtbdESTedlNKYSJuPIs4gQ4xY-cc8i0CKMTwVKOlHwAIcAF4LYWBLwWER0NcYfOEwPOgG89FVS1rbi9KXizebOToiqC4ktI6cSqlKS2leleSygRStcSfRAFSpSpy9S4isymo3Sty9ofSv4Qy9KYypi0aM7XrWYY4UwORUvRio7LS0KmMQuD0KUCKygGcPys8AK-iquPI0ywEhhBsKsZlGpYEdSvfbFZfEnGoxZaaUwHU3y2oUAf8PATANeYCcCO6UALEfMh4Pis8YrFFMqz4YnGZc08UoRHsfTe5D1Rk7bBi2kjFCq-fUAYarfD5cNEFeraNSFdoU2IwJLTAGFTCHyeaSieqmoRq5q1qiUdqtiTq7q2YXqreCygaxagBIiV6uqywiAOrMFLa3TXyIqzCN3JCxRQYr6wag-aZVa7RdayNP6-AnatUPa5qw6y3eFY6tiU6ugc6pqlqs2AgG6nsO6v81KIyuabRCGqiFaz6yFAGhZbqJYFZbfBbYNPI62RAKedXB2IDW5ZlBmho+q8cueEmx6-qjA4Kj4dmzmi4h2BsxaSa-m6cpmkm6K+ak9ToqW3qJdWW54icXm+mm2JYJWwW1c4W7RUW8mlFHKzWu2bWueOWwcfWzVRWmURCquVZGXOa9gjSgBG2+2OeD5NIU1eGuC7uJ2hoLVDmo212vSo2dis2lFC2568W2KqiP2u28OnpGO4lB2zOuyhy1rZm5nGKyAro+KlA-OpS4cdKxATKvqgSkym85OiOhS1yipdymC8u9FSuxy9uk2gy+iJO46Ru8u5u0AAgcQ1ACdeKGa0Gr2r6wSx4kiyFHG1eSmQmuZTqqUCe80KeoceKUa7Gi6vGzmQm4m82smse9W4KoSmAycUihq-8Ne7yDeicCare31TIcgNIHAdShXb6iNTa7rYBBKysT0T+s4H+6uuO-ywey+p7UNWaWGoB7vUBouVNL+n++iICK6sYBB43XLABja364B-KxKwqkDPariW2EG1FFm4C2UNkOgRiB3fOe6TmUcDmWOcSNUdh2OTh-Gj5S-SgcYYcpqB2lhX1Kh9AGh-u2Bi+wKy2hRRhrwZhyvViKSNh7uDh02TmHh-dHRrh4CIR0hbIURoRcR3WrBSRh4RKbdSibye6uenfPC6+1O2+2C4E1e7iPRG65YHarEKUOx-ek6rorGx+y6ros+rqkW+B-3B47Au+ialexq5+vxomwJ2Eb0AWh2IHO3Do4K6WxI92u-R2-TbJjGuRs8XJhR-i-xxXEyopjkmenWr8vW8ppYEmnBgOXLeJ4K+iNcbIXBkCcHLXbCYZwmMCSFXpnqygNIQ4t4lDMGhp2dPs+6XWARmZhRF4eZtZ7uUoTwdIaoNUUoH+o5zZ2OB2mDHZ0wae8Jl1Jx0mxRq+n2vZicXK4xAAKggV0fXnNrmfTWHIOYWGObKDOdKAueAgdscalFThGBtFKtet+ShtCUIrwrhbjQsAxsPoiZPtjmiceaHopqRZEmptGofrRf3v0ymXIEZxqa93npWdTpJsUXSHSC5CKAc2rg+TUWTyUatqeVTxRWcfofVW0R3mszZY5d6BsMGkhV2XJywFpcGRrvpe2biats6LfildyE5YEx2XwY0eek4h8cEaeayoldeR1b1dlflalBpctB8rVaWcZb6eZe0VZfZd1ZlZ-wVeFcHLFoFZbmAZ5boeLqSPD17kla9ZtcpLld0z9dmAdYnz7tVYTvVeeaZdLu1ZjZ9YNYDdAmNYSlNcIaTstffWtZ9auHjfwMTYaGoHSkRcP3KubZpJgwbb+B8jTZxZxsidPo6pidqfrpecpvetbfJehbpzbR6C3zydSzCv2WndqRnprrrqeoYTptmBwCXYGDwH-nUq7yARqO3e6GKH6D3fIhXZgYyrgczfiWjSAxhedy8HIAEBnyLvybGPQ28FfagEvfuZ4tvYtaESfajwvYGbBGKCMwsdHNNhdQj3JS3YFFndVtGRJeWo+uPwKvAYL0oTqqPtxuGYJdifSiuHqeJebaGo+ond02w-NzoqiuWdB1IXLzeawQ2ePf3HopcZLtQjY6HA4+-a45CdJFXZI6ypMYCFY+HI+dDwfvulA6Q9eDudE+vdrqA+HeHtWZk8E-3SffEqNAuGazgHogQ5jXEs+0pBtFhBIHAGBHoksBDYgEc8s6MwYVc5tDllSvonAAtDoA86zRHwff86+0C9hB5DsvQAc7GfABc9C4sHc-i5w9mGkBOh8789AAC4sEojZCFD7AIDoFmjWJGFOALXunoRC6s7C4eFS8wgAGluJb20217CHiv40yvu4KvMukuoEqBvPfPKRKujNGoEQUAGssvkurC+vkAnL0vBvuuqvsvrpAxkBxueuxFTRa1LQSaBv0ghvPPtFYAAwjkQ3zbaQs0+yTQzQLQrRzv6RIUJvWF0AJFKA5u9uFvhvmPpjzH+zRyzOnushkA3v9vAvmNjuxnhGfvyu-uhXnb6jgePvvsQfsusmugkt-4EfHusd5gwRKcPskvEvFvJvpZNgLhZzm3keiBCfhvYRcEovdvKfqeDuerKd8ucBMeeuvuIxbQ7LcgOuJwJuS1HvafWeRH2eGfEfQfuecBef+esFBemfquMVDl40OeieSFZDXh2vCvnoPThe+sVfThZuJese2vSuYPkAhf1uDetejeKk1fPuMXzffvLfFeUeHhqAzGHfPOvvkc5ehx0c3fifPeRHvfQe-ehFA-Kf7Wuww+luDlXg1v1fndmknQ4+qfo-e9MxsxEBigduMv9eFEjvAx2czubQ+yMwswcxbvy+HvrfQjsggeTeCfM+HhYAawZyatZp2+lgXxGfM-xK4UIorD4UFp1G6BPnzVdfwlhSYAiBZ2HdA2vE5-0Bjb2VF-+Xl+LBV-LITy3bnXZg-cItyA0QBQL3KTlhx+V5TXodfnjHzXNPWd0gOIdeXpe47XH4V+ZMD-eXQ0Xn2XT+gof+Bfyv5Vw16t-IxilCHpP8X+hbN-tlGrgf9hSFgWXu0GgDQNvGSUftkTA1jn0UUPOKgJaCX4NAyqBaHagADJH6LXfFswyliaMEB2HTqpCjo4qUs8V-WaNmHXA-4pIaDJKrCAICIB2BRbTgbiR4EFwwG29PoEIOQACQ2Qog5crwIoaAgcA+XLkFQjeDSCyGEg4WCoKDiaDFBxPPLkHGkS-tTA+g8Qegx0ELQL4eALiOYJYFrpdBA4GwVxG7Jd8FBFgvgY4OkTkMiA9g3weLBwAmCbE-g7QY4MM5SD3BL0AwYEK2AUJ1BoQywY4K2DdAUAiQrwcoK2BZ5zgkAaQbIK4Gv8tBSQzIdkNODf902e2P-h8hEG+sVMJ-PxEANMBXAWWTzedK-1DY1C2hcA0NuAKAR39+IHrB-k9Q6FyDahgwg5M-1f7it84jApGvtWYEBCdBWwfsC8HSFKCT0OAdqKMBFhrDDBmwpLlfwm4MJ0QsUQIRNyv4QD8au1faqbE5CzY4Om8BhOAFK7oBAhjyPoAQDMFRCihGQjYRfCoQCD9U3wmIToNti7DAhPUOSBpxO7LAhaBAygEQLU4-D1hjwHAJCLXAyY02g0MTkO2GHaJ4RiIutrMAAENDz+zQwYWlC6H1RxhCIqkca0GG9C24-QvBhSI1bCsCRrEGtoBhmG+DrhzVBYWEOUHtgSA7YcEToOFEjATAYoxwe2BqS7DQAAAUnvDP8cAgQ9sANmlFCigEmojYW4L5ZiCHBygl1C4Ki7AjPBKIoUA+CyCjA9RiDDwYaI2FKhdgOo1Ef0Fs7oB3hmwL4fqPtGLDHBgwQQWaIdGujY4V-PRnQBOGvCdB-QUMb7j5aXDZhkvCwHyOwBqg7hTaNUC6lNjQ9LekKZ4ZAAzSBD+gyAbkGCBdFCh2ghoXCkDyDF+jlBGeNIPciwDlicAvoR0BxDBG1jBRGwtsW3gDEujpoeQ1KKMMKEgjmQkQn0TIOHEFC4ByI4nn4jH5micx+mPxFsMzwTi7R0Q07g8D8SejPhr3M0aLl7zQB-hrIIEZOP+7Hj1RbccwUeJ3HQArRAYIgLaONxiCxK94t0RIj3HejNxl4j8aGLNG9NxKkI5SihkwCYA345AT4ZhDGZOg0gME0hrDysLoA5R0OMZs0nSBCgs0DWO8T0jwBGBmqUXZ0ARPgl41RcjQfCUKHUyITtxztCsK9zQlOcMJWEiwDhLNxZMfQjRJft6CCDcdRWvHTSmXVYrcSPQeTe6N8z-GzBKE8YPidOg8p5UkJRMbNB+3nbcTRgskz9o0nkkiVzKXoTyPUQxj0RvWIwHoHgFxLkTjJBkjpAhNQa0T62taCCYxPInMSRQbEp3FHnIDSAIwZ4IyaMFig2SzcuATyRGHXABTEkikjyLkDEndwJJEUrkBpKvKd1hJp3cStDk-7TsHOQCMZnoCaFjNyAqAPvjRNwkSY1g8YT4ZlLbhjME+J3ciWcmC7mjg+h4AUPRBymUlyJ+Ul8Ozl0DQAyAdYbDpePEouobOwoQgH4MepkchauaDkfx0HAPM2KfwOWCNOICPIdSepN+HdEojSAIySSUAJQNtLDT8Ay0-lDaTtLCoNp9YCMq9gCQ7S9pu07MgdNGkrSTp2ZVMmdMxoXSsy73Fso0DoBGgbpupO6YnDulGhFph0ogE9MDIvSQZbZN6eaS2mfSAklEPGtDNYhbB-p0iQGcDLulbBQZj0lwm7W7Y4jE6bIqPPJjqGACyRzDVkd8DpEyCaR6QWmT0JLZ-N-WRLf1hyLujTCEBYEFMZCnfGwYlp4M-GbHSFo9g020iImRmwk74iyZ+I50uTNJHADyRrMn4IzPplqz-W1A4xtTOlnszzQCIohKbGkRcynoyAXmbpn5mKJBZjyTEWp3mjiy02icSWT1RJlbtZZ+A+WfiOjIKyz+SsqmSrJpmTjQ2OAWkUHIZHMztZAc3WeyP1mIiiaaoDGWqETgmy4B5s-ApbNAjWzhZ0DUWQ7Ltm2E02RoZ2Q9Vdn7J3ZCiHAJ7PwHez8RcZH2Y0MpItDKRYc9maHM3FMysBLM4VmzJjmEDDZCc02EDLVBGgU5PMuYfyItmrkHpxAW2bnLU6EtS5uAcucKXqG+zcpzsamRrPZFtzXx9IzWRHIGFRzNO4w2OUQlHnPQ05jhDOZ4DBmzzTaYs-ORLPnnidj5+A5eVuyrkKISRa8xuZvJbnbyGZ-8lFFrMPndzF5+yU+R1QTnnyzZ488GJPPYrTzs5VTf4GxDzlC0nZz83EcQKXkbS5Zl0r2YjO0TfyG5yssBYHPbnqygFCiEBSyKPl4i9ZfcqBQDKTkwLL5wJa+YLLvnx0H5QtJ+RgsLnFz+Qi8nAO-P2Sfyo8Nc-AXXOIWrzSF-s8hVvPwE7yjWdM-eZ3MjnkLo5+AyBbdQHlJzTYI8lFJMwvlwK+ZU8lDIIPGmKxJpshNkP70HAcMgMNjWDFYs3gTTTaKjBxU4ot76Z0gnvI-OyhMh+I2gnaSGCMCHI10GEAAEn6D5SzIGAeao2JICeR2e1igOLYoCDTSZOPFeadUw27PDUl05aER4vjpTTT5M0uaaq0sqSUJgdlelH4mtQOo1CRwahAiHmAlKbFjw7Cs+U66jk1yYAKynUpeANKHxNqBSAmAeDqD2lEyzpRku6UdhUKy4gZRJWpQQARlslG+XjJUpBA+UHqG0rDM2nbSOqe05KrsrOSrTTp6096fDJ9JfT0ZgMs5XssuVQzDlH0u5YjJ+mpkHllAoGZQJBk7Lnlz076dDLzLXK4Zl0rxJ8uRkc5ayPy2wljMoE4yalay+pZsqzn2JAVZybhQtLQVYLiZmbGWXguP4Uy-ZG8gOUoorkqL2h4cjRaAoJXaKK5uinsGwrMUIKFpWKzCDiuqZ4q+FQioYTgtEXEqK5Ei4kXIspnkrFF1CqPNSu6G0rhmHQ8BbgGZVGzWVcIeYeyvyVTLzlXKhkoTMfmOz+VPc0mcKqjyir9kUir+eKrJVNzVZ0qrdrKupHqKFVOs1+b3INnMLE5thNVcjXgXpyLF4VHVZgG5WoLeFptfhabUwVC0i5+KqWW6pNWY18FyZQhfdOkW-T65Eq21RQt3lqKAFlK2xgfLoVaL41TKphXopYUIrh5PqjVf6sQULIToDXIcD22PpEcB2C80jogg+SjsyWp1B+pzBTGo03cja-Dri1bW3VB2DKs8GRxHbocx2KLGjvgX7VwK7kLwR5HMthGm0cqbMWKXbOZSrqiAs3dJRuvjpbqDYO6jOXZQ+CwAxp7irpSepHq4Zz1AalupQCvUHr7eR6oWqesfVjln1EAJLmktvXzL0oQGDhncgA1rrP1CyvhsBH0yfDBBuI0pX8FNgNIXFBvNkGRxg0ShIW9KrOoUumjzorgUzXTE6tmC-hANHa4DbipUaYbtG-DZkQQDnFShyNkGoDceuo1kB2Q4bQxvjSY1SNEI66oWpZKpjlgwGeS11JQ0QiyJoRd63FWzRb67rKG0AOwYhtk1arlGnG2jROB41bMHgkPGaZY3wKkaGgiUCjX8CQ1nhQN-DIJtxFmVQaQNQiMDRxNQCNqzNU6tTagu-W4En1daqSUsHnRuaYRX6h9d5t-W+aGglCERlF3s24rylfcmaexoyriavQpgT4SGvtmxqXZhKklYrPXlZr81DqwBZQudWCNXVDC91XHOrUTza1HKh4JFrS16r85Ya+OhGoHrYLN+Zc01R-IIU5af5ZCglQVv2SOq95wrWhZKDK04KIFZa+ObqSq1+qr5f6+reNEa1zy+V+cqNYB3a0vMhViaj2T1ormWqV5pKvLX-OK15r7VJmwteNvoWTblV02o2YPLm3mLwteQVLctoJlNb0FkawRZlpLnZaK5Yi3AOatwCHat2Mi3rfIslUDaLtuAYbbmuAVXbFV-2nRfdv0WVrUyT2zVRJoeqCg3FlGxLagpbRzlHN-DZLbT1x2CbPFxOgxqTuqU9VcdE6ZtYR3xrEdVNAcGdZR1JbUde1z22rRilIgcRKdZSyjNTqw1jAwtfOkgQLqF3UbRddG2DWTr6wC7Gd4TXtnizaptqX5MIjnVDSo7jsedWOmPh5EHFs6CdXazTdxvo2QCi1KSZ7ikoI2owiNz0SFMZulB47zNHm+fBbs0k6b14BbN8X+ozSVJfyW283Rhst2waGNHyKIRmptW2hGZxbOlXg2lg4AXUecbmc7sN3HimlZgGXSbF4YxSS0lLEcpb3DBjLmlrG-HfBx6VAVrG-S3vDWB54vAopxCyDvehrrZi+lpet1qXVk7kRvm0baVu9imEkaRtDBIPXntQU0aI92GhjXxvgKoAPAUgi2kLRUbDMLEUe+tIvouA-4jhdO9Qtvr6D2Itd++9Dao3xob7rd12hRPlKX24lC+R23LZSQm6871Nv-WKIFos2IBnF9eyoR-sr0e6qNlm3xQcHEqDAs84lX8AC0oBphoA2PJ0JtPICIA0w1SCYEKCRimdYQ5g13YM2SxIIN+ru1vALXX58tsqoGS0LSGomgCTFW4semyHJDDgxAp1TgCQb-5MGDMpgCg-q2dhC4xAhMdoJwDMScAVl7QD4EaA+B0BZKwS7MIaACCfMdQD+UADGKhbCk205CROIQmwaxwyO4Y0raodQCBgqUGPTmFlglA5Yu5C4aQH1y0PARTDYwcw5otaWYBWxrkGw3WEIat4otJ3QhqCHwA2gGswY+YIsAwBuGywEzF1VMoWBLAJ8UIZ0SYfCN6HZgXEAhNIA0MZpQjBAOw4xoiPFg4ApgNI1F3iO8acjDQVqVsNZQZGsjDh3DbKAglFHCGLIQEV1MGZmAqjJRppE6C2CYRKjCq0AI0fD1OcWjfZXQ7po6OYAYxhyHo2a36NcbBjUB4Y9w3aOpwM07wjI70ZrDOgiU9U4qdjwwBkApjhDQ9uFMSP1sZQWQbbviO0PtGSB2qSgI5ydGoAo92iagD0FgRdB1BajTmBM3zh6MGN0zCw7gFIBcQCjBxxYycdwCmSEN+Aq4+Cf2QygYskIW4I8av0fIowuOnOlYyHBOao8nhxACCfqNgnRj1Ulw2yFBP39PD8GrI-PmgB+HsJ9U4MQ3FeNSCCT9-bSOXwexdAmTAwIYCMDGA4Ag+Zeq+LADMEsmzD7RvxINAKkimYTIxgE+KCimink9Qxto+CflNdG6jMpv3cqYSOjH5TEx14GSZSjanijqp8kJSDJ6KmQIbJi7g9jNNkQ8w9IaozbskJBHojhp+w+0Y6n5HNDlpp09ftPxSnKA5RtEO6eyPgmWMzh0M17uGCmAusDxufSTtg2gGKUYAQaI2hs4xnUh6fDXt9wcVddXdtXXsLNkn2UR20e4TAMKMoTeLadimlLidHWwlmvuZZgoJWY0Q06Fdp+rxBYAgn2pHUiynCvdAV6t9iRKA5vezw5lIjhzvhW0K3moSvwN+pnfOGPWSWeQ0BjB4ZqbETFC0BDjzXg4HTt2eQuhAh7akwfErCj2wqI0CMAw9gXknQ0lHRDSmvVrR8hpgXohmh0S7Eig2AHkL+BMB9HbBJQdMcAF9UFL7diANc+0D3TkSdzoA9gyuYd1-9BDh0MQKbAENPd8N4F9AZBboC+rbhA2Zg6warxwWDzCFqvEhdJDCG+aJnXNLtxmlDmkxxPcILADe50WkuVvZPvTTgCzcaLFoVi0T3Ys09OLsAY3rxeHL0WH9jweCfCzkQb8x65eN7k7q3ESW-oHSic9XoYteg7w-0cJUD2n0+6rdZrEOUVpzUCnUebIAoD2W90NJfd9-fTWIxh4aWzL5Z-1I2bsu+LTLdW4mHgcp4PC2tk6k7ttt0UZz+Qd3W0FcHOq4HHOjArENtSlBEBoAycIgFAFIiCCGEV8DwN4DisVgZy+moRLXkwAlpfVcVtkPlwc5J9BLD1SnFMVY5CJxL9ffkFVZqv7o6rHFyq6YC2CU4geRO5tg4pasVWGr7Vzq+Tyhq9W2LHltq5QH6DIcpipA2q2NanOpRKcU1yhMNaxSjX+L41kgTpcssDHrLBl3QxJaHhmQXLMW4A45Y95lTCjuJsZnVKc4XlUAo+NHEAmpaXX6It18ifdcetYJ0c9rS67N2qk3WwpssdUDKC+sB9nrv1sYCm0HyCD3rgUz6-VPug-XycFIR5Ilb6C7KIOaaXZZ8AWXC9ncFAaQGPyAwD6Cbnk9qC8NM50B8xhYsm9IG7IMIagmTHE55OUMSgqbZQUoGLkJtkhYoHNyMeGCeAdLHO5E3NNQDRBCJfVpTZGzuKFu-0kEItwKeXmYZ4AH2S5moo0s43mCxdBAfTKkVigbgez1ARZFsZNNASUzGHfeBEpaWUwtgawfoBuA+DthxTnJ8EAGN5PjBDorti4O7YlBqEYr8cHIPCDmC7B9wBadK5UDxAxWgAA)

**Comment by apsavin** [comment]
cc @panagosg7

**Comment by jcready** [comment]
You cannot use `%checks` in Flow libdefs. You cannot have multiple predicate methods on an object either. See #4948 and #4254 for additional issues with `%checks`.

**Comment by panagosg7** [comment]
Unfortunately, `%checks` is not yet supported for methods.

**Comment by arahansen** [comment]
Cool, sounds like the limitations are at least known. Is there a roadmap I could track, or any plans for building out functionality for `%checks`?
