### ISSUE TITLE
Convert Optional Type Properties to Required

### ISSUE THREAD

**Issue by arahansen** [facebook/flow#5134]
I have a fairly common use case of typing server responses (specifically graphql responses) that contain many optional properties.

For example:
```js
type Animal = {
  kind?: string,
  age?: number
}
```

Where kind and age may or may not be defined for the response. I'd like to use this same type definition for my React components, the difference being `kind` and `age` are required properties that I would cover with defaultProps. So my React component might look like this:

```js
type Props = {
  kind: string,
  age: number
}

class Animal extends React.Component<Props> { 
  static defaultProps = {
    kind: 'dog',
    age: 2
  }
  ...
}
```

is my only option to rewrite the entire type definition of Animal, minus the `?` syntax? Or is there a way to tell flow that I want to use the Animal type, but make all properties required properties?

**Comment by apsavin** [comment]
You do an opposite thing

[try](https://flow.org/try/#0C4TwDgpgBAggdgSwLYEMA2UC8UDeAoKKAawTgBMAuKAZ2ACdSBzAGgKhUYirgFckAjCHTwBfPHlCRYiVGgDKQgG5CAShGpgA9nGrRsAEjkALFJAA88ZOgB8AbnGKUdKHRT9+CYFUuysuYqSUUADkru6ewczsnFQAjFAi9o7OYR7ACnTKdGoa2rreMugZWTlaOnr+JORUoW5pwQn2eAD0zVAAonR0mnTUFHjJLnWexarqZfnSVvJKY7nlfjhQAO7dcIwACt1gVPQ80IkDTkPhXlO+2EtVQbWnDYlAA)

**Comment by skyrpex** [comment]
`$Shape` works great! Why isn't it documented?

**Comment by apsavin** [comment]
@mrkev Do you know why no one from [PRs with docs for $Shape](https://github.com/facebook/flow/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%24shape) do not merged?

**Comment by mrkev** [comment]
no idea, maybe it fell of the radar ¯\\_(ツ)_/¯

**Comment by FlavienBusseuil** [comment]
Any progress on the original issue by any chance?

**Comment by gkz** [comment]
> Any progress on the original issue by any chance?

New type utilities like this are blocked by another project which we are actively working on.

**Comment by SamChou19815** [comment]
We now have `Required`
