### ISSUE TITLE
Type of 

### ISSUE THREAD

**Issue by zgotsch** [facebook/flow#5136]
If this is a bug, please try reproducing using https://flow.org/try/.

**Comment by CharlesStover** [comment]
what about type of

**Comment by apsavin** [comment]
Try [this](https://flow.org/try/#0FASwtgDg9gTgLgAgFQIIYGcECUCmqDGiAZjFGAgOQx6EXDBwCeEOCACqRJgLwIDeAH2ABIABY4ANhKgAuBOjgwQAOwDmAGmAIEwolFkJlAVzAAjHDE3DqygCYW5AEgAiIIkQA8HKF3X8b9jByAGJGyoQgUMoAvgB8CNzxuARwAHQAclD2mgLRANz0+BIYmADCUXCoKhYIOAAecDh2mMmEqeWQUU1wXpzo8XxaCAEWABQAlPxD2vhRCvzDTYF+qatQcOIw3lwI0QkIGyDoqRB9Bdra1HBGMMqLdmPrm9vo4+e7wNGFc4izncrdfajEQecrKSrVGAiMSSaTcABEAHdYBJbPDoXooNw+ABGABMAGYvhcSQhTKgYAjULYiNSiOjhNYlhZsacfDwBtDhAB6bkIAAq4gOzFYUCICDZO3QoigRlRZJwXN5U0ZPL5MKkBgUSjUVkZyt0+jkxjMFj1ao+qt5Sr5qDshnWNpV+vVmONJnMlidGukcm1Kg03pGQQQwKt6uEAH05HbGN7JokEAB+MMunTCASGD0Wb0Z+SKAO5zOmfQSPDKIvYGhwRwAUTLYG6HljsUrAElGjBUKYy83lIxYuNzcqvqq8qNJeg5IIEOJNX6C7qEG6s6aYAhcuN6KrZsp0FAy6lpKoJ30t6qrjc7h5bCAAG6xPiT1Jz6TRDzc28P6HRUfc1tbkAA)

**Comment by apsavin** [comment]
@zgotsch If I helped you please close the issue

**Comment by zgotsch** [comment]
Oops looks like I misclicked when I was opening an issue -_-
