### ISSUE TITLE
Anonymous functions with type parameters and function signature on left hand side sometimes don't type check when they should

### ISSUE THREAD

**Issue by eeasley-coursera** [facebook/flow#5138]
See short example at https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjAF4iBXbDfASxwB4BBAPgAoAPALjEYEpvGYAN5gATgFN85UdjDsA3GAC+8zDgJgA5t1bZyAWwBG40b1LMweoydIUqtHBzMiJUmXMUq1eQgAtuTGx85jy2UJTUdNhOwmKS0rIKyqpYPmA0ASyswSQWAG5wNAAmYREO0ezOcW6ylEXiUDTY4kWeqkA

I'd expect `h` to work just like `f`, `g` and `i`.

**Comment by SamChou19815** [comment]
now all of them type check
