### ISSUE TITLE
[Feature] Provide a type for React's componentDidCatch error info

### ISSUE THREAD

**Issue by ide** [facebook/flow#5139]
React's componentDidCatch method has two parameters, the `error` and an `info` object whose type is defined inside of React but isn't exported (https://github.com/facebook/react/blob/b52a5624e95f77166ffa520476d68231640692f9/packages/react-reconciler/src/ReactFiberScheduler.js#L29):

```
export type HandleErrorInfo = {
  componentStack: string,
};
```

It's a very simple type but would be nice to be able to just write:
```
import * as React from 'react';
...
componentDidCatch(error: Error, info: React.ErrorInfo) { }
```

(Apologies if this belongs on the React repo instead.)

**Comment by wmonk** [comment]
Will there be any movement on this? Happy to open a PR if help is wanted 👍

**Comment by techieshark** [comment]
Is this really fixed?

The original issue says:

> would be nice to be able to just write:
```
import * as React from 'react';
...
componentDidCatch(error: Error, info: React.ErrorInfo) { }
```

As far as I can tell, when using flow, `React.ErrorInfo` is not actually defined, despite this issue being closed as fixed. 

I see that there is a type definition apparently deep inside React ([here](https://github.com/facebook/react/blob/b52a5624e95f77166ffa520476d68231640692f9/packages/react-reconciler/src/ReactFiberScheduler.js#L29-L31)), yet I can also see that flow/lib/react.js is not using that (see [here](https://github.com/facebook/flow/blob/0dba4d316012c7c0401224e393cdd98d562d30b6/lib/react.js#L79)). 

When I try to use the code in the original issue description, flow fails:

```
Cannot get React.ErrorInfo because property ErrorInfo is missing in module react [1].

 [1]  2│ import * as React from 'react';
       :
     25│     this.state = { error: null };
     26│   }
     27│
     28│   componentDidCatch(error: Error, errorInfo: React.ErrorInfo) {
     29│     this.setState({ error });
```

Please correct me if React.ErrorInfo is somehow defined. I've seen references to it online ([example](https://stackoverflow.com/questions/51085983/ways-to-redirect-user-after-componentdidcatch)) but [this comment](https://github.com/facebook/flow/issues/2464#issuecomment-372064628) suggests it may only exist in Typescript.

**Comment by dominicfraser** [comment]
This also suggests it is not available: https://github.com/facebook/flow/blob/4312cba4bfccaf3ea38bfc1a882e10151ed2b35e/lib/react.js#L77

```
componentDidCatch(
    error: Error,
    info: {
      componentStack: string,
    }
  ): mixed;
```

It would be good to know if it will make its way there, or if I've been looking in the wrong place?

**Comment by intgr** [comment]
> Cannot import ErrorInfo because there is no ErrorInfo export inreact.Flow(InferError)

Not sure when this got fixed, but `React.ErrorInfo` type now exists in latest `@types/react` versions.

**Comment by danielo515** [comment]
So... is casting to any the only solution?
