### ISSUE TITLE
"Statics of class / Property not found in object literal" error

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#514]
Providing an object literal as an argument that's required to be an instance of a class that extends another class doesn't appear to work right.

Moving the bubbles and cancelable properties out of EventInit into CustomEventInit and making CustomEventInit not extend anything causes this to work. Alternatively, providing an empty object to CustomEvent's constructor when it's called at the end works too.

```
/* @flow */

declare class EventInit {
  bubbles?: boolean;
  cancelable?: boolean;
}

declare class CustomEventInit extends EventInit {
  detail?: any;
}

declare class CustomEvent extends Event {
  constructor(typeArg: string, customEventInit?: CustomEventInit): void;
  detail: any;
}

var event = new CustomEvent('foo', {
  bubbles: true,
  cancelable: false,
  detail: {a: 42}
});
```

```
[chris ~/Coding/flow-test]$ flow --version
Flow, a static type checker for JavaScript, version 0.12.0
[chris ~/Coding/flow-test]$ flow check

/Users/chris/Coding/flow-test/foo.js:17:13,21:2: constructor call
Error:
/Users/chris/Coding/flow-test/foo.js:8:1,10:1: statics of CustomEventInit
Property not found in
/Users/chris/Coding/flow-test/foo.js:17:36,21:1: object literal

Found 1 error
```

**Comment by AgentME** [comment]
Actually, I might be misunderstanding how declared classes work. I expected these two things to be equivalent:

```
declare class CustomEventInit /*extends EventInit*/ {
  detail?: any;
  bubbles?: boolean;
  cancelable?: boolean;
}

declare class CustomEvent extends Event {
  constructor(typeArg: string, customEventInit?: CustomEventInit): void;
  detail: any;
}
```

```
declare class CustomEvent extends Event {
  constructor(typeArg: string, customEventInit?: {
    detail?: any;
    bubbles?: boolean;
    cancelable?: boolean;
  }): void;
  detail: any;
}
```

but only the latter works when some of the properties aren't provided:

```
function triggerRelayEvent(element, detail) {
  var event = new CustomEvent('foo', {
    //bubbles: true,
    cancelable: false,
    detail
  });
```

Is that intentional? Is there some other feature that works the way I'm expecting?

**Comment by jeffmo** [comment]
That's right. In Flow, using a class name as a type annotation refers to a nominal type rather than a structural type. This means that the thing that's checked against the annotation must be an instance of the specified class or an instance of a child class of the specified class name.

So the following cases error/succeed:
```
class Base { baseProp: number }
class Child extends Base { childProp: string; }

var a: Base = new Base(); // valid
var b: Base = new Child(); // valid
var c: Child = new Base(); // Error: Base is not a subtype of Child
var d: Child = new Child(); // valid

var e: Base = {baseProp: 42}; // Error: This object is not an *instance* of Base!
```

If you're looking for structural typing, you probably want to define these as type aliases instead:

```
type BaseT = { baseProp: number };
type ChildT = BaseT & { childProp: string };

class Base { baseProp: number }
class Child extends Base { childProp: string; }

var a: BaseT = new Base(); // valid
var b: BaseT = new Child(); // valid
var c: ChildT = new Base(); // Error: Base instances don't have a 'childProp' property!
var d: Child = new Child(); // valid

var e: Base = {baseProp: 42}; // valid
var f: Base = {baseProp: 42, someOtherCrazyProp: 44}; // valid
```

**Comment by jeffmo** [comment]
(Note that we recently added support for `interface` definitions that are also typed structurally if that feels more natural for you. Note, however, that we haven't yet built out the `extends` clause for them though. It's a TODO, just not yet TODONE)

So, at some point (hopefully soon), this will be another alternative to my suggestion of using type aliases above:

```javascript
interface Base { baseProp: number; };
interface Child extends Base { childProp: string; };

// ...
```

**Comment by AgentME** [comment]
That makes sense! Though why does this work?

```
/* @flow */

declare class CustomEventInit {
  bubbles?: boolean;
  cancelable?: boolean;
  detail?: any;
}

declare class CustomEvent extends Event {
  constructor(typeArg: string, customEventInit?: CustomEventInit): void;
  detail: any;
}

var event = new CustomEvent('foo', {
  bubbles: true,
  cancelable: false,
  detail: {a: 42}
});
```

**Comment by jeffmo** [comment]
Hmm...well that's interesting. I think this might be a bug with `declare class` statements. If you turn these declares into a non-declare, it works as expected with nominal types...

**Comment by jeffmo** [comment]
Hmmm, well that's interesting... I'm not sure why this isn't erroring :(

Will have to take a closer look here, thanks for the report!

**Comment by mroch** [comment]
is that structural subtyping, @gabelevi?

**Comment by avikchaudhuri** [comment]
@AgentME @jeffmo Good story around this one.

The original example should no longer error with an upcoming fix of how declare class inheritance works.

Now, full support for interfaces are coming soon too. Recently we introduced structural subtyping against interfaces. But since interfaces don't yet support proper inheritance, currently we model many things with declare class that we should model ideally with interfaces.

When we have both, we will decide how subtyping against declare class should behave. The current thinking is that it will compare nominally with other classes, but structurally against object types. So your example should continue to work.
