### ISSUE TITLE
Methods created by $ObjMap don't seem to be checked.

### ISSUE THREAD

**Issue by tempname11** [facebook/flow#5141]
Minimal example:
```js
declare var thing: $ObjMap<{ foo: number }, <X>(X) => (X => mixed)>; 

// no error :(    
thing.foo('bad');

// no error :(
(thing.foo: ('bad') => mixed);

// ok, error
(thing: { foo: ('bad') => mixed });
```
Playing around with the argument and return types, exactness and variance didn't help.

Try [here](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AuALAlgOwOYC54ASAeQCMArAWSgAcAeAb3gDMB7Nw7AVwFsyQMeAF8ANPHoANAHwAKSQEp4AXmnx5Ktb0wAPEMAXSA3PABQpgPQX42NvEEw2Q-LPhuzGHLgB07NrIByMihgAIUjcysbOwcneBdTWU88Xw5CQODQpVV4bT0DCMtrNgBrcViYROSCeGY-dKCQsM1c3X0RcKA).

**Comment by c58** [comment]
Probably related case
```
type AnotherThing = $ObjMap<{ foo: number }, <X>(X) => (() => X)>; 
    
// no error :(
const test: AnotherThing = {
    foo: (): string => {
    	return '123';
    }
}
```

**Comment by kogai** [comment]
Probably I'd encountered the same situation.

And in those cases, polymorphic mapping function type (like `<X>(X) => (() => X)`) seems to equivalent as `Union` of possible types.

For instance,  in case of @tempname11 , mapping function type `<X>(X) => (X => mixed)` seems to behave as type like `(string | number) => (string | number) => mixed`.

That behavior seems not to intended one 🤔 

Additional one more thing, such odd behavior occurred in case of Array and Tuple.

```javascript
type AnotherThing = $ObjMap<{ foo: number }, <X>(X) => X[]>; 
    
// No errors! :(
const test: AnotherThing = {
	foo: [""],
}

// Error occurred, but it caused by incompatibility of string and string | number.
const val: string = test.foo[0];
```

Try [here](https://flow.org/try/#0C4TwDgpgBAggdge2ACwgJwCrIJZwOZQC8UAJAPIBGAVgLICGYAPAN5QBmCCAXFHAK4BbCuigBfADRRGADQB8ACmkBKIrKjSA2gF1ZAbigAoKMcMB6U1AByCKOjQI0AZwCEULvIMBjBHEfAowBB+PPBIqJg4+ERQzAYAkBzcUBoARCla4gaiBgbmUACiaPZoUAiennxFEAAmkhR8-tj+nnR8jjVQFCBQuN4CYHTA2BTYADZN3QhsUH5ouAR0cNUzwHNRAD68gsJoAHRePn5QAG50ozyz89GBfruJGgAMWrpAA)

**Comment by zerkalica** [comment]
May be similar bug, result is an object.

```js
type Todo = {
  id: string;
}

type Atom<V> = {
  set(v: V): void;
  reset(): void;
}

declare function f<V>(v: V): $ObjMap<V, <T>(T) => Atom<T>>;

const data: { todos: Todo[] } = { todos: [] }
const a = f(data)

// $ExpectError string is not a Todo
a.todos.set('test')
```
[flow/try](https://flow.org/try/#0C4TwDgpgBAKg9gEzlAvFA3gKClAlggLigGdgAnXAOwHMBuTAX001EigEFg4BbAHgDUAfKgzYSEYAAoAbkX4BKItLj56OMhGITJiqMtWNmCCAGMANgEMNUAGYBXSieC44lWwMEy5ugCQB5ACMAKwBZCzABABooXhhPGHlUYU4eWMFBekwTV1IoBAtgCyJ0KC4kYiJ4JABtAF0oBhESsrgKqDqGrJzgKAsRG0l8wvlmAHpRqB8AUQAPSCcpsjI4MhJyKmo8YihKOB6+qrhMCwA6FuITrSkAcmBNYGuRoA)

Same example in typescript works fine: [ts/play](https://www.typescriptlang.org/play/#src=type%20Todo%20%3D%20%7B%0D%0A%20%20id%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Atom%3CV%3E%20%3D%20%7B%0D%0A%20%20set(v%3A%20V)%3A%20void%3B%0D%0A%20%20reset()%3A%20void%3B%0D%0A%7D%0D%0A%0D%0Adeclare%20function%20f%3CV%3E(v%3A%20V)%3A%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20V%5D%3A%20Atom%3CV%5BP%5D%3E%3B%0D%0A%7D%3B%0D%0A%0D%0Aconst%20data%3A%20%7B%20todos%3A%20Todo%5B%5D%20%7D%20%3D%20%7B%20todos%3A%20%5B%5D%20%7D%0D%0Aconst%20a%20%3D%20f(data)%0D%0A%0D%0A%2F%2F%20%24ExpectError%20string%20is%20not%20a%20Todo%0D%0Aa.todos.set('1')%0D%0A)

$ObjMap doesn't work with classes (may be #3797):

```js
type Todo = {
  id: string;
}

type Atom<V> = {
  set(v: V): void;
  reset(): void;
}

declare function f<V>(v: V): $ObjMap<V, <T>(T) => Atom<T>>;
// Flow bug: object map. Expected object instead of
    
class A {
  todos: Todo[] = []
}
const a = f(new A())

// $ExpectError string is not a Todo
a.todos.set('test')
```

[flow/try](https://flow.org/try/#0C4TwDgpgBAKg9gEzlAvFA3gKClAlggLigGdgAnXAOwHMBuTAX001EigEFg4BbAHgDUAfKgzYSEYAAoAbkX4BKItLj56OMhGITJiqMtWNmCCAGMANgEMNUAGYBXSieC44lWwMEy5ugCQB5ACMAKwBZCzABABooXhhPGHlUYU4eWMFBegB6TKgAMTM4AHcoALtqIjhg02AobnCAOigAUQAPSCcIBChKoOq8SlIICy64GzEcTHMLYmIOURwuJGIieCQAbQBdEU3DE1dSKAsRG0lKCGL2HXlmbKgfVvbgJrIyODIScipqPFnKOBqjqs4JgLPVFnBiPUtFIAOTATTAGHXIA)

In typescript similar example works with classes: [ts/play](https://www.typescriptlang.org/play/#src=type%20Todo%20%3D%20%7B%0D%0A%20%20id%3A%20string%3B%0D%0A%7D%0D%0A%0D%0Atype%20Atom%3CV%3E%20%3D%20%7B%0D%0A%20%20set(v%3A%20V)%3A%20void%3B%0D%0A%20%20reset()%3A%20void%3B%0D%0A%7D%0D%0Adeclare%20function%20f%3CV%3E(v%3A%20V)%3A%20%7B%0D%0A%20%20%20%20%5BP%20in%20keyof%20V%5D%3A%20Atom%3CV%5BP%5D%3E%3B%0D%0A%7D%3B%0D%0Aclass%20A%20%7Btodos%3A%20Todo%5B%5D%7D%0D%0Aconst%20a%20%3D%20f(new%20A())%0D%0A%2F%2F%20%24ExpectError%20string%20is%20not%20a%20Todo%0D%0Aa.todos.set('1')%0D%0A)

**Comment by SamChou19815** [comment]
This is now fixed
