### ISSUE TITLE
How to import flow types from react?

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5147]
I can't for the life of me figure out how to import a type from React -- @types/react/index.d.ts

I think the namespace is what's throwing me off, and I can't find documentation anywhere on how to import with namespaces.

I'm looking for something along the lines of:

    import type { ErrorInfo } from 'react';

Where ErrorInfo is located in

    export = React;
    export as namespace React;
    declare namespace React {
      interface ErrorInfo {
        componentStack: string;
      }
    }

How do I use this ErrorInfo definition in my file?

**Comment by EugeneZ** [comment]
I think you're in the wrong repo. That's a typescript definition! 😮

**Comment by CharlesStover** [comment]
Is that not where Flow pulls its types? I've been doing `import type { TypeName } from 'package'` with success for all things outside of React. I guess the TypeScript definitions have all been the same as the Flow definitions for every other use case.

How do I get the Flow type in this case?

**Comment by EugeneZ** [comment]
React types come from the core flow libs. I think you need to wait for a Flow update.

**Comment by TrySound** [comment]
Definitions of react are kept here
https://github.com/facebook/flow/blob/master/lib/react.js

This probably can be closed.
/cc @vkurchatkin
