### ISSUE TITLE
Literal types don't get validated when they are a part of an object

### ISSUE THREAD

**Issue by Li0liQ** [facebook/flow#5151]
```javascript
const TestString: 'test' = 'test';

type TestObject = {
    test: typeof TestString,
};

const t: TestObject = {
    test: 'test'
}

switch (t.test) {
  case TestString:
    console.log('valid');
    break;
  case '42': // flow doesn't fail here :'(.
    console.log('invalid');
    break;
  default:
    console.log('default');
    break;
}
```

[Try it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzABUBTAgZXwCcBLbAcwC4wByfM-FsAXlfYJYBudPgCeABxLEOAeQBGAKxIZCvAN6owWsP3zMxkuFGkVqdegBpUAX2GYcBHc1IF5SlTzAaAkLuZsOFht0XAQafAwACzAACnwAOl0ASi9NMAwAQ1wpF3xKWgZGNK0sPDgYEnj4ehiWADcMmBoAExYk4W0wOSoSDIBrDvSsqRYAFgAmFmZgYDBYRDBmuDJsNjmMmhgwSJIesEYWGPji9Idyyuraugam1vaT7t6BtOaSKAyAVxg9E9Lcc6qcBqLFe7y+nHunUe-WE1iAA)

Adding `const tt: typeof t.test = t.test;` and using `tt` for switch enables the validation, but that is the behaviour I would expect flow to have by default.

Related issue: #3380.

**Comment by TrySound** [comment]
Fixed https://flow.org/try/#0MYewdgzgLgBAKgU2gZSgJwJZgOYC4YDkUSUBMAvIcdAQNwBQ9UAngA4LwkDyARgFYJgsSgG96MCTGpR8LdiABmnFOizYANPQC+DeqEiwZyqLwFCKMMZKkl8REgW2MIAdwxRgACxgAKKADppAEpLcRhgAEMIDkQVTBxcMIl9CBAAGwR-NJBsHwIANwi0jAATAiCGax40BAiAa0rwqI4CABYAJgJ8AHpumAVslxgSkCQwIn6IjDSYTwQamFwCH38k8PBUjKycvKxC4rKKterahrCShAUIgFc0mTWU9Mzs3IILq9vSI6qa+oYtIA
