### ISSUE TITLE
Can't decide between union type cases when using object spread

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#5154]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN7b4BcYA5AK4DOeATgwDRgCGA5nnoA7JgFsARhwC+YAD5UaQxv3ZwmOBvMY41AKzwBjDNzAsAlgC9loyTPRQmw4+bjCwUEgAoJvdvWI4AEoAkipUAEh2PAwmdndKADpk33ZpVHSgA

**Comment by rsolomon** [comment]
There's some discussion on this issue in #1488 and #1511

**Comment by villesau** [comment]
this will fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors in master
