### ISSUE TITLE
How to typehint union props, using props from component with defaultProps set

### ISSUE THREAD

**Issue by JCMais** [facebook/flow#5155]
The title is confuse.

But see the following to understand what I'm saying:

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUcwBnAQTgF44BvcuAXEwQIALjgAjEQBtUAOwA05AL6U00lCxZwAwrjAckADxhI5AE23J0MAHR7wEOWZgAeJhFZsAfL35wWGBQYYDQ4cyRMFABXaRgPVi4-QSERcRgoaKQlAWUKVSpaegSWACEkko4AMmTBCRQocSkIWRRFFTUNLV19cuNTCytiOwdIZzk3EtLfHgLyAHp51Ig4JCgcKBYFSQbwiCRtOQgYcldR8vqoOHnvIA

Am I required to repeat the defaultProps on CompB?

There is any other simple way to say that a component is just a wrapper to another one, passing down all the props that are not from themselves?

**Comment by SamChou19815** [comment]
Now it wokrs
