### ISSUE TITLE
Idea: keyed generic type params like `ReactElement<S=UFILikeState>`

### ISSUE THREAD

**Issue by ide** [facebook/flow#516]
Here's a thought -- what if you could define just some of the param types of a generic type?

My thinking is that generic types like ReactElement end up with a long list of param types that sometime are tedious to specify. There already is DefaultProps, Props, and State, and soon Context or maybe some Observable type will join the mix too. So if you want to declare the type of a React component that has Context of a certain shape but you don't care/know/want to specify the types of Props, State, etc, it's sort of a hassle. It'd be nice to write `ReactElement<C=MyContextType>`.

I bet this could help with simpler types like Maps too. Instead of `Map<any, string>`, one might write `Map<V=string>`. It does a better job of communicating that the programmer didn't get around to specifying the type of Keys, while with `Map<any, string>` it's not clear whether the programmer was lazy or actually intended for the Map to accept `any` Keys.

**Comment by avikchaudhuri** [comment]
@ide we recently introduced * as something you could write when you're lazy / want inference to take over, but don't intend `any`.

So, e.g., you could write Map<*, string> to mean Map<T, string> for some T.

Next, you could define type aliases to make your life easier, like:

MapOf<V> = Map<*, V>

Currently we support leaving out all type params, so something like : Map gets desugared to : Map<*,*>. We don't support partial instantiation for various reasons, not all of them reasonable (e.g., we have some implementation difficulties as well, in addition to possible programmer confusion). Your idea of named type arguments is excellent, I'll see what I can do.

**Comment by ide** [comment]
> we recently introduced * as something you could write when you're lazy / want inference to take over, but don't intend any.

Love it! Thanks for the tip!

**Comment by calebmer** [comment]
Closing as the issue was resolved. We’ll continue to think about this feature 😊
