### ISSUE TITLE
Flow doesn't type check the 'this' pointer? I have an example where Flow doesn't complain

### ISSUE THREAD

**Issue by lvdang** [facebook/flow#5162]
If this is a bug, please try reproducing using https://flow.org/try/.

I am calling a this.props.saveRef(this);, saveRef: (React.ElementRef<typeof Foo>) => mixed.

Is my use of ElementRef<typeof Foo> correct for this pointer?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqgQCe2amAAKzbGQAqw0QF4wAb1Rg1ZEgDdqNKAC4wAChr0CAOgCiMapmoA7AroA8QkXChgAYnDgA+AJRg8r5gmOgAHtQAJgA0qAC+fKh0MOQU3nBg1OEE9lEUJgxmYgCunADCLLh29gROEnBSsiIhKmpgdHB2ZAR4JQz4htiSZAYNTXKBbe1gZCUieEMj-nwzYAQAFuhkZsONOxrauoab2ytgwMAAkhSnFJ14nAwA-Kpq8Qn8rqLjZABCPmaCmUbzsJFsBh6eHQdgA5nEEkkUmkwADMtlcnZ8lQuOZShUql1avURmiga03p1ur1+gRBnspGNSYDJiCZnMFkt9is3mo7mZDjpqB5FPzBbozAAjGFRE5bMg896qN7i4UGQyBYKhCLRJLqLRCqCGaiaAgGQrmKw2WrOb7uLw+ALKC7AMA3dbyjr4J5EEoaWHUV7tN4fNRvThY6iLKa8sCcAhlOxGWPtJwZWYG3TyJRizPC+IXXwpxVgD4fVBONFgMG2eRsEhsYC+IA

**Comment by SamChou19815** [comment]
Flow errors due to duplicate declarations
