### ISSUE TITLE
Setting boolean typecheck not working

### ISSUE THREAD

**Issue by ehtb** [facebook/flow#5163]
Hi, please see this code:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodUCuA7AxgFwEs5sx8BTAZ3zAAp8AuMAfmoCdDsBzASjAG9UASFwlqZAJKUAyvg7cwAXjIBPAA7k4UMksXKA5O05d9qMObDBgYcmzZw2lMxdHZxAQwCMSyTLnGwADJAsH13ACNcfQA6TlwYTAATKnoeYVdxcO9lfClZeS4gkLDImLZyNRh3XHJ6ABpQ-TSLMGdzKzBKTFwayicWjJp3ACYffHVNbRo9AyNufSLQiKjYvATkylT0sRpw0ZyJrR0Z0LmTRZKV8srq2vwG-SbUAF8gA

Is this an issue, or is the latter implementation the (only) correct one?

I would assume that since the boolean check was in the previous line, is a constant and there could not have been any mutations, the type should've been correctly checked.

**Comment by SamChou19815** [comment]
It happens because we don't track refinements stored in consts.
