### ISSUE TITLE
Flow not initializing on Windows 10 after update to fall creators update

### ISSUE THREAD

**Issue by zonzujiro** [facebook/flow#5165]
Hello!

When I'm trying to launch flow, I see only this:

```PS C:\Users\Ivan\Documents\projects\phase-II> yarn flow                                                  
yarn run v1.2.1
$ flow
Launching Flow server for C:\Users\...
Spawned flow server (pid=3272)
Logs will go to C:\Users\....
flow is still initializing; this can take some time. [processing]
 ```

I tried with flow `0.57.3` and `0.56` — the same result, nothing. No errors, no warnings.
I reinstalled `node_modules` couple times, turned off `Windows Defender` — not helped too.

**Comment by Log1x** [comment]
This is an issue with the Fall Creators Update and is reported [here](https://github.com/Microsoft/BashOnWindows/issues/2448).

**Comment by zonzujiro** [comment]
The issue from your link is with linux subsystem in windows.

I don't think this is a case because I'm not using WSL.

**Comment by zonzujiro** [comment]
Well, I installed WSL and launched `flow` from there. It helped.

But this is a terrible way to solve the problem. I must keep the whole OS for launching only one flow.

**Comment by mrkev** [comment]
Closing since @Log1x mentions this is an issue with windows https://github.com/Microsoft/WSL/issues/2448 which seems to have been resolved. Lmk if that's not the case though.
