### ISSUE TITLE
How to export types in case of using CommonJS export?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5167]
ES6 modules system is used in the project.
I use to have different functionality for server and browser environments and I use to declare them in such code:

index.js
```
if (process.env.TARGET === 'SERVER') {
    module.exports = require('./serverModule');
} else {
    module.exports = require('./browserModule');
}
```
but in place where I use it flow doesn't know about those modules types thought they are present in the modules.

How export modules with flow types in right manner?
Help me please.. Thanks

**Comment by kogai** [comment]
I'm not confident understand the question properly, but I'll give it a try code such below when I'd encounter the situation to export multiple typed modules 🙏 

```javascript
// @flow

// module.js
const server = require("./serverModule")
const browser = require("./browserModule")

type Exportable = {
	type: "SERVER",
  	module: typeof server,
} | {
	type: "BROWSER",
  	module: typeof browser,
}

if (process.env.TARGET === 'SERVER') {
    module.exports = {
      	type: "SERVER",
    	module: server,
    }
} else {
    module.exports = {
      	type: "BROWSER",
    	module: browser,
    }
}

// app.js
import module from "./module"

if (module.type === "SERVER") {
  // We can use module as typeof server
  (module.module: typeof server)
} else {
  // As well as browser
  (module.module: typeof browser)
}
```

**Comment by budarin** [comment]
@kogai the idea is dynamic import modules under conditions - not statical

**Comment by SamChou19815** [comment]
This pattern will not be supported to make export analysis for commonjs solvable
