### ISSUE TITLE
flow doesn't like class output from gen-flow-files

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#5169]
`flow gen-flow-files file.js` on:

    export default class FlowBuild extends WatchmanCompiler {
    }

yields:

    declare export default class extends any {
    }

on which flow then throws:

```
  6: declare export default class extends any {
                                  ^^^^^^^ Unexpected token extends
```

**Comment by vincentriemer** [comment]
Hit this issue today, it appears that when a class is the default export the gen-flow-files command makes the class anonymous but it also can't seem to handle anonymous classes when using the resulting files itself.

**Comment by arabold** [comment]
This is still an issue with 0.66. Ran into it today. It's actually quite tricky. Does anybody know a workaround?

**Comment by MarkKahn** [comment]
@arabold -- I just copy the source files to `outputDir/source.flow.js` for now

**Comment by steida** [comment]
https://github.com/AgentME/flow-copy-source

**Comment by steida** [comment]
https://github.com/facebook/flow/issues/5871

**Comment by chixor** [comment]
For cases such as these we edit the offending `.flow` file outputted from `gen-flow-files` and commit to the repo. Much better than duplicating the entire source code into `/lib` via `flow-copy-source`!

**Comment by TrySound** [comment]
gen-flow-files is removed. A replacement is coming soon.
