### ISSUE TITLE
Function treated as object even though parameter is explicitly notated as object

### ISSUE THREAD

**Issue by vojtatranta** [facebook/flow#5174]
This code: 
```js
// @flow

const fun = (a: string, b: {c?: string, d?: number}) => {

  return {...b, a}
}

fun('test', () => ({'a': 'test'}))
```

Does not raise an error.

It should in my mind raise an error, even though function in Javascript are objects.

The problem is apparently in the fact that properties of `b` parameter of `fun` function are not required.

I understand that functions are objects, but this may lead to the bugs very easily. Is there any way ho to disable this behavior?

**Comment by AugustinLF** [comment]
The (only?) way to mark an object as "not a function" is to type it as non callable, with the `$call` property, see [this example](https://flow.org/try/#0FAYw9gdgzgLgBAMwK4TgXjgCgIYC46wBOAlhAOYA0cARvgN4gD8+RplcAJs3BEgLbUApoSoASENgA2k-ADcwxDgF8AlOgB8cOsGBw4hQTCSFUdAHQXqVbEuC3gyCJgDkMQbGdVMatJsx1nbGd8V3cYZ1UVIA)
```javascript

const fun = (a: string, b: {c?: string, d?: number, $call: void}) => {
  return {...b, a}
}

fun('test', () => ({'a': 'test'}))
```

**Comment by apsavin** [comment]
Another way: https://flow.org/try/#0FAYw9gdgzgLgBAMwK4TgXjgCgIYC46wBOAlhAOYA0cARvgN4A+IA-PkaZXACatwRIBbagFNCcBgF8AlOgB8cOsGBw4hYTCSFUdAHR7qVbBODHgyCJgDkMYbEtVMMtPMx1L2S-mu2Yl6VKA

```
const fun = (a: string, b: {|c?: string, d?: number |}) => {
  return {...b, a}
}

fun('test', () => ({'a': 'test'}));
```

**Comment by vojtatranta** [comment]
@AugustinLF thank you for the response.

It'll be really cool if I could somehow specify such behavior in the config.

I found another solution around it, which is, I think, a bit nicer:
```js
// @flow

const fun = (a: string, b: {| c?: string, d?: number |}) => {

  return {...b, a}
}

fun('test', () => ({'a': 'test'}))
```

By using `{| |}` exact operator, passing a function throws an error.

But still it is quite dangerous...

**Comment by jcready** [comment]
@AugustinLF for your workaround you should replace `$call: void` with `$call?: empty` otherwise plain objects won't be able to be passed in either:

```js
fun('test', {})
```

**Comment by vojtatranta** [comment]
Anyway I close this issue. Feel free to open it if a new config variable is introduced for such purpose.

Thanks!
