### ISSUE TITLE
fail type matching when using React.createElement with specifing annotated props

### ISSUE THREAD

**Issue by OsugaHiroshi** [facebook/flow#5175]
Using createElement with following condition, `type is incompatible` error will occur.
1. define component specifing props type __having one or more properties__.
2. define a variable __with type annotation__ to specify props when creating its component
3. call createElement with its variable

```js
// @flow
import * as React from 'react';

type Props = {
  index: number,
};

class MyComponent extends React.Component<Props, void> {}

let propsA: Props = {// with annotation
  index: 1,
};

let propsB = {// without annotation
  index: 1,
};

React.createElement(MyComponent, propsA); //why error?
React.createElement(MyComponent, propsB); //works

//these work
function foo(val: Props) {} 
foo(propsA);
foo(propsB);
```

This may be from 0.54.0 and 0.57.3 is the same.

Is this a bug ?

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciiOAnukqgACo3RkAvKADeiUKGQA7ACaUAHgC5QSgK6oARpSwAaRAF8eiGtFJkAsvwDCTTEspK8GnB5VkqtDgAdC4YsO6eADxisBImoABusMgqAHyy5rzQlHjo4iQAgtoxEqDSMiCg8Mg4ABbESkqwOEQ4yOHyiqoa2gCMZpZZOaB5sSQAQmWyldV1sLp4RI3Nre1KncpqWqD9FlYBdEE07K2UAKLZqB44ABSOoW7X8aMSBQCUXKAg8LX8oMaMLAAfkQB2Cx2oPgulCunjuzlc4SeI3y4w+X2A8GwAGsSLwQHVKCRhFisNjEJBdEo6GtQJBYLAbgkiNBivk3hlQBSGTcXoUPtzGXy0VwgA)

**Comment by jamesisaac** [comment]
Fixed as of v0.59
