### ISSUE TITLE
Tuples union type problem

### ISSUE THREAD

**Issue by sparlampe** [facebook/flow#5178]
Hello, I am trying to adopt d3.array [definitely-typed definition](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/d3-array/index.d.ts#L86) to flow. At some point I need to type something like below:
```
function func(i:number|void):([number,number]|[void, void]){return [i,i]}
```
and
```
const func = (i:number):number=>i
let y: [ number, number] | [void, void];
const t = func(1)
y = [t,t]
```
Neither the [former](https://flow.org/try/#0GYVwdgxgLglg9mABKSAKGAuMIC2AjAUwCcAfANzhgBMBKDVAbW32IBpnCiBdEhi61on5UuNAN5ECUEESQMYrGFwC+QA) nor the [latter](https://flow.org/try/#0MYewdgzgLgBAZgVzMGBeGAKAlgLjAgWwCMBTAJwEo9DSzUA+LAKABsTYBPHGAbRn2LkANPxrkAujAA+vAG4gsAExHyl4gNxNQkWLHSJkGAIwUmHNLyhCo4oA) typechecks. How can I make it typecheck?

**Comment by jcready** [comment]
The issue you're having seems to be that your variable `i` is typed as `number|void` and when you return `[i,i]` you expect flow interpret that as `[number,number]|[void,void]`, but flow cannot do that unless you first refine `i` to either `number` or `void`. Without that (seemingly pointless) refinement, flow instead interprets the type of your `[i,i]` array as `[number|void, number|void]` which is not equivalent. 

For the former you can do:

```js
const func = (i:number|void) => typeof i === 'undefined' ? [i,i] : [i,i]
```

There does appear to be something strange going on though, for instance [this](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AuAueA7ArgWwCMQYAfRAewEtgBuAKDHKwGdV4BPeAXjXYAcQ5AGZpuXHgHIcWUEMpYQwCfAD88ANqoANKgC68TJp26gA) type checks and the type-at-pos for `y` is `[number,number]|[void,void]`:

```js
declare var t: number|void;
const y = typeof t === 'undefined' ? [t,t] : [t,t]
```

And doing [this](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AuAueA7ArgWwCMQYAfRAewEtgBuAKDHKwGdV4BPeAXjXYAcQ5AGZpuXHgHIcWUEMpYQwCfAD88ANqoANKgC68TJp26GTVvABemVP0EjOPdkA) also produces no errors although the type-at-pos for `z` is now unknown:

```js
declare var t: number|void;
const y = typeof t === 'undefined' ? [t,t] : [t,t]
const z: typeof y = y
```

**However** if you do [the following](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AuAueA7ArgWwCMQYAfRAewEtgBuAKDHKwGdV4BPeAXjXYAcQ5AGZpuXHgHIcWUEMpYQwCfAD88ANqoANKgC68TJp266qfggCa3XgOEcGTVvABemKz3ZA), you get a type error and the type-at-pos for **both** `y` and `z` is now unknown:

```js
declare var t: number|void;
const y = typeof t === 'undefined' ? [t,t] : [t,t]
type Y = typeof y
const z: Y = y
```

Seems like a bug to me.

**Comment by sparlampe** [comment]
Thanks a lot, while trying to find a work around in the flow-typed file I found [another](https://flow.org/try/#0MYewdgzgLgBApgDynMsBcMAUBKAvAPhgG0wBXAWwCM4AnAGhjKtoF0Zcs98iBGOnlgChQkWJTRFoNAJZgA5jAA+jCtXowpshcqZq2HeEhRQcw8NBjAJm+UpXN1N7fb3tifAUA) demonstration of the problem:
```
const extent : ()=> [number, number] = ()=>[1,1]
const b:[string | number, string | number] =  extent()
const c:[string | number, string | number] = [1,1]
```
the second line does not type check with the error that type number is incompatible to type string.

**Comment by gkz** [comment]
That's expected, due to mutability of the tuple. The third line works as it's a literal value. In the future we will have read only tuples so then you could mark `b` as read only and it would work
