### ISSUE TITLE
Cannot refine union using intersection

### ISSUE THREAD

**Issue by pkuhanan** [facebook/flow#5179]
```
/* @flow */

type SomeType = number | { thing: number };

function f(x : SomeType & {}) {
  (x : { thing: number });
}
```

I would expect this to work -- we would check before calling this function that some variable is an object, then pass it in.  I expect `x` to have the type of the object branch from `SomeType` but instead I get an error... what's going on here?

**Comment by btford** [comment]
Possibly a duplicate of #3912 and/or #4029.

**Comment by goodmind** [comment]
Duplicate of #4029
