### ISSUE TITLE
Allow void parameters to be omitted, specifically for Promise<void>

### ISSUE THREAD

**Issue by ide** [facebook/flow#518]
When constructing a new promise of type `Promise<void>`, the `resolve` function of the promise doesn't need to take an argument. I'd like to write code like this:

```js
function doSomethingAsync(): Promise<void> {
  return Promise((resolve, reject) => {
    var resolverFunction: (() => void) = resolve; // just to demonstrate the expected type
    resolverFunction();

    // or... should still be able to chain promises
    var anotherVoidPromise: Promise<void> = Promise.resolve();
    resolve(anotherVoidPromise);
  });
}
```

**Comment by avikchaudhuri** [comment]
@ide just to confirm, resolve(undefined) works, right?

This seems to be a general issue with functions. A much simpler repro is:
function foo(x: void) { }
foo();

which gives a "Too few arguments..." error. I'll look into it, thanks for reporting.

**Comment by ide** [comment]
Yes, resolve(undefined) works.
