### ISSUE TITLE
[Feature] Section to specify path patterns to suppress errors 

### ISSUE THREAD

**Issue by rostislav-simonik** [facebook/flow#5181]
We'd like to have such config section as [ignore], [include]  but named e.g [suppress]
which will contains paths patterns where we still want flow to process files but we want to suppress errors. 

This is handy when I want flow to process 3rd party libraries which are not errorless but still contain precious type definitions. 

At this moment we are forced to ignore given library and to write own library definition. 

If there is any way how to achieve this at this moment, We will be very thankful for help. 

Thanks.

**Comment by jamesisaac** [comment]
This is what the [`[declarations]`](https://flow.org/en/docs/config/declarations/) section of flowconfig achieves.

**Comment by rostislav-simonik** [comment]
Thanks @jamesisaac. Yes, given section works exactly as expected, but there is a case which is not covered. FYI and others, if you setup option `all=true` so in that case all files in `node_modules` are validated. 

This is expected due, we don't want to validate only files that contain @flow keyword, developers usually forget this, and some files stay not flow annotated. 

Side effect of that you've got zillion errors from `node_modules` so you will end up with `node_modules` in `[ignore]` section.

Due `[ignore]` section has higher precedence as `[declaration]` section and ocaml regexp doesn't implemented negative look ahead pattern yet, so you will end up with exclusion for packages e.g. starting with prefix `@txo` like 
```
<PROJECT_ROOT>/node_modules/@txo.*/node_modules/.*
<PROJECT_ROOT>/node_modules/\([^@]\|@\([^t]\|t\([^x]\|x\([^o]\|$\)\|$\)\|$\)\|$\).*$
```
in `[ignore]` section

that is quite sufficient enough, we created script for that to easy that , but if you want another prefix then space complexity for defining of given rule is o(n^2) for each character it differs. 

So to solve this issue, we rather addressed given problem by introducing exclusion logic in `[ignore]` and others section like  .gitignore does.

Please refer to #7317
