### ISSUE TITLE
type comparing is wrong of usage of Array.reduce with 2nd argument

### ISSUE THREAD

**Issue by OsugaHiroshi** [facebook/flow#5182]
Using Array.reduce with 2nd argument and annotating return type for 1st callback argument, Flow shows error message.

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagEqeQK4BOAdgCobYC8oA3gL4DciiIJsyo8sRA1ogG0AugDoimACYEAxpgAUiUKEgES05AEtYJBUoCQ6AFy58xcpQA0ipaEzGAzsiIaSAc2sBKY3kKkKWOlAQUABDEnZkEORscV8SUDQsayVYszoma3oLdMQPZlZgZAALDXsuHl57QVFxKVldZVV1LR1rA29TP0tk2wcnF3clD0Dg+A1i2AJOMIiolp7U0nTmJSycvMQgA)

According to them, Flow detected its usage is `callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: Array<T>) => U`.
Its correct !!

But Flow said `This parameter is incompatible`.
This might be wrong.

In the detail of error message, Flow compared return type `ReturnType` to 2nd parameter `e: string`.
```
This parameter is incompatible:
9:   ): ReturnType { // annotate return type
        ^ object type. This type is incompatible with
8:     e: string          ^ string
```

But in this case, `ReturnType` should be compared to only 1st parameter, because of declaration is `callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: Array<T>) => U`

This is from 0.56.0 and 0.57.3 is the same. 

```js
// @flow
type ReturnType = {};

//not work
[].reduce(
  function(
  	p: ReturnType,
    e: string
  ): ReturnType { // annotate return type
    return {};
  }, {}
);

//this works
[].reduce(
  function(
  	p: ReturnType,
    e: string
  ) { // without annotation
    return {};
  }, {}
);
```

**Comment by kelvin-evari** [comment]
Can anyone give us an update on this one? This is a very annoying issue that prevents us from using reduce function with Flow.
