### ISSUE TITLE
Flow crashes very often

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5184]
I use to flow in WebStorm under Windows Server 2008
It crashes too often with message 'flow.exe has stopped working', so I must to restart it manually every 3-5 minutes

I've noticed: it works normally while I not running any build task with node.js
If I start task for client or server building for development - it crashes in resent minute

**Comment by makhnatkin** [comment]
I have the same issue.
Flow 0.57.3
Windows 7 6.1
WebStorm 2017.2.5 Build #WS-172.4343.25, built on October 20, 2017
JRE: 1.8.0_152-release-915-b12 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

**Comment by TrySound** [comment]
Let's agree it's webstorm problem. I use it in vim on windows and mac. Everything it fine except some memory leak if process is kept whole night.

**Comment by budarin** [comment]
@TrySound Thanks for sharing! I will write to JetBrains

**Comment by sagar12861** [comment]
I'm running flow on command line same problem
