### ISSUE TITLE
Why checking is not working?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5185]
Here a sample [link](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AzgFXNAvFA3gFBQlRoCGAthAMoLAQD8AXFAORrABOCAxsGygAfdgBtyADzYAaQgF8A3IUKhIsAEYArCPyxq8RUlBRUIrTjxQBzWUaTxk6FrAepM2WYuVoIwVgAp8Y1NpKHtENygDOSg5VhgtHWA9CABKVnUkJFEIchQogD4CYiNSkl43YGKymtIKajoGKPYASWA0YyQqgHckLgBrBGsZEtqSOJcI9BTm8Mc0JRISrl8AVy587lWIJTkgAl)

``` JavaScript
type OptionsType = {
    sameSite?: 'strict' | 'relaxed',
};

type ObjectType = {
    name: string,
    options?: OptionsType,
};

set: ({ name, options = {} }: ObjectType): boolean => {
            const {
                sameSite = 'Its not working !!!!!!!!!',  // <---- not working
            }: OptionsType = options;
  
  return true;
}
```

**Comment by jcready** [comment]
The default property value for `sameSite` when destructuring `options` does not have to satisfy any type checks. `options.sameSite` has type constraints, but the `sameSite` constant does not have any constraints.

**Comment by budarin** [comment]
@jcready,  so the only way it to declare default values like this?

```JavaScript
type OptionsType = {
    sameSite?: 'strict' | 'relaxed',
};

type ObjectType = {
    name: string,
    options?: OptionsType,
};

set: ({ name, options = { sameSite: 'strict' } }: ObjectType): boolean => {
 ... 
  return true;
}
```

**Comment by jcready** [comment]
Well I did find a way to turn your example into an actual bug ([Try Flow](https://flow.org/try/#0C4TwDgpgBAysBOBLAxsAMgQwB5QLxQHIBnBFYAqAH0IBtsCAoB0SKAeTGEQHsA7IgCrho+AN4MokqEQwBbCDETAIAfgBcsUqkxYANAwC+AbibI+JKMov4AFKOlyFSkYQCq-bgFdeAEwoGNDi5zIUgASg04JG1sPAA+B3lFZSA)):

```js
type StrictLax = 'strict' | 'lax'

type OptionsType = {
    sameSite?: StrictLax,
};

const test = ({ sameSite = 'Unsound' }: OptionsType): StrictLax => sameSite
```

**Comment by budarin** [comment]
I'm confused with modified sample

```

**Comment by budarin** [comment]
and yet another confusing thing [link](https://flow.org/try/#0MYewdgzgLgBAZgVzMGBeGAKA3gKDAQwFsBTAGhxAAcoBLcCNGXGGS-KACwC4YByAel7kWhfAA8AggHNiPAAzCYEYsAQAnWfHwAbZYo5QolAPJhtATx5wdenCxAA3YmoDuamlE1Q1CMnaU0UmDEACZWNn4sEETEAMoemrza4kI4AL7kaQCUPABGICDaxPhgaAB8TDigkLDMLPUsbJyKDSwhIKI0YC2txGKUNBoQPQ2ikjIj9cqqGpMsBkamFnMwjs5uCSsQgcEhWzHxnpNpjFS09ADc-hpQ6qXevldpQA)
```js
const func = ({
name,
options = {
  path: '/',
  maxAge: 0,
  secure: false,
  httpOnly: false,
  overwrite: true,
  signed: false,
  sameSite: 'lax',
},
}): boolean => {
const {
        path,
        domain,  <--- property `domain`. Property not found in object literal
        expires,   <--- property `domain`. Property not found in object literal
        maxAge,
        secure,
        httpOnly,
        overwrite,
        signed,
        sameSite,
      } = options;
  return true;
}
```

it's restructuring and spreading values mustn't be present in declared default value for option and filled in runtime with "undefined"
