### ISSUE TITLE
Allow explicitly including a folder under an ignored path

### ISSUE THREAD

**Issue by mudetroit** [facebook/flow#5186]
I have a problem that is admittedly probably a bit of an edge case, and perhaps there is a way to do this that I am just missing. I have a directory structure like such:
```
# app
# ├── alpha
# │   ├── beta
# │       ├── charlie
# └── …
```

I want to ignore all of the files under beta, but include those under charlie. I have tried

```
[ignore]
<PROJECT_ROOT>/alpha/beta

[include]
./alpha/beta/charlie
```

In this case `yarn ls -- all --explain` reports everything under charlie as explicitly ignored. I have also tried tweaking the regex in ignore like this

```
<PROJECT_ROOT>/alpha/beta/(?!charlie/).*
```

But then it reports everything under beta as implicitly included. Which makes me suspect that there is something bad with the regex itself.

On a general level it seems like an explicit include should override an ignore, but perhaps I am off on that.

**Comment by rostislav-simonik** [comment]
1. I'm not 100% sure, but I think that OCaml regular expressions don't implement negative lookahead. 
2. You should escape such control characters as `(|)` with `\`
3. Try rewrite negative lookahead according to this equivalent 

**semantic**
all modules except starting `ts-` (e.g. `ts-react-native-framework`)

**negative lookahead** 
`(?!ts-).*`

**OCaml regular expressions equivalent**
([^t]|t([^s]|s([^-]|$)|$)|$).*$

**escaped ignore section pattern** 
`<PROJECT_ROOT>/node_modules/\([^t]\|t\([^s]\|s\([^-]\|$\)\|$\)\|$\).*$`

**Comment by jcready** [comment]
This might be helpful: https://dsslimshaddy.github.io/flowignore/

**Comment by mudetroit** [comment]
@rostislav-simonik thanks for the help with the regex. Gave me enough that I was able to piece together a working solution.

I am going to leave the issue open, an admin can feel to close if they choose. It still feels like if you explicitly include something that should win over an ignore, but perhaps I am wrong in that feeling.

**Comment by rostislav-simonik** [comment]
@mudetroit it depends on project needs, sometimes include should have higher precedence, another time it shouldn't. 

But would be great to have option to override ignore precedence. Maybe gitignore logic ???

e.g.
```
[ignore]
<PROJECT_ROOT>/node_modules/.*
!<PROJECT_ROOT>/node_modules/test ; <<< forces include

[include]
<PROJECT_ROOT>/node_modules/test ; <<< it's suppressed by ignore section 
```

**Comment by mudetroit** [comment]
@rostislav-simonik I could see that as well. Right now though the combination of OCaml regex syntax and the way includes and ignores are applied makes for it very tricky to do things that shouldn't be overly difficult.

**Comment by IniZio** [comment]
@rostislav-simonik Thanks for your pattern :+1:

**Comment by cprodescu** [comment]
Has this been resolved via https://github.com/facebook/flow/pull/7317 ?
