### ISSUE TITLE
class must be intersection type with object

### ISSUE THREAD

**Issue by last-partizan** [facebook/flow#5190]
Hello, it's midnight and i'm trying to understand flow.

```
/* @flow */
class Answer {
  prop = 42;
}

type AnswerType = Answer & Object;

function what (obj: Answer) {
  return obj["prop"]
}
```

Here is my code, and flow says `indexable signature not found`. So, i must define and use AnswerType, but why flow doesn't do this by default?
Example at flow/try here:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQQDtcEBTAJzAG9UwwAHSuRsAXjABYAmAblQBfdABcAno3JFSFSgBUJUziTJUwAMjAB5AEYArchhEDUUAK7EjASzjEwCABbYRYABRx9ALmmrKASlp6MEpyETNKOw89AG0AImZWWIBdIVQgA

**Comment by jcready** [comment]
You can do this instead:

```js
class Answer extends Object {
  prop = 42;
}
```

All javascript classes implicitly extend `Object` anyways.

**Comment by last-partizan** [comment]
That's better, tnank you.

But anyway, i't like i'm writing code to please flow, and not flow helping me to write good code.

**Comment by SamChou19815** [comment]
this now works
