### ISSUE TITLE
CSSProperties not defined on React

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#5192]
Coming from typescript here and I know over there I can do stuff like this

```
// @flow

import React, { Component } from 'react';

export class SharedStyles {
  static flexParent: React.CSSProperties = {
     padding: '0 0 0 0'
  }
}
```

In flow I get the following error
```
Error: src/shared/components/blah.js:4
  4: import React, { Component, CSSProperties} from 'react';
                                ^^^^^^^^^^^^^ Named import from module `react`. This module has no named export called `CSSProperties`.
```

This also happens on the website
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMa4A0oA3qAMKyawB2RL+AvqJNk6AHJspCgIDcyIgA8seUGWgkAzktABlABYlhAEzW4AntCKqaiUKCW4SuFGR7GpABW3tcALkIjcAOnpq1Jz4MIjwUE1AAXlpkC05ETiA

So is React.CSSProperties through flow not supported? Is there a way to add it so that developers are prevented from writing css properties that don't exist?

**Comment by TiddoLangerak** [comment]
I think `React.CSSProperties` is a typescript specific interface, it's not something that actually exists in react itself. 

I think the closest you can get to it is `$Shape<CSSStyleDeclaration>` (doesn't work in playground though), but it's not perfect. You can find it's definition [here](https://github.com/facebook/flow/blob/master/lib/cssom.js#L71).

**Comment by rickyp-uber** [comment]
You're right, I think VS Code suggested that for me. When I use $Shape<CSSStyleDeclaration> flow does now seemingly break where I expect it to. The downside is that the flow plugin in VS Code doesn't provide correct typing information. Which means I gained something and lost something else. There has to be a solution where I get both...

**Comment by FezVrasta** [comment]
This no longer works on recent Flow versions, it throws `Cannot create Component element because property @@iterator of CSSStyleDeclaration [1] cannot be unbound from the context [2]
where it was defined in property style.@@iterator. [method-unbinding]`
