### ISSUE TITLE
Problems with the detection of types

### ISSUE THREAD

**Issue by szagi3891** [facebook/flow#5194]
[In flow try](https://flow.org/try/#0MYewdgzgLgBADgQwE4QKYGUpIJZgOYwC8MAFAG4IA2ArqgFwwJgCeAlA9DvkQHwwDeAKBgiY2AGakozOKhCSKNVEULEA5J1x41rAcNEGkqKNSRgYi2gG59IgL77BASCgALJCADuMAKJIPSCRqPgAessBQqAAmMJr4OjZ2NoKgkLCIKKgAqmBRqOK40UQwADwA0jwkGWgAalS0DOT19IwsuoR8Ze08tqSWLUxsDGUwAD4WINgxHXoGBhJ9zSrE1Ln5hVG6QnM7MEYmZja7MA7H+6bm1ah1Sk1KrEeiSY6p0DDi4hxYWmMTU8VXHJ5ApgaJVZBoTBcPCsIIARgRcISgiAA)

```
const parseString = (value: any): string => {
    if (typeof value === 'string') {
        return value;
    }
  
	throw Error('Expected string');
};

const parseUndefined = <K>(parseValue: (value: any) => K) =>
    (value: any): K | void => {
        if (value === undefined) {
            return;
        }
        return parseValue(value);
    };
  
const ff: string | void = parseUndefined(parseString)('1111');

```

```
39: const ff: string | void = parseUndefined(parseString)('1111');
                              ^ K. This type is incompatible with
39: const ff: string | void = parseUndefined(parseString)('1111');
              ^ union: string | undefined
Member 1:
39: const ff: string | void = parseUndefined(parseString)('1111');
              ^ stringError:
39: const ff: string | void = parseUndefined(parseString)('1111');
                              ^ K. This type is incompatible with
39: const ff: string | void = parseUndefined(parseString)('1111');
              ^ string
Member 2:
39: const ff: string | void = parseUndefined(parseString)('1111');
                       ^ undefinedError:
39: const ff: string | void = parseUndefined(parseString)('1111');
                              ^ K. This type is incompatible with
39: const ff: string | void = parseUndefined(parseString)('1111');
                       ^ undefined
```

In this example, it should be detected by flow that parameter K is string

**Comment by vkurchatkin** [comment]
Flow can't infer types that contain type variables, so you have to specify them manually like this: https://flow.org/try/#0MYewdgzgLgBADgQwE4QKYGUpIJZgOYwC8MAFAG4IA2ArqgFwwJgCeAlA9DvkQHwwDeAKBgiY2AGakozOKhCSKNVEULEA5J1x41rAcNEGkqKNSRgYi2gG59IgL77BASCgALJCADuMAKJIPSCRqPgAessBQqAAmMJr4OjZ2NoKgkLCIKKgAqmBRqOK40UQwADwA0jwkGWgAalS0DOT19IwsuoR8ZeykTMy8MGUwAD4WINhR7XxNSgy93YMjZGMxHXoGBhKklsqqxNS5+YUTa+unRiZmNqf2tuvnpubVqHVK07SsV6JJjqnQMOLiDhYLTDUbjYpPHJ5ApgaJVZBoTBcPCsIIARgxaISgiAA

**Comment by szagi3891** [comment]
It looks like it works. Thank you :)
