### ISSUE TITLE
Issue with: Property cannot be accessed on possibly null value

### ISSUE THREAD

**Issue by dugokontov** [facebook/flow#52]
I have modified your example 03_Null/nulls.js:

```
/* @flow */
var x = null;
function length() {
    if (x === null) {
        return 0;
    }
    return x.length;
}

var total = length("Hello") + length();
```

When I run flow on this file I get following error:

> nulls.js:7:16,23: property length
> Property cannot be accessed on possibly null value
>  nulls.js:2:13,16: null

But, if I move line `var x = null;` inside function `length`, everything will work as expected. It looks like flow doesn't work well with variables outside it's scope.

**Comment by arb** [comment]
@dugokontov did you ever find a solution to this? I'm noticing this issue now with early returns and `null`able input arguments.

**Comment by dugokontov** [comment]
@arb no ):
For some reason @avikchaudhuri closed this issue a long time ago...

**Comment by linuxonrails** [comment]
I have the same problem :-(
