### ISSUE TITLE
Auto complete fails with function call

### ISSUE THREAD

**Issue by HerringtonDarkholme** [facebook/flow#520]
I'm using vim-flow.  When using auto completion I found that sometimes flow gave me nothing. I think this problem should be reported here because `flow` command line tool, which vim plugin is used internally, does not behave properly.

I'm on Ubuntu, with `flow 0.12.0`. Test case as below. `AUTO332` is a token taken from vim-flow.

```
$ flow autocomplete << JS
var a = 123
function id(a) {return a}
var c = id(a)
a.AUTO332
JS
```

This gave me nothing. But after removing the statement `var c = id(a)`, it worked well.

```
flow autocomplete << JS
var a = 123
function id(a) {return a}
a.AUTO332
JS       
```

Result: 

```
toExponential (fractionDigits?: number) => string
toFixed (fractionDigits?: number) => string
toPrecision (precision?: number) => string
toString (radix?: number) => string
valueOf () => number
```

Thanks for bringing us Flow with its richness and idiomatic expressiveness. I really love it.

**Comment by nmn** [comment]
The autocomplete for number functions is currently broken.

```
/* @flow */
var num = 123
num.
```

This currenly doesn't get any suggestions from flow.

However this example from the tests does:

```
/* @flow */
var obj = {
  a: 123,
  b: 'hello'
}

obj.
```

**Comment by nmn** [comment]
More updates on this.

It's not just Autocomplete, pretty much all type inference/type analysis fails on function calls.

For example, let's say I have a simple module:
```
class A {
  test(a){
    return a;
  }
}

export default A
```

flow will correctly ask for annotations for the test method since it's being exported.
But let's say I have a class decorator function in play:

```
export default decorate(A)
```
Then flow stops asking for annotations and the module loses all type inference for other modules.
Setting a type for decorate does not solve the problem:

```
type Identity<T> = (in: T) => T
var decorate: Identity = somemodule.decorate
```

Currently the only way around this problem is:
```
var toExport: typeof A = decorate(A)
export default toExport
```

**Comment by mroch** [comment]
```bash
% flow autocomplete << JS
var a = 123
function id(a) {return a}
var c = id(a)
a.AUTO332
JS
```
now yields
```
hasOwnProperty (prop: mixed) => boolean
isPrototypeOf (o: mixed) => boolean
propertyIsEnumerable (prop: mixed) => boolean
toExponential (fractionDigits?: number) => string
toFixed (fractionDigits?: number) => string
toLocaleString (locales?: (string | Array<string>), options?: Intl$NumberFormatOptions) => string
toPrecision (precision?: number) => string
toString (radix?: number) => string
valueOf () => number
```
