### ISSUE TITLE
Object.keys call type removes "semantic" typing from object keys

### ISSUE THREAD

**Issue by vojtatranta** [facebook/flow#5210]
Problem is ilustrated here: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDkAhsapjgEKEkBGFl2esATrUfgD6jXIhQ6FrEigA1ljQBnUAEtZ4gHYIliAMawl0lKCxKArgFtpALlABvUAG1c7agF1zOtnKUBzUAF86VssXMyUAA3UmgDLGIAGgYAhhCwiOJvRFBQATA4dzl1MOg0eV1pAAtYA2gAE1A2LBQDNiU8NjZSAtFC4kUpWVIlKqNSNxRBxoAiaSwBpRQc0aEqGJVdACsDHVAXN3dEQXV6mun80AB5emWsdRQAOkkZatr67SaWtAAeTY8APhjS+CxgrBsUAASVA8DKlT0AA9sJdQPQsNA4PBQJoKjgULB4ThjgBpVKabS6UjNVrHSAAUUMJnMuFJbzsHE+dFO50uN26AAp9MZpABKIA

I'd expect `Object.keys` to return `Array<ExactKeyType>`. Which means that if I have object, that is defined like this: `type A = 'a'; { [A]: string }`. Expected results of application of `Object.keys` to such object would be `Array<A>`, not `Array<string>` as it is according to `Object.keys` typing: https://github.com/facebook/flow/blob/master/lib/core.js#L45

Suggestion:

I'd use this typing for `Object.keys`:
```js
static keys<T>({ [T]: any }): Array<T>
```

**Comment by jcready** [comment]
Even if your typing for `Object.keys` worked as you describe, it would still produce incorrect results because inexact object types can flow into it. This would produce no flow errors:

```js
function test (obj: { foo: string }): Array<'foo'> {
  return Object.keys(obj)
}

test({ foo: 'bar', baz: 'qux' })
```

**Comment by vojtatranta** [comment]
@jcready well my usecase is that I want to have exact set of keys in the object eg. just these: `foo, bar` no other. So it would be: `{ ['foo' | 'bar']: any }`. Then you example would throw an error, right or?

**Comment by jcready** [comment]
My point is that the general `Object.keys()` doesn't get to decide whether or not to accept inexact objects. It has to accept any object. There is also no way to type `Object.keys()` in a way that would allow it to be able to switch the resultant type based on whether the object passed into it was of an exact or inexact object type.

I submitted [a PR](https://github.com/facebook/flow/pull/4527) a few months ago that did [exactly what you're asking for](https://github.com/facebook/flow/pull/4527/files#diff-f265d6a6b6b64d4d096fddcf7d620a76R50), but I closed it because of the issues mentioned.

**Comment by noppa** [comment]
>My point is that the general Object.keys() doesn't get to decide whether or not to accept inexact objects. It has to accept any object.

Wouldn't that be what the `$Exact` type is for? [This example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmgDWaAngM4A8AKgHwAUsARgCsAXKAAkAUQAe2Ch04BKEaIDSTNlwDcqTDnyFSFarQYtegkdhKNFoZuVyUSAcwDaAXS2IQodgAtKzKBouLiwuIGUkKCMsESgGL6WTgTkvimMAA4EsFEAbtjQoOSwoADehLCwFlagAL6IxGRUNEVodlIy5Nz50CKlAD4VVaCWjKD9tTYAgiHYjKwA5JCVC5xliKCg+OREuMZq3QXyWvVeYH4BQSFhEVExcQlJKWlbaDt7oD1EKSUzuHOLZawVYNAzNWjkNrkABysHIHQoh16ZSG1TGkxEdgcznc602212+1MPWOiHqQA) seems to work quite nicely, although not quite the way OP was asking for.

Also, while I was testing that, I also noticed that [this slightly modified version of the original already works](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDkAhsapjgEKEkBGFl2esATrUfgD6jXIhQ6FrEigA1ljQBnUAEtZ4gHYIliAMawl0lKCxKArgFtpALlABvUKQD85nWzlKA5gBpQ9O6AdPnoAL50VqTmZKAAbqTQBljE7vSh9BFRMcQBANzImtq6pGxspGgA8pAAooYm5rj5hQA8uOzUAHx0RfQAVljqKAB0kjIAFPrG0gCU6UA) and, more worryingly, [this also seems to type check](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDkAhsapjgEKEkBGFl2esATrUfgD6jXIhQ6FrEigA1ljQBnUAEtZ4gHYIliAMawl0lKCxKArgFtpALlABvUKQD85nWzlKA5gBpQ9O6AdPnoAL50VqTmZKAAbqTQBljE7vSh9BFRMXGg6qHqydGxAQDcyJrauqRsbKRoAPKQAKKGJua4ZRUAPLjs1AB8dJX0AFZY6igAdJIyABT6xtIAlHlAA) even though it does not match the runtime behaviour.

**Comment by SamChou19815** [comment]
this now works
