### ISSUE TITLE
Union from exact types of an Objects values.

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5211]
So I have been looking for awhile now to figure out how I may do this.  I thought I had it figured it out but unfortunately in the end it didn't work.

The goal: Say I have an object of options (in this case classes).  I then have a function which may take an **instance** of any of the values found in the object.  

I found that $Values has been silently added but unfortunately it does not work in this way as it requires I add [typeof] which loses the classes properties and only allows for static properties.

```
class One {
  connect = () => {};
}

class Two {
  connect = () => {};
}

const opts = { one: One, two: Two };

function callConnect(on: $Values<typeof opts>) {
  on.connect();
}
```

https://flow.org/try/#0MYGwhgzhAEDyB2BTaBvAUNawD28nABdoBeaACgEoSA+VAXwG40601RIYAVAd21Qyy58RUpRr0mLNrghFsABwIxSKaLkQAuOEgA00Ary08+jVgDMArvEIBLXFjAgQAYSGJCZXFoAkANUcWiBAAPAQAnvKI2GZqihDUVOiYuAB0OHjuBJSSQA

The goal is essentially to convert `opts` to:

```js
type OptsValues = One | Two
```

Am I missing something?   This does seem like it would be a very powerful option.  

I do know I could use an interface in this case as both One and Two have the same methods - but I would like to only accept instances that are within that object.  

It's a pretty in-depth ask so I get it may not be possible - just wondering if I may be missing something.

Seems like it would work if `$Values` were just able to take the types of values rather than requiring a typeof request. 

I have seen a ton of others asking for that type of thing where 

```js
const vals = {
    one: 'ONE',
    two: 'TWO'
}
```

In the above case, we essentially want to create `type Values = 'ONE' | 'TWO'` rather than the only provided way of `type Values = string | string` via `$Values<typeof vals>`

It would seem we want something ilke

`type Values = $ExactValues<vals>` -- I can't imagine this is even difficult to implement considering it definitely is aware in this case of the class instance on the object - we just have no way of extracting those into a union.

**Comment by popham** [comment]
`$ObjMap` has sufficient destructuring magic to manage this. Try

```js
class One {
  connect = () => {};
}

class Two {
  connect = () => {};
}

const opts = { one: One, two: Two };

/* The `One` and `Two` values become Class<One> and Class<Two> types under
 * `typeof opts`. We need to remove the `Class<.>` wrappers.
 */
type ExtractInstanceType = <V>(Class<V>) => V

function callConnect(on: $Values<$ObjMap<typeof opts, ExtractInstanceType>>) {
  on.connect();
}
```

**Comment by bradennapier** [comment]
Thank you @popham - I hadn't spent much time on that since it is marked as buggy but will do so since that appears to be an extremely powerful option.
