### ISSUE TITLE
Bug: Destructuring an object breaks sentinel refinement

### ISSUE THREAD

**Issue by rbalicki2** [facebook/flow#5212]
I struggled for a while over this. Please see this minimal example: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeATgLYCWAdgIYxgC8YA3qmGAG50CueAXGCrcyAI1IAaNmGz4BAcgylKtGHMkBfANzoZBQiTwEmxctTpgAPiym75GA3jVSYeKBgH7Dk9iQoBzAAt3IgcNbVQAYzgqAGcMMBjhQgC8TyMwAAp7Qw8HAEpGAD5rdijY+OZpXAJ1RmkHbXZgYDAKKEzsvAA6XUYGJgUHOQLWdjaO6r6BzuGS9jADDG4SKgSklLSshy6XNwKAajWyZNSHLcMu30CMPMawdSlF5dXOrq4YXm0HyOiYuBcdnA-BlEscNmdKu9eAIAIwAFnEVVkYAUSjMqnueVuqCAA

In essence, sentinel refinement doesn't work with:
```
const { type } = tree;
if (type === 'tree') {
```

but does work with:
```
if (tree.type === 'tree') {
```

This is not a problem per se (now that I figured it out), but it could be clearer in the docs!

**Comment by jfirebaugh** [comment]
I think this is a duplicate of #3932.

**Comment by rbalicki2** [comment]
Indeed, it is a duplicate
