### ISSUE TITLE
Bug: Multiple calls on possibly undefined value behind truthy guard reports second

### ISSUE THREAD

**Issue by SimenB** [facebook/flow#5213]
Really bad title, but example should be clearer.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAFgJYB2A5mALxgDeqYYA+iwMYCGMMAzqRjwB+AFxgA8gCMAVnnYYANKgC+6bPjABhbnwEE6jZuzgwArgFtyY8hcl4ATkuYwKea7YdLVqKKfLzSOHIwKDg4AAoMMioxEgpKAEoxIW0efkEGJjBjcl4MbJ10-TAo+IA6Ni40vSzmZiFMuqa64zNLMVKqCo5CvTLKPAxNEwtyADkPe3CEp2aml3I3EujKbqrdQX7BgBlXCfM7KZna5tU59x4Abiz7QdN7YPWi69UgA

`getColumnNumber` is fine, but `getLineNumber` gets reported. Why? If I remove the call to `getColumnNumber` (or just hard-code it to `0`) then there is no error

**Comment by apsavin** [comment]
Because (AFAIK) `flow` thinks that a call to a function can change something.

Try [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAFgJYB2A5mALxgDeqYYA+iwMYCGMMAzqRjwB+AFxgA8gCMAVnnYYANKgC+6bPjABhbnwEE6jZuzgwArgFtyY8hcl4ATkuYwKea7YdLVqKKfLzSOHIwKDg4AAoMMioxEgpKAEoxIW0efkEGJjBjcl4MBlYOHXSCZVowKPiAbizSKDBwgEI2LjS9BLB7PAxTe2CbHhqsrp6+zOYjEwsrQtbdQQA6Sm7NKcsAOQ97cISnCZdyN1nivSXugBlXTfM7bd2s5RrVIA)

**Comment by SimenB** [comment]
Calling a function on an object can't make that object `null`/`undefined`, though (can it?).

Thanks for the workaround! I'm gonna stick with a `// $FlowFixMe` for now, though

**Comment by apsavin** [comment]
@SimenB 
```js
const thing = { __callsite: {getColumnNumber: function(){thing.__callsite = null;}} }
```

**Comment by SimenB** [comment]
Good point!

**Comment by jcready** [comment]
You could also do this:

```js
/* @flow */

type Thing = {
  +__callsite?: {
    +getColumnNumber: () => number,
    +getLineNumber: () => number
  },
}

type Callsite = {
  column: number,
  line: number,
}

function foo(thing: Thing): ?Callsite {
  const { __callsite } = thing
  return __callsite
      ? {
          column: __callsite.getColumnNumber(),
          line: __callsite.getLineNumber(),
        }
      : null;
}

```

**Comment by Zhouzi** [comment]
Perhaps a simpler illustration:

```javascript
class Bar {
  print() {
    console.log('Hey, this is Bar!');
  }

  alert() {
  	console.log('HEY, THIS IS BAR!');
  }
}

class Foo {
	bar: ?Bar;

	printBar() {
    	if (this.bar instanceof Bar) {
          this.bar.print();
          this.bar.alert();
        }
    }
}
```

```
17:           this.bar.alert();
              ^ call of method `alert`. Method cannot be called on possibly null value
17:           this.bar.alert();
              ^ null
17:           this.bar.alert();
              ^ call of method `alert`. Method cannot be called on possibly undefined value
17:           this.bar.alert();
              ^ undefined
```

[Try Flow](https://flow.org/try/#0MYGwhgzhAEBCYCdoG8BQ1oAcEEsB2ALgBQCUK6G0wA9nhNSAKYB0I1A5kQOQASjAngBpoBABY4YEuIgCEXEgG4KAX1QUwTBMTJoMASBp0GLNp14BRAJrCAKjwCSAZWhO4AQQBKcxStSrUoJAwAGLU1OR6AEaIAFzQAPzwCEqoetj4BEmk5JTQejgAZtBEYhLM0Uj4EARgeMCM1EVJOhS5uaUQ5YjM6YSkSm1tHV0IzBqMWv2tbaq5qspAA)

**Comment by mrkev** [comment]
This particular behaviour is not a shortcoming but a feature meant to protect against possible side-effects. Unfortunately, flow doesn't support pure functions (see https://github.com/facebook/flow/issues/2715 for discussion on the matter, and links to related issues).
