### ISSUE TITLE
Flow does not respect overridden object shape

### ISSUE THREAD

**Issue by gajus** [facebook/flow#5217]
```js
// @flow

type MovieType = {
  +id: string,
  +credits: {
    +edges: $ReadOnlyArray<number>
  }
};

type InputMovieType = {
  +id: string,
  +credits: $ReadOnlyArray<number>
};

const fooMovie = {
  id: '1',
  credits: {
    edges: []
  }
};

const foo = (movie: InputMovieType) => {};

foo({
  ...fooMovie,
  credits: []
});

```

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWVgG4CWWAKpjgLygDeiooA1EQCYBcoAzigE5EB2AcwA09JgGMeWFkRScOdBg0bTBWeaAAkAJSwBDFgHl+0NAEEePPWgA8-AK4BbAEZYeAPjEBfRF4DcyOjYoACS-Bj2KPjEZBSg1IpMrBzcfEKiypLSsho6+kYm5pbWdk6uHr4BiOKw-NygkLCw0STxtGLJoADkAIxdGaBZMnIKYgyq6hwA2gC63pXINXUoDU1tABSOhCQcYRFR27HYAJTx7rT+yI2w64kAdA-XLVgDQznTc17HfkA

This gives an error:

```
24: foo({        ^ object literal. This type is incompatible with the expected param type of
22: const foo = (movie: InputMovieType) => {};
                        ^ object type
Property `credits` is incompatible:
17:   credits: {               ^ object literal. This type is incompatible with
12:   +credits: $ReadOnlyArray<number>                ^ read-only array type

```

There shouldn't be an error, because `credits` property is overridden with an empty array.

**Comment by dannyharding10** [comment]
Looks like this is fixed in v0.111.0
