### ISSUE TITLE
Flow does not evaluate const value

### ISSUE THREAD

**Issue by tanhauhau** [facebook/flow#5218]
This works:
```
function reducer1(x) {
  switch(x) {
    case 'a':
    case 'b':
    case 'c':
      return 'a';
    default:
      (x: empty);
  }
}

reducer1('a'); 
reducer1('d'); // throw error
```

But this does not work:
```
const Da = 'a';
const Db = 'b';
const Dc = 'c';
function reducer2(x) {
  switch(x) {
    case Da:
    case Db:
    case Dc:
      return 'a';
    default:
      (x: empty);
  }
}
reducer2('a'); //throw error
reducer2('d'); //throw error
```

[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzABEwBeMAb1TDAEMAuMAclqYBpqwAjRpr9zhl4YBAX3RY8hIrTLNWAbkw4CxLnL5Mlk1UQwaRS1FACu2DPgCWOMACcApgBMTGe7YCMACgAeASkqcuAiW+BgAFj7+VDQ0GLS49vJM9Jyx8YmaKTFgcQnMIlnZdvb4JrbYSUrZjvZQtCYw+IXZPoz2ALYADvgAnr5VYOLixmYW1hUOzq62AEyRATRBIeHz0TG5iTLNOelq2xvEQqkxDqXllcc1dQ1NxzStYB3dfQND6KbmVjaTLm4AzKtAsFQhE-At1rsiAA6BjHA7QnhwyFQo5FYpnCosLSXWr1Rrbe7eNpdXr9ThvVA-aZeLFkqluGmOJhkylOX6zTy0pT0jlMJksnkArmsqb-Tn8pRAA)

**Comment by SamChou19815** [comment]
Closing since now explicit annotations on functions like this are required
