### ISSUE TITLE
$PropertyType with templated key

### ISSUE THREAD

**Issue by MOZGIII** [facebook/flow#5221]
I'd like to flow yo support something like this:

```js
type Value = { whatever: string }

type SomeType1 = { a: "123" }
type SomeType2 = { b: "456 "}
type SomeType3 = { c: "789" }

type Data = {
  some: Value,
  
  responses1: Array<SomeType1>,
  responses2: Array<SomeType2>,
  responses3: Array<SomeType3>
}

const getter = <K: $Keys<Data>>(
  data: Data,
  key: K
): $PropertyType<Data, K> | null => {
  if (!data || !data[key]) return null;
  return data[key];
};
```

I expect the type for value returened by `getter` func to be the same as the type for `Data`'s key that is specified as a tamplate value. Example: for `getter<"responses2">(mydata, "responses2")` the value should be `Array<SomeType2>`.

Better yet would be to allow some kind of deduction based on the value (and allowing unions for keys):
`getter(mydata, mykey: "responses2")` to have `Array<SomeType2>` as return type and `getter(mydata, mykey: "responses1" | "responses3")` to have `Array<SomeType1> | Array<SomeType3>`.

PS: my real usecase is a lot like getter function I used here, but it also fetches the last value from the array (and therefore will require some additional type magic to extract a scalar type from array).

**Comment by apsavin** [comment]
See https://github.com/facebook/flow/pull/5126

**Comment by MOZGIII** [comment]
Looks like this does thi trick. Is it implemented? I tried it with no success (master flow):
https://flow.org/try/#0C4TwDgpgBAaghgGwK7QLxQN5QO4As7AQBuEATgFxQDOwpAlgHYDmUAvgFDuiRQDKA9gFsIAFXAQAjFHRY4lAEQSATAGZ5bLuL5DR4pdMxQARgoAsAVgBsUeR27QBwsZBUGsAYwUB2ABwBOdQ5NHgARAjg3dihqHUp4ZAgAGiioFNIIKjB+BioMiUoAQVJSOBAAHkddSAkAPmTo9Mzs3KolQuLSip1nCCU6tIysnIyVdpLyyp6VGvYg92bgKCYIYEJSAzKAaUoAEk2IECoysOA4GpqAChSAE3DKE7h6qABrA8pN9gBKXYBRBAhhAxgD1juFElBNjUoAAfKAMJAIBDSKEYFJ0ABmUAuAEJbqcYbDceEANqvEAAXU+UHSwCQpAYcIRCAA3ANafSoHi4KSDuTWaxmUA

Copuld you assist with the right example for my usecase?

**Comment by apsavin** [comment]
Try [this](https://flow.org/try/#0C4TwDgpgBAaghgGwK7QLxQN5QO4As7AQBuEATgFxQDOwpAlgHYDmUAvgFDuiRQDKA9gFsIAFXAQAjFHRY4lAEQSATAGZ5bLuL5DR4pdMxQARgoAsAVgBsUeR27QBwsZBUGsAYwUB2ABwBOdQ5NHgARAjg3dihqHUp4ZAgAGiioFNIIKjB+BioMiUoAQVJSOBAAHkddSAkAPmTo9Mzs3KolQuLSip1nCCU6tIysnIyVdpLyyp6VGvYg92bgKCYIYEJSAzKAaUoaemYagAoUgBNwygB+MOA4eqgAawgQSk32AEpKABIAUQQIYQZgD0ylcblBNjUoAAfKAMJAIBDSCEYFJ0ABmUAOAEJTtcodDseEANoPEAAXVeUHSwCQpAYMLhCAA3ANqbSoDi4MTHqTmaxmdEBQL2MtVmQDrD4YkoAByY7S17MkVrA4YVhS6VUHTy5nzHKLAAeF3iKAMSrFyOimuElCweAIxDIlGlcGlbFuAyawyo+SghNkCmUajYpNujSGLTavqwJhsFmsgRDHvDI0ofqgnhsvgCwdm6qtEG1QA)

Looks like all errors are correct.
And correct code gives no errors.
