### ISSUE TITLE
Add `--quiet` to cli docs website

### ISSUE THREAD

**Issue by IanVS** [facebook/flow#5223]
https://github.com/facebook/flow/pull/2631 added support for a `--quiet` option, but it is not included at https://flow.org/en/docs/cli/.

Is https://github.com/facebook/flow/blob/master/website/en/docs/cli/index.md the correct file to edit to add it?  If so I'll make a quick PR.

**Comment by Brianzchen** [comment]
Well this is 3 years late but `--quiet` is still not documented, that's the right place to document, are you still interested in doing this? 😓
