### ISSUE TITLE
[Question] How to extend Flow function type with additional properties

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#5224]
Flow v0.57

I posted this question on StackOverflow as well (not sure which is the preferred platform for asking questions).

https://stackoverflow.com/questions/47023579/how-to-extend-flow-function-type-with-additional-properties

I'd like to define 2 function types, `Foo` and `FooExt` to help type check the following pattern:

```
const fooFn = () => ({ id: '...', type: '...' });
    
fooFn['HELLO'] = 'WORLD';
fooFn['test'] = () => {};

...

// now I can do this:
fooFn();
fooFn.HELLO;
fooFn.test();
```

The first function type is seemingly straightforward:

```
type Foo = () => {
  id :string,
  type :string
}
```

I'm stuck figuring out the second. It's not clear to me how to build off of function types.

I tried using intersection:

```
type FooExt = Foo & {
  HELLO :string,
  test :() => mixed
}
```

However, this approach fails:

```
// Errors:
2: type FooExt = Foo & {
                       ^ property `HELLO` of object type. Property not found in
7: const fooFn :FooExt = () => ({ id: '...', type: '...' });
                         ^ function

2: type FooExt = Foo & {
                       ^ property `test` of object type. Property not found in
7: const fooFn :FooExt = () => ({ id: '...', type: '...' });
                         ^ function
```

How do I define a `FooExt` function type that "extends" `Foo` but also includes the extra properties?

[Link to Flow Try][1]

  [1]: https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAKAlMgfFA3gKCigEsATKALgGdgAnYgOwHMAaQqUSSm+5-AX3ydo8OAFEAHsGSwEUAGR52ACTEAZNQHludRq3bAINShmxQAtsQkRSA-PgDGcBsYBmCGA0qjJ0lKaQcVFwSUgooAHIAOhiIlg5wCHDo2Kh+dABufHc4TwBtCNUNTQiAXRkIgHVNACU1ABEIrJz8iMMaMpkAnFx+LPwAegGOAAtiKigqEbgAVwAbcjAAQyoqbI8GDGaNqKKtbdyGKPbgLfsh0fHJ6fnyVyXiOfXDqMqazQA5AHEDzyiAd1oziYWyAA

**Comment by apsavin** [comment]
It's quite clear from flow errors that in your example you're trying to say:
"See, flow, my fooFn is an extended function - FooExt"

but flow answers:

no, it does not have HELLO property
no, it does not have test property

The fact that you adds these props in the next line means nothing since the props are required (to be from the start).

try [this](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAKAlMgfFA3gKCigEsATKALgGdgAnYgOwHMAaQqUSSm+5-AX3ydo8OAFEAHsGR52AEgDGAQwA2KirARsiACTEAZfQHludRq3bAINShmxQAtsQkRSA-PgVwGNh0oDWEKIwDDJ2SDgERF4+0gBmoSjhOKi4JKQaAOQAdLmZLBzgEFm52ZlQ-OgA3OwJ2XqGJiiZAOpGAEr6ACKZNUQJANqZVjSZALphmBF4-H1QtBDAAK60oQk1sx4xNnEIIZSiktIofoHBDBg1+AD01xwAFsRUUFT3cEsq5GBKVFT4u3AQpd-nsGPUDMYagCQtkRsBgTc7sBHs9Xu9PlA4kpiCoQYCwS12kYAHIAcShoOyAHdaN4mJcgA)

**Comment by UnsungHero97** [comment]
Thanks for the suggestion, @apsavin. It's not quite what I'm looking for. Let me try to clarify with a more specific example:

```
type Foo = () => { id :string, type :string }

export function getFancyFoo(type :string) :FancyFoo {

  const id :string = randomId();
  const foo :Foo = getFoo(id, type);

  ['A', 'B', 'C'].forEach((thing :string) => {
    foo[thing.toUpperCase()] = thing.toUpperCase();
    foo[thing.toLowerCase()] = () => { /* function that does fancy thing */ };
  });

  return foo;
}
```

The `getFancyFoo` function will first get a `Foo` function, and then decorate/enhance it with extra properties. At the end of the function, `foo` will look like this (Chrome Dev Tools):

<img width="223" alt="screen shot 2017-10-30 at 3 40 44 pm" src="https://user-images.githubusercontent.com/440299/32199208-d2a8ed80-bd88-11e7-8d9b-9b5cf0c0cec2.png">

`FancyFoo` is a `Foo` function, but it also has the extra properties added to it. I'm stuck on defining the `FancyFoo` function type.

**Comment by jcready** [comment]
This seems to do what you want:

```js
type Foo = () => { id :string, type :string }

declare var randomId: () => string;
declare var getFoo: (id: string, type: string) => Foo;

type FancyFoo = {
  $call: Foo;
  A: string;
  B: string;
  C: string;
  a: () => string;
  b: () => number;
  c: () => [];
}

export function getFancyFoo(type :string) :FancyFoo {

  const id :string = randomId();
  const foo :Foo = getFoo(id, type);

  ['A', 'B', 'C'].forEach((thing :string) => {
    foo[thing.toUpperCase()] = thing.toUpperCase();
    foo[thing.toLowerCase()] = () => { /* function that does fancy thing */ };
  });

  return (foo: any);
}

const test = getFancyFoo('wat')
test()
test.A.toUpperCase()
test.B.toUpperCase()
test.C.toUpperCase()
test.a().toUpperCase()
test.b().toFixed()
test.c().indexOf()
```

**Comment by UnsungHero97** [comment]
@jcready `return (foo :any);` seems counter-intuitive. Why is it needed?

**Comment by jcready** [comment]
Without the `any` I do not believe it is possible to do using flow.

**Comment by UnsungHero97** [comment]
@jcready thanks for the effort in finding a workaround! You should put up an answer on StackOverflow as well so I can accept it.

That said, the goal here was to figure out the right way to use Flow for type checking this example. It seems like this is currently not supported.

**Comment by apsavin** [comment]
Another way to avoid `any` is to cast `foo` to `Object`. It seems that `flow` finds errors correctly after [such a trick](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAKAlMgfFA3lASwBMoAuAZ2ACcCA7AcwBopRIzKaGoBfAKF6IQAxgBsAhlWgA3CVCpjaROAFsAkkVJpMSHBzr0A3AOHjJUGVSj0IweHE2pimvQ2asIz6vu047R3u6wCkIgyHi8UFAAgp6chhFQAEKx+kaRAMIpDGlQYg4+UC7xkQBG+dhQtACuyiUQVDlC5TpQANoAukZ8gTDBIHZhAwBkQbQh-hAAHmBwVMBQAGZVY8AEcLRWNr1j-QiogRReDJik2yEDuPyRQuuUhCSHcWHyiirqGI238wsIZADyJQAVsJ5ihrLY9sQ3OAIOh-JFWgByKKI5iIxKoqCI9KI9oAOh+VAAomIhAALVD7Mn6dhHegFS6RSI-OCtYDUhh44BwACqYEgVHSYnIEAw7TC7P0XN5-PqQpFHwSzIQbI59GlABk4AB3OXC0XocUoDAVfAAegAVItlkJVusWGSxPMlBByIs+g6aRazTwctw4Vc5DYqlQNiyuvwbrQ7sBXaDNrY+nZUIjtU7EegAnGMFnKHiotK+QL5Qbc8A8YlC7LBfqc7G8+kq8Xa5n6+WxBgm3qFa243iSp3uTACJMIEQ632hJ26IJJn8Fjmo3dJpoACRCkQiAA8dhwKDbit4Zp9q6J0xBRKoVFmvCX8xAmmqtXqEuzcKAA)
