### ISSUE TITLE
How to define parameter types in pairs?

### ISSUE THREAD

**Issue by CharlesStover** [facebook/flow#5228]
Let's say I have some function x(param1, param2). If param2 is true, then param1 is a number. If param2 is false, then param1 is a string.

```JS
x("valid", false);
x(12, true);
x("invalid", true); // Expected: error
x(11, false); // Expected: error
```

I feel like this is easy with declare:
```JS
declare function x(string, false);
declare function x(number, true);
```

However, declare is for definitions of functions I am using, not functions I am defining.

Maybe something like
```JS
const x: (a: string, b: false) | (a: number, b: true) = (a, b) => etc;
```

But that is not working. No matter what I try, it demands that the types of parameters a and b be specified, but I do not now how to specify them in pairs. Type of A is dependent on type of B, but not equivalent to. I would know how to do `<T: string | number>(a: T, b: T)` to make them the same, but I am at a loss at making them related. :(

Any help appreciated? Or feature requested if it's not possible.

Most specifically, I'm doing `x: (a: MyType<X>, b: true) => MySecondType<X> | (a: MyType<X & Y>, b: false) => MySecondType<X & Y>`.

**Comment by jcready** [comment]
You can do this:

```js
type Fn = {
  (a: number, b: true): number;
  (a: string, b: false): string;
}

const x: Fn = ((a, b) => { /* etc */ }: any);

(x("valid", false): string);
(x(12, true): number);
x("invalid", true); // Expected: error
x(11, false); // Expected: error
```

**Comment by CharlesStover** [comment]
What does the `any` do? I have any turned off in my project, so it would throw errors for me. Doing this without the any tells me that I need to define my parameters.

**Comment by jcready** [comment]
In that case I do not believe it is possible. The `any` is the type that can be inhabited by any other type and can also inhabit any other type. It is simply an escape hatch. It is similar to the `mixed` type which can be inhabited by any other type but cannot inhabit any other type itself.

**Comment by CharlesStover** [comment]
I'm not sure I understand what Flow is expecting to be there? Why does any fix it? Is it the definition for the function? If so, why doesn't Fn work? Or (a: one) =>two | (a: three) => four? I feel like conceptually there must be a non-any value that satisfies it, no?

**Comment by jcready** [comment]
If you place your cursor on the `x` on line 6 on [Try Flow](https://flow.org/try/#0C4TwDgpgBAYgdlAvFA3gKClAFAQwFxRwCuAtgEYQBOANFGQcJURAJQHHlUDcG2+UAZ0YBLOAHNa9KADMcAGwGsCQyqLE8AvmjQBjAPZwhUAB4F4SbLkkskAPlRQA9ACooEYDqjPHUDQRxwICw8aFjGWABEAG7ywgAmEbSyCkqCIuLBoeEAjABMtIzMbISkFJTBQA) you can see the type it is expecting at the bottom of the page:

```js
((a: number, b: true) => number) & ((a: string, b: false) => string)
```

Which is an intersection of two functions and AFAIK is not a type that could actually be satisfied by flow's inference of javascript code (hence the need to cast to `any` beforehand).

**Comment by CharlesStover** [comment]
With that definition, I have this giving me "no errors":
```JS
const x: Fn = (<T: number | string>(a: T, b: boolean): T => { return a; }: ((a: number, b: true) => number) & ((a: string, b: false) => string));
```

Is this valid?

And if so, for my initial case, it would be something like: `(<T: X | X & Y>(a: MyType<T>, b: boolean): MySecondType<T>): (a: MyType<X>, b: false): MySecondType<X> & (a: MyType<X & Y>, b: true): MySecondType<X & Y>)`

Where it accepts a type T<X> and returns U<X> or accepts T<X&Y> and returns U<X&Y>.

More specifically, this is a HOC accepting a Component with props X and appending props Y if the flag parameter is set.

But I can't say I fully understand what flow means by intersection of two functions or how I would know to do that in the future. Which is why I'm not sure if the code I came up with, though it gives no errors in Try Flow, is valid or what I'm looking for.

**Comment by bradennapier** [comment]
Yeah I am running into this as well.  Seems like it is definitely a bug in Flow itself.  In the end I have to use FlowIgnores because it appears to get the right type but gives errors that are impossible to get rid of.

This should be a really easy thing to do IMHO.  It is also very important.  It is stupid to have to refine things all the time uselessly.

To make a simple example of this:

```js
function foo(b: boolean) {
  if (b) {
  	return '1'
  }
  return 1
}


const str = foo(true); // number | string

const num = foo(false); | number | string
```

This should know exactly what each value is.  

As described above, you can intersect functions (also dont know what that is doing, but it seems to work) to get it to know the type correctly.  However it seems it will always produce errors.  If you $FlowIgnore them away you still have coverage and it returns the right type but that is just stupid 

---

The below works exactly as desired other than the fact you get a bunch of errors.

#### [Try Flow}(https://flow.org/try/#0C4TwDgpgBAShDOBXANsKBeKAKLAjAXFMAE6IQCUGAfFPCQJYB2A5pQGTZ6EBmAhsvArUojRAFtcEYuQDcAKDndEjAMbB6Ae0ZRuGjQB4AQoVx7kEXoypcoh8oQAkAYX7J9cJKgA0tmgG85KCh6bmxcSgCggEhiCGBEYm0AcgBGJMCoAF8M2PjEqBS5bIUVLTpaEgwdPSwSMlkoAHpGiuImZhKytFExKt0NLD4BChkmlp7JYiA)

```js
type Result = ((b: true) => string) & ((b: false) => number);

function foo<B: boolean>(b: B): $Call<Result, B> {
  if (b) {
  	return '1'
  }
  return 1
}


const str = foo(true); // string

const num = foo(false); // number
```

```
3: function foo<B: boolean>(b: B): $Call<Result, B> {
                                   ^ function call. Function cannot be called on any member of intersection type
1: type Result = ((b: true) => string) & ((b: false) => number);
                  ^ intersection
Member 1:
1: type Result = ((b: true) => string) & ((b: false) => number);
                  ^ function typeError:
3: function foo<B: boolean>(b: B): $Call<Result, B> {
                   ^ boolean. Expected boolean literal `true`
1: type Result = ((b: true) => string) & ((b: false) => number);
                      ^ boolean literal `true`
Member 2:
1: type Result = ((b: true) => string) & ((b: false) => number);
                                          ^ function typeError:
3: function foo<B: boolean>(b: B): $Call<Result, B> {
                   ^ boolean. Expected boolean literal `false`
1: type Result = ((b: true) => string) & ((b: false) => number);
                                              ^ boolean literal `false`
7:   return 1            ^ number. This type is incompatible with the expected return type of
3: function foo<B: boolean>(b: B): $Call<Result, B> {
                                   ^ string
```

**Comment by bradennapier** [comment]
See also: #5383
