### ISSUE TITLE
Interfaces do not allow Unions ?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5229]
https://flow.org/try/#0JYOwLgpgTgZghgYwgAgIIA9gHsDOANACQCUBhLEGYAc2QG8AoZJgVygBsAuZHMKUKgNyMmAEzhg4Afi5wQATyFNkAWwhgAFlhHTkANyzARyAD7de-AU3oBfRsOT0A9I+TAwyEVgg5wyBHCgUDXEzPhAaYBxXEGQNaBQQuDY2egRyHj9ySipyCC4MbHxiMgpqZABeOmFWTmQAckc6gBphVQ0tLjqABQB5AGUAFTqbeicXcjY5ZCS2LAB3fmRmEBEIShAIEVT09zTSqjA5rHzMXEJSLLLKhhZ2TsaWpjbNES5l1fXNkbHY9Ujptg4LDII5QADWOG2IAye2yGkCeTQpyKF32FSqt1qDWaNiAA

```js
interface AxiosXHRConfig<T> {
   url: string;
   data?: T;
   method?: void | string;  
}
```

In my mind - this would have method be:

1. ) optional to appear at all
2. ) if provided it can be undefined 
3. ) if provided it can be a string

string is NEVER allowed in this case

```js
// it doesnt care that string is in there at all
const config: AxiosXHRConfig<*> = {
  url: '/',
  method: 'POST'
}
```

```
9: const config: AxiosXHRConfig<*> = {                                     ^ object literal. This type is incompatible with
9: const config: AxiosXHRConfig<*> = {
                 ^ AxiosXHRConfig
Property `method` is incompatible:
4:    method?: void | string;  
               ^ undefined. This type is incompatible with
11:   method: 'POST'              ^ string
```

I did try variations as well - it will never accept string if it is optional in the interface.

**Comment by yury** [comment]
[try flow](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgIIA9gHsDOANACQCUBhLEGYAc2QG8AoZJgagFcoAbALmRzClBUA3IxYATOGDgB+HnBABPEU2TMAthDAALLGNm9+g5AB9kANyzAxIgL6NRyegHonyYGGRisEHOGQI4KBRtSQMBEBpgHDcQZG1oFFC4Dg56BHI+f3JKKnIIHgxsfGIyCmpkAF46UXZuZAByJ3qAGlENbV0eeoAFAHkAZQAVevo7Z1dyDgVkZI4sAHcjVhAxCEoQCDE0jI90sqoweawCzFxCUmzyqoYmWq6m1qZ2nTEeZdX1zdH6cbitKJmHBwWGQRygAGscNsQJk9jltEF8mhTsULvtKtVbpx7i1RkA)

**Comment by bradennapier** [comment]
Awesome, thanks you - read that shortly after but hadn't put it together yet.  Appreciate it.
