### ISSUE TITLE
Can I disable some rules?

### ISSUE THREAD

**Issue by lapanoid** [facebook/flow#523]
Did not find anything with google, I just want to disable false positive on fs.readFile(filename, 'utf-8')  (https://github.com/facebook/flow/issues/416)
can I do it somehow?

**Comment by mroch** [comment]
as of 0.12.0, you can add an option to your `.flowconfig` which sets up magic comments that suppress flow errors on the following line.

at facebook, we do this:

```
[options]
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
```

and then would do something like

```
/* $FlowIssue - flow doesn't type fs.readFile properly as of 0.12.0 */
var content : string = fs.readFile(filename, 'utf-8');
```

**Comment by avikchaudhuri** [comment]
@lapanoid: Looks like @mroch answered, hence closing; please reopen if it doesn't solve your issue.
