### ISSUE TITLE
Polymorphic generator functions

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#5232]
Is it possible to type polymorphic generators? E.g. consider a generator that yields on functions, and expects that `next` will be called with the return type of that function:

```js
function * demo() {
  const x : number = yield () => 3;
  const y : string = yield () => 'foobar';
}

const gen = demo(); 
let state = gen.next();
while (!state.done) {
  state = gen.next(state.value());
}
```

Flow won't compile the above example:

```
4:   const x : number = yield () => 3;
                        ^ string. This type is incompatible with
4:   const x : number = yield () => 3;
               ^ number
5:   const y : string = yield () => 'foobar';
                        ^ number. This type is incompatible with
5:   const y : string = yield () => 'foobar';
               ^ string
```

I can only get this example to compile if I explicitly type the Generator to either `yield` on `any`, or to let it accept `any` as next:

```js
const gen : Generator<any, *, *> = ...;
// or
const gen : Generator<*, *, any> = ...;
```

This does however make the entire `demo` function unsound.

Is it in any way possible to type the `demo` function above properly, without having to resort to `any`?

**Comment by TiddoLangerak** [comment]
In the mean time, I seem to have found a partial solution by (ab)using `yield *`:

```js

function * delegate<T>(val : () => T) : Generator<*, T, *> {
  var x : T = yield val;
  return x;
}
function * demo() {
  const x : number = yield * delegate(() => 3);
  const y : string = yield * delegate(() => 'foobar');
  console.log(x,y);
}

const gen : Generator<any, *, *> = demo();
let state = gen.next();
while (!state.done) {
  state = gen.next(state.value());
}
```

The final generator is still untyped, but within the `demo` function the types are correct at least.

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2613
