### ISSUE TITLE
[Question] Mocking express $Request

### ISSUE THREAD

**Issue by borlaym** [facebook/flow#5237]
Couple of more generic questions first:

- Do you annotate your unit test files with flow as well as source files?
- How do you handle mocks when the actual implementation type is fairly extensive?

Take this example:
```javascript
// parseCookieInformation.js
import type { $Request } from expess;
export default function parseCookieInformation(req: $Request) => req.cookies;
```
```javascript
//parseCookieInformation.test.js
import parseCookieInformation from './parseCookieInformation';

decribe(() =>{
  it(() => {
    expect(parseCookieInformation({ cookies: { foo: 'bar' }}).foo).toEqual('bar');
  });
});
```
Obviously this will throw a flow error, because the passed object is not a $Request. It's really convoluted to create an entire express request object if at all possible (I haven't found a constructor for it).

What is a best practice here? One solution would be to modify the underlying function by not requiring an entire request object, just what it needs, but I don't think that's a real solution. `parseCookieInformation` may call other functions that actually use other fields in the request object, but they might be mocked out in this test file.

I feel like the nature of mocks just doesn't really sit well with flow.

**Comment by apsavin** [comment]
You can try https://github.com/lykmapipo/mock-express-request and write a libdef for it using $Request type from express.

**Comment by borlaym** [comment]
That's what I ended up doing. I'm not happy about it, but it works. Thanks!
