### ISSUE TITLE
Flow doesn't resolve libdef's path correctly

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5238]
I've installed flow-typed, have imported libdefs.
Import type from module:

```js
import type { Store } from 'redux';
```
When I Ctrl+click on Store - WebStorm opens index.d.ts from /node_modules/redux/ folder while there present flow definition file /flow-typed/npm/redux_v3.x.x.js

If I import definition file directly
```js
import type { Store } from '../../../../flow-typed/npm/redux_v3.x.x';
```
I got an error: Cannot resolve symbol 'Store' and clicking on Store does not open definition file at all.

.flowconfig
```
[ignore]
<PROJECT_ROOT>/.build/.*

[options]
include_warnings=true
suppress_comment= \\(.\\|\n\\)*\\$FlowIgnore
# alias to flow folder
module.name_mapper='^flow/\(.*\)$' -> '<PROJECT_ROOT>/src/flow/\1'

[lints]
all=warn
untyped-type-import=error
sketchy-null=off
```

package.json
```
"eslint-plugin-flowtype": "^2.39.1",
"eslint-import-resolver-webpack": "^0.8.3", // for support aliases fom webpack
"eslint-plugin-import": "^2.8.0",
```

**Comment by jcready** [comment]
That's because [redux_v3.x.x.js](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/redux_v3.x.x/flow_v0.33.x-/redux_v3.x.x.js) does not export any types. It's simply a libdef which defines a module named `'redux'` which itself exports a type `Store`. Meaning the `Store` type is only able to be imported from `'redux'`.

**Comment by budarin** [comment]
but floe does not recognize it (

**Comment by jcready** [comment]
You need to change your import back to

```js
import type { Store } from 'redux';
```

**Comment by budarin** [comment]
here another error in this case: ESlint: 
**Store not found in 'redux' (import/named)**

**Comment by budarin** [comment]
I've found solution of the problem: eslint/import plugin scans node_modules and founds .ts files instead of reading definitions from flow-typed.
To solve the problem - add node_modules into ignore section of settings eslint/ignore
[like here](https://github.com/benmosher/eslint-plugin-import/issues/931)
