### ISSUE TITLE
Machine-readable output?

### ISSUE THREAD

**Issue by turbo** [facebook/flow#5239]
Hi there,

Is there a way to use flow as a binary or library such that it outputs machine-readable results? For example, this output:

```text
Error: .int/test.js:13
                 v
 13: fn('hello', {
 14:   num: "3"
 15: });
     ^ object literal. This type is incompatible with the expected param type of
  9: fn = function(str/*: string */, obj/*: Obj */)/*: string */ {
                                            ^^^ object type
  Property `num` is incompatible:
     14:   num: "3"
                ^^^ string. This type is incompatible with
      4:   num: number,
                ^^^^^^ number
Found 1 error
```

could be represented as (incomplete, but you get the idea) something like:

```json
{
  "errors": [
    {
      "file": ".int/test.js",
      "line": 13,
      "highlight": {
        "start": { "line": 13, "col": 14},
        "end":   { "line": 15, "col": 1},
        "token": "object-literal"
      },
      "message": " This type is incompatible with the expected param type of"
    }
  ]
}
```

Is there a way to get something like this today?

**Comment by turbo** [comment]
It looks like [`flow-base` (FlowService)](https://github.com/flowtype/flow-for-vscode/blob/master/lib/pkg/flow-base/lib/FlowService.js) might be what I'm looking for, but apart from the code being almost entirely undocumented, there doesn't seem to be a central package or repo maintained as an upstream source for this.

I found issue https://github.com/flowtype/flow-for-vscode/issues/6 so pinging @nmote for good measure.

**Comment by nmote** [comment]
There are a few efforts underway to make it easier to integrate Flow with an IDE but there isn't really a good general-purpose library.

You can pass most (maybe all?) Flow commands the `--json` or `--pretty` flag which will give you structured output. For example you would probably want to use `flow status --json` to get the results you're looking for here. Hopefully this works well enough for your purposes.

**Comment by turbo** [comment]
Thanks for the fast response, will try it out.
