### ISSUE TITLE
Number types

### ISSUE THREAD

**Issue by mroch** [facebook/flow#524]
Flow supports "string types", useful for enums and method overloading, e.g.

```
interface Document {
  createElement(tagName: "div"): HTMLDivElement;
  createElement(tagName: "span"): HTMLSpanElement;
  createElement(tagName: "canvas"): HTMLCanvasElement;
  createElement(tagName: string): HTMLElement;
}
```

It should also support number types, e.g. `function showItems(num: 1 | 5 | 10)`

**Comment by samwgoldman** [comment]
Ditto `boolean` types. Those, combined with a fix to #20 would help improve the type of generators' iterator result object. i.e., we could type `{ done: true, value?: R } | { done: false, value: Y }` instead of the less-user-friendly `{ done: boolean, value?: Y|R }`.

**Comment by samwgoldman** [comment]
@avikchaudhuri Seems like it would be pretty straightforward to extend the work you did with discriminated unions to support other singleton types. Is the example above for IteratorResult compelling enough of a use case?

**Comment by mroch** [comment]
coming ~today

**Comment by samwgoldman** [comment]
lol

**Comment by mroch** [comment]
number types: 7adc836446f1cb37f217cb3ba1c79ea1e224bbff
boolean types: bca7a9b5f135bf3a6ec7fcb15c7d559256171818

**Comment by samwgoldman** [comment]
So cool! I can't tell from the commits, but can the singleton number/boolean types be used to refine disjoint unions?

**Comment by mroch** [comment]
i think so but @avikchaudhuri might have some more stuff in flight... #20 is tracking that right?

**Comment by samwgoldman** [comment]
I'll give it a whirl and, if not, I think #20 is a reasonable place to track it. (Right now the wording of the issue is specific to strings.)

**Comment by avikchaudhuri** [comment]
yeah I have a diff in flight that will include a test for this!

**Comment by samwgoldman** [comment]
Haha, rad!

**Comment by avikchaudhuri** [comment]
@samwgoldman so https://github.com/facebook/flow/commit/28f01d1800618ad9f679d7a394c1feff1edf3a16 just landed, which among other things supports refinements based on singleton numbers BUT NOT booleans. It turns out we do a lot of stuff with booleans already, which go down different code paths than the ones for string and number literals. So you could still give that a whirl. ;)

**Comment by mroch** [comment]
cross-referencing #577

**Comment by majhork** [comment]
@mrock I'm having trouble with negative number types. Are they supported?
