### ISSUE TITLE
v0.58.0 does not work when compiled to JS for flow.org/try/

### ISSUE THREAD

**Issue by lrowe** [facebook/flow#5241]
Got to https://flow.org/try/ and open devtools. Uncaught in Promise errors are shown in the console with message: "re_search_forward: not implemented in JS".

**Comment by h-michael** [comment]
Got same errors.
Mac/Chrome: 62.0.3202.75

![2017-11-02 11 47 23](https://user-images.githubusercontent.com/4556097/32307414-b2501e5e-bfc3-11e7-8a9d-a858216c4b03.jpg)

**Comment by MichaelDeBoey** [comment]
Seems to be fixed I guess?

**Comment by h-michael** [comment]
I checked fixed too.
