### ISSUE TITLE
Spread Operator isn't working correctly

### ISSUE THREAD

**Issue by MichaelDeBoey** [facebook/flow#5243]
So I'm having the following situation (code is also on [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDCcAdlAJYDmYAvGAN6phgCGM8CAziwMYBcYAEZw4MPCxIAaJq3aJOCuAOGjxUmXgC2LcjAGcMAJ3IlK05hUMGSLTXn1GTZmTAmUBAGTcBXFpTzmYK7WtvZgBsamgXDGlCYOkc7MOIZwPHgKsIgCJN6agniGgYZ4AI7eGRg4CAAmyiJiEoGcABaIPPCceDgw3nEk9apNMhhwANZ4A+GOUagAvgDcmLgEXqa+-rRgAOQ1eNtgAD47kwfH21CGZzskMNtL2PhgACpaODEshljEZFRbjMw2BxuPwhA01EdpolAkD5IpBo0SJCIk5AlodHooaiZJYQnYEtjmK5TJ4fH4Ai4WHiwijZswYlR4li6WAUmkMpwsggcnkCoZkTMkmASuVKtU6mChkjjrSha12p1ur1+giITLBYFRhMprLpIt0DxSAYwIaSAA3QoYH4USgABU+tk4WwAFKabfbDI6BK9NO9PV9rVQAJQCQPUGgAPgYMlNxvosK4vEksmBimTbPSmQ4yZFFQM4uT8oQHTgXR6fRMgWY1eY6N0ydxGBsdmTxLMQSpTdCyYZ-WTWsmMhrzDm3reHwDpBtWzdVA9jqWMhKGG8hiRAOrADpt7O7Q7NJxk8wh2BgMA6zAG+QrF2Wx2oh3qT3YpWwAP1DWTwmQQJTRbDBg86aM8cAAELghIzrfrwQZVimcKcEoJqkP+gH7iB4FSlBchcIosEnhmHJcr+KGWkBIEAHK8oUzqEVmiD4TWuZirUJHmmR6FgRBJDOsx+a1Ix1ZFiWZbKkyf4cZ6wFcVhwmKuW-SCfq+qxhgyHsQB5EyYiLo4PuqoSAKiQhpKOmRtGTF4Cua5gAABgAJPQADKgq0fuQZzLZm6jB4iCFIQVJ4M6Qa0DQdDbEYFT3PMSyqepqFaVR+SFLp+lgLkyX8uqxk8pltBRhuzDLquSJ6VYeAAJIkBgblScmACMAAMQZLPqqBxRgbxhmOvoTt8U5-HQG7QaCkUUoCOEKIhAgRYYUVotougzQAVnALQkJuNRwHgEB4AAHrYPR4JuhqaNsgSNs2YTbAAUmtJDnZSJInA9gTBLe10ACLbY99IvlM2wtBgVR8GevYmCdcBnYEdGchwM31b9wplHmVSsW+c3jeEbTFvJYkA1AbBdEj74zZ1BgAPrvo9KlGmpu6hgN4bxZaYZAZwzqdb6YYtagQA)):

I get some config variables (either from the config file or provided with `data-`attributes).  
In the config file they're correct types (`boolean` or `number`), but when provided via `data-`attributes, they're strings.
```js
type Language = 'de' | 'en' | 'fr' | 'nl';
type TemporaryConfig = {
  allowsac: boolean | string,
  allowssso: boolean | string,
  email: string,
  firstname: string,
  lang: Language,
  lastname: string,
  origin: string,
  processflow: number | string,
  requestpwd: boolean | string,
  showcloseplugin: boolean | string,
  token: string,
};

const tempConfig: TemporaryConfig = {
  allowsac: true,
  allowssso: 'true',
  email: 'john.doe@example.com',
  firstname: 'John',
  lang: 'en',
  lastname: 'Doe',
  origin: 'http://origin.com',
  processflow: '1',
  requestpwd: true,
  showcloseplugin: 'false',
  token: 'test_token',
};
```

So I convert them to the correct types.
```js
type Config = {
  allowsac: boolean,
  allowssso: boolean,
  email: string,
  firstname: string,
  lang: Language,
  lastname: string,
  origin: string,
  processflow: number,
  requestpwd: boolean,
  showcloseplugin: boolean,
  token: string,
};

const config: Config = convertConfigParams(tempConfig);
```

With the following conversion function:
```js
const convertConfigParams = (configParams: TemporaryConfig): Config => {
  const {allowsac, allowssso, processflow, requestpwd, showcloseplugin}: TemporaryConfig = configParams;

  return {
    ...configParams,   
    allowsac: convertParamToBoolean(allowsac),
    allowssso: convertParamToBoolean(allowssso),
    processflow: convertParamToNumber(processflow),
    requestpwd: convertParamToBoolean(requestpwd),
    showcloseplugin: convertParamToBoolean(showcloseplugin),
  };
};
const convertParamToBoolean = (param: boolean | string): boolean => {
    return `${String(param)}`.toLowerCase() === 'true';
};
const convertParamToNumber = (param: number | string): number => {
    return parseInt(param, 10);
};
```

One of the errors I get, is that `allowsac` isn't of type `boolean`:
```js
36:   return {
             ^ object literal. This type is incompatible with the expected return type of
31: const convertConfigParams = (configParams: TemporaryConfig): Config => {
                                                                 ^ object type
Property `allowsac` is incompatible:
18:   allowsac: boolean | string,
                          ^ string. This type is incompatible with
4:   allowsac: boolean,
               ^ boolean
```
Which is because `flow` isn't counting in the overwritten value (which is a `boolean`).

I can solve this by setting all the other values explicitly in the return value and removing the spread operator, but that would be a bit cumbersome I think?
```js
return {
  email,
  firstname,
  lang,
  lastname,
  origin,
  token,
  
  allowsac: convertParamToBoolean(allowsac),
  allowssso: convertParamToBoolean(allowssso),
  processflow: convertParamToNumber(processflow),
  requestpwd: convertParamToBoolean(requestpwd),
  showcloseplugin: convertParamToBoolean(showcloseplugin),
};
```

**Comment by bradennapier** [comment]
@MichaelDeBoey this one might be a mix of a bug in v58 and the Try not actually using older versions of Flow. 

This works fine on my older flow and doesnt seem to work on v58 on my system.  It would seem that spread was broken completely in this version.  Still playing with this one a bit.

**Comment by Gisleburt** [comment]
FYI this is still a problem: #7210

**Comment by villesau** [comment]
This should fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors on master
