### ISSUE TITLE
Best way to copy a type and make every attribute optional

### ISSUE THREAD

**Issue by MichaelDeBoey** [facebook/flow#5246]
This one is most likely related to #5245 I guess...

What's the best way to copy my `Config` type and make it into an `PartialConfig`, which is just a `Config`, but with every attribute as an optional type.

So
```js
type Config = {
  allowsac: boolean,
  allowssso: boolean,
  email?: string,
  firstname: string,
};
````
will be
```js
type PartialConfig = {
  allowsac?: boolean,
  allowssso?: boolean,
  email?: string,
  firstname?: string,
};
```

**Comment by jcready** [comment]
```js
type PartialConfig = $Shape<Config>
```

**Comment by MichaelDeBoey** [comment]
Thanks @jcready! 🙂

That one's not in the docs, so that's why I didn't find it I guess.

It it recursive (for non-primary types), or do I have to make an explicit type for that?

**Comment by bradennapier** [comment]
This also will make the values optional:

```js
type Config = {
   one: string
}

type OptionalConfig = { ...Config }
```

but $Shape is better in this case since it works on exact types whereas the examplea bove would only work if it was not an exact type.

**Comment by jcready** [comment]
Another possible solution that gets [around problems with `$Shape`](https://github.com/facebook/flow/issues/3550):

```js
type PartialConfig = $Rest<Config, {}>
```

**Comment by jamesisaac** [comment]
Closing as $Shape is now documented
