### ISSUE TITLE
Interfaces should be able to inherit from non interface types

### ISSUE THREAD

**Issue by aikar** [facebook/flow#5249]
Usecase
```javascript
import type EventEmitter from "events";

export interface MyAPI extends EventEmitter {
    someOtherMethod(): void;
}
```
Or some special `extends $Type<EventEmitter>` kind of thing

Given a signature like this, I define my libraries exported API. I want to mandate that anything that implements MyAPI should also implement the specs of a NodeJS EventEmitter.

I should then be able to write code like:

```javascript
const api: MyAPI = config.useCustomEventEmitter
    ? getAPIWithCustomEventEmitter() 
    : getAPIWithDefaultEventEmitter();
api.addListener("test", (data) => { console.log("got test", data); });
api.emit("test", "foo");
api.someOtherMethod();
```

I am currently doing this in 0.55 by copying the libdefs from the built in node.js types and pasting them into my own custom interface, and modifying the return type to `: *` since `: this` is not allowed outside of `declare class`

However on updating flow to 0.57.3, I started getting
`Property `addListener` is incompatible: 'function type'. See https://github.com/facebook/flow/blob/v0.57.3/lib/node.js#L653. This type is incompatible with 'function type'`

So that workaround no longer works, forcing me to stay on 0.55.

I'm asking for some way to let interfaces inherit the type restrictions of another type in the same way 
`type Foo = Bar & Baz` works, be it through `$Foo<>` style usage, or simply letting `implements Type` work

**Comment by bradennapier** [comment]
@aikar I may not be understanding your request completely but as far as I am aware this is already the case.

```js
interface Bar {
  two: () => void;
}

interface Foo extends Bar {
  one: () => void;
}

/*
  $ExpectError
    Baz
      This type is incompatible with
        Bar
        --
        Property `two` is incompatible:
          property `two` of Bar
          --
          Property not found in
          Baz
*/
class Baz implements Foo {
  one = () => undefined;
}

```

**Comment by aikar** [comment]
@bradennapier Yes thats fine and dandy when the type you want to inherit is actually an interface.

I am talking about for when it is not - Core NodeJS types and third party type definitions where you don't have that control.

My issue describes why I'm unable to manually create my own interface too.
