### ISSUE TITLE
ES6 import of default and properties doesn't work

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#525]
These two things work:

    import _ from 'lodash';
    import {map, filter} from 'lodash';

but flow fails to parse this which I'm pretty sure is valid:

    import _, {map, filter} from 'lodash';

**Comment by jeffmo** [comment]
For reference, can you post the interface definition you're using for lodash?

**Comment by AgentME** [comment]
The error happens without any interface definition files. Here's the error for reference:

```
.../foo.js:7:12,14: identifier map
Could not resolve name
```

(Not directly related, but I can't get any sort of interface definitions for external modules to work anyway: https://github.com/facebook/flow/issues/526)

**Comment by avikchaudhuri** [comment]
@AgentME see my comment on that task, maybe you're setting up your libs wrong? Please report back here if fixing the setup causes this issue to go away, thanks!

**Comment by AgentME** [comment]
I just found that Flow fails to parse the following too:

```javascript
/* @flow */
import 'babel/polyfill'; // just execute it without importing anything from it
```

**Comment by jeffmo** [comment]
@AgentME: Nice catch! Can you open another issue for that so we can track it there? This should mostly just be parser work

**Comment by AgentME** [comment]
This issue is a parse issue too (same sort of error; it had nothing to do with the definition files), though I've opened that one as https://github.com/facebook/flow/issues/574.

**Comment by nmn** [comment]
+1

Same error for me. Flow fails to work in this case:
```
import _, {map, filter} from 'lodash';
```

**Comment by jeffmo** [comment]
BTW I totally glosses over the fact that this was a default+named import in one single statement. Apologies for not seeing that sooner.

As @samwgoldman mentioned on the PR itself, #600 should fix both of these issues

**Comment by jeffmo** [comment]
https://github.com/facebook/flow/pull/600 just landed which should fix this (and will be in the upcoming release)
