### ISSUE TITLE
Can't get "declare module ..." to work

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#526]
I'm trying to make some type definitions for some libraries I'm using, but I can't get it to work. I've been reading http://flowtype.org/docs/declarations.html but it doesn't seem I'm understanding it correctly.

Clone https://github.com/AgentME/flow-test/, run `npm install` (to install lodash locally), and then run "flow check". The flow check should fail because of misuse of lodash, but it does not.

flow-libs/lodash.js (pretty bare-bones so far)
```
declare module lodash {
  declare function map<T,U>(array: T[], cb: (value: T, key: number|string, array: T[]) => U, thisArg?: any): U[];
  declare function filter<T>(array: T[], cb: (value: T, key: number|string, array: T[]) => boolean, thisArg?: any): T[];
}
```

index.js
```
/* @flow */
// jshint ignore:start

import {map} from 'lodash';

// should work
var list = map([5, 6], x=>x+1);
console.log(list);

// should fail flow check
var list2 = map(123, 'foo');
console.log(list2);
```

**Comment by samwgoldman** [comment]
Possibly the same issue as #447

**Comment by avikchaudhuri** [comment]
@AgentME Sorry, couldn't repro. I made a dir called test, added index.js to it, made a subdir called lib, added lodash.js to it, made a .flowconfig in test/ with the lines
[libs]
lib

and ran flow check test, got the expected errors:

/home/avik/test/index.js:11:13,27: function call
Error:
/home/avik/test/index.js:11:17,19: number
This type is incompatible with
/home/avik/test/lib/lodash.js:2:36,38: array type

/home/avik/test/index.js:11:13,27: function call
Error:
/home/avik/test/index.js:11:22,26: string
This type is incompatible with
/home/avik/test/lib/lodash.js:2:45,91: function type

**Comment by AgentME** [comment]
If you have lodash installed (after running "npm install lodash"), then `flow check` fails to fail.

**Comment by samwgoldman** [comment]
Yeah, I can repro the same behavior, but only when the node module exists.

**Comment by avikchaudhuri** [comment]
Merging with #447
