### ISSUE TITLE
Disjoint doesn't detect branching in filter

### ISSUE THREAD

**Issue by klauszhang** [facebook/flow#5261]
It seems flow cannot pick Array.filter branching.

[flow/try](https://flow.org/try/#0PTACDMBsHsHcCh4BcCeAHApgAgGLWgLwDe8AlgM4BqAhpKQCYBcSATgK4YA08WWAbrQ6NyrUgDsA5vAC+iVJiwAhai2JkqtBo3C1yXeBhYtoLYaMmzk6bACUM5NpCQE80AD7KWiEFgkYkWNBikChYrGxIABahLPaOSPAAxkEiWLEOTuQEANpEFDR0TOFc-IIYjADk4PgV0pxYeRqF2rolhsamFbDGkgCEtQC68AB04KROhgAU6fEEAHwzTsP5mvQAlCMAttRo03FO84tIwwKQHGsA3IhAA)

Now we cannot use filter/map approach to determine which part of data we need to map.

to get around it, we could use an internal array
```js
const resultsArr=[]
data.forEach(result=>{
if(result.isValid){
  resultsArr.push(result.value)
}
})
```

I think this is a bug, please fix it. 

Thank you!

**Comment by vicapow** [comment]
As a workaround, you can put the map first:

````js
const results=[{isValid:true, value:'foo'}, {isValid:false, error:'wrong!'}]
.map(result => result.isValid ? result : null)
.filter(Boolean);
````

[flow/try](https://flow.org/try/#0PTACDMBsHsHcCh4BcCeAHApgAgGLWgLwDe8AlgM4BqAhpKQCYBcSATgK4YA08WWAbrQ6NyrUgDsA5vAC+iVJiwAhai2JkqtBo3C1yXeBhYtoLYaMmzk6bACUM5NpCQE80AD7KWiEFgkYkWNBikChYrGxIABahLPaOSPAAxkEiWLEOTuQEANpEFDR0TOFc-IIYjADk4PgV0pxYeRqF2rolhsamFbDGkgCEtQC68AB0ALbUaAAU6fFYBAB8aXFOw-ma9FgA-EsZAYxYYo6QAJQj4KROhpOK+JAY1GLHANyIQA)

**Comment by vicapow** [comment]
This is also a duplicate of https://github.com/facebook/flow/issues/4875

**Comment by klauszhang** [comment]
@vicapow good point! thanks!
