### ISSUE TITLE
Accessing Opaque Type twice removes type

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5266]
Not really sure how to report this one.

consider:

```js
function transformHandshakeResponse<R: Handshake>(response: R) {
  const identity = response.identity;
  if (response.identity) {
    return {
      identity,
      result: 'success',
      handshake: true,
      uuid: typeof response.uuid === 'string' ? response.uuid : 'handshake',
    };;
  }
  throw new TypeError(
    'Bad Result for Handshake Response Wrapper, expected identity',
  );
}
```

In the case above, you will notice I first save `identity` (my opaque type on the object i receive), then I check `response.identity`, then I use the original `identity` to save onto the object.  I do this because if I do:

```js
function transformHandshakeResponse<R: Handshake>(response: R) {
  if (response.identity) {
    return {
      identity: response.identity,
      result: 'success',
      handshake: true,
      uuid: typeof response.uuid === 'string' ? response.uuid : 'handshake',
    };
  }
  throw new TypeError(
    'Bad Result for Handshake Response Wrapper, expected identity',
  );
}
```

then I get:

```
object literal
   This type is incompatible with
   object type
   ---
     Property `identity` is incompatible:
     string
     ---
        This type is incompatible with
        Datastream$Identity
```

**Comment by rvion** [comment]
I think the problem doesn't come from "Accessing Opaque Type twice", but rather from checking it agains null or undefined.

I described my case here: https://github.com/facebook/flow/issues/5266) with a shorter reproductible example

-------

besides this, this problem is very problematic for me, as I can't find any good workaround

**Comment by darichey** [comment]
The second example works now.
