### ISSUE TITLE
Flow consumes all memory

### ISSUE THREAD

**Issue by mvolkmann** [facebook/flow#5271]
When flow is run, it searches for the file .flowconfig. If it isn't found in the current directory, Flow searches upward through all ancestor directories until it is found. Then the runs flow on all JavaScript files in that directory and all directories below it.

But what happens when .flowconfig is never found? The answer is that it stops looking when the home directory is reached and then runs flow on every file under the home directory. You can tell this has happened because the fan in your computer will start making a noise like a jet engine. This will consume all memory on the computer and it will lock up.

Many of us have our editors/IDEs to automatically run Flow on JavaScript files. In my case this happens using the Vim plugin ALE. This is frequently what initiates the problem for me.

This seems like such as easy fix. All that has to change is to make it so flow does not run if no .flowconfig file is found. Are there any reasons why this isn't a desirable change?

**Comment by aikar** [comment]
Ultimately this is a user issue, but I agree that flow should die and report an error instead of this behavior.

It shouldn't start parsing until it finds a flow config (and then really hope you didn't put a flow config in your home folder)

**Comment by barbalex** [comment]
Is this related to https://github.com/facebook/flow/issues/2152?

**Comment by barbalex** [comment]
This seems to be rather prominent in the issues. Maybe related issues found after a five minute search:

- https://github.com/facebook/flow/issues/5271
- https://github.com/facebook/flow/issues/4370
- https://github.com/facebook/flow/issues/4070
- https://github.com/facebook/flow/issues/4046
- https://github.com/facebook/flow/issues/3565
- https://github.com/facebook/flow/issues/3370
- https://github.com/facebook/flow/issues/2152

**Comment by mvolkmann** [comment]
I just looked through all the referenced issues. Only one of them, #3370, suggests that the issue might be that Flow is trying to run on too many files. I feel quite certain this issue would be fixed by changing Flow to report an error and not run if it cannot find a .flowconfig file anywhere in ancestor directories from where it is run. This suggestion doesn’t appear in any of the referenced issues.

**Comment by mvolkmann** [comment]
I wondered if the primary contributors to Flow think that this isn’t a serious issue. In my opinion this issue should be near the top of the list for things to be fixed soon. How is it that this doesn’t hit nearly everyone that uses Flow?

**Comment by JofArnold** [comment]
Does adding type checking to all your arguments in map and reduce functions fix the problem as per my comment here? https://github.com/facebook/flow/issues/2152#issuecomment-366221060

**Comment by mrkev** [comment]
Closing becase flow now warns of missing `.flowconfig`s in ancestors (not sure since what version, but here's the message I got with 0.72.0:

```
Could not find a .flowconfig in . or any of its parent directories.
See "flow init --help" for more info

```

**Comment by mvolkmann** [comment]
I am running Flow 0.76.0 and do not see this message. I created a new React application with create-react-app, cd'ed to that directory, and ran "flow". It's running for every and consuming most of my CPU time. It seems like this issue needs to be reopened.

**Comment by mrkev** [comment]
Are you sure you don't have a `.flowconfig` in any of the parent directories? What OS is this on?

**Comment by mvolkmann** [comment]
Sorry, I did have a .flowconfig in my home directory. After removing that, I now get the desired error message. Thanks!
