### ISSUE TITLE
covariance - outside constructor 

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5274]
I have run into this a few times where it would be nice to have a property be covariant -- but only either once it has been set the first time (that would probably be difficult to track/maintain) -- or outside of a classes/interfaces constructor.  

In the case below, since the property is never initialized but is defined in a way that it is a non-maybe type - it would make sense in my eyes that it would allow initialization in the constructor.

If that isn't something that you guys think should be the case, then it should definitely throw an error in this case sine it can be inferred that it is impossible for `this.client` to match the given type.

```js
export class ClientPlugin implements Plugin$Master {
  +client: DatastreamClient;
  +config: PluginConfig;

  constructor(client: DatastreamClient, config?: PluginConfig) {
    this.client = client;
    this.config = config || {};
  }
}
```

Where if any other class or subclass tried to set the property outside of the constructor call it would be an error - but it would be allowed here.

I know we can use property initializers but that does not always work.

I can think of it could be simulated using opaque types but would require multiply files setup and a good amount of boilerplate.

**Comment by vkurchatkin** [comment]
Try it on master, it works exactly the way you want.

**Comment by bradennapier** [comment]
Sweet!  Thanks as always @vkurchatkin
