### ISSUE TITLE
Can't use `get` in destructuring or shorthand object notation

### ISSUE THREAD

**Issue by splodingsocks** [facebook/flow#528]
Heya!

I consistently get the following errors while trying to require and destructure certain operations from lodash.

1. Require 'get' or 'set'

```
var {get} = require('lodash')
```

Error:

```
Unexpected token }
```

- - -

2. Require 'set' and 'get' (but only in that order)

```
var {set, get} = require('lodash')
```

Error:

```
unexpected parsing exception: Failure("Nooo: (\n")
```

If 'get' comes first and not set, only the first error shows (the parsing error)

I can successfully require both of them without desctructuring:

```
var set = require('lodash').set
var get = require('lodash').get
```

If I require 'get' separately, but still try to require 'set' through destructuring I get the funny "Nooo" error.

Running Flow 0.12.0

**Comment by mroch** [comment]
This also happens on object short notation, which I think is the same underlying issue as destructuring.

From #661:

```
/* @flow */
function get () {
}
module.exports = { get };
```

The error is `Unexpected token }`, on the `module.exports` line. 

I also get a similar error if `get` isn't the only thing in the object, e.g.:

```
/* @flow */
function get() {}
function add() {}
module.exports = { get, add };
```

In this case, the error is:

`Unexpected token ,`

**Comment by jeffmo** [comment]
Woo! This was fixed some time ago

**Comment by mroch** [comment]
not fixed for object short notation:

```
/* @flow */

function get() {}
function set() {}

let x = {
  get,
  set,
}
```

```
7:   get,
        ^ Unexpected token ,
8:   set,
     ^ Unexpected identifier
8:   set,
        ^ Unexpected token ,
9: }
   ^ Unexpected token }
9: }
    ^ Unexpected end of input
```
