### ISSUE TITLE
[REQUEST]: Some way of collecting results

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5283]
This actually may be what `$Compose` is for, but not positive how it can be used in this example.  I've seen a couple situations now where this has become a problem (I know `Map` and support for using `.has()` as refinement is likely similar).  

It would be nice (although I absolutely see the difficulties in providing this) to have some utility for collecting results in the case of chaining and/or future callbacks, etc. 

I have been able to cheat a little bit by building an interface such as:

```js
declare function $GetResults<T>(T): [void | Error, T];
declare type $Results<T> = $Call<typeof $GetResults, T>
declare type Redis$ArrayOfResults<T> = Array<$Results<T>>

declare export interface Redis$Pipeline<
      A = empty,
      B = empty,
      C = empty,
      D = empty,
      E = empty,
      F = empty,
      G = empty,
      H = empty,
      I = empty
    > {
      hgetall<K: string>(key: K): Redis$Pipeline<void | Object, A, B, C, D, E, F, G, H>;
      hgetall<K: string, V>(key: K, callback: Redis$Callback<V>): Redis$Pipeline<V, A, B, C, D, E, F, G, H>;
      hmset<K, V>(key: K, value: V): Redis$Pipeline<Redis$SimpleResult, A, B, C, D, E, F, G, H>;
      hmset<K, V>(key: K, value: V, callback: Redis$Callback<Redis$SimpleResult>): Redis$Pipeline<Redis$SimpleResult, A, B, C, D, E, F, G, H>;
      exec(): Promise<Redis$ArrayOfResults<A | B | C | D | E | F | G | H | I>>;
      exec(callback: Redis$Callback<Redis$ArrayOfResults<A | B | C | D | E | F | G | H | I>>): any;
    }
```

Where each call is chained and the results are provided once exec is called in an array.  This does work but obviously if the chain grows past the `I` then we are a bit screwed, requiring we add more and more options to represent such a case.

I am thinking something like the following:

```js
declare export interface Redis$Pipeline<...T> {
      hgetall<K: string>(key: K): Redis$Pipeline<void | Object, ...T>;
      hgetall<K: string, V>(key: K, callback: Redis$Callback<V>): Redis$Pipeline<V, ...T>;
      hmset<K, V>(key: K, value: V): Redis$Pipeline<Redis$SimpleResult, ...T>;
      hmset<K, V>(key: K, value: V, callback: Redis$Callback<Redis$SimpleResult>): Redis$Pipeline<Redis$SimpleResult, ...T>;
      exec(): Promise<Redis$ArrayOfResults<...T>>;
      exec(callback: Redis$Callback<Redis$ArrayOfResults<...T>>): any;
    }
```

Where we are simply collecting values with each call.  This very well may already have some method of representation that I am not aware of.  

---

The example showing the collection of results also doesn't really produce workable results in the end since the goal would be to end with a `tuple` of the results rather than a tuple of the results and a bunch of voids (which makes it hard to handle the various cases).  

If Flow could collect then return in a way that it was aware exactly how many results are in the tuples and what they are - it would really make it powerful.

**Comment by Peeja** [comment]
Would you include some code demonstrating what you're trying to type? Being unfamiliar with the Redis API, it's hard to infer what this is trying to solve.
