### ISSUE TITLE
Allow `uncovered` variable use in `throw` or `console` commands?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5292]
So I just ran into an issue which is urking me big time due to my OCD.  I absolutely expect 100% coverage on every file I use.  

The problem is that when I want to provide error messaging, it is killing my coverage when I try to use the variable in the case it can not be found in a union, for example.

```js
/* @flow */

type RedisEvents = {|
  CLIENT_DISCONNECT: (event: string, client: DatastreamClient) => void,
  CLIENT_REMOVED: (event: string, client: DatastreamClient) => void,
  CLIENT_KILLED: (event: string, client: DatastreamClient) => void,
  CLIENT_STATE: (event: string, client: DatastreamClient) => void,
  CLIENT_IDENTITY: (event: string, client: DatastreamClient) => mixed,
|};

type RedisEventTypes = $Keys<RedisEvents>;

type RedisEventResponse<T> = $Call<
  $ElementType<RedisEvents, T>,
  T,
  DatastreamClient,
>;

async function handleRedisEvent(event: RedisEventTypes, client: DatastreamClient) {
  switch (event) {
    case 'CLIENT_DISCONNECT':
    case 'CLIENT_REMOVED':
    case 'CLIENT_KILLED': {
      break;
    }
    case 'CLIENT_STATE': {
      break;
    }
    case 'CLIENT_IDENTITY': {
      break;
    }
    default: {
      // this kills my coverage
      throw new TypeError(`Unhandled Redis Event: ${event}`);
    }
  }
}

export default function routeRedisClientEvent<
  T: RedisEventTypes,
  C: DatastreamClient,
  R: RedisEventResponse<T>,
>(event: T, client: C): Promise<void | R> {
  return handleRedisEvent(event, client).catch((err: Error) => {
    LOG('[ERROR] | [CLIENT/REDIS EVENT] | ', err);
  });
}

```

![image](https://user-images.githubusercontent.com/15365418/32518483-9253ded4-c3be-11e7-86ee-1bded7366507.png)

In the very least it may be nice to allow ignoring of flow coverage in some way 

```js
// $FlowIgnoreCoverage
```

**Comment by vkurchatkin** [comment]
The question is: why are you doing this, if you already know that this code is unreachable?

**Comment by bradennapier** [comment]
It is unreachable in the codebase, but it is a back-end API and theoretically a user may provide an invalid event type.  The errors allow me to log them via our logging platform. 

So while they should never occur, the insanity check is still there to aid in the case it does occur.

**Comment by vkurchatkin** [comment]
So there's your answer: Flow marks this as uncovered, because it is, in fact, unsafe.

**Comment by bradennapier** [comment]
Yet there is no way to use it for error reporting - thus using flow also reduces your ability to report errors.  

We should be able to report them without getting hit on that.  It is safe - and worst case - at least provide a way of marking it and/or refining that it can be used for the expression.

**Comment by vkurchatkin** [comment]
> Yet there is no way to use it for error reporting - thus using flow also reduces your ability to report errors.

As you can see, Flow allows you to do anything. Yet it can't verify safety of these operations, so it marks them as uncovered. It seems that what you want is a generic way to suppress coverage warnings.

**Comment by bradennapier** [comment]
In an opinionated manner, yes.  I believe in specific cases it would make sense such as this where we are "penalized" for providing error reporting at runtime.  

Others may not be as OCD as me but even 98% coverage urks me big time already.  Stoped using try/catch all together already.

**Comment by SamChou19815** [comment]
Coverage is not something that we intend to provide mechanism to suppress.
