### ISSUE TITLE
(...args: any) throws error in exported function

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#530]
I need to a code that looks like this

    export class Foo {
        bar(...args: any) {
            console.log(args.length)
        }
    }
    
    var k = new Foo()
    k.bar("ab", "cd")

However, flow doesn't like this

    (...): element of any
    Missing annotation

Why doesn't it allow that? And how to make it happy?

**Comment by runn1ng** [comment]
bar(arg: any) {
          ....
    }

works, and this works too


    bar(args: Array<any>) {
          ....
    }

**Comment by runn1ng** [comment]
I need this, so I can make a function a goal for event emitter, 

For example like this

    export class Foo {
        bar(...args: any) {
            console.log(args.length)
        }
    }

    var foo = new Foo();
    var emitter = new EventEmitter();
    emitter.once("event", (...args) => foo.bar(...args))

I can probably rewrite it as this

    export class Foo {
        bar(args: Array<any>) {
            console.log(args.length)
        }
    }

    var foo = new Foo();
    var emitter = new EventEmitter();
    emitter.once("event", (...args) => foo.bar(args))

But I feel it's a bit strange

**Comment by runn1ng** [comment]
(I am leaving alone that emitter's on() is probably wrong in the definition, I will make it as a separate pull request :))

**Comment by avikchaudhuri** [comment]
Thanks for the report, will fix! You can use ...args: Array<any> as a workaround.
