### ISSUE TITLE
"This module only has a default export"

### ISSUE THREAD

**Issue by karltaylor** [facebook/flow#5302]
I have a `utils/index.js` file which looks something like this to give me quick access to all the utils within my app.

```javascript
/**
 * @providesModule utils
 * @flow
 */

import isValidEmail from './isValidEmail';
import isWithinVersionRange from './isWithinVersionRange';

...more util functions

export {
  isValidEmail,
  isWithinVersionRange,
}
```

When I import one of these functions in another file like so...

`import { isValidEmail } from 'utils';`

Flow throws a warning saying `This module only has a default export.`

Am I doing something wrong?

**Comment by TrySound** [comment]
Probably you wanted to import `./utils`, not `utils`?

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
