### ISSUE TITLE
Existential-based types union does not type hint in switch case

### ISSUE THREAD

**Issue by Skysplit** [facebook/flow#5305]
[Code snippet](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagKIA9kAnAQwGNkAlTZAV0IDsB9AHitoYBpQAxegLlAAKAHSjihAOYBnAcXqoA2gF0AlKAC8APlBs69bep3U9AbkQoM2fETKVjDZrwAqlg7gIlyuhiwBUXZ1czCyweWFgNUABvUEhwgSkiAEt6CVAAXxDsACFxSJiAI3EBAvDoTDkM81JYekTQJwBNAAUcRm4AeQ7IgHJOjp6zGrrkBpa27IBBCl6pikHq2vq42EnyJNrIwXRiVDhiABMBbnC1LSEYtCwBJtb2rq4dvdhDjJVg4fqiwjXkDfotk99kdQLlCGdtIJLpYbuNGHNHrtgW9gldsL9-hpEKBQAAfdw2Lz2ejMNGwSCxcIY2qabF4gmeOzsElkinfan6RYjUDITD1QyCWz-AQciHROlSeBJZCkAAWQiFtWEaLUUTpONIxCk2FubX6AjVOKNoEIxNAivowiBLwOZmNmWNmu1YzucwN6qNpuZ5vWSuthztRodRoOmEgxBo0GQ7uNOK9elixGg2sDOODmXSqL5yEEKw5UMpsAEPWgSXQUhoAFsem93ihs4J2b76AXvgJw8nsOkVHWgA)

In this snippet I'm extracting return from `fooAction` and `barAction` (this trick was found on flow issues page :)).
However, these types union isn't properly recognized in switch statements.
As you can see in snippet, only `TYPE_FOO` is properly type hinted, while `TYPE_BAR` receives `any` type.

If we explicitly define these types, everything works fine. [Working example](https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AFQJoAKAogPoBiA8paALygDkVlDA3CutnkWQEICCAJTqMBgtokRYAngAcApqHKxYIgN6gZCgFya582JG4kK1ADShZAQ2lwrAE10bIK3WgCuAWwBG8gE6gAL5BUvqgvFYB9Bpa8rqxhsZ8QhbWtrAOTqDekbrYfgCWaADmQSGhCkoq-MhYBegiABQusG5evn4AlHQAfFWwkrHhkTV1DfSNOX55WIUl3bR9EX6SqJg4LaP1aLrKsFvjoC29oI0x+roEJsypNnaOoM4qZYGd7Bzr2SO127rLB2gRFMTmc9DokqQxLd0plHl8AsFXu8hgCRHtQAAfYYrD5cLDyLgTKw-dC6AELPpqRCgUAYeAFLDIAAWp2JYzQADpYt0qTSacgrBhFFcyMwnNS+TS-PIsO4-IC2dsOWl7hyWuxJYEJfzBcKeJChOLJVKZXKFSTOSqMvYOVMNXytZL7PJIFZ3NAsEbjdLZfKjlZoEL7TTHSFAqwgA)

This doesn't seem to be an issue when types are split across the files

**Comment by SamChou19815** [comment]
Existential types are dead
