### ISSUE TITLE
Parameters fields of the same type parsed wrongly

### ISSUE THREAD

**Issue by happylynx** [facebook/flow#5307]
Code:

```
function f({a: string, b: string}) {}
```

reports:

```
4: function f({a: string, b: string}) {}
                             ^ Strict mode function may not have duplicate parameter names
```

However I believe it should be ok to have two parameter fields of the same type.

Demo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgA4Cc4BGMApgLapQCuAdgMYAuAlnNWFABQDeAhgFxgBnerkbUA5gBowBfkJHiAvgEownBekxg4Aawo0GzVmK60ptZavVA

Flow version: v0.59.0, master

**Comment by bradennapier** [comment]
Hey @happylynx you don't annotate an object like that.  You would do this instead:

> Note: Both of your example functions fail in that try example

```js
/* @flow */

// ok
function f({a, b}: { a: string, b: string }) {}

// ok
function g({c}: { c: string }) {}
```

### [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgA4Cc4BGMApgLapQCuAdgMYAuAlnNWFABQDeAhgDRgEAvgC4wnMN1EBnerkbUA5vwLTZ8hWEEBKMYPSYwcANYUaDZqwVdaIsWFqq5izTs56gA)

**Comment by happylynx** [comment]
Thanks @bradennapier!
