### ISSUE TITLE
React.Children functions have no type information since 0.55

### ISSUE THREAD

**Issue by fizker** [facebook/flow#5308]
In 0.54.1, the code below gave the error that `a` is the number 2 and not a string. But in 0.55 and forward, flow says no errors. 

```js
// @flow

import React from 'react'

const n:number = 2
React.Children.forEach(n, (a:string) => {})
React.Children.map(n, (a:string) => {})
```

Also, when running `flow suggest` on the file, it gives no suggestions for the types of the second parameters, which matches the behavior for the `any` type.

A workaround is to manually copy the type of the first parameter onto the second parameter, instead of having flow infer it

**Comment by SamChou19815** [comment]
Fixed a long time ago
