### ISSUE TITLE
Flow does not always infer t as type union of arguments in <t>(B<t>, B<t>) => B<t>

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#5309]
Here is a [example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAIlobACa4A8+AfKAN6Kig2U0AU6ADgFcMALgC2KAB5YqASmEBRHDlg4APvkQBfZJ2j4cJSALSEMKWGlCwA1qHpNuAN3zQBWYfjnkudRol36hsam5pYqdoyg3NBYkCLe1L4MADSgOCgA5gAW8RSJOPZeeTQFfgEGoM44oADKGOloGcIJJbQAzvXoGQzIlGgdHACMoAC8VjjcNtwARFko0zKpU2gC0NAyMsiIfQNUAEzsYyrcdQ0ZS9bcK2sbiEA) that illustrates odd behavior:

```js
// @flow

interface Decoder<a> {
  decode(input:mixed):Error|a
}

declare function ok <a> (value:a):Decoder<a>
declare function or <a> (left:Decoder<a>, right:Decoder<a>):Decoder<a>
declare var String:Decoder<string>

const d1 = or(ok("hi"), ok(null))


const d2  = or(String, ok(null))
```

In case of `d1` type is inferred as `Decoder<string|null>` as I would expect but in case of `d2` instead of inferring it `d2` as `Decoder<string|null>` flow errors pointing out that `ok(null)` is `Decoder<null>` rather than expected `Decoder<string>`.

**Comment by bradennapier** [comment]
@Gozala You can try this

#### [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAIlobACa4A8A1PgHygDeiooNlNAFOgAcArhgBcAWxQAPLFQCUogKI4csHAB98iAL7Ju0fDhKQhaQhhSw0oWAGtQtZqF4A3fNCFZR+BeR51mRH1DY1NzS2s1BydeaCxIMT9qAKYAGlAcFABzAAtEimScRyZfApoiwOCjUDccUABlDEy0LNEk8toAZyb0LKZkSjRurgBGUABeGxxeO14AIhyUObl02bQhaGg5OWREQeGqACZOSbVeRuas1dtedc3txCA)

```js
// @flow

interface Decoder<+a> {
  decode(input:mixed):Error|a
}

declare function ok <a> (value:a):Decoder<a>
declare function or <a> (left:Decoder<a>, right:Decoder<a>):Decoder<a>
declare var String:Decoder<string>

const d1 = or(ok("hi"), ok(null))


const d2  = or(String, ok(null))

```

**Comment by Gozala** [comment]
Thanks @bradennapier I can't really use `or` signature suggested in second example as this is how it's implemented:

```js
class Or <a> implements Decoder<a> {
  left:Decoder<a>
  right:Decoder<a>
  constructor(left:Decoder<a>, right:Decoder<a>) {
    this.left = left
    this.right = right
  }
  decode(input:mixed):Error|a {
    const left = this.left.decode(input)
    if (left instanceof Error) {
      return this.right.decode(input)
    } else {
      return left
    }
  }
}

const or = <a> (left:Decoder<a>, right:Decoder<a>):Decoder<a> =>
  new Or(left, right)
```

@bradennapier Can you please elaborate what's the co-variance in type parameters mean ? It does work but I'm not sure I understand why.

**Comment by Gozala** [comment]
Reading through the [type variance](https://flow.org/en/docs/lang/variance/) document and [property variance](https://flow.org/blog/2016/10/04/Property-Variance/) document I think I get a sense why covariance is used in type parameter - it accept subtypes of `a` in place of `Decoder<a>` and I guess that means that `Decoder<string>` and `Decoder<null>` both can be casted as `Decoder<string|null>` and there for things work they way they do.

That being said I'm still not sure why `d1` in the example is fine and `d2` isn't though.

**Comment by vkurchatkin** [comment]
@Gozala in the second example you are asking Flow to find such `a`, that `Decoder<string>` is a subtype of `Decoder<a>` and `Decoder<null>` is a subtype of `Decoder<a>`. This is only possible if `Decoder` is covariant.

**Comment by SamChou19815** [comment]
Making `a` covariant will fix the problem
