### ISSUE TITLE
Impossible to retrieve the argument types of functions?

### ISSUE THREAD

**Issue by tengyifei** [facebook/flow#5313]
```javascript
type ExtractReturn<F> = $Call<<T, R>(f: (x: T) => R) => R, F>
type ExtractInput<F> = $Call<<T, R>(f: (x: T) => R) => T, F>

let f = (x: string) => 5;

// This should not typecheck but no error from Flow
let b: ExtractInput<typeof f> = 10;

// this should typecheck
let c: ExtractInput<typeof f> = 'asdf';

// $ExpectError
let d: ExtractReturn<typeof f> = '5';
```

The only difference between line 1 and 2 is replacing `R` with `T`. Unfortunately, Flow cannot determine that `ExtractInput<typeof f>` is a `string`. :(

https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwB4AxAPigF4oASAYWQBsHDCAVAGig1IAoAzAFxQecIawCUlchkkVpnMgChQkWAhToAkvjA5gJclTqNmbTt35CRY2dNtQOUJYobYofSsNFQAzkgCW+ADm9gCsANyKigD00Q4AFv4+vvEA9jgMACZQ+KnAUCoQqPFFANZQAEZ6OalQEIiIqYjujQC2TgypAO4ubhVC8EhowNq6+oWpHnyGUACMAAyRMXHAick+aRnZhcVlvfmoA+rDo3qEE1MzAOTIPpl8V0uxNPCQ6DANTftQmUdD6FhcARzuAIJN3NdQo8gA

**Comment by SamChou19815** [comment]
`Parameters<...>` now exists
