### ISSUE TITLE
Strange flow-cli behavior with errors appearing and disappearing

### ISSUE THREAD

**Issue by jsonnull** [facebook/flow#5316]
I'm running into a very frustrating issue where Flow sometimes reports errors and sometimes does not. I'm utterly baffled and I would love help identifying the cause of the issue.

Here's the process I'm currently using to find this behavior:

1. Run `flow`, to start the flow server and get a status check
  _Result:_ no errors
2. Run `flow check` to sanity check the server results
  _Result:_ no errors
3. Make an edit which introduces an obvious Flow error, run `flow`
  _Result:_ 24 errors
4. Run `flow check` with obvious error
  _Result:_ 0 errors 🤔 
4. Make an edit which undoes the obvious Flow error, run `flow`
  _Result:_ 23 errors 🤔 
5. Run `flow check`
  _Result:_ 0 errors
6. Run `flow stop`, then `flow`
  _Result:_ 0 errors 🤔 

Here's what it looks like to me...
1. Spawning a flow server reports errors correctly until an error is introduced
   1.1 If the error is introduced, a bunch of "ghost errors" appear out of nowhere
   1.2 Fixing the error still leaves the ghost errors
   1.3 Restarting the server makes the ghost errors go away
2. Throughout this whole process, `flow check` is failing to type-check code at all

**Comment by jsonnull** [comment]
I put together a gif of the issue to demonstrate:

![gif](https://jsonnull.com/flowerror.gif)

**Comment by bradennapier** [comment]
@jsonnull in your .flowconfig are you using the `module_dirname` feature?  That will break your errors as described.

**Comment by jsonnull** [comment]
@bradennapier 

I am using `module.system.node.resolve_dirname`

```[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src```

Will that break them as you're suggesting? Is there anywhere I can read more on this issue?

**Comment by jsonnull** [comment]
Did some looking myself and it appears I am indeed running into the issue @bradennapier described.

There's current ongoing discussion at: https://github.com/facebook/flow/issues/5180

**Comment by SamChou19815** [comment]
not enough info to repro
