### ISSUE TITLE
this has wrong type in static methods

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#5317]
**Note**: In the body of a static method, the value of `this` is the class itself, not an instance of the class ([source](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes/static)).  But the type Flow chooses for `this` in a static method is an instance of the class:

[Try flow link](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwLIHtQXgbwCh55kAXKUgSzBLAAsQBbKACgDspGQAuE0mSmwDmASl6k6lZAG4ifCtUSYArm1LtOPPgOFj4UNgE9ZAXwIEkqeAFVkIGPBAAPUiDbA0WHPnhmCt+wA6ZHomVgByADNMTHCRQLAVNRZwhggIWJECIA)

```js
declare class Model {
  static schema(name: string): this;
  static count(name: string): any;
}

class User extends Model { }

User.schema('foo').count('hello')
```

### Expected behavior
`typeof User.schema('foo')` is `typeof User`

### Actual behavior
`typeof User.schema('foo')` is `User`

**Comment by popham** [comment]
Whoopsie. Your `this` return type should be a `Class<this>`.

**Comment by jedwards1211** [comment]
@popham are you sure?  In the body of a static method, the value of `this` is the class itself, not an instance of the class, so shouldn't Flow adopt the same behavior?

**Comment by popham** [comment]
Yes I'm sure. Accepting your suggested change, how would I annotate a static method that returns an instance of its class?

**Comment by jedwards1211** [comment]
@popham that's true, I see what you mean.  Though for returning the class itself, `Class<this>` is not exactly the same as `typeof this` is it?
