### ISSUE TITLE
Dead parser code

### ISSUE THREAD

**Issue by popham** [facebook/flow#5318]
Judging by [object_parser#L428-L431](https://github.com/facebook/flow/blob/831243fa6bf8a403f154208765a482b58cf88a87/src/parser/object_parser.ml#L428-L431) and [test/flow/private_class_properties/constructor.js#L9-L15](https://github.com/facebook/flow/blob/831243fa6bf8a403f154208765a482b58cf88a87/src/parser/test/flow/private_class_properties/constructor.js#L9-L15), I suspect that private constructor properties are supposed to be forbidden. Unfortunately the `String.equal name "#constructor"` predicate always fails. Should that `"#constructor"` be `"constructor"`? Or should that case be removed? Else?

**Comment by popham** [comment]
FYI, the error for static constructor properties is missing its "static" modifier. See [object_parser.ml#L422-L425](https://github.com/facebook/flow/blob/831243fa6bf8a403f154208765a482b58cf88a87/src/parser/object_parser.ml#L422-L425), [test/flow/class_method_kinds/multiple_constructors.js#L7](https://github.com/facebook/flow/blob/831243fa6bf8a403f154208765a482b58cf88a87/src/parser/test/flow/class_method_kinds/multiple_constructors.js#L7), and [test/flow/class_method_kinds/multiple_constructors.tree.json#L7-L10](https://github.com/facebook/flow/blob/831243fa6bf8a403f154208765a482b58cf88a87/src/parser/test/flow/class_method_kinds/multiple_constructors.tree.json#L7-L10). The error should read "Classes may not have static fields named `constructor`."

**Comment by mroch** [comment]
fixed in https://github.com/facebook/flow/commit/9f106b8733c1f0416866890f0ed9458d9dba9fe4
