### ISSUE TITLE
Why doesnt flow tell me that something is null

### ISSUE THREAD

**Issue by hgenners** [facebook/flow#532]
var something = null;
var x = something.get("key");

It does not warn about the above. Is there any javascript static analyzer that would ?

**Comment by jeffmo** [comment]
Hmm, I'm getting an error when I try this: https://gist.github.com/jeffmo/434e5413a81fc880f5a7

Maybe you forgot to opt-in to flow with the `/* @flow */` header?

**Comment by jeffmo** [comment]
Closing this out, but feel free to re-open if you're still having issues.
