### ISSUE TITLE
Maybe union type ordering error

### ISSUE THREAD

**Issue by deanbrophy** [facebook/flow#5320]
**Expected Result**
Maybe union types can be specified in any order:
`?(Array<T> | T)`
`?(T | Array<T>)`

**Actual Result**
The ordering does matter. [Specifying the array first](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo4AnAUQENcALAQV10wFtMYb8BTAEwA8AFQB8AClRgwNChQBcYAPxjGsmgE9hIsAB8wQgJQAaSWFwAjBWJ4webBYbABebQDc4hPiakBnXHAAHHgVFGmx1EwMwAG9TQigwFTV1ADpCH1UKDTEZCgMo2KkpXJTyajp6MQsjMD9AngMAblMAXzAbHx4weMTcgtMpCxTcGhgYMTqgmr7mqRbUedR8dSCwAHV6bh5XHgpnGNMAZXxMKCgFbHZzXYX0VxkwNnUAGXT8ELENrZ29vUyNARfXg-ERRJxgS5jZoYHAEYikPhwY6nKBiAyFACQZVoDGYrA4XF4fDET1ePnwNURQno6SatxheCIJDAVJpPgmcDYPHwNOwAHMFEDtrt0aZbkA) works correctly. [While including the generic first](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo4AnAUQENcALAQV10wFtMYb8BTAEwA8AFQB8AClRgwNChQBcYAPxihYAD5hGsmgE9hIgJQAaSWFwAjBWJ4webBUINgAvCLAA3OIT4mpAZ1w4AAceBUUabB0TJwBvU0IoMDEtCl0AOkI-FN0xGQoDWNMpPLTyajp6MQsjMADgngMAblMAXzAbPx4wBKS8wqkpCzTcGhgYMTqQmr7mqRbUedR8HRCwAHV6bh53HgoXMDipAGV8TCgoBWx2c12F9HcZMDYdABlM-DCxDa2dvY1svTfXi-Qz7K5jZoYHAEYikPhwE5nKBiAyHACQZVoDGYrA4XF4fDEzzefnwNXhQnomSadyheCIJDAFKpfgmcDYPHwVOwAHMFEDtrtUaY7kA) causes an error.

I first noticed this error in React using flow version 0.53.1, but the examples provided above are for v0.59.0

**Comment by bradennapier** [comment]
Hey @deanbrophy this is because `T` could be an array so `T` in this case matches everything while `Array<T>` only matches arrays of `T`.  

Therefore you always want to order your types from most specific to least so it doesn't match an unwanted type.

**Comment by deanbrophy** [comment]
@bradennapier Excellent! That makes sense. I'm wondering if the error message could be more specific, though, or is this something that's explicit in the documentation?

**Comment by bradennapier** [comment]
Actually upon reading this error it is actually different from what I assumed:

```
forEachAccumulated(myList, doThis);
                           ^ function. This type is incompatible with the expected param type of
                           cb: (elem: T) => void,
                                 ^ function type
                                 This parameter is incompatible:
forEachAccumulated(myList, doThis);
                    ^ array type. This type is incompatible with
                      function doThis(something: Whatever){
                                      ^ object type
```

Basically it is saying that it is epxecting the `Whatever` object but instead it is receiving `?(Whatever | Array<Whatever>)`

Indicating that we will be passing a non-array type in the annotation seems to fix this.

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAkAcnAHYCCATlQIZYAquBAvGADwMB8AFNXVk5cwAHzAMAlGBbCGAblRglYVFACuZAMYYAluTBQ4VAKK1NACwqbNagLZqYtDHgAmQnorC0aALjAB+HgZRMH56IQkAGk9NACM-HjwYPFs-QgBhWhgYdhJyMMZmSPEuKRkwADc4HRdopQBnTTh8P39aMixoqQBvTx0oMD4aegA6HXqCnm8qCR7PJWmRwxMzcx444sbmvAkFJQBfMCT6gn7B6bnlMDiRzSyYHi38You9sH3UD8xmMAB1cyceAqeCo0jAvSUAGUMGooFA-GQ7LEQZ90BVvGBbFgADLjDCtHj-QHA0FiArsInOEmlMGI7IKVQabR6MhgFxwaGwqA8CQQgCQy1MFisNnsjmcLh4WNx9QwxXZDHM412qMZWl0+gVSvqjzgtjwGCVZAA5n5KUCQbzPKigA)

**Comment by deanbrophy** [comment]
Right on! I think it's safe to close out this issue then. 

Man, I need to get caught up on utility types, but they're not very well documented. I had no idea $Call existed.

**Comment by bradennapier** [comment]
@deanbrophy you can take a look at our pubchan package.  It has some useful utility types for composing your types: https://github.com/Dash-OS/pubchan/blob/master/src/pubchan/types/utils.js

**Comment by deanbrophy** [comment]
Right on. I wish the built-in Flow utility types were better documented. It looks like things like $Call have no documentation whatsoever.
