### ISSUE TITLE
Loop Protection Required?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5323]
The following doesn't work but it should as it is valid to do something like this.  In my case the callback function calls itself with a reference to itself  as the "ref" is used within WeakSets, etc to validate various pieces.

Just spent at least 3 hours with zero idea why my files were not typing properly... no errors or warnings.. just mutated everything to any on me and i had to take it apart literally argument by argument and reprogram it 3 times just to figure out this was being done... 

#### [Try Flow](https://flow.org/try/#0FAFwngDgpgBAYgOxgXhgCgE5QGYC4YDyARgFYAqkUAlCgHwwBuA9gJYAmA3MKJYaRdBQwA3sBgwseeAmABfbgGMmCAM4gYZKGvzFyvVKPGT8mHDv6UayesPnyOMAPSORx9G4CGCMFfrN2skA)

```js

type Fn = (ref: ObjType) => void;

type ObjType = {
  ref: Fn
}

const Test: ObjType = {
  ref: (ref: ObjType) => {}
}
; // {ref: (ref: any) => void}
```

**Comment by vkurchatkin** [comment]
Seems to typecheck as expected

**Comment by bradennapier** [comment]
It is not covered.  It changes `ObjType` to `any` so the arguments are no longer typed.

**Comment by bradennapier** [comment]
I did fin that interfaces do not appear to have the same problem.  Would this not indicate a bug ?  Would be nice to have mor especifics on the exact differences of interfaces and types since they appear to handle a few different areas very differently.

```js

type Fn = (ref: ObjType) => void;
type Fn2 = (ref: ObjType2) => void;

interface ObjType {
  ref: Fn
}

type ObjType2 = {
  ref: Fn2
}

const Test: ObjType = {
  ref: (ref: ObjType) => {}
}
; // {ref: (ref: ObjType) => void}

const Test2: ObjType2 = {
  ref: (ref: ObjType2) => {}
}; // {ref: (ref: any) => void}
```

**Comment by vkurchatkin** [comment]
Can you provide an example that should be an error, but isn't?

**Comment by noppa** [comment]
Sounds like a problem in your editor / whatever is reporting these types.  
Flow type checks calls to `Test.ref` correctly in [this example](https://flow.org/try/#0C4TwDgpgBAYgdlAvFAFAJwgMwFxQPIBGAVgCrgQCUSAfFAG4D2AlgCYDcAUB6JPsWb2QBvDlCgYcsOBwC+XAMYM4AZ2BQSEVbkKlySKCLETc6LNv7kqiWkLkzOHDaoB0ElE+AU2UAPQ+oAOoMaADWygA0UACGylAQAB6Q8sAQLI6awK5YKELi2cZ8upAUuTJQMl6+-kGhEdGxCUkpaRw+AFTpLm4ALABMlX6wUUwANnUxcYkQyamdmW65bgVwAK4AtgQQaFSl5ZVVQ6PjDVMzaW0+QA).

**Comment by jcready** [comment]
This is a bug in flow's type-at-pos which reports recursive types as `any`. See #4358. The minimal test case is:

```js
type T = { t: T };
const t = {};
t.t = t;
(t: T);
```

The result of `type-at-pos index.js 4 2` is `{t: any}`
