### ISSUE TITLE
What's difference between Flow and JSDoc in WebStorm ?

### ISSUE THREAD

**Issue by noelebrun** [facebook/flow#5329]
Hello,
I'm trying to understand the difference between Flow and JSDoc in a complete IDE like WebStrom? When you are creating your JSDoc with the parameters and type, WebStorm will tell you if your type aren't correct. (Except for the syntax indeed)
You can use @typedef to define your interfaces and the big pros is that you don't have to add anything in your process with JSDoc.
I'm sure there's a lot of good pros for Flow but I don't know Flow well enough to find them :/
Thanks!
Noé

**Comment by lll000111** [comment]
One thing is a documentation tool and the other one is a static type checker.
