### ISSUE TITLE
Q: Disjoint Union 

### ISSUE THREAD

**Issue by stevemolitor** [facebook/flow#5330]
How do I type the function type of an object whose values are functions that take a disjoint union type as their parameter? For example:

```js
// @flow

type Person = {
  type: 'person',
  name: string,
};

type Android = {
  type: 'android',
  manufacturer: string,
};

type Data = Person | Android;

const ToStringFuncs: { [*]: Function } = {
  person: ({ name }: Person) => name,
  android: ({ manufacturer }) => manufacturer,
};

const toString = (data: Data) => ToStringFuncs[data.type](data);

// no errors:
toString({ type: 'person', name: 'bob' });
```

How do I replace `Function` above with something more specific? If I try this:

```js
const ToStringFuncs: { [*]: (data: Data) => string } = {
```

I get `Property not found` errors for `name`, `manufacturer`, and errors like this: `Expected string literal 'android', got 'person' instead`.

Is this possible with flow? Am I going about it the wrong way? Thanks!

**Comment by jcready** [comment]
Change your toString function to this:

```js
const toString = (data: Data) => data.type === 'person'
  ? ToStringFuncs[data.type](data)
  : ToStringFuncs[data.type](data);
```

Flow needs you to make the pointless refinement first.

**Comment by stevemolitor** [comment]
Thanks. Is there a way around the pointless refinement? I tried that already, and it works, but the example is artificial; in my real code there are lots more functions in the object map, so refining each one isn't super practical.

Here's a slightly more realistic example:

```js
// @flow

type Person = {
  type: 'person',
  name: string,
};

type Android = {
  type: 'android',
  manufacturer: string,
};

type Animal = {
  type: 'animal',
  collarNum: string,
};

type Data = Person | Android | Animal;

const ToStringFuncs: { [*]: (params: any) => string } = {
  person: ({ name }) => name,
  android: ({ manufacturer }) => manufacturer,
  animal: ({ collarNum }) => collarNum,
};
                        
const toString = (data: Data) => ToStringFuncs[data.type](data);
                        
// no errors:
toString({ type: 'animal', collarNum: 'bob' });
```

I'd like to get rid of the `any` in the declaration of the `ToStringFuncs` value type, but putting in `Data` doesn't work.

**Comment by jcready** [comment]
Unfortunately I haven't figured out a way around it. There's almost no point to the `ToStringFuncs` object and you are probably better off with a switch:

```js
const toString = (d: Data) => {
  switch (d.type) {
    case 'person': return d.name
    case 'android': return d.manufacturer
    case 'animal': return d.collarNum
    default: throw new Error(`Flow doesn't understand exhaustive checks`)
  }
}
```

**Comment by SamChou19815** [comment]
Closing since * are no longer supported
