### ISSUE TITLE
Function taking object with maybe property errors when taking object with assured property

### ISSUE THREAD

**Issue by ryanscottaudio** [facebook/flow#5331]
code:
type ObjectType = {
	test: string,
};

type MaybeObjectType = {
	test?: string,
};

function test (input: MaybeObjectType) {};

const foo: ObjectType = { test: 'test', };

test(foo);

error:
13: test(foo);
         ^ object type. This type is incompatible with the expected param type of
9: function test (input: MaybeObjectType) {};
                         ^ object type
Property `test` is incompatible:
6: 	test?: string,
           ^ undefined. This type is incompatible with
2: 	test: string,
          ^ string

example:
https://flow.org/try/#0C4TwDgpgBA8gRgKwgY2AFXNAvFA3gKAEhgIBnYALinICcBLAOwHMAafAXwG599RIoAsgEMQcCPCSoM-HAWJlgAfiq1GrDt3wAzAK4NUdAPYMoJclAAUjMDsqCRYiSnSYAlHi49kx81sOGqJylMKFlTBSoAcjNgSJYoT14FCz9DV04gA

**Comment by bradennapier** [comment]
The exact part is not strictly required, but I recommend it.

#### [Try Flow](https://flow.org/try/#0C4TwDgpgBA8gRgKwgY2AFXNAvFA3gHwCgBIYCAZ2AC4pKAnASwDsBzAGkPwF8BuQw0JCgBZAIYg4EeElQYhOACQBlABajIAHmkp0mAHx9CAMwCuTVAwD2TKGUpQAFMzAnqI8ZO2zMASjy9+ZGt7I0tLGi9deTxbCjcAcjtgeLYoAIE4h1DLHx4gA)

```js
type ObjectType = {|
	test: string,
|};

type MaybeObjectType = $Shape<ObjectType>;

function test (input: MaybeObjectType) {};

const foo: ObjectType = { test: 'test', };

test(foo);
```

**Comment by SamChou19815** [comment]
To make it pass, properties need to have +
