### ISSUE TITLE
Optional properties in an object used as bounds for a generic are treated as non-optional

### ISSUE THREAD

**Issue by btford** [facebook/flow#5334]
Code:

```
type Props = {
  onClick?: () => mixed
};

type Component<SomeProps: Props> = SomeProps;

type MyComponent = Component<{
  otherProp: string
}>

let y: MyComponent = {
  otherProp: 'hey'
};
```

Error:

```
7: type MyComponent = Component<{
                                ^ object type. This type is incompatible with
5: type Component<SomeProps: Props> = SomeProps;
                             ^ object type
Property `onClick` is incompatible:
5: type Component<SomeProps: Props> = SomeProps;
                             ^ property `onClick`. Property not found in
7: type MyComponent = Component<{                                ^ object type
```

I'd expect this not to error, because `onClick` is optional. I've tried using `$Shape`, `$Subtype`, and `$Supertype` on `Props` as well to no avail. My goal is to have `otherProp` be allowed, and `onClick` only error when it doesn't return a value.

The issue is present on both `v0.59` and `master`.

https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbwFBSggOwGEAbASwGMBrAfgC4oAKASnQD4oBbMgDwgBNsAX2zZQkKEQScwhCAWAAeAMrSI8JMgYaUHDKs7rEKANyjx0ALIgpMuQvSTpsgvKU48CYAAsIcHQzIwHBkBADmwmyiJBDAUCAM1rYubo4e+D5+AVAA5L4gOcJmQA

**Comment by goodmind** [comment]
This is not a bug, consider this

```js
type Props = {
  foo: number,
  +onClick?: () => mixed
}

type Component<SomeProps: Props> = SomeProps;

const ref: {foo: number} = {foo: 11, onClick: 230239230}
type MyComponent = Component<typeof ref> // error, onClick can be any type
const y: MyComponent = {foo: 11, onClick: 230239230};


const ref2: {|foo: number|} = {foo: 11}
type MyComponent2 = Component<typeof ref2>
const y2: MyComponent2 = {foo: 11};
```

https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbwFBSgMwQQC4oA7AVwFsAjCOAGlygGoEyBhAGwEsBjANYB+UgAoAlOgB8UKjwAeEACbYAvtmyhIUDgiph2EMsAA8AZT0R4SZKWsoZGC1SuIUAbg192yYFDgQ+KSYhCTk1HRwquhYoaQAjPEMUOzc-AKkAEwAzAAMOQCcObnqWtAAsiC6+obGMdUGZEamZQj4-oEyAPRdUPSIjCmcvIJQfACGZFB0UJMgUGXY3mS+UCCklQ21fhghRAlJQ2mCWXmFxaqeXj5+AfiZwQA+ceG09I-Ruy+JpeAVVXpGs1MvVAdsTK12ndMlIljc1g8oJswU1jCCvvsoD93EA

**Comment by villesau** [comment]
@goodmind why onClick needs to be readonly in the latest example to work?

**Comment by Bannerets** [comment]
@villesau `string` isn't a subtype of `void | string` in an invariant position.

Same as here:
```js
class C<T> {}
;(new C<string> : C<string | void>) // error
```

**Comment by villesau** [comment]
doh, true. So in other words if it wouldn't be write-only, the property could be written later on and it would not match `{|
  otherProp: string
|}` anymore.
