### ISSUE TITLE
Multiple type parameters in async arrow function

### ISSUE THREAD

**Issue by nicolo-ribaudo** [facebook/flow#5335]
https://flow.org/try/#0IYZwngdgxgBAPAFQDQwKoD4AUAzCAuGTAfgQEoYBedNUg1S63TUoA

```js
async <T, U>(fn: (?T) => U): U => fn()
```

I think that this is valid code, but flow throws `Unexpected token :` (and, if I remove the return type annotation, `Unexpected token =>`). It works with non-async functions (`<T, U>(fn: (?T) => U): U => fn()`).

**Comment by PavelVanecek** [comment]
I think I found a similar case:
https://flow.org/try/#0JYOwLgpgTgZghgYwgAgEoQCYFcAeBBBMYAexGQG8AoZG5AajAE8AHCALmQBIBlLAIyasAPAGcwUUAHMAfAG5KAX0qUEpMclIoAvMiF4O6bPkIkQ0gBRwokkRzwBtALoBKDgAUoxALbAREPdLIWtKUAJAe3r4QAHRQECLEADYAbhCW1iL2AAwuyqog6mAA7sRByHAijCAIuvpomLgERKQWVjZ2Tq7IET5+AUEhoW2ZOZRAA

```
// perfectly fine
const one = <A: B>(args: A[]): Promise<A> =>
```

```
// unexpected token
const two = async <A: B>(args: A[]): Promise<A> =>
```

**Comment by SamChou19815** [comment]
This is supported now
