### ISSUE TITLE
Flow treats properties of `empty` type as `any` type

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#5336]
Here is an [example illustrating this issue](https://flow.org/try/#0C4TwDgpgBAKghgcwDwGsCWA7AJgGiluYOAPigF4oBvAKCiiIQC51sBuWqANzgBsBXCIwJF2AX2rUsEAMY84AJ2jd5UALaN4yAEQYA9rrBa8EVWFDFqqgHTd+EK8F0BVMJHkBhOAGcIACgCUQA):

```js
type Tag<kind, data> = {
  tag:kind;
  value:data;
}

declare var m:Tag<"noop", empty>
m.value.toUpperCase()
```

I would expect flow to report error when calling method, stringifying or doing anything really to `m.value` but instead flow reports no issues and in fact treats `m.value` as `any`.

**Comment by jcready** [comment]
It seems like the `empty` type is just defined as the type which cannot be inhabited. It's in a similar vein to `any` or `mixed`.

Type | Can Inhabit | Can Be Inhabited By
----:|:-----------:|:-------------------:
`any` | `{ALL TYPES}` | `{ALL TYPES}`
`mixed` | `∅` | `{ALL TYPES}`
`empty` | `{ALL TYPES}` | `∅`
N/A | `∅` | `∅`

I do agree that `empty` should probably belong on that bottom row instead, but in practice It's not possible to have a javascript value which inhabits your type.

**Comment by vkurchatkin** [comment]
Closing, this is exactly how it is supposed to work.
