### ISSUE TITLE
[Proposal] reduce variable type in if-else/switch blocks

### ISSUE THREAD

**Issue by XaveScor** [facebook/flow#5337]
https://flow.org/try/#0PTACDMBsHsHcCh4BMCmBjSBDATigBOAK4B2aALgJbTF4UDOAymdhcQOYAUmAXHnc6zYBKXs0Ipk6LLgIlyVGvSYt2XXsUIBbAEYpsIgpkh0JkjDnwA3HHh58B7PAB88GnXsQVweDkoedMISE8AG94PB87fhVheABfPBRjfDCItVctXX14oA

flow can't recognize true type of `a` in if blocks. Because of we can't create `isString`, `isBoolean`, etc functions.
I found `Array.isArray` implementation: https://github.com/facebook/flow/blob/85b6120f7373f3906cda8057cb63742c5586effb/src/typing/statement.ml#L4263
We can rewrite her:
```
isArray(a: Array<any>): true;
isArray(a: *): false
```

**Comment by apsavin** [comment]
> Because of we can't create isString, isBoolean, etc functions.

we [can](https://flow.org/try/#0PTACDMBsHsHcCh7gK4DsDGAXAltVACbAZwGVMAnbVAcwAoBDALnwFtsAPAUwBMBKZgEbRokTvQIBSdAAtO6ANZF8Ab3j585TpmTkCmAJ4AHTtHD56+ALzX8AciIUq1WwG54AX0Tc5kepvwAbn7mzA6UNPgAPvioyCwCnOSI2Ga0xGThdPS8vCpq+AyhjjS8HvickESceeqFMXEJ5KXuQA)

**Comment by XaveScor** [comment]
How to create typing to external lib?

**Comment by TrySound** [comment]
https://flow.org/try/#0PTACDMBsHsHcCh4BMCmBjSBDATigBOAK4B2aALgJbTF4UDOAymdhcQOYAUmAXHgLYUAHiiQBKXgCNo0SCkw0ApGgAW6ANZ08HMgE8ADimjg8mPAF4LeAOR1mrNldEBuRKgw58ANxwnetlux4AD54xIR8EijYiBTGHPRMAZyYoqJ4AN7weFo8eP72ovAAvngokHT4mdlcvGERUYVFQA

**Comment by XaveScor** [comment]
Thanks, but I can't do something common:
https://flow.org/try/#0PTACDMBsHsHcCh4BMCmBjSBDATigBOAK4B2aALgJbTF4UDOAggBSYBceD22mAngDzFCAWwBGKbAD4AlOxHRokFJhoBSNAAt0Aazp4mZbIRRSA3MnRZcBEuSo16zNhy68+dAxWIBzabPmLlPDVNNB09cExIOmMzcwwcfAA3HDwnTm5+QVFxCTwAH2cMtw9vCUQKcD0HFikpPABveDw9NJdM4TFJKXgAXzwUKPxG5pZ2dNd3bE8fbp6gA

**Comment by TrySound** [comment]
No

**Comment by SamChou19815** [comment]
It should be done via type guard instead of this overload
