### ISSUE TITLE
[Bug] flow cannot get true type with destruction

### ISSUE THREAD

**Issue by XaveScor** [facebook/flow#5338]
test case:

https://flow.org/try/#0PTACDMBsHsHcCh4BMCmBjSBDATigBAG454AeAXHgN6YUDOALtgJYB2A5gL54A+VNeLAK4BbAEYpsHeGmgsGecNGh4AvHgAU1DhXoBPAA4po4UgEpVAPirwAkOv4Nm7HgJHjsp+BwDcQA

**Comment by etruska** [comment]
Here's perhaps a little more expressive example of what I think is the same bug:
[test case](https://flow.org/try/#0C4TwDgpgBACghgJzgWwCrmgXigOwK7IBGECUAPlAM7AICWOA5gFCiSwID2Yl6b2A3lDCIUALlwFipCtTqMoAXyZMAxhxzUoAMzw4VUbAAphSZFHHxTvLFAAsAJigBKAwD4JAGw8BuVes06eo5GgiYoBnaOCubsXDwYzm6ePkA)

**Comment by SamChou19815** [comment]
this now works
