### ISSUE TITLE
Using an array as the initial value for Array.reduce leads to incompatible expected param type error

### ISSUE THREAD

**Issue by daniel-wer** [facebook/flow#5339]
https://flow.org/try/#0GYVwdgxgLglg9mABAQwBTIE4YFyIIJbICeAPGCALYBGAphgHwCUuBGxZltDiA3gFCJEEBAGcoKLACZEAXgkYAdBWQAHVMpUAVOACE4cADaMA3AMQYaUEBiSYMkhRYAmICDVRnBqCyJAGoLISk5NR0TLL0vJ6C5jS+-goqICIAFqgAjCbRghZWNrHxUKYxiAC+ADTRANoAupWCjHylfHygkLAIiBraeoaozIhU+gY0yEj8OZbWSMDIBiI0pqVAA

This code fails

```javascript
function a(arr: Array<number>): Array<number> {
  const arr2 = arr.map(mapToBool);
  return arr2.reduce(
    (result: Array<number>) => {
      result.push(1);
      return result;
    },
    [],
  )
}

function mapToBool(): boolean {
  return false;
}
```

with the following error

```
4:     (result: Array<number>) => {       ^ function. This type is incompatible with the expected param type of
[LIB] static/v0.59.0/flowlib/core.js:251:       callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: Array<T>) => T,
                                                            ^ function type
This parameter is incompatible:
12: function mapToBool(): boolean {
                                       ^ boolean. This type is incompatible with
4:     (result: Array<number>) => {
                ^ array type
```

Looking at core.js it seems like Flow is selecting the wrong reduce case:
```javascript
reduce(
      callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: $ReadOnlyArray<T>) => T,
      initialValue: void
    ): T;
```
instead of
```javascript
reduce<U>(
      callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: $ReadOnlyArray<T>) => U,
      initialValue: U
    ): U;
```

Interestingly I noticed that replacing line 2 of my initial example with a static assignment `const arr2 = [true, false]` gets rid of the error, so the bug seems to somehow be triggered by that `arr.map` call.

**Comment by jcready** [comment]
Just remove the annotation from the 4th line:

```js
(result) => {
```

**Comment by daniel-wer** [comment]
Thanks, that'll work until the bug is fixed :)

**Comment by XaveScor** [comment]
I think its better. https://flow.org/try/#0GYVwdgxgLglg9mABAQwBTIE4YFyIIJbICeAPGCALYBGAphgHwCUiA3gFCKIQIDOUKWAEyIAvAIwA6CsgAOqaTIAqcAEJw4AG0YBuDl178YYGFGwEMxMpVoNRiANoBdPRhpQQGJJgyCJrgCYgEDSoepyuPCAa-CL0rGGciBFRUBIyIDwAFqgAjDoJ4W4eSMnRuomIAL4ANAlGJrWcjGyVbGygkLAIiArKapqojLhU6ho0yEjshe6eiMDIGjw0upVAA

**Comment by goodmind** [comment]
Fixed in https://github.com/facebook/flow/commit/9edb45d7955f514fd4110cb9a035a3637bf28f43
