### ISSUE TITLE
Unions are not exclusive (OR, not XOR)?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5344]
[I found this as a TypeScript issue on StackOverflow](https://stackoverflow.com/questions/47315346/provide-one-of-object-types-in-typescript) and tried the same code with Flow, the problem is the same.

```js
interface A {
    x: number
}
interface B {
    y: number
}

type Z = A | B;

// here it allows me to create a variable of type Z with both members of type A and B.
let z: Z = {
    x: 6,
    y: 6
}
```

[Demo](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgILIN4Chm+QDwC5kQBXAWwCNosBfLUSWRFAIUxzwE9iyqb6WMFwAOKAFrIAvGmQAfZKwDcWLAHo1yABbQUwMMjgAbIwHsA7gGdk5FGFPIEUCHEiHkANzhRgcSkZRTGGRhMWRJc30tZEpTMGjbfihrIJDRFHQ4EAATRQA6LACDAC9iSRlsPAJiADYAGk5cHmQauiwgA)

**Comment by lll000111** [comment]
well I guess that works as designed

**Comment by jcready** [comment]
Properties are allowed to exist on the objects inhabiting an interface which don't exist in an interface. You would have to use exact object types if you wanted an flow to complain about `z` or define the exclusive keys as `empty` in the other interfaces:

```js
interface A {
    x: number,
    y?: empty
}
interface B {
    x?: empty,
    y: number
}
```

Or

```js
type A = {|
    x: number
|}
type B = {|
    y: number
|}
```
