### ISSUE TITLE
Support boolean in ES6 object spread.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#5347]
A simple expression like [this one](https://flow.org/try/#0MYewdgzgLgBAJiAphAciKB1EAnA1jAXhgG8YA6CgMwEMAbCRGAMiZOoC4YBGAXxh4BQoSLATIseQiXIUo2AK6MWbTr35A) is not supported:

```js
const doesNotWork = { ...false && {a: 1} }
const doesWork = { ...true && {a: 1} }
```

I find it useful to use that syntax to conditionally add properties in a concise way.

**Comment by TrySound** [comment]
@AndrewSouthpaw According human logic boolean can't be really spread even if engine is support such feature. Use ternary with empty object literal to solve your problem
https://flow.org/try/#0MYewdgzgLgBAJiAphAciKB1EAnA1jAXhgG8YA6CgMwEMAbCRGAfhOoC4YBGAXxg+N7cAUKEiwEyLHkIlyFKNgCujAGQrWHHjG5A

**Comment by AndrewSouthpaw** [comment]
Thanks for the input, that is what I chose to do as well, it's just slightly less concise. Oh well.
