### ISSUE TITLE
Question: does flow allow unsound assignments?

### ISSUE THREAD

**Issue by aleksey-bykov** [facebook/flow#535]
There some unsound situations in TypeScript that are allowed in order to support some common usage scenarios, particularly function argument bivariance when a signature of a function is checked for being assignable to another signature: http://www.typescriptlang.org/handbook

> Function Argument Bivariance  
When comparing the types of function parameters, assignment succeeds if either the source parameter is assignable to the target parameter, or vice versa. This is unsound because a caller might end up being given a function that takes a more specialized type, but invokes the function with a less specialized type. In practice, this sort of error is rare, and allowing this enables many common JavaScript patterns.

Where does Flow stand on this?

**Comment by avikchaudhuri** [comment]
Flow tries to be sound unless it can't really help it (which sometimes happens when faced with hard precision vs. soundness issues, mostly around reflective stuff). In particular Flow doesn't support argument bivariance, only contravariance.
