### ISSUE TITLE
No constraint in Array of tuples of classes with same interface

### ISSUE THREAD

**Issue by zerkalica** [facebook/flow#5351]
For dependency injection I need to describe mapping of original class to another with same interface. 

Something like this ``` [Class<V>, Class<$Subtype<V>>] ```. But how to apply this constraint to array of this tuples?

For single tuple of classes all works fine:

```js
class A {
    f() {}
}
class B {
}

type Rec<V> = [Class<V>, Class<$Subtype<V>>]
// $ExpectError
const v: Rec<A> = [A, B] // This type is incompatible with A
```

But not works for Array of Rec:

```js
// Wrong - no errors
const va: Rec<*>[] = [
    [A, B]
]
```

A similar example for functions (check that first argument of same type):

```js
type _Fec<A, R, V: (a: A) => R> = [V, V]
type Fec<V: Function> = _Fec<*, *, V>

function a(v: string) {}
function b(v: number) {}

// $ExpectError
const v2: Fec<typeof a> = [a, b] // This type is incompatible with function

// Wrong - no errors
const va2: Fec<*>[] = [
    [a, b]
]
```

[flow/try](https://flow.org/try/#0MYGwhgzhAECC0G8BQ1XQGYAoCUiC+SBokMAQooUkgC4CeADgKbQBKjwAPAGoB80AvNADaAYXBRuPADTQxJDgBIAygFcARnSaSeAXSQB6fdAUBRAB5Ng1EwCcbAextJg9gHYRq0AG4AuVuw5YPkEhWBlSHWhDaAAVAAsASxhNZiToBNcXAFt6MGoEtRBmAHcE6ji4KmiAdQdXAHNoAFpoV3toRjtHCGc3D28wPzZOACoeIUiQlDRQ8L09GgZmAH0AMQCw1hkuP0xBuFx+PhZg4S5tvRTodc4d65VM-LdTtYCRmXfoXip0B6sEtzQMCYXzQDw2DL1XAIAi-R4A1zQNQgvyuFRZNSdaEEAxGUwWdjWLpOFzuTxeABMfhuHBS9nQQNOQjAMjUkWi8TSVzSGWyuXyhRKZQqcP+biqRlqbkaLTaHWJPVJ-S8YCp1ze40mwmmqGZrPmSCAA)

Simpler example:

Not working in flow:

```js
function a(v: string) {}
function b(v: number) {}

// $ExpectError
function f<A>(a1: A, b1: A) {}
f(a, b)
```
[flow/try](https://flow.org/try/#0GYVwdgxgLglg9mABAQwBQDcBciDOUBOMYA5gJSIDeAvgFCiSwKIBGG2YIAtswKb7nUadcNHhJgAHgCCAPlTIAjNikAaFksRSBtYPLXNSNIA)

But same example in [typescript/play](https://www.typescriptlang.org/play/#src=function%20a(v%3A%20string)%20%7B%7D%0D%0Afunction%20b(v%3A%20number)%20%7B%7D%0D%0A%0D%0Afunction%20f%3CA%3E(a1%3A%20A%2C%20b1%3A%20A)%20%7B%7D%0D%0Af(a%2C%20b)%0D%0A) shows as expected:
``` Argument of type '(v: number) => void' is not assignable to parameter of type '(v: string) => void'. ```

**Comment by zerkalica** [comment]
May be dupe #2630

**Comment by SamChou19815** [comment]
Closing since $SubType is killed
