### ISSUE TITLE
Unsupported Catch Declaration Parameter when Destructuring Catch Statement

### ISSUE THREAD

**Issue by TomPridham** [facebook/flow#5352]
Flow throws an error when trying to destructure input in a catch statement. see: https://flow.org/try/#0C4JwngBA3gUBHABYgPYHcIDsCmGCiIqIAFAOSLYDGA1qQJQwC+ElAhsJYsVALbYDO-VgHNsjOrHiUUmfigA22AHTyUw4n0EjsDRjBgB6A5hQRshFCBihIkhMnRZcEAkTIUa9Ji3adi5ogk4Fhk5RRU1fwsQJU0hUV0gA

**Comment by goodmind** [comment]
Duplicate of #6610 6636

**Comment by goodmind** [comment]
Duplicate of #6636
