### ISSUE TITLE
Type checking disjoint union with 3+ types causes "Property not found in object type"

### ISSUE THREAD

**Issue by alexandresmirnov** [facebook/flow#5355]
I'm trying to type check my way through a disjoint union, and when there are two possible types in the union, everything works fine (as per [the docs](https://flow.org/en/docs/types/unions/#toc-disjoint-unions)).  However, once I add a third type into the mix, I start getting "Property not found in object type" errors.

Is there something I'm doing wrong?

Example: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKArgMal4DOlYAvGAN5jb4BcYA5JWRdRwDRgAbgEMYxPOwBGcODDwiAdmAC+Abky4CAMREBLeQBMwdRsy3sOUMZTwCweAE6O4j9pQyO9igOaqNLAQA8hgAFk6mTIGWcGFO9rHhbmCKxAC2Uk7q6IFgACJwxFLyAEpUOHCKtqYk5FQ0AD5gugZ4hgFaYAAqXjil5ZXV9LW8jc36RmBNIUkaqMDAhnBUihwYYAiuANaoUMSKpBh6lWDwPj16fXgAFCLsF1dllBVVeACUDKgmelBgtwB0uVowM43DqfDejC+JjApEGcjw-zOANE4neGhMKmheBg1R+AKB9CsNjsH2hJjhVQRSLgPgBThcjjeGNU2NxBHxIkBnRBHES8TJMNh8PkNLpXP5TJZWKx82Am0cWxoUG8eF2+0Ox2UZwKRXkt3YuuKeCeL1sgrAPz+XMJRLBow4kM+QsplGpyK5qIkzOhWJMOLxUAJPKJ1nZjudMNd7tp9Ocrh9mNQWKAA

**Comment by jcready** [comment]
Use strict equality `===` and your example works.

**Comment by alexandresmirnov** [comment]
That fixes it, thank you so much!
