### ISSUE TITLE
getBoundingClientRect 'y' property not found

### ISSUE THREAD

**Issue by ericfalchier** [facebook/flow#5357]
Hey, flow is pretty awesome. Noticed when I ran flow I got this error. Might be a good reason why but noticed x and y are missing in the source code
![screen shot 2017-11-16 at 11 12 31 pm](https://user-images.githubusercontent.com/22512686/32929181-3968303c-cb24-11e7-909b-6000e3a180f5.png)
.

**Comment by agentcooper** [comment]
According to MDN [`x` and `y` are experimental](https://developer.mozilla.org/en-US/docs/Web/API/DOMRectReadOnly/x) with poor browser support. You probably want [`left` and `top`](https://github.com/facebook/flow/blob/140179bbe962fe623dd1d0955906115493eb519c/lib/dom.js#L3045-L3052).

**Comment by ericfalchier** [comment]
^Cool, thanks for answering

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by danielo515** [comment]
Ok, but what if I want to account for them in case they exist? Why this narrowing down doesn't make flow shut up?

```
return {
    width: rect.width,
    height: rect.height,
    top: 'x' in rect ? rect.x : rect.top,
    left: 'y' in rect ? rect.y : rect.left,
    x: 'x' in rect ? rect.x : rect.left,
    y: 'y' in rect ? rect.y : rect.top,
    right: rect.right,
    bottom: rect.bottom,
  }
```
