### ISSUE TITLE
Spread exact shaped object cannot flow into intersection type

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#5358]
This case seems pretty easy and I'm not sure if it is a bug or just a way how flow works, but for me it's odd that this spread type is treated as inexact.

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AYVgHaQCWA5qALygDeAPoqKMQCYBcoBArgLYBGWAJwA0DUOmzsAzigHECpEbQC+yAMaFpoEgQCG0AAo6BknFQAU6omXb4r5AGQ1QGIzu5SZc8koCUlAHygAOQCWJKc0ChBahoozkYmtiTk5pbJNoTJQvECbh6y8n4UgdSilprcgqRYzJQ0AHSNaWTZLrncoCqMoSicAgRacnqGxlhmlQLVzD6ISkA

**Comment by cprodescu** [comment]
This is likely same issue as #2405

**Comment by Andarist** [comment]
Indeed, I think it is. It's a bummer that the other issue stays unresolved after so much time 😢
