### ISSUE TITLE
Error when exporting a function working with a Map

### ISSUE THREAD

**Issue by Flashwit** [facebook/flow#5359]
This seems maybe potentially related to https://github.com/facebook/flow/issues/4805 but I'm not entirely sure. You can check out the error at the [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhgQLxgDeqYYGAFgJYB2A5gFxgCyJOAHgDOGAE5t2AGjAAjOHBh4SrAHyoAvugDGcViLBtmGZiRjEyebufJgqtekwndWeJHxwAKAJQbtu-QiMZLZgHiIWVqQ2VIbGptZ40tTY+NI4JFjwJAAm6l62KjR0YEIIRlqMHil4+fb0YFokQgQA5I4cLZzF9WCieBgArqKsRT09AHST4eSS3WPtXGAubvxhUXjjCz5jYJr0mpqoeAAeOHCiGGDZeFAkAzCXgWQA3EA) page.

```
type State = {
  thing: Map<string, boolean>
}

const initialState: State = {
  thing: new Map()
}

const what = (state: State = initialState, {type, payload}) => {
  switch(type) {
    case 'thing':
      return {
        ...state,
        thing: new Map(state.thing)
      }
  }
}

export default what;
```

results in

```
16:         thing: new Map(state.thing)                   ^ type parameter `K` of constructor call. Missing annotation
16:         thing: new Map(state.thing)                   ^ type parameter `V` of constructor call. Missing annotation
```

If you comment out the export default line, you will see that it stops complaining about the missing annotation for K and V.

I can guess that it wants me to annotate the types for some reason (even though it's already declared?) but I have no idea what this syntax is supposed to be.

**Comment by agentcooper** [comment]
Your example is missing return type and a default case for switch to eliminate `undefined`.

This type checks ([Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhgQLxgDeqYYGAFgJYB2A5gFxgCyJOAHgDOGAE5t2AGjAAjOHBh4SrAHyoAvugDGcViLBtmGZiRjEyebufJgqtekwndWeJHxwAKAJQbtu-QiMZLZgHiIWVqQ2VIbGptZ40tTY+NI4JFjwJAAm6twA8jIAVnhaGF6RFrYqNHRgQghGWoweKXhetfT0WiRCBADkjhz9nHVdYKJ4GACuoqyd410AdCvh5JJji0NcYC5u-GFReEvbPotgmuPZeFAk0zAYo+eTM3P1RwDcdZqaqHgAHjg4KIMGBrrd7qDAmQPkA)):

```
/* @flow */

type State = {
  thing: Map<string, boolean>
}

const initialState: State = {
  thing: new Map()
}

const what = (state: State = initialState, {type, payload}: Object): State => {
  switch(type) {
    case 'thing':
      return {
        ...state,
        thing: new Map(state.thing)
      }
    default:
      return state;
  }
}

export default what;
```

I agree that the error message is cryptic. The rule of thumb here I think is always make sure the return type is there for exported functions.

**Comment by Flashwit** [comment]
Oh wow, I never would've thought of that from that error message. Thanks!
