### ISSUE TITLE
Unclear "inconsistent use of library definitions" errors when property type mismatch

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#536]
While working on some code, we made a mistake, but got a confusing series of errors from Flow which distracted from the bug.

bar.js
```javascript
/* @flow */
// jshint ignore:start

class Bar {
    _worker: Worker;
    constructor(worker: Worker) {
        this._worker = Worker; // <-- whoops, typo
    }
    barrer() {
      this._worker.postMessage({a:5});
    }
}

export default Bar;
```

foo.js
```javascript
/* @flow */
// jshint ignore:start

// ...
import Bar from './bar';
// ...
```

```
$ flow check

/Users/chris/Coding/flow-worker-test/bar.js: inconsistent use of library definitions
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_21cbd535/lib/bom.js:122:1,128:1: class type: Worker
This type is incompatible with
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_21cbd535/lib/bom.js:122:1,128:1: Worker

/Users/chris/Coding/flow-worker-test/bar.js:10:7,37: call of method postMessage
Property not found in
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_21cbd535/lib/bom.js:122:1,128:1: statics of Worker

/Users/chris/Coding/flow-worker-test/foo.js: inconsistent use of library definitions
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_21cbd535/lib/bom.js:122:1,128:1: class type: Worker
This type is incompatible with
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_21cbd535/lib/bom.js:122:1,128:1: Worker

Found 3 errors
```

* The "inconsistent use of library definitions" error is given on bar.js with no line number which wasn't very useful. I skip past this one for now as it doesn't tell me much, and the other errors look more specific.
* Then an error is given on the line containing "postMessage" claiming that the property doesn't exist on `this._worker`, which confuses me pretty badly because `this._worker` is defined to be a Worker instance. I spent a while staring at the definition of Worker in flow's lib/bom.js trying to figure out if something was wrong with Worker's definition there. Tried declaring my own Worker class with a postMessage method and still couldn't figure out what was wrong here.
* Then another "inconsistent use of library definitions" error is given on foo.js with no line number, and mentions something about Worker, which confused me extremely because foo.js used to reference Worker, but the error message persisted even after I removed all mentions of Worker from foo.js!

What was weird was that Flow missed the one spot that actually had an error:

    this._worker = Worker;

(upper case "W". `this._worker` was supposed to be set to the `worker` variable which had an instance of a Worker. Not set to the Worker class itself, which should have failed type checking.)

**Comment by samwgoldman** [comment]
The error message looks like this now:

```
test.js:6
  6:         this._worker = Worker; // <-- whoops, typo
                            ^^^^^^ class type: Worker. This type is incompatible with
  4:     _worker: Worker;
                  ^^^^^^ Worker
```

I think that's good enough to resolve this issue.
