### ISSUE TITLE
Inference of new property on an Object value

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5362]
For variables marked as `Object`, I would like added properties to have their types inferred.

```js
const obj: Object = {}

obj.foo = 1  // Infer `foo` to be a `number | null`

const foo: typeof obj.foo = true  // Error!
```

This would be useful for a map of class instances, where each class may have unique properties. If the instance type can be inferred, I don't have to be explicit when accessing an instance.

Obviously, this wouldn't support dynamic keys (eg: `obj[key] = 1`).

And to clarify, objects typed using `const obj: { foo: number }` would still "throw" an error if an unknown property is accessed or set.

**Comment by vkurchatkin** [comment]
Just drop the annotation and it will work the way you want.
