### ISSUE TITLE
Transitive generic arguments lose constraints

### ISSUE THREAD

**Issue by Li0liQ** [facebook/flow#5363]
```
type Identity<T: Object> = T;
function foo<T: Object>(baz: T) {}
function bar<T: Object>(baz: Identity<T>) {}

foo(); // fails, as expected
bar(); // doesn't fail :(

```
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAJngHYYCW2APACoBcYA8gEYBWeAxhgHxgBeMHQDcqKAFcyPSnDJgocOPSZtOPXgApWAQwBeTOgEowAbwC+4qTLlhdAJxUsO3Ptv1MS5KrTq8TFuiKcJpGImDAwAo6lDAAzgA0YDpxYHgAHvg8eMSoDqHhkWDEcHhxZADkGNGxYAyaQA)
Passing argument of generic type into another generic type removes all constraints.
Expected behavior: constraints should be applied.

Current behavior causes issues in [react-redux libdef](https://github.com/flowtype/flow-typed/issues/1269).

**Comment by SamChou19815** [comment]
now both fail, if replacing Object with {...}
