### ISSUE TITLE
`extend` keyword for adding properties to an existing type

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5364]
I'm interested in extending an existing type (as requested in #396). One use case for extendable types is adding methods to a prototype. Would an `extend` keyword do the job?

```js
// flow-typed/jquery.js.flow
declare class JQuery {
  // ...
}

// src/extensions.js
extend class JQuery {
  smoothScroll(top?: number, left?: number): void;
}
$.fn.smoothScroll = function(top, left) {
  // ...
}
```

The two cons I see there are:
- You need to import `src/extensions.js` wherever you want type safety for the extensions.
- You can't just specify the type signature on the function itself.

The first con is easy to fix. Just add `src/extensions.js` under `[libs]` in the `.flowconfig` file.

The second con could be fixed with the following syntax:

```js
// Assume `typeof $.fn` => `class JQuery`
extend typeof $.fn {
  smoothScroll(top: number, left: number): void {
    // ...
  }
}

// ...compiles to:
Object.assign($.fn, {
  smoothScroll(top, left) {
    // ...
  }
})
```

Until something like that is possible, I'll be doing `Object.assign(($.fn: any), {...})` and adding the method signatures to the original `declare class JQuery` statement.

**Comment by aleclarson** [comment]
To clarify, I'm proposing both `extend class` and `extend typeof` be added to Flow.

**Comment by Andarist** [comment]
Hm, I was wondering the other day how to extend redux's store and I guess your proposal could help with that.

**Comment by doberkofler** [comment]
typescript supports the concept of merging.
https://www.typescriptlang.org/docs/handbook/declaration-merging.html

**Comment by aleclarson** [comment]
@doberkofler The `interface` merging and `namespace` keyword look great. I would want `namespace` to work with modules, though.

**Replacing `extend typeof`:**

```js
// Assume `JQuery` is a class declaration defined in the `flow-typed` directory.
namespace JQuery {
  smoothScroll(top: number, left: number): void {
    // ...
  }
}
```

**Replacing `extend class`:**

```js
// The `smoothScroll` method is provided by a third-party (which doesn't have libdefs).
interface JQuery {
  smoothScroll(top: number, left: number): void;
}
```

Nice detective work, @doberkofler. I haven't checked out TypeScript, since it doesn't have gradual adoption, IIRC.

**Comment by deecewan** [comment]
maybe even `extend module 'jquery'` at the top level?

**Comment by SamChou19815** [comment]
Closing since we don't plan to add this keyword. Once we support things like this, it will be via things like declaration merging in TS
