### ISSUE TITLE
Cannot name my types like some builtins

### ISSUE THREAD

**Issue by loyd** [facebook/flow#5365]
Hi, everyone.

```javascript
/* @flow */
class Array {
    a: string;
}

function t(a: Array) {}  // Incorrect number of type parameters (expected 1)
```

But it works fine with `Map`, `Boolean`, `String` etc, but not with `Array` and `Function`.

**Comment by agentcooper** [comment]
You can [turn off Flow library definitions](https://flow.org/en/docs/config/options/#toc-no-flowlib-boolean).

**Comment by loyd** [comment]
I know, but I don't want to replace std defs.

**Comment by SamChou19815** [comment]
This is now allowed
