### ISSUE TITLE
ObjMap example broken since 0.57.0

### ISSUE THREAD

**Issue by trevorah** [facebook/flow#5366]
Looks like the changes to `$ObjMap` broke something in the example: https://flow.org/en/docs/types/utilities/#toc-objmap

0.56.0:

<img width="980" alt="screen shot 2017-11-19 at 15 45 06" src="https://user-images.githubusercontent.com/298742/32992314-f80e6812-cd40-11e7-9c81-cf675003e3e2.png">

0.57.0 and higher:

<img width="980" alt="screen shot 2017-11-19 at 15 45 19" src="https://user-images.githubusercontent.com/298742/32992315-038d16fc-cd41-11e7-9476-f127249064a6.png">

I'd love to know if this is a bug or a changing api, as the `$ObjMap` example is almost identical to something I'm trying to type up at the moment.

Thanks!

https://flow.org/try/#0PTAEAEDMBsHsHcBQiSmgUwC4HIDOp4AnAS03VAENRMBPAB3QwDdHRIBXAOwGNNjZO1ABYVM1CgGt0+KgAMAFAEpQAXgB8oAGqzKnACahCWdoU4zQs7aHml8RzCcG0GixM-IBRAB6ZCFXgBKxqYAKvTkKqAAPJpq8kqqGprK6lrIHDx8AoZcUQCCADSgAPIAXKAA3gDaUjTluL7EnADmALrlCal5AL5xsOXFiuUAJMUARgBWALIUdFHFRd6+-phBDqHhGhWIoIbBguMT6LwAdLW48rCKJ0Z67Nzo8f7cRRIpGofHmCcUuLjEzU48meRQqoBq7VAsAhCW6ilBcIA3IhushuAIGlDVJUdpQOu9qIR2OgCrixvjEqBsJBYLBsCjkYh5ESgVcfuUxrSMBROIpEaBUMUJEyWZdruTQA0SC0+btBcKgA

**Comment by vkurchatkin** [comment]
This just seems like a very bad example that is not supposed to work. This works fine:

```js
type ExtractReturnType = <V>(() => V) => V

declare function run<A, O>(o: O): $ObjMap<O, ExtractReturnType>;
    
const o = {
  a: () => true,
  b: () => 'foo'
};

(run(o).a: boolean); // Ok
(run(o).b: string);  // Ok
```

**Comment by trevorah** [comment]
@vkurchatkin that fixes the return type, but the args are no longer enforced:
```js
type ExtractReturnType = <V>(() => V) => V

declare function run<A, O>(o: O): $ObjMap<O, ExtractReturnType>;
    
const o = {
  a: () => true,
  b: () => 'foo'
};

(run(o).a: boolean); // Ok
(run(o).b: string);  // Ok
run({ cat: "dog" }) // Ok, but I would like an error...
```

**Comment by vkurchatkin** [comment]
That is a regression, unfortunately

**Comment by trevorah** [comment]
Thats a shame. Anything I can do to help?

**Comment by Alxandr** [comment]
Probably related: https://github.com/facebook/flow/issues/5428

**Comment by deecewan** [comment]
Any updates on this? Seems pretty average to add a regression *8* versions ago now, and now address it.

**Comment by goodmind** [comment]
It errors if you access value

https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwBVxoBeKAHgDUA+ACgDMAuKOgSilJqio654BQAgCYRUAG2SJoDHPnQBLAPb4oiORQCCAGigB5ekpZ62LACR6ARgCsAssjAU9u+EjSZseIiRoBuAVCBUAKoKgDOwFBKnFAA3gFQyCzsnNxIOBDaCZbJfNwA5AxKSvkCAL7+AnTq+HRKbAB0SVCWxeIQyPhsvlAA9L36ANZVNXWNOVARiAr4AObdgf1DIeGRAG7I4jGjsVCoyMAsAETCSrNHUGUcS3qDupY4kQCSUADuSjjiwlDiCoPQnSgEEQiCUiAaEKEG3EDX2wCAA

**Comment by SamChou19815** [comment]
The example has been updated a while ago
