### ISSUE TITLE
Refinement bug with disjoint $Keys or cryptic error

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#5367]
Aint sure how to describe this better with words, I think [the example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqA5gKa4C8oAPACoBcoA8gEYBWBK2ANKAAo0AkA0gQCemSgD5RACgAOAJ1hSanDrCY0KASl4BRaAQC2BdNgqCpBSh06jQxaysYBtWfIC6iUB88fUGHKBQArjIyAJYEACYA4kQ25NR0TCzsXLwCwmKSzgpcmqASFDbWPDr6hsam5hSWouqFoPZ19k5yUm6IIKDwsDIA1iHoeD5YuOgBBqEoAMrd2ABCgpwtsZQ0DMyslqlCIhTi0i20MgCyAIZSZjKKHCfBag4uuRT3dQDe7p5ow6B6ZxexDbZ8ER9vJDqdzgQZMomOpEABIGREILoUA3GQAOkwMwkEgIugMRgAghw8aUjLNaoCfhCZLj8WVCbUALTfX6QulkubqWEAX2QHS6vX6g0+flG4xCUxm83Bf1IKwS62S3FA-G2GQk1Iuajq4vokOut1ATwedxcr3hiOwyNRwUx2I5BOwxNApKdFLqWvZboZzNZNMdZQp6jhiD57TAgr6Ay8QzFY0hkumMjmggAqphhQBhIKhCLREhxVaJDYpVVpHZ7LJgtmXLigAA+eQKgL1kPUhrrJsez0BbzhotwXpksWwFVgkFA1eOtZsxFIAHJIAF0KwQhgF6AAPxTg4zmmgGiBYJhKLA6ey9uWpEyFFo+0pnE+okk+nkynWYeBol+r-Prm8u8XjASBoARqA6CwLgUbCnGIwJhMyapss8RrEkmzluquyZHul51pwjbNrqYz6jIHa2l29w9uafbwroQ61kBoAhJOEhjmYE67qC+5yvOoBLiua4brUbwgcOsQXoxXg8q60CYAQoCicBHQoCcODCqAAAWkIKSEmD1D0TEeCCUg1jSNA4KEAzqAA3EZ-pyvUTB1IQ2AmWZFzQowsLSde1q3hRD5ud+zqvpyHpUrWIWMqALJ-m+AFhvZoHAYgQA) can explain it best.

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
