### ISSUE TITLE
"Method cannot be called on possibly null value" while using method twice

### ISSUE THREAD

**Issue by jony89** [facebook/flow#5372]
Getting, "Method cannot be called on possibly null value" while using method twice, although There is a check that the method is not null.

The error is only on the second line : 

```js
    if (this.refItem) {
      this.refItem.methodA();
      this.refItem.methodB();
    }
```

reproduced here : 

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciilAHplygcAT3SVQABUboyAXlABvRAF8eiMRNABlHERyTFK9bxrRSZAGLJolACrtJAwwDsAJmSq0cAOgDCTJiulK44ADwysHIANLr6hgB8yoigoCQJyDSg7pSQRACu0DhRcqDGqaCqvGns7B6UWAAyyBnloAAUAJTlySppaciQnTgAFq2+7JAAkoaoPf0DaWMTU7OUqL6olGOw7gCC3TxLy+Mkk3nrm9u77gBCR5Vp1c8aaeiyJABc0p9voGs5j8APzeOi+ACidm2YSokHCRFcokS-1GiPcdiucPaHRoILBfihG1CODhCKRiR68j6IjOFxmc3aNC4VX+9VyWG6KSW7BwBSwrk6TwG4XcyAAbolhUtRRKAXl5EoVuc0R5MXM4apQMApSdQOFgGLJcKuscqmpeAIhHhcvkingbHZHJRKDwgA

**Comment by apsavin** [comment]
https://flow.org/en/docs/lang/refinements/#refinement-invalidations-a-classtoc-idtoc-refinement-invalidations-hreftoc-refinement-invalidationsa

fixed [example](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciilAHplygcAT3SVQABUboyAXlABvRAF8eiMRNABlHERyTFK9bxrRSZAGLJolACrtJAwwDsAJmSq0cAOgDCTJiulK44ADwysHIANLr6hgB8yoigoCQJyDSg7pSQRACu0DhRcqDGqaCqvGns7B6UWAAyyBnloAAUAJTlySppaTSwrm3skACShsyKOAAWrb5jk5SoPAOgyJCdS1M9-eugOyu+qJRzsO4Agt1rB0eoJ2ezFwBCN5Vp1Z8aaeiyJAAuaT-H6HPLLVBAgD83jovgAonZTmEqJBwkRXKJEqDZhj3HYIaj2h0aNDYX5EStQjhUejMYkevI+iJ5iRFuCpu0aFwqqD6rksN0Uut2DgClhXJ0PgNwu5kAA3RLS9ayhVgyDyJRzBa4jwEqao1SgYBKg6gcLAOWK6VdW7Vap8QTYPC5fJFPA2OyOSiUHhAA)

**Comment by apsavin** [comment]
Also see https://github.com/facebook/flow/issues/2715

**Comment by jony89** [comment]
Umm, that's not a fix but a workaround..
