### ISSUE TITLE
"Called with too few arguments" for declared %checks function

### ISSUE THREAD

**Issue by loyd** [facebook/flow#5374]
```js
declare function test(n: Object, opts?: Object): boolean %checks (typeof n === 'string');

test({});  // function call. Called with too few arguments
```

[Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmjloDO5AFCQFygDyARgFabkANKFgAHcgwD8HHvwoBKDt1ixoabLQCkGABaYA1g1DNyAT1FpYkULQC890AHImuSiQDmj+QG5k9JswA3gC+PkA)

**Comment by Brianzchen** [comment]
This works now in latest version 0.138.0
