### ISSUE TITLE
[bug] Argument destructuring - calls invalidate refinement

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#5378]
If we keep this destructuring in the argument it seems that functions calls (such as `Object.keys` in the example) invalidate refined property (it's kinda treated as it could change like when being an object's property).

If we move destructuring (uncomment commented lines) to the function's body it magically starts to work correctly.

[Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqArgA5wCGAJgGICW0ApqALygAUiAkHgE7QBcoOHldAHMANG1LFsxXgHkARgCsaKbGNYBvUAAsaZGh0wjQGAAodYQjjUyZQAX16adegwH5HoANr9BQgLq8PsL2RqbmltaY7qDoeAC2cvoMAHygcZQAHjSk9gyg6nZioKCsIJgEyh7OpPpRHt7YAsIBfI2+IcboZhZWNtGxCUn0qelZOXZ5BYgAlCn5bCCgaFi4Tro1BqFd4b22E4zlymzLOKAZWhyTdscYp5qEJON55xzIrJSQzNgAnhWwn2EepEGPRGABySB4dAqSgYMGzdRsdhEWBkAB0GAIO2BjBoADcaOhcMN5qwyYCIjYmPjCdg0Y9sqAwDSiWjsLApNBpkjrqxrmwHqjSBj0I88kxZiSpsjHiL9OZLowJXNpYL0RhiHJYBxicxJakpmwXhiKugmGCTDIAMoAFTBRk4XLeH2Y1VqCKR8iUKjRAGsaN9MEw3QZpmi4sQCMH1kNUsbMDRsAAlGgARzw1mwAAkYxxoy4jCHMJ4Q35pty+W944TSEwJFJuXYgA)

**Comment by jcready** [comment]
That's because arguments are treated as `let` whereas your destructuring in the function body is using `const`.

**Comment by Andarist** [comment]
Makes sense, thanks for explaining. Was starring at this for quite a bit and didn't connect those 2 dots.
