### ISSUE TITLE
Flow thinks it's undefined?

### ISSUE THREAD

**Issue by VictorChen** [facebook/flow#5381]
Here's my code:

```
function testString(foo: string) {
  return foo;
}

type Person = {
  name: {
    first?: string,
    last?: string
  }
};

function test(person: Person) {
  if (person.name.first && person.name.last) {
    return `${testString(person.name.first)} - ${testString(person.name.last)}`;
  }
}
```

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygZSgJxmAcwApg44AuRDPQgSkQG8AoRRHFKEHJUuAbiYBfJkygBPAA4pEABRQ40CRAF5GLRGACGAWxSVmrAJDAYCqAH5K1fAQA061gBtNGS1Vw31wwQKahIsEqoGERSCgiUcuFg9AaIMMCIofKKYAB0WrppJmaIAGR5iGGpGTooac4YsQ5sHFxIAAYAJAzBWB6EydGlWTlVgogAtIgtbdg0xMUIPeWVULSCDQKs3kxAA

For some reason it thinks `person.name.last` is undefined? Also, what's weird is that rewriting it to this works:

```
function test(person: Person) {
  if (person.name.first && person.name.last) {
    const first = person.name.first;
    const last = person.name.last;
    return `${testString(first)} - ${testString(last)}`;
  }
}
```

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygZSgJxmAcwApg44AuRDPQgSkQG8AoRRHFKEHJUuAbiYBfJkygBPAA4pEABRQ40CRAF5GLRGACGAWxSVmrAJDAYCqAH5K1fAQA061gBtNGS1Vw31wwQKahIsEqoGERSCgiUcuFg9AaIMMCIofKKYAB0WrppJmaIAGR5iGGpGTooac4YsQ6IEAgYiDkNqsUIpVlNUAKsrHVgDZVQKkUpbZnlg9097JzciAAGACQMwVgehCSmVYKIALSIy6vYNMSDtILzU95MQA

**Comment by apsavin** [comment]
https://github.com/facebook/flow/issues/5372

**Comment by VictorChen** [comment]
@apsavin ah thanks!
