### ISSUE TITLE
Declare exported variable types

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5383]
I want to declare the types of each property in the `exports` object of a module.

This is the only way I've found works:

```js
// $FlowFixMe
declare var exports: {
  foo: () => Promise<void>,
}

exports.foo = () => Promise.resolve()
```

Is there a recommended approach for doing this?

**Comment by bradennapier** [comment]
You may find some insight in the example we have here: https://github.com/Dash-OS/flow-by-example/tree/master/examples/typing-imports

**Comment by aleclarson** [comment]
@bradennapier Are you talking about [this file](https://github.com/Dash-OS/flow-by-example/blob/254bfd0e64a9c4555117ac5d04c4b28660fb1d91/examples/typing-imports/classes/index.js)? I'm looking to declare the property types of the `exports` object, where the function implementation exists in the same file and may have multiple signatures.


This works:
```js
module.exports = {
  foo(): Promise<void> {
    // ...
  }
}
```

But I would prefer to use the provided `exports` object.
It seems I can't override its default type of `Object` though.

**Comment by bradennapier** [comment]
You specifically want to do this within a flowlib and not with exported .flow.js files?  It works perfectly for me if declared in the files themselves but perhaps I am still misunderstanding what you want to do.

![image](https://user-images.githubusercontent.com/15365418/33101367-ec15ed7c-cecc-11e7-8055-8db2064539c4.png)

**Comment by bradennapier** [comment]
What you want is to just use declare function multiple times.  Those are provided as exports. 

```js
/* @flow */
declare module 'import-test' {
  declare function foo(): Promise<void>;
  declare function foo(a: number): number;
}
```

```js
/* @flow */

const obj = require('import-test');

const { foo } = obj;

const result = foo(1);

(result: number);

const result2 = foo();

(result2: Promise<void>);

```

**Comment by aleclarson** [comment]
I should clarify I'm working with an internal module, but your advice works well for others that come across this issue. Thanks for investigating! 👍 

> If outside of a flowlib then you dont want to use declare like you are as that is globally declaring the type which is obviously going to be a problem.

Not always true. The following declaration is what I'm looking for:

```js
declare module.exports: {
  foo: () => Promise<void>,
}
```

But it doesn't seem to support function overloading:

```js
// The second `foo` takes precedence.
declare module.exports: {
  foo: () => Promise<void>,
  foo: (a: number) => number,
}

// Same here.
declare module.exports: {
  foo(): Promise<void>;
  foo(a: number): number;
}
```

**Comment by bradennapier** [comment]
You will still get an error, but something like this does work... the error is probably similar to the one you ran into. 

However it does type things properly in the other files.

```js

const foo = (a?: number): Promise<number> | number => {
  if (typeof a === 'number') {
    return Promise.resolve(2);
  }
  return 2;
};

// $FlowIgnore
module.exports = ({
  foo,
}: {
  foo: ((a: number) => Promise<number>) & (() => number),
  // foo(a: string): Promise<number>,
});

```

```js
const obj = require('./mod');

const { foo } = obj;

const result = foo(1);

// $Works
(result: Promise<number>);

const result2 = foo();

// $Works
(result2: number);
```

![image](https://user-images.githubusercontent.com/15365418/33110828-843577da-ceff-11e7-9dc0-93a358359d8f.png)

![image](https://user-images.githubusercontent.com/15365418/33110831-8b9b92de-ceff-11e7-9c0d-2e6bef86b673.png)

**Comment by aleclarson** [comment]
@bradennapier Awesome, thank you for the help!
