### ISSUE TITLE
Flow inconsistently reports errors, gets stuck on "0" errors

### ISSUE THREAD

**Issue by rossPatton** [facebook/flow#5385]
This has been affecting me and a coworker. I'm not sure exactly when this began occurring, but sometime around `0.56.0` and the latest release

Here's what happens. I'll run `flow status` and get a list of errors. So far, so good. Functioning as expected. After fixing some (but definitely not all) errors, I run `flow status` again. Now it says 0 errors, but I know for a fact that this is not accurate. Sometime later (often much later) the previous errors will resurface unexpectedly, blocking releases and just generally being very annoying. This behavior occurs on my macbook pro, my coworkers macbook pro, and even on our ci environment (circle)

Running a full check via `flow check` is no different, same erratic behavior

I'm not sure how to reproduce, since the main problem is it's unpredictableness

In my current situation, I did some much needed re-organizing. I was running `flow status` to fix broken imports. I moved hundreds of files and folders, and had about 160 errors left (that I most certainly did not fix). All of a sudden, flow ceases to work

<img width="1007" alt="screen shot 2017-11-20 at 4 50 14 pm" src="https://user-images.githubusercontent.com/2379901/33049026-f25808e2-ce12-11e7-8319-982fcf5792fa.png">

<img width="740" alt="screen shot 2017-11-20 at 4 50 24 pm" src="https://user-images.githubusercontent.com/2379901/33049029-f8775c78-ce12-11e7-89c3-d9e15032cccb.png">

**Comment by apsavin** [comment]
#5180 ?

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
