### ISSUE TITLE
Primitives recognition bug

### ISSUE THREAD

**Issue by xahon** [facebook/flow#5387]
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAgqAN6KgBu+OAjAFygDOGO6A5gNzV04ATAH4W7Tml6IAvskLR8rVqABClavgCSadszIbt7QS1LVQZwrB0cAroQywcACnwmAlOtBfQGABYpWADotawZQAF5QAHkAIwArLHtgpRQuNCcKaQAaT28vAWNQJyc3MQ5uCIA+UABycRq3EpyQUABVVgqFAFsYgBN8UHhHAGtWMzzAyfxx0Gk3GZm-AODDDEEI6PjEjGSOtIzs3LyCljqOGuawAAVOLpQMFBoSAAd6VixlRVAbNF6sSHQWF6My8k2CMzmZlk0iAA

I think it does not need an explanation

**Comment by SamChou19815** [comment]
Now working as expected.
