### ISSUE TITLE
[feature request] Covariant function arguments

### ISSUE THREAD

**Issue by Andarist** [facebook/flow#5392]
It would be super nice to mark any function arguments as covariant, without that we need to make ugly hacks like [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqA5gKa4C8oAPAPIBcoFARgFYErYA0oACjQCQDSBAT0yUAfCIAUABwBOsSTQ7tYjGhQCUPAKLQCAWwLpsAFQGSCldhxGhi15QwDaMuQF1EoD54+oMOUOgBXfWkASxQAZVhpbAAhARtyI1VGZjZOHn4hMiMxcRD0ADcAQ1Ciww5ZSQppAFkiyTNpBVAAH1BxIxtrQN06Amk1dhKm0CMHFw1R8a7QAG9EAEgQUAALIpQAa0W0LFxnKtr6xoT84tLyyuq6hv7t31xdI-6E7FMCWEhQfaun6RtiUgAckgAXQLBCGEBoAA-F9Locbn8aOICNA1DNCNgpPDro12Ki1ItpEQAtJ0KBhgA6TBRLEonT6QwAQXxDIMsXRtlAj0R9L07KZ6IAtNzfnzGRzCQBfIA)

**Comment by bradennapier** [comment]
You can set the generics that you assign to the arguments as covariant, but don't think that is what you are wanting here.  

Honestly don't really understand what it does specifically at this point.  I do know that it is critical to make some things work at times though

[Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqA5gKa4C8oAPANQDyAXKFQEYBWBK2ANKBQAp0AkAaQIBPTGSoA+CQAoADgCdYsut06xmdKgEp+AUWgEAtgXTYAKsNkFxnbhNDF76pgG0FSgLqJQP3z9QYOKDoAK7G8gCWKADKsPLYAELCDuQUZprMrBxcvKCCImJmUtIR6ABuAIaRFabcirJU8gCyFbJW8iqgAD6g0mYO9qGGDATyWpxVHaBmLh4607MDoADeiACQIKAAFhUoANbraFi47g3Nre0ppZXVtfWNLW2jh4G4hhejKdiWBLCQoKcHh95A5iKQAOSQELoNgRDDg0AAfgB93OTxBdGkBGgWiWhGwclRj3anGxWnW8iIIXk6FAkwAdJg4gSsQZjKYAIKktkmRK4xygd7o1lGXkc3EAWkFwJF7L55IAvkA)

**Comment by Andarist** [comment]
Nope, it's unfortunately not the same - look [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqA5gKa4C8oAPANQDyAXKFQEYBWBK2ANKBQAp0AkAaQIBPTGSoA+CQAoADgCdYsut06xmdKgEp+AUWgEAtgXTYAKsNkFxnbhNDF76pgG0FSgLqJQP3z9QYOKDoAK7G8gCWKADKsPLYAELCDuQUZprMrBxcvKCCImJmUnKKslTyALIAhrJW8iqgAD6g0mYO9qGGDATyWpxV8vWgZi4eOsOj7aAA3ogAkGhYuIY1dSnYlgSwkKDuZZWrPQ7EpADkkCHobBEYp6AA-Lul5dW1R3TSBNBaU4TYJUoXod5Jwvlp5vIiCF5OhQAN5AA6TBxf6fAzGUwAQVB6JMiR+jlAKze8jRRjxmJ+AFoicCyRj8eCAL5AA)

Also would love some docs about setting a variance on generics, no idea what it does at the moment   ¯\\_(ツ)_/¯

**Comment by jesseschalken** [comment]
Why does Flow not accept the code without the extra variable? I would have thought `propOrMapper` would be narrowed to `P` in the else branch of the ternary. 🤔

**Comment by jesseschalken** [comment]
Try https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean

**Comment by jesseschalken** [comment]
Also, I don't see why extracting a variable causes the code to pass. Even if the new variable is declared with `let` or `var`, Flow still seems to narrow it in the else of the ternary because there are no assignments to it anywhere (it's "effectively const"). Why doesn't the same apply to the parameter?

**Comment by Andarist** [comment]
Hm, I was pretty sure that changing the declaration to `let` or `var` would cause the same thing as having it in the argument. It seems though that flow is preserver the refinement in that case too.

There is a possibility that flow treats arguments as reassignable object (which it is in non strict mode) and fears to make the assumption that it won't change. That would be quite weird behaviour of flow, shouldn't assume such things.

The reason might ofc me completely different, now knowing that `let` and `var`s are keeping their refinements I would categorize my issue as a bug.
