### ISSUE TITLE
Refinement from 'mixed' to 'object' is lost after call to `hasOwnProperty()`

### ISSUE THREAD

**Issue by anandthakker** [facebook/flow#5393]
In the following, I'd expect both uses of `hasOwnProperty` to type check successfully, but the latter produces "call of method `hasOwnProperty`. Method cannot be called on mixed".

```js
function f(input: mixed) {
  if (typeof input === 'object' && input !== null) {
    input.hasOwnProperty('foo');
    for (const key in input) {
      if (!input.hasOwnProperty(key)) continue;
    }
  }
}
```

https://flow.org/try/#0GYVwdgxgLglg9mABMAFDMAHEUBciC2MAHgKYAmAlIgN4BQiiMwiKUAnhiXM+llIgF4hiAORwARgCsS0EYgBk8xpmyIAhMLAgANtqp0GDXtgB0ACwCGAZwDyAdzAAFAE5xOz9ihHA4cERQBuekMfZxYIBCt+AGsSNmVlPn1gw0ZmFDVjKHNreydXd09YtgoqCLBYLRIg1IBfYPraoA

**Comment by lll000111** [comment]
This version has no errors, although I did not really change anything, just some reformatting:

```js
function f (input: mixed) {
    if (typeof input === 'object' && input !== null) {
        input.hasOwnProperty('foo');

        for (const key in input) {
            if (!input.hasOwnProperty(key)) {
                //...
            }
        }
    }
}
```

[Flow Try link](https://flow.org/try/#0GYVwdgxgLglg9mABMRAKGYAOIoC5EC2MAHgKYAmAlIgN4BQijiMKqUAnpqXChtlIgC8wxAHI4AIwBWpaKMQAyBcyw5EAQhFgQAGx3V6TIyv4A6ABYBDAM4B5AO5gACgCc4XFx1SjgcOKMoAbjoGY0ZfFzQIBGsBAGtSdhUTHANQsKMWNHU+HAsbB2c3Dy8E9ko0jKrEAHoa0wb06oBfJqNW9rpWoA)

**Comment by CharlesStover** [comment]
`input` (and all function parameters) are not constants. Flow is afraid that these variables will change value at some point in the function, because they could. If input was type number, it could change to another number, and that's fine. The type is still number, so you can do number things with it. However, if input can have multiple times (as mixed, it can), then changing it from an object to a number or string or etc. means you can no longer do Object things with it.

To get around this, you set temporary constant variables:
```JS
function f(input: mixed) {
  if (typeof input === 'object' && input !== null) {
    const i: Object = input;
    i.hasOwnProperty('foo');
    for (const key in i) {
      if (!i.hasOwnProperty(key)) continue;
    }
  }
}
```

If input changes, that's fine -- the temporary variable here still points to the Object that input was, allowing you to use Object methods on it.

**Comment by lll000111** [comment]
That should ONLY be a concern if a function is called, which Flow does not interpret further and therefore treats as "possibly mutating". I don't think this is a valid explanation in this case, without any inner function. I've had that conversation numerous times previously, and it _always_ was about inner functions.

**Comment by CharlesStover** [comment]
>That should ONLY be a concern if a function is called,

[You'd think so.](http://files.explosm.net/comics/rlincoln.jpg) Unfortunately (or fortunately for the original poster), the code I posted validated with no errors.

hasOwnProperty probably is a refinement invalidation. I don't believe Flow distinguishes between whether or not a called function is an innate, non-mutating JavaScript function or a possibly-mutating, user-made function. Perhaps it should.

**Comment by anandthakker** [comment]
> hasOwnProperty probably is a refinement invalidation. I don't believe Flow distinguishes between whether or not a called function is an innate, non-mutating JavaScript function or a possibly-mutating, user-made function. Perhaps it should.

Ah, interesting.  Yeah, I think you're right about this; I assumed (for not good reason) that `hasOwnProperty` would have special semantics.  Thanks for the workaround, @CharlesStover.

**Comment by SamChou19815** [comment]
expected since function call invalidates refinements
