### ISSUE TITLE
`type-at-pos` is broken with Map/Set/mixed

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5397]
Unfortunately I have zero clue how to re-create this one, it appears to be due to some deep reason I can not figure out and has to be multiple files or something - essentially I get this error, which breaks flow across the board on `nuclide`

```
[2017-11-23T02:40:05.142Z] [WARN] nuclide-flow-rpc - Invalid JSON result from flow type-at-pos --json --path /Users/bradennapier/Desktop/Dash OS/IDE/projects/pubchan/src/middleware/wildcard/index.js 72 35. JSON:
''.
```

It happens as soon as I try to refine a reduced Map -> Iterator -> Array<mixed> it fails.  Super confusing 

```js
function prepareWildcardSearch(
  matches: Set<PubSub$Subscriber>,
  listeners: Map<mixed, Set<PubSub$Subscriber>>,
  middleware: Middleware<WildcardMiddleware$State>,
) {
  const listenerKeys = [...listeners.keys()];
  const fin: Array<Wildcard$ToPatternTypes> = [];
  const keys = listenerKeys.reduce((p, c) => {
    console.log(c);
    // --> THIS BREAKS FLOW 
    if (c) {
    }
    return p;
  }, fin);
  middleware.state = { keys };
}

```

Been trying for 2+ hours to make a repro but I can't... so its obviously some deeper issue that breaks this during refinement in the reduce.  I would imagine it is linked to all the refinement bugs in some way.

**Update** `if (c) {}` breaks it but `if (c != null) {}` does not seem to break it.

**Comment by SamChou19815** [comment]
not enough info to repro
