### ISSUE TITLE
property `Component`. Too few type arguments. Expected at least 1

### ISSUE THREAD

**Issue by imdadahad** [facebook/flow#5402]
If this is a bug, please try reproducing using https://flow.org/try/.

![image](https://user-images.githubusercontent.com/5855115/33191194-734f1236-d0ae-11e7-9614-6bdcd7ab854d.png)

```
/* @flow */
import React, { Component } from "react"

class MyComponent extends Component {
  
}
```

**Comment by vkurchatkin** [comment]
`Component` requires at least one type argument:

```js
class MyComponent extends Component<{}> {
  
}
```
