### ISSUE TITLE
Flow sometimes doesn't understand localStorage behavior

### ISSUE THREAD

**Issue by emil14** [facebook/flow#5405]
Flow doesn't understand that value of `savedItem` variable can't be `null`:  

```JavaScript
/* @flow */

function getSavedItem (): ?string {
  return localStorage.getItem('key');
}

if (getSavedItem() === null) {
  localStorage.setItem('key', 'value');
}

const savedItem: string = getSavedItem();

JSON.parse(getSavedItem());
```
It says:
`const savedItem: string = getSavedItem(); ^ null. This type is incompatible with string`

But somehow it does understand  when using arrow function instead of regular

```JavaScript
/* @flow */

const getSavedItem: Function = (): ?string => global.localStorage.getItem('key');
```

---

Don't forget to use `global.localStorage` instead of `localStorage` if you want to reproduce this behavior on https://flow.org/try

**Comment by vkurchatkin** [comment]
Flow knows nothing about `localStorage`, so it can't know that `getItem` won't be undefined after you call `setItem`.

**Comment by emil14** [comment]
Thank you, I got your point.

But why Flow isn't against using arrow functions here? And why Flow "knows nothing about `localStorage`" but knows about `JSON.parse()` method (I can't pass non-string value to it because of Flow warnings).

Can you tell me how should I handle things like these if for some reason the regular function is needed?

**Comment by vkurchatkin** [comment]
> But why Flow isn't against using arrow functions here?

This has nothing to do with arrow functions. In the second example you assign you function to a `Function` type, which essentially is a function that returns `any`.

**Comment by emil14** [comment]
Yes, you're right. I thought `(): ?string` in the first example gives Flow understanding of what `getSavedItem` returns but its not.

Thank you!
