### ISSUE TITLE
BUG: checking if ((val:?OpaqueType) != null) makes val unusable (ill-typed)

### ISSUE THREAD

**Issue by rvion** [facebook/flow#5406]
# BUG when checking if ?OpaqueType != null
checking if ?OpaqueType != null break opacity

flow version 0.59

## reproduction:
2 files needed to reproduce:

### a.js

```js
//@flow
export opaque type AAA: string = string
export const maybeA: ?AAA = 'ok'
```

### b.js (ERROR)

```js
//@flow
import { maybeA } from './a'
import type { AAA } from './a'

const a: ?AAA = maybeA

if (a != null) {
}
```

gives error:

```
[flow] string (b.js:6:11) This type is incompatible with AAA (b.js:6:11)
Flow-IDE
AAA: ? AAA
```

![image](https://user-images.githubusercontent.com/2150990/33231896-2647f624-d1fd-11e7-9ab6-55d43d48130c.png)

--------------------

more info:

flow doesn't complain when I do nothing with my a.

```js
//@flow
import { maybeA } from './a'
import type { AAA } from './a'

const a: ?AAA = maybeA

// if (a != null) {
//     use
// }
```

but there is no realist way for me to use a: 

![image](https://user-images.githubusercontent.com/2150990/33231930-cdbb1648-d1fd-11e7-8d18-860a7f9f790e.png)

I can unsafe cast things like that:

![image](https://user-images.githubusercontent.com/2150990/33231969-a25b8090-d1fe-11e7-8fe2-b38de5c30548.png)

but I'm working on a medium sized app with ~300+ modules, and in some cases, it's _really_ unpractical / not worthing the effort because all I would gain would be extra complexity for no added safety

-----------

Also, in my code, opaques comes from a libdef, not from a module:

```js
declare opaque type SomeStuffId: string
declare opaque type MiscId: string
...
```

 📝  __so the problem is not related with the type alias, only the super type__

**Comment by darichey** [comment]
This works now.
