### ISSUE TITLE
Flow allows multiple signatures for an array manipulating function, one of which is wrong

### ISSUE THREAD

**Issue by josephjunker** [facebook/flow#5408]
This typechecks, even though `badFunc` is given the wrong signature:
```es6
function badFunc(arr: Array<number>) : Array<Array<number>> {
  return [].concat(id(arr));
}

function id<A>(a: A) : A {
  return a;
}
```
This can be seen [here](https://flow.org/try/#0FAehAIAEDMBsHsDuxjQK4DsDGAXAlvBuAEYCGAJgGKZYAUpATgwFzgCCTpAngDwZoBbYgFMGAPgCU4Vhwbces+fyGixY8AG9g4cA2E40DIgG0AugDoshLKRy085ekwkSA3MAC+KdNnyFwDgpi9DJSMprauvqGRKTuXkA).

This is the same code, given the correct signature:
```es6
function badFunc(arr: Array<number>) : Array<number> {
  return [].concat(id(arr));
}

function id<A>(a: A) : A {
  return a;
}
```
Flow also accepts these types. This can be seen [here](https://flow.org/try/#0FAehAIAEDMBsHsDuxjQK4DsDGAXAlvBuAEYCGAJgGKZYAUpATgwFzgCCTpAngDwZoBbYgFMGAPgCU4Vhwbc+gkePABvYOHANhONAyIBtALoA6LISykctPOXpMJEgNzAAvinTZ8hcDZ5sx9DJSMqrqmtq6RKTObkA).

The net result is that the same function is allowed to be given two different type signatures, one which is correct, one which is incorrect.

Removing the call to `id` causes flow to only accept the correct type. If `id` is specialized to operate only on values of type `Array<number>` then the problem persists, as seen [here](https://flow.org/try/#0FAehAIAEDMBsHsDuxjQK4DsDGAXAlvBuAEYCGAJgGKZYAUpATgwFzgCCTpAngDwZoBbYgFMGAPgCU4Vhwbces+fyGixY8AG9g4cA2E40DIgG0AugDoshLKRy085ekwkSA3MAC+KdNnyFwDvQynLzKIuJSwXKhguHqWjp6BkbgpO5eQA) and [here](https://flow.org/try/#0FAehAIAEDMBsHsDuxjQK4DsDGAXAlvBuAEYCGAJgGKZYAUpATgwFzgCCTpAngDwZoBbYgFMGAPgCU4Vhwbc+gkePABvYOHANhONAyIBtALoA6LISykctPOXpMJEgNzAAvinTZ8hcDfozOvPxCopLS7AEKwcpqGlo6euCkzm5AA).

**Comment by vkurchatkin** [comment]
It seems that there is some sort of race condition. If you swap the order of the functions it works fine

**Comment by SamChou19815** [comment]
Now it seems to work
