### ISSUE TITLE
Bound generic types don't warn until used

### ISSUE THREAD

**Issue by amsul** [facebook/flow#5409]
Hi there! Thanks for the awesome library.

I found a small inconvenience when using generic types. This snippet should warn, but doesn't:

```jsx
type NameType = 'user'
type ObjectType<Name: NameType> = {
  name: Name,
}
type UserType = ObjectType<'lol'>
```

..until I try to use it:

```jsx
const user: UserType = {
  name: 'user',
}
```

https://flow.org/try/#0C4TwDgpgBAcghgWwgFXNAvFA5AVwM4QBOWAUKJFAPIBGAVhAMbCqQA88SAXLIimgHxRMAbxJQoAO17cOEADQkAvmTRQAqgUIsMVOo2ZpWWADYB7Y1n4kSAegBUdqDZINTEvMCj4i3DUW1CUKLiUlzY3sQKyvZ2NkA

Not sure how to go about fixing it. But if there are any pointers, I would be glad to submit a PR 🙏

**Comment by SamChou19815** [comment]
It now errors
