### ISSUE TITLE
Does flow restrict type of property value?

### ISSUE THREAD

**Issue by AlexanderShushunov** [facebook/flow#5413]
I have an array of object keys. I have got it by $Keys.
I take a value by one of the keys. Flow infer the type of the value as *any*. But *mixed* (or *string | number* in my case) will be more appropriate and soundness.

[flow.org/try/](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAKuATgM5wB2YAvGAN4A+qYYFAhgLa4BcYp6xAJYUA5gBpmYNiJ6sArhwBGJVAwC+qVAGNK-MNiEV0ANTYw5uUjTAAeACq86agHwAKXEcFZedsWADWuJikvACCxMRsmDYAJADSQaT2zs4AlDTOYKgAkAGJAHQcbNiukizlgZgZYDoU5DC4+fAi7p5YANqVALr5AoIcrqmpZSzD2rro+rhYbLxEZJTWdJLsXLwA5ERY6xIs0rIATAAsqBqoBsImZhakrngzfu3rq7g7YOv7612pANyoQA)

**Comment by SamChou19815** [comment]
this now works, if the bound is set to `{...}`
