### ISSUE TITLE
Large open source project abandoning Flow due to lack of support

### ISSUE THREAD

**Issue by rsolomon** [facebook/flow#5416]
I don't mean for this to be inflammatory, but can someone from your team please weigh in on the issues outlined in https://github.com/mui-org/material-ui/issues/9312#issuecomment-347308524 ?

Flow 0.53.1 effectively removed HoC support by removing the ability to explicitly define `DefaultProps`. This was able to be worked around with `$Diff` until 0.57, which inexplicably enforced a requirement that the original type must contain all types being subtracted from it. The solution is out there, kind of, but it creates a rickety, barely-functional atomsphere that pumps out dozens of errors when a single problem component is introduced into the system.

The issue is further exasperated by https://github.com/facebook/flow/issues/5382 , which prevents even the examples in the docs from functioning properly.

We all understand that bugs happen, but we haven't heard *anything* official about what is planned to be done about these issues. As a user of your lib, it's terrifying to know that, without a roadmap, every single weekly release may deprecate entire codebases and force developers to devote dozens of hours just to conform to breaking changes that add only marginal benefit to the end user.

The release of Fiber was done in a way that prepared users of React over *months* an opportunity to remove use of deprecated APIs. What can be done for Flow to follow the same cadence?

**Comment by vkurchatkin** [comment]
> This was able to be worked around with $Diff

Can you elaborate? #5382 seems to work fine with $Diff

**Comment by rsolomon** [comment]
See https://github.com/mui-org/material-ui/pull/8983 . It required a many thousand line change to support the additional constraints of `$Diff`. It was not possible to incrementally adopt. #5382 is a separate issue from `$Diff` specifically, but adds to the issues around a generic way to type HoCs.
