### ISSUE TITLE
Unclear/misplaced error about type of returned promise

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#542]
If you have this:

```javascript
/* @flow */
function foo() {
  return {a: 5};
}

console.log(foo().b);
```

Then you get a flow error on the `foo().b` part as you'd expect. But if you have a similar error with a Promise-returning function that is annotated to return an untyped `Promise`...

```javascript
/* @flow */

function foo(): Promise {
  return new Promise((resolve, reject) => {
    resolve({a: 5});
  });
}

foo().then(x => {
  console.log(x.b);
});
```

Then you get errors on the lines with `new Promise` and `resolve(` instead:

```
$ flow

/Users/chris/Coding/flow-pr-test/ajax.js:4:10,6:4: constructor call
Error:
/Users/chris/Coding/flow-pr-test/ajax.js:5:13,18: object literal
This type is incompatible with
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_1d25ae62/lib/core.js:345:25,38: union type

Found 1 error
```

This is hopelessly confusing when foo() is being called and mis-used from an entirely different file than it was defined in.

Interestingly, if you remove the type annotation of foo's return value entirely (`function foo(): Promise {` -> `function foo() {`), then the place the function is called (`foo().then(...);`) usefully gets a mention in the error message:

```
$ flow

/Users/chris/Coding/flow-pr-test/ajax.js:9:1,11:2: call of method then
Error:
/Users/chris/Coding/flow-pr-test/ajax.js:5:13,18: object literal
This type is incompatible with
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_1d25ae62/lib/core.js:345:25,38: union type

Found 1 error
```

**Comment by samwgoldman** [comment]
From what I understand, this is a pretty tricky issue, but @bhosmer has been working on improving the error messages. He might appreciate the test case, but I think we should start merging these issue together to keep the conversation in one place.

Other related issues: #501, #411, #409, #341, #324, #251, #202.

**Comment by avikchaudhuri** [comment]
This week I landed a couple of changes that take another (complementary) approach to better error reporting: making annotations more reliable. 

One of those changes fixes this problem. Earlier, : Promise (and any other generic type without type args) implicitly meant : Promise<T> for some T waiting to be inferred, and that caused a lot of confusing error messages around generics. Now, : Promise means : Promise<any> (and similarly, when you leave out a type arg when using a generic type in an annotation, it's always `any`), so you won't get any error in your example. 

This fits general intuition in a lot of cases: e.g., you'd expect Array<S> for any S to be  a subtype of Array, and it is so with Array<any> but not Array<T> for some fixed T. 

Now, if you do add an explicit type arg:
```
/* @flow */

function foo(): Promise<{a: number}> {
  return new Promise((resolve, reject) => {
    resolve({a: 5});
  });
}

foo().then(x => {
  console.log(x.b);
});
```

you get a good error message:

```
/home/avik/issue-542/test.js:9:1,11:2: call of method then
Error:
/home/avik/issue-542/test.js:10:15,17: property b
Property not found in
/home/avik/issue-542/test.js:3:25,35: object type
```
