### ISSUE TITLE
RFC: all=true should not affect [libs]

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5421]
When using `all=true` in my project, I'm forced to put every non-Flow dependency under `[ignore]` to avoid Flow eating up all of my RAM.

To fix that, I suggest altering the behavior of `[libs]`. Any directory under `[libs]` will not have `all=true` applied to it, unless it has `all=true` in its own `.flowconfig` file (#238).

Then I could put `./node_modules` under `[libs]` and not worry about any large dependencies (like `babel`) being parsed by Flow.

**Comment by aleclarson** [comment]
Also, `[libs]` behavior would need to override `[include]` since the project root is auto-included. Another option is to add an option for preventing the project root from being auto-included (#5418).

**Comment by aleclarson** [comment]
I can't use `all=true` until the current behavior is fixed, so I'll have to put `// @flow` at the top of every flow-typed `.js` file.

**Comment by danloiterton** [comment]
I just came across this same issue. I wanted to add flow to my whole codebase on a fairly new project so we don't have to remember to annotate the top of every file. So I added `all=true` to the `[options]` in `.flowconfig` 

...a few minutes later my computer crashed!

**Comment by willisplummer** [comment]
I'm running into the same issue. Any updates?

**Comment by SamChou19815** [comment]
Closing since node_modules should not go into libs. It should go into [declarations]
