### ISSUE TITLE
Arrow function with closure fails to track generic type (statement function works)

### ISSUE THREAD

**Issue by pascallaprade** [facebook/flow#5423]
I wrote the two same functions, one as an arrow function, and the other as a statement with the 'function' keyword.

The function takes a generic input to determine the type of a function it will be provided (that will itself be provided with the data itself) and returns a function that will call that function, receiving itself the data to provide.

Here is some sample code:

```typescript
// Outputs:
// "string literal `A` (This type is incompatible with the expected param type of some incompatible instantiation of `D`)"
// and
// "string literal `B` (This type is incompatible with the expected param type of some incompatible instantiation of `D`)"
const version1: <D : DataType>(strategy: Strategy<D>) => (data: D) => string =
  strategy => data => strategy(data)

// Does not output errors (as I would expect).
function version2<D : DataType>(strategy: Strategy<D>): (data: D) => string {
  return data => strategy(data)
}
```

With the statement function, the function declaration works fine, no error is outputed, and trying to call it produces the expected warnings.

But when I write the same function with an arrow function being assigned to a 'const', I get an error on the call of the first parameter in my closure, saying the parameter of the second function is incompatible with some instantiations of the function.

Since that type is specified as a generic parameter, and that I'm using the same type for my closure, I would expect this not to give errors, as the same statement function does.

Also, even if I get an error in the version 1, calling it still works as expected, meaning that it recognizes type mismatches between the parameters of the main function and the returned closure's parameter.

Please find a (really simple) version of that problem, complete with all definitions and test calls, here:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAiAhhsQCq4EC8YA5AIJ1gA+9AQnetvmAMoYATqTwBzLAB5CYAFxFSFKgD4wtABQATBXMIBKVSoDOQgJYA7Udyr8hI8Q1U3hGMZMZ0lmawOev2jnzs3Tk9UAGM4M2MwY197OUCXe0ctMgMwVOIwYGB6JnDI6Nig9gTbJKx-Wkz0mpyOLlR6gHkAVwwcdsMZJtyAIljzUTAYExdhGDAAAwYpsDVyAAsTQzAeAhWwcwiAWxxSEwAjGAIEMcW1xYI8AA98MJcNMH3hHbXrOCgYuB2Ns139hgjictlEyGYgQdImBPtNCFNdH1emBiGYNMiBqYLCMxngJtN2HMFstVustqttj9AcDTudLtc7ngHngni9iG8ybDDD8-gCDsc-sZUZCgdDYVN4YiCmCwAA3PGGEyRACMciksnkZEo+CUamKFTKcUkhCU+moKk02iIZqMWOG1FQYBi5VctQU6X1rktZF06HqhDgeFWZjgGBh7U6YbxgjgglWamIqwAkmAEHBWjAnrd7hhdAA6VBQVr-UVmOUKpVmABM6p0Cm1eF1nvEhqCUlNcm9xB0NudgiGYAA3o6wII8BhWoIyzVzX2gl3fQBfP25ACi8sEWDAYWIMEmacEAGt47GwFBiCYYIZ9ImwNmmY8ADRgENgHakcb0u+CGNxsCiEx5TLYhDjgeUeg3RUVT1F17F0NR3F9SDK2VGCjXYeDENQZDoObLAGEwzgkIrXDYMqQi6F9bCSOrNCggIhCmGIuNKyrOiKgwxjKOoljIjYvCGLoIieKg2i8M4oTuKAA

(Please note: in this simple example, the Strategy type and the closure type coincide, but it's really to keep the example simple. In practice, the faulty function serves to simplify usage of said Strategy by centralizing more of its parameters in the first function call, returning a very easy to use closure. However, with more parameters, I get the exact same error. I simplified it to make sure of what was the problem, and to keep the example simple as said above.)

**Comment by aliceklipper** [comment]
You can rewrite the second example as an arrow function:

````javascript
// No error
const f = <A, B>(f: A => B): (A => B) => a => f(a);

// Error
const g: <A, B>(A => B) => A => B = f => a => f(a);
````

But you have to annotate the function itself, not a variable.

**Comment by pascallaprade** [comment]
Yes, thank you! It seems like the version with the annotated function works!

Is there any reason why assigning a function litteral to a typed variable does not work? Because the variable type I gave in the example above does still work with your answer:

```typescript
// No error either
const version3: <D : DataType>(strategy: Strategy<D>) => (data: D) => string =
  <D : DataType>(strategy: Strategy<D>): (D => string) => (data: D) => strategy(data)
```

It feels to me like Flow should be able to figure out `version1`'s assignment was as valid as the `version3`'s, which works properly...

Clearly, the type signature in `version1` is compatible with the assignment, even though the assigned function is not explicitely typed like in `version3`.

Maybe it's designed like this and this is expected and all, but still, as a user, I don't see why `version1` should not work within the type system.

At the very least, maybe the error message could be improved to better point that some part of the assignment's type does not match the type declaration? At the moment, I get two separate errors, one for each case of the type union, that tells me that part of the union is incompatible with D (which is of the union type), which I find very confusing.

Here is the updated example with fully typed `version3`: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAiAhhsQCq4EC8YA5AIJ1gA+9AQnetvmAMoYATqTwBzLAB5CYAFxFSFKgD4wtABQATBXMIBKVSoDOQgJYA7Udyr8hI8Q1U3hGMZMZ0lmawOev2jnzs3Tk9UAGM4M2MwY197OUCXe0ctMgMwVOIwYGB6JnDI6Nig9gTbJKx-Wkz0mpyOLlR6gHkAVwwcdsMZJtyAIljzUTAYExdhGDAAAwYpsDVyAAsTQzAeAhWwcwiAWxxSEwAjGAIEMcW1xYI8AA98MJcNMH3hHbXrOCgYuB2Ns139hgjictlEyGYgQdImBPtNCFNdH1emBiGYNMiBqYLCMxngJtN2HMFstVustqttj9AcDTudLtc7ngHngni9iG8ybDDD8-gCDsc-sZUZCgdDYVN4YiCmCwAA3PGGEyRACMciksnkZEo+CUamKFTKcUkhCU+moKk02iIZqMWOG1FQYBi5VctQU6X1rktZF06HqhDgeFWZjgGBh7U6YbxgjgglWamIqwAkmAEHBWjAnrd7hhdAA6VBQVr-UVmOUKpVmABM6p0Cm1eF1nvEhqCUlNcm9xB0NudgiGYAA3o6wII8BhWoIyzVzX2gl3fQBfEfS6LyuOVgDMaukda1yj1LpbTjbJt7XZ7HrtqhHtc1ih1h6NrYq7d0neks8GFnPmUvX6PLAFz9XIAFF1ywMAwmIGBJjTQQAGt41jMAoGIEwYEMfREzAbMmUeAAaMAQzAHZSHGelcMEGM4zAUQTHlMtiEOOB5R6ddFRVJ8ggYXQ1HcX0OMrZVuIqdg+IE1AhK45ssF4-jOEEisZMA8SFLoX0pOU6tRNceTJOknTZLUgztKrXT7AkxStI3SJzOMqyNPQQzNwsuSJKYJTbLMVyHP4zybM4ny3P06yXLckzrKAA

**Comment by aliceklipper** [comment]
@pascallaprade, you haven't to annotate **all** functions, only first one. Also, you haven't to annotate the variable. These annotations are redundant. Simplified example also works as expected:

````javascript
type DataType = 'A' | 'B'

type Strategy<D : DataType> = (data: D) => string

type StrategyA = Strategy<'A'>
type StrategyB = Strategy<'B'>

const strategyA: StrategyA = data => data // 'A'
const strategyB: StrategyB = data => data // 'B'
  
const version3 = <D : DataType>(strategy: Strategy<D>): (D => string) => data => strategy(data)

version3(strategyA)('A') // No error
version3(strategyB)('A') // Error
version3(strategyA)('B') // Error
version3(strategyB)('B') // No error
````

[REPL link](https://goo.gl/mCivhN)

**Comment by SamChou19815** [comment]
Now the behaviors are consistent
