### ISSUE TITLE
Flow not stripping class property annotations

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5426]
![](https://i.imgur.com/fGhpjT7.png)

Here's my `.babelrc`:

```json
{ "presets": ["flow", "es2015"] }
```

How can I strip the `meta: Object;` annotation?

**Comment by aleclarson** [comment]
The workaround for this (not pretty):
```js
export default class Project { /*::
  meta: Object; */
}
```

**Comment by Brianzchen** [comment]
Works in current version, tested 0.134.0
https://flow.org/try/#0KYDwDg9gTgLgBAE2AMwIYFcA28DGnUDOBcAClBAFbA7wDeAUHE3ALbAyoBccA8gEZUaAbnoBfIA
