### ISSUE TITLE
boolean can't be coerced into a string?

### ISSUE THREAD

**Issue by aleclarson** [facebook/flow#5427]
```js
function foo(recursive: boolean): void {
  console.log(`foo: ${recursive}`) // Error: This type cannot be coerced into a string
}
```

Is this kind of restriction really necessary?

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2549

**Comment by aleclarson** [comment]
I get why `const str2: string = (str: string) + (bool: boolean)` should be prevented, but perhaps template strings should allow implicit type-casting for primitive values.

What do you think, @vkurchatkin?
