### ISSUE TITLE
Errors with no call site in newest flow

### ISSUE THREAD

**Issue by Alxandr** [facebook/flow#5428]
I just updated to flow 0.59.0, and the result was a bunch of the following errors:

![image](https://user-images.githubusercontent.com/112334/33382443-0bf8d942-d521-11e7-9f60-9bea0ee7c811.png)

I have no clue what is causing them, where they are originating from, or what I can do to fix this. I've been going around in my code trying to type things that use the function it's complaining about, and this does not help.

The function in question is defined as following:

```js
function object<S: { +[name: string]: ArbGen<*> }>(
  map: S
): ArbGen<$ObjMap<S, <V>(v: ArbGen<V>) => V>> { /* implementation */ }
```

I'm unable to produce a minimal example that shows this problem, because I have no clue what's causing it. I just know this used to work in flow `0.56.0`.

**[Edit]**  
I just tested on older flow versions, and this broke in `0.57.1`. There is a very good chance that this is an issue in my code, I just don't know how to find it, nor fix it, cause I'm getting next to no error information.

**Comment by apsavin** [comment]
Maybe related to https://github.com/facebook/flow/issues/2674#issuecomment-344714624 ?

**Comment by Alxandr** [comment]
I remember looking at that issue before I started writing this library at all, and I'm pretty sure that had already been fixed, but I might remember wrong.

**Comment by Alxandr** [comment]
I managed to make a somewhat minimal reproduction. Maybe someone can tell me what is wrong [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgCC2ARgOIoB2APANQAqAfKALygDeiooAOYpcAZQCWdQdBQAKAJQAuUCwA0iAL4BuZABMUAY2gBDbKUgBXOgdzjYdUAC9xGAPKUAVodyzYy43SEqqAY2LAYAM7KACQASijGuq500IQU2MaEDBG42JKCbEqgAYQ6iPpGpqToWHiglta29qAGsAC2lJLGTXQRsgB0g6aUUaBxCUkpadgZWRQ09AwAVGyFyvO0jOOJyanpmQwlq2UVJmagNTj4DTZ2DrCe3gyiyjygTADadMZtKMo5eSkAF11lRNssOBo2LI2sYMMpREUNotou4PABZOHPYIMABq0IAbqCFox8fIuBx8WwToYzqQCaZisJieC6BYOihsNTyrSqqAGdhQN9fizFgD8tzEEQSKAAAqciLNbhvYzMoXsyicrRCn5-UDiqSgbSIVq9fDwuUKpWgB5eGyyPgCVUodQCYUoTTyfrCMT5GQKLRAA):

```js
// @flow

export type ArbGen<+T> = {
  getSingle(): T,
};

declare function zipObject(o: any, props: $ReadOnlyArray<string>): any;

declare export function combinations(...arbs: $ReadOnlyArray<ArbGen<*>>): ArbGen<$ReadOnlyArray<any>>;

declare export function object<S: { +[name: string]: ArbGen<*> }>(map: S): ArbGen<$ObjMap<S, <V>(v: ArbGen<V>) => V>>;

declare var age: ArbGen<number>;
declare var name: ArbGen<string>;

type Person = { age: number; name: string };
const p: Person = object({
  age,
  name
}).getSingle();
```

**Comment by samwgoldman** [comment]
I was able to work around this by replacing `*` with `mixed`. The behavior of `*` can be pretty surprising, and while I'm not sure exactly what is happening here, I think the solution is just to avoid `*` here.

**Comment by Alxandr** [comment]
I still don't think this issue should be closed, because the bigger issue is the fact that the error does not provide any information about what is actually wrong, nor how to fix it. And this clearly seems like a bug, no?
