### ISSUE TITLE
Flow-typed objects destroy autocomplete capability in all editors

### ISSUE THREAD

**Issue by soosap** [facebook/flow#5431]
In my case I am using objects as enums.

**Untyped universe**

![image](https://user-images.githubusercontent.com/7187705/33388710-f80a08e2-d530-11e7-82e3-24929002597b.png)
This particular enum constraints the valid set of screens to which I could route to in my app. It allows me to use it elsewhere in my app like this:
![image](https://user-images.githubusercontent.com/7187705/33388812-3ceb24f0-d531-11e7-9d29-efba223a2518.png)

**FlowTyped universe**

Leveraging FlowType is powerful. Now when I try to reference a invalid key in my enum, I immediately get a flow warning. I mean here it seems pointless, but in my app structure flow types are defined in a standalone file.
![image](https://user-images.githubusercontent.com/7187705/33388888-81bec000-d531-11e7-9e05-3c8068f93e94.png)

That blessing, however, comes at a very high cost: I lose the autocomplete results no matter what editor I use (tested on atom and vscode). **NO MORE AUTOCOMPLETE**
![image](https://user-images.githubusercontent.com/7187705/33388983-c9dc5df2-d531-11e7-8c11-3bc1c720e821.png)

Why is it that flow-typed objects lose the autocomplete capability? I was not sure where was the right place to post this. Since it did not work for neither atom nor vscode, I thought I start here to ask for guidance.

**Comment by apsavin** [comment]
PhpStorm:

![2017-11-30 10 35 56](https://user-images.githubusercontent.com/632171/33419167-51c65e92-d5ba-11e7-9386-decb6c5e0b84.png)

![2017-11-30 10 35 14](https://user-images.githubusercontent.com/632171/33419169-576137aa-d5ba-11e7-8429-3d912164a72a.png)

Works as expected.
So it seems that the issue isn't related to flow itself and you should address it to the developers of editors.

**Comment by soosap** [comment]
Thanks for investigating. I posted this over here https://github.com/flowtype/flow-for-vscode/issues/188
