### ISSUE TITLE
Bug: Spreading of exact intersection ignores intersected type

### ISSUE THREAD

**Issue by 0x24a537r9** [facebook/flow#5433]
https://flow.org/try/#0C4TwDgpgBAGlC8UDeBDAXFARge2wGwhQDsBfAbgChRIoBNBZAHwDpWASAUQA8UBjYADwAKOADJkmDDnyFSASgB8jchQoFgUEBnqIhSEhmIg5lEMxQMAZijwBnCKeaYrN+2ShQA9J6gAxPNgA7lAAJtgQtkQA5BoA1kRBUCg4AK4amAD8FEA

```js
type X = {a: boolean};
type Y = {|...$Exact<(X & {b: boolean})>|};

let y: Y = ({}: any);
y.a = false;
y.b = false;  // Flow doesn't know about b?
```

Per Caleb: "Object type intersection should be as simple as “merge the fields,” but our implementation of intersections uses a set of higher level typing rules that sometimes break in edge-cases like this"

**Comment by SamChou19815** [comment]
While we should error on exact intersections, the behavior seems to be expected that exact intersections, which should be empty, shouldn't work
