### ISSUE TITLE
How flow resolves types?

### ISSUE THREAD

**Issue by Diokuz** [facebook/flow#5435]
Im working on my _js_ library, annotated with flow. It is a _private library_, so I cant make a _pr_ to https://github.com/flowtype/flow-typed

What is an official way to supply a library with _flow types_? I want my users to be able to import them. Like that:

```
import type { MyType } from 'my-private-library'
```

I can place all my types to `node_modules/my-private-library/index.js` file (as described in [Flow Module Types](https://flow.org/en/docs/types/modules/)), but that way seems pretty hacky.

I found out (https://github.com/facebook/react/issues/11680) that flow, somehow, resolves `import type { ComponentType } from 'react'` as https://github.com/facebook/flow/blob/master/lib/react.js, which not placed in `node_modules/react`, actually.

So, how flow resolves _type imports_? How can I make it resolve `from 'my-private-library'` as `node_modules/my-private-library/src/types.js` for example?

**Comment by TrySound** [comment]
@Diokuz Just place it according `package.json` `main` field but with `.js.flow` extension.
https://unpkg.com/derivable@2.0.0-beta.2/dist/

**Comment by TrySound** [comment]
React definitions are built in flow binary

**Comment by Diokuz** [comment]
> @Diokuz Just place it according package.json main field but with .js.flow extension.
https://unpkg.com/derivable@2.0.0-beta.2/dist/

@TrySound is that an official way? Cannot find that way in the docs https://flow.org/en/docs/config/libs/
Will flow always consider `%main%.flow.js` as a libdef default source, as well as `/type-flow` directory, and directories from `[libs]` section of _.flowconfig_ file?

**Comment by Diokuz** [comment]
Okay, I found TODO guy here :) https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-module

**Comment by TrySound** [comment]
It's not about only main. All files with flow extension will be preferred over non flow files in the same directory.
