### ISSUE TITLE
Union type resolution error

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#5438]
```
// @flow

export type Location = { city: string } | { country: [string, string] };

const b: Location = { country: ["Sweden", "Malmo"] };

if(b.country) {
  const pair = b.country;
  const [_1, _2] = pair; 
}
```

Emits two errors:

```
9:   const [_1, _2] = pair; 
            ^ element 0. Computed property/element cannot be accessed on
9:   const [_1, _2] = pair; 
                      ^ property `country` of unknown type
9:   const [_1, _2] = pair; 
                ^ element 1. Computed property/element cannot be accessed on
9:   const [_1, _2] = pair; 
                      ^ property `country` of unknown type
```

The union type has distinct set of keys used for each variation. How can one get around that without going through `any`?

**Comment by apsavin** [comment]
[Corrected code](https://flow.org/try/#0C4TwDgpgBAMg9gYwIbAJZwHZQLxQN4A+UCqoAXFAM7ABOqGA5lAQL7P5EJwCuGtIFANrU6jADRVa9BgF1mLANwAoJVwzUoAIwrxkaTDnzEefGgKiCARAGUA7hAAmEDJYmWAskgA2AWziW5RRVUADMACk0AOi5efgBKfCUoY3VgKDAkVBpDKJjTEGVktQ1BAH0ARglSgCY5XAyshSglFiA)

[Docs](https://flow.org/en/docs/types/unions/#toc-unions-refinements)

**Comment by pronebird** [comment]
@apsavin ah thanks a lot! I didn't realize using exact `{| .. |}` would refine the union! 🎉
