### ISSUE TITLE
bug with union types and closures combination.

### ISSUE THREAD

**Issue by tal952** [facebook/flow#5440]
Hey, there is a bug with union types and closures:

``` javascript
/* @flow */

type VisualData = (
    { type: "Type1" } |
    { type: "Type2", id: number, data:number[]});

function foo(item: VisualData) {
  if (item.type === 'Type1') {
    return 'Type1';
  }
  
  // property `id` found
  const id = item.id;
  
  // property `id` not found
  item.data.map(x=>item.id);   
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBqAlgM4CuAhjACKUaVgC8YAFKmJ2AN5jb4AuMACIAKrjwBGYWAC+YAD4cuvfniFiJAJmEAaMMQAmQgHbkAtgCM8AJ32H6lAWau2A2gF1ZASgDc6KHITAGMMYjgTMCg4OFZiDDxzIRIKajoGbx5lYig2eMSAOjVmJhYAcnF8STLM7mVOGzwMchtIiolq-05ZZWVgYDAcGzh8G2wwAAMjCai4IMNlYIjSDANDZgME8wKjLrA+gaGR23GpwxmTOFXo+eytgocGAvNKHFYADyYAPnztoz8uKhZEA

**Comment by jcready** [comment]
This is because `item` is not a constant and can therefore be reassigned when `item.data.map()` is called. If you make `item` a constant then the error goes away.

```js
function foo(i: VisualData) {
  const item = i;
  if (item.type === 'Type1') {
    return 'Type1';
  }
  
  // property `id` found
  const id = item.id;
  
  // property `id` found
  item.data.map(x=>item.id);
}
```

**Comment by tal952** [comment]
Can you please give an example of such reassignment?
