### ISSUE TITLE
BUG: Can only check one instance property for presence

### ISSUE THREAD

**Issue by AlexJWayne** [facebook/flow#5441]
If you have a method that validates existence of more than one instance property, only one of them seems to remember it's been checked.

```js
class SomeClass {
  foo: ?string
  bar: ?string

  constructor(foo: ?string, bar: ?string) {
    this.foo = foo
    this.bar = bar
  }

  method() {
    if (!this.foo) return
    if (!this.bar) return
    this.foo.toUpperCase() // Works
    this.bar.toUpperCase() // Error!
    //       ^ call of method `toUpperCase`. Method cannot be called on possibly undefined value
  }
}
```

[Try Flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToDKsBbAUwGENtQBvRUUSWWALlAH5MAXAJwEsA7AcxqgARuk7M2XPoKEpYvDpwCuKdrE4AKek1aLpAGhFiJegQEoqQ2uwAW3TADptoALx0GV0LfsPRnV0acQgC+yLTEtrAAJhoW1LS03JCgGgCE3o7aFpxE7EqcvJ5JKel2jn7ZufmFCV5lTgwOagCqAA6tRJwkWESxoCCgAOrqANaYnhm+Yk2wbR1dPX0DAKIASqsA8qupIYihyAPwo+PQue46kjwCiKfsgSZS15BKvKrc8nS8ffGgxWlZoByeQKQj+qQqgKqINo2hmc063UwvQsA2GnDGQj8cPaCMWKLAaIxwSAA)

However, this does work as expected with simple variables.

```js
// works
let foo: ?string
let bar: ?string
function fn() {
  if (!foo) return
  if (!bar) return
  foo.toUpperCase() // Works
  bar.toUpperCase() // Works
}
```

What's odd is that this first one you try to _use_ works (not the first one you check). Change which property you access first after the check and a different property will be `maybe` typed.

**Comment by apsavin** [comment]
#5732

**Comment by Squeegy** [comment]
Oh, so this is a feature? 

But why does that second example work? what if `foo.toUpperCase()` contained `bar = null`?

**Comment by jesseschalken** [comment]
The second example works because they're local variables and Flow has determined that `foo.toUpperCase()` couldn't possibly have assigned a falsy value to `bar`. In the first example they were properties of `this` instead of local variables, and Flow couldn't guarantee that the call to `this.foo.toUpperCase()` wouldn't assign a falsy value to `this.bar`, since `this` could potentially be shared with the implementation of `toUpperCase()`.

**Comment by jesseschalken** [comment]
That said, I'm surprised this passes:

```js
let bar: ?string = null

function fn() {
  if (!bar) return
  zoo()
  bar.toUpperCase() // Works
}

function zoo() {
  bar = null
}
```

**Comment by SamChou19815** [comment]
Now everything is working as expected.
