### ISSUE TITLE
flow playground - doesn't expose DOM globals

### ISSUE THREAD

**Issue by Hotell** [facebook/flow#5442]
DOM globals are undefined within playground
```
            ^ identifier `HTMLElement`. Could not resolve name
```
and so on...

[DEMO](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgMIFcDOYD2BbAUQBsI8JwCA3csAeQAcxgcRNkBvAKGWQCN1evEpgBcfHDhJwQAbm7IE0pEThCIY3hKmz5CfPRyYIAEw1aI0uT2MQwcYEQD8YyjmDHkAH2S1eAKwgEMDkAX3lOMABPehQMbHxiUhoqGmQAXjQsXEJqcGQAMg5dfUMTZ3FJCxAAGmK8AyNjAAU4MAALcoAKAEp0gD5kAEEoKDhIgB4AORwbPs4Qq2RwvVYwZBsYUUz4whIyCly6RmZWdKKefkFhMTAodAhankUQZVUSG7uHuoaTMXgiIzzOScGDoF5MFjIUjAMCdeQQPZiAASABUALIAGUS+zAj2QIDgZDE2CgoAA5nicIwtnFstjkocGBDWJxumZKtJzgoWNgoYzjjyzuxkAA6MUbTDVUViqlgNgLeQkNbqbZ0vYMmiLYAwZCdADkenqpWMeuQoFVCUOIvoUBwuCiMV6XB4PBQGRAEAA7hacjROgSyFKIPzmZhuosQlCAShnS63brjDgEOgcSKEFALJAUuB9bTLTQ9WyffSDjRw-JXSLQDC876cwGHnyaEyTpgRZc1JKm+AWzy00oEW9G8HmwLWCKbHYHOWXT5-IEwBOIDBQBAmraYlAop1GwaSo09VLhZQ4ER7mIRz2x23DT8PCEZ8gwjwM2B0FAQFHSBPgJh6K0EDabNYQgcsQiAA)

**Comment by Brianzchen** [comment]
This is intentionally missing for performance reasons. I don't think there are any plans currently to put this back in. Your work around would have to be running tests on a `test.js` file in your project as a playground when you need these kinds of objects.

**Comment by SamChou19815** [comment]
Closing due to the reason described above. One day we might add them, but not via including them in a hardcoded way, but more like TS playground's automatic type acquisition
