### ISSUE TITLE
Flow 0.60[.1] breaks IDEs (at least Atom and WebStorm)

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5444]
Atom works with 0.59 but not with 0.60:
https://stackoverflow.com/questions/47599966/cant-get-flow-working-with-atom

WebStorm works with 0.59 but not with 0.60:
https://youtrack.jetbrains.com/issue/WEB-30020

**Comment by steida** [comment]
It seems it's already fixed. Hope they release flow-bin soon. cc @calebmer

**Comment by lvdang** [comment]
@lll000111  are you able to get flow working webstorm for 60.1? I am getting "Error: process terminated" in Web Storm. I was getting same error as you for 60.0

**Comment by lll000111** [comment]
@lvdang I was suspicious of that tiny patch (I looked at the change in 0.60.1) and it indeed does not address this issue.

**Comment by erezbaum** [comment]
v060.1 and IntelliJ IDEA 2017.3 (Ultimate Edition) Build #IU-173.3727.127
seeing the same problem,.

**Comment by Meeeeow** [comment]
Downgrade not work for me, WebStorm 2017.3 Build #WS-173.3727.108

**Comment by evrimfeyyaz** [comment]
RubyMine Build #RM-173.3727.132. I tried Flow 60, 59 and 55, none worked.

**Comment by lll000111** [comment]
@Meeeeow @evrimfeyyaz Pls. define "does not work". This does not look like this particular problem I reported right here, which only occurred from 0.60. Check the linked error descriptions.

**Comment by Meeeeow** [comment]
@lll000111 Updated, but useless, i can't reproduce it in command line, looks like a bug of JetBrains IDE itself

**Comment by lll000111** [comment]
@Meeeeow Consider adding to the linked WebStorm ticket. Check if there is anything in the log (Help => Show Log in Explorer => ìdea.log`).

**Comment by Meeeeow** [comment]
@lll000111 My bad, it's looks like another bug of WebStorm. it can't understand OCaml regular expressions in `.flowconfig`?

```ocaml
.*/node_modules/.*
```

**Comment by lll000111** [comment]
@Meeeeow I'm not sure WebStorm reads `.flowconfig`. I don't think it does.

**Comment by jesseschalken** [comment]
Both 0.60.0 and 0.60.1 are broken in Atom and WebStorm for me as well. 0.59.0 works fine.

**Comment by lvdang** [comment]
I wonder if Facebook/Flow developers are aware of this issue. If they are using IJ or WebStorm with v60.0 and v60.1, the Flow developers should also see this issue.

**Comment by steida** [comment]
Atom works for me. With Nuclide.

**Comment by lvdang** [comment]
[https://youtrack.jetbrains.com/issue/WEB-30020](url)

**Comment by lll000111** [comment]
@lvdang 

1) your URL is broken (the text is okay, the underlying link is not)
2) that link already is at the very top in my very first post

**Comment by lvdang** [comment]
thanks for clarification

**Comment by thomasfr** [comment]
I can also confirm that this breaks with 0.60.0 and 0.60.1 with latest WebStorm version 2017.3:
```
WebStorm 2017.3
Build #WS-173.3727.108, built on November 25, 2017
JRE: 1.8.0_152-release-1024-b6 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Mac OS X 10.13.1
```

**Comment by lll000111** [comment]
FYI: The state of the WebStorm ticket has been changed to "fixed" (there is no new version available yet, obviously, probably in an upcoming EAP and then a patch for 2017.3).

**Comment by lvdang** [comment]
I updated v61.0 still getting: Error:Timeout on starting language service process

with latest WebStorm. Hopefully WebStorm has patch to fix this issue.

**Comment by yamov** [comment]
WebStorm has released an update https://confluence.jetbrains.com/display/WI/WebStorm+173.3942.31+Release+Notes
Works for me with Flow 0.60.1

**Comment by oriSomething** [comment]
Is there any new, we've tried Flow 0.64 with the latest WebStorm (2017.3.3), and it doesn't works.
It prevents us from upgrading Flow because some of the team uses WebStorm :(

**Comment by lll000111** [comment]
@oriSomething I'm using Flow 0.64 and [the 2018.1 EAP](https://blog.jetbrains.com/webstorm/) without problems. The last official release works too, that's what I used before upgrading to the EAP.

**Comment by oriSomething** [comment]
@lll000111 Interesting, Because it doesn't work for me and 2 of my co-workers. But I see what you're talking is a new version that WebStorm doesn't show me that there is an update :(

Thanks!

**Comment by lll000111** [comment]
@oriSomething As I said, the last official version worked for me too. I think that was 2017.3.3. It defintiely worked &mdash; apart from the crashes of the Flow server on Windows, [but they are a Flow bug](https://github.com/facebook/flow/issues/5583).

**Comment by lll000111** [comment]
I'm closing this issue because it's been working with the last few Webstorm releases (incl. EAPs). the remaining issue #5583 is Flow crashing regularly (on Windows systems at least) which the IDE can do nothing about.

**Comment by DerKobe** [comment]
I chose a different node version in the ESLint settings panel of WebStorm and now it works fine again.
