### ISSUE TITLE
Getting : Error: Process terminated in WebStorm IDE on version 60.1

### ISSUE THREAD

**Issue by lvdang** [facebook/flow#5447]
If this is a bug, please try reproducing using https://flow.org/try/.
Getting : Error: Process terminated in WebStorm IDE on version 60.1

Anyone else getting this error?

**Comment by lvdang** [comment]
I am on the most recent update of WebStorm: #WS-173.3727.108, Flow v.59 works fine. 
v60 and v60.1 causing Web Storm issues.

**Comment by lll000111** [comment]
Duplicates https://github.com/facebook/flow/issues/5444

**Comment by erezbaum** [comment]
v060.1 and IntelliJ IDEA 2017.3 (Ultimate Edition) Build #IU-173.3727.127
seeing the same problem,.
