### ISSUE TITLE
[0.60] Rest of destructuring TypeAlias not considered to be same type

### ISSUE THREAD

**Issue by danez** [facebook/flow#5449]
This was working before, but now started breaking with 0.60

https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBqBDANgSwCYYzB4DyYMOEAdgM5wC8cA3gD4BQccAxgO54D8ALjg0YUHFQDmAGg5wwGGjQAKwKMqjAawGELgAjCBCzAMVWSwC+AbjZ2AZgFcqXCtTj2shIlQCCUSUcAW2AqGBoyN1plDFgaAAoIchphTFwCIlJySloASmEANwh8ZjkualFSzk4FJVV1TW0YWWq4ADoOpKiaOUsGOC6aWzkDRxwsPH9AkLCaAEkiIMTsitzbSzs2Jxco0fHJgODQ8IXgJa6clPRsfEJiSMv8uCKSpksgA

```js
export type ValidatedOptions = {|
  cwd?: string,
  passPerPreset?: boolean,
|};


function flattenArgumentsOptionsParts(opts: ValidatedOptions): void {
  const {
    passPerPreset,
    ...options
  } = opts;

   buildArgumentsItem(options);
}


function buildArgumentsItem(options: ValidatedOptions): void {}
```

**Comment by lone-star** [comment]
👍 
Having similar issue. This example also fails from 0.60, onwards: https://flow.org/en/docs/types/utilities/#toc-rest

Test here: https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbygOwIYC2EAXFMsHAJY4DmANFHjSbgK4EBGEcUAvgNwAoQQGMEOclDCIUpeElQZM+IqQDkAKXFqGTFgBYATANHjJmPQwB0NhMAAW3eSl7opM5EIAUdx3GfIpAAkAEoQ5AA8AQyYAD56pDjsXHCxvAB8AJT8QA

**Comment by carmanchris31** [comment]
Similar, possibly related issue:

```js
type StringMap = {
  [key: string]: string;
};

function test(params: StringMap) {
  const {
    a,
    ...rest
  } = params;
  
  if (params.b !== undefined) {
    // This works as expected
  }

  if (rest.b !== undefined) {
    // This should work the same way
  }
  
  if (rest.a) { // $ExpectError
    // This wouldn't ever happen
  }
}
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQE4CWAdgOYCyAhhqALygDeiooA2gNZZoBcoAzoVJkAun0HFyAbkQBfGYkgBXEgGMURWCVAosggBQYqBKgFt+ffJMo0AlExahVWwQ9asqAGkesAdP4I9FEdZelAjE3MZVkciSFBDYzN+XwAjUABCOgYVABMsSFIsXPtmd1AQUAAVAAsiflB4WAIOBqoGrAAPbHVikORWOITAwTTM7NA8gqKSt3dK2vqBGtglaFzG5o4dGpx+Mxx4KjR+mMH4-RGUXypSirAAEgBRbqx1J4ICZp976rqGpprXIkADkKFAWAAblgCKAajRsCR+rJEEA
