### ISSUE TITLE
Strange errors with EventEmmiter and Promise combination

### ISSUE THREAD

**Issue by karelbilek** [facebook/flow#545]
My application is throwing a strange flow error that I cannot debug, or find a reason of.

The code of is as follows

```
import {EventEmitter} from 'events'; // given using browserify

class Foo extends EventEmitter {
}

function experiment(): Promise<Foo> {
    var foo: Foo = new Foo();
    var res: Promise<Foo> = Promise.resolve(foo);
    return res;
}
```

This produces the following error

> (...): Foo
> This type is incompatible with
> /tmp/flow/flowlib_10182f91/lib/core.js:337:1,364:1: Promise

What is going on?

**Comment by runn1ng** [comment]
Interestingly, this code seems to work

    function experiment(): Promise<Array<Foo>> {
        var foo: Foo = new Foo();
        var arrfoo: Array<Foo> = [foo];
        var res: Promise<Array<Foo>> = Promise.resolve(arrfoo);
        return res;
    }

**Comment by samwgoldman** [comment]
I can reproduce this and if seems like a bug. It's particularly curious that this bug seems to depend on the type parameter to `Promise` being imported. If I inline the class declaration into `Foo`, there is no error:

```javascript
/* @flow */

declare class Foo {
  static listenerCount(emitter: events$EventEmitter, event: string): number;

  addListener(event: string, listener: Function): Foo;
  emit(event: string, ...args:Array<any>): boolean;
  listeners(event: string): Array<Function>;
  on(event: string, listener: Function): Foo;
  once(event: string, listener: Function): Foo;
  removeAllListeners(event?: string): Foo;
  removeListener(event: string, listener: Function): Foo;
  setMaxListeners(n: number): void;
}

function experiment(): Promise<Foo> {
  var foo: Foo = new Foo();
  var res: Promise<Foo> = Promise.resolve(foo);
  return res;
}
```

The above is OK.

**Comment by avikchaudhuri** [comment]
Interesting, thanks @runn1ng for the repro and @samwgoldman for the additional analysis!

**Comment by AgentME** [comment]
Here's another mostly similar reproduction case I ran into:

```javascript
/* @flow */
// jshint ignore:start

import {EventEmitter} from 'events';

class Bar extends EventEmitter {
    constructor() {
        super();
    }
}

var pr = new Promise((resolve, reject) => {
    resolve(new Bar());
});
```

**Comment by runn1ng** [comment]
I cannot reproduce this bug anymore.

**Comment by runn1ng** [comment]
Nope, still can reproduce, reopening. It did not produce error first due to this bug
https://github.com/facebook/flow/issues/1410

but once I set up flow so it loaded `EventEmitter` definitions properly (instead of ignoring it because of the module `events`), it starting doing this again.

**Comment by runn1ng** [comment]
When I investigated more, it seems it has nothing to do with `EventEmitters`. Any time a class extends a class, that's declared in an external module, it does that.

It just happens that `EventEmitter` is probably the most extended class like that. 

But when I tried that with any similar class, it did the same thing. It has to be from an external module from a definition file, and the returned class have to extend that class. Try, for example, `net$Socket` that is in `node.js`, etc.

**Comment by runn1ng** [comment]
It does *not* need to be from the `lib/*` flow definition file; it can be anything defined in `[libs]` in `.flowconfig`.

**Comment by runn1ng** [comment]
**HA!** I solved it in the most weird and roundabout way possible.

I created a file `eventEmitter.js`, in which I have a simple few line script that doesn't do anything in particular

`````
import {EventEmitter} from 'events';
export class EventEmitterMine extends EventEmitter {
     constructor() {
          super();
     }
}
`````

and in the files, describing classes extending EventEmitter, I just do this
`````
import {EventEmitterMine} from './eventEmitter';
class MyClass extends EventEmitterMine {
     constructor(...) {
         super();
         ....
     }
}
`````

and it starts working. Interestingly, this alone doesn't help, without creating the extra file. The `EventEmitterMine` *has* to be in another file than the extending class.
`````
import {EventEmitter} from 'events';
export class EventEmitterMine extends EventEmitter {
     constructor() {
          super();
     }
}

class MyClass extends EventEmitterMine {
     constructor(...) {
         super();
         ....
     }
}
`````

**Comment by samwgoldman** [comment]
Hey, thanks for digging into the analysis. Are you able to come up with a repro that doesn't use eventemitter? A small isolated repro would really help nail this down.

**Comment by runn1ng** [comment]
Well the repro is easy... as I said, just replace EventEmitter with net$socket...


````
import {Socket} from 'net';

class Foo extends Socket {
}

function experiment(): Promise<Foo> {
    var foo: Foo = new Foo();
    var res: Promise<Foo> = Promise.resolve(foo);
    return res;
}
````

Exactly the same error (at least on my version... I haven't updated flow in a while)

**Comment by runn1ng** [comment]
And what really fixes it is having a small "helper" class, that sits in a separate file, and looks like this (this is the entire file)

````
/* @flow */
import {EventEmitter as EventEmitterOut} from 'events';
export class EventEmitter extends EventEmitterOut {
    constructor() {
        super();
    }
}
````

...and use that one instead of EventEmitter from node. Everything is then typechecked correctly and works correctly.

**Comment by SamChou19815** [comment]
This is fixed a while ago.
