### ISSUE TITLE
Frozen object literal types are not enforced in equality check (===)

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#5453]
```
/* @flow */

const Enum = Object.freeze({
  FOO: 'foo'
});
const a: 'foo' = Enum.FOO
const b: $Values<typeof Enum> = Enum.FOO;

if (a === '') {}          // Errors as expected
if (b === '') {}          // Errors as expected
if (Enum.FOO === '') {}   // no error
```

[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFFsBXAWzAF4wB5AIwCsBTDfAOigCdnmAvZgAoA3qjBgAYrVoAuMAHIocOPNQBfAJQBuTDgJgAhnMXL51YmXLsptXXkL05AEgBqBmKWa4APPgCeAA7McFAWFAB85iQU1tI6qACWoYIG1FQ08vIaYMJq4vkFYMDAxFxccFy4hlXMAB5BbMwAJonJ9GkZWTl5hQXFpeWV1WB1DfjNrWCC0VY2HQpdufn92HAjZRVAA)

This is likely a longstanding bug. Filing this since [in 0.60 release](https://github.com/facebook/flow/releases/tag/v0.60.0) frozen objects were fixed to maintain literal types (when applying `$Values`)

**Comment by SamChou19815** [comment]
now all of them error
