### ISSUE TITLE
Generics: type parameters should be allowed to be passed to function calls

### ISSUE THREAD

**Issue by drodsou** [facebook/flow#5455]
That is, this code should work (as it does in typescript):

```
//@flow

function fun1 <T> (value: T) : T {
  return value;
}

fun1 <number> (1);
```

Also it'd be cool if this code could work too (doesn't work in typescript either):

`let fun1NumberOnly = fun1<number>;`

**Comment by apsavin** [comment]
I'm not sure that I understand your first example (that works in TypeScript). Why do you want to specify type on function call?

Talking about the second example, isn't it what you're looking for?

```js
//@flow

type FnType<T> = (T) => T;

const fn = <T>(value: T): T => value;

const fun1StringsOnly: FnType<string> = fn;
const fun1NumbersOnly: FnType<number> = fn;

// error
let str: string = fun1NumbersOnly('324243');

// ok
let num: number = fun1NumbersOnly(324243);

// ok
str = fun1StringsOnly('324243');
        
// error
num = fun1StringsOnly(324243);
```

Try [here](https://flow.org/try/#0PTACDMBsHsHcCh4BcCeAHApgAgGIDsAVdDAHgID4sBeLACgIEprKCBuRAY2jwGcktwealjLlaANwCGkAK4YAXFkaKCzLFNkZ28Lr37gZeAIwBlJACcAlngDmPAPJ5IKRfiKYSfK7co1B7XT4BQyMAORkAWwAjDHMHJxdcQmISPEiY818BPG0QLFjzaHN4SAx+L0UvaxthA2Nw6Nj451oAcgBmACYAFh721oZc4CxoAGsSsqw0iMVpjNqQhozmlFou3u72wcQ8sfgvBeMzbztHFo6evoH2LFu72-g8gqL4acPTC2qVtcvNwaA).

**Comment by drodsou** [comment]
Thank you for your time apsavin.

- In the second example I learned something from your code and I ended with this syntax, thanks!:
```
let fun1NumberOnly : (number)=>number = fun1;
```

- Regarding the main question, I find the need of passing types when the type is not just checked in the arguments/return of the function, but somewhere inside it. Imagine this situation:
```
function createActionBuilder <ActionPropsType> (action:string) {
    return {
        action : action,
        build : function (actionProps : ActionPropsType) {
            return {type:action, props:actionProps})
        }
    }
}

// ---- usage
let action1 = createActionBuilder <{ prop1 : number }> ("action1")

// OK: both prop1 an 1 are type cheched against <ActionPropsType>
let dispatchable1 = action1.build( {prop1 : 1} ) 

// error, prop2 does not exist
let dispatchable2 = action1.build( {prop2 : 1} ) 

// error, "one" is string
let dispatchable3 = action1.build( {prop1 : "one"} )
```
This works in typescript, you can try it <a target="_blank" href="https://www.typescriptlang.org/play/index.html#src=function%20createActionBuilder%20%3CActionPropsType%3E%20(action%3Astring)%20%7B%0D%0A%20%20%20%20return%20%7B%0D%0A%20%20%20%20%20%20%20%20action%20%3A%20action%2C%0D%0A%20%20%20%20%20%20%20%20build%20%3A%20function%20(actionProps%20%3A%20ActionPropsType)%20%7B%0D%0A%20%20%20%20%20%20%20%20%20%20%20%20return%20%7Btype%3Aaction%2C%20props%3AactionProps%7D)%0D%0A%20%20%20%20%20%20%20%20%7D%0D%0A%20%20%20%20%7D%0D%0A%7D%0D%0A%0D%0A%2F%2F%20----%20usage%0D%0Alet%20action1%20%3D%20createActionBuilder%20%3C%7B%20prop1%20%3A%20number%20%7D%3E%20(%22action1%22)%0D%0A%0D%0A%2F%2F%20OK%3A%20both%20prop1%20an%201%20are%20type%20cheched%20against%20%3CActionPropsType%3E%0D%0Alet%20dispatchable1%20%3D%20action1.build(%20%7Bprop1%20%3A%201%7D%20)%20%0D%0A%0D%0A%2F%2F%20error%2C%20prop2%20does%20not%20exist%0D%0Alet%20dispatchable2%20%3D%20action1.build(%20%7Bprop2%20%3A%201%7D%20)%20%0D%0A%0D%0A%2F%2F%20error%2C%20%22one%22%20is%20string%0D%0Alet%20dispatchable3%20%3D%20action1.build(%20%7Bprop1%20%3A%20%22one%22%7D%20)%20">here</a>

Is it possible to do this in Flow?

**Comment by apsavin** [comment]
Well, I don't see that there's big difference with `FnType` from my code above. 
> when the type is not just checked in the arguments/return of the function, but somewhere inside it

Actually, you do use `ActionPropsType` in the return  type of the `createActionBuilder`. So you can express it with `flow`.

But now I understand the intention, thanks.

**Comment by kangax** [comment]
What is this a duplicate of?
