### ISSUE TITLE
Tuple as function rest parameter

### ISSUE THREAD

**Issue by markusjwetzel** [facebook/flow#5456]
I have a tuple with an object. Part of the object is an optional object property. If I use this tuple as a normal function parameter everything is okay, but if I use the tuple as a function rest parameter, then I'll get an error. Is this a bug or for some reason the intended behaviour?

Here is the code:
```javascript
type UserTuple = ['User', { name?: string }]

// this works
const test: (UserTuple) => void = (type, attributes) => {}
test(['User', { name: 'James' }])
test(['User', {}])

// this doesn't work
const test2: (...UserTuple) => void = (type, attributes) => {}
test2('User', { name: 'James' })
test2('User', {})
```

Here is the link to Try Flow: [LINK](https://flow.org/try/#0PQKgBAZgNg9g7mEwBQyAuBPADgUzAVQGccAnAFQFcso8BeMAbQHIjSmAaMAbzADsBDALY4A-AC4whNCQCWvAOZgAvgF1UwYGDQALGYTBwYJANaFkAYxi8pWnFIkAKVuSo0AlGFoA+MADcYMgAmnmAOmLic-GjSMgBGFGh2Ht7cSuh2aA7MzhzcfEI4EkwAUgWETMoqbulSWSzEJLlcqtXIGlq6+oEwdrxMaAZGxhZWNolSAEyOAHSzzpTUOMk+-kEhYdg4kdGy8ePLqTVoEw71bJw8AsJFpcLlytXjx6c5F0puQA)

**Comment by gkz** [comment]
Works currently
