### ISSUE TITLE
type "string" not compatible with "string | number"

### ISSUE THREAD

**Issue by alaindresse** [facebook/flow#5458]
Hi,

In the following code:
```
/* @flow */

const plain: { [key: string]: string } = { prop: '' };
type TestType = { [key: string]: string | number };
const testVar: TestType = plain;
```

flow detects a type incompatibility in the last line's assignment, apparently failing to note that the type `string` is compatible with `string | number`.

Am I missing something ?

Thanks, Alain

**Comment by vkurchatkin** [comment]
This because objects are invariant by default. You can make it covariant like this:

```js
const plain: { [key: string]: string } = { prop: '' };
type TestType = { +[key: string]: string | number };
const testVar: TestType = plain;
```

**Comment by alaindresse** [comment]
Thanks for your quick reply !

My case is actually a bit more involved than this. Could you point me to the documentation of the +[] to make the objects covariant ?

**Comment by lll000111** [comment]
@alaindresse Does the documentation help? -- See https://flow.org/en/docs/types/interfaces/#interface-property-variance-read-only-and-write-only-a-classtoc-idtoc-interface-property-variance-read-only-and-write-only-hreftoc-interface-property-variance-read-only-and-write-onlya

**Comment by alaindresse** [comment]
Very helpful. Thanks !
