### ISSUE TITLE
Request: "type import" statements which don't get executed at runtime

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#546]
I recently noticed what seems to be a useful undocumented/unexpected feature: you can export and import types between files even though they don't have a runtime representation:

a.js
```javascript
/* @flow */
export type Alpha = {a: Set<number>};
```

b.js
```javascript
/* @flow */
import {Alpha} from './a';
var x: Alpha = {a: new Set()};
x.a.add(1);
x.a.add('a'); // <-- useful Flow type error
```

I've found this useful and already started making use of it, but it bothers me that I have to do a regular import which still causes the imported file to be executed (and included in the bundle when using browserify) just to import a type for non-runtime use only.

There's also the practical concern that adding imports can change the execution order of files and break things, like in the case of modules which have their execution dependent on the side effects of previously executed modules or have circular dependencies. It's not ideal, but I shouldn't have to worry about breaking that sort of thing being a possibility when I'm just adding Flow types to files.

Can a statement be added like "type import" or "declare import" which imports identifiers only for Flow type use but prohibits them from being runtime-visible / non-type identifiers, and is entirely stripped out in the compiled javascript? Example usage:

a.js
```javascript
/* @flow */
export type Alpha = {a: Set<number>};
export class Beta { foo() {return 123; } }

// never gets executed unless this file is imported regularly from somewhere else.
console.log("a has been executed!");
```

main.js
```javascript
/* @flow */
type import {Alpha, Beta} from './a';
var x: Alpha = {a: new Set()};
var y: Beta = (window.betaInstance: any);

// This next line triggers a Flow error because Beta was only imported for its
// type, and doesn't have any runtime representation here.
var z = new Beta();

// This next line also triggers a Flow error because that can't work at runtime.
if (y instanceof Beta) {
  console.log("is a beta");
}
```

**Comment by jeffmo** [comment]
Yea, it's a known bug that 'import type' works for 'export type' -- and this will be cleared up soon.

You can use 'import type ...' To specify an erasable type import (and once the bug is fixed, you'll only be able to use 'import type' for type exports).

**Comment by jeffmo** [comment]
Thanks for the report though! I'm hoping to have a fix for this next week

**Comment by AgentME** [comment]
Oh awesome!

Can you use "import type" to import a class just for its type?

**Comment by jeffmo** [comment]
Indeed -- 'import type' is basically sugar for creating a local type alias to a remote type.

So if you used it in classes, it's be as if you typed:

var MyRemoteClass = require('MyRemoteClass');
type MyClass = MyRemoteClass;

Except you get to skip the local runtime variable and the execution of the remote module.

So basically anything that can go on the right hand side of a type alias can be imported with 'import type'.
