### ISSUE TITLE
Destructuring function param doesn't work with union types

### ISSUE THREAD

**Issue by atabel** [facebook/flow#5461]
Here is an example with a redux reducer:
This code:
```js
type FooAction = { type: "FOO", payload: Object };
type BarAction = { type: "BAR", payload: Object };

type Action = FooAction | BarAction;

function reducer(state, { type, payload }: Action) {
  switch (type) {
    case "FOO": return { ...state, value: payload };
    case "BAR": return { ...state, value: payload };
    default:
      return state;
  }
}
```
Produces this error:
```
6: function reducer(state, { type, payload }: Action) {
                             ^ string literal `BAR`. Expected string literal `FOO`, got `BAR` instead
6: function reducer(state, { type, payload }: Action) {
                             ^ string literal `FOO`
6: function reducer(state, { type, payload }: Action) {
                             ^ string literal `FOO`. Expected string literal `BAR`, got `FOO` instead
6: function reducer(state, { type, payload }: Action) {
                             ^ string literal `BAR`
8:     case "FOO": return { ...state, value: payload };
            ^ string literal `FOO`. This === check always fails because `FOO` is not the same string as `BAR`
6: function reducer(state, { type, payload }: Action) {
                             ^ string literal `BAR`
```
[see in Try Flow](https://flow.org/try/#0C4TwDgpgBAYg9nAggY2ASzgOygXigbylEgC4oAiGAeSvIBoowBDEAGziYBMyqAjAKwiooAXwDcAKGLQAQkwBOKdFlwEi4CGXIzEAJXqMW7LjwFDgoyVI1QlGbHnhJU9qAB8ocxS6xWAZgCumD7Y8hCcAcgQ8gAUAM7ATMAQDITSDMxsHJyiZHZYAJQEElBQcQDuaMDIABZQMdJF+CWlUMhMcdCUNORkYcAB8tiEAHRjCUkpUABuTKwBmoZZXJYtpe2dFDr6fRADQ2pjIxPJDLPzi5nGOeJrUJwQfkwBrMAkd6X9g9gnEJKlIgkIiAA)

But, if I move destructuring to the function body instead of function declaration:
```js
function reducer(state, action: Action) {
  const { type, payload } = action
  switch (type) {
    case "FOO": return { ...state, value: payload };
    case "BAR": return { ...state, value: payload };
    default:
      return state;
  }
}
```
```
no errors!
```
[see in Try FLow](https://flow.org/try/#0C4TwDgpgBAYg9nAggY2ASzgOygXigbylEgC4oAiGAeSvIBoowBDEAGziYBMyqAjAKwiooAXwDcAKGLQAQkwBOKdFlwEi4CGXIzEAJXqMW7LjwFDgoyVI1QlGbHnhJU9qAB8ocxS6xWAZgCumD7Y8hCcAcgQ8gAUAM7ATMAQDEwhZHZYAJQEElBQyFgJatIMzGwcnKKqacqYeVBxAO5owMgAFlAx0jn4DfnITHHQlDTkZGHAAfLYhAB0CwlJKVAAbkysAZqGFVyW-QVDIzr6ExBTM2oLc0vJDOub2+XGVeIHnBB+TAGswCQH+Um02wtwgknyIgkIiAA)

**Comment by kristiehowboutdat** [comment]
Here is another example: [Try Flow](https://flow.org/try/#0C4TwDgpgBAsiAq5oF4oG8oH1OkgOwEMBbCALigHIBBCqAXyigB90sclCTyKAhWugNwAoIQHpRUACIQAzsABOAVwDGwRfICWeAOZQtUAGaK8qjQHs8UAEZmAJiCgBaKAHcz8gNYyhyi3NfuXlCoABTA5HCIkACUwQB86EKMvnj+GNi4EJzQDKjAwgCQGgZQIRkcxCjIqNQUsWhJjFAFKTJmADYQAHTtZtohtdHCTfRCdCLiUrIKKmqaOnqWRibA5pZgBPLEMk5QtmayUAByAPLwAZ4+fsB7BzJ4wADqgcGl6ez4lfQRCEixyAkGkUSmUPlkvtUajR6o1GC0-B1ur1+oNhk1xnQgA)
