### ISSUE TITLE
Need a $Deprecated utility type

### ISSUE THREAD

**Issue by 8bitjoey** [facebook/flow#5462]
Sometimes I'd like to indicate that a property is deprecated and is going to be removed soon.
There is a helper to do that if I used prop-types: 

```
import deprecated from 'react-prop-types/lib/deprecated';
...
static propTypes = { 
    myDeprecatedProp: deprecated(PropTypes.bool, 'Use `newProp` instead'),
    ...
```

But I don't want to use prop-types and flow types simultaneously. 
So I find it handful if flow had a special utility class which throws a warning if such deprecated property is used in the code.

**Comment by vkurchatkin** [comment]
See: https://github.com/facebook/flow/issues/4646
