### ISSUE TITLE
Is it possible to use $Values for enums, without using Object.freeze?

### ISSUE THREAD

**Issue by bluepnume** [facebook/flow#5465]
The latest flow release shows the following example:

```javascript
const Enum = Object.freeze({
  X: 'x',
  Y: 'y',
});
type EnumT = $Values<typeof Enum>
('a': EnumT); // Fails
```

Is it possible to do this without the run-time `Object.freeze()`? This raises browser-support and performance concerns.

I tried this but it didn't work:

```javascript
type FrozenEnum = { +[string]: string }
const Enum : FrozenEnum = {
  X: 'x',
  Y: 'y',
};
type EnumT = $Values<typeof Enum>
('a': EnumT); // Doesn't fail but should
```

How can I mark the `Enum` as being frozen, without using `Object.freeze`?

**Comment by zerobias** [comment]
@bluepnume Not exactly what you want to see, but you might not need the runtime to declare something. Thanks to comment syntax this works as well

```js
const Enum = /*::Object.freeze(*/{
  X: 'x',
  Y: 'y',
}/*::);*/
type EnumT = $Values<typeof Enum>
('a': EnumT); // Fails
```

**Comment by TrySound** [comment]
I guess this can be closed in favor of https://github.com/facebook/flow/issues/627

/cc @vkurchatkin
