### ISSUE TITLE
Object factory shenanigans w/derived types

### ISSUE THREAD

**Issue by XaserAcheron** [facebook/flow#5470]
I've run into a bit of a bind. The short of it is I'm using object factories to create things (i.e. no classes or `new` anywhere), and I'm being brickwalled by Flow when trying to create a derived type.

It's maybe best to explain with an example, so here's a super-stripped-down sample of what I'm trying to do on [Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgNoA0CCAumHAEYBWApgMYAuYUAhnXAE4CeYAzgBaUB2jfgEsA5kK4A6dJjAATSlGH9KYRmABCjLqtrsADqqFy1DZrTacoAV351hcfgzZhqrSo1rLRprTpIUNLTSqHqGmtqqALxgAN6oAJBQcHAAXNy0rN6oAL7oNnZejq7unpR+lAAUAJTpFXGJ1I5c9CoI9TGxOWCytjqMMJRyANxqMDBgwlwkANaoYAtgbRWSyXBgMQBEawCEm-NgibL8iK7a9ML0AGRg7rTWrPyjtDxTYAhsM9OipfRcytRVHAHgEqHQjlgTkgeNoxhMXqp3ABHazCdwmfSsOCGVheSjTOBQCI6aSLW6Ue6PMCVZaROqRaq5GSQ07JVjcOAAWwpr34PnUpEuYE5bFUmLIg05nmE1HSg1oAHJpiKFBMuFzVP9OfpBpN+HwsrQhICQmFVAARShZABuQw2DQSpEYrHSLSyfNyYBuFXytnsxTcHlolEtNqGNXSoeEtpM8QSsnlSpKQaMxKM-BMmU4xjUckzfDAmydrH28aw4pxejAFkmf3WCFU1CEZxater6zNYCjMekCSa-FbbW7dpigbKFRqBwWQ6t0aGkmL9qLzr2PSwcB4SzgOzUTitWNYIQWZb11b4ljPb14wJgJgGEw+rBmZ81jG5ABowKRrPQERDq1i1ikIM6rcmA+jOhc0wvJ4L7kpSTjWgM1iqFAWKcsm46RJMXD-iA-SDHIICfuqYAAGLwEgchwPi-AKvQMDCDMqhCggfBOA2AHZhmuYmAqxYKiEJ4AJIKhhJx-A8qhsbBOj0ISLb0NaKTUeslTaFw1ict4L7uDhu7sIyJ4fNYt5wqcYE1qQBgaZe0xcICghZHAn6bFwjBQAI+JcJsX6qHIb4qHIR6LHcDxODSlAIMOciRrOMaMnkQA); code replicated below:

```javascript
/* @flow */

// [XA] object factory shenanigans.

// define a Base type and a factory function for creating a Base object.

type Base = {
	foo: string
}

function createBase(): Base {
	const newBase = {} // unsealed; all is ok
    newBase.foo = "foo!"
  
	// now cast it & return; this works great since our object
	// now has all the required properties of Base.
    return (newBase: Base)
}

// now for something a bit more problematic: let's model some simple inheritance.

type Derived = {
	bar: string
} & Base

function createDerived(): Derived {
	// let's create a Base and try and add the "bar"
	// property to it so we can cast it to type Derived.
	const newDerived = createBase()
    newDerived.bar = "bar!" // oh no! an error.

  	// in theory this should all work the same, but the
	// troublesome part is that the return value from createBase is
	// *sealed*, so Flow doesn't like it when we try and add 'bar'.

	// I'm not sure what set of cast voodoo (assuming there is any)
	// would allow me to bypass this scenario, "safeness" be damned.

    return (newDerived: Derived)
}
```

To summarize: the Base factory function works great since it starts with an unsealed object literal and ends with a properly-typed object at the time of casting, but the Derived case fails when we try and add new properties to the Base object ('cause it's sealed).

Does anyone have any insight on how to achieve this? In my simple example above I suppose I could  sidestep the system by casting to Object (i.e. `const newDerived: Object = createBase()`), but this ends up disabling the property type checks on return, meaning if I accidentally set `newDerived.baz`, it'll slip through.

What I'd really love is some way to tell Flow that `newDerived` is _going_ to be a valid Derived type at some point, then cast it at the end to tell Flow to do its thing, but this seems like it would be feature request territory... hence this issue, rather than an SO post.

Post-disclaimer: This is sort of the same as #1606 and #4193, but I figure having a slightly more realistic use case would help.

**Comment by EdwardDrapkin** [comment]
You have to copy the object to reassign its type.  You are not returning an object, but a reference to an object.  So if you mutate the reference that you return from your factory, you mutate all the other references to it.  That's not a big deal in a factory function, but Flow can't guarantee that the object you're returning hasn't escaped scope (as a Base, where other things are expecting to be and stay a Base), so you can't refer to it as a Derived.

Here's a demonstration:
```
class Foo {
	getBase() {
    	return this.base; 
    }
}

function extend(foo) {
  const o = foo.getBase();
  o.extended = true;
  return o;
}

const f = new Foo();
f.base = {};

extend(f);

console.log(f.getBase()); // there's a extended property here!```

**Comment by XaserAcheron** [comment]
Thanks! That works well, and fortunately the performance impact of copying the object is negligible in my case. That sheds some light on why Flow behaves the way that it does, too.

I do wish there were some way of officially signaling "this is unsafe, but I know what I'm doing" though, since the fix involves adding a runtime operation. Something like the `$Unseal<obj>` suggestion in #4193 would do the trick.

**Comment by EdwardDrapkin** [comment]
There's suppression comments but they suppress Flow entirely, not just a single error.

**Comment by XaserAcheron** [comment]
It's a web app, for the record. In a perfect world we'd have a bit more choice in the matter of client-side web development, but alas. ;)

**Comment by zerobias** [comment]
@XaserAcheron you can think about $Shape<T> as "incomplete object of type T", so you can type it like this
https://flow.org/try/#0FAFwngDgpgBAQgQwM6wLwwN7BjAZge3wC4YkQAnASwDsBzYAX2GFwFdqBjES-amD8lAQgoiFAAoAlCTGwsASA68yMalADusmOgxMcONZuRQAdAXzaYAInMBCK9n2CQrcn0OzGzcNBgARKCoANygAE0ssHAAjBHISMio6ABpHEzSAEgBRAA8ELgAeWQA+LxZ2Lh4+ASERAOCwqRI6yhDwyP0lahVDZtaSdIBlAAsEaHzesKLLauFRYylHAw0J0JMY8ksrdfsYAHpdmHwh21ULQPJ8ckWYZ1d3ZcCWsMYgA

**Comment by XaserAcheron** [comment]
Oh wow, I had no idea $Shape existed. Thanks! That's exactly what I'm looking for, right on the nose.

The lack of documentation on it is unfortunate. If it was listed with the rest of the Utility Types, I wouldn't have needed to file this issue in the first place. :P
