### ISSUE TITLE
Example for $Call needlessly complicated?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5473]
Doc for `$Call`: https://flow.org/en/docs/types/utilities/#toc-call

For example, this demo code:

```js
// @flow

// Takes a function type, and returns its return type
// This is useful if you want to get the return type of some function without actually calling it at runtime.
type ExtractReturnType = <R>(() => R) => R;
type Fn = () => number;
type ReturnType = $Call<ExtractReturnType, Fn> // Call `ExtractReturnType` with `Fn` as an argument

(5: ReturnType);  // OK
(true: ReturnType);  // Error: ReturnType is a number
```

I don't understand why there is an extra `ExtractReturnType` function type. After all, given the description of `$Call`, this seems to be _exactly_ what it already does! 

[Flow Try with the example rewritten to not use the additional superfluous helper](https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwBVxoBeKAHgwD4AKWgSilOqgyZbYG4AoUSKADF8zKI2at8OALYAjCIl4B6Jf2hZcBYgPIASAMLIANkYrwkaTNjxESAGiH5WKqIZNQABuZToNN7RAeUADuAJbAABaewkHIAM5QyCLIiADmMhD4wDx8JGzWWnl6bqbC1Dm0AKwAXPmatpAMXFBQLgDyANI8tEg4ELV+hY3NrUqwiIgA9ogDBQ3QoQnIUFJyCjwtLUA)

```js
type Fn = () => number;

type ReturnType = $Call<Fn>

(5: ReturnType);  // OK
(true: ReturnType);  // Error: ReturnType is a number
```

If the point was to demo a more complicated scenario and to show that you can specify parameters as well it should be stated. The core example should demonstrate the core function.

**Comment by samwgoldman** [comment]
Sure, feel like putting up a PR?

**Comment by lll000111** [comment]
I feel like putting up a ticket. No matter, I already decided to switch to Typescript sooner rather than later - this project's issue handling is basically non.existent. Well, apart from you closing tickets left and right without anything having been done. Just look at the list of open vs. closed issues for Typescript and for Flow. Quite embarrassing, actually.
