### ISSUE TITLE
getBoundingClient should return a DOMRect not a ClientRect

### ISSUE THREAD

**Issue by gregtatum** [facebook/flow#5475]
The spec defines `getBoundingClient` as returning a `DOMRect`.
https://drafts.csswg.org/cssom-view/#dom-element-getboundingclientrect

MDN also uses the `DOMRect` in its examples:
https://developer.mozilla.org/en-US/docs/Web/API/Element/getBoundingClientRect

Flow defines it as a `ClientRect`:
https://github.com/facebook/flow/blob/166b0c202b778539832f61fc7f98a4a7e94dfa9d/lib/dom.js#L995

And has the Class declaration as `ClientRect`:
https://github.com/facebook/flow/blob/166b0c202b778539832f61fc7f98a4a7e94dfa9d/lib/dom.js#L3045-L3052

You can create a `DOMRect` directly using:
```
new DOMRect()
DOMRect { x: 0, y: 0, width: 0, height: 0, top: 0, right: 0, bottom: 0, left: 0 }
```

But it is not compatible with the ClientRect.

**Comment by gregtatum** [comment]
flow.org/try does not appear to have the DOM definitions in it, but I believe this would error:

```js
function acceptClientRect(rect: ClientRect) {}

// Fine:
acceptClientRect(element.getBoundingClientRect());

// Bad:
acceptClientRect(new DOMRect());
```

**Comment by julienw** [comment]
`[1] IE and Edge support the non-standard MSDN: ClientRect which does not define x and y properties`

Maybe that's why there's this difference, with Flow taking the safe approach ?

**Comment by julienw** [comment]
> But it is not compatible with the ClientRect.

It actually is :) a DOMRect _is_ a ClientRect too (it has all the right properties)

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by julienw** [comment]
So, nothing changed here as far as I know. GetBoundingClientRect still returns ClientRect. Is the rationale from my previous comment right? Maybe it should return `ClientRect | DOMRect` ?

**Comment by TrySound** [comment]
I would just define it as interface to prevent instantiating. It still does not give any functionality.

**Comment by airqb** [comment]
use "top" instead of "y" and "left" instead of "x" I think the "top" has more Availablity in most of the browser, chrome support "y" and "top" but others maybe are not. this why the "top" is most supported cross-browser  than "y"

**Comment by julienw** [comment]
Yeah, it's not yet supported in Internet Explorer, Edge or Safari, sadly. Still this is the spec...

**Comment by rayellis4** [comment]
DOMRect as the response type to getBoundingClientRect() is supported by Edge (v86) and Safari (v13) on IOS and macOS.

I would find it useful if it were supported by flow, too.

**Comment by Dagur** [comment]
Surely it can be changed now. ClientRect is deprecated.
