### ISSUE TITLE
Getting non-static property of class out of generic type

### ISSUE THREAD

**Issue by vojtatranta** [facebook/flow#5481]
I am desperate!

I would bother all you fantastic people with this, but I am done...

I cannot get this working: https://flow.org/try/#0PTAEAEDMBsHsHcBQyDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYhSxBxUMPwkAvKAA8AQXEAhZqWUA+ABQBpDNgLFmAYReYzt8QBN8SCZQCwBKUANbMgpKGn1OGkFQe1p6EIASABF+SEhjDIAFOip8GiIAT1wK0rNxAHI0hnq-UNsIqJSbMLVYyn7QPoHBytLQAFEAD1KUInx-SK62Dm55RTFJaVhZNaFhFQ7omw0tHXiQqZm5haM9Ins3InFSTZk5UHq54nqDoA

What works:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHNQAX0QTkiIgE8q+PISIAFOg1ABeUABI19fDTm55+ADwFiAGlAByWvUy2AfBVCpYg4qEido0SH5-fAATZktVdRxtUjYObmZbPiFhW3EgA
```js
// @flow

class Test {
  props: { value: string }
}

type TestProps = $PropertyType<Test, 'props'>
  
const fullfilled: TestProps = { value: 'string' }
```

And I don't understand why does this does not work:
```js
// @flow


class Test {
  props: { value: string, meloun: string }
}

const get = <A, B: {}>(KlassTest: Class<A>, defs: B) => {
   return (props: $Diff<$PropertyType<A, 'props'>, B>) => ({})
}
        
type Expected = ({ value: string }) => {}
const res: Expected = get(Test, { meloun: 'test' })
```
The error I get:
```
9:    return (props: $Diff<$PropertyType<A, 'props'>, B>) => ({})
                           ^ property type. Property cannot be accessed on
8: const get = <A, B: {}>(KlassTest: Class<A>, defs: B) => {
                ^ A
```

How should I type those generics to make flow understand?

Thank you for any help!

**Comment by apsavin** [comment]
Try [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYgAm+NOhr5QkWSiL9Yg0MPwkAPAGFxAQWa2M2OwD5xAIWYB5AEYAVtpE7gAUANKumATEzA7iWpBMoF4AlMwAJAAi-JCQ1pkACnRU+DREAJ64lWV24gDktPSYDZ6p7gDclJQUPf2IVWWgAKIAHmXG+BqgALws7Fw8oHxCwiqdyChmxKB6KeOTRNNzFlZhsUTipJLSsLLMDcfEDSppQA)

**Comment by vojtatranta** [comment]
@apsavin you are my hero!

But can I write it without declare? Or could you please give me a full example with such function implemented? If you don't mind of course.

Because I don't understand why the same code does not work when I implement such function:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYkiyURfrEGhh+EgB4AwuICCzUxmxmAfOIBCzAPIAjAFb5t9gBQA0raYBMTMFuIAJviQTKBOAJTMACQAIvyQkMbJAAp0VPg0RACeuMUFZuIA5LT0mFWO8fZkyJQoesSgNISc0CQAvKBBWCGERAB0tUSwJQWT+ZgUoB7e2uMA1vjFmH7RsQnjkLA0AKLoKAAWfn6bxQmg-c3klJTR0Eb4XT19ANq3ALpLZQJJZLbpETg0fTdTC9IhqJYvF6IWafE4ADwK2nwkQeLHYXB4oD4QmEKgA3Mh2oJOjDmBisUQcXjDEQ-KEiOJSJJpLBZMwqkziFUVAkgA

**Comment by apsavin** [comment]
Try [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYiFF8NSOhT5QASQDq-IgAsACnQZkK1G01AB5AEYArfCiJrkkWd78sIKgwvgkADwAwswmZlaO4gCCzFEY2NEAfOIAQsxunt6ZABQA0umYBMTMSeIAJviQTjkAlMwAJAAi-JCQEe3W9NpEAJ64I1T40eIA5LT0mDPZoDmZdvYowcSgNISc0CQAvCwAdGflWJWERCfzRLCjk7eOKvYFXjcA1vgjmMUNTRaJ0gsBoAFE9OZisVviMWqBDmtyJRKA1oOEDLtMPsiABtWEAXXsyha9nsuyInBoISxON8KIZoEQjwMYIAHpNvPg6giWOwuDxQHwhMIVABuZCbQTbLHMdmcrQ845hIjFKpEcSkSTSWCyZgzLTEGYqFpAA)

**Comment by vojtatranta** [comment]
Omg omg! You are so awesome thank you sooo mich!

**Comment by vojtatranta** [comment]
@apsavin I don't think it works correctly.

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYiFF8NSOhT5QASQDq-IgAsACnQZkK1G01AB5AEYArfCiJrkkWd78sIKgwvgkADwAwswmZlaO4gCCzFEY2NEAfOIAQsxunt6ZABQA0umYBMTMSeIAJviQTjkAlMwAJAAi-JCQEe3W9NpEAJ64I1T40eIA5LT0mDPZoDmZdvYowcSgNISc0CQAvCwAdGflWJWERCfzRLCjk7eOKvYFXjcA1vgjmMUNTRaJ0gsBoAFE9OZisVviMWqBDmtyJRKA1oOEDLtMPsiABtWEAXXsyha9nsuyInBoISxON8KIZoEQjwMYIAHpNvPg6giWOwuDxQHwhMIVABuZCbQTbLHMdmcrQ845hIjFKpEcSkElAA

In this case, where no default is set the `Expected` type should be `{ value: string, meloun: string }`. Therefore example above should throw an error.

And there's another issue. Out of technical debt reasons I cannot use ~Flow@0.60.x`. I can use only `0.51.0`.

And if I turn on this version I get this strange error: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYiFF8NSOhT5QASQDq-IgAsACnQZkK1G01AB5AEYArfCiJrkkWd78sIKgwvgkADwAwswmZlaO4gCCzFEY2NEAfOIAQsxunt6ZABQA0umYBMTMSeIAJviQTjkAlMwAJAAi-JCQEe3W9NpEAJ64I1T40eIA5LT0mDPZoDmZdvYowcSgNISc0CQAvCwAdGflWJWERCfzRLCjk7eOKvYFXjcA1vgjmMUNTRaJ0gsBoAFE9OZisVviMWqBDmtyJRKA1oOEDLtMPsiABtWEAXXsyha9nsuyInBoISxON8KIZoEQjwMYIAHpNvPg6giWOwuDxQHwhMIVABuZCbQTbLHMdmcrQ845hIjFKpEcSkSTSWCyZgzdDmWDuGYqFpAA

I know I am wasting your time and I am sorry for that. But could you take a look? Thanks!

By the ways, here's full example what I am trying to type:
```js
// @flow

import React from 'react'


export type IWithProps = React.Component<*, *, *> & { props: Object }

class TestComp extends React.PureComponent {
  props: {
    value: string,
    memberRole: boolean,
  }

  render() {
    return (
      <h1>{this.props.value}</h1>
    )
  }
}


const createConnector = <ConnectedProps: {}, ResultProps: {}, Comp: IWithProps, CompKlass: Class<Comp>>(
  WrappedComponent: CompKlass,
  connectedProps: ConnectedProps,
  fn: (connectedProps: ConnectedProps) => ResultProps,
) => {
  const initialState = fn(connectedProps)
  return class extends React.PureComponent {
    props: $Diff<$PropertyType<Comp, 'props'>, ResultProps>
    state: ResultProps = initialState

    static defaultProps: ResultProps = initialState

    render() {
      const props = { ...this.state, ...this.props }
      return (<WrappedComponent {...props} />)
    }
  }
}

const connected: {
  role: (num: number) => number,
} = {
  role: (num: number) => num,
}

const Result = createConnector(TestComp, connected, (options: *) => {
  return {
    'memberRole': options.role(123),
  }
})

const t = <Result memberRole value='eee' />
```
And now I get strange error: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdyiRAHlnqLgJ4ZFQASQDqKXAAsACtQwBnUAF5CTXADoAwjSwA7IjtwAeAFQAaUGYsA+UADJQAb1AZZcgFygA8gCMAVkQpQAF9kMmgSOQUAFSI5XC1MUA5cfQATBWJydSkAV0YE3X18B0RQZ1cPErKygDcSaByiDzjsFB0Ac1NS6rQiNG8ibAJYaCbQb1gR0h0uspDuxh1UwYAKAEpHbrLGXDydUBWt6sMJAEYrB0kUOTUXWHk1OoaiIMNgM6sjte6Q+cQyWA6OKgMiMEgpLQ6PQUHBKUCGSHQlKpGT3dyOILmYhyHLQXCo+SVTGgAoeUTiaSucwFADS4UiHg09LkCO0VishzKImwJAwAlSBUBRUZ2jpETksxBgKRRBRFRJ0oCyIJEu6kB0HhWAKhStlKpFOooetcG0UNmxuPxVMQppsVSlQPwbXEKHqAGVcODBMp1VrFUa5WjvtsiLtsPswuKkuwUksMqo1Ll8tohQZNtVymiPAASAAiKEgkEM2YJgz4UX4RFZmHMdDu8joVixsUtKs+GbiXo8FrxKrhztwrugHq9yA7nsHZFAy0gJFb8p7VrR-Z0LvdE6IY+qi2W2HW6YzDuB9YUyicagvVxunZS5gvaivt1cwSOIbD+xWhm5vP5gr0aYce8TyCUBgCsYNqhCOZEHmbVgW1GVUkqBYpk1HQcjQDx0P6QZbVAbCBmwLoQLPFDRjQjCsIwwi8Ow4jQkBYFFzhUFSAhf1cBwFYYjiApzAQ3VUnMFZ7kHRiPGMPD7R2PYDzKOhehwoYpjoDxRJQRi1GoUYVlOAAmABmNZJV+b5-kY-B8GUQxmMUwjhlGUAnkaRQ6CIdy6FAz4gA

```
23: const res: Expected = get(Test, { meloun: 'ahoj' })                          ^ property type. This type is incompatible with
23: const res: Expected = get(Test, { meloun: 'ahoj' })
               ^ object type
```

**Comment by apsavin** [comment]
1. It works correctly. `type Expected = { value: string };` does not mean that `meloun` can't be in the object. It means only that object must have `value` prop of type `string`. So there's correctly no error.

2. I'm afraid `$Diff` is broken in `0.51`. Just do the upgrade - you'll need to do it at some point anyway. Sorry, I can't find a way to type what you want on `0.51`

**Comment by vojtatranta** [comment]
@apsavin 

1. aha! You are right, this works as expected: https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToAqBTTAF1AG9FRQAHAJ1iswC4zQA3daAV32eJoEsAdgHMANKAC2+OJ0G8iAkaAC+iVYiFF8NSOhT5QASQDq-IgAsACnQZkK1G01AB5AEYArfCiJrkkWd78sIKgwvgkADwAwswmZlaO4gCCzFEY2NEAfOIAQsxunt6ZABQA0umYBMTMSeIAJviQTjkAlMzF9EROACQAIvyQkBHd1vTaRACeuBNU+NHiAOS09JgL2aA5mS2gALyZbLD8dXb2KMHEoDSEnNAkOywAdE-lWJWERA-LRLCTs5+OKnsBS8HwA1vgJphig0mi0HpBYDQAKJ6czFYrgibbPZ2SiUBrQcIGK6YG5EADamIAuvZlC17PYrkRODQQiSyb48VzQKhziQSbtQuFilUiOJSJJpLBZMwFpg6pAFuJ2FweKA5fh8AsVC1iqQ6UA

2. I fear that...

Thank you for your time again! It's been massively helpful!

**Comment by vojtatranta** [comment]
Well,
I am still not able to type it even in 0.61. :(

How come that InjectedProps does not seem to have affect on `$Diff<>`? It seems like `injectedProps` are empty:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdyiRAHlnqLgJ4ZFQASQDqKXAAsACtQwBnUAF5CTXADoAwjSwA7IjtwAeAFQAaUMYB8oAGSgA3qAyy5ALlAB5AEYArIhVAAX2QyaBI5BQAVIjlcLUxQDlx9ABMFYnJ1KQBXRnjdfSN7RFBS0AA3EmhsondY7BQdAHNTErK0IjQvImwCWGha0C9YftIdVtLA8ysHZFLGHRSegAoASlmy0EZcXJ1QZbbNwwkARkt7SRQ5NWdYeTVK6qJAw2BTy0PQVbbg4JDYHSxUBkRgkZJaHR6Cg4JSgQwQqHJFIyO5uBxTYQ6PwUIjIlzuewY-LuUTiaQucz5ADSYQi7g0tLk8O0lksB1KImwJAwAhS+QBhXp2hp4TkE2BAMRuJR8iFkP8SJlYrajWxSJJWIV0opiHWimsxVKfAEKgAjtkUIw8ajYQASAAiKEgkEMtplPT4kX4RGZmHMdFu8jolnMQk1OOt8g+pTIAKBjXEKCqAGVcGDBmG1dqbcpVVqUm1trtgYzEuxkot0qo1Dk8toBQZDMRzZbs-JQ+HFS4DZ9A2jmxarUrPrF0xqs5GFLmdImU2nknMyqPcCgyKAlpASNloLgleP80rYQmV3P04v5qkVutDZsJYD8H3YY41C-Ltdl0RzC+1G+bi4gp8F47NgezLIYnLcry-J6AYDjfn2gSgMAljfJswSTIgfyxved5SikBKFqM7jLDo2RoO4pFdD0erWMMowkOMmFPoRAzEZRFFkd02A0Tw2A1K0WFxvgxByNu+DKCCpDgpKCo4Ms0SxPk5jYXh5g3qUHRUb0RG8fxPy6v8OHiXCIliRUVQ1IodBEEQdBIZYQA

In this case there should be no error, because `memberRole` is provided in `injectedProps` and `value` as prop.

There are nother strange things happening, if I do this:
```js
<ConnectedProps: {}, InjectedProps: { memberRole: boolean }, Comp: IWithProps, CompKlass: Class<Comp>>(
  WrappedComponent: CompKlass,
  connectedProps: ConnectedProps,
  injected: InjectedProps,
) => {
```
Everything works. But I want to have `InjectedProps` generic.

If I do this:
```js
<ConnectedProps: *, InjectedProps: *, Comp: IWithProps, CompKlass: Class<Comp>>(
  WrappedComponent: CompKlass,
  connectedProps: ConnectedProps,
  injected: InjectedProps,
) => {
```
Suddenly no props are required. Which is even worse.

I'd be glad fo any help! Thanks!

**Comment by apsavin** [comment]
Something like [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK3RnkAVKqVwBhZhlBUAHrioA7ACblqdXADoACgFcO4zLHkLcAHgDeiUFdAA3YtG1UAXKBHYU8gOYAaS9bRUaABGVNgUsNDOoEGwETTyvlYAvt6EAHygFn4cSqEAFACUmX5WHLi68qB5JdYmABYAjGlmuHUopOoYTBgddg5USSbAjWk1BX5JiJM8hiKgtBzEcuLyRvQ4oAC8oCY1Vitrcoqa3aQuZimge6AAkvIAVlT0VMen55fX+hgA0nykZ6BRH9SCZVPR1F9DMYTARUgQ0mlEtZkRRNC4ACQAERQkEgoM4GgAopEAvJcCdYD0TF9fvxEbcHk8jhSeojrlY0tUrAB1bDEDAYF6Qoxklw04FI2iGQ4vFkAg5M2WnJEeR7PRQuO5q5nKxAFMXA-FqCESKFk0GaVJaxWvSmkBFbDIWKxS+RzDwoXAoewAZVwSyi1vVcq2oFVNuyVHK2EqvH4UlkCmUlAJWl0VGF0NRVsZwdOTpqIgDoY9Xt9-rkyGRRa9tFAiiokGI2mg5LeDO1SrtJfknu90D9Aar1hyDewhWKyJds3wXW72zMoHUy9a7XUNaoqWX6lXHTnPVAkynoDKFSqJl5-MFikzZMy2-3pCSoGAaXGyKPh6mMzd+FdMo1ScTziFw8nkbQ0BccDglCIpNgyGI4mIBIplDZ1gMiUDoKgiCQmwOCMlwbBHF8aZXTmahSBbfBtgWGhlmlJkcDyIQRC+VJ-xtVJ0KsAIYLCEDQCIkiJj1H85honZKOo2x7EcTZWCoKhWBfNIgA)

**Comment by vojtatranta** [comment]
@apsavin aha, I need to use `$Diff<>` when declaring generics! Thank you again!

I hope that's all I need.
