### ISSUE TITLE
Destructuring assignment with `or` makes Flow unsound

### ISSUE THREAD

**Issue by taylor-cedar** [facebook/flow#5482]
Here is an example of the bug:
```js
type A = {
  a: number,
  b: number
};

type B = {
 c: ?a 
};

function a(d: B): number {
  const {c} = d; 
  const {a} = c || {};
  
  return a;
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCGAXGAHYCuAtgEZ4BOANFWOwYsO3VAF8A3Omz4wAIVIUqAYwYB+GmHFTUUZo2UYAlnEa0AFABMGcgJRC2nLkurLTAZwwVlYxZYlarh5e5DS+ZMpgAD5RFJL8-Fx4GMxcZjRSYkA

**Comment by lll000111** [comment]
Why did you define `type A`? It is not used in your example code.

**Comment by apsavin** [comment]
@lll000111 I think it should be

```
type B = {
 c: ?A
};
```

**Comment by lll000111** [comment]
See my smaller example, it already shows what you want to show. Basically, using `{}` is interpreted like the Flow type `Object`, which is kind of an "object-any" type and prevents further checks.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
