### ISSUE TITLE
`$ObjMap` doesn't work with intersection types

### ISSUE THREAD

**Issue by tdawes** [facebook/flow#5485]
Hey, I'm having trouble with `$ObjMap`, and noticed that it seems to drop properties when mapping over intersection types:

Doing

```javascript
type A = {
  a: number,
};
const simple: $ObjMap<A, () => string> = {
  a: "test"
};
simple.a;
```

works as expected, but using an intersection type:

```javascript
type B = {
  b: number,
};
const intersection: $ObjMap<A & B, () => string> = {
  a: "test",
  b: "test",
};

intersection.a;
intersection.b;
```

gives the error:

```
18: intersection.b;
                 ^ property `b`. Property not found in
18: intersection.b;
    ^ object type
```

(See [here](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUCGAuKA7ArgLYBGEATgDQoC+A3CgMYD2uAzsFKwJaFgA2EHABIA8sQBWAWQxgAPDApQAFAEoEAPk7AyXXAHNNiVOmxQARMAjszNet14CAdBnopQkKACEEyNFGI4BCTkVHSMLOxQupZkrBAMwFwswmJSMvJQAGReiqoaWjr6hr4mOBZWwGZU6AHmltahrtHkcQlJuM70zbHxiSyOxLRAA) for example)

Any idea if there's a workaround/fix?

**Comment by kogai** [comment]
I'd encountered the same situation.
It seems working properly up to [0.53](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AuAueASA8gIwCsBZKABwB4BvKdAZ1RgEsA7AcwF94AyeSvdZgFcAtnhAx2AGnjkAKgD4AFLICU8ALzz4eAPY6IIKM3kBuAFBnUAOijnreO1bAmgA).

**Comment by zerobias** [comment]
`&` never worked as you expected, you shouldn't use it for merging object types into one

Type spread works as usual

https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUCGAuKA7ArgLYBGEATgDQoC+A3CgMYD2uAzsFKwJaFgA2EHABIA8sQBWAWQxgAPDApQAFAEoEAPk7AyXXAHNNiVOmxQARMAjszNet14CAdBnopQkKACEEyNFGI4BCTkVHSMLOxQupZkrBAMwFwswmJSMrJIUI7ZQgCiAB4YCfLqitmOeYXFnprUiqoaWjr6hr4mOBZWwGZU6AHmltahrtHkcQlJuM70o7HxiSyOxLRAA

**Comment by wchargin** [comment]
> `&` never worked as you expected, you shouldn't use it for merging object types into one

Surely you can understand why this is confusing. The docs explicitly say, "When you create an intersection of object types, you merge all of their properties together." Furthermore, it looks like OP wanted to use `A & B` to indicate an object with all of the properties of both `A` and `B`. [This is the intended use case of object intersection types, with verbiage taken verbatim from the docs.](https://flow.org/en/docs/types/intersections/#toc-intersections-of-object-types)

The behavior that everyone is expecting is both the natural behavior (i.e., type-theoretically, this is what an intersection type is) and what is listed in the docs. On the other hand, type spread is not listed in the docs anywhere.

The fact that it does not work is very clearly a bug in Flow—either in the code or the docs. How are developers supposed to use Flow when the documentation describes a perfectly nice system that simply is not what Flow implements?

**Comment by SamChou19815** [comment]
Closing since $ObjMap is deprecated. It works well with mapped type
