### ISSUE TITLE
Options object destroys type checking.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#5487]
A simple options object applied as a spread do an object seems to mess up type checking.

```js
type Foo = { a: number, b: 'foo' }

const newFoo = (a: number, options?: {} = {}): Foo => ({
  a,
  b: 'foo',
  ...options
})

newFoo(1, { b: 'a' }) // No error!
```

Here's a [Flow Try](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvKBDAXFAdgVwFsAjCAJwBopicByAMwVqgF8AoNgYzlwGdg8EAO7xEKABTY8RUpShwwwAJY9eAfhyoWyNCwCUOUcgB8UcajZRMFS9TqM4tG1YB0bhctVt9HXMNHiAIxU6DRQtBjM+lAA9DFQAHKI5GRwZACEQA) link.

I would expect it to throw an error. Am I doing something wrong?

**Comment by kevanstannard** [comment]
I'm not sure why this doesn't trigger an error, but if you change the type of your options to `$Shape<Foo>` it will at least check that `options` has valid properties:

```js
type Foo = { a: number, b: 'foo' }

const newFoo = (a: number, options?: $Shape<Foo> = {}): Foo => ({
  a,
  b: 'foo',
  ...options
})

// Error: Expected string literal `foo`, got `a` instead
newFoo(1, { b: 'a' });
```

**Comment by AndrewSouthpaw** [comment]
Argh! I forgot about `$Shape`! Rats, that's exactly the utility method I was trying to figure out.
