### ISSUE TITLE
for-await statement fails for Iterable objects

### ISSUE THREAD

**Issue by jeswin** [facebook/flow#5489]
For-await on an Iterable&lt;T&gt; is valid, since it falls back to obj[Symbol.iterator] if obj[Symbol.asyncIterator] is not found. However, flow complains with the message  '$Iterable (This type is incompatible with $AsyncIterable. Property `@@asyncIterator` is incompatible:)'

```javascript
async function test() {
  for await (const i of [1,2,3,4]) {}
}
```

**Comment by dperetti** [comment]
Sounds more like a bug than a "feature request" ?

**Comment by dperetti** [comment]
[My workaround](https://flow.org/try/#0KYDwDg9gTgLgBAE2AMwIYFcA29noHYDGMAlhHnKgM4CehAglFKtQDwAqAXHA06wFQA+AQAoAbqkzpgXNgEoudGoQCSMYEwBGmYCwAkAUW0BbYHhhtqYHWwA0cPOiMb1QuAG8AUHDhRgMdFDkwmISUlyoeNTy3EoEquqoWjoGxqbmltZ2Dk4uArIeAL4eHlS0BHC4hCRkcGqUMMKy7l4V0BQA7qjE8MIEZPVwxHAQyBSxPMzCANoAjDYATDYAzDYALAC6sk1uRUUeQA
) is to use an helper function like this to cast to AsyncIterable:
```js
export default function asyncArray<T: Array<*>>(value: T): AsyncIterable<$ElementType<T, number>> {
  return ((value: any): AsyncIterable<$ElementType<T, number>>)

async function test() {
  for await (const i of asyncArray([1,2,3,4])) {}
}
```

**Comment by goodmind** [comment]
Related https://github.com/facebook/flow/issues/5491

**Comment by SamChou19815** [comment]
This now works
