### ISSUE TITLE
Functions mapping object values and unwrapping higher kinded types

### ISSUE THREAD

**Issue by almost** [facebook/flow#549]
I'm trying to figure out if it's possible to write a type for a function that takes a mapping object of higher kinded type values  and returns the values stripped of the outer thing.

So something like `function<A>(input: {[key: string}: Thing<A>}): {[key: string}: Array<A>}` except that `A` is different for each key.

An example would be a function that takes a mapping object of arrays and returns a mapping of the head of each:

```
function headsInObject(obj: {[key: string]: Array<any>}): {[key: string]: any} {
  var out = {};
  for (var key in obj) {
    out[key] = obj[key][0];
  }
  return out;
}
```

This type checks but it loses all the information about the object coming in.

Is this impossible?

Sorry for my clumsy explanation, I'm missing the correct terms to describe what I want I think!

**Comment by samwgoldman** [comment]
Does the following example show the kind of type checking you'd hope for?

```javascript
/* @flow */

function headsInObject(obj) {
  var out = {}
  for (var key in obj) {
    out[key] = obj[key][0];
  }
  return out;
}

var output = headsInObject({ a: [0], b: [""] });

(output.a : string); // should error, expected number
(output.b : number); // should error, expected string
```

**Comment by almost** [comment]
Yes, that's it

**Comment by freddi301** [comment]
It would be wonderful to have map type comprehension.
Something like
```javascript
(x: {[id: string]:=> W<A>}): {[id:string]:=> W<B<A>>} => ...
```
where `{[id: string]:=> W<A>}` means for each key-value, not all values are same type.
I spotted something like this in $ObjMap or $ObjMapi magic operators in the source

**Comment by vkurchatkin** [comment]
Yes, `$ObjMap` should solve the original problem
