### ISSUE TITLE
$Shape breaks for nested object indexer property.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#5492]
[Try Flow link](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCywYEMAmXsAqcAvHAN4BQcCywAzgFzlwDaA1sIk3TFAJYA7AOYBdJgICuAWwBGwKHAC+AGgqKKFUJFg0UcAMrYYwIqUrUpmXPixMM2PIVXqKAeldwA6tDZ04AM0FgTXBoeABjCAEeOAFgAHd7a2wSOAAKCDAYPii6AH4mABJ9AAssFAAeJMcsAgA+VLJFAEo7KxrTBrTzXXomMjgCUBgmAEYlVWoAOhnM7NznZo1qdzgAEQh6WIh4eJ8Q7Qjc+Dj4oakwABt8YEMb1IysnOiCuGKyyrvjesaWpi+TCQuj1LA4bP0qNReoxmEMQCM4OMVJDkdNZk8FmolkA).

Use case: I have an factory that provides defaults for an object and allows passing in an `options` object as overrides. I'm typing the options object as `$Shape` of the return type. This normally works fine, except when the return type includes a property that itself has a object indexer type as one of its properties.

**Comment by k** [comment]
Are you looking for something like [this](https://github.com/facebook/flow/issues/5262#issuecomment-343819557)?

**Comment by AndrewSouthpaw** [comment]
That's perfect. Thanks!
