### ISSUE TITLE
Imported string constant breaks typing.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#5493]
This is a very strange one, and unfortunately requires imports across files, so I can't do a Flow Try on this one. 😞 

I have a `constants.js` file which simply contains string constants, and I use them in a file where I map the constants to a handler function.

```js
// foo_constants.js
// @flow
export const LOADED = 'lesson_plan/LOADED'

// foo.js
// @flow
import * as c from './foo_constants'

type StateT = { loading: boolean }
const handlers: { [string]: (any[]) => StateT } = {
  [c.LOADED]: (state: StateT) => ({ ...state, loading: 1 }),  // Does not throw an error
}
```

Strangely, if I inline the constant, the error show up:

```js
// foo.js
const handlers: { [string]: (any[]) => StateT } = {
  ['LOADED']: (state: StateT) => ({ ...state, loading: 1 }),  // Error
}
```

Or, if I redundantly specify the return type of the function, the error shows up:

```js
// foo.js
const handlers: { [string]: (any[]) => StateT } = {
  ['LOADED']: (state: StateT): StateT => ({ ...state, loading: 1 }),  // Error
}
```

Can others reproduce, or know what's going on here?

**Comment by SamChou19815** [comment]
These issue should be resolved after types-first
