### ISSUE TITLE
Still Broken?  module.system.node.resolve_dirname doesnt work 

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5494]
This has been reported a few times - figured it woudl have been fixed by now since its been broken for a long time now (version 58 i believe). 

module.system.node.resolve_dirname will break Flow 100% and it stops reporting any/all errors in the project.

See #5225 #5180 

Can we please get this looked into?  It sucks to have to use relative urls for everything just to support this.

![image](https://user-images.githubusercontent.com/15365418/33817811-584f1f3a-ddf6-11e7-8b44-c6d8c4f95c85.png)

`2 !== string`

**Comment by bradennapier** [comment]
Or in the minimum just remove it completely as a feature since its broken?

**Comment by stayman** [comment]
We were able to resolve this issue in our codebase by following the advice in https://github.com/facebook/flow/issues/5180#issuecomment-344226227

**Comment by on3iro** [comment]
@bradennapier I can confirm this - still not working for me either. Even if I apply the suggested methods from #5180

**Comment by apsavin** [comment]
It works, but not as you expect.

`module.system.node.resolve_dirname` marks a directorty as similar to `node_modules`.
Files in folders like this ignored by default if you don't use such files in your project (in some directory outside the `node_modules` and `src` if you marked `src` as `resolve_dirname` directory)

**Comment by on3iro** [comment]
@apsavin ok, so considering the scenario that I want to resolve imports from inside source like

```js
import myModule from 'myModule'
```

What steps would I have to take?
I already set `module.system.node.resolve_dirname=./src`, but this doesn't seem to help. Is there anything else I would have to do?

**Comment by apsavin** [comment]
You should remove 

`module.system.node.resolve_dirname=./src`

And add

`module.name_mapper='^myModule/\(.*\)$' -> '<PROJECT_ROOT>/src/myModule/\1'`

**Comment by on3iro** [comment]
@apsavin Ah thanks - that works. It's a bit unwiedly, but at least now we can update our Apps. Thanks! :)

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
