### ISSUE TITLE
Updating = Flow Broken (v0.61)

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5495]
I keep running into an issue where whenever I do basically anything flow stops reporting any/all errors and I have to restart atom completely.  It seems like Flow is just completely broken at this point. 

I posted about the resolve_dirname thing but even without that configuration if I edit `.flowconfig` then all errors stop reporitng for flow until I quit and restart atom.  I have restarted about 65 times in the last 2 hours.

I have "Debug LSP" checked but that appears to do nothing so I dont really know how to debug anything at this point.

![image](https://user-images.githubusercontent.com/15365418/33821562-19b24e24-de09-11e7-9d6a-8defa7dea593.png)

```
[ignore]
.*test/.*

[libs]
./internals/flow/definitions
./node_modules/ioredis-utils/flowlibs

[options]
unsafe.enable_getters_and_setters=true
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
esproposal.export_star_as=enable
; module.system.node.resolve_dirname=node_modules
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
suppress_comment=\\(.\\|\n\\)*\\$FlowIgnore
```

**Comment by jpolo** [comment]
I have same problem and I cannot upgrade flow to 0.61.0. I have a slightly different problem. At first run, flow does not report any error. Then when I save a specific file, it seems to "unlock" all errors and they are reported to the console.

**Comment by samwgoldman** [comment]
I can assure you that Flow is not "completely broken." There's not enough information here for me to guess what is happening for you.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
