### ISSUE TITLE
React.PropTypes.bool: Unexpected token bool

### ISSUE THREAD

**Issue by delta143** [facebook/flow#550]
I tried to complile the foolowing code block using Flow 0.12 and got an error "Unexpected token bool" in the code line: ` React.PropTypes.bool`. 

It worked fine for `React.PropTypes.object`, but it doesn't work `React.PropTypes.bool` or `React.PropTypes.number`.

=====
    /* @flow */
    import React from 'react';

    class GridRow extends React.Component {
       static propTypes: {
         o: React.PropTypes.object,
         b: React.PropTypes.bool,
         n: React.PropTypes.number
       };
     }

**Comment by jeffmo** [comment]
In this case you want to use `Object`, `bool`, and `number` (respectively).

`PropTypes` is for React's built-in *runtime* typechecker (independent of Flow). For annotations on an object like you're doing here, you just want to use a regular old Flow annotation.

**Comment by samwgoldman** [comment]
`React.PropTypes.blah` is an expression in the runtime language, but here you're using it in the type language.

This also fails:

```
class GridRow extends React.Component {
  static propTypes: {
    b: React.PropTypes.string
  };
}
```

What you want is something like this:

```
class GridRow extends React.Component {
}
GridRow.propTypes = {
  o: React.PropTypes.object,
  b: React.PropTypes.bool,
  n: React.PropTypes.number
}
```

In the future, we might support the experimental proposal for class properties, so you could write something like this (note the equals sign):

```
class GridRow extends React.Component {
  static propTypes = {
    o: React.PropTypes.object,
    b: React.PropTypes.bool,
    n: React.PropTypes.number
  }
}
```

Note that you can also specify the types of props with flow syntax in ES6 classes, like so:

```
class GridRow extends React.Component {
  props: { o: object; b: bool; n: number };
  static defaultProps: {};
}
```

But it's alway good to define `propTypes` if you're writing a library for others to use outside of flow.

HTH!
