### ISSUE TITLE
Can I mark a function parameter read-only - immutable (object params) (yes I know about variance)?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5501]
I know about covariance, contravariance, bivariance, and invariance..

Documentation:
- https://flow.org/en/docs/lang/variance/
- https://flow.org/en/docs/types/interfaces/#toc-interface-property-variance-read-only-and-write-only

I would like to declare a normal function parameter as read-only though, and I can't do that with those methods, nor with the special `$ReadOnly<T>`.

For example, and this is just for demonstration because `$ReadOnly<T>` does not work with a primitive type:

```js
function square (a: $ReadOnly<number>): number {
    return a * a;
}
```

**Comment by jcready** [comment]
The only way to do with you want right now is to set this project-specific setting:
 [`experimental.const_params`](https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean) in your `.flowconfig`.

> Setting this to `true` makes Flow treat all function parameters as const bindings. Reassigning a param is an error which lets Flow be less conservative with refinements.

**Comment by lll000111** [comment]
@jcready 

> Why doesn't variance work for you?

How would I do that given the example function? I don't see how. It only seems to be for object properties.

**Comment by jcready** [comment]
This seems to work as you'd expect, but I'm not 100% sure this works the way I think it does:

```js
function square <+T: number> (a: T): number {
  return a * a;
}
```

**Comment by lll000111** [comment]
I turned on the flowconfig option.

However, that option leaves the issue of immutable object parameters: The constant is only the reference itself.

Since I don't actually want to declare the properties of a given object type used as input parameter as constant I still have this problem for objects as parameters:

```js
type MyObjType = {foo: number};

function square <+T: MyObjType> (a: T): number {
  a.foo = 42;
  return a.foo * a.foo;
}
```

[Flow Try](https://flow.org/try/#0C4TwDgpgBAsiDyAjAVgFXNAvFA3gMwHsCAuKAOwFcBbRCAJwF8BuAKBbwrIGNgBLAslADOARwoBDOtAA8AalSk4SNBgB8UABTjSqAJSlKNerhZQo4gHSECUbABYATKzNTgFOoMvWoAKnNWiVgYWIA) &mdash; no error.

**Comment by zerobias** [comment]
You should carefully check before using + - variance symbols as it seems like they should not work in functions and I noticed that it has almost no effect on function types, only on classes

**Comment by jcready** [comment]
Does this not work for you?

```js
function square <+T: $ReadOnly<MyObjType>> (a: T): number {
```

**Comment by lll000111** [comment]
I wrote about `$ReadOnly` in th einitial comment &mdash; and then promptly forgot about it...

Anyway, just

```js
function square (a: $ReadOnly<MyObjType>): number {
```

is enough now, [FLy Try link](https://flow.org/try/#0C4TwDgpgBAsiDyAjAVgFXNAvFA3gMwHsCAuKAOwFcBbRCAJwF8BuAKBbwrIGNgBLAslADOARwoBDOtAAU40gBIAShHEATeGQA2IADxwkaDAD4AlKUo16uFlCjiAdIQJRsAFgBMrW1OAU6ghycoACo7RyJWBhYgA).

**Comment by lll000111** [comment]
Just for the record, `$ReadOnly<...>` is not free of side effects. I suddenly get trouble in completely different places when I declare read-only parameters this way. They _definitely_ are read-only for the function where they are declared thus (actually, _all_ those objects are, the kinds of objects where I tried to use this in my code are "write-once, read many times, never modify"). However, I get Flow errors of the type "cannot decide which case to choose, please add type annotation to XYZ". Without the `$ReadOnly` Flow has no such trouble! Also, while I'm more than diligent adding type annotations, adding one to some random property within an object literal used as direct parameter for a function is silly. I'd have to assign it to a `const`, give that const a type annotation and use the `const` as parameter instead of using an object literal - which I find a bit silly. Shouldn't it be _easier_ for Flow when something gets a read-only status? There is something about how `$ReadOnly` is expressed internally that (over)complicates things.
