### ISSUE TITLE
Object map with string/number union keys can fail to validate

### ISSUE THREAD

**Issue by esturcke** [facebook/flow#5503]
I'm a little unsure how to describe the problem, but I've simplified it down to the [following](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAKA3lA2gZ2AJwEsA7AcwF0AuKYgVwFsAjCfKAHyjyLKgF8BKZAD4oANziEAJgCgAxnGJ4oAMwTV4iFKkFIRtYpIjKSEGVChyFSxgEN8ARmqYA1hBCPOBEqQA0UVyAATNR0TCx8yFAubh4ARDhw9NBc3rF+AcFQ9gAM2XzSqnCotg6CUAD05So2hAA2ONKWisBQJYGR0e7U8YnJXmRp-m6ZOXm8BQjFdoFllVAA7nD4zjgAhNJAA):

```js
type Foo = ({ [string]: number | string }) => void
const foo: Foo = () => undefined
  
const bar1: { key1: string, key2: number } = { key1: "some string", key2: 100 }
foo(bar1)  // fails

const bar2 = { key1: "some string", key2: 100 }
foo(bar2)  // works!
```

For `bar1` where the type is specified, the call to `foo` is failing with:

```
5: foo(bar1)  // fails
       ^ object type. This type is incompatible with the expected param type of
1: type Foo = ({ [string]: number | string }) => void
               ^ object type
Property `key1` is incompatible:
1: type Foo = ({ [string]: number | string }) => void
                           ^ number. This type is incompatible with
4: const bar1: { key1: string, key2: number } = { key1: "some string", key2: 100 }
                       ^ string
```

I don't see that when the type is not specified in `bar2` even through flow deems it to have the same type: `{key1: string, key2: number}`.

Am I missing something obvious here?

**Comment by jcready** [comment]
The type `{ [string]: number | string }` says that for every key the value must be (and/or be able to be) either a string or a number. Whereas the type `{ key1: string, key2: number }` says that `key1` must **only** be a string and `key2` must **only** be a number. A Foo function expects to be able to set any property of the object it is passed to **either** a string or a number, but it wouldn't be allowed to set the property "key1" to a number for `bar1` because of the type you cast it to.

**Comment by jcready** [comment]
Change the type to this any it will work (note the `+`):

```js
type Foo = ({ +[string]: number | string }) => void
```

**Comment by esturcke** [comment]
Yes, this worked @jcready! Thank you, I think I understand the `+` a bit better now. The default for me is to think of immutable data structures, but it looks like that's not what I was expressing with my types and in this case it matters.

Your explanation also led me to find the reference in the docs on [Covariant (read-only) properties on interfaces](https://flow.org/en/docs/types/interfaces/#toc-covariant-read-only-properties-on-interfaces).
