### ISSUE TITLE
Interfaces suppress optional property errors

### ISSUE THREAD

**Issue by jesseschalken** [facebook/flow#5504]
```js
interface Bar {
  x?: string
}
  
function foo(bar: Bar) {
  if (bar.x !== undefined) {
    bar.x.charCodeAt(0) // TypeError bar.x.charCodeAt(0) is not a function
  }
}

let y: {} = {x: 1}
foo(y)
```

This code passes Flow, but it throws "TypeError bar.x.charCodeAt(0) is not a function" at runtime.

If I change `interface Bar {...` to `type Bar = {...`, I get this type error instead:

```
    13: foo(y)
            ^ object type. This type is incompatible with the expected param type of
    6: function foo(bar: Bar) {
                         ^ object type
        Property `x` is incompatible:
            6: function foo(bar: Bar) {
                                 ^ property `x`. Property not found in
            13: foo(y)
                    ^ object type
```

I'm even sure the error it's reporting is the same error that occurs at runtime, but it's at least reporting an error.

Why does changing `interface ..` to `type ..` change the result?

**Comment by samwgoldman** [comment]
Yeah, this is a bug. `{} <: { p?: T }` is an error for exactly this reason. The inhabitant of `{}` might have a `p` property through width subtyping, which is incompatible with `T`. The typing rules are correct for object types, but not for interfaces.

**Comment by jesseschalken** [comment]
@samwgoldman What is the intended difference between interfaces and typedefs, anyway?

Additionally, this issue suggests that `x?: string` is (or should be) identical to `x: string | void`. Is this the case?

**Comment by SamChou19815** [comment]
Now it correctly errors
