### ISSUE TITLE
Issue with very basic mixed types

### ISSUE THREAD

**Issue by maxsalven** [facebook/flow#5505]
```
type Multi = {
  foo: number | string
}

type Single = {
  foo: number
}

function expectsMulti(arg: Multi)  {
  return arg
}

function doSomething(arg: Single) {
  expectsMulti(arg)
}
```

This gives me an error `Property foo is incompatible`. However I am passing an object where `foo` is a `number` to a function that expects an object where `foo` is a `number or a string`. Why is this not allowed?

If I change things to not be inside an object, then it works fine:
```
type Multi = number | string

type Single = number

function expectsMulti(arg: Multi)  {
  return arg
}

function doSomething(arg: Single) {
  expectsMulti(arg)
}
```

**Comment by apsavin** [comment]
Because your `Multi` type is mutable.
So it's possible to set a number to `foo`.
But it means that object of type `Single` passed by reference will be changed and will be not of type `Single` anymore.

```
type Multi = {
  +foo: number | string
}
```
^ so this should fix your issue
