### ISSUE TITLE
Incorrect result of typing and `unknown` in `type-at-pos` when using spread types

### ISSUE THREAD

**Issue by burdakovd** [facebook/flow#5506]
In this case type-check should've failed but Flow succeeded it, and doesn't show what's behind the `*`: https://flow.org/try/#0PTAEAEDMBsHsHcBQjgCpWNK0ODKAFUAXlFwBcBDMgU3wCdYAHAZ02xwBFCSOBLZxlQDGAC3pNWWYMjIBPRtVABhWAFtGsAHbVNZACrzqAHnwA+YqAAU+AJTFzAN1i8AJgG5k1AB4a6ZUHIKoACy1HQA5tQuRgDydLzhvJoU0ABcoADeAL4ANKAAkpoAVtRCNC7p2eYkGQB09XEJSSl59bWFJWVRWR6I3r7+gYoAEgkiYXEuYSrqWjpkRh2l5ZVZ1aAmDCymlpigQmoa2rrpM0fzBgqbEqY5iHZE5mdzupfGACR8kJDXLHlLXRcplMvSGIQojHIVGoelg4hYRgIq3Wlge5neAFEvBQyoizB4wcEIXwBMIRLD4cwjFxkRZUfZQJjsbiuCDPD5YH4AoZlFptGUsYxoLwhLwFkjMrlQDTJSjMETIZQaBStlSCLd5cT+IIyKIVRJqWY7mjQKNwuM6JNpocXgtQhEoni8qy2YhIABXTRlXhaALUZhkXY4A6aflkU585aC4WihYZZKqajpAPxTThKWoDU2dJmi1WujPY5xhNJ0AppLhPKRTRTOjpTTu1QAIzCeQokXrjZbdDWmT2IYDZcY6QVUOVcNVRnjFETybIqfTKJNlgyoBL6QA5ONZBvQFkbB5g1pBy5h+DFdD9QjM3Tl6vq7X0gBGPcH-vH-wiWBCCwhsOWAQ8lPN8cBAAIRH4Msv3daAXFAEQKAcRRIAoXhoCiPJmCSIRFDIC1FH4TQN38ChNFkPCKwCWBQEYd1-CSANqAoODYEgUAKCwPYwLwqgyyofhIF4f1uSCOhqAAR3dXgxMTXRmDuUCwCbKT-BgBB2OgOB4GYUBINIuCUmYaiXFgf0iP8Zgv3gUB4AQwZxhEgidNsnRQHdLC01AYjDAAWioHyNGYDcuLARhUzIHTLE9ABrTQEE0Gw9jEsh3ToTR4O-DwsmQIA

In this other case it should've succeeded, but Flow rejects it and similarly doesn't show what the type is:
https://flow.org/try/#0PTAEAEDMBsHsHcBQjgCpWNK0ODKAFUAXlFwBcBDMgU3wCdYAHAZ02xwBFCSOBLZxlQDGAC3pNWWYMjIBPRtVABhWAFtGsAHbVNZACrzqAHnwA+YqAAU+AJTFzAN1i8AJgG5k1AB4a6ZUHIKoAASvADmItR0APJ0LlEq6lo6ZEYAkpoAVtRCNC4AXKAA3gC+5iQmDCymlpigQmoa2rqFiU0pBgqVEqYANIh2ROZtybqdxgAkfJCQ3Sy9oBnZudQupqYeiIGKALIUjORU1Hqw4ixGBIWl5VaD5hMAol4UuRdmHtuge4x8AsIiJzOzCMXCuZQsljuoEez1eXA2nh8sD8AUMyi02lyT0Y0F4Ql4qUuxRKC1BxJutS++0ONEBVWBBD6mG+v0EZFEdIkILM-ShoQiUVi8ToI2aqSKADopQQFlKJVwypsQKBvDi8QTEJAAK6aXK8LQBajMMiU+oYnJkVrmrE+XH48WaCiqaiFY10XiaMIk4phHTCwqaLWqABGUTKvMK-MiMTiCUaowdTpdoDdHrCC19mn9oEDIbD5iKdQammNKcYhW+NOOp3pRiKjudrrI7s94JIkPsViKOaThQA5JFZH3QCUbB4cMXSy5y1SDpRaTWuUVM9nc6G6G3bp3LN2V1FCgBGEdjotaUsiWBCCzFzEmgQLacnnDKsgifgpi9a6AuUAiCgORRmC1IQhGoVZVhTD1QNRBRmFAVR-jqZVgy1fwYAQFU6AYOg4NgVCkLACgs1AOhqG1ZgjQCWAPww19FBeMgtQoaAYMUWBIF-S86lIxi6E0TihA8EpECAA

Second example inline:
```
type ComponentType<P> = (P) => void;

export type HigherOrderComponent<Injected: {}> = <Props>(
  component: ComponentType<Props>,
) => ComponentType<$Diff<Props, Injected>>;

type MapStateToProps<SP: {}> = () => $Exact<SP>;
type MapDispatchToProps<DP: {}> = () => $Exact<DP>;

export type ConnectExplicit<SP: {}, DP: {}> = (
 MapStateToProps<SP>,
 MapDispatchToProps<DP>,
) => HigherOrderComponent<{...SP, ...DP}>;

// explicit
function test(
  connect: ConnectExplicit<{name: string}, {gender: number}>,
): HigherOrderComponent<{name: string, gender: number}> {
  const sp: MapStateToProps<{name: string}> = () => ({ name: 'hey' });
  const dp: MapStateToProps<{gender: number}> = () => ({ gender: 1 });
  const hoc = connect(sp, dp);
  // this should have succeeded since types match
  // but flow errors out
  // and refuses to show the actual type of hoc
  return hoc;
}
```

**Comment by apsavin** [comment]
Try `) => HigherOrderComponent<{...$Exact<SP>, ...$Exact<DP}>;` and it'll fix your second example.

**Comment by SamChou19815** [comment]
Closing since * is no longer supported
