### ISSUE TITLE
Disjoint Union with literal types + Intersection breaks flow

### ISSUE THREAD

**Issue by burdakovd** [facebook/flow#5507]
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQQMYoCWsAdqALygDkAhtaAD40BG1A3MpAK6mEnkMARgAUtfmQBceCaQCUoAN4BfLr1mgMAJjGzpBYmVAAyUAGcUAJyKkA5gsWJQm0eMPzOyoA

Inline example (throws huge Flow error):
```
type Action = 'a' | 'b';

function p1(action: Action) {}

function p2(action: Action & string) {
  p1(action);
}
```

**Comment by apsavin** [comment]
Well, what's wrong with the error? You're trying to call `p1` with `Action & string` while `p1` expects `Action` only.

Flow talks about it, too:
```
8:   p1(action);
        ^ intersection. This type is incompatible with
5: function p1(action: Action) {}
                       ^ string enum
```

**Comment by burdakovd** [comment]
Hmm, It is an intersection.

If I understand what intersection is, it's that in `p1` variable `action` must be one of the enum values and be a string. From that it follows that it must be one of the enum values, from that it follows that it should be allowed to be passed to `p2`.

The real code had complex `Action` type composed of many disjoint objects, and then I had a wrapper function that worked on them under assumption that they have `type: string` field, and it did `Action & {type: string}` and somehow such `&` made it impossible to pass them further to functions expecting `Action`.

I.e. `x \in A & B => (x \in A) AND (x \in B)`

**Comment by samwgoldman** [comment]
Yeah, this seems like a bug to me. `A & B <: A` should always be true.

**Comment by SamChou19815** [comment]
The problem seems to be fixed a long time ago
