### ISSUE TITLE
unclear-type reports generic restrictions

### ISSUE THREAD

**Issue by villesau** [facebook/flow#5510]
unclear-type reports following: `const fn = <T: Object>(val: T) => val;` 

As far as i understand, Object in this case just restricts type to be an object, but infers the rest, right? So it is similar to `const fn = (val: *) => val;` or `const fn = <T: *>(val: T) => val;` but with slightly more restricted type?
That means Flow shouldn't complain about unclear-type in case of defining generics.

**Comment by villesau** [comment]
Oh, i just realised that `const fn = <T: Object>(val: T) => val;` actually removes the type information:

https://flow.org/try/#0FAYw9gdgzgLgBAMwnAvHAPAFQFxwPIBGAVgKYgwB8AFAG4CGANrpgJSoVz0OiSyIQAmVBhxwAVNS7M2KDlx7R4SAMzDajXGJlzGwPeEVwwBYQG8EuAKwBfANx6kVYywB0ATzjAA9F6QCnBK4ePnAwbgAOJAC0JABOsWCx3r4QygFBcCFhkTHxicBwhUWFQA

That said, is there _any_ way to restrict the inferred types?

**Comment by jcready** [comment]
You can try:

```js
const fn = <T>(val: T & {}): T => val
```

**Comment by villesau** [comment]
Thanks @jcready, really good tip!

I refined it a bit and this seems to work too: `const fn5 = (val: * & {}) => val`

see https://flow.org/try/#0FAYw9gdgzgLgBAMwnAvHAPAFQFxwPIBGAVgKYgwB8AFAG4CGANrpgJSoVz0OiSyIQAmVBhxwAVNS7M2KDlx7R4SAMzDajXGJlzGwBXyQAWYVkka4mOADI4AbwC+LZu067wi-gFY1U8dbuOLlxwIaFweu58YATCtgi4nvYA3HpIVNEsAHQAnuEA9HlIAukEWbkFcDDZAA4kALQkAE6NYI3ABSolZXAVVbUNza2pEIZdmQjthSNjABY9eX31TS1twEieYwghk16z84sDK0A
