### ISSUE TITLE
$NonMaybeType with optional $PropertyType - incompatible with empty

### ISSUE THREAD

**Issue by danharper** [facebook/flow#5512]
Given the following:

```ts
type A = {
  foo?: {bar: string}
}
```

If I try to get an alias for the foo property:

```ts
type Foo = $NonMaybeType<$PropertyType<A, 'foo'>>
```

I can use it without errors, but it errors if I try to assert a type that it's incompatible with `empty` (like this, or by passing it to a function expecting `Foo`):

```ts
declare var foo: Foo

// no errors
foo.bar.toUpperCase();

// ({bar: 'f'}: Foo)
//  ^ object literal. This type is incompatible with
// ({bar: 'f'}: Foo)
//              ^ empty
({bar: 'f'}: Foo)
```

However it's fine if I double up the `$NonMaybeType`:

```ts
type Foo = $NonMaybeType<$NonMaybeType<$PropertyType<A, 'foo'>>>
```

* [Erroring Repro](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phhRxwD8AXBQEYCGATswM4YcCWAOwDmAX1TjMuAgDE6pMABIAcnEEBZNlhZ4AKtIA8igAoc4+Dtn34DhADRgA5LTiOAfG6phUAEzwBjGE4CADdOGjpmOTh0FwA6dg44jDgAVRwLAGE2bjwACgBKAG50PPJE5mdHUSi6AvRUIA)
* [Passing Repro](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phhRxwD8AXBQEYCGATswM4YcCWAOwDmAX1TjMuAgDE6pMABIAcnEEBZNlhZ4AKtIA8KtZu17DigAoc4+Dtn34DhADRgA5LTjuAfH6pgqAAmeADGMJwEAG6cNHTMcnDoXgB07BwpGHAAqjh2AMJs3HgAFACUANzoJeTpzJ7uogl0ZeioQA)

**Comment by samwgoldman** [comment]
Thanks, this seems like a bug.

**Comment by holman** [comment]
Think this issue can be closed now; I think it might be fixed.

I ran into this today and this issue pointed me in the right direction and fixed my problem. ✌️ The `Erroring Repro` link above no longer errors out now, either.
