### ISSUE TITLE
Flow complains when trying to access element properties on Event.target/currentTarget

### ISSUE THREAD

**Issue by carrickjason** [facebook/flow#5513]
This may not be a bug as much as it is a question.

If I have an event handler in a React component like so:

```javascript
handleClick = (e: Event) => {
    console.log(e.currentTarget.name)
}
```

Flow complains because name is not a property in type EventTarget.

Shouldn't EventTarget be the same as type HTMLInputElement?

**Comment by samwgoldman** [comment]
Lots of related discussion already: https://github.com/facebook/flow/issues?q=is%3Aissue+Event+currentTarget+is%3Aclosed
