### ISSUE TITLE
Flow fails to error when accessing undefined key on object

### ISSUE THREAD

**Issue by peterwj** [facebook/flow#5514]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGATgK4DGGYAvGAN6phgDWeWAXGAM6kCWAOwDmqAL4BudBTgDePWmAAUjZm05gARAENuAEygaANGK7FyVAJSTUoMAgAWWMLrh5uYGIIIBGAExg8EhI4EjAAIzJqTwEfAGYwATgMAH5kNGBgHgA6WC0hSW4cmDywAB9SsCgtGG48Aqy1MoqqmrqgA

Flow normally errors when you attempt to access a key on an object when that object's Flow type lacks the requested key.  However, Flow will **not** error if that illegal access is subsequently used in a boolean computation; see the `/try` link above.

Note that Flow **will** error if you attempt to access a subsequent property or use the illegal access as the operand to an arithmetic operation.

**Comment by pjm0616** [comment]
Related to #698 #3318 #4763
You can write like `(s.flag:*) || false;` as a workaround, but type refinement doesn't work with that.

**Comment by samwgoldman** [comment]
This is by design -- property accesses in conditional positions are often used for property testing, so Flow allows you to write `if (o.p) { ... }` even if the type of `o` does not declare a property `p`. Note that `o.p` has the type `mixed` within the conditional block.
