### ISSUE TITLE
Unexpected behaviour with a mapped array of objects 

### ISSUE THREAD

**Issue by gwyneplaine** [facebook/flow#5515]
I have an array of objects of type <T> where T is the following shape: 
```
type T = {
  a: string,
  b?: string,
  c: Array<string>,
  optionalProperty?: boolean,
}
```
This array is then passed into a map method of the following shape 
```javascript
array<T>.map(({ optionalProperty, ...restOfObject}) <T> => restOfObject);
```
that strips away an **optional** property. The returned array of objects is then assigned to a property within a typed object. The property is typed as an Array of <T>. 

The map method is given a seemingly valid return type.  However I get the following flow error as a result. 
```javascript
Property `finalised` is incompatible:
24:   dependents: arrayOfObject.map(({ optionalProperty, ...restOfObject }): objectType => restOfObject),
                                                           ^ property `optionalProperty`. Property not found in
24:   dependents: dependents.map(({ optionalProperty, ...restOfObject }): objectType => restOfObject),
                                                                            ^ restOfObject
```

I would expect, given that the removed property on <T> is declared as optional, that this would not error. 

Please find the reproduced example below, note that this does not error in 0.59.0 but does in 0.60.0 and above: 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAme+AdsaRgCq4EC8YA3qmGKQIYC2eAXGAM4YATgEtSAcwA0LMNnwB+PoNETprYmQoBjEXn58AgkKHssAHmVjxAPjVgoY9jBH88hRWABGcODDztSaQBfdDkCLQALAPE9PGpaMAZmdRI8cjSMfTAjE3MNNIp4-FtUENQtOFJBIlT0yj58uqL6JhkObj4AcnZPLU67MK6evrtG7V0sgG1OgEZ+sE6AJnnOgGZOgF07Bw5nV0I+YQBXPGD0CqqMGs0MrJzTMzGMmmLEsEmnyg2AbnPK6si0ViGD4gIkwJeLWS1wKtwatUK-AAdJx2DgABToxj2Rx7NySMBIolCPRXIIASnhN0okMS1jAJME5LsJL87FcADk4Bg9F1SNyCBE8CT+qUgA

**Comment by jcready** [comment]
Changing `dependentType` to an interface seems to do the trick:

```js
interface dependentType {
  name: string,
  type?: string,
  dependencies: Array<string>,
  finalised?: boolean
}
```

**Comment by samwgoldman** [comment]
Unfortunately, changing to an interface only works due to the bug in #5504, so it will not work when that bug is fixed.

The underlying typing rule here is this:

```
type A = { p: number };
type B = { p: number, q?: number };
function f(b: B) {
  if (b.q !=== undefined) {
    (b.q: number);
  }
}
var a: A = { p: 0, q: "foo" }; // allowed via width subtyping
f(a); // must be an error, or else `(b.q: number)` assertion in `f` is false
```

An interesting aspect of this example, however, is that the destructuring pulls off `optionalProperty`, so we know that `restOfObject` definitely doesn't have that property. Our type system doesn't currently have a way to express that, but that would be enough to allow this program to type check.

**Comment by SamChou19815** [comment]
This now works
