### ISSUE TITLE
Error when Union types includes Object

### ISSUE THREAD

**Issue by rally25rs** [facebook/flow#5516]
See:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCArlFHgE5gC8YAghRQIZYA8A3qmGNvgFxgAzhgoBLAHYBzADRcwAEyYYmA8cQC2AI0pgAPmADymgFZ4Axhj1CREmXMoU4FAZrhwYeJuNkBfAHwA3Oi8BCRklABMNPSMLBxyIQLCYlKy3IrKAkamFmlgDk4ubh5evoHoZnDiwmAUeDhOGAJh5FS0ANoAukGV1ZZ1DRQYEc2krVEd3ejAwGAAKgAWooJgUEyiMCsAFABi8EjycHiC4gDklhhL4gDW+eIiWAB0GUxgZl5g2oYm5hgAlKgBo1HlAnABRJhmBZbPD3ChYGh+MCcbi9GovLI-CzRWEPZ5KJhBHx-IKoGbzJYrHBMQSCY6A+qNCIg8GQ6G4+GI5FyNGWDHfHKWWgcp4vIkk1BAA

If you have a union type that includes `Object`:

```
type Buffer = Array<{
  type: string,
  data: number | Object | string,
  error: boolean,
}>;
```

Then this:

```
const report: Buffer = [];
report.forEach(entry => {
  const data: Object = entry.data;
});
```

Reports errors:

```
20:   const data: Object = entry.data;
                           ^ number. This type is incompatible with
20:   const data: Object = entry.data;
                  ^ object type
20:   const data: Object = entry.data;
                           ^ string. This type is incompatible with
20:   const data: Object = entry.data;
                  ^ object type
```

Flow seems to not notice that `.data` can be of type `Object`.

-----

If you change the type definition and remove the union, making `data` only of type `Object`:

```
type Buffer = Array<{
  type: string,
  data: Object,
  error: boolean,
}>;
```

then there are no Flow errors.

**Comment by apsavin** [comment]
> Flow seems to not notice that .data can be of type Object.

Mmmm?

Flow seems to correctly notice that .data can be of type Object or number or string and it's wrong to assign a variable of type `number | Object | string` to a variable of type `Object`.

**Comment by rally25rs** [comment]
Huh, I originally didn't have the `: Object` type defined on my const variable, but added it to try to give Flow a hint as to what I wanted. But I rearranged my code a bit and now I'm not getting any errors any more, and if I "undo" back to when I was getting errors, I still don't... maybe it was just in a weird state for a run. OK, well, seems fine now... sorry!
