### ISSUE TITLE
Cannot use parameter type inside a polymorphic function

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#552]
function foo<X>(x: X): X {
        var y: X = x;
        return y;
    }

This doesn't check

> identifier X
> Could not resolve name

When there are more complex types, it would be nice to be able to use the actual parameter inside the function (such as `Array<X>` etc.)

**Comment by samwgoldman** [comment]
This is a known issue, being tracked over in #160.

**Comment by samwgoldman** [comment]
@runn1ng just a quick update: the restriction on referencing types is now lifted on the latest master, so your example code will type check now.
