### ISSUE TITLE
Making intersection type exact fails

### ISSUE THREAD

**Issue by nvie** [facebook/flow#5521]
It seems using `$Exact<A & B>` doesn't work as I would intuitively expect it:

    type A = { id: number };
    type B = { name: string };
    type C = $Exact<A & B>;  // error

What I would expect (and my goal) is to combine A & B into this:

    type C = {|
        id: number,
        name: string,
    |};

I'm currently doing this as a workaround.  Is there a more elegant way?

    type AB = A & B;
    type C = AB & $Shape<AB>;

See this [example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeoAlgCYBcoAdgK4C2ARlgE6gC+A3KpjgCFCJOgENGWGgGcUbMrQDmXXohCgAkhSyjooKbGj0UZWLVVh02UAGFhAEgCiAD1EBjFAB58AMlACAfNygoGoegCgEoADiAPK4ADLIanFYUlKgWNBYCqK0KHxWuEJEPn68lji2xUK+dgDKABai2F4BQSFg4aAA6tEASgDSuL3RAKoAcgAiiWAAKikooK6iUimIABSklDQAjAA0YhI0AOQAUrD1tEdcNNYAlG1qsADW65vUoNvXNvfBao5O2HcDjYbFgbBojDIqXkSkgZAyFAOWFe5HeeyRxzOFyO+0gsFgx2YojYV04Nx+7VA-0BKGBoPBeno2DYMHosHoaThCNAeNgiCAA) for a full version.

**Comment by samwgoldman** [comment]
How about this?

```
type A = {| id: number |};
type B = {| name: string |};
type C = {| ...A, ...B |};
```

[Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPqAJYAmAXKAHYCuAtgEZYBOopAvgNypMOAEKES5egENmWOgGcUHCvQDm3foOygAwmLKgAdEdwAaQ0dG8BiEKAAqWBaADGkuY8QAKYpVqgAjGZSMnQA5ABSsAAW9KGgPHTaAJR8oKC2sADWXj7UdP7xiSlptgAkAKIAHtjOKOUcHLAcdMwUcnLKapAUWNBUDNJYOb75QYNhkTGhZpCwsGGskhxxCTrF6WAV1Vi19Y3NoHKM2BwwjLCMcqDdvf2zsIhAA)
