### ISSUE TITLE
No error for non existing prop in object in some cases

### ISSUE THREAD

**Issue by lapanoid** [facebook/flow#5522]
https://flow.org/try/#0MYewdgzgLgBAygeQLIFED6CBCApFBhAFRgF4YBvAKBhgDEBJAJTgIC4YByepg9gGivj4EAOQAibdnCFi+AggAlG4jgqXsKAXwoUA9DsSoMOfAQB0NBAFUGCmHpgBLAGYwAniACuMD2FABbPwBTMFgoAAsHCBgnABsQAHcYeIcYmOiHACdAmECMjJAMmABDKMCADwAHQOAoQIATGG1nGAAKA3QsXEJzKxt5EmJSTl6FdgBKcjsdGDAQHLyC3mLUmABzEBA6gXtTXc1tCGSoYDDW9nHyAWAS7PajLrMaS2eX57YyKZgEACMAK2rYHUQIEorNYGEigA3bIQDwnGAVfIVJbfDywaApNKzeb5DLaajUb5ZIoAawEWg0QA

```
const SOME_OBJECT = {
  FIRST: 'FIRST',
  SECOND: 'SECOND',
  THIRD: 'THIRD'
}

//SOME_OBJECT.FOURTH // if you uncomment this flow will fire error as expected 

if (SOME_OBJECT.FOURTH === 'FOURTH') { // no error, all good
  // ...
}

switch ('') {
  case SOME_OBJECT.FUUUUUUUU: { // Object does not have such prop, but still no error

    break
  }
}
```

**Comment by andreypopp** [comment]
dup of https://github.com/facebook/flow/issues/4543

**Comment by lapanoid** [comment]
closing
