### ISSUE TITLE
How to describe types of objects from libs?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5525]
I use koa's request.state, which is an object for store any developer variables in request

```js
request.state.someProp = 'lalala';
```

but when I use it in my code 

```js
if (request.state.someProp) {
 ....
}
```

I see an error: Error:(...) property `someProp`. Property not found in mixed

What is the right way to overwrite type of such objects?

**Comment by popham** [comment]
Searching for `state` within the various `koa`s from https://github.com/flowtype/flow-typed/tree/master/definitions/npm, I only found `state: Object` declarations. Toying with an `Object` typed variable ([Try](https://flow.org/try/#0CYUwxgNghgTiAEA3W8DWAueB5ARgK3ABcBuAKFQDoBnAewFsQAFGGgB3gF54AiKK4AGbcyASwHwAFJVoNmbAJTwA3qXiTp9Ji1aYqhGCIB2Ac3lk1U6prk74hgK50cIGGdIBfUkA)) I can't reproduce your problem, but I'm not even sure if you're using one of those flow-typed libraries. I suggest (1) providing enough information to reproduce the problem and/or (2) opening an issue in the [flow-typed issue tracker](https://github.com/flowtype/flow-typed/issues) (if you're using a flow-typed library).

**Comment by samwgoldman** [comment]
Yeah, there's not enough information here to diagnose what is going on.
