### ISSUE TITLE
Flow allows calling any method on a function object (e.g. `() => void`)

### ISSUE THREAD

**Issue by burdakovd** [facebook/flow#5528]
Repro (allowed by Flow but shouldn't): https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AYQIbTT4BG0OAvKABQCUoFAfKAG6wCWAJgNzKQCuAOwDGKdrEGhI1YQC48hYmSz0A3olChhAOhQALLILq8AvkA

```
type Callable = () => void;

function f(c: Callable) {
  c.then();
}
```

**Comment by jcready** [comment]
You can use this as your callable type to get flow to throw in your example:

```js
type Callable = {| $call: () => void |}
```

**Comment by samwgoldman** [comment]
Instead of `$call`, use an object type with a callable property, like `{ (): void }`. The `$call` property is an unfortunately leaked implementation detail that can go away at any time. Callable properties are the public API for this.

**Comment by samwgoldman** [comment]
As far as why the original example is not a type error, the statics of function types in Flow are currently `any`-typed. This was a compromise we made a while ago to accommodate APIs that mutate function statics, but it's worth revisiting.

Defining an object type with a callable property is a way to define a function type and it's statics together.

**Comment by saadq** [comment]
Is there any documentation for callable properties? Browsing through the issues, some seem to make mention of this link: https://flowtype.org/docs/quick-reference.html#callable-objects

But that doesn't seem to work anymore.
