### ISSUE TITLE
Array of classes not correctly keeping underlying (extended) classtypes when used as array

### ISSUE THREAD

**Issue by M-TGH** [facebook/flow#5530]
Note: I'm open for title changes, I just crammed everything in there.

Had recently been having an issue whilst working with arrays of my own class items.
Here I found out it seems that when using an array flow doesn't correctly see the full inheritance tree (or something along those lines).

See: [flowtype.org/try/...](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoUYBic5gMYwCGAzsWABYljFwC2ApmFDsmgSWdnAN6oCQzOAC5qAFwBOASwB2AcwDc-fnjjTiEgK55RccQAoAlLzAnTo8pOIA6QWAC8YAOSDHi02AC+qL+nBcAQoTi+ESkYPQAHqL00gAmMrJYLIRxYISx8XJgqmCBwSio7GEBQeFRMbGcLLx8AEZBIupScorKqk1aOvpGqO4mxBoADvTdbn3mllb1wQ6O0669pl4+GADqjJQAboxwGsFB4oQAntlQSXCOZAUw9KJMOACC4odHIk8vADxcAHz2YADaAF1WmsNoRtmlpGlnsdTuc8pcwHppHBoiIEORcJFoqkuNRcMRMRoYLF8LtpHdmMEuAAaNJQQiSADWBlYhXalJweXexzeMKOXy5QV+Dn+0noSBK3Tp4slQu6wNQvjAAFVxRFhtp6LERKtyDEwBpiAkwOZGIJufy0mQUtCXmBJHdYnB6GQUXcVBoKdbIWAeSc4GcuIiCoJ-X8LUF-fIwMBgGBna6wO6wAhdEywAB+JVrCwwdRpWpwCFQL3aSSqQgwR0nRPEaSOO5p8RMukTMh1tlhq2iyPif3-AAMgLpfYHAEZAYDY-Hm0yyJns8qAKIa+hanVgAAq+od0VoNvzuDnqf1UKN2odUONcmJpQvXce-KsgyN5D0Y-5Q8BBhjcdT6bEDm4D+KoRpgIMcAyKIxDooBp4GukmSJLaXqxPQUAyJemxVho5riHQpq7gcsKhk+Lwvm+H7ygOABMP5-rOgGoEAA)

I hope these test-cases explain the situation as needed. If any more information is required feel free to ask (although I don't have much more to add).

If I'm just noting a feature as a bug here feel free to close the issue, however i would appreciate it if an explanation about why this is the case is given.

**Comment by apsavin** [comment]
The error is correct:

```
let fooArray: Array<Foo> = [];
const fooBarArray: Array<FooBar> = [new FooBar(), new FooBar()];
fooArray = fooBarArray;
fooArray.push(new FooBaz()); // FooBaz - another descendant of Foo. Now fooBarArray contains FooBaz instance.
```

**Comment by M-TGH** [comment]
I'm sorry, I didn't fully understand your comment. In which way is the error correct? Should it really not be possible to use an array of FooBar's as an array of Foo's?

Since this works:
```
const a:Foo = new FooBar();
```
I feel like the array version should work as well.

**Comment by apsavin** [comment]
Any FooBar is Foo, but not any Foo is FooBar.

**Comment by apsavin** [comment]
You can push any descendants of Foo in array of Foo's.

**Comment by M-TGH** [comment]
Sounds about right, however my problem is with when giving an array of FooBar's to something that takes an array of Foo's (which should work, right??). It still gives an error in this scenario:
See: [flow.org/try/...](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoUYBic5gMYwCGAzsWABYljFwC2ApmFDsmgSWdnAN6oCQzOAC5qAFwBOASwB2AcwDc-fnjjTiEgK55RccQAoAlLzAnTo8pOIA6QWAC8YAOSDHi02AC+qL+nBcAQoTi+ESkYPQAHqL00gAmMrJYLIRxYISx8XJgqmCBwSio7GEBQeFRMbGcLLx8AEZBIupScorKqk1aOvpGqO4mxBoADvTdbn3mllb1wQ6O0669pl4+GADqjJQAboxwGsFB4oQAntlQSXCOZAUw9KJMOACC4odHIk8vADxcAHz2YADaAF1WmsNoRtmlpGlnsdTuc8pcwHppHBoiIEORcJFoqkuNRcMRMRoYLF8LtpHdmMEuAAaNJQQiSADWBlYhXalJweXexzeMKOXy5QV+Dn+0noSBK3Tp4slQu6wNQvjAAFVxRFhtp6LERKtyDEwBpiAkwOZGIJufy0mQUtCXmBJHdYnB6GQUXcVBoKdbIWAeSc4GcuIiCsBgPc4P6-hagv75GAw2AAMJ0BgU7XZDSc4IohB04j0RgjcS6ezfJVQL3aSQ5aLqPJ6A58z4-HomFRqOA3KzwWSN54GRQ+OuiBsx8T+wdAA)

**Comment by M-TGH** [comment]
See a string/mixed version of this problem: [flow.org/try/...](https://flow.org/try/#0DYUwLgBAtglgHiAJgQQE6oIYE8BcE2ZYA8sCiAfBALwQDaAugNwBQokAzmKjAHYDmBbHkHFO3fpRoMWzAGYBXHgGMwMAPY8IYEJwAUGdMPTYS8JOQCUAb2YQIzAL7NtesbwHGsFxkA)

**Comment by apsavin** [comment]
It’s the same case as above. You can change an Array inside a function. Just use $ReadOnlyArray<Foo> as a type of a function.

**Comment by M-TGH** [comment]
I'll close it for now. However I still feel an Array of strings should be accepted as an array of mixed, even in writable situations. Thanks for the help.

**Comment by apsavin** [comment]
> However I still feel an Array of strings should be accepted as an array of mixed, even in writable situations.

But why?

**Comment by M-TGH** [comment]
Because the singular forms also work, why would an Array change the inner situation? 
E.g:
```
let mix: mixed = 'string';
```
This works, however the array situation does not? But why?
Same as this would work:
```
let mixes: Array<mixed> = ['string', 'string'];
```
However then suddenly this doesn't: 
```
const stringArray: Array<string> = ['string', 'string1'];
let mixes: Array<mixed> = stringArray; // Image as parameter use for a useful usecase
```
To add to the list, this does work when you do not type the string array as an array of strings, e.g.:
```
const stringArray = ['string', 'string1'];
let mixes: Array<mixed> = stringArray;
```

**Comment by apsavin** [comment]
This
```js
const stringArray: Array<string> = ['string', 'string1'];
let mixes: Array<mixed> = stringArray; 
```
does not work, because if you will do

```
mixes.push(5);
```
you'll have a number in your `stringArray`.

**Comment by apsavin** [comment]
This
```
const stringArray = ['string', 'string1'];
let mixes: Array<mixed> = stringArray;
```
Does work because `flow` is smart enough to trace type `Array<mixed>` back from `mixes` declaration.

**Comment by M-TGH** [comment]
I understand the whole it comes from an Array of strings reference history story. However then why does this way in singular form work without raising an error:
```
let string: string = 'string';
let mix: mixed = string;
mix = 5;
```
If the case is that flow keeps the same type on the same reference shouldn't it also forbid this usage since you're throwing a string typed variable into a mixed variable which then effectively should override the type since the reference still has the string type?

**Comment by apsavin** [comment]
Well, it's all about how JavaScript works. If you use an Object (Array, Function, ...) you work with a **reference**. If you use string (number, boolean), you work with a **value**.
