### ISSUE TITLE
Passing non-optional property instead of optional throws Error

### ISSUE THREAD

**Issue by vetvicka** [facebook/flow#5534]
```
/* @flow */

function acceptsObject(value: { foo?: string }) {
  // ...
}

acceptsObject({ foo: "bar" });     // Works!
acceptsObject(({ foo: "bar" }: { foo: string }));     // Error!
```
It is not possible to pass an object with non-optional property where optional property is expected. If I rewrite the example it seems like a bug to me: 
```
/* @flow */
type Optional = {
  foo?: string,
};

type NonOptional = {
  foo: string,
};

function fooFun(maybeFoo: Optional) {
	if (maybeFoo.foo) {
    	// do something...
    }
}

const nonOptional: NonOptional = { foo: 'bar' };

fooFun(nonOptional); // Error! I don't think there should be one.
```

[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDy26AlnAHYCGMYAvGAN6phhRxwD8AXGAM7oAnEuQDmAGlQBfANyoMOfADkKRUhWp1GzVux78hoiTLlQAruQDGa8jrgAxcwAoAtpUwAjXHd2FiZKjAAlFoAkCRQYC5unt5wAHRscMFMLCwhwMBgACZwfHDOuOgAFsIiceXaLJJSchYU-GDkKn7qMDzK5Kr+GvQMtjwA5O6UAgNgxqiJDuSOTZ0tAYGyQA)

**Comment by pronebird** [comment]
Bummer but if types were interchangeable like that then a Dog could be a Cat just because they both have four paws and there is no polymorphism in Flow.

What you should do instead is use a single type and then use a `$Shape` if you wish to omit certain fields within the object type.

**Comment by jcready** [comment]
Your `fooFun` function should be allowed to set `maybeFoo.foo` to `undefined`. That's why passing a non-optional `foo` property is not allowed.

**Comment by jcready** [comment]
Change your type to this and you won't get any errors:

```js
type Optional = {
  +foo?: string,
};
```

**Comment by vetvicka** [comment]
@jcready That makes sense. 
Thank you for explanation!
