### ISSUE TITLE
How to pass flow props through React components?

### ISSUE THREAD

**Issue by ramusus** [facebook/flow#5535]
I create example of my question here
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudejAqUAYhnzliNAB6EaAOwAmlWg0IA6AMKs88hYQA8AbwC+APjBHUYMFyU18ACgCUl62ACQXQgFd88sAMAWQxFRRgaMgBeIwBGEzAAIxiAJhNgM3cTVGzUQWEwELCIsBk5JRVuDW1cOD15QysbRIAuMHkfLESHABociybbBUUHFzcbLxpff0CAGQpiI3VlwgALDHJ1HBYccgT6GLWNrZ3NxLAAajB4jKycgSFySnnJUtlhyrUtHTr9Y3cbKQ2h0ur0AUlgZ1uvg+jYbPRIaCYf1xkN7E5XIMbN4-AEDIoMAA3MxGI6bbZwXbqUiXMBkk6Us60+kUqn0EwGYAE4n8GzZExAA

I have chain of 3 components (could be more) each in separate file. `Middle` component passes all his props through and add one more. How to define flow types for props correctly in case, where middle component shouldn't know anything about props he just passing though? Specifically, I don't want to include type for prop `a` in the file with `Middle` component.

**Comment by apsavin** [comment]
Well, `Middle` component knows about `Last`.  Why not show this fact in it’s props explicitly?

**Comment by ramusus** [comment]
@apsavin in other words, do you suggest to do like this ?
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudejAqUAYhnzliNAB6EaAOwAmlWg0IA6AMKs88hYQA8AbwC+APjBHUYMFyU18ACgCUl62ACQXQgFd88sAMAWQxFRRgaMgBeIwBGEzAAIxiAJhNgM3cTVGzUQgBPHEiQsIiABRYcSii3G0SALjB5HyxEhwAaHLAAHzAAGQpCCrgq-lRBYTAS8MiZOSUVbg1tXDg9eUNp8sryCysbO0UHF1rPbz8AgwHJS3U7wgALDHJ1HB2E+hjH59ed9USwABqMDxDJZHLoApFfqDYZVMA1fY2MiNZqtDruOqolptfCdZFgejY9F4nJjCbkSjXKSyBTKahLLQ6Nb6K6wnZ7dyHY6uJEHGi+fyBRQYABuZiM3xebxGL1IQLAUt+sv+CqVMqq6noJgMwBF4v4NmyJiAA

**Comment by apsavin** [comment]
Maybe something like [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudejAqUAYhnzliNAB6EaAOwAmlWg0IA6AMKs88hYQA8AbwC+APjBHUYMFyU18ACgCUl62ACQXQgFd88sAMAWQxFRRgaMgBeIwBGEzAAIxiAJhNgM3cTVGzUQgBPHEiQsIiABRYcSii3G0SALjB5HyxEhwAaHLAAMjAAEgARDCgoAwAZCkIKuCr2yzB6RubWhzBzflRBYTAS8MiZOSUVbg1tXDg9eUNd8sryCysbO0UHF1rPbz8A8cnLdX-CAALDDkdQ4O4JegxIEgsF3dSJMAAajA8QyWRy6AKRTAE0k0yqYBqjxsZCWLTa+E6pKS5JWVPcNkWTQpHRyGy25EoeKksgUymoJy0Ogu+h++LuD3cz1erhJTxovn8gUUGAAbmYjDDQeCZqDSMiwNq4XqEYbjbqqup6CYDMBVRr+DZsiYgA)
