### ISSUE TITLE
What's is wrong with types?

### ISSUE THREAD

**Issue by budarin** [facebook/flow#5536]
I'm sorry, but flow messages so unclear so I can't understand what is wrong in code

```js
export type ActionType = {|
    type: string,
    payload: mixed,
|};

const ONE_SECOND = 1000;

const START = '@timer/START';
const STOP = '@timer/STOP';
const RESET = '@timer/RESET';
const TICK = '@timer/TICK';

const timerStatuses = {
    STOPPED: 'Stopped',
    RUNNING: 'Running',
};

export type TimerType = {|
    status: 'Running' | 'Stopped',
    seconds: number,
|};

const TIMER_INITIAL_STATE: TimerType = {
    status: timerStatuses.STOPPED,
    seconds: 0,
};

export type AppStateType = {
    +timer?: TimerType,
};

export function timerSelector(state: AppStateType = { timer: TIMER_INITIAL_STATE }) {
    return state.timer.seconds;
}

export default function timerReducer(state: TimerType = TIMER_INITIAL_STATE, { type }: ActionType): TimerType {
    switch (type) {
        case START:
            return { ...state, status: timerStatuses.RUNNING };
        case STOP:
            return { ...state, status: timerStatuses.STOPPED };
        case TICK:
            return { ...state, seconds: state.seconds + 1 };
        case RESET:
            return { ...state, seconds: 0 };
        default:
            return state;
    }
}
```

[Flow Try](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCCBjGBLCA7AFWVQF44BvAHwCg46FiAuOAZximzwHMAaW+sAENEAGwiCAJswC22EMAl9KAXwDc1ahnxs4AeQByAUQD6AZUMBhAwBE4ZAIwAGZ+s3b4pgmgBKBO3AByAAEcaWAoAHpPHwIA9S08HU9dAAV-YNDwqIJUuLdE+G9Dcz8yDOwwyKKSvISdAgBJCwBpdJCKrMaWvPydTKhTGEEYAFcWYBZ-cn46ZJSUw2tmAMGIMBQJAL56OG8AVX19Bv0AcWXvEbw8Ti4t6jUNUEhYBhQ4Ag6oIjeyKhnWIajFjnS7XbgBOCUQKrdYKO47cYJCTAuB4EbSABG4SUD168EaAFlDN5jMcGo00AAZMxeAiGZgfSrfUgUf5sYZjZj9QYc8YsAB0cwW1m29ER+GRzEcfFxT2g8CQbzQ6x5MGAzKm-wA1P0APwMz7MmWuOUvABmlywuDwCE+pmAImAWGgAAp2WrmMqwKr1cQprbKgyGkSSWSKdTonS4MoAJSsnZQYCjKA293Afn9fnivDI9TKR7geVwCTAM2CEYieAWvBW-AB8LeBQjDDhN2A4AGpl+siE4mko7hmloOk8CivVDKT21wjEGOd8Ia6YIgDu2BgGAAFnAXYrgHGlzt6BhBOM4NFfIx-of6InkzbyHB+U+06P3Zz6wNAWMJvz9odjic0bqNedDHqecyXiBh63iMKZjk+Wbtq+X4otyKE-kKixAVeR4nqgXTNJBUE3kmsH3o+z5IawToSiiaZZjROaTFqcD2NhUFgag1SGAQRHEXAMFwQ+CEvtRSIoo47EgSWZYVjAfHEYJqbtsB9D5soQA)

Help me please

**Comment by popham** [comment]
What particular error message do you find confusing?

**Comment by budarin** [comment]
I'm confusing about spread error:
```js
return { ...state, status: timerStatuses.RUNNING };
                       ^ object literal. Inexact type is incompatible with exact type
36: export default function timerReducer(state: TimerType = TIMER_INITIAL_STATE, { type }: ActionType): TimerType {
                                                                                                        ^ object type
```

**Comment by popham** [comment]
I inserted `({...TIMER_INITIAL_STATE}: TimerType)` immediately after `TIMER_INITIAL_STATE` and Flow produced a similar error:

```
28: ({...TIMER_INITIAL_STATE}: TimerType);
     ^ object literal. Inexact type is incompatible with exact type
28: ({...TIMER_INITIAL_STATE}: TimerType);
                               ^ object type
```

The rest operator apparently doesn't preserve object exactness. As a work-around I would destructure `state`:

```js
export default function timerReducer({status, seconds}: TimerType = TIMER_INITIAL_STATE, { type }: ActionType): TimerType {
    switch (type) {
        case START:
            return { seconds, status: timerStatuses.RUNNING };
        case STOP:
            return { seconds, status: timerStatuses.STOPPED };
        case TICK:
            return { status, seconds: seconds + 1 };
        case RESET:
            return { status, seconds: 0 };
        default:
            return { status, seconds };
    }
}
```

You could even destructure it

**Comment by budarin** [comment]
@popham thanks!

It helps in case of a small state.
When it is more complex - it's become boring to type of all structure of a state

**Comment by budarin** [comment]
Is there any full explanations how to work with object types?
It's annoying to get every time cryptic error: 'Error: object literal. This type is incompatible with the expected param type of object type'

```js
type Dictionary<K, T> = { [key: K]: T };
export type Reducer = <S, A>(state: S, action: A) => S;

let reducers = reducers: Dictionary<string, Timer>;
reducers = { timer: timerReducer };
```

[here to try](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCCBjGBLCA7AFWVQF44BvAHwCg46FiAuOAZximzwHMAaW+sAENEAGwiCAJswC22EMAl9KAXwDc1ahnxs4AeQByAUQD6AZUMBhAwBE4ZAIwAGZ+s3b4pgmgBKBO3AByAAEcaWAoAHpPHwIA9S08HU9dAAV-YNDwqIJUuLdE+G9Dcz8yDOwwyKKSvISdAgBJCwBpdJCKrMaWvOpQSFgGFDgCDqh-Kn46NkEYAFcWZgDvWbw8Ti4AuEpA0xgIMBQJAL56VmAEiQW4PFnpACNwpTUNOvhGgFlDb2MG-QbGtAAGTMXgIhmYI0q40mrBgM3mi12+0OxxhLHO+EuzEcfGevXA0HgSCGaAOuxmwCIQzI5BhAGpMlAIaNca4+oS4AAzFZYXB4BCjUzAETnPZQAAU0xgwGYpLA5OlVNIFAFlQhDU+31+-waQJBaDBcGUAEoKDCoMA5lB+VLgAA6Rl29EXFjqZQadkDCTATmCWYieDcvC8-Cq8LeBSzDDhSVw6XMqFkD5fH5-AHA6Jgngq4nAbNCUTiCRG2UhwjEY0J8Jm04sADu2BgGAAFnBxbnTbTTqcMIJ0XBor5GDDu-QLVb+eQ4HaZ7bs1KEYFlqt1ptnqO6L3+8kUsON93x7NrSqZ0643nYfCrgEkQcFGv1Put6gus09-ux5aj5Pp7Pz-OMTwLFL2lJ1AMuOA6TgewjUfDdnzgapDAId8PzgQ9jynU85zOF1sVgkd6G9X1-RgVCPwwm1zzguh3XdfF+iJYg4GsbAy0EKBEAAHmabMCAAPnGOAAG0AGtgEQZhmgAXQhAjPSYoYIwkKNqzILjTGzNB+NjClmE0uBBDLWVTRIQTTFcEV4AtFToygK5WPYziuLYDhuGzZTVKgQSaWeGyvJYITGWYRlPLs2CgA)

**Comment by apsavin** [comment]
You can try to use [this](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcCCBjGBLCA7AFWVQF44BvAKDhoWIC44BnGKbPAcwBprawBDRABsI-ACaMAtthDAxPAL4BuSpQz4WcAPIA5AKIB9AMp6AwroAicMgEYADA5VqN8IwTQAlAtbgByAAI4ksBQAPRungS+Kup4mm5aAAo+AUEh4QRJ0c5x8B56Jt5kqdjBYfmF2bGaBACSpgDSKYGl6XWN2ZSgkLB0KHAErVA+VLTMMPwwAK5MjL4eU3h47By+cAA+fkYwEGAoYr48Y0zAsWKzcHhTkgBGIYpO1fB1ALJ6Hga1OrV1aAAyxncBD0jEGZRGvBoLEmMzm212+0OkOYp3w50Ydgeqm60HgSH6aD220mwCI-TIo1oAGo0lBQUMsV1wLi4AAzRZYXB4BBDIzAISnHZQAAU0JgwEYhLAxPFZNIFB5ZVBtTeHy+P1q-0BaGBcAUAEoKMioMBplBuWLgAA6WlWk5nJgqBTY5m9MTAVn8KZCeDsvCc-CKkIeORTDAhUUTcX08FkV7vT7fX4AiLArgK-GoBSSgOEYj6mMhI3HADu2BgGAAFnBhZnDZSxjQMPwTnAIl56MjG7QTWbueQ4Fah5b02LYX4FksVmtlF3aM3WwlEp3u93e1NzQqh3ao8BR1Hx754Xs5DOVKu4AvUO0GiuLz3TRv+4Ph7vR6i8OjxiS7R-znAqTgGw9XPVcrzgCo9AIO97zgddNwHbcRxRB0MRAucaHdT1vRgGD73gi1d1AmhnWdJkejxYg4AsbBc34KBEAAHgadMCAAPhGOAAG0AGtgEQRgGgAXVBdCcV6TMINDcMoEYox0zQDiyEjElGHkuB+FzSVDRIDijCcAV4BNMQwxCC4aLohjGJYNhOHTEMTJkxiACp02ctilIoWdjNMqAmE42lGFpBzfJAoA)

You can't use spreads and exact types in current version of flow: as @popham said 

> The rest operator apparently doesn't preserve object exactness.

**Comment by budarin** [comment]
@apsavin thanks!
