### ISSUE TITLE
Major: Function type with Date argument accepts a function with number argument

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#5539]
### Flow verisons
Seems to happen on any version I've tried so far:
* 0.37
* 0.40
* 0.42
* 0.50
* 0.57.1
* 0.61

### Code [(Try flow link)](https://flow.org/try/#0C4TwDgpgBAIghsCBhOAbVAjOBjA1lAXigAoA3NAVwgC5YEIBKQgPigAUAnAewFsBLAM4QAPHAB2IZgCgoUKQDMKY7MD5cxUeVy5lKNKGIo8MEDg1qdegkeMlQA3jKgcIwChw2X+QgHQuBXKikEMQMUgC+UlLEWly08Igo6Fh4DADcQA)
```js
type DateCallback = (value: Date) => Promise<any>
  
function foo(value: number): Promise<any> {
  return Promise.resolve()
}

(foo: DateCallback);
```

### Expected
```
7: (foo: DateCallback);
     ^ function. This type is incompatible with
7: (foo: DateCallback);
          ^ function type
This parameter is incompatible:
1: type DateCallback = (value: Date) => Promise<any>
                               ^ Date. This type is incompatible with
3: function foo(value: number): Promise<any> {
                       ^ number
```

### Actual
```
No errors!
```

**Comment by jcready** [comment]
Reduced case:

```js
declare var x: Date;
(x: number); // no error
```

**Comment by jedwards1211** [comment]
whoa!

**Comment by jedwards1211** [comment]
It must have to do with making Flow support comparisons between numbers and Dates

**Comment by ilias-t** [comment]
This a major was a major "WAT" moment for me? Is this intentional. Ideally this should throw an error, but it doesn't.

`const time: number = new Date();`

**Comment by NilSet** [comment]
@jedwards1211 looks like you are correct. Removing instances of Date from the numeric test at https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L7312-L7313 fixes this particular issue, but makes it impossible to perform numeric operations on Dates

**Comment by NilSet** [comment]
One solution might be to remove the numeric attribute of Date and force users to do `Number(myDate) > Number(theirDate)`.

**Comment by hoangmngo** [comment]
Agreed. `Date` and `number` share some common arithmetic operations but they're definitely not the same type.

**Comment by jedwards1211** [comment]
I think it's possible to fix this issue without breaking support for number + Date and so forth.

**Comment by NilSet** [comment]
Funny you should mention number + Date! Turns out `+` stringifies Date, and all the other numeric operators numberifies Date.
![image](https://user-images.githubusercontent.com/4490501/48144552-fb455780-e265-11e8-950c-4864ef7ff897.png)
Meanwhile flow happily accepts `const a: number = new Date() + 12;`
