### ISSUE TITLE
"property children ... not found in ... HTMLElement"

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#554]
```javascript
/* @flow */
var x = document.querySelector('.foo').children;
```

```
$ flow

/Users/chris/Coding/test/test.js:2:9,47: property children
Property not found in
/private/var/folders/4m/px1762nd6y515zdshl6_pz600000gn/T/flow/flowlib_11e25ff/lib/dom.js:361:1,394:1: HTMLElement

Found 1 error
```

This seems especially weird because it looks like this should work with the definitions in dom.js. The querySelector method returns an HTMLElement, and HTMLElement extends Element which has a children property defined.

**Comment by samwgoldman** [comment]
This works correctly on master, but I don't believe [the commit that introduces the lib def](7520895388854aecc98df6e1bbd5e02e31fdbc08) is released yet.

**Comment by AgentME** [comment]
Oh that's definitely it. I was looking at the dom.js in master. If I look at the file actually mentioned in the error message, I see no `children` property.
