### ISSUE TITLE
Modifying object by Iterating over its keys

### ISSUE THREAD

**Issue by cglacet** [facebook/flow#5542]
I'm not sure what is happening so my title is probably off. 

[Here is the code](https://flow.org/try/#0PQKhAIAEDMBsHsDu4TAFAHICuBnApuDgC4BOAlgMZEYDcaaRAngA4EDC88JAJuALzgAJAFEAHgEMqAHgDeacOFEAucAEESJcYykA7LAFsARnhIA+ADTzwjFes3a9Rkxauxxx2LY1apxcjoBzUzQAX1M6JlZwAFlxEgBrE35wOQUASCIyIlg8FT8yQMs0gDpSji5uULo0HKJwZnFEHSVYhKSBVPAMrJylACIABUadcCzRnD7LdOVwAG0ARnMAJnMAZgBdKa6bOYAGc33dzas0tw8VWb7RSaub6-WqtAp4HWJwBApxTJecJXKeZKdNIzWYrMHHdI7BYHczzCFdM54TxzPqMG5o8yovoPEL0Z6vOqJRg4ZIAeUMACs8FRikScAAKD5fMg-ACUdGgXHA9PxbyJ4Hg0HAdNZaDSDSasyJ62STO+ryleEY6zoQA):
```JS
/** @flow */
'use strict';

type Coord = $Exact<{
  x: Array<number>,
  y: Array<number>,
  label: Array<string>
}>;
type Marker = {
  	title: string,
	...Coord
};

const pawn:Marker = {
  	title:"Pawn it is",
  	x: [1,2,3],
  	y: [0,0,0],
  	label: ["x","x","x"]
};
const locations:Coord = {
  	x: [2,2,2],
  	y: [1,0,1],
  	label: ["y","y","y"]
}

// This shows no error:
pawn["x"] = locations["x"];
pawn["y"] = locations["y"];
pawn["label"] = locations["label"];
// But this does:
const keys = Object.keys(locations);
for (const key of keys)
	pawn[key] = locations[key];
```

Errors are all of this kind: 

```bash 
33: 	pawn[key] = locations[key];
                 ^ array type. Has some incompatible type argument with
33: 	pawn[key] = locations[key];
     ^ array type
Type argument `T` is incompatible:
5:   x: Array<number>,
              ^ number. This type is incompatible with
7:   label: Array<string>
                  ^ string
```

It seems like flow tries all possible combinations from `pawn[`A`]` x `locations[`B`]` for A and B in (`x`,`y`,`label`) which is odd since `key` is a constant and therefore A equals B. Notice that this has the same effect if I replace `pawn[key] = locations[key]` by `pawn[key] = pawn[key]`.

Any idea on how to achieve that without errors (copy something from an object to another using their respective keys)?

**Comment by SamChou19815** [comment]
This pattern will not be supported
