### ISSUE TITLE
Batch up disjoint union membership errors

### ISSUE THREAD

**Issue by wldcordeiro** [facebook/flow#5545]
One of the error types I find most jarring is when you have a mistake in something like a redux reducer and have a `case` with an invalid `action.type` value. If your `Action` type is a disjoint union of say 200 action types you get 200 errors for that one line when it could be batched and reported as a single error along the lines of "Exhausted all 200 members of `Action` type"

**Comment by SamChou19815** [comment]
not enough info to repro
