### ISSUE TITLE
Spread operator "..." does not mark object as sealed declaration

### ISSUE THREAD

**Issue by jpolo** [facebook/flow#5546]
The expand operator on object does not seems to be recognized as sealed object (https://flow.org/en/docs/types/objects/#sealed-objects-a-classtoc-idtoc-sealed-objects-hreftoc-sealed-objectsa)

As the spread operator returns a new object and does not mutate any object, it should follow the standard of sealed declaration.

A bad consequence is that is allows using a property (often calling a method) on the object without any reported error.

Reproducing :

https://flow.org/try/#0KYDwDg9gTgLgBAMwK4DsDGMCWEVwLICGA1sAELAAWBAbtlABQCUcA3gFBxxTAxJS4B5AEYArYBgB0CbsABeweu06cEECAC44MKEmAAaDnAC+jANxsjbNqEiw4aHAGd4AZSRC8EACZIANsDgAXlZDCTDCEnIqWmgmA05QTCwUAHNNAHIhAih0g0tONjcPbz9gCUcKCD8vACVgWxgAUSgoWMYgA

**Comment by gkz** [comment]
`shouldReportError` now errors as expected.
