### ISSUE TITLE
Probably a bug in Generic type scope inside HoC functions

### ISSUE THREAD

**Issue by vojtatranta** [facebook/flow#5554]
This code here: 
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vKK2wB2pfLQ7FcVAMID+VejlABeUAB5EoUAGUq2AG4paVACoBPDFVIAuUAG9QAbSHYU-AOYBdKwCNYsaDX6gAL6IAHwAFGqgpNp6RqbmVlq6+nFmpAA0iACUiiEqkVKYANLQZJagEqWkpMrUdLgAdIVYMvy4ygTphCEhmeGRAOrYxBhmACbNAlRtVs0lZZk5Cnmq6gCS-ABWsuJjAApMGOXWgZnqFHtWACQAIiiQkLWcjQCifmjTuAewR8pzVaReqANtt6FR9odAX0IupnKDdlYQTtwd8jotZgCnvUmswWp9ansukiwRCfoC8ssbJE+IJ8M4ULgUMRoBpcGIqIitsjSUdFKA4dzIhxcABXbABWgA0BUAAe4n4Y3IdXoDT2YskuKmbQJRK5JNRgKp6nUQnZfPpjOZrPZyGNUTZjNooDGVEgxBF0C+kM58JRkPN-AZTJZDqotuNHAV2jCOWskTtNKEoAw-qUtgaGdwAAsUKQGqbxF0Mw1s7mGimyUF4xGqKLxaAwsohiNxpNWvhrMWK0dAqBgCEstXgupgsFkJKyqBDOZcM1pXLporKM9Veq2-i4+odMyRRz7U5XGdQB80J5tBRfHvvJfiPxMqdulTEJGXdgY0bQMKxQEYcblFmAEYQmsUs827PNt2gXdAmUYBAJCSJB1HHheAEJNqFID18CUEQaHEKR+BkOQ31sEVomwDZIFgVkcD3XBsF3IIsjCachGaZjN2PKhT3PS8rHo3d70HVDaVAbCVAwrC+xCIA

Says no error, even though `<Result />` should have `value` prop required.

Strangely, this code works:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vKK2wB2pfLQ7FcVAMID+VejlABeUAB5EoUAGUq2AG4paVACoBPDFVIAuUAG9QAbSHYU-AOYBdKwCNYsaDX6gAL6IAHwAFGqgpNp6RqbmVlq6+nFmpAA0iACUiiEqkVKYANLQZJagEqWkpMrUdLgAdIVYMvy4ygTphCEhmeoAkvwAVrLiACYACkwY5daBfZQTVgAkACIokJC1nI0Aon5oVG1TsDPKzSVlvaCDI-RUk9OkvaER6gDq2MQYZmPNAkdcFYLlUMpFnHdxlZbqMHicZpkssDQdt6k1mC1AbUJl0YfdHqdnnkFHlrJE+IJ8M4ULgUMRoBpcGIqNDhrCCTNFKAIezIhxcABXbABWig0BUAAe4n4Y3IdXoDQmQskGIBbWxuLZ+PhzxskXUQmZXOptPpjOZyHUBqZtNooDGVEgxAF0FwOtZkLhT2N-BpdIZNqolqtHBl2jCOTJVqtFKEoAw3qUtgaKdwAAsUKQGobxF0Uw105mGgnCUF9SGqILhaAwspPt9fv9WvhrPmSzNAqBgCEsuXgupgsFkKKyqBDOZcM1xVKjrLKDtFcqm1io6AdPSBSyorgnK4Foc0J5tBRfFvvKfiPxMvNunrEKGHdgI3r1PyhQE3lblGmAIwhayFlm7ZZuu0CboEyjAL+ISRL2g48LwAhxtQpAuvgSgiDQ4hSPwMhyE+tgCtE2CDJAsCMjgW47puQRZGE45CM0XSrgeR7YCefhWNRVDXr2iGUqA6EqChaFdiEQA

The only difference is that in the first example there is one level of HoC function more than in the working one.

Seems like generic type scope is not correctly applied.

**Comment by vojtatranta** [comment]
Any idea why is this happening?

**Comment by vojtatranta** [comment]
Hey everyone, any help is appreciated!

Could you help? @apsavin ?

Thanks!

**Comment by apsavin** [comment]
Well, looks like a bug for me.

**Comment by vojtatranta** [comment]
Yeah? Well, is there any way I could assist? Unfortunately, I don't speak OcaML :(

**Comment by vojtatranta** [comment]
@apsavin heey, any updates on this :)

I'd love to help, but you know, OcaML is a "spannish village" for me...

**Comment by apsavin** [comment]
@calebmer could you please take a look?

**Comment by vojtatranta** [comment]
@apsavin aha, but these issues do not explain why the second example works when there is the only difference in using another closure.

> it uses *. That should never be used. 
Well, how come second example works? :) I tried this, but no luck: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vKK2wB2pfLQ7FcVAMID+VejlABeUAB5EoUAGUq2AG4paVACoBPDFVIAuUAG9QAbSHYU-AOYBdKwCNYsaDX6gAL6IAHwAFGqgpNp6RqbmVlq6+nFmpAA0iACUiiEqkVKYAApMGJY2gZnqhRgauGJUVtaVBcwYANLQZOUSXaSkytR0uAB0NQJU-LjKNSWwZemgNXUNISGZ4ZEA6tjEGGYAJuMyU1Y1nd2ZOQp5quoAkvwAVrLiB3NlTS3qFEVWACQAERQkEgMzaHwyoEeL3oVHepVI61CEXUzlhbysMNe8MhVzOfQGQ3oYzaEymgyKi2xcIR8yReRuNkifEE+GcKFwKGI0BW4ixzxxdLKilA6KFkQ4uAArtgArRCaAqAAPcT8A7kYmjIqyyRkk7TX7UwW0yF5ayRdRCBqijlcnl8qjIdRW+pc2igA5USDEaXQXCQgUY3GI238Tnc3lup2W0AcdXaMI5C0ul2soSgDChpS2EZ53AACxQpBG1vEizzI0LxZGWfpQVj6ilsoCYWUOz2h2Ok3w1krdbKgVAwBCWVjwXUwWCyAV3VAhnMuBqStVkw1lE42t13YpKdAOh50saUVwTlcVVAaCoaE82govmP3gfxH4mUqhHNyHjXuwSeZTaoGU5VAVEXWUAsAEYQmsasSwHEsD2gI9AmUYBIJCSIxynHheAEDNqFIP18CUEQaHEKR+BkORf1saVomwR5IFgOocGPU8jyCLIwgXIQai4i1EKPKxWGIAtYCebhAjHXC2VAYiVAIojhxCIA

> it uses an un-instantiated type parameter in the return type. Try inlining the type for RP.
I think it is instantiated because the only value it requires is the `injectedProps` which is instantiated

**Comment by SamChou19815** [comment]
Closing since the example uses a lot of * that's unsupported for a long time
