### ISSUE TITLE
Disjoint union for function types (to define null case).

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#5558]
I'm hoping for something [like this](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKAoKUA+UAUBnYAJwEsA7AcwEpkA+KAki9LXANzmIBNqk7SBXALYAjCIVSoAxnFIEoAMwQAuWAmS4AhjzoBvZsXmbkKfqU4R5ZCJyzYNxqAIA2T6oQjB+hUlACMzd09vKA1UAF8gA) to enable typing a function definition for the null case:

```js
type Foo = 
  | (string) => string
  | (void) => number

const foo: Foo = (a) => {
  if (a == undefined || a == null) return 1
  return a
}
```

I would expect this to work, but flow apparently doesn't like it. I find it rather annoying to deal with maybe types, a la `const foo = (a: ?string): ?string => {...}` and was hoping there was a better way to do this.

**Comment by jcready** [comment]
You need an intersection instead of a union:

```js
type Foo = 
  & ((i: string) => string)
  & ((i?: null) => number)

declare var foo: Foo;
(foo(''): string);
(foo(): number);
(foo(null): number);
```
