### ISSUE TITLE
Doesn't complain about an undefined type

### ISSUE THREAD

**Issue by NameFILIP** [facebook/flow#5559]
```
type A = A;

const a: A = {
  a: '1'
};
```

https://flow.org/try/#0C4TwDgpgBAglC8sDcAoFBjA9gOwM7CgEMAuWBKAbxSiNIHIBGOlAXySA

Context:
I extracted a type into a type definition:
```
type FieldName = $Keys<Fields>
```
and then did a Replace All for `$Keys<Fields>` with `FieldName`. This has changed the definition as well. Luckily it was caught in code review, but I was surprised that flow had not reported an error

**Comment by idiostruct** [comment]
`type A = A` defines a generic with an "unknown" type. In your example, view the AST tab and look for `"type": "GenericTypeAnnotation"`. Here's [another example](https://flow.org/try/#0C4TwDgpgBAglC8sDcAoFAzArgOwMbAEsB7bKLPACgEMAuWASigG8BfNc3CgRnox04BEXAbw4VWo-hWAAnTBEmUA2gF16QA) illustrating the behavior in question.

**Comment by SamChou19815** [comment]
This now errors
