### ISSUE TITLE
React Ref: This type is incompatible with ((React$ElementRef<ElementType> | null) => mixed)

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#5561]
For some reason, in this very specific instance (not any others, and we do this in other areas of our code) flow seems to think the ref returned can be null. Other instances it just seems to be okay with using refs.

Here is a link to the [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50yAPPIsFRgUAziLABlQhUJkoAVxgAFOHgBuZfGF6yAdgBNx5aoQB0AYQZ5dZXYQA8AbwC+APjCPUYMAH086zQAuMAAJABUAWQAZABEMNQBRGDIsW0IuL0E4XRFCfHkaAgAKHHocEWCKXQBPAEoPTO8ReRxNErKRWq5vZwzvVgM2+s9vfrJCeXxdMCLG0ft9eLnRsFYoAF5HQgALDBFTHxFxlQD8cig3ZbB7YEW1VzmuzN70b0Pj1TgNM7kwdZn-F8gqFIrF4kkUml6ut3CNRjs9gdAd8-mBkZpumBnKhsahePxiEJROIpDIyBIyMkaCcgVodLZDKQ2GZLLhsmknG4Gm90fhgqTZAplJ9vn0sjk8gVCMVSqoKmAqnVuaNmq18O05U8emKBvohsqxhMpjMrvYBXJFDTvlcxhstrt9u9CFbNOdLitvDdzUKXfgHistVixU7fedUSURcDvZbI-hobC5gjHbzUbzMdjsUA), any help will be greatly appreciated.

**Comment by vicapow** [comment]
Hey @rickyp-uber ,

Try flow doesn't import DOM globals so that explains the `HTMLDivElement` errors. Running your example locally, I get the original error you're reporting about `null` on line 15.

````js
Error: original.js:15
 15:         ref={this._setPopoverRef}>
                  ^^^^^^^^^^^^^^^^^^^ function. This type is incompatible with
 14:       <div
            ^^^ union: function type | string
````

see: https://github.com/facebook/flow/blob/master/lib/react.js#L173

````js
declare type React$Ref<ElementType: React$ElementType> =
  | ((React$ElementRef<ElementType> | null) => mixed)
  | string;
````

Because `HTMLDivElement` can be `null` you'll want to define your `_setPopoverRef` as...

````diff
-  _setPopoverRef = (popover: HTMLDivElement) => {
+  _setPopoverRef = (popover: HTMLDivElement | null) => {
    this._popover = popover;
  }
````

But this error to me seems reasonable given the definition of the `ref` prop.

Could you give examples of when flow doesn't complain about `ref` potentially being `null`?

**Comment by rickyp-uber** [comment]
"Could you give examples of when flow doesn't complain about ref potentially being null?"
I've found why it seems to be working but actually isn't. The component StatefulPopover in our code base has an unknown variable type to flow, meaning it defaults to any. This allows me to not have to specify null. Not the greatest fail scenario in my mind but I come from a typescript world.

That said, the typescript version of this same code seems a bit cleaner due to not needing to pass the null in.
https://codepen.io/anon/pen/EoZwNX?editors=1111

Something that could resolve this is in React, instead of passing null to the ref in the component unmount, pass undefined. I believe then you wouldn't need to specify null as a type. That said, it is a pretty core change so I doubt it would happen. Is this proposal worth opening a bug? I feel it would likely be closed out immediately considering the lack of impact it would have...

Thanks for looking into this!

**Comment by supercamilo** [comment]
Check https://flow.org/en/docs/react/refs/
