### ISSUE TITLE
Flow fails due to "possibly null value" even after checking for null

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#5562]
I would assume checking payload for null before the whole thing executes would be enough.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swATOAZX0yigAoAHAQwE95myAuMAfgG8wAbQDO+AE6FsAcwC6PMZJlgAvgEow-VGDCEoYJmw5kwAQgC8YbJhgwNWnToDyAIwBWAUwIA6ANYfWEUN2OE41bUcdbxE4cXx6cMioqFiAUWZcAAt6ejJmfA9qJWkFCSlpABpdMgAPHmsAWxcPcSq8gqLygGE4Wy8iEh4AQXFxNgAeRXKAPg1zac0IpLBcEhiYD294aWDjIXbCsplZNQBuJdUziJVUFSA

**Comment by vicapow** [comment]
This is a duplicate of #5541

**Comment by rickyp-uber** [comment]
Sure is!
