### ISSUE TITLE
Tuple is failling when creating it using slice

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/flow#5564]
Hi,

As you can see in [this example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqbsAVAVwAdoBTAJlAF5QAKbUigFgC5QBtdIgWwCNyAJwA0oHgOFiJg0eL6yAugEoO3BVPmShi2gD5EoPM3IsAdJmgBLFOXoAGMZWUBuIA), when you use slice on a tuple and you want to type the result also with a tuple of a reduced length, it fails saying:
> array type. Only tuples and array literals with known elements can flow to

I understand that when dealing with arrays of unknown size it wouldn't be correct to try to get a tuple from them, but this case is different, you are starting from a tuple so IMHO it makes sense to be able to create another from it, in fact it works fine if you create it manually ([item1, item2 /* etc*/]).

I would appreciate any insight on this, thanks!

**Comment by idiostruct** [comment]
You're starting with a tuple, but the return type of [`slice(0, 2)`](https://github.com/facebook/flow/blob/81e92a11851bdbc87400e3c6f2c68e827b4ff497/lib/core.js#L231) is `Array<T>` not `[number, number]`. I'm unaware of alternatives to manually creating an array literal with known elements. Does this help?

**Comment by mgtitimoli** [comment]
Thanks @idiostruct, yes I saw that.

The problem I see is that they are asking for: 

> array literals with known elements

and given the fact slice takes as input a tuple I would expect this condition to be satisfied...

**Comment by idiostruct** [comment]
I'm beginning to understand your inquiry. Assuming `Array<T>` didn't derive from `$ReadOnlyArray<T>`, each could return their respective types satisfying your condition:

```js
declare class $ReadOnlyArray<+T> {
  slice(start?: number, end?: number): $ReadOnlyArray<T>;
}

declare class Array<T> {
  slice(start?: number, end?: number): Array<T>;
}
```

```js
array.slice(0, 2) -> array
tuple.slice(0, 2) -> tuple
```
I'm a novice to the internals and probably oversimplifying.

**Comment by SamChou19815** [comment]
General type definitions like slice will not special case for tuples
