### ISSUE TITLE
Generic constraint from parameters won't raise error

### ISSUE THREAD

**Issue by zaaack** [facebook/flow#5569]
https://flow.org/try/#0PTAEAEDMBsHsHcBQyAmBTAxtAhgJzaAG56gDOaALgJIB2AXKADwAqANKAGoB8AFPhrFwoGbUNgwY0pUoIY8esAEYArEQEpQAXi6cNAHzIVcASxoBzANoBddsWgBXNAH4GHDdtDNkidFjwFiXFB7AAcUbAo0WgYWdm4+TEFhT3ZxSWlZUHklVU93HTdQA1IjU0sbYLCIwRcswld83S0dL1BQb29oSkMIgk1QAG9ENppsAFs0BgBybFmp1mGxM0nQAEZEAF9kcmoaHhLe9gB9ZtAjgDpsZfYBjY0QMgALWHtoFFAKZ-hQNFxcQUQoXCkVo+wohzOpwuVzQqVOPAG5yR2DuaiAA

**Comment by SamChou19815** [comment]
This is expected, since we infer V to be a union of state and `{}`.
