### ISSUE TITLE
`npm install underscore` suppresses flow errors

### ISSUE THREAD

**Issue by danvk** [facebook/flow#557]
I've been experiencing a mysterious absence of Flow errors for external libraries recently and was able to track it down to installing underscore via NPM.

Here's a minimal repro...

First, the expected behavior, which is that `_.foo` isn't declared in a lib file and should be an error:

```
git clone https://github.com/danvk/toy-flow.git
cd toy-flow
npm install
./node_modules/.bin/flow check

/Users/danvk/github/toy-flow/foo.js:5:10,16: call of method foo
Could not resolve name

Found 1 error
```

Now I install underscore and the error goes away:

```
npm install underscore
underscore@1.8.3 node_modules/underscore
./node_modules/.bin/flow check

Found 0 errors
```

It's a coincidence that the suppressed error has to do with a symbol in underscore—errors from other external libraries for which I've written type definitions, like Q and Mocha, are also suppressed.

This is an issue with Flow 0.10, 0.11 and 0.12, but not 0.9.

**Comment by samwgoldman** [comment]
I think this is the same as an existing issue: #447. Thank you for finding the regression point between 0.9 and 0.10!

**Comment by danvk** [comment]
Closing this out as a dupe.
