### ISSUE TITLE
function argument cannot receive simple Union Types?

### ISSUE THREAD

**Issue by ryota-murakami** [facebook/flow#5572]
# Question
I created `Contact` Union Types in order to define typed representing either `Phone` or `Email`.
And I specified `Contact` Union Types as a function argument and accessed the number poroperty inside the function, following error displayed.(reference sample code)

```
property `number`. Property not found in Email
```

As far as i know, this `Contact` Union Type matches either `Phone` or `Email`, but i don't understand why access to exist properties on `Phone` Induction `Email` type check errors.

Is the purpose of Union Type not grouping multiple types and abstraction?

I'm sorry if I misunderstood about Union Type.

Thank you for your helping.

# sample code

[https://flow.org/try/](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKAFnAHYEC8YA3qmGGQK4C2ARngE4BcYAzhk4BLMgHNUAX0y4CAURYBDITDDU6DBQBNNnPHz68BwsZPTZ8YAMLkMCgMYZVRUhTAAfMPKUx0UJmQchcjBdLWsyWwcACjsbewxecMiMAEpaejBYsgEwHBc8ADlWDk4nLOSAOmZ2LlMGVCA)

```js
/* @flow */

type Phone = {
  number: string
}
type Email = {
  address: string
}

type Contact = Phone | Email

function readContact(contact: Contact) {
  const phoneNumber = contact.number // 13:  const phoneNumber = contact.number  ^ property `number`. Property not found in Email
}
```

**Comment by apsavin** [comment]
Well, your `Contact` is `Phone` or `Email`.
So, maybe it's `Email`. But there's no `number` property in `Email`.

See [docs](https://flow.org/en/docs/types/unions/) about union types. Especially [this](https://flow.org/en/docs/types/unions/#toc-disjoint-unions) and [this](https://flow.org/en/docs/types/unions/#toc-disjoint-unions-with-exact-types).

**Comment by ryota-murakami** [comment]
@apsavin oh, sorry.
I should use `Disjoint unions`, thank you so much.
