### ISSUE TITLE
type Foo = Foo should error

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#5573]
````js
type Foo = Foo;
function foo(f: Foo) { f = f + f; }
````

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvESQNypQCuAdgMYYCWcDYUJAFFAFyU4ASjABvLuUkBqLlTABfIA

**Comment by NameFILIP** [comment]
Similar to https://github.com/facebook/flow/issues/5559

**Comment by stereobooster** [comment]
Duplicate of https://github.com/facebook/flow/issues/5771

**Comment by goodmind** [comment]
Duplicate of #5771
