### ISSUE TITLE
How do I customize the check type in React ?

### ISSUE THREAD

**Issue by simonguo** [facebook/flow#5579]
For example : 
https://github.com/Semantic-Org/Semantic-UI-React/blob/master/src/lib/customPropTypes.js#L314

**Comment by jamesisaac** [comment]
Closing as this has very little info, so difficult for anyone to know how to help you.

If you want to re-open, please provide a description of what you're trying to achieve.  Or even better a reproduction of the problem you're facing on https://flow.org/try/
