### ISSUE TITLE
$ObjMap output types conflated into union

### ISSUE THREAD

**Issue by freddi301** [facebook/flow#5584]
keywords: $ObjMap

[flow try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmgawC2ADrAM5oA8AggDSgBCfAMIA+ABSQAXKDEAjafwCUoALwjQQvgHNpY7NK7K1AxQdXqhAbmTkAnkwIAVWClirQAb1CuSaabNhYaDRsEj5yNAAPcmlWclxKEi1QAF9EOwdQAGVybAj3L3IXNmlnVwBtAF0+elII3GkSIgZZNFxU6wyCABk0ElYOLKJZOLy0dRUZRFBQbApqEl1WYdGI6SGR3IijdQ3VtEQd7K2CYxyxy1Bken7yUESMd33zUGeAalAARmtEEFn5misX5gRwAeQAIqDpFo+m1sNBKAAvAhiDChEiwO5dDAAC0wAGtFIgbnF7iQimUSqBev0OJSqhNZi9WC8xF4AHSc1jhYqsaTYMSsdlFVysZQpRTWEl3RJFISwOptaQ0gZNFptRnYZmsjlcmoK8lK2aC9m1Q24cWS4mAu5m8iUrgA-rKvoDemVTVO8zTOiMFjsMSy2CU1h6J2KPhB+WK3CBsiKK2IYhkKg0UDBfpoAbnNaeUDlfFoWyxeKJLSVfkkWypcQ+-brE6HaQAElBsgAVgBZbBMDg+nNoHg+wYrE61mYzZabMbrUdjH1HMRh1OLGRT+vZOfbF57E6LjcDo6HxDqDw+-DkIi4WhiAAMldsVrS1turxOkQbYwKvpj0lvPNFaQqg6a4bXTV0s0idwM3YUN9kiRNpTJOUDXqKDJhgyDTVQtofiQoMQ3Q8DM1YSJhV5PCwKIqMcNwSIxBINQSAAKgAJkUQV3yJIA)

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
