### ISSUE TITLE
The point of $ObjMap

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#5585]
Hi,

Can anyone explain the point of `$ObjMap` and what's this exercise with `F` parameter all about?

For example:

```
type ExtractReturnType = <V>(() => V) => V

function run<A, O: {[key: string]: () => A}>(o: O): $ObjMap<O, ExtractReturnType> {
  return Object.keys(o).reduce((acc, k) => Object.assign(acc, { [k]: o[k]() }), {});
}
```

Why can't `$ObjMap` be used as `$ObjMap<TObject, TTransformedReturnValue>`?

Why does one need to do an `ExtractReturnType` dance and go through unnecessary hoops?

**Comment by TrySound** [comment]
Because we usually don't need one type of value. $ObjMap allows to extract one value type from previous one.

This probably can be closed.
/cc @vkurchatkin

**Comment by pronebird** [comment]
@TrySound alright I see. So basically the extraction function is a somewhat constraint that is when resolved produces the return type which can be useful in case if the object has an array of functions which return values we could capture then.
