### ISSUE TITLE
0.62 introduces failure on Object key named `static`

### ISSUE THREAD

**Issue by STRML** [facebook/flow#5589]
Code:
```js
type Foo = {
  static(path: string): void;
}
```

Failure in 0.62: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgDOGAhhgJYDGAFDswBYBc9DACcWAOwDmASgEA3OCwAmAblQBfIA

Success in 0.61:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgDOGAhhgJYDGAFDswBYBc9DACcWAOwDmASgEA3OCwAmAblQBfdEA

**Comment by STRML** [comment]
This breaks typechecking on popular methods like `express.static()`.

**Comment by jcready** [comment]
Workaround:

```js
type Foo = {
  static: (path: string) => void;
}
```

**Comment by samwgoldman** [comment]
Oof, sorry about that. Will fix ASAP.

**Comment by samwgoldman** [comment]
OK, I have a diff up internally (building on @popham's excellent work in #5518). Might take a beat to get reviews in due to the holidays.

Thanks for reporting!

**Comment by popham** [comment]
I managed to maintain this bug in #5518. Fixing....

**Comment by samwgoldman** [comment]
Thanks @popham but no need -- I already have the fix up for review internally
