### ISSUE TITLE
Problem with Array of Object type not compatible with null

### ISSUE THREAD

**Issue by seanippolito** [facebook/flow#5591]
I ran into an issue with flow that I can't seem to resolve with Maybe type syntax. I have an array of Server Type objects declared like this serverData: Array<Server>, I have also tried (?Server)[] and ?Server[] to see if null values would be accepted and I still received compatibility issues. Here is the output from Flow. Any assistance would be appreciated, thanks. I am not sure if this is a bug or not so I am not reporting it as one.

Error: src/Components/RightPanel/RightPanel.js:78
                     
 78:       serverData: this.props.serverData
 79:         .map(server => {
 80:           const match = server.serverName.match(reg);
...
103:         .filter(server => !!server) // This throws a flow complaint not sure why
             --------------------------^ array type. Has some incompatible type argument with
 45:   serverData: Array<Server>,
                           ^^^^^^^^^^ array type
  Type argument `T` is incompatible:
     82:             return null; // this throws a flow error, something is wrong with the Array<Server> type accepting null
                            ^^^^ null. This type is incompatible with
     45:   serverData: Array<Server>,
                             ^^^^^^ object type

**Comment by apsavin** [comment]
@seanippolito Could you please provide a short reproducible example using flow.org/try?

**Comment by SamChou19815** [comment]
not enough info to repro
