### ISSUE TITLE
Unsupported option specified! (unsafe.enable_getters_and_setters)

### ISSUE THREAD

**Issue by dsherida** [facebook/flow#5594]
I'm getting the message `.flowconfig:72 Unsupported option specified! (unsafe.enable_getters_and_setters)` which is an option defined in the default .flowconfig while using create-react-native-app. This option is also specified in the [Flow documentation](https://flow.org/en/docs/config/options/#toc-unsafe-enable-getters-and-setters-boolean) so why am I getting this error?

**Comment by idiostruct** [comment]
Its been removed in [0.62.0](https://github.com/facebook/flow/blob/master/Changelog.md#0620). Getters and setters are enabled by default.

**Comment by aikar** [comment]
That was a horrible idea to make everyones process fail hard instead of simply ignoring it or printing a deprecation warning.

**Comment by TrySound** [comment]
@aikar It's major release. Just read changelog.

**Comment by Aravindhan12** [comment]
I'm using flow bin version 0.63.1. Same error as @dsherida mentioned. Tried Downgrading to 0.62.0 but still the error remains the same.

While the yarn run flow command runs, following error appears,
.flowconfig:72 Unsupported option specified! (unsafe.enable_getters_and_setters)
error Command failed with exit code 8.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

**Comment by TrySound** [comment]
@Aravindhan12 Just remove that option from your config.

**Comment by Aravindhan12** [comment]
Finally I have fixed this by downgrading to Version 0.56.0.

@TrySound  As you said I have removed the option. Now when the yarn run flow command runs, I received a error as  Launching Flow server for Wrong version of Flow. The config specifies version ^0.56.0 but this is version 0.62.0 Could not start Flow server!  error Command failed with exit code 78. 

So I downgraded to 0.56.0. After that when I run the  yarn run flow command, lot of errors was thrown in all the files with the message  get/set properties not yet supported. 

To fix it I have added the unsafe.enable_getters_and_setters in the .flowconfig (which I have removed earlier) and it works.

Hope this helps someone.

**Comment by TrySound** [comment]
@Aravindhan12 Downgrading doesn't help anybody. Kill all flow processes, remove version mark from config, remove unsafe.enable_getters_and_setters and run `flow`.

**Comment by TrySound** [comment]
@Aravindhan12 Also make sure you have latest versions installed globally and locally.

**Comment by Aravindhan12** [comment]
@TrySound Thanks for Pointing it out. I have removed the option and changed the version to 0.63.1 in my config file. Also upgraded to version 0.63.1 from 0.56.0. It's all works fine now. 

Thanks for quick help.

**Comment by tintorres** [comment]
I can reproduce the issue in 0.64.0

It fix the issue when I downgraded to 0.57.3

**Comment by TrySound** [comment]
@tintorres If you look above you can find solution. Also you can read [changelog](https://github.com/facebook/flow/blob/master/Changelog.md#0620)

**Comment by kazeshini178** [comment]
Think the flow docs should be updated to indicate this change. As they are currently misleading or just wrong (depending how you look at it)
