### ISSUE TITLE
Strict subtype/subset of a union type

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#5595]
When using generics, one can state that an interface is parameterised by a type variable. Like:

```
interface ABC <L: SomeOtherType> { ... }
```

If this `SomeOtherType` is also a union of multiple types, is there a way to say that this interface must be implemented with a specific type of the union?

Right now it's still possible to say:

```
class A implements ABC<SomeOtherType> { ... }
```

Using `$Subtype<SomeOtherType>` doesn't work because `SomeOtherType` is a subtype of `SomeOtherType`. So I'm looking for some kind of strict subtype or strict subset.

**Comment by lll000111** [comment]
Define the interface with the concrete type?

I don't quite understand (okay okay, more often than not one should not comment at all in this case but here we go), either you want the interface to be for the union (all those types) or not.
