### ISSUE TITLE
defaultProps is ignored when validating a prop that has sub-methods (e.g. Date)

### ISSUE THREAD

**Issue by dmatteo** [facebook/flow#5596]
## Issue 
It looks like the parser is ignoring the fact that I'm defining a fallback for my optional prop, therefore stating I might call `getTime()` on an undefined prop.

However, I'm falling back on today's date using `defaultProps`, which should take care of that.

```
call of method `props.date.getTime()`. Method cannot be called on possibly undefined value undefined
```

My real case scenario is using `moment.js` and `.format`, but it doesn't matter, as I was able to reproduce with "normal" JS dates as well.

## Repro 

Reproduced on [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gBKApgIboEC8YATsQI4CuAlnQBQDkd5eHAlAG5UqZljzEaUcsTABZAJ4AFGnAAOOMAG9UYMABNS4gPwAuMABFDxIQF8dYDNnxz5AZQBiAYTDU2qlepmCspqOHw+AHxaqACQdHiMNFhgADyiqowEAG6kMIzElJr+oQB0BuIlAObEeAAqzAC2xGx8NmDAEah2qAoenmXEUowweCHqPtG65cRmWMRIluItADRdQA)

## Config
* App scaffolded with `create-react-app`
* flow-bin v0.62.0
* flow-config pristine

---

**p.s.** coming from TypeScript, I recently starting exploring flow... I LOVE IT!

**Comment by samwgoldman** [comment]
This is working as expected, actually. The type of `props` should be non-optional, and defining the `defaultProps` field makes the field optional the type of the "config" object. Note the distinction between props and config. Props are what you have in the render method of a react component, while config is the object you pass to createElement (via JSX or not).

[Try Flow example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gBKApgIboEC8YATsQI4CuAlnQBQDkd5eHAlAG5UqZljzEaUcsTABZAJ4AFGnAAOOMAG9UYMABNS4gFxgAIoeICwwYGAAGB8XbDMNWbAFo1eZtlIwwVABfIV0MbHw5eQBlADEAYTBqNlUVdRMFZTUcPiSAPi1UAEg6PEYaLDAAHlFVRgIAN39GYkpNVOyAOkdiToBzYjwAFWYAW2I2PiDrPOChVAU4+O7iKUYYPCz1JMLdHpMsYiRzcUmAGjnhNirFhJnBa1sHC2dXMG9fLH8wAAsJYiAA)

**Comment by dmatteo** [comment]
I'm not sure I get it.

If date is not optional, as you defined in your interface, why isn't `flow` erroring when calling `<MySFC />`?

**Comment by samwgoldman** [comment]
In the body of the MySFC function, `date` will always be present, because it's provided by `defaultProps` if not explicitly passed in. That's why the field should not be optional in the props type.

Loosely speaking, you have something like this: Props = Config + DefaultProps, where Config is the object that you pass to React.createElement.

Does that make more sense?

**Comment by dmatteo** [comment]
Sorry, delete my comment cause I got it after re-reading 😄 

I guess my confusion comes from the fact that both TypeScript and PropTypes work in a slightly different way. I could be wrong, but I don't think they make a distinction between `Config` and `Props`.

Anyway, got it, thanks!

**Comment by samwgoldman** [comment]
Yeah, I'm not super familiar with how TypeScript deals with this problem :)
