### ISSUE TITLE
Array#reduce on empty array should require an initial value

### ISSUE THREAD

**Issue by deecewan** [facebook/flow#5598]
If this is a bug, please try reproducing using https://flow.org/try/.

Currently, `Array<any>` does not require an initial value for reduce. That means that
`[].reduce(() => '')` will result in a `TypeError`(`Reduce of empty array with no initial value`).

I don't know if this is possible, but ideally, strict tuples should not require an initial value (to typecheck, they must be of known length already), but any variable length array should require an initial value in the reduce.  There may be ways to know that a particular array has items in it, in which case it can be avoided.

[This](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAPACgEMAnGgLjAEE6qBPAHgGd8bDsA5gD4AlGADeqMGBoBTfJhqlaNAHRyAJplyyK1ADRgARmIC8QsFTABqYyIDcqAL7pKAbQC6I1O4DkVX0NfI0CwX1xfL1QgA) `/try/` example shows it passing successfully in flow, and the following screenshots show it blowing up in Chrome and Safari.

![image](https://user-images.githubusercontent.com/4755785/34474206-a9fd6bf6-efc7-11e7-9529-d066f81a1a6b.png)

![image](https://user-images.githubusercontent.com/4755785/34474226-fd4f153e-efc7-11e7-9188-0986ffe98165.png)

**Comment by jcready** [comment]
Flow also let's this pass.

```js
/* @flow */

function x(arr: Array<number>) {
  return arr[123].toFixed(1);
}

x([]);
```

**Comment by deecewan** [comment]
hmmm. maybe flow should force refinement to determine length for that case @jcready? The reduce function will work fine on an empty array, providing a default is given.

Essentially, my proposal is:

for tuples, reduce is the current signature (unless the tuple has zero length?)
for `Array<*>` items, the signature is `reduce<A, T>((a: Array<A>, b: A) => T, initialValue: T)` to enforce the use of an initialValue when using a variable-length array.

**Comment by SamChou19815** [comment]
Unfortunately, this is out of scope, since there is no reliable way to keep track of empty array in a type system
