### ISSUE TITLE
Buffer#buf.swap64() is not supported

### ISSUE THREAD

**Issue by kesor** [facebook/flow#5600]
https://github.com/facebook/flow/blob/aea3635e9b5cd806a1fe83b664eb1939aceda63d/lib/node.js#L77 is missing `swap64()`

According to https://nodejs.org/api/buffer.html#buffer_buf_swap64 `buf.swap64()` was added in: v6.3.0

**Comment by nicoffee** [comment]
Hello! I made PR for this issue: https://github.com/facebook/flow/pull/5888
Please, take a look at it.

**Comment by jdecked** [comment]
Has this been fixed? Given that #5888 & #5653 are both closed, I assume yes, but otherwise, I'd like to work on this.
