### ISSUE TITLE
`React.DoesNotExist` error is hidden or missing

### ISSUE THREAD

**Issue by lydell** [facebook/flow#5602]
**Minimal reproduction repo:** https://github.com/lydell/flow-bug

It seems like something is a little bit off when it comes to handling the `React` variable:

- If I forget to `import * as React from "react"`, the `React. Could not resolve name` error is missing.
- `React.AnythingThatDoesNotExist` does not seem to cause errors in flow-typed/ files.

test.js:

```js
// @flow

// Intentionally "forgotten".
// import * as React from "react";

import foobar from "foobar";

function test(): string {
  return foobar();
}

// Should complain about `React` not being defined.
function test2(): React.Node {}
```

flow-typed/foobar.js:

```js
// @flow

import * as React from "react";

declare module "foobar" {
  declare export default function foobar(): React.DoesNotExist;
}
```

Expected: ``DoesNotExist: Property not found in 'exports of `react`'`` and `React. Could not resolve name`.

Note that [eslint-plugin-flowtype-errors](https://github.com/amilajack/eslint-plugin-flowtype-errors) somehow runs `flow` in some way that _does_ show an error for the `DoesNotExist` case:

```
$ eslint .
/home/lydell/bugs/flow/flow-typed/foobar.js
  6:45  error  DoesNotExist: Property not found in 'exports of `react`'. See line 3  flowtype-errors/show-errors

✖ 1 problem (1 error, 0 warnings)
```

Also note that `React` being undefined _is_ reported in [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgJIDsAuApgQJZy4CGMMAnmAERRwBOA5nPkbvQHQZYkAtgAcW+ZGAoBnMACVCFAMbiozOIIbMFy+gG50UAK65lZXGCJT8ACgCUALjnb8PAKIxCg4vgDC5KCSsADwAfGAA3gC+6EA).

I discovered these oddities when trying to make a library definition for an npm package that exports a HOC (see also #5592).

Flow version: 0.62.0
Node.js version: 8.9.0
OS: Ubuntu 16.04

**Comment by SamChou19815** [comment]
fixed
