### ISSUE TITLE
Lazily parse package.json files

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#561]
This has caused issues with node module dependencies that include intentionally invalid package.json files in their distributions (as part of tests).

For now, there is a workaround: add an entry to the `[ignore]` section of the .flowconfig.

I think we should only parse the package.json file once the relevant module has been required. Ideally, we would only parse once if the module were required multiple times.

**Comment by mroch** [comment]
I think the challenge here is that if we defer them, I don't think we'll be in an environment where we can raise the parse error.

also, we check every `@flow` file under root (+includes-excludes) whether or not it's required anywhere, so I expect we'd end up parsing the package.json anyway when we check the files in that package (except for true edge cases like a directory with only an invalid package.json for a test, but if that test had a .js file in it then it'd still fail).

**Comment by samwgoldman** [comment]
We raise if the package.json file can't be found. Couldn't the same code path could raise the parse error too?

You make a good point, though, that even if we do it lazily, we could end up parsing them anyway through requires in `.js` files.

Do you have any alternate ideas that solve the whole problem? `[ignore]` does work, but if we could eliminate the startup cost somehow, without requiring configuration, that would be ideal.

Also, the `[ignore]` solution means each project needs to solve the same problem over and over. It's not ideal, but what if we added a custom key to `package.json` files themselves, allowing node modules to specify ignored patterns. Not idea, because projects would need to add code just for us, but it does help address the issue that everyone needs to configure each project.

**Comment by mroch** [comment]
re: custom keys in package.json, i think we should support nested .flowconfigs for things like this... but I don't know that I've thought enough about the implications of that.
