### ISSUE TITLE
Feature request: flow explain -command to explain the type

### ISSUE THREAD

**Issue by villesau** [facebook/flow#5610]
Some times would be nice to see what flow knows about certain types. [Let's take this as an example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAjGALxgDeAPoQFxgB2ArgLYBGeATtQL4DcmXAUIAmclWoAhBiw7c+gofjABhCSTAAyIqOUEAImAk0AdOZIAaMOdNjFqIA)

I'd like to be able to know what exactly flow thinks type C and type D are. How they are different? Now Flow is more like a black box what comest to resulting types. I can only try out with different ways to see if there are any differences. More practical would be if I could just hover over the type and flow would print the exact type for me as it would be defined. That could be achieved with command like `flow explain /path/to/file.js 6 6` this would then print the shape which satisfies type C, something like: `{|A: number, B: number|}`. This would help a lot to figure out some of the type errors flow gives.

Would that make sense or is it already somehow possible?
  
  E: A tool like try flow to show resulting types would also be really nice btw!

**Comment by jcready** [comment]
What you're asking for already exists.

```
flow type-at-pos /path/to/file.js 6 6
```

**Comment by villesau** [comment]
@jcready that is not the same. For that piece of code in the link the command returns `(unknown)` for the position. Also, for other parts it returns very vague types, like `object literal` or the name of the type. That does not help debugging the type definition at all.

**Comment by jcready** [comment]
@stereobooster I believe @villesau wants `type C` to be displayed as:

```ts
type C = {|A: number|} & {|B: number|}
```

**Comment by SamChou19815** [comment]
Now hover generally tries to show the types in the most helpful way. Since the request in this issue is quite vague, I will close this unless there are other specific feedback.
