### ISSUE TITLE
Issues with currying, $ElementType, and generics

### ISSUE THREAD

**Issue by spicydonuts** [facebook/flow#5611]
I commented out the lines which do not type check.  I'm not sure if these are separate issues or not.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAHMBTfABQCc4AHMAXjAB4B5ALjAG8BqAbQMoBLbEQC6HALaCAHiQAmAXwA0YchwAkAaRIBPXKwB8BgBRwOLFTQ7kAlBoCiMEhJLZ8AFR00SrFeQMMBqhgYHC8NKIA3OhYeISkFNQ0AMIArpRC8gzM7Fx8AsJikjLyyqoa2nqGJlaqNoFgpuZ2YOqOzq4eXj4WqgH0QSFhEdHoxglUtMacYFBwZmAArGBlAORzcKst2KkSAEYklDaRYMDAYADqcJQA1rgquACGLmCPuGAk0s80TmDCYHI4BhcKgzo0JklprN5hxlmsNlsOAURMdTucrrd7h9pN4MPgsodqJRQedxmRJjQoRtYSsVKs9o9KIiwDt9odUWCMXcVJ9cfi5B8Mtd0GCyYlaGkMoJ5MZ1vMtlSYUsVttdgcjicwQARQQC7BwQi8kh4wVEkng8lJSWZOSyhE2RULOEtZFEDnnew4438gGCKBQQ6dU3C0UQiXpG2yhlMh0zanKhSqtkatFgT18rJyP0ByhBwkh84YCPSgUAN0OuEEOD+71SOyeeyc6HNADkDWBcOkSH8oH98Kt3rmYI8fXtUoR8AALQTvQEkXDYVaEBDXG4fQRTw5sEWFnAEYiW2gXDeT9zZVgcHj8fBCETiMBSWSKPwVXT6FgGFTuBxOFxuTzeL4fQmAsvS1LYHBngM5pDOEUTNmC5BwLglaNjorwwLgcBgEOI5ZAAtPhYCbrg3ZQHWeJVngALYZuHbPN2U6FCoY4TpO3a5kWlCVuWoTYCQ5pzu8+oTt0YAYOxGA3NumB7oQdb4IIMDnu4NQcMY7j1AMYB7PMMAqFA6maQ0xnQSExj4JBLRQQEnDBCEYBOIQlCQdkUAWTY9khICXBeQ5lBuR5fkKGACDTr8xgAISUkcnkOThZDpNgOH2QoO7iXJYAKUpABMKlqY0pkBLpcD6bMRlaQERUwY0llgJprnaXZYLxbE+4BYw7n4J5LX+YllDJTF9QAPw4WAHDZTAxg0AZDpHDVChAA

**Comment by apsavin** [comment]
See [corrected version](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAHMBTfABQCc4AHMAXjAB4B5ALjBYCMArEjfABow5DgBIA0iQCeuVgD55ACjgcWwmh3IBKcQFEYJALYls+ACrSaJVsPLyG81GDBwA2jQC6AbnRY8hKQU1DQAwgCulJQAliQAJgzMosjKmiLajmBKrGq8-PjKqpy6YGIGxqYWVjbqIg70Ti7uXtq+6EpBVLRKAN5gUHBFAKxgAL7CAOQDcBMl2OFGXCSUrWDAwGAA6nCUANa4wrgAhiZgR7hgJAAeJzSGYNHYYHFwGLio61mdIb39gxwjcZgKaDWYcAgxbBEVafbZ7A6XK7WATxS5RHYfDYdMhdGi-aYAsaTLhHShgsDzRbLGEbOH7YTXZH4VHLaiUdrfWgRKKxOJKEEzbT4-5gQFzBZLFbeNYbAAi0QS2DghEZ+TRbMxXxxIW5MXi-Oms2FwzGJQhj2h0s+eiR+VRcWiUCgy0q6oxn2xwS5kT1fImJLJQr6BNFpo4lMlNLANqZ9sdzsortZGKAA) of first two functions

**Comment by apsavin** [comment]
Should I take a look on others?

**Comment by spicydonuts** [comment]
Interesting.. I guess I don't understand the difference, especially since the way I had them is how `$ElementType<>` is used in the docs.  The `*` in the curried version does make sense, but shouldn't that mean there _is_ an inferred type the `*` can be replaced with?

**Comment by apsavin** [comment]
Well, talking about the type of the curried version. You can't type `P` as `$Keys<O>` because you use `P` in a function that knows nothing about `O` on the moment when you call it (and you can use returned function with different objects). I'm not sure I answered the question though)

**Comment by spicydonuts** [comment]
That makes sense.  I guess I'm wondering if there's something else you can put there, like `<P: ValidElementTypeKey>`, whatever that missing constraint is that becomes a problem without the `: *`.

**Comment by apsavin** [comment]
>I'm wondering if there's something else you can put there

I'm not sure, but I think there's nothing wrong with `*`.

**Comment by spicydonuts** [comment]
I don't think there's anything wrong with it, but as I understand it it isn't really a type -- it's a placeholder for the compiler to infer a type.  The reason this bugs me is that I don't know what that inferred type is.  It doesn't seem to be documented anywhere.  If it's just "magic" it's hard to debug or build an understanding that lets me use it in other situations.  I'd like to leave this open to see if anyone feels able to answer that part of the question.  Thanks for the help though, it compiles now at least 🙂

**Comment by apsavin** [comment]
> what that inferred type is

I think the inferred type is string literal type. For string `'foo'` the type is `'foo'`, not `string`

**Comment by spicydonuts** [comment]
Ahh, that makes sense.  Maybe it's impossible to write without the `*`.. (which seems wrong -- the `O` should be definable higher up or there should be a way to represent the yet-to-be-provided type so `$Keys` is usable..
