### ISSUE TITLE
Docs say Unused Suppression is an error; Changelog says warning

### ISSUE THREAD

**Issue by Peeja** [facebook/flow#5612]
["Unused Suppression" is now a warning](https://github.com/facebook/flow/blob/master/Changelog.md#0540), but the [config docs](https://flow.org/en/docs/config/options/#toc-suppress-comment-regex) still say it's an error.

**Comment by Peeja** [comment]
(I couldn't figure out how to get warnings to show up; turns out it's a config option and CLI flag. No Flow bug here, just a docs bug.)

**Comment by ryami333** [comment]
Would be nice if there was a config option to elevate Unused Suppression warnings to errors, for CI/CD purposes.
