### ISSUE TITLE
Flow coverage appears not to know about $Compose

### ISSUE THREAD

**Issue by Peeja** [facebook/flow#5613]
I may be misdiagnosing the problem. Here's what I'm seeing.

When I use `recompose.compose()` in my app, Atom tells me that it's not covered by Flow. It's defined as `$Compose`, and Flow does appear to be able to see that definition.

When I open [the `$Compose` test file](https://github.com/facebook/flow/blob/6c489feea105adde3bfd85b4035b90fc4f2d099f/tests/compose/basic.js) in Atom, I see that most of the file is considered not covered by Flow. `flow coverage basic.js` reports `Covered: 79.17% (38 of 48 expressions`; given the code, I would expect 100%.

**Comment by chrisnojima** [comment]
I get this as well. I'm using 63.1 and compose from recompose (which uses $Compose) https://github.com/acdlite/recompose/blob/master/types/flow-typed/recompose_v0.24.x/flow_v0.55.x-/recompose_v0.24.x.js#L78
and flow coverage --color marks my compose call as red

**Comment by volkanunsal** [comment]
Same issue here.

**Comment by lo-corp** [comment]
Please open this ticket. Code coverage issue happens till date.

**Comment by goodmind** [comment]
@lo-corp I can't repro it with `compose`
