### ISSUE TITLE
Can't use NaN in union type

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#5615]
Not sure why the following wouldn't be allowed:
```js
/* @flow */

type MaybeDigitalValue = 0 | 1 | NaN
```

```
3: type MaybeDigitalValue = 0 | 1 | NaN
                                    ^ number. Ineligible value used in/as type annotation (did you forget 'typeof'?)
3: type MaybeDigitalValue = 0 | 1 | NaN
                                    ^ NaN
```

**Comment by jcready** [comment]
I'll just quote [the reason TypeScript doesn't have a `NaN` literal either](https://github.com/Microsoft/TypeScript/issues/15135#issuecomment-296850977):

> `NaN` is not semantically a unit type the same way 0 is -- any number of _different_ invalid operations produce `NaN`; this is also somewhat true of `Infinity`. `NaN`'s odd behavior with `===` would also introduce a bunch of extra logic in how we narrow.

(Note: `Infinity` and `-Infinity` aren't allowed either)

**Comment by jedwards1211** [comment]
Ah, I see.  Well I can use `null` instead, so it's not a huge problem.
