### ISSUE TITLE
Large sections of code is not covered by flow coverage

### ISSUE THREAD

**Issue by makandre** [facebook/flow#5616]
I'm trying out Flow for the first time with just a Hello World express app, and getting warnings that a large part of the file is "uncovered code". I'm not sure if this is expected or if I'm missing some configuration.

Using:
`flow-bin`: v0.62.0
`flow-typed`: v2.2.3
flow VSCode plugin: v0.7.3

And installed flow type definition for `express_v4.16.x`

As you can see almost the whole file is flagged as uncovered.

![image](https://user-images.githubusercontent.com/17596240/34618098-ad41a296-f20b-11e7-8e75-f5cf6d6f40ee.png)

My test repo is at https://github.com/makandre/flowtest

**Comment by future-challenger** [comment]
i met this problem too..

**Comment by AugustinLF** [comment]
You need to add the `flow-typed` repo to the libs section of your `.flowconfig` :) https://flow.org/en/docs/libdefs/

**Comment by MartinCerny-awin** [comment]
@AugustinLF It is not necessary if it folder is called /flow-typed It should find libs section automatically.

I am having the same problem.

**Comment by MartinCerny-awin** [comment]
The issue is because imported libraries (modules) are not using flow.

**Comment by danielo515** [comment]
How can I see the reasons why some areas are not covered by flow? I have local files that import types from other files and they say they are not covered by flow, but they should!
