### ISSUE TITLE
Exact intersection type works. Should it?

### ISSUE THREAD

**Issue by vezaynk** [facebook/flow#5626]
```js
type A = {| foo: string |};
type B = { bar: number };
type AB = B & A;

declare var abc:AB;

// Doesn't work, obviously
abc.d = 3;

// Works... okay...
abc.foo = 'test';
abc.bar = 123;


// Doesn't work??
const ab: AB = { foo: 'test', bar: 123 };
```

[Online sample](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfKAzA9pgXFAzsAE4CWAdgOZQoC+A3AFCiRQBCCyUARgIZF5kArgFsuEIlHpNw0GO0TsAZLEYMAJhADGAGz7QAbnyg8umnHNUB6S1AAimCPjIByYFADumIgGsANFEwufRJMQXxtEAYTTQA6NQ4AZisbAHUvb3wYrIDvHhAsmKjTGKxMDldHYGdGaJjeCUQARgAmJIZ26zsHJ1cPdIB+foZNTDJCYy48OQ4kDGw8CsJnf3q8FoTJOiA)

Basically, what the `AB` type is suppose to mean a type which is EXACTLY like `A` but also intersects with `B`. The only possible intersection is where an object is exactly like `A` and `B` features all necessary properties.

It is late, I am tired and confused. Either this is a bug in Flow or [this](https://github.com/facebook/flow/issues/4946) thread is misleading. If the latter is true, then the weirdness in my code sample above should be explained and documented.

**Comment by dannyharding10** [comment]
As was [commented in the mentioned issue](https://github.com/facebook/flow/issues/4946#issuecomment-356002233), 

> the explanation for the difference is that declare var x: Type means "assume there is a variable x that already matches Type". And if there were an abc of type AB, it would be legal to set its foo and bar properties. But that's different from actually constructing a value of that type, which is impossible.

> The reason it's impossible is that no object can both have the key "bar" and yet only have the key "foo", which is what that intersection type is requiring.
