### ISSUE TITLE
0.63.x regression: setTimeout() & setInterval() return types broken

### ISSUE THREAD

**Issue by jaredh159** [facebook/flow#5627]
Error does not exist in `0.62.0`

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjgC4xsBXAWwCMBTAJzAF4xd78AVAS2vriV8ACmEBKVgD4wAbwC+AGjABmAAyqxAbkw4CYWgENG5KnSat2nAJLZ8TAG4GYoiS2nylajZqA

```ES6
// @flow
const foo: number = setTimeout(() => {}, 300);
const bar: number = setInterval(() => {}, 300);
```

```
3: const foo: number = setTimeout(() => {}, 300);
                       ^ TimeoutID. This type is incompatible with
3: const foo: number = setTimeout(() => {}, 300);
              ^ number
4: const bar: number = setInterval(() => {}, 300);
                       ^ IntervalID. This type is incompatible with
4: const bar: number = setInterval(() => {}, 300);
              ^ number
```

**Comment by TrySound** [comment]
@jaredh159 Not a regression. Just not documented. As you can see [here](https://github.com/facebook/flow/blob/master/lib/core.js#L730) number was replaced with opaque type to prevent passing incorrect values to clearTimeout/clearInterval. Try to infer opaque types.
```js
const foo: * = setTimeout(() => {}, 300);
const bar: * = setInterval(() => {}, 300);
```

**Comment by jaredh159** [comment]
I looked at the commit that made the change and I think I understand better.  You're trying to enforce the fact that you should only pass to `clearInterval` something that came from `setInterval` and so on.

That makes a certain amount of sense -- but I still think this might cause a lot of head-scratching and `// $FlowFixMe` because it seems broken not to be able to type the return of one of these functions as what they are -- a number.  Maybe a specific error message?  Is that even possible?

**Comment by TrySound** [comment]
It's private value which works only with pair. Passing wrong value may have same effect as passing wrong type. So semantically it's a good direction if you upgrade major version.

**Comment by TrySound** [comment]
I mean private type.

**Comment by TrySound** [comment]
Yeah, there should be a global type.

**Comment by jcready** [comment]
There are global types for these: ([Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjgC4wAVASwFsBTOAV3wEkARMAXjFzv2vpN8ACmEBKLgD4wAbwC+AGjABmAAyqxAbkw4CYAEYBDAE7kW2fHWMA3QzHZcefc5Zt3REztPlK1GzUA))

```js
const foo: TimeoutID = setTimeout(() => {}, 300);
const bar: IntervalID = setInterval(() => {}, 300);
```

**Comment by jaredh159** [comment]
@jcready oh great, thanks!

**Comment by lvdang** [comment]
does TimeoutID have a default type?

const foo: TimeoutID = ?; // number, string, boolean fails

**Comment by apsavin** [comment]
@lvdang if you need to initiate a constant, you can get `TimeoutID` only from `setTimeout` function.

**Comment by MrLoh** [comment]
@TrySound Ok I understand the reasoning of the introduction of `TimeoutID` type, but I don't understand what I should declare in my react components now. I usually do 

```js
class MyComponent extends React.Component<{}> {
  timeout: number;
  componentDidMount() {
    this.timeout = setTimeout(doSomethingLater, 1000)
  }
  componentWillUnmount() {
    clearTimeout(this.timeout)
  }
}
```

I’d expect to declar `timeout` now as type `TimeoutID` instead of `number`, but do I understand correctly, that I should declare it as `any`?

**Comment by TrySound** [comment]
@MrLoh `any` is unsound. You should use `TimeoutID`.

**Comment by lll000111** [comment]
@jaredh159, @MrLoh

> setTimeout and setInterval return numbers always. 

No they don't. On node.js they return an object: https://nodejs.org/dist/latest-v10.x/docs/api/timers.html#timers_class_timeout

**Comment by msh2050** [comment]
`import React, { Component } from "react";
import ReactDOM from "react-dom";
import WebFont from "webfontloader";

WebFont.load({
  google: {
    families: ["Titillium Web:300,400,700", "sans-serif"]
  }
});

type Props = {};
type State = {
  date: Date
};

class Clock extends Component<Props, State> {
  constructor(props) {
    super(props);
    this.state = { date: new Date() };
  }

  componentDidMount() {
    this.timerID = setInterval(() => this.tick(), 1000);
  }

  componentWillUnmount() {
    clearInterval(this.timerID);
  }

  tick() {
    this.setState({
      date: new Date()
    });
  }
  render() {
    return (
      <div>
        <h1>Hello, world!</h1>
        <h2>
          It is {this.state.date.toLocaleTimeString()}.
        </h2>
      </div>
    );
  }
}

const rootelement = document.getElementById("root");
if (rootelement == null) {
  throw new Error("no pad element");
}`

where I should define timerID

**Comment by kdrich** [comment]
> I don't understand what I should declare in my react components now. 

@MrLoh, depends on your setup. I'm doing this. Same idea, I just wait to initialize it. What did you end up doing?

```
export default class Header extends React.Component<{}, State> {
  state = { query: '' };
  @observable timerId: TimeoutID;

  doSearch = (): void => {
    if (typeof this.timerId === 'number') {
      clearInterval(this.timerId);
    }

    this.timerId = setTimeout(() => {
      const { query } = this.state;

      if (query.trim().length > 0) {
        console.log(`Fake searching for "${query}" with timerId ${String(this.timerId)}`);
      }

    }, 300);
  }

  // https://flow.org/en/docs/react/events/
  setQuery = (e: SyntheticEvent<HTMLInputElement>): void => {
    if (typeof e.currentTarget.value === 'string') {
      this.setState({query: e.currentTarget.value }, this.doSearch);
    }
  }

...
```
