### ISSUE TITLE
Underscore starting fields not inherited (bug or undocumented feature?)

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#563]
When a class field starts with an underscore, it's not inherited further. Example:

    class Foo {
        _value: number;
    }
    
    class Bar extends Foo {
        tellValue(): number {
            return this._value; 
        }
    }

Doesn't typecheck. The same code looking like this typechecks:

    class Foo {
        value: number;
    }
    
    class Bar extends Foo {
        tellValue(): number {
            return this.value; 
        }
    }

It might be a feature, since underscore fields are usually taken as "private" (in Java terms). However I don't see this feature documented anywhere.

**Comment by mroch** [comment]
yeah, you're correct that this is an undocumented "feature" (d'oh!).

It's assuming that you're using Facebook's [[https://github.com/facebook/jstransform/blob/master/visitors/es6-class-visitors.js | ES6 class transform]], which "munges" underscore-prefixed properties in order to make them more or less truly private.

that is, we transform `_value` into something like `$<className>_value` (`$Foo_value`), so that if someone tried to write `someFoo._value`, it wouldn't work since that `_value` is either not transformed (if not part of a class) or is transformed into the wrong name, like `$Bar_value` in your example. this also prevents them from being inherited, as you noted, even at runtime not just in Flow.

**Comment by samwgoldman** [comment]
I don't mind this convention, but at a minimum we should improve the error message here.

This feature, if documented, would also resolve #275, assuming we want to keep it around.

**Comment by runn1ng** [comment]
@mroch Oh OK. I am not using Facebook's ES6 class transforming at all (just babelify), so that's why it didn't really make much sense to me.

**Comment by popham** [comment]
This feature doesn't agree with the coding style of a library that I'm migrating to Flow.  I was completely mystified by a bunch of `Property not found in` messages (many under `protected` usage).  My convention is

* Leading underscore => unstable--use at your own risk.
* No leading underscore => public--stable throughout a major version, and before removing the it, it must exist in the deprecated state for a major version's entire duration.

(Analogous to Node streams `_readableState` and `_writableState`.  And I'm curious what would happen if I attempted to document them under `lib/node.js`.)

I would love to just yank this feature, but I guess there may be a bunch of devs that rely on it.  Would a PR get accepted that just yanks this feature, or would I need to maintain backwards compatibility?  (Another convention of mine is: undocumented => all bets are off.)

**Comment by gabelevi** [comment]
I don't think we can yank it completely. As @mroch mentioned above, it's a feature that goes with Facebook's ES6 class transform, and we do use that transform. Ideally we'd eventually add proper visibility modifiers like `private`, `protected`, `public`, etc. and use those in Flow and in the transforms to enforce visibility in a sane manner. But for now, we do still use the underscores.

I wouldn't be opposed to creating a config option to gate this or configure it. I'm not sure if we could default it to off (anyone using JSTransform is automatically getting the munging I think...not sure about Babel).

**Comment by popham** [comment]
I figured.  Can't blame me for trying.

I'll proceed with a `--no-underscore-munging` CLI flag and a `underscore_munging=boolean` config option (if there's an existing convention that configs default true/false, then `underscore_munging` -> `no_underscore_munging` if nec.).  Hopefully the default behavior can be flipped someday--it sounds like something to bundle with a major version shift.

**Comment by popham** [comment]
PR over at https://github.com/facebook/flow/pull/648.  1780 errors -> 970 errors in my library!

**Comment by mroch** [comment]
gonna close this since it's configurable now and off by default. having to opt into it takes care of it being surprising, IMO

thanks @popham

**Comment by runn1ng** [comment]
I actually started to like this feature :), how to turn it on? I cannot find it anywhere

**Comment by runn1ng** [comment]
oh nevermind, it's `munge_underscores` in flowconfig. Sorry

**Comment by vaukalak** [comment]
Hello.
in my `.flowconfig` I write:
```
[options]
munge_underscores=true
```

and here is my code:

```
'use strict';
class A {
    _privateProperty : number;
    constructor() {
        this._privateProperty = 2;
    }
}

var a : A = new A();
console.log(a._privateProperty);
```
and the execution log:
```
$: flow check

Found 0 errors
```

Do I understand correctly, that, when I have `munge_underscores=true`, this check should fail with error?

**Comment by bsr203** [comment]
I too curious about how to use this feature. I am using latest flow 0.22.1 , but doesn't give an error as @vaukalak pointed out.

**Comment by vpotseluyko** [comment]
+1 one here
