### ISSUE TITLE
Flow caches failures across processes (despite killall)

### ISSUE THREAD

**Issue by juicetin** [facebook/flow#5633]
System info:
`Linux machine 4.14.11-1-ARCH #1 SMP PREEMPT Wed Jan 3 07:02:42 UTC 2018 x86_64 GNU/Linux`
Flow info:
`Flow, a static type checker for JavaScript, version 0.59.0`

Logging this separately to #4555 as the issue description in that one currently specifies that the _flow_ (no pun intended) to get that bug is that it requires a `killall` - in my case, `killall` doesn't solve the problem (this is only mentioned in a comment on that issue).

I frequently get cached errors pointing towards lines that have clearly changed even using `killall`, and have to subsequently remove my $HOME/.cache/yarn contents to clear the error. E.g.

```
Error: <fiilename>:<filenumber>
101:     thing => thing.foo || null,
                            ^^^^^^^^^^^^^^^^ property `bar`. Property not found in
101:     context => context.foo || null,
                    ^^^^^^^ object type
```

**Comment by adeperio** [comment]
Same

**Comment by evbo** [comment]
This is still an issue. Can someone explain how to clear cached state? I've tried stopping and starting flow but problem persists.

**Comment by SamChou19815** [comment]
The issue is likely resolved a long time ago
