### ISSUE TITLE
Destructuring union types

### ISSUE THREAD

**Issue by maxsalven** [facebook/flow#5637]
```
type Union = { a: string } | { b: string };

const foo: Union = { a: "bar" };

const { a, b } = foo;
```

Is there any way to do this without Flow complaining? I know that one of my destructured values will be `undefined`, and that's fine, I still want to pull out both possible values.

**Comment by TrySound** [comment]
You can't access fields which probably do not exist. You can seal objects (so they can't have another fields) and check field existence to refine necessary type.

https://flow.org/try/#0C4TwDgpgBAqgdgSwPZygXigbwD5QIYBcUAzsAE4JwDmU2AvrVrgEZGkXW10DcAULwGMUpKADMkSIvGSoMmfEQBEzPGUVQe-BKKgAKcUgB0eAJRZeUPQeNtylKid50tO-RMPMzmC1fesSdtSOdEA

This probably can be closed.
/cc @vkurchatkin
