### ISSUE TITLE
JS list methods dosen't works with union of mixed array

### ISSUE THREAD

**Issue by Fi3** [facebook/flow#5639]
When we try to apply a js list method to an union type of mixed array type we have a flow error.
This do not happen if the union type is composed by array not mixed.
[try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgFIGUwwCWAzgC5gC2ApqQBZwAmYATgIYlVisB2YVzzOMzBxeAV26FRYUgE8ADpzhRKhAB5UmrAa1kyFVVHMVgAgmAC8qMGAA+YANoByY1QCMTgDRgyzQtwBzAF1rO0cXAwAmJxDUAGNRMjBaAC4zS3DXD28nSOiggG5UWgA6ACs4fwAKJ2AnAEp0TDAAFVoSMAY4MG44clpWeUVeBFoqEc4BgDdOCSleVxEVYkIKeRhObTY9VyMDMAAhS1D7B19-AO9zwJCbU+vg9ATuJIAvNKOLTINssCc4wisOAxIqlCrVWoNJpYADqQgA1to4BIGHsTAA5Y53HykPyBE5-LJOAkRRTRdCLdHmKzYhzo7zo25hOmxZ5JbhpKkZZxEnIAoExVDccqVbg1OqNIA)
Is this a bug?

**Comment by idiostruct** [comment]
This is not a bug. `A` seems to be a  [disjoint union](https://flow.org/en/docs/types/unions/#toc-disjoint-unions-with-exact-types) type.

**Comment by Fi3** [comment]
I don't understand why this should be the expected behaviour.

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
