### ISSUE TITLE
Unexpected successful compilation

### ISSUE THREAD

**Issue by megamaddu** [facebook/flow#5642]
Why aren't both calls errors in [this example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCgEsZ8BTAJwHFzsriMwBeMAHgBUA+ACgAdK5ACaMAhhQBcYHhwCULLmABGcODAA0YUZUpSOAbQC6svUYWowWnQDoSZKv0EiM48rPRY8hOxUoBlfG0WaQFhMUlpEHlmRRU1TW1dZCMTZMNzS0TbUl9HMJcKd3QfKlp6SkYeAA8FMCrrBHEWZlYAVk19AEZNACZNAGZNABZNVuNinKoA7Wra+sbCFraO7rA+sEGwEbAx2SA)?

I would expect `filterStar`'s call to create an error in `filterStar` itself, trying to unify two separate `*`s.

**Comment by SamChou19815** [comment]
* is now effectively any.
