### ISSUE TITLE
React Flow Types Aren't Defined

### ISSUE THREAD

**Issue by pizza-r0b** [facebook/flow#5643]
Using `react: ^16.2.0` I get 

`[flow] Named import from module react (This module has no named export called StatelessFunctionalComponent.)` 

when I 

`import type { StatelessFunctionalComponent } from 'react';`

According to https://flow.org/en/docs/react/types/ this should work, however it does not. So does that doc need to be updated, or am I doing something wrong?

**Comment by idiostruct** [comment]
What version of Flow are you using? `StatelessFunctionalComponent` type was introduced in 0.26.0.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
