### ISSUE TITLE
cannot nest modules in libdefs

### ISSUE THREAD

**Issue by techieshark** [facebook/flow#5644]
I'm interested in making a libdef for `google.maps` client side browser JS API (sidenote: if that exists please let me know and I'll skip the work).

I took the [Google Maps TypeScript definition](https://www.npmjs.com/package/@types/googlemaps) and tried using [flowgen](https://github.com/joarwilk/flowgen) to produce something, but I'm thinking the nested module nature of google maps api is problematic. 

Should something like the following work?  I tried it [on flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswBbODAVxhIHIBzOOem2sAb1TG7GzyJLkqNMLVL4ADgGc2nHvN64CxMFgAeEuIQAuYflKlgAspI4BfADRcF3PspLrNOvQQPGiAayyFzVm7aUBVQ0tXQBLADttbyh8HBITCQB5CW0wuAjDdktrGzsgx1CXfDcAGXxtUoj6DlyFHP9FfhUhajoJAniZWsb5fJVC531DAEFKbTgcOFIOrGjfOsb+hxCh10MAZSwiHAALACE4NQXGszqzs6A) as well as locally (putting the code below in `./flow-typed/google.flow.js` but it doesn't seem to work - 

```
declare module 'google' {
    declare module 'maps' {
        declare export class Map {},
        declare export class Marker {},
        declare export interface MapOptions {},
        declare export class LatLng {
        },
        declare module 'places' {
            declare export class Autocomplete {},
            declare export class SearchBox {},
        }
    }
}
```
I'm seeing this error:
```
$ flow
Library parse error:
flow-typed/google.flow.js:12
 12:     }
          ^^^ Unexpected identifier
```

**Comment by goodmind** [comment]
I believe new maps doesn't have nested modules https://github.com/goodmind/FlowDefinitelyTyped/blob/master/flow-types/types/%40google/maps_vx.x.x/flow_v0.25.x-/maps.js

**Comment by mroch** [comment]
for posterity, I think you'd type this like

```
declare module 'google/maps' {
  declare export class Map {}
  ...
}
declare module 'google/maps/places' {
  ...
}
```
