### ISSUE TITLE
$ObjMap produced types don't unify with objects with optional properties.

### ISSUE THREAD

**Issue by zgotsch** [facebook/flow#5648]
`$ObjMap`ed types don't play nice with optional properties.

```
type Id = <T>(T) => T

function id<T, O: {[key: string]: T}>(o: O): $ObjMap<O, Id> {
  return o;
}
    
type Foo = $ReadOnly<{foo?: number}>;
    
const foo: Foo = id({foo: 42}); // okay
const bar: Foo = id({}); // This shouldn't break, but it does
const baz: Foo = {}; // okay
```
https://flow.org/try/#0C4TwDgpgBAkgJlAvFAPAFQHwAo0EokZRoBQxAZgK4B2AxsAJYD2VU9c6ANFAPIBcUAbwDaAawgh+AZ2AAnelQDmAXX5oAvtkb9uufgBJuAIwBWAWQCGYFNy7xCA4lCgyIwCjJaMA3MTWOnUMSgkFAAYoyMSFB6AEoQ5nDcVAA2ICgCZBEA-PxUFAC2hhAyGj4BgTTM0lCZWmERUWxYGRH8ACwATGq4PpVU1YbmMvzhkchNAt1eUAD0M0QAFvSSUJILjBTJcFQA5MBQhi7mIsR9A+YAXiMNyJNeQA

**Comment by stereobooster** [comment]
The issue here is that `typeof id({})` is `{||}` e.g. object strictly without keys. 

```ts
const baz: Foo = ({}:{||}); // error
const baz: Foo = ({}:{}); // error
const baz: Foo = ({}:$Shape<{||}>); // ok
```

**Comment by goodmind** [comment]
I think this if fixed
