### ISSUE TITLE
Separate type doesn't check the implementation return type

### ISSUE THREAD

**Issue by sam-rad** [facebook/flow#5651]
What I have here is two types which I think are identical but the inline type can throws an error appropriately but the separate type does not:

```javascript
function getProp<O: { +[string]: * }, P: $Keys<O>>(p: P, o: O): $ElementType<O, P> {
  return null;
}
                     
(getProp('a', { a: 42 }): number); // Error
                     
                     
type Fn<O> = <O: { +[string]: * }, P: $Keys<O>>(p: P, o: O) => $ElementType<O, P>;
const f:Fn<*> = (p, o) => null;
    
(f('a', { a: 42 }): number); // OK
```

[flow/try](https://flow.org/try/#0FAMwrgdgxgLglgewgAgOYFMYAUBOCAOAPAPIBcyA3sgNQDaAzjDnBKgLrkBUyAvgDTIs5ACQBpdAE96JAHwyAFPnJYBCcsQCUIgKIAbdAFt0EGABUJ+dCQFYZlYMmQ5MYHCghhdugNzAeDx0Cg4JDgeQxsPHx5AHIAQxiBKjjyABYAJl4tZA8DACN0HA1vZAB6UuRtHDwcAJD60IamoOAYC3RkADEIWWQAXmQScio6RmZWDmRufkERcSlZBSVBVXUNfrthPUNjM3brQRlfKCRGZBBSbsJOOwHFVXW+uw8vXxb5EFiEpOQU5AysuRcgUiiVyshiKIgA)

**Comment by SamChou19815** [comment]
Closing since * is no longer supported
