### ISSUE TITLE
nested $Diff looses types in case of stateless functional react component

### ISSUE THREAD

**Issue by villesau** [facebook/flow#5652]
see this: [broken example with stateless functional component](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3BjviIEAntmpgA3gGEWuAHbU5BACqjqAGjABlAiQLUY1MmQBiAVzkN0cOSRgyBCpQF8wTFu070CvVH5FiYMoAFtSqgQC8YAA8AAqUAFxgAPIARgBW1AwAfAAUDvKKKmpxlNkAlGAR2WAFNkXh1NEAJAAi6FBQLe2dpZoSztn9g9l8AeKxzNgUURKoYGDY5GQEzGYA5sFJcmaYqdR46vOkqXRJK3jocuuoznyodDYrtR5RudhTZEmTcNOV1ZJjpwCGY8HIYgATdAAN2yxwWEg+vzIADolsZVnANsFnMdosAobC+LiHk9GOC3vAYEkQmE1P8anMFo85M8HAAmKpgKn5FjlPgLaIck50CISNhsVzAOHOIA)

Flow should complain that passtrough property is missing but it doesn't.

However, if i change the component to class based, it works like it should: 

[working class based example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3BjviIEAntmpgA3gGEWuAHbU5BACqjqAGjABlAiQLUY1MmQBiAVzkN0cOSRgyBCpQF8wTFu070CvVH5FiYMoAFtSqgQC8YAA8AAqUAFxgAPIARgBW1AwAfAAUDvKKKmpxlNkAlGAR2WAFNkXh1NEAJAAi6FBQLe2dpZoSztn9g9l8AeKxzNgUURKoYGDY5GQEzGYA5sFJcmaYqdR46vOkqXRJK3jocuuoznyodDDLtR7UAB76cgAmFDTeAHR1JwEOJTMg1OYLTjfA65SqQhZgTgEMx4OQxL7oABu2QkBGC6DI-2wYOJy1WcA2wWc0WAmJxfAWzlufjoNhWbnRUVy8BgSRCYTUlWqkmObLkHIcACYqmBefkWOVGTFpSc6BEJGw2K5gNlbkA)

and if you take the other $Diff away, things start to work again:

[example without double $Diff](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3BjviIEAntmpgA3gGEWuAHbU5BACqjqAGjABlAiQLUY1MmQBiAVzkN0cOSRgyBCpQF8wTFu070CvVH5FiYMoAFtSqgQC8YAA8AAqUAFxgAPIARgBW1AwAfAAUDvKKKmpxlNkAlGAR2WAFNkXh1NEAJAAi6FBQpZoSztnZfAHisczYFFESqGBg2ORkBMxmAObBSXJmmKnUeOpTpKl0SfN46HJLqM58qHQ287UeUbnYo2RJI3BjldWSe5wEZng5DEACboABu2T20wkzw+ZAAdLNjAs4Mtgs49tFgKCIXwMddbowgY94DAkiEwmovjVJtMbnI7g4AExVMCk-Iscp8abRZluZiYACyJGw7TIswIdGCyjg7zGEQkbDYrhIBwVStcwEhziAA
)

This makes it impossible to write certain library definitions, like for react-redux.

**Comment by SamChou19815** [comment]
The issue is fixed a while ago
