### ISSUE TITLE
gen-flow-files generates wrong .js.flow files with multibyte string literal type

### ISSUE THREAD

**Issue by hakobe** [facebook/flow#5654]
Unicode string including non-ascii characters can be used for literal type like below.

```javascript
// @flow
export const greeting: "こんにちは" = "こんにちは"
```

When I run `flow gen-flow-files` against this code, I get the .js.flow file below.

```javascript
// @flow

declare export var greeting: "\227\129\147\227\130\147\227\129\171\227\129\161\227\129\175";
```

So that this literal type string contains octal escape sequences, flow produces errors when this file is loaded.

```
Error: greeting.js.flow:6
  6: declare export var greeting: "\227\129\147\227\130\147\227\129\171\227\129\161\227\129\175";
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ Octal literals are not allowed in strict mode.
```

To reproduce this error, you can use this gist https://gist.github.com/hakobe/3e05015b9e3b1538c8326e4aa88a635f .

In order to fix this error, I think this code should be changed.

https://github.com/facebook/flow/blob/aaa1189ecb4ca5f716538ffaa97138cc48305229/src/typing/codegen.ml#L305

It looks that generated code with OCaml's `Printf.printf "%S" v` is not compatible with JavaScript.

**Comment by TrySound** [comment]
gen-flow-files is removed. A replacement is coming soon.
