### ISSUE TITLE
Object type can flow freely into exact types (since 0.53)

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#5662]
Not sure if this is expected behavior, but I was not able to find it in the changelogs and found it surprising.

[Flow try](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPlAZggXFAZ2ACcBLAOwHMp0BfAbgCgBjOcoqOAIwCt8B5XhGbBkaBo0YAKbn1gIAlFAD0yqAElyEAB4BDEVFCQopAifKsAtmF3BSXADbQA7qWAALKDv2ij0CtgOcM5QADxQAAwAdACsAEyMqlAAcogQxMRwxOaBwVAAfCjRMQDMURGMQA)
Switch to 0.52.0 to get the error behavior.

**Comment by samwgoldman** [comment]
That this worked before 0.53 was a bug. `Object` is the supertype, but also the subtype of all non-primitive types, including exact object types.
