### ISSUE TITLE
Flow allows writing new property to a mixed refined as object, but not to an object

### ISSUE THREAD

**Issue by dsilvasc** [facebook/flow#5664]
[This](https://flow.org/try/#0MYewdgzgLgBAtgLngSwB4FMAmMC8MDeAvgFDHIBmMAFHDAGR0xQCeADuiJbTjzAOQgARgCt0wKHwCUBYjHgA6ciBC5+ggIYAnPsRJlKNeoxbtO8XLwEixE6flkxQkWEOFIiquA9eLlqvhrauqQU1LQMTGwcXBZ4VqLiUjJyTtAwru6Eng6psHAATEhwaFiqrg6hNPlGkaZc1TxxrjZJ9nJyBb4qcYE6ciQkQA) doesn't seem to make sense:

```typescript
const m: mixed = {}

if (m && typeof m === 'object') {
  // flow allows this
  m.foo = 'bar'
}

if (m && typeof m === 'object') {
  const obj: {} = m
  // flow does not allow this
  obj.foo = 'bar'
}

if (m && typeof m === 'object') {
  const obj: {} = m
  const m2: mixed = obj
  if (m2 && typeof m2 === 'object') {
    // flow allows this
    m2.foo = 'bar'
  }
}
```

Flow complains about `obj.foo = 'bar'` but not about the others:

```
9:   obj.foo = 'bar'
         ^ property `foo`. Property not found in
9:   obj.foo = 'bar'
     ^ object type
```

Flow allows writing a new property after refining a mixed to object, but not when the type is object to start with.

**Comment by apsavin** [comment]
Take a look at [this](https://flow.org/try/#0MYewdgzgLgBAtgLngSwB4FMAmMC8MDeAvgFDHIBmMAFHDAGR0xQCeADuiJbTjzAOQgARgCt0wKHwCUBYjHgA6ciBC5+ggIYAnPsRJlKNeoxbtO8XLwEixE6flkxQkWEOFIA8tfGq4D14uVVPg1tXVIKaloGJjYOLgs8K1FxKRk5J2gYVyQiHwcM2DgAJiQ4NCxVVwcImiKjGNMuOp5E1xtU+zk5YoCVRJCdORISIA) and [this](https://flow.org/try/#0MYewdgzgLgBCBGArAXAbxgQ2TaAnAlmAOYwC+MAvDOljAOR51kDcAUKwogHTwa6X0AJgDMIIusyA). There's a difference between `Object` and `{}` types.

**Comment by dsilvasc** [comment]
Does the `typeof m === 'object'` condition then refine `m` from `mixed` to `Object` instead of `{}`?

**Comment by apsavin** [comment]
To `{[key: string]: mixed}`

**Comment by dsilvasc** [comment]
Oh I see.  Thank you -- not a bug then.  Closing.
