### ISSUE TITLE
Property not found error gets removed due to a ternary

### ISSUE THREAD

**Issue by drifkin** [facebook/flow#5666]
I was testing out the behavior of Flow when you attempt to read a property that doesn't exist on an object's class.

A simple test:

<https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAYTAG9UBfdDOAO1wBcwMwBeMGgUyUIAoBKANxVaDMAA8AXGABGcODA7YarMAEJVGAHS44AWw70AFgEsaAcwFA>
```javascript
/* @flow */

class C {
}

const c = new C();

const x: boolean = !!c.something;
```

gives an error, as expected:

```
8: const x: boolean = !!c.something;
                          ^ property `something`. Property not found in
8: const x: boolean = !!c.something;
                        ^ C
```

Now if I add a single line (that I think should probably also be an error):

<https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAYTAG9UBfdDOAO1wBcwMwBeMGgUyUIAoBKANxVaDMAE9WTAHS44AWw70AFgEsaAczAB+MPQBOAVw5gAXGCjYYuDgLDBgYADwBaZ2GwATDxw9gYajkwRRgAPMwAjODgYDmwaSQBCBIwZeUVVDQEgA>
```javascript
/* @flow */

class C {
}

const c = new C();

const y = c.something ? true : false; // <-- added line
const x: boolean = !!c.something;
```

it now says `No errors!`, even though the original error is still there.

I also noticed that this happens with plain objects, not just class instances.

**Comment by SamChou19815** [comment]
now both error
