### ISSUE TITLE
Type Refinement Works for || but not &&

### ISSUE THREAD

**Issue by arahansen** [facebook/flow#5669]
[This try flow](https://flow.org/try/#0GYVwdgxgLglg9mABAKzjMA5EBbAFGHAfgC5EDsAjAUwCcAaRAZyhoEEabT2aBDATwA8zGugDmAPgCUiAN4AoRIhjBE+HIgCEAXi2JwAEyrB0VfYgBk5suvFMW3AHQAbKmFFQAFtPmLFAej9ETxhGOx4oKiVQsDgoRAA3HicYM2A4GiCPEMRQSFgEDQVfGiooEBowIoBfIqKSsoq7Ng4AbXIAXUQAamtsByg4AGUWMVxJORq5XOh4JGMAD1MAKTRMHDVsEl7qeibuLg5+IRG3KVki5VVyRB1dAyMTMwAfJ97EW2FHFzdPbyL-QLBULMcKRbIxOKJZKpdKZbLTfJgQq+RD1cqVRQ1RR1UrovatDrdXr9IYnURjCZyIA)

Has two functions which should have logically equivalent branches, but one properly refines the type, while the other one loses the type refinement. Not sure why this would be?

Code:
```javascript
function joinNum(num?: number, strArr: Array<string>) {
  if (num !== undefined && num > strArr.length) {
    // this state is not valid for this function!
    return
  }
  
  return strArr[num] + num.toString()
}

function fixedJoinNum(num?: number, strArr: Array<string>) {
  if (num === undefined || num > strArr.length) {
    // this state is not valid for this function!
    return
  }
  
  return strArr[num] + num.toString()
}
```

**Comment by vkurchatkin** [comment]
This behaviour seems correct. In the first example `num` can still be undefined after `if`.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
