### ISSUE TITLE
Compound assignment of object property does not respect property variance

### ISSUE THREAD

**Issue by louischan-oursky** [facebook/flow#5671]
See https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhgQLxgDeAPqmGANQDGcArgHbkBOAXGE7sAtgCM8PADSpaAXwDc6NpwDOGMCQHEylGgzBsuvAQAZpC9CQB0h7hOZUAjIuu3eYJ-KA

Line 11 should be a type error

**Comment by goodmind** [comment]
Duplicate of #7195
