### ISSUE TITLE
Implicit type coersion of function to boolean

### ISSUE THREAD

**Issue by wereHamster** [facebook/flow#5674]
```
const f = (): string => ''
const b: boolean = f && …
```

Flow accepts this code. But the developer most likely wanted to call the function, ie. `const b = f() && …`. Since `f` is not defined as nullable, it doesn't make sense to attempt implicit coersion into boolean, as that will always succeed.

**Comment by michaelhogg** [comment]
I guess Flow is smart enough to figure out that the constant `f` contains a [truthy](https://developer.mozilla.org/en-US/docs/Glossary/Truthy) value (a function), and so it can simplify `f && …` to `…` (ie: it can safely ignore the `f &&` part).

Some more examples, using truthy and [falsy](https://developer.mozilla.org/en-US/docs/Glossary/Falsy) constants:

```js
const b: boolean = 0 && true;  // Flow error
const b: boolean = 1 && true;  // OK

const b: boolean = ''  && true;  // Flow error
const b: boolean = 'x' && true;  // OK
```

In the 2nd and 4th examples above, there's no possibility that `1` or `'x'` could ever get assigned to `b`, and so Flow is happy.

**Comment by wereHamster** [comment]
I'd really like to see flow enforcing both sides of binary operations (`&&` or `||`) to be of boolean type. If you meant to use those operations in a different context, say to fall back to a default value (`foo || fooDefault`), the ternary operator is often better suited (`foo === undefined ? fooDefault : foo`), and you won't ever run into problems because `0` is falsy (eg. given `foo=0` and `fooDefault=5`, `const myFoo = foo || fooDefault` will most likely not do what you wanted.

**Comment by kenrick95** [comment]
Another related use case in ternary operator: [Flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYBAzgMpwC2ApngBYFYDmAFAJQBcYARnHBi0AhiQDeqMGABO9DNJJRhMMrVQBfVDmJk8YBsINgAvKUo16TVmAD8YAOTD7YHvd72A3KiA). In this case, the expected behavior should be that the developer _calls_ the function instead of being implicitly coerced into boolean
