### ISSUE TITLE
How to get concrete type from maybe array

### ISSUE THREAD

**Issue by StevePotter** [facebook/flow#5676]
Hello, we are using a code generator to make Flow types for our GraphQL queries.  In my component, I need to access a type inside one of the generated query types.  For this I use `$PropertyType` and `$ElementType`.  Many of the generated types are maybe, annotated with`?`.  When I try to access an inner type that is a maybe type, I get an error like this:
```
Computed property/element cannot be accessed on possibly undefined value
```
An example is available [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKeATgM5wB2YAvGAN6phgDGAFgJYwAmJelALjAB+AIIkSAQywAeRs2aVJAWzxCyGEh0oBzADRMwAXwB8qI+mz4wAYU48+1OgBJCJOPhLYAKrjwzicio9MABydi5eflCzKwI7SNowZwBRGDxVSgxffBkEh34QgAYzVBYqDVZ7bgF87iT5MCVVIQAiACt+VvNUIA)

The code from that example is:
```
/* @flow */

type Person = {
  children: ?Array<{
    name: string,
  }>
}

type Children = $PropertyType<Person, 'children'>
type Child = $ElementType<Children, 0>

const child:Child = {
  name: "jen"
}
```

And it fails.  If I change `children: ?Array<{` to `children: Array<{` it works.  But my graphql schema can't change.  I can't find any Flow utility type to get the type of a 'maybe' property.  Like I would expect to be able to do:

```
type Children = $InnerType<$PropertyType<Person, 'children'>>
```
Where `$InnerType` strips the `?` (maybe) and just returns the array type.  Does anyone know how this could be achieved?  Thanks!

**Comment by TrySound** [comment]
There is `$NonMaybeType`
https://flow.org/try/#0MYewdgzgLgBAhgLhmArgWwEYFMBOMC8MAFAIxIAkAcuALJwCe2AKvQA5YA8A-KprgHwBKANxA

**Comment by StevePotter** [comment]
@TrySound thank you so much!  I didn't see this in the docs.  Thanks again!

**Comment by wouterb** [comment]
This issue helped me out. There is a PR #4351 that adds `$NonMaybeType` to the docs.
