### ISSUE TITLE
Broken interaction between optional object type field, parameter destructuring, and function scope.

### ISSUE THREAD

**Issue by jetpacmonkey** [facebook/flow#5677]
Essentially, I have a function which takes an optional parameter, renames it with destructuring, and then references that parameter from inside a returned closure.

```js
type Opts = { component?: string };
type ReturnedFn = () => string;
function getRenderFunction({ component: Component }: Opts): ReturnedFn {
  if (Component == null) {
    return () => 'foo';
  }

  return () => Component;
}
```
[recreated at flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAzmALxgDeYAxnALY5wB2erGAXAPxikYATgEtWAczABfANyZcBAEp4MAV0HsAJgDFWlMAAoAlJQB8-IaLGyoK1nQzC2YMcqWsNeQVtv3HrfbQMzGwc3GAAwkws7JxSXEQkpIbxSqrqeNq61KhgYMJQBpHBMRiUVKwqMDDG2bm5gspqukamYADkUHBwbbK5kuj1jeoGxhRmRdGhspJAA)

This is the most reduced testcase I could find that still breaks. If I do `const Component = component` inside my function, [everything is fine](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAzmALxgDeYAxnALY5wB2erGAXAPxikYATgEtWAczABfANyZcBAEp4MAV0HsAJgDFWlMAAoAlJQB8-IaLGyoK1nQzC2YMcqWsNeQVtv3HrfbQMzGwcGFJcRCSkhhFKqup42rrUqGD0bAJgAMJMLOycekF5obJpwlAGOcH5YRRUrCowMMYpaWmCymq6RqZgAORQcHB9pVLo7Z3qBsYUZlXFnLKSQA). Same if I make `component` [required](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAzmALxgDeYAxnALY5wB2erGAXGKRgE4BLVgHMwAXwDcmXAQBKeDAFd+7ACYAxVpTAAKAJSUAfLwHCR0qEtZ0MgtmBGKFrNXn4brt+6120GzGwc3GAAwkws7JwSPMRk+jwKyqp4mtrUqGBgglB64YFRGJRUrEowMIYZWVn8iiraBsZgAORQcHDN0lni6DV1qnqGFCb5kcHS4kA) or reference my variable [directly, instead of inside a returned function](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyOGAzmALxgDeYAxnALY5wB2erGAXAPxikYATgEtWAczABfANyooAV1Z0MwtmDF4MAJQ4ATPIIBii5atYAKWg2ZsO3MAGEmLdpylciJUgEoPAkeI0qGBgwlBg5k42rhiUVKzyMDDeQSEhgprygqxgAORQcHC5siGS6OmZ2Y7OtpyykkA).

My apologies if there's already an open issue for this. It proved difficult to search for, since people asking for type annotations inside destructuring kept on coming up, which is not what I'm running into here.

**Comment by jcready** [comment]
It's due to refinement invalidation. You perform a refinement and return a function which returns the non-constant variable you previously refined. The non-constant variable could be modified before your returned function gets called. Therefore the refinement is invalidated inside the returned function.

**Comment by jetpacmonkey** [comment]
Gotcha, ok, so `const Component = component` works because it's _not_ actually equivalent. The equivalent would be `let Component = component`, which would have the same error message because Flow can't ensure that the value isn't changed somehow. Kind of a bummer, but it makes sense, thanks.
