### ISSUE TITLE
Duplicate imports should error

### ISSUE THREAD

**Issue by mroch** [facebook/flow#568]
See https://people.mozilla.org/~jorendorff/es6-draft.html#sec-imports-static-semantics-early-errors

Since `import type[of]` mirrors `import`, duplicates of those should error too.

**Comment by jeffmo** [comment]
Indeed, because we don't have let bindings `import`s are currently approximated as vars.
Once we have let bindings (#431) this should be a trivial tweak to piggyback on that functionality

**Comment by rtsao** [comment]
I think this has since been fixed.

**Comment by calebmer** [comment]
Closing as [this has been fixed](https://flow.org/try/#0JYWwDg9gTgLgBAbwMIXBAdgU3TANHFNLHAXzgDMpU4ByKTAQwGMYaBuAKFEljhgE8wmRAAUArvUKRieOOMmpp2GGUrU6jFuyA).
