### ISSUE TITLE
Can't bind the apply function

### ISSUE THREAD

**Issue by marcusdarmstrong** [facebook/flow#5681]
Hi there! I've been trying to get rid of a $FlowFixMe in our codebase and have isolated it down to this:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1ACYqQCGArtPgBSQBcoAYmQHYDGuAlrMwJSgC8APlCQAdCQwZoAT1EAjDswI0eAbkRA

That is,

```javascript
// @flow

export default (f: Function) => f.apply.bind(f);
```

yields

```
3: export default (f: Function) => f.apply.bind(f);
                                   ^ call of method `bind`. Callable signature not found in
3: export default (f: Function) => f.apply.bind(f);
                                   ^ function type
```

Even though...

```javascript
const foo = () => console.log('Works');
const bar = f => f.apply.bind(f);
bar(foo)(); // Works
```

**Comment by oriSomething** [comment]
From curiosity, why binding `apply`?

**Comment by marcusdarmstrong** [comment]
Not my code so I can't be 100% sure, but I think it might have just been so that we could use an args array.

**Comment by SamChou19815** [comment]
This now works
