### ISSUE TITLE
'Property not found in object' error thrown incorrectly

### ISSUE THREAD

**Issue by tgds** [facebook/flow#5682]
Came across the [following issue](https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAHgB1gJwC6hwJ7rKgCCAxjgJawB2poAvKAN75HIBcoA5KQMIAVAJIB5AHIB9Uj1ABfFBmx5CxMpRq0AQk1bti3PkLFStPADSgqAE260ArgFsARsizzEntJlz6SFajomRFBQAB91QPoQ8MjNLS8lX1USAGUcAEMcEmYWRAVEcjoAZzwqWipqDOh0rK5QWuzdPIKi2lLQLGRre3I3XQAKUrruRpyrCqqazOzLDI06bgDNAEpRmZyAPlYY4vhK8gALUAH5qIA6FJWd0NDyDOKSIxEJaR5uPIBIO5K8DN0zppzjYANygECgACiWCw2G4AAVYcRcARQLRYHhILB7LRrBM4nQGABaUD8bBdSgxW6dZA4exYWigYbZEGIT4Kan3R68AQvUzvG7U0BtDrOAELWjA6xgiHiWCgNyw9wkskw5CUoWgADaAF1zo4MugBgNroxtmwunSGaBAXQpfJrhDoUqEUi3IQ0RjQFicXjygT6KAScJaEU1RqhZb6YzmchWdSObdrMhIBl7NAcJwqbco9bY-GPAVvMpQMnU+m8F0en0sIggA) when annotating one of my reducers. Line **24** should not throw an error, I believe, but it does. Seems to happen because action.id is used in a new scope.

```(javascript)
// @flow
export type ActionA = { type: 'ACTION_A' }
export type ActionB = { type: 'ACTION_B', id: number }


export type Action =
  | ActionA
  | ActionB

export type State = {
}

const initialState: State = {
}

const reducer = (state: State = initialState, action: Action): State => {
  switch (action.type) {
    case 'ACTION_A': {
	  const a = action.id; // Error: Property not found in ActionA - Correct
      return state;
	}
    case 'ACTION_B': {
      const b = action.id; // No error - Correct
      [].map(() => { return action.id }) // Error: Property not found in ActionA - Incorrect
      return state;
    }
    default:
      return state;
  }
}

export default reducer

```

**Comment by jcready** [comment]
It's due to refinement invalidation. You perform a refinement and then create a function which you pass to `[].map()`. Flow doesn't know when that function you created will get called. The action object could be modified before your function gets called, therefore the refinement is invalidated inside the function passed to `[].map()`. You can fix this by having your inner function return the `b` constant variable you created.

**Comment by tgds** [comment]
ah, that makes sense. thanks!
