### ISSUE TITLE
Is there a good way to support import/require from flow.js?

### ISSUE THREAD

**Issue by kasbah** [facebook/flow#5684]
Hey, I compiled flow.js and have successfully used `flow.check` and `flow.typeAtPos` and others. I am a bit unclear on what `flow.registerFile` and `flow.setLibs` are supposed to do even after looking at the source code. 

What I am really looking for is a good way to recursively load module either through Node's `module.exports/require` or through ES6 `export/import`. Is there a good way to provide additional modules that could optionally be imported in the main source file? Likely I would have to read the contents of these files and then pass them to flow, but I can't see how.

**Comment by SamChou19815** [comment]
The compiled flow.js is considered to be unsupported for general use. We only guarantee that it works well for try-flow purposes
