### ISSUE TITLE
Disjoint Union boolean comparison error

### ISSUE THREAD

**Issue by taylor-cedar** [facebook/flow#5685]
Disjoint unions throw `Property not found in` on existence checks. Below is an example

```js
type Disjoint = { a: 1 } | { b: 2 };
const obj: Disjoint = { a: 1 }; 

const isA = obj.a == null;  // error  ^ property `a`. Property not found

/*
Forced to do
const isA = obj.a == null ? true : false;
*/
```

Here is the link to the try flow https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAiAlgM4BWcxAdhmALxgDeYAhgFxgCMYAvmAB9mYAEacATHwDcqAMZxqpOnBHlOJClVoNhHbtLDp5iumQCCOleQB0rBo2oBXGDBmpQqAGJwATrLwAJmAYcGABcHIKSmDmlqq29mBOLmAA-ME+jgScUKwwpHgyKEA.

**Comment by SamChou19815** [comment]
This is now supported, if all objects in the union are exact
