### ISSUE TITLE
Reverse $ReadOnly and $Exact operator

### ISSUE THREAD

**Issue by jpolo** [facebook/flow#5687]
Hi,

I have been recently with $ReadOnly and $Exact operators, and it seems it is difficult/impossible to reverse $Readonly operator. (convert an immutable entity to a mutable one)

Example :
https://flow.org/try/#0GYVwdgxgLglg9mABBOAHAngHgCoD4AUcAXIgCQBKApgIYAmA8mADZZ4CUiA3gFCKIBOlKCH5JCJbGwDc3AL7cUYAM5QBNWghb0ARgCtK0RAF5E+TomBxiiAIyJZJCusYtMnS9bAgAttsr9ZXGkFBBVEAHd+GChqbSZKHX1DExQMfEE6TXREgyhgyOjY+JzoADoPY0QAJikgA

I had same problem with $Exact operator, which I did not know how to reverse.
Maybe something like $Invariant<T> and $Inexact<T> type utilities ?

**Comment by oriSomething** [comment]
`$Inexact` can be very useful!

**Comment by vkurchatkin** [comment]
Here is `$Inexact` for you:

```js
type $Inexact<T> = { ...T };
```

**Comment by oriSomething** [comment]
@vkurchatkin good to know, because with objects that aren't "exact" it works differently which is confusing so I didn't thought it does it, since:

```js
/* @flow */

type E = { x: number };
type I = { ...E };

// No errors
var o: I = {  }; 
```
I don't know if it's in the docs. But It's unexpected behavior

**Comment by goodmind** [comment]
Better inexact
```js
type $Inexact<T> = {...$Exact<T>}
```

**Comment by rizkyario** [comment]
Have you tried using

```
$Shape<T>
```

**Comment by rdourado** [comment]
What about "`$Writable`"?

**Comment by SamChou19815** [comment]
You can use spread

**Comment by hurrymaplelad** [comment]
@SamChou19815 FYI, `$ReadOnly` currently works with interfaces, while spreading does not. I believe there's inverse of $ReadOnly for interfaces.

[Try Flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQqeK4kIABABJTnAAA6UE5ws5GGQnPspigCAA3IL6YLBQB6JWc2zwSgiTlwCQAchInIA7qZLGg2shBbZ7NrxbyALx8sWc-nJF30uVQOAAbRdGBdAF1OQ6XWgXR7laqMjttRJOVE2ANaBaoAAKODigAkACVWGwAPJQQYAHm5AD4AJQ+10gQPB8AuxVQFWcqS0FsQTlR7Axo0m1rdjAIFFQZMrYw8gBMQb5Vln2dzBeLZfdjdyIAaJhIcGgSQaAAYrBOAKwHvcgelAA)
