### ISSUE TITLE
ALL properties are optional - but Flow complains about assigning an empty object

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5688]
[Flow Try Link](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AzgFXNAvFA3gD4BQUZUS8yKAhgDYCMA-AFxQoCuAtgEYQBOAGlLlKiVPQBMrKDyRI6EGimHkKVCXQDMMuQqUpihAL4BuYsQBmHFAGNxKKABMIXJFAAUY6mhlwHmNhQePjGAJRsAG5ICE4EImQA9IlQAHTpxGbEQA)

Code:

```js
type OptionsType = {|
    optional1?: number,
    optional2?: boolean,
    optional3?: boolean
|};

function demo (options?: OptionsType = {}): void {
    // ...
};
```

Error message:

```
7: function demo (options?: OptionsType = {}): void {
                                          ^ object literal. Inexact type is incompatible with exact type
7: function demo (options?: OptionsType = {}): void {
                            ^ OptionsType
```

It works when I use `{ .... }` instead of `{| .... |}` for the type definition, but I don't want that because then using a non-existent property would work too (example: `demo({foo:1});` would not cause an error message either). I declared ALL properties as optional, therefor assigning an empty object should not cause an error.

**Comment by idiostruct** [comment]
Does an inexact type and `$Shape<T>` satisfy your requirements: [Try Flow](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7AzgFXNAvFA3gFBRRLzIoCGANgIwD8AXFCgK4C2ARhAE4A0xUuVQ0ATEyickSahEooBJMohHUAzBKky5KQgF8A3IUIAzVigDGKlFAAmEdkigAKZRTQSAJAGUAFpUgAHjhrTGwAPig8fD0ASmYANyQEWwJBEgB6DKgAOjz9I0J7R2dYo2KkZxiyoodK-DdVWmZaOPK6qsaqOha+IWsxZhMaNAg22pKG4W7mqFo+rsGoYepRhemaNWZgHlYxmqyoAFEeHiQeQkOKzo2eub6TaRa2oA)?

**Comment by lll000111** [comment]
@idiostruct Good to know there is a workaround! However, the original construct should work, the type definition is fulfilled by an empty object.

**Comment by jcready** [comment]
This looks to be related to #4582

The same workaround should work for you though. It not _exactly_ exact, but it gets the job done in most situations:

```js
type OptionsType = {
    optional1?: number,
    optional2?: boolean,
    optional3?: boolean,
    [any]: empty
};
```

**Comment by lll000111** [comment]
@jcready 

> The same workaround should work for you though.

See my previous comment :-)

**Comment by jcready** [comment]
This is a duplicate bug report of #4582

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
