### ISSUE TITLE
Generic type constraints don't work in some case

### ISSUE THREAD

**Issue by loyd** [facebook/flow#5690]
For instance, here it is not checked:
```js
declare function foo<A: number>((a: A) => void): void;
declare function cb(a: string): void;
foo(cb);
```

[try it](https://flow.org/try/#0PTAEAEDMBsHsHcBQyAmBTAxtAhgJzaJAK4B2GALgJawmGywA8AggFyglEC2ARmrgHwAKQdjZMAlKAC8-UADdYlFOLYKlAbkToseAsTJUaoDNxFsAzuVyUSAcxXzFKTZHqCT49UA)

Meanwhile in the code below (without generic types), it is checked as expected:
```js
declare function foo((a: number) => void): void;
declare function cb(a: string): void;
foo(cb);
```

[try it](https://flow.org/try/#0PTAEAEDMBsHsHcBQyAmBTAxtAhgJzaJAK4B2GALgJawmGywAUD2AXKCUQLYBGauAlKAC8APlAA3WJRT82k6QG5E6LHgLEyVGqAzdmbAM7lclEgHNZEqSiWR6DXfwVA)

**Comment by lttb** [comment]
Just to note, this example works too

```js
declare function foo<V: <A: number>(a: A) => void>(V): void;
declare function cb(a: string): void;
foo(cb);
```

I think there are some problems with argument refinements

**Comment by stereobooster** [comment]
Similar to https://github.com/facebook/flow/issues/5903 ?

**Comment by SamChou19815** [comment]
Now both work
