### ISSUE TITLE
Bridge javascript string const and type declarations

### ISSUE THREAD

**Issue by gyrodave** [facebook/flow#5691]
Hi,

I'm using flow with redux and face what looks like to be a very common source of fustration amongst redux users.

When declaring types for redux action eg : 
```javascript
type DeleteItemAction = {
 type: 'DELETE_ACTION',
 id: number,
}
```
This "DELETE_ACTION" string will be used in a lots of places therefore, the common pattern is to declare and export a const DELETE_ACTION_CONST = "DELETE_ACTION" (much less prone to making spelling mistakes).

Now we are left with duplication of declaration. A const xxx = "DELETE_ACTION" and type: 'DELETE_ACTION'. I obviously tried to do a type declaration that looks like this : 

```javascript
type DeleteItemAction = {
 type: DELETE_ACTION_CONST,
 id: number,
}
```

This doesn't work as flow is not designed to use const values in type declaration. This seems to be quite ligit as const value can be the result of complex calculations ( returned by a function ) therefore requiring flow runtime to look through and execute to code that returns the value.

**As as much I understand that going from javascript const to flow type declartions is not feasible I don't  see what would make going from flow declartion to javascript const not possible.**

Being able to declare simple string const like so : 

```javascript
const DELETE_ACTION: $FlowSolidString = "ACTION_DELETE" 
```

And have flow to transpile this to : 

```javascript
type DELETE_ACTION_TYPE = "ACTION_DELETE"
const DELETE_ACTION = "ACTION_DELETE" 
```

Would, I think, be quite handy.

**Comment by stereobooster** [comment]
This is what we got now

```ts
const delete_action: "DELETE_ACTION" = "DELETE_ACTION";
```

[try](https://flow.org/try/#0MYewdgzgLgBAJgUwDYKgg+gQ2FAluALhgCIARAUQBlyAVc9AQQGEaBJAeQDliYBeEitTqMWHbgG4AUKEixMcOFhz4wRYg1KkRbLj37rN2scSlQAngAcEMbHnAQ+Mc1ZAAzeMlQZbKmAB8nSwQ3GwUlOzApAApidhoACXIAJSNdAh97AEogA)
