### ISSUE TITLE
defaultProps in StatelessFunctionalComponent error

### ISSUE THREAD

**Issue by andrewkslv** [facebook/flow#5692]
Getting error by setting defaultProps in stateless component:

```js
/* @flow */
import * as React from 'react';

type TouchableProps = {borderless?: boolean, children?: React.Node};
type TouchableType = React.StatelessFunctionalComponent<TouchableProps>;

const Touchable: TouchableType = (props: TouchableProps) => <div>{props.children}</div>

Touchable.defaultProps = {borderless: false}
```

[flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudQgE8cNMABU4AV3oALUgCMYNAAosclALxgA3vIIATGviXlyAfgBcYPXCWkAdgBowsjDH1d7l6t0IA6ADk4QwBffiERcSlZBSUxYVEtWgZ-AGVCUkIaE3IAMUl7Rgw4e1IYAGFWPHsae0IAHglpOUUVNXIAPn5UehLyYiaY1qtBlriEsC0AChx2keixtrh1AEpJjrB6-QwANw7tWeXyP1d3TxD64G299FHYmj9DKFJJGEJVI8mdPXxDYxpTFZnjByDQQqggA)

Expected behavior: no errors.

**Comment by nanot1m** [comment]
`borderless` should not be optional in TouchableProps

**Comment by nanot1m** [comment]
[try this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudQgE8cNMABU4AV3oALUgCMYNAAosclALxgA3vIIATGviXlyALjB64S0gDsANGFkYY+rrYD8F2g0IA6ADk4QwBfflR6OFtyYglpOUVRLQAKHDVzcSlZBSVVOHUASjANAD4wAB59DAA3Eu00-PI-Z1d3EPLgKtr0OOzEv0MoUkkYQjz1Yp09fENjGlMLIZhyGhD0XnLehKUwYBKgA)

**Comment by casr** [comment]
I just across this myself. The definition doesn't include defaultProps:

```js
/**
 * The type of a stateless functional component. In most cases these components
 * are a single function. However, they may have some static properties that we
 * can type check.
 */
declare type React$StatelessFunctionalComponent<Props> = {
  (props: Props, context: any): React$Node,
  displayName?: ?string,
  propTypes?: $Subtype<{[_: $Keys<Props>]: any}>,
  contextTypes?: any
};
```

[Flow docs](https://flow.org/en/docs/react/components/#toc-using-default-props-for-functional-components) do not include type at all. Seems like an oversight to me.

Something that can be PRd perhaps?

**Comment by pigoz** [comment]
if you omit TouchableType flow will infer the correct type. You also want to make the borderless field not optional, flow will infer the correct ElementConfig from Props and defaultProps.

ie: 

```
/* @flow */
import * as React from 'react';

type TouchableProps = {borderless: boolean, children?: React.Node};
type TouchableType = React.StatelessFunctionalComponent<TouchableProps>;

const Touchable = (props: TouchableProps) => <div>{props.children}</div>

Touchable.defaultProps = {
  borderless: false
};

<Touchable>no errors</Touchable>;
```

[flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqgQCe2amAAqcAK50AFiQBGMagAVm2CgF4wAb3n4AJtTxKyZAFxg9cJSQB2AGjCz0MfZ1sB+CzXoEAdABycIYAvnxCIuJSsgpKYsKiWj4MfgDKBCQE1CZkAGKStgzocLYkMADCLLi21LYEADwS0nKKKmpkAHx8qHQlZERNMa1gWgAU2O0Wgy1KqnDqAJQjHWD1+ugAbh3aE-Nkfs6u7iH1wOtb-NOx1H6GUCSSMARz6iM6qGCWBkY5FvcwZGoqDC-Ea0Rm1A6tjgYCMzDwZFOV1aXSAA)

**Comment by mgtitimoli** [comment]
@pigoz: There are times when you have no other alternative than using StatelessFunctionalComponent or more generally ComponentType, for example when you want to help flow to get the type of a composition of higher-order components.

It would be super nice if we find a workaround to this issue.

**Comment by mgtitimoli** [comment]
BTW, I forgot to mention that there is a workaround, but it's really ugly, have a look:

```
const defaultProps = <define your defaultProps here>;

type PropsWithDefaults = Diff<Props, typeof defaultProps> & $Shape<typeof defaultProps>;

// $FlowFixMe: we need this to omit the error originally described :(
Object.assign(YourComponent, {defaultProps});
```

**Comment by mgtitimoli** [comment]
I've just noticed that combining $Diff with $Shape breaks the whole type!

@calebmer are you aware of this issue?
