### ISSUE TITLE
Type Inference issue

### ISSUE THREAD

**Issue by alexander-shvets** [facebook/flow#5693]
In comparison with TypeScript, Flow doesn't catch these errors:
```js
let n = 0
let s = "S"

test(n) // ok
// TypeScript only errors:
test(s)
n += s

let s2 = String()
let n2 = n // inherit type Number
test(n2)  // ok
// TypeScript only errors:
test(s2) 
n2 += s2

function test(n = 0) {}
```
Why? Is it ideology-based decision?

**Comment by jcready** [comment]
Since you didn't specifically annotate the test function, flow bases its inference off of the types with which you call it. Flow infers your test function to have the type:

```js
(n?: number | string) => void
```

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by ShalokShalom** [comment]
Type inference not working: We can close this :laughing:
