### ISSUE TITLE
Optimization Guide Request

### ISSUE THREAD

**Issue by TheTFo** [facebook/flow#5694]
Hi all,

I'm using Flow with VSCode on Windows, and have noticed that it has gotten very slow in my application. Every I change I make seems to take 30 to 40 seconds to get feedback.

I have a feeling I'm using this correctly, and I'm wondering if there's a guide to optimize flow.

Thanks!

**Comment by mrkev** [comment]
Is this still an issue? What version of Flow and Windows is this with?
