### ISSUE TITLE
$Shape doesn't work

### ISSUE THREAD

**Issue by loyd** [facebook/flow#5702]
```js
type A = {a: string};

function test(fn: $Shape<A> => void): void { fn({}); }

function fn(a: A): void { a.a.slice(2) }

test(fn)   // no error 0_o
```

[Try it](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAhgFygDOKATgJYB2A5gL4DcykArowMYp6sRqBRYaACkiNKAEgDKAC1LYAPLgB8hLQDdY9ACYBKSnsMlQ0icVZH2oVl14ChIqxTwnQZgxdIA6AKpoej4sCQAmIwdkMUlpaJBQRlhQLFpaWFpQAAYAfVggA)

**Comment by idiostruct** [comment]
`$Shape<T>` does not error on missing properties: think of `$Shape<T>` and `T` as "overlapping" types. Consider using a sealed object type or `$Exact<T>`.

**Comment by loyd** [comment]
I interpret `$Shape<{a: string}>` as `{a?: string}`, where am I wrong?

**Comment by loyd** [comment]
```js
type A = {a: string};

function test(a: $Shape<A>) {
  a.a.repeat(2); // no error
}
```

Is it the expected behavior?

**Comment by TkDodo** [comment]
@jacekkolasa I'm afraid your workaround stopped working in version `0.106.0`. It is still working with `0.105.2`:

https://flow.org/try/#0C4TwDgpgBAglC8UDeBDAXFAzsATgSwDsBzAXwG4AoUSKAZTBwhQBNaALFGxJCqKAOkEASdpwgAeGAD4ANBRIUAZgFcCAY2B4A9gSjAI2ABTo6DJqw6QAlMl5QU-B40gpghgExWyUAPQ+oAMIoBARawFBqKAA2UVAABg5OEC7AcVAARhCRypjQDFqQOKDxzkypUHiYUAC2lZiERBW6qswQioQQzFAA2gCMALr88kA

**Comment by TkDodo** [comment]
It's also not working at all when using `strict` objects, which we are almost exclusively doing...

**Comment by TkDodo** [comment]
A lot of valuable discussion is going on in https://github.com/facebook/flow/issues/7566, and I think this solution is what will work in most cases: https://github.com/facebook/flow/issues/7566#issuecomment-526324094

Here is another example of `$Rest<T, {}` working as expected, even with `strict` objects:

https://flow.org/try/#0C4TwDgpgBAChBOBnA9gOygXigbwD4CgooBDAcwgC4pUBXAWwCMEAaQ64uyqRYeAS1SlWuAL758oSLGLxgfYgBsAPABUAfJigASAEoQeq5jhFr8AYzQ8oYGXMVwkaKjFvzlDlKg1ZsJclQAWACYoMXwbWTcPNAA6VA4IGPgISGJgAAoggEooAHpcqGAACz5EKAt4ZLNgBRBC8AgAWgR4ZCRxCLsFaNQYgDNkZDyCnj4FBWpkYBIzM31EPgYFCCMmM2IaRGgeqFKoCAAPYmqgA

There is even a good explanation in the docs:

https://flow.org/en/docs/types/utilities/#toc-rest

> For example, $Rest<{|n: number|}, {}> will result in {|n?: number|} because an in-exact empty object may have an n property

At least this is what we are going with at the moment.

**Comment by danielbartsch** [comment]
There's also a weird error when treating `$Rest<T, {}>` like `$Shape`: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQIYBOKAlvtADwAqAfKALygAkASlgM4rUA0oA3gF8aiUKFSYcAZVgBbLFQkN+AH1D4AXKE6ESAOwDmoZQOQBjWLs6gsAD3ymUm6XIXYlfNZoDkX0CcTmliigGESk5JoExGSUzvISdIweGqA+fmYWVliEhLCEkWExFHGuWInWdg5AA

```
... because string [1] is incompatible with undefined [1] ...
```
just looks plain wrong, as `[1]` is talking about the same property, yet one of them is `string`, the other is `undefined`

**Comment by jedwards1211** [comment]
@loyd you would hope `$Shape` is the same as making all the properties optional, but it isn't unfortunately.

```js
const b: $ReadOnly<{age?: number}> = { name: 'foo' }
const a: $ReadOnly<$Shape<{age: number}>> = { name: 'foo' } // Cannot assign object literal to `a` because property `age` is missing in object literal 
```

So what's the actual purpose of shape?  Who knows...

**Comment by STRML** [comment]
So we've created `$MaybeKeys<T> = $Rest<T, {}>`. What is `$Shape<T>` actually supposed to do?

**Comment by gkz** [comment]
Use `$Partial` instead https://flow.org/en/docs/types/utilities/#toc-partial

> This utility converts all of an object or interface’s named fields to be optional, while maintaining all the object’s other properties (e.g. exactness)
