### ISSUE TITLE
typeof type alias behaves differently from inline typeof type.

### ISSUE THREAD

**Issue by RichieAHB** [facebook/flow#5704]
As in the title, for some reasons the aliased type behaves differently to the type that is described inline when using `typeof`.

# Aliased
![picture 15](https://user-images.githubusercontent.com/1652187/35275289-29789f8e-0037-11e8-81cb-afea34113cc5.png)

# Inline
![picture 16](https://user-images.githubusercontent.com/1652187/35275290-298bb114-0037-11e8-8156-eb8e38654416.png)

This isn't just an error in flow-for-vscode, and is the same when running the flow bin.

**Comment by SamChou19815** [comment]
Not enough info to repro
