### ISSUE TITLE
How to check the specific type of (React.Element<A>|React.Element<B>)

### ISSUE THREAD

**Issue by fizker** [facebook/flow#5707]
How can I check the actual type of a component passed in to `render()` while making flow happy?

Basically, I want to make something like the HTML `<table>`, where the visual order of `<thead>`, `<tbody>` and `<tfoot>` are always all `<thead>` first, then all `<tbody>` and finally all `<tfoot>`, regardless of the order they were added to the DOM. Similarly, I might want something like `<tr>` being lumped into a `<tbody>` as a convenience method for the dev.

The problem is that at runtime, it seems like testing `<Type/>.type === Type` works just fine, but flow does not accept that we have made the type-check.

Following is an example that shows the basic idea I have of determining the type. It works fine at runtime for React 15 and 16, but it fails flow. Is it possible to write the code in such a way that it works everywhere?

```javascript
// @flow

import * as React from 'react'

class A extends React.Component<{ a: string }> { render() { return <div>A: {this.props.a}</div> } }

class B extends React.Component<{ b: string }> { render() { return <div>B: {this.props.b}</div> } }

class CA extends React.Component<{ children: React.Element<typeof A> }> {
    render() {
        const { children } = this.props
        return <div>{children.props.a}</div>
    }
}

class CB extends React.Component<{ children: React.Element<typeof B> }> {
    render() {
        const { children } = this.props
        return <div>{children.props.b}</div>
    }
}

class C extends React.Component<{ children: React.Element<typeof A>|React.Element<typeof B> }> {
    render() {
        const { children } = this.props
        if(children.type === A) {
          // The next line errors because flow thinks that `children` might be of type B
          return <CA>{children}</CA>
        }

        if(children.type === B) {
          // The next line errors because flow thinks that `children` might be of type A
          return <CB>{children}</CB>
        }
    }
}

<C><A a="bum" /></C>
```

[flow try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK3RnkBBUFQAeuKgDsAJuWp1cAOgDCzLBMm4APAG8SALlClc2FBIDmoAL4A+ULo7Sq2ABQBKO6A64ArtgmhNKRQAN2sBA21cAAsUUgUMJgw44ktNYCDQqysePlJyACFhMUkZSk5FFUxYdQktXQAjAyMTcytbexKnNw8vX39AkOt8iOjY+MS4+tT0wazLHP5QJSFRcWlZcuVVao0dUFoY6CkHAzl6BQBRaCo0XdwATwwqWEhQAVsbO0RQH89Ol3c2m+vxBtGqRg8BxQRwcWQAvKBRnEErAksCQT9en4AhlrNooTDJONUclprj0dl5oheIslIVViUNvItlUanV9odjpJTpsrjc7o9nq98h92hSHFIuoCKaDwfhdASuf5LKAEUjiWiMb8sf1cfjOQ4NZMyYMKfMqTS8ksimtSmcKts2XtFScysy+bdapoHk8Xm9rAAfe2Xa6erQ+oWgEVtL4giVS2Na-ZyyEGyTwxExZETGW-FCQZwuokR1VwhECaVJ7VUHzYzTLPFFiTTBu5n5Uqv5wtpiQKEtlhH5StVv61-p0xs9lsitvZEHm5D16yaITEOEAInq3jQ69AwGXwCU1iAA)

**Comment by apsavin** [comment]
Why not use `instanceof`? See [example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK3RnkBBUFQAeuKgDsAJuWp1cAOgDCzLBMm4APAG8SALlClc2FBIDmoAL4A+ULo7Sq2ABQBKO6A64ArtgmhNKRQAN2sBA21cAAsUUgUMJgw44ktNYCDQqysePlJyACFhMUkZSk5FFUxYdQktXQAjAyMTcytbexKnNw8vX39AkOt8iOjY+MS4+tT0wazLHP5QJSFRcWlZcuVVao0dUFoY6CkHAzl6BQBRaCo0XdwATwwqWEhQAVsbO0RQH89Ol3c2m+vxBtGqRg8BxQRwcWQAvKBRnEErAksCQT9en4AhlrNooTDJONUclprj0dl5oheIslIVViUNvItlUanV9odjpJTpsrjc7o9nq98h92hSHFIuoCKaDwfhdASuf5LKAEUjiWiMb8sf1cfjOQ4NZMyYMKfMqTS8ksimtSmcKts2XtFScysy+bdapoHk8Xm9rAAfe2Xa6erQ+oWgEVtL4giVS2Na-ZyyEGyTwxExZETGW-FCQZwu9OmIzECS0SMCaVJ7VUHzYzTLPFFiTTJu5n5Umv5wtp-wl3Blit+-LVmt-ev9OnNvttkUd7Ig83IRvWTRCYhwgBE9W8aC3oGAa+ASmsQA).

**Comment by fizker** [comment]
@apsavin Because that is not how jsx works. `<A />` does not return an instance of `A`, and `instanceof` will therefore always return false.

[See flow fail the check](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK3RnkBBUFQAeuKgDsAJuWp1cAOgDCzLBMm4APAG8SALlClc2FBIDmoAL4A+ULo7Sq2ABQBKO6A64ArtgmhNKRQAN2sBA21cAAsUUgUMJgw44ktNYCDQqyseWAkjEgBGPSEAXlB1eFABN1AQUFiSf1MjYglaKkapUHhYb2gunuwAa26UaPq83Fb22EhEWlz84gAmYtAyzSFiEoAiYh3a2zqGiVh8VomWtqoAGk7R6GgSaCA)


Or go to https://reactjs.org and paste the following into one of the live-try boxes so see it yourself. You need to add a whitespace after pasting, to trigger the live-code runner
```
class A extends React.Component {
  render() {
  
  }
}

alert(`new+instanceof: ${new A instanceof A}.
jsx+instanceof: ${<A/> instanceof A}.
new+type: ${(new A).type === A}.
jsx+type: ${<A/>.type === A}`)
```

**Comment by arielalvarez88** [comment]
Did you find a way ?

**Comment by aKnownGlitch** [comment]
Looking for same.  Any results?

**Comment by willcodes** [comment]
Also would like to know

**Comment by fizker** [comment]
I might have a solution. Currently, I'm using this function:
```js
// @flow

import * as React from 'react'

export default function filterComponentsByType<P, T:React.ComponentType<P>>(elements:React.ChildrenArray<?false|React.Element<*>>, type: T) : $ReadOnlyArray<React.Element<T>> {
	const asArray = React.Children.toArray(elements)
	const nullOrCorrectType = asArray.map(child => {
		if(!child) { return null }
		return child.type === type ? child : null
	})
	const filtered = nullOrCorrectType.filter(Boolean)
	return filtered
}
```

You give it `this.props.children` and a type, and it will return the children that match that type. It could easily be extended to also return the children that does not match the type.

[Try Flow proving the typing works](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vJUAeWeUABMqkYgFdoDcQDt6KWDNCQUUqtgDCzLDKozcpAEIBPACrGMVADwAFADShTALmp1cAOi2ZFe3Ocu2AHyBABRU0FRovqQunB4aABaqQhwyAILY2MTGVgD8YtCkVAA+rvTuAKIRUfpWBMEOuBZUTo4AlKCtACSuQgDyMtDGGVk5ZR5Vkb5WpsGgAN6IAJC0iqT4ZCPZoAC8lHGeSdApeu64sFvGYdXRbcurMuugMpLQfZo4HPT+VLskpJd3GhiBgQrQjkJdoEFsslihICEAITg5IdeagDi4cTYJQvaDQUAAX1hmOxShRxzOzV2Oz2TUsoFyoApkNaeOgy0JdxWawYqlw6iokL27PeWkyVG+zXcKjU2BChlgsAixBk3NJOOU-MFQkQxMQtGgZHIaVAfAFMiE5HGnm0Plq80J0MWS1SInlaJJVCxmqsQhQADdAqYkuQUORVaA0lZgP6g5y9YhILJ5IpQIYQhgmBgYo7Pa7vWTQH7A8HQ6BwyR0zG44FEwajaRyBozbwLVb9m5bd5dA7mRDUq0bYlkqlLnkCkVSgdJjVcFZ6VRYJAo4Fp13Z9NF8v03MnTCC5b1CF8zzHhsnD0aP1BsNMtkrDbN7Vtyu0nM9rKBR8e9ETD8QlwUN3CzWAc3cFlUgcNJuTPJ4ACNL16AYhnHJ8bhfZod0MD8tTlLwdD-MxmkA4DQPAyC9AcQw7i9H0lBLeMlmYqwEgARkCaNgHYutmKWeZiH1PjWI4wwYx42F+Pg4kWNjUsE31KwNDrUBi1NYAVOLQxQA0xBVKsdTNKsbTdPmdlQAAMgstSNOJeZJ1+KytNsxAY2UoA)

Code for [reactjs.org](https://reactjs.org) live box (still, you need to type anything after pasting to trigger the parser)
```js
function filterComponentsByType<P, T:React.ComponentType<P>>(elements:React.ChildrenArray<?false|React.Element<*>>, type: T) : $ReadOnlyArray<React.Element<T>> {
  const asArray = React.Children.toArray(elements)
  const nullOrCorrectType = asArray.map(child => {
    if(!child) { return null }
    return child.type === type ? child : null
  })
  const filtered = nullOrCorrectType.filter(Boolean)
  return filtered
}

class A extends React.Component<{}> {
  render() {
    return <div>This is an A</div>
  }
}
function B(props:{}) {
  return <div>This is a B</div>
}

class C extends React.Component<{ children: React.ChildrenArray<React.Element<typeof A>|React.Element<typeof B>> }> {
  render() {
    const a = filterComponentsByType(this.props.children, A)
    const b = filterComponentsByType(this.props.children, B)
    
    return <div>
      <h1>A</h1>
      {a}

      <h1>B</h1>
      {b}
    </div> 
  }
}

ReactDOM.render(<C>
  <A />
  <B />
{null && <A/>}
{false && <B/>}
  <A />
  <B />
</C>, mountNode)
```

**Comment by stepankuzmin** [comment]
Still trying to achieve this, but no luck so far.

```jsx
/* @flow */
import React from 'react';
import type { Element } from 'react';


class A extends React.Component<{ a: string }> {}
class B extends React.Component<{ b: string }> {}

type AB = Element<typeof A> | Element<typeof B>;

const getAorB = (component: AB): string => {
  if (component.type === A) {
    return component.props.a;
  }
  
  if (component.type === B) {
    return component.props.b;
  }
  
  return "";
}
```

```
13:     return component.props.a;
                               ^ Cannot get `component.props.a` because property `a` is missing in object type [1].
References:
7: class B extends React.Component<{ b: string }> {}
                                   ^ [1]
17:     return component.props.b;
                               ^ Cannot get `component.props.b` because property `b` is missing in object type [1].
References:
6: class A extends React.Component<{ a: string }> {}
                                   ^ [1]
```

[try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcGO+RBAntlJgA3mACiMUplIA7IgF8wtekxZUCHVFsoxyAZz1gAgmFIAPArIAmhsuoB0AYXq4ZsggB5R5AFxg9BHjoMgDmYPIAfCLyqDr6hgBCphbWtqwETi5wbnJeYABGfgFBoeFRwjGo-ILGSQC84pLSudWkcFDGUQA+jVLuHq3tYAkRnLHZAWAhpARG+PVgABSUWTkEfkYJAJRFgcFhdeWoYGDoHcur7vatYHV3xlsixydgLAQArngyYCvca-bYOjYPT2cicE4xE7PM5LX6uK43O4NbZPF6vGafb5w7JXQFwYH2fLg8LPZ5vTFgABElM48iAA)

**Comment by danielo515** [comment]
I think I have a very similar case, but I am using cloneElement, whic gives me a rather cryptic error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ ../spring/src/components/DescriptionText/DescriptionText.js:162:11

Cannot call cloneElement because property variant is missing in call of cloneElement [1] but exists in props [2].

        159│           title
        160│         ) : (
        161│           // So if it is not string it must be one of the compatible Text types, therefore not wrap it
 [1][2] 162│           cloneElement(title, { variant: selectedVariant.title.variant })
```
And here it is nicely colored:
![image](https://user-images.githubusercontent.com/2270425/107766494-d3da7080-6d33-11eb-8b86-4b7259a0b086.png)

**Comment by danielo515** [comment]
I ended creating an assert function that returns the proper type with a couple of checkings and throws here and there

**Comment by SamChou19815** [comment]
You might be possibly to hack it, but we really don't recommend it since it's inspecting jsx internals, while we might make opaque in the future.
