### ISSUE TITLE
Doesn't catch errors for React.ComponentType<$Subtype<Props>>

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#5708]
[Try flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK4CeGVUADUUVeAAUmGcgF5QAb0ShQtaGVJVSALlClc2FADsA5gBpEAXx79BIsaDnU6uAHQBhZlkNVDuACo2ADwAJADKAK4ARnwCgXYSUqQAfElKoIgxggBisLCSsNIOCmmq6po6huFokVTY5lbKiLSwhnqgObA68UUAFBiJOh350gCUDkmggQAmKABuoMCpQA)
```js
// @flow

import * as React from 'react'

type ViewProps = {
  classes: string,
}

type View = React.ComponentType<$Subtype<ViewProps>>
  
type FooProps = {
  classes: number,
}
  
const Foo: View = (props: FooProps) => <div />
```
```
No errors!
```

Valid errors do show up if you use `React.ComponentType<ViewProps>` or try to assign `FooProps` directly to `ViewProps`.

Without being able to use `$Subtype`, I have to awkwardly use intersections to allow additional props on the component instance:
```js
// @flow

import * as React from 'react'

type ViewProps = {
  classes: string,
}

type View<T> = React.ComponentType<ViewProps & T>
  
type FooProps = {
  classes: string,
  value: number,
}
  
const Foo: View<{value: number}> = (props: FooProps) => <div />
```

**Comment by kuzmenko1256** [comment]
[Try it ](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UBIASwBMAuMAOwFcBbAIwFMAnAblQF90WPAQBCYDgA8ALhwbUCxMgPRQmDDNMpwGYLuoAUlBrmnYNHegBIAykzbSAngAcOAHkIA+AJSkKx03MMDgA6GjAAXjAAcllTaL5BVH0GAwYOJEJvZMN0pFFsoA)

**Comment by TrySound** [comment]
Subtype is deprecated utility type
