### ISSUE TITLE
v0.64.0 does not include an OSX build

### ISSUE THREAD

**Issue by ajablonski** [facebook/flow#5709]
Apologies if this is covered somewhere else or no longer relevant. It seems like the 0.64.0 release of Flow doesn't contain an OSX build (https://github.com/facebook/flow/releases/download/v0.64.0/flow-osx-v0.64.0.zip returns a 404).

**Comment by GAntoine** [comment]
Seems the [travis build](https://travis-ci.org/facebook/flow/builds/332267188) is stuck, it's been running for > 24 hours at this point.

**Comment by KenanY** [comment]
The build is now available.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
