### ISSUE TITLE
Flow seems to ignore null check on ref when calling function on them

### ISSUE THREAD

**Issue by yadomi** [facebook/flow#5710]
I'm using reference of a DOM element with React, but I can't find a way to avoid flow telling me that  the ref could be null even if i've explicitly checked right above.

Example here: http://bit.ly/2n6z8jB

This seem to only happen when calling a function on the ref:

```jsx
[...]
componentDidMount() {
  if (!this.refVideo) return;
  this.refVideo.src = 'http://example.fr/video.mp3';
  this.refVideo.load();
  this.refVideo.play(); // This does not work, refVideo may be null ?
}
```

However doing this work:

```jsx
componentDidMount() {
  if (!this.refVideo) return;
  this.refVideo.src = 'http://example.fr/video.mp3';
  this.refVideo.load();
  this.refVideo && this.refVideo.play(); // This work, but why don't I've to do the same of the line above ?
}
```

**Comment by Tarektouati** [comment]
I'm having the same problem with Flow.
I'm checking my variable if it could be string or null and it returns an **Error** that the type is incompatible with the expected param type.
```
export const getAuthenticatedUser = () => {
  const user: ?string = localStorage.getItem('user');
  return isNil(user) ? null : JSON.parse(user); // [flow] null or undefined (This type is incompatible with the expected param type of string)
};
```

thx

**Comment by AugustinLF** [comment]
@yadomi Your problem is due to [refinement invalidation](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations), that is that flow considers `this.refVideo.load();` might make your call check invalid :/

@Tarektouati This seems to be another problem, it's that flow doesn't know that `isNil` refines user to a string. Doing a manual checks work `return typeof user !== 'string' ? null : JSON.parse(user);`.

**Comment by yadomi** [comment]
@AugustinLF thanks ! You seem to be right because when I do this (as the doc says), I don't have any errors. 

```jsx
[...]
componentDidMount() {
    if (!this.refVideo) return;
    const video = this.refVideo;

    video.src = 'http://example.fr/video.mp3';
    video.load();
    video.play(); // This does not work, refVideo may be null ?
}
```

This seems much like a hack to me than a real solution. 
Is this the right way to do it or should I explicitly check `this.refVideo` on every function call ? 

Thanks :)

**Comment by AugustinLF** [comment]
Using a [helper function](https://flow.org/try/#0C4TwDgpgBAaglgEwgeygXigbwM4CcDGAXFNsLnAHYDmANFADbICGCxAYgK4X7BzIV0w9JiHZcefCgF8AUDPzDs2EsA4AzNVhkBIXBDXwkyYgH5DKObq7nkACgBuiFMRsBKLdu2OjAOjz50KAByAAtgYDBCAHooiAAPJgBbIQgfNVwo7xQfZIBmIIBuGSgSqC8nZB9GFltXItKyrMqhEVqi7VltfGRk-ggKYAARRABZZC5gWq0G7ThNWwBCYBC4bB89Awr3PVVcCnbtZdX16wrbI7WNt3bZKSA) is probably the way that looks the nicest. But I don't think you can do much cleaner than that :/

```javascript
type Video = {src: string, load: Function, play: Function}

class stuff extends React.Component {
    refVideo: ?Video

    runVideo(video: Video) {
        video.src = 'http://example.fr/video.mp3';
        video.load();
        video.play();
    }
    componentDidMount() {
        if (!this.refVideo) return;
        this.runVideo(this.refVideo);
    }
}
```

**Comment by yadomi** [comment]
@AugustinLF Thank for your help, that make sense
