### ISSUE TITLE
By-shape object type refinement

### ISSUE THREAD

**Issue by wips** [facebook/flow#5713]
Hi guys,

I'm struggling with types refinement `v0.64.0`.

```js
type TError = {
  statusCode: 404,
  entityType: string
}
type TResult = {
  id: 200,
  data: Array<*>
}

function foo(res: TResult | TError) {
  if (res.id === 200 && Array.isArray(res.data)
  ) {
    return writer(res);
  }
  errHandler(res);
}

function writer(line: TResult) {}
function errHandler(err: TError) {}
```
I get the following error:
```
16:     return writer(res);
                      ^ TError. This type is incompatible with the expected param type of
21: function writer(line: TResult) {}
                          ^ TResult
Property `data` is incompatible:
21: function writer(line: TResult) {}
                          ^ property `data`. Property not found in
16:     return writer(res);
                      ^ TError
```

Could you advice whether it is a bug or should I refine types in a different way?

[try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAogE6lylgC8YA3qmGAM4YCGGArswMJwAmeAFxgALAAZRAGkZg8AOwwBLbIVzCWGUkvkBzVAF9M6ogCU8zTjAw16spfxEAmceJlN+HNiICC5NlgAPCAAfIboUJzyAMbKcPJgUHBwABSkFiKE5pbWYAA+RGQUpACUdkxKUGBpFgB0DjTUtC7iYLJMTABknWB+pAH1zH0BNcy1nuwlsmUMHWDpXKQJCNoYeKSjJQDcskZM66QAEmzy-DDrmztGqJExccurFzA6GlkWVhgzRrexSvFy5GOp3OGwOmSKlC+qCAA)

**Comment by apsavin** [comment]
The most simple way is to always use the `statusCode` property like [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAogE6lylgC8YA3qmGAM4YCGGArswMJwAmeAFxgALAAZRAGkZg8AOwwBLbIVzCWGUkvkBzVAF9M6ogCU8zTjAw16s1h259BIgEzjxMpvw5sRAQXI2LAAeEAA+Q3QoTnkAY2U4eTAoODgAClILEUJzS2swAB8iMgpSAEo7JiUoMEyLADoHLl4BAmoOsHdxSoYmJiyuUmSEbQw8UnrmcoBuWSMmCdIACTZ5fhgJqdmo1Bj4xJGxrZgdDVyLKwxeo32EpSS5clX1zcmlnNLKG9QgA).

See [docs](https://flow.org/en/docs/types/unions/#toc-disjoint-unions).

**Comment by wips** [comment]
@apsavin, thanks for the help. I don't have `statusCode` field in both types and I don't want to introduce it just for the sake of Flow. I'll try to use exact object types.

But in general it is still unclear why can't I just use a value as an exact type after all refinements for this type are checked? I.e.:
```js
type TError = {
  statusCode: 404,
  entityType: string
}
type TResult = {
  id: 200,
  data: Array<*>
}

function foo(res: TResult | TError) {
  if (res.id === 200 && Array.isArray(res.data)
  ) {
    return writer((res: TResult)); // at this point I'm completely sure that res fulfills 
                                   // TResult requirements, so why can't I use it as 
                                   // a TResult exactly?
  }
  errHandler(res);
}

function writer(line: TResult) {}
function errHandler(err: TError) {}
```

**Comment by apsavin** [comment]
>  return writer((res: TResult)); // at this point I'm completely sure that res fulfills 
                                   // TResult requirements, so why can't I use it as 
                                   // a TResult exactly?

Because nothing prevents error to be something like this:

```js
const wrongRes = { id: 200, data: [], statusCode: 404, entityType: 'bar' }
```

**Comment by wips** [comment]
Yes, it can satisfy both types, but by typing exact type hint like `(res: TResult)` I'm saying that I explicitly want to handle it as a `TResult`, even if it satisfies `TError` too. And what I want is safe - the variable has all attributes to be handled as a `TResult`.

Don't get me wrong, I'm not insisting that it is still a bug, but I want to understand reasons behind this behavior. Usually Flow behaves very intelligently, but sometimes I don't get it and it makes very hard to adopt it and popularize among people around me.

**Comment by SamChou19815** [comment]
Disjoint unions require a common shared field, and function calls can invalidate refinements.
