### ISSUE TITLE
Casting a Class<T> as another object with optional properties makes all properties mandatory

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/flow#5714]
I'm trying to replace some code that relied on static members in an interface, so I figured I could cast Class<T> to SomethingElse<T> and be done with it... turns out, Flow wants all properties, optional or not, in Class<T>'s statics.  [Here's the minimal case](https://flow.org/try/#0C4TwDgpgBAQg9gDygXigbwFBW1AtgQwDsATfYOAJxAC4oBnYCgS0IHMBuDASDjGCbiF8AGwD8tBszacAvhgwBjYfjp0oAMThx03BmSYK8RUuSoTGLDhjmLBDKADNqACgDCy1QB5NcAHxQAMlhEAEoUDS12IA):

```
type Box = {
    mandatory: string;
	optional?: string;
}

class Foo {
	static mandatory: string;
}

const f:(Class<Foo> & Box) = Foo;
```

**Comment by EdwardDrapkin** [comment]
This looks like a regression introduced in v0.56.0.

**Comment by SamChou19815** [comment]
Making Box an interface will work. This is intentional
