### ISSUE TITLE
Flow does not infer closure parameter even when annotation is provided

### ISSUE THREAD

**Issue by jpolo** [facebook/flow#5719]
When passed as parameter of a function, a closure is not inferred correctly although every annotations are done statically : 

[Update] Fixed URL, cf @blj comment

https://flow.org/try/#0PTAEEkDtQWwT1AGwJYCNQHsBmoDOBTRfAYwBcMAnAOgCtcAofADwAdLTRS4X9QBlQiXIUAKt3wAePqQCGpfABpQAJXykArhUgA+UAF5QACmlzee3ao1aAlKABkoAN71QeQWQBc-WfP0W1mpAK9AC+ANz0jKzsoMQYkLgcAkRklPpGhrbmTi6gwABU+bmg+aAA2si4yUJpACb4uMQUyCykyPEAusVFriXAuVjqkGTt0JXVqRSGGF4wyEz4tdZeqBgYRDLQAKTEABYkANa4Ob2gFAFanOLYmPp6BgDkg8Nt8Q-2Dlw8NxhUBCkce6PZ4jN4RVwhSKuAo9VylADC51MoBkbgBaSwFAwMFAINekG63VAAAEWDIKDIcbjQABaTj7XFDUHQUi7OScGQHXioxLImTHMkUmBqfAUInE85WBKgSD4ADuaJqYt6+X6rjxo0wWCkPkUKm0hmKuK8xl1fhUtgAPvx3MIxDwdaYlMptLlljb0aJxI75M7dM5TnEEhx-kIAGLQAzkMNM-GGLDWcG9IOJRWTdKGXnyLwmeRZXShsgRzO6xNGwvCP629IViNJ1ySwJp4RJyG5GFEkQUBDkWLxABuoo4gspIoonAwKOblEJKpJI6pODprN4Gvi9PZsi5U6z3IF5NH8mVcJJja0x1lCorM5VasZL01mOxPr1LsNpywJtzZgsVo9SvtSRvz9N0c1tShAJfP0Tl6M8xiqcCpgTUAAH4jE-FFIDgWwvGweMywhKE8kKIlEXwPkZXladxyacjhFAOVkFZUAFwYFVxQXdVaXpVdY01Vl2Tgyir0QtiTwlC5pUvajujvNdoFYiQAAUDxgXAlGA-V316DCVKFY5sm-c1lFA-9JjIuQIO9PTKXU7wnX1GCG0koxWK8Gy1PzXEsRgeNDFY6wCNANtoRIud4QHIcJzwZAYBYIh72ZWc4Tkvj12jNLICgrSjQw01kWyZQ-wmO1vU0l1TKMwqnLOFyvnwG4sCrAE7mBTL3jQpqK1ALwsFbIihIAeVQGghCoTF8HwAAvfBDADHSfOCU5xkQpbemwNbXFYzaJxjB94jWkIyyOzJ63oEAIGgeBatqdQmFgDBbqIWgxNOKI2AoDh6tAABZR71CIKqYOQSB6iYAAhOBwFqLx5tcMpEmaSAAHMOi8SB1BgVBRVyEJgkhU5XHemIUw4P6nvwErKAMmCsBB2pIehsDPSoVjtNcQxkBhvBSCR5GvJLUwvHJgHKdLLwUIxrHRT8I1XF3Kh6eYRnagqWoulcaw1riIZSGZpUqDwwXs1+-7AfFmVMex8dsmG0ayCoLk4FwY38EV0HlahpYqCIFHWWsUIiNOIA

In this example, neither Selector.of() or Selector.params() does not understand that I annotated correctly the passed closure.

**Comment by blj** [comment]
I think you have wrong example link.

**Comment by SamChou19815** [comment]
This now seems to work?
