### ISSUE TITLE
Higher order components with callbacks are variant in the wrong direction

### ISSUE THREAD

**Issue by aaronjensen** [facebook/flow#5720]
Perhaps there is a better way to type this, but this is coming from a bug in the react-router-dom types.

**edit**: there is a [better way to type this](https://github.com/facebook/flow/issues/5720#issuecomment-360593487), though I'm still not sure if the below is a bug. It certainly cost us quite a bit of time.

```js
/* @flow */
import * as React from 'react'

type HocProps = {|
  bar: number,
|}

type Props = {
  bar: number,
  callback: string => void,
}

class MyComponent extends React.Component<Props> {
  render() { return null }
}

declare function hoc1<P>(React.ComponentType<{| ...HocProps, ...P |}>):
                        React.ComponentType<P>

const MyComponent1 = hoc1(MyComponent)                       

// This should typecheck, but does not
;<MyComponent1 callback={() => {}} />
// If I specify the type of the callback, it's fine
;<MyComponent1 callback={(a: string) => {}} />

// Using the Exact<T> hack from 
// https://github.com/facebook/flow/issues/2630#issuecomment-344795952
// Allows this to typecheck, however...
type Exact<T> = T
declare function hoc2<P>(React.ComponentType<{| ...HocProps, ...P |}>):
                        React.ComponentType<Exact<P>>
                         
const MyComponent2 = hoc2(MyComponent);                        
;<MyComponent2 callback={() => {}} />
// We lose actual type checking
;<MyComponent2 />
;<MyComponent2 callback={(z: number) => 3} />
```

[flow.org try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbqqBAntmpgAEnDoAFZtgoBeMAG8APqjBgARiTwAuMADsArpnXU8AGlRKAvrwFCwUuDLDyFqjVt2Hjpi2rokMDCadADWumQEeOh6AOYuAHxgAG5w6AAmFjaodDDkFACy-ADCLLh61HpE1AAeBJXpFDT0BAB0pThwFVUAPI4ySW5qnHrppgAUAJSKYJwEBnh6+gZBYDbZY7lawlAGegzoXWAAFuIAjH0J480M7WVdlQQAKoLUPcpgrV9iktJkZp8vhIwNYEpNtO41FDoTDYWobm0OuVHi8hJdeHQupEwEUkQ8qmcXCdzuNcfdugRpnDqXDeMBgGAnsd0BQyKcVukwHZqHRjjzQgD1AYiOk4NQKHo4ARUABuHpkzoUwkBIIhUKyBRTRKKKxWMDABKoelgACSUFNYDIQjo6Cg-C5fK5rzAcHNBEdKuC9AFYHQBDYFCgMWosvlJXJj2VgS9YQ14xIESiMVi01kg11+sNRoZAFUyMmHcIAKI1Fo9J5JY7esBMFhgbMnAgEGTaemxP3HAzqVqYzDAKD0ajqOBwUL9+AIYAssgGcXAABMADYAMwABgAxNPZ73MI8ALTLgAsh4A7ABOACsl-nDYAgkFEBR3SyuXAnda+WEAacENRkqYvlaPhnRLMsKyJJ5UE2PJOBrPYDiOU46HnS5ri4REIyqVE3g+QCfn6f5AVaYFQXBSEaQo+F0LuRUUVeHpQIYS5DUo1i1ByLEiAVZEqnnIkkPnUlw1oqpJhlNjKNDbj8QIPjPTVONU3TPUDQbAB1YR4DIYQWgMQJ32EXl+WTKThJ42TM1MvEKTk6MFM1AAvLwjBMPAlLAZcVKzY0mRfF93WEUU6CMR5qE5EhsGwZh6GOUhRjAUVxTABB8FCMAorgKCeRgnZ4IIQ4liQ5dUIRGjzOwy4yIkijSusui0QAEgAEVtKA+gBfC-gSFjqppDi9GxaSKWXfjxGXIS6tE8TetpOUhseEb5O9RTtQUDNVONOazJkkaNoZLbJoIRa7OWxznJ8NztU8yygA)

**Comment by aaronjensen** [comment]
FWIW, this is the [documented](https://flow.org/en/docs/react/hoc/) way, and it appears to work as it should:

```js
declare function hoc3<P>(React.ComponentType<P>):
                        React.ComponentType<$Diff<P, HocProps>>
                         
const MyComponent3 = hoc3(MyComponent);                        
;<MyComponent3 callback={() => {}} />
// ;<MyComponent3 />
// ;<MyComponent3 callback={(z: number) => 3} />
```

**Comment by SamChou19815** [comment]
This now works
