### ISSUE TITLE
Union type refinement using a map

### ISSUE THREAD

**Issue by geraintwhite** [facebook/flow#5726]
Flow throws an error when trying to do type refinement using a map instead of if statements or a switch statement. This seems like something flow should be able to do?

```ts
type FooType = {|
  type: 'foo',
  x: boolean
|};

type BarType = {|
  type: 'bar',
  z: boolean
|};

type FooBarType = FooType | BarType;

function test(obj: FooBarType) {

  // This is invalid
  
  const f = {
    foo: (obj: FooType) => obj.x,
    bar: (obj: BarType) => obj.z
  }[obj.type];
  
  console.log(f(obj));
  
  // Equivalent to the following which is valid
  
  if (obj.type === 'foo') {
    console.log(obj.x);
  } else
  if (obj.type === 'bar') {
    console.log(obj.z);
  }
  
  // Or a switch statement
  
  switch(obj.type) {
    case 'foo':
      console.log(obj.x);
      break;
    case 'bar':
      console.log(obj.z);
      break;
  }
  
}
```

https://flow.org/try/#0C4TwDgpgBAYg9nAKuaBeKBvAPgKClUSALigHIAzBUgGjygA8SAjBAGwgEMA7HLAXwDcOHIWgAhDgCdkkKOmx1RJUkyk06AL2ZtOPfkJEpYCCdKPp4SI1iimZEA+QCuXAMbAAlnC4EIAZ2AACjgmACsSSzsUAEpMYXwAegSoRAALDz8oDKyuADcOVg8AEzo6V28AqHI5OPx8SjgSYLCIhHtY1AA+KBDQgDp6WjqoVUkm3pIoyA7u3r6NOj4AbTnRAF0hfDKKuHY+1jgAc0DyZtDo6M2oOiSoAFEARycPfPYuYAI4AlToSlYDgDuHi4hygAPSrlSWUyr2KpXwHmqZz6ojkqHQFCosQwdHw5S4fl2EH2R2R9EuiygEFYfggdERUGRqPRGNGpGxuKg+MJewOxzmGgp+D48KgtwA8pIoBwoH4gcBIbLgBxgBAALYQd6iuUeBWpJkxWp1VwcWlkBqkIicvE7Xmkubkq7DJiSTgAaydXNN0BUaitwxtBKJJP5YXmQoDLvdVxFWz4QA

**Comment by grit96** [comment]
Related to #5330

**Comment by SamChou19815** [comment]
This is not equivalent. In the not working example you get a union type of functions, which shouldn't type check
