### ISSUE TITLE
Cannot instantiate a class with parameterized generic types

### ISSUE THREAD

**Issue by jessicaxp** [facebook/flow#5727]
Apologies for the title - had a hard time thinking of a better one for this case!

The issue is that I need a generic class with some Type T that internally instantiates another class with the same generic type. The outer class needs to be able to call methods on the internal class and trust that they'll agree on the generic type for parameters and return types. In my real-world case, the internal class is split from the external class so it can be mocked with a different implementation between tests and production.

In Java this is accomplished by declaring the generic type when calling the class constructor, but I don't see a way to accomplish anything similar in Flow.

[Minimal example with errors on https://flow.org/try/](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AWQE8B5AFwAsBTAJwGFs8AeAVQD4wBvVASADcsMAK5UAXGBYBuXjipkwAXjAAKHHAC2VEgCMAVuJYBKcXzgBLACaKO3HmDCUzOAHQDhVRWDWadu6TwBfVHt7AHM5T2VjCWsuYJD7GjkhGgA7BwonV0ERaQSgnnCyAAUaDScPJSjxUvLZVg4FG15E5LSwWvUK5yS1GD4qZUcXNxFDPJCgoIxGfGIGXBwmABVm+zNU1NpxYnJqelmVtgn0OFScMhohdDI4Gii4hOHnDa2aTy2kXcpaBbwo-zAYBgABSWAEAFonBQwAg4EIYFZtB5vHJMqlQmAYGYANZieI8IEZLKvWgfKhfUg-A6LI4A+LTeyyeRVUZiMDLaKmSyxbhPTIuUk0ZzM5Rs8YM+LxIqRaLLXnxVpkFLpZ5C5xFen2IJhOSdCqymplLr1VYKhJJZXtNWbWgavXGipasBTIA)

**Comment by jessicaxp** [comment]
@zgotsch Thank you! I'll give that a try

**Comment by SamChou19815** [comment]
This now works
