### ISSUE TITLE
Spread operator doesn't work for arrays

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#573]
This code doesn't typecheck

    var a: Array<number> = [1, 2, 3]
    var b: Array<number> = [...a];

This is how it works [with babel](https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=false&code=var%20a%20%3D%20%5B1%2C%202%2C%203%5D%0Avar%20b%20%3D%20%5B...a%5D%3B%0A%0Aconsole.log(b)).

Flow just returns

> ...: rest array of spread operand
> This type is incompatible with
> ....: number

(Spread operator is marked here #560 as done, so I am adding it as a separate issue)

**Comment by runn1ng** [comment]
This idiom is kinda useless in the simple case, but it is useful in "array-like" objects.

    var collection: HTMLCollection = window.document.getElementsByClassName("my-class");
    var elements: Array<Elements> = [...collection]
    elements.filter( /*....something...*/ ).map //...... etc

With [Babel REPL](https://babeljs.io/repl/#?experimental=true&evaluate=false&loose=false&spec=false&code=var%20collection%20%3D%20window.document.getElementsByClassName(%22form-group%22)%3B%0Avar%20elements%20%3D%20%5B...collection%5D).

(Note that this requires [Babel polyfill](https://babeljs.io/docs/usage/polyfill/) in chrome, [because of the use of Array.from](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/from#Browser_compatibility).)

**Comment by samwgoldman** [comment]
Very easy to repro. Seems like a bug to me. Thanks for the report!

**Comment by runn1ng** [comment]
No problem! I report the bugs as I encounter them in real code :D

**Comment by mdausmann** [comment]
related?
```javascript
class Person{
  name: string;
  constructor(name){
    this.name = name
  }
}

var map: Map<string, Person> = new Map([
    ['bob', new Person('bob')],
    ['tim',  new Person('tim')],
]);

var count = [...map.values()].filter(p => (p.name=='bob')).length
```

/Users/michael/Tutorials/node/clickforce_es6/src/Test.js
  line 14  col 13  call of method filter - Error:
  line 14  col 44  property name - Property cannot be accessed on
  line 14  col 17  rest array of spread operand
  line 14  col 17  call of method values - Error:
  line 14  col 17  Iterator - This type is incompatible with
  line 14  col 17  spread operand

**Comment by kkirby** [comment]
@mdausmann I would guess so.

I just found this bug myself when trying to use it in favor of splice, e.g.: `['abc',...arr]`. For others, a workaround would be `Array.from` as that's what's happening in Babel when you do `[...arrayLike]`.

**Comment by jaredly** [comment]
still a bug!

**Comment by runn1ng** [comment]
It works on my copy (at least the current github version)

**Comment by gabelevi** [comment]
Right, this should be fixed in 0.17.0. https://github.com/facebook/flow/commit/89b5aa68e8c9449aefdcb8c5b2a370a8cb080527 was the commit that fixed this.

**Comment by wldcordeiro** [comment]
I can open another issue for this, if you'd like. But from reading into Spread it should work on iterables, so in that case it should work for a `Set` which is currently an error as of 0.22.0.

**Comment by samwgoldman** [comment]
@wldcordeiro there is already an open issue for that—on mobile so I can't find it now.

**Comment by glortho** [comment]
Progress is being made here: https://github.com/facebook/flow/pull/1668
