### ISSUE TITLE
Return type polymorphism uniquely determined by input type

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#5730]
Is there a way to specify that a function returns type A given inputs B, and returns type C given inputs D?

Kind of like this:

```js
// doSomething() -> number
// doSomething(100) -> boolean
function doSomething (int?: number): number|boolean {
  if (int === undefined) {
    return 1;
  } else {
    return true;
  }
}

let num = doSomething();
console.log(Math.floor(num));
```

This results in an error where `num` is claimed to be a boolean. https://flow.org/try/#0GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmiAFIVAPwBciYImARtgE4CUt9TrAPo3HAA22AIZIA3gChEiGMDIVEAXhWJwybMELZkbRFJkyWuECyQBGANzTEAX0TZBAZ2z6bRk2cRQWIbNZlbSSDJYSg6BmUUdCxcAmJSNmsIBCchbAA6QTgiUgBZEXwM4Gy4FlIuNiSgA

In Haskell, there's multiparameter typeclasses and return type polymorphism combined with functional dependencies that deal with this. (https://stackoverflow.com/questions/20040224/functional-dependencies-in-haskell)

**Comment by SamChou19815** [comment]
You can use conditional type, although it will be difficult to satisfy the conditional type
