### ISSUE TITLE
How to type merging new values into object with spread for unions?

### ISSUE THREAD

**Issue by edele** [facebook/flow#5731]
Flow `Could not decide which case to select` for example below. I assume it guards me from spreading together different types of union. I added a check to only spread if types are the same, but flow seems not to infer this.

Could it be considered safe to spread unknown cases of union if they are guaranteed to be the same as in the example?

```js
/* @flow */

const editStudent = (student: Student, newFields: Student): Student => {
    if (student.grade === newFields.grade) {
        // Cases are guaranteed to be same here
        // so it’s safe to spread?
        return { ...student, ...newFields };
    }

    return student;
};

type Student =
    | {
          grade: 1,
          name: string
      }
    | {
          grade: 2,
          name: string,
          hasLibraryAccess: boolean
      };
```
[Same at https://flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAFMATAS3wGV8BXEo7QgXjAAoC6H8AuMazxgBow2IggBiZIjBK5e-eowCU82ouYA+MAG9UYfWDJQ2HdQDoA5gCcAhvTBNHIsZOmzLt+kp16Df4MBgAMI2uES4YDZWRGAWNFE2jESkYPhwYABGMbg2ALYxABZE0b5++gFguOkUgJgEETlQMWmVAA7RdgD8pWXRtFbYOmBmw6ZcwsNmohJSMhEAvgDc3XPofr00-ZVqXEuL6PgAni0xClwO3QA+PmVl1nZEvACMgt032HkPW1Zk2BavYCs-FddDc-Hd6LwAEwvUEGd75XgEb6-GGwsAFUIAGTIGVsVgOAEEMBhwnJMnA4DAiIl-nsgA)

EDIT:
Just thought that in the example I can just return newFields. But real use case is more complicated: newFields is a diff, so spread is used to leave fields missing from diff as is.

But I can’t think of a way to annotate diff. Can I create a type with all fields of another type but they are optional?

**Comment by idiostruct** [comment]
Student could be made into an object type with optional fields:

```typescript
type Student = {
  grade: number,
  name: string,
  hasLibraryAccess?: boolean
};
```

**Comment by akre54** [comment]
Yeah I have [a similar failing case](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCWAJgFxgDOGATjQHYDmqAvumz4wAIVIUqtRi3ZduAbQC6-QbgIApOFzx1xxAD6j0UAK6cAxhhpxOYKAAoAhm24BKJpu27K1NngwmbLY+1GAAdBH2hGxsjlhhNMzRsVhOLq5gAPwU9EzO3GEAto44TqQAfGCOCXSufGBM5LlVLnyukgICQA). Unfortunately I can't just add maybes to the base type because the cases are unique.
