### ISSUE TITLE
Object types that are exported as opaque

### ISSUE THREAD

**Issue by CMCDragonkai** [facebook/flow#5733]
In a JS file, when defining an opaque object type:

```
opaque BitMap = BitSet;
// ... functions that work on BitMap
export type { BitMap };
```

When importing this type into another file, it is unknown whether this `BitMap` type is an `Object`.

That means I wasn't able to do `type SnapShot = WeakSet<BitMap>`.

I understand why this is so. But what's the solution to this? It appears you just cannot use opaque types when you expect to pass them into other generic types outside of the file you defined them in.

**Comment by nmote** [comment]
You can provide bounds to opaque types. Check out [this example](https://flow.org/try/#0CYUwxgNghgTiAEB7ADlAjgVwQFwJ7IQCEBLbAWSmQC54BvAXwG4AoZvA+AZQDtLOALRNngBeeAHUQUANacQ2ADwlylAHwtmoSLAQA3WPAAeNHn0HYWhgHRRgwRkA).
