### ISSUE TITLE
Specifying generic type on a class created by a function?

### ISSUE THREAD

**Issue by davidliu** [facebook/flow#5740]
I've got the following function that wraps a React Component and spits out a new class:

    const RecyclerViewDataWrap = <P>(Wrapee: Class<React$Component<P, *>>) => {
      return class {
        props: P

        constructor(props: P){
          this.props = props
        }
        render(){
          return (
            <Wrapee {... this.props}  />
          )
        }
      }
    }

    export default RecyclerViewDataWrap

    // in some other component file:
    export const SomeComponentData = RecyclerViewDataWrap(SomeComponent)

This allows me to create `SomeComponentData` objects that will render SomeComponents with the props I tell it to. However, I'd like to be able to declare the generic type along with it so that the constructor can know what types it wants. Right now, if I do use this new class, I get the following error:

`This type is incompatible with the expected param type of **empty**`

Ideally I'd like to do something like this to specify the type of P:

    type Props = {
      title?: string,
      price?: number,
    }
    export const SomeComponentData = RecyclerViewDataWrap<Props>(SomeComponent)

But this is a syntax error. Any tips?

**Comment by SamChou19815** [comment]
This is supported
