### ISSUE TITLE
Array of subtypes raise an (unexpected) error

### ISSUE THREAD

**Issue by cglacet** [facebook/flow#5742]
I feel like [this error](https://flow.org/try/#0PQKhAIAEDMBsHsDu4TAFAHICuBnApuDgC4BOAlgMZEYDcaaww4A8gHYHwnhGLzgAmZALZC8rHGXisAhrHAV4nQTKJ4cALjREAngAcCbPABFwAXnABvcAA91rLEIBGeEgF86O-eAAqvE+atbeycXABpwbTsHZzc6BiYAZTwiIjJWAHNwLF1waXAAJiMAWgA3PCpOdXA0BXEieUUSfgBBdV94f0tbAEZQyPz3GqliBqUAITa-My71fL71ABZB2pH2owA1cqJK5pISaW0AHjWAPmmAbQUlZtCrprGAXTjGcABhEjxpVIzwTnAAIgUum0aXS-3A3WKd2UXzU4GgJHgQgKUMaMNUOHAvBIAGtMUM6qMmq91IZOhZbABmeYANmWw3q0OaZNJ7E6TLoL3en2+mTy7GQkKK0j2B3hiORPD4hSK0LSsMx2Lx3EUVQJIzJmwqJHUu32RzJZ3MlzRN2hj05TDGWHqgPgwNB4LyMpF+pVuQhxVdYv2ZHwuVY4BciJ11RW9U1W04Yz9utFBrZRp8fi12xINCAA) is not legit:
```js
type OneD = { x:number };
type TwoD = { x:number, y:number };

const coordA:TwoD = {x:1,y:2};
const coordB:TwoD = {x:2,y:4};

const coordC:OneD = {x:3,y:6}; // OK
const coordAOneD:OneD = coordA; // OK 

const OneDVector:Array<OneD> = [coordA, coordB]; // OK

const TwoDVector:Array<TwoD> = [coordA, coordB];
const OneDVectorBis:Array<OneD> = TwoDVector; // Error.
```

The error more or less look like this: 

> Property `y` is incompatible. property `y`. Property not found in `OneD`. 

Which is true, but I don't see how this is a typing error? I mean it's not an error when playing with objects, why would it becomes one when playing with arrays of the same objects.

**Comment by vkurchatkin** [comment]
Because arrays are mutable, which makes them [invariant](https://en.wikipedia.org/wiki/Covariance_and_contravariance_(computer_science)). Using `$ReadOnlyArray` fixes the problem:

```js
type OneD = { x:number };
type TwoD = { x:number, y:number };

const coordA:TwoD = {x:1,y:2};
const coordB:TwoD = {x:2,y:4};

const coordC:OneD = {x:3,y:6}; // OK
const coordAOneD:OneD = coordA; // OK 

const OneDVector:Array<OneD> = [coordA, coordB]; // OK

const TwoDVector:Array<TwoD> = [coordA, coordB];
const OneDVectorBis:$ReadOnlyArray<OneD> = TwoDVector; // OK
```

**Comment by cglacet** [comment]
Ah ok, that makes total sense. Now I see how allowing this would be a problem if we start pushing 1D-coordinates in the 2D-Array. `$ReadOnlyArray` is exactly what I needed in my case, thanks for the explanation.
