### ISSUE TITLE
Unsafe lookup class instance properties if not initialized.

### ISSUE THREAD

**Issue by bhongy** [facebook/flow#5744]
It seems like class instance properties are not being checked if the properties were not initialized (e.g. in constructor).

```javascript
type Team = {
  name: string,
};

class Game {
  aTeam: Team;
  bTeam: Team;
  constructor() {
    this.aTeam = { name: 'A Team' };
    // did not initialize bTeam, no complain
  }
}

const game = new Game();
console.log(game.bTeam.name); // no flow error but it'll throw in runtime
```

Tested in Flow 0.64.

[Detailed example on Try Flow](https://flow.org/try/#0C4TwDgpgBAKhCGBbKBeKBvAUFKA7JEAXFAM7ABOAlrgOYA0mAvgNzaYDGANvCSVAOIEM2KPDhJi4xKxwAjKZITSR7BbCUyoAEzVTNEXRswqA9rjLkAru2AnyACgCUwnDmAALSiQB0Ypagw8AmIAcgBBdSQQqBYRHAB6eKgIcnI7YlBIKGp2E0QweGBKWU4IOigPL2y+CAAPSBsILW84is8feX80S1wtCAAzaibNBKSUtPJiRC8SahooEPxECGjBiE4tcsq+KrqG4CaW1zavb1UuwNjjxLwTYGzcSiL4TkoAL2gdf3he5Kkoeylfr3Az+EyWe7UA64IpmF6cECOVrbbxfJCaRjGHDkBBaAAiUicLlcN221Sgg1wEFaOOAlnIuBOPjRyhwmJEAHcqAcCUoiVhrmNUukKuBoDk8gUiiUykzyXsII0tMj2qj-mh0FcYkxjLlzPcaEI0FSOQICE5WJgbiR4P1ZTxkvVFQdmhwzCQTKVvJwTDR7Iblr4pN4lhBHKwbrgTMlheRyrJFfBLCRoB5oOM7FAOQ72EmaO5IYy9RZrLY46Iak6lS1i56IN7ff6CGdg6Hw8YbgBVKlVl3EKMxiYVcggOYVaPwdjsCC8bRScqgpBu8x1ht+gP1lkhgjt2ten3r5uLxDb5bhoA)

**Comment by RyanCavanaugh** [comment]
Duplicate of #650

**Comment by bhongy** [comment]
Thanks @RyanCavanaugh!
