### ISSUE TITLE
Union type and destructuring function parameters does not work together

### ISSUE THREAD

**Issue by AlexanderShushunov** [facebook/flow#5745]
I have a union type:
```js
type Option = {
    hasValue: true,
    value: number
} | {
    hasValue: false
}
```
The property `hasValue` is existed in both cases.
If I try to extract the property by destructuring assignment, it works correctly. 
```
declare var option: Option;
const {hasValue} = option;
```
But if I do destructuring in function parameters, Flow produces very srtange errors. 
```
const isEpmty = ({hasValue}: Option) => !hasValue;
/*
    boolean literal `false`. Expected boolean literal `true`, got `false` instead
    ...
    boolean literal `true`. Expected boolean literal `false`, got `true` instead
*/
``` 

[TryFlow](https://flow.org/try/#0C4TwDgpgBA8mwEsD2A7KBeKBvAUFfUAFgIYDOAasQDYCuEAXFMAE50A0eBAbtXYyjQC2AIwjMcAXygAfbJ3wkKvBlABm1UhEk4cAEwgBjKsWbQezKEnjIUjOIlQBuHAdSlg2RZVoQpmKw4ozi5uHgikAKJggqAYUAAUWF7KEnbWqACUGAB8UACEyT7OQA)

**Comment by kristiehowboutdat** [comment]
Another reproduction using Flow 0.73.0: [Try Flow](https://flow.org/try/#0C4TwDgpgBAsiAq5oF4oG8oH1OkgOwEMBbCALigHIBBCqAXyigB90sclCTyKAhWugNwAoIQHpRUACIQAzsABOAVwDGwRfICWeAOZQtUAGaK8qjQHs8UAEZmAJiCgBaKAHcz8gNYyhyi3NfuXlCoABTA5HCIkACUwQB86EKMvnj+GNi4EJzQDKjAwgCQGgZQIRkcxCjIqNQUsWhJjFAFKTJmADYQAHTtZtohtdHCTfRCdCLiUrIKKmqaOnqWRibA5pZgBPLEMk5QtmayUAByAPLwAZ4+fsB7BzJ4wADqgcGl6ez4lfQRCEixyAkGkUSmUPlkvtUajR6o1GC0-B1ur1+oNhk1xnQgA)

```js
type MyType = { __typename: 'A' }  | { __typename: 'B' };

// Destructuring in function body - works
const works = (t: MyType) => {
    const { __typename } = t;
    if (__typename === 'A') {
    	console.log('A');
    }
}

// Destructuring in function params - does NOT work
const doesntWork = ({ __typename }: MyType) => {
    if (__typename === 'A') {
    	console.log('A');
    }
}
```

Errors
```
12: const doesntWork = ({ __typename }: MyType) => {
                          ^ string literal `B` [1] is incompatible with string literal `A` [2].
References:
1: type MyType = { __typename: 'A' }  | { __typename: 'B' };
                                                      ^ [1]
1: type MyType = { __typename: 'A' }  | { __typename: 'B' };
                               ^ [2]
```

**Comment by villesau** [comment]
Some related issues:
https://github.com/facebook/flow/issues/6146
https://github.com/facebook/flow/issues/6805
https://github.com/facebook/flow/issues/6594
https://github.com/facebook/flow/issues/6408
