### ISSUE TITLE
React.ElementProps and React.ElementConfig pass incorrectly with non-class component

### ISSUE THREAD

**Issue by Peeja** [facebook/flow#5746]
These pass, but should (if I understand what they do correctly) fail:

```js
({foo: 1}: React.ElementProps<React.ComponentType<{foo: string}>>);
({foo: 1}: React.ElementConfig<React.ComponentType<{foo: string}>>);

({foo: 1}: React.ElementProps<React.StatelessFunctionalComponent<{foo: string}>>);
({foo: 1}: React.ElementConfig<React.StatelessFunctionalComponent<{foo: string}>>);
```

These correctly fail:

```js
({foo: 1}: React.ElementProps<Class<React.Component<{foo: string}, any>>>);
({foo: 1}: React.ElementConfig<Class<React.Component<{foo: string}, any>>>);
```

[try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAFAN4EQQBccAjAL5fY8MAHQBRADZYQWAHYwACsTCoAPIPzCAwiUgzZMACoBPMFhWt2XVDCjAZAc14A+JwEp6LNpx79MVERJS+toyBMD2av5aOhB6csam5l5WNnaOLu4MnpY+AlGB0nKKEMqRQsIAyjDIMFiSqKgAYgCuMvjAscji2uCx+kk51rYOzm4eFt58eeUFwbFhEeoiVTV1WA0tbTAdMl09uv0TKcPpY1lHuX4zkoUKSqqa4miqS9G9cTAD3kNpvAA0KBkRhcZ2yk18r1mchCCxUj2eZQ0+z6ci+x1+AOQQJBmSAA)

**Comment by migueloller** [comment]
Having this issue as well. Interestingly enough, defining `SFC<T> = (props: T) => null` doesn't have the same issue with `React.ElementProps` but it does with `React.ElementConfig`.

[try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAFAN4EQQBccAjAL5fY8MAHQBRADZYQWAHYwACsTCoAPIPzCAwiUgzZMACoBPMFhWt2XVDCjAZAc14A+JwEp6LNpx79MVERJS+toyBMD2av5aOhB6csam5l5WNnaOLu4MnpY+AlGB0nKKEMqRQsIAyjDIMFiSqKgAYgCuMvjAscji2uCx+kk51rYOzm4eFt58eeUFwbFhEeoiVTV1WA0tbTAdMl09uv0TKcPpY1lHuX4zkoUKSqqa4miqS9G9cTAD3kNpvAA0KBkRhcZ2yk18r1mchCCxUj2eZQ0+z6ci+x1+AOQQJBmToMBMWDgFUamhUBiccAAvHBGGB7lwDK4qRTXgA5CAAEywdDgvLgTAuUyuGihdxKqmJpIuPxGGXGyUukJuc1C4RUkrRcBlp0yQA)

**Comment by SamChou19815** [comment]
They are now expected to pass after React typing revamp a while ago
