### ISSUE TITLE
 Isn't Array a subtype of Object? 

### ISSUE THREAD

**Issue by philipp-sorin** [facebook/flow#5748]
If this is a bug, please try reproducing using https://flow.org/try/.
Error: src/main/views/pricing/packages/DetailedCountry/DetailedCountryView.js:357
357:            const currentAdditionalServices = flatMap(current.currentPricePackageCountries, x => x.additionalServices)
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ array type. This type is incompatible with the expected param type of
554:     flatMap<T: Object, U>(
                    ^^^^^^ object type. See lib: flow-typed/npm/lodash_v4.x.x.js:554

**Comment by AugustinLF** [comment]
Technically, everything is a subtype of an object (a function also in JS). But flow is a bit stricter, and tends to do "what should be correct". So, for flow, an array isn't an object.

**Comment by philipp-sorin** [comment]
Doesn't this statement break Polymorphism here?  :)

**Comment by AugustinLF** [comment]
Hmmm, not sure of what you mean here^^ I guess the flow team considers that there are really few use cases where you'd want an object and accept an array. Could you perhaps provide us with an example?

**Comment by SamChou19815** [comment]
Not enough info to repro
