### ISSUE TITLE
Can no longer cast functions to classes

### ISSUE THREAD

**Issue by jdelStrother** [facebook/flow#5750]
We used to be able to cast functions to class-types, to type check new-able functions (https://github.com/facebook/flow/issues/2149)

```js
function SuperClass() {}
function Foo() {}
Foo.prototype = Object.create(SuperClass)
Foo.prototype.bar = function(){}

interface IFoo {
  static (): void;
  bar(): void;
}

export default (Foo: Class<IFoo>);
```

It seems like this stopped working around flow 0.62, and now complains that the function "is incompatible with statics of IFoo".  Any suggestions on a workaround?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBlTABwFMAnAYRgEMBnFgCgEowBvAXww4CxUgDE4cLr1QDxcAHSVacfCoCeNMAF4wAeQBGAK2oF5uWtSb5q7CjQbM2nVHMXLV+DdXn6mtbWBYeEQkXPzohNjWtFBMuNRgAJJy0mBgLPhWhLhgXABcYABucIQAJgDcqGm+tPlFJRUy6NQAHpRwtPhgpdSxmDBd7HIFjKwsADzJEgB8nOVAA

**Comment by SamChou19815** [comment]
Expected as we deprecated old-style class support.
