### ISSUE TITLE
A way to bypass flow type checking

### ISSUE THREAD

**Issue by henricavalcante** [facebook/flow#5751]
I was introducing flow and refactoring legacy code and I found a weird behavior in Flow, if the `return` statement is placed before functions there is a way to bypass the type checking as I did in this example:

```js
/* @flow */
(function() {
  var _obj = {a, b};

  _obj.b(3);
  
  return _obj;

  function a(p1: string): string {
    return 'string';
  }

  function b(p1: number): string {
    return _obj.a(p1);
  }
})();
```
output:
```
No errors!
```
[Live (flow.org/try)](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAFFArgOwMYAuAlnDugJRgDeqYYtYAbgIYBOYA+nAEYBWYAXmrMANGG4BfANwNgwMACUApgAcYzPERwBzJmzAE4YPKQDOBMEtas47BERgxxSsKYAWiJQBNZwEznNOHn4hKlFxaQYGLj4AOm50AGZyGToE5NT6OlYlAixWHCC+GQZsfGJSMGZ0FQBGAC5XAlYtbXJG8xadagZs3PzCgHJO1sHMiVRS3EISQoS6xpwsAFtuK3amrt0aOj68gqLeWOq6lIYJiXIKKSA)

if I move return after functions or even if I change `var` to `const` the error is displayed as well like this:
```js
/* @flow */
(function() {
  var _obj = {a, b};
  
  _obj.b(3);
  
  function a(p1: string): string {
    return 'string';
  }

  function b(p1: number): string {
    return _obj.a(p1);
  }

  return _obj;
})();
```
output:
```
12:     return _obj.a(p1);
                      ^ number. This type is incompatible with the expected param type of
7:   function a(p1: string): string {
                    ^ string
```
[Live (flow.org/try)](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAFFArgOwMYAuAlnDugJRgDeqYYAbgIYBOYA+nAEYBWYAvNUYAaMJwC+AblphpHHgDpO6AMzkpdadnzFSYRugAOARgBcYAM4FmRHAHNyZy9bvVpdZgFMCWZjjAByJxtbf3UwMVRNXEISPyVjMxwsAFtOD2YHCytg1zp3Lx8-OW55fWM1aQjpT29fdi5uKTFyCgkgA)

**Comment by SamChou19815** [comment]
This has been finally fixed recently.
