### ISSUE TITLE
Thrown error: 'Unsupported option specified! (unsafe.enable_getters_and_setters)'

### ISSUE THREAD

**Issue by hikerpig** [facebook/flow#5754]
version: 0.64.0

My .flowconfig

```
...
[options]
unsafe.enable_getters_and_setters=true
...
```

**Comment by TrySound** [comment]
@hikerpig This option was removed and accessors enabled by default. See [changelog](https://github.com/facebook/flow/blob/master/Changelog.md#0620)

**Comment by hikerpig** [comment]
My fault, didn't see changes in flowtype.org docs, should have checked changlog

**Comment by TrySound** [comment]
You may close the issue.
