### ISSUE TITLE
Array methods yield improper type resolution on resolved `Promise<Array<imported type>>`

### ISSUE THREAD

**Issue by ghost** [facebook/flow#5761]
[try flow link](https://flow.org/try/#0JYWwDg9gTgLgBAMQhOAzKERwOQDoD0qy2A3AFBmoCuAdgMYzAQ1wDmApjUhAM4AUASgBccAAoYQwHuwA8AQShQAhgE8Z3AHwa4AbwC+FJTxX00tBkxYATCAGVM7GAAtgNVoN1k4cOsx7wiXjgAXjglAHclYHgOLmR+AXJvQJ5cIigAUSU6J0FyAyA)

```
import Foo from './foo';

function genFoos(): Promise<Array<Foo>> {}

async function doSomething() {
  const foos = await genFoos();
  foos.forEach();
}
```

`foos` on the last line resolves to `Array<Foo> | Promise`.  Seems to be related to the import (not a missing import since the actual import in my code resolves fine).

My editor started complaining at me with the above code when I typed `.forEach()`, saying that `foos` was resolving to `Array<Foo> | Promise` and that `Promise.forEach` isn't valid.  As soon as you add a function in the forEach, e.g. `foos.forEach(n => n)`, it properly resolves `foos` to `Array<Foo>` again.

I'm not sure if this is a case where invalid code is making flow behave oddly (since `foos.forEach()` would throw), but regardless I think it should behave properly since many editors will run incomplete code through flow.

**Comment by zyklus** [comment]
Correction: This issue isn't isolated to `.forEach()` being called without a function, but I can't seem to reproduce it easily with try flow since it seems to require an `import` to a valid file.  I just made a simple file with:

    export default class Foo {}

and changed the `.forEach()` to `.forEach(a => a.foo())`

**Comment by SamChou19815** [comment]
These issues are likely fixed a long time ago since types-first
