### ISSUE TITLE
React Portal type

### ISSUE THREAD

**Issue by marlo22** [facebook/flow#5762]
Hi everyone! 😄 
How I should define type when my components return React.Portal? Code below is OK?

    render(): React.Portal | null {
      if(domNode !== null) {
        return ReactDOM.createPortal(<LoaderExpanded />, domNode)
      }
      return null;
    }

Thanks for answers!

**Comment by TrySound** [comment]
@marlo22 You don't need to define return type in components. It will be inferred.
