### ISSUE TITLE
ReactDOM.hydrate: Property not found in module 'react-dom'

### ISSUE THREAD

**Issue by JustFly1984** [facebook/flow#5766]
<img width="1261" alt="screenshot 2018-02-04 11 22 09" src="https://user-images.githubusercontent.com/2255993/35774535-3bb735dc-09ad-11e8-80e3-4e9cc4002312.png">

Please, somebody explain, what is going on?

**Comment by apsavin** [comment]
#5074

**Comment by apsavin** [comment]
Also, double of #5035
