### ISSUE TITLE
Lodash style _.get to get the type as well?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5767]
So something that I really continually fight is when using things like lodash's `_.get` functions.  Obviously it makes sense that it might be very hard to handle when using the string styling to get a value within an object, but I was wondering if it would be possible to somehow type when using the array styling.

I think I can see how it might be achieved with some magic, but think I need a bit of help to see this one through.

So we have an object that may be multiple levels deep.  We type is appropriately, in our case we even make it read only:

---
## Bootstrap

```js
type ConfigType = {
  +foo: {
    +bar: boolean,
    +baz: number,
    +qux: {
      one: string
    }
  },
  +bar: number
}

const config: ConfigType = Object.freeze({
  foo: {
    bar: true,
    baz: 2,
    qux: {
      one: 'two'
    }
  },
  bar: 1
})
```

---
## Goal: 

Our goal is to properly type it so that we can use a "getter" function to easily access the nested type (and value).

```js
const qux = _.get(config, ['foo', 'qux'])
(qux: { [key: string]: string });
```

---

So we are going to need a function to access the keys within the given object.  Instead of using Lodash, I wrote a similar implementation so that we could attempt to get it to properly give us our type.

Below will not properly do what we need as it does not strongly type the path to the point it will be aware of the possible levels of depth.

```js
const get = (path: Array<string>, def?: any, ...args: Array<*>) =>
  path.reduce((p, c) => {
    if (typeof p === 'object') {
      let value = p[c];
      if (typeof value === 'function') {
        value = value(...args);
      }
      return value || def;
    }
    return p || def;
  }, config);
```

Here is where things start to get a bit tricky and I am not positive it is really possible in the end to do this, but I feel a few ways are there if we get clever.  So wondering what you guys think.

---

## Using $Keys

So my first thought is that we will need to use `$Keys` to capture an array of the possible keys that can be used in our array.  Our issue is that we are going to need to get multiple levels deep in order for this to work.

On the first level it is easy as we can simply run the following:

```js
type ConfigKeysType = $Keys<typeof config>;
```

Since our config is a frozen object, this will then provide us with `'foo' | 'bar'`

However our goal is to continue this practice to use the value of the first element to capture the type of the next and so-on.

So this is where it gets pretty darn complex to handle and I have run into a roadblock.  I can kind of see what needs to be done here using $Call, $TupleMap, etc. but it's pretty complex.

---

## Gibberish

Ok so this is where I am pretty much going to be probably not making sense as I work through my confusion  (and hopefully spark one of you to realize how this might be possible, if it is).

I am thinking we will end up needing something along these lines:

```js
type CaptureKeysOf = <O, K>(obj: O, key: K) => $Keys<$ElementType<O, K>>;
```

Which we will then use `$Call` to capture each responding element that we map from the array we receive?

So our end result would be something that would result in a type like (structured that way to illustrate but really it would just end up being a single union of all possible strings in the end):

```js
type AcceptableKeys = ('foo' | 'bar') | ('bar' | 'baz' | 'qux') | ('one')
```

I figure it will be essentially impossible to structure it in a way that it could dynamically enforce the position of the acceptable keys since that would require tuples and we don't necessarily know the depth. 

We could go the route of just having a maximum depth and creating tuples of every variety but that seems like it would end up breaking down as the application might evolve and I do want to be able to use this in more cases than just this.

In the end, the goal is for our caller to know the type of value it called (or if that value was not found int he object).  

---
## Flow Lockups

Unfortunately this tends to break flow completely quite a bit as it is obviously looping (as mostly expected).  Below is some other stuff I was playing with... I mean I feel like I know what I need to do but I don't know how to get there.  Going to need to refine arrays to tuples then use $Keys to create acceptable array of string literals... ahhhhh!

Note: Yes I am aware the actual thing being done below can easily be represented by Flow without any extras, just showing as example 

Any ideas?

```js
type CaptureKeysOf = <O, K>(O, K) => $ElementType<O, K>;

type ConfigureType = {
  +one: {
    +two: string,
  },
};

type OneKeys = $Call<CaptureKeysOf, typeof config, 'one'>;

const configs: ConfigureType = Object.freeze({
  one: Object.freeze({
    two: 'hi',
  }),
});

const test: OneKeys = configs.one;

console.log(test);

```

At this point its more become a project of interest.  Simply wanting to see if the advanced functionality of Flow has reached a point that we would be able to refine this complex of a situation.

**Comment by bradennapier** [comment]
From what I can tell, to make this work well we would simply really want something that could basically iterate an array and eventually return an object as the type (or any other type as the result).  So we need to refine in more ways at the end of the day.

**Comment by bradennapier** [comment]
I would note that the following does work, so it seems to be a matter of applying it within some sort of mapping function to reduce and filter it.

```js
const path = ['one'];

type ObjType = {
  +one: 'two',
};

const obj: ObjType = Object.freeze({
  one: 'two',
});

type PathType = $ElementType<typeof obj, $ElementType<typeof path, 0>>;

('two': PathType);
```

**Comment by trevorwhealy** [comment]
This addition would be incredible.

**Comment by danielo515** [comment]
I am wondering if this is possible with a much simpler (and less nested) type.

Something like `{ [key: string]: string | Itself }`.

Have you achieved something like that?
