### ISSUE TITLE
Refine tagged unions by singleton boolean types

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#577]
https://github.com/facebook/flow/blob/28f01d1800618ad9f679d7a394c1feff1edf3a16/src/typing/flow_js.ml#L4225

This can be used to form a more specific type for `IteratorResult` values with completion values. Something like:

`type IteratorResult<Y,R> = { done: false, value: Y } | { done: false, value?: R }`

**Comment by andrewimm** [comment]
Subscribing, since using `0`/`1` for flags is getting uncomfortable.

**Comment by samwgoldman** [comment]
Sorry for the lack of movement on this one. I got a bit in the weeds when I started looking into this. We need to make sure we handle refinements on `obj.prop`, `!obj.prop`, and `obj.prop === boolean`. The former two cases are where things git a bit hairy, because if the prop isn't a sentinel value, we still want to do a heap refinement.

I'm going to unassign my self in case someone who has more bandwidth wants to take this on. I won't have time for a few weeks.

**Comment by samwgoldman** [comment]
Some use-case code, with a bonus complication.

```javascript
/* @flow */

// OK
function *map<T, U>(f: (x: T) => U, xs: Iterable<T>): Iterable<U> {
  for (let x of xs)
    yield f(x);
}

// Needs boolean sentinel discrimination
function *map2<T,U,R>(f: (x: T) => U, xs: $Iterator<T,R,void>): $Iterator<U,R,void> {
  let result = xs.next();
  while (!result.done) {
    // result.value should be Y
    yield f(result.value);
  }

  // result.value "should" be R|void, but we have another problem: our
  // generator expects us to return R here. R may be `void`, so we
  // can't refine the problem away. We could make the return optional,
  // since IteratorResult is `|void`'ed anyway...
  // ... but I think we should just relax type checking here, and
  // assume done=true implies value=R. People shouldn't iterate past
  // the completion value in practice. Fair trade-off, IMO.
  return result.value; 
}
```

**Comment by Daniel15** [comment]
Here's a pretty simple example of something that should work once boolean refinement is implemented:
```js
type MyState = {
  isVisible: false
} | {
  isVisible: true,
  name: string,
};

function handleState(state: MyState): string {
  if (!state.isVisible) {
    return '';
  }
  return state.name.toUpperCase();
}
```

Today this throws a Flow error "property `name`. Property not found in object type" as it doesn't know that `state.name` will never be null if `isVisible` is `true`.

**Comment by samwgoldman** [comment]
Going to reopen this. The current commit does enable refinement, but only using syntax like `if (o.p === true)` -- i.e., with an explicit `true`/`false` check. It does not work for syntax like `if (o.p) {...}`, which we definitely want to fix as well.

**Comment by samwgoldman** [comment]
Existence checks are released now. Forgot to close this.

**Comment by puneetar** [comment]
Probably there is a difference between how types and interfaces are treated in flow

```
type AB  = {
    x : true
}

type AC = {
    x : false,
    name : string
}

type A = AB | AC

const fold= (a : A) => (f: AB => string, t : AC => string) :string => {
    if(a.x)
        return f(a) // works 
    else
        return t(a) // works
}
```

```
interface AB {
    x : true
}

interface AC{
    x : false,
    name : string
}

type A = AB | AC

const fold= (a : A) => (f: AB => string, t : AC => string) :string => {
    if(a.x)
        return f(a)  // Cannot call `f` with `a` bound to the first parameter because boolean literal `false` [1] is incompatible with boolean literal `true` [2] in property `x`.
    else
        return t(a) // Cannot call `t` with `a` bound to the first parameter because property `name` is missing in `AB` [1] but exists in `AC` [2].
}
```

Why does using interfaces to declare the union type not work?
