### ISSUE TITLE
A piece of code makes flow go crazy

### ISSUE THREAD

**Issue by sam-rad** [facebook/flow#5774]
Not sure why but if you go to flow/try and paste this:

```
const objToKeys = obj => 
  Object.entries(obj)
    .reduce((acc, [k, v]) => 
      typeof obj[k] === 'object'
        ? [ ...acc, k, ...objToKeys(obj[k]) ]
        : [ ...acc, k ], 
      []);

```

the browser will freeze. I tried with the a local installation and that will jump the CPU usage up to 99% and I have to kill the process. I tried with `0.53.0`. `0.64.0` and a few others.

**Comment by TrySound** [comment]
Yep, related to https://github.com/facebook/flow/pull/5735
Seems like last flow version don't handle recursion well

**Comment by snikobonyadrad** [comment]
Oh wow. It's not just the latest version though.

**Comment by TrySound** [comment]
Just didn't have such problem a few versions ago.

**Comment by SamChou19815** [comment]
Fixed
