### ISSUE TITLE
Weird behavior with the simplest arg => value generic

### ISSUE THREAD

**Issue by TrySound** [facebook/flow#5775]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAJngHYYCW2YAvGADwAqAfABQBuAhjAK54AuMEwCUdFsIDcqMLLCo8ADxxwAThjABjOGQDOGysSElyVGvW58CtCZf6SgA

**Comment by snikobonyadrad** [comment]
That can be written as:

```
type Identity<T> = (value: T) => T;
const id: Identity<*> = value => value;
```
