### ISSUE TITLE
Binary operators don't work as intended inside logical operators

### ISSUE THREAD

**Issue by mroch** [facebook/flow#578]
function num(x: number) { }
num((100 * false) || 0);

The code above gives a boolean ~/~ number error blaming the function call. Looking closely, the type of 100 * false is inferred to be boolean.

The reason is that bool_test is called whenever _ op false appears, even when op is * (whereas this routing should happen only for equality operators). See https://github.com/facebook/flow/blob/28f01d1800618ad9f679d7a394c1feff1edf3a16/src/typing/type_inference_js.ml#L4388

This is probably also a problem with other cases above and below this case: in general, ops need to be matched earlier, so that non-matched ops correctly fall through to https://github.com/facebook/flow/blob/28f01d1800618ad9f679d7a394c1feff1edf3a16/src/typing/type_inference_js.ml#L4535

**Comment by mroch** [comment]
cc @samwgoldman, possibly relevant to #577

**Comment by samwgoldman** [comment]
Interesting bug! If you're in there, and the fix for #577 is at hand, feel free to take it over! :smiley:

**Comment by mroch** [comment]
Closed by 32bb69984037caae3b4589fc2722651d3b89a6f8
