### ISSUE TITLE
Wrong error position with $ObjMap and disappearing errors

### ISSUE THREAD

**Issue by niieani** [facebook/flow#5785]
# [Flow Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagCQFUA7AS1gIHUjkALWAV2QB4A5WZAFQBpQBhaTAQwJsAfKAC8ubv2jQGDAEqYAzu2EAKAG6gAXDz6C2oAD6hFKtgEpxos+y4tVKDNhwsCTWjIYjxuQiXJKGnpvLgJPaGEnLFw3DxkAeQAjACtMAGNGHwkcZJSAWX50UNAGAAUAJ1h0ETVK6strP2JSCmo6RnqasIjhKLQY11I8jORfFQqiAgBzY1BwgFskzAq5pNhYfQI5gDFaAkyAuYBBCor+VAZBVFETcJk5jVgiABNolziIkcyAEUxMYrZXB5QrFRCgUCccGgECgKagdL8JTYShKeasUCCUCwVKjbTQgBkoDU5SqNR0sWGuMy6nu0DmXUaYlEjIs0NhmGgyK4FQytAqSiIGmwiJk+IhRJJjPUrKaQ3cX2pyD+ANJDWEbKi71AKvQvgA3tDSJhdBMprM7hEONDkPBYLpDRCIS9-uhTchJjM5nTrRCAL7eq2IP2IRDpUgqUDoJFo3Ty+LQb7K10MXWiCSO7EEE2gADkAEYAEwAZlzvtAtvtoEzztdugLJdz0L91pDiFhcERyCOsEgFaoRDRKyqq0HoCUtHW6G7C2kYYjY0g-CI0HzFPjirSvxTaYNRuz9aLpfLld0PuDodh1DHw9gqxeg6KWH4AtA8ComG2uaXK-zubhaLwtQIqwC67ZgMimALIBYxjhO6C8kogpeteSjzgQkY-tAhbrp8iRKrqqauum1b7jmDbHjadoOi6AJnhELYXuhmHLtAxa4aQCZJoRu4ZmR9EyCe1GkU6oC0W6eZHk2-qtogQA)

```ts
const fail1 : $NonNullObjectDeep<Deep> = {
  one: '123',
  two: null, // location of this error is shown in $ObjMap definition instead of here
}

type $NonObject = string | number | boolean | Function | Array<any> | null | void
type $NonNullObjectDeep<T> = $ObjMap<
  T,
  // in case its not an object, remove "null":
  & (<PropT : $NonObject>(null | PropT) => PropT)
  // else, recursively remove nulls for each object prop:
  & (<PropT>(PropT) => $NonNullObjectDeep<PropT>)
>

type Deep = {
  one: string | null,
  two: {
    deep: string | null,
  } | null,
}
```

**Comment by SamChou19815** [comment]
Closing since $Call and $ObjMap is deprecated
