### ISSUE TITLE
Update Flow-to-React-PropTypes info in React Components docs

### ISSUE THREAD

**Issue by visusnet** [facebook/flow#5786]
The docs reference a flow to a proptypes plugin that was previously owned by @thejameskyle and moved to the Atlassian Github organization (there is a redirect). While this plugin provides some use cases, many basic features are missing (including generic components like ``Component<Props>``). Additionally, this plugin does not seem to be actively maintained anymore.

There is another Babel plugin that has the same mission but seems more feature complete and is actively maintained:
https://github.com/brigand/babel-plugin-flow-react-proptypes

I therefore propose that you update the link to the now-Atlassian-plugin and additionally mention @brigand's addon.

**Comment by thejameskyle** [comment]
Of course it's maintained, just because it doesn't have commits for a few months doesn't mean it's not maintained. If it doesn't do something you want, open a pull request, don't go around complaining about it.
