### ISSUE TITLE
Required module not found for peerDependencies

### ISSUE THREAD

**Issue by parkroolucas** [facebook/flow#5787]
Flow is giving me errors, stating that a required module cannot be found, whereas it is included in my project as a peer dependency.

What is the best way to proceed with this? Should I include the dependency under `devDependencies` also?

Thanks in advance.

**Comment by TrySound** [comment]
@parkroolucas Is it exists in you `node_modules` folder?

**Comment by parkroolucas** [comment]
@TrySound No it does not, as it's a peer dependency. I understand that it makes sense for Flow to give me this error; however, I'd like to know what would be the best solution in my situation.

**Comment by TrySound** [comment]
@parkroolucas flow doesn't care how you keep dependencies in package.json, but they should be in `node_modules`. If you keep your dep in peer, then you don't want it to make direct dep, so you add it as devDev only for dev process.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
