### ISSUE TITLE
Expect error for invalid factory parameter

### ISSUE THREAD

**Issue by sepo-one** [facebook/flow#5788]
Version: `0.65.0`

```javascript
type Reducer<S, A> = (S, A) => S;
const makeReducer = <S, A>(is: S, r: Reducer<S, A>): Reducer<S, A> =>
  (s, a) => (s === undefined ? is : r(s, a));

// $ExpectError: because r() suppose to return string
const reducer = makePlainReducer('', () => {});
```

So i expect error here, because parameter `r` i'm passing to factory should return state (according to `Reducer` type).

Unfortunately, cannot repro as [try](https://flow.org/try/) service seems to be down

**Comment by sepo-one** [comment]
Event the simpler [example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAJgK4DGeATgDwDKANGAIIB8YAvGABROsBKLh3oBuVCTwUYAQ2oEoZAHYUMASzhKwAWxkBrPMXJU69NjzVK16mTHoYZGPAC4w9Aa6OUaDZiDbiYEHBQagUmgDOGGDyxjRcOvqGpN7UPADk6QLiqMDAYAAkAKIAHviqRdTUcNSuAEZk0QByAPJgNNXUqLGpPACM2ahAA):
```javascript
/* @flow */

type Reducer<S, A> = (S, A) => S;
declare function makeReducer<S>(initialState: S): Reducer<S, *>;
        
const reducer = makeReducer('');

// $ExpectError: but NO error
reducer(1);
```

**Comment by SamChou19815** [comment]
It's now complaining that `A` is underconstrained, which is expected.
