### ISSUE TITLE
Try Flow (the "playground") not working

### ISSUE THREAD

**Issue by massimonewsuk** [facebook/flow#5790]
0.65.0 isn't working in the flow playground. I just get the 3 loading dots. It shows several 404s in the developer tools.

0.64.0 works fine though.

**Comment by IvanGoncharov** [comment]
Same issue for me:
![image](https://user-images.githubusercontent.com/8336157/35999270-ea7af1e4-0d27-11e8-9161-0cbae8638b49.png)

I can reproduce it in Chrome, Firefox, and Safari.

**Comment by SavePointSam** [comment]
Noticed the same on Chrome 64

![image](https://user-images.githubusercontent.com/8203211/36000580-43f2ef56-0cd8-11e8-873c-4c6375eeb4f2.png)

Master and the other versions work fine. Also, the issue is with `v0.65.0` not `0.6.5` as described in the original post.

**Comment by massimonewsuk** [comment]
@SavePointSam Thanks, I've updated the original issue description

**Comment by nmote** [comment]
I believe this has been fixed

**Comment by patw0929** [comment]
It seems not working with 0.68.0 now:
![image](https://user-images.githubusercontent.com/3055294/37524166-f6bd490e-2963-11e8-96f2-7967ec909e25.png)
