### ISSUE TITLE
Regression since 0.57.0: Inference chain gets broken in certain situations

### ISSUE THREAD

**Issue by villesau** [facebook/flow#5792]
Repro steps can be found from this comment: https://github.com/flowtype/flow-typed/pull/1731#discussion_r167033777

So in a nutshell, Flow can't infer the type from passed in object property which is assigned to object passed out. This causes unsoundness: you expect type to be what it is not. This seems pretty bad regression to me.

You can see in the test case that the component expects number, but string is passed in. If you test the libs on versions earlier than 0.57.0, Flow is able to infer the type and fails the test appropriately.

To see the issue clearly, you can remove the rest of the tests but the one comment is pointing to. Also others that top most `connect` definition are not relevant to point out this bug.

**Comment by villesau** [comment]
Here is a slightly better scoped example of the issue: [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6hwJ7oCmoA3qAMKwawB2xdOAKkcQDSgCi0xqjOAApZY6AM6gAvqEgjUoAORZiAQwDGOBQG4UtXKABUoFRIBKqjTLmLl6zToAmxNdBXL8bUABFkY9Cpw1AAsAHgBBAD5QAF5jOgJHZ1d3QhJQAHlUZBwfPwDgkOpaBiYo2IASH0hIQppMEpxOMgdff0CggC5vVvzQgwjJCMSXN1JU0gBZFXQAZRwA4mZYYVExENMZwS70gCMAK2ccMtAACjF5nGJt-cOAShiojcFh5NJiAA9MfUgAVzoNZD0UBqegMDS1VBdIr1ASsEghfqcLxbDI3DScJ7XA4aCInRCgUCoaZzBZLFbiLpTWYXRbLETidabCKIW5dE4g4oCKE0e7RKLQ+iwtghSrIaohHh8ATktZFCIYpmgABk3kEQ0QGvGoBlMXIshoJMuZPpYi65ywyDoAHNJDoRmIJEVQB9LnQHGYLDgAHQChohGVRMj40DKN3ELAne5BgkE5Q4H5YOigEItABuETIOCCvi96BNXv1qENtJlkhCwDT6oJkkQNcQWuLurIKi6dB+qB24dtGpBdHOhOJNONq11ZxpXWLvMDwbjCaT0ZjheLw4poHOCy9KmDNe7iF7-eodDBlwcut7x5OROppLpq1uJyKtx0tSPh2Ip+AQyAA)

See that the type `fromStateToProps` is `number` in type `State`, but `Props` expects it to be string. If you change flow version to 0.56.0, Flow detects the wrong type, but newer versions don't

**Comment by SamChou19815** [comment]
We no longer support this kind of inference.
