### ISSUE TITLE
Off by one error with unicode inside of JSXText

### ISSUE THREAD

**Issue by vjeux** [facebook/flow#5793]
![image](https://user-images.githubusercontent.com/197597/36008396-07f80c10-0cfc-11e8-8846-24bce2f5a88f.png)

http://astexplorer.net/#/gist/c11cae6b230f8aaefcbed0302e81eadf/9533fc2a9bf68758312ca54aa108bcfcbcf33231

cc @mroch

**Comment by vjeux** [comment]
Found by @sahrens :)

**Comment by vjeux** [comment]
Looks like it's also an issue inside of a string: http://astexplorer.net/#/gist/22497b5b7766458755c09c9d0514b472/b08f0c63938855236b3bd4da5d5805917c9c2581

**Comment by nmote** [comment]
This should be fixed by https://github.com/facebook/flow/commit/e1260684edfb269e01b3085b8b46ad1e62de29f2 and the associated commit to add an offset style flag to `flow ast` (https://github.com/facebook/flow/commit/4f5f353ef7220aae93ce3f12281825e6caf17c12)
