### ISSUE TITLE
Conflicts with React behaviour in terms of defaultProps

### ISSUE THREAD

**Issue by Albert-Gao** [facebook/flow#5796]
```javascript
// @flow
import React from 'react';

type Props = {
  name?: string
};

const Try = ({
  name,
}:Props
) => (
  <p>{`${name}`}</p>
);

Try.defaultProps = {
  name: '',
};

export default Try;
```

Flow will say that `${name} Error:(11, 10) undefined. This type cannot be coerced to string`

But this is an optional prop (not isRequired), and I give it a default value. So it must be an empty string
in the case where the caller doesn't pass it. Why flow considers this as an error?

I can remove that `?` to make flow happy. But that doesn't make sense. If it is a required property, then there is no need to give a defaultProps.

I can simply give the parameter a default value like `name = ''`. But that doesn't look right. it just like flow has completely ignored the `defaultProps` here.

Is it a bug or I miss something here?

**Comment by idiostruct** [comment]
> But this is an optional prop (not isRequired), and I give it a default value. So it must be an empty string in the case where the caller doesn't pass it. Why flow considers this as an error?

Undefined and null, possible values for `name?`, are not coerced to a string. Use `String(name)` to explicitly cast these values.

> I can remove the ? to make flow happy. But that doesn't make sense. If it is a required property, then there is no need to give a defaultProps.

Loosely speaking, "required" means `name` needs a value, which defaultProps satisfies. I understand your confusion with regards to defaultProps.

**Comment by Albert-Gao** [comment]
thanks for the detail! 

and according to the docs:

> Note: You don’t need to make foo nullable in your Props type. Flow will make sure that foo is optional if you have a default prop for foo.

Look like flow wants to be more generic so it doesn't want to make an exception for react's convention, that's all.
