### ISSUE TITLE
Export all types from file

### ISSUE THREAD

**Issue by Jpunt** [facebook/flow#5797]
We've got a lot of types in our current project and I'd love to organise them in separate files, while importing them from a single point of entry (like you would with regular js in some cases). That's why I'd love to do this:

```js
// types/index.js
export * from './a';
export * from './b';
export * from './c';
```

Flow-wise this seems to work! But running this code in a (in this case react-native) project, this doesn't seem to be stripped away and it failes on a syntax error. Am I doing this wrong? Is this an undocumented feature that I'm not (yet) supposed to use?

**Comment by TrySound** [comment]
@Jpunt It's just javascript. Possibly you don't transpile something with babel.

**Comment by Jpunt** [comment]
Are you saying that my example should work already? It does work properly when I re-export each type by hand (eq `export type {Something} from ‘./a’`), so I don’t see why my transpiler config would allow the one but not the other.. :thinking:

By the way, just found out that doing the same thing from within a nested file does work! Could this be a bug?

**Comment by TrySound** [comment]
@Jpunt Show more detailed example, it's not clear for me what is changed

**Comment by Jpunt** [comment]
I really don't know what happend before the weekend, but it seems to be working fine 🤔 sorry for this!

**Comment by dannyharding10** [comment]
I'm having the same issue in a project made with create-react-app. I would love for this to work, but I'll probably just revert to 

```
export {Type1, Type2) from './filename'
```

**Comment by TrySound** [comment]
@dannyharding10 For now you can use `export * from 'file'` which is works perfectly.

**Comment by dannyharding10** [comment]
Sorry that's what I meant, removing the word `type` fixed the problem for me!

**Comment by MaxInMoon** [comment]
@TrySound did [this PR](https://github.com/babel/babylon/pull/617) included the usage of `export type *`?
