### ISSUE TITLE
Any plan about the 1,920 open issues?

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#5798]
It seems like it's getting out of control.

Do you have a plan of action to review, close and triage all these issues?

VSCode dedicated a full iteration 1 year ago to achieve it:

> Welcome to [the April 2017 release](https://code.visualstudio.com/updates/v1_12) of Visual Studio Code. For this iteration, we shifted from our usual focus on new features to improving our processes and code base. We reviewed and triaged all our open issues, fixed bugs, and reduced engineering debt.

Do you consider doing something similar for Flow?

Can we help in any way?

**Comment by zaynv** [comment]
It's now reached 2000 :/

**Comment by TrySound** [comment]
You probably could help with identifying obsolete problems and answering questions. This could help a lot.

**Comment by FezVrasta** [comment]
Considering nobody of the team replied in 1 month I doubt that would make any difference.

**Comment by RyanCavanaugh** [comment]
I work on TypeScript but check in on this issue tracker from time to time to see what's going on. Caleb responded to someone on Twitter a while back

https://twitter.com/calebmer/status/970281251033686016

![image](https://user-images.githubusercontent.com/6685088/37223763-5e4e6ac8-2386-11e8-9f20-b8913e2bcda1.png)

They're definitely busy as shown by the commit history - lots of fixes and features going in!

**Comment by vkurchatkin** [comment]
It's true, Flow folks are mostly focused on internal work. If you think, that some issue should be closed or labeled, you can always ping me, and I will do it ASAP. Unfortunately, that's the extent of what I can do.

**Comment by saadq** [comment]
Thanks a lot @vkurchatkin and @TrySound for taking the time to go through all those issues and closing a bunch.

**Comment by juanibiapina** [comment]
Another option is to tag support issues here and outright close them with a recommendation to move them somewhere else.

**Comment by TrySound** [comment]
Flow team is shared an access with a few guys. We will help to close and label issues in free time.
