### ISSUE TITLE
Unexpected reserved type PropTypes.bool

### ISSUE THREAD

**Issue by sibelius** [facebook/flow#5801]
flow 65

Error: src/components/common/OpacityViewAnimated/OpacityViewAnimated.js:22
 22:     isLoading: PropTypes.bool,
                              ^^^^ Unexpected reserved type

Found 1 error

https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThxgqADIRkAE2AA7AOYAuOACMIEADY5ZAGjgB6fXBgR58remSzQyGMAizUQuBDB5gzMVgBuWDctkAVxAVLCgdZ1wAC2ANKUpZZWw8GAA6ADkIKSw6AF96OlwNNHQAeTdcDyYANWAsAHcAQWsQWywpOCwADxgsWSl0ZPxUgGESSFk+mAAeTlcAPgFnVBhbYFw4MC4AFRYsVGVBYWPo2Pi+5TmwXdZUVL8sECnU0WwAR0DgSikI4+FRCTSORKDg7PZ3NSaX5wfIMY4JbJQAAUAEoln9KDBAlBZHAghoNM4YXkgA

**Comment by idiostruct** [comment]
What's your rational for using both `type Props` and `PropTypes`?

**Comment by artemkapleev** [comment]
You should do like this:
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAPJh7DMBqwWAO4BBAHahkMLABMAKiyzoAvHADedOHGCoAMhGTTgogOYAuOACMIEADY5RAGjgB6Z3BgRjxu+mTiQksAQoqgacBBcuDxMOlgAblg25qIAriAWWFAOYbgAFsA20pSi5th4MAB0AHIQ0ljZAL70jAockdH8QmISUtIAyjCSbCrqmtp6BkZmcATINqj1YRHczLEJSXAADNmaeQVFWCVwqTY2jc24NmjonCtMnSL+Q9JwWAAeUqLS6GX4FQDCJEgokOMAAPLconwBI8ejJ5KxUE5IR0Yd0Ar0BkMAHxqMJwYp1KAACgAlHjNJpKDAUlBRMcUqd8Q06A0gA

**Comment by SamChou19815** [comment]
We deleted the support for PropTypes, so this should no longer be an issue
