### ISSUE TITLE
Resolve flow-typings and npm modules with the node module resolution algorithm

### ISSUE THREAD

**Issue by k15a** [facebook/flow#5805]
Currently, Flow only searches the flow-typed directory in the root of the project where the `.flowconfig` is located as well. This makes it extremely hard to use Flow with Yarn workspaces because different packages can contain different typings which are not resolved by Flow.

Especially with Jest it generates a lot of errors.
Think about the following folder structure:

```
packages/
├── package-a
│   ├── .flowconfig
│   └── flow-typed
│       └── npm
│           └── jest_v22.x.x.js
└── package-b
    └── .flowconfig
```

Both packages have flow but only package-a has jest. package-a is also a dependency of package-b.

If you run Flow in package-b it cannot find the Jest typings because it only searches for the typings in package-b. This results in errors in all the Jest files because Flow doesn't know the Jest globals like `it` and `expect`.

Another issue is that Flow resolves the npm modules only until it finds a .flowconfig file and not further up. This is an issue because Yarn hoists the dependency in the root of the monorepo.

As all of the 3 projects (Jest, Flow and Yarn) are developed by Facebook I would expect that they work a little bit better in conjunction.
It would be great if Flow could finally implement the complete node module resolution algorithm for flow-typings and npm modules so this issue is finally solved.

**Comment by k15a** [comment]
Unfortunately, I don't understand OCaml at all otherwise I would love to help.

**Comment by baob** [comment]
Does anyone have a work-around for this ?

**Comment by SamChou19815** [comment]
flow-typed are global libdefs, so it shouldn't follow node module resolution algorithm. Packages that want to ship flow types should use .js.flow files instead.
