### ISSUE TITLE
`this` not properly type checked when rending a functional component in React

### ISSUE THREAD

**Issue by dounan** [facebook/flow#5806]
Flow does a good job of checking the type of `this` inside a function when a function is called normally, but it fails to to check `this` when the function is being rendered as a React component. This can lead to accidental references to `this.props` in a functional component.

https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdBArgHb7AQtwCyAngMIlILLCxgAKAJQAuOKhhRgLAOZwA3nThwA9NrgB5CGFQAaODAAWwVADowxY3AAmELOhYR4WAB7WYNgM04ShgmKC5LazsHW2R6AF8GXTgAFSt0VAsIJgAbJzhcZCZULBQuLChiKDMAIyZ4YHgXNzgPGDoAHj5BcE5ReG0APiS9QUqsfBzeOAqq1Dpk7qE+sSkaIA

**Comment by SamChou19815** [comment]
It now errors
