### ISSUE TITLE
binaries are distributed over insecure HTTP

### ISSUE THREAD

**Issue by michaelficarra** [facebook/flow#581]
On the [Getting Started With Flow](http://flowtype.org/docs/getting-started.html) page, the download links for the binaries do not use transport-layer security.

>  * Mac OS X: [http://flowtype.org/downloads/flow-osx-latest.zip](/downloads/flow-osx-latest.zip)
>  * Linux (64 bit): [http://flowtype.org/downloads/flow-linux64-latest.zip](/downloads/flow-linux64-latest.zip)

Additionally, they are not even available over HTTPS.

This is a major security problem for anyone attempting to use Flow. For now, Mac OS users can work around this by using brew because brew distributes all binaries over HTTPS.

**Comment by mroch** [comment]
Hmm, I agree that this sucks. I'm not sure how much we can do about it without moving away from github pages, though.

To unblock you, there are HTTPS downloads available from the Releases page: https://github.com/facebook/flow/releases

In theory, an HTTPS version of the site should be available at http://facebook.github.io/flow/ but we've got some CSS issues... tracking in #584

**Comment by mroch** [comment]
Alright, I switched to the github.io SSL links in #585. Thanks!

I'm going to close this one, and see if we can get the whole site hosted with SSL while still under flowtype.org somehow.
