### ISSUE TITLE
Add support for Promise's `.finally()` method.

### ISSUE THREAD

**Issue by zachgoldstein** [facebook/flow#5810]
Using the promise method `.finally()` will break flow's typing. Here's a silly example:
```
 31:     let test = new Promise(() => {}).finally(() => console.log('test'))
                                          ^^^^^^^ property `finally`. Property not found in
 31:     let test = new Promise(() => {}).finally(() => console.log('test'))
                    ^^^^^^^^^^^^^^^^^^^^^ Promise
```

Is there a clean way to use the promise method `.finally()` (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise/finally) and not break Flow's typing?

In `core.js` I see it's not supported on the `Promise` object: https://github.com/facebook/flow/blob/master/lib/core.js#L591-L610. Is there a particular reason why?

**Comment by idiostruct** [comment]
Does Flow support proposal APIs? You could derive a new class from Promise until it lands in core.js:
 
```typescript
declare class PromiseWithFinally<+R> extends Promise<R> {
  finally<U>(onFinally: () => U): Promise<U>;
}
```

**Comment by saadq** [comment]
It seems like [`Promise.prototype.finally` is stage 4](https://twitter.com/ljharb/status/956229868575846400?ref_src=twsrc%5Etfw&ref_url=https%3A%2F%2Fwww.reddit.com%2Fr%2Fjavascript%2Fcomments%2F7x8z1v%2Fjavascript_promiseprototypefinally_is_at_stage_4%2F). I think this means it is a "finished" proposal and should probably be included now.

**Comment by lll000111** [comment]
Not only is it stage 4, it already is available in the standard release of both Firefox and Chrome, and [Microsoft's ChakraCore has it in the code already](https://github.com/Microsoft/ChakraCore/pull/4668) (just merged into master 3 days ago).

**Comment by coaxial** [comment]
Ran into this as well, `finally` is part of the promise API now, Flow should see it as such

**Comment by dsainati1** [comment]
This is now supported in Flow: https://github.com/facebook/flow/blob/master/lib/core.js#L636
