### ISSUE TITLE
How to declare es-module/custom/path in one place?

### ISSUE THREAD

**Issue by Diokuz** [facebook/flow#5813]
Hi there)

I have a private library, and I want to supply it with flow typings. I already understood how to declare root level imports (just place `[package.json.main].flow`). But it not covers all my cases.

My library may work like that:
```js
import someFunction from 'my-library/lib/someFunction'
```

`lib` directory is generated by babel (es6+flow to es5) from `src` directory before `npm publish`. Also, `src/someFunction` has all typings inside it, but `lib/someFunction` doesnt.

How can I declare all types for `lib/someFunction`? Creating `lib/someFunction.js.flow` for each file is not a good idea, because I have tens of such files.

declaration of
```js
declare module "my-library/lib/someFunction" {
  declare export default T;
}
```
inside `[package.json.main].flow` not works for me either.

**Comment by saadq** [comment]
> How can I declare all types for lib/someFunction? Creating lib/someFunction.js.flow for each file is not a good idea, because I have tens of such files.

I think this is mainly what [flow-copy-source](https://github.com/AgentME/flow-copy-source) is used for. You would basically do something like:

Install it:

```bash
npm install flow-copy-source --save-dev
```

Write a script in your `package.json` for it:

```json
{
  "scripts": {
    "build": "babel src -d lib && npm run copytypes",
    "copytypes": "flow-copy-source src lib"
  }
}
```

**Comment by TrySound** [comment]
If you don't want to copy all files, just reexport entry point from source.
```js
{
  "scripts": {
    "build:flow": "echo \"// @flow\\n\\nexport * from '../src';\" > lib/index.js.flow"
  }
}
```

This probably can be closed.
/cc @vkurchatkin
