### ISSUE TITLE
if/typeof/in type narrowing on union type's uncommon properties

### ISSUE THREAD

**Issue by massimonewsuk** [facebook/flow#5816]
**Code**
```ts
interface Bird {
    fly: () => any;
    layEggs: () => any;
}

interface Fish {
    swim: () => any;
    layEggs: () => any;
}

function Move(pet: Fish | Bird) {
    if (pet.swim) {
        pet.swim();
    } else {
        pet.fly();
    }
    
    if (typeof pet.swim === "function") {
        pet.swim(); // Only this line works
    } else {
        pet.fly();
    }

    if ("swim" in pet) {
        pet.swim();
    } else {
        pet.fly();
    }
}
```

**Expected behavior:**
I expect the code above to work without any errors at all. I feel it's all reasonable.

**Actual behavior:**
I get error for all if/else branches. The only place that works is commented above.

**Comment by massimonewsuk** [comment]
Still an issue in v0.67.0

**Comment by TrySound** [comment]
post code also in [flow.org/try](https://flow.org/try/) please

**Comment by massimonewsuk** [comment]
It's easy to reproduce. Copy/paste into flow.org/try.

Here's the link for anyone that wants it:
https://flow.org/try/#0JYOwLgpgTgZghgYwgAgELCgE2QbwFDKHIwA2AngFzIAUAlMgLwB8ycIZA3AUSXGQKIBzQQGcqdRizac8AXzx5QkWIhQAxYCIAWuboREB3YAFtx9Zq3ZciyXgOFia5qVbkKYAVxAIwwAPYgyACyfgBuENQADhBgVBrayAA+aBiY9Pg2wDA00WAAdIYm6Xo2yLkFRsZ01kSyyBAkIigZpYTlpGTVJfI2JVk0YGTRftnlhcaMDAzIAESe3r4BM8WtbTEVJtXIAPTbyADyIOTIYFqatqAoBn5QANYi3fWNzSU27eRdNvJ92dQz4zNkKAyjEVqsxpVPrUnk1dKsQfkOlDCPJZEA

**Comment by massimonewsuk** [comment]
Still an issue in v0.70.0

**Comment by vkurchatkin** [comment]
Not a bug. `pet.swim` doesn't prove that it is a `Fish`, it could be a `Bird` with `swim` property of an arbitrary type.

**Comment by massimonewsuk** [comment]
@vkurchatkin Have a look at the following example which uses "exact" types instead (so `Bird` shouldn't have the `swim` property of an arbitrary type)...

```
type Bird = {|
    fly: () => any;
    layEggs: () => any;
|}

type Fish = {|
    swim: () => any;
    layEggs: () => any;
|}

function Move(pet: Fish | Bird) {
    if (pet.swim) {
        pet.swim(); // Works fine
    } else {
        pet.fly(); // Works fine
    }
    
    if (typeof pet.swim === "function") {
        pet.swim(); // Only this line works
    } else {
        pet.fly(); // Doesn't work - thinks pet could be a fish
    }

    if ("swim" in pet) {
        pet.swim(); // Doesn't work - thinks pet could be a bird
    } else {
        pet.fly(); // Doesn't work - thinks pet could be a fish
    }
}
```

**Comment by vkurchatkin** [comment]
Yes, this makes sense for exact object, but there is an issue for that already

**Comment by massimonewsuk** [comment]
@vkurchatkin Are you referring to this one? https://github.com/facebook/flow/issues/4772

**Comment by vkurchatkin** [comment]
Yes, but I think there are others
