### ISSUE TITLE
for-in over built-in type ValidityState

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#5823]
I have `const validity = this.input.validity`, where 

- `this.input` is a `HTMLInputElement` 
- `validity` is a `ValidityState`

It throws the following error when I loop over the properties with a `for-in` and try to access the values with a computed property:

```
  141 |
  142 |     for (let key in validity) {
> 143 |       if (!validity[key]) {
      |            ^^^^^^^^^^^^^ computed property
  144 |         continue
  145 |       }
  146 |

Indexable signature not found in

  141 |
  142 |     for (let key in validity) {
> 143 |       if (!validity[key]) {
      |            ^^^^^^^^ ValidityState
  144 |         continue
  145 |       }
  146 |
```

**Comment by idiostruct** [comment]
To use an "[indexer property](https://flow.org/en/docs/types/objects/#objects-as-maps)", ValidityState has to be defined with a `[k: string]: v` signature — [which it isn't](https://github.com/facebook/flow/blob/master/lib/dom.js#L2726-L2737). Here are some solutions for access of computed a property:

```js
if (!Object.prototype.hasOwnProperty.call(validity, key)) {
  continue;
}

if (!validity.hasOwnProperty(key)) {
  continue;
}

if (!Reflect.has(validity, key)) {
  continue;
}
```
