### ISSUE TITLE
Higher order function typing

### ISSUE THREAD

**Issue by demands** [facebook/flow#5824]
Hello! I have a question - I'm not sure it qualifies as a bug report, but it _might_.

I have the following code ([see it in Try Flow][1]):

```js
function higherOrderFn <T> (fn: (arg: T) => void) {
  return function (arg: T) { return fn(arg); };
}

const augmentedFn = higherOrderFn(function () {});
augmentedFn('foo');
```

It is throwing the following type error:

```
6: augmentedFn('foo');
               ^ string. This type is incompatible with the expected param type of
2:   return function (arg: T) { return fn(arg); };
                           ^ T
```

It seems like flow should be able to infer that in this case, `T` is a string. Why can't it?

If I am explicit about the return type of the function ([see it in Try Flow][2]):

```js
function higherOrderFn <T> (fn: (arg: T) => void): (T) => void {
  return function (arg: T) { return fn(arg); };
}

const augmentedFn = higherOrderFn(function () {});
augmentedFn('foo');
```

Then flow is happy. How does it know????

[1]: https://flow.org/try/#0GYVwdgxgLglg9mABACxgc2QUwE4HlsAmOAYkgDwAqAfIgBTBgBcdAhtmsxQJSIC8NANzgwCPAN4AoRImyYoIbElCRYCVu07iZchUrC02aLgG5EAX2MSzEiRAQBnKIhYg0AW0xgomAqT4p0LDxCEn1laHgkWnEzEwkXd09vX30AcmA4OFSTIA
[2]: https://flow.org/try/#0GYVwdgxgLglg9mABACxgc2QUwE4HlsAmOAYkgDwAqAfIgBTBgBcdAhtmsxQJSIC8NANzgwCXZrW59BwgogDeAKESJsmKCGxJQkWAlbtOPOSrUatYWmzRcA3IgC+NhfYUKICAM5RELEGgC2mGBQmASkfCjoWHiEJBba0PBItEb2tgq+AUEhYRYA5MBwcHm2QA

**Comment by vkurchatkin** [comment]
You need to specify the return type: https://flow.org/try/#0GYVwdgxgLglg9mABACxgc2QUwE4HlsAmOAYkgDwAqAfIgBTBgBcdAhtmsxQJSIC8NANzgwCXTn0HCCiAN4AoRImyYoIbElCRYCVu048ZSlWo1habNFwDciAL5W5tuXIgIAzlEQsQaALaYwKEwCUj4UdCw8QhIzTWh4JFoDW2s5bz8AoJCzAHJgODgc6yA
