### ISSUE TITLE
Using Flow for static Analysis in React-Redux app 

### ISSUE THREAD

**Issue by basav22** [facebook/flow#5825]
hello,

I am trying out Flow with React and Redux. So when we use connect API to map props from redux state, I am unable to access them in React Component being connected.

Here is the sample code. How do I access stateProps and dispatchProps using Flow ?
```
// @flow
import React from "react";
import { connect, ConnectedComponent  } from "react-redux";
import type { Connector, MapDispatchToProps} from "react-redux";
import type {Dispatch} from "redux";
type Props = {
    title: string,
    packageCount: number
}
// How to read stateProps from Props ?? 
function ChannelHeaderComp(props: Props) {
    return <div>
        <h2>{props.title}</h2>
        <h2>{props.stateProp}</h2> // showing error
        <span>{props.packageCount}</span>
    </div>
}

type State = {
    persons: Array<any>
}
function mapStateToProps(state: State):Object {
    return {
        person: state.persons[0]
    };
}
type ActionA = {type: "A",payload: any}
function mapDispatchToProps(dispatch: Dispatch<ActionA>) {
    return { dispatchAction: () => dispatch({type: "A", payload: {} }) }
}
const ChannelHeaderConnector: Connector<Props, any> = connect(mapStateToProps, null);
export default ChannelHeaderConnector(ChannelHeaderComp);
```

**Comment by apsavin** [comment]
Well, if you have `stateProp` in your `props` you should specify it in `Props`.

**Comment by basav22** [comment]
@apsavin If we add that `stateProp` in `Props`, that will cause all consumer components to pass that prop as well which I don't want. I can make that prop as optional, but is it the only way around?

**Comment by apsavin** [comment]
No, it should not.
Consumer components will use not `ChannelHeaderComp`, but connected version of it.

**Comment by apsavin** [comment]
But I'm not sure flow is good enough to use it correctly with `redux`.

**Comment by steida** [comment]
@apsavin Don't use Redux. https://medium.com/@dan_abramov/you-might-not-need-redux-be46360cf367 For Context, use https://github.com/jamiebuilds/create-react-context

**Comment by apsavin** [comment]
@steida  As far as I remember I said nothing about Context

**Comment by villesau** [comment]
react-redux libdefs have been rewritten since this, so I assume this is no longer a problem.
