### ISSUE TITLE
Inject prop for component with defaultProps

### ISSUE THREAD

**Issue by Diokuz** [facebook/flow#5826]
[TRY](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8wBhOXOAOzI+IF8wo+NmADk+SjRGZ2RMIQCeOMoxZs8XHgBVFy-oOFiJhKagVKwAWXmt2GwgAUhOAM5gAvI1QBIKHDgAuMA4AVywAIzJ8AG4wYGAwAEliDFdxAEdgjHEAE3ow4OTk1wwOMGyyKApgmAcnZ1ReKPQzZQBBbOyMQgxOChhHOBd3Ty8winxA50J8EoBzJsb0KhgKZ1crG3VuYjIAD0JubNdNzm2AHg21U54Bl3oQAD4R8srq2sHXDwZvHz9AgAZvLx0F5xBxyvgABQAShGoLIhGC+FKZ06ADcHgxCAALFIAOhwdTxvjgvDOwHRDyBDSaqConCmYAQ+AoOCU+GGZ3sgQYvAekIA6iy2WRsic7IFxdttEouQ9oZKrnYZWQuWAAGRgdqdbq9fp1J5uKleZarVwACQA8swwHsDuDjkrzvYNVqOl0ehw+rdnPcnt8vPDwZEYXCTQziEwxvh6Hi4+JGfwPDj8YSPiDA-SOM44DAyHj4LNISJoyI8uNoRn4YjkWAzkLWUoxU6eIw43iE4R+MBjV5gX2lhGwA2Rc3bNthszGyHLuOeJXUHEgnABH48mQqFVnMoumAUnvSi8qjUfWA4FBLNYW4Q6UPdsNQ0a6yOm1LW9G3CWKAAvESxJ6LvEABCBRyNiyhpmEeZYHuziBLu+4cHAySHhUx7vEM55gFazBAA)

So, I have many components with default props like that:

```js
class MyComponent extends Component<MyComponentProps, *> {
	defaultProps = {
		foo: 0
	}

	render() {
		return <div>{this.props.foo}</div>
	}
};
```

Here is prop types. Note, foo is required, but you can omit it because it is in defaultProps:

```js
type MyComponentProps = {
	foo: number; // It is required, but it is in defaultProps
};
```

Now Im trying to create HOC with generic:

```js
const wrapper = <P: {}>(WrappedComponent: ComponentType<P>): ComponentType<P & AdditionalProps> =>
	class HOC extends Component<P & AdditionalProps, *> {
		render() {
			const { bar, ...rest } = this.props

			console.log('bar', bar)

			return <WrappedComponent {...rest} />
		}
	}
```

which have all MyComponent props passed as `...rest`, plus `bar` prop.

Then I try to create wrapped component and use it:
```js
const WrappedComponent = wrapper(MyComponent)

// no foo, because it is in defaultProps of MyComponent
const x = () => <WrappedComponent bar='baz' /> 
// But the problem is: it is not in defaultProps of HOC
```
And I have an error:

```
38: const x = () => <WrappedComponent bar='baz' /> 
                    ^ props. This type is incompatible with
14: class MyComponent extends Component<MyComponentProps, *> {
                                        ^ MyComponentProps
Property `foo` is incompatible:
14: class MyComponent extends Component<MyComponentProps, *> {
                                        ^ property `foo`. Property not found in
38: const x = () => <WrappedComponent bar='baz' /> 
                    ^ props
```

How can I add prop for my HOC using typeflow generics?

**Comment by apsavin** [comment]
[Fixed](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjQgGjAG8wBhOXOAOzI+IF8wo+NmADk+SjRGZ2RMIQCeOMoxZs8XHgBVFZegFEYZLN0KsOUDAHMw-QcLETCU1AqVgAsvNbsNhAApCOADOYAC8jKgAkFBwcABcYBwArlgARmT4ANxgwMBgAJLEGCHiAI5JGOIAJvSpSUVFIRgcYFVkUBRJMP6BQai8meiuygCCVVUYhBicFDABcMFhEZGpFPgJQYT4zZaDA+hUMBRBIZ7e6iZgZAAehNxVIeecJgA8Z2rPPPPBAHzLmxQplRWu1Ot1viFwgwotFYgkAAxRXjoSLiDhtfAACgAlMtUWRCEl8C0XhMAG4-BiEAAWxQAdDhenSYnBeC9gOSfkj+oNUFROJswAh8BQcEp8EsXqgwDLZX4EgxePQAOoisVkKpPXzaJQJLUmHVkF5+H70ADy9Rw9QhCQMRhMZgslheqtFSk1H21Oj+ADIwGMJlMZnNeqgfpjXeqPT4TAlI+79VodNi9Z6DToXhbCFaegsgn9QlzIodjiEABJm5hXW73R5pniZy3W3p-aGRfHojI4vHFgXEJirfD0Okj8SC-jhGn0xl5lHt-kcIJwQx0+CWTEiQciWprbFz-GE4lgF1qhP1-sjuljwj8YBFyLIh8HPtgeMaxPEcLCt1d94xnh7qguSJHAAixLUZBUJ0QTKJMYDFPBLRtB0XS5oscBQB4XjnnyL7XEs3aFseb7RhcPBgIOoSbhQABeIg5H8QF5AAQvUcjUsoM6pIYWDwUECRwQhHBwEUSGgqhEJgBhYAVswQA)
