### ISSUE TITLE
Flow assumes any index access on a string will return a string

### ISSUE THREAD

**Issue by acusti** [facebook/flow#5829]
```js
'foo'[10].toUpperCase(); // passes
```

In the Flow REPL: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjjAF4wAKbAQwFsBTALjAICcBLbAcwEpyAfGFqMA2gEYADAF0AdPjgBVAA7KGbAMI1cDSrwDc6LHjgwGs+N0oBya6Jnylq9Vp16DQA

(Apologies if this issue has already been reported. I did a search through issues and didn’t find anything, but there are a **lot** of issues)

**Comment by SamChou19815** [comment]
This is expected, since we are intentionally unsound with array index access, and string does allow you to array index into characters

**Comment by acusti** [comment]
@SamChou19815 does that mean that #9065 should specifically call out array index access as unsound? or is that issue only for known unsoundness that you plan to resolve?

**Comment by SamChou19815** [comment]
@acusti #9065's intention is to document all the cases where we are **not** intentionally unsound, where we should either explicitly error, or codemods to a better pattern
