### ISSUE TITLE
[feature request] Allow linebreak as delimiter for types/interfaces

### ISSUE THREAD

**Issue by zaynv** [facebook/flow#5830]
TypeScript allows syntax like so:

```typescript
interface PersonProps {
  name: string
  age: number
  title: string
}
```

same thing for `type`:

```typescript
type PersonProps = {
  name: string
  age: number
  title: string
}
```

I know some may not like this style, but it would be nice if it was at least an option in Flow as it is in TypeScript. It's a nice-to-have for people who use the semicolon-less style.

**Comment by donce** [comment]
Totally agree - we're omitting semicolons, so having semicolons only in interfaces looks inconsistent :(
