### ISSUE TITLE
How to only accept keys of an object whose values are a certain type

### ISSUE THREAD

**Issue by kentor** [facebook/flow#5834]
How do I type a function that only takes keys of the object and enforce that the value at that key is a boolean? Trivial example:

```js
const o: { a: boolean, b: string } = {
  a: true,
  b: '1',
};

function toggleBoolean<O: Object>(o: O, key: $Keys<O>) {
  o[key] = !o[key];
}

toggleBoolean(o, 'a'); // should have no error
toggleBoolean(o, 'b'); // should error but does not

```

https://flow.org/try/#0MYewdgzgLgBCBcMDeMCGiBGIQBsCmqYANDBotAE4CWYA5jAL4wC8yAUDGolBQK55EOpRAHIAjCMEMA3GzYAzXmGBQq4GFBC1a+AELZ8hADwB5RCYwArPCoB8ACgQwTJANZ4AnogAkAaU8QprYAlOycIADa7h4AuiwwAISR0TGyDHKa2noGBGCOJCKoIsHSMAD0ZTAQABYgvDgAJjDVqABueDBgIDB4FBQgFGyZOnj6uLn5MCIYxaUVVbX1Tb39FKS8sA0geBCdIFByQA

**Comment by SamChou19815** [comment]
There is no such way
