### ISSUE TITLE
Types not inferred in a in-line function in a conditional

### ISSUE THREAD

**Issue by ocboogie** [facebook/flow#5840]
Example [here](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKpIC4oBEMA8sQQDSZQBGAhgE74ZZZ0Be+AzsPQJYB2AcyoBfdCIDc6dDmgBFAK4APZGiqz8BOQFUAGhSp1GUbnyHipM8PIXLV8RAB8oipZYBmC-gGNgvOPzYABa8nDC0vAA2nAAUAI62SviKygCUali87lDxiQB0sshIKESkBOnMLN4B3FCePqox6UgAfBksWNX8nHCREHmRcIK5ynlGY7RsqVIdkqLi0vW+-oHAIZwAInAQnPzAI0kuiRVUWTkJo4XFJSRkJx1dtag0k1AiqhdKE-QzVTXAdS83kazTalQeNV6-UGw3Y0yoWDmiIWQA).

I expected the function `thisFails` to run without a problem because if `quux.type` equals `"FOO"` then `bar` must be type `{ baz: string }`. There is no way (that I know of) to run `func` and have `bar` be type `string`. If 

This error also occurs with switch statements. I'm assuming this issue persists with any conditional.

The function `thisDoesnt` used a simple workaround. It's odd that flow complains about `thisFails` but not `thisDoesnt `, I would think that the outcome of those functions would be practically the same.

It seems like autocomplete works fine though. See [here](https://user-images.githubusercontent.com/8641243/36370323-7393120c-1513-11e8-9005-aa66dacddf47.png).

I originally came across this problem using Redux reducers. I was trying to use the `map` function in a switch statement. You can see the full example [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgAqAlgLYragC8oA3oqKAHYCGNAXKAM65sFdgHMANKwLUUfdgFcqAI1qS2GTvP4oAJnyWxY0FJ3ZrQFPQKEiJUtHMUrs5wo+W1EAXwDcydFh4BMSkALKwOpQ0dIwsbFw0APx8gsJi5rgyyRxOqlIaWrrZBkYmZlKW2am25mjZCh4uUoT1udjefohEJKAAgjqRMti9AMaZsOwMzFLdsqAARGQAkqEAogBKAPq9ACI78+YahHCcVlGevsizoOsoVLAAbijnw2MUE1NxwSR8iysbm3Wq1CAHkAGqrA75TjHWCnFI2MQdK4hcgUEYAaxeo3Gk1iMxCv2Way2ywAwgBpKHqGEnKzVJGXLqogDKuE4eGxbw++LYsyJ-y2LLIvXWZGpoCOdIRaVEyOZPTZsAwXNxnwJPwWxIBwpBAAUJVK4fTEXKmddVjoKLhVe88dM+YStYLNqsdktxYdaca+F82JYZTUpGx7lbIOjOLi+OFBtEpF55QEcPhrraeVIAD59AZp9iZm53R7PIY4u35yiY3P5tkcm0l7l5thZpUq+u4-OW625zqoTDJ76kF413CkRi9bDYGEAHheAD5OkmgjoUJBNNB8JB5OwGwAKQSRuZD9kjqYAbQAuuJQJwG3xcwBKO9DYekL78eDWkYAC1AO5vuIAOlme8HTYUARk4bRnRJbY9nmHhgzA7AUFweRsEmfcRwAkYJgg3A-wbACjVOe8-DA8DINIP4YKBUEIXgxC2GQ1D0OsA8APDddaB3TJogYWdpGiADLFAABCehGH-O0iO9EiyLAiCoOogFySpBDyKYlC0Iw48UAAqhOAwHihn40CNIsSBf142hhJ0BgJOvQjiJ0EC-XM0BmO00AQSUAArFAxgAyD+AoUR2B3JgvCvayXGYQTaD4GKgJkUAAGpQAARlALxSMYsCE3cjytNYmL5PInKyoopTtS2N0PXgsykOKnT2IMoyYtMtzyIoSzjKEkSJMkpzZJ0WzXLy8jPNYnz-MC4LQvCyLoqGK8pImGTYVOfSIh6iNcVywqCvcqbJlKvKKsQo62GXVd5HXdSNJOtiR3khMvCAA).

I know this is a weird edge case that's probably very difficult to fix, but I thought I would report the issue.

**Comment by darichey** [comment]
The examples work now.
