### ISSUE TITLE
`$DeepReadOnly` for nested object types

### ISSUE THREAD

**Issue by IanLondon** [facebook/flow#5844]
`$ReadOnly` doesn't recursively apply invariance to nested object types, and there doesn't seem to be any way to do this besides making a separate copy of obj `A` that is invariant. I still want the variant `A` around in case I want to mutate it in certain contexts.

It would be nice to have some way to use an object as if it's fully, deeply invariant without needing to declare a separate variant and invariant type for it.
[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPoqKAHaYDOymAJgFzHkWgDaAls6HQE5dKAcwC6LSgFcAtgCNM-NhQC+iEqsQBjWJTqheAEgBKmAIYMA8pWioAPDgB8BVhWp1GLIktCmWARgAmAGY2VQ0QUAA5WFAFflh+GlAmAApEBgA6N3pM02cA9KzaHIzZfICCxAiASV16c1B4bAALUwA3bGQY6VMAa2w8mkx0U35TelA0LFBIBNB+MwYAWh0bRBQMbFq20a5TSmQ8QmNFqxtbUjZsj1AT8zO7IlAI5GauJKFqfluTe+tUUDvKiYTS0GijAFdUDCTDIWL8eKJUDyOBIdicHgsARCMQSGTyRQqBxqZTErQ6PQMbYsba7faHZxeVzFG5M9i+UCBEIqRDhMCvbBxBJJaqNenpbZFdy5ZwAFgllDaUpKZUIAHY1UA)

```js
// @flow
type A = {|
  nested: {
    [id: string]: number
    }
|}

const d: $ReadOnly<A> = {
  nested: {
    a: 123
  }
}

// No errors, since `nested` is not made invariant
d.nested.a = 2
d.nested.b = 222

// Instead we have to make a separate type for read-only

type InvariantA = $ReadOnly<{|
  nested: $ReadOnly<{ // this inner $ReadOnly is necessary to get errors below
    [id: string]: number
  }>
|}>

const dInv: InvariantA = {
  nested: {
    a: 123
  }
}

// the errors I want
dInv.nested.a = 4
dInv.nested.b = 77
```

#### Desired:

```js
// Create a deeply invariant object without a separate type
const dInv: $DeepReadOnly<A> = { nested: { a: 123 } }
```

-----

Related to #5369 

Also the "reverse `$ReadOnly` #5687 would be another approach to the issue of needing a separate variant and invariant type of the same object type, when you want to mutate it. So instead of having `$DeepReadOnly` and applying it to your variant type, you could have some kind of `$DeepReverseReadOnly` that you apply to your invariant type. However with `$DeepReverseReadOnly`, developers would need to include a bunch of `$ReadOnly`s inside their object type declarations which is cumbersome and can introduce errors.

**Comment by sam-n-johnston** [comment]
You can check out this [comment](https://github.com/facebook/flow/issues/5369#issuecomment-383319736) to have a potential solution, until Flow adds this feature.

**Comment by sibelius** [comment]
@mrkev this is a feature request as well

**Comment by mgtitimoli** [comment]
I've just refactor [this](https://stackoverflow.com/questions/48634206/recursively-create-readonly-object-in-flowjs/48810420#48810420) into the following:

```javascript
type PrimitiveValue = boolean | number | string;

type PrimitiveValueArray = Array<boolean> | Array<number> | Array<string>;

type PrimitiveNonValue = null | void;

type PrimitiveNonValueArray = Array<null> | Array<void>;

type Primitive = PrimitiveNonValue | PrimitiveValue;

type PrimitiveArray = PrimitiveValueArray | PrimitiveNonValueArray;

type DeepReadOnly<T: Object> = $ReadOnly<$ObjMap<T, typeof doDeepReadOnly>>;

type DeepReadOnlyArray<T: Object> = $ReadOnlyArray<DeepReadOnly<T>>;

declare function doDeepReadOnly<T: Primitive | Function>(T): T;
declare function doDeepReadOnly<T: Object>(T): DeepReadOnly<T>;
declare function doDeepReadOnly<T: PrimitiveArray>(T):
  $ReadOnlyArray<$ElementType<T, number>>;
declare function doDeepReadOnly<T: Array<Object>>(T):
  DeepReadOnlyArray<$ElementType<T, number>>;
```

**Comment by rickyp-uber** [comment]
Was hoping you two maybe able to help with a union type issue I'm running into. I tried using the solution by @mgtitimoli with a union type and it fails. An example code of this is:
```
type A_NullSuccessful = { foo: number, bar: null };
type A_ObjectSuccessful = { foo: number, bar: { prop1: number } };
type A_ErrorsButShouldNot = { foo: number, bar: { prop1: number } | null };

const a: DeepReadOnly<A_NullSuccessful> = {foo: 10, bar: null };
const b: DeepReadOnly<A_ObjectSuccessful> = {foo: 10, bar: { prop1: 1 }};
// The following error's but shouldn't
const c: DeepReadOnly<A_ErrorsButShouldNot> = {foo: 10, bar: null };
const d: DeepReadOnly<A_ErrorsButShouldNot> = {foo: 10, bar: { prop1: 1 }};
```

Both of you are clearly much better with typing than I am, is there a way to break up the typing of the union?

**Comment by mgtitimoli** [comment]
Hi @rickyp-uber, 

I was having a look to your example and the issue happens because the union doesn't match any of the types expressed in the set of functions used to map, so it tries to use the last one and it fails because that union is clearly not an `Array<Object>`.

I haven't tested deeply, but I belive that adding a "match all the others" functions to the intersections should do the work, so it will be as follows:

```
type PrimitiveValue = boolean | number | string;

type PrimitiveValueArray = Array<boolean> | Array<number> | Array<string>;

type PrimitiveNonValue = null | void;

type PrimitiveNonValueArray = Array<null> | Array<void>;

type Primitive = PrimitiveNonValue | PrimitiveValue;

type PrimitiveArray = PrimitiveValueArray | PrimitiveNonValueArray;

type ReadOnlyArrayFrom<T: PrimitiveArray> = $ReadOnlyArray<$ElementType<T, number>>;

type DeepReadOnly<T0: Object> = $ReadOnly<
  $ObjMap<
    T0,
    // prettier-ignore
    & (<T1: Primitive | Function>(T1) => T1)
    & (<T1: Object>(T1) => DeepReadOnly<T1>)
    & (<T1: PrimitiveArray>(T1) => ReadOnlyArrayFrom<T1>)
    & (<T1: Array<Object>>(T1) => DeepReadOnlyArrayFrom<T1>)
    & (<T1>(T1) => T1) // match all the others  
 >
>;

type DeepReadOnlyArray<T: Object> = $ReadOnlyArray<DeepReadOnly<T>>;

type DeepReadOnlyArrayFrom<T: Array<Object>> = DeepReadOnlyArray<
  $ElementType<T, number>
>;
```

The problem with this approach is that this new function won't do anything with the argument that receives, so it will be your responsability to apply $DeepReadOnly to each of the values of that problematic type (union) to make them read only. So your example will also need to change as follows:

```
type A_NullSuccessful = { foo: number, bar: null };
type A_ObjectSuccessful = { foo: number, bar: { prop1: number } };
type A_ErrorsButShouldNot = { foo: number, bar: DeepReadOnly<{ prop1: number }> | null };

const a: DeepReadOnly<A_NullSuccessful> = {foo: 10, bar: null };
const b: DeepReadOnly<A_ObjectSuccessful> = {foo: 10, bar: { prop1: 1 }};
// The following error's but shouldn't
const c: DeepReadOnly<A_ErrorsButShouldNot> = {foo: 10, bar: null };
const d: DeepReadOnly<A_ErrorsButShouldNot> = {foo: 10, bar: { prop1: 1 }};
```

Hope this help you.

**Comment by mgtitimoli** [comment]
I kept thinking on this while I was having lunch and I came up to this other minimal version that addresses all the cases with the only caviat that for non standard types (unions, intersections, etc), each of them will have to set up manually, but for the other cases (object, arrays, and nested), the following utility type makes them deep read only:

```
// @flow

// Note: We are using $ReadOnlyArray to refine Array generics to allow them to be used with tuples 

type ArrayValue<T: $ReadOnlyArray<*>> = $ElementType<T, number>;

type ReadOnlyArrayFrom<T: $ReadOnlyArray<*>> = $ReadOnlyArray<ArrayValue<T>>;

type ToReadOnly =
  & (<T: $ReadOnlyArray<*>>(T) => DeepReadOnlyArrayFrom<T>)
  & (<T: Object>(T) => DeepReadOnly<T>)
  & (<T>(T) => T); // everything else
      
type DeepReadOnlyArrayFrom<T: $ReadOnlyArray<*>> = ReadOnlyArrayFrom<$TupleMap<T, ToReadOnly>>;

type DeepReadOnly<T: Object> = $ReadOnly<$ObjMap<T, ToReadOnly>>;
```

Enjoy :smiley: !

**Comment by vicapow** [comment]
Okay, I think I found a solution that isn't elegant but might help with this. It works up to N depth (were you can add more to N if you'd like).

````
// @flow

declare function readOnly5(number): number;
declare function readOnly5(string): string;
declare function readOnly5(boolean): boolean;
declare function readOnly5(void): void;
declare function readOnly5(null): null;
declare function readOnly5<E, T: Array<E>>(T): $ReadOnlyArray<T>;
declare function readOnly5<T: Object>(T): $ReadOnly<T>;

declare function readOnly4(number): number;
declare function readOnly4(string): string;
declare function readOnly4(boolean): boolean;
declare function readOnly4(void): void;
declare function readOnly4(null): null;
declare function readOnly4<E, T: Array<E>, R: $Call<typeof readOnly5, E>>(T): $ReadOnlyArray<R>;
declare function readOnly4<T: Object>(T): $ReadOnly<$ObjMap<T, typeof readOnly5>>;

declare function readOnly3(number): number;
declare function readOnly3(string): string;
declare function readOnly3(boolean): boolean;
declare function readOnly3(void): void;
declare function readOnly3(null): null;
declare function readOnly3<E, T: Array<E>, R: $Call<typeof readOnly4, E>>(T): $ReadOnlyArray<R>;
declare function readOnly3<T: Object>(T): $ReadOnly<$ObjMap<T, typeof readOnly4>>;

declare function readOnly2(number): number;
declare function readOnly2(string): string;
declare function readOnly2(boolean): boolean;
declare function readOnly2(void): void;
declare function readOnly2(null): null;
declare function readOnly2<E, T: Array<E>, R: $Call<typeof readOnly3, E>>(T): $ReadOnlyArray<R>;
declare function readOnly2<T: Object>(T): $ReadOnly<$ObjMap<T, typeof readOnly3>>;

declare function readOnly1(number): number;
declare function readOnly1(string): string;
declare function readOnly1(boolean): boolean;
declare function readOnly1(void): void;
declare function readOnly1(null): null;
declare function readOnly2<E, T: Array<E>, R: $Call<typeof readOnly2, E>>(T): $ReadOnlyArray<R>;
declare function readOnly1<T: Object>(T): $ReadOnly<$ObjMap<T, typeof readOnly2>>;

declare function readOnly(number): number;
declare function readOnly(string): string;
declare function readOnly(boolean): boolean;
declare function readOnly(void): void;
declare function readOnly(null): null;
declare function readOnly<E, T: Array<E>, R: $Call<typeof readOnly1, E>>(T): $ReadOnlyArray<R>;
declare function readOnly<T: Object>(T): $ReadOnly<$ObjMap<T, typeof readOnly1>>;

function test1() {
  declare var a: {b: string} | null;
  const readOnlyA = readOnly(a);
  // $ExpectError
  readOnlyA.b;
  if (readOnlyA !== null) {
    readOnlyA.b;
    // $ExpectError
    readOnlyA.b = 'b';
    // $ExpectError
    readOnlyA = null;
  }
}

function test2() {
  declare var a: {b: {c: string | null}} | null;
  if (a) {
    a.b;
  }
  const readOnlyA = readOnly(a);
  if (readOnlyA !== null) {
    readOnlyA.b;
    // $ExpectError
    readOnlyA.b = {c: 'wow'};
    // $ExpectError
    readOnlyA.b = null;
  }
}

function test2() {
  declare var a: {b: {c: {d: number[]}}} | null;
  if (a) {
    a.b;
  }
  const readOnlyA = readOnly(a);
  if (readOnlyA !== null) {
    const b = readOnlyA.b;
    // $ExpectError
    readOnlyA.b.c.d.push(10);
    const d: number = b.c.d[0];
  }
}
````

**Comment by mgtitimoli** [comment]
hm, what would you do this way @vicapow that is not a "type only" solution because you are calling `readOnly` function to get a read only type, and not the way I previously wrote which it only requires you to wrap the type you want to convert it to read only with `ReadOnly`?

**Comment by vicapow** [comment]
That’s correct. It’s not a complete type only solution but maybe it can inspire one. The new idea being supporting this to N instead of infinite.

**Comment by lttb** [comment]
hi! maybe this implementation could fit: https://github.com/lttb/flown/tree/master/src/Frozen

for example, it works well here: https://github.com/lttb/typed-actions/blob/master/src/tests/reducers.js#L60

and you can try it [here](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBiUIC9gDsA8AagHxwC8cAJAErACGAJgPK4A2i+G2eAsnWCihFixAFCikKdJhy4+A4EJLkqAURB0AxjHyUmAIwBW8ogBo4ASVy5FXWSPGhIsBMlRWbUO3nKi4cADI4AAoiAC44A0NgbWJgwgBKclIaemY2Dm85fkFhYgS-QJDwuABBKCg6DjpcRBF4pLIUgBUAVzBWYBNCcw9bGTx8wqDQwgjUxhZ2csrq2vrE5Ko2jq7+M0trfu5cIf8R4QalxML-M7OJNzgADRUs-ABvUQBIOgin8+f9d9PzuGfNBEAEy-c4AX1+YIuYLEogYMVYdCgqAAbki4CAItdQX8cedRCAAHR0Qn6QmaFQAZjgAHoaXBFJgoEA)

**Comment by mgtitimoli** [comment]
Hi @lttb,

The implementation you shared it's very similar to the one I wrote [here](https://github.com/facebook/flow/issues/5844#issuecomment-407169272), with the only difference that it doesn't  support arrays (it only supports objects), and you are applying `$Exact` which I believe it goes outside of the scope of read only.

One alternative to support arrays would be to create a type that uses `$Call` with `InnerFrozen`, and if you go into this direction you would probably end up in what I wrote before :wink:.

**Comment by lttb** [comment]
hi @mgtitimoli, that implementation is more about deep `Object.freeze` (because of specific needs), so that's why it's `exact` and `Frozen` 😄. But you can use `InnerFrozen` for arrays as well: `$Call<InnerFrozen, [{x: number}, {a: {b: {c: string}}}]>`, for example ([try here](https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcBiUIC9gDsA8AagHxwC8cAJAErACGAJgPK4A2i+G2eAsnWCihFixAFCikKdJhy4+A4EJLkqAURB0AxjHyUmAIwBW8ogBo4ASVy5FXWSPGhIsBMlRWbUO3nKi4cADI4AAoiAC44A0NgbWJgwgBKclIaemY2Dm85fkFhYgS-QJDwuABBKCg6DjpcRBF4pLIUgBUAVzBWYBNCcw9bGTx8wqDQwgjUxhZ2csrq2vrE5Ko2jq7+M0trfu5cIf8R4QalxML-M7OJNzgADRVKAGE6VlZ8Pq8B3HMAbQBvEAjcK0ALb6RQAX3MPzoER++hhmgiAGcYFAAJa4ADmYOxAF0xKIGDFWHQoKgAG4kuD-G6nc4XOl00QgL4ARhxADo6Oz9OzNCoAMxwAD0QrgikwUCAA)).

**Comment by vicapow** [comment]
Would anyone from the Flow team be willing to provide context? Is it something FB wants to implement but hasn't had the time? Or is this a feature that should intentionally be left out of Flow?

**Comment by vicapow** [comment]
Hello again,

Friendly bump. Could someone from the core team provide context on this?

**Comment by vicapow** [comment]
cc: @gabelevi, @jbrown215, @samwgoldman, @nmot

**Comment by k2snowman69** [comment]
It's a new year, any feedback? This would be fantastic to have for a redux store structure so that all edits are forced to be spreads...

**Comment by shannonmoeller** [comment]
How about this?

```js
type $DeepReadOnly<T> = $ReadOnly<$ObjMap<T, <V>(V) => $DeepReadOnly<V>> | T>;
```

https://flow.org/try/#0C4TwDgpgBAJAIhCYBKECGATA8gOwDYgA8AKgHxQC8sqmuBhMWARgFYCyaYJANFIQGqkAFPwCUlcvEQp02fEUHkAPlDIBuAFAbQkKAEFKUAN4aoUAJYYAXFBwBXALZMIAJ26moAcxeJg5nJ42AM7ALv6e7gC+mtrg0ABChiZmljb2Tq7uZmg2elExAMYA9jghUAU2Ukg0cvTx5FTJFtZQAIxZUDnGHiktAEwdZt6+4TYA5AASEHh4RVAA6kUueBhjHZH5WgUAdJaGAMyaO2i7GIYALEfbJ8MQfgGGk0V4aGNXaEnRPVAaxaXAUBaVRktHkhHqSQ8qTaHS6TV6NgG3wwrjAIBs+3W+SAA

**Comment by jcready** [comment]
Bump

**Comment by dsainati1** [comment]
Sorry about the delay.

Internally we use a type defined as follows:

```
type DeepReadOnlyFn = (<T>(Array<T>) => $ReadOnlyArray<$DeepReadOnly<T>>) &
  (<T: {}>(T) => $ReadOnly<$ObjMap<T, DeepReadOnlyFn>>) &
  (<T>(T) => T);

type $DeepReadOnly<T> = $Call<DeepReadOnlyFn, T>;
```

**Comment by jcready** [comment]
@dsainati1 this should error but doesn't:

```ts
type tuple = [string, number];
declare var x: $DeepReadOnly<tuple>;
x[0] = 'wat'; // should error
```

**Comment by dsainati1** [comment]
As written the type only applies to arrays and objects. Apologies if this doesn't cover all your use cases.

**Comment by jcready** [comment]
Right, that's why a flow-native (ocaml) $DeepReadOnly utility type is desired. Because a user-land defined type cannot cover all cases.

**Comment by jedwards1211** [comment]
@mgtitimoli unfortunately your simplified version doesn't work as well as your original one, Flow fails to catch some errors it should with the simplified version.

* [Original version that causes expected errors](https://flow.org/try/#0C4TwDgpgBACgTgSwLYOAgbhAagQwDYCu0AvFAEYD2FeEOAdlAD5R0FJkRxNQDOwidAOYBuAFCjQkWIhRpMuQhACCcODhBRSKtSAA8larToA+btvW7W7Tqebm9fAYONiJ4aPGSoMEAHIU6BSJNFgI8PG50CgQAE1dJDxlvTH9A-CJ7EPtLMLxbKGyo2JdxBOkvORJy2R9UoOhmTxr5dIh492rk5VV1EKau+szGpMq61vt2qQAlWhiAeTo8EHsAMTgKJF0AFQAuTsr7U1IAEhmcecXlnr1jgFEaJAg6YC33bYAaUOs4YxK3KQAIhAIGAzhcltsAAx7OZkABWEAAxsAjlBTrMFhDRFA0bC4QBZHBgXTYnFQLaQ96knEAehpUDAcAgwDQnAAtAhBHQKEzqVAAGRQAAU2wAjHt+pVuCsCHRkQgAsYhVtRQBKTSmFWqvmCkUqmHwpEo5VqjVQIEgsGYvQq4zaskC4ViiUjHyHE3q4imK2XVbrTa2+1k3XOgrXXR4o2-D1mi2gjG+65rDZiu06p22mNe8mmulQJA4YCIgAWUHwEWAxegFErnB4OOxxlEfzKcZ9S2yuygkeRqPR52t2TbCYhW1+k2gw4HiZ0yYDe2yPZRqKn4KuOhJOLuDyeLzeW0+Vg4P2brggAA8wDzgFAyltkBAAMqcBAQHgAws4ez10gAb1JwALuGR42FSOLoEBG4gVwzCOAgQjGFSAC+4g0gAVGh2JoVAhJgGA8GCFAABm-pQCW9B0BAEQAJIAreFBltcbJETyBYshAMS3g+vAvm+UAxJ+AB0UAAKo8BxxE8lhUCCMyUAUJAahoAE9aVoWjHQIIBA4GozzApxwAMUywAEHADA6ToPCCVhNKiBeV5wDed4Ps+iBvh+wBftcPC4SE-44gA2nBQgAMLFhRVHUTEezBYIAC6ez3o8rmvu+n7fsh4hEbK8oBFATyIhQMQQNRQhvsAHk4EKAmeXsq7WtsLm8WlnnfrhdpQP+KF2XKRUlWVfCVUK-mSRQewjTigFQAFoqfAATJ8ADMnwAOSVgg9Y8MWFBhJxnDrHAK1xWBZIQdNAAsnwAKyfAAbMdfJkDpewrU9ABeK0nShSHakAA)
* [Simplified version that doesn't cause expected errors](https://flow.org/try/#0C4TwDgpgBAggTnAhiAaogNgVwgHgCoBcUAJAEoSIAmA8gHbojxIg6K0gB8HUAvCQKLoIAWwi1gecLjwAaKLUzCARhDgcA3AChNoSFHJU6DJsgBicAPbD8RMhRr1GCZK3ZdeJAw+POWJ1BjY+FxaOlJQeBZeRiC8mlBQAGRQABQ2UNRKAFYQAMbAHCl4AJS83AAiEBBg0Y6ZOfnBxfFJqel2ho7+rpyFJWVQldW1PszmVk0tyWl4faU83CWhutBDNfYx-uPWhJ4bXb497nwjTmOW1i3EeJhgQgCyiGD4cpGnHJoa2iuDVeudDHqeWA6SB+W4fA63hYxHqj2esgiUX2DBC2ggAA8wBY4MAoD88ABLUQAZVUhIgAGdyohgIh-JSPABvFrAIjdBTKVQcGQtABu7MOnJUcCgAB8oJTgHBCbQAOY8zQAX20AHoAFTq+LqqDwsCyuVQABmFyguQAFmxaBB0FAAJLlfEWKCIXwAWiNOOEtOAEEo+OJ0Ep5KpUEotMQADooABVYP+z1wbVQOUQPEWSBIYCEiy0RnAS1413QOWYV1sX1+p1QOBpzBwWgu3yUyPa1WaTHY3H48JE0kh6kRhnw5ktADaUpl8oAwpbaNb0HbKERJwaALpEPsQMkyqk0ukM3kqzRGzC0fI5xtiXIWSgQO3yqnAfeIFLhulENanMEgrc7imDgezbwhwpQsse163vej5Si+KQsgknoWEQCEJPiRBjgAjHIABMcgAMxyAA5AWhKMpS5oWJg6D+qolhwERa68mhUAClAY4ACxyAArHIABsTEtAkSiukQREiQAXkRzFQCqSrNEAA)

In a lot of complicated type mapping cases like this, Flow seems to just lose track of the types or give up and treat a lot of nested types as `any`.  I've seen TypeScript fail in similar ways.  Over time I've become more and more wary of using `$ObjMap` and function intersection types 😕

**Comment by jedwards1211** [comment]
@mgtitimoli Also now that `Object` is equivalent to `any`, it's probably better to replace it with `{}` in your original types, though surprisingly it seems to work anyway since `$ObjMap` appears to constrain the input type parameter.

**Comment by Athelian** [comment]
> In my trying to understand what [this](https://stackoverflow.com/questions/48634206/recursively-create-readonly-object-in-flowjs/48810420#48810420) code does, I ended up with this other version:
> 
> ```js
> type PrimitiveValue = boolean | number | string;
> 
> type PrimitiveValueArray = Array<boolean> | Array<number> | Array<string>;
> 
> type PrimitiveNonValue = null | void;
> 
> type PrimitiveNonValueArray = Array<null> | Array<void>;
> 
> type Primitive = PrimitiveNonValue | PrimitiveValue;
> 
> type PrimitiveArray = PrimitiveValueArray | PrimitiveNonValueArray;
> 
> type ReadOnlyArrayFrom<T: PrimitiveArray> = $ReadOnlyArray<$ElementType<T, number>>;
> 
> type DeepReadOnly<T0: Object> = $ReadOnly<
>   $ObjMap<
>     T0,
>     // prettier-ignore
>     & (<T1: Primitive | Function>(T1) => T1)
>     & (<T1: Object>(T1) => DeepReadOnly<T1>)
>     & (<T1: PrimitiveArray>(T1) => ReadOnlyArrayFrom<T1>)
>     & (<T1: Array<Object>>(T1) => DeepReadOnlyArrayFrom<T1>)
>   >
> >;
> 
> type DeepReadOnlyArray<T: Object> = $ReadOnlyArray<DeepReadOnly<T>>;
> 
> type DeepReadOnlyArrayFrom<T: Array<Object>> = DeepReadOnlyArray<
>   $ElementType<T, number>
> >;
> ```

Beware that `Function` on this line:
>     & (<T1: Primitive | Function>(T1) => T1)
will catch everything in modern Flow, breaking the other cases.

**Comment by SamChou19815** [comment]
You can now easily write it with conditional and mapped type now, but we don't recommend it, since it has no chance to catch cases when classes are mutating stuff. Also won't work for function types with a function that's mutating stuff under the hood. It just gives you a false sense of deep readonly
