### ISSUE TITLE
FileReader.result is typed as ArrayBuffer instead of string|ArrayBuffer

### ISSUE THREAD

**Issue by quentin-sommer** [facebook/flow#5845]
Expected behavior:
reader.result is expected to be string or ArrayBuffer
https://github.com/facebook/flow/blob/20d47b0407e077c84e1e47e1cb2f9e22aa552075/lib/dom.js#L37

Actual behavior:
Error is thrown on `JSON.parse(reader.result)` saying that reader.result is ArrayBuffer and that `JSON.parse` expect a `string`

Code to reproduce:
```js
/* @flow */

const reader = new FileReader();

reader.addEventListener('loadend', () => {
  JSON.parse(reader.result);
});

reader.readAsText(new Blob());
```
playground sample: (not working because it can't find FileReader and Blob)
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzACcBTAQwBMSiwBeMbEpAMQEsYSAlcqogCgCUAbnSlK1AHSUKAUQBuJbPgAyrAoup8A5PHHYKWgDRhBdAHxgA3qjBgAUgGUA8gDkJABzJFcJPmN4SpLgArjD4wqgAvhGo-pL+AIK4ACokAB74fIxIAELwAEaCwkA

**Comment by quentin-sommer** [comment]
Someone pointed that I should be checking the type of the result like

```js
if (typeof reader.result === 'string') {
  return resolve(JSON.parse(reader.result));
}
```

**Comment by eMarek** [comment]
Is there any specific reason for it? Can `reader.result` be something else than string?

**Comment by quentin-sommer** [comment]
Depending on the method you use on the FileReader to read it can indeed be various types: https://developer.mozilla.org/en-US/docs/Web/API/FileReader#Methods

**Comment by eMarek** [comment]
Obviously. Thanks.
