### ISSUE TITLE
Type incompatible error when using optional properties in interface

### ISSUE THREAD

**Issue by chrisirhc** [facebook/flow#5851]
[Link to flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gAaYA3qmGEQPwBcYAztvlgOaoC+AblTYAngAdyATTABeGnQYt2nHvyGoScTBzAiwraXNr0irAORF8HM2tSpgwMAFF8+OFbBwArtjAALAlxUAAo9VgoASgEgA):
```js
/* @flow */
interface X {
  a?: string
};
type Y = {
  a?: string
};

const y : Y = {
  a: 'arst'
};

// Errors out here
(y : X);
```

Error:
```js
14: (y : X);
     ^ Cannot cast `y` to `X` because undefined [1] is incompatible with string [2] in property `a`.
References:
6:   a?: string         ^ [1]
3:   a?: string         ^ [2]
```

There are no errors when `a` is made not optional ([link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gAaYA3qmGEQFxgDO2+WA5qgL4DcqbAE8ADuQCaYALw06DZmw6Zu-VKhJxMbMELDNJM2vSZgA5EXxtTvAamDAwAUXz44lsHACu2MAAsCuKgAFLrMFACUfEA)).

It might have something to do with the variance of the property since setting `a` to write-only [works](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gAaYA3qmGALRED8AXGAM7b5YDmqAXwDcqbAE8ADuQCaYALw06YFuy49M-YalQk4mLmDFh2shbXpF2AciL4uVwSNTBgYAKL58cO2DgBXbDAACwJcVAAKI3YKAEohIA), though read-only [doesn't work](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gAaYA3qmGANRED8AXGAM7b5YDmqAXwDcqbAE8ADuQCaYALw06YFuy49M-YalQk4mLmDFh2shbXpF2AciL4uVwSNTBgYAKL58cO2DgBXbDAACwJcVAAKI3YKAEohIA) (which I imagine is more important for most users).

**Comment by zone117x** [comment]
This makes optional properties inside interfaces essentially unusable.

**Comment by chrisirhc** [comment]
Bumping this back up, in case it got forgotten.

**Comment by ammanvedi** [comment]
bump

**Comment by SamChou19815** [comment]
It now works
