### ISSUE TITLE
Support for conditional $ObjMap

### ISSUE THREAD

**Issue by villesau** [facebook/flow#5852]
react-refetch has following kind of interface:

`const Connected = connect({myData: {url: '/url'}, refreshMyData: (somethingFromComponent)=> ({myData: {url: '/url'}})})`

Connected component gets `myData` as `PromiseState` object which represents promises state. refreshMydata is passed to component as callback, which refreshes the data. If everything would be transformed to PromiseState the problem would be trivial to solve with $ObjMap. But in this case the resulting type depends on object value: In case of object it's shows as different object for component and in case of function it's ~almost the same function passed to component.

This would be possible to solve with type level conditions. As far as I know, it's currently not possible to write this kind of libdefs for Flow. I'm glad to be proven wrong though!

See https://github.com/heroku/react-refetch/blob/master/docs/api.md for details

**Comment by villesau** [comment]
```
type Mapper =  (<T: Object>(val: T) => {a: number}) & (<T: Function>(val: T) => T)
$ObjMap<T, Mapper >
```

Above kind of works, but the function interface is lost.

**Comment by miyaokamarina** [comment]
@villesau, type-level conditions may be simply written as here: https://gist.github.com/miyaokamarina/934887ac2aff863b9c73283acfb71cf0. Maybe you'll find it useful.

**Comment by minedeljkovic** [comment]
Extremely interesting @miyaokamarina !

It seems it doesn't work with recursive usage of $ObjMap, though. :(
https://flow.org/try/#0C4TwDgpgBAJAkgMwDwA0BcUBGB7bAbCAQwDsAaKAFQAsIyoBRPAZ2gF4oIBbMUAPinYwAwoTx4kAKCjSoAMigAKBcABOAVwjlqtcoxYBKAf23F9UmfKUJRLLTTp6Ih1v0f7S56Sg8zK9nzKOHrwA3BISoJCwAOLAEKjkAJr8giJikr6WMADKapiR8Sgp-KoaZpmKnACWAB4QACZGUNbMTgHSicFhEeDQcEwAcmqcmBAqqCkxcUjEw6Mq5EVhBVD9APKYAFYQAMbAEwJT8Rvbe4uhPVEU2ACMAEwHgogZq4NzYxMBNwHwyJ6vJ12+yK7SgJ2u90+-zuvAuK3Btwea0mMBOAFlCGAkGtyEgAGq8BR45zGRH42Hdeq7PCEFTQAButKgAHMMBCHrMRmMLgpWVAbvoQr4JAB6ABUUCYVGwajwjTGKmwKigYpFij5d0F4SpOxpdKgjOV2DZZIA3lBCBgmKoqsRmeRMBhOfMoABfULChTGqDmy1QO4OjA3N1a8WS6Wy+UqRXK1WKb0CsJhqUyuUcaNKrBqYBQerYCBMYgAcmAAEIVWqvRhfUHA-6Q2EgA

I would be very grateful  if someone would explain me why it doesn't.

**Comment by abonander** [comment]
I have a similar need for conditionals in `$ObjMap` but the condition I need is that some keys may be optional. Essentially, I have two object types and I want to enforce that only some keys in the first type be present in the second, conditional on the types of those key's values in the first object.

It seems that `$ObjMap` could support this by having the function return `void` for optional keys but it doesn't currently; the returned type still requires all the same keys as the input type.

**Comment by robatwilliams** [comment]
> It seems it doesn't work with recursive usage of $ObjMap, though
> I would be very grateful if someone would explain me why it doesn't.

#4776 "Flow does not report type missmatches with recursive types that use $ObjMap" ?

**Comment by hurrymaplelad** [comment]
Here's an example that seems to work with recursive `$ObjMap`:
https://flow.org/try/#0JYOwLgpgTgZghgYwgAgOpTgBwEoQQVygGdgA3FAbwChlkAeANQC5kKBfAPgAoGBKFigB8A7iwAkAUQAeiMHTEB5AEYArALJZGAGjQYceQiXIcOgtgG4a9ZshD4AtkujJByImCigA5tz4sGlmxUVGAAnpgo6JoAKhzIALzIYgDCcAA2aXRR+gTEZBA6sZZUCAD2IO7IUizZdEJWMKWlAoJWtEpwUC1ttMgdAF4sdo7OPWbIVmZUZnGJVBSirI3NE7QLTBQdXT3rm3CDAIxsQbTHVMfFVEA

**Comment by SamChou19815** [comment]
We now have conditional and mapped type
