### ISSUE TITLE
Exact property isn't kept by $ObjMap

### ISSUE THREAD

**Issue by julienw** [facebook/flow#5853]
```javascript
type ExtractReturnType = <R>((...rest: any) => R) => R;
    
function func1() {
  return 3;
}
    
function func2() {
  return 'foo';
}
    
const o = {
  func1,
  func2,
};
    
type ReturnValues1 = $ObjMap<$Exact<typeof o>, ExtractReturnType>;
type ReturnValues2 = $Exact<$ObjMap<typeof o, ExtractReturnType>>;

type ReturnValues3 = {|
  func1: number,
  func2: string,
|};

({
  func1: func1(),
  func2: func2(),
  foo: 'bar'        // NO ERROR [KO]
}: ReturnValues1);
      
      
({
  func1: func1(),
  func2: func2(),
  foo: 'bar'        // ERROR [OK]
}: ReturnValues2);
        
({
  func1: func1(),
  func2: func2(),
  foo: 'bar'        // ERROR [OK]
}: ReturnValues3);
```

[Live try example](https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwBVxoBeKAHgwD4AKWgOicQgGdgAuKZfEASiilqUDAKEiA3ACgosqFIBmOfOgCWAe3xQlKgIy0BAbxlQWuAlADM0gL4nZi5Ws3anAJgNRjss3i0ByBXV1f1t7eVRNdih1QS8THVRdABoE91SbaTl5UEgRbD8ANWQAGxw2XTiAEgB5ACMAKwBZZDAKKvg0YApciHUFGOpk2AQUdCxzIhJqaV78yeKytjdqzvR2+ubWnpJ+mOH4JC6Jv2JIahmpKTmTgkXy1ks4wwAfNL0ufBwAWzqIRFSskSbi47EQqnwAHNUi9MldaN5XB8kUkDICUSCMWiEsEuP46shEP5stkAPSkqAAORqsAwGBqGCgAG0ANI1AC6UhsXFu+HuFT4WRJ4QcCPeSS4iX0fHRwMl7mxQNxUHxhOJJNk5Np9MZTJqLM53PmRVKDzcgpFcikYqBTl08r0ioxDtQHhlOPUeIJRI1mopMDpDOZ+sNPIKd1NbEsgqAA)

What's especially strange is that when clicking on `ReturnsValue1` line 28, Flow Try actually gives an exact type in the status bar.

**Comment by migueloller** [comment]
Here's [another example](https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPgKClAZggLigAoBKZAPigHJ85qAabKAIwEMAnIsym9jxpnQBfANyZMAYzgA7AM7A8hKABIA8iwBWAWTZgAPPDgMo+gEoViPJFTPkbUC8jTM6RWgkE5+7-l6gA9AGqAKIAHpCSwCEcHHBcUADCbDIycIpscnIAlgDmMlBwWhBRUAA22cAQHGxlUMCIAAZ0jawlbACuctBgcZAcoFCN7ABerdlyUAC2EzkyuVDZBUWaJYqgkFAA2gCMALqsHYoQYRPAk0uFxaUVVTV1WwBMewB0UMyjvmwjgmKYQA).

**Comment by goodmind** [comment]
```
// @flow

type Foo = {| a: number, b: number |}

type Bar = $ObjMap<Foo, <T>(T) => T>

const foo: Foo = {} // error
const bar: Bar = {} // no error
```
