### ISSUE TITLE
[BUG] 3 lines of JS  => constant ~1min time to start flow + slow reload

### ISSUE THREAD

**Issue by rvion** [facebook/flow#5856]
flow constantly takes ~45sec to ~1min to load the following 3 line library:

```js
declare interface AAA { aaa: Element }
declare interface BBB { bbb: Element }
declare interface BUG extends BBB, AAA {}
```

then, it succeeds without error.

📝  __it is possible to reproduce the bug with other constructions, (without interfaces or extend)__, 

🔴 see https://github.com/facebook/flow/issues/5858#issuecomment-368471646 where the bug is affecting the `lodash` lib for example, which takes __40__ times longer to load because of this bug, without interface nor extends

# Repro

I made a repository with a minimal example to ease reproduction.
The Readme contains a detailed explanation.

https://github.com/rvion/flow-lib-loading-taking-forever

I can't reproduce on tryflow because minimal examples I have to reproduce the bug need Element or Event to be available.

:memo: I came across this bug while testing my ts2flow converter that generates flow libdefs from *.d.ts files. The initial case was with a [3000+ lines libdef](https://gist.github.com/rvion/bd2c65d26b38a02186708ad7d9b6dc38) generated from [pixi.js.d.ts](https://github.com/pixijs/pixi-typescript/blob/v4.x/pixi.js.d.ts) and flow was also taking ~1min to start.
:memo: this large file can also serve as a more complete repro case.

in a few words:

```
./node_modules/.bin/flow ls --explain
ImplicitlyIncluded    /Users/rvion/dev/repro/package.json
ImplicitlyIncluded    /Users/rvion/dev/repro/package-lock.json
ExplicitLib           /Users/rvion/dev/repro/lib.js
ConfigFile            /Users/rvion/dev/repro/.flowconfig
```

```
[...]
[2018-02-21 22:41:41] Initializing Server (This might take some time)
[...]
[2018-02-21 22:41:41] version=0.66.0
[...]
[2018-02-21 22:41:41] Loading libraries
[2018-02-21 22:42:27] Resolving dependencies
[...]
[2018-02-21 22:42:28] Checked set: Focused: 2, Dependents: 0, Dependencies: 0
[2018-02-21 22:42:28] Server is READY
[2018-02-21 22:42:28] Took 46.600281 seconds to initialize.
[2018-02-21 22:42:28] Status: OK
```

**Comment by rvion** [comment]
also reproductive with 

```js
declare interface AAA { aaa: Element }
declare interface BUG extends AAA, AAA {}
```

**Comment by rvion** [comment]
this bug is affecting real people from some time: https://github.com/facebook/flow/issues/5858

**Comment by awilkins** [comment]
This seems to be the case in [the testcafe](https://github.com/flowtype/flow-typed/issues/2156) typedefs which have a lot of interfaces composed of extending other interfaces.

**Comment by awilkins** [comment]
Patched the testcafe defs to [use intersections](https://github.com/flowtype/flow-typed/pull/2163) rather than multiple-extend interfaces.

This seems to have no ill effects in terms of function and removes the load time penalty.

**Comment by gnprice** [comment]
This issue can be closed, because the bug has been fixed.

Specifically, I don't reproduce the issue with a current version of Flow (from main, v0.163.0+), either in the original form or the reduced form here: https://github.com/facebook/flow/issues/5856#issuecomment-368333258

Instead, we get the expected behavior: `flow check` returns quickly (<1s), and it gives errors when you use the type `BUG` incorrectly and not when you don't:
```
(b: BUG): Element => b.aaa;  // ok
(b: BUG): Element => b.aaaa; // error
(b: BUG): string => b.aaaa;  // error
```
