### ISSUE TITLE
$Values does not work on opaque types in same file, reports 'any'

### ISSUE THREAD

**Issue by ghost** [facebook/flow#5857]
[try flow](https://flow.org/try/#0MYewdgzgLgBNCGUCmMC8MDeAoGMDkADHgFwwEA0O+AjCTNZbngEx3OUC+A3FlkgB4AHEACdYIQfACOAVxRQAnoJQBlKIhToAJADV4AGzkQAPIuUgAZnHXIAfDwHCxMM6ptJmaGLoNHTSpEtrDVteUEhYCxAQUjUNLwAKAEo0W0xuLHDoGAAjeBFY9090ZNT0riA)

```js
const state = {
  '0': 0,
  '1': 1,
  '2': 2,
};

export opaque type State = $Values<typeof state>;
export type State2 = $Values<typeof state>

const foo: State = () => {};
const bar: State2 = () => {};
```

`foo` doesn't complain here because `State` = `any` whereas `State2` = `0 | 1 | 2`

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
