### ISSUE TITLE
Files skipped intermittently

### ISSUE THREAD

**Issue by ajs139** [facebook/flow#5860]
Sometimes the files are being checked and have their errors reported, other times they are ignored by Flow (even though the file is still present in the list from `flow ls`). If a file that is prone to not being reported ever stops being ignored (which seems to happen if a file it depends on generates an error), any change to the file (such as adding an empty line) will causes it to disappear from the the output.

This behavior is seen even for isolated errors:

```
18: const foo:number = '';
                        ^^ string. This type is incompatible with
 18: const foo:number = '';
               ^^^^^^ number
```

This was introduced in v0.57.x, and was not a problem in v0.56.0.

**Comment by kogai** [comment]
You might seek #5180 or #5850

**Comment by ajs139** [comment]
Thanks @kogai -- #5180 looks like it's exactly the problem I have.
