### ISSUE TITLE
Flow does not check overriding value after rest/spread operator, same goes with Object.assign

### ISSUE THREAD

**Issue by andiwinata** [facebook/flow#5861]
If this is a bug, please try reproducing using https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgAKcAlgHYZgC8YA3mAB4BcYZArgLYBGeATgDRgsLdtz5gAvgG50AYzhkAzpRwBGFsXKUa9ZmFUAGQcP0HJM+UpUAmFgEMyWanQDkvBwBM4HFy1XWAZgAWQRccO3cfFhcACzwYeBdjFgB2aTkFZTAcDDxldSJSCmd6ADpytWSwWPjE8zBgYDA+XjheMAAKeV5ePFkMAEoMq2zc5VtCrRKwctKcayqahLgXesbWOGaets6EVrIAcyHLLJy8jACNIu0wAHkuACs+jFK7RUUSA7IO2glBecE9BMSzqEgGDSaZE2LTaHT2CiOqCAA

Consider below scenario:

```javascript
type Point = { x: number, y: number };

const p1: Point = { x: 10, y: 10 };
const p2: any = {'random': 1234, y: 7};

const ptest1: Point = { ...p1, y: 'hello' }; // error (correct)

const ptest2: Point = { ...p2, y: 'hello' }; // no error (wrong)
const ptest3: Point = Object.assign({}, p2, { y: 'hello' }) // no error(wrong)
```

flow simply ignore the check for `y` after we're spreading `...any` type, and I don't think this is correct. 

Since `y` is declared as the last value in destructuring, flow should check if `(y = number);` and throws error if the last `y` value is not `number`

**Comment by anru** [comment]
@andiwinata it's expected behavior. `any` allows everything and disable type checking.

If you want any type and save type checking you should use `mixed` type instead, see https://flow.org/en/docs/types/mixed/

**Comment by andiwinata** [comment]
ah you're right, it is showing the error correctly if I'm using `mixed` for `p2` in sample above.
Thanks @anru, will close this issue then
