### ISSUE TITLE
Issue with following through boolean logic

### ISSUE THREAD

**Issue by benjie** [facebook/flow#5863]
```js
function main(): { foo?: string } {
  const firstCondition = Math.random() > 0.5;
  const secondCondition = Math.random() > 0.5;
 
  const foo = firstCondition ? "blah" : null;
  const addFoo = firstCondition && secondCondition;

  // If addFoo is true, then both firstCondition and secondCondition must be true.
  // Thus if addFoo is true then foo must be a string and cannot be null.
  // However Flow complains it cannot coerce `foo` to a string below.

  return {
    foo: addFoo ? `foo = '${foo}'.` : undefined,
  }
}
```

raises

```
13:     foo: addFoo ? `foo = '${foo}'.` : undefined,
                                ^ Cannot coerce `foo` to string because null [1] should not be coerced.
References:
5:   const foo = firstCondition ? "blah" : null;
                                           ^ [1]
```

Here it is in flow.org/try:

https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYzACgJQC5EDeiwccA-PgM5QBOGA5ogL6EBQiiEC1xMN1AYQQATGLASIAvIgCyqKAAsAdDVRhhcZDkQA+RAAYlAVgDc7TtyiJKAUy7qh6sfCTS5ilWo1bsug8bNEc3seEjgpXn4oR1FxJDJEACIAIwAbVAVExHwwEFTUwIswHlRhYQAxUgjgPkERZwkAMkbrOxEYhrAzcwB6HsQASWBEUoqqmEpEWhAbABophRskZLhFSLqnOJH1VvthDq3kEB5kmymaGaVe-oAVBWPEGGHRyvCJ85mFpeIqo5Oz1DWWgMbbCThqMCrRCnRC5fJXDh9RAACTgAHcbAA3Gw0RDlVLoizIAAO6QwkzE4LAkKsXBxEDOAAMwoypuFAdQ6GBGKcCWiruYaDYoCAaEgCOYOGF8C8qglmVVpAByAAkBDCTCVSlZ+HAwhsNTANmEs3MTFYTCAA

**Comment by idiostruct** [comment]
Maybe types cannot be used in template literals regardless of the code path: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVpK0ctqDGcAdgM4AuYUccAXGAPzkBOAlkQOZgC8YARAEYwAhgAteAblQADACQBvKnAC+UoA). Either cast to a string, or type as a string primitive:

```js
//-- foo : ?string
`foo = '${String(foo)}'.`
```
```js
//-- foo : string
const foo = firstCondition ? "blah" : "";
`foo = '${foo}'.`
```

**Comment by benjie** [comment]
Interesting theory, but [simple string concatenation](https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYzACgJQC5EDeiwccA-PgM5QBOGA5ogL6EBQiiEC1xMN1AYQQATGLASIAvIgCyqKAAsAdDVRhhcZDkQA+RAAYlAVgDc7TtyiJKAUy7qh6sfCTS5ilWo1bsug8bNEc3seEjgpXn4oR1FxJDJEACIAIwAbVAVExHwwEFTUwIswHlRhYQAxUgjgPkERZwkAMkbrOxEYhrAzcwB6HsQASWBEUoqqmEpEWhAbABophRskZLhFSLqnOJH1VvthDq3kEB5kmymaGaVe-oAVBWPEGGHRyvCJ85mFpeIqo5Oz1DWWgMbbCThqMCrRCnRC5fJXDh9RAACTgAHcbAA3Gw0RDlVLoizIAAO6QwkzE4LAkKsXBxEDOAAMwoypuFAdQ6GBGKcCWiruYaDYoCAaEgCOYOGF8C8qgkAORhCIAHXl8sQAGofuEtfLVUp1fhwMIbDUwDZhLNzExWEwgA) has the same issue.

**Comment by idiostruct** [comment]
That is correct, because a `string` cannot be concatenated (coerced to a string) with a Maybe type.

**Comment by benjie** [comment]
Okay, but what I'm saying is you can't cast the variable to a string from a maybe string even when the conditions are met and there are no function calls to confuse Flow; e.g.

```js
function main(): { foo?: string } {
  const firstCondition = Math.random() > 0.5;
  const secondCondition = Math.random() > 0.5;
 
  const foo = firstCondition ? "blah" : null;
  const addFoo = firstCondition && secondCondition;

  // If addFoo is true, then both firstCondition and secondCondition must be true.
  // Thus if addFoo is true then foo must be a string and cannot be null.
  // However Flow complains it cannot coerce `foo` to a string below.
                  
  if (addFoo) {
    const foo_string: string = foo;
    return {
      foo: 'foo = \'' + foo_string + '\'.',
    };
  }
  return {};
}
```

https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYzACgJQC5EDeiwccA-PgM5QBOGA5ogL6EBQiiEC1xMN1AYQQATGLASIAvIgCyqKAAsAdDVRhhcZDkQA+RAAYlAVgDc7TtyiJKAUy7qh6sfCTS5ilWo1bsug8bNEc3seEjgpXn4oR1FxJDJEACIAIwAbVAVExHwwEFTUwIswHlRhYQAxUgjgPkERZwkAMkbrOxEYhrAzcwB6HsQASWBEUoqqmEpEWhAbABophRskZLhFSLqnOJH1VvthDq3kEB5kmymaGaVe-oAVBWPEGGHRyvCJ85mFpeIqo5Oz1DWWgMbbCThqMCrRCnRC5fJXDh9RAACTgAHcbAA3Gw0RDlVLoizIAAO6QwkzE4LAkKsXBxEDOAAMwoypuFAdQ6GBGKcCWiERxBULhYLzE9EJgXqRfARzBwQlYwgB9TkMKjA7nVUiFDg0GxQEA0JCykVhfAAcjCEQAOubzYgANQ-OAqjWMJ3m21Kc2zOXMQpMcx6g1GwhMbpMIA

**Comment by idiostruct** [comment]
`foo` could be null, thus it will always be a Maybe type (types don't change based on value):

```typescript
const condition = true;
const foo = condition ? "blah" : null;

//
// `foo`'s type, Maybe type, doesn't change even though
// the condition is true and its value is "blah".
//
if (condition) `${foo}`; // Error.
```

I apologize if I'm not understanding the underlying question; it's early in my timezone.

**Comment by benjie** [comment]
So the only way to solve this is to add additional redundant checks? e.g.

```js
function main(): { foo?: string } {
  const firstCondition = Math.random() > 0.5;
  const secondCondition = Math.random() > 0.5;
 
  const foo = firstCondition ? "blah" : null;
  const addFoo = firstCondition && secondCondition;

  // If addFoo is true, then both firstCondition and secondCondition must be true.
  // Thus if addFoo is true then foo must be a string and cannot be null.
  // However Flow complains it cannot coerce `foo` to a string below.
                  
  if (addFoo /* ---> THIS */ && typeof foo === 'string') {
    const foo_string: string = foo;
    return {
      foo: 'foo = \'' + foo_string + '\'.',
    };
  }
  return {};
}
```

even though we know that if `addFoo` is true then `typeof foo` is always going to be `'string'`?

**Comment by idiostruct** [comment]
Alternatives to the typeof check: use an [empty string](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBbAQ0OwAoBKALjAG8wo44B+JgZ3wCdqAczABfFqjBhcJPm0L8+AYRIATQkRJgAvGACyFfAAsAdPwrZVcMvTAA+MAAYTAVgDck6bPxgeAUxlLFUsNYlJdA2MzCysbOnsnVw8wT2A0KTSwADk4cjh+PzBsTBgYE1T0r2w5dlzdKAVlNVCtTjAAIgAjGAojdrAmdvbkqrkKVVUAMQ4deUV8YPVNUgAyFd8AtUWW7BGpfYPDqU8C-Ex+UmZPKVqmcamZtoADWtmAcgASZlrRN5MngZgHCqPwNbB+VQAGk8olQoiAA), instead of null, as the right-most ternary operand or [cast](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBbAQ0OwAoBKALjAG8wo44B+JgZ3wCdqAczABfFqjBhcJPm0L8+AYRIATQkRJgAvGACyFfAAsAdPwrZVcMvTAA+MAAYTAVgDck6bPxgeAUxlLFUsNYlJdA2MzCysbOnsnVw8wT0C5djgdeUV8YPVNUk4wACIAIxgKI2KwJmxMGBhkr2w5ClVVADEOLKgFZTVQrQAyId8AtTzB7CapWbn5qU9+P3xMflJmTylgNDmdsCUKdO78TIpfAWEAGjA-ADc-UmM4TCEjMA0Ach4wc75BbBCExbMA7EEZJhtTrdIoAAwyWU+ABJmABlS6AmgZOiiT4mWE1MA4VR+XrYPyqK6eUSoURAA) `foo` to a string.

**Comment by wordofchristian** [comment]
I have this same problem when I want to pull the condition of an if statement out into a variable (usually for the purpose of re-use or to add clarity).

```javascript
function doSomething(values: ?string[]) {
  const looksGood = values && values[0].length > 0;
  
  if(values && values[0].length > 0) {
    return values.slice(); // this works
  }
  
  if(looksGood) {
    return values.slice() // this fails
  }
}
```
[TryFlow](https://flow.org/try/#0FAhmFcDsGMBcEsD2kAEATRBlRBbAprABbyQDmAFAG4CGANuHgM4BcKA-I7AE4mkDaAXQCUKAN7AUKaMk4paiRAGtGAcQVoUAXhQ16TFADIDOug0Z8ADAIB0tPGSIoAfCgsBuCSk-xQVU-qMTPXMrW3tSRxcLEXFJSS4CcC5UXTNrRlp4aDxyITcUAHoClCJ4RhQAd0QuZU8AX09vX3klVXUYz3jE5KC0jKyckSKS4nLQanhaRnrgOqA)

What is the recommended approach for getting around this error?

**Comment by stereobooster** [comment]
@wordofchristian 

```ts
function doSomething(values: ?string[]) {
  if (!values) return;
  ...
```

**Comment by wordofchristian** [comment]
@stereobooster Yeah that works. I suppose you just have to write your functions in a way that if a type guard fails the function has to return or throw or some other thing that ensures there is no continuation.

**Comment by SamChou19815** [comment]
This is expected since Flow won't try to prove some refinement still holds in arbitrary code. Only a limited set of patterns are supported.
