### ISSUE TITLE
[question] Type Props for basic JSX elements

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#5865]
Are there any packages that define the [list](https://reactjs.org/docs/dom-elements.html) of props that a react JSX element can take?
We would like to type our components as exact, but it's a pain to manually list all of these.

**Comment by cprodescu** [comment]
These should also be listed in the `props` sections of `$JSXIntrinsics` definitions in https://github.com/facebook/flow/blob/60e640c2287c2e7b9d0f261e4c8a617763005f1e/lib/react-dom.js#L246

A few questions for the friendly maintainers (cc @samwgoldman):
- Are there any plans on this on the roadmap?
- Is this something you would accept PRs for or do you prefer `flow` react-dom bindings to remain unopinionated about `props` of JSX intrinsics?

**Comment by motiz88** [comment]
Essentially a duplicate of https://github.com/facebook/flow/issues/3773

**Comment by goodmind** [comment]
Duplicate of #3773
