### ISSUE TITLE
Resolve reflection for static methods

### ISSUE THREAD

**Issue by Heliodromel** [facebook/flow#5875]
Hi,

I need to do some reflection with static methods of a class but i'm running into this error : "an indexer property is missing in statics of `MyClass` "

How can i solve this ?

Here is the [flowTry](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAWQE8BhHfMAb1TDFwBdsGBLDMAW2IGUnWNCAUwYALOABMAFAEoAXPQYAnFgDsA5tVp0wi4QFdFKsACIMcODDABCYwG4tAX1RPMcFY07Cx4gHLYOgvKMyupgALwmXLzMbEKiEnau7gw6grh6MAxBSqoaESTkeLgA2gHxvv6CALoy9kA)

**Comment by haxxxton** [comment]
Noticing a similar error when calling a variable named method on a class instance : "an indexer property is missing in `MyClass`"

Here is the (slightly altered) [flowTry](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAWQE8BhHfMAb1TDAFtiBlAF2xYEsNCBTFgCzgATMAF4wACgCUALjC4WAJw4A7AOZiAfNVp0wivgFdFKsACIMcODDABCMwG5dAX1SvLKhQz6ChAOWx6HlZldTFzRlZ2Ll4BYUd0Dy9VBWwVDB5wlR4kEnI8XCdMOE8WfR5cQxgWOQVQjXEUtnSeAG0guP9A4KVVNQBdaQcgA)

**Comment by doshisid** [comment]
I am facing the same issue. Is there any temporary workaround this?

**Comment by beeant** [comment]
Me too... At first, I thought this is amazing, flow even checks and recognize the property of object declared in other files. But how can I resolve this error?
I'm trying to loop an array of classes to call a static function of each class with the same name, only if the class has that static function.

**Comment by SamChou19815** [comment]
This is intentionally unsupported
