### ISSUE TITLE
Intersection between $Shape and regular object generates false errors

### ISSUE THREAD

**Issue by anru** [facebook/flow#5879]
[TRY](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AIQIYDOOAvKAN6KiiEBcNKATgJYB2A5gDRWiv2sBXALYAjLI24BfZOmygAKqDKVqAD37CxjRJNAAyUABIAygAt82ADwFiAPmQBjWK0IpQKeouU86oAOQAJpDsftxq9ACMAMxRUkA)

```es6
// @flow

type Base = {
  s: string,
  n: number,
}

type T = {
  x: number
} & $Shape<Base>

const t: T = {
  s: 'dfg',
  x: 133,
}
```

In case of usage intersection between regular object type and $Shape object, flow says `x is missing in object literal`, but obviously `x` is present.

Possible related issue #5702

**Comment by idiostruct** [comment]
I can't speak on the error, but you could spread `$Shape<Base>` into `T`: [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AIQIYDOOAvKAN6KiiEBcNKATgJYB2A5gDRWiv2sBXALYAjLI0QBfZOmygAKqDKVqAOnUASAMoALfNgA8BYgD5u1AB79hYidMQBjWK0IpQKeouU86oAOQAJpDsfuagVqAAjADM0WF8oABMUkA).

**Comment by jedwards1211** [comment]
I wish Flow would just outright bail on object intersections because they're completely error prone if any of the types are mutable in my experience

**Comment by gkz** [comment]
Works if you use the safe replacement, `$Partial`:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AIQIYDOOAvKAN6KiiEBcNKATgJYB2A5gDRWiv2sBXALYAjLI24BfZOmygAKqDKVqAD37CxjRJNAAyUABIACvkYpm+aAB4CxAHzIAxrFaEUoFPUXKedUADkACaQ7AHcavQAjADMMVJAA

https://flow.org/en/docs/types/utilities/#toc-partial
