### ISSUE TITLE
Issues with React.ElementType and React.ElementConfig in annotations

### ISSUE THREAD

**Issue by rtsao** [facebook/flow#5880]
I'm using `React.ElementType` and `React.ElementType` in a function. It works as expected in a function with an inferred type breaks with explicit annotation with the same type.

Here's a small reproduction case:

```jsx
// @flow

import * as React from "react";

class MyComponent extends React.Component<{ foo: number }> {
  render() {
    return this.props.foo;
  }
}

function Render<T: React.ElementType>(
  props: { $as: T } & React.ElementConfig<T>
): React.Node {
  const { $as, rest } = props;
  return React.createElement(props.$as, rest);
}

type RenderType = <T: React.ElementType>(
  props: { $as: T } & React.ElementConfig<T>
) => React.Node;

<Render $as={MyComponent} foo={123} />;
// $FlowFixMe
// <Render $as={MyComponent} foo="expected type error (should be number)" />;

const DoesNotWorkCorrectly: RenderType = Render;

<DoesNotWorkCorrectly $as={MyComponent} foo={123} />;
<DoesNotWorkCorrectly $as={MyComponent} foo="does not fail (should be number)" />;
```
([Playground link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAETY32sDcyt0ZcgFkAngGFmWAHZUp+KgA9csgCblqdXADoJmWDLkAeAN6hIsWAC5QUgK5oARlWygAvgD5QxxKFAcpKs4AFACUXj6+flS4tthSoLgAFiikWhhMGKnmsLy+roj5iJC2UvQo+pSqzoYAKtYa9FoAotBUaLK4NSIYVO5BEemwmdamACRk1jVuoABklZrNre1yElKQKADmte6IIfWc2gBysIHhvrT6pPhjZAA0UVfTALygg5m5UTFx8420HMTKFptDpBN6pcake4cK4hXiFXDdKiVALOLo9UAvWr7BZA5adRF9AYZUgjUAQybTOYNbS4jqrdZbGo7MJPTzUrTHQK8RCGagolwQp7GUS6aQdVxmCxCgCMACYAMwS4DuXggMkAMTg8HVKAUQioiBAvKqArIQpFkn04slsCerEUPXoVBUCURoGcTBcQVIiVgtmgLqcNnsTmwIVYoGV3IuUkeABFYFRSMdcAB1HAAawk2A49GgIn2-LRSJefMC2G5hgTSZT6ewWZwudw+bJZuF4ktBlwEuyMoVSpVPOrydgacz2abLcF7dFVrkPalrBUifIUlHZmIKGgoG9vv9gaRdkcznDkcHQA))

The reason this issue is especially problematic is because of existing bugs (https://github.com/facebook/flow/issues/3025, https://github.com/facebook/flow/issues/4227,  https://github.com/facebook/flow/issues/5808, https://github.com/facebook/flow/issues/5824) with type inference and higher-order functions (where return types must be explicitly added). This combination of problems yields a catch-22: a return type annotation is required for higher-order functions to work, but by adding the type annotation it breaks!

**Comment by SamChou19815** [comment]
Now all of them work as expected
