### ISSUE TITLE
Need help refining my Arrays

### ISSUE THREAD

**Issue by coldpour** [facebook/flow#5885]
I'm struggling to refine my types here and looking for help. I have the following types

```
type Item = {a: number};
type Items = Array<Item>;

type ItemGroup = {items: Items};
type ItemGroups = Array<ItemGroup>;
```

and I thought I'd be able to write a function like so

```
const getGroupedData = (data: Items | ItemGroups): ItemGroups => {
  return data[0].a ? [{items: data}] : data;
}
```

But flow doesn't consider my refinement good enough. I also tried this

```
const getGroupedData = (data: Items | ItemGroups): ItemGroups => {
  if (data.every(e => e.a)) {
    return [{items: data}];
  }
  
  if (data.every(e => e.items)){
    return (data: ItemGroups);
  }
  
  return [];
}
```

but that had the same result. Can someone point out what I'm doing wrong?

[Play with it on Flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSGeAtmALxgDeAhgFxgB2ArqQEZ4BOAvgNyZcBYmQDOlMAEEuXWlgA8I0gD4Bg-ERKkA4lzgscE6gEstoxktH91wrbv05xVabIVL7B1ehh4MYAOa+HvgAJgAitBi0aqBgCHBcANaiqIEYwXjhkbQSABQh2RZmAJRFZMFOyjSoYGBcvixcTGAA2tRgpmKMBVFgPAC6AjyooCjosfFJKWkZWb1U+YWa5XoGoqXLOquOlFXUNXUNTWA90ajDo2gj4CFweKJMAOR+k4lgWL6pQduZEfNgiyiZVI4gAPpsKht3NtKtVasYoADTgA6PAAN24WFyBAoVTwyNoxWKcNqhwwjWabU6IO62QGAlqw1qBwRSOyqIxXCxOLxyOp62K+1JZIpbKBEJhxQZfQOB3q5OOLUG52uY2uJzuD2ecQSbw+fjGMx+cxyC1OwLBEoc62BFV2JPlotOLQADP0CWAAPytExmWlRAZgf1nC4gFBAA)

**Comment by zeorin** [comment]
Seems that:
> Flow cannot refine properties of objects in predicate functions
https://github.com/facebook/flow/issues/4723#issuecomment-369997237
Perhaps the workaround will work for you?

**Comment by SamChou19815** [comment]
`.every` doesn't refine. You will need to use .map to refine.
