### ISSUE TITLE
Library type becomes an error in Flow 0.13.1

### ISSUE THREAD

**Issue by danvk** [facebook/flow#589]
I have some type definitions that @gabelevi helped me right for Q which I've been using for months:
https://gist.github.com/danvk/58fafeb13881a282f92c

With the Flow 0.13.1 update, I'm seeing a cryptic error:

```
/Users/danvk/github/pileup.js/lib/q.js: Library type error:
/Users/danvk/github/pileup.js/lib/q.js: inconsistent use of library definitions
/Users/danvk/github/pileup.js/lib/q.js:265:29,172: function type
Callable signature not found in
/Users/danvk/github/pileup.js/lib/q.js:30:5,155:5: statics of Promise
```

The lines of concern are:

```
declare module "q" {
    declare class Promise<T> {     // line 30
        // ... line 265
        declare function Promise<T>(resolver: (resolve: (val: T | IPromise<T>) => void , reject: (reason: any) => void , notify: (progress: any) => void ) => void ): Promise<T>;
    }
}
```

I'm not sure what this error means, let alone whether it's real.

**Comment by avikchaudhuri** [comment]
This error happens when a class is called like a function. Can you confirm
its not real?

**Comment by avikchaudhuri** [comment]
Btw is that a constructor? If so, rename it to constructor and remove the
type params, leave out the return

**Comment by danvk** [comment]
I'm honestly not sure what that line is about. It's taken directly from the [DefinitelyTyped type definitions for Q][1]. Commenting it out makes the error go away and seemingly has no effect on my code, so I guess I'm not using it.

I'm having trouble getting the `constructor` variant to work. Both of these are parse errors:

```
    declare constructor(resolver: (resolve: (val: T | IPromise<T>) => void , reject: (reason: any) => void , notify: (progress: any) => void ) => void );
```
```
    constructor(resolver: (resolve: (val: T | IPromise<T>) => void , reject: (reason: any) => void , notify: (progress: any) => void ) => void );
```

[1]: https://github.com/borisyankov/DefinitelyTyped/blob/6f04d25ad38982d372cc3cda62fa4c0eef9e24d7/q/Q.d.ts#L268

**Comment by avikchaudhuri** [comment]
Make the second return void. Also if you do turn out to use it, you'll get
better results swapping the order of T and IPromise<T> in resolver

**Comment by avikchaudhuri** [comment]
Closing, please reopen if the issue persists.

**Comment by danvk** [comment]
I wasn't able to get the declaration to parse. I don't appear to be using this declaration so it's not an issue for me, but this would be helpful to address if Flow would like to shoot for compatibility with TypeScript `.d.ts` files.

**Comment by avikchaudhuri** [comment]
@danvk: the following snippet parses for me (I put it in a lib dir and pointed to it from [libs] in .flowconfig, as usual).
```
declare module "q" {
  declare class IPromise<T> { }
  declare class Promise<T> {
    constructor(resolver: (resolve: (val: T | IPromise<T>) => void , reject: (rea\
son: any) => void , notify: (progress: any) => void ) => void ): void;
  }
}
```

**Comment by danvk** [comment]
That's still failing to parse for me in the context of the broader `q.js` definition.

My full file is here: https://gist.github.com/danvk/27b85befa56eeb5c8c8a

The error I see is:

```
/Users/danvk/github/pileup.js/lib/q.js:265:5,15: Library parse error:
/Users/danvk/github/pileup.js/lib/q.js:265:5,15: Unexpected identifier
```

**Comment by samwgoldman** [comment]
Looks like you are declaring the constructor outside of a class context. If you want the default export to be a class, I believe you can declare exports to be typeof the promise class.
