### ISSUE TITLE
About type  'Object' confused? 

### ISSUE THREAD

**Issue by zenjava** [facebook/flow#5891]
```
type MethodArgs = {|
  args: Array<Object>,
  meta?: Array<Object>
|}

const value: Object = {};

hello(value);

function hello(args: MethodArgs){

}

```
That code result is No errors!
But, I will promise args's type is MethodArgs, Wha can I do it?

**Comment by TrySound** [comment]
@zenjava Just don't use `Object` type here, it's a kind of `any`.
https://flow.org/try/#0C4TwDgpgBAshwAsD2ATAggJwOYGcoF4oBvAHwCgooBDbHALikwypAB4B5AIwCsIBjYAD4ANBSgBbeFQD8DJiw49+QsiQC+ZMnyQA7HMCgA3KgBsArtEJE1Abk0IIJk0gAUx8xACUdsgDMzOgIAlrpQDk6uNLgMcIiomLieRJpqQA

**Comment by zenjava** [comment]
But what should I do if I have such a need?

**Comment by zenjava** [comment]
One method return a Object value? And  the value will put In MethodArgs.args？
Like  this?

```
// @flow

type MethodArgs = {|
  args: Array<Object>,
  meta?: Array<Object>
|}


function getValue (): Object {
  return {};
}

function hello (args: MethodArgs) {

}

hello(getValue());
hello({ args: [ getValue() ] });

```

**Comment by zenjava** [comment]
Thks, I found the solution?
```
// @flow

type MethodArgs = {|
  args: Array<Object>,
  meta?: Array<Object>
|}

type Value = {}
function getValue (): Value {
  return {};
}

function hello (args: MethodArgs) {

}

hello(getValue());
hello({ args: [ getValue() ] });

```

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
