### ISSUE TITLE
Can't use 100+ bytes literal types

### ISSUE THREAD

**Issue by aatatuzov** [facebook/flow#5897]
It seems that Flow doesn't support variable-length string literal types. See this [flow/try](https://flow.org/try/#0C4TwDgpgBAysBOBGADMqBeKByZiBMAzACwCsAbAOwAcAnLoaZbfcedXfq0xw28543YtB-Xt2F8eXdlgBQoSLAQ0aGbAMkTxG7WKE79e0dOMipZrTNmyANhGBQAzghTIAXEqSo1OA6c1+5gFGQbomoYbhlrRydg7O8CoecImqmFiB0RH+YRaZ+SFZWXJAA).

```
type Str100 = '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'
type Str99 = '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'

let str100: Str100 = '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'
let str99: Str99 = '123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'

```

```
4: let str100: Str100 = '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'                        ^ Cannot assign `'0123456789...'` to `str100` because string [1] is incompatible with string literal `0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789` [2].
References:
4: let str100: Str100 = '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'                        ^ [1]
4: let str100: Str100 = '0123456789012345678901234567890123456789012345678901234567890123456789012345678901234567890123456789'
               ^ [2]
```
At first glance you may think that such a long literal types do not make sense. However one (me) can use a JSON with phrase-based unicode fields for multilingual support. In this case Flow is supposed to check if there are i18n literals in code not defined in the JSON.

**Comment by mrkev** [comment]
Welp, nvm not a bug; it's right [here](https://github.com/facebook/flow/blob/master/src/typing/statement.ml#L3330). It's expensive to keep track of long strings so literals strings are capped at 100 characters.

Perhaps a way to set this constant this with a flag or through `.flowconfig` would come in handy for edge cases like yours. Unfortunately that is not on the roadmap, but if you'd like to PR I'd be happy to have a look at the branch.

**Comment by aatatuzov** [comment]
Thank you for response and information! I'll try my best to make PR with new `.flowconfig` option. I haven't  done any PR nor tried OCaml yet but... it's never too late to start!

>  It's expensive to keep track of long strings so literals strings are capped at 100 characters.

Isn't this 100 byte cap a temprorary fix? I mean if you gain some efficiency by truncating strings why wouldn't you replace them with short uids? I tried to find the answer by myself and found [that commit](https://github.com/facebook/flow/commit/e0f47c4e98d756960e469f742d0abbd813725fa2#diff-3bbc1792ef10ae5965c3bf2776988e14)) with some ratinale about sharedmem and serialization but it doesn't say much.

**Comment by mrkev** [comment]
Using uids is a good idea and IMO definitely doable, but it involves potentially adding a lot of infrastructure (string -> uid conversion, then a uid -> string table for things like error reporting, passing the table around where necessary, etc) for what's admittedly a bit of an edge case. I'm definitely in favour of the idea but it probably won't see time investment anytime soon 😅

Thanks for the PR! I'll look into it 👍

**Comment by aatatuzov** [comment]
> (string -> uid conversion, then a uid -> string table for things like error reporting, passing the table around where necessary, etc) for what's admittedly a bit of an edge case

I thought it may have a global optimization impact. Average literal length is at least two times greater than uid length. So one can probably save at least a half of a memory used for this purpose. Of course, I don't know if it really worth it.
