### ISSUE TITLE
Cannot get fs.WriteStream because property WriteStream is missing in module fs (IT IS THERE!!!)

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5900]
**Same for `fs.ReadStream`**

Using Flow 0.66:

Here is the entry for "fs" in `lib/node.js` of Flow 0.66 &mdash; and I verified that the file mentioned in the error message shown below is that file and has those same lines: https://github.com/facebook/flow/blob/v0.66/lib/node.js#L697

Yet I get this message:

```
Error ------------------------------------------------------- node_modules/One/lib/system/storage-streams.js.flow:299:22

Cannot get fs.WriteStream because property WriteStream is missing in module fs [1].

     node_modules/One/lib/system/storage-streams.js.flow
      296|     // it is consistent.
      297|     const cryptoHashObj: crypto$Hash = crypto.createHash('sha256');
      298|
      299|     const stream: fs.WriteStream = fs.createWriteStream(
      300|         path.join(StorageBase.STORAGE_DIR.tmp, tmpFile),
      301|         {encoding}
      302|     );

     ../../../AppData/Local/Temp/flow/flowlib_1e92416f/node.js
 [1]  697| declare module "fs" {
      698|   declare class Stats {
      699|     dev: number;
      700|     ino: number;
      701|     mode: number;
      702|     nlink: number;
      703|     uid: number;
      704|     gid: number;
      705|     rdev: number;
      706|     size: number;
      707|     blksize: number;
      708|     blocks: number;
      709|     atimeMs: number;
      710|     mtimeMs: number;
      711|     ctimeMs: number;
         :
     1018|     O_NONBLOCK: number, // 2048
     1019|     S_IRWXU: number, // 448
     1020|     S_IRUSR: number, // 256
     1021|     S_IWUSR: number, // 128
     1022|     S_IXUSR: number, // 64
     1023|     S_IRWXG: number, // 56
     1024|     S_IRGRP: number, // 32
     1025|     S_IWGRP: number, // 16
     1026|     S_IXGRP: number, // 8
     1027|     S_IRWXO: number, // 7
     1028|     S_IROTH: number, // 4
     1029|     S_IWOTH: number, // 2
     1030|     S_IXOTH: number, // 1
     1031|   };
     1032| }
```

Note that the file using that Flow type is in `node_modules`, because the funny thing is, I don't get the message in the library project (when I'm working on the library that here is included in another project), I only get it in the project including it. All other Flow types (and there are many) between included project and parent project (both have been extensively Flow-typed) work.

There is nothing of relevance in either of my respective `.flowconfig` or `flow-typed/`.

<br>

Unrelated(?), looking at `lib/node.js` I also don't understand where `stream$...` is coming from, used e.g. in `declare class ReadStream extends stream$Readable {...}`.

**Comment by mrkev** [comment]
Is this still the case on v0.70.0?

**Comment by lll000111** [comment]
Have not seen it, might be gone.
