### ISSUE TITLE
Type for decorator with unknown arguments

### ISSUE THREAD

**Issue by Diokuz** [facebook/flow#5901]
[TRY](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AUVALygA8AKgHwAUkAXKJQHRMCGATgOYDOdAVAJSFyoUgBpQTBmy68BBIaWQBjWADtOKUFgAeWRQFcUWOviLUxEqZ1lDIjFhytLV60FsL1mdFXoC2AIyxWPi9fANZBUAAWRGU1DTR3Sk9Qb39AsT86dVYASxV2MUUAfjo-WFhoLGYVYJTQwIiAVkRQVtBEbV0DLEotMQBybLz2foEQUE4AC1g9aAATUBRJ1gRNVhXWDp19Q0o0MQBGAaH8-rFvaGgxsCmZ+cXl1cCNoA)

I want to create a function `execute` (very similiar to lodash partial, but its typings just Array<any>), which takes a function as a first argument, and call it with `...rest` arguments. How can I type that?

```
// @flow

type E = <T>(f: (...args: *) => T, ...args: *) => T

const execute: E = (f, ...args) => f(...args)

const x = (a: number): number => 4
const y = (a: number, b: string, c?: boolean): number => 5
    
execute(x, 'string') // should throw error
execute(y, 1, 'string', null) // should throw error
```

I dont know arguments types for `f`, but I know, that `execute` _rest_ arguments must exactly match `f` arguments.

**Comment by stereobooster** [comment]
[Shorter version](https://flow.org/try/#0C4TwDgpgBAolC8UA8AVAfACgGYC4oYDoiBDAJwHMBnPAQVNOJCQCo0BKBNKFAGiiIJkqteoxbtO3AFABjAPYA7SsCgQAHhBkBXYBDxxE2PgKGUO8LlkIkKZ2YuVQ1CfMTwKtAWwBGEUm3cvX1JJABYpdU0dCAw1PgBGNiA)

```ts
type E = <T>(f: (...args: Array<*>) => T, ...args: Array<*>) => T
const execute: E = (f, ...args) => f(...args)
const x = (a: number): number => 4
execute(x, 1)
```

Issues looks very similar to https://github.com/facebook/flow/issues/5903

**Comment by SamChou19815** [comment]
The recommended top type for function is `(...$ReadOnlyArray<empty>) => mixed`
