### ISSUE TITLE
Passing on a function after a null check causes its signature to change?

### ISSUE THREAD

**Issue by casr** [facebook/flow#5903]
I seem to be getting an issue where passing on a function after a null check causes Flow to think that its type signature has somehow changed. I am probably misunderstanding the error, however, so I hope someone can help. I have made a small example below to use for testing.

Possibly related to #2712

```js
type Props = { a?: <T: string>(x: T) => T }

function B(props: Props) {
  props.a != null && C({ a: props.a })
}

function C(props: Props) {
  props.a != null && props.a('hello world')
}
```
```
4:   props.a != null && C({ a: props.a })
                               ^ Cannot call `C` with object literal bound to `props` because `T` [1] is incompatible with string [2] in the first argument of property `a`.
References:
1: type Props = { a?: <T: string>(x: T) => T }
                                           ^ [1]
1: type Props = { a?: <T: string>(x: T) => T }
                                     ^ [2]
```

https://flow.org/try/#0C4TwDgpgBACgTgezAZygXigbygQwPwBcUAPACpHLBwCWAdgOYB8AFAB5GkCU6jUpUAXwBQQgGYBXWgGNg1BLSgAhZmEQoi8JMm6YhUKKq0A6HFACEGWuIA21qADJ7UAMLNsOIoZQnBnIcLFJGTkFVy9kDTVtLD0DKJ8LKCtbBydwk2YAcgALCFsEKAB3BDhrABNMvwEgA

**Comment by stereobooster** [comment]
[Here is the shorter version](https://flow.org/try/#0C4TwDgpgBAglC8UA8AVAfACgB4C4ooEoE18BuAKAGMB7AOwGdgoAvHORDEI+EkUoA).

```ts
type A = <T>(x: T) => T;
const z:A = (y) => y;
```

**Comment by SamChou19815** [comment]
It now works
