### ISSUE TITLE
Nominal Type Check Failure

### ISSUE THREAD

**Issue by orlandoc01** [facebook/flow#5905]
The code below is validated by Flow, yet I would expect the assignment of `b` to fail to trigger an Error because classes nominally typed and the only relationship between class `A` and `B` is that both are used to create the sum type `Or`. Is this a bug or am I missing something? It seems that removing either the `constructor` or the `func` declaration from the `A` class causes flow to correctly detect the error in the `b` assignment  but as it currently stands it seems like Flow is failing to see this error.
```
/* @flow */
type Or = A | B

class A {
  constructor() {}
  func(): Or {
    return new A();
  }
}

class B {
}

const b: B = new A();
```
Link: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDyATmALxgCCYAPmAEKqoDGMAhgM7uVgDeqYYJnAB27dEQCuTdHCIAKAJS8AvvzBQJwpooBchEnwECiudBKLCww3EgqKA3GtWrmbTvV6oXQ0ejAAjPToyKxtKB0YgA

**Comment by vkurchatkin** [comment]
Slightly shorter example:

```js
class A {
  constructor() {}
  f(): A | void {}
}

(new A(): number);
```

**Comment by zerobias** [comment]
Notice that it already fixed in the master branch, as we can see in repl
