### ISSUE TITLE
No error if class that implements an interface has interface methods without arguments

### ISSUE THREAD

**Issue by AriaFallah** [facebook/flow#5907]
[flow.org/try link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWA7ALgUwE6QIYDGWoAkgCpYDOGoA3oqKAEY6wDWWaAFAB4BcoNAFcAts1wBKQTRzoA5gG5EAX2SFo+KlVCUaoFKIAO0LKK4YdFarQZNWHLt0n1GTUDiwZhONKADk-m5qKkA0)

```js
// @flow

interface ITest {
  broken(x: number): string;
}

class Test implements ITest {
  broken() {
    return ''
  }
}
```

Flow doesn't warn that `broken` in `Test` doesn't have the same arity as `broken` in `ITest`.

**Comment by idiostruct** [comment]
Function subtyping dictates that a function with a smaller maximum arity is still a subtype of a function with a larger maximum arity:

```typescript
broken()
broken(x: number)
broken(x: number, y: number) // Error!
```

**Comment by AriaFallah** [comment]
@idiostruct hmm, but why is that desirable behavior? I can't think of a case where you would want this to not be an error.

**Comment by vkurchatkin** [comment]
@AriaFallah not every implementation needs all arguments. Omitting some of them (or all of them) doesn't change correctness

**Comment by AriaFallah** [comment]
@vkurchatkin Alright makes sense. Thanks!
