### ISSUE TITLE
Flow linting not working on connected stateless functional components

### ISSUE THREAD

**Issue by no-stack-dub-sack** [facebook/flow#5909]
Not sure if I should be opening this here or in nuclide, but for some reason, in files that I have stateless functional components that are connected, flow linting does not work. Example:

```js
// @flow
import { connect } from 'react-redux'
import React from 'react'

const num: number = '2'
// no errors here or anywhere else in the file

const Pane = () => ({
  children,
  className,
  leftWidth,
  rightWidth,
  theme
}) => (
  <main
    className={className.includes('left-pane')
      ? `${className} ${theme}`
      : className }
    style={{ width: className.includes('left-pane')
      ? leftWidth
      : rightWidth }}>
    { children }
  </main>
)

const mapStateToProps = ({ panes, theme }) => ({
  leftWidth: panes.leftWidth,
  rightWidth: panes.rightWidth,
  theme: theme.current
})

export default connect(mapStateToProps)(Pane)
```

The error is caught when I run flow at the CL, but not as I code. If I write `Pane` as a `class` component, it starts to warn me about stuff, and normally, I get the `"missing type annotation for destructuring"` warning when I have a stateless func component like this. Lastly, as soon as I remove connect, and just export `Pane` directly, flow linting starts to work. It's not the end of the world, but I'm a bit stumped, and thought I might as well report it. Thanks.

**Comment by villesau** [comment]
react-redux libdefs have been rewritten since the issue so I assume it's not longer an issue with more recent versions of Flow.
