### ISSUE TITLE
Member variable treated as maybe null even immediately after being set

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#591]
This is a behavior that I didn't expect and run into often.

```javascript
/* @flow */
//jshint ignore:start

class Foo {
  _x: ?string;

  bar() {
    this._x = 'aaa';
    console.log(this._x.length);
  }
}
```

```
$ flow check

/Users/chris/Coding/flow-test2/a.js:9:17,30: property length
Property cannot be accessed on possibly null value
/Users/chris/Coding/flow-test2/a.js:5:8,13: null

/Users/chris/Coding/flow-test2/a.js:9:17,30: property length
Property cannot be accessed on possibly undefined value
/Users/chris/Coding/flow-test2/a.js:5:8,13: undefined

Found 2 errors
```

I understand technically `this` could have a getter or setter on '_x' which causes it to be read as null later, but it seems a bit much. The following makes it not error, even though a getter doesn't have to return the same thing each time:

```javascript
  bar() {
    this._x = 'aaa';
    if (!this._x) return;
    console.log(this._x.length);
  }
```

Usually I work around it awkwardly like this:

```javascript
  bar() {
    var x = this._x = 'aaa';
    console.log(x.length);
  }
```

**Comment by avikchaudhuri** [comment]
@bhosmer is going to fix this very soon.

**Comment by bhosmer** [comment]
Closing issue, went in [a while back](https://github.com/facebook/flow/commit/ef8ece919a4dbfde08cbb2c68c0335df2535aa8d).
