### ISSUE TITLE
Poor error message when iterating through Object.keys() of an object type

### ISSUE THREAD

**Issue by bourds** [facebook/flow#5911]
`// @flow

type Foo = "hello";
type Bar = "world";

type C = {
  foo: Foo[],
  bar: Bar[],
};

(c: C) => Object.keys(c).forEach(key => c[key].join());`

This causes the following error message which doesn't make any sense:

> 7:   foo: Foo[],
          ^ string literal `hello` [1] is incompatible with string literal `world` [2].
References:
7:   foo: Foo[],
          ^ [1]
8:   bar: Bar[],
          ^ [2]

This doesn't make sense since type Foo and type Bar are different so why is it saying they are somehow related.

I can work around this by adding some additional casting but it was difficult to figure out based on the error message.

`(c: C) => Object.keys(c).forEach(key => ((c[key]): $Values<C>).join());`

**Comment by SamChou19815** [comment]
This no longer errors
