### ISSUE TITLE
Extract param types from a function

### ISSUE THREAD

**Issue by deecewan** [facebook/flow#5915]
If this is a bug, please try reproducing using https://flow.org/try/.

I'm trying to produce a helper type that I can use to type redux thunks when they're used as React props after being put through `mapDispatchToProps`.

It looks like this:

```js
type ExtractThunkReturn = <T>(() => (FirstArg, SecondArg) => T) => T;
export type ThunkReturnExtractor<T> = () => $Call<ExtractThunkReturn, T>;
```

which works great ([flow try link](https://flow.org/try/#0C4TwDgpgBAYglgJwM7AIIIOZQLxQDwAqAfABQECUORUBA3AFCiRQDKEAxgPYB2AJullwlK2agEYATAygyojcNACiAD2AIAhu2AEAFgFduAawBKEYHoTcc+YiWFUoJeMjSYANKw49+mEdQoOdPQQymCcCMBQTNC6BiZmFtwqaprA4YTUuAAkAMLqADb5eMkaWrFGpuaWHsQM9ABmBlpwPFEQKPYA3vQyCAmWjvUeSH5Q3bJQfVVWAAoInAC2cEgQAHR9SJz5AG4QwrRyMgC+9CcT8swscAtg+RDlhtYPlYklqenRnPVtKETSsg0msAWlYkNdbhAAKorBAkZQALlY4LuD0o4ygylWwB0EG4dlGXG4mzuq3ynAwJAA5MB2sBKeRyKcgA)). The problem comes when I have a more complex thunk which takes some arguments.

```js
function test(arg1: number, arg2: string) {
  return (f, s) => {
    return Promise.resolve([arg, arg2]); 
  }
}
```

Now, using the same tactic as before, flow correctly picks up that the arguments to the `.then` are `number` and `string` ([flow try link](https://flow.org/try/#0C4TwDgpgBAYglgJwM7AIIIOZQLxQDwAqAfABQECUORUBA3AFCiRQDKEAxgPYB2AJullwlK2agEYATAygyojcNACiAD2AIAhu2AEAFgFduAawBKEYHoTcc+YiRIA6R+sxIAXFHXcQI6iXjI0TAAaVg4efkwfGii6eghlME4EYCgmaF0DEzMLbhU1TWAkwmpcABIAYXUAGyq8PI0tDKNTc0sQ4gZ6WTkAMwMtOB5UiBQSZwx3bj0AWwAjCAQQ8Yl3FAQ4bgxKAG8uqARsyygSHpCkKN3ug9arAAUETmm4JAh7A6ROKoA3CBIAbXGS0wEgAuuRaHIZABfegw7ryZjlR5gKrxJqGazolo5eoFIppTg9YYoIjSWT0PrcAZDLjTFHxACqLwQJGU7iRdNRynROz2ynswB0EG4dgBIVmYKoUEuMgAkGNJjN5ghwXsZCRZqs1BstmSoaqoUA)).

The problem is, I have no way of saying 'when you call this function, it'll take the same arguments as `typeof <function>`, and return the result of calling the inner function'.

Essentially, what I want is to be able to do something like:

```js
type ExtractThunkReturn = <T, P: $Params<T>>((...params: P) => (FirstArg, SecondArg) => T) => T;
export type ThunkReturnExtractor<T> = (...params: $Params<T>) => $Call<ExtractThunkReturn, T>;
```

where `$Params` (or something similar) provides me access to the parameters that that particular function accepts.

My best guess for right now is to try and use the existential type, which still doesn't work as expected ([flow try link](https://flow.org/try/#0C4TwDgpgBAYglgJwM7AIIIOZQLxQDwAqAfABQECUORUBA3AFCiRQDKEAxgPYB2AJullwlK2agEYATAygyojcNACiAD2AIAhu2AEAFgFduAawBKEYHoTcc+YiRIA6R2HUaAtkgBcUAFQjqJeGQ0TAAaVg4efkw-Ghi6eghlME4EYCgmaF0DEzMLbhU1TWAUwmohR3tnN08fGIASAGF1ABtmvAKNLSyjU3NLMOIGegAzAy04HnSIFGEoAG96GQRcyygSYbCkGIXZKGW+qwAFBE5XOCQIe2WkTmaANwhhWjkZAF96d92RseAJq2BpsAJCQXBgvNw9K4AEYQBBhUESLwoBBwbgYSg7PYrKzrTbbRayfZ5KDHU7nS7XW4PEgAbVB8MwEgAuuRngT3p9ZPJmCw4K4wM0IN1DNZhb08h0iiUMpxhlMUEQGBkoA1TgLEsLRfoetjJVppQpZfKgYqCTJvtxxpMkHz1QBVC4IEjKLy8-mC4UYgnKezAHQQbh2GJcbg3QX2ZqcDAkADkAJQMfI5A+Zrko0tv0mXHdiQdsJI7BagoQXlVOeUnvmBMLrXzccBMbCwxaF3Ivv9gdp6jCUJZVCrsgAkCDwZCYQhWamSFCkWpUejpFBXpPXkA)).

**Comment by villesau** [comment]
This is exactly what is needed for writing react-refetch types too.

**Comment by peter-leonov** [comment]
Just have tried to extract at least first argument type with the same technique, and got no type errors, but then checked if there is no hidden `any` type created out of nowhere and found one :(

```js
type ExtractReturn<F> = $Call<<A,R>(A => R) => A, F>;

// clearly, `Return` must be of type number
type Return = ExtractReturn<number => number>;
// but it looks like any :(
let x1: Return = 'string'
let x2: Return = []
let x3: Return = () => {}
```

**Comment by vitramir** [comment]
Try this

type $ExtractReturn = <V>((...args: any) => V) => V;
type ExtractReturn<F> = $Call<$ExtractReturn, F>;

**Comment by deecewan** [comment]
@vitramir That works to get the return type - I want the parameter types.

**Comment by SamChou19815** [comment]
`Parameters<...>` now exists
