### ISSUE TITLE
$Keys and number-indexed objects

### ISSUE THREAD

**Issue by Awpteamoose** [facebook/flow#5917]
I'm trying to use an fp-style prop-getting function with a number-indexed object.

```javascript
const prop = <O: Object, Key: $Keys<O>, T: $ElementType<O, Key>>(key: Key, o: O): T => o[key];

const foo = { [50]: "50", bar: "100" };

const t1 = foo[50]; // OK
const t2 = prop("bar", foo); // OK
const t3 = prop(50, foo); // Error
```
```7: const t3 = prop(50, foo); // Error
                   ^ Cannot call `prop` with `50` bound to `key` because number [1] is incompatible with key set [2].
References:
7: const t3 = prop(50, foo); // Error
                   ^ [1]
1: const prop = <O: Object, Key: $Keys<O>, T: $ElementType<O, Key>>(key: Key, o: O): T => o[key];
                                 ^ [2]
```

[flow.org/try](https://flow.org/try/#0MYewdgzgLgBADgJxHGBeGAeA8gLhlgIwCsBTYKAGhgGkSBPPAElromwD4qAVJgUQBsSAWxJgoXOnBLYqLduwAUAa3p4WVEHiwBKPFzTsYIANoq6AXQDcAKGuhIsAGYgQaGAG8YxgKwAGc3gARH6BVAQAhghBAIy+voEwAL42duDQMFDRbs4mflYwAPQF+NSpDhkATG6IyAqBEQihMDnaloXFWKX26VAAzNVIcAp+VC1tRTC8CEgI1kA)

**Comment by SamChou19815** [comment]
Expected, since there is no number key in JS. All keys are string.
