### ISSUE TITLE
Container<A> doesn't pass typecheck for type Container<A | B>

### ISSUE THREAD

**Issue by philipp-sorin** [facebook/flow#5918]
[try flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQyAuBPADgU1AQVALygDeiAkAB4BcoARrLNFgIYB2ANIgL6qY4BChEuTQ16jFh269sefgGFGTAMYoAlrFZDcAJx3M0AHnwAfUPwB8AbmSQArq1UatdgM5YAFMx0BzGrgUlLCdNAEphaURlTVcUUGg1WIB5SFx-PQNjCyEAbQBdG0Q3TwTk1NCrIA)

**Comment by apsavin** [comment]
[fix](https://flow.org/try/#0PTAEAEDMBsHsHcBQyAuBPADgU1AQVALygDeiAkAB4BcoARrLNFgIYB2ANIgL6qY4BChEuTQ16jFh269sefgGFGTAMYoAlrFZCAJACUWAEwDyraGlwAnC8zQAefAB9Q-AHwBuZJACurVRq1eAM5YABTMFgDmNLgKSlh+mgCUwtKIypqBKKDQaplGkLjRVjb2LkIA2gC6HohBoTl5BYluQA)

Someone can change your array and it'll lead to an error

**Comment by philipp-sorin** [comment]
@apsavin thanks
