### ISSUE TITLE
Support some flavor of semver in flowconfig's [version] section

### ISSUE THREAD

**Issue by ide** [facebook/flow#592]
The idea is for .flowconfig to specify that the project is compatible with e.g. both 0.13.0 and 0.13.1. Something like npm's caret would work well. Good bootcamp task?

cc @gabelevi

**Comment by mroch** [comment]
I like this idea... it's a pain for us to update all of our internal flowconfigs for patch releases.

We might need to hit 1.0 first though, since right now we're definitely introducing non-backwards-compatible changes in minor releases.

**Comment by ide** [comment]
npm's caret might line up with your versioning process. It special-cases pre-1.0 releases so that ^0.13.1 is sugar for ">=0.13.1 <0.14.0"

https://github.com/npm/node-semver/blob/master/README.md#caret-ranges-123-025-004

**Comment by mroch** [comment]
oh nice

**Comment by ide** [comment]
Nice! thanks Marshall.

**Comment by davidaurelio** [comment]
We have `^0.22.0` in [React Native’s `.flowconfig`](https://github.com/facebook/react-native/blob/master/.flowconfig#L94-L95) and it breaks for me:

```
!!! ./.flowconfig requires Flow v^0.22.0,
!!! but /Library/Application Support/Flow/v^0.22.0/flow doesn't exist
!!! Maybe ./.flowconfig requires a non-existent version,
!!! or maybe the binary is missing and the Flow team should be notified
```

cc @bestander
