### ISSUE TITLE
Covariant Return Type Issue

### ISSUE THREAD

**Issue by orlandoc01** [facebook/flow#5921]
When `Class B extends Class A`, my understanding is that type safety is preserved when the methods of `Class B` have a return type that is covariant with respect to the return types of the same methods on `Class A` (if present). In the example `flow try` link below, this is verified in the `Dog extends Animal` check I provide. However, when extending the `Array` class with a custom `List` class and implementing `map`, flow detects an error when returning `List<U>` from the method, even though it extends `Array<U>` and is therefore a subtype. Is there something I am missing or is this a bug?

Offending Code:
```
class List<T> extends Array<T> {
  map<U>(callbackfn: (value: T, index: number, array: Array<T>) => U, thisArg?: any): List<U> {
    return (null: any);
  }
}
```
Link:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2AQQDsBLAWyxgB4CA+MAb1TDAoAcqAhWgCgEoAXIVIVq3RmABOAUwAuAV0lEwPIvJgwhWIgE8+YAL6ojGbHjAAROAHMa9aQA9Z0ogBN8xcpTuNmrLBzc-EJWtuIMUnKKyqrqmmDaeobGqKiObHCSsmCu0lBY6tmYuPgAMiQ4slQAKvZOLu6EkpJYOjX0TCzsVACqvOiUMABGWOgA1lBEQjwAbpTy0kLVADRgJG6OQmpkQ9KSq1jNrUIER221+gC89D2rsgAWFafWAPxauoJg5ZW9HX4sMgUShUag07z0AG4-EYTKggA

**Comment by SamChou19815** [comment]
Seems to work now
