### ISSUE TITLE
Flow 0.67 lacks binary assets, breaks flow-typed.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#5922]
The latest [0.67 release](https://github.com/facebook/flow/releases/tag/v0.67.0) doesn't have the flow binaries in its assets like the other releases, which [breaks functionality](https://github.com/flowtype/flow-typed/issues/1921) in `flow-typed` where we've been expecting those binaries.

Was it intentional to release without the binaries as assets?

**Comment by davidgomes** [comment]
This also breaks flow-bin. See this issue: https://github.com/flowtype/flow-bin/issues/117.

**Comment by aikar** [comment]
This is likely due to 0.67 having a bug, maybe was removed intentionally. 0.67.1 is released with binaries

**Comment by AndrewSouthpaw** [comment]
Is it possible to remove 0.67 from the list of releases, or re-release it?... Right now we have a workaround where we just ignore 0.67, which seems brittle.

**Comment by mattdeboard** [comment]
@andrewsouthpaw Out of curiosity why do you iterate through flow versions

**Comment by AndrewSouthpaw** [comment]
We run our flow-typed libdef tests on each version of flow. We could whitelist specific versions, but up until now that hasn't been necessary.
