### ISSUE TITLE
string isn't a valid ?string in object types.

### ISSUE THREAD

**Issue by marcusdarmstrong** [facebook/flow#5923]
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeiooGATrBgFygD8AzipQJYB2A5gDSIC+AbmTpsoAEKESZCtTqgW7bnyHIAxrA4tQAIwCGlKQAp9AL3q4AlIQB8uvaeEatKUJFix6kosVk16AEQBoKqI+pRG7rCWgkA

It seems like the ? operator doesn't have correct type variance set up here? Obviously all "B"s are valid "A"s, yet Flow complains.

**Comment by lll000111** [comment]
Try this one-letter change: [Flow Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeiooA1BgE6wYBcoA-AM4rUCWAdgOYA0iAL4BuZOmygAQoRJlQNOozadeAkcgDGsLm1AAjAIbUZACkMAvRrgCUhAHz6D50Vp0pQkWLEbSixebQMoABEwaDqiIbUJp6w1sJAA)

**Comment by marcusdarmstrong** [comment]
Aha! I neglected to think about the writable case. Apologies.
