### ISSUE TITLE
Deleting a read only class property does not error

### ISSUE THREAD

**Issue by dmeehan1968** [facebook/flow#5927]
[Try](https://flow.org/try/#0MYGwhgzhAEBiD29oG8BQ1oGoBGYBOAXNAPwQAueAlgHYDmq60w815eArsGfHgBS6FobGrQCUKRhjIALShAB0A6AF5oAxgF8GGAGbtqwXuLQYMAEwCmIC2QvQZcxfgCQzgPRvoAN0rxwZX2poeB1oPAswM2DqEABPYk1ULVQgA)
```js
class Foo {
  +bar: ?string

  constructor(bar: string) {
    this.bar = bar
  }

  func() {
    delete this.bar		// violation of read only?
  }
}
```

NB: The MayBe type makes no odds

**Comment by SamChou19815** [comment]
It errors now
