### ISSUE TITLE
flow checker not throwing error for missing type

### ISSUE THREAD

**Issue by kirankumarkk** [facebook/flow#5931]
below is my code

```js
import React, {Component} from 'react';


type AccountDrawerProps = {
    accountId: ?string,
  setExchangeRate: (exchangeRate: string) => void,
};

class AccountDrawer extends Component<AccountDrawerProps> {
    constructor(props: AccountDrawerProps) {
        super(props);
    }


    handleExrateChange(exrate){
        this.props.setExchangeRate(exrate);
    };


    render() {
        
        return (
            <div>
                ** rendering logic goes here**
            </div>
        );
    }
}
```

flow check is not showing the missing type error for the function handleExrateChange.

Ideally it should alert that the param 'exrate' should be typed.

flow version 67.1 . I tried in flow try. 

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYG4AoLmATzCTgBBNGggBXcgBEoKAO5IoABTpgAznAC8uDnF1x0oiTACSAEwBccAPyqYUYMQDmmHXFVIYAUQAeaABYoTkgIKDBIlgAUSL4BQSFhlrb2TgCUmgB8cABuEMCmLhScHGgANiiq6sKGUjLyUHDRYcSm6gREpOQAPFXiNXIKyhBqmTiuuqLESWIY0BFgKqqWPUbS-UoLaaN6225i-FBzG5zbFFxjcLGmJUg+MmF4sY5IUd53SClbO7owfsCqAHTzIYA9xeGKBJ7xZ7RN4pY56QpnbbMZoKCKbc7bTF6ZgwMRQYhwCLYr6dUzALLpElfPQAKlpcBRpgUDkccBKEEcwDQcEcECQ6j8CiQ9Op206AHpyZTqXDzqcKEA

**Comment by TrySound** [comment]
@kirankumarkk It should not. Flow requires type annotation only for exported functions and classes. In other cases types can be inferred.

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYG4AoLmATzCTgBBNGggBXcgBEoKAO5IoABTpgAznAC8uDnF1x0oiTACSAEwBccAPyqYUYMQDmmHXFVIYAUQAeaABYoTkgIKDBIlgAUSL4BQSFhlrb2TgCUmgB8cABuEMCmLhScHNGQsHBoADYoqurChlIy8lBw0WHEpuoERKTkADx14g1yCsoQapk4rrqixEliGNARYCqqlgNG0sNKK2mTevtuYvxQSzuc+xRcU3CxphVIPjJheLGOSFHeT0gpewe6MH5gKoAHTLMYg9xeGKBN7xd7RL4pc56QpXfbMdoKCK7a77XF6ZgwMRQYhwCL4v69UzALLpCl-PQAKkZcAxpgUDkccAqEEcwDQcEcECQ6j8CiQzPp+16AHpqbT6UjrpcKEA
