### ISSUE TITLE
React.cloneElement fails because of props in union

### ISSUE THREAD

**Issue by danrot** [facebook/flow#5934]
We have a React component which can take a few different components as children. Based on the parent component we want to set a property on all child components, therefore we use `React.cloneElement`. However, if we try use clone on this element it does not really seem to work. I've built something to show that:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxkVHnJmAOR4XWMDcGO+RBAntlJgA3gGEAFuhgATFgDsAgnjzk+AGjABRGKUyk5BAL5ha9JiyoEOqVP0FgJU6QAU62AM4BGMAF4RqMDACUncCTwAuMDkAV0wAI1I8NVRDTlsBIUcZVzgPACZff0Dg0LzI0Lx0OQBzZNSbShhyd3cHSRlvUgAPYLlpVrJLADpRelw5fQIAHiyXNy8APn9DBqaWtqcC7t7+klYCEbG4CYMZ9rnc9zyl4RSbOyEAFRCCHI9C28DKc-lI7V1JlMHnAoBsOksAD5aHR6U7A0Gza4pNKNZqtZ6hMDbfS7QbUQ7cE7TDGveY3AJgeTSRIACgAlEVApTSARong5GAptJ0AA3BYUpkiPEHRrHUj-WEEGkESTuIbYeZDb5OeQaGXoOUKy5Kn76eXzOkrQVTYDcvmcQIrQxAA

Shouldn't the following line always succeed:

```
{React.cloneElement(this.props.children, this.props.children.props)}
```
Because the set of props the child has itself should always be correct, shouldn't it?

**Comment by SamChou19815** [comment]
Closing since we now banned React.Element inspection
