### ISSUE TITLE
Question/Feature: Generator Functions where the type of Next depends on the type of Yield

### ISSUE THREAD

**Issue by btford** [facebook/flow#5937]
Let me start with a motivating example. Let's say I want to implement something like [redux-saga](https://github.com/redux-saga/redux-saga) where I write a generator function that yields some function that represents XHR, and have a framework call `itr.next` with the value that comes back from a server.

```js
const getName = () => 'Brian';
const getAge = () => 123;
const parseJSON: (string => () => Object) = ...;

function gen* () {
  const name: string = yield getName;
  const age: number = yield getAge;
  const parsed: Object = yield parseJSON('{"greeting":"yo"}');
  return {...parsed, name, age};
}
```

Here's the example on [try.flow.org](https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AcwKZYByAhgLb6gC8oAFAJTUB8oA5AEIBOAliWqwG4U6bHkIBBAtTqMqLAIwAmAMxDUmHAAcSnDPgBSAZQDyRabWycAXKEvc0uWSwbNQR0wDo7D7pACeFlic9EKIkACuaMhY3OgAVGJoMqAA3oigoOqiaOT4Nt640n7c+NAAJmLEuUIZWTgkBDZo4WQARvicRSXllZL4NZkiWjp6ZTbGrQBW+NFdpRXaugYmRLSsKQBEuJz4hPa4G1YbfrAbAL6sIemgO1jhnEkpi6MANKA5FG8N+GdCZ4gAuq2LAkLCUGicSK0AhoK4ZeGga4IsKRaKxJKQtDQ-BoABisNS1yB3CC0hh+IYA2ghFSADcSNBwvg3mV0D9pCTOB40PgAB5YSnXeAAC241LoAEJWTzGGkEUCdhgOUFuXyBfTGfgGHD4RqmdJFR49f0kaBpeCbvgMB5zQN-hlbvcksa-oggA).

The definition for a generator function assumes that the generator will always accept values and yield values of the same type. The [`Generator` interface declaration in `./flow/code.js`](https://github.com/facebook/flow/blob/master/lib/core.js#L521) currently reads:

```js
Generator<Yield, Return, Next> { ... }
```

And so the type of `gen` is:

```js
Generator<string | number | Object, Object, ( () => string ) | ( () => number ) | ( () => Object )>
```

In practice, this means that I have to disambiguate the type of `Next` at each `yield` within the body of the generator function.

While I understand why this is important for the iterator returned from the generator function (because you cannot statically know how many times the iterator was iterated over), I suspect that you could at least improve the types *within* the generator function itself.

What I want is to map the `Next` value based on what is passed to `Yield`:

```js
Generator<Yield => Next, Return>

// So the type of gen becomes:
Generator<(() => string) => string | (() => number) => number | (() => Object) => Object), Object>

// or even better:
type ExtractReturnType = <R>(() => R) => R;
Generator<ExtractReturnType, Object>
```

The existing use-case (where `Yield` and `Next` are always the same type within the generator function) is easily captured:
```js
Generator<Yield, Return, Next> /* becomes */ Generator<Yield => Next, Return>
```

I suspect that it would be difficult (and maybe even impossible) to disambiguate the values yielded from the iterator, since it can't always be statically known how many times at iterator has been called. For my use-case, it's fine if the iterator returned is like:

```js
interface Generator<Yield => Next, Return> {
    next(value?: Next): IteratorResult<Yield, Return>;
}

// So in the example above...
const i = gen();

// i.next takes any of: "number | string | Object | void"
const v1: ( () => number | () => string | () => Object | void ) = i.next().value;
const v2: ( () => number | () => string | () => Object | void ) = i.next().value;
```

...so that disambiguating a union outside the generator function is still necessary.

Is there a way to achieve this effect currently (by for instance overloading the code type decl for `Generator`)? Is there a type-level "utility" function that would let me operate over unions in this way (something like [PureScript's RowToList](https://liamgoodacre.github.io/purescript/rows/records/2017/07/10/purescript-row-to-list.html))? And if not, is this something that would be interesting as a general improvement to Flow?

Thanks in advance :)

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/2613

**Comment by btford** [comment]
Oh nice! @vkurchatkin feel free to pull any of my explanation here into the master issue if you think it would help others discover it, or explain the motivation better.

Cheers!
