### ISSUE TITLE
type control fails with logical operator "||" 

### ISSUE THREAD

**Issue by MaxInMoon** [facebook/flow#5938]
I'm not a expert of flow, but I think it's not a normal behaviour.
Please tell me!

**Bug?**

when doing `form.valuesBadlyWritten || {}`, it won't rise error for `valuesBadlyWritten` (search for ` will NOT rise error` in the link below)

**Reproduce**

see [Link with a reproduced example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAMQIFsAVcygXjAG9UwwA3AQxgCuGAM4AudgF8ANKgkBudKmDAwAbQDyAaQC6YAOR9BIgEK8AJjFIB1fAEtChDADs9YBLZgwwd4ZQz58AnQAYzgnYWJfGAxgwhp8WgA1fiFhMFYACig6cXiGJgBKdIA+dk4wUPDibITkozTWGtoAOkNU0wtrOwdnBS58DEIBfCcwJrrUsAAfKckFeUVlNQA5dXowLV0DFJNzSxt7Rxc3Dy9V9Z8-AKDUSoiwKJi4ugmRABEwwisCAGt0sCyOWodEYFCKzFKHH6g2GoyarR2wg6+26R2mszYC3kQA)

**Comment by lll000111** [comment]
What is the question exactly? This looks alright to me.  Flow is correct when it says there is no proeprty `valuesBadlyWritten`.

**Comment by MaxInMoon** [comment]
@lll000111 sorry for the lack of clarity. Updated

**Comment by Brianzchen** [comment]
Fixed in current version 0.132.0
