### ISSUE TITLE
[idea] using "this" in constructer before "super" should not typecheck

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#594]
I am not sure if this should be checked by Flow at all or not, however, it's not a legal ES6.

    class Foo {
    
    }
    
    class Bar extends Foo {
        member: number;
        constructor() {
            this.member = 3;
        }
    }

[In Babel REPL](https://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=class%20Foo%20%7B%0A%7D%0A%0Aclass%20Bar%20extends%20Foo%20%7B%0A%20%20%20%20constructor()%20%7B%0A%20%20%20%20%20%20%20%20this.member%20%3D%203%3B%0A%20%20%20%20%7D%0A%7D) (note the error down there).

It's noted [for example here](https://developer.mozilla.org/cs/docs/Web/JavaScript/Reference/Classes/constructor):

> Note: In derived classes, super() must be called before you can use 'this'

I think flow should detect this.

(I am not so godly to be able to find this exact requirement in [official ES6 specification](http://www.ecma-international.org/ecma-262/6.0/).)

**Comment by avikchaudhuri** [comment]
Yes, this is on the radar! :)

**Comment by runn1ng** [comment]
:+1:

**Comment by mroch** [comment]
> I am not so godly to be able to find this exact requirement in official ES6 specification.

Interesting question... I'm not sure I can find it either. This is the closest I can find:
http://www.ecma-international.org/ecma-262/6.0/#sec-function-environment-records

it says:

> GetThisBinding(): Return the value of this Environment Record’s this binding. Throws a ReferenceError if the this binding has not been initialized.

**Comment by runn1ng** [comment]
It seems flow already does this. closing
