### ISSUE TITLE
Bug - Flow doesn't understand string | object ?

### ISSUE THREAD

**Issue by rimiti** [facebook/flow#5943]
Hello,

In first, thank you for this package, it's amazing (when it works ahaha!) !

So, can you explain me why flow doesn't understand this [simple case](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQUQLZQJYQBEpEp4BeeAZ0RlwDsBzeAH3gG946osQB+ALio16DANzwQOfIOq1G4gL6iAUMpAAPVAHsYiePUQgYAMyhgEAWTyFipNsvjGYWrIOzWiJADTKFD+MpgWnTUSCDUAIz8VviepBRsTi6CbJLWggBEhtQAAhrcqBAgAHRBWBkKSoHBodmIAEzRHrbk7Emu8FnhiHnqBUWlLhUqQA) ?

Example:
```
declare type EmailData = string | { name?: string; email: string; };

export interface MailData {
 from: EmailData,
}
  
const test1:MailData = {from: {email: "test@example.com"}};
const test2:MailData = {from: "test@example.com"};

```

Error:
```
7: const test1:MailData = {from: {email: "test@example.com"}};
                                 ^ Cannot assign object literal to `test1` because object literal [1] is incompatible with string [2] in property `from`.
References:
7: const test1:MailData = {from: {email: "test@example.com"}};
                                 ^ [1]
4:  from: EmailData,
          ^ [2]
8: const test2:MailData = {from: "test@example.com"};
                                 ^ Cannot assign object literal to `test2` because string [1] is incompatible with object type [2] in property `from`.
References:
8: const test2:MailData = {from: "test@example.com"};
                                 ^ [1]
4:  from: EmailData,
          ^ [2]
```

Thank you so much.

Have nice day!
Dimitri,

**Comment by apsavin** [comment]
I can’t explain this behavior, but I think it could be useful to note that all’s fine if you use type alias instead of `interface`.

**Comment by lll000111** [comment]
The problem is that your object could be written to in which case it would all fall apart, so you have to declare it read-only.

[Try this.](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQUQLZQJYQBEpEp4BeeAZ0RlwDsBzeAH3gG946osQB+ALio16DANzwQOfIOq1G4gL6iAUMpAAPVAHsYiePUQgYAMyhgEAWTyFipNsvgBqYzC1ZB2a0RIAaZQod4ZTAtOmokEGoARn4rfG9SCjYXN0E2SWtBACJDagABDW5UCBAAOhCsLIUlYNDw3MQAJlivW3J2FPd4HMjEAvUikvK3KpUgA)

See my longer explanation in this recent issue: https://github.com/facebook/flow/issues/5923

**Comment by vkurchatkin** [comment]
@lll000111 that is not the case. This example should work in theory. I recommend using `type` instead of `interface`. Interfaces have a lot of bugs and unexplainable behaviour.

**Comment by lll000111** [comment]
@vkurchatkin No. See the explanation in the linked issue and all those links. It's quite intentional.

**Comment by vkurchatkin** [comment]
@lll000111 interesting. Indeed, documentation describes this behaviour, but it makes no sense. There is no way to write in this case, and it works fine with `type`

**Comment by lll000111** [comment]
True, sure it makes no sense. I found the best way to explain it to myself to not suffer from cognitive dissonance issues too much while coding with Flow is that Flow looks at the actual code only very, very rarely. Most of the time it works with academic assumptions based on some pure type ideals, and looking down from that cloud number 9 level at everything that _could_ potentially happen in that theoretical universe it comes up with its sometimes strange interpretations.

**Comment by vkurchatkin** [comment]
@lll000111 the easiest way to explain it: it is a bug. When something weird is going with interfaces, it is most likely a bug.

**Comment by SamChou19815** [comment]
It seems to be fixed a while ago
