### ISSUE TITLE
Unable to create an exact object type from a sum type or $Keys

### ISSUE THREAD

**Issue by frontsideair** [facebook/flow#5945]
[Try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAEQAe5YAPhVuZrgQGqlgDe9A2oQLoAuMADsArgFsARngBOdAL7pgwMAGM4IgM4YwAQ2HEynMJWEBGMEo3bdU4e2OmLAGjBZhAJiuoV6zTrqhhwmZmDmbh5gnm4AXsIAzFZAA)

I want to create an exact object with specified keys but it seems like I can't. I also tried to use the `$Keys` typelevel function to get keys from an existing object type instead of creating a sum type by hand, but it didn't work either.

**Comment by TrySound** [comment]
@frontsideair What are you trying to achieve? Type with computed key can't be exact. It's probably should be a syntax error.

Computed key specifies all possible keys in this type. You may omit exact and get object where keys can be only `x` or `y`, but empty here is also possible.

```js
type T = "x" | "y"
type V = { [T]: number }
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAEQAe5YAPhVuZrgQGqlgDeYA2oQLoAuMADsArgFsARngBOYAL7oAxnBEBnDGACGw9mW6VhARkWpVGrVL0dDJgDRgswgExmLmsMpsGwRsMaOzmAujgBewgDMikA

If you want to specify required keys, you should describe them explicitly and use exact type.

```js
type V = {|
  x: number,
  y: number
|}
```

**Comment by frontsideair** [comment]
I was going to add my motivation but I was in a hurry so I left it out. I want to achieve this:

```
type ObjA = {|
  x: number,
  y: number,
|}

type ObjB = {|
  x: string,
  y: string,
|}
```

1. I want `ObjA` and `ObjB` to have the exact same keys.
2. I want `ObjA` and `ObjB` to be homogenous in the value types, so I want only want to write the keys, but it's not my primary objective.

I'm pretty sure what I tried to do was dumb. 😅

**Comment by TrySound** [comment]
You probably need `$ObjMap` utility type

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFYCCYAvGAN4A+qYYAHgFxgB2ArgLbF4ATgBomYLBx78ho+gF902fETIAhanUbN2YAM4ZBAS04BzUcwl6Dxs6nnoAxnE76wAQw4kKG2qw4AGYXEAsAVUJxcMMGIOABIvAFk3HAAeL3IggAoASmoAPisjUwKaXx0AcnKgy0rQoA

**Comment by frontsideair** [comment]
I think my thought process was that since I can get keys of an object as a sum type using `$Keys` utility, I should be able to do the reverse. I'd very much like to do it, so both `ObjA` and `ObjB` can be derived from a single source. I think this should be considered a feature request.

But your suggestion solves my problem right now, so thanks!

**Comment by TrySound** [comment]
It's don't think creating object from union is right. Mapping base object to another should be enough.

This probably can be closed.
/cc @vkurchatkin

**Comment by frontsideair** [comment]
Well, but when the object is not exact it works, but subtypes are allowed too: [link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAEQAe5YAPhVuZrgQGqlgDeYA2oQLoAuMADsArgFsARngBOYAL7oAxnBEBnDGACGw9mW6VhARkWpVGrVL0dDJgDRgswgExmLmsMpsGwRsMaOzmAujgBewgDMikA). I don't understand why do you think it's not right.

**Comment by TrySound** [comment]
@frontsideair It's different action. Union just sets constraints to the key. You can't set any other key, but you may not use all of them. Adding different behavior to it will even more confuse developers.

**Comment by frontsideair** [comment]
It makes sense, but then I think there should be an operator for creating an object type with a specific shape. I'll close this one though, it's probably not a bug, or the bug is not good enough error.
