### ISSUE TITLE
Object spread not handling booleans correctly

### ISSUE THREAD

**Issue by suchipi** [facebook/flow#5946]
Using booleans to spread into objects does not work correctly:

### Input:
```ts
const a = false;
const b = {
  ...(a && {}),
};
```

### Output:
```ts
2: const b = {
             ^ boolean [1] is not an object.
References:
1: const a = false;
             ^ [1]
```

### Expected Output:
```
No errors!
```

https://flow.org/try/#0MYewdgzgLgBAhjAvDAZnANhApgbgFCiSwBGSMA3njDAHR0AUCAZExQL4CUANHmzkA

Spreading `false` into an object does nothing, and if `a` was `true`, we would not spread a boolean, because we would move along the `&&` to the object. So this should be permitted.

In Chrome:
![](https://puu.sh/zGiNI/308afaff33.png)

Background: This pattern is used often when composing styles in CSS-in-JS libraries.

**Comment by lll000111** [comment]
@TrySound, @danwang Why the downvotes? It took me a while, but this actually seems to be about something factual. Whatever you think about that expression, it does not result in a boolean as claimed by Flow.

**Comment by TrySound** [comment]
@lll000111 this should probably have different message, but spreading boolean to object doesn't fill right. Though I can understand spreading `null` which has type object.

**Comment by suchipi** [comment]
For reference, here's what the relevant pattern looks like:

```js
const style = {
  display: "flex",
  justifyContent: "center",
  alignItems: "center",
  ...(disabled && {
    color: "#888",
    cursor: "auto",
  }),
};
```

**Comment by suchipi** [comment]
There is some congruity with `React.Node` being a supertype of falsy values:
```jsx
const a = false
return (
  <div>
    {a}
  </div>
);
```

**Comment by Yurickh** [comment]
I believe this is the best pattern to conditionally include a key during object declaration. 
For the people that think this isn't legal js, [tc39 explicitly confirmed that it is valid](https://github.com/tc39/proposal-object-rest-spread/issues/45).

For anyone interested in a workaround while this isn't fixed, I'm currently using:
> Instead of:
```js
const condition = false
const myobj = {
  akey: 'a value',
  ...(condition && { key: 'value' }), 
}
```

> I'm going with:
```js
const condition = false
const maybeKey = condition ? { key: 'value' } : {}
const myobj = {
  akey: 'a value',
  ...maybeKey,
}
```
Which is a solution I'm not particularly happy with mainly because of the throwaway variable, but it does the job for the time being.

**Comment by Cerberus** [comment]
I also have another workaround solution too. 🤣 
```jsx
{...Array(condition)[0] && yourObject}
```
![flow](https://user-images.githubusercontent.com/9087409/45467852-e22f9700-b74b-11e8-8ca9-12268d65a78a.png)
[demo on flow v0.80.0](https://flow.org/try/#0MYewdgzgLgBCBGArGBeGBvAUASAHT4AoBBAJxIEMBPAgM3IBsIBTASgG0AGAXRgDJeMObAGsmlAFwwA5ADcGAVyZSANDgC+LVWsyZQkWAkQAmVILyFSFalBKL23PgKzYRYybIVLV2DVsxA)

**Comment by lehainam125** [comment]
Does the project no longer maintain?

**Comment by TrySound** [comment]
@lehainam125 Do you see it's not maintained?
https://github.com/facebook/flow/commits/master

**Comment by aalises** [comment]
What's the status on this?

**Comment by goodmind** [comment]
I don't think it is right to typecast `false` to `{}` like spread does

**Comment by gkz** [comment]
This works fine now, without error: https://flow.org/try/#0MYewdgzgLgBARjAvDA3gKBjAdDqAnAVwFMAaNAXwG4g
