### ISSUE TITLE
Slow Flow performance

### ISSUE THREAD

**Issue by rexkenley** [facebook/flow#5950]
Hi

I am using flow 0.66.0. The checking performance is very slow and I use the /* @flow */ technique to limit the files flow checks. I also have this .flowconfig to exclude folders. Is there anything else I could do to see what is causing the slow performance? I have 142 js files that I use flow to check.

[ignore]
<PROJECT_ROOT>/.cache/.*
<PROJECT_ROOT>/_mocks_/.*
<PROJECT_ROOT>/config/.*
<PROJECT_ROOT>/dist/.*
<PROJECT_ROOT>/node_modules/.*
<PROJECT_ROOT>/parcel/.*
<PROJECT_ROOT>/test/.*
<PROJECT_ROOT>/xrmUpload/.*
[include]
[libs]
flow-typed
[options]
module.name_mapper='^\(.*\)\.css$' -> '<PROJECT_ROOT>/CSSModule.js.flow'
esproposal.decorators=ignore
[version]
0.66.0

**Comment by TrySound** [comment]
@rexkenley How do you use flow?

**Comment by rexkenley** [comment]
I use yarn to call "flow check"

**Comment by TrySound** [comment]
@rexkenley It's full recheck without caching. Use `$ flow` to check in development. `$ flow check` is ok on CI or with prepush hook.

**Comment by rexkenley** [comment]
Thanks! That did it!
