### ISSUE TITLE
$Subtype doesn't work sometimes

### ISSUE THREAD

**Issue by loyd** [facebook/flow#5952]
```js
function good({a: string, b: number}): void {}
function bad(number): void {}

(good: ($Subtype<{a: string}>) => void); // no error, as expected
(bad: ($Subtype<{a: number}>) => void);  // no error =(
```
[Try It](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqAOaywAmAFAN4CGAXKAM7YBOu6RANKAEYPqoAtjwCmLAL4BKBgDdYuMqCriUGHPkI8alAcLHTQchUpWIKJcgwoASAMqoe2AJ4AHEQB5aDZmw7iAfJKgALz+hvJkkgDcoCCg6LCgYiywLNw0jEkAHm44ImRmWmRWdg7Obp708UKiEoEhYUaRMbFgCUksKSwhFEA)

**Comment by TrySound** [comment]
Subtype is deprecated utility type
