### ISSUE TITLE
Annotating an object cloned with Object.keys(...).reduce(...) doesn't seem to work

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#5953]
I expected this to work:

```js
type MyObj = { foo: string, bar: string };

const lowercase: MyObj = {
  foo: 'hello',
  bar: 'goodbye'
};

const uppercase: MyObj = Object.keys(lowercase).reduce((acc, key) => ({
  ...acc,
  [key]: lowercase[key].toUpperCase(),
}), {});

```

[**Try it in TryFlow**](https://flow.org/try/#0C4TwDgpgBAsiDyAjAVlAvFA3lAZgezwC4oBnYAJwEsA7AcwBopEBDc4squqAXwG4AofgGM81MlAA2eAO4RyQ5iQjE4SVBkz8ouAsQDkACwgSpe+lqat9tAgBNEICHv59BIscCgBXMJHmLlWAQUdCg1CCFgADoAawgQEgAKKVl-JQBKKPIIWy8hCETE5iEhRjiQdPQAPihEzW0oxuLSiwBtcoBdYhS5BSV2+I6o4DwAVV85AGEAxPTzbjmsBYEgA)

Flow complains that what I'm assigning to `const uppercase` does not have the required `foo` and `bar` properties. But it does, because I'm building the object by reducing the keys of another object that contains it.

I'm not sure if this is a bug in Flow, or if I'm supposed to annotate it some other way?

**Comment by vkurchatkin** [comment]
Recognizing such patterns (which is not possible in general) is out of scope for Flow. You can always cast your value unsafely via `any`.

**Comment by JamieDixon** [comment]
I'd love for this to be possible. We've been running into the same issue and the only solution we've come to without resorting to losing the power of the type system is to manually craft the return values instead of reducing.

Having to break out of the type system (using `any`) doesn't feel like a good fit to me.
