### ISSUE TITLE
[0.67.1] - Declare module not covered by flow

### ISSUE THREAD

**Issue by yannamsellem** [facebook/flow#5954]
## Bug

I've update flow from v0.65.0 to v0.67.1 and since the update, `declare module` aren't covered by flow

#### With flow 0.67.1

Atom (with nuclide): 
<img width="390" alt="screen shot 2018-03-14 at 16 46 20" src="https://user-images.githubusercontent.com/10496045/37413510-8161d264-27a7-11e8-9627-88cf432953fe.png">

Command line:
<img width="390" alt="screen shot 2018-03-14 at 16 49 35" src="https://user-images.githubusercontent.com/10496045/37413544-9341c124-27a7-11e8-8b26-867e42f8d777.png">

#### With flow 0.65.0

Atom (with nuclide): 
<img width="390" alt="screen shot 2018-03-14 at 16 52 48" src="https://user-images.githubusercontent.com/10496045/37413740-f3c6bae0-27a7-11e8-86d0-9fab88ab30a9.png">

Command line: 
<img width="390" alt="screen shot 2018-03-14 at 16 53 37" src="https://user-images.githubusercontent.com/10496045/37413778-07ec6754-27a8-11e8-93ba-a9a2b29b2ffc.png">

I've also tried with flow v0.66.0 and v0.67.0 same issue, it only works with v0.65.0 and below

#### Config

flow: v0.67.1
node: v9.7.1

**Comment by mrkev** [comment]
Is this still an issue with v0.70?

**Comment by Brianzchen** [comment]
Works in 0.132.0

<img width="499" alt="Screen Shot 2020-08-28 at 4 56 55 pm" src="https://user-images.githubusercontent.com/12436524/91531527-45725e00-e950-11ea-83aa-bf5feaab7122.png">
