### ISSUE TITLE
Flow doesn't recognize when Array.filter() filters out specific types

### ISSUE THREAD

**Issue by EvHaus** [facebook/flow#5955]
The following code:

```
/* @flow */

const arr: Array<?number> = [1, null, 2]

const cleanArr: Array<number> = arr.filter((a: ?number): boolean => a !== null);
```

Returns the following Flow errors:

```
5: const cleanArr: Array<number> = arr.filter((a: ?number): boolean => a !== null);
                                   ^ Cannot assign `arr.filter(...)` to `cleanArr` because null or undefined [1] is incompatible with number [2] in array element.
References:
3: const arr: Array<?number> = [1, null, 2]
                    ^ [1]
5: const cleanArr: Array<number> = arr.filter((a: ?number): boolean => a !== null);
                         ^ [2]
```

In my case, I have an `arr` array that has `null` values, but I want a `cleanArr` array that strips those nulls out via a `filter` function. It seems that flow doesn't recognize that `null` values were removed and still warns me that `cleanArr` can contain `null` values when it certainly doesn't.

Repro: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMAnEgLjAEEyiBPAHgH5sBXAWwCMBTEgPjABeMAG0AjABowbGDCkAmALroseQhhjci2GhWq1GbLrwHDSJAHRQAljHy8AFA6KUWHHiQCUlTnDibtIQEiMABCQWEZGE8AblQgA

**Comment by vkurchatkin** [comment]
See https://github.com/facebook/flow/issues/1414
