### ISSUE TITLE
How do I use generics for function returning function returning function?

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#5956]
[Flow Try example code](https://flow.org/try/#0C4TwDgpgBAag9gSwCYB4AqA+KBeKA3RJKAHyjQG4AoSgYzgDsBnYKGgJwgENgIBBRkPRoBRNmzhsA6m05hIbHFAAUlKGqgNR4tgC5lWiQEocWAskrHsWFeqgAzenqUA6V5zYBzRnt5jOIFAAqDEssAAVxAFsERgggjAsTKE4BIWVVdVdndy8fPwDgiz0IuGjYlHhkeKwrKABvDLVgNhB6xtsoAHpOsgALaEYEABshkABaIbg4AGsEeg8oACJOAHdOBGBFqAh6TgAjIYhGKGB+k5bOmm4aXvsJE7OwKJiIdtsOYABXNnpktY37PQXG5PIxDFRbABfVjXW5KCBiYwNDrqBFsZzMTg0aZQADUuCU9AgKygBjYSkMhgxwCx0whKI09DJ8MR9LUkMokKolG6UAAymhhGEoABGKBjKAAYQ43Gg0lk8loDGYjLJihZulJYiMSToTDgh2ckw8GvBSqYLDREnlcgRinYXB4-EEIm1UhktvJmjdZp5PQFQqgACZxVBeHJRg9oCsPfITnBGdB7pEJNA7J8hMAEMq-VKZTxkvYMzQswwHtwoES8HaPt8mIWOAArCAliBEJ6lF7mlWMUp8VI0ABivwJoSgJTKEGcHF7Q2rSjqdimegALEGADRQPbuPQAciXcF3kLNep7fedQmHNsgRFwVvdCoRSl7kX7LuHvt5AeFAGZQwBJegCGmaBTmjWM2yLTNs3oSgXzfS96GvNsKUoZwwKBGdPiGFhamRKAEDsZQsJwnBsFwDMkAgOw5jbJF2lPA0p2NJRd0o6jaKQXczXZbYhliNpbEYw0WJI4BnAPHj1GE5i4BNMTnAAOQAeQAfT5ABVSUAAlVLQbT-0UgBxKSOWPKggA).

The example(!) use case here is a function call in three steps for an "asynchronous error wrapper" used for asynchronous functions that must not create rejected promises, e.g. because they are used as event callbacks from somewhere else or called decoupled through `setTimeout`. They have to report errors not to their caller (which may not even be there any more) but it has to be redirected somewhere.

1. Call a function that takes an "onError" callback that gets called for errors - return a FUNCTION. This function (this onError callback) can be used to wrap several functions.
2. Take the function from step 1 and use it on functions that we don't want to throw (or return a rejected promise)
3. Use the wrapped function instead of the original, its errors go to the callback from step 1. It returns `undefined` when there is an error instead of the return type of the function from step 2.

<br>
Now, my question is unnecessary in the described use case because nobody cares what the function returns.

But just for arguments sake, let's say I use the wrapper "inline" instead of the original function and actually use the returned value (in this case I would not use the wrapper because I could just let the error bubble up).

How could I use generics to use the return type of the function from step 2 as return type of the function created in step 3? I already added a `Void<T>` wrapper for "void | T" results, which would apply to the wrapped function.

When I use some `<T>` I don't get very far, I would have to use it across several functions. Flow does not complain when I do that, but the result does not work, I get an error basically saying something like "undefined doe snot equal undefined", for example.

Code (more in the above Flow Try link, here only the relevant part &mdash; and here I add my `<T>` experiments, there is a "*" in the Flow Try code, but Flow is unable to detect anything):

```js
// For convenience, I actually use this, and another one for `null`, in place of "?" which
// unfortunately means both but often I only want either undefined or null
type Void<T> = void | T;

const createAsyncErrorWrapper = (
    onError: (Error) => void
) => <T> (
    fn: (...args: Array<*>) => Promise<T>
) => async (
    ...args: Array<*>
): Promise<Void<T>> => {
    try {
        // The silly-looking "await" enables the try/catch for the promise
        return await fn(...args);
    } catch (err) {
        err.stack += (new Error()).stack;
        onError(err);
        // I could also rethrow the error, so the callback is like a T-pipe to inform a 3rd party
    }
};
```

I can also put the initial outer `<T>` in front of the step 1 function, no change.

**Comment by stereobooster** [comment]
[Is this what you are looking for?](https://flow.org/try/#0C4TwDgpgBAag9gSwCYB4AqA+KBeKA3RJKAHyjQG4AoSgYzgDsBnYKGgJwgENgIBBRkPRoBRNmzhsA6m05hIbHFHQYAFJSgaoDUeLYAuKCp0SAlDiwFklM9izK1mqADN6BlQDpPnNgHNGB3jFOEBQAKgwbLAAFcQBbBEYIMIxrcyhOASElTAdNT3dvPwCgkPDrAxi4eMSUeGRlLFsoAG91TWA2EBa2xw0Aej6yAAtoRgQAG3GQAFpxuDgAawR6HygAIk4Ad04EYDWoCHpOACNxiEYoYBHLzr6abhoh5wlL67A4hIge3o5gAFc2PR0ttds56B4vL5GCYqI4AL6sB5PFQQMRmVq9TSotjuZicGgLKAAalwKnoEE2UGMbBUJhMuOA+IWsMxWno1JRaJZGjhlDhVEoAygAGU0MIolAAIxQaZQADCHG40GksnktAYzDZ1MUnP0VLEpjSdCYcDO7jmPl1MPVTBY2IkKrkqMU7C4PH4ghEBqkMidNO03utgsGovFUAATDKoLw5FNXtBNr75Jc4GzoC9YhJoE4-kJgAgNcH5YqeOlnLmaPmGK9uFByXhnb8AUwyxwAFYQSsQIjvKqfG2axhVPiZGgAMSBpMiUEq1Qg7g4Q-GDZUzSc8wMABZwwAaKDHbwGADk67gR7h1uNg+HHqEE8dkCIuHtPtVqJUQ9iI89E6DQtDEoAMxRgAkvQBALNAVwJkm3blnmBb0JQn7fne9APt2tKUO40HgoufzjCwTQYlACBOIY+GETg2C4LmSAQE4yzdui3xXqa84WioR50QxTFIEe1o8gc4yJN0jhsWanGUcA7inoJmgSRxcCWtJ7gAHIAPIAPrCgAqnKAASWloAZIFqQA4vJvIXlQQA)

```ts
type Void<T> = void | T;
const createAsyncErrorWrapper = <T>(
    onError: (Error) => void
) => <T>(
    fn: (...args: Array<*>) => Promise<*>
) => async <T>(
    ...args: Array<*>
): Promise<Void<T>> => {
    try {
        // The silly-looking "await" enables the try/catch for the promise
        return await fn(...args);
    } catch (err) {
        err.stack += (new Error()).stack;
        onError(err);
    }
};
```

**Comment by lll000111** [comment]
The important value is the return value of the wrapped function, for which you use the now deprecated "*".

I ended up using this, but I have not fully tested if it provides full type support:

```js
type Void<T> = void | T;
type ExtractReturnType = <V>(() => V) => V;

const createAsyncErrorWrapper = (
    onError: (Error) => void,
    rethrow: boolean = false
) => <T: Function> (
    fn: T
) => async (
    ...args: Array<mixed>
): Promise<Void<$Call<ExtractReturnType, T>>> => {
    try {
        // The silly-looking "await" enables the try/catch for the promise
        // Returns the function's result or "undefined" if rethrow is false
        return await fn(...args);
    } catch (err) {
        err.stack += (new Error()).stack;
        onError(err);

        if (rethrow) {
            throw err;
        }
    }
};
```

**Comment by lll000111** [comment]
I'll close it because my particular problem is sort of solved. I'm not so sure about it in general though.
