### ISSUE TITLE
crypto.[randomFill, randomFillSync] are missing from the library definition in node.js

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/flow#5959]
Not in here: https://github.com/facebook/flow/blob/v0.67.0/lib/node.js#L477

But in here: https://nodejs.org/api/crypto.html#crypto_crypto_randomfillsync_buffer_offset_size

**Comment by idiostruct** [comment]
Sure, feel like putting up a PR?

**Comment by lll000111** [comment]
@idiostruct I think this _is_ a PR (_Push_ Request) :-)

**Comment by mrkev** [comment]
I think it's a valid response; nothing wrong with asking people for PRs. A lot of the stale PRs tend to be more complex and so harder to write and merge, but library definitions should be more straightforward.

Given how much other work there is to do and looking at the number of issues open I can say just opening issues isn't any better ¯\_(ツ)_/¯

**Comment by SamChou19815** [comment]
It's there now
