### ISSUE TITLE
Can't dynamically access a class property with $Keys

### ISSUE THREAD

**Issue by B-Reif** [facebook/flow#5960]
Reproduction: https://flow.org/try/#0C4TwDgpgBAQghgJygXigbymBB7MAuKAZ2AQEsA7AcygF8AoAY23OKgFsR4ECuV1Mc+KACJhtANyNmrShGBcACoL4AKANYQQBACQBpTYQA8XAHwAaKADc4AGwCuEAsTJUAlChP8EcuwnLtORABtDRAAXVooAHooqGw1AEI6Rhs4QkIoADFsbH4sXCcSCkpxWikWYADs3NRyCAB3LJzJJgqoWWBqpVxVUJ19ECNq8ytbB0KXSndkTzQ6AEhvYF9-DmqQzTDSmKgAUQQcBASoAGE4cnJsSrTCUkp-ACMIBjg7QmhzqAoAEwgADwgSHykAQoC+GTYpHSxTo9CAA

When I have a function that takes a $Keys of an Object, I can then use that argument to get a computed property on an object of that type. I was expecting to be able to do the same with $Keys of a Class type, but that seems to expect an indexable type, even though I know the property belongs to the class's $Keys.

**Comment by idiostruct** [comment]
It's a known [bug](https://github.com/facebook/flow/issues/4014); here's a workaround: [Try Flow](https://flow.org/try/#0C4TwDgpgBAQghgJygXigbymBB7MAuKAZ2AQEsA7AcygF8AoAY23OKgFsR4ECuV1Mc+KACJhtANyNmrShGBcACoL4AKANYQQBACQBpTYQA8XAHwAaKADc4AGwCuEAsTJUAlChP8EcuwnLtORABtDRAAXVo6Rhs4QkIoADFsbH4sXCcSCkpxSKYWYACklNRyCAB3ROTJPJk5IqVcVVCdfRAjIvMrWwcMl0p3ZE80OgBIb2BffwAlCAAzGwgGYAA6WWAVDiKLUNdJeiA).

**Comment by jcready** [comment]
A simple workaround is to just have your class `extend Object`. All classes extend Object anyway, so it makes no difference at runtime.

**Comment by idiostruct** [comment]
Nice! Much simpler than Reflect which most likely requires a polyfill.
