### ISSUE TITLE
Function cannot infer type when return a closure

### ISSUE THREAD

**Issue by zhujinxuan** [facebook/flow#5964]
Hi, this is a simple function that:
https://flow.org/try/#0FAMwrgdgxgLglgewgAhAUxlAFgHgCoBcA3hAIYC2aBAzjAE5wQDmAvgHwAUAHgXgJTIiyYMlFQktZHTTUwAGxjICyDnwC8bPMjUr1bLgG4Ro6TDB0U02QuAtgoSLEQpSEBDCxo6+YmUo16RlZOHn5lLSJjKQxzFHRMLG4+VVsgA
```
function fetch<T:{name:string}>(x:T) { 
   const result : ()=>T = ()=>x;
   return result
}

function another<T:{name:string}>(x:T): T {
   return fetch(x)()
}
```
It gives an error that:
```
8:    return fetch(x)()             ^ Cannot return `fetch(...)()` because object type [1] is incompatible with `T` [2].
References:
3:    const result : ()=>T = ()=>x;
                         ^ [1]
7: function another<T:{name:string}>(x:T): T {
                                           ^ [2]
```
It is strange that the T in `fetch` function is thought differently from the T in `another` function.

**Comment by vkurchatkin** [comment]
You need to annotate return type explicitly: https://flow.org/try/#0FAMwrgdgxgLglgewgAhAUxlAFgHgCoBcA3hAIYC2aBAzjAE5wQDmAvgHwAUAHgXgJQFkHPgF42eZEWTBksqElrI6aamAA2MZIOFiJIoaLZcA3DNnKYYOimWqNwFsFCRYiFKQgIYWNHXzEyShp6RlZOHn5BCSIzJQwrFHRMLG4+YQcgA

**Comment by btford** [comment]
Why does adding a type constraint on the return type change the behavior? This is pretty surprising to me tbh.
