### ISSUE TITLE
Flow v0.68.0 crashes on Windows

### ISSUE THREAD

**Issue by horprogs** [facebook/flow#5966]
`flow.exe check ` crashes with Fatal error: exception Unix.Unix_error(1, "socketpair", "")

Flow v0.68.0
Windows 8.1 Professional x64
Node v8.9.3
Yarn 1.3.2

I haven't any ideas about this..

**Comment by masaeedu** [comment]
@horprogs Flow 0.68.1 doesn't work on https://flow.org/try either.

**Comment by lll000111** [comment]
Related: https://github.com/facebook/flow/issues/5583

@masaeedu There is no 0.68.1

**Comment by masaeedu** [comment]
0.68.0

**Comment by mrkev** [comment]
Is this still an issue with newer versions of flow?

**Comment by lll000111** [comment]
Sure! Flow on Windows is a real party crasher. I now develop in a Linux VM - only one crash in three weeks. Windows: from crash to crash. I think Facebook has zero developers in a Windows environment.

**Comment by budarin** [comment]
![default](https://user-images.githubusercontent.com/8055157/41035898-d26be5ba-6996-11e8-9f56-1947be544be7.png)

Windows + Webstorm - regularly crashes for a few minutes of work with the project

**Comment by stevenalanstark** [comment]
v0.75.0 won't even start for me in Windows. 

v0.66.0 takes about 10 minutes to start up, and 0.75.0 was starting up for over an hour before I gave up and uninstalled it.

FLOW on Windows is completely unusable.

**Comment by usagene** [comment]
We ran into this socketpair error with 0.74.0 in windows 10 as well. It feels like the support for windows is very limited.  It is a bit of concern for companies like to use flow in windows.

**Comment by mroch** [comment]
we've fixed a lot of Windows issues this year. I'm going to close this, please file new issues for anything that still crops up on recent versions (e.g. v0.185+). thanks!
