### ISSUE TITLE
Flow suggesting superfluous annotation

### ISSUE THREAD

**Issue by ghost** [facebook/flow#5970]
[try flow](https://flow.org/try/#0KYDwDg9gTgLgBAQwM4E8B2BjOAzArpmASwjTgHNg0AeAFQD4AKMKCAW0KWAC44AFF9p1p04AHzg0AlD35sOwKgG0AolBZQANHDS4ANroC6YuIp36tNAyIDeAKDhwYUFHDsOHUYDFxRSpvbpaDAgA7giE8MxynDxSBgDc9nAAvnAYCDAYABZwDPgwKGDAACaqUJKuSQ4YJEjwwGo87CAlxmXQcAC8cPmFJWWJ7nCE2LkNUMNodQiYwBCj7eWVQx5ePn7jWmaGg+6pwLqcyyue3r4mDGjAIXCLDOPSt2rQklsBCVUpScm2yUA)

```js
1:  export async function gen<T>(promise: Promise<T> | T): Promise<[Error, null] | [null, T]> {
2:    try {
3:      return [null, (await promise: T)];
4:    } catch (untypedErr) {
5:      const err: mixed | Error = untypedErr;
6:      if (err instanceof Error) {
7:        return [err, null];
8:      } else {
9:        return [(new Error(err): Error), null];
10:    }
11:  }
12: }
```

On line 7 flow sees `err` as an `Error`.  And it suggests annotating it.  If I annotate it to `Error` it's happy.  Why do I need to annotate `(Error: Error)`?  😆

**Comment by MarkKahn** [comment]
Oh, and the annotation on line `9` seems completely unnecessary as well!

**Comment by stereobooster** [comment]
```ts
export async function gen<T>(promise: Promise<T> | T): Promise<[Error, null] | [null, T]> {
  try {
    const x:T = await promise
    return [null, x];
  } catch (untypedErr) {
    if (untypedErr instanceof Error) {
      const err: Error = untypedErr;
      return [err, null];
    } else {
      const err: Error = new Error(untypedErr)
      return [err, null];
    }
  }
}
```

**Comment by SamChou19815** [comment]
It works now
