### ISSUE TITLE
Flow reporting errors in the wrong places

### ISSUE THREAD

**Issue by cglacet** [facebook/flow#5978]
I can't really reproduce this bug with a minimal example as I don't really understand how it happens, but it happens quite often. 

Flow is reporting an error on some places when the problem comes from somewhere else (down in the type tree). The error should always show up for the most specific object, never for an ancestor. But it seem like it is not the case with flow I captured an occurence where it is pretty obvious that there is a bug: 

```es6
type Position = [number, number];
type MultiPoint_1 = {
  type: 'MultiPoint',
  coordinates: Array<Position>
 }; // OK
type MultiPoint_2 = {
  type: 'MultiPoint',
  coordinates: Array<Position>
}; // Not OK
```

If the declaration of `MultiPoint_1` is valid, then the declaration of `MultiPoint_2` should be. Also, if they are valid they should always be, independently from all other types (unless there are name collisions). But for some reason I have the following error showing up: `Only tuples and array literals with known elements can flow to Position` for one of the two and not the other (this makes no sense as the only difference between them is the type name). This is a very problematic bug as it makes it impossible to find where the real problem is. In my project, this code does not rely on anything and this therefore on top of the type hierarchy. It should therefore be correct everywhere or incorrect everywhere.

**Comment by stereobooster** [comment]
Can you post example in the [playground](https://flow.org/try/#0C4TwDgpgBACg9gZwJbCXAdlAvFA2ugVwFsAjCAJwBopDSKBdAbgChRIoBZAgG1XiXTAA+gEZsUAN7MoUNhABcUAORdeSfoKWVpUAMZw45ACYCAhsAgJFAQXLlTIADzxkqDAD5pAX0ZQA9H5QAPIA0qzg0Kp8cALCAEziUjJyiio80bFaOvqGJujmljZ2Ds6IKGjonj7+gQBycMDBYcxAA)?

**Comment by cglacet** [comment]
Like I said, the error shows without any apparent reason, on this particular piece of code (even though it doesn't rely on anything). I couldn't extract a (simple) setup that would make this code fails. 

If I recall correctly, the error is generated here depending on how the two types are used. 

Or maybe it was coming from the fact that another definition of `Position` was interfering. 

Sorry, it's been a while I don't have the error available anymore. I'm pretty sure it's one of these two reasons that caused the bug to appear.

**Comment by SamChou19815** [comment]
Not enough info to repro
