### ISSUE TITLE
[0.68.0] Error when checking existence of property in union types

### ISSUE THREAD

**Issue by azangru** [facebook/flow#5979]
Flow version: 0.68.0

**Background:** according to the [latest blogpost](https://medium.com/flow-type/new-flow-errors-on-unknown-property-access-in-conditionals-461da66ea10) by the Flow team, version 0.68.0 should be able to check the existence of a property in different branches of a union inside the conditional.

**Problem:** if one of the members of the union type is an intersection type, this breaks.

**Example:**

```
type A = {|
  +foo: string,
|};

type B = {|
  +bar: string,
|};

type AB = A & B;

type C = A | B;

type D = B | AB

function thisWorks(baz: C) {
  if (baz.foo) {  // <-- no errors
    let { foo } = baz;
    return foo;
  }
}

function thisDoesnt(baz: D) {
  if (baz.foo) {  // <-- error   ╯°□°）╯︵ ┻━┻
    let { foo } = baz;
    return foo;
  }
}
```

[example on try Flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKBqAZgezwC4oBnYAJwEsA7AcwBo0UBfAbjTVEigCEFl0mLACMAhuWJkqdRi3adw0GH0RwAZL3ldoAYX5wUmjtqgARfn0PKOOAK7UAxsEp5qUYAAtKJAOp5yANYkABRiAF7EOgCUyBhQlDhQoaJhAHT4eDFIcZgANhDAyFAZUMz84eyYmOQFtuRuGZWlaMw29k4ubp7epngQJNTAyRFmWXEJSeHpBGNVUPmFSMUEpeUpTdW19ct4Ta3MQA)

**Comment by apsavin** [comment]
[Workaround](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKBqAZgezwC4oBnYAJwEsA7AcwBo0UBfAbjTVEigCEFl0mLACMAhuWJkqdRi3adw0GH0RIoAOk0x6GzXzYcu0AML84KXvKNQAIvz4XlHHAFdqAY2CU81KMAAWlCQA6njkANYkABRiAF7ExgCUyBhQlDhQMaKx6vh4yUipmAA2EMDIUHlQzPxx7JiY5GUu5L559dVozM5unt6+AUE2eBAk1MBZ8bYFqemZcbkEMw1QpeVqVTWIdUVQTcAtbQQd3cxAA)

**Comment by azangru** [comment]
Cool! Thank you.

**Comment by azangru** [comment]
As a follow-up, I saw in a [pull request](https://github.com/facebook/flow/pull/5973/files) an explanation of why you aren't supposed to use intersections for exact object types (as was the case in my example), but even if I [remove](https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUDUAzA9jgXFAM7ABOAlgHYDmANCgL4DcKKokUAQgsmpgEYBDUoRIUa9Zq3bQY3RHABkXFm3DQAwjzgAfFdPVQAIj2565rLAFdKAY2DkclKMAAW5IgHUcpANZEACiEAL0INAEpedHIsKCDBYIA6XBxI1HR0ABsIYGQoFKgGHhCWDKhSHKtSZxTSwsZLG3tHZzcPIxwIIkpgeNDjNL4YuJDkvEGy7NykfLxC4oS69ArgKpq8OoZGIA) exact object types and change them to regular object types, the error still persists.
