### ISSUE TITLE
error with RegExp

### ISSUE THREAD

**Issue by chad-ding** [facebook/flow#5981]
why this can be an error.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKASgC4wBnfAJ0OwHMwBvVMMGAKb5GLWk1YcwAXjAByAIYAjXLIDcvfkLDMB7AKIAPAA60ASrsNHpYYJSW5qwdXx37jAOnwCmlcdWfaQpjMpOZuRu4AJACM6gC+qEA

**Comment by apsavin** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/n

> This feature is non-standard and is not on a standards track. Do not use it on production sites facing the Web: it will not work for every user. There may also be large incompatibilities between implementations and the behavior may change in the future.
