### ISSUE TITLE
Union Type missing properties

### ISSUE THREAD

**Issue by apolishch** [facebook/flow#5983]
Say I have the following types:

    type MessageType = 'example1' | 'example2' | 'example3'
    
    type MessageHead = {
      +type: MessageType
    }
    
    type BaseBody = {
      +payload?: any,
      +data?: any
    }

    type LabelledBody = {
      +labelName: string
    }
    
    type MessageBody = BaseBody | LabelledBody

    type Message = MessageHead & MessageBody

And I then consume a message like so:

    [{name: 'example1'}, {name: 'potato'}].find(thing => thing.name === message.labelName)

Resulting in the following flow exception:

    Cannot get message.labelName because:
     • all branches are incompatible:
        • Either property labelName is missing in MessageHead [1].
        • Or property labelName is missing in BaseBody [2].
     • ... 1 more error.

With `type Message = MessageHead & MessageBody` being displayed as the violated type

What I don't understand is why my Union Type doesn't allow for a message with a labelname?

Tryflow link:[Tryflow link][1]

  [1]: https://flow.org/try/#0C4TwDgpgBAshDO8CGBzCAVc0C8UDkEAHkgLZgA2EAjHlAD75GkUQBMtDBxZlAzHgCgBoSLATI0ACQhIAJlFwBvAVCgBqERABcYxKgxYBAXyGaoAISTwI5gPayQCqMtVqwSEOVtyA-DqQAdiAANCrqskjASH5QgSDGplhQADJIAEYQ5JSydg5OLurk6ZkAcqTaUPDAAE4AlgEoCcJJcHpouY64ltYd9CnFWRA59vHNoq0SOLqT0nJQAGTT+h1CAMa2AVVQRABiAK4Bq04AFCTi+joT+gCUCgB8zmEA2ooB5TpczJQ0RsHOb2cPmBbFFgLY8EYALoAOgAZvVZMdgAALeooe5QFFo6EAnDYXBnNoQaFFDLkMpna7GIA

**Comment by jodhman** [comment]
Just encountered the same problem.
Hopefully someone can give a heads-up on this.

**Comment by elramus** [comment]
+1

**Comment by langri-sha** [comment]
If I present things a bit differently:

```
type Message = (MessageHead & BaseBody) | (MessageHead & LabelledBody)
```

It makes perfect sense that either `MessageHead` or `BaseBody` needs to have the `labelName` property for it to be safe to access it on the `Message` union.
