### ISSUE TITLE
object property is not working

### ISSUE THREAD

**Issue by bichikim** [facebook/flow#5986]
```javascript
/* @flow */

export interface IRouters {
  base?: string,
  get?: IRouterInfo
}

interface IRouterInfo {
  [string]: string
}

const a: IRouters = {
  base: 'hi?',
  get: {
    'this is string!!!!': 'stttring',
  },
}
```

refer to:
[link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcwBLAO0I3ygEMBjDMASQCU4BXS-AZzAG9UYMACMa3DAH4AXGG6F85AOYAaQWEUZC05m05UmZKHFQBfdOS60GOjlwNH+agNpyFZRQF0ZrpafR04MjkwGhlWWypeAF5HIVFxGQByAAsSCUTVIQ1CGQEhIUTCVN4SXh93AEIqisSkuUJ5JQy1E1UTIA)

I cannot use object type since Flow is not supporting object type fully 
The get object properties types are string and I made the object  however Flow throw an error 'Cannot assign object literal ...' 
Is this a bug,  having no feature or I don't know how to use Flow?

https://flow.org/en/docs/types/objects/#toc-objects-as-maps

+ only working in this way

[working](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBLAdgFwKYBOUAhgMZ5gAqeAzjmAN6phj53YDmA-AFyPMswAbToFOAXT6jOAgL6p5qUnCx1WtHH2pqAvI0VscAOkOcwehvMMmNnIQHJi98ebD2AFhnuogA)

**Comment by TrySound** [comment]
@bichikim Interfaces are buggy. Use type aliases.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMASQCU4BXQjfAZzAF4wBvVMMAIwCGLDAH4AXGBaF8ASwB2AcwA0vMIoyEJ1Oo2ZV5UOKgC+6MhR0Mm+A0Y7c1AbWlylAXUmuFi0+gDGcPLSYIKStNbMbJw8fEIikgDkABayoomqfBqEkrF8YImEqWyybN5KAIRVFYlJ0oQyPhlqJqomQA

**Comment by bichikim** [comment]
@TrySound I'll do thanks
