### ISSUE TITLE
New Versions make Flow >REALLY< Annoying

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#5987]
Apparently we can no longer support dynamically looking up values in a class instance?  This completely breaks flow for me.  You don't even support indexer properties in classes yet you apparently 100% require them or throw errors ?

There are quite a few places this new behavior essentially make Flow unusable and require hard-coding like every detail of every possible scenario into your code.  On average to make ti work thus far I have added about 100% more code since it cant infer anything well.

---

Note that obviously the below doesn't make much sense but in my actual use case I am working with an interface and classes which are derived from the base class so it looks different.  This just shows the overall problem.

# [Try Flow](https://flow.org/try/#0FAYwNghgzlAEAqBTKAXWBvYBIA9gOwGEcBbABzERUQAoBKDYWJ2AX0efwCEBXASzAAmdBs1bA2ofKlgALHDgDWcALywA8gCMAVohAoAdADMATokQAvGpib4iZClQBcsPIgDusAMqU6AGnZcfILOrh7eKHTitMDAhtx4erz4sMbxABLySsLWzCBSaKSwqqEIyBHRWJo6evoKiACeUNRyilC0RjjGAKIQIDLNmUUAfCKisLyGsNQo9aSIOJOkANotCgC6RcqqAERxCShJeNv0OWOymVArmWv6EAJCpLQA3OyibG-P4kA)

```js

class Test {
    onComplete() {
    }
    onBuild() {
    }
}

const hooks = Object.freeze({
  onComplete: new Set(),
  onBuild: new Set()
})

function runHooks() {
    const p = new Test()
    Object.keys(hooks).forEach(hook => {
      if (typeof p[hook] === "function") {
        hooks[hook].add(p);
      }
    });
}
```

**Comment by bradennapier** [comment]
On top of that if you attempt to add an interface that actually support indexer properties it breaks because then the class can NEVER be compatible since you cant do indexer properties in classes.

This is messed up.

**Comment by jcready** [comment]
Just make your base class `extend Object`. It will make no difference during runtime since all classes extend Object implicitly anyhow, but it makes Flow happy.

**Comment by bradennapier** [comment]
Sweet!  That worked although a bit ugly :-P thanks!
