### ISSUE TITLE
Array<number>.slice() cannot be assigned to Array<?number>

### ISSUE THREAD

**Issue by karelbilek** [facebook/flow#599]
I have a code like this

```
var foo: Array<number> = [1,2,3];
var bar: Array<?number> = foo.slice();
```

I have it like this, so I can later put `null`s into `bar`. However, flow doesn't like that. What's wrong?

**Comment by runn1ng** [comment]
I rewrote it like 

    var foo: Array<number> = [1,2,3];
    var bar: Array<?number> = foo.map(i => i);

But that's just crazy.

**Comment by xjamundx** [comment]
Similar issue?

```
let parts = "22,33".split(',')
let formattedAmount = parts.slice(0, -1) + "." + parts[1]
```

```
num.js:4
  4: let formattedAmount = parts.slice(0, -1) + "." + parts[1]
                           ^^^^^^^^^^^^^^^^^^ array type. This type cannot be added to
  4: let formattedAmount = parts.slice(0, -1) + "." + parts[1]
                           ^^^^^^^^^^^^^^^^^^^^^^^^ string
```

**Comment by vkurchatkin** [comment]
The problem here is that `slice` returns `Array<T>`. Since arrays are invariant you can't assign `Array<T>` to `Array<?T>`.

`map` works, because it return `Array<U>`, and `U` is inferred to be `?T` in this case.

**Comment by runn1ng** [comment]
Ha, this is an old issue.

I still don't know how to do this properly though.

**Comment by vkurchatkin** [comment]
Ideally, we need a way to mark `slice` as returning new or unreferenced instanced. I experimented with using `Array<T | *>` for this purpose and seems to work.

**Comment by TrySound** [comment]
This can be achieved with `$ReadOnlyArray` type
https://flow.org/try/#0G4QwTgBAZg9jBcEAkAlApiAJgeQHYBsBPAQTDBEIB5cBXAWwCM0wA+CAXggG0BGAGgBMfAMwBdANwAoUJAbhEqDDgIkyFSgH5ajZm06wYAOgDO+AJYBjNAAoAlOKA

Can we consider this as solved?
/cc @vkurchatkin

**Comment by vkurchatkin** [comment]
No, I don't think so. This should work for mutable arrays, ideally

**Comment by SamChou19815** [comment]
This is working as expected
