### ISSUE TITLE
String or Object type issue

### ISSUE THREAD

**Issue by yantakus** [facebook/flow#5990]
How do I avoid Flow throwing an error (Property `name` not found in String) in this simple use case:

```javascript
function foo(value: Object | string): string {
  return value.name || value;
}
```

Here's the repl: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKANwEMZMBTALjAHkAjAK0YLAB8wAZ3wAnQtgDmASlYjxUsAG9UYMKMb5Mo0nQaMAdNloBbRgMF6mAblQBfVEA

**Comment by apsavin** [comment]
Like [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKANwEMZMBTALjAHkAjAK0YLAB8wAZ3wAnQtgDmASlYjxUsAG9UYMKMb5Mo0vgCeAB0ZwoYOg0ZgAvDbAByeRMl2wAfjP0mYVuaYA6bFoAW0YAblQAX1QgA), for example.
