### ISSUE TITLE
Add a `flow/flowtype` field in package.json to give a path to types that should be exported

### ISSUE THREAD

**Issue by saadq** [facebook/flow#5994]
TypeScript has a `"types"`/`"typings"` field that you can put in `package.json` in order to point to the declaration files that should be included in the output package. It would be nice if we could do that rather than using something like `flow-copy-source` or adding extra build step processes to copy the `.flow` files into the `dist`.

**Comment by TrySound** [comment]
Duplicate of https://github.com/facebook/flow/issues/2675

Also I think `.js.flow` files are even more expressive since they are not restricted to one entry point. There are a lot of cases which requires "path" imports like `import { renderToString } from 'react-dom/server'` and they requires more than one field.

So as a great solution you may create a build step without dependencies
```js
"scripts": {
  "build:flow": "echo \"//@flow\n\nexport * from '../src';\" > dist/index.js.flow"
}
```

**Comment by saadq** [comment]
Thanks, closing as a duplicate.

**Comment by saadq** [comment]
@TrySound But I should mention that this is kind of an issue when contributing libdefs to projects that aren't written with flow types. If I want to contribute flow type definitions to a project itself rather than using `flow-typed`, I have to make sure that the `index.js.flow` file is in the same folder as the `index.js`.

I'm basically running into this issue when trying to write a Flow libdef for `chalk`: https://github.com/chalk/chalk. They already have a `types` folder, so it would be nice if I could just drop a `index.js.flow` file in there and point to it in `package.json` rather than having to put the libdef and tests for it in the root project folder, which makes it kind of disorganized.

**Comment by TrySound** [comment]
Well, `types` is mostly typescript convention. Different tools have different cases.

**Comment by saadq** [comment]
Yeah, agreed. But both Flow and TypeScript definitions in a repo should have three things – a config file, a type definition file, and a test file. It would be great if having a structure like this was possible:

```
types/
├── flow
│   ├── index.js.flow
│   ├── test.js
│   └── .flowconfig
└── typescript
    ├── index.d.ts
    ├── test.ts
    └── tsconfig.json
```

**Comment by saadq** [comment]
As a sidenote, this is what the PR I sent ended up looking like: https://github.com/chalk/chalk/pull/260/files
