### ISSUE TITLE
Type compatibility - optional property is missing

### ISSUE THREAD

**Issue by levenleven** [facebook/flow#5997]
```javascript
type WithOptional = {
  optional?: string,
  required: string
}

type WithoutOptional = {
  required: string
}

const foo: WithoutOptional = { required: '' };
const bar: WithOptional = foo;
```

[Results](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDqAlhgBYDyOGxcAdgIYxgC8YA3qmGHNbYzAD8ALjABnDACdidAOYAaLmEl4AjgFdiKgCaiJ0uagC+6bPiKkycdRio16TVhyUqNWvLvFSZs4+gDG9BJgUHBwoiTk1rZ8Dsxs7MpqmjqiAORpYEYA3KiBdMEARgySEZZ2-I5soXDZQA) in: 
> Cannot assign `foo` to `bar` because property `optional` is missing in `WithoutOptional`  but exists in `WithOptional`.

Why optional property is required here, but `const foo: WithOptional = { required: '' };` is perfectly valid?

**Comment by apsavin** [comment]
Because if you'll do

```js
bar.optional = 'string';
```

it will add a property to `foo`, but `foo` typed as `WithoutOptional`.

**Comment by levenleven** [comment]
@apsavin So why `const foo: WithoutOptional = { required: '', optional: '' };` is allowed?

**Comment by lll000111** [comment]
Well observed @apsavin 

Another way to see it is to remember that in Javascript variables pointing to non-trivial types are "memory pointers", so you end up with two pointers of structurally unequal types pointing to the same memory space.

**Comment by levenleven** [comment]
@lll000111 I know I didn't specify an exact object type - so it should apply to original question, otherwise it doesn't make any sense

**Comment by lll000111** [comment]
@levenleven Please read my comment [here](https://github.com/facebook/flow/issues/5997#issuecomment-374604785).

**Comment by levenleven** [comment]
@lll000111 Again, I know what are exact types. This has nothing to do with the original question. 
If `const foo: WithoutOptional = { required: '', optional: '' };` is allowed, then there shouldn't be any problem with `bar.optional = 'string';`

**Comment by lll000111** [comment]
Please read my comments, I answered this question. You don't seem to read my comment.

**Comment by apsavin** [comment]
@lll000111 just try to look on it from the @levenleven point of view.

Obviously he read your comment and obviously your explanaition isn't enough. Can you try to explain it event better?

**Comment by lll000111** [comment]
@levenleven You can't have two variables of structurally different types pointing to the same memory object (structural typing is used for objects by Flow, nominal typing would not work in any case anyway).

**Comment by lll000111** [comment]
@levenleven You can't have two variables of structurally different types pointing to the same memory object (structural typing is used for objects by Flow, nominal typing would not work in any case anyway).

In your example specifically, you make the initial memory allocation for the small object (without optional property). Then you declare a variable of a type that is supposed to point to a larger amount of memory and assign the pointer form the small object.

**Comment by apsavin** [comment]
@levenleven 

Also, you can see a problem in the following example:

```
type WithOptionalString = {
  optional?: string,
  required: string
}

type WithOptionalNumber = {
  optional?: string,
  required: number
}

type WithoutOptional = {
  required: string
}

const foo: WithoutOptional = { required: '' };
const bar: WithOptionalString = foo;
bar.optional = 'string';
const baz: WithOptionalNumber = foo;
baz.optional = 5;
```

If `flow` would allow assignments as in your original example, the code above would be allowed, too, I suppose. It leads to errors.

**Comment by levenleven** [comment]
@lll000111 Now I see where we see the problem in different ways - I think that these types are structurally equivalent and you don't.

**Comment by levenleven** [comment]
@apsavin That makes much more sense

**Comment by lll000111** [comment]
Please count:

```
type WithOptional = {
  optional?: string,
  required: string
}

type WithoutOptional = {
  required: string
}
```

Two properties on top, only one below. Clearly NOT the same. And "equivalent" only if you use the transparent Javascript automatisms which let you get away with not being clear about object types (do you know that under the hood the JS runtime is/has to be much more exact about those types? It has to allocate concrete amounts of space after all)).

But since you voluntarily entered the "type world" and its restrictions what is true in Javascript is not true here &mdash; those types are _different_, and very clearly so. Space has to be allocated for teh optional type two, it's always there for the type system!

**Comment by levenleven** [comment]
@lll000111 I understand, but I don't think memory allocations are relevant here. In real typed language you also can't do the following (the other way around), but you can do it in flow:
```
const foo: WithOptional = { required: '' };
const bar: WithoutOptional = foo;
```
P.S. Flow has nothing to do with memory allocations, see above normal explanation by @apsavin

**Comment by lll000111** [comment]
@levenleven The memory allocation is of course not directly relevant, I used it to show that the TYPES are different.

> Flow has nothing to do with memory allocations

You don't say!

**Comment by jedwards1211** [comment]
what's sad is that `const bar: $ReadOnly<WithOptional> = foo;` doesn't work.

**Comment by SleepWalker** [comment]
For those who will land to this page here is an example with two possible solutions:

https://flow.org/try/#0C4TwDgpgBA6glsAFgeTMOB7AdgQwDZQC8UA3gD4BQUUGamueA-AFxQDOwATnFgOYA0VKJwgBHAK5wRAE1YdufCmQC+AbgoVQkWAkQZxwVOmz4ipStRESpEWey49eStRoDG2DlABmGDK3hI+oZ0JgTEJMJikjKsAOSxUC4U7lieAEY4nKwAJABKEDjSyFh4IAA8ASghDAB8Zj4Y6inpOABe-rpG9KbhAHT9DWpAA
