### ISSUE TITLE
Error incorrectly pointing at object generation instead of `null.method()` call

### ISSUE THREAD

**Issue by ghost** [facebook/flow#5999]
I can't reproduce this on try flow as it seems to only happen with imported code (is there a way to simulate this in try flow??), but here's the [try flow](https://flow.org/try/#0PTAEEMDoCsGcCh4BMCmBjANuATi0AzAVwDs0AXASwHtjQASYwjLAIwxQEEB3cCsgHgAqAPgAUABwBcoAArYqAWwqwUQ4aAA+oQQEppgzaEbMA3PBQAPcVWxkCJctVoBzFMUEALCsWdDpHbGxwAE9+JQsUJGExSFjxeSUVWH09WQTlVTpBQnF2AFlwcSEAGlAyYPEUKnx6Y1Z2bl4yaNAAbwBfRBBQFhgEeAoFa1s20Fd3Lx9QdoIE0ABySGBwebN4cFhg0ntSShoCKipRHTb4UFA0Glg7AG1wAF1QAF4IHj4xt09vZ1EARgAmADMOjW5yg+EOZk6QA) link anyway

```js
// a.js

declare function $nullableAwait<T>(p: Promise<T> | T): T | null;
export function genThing<T: Array<mixed>>(...promises: T): Promise<$TupleMap<T, typeof $nullableAwait>> {}

// b.js

import { genThing } from './a';

async function foo() {
  const [a] = await genThing(123);

  a.foo;
}
```

The issue is that on the last line `a` is possibly null, but the error I'm getting points at `await genThing(123)` and says:

```
[flow] Cannot call await with `genThing(...)` bound to `p` because an indexer property is missing in `Promise` [1]. (References: [1])
[Flow]
genThing: < T: mixed[] > (...promises: T) => Promise < empty >
```

Sorry for the somewhat convoluted test case, I can't seem to simplify it much more

**Comment by hwfwalton** [comment]
I'm now hitting this same issue :\

**Comment by SamChou19815** [comment]
The issue is likely fixed a long time ago
