### ISSUE TITLE
function overloading

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#60]
I would like to express a function with the following overloading:
```typescript
<B>(func: () => B): () => Promise<B>;
<A,B>(func: (a:A) => B): (a: A) => Promise<B>;
```
it seems to me that it is not possible since : 
```typescript
<A,B>(func: () => B | (a:A) => B): () => Promise<B> |  (a: A) => Promise<B>;
```
Does not conditionally constraint the return type, any idea ?

**Comment by avikchaudhuri** [comment]
The following should now work, closing.
```
declare function foo<B>(func: () => B): () => Promise<B>;
declare function foo<A,B>(func: (a:A) => B): (a: A) => Promise<B>;

foo(() => 0)(); // OK
foo((x: number) => "")(); // error: too few args, undefined ~/~ number
```

**Comment by leoasis** [comment]
Is it possible to set overloading types for function without using `declare`?

**Comment by AgentME** [comment]
@avikchaudhuri Is there a way to do that while also defining the function?

**Comment by pronebird** [comment]
It does not work in other contexts as @leoasis pointed out. such as when defining a function. Flow is not able to select the right combo.

```
// @flow

type State = Array<number>;
type GetState = () => State;

type Action = { type: 'A' };
type Thunk = (dispatch: Dispatch, getState: GetState) => Promise<any>;

type Dispatch = ((action: Action) => Action) | ((action: Thunk) => Promise<*>);

const dispatch: Dispatch = (action) => {
  if(typeof action === 'function') {
    return action(dispatch, () => { return [1]; });
  }
  return action;
}

dispatch({ type: 'A' });
dispatch((dispatch, getState) => Promise.resolve());
```

**Comment by hackhat** [comment]
```
// @flow

const items = [1, 2, 3];

type FirstType = ((_: 'a') => number) & ((n: 'b') => Array<number>);

const first: FirstType = (n):any => {
  if (n === "a") {
    return items[0];
  } else if(n === 'b') {
    return items;
  }
}

const a: number = first('a');
const b: Array<number> = first('b');
```

Is partially working. From https://stackoverflow.com/questions/45481046/how-to-define-a-type-of-return-based-on-an-argument-string-flowtype-javascript

**Comment by morajabi** [comment]
Any progress here? I think it's a quite important feature.

**Comment by zeorin** [comment]
Interfaces seem to have the behaviour you're looking for: https://github.com/facebook/flow/issues/3021#issuecomment-404156975.

**Comment by lll000111** [comment]
@zeorin Your linked example does not show how one would define a function. I'm not quite sure *what* it does, actually, there doesn't seem to be any Javascript, just Flow type stuff. How would one use that to do something real, with JS code?

**Comment by trusktr** [comment]
Can someone please provide a fully working example, not just `declare`d type examples?

**Comment by trusktr** [comment]
I tried making a function intersection as people have suggested, and making a real example, but it doesn't work:

<img width="748" alt="Screenshot 2024-10-27 at 1 05 50 PM" src="https://github.com/user-attachments/assets/3a8a77f8-ebab-4f21-b85c-d2a1a396284b">

[flow try](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQAOj5VgACACCbDYnIAvJz2ZyAGScgAUEvkyE5whEN14nNosvlNwAlIKAHxy64mdUi8VSmWc+ymKAIJUq01SCoITUCnVmu0GqDs2z2TnsNiy3n8oXSq0OnXAEWclgSISUKCc+ScgDUyoA3Oz6ezciAGiYSHBoEkGgAGKwAJgArEWCyB6UA)

**Comment by StreetStrider** [comment]
@trusktr 
[This seemes to work](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQAOlANE8qNgAAQwB7KODQPnEHkACgwyB5aGIzygvGlUplEDlAEopQByACMGoA3OzObhuXyBfCoCKIOLJTzhCIbgq0FL7KYoAh1TyNQAmPXs-mPM0Wq1S4G0B3BqC0VXs4Ds9n02OPaD2HkADR5AF4eTHzTz5FKYMQxVIIjzi9hVbx2TyebR84WtQqNRgNRWqzyAF5ausQMUagDulGgCA1jYHQ5blZz7c93d7Y9dE7b7YAzLPW1B41B2StjDyACoZ0urCAwVPs3IgBomEhCqBJBoABisnoArE+HyB6UA).

**Comment by trusktr** [comment]
@StreetStrider in the previous example, if I make the implementation parameters type `any`, the error persists:

<img width="815" alt="Screenshot 2024-10-28 at 4 35 07 PM" src="https://github.com/user-attachments/assets/5881e1ad-6d3b-41b1-a763-19a11f115ebb">

[Flow Try](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQAOj5VgACACCbDYnIAvJz2ZyAGScgAUEvkyE5whEN14nNosvlNwAlIKAHxy64mdUi8VSmWc+ymKAIJUq01SCoITUCnVmu0GqDs2z2TnsNiy3n8oXS2XA2hWoNQWgOnXAEWcuAwSUrYwQePyQUCoUAcjVJgzYvFiewyeVacz2coGddnKrnJYEiElCgnNTAGplQBuGN4Mix+MSgtF1PpzPOi250X51ZF2glzkZkcICsxqu1+uNlvt9kxiS1SgQADus4zHag9M3UG9EoAjEqAEyui8ZjAkNgwDNKx-P1+u9kAeh-nILTkTF3ShJQQYg2HvPkr3fJ8X0XKBchABoTBIOBoCSBoAAYrBvABWHCsJAekgA)

How do we fix that one?

**Comment by StreetStrider** [comment]
@trusktr 
[Maybe like this](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQAOlANE8qNgAAQwB7KODQHnsNg8gAU8mQPOEIhuvB5tGlspuAEpldcTABudmc3DcvkC+FQEVsMWS6X2UxQBAKpU8q0VBDqh1SJ062BGoUm0USqUiqC0O3S4G0VU84Dsnk8uAwCUrYwQOPyHkAXnTPIA5CqTJmeQAyfM8hPYJOKtMZ7OayiZ1VR6M8lgSISUE0pgDUio90bwZBjcfFJbLKfTqazjptecLxdWZdoFbHmYnCFr9ejTZbbZ5ndoHvrElqlAgAHcs5mPfT2ezReKAIwKgBMdagN8zGBIbBgmYVb4-X+f7IAPSATOxg8iYR6UBKCDEGwz43veWbvp+q5QLkIANCYJDekkDQAAxWA+ACsBF4SA9JAA).

The error message remains quite good as well.

**Comment by trusktr** [comment]
That's interesting, I have not seen that method explained anywhere, including Flow docs on [Overloaded functions](https://flow.org/en/docs/types/functions/#overloaded-functions).

<img width="715" alt="Screenshot 2024-10-28 at 6 37 58 PM" src="https://github.com/user-attachments/assets/705e7b8b-aee5-4006-84e3-3a59ecb21aa9">


But what's the difference? Is there a bug with the intersection method?

**Comment by StreetStrider** [comment]
> But what's the difference? Is there a bug with the intersection method?

I can't remember how I figured it out, but this is quite a reliable way to do this in both TS and Flow. It kind of creates proper overload, that's all I know. When you use intersection, sometimes it creates an «incorrect» intersection, considering function overload. Maybe someone with internals' knowledge can clarify.

> including Flow docs

In my opinion, Flow docs was never good. There were a lot of vague spots. So a lot of info became a sort of folklore. It is good to ask questions in tracker from time to time. Sometimes someone with better knowledge may help. This is what helped me in the past.
