### ISSUE TITLE
$Call should understand function unions

### ISSUE THREAD

**Issue by villesau** [facebook/flow#6003]
$Call would be decent way of doing conditional types if it would understand function unions.

let's say i have a situation where I have following object:

```
const obj = {
  a: true,
  fn: (props: {a: Object}) => {}
}
```

and when changing top level `a` to `false`, definition is following:

```
const obj = {
  a: false,
  fn: (props: {/* no a defined */}) => {}
}
```

If `a` is true, fn receives property `a` in function `fn`, otherwise `fn` does not receive `a`. The object might contain arbitrary number of similar flags which defines fn function interface.

This could be possible to do with $ElementType and $Call like follows:

```
type Call<T> = $Call<T>;
type Mapper = ((true) => {a: 'props related to AB.a being true'})
  | ((false) => void)
        
type AB = {
  	a: boolean,
	b: boolean,
  	fn: ({b: Object, a: $Call<Mapper, $ElementType<AB, 'a'>>}) => void
}
```

But $Call get lost when there are unions for mapper functions. If this would work, it would allow quite powerful ways of defining library definitions.

Now if there is for example 5 properties which alters `fn` interface, it requires 2^5 different definitions. Even better would be some more sophisticated way of defining types conditionally. Good example of this is react-measure: https://github.com/souporserious/react-measure which has flags to alter what onResize callback gets.

 See [try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDCAhjDADwAqAfGALxgAkJZV1A3JrgQLLE74ATvTAAKURkEBXPAEp6tAN7EAXGADkOQXBwBnMILwxiGPABMwGOGACCAIQB0xMACM8ASwB2Ac0vS86gC+sqhgYAA+AAXiUKS6cgpgAG5w7mYhYZmZXPi2diKKoWAAkKqucHAweMSeADSoxS5qLhVVNfVhxVCeaqKKTWAA8i4AVngAxhi1YGXMpBR8AniC04wAolUAtnieGJTc5PbT6sTq1NTBiSlpqIHo43CeuhhgUFKe4yKiWjq6avbyOhKO6oN4fPplSQyaYDWIweLTbq9H56QFKBoPJ6VPAOeDeb7aPROEKBYJAA) for details.

**Comment by SamChou19815** [comment]
Closing since $Call is deprecated
