### ISSUE TITLE
No error when using Object.assign to copy an incompatible object

### ISSUE THREAD

**Issue by jlong4096** [facebook/flow#6007]
Why am I not getting an error if I use Object.assign to make a copy of an incompatible object?

Reproduction:  https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQIYBO+AtqALygDeiooKAliVgM4qkYBcobhDAdgHNEAX2QhQASVBYAHtgDGKegAsckWNDjwBg0NAE4UsUJHwNoAGlD5+AE1ANld2KwB0iEADcioDAEZuAmIySip6JlZ2Ei5QAFd7LEhDBxEAbnEwaTlFZRQ1U01tXX1DehMzC2sAIzjlJ1AXVn4AchQ3OgB1FTQAfkQfQj8AJiCiUgpQAHlqgCssJTd8FhYGQX4ACioRa3DGZjYObgS7JJTQEQBKNKA

In the above example, p1 produces an error (which I expect), but p2 does not produce an error.

Thanks for the help!

**Comment by SamChou19815** [comment]
It now errors
