### ISSUE TITLE
React.ComponentType<{address: string}> doesn't accept component with {address?: string}

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#6009]
I'm making a users view where I can inject a custom component for rendering each user.
The users view will render this component with `name` and `address` props for each user.

If I inject in a component that requires both the `name` and `address`, Flow accepts it.
I should also be able to inject a component where `address` is optional, since there is no danger in always passing it an `address`.  But Flow considers this an error; this is a big obstacle to writing views where I can easily customize specific subcomponents.

### UPDATE
Using `+address?: string` in the component implementation makes the error go away.  But should it be necessary to mark `address` covariant? React Components aren't supposed to modify their props anyway.

Another solution is to use `address: $Supertype<string>` in `UserCardComponent` (and perhaps use `$Supertype` for all props).

### Code [try flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK4CeGVUAFVSVbAGFi2ACagAvJU64AdOOZYAdlQ24AKvyoAeAN6JQoDcTRUAXKFK5sKDQHMANGZLTpHUqTsOTq4eAL4AfJ6IkACuGvQosBqgHBrSYiJipABqKFTwABSSMnYZElLSAJR21HQqAHKwaaCm5hy40dhJ+Z7mhtIoAG4R5iOghgAWAIxhpaSGwFPDo2NFspbWcgBEAIKpvJtePlR+W9vRDs5uoLoAGgfAS73A-UOeFYghkXwCwqJlMgBJTDQAAKTAw5AULQsVls9kczncnmI3l8pAA-AEEcEPshaIkHL8xKsgRhoPJQPkMOD-ET-tJSaCaRV5GExi8wsZqbAIcp1lQQvMOcgUmlsLMcnl8qUScCKkA)
```js
// @flow

import * as React from 'react'

type UserCardComponent = React.ComponentType<{
  name: string,
  address: string,
}>
  
function renderUsersView(UserCard: UserCardComponent): React.Node {
  return (
    <div>
      <h1>Users</h1>
      <UserCard name="Andy" address="Austin, TX" />
    </div>
  )
}
  
type UserCardImplProps = {
  name: string,
  address?: string,
}

const UserCardImpl = ({name, address}: UserCardImplProps) => (
  <div>
    <h2>{name}</h2>
    {address ? <h3>{address}</h3> : null}
  </div>
)

renderUsersView(UserCardImpl)
```

### Error
```
31: renderUsersView(UserCardImpl)
                    ^ Cannot call `renderUsersView` with `UserCardImpl` bound to `UserCard` because undefined [1] is incompatible with string [2] in property `address` of the first argument.
References:
21:   address?: string,
                ^ [1]
7:   address: string,
              ^ [2]
```

**Comment by samwgoldman** [comment]
Using a covariant property is the correct answer to this question.

**Comment by jedwards1211** [comment]
@samwgoldman so in essence, the Flow docs should really be advising people to make all properties of every React Component covariant...
