### ISSUE TITLE
Flow should never consider React Component props readable

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#6010]
I guess we should always be marking our component props covariant, but should Flow really allow writing to component props under any circumstances?

In other words shouldn't `StatelessFunctionalComponent<Props>` essentially be equivalent to the following, and likewise for `React.Component`?
```js
(props: ObjMap<Props, <T>(t: T) => $Supertype<T>>) => React.Node
```

```js
// @flow

import * as React from 'react'
  
type UserCardImplProps = {
  name: string,
  address: string,
}

const UserCardImpl = (props: UserCardImplProps) => <div>{props.name = 'foo'}</div>
```

**Comment by samwgoldman** [comment]
`$Supertype` is not the same as read-only. In fact, all writes are allowed to a `$Supertype` property.

You're right that React props should be immutable objects, although React does not enforce that internally. The best way we have currently for expressing that is through covariant property annotations, which is what you should use.

**Comment by jedwards1211** [comment]
@samwgoldman is there any way to turn all properties of an object type covariant with any utility types?  I can't seem to find a way...

**Comment by saadq** [comment]
I think [`$ReadOnly`](https://flow.org/en/docs/types/utilities/#toc-readonly) is what you're asking for?

This:

```js
type Props = {
  +name: string,
  +age: number
}
```

is the same as

```js
type Props = $ReadOnly<{
  name: string,
  age: number
}>
```

**Comment by jedwards1211** [comment]
@saadq oh, thank you, I somehow hadn't discovered `$ReadOnly`!

**Comment by jedwards1211** [comment]
@samwgoldman is there a reason you guys didn't decide to make `StatelessFunctionalComponent<Props>` essentially `(props: $ReadOnly<Props>) => React.Node`?
