### ISSUE TITLE
0.68.0 regression: if (typeof module.hot === 'function') causes error

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#6011]
[Try flow link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWlQAoAuBPADgKazoC2sAJgK7QEB0AFrFqALxugDkklAdgMZYUsHhwCUoAN6JQoRAF9EQA)

Error does not occur in prior versions:
```js
// @flow

if (typeof module.hot === 'function') {
  
}
```
```
3: if (typeof module.hot === 'function') {
              ^ property `hot` is missing in object type [1].
References:
[LIB] static/v0.68.0/flowlib/core.js:809: declare var module: {                                                              ^ [1]
```

**Comment by samwgoldman** [comment]
This is an intentional change. See [Gabe's medium post](https://medium.com/flow-type/new-flow-errors-on-unknown-property-access-in-conditionals-461da66ea10), also linked from the [Flow blog](https://flow.org/blog/).

It seems like `module.hot` is a non-standard addition (Webpack?). The solution here is to override the libdef for `module` with all the non-standard additions that you rely on.

**Comment by jedwards1211** [comment]
@samwgoldman I get that but prior versions would also flag `module.hot` property accesses as an error, but allow us to use `typeof` to check for an unexpected property.  The following code works in 0.67.1 but not 0.68.0, are you sure this is not a regression:

```js
// @flow

type Foo = {foo: string}

const f: Foo = {foo: 'hello'}

if (typeof f.bar === 'string') {
  console.log(f.bar)
}
```

**Comment by jedwards1211** [comment]
Edit: I thought that prior versions would flag `if (module.hot)` as an error but allow us to explicitly check with `typeof`, like `if (typeof module.hot === 'string')`.

It would be nice to still have someway of checking for an undeclared property on an object that produces a refinement, so that references to that property don't need to be checked within the `if` block.

**Comment by samwgoldman** [comment]
Yes, this is by design.
