### ISSUE TITLE
Errors suppressed on react Component when imported by a lib

### ISSUE THREAD

**Issue by ckknight** [facebook/flow#6014]
Here is a minimal repository with the bug: https://github.com/ckknight/flow-libs-bug

On line 6 of `src/App.js`, `this.props.nonexistent()` is called, which _should_ be a type error.

By having the following lines in `.flowconfig`:

```
[libs]
flowlib/
```

and a file within that folder:

```js
// @flow

import { Component } from 'react';

declare module 'foo' {
  declare module.exports: any;
}
```

Regardless of whether `foo` is referenced anywhere else, the `import { Component } from 'react';` line causes flow to view `Component` as `any` within unrelated code.

**Comment by Leeds-eBooks** [comment]
@sibelius Sorry, I'm unclear as to whether imports outside of module declarations are supported or not?

**Comment by sibelius** [comment]
https://github.com/flowtype/flow-typed/issues/2023
https://github.com/flowtype/flow-typed/issues/1857
https://github.com/flowtype/flow-typed/issues/1857#issuecomment-371312890

**Comment by ckknight** [comment]
@sibelius sure it _should_ be `import type { Component } from 'react'`. Instead, my errors were completely swallowed with zero indication that there was a problem. That's the real issue.

**Comment by mrkev** [comment]
Closing in favour of the referenced issues
