### ISSUE TITLE
Flow is unable to infer return type, loops forever

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/flow#6017]
Hey there, we have noticed a pattern where some combination of inferred return types and conditional recursion cause Flow to seemingly loop forever.  

An example is here: https://goo.gl/fDQ4mc

Because Flow will loop forever, I went ahead and placed a return type annotation on the function.  If the annotation is removed, Flow will analyze forever.  Be careful with your browser tabs!

**Comment by sibelius** [comment]
this does not happen on flow 70, can u test again?

**Comment by EdwardDrapkin** [comment]
I made a screencast:

[flow-screen2.zip](https://github.com/facebook/flow/files/1939535/flow-screen2.zip)

GH won't let me upload the video file, so I had to put it in a zip, but it's there.

**Comment by sibelius** [comment]
no errors on flow 77

you can type like this

`type Payload = string | Payload[]`
