### ISSUE TITLE
Union types incompatible when it shouldn't

### ISSUE THREAD

**Issue by felippepuhle** [facebook/flow#6020]
I'm trying to type an i18n file but I got a really strange bug.

This is what my i18n file looks like:

```
type ScreenTranslationType = {
  title: string,
};

type AppTranslationType = {
  dependents: ScreenTranslationType,
};

export const pt: AppTranslationType = {
  dependents: {
    title: 'Meus dependentes',
  },
};
``` 

I have to convert these nested object keys into `dependents.title`, so, I created a simple helper:

```
type InputType = {
  [key: string]: string | InputType,
};

type OutputType = {
  [key: string]: string,
};

const handleI18nKeys = (input: InputType, prevKey?: string): OutputType => {
  return Object.keys(input).reduce((accumulator, currentKey) => {
    const newKey = prevKey ? `${prevKey}.${currentKey}` : currentKey;
    const currentValue = input[currentKey];

    if (typeof currentValue === 'string') {
      return {
        ...accumulator,
        [newKey]: currentValue,
      };
    }

    return {
      ...accumulator,
      ...handleI18nKeys(currentValue, newKey),
    };
  }, {});
};
``` 

But if I use `handleI18nKeys(pt)`, the following errors are thrown:

- Cannot call `handleI18nKeys` with `pt` bound to `input` because `ScreenTranslationType` [1] is incompatible with string [2] in property `dependents`.
- Cannot call `handleI18nKeys` with `pt` bound to `input` because string [1] is incompatible with `InputType` [2] in property `dependents.title`.
- annot call `handleI18nKeys` with `pt` bound to `input` because string [1] is incompatible with `InputType` [2] in property `title` of property `dependents`.

Any tips what I could be doing wrong?

-----

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMoGMAnTTAOwBUCBDEgZ2kuQEtZyNsBeUAb0VFCeTRMALlA1kBRiQDmAGkQBfANyIUbUAEF06CtToNmrLKE48+AE0xYSlkshqj8RUrtr0mLMm3nLVeFuKg6MiiWjpUbgae6qa8oJbWtvaiZnz8jIIioADkALKYAK408VakSZg02fJ8Cj4qiCCgABaY0FgEasYAkiToBchexrF8ANoA1pioouKSMgC60xJS0qAAPqA9fQPeivVoxgDy-VuDHNxx45OLs9ILYksydX4ByM3U5kJdAIwAHCQA0pNipwABRSLaiTb9U6yIJEABugNQAH5rssAJSiI7IE4xAB85z4RGQBQIJFABwARgArTB4ZAAOgmqBoYN6-XRDKI5gKeEwIJBlDweAKAFsCu5YARYSKCEQ7Ej0SYCak+P5aK8SJh4EiTHDMIjJqBkaAAAYAEi46ARSIUDMtsvlyFtptAokdpGdkxUaVA6sCHrsADVKNACmdwf0RoGvag5vVfYxIKAQftMLBkzGQ2GOOxONkZstskrVWliaTyaXfQya0KReLJdK4r7RlqdZM7lnQ+Hqi3fL6FKpfeWyYSWzWGXWxRKGFLe9Wa013p9fgCgSCuznYW3FfPQP397CuAp0SpfA0wEVloglzYV38kazgqegA

**Comment by apsavin** [comment]
[fix](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMoGMAnTTAOwBUCBDEgZ2kuQEtZyNsBeUAb0VFCeTRMALlA1kBRiQDmAGkQBfANyIUbUAEF06CtToNmrLKE48+AE0xYSlkshqj8RUrtr0mLMm3nLVeFuKg6MiiWjpUbgae6qa8oJbWtvaiZnz8jIIioADkALKYAK408VakSZg02fJ8Cj4qiCCgABaY0FgEasYAkiToBchexpwAJABKmJTmAPIk0KgAPKkA2gDWmKii4pIyALqbElLSoAA+oD19A96KAHz1aMZT-ReDHNxxq+v729J7YgcydT8AWQzWo5iEXQAjAAOEgAaXWxU4AAopBdROd+i9ZEEiAA3BGoAD8X0OAEpRI9kM8Ytc3nwiMgCgQSKApgAjABWmDwyAAdGtUDRUb1+mS+URzAU8JhkcjKHg8AUALYFdywAg4pUEIh2Qlkkx01J8fy0EEkTDwQkmXGYAnrUBE0AAA2GXHQ+MJCj5bu1uuQXudoFEftIAfWKjSoFNgVDdgAapRoAVXmj+ks4+HUDt6lHGJBQMj7phYAXM4nkxx2JxsltDtkDca0ozmaym1G+Z2FUrVerNXEo3wlharetfuWkynqoPfFGFKooy2WfTB52+d2VWqGBrpx3O00wRCYfDEciJ5WcSP9bvQLPbziuAoySpfA0wEVDogDzYj7DCcLgmfIA)

**Comment by felippepuhle** [comment]
It works! Thanks @apsavin
