### ISSUE TITLE
TypedArray.sort should return a TypedArray instead of void

### ISSUE THREAD

**Issue by julienw** [facebook/flow#6021]
See https://github.com/facebook/flow/blob/67976eb88989ce93ebcf3f6a4f617e5b696a6765/lib/core.js#L700

[According to MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray/sort), TypedArray.prototype.sort returns the TypedArray. I guess `void` should be changed to `this` in the definition.

For example the following code is valid javascript, but triggers a Flow error:
```javascript
const uint8 = new Uint8Array([40, 10, 50, 20, 30]).sort();
console.log(uint8.indexOf(40));
```
[Here is the code on try](https://flow.org/try/#0MYewdgzgLgBArgSzFAHDAvDMBTA7jAVSVQEEAnMgQwE8AKAbQBYAGAGhgEY2YBWbgJm4BmZgF0AlADoIIMlFriA3AChQkEABtskjSADmtRMhSSkAE2wAPAPIAzWi3FKgA)

**Comment by goodmind** [comment]
lol, this is hilarious

**Comment by julienw** [comment]
So, what's blocking progress here? I just got the same issue again :-)
