### ISSUE TITLE
Promise.finally should be added

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6023]
Bumping #5810 - Promise.finally is available in major browsers and is Stage 4.  It should be added to the core definitions.  Thanks!

**Comment by lll000111** [comment]
You can just leave a comment in #5810 to "bump", instead of opening a new issue. Because it's not a new issue.

**Comment by bradennapier** [comment]
Happy to close it.  Just wanted to make sure an item that is now being implemented into the wider ecosystems was seen rather than buried in months old issues that may never be seen.
