### ISSUE TITLE
The flow server is not responding : / Out of retries

### ISSUE THREAD

**Issue by chiaweilee** [facebook/flow#6025]
- Webstorm
- Vue 2.5.13
- Babel 6.26.0
- Webpack 2.7.0
- babelrc
`"plugins": ["transform-runtime", "transform-vue-jsx", "transform-flow-comments"],
  "env": {
    "test": {
      "presets": ["es2015", "env", "stage-2", "flow", "@babel/preset-flow"],
      "plugins": ["istanbul", "lodash", "lodash-fp"]
    }
  }`
- Webpack dev / prod
`plugins: [
    new FlowBabelWebpackPlugin()]`
- flow-babel-webpack-plugin 1.1.1

Sometimes, this happend...
and It will not resolved even restart the npm dev or IDE..

> ERROR  Failed to compile with 1 errors 
> Flow: Out of Retries
> 
> The flow server is not responding (3 retries remaining): -The flow server is not responding (2 retries remaining): \The flow server is not responding (1 retry remaining): |The flow server is not responding (0 retries remaining): /
> Out of retries, exiting!

I used flow to check one file only these moment, and it's..

```
// @flow
export default (store:Object) => {
  // watch lang
  store.watch(
    state => state.system.lang,
    (lang:string) => {
      window._V_.$i18n.locale = lang
      window._V_.moment.locale(lang)
    }, {
      deep: true
    }
  )
}
```

and I run flow check, 0 error(s) found.

**Comment by pronebird** [comment]
Same issue with `0.83.0`. Just goes in loops.

**Comment by cmmash** [comment]
Facing the same with version `0.74.0`

Why is this closed? What's the resolution?
I simply get this:
```
 (1386)-> yarn flow
yarn run v1.13.0
$ /home/ash/projects/upkeep/web-app/node_modules/.bin/flow
The flow server is not responding (0 retries remaining): /
Out of retries, exiting!
error Command failed with exit code 7.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```
