### ISSUE TITLE
Using Flow with extended classes produces unexpected behavior

### ISSUE THREAD

**Issue by hellsan631** [facebook/flow#6026]
I'm using flow with Firestore, and really love the typings it gives me for my data. However, im getting some errors that are preventing me from using 100% typesafe stuff.

**Case 1 error**:  ```GenericReference is incompatible with CampaignReference```

example: https://goo.gl/wgo8H8

Here i'm trying to extend the base class ```GenericReference``` with ```CampaignReference``` and override some of its returns, for better type hinting.

There is some generic database code that expects```GenericReference``` as a type. The type signature of the two classes are exactly the same.

**Case 2 error**: ```Cannot extend `GenericReference` with `CampaignReference` because `CampaignSnapshot` is incompatible with `GenericSnapshot` in type argument `R` of property `get`.```

example: https://goo.gl/bCsyN9

Here is where things are really weird. For each object in the database, i'm creating a data type to represent the actual object data, and extending the base classes and overriding their methods with this new data type. So we can reference this type stuff in code and get some hints as to what's in each object.

```ts
const campaignSnapshot: CampaignSnapshot = await campaignRef.get();

// has type hinting of whats inside this object!
campaignSnapshot.data()
```

This is solvable by changing the ```Generics``` to use type ```any``` instead. The generics are used elsewhere, and this removed all type hinting.

Any help or insight into how I could impliment these behaviors better would be appreciated.

**Comment by SamChou19815** [comment]
First error is expected. To make the second one pass, make the function readonly
