### ISSUE TITLE
Flow can't seem to understand export * from file 

### ISSUE THREAD

**Issue by pizza-r0b** [facebook/flow#6027]
Example:

**c.js**
```js
export function someFunc(){}
```

**a.js**
```js
export * from 'c.js'
```

**b.js**
```js
// flow says someFunc is not exported from a
import { somFunc } from 'a'
```

**Comment by TrySound** [comment]
Did you tried this?

c.js
```js
export someFunc(){}
```

a.js
```js
export * from './c.js'
```

b.js
```js
// flow says someFunc is not exported from a
import { somFunc } from './a'
```

**Comment by pizza-r0b** [comment]
@TrySound that seems to fix it. I was importing from `./module` changing it to `./module/index.js` fixed it. Thanks

**Comment by pizza-r0b** [comment]
@TrySound to be more specific I am using yarn workspaces to include different packages across apps. This recently became an issue. I didn't used to see this error

**packages/moduleA/someFile.js**
```js
export someFunction() {}
```

**packages/moduleA/index.js**
```
export * from './someFile';
```

**packages/moduleB/index.js**
```js
// Cannot import someFunction because there is no someFunction export in moduleA
import { someFunction } from 'moduleA'
```

**Comment by GhostxRipper** [comment]
I think that @TrySound was trying to say is to use the keyword `function` between your `export` and the name of your function

**Comment by pizza-r0b** [comment]
@GhostxRipper - sorry that was a syntax error while typing my example of the issue.

**Comment by chrissantos1995** [comment]
I'm getting this same error whenever using the `export * from ./file` syntax

**Comment by pizza-r0b** [comment]
@chrissantos1995 you need to make sure **every** file has the `// @flow` comment

**Comment by arekzelechowski** [comment]
I lost some time today because of this. I was upgrading `react-scripts` regularly but I have forgotten about `flow-bin`. Make sure to update it to more recent version (not sure which one introduced support for this syntax).
