### ISSUE TITLE
typeof function can be re-bound, producing union type

### ISSUE THREAD

**Issue by jtbandes** [facebook/flow#6029]
[flow.org/try demo](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEEAuMAciPLAF4KqBudLPQqARlrAAoBKWgHw8A3gEMyRAL68mLAmCgAmMn0Ejx9ctK4cmqYMDAAifAE8ADgFM4UMAHN2RsKJjwEuMHHwALSwCcwADcXAFdLD3w4MFxvUT9LZzAzKzAEAEsfe3ZyD0RsMDTsDLSXNIAvfwAafUMMURDcQrswb05IsAAjSywAWwTRMBCinAA6MbAACURLQKqwABIAYRcYaMtLHoioqDg-DASfA4sDuBrOhPjcOBhZgBNnbHvzPzhbkP2I3zBLAA8rDHwlnu-heflwI2YOHkDi4qhoQm4Ygk0lkUMIdmUSWONiysP48PUZAALIoUWAwAZUt5TGBbnBwklvGkPAhdgBrAD8mDR9gAzCp8UIlisADzJay2BxCOhwhFIsAkskUwwIam0+mfZlgZ6vd4JRTfPyg3Bc7msFqcGWCwnEFFm+TeTGym2ULT4i0McmU1U0ukM0T5EG7ZzmKxxFr+C6WKCR7AYJotXlcuSEbz8rFWHGtPFqREaRUyL0qtV+zUs9mmlOeS1gYQFAW5+VSfiSVHmtLsMjinFwdgjNI5gl54mkwveksaxla1l+TmQ81wA10OtpBtDpvaVv2whpTHzAAKLysfjMABVjmLsbZF5UKGlyNKeNbhwrR57x77Jz5pxX5-I4LyXArmucoaM2YBblWaTps6wquJembXry-aPs6L4Fu+hh2Gksz5IczgdHAsy3j66oMt+HhQKIaSrFgRrdPgMCmFyQA)

While trying to use `$Call` and the common "`ExtractReturn`" hack, I noticed Flow was not catching all my type errors. The problem seems to boil down to some strange behavior of `typeof fn`.

All is well:
```js
const A: 'A' = 'A';
const f1 = () => ({a: A});
const f2: () => ({a: 'A'}) = f1;
```

However, when `typeof` is used in another expression's type, the second initializer seems to form a union with the first. Here, `typeof g1` becomes `{a: 'A'} | {a: number}`. Only `$Call` is able to prevent this late-binding and raise the correct type error.
```js
const g1 = () => ({a: A});
const g2: typeof g1 = () => ({a: 42});  // why does this work?
const g3: () => $Call<typeof g1> = () => ({a: 42});  // why does this produce 2 errors?
```

This also produces some confusing error messages which seem to reference later lines of code:
```js
const h1 = () => ({a: A});
const h2: () => ({a: 'A'}) = h1;  // why does an error appear here referencing h3?
const h3: typeof h1 = () => ({a: 42});  // why does this work?
```

The same problem can propagate through object properties, although `$Call` still works starting in v0.68.0:
```js
const o1 = { i: () => ({a: A}) };
const i1: typeof o1.i = () => ({a: 42}); // why does this work?

const o2 = { i: () => ({a: A}) };
const i2: $PropertyType<typeof o2, 'i'> = () => ({a: 42}); // why does this work?

const o3 = { i: () => ({a: A}) };
const i3: () => $Call<typeof o3.i> = () => ({a: 42}); // given the above, why does this fail correctly? (v0.68.0 only)
```

See also: #5056

**Comment by SamChou19815** [comment]
All of them correctly error now
