### ISSUE TITLE
How to use React.Component with no props?

### ISSUE THREAD

**Issue by leonaves** [facebook/flow#6032]
I get the flow error `Cannot use property Component [1] with less than 1 type argument.` when trying to create a React class component. But my component has no props? What am I supposed to do?

**Comment by prewk** [comment]
`class Foo extends React.Component<{}> {}`

**Comment by leonaves** [comment]
That's horrible, why isn't the `Props` type optional?

**Comment by TrySound** [comment]
Because it's explicit. There is nothing horrible in explicitness.

**Comment by leonaves** [comment]
Then why is declaring the state type optional? If the preference is explicitness why not require:

```
class Foo extends React.Component<Props, {}> {}
```

For every component? You can't have it both ways, in real world use, both are optional so both should be able to be omitted or neither should, surely?

**Comment by TrySound** [comment]
It's semantics. Optional thing is the thing which does not exist. Components always have props. They can be empty but they always exists, so you should specify it's type. State may not exist in class component. Its void by default.

**Comment by leonaves** [comment]
Touché
