### ISSUE TITLE
Maybe Functions fail

### ISSUE THREAD

**Issue by eluchsinger** [facebook/flow#6033]
Why can't I use maybe functions?

```jsx
const test? : () => string = () => ("bla");
const test2? : () => string = null;
```

```
    8: const test2? : () => string = null;
                                     ^ Cannot assign `null` to `test2` because null [1] is incompatible with function type [2].
        References:
        8: const test2? : () => string = null;
                                         ^ [1]
        8: const test2? : () => string = null;
                          ^ [2]
```

**Comment by lll000111** [comment]
The syntax you use for `test2` is for function parameters that may be missing. Note that those are two different things, note the TWO "?" characters:

```js
function demo (maybe?: ?string) {....}
```

You can write your 2nd line like this:

```js
const test2 : ?(() => string) = null;
```

Or just be a bit more verbos but gain readability and control (because "?" implies both undefined and null, two values with two entirely different use cases):

```js
const test2 : undefined | () => string = null;
```

Because I don't like the double-meaning of "?" I created aliases like this:

```js
alias Void<T> = undefined | T;
alias Null<T> = null | T;

let test2 : Void<() => string>;  // to be set later
const test2 : Null<() => string> = null;
```

**Comment by eluchsinger** [comment]
So how would you define a type that can be undefined? Can I make a new undefined type like this:
``` javascript 
type Undefined<T> = undefined | T
```
I want to have a React Component take an optional function over its Props. So I have to define a type for the props that allows an optional function. If I don't pass the function over the component's properties, I guess it would be `undefined` or `null`?

**Comment by lll000111** [comment]
@eluchsinger  "undefined" is "void" in Flow, so I already did this in my comment...

**Comment by eluchsinger** [comment]
Well, I think my application shouldn't break if I pass my component an undefined or a null. Semantically, they are different, but in this case they will do the same logically. If a developer passes a null or if he doesn't pass anything at all doesn't matter in this case and is up to him.

Thanks anyways for the clarification.
