### ISSUE TITLE
Can't filter a type out of an array of unions

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#6035]
[try flow](https://flow.org/try/#0MYewdgzgLgBAZiEAuGBBATughgTwDzToCWYA5jAD4xgCuAtgEYCm6AfDALwwDaAugNwAoUJFgMs6TvEQA6OEQA2UFgAowndlBwAHJiDjUYAQg5cA5IRKkzASn5A)

```js
const foo: Array<string | number> = [];
const bar = foo.filter(n => typeof n === 'string');
```

`bar` is still `Array<string | number>`

I also can't annotate `bar` to `Array<string>` without casting it through `any` first

**Comment by TrySound** [comment]
It's known problem. You can find a lot of issues about this.

As a solution you can use reduce of flatMap which can be refined with actual values instead of magical booleans.

**Comment by MarkKahn** [comment]
@TrySound - I don't see how either `reduce` or `flatMap` is a valid replacement.  Can you give an example?

**Comment by TrySound** [comment]
Sorry, "or".

reduce from array prototype

```js
const a = b.reduce((acc, d) => {
  if (typeof d === 'number') {
    acc.push(d);
  }
  return acc;
}, [])
```

or flatMap from any library or handwritten or from the [future](https://github.com/tc39/proposal-flatMap)

```js
const a = flatMap(b, d => typeof d === 'number' ? [d] : []);
```

they are both easy to type.

**Comment by TrySound** [comment]
Performance impact doesn't matter if you don't work with large arrays.

**Comment by MarkKahn** [comment]
> Performance impact with flatMap doesn't matter if you don't work with large arrays.

Like canvas pixel arrays?  :)  I think I'll just cast through any for now, as much as I hate doing that

**Comment by TrySound** [comment]
@MarkKahn Then reduce as more common version of filter will solve your problem. Just don't use `filter` if you need refinement.

**Comment by MarkKahn** [comment]
What's your reasoning for pushing towards something like reduce vs. casting through any?

    const bar: Array<string> = (foo.filter(n => typeof n === 'string'): any);

`.filter` has a clear meaning, reduce is being used way outside of it's normal intention here.

**Comment by MarkKahn** [comment]
Dupe of #1414

**Comment by TrySound** [comment]
`any` is not safe.

**Comment by MarkKahn** [comment]
of course not, one of its purposes is to bypass the typechecker in exactly situations like this where it fails.  Perhaps it's just philosophical, but I'd rather keep the intent of my code correct than jump through weird coding patterns to make flow happy.

Though I see your point, and I'd argue for something like this instead:

```js
const filteredAry = [];
ary.forEach(v => (typeof v === 'string') && filteredAry.push(v));
```
