### ISSUE TITLE
Feature request: Mark typed import as any

### ISSUE THREAD

**Issue by villesau** [facebook/flow#6036]
Currently only way of taking libdefs into use is to do it as a big bang. When taking libdefs into use for widely used library, it might result loads and loads of errors, which is not feasible for one person to fix at once. Potential solution would be to have similar comment to suppress, but with difference that it marks current or next line (where the import is) as any, like the lib wouldn't have types at all. Then all the new code would be type checked and legacy code can be fixed gradually.

**Comment by TrySound** [comment]
There is `[untyped]` section similar to ignore one which treats matched paths as `any`. I use it for this purpose for some time.

**Comment by villesau** [comment]
@TrySound can you elaborate a bit? I'm not sure if that's suitable for my needs. Let's say I want to add libdefs for `reselect` and the library has been used throughout the project. This might cause hundreds of Flow errors which one is not able to fix without help. If i add `reselect` to untyped section, isn't the library then treated as it wouldn't have libdefs at all no matter where it's used? I'd like to mark all the imports of that library as untyped first, but gradually removing the annotation marking the occurrences as any.

**Comment by TrySound** [comment]
Yeah, untyped treats the whole library.
