### ISSUE TITLE
Get by index in array or string should be nullable.

### ISSUE THREAD

**Issue by nkt** [facebook/flow#6037]
Reproduce:
```
const char: string = ''[0];
const number: number = [][0];
```

**Comment by TrySound** [comment]
It's known. Flow do not check lengths of arrays and strings, since having conditions for everything can reduce performance. Also in a lot of times length is not predictable.

**Comment by nkt** [comment]
Maybe you can introduce settings for this behaviour?

**Comment by TrySound** [comment]
Probably lint rule.

**Comment by vkurchatkin** [comment]
Closing, this has been discussed many times over the years.
