### ISSUE TITLE
$Shape type reassign to original type does not yield with error (seems like a bug)

### ISSUE THREAD

**Issue by jony89** [facebook/flow#6038]
Indeed `$Shape` is not documented and considered experimental, yet it seems there is a bug while trying to assign the $Shape type into the original type : 

https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMAaTKAI33IFcBbeiY9AXwG510AYzjkiUMNmLBS2ADb4AJAGUAFtkgAeeHAB8yNDnwByI1D5CRYgGYJ82-RKkzZvIA

**Comment by TrySound** [comment]
Duplicate of https://github.com/facebook/flow/issues/6039

This probably can be closed.
/cc @vkurchatkin

**Comment by jony89** [comment]
sry, by mistake. closing
