### ISSUE TITLE
$Shape type reassign to original type does not yield with error  (seems like a bug)

### ISSUE THREAD

**Issue by jony89** [facebook/flow#6039]
Indeed `$Shape` is not documented and considered experimental, yet it seems there is a bug while trying to assign variable of type $Shape into a variable of the original type : 

https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMAaTKAI33IFcBbeiY9AXwG510AYzjkiUMNmLBS2ADb4AJAGUAFtkgAeeHAB8yNDnwByI1D5CRYgGYJ82-RKkzZvIA

I'd expect that I would not be able to assign `partial` into a variable that is defined with the original type with no optional props. (`foo` in the example)

**Comment by gkz** [comment]
You can use `$Partial` instead https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMAaTKAI33IFcBbeiY9AXwG510AYzjkiUMNmLBS2ADb4AJAAVJ0uQB54cAHzI0OfAHJDUPkJFiAZgnxa9EqTNm8gA
