### ISSUE TITLE
$Keys and type cheking - something wrong here

### ISSUE THREAD

**Issue by ValeryVS** [facebook/flow#6046]
Seems that flow can't handle automatic type checking with these cases:

https://flow.org/try/#0MYewdgzgLgBCBGArGBeGBvAUDGBDAXDAIwA02M8hATGTsIQMxkC+mmUAngA4CmMA0jw6oYAEkEcIAHk68QAMzhIAfAG42oSLADWQiIQkBtALoiA8kh7AoAOl2SAFAkQBKdZnkBXMNYCW4GGAACyttAFlcME9cABsAdRAAJ20IBwA3WM8eQgB+aETfMABzFwMhDHJfRXTMvgAyOpgamKzUFDQAclwOmAAfXpgMlr52zvge-sHats7gDpcXCpwcRJ4oT0SwKeHVGAB6Pe3WiCCQTxiAEwo+WR4FASFyVhW1ja2ujvVWD28-AODQgBBZpZXL5QolMrCLA4KpNIatBpKRCGBE8YyLGHLVbrTZHHi7A74mAnM6Xa4wW73CRPcg4t4wD5fNheHxQfxbAHAbQAIRB2RgeSgBWKpQe0Mq1TRMCR9ggNkKwBaFx4qTRCyW2NeeLRhMO0tJ5yu8Bu3DuihpOGeMHpeKZmG+rL+nJC3IAwvywcKIWKJJq4fyZY1nDYgrgIGYAO5gAAKiRAvESnH5GqxL1xW11+3100N5JNlLN1MeVrp2ve3WZPzZHJgkfjxTdru0npJ3tFUM1tsztT1MB4iXjiRgvggcG0JGJo5gXHj8Fw8Biwnr4CKDswQA

**Comment by apsavin** [comment]
The case with `includes` described in #5012
The case with `obj[value]` is wrong (just try to pass `'__proto__'`);
The case with `obj.hasOwnProperty(value)` looks ok for me, but limited (will not work/should be hard to implement for cases like [this](https://flow.org/try/#0MYewdgzgLgBCBGArAXDA3jAhqgjAGhnlQCYDhUBmAgDwH5cYBfGAXnQCgYtc9PCTeXcjCrtG7dlACeABwCmMANJyprGABJlUiAB5p8kADM4SAHwBuCaEiwA1ioiotAbQC6agPJI5wKADp7bQAKBEQASkt2QwBXMF8AS3AYYAALH1sAWUwwaMwAGwB1EAAnWwgggDd86LlUWmhi+LAAczCnFQ4ueONK6oUAMn6YXrya1hY2AHJMSZgAHzmYKtGFCan4WYWlvvGp4E3F5bG1mEnqSbCwzq4YYrkoaOKwbZXzGAB6d5exiBSQaLyABNCAp9HIjEoVHxxFw7g8nqcZpZxOxQn5qGocJEYnEoIlnql0gBhEY1OoNJqtdqqNB8brDI4DIZolKYCAeADuYAACsUQPJitJSXJLtdYfdHs9GW9Pt8FL9-kCQTAwRCtNC+HDJYjJsiJEA))

I think you can reduce your issue to the case with `obj.hasOwnProperty(value)` anyway.

**Comment by SamChou19815** [comment]
Flow doesn't support these refinements by design
