### ISSUE TITLE
Flow coverage not working on class properties

### ISSUE THREAD

**Issue by jsardev** [facebook/flow#6048]
So I'm working on a React app and I setup flow for the project. I wanted to check what is the coverage for one of my components and there was something weird going on there.

After running `flow coverage MyComponent.js` it showed that the following line were uncovered:

```
class Component {
 anotherMethod() {
   this.method(); // shows as uncovered
 }
  
 method = (): void => { }
}
```

What's interesting, when I switch to something like this:

```
class Component {
 anotherMethod() {
   this.method(); // now shows as covered
 }
  
 // the change was here
 method(): void { }
}
```

The line is covered again. 

What more - in VS Code in the first example the `flow-vscode` plugin show the return type of `this.method()` as `any`. In the second example it shows as expected: `() => void`.

Any ideas? Am I doing something wrong?

**Comment by SamChou19815** [comment]
The issue should be fixed a long time ago
