### ISSUE TITLE
Flow does not understand that String.toUpperCase() returns a capitalized value of input string

### ISSUE THREAD

**Issue by CoryDanielson** [facebook/flow#6050]
When calling `.toUpperCase()` on a string, flow understands only that the return value is a string.  If flow understood that the value is a capitalized version of the input string, it would alleviate a bit of overhead when converting strings into upper-case values and working with enums.

```
type TypeWeekendLower = 'saturday' | 'sunday';
type TypeWeekendUpper = 'SATURDAY' | 'SUNDAY';
const lowerSaturday = 'saturday';

// Flow knows that toUpperCase returns a string, but not that it will be TypeWeekendUpper
// Cannot assign `lowerSaturday.toUpperCase()` to `upperSaturday` because: Either string [1] is incompatible with string literal `SATURDAY` [2]. Or string [1] is incompatible with string literal `SUNDAY` [3]
const upperSaturday: TypeWeekendUpper = lowerSaturday.toUpperCase();

// To work around, you can create an object that maps the values from lower to upper.
const WeekendLowerToUpper = { saturday: 'SATURDAY', sunday: 'SUNDAY' };
const upperSaturday2: TypeWeekendUpper = WeekendLowerToUpper[lowerSaturday];
```

I'm unsure if this is outside of the scope of flow (to assume/evaluate the return value of a native method), but in this case it does seem reliable.

**Comment by CoryDanielson** [comment]
Interestingly, this code seems to work perfectly

```
const weekendLowerUpper: { [dow: TypeWeekendLower]: TypeWeekendUpper } = {
  saturday: 'SATURDAY',
  sunday: 'SUNDAY',
};
type TypeWeekendLower = $Keys<typeof weekendLowerUpper>;
type TypeWeekendUpper = $Values<typeof weekendLowerUpper>;
const lowerSaturday = 'saturday';

// Flow knows that toUpperCase returns a string, but not that it will be TypeWeekendUpper
const upperSaturday: TypeWeekendUpper = lowerSaturday.toUpperCase();

// Flow understands this, creating a mapping for lower-to-upper is slightly inconventient vs calling toUpperCase
const WeekendLowerToUpper = { saturday: 'SATURDAY', sunday: 'SUNDAY' };
const upperSaturday2: TypeWeekendUpper = WeekendLowerToUpper[lowerSaturday];

function doStuff(x: TypeWeekendUpper): TypeWeekendLower {
    return x.toLowerCase();
}
doStuff(lowerSaturday.toUpperCase());
```

Much confuse

**Comment by jedwards1211** [comment]
Flow doesn't have separate internal types for upper and lower case strings, and I honestly don't think that should be its responsibility.
@vkurchatkin I think this can be closed
You can use the shiny new [opaque type aliases](https://flow.org/en/docs/types/opaque-types/) as one way to solve this.
Otherwise, you have to do type casting yourself when what you're trying to model goes beyond what static typing can express.

**Comment by jedwards1211** [comment]
@MarkKahn it supports exact strings, but there's no way of typing `String.toLowerCase` such that Flow knows for an input exact string type it returns the lowercase exact string type.

You could work around this like so:
```js
const methods = {
  LOG: 'LOG',
  INFO: 'INFO',
}
const consoleMethods = {
  LOG: 'log',
  INFO: 'info',
}

type methodNames = $Keys<typeof methods>;
const myMethod: methodNames = 'LOG';

console[consoleMethods[myMethod]]();
```

**Comment by jedwards1211** [comment]
meh, there's nothing else you can do except use lowercase enum constants to begin with.  Using `toLowerCase()` to get a method name comes with its own maintenance risk since no tools can typecheck it correctly.
