### ISSUE TITLE
Type mismatches in inferred React defaultProps do not produce an error

### ISSUE THREAD

**Issue by karoun** [facebook/flow#6051]
@calebmer's [recent blog post](https://medium.com/flow-type/even-better-support-for-react-in-flow-25b0a3485627) about better React support included an example with `defaultProps`. Taking that example and introducing mismatched types should produce an error, but does not.

### [Observed behavior](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwCECAC44AOwCuIAEZYoAGjoBfenVwAbNOgCyTAMIlIUrFPhYAHjAsATdNjwwAdCfARzlgDycI3AB8AkJwqDDIMMC4cPZYBMgy2jD+3HB8gsLCohLkACwATGSqwhrqQA)

```js
import * as React from 'react';

type Props = {
  foo: number, // This is a number
};

class MyComponent extends React.Component<Props> {
  static defaultProps = {
    foo: '42', // This is not a number and should produce an error
  };
}
```
```bash
> flow
No errors!
```

### Expected behavior

```
Cannot extend Component [1] with MyComponent because string [2] is incompatible with number [3] in static property defaultProps.foo.
```

**Comment by lukeapage** [comment]
You have to use the component without a prop, so it uses the default prop to get an error...

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by karoun** [comment]
From a developer perspective, it'd be nice for Flow to show the correct error _without_ having to use the component, just as [it does for state](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwCECAC44AOwCuIAEZYoAGjoBfeoxZsAyjGQw2fQcPnIok2QqXqGuADZp0AWSYBhEpClYp8LAA9DKQATdGw8GAA6D3AIb18AHk4IbmU4PQMsAD4BIThUfRhgXDhgrAJkGXsYZO44YzzhUQlyABYAJjJVYQ0GYQLM+tzhOABIMws2zu64NXUgA).

**Comment by SamChou19815** [comment]
We now require annotation on this, and the issue is likely fixed a long ago
