### ISSUE TITLE
Unable to cast from Array<{specific}> to Array<mixed>

### ISSUE THREAD

**Issue by dmeehan1968** [facebook/flow#6054]
It appears that once Flow has been told of a specific type for an array, it can no longer be converted to a mixed array.  Here I'm using a cast, but it could be passing as argument or other assignment.

([Try](https://flow.org/try/#0MYewdgzgLgBGCuBbARgUwE4EF3oIYE8AuGbPfAHgRQwD4YBeGAbQEYAaGAJg4GYBdANwAoIQAoqaLDgLFSBcogCWAD1QATGgEoBASAD0emADFMASQAyI0aw7cY-WdIpLVG7Tv2GACpgDKvoA))

```js
const numberArray: Array<number> = [1, 2, 3];

(numberArray: Array<mixed>)   // FAIL

([1, 2, 3]: Array<mixed>)           // PASS
```

```text
3: (numberArray: Array<mixed>);	// FAIL
    ^ Cannot cast `numberArray` to array type because number [1] is incompatible with mixed [2] in array element.
References:
1: const numberArray: Array<number> = [1, 2, 3];
                            ^ [1]
3: (numberArray: Array<mixed>);	// FAIL
                       ^ [2]```

**Comment by apsavin** [comment]
Duplicate #6045

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by dmeehan1968** [comment]
Subtle, thank you.
