### ISSUE TITLE
Example from docs for $ObjMap broken

### ISSUE THREAD

**Issue by jwickens** [facebook/flow#6056]
$ObjMap mixes up return values when mapping functions. By "mixes up" i mean that I get errors showing that flow is considering the union of all return types collectively for each function individually.

* [docs im referring to](https://flow.org/en/docs/types/utilities/#toc-objmap)
* [try it in the playground](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSmgUwC4HIDOp4AnAS03VAENRIBXAOwGNNjY7RMBPAB3MwAsKmdhQDW6fFQAGACgCUoALwA+UADVJlOgBNQhLDUJ0JoSetDTS+PZgNtOPWYnvkAogA9MhCkwBK+wwAq3OQKoAA8qkrScooqqvLKasi0jMysuvRhAIIANKAA8gBcoADeANpiHMW4nsR0AOYAusUxiVkAvlGwxfmyxQAk+QBGAFYAshRcYfl57p7emH42gcEqJYiguv5swyPoTAB0lbjSsLIHelo0DOjR3gx5Igkqu-uYBxS4uMT1dNL3eRKoAqzVAsBBMXaskBUIA3Ih2sgGKwamDFKUNpQWs92IQaOgcpihtjYqBsJBYLBsAj4YhpHi-mcPsUhpSMBQ6LJYaBUPkRHSGadzsTQDUSA0uZtefzUP13DwmC5CIRYIQBfQhQcRazYOzOdzUAA5WA8PJDUDEYxiur1FBgOVuBWYJUqtWCpkMbmbb0+qVgY2m0AMAifUB0WBCOrsPjkVU-OoUaBg0ZvIA)

Expected: 

only errors on line 18 and 20 showing usage. This is the case with v56

Actual:

 Using version 68 the following errors are displayed in addition to 18 and 20. 
```
11:   a: () => true,
               ^ Cannot return `true` because string [1] is incompatible with boolean [2].
References:
12:   b: () => 'foo'               ^ [1]
11:   a: () => true,
               ^ [2]
12:   b: () => 'foo'               ^ Cannot return `'foo'` because boolean [1] is incompatible with string [2].
References:
11:   a: () => true,
               ^ [1]
12:   b: () => 'foo'               ^ [2]

```

Impact:

Anyone wanting to map an object type containing functions to a transformed set of functions will be affected. I discovered this while making types to transform from types for our API to backend types for our controllers, which are basically the same as the API types but with additional parameters.

* [example from my use case](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgIJgEZwCuAdgCZhRwBOYA5gKbH1UCWAxmAMrMBu792AA4swAFwCeg+qnoAPQdVFjJ9MAHFGzdtyp82A4WAC8YAN4BqANoBbeqIAWcUgDkAhrYBcYAM6jWxWgBdLwAKQVcqd28vV2JxAEpjAD4wAAUqOGsWb3oAHljxJIBfdEwuTNVCURYYFgllKW8xODFI4m9KKmsxe1VsVIBJChI2arhiMBZiURbvCocp2h7XJWsVtl6mgGs4V1QJKTAAJTtCKmIAFRVcgDEvG5Gx4hSTABIAYVcYGFzcgDUkiEQgA6UERWjRMAFRJGFJ-GFwgA0YBuSX2KhwVFohFs0yuUlu90eLHGLzAHy+P1y2EBIXBXmwCKhcSZ2GRqPRhwAsnZHKR8XkhCwvBomKw2Do9AYWMieQ4nF5fP5aGTXgBRGD0XGiAXU4Sy3lONGc1QXNodajWIUXODvcZ+ODfZjGMC5OV8oWA1xed1OIUI1BgMBhCJRBlYnGMHXXX2kT3Iwg5KheYg4vDMZEzLaMRV+RZMk6iM6XGOGuPCY1lBZNbI9VQHev2FZQnyLTVgWzy8hTFtse0ZJ00TrMnCDHyOQgwbvWQSa7UyeSKBp9YSxu3TAeaqi6oUizTiyX8IUGru55Wqz7fXJm2IWrrW239x1bk98nf6sCxpKVrDVyZNBx6wxBxm1cHxeH4AByJo4B4ZhKTAPsN2fZ1vAnKdJhnOcozEVwtkWSZphaVw2D7EglAQzs+RrCY6iafoBgXBQqCUBscGEdcHUHd9hXUfdtAg-RPRdV4AHk8AAKy5VxBD1GUwBvdpOitYQbU4zdmGNINtLAdBA1ABS1U4C5OGQLBAx03SqzaZSCMA5cmgQXoJkA8QwGIOAlB7WIwDgST6FGMAEGoLYmigKZ6FBYETQU+hfFjABGF06TPfNkjSDIshyXJU2sdMqDRNiLji0RYwAJmS713LTZgmXSTJsjyJVFmNIFXATJNkXCLpvDqzLGuBKg4sdOCQgS+IvApK9FLvFSWDUp9B2RYr4rLBKkniABuMAyjgLYwAAQlQNqOozMBuusXr0vqrLIqGuYYFGyDXEgibyUvH4ZuUh91JQqhlpK8qNu23atiO7SMCwPAqiC5y6zciJVAQSJBCkbsJh8vyJIC1jejc0gWg8pRgqoLYouioqSqFF1TAAHws8xREBstsFCKrmoCPqGuy3L8qSREGaZ1auwAIVCPAUxqqgudu3IOZVVBaZKSGwDkKRRnocg-xmIKQuO0wLKF0qWbZ1KAlO-7ztDS6ZYG+6RvoMb4mRMo7Unch0xbeWAH5fb9-3vcN5nRfFyW8rOxMzu6qJbZyQbhsex3nteoMyjIjDPbA3nmADwOigZDjFq3XUVtET14iAA)

**Comment by jwickens** [comment]
Related: #5584, #5141, #5584

**Comment by jwickens** [comment]
This also affects $ElementType

**Comment by jwickens** [comment]
This also affects $Call

**Comment by bwestergard** [comment]
@jwickens This seems to have been fixed in the most recent release!

**Comment by jwickens** [comment]
@bwestergard its quite a good release! But if you go to the links above you'll still see the mismatched type errors.  Like this one -> [example in playground](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSmgUwC4HIDOp4AnAS03VAENRIBXAOwGNNjY7RMBPAB3MwAsKmdhQDW6fFQAGACgCUoALwA+UADVJlOgBNQhLDUJ0JoSetDTS+PZgNtOPWYnvkAogA9MhCkwBK+wwAq3OQKoAA8qkrScooqqvLKasi0jMysuvRhAIIANKAA8gBcoADeANpiHMW4nsR0AOYAusUxiVkAvlGwxfmyxQAk+QBGAFYAshRcYfl57p7emH42gcEqJYiguv5swyPoTAB0lbjSsLIHelo0DOjR3gx5Igkqu-uYBxS4uMT1dNL3eRKoAqzVAsBBMXaskBUIA3Ih2sgGKwamDFKUNpQWs92IQaOgcpihtjYqBsJBYLBsAj4YhpHi-mcPsUhpSMBQ6LJYaBUPkRHSGadzsTQDUSA0uZtefzUP13DwmC5CIRYIQBfQhQcRazYOzOdzUAA5WA8PJDUDEYxiur1FBgOVuBWYJUqtWCpkMbmbb0+qVgY2m0AMAifUB0WBCOrsPjkVU-OoUaBg0ZvIA)

**Comment by jwickens** [comment]
I also opened a PR to add a test for this: https://github.com/facebook/flow/pull/6059

**Comment by gkz** [comment]
Works now
