### ISSUE TITLE
Getting fulfillment type from Promise?

### ISSUE THREAD

**Issue by bgdavidx** [facebook/flow#6058]
Let's say I have a function like such:

`async function f() { return 1 } // returns Promise<number>`

I can get the type it returns via $Call:

`type ReturnType = $Call<f> // type is Promise<number>`

but how can I get the resolved type of the Promise? In this case it is `number`.

**Comment by manfredxu99** [comment]
+1

**Comment by brad-alexander** [comment]
+1

**Comment by vkurchatkin** [comment]
You can use a helper type like this:

```js
type UnwrapPromise<T> = $Call<<T>(Promise<T>) => T, T>;
```
