### ISSUE TITLE
Error: Cannot import createContext because there is no createContext export in react.

### ISSUE THREAD

**Issue by merisbahti** [facebook/flow#6065]
I've updated to the latest react 16.3.0 and I get this error when trying to use createContext.

I've tried updating all related dependencies but I still get the same error. When I check `/tmp/flow/` I cannot find createContext in the libs. 

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/createStore.js:2:10

Cannot import createContext because there is no createContext export in react.

     1│ /* @flow */
     2│ import { createContext } from 'react'
     3│
     4│ type State = {
     5│   a: number```

**Comment by athomann** [comment]
Looks like its waiting on https://github.com/facebook/flow/pull/5920

**Comment by redbmk** [comment]
@merisbahti Looks like #5920 has landed. I just tried with `v0.73.0` and I'm not getting the error anymore.

**Comment by merisbahti** [comment]
@redbmk you are right, closing this issue now.
