### ISSUE TITLE
Imported-Exported class not recognized as local class

### ISSUE THREAD

**Issue by vramdal** [facebook/flow#6066]
In a simple `create-react-app` project, I have two classes, which lives in separate files:
`ClassA.js`:

```javascript
// @flow

import ClassB from "./ClassB";

export default class ClassA {

    constructor(objB : ClassB) {
    }
}
```

`ClassB.js`:
```javascript
// @flow

import ClassA from "./ClassA";

export default class ClassB {

    func(objB : ClassB) : void {
        let classA = new ClassA(objB); // Flow: Cannot call `ClassA` with `objB` bound to `objB` because `ClassB` [1] is incompatible with `ClassB` [2].
    }

}
```

Why doesn't Flow recognize that the `objB` I'm passing to `ClassA`'s constructor is of the same type as the local class?

flow-osx-v0.69.0

**Comment by thehogfather** [comment]
I can[not] reproduce this. Out of interest what IDE are you using? I get an inline error in vim although  I don't get the error in Atom or when I run the `yarn flow` command from the terminal. Make sure you are running the version of flow bundled with the project.

**Comment by vramdal** [comment]
I was using IntelliJ IDEA Ultimate 2017.1, with the Flow integration. I had it set up to use the globally installed Flow-bin.

After installing Flow in the specific project ({{yarn add flow}}), and reconfiguring IntelliJ to use that installation, the problem goes away. Weird.
