### ISSUE TITLE
Cannot infer generic function as an arrow function 

### ISSUE THREAD

**Issue by yodaiken** [facebook/flow#6067]
Trying to define a generic function as an arrow function seems to not work.

```
/* @flow */
type Fn = <V>(v: V) => V ;

function f<V>(v: V): V {
  return v;
}

// works!
const fn: Fn = f;

// works!
const sFn: Fn = <V>(v: V): V => v;

// should work, works in TypeScript
const otherFn: Fn = v => v;
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBiAdmALxgA8AagHwAUAbgFxhUCUZNrYA3KqlACuRAMboAlnBJRq9ZqzYsqYAN6owYAE650gzSQZ8Avv2DAwCOJoDWAZwCEqEVNvowUIi2Jl3fVGYsrO0dnIlcwW2IvEnJZRiVFblIuQ1NzWwALOEEYABNAmwAaArswcRIAFRxcAGURTXFsdCcXNzh0DNxNKMIYsAZOfp4gA

**Comment by stereobooster** [comment]
Similar issue https://github.com/facebook/flow/issues/5903

**Comment by SamChou19815** [comment]
Flow doesn't infer generic functions by design
