### ISSUE TITLE
$ElementType returns undefined when used in objects

### ISSUE THREAD

**Issue by lewchuk** [facebook/flow#6069]
Bug reproduction:
https://flow.org/try/#0C4TwDgpgBA9gRgKygXigbwFBSgawiALigDsBXAWzggCcAaDAXwG4MMAKNXfKIgVigZF4CAJQt2vIgBIAogBsI5CMWAAVcBAA8w2lADkeEHoB8YjAGMYxAM7ASFImUo0UUXuLZPp8xcrUbtRF0DfBMzDFBIWDBgAEsrAEM5AHlEV0xsQwB+bwUlFXVIQIRgwxN6ZlYOLhAeNwEhGPjiJNTRJihWSxs7YQBJHoTicwghNNROQz4BFjZ+weHR6LjElMQxKAB6TagAERgIa2I9OwB3GGocIA

```
19: (objInstance: optionalObj); // Doesn't work
     ^ Cannot cast `objInstance` to `optionalObj` because number [1] is incompatible with undefined [2] in property `key`.
References:
2:   key: number,
          ^ [1]
13:   key?: $ElementType<obj, 'key'>,
            ^ [2]
```

My use case is that I define an object shape but need a parallel type where all keys are optional (to support partial updates through merge). I want to use $ElementType to reduce duplication of types definitions of the fields but it doesn't work.

**Comment by lewchuk** [comment]
This may actually not be an issue with $ElementType but rather with the comparison between object types: https://flow.org/try/#0C4TwDgpgBA9gRgKygXigbwFBSgawiALigDsBXAWzggCcAaDAXwG4MNRJYxgBLGYgQwA2AeUQp0WXPgD8RMpRr1mrABRopIKEQCsUBkXgIAlEygB6M1ADuMajgDOUfo4gAPSAGNgEACYY1GlpQuvqcPHxCosamFta2Dk4u7hBevv7qoTBcvAIiiCbmljZ2js5Qbp7efgGZ+TGWACIwEPbEAOTAcXaJ5cmpfhgefPadhgCSxCP8xB4QBmKo6niEwXosKuOTwNOzBtkRedGFUE0t7Z3FOFBwpJ0VKVWsQ1uwiBNTMxAATHvhuVHiJb4HRrfybD6zH6vI6xU6tDpdK5le79IA

**Comment by apsavin** [comment]
Not a bug
See #5997 or #6009 for references

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by lewchuk** [comment]
Thanks for the links @apsavin I think I understand that the issue related to pointers of different types pointing to the same real object. I wonder if it would be possible to clarify the error message in these cases to indicate that as the source of the issue. The error message I got was especially confusing because of the direction of the sentence didn't seem to match the situation since `[2]` (as an optional type) is `number` | `undefined` so saying that `number` was not compatible with that didn't make sense.

Something as simple as reversing the order might help:

```
^ Cannot cast `objInstance` to `optionalObj` because undefined [2] is incompatible with number [1] in property `key`.

    References:

    2:   key: number,
              ^ [1]

    6:   key?: number,
               ^ [2]
```

**Comment by lewchuk** [comment]
This seems to be a similar issue as described in https://flow.org/en/docs/lang/depth-subtyping/, perhaps a reference there could also be a reference to that added to the error.
