### ISSUE TITLE
Automatic type detection should use generics when possible

### ISSUE THREAD

**Issue by ghost** [facebook/flow#6072]
```js
const identity = n => n;

identity(1);
identity(true);
```

I believe that `identity` should be automatically typed as `<T>(n: T) => T`, not `(n: (boolean | number)) => (boolean | number)`

**Comment by TrySound** [comment]
@MarkKahn This is expected behaviour. `identity` function is too special case, most of the time union is more correct as inferred type. To solve this you should type it manually.
This probably can be closed.
/cc @vkurchatkin

**Comment by MarkKahn** [comment]
I just reduced my code to an identity function for simplicity. my actual use case was a filter function in a test with a signature something like `<T>(n: Array<T>) => Promise<Array<T>>`, and it threw me for a loop when my 1st test started throwing flow errors after I wrote my 2nd.

I still believe a generic should be used here.

**Comment by TrySound** [comment]
@MarkKahn Implicit generics do not fit well in dynamically typed javascript. You should specify them explicitly with type annotation.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYUWAPACoB8AFFgFxgCCATqwIYCeV1AlEwAKrOAFsCAZwCm5Npx41qYAN6owYVlLwZWJYWMlSAdJolwYANyn0+AblQBfVKlplaAbQCMAXQFh94tKy7NzkWBiiAEZSrNT89q5YHgDkyb5CIoEycqESeKwEWADmcXYubu75GFLp-pmGwfLkkXDmUhxYpbZAA

**Comment by MarkKahn** [comment]
Okay, generics may not be the way to go but the current behavior isn't very helpful.  What about overloading the function signature instead?

    ((n: boolean) => boolean) & ((n: number) => number)

vs:

    (n: (boolean | number)) => (boolean | number)

**Comment by TrySound** [comment]
@MarkKahn What is the problem with solution I posted above you?

**Comment by MarkKahn** [comment]
Nothing, I just believe that the automatic types should work better.

**Comment by TrySound** [comment]
@MarkKahn They work well to fit javascript.

**Comment by MarkKahn** [comment]
I don't understand why you're so resistant towards a suggestion to make something better

**Comment by iclanzan** [comment]
> They work well to fit javascript.

What is this argument rooted in? I agree with @MarkKahn that generic functions such as `identity` should be polymorphic. I can’t think of anything in JS that would make this not fit.

**Comment by sibelius** [comment]
this works

```jsx
const identity = <T>(n: T):T => n;
```

explicit isn't better?

**Comment by MarkKahn** [comment]
@sibelius -- Of course, but my original post was a condensed example of ... something (it was a while ago).  We're still converting some of our codebase to flow so not everything is typed yet.

**Comment by SamChou19815** [comment]
We don't do this by design
