### ISSUE TITLE
babel-polyfill. Required module not found

### ISSUE THREAD

**Issue by rico345100** [facebook/flow#6073]
Using MacOS 10.13.1
Node.js v8.9.0
Flow 0.57.3
Webpack 4.4.1

I need to import babel-polyfill into my project. This is my script:

```javascript
/* @flow */
import 'babel-polyfill';
import './App.jsx';
import style from './style.scss';

...
```

.flowconfig:
```text
[ignore]
.*/node_modules/.*
.*/dist/.*

[include]

[libs]
./src/global.js

[options]
esproposal.decorators=ignore
module.name_mapper='.*\(.scss\)' -> 'CSSModule'
module.system=haste

[lints]
```

.babelrc
```text
{
    "presets": ["env", "react", "flow"],
    "plugins":  [
        "transform-flow-strip-types",
        "transform-class-properties"
    ]
}
```

Everything seems ok, but when running flow, this error showing up:

```bash
Error: src/index.js:2
  2: import 'babel-polyfill';
            ^^^^^^^^^^^^^^^^ babel-polyfill. Required module not found


Found 1 error
```

There is babel-polyfill because when I run the webpack, it bundles well. It seems flow doesn't know it. How do I solve this problem? Thanks!

**Comment by TrySound** [comment]
@rico345100 Just don't ignore node_modules.

This probably can be closed.
/cc @vkurchatkin

**Comment by rico345100** [comment]
@TrySound I just removed ignoring node_modules but still have same error. It worse, it takes too long, almost half minutes.

**Comment by rico345100** [comment]
@TrySound What if this happens because I ignore every node_modules it doesn't make any sense, because in other scripts, I imported other modules in node_modules like React, Redux and others.

**Comment by TrySound** [comment]
@rico345100 They are loaded from `flow-typed` folder and flow itself. Do you have `babel-polyfill` in your `node_modules` folder?

**Comment by rico345100** [comment]
Yes I have. Bundle works fine, only flow gives me this error message.

**Comment by TrySound** [comment]
Can you create reproducing error?

**Comment by TrySound** [comment]
Sorry, repository

**Comment by rico345100** [comment]
It's quite a mess, sorry :(

I tested with my another computer, Windows 10, with flow 0.69.0. It worked, but it takes almost past half seconds.

So I move back to my MacOS and updated to 0.69.0, it works now. It seems it's version specific problem.

But still, it's really really slow in Windows 10, sometimes it takes over minutes. Problem I was faced seems solved, but please makes Flow faster in Windows 10.
