### ISSUE TITLE
The ability to specify generic argument explicitly

### ISSUE THREAD

**Issue by shivawu** [facebook/flow#6074]
I'd like to in some cases, specify the generic type argument at callsite explicitly, as following:

```
class Gen<T> {}

const t = new Gen<string>();
```

Currently flow recognizes this as a syntax error. I know this might be a bad example since you can do
`const t: Gen<string> = new Gen();`, but there are cases, especially when writing higher-order function, this capability is needed

**Comment by noppa** [comment]
It seems this was added in 0.72

From [Changelog](https://github.com/facebook/flow/blob/master/Changelog.md#0720):

> Explicit type arguments in new and call expressions, e.g., f\<T\>(x)

[Example in flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToDiBTAOwB4AVAPlAG9EBIAN3WgFd8AuUUgbkQF9kUsQpgAuoMQF5QhfPDxFiogE4BLQgHNyACgCUPRFpEA6Ri3ahla9XuQhQAUSVLYSgDSgsofAA8ADvhQRfAATA2NTVg5CZgBbACN8JT0gA).

**Comment by shivawu** [comment]
Cheers! I’ll close then
