### ISSUE TITLE
Recursion Limit Exceeded

### ISSUE THREAD

**Issue by jasonLaster** [facebook/flow#6077]
We're seeing this error `Recursion Limit Exceeded` appear when we try to add the flow header to `parser/index.js:50:3` in this [PR](https://github.com/devtools-html/debugger.html/issues/5772)

Interestingly, if we comment out `PausePoint` the same error is shown here: `SymbolDeclarations`.

```
Error  ┈┈┈┈ src/workers/parser/index.js:50:3

*** Recursion limit exceeded ***

     47│   SymbolDeclarations,
     48│   AstLocation,
     49│   AstPosition,
     50│   PausePoint
     51│ } from "./types";
     52│
````

I've tried fixing this on and off for the past week and am not sure how to make progress. Do you have any tips for debugging these cases?

**Comment by jasonLaster** [comment]
So, the bug was fixed by moving `identifiers.concat(members, literals)` to `[].concat(identifiers,members, literals)` Not sure why that made a difference though

**Comment by jsatk** [comment]
Same issue here. So weird.
