### ISSUE TITLE
Failure("internal error: package node_modules/react/package.json not found")

### ISSUE THREAD

**Issue by janmarek** [facebook/flow#608]
Declaration is [libs] is not working when module is present in node_modules.

If the node_modules is ignored by .flowconfig, it shows the error in the title. If the node_modules is not ignored, declaration is not used even though it is more detailed then source code in node_modules.

See example at https://github.com/janmarek/flow-bug for more information.

Is it a bug or am I missing something?

**Comment by AgentME** [comment]
This looks like https://github.com/facebook/flow/issues/447

**Comment by SamChou19815** [comment]
This was probably fixed a while ago.
