### ISSUE TITLE
Exisistential type as method return type inference does not work.

### ISSUE THREAD

**Issue by marcind** [facebook/flow#6080]
Using `*` as the return type of a function, the actual inferred type seems to be the same as `any`: eg. 
```
class Foo {
  getStuff(): * {
    return {
      number: 1234,
    };
  }  

  doStuff() {
    const stuff = this.getStuff();
    stuff.number.toString();
    stuff.DOES_NOT_EXIST.toString(); // <- No error here
  }
}
```

[Playground](https://flow.org/try/#0MYGwhgzhAEBiD29oG8BQ1oHMCmAXAyrgK4BmJAFAJQBc0AVCqgJABOeRLAdoxr9J0QC2AI2wtaARgBMAZgAsAGnS8AvgG5lKjKmUATeIVIVKPXsHicIuaFaPQAvNFwALAJYQAdDgLEyVDXy2ZB4CImIeuAa4LK6cmP7KGEEkHgAiAPIAovgA+gBy6QAqOZkAGgCS+IURUTFx-tAA9I3QADwAtNB5SGIs8CzQzmLYmqgqQA)

I would expect this to behave the same exact way as if no return type was specified.

**Comment by sibelius** [comment]
`*` is causing `empty` inference:

![image](https://user-images.githubusercontent.com/2005841/39126875-ea5437f2-46d9-11e8-8c3f-e286603585ba.png)

this is happening in 0.70 as well

**Comment by SamChou19815** [comment]
Existential type is killed
