### ISSUE TITLE
Supressing "flow coverage" for a given line

### ISSUE THREAD

**Issue by girvo** [facebook/flow#6082]
The specific example is this:
```js
  reducer: (state, action: Actions) => {
    const { counter } = state

    switch (action.type) {
      case 'ADD':
        return update.state({ counter: counter + action.amount })
      case 'SUBTRACT':
        return update.state({ counter: counter - 1 })
      default:
        (action.type: empty); //eslint-disable-line
        return update.nothing()
    }
  },
```

The line `(action.type: empty); //eslint-disable-line` complains that it is uncovered, but it's a useful line to have as it makes the `switch` exhaustive on `action.type`.

For now I'm just ignoring it, but it's a shame as the rest of my code is 100% covered!

**Comment by clintwood** [comment]
Something like this which would exclude any uncovered code on the next line from the coverage score:
`.flowconfig`
```ini
[options]
suppress_coverage_comment= \\(.\\|\n\\)*\\$FlowIgnoreCoverage
```

**Comment by SamChou19815** [comment]
This is not planned since coverage issues are not hard errors.
