### ISSUE TITLE
Unsoundness when annotating an object where keys are a sum type

### ISSUE THREAD

**Issue by frontsideair** [facebook/flow#6087]
[This](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFVALygBEAgsaAD4kBCxyAxrAHYDOKoA1lmobfUzYdYAIwBWALlABvUAG1cAXSnMArgFsRWAE6gAvn2mJQJclIAMAGmOgQ-KQEZre5KLFzuaRUA) typechecks and [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFVALygBEAgsaAD4kBCxyAxrAHYDOKoA1lmobfUzYdYAIwBWfAN6JQJcgC5QABgA0M0CH6KAjGoC+yUWIDa3NAF0gA) does not. Object keys are annotated as a sum type, when unannotated it shows an error correctly but the annotation should not typecheck.

Snippet included for ease:
```
// @flow

type T = "A" | "B"

const key = "B"
const obj: { [T]: number } = { // problematic annotation
  "A": 0,
  // "B": 1,
}

obj[key]
```

**Comment by vkurchatkin** [comment]
Yes, map objects are unsound by design

**Comment by apsavin** [comment]
@vkurchatkin sounds like this sould be fixed though
