### ISSUE TITLE
`mixed` won't unify when in a type parameter position

### ISSUE THREAD

**Issue by zgotsch** [facebook/flow#6088]
E.g. you can't store an `Array<number>` in an `Array<mixed>`.

Try flow: https://flow.org/try/#0C4TwDgpgBA6gTgQzAHgCoD4oF4qoNwBQBAxgPYB2AzsFAgFxTkCuAtgEYRzZQCshZVGmwYsAlgA8IAE24JCJCtSgB3erEQpm7Tphx8FglcPVJkYyVN0q5QA

**Comment by TrySound** [comment]
It's similar to Array and $ReadOnlyArray. You may use covariant generic

https://flow.org/try/#0C4TwDgpgBA6gTgQzAHgNQBUB8UC8V0DcAUEQMYD2AdgM7BQIBcUlArgLYBGEcuUArMQo06HJmwCWADwgATXgmJkqtKAHdGsRCladu2PAKXC1ozUmQTpM-WoVA

**Comment by zgotsch** [comment]
Ah yes you're right. This is not a bug. Thanks for the help!

Now I have to refactor, since we can't have covariant positions in tuples...
