### ISSUE TITLE
Default parameters and spread arguments don't play well together.

### ISSUE THREAD

**Issue by imccoy** [facebook/flow#609]
This is a regression from v0.12 to v0.13.1. The specific thing that's throwing up errors in our code is that setTimeout doesn't typecheck when only passed a function.

Babel is quite happy to work with a function that has a default argument followed by a spread argument:

```
> function a(n = 0, ...args) { return {n, args} }
'use strict'
> a(0)
{ n: 0, args: [] }
> a(0, "f")
{ n: 0, args: [ 'f' ] }
```

But when I feed this file to flow:

```
/* @flow */

function a(a = 0, ...args: Array<any>) {
        return {a: a, args: args}
}

console.log(a());
```

I get

```
/Users/iain/Code/ir/src/varargs.js:7:13,15: function call
Error:
/Users/iain/Code/ir/src/varargs.js:7:13,15: undefined (too few arguments, expected default/rest parameters)
This type is incompatible with
/Users/iain/Code/ir/src/varargs.js:3:34,36: rest array of any
```

And I get the same thing regardless of if I define the first parameter as `a=0`, `a?: any` or `a: ?any`

**Comment by samwgoldman** [comment]
Thanks for this test case! I think I broke this one in #541.

**Comment by mvitousek** [comment]
This behavior no longer repros, closing.
