### ISSUE TITLE
Cannot always call functions with a mixed in their signature

### ISSUE THREAD

**Issue by nvie** [facebook/flow#6093]
Sometimes it's impossible to call a function if it has a `mixed` in its signature if I manually added a type annotation for it.

```javascript
function foo(o: {[string]: mixed}) {
}

type X = {
  a: number,
};

const a1    = {a: 123};
const a2: X = {a: 123};  // The only difference is the explicit type annotation

foo(a1);  // OK
foo(a2);  // Error! (unexpected)
```

Is this considered a bug?

[Try Example](https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUcBciDeBtAZygCcYwBzAXWwFsYAPAUwBMBfASlwChWuuoAngAdGiABqIAvN0SIAhtiKkKAGh4BuPhARF5ARlmzpOBYgDkKOGdabtYXXIBM2CcdMXU19bID0PxAAqABaiCAA2AojMMMDAjMSMkKIwBIhQIYiM9EJhMBAwUGnConJgYHBQcrAIfJZocnrs3oh+iADyANJcdU5Nvv4AosTEcMQEXEA)

**Comment by apsavin** [comment]
See #6088 #6054 #6045 etc

**Comment by nvie** [comment]
I'm still having a hard time understanding why this is only caused when I annotate the `a2` variable's type manually. If I leave the type-annotation away, Flow can apparently infer the type just fine for the same value.

As far as I can tell, the inferred type is the same as my `X` type alias (well, it's the _exact_ version of it, but that does not seem to be a relevant difference here).

Can anyone explain this a bit further?

**Comment by TrySound** [comment]
@nvie `a1` is not restricted to some specific type. `foo` can mutate it and pass string, boolean etc. `a2` is restricted to `number` value, so if `foo will mutate it then value and type may mismatch. If you tell flow that field won't be mutates with covariance or `$ReadOnly<>` utility type both cases work as expected.

**Comment by nvie** [comment]
@TrySound Thanks, that's really helpful 👍

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
