### ISSUE TITLE
Cannot infer a proper type from constant declaration

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#6094]
Sorry for topic name, but it's hard to give a better one :)
The following code declares a hoc, for a react component.
```
import React, { type ComponentType } from 'react';
const withSomeWrapper = <T>(Component: ComponentType<T>): ComponentType<T> =>
  props => (
    <div>
      <Component {...props} />
    </div>
  );
        
const A = withSomeWrapper(({ a }: { a: number}) => null); 
    
<A a={123} />
```
This works as expected. But I would like to write this declaration once, and then just reuse it:
```
import React, { type ComponentType } from 'react';
type HOC = <T>(Component: ComponentType<T>) => ComponentType<T>;
const withSomeWrapper: HOC = Component =>
  props => (
    <div>
      <Component {...props} />
    </div>
  );
    
const A = withSomeWrapper(({ a }: { a: number}) => null); 
    
<A a={123} />
```
For some reason this fails with:
```
6:       <Component {...props} />
          ^ Cannot create `Component` element because props [1] is incompatible with `T` [2].
References:
6:       <Component {...props} />         ^ [1]
[LIB] static/v0.69.0/flowlib/react.js:132:   (props: Props, context: any): React$Node,
                                                     ^ [2]
```
You can [try it](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAwhOBAHZJUwAqRJAvnAGZQVwDkUqG3ANwAoQsTgAJAPKk4AXjgAeegD4AFOUo06ALjIVI2hk2UqAlPJX6ttY8VMi01AM7wA7sBgALAMoUkAOpQKGDEUHrSsgqahraWwnBwYJxgzpZwagmJSgAmwABuKlnZSjHUcTgAdNXJEKmsAPRFJYoNeYVZZiIlwk5UrnAAgvJwHt5+IIHBoUhQamp4KHDMeot6VACuIABGs8wWclabADbHXXDFF4rDKHI4AIwATADMjSpAA).

**Comment by TrySound** [comment]
@vaukalak Tell flow this generic type should be only object, not number or string

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAwhOBAHZJUwAqRJAvnAGZQVwDkUqG3ANwAoQsTgAJAPKk4AXjgAeegC44UgEYArJBgB8ACnKUadNccimGTZXoCU8vWQqXa14rZFpqAZ3gB3YBgACwBlCiQAdSgUMGIoNWlZBQtqN0dhODgwTjAfRzgDTKylABNgADc9YpKlVKtcADpmnIg81gB6atrFDvKq4rsRWuFvKj84AEF5OECQ8JAomLikKAMDPBQ4ZjVNtSoAVxANVeYHOSdDgBsrobga+8VplDkcAEYAJgBmTr0gA

This probably can be closed.
/cc @vkurchatkin

**Comment by vaukalak** [comment]
@TrySound awesome, thanks a lot.
