### ISSUE TITLE
flow-parser: `implements` dropped in `DeclareClass`

### ISSUE THREAD

**Issue by duailibe** [facebook/flow#6096]
Minimal example: [flow playground](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgELIN4F8BQOAmECANnFCiXAM5XICCywAtgA7ERMTi3oY65A)

The `implements` is not included in `DeclareClass` like in `ClassDeclaration`.

It's similar to #5463, it's also an issue for [prettier](https://github.com/prettier/prettier/pull/4244)

**Comment by vjeux** [comment]
cc @mroch
