### ISSUE TITLE
import both name and members from module

### ISSUE THREAD

**Issue by OlavHN** [facebook/flow#610]
Example:

import React, {Component} from 'react';

gives error:

Identifier Component could not resolve name

when using the Component variable.

It seems to be supported in ES6: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

modules are reported as done in #560 .

**Comment by jeffmo** [comment]
Thanks for the report! This will be fixed when https://github.com/facebook/flow/pull/600 lands
(closing in favor of tracking that PR)
