### ISSUE TITLE
Missing React.forwardRef definition

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/flow#6103]
React 16.3 introduced a new [`forwardRef()`](https://reactjs.org/blog/2018/03/29/react-v-16-3.html#forwardref-api) API, for which Flow does not currently have a definition.

**Comment by motiz88** [comment]
I might try to work on this over the weekend.

Looks like for maximum correctness we need a new opaque type `React$RefForwardingComponent<Props>` (name?) and to add it as an option to the unions `React$ComponentType<Props>` and `React$ElementType`. However, and I'm extrapolating from limited experimentation here, it looks like Flow will not typecheck these props (when used in JSX etc) if we don't add special handling for `RefForwardingComponent` (in [`react_kit.ml`](https://github.com/facebook/flow/blob/master/src/typing/react_kit.ml) probably?)

And then there's the option of fudging it and pretending `forwardRef<Props>()` returns `React$ComponentType<Props>`, but that's obviously unsound 🤷‍♂️

**Comment by motiz88** [comment]
OK, having done some digging, I'm going to make a PR with the less-correct solution, typing `forwardRef` as returning `ComponentType<Props>`. I'm basing this on the existing [libdef for `createContext`](https://github.com/facebook/flow/blob/40a72f81e2f29e5a86a62738be036a852931a456/lib/react.js#L208-L213): It models `Provider` and `Consumer` as `ComponentType<Props>` even though internally they're [plain objects distinguished by their `$$typeof` property](https://github.com/facebook/react/blob/c35a1e74835d2b4c07f1e14779a22ae8ca5a0d10/packages/react/src/ReactContext.js#L52-L55), and therefore are neither callable nor are they classes extending `React.Component`.

Ideally we would model these React builtins using a first-class "opaque component" type so we could catch certain errors that the current model will happily allow (_and_ consider to have full type coverage).

**Comment by tiarebalbi** [comment]
Any idea of which release this will be part of? Thanks

**Comment by shahzaibkhalid** [comment]
+1

**Comment by jbrown215** [comment]
@tiarebalbi 0.89

**Comment by jbrown215** [comment]
I will follow up with a blog post on how to use the new AbstractComponent type. It will coincide with the 0.89 release.

**Comment by shahzaibkhalid** [comment]
@jbrown215 Can we get any idea of timelines for release?

**Comment by jbrown215** [comment]
At the latest, December 19th, but hopefully December 12th. Call these dates tentative, since unexpected blockers might pop up.
