### ISSUE TITLE
React.createRef type doesn't match actual API

### ISSUE THREAD

**Issue by billyjanitsch** [facebook/flow#6105]
See https://github.com/facebook/flow/pull/5920#discussion_r178429127 and https://github.com/facebook/flow/pull/5920#issuecomment-379057682.

The typing that was merged uses an old version of the `createRef` API -- different from the one that eventually landed and was released in React 16.3.

`value` needs to be changed to `current`.

**Comment by gaearon** [comment]
A fix is landing.
