### ISSUE TITLE
Missing React.StrictMode introduced in React 16.3

### ISSUE THREAD

**Issue by NoMan2000** [facebook/flow#6107]
Strict mode introduction.

https://reactjs.org/docs/strict-mode.html

Here's the proof.  This could be a React issue or a Flow issue, but since the error is occurring in Flow, I'm opening it here.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqfSrgDsBnYgEYVeGKuWqEACvRxgAvGAAUOGbwCU8gHxLUASAA84mgDoAyoXyjCAWTgATMpt2owYfbzI0MPTS7C7nVwNgDy8fP1d9YCNCMwsrWwdfNSA

**Comment by talkdirty** [comment]
There seems to already be a PR open for this: https://github.com/facebook/flow/pull/6078
