### ISSUE TITLE
array reduce: Flow thinks the accumulator is a constant

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#6109]
Flow 0.69 on Linux and also on Windows (both tested), run from WebStorm through

```
/usr/local/bin/flow server /home/me/Test
Apr  6 11:13:10.545 [info] argv=/usr/local/bin/flow server /home/me/Test
Apr  6 11:13:10.546 [info] Creating a new Flow server
```

I can reproduce the problem with an empty test project with nothing but a single file with the contents below &mdash; but i cannot reproduce it with "Flow Try"?!

I know I can just return the value, but in my code I temporarily inserted a log statement between value calculation and return for debugging so I had an assignment to the accumulator and an extra return statement.

I don't see why the accumulator is assumed to be a constant. I don't understand why

I can reproduce the problem locally in both my Linux and my Windows environment but not in Flow Try.

**Two** examples, for a `string` and for a `number` accumulator:

```js
// @flow
'use strict';

[].reduce((myString: string, item) => {
        myString += '';
        return myString;
    },
    ''
);

[].reduce((myNumber: number, item) => {
        myNumber += 1;
        return myNumber;
    },
    0
);
```

## Errors

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/main.js:5:9

Cannot reassign constant myString [1].

     2│ 'use strict';
     3│
 [1] 4│ [].reduce((myString: string, item) => {
     5│         myString += '';
     6│         return myString;
     7│     },
     8│     ''


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/main.js:12:9

Cannot reassign constant myNumber [1].

      9│ );
     10│
 [1] 11│ [].reduce((myNumber: number, item) => {
     12│         myNumber += 1;
     13│         return myNumber;
     14│     },
     15│     0


Found 2 errors
```

Flow core definitions for `reduce` are at
https://github.com/facebook/flow/blob/master/lib/core.js#L252

**Comment by TrySound** [comment]
Show your flowconfig

**Comment by saadq** [comment]
Do you have this setting on?

https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean

**Comment by lll000111** [comment]
Flowconfig:

```
[include]
./src/

[ignore]

[libs]

[options]
module.ignore_non_literal_requires=true
suppress_comment=\\(.\\|\n\\)*\\$FlowFixMe
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
suppress_comment=\\(.\\|\n\\)*\\$FlowExpectedError
experimental.const_params=true

[lints]
all=error
unclear-type=warn
untyped-import=warn
```
