### ISSUE TITLE
Constructor cannot be called on & Property not found in

### ISSUE THREAD

**Issue by bsr203** [facebook/flow#611]
Hi,

Below code produces following errors. Are they bugs, or not yet supported? The code is working functionally to get a singleton instance.

```
/* @flow weak */

var _ALLOW = false;

class A {
  name: string;

  static instance() {
    _ALLOW = true;
    try {
        global.__CACHE = global.__CACHE || {};
        if (global.__CACHE[this.name] === undefined) {
          global.__CACHE[this.name] = new this();
        }
        return global.__CACHE[this.name];
    } finally {
      _ALLOW = false;
    }
  }
}
```

errors

```
Found 4 errors
~/t/flow ❯❯❯ flow                                                                                            ⏎

/Users/bsr/tmp/flow/test.js:12:28,36: property name
Property not found in
/Users/bsr/tmp/flow/test.js:5:7,7: statics of A

/Users/bsr/tmp/flow/test.js:13:26,34: property name
Property not found in
/Users/bsr/tmp/flow/test.js:5:7,7: statics of A

/Users/bsr/tmp/flow/test.js:13:39,48: constructor call
Constructor cannot be called on
/Users/bsr/tmp/flow/test.js:5:7,7: statics of A

/Users/bsr/tmp/flow/test.js:15:31,39: property name
Property not found in
/Users/bsr/tmp/flow/test.js:5:7,7: statics of A
```

flow --version                                                                                  ⏎
Flow, a static type checker for JavaScript, version 0.13.1

**Comment by samwgoldman** [comment]
What does `this` refer to in a static method call? I think the `name`-related errors are real. If you declare `static name: string`, they go away.

`new this()` is interesting. I believe `this` in a static method should be the constructor function, but we don't understand that in flow. I think that part of this is a bug in flow. @avikchaudhuri, does that seem right?

**Comment by bsr203** [comment]
Hi Sam, thanks for the pointers. I have seen the usage of `this` in JS, and know doesn't allow in other statically typed languages. See a qn in [SO](http://stackoverflow.com/questions/11249037/javascript-this-in-static-methods), though it is poorly worded, some answers suggest it's ok to do so.

**Comment by calebmer** [comment]
Closing because it looks [like this works now](https://flow.org/try/#0G4QwTgBA+gggMnA8gdQgXggMxAGwM4CmA3AFAkDGOIeeEMEA3iRBAHYgC2BAXBHgC5gAlqwDmpZn34h+Q8hBECQrcgQAUASkaSWsBCnQRBAV2I6jYAJ7aWt26JwB7AEa4AdFCgBhGF4ASAKKGDi7unj7+QQA+UYwAvqR2dkKYEGohrjge3r6BANr8ABZCeG7sXAC66GgYxqwAJgSYIgT1WkxJSRlhOZEFxaXlBFUYrAQA7kYDmomdEHHmdmAE-MZgrBDdWeG5Af0lZZzDsyxxWCK4ONYdSXpIqBjY+GZ2C6ckC0A). Let me know if you still have problems 😊
