### ISSUE TITLE
soundness issue with object lookup

### ISSUE THREAD

**Issue by samuela** [facebook/flow#6113]
```js
function getString(key: string): string {
  const stuff = {a: 1, b: null, c: undefined};
  return stuff[key];
}
```
type checks just fine on v0.69.0 and master.

https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZQMpQE4zMgCgGtUBPALkQGcc9kBKSm3fRAbwChFEIEbqoIYMEQBedgENKARgA0iAEaUwIADar5ESuAAmqYHlQ6AvgG4uibOhDYkNIcADaJUgF1zxjkA

**Comment by SamChou19815** [comment]
Erroring since 0.235
