### ISSUE TITLE
Request to add `$Literal<T>` utility type

### ISSUE THREAD

**Issue by LoganBarnett** [facebook/flow#6115]
This came up as part of working Ramda's libdefs for [assoc](http://ramdajs.com/docs/#assoc) in [#2010 in flow-typed](https://github.com/flowtype/flow-typed/issues/2010). A lot of this will be copy-paste from that discussion.

Flow lets us treat a literal value as a type, which has a lot of utility by itself. The only way we can annotate for those types is via the exact type we're looking for. This doesn't lend itself well to any kind of generic application. My hope here is that `$Literal<T>` would allow us to express that some value must be a literal and that `T` could work as a constraint (this is a `string` literal, for example). In the case of Ramda's `assoc` we want to carry the key provided as an argument and use it as an actual key in the intersectioned object we're returning. If we know the key is a literal then we can safely infer the key in the object is also fixed, so we can effectively provide a new object with extra properties.

Aside from generic annotation, it looks like we can already do a fixed version:

``` javascript
// @flow

type Foo = {
  foo: number,
}

const key = 'foo'

const foo: Foo = { [key]: 1 } // works as expected!

const getFooValue = (): string => 'foo'

const key2 = getFooValue()
const foo2: Foo = { [key2]: 2 } // oh noes!

const getFooValueLiteral = () => 'foo'

const key3 = getFooValueLiteral()
const foo3: Foo = { [key3]: 2 } // Works again
```

[try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeiookBAXKAHYCuAtgEZYBOANIgL7IBjWPQDOKUAGssaYqADk1WHMHCxVWngKzSoANpS0AXToBGUP0RDR4gOZYU+WADUAhtEY4SACgCUdMRwAlvQ2xAB88orKlqriBgBMsnYOBK7uWL4x1uqw8XSO2noJxqCJvKAgoLAAFgywWCIAhCrZyY5pHgAygSicbrK+4ZEE0VZqBgDMSfbtbl09fdCZY+KKE-laJDr60hMlZRVgAOqwHBIioC42LsGIQA)

There's some special type information that's in there. In fact, this can be hardcoded as a type:

``` javascript
// @flow

type Foo = {
  foo: number,
}

const getFooValueLiteralExplicit = (): 'foo' => 'foo'

const key = getFooValueLiteralExplicit()
const foo: Foo = { [key]: 2 } // works
```
[try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeiookBAXKAHYCuAtgEZYBOANIgL7IBjWPQDOKUAHMsKfLABqAQ2iMsAGQCWKTkoCiADwzR1AzcVAAKAJR0A5NVg3iAPlB2CNwcLGgA1ljRmUjIEispqmtrQ+obGmlaIQqLi9nSyZqSgANp+aAC6dABMoLygIKDwsBw+IohAA)

But what I would like to see is something that allows me to express something like `$Literal<string>` (constrained so I can limit what it is - or use `*` if I don't care), and pass them around generically. Flow seems to understand a literal differently from other things and gives it special treatment, but short of the actual value being typed, I can't use it generically.

In the case of `assoc`, `$Literal` would be the key and because we've enforced that it will be a literal, we should be able to carry it over as part of the type def for the intersection create with `S & { K: V }`. It knows that `K` is legitimately a type that can be a property, and at some point that exact property can be resolved as part of feeding all of the typed information to `assoc` during our invocation.

I imagine this type could also play well with `$PropertyType` and/or `$ElementType` which requires a fixed literal type.

Having a utility type like this would be great but I don't believe this is blocking anyone currently.

**Comment by jfirebaugh** [comment]
Duplicate of #2242 I believe.

**Comment by LoganBarnett** [comment]
@jfirebaugh indeed it is. Thanks! Closing.
