### ISSUE TITLE
Error reporting for Promise<A> | Promise<B> is misleading

### ISSUE THREAD

**Issue by imccoy** [facebook/flow#612]
When I switched our project to v0.13.1, I started seeing some new errors. It turned out that they did reflect a potential problem with our code, but the error reporting was not very helpful.

With an src/types.js like this:

    /* @flow */

    export type A = { a: number };
    export type B = { b: string };

and this src/error.js:

    /* @flow */

    import {A, B} from './types'

    function promiseA() : Promise<A> {
        return Promise.resolve({ a: 0 });
    }

    function promiseB() : Promise<B> {
        return Promise.resolve({ b: '' });
    }
        
    function getPromise(t) {
        if (t)
                return promiseA();
        else
                return promiseB();
    }

    getPromise().then(function(ab) {
    });

I get these errors:

    /Users/iain/Code/ir/src/types.js:3:17,29: property a
    Property not found in
    /Users/iain/Code/ir/src/types.js:4:17,29: object type

    /Users/iain/Code/ir/src/types.js:4:17,29: property b
    Property not found in
    /Users/iain/Code/ir/src/types.js:3:17,29: object type

The problem is that getPromise() is being inferred as `Promise<A> | Promise<B>`. Flow then tells me that A and B are insufficiently similar for this manoeuvre, but it doesn't tell me _why_ this is being attempted. In my case it was because something returned an A when a B was required, and I was lucky that the distance between error.js and types.js was pretty short.

**Comment by samwgoldman** [comment]
The inferred `Promise<A> | Promise<B>` type is interesting. I can't see any reason why flow should reject such a program, but it would certainly be difficult to use a value of that type (how would you refine it?).

On a whim, I tried annotating your `getPromise` function to return `Promise<A|B>`, which would be a more useful type, and it actually type checked! It's annoying to have to add the annotation, but I wonder if perhaps flow could be very clever and infer the more useful type with the union "pushed into" the promise? cc @bhosmer

**Comment by samwgoldman** [comment]
Actually, in this case even the `A|B` type is terribly useful. If you had a discriminator you could use disjoint union refinement, but without one it's hard to convince flow to refine the union:

```javascript
/* @flow */

type A = { a: number };
type B = { b: string };
type C = A | B;

function refine(c: C): string {
  if (c.a) {
    return c.a; // expected error number ~> string
  } else {
    return c.b; // unexpected error "unknown property b"
  }
}
```

**Comment by imccoy** [comment]
It was quite difficult to get a test case where flow didn't infer Promise<A
| B>, but having seen it happen in the wild I knew it was possible.

I'm pretty ambivalent about flow being able to deal with this case
automatically. I care a lot more about getting an error message that tells
me where to look, at which point it's easy to resolve.

**Comment by samwgoldman** [comment]
In this case, I think the error message is itself erroneous—I don't see why there should be any error at all. I have marked this issue as related to error messages, though. It's something we're working on, but it's a bit tricky to get right, particularly with union types. If you didn't already know this, you can use the `--traces` command line argument to get more information about errors. Far from ideal, but it may help you until while we incrementally improve the error messages.

**Comment by imccoy** [comment]
Ooh, I'll take a look at --trace.

I totally understand it being tricky to get error messages right, and the
hostility of union types in this matter :)

Thanks!

**Comment by samwgoldman** [comment]
Just rechecked this and the repro code from the original issue no longer produces an error. I'm not sure what change specifically caused the change in Flow behavior, but I think this is resolved.
