### ISSUE TITLE
Flow doesn't understand nested objects type as return

### ISSUE THREAD

**Issue by SG5** [facebook/flow#6126]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDOGAhhngCq4EC8YA3qmGAJYB2beATgFwNPMwAbTYBXALYAjbgF0+kuHBh4SbAQF8ANKnXoootgGMMLOGzBRFACgCUfYmUrV+zQ2eKsO3MHXq7m7JxcQgCMAEwAzDI+YADk4RGxANxgwMBscBhgCkoqasxceBiiXOaMgp5B2szqSTp6Bsam5pZwtvak5FT4LmBubB4O5DHlgoHcfH7VYP5EnXgAdOPBCdF0CSlpGVk5yqpgGIoChcWlc451uqhAA

**Comment by SamChou19815** [comment]
This now errors
