### ISSUE TITLE
Flow doesn't recognize properties that are inherited from a different type via the spread operator

### ISSUE THREAD

**Issue by cyorobert** [facebook/flow#6128]
Consider the following example:

https://flow.org/try/#0C4TwDgpgBA8gdtAvFA3gKClARgQwE5QBcUAFHAK4C2WEeAlFIgHxQDOweAlnAOZoC+aNKEhQAknAAWtTsFYAxPAHtK8JKgxQAdDrUAaTQDMlSolArVaBwWkPk4AY2CclcKMAjsSlEABVJ3DxmEtJccooqagzomFA+-oFauHgkAIx0AkA

```js
type One = {
  bar : (number) => string
}

type InheritsFromOne = {
  ...One,
  foo : number,
}

function test(myThing : InheritsFromOne) {
   myThing.bar(1)
}
```

I would expect flow to recognize that myThing.bar(1) has the type signature (number) => string rather than undefined. Is this a bug, or intended behavior?

**Comment by apsavin** [comment]
Not a bug, works as designed.
You [can](https://flow.org/try/#0C4TwDgpgBA8gdtAvFA3gKClARgQwE5QBcUAFHAK4C2WEeAlFIgHxQDOweAlnAOZoC+aNKEhQAknAAWtTsFYAxPAHtK8JKgxQAdDoAkAUQAeOAMbAAPGqYAaTQDMlSolArVatwWjvk4ZzkrgoYAh2EkoQABVJbh5nCWkuOUUVNQZ0TChwqJitXDwSAEY6ASA) use exact type as a workaround.

**Comment by cyorobert** [comment]
@apsavin Thank you for the quick response. Here's a link to the docs if anyone else comes across this https://flow.org/en/docs/types/utilities/#toc-exact.
