### ISSUE TITLE
Can pass Promise in place of map

### ISSUE THREAD

**Issue by bluepnume** [facebook/flow#6130]
```
type MyMap = { [string] : string };
let foo : MyMap = Promise.resolve('hello');
```

This shouldn't type-check, right?

**Comment by idiostruct** [comment]
`MyMap`, loosely equivalent to `{}`, is an _unsealed_ object type matching most JavaScript objects. Properties added will have to adhere to `[string]: string`.

**Comment by bluepnume** [comment]
I guess to refine my question: how do I create a map type that will not allow a Promise object? As in, it will only allow vanilla javascript objects? Otherwise I feel like I lose a lot of type safety here.

**Comment by jcready** [comment]
This is a bug in flow. A Promise instance does not adhere to `{ [string] : string }`.

**Comment by lll000111** [comment]
If you add at least one known property it should work according to my quick and incomplete experiments.

**Comment by jcready** [comment]
CC: @vkurchatkin. Can you add the bug label?

**Comment by SamChou19815** [comment]
Should be fixed a while ago
