### ISSUE TITLE
DOM File definition out of date

### ISSUE THREAD

**Issue by SavePointSam** [facebook/flow#6131]
The File definition includes a deprecated property, [lastModifiedDate](https://github.com/facebook/flow/blob/master/lib/dom.js#L50), and is missing the replacement property, [lastModified](https://developer.mozilla.org/en-US/docs/Web/API/File#Browser_compatibility).

**Comment by WinfredMa** [comment]
Please add "lastModified" property, File object only has the "lastModified" property when upload a file on safari browser. Thanks.
