### ISSUE TITLE
A subtype in a list is not a subtype?

### ISSUE THREAD

**Issue by sharno** [facebook/flow#6136]
According to the Subtypes page in Flow documentation about Subtypes, that works fine:
```js
type A = {+id: number}
type B = {+id: number, +text: string}

const b : B = {id: 1, text: "hello"}
const a : A = b
```

but why when we put the types in a list it loses the property of being a subtype?
```js
type A = {+id: number}[]
type B = {+id: number, +text: string}[]

const b : B = [{id: 1, text: "hello"}]
const a : A = b
```

And is there a cleaner way of solving such an issue if I want to pass `B` as an array to a function that takes `A` as an array without casting to `any` first?

https://flow.org/try/#0C4TwDgpgBAglC8UDeBqAlgEwFxQHYFcBbAIwgCcBfAbQF0AoUSKAIQWXWzyNLIBooUwCAA9gOAM7AyaXAHNq9OgGMA9rklRiUHK0RUkmHAEZ+Q0TgBEACwgAbWyosV6q9cCgBDbbDbE6QA

**Comment by apsavin** [comment]
Like this: https://flow.org/try/#0C4TwDgpgBAglC8UAkAlCBDAJgeQHYBsQYAnY9EAHgG8BqAS0wC4pcBXAWwCMJiBfAPgBQoSFABCCKLQbM2XHgBooNYBAAewZgGdgxOrgDmvANoBdQYIDGAe1w6onKMwmJjVGVACMS1RuYAiAAsIfHxrf15zGztgKHQnWElOQSA

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin

**Comment by sharno** [comment]
Is there an issue tracking the `$ReadOnlyArray` getting documented? As it's not in the documentation yet

**Comment by apsavin** [comment]
https://github.com/facebook/flow/issues/2464
