### ISSUE TITLE
Support strongly typed alias primitives

### ISSUE THREAD

**Issue by andidev** [facebook/flow#6142]
Maybe this is totally out of the scope of Flow and I'm not sure if I'm using the correct terms here but it would be nice to be able to achieve the following.

// @flow
strong type OrderId = string;
strong type OrderItemId = string;

function getOrder(orderId: OrderId)  {
    return {};
}

const orderId = ("123" : OrderId);
getOrder(orderId);  // Should be OK

const orderItemId = ("123" : OrderItemId);
getOrder(orderItemId); // Should show ERROR

**Comment by saadq** [comment]
I think [`opaque types`](https://flow.org/en/docs/types/opaque-types/#toc-opaque-type-alias-type-checking) is what you're looking for. Is that right?

**Comment by andidev** [comment]
@saadq
@vkurchatkin 
If I use opaque type syntax I can't instantiate a MenuId form outside the file where the opaque type alias is defined. Which makes it useless for this use case.
e.g.
*file1.js*
```javascript
// @flow
strong type OrderId = string;
strong type OrderItemId = string;

function getOrder(orderId: OrderId) {
    return {};
}
```

*file2.js*
```javascript
// @flow
import type OrderId './file1';
const orderId = ("123" : OrderId); // Shows ERROR: Flow: Cannot cast `'123'` to `OrderId` because string [1] is incompatible with `OrderId` [2]. 
getOrder(orderId);
```
Opaque seems to be more of a private access modifier (at least for object types).

Maybe that is a bug that I cannot cast a string into an opaque type outside the file where the opaque type is defined?

**Comment by vkurchatkin** [comment]
No, it works as intended. You can't cast a string to `OrderId` exactly because it is opaque. Otherwise, what would be the point of `opaque`?
