### ISSUE TITLE
$Rest does not seem to handle generics properly

### ISSUE THREAD

**Issue by thabemmz** [facebook/flow#6145]
I have a helper function which removes a property from an object. The helper function accepts an `object` and a `key` and it will guarantee to return the object without a key.

## Failing...
The following implementation is erroring:

```
type ObjectWithoutProp<Obj, Key> = $Rest<Obj, {| [Key]: $ElementType<Obj, Key> |}>;

function removePropertyFromObject<O: Object, K: $Keys<O>>(
  obj: O,
  key: K,
): ObjectWithoutProp<O, K> {
  const {
    [key]: _,
    ...otherProps
  } = obj;

  return otherProps;
}

const input = { a: 1, b: 2, c: 3 };
const expected: { a: 1, c: 3 } = removePropertyFromObject(input, 'b');
```
See [on Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFZ4DGGA6gJYYAWcArhgAoBOcOAPCaQBownbgD4wAXjAASAEp4Azhj5khAbwA+YANoicAXQBcMgKIw8AWzwA7DABVceFYOFcc4jQF9RAbnRRmaypaOGswDks4ADc8PTwObAAxLgt+SmVCYzSqIQBpY2lcvCwFPlFRAApUMDA4MiyBarAAa2LjXMaASiyydLpGFnY3PjzxNSaKUKUwcZqa7VasIzAAfUa5sAA6bbhGeL0FJs9JWrI-JoiMZg4w3YZ9twU-T3RJ62naaxxWE7UwAENjABGITEYwAJiEFGMAGYwJ4-G9pngAB74Kh4AAmxj+gLAILA0LAcOOUgiFmisTc8SSKWyGAqn2+GCEAHJiKzOj4gA)

## Succeeding
However, when I explicitly define which properties are to be removed from the input object, Flow succeeds:

```
/* @flow */

type ObjectWithoutProp<Obj> = $Rest<Obj, {| b: $ElementType<Obj, 'b'> |}>;

function removePropertyFromObject<O: Object, K: $Keys<O>>(
  obj: O,
  key: K,
): ObjectWithoutProp<O> {
  const {
    [key]: _,
    ...otherProps
  } = obj;

  return otherProps;
}

const input = { a: 1, b: 2, c: 3 };
const expected: { a: 1, c: 3 } = removePropertyFromObject(input, 'b');
```

It seems to be that `$Rest` cannot handle a dynamic object key properly, as the result of `$Rest<Obj, {| [Key]: $ElementType<Obj, Key> |}>;` seems to return `{||}`.

Anybody got any idea whether this is a bug or I'm misunderstanding `$Rest` / dynamic object keys?

**Comment by SamChou19815** [comment]
This is intended behavior. If you want better control, we recommend mapped type
