### ISSUE TITLE
Setting array type for a variable explicitly does not work the same way as inferred type

### ISSUE THREAD

**Issue by ipotuzhnov** [facebook/flow#6150]
Hi. I was able to track down my issue to this pretty straightforward example.

```js
// @flow

function takesAListOfStringNumberUnion(list: (string | number)[]) {}

const inferred = [123]
takesAListOfStringNumberUnion(inferred)
const explicit: number[] = [123]
takesAListOfStringNumberUnion([...explicit]) // workaround
takesAListOfStringNumberUnion(explicit) // errors
```
~~It looks like a bug in flow, because it works fine when the type is inferred, but not when it's set explicitly.~~

Here is a link to flow try snippet https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqNgIYDWApgM4CCAMrpdgPKQDK2ATrugOYByqALYAjchwCq6fOgAU0BtgBcoGYy69QAH1DohojgEoA2gF0DoAN4BfZJgKNQ3SGI7kAJqAC8oIwEYATADMJogkFDT0jCzs6vx6YpLSMk4u7gaIdugO5AAeAA7ymLhKOvEcpl4+AcGhZFR0CtGc3HEiCVIEMkYAdL25BbhF2GagIKDwsBykxBywGG614Q1RbM28Am0SHbL9hcXmYy6TlIhAA

**Comment by apsavin** [comment]
Not a bug. Here the [fix](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqNgIYDWApgM4CCAMrpdgPKQDK2ATrugOYByqALYAjchwCq6fOgAU0BtgBcoACQAlcsQAmTdNACe1Dh2L6APIy69QAH1DohojgD4AlKADeAX2SYCjUG5IMQ5yLVAAXlAAbQBGACYAZgBdRBIKGnpGFnYrfkcxSWkZIJCw10Q-dADyAA8AB3lMXCV7Ao5o5MiYhJS0sio6BRzObnyRQqkCGWiAOnm6xtxm7GT3EFB4WA5SYg5YDC1+jKHstlHeAQmJKdlFppb1sBDtykQgA).

See https://github.com/facebook/flow/issues/6045 and other issues like this.

**Comment by apsavin** [comment]
Well, the error is the same from my point of view: you can't call a function with some argument of incompatible type. 

I agree, it could be better, of course.

**Comment by ipotuzhnov** [comment]
@apsavin I think you're right, the error message is essentially the same, but could be improved. So shall I open another issue or just update this one? I guess the latter will be confusing.
