### ISSUE TITLE
(v0.70) Missing type annotation when using array methods with exported function

### ISSUE THREAD

**Issue by chrisirhc** [facebook/flow#6151]
On flow v0.70, array methods / generic methods seem to be broken. This only happens when the function is exported, and uses an array method. Marking a return type of `any[]` makes flow pass.

Reproduction [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaGrAKIBOpspAzgBQCUoA3oqKKQKZYqkEDaAugDoAtgEMADjQBGoALwA+UFLoBuRAF9EidgA9xlLKFSZc+QiXKUqARnqgAXKFFoAngKYs2nbnyGQc0FjspNJyispqmtp6Bkbo2HgEABaiVGQU1HbMrCCg6VagsCiGUuxw8KDwOFhJoABEALI4VFQ4aADmoFgu4uxOaERYoqZodZ4cXDygAiISoQpKqhpauvqkhsYJZilpltQATFmeufnUhcVKZQiV1bWNza0dXT19zoPDiWOsEz7TfgFBEIyBYRZZAA):

```js
// @flow
function noErrors() {
  return [].map(b => b);
}

export function noErrors1() : any[] {
  return [].filter(b => b);
}

export function hasErrors() {
  // Errors out below with "Missing type annotation"
  return [].map(b => b);
}

export function hasErrors2() {
  // Errors out below with "Missing type annotation"
  return [].filter(b => b);
}

```

Errors:
```
12:   return [].map(b => b);
             ^ Missing type annotation for `U`.
17:   return [].filter(b => b);
             ^ Missing type annotation for `T`.
```

**Comment by apsavin** [comment]
Why use `any`? You can use something like `Array<string>`.

See the [changelog](https://github.com/facebook/flow/blob/master/Changelog.md):
> New missing annotation errors might be reported.

**Comment by lll000111** [comment]
Not an error.

You export a function &mdash; Flow expects you to document the function's return type. Your function has no return type annotation.

[Fixed.](https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaGrAKIBOpspAzgBQCUoA3oqKKQKZYqkEDaAugDoAtgEMADjQBGoALwA+UFLoBuRAF9EidgA9xlLKFSZc+QiXKUqARnqgAXKFFoAngKYs2nbnyGQc0FjspNJyispqmtp6Bkbo2HgEABaiVGQU1PSOAILkoi4APABUisysIKDpVqCwKIZS7HDwoPA4WEmgAEQAsjhUVDhoAOagWC7i7E5oRFiipmidnhxcPKACIhKhCkqqGlq6+qSGxglmKWmW1ABMWaC5pPnFpZ4VVdQ1dUqNCC1tHT19AbDUbjSbOGZzRKLVjLHxrPwBIIhGTbCJ7IA)

**Comment by lll000111** [comment]
@villesau 

You say:

> The error message doesn't tell anything about missing return type

The error message says

> ^ Missing type annotation for `U`.

!!!

**Comment by villesau** [comment]
@lll000111 It asks you to annotate your `U`, something related to your map or filter, it doesn't say anything return type annotation related. That's the point. Flow rarely requires you to annotate your return type which doesn't make it obvious. When I tried to update to latest Flow, I couldn't even see the benefit of having to explicitly type it: Previously Flow was able to infer the type just fine. At least all the cases I tested. But that's maybe not strictly related to this issue.

**Comment by lll000111** [comment]
@villesau The key is the `return` statement! "Missing annotation" is only applicable to function signatures and variables.

**Comment by vicapow** [comment]
This seems like inconsistent behavior. Either all exports should require explicit annotations or non should as long as the implicit types are valid.

**Comment by kennethtruong** [comment]
I'm pretty sure something seems wrong with exporting anything using an array method. 

Given this example [https://flow.org/try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqTsBbAUwEEAnMgQwE8AuUcq6gHhzIEt0BzAPlAF5QAbQDkACyLQ4IgLoBuZCFABRCrDKgAEkTJFUGHKEoDQAb0Sg8hIgDVK0AK5F6+YoxoA6ApQAOACj8ADwBKAT4Qi1AlSxiYgD1QAFl2TExOLlBsah8iI3R0WGxKbHYMUEh1UAADAFUqj0QAXwVEJQA5WBU1MkwtHT00LFwAIxNzS1dbeycXa3dqJuQiQJ91XEHDFDHIynpKABpI4fphppagA)
```
// @flow

const someArray: Array<string> = ['hello'];

// Error Here
const a = {
  someValue: someArray.map((x) => x)
  //         ^ Missing type annotation for `U`.
};

// No Errors Here
const b = {
  someValue: someArray
}

export const c = {
  a: a,
  b: b
};
```

**Comment by iainbeeston** [comment]
I'm seeing this too. You don't  need to wrap the array in an object, as you can see [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgIYxmOKMAFwAsBTAZ3LHIA9sBbABxirEtLgFcYATWnWZwATsTABtAEwAaMABYAumABG3cQGEwpbJRxhYiEgE9mNciJGjUAYzgA7SuICCYALySAjHNlgAzHLycgCsigB0UACWMMQWABR07gB8YIkApGBS7m4eAAwAlKj0wmJgdo7iAELukr5KRUKi4uVOYFoeEt6ZcgEKIeFRMfGJbinpmdl5hcVNZQ6tACIAXGDOltjGADz23IwqFikdXb69QWChEdGxIgnJqWAZWTlTQA). Happens in 0.7.0, but not 0.6.9. Adding a type annotation before exporting gets rid of the error

**Comment by schumannd** [comment]
So where do 'U', 'T' or 'S' come from? Are they just randomly generated letters? In that case it would be very helpful to replace them with 'exported function return type' or something like that.

**Comment by mrkev** [comment]
@schumannd [this](https://github.com/facebook/flow/blob/master/lib/core.js#L227) for `map`, [this](https://github.com/facebook/flow/blob/master/lib/core.js#L217) for `filter`.

It's _technically_ doing things well: you're returning an Array<U> or an Array<T> and it needs a type annotation for the type parameters of the returned array; the problem is it's a little cryptic since the user didn't directly define `map` or `filter`, so they wouldn't know what U or T are.

**Comment by schumannd** [comment]
Well yes, flow is throwing an error and thus doing things as it should.
If, however, the error message is not understandable, then there is definitely room for improvement. And saying "but it is working as intended" is not helpful.
Also, what are these Letters? Are they the names of the parameters of `map` and `filter`? What about 'S'?

I am strongly in favor of doing something about this. Operations on arrays are among the most common things to appear in any code. These cryptic error messages will cause a lot of new users trouble.

**Comment by jfirebaugh** [comment]
I'm not sure it technically _is_ doing the right thing. Return type annotations are not required on all exported methods -- that's easy to verify. So what's special about methods that use array generics?

**Comment by amypellegrini** [comment]
I don't understand this entirely, but if you do `import * as React from "react";` instead of `import React from "react";` flow doesn't complain anymore.

**Comment by functionalStoic** [comment]
@amypellegrini I ended up finding the same conclusion. I still don't completely understand but here is a screenshot that somewhat confirms it

![components___flow](https://user-images.githubusercontent.com/7215306/42387876-5b4a2958-8109-11e8-8cc8-91944d75a7fa.png)

https://flow.org/en/docs/react/components/

**Comment by peeyush-ad2games** [comment]
We already have `import * as React from 'react'` in our file but it's still giving the error.

**Comment by functionalStoic** [comment]
@peeyush-ad2games What version of flow are you using?

**Comment by peeyush-ad2games** [comment]
@functionalStoic we are using `0.78.0`

**Comment by woniesong92** [comment]
I also ran into the same issue. What's the status of this?

**Comment by innokenty** [comment]
So it's a great discussion, but how do we compile the code like that?

**Comment by amypellegrini** [comment]
@innokenty the usual setting is with Babel and Webpack, shout out if need more details.

**Comment by kevindice** [comment]
I hope this will help someone out: Map is typed as a generic.  You want to provide something in the place of `U` here, as in `someArray.map<U>(someMapperFunction)` where `someMapperFunction` is of type `T => U`.

An example:

```
dictToOptions = (options: {[string]: string}) => {
    const mapper = (key: string): React.Node => (
        <option key={key} value={options[key]}>{options[key]}</option>
    )
    return Object.keys(options).map<React.Node>(mapper)
  }
```

**Comment by luislhl** [comment]
I'm trying to upgrade my version to `0.91.0` and also having problems with `map` functions.

Maps like this are causing me the errors: 

```jsx
  renderDescriptions() {
    return this.props.products.map((item, index) => (
      <ol
        key={`description-${index}`}
      >
        {this.renderDescriptionItem(item.descriptions)}
      </ol>
    ));
  }
```

Changing to this solves the problem:
```jsx
  renderDescriptions() {
    const descriptions: React.Element<'ol'>[] = this.props.products.map((item, index) => (
      <ol
        key={`description-${index}`}
      >
        {this.renderDescriptionItem(item.descriptions)}
      </ol>
    ));

    return descriptions;
  }
```

------------------------------

But i'm still curious about something.

There is a [Medium post by Flow](https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8) about this change, in which they state:

> Note that builtin generic types like Map, Set, and Promise are not affected. Builtin types are merged early in the analysis, so Flow already complains about missing annotations when their instances reach exports.

So why are we getting errors in built-in map functions, like the one above?

My `this.props.products` variable is a built-in Array.

**Comment by kevindice** [comment]
@luislhl In your first example...

Flow knows that `.map()` always returns an array but doesn't know the type of the elements of that array.  It could be anything.  This information needs to either be explicitly provided like this `this.props.products.map<React.Node>( ...` or provided in a way that Flow can infer this information.

In your second code block, you specify the type of `descriptions` as being `Array<React.Element>`, so Flow can infer that `this.props.products.map( ...` will return this type.

**Comment by rastegars** [comment]
With an array of objects, using `.map<ObjectType>`, I got the following error:
```
type ObjectType = {
  id: number,
};
```

> property id is missing in React.Element [1] but exists in ObjectType [2] in the return value.

I fixed this error using: `.map<{}>`

**Comment by goodmind** [comment]
I think if you use $ReadOnlyArray it doesn't require annotation

**Comment by radar** [comment]
I ran into this issue today with the following code:

```
 configuredFlags() {
    return this.props.availableFlags.filter((flag: string) => {
      return this.initialFlagStatus(flag) !== 'default';
    });
  }
```

The solution was to define a return type for the `configuredFlags` function:

```
 configuredFlags(): Array<string> {
    return this.props.availableFlags.filter((flag: string) => {
      return this.initialFlagStatus(flag) !== 'default';
    });
  }
```

**Comment by danielo515** [comment]
Today I ran on this weird error.

I had this:

```flow
type Response = {
  viewer: { paymentRequests: $ReadOnlyArray<PaymentRequest> },
}

export default (companyID: string) => {
  const { data, ...info } = useQuery<Response>(  )
  return {
    ...info,
    data: {
      paymentRequests:  data.viewer.paymentRequests
            .slice()
            .sort(byPayDateDesc)
    },
  }
}
```

And I was getting this error:

`Missing type annotation for `T`. `T` is a type parameter declared in  read-only array type [1] and was implicitly instantiated at  call of method `slice` [2].Flow(InferError)`

Luckly I was able to properly "Cast" by doing this:

```flow
    data: {
      paymentRequests: data
        ? (data.viewer.paymentRequests
            .slice()
            .sort(byPayDateDesc): PaymentRequest[])
        : data,
    },
```

But I don't understand why flow was not capable of inferring what was already declared, slice should not change the data in any way, and it doesn't allow you to provide parameters, so this was kind of a dead end until I came to this funny cast.

**Comment by SamChou19815** [comment]
We now requires annotation on exported stuff unconditionally.
