### ISSUE TITLE
Types defined using spread operator not being checked correctly.

### ISSUE THREAD

**Issue by rasmusprentow** [facebook/flow#6152]
When defining a type using a spread operator it seems to not check types correctly.

Reproducing tryflow:
https://flow.org/try/#0C4TwDgpgBAglC8UDeBDAXFAzsATgSwDsBzAXwChRIoAhBZAIw232PMugGE6kA6PmADRQ+PauTIAzAK4EAxsDwB7AlAkBGABSEwGGAEpk5aXIXLVAJi0EdNA0iMz5SlRIDMVmxzvj1GpABM0AHJ-AH4gkj0AbigAelioAFEcHEUcSUsA4LCI6LiE5NT0tz9AkPDImPioADlFKAgUtNDQsjagA

```
type A = {a: string}
type B = {b: string}
type C = {...A, ...B}

function f1(inp: A) {}
function f2(inp: B) {}
function f3(inp: C) {}

f1({d:'d?'}); // Error
f2({d:'d?'}); // Error
f3({d:'d?'}); // No error??
```

I have not been able to find any documentation for the spread operator. However I would assume that a the call to `f3` in the above would fail as type `C` should consist of everything from `A` and `B`.

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
