### ISSUE TITLE
Using spread operator results in undefined

### ISSUE THREAD

**Issue by rasmusprentow** [facebook/flow#6153]
It seems like unexpected behaviour that the when using the spread operator the resulting type is undefined. 

```
type A = { func: () => void;}
                 ^ [1]
type B = {
 ...A
}

function f1(inp: A) { inp.func(); } // Works!
function f2(inp: B) { inp.func(); } // Error!
                            ^ Cannot call `inp.func` because undefined [1] is not a function.
```

https://flow.org/try/#0C4TwDgpgBAglC8UDeUBmBXAdgYwFxQAoBKBAPigDcB7ASwBMBuAXwCgXRIoAhBZFqAHRCYLViww5gNKpjQBGAjUxh8MEiiVgBE7MQZQmUAPRGoAdSoAnANYBnAITis2KTLQAmRcvxd1UTdrOegbGpgCilpZWjkA

**Comment by apsavin** [comment]
AFAIK works as expected.
You should use [this](https://flow.org/try/#0C4TwDgpgBAglC8UDeUBmBXAdgYwFxQAoBKBAPigDcB7ASwBMBuAXwCgXRIoAhBZFqAHRCAJAFEAHgENswADwxSLViww5gNKpjQBGAjUxh8MEin1gBq7MQZQmUAPT2oAdSoAnANYBnAIQqsMhpaqABMegb4XCZQZhYB1rYOTqJubu5+QA) workaround

**Comment by rasmusprentow** [comment]
What if the input type is an interface? Then the workaround cannot be used. (Arguably this is an different question). I still think the way this work is counter-intuitive and limits the use of the spread operator quite a bit. 

```
interface A { func: () => void;}

type B = {
 ...$Exact<A>
                   ^ Cannot create exact type from `A` [1].
}
```

**Comment by TrySound** [comment]
Interfaces are buggy. There's a lot of opened issues about them. Just don't use them.

**Comment by apsavin** [comment]
See the answer [here](https://github.com/facebook/flow/issues/3534#issuecomment-287580240)

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
