### ISSUE TITLE
Null check before coersion does not work

### ISSUE THREAD

**Issue by eluchsinger** [facebook/flow#6154]
I don't understand why I get a `Cannot coerce parentProject.projectId to string because null or undefined [1] should not be coerced. (References: [1])` error inside the `<Anchor />` tag. I check for null in the beginning of the function. I couldn't reproduce that message on [flow.org](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGAG4CGMArngFxgD85GYgEsAdgHNUAXwDc6KOxEBjDELgiwLABS1WHPJLA8SZcgEo6DMEKibdnajRHsYMc-UaMMAC1JIReJABRYlJiTQAiABU8AXDTWUZJS0sYPAwwDBj0mk1zKgA+Cw8wVPSWQzABYXFqMAADaIEwABIdNk5JOoSwJMZLYjT2YnV3D0yBHjrgHFIAKzxlcmBWu306gBpLTyyAGRYAWwAjABMWAEkRACVB4Z5c6kLaesb0lfa1nsskySA) and if I put *only* the `<Anchor />` tag in the `return`, I don't get the error either. **It happens only inside the map lambda**. What am I missing?

```jsx
type Props = {
   parentProject: Project
};

export default function RoomList({ parentProject }: Props) {
	if(parentProject.projectId == null) {
		throw new Error("The project tried to access had a projectId with null value.");
	}

	const { rooms } = parentProject;
	return (
	   rooms.map(room => (
		<ListItem key={room.name} pad={listItemPadding} justify="between">
			<Anchor path={`/projects/${parentProject.projectId}`}> // JSX Error here!
			   {room.name}
			</Anchor>
		</ListItem>
	   ))}
	);
}
```

```jsx
class Project {
	projectId: ?string;
	name: string;
	rooms: Room[];

	constructor(name: string, rooms: Room[], id: ?string = null) {
		this.projectId = id;
		this.name = name;
		this.rooms = rooms;
	}
}
```

**Comment by eluchsinger** [comment]
I thought of that too today. Is the problem that it isn't const and it's in the lambda?

**Comment by idiostruct** [comment]
My guess: `parentProject.projectId` could change during the iteration; thus, the refinement is invalidated.
