### ISSUE TITLE
Internal error: merge job timed out after 105.16 seconds

### ISSUE THREAD

**Issue by jfirebaugh** [facebook/flow#6155]
Looks similar to #5870 and #5831. I have a small reduced test case. Not linking to flow.org/try/ because it just spins forever.

```js
// @flow

type A = {kind: 'a', e: Type};
type B = {kind: 'b', k: Type, v: Type};
type C = {kind: 'c'};
type Type = A | B | C;

type TypeCases<R> = {|
    a: (A) => R,
    b: (B) => R,
    c: (C) => R
|};

function matcher<R>(cases: TypeCases<R>): (Type) => R {
    return (type) => cases[type.kind](type);
}

const f = matcher({
    a: (a: A) => [...f(a.e)],
    b: (b: B) => [...f(b.k), ...f(b.v)],
    c: () =>  ['']
});
```

With 0.70.0, this hangs in the "merged files" step, then eventually times out:

```
Internal error: merge job timed out after 105.16 seconds
```

**Comment by avikchaudhuri** [comment]
This will be fixed in 0.71.

**Comment by pizza-r0b** [comment]
Getting this error in 0.82.0

**Comment by devstein** [comment]
Getting this error in 0.93.0. Is there any way to find out what is causing it?

**Comment by FezVrasta** [comment]
0.108.0 still has it

**Comment by ahujsak** [comment]
has anyone come up with a solution for this. Just started happening with our project.

**Comment by leoselig** [comment]
@ahujsak Unfortunately not. We ended up increasing the timeout more and more while we migrated our entire huge repo to TypeScript. At the end of the migration, the timeout was set to 1000 seconds to make it pass.
