### ISSUE TITLE
Properly typehint components with JSX dot notation

### ISSUE THREAD

**Issue by svenlombaert** [facebook/flow#6160]
How do I properly typehint a component so I can render both `<Component />` and `<Component.Variant />`

I tried something like this:
```javascript
type Props = {
    x: number
}

declare class _Component {
    static Variant: Variant, 
}

const Component = (props: Props) => {
    return (<span>{x}</span>)
}

Component.Variant = ComponentVariant //imported from another module, a stateless functional component

const ComponentClass = Class<_Component> = (Component: any)

export default ComponentClass;
```

The above doesn't give me any errors in the Component file, which is good. But when I try to render I get stuff like this:

```
_Component [1] is incompatible with React.Component [2]. 
     357│               <Component
     358│                 x={14}
     360│               />

     /private/tmp/flow/flowlib_34952a0/react.js
 [2]  26│ declare class React$Component<Props, State = void> {

     src/components/Component/index.js
 [1] 269│ const ComponentClass = Class<_Component> = (Component: any)
```

```
Cannot create Component.Variant element because prototype [1] is not a React component.

     204│             <Component.Variant
     205│               x={14}
     206|               y={15}
     207│             />

     src/components/Component/index.js
 [1] 248│   static Variant: Variant, 
```

**Comment by apsavin** [comment]
Like [this](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nTjC4ADwBccAHYBXEACMsUOgF8GuCFNTwAwiUhSsU+HwAUYLqkmcI3AJRweAPgFCRlGDKhS4pgDyoYMhSTvwWtqgAdKIqfgD0gcFOdqrqmtpweuCaRjAAashQwMEmvuHckvxwTJLaRVIA5nAqDs6uwh5ePv6JIWGWkUyxCUEhKWp0WQa5kQVFJY6Z+jnGc8XG9HRYopCwcAAmWATIMgA2usuGGwx0flMrMLOF6-BMPABE73BxTkA)?

**Comment by apsavin** [comment]
I don't understand why are you trying to type a function as a class.

**Comment by svenlombaert** [comment]
Wow, must have done something wrong. It works indeed like that. Got the crazy class solution from another github issue. Thanks!
