### ISSUE TITLE
(0.70) Missing type annotation for React.ElementProps

### ISSUE THREAD

**Issue by dfleury** [facebook/flow#6161]
I got an error which gives me no clue about where the real problem is.
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ /private/tmp/flow/flowlib_118c0699/react.js:169:11

Missing type annotation for React.ElementProps.

     166│  */
     167│ declare type React$Element<+ElementType: React$ElementType> = {|
     168│   +type: ElementType,
     169│   +props: React$ElementProps<ElementType>,
     170│   +key: React$Key | null,
     171│   +ref: any,
     172│ |};



Found 1 error
```
It started since 0.70

**Comment by rgbkrk** [comment]
I ended up figuring it out for our code base. Every occurrence of `React$Element<*>` should likely be replaced by `React$Element<any>`. It can't seem to infer the react element type. Not the best, does clear up the error though.

**Comment by dfleury** [comment]
> I ended up figuring it out for our code base. Every occurrence of React$Element<*> should likely be replaced by React$Element<any>. It can't seem to infer the react element type. Not the best, does clear up the error though.

Yeah, it clear up all errors here too. Using the wildcard, the problem persists in the current version (which it 0.74.0 when this posts was written).

**Comment by jbrown215** [comment]
This has also been fixed recently on the flow side: https://github.com/facebook/flow/commit/27a58653684a0e28e0e43ae3cd1fa5e01b798597

Should be out in the next release.
