### ISSUE TITLE
Getting error despite null check in module scoped functions

### ISSUE THREAD

**Issue by htulipe** [facebook/flow#6162]
I could not reproduce this on the live console because document is not accessible there. Here is a sample code anyway. 

```
// @flow

// returned type is HTMLElement | null
const element = document.getElementById('my-element');

function getRect() {
  // Error Cannot call element.getBoundingClientRect because property getBoundingClientRect is missing in null
  return element.getBoundingClientRect();
}

export default function main() {
  if (!element) return; // Checking element is defined
  console.log(getRect()); // calling getRect
}
```

I'm in an ES6 module so `getRect` can not be called from outside and the only code that's calling it is my `main` function which performs a `null` check before. Still, I'm getting a error about `element` being potentially null. Is this normal behavior ?

Using flow 0.70.0

Thanks in advance

**Comment by SamChou19815** [comment]
Refinement doesn't propagate across function calls by design
