### ISSUE TITLE
Exporting methods returning arrays requires return type

### ISSUE THREAD

**Issue by arahansen** [facebook/flow#6165]
Before flow@0.70, the following code does not error. Now, flow requires the exported method to declare a return type (where it was inferred before).

[flow.org/try example](https://flow.org/try/#0FAehAIBcAsEsGdwFMBOKD2LECMkGMBDAV3iSmjKQA8AHTScaAxAO3XBSUiJRagE8aSYNTooGAMyIs8kWOj7oachfABKSACZE8qABQBKcAG9g4Dlx58A2gHIJ6dLYC6AOgC2BGnr0EjAXgA+cD9gAF9gEVp6cCkZFUVleRZ1LR1UADFYKi1DAC5wAEE0An4AHgAqYNNzTm5ecDsHJzdPb18A4NCIyMigA)

Code:

```javascript
// this errors because the export has no return type
export function optionsReducer() {
  return ['foo'].map((a) => a)
}

export function optionsReducerFixed(): Array<*> {
  return ['foo'].map((a) => a)
}
```

**Comment by apsavin** [comment]
Duplicates #6151

**Comment by jamesisaac** [comment]
Closing as duplicate (lots of discussion in other thread)
