### ISSUE TITLE
property `length` is missing in `Boolean`

### ISSUE THREAD

**Issue by CoenWarmer** [facebook/flow#6166]
Hi, I'm new to Flow and am attempting to type what I think is a very simple primitive. However Flow is throwing errors over it.

Consider the following:

```
/* @flow */
type FormValue = string | number | boolean | Array<string | number | boolean>

function foo(formValue: FormValue): string {
  if (!formValue) return ''
  if (formValue.constructor === Array && formValue.length > 0) {
    return String(formValue[0])
  }
  return String(formValue)
}
```

Flow is throwing errors: 

```
Cannot get `formValue.length` because property `length` is missing in `Boolean`
```
and 
```
Cannot get `formValue.length` because property `length` is missing in `Number`
```

This is puzzling, as I think I am typing the value to be either a string, a number, a boolean, or an array with either string, number of boolean values. What am I missing here?

Thanks!

**Comment by apsavin** [comment]
[fix](https://flow.org/try/#0C4TwDgpgBAYg9gJwLYDUCGAbArtAvFAZ2AQEsA7AcygB8oyskAjCBGqRuODCNMtgQQQI0IADxFSlNvSYs2HLjzIA+AFCqAZljIBjYCTh8NnABTHk6bBABcsRKkw4AlLYnkqAb1VQoJDVBMAQnMHKycoBAhgLAQ+AHI4719-E0FhEAA6EgI0kTN7S2coADJiqBDCiAzuSmAACyhlKAAGcK8fH0jo2KgAZWJ3fItHCABtZoBdJySAXySumL5+yQoh0OdVGaA)

**Comment by CoenWarmer** [comment]
Thanks!

**Comment by CoenWarmer** [comment]
Out of curiosity, why doesn’t value.constructor === Array work?

**Comment by apsavin** [comment]
Beause flow is not perfect. What do you do here is type refinement. Flow supports array type refinement via `Array.isArray`. It's enough for most cases.

Also, this is not an array: `{ constructor: Array }` . In your particular example such an object can't be passed to the function, but in general such check is wrong.
