### ISSUE TITLE
Confusing Internal Error and crash when I did something dumb

### ISSUE THREAD

**Issue by lukealbao** [facebook/flow#6167]
Hello! I realize that this is a user error — the snippet below should refine `x`, not its type `foo` — but the failure is a crash with an internal error reported, which is not as helpful as most of the ways Flow tells you that you messed up. I'm wondering why this wouldn't get reported to the user similarly to "referencing a type from a value position".

The original snippet:

```js
type foo = string | number | boolean;

function takeFoo(x: foo) {
  if (typeof foo === 'number') {
    // Internal Error ^^ 
  }
}
```

And the error when running typecheck:

```
Internal error: uncaught exception: Failure("attempt to refine type foo")
Raised at file "map.ml", line 130, characters
10-25
Called from file "hack/utils/collections/myMap.ml", line 15, characters 13-23
```

Thanks for Flow! (I'm happy to help, but I wouldn't even know where to begin. If someone needs help on this from an Ocaml-newbie, I would be glad to have a chance to poke around.)

**Comment by mrkev** [comment]
Thanks for reporting this issue! This is odd, could you confirm you're running the latest version of flow? If not I'd suggest updating and see if the error is still there.

**Comment by lukealbao** [comment]
Sure, I confirmed I'm running v0.70 release, and have the same stack trace. (Did you mean to build v0.71?)

**Comment by mrkev** [comment]
Nah, was just wondering about v0.70, thanks for confirming! 👍

**Comment by SamChou19815** [comment]
This was fixed a long time ago
