### ISSUE TITLE
declarations not working as expected.

### ISSUE THREAD

**Issue by nmn** [facebook/flow#617]
In my code I have this line:

`import {version} from '../package.json`

This is handled by node and browserify by default but not flow.
To work around this problem, I thought declarations would work. This is what the documentation suggests.

So added this declaration to the same file:
```
declare module '../package.json` {
  declare var version: string;
}
```

This declaration is supposed to be valid, and flow and babel don't complain about it, but but error with the import remains unaffected.

**Comment by samwgoldman** [comment]
I can reproduce this when I declare the module in the same file, but flow accepts the program when the module is declared in a `[lib]` .flowconfig directory.

I am perfectly able to declare a var or a function in a source file, though, so it seems like a bug that modules behave differently.

**Comment by AgentME** [comment]
`declare module` is pretty broken. It doesn't work right when used to describe modules that actually exist: https://github.com/facebook/flow/issues/447.

**Comment by nmn** [comment]
It might be something to do with when a declaration is actually run. I'm trying to make the [libs] version work. Will report back with findings.

**Comment by mroch** [comment]
Filed #620 about not understanding .json imports/requires, which I think is a separate but related problem here

**Comment by nmn** [comment]
I'm not sure when, but I stay on the bleeding edge version of flow from github, and this issue is now fixed.
