### ISSUE TITLE
Regression in 0.70.0 with exact objects

### ISSUE THREAD

**Issue by danwang** [facebook/flow#6174]
Hello dear flow maintainers!

I discovered something that seems like a bug; I am able to assign an object with more keys than it should have to an exact type. ([Flow try link](https://flow.org/try/#0C4TwDgpgBAglC8UDeBDAXFAjAXwNwCgBjAewDsBnYKdWBZGzAGigCMMAmPKbgeh6gDqxAE4BrclADuAS2AALKKWJQIw4SOYQAHpELAIAE3xEylVhgAkAUS0o9AHhgA+OkgB0HlFz6CR4qbIKSipqGlAArqTauvoGAPxAA))

```jsx
type A = {a: 1};
const a: A = {a: 1, b: 2};   // Works with no error, expected

const b: $Exact<A> = {...a}; // Works with no error, unexpected?
```

This bug is first present in 0.70.0. I think it may have been introduced in 1916b7d392feb254eb6ecdf392ad9c93651dd070[0]

[0] https://github.com/facebook/flow/commit/1916b7d392feb254eb6ecdf392ad9c93651dd070#diff-3bbc1792ef10ae5965c3bf2776988e14R2284

**Comment by SamChou19815** [comment]
This is fixed a while ago.
