### ISSUE TITLE
Assertions on properties should refine shape types

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#6177]
[Try flow link](https://flow.org/try/#0C4TwDgpgBAsghiARhAysATgSwHYHMoC8UA3nAFxQDOGOuANFIgPwXVZ4C+AUKJFACIQAZjkzAIAGxBp2+IqVY08DRItncuQgK7YAxsEwB7bFAjZKW9KiW4AFEMOGK8JNdkBKCoJHYxk6TYkXFBQmEJQ9o4AdIhQAIRE2FoSEu5QVsCWJg6GwVDAABbohgDuUNgQZQCi6MXotu5cGrzQMJgAHhAAJoQk5FAAth3d3C1QAHKGwG2dPfL9bLQa2noGxlA6Q+2RTrDDXZ4TUzPdQSFhES2G4TlRcIQERADki3hPaRlZUDl5hcVlFWqtUM9UaHCAA)

```js
type MaybeString = {a: string, b?: string}
type DefinitelyString = {a: string, b: string}

function ensureString(foo: MaybeString): DefinitelyString {
  if (foo.b != null) return foo // Flow should now consider foo to be of type {a: string, b: string}
  throw new Error()
}

type Mixed = {a: mixed}
type NotMixed = {a: string}

function unmix(foo: Mixed): NotMixed {
  if (typeof foo.a === 'string') return foo // Flow should now consider foo to be of type {a: string}
  throw new Error()
}
```

### Allowing these refinements would improve code safety
Let's say I work around the above example with a cast to `any`:
```js
function ensureString(foo: MaybeString): DefinitelyString {
  if (foo.b != null) return (foo: any)
  throw new Error()
}
```
**This is a maintenance problem** because imagine if someone changes the `a` type in `DefinitelyString`:
```js
type DefinitelyString = {a: number, b: string}
```
With the cast to `any` in place, Flow will not report any errors on `foo.a`.

But if `foo.b != null` would cause Flow to refine `foo`'s type to `{a: string, b: string}`, then we could return `foo` without a cast, and we would not risk introducing future bugs because of the cast to `any`.

I can also destructure and restructure like this without losing type safety, but it is needlessly wasteful:
```js
function ensureString(foo: MaybeString): DefinitelyString {
  const {b, ...props} = foo
  if (b != null) return {...props, b}
  throw new Error()
}
```

**Comment by SamChou19815** [comment]
We do not support refining one object type to another
