### ISSUE TITLE
Support sourcesmaps as an alternative to .flow files

### ISSUE THREAD

**Issue by ghost** [facebook/flow#6180]
We're already including sourcemaps in all of our transpiled code for debugging purposes, so it's completely redundant to also include `.flow` files that are (also) just 1:1 copies of the original source.

Would it be possible for flow to fall-back to using source from a provided sourcemap if there isn't a `.flow` file or lib def available?

**Comment by TrySound** [comment]
@MarkKahn Use `echo "export * from '../src'" > dist/index.js.flow` and publish sources to avoid duplication.

**Comment by MarkKahn** [comment]
@TrySound - Thanks, but that doesn't actually work for us as we have loads of generated files.  We're generating flow source then echoing that to `.flow` files, and through babel+sourcemaps

**Comment by TrySound** [comment]
That should work if you have only one entry point specified in `main` field of `package.json`.

**Comment by MarkKahn** [comment]
I don't see how with generated files.  Many of our `src/` folders have 1 file to hundreds in `dist/`

**Comment by TrySound** [comment]
There is only one file which has an access to every api. It's entry point specified in `main` field. So when user import from the lib that flow file takes all types from `src/index.js` which is mirrored with `dist/index.js`.

Take a look here. It works perfectly.
https://unpkg.com/react-beautiful-dnd@7.1.0/dist/

**Comment by MarkKahn** [comment]
You're not seeming to understand when I say we have *generated files*, e.g. `src/index.js` is akin to:

```js
const models = glob('../models/*.json');
models.forEach(model => writeFile(`../dist/${model.name}`, genClass(model)));
```

At which point `dist` gets populated with hundreds of files.  `src` often does *not* have flow annotations in it in our codebase.
