### ISSUE TITLE
"an indexer property is missing" for general objects

### ISSUE THREAD

**Issue by Paxa** [facebook/flow#6181]
A simple code like this can't work:
```js
" aaa "[true ? 'trimLeft' : 'trimRight']();

Result:
  " aaa "[true ? 'trimLeft' : 'trimRight']();
          ^ an indexer property is missing in `String` [1].
```
[flow-try example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAiMBDXYMDaALgE4CuApmAPxgDkpAlgLYAyFURdYAXPU8wBKjAOYALLgF0AFAEoA3KiA)

**Comment by kangax** [comment]
Just ran into this with Promise:

```js
const fn = Math.random() ? 'resolve' : 'reject';
Promise[fn]();
```

[try flow](https://flow.org/try/#0MYewdgzgLgBAZmGBeGBZAhlAFgOgE7pgAmIAtgBQCUMA-DAOR4CmEIANgG5P0wBcDzAFZNgUegG4AUAAU8ZAJYQmAbQQBdKuKA)
