### ISSUE TITLE
How to allow custom properties?

### ISSUE THREAD

**Issue by Paxa** [facebook/flow#6183]
In javascript we can add new properties to any object, how to make flow declaration for that?

[flow try example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVA3AhgJzAUxxzjwF4wA7fJAUSJIAoADAFQEsBbfMNgZwC4wAEgDeVJABEsAF3wMAlADppcAMrScbCgHMFAXybyA3OkLEcigMYBXIvgrSAqr0JhyAIgBCcAEbuTqEA)

Example:
```js
var error = new Error(`Time is: ${new Date().toString()}`);
error.currentUser = "Bob";
```

**Comment by saadq** [comment]
Something like:

```ts
class UserError extends Error {
  currentUser: string
}

var error = new UserError(`Time is: ${new Date().toString()}`);
error.currentUser = "Bob";
```

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAVVwFMAnAUTLLjLBIA8AXEgOwBMCqa6BvVMGAwBXamybFyALjC4mZAJasA5qgC+6AG7Y65HmAC8YViSSTK1WgAoABgBUFAWxJgFuGQBJeJpABFsLFYAlAB0THAAyvJKysFqNkEA3Kh6tCEiYqwSpHRGAEQAQnAARnmJQA)

**Comment by mrkev** [comment]
```
  throw {
    ...error,
    query,
    current_user,
  }
```
