### ISSUE TITLE
String interpolation for non-string objects

### ISSUE THREAD

**Issue by Paxa** [facebook/flow#6184]
[Template literals](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals) (back-tick strings) will call `toString()` for every interpolated non-string object, but flow doesn't think so

[flow try example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVADAIgQwC4CmYBAHjgLYAOMBAXGAwCQDeAdgUroQBQCUAvhkwBBAE6icAT2JkqNemBYBtAIwBdQZgDyAIwBWBAMZ4ZFanUXNmOeiv6bUhmDgDOLsMLDMweOAGU8UQBLVgBzPi8wUQI8AFdRVjAAIgA-FOE0pIBuMH5czABhWJdfcjA4fSMTUjN5S3YkYUEgA)

Perfectly working code example:
```js
`Date: ${new Date()}` // => 'Date: Sun Apr 22 2018 ...'
`Array: ${[1]}` // 'Array: 1'
`Object: ${{a: 1}}` // 'Object: [object Object]'

class A { toString() { return "~~A~~"; } }
`Custom object: ${new A}` // 'Custom object: ~~A~~'
```

Is it a bug?

**Comment by vkurchatkin** [comment]
Not a bug, implicit `toString` is not supported

**Comment by Paxa** [comment]
Thanks!

Is there something like a list of javascript features that not supported by flow?

So far I discovered:

* implicit `toString` for template literals
* call methods as properties `"a"['length']`
* adding custom properties to objects
* call `Object.defineProperty` without `value` field

**Comment by vkurchatkin** [comment]
> `"a"['length']`

that's definitely a bug
