### ISSUE TITLE
Proposal: $Diff for unions.

### ISSUE THREAD

**Issue by MrEfrem** [facebook/flow#6185]
Here is example of the problem: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAMozIxsC8cAbzpw4YYmABccAIxwAPnABM8uADsArgBtNdAL51cmtOgCCcLAA8eqgCbpseGADoAwiUiqsqmAB4N2gBoOLh4APkFhOEpbLCgACgBKCJERXAhVVHgBUXE4XTh+GAALYFQnTO4sGjhIkWACODixCDA4AEJefn9NJKEUlMoYdShVRp8AIRyW3gFmsF0AelCE+n79fsHh0e7VvL0GQ2M4SctrO0wqZzdwdK9fPqnJOAASAAVxWOYAFRYsH05KkEyHMyKE9OFsiJIsBVLgCo1cFINCAAEaxJK8cK4ADU2PokWiNliiWSKTSGSyjzy8OKpScc1QuyhGywQxGjVqKR8NmAADdQgJaWUYbgmuIErofAsefzOStIvpdEA

I want the `B` component could takes type of the `prop` from `State` of the component `A` excludes `null` value, because I know what `prop` already hasn't `null`. Of course I can check `prop` is not null in the component `B`, but it's excess step.

My offer that `$Diff` also could to do so:
```
type A = 1 | 2 | null;
type B = $Diff<A, null>;
```
or is necessary to exclude a several values then can use `Array`:
```
type B = $Diff<A, [null, 1]>;
```

**Comment by lydell** [comment]
This sounds like `Exclude<T, U>` in TypeScript: https://www.typescriptlang.org/docs/handbook/advanced-types.html#predefined-conditional-types
