### ISSUE TITLE
Feature request: Warn when $FlowFixMe is unnecessary

### ISSUE THREAD

**Issue by rasmusprentow** [facebook/flow#6187]
It would be nice if it was reported as an error or warning when a `$FlowFixMe` is unnecessary. Since they pollute the code and a lot of the times they get resolved by later versions or libraries that get updated it would be nice if they would easily be identified as unneeded. 

It could give an error along the line of 'Nothing to fix for this $FlowFixMe'

**Comment by oriSomething** [comment]
But it emit warning. What's wrong with that?

**Comment by rasmusprentow** [comment]
You are right, I just had to include warnings. Thanks.
