### ISSUE TITLE
Bug with flow - it stops working after file is saved

### ISSUE THREAD

**Issue by budarin** [facebook/flow#6188]
Suddenly (maybe after upgrade) flow has stopped working on my project properly

My config:
```js
[ignore]
<PROJECT_ROOT>/dist/.*
<PROJECT_ROOT>/.idea/.*
<PROJECT_ROOT>/.git/.*
<PROJECT_ROOT>/.tmp/.*

[include]

[libs]

[options]
include_warnings=true
suppress_comment= \\(.\\|\n\\)*\\$FlowIgnore

; Extensions
module.file_ext=.css

# module.name_mapper='.*\.\(svg\|png\|jpg\|gif\)$' -> '<PROJECT_ROOT>/flow/src/stub/url-loader.js'

[lints]
all=warn
untyped-type-import=error
sketchy-null=off
```
I use Webstorm:
```
WebStorm 2018.1
Build #WS-181.4203.535, built on March 22, 2018
JRE: 1.8.0_152-release-1136-b20 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows Server 2008 R2 6.1
```
when I edit my code - I see flow errors

![1](https://user-images.githubusercontent.com/8055157/39132476-9c412f98-471a-11e8-857d-50d953f90973.png)

but when I save the module - flow becomes blind

![2](https://user-images.githubusercontent.com/8055157/39132522-b75d7ea8-471a-11e8-95bc-d606762d90a4.png)

**Comment by budarin** [comment]
and there is an old problem:
although it is explicitly stated in the configuration not to monitor folders .tmp & dist - flow regularly crashes with an error when changes are made to these folders.

**Comment by chrisvasz** [comment]
I notice this also from VS Code on Windows on Flow 0.70.0. I'll try to narrow down a specific case, but it's not easy. For what it's worth, when I notice the problem, there are a lot (10+) of Flow processes in Task Manager. Under normal conditions, the number of processes is rarely above 3. When I save a file, the process count jumps to 4-5 temporarily, but settles back down to 3 shortly.

Whenever the problem happens, I just kill the flow process with the most memory, which takes the rest of them down with it.

**Comment by budarin** [comment]
There are some errors in console:
```
D:\Projects\kometa\node_modules\flow-bin\flow-win64-v0.73.0\flow.exe server D:/Projects/kometa
May 27 16:52:04.539 [info] argv=D:\Projects\kometa\node_modules\flow-bin\flow-win64-v0.73.0\flow.exe server D:/Projects/kometa
May 27 16:52:04.540 [info] Creating a new Flow server
May 27 16:52:34.714 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: Unix.Unix_error(Unix.ECONNRESET, "write", "")
May 27 16:52:34.714 [error] backtrace:
May 27 16:52:34.714 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
May 27 16:52:34.714 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
May 27 16:52:34.714 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
May 27 16:52:34.714 [error] 
```

**Comment by mroch** [comment]
we've fixed a lot of Windows issues this year. I'm going to close this, please file new issues for anything that still crops up on recent versions (e.g. v0.185+). thanks!
