### ISSUE TITLE
"unexpected typeapp: EmptyT" error after upgrading to flow 0.70.0

### ISSUE THREAD

**Issue by EvHaus** [facebook/flow#6189]
After upgrading from flow 0.69.0 to 0.70.0 I am now seeing the following flow errors:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/ux/src/FileUpload/FileUpload.js.flow:67:17

Internal error: unexpected typeapp: EmptyT

     64│ 	static defaultProps = {
     65│ 		defaultText: 'Click here or drag and drop a file to begin upload',
     66│ 		isOver: false,
     67│ 		onUpload: (): Promise<any> => Promise.resolve(),
     68│ 		releaseText: 'Release to begin upload...',
     69│ 		uploadingText: 'Uploading...',
     70│ 	};


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/ux/src/FileUpload/FileUpload.js.flow:213:49

Internal error: unexpected typeapp: EmptyT

     210│ 	 * Handler for the file drop event on the file uploader
     211│ 	 */
     212│ 	// eslint-disable-next-line react/no-unused-prop-types
     213│ 	_handleDrop = ({files}: {files: Array<File>}): Promise<any> => {
     214│ 		// Validate files
     215│ 		const validationError = this._validate(files);
     216│ 		if (validationError) {


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/ux/src/FileUpload/FileUpload.js.flow:240:55

Internal error: unexpected typeapp: EmptyT

     237│ 	/*
     238│ 	 * Handle for the file upload select event
     239│ 	 */
     240│ 	_handleInputSelect = (event: SyntheticInputEvent<>): Promise<any> => {
     241│ 		event.preventDefault();
     242│
     243│ 		// Find file objects
```

The errors all seem to be pointing at the `Promise<*>` definitions inside a third-party node_module library I'm using.

I've tried modifying the Promise type definitions to be more specific but that doesn't seem to make any difference. Changing the Promise type definitions to `any` in the third-party library code makes the issues go away. So it seems to be something to do with the default `Promise` type definition inside Flow itself.

Rolling back to flow 0.69.0 makes the issues go away.

Could anyone suggest any ideas about what `unexpected typeapp: EmptyT` might be referring to and what it may have to do with the Promise type definitions?

**Comment by EvHaus** [comment]
This is still an issue with `flow@0.71.0`

**Comment by StreetStrider** [comment]
Seemes on `0.72` this mutated into `Internal error: unexpected typeapp: MergedT`.

**Comment by mrkev** [comment]
Feel free to open another issue with repro information

**Comment by EvHaus** [comment]
@StreetStrider @mrkev  I've logged https://github.com/facebook/flow/issues/6284 for that.
