### ISSUE TITLE
Fails to infer exhaustiveness for union type

### ISSUE THREAD

**Issue by zen0wu** [facebook/flow#6190]
```
function test(a: 'a' | 'b'): number | string {
  if (a === 'a') {
    return 1;
  } else if (a === 'b') {
    return 'b';
  } /* else {} */
}
```

For such a function, flow should be able to know there's no `else` branch at the bottom and rule out the undefined case. 

The usefulness involves when I have a union type of several cases, I would like to enumerate through them explicitly, so that when I added another case in the future, flow would notice there's a missing case. I could fix this by removing `if (a === 'b')` condition, but that loses the exhaustiveness check.

If this is a bug, please try reproducing using https://flow.org/try/.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sx8BTAZ3wAoBDALjAHI7mwAfFgI2YEom2TAFtu5AE6cw1cYWwBzMAG9UYMIShh6YALx6WbPstVqw48vkzjSARgDcJgL5hyMSuXWbtenT37HTMwsrUmZeBzVHVCigA

**Comment by SamChou19815** [comment]
You can use switch instead: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyGUTkhyWIyaEHjp85cMn8CIljRCVZ2QF91CBFqAHoAKgACAAEYGggAd0jw0IAdKHSYEjw4aEjcDHpcAAosZEiAciwKyIAfSt4KgEpyxXJeDDQ6yKK0OCgESOB0yJ6E7TAAC0jSpqGR0ciwBgxK6vLMXCI0KEiARgBuBdHl+lWKxo2MLZ2GiqPdyP9056g2EAA3TqZoag+ABgAdAAmPbAwH-ED+IA
