### ISSUE TITLE
Worker (dedicated web worker) interface does not have onmessageerror

### ISSUE THREAD

**Issue by tiffon** [facebook/flow#6191]
MDN docs: https://developer.mozilla.org/en-US/docs/Web/API/Worker/onmessageerror

WhatWG: https://html.spec.whatwg.org/multipage/workers.html#handler-worker-onmessageerror

[Current interface](https://github.com/facebook/flow/blob/v0.70.0/lib/bom.js#L473):

```
declare class Worker extends EventTarget {
    constructor(stringUrl: string): void;
    onerror: (ev: Event) => any;
    onmessage: (ev: MessageEvent) => any;
    postMessage(message: any, ports?: any): void;
    terminate(): void;
}
```

**Comment by mrkev** [comment]
Library definitions live under /lib, feel free to send a PR if you’ve got a spare minute
