### ISSUE TITLE
spread of class type doesn't work like normal type

### ISSUE THREAD

**Issue by bmsuseluda** [facebook/flow#6195]
Im trying to work with the File class and stumbled upon this issue.
Flow doesn't understand spreading of a class type.
```javascript
class TestAsClass {
  name: string;
  value: string;
}

const convertWithClassFails = (test: TestAsClass): TestAsClass => ({ ...test });
```

Spreading works when im using a normal type instead of a class type:

```javascript
type TestAsType = {
  name: string,
  value: string,
};

const convertWithTypeWorks = (test: TestAsType): TestAsType => ({ ...test });
```

You can try it on [try flow](https://flow.org/try/#0C4TwDgpgBAKhDOwCC8bmgXigbwFBSgDsBDAWwgC4pEAnAS0IHMAafKAN2IBsBXS64PSasAvgG5cuAMYB7QoiizC7CDWAB1OsAAWaSOpk0A1vChYAFMATAqcRCj0QAlLesP0ZgHxRz2KADpAqwURJwlpLmJ4UztkeABhSOicNhJyKloGRgkCTl5+TKYJEUklBSUVNU0dRKj4ADFiOi5TC2CbWDcEpPgXTvtuuq8fP0D-dqhQsSA).

**Comment by idiostruct** [comment]
Classes are nominally typed, and object literals are structurally typed<sup>1</sup>. Therefore, `{ ...test }` is incompatible with `TestAsClass`. Is the objective to return a new instance?

1. [Nominal & Structural Typing](https://flow.org/en/docs/lang/nominal-structural)

**Comment by bmsuseluda** [comment]
Good point, thank you for the explanation.
