### ISSUE TITLE
Flow claims shorthand method definitions are not writable

### ISSUE THREAD

**Issue by theneva** [facebook/flow#6196]
Flow says that I can't bind a method in a class to `this` in the class constructor because [shorthand method definitions](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Method_definitions) are not writable. 

Tiny reproduction (also showing that functions as class properties work as expected): https://flow.org/try/#0MYGwhgzhAEASCmIQHtoG8BQ1vWMgdhAC4BOArsEciQBQCU6WOzRAFgJYQB0Er1bYfABMAsvDbIh0ALzQ2nHnxIDhYiUK4AjdsJryIdANxNm2fVuRlhAQRIlkAdxlyO3TZZt3HWnUL2ujE1NzADMrSnYCAAV7AAd4ZQBPZ1Dwokj8GOR4pJ9dfUDmAF8MIN5+VkFRcT4-BkxTHAB6JugQsHYQCCCS7CD3KyFbeydZehkAPkZG7BboB2oAa27ikyCw-AjouISiZNkNrfxxhpm5hZJlnowSoA

I need to bind the function to `this` (and can't just use a bound function like `myFunction = () => { … }`) because I'm passing the function as a callback to another class (from a third party library) that [will call it bound to its own `this`](https://github.com/react-dropzone/react-dropzone/blob/72abe1d900fecd7784e08010e2f60bcb790c956a/src/index.js#L191).

My code (transpiled with `babel-plugin-transform-class-properties`) works despite Flow's warning, so I believe this is a bug in Flow.

**Comment by idiostruct** [comment]
Methods on classes (and interfaces) are considered to be read only by Flow. One workaround is to do something like this in the constructor:

```typescript
(this:any).shorthandMethod = this.shorthandMethod.bind(this);
```

https://github.com/facebook/flow/issues/1517#issuecomment-194538151

**Comment by theneva** [comment]
Okay, thanks for the clarification!
