### ISSUE TITLE
Support for ES6 features

### ISSUE THREAD

**Issue by jlongster** [facebook/flow#62]
I didn't see an existing issue for this, nor do I see anything on the website about it, but I'm sure you all have plans for this. Looks like there are several ES6 features this doesn't support yet, particularly `let`:

```js
let x = 5;
```

```                                                                                  
/Users/james/projects/mozilla/gecko-dev/toolkit/devtools/server/actors/foo.js:3:1,10: 
Unsupported variable declaration: let

/Users/james/projects/mozilla/gecko-dev/toolkit/devtools/server/actors/foo.js:3:5,5: var x
Unknown global name
```

I'm interested in using this as a "light" type checker in Firefox. I don't know if we'll ever start adding a lot of type declarations, but this looks like it could be a nice "linter" using the weak mode. (still not sure how far that goes yet, but if it can even catch a few things that would be cool).

Since we can code against SpiderMonkey, we use ES6 a lot, like:

* `let`/`const`
* for-of
* short-hand object syntax (`{ foo }` turns into `{ foo: foo }`)
* generators

That's just off the top of my head. On the file I tried, the main things I hit were let/const and for-of.

**Comment by peterwmwong** [comment]
+1 for modules

**Comment by tenorok** [comment]
+1 for `let` and `const`

**Comment by thetalecrafter** [comment]
+1 for async/await. Would love to use flow with 6to5.

**Comment by jden** [comment]
+1 for only supporting things that are directly relevant to type checking. Many of the new ES6 keywords have no effect on checking / inference.

**Comment by iammerrick** [comment]
Modules please... :-)

**Comment by nemoo** [comment]
+1 for arrow functions

**Comment by murphyrandle** [comment]
Are +1's helpful? The things that I'm really hoping for are import/export, const/let, and generators.

**Comment by ivanoats** [comment]
Something that would be helpful here would be a checklist like in https://github.com/eslint/espree/issues/10 so that we can see how close we are.

**Comment by murphyrandle** [comment]
Also, :sadtrombone:, I had just tested:

```
var foo = function *() {
  foooooooo()
}
```

And I didn't get any errors. I hand't tried actually putting in a yield statement yet. Sorry. Generators are still unsupported.

**Comment by johanneslumpe** [comment]
Is there any update on this? The support for es6 modules would be really something to look forward to. Currently a show stopper for me as the whole project here is purely written in es6 using babel

**Comment by zerkalica** [comment]
+1 Yes, let, const and modules. Babel+flow is a real alternative of typescript.

**Comment by Aetet** [comment]
+1 for using es6 with flow.

**Comment by impinball** [comment]
Modules would be very nice. +1

**Comment by gavriguy** [comment]
+1 modules

**Comment by evansimmons-ck** [comment]
+1 modules

**Comment by danvk** [comment]
Could we add [getter/setter methods][1] to the list?

```javascript
class MyList<T> {
  list: T[];
  constructor(list: T[]) { this.list = list; }
  get length() { return this.list.length; }
}
new MyList([1,2,3]).length
```

[1]: https://github.com/esnext/es6-class/blob/master/test/examples/getter-setter.js

**Comment by ccapndave** [comment]
+1 modules!

**Comment by dialelo** [comment]
:+1: for the modules, is it in the roadmap for the near future?

**Comment by impinball** [comment]
@dialelo [As far as I can tell, yes.](http://flowtype.org/docs/coming-soon.html#_)

**Comment by callumlocke** [comment]
What @ivanoats said. Can a collaborator please edit the issue description at the top to add a GFM checklist like [this](https://github.com/eslint/espree/issues/10), and check things off as they are done?

I keep coming back to this thread to find out if Flow is compatible with my project yet, and a checklist would really help me out!

**Comment by callumlocke** [comment]
What @ivanoats said. Can a collaborator please edit the issue description at the top to add a GFM checklist like [this](https://github.com/eslint/espree/issues/10), and check things off as they are done?

I keep coming back to this thread to find out if Flow is compatible with my project yet, and a checklist would really help me out!

**Comment by callumlocke** [comment]
What @ivanoats said. Can a collaborator please edit the issue description at the top to add a GFM checklist like [this](https://github.com/eslint/espree/issues/10), and check things off as they are done?

I keep coming back to this thread to find out if Flow is compatible with my project yet, and a checklist would really help me out!

**Comment by OliverJAsh** [comment]
+1 for a checklist

**Comment by impinball** [comment]
Checklist would be awesome. +1

**Comment by milesj** [comment]
Is there a status page on what ES6 features are currently supported? Would be nice to have a quick overview. I keep running into blockers when implementing flow in my ES6 projects.

**Comment by seanhess** [comment]
+1 for generators. Thank you so much for implementing modules!

**Comment by friday** [comment]
+1 for stop using this issue thread as a poll of specific unimplemented es6-features.

**Comment by jgod** [comment]
+1. looking forward to let/const support

**Comment by ccapndave** [comment]
Note that you can get most ES6 feature in Flow right now by running your code through Babel with the flow blacklist. http://www.keendevelopment.ch/flow-babel-gulp-es6/ has a recipe for doing this.

**Comment by leeola** [comment]
@ccapndave The problem with that, at least in my case, is that Flow can have problems with the generated code from Babel. Eg, for me even using `class` with a method, eg:

```
class MyClass {
  func() {}
}
```

will cause babel to generate code that Flow believes is incorrect. Specifically the `_createClass` generated line. Have you found a workaround for that? _(and possible other generated code issues)_

**Comment by frankychung** [comment]
@leeola in that case blacklisting `es6.classes` will solve that issue since Flow understands ES6 classes.

**Comment by seanhess** [comment]
@ccapndave wouldn't that make all your flow errors report incorrect line numbers?

**Comment by ccapndave** [comment]
I don't use classes in ES6 so I couldn't say for sure, but I __think__ the sourcemaps will figure it all out.  Have a go and let us know!

**Comment by jgod** [comment]
@ccapndave Thanks for the tip, I got it working! I'm using the comment-style notation (great feature) so I don't have to do any stripping.

 I noticed that with the es6 class functions, like @leeola shows, I have to use the notation

```
/* (myVar: number, myVar2: string) */
func(myVar, myVar2) {
  return false;
}
```

instead of 

```
func(myVar /* : number */, myVar2 /* : string */) {
  return false;
}
```
on class functions - they're not treated the same as regular function declarations.
Babel seems to clobber them and give me 

```
func(myVar, /* : number */ myVar2 /* : string */) { // First type info after comma for some reason
  return false;
}
```

which errors out.

**Comment by samwgoldman** [comment]
Thanks for your input, everyone! I'm organizing the existing issues around this and taking @callumlocke's advice to create a checklist. To that end, I'm merging this with #560.

**Comment by Hector409-hmg** [comment]
I'm not normally one to complain, but this has be open for 9 months and as of flow 0.13.1 I'm still waiting for const/let. I would really love to use flow, but I have a lot of let and const in my project.

Thanks.

**Comment by friday** [comment]
@Hector409-hmg Work is being done (or at least was until recently). They're implementing it the "proper" way, but not only treating let/const as var, but also validating. If you just want to be able to use let/const, but treat them as var there are instructions in the pr comments: https://github.com/facebook/flow/pull/431#issuecomment-118206002

**Comment by oguzbilgic** [comment]
+1 for `let` `const`

**Comment by vjpr** [comment]
+1

**Comment by webhipster** [comment]
+1

**Comment by meagar** [comment]
+1

**Comment by impinball** [comment]
@webhipster @meagar and anyone else here, please check out #560.
