### ISSUE TITLE
Generic type constraint ignored in higher-order function

### ISSUE THREAD

**Issue by naomik** [facebook/flow#6200]
Found a question on StackOverflow: https://stackoverflow.com/questions/49993018/flow-annotations-for-recursive-function/50002456

⭐️ How we'd like to write it using flow's [generics](https://flow.org/en/docs/types/generics/)

    const Box = <A>(x:A): Box<A> => {
      return {
        map: <B>(f: A => B): Box<B> => Box(f(x)),
        fold: <B>(f: A => B): B => f(x),
      }
    }

🤔  Now we create a demo `number => string` function with a sample `Box<string>`

    const numberToString = (x: number) : string =>
      String (x)
    
    const b : Box<string> =
      Box("1")
    
⚠️ This should fail, but it doesn't

    b.map(numberToString)

🔍 Query `is:issue is:open generic` has [150+ open issues](https://github.com/facebook/flow/issues?utf8=%E2%9C%93&q=is%3Aissue+is%3Aopen+generic).  If this is a duplicate or isn't considered a bug, feel free to close this issue.

🐛 View the bug here on [flow.org/try](https://flow.org/try/#0MYewdgzgLgBAQiAHjAvDAPAQQHwApEBcmAlAfEltqlQN4BQMMATgKZQCuTYM9jjAtgEMADmXRw8AMzKZq8UuUTiqKKgkS5J+YsQA0DPpJAAbACZiJmmXLgK4crYj0GAvnTd8+dUJFhh2-ABGLEwAKiAAylBMAJZgAOaoMPhk-kEhxDBk0LEJ1AZRuYnadN7g0DCBWYroOXHxKgbquABEAIwtxKUA9N0wEAAWIOxmMJKCMca6leywpiAsEDBgIFB0gQB0QsK4acFhkdH1xEA)

**Comment by apsavin** [comment]
Could you please provide a link to flow.org/try?

**Comment by naomik** [comment]
@apsavin i updated the post

**Comment by thehogfather** [comment]
@naomik @mrkev here is an alternative without classes. It is more verbose than the class version see [flow try link here] but I think the outcome is the same. (https://flow.org/try/#0C4TwDgpgBAQg9gDwDwEEB8UC8UDeAoKKAWwEMwAuKJGNACgDNKUsMYBKF2RatAGgKj04AGwAmlHgyad2mVngC+AwngDGcAHYBnYFABGiLFXS0E5FG0rxk6TvkIAnCMACuDjbmXEyEmlKjMcrCWXMg0nAYIDKZsbPyEhEJivnSMATIhMJz0MfFQSkoJCWqaOlAaLkR6EA4AKnAAysAOAJYaAOZGppQVVTUclDqtHSwCTcOdMXgl2rpDbe31AHKV1Q5dZlDzHSG9a5wA1AgA3F4q6rP6UFbc2+0Y2JG0AEQAjM9s0wD0X1sAFnAXGJBCQWsJePoXLpRHAIFpynBgHg9AA6UhgWh7Gr1cYLT4-LQAoG6DSIkFgmZlADWRlR6Nod2Wq36QA)

Main issue I spotted with the original post was the overloaded use of `Box` as a value and as an undeclared type (which probably means it becomes `any` hence no errors?).

```javascript
type Box<A> = {
  map: <B>(f: A => B) => Box<B>,
  fold: <B>(f: A => B)=> B
}
    
const box = <A>(x:A): Box<A> => {
  return {
    map: <B>(f: A => B): Box<B> => box(f(x)),
    fold: <B>(f: A => B): B => f(x),
  }
}
      
const numberToString = (x: number) : string =>
  String (x)

const stringToNumber = (x: string): number => +x;
      
const b : Box<string> = box("1")

// should fail, but does not
b.map(numberToString)
//shoult not fail
const k = b.map(stringToNumber)
```

**Comment by Slowyn** [comment]
@thehogfather That what I was looking for in the original question. Your solution looks really cool 👍

**Comment by naomik** [comment]
@thehogfather thanks for the explanation, I didn't realize that type name can conflict with variable names in flow. It is indeed verbose but does exactly what is needed.
