### ISSUE TITLE
Undefined Property Access Into a Function Type Coerces to `any` type

### ISSUE THREAD

**Issue by GrantJamesPowell** [facebook/flow#6203]
Flow coerces unknown property access on function type signatures into an `any` type. This behaviour could cause unexpected errors when refactoring classes into functions. 

```
type FakeType = {}
type aFunc = string => number

const b: aFunc = () => 1
const a: FakeType = b.whatTheHeck // Flow makes "whatTheHeck" any type
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAhgNZ4AquBAvGAN4C+m1YxhArgHYDGYdAZwwAnAJZcA5vwB8YLhwC2AIzzD0POFyFglALjade-MAAoAlDLABGVBq0Y2+kuSr5jSgHQIAFsQwVvPAAJPB5SMFAwVABIQngkBTI8ATAAIh8-AODQ0lS2LiwwbDdiLgATMGFiUQFkuTgwVWE4YRSfPC42AQFRCS5xKVEHDAaoJKLqVDBpsAC-MFq8BRSy0olVOA4BDx3UFCA

(I love Flow by the way, you guys are killing it)

**Comment by SamChou19815** [comment]
This is now banned
