### ISSUE TITLE
JSX with exact prop types allow too many keys

### ISSUE THREAD

**Issue by danwang** [facebook/flow#6204]
As of 357ef4fe477978eebd9212a53fcc5e0de67cec08, this passes tests but seems like it shouldn't because too many props are passed in:

```jsx
      // @jsx Foo
      type Props = {|
        a: string,
      |};
      function Foo(elem: number, props: Props) {}
      const Bar = 123;

      const props: {a: string} = {a: 'a', b: 'b'};
      <Bar {...props} />;
```

Example passing test case: https://github.com/facebook/flow/commit/79d27fa4a1a58778b0967430da95706dfa6a5c0b

**Comment by mrkev** [comment]
A bit confused by your example. Isn't `Bar` a number?

**Comment by danwang** [comment]
The `// @jsx Foo` directive tells flow how to resolve JSX. Usually it is `React.createElement`, but in these tests `Foo` is used. I adapted this from the surrounding tests in `newtests/jsx_pragma/test.js`.

So the directive roughly means "Translate `<Bar {...props} />` into `Foo(Bar, {...props})`".

**Comment by goodmind** [comment]
This is intended, because you use width subtyping here
