### ISSUE TITLE
Multiple HOCs using React.ElementConfig breaks type checking of prop types

### ISSUE THREAD

**Issue by rtsao** [facebook/flow#6205]
A simple HOC works once, but if the HOC is used again, type checking is breaks.

[Try Flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQduANmugLICeAwiZAHZY+8LAA8YggCbpseGADoe4CAKEAeAN4EIEAFxw+AVxAAjLFAC+APjjrz9OhKzNklOADcXcEMgDWWPaoAKpYAFIEAlHAAvNYy+Aq8yoIwgRxgWKpx8gCiTFggyTx8BMAA5kGWlvYeUHAA8gLRXr5YIZyK-Mnh9DVwgQDuEE3efiENWN10cNNwdKrjcFoQUWSoABYQBkwSAPpmxFBkcAD0VQzHx3AAIhBY6HwQwlAHcwNDSyvrm9t7z9BHpxoQA)

```jsx
import * as React from "react";

class MyComponent extends React.Component<{foo: number}> {};

declare var make: <T>(T) => React.ComponentType<React.ElementConfig<T>>;

var One = make(MyComponent);
var Two = make(One);
    
<One foo="should_error" />;

// Does not error
<Two foo="should_error" />;
```

**Comment by SamChou19815** [comment]
Now both error
