### ISSUE TITLE
Are certain Object.create patterns supported?

### ISSUE THREAD

**Issue by infiniteperplexity** [facebook/flow#6206]
I tend to use certain patterns for prototypical inheritance using Object.create.  I've spent several days trying to make this work and the only way I can do it, so far, is by casting through "any".  Is there a better way?
```

//@flow
let parent = {
	foo: 1,
	extend: function<T: Object>(args: T): {...typeof parent, ...T} {
		let child = Object.create(this, args);
		return (child: {...typeof parent, ...T});
	}
};
let child = parent.extend({
	bar: 2
});
child.bar;
// desired error
child.baz;
let grandkid = child.extend({
	baz: 3
});
grandkid.baz;
// undesired error
grandkid.bar;
```

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoGBTALmADgQwCcMA7HAXjAG9UBIKOOALjAEYAaOjADy1IBMWUAK4kAxlgCWcEgB4AKiwDyAIwBWGCQD4AFEQDmAZxbyAlCyoA6a1gCeuDHCh4ipLOzDXL8gL7U6tJg4YgAWkjD8YJSqGhKWYsT4fDpYYYYeBoamANwBxFjChCRgOqHhgtRedg5OLsRkHl6+OXQ+qD65QWBlEVF1bpY8fCT8OjS0KkQsAEztLT38lpOEucDAYPwYhpLEkRiEhHCEqAtL+ABendhg+oT4IwDWkpGUp0MCY3ST5ywAzHO5W73fhPRbfVbrUSbba7MD7Q7HIGPZ5nFZAA)

**Comment by SamChou19815** [comment]
If you want the chaining behavior, use class inheritance instead.
