### ISSUE TITLE
React.createRef results in `empty` types that behave like `any`

### ISSUE THREAD

**Issue by migueloller** [facebook/flow#6207]
[Here](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24QB2q8WzArpXALxwA8AFQB8ACgAeALjgB+AQEopAnkLgBvGnDjACccT16N2AGyNy4MABbEA7nEZZbAUSjEoIsgWTAjWACbmIODZUTiw4CDAYYCZkIzgAN1j2LDI5DThKGE5GODEaAF86XCM0dGwwYl92fGicrDEYNl8yqhgAOgBhEkh7Rhg+VQAfQfyVdU1KHV5sPHbcSmRG7AIRNPSGcCY2GAARYF8AWQh2PtW1dM0Aeku4ABJHMTAsfGdXKQADYABBEAA5CBgXwOWEsEF8AHlGAAJGAgIx7eKOHwgbbvLToRgArQ5KECA4AGQRSKwKL6FyCHEoIkswFQbUmbVwnEofTkbW+fwBQJBFjBkNxBKJyO2q3ShXSLN8WDcZnGmgyIOy-F8wHiCoI3FUNLpk3ycEuQjFBSAA) is a link to the reproduction.

Basically, the way that `React.createRef` is typed will result in its result to always be `{ current: null | empty }`, causing Flow to behave unexpectedly.

Ideally, `React.createRef` would be typed as `type createRef = () => mixed` so that it would force refinement. Then, I would have to do something like this:

```js
import * as React from 'react'

const refine = <T>(x: ?T, t): T => {
  if (x == null || x instanceof t === false) throw new Error('failed to refine value')
  return x
}

class Reproduction extends React.Component<{||}> {
  ref = React.createRef()

  componentDidMount() {
    // $ExpectError: `iAmNotAMethodOnHtmlDivElement` is not in HTMLDivElement
    refine(this.ref.current, HTMLDivElement).iAmNotAMethodOnHTMLDivElement()
  }

  render() {
    return <div ref={this.ref} />
  }
}
```

I [tried](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24QB2q8lBwjWcAvHADwAVAHwAKAB4AuOAH4BAGjgwAlFIE8hcAN404cYATjievRgFcANubgAfa3DF7mMZI1xYIB+N29wCyc6hYSooAFsQA7nCckQCiUMRQImR+wOZYACaKEHBsHFwAbv6mWGRKOjlYMKZQjPY0AL50uOZo6NhgxOmm+MBMcFhiMFiM6W1UMAB0AMIkkJyMMHyatvUa2rpsPJjjE7iUyEPYBCJl5QzgTMMwACLA6QCyEKYLJ1rlugD0H3AAJDFiYCw+DiCSkAANgABBEAAOQgMEh90qIQg6QA8owABIwEDmW75GJpEBXMF6dCMeGOOCYgT3AAy+MJWGJC3eFXYnBEMBCwFQEzYu2qlAWChp9MZRKuSgmUNh8MRyNRGLFDOABMlLzKuka5WF6SwiWC610FSqNX46TV7O4mm5vP5WAI9TgHyE5Ua9SAA) to run the above snippet in try.flow.org, but unfortunately, it doesn't support browser globals.

**Comment by SamChou19815** [comment]
Fixed by local type inference and new annotation requirement
