### ISSUE TITLE
Error parsing value for "esproposal.optional_chaining"

### ISSUE THREAD

**Issue by dgcoffman** [facebook/flow#6209]
The docs at https://flow.org/en/docs/config/options/#toc-esproposal-optional-chaining-enable-ignore-warn say

> Set this to **enable** to indicate that Flow should support the use of optional chaining per the pending spec.

However actually assigning that value 

> esproposal.optional_chaining=enable

causes flow-bin version 0.70.0 to throw an error

> Error parsing value for "esproposal.optional_chaining". Unsupported value: "enable". Supported values are: warn, ignore

**Comment by fishythefish** [comment]
Sorry about that! 0.71.0 adds type support for optional chaining and consequently lets you enable the option.
