### ISSUE TITLE
Errors in object argument if no variable name is given

### ISSUE THREAD

**Issue by jesobreira** [facebook/flow#6210]
Actually the issue title may be confusing, since the problem is exactly that no error is threw while it should be. But I couldn't have an idea for a better title since starting an issue for having "no error" is also confusing. Alternative titles are:

* No error in wrong type definition in object argument if it has no variable name
* Flow does not throw error when needed if the types inside an object argument are mismatch

Well, let's go to what really matters.

While the following code returns error:

```
/* @flow */

function demo(argv: {a: number, b: string}): string {
    return arguments[0].b;
}

demo({ a: 123, b: 123});
```

```
7: demo({ a: 123, b: 123});
                     ^ Cannot call `demo` with object literal bound to `argv` because number [1] is incompatible with string [2] in property `b`.
References:
7: demo({ a: 123, b: 123});
                     ^ [1]
3: function demo(argv: {a: number, b: string}): string {
                                      ^ [2]
```

If we remove the variable name, it stops detecting the error and the code runs:

```
/* @flow */

function demo({a: number, b: string}): string {
    return arguments[0].b;
}

demo({ a: 123, b: 123});
```

```
No errors!
```

Expected: the same error threw for both the code samples.
What I got: the error is only threw if the function parameter has no name.

Tested on flow.org/try.

**Comment by jcready** [comment]
In your second example `number` and `string` aren't flow types, but rather variable names used in object destructuring. You can verify this by changing the line to `return a` or `return number`. You will see the following flow errors respectively: `Cannot resolve name 'a'.` and `Cannot return 'number' because number [1] is incompatible with string [2].`

To properly type your second example you would need to do:

```js
/* @flow */

function demo({ a, b }: {a: number, b: string}): string {
    return arguments[0].b
}

demo({ a: 123, b: 123});
```

Which will correctly provide the flow error you expected:

```
7: demo({ a: 123, b: 123});
                     ^ Cannot call `demo` with object literal bound to the first parameter because number [1] is incompatible with string [2] in property `b`.
References:
7: demo({ a: 123, b: 123});
                     ^ [1]
3: function demo({ a, b }: {a: number, b: string}): string {
                                          ^ [2]
```

**Comment by jesobreira** [comment]
Thanks for the clarification!
