### ISSUE TITLE
Recursive argument propagation for methods end up as `empty` on flow 0.65+.

### ISSUE THREAD

**Issue by izaakschroeder** [facebook/flow#6211]
The following example correctly fails on flow 0.64 but silently fails on 0.65+. The inner function arguments resolve to `empty` after a nesting depth of 2. Interestingly this is only a problem if called via `store.dispatch`. The plain `dispatch` function works (and fails) correctly. Unless I'm missing something 😕 

Sorry if the issue title isn't worded exactly correctly... the issue is hard to describe.

https://flow.org/try/#0C4TwDgpgBAIglgZzAQ2AYwBYB4DKAaKAQQIGEA+KAXigG8AoKKLAFTIAo34lVNcDio5AmwCUVCvkFjKFZiIBcUZgG4GUNoQVFVAX1V1QkKDmAB7AE4Q+RUhWr1GAE0Qp0GRV1e9JAoWoDmEMAmqBCiivhqCACuAEYIaOZwsWGi4lAAbqZwjlppMpnZjnhqlmAANshoEABKEI7R1eYcOFAAPoU5-NISWllddHpqjAbg0CHA0PYAZqamigB20QC2KeZDhtCEaMBwpgtUtJuKAOQA7hAQJxtjgvuTAB7AhzSxyOaKCMBJC-5DdI4IGhKpZMu8oF8LBB5CYobhgKF+Ds9gtSPcIE8yKpAcD3tAMuDnNw3PJPDxsBMIEjdvs0QtHsAsXQ6AB6FlKUz+fzlaDLaApYAXCAHAAGkMsADoiV4MCKoMgFo4oCLpeSRaz2cxOdzoNNyqYzpkIOYECioAKhQcAAwSgBsAFZ5YqoDbbQAWOhofZfKCWGLlZ7UcUQKUuckcRwARh6tFKQWi5gOUYjACYYw5GL744moI4UxGAMzp4aZyzABNJgscYuZ2tZ8s5+2qOtQHQiZuZtsdruDdvMtlQAAkAFEHpAdsPzOYLHQ2H7ogHPt84L8REA

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
