### ISSUE TITLE
Predicate functions don't apply refinements of called generic predicates

### ISSUE THREAD

**Issue by AlexKolpa** [facebook/flow#6214]
If you have a predicate with generic type argument, it's not possible to call this from a typed predicate as such: [Flow Try example](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKSoB2phsNoh6AyprgDwAqAfABQA3AIbQAXKAD83AJQSARrFjRMwpgFJiAC0zEA1ulABvRAEh8HVPiYjooAIQBeR6BqpodgGSfQth89BaABNMSEIaTCDKAF9EKlp6RmY2DgBBGiCAOVhcAFEAWwAHXABPIVEJSTwiGgBzOVBFZVUNbV0DY0RQUAtcKyYWdlxy6BlQb19RfxcAIhmYuOo6XAYmXEw8Ecrq8PrO7sJIUH5BtIzsvKLSkZkxk27u4kZ0ZoA6OFqR1+1hfFThgCMt0o3Vi0SAA). It seems as if Flow can't apply the refinements of the `isSet` predicate to the `isSetAndNotEmpty` predicate. If you replace the `isSet<T>` with the proper type, flow has no issues here: [Flow Try example](https://flow.org/try/#0PTAEAEDMBsHsHcBQByArgZwKanQFwE4CWAxrsgNyKSoB2phsNoh6AyprgBQBuAhtAC5QAfjxEaAcwCUQgEaxY0TLyYBSYgAtMxANbpQAb0QBIfB1T4mfaKACEAXnugaqaDYBk70NbuPQtABNMSEIaTADKAF9EKlp6RmY2DgBBGgCAOVhcAFEAWwAHXABPHn4hUQJQ6TkFJRVQdS1dfSNQUDNcCyYWdi5rKVBPb35fJwAiMaiY6jpcBiZcTDxSwRExKoHW5khQTh6UtMycguKVqU3ENrbiRnRFTAA6OAkVh81efGSuAEZzyjbopEgA)

**Comment by SamChou19815** [comment]
This now works
