### ISSUE TITLE
Possible BUG: $ObjMap doesn't work for param types

### ISSUE THREAD

**Issue by rostislav-simonik** [facebook/flow#6216]
I wanna transform value type: one function signature to another in object literal by $ObjMap

Could you please confirm whether it's flow internal issue, or I do something wrong. Thanks for answer. 

```
type TransformValueType = <PARAM> ((param: PARAM, test: string) => void) => (param: PARAM) => void

function aa<ATTRIBUTES: {
  [key: string]: (param: any, fixed: string) => void
}>(attributes: ATTRIBUTES): $ObjMap<ATTRIBUTES, TransformValueType> {
  return Object.keys(attributes).reduce((acc, key) => {
    const foo = attributes[key]
    acc[key] = (param) => foo(param, 'fixed')
    return acc
  }, {})
}

const attributes = {
  a: (param: {f: string}, test: string) => {},
  b: (param: {c: number}, test: string) => {},
}

aa(attributes).a({  // DOESN'T WORK, BUT IT STOULD 
  f: 's',
})


aa(attributes).a({  // WORKS, AND IT SHOULDN'T
  f: 's',
  c: 1,
})
```
throws following error
```
18: aa(attributes).a({  // DOESN'T WORK, BUT IT STOULD                      ^ Cannot call `aa(...).a` with object literal bound to `param` because property `c` is missing in object literal [1] but exists in object type [2].
References:
18: aa(attributes).a({  // DOESN'T WORK, BUT IT STOULD                      ^ [1]
15:   b: (param: {c: number}, test: string) => {},
                 ^ [2]
```

https://flow.org/try/#0C4TwDgpgBAKgTgQwHYGcBmB7OBbAaggGwFcIZxoBeKAHgAUBBAJXoFkA+KACk7AUWwBcUBsxYAaKMAgpgQmXACWSAOYBKKBQ4A3DAoAm6zV178hI1oe269AKBtoiSAMbAFGJFAQJq9GDEYAkgBCAKowAKIAykIA3jZQUADaANYQIHLAiioAukI8fAiCnkggEmgKAB4QehlZahpW+jYAvmycCMCZCgBGRFIoQr7+wWFRqkIAJADy3QBWLAhgPn6BoRGREvDI6Fh4hCRkkBxxCXAQwERwHjOzEC4AdKkgKO2dir39qvdnekROENwEE4nBInpYoCcElAnO4ZFBMBgNJ43j0+tIUmlsvEoUCnBiQNkkfl+OCEcTChIAOTlKp6SmqbGnc6XDy47HNCQxZoM5p2GGoYDIrofaRIyEIPImQqxNC1JTKDmSaSyKDyeXgrlibHdSUFIoxJxCJBEbDdCBwRX9FVqlQajktOxeV7CtEoL4ITgxBIAem9UAAIlMogA5SkwKAAdSmjAA0hI1lAAuHIjApiEADL+qDY2VQSkoSla7l2GxOjouz73D1eqC+yPRmMbKD0YNZpNQSIACTTmdDMBzQnzhexhqgAEYiwygA

**Comment by dangh** [comment]
May be this works for you?

```diff
function aa<ATTRIBUTES: {
-  [key: string]: (param: any, fixed: string) => void
}>(attributes: ATTRIBUTES): $ObjMap<ATTRIBUTES, TransformValueType> {
```

**Comment by dangh** [comment]
I don't see anywhere in your code enforce the param type in the second case. `{f: string, c: number}` is subtype of `{f: string}` so I expected no error here. Maybe you missed the exact type?

```diff
const attributes = {
-  a: (param: {f: string}, test: string) => {},
+  a: (param: {| f: string |}, test: string) => {},
  b: (param: {c: number}, test: string) => {},
}
```

The only downside is flow will not infer the attributes type unless it is used once.

```js
const attributes = {
  a: (param: {|f: string|}, test: string) => {},
  b: (param: {c: number}, test: string) => {},
  c: 'abc' // no error until we called aa(attributes).c()
}

aa(attributes).a({ f: 1 }) // error, good
aa(attributes).a({ f: 's', c: 1 }) // error, good
aa(attributes).a({ f: 's' }) // pass, good
```

**Comment by rostislav-simonik** [comment]
@dangh Oh, I see. But could please explain why
```
function aa<ATTRIBUTES: {
  [key: string]: (param: any, fixed: string) => void // <<<
}>
```
caused not desired behaviour. I want to understand to prevent future mistakes. Thanks a lot.

**Comment by rostislav-simonik** [comment]
Is that due `param: any` ?

**Comment by SamChou19815** [comment]
The issue seems to be fixed a while ago
