### ISSUE TITLE
Generic object types not being enforced

### ISSUE THREAD

**Issue by alaboudi** [facebook/flow#6220]
My mapper objects do not enforce my type rules for some reason I have been able to reproduce this in the link below. 

```
type EntityState<V> = {
  ids: string[] | number[],
  entities: {[id: string | number]: V}	
}

type User = {
  id: number,
  name: string,
}

const ids: number[] =[1] 

// why is there no error thrown here. If [1] was changed to ['1'], it will fail as expected though
const state: EntityState<User> = {
	ids,
  	entities: {
      [1]: 'hi'
    }
}
```

The link to reproduce it is here: https://flow.org/try/#0C4TwDgpgBAogdsAlqAysAhsCAeAagPigF4oBvAKCikQBMBnALijuACdE4BzAbQF0oAPlDgBXALYAjCKz4AaSlAgJkiCIzLdaTFuy6Dh4qa15NcAXwCQ5M+XKhIUAKp1pxMgq0HJ0+VTjoxCG02Dk55G3IAYwB7OBZqeiZRbxl+Im4ARn5bAHocqAB3RAAbYuFo4ChgAAtWaILFVjrWKAAzaJa6aMCoVgh0Lrgo2PiWTCDYZVQMLGxnaUISCgtaOl8oCyUkJDUmCioDqEyTKAByasRThSobCLzCkrKauobpZqgwOshWYpBhuMqYywACYmPBtiA0OM5i5WIt3Ct6OtNlNVOp9ocjqcMqcTudLtcoLdyEA

**Comment by idiostruct** [comment]
This is a known bug: https://github.com/facebook/flow/issues/1971, https://github.com/facebook/flow/issues/2928.
