### ISSUE TITLE
Intermediate type annotation for parameterized function used in JSX hides errors

### ISSUE THREAD

**Issue by danwang** [facebook/flow#6221]
Hello!

I was using flow recently and found a case where adding a type annotation to a variable causes Flow to drop type safety without warnings. ([flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvACShgA2WIWzGMhjAWAeRDAYMLABMAXCmYBPOAF44zAK7du9OjGVgsmLEyiz1cAN504cNlEWPgzAOYAaO5q0hF2kAAjLCgvAF99Q2M4AAViMFQAHgwPOABpAD4ra0pzWTSsZUU01IA3ZG4tLEV2AFFefkEAFSMsZNTMiIYAem64ADFgKDYHQ14AOjgACgB3aABrdDQ4LAAPY3w5AEpGFhHB4fgNRILlDKmweNRFOIgE5LNoWQ7CjK3FbDwYcYA5CFkTGostpdPREgcRrknqc1AAiRywuDlSpYOEudxIipVVIQeYAQkR3QyYIh8ChFhhsICiORVTRMCgrjcmJRqWYEHguIJcCJ+l6cAAyo9mJY2MoJtNZBAsOh2fA5lB5ih0GsNjJZDsoiYhUwRU0rCdXhcrjcrg88i8zlt1FlPvhfv8sPRdSMdSwFILhbJ9RpOOAGgIhCJxJJpHIwW6RXByflCvSoDSsaj4QymSzsXAuYTiXR+U0ABbAdBSmXMMhkmU6eCuFZQYhQPF0RKRywxynU9PJ9HM2lYNkczP47M0IA))

In this example, we are adding the type for a React component that accepts a type parameter. The first style works as expected, but the second does not provide correct type safety:

```jsx
const First = <Key>(props: Props<Record, Key>): React.Node => null;

type SecondT = <Key>(props: Props<Record, Key>) => React.Node;
const Second: SecondT = $implementationOmitted;
```

In my investigation, I discovered that **this applies only to functions that are used in JSX**. For example, the same example, but with function invocations, works as expected: [flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvACShgA2WIWzGMhjAWAeRDAYMLABMAXCmYBPOAF44zAK7du9OjGVgsmLEyiz1cAN504cNlEWPgzAOYAaO5q0hF2kAAjLCgvAF99Q2M4MTARFlQAHgwPOABpAD4ra0pzWTSsZUU01IA3ZG4tLEV2AFFefkEAFSMsZNTMiIYAem64ADFgKDYHQ14AOjgACgB3aABrdDQ4LAAPY3w5AEpGBMIrRILlDKmIONFWRVj41mSzaFkOwoyt-x1udSztXXoCKZz7hYjooyI4yGUKlUQS53HBypUsKkIPNkMoAIRkMJbX7-XIPYHkALguGQ6rkGFuEkI1LMCDwZGojFY-S9OAAZXuzEsbGUE2mcygixQ6DWGxksh2TFY8DcikOzym1wuSWweSexy2nx8uisnHADQEQhuEik4voblxgPyhWhMCgxPhUPJdtclMdiLgDPRmOxdAtALyBLIRIhCNtUFdVKqNLpnpR3uZQA)

**Comment by SamChou19815** [comment]
It seems to work now
