### ISSUE TITLE
How to dynamic assign value?

### ISSUE THREAD

**Issue by PengJiyuan** [facebook/flow#6224]
Just like this:

```javascript
/* @flow */

class A {
  a: string;
  constructor() {
    this.a = 'aa';
  }
  setProps(props: {[key: string]: any}) {
    for(let key in props) {
      this[key] = props[key];
    }
  }
}

const ins = new A();

ins.setProps({
  b: 2,
  c: 3,
  d: 4
});

console.log(ins.b, ins.c, ins.d);
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwxsAuMXAFwCcBLAOwHMBucsDOF+hgFcMdOAwAUASlLcKdABZNcAOmxgAvGADk2bFq4UAvt1wBTOgAUGcAA65xN63ZokA2gGtTATxoDWbAF0abBYvQ2kyCgooMXEYczBPLzBWMEdbXAjZKIUlD28AjTSnXHyvAIMo4yNUY0w+ehT+IpZTJEIpLlRWFTNLEvFIsAAjGgAmABpuDBoAZimKABMaABZayS7efjh45Xg2cR7lYYmmlQxTo8WNoA

**Comment by apsavin** [comment]
See #1323

**Comment by mrkev** [comment]
Closing in favor of #1323
