### ISSUE TITLE
$Diff<A, B> causes property variance in A to be lost in resulting type

### ISSUE THREAD

**Issue by nirrek** [facebook/flow#6225]
If the properties in A have variance, then the variance is lost in the resulting type.

```js
type A = { +p: any, +q: any };
type B = { +p: any };
type SetDifference = $Diff<A, B>;

let object1 : SetDifference = { q: 3 };
// This should be an error since 'q' should be read only. Unfortunately this typechecks.
object1.q = 5;
```

Repro:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5gDUOAXGAIYB2WANNQI73NZgC+Abky4CAIVIVqdRi35Ds+MAGU8GACIBLKFDwAnPEwDGBMgBJN2gDyF2ogHxDUMVWDgAjAFZ5DGAIxh6FXUtHX0jE0kuMABmOVRgYDAAFQALDQBnMHSUuABXGAATMDcCZjA9XThdLI1wsAByDnqsnPyikrB9BiK4JhgsADowAFUmKCqMXKYGDDx+sAw0zIVvFO8Aa3SB1HcvH18BjgkAVkcVsABZZlyGGCCLUINjCUoqKJ445wxXT28MACYApdrrd7iE9E8IpQjvRYoJ4olUhkwIYqvofPMAOYaABueGWa305V0lWqixmDQ4AAMwMimHBvghdBoMAw3M4dr8fP9DichEA

**Comment by lyleunderwood** [comment]
This really sucks, I'm using styled-components and the `withTheme` implementation uses `$Diff` internally (not really any other way to implement it) so variance is lost on all my prop types...

**Comment by jcready** [comment]
I would be disappointed if they fixed this variance issue with `$Diff` as I've been using it as a `$ReadWrite<T>` similar to `$ReadOnly<T>`.

```ts
type $ReadWrite<T> = $Diff<T, {}>;
type A = { p: any };
type B = $ReadOnly<A>;
type C = $ReadWrite<B>;

declare var a: A;
declare var b: B;
declare var c: C;

a.p = 1;
b.p = 1; // Expect error
c.p = 1;

(c: A);
```

**Comment by goodmind** [comment]
@jcready Nah, https://github.com/facebook/flow/pull/7643

**Comment by jcready** [comment]
That will be a great addition. Hopefully that lands soon.

**Comment by goodmind** [comment]
> soon

lol

**Comment by SamChou19815** [comment]
Closing since we are not changing $Diff, but the new Omit type can preserve variance
