### ISSUE TITLE
$Diff returns 'empty' for everything

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/flow#6229]
If this is a bug, please try reproducing using https://flow.org/try/.

Using this test file:

```
// @flow

type foo = $Diff<{a: number, b:number}, {a:number}>
```

Flow returns `empty` for the type of foo:

```
 📒10 🍺 yarn flow type-at-pos test.js 3 7
yarn run v1.6.0
warning package.json: No license field
$ /Users/edwarddrapkin/flow-test/node_modules/.bin/flow type-at-pos test.js 3 7
type foo = empty
/Users/edwarddrapkin/flow-test/test.js:3:6,3:8
```

When the type should be {b:number}.

I am unable to get $Diff to return anything but empty under any circumstances.

**Comment by vicapow** [comment]
From my experience this is an issue with type-at-pos but flow will still error on regarding inconsistencies when running flow check. Hope that helps

**Comment by darichey** [comment]
This works now.
