### ISSUE TITLE
instantiating imported constructor

### ISSUE THREAD

**Issue by rielsi** [facebook/flow#623]
Getting errors when `new`'ing constructor function imported from another module:
###### another.js

```
/* @flow */
export default function Extern(param /*:any */) { this.param = param; }
```
###### main.js

```
import Extern from "another"
new Extern("Test!");    // <-- Error: "assignment of property param / Property not found in / new object"

function Local(param /*:any */) { this.param = param; }
new Local("Test!");    // this works
```

Could be related to https://github.com/facebook/flow/issues/286 and https://github.com/facebook/flow/issues/23 and https://github.com/facebook/flow/issues/323

**Comment by billschaller** [comment]
Can't repro error on 0.41, but it's become a different issue: #3521

**Comment by calebmer** [comment]
Closing since we can’t repro. Please let me know if you still have this issue!
