### ISSUE TITLE
Flow can't infer that unknown string always belongs to $Keys by condition

### ISSUE THREAD

**Issue by jaroslav-kubicek** [facebook/flow#6230]
Hi all!

I was trying to use more narrow types, `$Keys<typeof Locales>` instead of `string`, but flow can't understand that I'm narrowing down any unknown variable string to a limited list of possible values by a condition.

Thanks for helping me.

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAkgMoDyAMrCgIbQCmmAKrEQEaaw3bWgC8oA3oqFBMA5gH0AQgHEAXKADkIgLRS5AGgGhKogKIFZcyot1qNKTKIDCALX1nF1k4IAmFUQBEA0vpeLPj0E7U7tre1L7a-oGiAIJ0oYqxkUEWABLxqf7U0KKSAEr6WYp5meg54gXoReIlMQCqFQm1NRbRDS012iHy1JWdNSle3ZUDNXgAcg3jo11yPYp4EeqCPaIAsgCaDRs1YzZDirs1BDL7xzVWrfsXNQAKaft3NbV6+8+Z5roFmEYEJgC+AG5UBgcKBhNRsGRKDRuKAABQUFAoagAB0hFHQwgArhRwbIAPw4ABOAEtMQBKbgAPj4phBuDg0OosgAJB5qABPTAAHmwHJR1FgkHwxChVFoDGYrHY1BpPA0ggRSNR6MxOPBoAAZJqRaRyOL6IwWGwIdQANqI5FokgY7G46gAXUp+NAlpVNrV9tAFVEbyBgiJEKxRPQoEZ4qBgMQQA

**Comment by danwang** [comment]
Try `getLocale('toString')`

**Comment by jaroslav-kubicek** [comment]
@danwang I know what you mean, the thing is that I tried the same with `hasOwnProperty` and it's still complaining as well: 
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAkgMoDyAMrCgIbQCmmAKrEQEaaw3bWgC8oA3oqFBMA5gH0AQgHEAXKADkIgLRS5AGgGhKogKIFZcyot1qNKTKIDCALX1nF1k4IAmFUQBEA0vpeLPj0E7U7tre1L7a-oGiAIJ0oYqxkUEWABLxqf7U0KKSAEr6WYp5meg54gXoReIlMQCqFQm1NRbRDS012iHy1JWdNSle3ZUDNXgAcg3jo11yPYp4EeqCPaIAsgCaDRs1YzZDirs1BDL7xzVWrfsXNQAKaft3NbV6+8+Z5roFmEYEJgC+AG5UBgcKBhNRsGRKDRuKAABQUFAoagAB0hFHQwgArhRwbIAPw4ABOAEtMQBKbgAPj4phBuDg0OosgAJB5qABPTAAHmwHJR1FgkHwxChVFoDGYrHY1BpPA0ggRSNR6MxOPBoAAZJqRaRyOL6IwWGwIdQAHQACwomCI8HQNyJsAFRL5SuRaJIGOxuOo5Mp+NAiPdqu9GoqojeQMERIhWKJ6FAjPFQMBiCAA

**Comment by stefanvonderkrone** [comment]
I stumbled upon the same problem and my solution to find the string in the object's keys:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAkgMoDyAMrCgIbQCmmAKrEQEaaw3bWgC8oA3oqFBMA5gH0AQgHEAXKADkIgLRS5AGgGhKogKIFZcyot1qNKTKIDCALX1nF1k4IAmFUQBEA0vpeLPj0E7U7tre1L7a-oGiAIJ0oYqxkUEWABLxqf7U0KKSAEr6WYp5meg54gXoReIlMQCqFQm1NRbRDS012iHy1JWdNSle3ZUDNXgAcg3jo11yPYp4EeqCPaIAsgCaDRs1YzZDirs1BDL7xzVWrfsXNQAKaft3NbV6+8+Z5roFmEYEJgC+AG5UBgcKBhNRsGRKDRuKAABQUFAoagAB0hFHQwgArhRwbIAPw4ABOAEtMQBKbgAPj4phBuDg0OosgAJB5qABPTAAHmwHJR1FgkHwxChVFoDGYrHY1BpXA0gmYACtqChsAA6ADWnMwcMIpHI4vojBYbAh1HJ6sgZKccMZ4upoHtMK4rtAiORaJIGOxuItoAAPgGhqI3kDBESIViiegnYaaEDAYggA

Not the best solution, but it solved the type issue.
