### ISSUE TITLE
Flow: Cannot resolve name `active`

### ISSUE THREAD

**Issue by Jahans3** [facebook/flow#6233]
I think this is a bug, I am destructuring a property from one object and in the same destructuring assignment using the value to get a dynamic property from another object. The objects are Redux reducers.

I've reproduced it here:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoApgDwA5wE4AuYAxnAHYDORA5ugQIJllwECGBAluQKp4cVgAvGAAUAbzDxi7LmQBcYCa2KcAbujABfADRgo6dABMFEgNrK16ALomwrJixk8+AzUMVvPCgPIAjAFboKgCUCvR4eKwAngA8VHxk1AB8Qin2zGyczvyoqEA

And here's the offending code:

export const getAnnotationUris = ({ location: { active }, feed: { [active]: { annotationUris } = {} } }: Object): Array\<string> => annotationUris

**Comment by Downchuck** [comment]
I've hit the same issue - it may be helpful to add in a failing test over at https://github.com/facebook/flow/blob/master/tests/destructuring/destructuring.js

I can't guess on the level of effort needed to actual fix the issue.

**Comment by wchargin** [comment]
Agreed that this is a bug. To explicitly clarify what’s going on: the
problem is that the variables bound within in a destructuring are in
scope for the lexical remainder of the destructuring. So, `active` is
_bound_ in the `location` assignment property and _used_ in the `feed`
assignment property. Flow appears to be evaluating these independently,
whereas it needs to thread the lexical context through from one to the
next.

**Comment by SamChou19815** [comment]
We no longer produce the bad error.
