### ISSUE TITLE
Announce Flow releases on the blog

### ISSUE THREAD

**Issue by danvk** [facebook/flow#624]
There have been eight releases of Flow since 0.5.0, but only one of them has been mentioned on the [Flow blog][1]. To find out about Flow releases, I check the [GitHub releases page][2] once or twice a week.

It would be helpful to have a venue where new versions of Flow were reliably announced.

[1]: http://flowtype.org/blog/
[2]: https://github.com/facebook/flow/releases

**Comment by gabelevi** [comment]
You're 100% right. Even if we don't have a feature blog post written, we should still post something to the blog & tweet it too. I'll add these to our release checklist. Sorry about that!

**Comment by jeffmo** [comment]
Sounds like @gabelevi is taking point on this ongoing, so going to close this issue out.

If you can think of ways in which we could do even better still in the future feel free to re-open, continue commenting, or continue sending feedback anywhere you can. Hearing this stuff we could do better is really really helpful, so please keep it coming!
