### ISSUE TITLE
What is the difference between `A & B` and `{ ...A, ...B}` in flow?

### ISSUE THREAD

**Issue by tanhauhau** [facebook/flow#6240]
Background:
I have code that looks [like this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBCAhgM4CWAxgJIB2UcYAvGAN6phg1EC2uAXGBLoATmRoBzVAF8A3Kgw58AQQAmANyI0KuWvSaFSlXQwBkrdmCIqVw3CRIChoiQBppc1FACuW9GTg0YOK46Ko2diQAFGL0AsTk1HQMAD5gqhpaOkkAlOYcZFBg0UkAdFbh9rlsHBy26F7CgTFwZda29nIcUhZ1DYEA5Cq4UEReMOiWbRH9clJAA)
```js
type BasicInfo = {
  name: string
};
type AdvanceInfo = BasicInfo & {
  address: string,
};
function getAddress(info: BasicInfo | AdvanceInfo) {
  if (info.address) {
    return info.address;
  }
  return 'default address';
}
```
However upgrade to 0.68, this throws an error because of unknown property access in conditionals

While trying to fix the code, i found out that [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwBCAhgM4CWAxgJIB2UcYAvGAN6phg1EC2uAXGBLoATmRoBzADSoAvgG5UGHPgCCAEwBuRGhVy16TVuzAA6M8XLU6caRyJq1w3CRIChoidPmKoAVx3oZHA0YOK46OqOziQAFGL0AhaU+gwAPmDqWjp61gCURhxkUGBx1ib2US75bBwcTui+wiHxcOUOTi4KHDLG9Y0hAORquFBEvjDoYBUdJAMKPUA) actually works
```js
type BasicInfo = {
  name: string,
};

type AdvanceInfo = {
  ...BasicInfo,
  address: string,
};
```
so I'm curious, what is the difference between the 2 and which annotation describe `AdvanceInfo` more accurately?

**Comment by oriSomething** [comment]
In `{ ...A, ...B }` If `A` is not "exact" all the keys can be `undefined`. The same for `B`
In `A & B` the new type should contain both properties of `A` and `B`

**Comment by tanhauhau** [comment]
but then why is it that `{...A, ...B}` does not throw a flow error but `A & B` does?

**Comment by apsavin** [comment]
@tanhauhau 

1. `A | B` where `B` is `A & C` throws because you're trying to get a property that is definitely missing in one of the branches of `A | B` (in `A`).
2. `{ ...A, ...B }` does not throw because this construction produces a new type. This new type contains all the properties from `A` and `B`, but as optional properties (as @oriSomething correctly described). However, you use `if` to check that an optional property exists, so flow sees no errors.

**Comment by tanhauhau** [comment]
@apsavin the property missing in branch `A|(A&B)` (in `A`) is missing in branch `{...A, ...B} | A` in `A` as well right?

**Comment by apsavin** [comment]
Yes, but why `{...A, ...B} | A` when you have just `{...A, ...B}`?
