### ISSUE TITLE
Possible bug when using union types

### ISSUE THREAD

**Issue by TimothyJones** [facebook/flow#6243]
I have the following code ([available here](https://flow.org/try/#0C4TwDgpgBAygjgVwIYCcI2E40C8UDeAUFFAG5IA2CEAXFAHYIC2ARhCgDSEC+A3IYVCQoASXrYU9SvGRooeIiXJVaDZmxRQAPmooUufARAAeYAPYpgUAGYJ6AY2ABLM-SgBzCMACySYwAoAZ0RUCEC6AEEUFCQQAB4xCSkKGVCAPm0oKJj41LQMLAg0gEo6RlZ2AmISKDRgBEkoYNkwgDo0ABMEewh-WwdnV38kKDL1dg4oFlHRcXZkvOgdRYLsUrUKzUUakidrKH8WVuVqeRw8Rj1iqp2duoa3JH5bqG4oCApA6G2X+8bfYAAC1aTD8w0mRxOEGKz1u3GqJG4kwADDCeAIgA)):

    type SquareState = {
      value: number,
    };

    type InternalSquare = {
      value: number | null,
    };

    export function getMax(squares: Array<InternalSquare> | Array<SquareState>): number {
       return squares.reduce(function(a : number, b : InternalSquare | SquareState): number {
        if (b.value === null) {
          return a;
        } else {
          return Math.max(a, b.value);
        }
      }, 0);
    }

Which is generating this error:

     9: export function getMax(squares: Array<InternalSquare> | Array<SquareState>): number {
                                                                 ^ number [1] is incompatible with null [2] in property `value`.
       References:
       2:   value: number,
                   ^ [1]
       6:   value: number | null,
                            ^ [2]

As far as I understand, there should be no error, because there's a guard against `null`. The code works fine with either: 

    export function getMax(squares: Array<SquareState>):  number

or

    export function getMax(squares: Array<InternalSquare>): number

But not with `Array<SquareState> | Array<InternalSquare>` 

Also, if I [replace the reduce with a for loop](https://flow.org/try/#0C4TwDgpgBAygjgVwIYCcI2E40C8UDeAUFFAG5IA2CEAXFAHYIC2ARhCgDSEC+A3IYVCQoASXrYU9SvGRooeIiXJVaDZmxRQAPmooUufARAAeYAPYpgUAGYJ6AY2ABLM-SgBzCMACySYwAoAZ0RUCEC6AEEUFCQQAB4xCSkKGVCAPm0oKJj41LQMLAg0gEo6RlZ2AmIyVCgmP3koAAZ+EmsLf3JNJ0amqF4oHrioYNkwgDoKCHp3YAALfsGoAGpl4qqSTadrKCCQtECAbScAXXHlankcPEY9dcVNzftXZ0YIVsfuKAgKQOgHx51Bp4Xzzcb1AIQjgjfZhY5nC4QYofTbcapokhoYAISRA4z8NGEIA), it works: 

    export function getMax(squares: Array<InternalSquare> | Array<SquareState>): number {
      var max = 0;
      for(var i = 0 ; i < squares.length ; i ++) {
         if (squares[i].value === null) {
           continue;
         } else {
           max = Math.max(max, squares[i].value);
         }
      }
      return max;
    }

Is this a bug, and if not, what am I missing?

**Comment by TrySound** [comment]
This probably can be closed.
/cc @vkurchatkin
