### ISSUE TITLE
Extending React.ComponentType type

### ISSUE THREAD

**Issue by dquang-tran** [facebook/flow#6245]
I have an HOC with this signature:
```
const enhance = (fragments: FragmentMap) =>
  (Component: React.ComponentType<*>): React.ComponentType<*> => {
    class WithFragments extends React.Component<Props> {
      static displayName = `WithFragments(${getDisplayName(Component)})`;
      static fragments = fragments;

      render() {

        return <Component {...this.props} />;
      }
    }
    return WithFragments;
  };

```
All this HOC does is adding a static field `fragments` to a react component. 
Right now, the return type of the enhance function is a function whose return type is `React.ComponentType<*>`.
This is an incorrect return type, since React.ComponentType<*> type by default doesn't have `fragments` field attached to it. So, if I were to use a component enhanced this way, by accessing 
`enhancedComponent.fragments`, I would get
`property `fragments` is missing in statics of `React.Component` [1]`.

What is the best way for me to create a new type that extends React.ComponentType and supports `fragments`field.

**Comment by rostislav-simonik** [comment]
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA24QB2q8WjAFso7lnALxwAFAEp+APjgAeAAoYA8tIDKYwQGESkRmxgAuTFRgA6deCbaAKgE8wWGfKVjhe7HiMnNF67dkLlcAGRwAN40cHBEyADmINqoegBGEBAANjiMNAC+4sGhcLjJaOgA6sAw7IowyDDAuNLEYJQwlnBYAB4wbAAm6C74xhpmjDB2vhIhYWEsVTXhUFExQ+gCBMjJqFgA3LlhlIydWFAiORMTjQCuUIxS7oPwQYYPZcCohg0QYKhZAPRiWycZuQBOywMAuVxKZQq01q9Uali2GT+cFy9AKqHQNy0Qwh7AgZxgUOqMPeByaLXaXR6Bn6pixwyCGTGmToDGY8Ex2hxhJqdRJsGaAjYnG4WBEagGdJxeIJlSJvJs-OEdA52NK5VlPPqpMshgi0Vi-DgMCgZywdCAA

**Comment by dquang-tran** [comment]
Hmm, yeah I don't see this error anymore for some reason. Thanks!
