### ISSUE TITLE
Unable to establish covariance with readonly properties

### ISSUE THREAD

**Issue by mike-marcacci** [facebook/flow#6247]
[Demo](https://flow.org/try/#0C4TwDgpgBA4hB2EBOBDANlAvFA3gKCigGoAzAezIC4oB+AZ2CQEt4BzAGgOICMUlr6jFqzwBfANx48oSFADKkAMZMSTRVlxdSFag2ZtOhIr35Q9wsZLwkArvEXAmZeFAAmZOWQC2EYAAthBQhlVUUACn9haiCQtQBKTUJFZzoyNAgAOjQyVgiAtgzyMmIoAHIzPzIbNFcyksiCkzjJUSlk+AYoBtZqOERUDGx8QiLqUsi6UsMoEzGAdzIkAGtSyykVKDzhQoooAEJMbHhqjAAyU6781gyTfcOoY7Q0BOG3D29fK5iVNS22ZrEQA)

```ts
type General = {
  +foo: ?string,
  +bar: ?string
};

type Specific = {
  +foo: string,
  +bar: string
};

function doSomethingSpecific(thing: Specific) {
  console.log(thing.foo + ' should ' + thing.bar);
}

const thing: General = {
  foo: 'this',
  bar: 'work'
};

if (thing.foo !== null && thing.bar !== null) {
  doSomethingSpecific(thing);
}
```
Because `thing.foo` and `thing.bar` have been asserted to be not null, flow can guarantee that `thing` is `Specific`.

Instead, this produces an error with an unclear way to resolve without creating a new object (which would be problematic in my case).

```
21:   doSomethingSpecific(thing);
                          ^ Cannot call `doSomethingSpecific` with `thing` bound to `thing` because null or undefined [1] is incompatible with string [2] in property `bar`.
References:
3:   +bar: ?string           ^ [1]
8:   +bar: string           ^ [2]
21:   doSomethingSpecific(thing);
                          ^ Cannot call `doSomethingSpecific` with `thing` bound to `thing` because null or undefined [1] is incompatible with string [2] in property `foo`.
References:
2:   +foo: ?string,
           ^ [1]
7:   +foo: string,
           ^ [2]
```

**Comment by SamChou19815** [comment]
Expected limitation, since we have no way to refine one object type to another. Instead, we can only narrow unions of object type.
