### ISSUE TITLE
Missing `$Shape` in the utility documentation

### ISSUE THREAD

**Issue by mloureiro** [facebook/flow#6248]
Hey guys

The only reference i found to `$Shape` in the documentation is [this one](https://flow.org/en/docs/types/casting/#toc-type-checking-through-type-assertions) which is inside of the last example, it is not even mentioned, but it is used.

I would expect this to be defined in the in the [utilities page](https://flow.org/en/docs/types/utilities/).

(didn't make a PR since I'm not actually sure where is the documentation repo)

**Comment by apsavin** [comment]
[There are](https://github.com/facebook/flow/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+%24Shape) some PRs already.

**Comment by mloureiro** [comment]
shoot, I should have taken a look to the PRs
thanks for pointing that out @apsavin (although all of them missing the CLA signing)

**Comment by apsavin** [comment]
> although all of them missing the CLA signing

None of them

**Comment by mloureiro** [comment]
> None of them

Ah, you're right, is the other way around 👍 


Closing since this is being done in: 
#2464
#3967
#5251
#5706
