### ISSUE TITLE
Flow ignore the check function from a 3rd party library

### ISSUE THREAD

**Issue by Albert-Gao** [facebook/flow#6253]
I use [is.js](https://is.js.org/)

And I use it to check whether a property is there or not:

```javascript
import is from 'is_js';

type Schema = {
  collectValues?: {[string]: string}
};

// schema: Schema
if (
    is.propertyDefined(schema, "collectValues") &&
    is.propertyDefined(schema.collectValues, reliedFieldName)
  ) {
      const a = schema.collectValues[reliedFieldName];
}
```

The error is:

```bash
Cannot get schema.collectValues[reliedFieldName] because an indexer property is missing in undefined [1].

[1]  28│   collectValues?: {[string]: string},
```

It will work if I mark that `collectValues` with non-optional, however, it's an optional. The error is simple because flow doesn't know the property is already checked.

How to make this work?

**Comment by idiostruct** [comment]
`is.propertyDefined` checks for presence, and not for undefined (similar to https://github.com/facebook/flow/issues/6250):

```js
var is = require("is_js");

is.propertyDefined({}, "collectValues"); //=> false
is.propertyDefined({ collectValues: {} }, "collectValues"); //=> true
is.propertyDefined({ collectValues: undefined }, "collectValues"); //=> true
```

You'll want to ensure `schema.collectValues` is not undefined before accessing its properties.

**Comment by Albert-Gao** [comment]
Thanks!!!

Yes, I missed that part, after adding `allSchema.collectValues != null`, everything works like a charm.

One more problem. I tried to extract this checking logic to an isolated function like this:

```javascript
function isCollectValuesThere(
  schema: Schema,
  reliedFieldName: string
): boolean %checks {
  return schema.collectValues != null &&
    allSchema.collectValues.reliedFieldName != null
}
```

Then use it like:

```javascript
if (
    isCollectValuesThere(schema)
  ) {
      result = getNestedValue(
        schema.collectValues[reliedFieldName],
        schema
      )
  }
```

It reports an error for `reliedFieldName` in `schema.collectValues[reliedFieldName],`

```bash
Cannot get schema.collectValues[reliedFieldName] because an indexer property is missing in undefined [1].
```

I already marked that `isCollectValuesThere` as `%checks`, what am I missing here?

**Comment by idiostruct** [comment]
Flow has no way of knowing if `isCollectValuesThere` mutates `schema`; therefore, the refinement is invalidated. Here's a workaround : [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVw2bAAwJYDOA+gFYE5gC2cAxgNYB0GaNcAdgQC5iFgC8YAN6owYAA4AnOGICmEzgE8AIjKh42MgCYAuMAAo4AIxIyanADRg6MhQEp+APjBGTZhgAsAhgQDyCNgAKUrLyCnrWdqgAvgDc6FAArmxmeOw8BCpQAIJsmgBycJx5CTAwBsamnLoglhG6XBLqAOa2uoZwcDAynmxgAKQ07qZ0BEIiYBIynAkSvS6VYACEAmwlMGAAZBvOFWYA2hEAuksra9HoirJgAMqDMpSe-GOirKWVAGqeMAkyBAD8ukEewazUO9U4jTYTSi0TiqFYHG4kxgeC0ADFUTB8p5KDIngAiKAdfFwhFcMAEO4PLK6W5DB5PYQvTpdMyfb6-QHjUREuC6fEAWXYEXx4xhMNQeCg+kImRy+UKxVKekp9M8WQYr1ZnHZPwIlmRqM0GJkWLyOJktnsTLAZKRvxK3AEqvu6s1LI+Xz1e0N6Mx2NxhziErtFKpngAQrTw4zYugpTKMqp5QUimsVeGI+63myvb8DaajSazRarc9bexyZMCI6ni6HlmtZ6OQQfYW-aaAzIg9EgA).

Note that the workaround is for illustration purposes and not necessarily a _final_ solution.

**Comment by Albert-Gao** [comment]
Thanks, I kind of seeing the pattern here. Our checking statement needs to match the flow's desire somehow. right?

**Comment by stereobooster** [comment]
Check out https://github.com/jamiebuilds/sarcastic, it is compatible with Flow
