### ISSUE TITLE
Support private methods

### ISSUE THREAD

**Issue by vjpr** [facebook/flow#6254]
https://github.com/tc39/proposal-private-methods

**Comment by hadnet** [comment]
Any update about this? When trying to use private methods ( #myFunction(){} ) I got this warning: Classes may not have private methods. I'm using Flow 0.93.

**Comment by jml6m** [comment]
I'm interested in this feature as well. I have classes that extend other classes and using the typical ES6 approaches to "private" attributes/methods (like #, WeakMap, Symbols, etc.) just don't work out in my architecture. If flowtype handled this itself, it would be much easier.

**Comment by sepehr** [comment]
Would love to see it live.

**Comment by goodmind** [comment]
@jml6m I think TypeScript better suits your use case, Flow wouldn't add protected, because it isn't standard js

**Comment by oonsamyi** [comment]
@goodmind Flow supports some features even from stage 1.
E.g. [Optional Chaining](https://github.com/facebook/flow/releases/tag/v0.71.0).

Why should private methods be exclusion?

**Comment by sakarit** [comment]
> @jml6m I think TypeScript better suits your use case, Flow wouldn't add protected, because it isn't standard js

Private methods is already in stage 3 so it will be standard soon.

**Comment by Ephys** [comment]
> Private methods is already in stage 3 so it will be standard soon.

They meant that "protected" class fields isn't standard JS :)

**Comment by nnmrts** [comment]
Any news on this? Why is every second issue in this repository dead since end 2019? Why is there no global setting to suppress specific errors?

**Comment by sepehr** [comment]
This is the main reason we're trying to migrate to typescript. I wish I could help here.

**Comment by hadnet** [comment]
So  jul 30 2020. Any news on this issue?

**Comment by XedinUnknown** [comment]
Yes, please! Since private properties already work, it should be trivial to add support for private methods as well. And this is already Stage 3 standard, as is mentioned above, so there's no reason to not do it.

**Comment by XedinUnknown** [comment]
Meanwhile, one way to go around it is to simply use interfaces.

```
interface Greeter
{
	getGreeting(): string
}

class MyGreeter implements Greeter
{
	getGreeting(): string
	{
		return 'Hello, ' + this.getName() + '!'
	}

	#getName(): string
	{
		return 'World'
	}
}

function greet(greeter: Greeter): void
{
    console.log(greeter.greet());
}

let greeter = new MyGreeter()
greet(greeter)
```

The function `greet()` doesn't know that `greeter` is an instance of `MyGreeter`; all it knows is that it's a `Greeter`. This is DIP, and I do this anyway in all my code.

**Comment by mischnic** [comment]
Another workaround is treating it like a property (assigning it) and then using `.call`
```js
class Foo {
    #priv: (number) => string;

    constructor(){
        this.#priv = (a) => String(a);
    }

    run(){
        console.log(this.#priv.call(this, 123));
    }
}
```
