### ISSUE TITLE
Support logical assignment operator

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#6259]
https://github.com/babel/babel/tree/master/packages/babel-plugin-proposal-logical-assignment-operators
https://github.com/tc39-transfer/proposal-logical-assignment

```
a ||= b

// equivalent to
if (!a) {
  a = b
}
```

**Comment by Hypnosphi** [comment]
It's Stage 3 now

**Comment by romanlex** [comment]
it's stage 4 now

**Comment by SamChou19815** [comment]
It's supported for a while now
