### ISSUE TITLE
Cannot call clients.forEach because property forEach is missing in $Iterator [1].

### ISSUE THREAD

**Issue by adityapunjani** [facebook/flow#6262]
https://github.com/facebook/flow/blob/v0.70.0/lib/serviceworkers.js#L56 
I think should be `Promise<Array<Client>> `

As per MDN (which refers to the spec) https://developer.mozilla.org/en-US/docs/Web/API/Clients/matchAll returns `A Promise that resolves to an array of Client objects. In Chrome 46/Firefox 54 and later, this method returns clients in most recently focused order, correct as per spec.`

**Comment by mrkev** [comment]
True; can confirm it's also defined as an array on the w3 spec: https://www.w3.org/TR/service-workers-1/#clients-getall

Feel free to make a PR and ping me on it 👍
