### ISSUE TITLE
Cannot cast type with a union in generic type argument to a type with a more inclusive union in its generic type argument.

### ISSUE THREAD

**Issue by Awpteamoose** [facebook/flow#6263]
Sorry if I butchered the title, not sure how to concisely describe the issue.

This is obviously a contrived example, but I have something very similar in my codebase.

```javascript
type ATypes = "A1" | "A2" | "A3" | "A4" | "A5";
type BTypes = "B1" | "B2" | "B3" | "B4" | "B5";

type A<Type: ATypes > = {|
	+type: Type,
|};

type B<Type: BTypes> = {|
	+type: Type,
|};

type A1 = A<"A1">;
type A2 = A<"A2">;
type A3 = A<"A3">;
type AnyA = A1 | A2 | A3;

type B1 = B<"B1">;
type B2 = B<"B2">;
type B3 = B<"B3">;
type AnyB = B1 | B2 | B3;

type Container<A: AnyA, B: AnyB> = {|
	+a: A,
	+b: B,
|};

const foo: AnyA = (({}: any): A1 | A2);
const bar: Container<AnyA, AnyB> = (({}: any): Container<A1 | A2, AnyB>);
```
[flow.org/try](https://flow.org/try/#0C4TwDgpgBAggKuCBnKBeKAiGBGDUA+mMATHoVgMxlEAs1WArBgNwBQokUAQgpCuhi64CmLqRGCqErnWlM27RLAA8vCAC5YalAD40UAN75WASADUHDVDUAaVvgC+Cy91WJNPREj3ojpi+7WiHaOzko4+jDKWLg6bC4kkdEkGHGKnDAUSZSp8eEAdiAwkdgiiYSZYZxC+lzRQrnp0GK19aRpLlxZ6HWSjQmFXLWlhC2jFFXQAMIA9vnAAIYAlvkQAE7KMJowhTA23NuDPobG5gvbduYARh4hTqysAMZzSMBQAGYzM4dF+gAUfwMDk0C0KAEptiNYMQwWxnvlXlArgs1ppZvNlqsNjsivscVxjgCgSDwWi5osVutNlCSHijrCgA)
```
28: const bar: Container<AnyA, AnyB> = (({}: any): Container<A1 | A2, AnyB>);
                                         ^ Cannot assign object literal to `bar` because in type argument `A` [1]: Either string literal `A3` [2] is incompatible with string literal `A1` [3] in property `type`. Or string literal `A3` [2] is incompatible with string literal `A2` [4] in property `type`.
References:
22: type Container<A: AnyA, B: AnyB> = {|
                   ^ [1]
14: type A3 = A<"A3">;
                ^ [2]
12: type A1 = A<"A1">;
                ^ [3]
13: type A2 = A<"A2">;
                ^ [4]
```

**Comment by Awpteamoose** [comment]
Seems to be an even simpler example:
```javascript
type A = "a";
type B = "b";

type T<T1, T2> = {| t1: T1, t2: T2 |};

type Wide = T<A | B, B>;
type Narrow = T<A, B>;

const ab: Narrow = { t1: "a", t2: "b" };
const abb1: Wide = ab; // Cannot assign `ab` to `abb1` because string literal `a` [1] is incompatible with string literal `b` [2] in type argument `T1` [3]
const abb2: Wide = { t1: "a", t2: "b" }; // ok!
```
[flow.org/try](https://flow.org/try/#0C4TwDgpgBAglC8UBEBDJBuAUKSUBCCyARhptuNACoA8lAjADRSUBMAfIQN4A+UwdALmaM+LIayjcAvlnK4A6gEsAJtEQ04vPEzxssOaADkUAJxMB7AO6ENOvWQDG5gHYBnYFBREhxs1a58gshoTMBixEhQMphObh5eREFKqoRe6FAA9BlQAMIozs7m8a6uigDmzlAABl5VfObVCXR1RBAOKACurtDuJorOZVAANorAECYoQ411ANp0ALpQiq5Lzk4AtmAowIpEQ9CWowAWUL39gyNjE1NVRLMsi-18FJ4mZR3rEM4eVfSzAMzzGIudyeIhEcLJNRQTiBISoJChcJIEhRdJZKDmADWAEIgA)

**Comment by jcready** [comment]
If you define your type as the following the error goes away:

```js
type T<+T1, +T2> = {| +t1: T1, +t2: T2 |};
```

**Comment by Awpteamoose** [comment]
Aha, gotcha, thanks!
