### ISSUE TITLE
property cells is missing in HTMLTableRowElement

### ISSUE THREAD

**Issue by gabrielrussoc** [facebook/flow#6264]
The following piece of code 
```
function contestDataFrom(row: HTMLTableRowElement): Contest {
  const cells: HTMLCollection<HTMLTableCellElement> = row.cells;
...
```
is giving me the following error
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/judges/codechef/getContests.js:7:59

Cannot get row.cells because property cells is missing in HTMLTableRowElement [1].

      4│ import type { State } from '../../types';
      5│
 [1]  6│ function contestDataFrom(row: HTMLTableRowElement): Contest {
      7│   const cells: HTMLCollection<HTMLTableCellElement> = row.cells;
...
```

It is a similar issue to #2170, which has been solved by #2226. From my understanding, the declaration is missing on https://github.com/facebook/flow/blob/master/lib/dom.js

I am using https://developer.mozilla.org/en-US/docs/Web/API/HTMLTableRowElement for reference.

I am willing to send a PR, I just wanted to be sure first.

**Comment by mrkev** [comment]
Yup, definitely missing. Feel free to PR!
