### ISSUE TITLE
When function return class, there is a scope Error. please see the demo link

### ISSUE THREAD

**Issue by wszgxa** [facebook/flow#6267]
It's a little hard to explain, please see the test link:

## Try Flow link:
https://flow.org/try/#0C4TwDgpgBAKhDOwoF4oAoCUKB8VECcBLAOwHMAocgYwHtjEoBDFdYBYAMQFdirhC6ALigB+OIizJcAb3JQohAGZoAhG0Tde-Ollnz56zjz4DiLTDigByeI1u2rcqAF8n+CMC74zVADZ34WBgoPX1DAEliYgh8TRM6TFD9KHdPbyhDOO1iTHIASFd5V2cgA

I have changed the testFunction to not equal null and undefined. But it still throws the error in the class method.

**Comment by apsavin** [comment]
[Workaround](https://flow.org/try/#0C4TwDgpgBAKhDOwoF4oAoCUKB8VECcBLAOwHMAocgYwHtjEoBDFdYBYALigH45EtkuAN7koUWvSRtEAMQCuxKsEJ0W0pAB8N6TDigByeIyNH9GANyio+CMDn5i4gDbH4sGFBFix6gJLFiCHx5RWU6TC9vMRs7Byh1EKUVYkxyAEgAXyssjKA)

If you declare a constant like in the example above it will contain a function for sure.

**Comment by wszgxa** [comment]
@apsavin 
Yep, add another variable will not throw the error. 

If we need to add a variable to solve flow error, it's a little tricky.

Thanks anyway.

**Comment by apsavin** [comment]
> it's a little tricky.

Agree.

But I'd recommend to turn on [experimental.const_params](https://flow.org/en/docs/config/options/#toc-experimental-const-params-boolean) option anyway - it makes life easier and it's a [good practice](https://eslint.org/docs/rules/no-param-reassign) also (imho).

**Comment by wszgxa** [comment]
I will raise this in our team. thank you again.

**Comment by SamChou19815** [comment]
This seems to work as expected
