### ISSUE TITLE
Default Parameter refinement not working

### ISSUE THREAD

**Issue by marudor** [facebook/flow#6268]
Reproduction case:
https://flow.org/try/#0C4TwDgpgBAglC8UDeAoKUBCB+AXMtUAkAPZjACWxAdgIYA2uUVArgLYBGEATgDQEC+KQSgBmzKgGMK1KGMkAKJFFLTadBFACMUfngAkABS6luoACrgIAHhg8oAcgz2AfBqT8AlMmGhImNwQweKjo6CqUaowsHNx86ILCclIRsuISAEyKymQR9BraulCGxpBc5pZWGHb2MC5QAD4ABQBuxOQAJm6e3kA

As you can see flow incorrectly doesn't honor the default parameter and still complains about a undefined. Although the parameter can no longer be undefined. (Type only allows undefined, not null as I used ?: before)
I've included an alternate typing for the same. Both do not work out as expected.

**Comment by apsavin** [comment]
Seems like a duplicate of #5957

**Comment by marudor** [comment]
Correct. Didn't find it looking through. Thanks.
Closing in favor of #5957
