### ISSUE TITLE
Error infering the correct type in constructor with mixed types

### ISSUE THREAD

**Issue by godzsa** [facebook/flow#6269]
I am trying to create a multi purpose constructor for a class, but Flow inherits the variable types incorrectly in the `if`:

```
class Rectangle {
    at: Point
    size: Size

        constructor (a: Point | number, b: Size | number, width: ?number, height: ?number) {
        if (typeof a === Point && typeof b === Size) {
            this.at = a
            this.size = b
        } else if (width != null && height != null) {
            this.at = new Point(a, b)
            this.size = new Size(width, height)
        } else {
            throw Error("Invalid constructor parameters")
        }
    }
}

```

At line 8 where there is `this.size = b` the `b` variable should always be of type Size, since it is checked, but I get `Cannot assign b to this.size because number [1] is incompatible with Size [2].` error.

Also another worrying thing is when I modify the code and delete the mixed type and just keep `b: Size` in the constructor parameters instead of `b:Size | number` the code compiles just fine, which is a problem, since at line 10 there is `this.at = new Point(a,b)` where `Point` constructor accepts two `numbers` not a `number` and a `Size`

**Comment by apsavin** [comment]
Could you please provide a link to flow.org/try ?

**Comment by apsavin** [comment]
[Well](https://flow.org/try/#0MYGwhgzhAEAKD2BLAdgF2gbwFDV9AHgFzICuAtgEYCmATjngJ7HnV327DzISo0nCp4NaAAoi0UpVoAaaEwktaASkzs8uVAAtEEAHT5oAXgJr1WnboZG5agL5Z7WUJBgBlRAC8qq9QHdEACZahApSdOqaVIgA5pqoIZKsWGqc3Lz8gsIi-kGaCYo0spExcflhKtjqZtp6OVrWdZqmeOZ6xbHoxu1xdg7JzlDQAEpUAmDI0SDelXhg8XBIaGoQnlQh7l7J6qk8fAJComAhCCjoAD6hrLIU66vQF4ky0I0hAPyPhdDd8+8FFc24RAAM0O0BQPHGwCo8BBJzQ0AAZAjoBQwWlIdCQRsqP8qnjoK1dHNrGAAVVCSsvNYKGTbNAqCAIN5gaJGtAAITGUggECI5HfDlckg8vkEhgAB0x0DARkMxgA5B95aLUBKpai5Qqlbj8dULMSuVRfAtTiIwNclGS9XpKd5DcbsdlAloilEOpbdXSGUyfLqWpoaPBjQBRGiBmgiABEAElkAA3MAgQLQHbpfbCcVgGhgMhUVC0CCRj34+zqez2IA)

**Comment by godzsa** [comment]
Oh thanks! :) I missed that one
