### ISSUE TITLE
Wrong place of error occurrence for React state array

### ISSUE THREAD

**Issue by sarneeh** [facebook/flow#6271]
This is specific to Flow + React setup.

Consider this example:

```
import React, { Component } from "react";

type MyObject = {|
    value: number
|}

type State = {|
    items: Array<MyObject>
|};

export default class Test extends Component<{}, State> {
    state = {
        items: []
    };

    render() {
        return <ul>
            {this.state.items.map(({ prop }) => 
                <li>{ prop }</li>
            )}
        </ul>;
    }
}
```

As you may notice, the problem is in the `map` function of `items` array property in the `state` - the `prop` property does not exist in `MyObject` type.

What I'd expect is to see the error in the `map` function part - `({ prop }) =>` and not like it actually does:

```
Error src/components/Test.js:13:16

Cannot extend Component [1] with Test because property prop is missing in MyObject [2] in array element of property
state.items.

 [2]  8│     items: Array<MyObject>
      9│ |};
     10│
 [1] 11│ export default class Test extends Component<{}, State> {
     12│     state = {
     13│         items: [] // Error is here
     14│     };
     15│
     16│     render() {
     17│         return <ul>
     18│             {this.state.items.map(({ prop }) => // Where I'd expect the error to appear
     19│                 <li>{ prop }</li>
     20│             )}
     21│         </ul>;
     22│     }
     23│ }
     24│
```

It points on the `items` property value of the default state declaration.

Is it a bug, or is it a desired behaviour? If yes, could someone please explain me why?

**Comment by apsavin** [comment]
> why?

Because flow works with types' graph, not with AST. I'm not sure that we'll have perfect error messages, but I can see that the flow team improves it from release to release.

**Comment by sarneeh** [comment]
@apsavin Thanks again for the explanation :) Is there any resource where I can learn more about how Flow works internally?

**Comment by mrkev** [comment]
This video is pretty good imo: https://www.youtube.com/watch?v=VEaDsKyDxkY

The error is a little cryptic, but I think the desired behaviour is there: it mentions `property prop is missing in MyObject [2] in array element of property state.items`. It does give a bit too much context which in this case is annoying, but in general I'd say giving too much info is better than not enough.

Closing this issue for now. "Improving errors" is always a goal 😅
