### ISSUE TITLE
Spreading allows creation of invalid type

### ISSUE THREAD

**Issue by RichieAHB** [facebook/flow#6272]
How is `b` allowed to be a `B` here when the `test` property may not (and, in this case, does not) exist? This maybe a duplicate issue but I can't find something exactly the same. I see other issue with flow complaining _more_ when spreading but not complaining _less_.

Thanks

```js
type A = {
	test?: string
}

type B = {
	test: string
}

const a: A = {};
const b: B = { ...a };
```

https://flow.org/try/#0C4TwDgpgBAglC8UDeAoAkMCBnYB+AXFDgE4CWAdgOYoC+KKokUAQgsupjoSRdXSgGMA9uRxQAhoTiIkNANyCRYgEaFWMqADpt4qPJRA

**Comment by Awpteamoose** [comment]
If you specify A as exact - it goes away. [flow.org/try](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUASGBAzsA-AFxR4BOAlgHYDmaKAvmmqJFAEILKbZ7FlW1GaAMYB7SnigBDYnERJ6AbhHjJAI2Id5UAHR6pUJWiA)

**Comment by RichieAHB** [comment]
@Awpteamoose I'm not sure that should be a prerequisite for avoiding runtime errors.

**Comment by mrkev** [comment]
This does seem like a bug to me; this assignment should be invalid

**Comment by Brianzchen** [comment]
Assignment is now invalid as of current version, tested 0.135.0
