### ISSUE TITLE
Cannot assign a normal type to a Maybe type

### ISSUE THREAD

**Issue by lukasbalaz** [facebook/flow#6273]
Why this works:
```js
const var1: number = 1
const var2: ?number = var1
```
but this doesn't ? :
```js
const arr1: Array<number> = [1, 2, 3]
const arr2: Array<?number> = arr1
```
Error:
```
Cannot assign `arr1` to `arr2` because number is incompatible with null or undefined in array element.
```
Am I missing something ? It should be always possible to assing `type` to `?type`, shouldn't it ?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gCGATsQIwBcYAgqYQJ4A8WArgLYBGApsQHxgBeMAG0yAGjAAmCQGYAuhmz4ipSVVrEGjAPytOPfkJLlUi3AQBuJSmD3digsGTPKrxNWF3t7jt2SA

**Comment by TrySound** [comment]
You cannot assign invariant array to each other. Use $ReadOnlyArray

https://flow.org/try/#0MYewdgzgLgBAhgJwQRgFwwCQCUCmcAmA8mADYCeAgknGQDxgCuAtgEY4IB8MAvDANrIANDABMwgMwBdAFChIsRAhHpseIqUrU6Afkat2XXouRA

**Comment by lukasbalaz** [comment]
Oh, I was actually passing the array to a function, completely forgot that I could mutate it in there if I wanted. Makes sense now, thank you :)
