### ISSUE TITLE
getting use-def information

### ISSUE THREAD

**Issue by lur2c** [facebook/flow#6276]
Hi, I have a question which is not a bug of Flow itself.

I'd like to use flow's type information to do additional analysis work and need to access the use-def chain of a program. I'm wondering if it's readily available in the analyzer.

If so, my next question is what is the best approach to start with and from where if I'm to write a fixed-point style analysis that uses the use-def information.

Thanks very much.

**Comment by SamChou19815** [comment]
We don't plan to expose it. eslint has better utils.
