### ISSUE TITLE
Is inheritance in Flow broken?

### ISSUE THREAD

**Issue by ClemensLey** [facebook/flow#6277]
Apologies if this is a duplicate. Consider a situation where you have a class B extending from class A. You create an object of type B and call a method fooA defined in A and then a method fooB defined in B.

    class A {
      fooA () {
        console.log('fooA called')
        return this
      }
    }

    class B extends A {
      fooB () {
        console.log('fooB called')
        return this
      }
    }

    new B().fooA().fooB()

When run the code it logs the following as expected

    fooA called
    fooB called

So Javascript understands that `new B().fooA()` is an object of type B. However Flow gives me the following error message:

    Cannot call new B().fooA().fooB because property fooB is missing in A

What to do? I'm interested in a solution where I do not need to change the parent class A because it is defined in an npm package. I can change B though.

**Comment by ClemensLey** [comment]
Thanks for your input. This would be an ideal solution if I could change A but I cannot because A is in an npm package. I am using flow-typed to specify the type of the function fooA there. If I change my flow-typed file to

    declare class A {
      fooA: () => this
    }

I still get an error message

    Cannot cast `new B().fooA()` to `B` because `A` is incompatible with `B`.

The one solution I know of is to declare `fooA: () => Object` but that of course does not provide type safety. Any help is greatly apprechiated.

**Comment by oriSomething** [comment]
I think it's still an issue. Because `this` is dynamic. We don't need to manually add annotations
