### ISSUE TITLE
covariant definition doesn't work in an array

### ISSUE THREAD

**Issue by bmsuseluda** [facebook/flow#6281]
In the following example i've got 2 'versions' of a type. The initial type has an optional string name and the advanced type has a required string name:
[covariant without array](https://flow.org/try/#0C4TwDgpgBAIhBmBLAdo4iD2yoF4oG8AoKKAYwwFswAbCYCAEwC4oAjDDWgQ2QBpioAamRcKEAPwsAzsABOKAOb8AvgG5ChUJFgIUaTMgDqaABYAlCAEcArolmMAcqOh4iJclVr1mbDtz4CImLScooq6oTkyDJQDBgAypR0Joq4UAAUDLqo6FgscEg5BgCUuAB8BAJRUpwQAHTUGAqZ2fpYdR40dIzF6moa1cCxCUnAKcgK8ZCkiFzUaS2Fbcj5rblGphY2do7OpTgVbsOJYmOKi3rrvYRqQA)

I'm using this to reflect that the data in a process will be more completed from step to step. In step 1 the initial type is correct.  On step 2 the user sets the name and so in step 3 the advanced type with the required name is more specific than the initial type.

So far, so good.

Now i'm trying to use this principle with an array, but flow doesn't understand what i'm trying to do:
[covariant with array](https://flow.org/try/#0C4TwDgpgBAIhBmBLAdo4iD2yoF4oG8AoKKAYwwFswAbCYCAEwC4oAjDDWgQ2QBpioAamRcKEAPwsAzsABOKAOb8AvgG5ChUJFgIUaTMgDqaABYAlCAEcArolmMAcqOh4iJclVr1mbDtz4CImLScooq6oTkyDJQDBgAypR0Joq4UAAUDLqo6FhSLHBIOQYA2gC6AJS4AHwEAojwGVlF+nkAdLTICsAmULUADFVuUACQUVKcEB0YCpnZrdEl-WVtHjR0jBXqJMqEahrjwLEJST2K8ZCkiFzUaXMtudEF84-GPRY2do7O5VU4tcM4okxGcuvc9I8pFs9qogA)

What am i doing wrong? Thank you for your help.

**Comment by TrySound** [comment]
Use $ReadOnlyArray.

**Comment by bmsuseluda** [comment]
Thanks for your fast reply. In my projects im working with immutable objects and arrays only. Did i understand your post correctly, that i have to use this utility type for all my immutable arrays?

**Comment by TrySound** [comment]
Yes, covariant arrays makes everything simpler. There is also $ReadOnly for objects, but objects are less problematic here.
