### ISSUE TITLE
wrong type while perform Array.isArray check on tulpe

### ISSUE THREAD

**Issue by ValeryVS** [facebook/flow#6287]
https://flow.org/try/#0GYVwdgxgLglg9mABACwKYEMAmB5ATgSU1TFigE8AeAFQD4AKAN3QBsAuRAbSoBpEB+ALYwAHqky9BIsRKGjMAXUQAfRFQCU7KogDeAKEQHEuVFBC4kAQVy50ZAHQwAzlZtlGLNf0RNmHAAyK7D4A3LoAvrq6EAiOUIiOyHAgzJgAQqgAogIADuRBcDCYiAC8KBg4BEQkMOR0HOBEwDBg0ogAjLwA5Og9nbxgyczyaqHRYLHxiclpqAByIAIARqi47ANLKyVlWHiExKRuHB2IAEzDwYgA9JeIiyBxNYhOiOvLuBzyukA
```javascript
function headOrIdentity<T>(val: [T, ?mixed, ?mixed, ?mixed] | T): T {
    return Array.isArray(val) ? val[0] : val;
}

const shouldBeEmpty: void = headOrIdentity([undefined, 1, 'aaa', null]);
const shouldBeNumber: number = headOrIdentity([1, 2]); // but it is number[]
```

**Comment by ValeryVS** [comment]
Properly typed `headOrIdentity` function.

https://flow.org/try/#0GYVwdgxgLglg9mABACwKYEMAmB5ATgSU1TFigE8AeAFQD4AKAN3QBsAuRAbSoBpEBbGAA9UmXgOGj+QkQF1EAH048pEsdMxzFXNRM2IAgrlzpKtBYioBKdlUQBvAFCJniXKighcSQ8bIA6GABnHxNGFktEAH5EJmYOAAY5dliAbgcAXwcsiARAqERA5DgQZkwAIVQANTgYTGSazEQAXhQMHAIiEhhyOg5wImAYMBFeAEZeAHJ0aYneMBLmGUs0nLA8gqKS8tQAORA+ACNUXHZ5w+Pm1qw8QmJSMl7xxCmZuYWlldz8wuLSioBlKC4IYAc3YeWBYBBlzQ1w6d26Dw4L3Qs0Q82Yi2WDlW6x+Wwqe0xpwWMLaN06916GKxnzW302f1QAFE+AAHcjsVDs8hkuG3Lo9DgfHFfdFwABKqECcGYDBEVDIbNQ7AOcFlGCQigYDXMZyOuHMENBetJLVh7QFVI4QJAqF4-VQg2GkieKLRNJFQA

**Comment by ValeryVS** [comment]
In the first example `headOrIdentity([1, 2])` should, interpret tulpe as Array in Array.isArray check or show error about incompatible argument.

**Comment by SamChou19815** [comment]
Expected since T can be instantiated to an array type
