### ISSUE TITLE
Propose: spread tulpe values

### ISSUE THREAD

**Issue by ValeryVS** [facebook/flow#6288]
Current

```javascript
function headOrIdentity<T>(val: [T, mixed, mixed, mixed] | [T, mixed, mixed] | [T, mixed] | Array<T> | T): T {
    return Array.isArray(val) ? val[0] : val;
}
```

https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwAsQpgB5GASVFWwwE8AKANyggC54mctgBKDrjwDcAKFCRYCFOmx5CxMpWq06AHgAqAPmasOAbXUAaeAFssADxDBjZy9dMWrAXXgAfeAZuP7t5249GDnYu7gCCMDBQalr+6vzw6iLSmLj4RCTkVCA0WPQ6ELzwAN4i8GXwcBjIMPjhkXQAdFgAznVR+byl5d0A-JysegAMTl3dZQKsogC+IrNgeM0Y8M0EOMgQwABCIABq3MAC+-AAvPIZStkqDHpooIhYqFbGAIzGAORQn2-GqOsQTrxRPNUItlqt1lsQAA5ZAmABGIBgHF+8MRJzOiiyOTyele8A+Xx+fwBQIWSxWaw22wAyhgYA8AOYcRb01AM9HpTHKXKMPQEqDfeC-CD-QEiYGgikQ7YwkXIv4chSZbk44Wi0kg8ngqkgACiJgADvQOCBDfRFecsVc9CTxWShTgAEogZo4CBMKzqOgGkAcOE4N3EfDuQTAfwohEwfwsxnhhWnTnKy486505AgYy3ED3R72PH8wVq21AA

With spread operator

```javascript
function headOrIdentity<T>(val: [T, ...mixed] | T): T {
    return Array.isArray(val) ? val[0] : val;
}
```

It could be useful with optional params of Tulpe.

**Comment by SamChou19815** [comment]
Tuple spread is now supported
