### ISSUE TITLE
Vague error description

### ISSUE THREAD

**Issue by avalanche1** [facebook/flow#6289]
```
const foo: Array<number> = [1,2].map((n) => {
	let  bar = n * 2
	bar**n
});
```
Obviously, this function returns `undefined`. But the flow error is really vague: `cannot assign 'map' to 'foo' because undefined[1] is incompatible with number[2] in array element`
It would be much more helpful if flow reported instead that `map` function needs to have an explicit return.

**Comment by SamChou19815** [comment]
The errors should be better now.
