### ISSUE TITLE
Value of type T won't flow into value of type ?T when using object spread

### ISSUE THREAD

**Issue by almost** [facebook/flow#629]
The following doesn't type check in Flow 0.3.1:

```
var a = {
  x: (null:?string)
};

a = {
  ...a,
  x: ""
};
```

I've used `string` as an example here but it happens with any type. It can be made to work by casting the object to a nullable:

```
var a = {
  x: (null:?string)
};

var b:?string = ""; 

a = {
  ...a,
  x: b
};
```

Doesn't seem to happen when doing direct assignment (eg `a.x = ""` works fine). I'm pretty sure this is a bug, apologies if it's a duplicate (I wasn't sure what to search for)

**Comment by jeffmo** [comment]
Definitely an odd bug...probably related to the spread of `x` onto itself I'm guessing. 
Thanks for the report!

**Comment by samwgoldman** [comment]
This no longer errors for me. I tried to construct some similar cases, and Flow seems to be handling stuff correctly now. Thanks for the report!
