### ISSUE TITLE
[Bug][Feature?] Use generic type as key in object

### ISSUE THREAD

**Issue by Rohit-L** [facebook/flow#6295]
Hi, Is there a way to use a generic as a key in an object. What I want to be able to do is:

```
/* @flow */

type Test<T, F> = {
	T: 'WORLD',
  	F: 'BAR',
}

const HELLO: 'HELLO' = 'HELLO';
const FOO: 'FOO' = 'FOO';

const test: Test<typeof HELLO, typeof FOO> = {
	HELLO: 'WORLD',
  	FOO: 'BAR',
}
```

But this doesn't work because flow will infer to use the literals `T` and `F` in the return type of `Test<>`.

Since flow explains that generics are "variables" in the type world, the next thing I tried is:

```
/* @flow */

type Test<T, F> = {
	[T]: 'WORLD',
  	[F]: 'BAR',
}

const HELLO: 'HELLO' = 'HELLO';
const FOO: 'FOO' = 'FOO';

const test: Test<typeof HELLO, typeof FOO> = {
	HELLO: 'WORLD',
  	FOO: 'BAR',
}
      
```

since that is how one would use a variable as a key in ES6. The problem in this case is that flow treats this syntax as an "indexer" and multiple indexers are not supported (flow thinks this is a mapping now).

Is there any way to achieve what I want here?

The use-case I am going for is an HOC in React that allows the child component (wrapped component) to choose the names for the injected props like so:

```
const openModalPropName: 'MyComponentOpenModal' = 'MyComponentOpenModal';
export default WithModalHOC(MyComponent, { openModalPropName });
```

The hoc then uses that prop name for the injected prop, which is a function that when called, opens a modal. This is useful if we need multiple modals that could be opened.

```
const openModalPropName: 'MyComponentOpenModal' = 'MyComponentOpenModal';
const openADifferentModalPropName: 'MyComponentOpenModalOther' = 'MyComponentOpenModalOther';
export default WithModalHOC(WithModalHOC(MyComponent, { openModalPropName }), { openModalPropName: openADifferentModalPropName });
```

**Comment by apsavin** [comment]
Like [this](https://flow.org/try/#0C4TwDgpgBAKhDOwA8MA0UBiA+KBeKA3lAHSkEA+UA2jALoBcUA5AOoDyASgDIAiTU5AL7oSZSlQwNmAIQCCHJuiFRBAbgBQ6gMYB7AHaIoACQCiXLm0ZNT5tv3zWzFpht0HgmNpeYYv9n34a2vqGwAjAjHCISKCQOgBmxk5s6LEQCZ5sOPgE6gCQNhZW7Nx8qOpQUHm+3kxyCuWCmsHuUADuAE76AOaR4THg6YmFKVBpGTXZhPkjxZy8ihVVvlb1i4JAA)?

**Comment by Rohit-L** [comment]
@apsavin Thank you! Interesting syntax..

**Comment by Athelian** [comment]
This syntax is invalid in modern Flow, could it be reopened?

**Comment by Athelian** [comment]
> Like [this](https://flow.org/try/#0C4TwDgpgBAKhDOwA8MA0UBiA+KBeKA3lAHSkEA+UA2jALoBcUA5AOoDyASgDIAiTU5AL7oSZSlQwNmAIQCCHJuiFRBAbgBQ6gMYB7AHaIoACQCiXLm0ZNT5tv3zWzFpht0HgmNpeYYv9n34a2vqGwAjAjHCISKCQOgBmxk5s6LEQCZ5sOPgE6gCQNhZW7Nx8qOpQUHm+3kxyCuWCmsHuUADuAE76AOaR4THg6YmFKVBpGTXZhPkjxZy8ihVVvlb1i4JAA)?


This syntax is invalid in modern Flow, could it be reopened?
