### ISSUE TITLE
Incorrect property is missing in undefined for optional array on second attempt to access array method

### ISSUE THREAD

**Issue by koulmomo** [facebook/flow#6296]
Even if you have an `Array.isArray` check in the correct scope before accessing array methods, flow will error on the second attempt. [try flow link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN4BGAhgE4D8AXGAIL321YA8AzhnoBLAHYBzAHwBfANzooAVxEBjDELgiwtACbaAKnABCDABRQSrYnAA0YAG60YCvKwHDxASiqoAkEKgmAIQcXFgAdEJ8IdxmJGF09B5elKhgaWA+9HgYCvQiculgUqlgJWnmcPEMYeb0AKK0ygAWJiYOMF5kElTKGnxwMHhh8GJtjh4yUh4lJT4VVfRhOAp8Le3OE6jFQA
)

```js
/* @flow */

type Foo = {bar?: Array<string>};

function addToBar(foo: Foo, value: string) {
  if(!Array.isArray(foo.bar)) {
     return;
   }
  
  // flow says this is cool for all array access methods forEach/map/filter/etc...
  foo.bar.forEach((val) => {console.log(val);}) 
  
  // flow complains Cannot call Array method because property `push` is missing in undefined [1]
  foo.bar.push(value);
}
```

**Comment by vicapow** [comment]
Technically, something could happen to `foo` to loose it's refinement in the function call (either in `forEach` or `console.log`). Because of this, Flow looses the refinement. To avoid this, assign `foo.bar` to a new locally scoped variable.

````js
function addToBar(foo: {bar?: Array<string>}, value: string) {
	if(!Array.isArray(foo.bar)) {
    	return;
    }
  const { bar } = foo;
  bar.forEach(val => val);
  bar.push(value); // no error!
}
````

see: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYAhgCbkAqcAQqQE4AUUccAXGAN4BGjA-JwCCDBqQCeAHgDOeBgSwBzAHwBfADRgAbqRgYApp1nylASm6oAkAShMAhCLHiAdAWmOJLNs74NT5rlQwYLBLBn08DAYsAG4gkNV4nGJZbjBfMFUwAF4wVjg44N9nVgYAUVIcAAsmHRgc5W1dU0L0xmcABwxpGrqDFtREoA

**Comment by koulmomo** [comment]
closing as works as intended.

Thanks @vicapow!

**Comment by deckar01** [comment]
It feels like there should be a way to hint to flow that the method does not mutate the input rather than changing functional logic.

**Comment by deckar01** [comment]
The work around doesn't prevent the function from causing errors. It just tricks flow into ignoring it.

- Error: https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqLNgBYCmATgLJmmwAmAFLAEYBWAlKAN6Kii5IoRlQCGpAHQVR6erAC2jLgD5QABgkBWLr3796ZaLTJF2EyLFgBuPqAC+iBygw58hebRINm7AFw8AN1FoVDIAfn9uC1h-NCw8Ajs7HVtBYVY2CSCQshS9IlJKGjomDKzg0I4bfJBQABIAUQAPAAcyHAaKClgKW34y7NDzSyVq+0dkDxLGbkGySOjYlwT0JR5QClpUCkJsClCreySqxCA
- False Negative: https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqLNgBYCmATgLJmmwAmAFLAEYBWAlKAN6Kii5IoRlQCGpAHQVR6erAC2jLgD5QABgkBWLr3796ZaLTJF2EyLFgBuPqAC+iBygw58hebRINm7AFw8AN1FoVDIAfn9uC1h-NCw8Ajs7HVtBYVY2CSCQshS9UCCKAuDQ0ABeU0zs0Jt84nJqT28MrJLc2r0QUAASAFEADwAHMhxeigpYClt+arJzSyUOhycPOiZuWcjo2JcE9CUeUApaVApCbAoa+ySOGyA

What is the point of having this behavior if it can easily bypassed accidentally with a single variable assignment?
