### ISSUE TITLE
[ Question ] Promise (async / await)

### ISSUE THREAD

**Issue by cavaller** [facebook/flow#6298]
2 classes
ClientData and Client

The function `client` in the `ClientData` returns an `Object` with `[string]: string`.
But the function `me` in the `Client` returns an `Object (ClientType)` with `id: number`.

**_The Flow does not warn me I am returning id as a number._**
It is a bug?

## ClientData.js
```
class ClientData {
  async client ($: { clientId: string, }): Promise<{ [string]: string, }> {
    const { clientId, } = $;

    const query = `
      SELECT
        *
      FROM
        public.client
      WHERE
        id = $1;
    `;

    return (await this.query(query, [ clientId, ])).rows[0];
  }
}
```
## Client.js
```
type ClientType = {
  id: number,
};

class Client {
  data: ClientData;

  constructor ($: {}) {
    this.data = new ClientData($);
  }

  async me (): Promise<ClientType> {
    return (await this.data.client({ clientId: this.data.clientId, }));
  }
}
```

**Comment by EnoahNetzach** [comment]
by removing the (useless, here) `async` and `await` in `Client.me`, the error gets thrown.

**Comment by SamChou19815** [comment]
Not enough info to repro
