### ISSUE TITLE
Dynamic type testing for `extensionof` analogue to `instanceof`

### ISSUE THREAD

**Issue by popham** [facebook/flow#630]
I would like to do some dynamic type testing based on an ES6 class's ancestry.  I've found that the concise way to check if class K is or derives from class A is by `K===A || K.prototype instanceof A` (I'm contemplating a sweetjs macro that maps `K extensionof A` to this expression).  When I attempt to use this filter in Flow, however, I get an error.

``` js
class A {
  static someMethod(): number {
    return 18;
  }
}
class B {}

function test<T: A | B>(K: Class<T>): number {
  if (K===A || K.prototype instanceof A) {
    return K.someMethod();
  }
  return 0;
}

var a = test(A); // OK
var b = test(B); // NG: call of method someMethod
// Property not found in statics of B
```

I've got an actual use case driving my interest in this missing feature; it seems pretty useful (if ES6 classes catch on).  Any chance of supporting this in the not too distant future?

(Flow rejects `K.someMethod !== undefined` and `K.someMethod` as predicates.  My current kludge is a vacuous `someMethod` implementation on `B` that always throws.  In the contrived case above, I would simply attach `test` to both classes, where one version returns 18 and the other returns 0.)

**Comment by jeffmo** [comment]
cc @mroch @bhosmer who have the best understanding of the current state of refinements/predicate

**Comment by moll** [comment]
Seeing the same problem here in `Property prototype is missing in statics of SomeConstructor` when trying to identify whether a constructor function is for a particular object hierarchy ~ `SomeConstructor.prototype instanceof Foo`.
