### ISSUE TITLE
RelativeImageStub can not resolve @2x @3x png or jpg

### ISSUE THREAD

**Issue by helele90** [facebook/flow#6300]
`[options]
module.name_mapper='\.\(bmp\|gif\|jpg\|jpeg\|png\|psd\|svg\|webp\|m4v\|mov\|mp4\|mpeg\|mpg\|webm\|aac\|aiff\|caf\|m4a\|mp3\|wav\|html\|pdf\)$' -> 'RelativeImageStub'`

some one knows how to resolve @2x, @3x png

**Comment by mrkev** [comment]
For usage questions please consult [Stackoveflow](https://stackoverflow.com/questions/tagged/flowtype).
