### ISSUE TITLE
can't load external file

### ISSUE THREAD

**Issue by fatfatson** [facebook/flow#6305]
in react-native, we can load external file(out of project directory) by many ways, such as 
1. `extraNodeModules` in rn-cli.js
2. `projectRoots` in rn-cli.js
3. babel-plugin-module-resolver

but none of them could be used in flow-bin,
so how can we load external file in flow checking?

**Comment by mrkev** [comment]
not sure I understand what you mean / want to achieve. Care to elaborate?

**Comment by mrkev** [comment]
That's odd. Flow should low everything you import on your file tree.

1. Is your `.flowconfig` on the root of your project (right under `project`)?
2. Do you have anything in your `.flowconfig` that might be blocking common from being imported?

**Comment by fatfatson** [comment]
I'm running react-native and flow in `client`,
`common` is not visible to them normally.
however react-native has a `rn-cli.js` config to work around it,
but how could flow recegonize `common/tools` is in another directory  outside the root?

**Comment by mrkev** [comment]
This functionality is documented: https://flow.org/en/docs/config/include/

**Comment by fatfatson** [comment]
no, it does not work!
create a new project by `react-native init ph`
add the below line to  `index.js`:

`import { bindThis } from "tools.js";`

and below to `.flowconfig`:
```
[include]
../common/
../common/*.js
```
running flow will complains:

> Cannot resolve module `tools.js`.
> 
>    4| import { bindThis } from "tools.js";
>                                ^^^^^^^^^^

**Comment by mrkev** [comment]
```
import { bindThis } from "../common/tools.js";
```
