### ISSUE TITLE
Declaration of union allows accessing invalid properties on classes

### ISSUE THREAD

**Issue by decentralion** [facebook/flow#6306]
Consider the following code, accessible at [this flow.org/try]

```js
// @flow
class Base {
  // Removing this constructor fixes the problem
  constructor() {}
}
// Changing this Subclass to not extend Base also fixes the problem
class Subclass extends Base {}

// Removing this line, or changing it to not return a union, fixes the problem
const thisLineShouldNotMatterButItDoes: Subclass | Base = new Subclass()

// Both of these lines SHOULD fail; neither does (either together or independently)
new Base().fail();
new Subclass().fail();
```

The issue repros on master and back to v0.37.

Props to @wchargin for helping to construct this example.

[this flow.org/try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjaBDAzh0AhTBTUAb0VFBFACV8BbWANwEsA7Ac1ABcALR7ZWZhg4AnAK7IOsYaEiMAHvmzdCAB2GwARtFqlQ-QSPGThACgCUxAL6JrFAMJc0bFu269QAZVEbUmJbFBmWA5QfDkOfGYAE1wCUDRoDADZBSUuVXUtHV8sT28c7DCI6Ow8DEIia0QKajomNk4ebGgWfAAaUCk9R2cGxhDJQODQYXwOUWFmeNBRZkYBDpTFRozNbRoUASFG3gAZVo8uWFFoKIA5YIBZNA4I4RxRDgBJDgARWEUALjyfdFyAH1i5VAAF5Avh4D8CuZENUwDhglxOpAVsCWsxlh4ABIAeQAqrtXjI0IxoABucH9dLSKIfbAmfBU-DSSSsMbUzrSFhRfAqSI85gcaAATzMiAxkLK+HMADpICToOYyeKIVC-hhZfLSUqgA

**Comment by goodmind** [comment]
This was fixed in Flow v0.98
