### ISSUE TITLE
Support array+object and function+object intersections

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#631]
Functions and arrays are objects, and it's OK to stick extra properties on them.

This would be useful for annotating the return type of `String.prototype.match`, which is an array but has an additional property:

``` javascript
/* @flow */

type MatchResult = (Array<string> & { index: number });
declare var result: MatchResult;
result.index; // object type
for (var x of result) {} // array type
```

```
test.js|3 col 21 error|  array type
|| This type is incompatible with
test.js|3 col 37 error|  object type
|| 
test.js|5 col 1 error|  property index
|| Property not found in
/private/var/folders/z1/sdzkzrw94b1dttp72spg4fd00000gn/T/flow/flowlib_24b3ff67/lib/core.js|135 col 1 error|  Array
|| 
```

Using intersections might be the wrong solution to this, but it seems reasonable to me. Whatever the solution is, we need some way to declare types for functions and arrays with extra properties. Inferring and tracking those properties automatically is a known and related issue, but I think this different enough to warrant its own issue.

**Comment by maranomynet** [comment]
I was running into the same in #3036 - and find it very disappointing that Flow doesn't seem to have any way of supporting this relatively common pattern.

**Comment by maranomynet** [comment]
It's been a while and some new features have been added to Flow since.
Has the status of this issue changed in any way?

This usage pattern is fairly common on JavaScript - to take an existing object (Element/Function/Array/etc.) and tack custom properties on to it.

**Comment by calebmer** [comment]
If you switch the order of the array type and the object type it [appears to work](https://flow.org/try/#0C4TwDgpgBAsghsAxgCwEoQM4FcA2woC8UAFAN5QCWAdgCYQAeAXFFVgLYBGEATlAL5QAZFACC3bnBAAeDMG7UA5gD4AlAG4AUHUQ443aADc9UfdjzN4SNJlzBNp2wDpqdemqgB6D1AD2HAFYQiPigkBoAZj68xEa89L7hJjZ4KlCkAl5QehIgUKEQGkA). I’m going to close, but this is still a bug which may be worth investigating.

```js
type MatchResult = ({ index: number } & Array<string>);
declare var result: MatchResult;
result.index; // object type
for (var x of result) {} // array type
```

**Comment by maranomynet** [comment]
@calebmer, I'm curious, **if** this is a bug (and it seems) then how should we report it as such?

I'd have thought closing an issue like this, might lead to the bug going unfixed/unnoticed...
