### ISSUE TITLE
Question: Access object properties by indexer

### ISSUE THREAD

**Issue by eluchsinger** [facebook/flow#6312]
How can I access an object's properties by an index like in the [React Tutorial](https://reactjs.org/docs/forms.html#handling-multiple-inputs) (Forms / Handling Multiple Inputs)?

If I try to do something like this:

```javascript
prevState.project["name"] = "Michael";
prevState.project[name] = value;
```
I get the following error: `Cannot assign value to prevState.project[name] because an indexer property is missing in Project [1]. (References: [1]).`

My project object is a class that looks like this:
```javascript
{
   name: string
   otherStuff: Stuff[]
}
```

**Comment by apsavin** [comment]
It's better to ask questions on sites like StackOverflow.com

Could you please reproduce the problem on flow.org/try and provide a link?

**Comment by vicapow** [comment]
This seems to be working as of Flow 0.91

````js
const a: { foo: string } = { foo: 'wow' };
a['foo'] = 'wow';
a['bar'] = 'okay'; // Error as expected.
````
