### ISSUE TITLE
Object with non-nullable key doesn't flow into object with nullable key

### ISSUE THREAD

**Issue by spudly** [facebook/flow#6313]
I need two object types. The first should have a nullable property, and the second should be the same, but that property should be non-null. I can create these types, but flow will not allow the latter to flow into the former.

Here's a reduced example to illustrate the bug:
```js
type A = 'A';

type HasNullableA = {|a: ?A|};
type HasA = {|a: A|};

const objHasA: HasA = {a: 'A'};

const objMightHaveA: HasNullableA = objHasA;
```

The last line fails with the following error:
```
const objMightHaveA: HasNullableA = objHasA;
                                       ^ Cannot assign `objHasA` to `objMightHaveA` because string literal `A` [1] is incompatible with null or undefined [2] in property `a`.
References:
4: type HasA = {|a: A|};
                    ^ [1]
3: type HasNullableA = {|a: ?A|};
                            ^ [2]
```

I would not expect this to fail. I expected that I could assign a HasA to a HasNullableA, but not the reverse.

Try It: https://flow.org/try/#0C4TwDgpgBAglC8UDkMkG4BQHSSgCQEMBnAOQFcAbCggIwojkQG8AfAgLigH4YWBfTDmiEijKKw6x+mDAGMA9gDsiwKPJoArETE7aE4ySiQCsC5avUaAsgEsA5gAtghAG4NdxclVr0xl7WhAA

**Comment by apsavin** [comment]
Works correctly.
Your objects are writeable. So you can set `null` to `objMightHaveA.a`. It will mutate and break `objHasA.a`.

**Comment by spudly** [comment]
My bad. I didn't understand how covariance works to enable you to pass more specific types in the place of more generic types.

For others who may have fallen into this mistake:
See https://flow.org/en/docs/types/interfaces/#toc-covariant-read-only-properties-on-interfaces

In my case, I generally treat everything as immutable (by convention), so I should probably just make everything read-only using `+`, `$ReadOnly`, and `$ReadOnlyArray`.
