### ISSUE TITLE
Add an optional static attribute to a type extending React.Component

### ISSUE THREAD

**Issue by danrot** [facebook/flow#6318]
I would like to add another optional function to `React.Component` in my project. Therefore I tried something like this:

```javascript
type View = ComponentType<*> & {+getDerivedRouteAttributes?: any}
```

You can see the results here: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3ChtnjgJ7qGgDeAYWqYAdoVE4AKj0IBfUJWp0GZHC0SJuvUADVkheKAC8oYe3GSZvADwAqAHygAZAIDUAc0I4AIoSzIAG6EACb4sACuOIQAgjg4AQBGUYQAzgD8AFygxKJccqyIpLCiqXhSaTjZ+oYmoKTQxKmpoIQAHtGiIS1EagB05mISODb8ck78iKCgZcQ4yKSgXr7+QaHhKXEJyMnRqQAUAJQCU6ByiAWaxaXllQBM1QZGpg1NLe2d3QSMOAMiJcNRuMTgUgA

I have marked the new attributes with a question mark, which should mean that the property is optional, and it is not necessary to provide in order for the type to be fulfilled. However, as you see in the flow try above, this question mark doesn't seem to make a difference.

Am I doing something wrong here? Or is that somehow the expected behavior? If yes, what other possibilities do I have to add a static optional property to a React component?

**Comment by apsavin** [comment]
Something like [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3ChtnjgJ7qGgDeAYWqYAdoVE4AKj0IBfUJWp0GZHC0SJuvUADVkheAB4ACgD5QAXlDD24yTN6mLAMgEBqAOaEcAEUJYyABuhAAm+LAArjiEAII4OIEARtGEAM4AXKDEolwKAD42IrD20rLOrIikJWl4Uuk4WfqGRvxyFtak0MRpaaCEAB4xoqF9RGoAdLZiEjit7QKIoKC1xDjIpKDefgHBYRGp8YnIKTFpABQAlIvLcohyldWitaD1tQBMTQbGbR2gXT0+oNhqMCIwcFNiqV5hZ+PdmEA)?

BTW `*` is depreceted.

**Comment by apsavin** [comment]
It seems so, my bad.

Alternative is implicit types AFAIK.

**Comment by angly-cat** [comment]
@danrot [check this](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3ChtnjgJ7qGgDeAYWqYAdoVE4AKj0IBfUJWp0GZHC0QpJhLJDJ94yHAAsA4oRwARHcgBuhACb5YAVxyEAgjhxZkAIzdCAGcBRFBQAGoAcwtrX3snV3cvH39AoIB+AC5QYlEuABpEOU1uXlAANWRCeAAeAAUAPlAAXgJGHAASYXZxSRleBuaAMlBDE3MrGwTnQJTfAPcg1kRSWFEgvClgnByqmtr+OWa20mhiIJDCAA93UQcQojUAOh6xCRxD49DwzeIcZCkUAxKbxRyzZLeBbpAAUAEofqASnIVmsNlsdgAmPbVOpHE6gM4XK63CQPdovN7rD5fZr8Yqo9abUDbTYAZhyT3InQAotBCKgafjWqBaqycJjQMBGswgA).

**Comment by danrot** [comment]
Finally found the time to test what @lebedev wrote, and it works for me :see_no_evil: Therefore closing this issue :slightly_smiling_face:
