### ISSUE TITLE
Issue with bounded polymorphism on react component's props ?

### ISSUE THREAD

**Issue by barroudjo** [facebook/flow#6323]
Hello,

I've come across this issue: when trying to do bounded polymorphism on a React component props, it seems that using a component method to call a function from the props gets flow confused with the types.
Because an example is much clearer:
````javascript
//@flow
import React from 'react';

export type DropdownSelectElement = {
  uniqueId: number | string,
  render: () => React$Node
};

type Props<T> = {
  data: Array<T>,
  onChange: (param: T) => void
};


class DropDownSelect<T: DropdownSelectElement> extends React.PureComponent<Props<T>> {
  //props: Props<T>;

  selectOption = (value: T) => {
    this.props.onChange(value);
  };

  render() {
    return (
      <div>
        {this.props.data.map((element) => {
          return (
            <span
              {/* the line below gives the following flow error: */}
              {/*Cannot call `this.selectOption` with `element` bound to `value` because `DropdownSelectElement` [1] is incompatible with `T` [2].*/}
              onClick={() => this.selectOption(element)}
              key={element.uniqueId}
              >
              {element.render()}
            </span>
          );
        })}
        )}
      </div>
    );
  }
}
````
Here is the link to reproduce it: [flow.org/try](https://flow.org/try/#0PTACDMBsHsHcCh4EsC2AHaAnALgAgEoCmAhgMZ7ibQq4DkmJ5tA3IoQB4Y67YCeahXABEqaACZwAdgGVCkQuQCi8lIUl4AvLgDe8XLgCukpAEcDhAJJiAXLkkGUAI0KZcAH1wBnbJiSSA5gA0ergMkmIutgAUAJS4GgB8BIzYACQActAR8AC+rPB8ArgACqKeADwAKklauvpixNjEtgCCmJjEvFUJwfrQkgDCABbEAYTRaMQdKLaVcYm4AG7QSGK5+fCkkMSensKiQlKy8uRVtiLQ4kdyCtjKhKrqSRzYamJ7RGTYAHTFBgwDagYSRqbDlUqXCrVJJ1XAgNBlWwQtBQhL5fSeG7kADyaGwSH68VwUUWxEg5lm8xhIX02CGSE83wRkO+-WGo38hBJZPMMVY+jyiH0YQimFiOhpoUI2H+kmJkv05TESEWCQV+h0dIZTLK3waTW+KGIaCiURuj2wVIlGptGoYMswcqi6ttuHKnkmkhdrtwbMgSFIAGsNNpxQstYzMSdsLj8f0zSpQTEct7XYHCLwQ+bQd8jKZzFYUz6fWri67tNn1N8RS5YkWy4rgB7RqWy3zvTlk96u67ysBlarJe2Bbl4EA)

And what's really interesting is that replacing 
````javascript
this.selectOption(element)
````
by 
````javascript
this.props.onChange(element)
````
 [makes the error disappear](https://flow.org/try/#0PTACDMBsHsHcCh4EsC2AHaAnALgAgEoCmAhgMZ7ibQq4DkmJ5tA3IoQB4Y67YCeahXABEqaACZwAdgGVCkQuQCi8lIUl4AvLgDe8XLgCukpAEcDhAJJiAXLkkGUAI0KZcAH1wBnbJiSSA5gA0ergMkmIutgAUAJS4GgB8BIzYACQActAR8AC+rPB8ArgACqKeADwAKklauvpixNjEtgCCmJjEvFUJwfrQkgDCABbEAYTRaMQdKLaVcYm4AG7QSGK5+fCkkMSensKiQlKy8uRVtiLQ4kdyCtjKhKrqSRzYamJ7RGTYAHTFBgwDagYSRqbDlUqXCrVJJ1XAgNBlWwQtBQhL5fSeG7kADyaGwSH68VwUUWxEg5lm8xhIX02CGSE83wRkO+-WGo38hBJZPMMVY+jyiH0YQimFiOhpoUI2H+kmJkv05TESEWCQV+h0dIZTLK3waTW+KGIaCiURuj2wVIlGptGoYMswcqi6ttuHKnkmkhdrtwbMgSFIAGsNNpxQstYzmSjWYMRmMzSpQTEct7XYHCLwQ+bQd8jKZzFYUz6fWri67tNn1N8RS5YkWy4rgB7RqWy3zvTlk96u67ysBlarJe2Bbl4EA) although nothing has really changed...

Is this really a flow error, or am I missing something somehow ?

**Comment by barroudjo** [comment]
Sorry to insist, but has anyone been able to look into this ? I provided the flow.org/try links to reproduce the issue. It would be really helpful to know if there's something I'm doing wrong, or if there is indeed an issue.

**Comment by idiostruct** [comment]
I'm unable to articulate _why_ your solution doesn't work, but here are two workarounds: [Try Flow](https://flow.org/try/#0PTACDMBsHsHcCh4EsC2AHaAnALgAgEoCmAhgMZ7ibQq4DkmJ5tA3IoQB4Y67YCeahXABEqaACZwAdgGVCkQuQCi8lIUl4AvLgDe8XLgCukpAEcDhAJJiAXLkkGUAI0KZcAH1wBnbJiSSA5gA0ergMkmIutgAUAJS4GgB8BIzYACQActAR8AC+rPB8ArgACqKeADwAKklauvpixNjEtgCCmJjEvFUJwfrQkgDCABbEAYTRaMQdKLaVcYm4AG7QSGK5+fCkkMSensKiQlKy8uRVtiLQ4kdyCtjKhKrqSRzYamJ7RGTYAHTFBgwDagYSRqbDlUqXCrVJJ1XAgNBlWwQtBQhL5fSeG7kADyaGwSH6UUWxEg5lmcVh+mwQyQnm+CMh336w1G-kIRJJ5hirH0eUQ+jCEUwsR0IQFhGw-0kuCiYv0uHKYiQiwScvlOmptPpZW+DSa3xQxDQUSiN0e2HmMLV6tCEqlMutNoVnkmkkdTtwzMgSFIAGsNNoRQtNXTMSdsLj8YSzaCYjl3U7fYReAGY+pvkZTOYrPGPR7VXmndo0z9BS5YrnC-pysAXaMC4Xue6cnH3a2nTWlSq5U3ebl4EA), [Try Flow](https://flow.org/try/#0PTACDMBsHsHcCh4EsC2AHaAnALgAgEoCmAhgMZ7ibQq4DkmJ5tA3IoQB4Y67YCeahXABEqaACZwAdgGVCkQuQCi8lIUl4AvLgDe8XLgCukpAEcDhAJJiAXLkkGUAI0KZcAH1wBnbJiSSA5gA0ergMkmIutgAUAJS4GgB8BIzYACQActAR8AC+rPB8ArgACqKeADwAKklauvpixNjEtgCCmJjEvFUJwfrQkgDCABbEAYTRaMQdKLaVcYm4AG7QSGK5+fCkkMSensKiQlKy8uRVtiLQ4kdyCtjKhKrqSRzYamJ7RGTYAHTFBgwDagYSRqbDlUqXCrVJJ1XAgNBlWwQtBQhL5fSeG7kADyaGwSH6s3iSWWq3iS2IkHMxJ0IX02CGSE83wRkO+-WGo38hCii0p5hirH0eUQ+jCEUwsVp+jFhGw-0kuCidJl5TESEWCRVMp0DKZLLK3waTW+KGIaCiURuj2w8xh2p1oTlCqVDsduHKnkmkjd7twHMgSFIAGsNNopQs9czMSdsLj8f0rSpQTEcr73cHCLww9bQd8jKZzFY036-VrS+7tLn1N9xS5YiWK-pysAvaNyxXBb6cqnfb33S31ZqVV3hbl4EA).

**Comment by barroudjo** [comment]
Thanks a lot, that's already pretty helpful !
But that also means this appears to be a real bug with flow...

**Comment by SamChou19815** [comment]
It no longer errors
