### ISSUE TITLE
Flow: Cannot call `this.methodName` with `arr` bound to `paramName` because read-only array type [1] is incompatible with array type [2].

### ISSUE THREAD

**Issue by theapache64** [facebook/flow#6325]
I am getting `Flow: Cannot call `this.methodName` with `arr` bound to `paramName` because read-only array type [1] is incompatible with array type [2].` from 
```
<TagInput
    ...
    onChange={(arr) => this.methodName(arr)}
    ^
    ...
    />
```

I am new in JS/React-Native/Flow. Why this is happening.? and how can i fix the error.

**Comment by apsavin** [comment]
It seems that you're passing a read-only array in a function that expects mutable array as a parameter, which is an error, because otherwise it would be possible to mutate a read-only array in such a function.

**Comment by mrkev** [comment]
Please refrain from asking usage questions here; stackoverflow.com with the `flowtype` tag is a good resource for that.
