### ISSUE TITLE
TextDecoder and TextEncoder missing from node's "util" module

### ISSUE THREAD

**Issue by julienw** [facebook/flow#6326]
Flow has a module definition for `util`:
https://github.com/facebook/flow/blob/4d8376ab1541c7ed70fa57b243bfe377609cd801/lib/node.js#L1711-L1723

But it lacks the definition for TextDecoder and TextEncoder that node has since v8.3.

Code to reproduce:
```javascript
import { TextEncoder, TextDecoder } from 'util';
```
Error:
```
Cannot import TextDecoder because there is no TextDecoder export in util.
Cannot import TextEncoder because there is no TextEncoder export in util.
```

**Comment by mrkev** [comment]
Feel free to add it in a PR and ping me.

**Comment by julienw** [comment]
Thanks @mrkev, I did #6335

**Comment by mrkev** [comment]
Ok, I'll have a look later today / in the coming days
