### ISSUE TITLE
Broken type != null checks in class methods

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#6328]
Any call, to anything, after a null check against `this.prop` seems to reset that check:

```js
class A {
   time: ?Date = null;

  method() {
    if (this.time) {
      this.time.getTime(); // no error
    }
    
    if (this.time) {
      console.log();
      this.time.getTime(); // error?
    }
  }
}
```

The same code works if you pull it out of a class.  Is this just an overly aggressive mutation checker since theoretically a function call could change the value of `this.time` here?  If it's intended I object ;)

**Comment by vkurchatkin** [comment]
>  Is this just an overly aggressive mutation checker 

Yes, exactly. You have to modify your code a little bit to avoid this possibility:

```js
method() {
    const time = this.time;
    if (time) {
      time.getTime(); // no error
    }
    
    if (time) {
      console.log();
      time.getTime(); // no error
    }
  }
```

**Comment by mrkev** [comment]
Flow unfortunately doesn’t track side effects, so it assumes any función call could modify state.

https://github.com/facebook/flow/issues/6182

Pure functions have been proposed https://github.com/facebook/flow/issues/2715
