### ISSUE TITLE
Flow cannot resolve name Audio

### ISSUE THREAD

**Issue by EreHuc** [facebook/flow#6329]
Hi,

It's very simple and I didn't find anything about it, I just want to use a sound for an JS Vanilla project using HTMLAudioElement via `new Audio(src: string)`, but flow can't resolve name Audio.

Here's a link using [Try Flow](https://flow.org/try/#0MYewdgzgLgBAtgTwMogK5gCYwLwzAUwHcYBBVDASxAAoByABwEMoALAfShDcfKrYDMKAG3y0AlAG4gA) with the current behavior

Here's MDN doc about [HTMLAudioElement](https://developer.mozilla.org/fr/docs/Web/API/HTMLAudioElement)

Thx

**Comment by mrkev** [comment]
The library definitions are probably missing. Feel free to submit a PR for this, if that’s the case :+1:

**Comment by hecontreraso** [comment]
Any workaround here? I'm experiencing the same problem

**Comment by jamesisaac** [comment]
Added in v0.93
