### ISSUE TITLE
Unbound value Hashtbl.find_opt (Trying to compile flow 0.72 on Alpine:3.7)

### ISSUE THREAD

**Issue by PiTiLeZarD** [facebook/flow#6331]
Hey there,

So title says it all, I brushed off a lot of errors but I'm way over my head with ocaml and stuff. 

I'm having:
```
File "src/typing/flow_js.ml", line 690, characters 15-31:
Error: Unbound value Hashtbl.find_opt
Hint: Did you mean find_all?
Command exited with code 2.
Compilation unsuccessful after building 614 targets (0 cached) in 00:00:57.
make: *** [Makefile:224: build-flow] Error 10
```

https://github.com/facebook/flow/blob/4d8376ab1541c7ed70fa57b243bfe377609cd801/src/typing/flow_js.ml#L690

I imagine if it's there, it should work so it might be a version issue?
```
/tmp/flow # opam list
[WARNING] Running as root is not recommended
# Installed packages for system:
base-bigarray                  base  Bigarray library distributed with the OCaml compiler
base-bytes                     base  Bytes library distributed with the OCaml compiler
base-num                       base  Num library distributed with the OCaml compiler
base-threads                   base  Threads library distributed with the OCaml compiler
base-unix                      base  Unix library distributed with the OCaml compiler
conf-m4                           1  Virtual package relying on m4
cppo                          1.6.4  Equivalent of the C preprocessor for OCaml programs
dtoa                          0.3.1  Converts OCaml floats into strings (doubles to ascii, "d to a"), u
gen                           0.5.1  Simple and efficient iterators (modules Gen and GenLabels).
jbuilder                 1.0+beta20  Fast, portable and opinionated build system
lwt                           3.3.0  Promises, concurrency, and parallelized I/O
lwt_log                       1.0.0  Lwt logging library (deprecated)
lwt_ppx                       1.2.0  PPX syntax for Lwt, providing something similar to async/await fro
num                               0  The Num library for arbitrary-precision integer and rational arith
ocaml-migrate-parsetree      1.0.10  Convert OCaml parsetrees between different versions
ocamlfind                     1.8.0  A library manager for OCaml
ppx_tools_versioned             5.1  A variant of ppx_tools based on ocaml-migrate-parsetree
result                          1.3  Compatibility Result module
sedlex                       1.99.4  unicode-friendly lexer generator
wtf8                          1.0.1  Encoder and decoder for WTF-8
```

I don't know how else can I help in figuring this out. Any help would be gratefully received.

Cheers

**Comment by PiTiLeZarD** [comment]
Just an update: I played around with a bunch of different ways of compiling this and somehow stumbled upon one that works. So this issue is fixed I guess ;)

**Comment by cloudyster** [comment]
I'm facing the same problem trying to compile flow in RHEL6 - could you please provide some info on what had to done to make it compile?

**Comment by PiTiLeZarD** [comment]
Sure, so I realised I was partly using ocaml dependencies, partly system dependencies and I was installing them one by one. I made sure I had a clean install without ocaml/opam and I updated the whole thing recompiling opam first:
` $ opam init --comp=4.05.0 -a -y`
(pretty amazing that the tool can compile itself at any version!)

Then letting it do it's job with the dependencies:
` $ opam install flowtype -y`

Then make sure you're in the opam universe:
```
$ eval `opam config env`
```

Then I compile it as is:
```
 $ git clone --depth 1 --branch v${FLOW_VERSION} https://github.com/facebook/flow.git /tmp/flow
 $ cd /tmp/flow
 $ make -j$(getconf _NPROCESSORS_ONLN)
 $ cp bin/flow /usr/bin/flow
```

Here is the list of dependencies I had to make sure I had installed:
 - alpine-sdk
 - opam
 - m4
 - libelf and libelf-dev (not sure I actually need these)
 - ncurses
 - inotify-tools (in my case docker on virtualbox on osx eventfs isn't working though dur to VB not supporting it)
 - linux-headers, git, bash and diffutils

You can safely remove all these dependencies afterwards and delete your ~/.opam directory which will swell considerably. (if size is something you care about)

I ended up with a working version of flow for only 1.8Mb very happy with that.

Hope it helps!

**Comment by cloudyster** [comment]
Thanks Jonathan,

in my case updating opam to a recent version (opam switch 4.06.1) made it work.
Cheers
