### ISSUE TITLE
Handing resourceQuery (foo.js?something)

### ISSUE THREAD

**Issue by brigand** [facebook/flow#6332]
Either I'm doing something wrong, or flow can't be configured to handle a resourceQuery in an import path.

Webpack config that allows this:

```js
{
  test: /\.scss$/,
  oneOf: [
    {
      resourceQuery: /mod/,
      loader: loaderWithCssModules,
    },
    {
      test: /./,
      loader: normalLoaders,
    },
  ],
}
```

Attempting to rewrite them in flow config:

```
module.name_mapper='^\(.*\)\?.*$' -> '\1'
```

Attempting to ignore those imports:

```
[ignore]
.*\?mod
.*\?async
```

Neither of these seem to work. I wonder if flow has some assumption that `?` won't appear in a module path.

Flow version:

```
"flow-bin": "^0.69.0",
```

**Comment by mgmarlow** [comment]
Running into the same issue where I'm specifying `*.scss?raw` to compile w/o css modules.

**Comment by brigand** [comment]
@mgmarlow I ended up doing a hacky work-around with a babel plugin. [Code here](https://gist.github.com/brigand/d67b98ef8d301726abdb1801c2fe7f4e). Don't have time to make a package out of it right now, but you can define babel plugins inside your project.

Example:

```js
// your current code
import './foo.scss?raw';

// change to
import './foo.scss'; // @raw
```

Since it's `disk -> flow`, and `disk -> babel -> webpack` it works out.

**Comment by mgmarlow** [comment]
@brigand Thanks for throwing that up in a gist. I hope that this issue gets looked at so I don't have to keep the extra plugin around.

**Comment by brookslyrette** [comment]
You can also ignore the error by using `$FlowFixMe`.
