### ISSUE TITLE
$Values does not work correctly with generic type :(

### ISSUE THREAD

**Issue by AlexanderShushunov** [facebook/flow#6334]
There is generic function. Generic type should be an object.
```javascript
function getTypedValue<Obj: {}>(obj: Obj, key: $Keys<Obj>): $Values<Obj> {
    return obj[key]
}
```
If we use this function,
``` javascript
const obj = {
  a: 3
};
const typedResult = getTypedValue(obj, 'a');
```
$Keys works perfect. We cannot pass anything except 'a' as a second argument. 
But using $Values triggers an error.
```
18: const typedResult = getTypedValue(obj, 'a');
                        ^ Cannot call `getTypedValue` because number [1] is incompatible with `$Values` [2] in type argument `Obj`.
References:
8:   a: 3        ^ [1]
14: function getTypedValue<Obj: {}>(obj: Obj, key: $Keys<Obj>): $Values<Obj> {
                                                                ^ [2]
```
I try to specify object type:
``` javascript
const moreStrictObj: {|a: number|} = {
  a: 3
};    
```
It does not help.
[Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQJQBIDSBTAngZ1PLAE4DW+A5rLACYECWALgBajmYB2mRdAxqIpACu7Hgzqx2rTAwCq7BtgAOmagDUAhtEGYAPAHkARgCsAXKADeAXwB8ACljGzhowBpQJHGYw5c+49YBKMwBbOgAPFQtEUBjQImlBIkkHIwBtD2wAXURLREQeCVwGUBTQAF4omPUzAGYcgG48gvYi0GEFZWoAJUxcQWhiirZZeSUVDS1Me2M3AHJ1WYDG5DBUCe18alhe0HZYYsJSemYpTm4+E1sBYVFxSWGAFTG1TW0-UwsbaY-nNwyvLB4d6BLzrXrAyqxeIMRLJYzpHDZXL5QrFDoqHp9AblKQMJ6dMHfOYLJZNVGgYLETAAZQY5wYzjM5gAPtVdoJggYuMzLDjzNFQGy6pZGrExeKJWKUS1ikV6Q8iNh8Rjev1BrjlS9JrZKfFafTfqB5ot6kA)

**Comment by eps1lon** [comment]
Seems like Flow does not infer the typeof ```obj```. If you call it with ```const typedResult = getTypedValue<typeof obj>(obj, 'a');``` it throws no errors.

Might be good to tell what you really want to achieve. From this example it looks like [$PropertyType<T, k>](https://flow.org/en/docs/types/utilities/#toc-propertytype) might be better suited.

**Comment by AlexanderShushunov** [comment]
@eps1lon call foo<Type>() works! O_O Thanks for tip!

**Comment by AlexanderShushunov** [comment]
@mrkev Why did you close the issue?
I think Flow should infer ```$Values<Obj>``` correctly like   ```$Keys<Obj>```.
Besides, It then I made some experiments, I noticed, then Flow infer the type somhow. I caught errors, which point me wrong usage with object values.

**Comment by jwickens** [comment]
@AlexanderShushunov @mrkev I think this is another instance of the "conflating object value types" illustrated in issues #6056, #5584, #5141

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
