### ISSUE TITLE
Flow type inference is not passed down to Array prototype methods

### ISSUE THREAD

**Issue by pfarejowicz** [facebook/flow#6338]
Basic repro code here: https://flow.org/try/#0C4TwDgpgBAyg9gVwE4GNoF4BQUoB8oDOwSAlgHYDm2eUAgkkgIYgA8A3vqJAFxQDkANxIATCHAD0AWwDMCABx8agkWKlgALIvzLREuBQp8ANIVS8ipSngC+APgDcmJyjhkiUEgQByEAO7xkNCh0KAAKOAAbYQDUCF4YtBMyPwS42ERYgEpeACM4SIhGMmDbKDZqEgAzMK4xasjojKCAQnQQ2rhq5P8miEyy6hwkCGBkYuIECEcccXEoABUAC2gCCBcyYToGZgA6T3omEChhxgiIo88yPmAoZIhRTeXhqByEG+BFxApFm5IbyRI3xuywiYGo1igEAiqw81VCB12+22IFC3VS-QAZBitoc9gQESiGuj+uUcDgqmEib0dhEIJQPlBWiE0dTafTFiTBmThqMkOMkJNpmTrFyeWNbilqQQ4JIIKEuThQtLAhATORRAAPfroWwKsnK2I7WqMtpQKkqgDa6ogGoAukbwNBcLg9TgDWgdgRUCaQubYlaNjb7V6UFzMkKRUMRuKWSqfWaoqlHNZ7EA

After type checking that a variable which can be a string or an array is indeed an array, Flow is not able to pass that knowledge into a callback function

```
 if (Array.isArray(newSource) && Array.isArray(oldSource)) {
    if (oldSource.length !== newSource.length) {
      return true;
    }
    return newSource.some(
      (source, index) =>
        source.type !== oldSource[index].type ||
        source.src !== oldSource[index].src
    );
  }
```

In this code, Flow is ok with `newSource` strictly being of type `Array` but it does not understand that `oldSource` is also an `Array` inside the callback.

**Comment by ChristianKienle** [comment]
Better late than never:

I think your type refinement is lost due to calling `some`. Calling any function after you have refined a type usually causes the refinement to be lost. This is because flow is unable to know what kind of side effects the function has. You can work around this by assigning the refined variable to a local variable before calling a function.

```
type Source =
  | string
  | Array<{| type: 'video/m3u8' | 'video/mp4' | 'video/ogg', src: string |}>;


const isNewSource = (oldSource: Source, newSource: Source): boolean => {
  if (typeof oldSource !== typeof newSource) {
    return true;
  // The second Array.isArray really isn't needed here but thought it might help
  } else if (Array.isArray(newSource) && Array.isArray(oldSource)) {
    if (oldSource.length !== newSource.length) {
      return true;
    }
    const os = oldSource;
    return newSource.some(
      (source, index) =>
        source.type !== os[index].type ||
        source.src !== os[index].src
    );
  }
  return newSource !== oldSource;
};
```

This is also documented somewhere...

**Comment by pfarejowicz** [comment]
Thanks @ChristianKienle that helped
