### ISSUE TITLE
`this` return type from arrow function as class method

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#6340]
[try flow](https://flow.org/try/#0MYGwhgzhAECC0G8BQ1oFsCmAXAFgewBNYAKASgC5pcBLGBaAJ2wFcGA7KnWgbmgF8U6bPgIAhaAF5oZSjRgSAfJx5I+QA)

```js
class A {
  methodA(): this { return this; }
  methodB = (): this => this;
}
```

flow throws:

```
3:   methodB = (): this => this;
                   ^ Unexpected use of `this` type.
```

**Comment by vkurchatkin** [comment]
You should write it like this:

```js
class A {
  methodA(): this { return this; }
  +methodB: () => this = () => this;
}
```

**Comment by MarkKahn** [comment]
Thanks, but is there a reason that the normal arrow class annotations don't work?  Shouldn't this be considered a bug/improvement request?  Especially since you'd need to re-write, or at least oddly separate, all the arguments with that method.

**Comment by vkurchatkin** [comment]
Basically, `this` is only a valid type in a context of a class: class method or class property.
