### ISSUE TITLE
Combining union and intersection types

### ISSUE THREAD

**Issue by RShergold** [facebook/flow#6341]
I can't seem to combine union and intersection types. I have a union type (in my example I've called them action body) intersected with a metadata type. 

I've gone over the documentation multiple times and I can't figure out why this won't work. My ultimate aim is to implement the `foo` function.

[Try flow example here](https://flow.org/try/#0C4TwDgpgBAggxsAlgewHYFkLAIZQLxQAkAShNgCYDyqANiADwDeAUFFIuQFxSoCuAtgCMIAJwA0rKAGcIUqSlQBJLjwHCRzAL4A+Zs1CRYCBQEZ8RUhWp0mk1Nn4RuAchgnnEtnGS9UwbnxColq6+uDQ8EhoAEzmJGRUtAwsbPaOLjDRHpK8MiLcUsAiiKgA5lAhegYRxmgAQsjkIOaSAD5GUagmbR0K0QDcVeG9aOaRCpg4UABkI6gNTYN6zABmvrWoUCvIyAAUUI44nONok9hiUIKNIMcbCyAAlLedUClQIli8IpuMAHT-h3OUH+vyuTU0WmWzAA9AAqVbrF6CbAifbYDbPBRQJ6FYplV6SRArNEbX5paB4SlQVxZbEEthsD7AL6bdGdX65UT9CpsCGMz7famoNAQZyQ2HQvRwhGoDaXbAALxJnUxoyeAH5Aup6exidTvL5gM52Ky5Q8dfzmYK2Qpfga-INeZImSzVDQaOLoUA)

````
type ActionMeta = $ReadOnly<{
  id: number,
  sessionId: number
}>

type Action1 = $ReadOnly<{
  name: 'A1',
  count: number
}>

type Action2 = $ReadOnly<{
  name: 'A2',
  user: string 
}>

type ActionBody = 
  | Action1
  | Action2;

type Action = ActionMeta & ActionBody;



function foo( meta:ActionMeta, body:ActionBody):Action {
  return {...meta, ...body}
}
````

**Comment by almost** [comment]
Looks like the spread operator doesn't work with union types. I've made an issue for that here #6342

**Comment by mrkev** [comment]
Closing in favor of #6342
