### ISSUE TITLE
Spread on union type fails with "Could not decide which case to select"

### ISSUE THREAD

**Issue by almost** [facebook/flow#6342]
This code:

[Try it with Try Flow here](https://flow.org/try/#0C4TwDgpgBAggxsAlgewHYEYoF4oG8BQUUqAhgLYQBcUA5DOjQDT4C+++oksCKqATNjyFi5KrRh8mrdp2jwkaQcIA+3BRhVrefANzsAZgFdUPRfuTIAFFABGyACYhK83gEpnp1EKIAnCMEMfL1wAOjC7RxY9FiA)

```
type Action1 = {
  name: 'A1',
}

type Action2 = {
  name: 'A2',
}

type Action = 
  | Action1
  | Action2;

function foo( body:Action):Action {
  return {...body};
}
```

Produces this error:

```
    14:   return {...body};
                 ^ Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To fix add a type annotation to .name [3].
        References:
        10:   | Action1
                ^ [1]
        11:   | Action2;
                ^ [2]
        14:   return {...body};
                     ^ [3]
```

Replacing `return {...body};` with `return body` fixes it. It doesn't seem like flow should have to decide on a member of the union just to use the spread operator?

**Comment by szist** [comment]
Any progress on this? Is there a workaround annotation we could use in the meantime?

**Comment by mrkev** [comment]
Spreads on objects are have a few issues at the moment and are being reworked.

**Comment by jcready** [comment]
This doesn't really have to do with spread, you get the same error when you do the follow (which is essentially doing the same thing as spread):

```js
function foo( body:Action):Action {
  return { name: body.name };
}
```

**Comment by mrkev** [comment]
Oh true, this is a separate bug.

**Comment by frontendphil** [comment]
Is there anything we can do to work around this atm? I'm also running into this issue and it is quite frustrating.

**Comment by villesau** [comment]
this will fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by pirate-matt** [comment]
This hurts me a bit... but seems to be a workaround:

```jsx
type Action1 = {
  name: 'A1',
};

type Action2 = {
  name: 'A2',
};

type Action = Action1 | Action2;

function foo(body: Action): Action {
  const flowIsBroken: any = { ...body };
  const newlyTypedBody: Action = flowIsBroken;
  return newlyTypedBody;
}

const shouldBeActionType = foo({ name: 'A1' });

// no errors means it's been typed correctly?
foo(shouldBeActionType);
```

**Comment by nmote** [comment]
This no longer errors in master
