### ISSUE TITLE
Errors when using disjoint unions and utility type $NonMaybeType

### ISSUE THREAD

**Issue by kristiehowboutdat** [facebook/flow#6344]
I get unexpected errors (string literal is incompatible with string literal) when attempting to refine a disjoint union that was derived using $NonMaybeType. [Full reproduction of issue](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgD6N2+AdgIYC2eAXGAOSHcA0qAL4BudAwIAhUhSq16uPC3ZdukgXICWjKHC6EATgeZYAPAGcMB7QHMAfINHjFYAKIAPNjhgEyxAD5gkmKowMBgAMqarACuMMwYtmAAjjF4BlhgBnjmcRjmYFAGcKxgzDhwMPAAtADGcAAmeDZKmC4eXj4AimkZAEo5eTLk-nLZuTAYXAD8HazeeIL+TqHhAApxMGAYABYE40MSYHAxGIXFpbsEPemZTVDamolwjG34YAAi6ZoAbngNcwWABUXGQACQAOReAFkTAAjPAg-CmORgtbFfAGbBIvCmQHdXpYAYTDD8HgHSbcOyoOwhMJgCEAeSBri4AHU9owwABJMoYDB4eZnDBwMAAIhwm2OpzFxwM4qa1j+squWUGk22LiKJTAT24BRwzGyjFJZVOcBajHSCX+mvwZN5LTO6WKBgKuwSPLADVFjDgZydhTg8tVCPgSDwnnmPjJeD+XN2JxsO22ezA9SauvdafMbDwADpUPVGJYwAgdlgPnAciagTtNOY2cGANYyAAUFKmn2+fwBUeBigAlKQ7LJqJooGAO+qMPm6BJlAQAIQkMhqbjDyjUajF8yVAvwGxt7gCywbsTUITCOnhJksrh1htllsFctKL0Nyo21MEfEEI5POYeAwFAZJ+mcMTmEkqqnJoMBPJkEgFG2kIwvCiIuMGYBohi6TYkORYvKWuwNk2BjNgUZDTiSXB-sOJCjluuqTtReRzgoTB5mAK5ruom5yDuRH7vmh7HqeGDnnIV4rLuZw7MwjAND4xJDFRDQJMwtH9gStwqZM9GMXI9IABIKUpBCCjg2DpswQHmFoLFLupGDMGA-iBE5Gn5p2-HbmqGAxAYXKMJsF5gFeYx4AFQWpqRL5ts5zDeTOg5hfS2TRVy5aVtW5i1vWjYtglXk+WIohAA).

**Sample Code**

```
type A = {
  __typename: 'A',
};

type B = {
  __typename: 'B',
  info: Array<string>,
};

type Example = A | B;

// Simulating query results from apollo-codegen
type ExampleQueryResult = {|
  result: ?Example,
|};

// Pull the result type out from the Query definition
type DerivedExampleType = $NonMaybeType<
  $PropertyType<ExampleQueryResult, 'result'>
>;

// NOTE: When I attempt to "pull out" or "derive" the result type from it's parent, autogenerated type, I get errors that I do not get for the below example, even though the code is the same.
const whyDoesntThisWork = (result: DerivedExampleType) => {
  if (result.__typename !== 'B') {
    console.log('test');
  }
};

// NOTE: This works when I isolate the Example type itself, not using the utility types ($NonMaybeType or $PropertyType)
const thisWorks = (result: Example) => {
  if (result.__typename !== 'B') {
    console.log('test');
  }
};
```

**Expected**:
Using the `DerivedExampleType` and the `ExampleType` would act the same.

**Actual**:
Using `DerivedExampleType` results in cryptic errors like ` string literal A [1] is incompatible with string literal B [2] in property __typename`, whereas using `Example` results in no errors.

Removing the `$NonMaybeType` and making the `ExampleQueryResult.result` `Example` instead of `?Example` fixes the issue (no errors reported). However, I am relying on auto-generated types based on a graphql schema (using apollo-codegen) and cannot make that change.

**Comment by matikrk** [comment]
I also had same issue when I've worked with gql types. It's stopping working when I use it with `$NonMaybeType` & `$ElementType`. 

Here is my minimal example:
```
type Union1Type = {type: 'a', a: string} | {type: 'b', b: number}; // ok
type aType = {union: Union1Type};
type Union2Type = $ElementType<aType, 'union'>; // ok
type Union3Type = $NonMaybeType<$ElementType<aType, 'union'>>; // fail
type Union4Type = $NonMaybeType<Union1Type>; // ok


const fnc = (union: Union4Type): string => {
  if (!union) {
    return 'x';
  }

  if (union.type === 'a') {
    return union.a;
  }

  if (union.type === 'b') {
    return union.b.toString();
  }

  return 'z';
};
```

**Comment by SamChou19815** [comment]
This now works
