### ISSUE TITLE
Current flow_parser to Opam-repository

### ISSUE THREAD

**Issue by nickbetteridge** [facebook/flow#6346]
Hi,
Is there any chance that the latest flow_parser can be pushed to the OPAM-Repository? I've been developing on V72 and have just hit a load of conflicts due to opam's current version of V62.
Cheers, Nick

**Comment by mrkev** [comment]
Was this updated? Why did you close this?

**Comment by nickbetteridge** [comment]
Ended up copying the parser tree into my code - which I couldn't have written without flow!

**Comment by reynir** [comment]
Can this be reopened, please?

**Comment by nickbetteridge** [comment]
I no longer need this - I'm quite happy to reopen - you could also open another issue with the same title  @reynir - if you'd rather I did this from @nickbetteridge then no problems

**Comment by reynir** [comment]
Yes, could you reopen the issue so we don't duplicate issues unnecessarily? Cheers.

**Comment by nickbetteridge** [comment]
Re-opened as per request

**Comment by reynir** [comment]
A release on opam has been made https://github.com/ocaml/opam-repository/pull/12546
