### ISSUE TITLE
Incompatible generic types between react components using refs

### ISSUE THREAD

**Issue by Palisand** [facebook/flow#6348]
[Flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYG4AoDmATzCTgAFOmADOAMQgQAPABUAfHAC8uDnDgBzMkijA0AfgBccWZjVwAJhADKhJDAAWwYhoDqwRwHFtutMYAUWqS+xvqyAJTKiijEPGYUnBxoADYooqJwkjIKcEgAHjBkFhkERKTk0sIQYlly8oo4FFy8-EIiogBCKFB1ym3VElK9AGSq6hCOOlVgxjFxHAlcKWkZXT05+YXExXClkOUwle1rdQ3m5tRSobUAVPKc6qL2yNR9-szU10N3kUqKjsBRAA6S4QPofB5wczMbY6fyRHDmdTMGAAVygxDg-iR6jg0iyONxcA+ShwAOBTxgLyoAHoacSkCAIAA3ATk7DEME6OhQQm4nBAwXkoFgdpUPk0+Q48LmJpNIA)

Bar is meant to "extend" Foo while maintaining the generic type `T`.

```javascript
import React, {Component} from 'react';

type PropsFoo<T> = {
  generic?: T,
  doSomethingWithGeneric: (generic: ?T) => any,
};

class Foo<T> extends Component<PropsFoo<T>> {}

type PropsBar<T> = PropsFoo<T> & {
  otherProp: any,
};

class Bar<T> extends Component<PropsBar<T>> {
  
  foo: ?Foo<*>;
  setRef = (ref: ?Foo<*>) => this.foo = ref;
  
  render() {
    return (
      <Foo
        ref={this.setRef} // remove this, no error
        {...this.props} 
      />
    )
  }
}
```
```
21:       <Foo           ^ Cannot create `Foo` element because `T` [1] is incompatible with `T` [2] in property `generic`.
References:
4:   generic?: T,
               ^ [1]
5:   doSomethingWithGeneric: (generic: ?T) => any,
                                        ^ [2]
```
Am I doing something incorrectly or is this a flow bug?

**Comment by apsavin** [comment]
The [fix](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYG4AoDmATzCTgAFOmADOAMQgQAPABUAfHAC8uDnDgBzMkijA0AfgBccWZjVwAJhADKhJDAAWwYhoDqwRwHFtutMYAUWqS+xvqyAJTKiijEPGYUnBxoADYooqJwkjIKcEgAHjBkFhkERKTk0sIQYlly8oo4FFy8-EIiogBCKFB1ym3VElK9AGSq6hCOOlVgxjFxHAlcKWkZXT05+YXExXClkOUwle1rdQ3m5tRSobUKnOqi9sjU-szU10MKkThwjsCiAHSXCB9V5sJrqczMbY6fxfczqZgwACuUGIcH88PUcGkWUxWLgryUOF+AIeMCe-wARs4LP4SeEqAB6RkEpAgCAANwEJOwxGBOjoUDxWJw-zFJP+YHaVGFjPkmPC5iaTSAA).

Do not use `*`, it's deprecated.

**Comment by Palisand** [comment]
Thank you @apsavin. Why do I have to `bind(this)` instead of using an arrow function?

**Comment by apsavin** [comment]
You [don't have](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDeBhCcCAOyWJgF84AzKQuAcilQwYG4AoDmATzCTgAFOmADOAMQgQAPABUAfHAC8uDnDgBzMkijA0AfgBccWZjVwAJhADKhJDAAWwYhoDqwRwHFtutMYAUWqS+xvqyAJTKiijEPGYUnBxoADYooqJwkjIKcEgAHjBkFhkERKTk0sIQYlly8oo4FFy8-EIiogBCKFB1ym3VElK9AGSq6hCOOlVgxjFxHAlcKWkZXT05+YXExXClkOUwle1rdQ3m5tRSobUKnOqi9sjUAfo38pFKigBuEMAWff5mNQPg04I5gKIAHSXCB9IFsJrqczMbY6fyRHDmdTMGAAVygxDg-ix6jg0iyJNJcCBShw4KhDxgTyoAHoWdSkCAIF8BPTsMRYTo6FBKaScJCJfTIWB2lRRSz5CTwuYmk0gA) to.

**Comment by apsavin** [comment]
> Also, what were the motives behind deprecating * in 0.72.0?

I'm not sure (I'm not from the flow team) but I heard that `*` caused perf issues.
