### ISSUE TITLE
JSX: "Property is missing in undefined" just after checking the object is defined

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#6350]
Flow version: 0.72

Hello,

This code gives me an error `Property is missing in undefined`:

```jsx
type Props = {
  video: {
    frames?: Array<{}>
  } 
}

const component = ({ video }: Props) => (
  <div>
    {video.frames && // frames is defined
      video.frames.map((frame, i) => (
        <div key={i}>
          {(i === 0 ||
            ((i + 1) % 30 === 0
              && i + 1 !== video.frames.length)) && (
                                       ^^^^^^^ Property length is missing in undefined [1].
              <div>{i === 0 ? 1 : (i + 1) / 30 + 1}s</div>
          )}
        </div>
    ))}
  </div>
)
```

Reproduced here: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqfUIE8cywAFejgDOYALxgA3qjBgAbhgAmZOAC4pM2WDoUsZYQH51AQXz4KXADySAvgD5NNsKhvoqcAHbDi73J7IexBIAFJLySipgNuqCcCIAlOJ2YMGalooYcg5aUgrKcAB0OnqiAGSlmjl5KkXmJQVYFDjBwcVkADRgGIliyak5OemZYADWZFxikhj2lQOyksEY4mISAAxgAD4bs3OyLUsA1GAAjIkApGAAzOsra2DlXWBHx2AAhCvh+bW6+gUwAQBzQgAC3iiQe-V2cyGWSmyzuBhOYHUiyeJ0SwCu62eNmElmAGSyOwG8VcUPxhOyWjBZLAFMyDniQA

For now, I'm using this workaround `video.frames.map((frame, i, arr) => ... arr.length ...`.

---

I don't know if directly related, but I opened a slightly different issue 1 year ago, about `undefined` check issues in JSX too: #3558 (still open).

**Comment by apsavin** [comment]
See #5372

**Comment by ggregoire** [comment]
Oh thanks, I didn't know about this concept of refinement invalidation.

But does it really apply in this example? I'm not calling any method or reassigning any value to `video` and `video.frames`, so how could `video.frames` be undefined?

**Comment by apsavin** [comment]
This check is very simple in `flow`. Even the call to `map` like in your example is a call to a function. And I can break your code above if I know JavaScript good enough using this call. 

Ah, I'm waiting for possibility to mark functions as pure very much.

**Comment by mrkev** [comment]
JSX transforms into method calls too: https://babeljs.io/docs/plugins/transform-react-jsx/

**Comment by dominicfraser** [comment]
Adding a link to the documentation for refinement validation: https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations
