### ISSUE TITLE
Cannot ignore Flow complaint "Illegal return statement"

### ISSUE THREAD

**Issue by AlexMSmithCA** [facebook/flow#6351]
Minor, but this feels inconsistent.  By default, a `// $FlowFixMe` comment indicates that Flow errors on the following line should be ignored.  This is not the case for an [`Illegal return statement` error](https://flow.org/try/#0PTAEBIDEBsHsHdIEsAeBZApgKAE4YC4CuOAdqAKwDcQA):

```
// somefile.js

// $FlowFixMe
return 5; // Illegal return statement
```

A contrived example, but should this Flow complaint be suppressed in this case?

**Comment by vkurchatkin** [comment]
No, you can't suppress a parsing error
