### ISSUE TITLE
Cannot resolve module 'immutable'

### ISSUE THREAD

**Issue by javascriptonian** [facebook/flow#6352]
From my understanding, flow refers to the definition in the `node_modules/immutable` folder for the `immutable` module, so setting `module.system.node.resolve_dirname=node_modules` should allow flow to resolve the module, however I'm still getting the error message. Is this a bug or am I missing out on something?

The following is my `.flowconfig` file.

```
[ignore]
.*/node_modules/.*

[include]
./src

[libs]
flow-typed

[options]
module.system.node.resolve_dirname=.
module.system.node.resolve_dirname=src
module.system.node.resolve_dirname=node_modules
```

**Comment by javascriptonian** [comment]
Actually, I ignored the error message and it resolved after a very long time..

**Comment by sadnessOjisan** [comment]
@javascriptonian I think now I have a same issue. please tell me how do you resolve it.

**Comment by Tasemu** [comment]
I have this issue now, grrr. Tell me that is not the actual answer here because that is ridiculous.
