### ISSUE TITLE
flow.exe: anon unexpected argument 'flow'.

### ISSUE THREAD

**Issue by omoabobade** [facebook/flow#6354]
I use a 64 bit windows system, i have the windows binary installed and added to my path. But when i run 

> yarn run flow

or 

> yarn flow

i get 
` yarn flow
yarn run v1.6.0
$ flow version; flow check
flow.exe: anon unexpected argument 'flow'.
Usage: flow.exe [COMMAND]

i have flow v0.73.0 binaries inistalled. cc @trueadm

`

**Comment by mrkev** [comment]
This is weird. Does this happen with the latest versions of flow?

**Comment by nmote** [comment]
It looks like `yarn run flow` is running `flow version; flow check`. I'm not familiar with Windows, but I bet it's not treating those as separate commands, so it's like running `flow version flow check`. I get a similar error message when running `flow version flow check` on Linux.

I think you just need to adjust the command that Yarn runs for your project when you run `yarn run flow`.
