### ISSUE TITLE
No type checking in inline functions declared after return statement?

### ISSUE THREAD

**Issue by gstipi** [facebook/flow#6355]
This is reproducible in https://flow.org/try/. I stumbled upon this because I am currently adding some flow type checking to a library which occasionally defines small inline helper functions at the end of a function block.

```
// @flow
function test() {
  let foo = {a:0} 
  
  bar()
  
  function bar() {
    console.log(foo.b)
  } 
  
  // return statement after inline function
  return
}
```

As expected, the snippet above results in a type checking error:  "Cannot get `foo.b` because property `b` is missing in object literal"

**However, the same snippet with the inline function bar declared after return yields no type checking errors.**

```
// @flow
function test() {
  let foo = {a:0} 
  
  bar()
  
  // return statement before inline function
  return
  
  function bar() {
    console.log(foo.b)
  } 
}
```

**Comment by chrisvasz** [comment]
We are experiencing this problem a lot in our React components. React hooks encourage long function definitions, so to combat the increasing function size, we have been writing our components like this:

```jsx
function Component(props: Props) {
  let { onChange } = props
  return <input onChange={handleClick} />
  function handleChange(event) {
    onChange(event.target.value)
  }
}
```

Obviously a simplified example, but you get the idea.

**Comment by SamChou19815** [comment]
This has been fixed
