### ISSUE TITLE
$Call always uses the first definition for overlapping definitions in interfaces

### ISSUE THREAD

**Issue by chisui** [facebook/flow#6360]
If an interface contains overlapping definitions than `$Call` will always select the first match. Even if a better match exists:

```.js
//@flow
interface F {
  (0): 0,
  (0, 1): 1,
}
const a: $Call<F,0,1> = 1
```
[*try flow* version](https://flow.org/try/#0PTACDMBsHsHcCgCWA7ALgUwE7gIYGN0ACAMUIG95DCAKABgEoAuQ2gGkprcIEYmf2AvvDzRkAZ1SEczACQBhHJEgAeYqzbcAfIQC8PIA)

The assignment of `a` will not typecheck since `$Call<F,0,1>` evaluates to `0` instead of `1`.

Swapping the order of definitions inside the interface will get rid of this particular error since the best match happens to be the first one.

```.js
//@flow
interface F {
  (0, 1): 1,
  (0): 0,
}
const a: $Call<F,0,1> = 1
```
[*try flow* version](https://flow.org/try/#0PTACDMBsHsHcCgCWA7ALgUwE7gIYGN0ACAMUIG95DCAKABgBpCBGASgC5n7Kbb3CH4AX3h5oyAM6pCODgBIAwjkiQAPMXoMmAPkIBeZkA)

**Comment by SamChou19815** [comment]
This is expected behavior.
