### ISSUE TITLE
flow ignores user-defined types for eval

### ISSUE THREAD

**Issue by lur2c** [facebook/flow#6363]
I have a single line of code `eval("alert(GO)");` I want to give it a type by defining the following in the flow-typed directory:

```
declare type EvalFn = string;
declare function eval(s :string): EvalFn;

```
but the output is:

```
test/src/global-1.js:1:1-4: any
test/src/global-1.js:1:1-17: any
test/src/global-1.js:1:6-16: string

```
If I change the name of the eval function to evals like evals("alert(GO)"); and change the type defs to `declare function evals(s :string): EvalFn;`, then flow dumps types as follows:

```
test/src/global-1.js:62:1-5: (s: string) => EvalFn
test/src/global-1.js:62:1-18: EvalFn
test/src/global-1.js:62:7-17: string
```

**Comment by stereobooster** [comment]
This what you can do https://flow.org/try/#0MYewdgzgLgBApgNwIYBsIwLwwBQQFzQBOAlmAOYCUeMAZgK5jBTHiYB8MA3gFAwyiRYhOBDopYWRKlwUA3LxjEaOKAE8ADnBDLho8ZgxYARPUbNwRilwV9hUOoTAxdYqAoC+8NHGt8+UAAtCEAB3GABRQmDCbCMAORBYJFoGJhYwSw9ud25sKTRsAHIkCEKqUzTwCm4gA

```ts
const evals = (s:string): function => {
  const result = eval(s);
  if (typeof result === "function") {
    return result
  } else {
    throw Error("Not a function")
  }
}
```
