### ISSUE TITLE
"Default" Props on React.StatelessFunctionalComponent not acknowledged

### ISSUE THREAD

**Issue by Josh-a-e** [facebook/flow#6366]
I'd expect (and it'd be great if) at least one of the below options to worked as a means to providing default props.

However they all come back with the same error:

```
<ComponentA/>
          ^ Cannot create `ComponentA` element because property `sayHello` is missing in props [1] but exists in object type [2].
```

(in order of personal preference)

**1st Choice** - [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnTgA7MkQDCLXEOpCCAQTABeMAAoA3mDIkAngAlqMeErBQSMMtTABfAFxgNWvQfh2ARnDgxaQ6wEolAHyqqGBgADwAJugAbgESOMIyRAqOZHZqjvqGcGAA-OxZ8GxgdmwAcnAEABboQgDmbFZhwFGxqL58AsKiYPFSSQBCxir+ikEqIWAAkJExAZOhM32JsnLA8zMtc+1AA)

```jsx
/* @flow */
import * as React from 'react';

const ComponentA = ({ sayHello = false }: { sayHello: boolean }) => (
  <div>Component A says: {sayHello ? 'Hello' : 'Nothing'}</div>
);

const ComponentB = () => (
    <div>
        <ComponentA/>
    </div>
)
```

**2nd Choice** - [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnTgA7MkQDCLXEOpCCAQTABeMAAoA3mDIkAngAlqMeGAC+ALjAateg-HMAjOHBi0hJpRc079huOagkYMmoTAEolAD5VVDAwAB4AE3QAN3CJHGEZIgUrMnM1K28jAH52Qrg2MHM2ADk4AgALdCEAczZjWOBElNQQvgFhUTA0qUyAIXcVMMVIlWiwAEgE5PC5mMXhjNk5YBXFzuWeoA)
```jsx
/* @flow */
import * as React from 'react';

const ComponentA = ({ sayHello }: { sayHello: boolean } = { sayHello: false }) => (
  <div>Component A says: {sayHello ? 'Hello' : 'Nothing'}</div>
);

const ComponentB = () => (
    <div>
        <ComponentA/>
    </div>
)
```

**3rd Choice** - [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnTgA7MkQDCLXEOpCCAQQBcVLgQB0AZQIkC1GNTJkAYgFchDdMJIwJOYTIIAeAN5gyJAJ4AJXfCUAjODg9EiEwAF8APjAAXjAAChc3Lx84GLAoKzJqcIBKGKi41DAwBwATdAA3CJspezA5Vw8yJSck7xh4MAB+dnb4NjAlNgA5OAIAC3QhAHM2MIdgcqrUHL4BYVEwGrtZACE0uLzogqKwAEgyyojT4ovt6Vk5YGuLxauVoA)

```jsx
/* @flow */
import * as React from 'react';

const ComponentA: React.StatelessFunctionalComponent<{ sayHello: boolean }> = ({ sayHello = false }) => (
  <div>Component A says: {sayHello ? 'Hello' : 'Nothing'}</div>
);

const ComponentB = () => (
    <div>
        <ComponentA/>
    </div>
)
```

**The thing that actually works** - [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqnTgA7MkQDCLXEOpCCAQTABeMAAoA3mDIkAngAlqMeGAC+ALjAateg-HMAjOHBi0hJgJRKAfKtRgwAHgATdAA3TwkcYRkiBSsyczUrfUM4MAB+dmT4NjBzNgA5OAIAC3QhAHM2Y39gYLDUNz5UCKlouQA6QOooEgBXGAIABWZsCmU1X00dLLhzHpgyalRjJsERcUko2QAhJVUPRW8VSYBIINDPSb8zlq35YEuz2ouGoA)

For reference, and I get that this is totally a workable solution, just less ideal, IMO

```jsx
/* @flow */
import * as React from 'react';

const ComponentA = ({ sayHello }: { sayHello: boolean }) => (
  <div>Component A says: {sayHello ? 'Hello' : 'Nothing'}</div>
);

ComponentA.defaultProps = {
  sayHello: false
};

const ComponentB = () => (
    <div>
        <ComponentA/>
    </div>
)
```

**Comment by Josh-a-e** [comment]
Having spent a bit longer on this, `{ sayHello?: boolean }` appears to be the (perhaps unsurprising) solution to by problems, but still, the inconsistent behaviour in the above seems to be a little weird as, to me at least, the intent behind specifying `Component.defaultProps` and default arguments  (`{ sayHello = false }`) is the same.

Thanks.

**Comment by constantin-melniciuc** [comment]
Randomly looking for something else here, but I can see that there is no prop validation in usecase 1, 2 or 3. You're inline declaring the value for the parameter which can be whatever you want and whatever type as well. The one that worked is actually performing prop validation. 

The solution with `?` is showing that the parameter is optional and the function can handle itself.

**Comment by SamChou19815** [comment]
Closing since this type is deleted
