### ISSUE TITLE
Is it possible to extend a type alias?

### ISSUE THREAD

**Issue by jamesqo** [facebook/flow#6370]
I have type aliases `A` and `B` and I need `B` to include all of the members of `A`. I've tried

```js
type A = { ... };

type B = {
    ...A,
    otherMember: string
};
```

and

```js
type B extends A = {
    otherMember: string
};
```

Neither seem to work, though. Is this a scenario supported by Flow?

**Comment by pnevyk** [comment]
Is [intersection type](https://flow.org/en/docs/types/intersections/) the solution for what you need? I tried to make an example for you [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5hRxwBcYAdgK4C2ARngE5gC+A3Omz4wAIVIUwbAIbd6AZwycAlgwDmvMADIiA1DDwZJ9MWUrTO9AESXefIA).

**Comment by Ricardo-Marques** [comment]
@jamesqo Yes you can, and it uses the syntax you tried first.

https://flow.org/try/#0C4TwDgpgBAglC8UDeAoAkAMwPZYFxQHIAjAQwCcCUBfFFUSKAIQWRSigDouYAaNqUmXwFsWSjRQBjLADsAzsAH5miVFEw5hggnzSDho8UA

If it does not work for you, you might just be using an outdated version of flow.
