### ISSUE TITLE
`check-contents` misses some (but not all) errors when `@flow` pragma is omitted

### ISSUE THREAD

**Issue by wchargin** [facebook/flow#6371]
For simple errors, `check-contents` correctly fails regardless of
whether the input stream contains `// @flow`:

```shell
$ cat a.js
const x: number = "WAT";
$ <a.js yarn flow check-contents >/dev/null 2>&1; echo $?
1
$ cat header.js
// @flow
$ cat header.js a.js | yarn flow check-contents >/dev/null 2>&1; echo $?
1
```

But some kinds of errors are only surfaced when `// @flow` is included,
even if we pass the `--all` argument:

```shell
$ cat b.js 
interface I {
  f(x: number): string;
}
class C implements I {
  f(x) {
    return x.length;
  }
}
$ <b.js yarn flow check-contents >/dev/null 2>&1; echo $?
0
$ <b.js yarn flow check-contents --all >/dev/null 2>&1; echo $?
0
$ cat header.js b.js | yarn flow check-contents >/dev/null 2>&1; echo $?
1
```

These can interact in the same file:
```
$ cat a.js b.js | yarn flow check-contents 2>&1 | grep Found
Found 1 error
$ cat a.js b.js | yarn flow check-contents --all 2>&1 | grep Found
Found 1 error
$ cat header.js a.js b.js | yarn flow check-contents 2>&1 | grep Found
Found 2 errors
```

Note that adding `all = true` to the `[options]` setting of
`.flowconfig` fixes the problem. This doesn’t seem like sufficient
justification for the behavior, though, because (1) `--all` option is
documented to “ignore absence of an `@flow` pragma”, which it clearly
does not, and (2) it is extremely surprising that `check-contents`
should ever ignore errors in its input, which it is explicitly being
asked to check!

Setup in all cases:

```shell
$ cd "$(mktemp -d)"
$ yarn init -y
$ yarn add flow-bin@0.73.0
$ yarn flow init
```

**Comment by SamChou19815** [comment]
The issue is likely fixed a long time ago
