### ISSUE TITLE
Object-based refinement doesn't work 

### ISSUE THREAD

**Issue by kangax** [facebook/flow#6375]
The following branching doesn't seem to be refined properly:

```js
type User = { x: 1 };
type Event = { nativeEvent: boolean };

const onFormChange = (model: User | Event) => {
  if (model.nativeEvent) return;
  const user: User = model;
};
```

Test case: https://flow.org/try/#0C4TwDgpgBAqgzhATlAvFA3lAHgLigRigF8BuAKFEigFEA3CAO2FQygYENgBLeux4PACMA9sIA2Edg2LkyAY2EM4zRQDFhiALYBhABZSA5tDQAKTcIAmEMXnhIoAHxr0mASlQA+DGShQuAMygzS2sAOg5uXhdgd0QIYABXRAZyXwUlZgSERFtslnMrMXJSIA

I don't see anything that could invalidate `model` being defined as `User` type, after the return statement.

**Comment by apsavin** [comment]
@kangax AFAIK your example works as expected.
You [can](https://flow.org/try/#0JYWwDg9gTgLgBAbzgYQuCA7Aph+BfOAMyjTgHIosBDAYxjIG4AoJmATzCzgFUBnLKHAC8iAD5wAHgC44ARjii8zdpzgBRAG454IhOIxUYwLZu0yARhAgAbahgVKWKrgGUYhrrqZw4AV35QMnwCADRMjkw01lS8vOoAJsAwALJYIOYCyRDxVNZwWBIwOPFxqOjYuAA8CHghcG4eAHyI3nCYAGLQIMgAFlQYAOaecAAUINlY1kEBCupauACUws0IrT7AhKMAhOPxkwB0EkuUML5QGMxrcDA9wLz7-DANRSNI-gIyu5NweAvMPkofOEgA) use exact types. See [docs](https://flow.org/en/docs/types/unions/#toc-disjoint-unions).

**Comment by apsavin** [comment]
Your `if (model.nativeEvent) return;` is not valid because `{ nativeEvent: boolean }` means that `nativeEvent` can be `false` and so this `if` is not sufficient.

**Comment by apsavin** [comment]
Sorry, I re-read the posts and I see that exact types were discussed already.

**Comment by apsavin** [comment]
But my fix works, that's strange.

**Comment by kangax** [comment]
@apsavin Thanks for looking into this. Yes, `nativeEvent` is a boolean but neither `if (typeof model.nativeEvent !== 'undefined') return;` nor `if ('nativeEvent' in model) return;` nor `if (model.nativeEvent === true) return;` work. Interesting that your "fix" works. I suppose that could be a workaround for now. I would just rather check for a single property (`nativeEvent`) identifying a type of an object rather than an arbitrary one from myriad props on the `User` which are likely to change in the future.

**Comment by apsavin** [comment]
Maybe it's better to pass `{ user }` and `{ event }` objects to the function instead of such checks.
