### ISSUE TITLE
Object.entries breaks the return type in a functional loop (map)

### ISSUE THREAD

**Issue by dmatteo** [facebook/flow#6376]
Looping over an array generated from an object literal, breaks the return type when using `Object.entries`, but works just fine when using `Object.keys` and then returning `obj[key]`.

#### Offending code (also reproduced on [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBqAhjAK4EC8YA3qmGAHZkC2AXE6wEZ4BOANPTABnDLw6jeAS0YBzQQF90AYziNRYWXgwlyeYWGoAKAJQcaYANqSZsgLoddFMAsMA+MEboMA1niwAjOZCDMzsYACcUYIMDJIcAOQAFngw8AkxLpl+WABMwbGc4QAsuZlxYokIScQYYFIGLFhgOGS8OHDCeAD8GUIKiiYA3OjAwGAAKkkNYAhwvD7CqKrqdQBupBTCjpt4lnaGYADyXABWeMoYAHQ5wkZaOrt3JiZCVyzEOEY57praTvpTJYcnZhqNxlMZgATOD6RgJDDLNQaDZ6YT5Ii7faHE7nS5XPCMMRSQEPAHPV4ASHenyMRmB-n4YFRFFBvxZeFeQA))
```js
/* @flow */

type Value = {
  num: number,
  str: string,
}

const getValues = (): { [string]: Value } => ({
  key1: {
    num: 999,
    str: 'hello',
  },
  key2: {
    num: 42,
    str: 'what is my purpose?',
  },
});

// This works
const values: Value[] = Object.keys(getValues())
  .map(key => getValues()[key]);

// This doesn't
const values2: Value[] = Object.entries(getValues())
	.map(([key, value]) => value)
```

There might be some nuances I don't get on why this brakes, but it seems to me that they should behave in the same way (they definitely return the same data).

Thanks a bunch!

**Comment by wchargin** [comment]
This is known. See comments and linked-to issues on #5663.

(I’d also love to see this changed, but I don’t think that there is any
new information in this issue.)

**Comment by mrkev** [comment]
Closing in favor of #5663
