### ISSUE TITLE
Cannot assign React.createRef() to this.[property] because inexact object type [1] is incompatible with exact RefObject

### ISSUE THREAD

**Issue by fterh** [facebook/flow#6378]
I understand that [Flow doesn't presently support](https://github.com/facebook/flow/issues/6102) React.createRef() type definitions.

From [React's source code](https://github.com/facebook/react/search?utf8=%E2%9C%93&q=RefObject&type=), I found these:

```
export function createRef(): RefObject {
  const refObject = {
    current: null,
  };
  if (__DEV__) {
    Object.seal(refObject);
  }
  return refObject;
}
```

```
export type RefObject = {|
  current: any,
|};
```

I tried using this snippet in my code, but I get an error instead:

`Cannot assign React.createRef() to this.[property] because inexact object
type [1] is incompatible with exact RefObject [2].`

**Comment by fterh** [comment]
I've updated to the latest React and Flow versions, still getting these though!

**Comment by apsavin** [comment]
Could you please reproduce it on [flow.org/try](http://flow.org/try)

**Comment by fterh** [comment]
I'm not sure how I can introduce React into the Try Flow environment, but I found a solution:

Changing;
`export type RefObject = {|
  current: any,
|};`

to:

`export type RefObject = {
  current: any,
};`

**Comment by TrySound** [comment]
Did you read the end of that issue? `createRef` api is supported for a few last versions.
https://github.com/facebook/flow/blob/master/lib/react.js#L219

**Comment by apsavin** [comment]
@fterh you can write `import React from 'react'` on [Try Flow](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4g) environment.

**Comment by im-martijn** [comment]
It would be nice if the flow documentation for refs was updated. I tried typing a ref using the createRef API today, but couldn't get it to work.

I tried something like this:
```
type Ref = { current: null | HTMLElement };

export default class SomeClass extends React.Component<Props> {
	someRef: Ref;

	constructor(props: Props) {
		super(props);
		this.someRef = React.createRef();
	}

	render() {
		return (
			<Component ref={this.someRef} />
		);
	}
}
```

This gives me an error:
Cannot create Component element because a callable signature is missing in `Ref` [1] but exists in function type [2] in property `ref`.

Where [1] refers to the Ref type and [2] refers to the creatRef function type definition in flow.

So, what did I do wrong / should I do to fix this?

**Comment by TrySound** [comment]
@im-martijn Documenting every type definition is wasting of resources. Read actual definitions. They are quite clean and always in current state.
https://github.com/facebook/flow/blob/master/lib/react.js#L189

**Comment by im-martijn** [comment]
Yeah, I did look at that, but didn't get it completely. New to flow / typing in general.

```
declare type React$Ref<ElementType: React$ElementType> =
  | {current: React$ElementRef<ElementType> | null}
  | ((React$ElementRef<ElementType> | null) => mixed)
  | string;
```

This is how I decided to use: `{ current: null | HTMLElement }`. I guess I'm not sure how to interpret `React$ElementRef<ElementType>`.

**Comment by TrySound** [comment]
React$Ref is global alias of
```
import * as React from 'react';
var a: React.Ref
```
same true for all react types.

**Comment by im-martijn** [comment]
Ah, great, thanks.

**Comment by Benjamin-Dobell** [comment]
The current flow type for `Ref` and `createRef` are incorrect, the type parameter is "specialized" as:

```
ElementType: React$ElementType
```

where we have `React$ElementType`:

```
declare type React$ElementType =
  | string
  | React$StatelessFunctionalComponent<any>
  | Class<React$Component<any, any>>;
```

This means Flow does not allow us to specify references to DOM elementes (i.e. `HTMLElement`). This is incorrect as references to DOM elements is documented behavior, https://reactjs.org/docs/refs-and-the-dom.html

**Comment by hrasoa** [comment]
`React.Ref<'div'>` is working but current returns an "unkown type":

`[flow] Cannot call `this.ref.current.focus` because property `focus` is missing in property `current` of unknown type [1]. (References: [1])`

Shouldn't it return an `HTMLElement` ?
