### ISSUE TITLE
nested type refinement not breaking after side effects

### ISSUE THREAD

**Issue by dannyharding10** [facebook/flow#6383]
After doing a type refinement on a nested value that is a disjoint union, you can refine the disjoint union to a specific type and use fields from that type, like so

```
type A = {
    type: 'A',
    value: number,
}

type B = {
    type: 'B',
    message: string,
}

type Nested = {
    ab: A | B,
}

function test(nested: Nested) {
    if (nested.ab.type === 'A') {
        console.log(nested.ab.value) // Works
    }
}
```

At this point, if you call any other functions before using the refined type, flow will throw an error, presumably because that function may have side effects.

```
function test(nested: Nested) {
    if (nested.ab.type === 'A') {
        doSomething()
        console.log(nested.ab.value) // Fails
    }
}

function doSomething() {}
```

However if you store the nested value in its own variable, do the type refinement on this new variable, then call a function with potential side effects, the type refinement is still considered valid.

```
function test(nested: Nested) {
    const ab = nested.ab
    if (ab.type === 'A') {
        doSomething()
        console.log(ab.value) // Works!! 
    }
}

function doSomething() {}
```

I don't know what the intended functionality is for these last two examples, but it seems that they should either both work or both fail.

Here is a flow try of the two examples, one failing and one succeeding https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phjb4BcYA5LXoYwDRVgCGA0nlgYBnDACcAlgDsA5pwC+6FmABCpClxYNmuPMo5cARv0FhJAVwC2BvKPmKdRVWWIAfFffxgAcnhF4AJmqU1NwGDITKnNRwGAAWNgzmVjZ2qFBmkgDGGOJwkmBQ3OIwABSSvhgBDD5+-gCU6tTiUGBlFQEAdKEdSiR9TCxsDcHUYLHcQgDK4v54AKJQUHjZbbVdBg3AwGAAYkUwQmB5MFhgCPH5ceKHMFIE12M2eFzUmXlCcDB4HfDSq5X+dZdYx1LgKBRpDLZXL5SRwPbFf5VbzteqNMBbMAASRaWDgZjA-jyzDAODMMBgYAABqEqUczBgwFIMHAmRhDoh8gA3bgSUJfdgFeBIAyiPDcADWhwmYDwAA98NkAlw3pIRDwDGpymtQlxmq1ur1+tp8EN0dRMYRJKd0lkcnkwJluBTHmKwGYhGZnSdHdwPb4aPECp9hVJpGAxRgzKJ8iJuJULHhJIyWQV9lFRpisTwhJ7E2BrE7-WzHfiYIEcDEkzlvadxlyCEIZgQ8ItluzBQYGTmwHiCU7Y3hnqMMdtxBhGIc4YzCsUwy8xhNprMFksVqFQSPVR8vj84H9unwBJttl5WbOYNGCPE3YnuGqS1dJFLqbSmRyWkpCGDUBDbdCHXGKZm1XdsSifaQGHvLA6gYLk4BmdEIJ6BwyEYKQeVuQIlEAXg3ABo9xhfyAA

**Comment by apsavin** [comment]
> it seems that they should either both work or both fail.

Why? I don't think so.
The call  `doSomething()` can't change constant `ab`, so, as you said

> the type refinement is still considered valid.

**Comment by apsavin** [comment]
Can be closed IMHO

**Comment by dannyharding10** [comment]
@apsavin if you look at the flow try I provided you will see that instead of `doSomething()`, I have put a function that actually does have side effects but flow still fails to catch the error.

In the case you mentioned, `doSomething()` can't change the constant `ab` but it can change fields on `ab`, which I imagine should invalidate the type refinement. When `ab` is stored as a constant it is still using the same reference as `nested.ab`, i.e. `nested.ab === ab`, so any code that could potentially change fields in `nested.ab` would also change those fields in `ab`.

**Comment by apsavin** [comment]
I did take a look. It's `nested` can be modified, not `ab`. Don't use `any`, it makes it harder to see the problem.

**Comment by dannyharding10** [comment]
I never responded to this issue, but you were right @apsavin! This was a misunderstanding on my part
