### ISSUE TITLE
Partners section on https://flow.org/

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#6386]
Feature request: To have a list of partners of whom are actually using Flow and with their permission add their names as contributors and users. This is similar to how typescript has a "Friends of TypeScript section" and it makes it feel as if the product isn't alone in the wilderness

http://www.typescriptlang.org/community/friends.html

If the worry is that it will look weird if there is only one or two groups at first, maybe put it behind a feature flag until you have enough big names listed on there?

**Comment by vicapow** [comment]
I would say this is a duplicate of: https://github.com/facebook/flow/issues/6282

**Comment by rickyp-uber** [comment]
Yep closing... That's been open for 29 days though so guessing partnerships aren't going to happen for a while.
