### ISSUE TITLE
Components as Methods

### ISSUE THREAD

**Issue by brigand** [facebook/flow#6391]
I've been using this pattern recently where a component is defined as a class method, allowing it to be used in JSX but also have access to the class's props.

[Try Flow | Flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugMJxYAeMWAdgBN02PDAB0bEpD78YAHmR8AngD44Abzpw4lQVigAKAJQat2nVhgBXKHzgGz5uHIHAAbisdPnMABbBUMQBJPjArQmAsJgEAXgAiLBBkYCY4uAB6T29zOT8A4NDwuAJI6PiwVgB3aAE0zK9tOXTXDy8jem0AXzMzELD4GPt1YtKBOE6TGLUHJzlgQpgGuDdkJissGPU8wLBiMECBZBhkAG0SqIEAXW7siD42X0UAcw31AyxJtW2xXYh9sTuD2eWAM52iABpOGJjlAXuIVmsPjdzPVtEY6J0gA)

```jsx
import * as React from 'react';

class C extends React.Component<any> {
  render() {
    return (
      <div>
        <this.Input field="email" />
        <this.Input field="password" />
      </div>
    );
  }
  
  Input = ({ field }) => (
    <input
      value={this.props.data[field]}
      onChange={(e) => this.props.onChange(field, e.target.value)}
    />
  )
}

```

Flow doesn't seem to like this

```
7:         <this.Input field="email" />
            ^ Cannot reference type `this` [1] from a value position.
References:
3: class C extends React.Component<any> {
         ^ [1]
8:         <this.Input field="password" />
            ^ Cannot reference type `this` [1] from a value position.
References:
3: class C extends React.Component<any> {
         ^ [1]
```

The code behaves properly with react/babel, it just seems that flow doesn't like it. While type checking it properly would be ideal, I'd be happy to just get rid of the flow error.

**Comment by SamChou19815** [comment]
now works
