### ISSUE TITLE
Buffer in class field cause Unexpected global type: PolyT

### ISSUE THREAD

**Issue by b4nst** [facebook/flow#6395]
Flow files generation with `flow gen-flow-files` fails when a field type is Buffer.

Code to reproduce:

```js
// @flow
export class Foo {
  _buffer: Buffer;
}
```

```stacktrace
Failure(\"Unexpected global type: PolyT\")")
```

It works as expected with any other type.

node version: 10.0.0
flow-bin: [0.72.0](https://registry.npmjs.org/flow-bin/-/flow-bin-0.72.0.tgz#12051180fb2db7ccb728fefe67c77e955e92a44d)

**Comment by macrozone** [comment]
i have the same error, but no Buffer. I have an Array<T> type

**Comment by SamChou19815** [comment]
The command was removed a while ago. We now have [flow-api-translator](https://www.npmjs.com/package/flow-api-translator) instead.
