### ISSUE TITLE
Flow incorrectly assumes closed-over variables are defined

### ISSUE THREAD

**Issue by zgotsch** [facebook/flow#6398]
When I use a possibly-undefined variable in a lambda, Flow forgets that it might not be defined.

```js
let x;

if (false) {
  x = 4;
}

// x.toString(); // This is a flow error
(() => {x.toString();})(); // But this isn't :(
```

https://flow.org/try/#0DYUwLgBAHg3AUHAlgMwgCmQQ2AZxASggG84JoIBeCAFngF8EB6R6AOjAHsBlMAJ0QB2AczT4YEZhAAqAC0Q4I8iJgjJgHAO4QQvXh15w0oygD5iUdtz6CRYuvlHjJAIQCukMHIXyBAckgAXGhAA

**Comment by zgotsch** [comment]
Interestingly, if `undefined` is explicitly assigned to the variable initially, this problem doesn't exist:

```
let x = undefined;

if (false) {
  x = 4;
}

// x.toString(); // This is a flow error
(() => {x.toString();})(); // This errors now!
```

https://flow.org/try/#0DYUwLgBAHhC8EFcB2ATEAzAlkkKDcAUAZuhABToCGwAziAJQQDeBE0cEALIQL5ED0-aADowAewDKYAE7YA5mXp4IgiABUAFphoRtEShHTAxAdwghp0sdIJlFcAHzMooyTPmK8Pep5VDNehZW0jpIpgCEQA

**Comment by SamChou19815** [comment]
This is indeed a limitation, but the one we have to accept to make type checking decidable

**Comment by SamChou19815** [comment]
TDZ is a non-trivial program property, so by rice's theorem, it's undecidable. Languages like Java will just reject programs when it sees things like this that might be hard to analyze, but the JS community has collectively demanded that that's too restrictive, and they want patterns like the following to work, so we decide to be more liberal on this:

```
let v;

export function init() {
 v = ''
}

export function get(): string {
  return v
}
```
