### ISSUE TITLE
Flow treats instance properties incorrectly

### ISSUE THREAD

**Issue by deecewan** [facebook/flow#6401]
I found this bug when using React, but have created a minimum example [on https://flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXAHgHEA+MAb1TDAEsziBbXALjAEEATgOwBPajQDcTMAAcBcMnACS7YYoEBhbDBgAjbBgDWvABRUAlGAC8dAG5wWAEynNpGOADtyAgK4Z1JmycPPxCouKWjMxgAJBkABYsuAB0QVzWrOxcLmDSzAlJyXIKyqrY6lo6+kYZBSnFiirEanCa2noGhsm6LB6OJnXmOQC+0tK95NgeGMRNLW1VnRmBWbwW1nRR0dKjrswNpc3lrZUdRiuca5F5ucy7t2COcADKcBzEBR4A5ibX0WB1VJZFIcbAyAaJeryRplCrtaqGcw3QFpEFgiGFCZkKYzObHBZnRE7VDDIA) that doesn't involve React at all

Essentially, Flow treats an instance property method differently to a prototype method.  This seems to occur only when generics are involved.

I'm not sure exactly what's happening, but it's almost like *different* generics by the same name are used inside the instance property-based method.

The reproducing code (you can also see in the link above) is:

```js
class Test<G> {
  items: Array<G>;
  protoIteratorCallback: (G) => void;
  
  constructor(items: Array<G>) {
   	this.items = items;
    this.protoIteratorCallback = this.protoIteratorCallback.bind(this);
  }
  
  instanceIteratorCallback = (item: G) => {}
  
  protoIteratorCallback(item: G) {}
  
  doSomething() {
    this.items.map(this.protoIteratorCallback)
    // next line fails. says `G` is not compatible with `G`
    this.items.map(this.instanceIteratorCallback)
  }
}
```

I feel like this code shouldn't be too out of the ordinary, and I can't figure out why it won't work if not for a bug.

Edit: My co-worker has just pointed out that it's broken with static properties as well. You can see the flow/try [here](https://flow.org/try/#0MYGwhgzhAEAqCmEAuAeA4gPmgbwFDWgEsl4BbCALmgEEAnWsAT3QwG5d9pkwlDhoADrQD2A+LSSMAwmBAgARmGABraAF5oACmJkqaAJTqs2AL6duvfqXhIAFsIAmMuYpXaSpPYdMcCD4QDKwtZ2hAB2AOaa3pwEoRAAdDrkCaRgApoIyAlCouKSzgpKyoYA9KXQAGZghCAQsdDxSR6JaRlZSKk29k6yRSplFQKQEIicZiZAA).

```js
class Test<G> {
  items: Array<G>;

  static propertyCallback = (item: G) => {}
  static methodCallback(item: G) {}

  doSomething() {
    this.items.map(Test.propertyCallback) // fails
    this.items.map(Test.methodCallback) // passes
  }
}
```

**Comment by idiostruct** [comment]
Here are workarounds: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAFQFNcAXAHgHEA+MAb1TDAEsziBbXALjAEEATgOwBPajQDcTMAAcBcMnACS7YYoEBhbDBgAjbBgDWvABRUAlGAC8dAG5wWAEynNpGOADtyAgK4Z1JmycPPxCouKWjMxgAJBkABYsuAB0QVzWrOxcLmDSzAlJyXIKyqrY6lo6+kYZBSnFiirEanCa2noGhsm6LB6OJnXmOQC+0tK95NgeGMRNLW1VnbxU1nYOjhlpqwx5ucyjrswNpc3lrZUdRoFZy5G70gd7YI5wAMpwHMQFHgDmJnfRMDAYB1VJZFIcbAyAaJeryRplCrtaqGcy7UFpCFQmGFCZkKYzOZnBaXVEPVDDIA), [Try Flow](https://flow.org/try/#0MYGwhgzhAEAqCmEAuAeA4gPmgbwFDWgEsl4BbCALmgEEAnWsAT3QwG5d9pkwlDhoADrQD2A+LSSMAwmBAgARmGABrKmmgBeLADdhhACaaiJUpqzYAvp269+peEgAWw-TLmKVACmJk1AShwrTn1hAGVheydCADsAc08AvAICKIgAOh9yNNIwAU8EZDShUXFJNwUlZQCAemroADMwQhAIThTHQnTM9Jy8gqRsh2dXWQqVGrqBSAhETisLIA).

```diff
- instanceIteratorCallback = (item: G) => {}
+ instanceIteratorCallback: G => void = item => {}

- static propertyCallback = (item: G) => {}
+ static propertyCallback: G => void = item => {}
```

**Comment by deecewan** [comment]
interesting. is there a known reason why they don't work?

**Comment by SamChou19815** [comment]
This now works well.
