### ISSUE TITLE
[Reproducible bug] Cannot get [object.key] because property [key] is missing in null

### ISSUE THREAD

**Issue by fterh** [facebook/flow#6403]
Reproduced here: [link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzABM4A5OfACwEtsBzMAXjAAoBDAJzoEomA+MAG8AvgG50wYGABunMNgCuMGAHkOKgEYArAFzylMMAB8hAawCmATz2LlxsAQ606wpmat6A5JXPK4nsVRZDn1lNU1dUMMTQQtrKPtHZ0D0KAVsDHxqHDAoODgWbj0Afg18mHM2bCFUMDBqKFYAQltVdW1eDnN8BQ5qqDYYXHNxOorCDU4ARjdW8O0AOjjR4jIKGnoWNIysnEKaurHusEmOACZZg3mtJasV4W5xYVQgA).

Firstly, an error attaches to line 13, where I `let bar2 = nullOrObj.key`. However, should `nullOrObj===null`, line 10 would have terminated the execution of the program. Furthermore, it is odd that line 11, which is essentially identical to line 13, does not produce the error.

Secondly, this error goes away if you swap lines 5 and 6. In fact, you can demonstrate that the above paragraph is true by modifying line 5 to `var nullOrObj: null | {key: null | string} = null;`. As you can see, line 10 does its job of preventing any access to a property on a null object.

**Comment by thehogfather** [comment]
@fterh this is related to refinement invalidations as documented [here](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations)
Another way to make the error go away would be to change line 13 to `let bar2 = bar1;` see [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzABM4A5OfACwEtsBzMAXjAAoBDAJzoEomA+MAG8AvgG50wYGABunMNgCuMGAHkOKgEYArAFzylMMAB8hAawCmATz2LlxsAQ606wpmat6A5JXPK4nsVRZDn1lNU1dUMMTQQtrKPtHZ0D0KAVsDHxqHDAoODgWbj0Afg18mHM2bCFUMDBqKFYAQltVdW1eDnN8BQ5qqDYYXHNxOorCDU4ARjdW8O0AOjjR4jIKGnoWNIysnEKaurHusEmOACY3U6mV4W5xYVQgA)

**Comment by mrkev** [comment]
Another one for https://github.com/facebook/flow/issues/2715
