### ISSUE TITLE
Destructuring union types with string literals does not work in function parameters

### ISSUE THREAD

**Issue by kristiehowboutdat** [facebook/flow#6408]
# Issue
Flow throws cryptic error messages when destructuring a union type that contains a string literal inside function parameters. However, if you destructure with the same fields inside the function body, no errors are thrown.

Reproduced using Flow 0.73.0: [Try Flow](https://flow.org/try/#0C4TwDgpgBAsiAq5oF4oG8oH1OkgOwEMBbCALigHIBBCqAXyigB90sclCTyKAhWugNwAoIQHpRUACIQAzsABOAVwDGwRfICWeAOZQtUAGaK8qjQHs8UAEZmAJiCgBaKAHcz8gNYyhyi3NfuXlCoABTA5HCIkACUwQB86EKMvnj+GNi4EJzQDKjAwgCQGgZQIRkcxCjIqNQUsWhJjFAFKTJmADYQAHTtZtohtdHCTfRCdCLiUrIKKmqaOnqWRibA5pZgBPLEMk5QtmayUAByAPLwAZ4+fsB7BzJ4wADqgcGl6ez4lfQRCEixyAkGkUSmUPlkvtUajR6o1GC0-B1ur1+oNhk1xnQgA)

```js
type MyType = { __typename: 'A' }  | { __typename: 'B' };

// Destructuring in function body - works
const works = (t: MyType) => {
    const { __typename } = t;
    if (__typename === 'A') {
    	console.log('A');
    }
}

// Destructuring in function params - does NOT work
const doesntWork = ({ __typename }: MyType) => {
    if (__typename === 'A') {
    	console.log('A');
    }
}
```

Errors
```
12: const doesntWork = ({ __typename }: MyType) => {
                          ^ string literal `B` [1] is incompatible with string literal `A` [2].
References:
1: type MyType = { __typename: 'A' }  | { __typename: 'B' };
                                                      ^ [1]
1: type MyType = { __typename: 'A' }  | { __typename: 'B' };
                               ^ [2]
```

# Expected
Behavior inside the function and inside the function parameters is the same.

# Actual
Behavior inside the function parameters throws errors, while doing the exact same destructuring is fine inside the function body.

# Related Tickets
https://github.com/facebook/flow/issues/5461
https://github.com/facebook/flow/issues/5745

**Comment by mrkev** [comment]
Yeah, this is one worth looking into. Thanks for the report and finding the related tickets 👍

**Comment by Mikoz93** [comment]
It seems to work fine when you provide a default value to the destructured property. [Try Flow](https://flow.org/try/#0C4TwDgpgBAsiAq5oF4oG8oH1OkgOwEMBbCALigHIBBCqAXyigB90sclCTyKAhWugNwAoIQHpRUACIQAzsABOAVwDGwRfICWeAOZQtUAGaK8qjQHs8UAEZmAJiCgBaKAHcz8gNYyhyi3NfuXlCoABTA5HCIkACUwQB86EKMvnj+GNi4EJzQDKjAwgCQGgZQIRkcxCjIqNQUsWhJjFAFKTJmADYQAHTtZtohtdHCTfRCdCLiUrIKKmqaOnqWRibA5pZgBPLEMk5QtmayUAByAPLwAZ4+fsB7BzJ4wADqgcGl6ez4la+19BEISLFkAkGkUSmUPlkvtUajRog0Ri0-B1ur1+oNhk1xnQgA)

**Comment by kristiehowboutdat** [comment]
Interesting, it "works" (no errors) with a default value that's not a valid string literal based on the union type: 
[Try Flow](https://flow.org/try/#0C4TwDgpgBAsiAq5oF4oG8oH1OkgOwEMBbCALigHIBBCqAXyigB90sclCTyKAhWugNwAoIQHpRUACIQAzsABOAVwDGwRfICWeAOZQtUAGaK8qjQHs8UAEZmAJiCgBaKAHcz8gNYyhyi3NfuXlCoABTA5HCIkACUwQB86EKMvnj+GNi4EJzQDKjAwgCQGgZQIRkcxCjIqNQUsWhJjFAFKTJmADYQAHTtZtohtdHCTfRCdCLiUAByAPLwAKLkAKoyWroARADC664AFhrKu3oyUHhmwFAEUABuBO0atrAISF3l+JWXyr7ytmtQwGYoAADSJIIFQWwQAw+PwXWxmWR4YAAdUCwVK6XY7xI6Iom34EWeMXiiSKJTKWKyH2qNRo0QaIxafg63V6-UGwya4zoQA)

**Comment by mrkev** [comment]
Welp, looks like a general problem with destructuring in params then

**Comment by HairyRabbit** [comment]
any update here ? 
:)

**Comment by HairyRabbit** [comment]
The code looks also not work,

```js
type Props = {
  value: boolean | string
}

function test({ value = true }: Props) {}
```

show errors:

```
5: function test({ value = true }: Props) {}
                   ^ boolean [1] is incompatible with string [2].
References:
2:   value: boolean | string
            ^ [1]
2:   value: boolean | string                      
                      ^ [2]


5: function test({ value = true }: Props) {}
                           ^ boolean [1] is incompatible with string [2].
References:
5: function test({ value = true }: Props) {}
                           ^ [1]
2:   value: boolean | string                      
                      ^ [2]
```
