### ISSUE TITLE
[Feature Request] Make it easier to specify the type of a field just once

### ISSUE THREAD

**Issue by jamesqo** [facebook/flow#6409]
I have the following Flow declaration for a POCO class:

```js
class WineFetcher implements IFetcher<Wine> {
    client: IClient;
    mode: 'all' | 'personal-only';
```

I would like to keep my code DRY and specify the type of each field only once. I just discovered it's possible to do this trick:

```js
constructor(client: typeof WineFetcher.prototype.client,
            mode: typeof WineFetcher.prototype.mode) {
    this.client = client;
    this.mode = mode;
}
```

This is pretty verbose, though. Ideally I'd just write `typeof this.client` but that isn't OK according to Flow. Can you guys consider supporting this scenario and making the syntax for this shorter? Thanks.

**Comment by SamChou19815** [comment]
Closing since Flow has much stricter type annotation requirement now.
