### ISSUE TITLE
Definition in `.js.flow` ignored

### ISSUE THREAD

**Issue by StreetStrider** [facebook/flow#6411]
Hello. I'm trying to go away from `[ignore] ; <PROJECT_ROOT>/node_modules/`. I got package [@streetstrider/rootpath](https://github.com/StreetStrider/rootpath) and `rootpath.js.flow` in it. Previously I got definitions for it in `<PROJECT_ROOT>/flow-typed/rootpath.js` where `declare module '@streetstrider/rootpath' { …` was defined.
I turned off ignore rule in my flowconfig and removed `flow-typed/rootpath.js` definition. Now, when I `import Rootpath from '@streetstrider/rootpath` the type is determined as `any` instead of proper `Rootpath$Constructor` type.

**Comment by TrySound** [comment]
@StreetStrider I think you forgot `// @flow` comment at the top of this file
https://unpkg.com/@streetstrider/rootpath@2.0.1/rootpath.js.flow

**Comment by StreetStrider** [comment]
@TrySound, thanks, Bogdan. That did the trick. But as far as I remember, previously, doc says that flow pragma is not required inside files, like in `flow-typed/*` and `.js.flow`, since they are already considered as typedefs. I can't find anything in [docs](https://flow.org/en/docs/libdefs/) right now. The doc completely miss `.js.flow` info, like it's deprecated :scratch:.

**Comment by TrySound** [comment]
Yeah, docs suck sadly.

**Comment by mrkev** [comment]
+1 😕 I'll take PR for docs, if anyone wants to contribute. Just ping me.

**Comment by StreetStrider** [comment]
This must be a person with expertise in the codebase. If someone like me would prepare a PR, he would definitely require help from some core guys. However, the docs in dire need of help.
