### ISSUE TITLE
Arraw scope narrowing do not work

### ISSUE THREAD

**Issue by Jabher** [facebook/flow#6413]
If this is a bug, please try reproducing using https://flow.org/try/ - [done](https://flow.org/try/#0MYewdgzgLgBAhjAvDAFANzgGwFwwIIBOBcAngDzQECWYA5jAD4xgCuAtgEYCmBAfAJRJeMDJgB0mLnSgALAFChIsDklSjchYuUo1aAofHRZ+AbiA)

When I try to pass *array of strings* (e.g.) into function that accepts *array of strings and numbers* I'm getting type error.

Code example:
```javascript
const a = (val: Array<string | number>) => val.length
const b = (val: Array<string>) => a(val);
```

Expected behavior: no errors, due to the logic that `Array<string>` is subset of `Array<string | number>`

Actual behavior (on flow 0.73.0): 
```
2: const b = (val: Array<string>) => a(val);
                                       ^ Cannot call `a` with `val` bound to `val` because string [1] is incompatible with number [2] in array element.
References:
2: const b = (val: Array<string>) => a(val);
                         ^ [1]
1: const a = (val: Array<string | number>) => val.length
                                  ^ [2]
```

**Comment by fishythefish** [comment]
This is expected behavior because `Array` is not covariant in its type argument. [Use a `$ReadOnlyArray` instead.](https://flow.org/try/#0MYewdgzgLgBAhjAvDAFANzgGwFwwCQBKApnACYDyYmAngIIBO9c1APNPQJZgDmMAPjDABXALYAjIvQB8ASiRSYGTADpMRHlAAWAKFCRYYpKiW4GTVuy7dZ8+OiwyA3EA)

**Comment by Jabher** [comment]
Cool! thank you a lot
