### ISSUE TITLE
if statement fails when trying to access "Node.firstChild.tagName" because "Node" doesn't have that property

### ISSUE THREAD

**Issue by CesarLanderos** [facebook/flow#6416]
Flow: `0.73.0`

Since version `0.68.0` I am getting this error on `DraftJS` because the `firstChild` property in `Node` is also typed as `Node`, and `Node` doesn't have a `tagName` property, thats in `Element`, which inherits from `Node`, all that is correct, thats how it is defined on the specifications, but getting an `Element` from `firstChild` is totally possible, at first I though of creating a PR changing the Node declaration so `firstChild` can return an `Element` or a `Node` (`firstChild: Element | Node`) but i guess thats not ok since the ECMA specs (AFAIK) doesn't mention explicitly that it could be an `Element`, only mentions that it should be the child of a node tree.

is there anything i can do to fix it?

Error:
![screen shot 2018-06-04 at 3 21 55 pm](https://user-images.githubusercontent.com/815951/40939677-0fcb2c6e-680b-11e8-8486-93472b05b7bc.png)

**Comment by CesarLanderos** [comment]
yeah totally, as far as i understand, any class can implement the `Node` interface, so anything can be returned from `firstChild`, its just... not quite anything, it depends on the class that implements the `Node` interface, as in, if we create any type of tree, lets say, a people tree, a class `Person` should implement the `Node` interface, meaning that it should have a property called `firstChild` that stores the first child of an specific node in the tree, which should also be `Person` instance.

thats why i can't think of a way to fix this without having to specify the "type of tree" that (in the draftjs case) react's `findDomNode` method returns (well, it returns a `Element` node, which has methods to get its own child `Element` nodes)

**Comment by Brianzchen** [comment]
`tagName` does not exist in `Node` - https://developer.mozilla.org/en-US/docs/Web/API/Node
But does exist in `Element` - https://developer.mozilla.org/en-US/docs/Web/API/Element
Therefore you have to first refine your type before you can check the `tagName`
```
if (t.nodeType === Node.TEXT_NODE) {
  // do something
} else if (t instanceof Element && t.tagName === 'BR') {
  // do else
}
```
