### ISSUE TITLE
Declared class property types can conflict with defined methods

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#642]
Flow treats methods and properties differently, but this can lead to confusion if a class declares a property type for a defined method:

``` javascript
/* @flow */

class Foo {
  bar: string;
  bar() { }
}

var foo = new Foo();

(foo.bar : string); // OK, but it's actually a function
(foo.bar() : void); // Error, but this is the correct code
```

**Comment by popham** [comment]
Property `bar` show up on instances as a `bar` getter+setter, while methods show up on the prototype.  The `bar` getter+setter masks the `bar` method.  Even in extension classes, the constructor's `super()` tends to populate the `bar` getter+setter, masking method overrides.  Under tryflow.org, `(Foo.prototype.bar() : void)` yields a "Function cannot be called on string" error and `(foo.__proto__.bar(): void)` yields a "Function cannot be called on Object" error.  Both of these are false negatives (barely--if `bar` touched the data of `Foo`, then a `bind` would be needed), but I would argue that Flow should make classes more opaque than ES6 does.  Coders shouldn't be goofing around with class prototypes.  The only exception I can imagine is my `extensionof` issue (#630), where the use makes up for an operator missing from ES6.

My tentative impression of ES6 9.1.8 is that an undefined property lookup results in a prototype lookup, so the following, Flow-unsupported case could be useful:

```js
class Foo {
  // Optionally override a prototype method with a local version
  bar?: () => string; // Flow rejects this :(
  bar(): string
}
```

Sorry for bumping the old issue.  I'm looking for an old issue that I vaguely recall--found this along the way.  Closable?

**Comment by calebmer** [comment]
I’m going to close, because this behavior may be correct given how prototypes work. We should revisit this when class properties are in the ECMAScript standard 👍
