### ISSUE TITLE
Crying for a help: flow always crashes on Windows! we can not work on the project!

### ISSUE THREAD

**Issue by budarin** [facebook/flow#6424]
We love Flow and dont even think about TypeScript, but we can not work with it - it crashes on every action on Windows OS.

Help please !!!

**Comment by budarin** [comment]
.flowconfig
```js
[ignore]
<PROJECT_ROOT>/dist/.*
<PROJECT_ROOT>/.idea/.*
<PROJECT_ROOT>/.git/.*
<PROJECT_ROOT>/.tmp/.*

[include]
/src/types/.*

[libs]

[options]
include_warnings=true
suppress_comment= \\(.\\|\n\\)*\\$FlowIgnore

[lints]

```

Flow's log
```
Jun  7 19:50:11.670 [info] Creating a new Flow server
Jun  7 19:50:41.721 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun  7 19:50:41.721 [error] backtrace:
Jun  7 19:50:41.721 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  7 19:50:41.721 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  7 19:50:41.721 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Jun  7 19:50:41.721 [error] 
Jun  7 19:51:11.794 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun  7 19:51:11.794 [error] backtrace:
Jun  7 19:51:11.794 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  7 19:51:11.794 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  7 19:51:11.794 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Jun  7 19:51:11.794 [error] 
```

**Comment by lukeapage** [comment]
We use windows and it doesn’t crash, so maybe it’s something specific in your code base? Can you get it down to a reproducible case?

**Comment by budarin** [comment]
Can you try to work with the [repo](https://github.com/budarin/react-ssr-bootstrap-project) in WebStorm?

**Comment by budarin** [comment]
here is the log:
```
Jun  8 22:26:17.455 [info] argv=D:\Projects\react-ssr-bootstrap-project\node_modules\flow-bin\flow-win64-v0.74.0\flow.exe server D:/Projects/react-ssr-bootstrap-project
Jun  8 22:26:17.455 [info] Creating a new Flow server
Jun  8 22:26:21.814 [info] File watcher reported 70 files changed
Jun  8 22:26:47.580 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun  8 22:26:47.580 [error] backtrace:
Jun  8 22:26:47.580 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  8 22:26:47.580 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  8 22:26:47.580 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Jun  8 22:26:47.580 [error] 
Jun  8 22:26:54.753 [error] File watcher (dfind) exited with code Invalid_exit_code (-1073740940)
Jun  8 22:26:54.753 [info] Monitor is exiting (File watcher (dfind) died)
Jun  8 22:26:54.753 [info] Broadcasting to threads and waiting 1 second for them to exit
Jun  8 22:26:55.503 [error] Tried to kill the server process (208), but it didn't die
```
and changed files in WebStorm
![default](https://user-images.githubusercontent.com/8055157/41177060-4d812438-6b6b-11e8-8238-1f784c608a5a.png)

but Flow reportes:
```
Jun  8 22:26:21.814 [info] File watcher reported 70 files changed
```
what 70 files shanged???

**Comment by budarin** [comment]
log for 2 project file changes:
```
Jun  8 22:40:23.563 [info] argv=D:\Projects\react-ssr-bootstrap-project\node_modules\flow-bin\flow-win64-v0.74.0\flow.exe server D:/Projects/react-ssr-bootstrap-project
Jun  8 22:40:23.563 [info] Creating a new Flow server
Jun  8 22:40:28.199 [info] File watcher reported 118 files changed
Jun  8 22:40:41.862 [info] File watcher reported 1 file changed
Jun  8 22:40:53.691 [error] Closing connection 'some ephemeral connection' due to uncaught exception in read loop: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun  8 22:40:53.691 [error] backtrace:
Jun  8 22:40:53.691 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  8 22:40:53.691 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  8 22:40:53.691 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Jun  8 22:40:53.691 [error] 
Jun  8 22:41:45.894 [info] File watcher reported 384 files changed
Jun  8 22:43:16.265 [error] Exception while trying to establish new connection over the socket. Closing connection: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun  8 22:43:16.265 [error] backtrace:
Jun  8 22:43:16.265 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  8 22:43:16.265 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  8 22:43:16.265 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 168, characters 2-1023
Jun  8 22:43:16.265 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 300, characters 6-374
Jun  8 22:43:16.265 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 299, characters 4-436
Jun  8 22:43:16.265 [error] 
Jun  8 22:43:16.265 [error] Exception while trying to establish new connection over the socket. Closing connection: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun  8 22:43:16.265 [error] backtrace:
Jun  8 22:43:16.265 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  8 22:43:16.265 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  8 22:43:16.265 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 168, characters 2-1023
Jun  8 22:43:16.265 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 300, characters 6-374
Jun  8 22:43:16.265 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 299, characters 4-436
Jun  8 22:43:16.265 [error] 
Jun  8 22:43:16.280 [info] File watcher reported 458 files changed
Jun  8 22:43:46.221 [info] File watcher reported 1 file changed
Jun  8 22:44:23.315 [info] File watcher reported 379 files changed
Jun  8 22:44:24.346 [info] File watcher reported 382 files changed
Jun  8 22:44:25.364 [info] File watcher reported 363 files changed
Jun  8 22:44:32.327 [info] File watcher reported 399 files changed
Jun  8 22:44:34.437 [fatal] File watcher (dfind) died: Unix.Unix_error(Unix.EPIPE, "write", "")
Jun  8 22:44:34.437 [fatal] backtrace:
Jun  8 22:44:34.437 [fatal] Raised at file "src/monitor/fileWatcher.ml", line 65, characters 55-82
Jun  8 22:44:34.437 [fatal] Called from file "src/core/lwt.ml", line 2123, characters 23-28
Jun  8 22:44:34.437 [fatal] Re-raised at file "src/monitor/fileWatcher.ml", line 61, characters 8-250
Jun  8 22:44:34.437 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 160, characters 6-317
Jun  8 22:44:34.437 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 173, characters 6-79
Jun  8 22:44:34.437 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 247, characters 6-209
Jun  8 22:44:34.437 [fatal] 
Jun  8 22:44:34.437 [info] Monitor is exiting (File watcher (dfind) died)
Jun  8 22:44:34.437 [info] Broadcasting to threads and waiting 1 second for them to exit
Jun  8 22:44:34.465 [error] Closing connection 'server #1' due to uncaught exception in read loop: Unix.Unix_error(Unix.EPIPE, "write", "")
Jun  8 22:44:34.465 [error] backtrace:
Jun  8 22:44:34.465 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun  8 22:44:34.465 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun  8 22:44:34.465 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Jun  8 22:44:34.465 [error] 
Jun  8 22:44:34.672 [error] File watcher (dfind) exited with code Invalid_exit_code (-1073740940)
Jun  8 22:44:34.937 [info] Successfully killed the server process
```

**Comment by mrkev** [comment]
Can you use flow from the command line? If so, does it work, or is there still an error? I wonder if it's a bug on flow or WebStorm's integration with it

**Comment by budarin** [comment]
- run Flow in separate command window - it shows me some errors
- in WebStorm do some edits and Flow crashes

![default](https://user-images.githubusercontent.com/8055157/41185565-3bf8d31a-6b92-11e8-9360-8ac2768d9cc8.png)

**Comment by budarin** [comment]
Here are log for starting Flow:
- DzCzBProjectszBreact-ssr-bootstrap-project.log
```
[2018-06-12 14:43:18.227] argv=D:\Projects\react-ssr-bootstrap-project\node_modules\flow-bin\flow-win64-v0.74.0\flow.exe start --temp-dir ./.tmp/flow D:\Projects\react-ssr-bootstrap-project
[2018-06-12 14:43:18.305] Initializing Server (This might take some time)
[2018-06-12 14:43:18.305] executable=D:\Projects\react-ssr-bootstrap-project\node_modules\flow-bin\flow-win64-v0.74.0\flow.exe
[2018-06-12 14:43:18.305] version=0.74.0
[2018-06-12 14:43:18.305] Parsing
[2018-06-12 14:43:21.081] Building package heap
[2018-06-12 14:43:21.081] Loading libraries
[2018-06-12 14:45:58.369] Resolving dependencies
[2018-06-12 14:46:02.222] to_merge: Focused: 28, Dependents: 0, Dependencies: 0
[2018-06-12 14:46:02.222] Calculating dependencies
[2018-06-12 14:46:02.222] Merging
[2018-06-12 14:46:04.967] Done
[2018-06-12 14:46:04.967] Checked set: Focused: 28, Dependents: 0, Dependencies: 0
[2018-06-12 14:46:04.967] Server is READY
[2018-06-12 14:46:04.967] Took 166.662893 seconds to initialize.
[2018-06-12 14:46:05.404] Status: Error
[2018-06-12 14:46:05.404] Status: Error
[2018-06-12 14:46:06.137] Status: Error
[2018-06-12 14:46:07.167] Status: Error
[2018-06-12 14:46:08.197] Status: Error
[2018-06-12 14:46:10.755] Status: Error
[2018-06-12 14:46:49.833] Killing the worker processes
Monitor is exiting with status Dfind_died (File watcher (dfind) died)
```

- DzCzBProjectszBreact-ssr-bootstrap-project.monitor_log
```
Jun 12 14:43:18.149 [info] argv=D:\Projects\react-ssr-bootstrap-project\node_modules\flow-bin\flow-win64-v0.74.0\flow.exe start --temp-dir ./.tmp/flow D:\Projects\react-ssr-bootstrap-project
Jun 12 14:43:18.149 [info] Creating a new Flow server
Jun 12 14:43:20.739 [info] File watcher reported 70 files changed
Jun 12 14:43:29.131 [info] File watcher reported 591 files changed
Jun 12 14:45:59.149 [error] Exception while trying to establish new connection over the socket. Closing connection: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun 12 14:45:59.149 [error] backtrace:
Jun 12 14:45:59.149 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun 12 14:45:59.149 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun 12 14:45:59.149 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 168, characters 2-1023
Jun 12 14:45:59.149 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 300, characters 6-374
Jun 12 14:45:59.149 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 299, characters 4-436
Jun 12 14:45:59.149 [error] 
Jun 12 14:45:59.149 [error] Exception while trying to establish new connection over the socket. Closing connection: Unix.Unix_error(Unix.ECONNRESET, "write", "")
Jun 12 14:45:59.149 [error] backtrace:
Jun 12 14:45:59.149 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun 12 14:45:59.149 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun 12 14:45:59.149 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 168, characters 2-1023
Jun 12 14:45:59.149 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 300, characters 6-374
Jun 12 14:45:59.149 [error] Re-raised at file "src/monitor/socketAcceptor.ml", line 299, characters 4-436
Jun 12 14:45:59.149 [error] 
Jun 12 14:46:00.179 [info] File watcher reported 100 files changed
Jun 12 14:46:26.278 [info] File watcher reported 590 files changed
Jun 12 14:46:49.818 [fatal] File watcher (dfind) died: Unix.Unix_error(Unix.EPIPE, "write", "")
Jun 12 14:46:49.818 [fatal] backtrace:
Jun 12 14:46:49.818 [fatal] Raised at file "src/monitor/fileWatcher.ml", line 65, characters 55-82
Jun 12 14:46:49.818 [fatal] Called from file "src/core/lwt.ml", line 2123, characters 23-28
Jun 12 14:46:49.818 [fatal] Re-raised at file "src/monitor/fileWatcher.ml", line 61, characters 8-250
Jun 12 14:46:49.818 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 160, characters 6-317
Jun 12 14:46:49.818 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 173, characters 6-79
Jun 12 14:46:49.818 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 247, characters 6-209
Jun 12 14:46:49.818 [fatal] 
Jun 12 14:46:49.818 [info] Monitor is exiting (File watcher (dfind) died)
Jun 12 14:46:49.818 [info] Broadcasting to threads and waiting 1 second for them to exit
Jun 12 14:46:49.849 [error] Closing connection 'server #1' due to uncaught exception in read loop: Unix.Unix_error(Unix.EPIPE, "write", "")
Jun 12 14:46:49.849 [error] backtrace:
Jun 12 14:46:49.849 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Jun 12 14:46:49.849 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Jun 12 14:46:49.849 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Jun 12 14:46:49.849 [error] 
Jun 12 14:46:49.958 [error] File watcher (dfind) exited with code Invalid_exit_code (-1073740940)
Jun 12 14:46:50.333 [info] Successfully killed the server process
```
Server the most of time dies

**Comment by budarin** [comment]
@lukeapage 
could you share your tools  & stack of technologies you use?
could you try my repo in your environment? here is my [repo](https://github.com/budarin/react-ssr-bootstrap-project)

**Comment by lukeapage** [comment]
Sorry I'm not on the flow project, I just noticed this bug

**Comment by mrkev** [comment]
A minimal sample repo that can reproduce the issue it'd be helpful, but the fact you mention this fails even with your Hello World project leads me to suspect it might be an issue with web storm. I'd suggest trying vscode or atom, and post any updates.

**Comment by mrkev** [comment]
In fact, closing since this seems to have been reported already at https://github.com/facebook/flow/issues/6424 and that issue has a few more followers. Discussion should be kept going there. Note: that thread also mentions Webstorm, which furthers my suspicion that this might be an issue with the editor.

**Comment by kumarharsh** [comment]
@mrkev it's not just an issue with Webstorm though - the vscode extension is unusable in Windows to the point of driving me to desperation to try anything - I bought an SSD just to make flow run faster (!!!) - it didn't help much 😂

For reference, I have project with >40k files, and Flow + Windows is just a slow chronic pain which hasn't gone away.

See [this](https://github.com/flowtype/flow-for-vscode/issues/58#issuecomment-284037133), [this](https://github.com/flowtype/flow-bin/issues/98#issuecomment-380788279), and [this](https://github.com/facebook/flow/pull/5659) for previous reports

I apologize for the incessant complaining 😂 - I tried to contribute via a fork (https://github.com/jbachhardie/vscode-flow-ls) which worked on the node-based flow-langauge-server and had got it to work with Windows (subfolder support as well as multi-workspace support). I was about the submit some PRs to flow-language-server project but then I learnt that flow-language-server was slated to be removed and LSP capability would be rolled into flow - so I didn't push the PRs. But even though most of it was working, it definitely seemed like it was flow itself which was the cause of most of the issues under Windows (btw, thanks for https://github.com/facebook/flow/pull/6573 - it might be helpful in making more headway in improving the flow binary for Windows). Sadly, I don't have enough time to learn OCaml to be able to contribute in any meaningful way in code, hence the complaining.

**Comment by mrkev** [comment]
Yeah, my suspicion is probably incorrect. The most common denominator in these issues seems to be Windows and an issue with `lwt`. I mean, after all Windows is a completely different OS so it makes sense that IPC be hard to generalize between platforms. 

Let see how things progress with LSP.

**Comment by nifgraup** [comment]
@mkrev "closing since this seems to have been reported already at #6424". That is this issue.

**Comment by goodmind** [comment]
@mrkev what issues you wanted to point?

**Comment by mrkev** [comment]
LOL

Lets keep this one open. I'm not sure which one I was referring to.

**Comment by icharge** [comment]
I'm experiencing this too.

**Comment by kumarharsh** [comment]
I have a feeling that flow will play *very* well with the upcoming WSL2 (already in Windows Fast Ring). Combined with VSCode's WSL Remote plugin, I think most of these issues might become redundant as flow will start running on Windows without having to ever support NTFS or Windows IPC. I'd still want flow to natively support Windows, but as a programmer I'll be more than happy/relieved to take this for now.

Has anyone tried this yet?

**Comment by goodmind** [comment]
Can someone explain how to reproduce this issue?

**Comment by kumarharsh** [comment]
From what I've seen, it's non-deterministic (https://github.com/flowtype/flow-bin/issues/98#issuecomment-380788279), but it's pretty easy to run into this when working on medium to large projects. Just make some edits, and save the file to trigger flow, and after some edits you'll see the computer's performance drop.

**Comment by icharge** [comment]
Try to reproduce like me.
I'm clone https://github.com/electron-react-boilerplate/electron-react-boilerplate/ and then use yarn install & run

run with `yarn dev` and then try to edit several files. 


![image](https://user-images.githubusercontent.com/1619007/61228999-8cec5980-a751-11e9-8417-86d10e96f0de.png)

**Comment by williampayne23** [comment]
I'm still encountering this issue on a windows system for a medium sized react project running flow through VSCode.

**Comment by lukeapage** [comment]
I have to keep task manager open and kill the server because it hangs with several processes open and 0% cpu usage. After killing a few tasks and re starting the server it restarts. It’s very likely to break if I change branch so lots of files change.

**Comment by SergioMorchon** [comment]
I'm experiencing this since the first time I had tu use Flow :( (almost 1 year)
The same issue with the file watcher:
```
Aug 23 11:26:21.117 [info] File watcher reported 1 file changed
Aug 23 11:26:46.249 [fatal] File watcher (dfind) died: Unix.Unix_error(Unix.EPIPE, "write", "")
Aug 23 11:26:46.249 [fatal] backtrace:
Aug 23 11:26:46.249 [fatal] Raised at file "src/monitor/fileWatcher.ml", line 79, characters 55-82
Aug 23 11:26:46.249 [fatal] Called from file "src/core/lwt.ml", line 2102, characters 23-28
Aug 23 11:26:46.249 [fatal] Re-raised at file "src/monitor/fileWatcher.ml", line 72, characters 8-356
Aug 23 11:26:46.249 [fatal] Re-raised at file "src/monitor/fileWatcher.ml", line 89, characters 6-184
Aug 23 11:26:46.249 [fatal] Re-raised at file "src/monitor/flowServerMonitorServer.ml", line 221, characters 6-134
Aug 23 11:26:46.249 [fatal] 
Aug 23 11:26:46.249 [info] Monitor is exiting (File watcher (dfind) died)
Aug 23 11:26:46.249 [info] Broadcasting to threads and waiting 1 second for them to exit
Aug 23 11:26:46.278 [error] Closing connection 'server #1' due to uncaught exception in read loop: Unix.Unix_error(Unix.EPIPE, "write", "")
Aug 23 11:26:46.278 [error] backtrace:
Aug 23 11:26:46.278 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 630, characters 38-65
Aug 23 11:26:46.278 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 545, characters 17-28
Aug 23 11:26:46.278 [error] Re-raised at file "src/monitor/connections/flowServerMonitorConnection.ml", line 152, characters 6-230
Aug 23 11:26:46.278 [error] 
Aug 23 11:26:46.707 [error] File watcher (dfind) exited with code Invalid_exit_code (-1073740940)
Aug 23 11:26:46.749 [info] Successfully killed the server process
```

**Comment by SergioMorchon** [comment]
@goodmind In general, I can reproduce it by commiting changes in a repo. Nothing special, also inconsistent, but just that.
I use the Visual Studio Code git integration to commit stuff.
Also when pulling changes (nothing that affects flowconfig nor related to flow, just some small code change) also use to kill it.
Our repo has about almost 4k files

**Comment by goodmind** [comment]
@SergioMorchon Sorry I don't have Windows machine currently, so can't look into it

**Comment by goodmind** [comment]
@mroch can you look into this? `dfind` throws `EPIPE` on Windows

**Comment by goodmind** [comment]
https://github.com/facebook/flow/blob/6edb1fd7b5cd794c6718272d0ee0800464a47707/src/monitor/fileWatcher.ml#L69-L80

**Comment by lukeapage** [comment]
Is it just me or is 105.2 much more stable? I haven't seen it crash yet, when 104.0 crashed constantly.

**Comment by icharge** [comment]
After I try to **Restart Client** for several time. then I got **BSOD** (Blue Screen of Death). That's not good.
I'm not sure this is helpful but this is what I found.

Event Viewer:
I got bugcheck this is log from BSOD
![image](https://user-images.githubusercontent.com/1619007/65389544-a62d0a00-dd81-11e9-884b-3df575d33c93.png)

```The computer has rebooted from a bugcheck.  The bugcheck was: 0x00000050 (0xffffde006c76015c, 0x0000000000000000, 0xfffff80153cc6ff1, 0x0000000000000002). A dump was saved in: C:\WINDOWS\Minidump\092219-8687-01.dmp. Report Id: db21d393-0fa5-48cf-830c-73267fed70f4.```
**0x00000050** is **PAGE_FAULT_IN_NONPAGED_AREA**

And then I open Dump file with **WinDbg Preview** from Windows Store (WinDbg can inspect that dump file)

![image](https://user-images.githubusercontent.com/1619007/65389643-a8439880-dd82-11e9-83a8-72cbf219416b.png)

I found **aswSnx**. This is an Avast Antivirus's Driver file and now I try to disable antivirus for a while.

**Comment by aceHubert** [comment]
any solutions here, getting this problem too

**Comment by rob2d** [comment]
Also immediately noticed this. I understand that certain devs may not use Windows, but it's used by 1/3 of software developers -- many times because our IT departments require it, or because we want to mimic our real world customer usage. Windows is also used by over 90% of consumers today with personal computers (non mobile). To just breeze by something as huge as this problem as this is a little bit short sighted IMHO and possibly not helping as Typescript is becoming ubiquitous -- really do not like the enforced/mandatory typed nature of Typescript but the fact that it works out of the box on VSCode is having me reconsider this library lately.

**Comment by icharge** [comment]
I'm quit from flow right now. So use Typescript is better.

**Comment by aleccaputo** [comment]
running into this as well right now with webstorm although it does seem to work on the command line
`Jan 16 08:34:39.859 [info] lazy_mode=off
Jan 16 08:34:39.859 [info] arch=classic
Jan 16 08:34:39.859 [info] abstract_locations=off
Jan 16 08:34:39.859 [info] max_workers=12
Jan 16 08:34:39.859 [info] Creating a new Flow server
Jan 16 08:34:40.912 [info] Server still initializing -> hangup. server_status=Server is initializing (parsed files 6000) watchman_status=Dfind file watcher is ready
Jan 16 08:34:41.913 [info] Server still initializing -> hangup. server_status=Server is initializing (parsed files 11836) watchman_status=Dfind file watcher is ready
Jan 16 08:34:42.914 [info] Server still initializing -> hangup. server_status=Server is initializing (parsed files 11836) watchman_status=Dfind file watcher is ready
Jan 16 08:34:43.916 [info] Server still initializing -> hangup. server_status=Server is initializing (resolving dependencies) watchman_status=Dfind file watcher is ready
Jan 16 08:34:44.918 [info] Server still initializing -> hangup. server_status=Server is initializing (resolving dependencies) watchman_status=Dfind file watcher is ready
Jan 16 08:34:45.919 [info] Server still initializing -> hangup. server_status=Server is initializing (resolving dependencies) watchman_status=Dfind file watcher is ready
Jan 16 08:34:46.922 [info] Server still initializing -> hangup. server_status=Server is initializing (merged files 0/11 (0.0%)) watchman_status=Dfind file watcher is ready
Jan 16 08:39:32.302 [error] Closing connection 'server #1' due to uncaught exception in command loop: Unix.Unix_error(Unix.EPIPE, "write", "")
Jan 16 08:39:32.302 [error] backtrace:
[2020-01-16 08:39:32.301] Uncaught async exception. Exiting
    Exception: Lwt_stream.Closed
    Backtrace:
        Raised at file "src/common/lwt/lwtLoop.ml", line 54, characters 17-93
Uncaught async exception: Lwt_stream.Closed
Raised at file "src/common/lwt/lwtLoop.ml", line 54, characters 17-93

Jan 16 08:39:32.302 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 685, characters 39-67`

**Comment by lukeapage** [comment]
I disabled webstorm using flow by removing the flow path in webstorm config and flow stopped hanging completely..

**Comment by nifgraup** [comment]
Here are three things that helped us with using Flow on Windows:

1. Disable the dfind file watcher as it is unreliable on Windows.
```
[options]
file_watcher=none
```
We use Webpack in watch-mode and wrote a plugin to run `flow force-recheck` when files are changed/added.

2. `[ignore]` files to speed startup. That includes nodes_modules (aside from the few dependencies written in flow), generated files, json, etc.

3. Upgrade to Flow 0.110.1 to get instant feedback in editor (VS Code).

**Comment by HIMISOCOOL** [comment]
> 1. Disable the dfind file watcher as it is unreliable on Windows.
> 
> ```
> [options]
> file_watcher=none
> ```

I am testing also using the flag
```
file_watcher=watchman
```
failing any improvement I will use `none`

**Comment by aheggie** [comment]
noting that I have this issue on what has got to be definitionally the tiniest possible code base

started a new react app this week with 'create-react-app'
added flow following the docs (version is 0.172.0)
have added nothing else to the app

flow server crashes on every git action in the console (add, commit, push, etc.)

also just freely crashes after about 3-5 minutes of idling doing nothing

exit message is "Monitor is exiting with status Dfind_died (File watcher (dfind) died)"

i will try the [options]file_watcher=none as above and report back

**Comment by mroch** [comment]
we've made a lot of Windows fixes this year (starting in March or April, so try again @aheggie!). if there are still issues, please file new issues. the .log and .monitor_log files would be most helpful!
