### ISSUE TITLE
Exact object spread too lax

### ISSUE THREAD

**Issue by rattrayalex-stripe** [facebook/flow#6425]
Copying from @valscion in https://github.com/facebook/flow/issues/2405#issuecomment-379178749

```jsx
// @flow
type A = {| a: string |};
type B = { b: string };
type C = {| c: string |};

declare var a: A;
declare var b: B;
declare var c: C;

var b: B = { b: 'foo', j: 'I am an extra property!' };

const d = { ...a };
const e = { ...b };
const f = { ...a, ...b };
const g: { a: string, b: string } = { ...a, ...b };
// This case SHOULD trigger an error, but it does not!!
const h: {| a: string, b: string |} = { ...a, ...b }; 
// This case should not trigger an error
const i: {| a: string, c: string |} = { ...a, ...c };
```

[Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A8+WUAGFhpUAGMJDFuy69EAE0yro5etgBuJitRy8DRk+cvjQA24eOnQF+muoLd3mLUQoREQaAA5JCwsBEANKAAVtQRAJIUALYUzKCYAB4M5KDo9LBY9GgAhBEyuqqwzHSgesqgAHQdRbL1jci5rR1torWIPU2QA50Jg8PdDU2s1GFUtJpsCc6SWjKTbeTTHbO8IKAAKgAWjDRq5DTYAMoAEgDyAKoAMgAioJqsrJg+cg5AGlegbACufUYfT0sEw12YsGQlUqo3mfXOSzIKy263CuO0nF2+3ah1qoEQJwuVxud1o51g4OgLURfV+-0BwPooLRvVAjCxVlWUlYCXUwu2XGJBzaqlqQA)

cc @mrkev

**Comment by mrkev** [comment]
Sweet, thanks for opening this issue. For reference, here is a minimal example of the error: [Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAhgFygDOyATgJYB2A5qAL4DcKG2AQgcVAAjSjQYt2XRABNMAY2ila2AG5KylHFzW1hlfoRIjQAckixYJgDSgAVpRMBJMgFsyjUJgAedUqHS0sFi0aACEJpKIiCCgACoAFvRUoHKkVNgAygASAPIAqgAyACKgdPTMzJi6pB5VgbQ2QgCuyKD0rdKwmMmMsMihoYhysIw0oPGURAA+GtRlLI2i86xTbAIkAHRbpDZbG0KSoEA).

**Comment by wchargin** [comment]
First bad commit is 3ff1fba844b6df378f4bab27caa7dd7023ff48d1.

**Comment by bwestergard** [comment]
[Another manifestation](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagOKYHaYBOAhtKALygDeAPoqKCQPwBco+ArgLYBGxAGgahebDj35EhjAMZiAgkVKoAPAGdkRAJb4A5gD5EtAL6IUGbAGUsMrZC0zKNeoxLsufQcN7uJX2QpKJKoa2nqGJmYysPgaoESYMgBKmPaETgAUAB7seISk0ACU7NaJdg6U+qAZ1AB09VnGhUA) of what I believe is the same problem. Problem appears between `v0.69.0` and `v0.70.0`.

**Comment by AlexEvanczuk** [comment]
Hi @rattrayalex-stripe !!

We are running into this issue and are wondering if there is any progress to get a fix for this merged in.

Hope all is well,
Alex

**Comment by mrkev** [comment]
Ah, good ol' spread.

Objects are getting a bit of an overhaul that will manifest in a number of spread, class, etc. related issues being fixed. It's slowly coming about, but yeah, people are aware spreads are a little broken right now (especially with exacts).

**Comment by esbenp** [comment]
Sounds good @mrkev - is there an umbrella issue or something for this where we can follow progress and what is being tinkered with?

**Comment by mrkev** [comment]
Unfortunately not that I know of /:

**Comment by oonsamyi** [comment]
@valscion
1) Why does this case should have an error?

> ```javascript
> type A = {| a: string |};
> type B = { b: string };
> declare var a: A;
> declare var b: B;
> // This case SHOULD trigger an error, but it does not!!
> const h: {| a: string, b: string |} = { ...a, ...b };
> ```

`{| a: string, b: string |}` is a supertype of `{ a: string, b: string }`, so using `h` variable will be safe. 

This case can be compared with next:
```javascript
const h: {} = { a: '', b: '' };
```
You're expanding `{ a: string, b: string }` type to {}`.
The converse is wrong: we aren't allowed to narrow the type:
```javascript
const h: { a: string, b: string, c: string } = { a: '', b: '' }; // has error
```
because `{ a: string, b: string, c: string }` is a subtype of  `{ a: string, b: string }`.

Another example:
```javascript
const a: number = 1
const h: string | number = a;
```
`string | number` is a supertype of `number`. It is safe because below in your code you can refine type:
```javascript
if (typeof h === 'string') { /* to do something with string */ }
```
2) Also this case:
> ```javascript
> // This case should not trigger an error
> const i: {| a: string, c: string |} = { ...a, ...c };
> ```
doesn't have errors now (check [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxUACNqdJm1A8+WUAGFhpUAGMJDFuy69EAE0yro5etgBuJitRy8DRk+cvjQA24eOnQF+muoLd3mLUQoREQaAA5JCwsBEANKAAVtQRAJIUALYUzKCYAB4M5KDo9LBY9GgAhBEyuqqwzHSgesqgAHQdRbL1jci5rR1torWIPU2QA50Jg8PdDU2s1GFUtJpsCc6SWjKTbeTTHbO8IKAAKgAWjDRq5DTYAMoAEgDyAKoAMgAioJqsrJg+cg5AGlegbACufUYfT0sEw12YsGQlUqo3mfXOSzIKy263CuO0nF2+3ah1qoEQJwuVxud1o51g4OgLURfV+-0BwPooLRvVAjCxVlWUlYCXUwu2XGJBzaqlqQA), please).

**Comment by wchargin** [comment]
@oonsamyi,

> 1. Why does this case should have an error?
> 
> > ```js
> > type A = {| a: string |};
> > type B = { b: string };
> > declare var a: A;
> > declare var b: B;
> > // This case SHOULD trigger an error, but it does not!!
> > const h: {| a: string, b: string |} = { ...a, ...b };
> > ```

Beceause `b` may be `{ b: "hi", c: "uh oh" }`, in which case `h` will
have an attribute `c` that is not listed in its exact object type. This
is unsound.

> `{| a: string, b: string |}` is a supertype of `{ a: string, b: string }`, so using `h` variable will be safe.

No: the opposite is true. It is a _subtype_. [Observe:][1]

```js
// @flow
type A = {| a: string |};
type B = { a: string };
declare var a: A;
declare var b: B;
(a: B);  // OK (good)
(b: A);  // error (good)
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeAPqAIYBcoAzsgE4CWAdgOagkC+A3ChtgCECxCtTpM2oHogAmmAMbRy9bADdlo3LzmLlajQCNqA3gAoqoAQEpuoUCFAB5ANKhTrWLBlXEpo7hs7B0x6elh6Nw8vHyA

> 2. Also this case:
> 
> > ```js
> > // This case should not trigger an error
> > const i: {| a: string, c: string |} = { ...a, ...c };
> > ```
> 
> doesn't have errors now

It never did; this was an example of Flow behaving correctly.

**Comment by wchargin** [comment]
> This is unsound.

And, to be more explicit, [this yields `coerce`][1]:

```js
// @flow
function coerce<T, U>(t: T): U {
  type Box = {| +isA: true, +t: T |} | {| +isB: true, +b: string |};
  const box: Box = {
    isA: true,
    t: t,
    ...({ isB: true }: {})
  };
  if (box.isB && box.b === undefined) {
    return (box: empty).t;
  }
  throw new Error("Unreachable.");
}
const twelve: number = coerce("twelve"); // no type error!
twelve.toFixed(); // runtime error!
```

(Typechecks, but fails at runtime, on Flow v0.85.0 and `master`.
Introduced in v0.70.0.)

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaBrAKYBOGxAPACoA0oAqgHwAUWAXKNQJScOgBvRKFBYAngAdioAEKwAHqAC8ggD6gA1DgDOAQU5ZSKYvQ0cuoVQF9LazTpkGjJzQCNO2wzjQBzS1YBuYUJ8T1BXBU45RRUhEREdfVFnWmCRcyxU+NAAOjyWAVAHJ2NQK04BK25gwOCcSFAWCPkch1AAMnbwhRzXZSUVdAATYkhvYiHuQTTQUmIsFFICJsjQYgBbCXFuHKwgkStgrAALUgRQNGJ4UABRUjPSFgAiBjQ5gEMMY-fXaGIcp7cIKHIhoMJYeDEaAAN2InDQKHWrjIyhCZAozwhUNhgICoBAF1gokk0jIDwAhIgsTD-lhYAAxHDyCYsIH4sBGNC4dak+6wUiUoA

**Comment by wchargin** [comment]
> `ObjectB` is a subtype of `ObjectA` => `ObjectA` is a supertype of `ObjectB`:
> 
> ```js
> type ObjectA = { foo: string };
> type ObjectB = { foo: string, bar: number };
> 
> let objectB: ObjectB = { foo: 'test', bar: 42 };
> let objectA: ObjectA = objectB;
> ```


Yes: in that example, `ObjectB` is indeed a subtype of `ObjectA`.

> Can I said same about exact type?
> 
> ```js
> type ObjectA = {| foo: string |};
> type ObjectB = { foo: string, bar: number };
> ```


No: in that example, `ObjectB` is _not_ a subtype of `ObjectA`.

Please recall what it _means_ for `U` to be a subtype of `T`: it means
that every value of type `U` is also a value of type `T`. There are
values of type `ObjectB` that are not of type `ObjectA`, and in fact
there are values of type `ObjectA` that are not of type `ObjectB`, so
neither is a subtype (or supertype) of the other.

**Comment by oonsamyi** [comment]
Thank you!
Yes, I agree:
> There are values of type `ObjectB` that are not of type `ObjectA`

But I don't understand this assertion:
> there are values of type `ObjectA` that are not of type `ObjectB`

`ObjectA` has only prop foo, that is string, but `ObjectB` has it too.
In accordance with
> U to be a subtype of T: it means that every value of type U is also a value of type T

`ObjectA` is a subtype of `ObjectB`.

**Comment by wchargin** [comment]
> But I don't understand this assertion:
> 
> > there are values of type `ObjectA` that are not of type `ObjectB`

The value `{ foo: "hello" }` is of type `ObjectA` but not `ObjectB`, [as
you can see in Flow Try][1].

Therefore, `ObjectA` cannot be a subtype of `ObjectB`.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagPICMArTAY2QEFQBeUAbwB9RJZYAuUAZ2QCcBLAOwDmoOgF8A3CgzZ8RUgCEqtRszadeggDSg8AQy5s+AVwC2eTF1DjEiABQ1lrUACIAFpmhwnltjJLkAlGKgoCC4ANK29kyOru6e3riEfnKBwaHmXLD6oHywyKA6fImyyHKIQA

**Comment by SamChou19815** [comment]
This now works
