### ISSUE TITLE
Parser error: Non-default imports must always have a specifier!

### ISSUE THREAD

**Issue by gaearon** [facebook/flow#645]
Running Flow 0.13.1:

```js
/* @flow */

import './sideEffect';
alert('lol');
```

Flow says:

```
Failure("Parser error: Non-default imports must always have a specifier!")
```

but it's a [valid](http://babeljs.io/repl/#?experimental=false&evaluate=false&loose=false&spec=true&code=%2F*%20%40flow%20*%2F%0A%0Aimport%20'.%2FsideEffect'%3B%0Aalert('lol')%3B%0A) ES6 import without a binding.

**Comment by samwgoldman** [comment]
@jeffmo fixed this in [a recent commit](https://github.com/facebook/flow/commit/9345927d449493530ddc8a4c24cdb07ec35ad9c3#diff-039977f8ee26db7e23ce7216574c735dR271), but it hasn't made its way into a release yet. Thanks for the report!

**Comment by gaearon** [comment]
Lol, the import was even called the same way in the test.
Thanks!
