### ISSUE TITLE
Issues building when using flow and react context

### ISSUE THREAD

**Issue by chrisdrackett** [facebook/flow#6457]
I'm trying to add flow types to context in the following form:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK2wB2pfAGF+uKgA98AXkqdcAOlodiYkXzGSAPKzGDWoAD6gAbrBQATAHwAKAJRA

flow says that everything is fine, but when I try and build my app I get a `SyntaxError: Unexpected token` right after `void>` (also it messes up syntax highlighting in my editor). I understand this might not be an issue with flow, but I'm not sure what is causing this :)

**Comment by apsavin** [comment]
Who reports the error? Babel? If so, it (maybe) means that the problem is in the babel plugin for flow types.

**Comment by chrisdrackett** [comment]
right now I'm using storybook. I'll dig in this evening some more and see if I can figure out what is going on

**Comment by sgb-io** [comment]
Also experiencing this, did you resolve it @chrisdrackett?

**Comment by sgb-io** [comment]
Upgrading `react-scripts` solved it for me.

**Comment by chrisdrackett** [comment]
I forgot to come back here and follow up, but I did get it working. I assume upgrading `react-scripts` or similar solved it for me as well
