### ISSUE TITLE
Flow server restarting when using Visual Studio 2017

### ISSUE THREAD

**Issue by KrzysztofLen** [facebook/flow#6463]
There's a problem using flow with Visual Studio. After changing file(.js or .jsx extension) with flow and save it, process flow.exe have been killed. Probably it's because of saving file by editor itself. Visual Studio create temporary file when changing something and after save it deleteting old one and replace it by temporary.
The issue with that is long time to wait , because everytime flow must restart and initialize new server over again.  In other editors issue not detected.

**Comment by michalnajman** [comment]
Confirmed in VS2015 and VS2017.

**Comment by michalnajman** [comment]
When Visual Studio save file (which is under flow server observation) flow save exception to log:

Unhandled exception: Unix.Unix_error(Unix.EPIPE, "write", "")
Raised at file "src/core/lwt.ml", line 3008, characters 20-29
Called from file "src/unix/lwt_main.ml", line 42, characters 8-18
Called from file "src/server/server.ml", line 259, characters 6-54

**Comment by xZliman** [comment]
Same here, but didn't use VS2017, I was working with VS Code
> Unhandled exception: Unix.Unix_error(Unix.EPIPE, "write", "")
Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 648, characters 38-65
Called from file "src/unix/lwt_unix.cppo.ml", line 563, characters 17-28
Re-raised at file "src/server/server.ml", line 246, characters 6-77
Re-raised at file "src/server/server.ml", line 197, characters 2-191
Re-raised at file "src/server/server.ml", line 243, characters 4-363
Re-raised at file "src/core/lwt.ml", line 3008, characters 20-29
Called from file "src/unix/lwt_main.ml", line 42, characters 8-18
Called from file "src/server/server.ml", line 259, characters 6-54

**Comment by SamChou19815** [comment]
We have decent support in VSCode now. We don't plan any Visual Studio specific integration
