### ISSUE TITLE
A composition with mixed functions produces unexpected errors

### ISSUE THREAD

**Issue by honzabrecka** [facebook/flow#6465]
A composition with mixed (may or may not return promise) functions does not work as expected:

```js
/* @flow */

const a = (x: number): string => x + ''
const b = (x: string): number => parseInt(x)
const aP = (x: number): Promise<string> => Promise.resolve(x + '')
const bP = (x: string): Promise<number> => Promise.resolve(parseInt(x))

type UnaryFn<A, B> = (value: A) => B | Promise<B>

type UnaryFnP<A, B> = (value: A) => Promise<B>
  
type Comp<A, B, C> = (f: UnaryFn<A, B>, g: UnaryFn<B, C>) => UnaryFnP<A, C>

const comp: Comp<*, *, *> = (f, g) => (v) => (g((f((v: any)): any)): any)

comp(a, b)(1)
comp(aP, bP)(1) // error
comp(aP, b)(1) // error
comp(a, bP)(1)
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMwBeMACgA8AuMbAVwFsAjAUwCcBKOgjgS2wBzMgD4wVMAGowAclmYcBMCzKVaYPoKE96zdhzFgADkQ642ASWz5qXRXkJEACmup1GrTrucc4TfgsAHi1hcVJxX39AtgA6DjZcOBgANzZqaTlZeyxHFVdyd018AWEfPwDgzwNwyIqY+MTktIpTcysbO3tUfABPYzYwAFVsM16AMWwggEEAGjAAIXDKFKIYBjY6aa4jBbAAHzAoyrYgpfQ+geHRjgnsZxn5pbdV9c2wbaNjmLPRVDAwD1+oMAML+YyPRbzEHLChQOgjMaTSFLeZCBE3O5naGiHYRa5I+6QmHoXLKLBMYx0MGUoIgeYgAAFDNhUDReNEjIoKQ5lCEFDhApSdCI2F6XF0ovFkrF3QpxgoRHmLC4FAAjDlwYrnMrnKqNYpKdrlfrNUalflTaggA

Just as a note, this works in TypeScript well.

**Comment by SamChou19815** [comment]
Closing since * types are killed
