### ISSUE TITLE
Callback requires unecessary refinement

### ISSUE THREAD

**Issue by Persola** [facebook/flow#6467]
This errors:
([try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDmAhgE4AmeAdmALxgDkJF1DmuBAtnsTHY915t2+ImUpU8pfgG9UYMAGsYxAM6qAXI2YSpDADTywpPKpxwqqgJYAjKzCsYrprTuoBtALqoAvumyiAMYAFnhQskbKapqMIWEGRiZmFtZ2Dk4uYIIwXr7+HGD4pKoW-AAUbpLSAD5gcVAAlOiBKRhEJlgAEsRWxeU4WkUlVA10AHxgcgomGACupDQ4AHRJ5pa29o7OqkucxDhlYAD642AAjGANANx5QA))
```
/* @flow */

type garden = 'garden'
type meal = 'meal'

type gardener = {
  klass: 'gardener',
  responsibilities: garden[]
}

type chef = {
  klass: 'chef',
  responsibilities: meal[]
}

type person = (gardener | chef)

const greyHairs = (p: person) => {
  return p.responsibilities.map( _ => 1 );
}
```

I understand (from #6464) that the call to `map` invalidates the type of `_` inside the callback, but I thought Flow wouldn't complain unless there's some use of the typed variable that has the potential to throw JS errors (?).

It's fixed it by [refining the disjoint union](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDmAhgE4AmeAdmALxgDkJF1DmuBAtnsTHY915t2+ImUpU8pfgG9UYMAGsYxAM6qAXI2YSpDADTywpPKpxwqqgJYAjKzCsYrprTuoBtALqoAvumyiAMYAFnhQskbKapqMIWEGRiZmFtZ2Dk4uYIIwXr7+HGD4pKoW-AAUbpLSAD5gcVAAlOiBKRhEJlgAEsRWxeU4WkUlVA10AHxgcgpW4WU4AHRR6nS09Ezi1HqjUwrGeBgArqQ0C0nmlrb2js6q85zEOGVgAPrjYACMYA0A3EY+YHgYKoCDsFCZDsdCvMzilLukbncHk9XrQJp8fn88kA) right before the call to `map`, but adding this doesn't actually give any more assurance about the types than having `p` typed as `person` in the first place.

In case using `map` this way seems unmotivated, it's true that in my actual use case the callback references the array elements. But it just passes each into a function which accepts `(garden | meal)`. Refining also fixes that case, though again there's no functional difference.

**Comment by Persola** [comment]
I imagine this is because Flow can't assign types to a disjoint union's properties until it's been refined to a non-union type? I assumed Flow would infer `.responsibilities`'s type to be `(garden[] | meal[])`.

If that's the case, the first example just needs `.responsibilities` to be treated as `mixed[]`. In my use case, where actually `type meal = (garden | otherType)`, it just needs to simplify `(meal[] | garden[])` to `meal[]`.

**Comment by SamChou19815** [comment]
Now it seems to work.
