### ISSUE TITLE
Unresolvable missing type annotation since 0.70.0

### ISSUE THREAD

**Issue by mikewoudenberg** [facebook/flow#6470]
I'm working on a sizeable project with flow running on all files. After I tried to bump flow-bin to 0.70.0 I ran into the following error:
```
/tmp/flow/flowlib_688a634/core.js:256:19

Missing type annotation for T.

     253│       initialValue: void
     254│     ): T;
     255│     reduce<U>(
     256│       callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: Array<T>) => U,
     257│       initialValue: U
     258│     ): U;
     259│     reduceRight(
```
as you can see this is an error reported in flow's own core library without any context. I tried the `traces` option in both my flowconfig and as command line argument, but to no avail.  Even if I crank it up to 10000 it still only reports the block mentioned above. 
To work around the issue I tried to find references to `reduce` and type the array on which it was 
invoked, but to no avail. Anyone got a clue on how I can find out what piece of my code is actualy causing this error?

Bumping flow to 0.74.0 produces the same error, so it's still there after 4 releases.

**Comment by mikewoudenberg** [comment]
@sibelius thanks. I was aware of that and as such went through all my typedefs, but I cannot find the culprit that causes the mentioned message. I'm having a hard time pinpointing what causes this error to be reported

**Comment by wcandillon** [comment]
@sibelius do you have type definition of React and React Native that work for flow 0.7.x?

**Comment by mikewoudenberg** [comment]
Digged a boit further and found the culprit in my code. I've isolated the issue in the following segment:
```
function flatten<T>(a: T[], b: T[]): T[] {
  return [...a, ...b];
}

export function issue() {
  return {elements: [1,2].map(x => [3,4].map(y => [5,6].map(z => ({x,y,z, foo: `${x}`}) ))).reduce(flatten, []).reduce(flatten, [])}
}
```

This obviously is an exported reduce result and it is solvable by adding the correct type but still... The error could be a bit more helpful

**Comment by jbrown215** [comment]
Sorry this error message was so unhelpful. I've been running into a similar issue recently. I'll look into making these missing annotation errors point to better places.
