### ISSUE TITLE
Assigning nested array element causes invalidation of array type refinement

### ISSUE THREAD

**Issue by quickgiant** [facebook/flow#6474]
I'm currently experiencing what looks like an incorrect refinement invalidation when accessing an array inside an object. The object is typed such that one of the properties is a maybe array. After refining the type of the array property to exist and have nonzero length, I can access the array without error. As soon as I set the value of one of the elements of that array, _without calling any other functions_, the refinement of the array itself is invalidated.

I've reproduced this on [flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFZ4DGGA6gJYYAWAsgIZbEEC8YA3qmGBYAnAOYB+AFyCAdlgDaAXQA0qAL7ooAV2lVacaWAAmcAMpwAtnka1pIgBRwyUkuSp1GrdngCUvfmGBgMAAlPCgbAmERMAw4MDwAD1oAZwwZQzAGFgA3Aml9AC88ITiYPFtGf1ooMAcyADoosE5uaU0YGDAAHy6wR1JG0XqyioZmlrAABl8+AQEhK00haQBuMH91AUCwCn1Ul0HolLAF8Ok8DNjMnIIRkUYwAD5uAEZ6sAAVBmOYCOvksD5eJCEpCer+XbSVJGOB4ZLUOBCADWzT6DSickmChW-m2AEFkslaCIDIwCOEhNC8GVLNI0lcWGAieYcGUwL8MMUWDAlGAEN8KGMKCwDBwZFhrLZwVsggA5OJaHQYPRQwQLHbcsqGaVogYYrGoniZanwKQAcngcBRLDSljNYFUOJlYDMlgYiBiWTSLEJxOktLSws0yThnoIpwiAZicTFNmy3NohhtFwAhBC9mlku72oYEcjUf1DsNyvcGDj1EA) with the following code:
```
/* @flow */

type ObjectWithMaybe = {
  arg?: any[],
}

function doSomething(obj: ObjectWithMaybe) {
  // Refine arg to exist and have nonzero length
  if (obj.arg == null || obj.arg.length === 0) {
    return; 
  }
  // obj.arg is refined to have length >= 1. This line has no error.
  const doesWork = obj.arg[0];
  // Assign the first element to a simple literal, which can be anything.
  // No functions are called.
  obj.arg[0] = { hello: 'look at me' };
  // Somehow that assignment causes the refinement to be invalidated!
  const shouldWork = obj.arg.length;
}
```

I've read the [refinement invalidations page of the docs](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations), but this case doesn't seem to fit. Maybe I'm missing something, though.

**Comment by SamChou19815** [comment]
This is expected conservative behavior
