### ISSUE TITLE
Difficult to suppress duplicate module provider errors when multiple versions of a transitive dep get installed

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#6475]
Please just get rid of these errors for the time being.

https://github.com/facebook/fbjs/issues/294

This happens even when I have `module.system=node`.  I'm not even using haste so this is a bug.

**Comment by jedwards1211** [comment]
Happens when (due to seeming yarn bugs) two different versions of `fbjs` get installed.  As the `@providesModule` annotations are some janky hack that seems internal to Facebook, please provide an option to at least suppress all of these errors.

**Comment by jedwards1211** [comment]
Also happens if dupe versions of `warning` get installed, so this is widespread, really annoying problem:
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-router-dom/node_modules/warning/warning.js:1:1

Duplicate module provider for warning. Change either this module provider or the current module
provider [1].

     node_modules/react-router-dom/node_modules/warning/warning.js
     1│ /**
     2│  * Copyright (c) 2014-present, Facebook, Inc.
     3│  *
     4│  * This source code is licensed under the MIT license found in the

     node_modules/@material-ui/core/node_modules/warning/warning.js
 [1] 1│ /**


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ node_modules/react-router/node_modules/warning/warning.js:1:1

Duplicate module provider for warning. Change either this module provider or the current module
provider [1].

     node_modules/react-router/node_modules/warning/warning.js
     1│ /**
     2│  * Copyright (c) 2014-present, Facebook, Inc.
     3│  *
     4│  * This source code is licensed under the MIT license found in the

     node_modules/@material-ui/core/node_modules/warning/warning.js
 [1] 1│ /**
```

**Comment by nirajniroula** [comment]
It's still an issue.  The error logs are polluted with `duplicate-module` errors which make other errors hard to find.

**Comment by gkz** [comment]
Have you tried using `[declarations]`?: https://flow.org/en/docs/config/declarations/
