### ISSUE TITLE
reason on flowtype codebase?

### ISSUE THREAD

**Issue by sibelius** [facebook/flow#6478]
Based on this https://twitter.com/sseraphini/status/1007244891435491328

I think supported new features in Reason would make it easier to contribute to flowtype codebase

**Comment by mrkev** [comment]
Hmm, what would you suggest?

**Comment by phpnode** [comment]
I think @sibelius is talking about converting the flow codebase to reasonml which is designed to make ocaml more approachable for JS devs. Converting the code is actually a one liner using `refmt`, but I think the blocker is that the Flow team like ocaml syntax and don't feel a need to change.

**Comment by mrkev** [comment]
Oh! Interesting proposal. Unfortunately it'd also mean loosing all the blame history, unmerged PRs, and depending on the Reason.ml team + whatever changes they make. The core flow team are long-time OCaml developers too, so they might probably be skeptic of the change 😅

I'm personally quite a reason fan, but although the learning curve is minimal it's still just gaining traction. Let's see where it goes in the future!
