### ISSUE TITLE
ComponentType with additional static properties

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#6479]
I have approximately this code:

    /* @flow */
    
    import * as React from 'react';
    
    const Foo = () => null;
    Foo.bar = null;
    
    const Bar: React.ComponentType<{}> & { bar: any } = Foo;
    
    const Baz = ({ children } : { children: React.Node }) => children;
    
    <Baz><Bar /></Baz>
    
Actually, the static property is being assigned using the Recompose `setStatic` HOC, but the end result is the same.

My problem is that this code will make Flow throw the [following error](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudenAB25YgDE4cMAF4wACgCUMgHxghAVxgx+EuADoARqXwy1m7QOGiwAIWMAuat0J6AwqzxCaQwgBUAnjg0ADwA3gC+qgBkYKFgRviOpEL+YOGmuvyogiLEdgBepnJx9AAWGDAAJlxCaWCOJeVVNY60DC4AcnCVNGlK0qplFdXeWcEFyuPGYMCTwBNAA):

    12: <Baz><Bar /></Baz>
             ^ Cannot create `Bar` element because object type [1] is not a React component.
    References:
    8: const Bar: React.ComponentType<{}> & { bar: any } = Foo;
                                            ^ [1]

I would expect Flow to be happy with my type, because I'm just adding properties to a ComponentType, but it's not. Is this a bug or am I typing it wrong?

**Comment by FezVrasta** [comment]
Just an heads up, on Flow 0.69.0 this code works just fine.

**Comment by cjmochrie** [comment]
I solved this problem by using `React.StatelessFunctionalComponent` instead of `ComponentType`.

**Comment by kubijo** [comment]
[This indeed worked in `0.69`, but regressed in `0.70.0`](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudenAB25YgDE4cMAF4wACgCUMgHxghAVxgx+EuADoARqXwy1m7QOGiwAIWMAuat0J6AwqzxCaQwgBUAnjg0ADwA3gC+qgBkYKFgRviOpEL+YOGmuvyogiLEdgBepnJx9AAWGDAAJlxCaWCOJeVVNY60DC4AcnCVNGlK0qplFdXeWcEFyuPGYMCTwBNAA)

- I haven't found a note about new bugs in that release and it seems to me that this should indeed be fine.
- I've also tried extending stateless functional & `class<React.Component>` types separately and joining them with union, by that fails as well.

Not having a slightest idea what the check for "**is not a React component.**" is, I'm at a loss

**Comment by FezVrasta** [comment]
And after 3 years I end up in this issue looking for the solution to this very same problem 😂 

@goodmind any chance to get some love for this issue?

**Comment by SamChou19815** [comment]
Closing since we don't recommend this pattern.
