### ISSUE TITLE
for..in does not respect type definitions

### ISSUE THREAD

**Issue by alanning** [facebook/flow#6484]
Type definitions seem to be ignored when `for...in` is used.  

Work around is to use `Object.keys`.

Suggested triage: Add warnings to documentation pointing out unsuitability of `for...in` and `for...of` usage and recommended use of `Object.keys` instead.

Note: I created a new issue since the related #935 is talking about type inference specifically whereas this seems to be a general failure case.

```
type RawData = {
  emails?: string,
}
type NormalizedData = {
  emails?: string[]
}

function normalizeData (rawData: RawData) : NormalizedData {
  const norm: NormalizedData = {}
  
  // GOOD: works as expected
  //if (rawData.emails) {
  //  const re = /\s*;\s*|\s*,\s*/
  //  norm.emails = rawData.emails.split(re)
  //}
  
  // GOOD: generates error as expected
  //if (rawData.emails) {
  //  norm.emails = rawData.emails
  //}
  
  // GOOD: generates error as expected
  //const keys = Object.keys(rawData)
  //keys.forEach((fieldName) => {
  //  norm[fieldName] = rawData[fieldName]
  //})
  
  // PROBLEM: should generate error but doesn't   <================
  //for (let fieldName: string of Object.keys(rawData)) {
  //  norm[fieldName] = rawData[fieldName]
  //}
  
  // PROBLEM: should generate error but doesn't   <================
  for (let fieldName: string in rawData) {
    norm[fieldName] = rawData[fieldName]
  }

  return norm
}

function apiRequestHandler () {
  const input = {
    emails: "foo@example.com,foo2@example.com",
  }
  const data = normalizeData(input)
  processData(data)
}

function processData (data: NormalizedData) {
  if (data.emails) {
    console.log(data.emails.toString())
  }
}
```

Full Reproduction: 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKAhggCLEbFgC8YA3qmGHgLbECWMAzgPwBcYbhgBOHAHYBzADSoAvplwEAcnBHsYHAF54AJhSq0GTFuy59BwsVIDaAXXnooAV3EBjDBzjiw4tRu08A2oAChFSYMESckpiAEowQVV1Yk0dfVjjZjdvYV9-JP9UwIzDOnoFZhNgYDAAcQB5BrJBBDUAa24wYi68AA98Dz1q4A4oMDCI2IA6Nk4eBMZmGuzcjDARAjpgAB1uEABuPZAAH2PpY7Rl2vz1WbMeI3CYqnv57mnuHE0MMLw4kaVMAjepNFpgDAACxEiF6IhhIm6vQGeCGuhGYwmz2Cb3MixBt1YuMedGxMzm5kBJhBjWagihMIQcIRSJYKLRIxy4jy7TwWC6dAaACMAFaojDTXn8yYveIjKUfKBqACixDckJCISgHDwMF0ymIrH+tAAfFkwCtCTZtbr9Ya8HYnlMqNadXqDUaHNc5ACqtcwAAFQgNABCABllQBZSyQuDOPUQ6GIFjwtRgIXOda6OB4bjiADk62YAB4aGXyxXKzQRkrESEYHh1jb3fbLKIJJIwHBxsKxR5JXzuDLgnF8f6rc27Z6nbLXbaPQ6qX6LbUg6GI9GhLH47pE4yUyyM1mc3nC8wwKWq1eyyZaxMG023VO8G3rJ2JBtnfFzcw-Oo5y206kl+AHPl6YAKCYmwYM4Ig+H+rCOKgLjuJ43jdDgHCEHgACOzi5hgAASxDiLoDZ1mOYBcnkEg4JmRhLOeFI8IIABESpwBA-SGt8eDTDkrDSBxABMXF9DxDb8XArCsbIzBAtRWaZHQCHFDowQhLRma+mAOAwm4ubcBpuixACkEoR4Xg+HpcAGdwRmZCEJlUIUKRpHoI7mpiTnkg83CUas3JwJJ8CSD5rzMR8GBwAAyu2UghKOJgKHIQA

**Comment by pladaria** [comment]
Another example:

```javascript
// OK
export const reduce1 = <K: string, V, O: {[K]: V}, A>(
    obj: O,
    fn: (acc: A, value: V, key: K) => A,
    initialValue: A
): A => {
    let acc = initialValue;
    Object.keys(obj).forEach(key => {
        acc = fn(acc, obj[key], key);
    });
    return acc;
};
  
// Not OK
export const reduce2 = <K: string, V, O: {[K]: V}, A>(
    obj: O,
    fn: (acc: A, value: V, key: K) => A,
    initialValue: A
): A => {
    let acc = initialValue;
    for (const key in obj) {
        acc = fn(acc, obj[key], key);
    }
    return acc;
};
```

https://flow.org/try/#0PTAEHkGkCgFMA8AOB7ATgF1AY2QOwM6aqwAmArlrAIygC8oAPJAFyiGoCWuA5gDSgA1fuFYBvANqQAuqwEBffgEEAfAApooTaGQAjAFatwvDVoBmuVqoCGWLK0X8AblYA2ZWLP4BrWAE9WkACUdMqgDiaaXBzoHK4Cru720IH2IaCiEaAusJg2WHSgUTFxCbAA3Jng+rBY6AB0Pr74qrp6gXWmaACiNgAWqo1pGVojoHkF5ta2-K3ijVLefoEVI3LLmcToZKi4Y7YVciug0CCgAHLImFBwSGiYOAREpBSwAEwFTKzsXHyCwmKSGSCBRhNSZVqGYwjcyWPL2JylTygRoBYK0ULhEZFWIueJuDxhZKpdHpTLZXK2ArYkr4o6aTqoUCqB6EZF+Qq7VrBYajTTjeiTPIzfRzPwLNm+darDY5ba7PIHMpAA

**Comment by SamChou19815** [comment]
All of them would correctly error now
