### ISSUE TITLE
Class mixing and strange instanceof behaviour

### ISSUE THREAD

**Issue by bitschaser** [facebook/flow#6486]
I have some big class and dream about splitting implementation of it's methods to different files. I tried to use class mixing but encountered something weird. See sample and comments below.

```
class Mixin1 {
  method1() {}
}
class Mixin2 {
  method2() {}
}
declare class HugeClass mixins Mixin1, Mixin2 {
  constructor(): void
};
class C extends HugeClass { }

function fn (b: HugeClass) {
  // Flow Error here: all branches are incompatible: Either `Mixin1` [1] is incompatible with `Base` [2]. Or `Mixin2` [3] is incompatible with `Base` [2]. Or super of `Base` [4] is incompatible with `Base` [2]
  if (b instanceof C) {
    b.method1()
  }
}
// But without instanceof checking everything is ok
function fn2 (b: HugeClass) {
    b.method1()
}

```

**Comment by yiakwy** [comment]
@speedboat Hello I doubt mixin is a part of flow type system standards. I have checked flow.org no description about mixin: used it inside class mixin or interfaces mixin or event objects mixin. Could you verify that your sentence is lexically correct?

**Comment by SamChou19815** [comment]
No longer errors
