### ISSUE TITLE
Cannot resolve module `mime-types`

### ISSUE THREAD

**Issue by budarin** [facebook/flow#6487]
Try to import mime-types 

```js
import mime from 'mime-types';
```

but got unexpected error:

```
{
	"resource": "/d:/Projects/react-ssr-bootstrap-project/src/server/utils/getFileDescription.js",
	"owner": "_generated_diagnostic_collection_name_#28",
	"code": "undefined",
	"severity": 8,
	"message": "Cannot resolve module `mime-types`.",
	"source": "flow",
	"startLineNumber": 2,
	"startColumn": 18,
	"endLineNumber": 2,
	"endColumn": 30
}
```

Here is .flowconfig:
```
[ignore]
.*/dist/.*
.*/.idea/.*
.*/.git/.*
.*/.tmp/.*
.*/node_modules/.*

[include]

[libs]

[options]
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
module.ignore_non_literal_requires=true

temp_dir=./.tmp/flow
suppress_comment= \\(.\\|\n\\)*\\$FlowIgnore

module.name_mapper.extension='svg' -> '<PROJECT_ROOT>/src/config/flow/stubs/url-loader.js.flow'
module.name_mapper.extension='png' -> '<PROJECT_ROOT>/src/config/flow/stubs/url-loader.js.flow'
module.name_mapper.extension='jpg' -> '<PROJECT_ROOT>/src/config/flow/stubs/url-loader.js.flow'
module.name_mapper.extension='gif' -> '<PROJECT_ROOT>/src/config/flow/stubs/url-loader.js.flow'

module.name_mapper.extension='css' -> '<PROJECT_ROOT>/src/config/flow/stubs/css-modules.js.flow'

[lints]

```
What the error is about?

**Comment by apsavin** [comment]
Well, `flow` does not understand the `'mime-types'` module because it comes from `node_modules` (I suppose) but `node_modules` directory is in the `[ignore]` section of your `.flowconfig`.

You can generate a types stub for this module using `flow-typed` and then correct it. Maybe [this](https://github.com/flowtype/flow-typed/blob/master/definitions/npm/node-mime_v1.x.x/flow_v0.25.x-/node-mime_v1.x.x.js) link will be useful.

**Comment by budarin** [comment]
Thanks, I've got it

**Comment by budarin** [comment]
@apsavin 
Could you help with htt2 module?
It's still not described in Flow types definitions

**Comment by apsavin** [comment]
Well, how can I help?
If you meant "Could you write flow types for http2 module and create a PR to this repo" then answer is "yes, but I don't know when I will have time." 

If you need it at work I think you can do it yourself, it's not necessary to wait for anybody.) That's how I got my `Contributor` badge.
