### ISSUE TITLE
Can reference arbitrary properties on functions

### ISSUE THREAD

**Issue by decentralion** [facebook/flow#6490]
As seen on [this flow.org/try]:
```js
/* @flow */

const f = () => 3;
f.foo().bar()
```

Why is this not a type error? `f` clearly does not have a `foo` property.

[this flow.org/try]:https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjAF4wAKASlID4wBmAblSgDoo44rWAjAQwBOVIA

**Comment by goodmind** [comment]
Duplicate of #106
