### ISSUE TITLE
Potential spread operator bug

### ISSUE THREAD

**Issue by Ricardo-Marques** [facebook/flow#6491]
I'm trying to build a type that has a set of nested properties that will be extended by some method.

[Try flow example](https://flow.org/try/#0C4TwDgpgBAshwEMoF4oG8A+AoKUBmA9gQFxQDOwATgJYB2A5gDQ5QBGClpFNDWGAvliyhIUAIIp02XCIhcqdJiwC28BKTiI+g4eGgA5AsAAKlCGQi1gASVoBlANZ1aIMZqSpMLQiXILeAkKyUI7OrpJeMnryPEq4qoikACQAItR4eAA87oxQhiZmFla2obQubmoAfNpCAMYEtBTkTmUgpKXlESyypADkCL3M8WqkaCy47JxQvay9LII69Y3AULRGHW3iXbgAdHtkLS5DUAnq6ONQezsHYTunx7j4RH2z81j8QA)

```javascript
// this will what a "full built" meta should look like
type Meta = {|
  foo: string,
  bar: string
|}

// the full type "A" includes a full built meta
type A = {|
  type: string,
  meta: Meta
|}

// when creating a skinny vesion of A, we omit some attributes from meta
type NotPresentInSkinnyAMeta = {|
  foo: string
|}

// so SkinnyA.meta is a diff between the full built meta and the properties that shouldn't be present
type SkinnyA = {|
  type: string,
  meta: $Diff<Meta, NotPresentInSkinnyAMeta>
|}

// all good here, works as expected
const skinny: SkinnyA = {
  type: 'a',
  meta: {
    bar: 'b'
  }
}

// throws "Cannot assign object literal to `notSkinny` because property `foo` is missing in `Meta` [1] but exists in `Meta` [2] in property `meta`."
const notSkinny: A = {
  ...skinny,
  meta: {
    ...skinny.meta,
     foo: 'b'
  }
}
```

**Comment by wchargin** [comment]
[Simpler repro][1] (without `$Diff`, `type`, or `skinny`):

```js
// @flow

type Meta = {|
  foo: string,
  bar: string,
|};

type A = {|
  meta: Meta
|};

const okay: A = {
  meta: {bar: 'b'},
  meta: {foo: 'a', bar: 'b'},
};

const notOkay: A = {
  ...{meta: {bar: 'b'}},  // errors, but shouldn't
  meta: {foo: 'a', bar: 'b'},
};
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWSygIagC8oA3gD6KiiSywBcoAzigE4CWAdgOYA0NUACNC7Zmy59BlAL4BuZOmygAgqQrVaAWwKFm+IojmLEAY1jc2oWAGtCaZurLkhuos3KjxoAOTDfWUEdPU96Jj9CX34RMWZ-QMEFZAsrFFBuWBQAeXtHNQ1XWgA6UvJ3fQpveIDZINoQUCx2dlh2FhjhAFd0sV4uwmFoNFYAC1gu6AATbl8UN1CKcPiozri-WqT5IA

While this definitely seems like a bug, it’s not a particularly
surprising one. The spread operator sees that the target has an
attribute with key `meta` and value `{bar: 'b'}`, which is inconsistent
with `$PropertyType<A, "meta">` (namely, `Meta`), so it complains. It is
failing to take into account that this property is overridden later in
the object anyway. At least, it seems to me that this is what’s
happening.

**Comment by wchargin** [comment]
Related: #6498.

**Comment by Ricardo-Marques** [comment]
[Also related, I think.](https://flow.org/try/#0C4TwDgpgBAqgdgQwK7ABYTsAlgYwcCAEwAkIFCIAnAZygF4oBvAHwCgBIAGQTgHMkEvCAC4oAcgxiozcRGpjWzAL6tWoSFACCKdJlz4ipclVoMWHAHRX4yNBmx4CJMhRoAaVlC9adAe0pYAF74WL5wotTAAXyKKt7xCYlJ8Wrg0EauprCIOvb6Thkm0j52eo6GLiaq6tAACgiU2AgANoU09FAAJADKqAiQADxt1AB8nlCsOGGRUGANTa2VNKL1jVgtwx2MHNpo-kEhYaJiCkpAA)

**Comment by wchargin** [comment]
@Ricardo-Marques, that seems unrelated; the error persists if you
replace `...UnauthenticatedHeaders` with `Language: "en" | "es"` to
inline the spread, and [is more easily reproduced by][1]

```js
// @flow
const x: $Shape<{a: number} | {b: string}> = {a: 1};
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1ADwFygAkAygBYCGADgKYA8A3hYWgK4C2ARjQE4C+oAD6gGnQth4BLNAHM+APlABeEc1ABGPgG5EQA

Feel free to open a different thread.

**Comment by nmote** [comment]
This no longer errors in master
