### ISSUE TITLE
Implement jsx generics

### ISSUE THREAD

**Issue by smashercosmo** [facebook/flow#6495]
Similar to https://github.com/Microsoft/TypeScript/pull/22415

**Comment by mrkev** [comment]
For reference --cause I'm sure people will come here looking for ways to do this-- right now you have to define [dummy components](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcmXRnwChS0AbFAZxrgDEIIAeAFQD44kAPGJAHYATekQwA6AMK5IAwTBYBvAEYooALjhsAvl0WkAkFEFCkUOAAoAlHH1x7cI0hgBXKALgshwAG4cLMACeYEgQmHAwABbANOJgOGCxqlBWLAD03n6kDnDapHkU1HSMzADKMFDAAgDm3Hwm9EysNBVV1XraQA).

**Comment by smashercosmo** [comment]
Thx @mrkev, that would've never come to my head)

**Comment by goodmind** [comment]
Closing for more descriptive https://github.com/facebook/flow/issues/7672
