### ISSUE TITLE
HTMLSelectElement missing validation properties and methods.

### ISSUE THREAD

**Issue by shannonmoeller** [facebook/flow#6496]
The type definition of [HTMLSelectElement](https://developer.mozilla.org/en-US/docs/Web/API/HTMLSelectElement) is missing validation properties and methods.

![image](https://user-images.githubusercontent.com/155164/41668168-fbfe5b4e-746b-11e8-9b9f-f7ab8a85fca6.png)

https://github.com/facebook/flow/blob/365e61b4dac03531b003ea201efe3dccf4da3890/lib/dom.js#L3162-L3185

**Comment by apsavin** [comment]
Do you want to create a PR?

**Comment by shannonmoeller** [comment]
Sure thing.
