### ISSUE TITLE
Type-checks for spread operator are failing

### ISSUE THREAD

**Issue by burdakovd** [facebook/flow#6498]
flow-try [link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAJngHYYCWUlAhgEYx4A8AKgHxgC8YA3qmDCViALjCsANKgC+AbnRQArmQDGVOGTAqNANzwAnDCXJUaBgEwAKAB5jjFanUYsyigLb0D7AJR3SDmgYmZgBnDH1KMgBzTn5BfTwMRX1NXjAAOkzrCSFRMGt04XSMOABlcMioy28wORkgA): 

snippet:
```
type Identifiable<T> = {
  id: T,
};

function convertIdentifier2(x: Identifiable<number>): Identifiable<string> {
  // this should succeed since we override id to be of string type, but generates type errors
  return { ...x, id: x.id.toString() };
}
```

```
8:   return { ...x, id: x.id.toString() };
            ^ Cannot return object literal because number [1] is incompatible with string [2] in property `id`.
References:
7: function convertIdentifier2(x: Identifiable<number>): Identifiable<string> {
                                               ^ [1]
7: function convertIdentifier2(x: Identifiable<number>): Identifiable<string> {
                                                                      ^ [2]
```

**Comment by ntomallen** [comment]
Here's [another example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDCArgM7pwC2ACgE5zYCMYAvGAOTq5lgNsY75iZSrXoAmFu07cxffnjAB5AEYArXAGN0TVgG9UYMAA8AXGDI0AlgDsA5gBoDYTGaHlqdRqgC+AblTy+CrqWhJ6Tqbm6FZ2joYuhKTuothiPv6oUETWWpZw1mBQcHAAFHBqZsGa2gCUlWrVEvqGGvnc5api9SHoYWDNYACQAHSjHXGGzmYcXOhgsk7eTjS46EQ0BR1i-ktAA). We basically take one object and transform it into another object, changing a few properties along the way. We have a property that is the same key on both objects, but different types. The spread operator should override the first property and replace it with the second, but flow doesn't support it.

**Comment by nmote** [comment]
This no longer errors in master
