### ISSUE TITLE
Usage in Node

### ISSUE THREAD

**Issue by steida** [facebook/flow#6499]
As I know we have only two options without for Node dangerous Babel transpilation.

1) https://github.com/flowtype/flow-remove-types
2) comments

It seems flow-remove-types is not maintained anymore. Am I correct?

**Comment by TrySound** [comment]
@steida Why do you think babel transpilation is dangerous for node?

**Comment by steida** [comment]
It's tricky. Wrong error lines, suboptimal performance, etc. Also, all we really need is removing types, as described in https://github.com/flowtype/flow-remove-types.

http://vancelucas.com/blog/dont-transpile-javascript-for-node-js/

**Comment by TrySound** [comment]
In development babel-node is ok. Just don't put it in production environment.

Did you find something doesn't work in `flow-remove-types`?

**Comment by steida** [comment]
I had some issues since I am using .mjs. Also, it seems to be unmaintained.

**Comment by TrySound** [comment]
Did you tried [esm](https://github.com/standard-things/esm)?

**Comment by steida** [comment]
No, I prefer Node 10 `mjs` https://github.com/este/este/tree/master/server I works well.
