### ISSUE TITLE
Default props for function types are not understood when using spreads

### ISSUE THREAD

**Issue by kumar303** [facebook/flow#6502]
If you specify a `defaultProp` value for a function type, Flow thinks that it is undefined.

Here is an example ([try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAEJpYAKxY6AXjgBvOnDgEIEAFxwAFAEo4AgHxwAdgFcQAIyxQANHQC+9Riza8I-ZSLFwAdE86oefVCbO4ANmnQBZJgBhEkh1LHV4LAAPGAiAE3RsPBgHEPAIcMiAHit+NVFxVBhkGGBcOHisAmRNbxg8wTtxcUkZeSVVOAAWACYjcVMGcUp1KqhFZpbKGE0odThssBVhGAALYFQHMHcHNsmAajgARmNsgHpl+kGTBmzA9LCI+HOVIA)) of the failure:

```js
import * as React from 'react';

type BaseProps = {
  foo: () => number,
};

type Props = {
  ...BaseProps
};

class MyComponent extends React.Component<Props> {
  static defaultProps = {
    foo: () => 42,
  };

  render() {
    return <p>{this.props.foo() + 1}</p>;
  }
}

<MyComponent />
```

```
17:     return <p>{this.props.foo() + 1}</p>;
                              ^ Cannot call `this.props.foo` because undefined [1] is not a function.
References:
4:   foo: () => number,
          ^ [1]
```

If I remove the object spread in `Props` ([try](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nThwCECAC44ACgCUcHgD44AOwCuIAEZYoAGjoBfenVwAbNOgCyTAMIlIyrMvhYAHjEcATdNjwwAdLbgEA5OADycENxKgsKoMMgwwLhwHlgEyKomMBHc8gJCwiJikrLySgAsAEx6woYMwpTKqVClMYWUMKpQynChYAr8MAAWwKh+YFxjohClANRwAIz6oQD0-fS1BgyhVoH2jvArCkA)), there is no Flow failure.

```js
import * as React from 'react';

type Props = {
  foo: () => number,
};

class MyComponent extends React.Component<Props> {
  static defaultProps = {
    foo: () => 42,
  };

  render() {
    return <p>{this.props.foo() + 1}</p>;
  }
}

<MyComponent />
```

Oddly, this only seems to apply to function types.

**Comment by apsavin** [comment]
Works as expected.

[Fixed](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAEJpYAKxY6AXjgBvOnDgEIEAFxwAFAEo4AgHxwAdgFcQAIyxQANHQC+9Riza8I-ZSLFwAdE4AkAUQAeeGAB5OqHnyoKiZmuAA2aOgAskwAwiSQ6ljq8FjuMMkAJujYXg7x4BBJKd5W-Gqi4qgwyDDAuHCZWATImmEwZYJ24uKSMvJKqnAALABMRuKmDOKU6k1Qit09lDCaUOpw3mAqwjAAFsCoDmCBDn2LANRwAIzG3gD02-STJgzeMQWJyfD3KkA) example.

**Comment by willdurand** [comment]
Hi @apsavin, thanks for your quick reply.

Could you maybe be more descriptive? I am not sure to understand why it works as expected since I don't see any documentation about spread.

**Comment by apsavin** [comment]
Spread makes all fields optional if spreaded type is not exact.

There're [PRs](https://github.com/facebook/flow/pulls?utf8=%E2%9C%93&q=is%3Apr+is%3Aopen+spread) with docs.

**Comment by willdurand** [comment]
@apsavin that's much more informative, thanks.

**Comment by kumar303** [comment]
Thanks so much. This helped me spot the problem in my real code. 

> Spread makes all fields optional if spreaded type is not exact.

This is surprising -- it sounds like a Flow bug. In this case, `foo` was marked required and even though it's spread into the new object, Flow should be able to figure it out, right? 🤷‍♀️

**Comment by apsavin** [comment]
> This is surprising -- it sounds like a Flow bug. 

Well, flow team created type spread operator with some semantics. It works by design. You can use it with `$Exact` so you can change it's behaviour if needed.

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
