### ISSUE TITLE
$ArrayElementType for arrays

### ISSUE THREAD

**Issue by Daniel15** [facebook/flow#6503]
Given this type:
```
type People = Array<{|
  name: string,
|}>;
```

You can extract the type inside the array using [`$ElementType`](https://flow.org/en/docs/types/utilities/#toc-elementtype):
```
type Person = $ElementType<People, number>;

({name: 'Daniel'}: Person);    // Works
({invalid: 'Daniel'}: Person); // Error
```

Tryflow: https://d.sb/1e

However, this syntax is pretty obtuse for people that aren't very familiar with more advanced parts of Flow (what does `number` mean? ... it's the type of the key of the array)

It would be nice to have something like `$ArrayElementType` so we could just do `$ArrayElementType<People>` in this case.

Right now it's easy enough to just alias it:
```
type ArrayElementType<T> = $ElementType<T, number>;
```
but it would be nice for this to be built in to Flow 😄

**Comment by SamChou19815** [comment]
Indexed-access type can support this: `SomeArrayType[number]`

**Comment by Daniel15** [comment]
@SamChou19815 It's not *really* fixed, as it still has this issue:

> However, this syntax is pretty obtuse for people that aren't very familiar with more advanced parts of Flow (what does `number` mean? ... it's the type of the key of the array)

I still think something like `ArrayElementType<T>` is clearer than `T[number]`.

**Comment by SamChou19815** [comment]
Flow already has a lot of less-known special global types like `$Compose`, `$CharSet`. We don't really want to add more unless there are compelling reasons to do so. e.g. I'm not convinced that `ArrayElementType<T>` is clearer than `T[number]`. If you think so, you can easily add this to the global library definitions.
