### ISSUE TITLE
ValidityState type missing 'tooShort'

### ISSUE THREAD

**Issue by oliverjam** [facebook/flow#6507]
Would it be possible to add `tooShort` to the [`ValidityState`](https://github.com/facebook/flow/blob/bb69ae6dc998560e83f54ad696cc387dde3a97ed/lib/dom.js#L2883) type? It looks like this has been implemented by pretty much every current browser so would be useful to not have to work around this error. Thanks!

[Reproduction repl](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgGoEMYCWAJgQC4CeAyqbqQKZgDGcADgXUWFAE5wC2YABalSLAM4AuTAHMyggK4AjAHTM+wKLkZ1FcOAGsN8BMEXxFpxQDYAnLjpWijGzYAcAVisAGOq4DMUO4ALLhEtlaMjH6uAOxERHR+uDYxHMCEFkT8ygBWYgDEADIATK7+qAmMMLjcDFW4YmI4+MRkVDT0YADeqGBgiqEAkgB2LPKkEv16MHS4wwDcvUzyYqT8AKLcvNyTunAzc4t9LLT03MMAsgRifLSMgrvTswtL3HPSdADyAG503LCIR77Z5HMBvYYfACqwwS-2MQIOLz6qzoLCuNzuDymwMOSzWcEKcAhCJBePILDo6NupHuJNxfW++HklOuYgIxOxiNBjMIRDpLwAvuhmMNVmAPqRNtswABeMAACi6YB5rQoYAFkyVKpIFEmeF5bWotAYAoAlLKAHzdJYEKAK7VtZQnER-S7Xan3c21Ujyc5gADkzrOwzAfHdmP9oNt9paOvIynxlEEcG4pC9dB9fv9+LAYmTqcjqAFQA)

**Comment by apsavin** [comment]
Do you want to make a PR?

**Comment by oliverjam** [comment]
Yeah sure, I'll try and do it today

**Comment by oliverjam** [comment]
Sorry, took longer than I thought to get around to this!
