### ISSUE TITLE
type-incorrect Flow program type checks

### ISSUE THREAD

**Issue by jbrownson** [facebook/flow#651]
#### Repro

`flow init` in an empty directory, add this code to `flowtest.js`, run `flow check`.

``` javascript
/* @flow */

type StringsNumbers = {[key: string]: Array<number>}
type StringsStringsNumbers = {[key: string]: StringsNumbers}

var s: string = "123"

function addDomain(ssn: StringsStringsNumbers) {
  var sn = {} // This should be inferred to be of type StringsNumbers
  sn[s] = [1,2,3].map(function(a) {0}) // This line should error since I forgot the "return"
  ssn["321"] = sn // This should cause sn to be inferred to be of type StringsNumbers
}

// Here I added a type notation for sn, which gave me an error and required adding the return
function addDomain2(ssn: StringsStringsNumbers) {
  var sn: StringsNumbers = {}
  sn[s] = [1,2,3].map(function(a) {return 0})
  ssn["321"] = sn
}
```

```
$ flow --version
Flow, a static type checker for JavaScript, version 0.13.1
$ flow check

Found 0 errors
```
#### Expected results

An error similar to this one:

```
$ flow

flowtest.js:10:11,38: call of method map
Error:
flowtest.js:10:34,34: undefined
This type is incompatible with
flowtest.js:3:45,50: number

Found 1 error
```

**Comment by dnalot** [comment]
> #### [Undefined Values and Optional Types](http://flowtype.org/docs/nullable-types.html#undefined-values-and-optional-types)
> …Flow ignores the possibility of undefined resulting from object property and array element accesses. Being stricter would force the programmer to do undefined checks (like null checks) on each dereference of an array element or object property to get anything useful done.

:sob:

**Comment by dnalot** [comment]
`sn[s] = 0` produces the same behavior however :unamused:

**Comment by SamChou19815** [comment]
This now errors when we removed support for unsealed objects.
