### ISSUE TITLE
Assignment of unrefined value as disjoint union fails

### ISSUE THREAD

**Issue by Persola** [facebook/flow#6513]
([try flow version](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCAlgE4AmYAvGAN5gDWMAhgM6sBcYA5AEZnluYAL4BuTLgIAlPDgzEYBGvSZtOPUrPmKhYifjAA1PKQx5epZmepEBYAD5gZchXnGKMjFuy4AKPgJCjtyaLjoAlDa+ALJWABYAdJYAduRwALa+kQB8YAAMCQCskQD8PPwUQlwhWq7c4gDGcMmsnngwpHBYXMam5pbWyl5qIuJAA))

```javascript
type Bird = { klass: 'bird' };
type Reptile = { klass: 'reptile' };
type Vertebrate = Bird | Reptile;
let klass: ('bird' | 'reptile') = (Math.random() > 0.5) ? 'bird' : 'reptile';
const elroy: Vertebrate = { klass };
```
```
7: const elroy: Vertebrate = { klass };
                             ^ Cannot assign object literal to `elroy` because: Either string literal `reptile` [1] is incompatible with string literal `bird` [2] in property `klass`. Or string literal `bird` [3] is incompatible with string literal `reptile` [4] in property `klass`.
[...]
```
I was surprised by the error because I thought Flow would implicitly type `{ klass }` as `{ klass: ('bird' | 'reptile') }`, which I thought would match `Vertebrate`. Seems similar to some of the secondary examples I gave in #6467. Note that [using an if...else instead of a ternary](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCAlgE4AmYAvGAN5gDWMAhgM6sBcYA5AEZnluYAL4BuTLgIAlPDgzEYBGvSZtOPUrPmKhYifjAA1PKQx5epZmepEBYAD5gZchXnGpFGRi3ZcAFHwCQo7cmi46AJTixFBgfgCyVgAWAHSWAHbkcAC2fhFgAHxgAAwpAKz5tKhg3mo2gRTcqMJgeDCsBFU1quz1Ydp4TcLoAMZw6axebaRwWFzGpuaW1sq1vXpAA) produces a different error message:
```
14: const elroy: Vertebrate = { klass };
                              ^ Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To fix add a type annotation to `klass` [3].
```
But this is inaccurate--`klass` already has a type annotation.

**Comment by SamChou19815** [comment]
Expected since `{foo: 1 | 2}` is not a subtype of `{foo: 1} | {foo: 2}`
