### ISSUE TITLE
Windows - only a single core is used

### ISSUE THREAD

**Issue by lukeapage** [facebook/flow#6517]
No matter what value I use for the max workers, only one of the running flow binaries does anything. I do get multiple executables starting up, but after small blips after startup (during start of parse phase), they go to 0%.

I'll try it out on a mac machine at work - could it be that windows workers aren't working properly? can I provide any more info to help get this sorted?

**Comment by mrkev** [comment]
Hmm, please post your findings from running on a mac at work.

**Comment by lukeapage** [comment]
@mrkev 
I tried mac and its hard to tell the parallelism since it completes in 3 seconds (45 seconds on windows) but looking at the cpu time I see something like

flow - 7,34
flow - 1,45
flow - 0,82
flow - 0,03
the other 4 are 0.03

so it looks like it works on mac but the work units are so fast it doesn't get to use many of the processes?

Why is flow 20x slower on windows? The parse speed is about the same, but resolving dependencies and merging are both alot slower. I'm not an ocaml developer, but I'm willing to try anything as improving windows speed would be a massive win

**Comment by lukeapage** [comment]
I did try out previous releases going back to 0.65 and there is no difference.

**Comment by lukeapage** [comment]
related: #5694

**Comment by lukeapage** [comment]
running on a windows 10 laptop it goes down to 8 seconds with windows defender, 7 seconds without windows defender. Thats as quick as the mac.

**Comment by mrkev** [comment]
Interesting. Guess I never asked what version of Windows this was on.

I don't have a Windows laptop (I should look into getting my hands on one 😅) and have little context on the windows support. I suppose a lot of it depends on the standard/3rd party libraries we use too. What I get from this is that something is different on older versions of windows, and perhaps we should specify Windows 10 is recommended on the README.
