### ISSUE TITLE
inexact mixed is incompatible with exact object type in array element

### ISSUE THREAD

**Issue by spudly** [facebook/flow#6518]
I have an array of exact objects and I'm passing it into a function in which the type of array element doesn't matter, so I've annotated it as `Array<mixed>`. Unfortunately, flow complains that it cannot assign the exact object array to the mixed array.

This conflicts with my understanding that any type can flow into a mixed type, so I think it's a bug.

See https://flow.org/try/#0MYewdgzgLgBApgDwIbCgGwJ4C4YEEBO+SGAPAN4A+4cOAjBQL4B8MAvDANpnV0MC6AbgBQQ0JFgBbAJYI4AEwCuABxwEipabLkt2iFOgwCgA , in which the following code results in a flow error.

```js
const exactly: Array<{|one: 1|}> = [{one: 1}];

const mixedup: Array<mixed> = exactly;
```

Error:
```
3: const mixedup: Array<mixed> = exactly;
                                 ^ Cannot assign `exactly` to `mixedup` because inexact mixed [1] is incompatible with exact object type [2] in array element.
References:
3: const mixedup: Array<mixed> = exactly;
                        ^ [1]
1: const exactly: Array<{|one: 1|}> = [{one: 1}];
                        ^ [2]
```

**Comment by apsavin** [comment]
[Fix](https://flow.org/try/#0MYewdgzgLgBApgDwIbCgGwJ4C4YEEBO+SGAPAN4A+4cOAjBQL4B8MAvDANpnV0MC6AbgBQQ0JFgBbAJYI4AEwCuABxwASAEpwkcgPJhMBIqWmy5LdohToMAoA)

It's because you can mutate original array after such an assignment so it'll loose it's type.

**Comment by apsavin** [comment]
Works as expected, should be closed imho

**Comment by spudly** [comment]
Perfect, thanks @apsavin!
