### ISSUE TITLE
Type function that makes an enum object

### ISSUE THREAD

**Issue by JCMais** [facebook/flow#6521]
Is it possible to type the return of a function that produces an object that acts as an enum?

Like the following:
```
function createEnum(values: string[]) {}
```

usage is something like this:
```
const POST_STATUS = createEnum(['DRAFT', 'PUBLISHED', 'REMOVED']);
POST_STATUS.DRAFT;
POST_STATUS.PUBLISHED;
POST_STATUS.REMOVED;
```

so `POST_STATUS` would have type `$Enum<T>` where `T` is infered, in some way, based on the args given to `createEnum`.

**Comment by mrkev** [comment]
This is not possible because the arguments are dynamic. What would be the type of the following?

```javascript
const some_var = request_from_server();
const POST_STATUS = createEnum(some_var);
```
This is impossible to know statically and can only be computed at runtime.

**Comment by fizker** [comment]
It is possible for all the cases where the type of the input is known (like hardcoded values such as the example, which is common for constant enum values). React used to supply a `keyMirror` function that did exactly that, but it is possible to do with arrays as well:
```
/* @flow */

function keyMirror<O:{}>(object:O) : $ObjMapi<O, <K>(k:K) => K> {
	var keys = Object.keys(object)

	return keys.reduce(function(obj, key) {
		obj[key] = key;
		return obj;
	}, {})
}
    
function createEnum<S:string,L:$ReadOnlyArray<S>, O:{[S]:string}>(l:L) : $ObjMapi<O, <K>(k:K) => K> {
	return l.reduce((x, key) => {
    	x[key] = 'abc'
      return x
    }, {})
}

type EnumType = {a:'a', b:'b', c:'c'}
const a:EnumType = keyMirror({ a: 1, b: 'a', c: {} })
const b:EnumType = createEnum([ 'a', 'b', 'c' ])
```
[Try Flow link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBrAUwE8BZQgJ3rnoB4B5ALgG8BfAPgAUcAEYArCgQ5sAlGA5gAJGzE0AhgAdC7ADRgWAaUFkO+2QF4+YQ2C6oAkADdV9ctQDOYM2GXiCAOkoqNyExCXxpdDt6CnxMelJAtz9ogBNMXAoBLDwiEhDRXUDZWzs7EVEAbUCAXU9XKgBueyiYuNJyprseXV4InlQwQbAMHAJiUlxo1XwKAFFsTABbFgBlDjd8ekJsAHNtABkOBQAlClUUtmwYKgBBRlUqVb5dTi4Kler1ze2d-gEYDj7WTyJQqDRaNi6AxGEzmSzWErRWLxMAwZIUNIZAQCAAehWocJsAyGdhxVWotS8AHJVMJcFTiUMwEi2mAcYywN0bDw+uh8FR1BQwPMlgAVAVCrxcVQcGlU3TCWXCeVgXCy+n9XAkDZgGUixbiwV1QJ0RjMARcXXyACMCvkct0au5nIiWuwOsV+sNktVUxm+oEFTADuDyt0VPpYGq0iAA)
