### ISSUE TITLE
Unnecessary "sketchy null check" linter warnings when using defaultProps in React

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#6524]
Flow Linter gives a `sketchy-null-bool` warning for this:

```js
type Props = {
  isHappy?: boolean,
};

const Emoji = ({ isHappy }: Props) => 
  <>{isHappy ? '😀' : '😭'}</>;
//   ^^^^^^^  Sketchy null check on boolean which is potentially false. Perhaps you meant to check for null or undefined?

Emoji.defaultProps = {
  isHappy: false,
};
```

But I've specified a default value, so `isHappy` is guaranteed to be a boolean here, and the warning is wrong.

**Comment by apsavin** [comment]
It's because your `Props` type is wrong.
You should use

```
type Props = {
  isHappy: boolean,
};
```

**Comment by callumlocke** [comment]
Ahh I thought the a maybe-type was necessary if you want to be able to render `<Emoji />` without specifying props, but it seems having defaultProps is enough to allow doing that. Thanks

**Comment by callumlocke** [comment]
What led to my confusion was that the airbnb eslint config includes:

```js
  'react/default-props-match-prop-types': ['error', { allowRequiredDefaults: false }],
```

It seems having this lint rule forces you to always use maybe types if you've got corresponding default props, which sounds nice and thorough but it seems it actually reduces Flow's refinement ability, so it thinks values may be undefined when they're guaranteed to have been set.
