### ISSUE TITLE
Flow passes / fails depending on where curried type annotation occurs

### ISSUE THREAD

**Issue by RichieAHB** [facebook/flow#6525]
If I type the return type of `hofAB` as a function that returns a function of the type ` () => {| ...T, meta: Object |}` then flow complains.

[Try](https://flow.org/try/#0GYVwdgxgLglg9mABACzsAggIQDwBUBciA8gEYBWAptAHwAUAhtPGAMIBOF9UcbhtAlIgC81RLn59BIxAG8APogB0y3ABpEAWwpR6hUpWiI5AX1kAoRIg5QQbJAOGjaMi5aXLGsBO07c2A1VdLLR1CGWNXY34AbjMIsygATwAHCkR0YXNLJNTCACJ0PLjYnLTMTJdslIp8zCLjWITq9PKhWQVlRXR1EN1iciooI1MFeXdFTB7tPv1B4caIBABnIb6sTNQMTFoHaWdEUvzCxCj+AVigA)
```js
function hofAB<T: Object>(actionCreator: () => T): () => {| ...T, meta: Object |} {
  return () => ({
    ...actionCreator(),
    meta: {}
  });
}

type A = {
  type: "A"
};
type B = {
  type: "B"
};

type AB = {| ...A, meta: Object |} | {| ...B, meta: Object |};

const a: AB = hofAB(() => ({ type: "A" }))();
```

However if I annotate the returned function with the return type (dropping the `() =>`) `{| ...T, meta: Object |}` then flow is fine.

[Try](https://flow.org/try/#0GYVwdgxgLglg9mABACzsAggIQDwBUBciA8gEYBWAptAHwAUAhtPGAMIBOF9UcbhtAlIgC81RLkEBvAFCJEHKCDZIBhCQB9EAOm24ANIgC2FKPUKlK0RGoC+w0bWmzZ2zY1gJ2nbmwG6ZToxNVa39rfgBuKRCpKABPAAcKRHRhREdEOMTCACJ0bKjIzKTMVPSinMx860iYhKSsUo0XdH1A02JyKigrWw11LW1MVuN28y6emogEAGdu9oahFDQsWgE7RAcMupy8xDD+AUigA)
```js
function hofAB<T: Object>(actionCreator: () => T) {
  return ():  {| ...T, meta: Object |} => ({
    ...actionCreator(),
    meta: {}
  });
}

type A = {
  type: "A"
};
type B = {
  type: "B"
};

type AB = {| ...A, meta: Object |} | {| ...B, meta: Object |};

const a: AB = hofAB(() => ({ type: "A" }))();
```

And if I add *both* then flow complains again:

[Try](https://flow.org/try/#0GYVwdgxgLglg9mABACzsAggIQDwBUBciA8gEYBWAptAHwAUAhtPGAMIBOF9UcbhtAlIgC81RLn59BIxAG8APogB0y3ABpEAWwpR6hUpWiI5AX1kAoRIg5QQbJAMKyFyxWs3bdxclShHT02hkLSyVlRlgEdk5uNgFVYMstHUIZY2DjfgBuMzSzKABPAAcKRHRhc0sC4sIAInQanOyqksxyoMqiilrMBuNsvM7S1qEnUMV0dSTPfR8-I1GXTEmPPW9DE36IBABnX08sctQMTFoBYVFAxGba+sQM-gFsoA)
```js
function hofAB<T: Object>(actionCreator: () => T): () => {| ...T, meta: Object |} {
  return ():  {| ...T, meta: Object |} => ({
    ...actionCreator(),
    meta: {}
  });
}

type A = {
  type: "A"
};
type B = {
  type: "B"
};

type AB = {| ...A, meta: Object |} | {| ...B, meta: Object |};

const a: AB = hofAB(() => ({ type: "A" }))();
```

In this specific repro flow is complaining about the exactness of types; we were getting a lot of `indexer property is missing` errors but I couldn't get it to reproduce the error we were getting in a simple test case.

I'm guessing this it to do with scoping types over closures but it took *aaaaages* to figure out. Typically the errors were pretty unclear and pointed to weird call sites but also, at a glance (or even at a long stare) it's not clear why changing the types in this way fixed the issue.

**Comment by SamChou19815** [comment]
Now it works if you annotate the return as requested by recent versions of flow
