### ISSUE TITLE
Using constant as type

### ISSUE THREAD

**Issue by hoangpham95** [facebook/flow#6527]
Recently I've been trying to use flow with Redux. I have error with this snippet:
```
// in actions/auth/register
export const REGISTER = 'REGISTER';
export const SUCCESS_REGISTER_USER = 'SUCCESS_REGISTER_USER';

// in type declaration files
import {
  REGISTER,
  SUCCESS_REGISTER_USER
} from 'actions/auth/register';

import User from 'types/User';

export type Action =
  | {type: REGISTER, user: User}
  | {type: SUCCESS_REGISTER_USER, user: User}
```

However, flow doesn't complain when I change type Action to
```
export type Action =
  | {type: 'REGISTER', user: User}
  | {type: 'SUCCESS_REGISTER_USER', user: User}
```
And flow complain that `Cannot use string as a type because string is a value. To get the type of a value use typeof`. Does anyone know how to resolve this?

**Comment by jcready** [comment]
As explained by the error message: `To get the type of a value use typeof`:
```js
export type Action =
  | {type: typeof REGISTER, user: User}
  | {type: typeof SUCCESS_REGISTER_USER, user: User}
```

**Comment by hoangpham95** [comment]
@jcready I thought `typeof REGISTER` is a string, and a random action like `{type: "random stuff", user}` will still pass the typecheck.

**Comment by hoangpham95** [comment]
@jcready still doesn't fix the error

**Comment by daryn-k** [comment]
jcready, it's not a solution, it's a verbose workaround.

**Comment by Peilin-D** [comment]
I also ran into this problem, how about this?
```
const register = { Register }

export type Action = {
  type: $Values<typeof register>,
}

```

**Comment by SamChou19815** [comment]
We are not going to change this behavior
