### ISSUE TITLE
Generic Class Properties require annotations

### ISSUE THREAD

**Issue by marcusdarmstrong** [facebook/flow#6528]
If this is a bug, please try reproducing using https://flow.org/try/.

https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFioA8AKgD44AXjgBvAD504cACbIYyAFxwAglCjIm-AQBppcXAAtgAG1mUAdioAU6zdsEBKEUOx4YAOgByEWVjoJAF96RhY2AGVFGCwdEXEpGTxcAFcQFNMFLFkAEQVlNQ0tHUCQhlxM1HRVXFT0zJhgSwBzTggAN2B-KDisAA8Yy1l0d3xPAGESSEssSxgeNu4dXTgorJ0hMQNUaLZRLZkk2rSMrNz8lRgTVE8wLhv5RQMygytumxcDw8oYFKhLOBXYA3O4QbieYxmCyzGxAm47LKeZInBrZPKKJz0GRBOhBIA

It appears that a generic class property (in this case, the react 'state' property) can't be initialized without a separate annotation.

Working Example: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFioA8AKgD44AXjgBvAD504cACbIYyAFxwAglCjIm-AQBppcXAAtgAG1mUAdioAU6zdsEBKEUOx4YAOgByEWVjoJAF96RhY2AGVFGCwdEXEpGTxcAFcQFNMFLFkAEQVlNQ0tHUCQhlxM1HRVXFT0zJhgSwBzTggAN2B-KDisAA8Yy1l0d3xPAGESSEssSxgeNu4dXTgorJ0hMQNUaKwVNZi40S2ZJNq0jKzc-JUYE1RPMC4H+UUDMoMrbpsXE9PKGApKCWOB3YAPJ4QbieYxmCyzGxgh47LKeZIXBrZPKKJz0GRBOhBIA

Shouldn't this be inferable?

**Comment by stereobooster** [comment]
Similar to https://github.com/facebook/flow/issues/5903?

**Comment by SamChou19815** [comment]
Closing since we now require annotation for all class properties.
