### ISSUE TITLE
`$Call` doesn’t work with unions of instance methods

### ISSUE THREAD

**Issue by wchargin** [facebook/flow#6530]
One surely expects that `f()` is assignable to `$Call<typeof f>`, but in
fact [this is not always the case][try1]:

```js
// @flow
class Foo { type(): "FOO" { return "FOO"; } }
class Bar { type(): "BAR" { return "BAR"; } }
declare var x: Foo | Bar;
const xType1: "FOO" | "BAR" = x.type();
const xType2: $Call<typeof x.type> = x.type();
```

[try1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjaBDAzh0AxWtQBvUAFwE8AHAUwAoBKALlACIcB5N5o0AJypICuPAHYt2nANygAvjJTosoAEJoe3ctXpNmSgIIAlLsT6CRLPYamzpiACZVUqqqABuq0JCZ4CAH2WqJFFhhDBIPABVKKgBGbXEuPx0DLgBeDwA6DVo6QORg0IiogCYmABIAYTRoaAAeLNhIDKyAPlA0yEyo+kCgA

This is true in spite of the fact that Flow can assign precise types to
`x.type`; [the following declarations have no error][try2]:

```js
class Foo { type(): "FOO" { return "FOO"; } }
class Bar { type(): "BAR" { return "BAR"; } }
declare var x: Foo | Bar;
const xType1: () => ("FOO" | "BAR") = x.type;
const xType2: (() => "FOO") | (() => "BAR") = x.type;
```

[try2]: https://flow.org/try/#0MYGwhgzhAEBiD29oG9oBcCeAHApgCgEoAuaAIlgHkLSVoAnHNAVzoDszLqBuaAXz4BQoSDABCYOrUy5CJUqICCAJRqoGzNmUUqe-XgIAmOYQ2gA3CdAAeJBEgA+0cXS5D4rCGmsAVbDgCMJITQALwAfNB45FQ0jvLKpASh1gB00jiuwO6ePn4ATEHB4RwxSY54RRHxKkkhqemuQA

**Comment by SamChou19815** [comment]
It seems to be fixed now
