### ISSUE TITLE
Spread Operator allows Defeat of Type System

### ISSUE THREAD

**Issue by DeedleFake** [facebook/flow#6536]
[Flow Try.](https://flow.org/try/#0C4TwDgpgBAogHgQwLZgDbQLxQN4CgpQIBcUAdgK5IBGEATrgL664DGA9qQM7BQu0QJgmKAAowtNmE4lsAbW60AlqQDmAXRJJFcCABMGAShLxkaTAD5R2AHS3xkzoeboeCKFj4ChI7MSgByIW5-JxcyEgpqOndCawQgA)

```javascript
type Example = {
  a: number
}

const create = (props: {[string]: mixed}): Example => ({...props})

let a = create({a: 'test'})
let n: number = a.a
```

This produces no errors at all. Try identifies the `a.a` on the last line as a `number`, despite the fact that it clearly contains a `string`.

**Comment by SamChou19815** [comment]
This now errors.
