### ISSUE TITLE
Code of conduct link is broken

### ISSUE THREAD

**Issue by matchu** [facebook/flow#6537]
`CODE_OF_CONDUCT.md` links to `https://code.fb.com/codeofconduct`. When I navigate there, I see the following:

<img width="1370" alt="image" src="https://user-images.githubusercontent.com/59218/41997515-09f190b2-7a0d-11e8-9e50-a313ccb7a919.png">

I briefly looked for the Code of Conduct on the site, but couldn't find it.

**Comment by LegNeato** [comment]
This appears to be fixed and should be closed. At the link I see a CoC.

**Comment by matchu** [comment]
Ah yes, link works for me now! Thanks!
