### ISSUE TITLE
Recursion limit exceeded when redeclaring class to extend itself

### ISSUE THREAD

**Issue by jussi-kalliokoski** [facebook/flow#6540]
The following snippet causes recursion limit to be exceeded at least with flow 75 and master using the playground:

```
declare class Object extends Object {}
Object.assign({}, {})
```

I'm not entirely sure what the expected behavior is, but at least exceeding the recursion limit is probably not it. FWIW, I was trying to see if I can use this to extend built-in definitions.

**Comment by mbrowne** [comment]
I ran into this as well. How can native prototypes be extended?

**Comment by skeggse** [comment]
In working around #7225, I ran into this with (just hangs [on the repl](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsAJXwDsBzErADwBcs6MrbGSBvVGFLF8HAMJw6HdgFd8MAGKF8DALac2ACigr1mgFxhybQgEtGASiMARODlkbpy1U7YBuVAF90OKSbAVPiNeJjAAXjAECwxEADomNgBlLBhcNjMpLUsErDZQrABBbQAGS08gpji-GAIAB3IsHQVG8tQgA)):

```js
/* @flow */

declare class Range extends Range {
  createContextualFragment(fragment: string): DocumentFragment;
}

const range: Range = window.getSelection().getRangeAt(0);
range.collapse(false);
```
