### ISSUE TITLE
Infer parameters' types on exported objects 

### ISSUE THREAD

**Issue by LennyPenny** [facebook/flow#6542]
For some reason Flow throws a hard error when you don't define the types of function parameters in exported objects/classes/etc. 
This seems very inconsistent because it doesn't complain about their return types. 

Thus you have to manually tag every argument with `arg: *`, which also loses any magic the the type inference might be able to do. 

It would be great if there was an option to suppress these errors!

**Comment by SamChou19815** [comment]
Closing since now types-first requirement is much stricter.
