### ISSUE TITLE
flow has different behavior on Ubuntu 14.04 (travis-ci) than on MacOs

### ISSUE THREAD

**Issue by dcgudeman** [facebook/flow#6543]
On Ubuntu 14.04 (the default environment for travis-ci) both `focus-check` and `ls` return different results from when run on MacOs (v10.13.5). On Ubuntu 14.04 `flow ls` in particular only returns `.flowconfig` whereas on MacOs it returns all the files in my project that are tracked by flow. This is causing problems for me because I am trying to use flow in my company's CI/CD process.

**Comment by alexkrolick** [comment]
Did you figure out a workaround? Was it due to symlinks or something specific to Travis?
