### ISSUE TITLE
request: Make $Keys & $Values types more clear

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#6550]
My request is simply for ease of readability.  Some of the objects we're running `$Keys` on are fairly complex so when we look at the type of an object and see `$Keys<{...large object}>` it's pretty hard to consume.

Suggestion:

```js
const map = {
  KEY: 'KEY',
  KEY2: 'KEY2',
};

type types = $Keys<typeof map>;
```

This currently lists the type as

    $Keys<{|KEY: string, KEY2: string|}>`.

Suggest something like this instead:

    'KEY' | 'KEY2' /* from $Keys<typeof map> */

**Comment by darichey** [comment]
Fixed by 469972e08232a509762aacc27d38e3c802141320
