### ISSUE TITLE
Generic type T is inferred as T | any

### ISSUE THREAD

**Issue by zoontek** [facebook/flow#6551]
Hello!

I try to re-implement ReasonReact ReducerComponent using React + flow + switch exhaustiveness.
But when I use my render prop, flow infer my state param as `State | any` and I don't understand why.

```js
type Props<S, A> = {|
  initialState: S,
  reducer: (state: S, action: A) => S,
  render: ({|
    state: S,
    send: (action: A) => void,
  |}) => React$Node,
|};

export class ReducerComponent<
  S: {},
  A: { type: $Subtype<string> },
> extends React.Component<Props<S, A>, S> {
  state: S;

  constructor(props: Props<S, A>) {
    super(props);
    this.state = props.initialState;
  }

  render() {
    return this.props.render({
      state: this.state,
      send: action => this.setState(state => this.props.reducer(state, action)),
    });
  }
}

// usage

type State = {| count: number |};
type Action = {| type: 'INCREMENT' |};

class Counter extends React.Component<{}> {
  initialState: State = { count: 0 };

  // state arg if of type {|count: number|} | State | any
  reducer = (state, action: Action) => state;

  render() {
    return (
      <ReducerComponent
        initialState={this.initialState}
        reducer={this.reducer}
        // state param if of type {|count: number|} | any
        render={({ state, send }) => <div />}
      />
    );
  }
}
```

Demo is available here: 

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgAK1GAM4AeAMoAaUAEEAfKAC8oAN4AfRKFAoAdilwoS0UbhK4iALlAT1oRgBMArmSLYLACkHHTFiaHJ7YWhZSAJQKclYajFq2zm6q1hoeJuaW4gmggkTRbn4oAUGh8nIAbrAotmkaKgC+hXLEfgAkAHKwMWk1bIhEAB5YeKBk0CSCgoREDk7YAMI0WFpZuMLWohZK1ZXSa6Cc3BaNovYARrtEwh7Y2gDmchuIcr2m0WMNFAB0s5gBi8L8sEJiSSySSiORKaxJLyWLoaMgBC6OXA4VwYASCCx-AE+WShcEaRL2bjYFFo4JsfE7AAWKEEb0hPEUqP+tO0un0hk8RHJoGqyEiWRixNx6UYuHs2C0VJpbyZQjeUUFrjxFIynIsuGptPpmwpmWyvgoeUlRSlWqIuCMyXcnLCpplaPlE0czmtyUkuQCwWCOp5ZOsvN5iBAoHsghIVyIyEQp0sNsUqkGsHsWlwFi09jQR2coE60a4PCkhoCCmUKh2+YsdAAks1pgQAKIAWXrzQAKnQc9UukMRmNZsnTNhQI8BS8mLgPnNvinhOswdZWXoDJaoSuGcpEwOLAAGHkw0DB+m+bBXTSQUCwc8x1RwregdOZ5w1HOx5IvkhaDjWOzOoeKV2mO6RaBNIwF1KqyT7gqLrChSoripKrjpBowjEJMzifPMizIfii7smu8hKBq0p4cunK8iq+I-lMhHEbS1HOBRlEHmAR4YCQ2AkLQKDnpe5bcKWt4pmmGZZtgz5lh+X7MTYArOIRSoQYBGQCr6trCLYKDFAeMhMRSwAyOkfoaAGiBAA

**Comment by Goodluckhf** [comment]
+1 I have the same issue.

**Comment by SamChou19815** [comment]
Closing this since the example uses the unsupported `$Subtype`
