### ISSUE TITLE
Should flow rewritten from scratch with better tooling ?

### ISSUE THREAD

**Issue by sagarrayudu** [facebook/flow#6554]
If this is a bug, please try reproducing using https://flow.org/try/.

**Comment by TrySound** [comment]
No

**Comment by sagarrayudu** [comment]
@TrySound Is that mean flow already had better tooling ?

**Comment by TrySound** [comment]
It's improved with every release. Do you know flow has lsp (language server protocol) support which is universal for a bunch of editors? Error messages a few releases ago became realy nice. Linters do a great job on making your code stricter.

Just watch at commits. They are like a blog.

**Comment by sagar12861** [comment]
@TrySound I love to adopt to flow and we are using it our project. but now it is like using nothing. because of windows issues. At some point we are unable to enforce static typing. It would be great if this tooling is improved. I’m not sure of very recent releases.

**Comment by TrySound** [comment]
Yeah, there was some problems when I was on windows. But all I have to do is to rerun flow a few times per day. I used neovim with ale. It worked stable enough for me. I think most issues are related to bad IDE integrations, mostly webstorm.

**Comment by sagar12861** [comment]
But if you could view pull requests like #6424 developers are crying for help. In my case it it restarting frequently. It is turning unreliable. Can these issues be taken as priority so every one can use flow as it advertised ? Or I There is a pull request that I have created to update the documentation ? https://github.com/facebook/flow/pull/5659

**Comment by mrkev** [comment]
Closing because:

- Re-writing flow is tangential to making it better.
- The issue has the default text.

But with that in mind, I'd be happy to help review a full re-write. Feel free to submit a PR and tag me in it ¯\\_(ツ)_/¯

**Comment by mrkev** [comment]
@sagar12861 I'm sorry it's not working properly for you-- flow is far form perfect but that' doesn't mean flow is not being worked on, as you can see by the commit history. Unfortunately, a limited number of people work on it and not all bugs can be worked on with the same priority.
