### ISSUE TITLE
Type 'string' is not compatible with type 'mixed'

### ISSUE THREAD

**Issue by vale-riia** [facebook/flow#6559]
Hello, 
I have run into an interesting problem which you can check [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sws8AKAWwE8A1AQwCcAuMWgFRoAcBTASjBsAbnEIATMAG8Avunw9e7Glz5gAvNIDaAZ3xNC2AOYBdNlUIAPXuLkYcBYqVoAxOHAr8pqMGGHMwTG5xBnwlNilsBipeNj0DYwAaMAk4-UMjGQ1pAHIomJy2ACIGIuSciUKwItwiuV9yXAogkLD+AG5UOSA)

```js
/* @flow */

function func1(myVar: myType) : void {}

type myType = {[string]: mixed}

function myFoo(){
  var update : {name: string, id: string} = {'name': "a", 'id': "c"}
  func1(update);
}
```

So basically i want to make strict type for the variable i pass into `func1` and make `myType` more generic. This does not seem to be possible. At the moment i am getting this error:

```js
 func(update);
          ^ Cannot call `func` with `update` bound to `myVar` because string [1] is incompatible with mixed [2] in property `id`.
References:
8:   var update : {name: string, id: string} = {'name': "a", 'id': "c"}
                                     ^ [1]
5: type myType = {[string]: mixed}
                            ^ [2]
9:   func(update);
          ^ Cannot call `func` with `update` bound to `myVar` because string [1] is incompatible with mixed [2] in property `name`.
References:
8:   var update : {name: string, id: string} = {'name': "a", 'id': "c"}
                         ^ [1]
5: type myType = {[string]: mixed}
```
If i make 1-to-1 match, then i don't get any errors (for example when i declare `myType` as `{[string]: string}`). 

According to the [documentation](https://flow.org/en/docs/types/mixed/#toc-anything-goes-in-nothing-comes-out), `mixed` type in `myType` should work but apparently it does not. Is there anything i am doing wrong or is it a bug?

Just some additional experiments: 

```js
/* @flow */

function func(myVar: myType) : void {}

type myType = {[string]: string | number}

function myFoo(){
  var update : {name: string, id: string} = {'name': "a", 'id': "c"}
  func(update);
}

```
gives me this error:

```js
func(update);
          ^ Cannot call `func` with `update` bound to `myVar` because string [1] is incompatible with number [2] in property `id`.
References:
8:   var update : {name: string, id: string} = {'name': "a", 'id': "c"}
                                     ^ [1]
5: type myType = {[string]: string | number}
                                     ^ [2]
9:   func(update);
          ^ Cannot call `func` with `update` bound to `myVar` because string [1] is incompatible with number [2] in property `name`.
References:
8:   var update : {name: string, id: string} = {'name': "a", 'id': "c"}
                         ^ [1]
5: type myType = {[string]: string | number}
                                     ^ [2]
```
So it looks more like a problem of having 'loose' rules for object typing.

**Comment by apsavin** [comment]
[Fix](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sws8AKAWwE8A1AQwCcAuMAEgCUBTBgEwDy2GDQA8tACo0ADtwB8ASjBsAbnEJ8wAbwC+6fDO5hJhsAF5tAbQDO+JoWwBzALpsqhAB7c+ejDgLEpLQAYnBwFApaqGBgKsxgmNJ8DPhGbFrYDFTcbLb2TgA0YBq5dg6OOubaAOSZ2dVsAEQMjUXVGg1gjbiNejHkuBSJyakKANyoekA)

**Comment by apsavin** [comment]
It's because you can mutate "external" object inside a function.

**Comment by apsavin** [comment]
Works as expected.

**Comment by vale-riia** [comment]
@apsavin Thank you! 
Although, if i have [this use case](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sws8AKAWwE8A1AQwCcAuMAfgBIAlAUwYAmAeWwwaAHloAVGgAdeAPgCUYNgDc4hAWADeAX3T45vMNONgAvGADO+JoWwBzMAB8wAIzhwY-Um4CCTEwMElSEAB68AgquugDatvZOALqqphFRBhg4BMSktABiXhRKOqhgZDkUAETVSgDc5ZWUcQDMrclKqFmoQA) then i have problems with instantiating $ReadOnly with primitive types. Is there any workaround for this?

**Comment by apsavin** [comment]
Like [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sws8AKAWwE8A1AQwCcAuMAfloBUaAHAUwCUYNgDc4hACZgA3gF90+PvzDdlYALxgAzviaFsAczAAfMACM4cGPwakzAQSZMGNADxVCAD36SAfKZgACQASraSAPLYMO4yANq6+kYAuiKq3r5yfujkBMSktABiVhSCMqhgZDi4FABEtYIA3BVVlHEAzO3JgqgK6EA)?

**Comment by vale-riia** [comment]
@apsavin right =_= Thanks a lot for help!

**Comment by apsavin** [comment]
You're welcome! Please, close the issue if you have no other questions on the topic.
