### ISSUE TITLE
No way to refine types

### ISSUE THREAD

**Issue by Diggsey** [facebook/flow#6560]
Using the spread operator has been previously recommended to use instead of intersection, because intersection doesn't behave in the way most users expect. However, the spread operator also doesn't work for refining types:

```js
type X = {a?: string, b?: string}
type Y = {a: string, ...X}

const x: X = {}
if (x.a) {
  const y: Y = x
}
```

This is a very common case that seems to be impossible to represent with flow. Using exact objects instead doesn't appear to help.

**Comment by apsavin** [comment]
Could you please provide a link to flow.org/try with a repro?

**Comment by apsavin** [comment]
Could you please provide a link to flow.org/try with a repro?

**Comment by Diggsey** [comment]
https://flow.org/try/#0C4TwDgpgBAGlC8UDeBDA-ALigZ2AJwEsA7AcwBooAjTHfYkgXwChRIoBNBZFLXQ0igDphMZkwDGAeyK4oADyxxESZgQBmUABRzBKAJTImUKFJnAoILJ0RymDIA

**Comment by jcready** [comment]
This is because both `x` and `y` would share a reference to the same object and since all of the properties of the type `X` are writable it would allow you to do this:

```ts
const x: X = { a: 'string' }
if (x.a) {
  const y: Y = x
}
x.a = undefined
// oh no, `y.a` is no longer a string
```

However, if you spread `x` then everything works as expected:

```ts
const x: X = { a: 'string' }
if (x.a) {
  const y: Y = { ...x }
}
x.a = undefined
// `y.a` is still a string
```

P.S. the check of `if (x.a) {` won't pass for an empty string. A better way to refine this would be by using `if (typeof x.a === 'string') {`

**Comment by Diggsey** [comment]
@jcready It's also inconsistent with how flow treats nullable fields:

```js
type X = {a: ?string, b?: string}
type Y = {a: string, ...X}

const x: X = {a: 'hi'}
if (x.a) {
  const y: Y = x
  x.a = undefined
  console.log(y.a)
}
```

This suffers the exact same problem, and yet is accepted by flow.

**Comment by villesau** [comment]
Even when moving `a` definition after spread & making everything exact & read-only it still fails:

https://flow.org/try/#0C4TwDgpgBAGlC8UDeAfKBqAhgfgFxQGdgAnASwDsBzAGgwCM9CSLKoUBfAKFEigE0EyNADpRMWlnxEyVDp04BjAPbkiUAB744iJFEz4A5MQjGDULqQBmUABTrhmAJTJOUKMtXAoIfAMTrOdiA

**Comment by jbrown215** [comment]
This has nothing to do with spreads. You can just copy the properties into the object directly to make the repro.

This also just isn't how Flow does refinements. That refinement on x.a refines x.a, not x itself. [See here for a smaller repro](https://flow.org/try/#0C4TwDgpgBAglC8UDeBqMB+AXFAzsATgJYB2A5gL4DcAUKJFAEILJrZ5FlXXUAmEAxgBsAhvmgA3UVGHYYNaoQBmUABTCAdGCgBCRMQCugwQEpk1KKo1g2BEqWOUoAeidQAShEUkIPc5ewMDs6uEPj4APb46tJQhDjEAOTAUGJexD5QwOEx6QDumeAQADRQ4cSCINKasTjU5EA)

**Comment by jcready** [comment]
>This also just isn't how Flow does refinements. That refinement on x.a refines x.a, not x itself.

Why _shouldn't_ Flow be able to do refinements that way? In your example:

```ts
type A = {+p?: string};
type B = {+p: string};

declare var a: A;

if (a.p != null) {
  (a.p: string); // Refined
  (a: B); // error. a isn't refined to a new type, only a.p is
}
```

How is it unsound to mark `a` as being type `B`?

**Comment by jbrown215** [comment]
Both behaviors are unsound. This is just an instance of where Flow is incomplete. That's why we made disjoint unions-- to explicitly support cases where you need to distinguish between branches of object types.

**Comment by goodmind** [comment]
@jbrown215 You probably meant example like this
```js
type X = { +a?: string }
type Y = { +a: string}

const x: X | Y = { a: 'rere' }
if (x.a) {
  const y: Y = x // error
}
```
[link](https://flow.org/try/#0C4TwDgpgBAGlC8UDeUDUBDA-ALigZ2ACcBLAOwHMoBfAKFEigE0Fk11cCSLaaBjAe1IEoAD1xwAPkxYp2UAOSEIS+dRrEAZlAAUIgHToAlMhpQoAocCghczRCKgB6R1GWF+hGlSA)

**Comment by jbrown215** [comment]
I didn't, but it does further illustrate my point. Flow has strictly more information in that code sample and _still_ does not refine the object type.

**Comment by villesau** [comment]
If one would want to fix such issue, where to start digging & debugging?

**Comment by jbrown215** [comment]
I think this is a fundamental change to our refinement model, which is pretty limited.

**Comment by jcready** [comment]
This change would be a huge improvement.

**Comment by jbrown215** [comment]
Certainly, but maybe not feasible to implement in a way that is performant.

**Comment by SamChou19815** [comment]
Expected limitation since we don't support refining one object type into other
