### ISSUE TITLE
Generic types in unions aren't resolved properly

### ISSUE THREAD

**Issue by Jasyer** [facebook/flow#6562]
I have [this](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQQMYoCWsAdgIwA8AKgHygC8oA3qOtgFyjUA0oGAQzRwBAEy6kArgFsARlgBOoAL4BuVJhwFiZAEw16TVuyxde-ISPGgAzigVFSAcxXqN2PIRKka5PtV1DTx0KX3oAH2DvfQDadXwyO1B8BSwBFCwAJSxRSXxFRlBff0CAChNyMz82TV0zXQBKRnpSgS8yLm1vYu5ApoZ6ZkRQW3giFHwAC1b20gA6EyahkZH8ARscCo5hlZGZkIXNKob1Xb22g8FhWDEJGXkFE53d2VSBAGs3XbWNmuw654rfbeQ6cXpPM6gYFkOZXKxcOwOZwQs6vNKfHbKRDKIA) code:
```
// @flow

type Action1<T> = { type: T, payload: number };
type Action2<T> = { type: T, payload: string };

type Action<T1, T2> = Action1<T1> | Action2<T2>;
const createReducer = <T1, T2>(type1: T1, type2: T2) => (action: Action<T1, T2>) => {
  switch(action.type) {
    case type1:
      (action.type: T1);
      (action.payload: number);
      break;

    case type2:
      (action.type: T2);
      (action.payload: string);
      break;
  }
}
```
Flow couldn't resolve the type of `action.payload` in each case of the switch:
```
11:       (action.payload: number);
           ^ Cannot cast `action.payload` to number because string [1] is incompatible with number [2].
References:
4: type Action2<T> = { type: T, payload: string };
                                         ^ [1]
11:       (action.payload: number);
                           ^ [2]
16:       (action.payload: string);
           ^ Cannot cast `action.payload` to string because number [1] is incompatible with string [2].
References:
3: type Action1<T> = { type: T, payload: number };
                                         ^ [1]
16:       (action.payload: string);
                           ^ [2]
```
Is this behavior correct? I expected this code to be correct. If I replace some generics with string literals flow [won't show](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQQMYoCWsAdgIwA8AKgHygC8oA3qOtgFyjUA0oGAQzRwBAEy6kArgFsARlgBOoAL4BuVJhwFiZAEw16TVuyxde-ISPGgAzigVFSAcxXqN2PIRKka5PtV1DTx0KX3oAH2DvfQDadXwyO1B8BSwBFCwAJSxRSXxFRlAAChNyLgByMixyvhNdCpR4WHKASkZ6IoEvMi5tb0pK0mq+csbm2jaGemZEUFt4IhR8AAtO7tIAOhM2mbm5-AEbHFKOWb25tZCtzQqq1vVzi66rwWFYMQkZeQUWh8fZVICADWbnOByObE09TO50u3munFAoya9xhezhZA2rysXDsDmcvzRcwBaRBZ2UiGUQA) any errors:
```
// @flow

type Action1<T> = { type: T, payload: number };
type Action2<T> = { type: T, payload: string };

type Action<T1, T2> = Action1<T1> | Action2<T2>;
const createReducer = (type1: 'one', type2: 'two') => (action: Action<'one', 'two'>) => {
  switch(action.type) {
    case type1:
      (action.type: 'one');
      (action.payload: number);
      break;

    case type2:
      (action.type: 'two');
      (action.payload: string);
      break;
  }
}
```

**Comment by stereobooster** [comment]
This will not work, because type checker can not be sure that `T1` doesn't equal to `T2`, so if you replace it with exact types it can prove it.

**Comment by Jasyer** [comment]
Oh, this is true. Thanks, @stereobooster.
