### ISSUE TITLE
I get errors when this types are in separate files, but not in a single file.

### ISSUE THREAD

**Issue by esbenvb** [facebook/flow#6563]
I get this error when the type definitions are spread around my code base (where they belong).

But when I copied all types into the Try Flow tool, I get no errors. I also don't get errors when I copy all this to a local file in my React project and run flow check. 

What can be wrong?

```
yarn run v1.7.0
$ flow; test $? -eq 0 -o $? -eq 2
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/store/selectors.js:40:10

Cannot return reduceKeyedList(...).sort(...) because:
 • enum [1] is incompatible with string literal done [2] in type argument ActionCode [3] of array element.
 • enum [1] is incompatible with string literal payment_timeout [2] in type argument ActionCode [3] of array element.
 • enum [1] is incompatible with string literal prepare [2] in type argument ActionCode [3] of array element.
 • enum [4] is incompatible with string literal cannot_prepare [5] in type argument StateCode [6] of array element.
   element.
 • ... 28 more errors.

        src/store/selectors.js
 [1][4] 32│ ): Session<PaymentSessionEntryActionCode, PaymentSessionState>[] {
          :
        37│   entityId: EntityId,
        38│   state: State
 [2][5] 39│ ): Session<RobotSessionEntryActionCode, RobotSessionState>[] {
        40│   return reduceKeyedList(state.robots[entityId].sessions).sort(sortBy('started'))
        41│ }
        42│
        43│ export function messageHasBeenHandled(messageId: string, state: State): ?boolean {

        src/types.js
 [3][6] 40│ export type Session<ActionCode, StateCode> = {|



... 28 more errors (only 50 out of 78 errors displayed)
```

(Keep in mind that I have removed some action and status codes, for readability of the code and the error messages.

[Code is here ](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AJVgEawoDKWAzuQJawB2JKAhigK7kDCsAJjgLyKhQAH1AByAPrjasceQrU6k0QOFiudLMtSYc+IqXk1aAUQBOp2Kc49Q-QSNEBjRrWkpxGU1gyMvy+2JylEbiVLQoWKa0jNDikRamWujYeITEZMF0AOq+tGEA5tZ8Kg5hEeYsGBFc4gRo4myR-qqiZfGV1bX1crTkllpYAB4YliigybppBpn0TBG2Jan6GQom5pZFi3rphnQMzGybAdvTqzlRBZvaKScrRsaD5dHQAIKOKEZFtmKMRKYoygmSx2MwAkuFIs83h86F87C1JOQmP9ZLtaEpFhJZMj3F5ICwsNAChiAljfqNxHiCUTaPkMddJvozAk4WJnK5iKE8h8YlQAF6aFptKIxOLrRIM4GkOaHbh8QI4gqiFrkAAWLBQH1p4nU8FoytKXGggockjclKwjEcqt+xoxQxG-3GOil+3mvClzI2ctUtxlHB9IluaLdWEQDtGzpuU2MADcsOFoZ8ffCHF5GFw0M0HOzzWEqDyiQKki6TgAZKhI74kNBIrAAWwrSIAPH7mFgADSutHGcKmNBJ2FyrvBmahgB8yHDw0jQIAKqYXOQrTDaKCuN8kaYCtPHWMgaCSAB5AAcADYAAwARjnVHrFCY9Ywm5Q29pu9nLrnsAwVEcL7ffIPydIEAFl5EYfJ5QAbyEFQAGoUB-P8AC5QC3AoOwQxw6AicI0KPAgACssHeLChAAX2A-cXXBDANVwCgWGgMYPWg0AAG06I1ABpLA0AAXTQ7iUAANRiAlQCoiMQNo2h6JQPi0AAncD3kjVxOgSSPQw98ZJom4mJY1lRHifoWngXIlRVFhHEceQBhnWSUl7V80GbQdaCKLs7j2OYsHHb5YJUG1yAAISwBMAAkXCNLAuDQohYGNFwsMED57yRRgn2E49z2vW9MsfDA0tABsC2qcDKEgrAAH40Kq5coNK18qHyKDTEamr6tALrmpULKIjQ3zZnbUrrVgHpPKKHrpuHFQuGYRgepExjyGYlByKo5B9KjRkQVWVz+zmmxU27GYHieGITrDY4phG8Erted5kx4HanIMnAazres4wTFAjvc0MikCti4MEeDBqwYb-O8hCMofbKMFy09LxvO9EafUr4PKzV4r66Heog-rKKnai9tAEaPJeoceB82G5VB0BgsEKGYfbOHBH+gs0HXNDXJ59cWsXXoVyMPnQAXJcxboIWBpxeKUfy9GiqR0r-u3Ch+b7dybvpjnGY4gTSsWpgVvUlA1o20qvHWlieqt4z5tJ969wpkamxQanV28ymGZ4JnoJUDipdFmm1y4ITKbRb3Xs7P2DYDrDpI+imBfQdcVPfV3PxSUMgvB0ALH0cg0PLStNsQF3dqBb6InrZtgeHaOZj1lvVibgOC4Q7mM4S0B095rhSvIWt67+8JS8pseGwngGdcb-2AqN8aWHMf7Q+XcOJdqzeZYjkf-PZiJOfQtEp49ivG7RNuRs7gKtpz5yvpnxsr-vnyb-D3276XwPg8HuuKOdcGyL0TvHEat8Qx-2TogHCvQxh9H+GFZSHoAAUkAqCEn7rpfIABKWwgU0GMAIsRUim1QAEFISRd4BDeCTkECAMq5AaQoAALRcErLaLAbDaBDHYTSHA0heEPnimwq6-YVCMAAHQIyyk+WwvAPQEA4pg7BAlQC1VABeUAaFGCqKwdASOoBAoqLUUYjRWi2FXl0aAK8yB4FVi8FwWyWAlLxU9t8NBhAaEoGoeQuhDDQCEV8dIgA1vxcg3iyG0Okc41xaC0G22tqACJaBAmcWkVk5JLEuw+PIRxNJAljacQEngp+Yx8S0HDkXe6580EqF7kPbWHw+6H3bMfMMeDhox1HIdHWbc+lGAnEbZmKgvCsCiEXeKrj3FcE9mgqGcSpjkA4k0oB0igirHIHgzZoxFmjBQWg0QWV-jxVEHg8pVEgA)

**Comment by SamChou19815** [comment]
It should be fixed by types-first a while ago
