### ISSUE TITLE
"indexer property missing in mixed" error with Object.keys

### ISSUE THREAD

**Issue by chucksmash** [facebook/flow#6564]
I've included two snippets below (verified on https://flow.org/try) that I believe should be equivalent from Flow's perspective. The first snippet passes type checking while the latter fails it.

``` javascript
/* @flow */

// equivalent working example
const canLogKeyValues = (val: mixed): void => {
  if (val instanceof Object) {
    for (let key in val) {
      console.log(val[key]);      
    }
  }
};
```

``` javascript
/* @flow */

// fails!
//   12:       .forEach(key => { console.log(val[key]); });
//                                               ^ Cannot get `val[key]` because an indexer property is missing in mixed [1].
//        References:
//        9: const cannotLogKeyValues = (val: mixed): void => {
//                                            ^ [1]
const cannotLogKeyValues = (val: mixed): void => {
  if (val instanceof Object) {
    Object.keys(val)
      .forEach(key => { console.log(val[key]); });
  }
};
```

**Comment by apsavin** [comment]
[Fix](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAwENts58AZOAcwGkBTATwDViYBXB3MAXjAAUAN3YAuMAFsAlgA8GAEwCU4oXCny+APjABvVGDBSogkTEN58pDAzjGA8gCMAVgwz5Fu-QaI4CYAE4MUFLYCmxm-KYA3F4Gji5uAHQA1sy4AoHBofLhirHeiVBw-gCixBgAFgKpTFq6PnhwMAyJ8DQZQSFh7ADaNQC6ilFgAL5DXiOoI1FAA)

See #2715

**Comment by chucksmash** [comment]
Great, thanks for the tip and the issue reference @apsavin
