### ISSUE TITLE
Variable keep being typed as Promise event after async / await

### ISSUE THREAD

**Issue by alburkerk** [facebook/flow#6571]
**Reproduction :**
[Try it](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoA1pqgFygDOyATgJYB2A5gL4DciiAxrMzqgAhpTyEiiUGQrUA5MLkAaRFx5osoAEIFiU0JFixqzAK4BbAEaZ6K6ZeH1qdJm1Xc+AoYdi6AFACUlAAK9LDmjDSYADw4AHwECZIAkPSYyKb0zKDMmPCgoeGRmH6Qpsy8yIwCfmk0sNAAbphKoGkAVpiVAZLS0slRyAAqjOaYsKbIpeWV1cyBvX1LqZj1TSXCAdxLS+ytAIwADMdb+tLsp+w8-ILIoA70usI0qBWggWKJesk3QnWfhD8fmE8GEjDuPkCQWEzFQp1AKwyWTaq24V0QQA)

**Context :**
When calling a function called 'foo' returning a promise with await, the type of the variable is still Promise.

Flow correctly interprets the value if we just return the variable, but triggers an error if we type the return of the function called 'bar'.

Is there any issue / PR related, or a common workaround ? Casting with any didn't seem to solve the error.

**Comment by sibelius** [comment]
The return of the function is a Promise<T>

After await is only T

The behavior is correct
