### ISSUE TITLE
0.76 Changelog error is wrong about [silence] - should be [declarations]

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#6572]
See https://github.com/facebook/flow/pull/4916#issuecomment-400029607

It was renamed `[declarations]` according to the last comments for the PR.

The commit message for https://github.com/facebook/flow/commit/433581b51b44f345e7ffa9ba8b78487da245d7dc also is wrong, it says [silence] while the actual code says [declarations]

**By the way,** when this is documented some day I hope there will also be an explanation for the name "declarations". The previous choice "silence" was more or less obvious to anyone, "declarations" requires internal knowledge about "decl mode" that most Flow users are completely unaware of (I never heard about it before reading through the PR discussion). I think it's unfortunate that **a naming that exposes internals** was chosen, I think one should aim to name things meant for external consumption based on the outside view, not based on what's (well hidden) inside.

**Comment by vladshcherbin** [comment]
Yep, *declarations* is a terrible name. Impossible to understand, why it was chosen instead of *silence* and what it does

**Comment by gabelevi** [comment]
Ah, sorry, when I put together the Changelog I went based on commit messages. And I think the commit message on the imported diff never got updated when the feature was renamed 😢

**Comment by mrkev** [comment]
(yup, myb!)

**Comment by sibelius** [comment]
```jsx
[declarations]
.*/node_modules/.*
```

declarations is not working for me, 

it is still showing errors on node_modules

is this the right way of using declarations?

**Comment by lll000111** [comment]
@sibelius Probably this: https://github.com/facebook/flow/pull/4916#issuecomment-404096245
