### ISSUE TITLE
BUG: Implementing imported interface creates errors with async fns

### ISSUE THREAD

**Issue by leebyron** [facebook/flow#6576]
If a class implements an interface imported from another file, and then an instance is returned from an async function, an unexpected incorrect error is produced. 

If that same interface and class are located in the same file then no error is created as expected.

I have a minimal repro up here:
https://gist.github.com/leebyron/d94b159284644575906ac17cdc3e34a9

Test this out yourself with:

```
git clone https://gist.github.com/d94b159284644575906ac17cdc3e34a9 flow-implements-bug
cd flow-implements-bug
npm install
npx flow check
```

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
