### ISSUE TITLE
Declaring types for external library that defines a base class?

### ISSUE THREAD

**Issue by girvo** [facebook/flow#658]
Hi there,

Love Flow, amazingly well done. I'm curious what the best way to `declare` an external module's type signatures should be, where the module exposes a number of classes that your app level code extends?

The library I'm specifically discussing is [Flummox](https://github.com/acdlite/flummox), a Flux implementation; it's a fairly dynamic and "magic" library, however I believe there are some nice ways of taking advantage of Flow while using it.

A good example would be Stores. 

```javascript
import {Store} from 'flummox';
import type Flux from '../Flux.js';  // This is our class, extends Flummox and registers all actions and stores

type TodoState = {
    todos: [Todo];
}

type Todo = {
    name: string;
    complete: boolean;
}

class TodoStore extends Store
{
    state: TodoState;

    constructor(flux: Flux) {
        var actionIds = flux.getActionIds('todos');
        this.register(actionIds.completeTodo, this.handleCompleteTodo);
        
        this.state = { todos: [] }; 
    }

    handleCompleteTodo(index: integer): void {
        var todos = this.state.todos.slice(0);
        todos[index].complete = true;
        this.setState({ todos: todos });
    }
}
```

In that Store object, the key methods are `setState` and `register` (and it's counterpart `registerAsync`). I've constrained the `setState` method to only operate on the `TodoState` type, by overriding `setState` with my own definition that merely calls `super.setState(newState)`: this works well enough.

The big one is `register` -- I don't know how to `declare` the type signature of it, without overriding it, which isn't ideal as it's the same signature for every `Store` child class.

How is this handled, typically?

Cheers!

**Comment by popham** [comment]
I read this.  I'm not going to study the source code of external libraries and reverse engineer what you have done to figure your question out.  It's time consuming and of no benefit to anyone but you (unless I document what I've learned and reverse engineered).

Pose this as a toy problem (fewer lines of code the better) that I and others can understand without consulting external references, and you might get a useful response.

**Comment by samwgoldman** [comment]
@girvo It sounds like you just need to declare the class in a declaration file. Please look at the documentation for guidance on this. There are two sections in particular that will help you out:

1. http://flowtype.org/docs/third-party.html#example
2. http://flowtype.org/docs/declarations.html#_
