### ISSUE TITLE
Feature Request: support Regular Expression named capture groups

### ISSUE THREAD

**Issue by 1pete** [facebook/flow#6581]
Flow considers match result from regexp execution as an array, therefore there is an error when trying to access `groups` from match result

flow version: 75, 76 (current)
[flow try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzACcBTAcxIA8AHMAXjGAD0AKAfgB4BPEgQyIB8AHQAmAbwAsAXwCUAWnYcAtjnwALYeIBMshZxG98JTWJ0yAJGix5CSwxjUAlErgCuMQg1IUaAOiokGCwA5FoADACMABxyYQDssQCcwTLoAJZQYCx2+A7Obh4yYGKoAJDWBMVgZERwrtS4AFxVPPwANGAq2OodBkZgUgP0nfZOLu74qFJAA)
```js
/* @flow */

const regexp = /^(?<year>\d{4})-(?<month>\d{2})-(?<date>\d{2})$/
const matchResult = regexp.exec('2018-07-09')

if (matchResult) {
  const { groups: { year, month, date } } = matchResult
}
```
```
../-:7: 	const { groups: { year, month, date } } = matchResult
                 ^ all branches are incompatible: Either property `groups` is missing in `Array` [1]. Or property `groups` is missing in object type [2].
References:
[LIB] ..//static/v0.76.0/flowlib/core.js:239: declare class Array<T> extends $ReadOnlyArray<T> {
                                                            ^ [1]
[LIB] ..//static/v0.76.0/flowlib/core.js:332: type RegExp$matchResult = Array<string> & {index: number, input: string};
                                                                                        ^ [2]
```

note: flow version 74 or older doesn't consider this pattern a problem.

**Comment by 1pete** [comment]
This might relates to #6374

**Comment by mrkev** [comment]
Type is defined here:

https://github.com/facebook/flow/blob/069315bf646cb3f0428812133a93310b901e45d5/lib/core.js#L332

Feel free to PR and tag me 👍

**Comment by peterdm** [comment]
This seems to be broken again.  See try link from OP above.

**Comment by jamesisaac** [comment]
@peterdm `groups` exists in the typedef, but it's an optional type, so you just need an extra check in the if statement:

```js
if (matchResult && matchResult.groups) {
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzACcBTAcxIA8AHMAXjGAD0AKAfgB4BPEgQyIB8AHQAmAbwAsAXwCUAWnYcAtjnwALYeIBMshZxG98JTWJ0yAJGix5CSwxjUAlErgCuMQg1IUaAOiokGCwA5FoADACMABxyYQDssQCcwTLoAJZQYCx2+A7Obh5gAGRFYDl5Lu74vmREcK7UuDJgYqgAkNYELWC19Y0AXN08-AA0ZapqYwZGYFKz9GX2TpUeqFJAA
