### ISSUE TITLE
Incompatibility with Bluebird Promise.all() libdef in 0.76

### ISSUE THREAD

**Issue by af** [facebook/flow#6583]
Hi, we're trying to upgrade from 0.75.0 to 0.76.0 but running into the following incompatibility between bluebird's libdefs, and Flow's own core definitions. At first glance it looks to me like bluebird's libdefs are more correct, but I could very well be wrong.

The [latest bluebird libdefs](https://github.com/flow-typed/flow-typed/blob/1cb1933212cbbd6c94ea28b2fcda57fba53b6cf0/definitions/npm/bluebird_v3.x.x/flow_v0.70.x-/bluebird_v3.x.x.js) take a second type parameter for `Promise.all`, while flow's own core definitions only have a single type param. It doesn't look like either's definitions have changed recently and I can't reproduce this error in 0.75.0, so I'm not sure why it's only causing an issue now. When starting up flow on our codebase, we get the following error highlighting the mismatch:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ /private/tmp/flow/flowlib_2a72e5de/core.js:608:5

Cannot use function type [1] with less than 2 type arguments.

     /private/tmp/flow/flowlib_2a72e5de/core.js
     605│
     606│     static resolve<T>(object: Promise<T> | T): Promise<T>;
     607│     static reject<T>(error: any): Promise<T>;
     608│     static all<T: Iterable<mixed>>(promises: T): Promise<$TupleMap<T, typeof $await>>;
     609│     static race<T, Elem: Promise<T> | T>(promises: Iterable<Elem>): Promise<T>;
     610│ }
     611│

     flow-typed/npm/bluebird_v3.x.x.js
 [1]  60│   static all<T, Elem: $Promisable<T>>(
      61│     Promises: Iterable<Elem> | $Promisable<Iterable<Elem>>
      62│   ): Bluebird$Promise<Array<T>>;



Found 1 error
error Command failed with exit code 2.
```

**Comment by arabold** [comment]
Same issue here. Happens only on 0.76.0, not on 0.75.0. It seems every time `flow-bin` is updated the Bluebird definitions break 😢

**Comment by EvHaus** [comment]
FYI: This is fixed for me on the latest version of the bluebird libdef + flow 0.78.0

**Comment by dlam** [comment]
It looks like this PR addresses this issue https://github.com/flow-typed/flow-typed/pull/2509/files

**Comment by af** [comment]
Confirmed, with the latest libdefs and flow 0.78.0, I'm no longer seeing this issue– closing this ticket
