### ISSUE TITLE
Spread operator provide the way to skip type checking

### ISSUE THREAD

**Issue by arthurgubaidullin** [facebook/flow#6586]
The following [code](https://flow.org/try/#0C4TwDgpgBATgblAvFA3gbQM7BgSwHYDmAugFxQC2OAHhACYC+A3AFDMDGA9nllARMACV+ANQCGAGyRQAFAEoyAfnhIAfDJTAIWMgBYATPVktmoSFFqjgoqSgA+zAJCbtUAEYcO4iKLzNbTVk5uYChgDgBZEAAVcGhkaTgyeHlzS2tENRQoKAds5myHGH4AVxg8VAA6KrgmKAB6Oqg8DigIGBgOGBkAdw7CWWYA9i4eLuQ+QREJORYcADMZLoBCRGQ8YvFJADIt2CgV5GK8Wgg5-DpZVFCI6NjpGCMoemzsoA):
```javascript
type rv = {[string]: mixed};

const getRetVal = (): ?rv => ({test: 42});

type data = {|
	test: boolean
|};

const toMyType = (v: rv): data => {  	  
  	return {...v}; // no error (wrong)
};

const r = getRetVal();
if (r !== null && r !== undefined) { toMyType(r); }   
```

Does not produce an error as expected.

**Comment by SamChou19815** [comment]
It now correctly errors
