### ISSUE TITLE
Request: Extract function parameters with Generics

### ISSUE THREAD

**Issue by Zaggen** [facebook/flow#6588]
I think is a common pattern in a very flexible language like js to take some method/fn and map it with different signature but some of the original arguments.

For example In [rematch.js](https://github.com/rematch/rematch) you have a set of reducers that take 2 parameters (`(S, P) => S`), and that is later dynamically mapped to function that only take the second param (payload) `(P) => void`.

Right now I know is possible to extract return types using the deprecated `*` or via `$Call`, but I don't see a way of extracting the params data, not sure if there is no support for this which would be great, there is a bug or I simply don't know how to do it.

[Try Flow](https://flow.org/try/#0C4TwDgpgBAShAmBXAxhATlAvFA3gHwCgooBLAO2TQgEMBnCALigB4BlJgeQCMArCZYAD4AFLWDVgjKKwA0UMNRAAbAPbV4TMogC2XdAEosg6TIJ4AvgQIB6a1AAqACxK0owNCWQBrKAHcVaF6uAGYBUFTAiGhkbuAQrlyIwFBkKsmhGApo1Nq0BKCQUADiEMAACtTZ2gD6zGVyAGJkTKLikkzUZCBQcgrKahpQZYaYxp0gxthl+XHFpRVVzPaTc+WVObUAVHLLVgXQACIuCsDIjui0AIxYUAAk3DwAstRgzHBIqGhyzE0iwc1QJojYwlNaLX5GKDjQQEYQ4UgUKh0KTCAAeTDEHjIAHNgVBUVBzEwjrQTmcLpdDLZpO5yNioLRHCpEEp4FA9AjkCptCcSFwlNBfCRgI4Ujo9GgiMRpTLZXKoDNCiSyec0LQAEw3e68Z6vd4odDfWRDRoA4TG4aQ1h-AFAyHCS2jKFdYzyt1y2Hw8iUGj0Frohm0nF4glEqDKiTktXqql2VhB+mM5ms9nQb3c3n8wXC0VaXToIA)
```
type Reducer = {|
  increase: <S: Object>(state: S, payload: number) => S,
|}

// This trick works for return types but not for params
type GetParam_<P, Fn: (state: any, payload: P) => any> = P
type GetParam<T> = GetParam_<*, T>

type Dispatchers1 = $ObjMap<Reducer, <Fn>(fn: Fn) => GetParam<Fn> => any>
({ increase: (x: string) => x }: Dispatchers1) // String should be incompatible with number but no error
                      
type Dispatchers2 = $ObjMap<Reducer, <S, P, Fn: (S, P) => S>(fn: Fn) => (P) => any>                      
({ increase: (x: string) => x }: Dispatchers2) // String should be incompatible with number but no error
```

There is a similar discussion for Typescript [Here](https://github.com/Microsoft/TypeScript/issues/24068) and based on some typings I found on the [rematch repo](https://github.com/rematch/rematch/blob/master/src/typings.d.ts#L36) theoretically you could do something in typescript like this (Though it didn't work for me on TS playground):

```
type Reducer = {
    increase: (state: Object, payload: number) => Object
}

type Dispatcher<P> = (P) => void

type ExtractDispatcher<R> =
  R extends (state: infer S, payload: infer P) => infer P ? Dispatcher<P> : Dispatcher<any>

type ExtractDispatchersFromReducer<R> = {
  [key in keyof R]: ExtractDispatcher<R[key]>
}

type Dispatchers = ExtractDispatchersFromReducer<Reducer>
```

Any thoughts on this?

**Comment by villesau** [comment]
This is pretty much exactly what would be needed for redux-actions:

```
  declare function createAction<T, A, P>(
    type: T,
    payloadCreator: (...rest: A) => Promise<P> | P,
    $?: empty
  ): {(...rest: A): { type: T, payload: P, error?: boolean }, +toString: () => T};
```

See: https://flow.org/try/#0PTAEAEDMBsHsHcBQjSgCYFMDG0CGAnDUSAVwDssAXAS1jNC0N0owEErayAeAagBUANKB6shPAAoA+ABQpUoSgE8ADhgBcoQXNTLciuLjQBhJpVj4N0gHQ3CAZ0obWASlABeSaHH5YAW2p2GFxSoAA+XgLaoAAkAPwaGL7KSnLOGgDe1rYYDk5poOnCSqoagsK6+rCGGuJiGPg++PGgAEawsNAYuPQAvmJmAMqU+NRkAOaWrh6aPQDcyBgAHsrmlAx0Dgo5a24MpmwcdLKoAOR8AJriAKInkajSuBoOI+NCLRpkJL4t9VOeAIwAJgAzIhnPN5PJECwHNITrgWlg0LdQMDAf9nEA

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/redux-actions_v2.x.x/flow_v0.39.x-/redux-actions_v2.x.x.js

Also [refetch](https://github.com/heroku/react-refetch) needs this.

**Comment by SamChou19815** [comment]
We now have support for `Parameters` type
