### ISSUE TITLE
HTMLInputElement is missing HTML5 properties

### ISSUE THREAD

**Issue by mroch** [facebook/flow#659]
From [MDN](https://developer.mozilla.org/en/docs/Web/API/HTMLInputElement):

> The following properties have been added: autocomplete, autofocus, dirName, files, formAction, formEncType, formMethod, formNoValidate, formTarget, height, indeterminate, labels, list, max, min, multiple, pattern, placeholder, required, selectionDirection, selectionEnd, selectionStart, step, validationMessage, validity, valueAsDate, valueAsNumber, width, and willValidate.

> The following methods have been added: checkValidity(), setCustomValidity(), setSelectionRange(), stepUp(), and stepDown().

**Comment by jeffutter** [comment]
I have run into this problem...using checkValidity() . Is there some workaround in the meantime? Is it possible to extend the predefined types dom.js manually?

**Comment by samwgoldman** [comment]
Pull requests to update the library definitions in `lib` are greatly appreciated! There is at least one issue open already for extending declarations provided by flow's lib files, but I don't think anyone is working on that. The workaround is to disable the flow lib (`--no-flowlib`) and copy the files in `lib` into your own project, then edit them there. If you're doing that, we'd really appreciate those changes upstream.
