### ISSUE TITLE
Array#concat should not reverse the types when used on tuples

### ISSUE THREAD

**Issue by ooflorent** [facebook/flow#6593]
It looks like `Array#concat` messes with types when using tuples.

```js
let a = [1, 2]
let b = ["a"]
let c = [...a, ...b]
c[0].slice(0)   // expected: err
c[0].toFixed(2) // expected: ok
c[1].slice(0)   // expected: err
c[1].toFixed(2) // expected: ok
c[2].slice(0)   // expected: ok
c[2].toFixed(2) // expected: err
```

When using spread, Flow matches our expectations.
However, when using `a.concat`, there are more errors:

```js
let a = [1, 2]
let b = ["a"]
let c = a.concat(b)
c[0].slice(0)   // expected: err
c[0].toFixed(2) // expected: ok
c[1].slice(0)   // expected: err
c[1].toFixed(2) // expected: ok
c[2].slice(0)   // expected: ok
c[2].toFixed(2) // expected: err
```

Some of them are really surprising:

```
5: c[0].toFixed(2) // expected: ok
        ^ Cannot call `c[0].toFixed` because property `toFixed` is missing in `String` [1].
References:
2: let b = ["a"]
            ^ [1]
…
8: c[2].slice(0)   // expected: ok
        ^ Cannot call `c[2].slice` because property `slice` is missing in `Number` [1].
References:
1: let a = [1, 2]
            ^ [1]
```

Reproductions (Flow v0.76):
- https://flow.org/try/#0DYUwLgBAhhC8EG0CMAaCAmAugKFJARnIgERTE54QDGRCAdA1Gg3fjlQgAyZ0DOwASyogAFJwCUEKQHppEEAA8ADiCpgQAEwBc8gE67sHbnTAB7AGICFmkekmz5y1eu0RTAa0PIe-IaIlSEA6KKmqaOiD6Xkg8ZpbWGrb2ciHO4W6eHFh8gsJikjIpTmGuHl7ZcVY2dkFFoS4R+kA
- https://flow.org/try/#0DYUwLgBAhhC8EG0CMAaCAmAugKFJARnIgERTE54QDGRUAdFQPYB2VUYAFPgJTZUIAGTHQDOwAJZUQHAdwjyA9AoggAHgAcQVMCAAmALhUAnI30HCwjAGLjVejujlKVGrToMRGAazNJhYyWlZeQhnNU1tPUMQE18La1t7R1DlcLcozx9+LFEJKRk5RVTXSI9vMxzLGztdBydiiPdokyA

**Comment by SamChou19815** [comment]
There is no special treatment for array.concat, so this is expected
