### ISSUE TITLE
Way to require the user to provide a type?

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#6597]
One of the flow-typed maintainers here...

I'm looking for a way to type a function such that the return value must be typed explicitly by the user for it to be correctly typed checked by Flow. Something like this:

```js
type TypeMe = $RequireType

const works: TypeMe<{ a: string }> = getJSON('{"a":"hello"}')

// $ExpectError
const shouldNotWork = getJSON('{"a":"hello"}')
```

The use case is valuable for libdefs, such as axios, where the the return type from the server can either be effectively `mixed` or `any`, both of which have cons.

I've tried doing something like parameterized types ([Flow try](https://flow.org/try/#0FAFwngDgpgBAKpKBZKAeOA+GBeewDGA9gHYDOIMA5lCAFIDKA8gHI4zoYAUAHgFwwBDYmACU-BNBQccWbsAIlyMAO6EATgGtS4xFIDeg-uTUBLYpRgBfLLmp0mzTgHI9AIgGvergBZQANn6ErpZOIgpkhH5QAHSBlJyqmqTRAmHhSqTehACufgAmzIQgAOrqGmx2DCzObh5evgFBIWFEEVGxhPGZOfmFJWUpYUA)) but it didn't work the way I hoped.

**Comment by lll000111** [comment]
> to be correctly compiled by Flow

Flow does not compile anything...

**Comment by AndrewSouthpaw** [comment]
Fixed the question.

**Comment by sibelius** [comment]
can you use Phantom Types for this https://medium.com/@gcanti/phantom-types-with-flow-828aff73232b?

**Comment by sibelius** [comment]
it would be something like this https://flow.org/try/#0JYOwLgpgTgZghgYwgAgJIgCYQB5wEYA2EAPACoB8yA3gFDLIDaA1hAJ4BcyAJANJsDOZcgF1OXAGpwCAVwiCKNAL40aCAnH79kAEThg4Q5MAC2AByLGI4Leiy5CJCtTrcWHZHBCsA3C64A3KVlOTx8lFQQAexB+MGQAcwgwACkAZQB5ADlkAF5kIQAKbBCvAEpOXX1DHMpsCOjY5AB3SKgmfgq9AyoPTlioUHjkRUo8xJSMzIKAcioAIjg59jmACwgCAki5xWnSmgB6faiYyKIAOk34gpa2-jO4PeP+U4gLyKub9oZpuGnhPdUDTi-BWkWkBAwmUiYAA6q0mLkEkk0lkZvNFss1hstjtHg0Xm8riCwRCobD4fc9kA

this does not work well because this is a problem with flow https://github.com/facebook/flow/issues/1323

**Comment by sibelius** [comment]
I think you can do that on Flow 78

check this

https://flow.org/try/#0C4TwDgpgBAKgPAQQDQGoBCA+KBeKBvAQwC4pkoUAjEtAXwG4AoBgMwFcA7AY2AEsB7dlGaIkmABTFSSKFShoAlCXjJM+BlCgAnCMFabBhaRRoMTDCAA8wfTcCgATCMwKsANneZiADNK-y6UAD0gVAAzgAWfG72UABWrKF2FNAAtjyhoTzsAOZCNlJQ7Hx2aEA

![image](https://user-images.githubusercontent.com/2005841/43645722-22a11d80-9709-11e8-8771-1e3500f832a0.png)

**Comment by AndrewSouthpaw** [comment]
I'm not quite following what this is doing... also I'm noticing that the error only occurs when it's exported?

**Comment by AndrewSouthpaw** [comment]
Wanted to ping on this again. We've been having several conversations in the flow-typed repo where libdefs could be made more powerful if there was a way to require explicit typing by the user (e.g. [flow try](https://flow.org/try/#0FAEwpgxgNghgTmABAMwK4DsIBcCWB7dRHdcADwCEBPAHgBUAaRAJQD4AKZdALkTdJ9oBKRAF4WiAM5Y4xAOaNSEngEE4cGDVotBPJsGBhSABzxwsiLJSNIAytYg5kOCLStIRiAN7BEiGDykZdHkfRAAjHnRUAFswsDh6YABfUN809IzMrOBLa2YwCVQoLABpMEoJUVCAH0QAcmQ8PDqa+rD4FqzfHLd8wuLRL0QAbSYCotLyiQBdHjtIR2dXPJTgCAIpREUVNQ1qeYcnFzdxD2HPPx4GprrGCMQARkQkxgv-No67ngAmZ+ngAD0AMQADV4DgYOhzA8uIDget0Js4LpxgMPMQyFQ+KJxKQAHQwBQSQRw0HgyHmb6woGIBFIlH9czokiGKj7eyLY7WRhjRnsUg4rYEokkmnkPBYAAWiAAbuSoZUnpCQIhfgB3UwAaz8lUM9iwYBAeNJYJkFMQAGZeFKcJUCEgQHgCoh0BLEBq4JqdKSAGKmMlmqGWxhwIi66JGSySPCISV4axoKBQSgWSW2yRxooq5AwHBQCy9dYy+IwWRICCSyCaiTGunmUPMzGUbFiIWErbE-RwPGNPB4sKIADUj2A3faY6HqtH-ZgAC9+5OrTTaGnKhJM1AVWEEDBNcAgA) and [issue](https://github.com/flow-typed/flow-typed/issues/2846)).

**Comment by SamChou19815** [comment]
Closing this since Flow now will complain under `inference_mode=lti` when some type arguments are underconstrained.
