### ISSUE TITLE
Allow defaulting to Exact types and create $Inexact

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#6598]
This comes up quite a bit with our react components whenever we do a refactor. Many of our components take optional types but when we rename those optional types we do not get breaking changes upstream to notify us all the places we need to rename the variable.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDgM5gC8YA3qmGMXgI4CuAlswCYBcY5DMQ4A7AOYAaBmDIYOcEQEMYAfn6Dh4qQF90UNiIDGchWBykcAYWUw8xABTmy5fiWcBKOtODAwAETgBDDYoKFRdVCcrGzt7ekZmdi48PjAAIkTOHjSpRll5JRgAfWYlAFsU-jT8hWU08PcAbiA

If instead there was an option in the .flowconfig to default to $Exact type and create a new utility type $Inexact the reverse of the current scenario would be possible

**Comment by lll000111** [comment]
You can do that yourself?

Just write your types as exact types (with the bars):

```
type Props = {|
  required: string,
  optional?: string,
|}
```

**Comment by rickyp-uber** [comment]
Yea but doing this for every type defined everywhere is a serious pain. Also there is no way to enforce that new developers writing new code align with this standard other than code reviews and pipes are easy to miss.

**Comment by sibelius** [comment]
this could solve Object.values problem

**Comment by lll000111** [comment]
@rickyp-uber https://github.com/gajus/eslint-plugin-flowtype#eslint-plugin-flowtype-rules-require-exact-type

**Comment by jcready** [comment]
@sibelius that issue still wouldn't be resolved because inexact object would still exist, it just wouldn't be the default.

@lll000111 I have a hard time believing that said eslint plugin covers things like object type spread or any of the utility types that output inexact object types.

**Comment by rickyp-uber** [comment]
@sibelius Exact types definitely help with the Object.values issue. It's one of the main reasons we went that direction

@lll000111 Ooooooh good find! Though not as nice as having it as a single setting somewhere (which i'm leaving this open for) this does seem like a valid alternative. I'll try it next week (earliest in my current schedule) and let you know how it goes.

**Comment by mgtitimoli** [comment]
I can't remember where I have seen this, but the code you are looking is:

```
type Inexact<T> = {...T};
```

**Comment by rickyp-uber** [comment]
Still not the same but interesting to know

**Comment by wchargin** [comment]
This is in progress. See 1ac913040f38309480934ccb6717a3ffc65094a8. It looks like the eventual syntax will be `{foo: number}` for an exact type and `{foo: number, ...}` for an inexact type (literal ellipses).

**Comment by mike-marcacci** [comment]
It looks like exact is going to become the default behavior eventually. Flow published [a blog article](https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf) about this recently.

**Comment by kevinSuttle** [comment]
It is enabled as default as of [v0.84](https://github.com/facebook/flow/releases/tag/v0.84.0) but I think if you're not using Babel 7 yet, you have to upgrade to support the `...` syntax. The codemods/linters have not been released for upgrading either. So, I too, would like to see the `$Inexact<>` utility type.

**Comment by jncornett** [comment]
Is there not a better solution that is more scoped to the particular problem? This solves the specific problem of optional prop renaming but also makes code more brittle and difficult to change overall. It's like using a sledgehammer to mount a painting. In particular, it makes programming to interfaces (i.e. duck-typing) *harder*.

**Comment by wchargin** [comment]
@jncornett: Flow supports interfaces. Using them solves the problem in
your example ([Flow Try link][try-1]):

```js
// @flow
type Item = any;

interface Fetcher {
  fetch(key: string): Promise<Item>;
}

function fetchItems(fetcher: Fetcher, ...keys: string[]): Promise<Item[]> {
  return Promise.all(keys.map(k => fetcher.fetch(k)));
}

const myApi = {
  fetch(key: string): Promise<Item> {
    throw new Error("Not yet implemented");
  },
  somethingElse(...args) {
    // ...
  }
};

// No error (good)
fetchItems(myApi);
```

[try-1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagJLMwLagC8oAhgHaoDciiAlhfgE6RkDG2AYpsuwBaZmoAN6JQoSLwEAKANaZUALlABnZM0YBzAJQqACs1gF6qzAB48hAHy0AvnUgBXCu2T1YFSdP5WCqmSk+QWYVHmChABpQADo4hVRVFXVNCi0AbQBdPVBDY1MLPyzrUXFQZl4nZi88kzMYsmhoeUVVGIIydHkSEqCBIRi+-nkdUfs6dk91UAJUAEF0ehJSiSGW5TUNbRzagst8AhKxCQlkfiN4UApMS4BRZiNmGQAiADlYZFBUXlB6AnRoIRMExMAATZ46WgSOyRMqqYy8fjaW7QMwyOINZhaVQ6FYnECxOJlBx2WiIAnvUBCR6gGRaWCwUE6RBDPwBWYLeiQxBAA

**Comment by wchargin** [comment]
@goodmind: Inline interface types were indeed added in Flow v0.73.0, but
there’s certainly nothing wrong with the “old” syntax, and I don’t see
any reason to prefer the “new” one.

**Comment by goodmind** [comment]
I think this is resolved?
