### ISSUE TITLE
Fill out Node APIs

### ISSUE THREAD

**Issue by isiahmeadows** [facebook/flow#660]
Here's the remaining Node APIs that are currently empty:
- [console](https://nodejs.org/api/console.html) - Imported by default.
- [https](https://nodejs.org/api/https.html) (nearly a clone of http)
- [punycode](https://nodejs.org/api/punycode.html)
- [readline](https://nodejs.org/api/readline.html)
- [repl](https://nodejs.org/api/repl.html)
- [smalloc](https://nodejs.org/api/smalloc.html) - Introduced in 0.12
- [string_decoder](https://nodejs.org/api/string_decoder.html)
- [timers](https://nodejs.org/api/timers.html) - Imported by default.
- [tls](https://nodejs.org/api/tls.html)
- [tty](https://nodejs.org/api/tty.html) - Not frequently used
- [vm](https://nodejs.org/api/vm.html)

**Comment by mroch** [comment]
filed #1137 for `https` specifically

**Comment by kittens** [comment]
Once #1312, #1313, #1314 and #1315 are merged we'll have the complete Node stlib.

**Comment by rgbkrk** [comment]
Those PRs look closed up, is this closed too?
