### ISSUE TITLE
Flow server needs restart on change to a file in libs

### ISSUE THREAD

**Issue by vjpr** [facebook/flow#6600]
Is this expected behavior? This makes development very slow on large projects. Every time I add a dependency, I run `flow-typed` to generate the defs for it, the server restarts. This takes about 2 mins.

Surely the server can update things without having to re-parse all files?

**Comment by Bannerets** [comment]
> Surely the server can update things without having to re-parse all files?

You can use something like https://gist.github.com/zerobias/e386e0ea5d0773f589d3d6c6fe8c7426

**Comment by SamChou19815** [comment]
This is expected, since libdef files can affect everything.
