### ISSUE TITLE
$NonMaybeType<mixed> still takes `null` and `undefined`

### ISSUE THREAD

**Issue by mrkev** [facebook/flow#6606]
[try flow](https://flow.org/try/#0C4TwDgpgBAKlC8UAkA5A9gOwLIEMQCMIZwIAeAfgFsBLADwgBMA+AKAYgGMAbHAJ2gBmAVwwdg1TFAEAKWgC5YASgUA3NNQYBuFjJHsB1DI0U7pGIVy6KgA)

This is probably a bug. ~It would make a good first task.~ _Edit: [maybe not](https://github.com/facebook/flow/issues/6606#issuecomment-521723858)._

**Comment by motiz88** [comment]
Could be related: `$NonMaybeType<$Shape<T>>` likewise still takes `null` and `undefined`. [Example case](https://flow.org/try/#0C4TwDgpgBAKlC8UDeUBmB7dAuKBnYATgJYB2A5lAL4DcAUAMbon5QCGOAJAMoAWrkAHhgA+KAB8oJAK4AbGQihSSAEwipSEZXUbNgUAEacAckwCyrEPogxwEAdz6CRoidLkKlq9SU10gA)

**Comment by lucianomlima** [comment]
Still doesn't work with version 105.2. 
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhgQLxgDeqYYAJmXgFxgD8AdgK4C2ARngBOAGjpgMAS16sOAZwxDJnAOZiAvgG50UbpwDGUuJzD7j+sgBFmAQU4MAKtLwAKao2YiJzsOrYASADljAFkSLEEHXDwAHmJmAD4ASjYeAWEacTNOBTAAbQALOG5RMF5lbnIAXTAqKRkAOjkcGEkMFwByFg6k7XohPAwSk048JGtyFyZyJKbBgAlioTkXAGoikq9V8p4Z7XVUIA)

**Comment by goodmind** [comment]
@lucianomlima your example is wrong, $NonMaybeType isn't used for objects

**Comment by lucianomlima** [comment]
@goodmind what I can do or use with Objects?

**Comment by goodmind** [comment]
@lucianomlima for your case [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGAhhgQLxgDeqYYAJmXgFxgD8AdgK4C2ARngBOAGjpgMAS16sOAZwxDJnAOZiAvgG50UbpwDGUuJzD7j+sgBFmAQU4MAKtLwAKao2YiJzsOrYASAHl+ACsAWRIcAB5iTzAohwA+FwcASjAKRLB-ADljCKxBB1w8BMTE1LYeAWEacTNOBTAAbQALOG5RMF5lbnIAXQzvGQA6ORwYSQwXAHIWGdTteiE8DE6TTjwka3IXJnJUsdWACQ6hORcAanbOr0uengPtdVQgA)

**Comment by lucianomlima** [comment]
@goodmind Thanks a lot!

**Comment by goodmind** [comment]
@mrkev it's actually pretty hard to fix... I didn't knew about `ground_subtype` function and `$NonMaybeType<string>` is reverse of `?string` type and uses bunch of new `use_t`s for me `ReposUseT` and stuff
