### ISSUE TITLE
0.75: property is missing in object type

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#6609]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjgC4wByYuCsAXkuosxwLACMBDAJ3Iq+60G-Hs1T4AngAcApmABiJAEI96YSbLhQiJMAB910mVo490wYGAAqACwCWuMAjjcA1rlQXDshctXCmfUoBMQ05AEEMfDscelQwIIBvMPJFOBVuABodMjACbjtsAHMAX3iklODOAC8KMtQoAFdsKJjsImwACk5WnHJI6JxsyrSMgEpyAH58wqKwRPK7bW7e7AA6MPo6BjCx+fKE7hl8Ru52nsH16gBucrLD49P27EaYGFuyoA

Works in 0.74 but not in 0.75. Also works if you use literals in `FooBar` type

**Comment by SamChou19815** [comment]
This works now.
