### ISSUE TITLE
`Unexpected token }` on files with `get` in ES6 object literal

### ISSUE THREAD

**Issue by roblg** [facebook/flow#661]
I'm attempting to use flow on a project, and ran across a really confusing error message. The simplified test case is:

```
/* @flow */
function get () {
}
module.exports = { get };
```

The error is `Unexpected token }`, on the `module.exports` line. 

I also get a similar error if `get` isn't the only thing in the object, e.g.:

```
/* @flow */
function get() {}
function add() {}
module.exports = { get, add };
```

In this case, the error is:

`Unexpected token ,`

The workaround is pretty straightforward (rename the 'get' function and use `get: _get`, or similar), but seemed worth reporting.

**Comment by mroch** [comment]
Thanks for the report and the simpler repro than we had before! We're tracking this in #528 (gonna change that issue's name...)
