### ISSUE TITLE
Supporting wrapped react components when explicitly typing children

### ISSUE THREAD

**Issue by alex-e-leon** [facebook/flow#6611]
I'd like to explicitly type the kinds of components a react component takes as children - but also support wrapped components that return those kinds of components.

For example:
```js
// @flow
import * as React from 'react';

type children = React.ChildrenArray<React.Element<'div'>>

const ComponentA = (props: { children: children }) => (
  <div>{props.children}</div>
);

const ComponentB = () => (<div/>);

const works = <ComponentA><div /></ComponentA>;
const doesntWork = <ComponentA><ComponentB /></ComponentA>;
```

Is there any way to define a type that allows either a specific react component or any component that returns that react component?

Note that in my example, since componentB is a functional component, we could make it work by calling it as a function `<ComponentA>{ComponentB()}</ComponentA>;` which makes me think that there should be a nice way to type this but for class based components this doesn't work anymore.

**Comment by goodmind** [comment]
This should work
```js
type children = React.ChildrenArray<
  React.Element<(props: any) => React.Element<"div">> | React.Element<"div">
>;
```

**Comment by goodmind** [comment]
Unfortunately, doesn't support class components :\

**Comment by rtsao** [comment]
Ideally, this should work recursively and with fragments as well.

**Comment by danielo515** [comment]
I just want to link my stack-overflow question specifically related to this:
https://stackoverflow.com/questions/67707502/how-to-restrict-to-react-fragment-of-certain-children-types

In my case, I was asking about just Fragments, because I don't want to have to create a new functional component just to be able to wrap the inner components into a Fragment. Should I add a different issue for that?

**Comment by SamChou19815** [comment]
We do not plan to have good support for this, since it tends to lead to inspecting jsx internals
