### ISSUE TITLE
Type refinement doesn't work with optional chaining

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#6613]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5RxwD8AXGAM4YBOAlgHYDmAvulAFcOAYwxs4HMFA4AKAIYMahAJQNi5VGDBsoYeTQB0VOMoqatYFngwCWkuQG5zfLVZt2KxhgHIAJnig5ARgMbx4nPiA

**Comment by TrySound** [comment]
Hi @jbrown215, is this issue in team task list or it's not relevant yet?

**Comment by jbrown215** [comment]
Not on our radar yet

**Comment by TrySound** [comment]
Okay, thanks

**Comment by lxe** [comment]
Bumping for visibility?

**Comment by tebuevd** [comment]
V8 supports it now: https://v8.dev/features/optional-chaining

**Comment by mrtnzlml** [comment]
Similar issue/inconsistency described here: https://github.com/facebook/flow/issues/8106#issue-500543967

**Comment by dannyharding10** [comment]
Here's a [simplified example](https://flow.org/try/#0C4TwDgpgBAglC8UDeUBmB7dB+AXFAzsAE4CWAdgOZQC+AULagK5kDGwJ6ZUAtiAGLMWACgCGeGAEpktKFBKooorADoM6KUhmyoLToR4gAysXIU8hUpQRQRqzFrp1t2rbNpA) (IMO). Is this something that the Flow team would like some help on? I would love for this feature to be added to flow!

**Comment by dsainati1** [comment]
@mvitousek is currently working on this

**Comment by gajus** [comment]
Was this ever implemented?

**Comment by mvitousek** [comment]
It was implemented as of v0.114! If you check out the try-flow examples in this issue you'll see that they pass now.

**Comment by TSMMark** [comment]
Confirmed, works in 0.114.0. Big improvement, thanks so much!
