### ISSUE TITLE
Providing Flow typing for function argument when using default object values

### ISSUE THREAD

**Issue by jmarceli** [facebook/flow#6616]
I'm not sure but I think that this might be a Flow bug. I'm unable to add Flow typing when using `Object.assign` to provide default values for function arguments. Here is a SO question: https://stackoverflow.com/questions/51422411/flow-default-values-type-checking/51431098

And here is a direct link to reproduce this problem on flow.org/try: [https://flow.org/try...](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AYVgHaQCWA5gJIGgC8oA3oqKAM6wC2WAagIbQCuWAPwAuUAT5sARlgBOAGkQBfANzJ02PIRKkamomUqgAZPUYt2XXgNHipshSuSQ+BAMYpihUCizMUAClctMlF8fQoCAEobCWkZUyYQUAALWRwAMTh4UHhiaGhQGSwMWBkUUG4qWRlS4TMk3EqCWHLuZmYyKgADAHlJACssdwA6No7SAn9h6ciu71hQLrY0MO056VduPmYcFwATLBICLD3QAG0ARgBdUGJmW7d2DG4PSWgcXJRksVjZc4AmG7EKgYGrYMpoRasDg8fhYLrDOpMIIEPygZarEJ6bS6PqDEZjTr+OiKOQJJjmGFWLCiC4ABgZCiYpNAKO0kVUZiKKD4Mio0KwPS+snSLncnkmGOCpGGAthAg5SicYo8XhaqRkorcqsmwIwfBQMTsMmiP2N5O5vKoF3+AGZVIogA)

Any help will be appreciated.

**Comment by wchargin** [comment]
Your problem can be reduced to a simpler example—with intersection
types, optional and non-optional properties [don’t mix well][1]:

```js
// @flow
type ConfigIn = {someValue?: number};
type Config = ConfigIn & {someValue: number};
const c: Config = {someValue: 1000};  // error!
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMKwHaQCWA5gJL6gC8oA3gM6wC2mAagIbQCumA-AFyh8XJgCNMAJwC+AbhQZseQqWq4CxcpQBkdRiw7dMg4WMmzEAYwL1koC4KUbVDZm049BARgAMv2aFAQUEkJWAkAQkQgA

(Potentially related: #5929.)

Using the type-spread operator (`...`) instead fixes this, and [fixes
the downstream problem in your example][2]:

```js
// @flow
type ConfigIn = {someValue?: number};
type Config = {...ConfigIn, someValue: number};

function test(config: ConfigIn): number {
  const myConfig: Config = Object.assign(
    {},
    {someValue: 1000},
    config
  );
  return otherFunction(myConfig.someValue);
}

function otherFunction(input: number): number {
  return 123;
}
```

[2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMKwHaQCWA5gJL6gC8oA3gM6wC2mAagIbQCumA-AFyh8XJgCNMAJwC+AbhQZseQqWp0AdBqXFy+ADShGLDt0yDhYybMSJIXfAGNkRAqGSZ6yABT2C2wVtIKAEozEXEJOkRQUB98D1AmVACSf18VGgB5UQArTEc1dnp6UnxPKOi6KV1y6IZmNk4eQQBGAAZ2qpqYtJJyoLloiUxkLglKWGQAC0kAMTtHZ1LE5LVDBpN+xClrWwcnFwnpiTm9xc8ifHQuZFCLCRChMMlIweHRymaAJgBmOW2gA

Frankly, intersection types seem to break more often than they work.
I avoid them altogether.

**Comment by jmarceli** [comment]
Thanks, this is it.

What is more, for anyone interested. It is sometimes good to use [Exact object types](https://flow.org/en/docs/types/objects/#toc-exact-object-types) to avoid nested properties problem [example](https://flow.org/try/#0C4TwDgpgBAwg9gOwGYEsDmBJBUC8UDeAUFFAM5wC2EAagIYA2ArhAPwBcUCjFARhAE4AaYlDjAAFgLpMIHIiRLAIpYBy68BwkgF9C2gNyFCoSLESo0uAiIB0d+MnRYtZSjQbM13PkL2HCSIwIAMbAKIhQSioAFMHm6BwOFlgAlF4a-NYkcQgqUBQgSQlmjpZ4API8AFYQoTa0pKToCNH42oJZCuRU0p5QAIwADMMu7VA5Fin+JPwQwIz82GKS-ABiQaHhLQVFaDbLUh4QNlHAU3pGgSFhEQdrGzctKAhgjKqc3gJpHxmds-OLAYAJgAzIZdEA) and [solution](https://flow.org/try/#0C4TwDgpgBAwg9gOwGYEsDmBJBUC8UDeAPgFBRQDOcAthAGoCGANgK4QD8AXFAs1QEYQATgBpSUOMAAWQhiwhd8YssAjlgXHvyGiyAX2KFdAbmLFQkWIlRpcBMQDpH8ZOiw6K1Ok1YbeAkcTGpkjMCADGwCiIUCpqABRhVuhcztZYAJS+WoJ2ZIkIalBUIKnJli42eADyfABWEBH29OTk6Ahx+LrCuWQeNLI+UACMAAxj7l1Q+dbpJmKCEMDMgtgS0oIAYqERUe3FpWj2azLeEPaxwLOBwduR0cebt7txKAhgzOrcfkKZX9k9CyWK2GACYAMwmXRAA)
