### ISSUE TITLE
missing type-error with enums returned from functions

### ISSUE THREAD

**Issue by gabor** [facebook/flow#6617]
this does not produce an error-message:
```
type Bit = 'zero' | 'one';

function getOne():Bit {
  return 'one';
}

const b1 = getOne();

if (b1 === 'wrong') {
  console.log('.');
}
```

this does produce an error-message:
```
type Bit = 'zero' | 'one';

function getOne():Bit {
  return 'one';
}

const b1:Bit = getOne();

if (b1 === 'wrong') {
  console.log('.');
}
```

why is there no error-message in the first case? the only difference is that in the second case i explicitly annotate `b1` to be of type `Bit`. but it is of type `Bit` in the first case too, because the function `getOne` returns a value of type `Bit`. so why no error-message?

(to be clear: i think we should get an error-message in both cases)

**Comment by wchargin** [comment]
In the first example, the type of `b1` is inferred to be `string`,
simply because this is required to make the following code type-check.
That’s just a consequence of how inference works.

The implicit upcast in the initialization of `b1` is valid because `Bit`
is a subtype of `string`.

**Comment by gabor** [comment]
thanks for the explanation, but is there anything that can be done to improve the situation?


in my case i had a typo in the string, so i had something like

```
const b1 = getOne();

if (b1 === 'zero') {
    // do something
    return;
}

if (b1 === 'oneeee') {
   // do something else
   return;
}

throw new Error('unreachable');
```

as you see, i had a typo in the "one" case. and when i found the bug i was wondering why flow did not catch the problem. is there perhaps some different pattern i should use?

**Comment by wchargin** [comment]
Yes. You should [ask Flow to verify that you have handled all cases by
using an empty-type assertion:][1]

```js
// @flow
type Bit = "zero" | "one";
declare function getOne(): Bit;

function f() {
  const b1 = getOne();
  if (b1 === "zero") {
    // do something
    return;
  }
  if (b1 === "oneee") {  // whoops!
    // do something else
    return;
  }
  (b1: empty);  // error! (good!)
  throw new Error("unreachable");
}
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagEIEtlQBeUAIgC9MAnWU0AHzNgDtNSBuRAE0wGNoAhlWyQArs17I8LUAHNMyAPKsAFAEoAXLgKdEYiVJmR1oAN6JQoXiwDOhAEYBGYnIXLM6zpbyRQKp8REJBTUtGpmFpagIKBcsKA2sAC2CgAWeMyykZbCyKJUzF6gAL6RPn4BQcEsmLWk4aaWMfCpsLDoNgCE2dFgcQnJaRmyoJjQNpg9ufmFkaWW-o5amEnoaGrsTWDUNFSdfrJtXJ1qkcipNPCgrFcAolS7KqTiwgK8qQL20GwbiKVAA

In the above code, Flow raises the helpful error,

> Cannot cast `b1` to empty because string literal `one` is incompatible
> with empty.

indicating that we have forgotten the case `one`. Replacing `oneee` with
`one` in the guard properly fixes the error.

This protects you both now and in the future. If you add another case to
the type `Bit`, then Flow will raise an error here to indicate that you
need to handle the new case.

Personally, I usually write `throw new Error((b1: empty));`, which
includes both the static check and the dynamic check, and encodes the
problematic case into the error message.

**Comment by SamChou19815** [comment]
The issue was fixed a while ago.
