### ISSUE TITLE
Unable to extract function type into type variable. Generic incompatible with itself?

### ISSUE THREAD

**Issue by spudly** [facebook/flow#6619]
I prefer to extract the type annotations for a function into a separate variable to make the functions easier to read, but in this case, I can't do so. Can anybody explain what I'm doing wrong?

```javascript
// @flow

// this works:
const myFunc2 = <T>(value: T): T => value;
        
// this reports an error. how could T be incompatible with T?
type MyFunc = <T>(value: T) => T;
const myFunc: MyFunc = (value) => value;
```

Error:
```
8: const myFunc: MyFunc = (value) => value;
                                     ^ Cannot assign function to `myFunc` because `T` [1] is incompatible with `T` [2] in the return value.
References:
7: type MyFunc = <T>(value: T) => T;
                            ^ [1]
7: type MyFunc = <T>(value: T) => T;
                                  ^ [2]
```

[Try It](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgC4AsCWBnU9YAnAaxwC5EBjWAOxzVAFsBPAMQFcbKAmUAXlAAeACoA+ABQA3AIbR2AUzKhhASiXD+o0DLnyA3IlBHjRlGEy5QheQAciaPNJqh5hQkQB0oDAlDV20AAmyqAARvKgWFywjDbSaFih0BHwWJjKAPyIaMw2EQCybJyU-EJiUrIK6iqaygbUdAwsHFxKhS0lAhW6NXxaOgoGiJDFCbSgQA)

**Comment by wchargin** [comment]
This is ridiculous, but [annotating the lambda “fixes” it][1]:

```js
// @flow
type Id = <T>(value: T) => T;
const id: Id = <T>(value: T): T => value;  // works
```

As of Flow v0.71.0, you “only” need to annotate the parameter. In
earlier versions of Flow, you additionally needed to annotate the return
type. Annotating _only_ the return type is not sufficient in any version
of Flow.

If you ask me, this is _clearly_ a bug.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagJIBNQBeUAHgBUA+ACgDcBDaAV0wC5QyBKIi9gbkQDGsAHYBnZKACWeNviKlKtBszadV3UPSaZeoUCFDxYAJwDWoxEA

**Comment by stereobooster** [comment]
Same as https://github.com/facebook/flow/issues/5903 ?

**Comment by spudly** [comment]
Looks like it, although it looks like that issue needs to have its title updated

**Comment by SamChou19815** [comment]
This now works
