### ISSUE TITLE
get-def doesn't resolve QualifiedTypeIdentifier

### ISSUE THREAD

**Issue by minedeljkovic** [facebook/flow#6620]
`foo.js`
```js
// @flow

export type TFoo = number;
export const vFoo = 2;
```
`bar.js`
```js
// @flow

import * as Foo from './foo';

const x: Foo.TFoo = '';
const y = Foo.vFoo + 1;
```

Type TFoo is not resolved in `bar.js` (line 5 col 14):
`{"path":"","line":0,"endline":0,"start":1,"end":0}`
but type inference works, so this line errors:
`const x: Foo.TFoo = ''; // flow error: string is not compatible with number...`

Value vFoo is resolved sucessfully in `bar.js` (line 6 col 15):
`{"path":"/foo.js","line":4,"endline":4,"start":14,"end":17}`

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
