### ISSUE TITLE
Type inference based on return value seems to be broken.

### ISSUE THREAD

**Issue by mirek** [facebook/flow#6621]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAieAxnACZ4A8AKgHxgC8YAFAG4CGMArngFxgAzhgBOASwB2AcwCUTBjXRRuEkhjFwJYALYcA1tXotKZSgOKnDdOQG9UYMCLwZuIrSYp4WAcgAsAJm8ZVABfdDIJYTAADyYdfWoJbm0AIzwROhZ2Ll4BYXFpOUYGHA4RQTwAMXgODGyePBlgoA
```js
/* @flow */

type Decode<T> = (value: string) => T

function make<T>(decode: Decode<T>) {
  return decode('42')
}

const x = make<number>((value: string) => parseFloat(value))
```

Type of `x` is not correct - `mixed`. Expected type should be `number`.

**Comment by mirek** [comment]
Yes, I know, it's relatively simple inference.

**Comment by mrkev** [comment]
Yeah, it's interesting that it's not :/

**Comment by mirek** [comment]
Just for the record, explicitly specifying return type for `make` function fixes the problem https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAieAxnACZ4A8AKgHxgC8YAzhgE4CWAdgOZMMa6KAFduJDJzjcwAWwCGAa2r0AFJTKUAXEVIUVdAJQ6aYAN6owYdngwj2MjftUByACwAmF4dQBfdGTcbGAAHkxyStTcIrIARnjsdKo48uwseABi8PIYPqgA3KohOtFxCYZAA

**Comment by SamChou19815** [comment]
This should be fixed with escaped generics detection. Now return annotation is required.
