### ISSUE TITLE
Custom `@jsx` non-react components do not work since 0.75.0

### ISSUE THREAD

**Issue by sobolevn** [facebook/flow#6626]
I am using `vue` + `flow`.

I had a component like this:

```vue
<script>
// @flow
// @jsx ActionBar

import Vue from 'vue'
import Component from 'nuxt-class-component'
import { Action } from 'vuex-class'
import type { CommentType } from '~/types'

@Component()
export default class ActionBar extends Vue {
  @Action('fetchComments')
  fetchComments: () => Promise<Array<CommentType>>

  render () {
    return (
      <div class={this.$style.actions}>
        <button
          class={this.$style.reload}
          // Try to use `this.fetchComments(12)` instead to raise type errors
          onClick={this.fetchComments}
        >
          reload comments
        </button>
      </div>
    )
  }
}
</script>
```

And it was working perfectly after I have discovered this undocumented `@jsx ActionBar` feature.
But after `0.75.0` was realesed, it no longer works.

Error messages:

```
/code/client/components/ActionBar.vue
  34:8   error  Cannot create `div` element because a callable signature is missing in statics of `ActionBar` (see line 19)     flowtype-errors/show-errors
  35:10  error  Cannot create `button` element because a callable signature is missing in statics of `ActionBar` (see line 19)  flowtype-errors/show-errors
```

Original issue: https://github.com/wemake-services/wemake-vue-template/issues/683
Related PR: https://github.com/wemake-services/wemake-vue-template/pull/679
Travis build: https://travis-ci.org/wemake-services/wemake-vue-template/builds/406968425?utm_source=github_status&utm_medium=notification

**Comment by ArmorDarks** [comment]
Well, glad to know that Flow still, for now, reason assumes that all JSX compiles to React code. Like, there is no babel and it actually does not compile Vue JSX tags into something else...

**Comment by ArmorDarks** [comment]
Thanks for the hint, though it still sounds like a hack...

Note that your `jsx` function probably should be at least something like this, otherwise Flow will throw:

```js
function jsx (element: string, props: ?Object, children: (string | Object)): Object { return {} }
```

Also, despite all my attempts,` jsx` always returns `any` which isn't exactly what we need here.

![image](https://user-images.githubusercontent.com/4460311/45575081-edcdab80-b87a-11e8-911c-fbbb05c7dff1.png)

Did you figure out why?

**Comment by sobolevn** [comment]
No, sorry. I am not using `jsx` in real projects, so it is just a demo.

**Comment by ArmorDarks** [comment]
Btw, this doing same thing, but slightly cleaner:

```js
// @flow
// @jsx jsx

declare function jsx (element: string, props: ?Object, children: (string | Object)): Object
```

However, it still results with `any` on jsx tags output.

**Comment by sobolevn** [comment]
@ArmorDarks thanks! Can you please send me a PR with this code?

**Comment by SamChou19815** [comment]
The pragma should work now
