### ISSUE TITLE
Union of Array: "property A/B is missing" when accessing the property C, that is common to every branch

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#6629]
```javascript
type X = { a: number, c: number }
type Y = { b: number, c: number }

const x: Array<X> = [{ a: 1, c: 1 }]
const y: Array<Y> = [{ b: 1, c: 1 }]

const test = items => items.map(i => i.c) // access the common property

test(x)
test(y)
```

gives me

```javascript
const x: Array<X> = [{ a: 1, c: 1 }]
                  ^ property `b` is missing in `X` [1] but exists in `Y` [2].
const y: Array<Y> = [{ b: 1, c: 1 }]
                  ^ property `a` is missing in `Y` [1] but exists in `X` [2].
```

Reproduced here:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAaYAvGAN5gCGAXGAHYCuAtgEZ4BOANGAMZ1M2nMAF9MuAgE1SFMKwEt23PgqEdR6XnHoBnDGAAedAIIcOVLAB5CAPhkBtSrTABGHv1eiAuqi279WCZmFpaSdmSOcnRuKp4iPr7aemAYeMlkAJapzDqkdll4OQB0zFQ4ABQZeWAZRbwAlOipeuUGjc0Y5Vj1QA

I don't know if it's a bug or if it's intended.

If it's intended, it seems a bit overkill since I access only the common property. Am I missing something?

**Comment by ggregoire** [comment]
Hi @wchargin, and thanks for your long answer!

I guess the `$ReadOnlyArray` workaround is OK for now.

I just hope they will eventually fix this. :)

**Comment by ggregoire** [comment]
If someone is looking for the `.find`:

```javascript
// @flow
type X = {a: number, c: number};
type Y = {b: number, c: number};

const x: Array<X> = [{a: 1, c: 1}];
const y: Array<Y> = [{b: 1, c: 1}];

const test = (items) => (items.find: ((X | Y) => boolean) => X | Y | void)(i => i.c === 1);

test(x);
test(y);
```

[Demo](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagBqgLygDeAhgFygB2ArgLYBGmATgDSgDGFNDzAvgNwoM2AJoFi9LnUasOUnkwGJE7WJQDOyUAA8KAQSZMSqADw4AfOIDapCgEY2nUHd4BdQao1bU+w8ZMiloQ2ks6O9m6CKmqaoMiYsYQAFACW8bTqAJQElqnp6gB0kCmUACYUSUl4AD6gItn4lvSwsNCYJJQNljV1oLUAbrAppZmpOaApBewE+IR2mVHxmknaCygJyEmoa0A)

**Comment by SamChou19815** [comment]
This now works with exact objects
