### ISSUE TITLE
module.name_mapper does not work AT ALL unless module.system=haste

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#6634]
The module mapper configuration option does not work at all for the default "node" module system. It only does anything at all when the React Native system "haste" is used. That is contrary to all documentation and claims in various discussions.

I don't use regular expressions, I only tested using a basic string. The mapping system was completely inactive unless I told Flow to use "haste", which according to Flow's own docs only is for React Native.

- Does the mapper indeed only work for "haste"?

- What are the consequences of setting "module.system=haste" when I don't have a React Native project?

PS: Using Flow 0.77

**Comment by lll000111** [comment]
I added

```
module.name_mapper='^my-module$' -> 'MyModule'
```

and to a new ROOT/flow-typed file

```
declare module MyModule {
    declare module.exports: {
        MyObject: Object
    };
}
```

and then I have a file somewhere in the project that does

```js
const {MyObject} = require('my-module');
```

**Comment by lll000111** [comment]
Uhm... I don't have a *physical file* for the target module, only a declaration. Is that the difference? Does the node module system require the resolved module to be a physical file, while `haste` allows it to just be a virtual declaration without a physical body?

**Comment by apsavin** [comment]
Maybe... We have physical files.

**Comment by lll000111** [comment]
I tried creating a physical file following instructions in https://stackoverflow.com/a/37272883 but keeping my much simpler example. No change.

**Comment by lll000111** [comment]
UPDATE I changed the config line to point to a file. No success yet but at least the error changed, so _something_ is happening even without `haste` config option. I'll see if I can figure this out.
