### ISSUE TITLE
typeof checking doesn't affect flow if in other const

### ISSUE THREAD

**Issue by bastoune** [facebook/flow#6637]
I exported a function isObject checking the type of a variable and flow show errors that it doesn't if I directly do the test.

Please see the two different function below :
- funcWhichShowError
- funcWhichUnderstandTypeof

[Find here the associated flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gCWOA8gEYBWApugQLxgAUclAXGAIZYCeAlO2ThwYVLmDoA+JozzcADlThQwLCuLoMA5Kpp5NvMADJDTVWACEGsFgCuMGL16oM2fCsq6AYjazpxptjByaloDSTAAbwBfF1wCODwACyoAJ29ff2ZA-BTCLABzMKlo5ygfWkJsMDLfAHVEwnREgGVExABRFJS4FMYAD3YcvPywAB8gj1DI1DAiZUZiYN1+xxnZ9xC8dPQVtaoYHCo12YTktPLdmNLyvEqsavL6xsSAVSwAE1T8LneAFXlFFB+oM8LkCmMJpsDBE1oR5jIAUowH11FodLR9EYTP0LFZbPZVusNl4Ln0nLN9odjiokqltpdUEA)
```
/* @flow */
const isObject = (obj: any): boolean => ((typeof obj === 'object') && (obj !== null))

const objectFunc = (obj: Object) => {}
const otherFunc = (obj: string) => {}

function funcWhichShowError(x: string | Object) {
  if (isObject(x))
    objectFunc(x)
  else
    otherFunc(x)
}


function funcWhichUnderstandTypeof(x: string | Object) {
  if ((typeof x === 'object') && (x !== null))
    objectFunc(x)
  else
    otherFunc(x)
}
```

**Comment by apsavin** [comment]
[Fixed](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gCWOA8gEYBWApugQLxgAUclAXGALaEAeVAJgEp2ZOHBhUAhljABSdAAsaAaxxg6APiaM8ATwAOVOFDAsKaugwDkpmnksCwAMkdNTYAIQWwWAK4wYAgKoGNj4JpS2AGI+WOhqrmxg5NS0DhpgAN4AviG4BHB4igBO0bHxzIn4RYRYAOZpmtnBUDG0hNhgLbEA6vKECgDK8ogAokVFcEWM3OxVNbVgAD5JEamZqGBExozEybbTgRub4Sl4pegHR1QwOFRHmwXF55c5za147dJd6L398gCqWD4VCK+CkfAAKvpDFBprM8NU6ksVqcHBkjoRttpoUYwNxzFYbLR7E4XNMPF5fP5DscTlFWpdNtdbvcTIUQc9uEEckA)

[docs](https://flow.org/en/docs/types/functions/#toc-predicate-functions)

**Comment by bastoune** [comment]
Sorry for that :s
