### ISSUE TITLE
improved inferred type when using $Call

### ISSUE THREAD

**Issue by sibelius** [facebook/flow#6638]
![image](https://user-images.githubusercontent.com/2005841/43217368-d5d45b04-9017-11e8-87e2-9c62eab83b30.png)

https://flow.org/try/#0C4TwDgpgBAsiDyAjAVlAvFA3gKClAhgFxQDOwATgJYB2A5gDS5SLHUCuAtohOYwL7YAxgHtqZKLQjAAguigAKYcThJkASnQA+LE3JS25alGEA6fAG5sA7BAAeYYeWBRQkKAFFbFfIOAAlfUMAHgAxam0MABIAYXwAGzigoIAVTXl5E0yASWAefEQ4iCD8ahBNDTRtZIqq+igwzUtsV2g-OU9vXwDgA2ogluEAMwkpaU0mbHkARgAGYj8NKCA

when using `$Call` `flow` won't show the inferred type

it show `type R = ExtractReturn<(o: MyObj) => string>`

instead of saying that `R` is a `string`

how can we improve this?

**Comment by SamChou19815** [comment]
This now works.
