### ISSUE TITLE
add support for new type: bigint

### ISSUE THREAD

**Issue by dnalborczyk** [facebook/flow#6639]
```javascript
(1n: bigint)
```

https://flow.org/try/#0BQRgdgXABARglgczmALgSiA

**Comment by goodmind** [comment]
Parsing side of this feature was imported in #7471

**Comment by dsainati1** [comment]
This should be resolved, so I'm going to close this.

**Comment by goodmind** [comment]
@dsainati1 there is still typechecking part

**Comment by lo-corp** [comment]
When can we expect this?

**Comment by seanlangbrown** [comment]
BigInt support would really help with a project I'm working on.
I see there are 2 PRs for BigInts that have been open for 1 year.
Are these just waiting for review or is there anything someone (like me :) ) can contribute to help resolve this issue?

**Comment by nnmrts** [comment]
Can we first have support for `Array` please?

**Comment by Brianzchen** [comment]
I'm still getting the error `BigInt bigint [1] is not yet supported. [bigint-unsupported]` in latest version.

cc @mroch any insight? 🙏

**Comment by gkz** [comment]
BigInt is now supported as of 0.194
