### ISSUE TITLE
$Exact fails with keyed maps

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#6640]
In general, the key types of the object maps are being applied directly instead of based on types. So if you have 
```
export type StoreData = {
  b: {
    notId: 'c'
  },
  [string]: {
    id: string
  },
};

let data: $Exact<StoreData> = {
  b: {
    notId: 'c'
  },
  a: {
    id: 'a'
  }
}
```

I would assume that StoreData would require b and everything inside it to be exact but because the objet is also keyed on string that any other property would have to be a string and it's value to exactly match the type defined.

https://flow.org/try/#0KYDwDg9gTgLgBDAnmYcDKNrACIEMa5wC8cA3gFBxwBGAXGZVXAHYQwCSAJvQOQDGPRgF8ANIwDaAZxhQAlswDmAXXoUmcWdzjS5i4WKEBucuQA2weJ3y56AEgCiIXHxgAeDFjwEAfMQZU6fyZWDi1+QSpRRhsgqk1eXAi4IXIhIA

**Comment by vicapow** [comment]
I'm not entirely sure this is a bug. I think this fails for the same reason as

````js
type ExactProps = $Exact<{ [string]: { id: string } }>;
const t: ExactProps = {a: 'a'};
````
which is an exact of an object as a map doesn't make sense

**Comment by rickyp-uber** [comment]
An exact object map would equate to that object map. Though a no-op, I think it still makes perfect sense. This no-op function is useful for when attempting to implement recursive functions such as a DeepReadOnly or a DeepExact.

**Comment by vicapow** [comment]
Would someone from the FB team would be able to verify if this is a bug or flow working as expected?

**Comment by SamChou19815** [comment]
This is working as intended
