### ISSUE TITLE
[flow] statics of `React.Component` [1] is incompatible with `React.StatelessFunctionalComponent` [1]

### ISSUE THREAD

**Issue by dquang-tran** [facebook/flow#6642]
[Flow Try Link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqtQAeuQmDoxyFACLUoJAK4wCAYRa4AdtXVEhBLQBMKNegQB0ABXmdVOOJu0AeAN4BfAHxgnqMGE7r91HgAFACUnt4+vtQEVupgQagAkIkO+ugAbh4AEtQw8GAOwGmZET4hfD4uqFX8UPLqDOh2YAjoBAAWAMos1ADyHYE2GloEQV4+gcx4Q3YjAFxgAKJ4UzP2RAC8YDJyiipqs9oANBF6ZAQnLgvjYJP4a-NUXGYP2gAqAJ7Y1A4k6h9uE4+M4EBZ-D5gDYeABGcDgMFo6kuIQWQWMDFMrwIn2+v3+bjCUKeJkxB3WOJ+4I8N04MTwcSCWMJ1NKYjs5zAcAG0zJI0h8WZ4UikVpsQKxTAwDcFUiLhlPlF9M53KxMrl1X4QhERACuyULTaXR6-Xag152j4QA)
Can someone explain to me why this throws an error on line 14?

If I replace React.ComponentType<any> on line 17 with Class<React.Component<{}>>
[Link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqtQAeuQmDoxyFACLUoJAK4wCAYRa4AdtXVEhBLQBMKNegQB0ABXmdVOOJu0AeAN4BfAHxgnqMGE7r91HgAFACUnt4+vtQEVupgQagAkIkO+ugAbh4AEtQw8GAOwGmZET4hfD4uqFX8UPLqDOh2YAjoBAAWAMos1ADyHYE2GloEQV4+gcx4Q3YjAFxgAKJ4UzP2RAC8YDJyiipqs9oANBF6ZAQnLgvjYJP4a-NgyhJkZA7GDKYPjq5ubic+M4EBYkdQATzAGw8ACM4HAYLR1JcQgsgh8zN8CAAVMHYagOUFgtxhKFULgYg7rHF4gngjw3TgxPBxIKYkn00piOznMBwAbTSkjSHxdnhSKRRmxArFMDANwVSIuBU+SXM3n8zEKpXVfhCEREAK7JQtNpdHr9dqDQXaPhAA)

Then, there is no error. The error message is cryptic and I am not sure how to resolve this

**Comment by schnerd** [comment]
I reported similar behavior in #6666, maybe the same underlying issue?

**Comment by browne0** [comment]
They're not compatible, if you want to a component that uses either, use `React.ComponentType`

https://flow.org/en/docs/react/types/#toc-react-componenttype

**Comment by dquang-tran** [comment]
@browne0 What do you mean? I did use `React.ComponentType<any>`. Check the first link in my post. Flow complains at React.ComponentType but not at Class<React.Component<{}>>

**Comment by tcoughlin3** [comment]
@dquang-tran I happened to notice your Flow Try link has no errors in the new release 0.89 of Flow.

**Comment by dquang-tran** [comment]
@tcoughlin3 It seems to be fixed in newer versions.

Closing the issue

**Comment by diljeetk** [comment]
such a=errors are comming inside the node_modules react-native library 

Cannot cast Image to statics of ImageComponentType because AbstractComponent [1] is incompatible with statics of
ImageComponentType [2].

     node_modules/react-native/Libraries/Image/Image.ios.js
     162│   },
     163│ });
     164│
 [2] 165│ module.exports = (Image: Class<ImageComponentType>);


How to handle those?
