### ISSUE TITLE
Flow throws error; module not found but module exists

### ISSUE THREAD

**Issue by kunokdev** [facebook/flow#6646]
Even tho module is installed and it exists, Flow cannot resolve it and throws error.
See below:
1) Inside bash I ran `flow` and it throws error that module is not found
```
    user@pc:~/code/project$ flow
    Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/functionalities/Growth/index.js:3:25
    
    Cannot resolve module react-redux.
    
         1│ // @flow
         2│ import React from "react"
         3│ import { connect } from "react-redux"
         4│
         5│ type Props = {
         6│   children: Function
    
    
    
    Found 1 error
```
2) Below command checks whether directory exists and it does
```
    user@pc:~/code/project$ ls node_modules | grep react-redux
    react-redux
```
I tried to remove and reinstall both `node_modules` directory and `yarn.lock` file. 

Versions should be matching: 
```
    flow version
    Flow, a static type checker for JavaScript, version 0.77.0
```
.flowconfig:
```
    [version]
    0.77.0
```
[![enter image description here][1]][1]

  [1]: https://i.stack.imgur.com/wP0Cn.png

**Comment by cogell** [comment]
solved here: https://stackoverflow.com/questions/51563112/flow-throws-error-cannot-resolve-module-react-redux-even-tho-its-installed

**Comment by kunokdev** [comment]
Thanks, I am actually author of that question as well. I think its enough good to have reference to the given answer, let's close this issue in the meanwhile.

**Comment by meloseven** [comment]
check your `.flowconfig` in root path, try to remove `<PROJECT_ROOT>/node_modules/.*` under the field of  `[ignore]`

**Comment by gajus** [comment]
> check your .flowconfig in root path, try to remove <PROJECT_ROOT>/node_modules/.* under the field of [ignore]

How to ignore errors in dependencies without getting "module not found" error?

**Comment by albertbuchard** [comment]
This worked for me: https://peterelbaum.com/flow-js-node-modules/
