### ISSUE TITLE
$Call is not able to retrieve the parameter type of a function

### ISSUE THREAD

**Issue by maxaggedon** [facebook/flow#6647]
Following the docs I tried to retrieve the parameter type of a function in the same way we can retrieve its return type. But had no success, no errors are raised...

[Here is a small repro in the playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyeGAFnACZgC8YAzhgE4CWAdgOY0B8YARnHBh4AhqwDc6bPjABRAB5NhAYwwAlEgFdGrACq4CtADw6uAClFZuYHQEorOiWCdhM+sOoxbdb2gBIAwsIwMIbyiioeXnr4ADREJOQUXBKopkwaeABc7pra0Xg2YmDAwGAA6nCMANZ0qQBEpHjBcHXZkXn6hcWl8vgqeBQyjIyVkm5hjMoYAArCkwC2+TRgxmY6VhZ21DwOqM4uUgSzC0t+gcGhCpMqx8KL+nHEZJTJe86p6Vlgt-f4XSVgADK5A0MAoADFhMwYPVGs1Wt85nd8v9ShVqrVnEA)!

**Comment by langri-sha** [comment]
Stumbled on this recently. I am not sure why this works suddenly, but it seems to work on Try Flow, at least.

```
type ExtractParamType = <T>(T => any) => T & T // :see_no_evil:
```

**Comment by Bannerets** [comment]
I guess it is somewhat working as intended. You can't get arguments of a function by calling it.
You have to use something with invariant/contravariant generic to make it work.  In `ExtractParamType`, `T` shouldn't be in a positive (covariant) position.
```js
type ExtractParamType = <T>({ -v: T => any }) => T
// or: type ExtractParamType = <T>({ v: T => any }) => T
declare var foo: $Call<ExtractParamType, { -v: (a: string) => boolean }>
// or: declare var foo: $Call<ExtractParamType, { v: (a: string) => boolean }>
;(foo: string) // ok
;(foo: boolean) // error
```
[try flow](https://flow.org/try/#0FAguE8AcFMAIFEAeoBOBDAxqACm9BbAFSjgF5YAeQgPgAoBvWAWgDcAuWQ2U62NAO3CwAvgEpuvQsFgzYwACbQMAGzxwWeWADMA9jo4ASAMJplyiklSYceNERIAaWI1YdaaDgGdUAS34BzcR5YACM9ZWgBEWoQAG5aXX1YbxQ-QNgAegzYHQBrYHjEjjCdCIFxLNhoFBQdFCA)

---

The solution with `T & T` doesn't really work, see [try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyeGAFnACZgC8YAzhgE4CWAdgOY0B8YARnHBh4AhqwDc6bPjABRAB5NhAYwwAlEgFdGrACq4CtADw6uAClFZuYHQEorOiWCdhM+sOoxbdb2gBIAwsIwMIbyiioeXnr4ADREJOQUXBKopkwaeABc7pra0Xg2YmDAwGAA6nCMANZ0qQBEpHjBcHXZkXn6hcWl8vgqeBQyjIyVkm5hjMoYAArCkwC2+TRgxmY6VhZ21DzrAGTWjs6u0rMLS36BwaEKkyqnwov6ccRklMmozi5pjBnZ94-4LolMAAZXIGhgFAAYsJmDB6o1mq0wP98kDShVqrUPkccU48S5PqgKHglDA5gQAG5zMA4P5zB75VBiUx0+hMNjsGzM1nZfiCESsOzAujgyFgKCwmBAA) (24-26 lines).

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
