### ISSUE TITLE
Inlining imported types causes type error (regression in v0.76.0)

### ISSUE THREAD

**Issue by wchargin** [facebook/flow#6649]
Consider the following module:

```js
// @flow

export type FooId = "FOO";
export type BarId = "BAR";

type Box = FooBox | BarBox;
type FooBox = {| +id: FooId |};
type BarBox = {| +id: BarId |};

function getId<T: Box>(t: T): $ElementType<T, "id"> {
  return t.id;
}
```

This module [typechecks just fine][1], which is the correct behavior.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgBissAkgCagC8oARGQPKtMDcqmO+RJUACEAhtloNmQgIIAlLsgGkhsNJIqwVagD7CxW7kvKUtkgN66A1AEsaALmPU62gL6Hiy-avNXbD0eLObsiQAK4AdgDGuNaw4aAA5ii4tAA8ACr+qgB8ABS4DukAlA4AJACi0CgAtijhuOkeGQA0zLZM2aBmiKCg2Mmh2PG4AHS23C6IQA

But, suppose that we now create two modules:

**ids.js**

```js
// @flow

export type FooId = "FOO";
export type BarId = "BAR";
```

**client.js**

```js
// @flow

import type { FooId, BarId } from "./ids";

type Box = FooBox | BarBox;
type FooBox = {| +id: FooId |};
type BarBox = {| +id: BarId |};

function getId<T: Box>(t: T): $ElementType<T, "id"> {
  return t.id;
}
```

In Flow v0.76.0, this fails to typecheck:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ client.js:10:10

string literal BAR [1] is incompatible with string literal FOO [2].

 [2]  6│ type FooBox = {| +id: FooId |};
 [1]  7│ type BarBox = {| +id: BarId |};
      8│
      9│ function getId<T: Box>(t: T): $ElementType<T, "id"> {
     10│   return t.id;
     11│ }
     12│
```

In Flow v0.75.0, this correctly has no errors.

**Comment by SamChou19815** [comment]
These import related issues should be resolved a long time ago since types first
