### ISSUE TITLE
Any plans to allow importing in libdefs?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6650]
This doesnt work at all - it shows it works in the libdef itself fine but when used in any files it changes anything imported into `any`

There are hundreds of folders and files at multiple levels so importing stuff all over woudl take weeks if not longer to type when we could do it with a hour with a libdef... so... this sucks :( - the actual model is used about 8,000 times throughout the applications we use so sharing it with the various projects and just having it available all over is extremely ideal.

```javascript
/* @flow */
import type SequelizeType from 'sequelize';

declare type Example$DB = {|
  Sequelize: Class<SequelizeType>,
|};

```

```javascript
export const Account = ({ Sequelize }: Example$DB) => ({
  name: 'account',
  fields: {
    id: {
      type: Sequelize.THIS
    },
    a: Sequelize.DOESNT,
    b: Sequelize.CARE,
    c: Sequelize.CAUSETHEY,
    d: Sequelize.ARE,
    e: Sequelize.ANY,
  },
});

```

However, this does work as expected:

![image](https://user-images.githubusercontent.com/15365418/43350011-bbed5130-91b8-11e8-9d88-7f28f83cb06c.png)

Here is what VSCode shows it is getting from Flow when using:

![image](https://user-images.githubusercontent.com/15365418/43350103-638f15b8-91b9-11e8-93e8-2b0b36913944.png)

I can also peek the definition and see that it is clearly seeing the right definition:

![image](https://user-images.githubusercontent.com/15365418/43350126-96f59800-91b9-11e8-89c7-537d1ee39393.png)

**Comment by bradennapier** [comment]
I've come to the conclusion that libdefs dont work at all anymore.

I am declaring a module

```javascript
declare module 'whatever' {
     declare export type ECDSA$V = 27 | 28;
     declare export type ECDSA$R = string;
     declare export type ECDSA$S = string;
}
```

then i include it

```javascript
import type { ECDSA$V ... } from 'whatever'
```

and i use it on that file and it works fine...

now EVERY file that calls any functions declared with those properties automatically use `any` instead - which means i lose ALL typing in ALL libdefs i use anywhere in my app... absolutely stupid

```javascript
// module function
export const utils = {
   recover(hash: string, v: ECDSA$V, r: ECDSA$R, s: ECDSA$S): string {
        // ... does stuff
   }
}
```

^ this is in an object...

when called from a different module

```javascript
/* @flow */
import type {
  ECDSA$R, ECDSA$V, ECDSA$S,
} from 'idex';
import { utils } from './utils';
const { recover } = utils;

const signature = (
  _address: string,
  hash: string,
  v: ECDSA$V,
  r: ECDSA$R,
  s: ECDSA$S,
) => {
  const address = utils.formatAddress(_address);
  const compare = recover(hash, v, r, s).toLowerCase();
  return address === compare;
};
```

in this case it will type v, r, and s as `any` when within the module importing the utilities while it will type them properly ONLY in the module that declares the utils.

![image](https://user-images.githubusercontent.com/15365418/43417636-5d8535d8-93f0-11e8-96fd-403e155fbdba.png)

**Comment by fishythefish** [comment]
Yeah, we caught wind of this in #6414 and #6415. Having an `import type` in a libdef outside of a `declare module` causes this issue; moving it into `declare module` fixes it. We're revisiting our libdef parsing to fix/disallow this.

**Comment by johansten** [comment]
Importing the individual types from another libdef seems to work fine, but I've got a whole module I need to import in a libdef as a sub-module.

No-go, everything becomes Any. 

    declare module m1 {};
    
    declare module m2 {
    
    	declare var m1: m1;
    
    }

**Comment by bradennapier** [comment]
Yeah they need to add support for `import type * as Blah from 'blah';` which is supported outside of libdefs but not inside.

**Comment by Hypnosphi** [comment]
> Having an `import type` in a libdef outside of a `declare module` causes this issue; moving it into `declare module` fixes it

@fishythefish OK, but how can I declare a global variable of some imported type? `declare var` doesn't work inside `declare module`. What I want to do is this:

```
// flow-typed/globals.js
import type {MyType} from 'my-types' 

declare var myGlobal: MyType
```

**Comment by gnprice** [comment]
This issue can be closed as fixed.

Flow does support importing types in libdefs; you just have to do it inside a `declare module` block. And since v0.144, if you innocently try doing so at the file's top level, Flow has given you a good error message:
> Cannot use an import statement at the toplevel of a library file. Import statements may only appear inside a `declare module`. [toplevel-library-import]

---

I don't understand the comments about `import type *`, but that would be best filed as its own issue (if the original author, or someone else, is still interested in it.)

---

> OK, but how can I declare a global variable of some imported type? `declare var` doesn't work inside `declare module`.

Using `declare var` inside a `declare module` block, in a libdef, works fine for me in some quick testing. If there's something there that doesn't work, it belongs as its own separate issue.
