### ISSUE TITLE
flow-parser@0.77.0 is missing in the npm registry

### ISSUE THREAD

**Issue by ikatyang** [facebook/flow#6652]
https://www.npmjs.com/package/flow-bin?activeTab=versions
https://www.npmjs.com/package/flow-parser?activeTab=versions

I'm not sure why `flow-bin@0.77.0` was already released but `flow-parser@0.77.0` is still missing.

**Comment by fishythefish** [comment]
I believe one of our automated jobs failed due to npm invalidating some tokens: https://status.npmjs.org/incidents/dn7c1fgrr7ng

v0.78.0 will be released this week, though, so if having v0.77.0 isn't critical, I would just wait for that.

**Comment by lll000111** [comment]
What is this parser used for anyway?? I never found any documentation.

**Comment by lll000111** [comment]
Never mind - the 2nd time in less than ten minutes that I have to remove an issue comment because immediately after posting I realize it's silly.

**Comment by ikatyang** [comment]
https://www.npmjs.com/package/flow-parser/v/0.78.0
