### ISSUE TITLE
Unexpected and incorrect error message when passing `any` type as initial value to `Array.prototype.reduce`.

### ISSUE THREAD

**Issue by serhalp** [facebook/flow#6656]
### Background
`Array.prototype.reduce` has [two signatures](https://github.com/facebook/flow/blob/27d4ac68457e097061f99fb22411244108dbae36/lib/core.js#L216-L223). When the second argument (`initialValue`) is omitted/undefined, the first element of the `this` array is used as the initial value, so the type of the accumulator argument (`previousValue`) to the first argument (`callbackfn`) is `T`, the type of array elements (also the type of `currentValue` and the `reduce` return type). When the second argument (`initialValue`) is defined and of type `U`, the accumulator argument (`previousValue`) to the first argument (`callbackfn`) is `U`, which is also the `reduce` return type in this case but different than the type of `this` array elements and `currentValue`.

### Bug
The types all appear to be correct as far as I can tell, but in one particular case I would not expect an error _and_ the error message is factually wrong. In [this code](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeAPpAQFygDOKATgJYB2A5uQL4DciAxrFYNQVWHVoBBRowCGaADz5YAPmKgA2qTG0A5LIBG-XVwC6fVJhwAhWY3UUDd2rgCurfimZDufQcJRQJ3sSUmDaAAoASmI1Ui5eZBBQAElWZi9ZaFAANyzXHFhIUHRsUAADW0Zy0ABaUFZCLBlYRkQxOgA6RiwAE1d+LAjEUFAI2X5+ABpRAhiiONAJ-k7g6J5QHpRXRlYlyY2uKZGx8NAqqMQoi2S0jOYs3PzC4tKcctlWNBr69ywAD2wnj6oEkADkACKgNiCGRYTygZqMVrtAhdHr9QbDUbjSYzMTzRbLVZ2dabLDbXb7fiHY44s6fNCXa5JMBgwhse6PPLQAozZgAWww0GY-Ay0DQs3EGgADKZQEUSlYKsofojAfCUCCkSiOt0+gMhidcdMpYSyNSSYwyVsdntlocrjwgA), you can see that when using an initial value with a `Bar` type, flow understands that the accumulator (first argument to `reduce`'s first argument) is of type `Bar`, and when omitting an initial value, it understands that the accumulator is of type `Foo`. But when passing in an initial value typed as `any`, not only does it error, which I do not expect (that's the whole point of any – you can call `.bar()` on it even if it doesn't know that it's there...), but more egregiously it outputs an incorrect and misleading error message:
```
Cannot call `acc.bar` because property `bar` is missing in `Foo` [1].
```

The property `bar` is not missing in `Foo`. `acc` is of type `any`, not `Foo`!

The only explanation I can think of is that because it's typed as `any`, it could be `undefined`, which would make the accumulator's type `Foo`. But even in this case flow is not painting anywhere near the full picture.

### Related issues(?)

These issues may be related or the same? I can't quite tell:
- https://github.com/facebook/flow/issues/5339
- https://github.com/facebook/flow/issues/5182
- https://github.com/facebook/flow/issues/4214

**Comment by wchargin** [comment]
[Here is a simpler repro:][1]

```js
// @flow
["a", "b"].reduce((acc) => acc * 2, 1.0);  // works
["a", "b"].reduce((acc) => acc * 2, (1.0: any));  // error!
```

(The expression is valid and evaluates to `4`.)

> The only explanation I can think of is that because it's typed as
> `any`, it could be `undefined`, which would make the accumulator's
> type `Foo`. 

Yep, this looks to be what’s happening. If you simply write

```js
foos.reduce((acc) => acc, (bar: Bar));
foos.reduce((acc) => acc, (bar: any));
```

you can see that in the first case `acc` is inferred to be of type
`Bar`, and in the second case it is inferred to be of type `Foo`. (Place
your text cursor on `acc` and look at the footer at the very bottom of
the window, which shows the inferred type at the cursor.)

Swapping the order of the `reduce` declarations in the `lib/core.js`
definition does not fix the bug.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBtARAQ1QGlKgRqgLoB0ATgKYAmArgMbkAUD6ttAlKALwB8oLtoAFSgATDgCMxAAxsA3KFAhQ8WKQDWAZxQZsuAiQo16Tfhx59WQ0TgaSpALj4A7AJ5s5CpeVKlVAQkQgA

**Comment by Bannerets** [comment]
It can be fixed with `$Trusted`:

```js
  reduce(
      callbackfn: (previousValue: T, currentValue: T, currentIndex: number, array: Array<T>) => T,
      initialValue: $Trusted<void>
    ): T;
    reduce<U>(
      callbackfn: (previousValue: U, currentValue: T, currentIndex: number, array: Array<T>) => U,
      initialValue: U
    ): U;
```
