### ISSUE TITLE
$Values create a weird side effect

### ISSUE THREAD

**Issue by tanhauhau** [facebook/flow#6658]
See [flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoApgDwA5wE4AuYAxnAHYDORAYgKIAqAwgBID6AkvbQLIDKAXGADeqMGABKtAIoBVWry4ARQQHI6TNpx69Wk2fKUqANKLC8ZjRvIFg1DFhy59W5y9eOnqAQXYAZWsq26g5azt5+AR4AvmAAvMKmenIKAarBmk46SQaRJmKuVrw2dhqO2i4WhbweYuH+gSUhmax1uahRANyoqFAArmTEBACW5GAAhoMjZNToBMQAFuLoAI696FQAFKvoeACevAR4Q2QA5oJUR6cAlAlieLO9eGS3YmAEu9jogullfAB02RSijyr2wY128DGABNBEIwNs9gdLicwFEQZ12t0+gNhqMJrjprMFtQxkMYBtTDs8PhBGRegBbABGOxBCP2h2OZzAF05qBuIjuDyeLzE70+33sGW0f1awNMYjBELg0Nh8tebKRnJBrzAVJpurw1Lw2tR6K6UW6pEoRFITOO6ChXkmo3iAvGzsJc0WKzWVBB+KmMy9JLJJgxqDF6DAtEwh3xSwIj2e8QAPOIAHwbDZ-HNjPAnCiCEA3WLpiQlsviLqRsBOgkUGRkKa8TkwdBLKG9Yg7FP0MvxAAkADUxjBfSmBwB5RkAK24Y2wvaM0djeHjQrI6fTXVQwGAYBOsze8yjAfIFDAcFn6EGbw+UfuieFUGp9PdBJI9zGBHwEfvtY9OIAPrRtm1bdsHS7HtIzgKASDgO0yAdOspm3NUxB6fpAPuTtuzwDYzzIQQUPIflTCGOCCI9P4a1iOiwB+UJeBlHx6jInVCK6MQLQtIA)

in summary, im having a object of action types for redux:
```
export const FETCH_ITEMS: {
  REQUESTED: 'FETCH_ITEMS_REQUESTED',
  SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FAILED: 'FETCH_ITEMS_FAILED',
} = {
  REQUESTED: 'FETCH_ITEMS_REQUESTED',
  SUCCESS: 'FETCH_ITEMS_SUCCESS',
  FAILED: 'FETCH_ITEMS_FAILED',
};
```

and i have my action creators:
```
function actionFetchRequest(...) { 
   return { type: FETCH_ITEMS.REQUESTED, ... }
}
```

and im creating a action type by doing
```
const allActions = {
  actionFetchRequest,
  ...,
};

type ExtractReturn = <R>((...args: *) => R) => R;
type ActionsUnionSingleReducer<T> = $Values<$ObjMap<T, ExtractReturn>>;

// get the actions object type return from action creator
type Action = ActionsUnionSingleReducer<typeof allActions>;
      
function reducer(action: Action) {
  if (action.type === FETCH_ITEMS.FAILED) {
    action;
  }
}
```

so what's wrong: somehow at the point of doing `$Values`, it will affect the type of FETCH_ITEMS object to become something like
```
 {
  REQUESTED: 'FETCH_ITEMS_REQUESTED' | 'FETCH_ITEMS_FAILED',
  SUCCESS: 'FETCH_ITEMS_SUCCESS' | 'FETCH_ITEMS_FAILED',
  FAILED: 'FETCH_ITEMS_FAILED',
} 
```
, which i don't understand why. can someone please explain what is happening?

**Comment by retyui** [comment]
Your action creator return any 
![image](https://user-images.githubusercontent.com/4661784/48665209-cc2bb300-eabb-11e8-9328-8736a5ccbbc9.png)


When you will use arrow function type will look better
![image](https://user-images.githubusercontent.com/4661784/48665202-9c7cab00-eabb-11e8-8dc3-2c5ed4c67d2e.png)


I recommend to check documentation  [how to work with Redux Actions in flow.js](https://flow.org/en/docs/react/redux/#typing-redux-actions-)

**Comment by SamChou19815** [comment]
The issue is fixed a while ago
