### ISSUE TITLE
Utility for getting a union of all values at a given key in an array of objects

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#6659]
```
const myObjects = [
  { name: 'foo', age: 123 },
  { name: 'bar', age: 424 },
]
```

I want a DRY way to get the union type `'foo' | 'bar'` based on the above array. There doesn't seem to be any combination of [utility types](https://flow.org/en/docs/types/utilities/) that could work for this.

**Comment by M-TGH** [comment]
Similar as you seem to have experienced in #6651, flow defaults literals to it's primitive Subtype. Which ends up forcing you to often type these kinds of values. Flow often prefers not having to infer computed values.

Would recommend something along the lines of [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCiAbrgHboAqOuBpArgLZgC8YA5AMZymm4fq4AJmzAAfdoICWAZy48+A4QG5UqSeVwAnKAEMO+AEI7pNEuQDeqMGFxn0ALkJ2qeWoxUBfVXOnowDTGIydGlHIxMg8gBtAF0WMCirMHMbO0dObl5+ITYAGjBJQUcARjAPXKSU22D0qVlMhRz8wpL89EkGXEdeJAARHQEACgBKMoqYlVRgYDAAdUkYGDBNXGk6GD91MAAjY0kOHUXMMHQAC3xpHU6wYydglxp6BgxqMABxXHRIylfWABIAAqaOB4TRYB4AHj+BBguE65EhWDwcCg-kCdmk+Se2y0AD58mxquQ2LiVNMwNCAB54fgETTAzSoHx+AS+RwfL7OX5gYpkmazOCaADW0iZ3F8YDkWU5wQAclcuu9Pt8HvEMvJsspVOSVdQ3ExmIalTKEdQxaQJd99Y5da4nvEpQpvvLOkowEA):

```js
/* @flow */
type EventTypeEnum = 'connected' | 'disconnected';

interface BaseEvent{
  event: EventTypeEnum;
}

const myEvents: BaseEvent[] = [
  { event: 'connected', id: 1 },
  { event: 'disconnected', id: 1, time: new Date() },
];

// Will result in basically the same as EventTypeEnum
type GetEventType = $PropertyType<$ElementType<typeof myEvents, number>, 'event'>;
// $ExpectError
const test: GetEventType = 1;
// Works
const connectEventName: GetEventType = 'connected';

// EventTypeEnum === GetEventType
const EventEnum: EventTypeEnum = connectEventName; 
```

**Comment by callumlocke** [comment]
Thanks @M-TGH, but I should have mentioned I need to do it completely dynamically, so I can do it with an unknown object, via generics.

Contrived example using the imaginary `$UnionOfValuesByProperty` utility that I want:

```jsx
// Ideal library definition
type Person = { +name: string, +age: number };

declare var selectNameOfOldest: <A: Array<Person> >(A) =>
  $UnionOfValuesByProperty<A>


// Usage...
const oldestPersonName = selectNameOfOldest([
  { name: 'Bob', age: 30 },
  { name: 'Alice', age: 52 },
]);

// oldestPersonName should now have type: 'Bob' | 'Alice'
(oldestPersonName: 'Bob');    // OK
(oldestPersonName: 'Alice');  // OK
(oldestPersonName: 'George'); // Error!
```

**Comment by SamChou19815** [comment]
`type T = (typeof myObjects)[number]['age']`
