### ISSUE TITLE
Unexpected difference between `object` and `{...object}`

### ISSUE THREAD

**Issue by LaureRC** [facebook/flow#6662]
_cc @tychota_
### Reproduction
Successfully reproduced on https://flow.org/try/ from version 0.60.0 to version 0.77.0 : **[LINK](https://flow.org/try/#0C4TwDgpgBACgTgewFYQMbACrmgXigbwEsATAfgC4oBnYOQgOwHMAaKegQwFsJKa6mAvgG4AUCID04qAygIArnChhEKdFGAALQlSUQ4AMwRxOUdlFTsANpfUIoAEQBCt6uwBu0TdHoQA7kpU0YBFUS3YqHXhkIKcCEShqYHZgQlRTKhB6NNQ4CGSIAAplaPRKKNVMbABKMsRObQgAHnKgrEgAPjiEhNzgBXoAkuBRBIEoEQExSWkBqgRuc3DoX2gqDXlLYnNLBB91DWhiioA6CSkDrM8D7d2IFrV9OSyU3ampWhA2AAaARhFwzJpR7PQi7G4+e7AAByAHkANJFQKlWBIyqQKpdcy7GgEEisY4Eo5BADqhE08mAAEliGM8ET0CNxglphgtDpiAgIDp6AhgFBfEYANZUVi+A65KCUqAQAAekDUZJcArgwviUGmMmIEAgxFY9OApPJcipWw5XMShGs1HlhH0n30O38qF2tHYaioDFQ3i40G0UC1+gYEDVkKcxxyeWAhX1hvWxupVVEkzO6jgn3oXwATP8MlkoMD0KCBqFbpD4T9EUNakM2hAMfg1c76DiiLqoATjjGyXGTbTBhVGWqWWyHDCAKIAZWocmU2gYjEsn2VwtF4ugUtl8r5iuAdg51EI9TCik07AGH2+f2ZUgAEgh-H6vODoAAjT4IF8VKC5HEMKNwZQICjLY33zR0Zn-DhrBAIcpClQUeSdHYfC2D8v1dZtDGMaUZTdPlQEgFwg1wtQX2NKA1xRGtsGkbleWtNBbU+cIoDHEjgmvag7E0P0dgQYV+QgQg4C2XcoG4ENUTDCN8gKfAOy7I1e0TCYxBCbE+X1asKlrKA8HwaRiEoAAiAB2LUABZ2EzfQAE4AFoIAAVh+Cz7IszMnJfez2HYF8fnszN2AADgANgsN0AAYIB+YLjNYDhuBMok+R+YyoGEEJkLuVFYQRfUqiy0tUXLSsKkKs5JCq6qatqurxEqqqoAAGSAnQLzcdg6DPPlasa+qBoGt5U3TL4AGYU2XHRAz2FjNyCUx6C2P1ihfPzF32V8uT5Xx2E+MT9zIvkqG1TgdCoGc9FkDw4GdTgwEsWUXAk6ZHr5BYePoQV+Q0ZIoBAeR9gYb6EH0aQ+VIEQCOgSFa1jak9NxIzEn4Fg2B9XhaHnSZoaonTsFjCkEbwAASAAlbbmlROHu2pVh8GMkhjMx1GBHaKGaNh7AADUusIHrEa5yB4a2KAAB88daAnuyJ4hRDEUJwkiKTHEzTEaGSVJ0kBcxclkrTJfQWtee6+hgBqKj6hOqnqOF2niE6Btum-ID+iRkzzIgKybIc5zXPczzvN8-zApC8LfNQaLYvi9tCVRTLRnGZMATzAsXmLbKyzhTMyqCbSpbtzQE0xaYeJ0fkhWmoNGw0pH8TjoZCfjGlEf1QcElDVXwz1qM5IU1Em+UpMFdr-VM3zo3paLrZ9MMj3LOsuzHJctyPK8ny-ICoKwoiyOYrihKMagYyUqgNKMtEEsIRK7Pc-QTMqiAA)**

### Expected
- try 1 works
- try 2 performs similar to try 1, so works (or fails if try 1 fails)
- try 3 works

### Actual case
- try 1 does not work
- try 2 works 🤔
- try 3 works

### Questions
- Is it expected for try 1 to fail ?
- How does flow understand {...rest} internally ? Why does try 2 work if it is expected for try 1 to fail ?
- Isn't try 3 overcomplex in my case ?

**Comment by tychota** [comment]
0.59.0 displays no error so if it is a bug, this as been probably introduced in 0.60.0.

[changes between 0.59 and 0.60](https://github.com/facebook/flow/compare/v0.59...v0.60)

**Comment by goodmind** [comment]
This was fixed in Flow v0.100.0
