### ISSUE TITLE
Alternative version of --no-auto-start

### ISSUE THREAD

**Issue by ianobermiller** [facebook/flow#667]
Use case: I want the same command to run in dev and CI. When run:
- If flow server is started already, it just runs `flow status`
- If flow server is not started, it runs `flow check`

Similar to `--no-auto-start`, except instead of quitting it falls back to `flow check`.

`flow status --no-auto-start || flow check` almost works, except it `flow status` returns an error code if there are any errors, which will then cause `flow check` to run redundantly. I could check the status code, but then we have left universal command line compatibility (of course flow doesn't support windows yet, but it will eventually).

**Comment by calebmer** [comment]
You should be able to use the status code. I believe `flow status --no-auto-start` will exit with a code of 6 if the server has not started, but with a code of 2 if there were some errors. Please let me know if this approach is inadequate and you still need this 😊
