### ISSUE TITLE
In union types `undefined` does not unify with `void` unless explicitly typed

### ISSUE THREAD

**Issue by jasononeil** [facebook/flow#6673]
URL to reproduce:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ASQMawB2AKpjgLygDeoAlgCYBcoAzigE51EDmANKABudLPABCsAB4t2XXqAC+qcnkJEAarEagqtOmpaCtDRQG5l2VcQAKHLKyxEUOmvQNXSKhefSWAcsQORA5kllQExJraAD4etvaOKOaIauxuNnZBKCwBwY4hKrrpRCx6zKAA5BUCwqIS0pUVimbIqc76kcY5gflYoZSuHSWgABQArkQMWJDcWOVGjACULSmB7WpRDADKABawY9AMAOqwHADW3Xl5-S567hNTM0RzLUA

**What happens**

This code:

```js
// @flow

type IconType = { id: string, viewBox: string }
type IconVoid = { icon: void };
type IconPresent = { icon: IconType };
type NonsenseType = IconVoid | IconPresent;

const iconPresent: NonsenseType = { icon: { id: '', viewBox: '' } };

const iconVoid: NonsenseType = { icon: (undefined: void) };

const iconVoidShouldWork: NonsenseType = { icon: undefined };
```

Generates this error:

```
    12: const iconVoidShouldWork: NonsenseType = { icon: undefined };
                                                 ^ Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To fix add a type annotation to `undefined` [3].
        References:
        6: type NonsenseType = IconVoid | IconPresent;
                               ^ [1]
        6: type NonsenseType = IconVoid | IconPresent;
                                          ^ [2]
        12: const iconVoidShouldWork: NonsenseType = { icon: undefined };
                                                             ^ [3]
```

**What should happen**

Line 12 should pass in the same was as Line 10. Or more explicitly, if "`(undefined : void)` allows you to unify, using `undefined` without the explicit type should also.

**Context:**

We are trying to build a react component that can accept `<Button icon={...} hideLabel={...} />` props but can only accept them "hideLabel" if "icon" is provided, using a disjoint union:

```js
type Props =
 | { icon: void, hideLabel: void, iconPosition: void }
 | { icon: IconType, hideLabel: bool }
 | { icon: IconType, iconPosition: 'before' | 'after' };
```

I suspect using 

```js
type Props = {} | { icon:IconType, hideLabel: bool } | { icon: IconType, iconPosition: 'before' | 'after' }
```

would be closer to what we want, but because `icon` isn't present in the first case it's not a proper disjoint union. In investigating further we found the bug above which we thought is worth reporting.

**Comment by SamChou19815** [comment]
Now it works
