### ISSUE TITLE
Cloning a tuple and preserving type info?

### ISSUE THREAD

**Issue by MarkKahn** [facebook/flow#6677]
I'm trying to figure out how to clone a tuple while preserving type info, e.g.:

```js
type pair = [number, number];
const MY_PAIR: pair = [1, 2];
const ANOTHER_PAIR: pair = MY_PAIR.slice();
```

This fails because `MY_PAIR.slice()` returns a generic array, as does `Array.from()`.  Is there a clean way to do this?

**Comment by SamChou19815** [comment]
Closing since we can't special case for every library functions.
