### ISSUE TITLE
Bug: "Could not decide which case to select" when using $Shape and an intersection of function types with differing parameter count

### ISSUE THREAD

**Issue by philippotto** [facebook/flow#6679]
[Flow try](https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQMQHYAYA8ASgHzwC88AFAJRkkHwA+8ACjAPYC2AlgM4iEkmAcRBYQMKIjYw8AKgA0BebKIBuAFChIsBCnTxsARjwAVQ-PjEylRIYBc8MzVJ1GLdtz4C3IsRKkyCkoqGlrQcEhomFgATKbmjjEWVuQUtg5mFogxGTHOrkysnLz8VsKi4pLScorKauqa4OG6UfAAwlAQENhk6vDwAGSUhBbYDtj4xEQUAGZY41j5llR9g8OZlqPzBljGG1Oz29hZ9o6GSwQr-QD01-AAkjNIABYIM2xdbADuXFgA5vAIL8ELx4HAOGwAG4gYBZV7wEAADygHFQEAQX2kAGseKshhR4hYTElNjsFnENsTkkRpnMFicMglsrkLitGtoIpDYPAwJ0IPAHB0utgNP0xeKJeo9AgAMootEgEytcgAbwYqywKJADh4iBgvz+8lWoB4YH1qEQXDY211+v+RoYAF9RRL+upbvAAOqvLDwHjy9EYACuWDAlutSCgWJAPHgUHgctR6KV+l+upAUGA8DYTwAJDLnlB0HhEwqUyAiHCEEiAxjsbiZiGw1bff6kyBg6Hw1gKGAHPnC8XS8mokQqA5IWwuFmVY6Go2uy34HMKKgHMPFVEaCrVquAHSajjav16g1UF37k1mrgWls60--c+rSU3O6YmA41ZthWd5vWig7uKh7HqgB5aka-SOmyr7wMAbAxvAWBsIg8Dvliqy8l0FDfoGTbdhYgFisBDigcBEHwFBGiOkAA)

Code to reproduce:

```js
declare type Fn0<R> = () => R | Promise<R> | Generator<*,R,*>;
declare type Fn1<T1, R> = (t1: T1) => R | Promise<R> | Generator<*,R,*>;
declare type Fn2<T1, T2, R> = (t1: T1, t2: T2) => R | Promise<R> | Generator<*,R,*>;

declare type CallFn =
  & (<R, Fn: Fn0<R>>(fn: Fn) => R)
  & (<T1, R, Fn: Fn1<T1, R>>(fn: Fn, t1: T1) => R)
  // If the following line is removed, the example works
  & (<T1, T2, R, Fn: Fn2<T1, T2, R>>(fn: Fn, t1: T1, t2: T2) => R)

declare var call : CallFn;
              
type SampleType = {|
  name: string,
  description: string,
|};
        
// When sampleFunction takes a SampleType instead of $Shape<SampleType>, the example works
function sampleFunction(c: $Shape<SampleType>): void {}

function fn(p: SampleType) {
  (p.name: string);
  (p.description: string);
       
  // works
  sampleFunction({
    name: p.name,
  })

  // does not work
  call(sampleFunction, {
    name: p.name,
  });
}
```

Sorry for the verbose issue title.

**Comment by gkz** [comment]
Does not error if using the safe replacement `$Partial`:
https://flow.org/try/#0CYUwxgNghgTiAEAXAngBwQMQHYAYA8ASgHzwC88AFAJRkkHwA+8ACjAPYC2AlgM4iEkmAcRBYQMKIjYw8AKgA0BebKIBuAFChIsBCnTxsARjwAVQ-PjEylRIYBc8MzVJ1GLdtz4C3IsRKkyCkoqGlrQcEhomFgATKbmjjEWVuQUtg5mFogxGTHOrkysnLz8VsKi4pLScorKauqa4OG6UfAAwlAQENhk6vDwAGSUhBbYDtj4xEQUAGZY41j5llR9g8OZlqPzBljGG1Oz29hZ9o6GSwQr-QD01-AAkjNIABYIM2xdbADuXFgA5vAIL8ELx4HAOGwAG4gYBZV7wEAADygHFQEAQX2kAGseKshhR4hYTElNjsFnENsTkkRpnMFicMglsrkLitGtoIpDYPAwJ0IPAHB0utgNP0xeKJeo9AgAMootEgEytcgAbwYqywKJADh4iBgvz+8lWoB4YH1qEQXDY211+v+RoYAF9RRL+upbvAAOqvLDwHjy9EYACuWDAlutSCgWJAPHgUHgctR6KV+l+upAUGA8DYTwAJDLnlB0HhEwqUyAiHCEEiAxjsbiZiGw1bff6kyBg6Hw1gKGAHLnmLBLZ0S7Xy0QqA5IWwuFmVY6Go2uy34HMKKgHKXk1EaCrVuuAHSajjav16g1UF2Hk1mrgWls68--S+rSU3O6YmA41ZthWd5vWhQe7isep6oEeWpGv0jpsu+8DAGwMbwFgbCIPAn5YqsvJdBQv6Bk23YWMBYqgQ44GgVB8AwRojpAA

https://flow.org/en/docs/types/utilities/#toc-partial
