### ISSUE TITLE
Bug: $Exact of a type intersection doesn't work

### ISSUE THREAD

**Issue by Dremora** [facebook/flow#6680]
See the following code:

```
/* @flow */
type A = { a: number };
type B = { b: number };

type AB = A & B;

type ABExact = $Exact<AB>;

const abExact: ABExact = { a: 42, b: 42 }
```

**Expected outcome:**
No errors.

**Actual outcome:**
```
9: const abExact: ABExact = { a: 42, b: 42 }
                  ^ all branches are incompatible: Either cannot assign object literal to `abExact` because property `b` is missing in `A` [1] but exists in object literal [2]. Or cannot assign object literal to `abExact` because property `a` is missing in `B` [3] but exists in object literal [2].
References:
5: type AB = A & B;
             ^ [1]
9: const abExact: ABExact = { a: 42, b: 42 }                            ^ [2]
5: type AB = A & B;
                 ^ [3]
```

Flow version: 0.77.0

**Comment by SillyFreak** [comment]
I'm hitting this bug as well. This would be very useful for CRUD interfaces:

    type Id = {
      id: number,
    };

    type Values = {
      name: string,
    };

    // a record must have an ID and all fields
    type Record = $Exact<Id & Values>;
    // ID can be auto-generated and is optional
    type CreateRecord = $Exact<$Shape<Id> & Values>;
    // ID is constant, only values can be updated
    type UpdateRecord = $Exact<$Shape<Values>>;

(or something like this, not checked closely as it doesn't work anyways)

**Comment by SillyFreak** [comment]
for people finding this bug, I just stimpled over [this](https://github.com/facebook/flow/commit/ad443dc92879ae21705d4c61b942ba2f8ad61e4d), which will likely work for most use cases: instead of trying `$Exact<A&B>`, try `{| ...A, ...B |}`.
