### ISSUE TITLE
Flow not recognizing function parameter defaults

### ISSUE THREAD

**Issue by JDWong-wag** [facebook/flow#6682]
Not sure if that has been posted before, but flow doesn't properly recognize parameter defaults when determining parameter types within a function.

Example:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiArgHYDGYAvGABQD8ttAlNQHxgC2AlgB54ATZqyocAbnG4CA3OnJxSAZwxgoZcgC4i66nU5YSFXS3ZgA3gF8RHM6gCQ+w+RayLQA

```
type Func = (?(() => mixed)) => void;

const func: Func = (myFunc = () => {}) => {
  myFunc();
  // ^ Cannot call `myFunc` because null or undefined [1] is not a function.  
}
```
The `myFunc` can never be null or undefined since it is set to an empty function by default, but flow doesn't recognize this.

Is this a bug in flow or am I just using it incorrectly?

Thanks!

**Comment by knyzorg** [comment]
```
>> const func = (myFunc = () => {}) => {
	    myFunc();
      }
>> func(null)
<< Uncaught TypeError: myFunc is not a function
```

Working as intended

**Comment by jcready** [comment]
@knyzorg is correct, default parameters only get used when `undefined` is passed or the argument is omitted. If `null` gets passed then the default is not used.

**Comment by JDWong-wag** [comment]
That's right, thanks for your answers @jcready @knyzorg

**Comment by knyzorg** [comment]
Oh by the way. I just realized, you were likely interesting in the following:

```
type Func = ?((() => mixed)) => void;

const func: Func = (myFunc = () => {}) => {
	myFunc();
}
```

This says that the argument can not exist, but if it does, it has to be the function.
