### ISSUE TITLE
Losing read-only property when composing types

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6684]
# [Try Flow](https://flow.org/try/#0C4TwDgpgBAJAogJwQewQZygXigbwD4BQUxUA1AOQCWAdgG4CGANpQCYC0ESq5AXFAJyCANERIUARvXYIIARwCuENMF5QATABYRxPAF8A3AQKhIsRCgQwAygGMAFhAC29ADykA0nxjuIINC-gudAA+YKxcQhIoAHpoqGAHKE4LKBtkFmh6NDRkG0p6YAgWKAB3SgT4xOTUePAIUWJSNIyvOEYnCGpgABU6gPNUNCEod2DtMUclNHoAcwg+AAoTeahlBBoZ4YA6HfoEGbQ+emoQAG0AXQBKLDC1jfG9Q2M62ABxCGABhFsHZ3CXUYLdzXTBhQIWaz2JyuUZPNLUZRJIKHWAAeXEACsALL0MCUfrI4Ywd6fII-aFhbA4URUOhMVgcIKqalRZorQT8cbESbZWYrZY3KAAAwAgtQoDQGMxitUEKUslB5GgilBkAAzWqmABEMBwy10WuGstWUL+1GQwCgauQ8moLC2xAACu0stAaNaEI4oFZ5GAwKhgFsheNdONyJJpHJFMpmQ1UukVpouVAedM5osQWFyGKJXTpVAZAolJaSgqZDYIJRaEVyCGRAYjBAAB7+hCWmyMLIYADCSuAyEcXzc3S8Pj8BIsaFCSSbhTtGC+uFEpGWfG6T0abNa7UmXV6kAng2G3WCG-jCOACHkNn7CCWdTX212+xRxzOVyXrOQF5Nv3orSCSE-xcE9wllNBTmWc5DC-H9Uz5cI0FNegtnguZ70gJ8tj2A5LjPYg0F9TgFjQiA8LjL4thsXFgHkGQrGAegbAAa26BAmIgJY7EoIYoF7ZQBy+ci4wSHitmoehJnCch+P7QcmRgkhRLQLYBWwZZFOIZSqITRDkJ0jJNMqMTSPCUjFN0AhLKiYg41s+FEWScJqAgEo+L7QSggWcMpDYQtoxUcibKgAgFmSAzEw0IKbNC8LVygHzIyLGM8KAA)

I have ripped out the specifics as much as possible from this example to show what is going.  It gets so close to working, which will be insanely awesome - but it is losing the generic type <T> when I give it to an object (likely due to the constraints I have to place upon it).

It gets everything right except the schema object it is returning appears to giving unions for all properties even though it is receiving more than enough information to know exactly what value it should be.

More evidence here which doesn't even make much sense to me is the fact I need this:

```javascript
const schema: $Error$Schema<T> = errors[type];
```

Since `type` is a read only parameter in the constructor, and we can validate without a doubt that it is a string literal of a given value that will never change, this should absolutely work.

Without the extra definition on schema it should absolutely know that it will be the value as defined.

This level of typing would be critical.  If I do

```javascript
const err = new CustomError('bad-request');

const { code } = err;
```

in the case above, there is absolutely no reason it shouldn't be able to tell me the code is 24.  This is the type of thing that will be actually useful during development rather than it just telling me its a number - it can actually take the property its given and tell me.  If i don't feed it a string literal and its a var that is "string" then sure - or if i were to give it a var which had a type of `$Keys<$Errors>` or something then it ofc would be a union.

In this case this is actually across multiple files and the top portion of the `try` example is imported into the other files through a libdef.

**Comment by SamChou19815** [comment]
The example seems to work now
