### ISSUE TITLE
Given type X = {a: {b: string, c: string}}, objects of type X aren't assignable to variables of type {a: {b: string}}

### ISSUE THREAD

**Issue by evankroske** [facebook/flow#6686]
## Interactive Example
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAaYAvGAN5gCGAXBWAEZ0DOGATgJYB2A5gDRgAxi3bceYAL6SA3KkFwurMAA86xMpVr0mYAORQ4cXQOF7dkmXIVKsdTXcYjOvC1LLLpQA

## Error Message
Cannot assign `x` to `y` because property `c` is missing in object type [1] but exists in object type [2] in property `a`.

## Description
It seems like Flow's width subtyping doesn't work for properties of properties.

**Comment by wchargin** [comment]
Flow is correct. If the assignment were permitted, you could write

```js
// @flow
type X = { a: { b: string, c: string } };
const x: X = { a: { b: "foo", c: "" } };
const y: { a: { b: string } } = x;
y.a = { b: "where did 'c' go?" };
if (x.c === undefined) {
  throw new Error("Impossible!");
}
```

to get a runtime error thought to be statically impossible.

Correspondingly, [the error disappears if you mark `a` as read-only:][1]

```js
// @flow
type X = { +a: { b: string, c: string } };
const x: X = { a: { b: "foo", c: "" } };
const y: { +a: { b: string } } = x; // no error!
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagBqgLygDeoA1AIYBcxoARtQM7IBOAlgHYDmANKAMaMWHTqAC+YgNyI+sdk1AAPankIkqNeqABEkWLC28B2rWMnTZ81NRIVrdQWy6nxhBRNAhQ7WKEzNmsMwAhIhAA

**Comment by evankroske** [comment]
@wchargin, yep, that makes sense. Thanks for explaining this!
