### ISSUE TITLE
Flow doesn't detect any error in foo.js when foo.js.flow is defined

### ISSUE THREAD

**Issue by GuillaumeJasmin** [facebook/flow#6687]
Hi,
I have some trouble to work with `.js.flow` files. I have 3 simple files:

hello.js
```js
export const sayHello = name => {
  return `Hello ${name}`
}
```

hello.js.flow
```js
// @flow
declare export function sayHello(name: string): string
```

demo.js
```js
// @flow
import { sayHello } from './hello'

sayHello(12) // flow error, so it works

sayHello("foo") // no error, so it works
```

Everything seems works fine.

BUT, when I make a mistake in my hello.js, flow doesn't detect any error:

hello.js
```js
export const sayHello = name => {
  return 10 // flow should throw an error because it's not a string
}
```

Any idea how to works with `js.flow`, without need to add type into `hello.js` ?

**Comment by GuillaumeJasmin** [comment]
Thank you very much ! My understanding was bad, it's better now

**Comment by evbo** [comment]
@lll000111 The [Declaration Files](https://flow.org/en/docs/declarations/) docs only specify that `declarations` statements will be used from .flow files, just like OP showed.
