### ISSUE TITLE
Misleading error when spreading properties in JSX

### ISSUE THREAD

**Issue by StevePotter** [facebook/flow#6688]
[Reproduced on flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAYnuQOaakB2tYBAntlJgAwnBxwu3AgBVBwgL5goecWADkeCtXWpUAoaLgwAyugBewgLxguAV0wAjUnjAAfMI7jGKXPaQAPXEI+eSMYAAVVbABnMBt6N1QwMBg2AH4ALnCzSxpUNwU9YGBPchjhSnFcKR5UQOCiKq4YojEYbLEJWtl5AB52qLhYgD54sAAKbGiYgEp4sYnksD6Wdk4eBgA6HenhmKVgEdRZ4tLKO1a1Ku7pPgALciI4ADcXPHQAE1I4tLAX8gwOykVAlTyqADW3AAhClHHYiAR7sJ3vgwJwYjF2MJ0HFMLiYBRPuguGx6kF8E1JK1wgAhSHcTrVSTSORCAbGIajcZTGbzKyLZYcmDLFJpKz0ACMACYiikUvQdls9rE5WAjiczmAWcp0AEwLiwNgEQQSWxUubnPAkEjhDFpkTyY0wM0ae0mHrJUzbjw2aRhVyYmMbLz9vzBSlhaLtrsZmqxWwJTK1RrTvLQaVyFw4LbXFA9Qa4uRPsTSRblKpMEaZk7KS7qW1jB6AtLvTVWf1BjNg5NGGk6EqVXEFOHJkL2tHxfQ-m4PMno4rY-sU8c0-KUkA)

We are building helper layout components with different Col types.  There is a base column we use, and then try to add another helper component like:
```
export const ColBroken: ComponentType<ColProps> = (props) => (
  <Col
    lg={12}
    {...props}
  />
)
```
The error is:
```
7:   lg?: ColSize,
          ^ boolean [1] is incompatible with number [2].
References:
7:   lg?: ColSize,
          ^ [1]
19:     lg={12}
            ^ [2]
```
I couldn't figure out what the problem was.  Then I found some workarounds.  But it was basically just playing around with the JSX that solved it.  But this should be valid.  I included several workarounds in the flow/try link.

**Comment by jamesisaac** [comment]
Looks like this is fixed since v0.89 which refactored the handling React component types: https://medium.com/flow-type/supporting-react-forwardref-and-beyond-f8dd88f35544
