### ISSUE TITLE
Improve error message or fix issue for why subclasses don't typecheck

### ISSUE THREAD

**Issue by omarstreak** [facebook/flow#669]
The following file fails to type check:

```js
/* @flow */
class A {
	constructor(){}
}

class B extends A {
}

class C {
	_member: A;
	constructor(){}
}

class D extends C {
	_member: B;
}
```

The error given is:
```
fail.js:11:11,11: A
This type is incompatible with
fail.js:16:11,11: B
```

Considering there's no difference between B and A it's strange that the error message says they're incompatible.

**Comment by popham** [comment]
I've been rummaging around the source recently, and this smells like something I narrowed down to the `ClassT(l)~>ClassT(u)` flow.  Adding a couple of guards, `ClassT(AnnotT(...))~>ClassT(u)` and `ClassT(l)~>ClassT(AnnotT(...))`, did the trick for me.  This was necessary to get `function (A: Class<K>): void` to accept subclasses of `K`.  I haven't had time to put it in its own branch and test it, although it didn't break any existing tests....  (This may be abusing the data model.)

**Comment by jeffmo** [comment]
We do need to document subtyping and variance better, but here's the reason we don't allow this:

```js
var c = new C();
c._member = new A();

var d = new D();
d._member = new B();

var cInst: C = d;
var aInst: A = cInst._member; // Unsafe!
```

In other words, because instances of `D` are a subtype of instances of `C`, the type of all properties on instances of both `D` and `C` have to be the same type.
