### ISSUE TITLE
Flow unable to handle unions?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6690]
I have run into this in a few places and not too sure what my logic is missing here.  If I have a property that is a union "1 | 2" and a value that is a value of "1 | 2" they are not compatible?

## [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAkAogE6lykDOYAvGAN4A+qYbYA1AOQBGAhgBMAtKTwBHAK54qGLgC4wAJgAsAGlbsOPGHwDGAaxgBLGXgELlABgDM6tkwC+AbnTZ8RMhVKEAyroAWeAC2fAA8HADSCoQReFhUoQCSACLEABok5JRUAHw5dIws7GDAwGAYgWB4WaRgunACBHxUVHC6RnwYZmAIRhXlldVe5bh4Gmz1jdHEMMF4AHYYACqjoZleVKpgETl2mkHSVHwA5ngKABRuZ2AypEbzx1sAdC98pMdUCnzzWADaALoASjo+Vu90eGkcLkwoyIAHE8BhPJQ-IEQgVQjtzhFgbR8utKL4AsEwjsXMVUPV5jIqjVPkQAPI8ABWAFk+DgjGtkdQtoQEUiaqiSfl6AwNLxBCJxFIZPJGOM6g1rio9mwDi0Ttdzrj8lwAILzMD3ABufGMAjAokk0gwPWaVrwujwRhNZi4ewce20ekMJi65gVxUm1ystkVGqOpwuurABqN9y6pHm5pu1TdtSGlDAbV0EnI3QE+fBYCwcHzjptMiebCW-hMN385ZglvmcDt-j4bpzujzBYEWxws2aBFEOEodowcDAPgkOHHpAwTw9Gi9qGc6F0OhaYAAwhIZHAgjzwktorF4ty6XkqgAPLrzAQ0HlBzhXBRLaFsDgh6IABQofBFywFZ8CvLwiTRMIll2OMQy4HInBKMowzAJglGUdAJjgakMFICRdCnUhLlGD9nled56W+P4gVfbDcJuYkQmmGpIJJUIYIKLNqF+K5-nJdgqRpBglUaMAHAKKgmL4JDSjAVD0JURUhLtSMtUk6SnjU04SPwcinjeD5AS-dgqDnapzm0vBjMVHknl0DkMHzPAfAwX0llIPQ8EuetNj3A8p2PGobMVCoTCeFMDgKLh90PIKvC4AS2DCqgniuAorhM5LfPs5UChDJKShAUKcpDfLlUK4oquqsAAD092+Ns7WaKgjGOI0AAMQw68ppw6lLcsaHqeCdPgDwIeYJCCEbamMJNUw6lQet+ABGf5jRoe56iCHBOiMbQCF6fpJum6owDm6oFrDZbFH+J4SvCsr6AKxUareuqGvmJqwBatrOu63qwH60rlWG0bxrAE6ZvOvpLpgIHrrAVb1obLaj12jB9tmHo+n8SGpuhi7PPhxblBuu7FRQVd11QIA)

```javascript
/* @flow */

type $Errors = {|
    +'bad-request': 24,
    +blacklisted: 403,
  |};

type $Error$Schema<+K: $Keys<IDEX$Errors>> = {|
    // the error code associated with the error type
    +code: $ElementType<$Errors, K>,
    +message: (type: string, ...args: any[]) => string,
  |};

type $GetErrorSchema = <K>(K) => $Error$Schema<K>;
    
const errors: $ObjMapi<$Errors, $GetErrorSchema> = {
  'bad-request': {
    code: 24,
    message: () => 'An invalid request was received',
  },
  blacklisted: {
    code: 403,
    message: () => 'An internal server error occurred during your request.  This should not have occurred, please report to Support.',
  },
};

class CustomError<+T: $Keys<$Errors>> extends Error {
  +type: T;

  +code: $PropertyType<$Error$Schema<T>, 'code'>; // 403 | 24

  constructor(type: T, ...args: any[]) {
    const schema: $Error$Schema<T> = errors[type];
    const { code } = schema; // 403 | 24
    const message = schema.message(type, ...args);

    super(message);
    Error.captureStackTrace(this, CustomError);

    this.name = 'CustomError';
    this.type = type;

    this.code = code;
    /*
    this.code = code;
                    ^ Cannot assign `code` to `this.code` because number literal `24` [1] is incompatible with number literal `403` [2].
    this.code = code;
                    ^ Cannot assign `code` to `this.code` because number literal `403` [1] is incompatible with number literal `24` [2].
    */
  }
}

```

Took a second stab at this by doing some fancy tuple mapping as well using a different approach with the same result.

## [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAkAogE6lykDOYAvGAN4A+qYbYA1AOQBGAhgBMAtKTwBHAK54qGLgC4wAJgAsAGlbsOPGHwDGAaxgBLGXgELlABgDM6tkwC+AbnTZ8RMhVKEAyroAWeAC2fAA8HADSCoQReFhUoSTklFQAfKl0jCzsYMDAYBiBYHjJpGC6cAIEfFRUcLpGfBhmYAhGhQVFJV4FuHgabBwVVdHEMMF4AHYYACp9iZ4pqmARqXaaQdJUfADmeAoAFG77YDKkRpM7ywB0t3ykO1QKfJNYANoAugCUdBlnF1cNI4XJg+kQAOJ4DCLUgAYUqeAAYhQgrEsJlQqsDhEfrQMiRxptpnN8AtSlRlqsXMcPAAPDCkPQYACC5D4WAAanwYFIMRzUgdWYysKF+biMhyQTTCJDoaU-IEQhisTjfh5Sr4AsEwlSBmBWNKYfCqjR6IRYdyYKENCR6YzdCy2ZzuVJ1oQZhIcOMALJ8HChIXsxJohJJLxpNYQqFGhHIuCouJrVCpJy5fJWaxgJhKZR61AVSYyYrk6IAeR4ACtfTgjGTw8sZdH5VqQhl6AwNLxBCJxFIZPJGHrhicVOs2JtarsTgdxWAuMzJmALgA3blGARgUSSaQYVo1Td4XR4IzLsxcdYOdbaPSGEzNcyDnLDiw2MdgCfbPaHWfzxcXZqkJM3KnCUp5lN0lBgPUugSOQLQCLBAJgFgcCwQe24yNcbAzP4JinP4qEwBukxwLu-h8KeUG6DBcECMsXp4DUBCiDglC7hgcBgD4nqsaQGDXOeGiXqgzjoLoOi1GAsISDI8YwuEMzRCGdYpOkxT0lMAg0DCj6cMcCgzCCgzPuqXjGtIqZ5GAGZZjm6BsAWZwSA6lBHH0Bk3HcDxPGALzvN8ukOXAha7lQLZ8KMGoKtqoQzG2xbhm8xwfKmQ7BUWH5TpkYWKnw1yZXsbn4J51z3I8XxGewVCeiUBwFXgFV6jC1y6H6GCwXgPgYDeMz2ngRy4RSUkyRxQQwo1eqFCY1xAZsmRcNJsljaUXAuDkU1UNcNL0MclVsBtLUItl4WHVUlnpjYtkqHqoCTYNp0EPQw5rTkr1vTkAB6UkvCRu41FQRg7IuAAGw7AwUnHAwdYNgDwh58DJBCTBIQRw2UxgAcBwMqODbwAIwfEuNAXBUQQ4E0RjaAQbQdMjqMlGAGMlFjGa44oHzXHd03Dpkz16u9AtgF9FqTL9vm1IDIMwxxYBQ-dMNw61iNgHTaOM+0zMwLLrNgPjhN4ST8bkxglPjK07T+CrKNq0zjJa9jyhsxzeooEJImoEAA)

```javascript
type $GetErrorCodeFromKey = <K>(K) => $ElementType<$Errors, K>;
type $ExtractArrayValue = <V>(Array<V>) => V;

 type $ErrorCodes = $Call<
  $ExtractArrayValue,
  $TupleMap<Array<$Keys<$Errors>>, $GetErrorCodeFromKey>,
>; // 403 | 24
```

**Comment by goodmind** [comment]
This is bug with `$ElementType`, `$PropertyType` 
https://github.com/facebook/flow/issues/4211
