### ISSUE TITLE
Intersection and object spreading doesn't work together

### ISSUE THREAD

**Issue by GuillaumeJasmin** [facebook/flow#6691]
I have a simple example, where flow can't work well with intersection and object spreading

[You can try online demo here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5gCGAXGAM4YBOAlgHYDmYAvprgQCFSFMACM6jVpx598YAMLDKAYwnN2XXqmVw2jMHFEArOsQBkYIRcVlyqMNToByKk4A09sc9HvPqsE7Kvlo6ehgUom5gAHSxTHiM3MKGRgDc6GDAwGAIcEwA1vRgUOx42rr6VABqVDAArgRk8YzRVOhZYHhMTHlgABZdeFGwiAx9cHUwACbFE2wzge5ideEs4VNwCWxOGOVhYMo19Y1gzRjRykA)

```js
/* @flow */

type A = { a: string }
type B = { b: string }
type C = { c: string }

const obj: A & B & C = {
  a: 'a',
  b: 'b',
  c: 'c',
}

const {c, ...rest} = obj;

 // works fine
const aValue = rest.a

// error here, flow should found 'b', but it doesn't
const bValue = rest.b
```

Any idea how to solve it ?

**Comment by etnbrd** [comment]
I encountered almost the same problem.
Though, I am quite sure the two are not semantically identical, I worked around this issue using exact objects and the flow spread operator.

``` javascript
/* @flow */

type A = {| a: string |}
type B = {| b: string |}
type C = {| c: string |}

type Obj = {|
  ...A,
  ...B,
  ...C
|}

const obj: Obj = {
  a: 'a',
  b: 'b',
  c: 'c',
}

const {b, ...rest} = obj;

 // works fine
const aValue = rest.a

// works fine as well :)
const cValue = rest.c
```

**Comment by GuillaumeJasmin** [comment]
Great ! Thanks !

It seems work too without exact object, but only spread operator: [demo](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5gCGAXGAM4YBOAlgHYDmYAvprgQCFSFMACM6jVpx598YAMLDKAYwnN2XXrIIARJajBgAdCcIAaA8ZMCLhk0fkXuAbnTK4bRmDiiAVnT0ycktaMAByKjDbMTow0SjLVXDlBK13TwwKUTMrIyY8Rm5hH19XA2BgMAQ4JgBrejAodjxUdK8qADUqGABXAjJ8xiMqdAqwPCYmGrAACwm8HNhEBhm4HpgAE0a1ti2wlJzRHsyWTI24ArYwjFaPL2Uu3v6wQYwjZSA)

**Comment by etnbrd** [comment]
Yes, true, but then the type for `rest` is `{a?: mixed, c?: mixed}` which is basically any object :man_shrugging: :stuck_out_tongue:

**Comment by GuillaumeJasmin** [comment]
nope, if I write:
```js
const aValue = rest.c()
```
I get an error because `c` is a string.

And if I write:
```js
const cValue = rest.d
```
I get an error too because `d` is undefined. So `rest` seems to be good, and show correct errors

However, exact object can prevent one more thing:
```js
const obj: D = {
  a: 'a',
  b: 'b',
  c: 'c',
  e: 'e'
}
```
because `e` is not defined in the type `D`, so you will get an error if you use exact object :)

**Comment by etnbrd** [comment]
Ah, yes I didn't got this difference, thanks :)
