### ISSUE TITLE
Add documentation for $Shape on flow.org

### ISSUE THREAD

**Issue by rickyp-uber** [facebook/flow#6692]
To save others time please update your documentation to match current feature sets. Locating the $Shape utility is currently very difficult

**Comment by vicapow** [comment]
looks like it was documented in the past? https://github.com/facebook/flow/pull/5251/files

It may be that this is deprecated but this is unclear.

**Comment by vicapow** [comment]
here you go https://github.com/facebook/flow/pull/6694
