### ISSUE TITLE
Can't type a mixin function using $Subtype and generics

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#6695]
The `$Subtype` utility function is puzzling to me. Is there any documentation on how to use it well? I'm trying to use `$Subtype` to type a mixin function. I believe my type signature is correct. I keep getting these errors:

```
const MyMixin: MixinFunction = superclass => class extends superclass {};
                                                ^ Cannot extend `superclass` [1] with `<<anonymous class>>` because `A` [2] is not inheritable.
```

Here is my super simple code:

```
type MixinFunction = <A>(superclass: Class<A>) => Class<$Subtype<A>>;

const MyMixin: MixinFunction = superclass => class extends superclass {};
```
[Code on Try Flow.](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAlgB7EB2AYgK4UDGGxcFYAvGADwCCAfABQBnGvgBO9GAENBggFxgAwlJk9eASna9FywZwAkAZRoAjbPlW8A3KnotBGIlhLkK855VoMmLdmGFiJaUFNMECZMDxSDDwKABNg-zxxHTAAbwBfSyA)

I'd really appreciate any feedback on this. Thank you.

**Comment by TrySound** [comment]
Subtype is deprecated utility type
