### ISSUE TITLE
$Call do not extract function argument

### ISSUE THREAD

**Issue by dfroger** [facebook/flow#6696]
Using `flow 0.78`, I fail to use `$Call` to extract the type of a function argument.

For instance:

    type Func = number => string

    type R = $Call<<A, R>(A => R) => R, Func>  // Ok, string
    type A = $Call<<A, R>(A => R) => A, Func>  // Bug, empty

R is the type `string`: flow has successfully extracted the **R**eturned type in `Func`. But A is `empty`, where I would expect `number`, ie the type of the first **A**rgument in `Func`.

Why is `A` `empty` instead of` number`?

Here is a [flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiArgHYDGYAvGKcQLYBGeATtQHxgDOGLAlqQDm6bPjAAlamAAkAYQCGMGAB5lAQQA0E9gAo1HCQEoD4rSQrtMuAvppzFK9VvG7bnccaqdNRMuUtgYKjkcKQ8YPIAXGC2YLzEeADcgcDAYABCxILR5pRQfCzh8iyCDHikGGB8XBG0DMwsWozElYJwlQDkePQ42B1x1sGh4SzRkjTxSSlpAKIsLHBsUHBkACY5fmAseBjELKR4qwNi1bU8-EJAA)

**Edit**

Seeems duplicate of #6647

**Comment by philippotto** [comment]
Possibly related to https://github.com/facebook/flow/issues/6647.

**Comment by jamesisaac** [comment]
Closing as duplicate of #6647
