### ISSUE TITLE
How to combine flow with react-navigation greatly

### ISSUE THREAD

**Issue by JNUfeatherwit** [facebook/flow#6697]
In a React Project,I want to use React-navigation and flow at the same time.But react-navigation put some important method into this.props,and this will reports errors. 
like this:
Error:(14, 37) Cannot get `this.props.navigation` because property `navigation` is missing in object type [1].

**Comment by jamesisaac** [comment]
Use [flow-typed](https://github.com/flow-typed/flow-typed) to install the libdef for `react-navigation`.

You can find example usages in the flow-typed repo: https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/react-navigation_v3.x.x/test_react-navigation.js
