### ISSUE TITLE
Downcast error

### ISSUE THREAD

**Issue by xhubbsaxo** [facebook/flow#6698]
If this is a bug, please try reproducing using https://flow.org/try/.

```
/* @flow */

type RowInfo = {isDivider: boolean, isCustom?: boolean};

type RenderedRowInfo = RowInfo & {
    isCustom: boolean, //now required
}

// boolean or null to boolean
const b:boolean = true;
const a?:boolean = b; //no error

// not working with object props
const e:RenderedRowInfo = {isDivider: true, isCustom: true};
const f:RowInfo = e; //error!!!
```
It looks like casting from b:boolean to ?b:boolean works fine for simple values, but its not working fine for object props. In general object with required type for prop can not be casted to object with maybe ? prop.

**Comment by xhubbsaxo** [comment]
The same happens when 

```
type RenderedRowInfo = {
    isDivider: boolean, 
    isCustom: boolean,
}
```

**Comment by M-TGH** [comment]
This is because in Javascript [objects are passed as references](https://codeburst.io/explaining-value-vs-reference-in-javascript-647a975e12a0).

So if you have this continuation on your code snippet above:
```js
// not working with object props
const e:RenderedRowInfo = {isDivider: true, isCustom: true};
const f:RowInfo = e; //flow-error!!!

f.isDivider: false;
delete f.isCustom;

console.log(e); // {isDivider: false}
```
This can be fixed by creating a new object instead of using passing through the reference, e.g:
```js
const e:RenderedRowInfo = {isDivider: true, isCustom: true};
const f:RowInfo = {...e};
// or (does the same):
const c:RenderedRowInfo = {isDivider: true, isCustom: true};
const d:RowInfo = {isDivider: c.isDivider, isCustom: c.isCustom};
```
You might also be interested in the [`$ReadOnly`](https://flow.org/en/docs/types/utilities/#toc-readonly) utility type.

**Comment by jcready** [comment]
@M-TGH I don't believe that's the reason since this produces no errors:

```js
type OriginalRowInfo = {| +isDivider: boolean, +isCustom?: boolean |};

type RenderedRowInfo = $ReadOnly<{| ...OriginalRowInfo, +isCustom: boolean |}>

// boolean or null to boolean
const b:boolean = true;
const a:boolean = b; //no error

const e:RenderedRowInfo = {isDivider: true, isCustom: true};
const f:OriginalRowInfo = e; //no error

// I would still expect this to cause a flow error, but it does not
delete f.isCustom; //no error
```

**Comment by M-TGH** [comment]
Seems like an unrelated bug where you're allowed to call delete on readOnly properties. In this case it does indeed fix most of it by making the properties readOnly as flow assumes the reference won't be changed.

**Comment by xhubbsaxo** [comment]
Can be solved like in: https://github.com/facebook/flow/issues/7476
