### ISSUE TITLE
package.json.flow file ignored

### ISSUE THREAD

**Issue by texastoland** [facebook/flow#6700]
#### `lib/cli.js`

```ts
// @flow strict
import {version} from "../package.json"
```

#### `package.json.flow`

```ts
// @flow strict
declare module.exports: {version: string}
```

#### Actual

``Importing from an untyped module makes it `any` and is not safe!``

#### Expected

I naively assumed JSON is always typed.

#### Question

is there a better channel for these kind of questions preferably Slack?

**Comment by M-TGH** [comment]
Neat idea, unfortunately the extension is explicitly `.js.flow` however this seems to work correctly:

**lib/cli.js**
```js
// @flow strict
import {version} from "../package"; // Notice, no longer specifically .json
```
**package.js.flow**
```js
// @flow strict
declare module.exports: {version: string}
```

It also does work when requiring it, but I understand why you might prefer using ES6 imports to keep a more consistent code style.

Seems like it's been tossed around, but still doesn't work for ES6 imports; #4596

Far as the slack question, not that I know of, there's an IRC channel on Freenode (see [readme](https://github.com/facebook/flow#join-the-flow-community)). However I just quickly checked that out and it doesn't look too lively.

**Comment by texastoland** [comment]
🙏🏽 thanks thank you resolves my issue.
