### ISSUE TITLE
Object rest operator with indexer throws error when indexing

### ISSUE THREAD

**Issue by AlmeroSteyn** [facebook/flow#6701]
I am not sure if this is a bug or just me not being able to find the correct info.

In a React component I have a prop getter function. I do not want to type every possible prop that can go on an input and I am trying to index some props to check if they exist:

```js
class N {
    getInputProps = ({ onChange, ...props }: any = {}): {
        [name: string]: any
    } => {
        // ....
        return {
            'aria-disabled': props['disabled'] ? 'true' : null,
             ...props
        };
    };
}
```

If I use anything but `any` to type the incoming parameter Flow throws and says that `disabled` does not exist on the object. I tried to type it as an indexer like:

```js
getInputProps = ({ onChange, ...props }: {[name:string}: any} = {})
```

Any help would be appreciated if this isn't an issue.

**Comment by goodmind** [comment]
Simpler reproduction:
```
//@flow

function a({ foo, ...props }: { [name: string]: string } = {}) {
  props.bar;
  foo;
};
```

**Comment by SamChou19815** [comment]
no longer errors
