### ISSUE TITLE
Adding statics to wrapped component

### ISSUE THREAD

**Issue by svenlombaert** [facebook/flow#6703]
Hi,

I have a hard time type hinting static methods I add to a component wrapped with a HOC.
I add the static methods to the wrapped component, because this HOC doesn't copy over the static methods from the component it receives.

```typescript
/* @flow */
import React, { Component } from 'react';
import type { ComponentType } from 'react';

/***** Price Component *****/

const Price = (props: *) => {
	return <input name="price" />
}

/***** OrderBook Component ******/
type OrderBookProps = {
  foo: 'bar',
}

class Orderbook extends Component<OrderBookProps>{
    render() {
      <p>Orderbook</p>
    }
}


/***** Generic HOC that injects styles prop ******/
type StylesCreator = (props: Object) => Object;

type HOCProps = {
  styles: StylesCreator | void,
};

const withContextualStyles = (styles: StylesCreator) => {
  return <PassedProps: {}>(WrappedComponent: ComponentType<PassedProps>): ComponentType<$Diff<PassedProps, HOCProps>> => {
    const WithContextualStyles = props => {
      return <WrappedComponent {...props} styles={styles(props)} />;
    };

    return WithContextualStyles;
  };
};
      

const WrappedOrderbook = withContextualStyles(() => ({}))(Orderbook);
WrappedOrderbook.Price = Price;
      
export default WrappedOrderbook;
```

Flow playground link here:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYAwnDnAHantEC+YUeVmADkeCtWEBuDG0JgCAT2ykGzVrk7cAKkpV8BQ0eIJTUqUCEvgACnnSUVLNpqJXLaVJQ4BnIrfsqALxgABTYgtjeAFzIAJRggQB8DKgAkGIEAK547GAAPOjs2JlE7OSYpIEAROEBVWDAiag8ZhZWYADyeAAmpHgAQnBwANZqzlyubiioisqdPX2DI7ZwkQkpYPxDMcIARuR4wjTNZpQw5N7e8714u0OjpAAeBFzdV04aE3ldN0vDK5FEvQ0mJ2DcQvFgZtoflsIkfn07iM8sA4agYS0Wq0pmAAOJcPr2MAACQ6THkAAtyERCgArUjUK6+BQwUhXcKrZBTNCzFQAZUUrO8TDE1Pw6zCEWinV29Oo8SSMrlBGkM10JLJAKuwShYGZQpiApZbJFFAI4oAPmAAG5wdDdY48VVedi+MAIdAECksbhPLLkGBGoUS-Vsw2Ck2i814BXJXUZbK5PLWC7eUjdLUxeg8RIhADqeHI2GU3Q+HAmMTLLh0ymTqfTWsSsUr6nL2l0eQAJAARdBQKB1y4NqV0UlMRvJRW6zYut15z3ejgvZ6ZANBtnrDlrKfomFgBM5fIFoslqsTBgAOivW+8fFD3kC9HvktW3lifEa0gxqphB9y869H1l39QMI28L8wCdZoIJhU4fCIY9i3TBFbnudYPUApc-VXUDjW8EIIQSZIQmzWJYhCFCkWGWJpEQktKPuC9-AcdZmNIGDoVQJ5cDkXooHITIYAQwskO6BiRkkIA

**Comment by kubilaykiymaci** [comment]
I have the same problem, i have temporarily written "//$FlowFixMe", but the code readability is reduced. Because it needs to write anywhere it is used.

**Comment by SamChou19815** [comment]
Function statics are now only supported in very limited ways.
