### ISSUE TITLE
Spreading into an object allows a value of undefined for subsequent properties

### ISSUE THREAD

**Issue by edzobel491** [facebook/flow#6715]
### Problem:
Spreading an object before other properties, allows _undefined_ for subsequent properties.

### Example:

[Try link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAKrgQLxgDeAPmAIYByArgLYBGeATgFxgA7dl24AaRgGUM3AJYCA5vwDO0ufLC0AvgG5UAYzgCVYOQDcGMGQBMA8hwBW-YmXxgq1AHRfqjVpx78AExgmuIMUrIK-CwCVnhQcnhWIdpgwMByBtzceHoYMFhgOAxKSnhKYNiuegAWuQDWavqGxgwCcBh1fESk5G40kqpRYDFxCQJJ4l4ePszCAWDBmjpgq2nAWTl5BWDyeBPcDBjljAJgPNxw3Gs3t0A)

```flow
type MyType = {| aNumber: number, aString: string |};
const invalidObj: MyType = {...{ aNumber: 2 }, aString: undefined }; //incorrectly passes type checking
const another: MyType = {...{ aNumber: 2 }, aString: 2 };            //correctly generates an error
const oneMore: MyType = { aString: undefined, ...{ aNumber: 2 }};    //correctly generates an error 
```

It seems like the place where you spread an object is affecting Flow's ability to type check subsequent properties.

**Comment by nmote** [comment]
This has the expected behavior in master
