### ISSUE TITLE
Flow type checker is running very slow

### ISSUE THREAD

**Issue by peeyush-ad2games** [facebook/flow#6716]
Recently found that flow type checker is running very slow for my machine when running relatively fast on other machines. 

On other machines, it runs slow for the first time and then runs pretty fast, seems like flow caches the file's data and just run type check with the difference in files may be. We have already enabled skipping the `node_modules` folder but that didn't help either.

OS:- OSX
Flow Version:- 0.78

It seems like some dependency issue that is installed on my system(I tried removing and reinstalling node_modules) didn't help, is there a way to check what step is consuming most of the time?

Could be related to:- https://github.com/facebook/flow/issues/5858

**Comment by SamChou19815** [comment]
Not enough info to repro.
