### ISSUE TITLE
Don't throw any exceptions when react state is not suitable by type

### ISSUE THREAD

**Issue by inyellowbus** [facebook/flow#6718]
Hello, look at the code below

```
// @flow
import * as React from 'react';

export default class Auth extends React.Component<{
  // smth props here
}, {
  keyword: string,
}> {
  state = {
    keyword: '',
  };

  render() {
    const {
      keyword,
    } = this.state;
    return (
       <input value={keyword} onChange={(e) => {
         this.setState(() => ({
           keyword: 123,
         }))
      }} />
    );
  }
}
```

It's just an example, i did it like writed here https://flow.org/en/docs/react/components/#toc-adding-state. So, i think that this should throw exeption in console when we set not string to keyword, but it isn't. And if we set default state not like a string

```
state = {
  keyword: 123,
};
```
it will not throw too.

With props this works fine. Should it works with state like works with a props? Or maybe it is correctly? How can i get exception in console if i set incorrect state?

**Comment by SamChou19815** [comment]
This now errors
