### ISSUE TITLE
Uninitialized variable false positive with catch+if+break

### ISSUE THREAD

**Issue by cakoose** [facebook/flow#6725]
```js
declare function f(): {n: number};
declare function p(): boolean;

function g() {
  while (p()) {
    let x;
    try {
      x = f();
    } catch (err) {
      if (err.x) {
        throw err;  // L1
      } else {
        break;      // L2
      }
    }
    console.log(x.n);  // False positive: 'x' is possibly uninitialized
  }
}
```

Some minor variants:
- If L2 is changed to `continue`, same issue.
- If L2 is changed to `return` or `throw`, the false positive goes away.
- If L1 and L2 are both set to `break`, the false positive goes away.
- If L1 and L2 are both set to `continue`, the false positive goes away.

**Comment by goodmind** [comment]
https://github.com/facebook/flow/pull/7658 should fix this

**Comment by SamChou19815** [comment]
This is now fixed.
