### ISSUE TITLE
Bug: Aliasing $ReadOnlyArray changes its behavior

### ISSUE THREAD

**Issue by Zaggen** [facebook/flow#6730]
When using `$ReadOnlyArray` to avoid having to specify extra data that a function you are calling does not care (to treat data as superTypes) works as expected but if I alias it like this `type List<T> = $ReadOnlyArray<T>` it stops giving this behavior which unless I'm missing something is a bug :(.

[Here is the Try Flow](https://flow.org/try/#0C4TwDgpgBAMglgZ2AHgCoD4oF4oBIBKEAhgCYDyAdgDYgCCATvUSGugFBuiRQBicVAWwTZYiFAG82UKHBIAuKBQCuAgEYR6AGimKiAiAqT04FAObbpIYvUPBjZi1FMQK9A6KTIjJ0+kdNgHwVlNQ1tAF92NgAzJQoAY0CAewooMCJ6BAg+QQQACmj+IQUcoQBKKElpeJSkKHUkUuEcZ2AACThTAAsIJHwiCgBrCBImgqKEMp03YCV6VKrpet7gJsdpQtzHcLYdznBoJtQk-qGReE9F2WCVdS1pokCzG9D7yI5YhOTU1o7uldOw1GE3GuRKE2OgLKCgYTBYITumEWMzmqU2Qh00gAdAgqHB4hA8lMllAcUl6MA8nkiJp6hUsJhqViAj4oJhVMzHqyAPxQAC0AEYoAoBWViUssQIiGBQQJsJh0VjZFNwkA)

And here the example code for direct reference:

```
type List<T> = $ReadOnlyArray<T>

type Films = List<{
  id: number,
  name: string,
  year: string,
  genre: List<string>,
  rating: number,
}>

function parseFilms(films: Films) {
  const bestFilms = getHighestRankedFilms(films) // Error here with List but not with $ReadOnlyArray
  return {
    bestFilms,
    films,
  }
}

type FilmsToRank = List<{
  id: number,
  rating: number,
}>

function getHighestRankedFilms(films: FilmsToRank): Array<number> {
  return films
    .slice()
    .sort((a, b) => (a.rating > b.rating ? -1 : 1))
    .map(film => film.id)
}
```

I hope it makes sense, if you need me to do something extra let me know :)

**Comment by jcready** [comment]
Make the generic parameter covariant to fix your problem:

```ts
type List<+T> = $ReadOnlyArray<T>
```

**Comment by Zaggen** [comment]
@jcready awesome, it does the trick
