### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/flow#6732]
![image](https://user-images.githubusercontent.com/4404683/44008118-141e0236-9e76-11e8-9c55-921dda6138af.png)

The test can be found [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQwBUoCmBnaBLAdgC4C0AJjpgIYBG06oesRATuiegMbQUugrCLIwOALYAHWEwKgCAT1F0A3gDE8AX1CQmsYaABEAOmCz5mXQG4BxuioA8AQSYBzTAC5QAEgBK6CiQDyeNAyDkwUMjYUeDIAfAA0oN6YAK7QBNGgALygABT6edzObg7OAJSZ6YkpBBaCoKIsBAQ46ExEOI4MLIhWoAAK3E0U0JmIoKAAZDn28QBC8Z7R2ZButgDadrMAuvNxoBRFZRnpazPbCdEloxNTG6Bz50sreDbrWzvx+6C3VG4zhxWXMaTbLTO7xADCO0eoDWt3u4LOCw+B3KMOeq3hiIuV2BoPhUOWaJecIhWORX3iPzu-yJqwRO0B1xBJNAkIehNhs1J7z2RUpv3i7Dc4JpnkZuJZbIAIgSnsSuaz4lKybyvjSThClVjxTcFdLZbTJVqeZ9vr91ejpdqcbqwYrQDL2XLXnarSa+aAqfchayLS9lQybcy9UqDZzXcbzuSzXafWySG4paKdcGIw74gBRMPoo3p0AZlWmv0YzV5guBoG2-Fl7PytOO8tR1Uxv6otb6-PWyup6sN2su3uZwser2C4XFhtdpl40t9p2GkNl4cUz0C0Bx+IJh3FxsLFMz+1zhbQ8ODzvulej9fCzeJ+LoNwZ5M1diwPCYKSiAY4IZufqSH9hiyJY8HiPJ9EwbR0GKTAaUgPB9CofASGyJI8DYSB8FYMC8kg4RoKcWCanQAAPcRJFADCKCqOpvyGCwgA), but you are not gonna be able to get any feedback, as it's also causing the browser to crash.

**Comment by mroch** [comment]
this seems to be working now! I didn't try to bisect to the specific version too much, because every time I tried an old version it crashed the browser tab 🙃
