### ISSUE TITLE
"Refining Maybe types" do not work when assign function return value

### ISSUE THREAD

**Issue by mjyut** [facebook/flow#6736]
["Refining Maybe types"](https://flow.org/en/docs/types/maybe/#toc-refining-maybe-types) do not work when assign function return value to property of the property.

Code:

```javascript
// @flow

class C {
	s: ?{str: string}
	m() {
		if (this.s != null) {
			this.s.str = "abc"   // it is OK
			this.s.str = abc()   // it is Error
		}
	}
}

function abc() :string {
	return "abc"
}
```

Flow error:

```
8: 			this.s.str = abc()   // it is Error
             ^ Cannot assign `abc()` to `this.s.str` because property `str` is missing in null or undefined [1].
    References:
    4: 	s: ?{str: string}
           ^ [1]
```

[Online Flow-try.](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToDCoBvRASEwC5QB+AzAFwCcK76BLAOwHMBfEgWwAoAlIRLEWkUP1oALFpgB0OAIQBeUGwCu0aMKLF9MuYsUNQagEToARinOh7IUC1pOcAeQDSo4oYV-TatYoQvagjs6uoACi9PSw9KI8xDw8iJAabCi0LLBsoEEhZMzsHCLE9ACmtBr0eZY25ohcQA)

Thanks for reading. 😄

**Comment by 0rvar** [comment]
You can often use intermediate variables to get around refinement limitations:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDG0CGBnToDCoBvRASEwC5QB+A0TAFwCcL6GBLAOwHNQBfEgWwAUASkKJQEySljt6tUAF5QdABatMAOkwlirSKEE4AhEvYBXaNFFFJtyaS2NFoAEToARihc6HLZx5QRSRBQVjpQnABRBgZYBh0+Yj4+REgzdhQ6VhlQAJFmRg5uImIGAFM6MwZ2VwDvHiA

**Comment by wchargin** [comment]
[Any function call invalidates refinements.][1]

[1]: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

This is because the call to `abc` could have plausibly reassigned
`this.s` to be `null`. Of course, the current implementation of `abc`
does no such thing, but Flow cannot discern this just from the type.

If you search for “function call invalidates refinements” on this issue
tracker, you’ll find lots of similar issues. The fix offered by @0rvar
is good and correct.

**Comment by mjyut** [comment]
> This is because the call to `abc` could have plausibly reassigned
this.s to be null.

I understood what was happening. Thank you very much.

---

memo:
Flow is very clever. But I think that "Refinement Invalidations" is unnecessary in above situation.
Even if `abc()` rewrites `this.s` as a side effect, it still run without run-time error.
Because assignment expression are evaluated from the left side.

```javascript
// @flow
class C {
	/*::
	s: ?{str: string}
	*/
	m() {
		if (this.s != null) {
			// it is error in Flow
			// however, there is no error when running as JavaScript
			// even if there is a side effect of changing `this.s` in `abc()`
			this.s.str = abc()
		}
	}
}

function abc() /*:string*/ {
	// side effect !!
	c.s = null
	return "abc"
}

let c = new C()
c.s = {str: "a string"}
c.m()
console.log( c )   //=> C { s: null }
```

**Comment by wchargin** [comment]
> it still run without run-time error. Because assignment expression are
> evaluated from the left side.

That’s a good point. You’re right: the invalidation should only apply to
expressions/statements that are evaluated/executed after the function
call. Here is a more minimal example that demonstrates the soundness:

```js
// @flow
function foo(x: {box: ?{field: string}}): string {
  x.box = null;
  return "nulled";
}
const o: {box: ?{field: string}} = {box: {field: "hello"}};
if (o.box != null) {
  // Flow flags an error, but this is actually totally sound, because
  // `o.box` is evaluate before `foo` is invoked.
  o.box.field = foo(o);
}
```
