### ISSUE TITLE
Dynamic imports in generator don't work

### ISSUE THREAD

**Issue by leoselig** [facebook/flow#6739]
I have this code (to lazy-load a module in my [`redux-saga`](http://redux-saga.js.org/)):

```javascript
function myGenerator() {
  const { lookup: lookupMIMEType } = yield call(() => import("mime-types"));
}
```

### Problem

See here: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5twBzAU2wAoBKMAb1TDFxIGd9GwAHAQwBO7CmAC+YALxgAnoQowAJqz4wY1OpIB8YQgFsecAfmoAiTAJgnatANzoWAivnPZeg4XdFA

The flow try tool seems to crash silently. On my CLI I get the following error:

```
$ flow --max-warnings 0
Launching Flow server for /Users/leoselig/nexenio/web
Spawned flow server (pid=50359)
Logs will go to /private/tmp/flow/zSUserszSleoseligzSnexeniozSweb.log
Monitor logs will go to /private/tmp/flow/zSUserszSleoseligzSnexeniozSweb.monitor_log
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ packages/app-files/src/js/routing/index.js:0:1

Internal error: uncaught exception:
Context.Require_not_found("\"/Users/some/path/to/file.js\":
(90, 63) to (90, 75)")
Raised at file "map.ml", line 130, characters 10-25
Called from file
"hack/utils/collections/myMap.ml", line 15, characters 13-23




Found 1 error
```

### Expected

Get the same result as with the workaround [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5twBzAU2wAoBKMAb1TDFxIGd8x4BDAEwCycPphgUwAXjB1JAPjCEAtgAc4AJ3zUARJjUwttANzNWHLgzDKea9uIC+ksAE9CFGH1Y8YMar0HDRCiN0FjUKfF1sS2tbYzsgA)

**Comment by SamChou19815** [comment]
It no longer crashes
