### ISSUE TITLE
$ObjMap does not work with higher order functions

### ISSUE THREAD

**Issue by 0rvar** [facebook/flow#6746]
When defining a type using $ObjMap and a higher order function as second type argument, flow stops type checking the result:
```jsx
type MakeThunk = <V>(V) => (() => V)
type ThunkedObject<R: {}> = $ObjMap<R, MakeThunk>

type A = {| foo: string, bar: number |}
const thunked: ThunkedObject<A> = {
   foo: () => 2, // This should be error, incorrect return type
   bar: () => '3', // This should be error, incorrect return type
}
```
[Flow Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPogJCSywBcoAzigE4CWAdgOYA0lARgENm9dgFcAtnyzNEpAL7JUmHAFkBAaywAVABaj26wqAA8ANQB8AClMBKQudCXLdgg9tLsoXfs0ATAPJ8AFZYAMYoxgBK9MRyDkQAJIFBahhR3KBqmt4G5sihsOxMoCh6Bli+9Dl+yWERuPEkiKAt1HSOLg4ATBkgXjqsDIw6sKLQvqBSoNLMsMwZHAXMzHWgKyiizOwlys0tgsId9qAA5ADMJ71guoPDo+OTODNzC+xLK+FrWBtbO9iICkQfQAygJ2Kx0KBQjowoYALSgXywLBDZKpUDwOaGAQoUACaDQAD8HhwAEkJkQzFZbMdTCTQOTauEojE4kYksFUukGb48gUirjWAFgvRGcE6sYGkZiHtQG16D1QH0bkNbu86tA0HLoAJOJwKnihgI-k9lnNZQd6OdLkrrgNVUN1eFNdrdfqJgIjSbpmaZAogA)

This looks like a bug (or undocumented limitation) to me.

**Comment by goodmind** [comment]
It works, just the other way around, this is actually documented limitation

>This is extremely useful for expressing the return type of functions that manipulate objects values.

Only return types, not input types

```js
// @flow

type A = {|
	foo: string,
	bar: number
|}


type ThunkedObject<R: {}> = $ObjMap<R, <V>(V) => () => V>

declare var thunked: ThunkedObject<A>
    
const value1 = thunked.foo()
const value2 = thunked.bar()
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPogJCSywBcoAzigE4CWAdgOYA0lARgENm9dgFcAtnyzNEpAL7JUmHABUAFqPYBrLABMA8nwBWWAMYoAPACV6xOQD5CoACSGjAWQEZr3UBYBq9gAU-gCUhI5B4QSOgci6ZtBCOABuQqAoGtp69OqaOgbGZpa49oigFaDllaaw7EygadCiWACMTpn5egB01LBR1RW19SiNAs1YAEwdWQXdgswDQA
