### ISSUE TITLE
Add a constraint for exact types

### ISSUE THREAD

**Issue by jcready** [facebook/flow#6747]
I have a generic function that by design requires that its parameters may only take exact arguments, i wish i could get such guarantee from flow by declaring my function as follows:

```js
declare class Object {
  static entries<exact T>(object: T): Array<[$Keys<T>, $Values<T>]>;
  static entries(object: any): Array<[string, mixed]>;
  static keys<exact T>(o: T): Array<$Keys<T>>;
  static keys(o: any): Array<string>;
  static values<exact T>(object: T): Array<$Values<T>>;
  static values(object: any): Array<mixed>;
}
```

**Comment by goodmind** [comment]
I think this is flawed idea, because exact object is more like labeled tuple, so you can't really have supertype of all exacts

Related #7773

**Comment by jcready** [comment]
What is the proposed alternative solution to properly typing `Object.values()` and `Object.entries()` so they don't result in `mixed`?

**Comment by goodmind** [comment]
OCaml :\

**Comment by Bannerets** [comment]
Currently the constraint exists, you can use `$Exact` for this:

![image](https://user-images.githubusercontent.com/10106819/61994823-50d9c280-b088-11e9-855c-8473b10f63f1.png)


```js
declare function keys<O: $Exact<any>>(o: O): Array<$Keys<O>>;
declare function keys(o: mixed): Array<string>;

declare var o1: {a:1, ...}
declare var o2: {|a:1|}
const ex1 = keys({a:1})
const ex2 = keys(o2)
const inex1 = keys(o1)

const t11: 'a' = ex1[0] // ok
const t12: 'a' = ex2[0] // ok
const t13: 'a' = inex1[0] // error
```

[try flow](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwGsQBPAZwB4B5ALngBIBRADyk3KlWID4uAKHWpQCUtAIIwYUYuToBpEhUo8A3AChQkWAhTpseQgv60AtliYhgI+OMnTSGGFlQBzLmvXhoceADdY8HABGWgBvKGpAgBp4ADo4gF8PTW8-GACAJlCAH3DArMSwPHt4ECZA+ABeAzJeMIj4oVVC1GLS9Mrq0n50xubip1LyqqIaoMamoox4DEDg+AByKHmOwYBtAAYAXXgAeh2AggmWqZnMhaWVpnSN7b2Do+KZgGZaReWqgbKb3f2QCRwYKogA)
