### ISSUE TITLE
Is it possible to refine a regular 'string' type to a union of string literals?

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#6748]
Take this object with enum-typed keys:

```jsx
type MyPropName = 'foo' | 'bar'

const myObject: {[MyPropName]: number} = {
  foo: 123,
  bar: 456,
}
```

I want to be able to create a function that takes *any* string (from user input at runtime) and looks this up in the object, falling back to a default value if it's not there:

```jsx
const defaultValue = 999

const getValue = (propName: string) => {
  return myObject[propName] || defaultValue // ERROR
}
```

But this causes a Flow error:

```
Either string [1] is incompatible with string literal `foo` [2]. Or string [1] is incompatible with string literal `bar` [3].
```

I could change the `getValue` function to take `propName: MyPropName`instead of a `propName: string`, but that would be wrong, because the function is going to be called with user input which could be any string.

I don't see why it should be an error to just attempt to read an object key that might not exist. As long as the resulting value is marked as being possibly void, then I don't see the problem.

I have tried refining the type, but none of these work:

```jsx
// Using hasOwnProperty
const getValue2 = (propName: string) => {
  if (myObject.hasOwnProperty(propName)) {
    return myObject[propName] // ERROR
  }
  
  return defaultValue
}

// Using "in" operator
const getValue3 = (propName: string) => {
  if (propName in myObject) {
    return myObject[propName] // ERROR
  }
  
  return defaultValue
}

// Using Object.keys()
const getValue5 = (propName: string) => {
  if (Object.keys(myObject).includes(propName)) {
    return myObject[propName] // ERROR
  }
  
  return defaultValue
}
```

I also tried a `switch` statement, and this works:

```jsx
const getValue6 = (propName: string) => {
  switch (propName) {
    case 'foo':
    case 'bar':
      return myObject[propName]; // NO ERROR
    default:
      return defaultValue;
  }
}
```

I guess a complex `if` statement would work too. But that's not a reasonable solution if the `MyPropName` enum type has a lot more possible key names in it.

[Above examples on TryFlow](https://flow.org/try/#0C4TwDgpgBAsiAKAnA9mAcgQwLbQLxQHIAzZZAqAH0ICMNECAoBgY2QDsBnYKLEAeWoArCM2AAuKAG8A2nCSpMOALoS2AVyzUIiAL5R8khlCglkEgIwAmAMwAaI1FqIJAFgCsANns6mrTtwATCCIMNQAbYAA1DDC1PCgATiTfdi4oAHMIKJi4-SgACjAUdGwICS5EAEs2dIBKfQA+KQdELLVENh5+IRFgaSKFUqVKKiCQ8OzY6AB6aagAUQAlRb5Fhh8mWahoquQ1DigMYGAILDBgA+BkKFaiaugBkpwxTbmAVQ5q9KgACwwOPgAdzY8kgiFALFS3EykziljyhWKijKUAqX3quCahmMlSIBV4AmEogAdH8AcDQdpQIjBjhavVscYbm0Ol1Cb1+kihlAtksVmtjD5jC0WZ0xqEItEputXlAPl8oAAiaqKqCobRHZCISH+DJZKVxawIx7I8rAKo1DFYhy4gom0pQapsnqiBkOYytYDtToEl19e3KHlzPmrBxCqAir2s8UTA0QGUMLbympQdkkgDWEBAHHytR1aRhcbcxq5z1R5vRjWaOLx+TTwGJmez+V9ROAtWJ1WYsSCOYDEHp1aZnu9zrbnNpEGGvOWocFDkjo5jkpy8Y2ifenxTHEBlWAzB++eh+tXHhLk7NFrqVcZO73B7tpYHQ+MzH+0GIpAILyZUDfHA-Jxv3dYdRTHDl+yUABuEDl3EECPTAuC4xg+cfCAA)

**Comment by lll000111** [comment]
[I fixed it for you.](https://flow.org/try/#0C4TwDgpgBAsiAKAnA9mAcgQwLbQLxQHIAzZZAqAH0ICMNFyqBnYRASwDsBzAKG4GNk7ZlCwgA8tQBWEPsABcUAN4BtOElSYcAXQXsArlmoREAXyj5F3KFBLIFARgBMAZgA0VqLUQKALAFYANncTXgEhYCgAEwgiDD0AG2AANQx4vTwoAE5s0MFhTghk1PTzKAAKMBR0bAgFZjYuAEpzAD4lD0RCvUR2EXEpGWBlSo0arUoqaNiEorToAHp5qABRACVVsVXuEN5FqBS2ZD1GKAxgYAgsMGAT4GQoTqIOaBHqnDldpYBVRg5OKAAFhhGGIAO7sdSQRCgfh5CIFWbpRylCpVTS1KD1P7NXBtSzWVhEcqiCTSWQAOiBIPBkOMoFRoxwjWa+OsDy6PT6pMGwzRYygezWGy21hC1g6HN6UziiRSc22nygPz+UAARBxVVBUMYzshELDwlAEXL0s4Ua90XUWNjWu0CUSGW9oBwuQNZCyPNZOsBur0SW6hhb+YL1psPGKoBKfZzpTMTRAFdw9squFBuRSANYQECMMqNA35QrxvzmvnvTHWpq21mE8rp4DkrM5sr+snARrkjh8NLRXNBpketns6N+-pt3mMiDjEPC8MeKO+qIxGWIhM7JPfX6pxig1jAPgAgvwovFCABUuTq0NTg4vEeHd7g-lfsQQdsvjA6DEUgED5Dj+MF+Xi-p6bLeourY8i+WgANygbGiR-kOw6Lghq5waKCpAA)

You only need to look at the very first line.

**Comment by callumlocke** [comment]
Thanks, but I'm not sure that solves the problem, because `'foo' | 'bar' | string` is the same as `string`, right? So now I just have `{[string]: number}`, - your answer seems to be just to give up on typing the object keys?

I know there's a lot of code examples, but please skim the rest of my issue :) The headline didn't summarise the main thing I'm asking (I've updated it now).

What I'm trying to understand is, why can't I refine `propName` from `string` to `'foo' | 'bar'` by doing `if (propName in myObject) {...}` or `if (Object.keys(myObject).includes(propName) {...}`, etc? Is this kind of refinement just too difficult, or hasn't been implemented yet, or outside the scope of Flow for some reason?

I'll close this as it's more a general question than an issue, but I'd appreciate if you/anyone could reply to help me understand the refinement question.

**Comment by Viktor2020** [comment]
@callumlocke 
может тебе подойдет ето 
[example](https://flow.org/try/#0C4TwDgpgBAsiAKAnA9mAcgQwLbQLxQHIAzZZAqAH0ICMNECAoBgY2QDsBnYKLEAeWoArCM2AAuKAG8A2nCSpMOALoS2AVyzUIiAL5R8khlCglkEgIwAmAMwAaI1FqIJAFgCsANns6mrTtwATCCIMNQAbYAA1DDC1PCgATiTfdi4oAHMIKJi4-SgACjAUdGwICTlixQgASn0APikHPzSAawgQDgkAQUREDBAAHgqFUob8AWFRADo2jvzeCZFgaoBuJtTuWfKEStLKKAA3ZABLALzZjimiY7YA-PyWsWGSnFrcBpb9XHwikde14zHIgFWa1RBZNSINg8fhCJbSWZKAFQcHASHQoIhcLZWIQBg+JiZHFxfIAIlMpNWDAA9NSMlloriyaZLJSVlBaVBtChEEA)

const getValue = (propName: MyPropName) => {
  const keys: Array<MyPropName> = Object.keys(myObject);
  const key: MyPropName | void = keys.find((k:MyPropName) => k === propName);
  if (key) return myObject[key];
  return defaultValue
}
