### ISSUE TITLE
Problem with object spread syntax where the object type has optional values

### ISSUE THREAD

**Issue by jonleighton** [facebook/flow#6751]
[Example at Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5hRxwBcYA-AM4YBOAlgHYDmYAvgG50UAK6cAxhnZxOVGgAoAhvUIBKCqj7pxMlmGVFSFOXTAByanDP8hOznoBGRypfoWa1wcIWUAdP8UAGhM3S09VATBgYDBOODA8VlY4VlRLeRcaUI9g-19FfgiomMTk1LSfMDyHYNdzMMLI6Nj40pSKuAyQ+pyq-yc+Iua4hKT2oA)

The following code:

``` js
/* @flow */

type A = { foo: ?string };

function foo(a: A) {
}

const a: A = { foo: 'foo' };
const b = { foo: 'foo' };

foo({ ...a, foo: 'foo' }); // no error
foo({ foo: 'foo', ...a }); // error

foo({ ...b, foo: 'foo' }); // no error
foo({ foo: 'foo', ...b }); // no error
```

Produces this error:

``` js
    3: type A = { foo: ?string };
                       ^ null or undefined [1] is incompatible with string [2].
        References:
        3: type A = { foo: ?string };
                           ^ [1]
        12: foo({ foo: 'foo', ...a }); // error
                       ^ [2]
```

It also produces an error if I define the type as:

``` js
type A = { foo: string | null | void };
```

In that case I get:

``` js
    3: type A = { foo: string | null | void };
                                ^ null [1] is incompatible with string [2].
        References:
        3: type A = { foo: string | null | void };
                                    ^ [1]
        12: foo({ foo: 'foo', ...a }); // error
                       ^ [2]
```

**Comment by jonleighton** [comment]
Here's a workaround:

``` js
foo({ ...null, foo: 'foo', ...a });
```

**Comment by richardbarrell-calvium** [comment]
> Here's a workaround:
> 
> ```js
> foo({ ...null, foo: 'foo', ...a });
> ```

Thank you so much for this, you've saved me from having to put a heinous `: any` in my codebase.

**Comment by levibuzolic** [comment]
Seems like it might be a bug with the type refinement process, it's like the type is being refined too early and then being compared against.

When doing:
```js
type A = { foo: ?string };
const a: A = { foo: 'foo' };
const bar = { foo: 'foo', ...a };
```

The type of `bar` is automatically refined from `{ foo: ?string }` to `{ foo: string }`, which then makes it incompatible with the original definition of `A`. 🤔 

Spreading any `null` or empty object (`...{}`) will prevent this refinement from happening.

You can even spread the same object twice to prevent the type refinement: 

```js
foo({ ...a, foo: 'foo', ...a });
```

**Comment by villesau** [comment]
Made a PR to fix this: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This code no longer errors in master
