### ISSUE TITLE
Model React opaque element types soundly

### ISSUE THREAD

**Issue by motiz88** [facebook/flow#6753]
Alongside [strings, stateless functional components and class components](https://github.com/facebook/flow/blob/6ddc364cdb7702af23e69b9dd4382e8015f9e71e/lib/react.js#L156-L167), React currently [accepts](https://github.com/facebook/react/blob/master/packages/shared/isValidElementType.js) a set of internal [symbols](https://github.com/facebook/react/blob/master/packages/shared/ReactSymbols.js) for an element's `type` (and a few others wrapped in a `{ $$typeof: ... }` object). The symbols themselves are all private; they form "opaque components" that are returned from various public APIs and serve to trigger certain intrinsic behaviours within the renderer.

In Flow, because of [limitations in `react_kit.ml`](https://github.com/facebook/flow/issues/6103#issuecomment-399408555), we instead model these as function and/or class components, which _works_ in most ordinary cases, but is not technically correct - e.g. Flow will let you [call](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgIilQ3wG4AoZdGAOgDEoUBzEJAOxgAoBvNAC2AAbACZE2ALjhsAroMEBfAJQUgA) or construct them, which will cause an [error](https://codesandbox.io/s/j2p5qnwwx9) at runtime. It would be better if we could leverage opaque types, while keeping props checking and all the other nice things. (Architecturally - perhaps we can allow libdefs to declare these opaque types rather than having to build them directly into `react_kit.ml`?)

The following is a list of React features based on opaque component types and how they're currently modelled in Flow, if at all.

### Stable features

- [x] `Fragment` - modelled as a function
- [x] `StrictMode` - modelled as a function in https://github.com/facebook/flow/pull/6078
- [ ] Context `Provider` - modelled as `ComponentType`
- [ ] Context `Consumer` - modelled as `ComponentType`
- [ ] Return value of `forwardRef` - modelled as `ComponentType` in https://github.com/facebook/flow/pull/6510

### Unstable features

I'm including these for completeness, as they can be expected to officially land in future versions of React. There is no current implementation or PR for these in Flow.

- [ ] `unstable_AsyncMode`
- [ ] `unstable_Profiler`
- [ ] `Placeholder`

**Comment by jbrown215** [comment]
The machinery necessary for this will be going out in 0.89. This fixes `Fragment`, `StrictMode` and `forwardRef`. I will also take a look at `Provider` and `Consumer`.

**Comment by jbrown215** [comment]
This also fixes Provider and Consumer.

**Comment by TrySound** [comment]
I guess it's fixed with AbstractComponent.
