### ISSUE TITLE
Accept Promise as React element type

### ISSUE THREAD

**Issue by motiz88** [facebook/flow#6754]
Architecturally related to #6753, but IMHO this is its own issue with its own timeline/priority etc.

An upcoming version of React (probably under the "Suspense" umbrella) will have built-in renderer support for [promises as an element type](https://github.com/facebook/react/pull/13397). In Flow terms, `Promise<React$ElementType | {default: React$ElementType}>` will itself be a valid `React$ElementType`. This is in support of higher-level features like [lazy-loading components](https://github.com/facebook/react/pull/13398).

Getting Flow to accept anything other than strings, stateless functional components and class components as valid React element types will take some changes in `react_kit.ml` (that are beyond me personally). In this case, and unlike #6753 where we've had unsound-but-workable solutions due to the nature of the APIs modelled, I believe this one can't be solved with just libdef changes.

**Comment by SamChou19815** [comment]
I think we already have good support for Suspense.
