### ISSUE TITLE
Cannot resolve packages from GitHub

### ISSUE THREAD

**Issue by gabrielenosso** [facebook/flow#6755]
Hi guys,
I get the error "Cannot resolve module" with a private package that I have on GitHub.
In my package.json file I have:
```
"packageName": "git+ssh://git@github.com/userName/api-client.git#dist"
```

My configuration uses ```[options] all```, so I have to use ```[ignore] node_nodules```, otherwise I get errors from all my dependencies.

In my package, I have a index.js and index.js.flow, but they are also, of course, in the node_modules folder.

How can I let it work properly?

**Comment by SamChou19815** [comment]
Not enough info to repro, and likely not a problem of Flow
