### ISSUE TITLE
Using generic subtype of union

### ISSUE THREAD

**Issue by JesperLekland** [facebook/flow#6756]
Hi! 

Much as one can use sub/super-types  for objects I would like to somehow allow sub/super-types for unions. 
In the following case I have one type `Bar` which clearly encapsulates type `Foo` but also have another union.

```js
type Foo = 'Foo' | 'Bar'

type Bar = 'Foo' | 'Bar' | 'Baz';

type Baz<T: Foo> = { 
  foo: T,
};

const foo: Baz<Bar> = {
 //Flow: Cannot instantiate `Baz` because string literal `Baz` [1] is incompatible with enum [2] in type argument `T`.
}
```

Is there any way to accomplish this? Flow should be able to know that within `Baz` I can safely declare foo as either "Foo" or "Bar" as it's encapsulated by both type `Foo` and `Bar`

**Comment by lll000111** [comment]
What is the problem? The error is exactly what you should get. You have more elements in "Bar" than in "Foo", so you clearly cannot use "Bar" in places where you told Flow to only accept "Foo".

Unrelated to the error, if you want to define a new union by extending an existing one just write `type Bar = Foo | 'Baz';`

**Comment by JesperLekland** [comment]
Fair enough! Thanks for the explanation
