### ISSUE TITLE
Weird issues with using Array as a constructor

### ISSUE THREAD

**Issue by an-kumar** [facebook/flow#6759]
I'm trying to use Array as a way to tell a function that it will return some Array type. It's part of a library that registers serialization/deserialization functions per class.
 
https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygMXBAPAFQD4AKCAGzQC5EBhMgQzTQMIEpr9EBvAKEUQBOKKCAFJiABmr0wAT1YBuRAHpliAFYgMyOIgAOjNMll6YYAOY8Avjx6rEASWCJZcEIPCJgZOAHdjeigAtPRQQXpwRgAWKEIANMgxASiIMFCpYMCxRsBwAogARPQCAgWpRgUAgiX0srgoALZ6ULKEBTwQCNrF+QC8yOhYOMTVArWKtvYAEn4oAG6xCVBRMEYYMGRkXvQbVB1d6T0ATNSjtfVNLYSI-agY2JAjNfIKk2qVYAAmiauIvnkAayMUDgcAAdB0GExEPhBnRDCxuNZbJ0wN0SgBmDhwqHMGStG4De7DWEYeFMRRAA

shows the issue. Basically, Array cannot be used as Class<T> where T is an array type. I would have expected Array to be the constructor for Array<T>, like `TestClass` in the flow.org/try above.

**Comment by SamChou19815** [comment]
This no longer errors
