### ISSUE TITLE
$Spread operator

### ISSUE THREAD

**Issue by Benjamin-Dobell** [facebook/flow#6764]
I'd like to request an additional utility type `$Spread` that would make the following possible:

```javascript
type Suit = "Diamonds" | "Clubs" | "Hearts" | "Spades"
type AllSuits = [$Spread<Suit>]

const ALL_SUITS : AllSuits = ["Diamonds", "Clubs", "Hearts", "Spades"] // OK
const SOME_SUITS : AllSuits = ["Diamonds", "Hearts", "Spades"] // Error
```
The only concern is that `SOME_SUITS` is actually invalid for _two_ reasons:

  1. Because `"Clubs"` is missing. ✅ 

  2. `"Hearts"` and `"Spades"` are now in the wrong position.

__2__ is relevant because array types are positional (as they should be), thus the following would also be invalid:

```javascript
const OUT_OF_ORDER_SUITS = ["Spades", "Diamonds", "Clubs", "Hearts"]
```

This isn't entirely ideal as the "possible values" of a union type aren't really ordered in the first place. Having an additional "$Set" type would fix that, but that's probably another Github issue.

I am aware that type/literal definitions can presently be somewhat inverted i.e. derive types from constants with the help of `$Keys<typeof SomeObject>`. However, that only works in the simple case.

Ideally it'd be great to be able to validate more complex cases e.g.

```javascript
type EmptyThing = {
  type: 'empty'
}

type StringThing = {
  type: 'string'
  value: string
}

type NumberThing = {
  type: 'number',
  value: number,
}

type Thing = EmptyThing | StringThing | NumberThing

type ThingType = $Values<$PropertyType<Thing, "type">>

const everyType = ['empty', 'string', 'number'] // Flow type???
```
I'd like to have a way to add flow typing to that last line line such that it gives a flow error if I come along and add a new `Thing` e.g.

```javascript
type DateThing = {
  type: 'date',
  value: Date,
}

// ...

type Thing = EmptyThing | StringThing | NumberThing | DateThing

// ...
```
If we had `$Spread` I could simply go:

```javascript
const everyType : [$Spread<ThingType>] = ['empty', 'string', 'number']
```

Then I'd have the desired result with a flow error stating something like:

> __everyType__ has the wrong length. It should be length 4, but is length 3.

**Comment by wchargin** [comment]
> Ideally it'd be great to be able to validate more complex cases e.g.

[You can do this with existing tools:][1]

```js
// @flow
type EmptyThing = {
  type: "empty",
};
type StringThing = {
  type: "string",
  value: string,
};
type NumberThing = {
  type: "number",
  value: number,
};
type Thing = EmptyThing | StringThing | NumberThing;

type ThingType = $PropertyType<Thing, "type">;

const types = { empty: true, string: true, number: true };
const everyType = Object.keys(types);

function _staticCheck_hasAllTypes(x: ThingType): $Keys<typeof types> {
  return x;
}
function _staticCheck_noExtraTypes(x: $Keys<typeof types>): ThingType {
  return x;
}
```

If `types` either omits a type that exists or includes a type that does
not exist, Flow will raise type error. If you want the values in an
array, you can use `everyTypes`.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagKIFt00AVACwEsA7Ac1AF5QBvRUUNLALlACJMC0uANIgC+AbhQZsAZWQAnSlVIK6jZq0mcuAZzkLBagG4BDaAFdMnHfOpCxErKABypvACNMspdRVMWbC9wULu6y+izGZgFBbh624v6gXjT0+ISoSaAAPqAy1ork3tnOMZ4FVOL22ElEkioAJAAKsrBYssSSADxJAtz+XAB8FQDGsBQ66lhaPqC8aZxy5j1WCvOyi6DRIavmoHYjY8gzBh7ptfQA8q4AVphDyAB0ANaYqFoAFP5aAJQVkKYUdzIo1AAH0dEZkGQhgBhEi3R4gkhGLQAQWg0BqkzeAA9ONVJF9OHUANIvLQdfywSATTBafqqFiyTDIUyyCigbHiYSIP4AyHAsHICFQ2HwkEUWA4bFyIyY2k4omk14UyRUml0wmJMpyhmgJkstkcrmIIA

Is there anything wrong with using this existing form?

(Disclosure: The feature as proposed raises a _lot_ of red flags in my
eyes. First, union types are absolutely unordered—if `A | B` is ever
different from `B | A`, then this is unequivocally a bug in Flow. It
sounds like the proposed feature is that `$Spread<T>` should be an
`unquote-splicing` with the semantics, “_all_ inhabitants of `T` must
appear here in the enclosing list.” My intuition is that this is not the
kind of thing that a type system like Flow can easily be extended to
handle.)

**Comment by Benjamin-Dobell** [comment]
> Is there anything wrong with using this existing form?

```
type Thing = EmptyThing | StringThing | NumberThing;

type ThingType = $PropertyType<Thing, "type">;

const types = { empty: true, string: true, number: true };
```

> Is there anything wrong with using this existing form?

I have two issues with this:

1. DRY. We already know what are valid `type` from a `Thing`. If we're creating an object manually the problem doesn't go away, we've just been moved it to the definition of `types`.

2. I don't _believe_ this can be moved into a module declaration, meaning it can't be incorporated into `flow-typed` definitions.

I do actually already do something similar to this, but as in the propose solution I have to manually keep the type definitions in sync with some constants.

> (Disclosure: The feature as proposed raises a lot of red flags in my
eyes. First, union types are absolutely unordered—if A | B is ever
different from B | A, then this is unequivocally a bug in Flow.

Absolutely agree. I mentioned the concept of `$Set` but didn't want to over-complicate this issue. I just wanted to lay out what I'd like to achieve, and propose a _rough_ solution.

> It sounds like the proposed feature is that $Spread<T> should be an
unquote-splicing with the semantics, “all inhabitants of T must
appear here in the enclosing list.” My intuition is that this is not the
kind of thing that a type system like Flow can easily be extended to
handle.)

I'm far from an expert in this area, so am in a position to make claims about how this might be implemented. As a consumer of Flow I see value in such a feature. We can already validate that `X` appears as key in a map, I'd basically just like to do the same for a "set", although we don't have Set syntax so I've been a bit audacious with my use of arrays. We have `tuples`, so I'm basically envisioning something like unordered tuples.

**Comment by Benjamin-Dobell** [comment]
Whoops, my apologies!

You're not at all suggesting `types` is required for validation, you're _validating_ `types`!

I was just a tad confused by the use of an object rather than an array, but you mentioned `everyTypes` as a similar solution for arrays.

It's a _little_ bit clunky, but it lets me do what I want, so am happy to close this issue 👍

**Comment by wchargin** [comment]
> If we're creating an object manually the problem doesn't go away, we've just been moved it to the definition of `types`.

I don’t understand. In your “desired behavior” example, you construct
`ALL_SUITS` and `SOME_SUITS` manually. How is this different from
constructing `types` manually?

> I do actually already do something similar to this, but as in the
> proposed solution I have to manually keep the type definitions in sync
> with some constants.

Yes: you can add fancy utilities to the type layer, but not to the value
layer. All emitted JavaScript is written by the user. Flow never
generates code; the process of compiling Flow to JavaScript literally
only deletes characters from the input file (or replaces them with
whitespace). This is a core design principle of Flow and one that is, in
my estimation, not likely to change.

It seems to me that the example that I proposed has the minimal amount
of boilerplate. You define the types at the type layer as usual. You
define a single constant `types` with values linked to the types.
Everything else is derived. Without generating code, what better could
one do?

> I don't _believe_ this can be moved into a module declaration, meaning
> it can't be incorporated into `flow-typed` definitions.

Not sure what you mean by this.

> We can already validate that `X` appears as key in a map, I'd
> basically just like to do the same for a "set", although we don't have
> Set syntax so I've been a bit audacious with my use of arrays

Presumably by “map” you mean string-keyed object, not `Map`.

The standard way to emulate a set in JavaScript is to use an object
whose keys map to a fixed value (like `true`), not to use an array
(which really _doesn’t_ represent a set: it’s ordered, admits
duplicates, and doesn’t have fast lookups or modifications). If you use
the standard set-as-object form, much of Flow’s existing functionality
comes for free, as demonstrated above.

I don’t work officially on Flow or for Facebook at all, so I don’t
really have much more to contribute on this issue, but I would humbly
suggest that you try to work within the existing set of primitives
afforded by Flow. You can come up with all sorts of clever constructions
to get a high degree of expressiveness while fixing particular runtime
representations, but if you try to force Flow to work with an object
structure that it wasn’t designed for, you’ll keep running into trouble
down the road. I say this as someone who knows a thing or two about type
systems and tried really hard to get things to work, eventually falling
back to simpler approaches, which has removed an order of magnitude of
headache.

**Comment by wchargin** [comment]
> Whoops, my apologies!
>
> You're not at all suggesting `types` is required for validation,
> you're _validating_ `types`!

Correct. I should have been clearer there. To be more explicit:

A type system is, at its core, a proof system. By creating a function
that accepts `x: T` and returns `e: U`, you ask Flow to _prove_ that
whenever `x` is a term of type `T`, then `e` is a term of type `U`.

This simple idea enables you to express powerful constraints simply by
creating functions (or, in general, annotating expressions). The
constraints are all checked statically, even if the functions are never
run or exported.

> It's a little bit clunky, but it lets me do what I want, so am happy
> to close this issue 👍 

Great; glad that we’re on the same page.
