### ISSUE TITLE
Maybe types validation counts as undefined even after checks

### ISSUE THREAD

**Issue by Rejpal** [facebook/flow#6766]
When you have an optional property in an object, flow shows error in using the type even when you check before if it is there or not.

*Reroduced*
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCSAwnAHYBueATgM4CGGAluWALxgDeqYYO9WePQAmAfgBcXHmACQeGHgC2eMhlqSAgtWoCAPPTJYAfNIC+qc6igBXMgGNmraiuE0ACjGsBzJmTAAKO3IqOkYWMkkSYJoGRzIASileJigAoMoYsPIAOn5BOBEwADIisHSQ2PDcgSFhbPklFTVE7l5edNoMLj4aguFJTjAG5VVaMFNx9jLo0LiAbmleZwxraj9-RbbOU2BgZ3oHacUccibN+IXeS14MAAtqRDAyPCQAUW04an8AcgAVaiwvi8YAwcDAzjIrmoYA83l8YAQTDucGsXTytWy3wuFiAA

Is there any way to explain flow that in this particular place in code the property is defined for sure?

**Comment by wchargin** [comment]
This appears to be a bug with destructuring specifically. Replacing

```js
    const { payload: { elements } } = conversation;
```

with

```js
    const elements = conversation.payload.elements;
```

causes the error to (properly) disappear.
