### ISSUE TITLE
Assignment using Bracket syntax and variable keys creates false positives

### ISSUE THREAD

**Issue by rakelley** [facebook/flow#6767]
[TryFlow Demo](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAKrgQLxgDeqYYUccA-AFxgDOGATgJYB2AcwA0dMACMAhtzZh+AVwC24vN1H0pAL1lc+Q1AF90AYzj8uYODAAmAZR7zjGdsTL4wVWvUZx2AcnhuPEU-dQlpdgBGQwBuVFNzDDk8BHtuR2ciUnIPGgM41GBgIjwMAAs4azBIyTAAWjAAdThuAGsOVAB5cQArPCcAOla8LA4ACis7BycASgHGbgBRSWMysah5fideMzHhrBmaMV4oMD2RjwoqPx8-MAAfe7B9y+utP0OvemTU6YwAbX2AF1cpM0hlASMgXF6EZ6Cczi8rm9pB8jt8fuCnJCsCCqGC-jjoWIjAYZgUiiVypVquJ6mAAGKSXgwDrdPqDfbjAnpWbzFrLVbrTbbXb7T7HU7nLCvMA3Jh3R7PC7IuVSbiKp5Iq5qySaNFfej8FJYgHA0E2U1EmFgUnk9CUwilCpVABMtQazTabN6-QwQxG3MtfzmC0Faw2WwwO340ol9A4CF4GCF4vR32Mkg4BHlcD8rDE9Ez2d1+oLGKNJsJ5vxwd5ZqhNox4iCklaTe+hbAxZz6vzXcrv3rRItU2HwI7Glb7ZJhnthWKTupbrpDSZLJ9HP9XImdYyoYFKwjIujYpG8c4SZTazThu7WZzt3LGYfuo1z6Lr787w-32NQ4hGtLD3bEJwHCRpxtO04iAA)

With an object map of mixed value types, and property access/assignment using bracket syntax and a variable key, flow always considers `Type[key]` to be able to evaluate to any of the value types represented by all the possible `key`s, even when it logically cannot be more than one type in a single given assignment expression.

This can be bypassed by writing your conditions verbosely to limit the possible types, as in the demo, but this is an unpleasant workaround when simply trying to copy a subset of optional properties between two objects of the same type.

**Comment by SamChou19815** [comment]
This kind of dynamic pattern will not be supported
