### ISSUE TITLE
polymorphic classes don't work in an es5 world

### ISSUE THREAD

**Issue by jaredly** [facebook/flow#677]
For example:

```js
function Deferred /*:: <Tvalue, Treason>*/() {
  // stuff ...
}

Deferred.prototype.resolve = function resolve(value /*: Tvalue*/) /*: void*/ {
  this._settled = true;
  this._resolve(value);
};
```
Gives `Tvalue is undefined`. I don't know if there's a reasonable way to do this, but it makes a flow-annotated es5-transpiled lib unusable in a project that also uses flow :(

From [this issue](https://github.com/facebook/fbjs/issues/23) on fbjs

**Comment by jeffmo** [comment]
Indeed, we don't have a good way to declare class-wide type parameters on ES5 classes.

If you must use ES5 function-classes, your best bet here is probably to use a `.js.flow` shadow file that sits next to the ES5 file and declares the ES6 class interface for other modules that use the class.
