### ISSUE TITLE
Any update on the class indexer bug?

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6770]
Super annoying and causing lots of confusion with people when they see that I am extending all my classes with `Object` - any update on fixing this problem?

#4014 

Actually it seems that you can't even work around this if you are using interfaces.  Having the class just extend Object seems to have consequences (Flow thinks any object matches such as Map, Set, etc?)

**Comment by lll000111** [comment]
Just an aside, you should comment there and not open a new issue. Same visibility for anyone viewing the issues list ordered by "last updated".

**Comment by wchargin** [comment]
Looks like the `extends Object` workaround broke in v0.81.0, probably
due to the “Removed the indexer from the `Object` libdef” change:

<https://github.com/facebook/flow/blob/07f29a8efb38a69af95fef9531ff9e6545d4fd65/Changelog.md>
