### ISSUE TITLE
ElementConfig and ElementProps not working with ComponentType and StatelessFunctionalComponent 

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/flow#6774]
Something happened on version [0.63](https://github.com/facebook/flow/blob/v0.63/Changelog.md#0630) that broke extracting props (`ElementProps`) or config (`ElementConfig`) from components declared with `ComponentType` or `StatelessFunctionalComponent`.

[try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgBE2pFdA3MulnqLgJ4ZGgA3gGEaWAHZFxuACp8iAGlABRaETRTcABWoYAzkoDKuEriJq9egGIBXcRRSxxJaKMxPNAX1BUa9RuS4rMi8-KA6sPqgALxCAD4YAAwAXKAARrCwaiTiShgAjKl6uNgo4gDmcZ7IZE7FoG4SmqmNHtJy-AA8EfoAfDGgABR2ACZEkGVEI6k5PACUbIihAjKJA6rqmj16ncuwkA1ibbi9i7Xi9WQpoKsDgp4sQA)

- works as expected on **0.62**
- does not work as expected on **0.63**
- does not work as expected on latest version (**0.79.1**)

**Comment by mgtitimoli** [comment]
@calebmer is there a chance I get some feedback from you on this one?

**Comment by fabiomcosta** [comment]
Exactly, this is still broken.
0.84, still doesn't work as expected.

**Comment by fabiomcosta** [comment]
This is a very serious issue that prevents any HOC from being properly type checked.

**Comment by fabiomcosta** [comment]
YES, sounds like this has been fixed on 0.89!
