### ISSUE TITLE
flow reinitializing every time i run it.

### ISSUE THREAD

**Issue by killynathan** [facebook/flow#6775]
Flow v0.79.1.
MacOS High Sierra v10.13.4

Steps to reproduce:
  1. npm run flow
  2. make any changes in files being watched
  3. npm run flow

The consecutive times calling flow is re-spawning another flow server, and not going off on the first server that was spawned, resulting in a very slow process to typecheck as it is reparsing all the files. I am guessing flow is crashing. This also messes with the 'Flow Language Support' extension for Vs Code. This error occurs both when the extension is enabled and when it isn't.

**Comment by SamChou19815** [comment]
This is likely fixed a while ago.
