### ISSUE TITLE
[REQUEST]: Indexer Properties with Safe Typing when Guaranteed 

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#6776]
So ran into the issue defined [here in the docs](https://flow.org/en/docs/types/objects/#toc-objects-as-maps) where an indexer property essentially allows you to access any property on an object even it it does not exist.  

This makes sense for the most part, since the object could be mutated Flow in general can't assume it's not there when evaluating, at least not without possible side-effects in many situations.

That being said, this is not true in all circumstances.  **Specifically if the object is frozen.**  Flow already uses frozen objects to be less likely to lose typing for an object as you call functions so it makes sense to also handle this.

So say I have something like:

```javascript
/* @flow */
type Commands = {
  [commandID: string]: () => number
};

const obj: Commands = {
   one() { return 2 }
};

const result = obj.two();
```

Flow will allow this to occur.  While I can understand in this specific case flow could technically be safe and at least provide a warning to the user, my guess is this was decided against due to the many situations that you have to consider when you can and can't be sure this object may or may not be mutated.

**HOWEVER**

```javascript
/* @flow */
type Commands = {
  [commandID: string]: () => number
};

const obj: Commands = Object.freeze({
   one() { return 2 }
});

const result = obj.two();
```

in the case above it is guaranteed that there is no situation that `obj.two` will exist or be a function.  Flow can be **absolutely certain.**

---

That being said, it would be nice in general if flow could at least have a linting warning and/or error in at least some cases when indexer properties are utilized.

### [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDCcAtsQIYB2AJgM5gC8YA3qmGANoDGJ51AkgBEAXGBroATgEsKAcwC6IgBQBKBgD4wFAK7EARrnGoAvgG5UqbhTFg4ugFYiipSrQZgA8vdyd0AOijiuLgAXriKLGw2FGGqTGCB6FriFGAATGBGxspmFnBW6PG4NFowBYy2dr7oCHAqJkA)

This would essentially mean "its this type, any keys that aren't otherwise defined within the type must conform to the indexer property type, but once its define it only allows lookups against the keys it knows exist.

There may be other reasoning / problems with this logic.  It may only work, for example, when statically defining the object, which would still be fine imo but would be nice to have the extra type checking there without needing to run existence checks in your code just to be sure.  

Specifically in my case, importing the object that uses that type means that spelling errors or problems do not result in a warning or error to the user which is a critical piece of Flow for me (or the #1 thing that causes incorrect type response in a f unction, when you short circuit a function and return early while forgetting you should return a string or something).

**Comment by SamChou19815** [comment]
Flow doesn't do global inference. In your example, the annotation will prevent Flow from going deeper into how things are defined, which is expected behavior
