### ISSUE TITLE
declare module doesn't work with ES6 default import

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#678]
The following correctly gives a flow error:

``` javascript
// foo.js
/* @flow */
var _ = require('underscore');

function foo(): string {
  var x = _.clone("foo");  // ok
  return _.foo();  // call of method foo Property not found in module underscore
}
```

```
// .flowconfig
[ignore]
.*node_modules/flow-bin.*
.*node_modules/underscore.*

[include]

[libs]
lib

[options]
```

``` javascript
// lib/underscore.js
declare module "underscore" {
  declare function findWhere<T>(list: Array<T>, properties: {}): ?T;
  declare function clone<T>(obj: T): T;
  // ...
}
```

However, if you change `var _ = require('underscore');` to `import _ from 'underscore';`, then the flow error disappears. If you change it to `import * as _ from 'underscore';`, then flow keeps giving its error correctly.

Default imports and wildcard imports are different for ES6 modules, but for non-ES6 modules at least Babel treats them very similar and I very often use default imports to import non-ES6 modules.

I guess there's two issues here. First, there doesn't appear to be a way to declare the default export of a module. I'm not sure how I could create type declarations for a module like jQuery which exports a single function with a ton of properties. I was hoping I could do something like this in the short term:

``` javascript
// lib/underscore.js
declare module "underscore" {
  declare function findWhere<T>(list: Array<T>, properties: {}): ?T;
  declare function clone<T>(obj: T): T;
  // ...
  declare default = {
    findWhere<T>(list: Array<T>, properties: {}): ?T;
    clone<T>(obj: T): T;
    // ...
  }
}
```

Second issue, is that the above work-around is pretty redundant for modules where the default export was the entire module itself. It would be useful if there was a way to declare that the default export is the same as the entire module, like this:

``` javascript
// lib/underscore.js
declare module "underscore" {
  declare function findWhere<T>(list: Array<T>, properties: {}): ?T;
  declare function clone<T>(obj: T): T;
  // ...
  declare default = self;
}
```

**Comment by kylehg** [comment]
+1 also seeing this

**Comment by clebert** [comment]
+1

**Comment by calebmer** [comment]
This is no longer an issue with the underscore types: https://github.com/flowtype/flow-typed/blob/master/definitions/npm/underscore_v1.x.x/flow_v0.38.x-/underscore_v1.x.x.js#L693

We will be revisiting how you declare modules soon and make more fundamental changes at that point 😊
