### ISSUE TITLE
Flow doesn't check globally declared object type if some value contains any React$ type

### ISSUE THREAD

**Issue by stomvi** [facebook/flow#6781]
flow-bin@v0.79.1

Let's see the following code:

```
// @flow
import React from 'react';

// flow type declarations
type Payload = {
  key: React$ComponentType<*>,
};

type Props = {
  content: string,
};

// SFC
const Foo = (props: Props) => {
  const {
    content,
  } = props;

  return (
    <div>
      {content}
    </div>
  );
};

// some function
function testFunction(input: Payload) {
  return input;
}

// calling the function with a payload
const testInput = {
  key: Foo,
};

testFunction(testInput);
```

This works fine. But if I move the type declaration `Payload` to some js file under `/flow-typed`, the payload `testInput` will be uncovered by flow. I found this is happening only if any value of the payload object is type `React$Element<*>` or `React$ComponentType<*>`. Not sure if other React$... types will cause this. Is this a bug or it's just currently a limitation of flow?

Here's a screenshot:
![screen shot 2018-08-23 at 3 38 22 am](https://user-images.githubusercontent.com/1802713/44486387-0684e000-a686-11e8-9314-71b614e57275.png)

**Comment by SamChou19815** [comment]
This is likely due to usage of existential types, which is no longer supported.
