### ISSUE TITLE
Flow reporting that property is not available even with gate detecting case that it is undefined.

### ISSUE THREAD

**Issue by ezmiller** [facebook/flow#6787]
I'm unsure if this is a bug or something that I've missed, but I can't quite see why Flow is reporting errors in this sample code:

```
const camelize = (x) => x;
const getSearchTypeFromPath = (x) => x;

type A = {
  type: '@@router/LOCATION_CHANGE',
  payload?: {
    pathname: string,
    query: {},
  }
}

type B = {
  type: 'action.foo',
  payload?: {
    mode: string,
    params: {}
  }
}

const byMode = (
  state: {} = {},
  action: A | B,
) => {
  switch (action.type) {
    case '@@router/LOCATION_CHANGE': {
      if (!action.payload) {
        return state;
      }
      
      const modeKey: string = camelize(getSearchTypeFromPath(action.payload.pathname));
      return {
        ...state,
        [modeKey]: action.payload.query,
      };
    }
    case 'action.foo': {
      if (!action.payload) {
        return state;
      }

      const modeKey: string = camelize(action.payload.mode);
      return {
        ...state,
        [modeKey]: action.payload.params,
      }
    }
    default:
      (action: empty);
      return state;
  }
};
```
Here is a link a demo: [link](https://flow.org/try/#0MYewdgzgLgBMCGBbApgGwJYC9kwLwwAoAPASjwD4YiBuAKFElgHNkoBlZeAJ2AAsAVAJ4AHZADEuIRAAV4UXnkKkKVOrSgicAQUUBvWjBgbRALhgByAAKXJAVyjIuAegAyAeQDCW-gEk3AOQB9DwAJLX8AcQBRcwAaAxhheEFUEHgAEwB+M31DQyT5MCRkM2gudDAmeLyYAEdbR0EcgF9qmGbaDvVNGAAhPQTjEot4YCh0cAA6ADMQEDiEpJS0rJyEw0QQdOGyiqr1xO4kCBaEjq6GaBgAI0EAWS2cfAIE6Dlh3Wa9VoTR8fAzDoAD59eJkXCUXIwCAAd3QUD4hD+EzAkyGZChhgQEBwVhsIHsjlcnm8fiCoXC0XMaxqhnQ00IAEJkVMlqkMhiDjUuKxbFwwNCoO86LT2lyYOLLrBNtsANLIJqC8qVRQIFAYbAEFjsTg8ASaCRSWTyAgs1FslaTAq8IooEgkEW0nlQPkCzG0yaet4ONqigDaMuQ8sEAF0zGarcl2elJvVGr68s1HYYOjVsbiI7N5jTafSmRGLRyYO7ubz+YLheLU7SpTBA8HSlBlUxVcUNchTWMUZHlhlJoGHeLna7i+LDJ7Jt7kAmagHHsGwzAC1HLUkuMcZ2KatXDNtpvBbKgoCZxZ3-mAzMhEMINIPRcPy1PHedqEA)

The errors are:

```
33:         [modeKey]: action.payload.query,
                                      ^ Cannot get `action.payload.query` because property `query` is missing in undefined [1].
References:
6:   payload?: {               ^ [1]
43:         [modeKey]: action.payload.params,
                                      ^ Cannot get `action.payload.params` because property `params` is missing in undefined [1].
References:
14:   payload?: {                ^ [1]
```

It seems to me that the if-gate at the top of each case block, should handle the case where `action.payload` is undefined. Oddly, if I remove the functions that in this example code have been turned into dummies, the code doesn't produce any errors, even though the logic of the program flow is as far as I can tell the same. Here it is without the dummy functions: [link](https://flow.org/try/#0FAFwngDgpgBAgjAvDA3sGNzQFwwOQACBATgPYCuIUxA9ADIDyAwnACoCSDAcgPpMAScLgHEAongA06GBACGYADalZAEwD8uNBgxyQACwB2sgLZRcAZxDEAlgYDmU7TACO5amE0BfRzE-A-oJCwAEJIqNJYZviyAMYg1qQGAHQAZqSkktJyisrqmtIYxqQqUZY29j46ssQm5l7SfgExiZYwAEZgALLFsMgAFNKWslReYSje0rHxibgIAD4wwVIAlEgAfOEY5gDu1iAxejB9UwnJkata2jGy5rCEJBRUtIwsHNx8giLi+U4Y1ilHACEJ0SSWySlUFwKv2IUBA5GIBhgQyoAG5oRg-L8YBiYM0DK0iiUANJQDzIqy2OxhEHJcG5MHDQwmKDo7Gw+GIzbYmBJPkoqCVX4AbSJUFJYAAurhaYycqokq53ELMWztFirjc7rK0hkfr9-kDZfTIdz2XCEUiBWqnBqnPjCT0JRZKfYaXFTnKISokmKbdoOZazb8+UkBSrtKKnWTpTBjfJvYyasZzBG7b5oSUUrJyAoQNhcccPTMYFBjBBwMt-RhA1zrQ1-KigA)

**Comment by jbrown215** [comment]
This is because of your calls to camelize. Flow invalidates refinements after function calls-- see https://flow.org/en/docs/lang/refinements/#refinement-invalidations-
