### ISSUE TITLE
Better error messages for things that can be solved with generics

### ISSUE THREAD

**Issue by benwiley4000** [facebook/flow#6792]
I'm doing this:
```js
function shuffleArrayExceptNot(array) {
    return [...array];
}

// Loop 1
for (const str of shuffleArrayExceptNot(['x','y','z'])) {
  
}

// Loop 2
for (const num of shuffleArrayExceptNot([1,2,3])) {
  
}

// Loop 3
for (const [a, b] of shuffleArrayExceptNot([[1,2],[3,4]])) {
     
}
```

If I remove either Loop 2 or Loop 3, everything is fine, but when I have both, I get this error message:

```console
16: for (const [a, b] of shuffleArrayExceptNot([[1,2],[3,4]])) {
                ^ an indexer property is missing in `Number` [1].
References:
11: for (const num of shuffleArrayExceptNot([1,2,3])) {
                                             ^ [1]
```

Not sure how to begin to fix this one. Also not sure if this is my fault, or if it's a bug.

### Repro [here](https://flow.org/try/#0GYVwdgxgLglg9mABAZwBYmMANgUwIIBOBAhgJ4CiAHhDgA5QBycUAFMUWQJSIDeAUIkGICOKCAJIA2gDpZ7EqQC6Abj4BfPnwD0WxABk4cWogCMfYHAKIWEBMigooVuMBTpMuQgqo16TVpIA5JSBADSBpGGBAF6Bipzc-ILqmjr6hsYATOaW1rZg9ohgIAC2iC5uGNj4HBTUdIzMLJImoZmhAMzxiQKIKdq6BkaIHTlWNnYOksShiABGiuWuaFWetT4N-s0tbYqhkh2hACyK3by9QupAA)

**Comment by benwiley4000** [comment]
Hm, by making the function generic:

```js
function shuffleArrayExceptNot<T>(array: Array<T>): Array<T> {
    return [...array];
}
```

I solved my issue. However I think Flow should give me a hint instead of giving me the very cryptic/wrong message it did (as far as I know the "indexer property" thing doesn't work for arrays).

**Comment by SamChou19815** [comment]
Closing since the original example will require annotation since v0.201
