### ISSUE TITLE
Type Assertions of objects modify its type

### ISSUE THREAD

**Issue by elas7** [facebook/flow#6795]
The following works fine ([Flow Try](https://flow.org/try/#0MYewdgzgLgBAbgQwDYFcCmMC8MAsAmAbgCgiAKRVNALhjBQFsAjNAJwEoCYB6LmAdRAsA1hBhixZCuhr4O4sT36CRQA)):

```javascript
const value = 42;

(value: number); // Works     
(value: 42);     // Works
```

But the following fails ([Flow Try](https://flow.org/try/#0MYewdgzgLgBCBGArApsWBeGBvAUDGAZiCAFwwAsATAJA4C+A3DjgBQIpplZGkxgCuAW3jIATnQCUDGAHoZMAOohRAawit2qKFx5kqk6fnxyYAUVGjlAQhxA)):

```javascript
const object = {
  foo: 42	
};

(object: {foo: number}); // Works
(object: {foo: 42});     // Error!
```

It fails with the error `"Cannot cast 'object' to object type because number [1] is incompatible with number literal '42' [2] in property 'foo'."`.

Note that asserting `42` first, and then `number` works fine ([Flow Try](https://flow.org/try/#0MYewdgzgLgBCBGArApsWBeGBvAUDGAZiCAFwwAsATAJA4C+A3DjgBQIpplZGkWV0BKBvhEB6UTADqIAE4BrCK3aooXHmTABXALbxkMwcPFTZCoA)):

```javascript
const object = {
  foo: 42	
};

(object: {foo: 42});     // Works
(object: {foo: number}); // Works
```

Therefore, it looks like type assertions of objects modify its type. Is this an error?

**Comment by lll000111** [comment]
Well, `foo` is not constant, it could be anything.

**Comment by elas7** [comment]
@lll000111 Thanks, but I'm not sure if that is the problem because updating the first example to use `let` keeps working ([Flow Try](https://flow.org/try/#0DYUwLgBAbghsCuIIF4IBYBMBuAUDgFLAiAFwQB28AtgEYgBOAlFhAPSsQDqA9vQNYBnCMOEEiiMpmYjh7Lr0FA)):

```javascript
let value = 42;

(value: number); // Works     
(value: 42);     // Works
```

Besides, I'm not sure if I need to define a type for the object for this to be a valid problem. I just want to be able to assert the types inferred by Flow, without _changing_ the types while asserting.

I updated the original post with an example of how changing the order of assertions makes it work again.

**Comment by lll000111** [comment]
[Yes (link, demo)](https://flow.org/try/#0MYewdgzgLgBCBGArApsWBeGBvAUDGAZiCAFwwAsATAJA4C+A3DjgBQIpplZGkwCGYAJ50AlEzZJUULjzLQATgEswAc1Hj2UmcTIDhY1ps7ZZMMAFcAtvGTz1OIA)

The reason is probably what is described here: https://flow.org/en/docs/types/casting/#toc-type-casting

Although this is all not exactly ideal, neither the behavior nor the documentation.

**Comment by elas7** [comment]
@lll000111 got it, thanks!
