### ISSUE TITLE
Error with missing null check in $Shape field

### ISSUE THREAD

**Issue by khlevnov** [facebook/flow#6796]
Hello, I have a problem, or maybe a bug. When I try to define $Shape of any type, all fields will be maybe, and user have to check it before using. But example below is correct in case with undefined string field. Why flow is missing potential bug with calling method on undefined?

```javascript
type Sometype = {
  stringField: string,
  numberField: number,
}

type ShapeOfSometype = $Shape<Sometype>

const emptyshape: ShapeOfSometype = {} // No errors!
const shapeWithString: ShapeOfSometype = { stringField: "string content" } // No errors!
const shapeWithNumber: ShapeOfSometype = { numberField: 42 } // No errors!

// Case with undefined string field "a",
// but flow doesn't says anything about null check!
shapeWithNumber.stringField.toLowerCase();

// Correct way to check it before using string methods
if (shapeWithNumber.stringField) {
  shapeWithNumber.stringField.toLowerCase();
}
```

Link to try flow with working (or not) example.
https://flow.org/try/#0C4TwDgpgBAyg9gWwqSUC8UDeAoKUDOwATgJYB2A5gGIkQA2AJgFwHHkUA0uUZArggCMIRGvWY9+QolwC+2bCmgwAFgENIAeQBm8JIvRQAJCvUQAPLuTgIAPnkBjOGUJQICMKHxrILE5p2IVqgYmDJQAPThUABycK5ERHBE+ACE2I7OwATeEADqJMDKMGyUvjnalvohrKSUoowsAESEtRRQGcAQZMCNUGGRMXHCiclpGS5epvmF0ZLCZaYVgVVYEoLC9eIALABMfRFRsfEjqfIDAMKq+NAA7gXKULxkDBBa5BAMNexQb2JQjapGlwBgJeFktHQ4DcoAw4BB8GQAORZfCqED4KCqMggQrfVQCOBgiR0Oj2ZQQewAazSk0g02Us3WRAAdC12JtmcA4AAZKHCS7XAAUAEoANxnKLnJJEClZG5oqBc9rkqlQApQIRaJLQXj4b5syhQPTKOAMfDYEhaKCC2l5e6MqSskrUWiMYVYbi2+kO4RO1ocrm8m78q4QEXiuRAA

**Comment by bhandarijiwan** [comment]
It seems like Flow doesn't need a refinement check for  `$Shape` types even though the [docs](https://flow.org/en/docs/types/utilities/#toc-shape) do say  `$Shape` marks every field optional.
However, the behavior you are looking for is possible with a little workaround. [Link](https://flow.org/try/#0C4TwDgpgBAyg9gWwqSUC8UDeAoKUDOwATgJYB2A5gGIkQA2AJgFwHHkUA0uUZArggCMIRGvWY9+QolwC+2bCmgwAFgENIAeQBm8JIvRYAdMYAkK9RAA8u5OAgA+KBygBtVWRABdFhARhQeHLYAMZwZIRQvv4g+GqQLOaaOoi2qBiYMlAA9FlQAHJwkUREcET4AIQhYRGxFgDqJMDKMGyUCXEQ2jb66ayklKKMLABEhP0UUKFkwBDTw1CZOfmFwiVllVM1HQ1NeZLC7RZdKT1YEoLCg+IALABMC9m5BUVrFfJV4cA8THwXRAZRUC1SCGX5SK4AbkeL1KHxqTDG7ABfiBHUMiIGtEYUKWq1hwIgO2Uez+6Na1CxDEMwDgABk4AB3YQAYVU+AgAAoAJQ43J4ojyJbM0pECDBL4M1QgKA0ybKMUAaygjSgQi0pWgvHwSIxEz0yjgDHw2BIWigHIJRJJUjJ4yuXKw3EtjWJ+yItvYV2pdMZLLZnJ52CCQA)
```js
type Sometype = {
  stringField: string,
  numberField: number,
}

type ShapeOfSometype = {...$Shape<Sometype> , [any]: empty  }

const emptyshape: ShapeOfSometype = {} // No errors!
const shapeWithString: ShapeOfSometype = { stringField: "string content" } // No errors!
const shapeWithNumber: ShapeOfSometype = { numberField: 42 } // No errors!


const n:number = emptyshape.numberField; // error
const s:string = emptyshape.stringField; // error
shapeWithNumber.stringField.toLowerCase(); // error

// Correct way to check it before using string methods
if (shapeWithNumber.stringField) {
  shapeWithNumber.stringField.toLowerCase();
}
```

**Comment by eoingroat** [comment]
This is a big issue for us, the behaviour linked in the docs was the assumed behaviour - it also makes the most sense - and was in reasonably widespread use across our codebase.

For simplicity here are two try flow links simply showing the issue and a workaround. A fix would be lovely.

[Issue (try flow link):
](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6oCQAhgFxgDOGATgJYB2A5gNyoC+fVFACuHAMYY2cDmCgAKAG4MAJAGUAFjXwAeQgD4AlA2KUqLPBhEtZinmGDAwAFQ1tGyRhrgiYAE3AMDRZEMBpZPBYQlgAaMAAjEQwwNmS-ODxGDgByDAEgA)
```
/* @flow */

type A = {
	a: string;
};

function f(v: $Shape<A>): A {
	return v; // This *should* throw an error, but it doesn't
}
```

[Workaround (try flow link):](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgB54AmAygBYCG+APACoB8YAvGAN6oCQAOiEASWgzwtWAGlRgwfANp0AdlgC6ALjDZ8cKGACuyinijFllGQF90OggEFOPfnS0BnDACdzAcwDcqFYBqFBGAMYYxHDKYFAAFABuWiTk1PRM9qwAlFqOvHJywMBgwgCipPgRpZ6ecJ78nngYBp4xCX5gRWDMNMRuyG40cAYwFOAYNLVIKmB4NXVSYCoUYMQYYBRweG6BQA)
```
/* @flow */

type FixedShape<T> = {
	...$Shape<T>,
  	[any]: typeof undefined,
}

type A = {
	a: string;
};

function f(v: FixedShape<A>): A {
    // $ExpectError
	return v; // This *should* throw an error, and it does
}
```

Note that we have chosen to use `[any]: typeof undefined` instead of `[any]: empty` because :
* it is undefined
* flow's concept of empty's behaviour in short circuiting of booleans does not match undefined

**Comment by oonsamyi** [comment]
[Workaround (try flow link):](https://flow.org/try/#0C4TwDgpgBAyg9gWwqSUC8UDeAoKUDOwATgJYB2A5gGIkQA2AJgFwHHkUA0uUZArggCMIRGvWY9+QolwC+2bCmgwAFgENIAeQBm8JIvRQAJACUIhADy7k4CBywyAfPIDGcMoSgQEYUPjWQWFXUIbSt9DEwZKAB6aKgAOThPIiI4InwAQmxXd2ACfwgAdRJgZRg2SkCC0MRrVAjWUkpRRhYAIkImiigc4AgyYDaoKNiEpOFU9Kycjz9g4tL4yWEq4Jq9GwNMCUFhFvEAFgAmYZi4xOTJzPlRgGFVfGgAdxLlKF4yBggtcggGRvYUB+YigbVUbS4owEvDyWjocCeUAYcDMZAA5Hl8KoQPgoKoyCBSoDVAI4DCJHQ6M5lBBnABrLJzSALZRLXZEAB0nXY+w5wDgABkEcJ7o8ABQASgA3Dc4rc0kRaXkntioPyejT6VASlAhFo0tBePhAdzKFA9Mo4Ax8NgSFooGKmUVXmypFyKtRaIwJVhuE6Wa7hO6urz+UKniKHhBJTK5EA)
`type $SaveShape<O> = $Rest<O, {}>`

**Comment by gkz** [comment]
Errors if you use the safe replacement, `$Partial`: https://flow.org/try/#0C4TwDgpgBAyg9gWwqSUC8UDeAoKUDOwATgJYB2A5gGIkQA2AJgFwHHkUA0uUZArggCMIRGvWY9+QolwC+2bCmgwAFgENIAeQBm8JIvRQAJAAVVRYCVV0APLuTgIAPnkBjOGUJQICMKHxrIFhV1CG07fQxMGSgAehioADk4LyIiOCJ8AEJsNw9gAgCIAHUSYGUYNkogwrDEe1RI1lJKUUYWACJCZoooXOAIMmB2qGi4xOThNIzs3M9-EJKyhMlhapDavQcDTAlBYVbxABYAJhHY+KSUqaz5MYBhVXxoAHdS5SheMgYILXIIBia7CgvzEUHaqnaXDGAl4+S0dDgzygDDgEHwZAA5Pl8KoQPgoKoyCAykDVAI4LCJHQ6C5lBAXABrbLzSCLZTLPZEAB0XXYBy5wDgABlEcIHk8ABQASgA3Ld4nd0kR6flnrioILenTGVBSlAhFp0tBePggbzKFA9Mo4Ax8NgSFooBKWcU3hypDzKtRaIwpVhuC62e7hJ7uvzBSLnmLHhBpXK5EA

https://flow.org/en/docs/types/utilities/#toc-partial
