### ISSUE TITLE
[React] Flow loses the inferred type of imported functions when using typeof inside Component<Props>

### ISSUE THREAD

**Issue by ggregoire** [facebook/flow#6797]
Edit: [last update on this: it appears only when 'action' is imported](https://github.com/facebook/flow/issues/6797#issuecomment-416657143).

--

I don't know if I'm doing something wrong or if it's a bug, but it looks pretty straightforward:

```javascript
import { action } from 'somewhere'

// action: (param1: string) => {| type: string, param1: string |}

const actions = {
  action
}

type Props = typeof actions

class MyComponent extends Component<Props> {
  componentDidMount() {
    this.props.action(1, 2, 3) // No errors when I run 'flow check'!
  }
}
```

**Flow correctly infers the type of the function outside of the component**. But, once it is passed to the component (`this.props.action`), it becomes `any`.

I also tried, without success:

```javascript
type Actions = typeof actions

type Props = Actions
type Props = {} & Actions
type Props = { ...Actions }
type Props = {| ...Actions |}
```

**Comment by ggregoire** [comment]
Maybe it was not clear, so here is another example:

```javascript
import { action } from 'somewhere'

// action: (param1: string) => {| type: string, param1: string |}

action(1, 2, 3)
// Error 1: Cannot call `action` with `1` bound to `param1` because number [1] is incompatible with string [2]
// Error 2: Cannot call `action` because no more than 1 argument is expected by function [1]
// so Flow is catching all the errors as expected

const actions = {
  action
}

type Actions = typeof actions

type Props = {|
  ...Actions,
  otherProp: string, 
|}

class MyComponent extends Component<Props> {
  componentDidMount() {
    this.props.action(1, 2, 3)
    // No errors! Flow is not catching anything.
    // But it's the exact same function, passed through the Props
  }
}
```

So, either I'm not typing the Props correctly, either there is a bug somewhere.

**Comment by AlicanC** [comment]
I'd try doing:
```javascript
type Props = {|
  ...$Exact<Actions>,
  otherProp: string, 
|}
```

**Comment by ggregoire** [comment]
So I just discovered that it's actually because `action` is imported.

I was trying to reproduce the bug on flow.org/try but it works as expected when it is in the same file: https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowFDtqkDO86MYKTgBeOAAowKKChABGAFxw+UYCQDmASlEA+CXhgBPMEiWMAgvgAqASQDyAOUbYpM+XEqbOAoSXFzsACZsAGYvdiMTOAAFejAeUVwAHzgAOnTzDF8EpMpONAAbFB4EgDEICDgkAA8YcgATBMJiMgoAHliIeL0cdjg4bhbyGAARYHqAWQgAVwpxbV7+-pgAC2AeVLA4jZ9SfyDQr368vK5efizeRMW4XZIlh8en55el9lPIpDhMwSuxT4gNFulxIPCAA

I also confirm that the type of the imported `action` is correctly inferred **out of the component's props**:

```javascript
import { action } from '../state/actions'

const mapActionsToProps = {
  action
}

type Actions = typeof mapActionsToProps

type Props = {| ...Actions |}

class MyComponent extends Component<Props> {
  componentDidMount() {
    action(1, 2, 3) // Error 1: Cannot call `action` with `1` bound to `param1` because number [1] is incompatible with string [2]
                   // Error 2: Cannot call `action` because no more than 1 argument is expected by function [1]

    this.props.action(1, 2, 3) // No errors!
  }
}
```

**Comment by ggregoire** [comment]
@kangax No I didn't find any workaround. I write the type of every action that I pass to my components… like

```javascript
type Props = {|
  action: (param1: string) => {| type: string, param1: string |},
  action2: () => void,
  // and so on…
|}

class MyComponent extends Component<Props> { ... }
```

**Comment by kangax** [comment]
@ggregoire I'm seeing a similar issue where props lose their types:

The shape seems to be determined properly:

<img width="555" alt="screen shot 2018-10-16 at 12 55 42" src="https://user-images.githubusercontent.com/383/47033463-e1bb5f00-d142-11e8-85e3-f30d72d471d2.png">

But the 2nd level props are `any`:

<img width="558" alt="screen shot 2018-10-16 at 12 53 05" src="https://user-images.githubusercontent.com/383/47033424-c51f2700-d142-11e8-8d58-96cd198a0ba6.png">

I also checked with `type-at-pos` and it's consistent with what I'm seeing in VSCode:

```sh
➜  git:(master) ✗ flow type-at-pos app/scripts/xxx.jsx 10 27
{byUuid: {[string]: Array<Ticket>}, error: mixed, loaded: boolean, loading: boolean}

➜  git:(master) ✗ flow type-at-pos app/scripts/xxx.jsx 10 37
any
```

It's pretty bizarre how Flow recognizes this shape correctly but then reports property's value **in the same expression** as `any`. Perhaps some kind of internal shape caching?

@mroch any hints on what this could be?

**Comment by kangax** [comment]
@ggregoire I felt it might be the same issue because:

- if I remove `connect`, `loaded` is determined correctly
- if I remove spreading (`type Props = ReduxProps`) `loaded` is determined correctly

In my case, however, importing GlobalState or defining it locally doesn't make a difference.

**Comment by MartinCerny-awin** [comment]
I think that this bug is similar to issues https://github.com/facebook/flow/issues/7071 and https://github.com/facebook/flow/issues/4312

**Comment by dfroger** [comment]
@MartinCerny-awin  Thanks for this very usefull feedback! I'll keep an eye on this issues...

**Comment by SamChou19815** [comment]
These import related issues should be resolved a long time ago since types first
