### ISSUE TITLE
Minus operator with union types

### ISSUE THREAD

**Issue by mees-** [facebook/flow#6798]
I encountered an error in typechecking

```js
let a: 1 | 2 | 3 = 1
let b: 0 | 1 | 2 | 3 = a - 1
```
this should work but it gives an error:
```
Cannot assign a - 1 to b because:
 • Either number [1] is incompatible with number literal 0 [2].
 • Or number [1] is incompatible with number literal 1 [3].
 • Or number [1] is incompatible with number literal 2 [4].
 • Or number [1] is incompatible with number literal 3 [5].

                 169│ }
                 170│
                 171│ let a: 1 | 2 | 3 = 1
 [2][3][4][5][1] 172│ let b: 0 | 1 | 2 | 3 = a - 1
                 173│
```

**Comment by wchargin** [comment]
Flow does not understand type-level arithmetic on number-literal types
(or type-level concatenation of string-literal types, or most type-level
logical operations on boolean-literal types).

Literal types are meant to be treated as atomic units, not to be
manipulated at runtime.

An even simpler example is:

```js
const x: 1 = 1;
const y: 2 = x + 1;  // error
```

Or even:

```js
const z: 2 = 1 + 1;  // error
```

Is there a more complete example that you can share to indicate _why_
you want this functionality?

(Related: #6789.)

**Comment by mees-** [comment]
I have a function that takes two coordinates within a range and returns coordinates next to that position, the coordinates next to it can't be typed as my `Position` type because of the substraction

```js
type Position = {
  x: 0 | 1 | 2 | 3,
  y: 0 | 1 | 2 | 3,
}

({x, y}: Position): Position => ({ x, y: y - 1})
```
this is giving me the error, because the return type of the function isn't seen as a `Position`.
I have also tried the following to make sure that y never becomes `-1`:
```js
type Position = {
  x: 0 | 1 | 2 | 3,
  y: 0 | 1 | 2 | 3,
}

type PositionExceptTop = {
  x: 0 | 1 | 2 | 3,
  y: 1 | 2 | 3,
}

({x, y}: PositionExceptTop): Position => ({ x, y: y - 1})
```

but this gives me the same error that is also mentioned above

**Comment by wchargin** [comment]
Right. You’re trying to represent an ordinal data type as a union of
literals. There’s nothing wrong with that—it’s a reasonable thing to
want—but Flow wasn’t designed with that in mind: literals are meant to
represent categorical types, not ordinals.

Beyond the obvious [explicit conditional structure][1]

```js
// @flow
type Position = {
  x: 0 | 1 | 2 | 3,
  y: 0 | 1 | 2 | 3
};

type PositionExceptTop = {
  x: 0 | 1 | 2 | 3,
  y: 1 | 2 | 3
};

({ x, y }: PositionExceptTop): Position => ({
  x,
  y: (() => {
    switch (y) {
      case 1: return 0;
      case 2: return 1;
      case 3: return 2;
      default: throw new Error((y: empty));
    }
  })()
});
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagAqwM4CWyhsAdqALygDeiooAHgFygAMoAPqAIxegAmfgGYANPVCpWHbn25DuwxAF8A3IhQZseIiXIBRRgGNM6ZABVY6KrQkt2-OYJHiGU3vwWglajQAoaJlFJUGVWHWJSMkMTM0t0AEpwgkjyKgA+UAC7V0lWPz8EjNsGBnx4YiMACyzUIrpS0qMAQ3xsHlYAJ0xkAFdOijZ1RoYWtsEunv6KHmGRsexhSb6BwTnGgBNMSGbe6GRWZCrOhFAyTHhQfU6TzoL3TABbMzqE9dCJZQTClTfEIA

or an `any`-cast, I don’t think that Flow has any solutions to the
problem that you pose.

**Comment by mees-** [comment]
Alright, the conditional seems fine. I'll close the issue now. Thanks for your help @wchargin
