### ISSUE TITLE
Null check via helper function doesn't register as null check to Flow.

### ISSUE THREAD

**Issue by kkirby** [facebook/flow#680]
As the title tries to explain, if you are doing a null check via a helper function, Flow doesn't recognize it as a null check. So if you try to access the property that you're null checking, a type error is thrown.

```javascript
/* @flow */

function func(val:string){}

class Struct {
	prop:?string;
}

// This doesn't work.
function checkEmpty(struct:Struct){
	if(empty(struct.prop))throw new Error('prop is empty.');
	func(struct.prop);
}

// This doesn't work.
function checkNegateEmpty(struct:Struct){
	if(!empty(struct.prop)){
		func(struct.prop);
	}
}

// This works
function manualEmptyCheckThrow(struct:Struct){
	if(struct.prop == null)throw new Error('prop is empty');
	func(struct.prop);
}

// This works
function manualEmptyCheck(struct:Struct){
	if(struct.prop != null){
		func(struct.prop);
	}
}
```

The use case is that I want to check if a value is empty. The real logic for such a function is:

```javascript
function empty(val){
	return (
		val === undefined ||
		val === null ||
		typeof val.length !== 'undefined' && val.length == 0;
	);
}
```

But I simplified it for the example above.

**Comment by samwgoldman** [comment]
It's not currently possible to write a function that refines types like this, but there is an open issue for this which has seen a recent proposal. I'm closing this to merge with #34 instead. Thanks for the very detailed issue!
