### ISSUE TITLE
[bug] Interface allows any function type

### ISSUE THREAD

**Issue by lrowe** [facebook/flow#6802]
I ran into this bug refactoring where flow did not detect that I was passing a method of an interface argument rather than the interface argument itself.

```js
// @flow
"use strict";

interface IFoo {
  foo(): void;
}

type TFoo = {
  foo(): void
};

class Foo implements IFoo {
  foo(): void {}
}

function useIFoo(fooish: IFoo): void {
  return fooish.foo();
}

function useTFoo(fooish: TFoo): void {
  return fooish.foo();
}

const afoo = new Foo();

// Errors as expected
useTFoo(afoo.foo);

// but this does not error
useIFoo(afoo.foo);

// Errors as expected
useIFoo((a: number): string => String(a));

// but this does not error
declare var f: (a: number) => string;
useIFoo(f);
```
[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAiArgZwKanQFwE4CWAxrsgNyKKEB2um+kAhsdgJIBissoA3oqFCRuACgCUALlAA3WIQAmlAL5VcATwAO2ACpceAXj4ChoyTLnzESyomLQm6dKD2hCAWw3RMbzHSeduI0FhWHEpWQU+FRVESFQaUkJYGlAMTADQkMJ0AAspDLMI+SDQfExcVHwUrNyAOhDxZSo4hNwklLTdURq80C7YQosSsoqqkzk6hrEm22S8UCYQ0EMaTHhnUxsQUABRfHxYfCcHUEwADy1STEtOvRFF7nruaaptgCNUXFBcHOzQeVgmCcNFgXwYB3wiDSGXuISeAy2YD2EOOTnOl3oNywMPuUhoqDcbwYZjwRBoAHNlgA+UAAZQItHJ9zEL0Q70+31+TgBQNAILB+0OiHkmDsTDKMnFQikuL5BKJ+DE1JwDIplGhd0gLyAA)

**Comment by wchargin** [comment]
This may well be related to #6490. In particular, the underlying problem
seems to be that [Flow thinks that a function of type `() => void` in
fact _is_ an `IFoo`][1]:

```js
// @flow
interface IFoo {
  foo(): void;
}
const f: () => void = () => {};
(f: IFoo);  // no error!
f.foo();  // also no error!
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUASQDFZZQBvRUUSSgCgEoAuUAN1mQBMBuRAF9EBWKgDO6Bh1agAvAD4uPXgtBylNIYKaQO5Si370QoVFRzZY2AISJIAOkaxWJ0GbzQJVC6Cs29kA

**Comment by goodmind** [comment]
[This now doesn't error only on methods](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUASQDFZZQBvRUUSSgCgEoAuUAN1mQBMBuRAF9EBaHgDOE0GRp1QE9HnTICDVh258aIkUzIA6SB3KUW-eiFCoqObLGwBCRIchHm5y2DzQJVG6B2Do5AA)
```js
// @flow
interface IFoo {
  foo(): void;
}
class F {
  static f(): void {}
}
(F.f: IFoo);  // no error!
F.f.foo();  // also no error!
```

**Comment by SamChou19815** [comment]
Now all of them error as expected
