### ISSUE TITLE
wrong return type for setAAD method in node.js cipher class

### ISSUE THREAD

**Issue by farzonl** [facebook/flow#6804]
[cipher.setAAD
](https://nodejs.org/api/crypto.html#crypto_cipher_setaad_buffer_options) is suppose to return a Cipher class instance, flow thinks it returns nothing

ex.
    [/private/tmp/flow/flowlib_13846dd/node.js](https://github.com/facebook/flow/blob/master/lib/node.js#L358)
 [1] 358│   setAAD(buffer: Buffer): void;

**Comment by mrkev** [comment]
Solving in #6849.

Seems like a simple enough issue. I'll close this; feel free to track progress and follow up on the PR.

**Comment by farzonl** [comment]
Hey cool, thank you!
