### ISSUE TITLE
Flow not recognizing safe type transitions inside of lambdas

### ISSUE THREAD

**Issue by aikar** [facebook/flow#6807]
I am ensuring that when a Function is passed to the method, it is converted to its name.

So this method lets you pass a direct reference to a method or the methods name itself.
We prefer method reference so "Find usages of method" is usable in the IDE.

Flow should see that by the the time the lambda is hit, that method has no potential to not be a string.

![screenshot at 13-57-29](https://user-images.githubusercontent.com/58008/44741178-56bad280-aaca-11e8-8209-dea20173e14e.png)

Flow 79

**Comment by mrkev** [comment]
A [flow.org/try](https://flow.org/try) would be much preferred next time. I wanna play with this but I'd have to type the whole thing down, hard to do so while on the run.
