### ISSUE TITLE
Array of tuples

### ISSUE THREAD

**Issue by martahj** [facebook/flow#6809]
Hello,

I'm trying to define a type that is an array of tuples. My use case is an array of [x, y] points on a map. 

```js
/* @flow */

type MyTupleType = [number, number];
type MyArrayType = Array<MyTupleType>;

````

When I run this code, however, I get the following error:
```
MyArrayType [1] has an unknown number of elements, so is incompatible with MyTupleType [2] in array element.
```

I understand why you cannot assign a value that was previously declared an array to a tuple variable or visa versa, but I'm having trouble understanding why you can't have an array of tuples. Any thoughts on this, and what would be a better implementation?

**Comment by M-TGH** [comment]
It looks to be working as expected when tried on [flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAKgK44x4m4EC8YA2gHZkC2ARngE4A0YrTjwC6Abky0iWAILduAQ1KSGshVgA8xcpWq0AfONQBjOMwDOGMPLkAuKasU18YBo0YBWABz8A7MP6MAEwAzPwALABswmJAA).

Looking at the error, it occurs when the Array is cast to the Tuple, alike this:
```js
/* @flow */

type MyTupleType = [number, number];
type MyArrayType = Array<MyTupleType>;

const arr: MyArrayType = [];
const tuple: MyTupleType = arr; // Error , Array can't be cast to Tuple
```
Here's a [flow/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAKgK44x4m4EC8YA2gHZkC2ARngE4A0YrTjwC6Abky0iWAILduAQ1KSGshVgA8xcpWq0AfONTBgYaQBMzYDBSpW4YeXMWoAxnGYBnDA6dYAXFKqijT4YAyMYqiOagB0OGQeABYAFIwAjLwATMIAlOLGYAAkAKIAHvguGMVycNwCcN7xSQCWzADmDmBucniVVjZ4flG+cQkpjADM-ADkAHLys9O5hgUl5b1VNXVBWHb9Oq7uXj7cAcQ7IfRMkW6e3tY6Z6QDl2EnokA) showcasing the error.
