### ISSUE TITLE
Flow errors on possible downcast.

### ISSUE THREAD

**Issue by kkirby** [facebook/flow#681]
If you have an object type definition that says one property has to not be `null`, and another type definition where the property can be `null`, Flow will say the types are incompatible if you go from the never null to the maybe null.

Example:

```javascript
/* @flow */
type MaybeNull = {
	prop: ?string
};

type NotNull = {
	prop: string
};

function neverNull(struct:NotNull){
	/**
	 * This should work since the `prop` value
	 * in the structure is guranteed to not be
	 * null. But Flow says it's incompatable
	 * with the `MaybeNull` type.
	 */
	maybeNull(struct)
}

function maybeNull(struct:MaybeNull){}
```

This is what Flow errors out with:

	test.js:11:2,18: function call
	Error:
	test.js:3:9,14: null
	This type is incompatible with
	test.js:7:8,13: string

	test.js:11:2,18: function call
	Error:
	test.js:3:9,14: undefined
	This type is incompatible with
	test.js:7:8,13: string

**Comment by mroch** [comment]
here's why flow doesn't allow this:

```
function maybeNull(struct:MaybeNull) {
  struct.prop = null; // totally valid
}

function neverNull(struct:NotNull): string {
  maybeNull(struct);
  return struct.prop; // this is null!
}
```

Flow doesn't do any sort of analysis to know whether or not `maybeNull` mutates the object (yet), so right now it's conservative.
