### ISSUE TITLE
Declaring an unitialized class property.

### ISSUE THREAD

**Issue by nicolo-ribaudo** [facebook/flow#6811]
Suppose I have an existing project to which I am adding flow types:

```js
// Original project:

class Foo {
  x = 2;
  y = 3;
}

class Bar extends Foo {
  x;

  sum() {
    const sum = (this.x || 5) + this.y;
    console.log(sum);
  }
}

new Bar().sum(); // Logs 8 (5 + 3);
```

```js
// With types:

class Foo {
  x: ?number = 2;
  y: number = 3;
}

class Bar extends Foo {
  // *

  sum() {
    const sum: number = (this.x || 5) + this.y;
    console.log(sum);
  }
}

new Bar().sum(); // Should log 8 (5 + 3);
```

\* I want to say that the `Bar` class has:
 - an `x` property whose type is `?number` and that is part of the JS code
 - an `y` property whose type is `number` and that isn't part of the JS code.

How can I differentiate the two cases?

**Comment by allex** [comment]
yyyy, i also prefer to strip these code w/o initial value.

**Comment by goodmind** [comment]
Comment syntax would work
```js
class Bar extends Foo {
  x: ?number;
  /*:: y: number; */
}
```

**Comment by nicolo-ribaudo** [comment]
I don't think that it is a solution: it would be the only place where a flow comment has a different behavior that a non-comment type annotation.

**Comment by mroch** [comment]
we don't want people to be forced to use the comment syntax, so we're going to implement the `declare` syntax.

**Comment by nicolo-ribaudo** [comment]
Thanks! :heart: :heart: :heart: 

We would like to release Babel 8 in March (we don't have an ETA yet, but it won't definitely be in the first half of the month).
In Babel 8, we are going to stop removing uninitialized class fields and so far we have been recommending the comment syntax to migrate to something that will be compatible with the new major version.

If you have any ETA, I could start working on the `declare` syntax in Babel so that, if you release it in Flow soon, we will be able to ship it in Babel 8.0.0.
