### ISSUE TITLE
Automatic type annotation on Arrays / Matrix seems to get confused

### ISSUE THREAD

**Issue by piuccio** [facebook/flow#6815]
Sorry guys, I'm just learning how to use flow but I'm stuck with this code. I extracted it from cytoscape and removed as much as possible to keep the bug visible, don't expect the code to have much meaning.

[Flow try](https://flow.org/try/#0C4TwDgpgBAogJgc2gXigbwFBSgMwE4D2AtgFxQDOweAlgHYIA0WUwBZlN9T2w1REZWgFciAIwh4mAXwyhIUAHIE4EcgBlqlKKgCCePAEMQAHg50EAPgDcs8NHhJ1m4Nqh7DJhxGsYMEAB5gBHjA5AB0OAA2BCBwAOoGeOQAFgaRka4AFLTKqmRKKk6UDFAQiHmw5UXAAJTaFujMAMYEtFrCRAWqrjmFYZEQ9MDJNswA9GNQAJK01Lxp1ABe0EQGVNT+UELkZbjBUGBryVB4EC1tVEJNvK3jkzNz1AvLUHDOBrRNK2s0-s2t7QCLlQAG0ALo2bDnLRlJAKIGucGjKEAlx0OYAWR+G1cOCEnxutCg6OAWPW-kyiQ8dUw2GwOH2mQGaNcAAYrMSoMYoB0uuQOdQANSCmnMOlQKlGMJgbbJTLgmqQukybBSZHE2ak7EU2hAxXMElk36ZWEQeH+WrqiZQAAKhC+5HIpSqzAZeCgTIgLNQ7M53NN4QGQxGxOFovF0Jc5AIQjwXxmKk2qAAjEqURcWIkkMAEwFXKnfGKeUCQdHY-HaImwSDgFmvbn-GDXLW8NmG2nnXCS2W4xAG9WW23KwEm6gAyDqBDmDJ-hnTk7ULS6YdhmRMvhiOx1lwWGwKNuEHVkA0l+LmbhCEQG-mO9hz6xr6gAEzqs9eg6nABuuMv7aL2AAd2SagBg9Dcr2HTYAEJkFQB9IPDcVly-H9iD-JC6XAx9iwtEEsMggcCH7W8oBVZVp3VU5gFjIl5xsGQgA)

The gist is

I initialize two arrays
```js
  const next = [];
  const edgeNext = [];
```

and then I have a function that creates a matrix
```js
function initMatrix(array) {
    for (let i = 0; i < numNodes; i++) {
      array.push([]);
    }
  };
```

When I populate the two matrices with different types

```js
initMatrix(next);
initMatrix(edgeNext);

next[1][1] = 1;
edgeNext[1][1] = { edge: 1 };
```

The type system will say that both of them are `Array<Array<Edge | number>>` while I expect

`next` to be `Array<Array<number>>`
`edgeNext` to be `Array<Array<Edge>>`

Maybe there's something I'm doing wrong or the issue was already reported, again I'm new to flow and a bit lost, didn't even know how to search for this in the issues list.

If you have missed it, the link to reproduce is [here](https://flow.org/try/#0C4TwDgpgBAogJgc2gXigbwFBSgMwE4D2AtgFxQDOweAlgHYIA0WUwBZlN9T2w1REZWgFciAIwh4mAXwyhIUAHIE4EcgBlqlKKgCCePAEMQAHg50EAPgDcs8NHhJ1m4Nqh7DJhxGsYMEAB5gBHjA5AB0OAA2BCBwAOoGeOQAFgaRka4AFLTKqmRKKk6UDFAQiHmw5UXAAJTaFujMAMYEtFrCRAWqrjmFYZEQ9MDJNswA9GNQAJK01Lxp1ABe0EQGVNT+UELkZbjBUGBryVB4EC1tVEJNvK3jkzNz1AvLUHDOBrRNK2s0-s2t7QCLlQAG0ALo2bDnLRlJAKIGucGjKEAlx0OYAWR+G1cOCEnxutCg6OAWPW-kyiQ8dUw2GwOH2mQGaNcAAYrMSoMYoB0uuQOdQANSCmnMOlQKlGMJgbbJTLgmqQukybBSZHE2ak7EU2hAxXMElk36ZWEQeH+WrqiZQAAKhC+5HIpSqzAZeCgTIgLNQ7M53NN4QGQxGxOFovF0Jc5AIQjwXxmKk2qAAjEqURcWIkkMAEwFXKnfGKeUCQdHY-HaImwSDgFmvbn-GDXLW8NmG2nnXCS2W4xAG9WW23KwEm6gAyDqBDmDJ-hnTk7ULS6YdhmRMvhiOx1lwWGwKNuEHVkA0l+LmbhCEQG-mO9hz6xr6gAEzqs9eg6nABuuMv7aL2AAd2SagBg9Dcr2HTYAEJkFQB9IPDcVly-H9iD-JC6XAx9iwtEEsMggcCH7W8oBVZVp3VU5gFjIl5xsGQgA)

**Comment by wchargin** [comment]
Solve this by annotating the type of `initMatrix`:

```js
const initMatrix = function initMatrix<T>(array: T[][]) {
  // …
};
```

As described in the docs, [Flow does not infer generic types][docs].

[docs]: https://flow.org/en/docs/types/generics/

**Comment by piuccio** [comment]
Sweet thank you. For reference, I ended up writing it like this because I'm using the comment syntax

```js
  const initMatrix = /*:: <T> */(array/*: T[][] */) => {
    // ...
  };
```
