### ISSUE TITLE
React render() cannot return undefined: React$Node shouldn't be undefined 

### ISSUE THREAD

**Issue by Ojisama** [facebook/flow#6818]
Hello! 

Small problem we stumbled upon while developing: In React, the `render()` method of a `React.Component` does not accept undefined. 

However, in Flow, the `render()` method returns a `React$Node`, which can be `void` (=`undefined` ? I'm not sure of that).

#### Minimal Working Example:

```jsx
const UndefinedComponent = () => undefined;
```
When you render it:

![image](https://user-images.githubusercontent.com/25685118/44851732-8d772100-ac61-11e8-9ff5-f70c094f976e.png)

But as you can see on [this Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50qYKBnPmADCDPADsyYwuTEATMvgCqcslAwTZYMgA9Ck2YPLVCAEhG44EqQB4QAPjABvMKxX4wAXjAAKAJSeHAFcVNQ0wAF8gA), Flow doesn't pick it up.

The simplest solution is to remove `  | void ` from the `React$Node` type declaration. (`lib/react.js`, l.13)
May I open a PR to fix that, or is there another way to do it to prevent side effects?

Thanks :smiley: 

---

Environment:

| lib | version | 
| ------------------------------ | ------------------- | 
| Flow                    | 0.79.1         | 
| React                    | 16.3.2         |

**Comment by jbrown215** [comment]
Please do open a PR! I'm not entirely familiar with our react typings myself, but changes to our libs usually get more attention than our issues
