### ISSUE TITLE
Implement $Compose and $ComposeReverse functions

### ISSUE THREAD

**Issue by mgtitimoli** [facebook/flow#6820]
I was expecting to be able to use `$Compose` and `$ComposeReverse` to type `compose` and `pipe` respectively, but I got errors.

- [compose](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqFBDaaAVXXwCcBPUAXlAAoKBzAGlEnQEpaA+d9RuSacA3MjRZcaALYAHWJgCmALlAASAMKw5CxbQYA6IwFcyVAGJZuNPs16JQoUxUqXMB8ooAmxlIoBKAJZMABbY9AREpC5szKLIigAe8uS4XoqQ+MbQUtrySiJAA)
- [pipe](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqFBDaaAVXXwCcBPUAXlAAoKBzAGlEnQEpaA+d9RuSacA3MjRZcABwCWUgKYAuUABIAwrAC2U2JnkAleQDd55PbQYA6awFcyVAGJZuNPs16JQoOxUpPMluTyACY2KPL0BESkvmzMosjyAB465LjB8pD4NtDScvJiQA)

**Comment by mgtitimoli** [comment]
@calebmer is there a chance I can get a feedback from you on this one, thanks!

**Comment by istarkov** [comment]
You are doing it wrong ;-)

To declare your own function which will be able to be typed as $Compose you need to know all the types of all the internal composable functions, see how Compose was declared in a time before $Compose 
https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/recompose_v0.x.x/flow_v0.47.x-v0.52.x/recompose_v0.x.x.js#L69

So the problem that in your code no algorithm will be able to infere right types for infinite number of arguments. So what you can do.
The simplest way is [here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqFBDaaAVXXwCcBPUAXlAAoKBzAGlEnQEpaA+d9RuSacA3MjRZcaALYAHWJgCmALlAASAMKw5CxbQb16AOhMBXMlQBiWbjT7NeiUKHMVK1zEfKKAJqZSKAEoAlkwAFtj0BESkbmzMnJzK+OiUosggoPCw5ADWmKja8kr0AB52paAA1KAATGyVdqCVAFR1nPQAjOmImdhh5AiYoPjD3oR4RbqFOiXlPJU19c28K221HQDkmz2IiqXy5Lg+ipD4ptBSU0oiQA)
explicit cast to any and then to $Compose

**Comment by mgtitimoli** [comment]
hey @istarkov, thanks to jump into this issue :)

Definitely typing to any will fix the issue, but what you are saying is not true for other types, what I'm trying to say is that if you have a type you can assign it to a variable and that defines all the types at the right of the assignment, this is, in the expression you are assigning to that variable.

The problem with both `$Compose` and `$ComposeReverse` is that, as I have shown in the example, if you try to do this, then you got an error, and this IMO is triggered by a potential difference between the two signatures, the ones from the types, and the ones from the implementations.

Does this make sense?

**Comment by istarkov** [comment]
Let's move on with functions with finite set of args
So let's start with function subtyping
```
// this works `number=>number` subtype of `(number, number) => number`
const fn: (number, number) => number = (a: number) => 1;
// not work
const fn: (number, number) => number = (a: number, b: number, c: number) => 1;
```
now imagine both functions have infinite number of arguments, inifinitity is not equal or greater or less than inifinity, how algorithm can detect which infinity has more power ;-) ?

Now let's about Compose itself
Algorithm would be able to resolve right side iif left side also have defined types, but in your case it's not, $Compose is created to infer data from function argument at right.
See example:
```
// Similar to $Compose in flow 
type Compose = <A, B>(bc: (A) => B) => A => B;
// THIS will not work, no types to infer
const comp1: Compose = a => b => a(b);
// BUT very useful for situations like
const myCompose:Compose = (null:any);
// See here x is infered and has type of argument (number)
myCompose(x => 1)(2);

// But if you will declare Compose like here
type Compose2<A, B> = (bc: (A) => B) => A => B;
// This will work and types at right will be infered, as algorithm knows them
const comp2: Compose2<number, number> = a => c => a(c);
```

I think this is enough ;-)

**Comment by SamChou19815** [comment]
The types are designed to be used in libdefs. We don't provide a way to ensure that your implementation actually conforms to it, so we always error
