### ISSUE TITLE
Flow does not typecheck properly when overwriting a key in an object

### ISSUE THREAD

**Issue by csakai** [facebook/flow#6821]
I have an object where I want to fill in a field with dynamically picked data. When I destructure the input object and overwrite the non-matching property, Flow complains that I am trying to pass in the wrong data-type.

When I explicitly destructure the input parameter to exclude the non-matching value, flow throws no errors.

I initially thought that it was because my method of picking the dynamically generated data was not explicit, but even when explicitly typing the transform function, it still complains.

For example: 
```
type Foo = {
  a: string,
  b: string
}

type Bar = {
  a: number,
  b: string
}

type Baz = {
  ...Foo,
  a: number
}

const getName = (arr: string[], index: number): string => {
  if (arr.length > index) {
    return arr[index];
  }
  const randomIndex = Math.floor(Math.random() * arr.length);
  return arr[randomIndex];
};

// pretend I got this string array from some API
const names = [ 'a', 'b', 'c', 'd' ];

// flow complains:
// "Cannot return object literal because number [1] is incompatible with string [2] in property `a`."
const transformBazToFoo = (baz: Baz, namesArr: string[]): Foo => ({
  ...baz,
  a: getName(namesArr, baz.a),
});

// flow still complains:
// "Cannot return object literal because number [1] is incompatible with string [2] in property `a`."
const transformBarToFoo = (bar: Bar, namesArr: string[]): Foo => ({
  ...bar,
  a: getName(namesArr, bar.a),
});

// works fine
const transformBarToFooExplicit = (bar: Bar, namesArr: string[]): Foo => {
  const { a, ...bazn } = bar;
  return {
    ...bazn,
    a: getName(namesArr, bar.a),
  };
};
```

I have reproduced the bug here: https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMAaTKAI3yLKvQF911RIoAhbYsjR08UcgFcAtvQjFaWRoRIVK7TgGM45IlEoRgAOWyToKABQDiTZVQDaAXWpQKAEwgAPfBOmyAlNZZKZAA+YSxSADMoC2JiADoAGwgqYAALKFDXD18wrChifXFichxY2yz3ewBuOg4sTW1gfOxyFzhJAElWjyEAWWw0uIiEhGIzfsHiFrbJMxyAKlL4pJTU3xqsAuAikstbKdb2rrdKmrYa9AadcmMIAiFbKABybCenJ-o35-Uvp5cnqDVTgAemBUGGcAA7lBNJIwAlsBQCJctDoSC0CBE4MRJPxiAAVODwRDmegCfB4pw3EwEACCsQCKgc-lgCBC0QwWDi3LJchE+D0hluZmpd3pcgYAji2F8tDY6xBYMh2IA1vcIhQICjGlB0dosTi8YTiQBRdzw0jqUhNUnkvgCKm3OkMpSBZn4Ynszkw1FNVA4JzcuJkgBeUDYQl5G3yhWKuS5POwIfkeVEgqMJhFTvFTl50tltTOVSAA

**Comment by csakai** [comment]
Upon further inspection, this has nothing to do with object destructuring, but rather has to do with assigning multiple values to the same key in an object (which is perfectly valid javascript). Have a look here: https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMAaTKAI3yLKvQF911RIoAhbYsjR08UcgFcAtvQjFaWRoRIVK7TgGM45IlEoRgAOWyToKABQDiTZVQDaAXWpQKAEwgAPfBOmyAlNZZKZAA+YSxSADMoC2JiADoAGwgqYAALKFDXD18wrChifXFichxY2yz3ewBuOg4sTW1gfOxyFzhJAElWjyEAWWw0uIiEhGIzfsHiFrbJMxyAKlL4pJTU3xqsAuAikstbKdb2rrdKmrYa9AadcmMIAiFbKABybCenJ-o35-Uvp5cnqDVTgAemBUGGcAA7lBNJIwAlsBQCJctDoSC0CBE4MRJPxiAAVODwRDmegCfB4pw3EwEACCsQCKgc-lgCBC0QwWDi3LJchE+D0hluZmpd3pcgYAji2F8tDY6xBYIh0Nh8MR2hRjSg6O0WJxeMJxIMcAAIncSOJ1NsCkIzLyKQIqbc6QylIFmfhieyzJycPhedL5Ax-VLsEHRIKjCYRc7xU4AzK5Qr0KCoJDsQBre4RCgQTVog6Y7G4gSGhAAUXc8NI6lITVJ5L4jrEsddzCZ9hZXqQoV9VyaqBwTm5cTJAC8oGwhLyNvlCsVclyedgx0GsBH9FGIDGaXHJfFE7UzlUgA

**Comment by wchargin** [comment]
Your example `transformBarToFoo` appears to be a duplicate of #6108.

I don’t understand your example `transformBarToFooNoDestructure`. You
write `b: bar.a` in an object literal of type `Foo`, but `Foo` declares
`b: string` and `Bar` declares `a: number`. [Did you perhaps mean to
write `b: bar.b`][1]?

```js
// @flow
type Foo = {
  a: string,
  b: string,
};

type Bar = {
  a: number,
  b: string,
};

declare function getName(arr: string[], index: number): string;
declare var names: string[];

// no error (good)
const transformBarToFooNoDestructure = (bar: Bar, namesArr: string[]): Foo => ({
  a: bar.a,
  b: bar.b,
  a: getName(namesArr, bar.a),
});
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagGK1qALygDeiooAhgFygDOyATgJYB2A5gDTmgBGtDFh24BfANyIUGbACFKjIqR41QrAK4BbXpkbcK-ekzZdE4yQBNMAY2jzskNayvJmsVqHaZkAOUobMABTyjAJGHADaALqcoGyWAB606lo6AJShQuwSljZ2oABu8qp+mHQZxlESiCCqBDqMsAoB7PjmqYhWbgygTJSsdJCNGnKMACqweLDesAAipUxqzmqM2MQBvPK0IzGsJXQAgowhhplR6bj4RAB8oAFkFCobjAB0lHp8tE-PvO8qnj4lAK7fwHI4xL6UVKiVISIA

(I’m looking at the code in your second comment only.)

**Comment by csakai** [comment]
@wchargin The example `transformBarToFooNoDestruture` is to demonstrate what `transformBarToFoo` is doing under the hood. It is destructuring the param `bar` into
```
{
  a: bar.a,
  b: bar.b
}
```
and passing those key-value pairs to the resultant object, after which the line
`a: getName(namesArr, bar.a)`
is overwriting the resultant object's `a` key-value pair with the result of `getName(namesArr, bar.a)`

In plain old javascript, writing something like this:
```
const result = {
  a: 1,
  b: 'foo',
  a: 'bar'
};
```
while confusing, is syntactically valid, and will produce the resultant object:
```
const expected = {
  a: 'bar',
  b: 'foo'
};
for (let key of Object.keys(result)) {
  result[key] === expected[key] // true
}
```

PS: You are correct that the initially described problem is a duplicate of #6108 - And thank you for directing me to that issue.

However, I am also indicating that this isn't really a problem with how flow handles spreading, but rather, how it evaluates object re-assignment (eagerly). The work-around described in #6108 certainly works, as I demonstrated in my code sample in my OP, but it was surprising to see that I needed to break convention (using spread indiscriminately and reassigning selectively) in order to get flow to read my code properly. I wouldn't mind (if I had the time) working on and submitting a PR to fix this issue, but on initial inspection of the flow code base, it's very outside of my scope of knowledge and would take me some time.

**Comment by csakai** [comment]
@wchargin Wow! Great catch. This is why we don't use meaningless variable names in production code. The flow error disappears when using the explicit reassignment when `result.b` is being assigned `bar.b`. I'll go ahead and close this since the original issue #6108 is indeed what my issue is about
