### ISSUE TITLE
Definition: Response constructor missing ReadableStream as a possible argument

### ISSUE THREAD

**Issue by charlag** [facebook/flow#6824]
Definition of `BodyInit` in [libs/bom.js](https://github.com/facebook/flow/blob/master/lib/bom.js#L942) is missing a `ReadableStream` option
see MDN: https://developer.mozilla.org/en-US/docs/Web/API/Response/Response
see spec: https://fetch.spec.whatwg.org/#concept-bodyinit-extract

Thanks!

**Comment by mrkev** [comment]
Created #6848

**Comment by charlag** [comment]
Thanks, could bring myself together to figure build process and fix it!
