### ISSUE TITLE
.flowconfig changed in an incompatible way. Exiting.

### ISSUE THREAD

**Issue by killynathan** [facebook/flow#6825]
flow v0.75.0
macOS v10.13.6

Whenever I run flow, I get the following error in the logs:

`
path/to/.flowconfig changed in an incompatible way. Exiting.
`

which means the next time I run flow, it has to restart (re-initialize/re-parse). Someone else is using the exact same .flowconfig and flow version as me and it works for him. Does anyone know of any variables besides OS and flow versioning that can cause this?

**Comment by mrkev** [comment]
That's odd, and happens right here: 

https://github.com/facebook/flow/blob/8b493f89c35c6da6e0d1be348ba9f3b50e7bb77c/src/server/rechecker/recheck_updates.ml#L60-L68

Interesting paths to follow from here are `src/monitor/fileWatcher.ml` is pushing a change to `.flowconfig` as told by [`watchman`](https://facebook.github.io/watchman/), which is what flow and uses to tell if files change iirc. If you install and run watchman standalone does it also claim your .flowconfig changes?

**Comment by killynathan** [comment]
I fixed this problem by deleting the whole project that houses the `.flowconfig` and re-cloning it and npm installing again.

I later encountered a probably unrelated problem when running flow where flow looks in my trash for the global flow program that I previously installed and uninstalled.

**Comment by mrkev** [comment]
`watchman watch ~/src`

More info on their site: https://facebook.github.io/watchman/

**Comment by athomann** [comment]
This issue was resolved for me when I removed the directory out of iCloud file sharing.  It seemed to freakout when files would sync. I wonder if this would be affected by other services like dropbox.

**Comment by mrkev** [comment]
Sounds like watchman thinks iCloud is for some reason updating `.flowconfig` while you use it-- probably metadata. This could well be a bug with watchman, or a bug with iCloud itself.

**Comment by btmills** [comment]
As another datapoint, I was experiencing this same error with a project stored in an iCloud-synced directory, and moving the project out solved it. Flow 0.98.1 on macOS Mojave.

**Comment by vicapow** [comment]
As one more datapoint, I also recently helped debug an issue with the flow server not starting because they had inadvertently synced the repo with icloud.

**Comment by SamChou19815** [comment]
This is likely fixed a while ago.
