### ISSUE TITLE
more helpful error message when passing a function to `$Call`

### ISSUE THREAD

**Issue by MatrixFrog** [facebook/flow#6826]
I'm trying to use `$Call` with a mapStateToProps function, though I think this would apply for lots of other functions that have nothing to do with Redux or React. I first tried

`type ConnectedProps = $Call<mapStateToProps>`

which seemed reasonable to me. The error was `Cannot instantiate $Call because a callable signature is missing in prototype [1]`. To be completely honest I don't know what this means. But in any case, the problem was that you're supposed to pass a function _type_, not a function, to `$Call`. So I would suggest adding: "Did you mean `$Call<typeof mapStateToProps>`?" with the "typeof" bolded for emphasis, to the end of the error message.

**Comment by goodmind** [comment]
I think this was fixed in Flow v0.82
```
5: type F = $Call<mapStateToProps, 1>
                  ^ Cannot use function as a type because function is a value. To get the type of a value use `typeof`.
```
