### ISSUE TITLE
React ref: property `focus` is missing in property `current` of unknown type

### ISSUE THREAD

**Issue by hrasoa** [facebook/flow#6827]
in this case, `current` should return an `HTMLButtonElement`, instead its type is "unknown":

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQokscMATzBJciJDTjU6DZqxgdOnNABsUAZzVwAQgFcYMUnCQAPGOQAmmwsTIUAPDkoA+XJzju4buAEgWNAFxiNHaMAEZ6BiSMLgC8YugwAHRoLChmyDQAFACUXO5e3mhEkLYwACLA5gCyEDoUOa7e3sASmTAAFsBqiX7JOlAsFNmN3u7eHV094n0D5Ek0EGg6ajlcTZSc3hv5vhZIUA04XmMsMP0kcHbh+oZ+MTgT3X7O15F2APSvpE55HtScGyAA

**Comment by SamChou19815** [comment]
It now produces a better error
