### ISSUE TITLE
Can't make a promise resolve to a class if it extends EventEmitter and has a constructor

### ISSUE THREAD

**Issue by AgentME** [facebook/flow#683]
I'm stumped.

```javascript
/* @flow */
// jshint ignore:start

import {EventEmitter} from 'events';

class Bar extends EventEmitter {
	constructor() {
		super();
	}
}

var pr = new Promise((resolve, reject) => {
	resolve(new Bar());
});
```

```
$ flow --version
Flow, a static type checker for JavaScript, version 0.14.0
$ flow

/private/tmp/a/foo.js:6:7,9: Bar
This type is incompatible with
/private/tmp/flow/flowlib_5929094/core.js:352:1,379:1: Promise

Found 1 error
```

Changing the promise to resolve to anything else (like `new Object()` or even `new EventEmitter()`) makes the error go away.
Removing Bar's constructor makes the error go away.
Making Bar not extend anything (and removing `super()`) or making it extend anything else like `Object` makes the error go away.

**Comment by samwgoldman** [comment]
This is not the first time that Promise and EventEmitter have quarreled! I wonder if this is related to #545?

**Comment by AgentME** [comment]
Yeah, looks like the same issue. I tried a similar test where I inlined the declarations of EventEmitter and events$EventEmitter into my file exactly as they were in Flow's `node.js` definitions file, and the error would go away, so I'm pretty confused. Maybe it has to do with Bar extending a class that was imported from elsewhere and declared in an external definitions file.

**Comment by runn1ng** [comment]
> I tried a similar test where I inlined the declarations of EventEmitter and events$EventEmitter into my file exactly as they were in Flow's node.js definitions file, and the error would go away

Thanks @AgentME , this seems like a great workaround.

**Comment by runn1ng** [comment]
...but it doesn't work.

**Comment by AgentME** [comment]
I did that just to probe what exactly triggered the bug. If you want to work around it and make a file type-check, try casting some things to `any`. This or something like it ought to work:

```js
var pr: Promise<Bar> = new (Promise: any)((resolve, reject) => {
    resolve(new Bar());
});
```
