### ISSUE TITLE
Deconstructed defaults don't typecheck correctly.

### ISSUE THREAD

**Issue by mirek** [facebook/flow#6832]
https://flow.org/try/#0FAMwrgdgxgLglgewgAgOYFMYEYAUMEBCANglANYD8AXMhGALYBG6ATsgD7IDkRAhjOgDOMLsgC83PgOFcAlMgDeAX2ChIsRCgwwATDgXJ8xUmXGT+QkciU0FnIyXLVaDZm048LMjkvnKgA

```
function get1(toBlock?: number | 'latest' = 'latest') {}
function get2({ toBlock = 'latest' }: {| toBlock?: number | 'latest' |}) {}
```

`get1` function type-checks ok.
`get2` function complains, but should type-check the same way `get1` does, right?

**Comment by mrkev** [comment]
Yeah hmmm, this seems like a bug to me.

**Comment by mirek** [comment]
This works fine with recent versions, thank you ❤️.
