### ISSUE TITLE
Process doesn't exit when called from Node on Windows

### ISSUE THREAD

**Issue by nwoltman** [facebook/flow#6834]
When running Flow's `check-contents` command on Windows using Node's [`child_process.spawnSync()`](https://nodejs.org/dist/latest-v10.x/docs/api/child_process.html#child_process_child_process_spawnsync_command_args_options) function, the process never finishes, so `spawnSync` never returns.

Note that this only happens if a Flow server is not already running.

[Here is a demo repo that reproduces the bug](https://github.com/nwoltman/flow-bug-demo)

The problem started occurring in Flow `0.71` and has not changed since that version.

For reference, I'm on:
Windows 10
Node 10.15.0

This issue has been plaguing Windows users of [`eslint-plugin-flowtype-errors`](https://github.com/amilajack/eslint-plugin-flowtype-errors) for months.

**Comment by SergioMorchon** [comment]
I downloaded & reproduced it, Windows 10 & Node v8.11.3.
I had experienced the same issue sometimes, now it has an explanation :)

**Comment by nwoltman** [comment]
After testing on recent versions of Flow, it looks like this was fixed in `v0.127.0`.
