### ISSUE TITLE
Type error inside if statement and using Math functions

### ISSUE THREAD

**Issue by tonai** [facebook/flow#6838]
I'm not sure if this is a bug but I got a flow error with the following code which seems to be ok :
```js
type Action = {
  type: 'PANEL_RESIZE_UPDATE',
  width: null | number
};

function test(action: Action) {
  let width = 0;
  let vectorX = 0;
  let minWidth = 10;
  if (action.width !== null) {
    width = Math.max(action.width, minWidth);
    vectorX = (width - action.width) / 2; // Cannot perform arithmetic operation because null [1] is not a number.
  }
}
```
Try it yourself : https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhgJZwB2YAvGAN6phjb4BcYA5AAqEByAUQAyAfQBKAgMoBJAFoCRAVW4ARQgBUBnADRMwCMgBMMACw6UArjBhgAPmEsBbAEZ4ATqgC+AbnRQLlKQU1Bh4AM4YABQAhkFUHCTkVACUDHoweBj6Rqa0YAAMvswZWQBueKRwbgAaeYXpmWCOZJQA6jkmeQCM9cxkUGAxcZQAdAbGnQCENHSW1qmMzMzjuXQAstGmI47RAB5DSaMrJtpNLe0TyUVL5ZU1eZHHYAC0YLGHYx2pwGAATNeeLyoIA

Notice that the error is only on the second line inside the if (after `Math.max`).
Which mean I can avoid the problem by using 2 if statements:
```js
  if (action.width !== null) {
    width = Math.max(action.width, minWidth);
  }
  if (action.width !== null) {
    vectorX = (width - action.width) / 2;
  }
```

Or affecting `action.width` to a new variable inside the if statement:
```js
  if (action.width !== null) {
    const data = action.width;
    width = Math.max(data, minWidth);
    vectorX = (width - data) / 2;
  }
```

Or avoiding the usage of `Math.max`:
```js
  if (action.width !== null) {
    width = action.width > minWidth ? action.width : minWidth;
    vectorX = (width - action.width) / 2;
  }
```

I think that flow does not know that `Math.max` is a pure function and that it does not modify its parameters by reference, so `action.width` is still a number after `Math.max`.

**Comment by swac** [comment]
I think this is by design: https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations. Flow is intentionally not making assumptions about `Math.max`, in particular, that it doesn't hold its own reference to `data` and can modify it. Even though the default implementation is a pure function, it's technically possible that it was monkeypatched at runtime.

**Comment by tonai** [comment]
Thanks for your reply and the link to the doc.

It's not always obvious to find the source of an error.
Here the error is on the second line, but is in fact generated by the usage of the `Math.max` function on the first line (inside the if statement).

I don't know if there is a way to improve those kind of error.
That would be nice.
