### ISSUE TITLE
Intermediate files without Flow pragma make it easy to accidentally circumvent Flow.

### ISSUE THREAD

**Issue by joshduck** [facebook/flow#6840]
If I have a consumer and publisher of an interface with a`@flow` pragma, and an intermediate file without a pragma, Flow will ignore all typing and type interfaces as `any`. 

This technically makes sense, but is a massive foot gun. When I searched multiple codebases it was a very prevalent problem. It mostly appeared when using superfluous index files ([here's a repo version](https://github.com/joshduck/flow-example-of-broken-index-file/blob/master/src/foo/index.js)):

```javascript
// foo/foo.js (provider)
// @flow
export default function foo(a: number, b: string) { }

// foo/index.js (author forgot Flow pragma)
export * from './foo';

// entry.js (consumer)
// @flow
import foo from './foo';
foo(false, {}); // Flow does not catch errors.
```

Instead of silently ignoring types, Flow could pass the type information along. Or, alternatively, warn if an intermediate file is missing an annotation that would let Flow do the expected thing.

**Comment by threehams** [comment]
https://github.com/gajus/eslint-plugin-flowtype has rules to enforce Flow annotations.

**Comment by joshduck** [comment]
Yes, the lint rules can catch this (I put an [example in my test repo](https://github.com/joshduck/flow-example-of-broken-index-file/blob/master/.eslintrc)), but that requires installing ESLint, installing the ESLint Flow rules, and then configuring the `flowtype/require-valid-file-annotation` rule correctly (it has a weird default behaviour that does the wrong thing).

**Comment by jbrown215** [comment]
Flow doesn't aim to be the only tool you need for javascript development-- it's meant to be added to the JS toolchain. In particular, we try not to build in functionality that already exists in tools that don't require precise type information to work.

I recommend fixing the `require-valid-file-annotation` ESLint rule-- sounds like that would be very helpful to a lot of people!

**Comment by aleclarson** [comment]
Is the `untyped-import` linter supposed to check for `.js.flow` modules with the same name?
