### ISSUE TITLE
Missing inference in $Call

### ISSUE THREAD

**Issue by smikhalevski** [facebook/flow#6842]
```js
('abc': $Call<<E>(E) => $PropertyType<E, 'foo'>, { foo: number }>); // Error, ok

(['abc']: $Call<<E>(E) => [$PropertyType<E, 'foo'>], { foo: number }>); // No error. Why?
```
[Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgBQHICGARgMa4BcYAJAML4wwA8DAogHzbMCUYAvK1QAUATnAAOAUyEAXAJ4AVGRJYAaMLihw4uVqoDeYDXAoA7AK4BbQpLABfVpwDcYTGGZCRQ1XADW6bAG0CElwAXQoaOkYWdi5efn9KYTFJWQUlZlV1TW0QvQNNEwsrIVt7JxcAOTgwSQ8AOjAAdQALGQB+VCA)

I expected both of these examples to throw an error that `string` is incompatible with `number` but the second example seems to infer `$PropertyType<E, 'foo'>` as `any`. Can you please explain why?

**Comment by smikhalevski** [comment]
Just found out that adding `$NonMaybeType` fixes this issue:
```js
(['abc']: $Call<<E>(E) => [$PropertyType<$NonMaybeType<E>, 'foo'>], { foo: number }>); // Error!
```
Why? 😨

**Comment by Bannerets** [comment]
> but the second example seems to infer $PropertyType<E, 'foo'> as any

No.

```javascript
type A = $Call<<E>(E) =>
	[$PropertyType<E, 'foo'>], { foo: number }>;
;(['abc']: A)
```

Here `A` is `[(string | number)]`

![image](https://user-images.githubusercontent.com/10106819/45157637-63d27280-b1ea-11e8-9719-d76c42de3364.png)

You can also use this:

```javascript
type A = [$Call<<E>(E) =>
	$PropertyType<E, 'foo'>, { foo: number }>];
;(['abc']: A) // error.
```

**Comment by SamChou19815** [comment]
These both errors under `inference_mode=lti`
