### ISSUE TITLE
flow osx version is not catching some flow errors

### ISSUE THREAD

**Issue by joselcc** [facebook/flow#6844]
I using `flow-bin` to run flow type checks in a projects. I noticed that `flow-bin` runs a different flow binary depending on the current OS

```sh
package/flow-linux64-v0.75.0/flow
package/flow-osx-v0.75.0/flow
package/flow-win64-v0.75.0/flow.exe
```

The interesting part is that in linux I got more flow errors reported than in the osx version

MAC  (OS X 10.11.6)
===
```sh
$ node tools/abc-scripts/node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.75.0

$ npm run typecheck
....
......
Found 39 warnings
[abc-scripts] typecheck FINISHED!
```

LINUX (docker container Debian GNU/Linux 9)
=====
```sh
root@2b6eff7b9d90:/home/my-project# node tools/abc-scripts/node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.75.0

root@2b6eff7b9d90:/home/my-project# npm run typecheck
....
......
Found 4 errors and 16 warnings
[abc-scripts] typecheck FAILED!
```

(I haven't tested running flow as root in mac)

**Comment by mrkev** [comment]
+1. Especially curious about the `.flowconfig`

**Comment by gwing33** [comment]
No idea if this is related at all, but I had a similar issue, OSX wasn't reporting the same errors while our linux CI container was reporting 55 errors. Turns out that `flow-typed` wasn't updating itself properly. After manually pulling in the latest changes into the `~/.flow-typed/repo` everything started working again.

**Comment by akread** [comment]
We are running into a similar issue. Our CI/SD tools runs in a linux environment and all of our engineers are on mac os. There are errors that systematically show up on our CI/CD tool that never show up locally. This happens to all of our engineers.

Is there any information that I could provide that might help troubleshoot this? We are currently on version 0.113.0.

**Comment by SamChou19815** [comment]
These might be some bad releases a while ago, but I don't believe it should happen anymore since now the release is built from CI with the exact same source.
