### ISSUE TITLE
Type guessing is broken

### ISSUE THREAD

**Issue by gaborantal** [facebook/flow#6845]
I'd like to use Flow without making annotations in my code. That is not the typical case, I know, but I'd like to get type information (even if they are too bare). But the type guessing system seems to be totally broken. 

I created the most primitive example that should be guessed well. 

`const aNumber = 23;`

Flow gives the following result when I run `dump-types`:

```
d:\test>flow dump-types test3.js
d:\test\test3.js:1:7-13: any
d:\test\test3.js:1:17-18: number
```

Which seems absolutely guessable according to the fact the right side of the assignment was recognized well.

Another example taken from [here](http://sitr.us/2014/11/21/flow-is-the-javascript-type-checker-i-have-been-waiting-for.html):

```
function foo(b) { if (b) { return 21; } else { return ''; } }
function bar(b) {
  var x = foo(b);
  var y = foo(b);
  if (typeof x == 'number' && typeof y == 'number') { return x + y; }
  return 0;
}
var n = bar(1) * bar(2);
```

According to the blog post, Flow **was** able to determine the type of foo (for example) which was a `string | number` union. But currently, Flow tells only that it can be anything, while clearly not.

```
d:\test>flow dump-types test.js
d:\test\test.js:1:10-12: (b: any) => any
d:\test\test.js:1:14: any
d:\test\test.js:1:23: any
d:\test\test.js:1:35-36: number
d:\test\test.js:1:55-56: string
d:\test\test.js:2:10-12: (b: any) => any
d:\test\test.js:2:14: any
d:\test\test.js:3:7: any
d:\test\test.js:3:11-13: (b: any) => any
d:\test\test.js:3:11-16: any
d:\test\test.js:3:15: any
d:\test\test.js:4:7: any
d:\test\test.js:4:11-13: (b: any) => any
d:\test\test.js:4:11-16: any
d:\test\test.js:4:15: any
d:\test\test.js:5:14: any
d:\test\test.js:5:38: any
d:\test\test.js:5:62: any
d:\test\test.js:5:62-66: any
d:\test\test.js:5:66: any
d:\test\test.js:6:10: number
d:\test\test.js:8:5: any
d:\test\test.js:8:9-11: (b: any) => any
d:\test\test.js:8:9-14: any
d:\test\test.js:8:9-23: number
d:\test\test.js:8:13: number
d:\test\test.js:8:18-20: (b: any) => any
d:\test\test.js:8:18-23: any
d:\test\test.js:8:22: number
d:\test\test.js:11:7-13: any
d:\test\test.js:11:17-18: number
```

So can someone tell me if that's true or am I missing something that would solve my case. I am using the latest release (0.80.0). 

Thanks for the help in advance.
Cheers,
Gabor

**Comment by jbrown215** [comment]
Did you make sure to add `//@flow` to the top of your file? When I do I get this for that example on 0.80.0:
```
test3.js:3:10-12: (b: number) => (string | number)
test3.js:3:14: number
test3.js:3:23: number
test3.js:3:35-36: number
test3.js:3:55-56: string
test3.js:4:10-12: (b: number) => number
test3.js:4:14: number
test3.js:5:7: string | number
test3.js:5:11-13: (b: number) => (string | number)
test3.js:5:11-16: string | number
test3.js:5:15: number
test3.js:6:7: string | number
test3.js:6:11-13: (b: number) => (string | number)
test3.js:6:11-16: string | number
test3.js:6:15: number
test3.js:7:14: string | number
test3.js:7:38: string | number
test3.js:7:62: number
test3.js:7:62-66: number
test3.js:7:66: number
test3.js:8:10: number
test3.js:10:5: number
test3.js:10:9-11: (b: number) => number
test3.js:10:9-14: number
test3.js:10:9-23: number
test3.js:10:13: number
test3.js:10:18-20: (b: number) => number
test3.js:10:18-23: number
test3.js:10:22: number
```

In any case, Flow is not meant to be used without any type annotations. There are places Flow will require types and will emit an error if it is left unannotated.
