### ISSUE TITLE
Object$Assign should allow non-object sources, or else document that it differs from JS

### ISSUE THREAD

**Issue by wchargin** [facebook/flow#6856]
Consider [the following code][1]:

```js
// @flow
Object.assign({}, null, true, 6, Symbol("hi"), {a: 1});
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQB5ARgKwKYGMAuA6AQwGdiBLAcwDsAKAbwF8AaUKgV2mhdwCc3MWANhYBlAJ4BbVLGg0ARAAsycgJQs6hAFygAjAxUBuREA

In Chrome, Firefox, and Node, this evaluates to `{a: 1}`.

But Flow rejects this code, complaining that `true`, `6`, and
`Symbol("hi")` are not objects. (Actually, the complaint about the
symbol is that “`toString` is not writable”, but… okay.)

It seems that `Object$Assign` should be more permissive in this regard.

**Comment by villesau** [comment]
@wchargin I'm pretty sure that it's by purpose. Flow is not supposed allow everything what JS allows. The examples you mention are very likely error cases and I'm happy if flow complains about them.

You can't e.g multiply a string even though JS allows you to do so.

**Comment by wchargin** [comment]
That is also reasonable. The cases of string and array arguments seem
especially likely to be errors, as `Object.assign({}, "hi")` evaluates
to `{"0": "h", "1": "i"}`.

(I don’t have a stake in this issue either way. If the team wants to
wontfix it, preferably documenting this somewhere, that’s fine with me.)

**Comment by fizwidget** [comment]
I agree it makes sense for Flow to reject the examples given above. One case I'm not so sure about though is `Error` objects. In my code I'm currently doing something like this:
```
const event = {
    // Extract `message` and `stack` manually, as they aren't enumerable properties:
    message: error.message,
    stack: error.stack,
    // I also want any other properties that were attached to the error.
    // This causes a "property `toString` is not writable" error from Flow:
    ...error,
};
```
This feels like a reasonable thing to do, and I'm currently using `// $FlowFixMe` to silence the error. Is there a better alternative I'm missing, or should this be considered a bug in Flow? Thanks! :)

**Comment by wchargin** [comment]
@fizwidget: Eesh, that’s a weird one. It seems like a separate issue,
though. You can reproduce it without spread:

```
// @flow
const x = {};
x.toString = () => "hi";
```

The above code is valid JavaScript, and `String(x)` evaluates to `"hi"`.
But it is rejected by Flow with “property `toString` is not writable”,
as you note.

As a workaround, [you can upcast `error` to `{}`:][1]

```js
// @flow
declare var error: Error;
const bad = {
  message: error.message,
  stack: error.stack,
  ...error, // fails
};
const good = {
  message: error.message,
  stack: error.stack,
  ...(error: {}), // works
};
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tAG66io46w4BcoAomRQNyLqwB2AzgC6gBGWyoALygA3olCgAtqnbssAc1TVS5HADppshagA040FyzoA1svrrDJvRLW2VFHaBChIWAJbR2iAL5MWHbnlYWAFhMQlNOUUzVQ0ZKN19S1MSczVk61BbNQAKeypRbwBKR2d4CmMvX0QgA

This _shouldn’t_ work—it is a Liskov failure—but it does.
