### ISSUE TITLE
React type import inconsistencies

### ISSUE THREAD

**Issue by villesau** [facebook/flow#6858]
Hi, 
I've noticed inconsistency in class intersection types depending wether it is defined in module declaration in libdef or inline. I've repo to test the behaviour. It has two branches for different behaviour:
- repro steps: https://github.com/villesau/flow-error/blob/master/README.md
- the one with libdef: https://github.com/villesau/flow-error/compare/with-libdef
- the one with inline declaration https://github.com/villesau/flow-error/compare/inlined-declarations

**The problem**
As you see, the one with inline declaration does not complain, which, in my opinion, is the correct behaviour. But the one with defined libdef instead complains. As far as I know, these two ways of defining types should not be different from each other.

This prevents from building really type safe libdefs for Enzyme: .instance() can't be properly typed in module declaration due to this problem.

**Example pasted here:**

modified enzyme libdef:

```
declare module "enzyme" {
  import type { ElementRef } from 'react';
  declare class Wrapper<C> {
    instance(): $Call<<C>(Class<C>) => C, $ElementType<C, 'type'>>;
    instance(): ElementRef<C>;
  }

  declare class ShallowWrapper<C> extends Wrapper<C> {}

  declare export function shallow<C>(node: C): ShallowWrapper<C>;
}

```
usage:
```
// @flow
import * as React from "react";
import {
  shallow
} from "enzyme";

const shallowWrapper = shallow(<div />);
declare class ClassComponent extends React.Component<*, *> {
  instanceMethod(): number
}

const componentWrapper = shallow(<ClassComponent/>);
(componentWrapper.instance().instanceMethod(): number);

shallowWrapper.instance();
```

Above does _NOT_ work.

```
// @flow
import * as React from "react";
// copy from libdef starts
import type { ElementRef } from 'react';
declare class Wrapper<C> {
  instance(): $Call<<C>(Class<C>) => C, $ElementType<C, 'type'>>;
  instance(): ElementRef<C>;
}

declare class ShallowWrapper<C> extends Wrapper<C> {}

declare function shallow<C>(node: C): ShallowWrapper<C>;
// copy from libdef ends
const shallowWrapper = shallow(<div />);
declare class ClassComponent extends React.Component<*, *> {
  instanceMethod(): number
}

const componentWrapper = shallow(<ClassComponent/>);
(componentWrapper.instance().instanceMethod(): number);

shallowWrapper.instance();
```

Above instead works just like expected.

**Comment by villesau** [comment]
Hmm.. It might actually be related to type import!
[works](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDcKG2eOAJ7pKoAN6gAotEqpKAOxxVIoAL6gGTUAHJ2tHNp4ATSjWhF2oM6TIB1LEXQisAHgDCAPnGJQoZPJIcInkaSgAKAEoALlAAEjciaGgXdw8wt3MSElSI0ABeLzcAGjjpWQUcABVhSncS7SERbQ8PHl9-QODQyJiyuUVlVJ5VREQTa0trLNAAZQALRLh4e0dnVNBKAA8cBSM7BydKV09xEbHTc0stzFwNAFcQnGRYeVASBaSEVLD5WBMYtzRWYfJYrQ7HVqjGgvQJvEEIMHOfJwxYIMIuIzIABuoGAHgixguFlEUzIGRsbiYmHkFQ2212ZCo+gAdJS+DTFC58CV8F4xD4-AEgiFKABZSg4OZ-HqgeR3VAAIyOiDO0KFVipLwqiKOyPeqPg6PJWTZ1IqeIJiDC0PZ2oOzmZHWF3QijqFXTFEqlRhlcsVR0tiH1n2W9qObs6IsiPCAA)

[does not work](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDcKG2eOAJ7pKoAN6gAotEqpKAOxxVIoAL6gGTUAHJ2tHNp4ATSjWhF2oM6TIB1LEXQisAHgDCAPnGJQoZPJIcInkaSgAKAEoALlAAEjciaGgXdw8wt3MSElSI0ABeLzcAGjjpWQUcABVhSncS7SERbQ8PHl9-QODQyJiqfQA6MrlFZVSeVUREE2tLayzQAGUAC0S4eHtHZ1TQSgAPHAUjOwcnSldPcQmp03NLPcxcDQBXEJxkWHlQEhWkhFSw+SwEwxNzRRY-NYbU7nVqTGgfQJfCEIKHOfJI1YIMIuIzIABuoGAHgixhuFlEczIGRsbiYmHkFR2+0OZD6dH6tL4DMULnwJXwXjEPj8ASCIUoAFlKDglkCeqB5E9UAAjM6IK7w0VWOkfCqos7o76Y+DY6lZTn0ipEkmIMLwrl6k7OfodMXdCIu0VdSXS2VGeWKlVnG2II2-dZOs6ezriyI8IA)

[does not work](https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJlgM5GgDqOWADlajgDwDCAfKAN6KigCWAdkQBcsvdKgAUASgBcoACSMs0aPSbMxjbCVUTQAXlaMANHICi0VAFtUvAQBUAnrSbGA5AMeoXzZgG5OPfiERcWlQACVULHQBWTNLawEIyFU-AF9EFAxsPAJNUgBlAAtFOHgKaloGFlBUAA8Ba2RScpo6VXZ0zMIcuqpYHAFQSABXEQFuWF5QImKlBFUxXlg0GUZQopKEFsqUjPRJwWnZ0u26PSPN+DF6ZG4AN1BgZgk-NG78QhJQDWIiRlgLH1eAkavVGqQIlEBAA6f6AyYJegAKmMSNYHC4fEEwlEAFlUAJCstJDJeMMLAAjOiITr7QIEAFAhKnHDnGaXa4-Ehwpk2J4vRBifbw4E2FnQrFBUSSCWBHGofGE4mhMmUugCxDsuZlSitHCy7HBSR+IA)

See how `ElementRef` is defined. There should not be any differences in the above three definitions.

**Comment by wchargin** [comment]
This looks related to #6538, yes?

(Possibly additional complications as `React$ElementRef` is a native type.)

**Comment by SamChou19815** [comment]
These import related issues should be fixed a long time ago since types first
