### ISSUE TITLE
Add property 'getHeaders' to `http$ServerResponse` 

### ISSUE THREAD

**Issue by brycedorn** [facebook/flow#6860]
hi 👋 I'm currently trying to use this in a node application and it's missing. can I just make a PR and add it?

here it is in the node docs: https://nodejs.org/api/http.html#http_response_getheaders

and here it is (missing, among other properties) in flow: https://github.com/facebook/flow/blob/master/lib/node.js#L1251

edit: I'm sure you guys get tons of these daily, so I'll just add it to the local flow-typed definitions we use.

**Comment by wchargin** [comment]
For what it’s worth, clear-cut PRs like these are generally appreciated.
You’ve found it in the Node docs and in the missing section of the
libdefs, and an issue/PR search for `getHeaders` doesn’t reveal that
this has been proposed and rejected before. Feel free to submit a PR if
you like. :-)
