### ISSUE TITLE
Where is React$ElementRef defined?

### ISSUE THREAD

**Issue by skidding** [facebook/flow#6866]
Hi,

I'm trying to understand the React types in depth, but I don't understand where `React$ElementRef` is defined.

Unlike the other types, it is only referenced inside [lib/react.js](https://github.com/facebook/flow/blob/f68b89a5012bd995ab3509e7a41b7325045c4045/lib/react.js), but its definition must be elsewhere.

Thanks!

**Comment by wchargin** [comment]
It is a native type, defined in the OCaml code for Flow:

<https://github.com/facebook/flow/blob/b367a032d176ce1bcd976c5d0d70bbd778380a60/src/typing/type.ml#L998>

<https://github.com/facebook/flow/blob/b367a032d176ce1bcd976c5d0d70bbd778380a60/src/typing/ty_normalizer.ml#L1331>

Your best reference for understanding the React types in depth is
probably the relevant Flow documentation page:

<https://flow.org/en/docs/react/types/#toc-react-elementref>

**Comment by skidding** [comment]
@wbinnssmith Thanks!
