### ISSUE TITLE
No type checking when importing index.js from a directory that contains a index.css file

### ISSUE THREAD

**Issue by doberkofler** [facebook/flow#6870]
It took me a long time to understand, but it seems as if flow would completely stop any type checking when importing **index.js** from a directory that also contains a **index.css** file.

I was able to reduce my problem to a most simple test case as follows:

**index.js**
```
// @flow
import {MyClass} from './myclass';
const myclass = new MyClass();
myclass.xyz();
```
**./myclass/index.js**
```
// @flow
export class MyClass {}
```

**./myclass/index.css**
```
/* dummy */
```

**.flowconfig**
```
[ignore]
node_modules/.*

[include]
src/.*

[options]
module.file_ext=.js
module.file_ext=.css
module.name_mapper.extension='css' -> 'empty/object'
```

Running `flow check --show-all-errors` shows 0 errors.
When removing the **./myclass/index.css** file or when deleting the `module.file_ext=.css` and `module.name_mapper.extension='css' -> 'empty/object'` lines from the **.flowconfig** the expected error `Cannot call "myclass.xyz" because property "xyz" is missing in "MyClass" [1].` is shown.

I wanted to add, that actually the index.css file does not even have to be imported to reproduce this problem. It seems a bit as if flow would simply ùse the index.css file instead of the index.js file when including the./myclass/index.jsfile only using the directory syntax./myclass`.

Any help would be most appreciated!

**EXAMPLE**
[test.zip](https://github.com/facebook/flow/files/2364453/test.zip)

**Comment by doberkofler** [comment]
I wanted to add, that actually the `index.css` file does not even have to be imported to reproduce this problem. It seems a bit as if flow would simply ùse the `index.css` file instead of the `index.js file when including the `./myclass/index.js` file only using the directory syntax `./myclass`.

**Comment by maximeg** [comment]
It seems to be due to your:
```
[include]
src/.*
```
which eagerly includes all files, even `index.css` which conflicts with `index.js`, not just the ones your import.

Also, remove your:
```
module.file_ext=.css
module.name_mapper.extension='css' -> 'empty/object'
```
This won't be needed, you won't eagerly include css, just import them and `css` is in module_resource_exts.

I guess you're doing include not have `@flow` on top of each file. Did you try `src/.*\.js` ?

**Comment by doberkofler** [comment]
@maximeg Thank you for your comments. Could you please elaborate on the following:

I my understanding
```
[include]
src/.*
```
only tells flow where to look for my files but then only the files containing a `// @flow` comment on top will be included. What did I misunderstand here and would you be so kind to point me to the proper documentation?

You mention removing
```
module.file_ext=.css
module.name_mapper.extension='css' -> 'empty/object'
```
but there is quite some information that suggests that this is needed when importing css resources.
I tried removing it and it does indeed resolve the problem and flow no longer complains when importing but this must have changed since I initially started using flow. Would you know about what changed and why it is no longer needed?

Thank you!

**Comment by kohver** [comment]
I think the problem appears when you have two files with the same name but different extensions. Let's say you have following file structure:

```
src/Foo.js
src/Foo.css
```

And any other file tries to import `Foo.js`:
```js
import './Foo';
// flow won't check types from this file, because Foo.css will be "imported" instead.
```

But there is a workaround. You can explicitly declare file extension:
```js
import './Foo.js';
//            ^^^ it works because of the explicit file extension.
```

Of course it's true only if you use css modules, e.g. your **.flowconfig** includes something like this:
```ini
[options]
module.file_ext=.js
module.file_ext=.css
module.name_mapper.extension='css' -> 'empty/object'
```
