### ISSUE TITLE
generic default parameters

### ISSUE THREAD

**Issue by mernxl** [facebook/flow#6875]
When working with generics, i came across this issue, which you can find [reproduced here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAMTjgB4AFMAXjGwDsBPAPjAG9UwxcAXbbgSwxgARtgBOpACrVajJgAoAjgFc4ALjCSAlBuntOnMQFNuysXTAq4Abg5gAvqkdA).
I wish to understand if that is desired behavior or an abnormality.

```js
...
3  class Foo<P = any> {  // <-- No Error
4   static bar<T = any>(quo: T): T {      // <-- Errors
5     return quo;
6   }
7 }
...
```
Error Tab
```
4:   static bar<T = any>(quo: T): T {
                  ^ Unexpected token =
4:   static bar<T = any>(quo: T): T {
                    ^ Unexpected reserved type
```

**Comment by mike1808** [comment]
AFAIK default values for generics works only for parametrized generics in where only classes, type aliases and interfaces can have parametrized generics. https://flow.org/en/docs/types/generics/#toc-adding-defaults-to-parameterized-generics

**Comment by lyleunderwood** [comment]
@hayk94 That stack answer is not adding a default, it's adding a bound to the generic.

The way this is presented in the documentation is confusing. The distinction between generics and _parameterized_ generics is totally unclear.

>Functions and function types do not have parameterized generics.

What does this mean? Functions can have generics:

```javascript
type Func = <A>(A) => A;
```

Functions can have bound generics:

```javascript
type Func = <A: Object>(A) => A;
```

Functions can take type parameters:

```javascript
const func: Func = (a) => a;
func<{ a: number }>({a: 1, b: 2});
```

But they can't take defaults:

```javascript
type Func = <A=void>(A) => A;
```

Does this mean generics on functions are somehow less parameterized? Are there other things that generics on functions can't do that other generics can? Should these questions be answered in the docs? Typescript seems to support this.

In my case I'm trying to do something like this:

```javascript
// I want to be able to call `create` either with or without the first arg, if 
// i pass the first arg the return type should be `R`, if I don't, it should be `string`.
type Generator<T> = () => T;
const create = <R=string>( // throws an error as defaults aren't supported
    generator: Generator<R> = () => 'test',
): R => generator();

(create(): string);
(create(() => 1): number);
```

I'm not sure my problem would be solved by defaults, anyway.

**Comment by goodmind** [comment]
Fixed by https://github.com/facebook/flow/commit/c18ee0d8ee7999ef65ee21d0113b7351c5dc1e15

**Comment by Mouvedia** [comment]
```
  declare class Common<T> {
    hook: Hook<T = this>;
    pass: Pass<T = this>;
    done: Done;
  }
```
@goodmind which issue covers this use case?

**Comment by goodmind** [comment]
I don't think there is one

**Comment by ozyman42** [comment]
How is this fixed? I'm still not able to provide a default type for generic parameters
