### ISSUE TITLE
[React] Flow consider empty array default props as undefined

### ISSUE THREAD

**Issue by zachary95** [facebook/flow#6882]
Hello, 

I have a component that has an array as a optional prop. This array is populated later with Redux, but initially the component will initialize as a empty array on which I'm performing `.map`.

However, Flow consider my `this.props.array.map(x => x)` as non-valid because flow think `this.props.array` is undefined.

Example : https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAqsAEVi8uPALygA3olCgAdsVSEAXKADOOLMjkBzADQzQyACaqNW3XtCIAvm07dQABSro1oCdNk5Yx2GoB+VX4hEW4AbQBdAxtWRFJoYjV3ENgAGWQNUEIADxxCOWN3IjIcADoAYWpMOQKcAB4XWDcAPilDDWIcZFJQY0JIYgBXaBwmtw922W9ff1Uog1lYtlkGQsIsAAoASinphhwhrDlQTcNp0HqRlvOLqRwAC0yy9Fc1Mp8-d9RidE3P2AeNpnO53erQZAtSQAsoKJQ2erACE3UGybbbOygxHXW7bQx2OyIXKYXB9AbDUZ8QTpTI4VhAA 

Flow Version : 0.80.0.

--- 

The only hack I've found so far is making a null-check.

```
const toDos = this.props.todos || [];

toDos.map(todo => todo);
```

Which is basically replicating `defaultProps` behavior.

**Comment by wchargin** [comment]
As I understand it, you should mark the `todos` prop as non-nullable.
Clients will still be allowed to omit it as long as you include the
relevant key on `defaultProps`.

[Here is a fixed version of your example, which typechecks without
error:][1]

```js
// @flow
import React from 'react';

type ToDoType = {
  name: string,
  id: string, 
}

type Props = {
  todos: ToDoType[],
};

class ToDoList extends React.Component<Props> {
  static defaultProps = {
    todos: [],
  };

  render() {
    return (
      <ul>
        {this.props.todos.map(todo => (
          <li>{todo.name}</li>
        ))}
      </ul>
    )
  }
}

export function sample(): React$Node {
  // Explicitly specified `todos`:
  const a = <ToDoList todos={[{name: "explicit array demo", id: "test"}]} />;
  // Omitted `todos`; will use default prop:
  const b = <ToDoList />;
  return <React.Fragment>{a}{b}</React.Fragment>;
}

export default ToDoList;
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAqsAEVi8uPALygA3olCgAdsVSEAXKADOOLMjkBzADQzQyACaqNW3XtCIAvm07dQABSro1oCdNk5Yx2GtV+IRFuAG0AXQMbVkRSaGI1dyDYABlkDVBCAA8cQjljdyIyHAA6AGFqTDk8nAAeF1g3AD4pQw1iHGRSUGNCSGIAV2gcBrcPVtlvX39VCINZaLZZBnzCLAAKAEoJyYYcAaw5UHXDSdBaoabTs6kcAAt0kvRXNRKfP1fUYnR199gPFonG43WrQZBNSR-EoKJQ2WrAMFXYGyTabOzA+GXa6bQx2OyIbKYXCgSADOTkZCwI5qRToaCELaqIrkAAkADlfDwvKAQKAAKJZOldZA4aAcdTcUjISDIQjGUAAAz+agVykMpCpGWI41qyTSGWVYkkoUkMJUoAARISwVK8MQsFhiOLeqhYBarCZVBbchoLTZwjYeU1WLJeQB5VAi3LypXTFXMUDwZDQaCgAZqHi9fpDPDPRpq2QauQZABGOr16TwwGDhj2ByOtWZpQAYo6dEo5DgIcQbJIS3DgE2Sq3iO2ajX8YTsHgs4NhnxBKlK6wgA

Note that if you remove the `defaultProps` or its `todos` key, then Flow
properly raises an error on the definition of `const b = <ToDoList />`.

**Comment by zachary95** [comment]
Hello @wchargin, thanks for answering. 

This example works indeed, I tried it but I have two remarks here : 
- `eslint-plugin-react` will complain with `react/require-default-props` because I'm adding a defaultProps to an optional prop (this can be turned off) ;
- It could be misleading for others developers to say `todos` is required while it is not really.

**Comment by wchargin** [comment]
Let me note upfront that while this behavior may be a little surprising
(it was to me too, originally, and I might not have chosen this behavior
myself), [it is the documented way to do things][docs].

[docs]: https://flow.org/en/docs/react/components/#toc-using-default-props

> `eslint-plugin-react` will complain with `react/require-default-props`
> because I'm adding a defaultProps to an optional prop (this can be
> turned off) ;

This is a bug in eslint-plugin-react. See:
  - <https://github.com/yannickcr/eslint-plugin-react/issues/1904>
  - <https://github.com/airbnb/javascript/issues/1843>

I’d turn the lint rule off either globally or with line-by-line
suppressions until this is fixed, if I were you. Don’t let your linter
make you write worse code.

> It could be misleading for others developers to say `todos` is
> required while it is not really.

Two points. First, as mentioned above, this is documented—so it’s
something that each developer will have to learn and get used to only
once. Second, it’s not all that unnatural, depending on your point of
view. You’re thinking of `Props` as the interface to the _clients_ of
the component, but Flow uses it to mean the interface for the component
_itself_—i.e., the type of `this.props` as accessed from `render`. From
that point of view, it is at least consistent.

Does this answer your questions?

**Comment by zachary95** [comment]
It does, thanks! I will tell my team about it then.

**Comment by wchargin** [comment]
Great; glad to hear it.
