### ISSUE TITLE
Can't assign more specific generic into less specific generic

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/flow#6884]
The following gives an error:
```
type Superset = Subset1 | Subset2

type Subset1 = {
  prop1: string
}
type Subset2 = {
  prop2: string
}


var moreSpecificArray: Array<Subset1> = [];

var lessSpecificArray: Array<Superset> = moreSpecificArray;
```
```
Cannot assign `moreSpecificArray` to `lessSpecificArray` because property `prop1` is missing in `Subset2` [1] but exists in `Subset1` [2] in array element.
```
Interestingly, changing the following line to this does not give an error:
```
var lessSpecificArray: Array<Superset> = [].concat(moreSpecificArray);
```

Try-flow example:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKArvgE4DOeGYAvEcQEZUYCMYAPg89QEzrZ83Fu3oBvVGDA4ycHKwBcYChjIBLAHYBzVAF9MuAiR4ZedMBKky5vJSvXa96VADcAhmTABbOGTyF8AGM1KDVAgEEyMjcsJUjorAAeYxEAPnMAbQBdAG50d08YPAoKALxg0IiomLjqpJJyFnT6Hz8yirD4mLzXDzAACzdAgGs8ABMAGWLSoJDOutqE5NI8SmpmsGyAOkC4DUC3DAAKVv9Zyq6sAEocoA

**Comment by bsmith-cycorp** [comment]
It's not just a matter of cloning, though, because this doesn't work either:
```
var lessSpecificArray: Array<Superset> = moreSpecificArray.slice();
```

**Comment by xanf** [comment]
@bsmith-cycorp it's absolutely valid behavour. Arrays are invariant by default. To make words simple: since arrays are copied by reference you can doo lessSpecificArray.push, this will validate against Superset type, but will actually add valud to "moreSpecificArray" (since they share same ref).

changing to
```js
var lessSpecificArray: $ReadOnlyArray<Superset> = moreSpecificArray;
```
makes no errors, since read-only arrays are covariant

**Comment by wchargin** [comment]
@xanf is entirely correct. Mutable structures are invariant; read-only
structures are covariant.

> It's not just a matter of cloning, though, because this doesn't work
> either: […]

This is “just” an inference failure. [You can solve it by adding a type
annotation][try]:

```js
/* @flow */
type Superset = Subset1 | Subset2;
type Subset1 = {
  prop1: string
};
type Subset2 = {
  prop2: string
};

var moreSpecificArray: Array<Subset1> = [];
var lessSpecificArray: Array<Superset> = (moreSpecificArray: $ReadOnlyArray<
  Superset
>).slice(); // OK
```

[try]: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDKArngE4DOu6YAvIUQEaXoCMYAPvU1QEwDcGHPmLdWtMAG9UYMNlJxsLAFxhy6UgEsAdgHNUAXwFY8XZj3FSZchTxVrNugwNQA3AIakwAWzilcBPABjDSgNQIBBUlI3TBVI6MwAHhFmFgA+cQBtAF0Bd08YXHJyANxg0IiomLiqpOIyZgy6AAofP1LysPjqsAASACVcNwATAHktGExupOl6BqpUNIBKADpyGDDcZqW+MGBgMFGAaVQgA
