### ISSUE TITLE
Unsoundness when using $Subtype

### ISSUE THREAD

**Issue by aij** [facebook/flow#6886]
The documentation only says "Work in progress", so I'm not sure exactly how `$Subtype` is supposed to work.

A colleague found it and thought it was a nice way to get around a type error. (not realizing it was unsound to do so)

Here's an [example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFVALygDeokssAXKAHYCuAtgEZYBOoAvgNyqY4CqhEmQrV6zNgBpQTAIatqAZxSsAljQDmnHogDGsGstAohpclVAAGbXoNHZ1AIKtWstAB4AJAGU6TdNjuuAB8wUIA2igAujz6hiZ01IJEsuGWUchxRjSwKAD6snnKappKKupaRHQAdHKsOlkmsjR5WAAeulgYKKoGYows7EQ5+YXFFdXQWJooABZcQA)

```
// @flow

type T = { foo: number };
type U = { foo: number, bar: string };

const t = { foo: 0 };
const a: Array<$Subtype<T>> = [t];
const u: U = a[0]

const not_a_string: string = u.bar;

const an_exception: number = not_a_string.length;
```

**Comment by dsainati1** [comment]
The newest release adds an optional lint against these utilities. It is our eventual plan to deprecate them entirely.
