### ISSUE TITLE
Null coalescing operator (??) is not treated the same as equivalent ternary expression

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/flow#6890]
With the new null-coalescing operator in Babel 7 (`??`), the following two expressions are equivalent:
```
obj.prop != null ? obj.prop : 42
obj.prop ?? 42
```

But in Flow, the latter case doesn't work when refining union types:
```
type Type1 = {
  prop: number
}
type Type2 = {
  prop2: number
}

([]: Array<Type1|Type2>).forEach((obj: Type1|Type2) => {
  console.log(obj.prop != null ? obj.prop : 42) // this has no errors
  console.log(obj.prop ?? 42) // this has an error
})
```

Here's a try-flow:
https://flow.org/try/#0C4TwDgpgBAKuEEYoF4oG8BQUpgE4HswAuKAOwFcBbAIwlwwF8NRJZ4AmFdLHAsdkhRp1GGDAAoA2gF0SAQVy4AhiAA8cSAgA+GiOwB8ASgB0AM3y4AokoDGAC3Hj81AFYld23e0Mp93bDb4pADO+AA2EMZh+ADmTq7GeIRQAISoFGFhUAD8UM4uiXxQJAAs3lAA9BVQwHYAlsFQdkqNpPhQdAS4wTyBIeGR0XH5hcnZuWU+VTX1jc2NSqQdihaMhkA

**Comment by SamChou19815** [comment]
If you change the object to be exact, it would work as expected. Doing the same for inexact objects would be unsound.
