### ISSUE TITLE
Unexpected token %checks

### ISSUE THREAD

**Issue by LvChengbin** [facebook/flow#6896]
The code below will get an `Unexpected token %checks` error.

```js
const x = {
    fn( f ): %checks {
        return true;
    }
}
```

https://flow.org/try/#0MYewdgzgLgBAHjAvDA3gKBjAkAMzAChhxgEoAuGAUmAAsBTYAawlQ2ywCc6oBXDsGFA486AbjRYAvmklA

**Comment by lll000111** [comment]
[Try this.](https://flow.org/try/#0GYVwdgxgLglg9mABMMAKZiCUAuRBSCACwFMIBrAZ0QG8AoRRAJ2KhEaSkZGIG5aBfWrQgIKURAA9EAXhr1EASBQDaQA)

**Comment by LvChengbin** [comment]
@lll000111 Thanks a lot. I know that I can do that way, I just wanted to report an issue.
