### ISSUE TITLE
help with %checks with class with generics

### ISSUE THREAD

**Issue by sibelius** [facebook/flow#6899]
We are trying to add more generics to graphql-js to make it more typesafe, you can check our work here: https://github.com/graphql/graphql-js/pull/1522

The problem is that is causing some troubles in refinements using `%checks`

For instance this:

https://github.com/graphql/graphql-js/blob/master/src/validation/rules/OverlappingFieldsCanBeMerged.js#L755-L757
```jsx
if (isObjectType(parentType) || isInterfaceType(parentType)) {
          fieldDef = parentType.getFields()[fieldName];
        }
```

typecheck properly without generics, but does not work well with generics

parentType is inferred as `?GraphQLNamedType` instead of `GraphQLNamedType`

**Comment by SamChou19815** [comment]
Type guards now support generics
