### ISSUE TITLE
React components should be contravariant in <Props>

### ISSUE THREAD

**Issue by philipnilsson** [facebook/flow#6901]
I would expect React components to be contra-variant in the Props type argument. That is, I'd expect the following not to produce an error

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAwhOBAHZJUwAqRJAvnAGZQVwDkUqG3ANwAoYWmoBneAA0AXGQqQadRsQA8eNhAjypUYFQDmcZgD44AXnYBXKhmDUAFJu0mAlLmFxvfGNahUcGoAFgCMpjhaEMxqAPRh5sLMouJUUnAAmvLklMoMTBrs2row+kbYAEYoUPJU1iAVSFAm5lbSIkA

At the very least this should be true for stateless functional components, given that the following works without issue?

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAchACYkC+cAZlBCHAORSoYsDcAUD4cTgBhJpAB2SMTAAqRJAB4AtAAVGYAM4A+OAF44qiBt3byVPmghj18ABoAuYaMuSZc+XjoQID61GBiAczhqbT06AFcxDGBLAAoPL2CASlweOHT2GHCoMTh5AAsARk0cTwhqeQB6Iu0eanNLazgATQcRcGcpWWJ3ei8fGD9A7AAjFCgHMXCQEaQoYNC4G14gA

Is there something I don't see that prevents this for class components? I'm running into difficulty typing higher-order components due to this.

**Comment by jbrown215** [comment]
This is a question I've found myself asking myself as well. I'll get back to you on this

**Comment by jbrown215** [comment]
Here's why it wouldn't work in ComponentType, using only class Components:

https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctAGxQGc64ANOJADxiQDsATR5dDAB0AYVyQu3GAB4A3gF8AfHFnl5VWgzgBNVh259ExYWPARJXGbLYAuOFwCuIAEZIoSleqrm68AIJ2AhgAJKYSUgAqAJ5gSHIeALzMFGg+8ABCgcah4uaRMXHWdo4ubok6FOSYDlwYwOZwnL4AFCJZgjlmFjDRsXK29k6u7ooANHADJcMAlCrkcHBEMA5QXHDSIhMJ1vKLSJjbaHAJyrLAmHDNRwCESY7U1LNXQmA4YHRCbHDFQ27T8rsAPSKCheQGAuAASQuAHckHAUA8IHCeI0kC0-NNxl8YRAHNRUa44DUePtgJJCQ4sNRkXBcfjUTAABbkgDWcGAMEYKEGpSgQiAA

**Comment by jbrown215** [comment]
Actually, my example isn't quite right. Going to rethink

**Comment by jbrown215** [comment]
I'm still unsure about whether or not `Props` can be contravariant, but if we parameterize by `Config` instead it definitely can be contravariant. ComponentType conflates Props/Config right now. In an upcoming change, we choose to only represent config here. This will allow the type parameter to be contravariant.
