### ISSUE TITLE
Refinement using ['key'].includes(value) not possible

### ISSUE THREAD

**Issue by villesau** [facebook/flow#6904]
[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqS7QBeUACgDcBDaALlBwCcBLdAcwEpaByAU3QFcAtgEZOoAD4ACnvwEAmUYQB8oAN6JQoRpBIBtaYJEAaUPrmcAugDpmKaHwAm3TOSps2q9aACQ9btj70BJTQngC+oNzQmNweGj5+AQSmImGIoUA)

It's common practice to check using array of strings wether some value is any of them. Flow is not able to refine that case, and is still returning just `string`, even though it would be possible to refine the value.

Instead you need to fall back into cumbersome if statements: [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqS7QBeUACgDcBDaALlBwCcBLdAcwEpaByAU3QFcAtgEZOoAD4ACnvwEAmUYQB8oAN6JQoRpHJUihYtMEjxkytD0Heg+W1XrQASHrdsfegTP2AvqG7RM3HYaTi5uBIbCnN6IXkA)

If there are many possible values to check, this will bloat badly and make the code harder to read.

**Comment by lll000111** [comment]
If it's any consolation, TypeScript (tested 3.0.1, target "es2017") isn't any better, it says

    TS2322: Type 'string' is not assignable to type '"enum1" | "enum2"'.

**Comment by SamChou19815** [comment]
Closing this since we are unlikely to support refinements with arbitrary library functions.
