### ISSUE TITLE
Spreading $Shape of exact type is same as spreading of same exact type

### ISSUE THREAD

**Issue by petejodo** [facebook/flow#6906]
It seems when spreading a `$Shape` of an exact type, it doesn't actually spread on type `$Shape<T>` but just spreads on `T` instead. The following breaks in [try flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfKAzA9pgXFAdgK4C2ARhAE5QoC+A3AFCiRQBCCyapAhhXgM7AKAS3wBzavQYMAxpnyCopAIx4AJAGUAFt0gAeVgD4OSJbzwByQRQtQpchcCUAmddt0QDxxEilNw0ACiAB7cxGAANhDKegAqADRQAKrenAxQGVAAdDkJ6Zk5WUkMtIz+LCFhkRDOcYkpJij52bnxzYWaOvopJX4OihDBqlCV4VExMImdHl6pSPlYuFDKbRk8fASEEREMffIDwa4joWM1epNscwvYeMq7dEA)

```js
type A = {| foo: number |};
type B = {| bar: string |};
type C<T, U> = {|
   ...T,
   ...$Shape<U>
|};

const c: C<A, B> = { // Error, property `bar` missing
  foo: 1
};
```

**Comment by orlandoc01** [comment]
Any updates on this issue? Is this a bug then in flow or are we misusing the spread operator with the $Shape type because we don' understand some behavior going on here?

**Comment by orlandoc01** [comment]
Ok, I've been using the following instead actually:

```
type Partial<T> = $Rest<T, {}>;
```

https://flow.org/try/#0C4TwDgpgBACghgJ2ASzgGwDwBUB8UC8UAJAEoQDOw2ANFAN4C+OA3AFCuiRQCCB9APlABmAexEAuKADsArgFsARhARR+DNp2gAhPnUELEkygmRSA5qvUdw0AMI0oAVTyE9rKB4B03rNXdfveCRUTGdWNTZWAGMRKUooKMl7blotF3p-UQkoAEY-dSA

**Comment by kevinbarabash** [comment]
Would it make sense to define `$Shape`'s as `$Rest<T, {}>`?  Are there things that rely on `$Shape`'s behavior that wouldn't work this change?

**Comment by somewhatabstract** [comment]
Now that https://github.com/facebook/flow/releases/tag/v0.162.0 includes `$Partial`, is this issue addressed?

**Comment by mrtnzlml** [comment]
> Now that https://github.com/facebook/flow/releases/tag/v0.162.0 includes `$Partial`, is this issue addressed?

It seems like yes: [flow.org/try](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfKAzA9pgXFAdgK4C2ARhAE5QoC+A3AFCiRQBCCyapAhhXgM7AKAS3wBzavQZNw0AMIAeACoAaKAFUAfB1QMo+gHRHVew0YAkABV7Bh3ADYKtDWowYBjTPkFR3eRTBqrNqISFAA9OEEmFCUFJgUpli4UACMDPRAA)
