### ISSUE TITLE
Flow not infer function return type with generics

### ISSUE THREAD

**Issue by cain-wang** [facebook/flow#6910]
Hi,

I'm trying to infer a callback return type with generics.
Somehow the generic type inference works with function parameters, but not with return types:

function echo<T>(content: T, callback: () => T) {
}

echo('string', () => {
  // should flow infer return type as string here?
  return 1;
}); 

Should Flow err in this case as the actual return type is not compatible with the assumed inferred type of string?

https://flow.org/try/#0GYVwdgxgLglg9mABHA1gHgCoD4AUEFQCmYUAXIhgDSIQCGANvQEa0QrkaIC8WitYATwCUiAN4AoAL7jxqHAHIAzlABOMMAHN51AG4MQhbrwmJEe+gYB09YhqgALRAHonyFH0Vn9hqAIAOhjCe6sCEKiqEACYeiMpqmlJCMqCQsAiIhBD2cJi4+CTEZBTUdIwsbOQ4IjwUIhLS4pnZCnHqWtRVRmLipi6x2SD00cD0cADuiCFhiBFQICpIvgExrZqI9mGEAPw9M4RzC4gAjADciSeIMkA

**Comment by wchargin** [comment]
Please use [code formatting][fmt] to make your post easier to read.

Flow’s inference is working just fine. The type inferred at the second
call site is not `string`, but `string | 1` (or `string | number`).
The first argument, `"string"`, can be safely upcast from type `string`
to type `string | 1`, and the callback `(() => 1)` can also be taken to
return `string | 1`. The program is perfectly sound.

If you write `echo<string>("string", () => 1);` to explicitly specify
the type parameter, Flow indeed raises an error as you expected.

[fmt]: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by jbrown215** [comment]
@wchargin is correct.

**Comment by cain-wang** [comment]
Just verified babel-eslint 9 is compatible with this feature now. It's a happy day! Thanks a lot!
