### ISSUE TITLE
React.ComponentType<Props> getting typed as `any`

### ISSUE THREAD

**Issue by melissafzhang** [facebook/flow#6912]
I am typing the `inject` HOC from `mobx-react` to enable prop checking. I have a custom libdef like this: 
```
type SomeStore = {
  name: string
}

type Stores = {
 someStore: SomeStore,
}

declare function inject<Props>(
    ...storeNames: $Keys<Stores>[] // verify that strings are names of stores
): (component: React.ComponentType<Props>) => React.ComponentType<$Diff<Props, Stores>>;
````
However, the function that is returned from the inject function does not get typed correctly. Rather it is typed as `(any) => any` instead of` (React.ComponentType<Props>) =>  React.ComponentType<$Diff<Props, Stores>>`. This causes the behavior where wrapping any component in `inject` will prevent any prop type checking from happening at all.

I have reproduced [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KgQE9s1MAGUW1UQXwiAvGADeqMGAB2JTNQBcYMgTzpVAc1QBfVPyEipMivKW6JNzjvGbn1ADRmLAE2p0MCScYFAArqoM6HCqYIYAVgEEADwACszYZAB8ABTKKmAAdMV6MgByGtRkOgAkANLUAmTJHtkA2gC6YMDAYABu1AZQAmAEABYkRHoGxhTBIuqaFHBQutKcZKgAlDo5dCy4qtSqBDo09ASFAMIHMccEACpWaRnZW2CyWVRclzc4dycnsJkjUACLoKBQF5wTKeMTrKpZLJ8CyCYRgdIwuyKfJkJwI1z4mTeUwowLkCgAWQEf0O9zA1AAHgRjr4KOcGNdbkcTtDMl8HGBOKp-Hgcu9BSpOAQwnhYqowjAYHwVOZzKgeqMxugKGQxnBFb4tcwkCRYoNmHgwAAjAIkMJkER49wIuIUVRwIgJJLUXyoJm4QhgfxQe0wL2qRIMcU5am0gEELZ8IA). In this example, there should be an error for the last line since no props are being injected.

**Comment by fabiomcosta** [comment]
Maybe a simpler example:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudQgE8cNMAAUWOcgEEwAXjABvAD6owZAFxgAdgFcsAIxr5UygL78AkKmDAwASW1hCACxoFBZGDGdvyogGYwGAxtGkpSLjAARxpo3QwAN1IYGm1CVAAKRTADLSCzLVoGQgA6AFFUrDTCAGE4bSgMAHMAHmLGUvrcBpqAFWEaVok4KWkAPnGASn5s3PywQupuMsqaavSRqXaVrtY8MPSBkWHJGUmZmzsDXWIGmE9XDEpe3xYEciycvLACrS2ZJcgA

**Comment by SamChou19815** [comment]
This now errors under `inference_mode=lti`
