### ISSUE TITLE
Flow parser should support import.meta

### ISSUE THREAD

**Issue by rtsao** [facebook/flow#6913]
`import.meta` is a stage 3 proposal that has shipped in Chrome, Firefox, and Node 10. Flow should be able to parse this syntax.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcA6LAU0IENiBXfGAbiA

**Comment by wchargin** [comment]
Implemented in #6958.

**Comment by wchargin** [comment]
Friendly ping on that PR. I know some folks were interested in this and
wouldn’t want the diff to go stale.

**Comment by mgtitimoli** [comment]
We didn't get a response from your previously friendly ping @wchargin, so I'm pinging again hoping we are gonna get some response now :)

**Comment by fredericgermain** [comment]
`import.meta.url` is the official way to have `__dirname` in ESM node implementation. ES6 Module support is very strict in node.
https://nodejs.org/docs/latest/api/esm.html

We can't migrate to modules while flow is not supporting it (flow-remove-types makes an error on this syntax too). Or we have to get around the __dirname variable.

**Comment by YevhenKap** [comment]
It's not implemeted yet( Though [import.meta](https://html.spec.whatwg.org/multipage/webappapis.html#hostgetimportmetaproperties) is living standard already.

**Comment by unphased** [comment]
I cannot use flow because use of import.meta breaks flow parsing of the entire source file from that point forward... 

Yes, I am using import.meta.url to obtain __dirname in node scripts.

**Comment by strager** [comment]
I use this ugly workaround to make both Flow and Node.js happy:

```
// $FlowFixMe
let __filename /*: string */ = url.fileURLToPath(import /*:: ("") */.meta.url);
```

I don't know if this works with flow-removes-types or Babel, though.

**Comment by ancms2600** [comment]
The above workaround didn't quite work for me but this does:

```js
import { dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname/*:string*/ = dirname(fileURLToPath(/*::(*/import/*::('fs'):any)*/.meta.url));
```
