### ISSUE TITLE
fields of spreaded types ignored in generic functions

### ISSUE THREAD

**Issue by nikhedonia** [facebook/flow#6916]
I just [try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN5hQkBcYAzhgE4CWAdgOZgC+A3JlwFicAEIBDFuSpgAdAtEAaMACMpDZu259B2fERKSWAJhnVacTa05cV6lte08B6VFACuHAMYY2cDhoSABE8Dj9sAB4AFQZRAD4ACjA4VQArBmiASkyqVDAwFjwMDxZA1LTBXjcYYrAADzA4oykKC3owAHJLTvsNLodO3VRajDAsJsNxKRM2oKsunr7HAakh11RgYDAAEgBRevxfPZYWOBZ3ELCIrET6rP4CrbATs5YAQku4UPC2bESsA8ntsAOrnADWjE+QA)ed the following snipped:

```js
/* @flow */

type Foo = { foo: string };
type FooBar = { ...Foo, bar: string };
type FooBar2 = { foo: string, bar: string };


function fooDentity<T: Foo>( obj: T): T {
  return obj;
}


let x : FooBar= { foo: 'foo', bar: 'bar' };
let y : FooBar2= { foo: 'foo', bar: 'bar' };

// $ExpectError
fooDentity(x);  // Error!
fooDentity(y);  // Works!
```

The failure seems like a bug to me...

**Comment by goodmind** [comment]
This works

```js
/* @flow */

type Foo = {| foo: string |};
type FooBar = {| ...Foo, bar: string |};
type FooBar2 = {| ...Foo, bar: string |};


function fooDentity<T: { foo: string }>(obj: T): T {
  return obj;
}


let x : FooBar  = { foo: 'foo', bar: 'bar' };
let y : FooBar2 = { foo: 'foo', bar: 'bar' };

fooDentity(x);  // Works!
fooDentity(y);  // Works!
```

**Comment by nikhedonia** [comment]
I'd like to have this issue reopened as I see your code example just avoids using the broken feature.

The usage of `{ ... }` `{| ... |}` doesn't make any difference.
Note the main difference between our code examples is here:

```
function fooDentity<T: Foo>(obj: T): T {
  return obj;
}
```

vs

```
function fooDentity<T: { foo: string }>(obj: T): T {
  return obj;
}
```


I don;t think it is a practical solution to explicitly write out all members of a potentially very complex type

**Comment by goodmind** [comment]
You can write it like this then
```
/* @flow */

type Foo = { foo: string };
type FooBar = { ...$Exact<Foo>, bar: string };
type FooBar2 = { ...$Exact<Foo>, bar: string };


function fooDentity<T: Foo>(obj: T): T {
  return obj;
}


let x : FooBar  = { foo: 'foo', bar: 'bar' };
let y : FooBar2 = { foo: 'foo', bar: 'bar' };

fooDentity(x);  // Works!
fooDentity(y);  // Works!
```

**Comment by goodmind** [comment]
It isn't broken feature, Exact is supposed to work like this

**Comment by nikhedonia** [comment]
> It isn't broken feature, Exact is supposed to work like this

I don't understand how your examples relate to mine.

Furthermore you `FooBar2` was supposed to be the contrasting example.
In your code snippets you made them identical which renders FooBar2 obsolete. 

How are `FooBar` and `FooBar2` different in my example?

Could you articulate why my example is not supposed to work? 
What is the rationale behind preventing an intuitive notation from working and obfuscating with a confusing error message?

Maybe it's worth to step back and think about  how things *should* work as opposed how things are right now - If we don't we won't make any progress.

**Comment by goodmind** [comment]
@nikhedonia you can't use exact objects as constraint in generics, also spreading inexact objects makes properties optional because it represents runtime spread

**Comment by goodmind** [comment]
[This](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN5hQkBcYAzhgE4CWAdgOZgC+A3JlwFicAEIBDFuSpgAdAoAkAUQAeEgMYYAPKIB8AGjAAjKQ2btufQdnxESklgCYZ1WnHOtOXI6ZafLHgF0VCgAVw4tNjgOGhIAETwODDZsbQAVBn0ACjhjACsGdIBKIqpUMDAWPAwwlli8-MFeEJgasFUwLIcpSoo3ejAAcnch3zNhvyHrVDaMMCwu+3EpF364j2HR8f9JqWng0ISklOxs1WL+SuBgMAB1OBYAa0YAQiO4ROTUrGysS+utwezzeQA) didn't change anything from you example besides adding `$Exact` around `...Foo`, it is supposed to work like this, explanation: https://github.com/facebook/flow/issues/3534#issuecomment-287580240

```js
/* @flow */

type Foo = { foo: string };
type FooBar = { ...$Exact<Foo>, bar: string };
type FooBar2 = { foo: string, bar: string };


function fooDentity<T: Foo>(obj: T): T {
  return obj;
}


let x : FooBar  = { foo: 'foo', bar: 'bar' };
let y : FooBar2 = { foo: 'foo', bar: 'bar' };

fooDentity(x);  // Works!
fooDentity(y);  // Works!
```
