### ISSUE TITLE
'flow-typed install' does not stub 'yarn link' modules

### ISSUE THREAD

**Issue by FrozenKiwi** [facebook/flow#6919]
This isn't so much of a bug report as a notice to anyone else with this problem:

Repro steps"
1) 'yarn link my-library' into your project, 
2) 'yarn flow-typed install' : 

Run flow - we see "Cannot resolve module 'my-library'

As per this stack-overflow question: https://stackoverflow.com/questions/51563112/flow-throws-error-cannot-resolve-module-react-redux-even-tho-its-installed I expected stubs to be generated for the linked module.

I also tried resolving using the suggestions at https://github.com/facebook/flow/issues/4015

Workaround/to resolve:
Explicitly stub project 
yarn flow-typed create-stub my-project

**Comment by jamesisaac** [comment]
Please open the issue in https://github.com/flow-typed/flow-typed instead -- the flow-typed CLI is completely separate from this project.
