### ISSUE TITLE
Get type of variable

### ISSUE THREAD

**Issue by jakkdu** [facebook/flow#6921]
This is my program test.js
```
// test.js
"use strict"
let ast = require('flow-parser').parse('var a=1;console.log(a);');
console.log(ast
.body[1].expression.arguments);
```
This is a result.
```
$ node test.js
[ { type: 'Identifier',
    loc: { source: null, start: [Object], end: [Object] },
    range: [ 20, 21 ],
    name: 'a',
    typeAnnotation: null,
    optional: false } ]
```

Is there a way to get the typeAnnotation for 'a' as Number, not null?

**Comment by wchargin** [comment]
Nope. The `typeAnnotation: null` in the result indicates that there is no explicit type annotation in the source code. This is all that you can determine at parse time. To infer the type of `a` and have this annotation flow through to the call site at `console.log`, you would need to actually run Flow on the module—which is a much more expensive and complicated task than the relatively mechanical operation of parsing.

**Comment by jakkdu** [comment]
Thanks!
