### ISSUE TITLE
Generate suppression comments on initial flow-typed import?

### ISSUE THREAD

**Issue by indigoviolet** [facebook/flow#6924]
I did some searches of the flow and flow-typed issues and didn't find a good approach to this, please give me a pointer if I'm missing it.

Upon import of a new library definition into an existing codebase, one would expect many errors to be thrown. I think that it is a huge amount of friction to fix all of those errors at once - a better approach might be to auto-generate suppression comments for all errors of some kind, that can then be burned down over time, so that we can at least stop generating *new* errors.

Thoughts?

**Comment by lll000111** [comment]
Umm... what is stopping you from doing exactly what you say? I mean, tackling the errors one by one. Start with the first one, then the next one, and so on. Just ignore the other 10,000 errors below the one you are looking at.

**Comment by jbrown215** [comment]
Assuming you have no errors before the flow-typed import, you can use the tool named `tool` at the root of the flow repo to add suppression comments. I believe the command would be something like: 
`./tool --check check --comment 'Your suppression comment here. Remember to use single quotes, lest $FlowFixMe be interpreted as a bash variable' --all`
