### ISSUE TITLE
When spreading multiple objects, later types don't override earlier types

### ISSUE THREAD

**Issue by benadamstyles** [facebook/flow#6933]
I am surprised that, when spreading multiple **exact** objects that have the same keys into a new object, those spreaded later don't override those spreaded earlier (as they do logically, in JS).

This may be related to https://github.com/flowtype/flow-bin/issues/93.

Repro on the flow repl [here](https://flow.org/try/#0C4TwDgpgBAIgTgQwGbCgXigEgEoQQEwHkA7AGxAB4BvAHwCgooAPAfgC4oWBnYOAS2IBzOjQC+APjp1QkKAEliwCHHRZcBEuWr1GTDj35CREqTOgAxAQlKqceImUq0GzfbwHCxkugGMA9sQ8UPgc8MioGFQuelDEAK6kpHSiUv6BqAJKcBwKWapRuhwA5AYeRclSAPSVUGbyispQfFxQ-gC2YAjAfABGpNAA7nzAABa14BZWSWlBSjwclsTWqpnKVTUAyiN+CfjERaij0HV+SE0NKkPEUCPKECy+AUFIC1P5LgB0X-gANJ9fqzgySAA).

```js
type Draft = $ReadOnly<{|
  x?: ?string
|}>

type Inter = $ReadOnly<{|
  x: string
|}>

type Final = $ReadOnly<{|
  x: string
|}>

const d: Draft = {
  x: null
}

const inter: Inter = {
  x: 'string'
}

// type Inter is compatible with type Final
const test: Final = inter

// This errors. Shouldn't the type of inter win here?
const f: Final = {
  ...d,
  ...inter
}
```

**Comment by wchargin** [comment]
Duplicate of #6108?

**Comment by benadamstyles** [comment]
Yep thanks, I didn’t find that one. My issue shows that the bug also exists with exact types.

**Comment by wchargin** [comment]
No problem. I’m not surprised that it occurs with both exact and inexact
types—exactness isn’t a problem when spreading values. (Spreading
_types_ is a different story.)
