### ISSUE TITLE
Property 'caretRangeFromPoint' is missing in Document

### ISSUE THREAD

**Issue by philong6297** [facebook/flow#6937]
I have this issue:
![capture](https://user-images.githubusercontent.com/29605147/46062420-f0da6d00-c193-11e8-8a76-9bf75fe92862.PNG)
How can i fix it?
flow version: 0.81.0

**Comment by jbrown215** [comment]
You can make a PR to this repo. You probably want to change this file: https://github.com/facebook/flow/blob/master/lib/dom.js#L614

**Comment by philong6297** [comment]
Can i ask you how to extends the type of 'document' so i can just only declare caretRangeFromPoint property in local without edit the module

**Comment by jbrown215** [comment]
I'm not sure myself. Looks like this was discussed before: #396
As a temporary fix, you can always add a suppression comment.

You might want to reconsider if you should use that function at all. From the documentation, it looks like it's not well supported and isn't going to be well supported: https://developer.mozilla.org/en-US/docs/Web/API/Document/caretRangeFromPoint

**Comment by wilsonshakespeare** [comment]
Please help take a look at this issue: Seems unattended for some time
https://github.com/facebook/flow/issues/5883
