### ISSUE TITLE
Flow should error when unpacking missing property in function parameter

### ISSUE THREAD

**Issue by omninonsense** [facebook/flow#6938]
Flow doesn't error when one of the unpacked fields is missing from the parameter type, while unpacking fields from objects passed as function parameter. It only errors if the unpacked value is later referenced  within the function body.

A snippet which reproduces this:

~~~jsx
/* @flow */

type T = {|
  s: string,
|}


const obj : T = {s: ''}

// Errors - OK
const {s, x} = obj

// Should probably error, but doesn't!
const f =  ({s, x} : T) => s

// Errors - OK
const g =  ({s, x} : T) => x
~~~

[Above snippet on flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqYAvGAN4A+qYYAzgFz0YBOAlgHYDmANKpQF90qAMZwOdDGDgAjAFZgmxMuUZgA5OqGpgwMAFEWLOCzpgAtGADyAaVHjJFOjzAAPAaWnz0usAGUACzgAVxgAEzA8IxMXGWCpMLg8Og51DABCewkpKE8wAApVF3dFIgBKUgA+eh89Q2NTC2s7MWywLjzC5zcPJQqSatcgA)

**Comment by jbrown215** [comment]
It does

**Comment by omninonsense** [comment]
> It does

It didn't; I'm glad it got fixed. 🙂
