### ISSUE TITLE
Functions eat types.

### ISSUE THREAD

**Issue by nmn** [facebook/flow#694]
I mentioned this in other issues, but I was told this bug warranted it's own issue so here it is. I can't explain this with words, so here's an example:

Say I'm using inline-styles:

```
export default {
  container: {...},
  item: {...}
}
```

Using this module in another module and using an incorrect property name will correctly throw errors. But wrapping the object in a function call destroys this:

```
export default autoPrefix({
  container: {...},
  item: {...}
})
```

Now, this module doesn't seem to have any more type info associated with it.

For reference, this is the type I gave to the wrapping function to make this all work:

```
declare function autoPrefix<T> = (obj: T) => T
```

I tried assigning that type in various ways. Let me know if I'm doing something wrong.

---

Workaround:

```
var obj = {
  container: {...},
  item: {...}
}
var toExport: typeof obj = autoPrefix(obj)
export default toExport
```

This fixes everything. 

---

Bonus, I was having this problem with ES6 classes in React and decorators, so I built a eslint plugin to help me avoid these mistakes:
https://www.npmjs.com/package/eslint-plugin-jsx-extras

**Comment by gregwebs** [comment]
This issue and the workaround look very similar to what I encountered in #721.

**Comment by nmn** [comment]
AFAIK this is no longer an issue.
