### ISSUE TITLE
Mapping over same objects and overwriting values

### ISSUE THREAD

**Issue by HenriBeck** [facebook/flow#6942]
When mapping over the same objects, flow doesn't allow to overwrite the values of the objects even though they are the same.
I'm assuming that flow checks merely all of the values of an object and checks if there is only one type as the value and if it's the same.

I guess this is a particular case. I think flow should only compare the types of the same keys and the structure of the object.

```js
type Test = {
	key1: boolean,
	key2: string,
	key4: number,
	key6: Array<{}>,
};

function merge(obj1: Test, obj2: Test) {
	const keys = Object.keys(obj2);

	for (const key of keys) {
		obj1[key] = obj2[key];
	}

	return obj1;
}
```

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqeAzhmALxgDeqAkANZ5YCMAXGAEZxwx4CGAOwA09JlgBMHMgCcAloIDmoxswAsHQQFcAtpzwyV4gGwcAgjJn8sAHmoBfAHyj7AbnRQtggMYY5cQTAdA0U8AAo4TgArdiJSDGEwSKipOLIAShp6bwCyMHESSjAAeWi8XwA6AojoiXT3eig4GTAwnME88SSofOYSTNo6OmSWAG1xAF0i5Ilx5gn3Ont0Ohk8DC0ZQJH3eyA)

**Comment by goodmind** [comment]
It has, for reference #6927

**Comment by lll000111** [comment]
@goodmind Could it be declared using a generic (object) type of the keys of the object? There are similar discussions and issues in TypeScript, and [TS's ahejlsberg wrote that's not possible](https://github.com/microsoft/TypeScript/pull/12253#issuecomment-263132208) (but I don't buy the argument he gives).

**Comment by goodmind** [comment]
I think it should work like [this](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXwGsQBPAZwB4A1AGngBUAueAEgFEAPKTKgPh4AocAIwBW4DEzoBKJgEEYMKMXLMA0iQp0+AKFCRYCFOmx5CG8o3gBvAL4DhYzJJnx5i5aQwwsqAOY9teHhdcGg4eAA3WHh2JisAHygmT28-eJttbTA8TxjSeABeMzJ+dikAbngAeirXBSUVdTILHSC29o6g7VLSAG0ABgBdJgByIRGpatqQBRwYQM7Frr0whCiYeGI4pPgUn18MrJyMTfyiohLiCqm693I9vwCgA), but without two generics

**Comment by SamChou19815** [comment]
This pattern will not be supported as it's too dynamic
