### ISSUE TITLE
Invalid package for linux

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#695]
I downloaded and unziped https://facebook.github.io/flow/downloads/flow-linux64-latest.zip. This archive contains a single file 'flow' which cannot be executed "Cannot execute binary file: Exec format error". There are no examples in the archive.

**Comment by mhagmajer** [comment]
`uname -a` output:

`Linux settlor-HP-250-G1-Notebook-PC 3.13.0-30-generic #54-Ubuntu SMP Mon Jun 9 22:47:59 UTC 2014 i686 i686 i686 GNU/Linux`

**Comment by mroch** [comment]
from the `i686`, this looks like you're using a 32-bit OS, which flow unfortunately doesn't support (tracked in #270).

if that's not the case, please reopen!
