### ISSUE TITLE
optional type coercion?

### ISSUE THREAD

**Issue by edjroz** [facebook/flow#6951]
I'm working with Koa 2 using it's allowed types, at some point I have a middleware to id the request.
this causes the ctx.request.id to have type mixed due to the type declarations of koa 2.

I'm trying to place this `ctx.request.id` in a string template `${ctx.request.id}` However I get this error in trying to do so:

```
Cannot coerce ctx.request.id to string because mixed [1] should not be coerced.
```

I understand that the official koa type describe added properties to the middleware as mixed types:

```
[key: string]: mixed, // props added by middlewares.
```

```Javascript
// @flow
import type { Context } from 'koa';

async function logRequest(ctx: Context, next: () => Promise<void>) {
     return `${ctx.request.id}`;
}
```

I tried maybe destructing it like so (I'm not sure how to properly destruct properties with flow haven't found docs on this):

```Javascript
async function logRequest(ctx: Context, next: () => Promise<void>) {
  const { id }: string = ctx.request; 
  return `${id}`;
}
```

But I get another error type 
```
Cannot assign ctx.request to variable because Request [1] is incompatible with string [2].
```
 naturally since `ctx.request` is a Request type

how should I approach this using flow  ?

**Comment by wchargin** [comment]
You can use `String(ctx.request.id)` to convert the value to a string.

For general-purpose downcasts, see #6482.

**Comment by edjroz** [comment]
Thanks it helped me alot.
