### ISSUE TITLE
callable signature ?

### ISSUE THREAD

**Issue by edjroz** [facebook/flow#6953]
I'm trying to create a router 

```Javascript 
import koaRouter from 'koa-router';
import type { ServerType, Context } from 'koa';

export default function ({ app }: { app: any }): ServerType {
  const router: koaRouter = koaRouter({ prefix: '/hello' });
  router.get('/', worldHandler);

  return app.use(router.routes()).use(router.allowedMethods());
}
```

but I'm receiving an error 
```
Cannot call koaRouter because a callable signature is missing in statics of Router [1].
```

I checked the `koa-router` declaration from flow-typed which seems to be importing the type of the `Router` declaration
roughly like this:
```Javascript
declare module "koa-router"{
  declare class Router{
    constructor(opts?: {
      prefix?: string,
      sensitive?: boolean,
      strict?: boolean,
      methods?: Array<string>
    }): Router;
    // Router Implementation
   }
  module.exports = typeof Router;
}
```

Why is the flow checker throwing this error ? Isn't the export of typeof Router a callable class?

**Comment by lll000111** [comment]
const router: koaRouter

You assign the *module* as the type. I would use something that's actually __in__ that module :-)

**Comment by edjroz** [comment]
I let `flow-typed` handle that for me so it's most likely this one: 

https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/koa-router_v7.2.x/flow_v0.25.x-/koa-router_v7.2.x.js

**Comment by edjroz** [comment]
As it seems since the module Koa-router exposes a class, so it should be initialized in order to execute it.

```Javascript
  const router: KoaRouter =  new KoaRouter({ prefix: '/health' });
```
