### ISSUE TITLE
Property is missing in null or undefined

### ISSUE THREAD

**Issue by ixio** [facebook/flow#6954]
I'm new to flow so I hope I haven't missed anything obvious.

I'm using it with React and I have a lot of components that have state data coming in from AJAX calls in componentDidMount. I figure that the best way to deal with that is to have state objects as Maybe-Types and initialize them with 'null'.

However I get a lot of errors like:
```
Cannot get this.state.user.name because:
 • property name is missing in null or undefined [1].
 • property name is missing in null [2].
```
Even if I have a condition checking that this.state.user exists.

It looks like a bug to me because the conditions seem "brittle" (not sure if random would be a better word). I might have 5 properties set up the same way and only some of them will raise errors.

I tried to make a typical example of my problems:
[flow.org/try link](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3qAMKwawB2hzeAvqJFo6AORYS5fgG5EiHAE90hUAGUcxHHIC8NRKFABXAM6EsALlAB+apq2hkAE2PNtqAEYGKFrc2KpCx3TizJmAHMLDkQOcVJoYl1dUABVfSxQQgAPFWZrWIYmVnYAHgA3WBsqRWVCAD4NLV9y0HVzSx1Eu21oaBCJLVJGTFycABEbAFlYbXYACgBKassQUGtYUF9tSEhQaGQAazliZlAAQQApA4ANUFJidtAcJYDkPFqVToshDINp2a1kdYmAQhwAAtkLoAHRPQigvQGGaNJqgIQ4bRYfYTNzwvLWZAFCro+GgPLoCoAGVgxCxQXiiVAoNpeWARLxlnpWJxTKm6NCTWghDwkGQPI8XnqN2BYIhUMSoKFkKE6CipEIE34Aio-AA+vwZgBqASg0i6ApidGI5GopmY7G4-FaQkVBIGUAAYmoQJB4KUKklBlBNg49MZNoJRIAEnJAdFQMRQIEhMpQDLjK6xR7yt6sNLPIR-QzrTa7Q6kgFIEt+TyrLok2W2Fmc4GMcBWXmtBytKFQkA)
If you remove line 27 there are no more errors (another "brittle" condition).

If there is a better way to init typed states in React with flow I'm open to learning. However seeing how the errors pop up it looks to me as if there is a bug in flow anyways.

**Comment by wchargin** [comment]
[Function calls invalidate refinements.][docs]

Removing the `.replace(" ", "_")` in your code fixes the error.

You can [bind the value locally to avoid the invalidation:][try]

```js
  render() {
    const {user} = this.state;
    if (!user) {
      return (
        <div>
          <p>Loading User ...</p>
        </div>
      )
    }
    let filename = user.name.replace(' ', '_') + '.csv';
    return (
      <div>
        <p>User #{user.id}</p>
        <p>He has a great name: {user.name}</p>
        <p>User info file is: {filename}</p>
      </div>
    )
  }
```

(Yes, using maybe-types is a good approach.)

[docs]: https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations
[try]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3qAMKwawB2hzeAvqJFo6AORYS5fgG5EiHAE90hUAGUcxHHIC8NRKFABXAM6EsALlAB+apq2hkAE2PNtqAEYGKFrc2KpCx3TizJmAHMLDkQOcVJoYl1dUABVfSxQQgAPFWZrWIYmVnYAHgA3WBsqRWVCAD4NLV9y0HVzSx1Eu21oaBCJLVJGTFycABEbAFlYbXYACgBKassQUGtYUF9tSEhQaGQAazliZlAAQQApA4ANUFJidtAcJYDkPFqVToshDINp2e6WXxo9Ay46hwAAtkLoAHRPQjiJrIdYTACE-ywM0aTVAQhw2iw+wmbnReWsyAKFXx6NAeXQFQAMrBiESgvFEqBway8sAqWTLOyiSSuVN8aEmtBCHhIMgRR4vPVmgZwVLCOChOgoqRCBN+AIqPwAPr8GYAagE4NIugKYnxmOxuK5hOJpPJWkpFQSBlAAGJqMjwTYOOzOY6KVSABJyYHRUDEUCBITKUAK4xexLyzyEP0ch2O52upIBSBLcUiqy6ROFtip9MBgnAXmZrQCrShUJAA

**Comment by ixio** [comment]
Thank you for the quick answer. Looks like this is indeed not a bug but the current state of affairs. Your solution works well for me. Thanks again.

**Comment by wchargin** [comment]
You're welcome; glad that it worked for you.
