### ISSUE TITLE
Cannot resolve module for relative paths 

### ISSUE THREAD

**Issue by sainareenchand** [facebook/flow#6960]
Example in file at path has the below import:

src
 &nbsp; &nbsp;-abc
 &nbsp; &nbsp; -def
 &nbsp; &nbsp; &nbsp; &nbsp; ghi
 &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;--hello.jsx
 &nbsp; &nbsp; &nbsp; &nbsp;words.js

(ghi folder and words.js are in the dir 'def')
       
   ```
In src/abc/def/ghi/hello.jsx:

   import words from '../words';

--> Throws error "Cannot resolve module ../words
```
My .flowconfig

```
[ignore]
.*/node_modules/.*
.*/build/.*
.*/dist/.*

[include]
.*/src/.*
.*/test/.*

[libs]
flow-typed

[lints]

[options]
all=true
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src
module.name_mapper='^/\(.*\)$' -> '<PROJECT_ROOT>/\1'

[strict]

```

Please help how to resolve '../words',

Thanks in advance.

**Comment by GEMI** [comment]
Why was this closed without any comment?
