### ISSUE TITLE
Strange bound-name bug when declaring type within block scope

### ISSUE THREAD

**Issue by talbenari1** [facebook/flow#6961]
The following code throws a strange error:
```
{
  type Foo = string;
}
```
Here's the error message:
```
2:   type Foo = string;
          ^ Cannot declare `Foo` [1] because the name is already bound.
    References:
    2:   type Foo = string;
              ^ [1]
```
According to Flow, the type is being redeclared... in the same place it's being declared.

[(Try Flow link to the above code)](https://flow.org/try/#0N4KABGAuCeAOCmYBiB7FYC8YDOkBOAlgHYDmA3CAL5A)

**Comment by jbrown215** [comment]
Type aliases being declared within a block is a known problem, but there is no one currently working on fixing it.

**Comment by mroch** [comment]
the error is certainly clowny, but it's not clear to me that the correct fix is to allow type aliases in blocks rather than to fix the error.

I'd consider it a syntax error to use `type` in a block, or anywhere other than a top-level script/module. so, we should also ban it in function bodies as well as blocks.

if we do allow it, I think we'd want to do some analysis to make sure it doesn't leak. I believe (cc @panagosg7) that we should do a similar thing for types that are used in exports but not exported themselves, so that other files can annotate properly.

for example:

```
function foo() {
  type Local = string;
  const x: Local = "foo";
  return x;
}
```

what is the return type of `foo`? ([try flow](https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBKRBvAUIxKATwAcBTRAGTggEMAbRAXkQGcoAnGMAcwG58iCAnaIAHgC4qNBs0QAiFHHkCCHMlBAckYgQF9cuNEsxTqdehj5A))

similarly:

```
// foo.js
opaque type Local = string;
export function foo(x: Local): Local { return x; }

// bar.js
import {foo} from './foo';
const x: ???? = foo("bar"); // can't annotate this!
```

**Comment by goodmind** [comment]
I think it's fine to use type aliases in blocks or functions, I often use functions ala-ML modules

**Comment by goodmind** [comment]
@mroch in your example return type of `foo` is just `string`, it makes sense that alias is inaccessible outside of a function

**Comment by mroch** [comment]
ok, how about an opaque type?

```
function foo() {
  opaque type Local = string;
  const x: Local = "foo";
  return x;
}
```

**Comment by goodmind** [comment]
opaque type inside function is pretty much `Symbol()` if it was supported

**Comment by goodmind** [comment]
It's also strange that generic is mixed if we return it from function without return type, but it's unrelated I think
```js
function generic<T>(t: T) {
  declare var hey: T;
  return hey;
}


let foo = generic(1) // mixed
let bar = generic('') // mixed
```
[link](https://flow.org/try/#0GYVwdgxgLglg9mABAcwKZlQJxhAPAFQD4AKKALkXwEpEBvAKEUQBNUIAbAQ01UQDduiABaoAnhXwBuRoh5QQmJCNHSAvvQ3tUURMDhxEAXhTosOYgEYaAemuIAtjAAeqZvS06ARoONoM2CGIAciCbO0cXZiA)

**Comment by goodmind** [comment]
@mroch what you think about: 
- prevent opaque types declared inside function from returning (can't go outside of function)
- regular types can be returned, because it is just alias

**Comment by goodmind** [comment]
Actually I tried to use opaque type inside function, and I think it should be scoped to function or make it impossible to return it from function

```js
// file a.js
// @flow

import {foo} from './b';

const hey = foo().value;

const wow: typeof hey = foo().value; // no errors, same opaque type scoped to file location, and not function call

```

```js
// file b.js
// @flow

export function foo() {
  opaque type Local: string = string;
  const m: Local = "str";
  return {
    value: m,
    toString(): string {
      return m;
    }
  };
}
```

**Comment by wchargin** [comment]
FWIW, I also find it very useful to declare types locally within a
function, and would be sad to hear that that ability were on the
chopping block.

This would be particularly frustrating with combined with test runners
that ask everything to be inside a `describe` block. Here are some type
definitions declared 2300 lines into a test file, which very much do not
want to be hoisted to the top:

https://github.com/sourcecred/sourcecred/blob/8f9e967496ef82b11ea6d09c9ee408d18f3a8420/src/graphql/mirror.test.js#L2372

And when test cases are explicitly testing that a particularly tricky
type signature has the right properties, local type definitions are
almost like local variables in spirit:

https://github.com/sourcecred/sourcecred/blob/8f9e967496ef82b11ea6d09c9ee408d18f3a8420/src/util/map.test.js#L12-L14

**Comment by wchargin** [comment]
> ok, how about an opaque type?

Also FWIW, I _do_ use opaque types within functions, and would use them
within block-scopes if not for this bug. I use them to establish
invariants that only make sense within the context of one function.

[Here’s an example][1] (whose particulars I do not endorse as production
code):

```javascript
// @flow

declare class Element {
  innerHTML: string;
};

function foo(element: Element, userInput: string) {
  declare opaque type SafeHtml: string;
  function sanitize(id: string): SafeHtml {
    const escaped = id.replace(/[<>=&"]/g, (c) => `&#${c.charCodeAt(0)};`);
    // Only the following line needs to be audited for security.
    return ((escaped: string): any);
  }
  function renderEmphasis(element: Element, text: SafeHtml) {
    element.innerHTML = `<em>${text}</em>`;
  }
  renderEmphasis(element, userInput);  // type error: good
  renderEmphasis(element, sanitize(userInput));  // OK: good
}
```

And here’s a real-world example, which cites this bug:

https://github.com/sourcecred/sourcecred/blob/8f9e967496ef82b11ea6d09c9ee408d18f3a8420/src/graphql/mirror.js#L1259-L1278

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaFtgM7GgCi0aAtmgHYAuoA3oqKAJZ11q4ASAFQCyAGQBcoYg1xcA5gG5EAX0WJIAVzoYGHWHVCRYsABRoqtRhMo16DADSh1xXgEk6AB3UMJUmXVkAlCxsoOhE+KCw7tgAjuoEDACe7gQAytiQaHwM1NA+0nKK7BpaOnqS2HQcOgBeaMYcKPl+gRLpmdm5wezsGHpSoGjEGNgpKKAAvJwoAHT47jgY9cAA2gA8AHwTAGQARAC6wLIOxhhBExugAAbbAMQAJMwYMxgAFngAwrDoAIIMxgAGAIqK4BIo9ECgADydGgiVADFeBEM0Dg8DkoGgXAIPDQKDIDFgoAARgRsOoUNU8QZYLhJJh1DIkjMQux8AxGfpjKZhqM8c05AEJJVEmCQkoQiVtLp9Pg6OhcORqO53sQOMRTOZbFYtYwHAw0AAPbygdpZHLQIKsHqDXUMGZcHj8YQiSbXNY0DaPA3GpRrYCeq7giVs+gKpUqkjqzU2PWOZy4NyeBhg9iQpIpQa4XC0iSyIwoEJy8PK1XRsyx+wVKq1epOVweLwBVOgSFQgDSeYLyiAA

**Comment by goodmind** [comment]
@mroch any conclusion?

**Comment by Shelagh-Lewins** [comment]
It would be great if the error message could be changed to better explain the issue and possible solutions.

**Comment by SamChou19815** [comment]
Looks like this is no longer an issue.
