### ISSUE TITLE
JSX Null Check Components

### ISSUE THREAD

**Issue by thejuan** [facebook/flow#6965]
We are using this library to allow JSX based control flow https://github.com/romac/react-if
Is there a way to tell flow that a type has been null checked inside this component?

```
 <If condition={this.selectedTeamMember}> <-- property can be undefined
          <UserInfo  user={this.selectedTeamMember}  />  <-- Flow error as user prop doesn't accept undefined
  </If>
```

**Comment by wchargin** [comment]
No, there is no way to do that, and moreover it does not make sense.

Recall that your code desugars from

```jsx
<If condition={this.selectedTeamMember}>
  <UserInfo user={this.selectedTeamMember} />
</If>
```

to

```js
React.createElement(
  If,
  { condition: this.selectedTeamMember },
  React.createElement(UserInfo, { user: this.selectedTeamMember })
);
```

In particular, the children of the `If` (namely, your `UserInfo`) are
evaluated regardless of the `condition` that you provide.

So, for instance, suppose that `this.selectedTeamMember` is declared to
have type `?string`. If Flow refined it to be of type `string` within
the children of `If`, as you’re suggesting, then the following would be
considered safe:

```jsx
<If condition={this.selectedTeamMember}>
  <UserInfo user={this.selectedTeamMember.toUpperCase()} />
</If>
```

But this code would throw at runtime when `selectedTeamMember` is
`null`, before the `If` component is even rendered!

Consider instead using the standard React pattern for conditional rendering:

```jsx
this.selectedTeamMember != null && <UserInfo user={this.selectedTeamMember} />;
```

[This typechecks just fine.][1]

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgBEWJ5tA3IgCaGnTEOgBuPUAA0AXAUY4AJAGFqmAHaF5OACoBPdIQA8AbwCuAZ0JYxBnFmTyA5gF8AfKw5cehfoNTE1AI0IBVIyagAPxmFtasiCCgKgAWyAagkMTI0Ak4sKA4GpwxnADWoAAUVrCwbACUIpFgWkKghsYAvDoe3n4BNqDADojV0XFp2aS5pHkJxaUVVYWtPv7GoACEjaDyetDQoABkW6C19QHNs+3Gnd3lrEA

**Comment by thejuan** [comment]
Appreciate the detailed reply!
