### ISSUE TITLE
/* @flow strict */ On all source files

### ISSUE THREAD

**Issue by esovan** [facebook/flow#6967]
With `all=true` i can make flow check all files. How do i expand this to strictly checking all files?

My current .flowconfig:
```
[ignore]
.*/node_modules/.*

[libs]
flow-typed

[options]
all=true
module.use_strict=true

[strict]
nonstrict-import
unclear-type
unsafe-getters-setters
untyped-import
untyped-type-import
```

The last strict part is not applied unless i type `/* @flow strict */` in files. 
I want to avoid adding a comment to all files if possible :)

**Comment by jbrown215** [comment]
cc @gkz

**Comment by mxstbr** [comment]
I'd love to have `all=strict`!

**Comment by jbrown215** [comment]
as far as I understand strict, it's actually just setting all of the lints in `[strict]` to error. Try changing the `[strict]` section to `[lints]` and add `=error` to the end of each line. So:

```
[strict]
nonstrict-import=error
unclear-type=error
unsafe-getters-setters=error
untyped-import=error
untyped-type-import=error
```

That should set all of these lints as errors when flow type checks. Let me know if this isn't sufficient.

**Comment by mxstbr** [comment]
I had already set `[lints] all=error`, would that suffice?
