### ISSUE TITLE
Can't refine a primitive enum when compared to a const, but can refine object

### ISSUE THREAD

**Issue by eoingroat** [facebook/flow#6968]
using v0.82.0

Here is a simple case of something that has been biting our team for a while:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1AQQFygBEuRoAvMaQNwrragBChRjZlrRtdmOsBoAN4A3QlgCeABwCmsSHgC+FIaMW1UvULGYqxU2fMZLKIwke6QArmmRYAlui0AKYQENol6XplytuUAA+oBI+8toAlEKIAJB2kC7ungB0whTklLiRgjHRCR5ewfq+-OG0oOWgCohViFY29o7xbvneBniBhaFMWTFxeZ5pGT3Ruc2erb6ZZRVVNXW2DmigkABM-QUhbf5Bm76MPeVxoOuDVEQHFesT8lOI5bOItdYLjgC20lgAFrAAJldnHU4FyOJ3SHFIF3K-xI52msyAA

What is shown is several ways an enum can be refined, depending on what types constitute the enum, and that an enum of primitive types will not refine when it is compared to a (const) variable - but enums of other types will.

I suggest that this is a bug - and that the following should work without error:
```
let value: "A" | "B" = "B"
const A: "A" = "A"
if(value === A) {
  (value: "A");
}
```

full code below using v0.82.0:
```
// @flow
const A: "A" = "A";
const B: "B" = "B";

const oA: {v: typeof A} = {v: A};
const oB: {v: typeof B} = {v: B};

function o(value: typeof oA | typeof oB) {
	if(value.v === A) {
		(value: typeof oA);
    }
}

function f(value: typeof A | typeof B) {
	if(value === A) {
		(value: typeof A);
    }
}

function f2(value: typeof A | typeof B) {
  if (value === "A") {
    (value: typeof A);
  }
}

function method(value: "A" | "B") {
  if (value === "A") {
    (value: "A");
  }
}
```

**Comment by skeet70** [comment]
Related to object refinement working here, using object unions introduces its own related [issue](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCZwKYDOYAdnAC5gJwBOA1qmQJ4AOeYAogJIAqAEuwCUwAXjABvWnkYAuMAHIA8gDl2) reported by @josh-schlick. These two things combined seem like a serious problem. Avoiding annoying stringy issues is one of the main reasons for using flow in our product. Is this a new issue or just something that's been around forever?
