### ISSUE TITLE
[bug] union type is not respected when using spread

### ISSUE THREAD

**Issue by gajus** [facebook/flow#6974]
```js
type RegisteredTestType = {|
  +id: string,
  consecutiveFailureCount: number | null
|};

const createTest = (registeredTest: RegisteredTestType): RegisteredTestType => {
  return {
    consecutiveFailureCount: null,
    id: '1',
    ...registeredTest
  };
};

```

Actual:

```
3:   consecutiveFailureCount: number | null
                              ^ number [1] is incompatible with null [2].
References:
3:   consecutiveFailureCount: number | null
                              ^ [1]
8:     consecutiveFailureCount: null,
                                ^ [2]

```

Expected:

No error.

Test:

https://flow.org/try/#0C4TwDgpgBAShDmBLAzsCAnCATAKhVO40AvFAN4A+AUFFANSJYBcUq6iAdvADQ1QDGAew7II-AK7BEANwgAxAIaIANuMwBhQeI7AWHcQFsARhigUo+5cqoUAvgG4qVISOADMCtHlRRSACkwkVAxsb11YBBQ0TFx8YEJIAEoWOCDo0LiEkgA+cj5MYDUOPNpaF1EJKVlFFTUITW1wy2VeUqhGFgByAEZO1tKAOiHAqJDY1D4HKgcgA

**Comment by gajus** [comment]
For whatever reason this works:

```js
type RegisteredTestType = {|
  +consecutiveFailureCount: number | null,
  +id: string
|};

const createTest = (registeredTest: RegisteredTestType): RegisteredTestType => {
  return {
    ...{
      consecutiveFailureCount: null,
      id: '1'
    },
    ...registeredTest
  };
};

```

https://flow.org/try/#0C4TwDgpgBAShDmBLAzsCAnCATAKhVO40AvFAN4A+AUFFANQDGA9gHbIQMCuwiAbhADEAhogA2nTAGEmnFsABcUFpwC2AIwxQKSzqNEAaGvURZFqdIhbwqFAL4BuKlWZtgUBpiFo8qKKQAUmEioGNg+CrAIKGiYuPjAhJAAlIpwwTFh8YkkAHzkRpjAEiz5tLQAdJVkRmXurOxcPPzCYhIQ0rIRynqGtbQmigDkAIyDNVC2vWWV5UHRoXGoRg5UDkA

**Comment by nmote** [comment]
This no longer errors on master
