### ISSUE TITLE
[Question, Maybe Bug?] Flow is not Reporting an Error if a Class/Object does not implement an Interface when Using Wildcard '*' ES6 export syntax

### ISSUE THREAD

**Issue by thedanchez** [facebook/flow#6977]
Using Flow in my project and just want to say that I love the work you guys have done with this thing. It's an incredible tool for the JS community. Please keep making it better.

One question I have as the title states, should Flow be reporting an error if something does not conform to an interface entirely? Or is the implementation of the interface methods optional? 

For example, given:

```js
// @flow
interface IAuthInterface {
  logInSuccess(): void,
  logInFailed(): void
}

class LogInView extends React.Component implements IAuthInterface {
  constructor (props) {}
  logInSuccess () {} 
  render() {}
}
```

When I run `flow` here, it does not report any errors, but I'm thinking it should since my `LogInView` does not fully implement the `IAuthInterface` I specified.

**Comment by thedanchez** [comment]
@wchargin Thanks for the reply! Super helpful. 

Sorry about that. I short-handing everything in my snippets with respect to importing React and whatnot. Also using ESLint and WebStorm to strip out the need of semicolons in my JS files which is why you don't see them. But I'm surprised I can't get Flow to throw me an error even though I don't implement all the interface methods I define...

**Comment by thedanchez** [comment]
@jbrown215 I wish it was something that simple that I missed, but unfortunately no. I have all the necessary `// @flow` annotations in place.

@wchargin So I just made a breakthrough observation around my problem that I'm hoping you can further shed light on. 

There are two parts to it: flow configuration and implementation. The first I was able to address and it had to do with what was outlined in this issue thread [here](https://github.com/facebook/flow/issues/5180). Feel free to comment on my applying of this.

Before I go to the second, which is still unresolved, I have to apologize first. In my haste of writing the initial post, I wasn't entirely truthful with the setup I had. I wrote out what I believed to be the final output or end state of the setup I actually have but obviously I was wrong. I discovered my error after trying out my "shorthand" expression up top as is and I ended seeing the same thing you did which is Flow producing an error.

So I'm going to paste both versions (the same one above and what I ACTUALLY have) for clarity sake.

```js
// LoginView.js
// @flow
// SHORTHAND VERSION -- what I 'thought' I had essentially
// 'npm run flow' correctly reports an error

interface IAuthInterface {
  logInSuccess(): void,
  logInFailed(): void
}

class LogInView extends React.Component implements IAuthInterface {
  constructor (props) {}
  logInSuccess () {} 
  render() {}
}
```

```js
// REAL VERSION -- what I actually have

// modules/myLib/separateFile.js
// @flow
export interface IAuthInterface {
  logInSuccess(): void,
  logInFailed(): void
}

// LoginView.js
// @flow
// 'npm run flow'  does NOT report an error
import type {IAuthInterface} from 'modules/myLib/separateFile'

class LogInView extends React.Component implements IAuthInterface {
  constructor (props) {}
  logInSuccess () {} 
  render() {}
}
```

Hopefully what I wrote makes sense

**Comment by Soreine** [comment]
I just met the same problem. It looks like the wildcard export syntax `export * from '...'` is not supported by Flow.
The same issue was reported here https://github.com/facebook/flow/issues/6234
