### ISSUE TITLE
Nesting generic react components throws error if callback with generic is included

### ISSUE THREAD

**Issue by danrot** [facebook/flow#6978]
We have two react component, whereby both of them have a generic type. The generic type is used in a prop called value and in a callback. One of these react components uses the other one, and this is leading to some errors.

I have created the following minimum example showing this error (which I would say is not correct) in this [flow try](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAKV6AM4AeACoA+UAF5QAb0ShQsAHYBhABbFlAc0IAuUAApRASmmSAbrGQATADQLQF4tACu+0KIcBfVolLQxIKCoKoATGKShAAeOITKNiFEZDgAdKrUmMrxOML8sEKRkvKI3mwBQSGqAIyRoDFxCUmMaRkYKjl5AiISxY6aCdCEGlq60kbObh6m5nKOAJA46siCqejdqSojOoSGk+4mrIq+jo4MCYRYhmbyiooMOK5YyqDC4Y53SmoDulKySytUgMbENtroyp9FPtCH8Aat1gVVtCIXdgOIjqAyt4gA). The code looks something like this: (copied from the flow try)

```javascript
// @flow
import React from 'react';

type Props<T> = {
  onChange: (T) => void,
  value: T,
};

class C2<T> extends React.Component<Props<T>> {

}

class C1<T> extends React.Component<Props<T>> {
  handleChange = (value: T) => {
  	this.props.onChange(value);
  };
  
  render() {
    return <C2
      onChange={this.handleChange}
      value={this.props.value}
    />;
  }
}
``` 

I am currently using flow 0.71.0, but the issue also seems to exist in the latest release.

**Comment by wchargin** [comment]
This has to do with the fact that `handleChange` is declared as a class
property. [It suffices to desugar the property manually:][try-1]

```js
class C1<T> extends React.Component<Props<T>> {
  handleChange: T => void;

  constructor(props) {
    super(props);
    this.handleChange = (value: T) => {
      this.props.onChange(value);
    };
  }

  render() {
    return <C2 onChange={this.handleChange} value={this.props.value} />;
  }
}
```

[try-1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAKV6AM4AeACoA+UAF5QAb0ShQsAHYBhABbFlAc0IAuUAApRASmmSAbrGQATADQLQF4tACu+0KIcBfVolLQxIKCoKoATGKShAAeOITKNiFEZDgAdKrUmMrxOML8sEKRkvKI3mwBQSGqAIyRoDFxCUmMaRkYKjl5AiISxY6aCdCEGlq6BqLmTtY2foqkKoI4WK7k2Ibo3WbyioqCrtxY65usO6A46siCqQM2QyM6PDKGzm4eppPbp2cXVxsFVyp7rpni53CYTjtfI4yo4GAlCIcto5FAwcK4sMpQMJwko1ANdFJZOdLtctLdhvjCN4nKDCITib9uqkXu5qcBxBCymUgA

[It similarly suffices to declare `handleChange` as a function rather
than a class property:][try-2]

```js
class C1<T> extends React.Component<Props<T>> {
  handleChange(value: T): void {
    this.props.onChange(value);
  }

  render() {
    return (
      <C2 onChange={this.handleChange.bind(this)} value={this.props.value} />
    );
  }
}
```

[try-2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgAKV6AM4AeACoA+UAF5QAb0ShQsAHYBhABbFlAc0IAuUAApRASmmSAbrGQATADQLQF4tACu+0KIcBfVolLQxIKCoKoATGKShAAeOITKNiFEZDgAdKrUmMrxOML8sEKRkvKI3mwBQSGqAIyRoDFxCUmMaRkYKjl5AiISxY6aCdCEGlq6hs5uHqYGVrZyjoo46siCqejdqSojOoTjLu4mrIpljgwJhFiGZvKKigw4rljKRgu3wuFKagO6UrJLK6kBjYhttdKkAEbIBKGf6CEzeJz7Qi-WFrDYTdwI4DiV6HRxlMpAA

I agree that this behavior is a bug: Flow should accept both versions.

**Comment by danrot** [comment]
@wchargin Thanks for letting us know how to fix it! Would still be nice if the bug would be fixed one day :smiley:

**Comment by SamChou19815** [comment]
No longer errors
