### ISSUE TITLE
can not cast a class property from base class to subclass

### ISSUE THREAD

**Issue by popolan1986** [facebook/flow#6979]
try this in flow online:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2ASQDscAXAJwFcBbAUyNLAG8BfVDbPMAEQFlewtAB6l6AE3zEyVOg2aowYAEZZyACgCUzNmw658AYTgMsASyK1y8xeek16pAFyESFewwDcqXZn1gAypRKRibmloIi4obGpGYWVkwKYOjGduikcOpaiYqKOJQADpaaXooAkKQAFqY4AHS2brKMALxgFkh8vCVJbIpJUHBwmta5Ka5gYtTUzp1grWpVNfWuMg4z-BqlYDqoQA

/* @flow */
class Instrument {}

class DMM extends Instrument {
  bar() {}
}

class Container {
  instrument: Instrument;
}

class SubContainer extends Container {
  constructor() {
    super();
  	this.instrument = new DMM();
  }
  
  foo() {
    const dmm: DMM = (this.instrument: DMM);
  }
}

I expect the casting works in foo method.

**Comment by wchargin** [comment]
@jbrown215 is correct. To elaborate, you can solve this by [making
`instrument` read-only on the superclass and narrowing its declared type
on the subclass:][try-1]

```js
/* @flow */
class Instrument {}

class DMM extends Instrument {
  bar() {}
}

class Container {
  +instrument: Instrument;
}

class SubContainer extends Container {
  +instrument: DMM;
  constructor() {
    super();
  	this.instrument = new DMM();
  }
  
  foo() {
    const dmm: DMM = (this.instrument: DMM);
  }
}
```

[try-1]: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxjAhgZx2ASQDscAXAJwFcBbAUyNLAG8BfVDbPMAEQFlewtAB6l6AE3zEyVOg2aowYAEZZyACgCUzNmw658AYTgMsASyK1y8xQGpz0mvVIAuQiQqOGAblS7M+sABlSiUjE3NLQRFxQ2NSMwsrJgUwO3cZJ1c+Xh9FdGMHdFI4dS1kxUUcSgAHS01csABIUgALUxwAOnsPWUYAXjALJGz6lLZFFKg4OE1rCvz3MDFqaiz+MAG1Vvau9M8XHn4NBp1UIA
