### ISSUE TITLE
Early return doesn't refine value in classes methods

### ISSUE THREAD

**Issue by ArmorDarks** [facebook/flow#6981]
### Test case

[Flow test case](https://flow.org/try/#0PTAEBMHsFMGcDsDkAXUB3SAnA1gKFwMYA2AhrLKACpzICMoA3rqKALYkAOoAvKPAK5Ei+FshqgAFAEoAXKABukAJbhGzFqCUAzSQEJkACyWwAdOw5TQmaMn6Z4IjYeNnOJyPGjT1oo6fMmyBjeLAC+uOG4IOhY2LD4xGQU1LDIAExqLOY8fILC6mKpkrIKyqpMGpo6Evp+rhZWNnYOPqDO-m4eXlLq4ZEEHkXZvAJC+NEYOPG4WvzwBMhKHm00AMzFcooqmVV65pbWtvbq6gFdIWxuQZDe4UA)

```js
// doesn't work

class Test1 {
  map = null

  test (): void {
    if (!this.map) return

    this.map.one()
    this.map.two()
  }
}

// works

class Test2 {
  map = null

  test (): void {
    if (!this.map) return

    this.map.one()
  }
}

const map = null

// works

function test3 (): void {
  if (!map) return
  
  map.one()
  map.two()
}
```

### Expected

To yield no errors, since code after early return will never execute

### Received

`Test1` will yield Flow error:

```
Cannot call `this.map.two` because property `two` is missing in null [1]
```

despite the code after `if (!this.map) return` will never execute.

Note that error appears only if two different methods on `this.map` executed and does appear exlusively within classes methods.

**Comment by wchargin** [comment]
[Any function call invalidates refinements.][1]

[1]: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

As far as Flow knows, your `this.map.one()` call might have the side
effect of resetting `this.map` to `null`.

As you can see, binding `map` before the execution prevents the error.

**Comment by ArmorDarks** [comment]
I know and that would be true, if not the fact that code after return with a null check will never execute? So, side effects will ever occur.

That error would make sense if we'd had following code:

```js
class Test1 {
  map = null

  test (): void {
    if (this.map) {
      this.map.one()
      this.map.two()
    }    
  }
}
```

But doesn't make sense with an early return.

**Comment by wchargin** [comment]
> I know and that would be true, if not the fact that code after return with a null check will never execute. So, side effects will ever occur.
> 
> That error would make sense if we'd had following code:
> 
> […]
> 
> But doesn't make sense with an early return.

Your original code

```js
class Test1 {
  map = null

  test (): void {
    if (!this.map) return

    this.map.one()
    this.map.two()
  }
}
```

is exactly equivalent to the second version

```js
class Test1 {
  map = null

  test (): void {
    if (this.map) {
      this.map.one()
      this.map.two()
    }    
  }
}
```

and in particular if in _either_ version `this.map.one()` mutates `this`
such that its `map` argument is `null` (which it might) then the
following line `this.map.two()` _will_ execute and error. The fact that
there has previously been an early-return is not relevant.

To be entirely explicit: you did not define the type of `map`. I can
provide the following definition that causes an error with your exact
code:

```js
// @flow

class MyMap {
  target: Test1;
  constructor(target: Test1) {
    this.target = target;
  }
  one(): void {
    this.target.map = null;
  }
  two(): void {}
}

class Test1 {
  map = null;
  test(): void {
    if (!this.map) return;
    this.map.one();
    this.map.two();
  }
}

const test = new Test1();
test.map = new MyMap(test);
test.test();
```

This code raises “TypeError: Cannot read property 'two' of null” on the
call to `this.map.two()`.

**Comment by jbrown215** [comment]
@wchargin is correct. thanks for the help!

**Comment by ArmorDarks** [comment]
Yeap, you're right after all. For some reason, I was under impression that early return should prohibit execution of further code completely, but I realized that if `this.map` won't be null, it will pass early return and might error on the second call.

I'm sorry for the confusion. You're explanation just took my thoughts in the wrong direction...
