### ISSUE TITLE
Generic 'type' definitions are ignored, but primitive/class type definitions are enforced

### ISSUE THREAD

**Issue by philberesford** [facebook/flow#6985]
Hello,

I've been working on a generic mapping function to take an instance of one `type` definition and return an instance of a different `type` definition. Essentially, it's a mapping function - where the input and output types are determined by the consumer, hence the use of generics.

However, when these `type` definitions follow the pattern `type Something = {}`, Flow appears to ignore the type annotations and _does not_ report an error when incompatible parameters are passed to the function. But, when the `type` definition is either a `class` or a primitive type (`string`, `number`), then Flow _does_ show an error, as expected.

I've created an example of this at [Flow/Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAUQA9sBbABxgFMBhHfAHgFkAaMAEQD4wBvVAJAB9MtgoVqAJwBcYABTMAlGAC8PDgG5UYMNrACMcAHa4ALpICuGU3EnzR4qbIXK1nRfx0CBpgBYBLXAA6ETEJOxUwB3CtAQBfdAFcbAA3ajkyWSVZDj49HR1JalMLSSMwP0CQ6KkMxS0CsASE1FMATwkwADE4OAAVDupVPiatVsGwACFsSQHOyN5R9Cw8Ah64elWRlpX8KZnNvcWW9s6AZXN-IwBzOaHIs0kr67HToYA5CzIAIyk74aMX1+kjGhhMpjAUF6d2ms0GzDCUmGcnWd0U0lh-zcnjARRKZT4cS0ROWxjMkN6h1wsKpCMcEXk6yp6JpDAI2L0eNK5SM1CQrNWcnqqBJmDJEMezzunx+f3hiIZcguTxuaOkMuBWJ4OK5BIAjMTQeKKf1BpjBgBJcHYIwYe5gXlIEjkKh0NmMVGDdjmiRcORQ00SH3UOnhYVg8lkOAAE2oMD1sk980JWgDMJmdytZhtdqCyTSGRjcb19QEwGAYHecDAUkktlwYvBUSLMAATLJg8NeCS02aM5brbbqHnUuko7G26Xy5Xq7X62AALQzmuSOuSAgIXzUcpwcLYUzPMDGMAYCxmOBkCoTWNQK7+A9koJgM6+OAWGDRipbopgX4AflJJsAypAV8CzUwc3tR0iFISgaCpD1KTZb0DjZP1gLZUDcFDKRw2Ncc4wAZkTJCtkiaCmTZIVU1I-AsPAyCRwLAiYEIqcKyrFc1wbCMIRYgAWDtULIh0+X2SQqWo1AMNWejB1zfMxxbfj2O6eAkDnddF26WwTzZahcHYPwhjeE8twwABrQ9ERmAgbDABBbAssA8BrYgJGsaho0A8lJVVQYNTlCQGKHAExOdOC3VWRhlSlL1KyBILqD9PzbgCxK4QkHDJDwpsWIAVlkWL-OTAByb4bUq0qtFS6UMszeTh0UwsJ3y1TOM0nj8JbAA2WRAsy+0DVQWr0tlQaQoU0cWrjHrVK6dSuPnJcejsCgnjIe9-DSK8JEMr8hmubcpH8DBdqGDBzKsm4XMcWyKmrRzJGc1zqHc6hPOjIIgA) which demonstrates the issue we're encountering. In this example, I would expect there to be 3 Flow errors, but I'm only getting 2. I'd hope to see an error raised by line 43 in this example. 

I've been through the documentation, and can't seem to find an example of how to achieve this third Flow error when dealing with custom `type` definitions. 

Hopefully there's a way and it's something simple.

Any suggestions or recommendations would be appreciated.

Thanks

**Comment by wchargin** [comment]
> ```js
> type FooType = { };
> 
> type BarType = { };
> ```

These types are exactly the same and are treated interchangeably. You’ve
declared that a function takes a `FooType`, and you pass a `BarType` to
it—this is fine, in just the same way that `1 + 3` and `2 + 2` are the
same number.

Type aliases are _transparent_, not _opaque_, and object typing is
_structural_ while class typing is _nominal_.

The italicized words are useful keywords for research. I suggest that
you read what the Flow docs have to say about nominal and structural
typing. Opaque types may be an appropriate solution for your problem.

**Comment by jbrown215** [comment]
Thanks @wchargin !

**Comment by philberesford** [comment]
Thank you for the feedback @wchargin, that helps to clarify things for me.

I've created a new [Flow/Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAUQA9sBbABxgFMBhHfAHgFkAaMAEQD4wBvVAJAB9MtgoVqAJwBcYABTMAlGAC8PDgG5UYMNrACMcAHa4ALpICuGU3EnzR4qbIXK1nRfx0CBpgBYBLXAA6ETEJOxUwB3CtAQBfdAFcbAA3ajkyWSVZDj49HR1JalMLSSMwP0CQ6KkMxS0CsASE1FMATwkwADE4OAAVDupVPjAoXtkzSX8jAHMmrVbBsAAhbEkBzsjeMAAjNdkjCzIdqXn0LDwCHrh6S5GWi-wVtdun7Zb2zoBlc2mZjaGkUmfwWnyGADkjid1ktIodjlIFoYTKZRr0AasYRJmGFTpE5NcAYppJiAaoeJ4wEUSmURnsZGAAIxnOJI4xmNE3Bi4TGvXA4xwReTXPnE3nc8l5QrFUrlIzUJDiy5yeqoVnndmo4GzAGQhFY6gC8LDOQ-KY6wbEvXQsluSnU2VMrTqzCazkYtYAgCSKOwRgwgLA8qQJHIVDo3MYhMG7FJgy4cjG-UGcexuMkquRHLIcAAJtQYIzZNHNiMk7IAORJitnJMeg0+sx+gNBZJpDJ5guM+oCYDAMDguBgKSSWy4V0oqKdmAAJlkqcD23psmZ6rrKc9g0bpmb1FbqXSOfzs57fe68CQI7HYAAtGAEL5qOUwQRfAewLn-FAoFIn1q3xIuDsGCYAYI+GAANZ-BUQ4ILYEFgHgw7EBI1jULmGqTkmfJKvg267sMwZEKQlA0HyUa9HysYvNyCbYdyuH8ummZukeBYAMzFpREpwgq3Tccqqr0ZcjH4f6e5toe07sae-aDsOkijpI45ZqibEwAALPONF3Lxio6fgKpaMJ+Cib64n7u26kabJ56IApSkEHePR2I8uDUEBFSPhUSxgdQkHQbiawEDY97wYhBDUCh-mmOhmEctq-yDNaUjeuZAaEXxoakRGlyMGafwAuwKUGgmiW6lCqWDEaUgsZO6kAKyyAVFqlhWexGH62AVlo5XJZVDbpRJB4dseDW2fJV7KRO2bTgAbLIJW2k6qB9RIS1bkNllScec22V0F4Odezm2GAFBTGQ-imP4aQ+YBwHeTMT5SP4GB3UMfkBbMiGOMFMFhZICFIVFqGxbmQRAA) entry where the type annotations have different shapes.

```
type FooType = { foo: string };

type BarType = { bar: number };
```

In this scenario, Flow errors are raised as expected. 

Thanks again.
