### ISSUE TITLE
Map.has condition not recognized when calling Map.get

### ISSUE THREAD

**Issue by egeriis** [facebook/flow#6987]
[Reproduction](https://flow.org/try/#0GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFAM5QBOAXIhZYUQJSIDeAUIohAmXADbYAdPzil6TANzsAvu3ahIsBCjgAxAIb9+AIw0QA1iRas57HmArd9ebLQCyGgA4AeeowA0dKowB8iAF5EMGwAd0RHJ2NpRWh4JGBcCDw1SiwAYRtsEgNsAE9ad2ITTkQYYEQSCCyhPA0yHPymEq4uSlwQSiRq5OEiXEa8qVKzLnw08JDwgFFKNMoSAHIAaXzguChEYDhwZDLurNpFxABqRFyh6TMqPLZS1AwcfEYSRKhk1Iyspcw81bzFs0rtZ3ngSNgWqpNNo9IZorIgA)

In above example `fetchFromCache` will always return a string or throw an error, given that `cache` has type `Map<string, string>`. As you can see, that causes Flow to throw an error that `doSomething` cannot be called with `undefined`.

However, fetching the value from `cache` Map is wrapped inside `cache.has` to insure that the value exists in the map before returning.

I understand this is a special case, where the type system in itself may not be sufficient to solve this. But there are other special cases where Flow are able to recognize when something is conditionally called. Might be worth implementing support for this case too?

**Comment by jbrown215** [comment]
We prefer not to hardcode support in for library functions when we can avoid it. Why not just restructure the code a bit?

https://flow.org/try/#0GYVwdgxgLglg9mABAEzgZTgWwKZQBYxgDmAFAM5QBOAXIhZYUQJSIDeAUIohAmXADbYAdPzil6TANzsAvu3ahIsBCjgAxAIb9+AIw0QA1iRas57HmArd9ebLQCyGgA4AeeowA0dKowB8iAF5EMGwAd0RHJ2NpRWh4JGBcCDw1SiwAYRtsEgNsAE9ad2ITTm5eKEQANy1A62ThIlwc-KlSmGBEEmr+RABCILAQbRKuLkpcEEokbukuMy58NPCQ8IBRSjTKEgByAGl84LgK4DhwZERCOttabcQAakRcvNazKjy2UtQMHHxGEkSoMlUhksjtMHl9nltkwXtZAXgSNgRqpNNo9IZorIgA

**Comment by egeriis** [comment]
@jbrown215 Yeah, I recognize that's a possible solution. I'm raising this issue, since it essentially makes `Map.has` useless in control flows.

Not sure what you mean with _library function_, `Map` is a standard JavaScript class, not to be confused with Immutable.Map. If that wasn't clear.

**Comment by egeriis** [comment]
@jbrown215 This is a bit of a pita, no further response?
