### ISSUE TITLE
Order of cases in switch statements causing issues

### ISSUE THREAD

**Issue by thomasminton** [facebook/flow#6988]
Having defined a type (a union of two other types) I use that type in a switch statement. I have one case per type from the union type and everything works fine. If I add a case after these that isn't described in the union type ("SHOULD-FAIL" in the tryflow link) flow doesn't throw any errors.

If the "SHOULD-FAIL" case is moved so that it is not the last case flow correctly marks it as an error.

I have reproduced the issue here:

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagPJYHYCysAJgIbQCCAxsgJaz6gC8oA3oqKGlgFygAiHAAUAogDkA+oRwARSgBkBAGk6h0ZVHDIl+HLlwC2pCgEldoAM7IATnXwBzNQF9EzgNyIUGbAGE4lpjE5FS0DEys+tw+-AK+CjgAyqLScooCbp7eWKA09IwsuATBFHnhoAA+oP6wgSWh+fiePNiJyGTI2JFqANSwxSbQ5vwA-NZ2jpmI1IzWoPZ09BRtHV3sav2YRIPDoPgArtDQU4iYAB7osDbIoCSYkGSHNwAU1qv8K52FC0vQn5jKUBkMKMfhlRgASg+7S+zAAfOsuJZ4ItqAALUDPYGNAB0LQhiIM1DIgUEIgkqXkSj0agMoBsmGQ+xsTCidK4OM5b06qnZBk22xCu2x4RxGi0sB0OOMQpItIMHnlzj58uJpLiCWSlPSNL5DKZLMJfM5OO5APldIF9V2ByOFtAirprjpauwAkgkBIkEsJAEvDZXAAkPrmayTWblUq+aB5XcHk9ePaQ4azZ4uK5FUA

**Comment by jbrown215** [comment]
In the case that can never happen, flow infers the type of `action.type` to be empty, meaning that case is impossible to reach. If you tried to do anything with `action.type` there Flow would not allow it.

However, @dsainati1 has done some really great work this week on improving how we handle these kinds of things with literals. I'll let him check your example to see if it would be covered with his improved analysis

**Comment by dsainati1** [comment]
The changes I made do indeed fix this case. If you run try-flow on the master branch you should see that the case errors. I’m gonna mark this as closed unless you have any other concerns?

**Comment by thomasminton** [comment]
Nice one. Thanks!
