### ISSUE TITLE
class name visibility in class expressions

### ISSUE THREAD

**Issue by matklad** [facebook/flow#699]
I believe Flow (version 0.13.1) incorrectly handles visibility of class name in class expression. 

The following code fails with `error identifier Foo Could not resolve name`

```javascript
var Bar = class Foo {
    static factory(): Foo {
        return new Foo()
    }
};
```

It seems that the name `Foo` should be visible inside the class body (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/class).

If I use class statement instead of class expression, everything is Ok:

```javascript
class Foo {
    static factory(): Foo {
        return new Foo()
    }
}
```

**Comment by gabelevi** [comment]
@matklad thanks for reporting and @samwgoldman thanks for fixing!
