### ISSUE TITLE
[Maybe Bug] Intersection types with a same property name not check as expected.

### ISSUE THREAD

**Issue by yqz0203** [facebook/flow#6992]
[try](https://flow.org/try/#0FAFwngDgpgBAgjAvDA3jCAnA9hAzgLlRgENCA7AVwFsAjKDGAXydElgCEkjMcCiby1Og2aNgraPE7IEAMhjtxAN2INSUrmh55CadQEYANDAEx9TJgG4gA)

The flow document says 

>But when you have properties that overlap by having the same name, it creates an intersection of the property type as well.

So I tried as blow, but got an error.

``` javascript 
type A = { props: { a: number } }
type B = { props: { b: number } }

type AB = A & B

var a: AB = { props: { a: 1, b: 1 } }; // Error!
```
I also tried changing type `A`,  it worked!

``` javascript 
type A = { props: { a: number, b: number } }
type B = { props: { b: number } }

type AB = A & B

var a: AB = { props: { a: 1, b: 1 } }; // Works!
```
I finally tried exchanging the positions of `A` and `B` ,  it threw an error again.

``` javascript 
type A = { props: { a: number, b: number } }
type B = { props: { b: number } }

type AB = B & A

var a: AB = { props: { a: 1, b: 1 } }; // Error!
```

Am I missing something or it's a bug?

**Comment by wchargin** [comment]
Unfortunately, you’re not missing anything. Those docs are simply wrong
and do not accurately describe how intersection types work in Flow.
There’s some related discussion in #5895.

Intersection types in Flow really do not work very well. Personally,
I avoid them entirely.

Spread-types tend to behave better:

```js
type AProps = {| a: number |};
type BProps = {| b: number |};
type ABProps = {| ...AProps, ...BProps |};

// or
type A = { props: {| a: number |} };
type B = { props: {| b: number |} };
type AB = { props: {| ...$PropertyType<A, "props">, ...$PropertyType<B, "props"> |} };
```
