### ISSUE TITLE
Error when calling optional function prop with defined defaultProp

### ISSUE THREAD

**Issue by jjenzz** [facebook/flow#6993]
[http://flow.org/try/#example](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQnMAnmEjgAFemADOcALy5OcOKQBiENAFcxAfgBccABQBKKQD44ANwjAAJpk6UunNABsUYiQEkSYFfCQAPGOQsJQmIyCgAeEQhxYxxZODEYFBhgNDgLJBoUFQcYSPEpGTk5RWU1bX0jXEprOVtuOQALFBILByQlVQlpCskYuLk0UgTceRIOtThqaRgG4DEAOjBRMS4iuAB6dbSIeKIkGeASAHM4BqQWOGaLOBnyefv+0fGxfVXJuzkWFvOK2LWWGAqKAkOBhQ6eeB8ASSABE-j8MKepTEkhwBwWTRabWe1HWhjilBsQA)

```jsx
import React, { Component } from 'react';

type Props = {
  onFocus?: () => void,
};

class Input extends Component<Props> {
  static defaultProps = {
    onFocus: () => {},
  };

  handleFocus = () => {
    const { onFocus } = this.props;
    // do something here and then...
    onFocus();
  };

  render() {
    return <input type="text" onFocus={this.handleFocus} />
  }
}
```

```
    onFocus();
        ^ Cannot call `onFocus` because undefined [1] is not a function.
```

I'm fully expecting my response to be that the `Flow` isn't aware of `defaultProps` but thought I'd throw it out there. How do people tackle this? I was hoping not to have to wrap all my event props in a conditional before calling them 😕

**Comment by wchargin** [comment]
You can solve this by making `onFocus` not optional in `Props`:

```js
type Props = {
  onFocus: () => void,
};

// [rest of your code]

const examples = [
  // works (good)
  <Input />,
  // works (good)
  <Input onFocus={() => void console.log("Focused!")} />,
  // type error (good)
  <Input onFocus={3} />,
];
```

[(Link to example.)][try-1]


You can think of the `Props` type as specifying the interface for
`this.props` as used _inside_ the component, not the exact props that
need to be provided to _construct_ the component. It’s a bit
counterintuitive that this is the way that you’re supposed to do it,
[but it is at least documented][docs].

[try-1]: https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecDCE4EAdkifAL5wBmURcA5FKhowNwBQnMAnmEjgAFemADOcALy5OcOKQBiENAFcxALjgAKAJRSAfHABuEYABNMnSl05oANijESAkiTAr4SAB4xyZiYTEZBQAPCIQ4oY4snBiMCgwwGhwZkg0KCp2MOHiUjJycorKapq6BriUlnLW3HIAFigkZnZISqoS0mWSUTFyaKRxuPIkbWpw1NIwdcBiAHRgomJcBXAA9KspELFESFPAJADmcHVILHCNZnBT5LO3vcOjYrrL4zZyLE2nZdErLDAqUBIcBC+3c8D4AkkACJfD4oQ9imJJDg9nMGk0Wo9qKt9DFKFZuP0SINvChwC0OnAANoxdZwADu0AA1hItAcIBAzDoYiFXGC1voqmsNoyoCztOzOdy5Ly3B4Ee1kV1DCZzHAiWIIC1ZnYIActFDHkgzABCKE6bGC2kbCGCU70KASjlcnl8+VFRU4ADMlssAF0uEA
[docs]: https://flow.org/en/docs/react/components/#toc-using-default-props

**Comment by jjenzz** [comment]
Thanks for getting back to me @wchargin. I discovered this issue after posting too https://github.com/facebook/flow/issues/1660

It seems bizarre to mark/document something as required when it's not. Not a fan of the approach but if that's the only option for now, will go with it.
