### ISSUE TITLE
Losing resolved non-null type when calling method on an array

### ISSUE THREAD

**Issue by bradzacher** [facebook/flow#6994]
[repl](https://flow.org/try/#0PQKgBAAgZgNg9gdzAZwC4CcCWBjVYTABQhqAngA4CmYAYnHGALxgDeAPoWGAIYBcYAfjRYAdgHMANITYBfANwkK1AELd0TVhy7l0ccv2GZxU2QsJQAriNyY4IsAjjoA1shpHKACjVj+dOACU-AKq6iycYJhQYN7oYgB03EzMIhYwMGBsbDxxicnMAOQFAawRXOiUqBbo9qnpClwyEREVVTWlXNq6+jkJ3FKNCk3mVjZ2YABGus6UIgCMsb609EGCoR2R0Yt5jClpGVm9O7tgRSXhnWCt1bX7DWBNXBEA2gC68RUAbpToyF4B92u7QunR0en4PkSAweQ2IlmsqFs9imcBmIgATIs-CtgusQVEYpCkic6gdskT8qdihtypUbmBSfdHmAXu9kE5UJ4AS06cCymAwT0idD5IRhvCxsjprMAMxY5aBXFqDYE7bEvbpTLk3LqwrUkG0tq3eoRZms+JQTDpTxzbmG+kGgXdCE6kWwkYIpGTaUiAAs8v8qxCyvxWwpJP2WqOuqp535QONMCZzS4b3iAFtuORPFymAA+Bn7O1XXn2R2Cl19N1iuGjRHjFFogCsAZxaxDEVV4Y1ZOjlLONJLRsLJsaKbAafZ6a8ucYBag3Bgf2LCcHFej1fFda9jdmADZW4r22FO2GdckR73u3q45dV4zTeO01AnABRbjYAAWOZKc9YMhXUs12dDdTVhIA)
```ts
/* @flow strict */

type Foo = {|
  a: ?string,
|};
type Bar = {|
  prop: string,
|};

function worksFine(arg: Foo): ?Bar {
  if (arg.a == null || arg.a === '') {
    return null;
  }
  
  return {
    prop: {
      nested: arg.a,
    },
  };
}

function broken(arg: Foo): ?Bar {
  if (arg.a == null || arg.a === '') {
    return null;
  }
  
  [].reverse();
  return {
    // Cannot return object literal because null or undefined [1] is incompatible with string [2] in property `prop`.
    prop: arg.a,
  };
}
```

**Comment by wchargin** [comment]
[Any function call invalidates refinements.][1]

[1]: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

Please read those docs and post back if it's still unclear.

**Comment by bradzacher** [comment]
I understand the reasoning, but surely with the complete type inference system this would be possible to decide which functions can mutate the current scope.

even this simple (very clearly correct) case fails.

```
function broken(arg: Foo): ?Bar {
  if (arg.a == null || arg.a === '') {
    return null;
  }
  
  const foo = () => {}
  foo();
  
  return {
    // Cannot return object literal because null or undefined [1] is incompatible with string [2] in property `prop`.
    prop: arg.a,
  };
}
```
