### ISSUE TITLE
Cannot import Server from http

### ISSUE THREAD

**Issue by theboyWhoCriedWoolf** [facebook/flow#6999]
Hello,

I am using the latest version of flow-typed and flow and am still unable to resolve this. I think its linked to https://github.com/facebook/flow/issues/5113 but it seems there is no update to if this is even going to be resolved.

Any help would be appreciated. 

Thanks

Error I get is 
```
Cannot import Server because there is no Server export in http.

     1│ // @flow
     2│
     3│ import type { Server } from "https";
     4│
```

**Comment by goodmind** [comment]
This was fixed by #7448
