### ISSUE TITLE
flow get-def throws for React class methods

### ISSUE THREAD

**Issue by whhhooop** [facebook/flow#7001]
Flow: 0.83.0
React: 16.5.2
OS: MacOS 10.14

If i try to execute `get-def` command on any of `React` class methods that i defined, flow throws an error. For example if i have the following code in the `render` method
`<div onClick={this.handleClick} />`
and i execute `get-def` on position of `this.handleClick` i get the error
```
Failure("unexpected args passed to instantiate_poly_t: AnnotT")
Raised at file "pervasives.ml", line 32, characters 17-33
Called from file "src/typing/flow_js.ml", line 12031, characters 21-51
Called from file "src/typing/flow_js.ml", line 12198, characters 12-34
Called from file "src/typing/flow_js.ml", line 12138, characters 25-58
Called from file "src/typing/flow_js.ml", line 12199, characters 4-24
Called from file "src/server/command_handler/getDef_js.ml", line 108, characters 13-47
Called from file "src/server/command_handler/getDef_js.ml", line 174, characters 8-37
Called from file "src/server/command_handler/getDef_js.ml", line 203, characters 42-83
Called from file "src/core/lwt.ml", line 2101, characters 16-20
```

For any other variable/class/function etc `get-def` work correctly. Am i doing something wrong?

Here is the example [repository](https://github.com/whhhooop/flow-get-def-error) for reproducing the issue.

**Comment by Mayank1791989** [comment]
fixed in 0.84
