### ISSUE TITLE
Docs for "esproposal.export_star_as" seem to be wrong

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#7002]
Docs [here](https://flow.org/en/docs/config/options/#toc-esproposal-export-star-as-enable-ignore-warn) say:

> The default value of this option is `warn`, which gives a warning on use since this proposal is still very early-stage.

But in Flow 0.81, this option seems to do nothing. I have `export * from ...` in my project (to export types, in fact) and it works perfectly with no warning, no matter what setting I set for `esproposal.export_star_as`

**Comment by SamChou19815** [comment]
Closing since this is no longer configurable.
