### ISSUE TITLE
Inconsistency when casting object with defined keys into object with nullible keys

### ISSUE THREAD

**Issue by jackyzhen** [facebook/flow#7004]
```
/* @flow */

type A = {|
          a?: number,
          b?: string
          |};

type SortOfA = {| 
                a: number,
                b: string
                |};

const sortOfA: SortOfA = {a: 1, b: "b"};

// (sortOfA: A); // this triggers "Cannot cast `sortOfA` to `A` because string[1] is incompatilble with undefined [2] in property `b`.

({...sortOfA }: A); // but this works
```
Reproduced [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+qYtd9AhgPwBcYAdgK4C2ARngCcANDXpjerMAGcMAgJbsA5qLF1KAXwDc6bPjABlOAIwB5KMTJUwK1bYZsufQSNuuwvNjPlKbbtVvQAYzh2GWkjU3M2Q2MzCwp7MABGIXc2ACJedIDUYGAwAAopCLi2QgBKTTA8sAQACywwABM4PCl2AHIMMAw6uSlaowBrVALyADpJ4tjzMHUyyur83k5u3v7m1qlUIA)

**Comment by wchargin** [comment]
Flow is correct.

If `SortOfA` were a subtype of `A`, then you could write

```js
const sortOfA: SortOfA = { a: 1, b: "b" };
const a: A = sortOfA;
delete a.b; // valid: `b` is optional in `A`
(sortOfA.b: string); // unsound! `sortOfA` invariant has been corrupted
```

If you make a shallow copy (`const a: A = {...sortOfA}`), then this
problem does not occur.

You can solve this problem by marking the properties read-only:

```js
// @flow

type A = {|
  +a?: number,
  +b?: string
|};

type SortOfA = {|
  a: number,
  b: string
|};

const sortOfA: SortOfA = { a: 1, b: "b" };

// These both work.
(sortOfA: A);
({ ...sortOfA }: A);
```

(You only _have_ to mark them as read-only in `A`, as demonstrated
above, but you probably want them to be read-only in both `A` and
`SortOfA`.)

**Comment by jackyzhen** [comment]
@wchargin That makes sense, thanks!
