### ISSUE TITLE
Property dataset is missing in null or undefined [1].

### ISSUE THREAD

**Issue by michaelturnernature** [facebook/flow#7013]
It's complaining about the line where I check if the dataset `dropDownState` has been set to `CLOSED_CLASS`. I tried wrapping dataset by doing the following with no luck `(parentNode.dataset: ?any).dropDownState ===....`

Anyone come across this problem?

```
document.addEventListener("keyup", (event: KeyboardEvent) => {
    const el = (event.target: HTMLElement);
    const parentNode = (el.parentNode: ?HTMLElement);
    if (parentNode.dataset && parentNode.dataset.dropDownState === CLOSED_CLASS && event.key === "Tab") {
      toggle(el);
    }
  });
```

**Comment by wchargin** [comment]
`parentNode` has type `?HTMLElement`, as you have explicitly annotated.
This means that it could be `null` or `undefined`. But if it is `null`
then `parentNode.dataset` will raise a `TypeError`. Flow is correct to
show you this type error.

The null-check should be on `parentNode` itself, not on its `dataset`
property (an `HTMLElement` always has a `dataset`):

```js
if (
  parentNode &&
  parentNode.dataset.dropDownState === CLOSED_CLASS &&
  event.key === "Tab"
) {
  toggle(el);
}
```

(I suspect that the above should work, but you haven’t provided a
self-contained reproducible example, so I can’t verify this.)
