### ISSUE TITLE
Flow does not compile to lib- (dist) folder

### ISSUE THREAD

**Issue by wilnauerm** [facebook/flow#7042]
I once deleted the flow folder.
Since then flow does not compile anymore to my list folder (previously lib).

This is my .flowconfig

```
[include]
.*/modules

[ignore]
.*/build/.*
.*/node_modules/.*
.*/data/.*
.*/config/.*
.*/dist/.*
.*/logs/.*
.*/terraform/.*
.*/flowtyped/.*
.mochasome.*

[lints]
deprecated-call-syntax=off 
```

Any ideas what might go wrong?
Cheers
Marc

**Comment by lll000111** [comment]
> Any ideas what might go wrong?

Yeah... Flow does not compile anything, it's a static type checker not a transpiler like Babel :-)
