### ISSUE TITLE
class instance has type `any`

### ISSUE THREAD

**Issue by dfroger** [facebook/flow#7045]
I've a bug that is hard to explain as I don't clearly understand what cause it.

I've reproduced it [here](https://gist.github.com/dfroger/81947b31b96913a71d60bb477c91928c) (I did not manage to simplify it more).

The problem is that flow found no error, but variable `foo` has type `any` instead of `Foo` (`foobar.js`).

They are circular dependencies between files.

Making little change in this example make either flow find errors or make `foo` have the good type `Foo`.

My problem is that in real code, I fall "randomly" into this situation without flow errors, where `foo` is no more typed, and errors on invoking `foo` methods with wrong types are not catched.

**Edit**: updated the description as I simplify the gist.

**Comment by dfroger** [comment]
A "pragmatic" workaround would be to define actions like this:

    export const action1 = (): * => ({ type: 'ACTION1' });
    export const action2 = (foo: Foo): * => ({ type: 'ACTION2', foo });

instead of:

    export const action1 = () => ({ type: 'ACTION1' });
    export const action2 = (foo: Foo) => ({ type: 'ACTION2', foo });

so the type Action get from `ExtractReturn` becomes (no more `any`):

    export type Action =
        | { type: 'ACTION1' }
        | { type: 'ACTION2', foo: Foo };

`ExtractReturn` is for example:

    type ExtractReturn<Fn> = $Call<<T>((...Iterable<any>) => T) => T, Fn>;

Then flow detects errors to fix in order to fix the type of `foo`.

**Comment by dfroger** [comment]
maybe a pragmatic workaround is to avoid circular dependencies is the code (https://github.com/aackerman/circular-dependency-plugin)

**Comment by wchargin** [comment]
> but variable `foo` has type `any` instead of `Foo` (`foobar.js`).

You can fix this by annotating the `Foo` constructor to return `void`:

```js
export class Foo {
  constructor(bar: Bar): void {}
}
```

See #6400.

With this annotation, Flow infers that the type of `foo` is `Foo`, and
raises no type errors. This seems like the correct behavior, yes?

(To be clear, this is definitely a bug, just perhaps not a new one.)

**Comment by dfroger** [comment]
This indeed fix my example code and my real code! Many hanks for your help!

I'm going to close this issue, as it is likely the same bug as #6400
