### ISSUE TITLE
Inconsistency between string-literal and number-literal subscripts

### ISSUE THREAD

**Issue by wchargin** [facebook/flow#7051]
These all raise type errors, which makes sense:

```js
// @flow
const x: { a: number } = { a: 1 };
x.wat; // error (good)
x["wat"]; // error (good)
x["0"]; // error (good)
```

But [this does not raise a type error:][1]

```js
// @flow
const x: { a: number } = { a: 1 };
x[0]; // no type error!
x[0] = "hello";
const y: number = x[0];
y.toFixed(); // runtime error!
```

Recall that `x[0]` and `x["0"]` are completely equivalent in JavaScript
(even if `x` is an exotic object like a `Proxy` with a `get` trap),
because all property key values are String or Symbol values. It
therefore does not make sense that one should have a type error where
the other does not.

I understand that indexer property accesses are unchecked as a
deliberate design decision (like `myMap["foo"]` or `myArray[7]`).
But here the object in question does not have an indexer property.

Making the object type exact does not fix the problem.

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1ADwFygDeoAhoWgK4C2ARgKYBOoAvqALzFmECMrA3IlwBtAAwBdfqBCg0sUFgCeAB3qgmjWIwCEQseI6gARAAt60OEcGpMORRRoNmnERMGKAdFlgAxAJa49AAmABQAlFIyjJRoWH7UahpaukA

This obviously enables breaking the type system arbitrarily, but it’s so
simple and long-standing (since at least v0.37.0) that I have to wonder
whether it’s deliberate for some reason. What’s going on?

**Comment by thecotne** [comment]
i have same issue with Exact object (i would expect not to have indexer on _**Exact**_ object that does not specify indexer property)

```js
/* @flow */

type Obj = {| +name: string |}

declare var obj: Obj
declare var aa: number

;obj.name// ok as expected
;obj.age// error as expected
;obj['1']// error as expected

;obj[aa]// no error
;obj[1]// no error
```

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFZgC8YA3gD5gDUAdgIYC2eAXGAM4YBOASyYBzMLQC+6ACZ4AxjBb8CANyVg4ZbiVKpZCpavUsW3JgFc2xPP3QBuTaQB0rDsGAaA1mBY8weAA98OQw8aVQHMicWETx3f35+OH4fP0Dg0PDI0gBtAHIARjyAXXibJJTffyD5TPtHHJNSjyY4BIqIhoLmsFb25NQgA)

**Comment by SamChou19815** [comment]
Now all of them error as expected
