### ISSUE TITLE
Polymorphic function with Class<T> parameter doesn't typecheck

### ISSUE THREAD

**Issue by marton78** [facebook/flow#706]
This code doesn't typecheck:

```
/* @flow */

function test<T>(C: Class<T>) { var t = new C(); }
function Y() { console.log('constructing'); }
test(Y);
```

flow 0.14 fails with the message: `constructor call: Method cannot be called on T`

**Comment by samwgoldman** [comment]
I think there is a problem with the definition of `test: <T>(C: Class<T>) => void` itself. You could interpret this statement to mean "for any type `T`, there is a class type constructing that `T`." However, that isn't true! I couldn't substitute `T` with `number`, for example.

You can, however, use an existential type for this:

```javascript
/* @flow */

function factory<T: *>(C: Class<T>): T {
  return new C();
}

class Foo { }
class Bar { }
class Baz {
  constructor(arg: string) {
  }
}

var foo: Foo = factory(Foo);
var bar: Bar = factory(Bar);
var baz: Baz = factory(Baz); // expected error: too few arguments
```

**Comment by marton78** [comment]
Wow, thanks! Is this documented somewhere? I cannot find anything about existential types on flowtype.org

**Comment by mroch** [comment]
not documented on flowtype.org but there is a good overview at http://sitr.us/2015/05/31/advanced-features-in-flow.html#existential-types

**Comment by SamChou19815** [comment]
This is expected, since we won't treat functions like classes anymore.
