### ISSUE TITLE
Flow cannot find custom/self published package

### ISSUE THREAD

**Issue by Pfeifenjoy** [facebook/flow#7069]
I have a small node module which uses flow, thus I want to publish it
with the flowtype annotations.
Therefore I followed this "https://javascriptplayground.com/npm-flowjs-javascript/" guide.

Basically I used flow-copy-source to copy all source files
to my build directory. This works and my build directory contains
the original source files with a ".flow" suffix.
Furthermore I use webpack and babel to bundle everything into an index.js.

Thus my original source folder which looks something like this

    src/
        index.js
        app.js
        ...

is transformed to

    build/
        index.js
        index.js.flow
        app.js.flow

In my package.json I have set the "main" property to "build/index.js", the "files" property to ["build"] and the name to "@myname/mymodule" 

I then published the package to my npm account with `npm publish`
and installed it in another project with `npm i --save @myname/mymodule`.

In this other project I require the module:

    import x from "@myname/mymodule"

When I transpile everything with babel and run it, the code is correctly executed.
However when I run flow, I get the following error Message:

    Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/index.js:6:22
    
    Cannot resolve module @myname/mymodule.
    
         6│ import frontend from "@myname/mymodule"
    
    Found 1 error

Does anybody experiance the same error, or knows what I have done wrong?

**Comment by Brianzchen** [comment]
For one thing, your flow files should be `name.flow.js` not `name.js.flow`. Also not being able to resolve, should have nothing to do with whether the files are typed or not, if they aren't you'll just get `any`.

This is probably related to your flowconfig having ignored node_modules, if you need more help post your config here. Otherwise I will close this for now.
