### ISSUE TITLE
ExtractReturn type is any

### ISSUE THREAD

**Issue by dfroger** [facebook/flow#7071]
I have problem with the `ExtractReturn` helper as reproduced in this example code. 

In `redux.js`, `action` has type `any`, while it should be the returned type of `foo`.

Tested with flow 0.83.0, there is no error message.

Thanks for your yelp.

`actions.js`:

    // @flow

    import type { A } from './a';

    import * as actions from './actions';

    export type ExtractReturn<Fn> = $Call<<T>((...Iterable<any>) => T) => T, Fn>;

    export const FOO: 'FOO' = 'FOO';
    export const BAR: 'BAR' = 'BAR';

    export const foo = () => ({
        type: FOO,
        foo: 42
    })

    export const bar = () => ({
        type: BAR,
        bar: 42
    })

    export type Action =
        | ExtractReturn<typeof actions.bar>
        | ExtractReturn<typeof actions.foo>;
        
`a.js`:
    
    // @flow

    import * as actionTypes from './actions';
    import type { Action } from './actions';

    export type A = string;

    export const reducer = (action: Action) => action.type === actionTypes.FOO ? 1 : 2;
    
    
`redux.js`:
    
    // @flow

    import * as actionTypes from './actions';
    import type { Action } from './actions';

    export const reducer = (action: Action) => {
        if (action.type === actionTypes.FOO) console.log(action.x);  // action is typed any here
    };

**Comment by MartinCerny-awin** [comment]
I am having the same issue and it looks like that it is related to import bug mentioned in https://github.com/facebook/flow/issues/6797#issuecomment-416657143

When I use type extracted using `ExtractReturn` in the same file it is correctly typed, but when I import it in the different file, it is exported as `any`.

**Comment by dfroger** [comment]
@MartinCerny-awin Thanks for this very usefull feedback! I'll keep an eye on these issues...

**Comment by Eugene-Musika** [comment]
It works if add `*` as return type to `foo` and `bar` actions like so:
```javascript
export const foo = (): * => ({
    type: FOO,
    foo: 42
})

export const bar = (): * => ({
    type: BAR,
    bar: 42
})
```
Hope it will help someone.
But still I think it's a bug. And it reproduces even in v0.109.0

**Comment by dfroger** [comment]
Interessing! By the way, I didn't updated this issue, as I'm no more working with `JavaScript`/`flow`.

**Comment by SamChou19815** [comment]
We now have `ReturnType`
