### ISSUE TITLE
Refinement & invalidation when passing $Readonly objects as arguments (Try Flow provided)

### ISSUE THREAD

**Issue by nickluger** [facebook/flow#7084]
I'm trying to check whether a `$ReadOnly`-object has a an optional property, and if that is the case, pass that object to a function that expects a `$ReadOnly`-object with that property required.

I know that type refinements are invalidated, if an [intermediate function call was used.](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations) 

Here's an [example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCATgOYDOYAvGACQBKeAhgCYDyAdjFgDwDeAH1RgwADwBcYchmIBLDqRFLlS1AIC+APnRQArhwDGGWXA5gocOAAo+o9ZJIUAlGD7CwB0+Tgw8AOnhSK1EnAG5UdXRPDmkwOAAjACtJBmZ2Ll5BUQB+MElpOQUNTWpXCTAAIgw8aQr1cNRZKCsExL8Q13dgYDAAYSYYXxYwFlliPCNuMCYoauIwDAALAnGoeTwAWzwODA9lgwBrMB7SXSZiFncLa1awiKA) without any function call. So the type refinement is either never applied, or get's invalidated. Unfortunately i do not understand why, yet.

If i pass a copy of the object, copying the checked property, like in t[his example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCATgOYDOYAvGACQBKeAhgCYDyAdjFgDwDeAH1RgwADwBcYchmIBLDqRFLlS1AIC+APnTBgYACoALAnABGAKzwBjDGAC2AV2lhDTAG4EcxOPmLYxqFAOHDaycBxgUHBwABR8ouqSJBQAlGB8wmBW4eRwMHgAdPCkMaIpANyo6ujZHM5m5pIMzOxcvIKiAPxgktJyChqa1OkSYABEGHjSY+qVqLJQMQ0FZemZtc7x6sMNlSJRsVsVVUA), it works.

I would really like to understand, why that is. Thank you in advance!

**Comment by wchargin** [comment]
Flow is correct. The type refinement is never applied.

You have a reference `obj` of type `{|+x?: string|}`, but that does not
mean that _all_ references to this value have read-only type.

Suppose that the implementation of `foo` were the following:

```js
function foo(args: Args): () => string {
  return () => args.x.toLowerCase();
}
```

Then we could write the following:

```js
const mutable: {|x?: string|} = {x: "test"};
const obj: $ReadOnly<{|x?: string|}> = mutable;  // valid

if (obj.x) {
  const callback = foo(obj);  // unsound!
  delete mutable.x;  // valid: `x` is optional and mutable
  callback();  // runtime error!
}
```

If `{|+x?: string|}` could be refined to `{|+x: string|}` as you
suggest, then the above code would typecheck but raise a runtime error.

This is also why it suffices to shallow-copy the object as in your
second example.

Does this make sense?

**Comment by nickluger** [comment]
Absolutely! Thank you for your detailed and clear explanation. 👍.

**Comment by wchargin** [comment]
Great, glad to hear it.

**Comment by FezVrasta** [comment]
@wchargin is there any reason of why the invalidation happens even in this case though?

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAHgFygAkASgKYCGAJgPLrQCeAPAN6iNED86ArgLYAjcgCdQAXwB8oALyhaggFbkU2AHSQR5cgC9yACnadQAJgkBKANzIAlpFD68axqACEcvtGjnQrRKADQNCxYaHI1OABzfQBySFhYGKtkQPxnUABaU2txIA

```js
// @flow

const x: $ReadOnly<{ y: ?number }> = Object.freeze({ y: 2 });

if (x.y != null) {
    console.log('foo');

    x.y - 2;
}
```
