### ISSUE TITLE
appeal for class symbol computed properties to support operator overloading

### ISSUE THREAD

**Issue by yiakwy** [facebook/flow#7087]
Without using flow, the following codes works perfectly with class mixin (flow also does not implement it yet) syntax:

```js
// es6 with type striped plugins
// x.js
export class IOperator {
__add__(other: any): any;

[Symbol.for('+')] (other: any): any {
return this.__add__(other)
};
}

// y.js
export class Vector extends Mixin(haha, IOperator) {
__add__(other: Vector) {
bla bla bla
}
}

let a = new Vector()

a + a // passed
```

However, if I want to use flow, everything goes to mess

```js
// x.flow.js
export interface IOperator {
__add__(other: any): any

// $FlowFixMe
[Symbol.for('+')] (other: any): any;
}

// y.flow.js
interface IPoint_<Impl> extends IOperator {
__add__(other: Impl): any;
do_Something(): void;
}

interface IPoint extends IOperator {
__add__(other: IPoint): any;
do_Something(): void;
}

class Point implements IPoint_<Point> {
__add__(other: Point): Point {
	return this
}
[Symbol.for('+')](other: Point): Point {
return this.__add__(other)
}
do_Something(): void {}
}

let a: IPoint = new Point()

a + a // Error ! But it works in es6 !
```

IPoint, Point cannot see the computed properties defined and throw errors. This is not the expected behavior which already been proved correct in es6

**Comment by wchargin** [comment]
It’s hard to understand what you’re asking.

The following code does not work in ES6:

```js
class Vector1D {
  constructor(x) {
    this.x = x;
  }
  __add__(that) {
    return new Vector1D(this.x + that.x);
  }
  [Symbol.for("+")](that) {
    return this.__add__(that);
  }
}
console.log(new Vector1D(4));
// prints "Vector1D { x: 4 }"
console.log(new Vector1D(2) + new Vector1D(2));
// prints "[object Object][object Object]"
```

I don’t see any [TC39 proposals] relating to operator overloading.

I do not know what a “type striped plugin” is.

Please provide a [short, self-contained, correct example][sscce] of code
that runs correctly but which you are having trouble typing. Please
specify the environment in which it runs (e.g., “Node 10.0+”).

There are also various existing issues about symbol properties. You
might want to read some of these.

[TC39 proposals]: https://github.com/tc39/proposals
[sscce]: http://sscce.org/

**Comment by yiakwy** [comment]
@wchargin the codes work by using babel-operator-override plugin to transform the codes.

**Comment by wchargin** [comment]
There is no plugin `babel-operator-override`. There are several Babel
plugins related to operator overloading:

  - `babel-plugin-overload`
  - `babel-plugin-operator-overloading`
  - `babel-plugin-operator-overload`

When asking others for help about the behavior of nonstandard syntax
transformations, please provide a _complete_ example: your code, your
`package.json`, your Babel config, your Webpack config, any other
required files, and a command that we can use to run your code. We
simply don’t have enough information otherwise.

After looking at the implementations of the first and second plugins
above, I strongly suspect that this is not a feature that Flow will
choose to support, unless it becomes part of standard ECMAScript.

**Comment by yiakwy** [comment]
# Problem

Cannot resolve symbolically computed properties in *interface*, *class*. subclassing them either does not work or recognize them.

## package.json
```js
xxx
devDependencies: {
    "babel-plugin-overload": "0.0.2",

}
xxx
```

## .babelrc
```js
{
	"presets": [["es2015", {"modules": false}], "stage-2", "react", "babel-preset-flow", "flow"],
	"env": {
		"test": {
			"presets": [["es2015"], "react", "babel-preset-flow", "flow"]
		}
	},
	"plugins": [
		"transform-runtime",
		"operator",
		"overload",
"transform-flow-strip-types",
		["module-resolver", {
			"root": ["./src"],
			"alias": {
				"primitive": "./src/primitive",


			}
		}]
	]
}

```

## Flow lib

```txt
Bool.flow.js
Integer.flow.js
Float32.flow.js
CSSModule.flow.js
...
```

## .FlowConifg

```txt
[ignore]
.*/node_modules/fbjs/.*
.*/node_modules/jsonlint/.*

[include]

[libs]
flow

[lints]

[options]
module.name_mapper='^primitive' -> '<PROJECT_ROOT>/src/primitive'
xxx ... xxx

module.name_mapper.extension='jpg' -> '<PROJECT_ROOT>/flow/WebpackAsset.flow.js'
module.name_mapper.extension='yaml' -> '<PROJECT_ROOT>/flow/YAMLModule.flow.js'

esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable

[strict]
```

## flow for Facebook jest

```js
const babelJest = require('babel-jest');
const jestPreset = require('babel-preset-jest');
const flowPreset = require('babel-preset-flow');

module.exports = babelJest.createTransformer({
	plugins: [
		"transform-flow-strip-types"
	],
	presets: [jestPreset, flowPreset]
});

```

@wchargin  I cannot show you the source codes. The codes I list are pretty close. Please tell me anything else you need. Thank you.

**Comment by goodmind** [comment]
This is non-standard
