### ISSUE TITLE
Weird errors around ElementConfig and creating a props object

### ISSUE THREAD

**Issue by EdwardDrapkin** [facebook/flow#7092]
Hey there,

I'm trying to create a function that returns some props suitable for spreading into a component, something like `<TextInput {...getPropsForTextInput(someObjectGoesHere)} />`.    I'm not even sure how to explain what's happening [here](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgEyTQBsUi4YBPMJOABRzAGc4AvHADe5OOLgA3FHQCuSAPwAuOAt4wowAHYBzcgF9K9FL34BRAB4pwdDkgswkWqv2ToYAOgDCuSFqcwADzcEHwAfCKUhuSYsloYwBBacDpIMCF8AGLQltZgtoEAKipuGAAkZrYgAT5amMA6gazsEJhwuTZIYWEAFADWSCwq6pq6ADRwEJJIUJo0vCplAMoAFijsRWEAlCqFkRJwRDCyUMmiBwfSckgq+JgQEPhjYhfiHu9TM3NIvM8HhtFYvEYIlkgB3FYsAAiEB+hRWwF4AHl-AB1aB9IolYgwCpVGpJeqNZpIVrtKydbr9QbDDTaHQTT6zYDzRardZITY7OB7c4ASDQSXUcDAPH4QnOBz5V3kt3ujzgL3E+go4iVhzSJzO6oO7w8otCvx1Ej1TO+-HVAJe1qBCSSzBWSDcdFRhUyWMQOLxSGqWhgtSJTTYpLaHXyXV6AyGcBG9MZ02ZrLgyzWG0K212+wkRy1WdeeslEj5lxksoI8vwiteyr+1dNCfNVYkAKAA) except that either all three should fail or none of them should.  Why does the first one fail and the rest do not?  I think this is a bug of some sort.

**Comment by SamChou19815** [comment]
Now it no longer errors
