### ISSUE TITLE
How to import YAML file in flow

### ISSUE THREAD

**Issue by yiakwy** [facebook/flow#7094]
I have codes working perfectly in es6

```js
import SETTINGS from "primitive/settings.yaml"

```

However, flow throws errors that

> Cannot resolve module `primitive/settings.yaml`

I have double checked that my ".babelrc", ".flowconfig" have correct path configuration. Initially, I have webpack.[env].config.js to define loaders. However, documentation of flow talks little about it except for css, jpeg files and so on. I am curious that I am missing anything.

**Comment by AugustinLF** [comment]
I imagine you have a specific babel (or webpack) plugin that handles that? The thing is that flow doesn't execute your code, so if you use something that is not native to JS/Node, flow cannot handle it. So you'll have to do the same thing as with css/jpeg file (use the [module mapper for instance](https://flow.org/en/docs/config/options/#toc-module-name-mapper-regex-string)). But you won't have any type safety (it'll be typed as any). You can still add your own typings to settings, but it won't be checked against the content of your yaml file.

**Comment by yiakwy** [comment]
Yes, I use webpack to configure babel yaml-loader. But it is unclear that how to process the file in mapper. For the moment, I use "$FlowFixMe" to escape the error. But it makes me feel blue because it breaks static checking with brute force.

**Comment by zerobias** [comment]
```bash
echo '//@flow\n declare export default {presets: Array<string>}' > settings.yaml.js.flow
```

```js
import config from './settings.yaml'
```

**Comment by vicapow** [comment]
if you can describe the shape of the returned data in JS, you can use @zerobias technique to define the definition for it. Other than that, Flow really is only built to analyze JavaScript
