### ISSUE TITLE
Error: Cannot resolve module react-native

### ISSUE THREAD

**Issue by dbarros** [facebook/flow#7099]
When running `flow` I get the following error:

```
Error ┈┈ index.js:3:29

Cannot resolve module react-native.

     1│ /* @flow */
     2│
     3│ import { AppRegistry } from 'react-native';
     4│ import App from './src/App';
     5│
     6│ AppRegistry.registerComponent('myApp', () => App);

Found 1 error
```

Now, I don't care about checking that my code is calling in to libraries (like react-native) with the correctly annotated Flow types. So I don't need to import type libs for these external libraries. I simply want to get rid of this error, and just have Flow check my own code files for type errors (at least for now).

Is there a config option I can use to ignore these types of errors (which are not code errors)?

**Comment by lll000111** [comment]
Add something like this to your .flowconfig:

```
[options]
module.name_mapper='^react-native$' -> '<PROJECT_ROOT>/src/react-native-dummy.js'
```

Contents of src/react-native-dummy.js:

```js
// This is for Flow which complains about the missing module when it checks the RN code, which
// during ONE development is not needed to it is not installed. This module is configured as
// "react-native" module replacement in .flowconfig

declare export default {NativeModules: Object};
```

**Comment by dbarros** [comment]
@lll000111 that worked perfectly. thanks!

**Comment by bradbumbalough** [comment]
This is the only option that has worked for me.

**Comment by httol** [comment]
> ```js
> declare export default {NativeModules: Object};
> ```

Perfect!
