### ISSUE TITLE
guard against null does not work if function contains inner function

### ISSUE THREAD

**Issue by bjouhier** [facebook/flow#710]
Repro:
``` javascript
/* @flow */
function outer(s?: string) {
	function inner() { return "a"; }
	if (s == null) s = "";
	return inner() + s;
}
```
Output:
```
/Users/bruno/dev/flow/nullable-issue.js:5:9,19: +
Error:
/Users/bruno/dev/flow/nullable-issue.js:5:19,19: undefined
This type is incompatible with
/Users/bruno/dev/flow/nullable-issue.js:5:9,19: string
```
If I move `inner` outside of `outer` the error goes away.

**Comment by samwgoldman** [comment]
Thanks for filing this issue. This is a tricky behavior in Flow, which bit you, but I promise is motivated by good intentions. Flow isn't quite smart enough to know whether `inner` mutates `s` or not, so for now it is pessimistic by default.

I'm not sure if anyone has plans to implement the necessary analysis on their short term TODO list, but it's definitely on our radar. For now, this is a case where we ask that you restructure your code to make it easier for Flow to understand. Let me know if I can help you convince Flow that your code is sound.

For now, I've taken this issues as a prompt to improve the documentation. I mentioned this case specifically in the caveat section I've written into #711. Thanks again!

**Comment by bjouhier** [comment]
Thanks. I think that this is a valid code pattern. I want the `inner` function to be correctly scoped, even if it does not access the closure. Otherwise I'm polluting the enclosing scope.

There are also scenarios in which `outer` will declare variables `v1` and `v2` and `inner` will only access `v1`. In this case I cannot move `inner` outside without changing its signature and I would like the guard to work on `v2`.

**Comment by samwgoldman** [comment]
You're absolutely correct that this is a valid code pattern. Flow takes a very pessimistic view, which sacrifices precision to achieve safety, until we can build the analyses that would afford us both.

The "trick" to convince Flow that your code is indeed sound (which it is), is to avoid function calls after a refinement. In your original example, it's the invocation of `inner()` after the refinement that does it.

In this specific instance, you should be able to write the following, which does type check:

```javascript
/* @flow */
function outer(s?: string) {
  function inner() { return "a"; }
  return inner() + (s || "");
}
```

I'll keep this open for now, but I might consolidate this issue and others which are similar in the future.

**Comment by bjouhier** [comment]
Thanks for the detailed explanation and the workaround.

**Comment by samwgoldman** [comment]
This behavior is now documented in the [caveats section of the documentation for dynamic type tests](http://flowtype.org/docs/dynamic-type-tests.html#caveats).
