### ISSUE TITLE
"property getElementsByTagName is missing in Element"

### ISSUE THREAD

**Issue by techieshark** [facebook/flow#7101]
I'm getting the following error running flow 0.84:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ test.js:11:26

Cannot call rootEl.getElementsByTagName because property getElementsByTagName is missing in Element [1].

      8│ }
      9│
 [1] 10│ const rootEl: Element = root;
     11│ const childPara = rootEl.getElementsByTagName('p')[0];
     12│
     13│ console.log(childPara);
     14│
```

This is my file:

```
// @flow

const root = document.getElementById('root');

if (!root) throw Error('No element.');
if (!(root instanceof Element)) {
  throw Error('unexpected element type');
}

const rootEl: Element = root;
const childPara = rootEl.getElementsByTagName('p')[0];

console.log(childPara);
```

I put in the type cast to `rootEl` because I thought it might help (it didn't) - I was getting a similar error without it:

```
Cannot call root.getElementsByTagName because property getElementsByTagName is missing in HTMLElement [1].
```

Not sure why this is happening - looking at the DOM flow spec, it looks right:

`HTMLElement` extends `Element`:
https://github.com/facebook/flow/blob/master/lib/dom.js#L1520

And `Element` has `getElementsByTagName`:
https://github.com/facebook/flow/blob/master/lib/dom.js#L1279

**Comment by Brianzchen** [comment]
`getElementsByTagName` now exists in latest version, tested on 0.132.0
