### ISSUE TITLE
Confused by interfaces and variance

### ISSUE THREAD

**Issue by thiagodelgado111** [facebook/flow#7107]
Hi all, quick question, can you guys help me figure out what I'm doing wrong here?

```js
/* @flow */

interface IA {
	_b: IB;
}

interface IB {
 	foo(a: IA): string;
}

class A implements IA {
	_b: B;
}

class B implements IB {
  foo(a: A): string {
    return 'foo';
  }
}


const a = new A();
const b = new B();
a._b = b;

console.log(b.foo(a))
```

Error:
```
16:   foo(a: A): string {
             ^ Cannot implement `IB` [1] with `B` because `A` [2] is incompatible with `IA` [3] in the first argument of property `foo`.
References:
15: class B implements IB {
                       ^ [1]
16:   foo(a: A): string {
             ^ [2]
8:  	foo(a: IA): string;
            ^ [3]
```

You can check it out here: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAgmAN6oCQA+gEYBcVAQgNyoC+6bPiJkKlLvVRhGUOHAAUxTjQCUnAM44C2AOZ9BqUjGIaNYWhgC2ABxh4reXOZpSWHMLwHpjp85Os7ByccF0kGMDA5RWULdTAtHSxdKUjIgjwcAFcCLDAAcmj8vkjBQyM4LC0wYjAAXjAsPCRqBVU+Ukrq1nrG5s82vmIAOjZe1j4Kqrh7YfhdBVZh6KVVVSA

**Comment by thiagodelgado111** [comment]
If I got it right, the first argument in `foo` is contravariant, so we could only use `IA`. Is there a right way to do it? Maybe using generics?

**Comment by wchargin** [comment]
> can you guys help me figure out what I'm doing wrong here?

Your `IB.foo` accepts an arbitrary `IA`. But your `B.foo` accepts only
an `A`. So, if I have an `ia: IA` that is _not_ also an `A`, I cannot
pass it to `B.foo`. Thus, `B` does not implement `IB`.

> If I got it right, the first argument in `foo` is contravariant, so we
> could only use `IA`.

This is exactly correct. Function types are contravariant in their
parameters and covariant in their result type. (Can you see why? Think
about what it means for one type to be a subtype of another.)

> Is there a right way to do it? Maybe using generics?

It depends on what you’re trying to do, which isn’t totally clear from
this example. In particular, it depends on what `IA` and `IB` actually
represent.

If it’s possible to implement `B.foo` such that it accepts an arbitrary
`IA`, that would probably be a good solution.

(For instance: if `IA` is `Collection` and `IB` is `Map` and `foo` is
`containsAllKeys`, then really it should accept a `Collection`, not
specifically an `ArrayList` or `HashSet`. Programming to the interface
is appropriate here.)

If it’s not possible—if `B.foo` really only works on `A`s—is `B` really
an `IB`? Should `B` just not implement this interface? Or should `IB`
not include this method?

If it really seems like `B` should be an `IB` but it also really has to
depend on `A` specifically, then you could parameterize `IB`, yes:

```js
// @flow
interface IA {}
interface IB<T> {
 	foo(t: T): string;
}
class A implements IA {}
class B implements IB<A> {
  foo(a: A): string {
    return "foo";
  }
}
```

(For instance, if `IB` is a `Comparator` and `foo` is `isLessThan`, then
it probably really only can compare a specific kind of value. Generics
are appropriate here.)

**Comment by thiagodelgado111** [comment]
Hey @wchargin, thank you very much for the explanation, great answer! ❤️ Now I get it, in my case, parameterizing`IB` is the way to go as it does have a dependency on `A`, closing this one! :)

**Comment by wchargin** [comment]
Great; glad to hear it. You're welcome.
