### ISSUE TITLE
How can I export an interface with module.exports?

### ISSUE THREAD

**Issue by shamoons** [facebook/flow#7109]
```
// @flow

interface ConferenceConfig {
  status: string;
}

module.exports = {
  ConferenceConfig: ConferenceConfig
};

```

I tried that, but to no avail. I get: `[flow] Cannot reference type `ConferenceConfig` [1] from a value position. (References: [1])`

**Comment by shamoons** [comment]
@TrySound How should I export my types then?

**Comment by TrySound** [comment]
@shamoons 
```
export interface Name {}
export type Name {}
export type {
  Name1,
  Name2
}
```

**Comment by shamoons** [comment]
@TrySound Can I use CommonJS somehow? I'm trying to avoid excess transpilers

**Comment by wchargin** [comment]
@shamoons: If you use the syntax `interface ConferenceConfig { … }`, you
must already be using `flow-remove-types` or equivalent, yes?

The `import type` and `export type` directives are removed from your
code entirely by `flow-remove-types`. They don’t require actual module
system support.

**Comment by shamoons** [comment]
```
// @flow

type ConferenceConfig = {
  status: string;
}

export type { ConferenceConfig };

```

```
Errors with:
/src/interfaces/conference.js:3
type ConferenceConfig = {
     ^^^^^^^^^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:80:10)
```

@wchargin

**Comment by wchargin** [comment]
If you’re not using `flow-remove-types` at all, you should look into the
[Flow comment syntax]. It serves exactly this purpose:

```js
// @flow

/*::
type ConferenceConfig = {
  status: string;
}

export type { ConferenceConfig };
*/

const myConfig /*: ConferenceConfig */ = …;
```

[Flow comment syntax]: https://flow.org/en/docs/types/comments/

**Comment by shamoons** [comment]
@wchargin , I am using it:

`    "build": "flow-remove-types src/ -d build/",` in my package.json

**Comment by wchargin** [comment]
Hmm—are you sure that it is configured correctly? The `type … = …` lines
should be removed entirely:

```js
$ cat in.js
// @flow

type ConferenceConfig = {
  status: string;
}

export type { ConferenceConfig };
$ flow-remove-types in.js >out.js
$ cat out.js
//      

                         
                 
 

                                 
$ 
```
