### ISSUE TITLE
How can I force a return to match a type?

### ISSUE THREAD

**Issue by shamoons** [facebook/flow#7116]
In my file, I have:

```
return TranscriptLib.saveTranscription(timeoutResponse.response, providerId)
    .then((dbTranscription) => {
      if (exitEarly) {
        return;
      }
      ConferenceId = dbTranscription.ConferenceId;
```

And my `saveTranscription` method has:
```
function saveTranscription(response: OperationResponseResults, providerId: string): Promise<DbTranscription> {
      return global.db.Transcription.findOne({
        where: {
          providerId
        }
      });
};
```

My `DbTranscription` is defined as

```
type DbTranscription = {
  ConferenceId: string,
  id: number
}
```

But VSCode has an error where I have `ConferenceId = dbTranscription.ConferenceId`:

`[flow] Cannot get `dbTranscription.ConferenceId` because property `ConferenceId` is missing in `TimeoutID` [1]. (References: [1])
`

**Comment by Brianzchen** [comment]
Hi @shamoons bit late here but if you're still interested, I've tried to reimplement your code in a [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagCICMAVAJwEMA7AZwGMiBLdZW2M0AXlAG8AfRUUAYWaRMRTGSqYAkgBMAXKArI6ZAOYAaXqFpzQZAK4BbPCI1cAvgG5EKDNgDyWUo2YAlTBXTMKmNxT3RkCjZOLlBzK0QqL2RQYnJqOgYAGVo8YI5NChIAN0w4yhp6ZzJ5AApNPlEPL0x5BxESYt9PSh93f0CNPj50Ilhs7REZeUVldU0ASnkABT6DWm8AHnx8hKKmMgA+Nm2VODwSaAA6aTwj1cKGDaPIWjJpOzJMUozu0HgACxFazgru3v6gyIMi63TMoLMEw0lmsUUoMUgenEwVKjAMmFgemQzRqalAAIG0iG0jxmAAHrRkABREhEaCoCY7UDlPgXRLIFJnLK5NnrZio2jozHY9wtbxHKpizB4glAmQTP5HZBfMilUqnXlXZiM1jbV5vLSQZnkyk0ukM34G7qiZB6IhkKxWsx-PhwxQCITfcRSaTBDWkArs66CMjCUTemSOsEKiZWIA) but can't seem to get your error. `dbTranscription` is typed as `DbTranscription` so there are no errors when trying to get the property, `ConferenceId`.

Can you provide more info on this?
