### ISSUE TITLE
Flow doesn't refine Arrays after a `typeof` check

### ISSUE THREAD

**Issue by talbenari1** [facebook/flow#7123]
Given a value of type `mixed`, refining the type down to `{| [string]: mixed |}` via a `typeof` check and subsequently refining it to be an `instanceof Array` causes Flow to think the code is dead (or at least that's my understanding of what's going on). For example:
```js
function foo(x: mixed) {
  if (typeof x === 'object' && x instanceof Array) {
    // x is now `empty`, but it should be `Array<mixed>`
  }
}
```

**Comment by talbenari1** [comment]
Hmm... upon further inspection, this actually looks like two bugs compounded into one. 

I don't even need the `typeof x === 'object'` guard in the example above to be able to reproduce this:
```js
function foo(x: mixed) {
  if (x instanceof Array) {
    // x is still `empty`
  }
}
```

But if I change it to `Array.isArray(x)`, Flow refines `x` as expected:
```js
function foo(x: mixed) {
  if (Array.isArray(x)) {
    // x is `Array<mixed>`
  }
}
```

However, if I then add the `typeof` check back in, `empty` comes back:
```js
function foo(x: mixed) {
  if (typeof x === 'object' && Array.isArray(x)) {
    // x is `empty` again
  }
}
```
So I'm not really sure what's happening here.

**Comment by talbenari1** [comment]
Also note that placing the `typeof` check *after* `Array.isArray(x)` works correctly:
```js
function foo(x: mixed) {
  if (Array.isArray(x) && typeof x === 'object') {
    // x is `Array<mixed>`
  }
}
```

**Comment by wchargin** [comment]
Related: #6874.

> causes Flow to think the code is dead (or at least that's my
> understanding of what's going on)

You understand correctly.

It looks like this isn’t specific to `Array`. Any class suffices.

[This yields `coerce`:][1]

```js
// @flow
function coerce<T, U>(t: T): U {
  class C {
    value: T;
    constructor() {
      this.value = t;
    }
  }
  function f(c: mixed): U {
    if (c instanceof C) return (c: empty).value;
    throw new Error("Unreachable.");
  }
  return f(new C());
}
const twelve: number = coerce("twelve"); // no type error!
twelve.toFixed(); // runtime error!
```

[1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQkCuA7AxgFwJazaBrAKYBOGxAPACoA0oAqgHwAUWAXKNQJScOgBvRKELQAhgGcJoAMKDhI0ADcx0FMU7UA3ApFE0ErKRTZYpFt3mLFWABY4JAOhVrioALygsO6wF8F-iKomLj4oJAsGJwAtjgAHsQAJryMVoo4kKCRoDgGWGKYxLCZMpakxFgopASRnMTRAA5YAJ7czqrqPja2pAigaMTwoACipL3mAEQMaOViGLZiAEbQxI4T3F2BoOWV1eEsA0MyFhuI-vqGXvDE0Eoa-SjRi2QehCTkxCwTWNe3xOtaUAgfqwLzNBpuMjjACEiB+NzujiwsAAYvEkhZAcDjGhcNFIWMzLCgA

It is also worth noting that changing `mixed` to `mixed | C` in the
above code causes a Flow error, which breaks the characterization of
`mixed` as the top element of a Heyting algebra.

This issue occurs in Flow v0.85.0 (and `master`), and all the way back
to v0.37.0, the earliest version available on Flow Try.
