### ISSUE TITLE
[Flow 0.85] How to type connected components with react-redux?

### ISSUE THREAD

**Issue by atabel** [facebook/flow#7125]
As announced in this [blog post](https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8), Flow 0.85 needs extra type annotations for some exports.

This seems to be the case for react-redux connected components.

Here is an example:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudYMDDlsOGBigYaAEzBcGhALRdpAVwAeYQgE8cNcumk16MUly26aYACIZyOUoXoALAIIAFAJIAeVwD4wAF4wAAoFDDgAOwAuMFcASiCA134jEzMrHT0bOwcnZ19YgG8smliAEgBlVQAjUu9yQnwMSIBzPwBfAODbe0cXDx9-flQ003NSsABZUhxKwkcaABU4dxYccm9K2IB5GoArY0IAGjBK912Do9Oqc8vDxm7QxsXYytOcdfI390TAgNu7hGYwyYCgqkijAikTA9CikSO3lQYDAAGFWLFaAoAHTo3BRGiRQhLSzeEB+Y7Is73a5Uu5gPYPE5UwE0xiUlGoi5gcq2KBQbxYxjYgCiMBoWEJhHRkUkrW8eIp1HOFLpS2KAG0APoVADSNG0m0VAF1YqRItoOqg-CEqVhZvNFis1nANrEZnMFoRlqsvltTucbiqOWB7ThenkXM6vgB+WKRVQwGCoeKxEJw-EIomxPF-AHcQi41h4LPE0lcsAAMjO7gC1aqzlmNC2Sz8I0EYEJsjgUDkBeUMg0Fj0BnQkxdGyCYCKAB8qTh46osDUaPgQy0mTJuQnl6vUDOOiM4ZFGmjiwSiVPQkUcKcN0ctx1YhPyHnQlTvNIMAA3Pw3jpkJEshFPejCPt4wBfr+YApugx6nmGjretGrqUMEIRviERRUqB3rSNyADMqAdPER5RKeMoImB0h4jgU7HlRhAhIhXo+i+8QhLRF6EKR6AhBhSTvii3h+FSwlcaWYA4IERQAIwAbhW4yQATABwCiSi4nwg+NHFlJMnyWA6kfsZ8QcfE6A0OoeBEGARhQKQibEJROm0fwmkeZ5XneWAQA

It fails with these two errors in Flow 0.85, but worked fine in Flow 0.84
```
Missing type annotation for `CP`. `CP` is a type parameter declared in function type [1] and was implicitly instantiated at call of `connect` [2].
```
and
```
Missing type annotation for `SP`. `SP` is a type parameter declared in function type [1] and was implicitly instantiated at call of `connect` [2]
```

So what's the recommended way to type connected components with react-redux and Flow 0.85?

**Comment by atabel** [comment]
Not sure if I should open an issue to flow-typed instead

**Comment by peter-leonov** [comment]
@samwgoldman, thanks a bunch for providing [those concise and strict typings](https://flow.org/try/#0PQKj-YChQAgJwKYBMCuAPWJqghaUyiAxgDYCGSsA9gA7kCOqisALgJ60sDKr1SAHm4AaWAEEAfAG5CJClQ5dYAEQCWAZ3qtiACwGTYAXnFGJ4mTDxX8lhInLFWAWiRpM2S9esFgwE8WoAO0CSVhRYAIBbWiDEQNZYAHd4clp1WHVqSJYomJD42AB1AGEAOlgAOWowth1yBO5YAApeesQASlhyQOQVZrFHVSD2mD9KFgAiWjr4rIm2ThZ6FOyw+HVRcnTWHUR2LqpA6oig9VYU1RDegCN9nZYiADNL1VYhwNhr1FZRhHrd+CfO67E7xRDoBL1WosVDqFjqV6IUqyMjjCIUdTpYpBEKOFDY6KxeICJwiWBOZSiADyAAVRABqEpmcFhHrpABK9kcABICXk4qwBLSzABvKCwDKseqqYiwRkpWhcZB8omsABcRWKMglAHNEKxCgqlQBJQJnbrERBNdoazkOVjcgCipEQ2XinMeAiZMgAvlAoIoWABZVKtMIAFWoNPgdHUJLJTlpDO4NLMxia4slbQ1Ikz1ESgWjsY1SagnUMZhTFl8sG45GyXXS5Gu1AAbohRF8EvdYER4KpW9KgrANJ8tuFh8gNFpdCOzWFyL1qI8s2FkYHYCHaGpNPVdJGi2kSZTyUm5cpU0Zmpmp7vtDoNZS8wXD+oS3Sy6YVDSLBug4h4D1V94zpckL1ERNQPpINL3TTNzTCV8cw-CVbxnHQkO-YRn0LGM0nfbDyzMGDqz8cMQQCYJQn4WBHlQQJBmHe1yFQUhSH2Lh4EeLJthBZJUloS4dVEHUByE2BYS6UFcTCZBflyVV10WWBsSoxx+HjCCTzPJkrxKL9igxONVJk-Esn5YkyW00CmWkf0axpb43kCHUR0hNi2GoPV7ngZEiFRKg6IYt5h0omShFEazRBTSLUwzCVIlDKUIyjPC303JK2gPNKItgM8LwkbCEtSHd0Oy4sMu3ac9x0cqjyi2tU0IjUTOo+Bcoau0eRVfJWHDRYBBFAAfUpRrPUbShi2AJovIafQkOyUXkFggsYj4wtCDrqVAqbwM3OLM0S2gw0QOr0q3E6zty-KmsOkrqvvM6NS3UqaquhqU0Kw6AKAtLnp+xBgN20Czxgr6bRUnE2q2vLQK6h0eoFfquAEMHFtwLwPDgR10HrWgXSwHBMbAAhKLOWB4avJAmFUJAmgmJB7QmdpSNgY1EtEkIkhYOp2ykhFogJ1wMElfgkX9DdGmMQJUEia4AJkDcxCvEUFi4DUAHJjQqYp2Q12AfVgIbYFVwNNeUR1df1n0ZH85bYEHQEzjFnM+EEMlJCkWAa3YahUAiboRw5y5EHsvwxB6KSFN6iXlNfFWhszDQKkQHVpXbDUW2oF1uiK2jqGoDUzn7Fy8+uSgi-OITsLmixUUxTd2ERgoWTiZAOS5VhSmbwVX1FeDkplXtEEeFjSFYePjFV8v4A1CYnjHhIZ-mG3-QlJAegA60TczCUyYSEVk9T9OO3z6hO0oQ3jB2DRSloNLtQlOxWFQeAPgAAyPtO3gzk2v5Pn0ohuKFxNsAwBY5Z4mxnj6d+j8-R+l+IUHIgd+K0FqFCaOAo5xRyCFKEOgIdhQnvm2VQRB0gIVDjWJBAcPhHXQQkChnkaCv1gMQtIYdKjVBYIQ7sIJlj1n1ABNWiAmyBVYuxOcjwAKuCgKtEKtDMopVfE0Choh8y4VjJ0MU699Svw+Nop+-8f6IErm0WAAhYAAAY87wI4WINOlxRD8NWEIwM6Q6IeUuFI+AMi5HvFgEdV6j1UqxiaGhGqaiXxpS0ZmJAL836gILhqSxtioD70bqpPBIRATGA2o4eKATFGnRCWkPOgSHr7hKRsMsTQgxN3MqqFm-pUb1PiOQfB3sJAcONCuRILBEjdG7NQWA4IYjwF4TkXB7TsmiD6bAEI4Q+CsJjK2UhLBuhHEHkcdx-Bfg9kYd0Xo4T7zCPUOUciAEWCjiOLAUg1BiDkFILAAA1kcRILpkB6i6C2b40I4SnN+H7VgCIiA0BXOQZZJC+yiEyNzeZiBFnDPliM9A+MZSvGRL8AAqgxLIbohkZARSMnxuzfCRGoGgF0pRRn8GBVeOpmTpkKyAA) for `connect` I personally was missing forever!

Imho, there is a little typo in the typings:
```diff
-  mapStateToProps: MapStateToProps<S, OP, DP>,
+  mapStateToProps: MapStateToProps<S, OP, SP>,
-  mapDispatchToProps: MapDispatchToProps<D, OP, SP>,
+  mapDispatchToProps: MapDispatchToProps<D, OP, DP>,
```

This fixes an error like this:

> [Flow] Cannot call `connect` with `mapStateToProps` bound to `mapStateToProps` because property `someDispatchProperty` is missing in `StateProps` but exists in `DispatchProps` [2] in the return value.

**Comment by peter-leonov** [comment]
By the way, for those type hackers spending their weekends in fixing 100 new (legitimate) errors, here is how I use Sam's typings.

First I split the huge all in one `Props` type in three distinct types (`OwnProps`, `StateProps`, `DispatchProps`) and one combined (just `Props`):
```js
// these are the old school props coming from component usage:
// <Component own1="foo" own2="bar" />
type OwnProps = {|
  own1: string,
  own2: number,
|};

// these are the props coming from state via `mapStateToProps`
type StateProps = {|
  state1: boolean,
  state2: number,
|};

// these are the props dispatching actions from `mapDispatchToProps`
type DispatchProps = {|
  action1: typeof actionCreator1, // actionCreator1 is an imported action creator function
  action2: typeof actionCreator2, // actionCreator2 is an imported action creator function
|};

// and finally the main type for component type creation (`Component<Props, …>`, see below)
type Props = {|
    ...OwnProps,
    ...StateProps,
    ...DispatchProps,
|};

// here is the normal React component class definition
class MyComponent extends Component<Props, void> {
  render() {
    // `this.props` has all the props as expected because it's of type `Props`
    console.log(this.props.own1)
    console.log(this.props.own2)
    console.log(this.props.state1)
    console.log(this.props.state2)
    // including action dispatchers
    console.log(this.props.action1(…))
    console.log(this.props.action2(…))
  }
}

// and the most important part is using the `connect()` function with proper type parameters
export const MyController = connect<State, Dispatch, OwnProps, StateProps, DispatchProps>(
    mapStateToProps,
    mapDispatchToProps,
)(MyComponent);
```

The `State` and `Dispatch` types come from how it's officially recommended to type [Redux with Flow](https://flow.org/en/docs/react/redux/). In short:
```js
// the overall state of your app
type State = {|
  +forms: FormsReducerState,
  +notifications: NotificationsReducerState,
  // and so on
|}

// all the actions of your app
type Action = FormsAction1 | FormsAction2 | NotificationsAction1 | NotificationsAction2;

// type of a `dispatch()` function
type Dispatch = Action => Action
```

P.S. Adding this code to `connect()` typings allows to use an object with dispatchers instead of a function:

```diff
+ declare export function connect<S, D, OP, SP, DP>(
+     mapStateToProps: MapStateToProps<S, OP, SP>,
+     mapDispatchToProps: DP,
+ ): Connector<S, D, OP, React$ComponentType<{| ...OP, ...SP, ...DP |}>>;
```

**Comment by laurenskling** [comment]
Whenever I think I'm starting to get flow, stuff like this breaks my brain 😅 
I have no idea how to fix my 300 connect errors right now. Giving them 6 parameters doesn't really sound like the most readable thing to do.

**Comment by peter-leonov** [comment]
I wonder if the should be a way to tell Flow "I know what I'm doing" and make it possible to export a generic instantiation, like $FlowFixMe but for performance related things. Kinda $FlowTrustMe :D

**Comment by kangax** [comment]
My sad face when Flow is already at 0.88 but we can't get past 0.85 without $FlowFixMe-fying 500 errors...

**Comment by oshalygin** [comment]
This feels pretty bad.  Why was this closed?

**Comment by peter-leonov** [comment]
@oshalygin I guess, because of these two PRs to `flow-typed`: https://github.com/flow-typed/flow-typed/pull/3012 and https://github.com/flow-typed/flow-typed/pull/3035

**Comment by peter-leonov** [comment]
We are also crafting another one to make the `connect()` function typings more composable with other HOC (in terms of `compose()` function from Redux) here: https://github.com/flow-typed/flow-typed/pull/3076. Please, help 😊

**Comment by oshalygin** [comment]
Thanks for the update @peter-leonov !

**Comment by vaukalak** [comment]
@kangax As far as I understand it should be still possible to type via:
```
connect<*, *, *, *, *>
```
So I think, running replace of `connect(` with `connect<*, *, *, *, *>(` may solve part of your issues.
