### ISSUE TITLE
Can't use a union of function types to type a function with multiple signatures

### ISSUE THREAD

**Issue by callumlocke** [facebook/flow#7130]
I was hoping it might be possible to help Flow infer the return type of a function depending on its input type, like this:

```jsx
type IsNumber =
  | (number => true)
  | (any => false);

declare var isNumber: IsNumber;

(isNumber(123): boolean); // ERROR
(isNumber('nope'): boolean); // ERROR

(isNumber(123): true); // ERROR
(isNumber('nope'): false); // ERROR
```

But Flow errors on all four type assertions. I expected all four of them to pass, especially the `: boolean` ones. ([tryflow](https://flow.org/try/#0C4TwDgpgBAkgzgOQK4FsBGEBOUC8AoKKAHygAoA7VDbHAPimEyQgEoDiyBDckXegM04AbOKwDcePABMIAYyGdM0AG6KoAS0RUsALlhb0WCXlKbkhzKQCMAJgDMLPWgD2zoRG4sxUAPQ+oAKIASkEA8kEmZtqWAOTkzpAxjlAubh7kXr7+wWERkQbU1vbJjMyZfoEh4fnmhXEJEEl6giLiWZW5QA))

Then I tried doing the same thing using an interface:

```jsx
interface Foo {
  isNumber(number): true;
  isNumber(any): false;
}

declare var foo: Foo;

(foo.isNumber(123): boolean); // PASS
(foo.isNumber('nope'): boolean); // PASS

(foo.isNumber(123): true); // PASS
(foo.isNumber('nope'): false); // PASS
```

All four assertions pass as expected! And they fail correctly if you change them – e.g. `(foo.isNumber(123): false)` errors as expected. ([tryflow](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgGIHt3IN4ChnLADOAcgK4C2ARtABQiU1QCUAXMmFGRANz6GlGdOCACebZPAA2RXrgC+uXABMICKXCgoAbpsmZ2GdH1y0YmAHTFy1OgEYATAGYJVTFIgjmPZAHpfyAAKAIIAyqGm5uhWgrZQtADkIOgADhAJru6eIN5+ASHhSmaW1kLxji7snNy5-kFhEcXRpXGJyWkZ7NKytfkNQA))

Two questions:

- Why isn't this awesome feature mentioned in the [Interface Types docs](https://flow.org/en/docs/types/interfaces/)? Is it safe to rely on it?
- Why doesn't it work with a union of function types?

**Comment by Awpteamoose** [comment]
`IsNumber` in the first case is either a function that returns true for numbers or a function that returns false for any value, it's not both at the same time.

Try like this: 
```javascript
type IsNumber =
  & (number => true)
  & (any => false);
```

**Comment by callumlocke** [comment]
Ahh that makes sense now, thank you
