### ISSUE TITLE
Spread operator fails when deeply overriding objects

### ISSUE THREAD

**Issue by pierpo** [facebook/flow#7135]
Hi,

I am trying to override an object with an enriched version of it using the spread operator but flow does not seem to understand.

Am I doing something wrong?

[Example here](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPoqKAM4oCukkAXNSgE4CWAdgOYA0FoWlSytmZAZU4BDALZZmNDj36VSAX0Trk6bKABChEuUo16TFkr4ChIsccqhpchWy5WHoKQBMvrLFSoXSxVQdX4tREhaTgBjFHZYTlAUfxTWAAopZlwASmYDYgEYxJpQACNDQo8AOlqpEMobURIJB1rqqWqmhodvX39A0AByAAssaDgh1o1KNQBuZEo-OlYksoWNIA)

As you can see, the `A` and `B` types are the same, but the key `user` of the type `B` has one more field.
When I create a new object of type `B` by copying my object of type `A` with a spread operation and adding the new value through it, Flow gives an error. 

```javascript
// @flow

type A = {|
  stuff: string,
  user: {|
    name: string,
  |}
|}

type B = {|
  stuff: string,
  user: {|
    name: string,
    address: string,
  |},
|}

function tester(a: A): B {
  const b = {
    ...a,
    user: {
      ...a.user,
      address: 'hello'
    }
  };

  return b;
}
```

gives

```
27:   return b;
             ^ Cannot return `b` because property `address` is missing in object type [1] but exists in object type [2] in property `user`.
References:
5:   user: {|           ^ [1]
12:   user: {|            ^ [2]
```

Might be related to [this issue](https://github.com/facebook/flow/issues/2405).

Thanks for your help :)

**Comment by wchargin** [comment]
Duplicate of #6108.

**Comment by pierpo** [comment]
Indeed. Didn't find it, sorry about that 😉

**Comment by wchargin** [comment]
No problem.
