### ISSUE TITLE
[BUG] Cannot resolve module on windows

### ISSUE THREAD

**Issue by gengjiawen** [facebook/flow#7138]
Reproduce 100% on windows, works fine on macOS and linux.

## Repro steps:
* clone react native https://github.com/facebook/react-native
* yarn install
* yarn run flow-check-android

## What happened
```cmd
$ flow check --flowconfig-name .flowconfig.android
Error --------------------------------------------------------------- IntegrationTests/AccessibilityManagerTest.js:16:39

Cannot resolve module `RCTDeviceEventEmitter`.

   16| const RCTDeviceEventEmitter = require('RCTDeviceEventEmitter');
                                             ^^^^^^^^^^^^^^^^^^^^^^^


Error -------------------------------------------------------------------------- IntegrationTests/AppEventsTest.js:18:28

Cannot resolve module `deepDiffer`.

   18| const deepDiffer = require('deepDiffer');
```
## Related issue
see https://github.com/facebook/react-native/issues/21311

**Comment by leo-tavares** [comment]
I have the same issue

**Comment by jamesisaac** [comment]
All of the files that raise this issue have both a `.ios.js` and a `.android.js` counterpart.  Presumably this issue is because `module.system.haste.name_reducers` isn't working correctly on Windows.  If you take the base RN project on Linux/Mac, and comment the line `module.system.haste.use_name_reducers=true`, then you get the same errors as on Windows.

**Comment by empyrical** [comment]
I can confirm - if you roll back RN to the commit just before it was using `name_reducers`, it works on Windows again. It doesn't appear as if reducers (at least - on the React Native project) ever worked on Windows.

**Comment by jamesisaac** [comment]
CC @jbrown215 @nmote 

Flow still doesn't work at all with React Native on Windows.  Seemingly because `module.system.haste.name_reducers` isn't supported.  This has been an issue from RN 0.56 and Flow 0.75 (July 2018) to present.

**Comment by nmote** [comment]
I don't have time to look into this at the moment but if someone puts together a PR I will make sure it gets looked at. If someone does an investigation, it would probably be good to post what they find here before making a PR, to make sure we're on the same page.

**Comment by avikchaudhuri** [comment]
I bet this section of the code needs more work for Windows separators:
https://github.com/facebook/flow/blame/master/src/services/inference/module/module_js.ml#L506

An old diff fixing regex matching of paths to work with Windows separators might give some ideas: https://github.com/facebook/flow/commit/99e82d07ec40cf2138554fe4483da0f4bf4d0aec

**Comment by avikchaudhuri** [comment]
In particular, I wonder what will happen if we add a `Sys_utils.normalize_filename_dir_sep` on the file name before doing the regex matching. Unfortunately I don't have a Windows environment ready to test this, but hopefully it's a start.

**Comment by jamesisaac** [comment]
@avikchaudhuri Great info, thanks.  I've submitted a PR which fixes (tested locally): #7419

**Comment by avikchaudhuri** [comment]
Hooray! @cpojer @TheSavior let's keep an eye on this.

**Comment by avikchaudhuri** [comment]
@jamesisaac Assuming the diff passes internal checks, I'll merge it soon. Any chance you could also try debugging #6920?

**Comment by cpojer** [comment]
Yay, thank you @gengjiawen and @avikchaudhuri!

**Comment by jamesisaac** [comment]
> @jamesisaac Assuming the diff passes internal checks, I'll merge it soon. Any chance you could also try debugging #6920?

Sure, I can try and have a go with that one too when I get a chance.  To be honest this probably also explains why I wasn't having any luck with `[declarations]` either.  I'll see if I can go through all the flowconfig options and make sure the paths are being normalized.

**Comment by gengjiawen** [comment]
@cpojer Can you help with flow draft a new release so we can use to fix react native ?

**Comment by cpojer** [comment]
The Flow team is already working on a new release which should come out within the next two weeks. They are responsible for syncing it to RN which I expect to happen within that time frame. Sorry for the wait but they have to do a lot of stuff to get a new release out, please be patient 😇

**Comment by gabelevi** [comment]
@gengjiawen I needed to publish a patch release anyway, so I picked this up to. Should be out shortly in v0.92.1

**Comment by gengjiawen** [comment]
@gabelevi Thanks. Will you create the pr to react native ?

**Comment by gabelevi** [comment]
@gengjiawen I don't plan on sending a PR to react native. What would need to be updated? Just the `yarn.lock` I suppose, since this is just a patch release?

**Comment by gengjiawen** [comment]
@gabelevi similar to this https://github.com/facebook/react-native/pull/23289.

**Comment by cpojer** [comment]
As mentioned in the other PR, the Flow team at FB will take care of this upgrade. It cannot be done through GitHub.
