### ISSUE TITLE
Apparent unsoundness in type inference in the presence of circular imports

### ISSUE THREAD

**Issue by krallin** [facebook/flow#7143]
I hosted the repro for this apparent bug here: https://github.com/krallin/flow-unsoundness-repro (it's ~ 65 SLOC)

Consider the implementation of `ImplementationStatesIndex`:

```js
/* @flow */
import type { ImplementationState } from './models/ImplementationState';

export default class ImplementationStatesIndex {
  static empty(): ImplementationStatesIndex {
    return new ImplementationStatesIndex();
  }

  static fromImplementationStates(
    _: Array<ImplementationState>
  ) {
    return ImplementationStatesIndex.empty()
  }
}
```

The apparent unsoundness is in `src/lib/reducer/data/index.js`:

```js
/* @flow */
import ImplementationStatesIndex from './ImplementationStatesIndex';

function unsound(): string {
  return ImplementationStatesIndex.fromImplementationStates([]);
}
```

`ret` should normally be a `ImplementationStatesIndex`, but here, Flow lets us return this as a `string`. In fact, Flow's type inference appears to incorrectly conclude that the type of `ret` is `any`.

There is no error prompting to add a type annotation to the definition of `ImplementationStatesIndex.fromImplementationStates`, but doing so fixes the problem.

What's more interesting is that the issue goes away (i.e. a type error shows up) if we make changes practically anywhere in the repro. For example, remove `PreparedImplementation` and the `PreparedImplementation` import in `src/lib/reducer/data/models/Implementation.js`, updating the file to look like this:

```js
/* @flow */
export opaque type ImplementationId: string = string;

export type Implementation = {
  id: ImplementationId,
};
```

After making this (seemingly unrelated), Flow is now able to locate the aforementioned problematic code:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/lib/reducer/data/index.js:6:10

Cannot return ret because ImplementationStatesIndex [1] is incompatible with string [2].

     src/lib/reducer/data/index.js
     3│
 [2] 4│ function unsound(): string {
     5│   const ret = ImplementationStatesIndex.fromImplementationStates([])
     6│   return ret;
     7│ }
     8│

     src/lib/reducer/data/ImplementationStatesIndex.js
 [1] 5│   static empty(): ImplementationStatesIndex {
```

I'd appreciate help understanding whether there is indeed a bug here, or pointers to troubleshoot further (I'm otherwise a bit stuck at this point).

Thank you!

---

I should mention that I attempted to use `@flow strict` to fix the problem: I was hoping `unclear-type` might catch the issue, but that wasn't the case.

**Comment by krallin** [comment]
I should mention that some older versions do not appear to have this issue: specifically, Flow 0.56 catches the type error, but Flow 0.57.1 does not.

**Comment by SamChou19815** [comment]
We now require the class to be fully annotated, and the issue is caught
