### ISSUE TITLE
[BUG] Using incorrect type signature when redefining functions

### ISSUE THREAD

**Issue by pikelnys** [facebook/flow#7148]
I found this when I accidentally imported a function, and then defined a new function with the same name. 
```javascript
/* @flow */

function something(x: number) {
  return 'is a number'
}

function something(y: string) {
  if (!y) return 'is a string'
  return something(0)
}

something(1) // => 'is a string'
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBnOAWwFN8ALQ7AcwAoAPALjG00oCNqAJwCUYAN6owYQbUyDSAckJkwAQ268BghagC+6LHiIlyVWg2YsAnlzL5BjJqIkBIQlDAsAhFdEz8corKauT2jjou-oGmNPSOLAAMwnroFLEWrACMosDAYAC8AHxgSirqdg7MCkA

This does not throw a type error, even though the first function definition is overwritten.

**Comment by SamChou19815** [comment]
Fixed a long time ago
