### ISSUE TITLE
How to type react-redux connected HOC component?

### ISSUE THREAD

**Issue by svenlombaert** [facebook/flow#7151]
I searched around the issues but could not find any answer.

I'm basically trying to do this:

```javascript
// @flow
import React from 'react';
import { connect } from 'react-redux';
import type { ComponentType } from 'react';

type InjectedProps = {
  foo: string | void,
};

const enhance = <PassedProps: {}>(
  WrappedComponent: ComponentType<PassedProps>,
): ComponentType<$Diff<PassedProps, InjectedProps>> => {
  const WrapperComponent = (props: PassedProps & { things: Array<Object> }) => {
    const { things } = props;

    return <WrappedComponent {...props} foo={'bar'} />;
  };

  const mapStateToProps = (): { things: Array<Object> } => ({
    things: [
      { title: 'Thing 1' }, 
      { title: 'Thing 2' }
    ],
  });

  return connect(mapStateToProps)(WrapperComponent);
};

export default enhance;
```

I followed the HOC guide from the docs, and that works perfectly for **non-connected** components. But when I connect my WrapperComponent, I get this error:

```
[flow] Cannot create `WrappedComponent` element because props [1] 
is incompatible with `PassedProps` [2]. (References: [1] [2])
```

Anyone has an idea how to fix this?

**Comment by svenlombaert** [comment]
Hmm, non of the above seem to work. If I remove `things` from my mappedProps, the EnhancedComponent doesn't complain I'm not passing `things`...

**Comment by krallin** [comment]
@svenlombaert perhaps you could share exactly how you're using this? (i.e. a full example including a a case that should pass type-checking and one that shouldn't, not just the `enhance` declaration)

To be clear, I'm just a Flow user like you — perhaps the maintainers could answer without a full exaple, but those are usually useful :smile:

**Comment by dsainati1** [comment]
The new React.AbstractComponent feature in the v.89 release might solve this problem for you
