### ISSUE TITLE
Union types and type spread operator not creating new subtype.

### ISSUE THREAD

**Issue by felix-h** [facebook/flow#7153]
Union types and type spread operator not working together.
Example:

type A = {
  a: string;
}

type B = {
  ...A,
  b: string,
}

type C = {
  ...A,
  c: string,
}

type D = B | C;

const a: A = { a: 'a' };
const d: D = { a: 'a', b: 'b' };

const tester = (argA: A) => { console.log(argA); };
tester(a); // <- ok
tester(d); // <- gives error below

Error:
Cannot call tester with d bound to argA because:
 • Either undefined [1] is incompatible with string [1] in property a.
 • Or undefined [1] is incompatible with string [1] in property a.

Expected:
'tester' can be called since d effectively is a subtype of A.

Try it, last tested v0.86:
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeiooAhgFygDOyATgJYB2A5gNyIC+iKG2AIQLFSoAHQScAGlEAjanSZsZPPllABhYSTISx00QGMFDFqxW806gCLChAH02dEh2MzoVqeQkU+gA5OT+oFycru7IoAAm1LY+foH+UqDyAbLBobzhHsiYdJj0wgAU5PSsOF4AlAQAfMSg2bDQmGJwrCVlOJXsIZy5+fQl3Sh5uYNR3UA

**Comment by wchargin** [comment]
The problem is that `{...A, b: string}` becomes `{a?: string, b: string}`. This is thus subsumed by #6855.

**Comment by felix-h** [comment]
Thanks for the pointer, closing.
