### ISSUE TITLE
flowtest package mentioned in changelog is not available in repo

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#7154]
The changelog in 0.86 mentions

> Added the flowtest package. flowtest is a CLI tool for running tests on Flow types.

but the link is dead and no flowtest package exists in the flow repo

**Comment by jbrown215** [comment]
We decided to not release it until we gathered some more feedback. The commit that removed it from this repo was pushed after the branch cut, so the pusher had no way of knowing.

I will follow up with it after we get more feedback internally

**Comment by jbrown215** [comment]
459fd067fa96c02947dff7fb82f0e12ad584970a is the last commit that was relevant to flowtest before it was removed.
