### ISSUE TITLE
ReleaseNotes for 0.86 links to non-existing page

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#7157]
https://github.com/facebook/flow/releases/tag/v0.86.0

Under "New Features:

> Added the [`flowtest` package](https://github.com/facebook/flow/tree/master/packages/flowtest). flowtest is a CLI tool for running tests on Flow types.

The link to https://github.com/facebook/flow/tree/master/packages/flowtest is "404 Not Found".

**Comment by vicapow** [comment]
this is a duplicate of https://github.com/facebook/flow/issues/7154
