### ISSUE TITLE
Promise: Missing type annotation for `R`.

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#7158]
I get this error when I try to use a Promise, it seems to have started with Flow 0.79:

```
[flow] Missing type annotation for `R`. `R` is a type parameter declared in `Promise` [1] and was implicitly instantiated at new `Promise` [2]. (References: [1] [2])
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQpEFMAeAHWAnALqACaqQCGArtAQBQCUoAvAHygB2q8oACjrALYBLAM6pqORixx1aQA

I'm not sure what does it expect me to do?

**Comment by AugustinLF** [comment]
They wrote a blog post about this https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8

What you'll need is to specify what kind of content this Promise will wrap.

**Comment by FezVrasta** [comment]
I read that:

> Note that builtin generic types like Map, Set, and Promise are not affected. 

isn't that true?

May you provide an example to make my code work?

**Comment by TrySound** [comment]
@FezVrasta In some cases they require explicit type too.
https://flow.org/try/#0PTAEAEDMBsHsHcBQpEFMAeAHWAnALqACaqQCGArtAQBQCUoAvAHygB2q8oACjrALYBLAM6oAPADdYAwk2o5GLHHVpA

**Comment by FezVrasta** [comment]
I see, thanks!
