### ISSUE TITLE
$Compose a function that takes more than one argument

### ISSUE THREAD

**Issue by retyui** [facebook/flow#7160]
In the current implementation, the `$Compose` accepts only unary functions.

But in javascript you can call the `compose()` function with an unlimited number of arguments.

Here  example [https://flow.org/try/xxx](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAG56gawC2ADrAM5oBcoAJAMIXV0DcyixuokAIygAvKXa00ACkQBIKdkYAjWLGhpsAOwCUjGgBdcAS00BzUQD5QAcmsAaOQr2GTp3aBVqNmy6EMBXNERtbkQpISlrA1drdwNjMxCePgEAJlFxKkkZeUUPVXUtOJczX1sHXOcE0zsPRk1-ciU0XHdPQp8RKwCgpLDIVMjos3tQQVSAZmLqkKA)
```js
// @flow

declare var compose: $Compose;


var f1 = compose(
	(a: boolean): string => '',
	(a: string): boolean => true
);

(f1('sting'): string);


var f2 = compose(
	(a: boolean): string => '',
	(a: string, b: number): boolean => true // error
);

(f2('sting', 123): string);
```
There is a possibility that this can be fixed?

**Comment by dsainati1** [comment]
Which `compose()` function are you referring to? I don't think that's a native Javascript function. Either way, the semantics of a `$Compose` type operator are somewhat ambiguous. It doesn't really make sense to compose an arbitrary function `A => B` with one of type `(B, C) => D`. Where does the `C` come from? You would need to pair your `B` with a constant `C`, and the way you would do that would be implementation specific. You should be able to come up with something for your use case using `$Call`.

**Comment by FireyFly** [comment]
While it doesn't make sense in the general case, it *does* make sense for the right-most function to take multiple arguments: after all, it'll be invoked first.

The [Redux documentation on `compose`][1] explicitly documents this behaviour:
> The exception is the right-most argument which can accept multiple parameters, as it will provide the signature for the resulting composed function.

Since I suspect Redux is one of the more popular providers of a `compose` implementation, and it's a documented behaviour of their take on `compose`, it would be nice if `$Compose` could be tweaked to match this.

Can we re-open this issue (as a feature request) in light of this?

[1]: https://redux.js.org/api/compose

**Comment by retyui** [comment]
I can't reopen this issue.
@dsainati1

**Comment by villesau** [comment]
> While it doesn't make sense in the general case, it does make sense for the right-most function to take multiple arguments: it'll be invoked first, and thus can take all arguments of the resulting function as input.

This is exactly what is needed for [Reselect](https://github.com/reduxjs/reselect). Now the definitions are pretty hacky, and not very usable with required type annotations: https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/reselect_v4.x.x/flow_v0.47.x-/reselect_v4.x.x.js

**Comment by goodmind** [comment]
@villesau this doesnt't work like $Compose, it needs arguments from selectors in right-most function

**Comment by villesau** [comment]
Oh, I misunderstood the previous comment. My bad.

**Comment by FireyFly** [comment]
This doesn't seem to be addressed yet--why close the issue?

**Comment by SamChou19815** [comment]
We don't plan to expand on $Compose, since we don't want more special cased builtin types. Creating a lot of overload might be better.
