### ISSUE TITLE
Flow check files without /* @flow */ directive

### ISSUE THREAD

**Issue by ravecat** [facebook/flow#7161]
Flow check files without `@flow` instruction and spends considerable time on it

>husky > pre-commit (node v10.12.0)
yarn run v1.10.1
$ flow check
Found 0 errors
Done in 7.02s.
 ↓ Running tasks for src/**/*.{js,jsx} [skipped]
   → No staged files match src/**/*.{js,jsx}
 ↓ Running tasks for src/**/*.{js,jsx,json,css,md} [skipped]
   → No staged files match src/**/*.{js,jsx,json,css,md}

Current flow environment
```
"babel-preset-flow": "^6.23.0",
"eslint-plugin-flowtype": "^3.2.0",
"flow-bin": "^0.86.0",
"flow-watch": "^1.1.3",
"flow-webpack-plugin": "^1.2.0",
```

Use flow check in pre-commit hook, my scripts

```
"flow": "flow check",
"flow:watch": "flow-watch",
....
"precommit": "yarn flow && lint-staged",
```

Also can reproduce with repo (step by step paste to console)
1. `git clone https://github.com/ravecat/custom-create-react-app.git --single-branch --branch feature/update-flow-env`
2. `yarn`
3. `git commit --amend` and can see console output like above

Where am I wrong?

**Comment by jbrown215** [comment]
Can you also show your flowconfig?

**Comment by ravecat** [comment]
@jbrown215 
```javascript
[ignore]
.*/node_modules/styled-components/.*
.*/dist/.*
.*/lib/.*
[options]
module.system.node.resolve_dirname=node_modules
module.system.node.resolve_dirname=src
```

**Comment by jbrown215** [comment]
And what in particular is making you think it's checking files without the flow directive? Can you make a minimal repro?

**Comment by ravecat** [comment]
@jbrown215 I wrote in my first post repo for check

1. `git clone https://github.com/ravecat/custom-create-react-app.git --single-branch --branch feature/update-flow-env`
2. `yarn`
3. `git commit --amend` and can see console output like above

**Comment by jbrown215** [comment]
There's nothing from flow in your console output other than `Found 0 errors`, which you would get from running `flow check` in a repo with no errors. Are you getting error messages in files that don't have a `@flow` pragma? If not, I'm not sure I understand what you're asking here.

**Comment by Brianzchen** [comment]
Running flow for the first time will always take time because flow instance is starting regardless of how many flow files there are to test. Closing until there's more info
