### ISSUE TITLE
What about React.lazy, React.memo and React.suspense?

### ISSUE THREAD

**Issue by mcharytoniuk** [facebook/flow#7162]
I tried using React 16.6 features like lazy or suspense (https://reactjs.org/docs/code-splitting.html#reactlazy ) but those types are not supported by flow yet. 

I also didn't see other opened issues regarding that (which I find weird because I expected those features to be popular :D). Is this behavior planned or lazy / suspense should be used in other way with Flow?

![screenshot 2018-11-12 at 00 04 29](https://user-images.githubusercontent.com/1286785/48319459-8af45880-e60e-11e8-9cc9-82547bc2a333.png)

![screenshot 2018-11-12 at 00 03 35](https://user-images.githubusercontent.com/1286785/48319452-6bf5c680-e60e-11e8-9aa7-9e34b734ae81.png)

**Comment by AugustinLF** [comment]
No luck, there is an issue^^ #7093

**Comment by jbrown215** [comment]
Working on it. closing in favor for #7093

**Comment by kevinSuttle** [comment]
Shipped as part of [0.87.0](https://github.com/facebook/flow/releases/tag/v0.87.0)
