### ISSUE TITLE
the second statement in if condition

### ISSUE THREAD

**Issue by snasc** [facebook/flow#7163]
The code is like this:

[flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiYAvGAN4CGA-AFxgDOGATgJYB2A5gL4DcmuAgCFSFSvSZsuAGjAAjCSw49+qAG6VmYKHDj1iZKvQDkAZmN91m+ZvojD4sMYCMx2QqcAmC6tZQwABQ6cAB0lACUFKhgNsxhosFh-DFymiFyCbpJqNxAA)

```javascript
type F = {a?: string};
type B = {a: string, b: string};

var foo: F = {a: '3'};
var bar: B = {a: '1', b: '2'};

if (foo.a) {
  bar.a = foo.a;
  bar.b = foo.a;
}
```

and Error is: Cannot assign `foo.a` to `bar.b` because undefined [1] is incompatible with string [2].

Looks like in the first statement of if condition, Flow known it is not undefined. But why in second statement, Flow say it maybe 'undefined' and incompatible with string?

**Comment by ChristianKienle** [comment]
This seems to be a case where a refined type has been lost.

This should work:
```
const { a } = foo;
if(a) { bar.a = a; bar.b = a; } 
```

Usually each expression discards previous checks if they are not conserved by assigning the thing you have checked first.

I haven't used flow in a long time so it is possible that I am mistaken but I am pretty sure that my workaround still works and it is also mentioned in the docs as a pattern to work around similar problems.

**Comment by snasc** [comment]
@ChristianKienle  Can you give me a link to thd doc that mentioned this? 

Thanks.

**Comment by jbrown215** [comment]
https://flow.org/en/docs/lang/refinements/#refinement-invalidations- is where we talk  refinement invalidations and what causes some of them

**Comment by snasc** [comment]
I got it. Thank you @jbrown215
