### ISSUE TITLE
Spreading optional exact objects breaks exact objects

### ISSUE THREAD

**Issue by entropitor** [facebook/flow#7164]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKcAzgJYZlwB2YAvGAN4A+qYYAHgFxjUCuAWwBGeAE4AaNmCw9+wsZOYBfdFD7UAxpRphReEngwANABQ4eAfmLlt1AJQ9rFKrUZS9GPqNdT2AOgCcSXZ2bjAABmCwFRUNGhI4GDw-eABzEz0DYxN+GBg7OyA

```js
/* @flow */

type Position = {|
  x: number,
  y: number,
|}

function resetX(p: ?Position): Position {
  return {
    ...p,
    x: 0,
  }
}
console.log(resetX(null))
```

The function resetX should give an error as the return value doesn't match the return value if the input is null

e.g. console.log logs {x: 0} (no y) and that doesn't match the exact type Position

**Comment by kubilaykiymaci** [comment]
Which version do you use? It looks fixed after 0.70 version.

**Comment by entropitor** [comment]
@kubilaykiymaci Well, I want it to be a Position but I want flow to give me an error that this code is invalid, so I can return a valid Position

**Comment by nmote** [comment]
This errors as expected in master
