### ISSUE TITLE
React Class context type not inferred from `static contextType`

### ISSUE THREAD

**Issue by skidding** [facebook/flow#7166]
The newly added [Class.contextType](https://reactjs.org/docs/context.html#classcontexttype) feature added to React makes it easier to bind a single context to class components.

But it seems that the type of the context value isn't inferred on `this.context` in the class instance. Is this know and are there plans to support this?

**[Try Flow example](https://flow.org/try/#0JYWwDg9gTgLgBAbzgYQuCA7AphmAaOAYyiwEMYtVcsAPeAXzgDMo04ByE0wmdgbgBQAmAE8wWOAFkRVCnQBqpADZwAvIgFw4AVwDOWKAC5EcDKRBZjumFGAYA5nHoDnAwpmtSZmOfHXEyCllaGAAeaWCFZQA+AAoETR19IxMzC2N2AHFtLGt2JxcASiFCJVJdXS9UdGxcOBCcABNK6shasIR6aI0tAHpeuABRGnEeLEa4GAALYEqlOwkYCDg7JgMqnxD2StFxFdxl6dmAOndqOmPE-rgASQxrMkaCI91TzboVyv0cOHK4AANSBgRP9LlprORgIQiO8YAAVMQSdQRWGCLRXAYAVQw7hAFjqLzg82wk2WSiw8AAYkoIAB3OAAawwdMmM1eZ18xzSEkaEFyGHYMGOtFmQoxHJCxhR5xgiiUaLgiRIGEaBlihR6WjgJBg2igGABAAlgHAACQIF5vGVc8xYegAQn+iWcriAA)**

```js
import { Component, createContext } from 'react';

type MyContextVal = {
  user: { name: string }
}

const MyContext = createContext<MyContextVal>({
  user: { name: 'Guest' }
})

class MyComponent extends Component<{}> {
  // Expected this line to infer MyContext's type into this.context.
  // Instead, this.context is seen as `any`.
  static contextType = MyContext;
  
  // Uncomment this line to let Flow know this.context.name doesn't.exist.
  //context: MyContextVal;
  
  render() {
    return `Hi ${this.context.name}!`
  }
}
```

Thanks!

**Comment by jbrown215** [comment]
I'm currently working on React types and can look further into this.

**Comment by jfo84** [comment]
Would really appreciate it, @jbrown215. Happy holidays!

**Comment by skidding** [comment]
@marioestrada You can declare `context` as an instance property with the type of your context. See the `context: MyContextVal` commented line in my initial post.

**Comment by jbrown215** [comment]
I'm not planning to add built-in support for this, unless the React community rejects hooks. To me, it seems like function components are the future and that I should focus my work on React types to be around function components.

**Comment by dmnd** [comment]
@jbrown215 perhaps that's an OK approach for greenfield projects. 

But one of the big benefits of Flow is being able to adopt it in an existing project, and existing projects probably have a lot of class components that work fine and don't need to be rewritten.

From the [Hooks docs](https://reactjs.org/docs/hooks-intro.html#gradual-adoption-strategy):

> We intend for Hooks to cover all existing use cases for classes, but we will keep supporting class components for the foreseeable future. At Facebook, we have tens of thousands of components written as classes, and we have absolutely no plans to rewrite them. Instead, we are starting to use Hooks in the new code side by side with classes.

**Comment by jbrown215** [comment]
@dmnd: That's true, but I also have to prioritize what I work on to make sure I'm doing the most important work I can be doing. Right now, stronger built in support for `static contextType` is not the most important thing I can do.

**Comment by goodmind** [comment]
Any idea why this can't be done with libdefs?

```js
import * as React from 'react'

class FakeComponent<Props, State> {
  static +contextType: React$Context<any>
  +context: mixed
}

class A extends FakeComponent<{||}, {||}> {
  static contextType = React.createContext(1)
  context: number
  render() {
  	A.contextType // type is React$Context<any | number>, not $ReactContext<number>
  }
}
```

**Comment by dmnd** [comment]
Thanks for all your work on Flow, @jbrown215. 

I understand one must always prioritize, it's just a bit disappointing that Flow doesn't have enough resources to aim for full support for React. Maybe you could add the label `Accepting PRs`?

**Comment by bambielli-flex** [comment]
Also ran in to this! My solution was to type both the static contextType value *and* the context property itself. 

something like this:

```{javascript}
// file1 where context is provided
const myContext: React.Context<number> = React.createContext(0);
export {myContext};
```

```{javascript}
// file2 where context is consumed
import {myContext} from 'file1'; 

type Context = number;

class ClassName extends React.Component<Props, State> {
  static contextType: React.Context<Context> = myContext;
  context: Context;

  render() {
    const myValue = this.context; 
    ...
  }
}
```

Typing contextType as React.Context<Context> in file2 checks against the type of the exported `myContext` in file1. Without this type, the type of myContext could change in file1 and would not be caught in file2.

Typing `context: Context` in file2 allows the extraction and usage of myValue in the render function to flow check.

Aliasing the expected value from the context as `type Context = number` at the top of file2 ensures that context and the value provided by contextType are the same.

**Comment by SamChou19815** [comment]
This won't be supported, and we already killed prop-types support
