### ISSUE TITLE
Need more documentation on gen-flow-files option

### ISSUE THREAD

**Issue by aeulitz** [facebook/flow#7168]
[Please advise if there's a better forum for what essentially a flow compiler usage question.]

I was wondering if the output of the gen-flow-files option can be used to detect changes of the public API of flow-authored components (e.g. via an automatic build step that compares submitted flow declarations against recalculated ones). My attempts to generate flow declarations via compiler invocations like

> flow-bin\flow-win64-v0.67.1\flow.exe gen-flow-files react-native\Libraries\WebSocket\WebSocket.js

… result in tons of error messages like

          Error ------------------------------------- ../../../src/react-native/IntegrationTests/AccessibilityManagerTest.js:13:29
          Cannot resolve module react-native.
          13| const ReactNative = require('react-native');

… i.e. errors in files that are seemingly unrelated to the gen-flow-files argument (WebSocket.js). This is most likely due to using the gen-flow-files option in an unintended way, but where can I find documentation on how gen-flow-files is intended to be used?

**Comment by jbrown215** [comment]
`gen-flow-files` is very broken right now. We have a version that will work in the pipeline, but it's not quite ready yet. When we release it, we will put up a blog post and documentation.
