### ISSUE TITLE
[Question] Async not work in class

### ISSUE THREAD

**Issue by HsuTing** [facebook/flow#7169]
[example](https://flow.org/try/#0C4TwDgpgBAzsD2AnCAVc0C8UDeAoKUArjBIgHYCGAthAPwBcswiAlmQOYA0+UEVFLADYMmrDtwC+Ably4AxoIowYUAMIU5AC2gAeFAD4cPOEgiMUMgj3YRgACjCJ4AKwhzgAERaJGcMewBKRgAFJyoWEj1DPAICZGBCcigyCAB3KFD4cJI7O2QYeEEAN0xonliofMKSu2BNCIA6E2QAy1iJANaeCR5rWxRU+CgsJRAyOSgHJ1d3Lx9RNkCQsIiIKOGyivjEsig6xuaINulcHvlFZSgAVRJEXgAPYAgyABMVdS01w7RIMrO5eBkOBEW7DZJpa63OxdXB2UbjSYBDZGAgAoHASoQGCEQTAXwIZA-TBQCipAQY4ikBo2ewAciecFpXVRgOB+RxwAG8HxpiJYNJ5JBVJpXLs9KxwCZMg60KkQA)

code:

```js
type storeType = {
  username?: string,
  email?: string,
};

class Cache <T> {
  store: T;
  
  get(projectDir: string): Promise<T> {
    return new Promise((resolve => {
      resolve(this.store);
    }));
  }
  
  getTwo = async (projectDir: string): Promise<T> => {
    return this.store;
  };
}

class User extends Cache<storeType> {
}

const user = new User();

(async () => {
  const result: storeType = await user.get('test');
  const resultTwo: storeType = await user.getTwo('test');
})();
```

I think `user.get` should be equal to `user.getTwo`, but it do not work.

**Comment by HsuTing** [comment]
[update]

This can not get variables in store, too.
[example](https://flow.org/try/#0C4TwDgpgBAzsD2AnCAVc0C8UDeAoKUArjBIgHYCGAthAFyzCICWZA5gDT5QRUVMA29OMzacAvgG5cuAMb8KMGFADCFGQAtoAHhQA+HFzhI6UFFIJdWEYAAowieACsIM4ABEmiIYxasAlPQACg5UTCQ6+ngEBMjAhORQZBAA7lDB8KEkNjbIMPD8AG6YkVzRULn5RTbA6mEAdEbIfubRYn7NXGJcltYoyfBQWAogZDJQdg7Orh5eDCL+QSFhEBGDJWWx8WRQNfWNEC2SuF2y8opQAKokiNwAHsAQZAAmSqoaK-tokOsMxoMGZWIpEoNHoAHIgeRqBAwZwyjw+IIoGCEQJYZ1jtIZPAyHAiNd-klUldSDYOrgbMNRuM-GsAVBsbjgDh8cDoVAxN5jF9MFAKMk+MzIXUrLYwQ84GCOgRGXjsKyoaCFSDUP0OVzkDz-vzBQqRb1+jZxRBJR02mSJEA)

```js
type storeType = {
  username: string,
  email: string,
};

class Cache <T> {
  store: T;
  
  get(projectDir: string): Promise<T> {
    return new Promise((resolve => {
      resolve(this.store);
    }));
  }
  
  getTwo = async (projectDir: string): Promise<T> => {
    return this.store;
  };
}

class User extends Cache<storeType> {
  store = {
    username: 'username',
    email: 'email',
  }
}

const user = new User();

(async () => {
  const { username }: storeType = await user.get('test');
  const { username: usernameTwo }: storeType = await user.getTwo('test');
})();
```

**Comment by wchargin** [comment]
Explicitly annotate the type of `getTwo`. This is #4743.

**Comment by HsuTing** [comment]
@wchargin Thank you!
This work!

**Comment by wchargin** [comment]
You're welcome; glad to hear it.
