### ISSUE TITLE
[Question] Using disjoint unions

### ISSUE THREAD

**Issue by sgb-io** [facebook/flow#7172]
Reproduced example: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMrIIbLYC8oA3oqKANTIAWAlgHYDmAzgFygCCATr-lQAeCgEhR1JvgC2mLm2S9mLADSUqGqtQDGsAK5NkXJnukAjTLzWgAvgD5ENgNyJEupgtwBRACoB9ADluAFkvUFIAchxfQJCvCLdYD2RvfwBhAHkAVQCfcNAomMycnwSUDGwcTGQAmRJyUDQsLibMWEhU2NCVUClZeUVlWxdW3Gq0-UN8skaKlor2zuLcnt0DI17TC15h11HubWQGJPyqmrrQAB8x5An1l0RIA0PjplBeTAATPW1LAAoFIQ5LgCEQevgXkkuAcjkkAJRcPBA8jqNjwBjIbR0UB-CGwpgAOlacJRmm0+DYlRiQVCHHUmg+yD0vDeFE0mgJnMBYPp7Poyk4oG5mCJjFYbAJ0nw6D+f35rBJxDspPZVFEjOZrN5mnEnNFymsqqNVD6wLxrwJpu1oHENmtohscOtzlconJlKW2VydNVGpZKtVeuFhtV8vYAyB+vFkulsrDiuVbKN6uqmoD7N1nLDIeN7LWhi45qSBPzyHtDvtjudD00n0wkHwemgRlE1r9b2FLiodpsQA

Having read the documentation and read similar issues, I am unclear how to correctly use disjoint unions in the simple example above.

Is anyone able to point me in the right direction here?

**Comment by AugustinLF** [comment]
The problem is actually not with the union, but with your map call which invalidates the refinement.

**Comment by wchargin** [comment]
@AugustinLF is correct. Here are the [docs on refinement invalidations].
Here is a [fixed example] of your code.

[docs on refinement invalidations]: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-
[fixed example]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagMrIIbLYC8oA3oqKANTIAWAlgHYDmAzgFygCCATr-lQAeClSrUm+ALaYubZL2YsANJTHUAxrACuTZFybapAI0y81AXwB8iCwG5EiLU3m4AogBUA+gDluAWTdQUgAiHE9fALcQh2dXcO8AYQB5AFUfD2DQMIiU9I8YxzQsXExkH2kSclBi2RqMTFhId28-QOVQSRk5BSVQexQG0uREnT0ssnqsLlqmlq88jI6tXX1Oo1NefodBku4NZAZYJiycMoqZUAAfYdHVnchdA6OT3kwAE20NMwAKeUI6ngAR18M9jlx9odjgBKLhAojkNRseAMZAaOigH6gqFMAB0tWhiLEoA0+DY2ASkUCXFExJJx1cXSq2JeuKZDjpoDeyG0vBOtM5uKF-yIqk5VHoSk4oBFmHxjFYbFxUnw6B+ktYwSsRPFVG5vP5al1VCF8qUYuNVCZRvFA11FmhNqodrEFhtpPJ80WHhpTvpLmQ9NWWRZx1xKz0HLp+r5OsFwoIor9EoV7B6ALNiuVqvVqa1cfFMcNlpNQo1KmTdIjyErzqjnIdfpdzpt70wkHw2mg+j9RZlicwUbdbqAA

**Comment by sgb-io** [comment]
Thanks @AugustinLF @wchargin
