### ISSUE TITLE
Flow generic of type {} is incompatible with default value of {}

### ISSUE THREAD

**Issue by robCrawford** [facebook/flow#7173]
Flow reports that a default argument value of {} is incompatible with a generic of type {}.
Here is a minimal example:

```javascript
function copy<T: {}>(o: T = {}): T {
  //                        ^ object literal [1] is incompatible with `T` [2].
  return {
    ...o
  };
}
```

The docs say about the type {}, "Sometimes it is useful to write types that accept arbitrary objects, for those you should write {}".
So in what sense are they incompatible?

**Comment by wchargin** [comment]
Flow is correct, and this doesn’t have to do with default values in
particular. Here is a simpler example:

```js
// @flow
function foo<T: {}>(): T {
  const t: T = {}; // error! (good)
  return t;
}
```

It is important to understand that the notation `T: {}` does not mean
that `T` must be _exactly_ `{}`, but rather that it must be a _subtype_
of `{}`. In other words, `T` may be any object type. If the above code
typechecked, then I could write

```js
const bad: {x: string} = foo();
```

but then `bad` would actually have value `{}`, which would be unsound.

That is: your function does indeed accept arbitrary object types `T`,
and `{}` is not an instance of an arbitrary object type.

**Comment by robCrawford** [comment]
Ah, so I think you're saying that any hard-coded return value breaks the contract that `T` is generic. 
This reminds me of a common Elm error which would be like "Your type annotation uses type variable `T` which means ANY type of value can flow through, but your code is saying it specifically wants to return `{}`".
It had seemed to me that an empty object literal would also satisfy any subtype, but thinking about it that's a bad assumption.

**Comment by wchargin** [comment]
> Your type annotation uses type variable T which means ANY type of
> value can flow through, but your code is saying it specifically wants
> to return `{}`

Yes, that’s a good explanation.

> It had seemed to me that an empty object literal would also satisfy
> any subtype, but thinking about it that's a bad assumption.

Right. :-)

**Comment by dirtyhenry** [comment]
Following the example below, I get why Flow could error when `copy` is being **used** with an actual type for which `{}` is not a valid value, but I don't understand why Flow errors when `copy` is **declared**.

For instance, consider this declaration: 

```
function canonicalize<T: {}>(value: ?T): T {
  const neutralElement: T = {};
  return value ? pickBy({ ...value }) : neutralElement;
}
```

`canonicalize(null)` and `canonicalize(undefined)` should return `{}`.

How can I achieve that without having to do this: 

```
function canonicalize<T: {}>(value: ?T, neutralElement: T): T {
  return value ? pickBy({ ...value }) : neutralElement;
}
```

Is there a way I can be more specific to what types are allowed than `<T: {}>`?

**Comment by robCrawford** [comment]
Flow errors any time your logic contravenes your types... `T` is the type 'any subtype of {}' which includes things like `{| id: string |}`. An empty object isn't of that type. You could annotate with an object of none or more props:
```
function copy(o?: {} = {}): {} {
  return { ...o };
}
```
Or to keep the generic you could add the literal to the return type.
```
function copy<T: {}>(o?: T): T | {} {
  return { ...o } || {};
}
```

**Comment by dirtyhenry** [comment]
> `T` is the type 'any subtype of {}' which includes things like {| id: string |}. An empty object isn't of that type.

I understand that.

But I feel like Flow should error when `T` is resolved as a type for which `{}` is not a legal value, rather than when such a function using `{}` as a legal value for a type `T` is declared.

**Comment by wchargin** [comment]
When you write `function canonicalize<T: {}>(value: ?T): T`, you’re
making a _promise_ that for _any_ type `T` that is a subtype of `{}`,
the function `canonicalize` accepts a `?T` and returns a `T`. Flow is
informing you that you are in fact breaking that promise, and so is
properly erroring.

Suppose that you were writing a library, and you defined

```js
/** Returns its input. */
export function identity<T>(x: T): T {
  return 4;  // `T` should be `number`, by the way
}
```

as a public function that is exported and used by consumers of the
library but is not used within the library itself. If Flow were to act
as you suggest, then there would be no error at the declaration of
`canonicalize`—even though it is erroneous!—or in your library at all,
but _users_ of the library would get an error when they tried to use it
in the way that the types say that they can.

Flow’s generic types are different from C++ templates in this respect.
The function isn’t typechecked separately for each value of the type
parameter that ends up being used; it’s a single function that has a
generic type. Once the type of the function is determined, the body is
irrelevant: all functions `<T>(x: T) => T` are treated identically from
Flow’s perspective. This is critical to modularity. When I see that a
function has a certain type, I can safely use it in accordance with that
type, without having to worry that I’ll get an unexpected type error if
I pass some parameter that is valid according to the type but actually
violates some “hidden requirement”.

**Comment by ancmikesmullin** [comment]
as a restatement of https://github.com/facebook/flow/issues/7173#issuecomment-456495732

I was interested to find this does not work:

```js
Utils.reduce = /*::<T: any = {}>*/(a/*:mixed[]*/,cb/*:(T,mixed,string)=>void*/,def/*:T*/={}) =>
    _.reduce(a,(acc,v,k)=>{ cb(acc,v,k); return acc; }, def);
```

but this does:

```js
Utils.reduce = /*::<T: any = {}>*/(a/*:mixed[]*/,cb/*:(T,mixed,string)=>void*/,def/*:T*/) =>
    _.reduce(a,(acc,v,k)=>{ cb(acc,v,k); return acc; }, undefined === def ? {} : def);
```
