### ISSUE TITLE
Generic types not working with arrow functions

### ISSUE THREAD

**Issue by yassinecc** [facebook/flow#7174]
When using generics, Flow throws an error when using arrow functions, unless they are explicitly typed, see [this example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodBjGBDAzrsAWQE8BhHfARgB4AVAPjAG8wxhgwA5OMAUwCd+cfmAQBLAC4ALOAFcJYDHAB2E3gA8FAIzHKAJroDmqVgDds-Mdi0xeALjC0A3CbAqAqgAc92NWAAUALa+GFIOtACUzAC+LqwmSoGeKryqACJieoRyqv5RTK6s0mK4AHQe3r68-sVl5pbWthFxYNGobahYeAQk5N0ATHSMLGwc3HyCwqKSUnzqnjBiGJJgEsSeRq71Vjb2ji0VPmrhYAC8jKZwmWcBwRKh4VHnMS0JcEkp6ZnZsrn5haspCVysovEdqrVSttGrxmq42h0uvgiGQKLgAMxDZisdhgACikxEUgEvC2Fh2tnCB1BlT8p1uITCjiew1irjeH2UqQkGSyOQkeWYAMhhyqNSBdXJMLhrARqCAA)

I would have thought that Flow would have inferred generic types in this case:

```
class MyClass<T> {  // Error here
  variable: T;
  onUpdate = (match: T) => {};
  
 componentDidMount() {
    this.onUpdate(this.variable);
  }
}
```

**Comment by jbrown215** [comment]
Flow never infers generic types :(
