### ISSUE TITLE
Flow has used 11G memory

### ISSUE THREAD

**Issue by vfan** [facebook/flow#7177]
![2018-11-15 16-57-12](https://user-images.githubusercontent.com/1477088/48541599-e87ef280-e8f7-11e8-8cf8-d539d1487e3d.png)

**Comment by jordyvandomselaar** [comment]
Even more for me:

![image](https://user-images.githubusercontent.com/12712484/48557336-c29d2200-e8e6-11e8-898d-3819277cb11d.png)

**Comment by jbrown215** [comment]
Is your project open source? It's possible there's some pattern going on that causes flow to use a ridiculous amount of memory.

**Comment by jordyvandomselaar** [comment]
@jbrown215 mine isn't unfortunately.

Could it have to do that I've included node_modules?

**Comment by jbrown215** [comment]
yep, that's entirely possible

**Comment by jbrown215** [comment]
Node modules usually don't have flow types-- you can use https://github.com/flow-typed/flow-typed for external libraries
