### ISSUE TITLE
AMD support (Almond)

### ISSUE THREAD

**Issue by agentcooper** [facebook/flow#718]
Having modules in the following format:

``` js
define('store', function(require, exports, module) {
    'use strict';

    var store = { /* ... */ };

    module.exports = store;
});
```

I can use

```
[options]
module.name_mapper='store' -> '../modules/store'
```

to make this work

``` js
/* @flow */

var store = require('store');
```

But Flow does not understand `module.exports` in the module, is there any way to make it work?

**Comment by TrySound** [comment]
I'd say pure AMD is not relevant anymore. Better to use it as generated format from esm. Rollup supports it https://rollupjs.org/guide/en#output-format
