### ISSUE TITLE
Not supported Node.isConnected nor Node.getRootNode()

### ISSUE THREAD

**Issue by jorgecasar** [facebook/flow#7180]
Attending to the Node API are missing isConnected readonly property and getRootNode method

**Comment by jbrown215** [comment]
Feel free to put up a PR

**Comment by jbrown215** [comment]
Sorry I've taken a while to merge this in-- there's been a whole bunch of updates to the libdefs recently which cause conflicts. I will make sure this is in the 0.89 release.
