### ISSUE TITLE
ocamlbuild -use-ocamlfind -no-links -I scripts scripts/ppx_gen_flowlibs.native

### ISSUE THREAD

**Issue by luojuan5** [facebook/flow#7184]
Hi, when i build flow on windows 10, use make all, occur this mistake: 

aaa@DESKTOP-Q189CVH ~/opam64/flow                                                
$ make all                                                                      
ocamlbuild -use-ocamlfind -no-links -I scripts scripts/ppx_gen_flowlibs.native   
make：ocamlbuild：命令未找到                                                     
make: *** [Makefile:289：_build/scripts/ppx_gen_flowlibs.native] 错误 127
--
what could I do to solve this problem
Thank you!

**Comment by luojuan5** [comment]
$ make all
ocamlbuild -use-ocamlfind -no-links -I scripts scripts/ppx_gen_flowlibs.native
Failure: ocamlfind not found on path, but -no-ocamlfind not used.
Compilation unsuccessful after building 0 targets (0 cached) in 00:00:00.
make: *** [Makefile:289：_build/scripts/ppx_gen_flowlibs.native] 错误 2

**Comment by jbrown215** [comment]
The error message says you need ocamlfind on your path.

**Comment by luojuan5** [comment]
Thanks very much, but another mistake occur:

aaa@DESKTOP-Q189CVH ~/opam64/flow                                                $ make test                                                                      ocamlbuild -use-ocamlfind -no-links -I scripts scripts/ppx_gen_flowlibs.native   + ocamlfind ocamldep -package core_kernel -package unix -package compiler-libs.c ommon -package wtf8 -package ppx_deriving -package dtoa -modules scripts/ppx_gen _flowlibs.ml > scripts/ppx_gen_flowlibs.ml.depends                               ocamlfind: Package `core_kernel' not found                                       Command exited with code 2.                                                      Compilation unsuccessful after building 1 target (0 cached) in 00:00:06.         make: *** [Makefile:289：_build/scripts/ppx_gen_flowlibs.native] 错误 10
--

I have tried install core_kernel, but it haven't successful

**Comment by jbrown215** [comment]
Have you followed the setup instructions here: https://github.com/facebook/flow#building-flow

**Comment by jbrown215** [comment]
Ah. How did you install core_kernel? `opam install core_kernel` ?

**Comment by luojuan5** [comment]
yeah, it's wrong?

**Comment by luojuan5** [comment]
Yeah，I have run eval $(opam config env).

**Comment by mroch** [comment]
https://github.com/facebook/flow#readme has updated instructions for building on Windows
