### ISSUE TITLE
null or undefined is incompatible with IntervalID

### ISSUE THREAD

**Issue by pronebird** [facebook/flow#7186]
I have a __plenty__ of code that does something like:

```js
if (this._foo) {
  this._foo.bar();
}
```

Today, suddenly out of blue, it does not work anymore.

```
Cannot call clearInterval with this._relaysInterval bound to intervalId because null or undefined [1] is incompatible
with IntervalID [2].

     packages/desktop/src/main/index.js
 [1]  71│   _relaysInterval: (null: ?IntervalID),
        :
     475│     if (this._relaysInterval) {
     476│       log.debug('Stop relays periodic updates');
     477│
     478│       clearInterval(this._relaysInterval);
     479│
     480│       this._relaysInterval = null;
     481│     }

     /private/tmp/flow/flowlib_1dbb92ab/core.js
 [2] 731│ declare function clearInterval(intervalId?: IntervalID): void;
```

Now the best part: if I comment out the `log.debug` line - the error is suddenly gone! 😆😆 

```js
  _stopRelaysPeriodicUpdates() {
    if (this._relaysInterval) {
      // log.debug('Stop relays periodic updates');

      clearInterval(this._relaysInterval);

      this._relaysInterval = null;
    }
  },
```

**Comment by wchargin** [comment]
> if I comment out the `log.debug` line - the error is suddenly gone!

This is correct. [Any function call invalidates refinements.][1]

[1]: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

Please read those docs and, if you are still seeing surprising behavior,
post a Flow Try link demonstrating code that you think should typecheck
but in fact does not.
