### ISSUE TITLE
Weird error with optional properties when interfaces are nested

### ISSUE THREAD

**Issue by ivanhoe011** [facebook/flow#7187]
Flow complains when optional object property is properly set to a string. If it's not set at all it works fine.

Please see the code example: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgBE2pFdA3MigHa5HaTlGgyAV2yMuAVQDOPACoBPDAIDeiUKA4k0RAFyhJubJwDmAGlWgh07AH10JI0QD8u-YY6nEAX3ZcefMgJksByQKEbyiqAqapY8usKiRBJWEURm3oi4CgIACtQYkqAAvFGqQSFh8cGh4dmgXsjl+qBocgDC1cWlMVa60WrqmjqgAOQA6gAWJNwAbjwjZgMWVrZo9sMjAEYk2AB0AFYYRgvm3t5q5pdN+ABisLBdABRK5TWeoLp5sAUAlMUAfKBHuYADwAExQM3+5gGNwA8nCBqDgBCoYgfmxENdQABBDAYJ5-IqA-pqRi4EQcIEwgYASBBdwerzCRSUrQ6IXewGhSwxDUQRAAHlg8KAwUQ+EJoPg8RgWEA

Using type instead of interfaces solves the problem, but I don't know how to export the rules then?

**Comment by belka-ew** [comment]
Even smaller example:

```js
'use strict'
// @flow

interface RouteConfig {
  redirect?: string
}

interface RouterOptions {
  routes: RouteConfig
}

const router: RouterOptions = {
  routes: {
    redirect: 'projects'
  }
}
export default router
```

**Comment by mislav** [comment]
[Ran into this problem as well](https://flow.org/try/#0CYUwxgNghgTiAEBLAdgFxDAZlMCCC8A3gFDzwD058qAFggEYCuA5vAM4ggC2b1A9vHoJUMRM2YYQwQQE9qNRLyEpWUZPD4AHVIj7IoEeAAoABgH4TASngBrEDIBcpDdt36IAaXtmH7ESoBuYgBfYmJQSFgEFHQsHAQABSJnZBA2dGAASTQMbFxfPCDQsmJMRmQwHT0-EE0AIRkAZXRNI0tfJJIySnlFeAB3PhgbXj0IOSEwKEYOJFQBqF4QAA9NCEQwRFRx+AjoOGlF+AAiPGPqGU0QJzIwPXT4VPSpbNi86-gCAF5ksjItKruLyOeAAcjoEAgfFBzmK8DgqEYMHUXT+Twyr1y8VhITCZQqgPgBggeFQAHkKiA2h1fhQqPQ+LQTmcichpMcEucYljcLx+pJ2FAdGxMIgpAAaQSMeaYKH9eBgGh8OxsG7wkCI5G0sjol45OL5bV-AFuAzA3zgkCQ6HOMhw0LBIA) with latest Flow (v0.101)

**Comment by stephan-noel** [comment]
Just posting her to update that this is still happening for me, not only with optional properties though.

```
Cannot assign object literal to theme because inexact TypographyDescription [1] is incompatible with exact object
literal [2] in property typography.headingThree. [incompatible-exact]
```

**flow-bin version**:  `0.145.0`

I'm using create-react-app.

**Example**:  

![image](https://user-images.githubusercontent.com/34415120/109343207-e0e37d80-7864-11eb-869e-655513e8c78f.png)

**Successful workarounds**:

- Changing `TypographyDescription` from an interface to a type alias

**Failed workarounds**:

- Making `fontWeight` required

**Comment by SamChou19815** [comment]
The problem seems to be fixed a long time ago
