### ISSUE TITLE
Union type with self-referential can't be generated using gen-flow-files

### ISSUE THREAD

**Issue by sakai-akinobu** [facebook/flow#7190]
For example, the following case.

```javascript
export type Foo = number | Foo[];

const num: Foo = 1;
const ary: Foo = [1, 2];
```

If this code is converted with the `flow gen-flow-files` command, it will result in an error. It seems that it can't be converted if the union type includes a self-referential.

Since it works correctly at type checking, this definition is a supported syntax, isn't it?

I wrote the [reproduction code](https://github.com/sakai-akinobu/issue-of-self-referential-type).

## Environment

- flow-bin: 0.86.0
- Node.js: 10.11.0
- OS: macOS 10.13.6

**Comment by jbrown215** [comment]
`gen-flow-files` is very broken and not being maintained right now. We have an alternative solution in the pipeline

**Comment by sakai-akinobu** [comment]
OK, I will expect an alternative solution. So I will close this issue.
Thanks for the reply.
