### ISSUE TITLE
Covariance not working when used beside destructuring in type.

### ISSUE THREAD

**Issue by blarsonat** [facebook/flow#7196]
Here is a concise repro tested in try flow:

https://flow.org/try/#0C4TwDgpgBAsglgDzgOygXigbwD4CgpQCGA-AFxQDOwATigOYA0u2AvgNy66iRQBChFCABVw0DJnxQA1ADNyVWskaSA9CqhDqIKNQgBbAPYA3elGAALaMggJgUADYpohZABMoIAwFcoAdzj29pQQ0BaEdgDGxoS0LhHQBjJQMnAQ9u4A5DIZfgbUANYUUGDUBpDU9iAAdJJVdfBIyEzsnNzQAMpeAEYR9gIUIjziknJQGQbWOdhjwL4GGUwEdVUNKM0cuFHIVGYQVOSdPX0UA6LoWCPk45PrnFs7XQLCe8Dk-IKDYrtUHEA

The code is:

```js
type Mixin = {|
  a?: string,
|};

type BaseType = {
  +f: string,
  // Try removing the next line and you will see that covariance of field 'f' works properly.
  ...Mixin,
};

type SubclassType = {
  f: 'one' | 'two',
  ...Mixin,
};

const test: SubclassType = {
  f: 'one',
};

const baseTest: BaseType = test;
```

The issue is that covariance of field 'f' is incorrectly ignored when used beside the destructured type Mixin in the definition of BaseType. If the destructured Mixin statement is removed in BaseType, covariance of field 'f' works properly.

**Comment by SamChou19815** [comment]
Adding $ReadOnly helps. This is due to spread operator stripping all variance annotations
