### ISSUE TITLE
Flow complains when default parameters can be undefined and parameter defined with `?`

### ISSUE THREAD

**Issue by rumax** [facebook/flow#7199]
If default parameter can also have `undefined` value, `flow` complains with the error (see output below), but only if the parameter defined with `?` optional parameter. In case `| void' is used - no issues.

> If this is a bug, please try reproducing using https://flow.org/try/.

Yes, can be reproduces

```
/* @flow */

type Conf = {
  id?: number,
};
const conf: Conf = {
  id: -1,
}

const something = (id?: number = 5): number | void => {
  return id;
}
                       
const something2 = (id?: number = undefined): number | void => {
  return id;
}

const something3 = (id?: number = conf.id): number | void => {
  return id;
}
                        
const something4 = (id: number | void = conf.id): number | void => {
  return id;
}
                              
something();
something2();
something3();
something4();
```

As a result flow complains to `something2` and `something3`
```
    14: const something2 = (id?: number = undefined): number | void => {
                                          ^ undefined [1] is incompatible with number [2].
        References:
        [LIB] ..//static/v0.86.0/flowlib/core.js:13: declare var undefined: void;
                                                                            ^ [1]
        14: const something2 = (id?: number = undefined): number | void => {
                                     ^ [2]
    18: const something3 = (id?: number = conf.id): number | void => {
                                          ^ undefined [1] is incompatible with number [2].
        References:
        4:   id?: number,
                  ^ [1]
        18: const something3 = (id?: number = conf.id): number | void => {
                                     ^ [2]
```

**Comment by rumax** [comment]
Hi @lll000111, thanks for your reply. Indeed `null` and `undefined` can be confusing, and it really nice idea to define `export type Void<T> = void | T;` or type Null.

But in the described case there is no `null` values at all, I do work with `undefined` only. This has some benefits over `null`, like default value, etc. Moreover flow produces error `undefined [1] is incompatible with number [2]`, but number value is optional (`id?: number` which means it is a number or `undefined`).

Or maybe it should be better error reporting from flow? Like, for example, a message `default parameter cannot have type undefined`.

**Comment by lll000111** [comment]
Oh and about default value "undefined": well just don't do it? I mean, what's the point? It already is undefined if this is executed.

**Comment by lll000111** [comment]
It is NOT a bug. Read what I wrote. You don't do that, so the discussion is more and more useless. I explained your mistake in great detail.

**Comment by lll000111** [comment]
> JavaScript standard 

**THIS IS FLOW!!!**

**Comment by lll000111** [comment]
> JavaScript standard 

**THIS IS FLOW, it's about TYPES!!!**

Just _read_ what I wrote. Ridiculous!

Over and _out_ &mdash; I gave you far more than you need to understand and solve your problem, including an example (did you even look at it?!).
