### ISSUE TITLE
Union type won't work in array

### ISSUE THREAD

**Issue by JalilArfaoui** [facebook/flow#7201]
```js
/* @flow */

type Success = { success: true, value: boolean };
type Failed  = { success: false, error: string };

type Response = Success | Failed;

const failed: Failed = { success: false, error: 'error' }

const failures: Failed[] = [failed]

function handleResponse(response: Response) {
  // do stuff
}

handleResponse(failed) // Works

function handleResponses(responses: Response[]) {
  // do stuff
}

handleResponses(failures) // Does not work :-(

const list: Response[] = failures // Doest not work either :-(
```

Shouldn't `Failed[]` be considered as a subtype of `Response[]` ?

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKArgMal4DOlYAvGAN5iVkXUBcYGATsXgDRgAbgEMYfTgCM4cGHhEA7MAF8A3JlwEAYiICWcgCZg6jZqyqVOUMZQFg83bnG6dKPXQoDmK9RvxgAJSocOAVbExJyCzAAHzAdfTwDX1JQtzBrRINOBMMTJhYojgybOwcnFzAAcnLnKpV0VLCMEv1ibiocvUMAbQBdEx7Mwz70KGIFUgxdULAAC0UDOSDKELC8AAoO1bS8ThW12wBKRlRjYGAwAzhmDGIoKFRldAWFJbwD3Y3hpJOLsAA6s4ANaUMYTKYzJSvd6fdaULbBXaWQJI9b9E4MM5gf7XW73R7PVAw5Zo2wI4btKh-S4AETgVDACjgLQQILA7AAtBtGmkWjBdG59mS8P0TJTtji6Qz0szWey8LoMHMHBzuUA

**Comment by alexandersorokin** [comment]
No.  Failed[] is not subtype of Response[].
But $ReadOnlyArray<Failed> is subtype of $ReadOnlyArray<Response>

**Comment by JalilArfaoui** [comment]
Oh, yes of course !

I never mutate anything, so I'm not used to consider it ;-)

It works great with  `$ReadOnlyArray`, thanks !

Here is fixed example in case anyone has the issue: 

```js
/* @flow */

type Success = { success: true, value: boolean };
type Failed  = { success: false, error: string };

type Response = Success | Failed;

const failed: Failed = { success: false, error: 'error' }

const failures: Failed[] = [failed]

function handleResponse(response: Response) {
  // do stuff
}

handleResponse(failed) // Works

function handleResponses(responses: $ReadOnlyArray<Response>) {
  // do stuff
}

handleResponses(failures) // OK if not mutated inside function !

const list: $ReadOnlyArray<Response> = failures // OK if readonly !
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKArgMal4DOlYAvGAN5iVkXUBcYGATsXgDRgAbgEMYfTgCM4cGHhEA7MAF8A3JlwEAYiICWcgCZg6jZqyqVOUMZQFg83bnG6dKPXQoDmK9RvxgAJSocOAVbExJyCzAAHzAdfTwDX1JQtzBrRINOBMMTJhYojgybOwcnFzAAcnLnKpV0VLCMEv1ibiocvUMAbQBdEx7Mwz70KGIFUgxdULAAC0UDOSDKELC8AAoO1bS8ThW12wBKRlRjYGAwAzhmDGIoKFRldAWFJbwD3Y3hpJOLsAA6s4ANaUMYTKYzJSvd6fdaULbBXaWMAAEiCIgMAHkFDAsABBRwiLAAHjhtgAfCcGGcwP9rrd7o9nqgYcskfDvt12lQ-pcsQBpMC6KBgBRwFoAW2IGBEGCSwrCugMBHGk2mswAhI00i0YLo3Jx0fJsbiCUTSeS8BSTMMeTR-oLhaKOpjQniwJqgA
