### ISSUE TITLE
Flow doesn't recognize null check on assignment expression.

### ISSUE THREAD

**Issue by cakoose** [facebook/flow#7202]
```
declare function readNumber(): number | null;
declare function printNumber(n: number): void;

function f1() {
  let n;
  while ((n = readNumber()) !== null) {
    printNumber(n);  // <-- false positive
  }
}

function f2() {
  let n = readNumber();
  for (let n = readNumber(); n !== null; n = readNumber()) {
    printNumber(n);  // <-- ok
  } 
}
```

[Error from flow.org/try](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXzimADlkBbAIxBgAoBKALnlXKpngB9nkIIBuAFChIsBCnTY88AA4wsqDKUrUaqJi2UxG8AG44swQQPGZc+RAEZ68AN4D48CCAzNBDgO4ALLE-g1V8AC8BCBESmz0dPAAhIHBLLxRdg4OsvKKrCqodHwOAPR58AA8ALQlSFAQAM4I0jhVWNg6IPbwAL4CHcZoplKIAEzWyY7OzEEhYZm0Oa2IOOw0Ti74wYQkU-S5+LHxPPxjq6HrmpG2ralyCuFZOfmFpeU4ANatbfCdQA)
```
7:     printNumber(n);
                   ^ Cannot call `printNumber` with `n` bound to `n` because null [1] is incompatible with number [2].
  References:
  1: declare function readNumber(): number | null;
                                             ^ [1]
  2: declare function printNumber(n: number): void;
                                     ^ [2]
```

**Comment by tonthanhhung** [comment]
Could be different issue, but Flow also don't understand null check on this 
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AVQM5YBOAKplgIygC8oA3oqKAJAB2AhgLZYBco+KIgEtWAcwA0iZgBMskdgFdoKAEqxovUAH5WCzgCNiiAL7J02PIVLkATDXqMWHbjwHCxkmXMXK1GvroGRqbIwABUAMLshKAUfABiAIIAkgAyAKIAIqBhwIgAxrCsAqAKVjwExGTYVLQMTM6aAESJWKxY7KygGLD4CsQ4KLBEQ0T8WNJNkkyy8kqq6ry60NAmoZHRODZ8AOoA8ioA0gDKpoXFKKVW9vWgjXwtbR1dPX0DoKOj45PToLM+C38y1WxlyyEQIFAJAAFkJ8HclNBQPloVh8gBrUBwu6wS7wYbokSiUCQYbIzaxRBCSCgAAUZWIADp-vM-FgAJQMZjnEoM0iwY7sABuvEq1mwdlofLWyCAA

**Comment by cakoose** [comment]
@tonthanhhung: I don't know Flow internals, but I think your issue is worth filing separately.  Maybe with a title like "type refinement on field doesn't apply to containing object".

**Comment by patrikniebur** [comment]
I have an issue with similar null check. It works with simple `message !== null && console.log(message.title)` but fails when I have null check in variable like:
```
const isMessageAvailable = message !== null;
return isMessageAvailable && message.title;
```

[Flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoKBXAdgYwC4CWcWYA5gKZ4Cy5AzrQIYUAUAtnYxWALxhYYwYASjABvVAEgATpQxSS7ek3IBuVAF9U6bPiIkZDfAGE4rAA7FyWPAHUCeABZwMeAKJSpcKWw7KR4iRxiWjwwMxgGLBolLl4Kal8WRU5yITUwMFQMiWBgMCCsELACWmiUgEEANwYCCIAjGHIeMABCFvDIsuV0zOyZPDkSZjaOqMSmgDIJsAADAB5aM0iAPgASUVGuigA6QjxG9TngRZWZtI0tbVxCYjADY1MLLCs8HxjUsUkCos3x5vituQ3ilzhksmBAsFQiVAVUavVGs0RhExu8euDpLJ5GBmDDxnDagwGpNpvMTlg1hsUYDdvYDkdycszmp1EA)

**Comment by cakoose** [comment]
@patrikniebur: Your example requires more advanced refinement tracking, which I don't think Flow even attempts right now.  It should probably filed as a separate issue, maybe under the title "Flow doesn't propagate refinement information through variable".

**Comment by SamChou19815** [comment]
This is intentional to make loop analysis not requiring fixpoint
