### ISSUE TITLE
Nuclide website "five simple examples" returns 404

### ISSUE THREAD

**Issue by PinkyRabbit** [facebook/flow#7207]
Hello. I just want to start to use `flow`. On [nuclids website page](https://nuclide.io/docs/languages/flow/#installing-flow) I found the link [five simple examples](https://flow.org/docs/five-simple-examples.html), that open 404 error.

**Comment by lll000111** [comment]
You should open an issue with nuclid. They could poinit to https://github.com/facebook/flow/tree/master/examples
