### ISSUE TITLE
module.exports=any silently ruins type exports

### ISSUE THREAD

**Issue by gregwebs** [facebook/flow#721]
// export.js.js

``` javascript
/* @flow */

export type A = { a: string }
function acceptA(a: A): A { return a }

// always fails as expected
// acceptMethod(2)

// works as expected when exporting empty object
// module.exports = {};

// silently ruins type exports
module.exports = ({} : any);
```

import.js

``` javascript
/* @flow */

import {A} from './method.js'
function acceptA(a: A): A { return a }

// failure is dependent on exports of import.js not being any
acceptA(2)
```

I am on Flow 0.14. I saw the same behavior on 0.13

**Comment by mroch** [comment]
interesting. does `module.exports = ({}: any)` also repro? i expect it does, but just want to simplify the test case to eliminate a variable called `any` and also the use of `declare`

cc @jeffmo

**Comment by gregwebs** [comment]
yep, your version has the same result. I updated the description.

**Comment by gregwebs** [comment]
want to give this a bug label?

**Comment by TrySound** [comment]
Closing in favour of https://github.com/facebook/flow/issues/7444
