### ISSUE TITLE
 Cannot spread same exact immutable types: null or undefined [1] is incompatible with string [2].

### ISSUE THREAD

**Issue by villesau** [facebook/flow#7210]
[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeAPqANSQEBcoA-AM4oBOAlgHYDmo5AXwDciAMawurUCixSSACgBGAQzYN8sAJTqCxAHyh5pULVgMA5KfMAaUADoHKtgM1CgA)

```
// @flow

type Foo = {| +foo: ?string |};
const test = (bar: Foo): Foo => ({ foo: 'foo', ...bar});
```

causes:

```
3: type Foo = {| +foo: ?string |};
                       ^ null or undefined [1] is incompatible with string [2].
References:
3: type Foo = {| +foo: ?string |};
                       ^ [1]
4: const test = (bar: Foo): Foo => ({ foo: 'foo', ...bar});
                                           ^ [2]
```

This is very strange and frustrating issue, I think there is no any scenario that would make the error valid.

The error location is also very odd: It's in the _type_, not in the usage. this makes suppressing the error pretty non-optimal.

If I don't spread, the problem disappears.

This happens with all Flow versions.

[Happens also without exactness or read-onlyness](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeokBAXKAPwDOKATgJYB2A5qAL4DciAY1htGoFFlEkAFACMAhkxr5YASiUFiAPlBTylWDQDk+wwBpQAOivym3FbyA)
[possibly undefined version works](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMVrKALygDeAPqANSQED8AXKAM4oBOAlgHYDmo5AXwDciAMawurUCixSSACgBGAQzZN8sAJTqCxAHyh5pULVhMA5KfMAaUADoHKtgM1CgA) Unfortunately this is not what our type really is :/

**Comment by Gisleburt** [comment]
I'm suffering the same problem. This appears to have been a long standing bug in flow. See #5243

**Comment by nmote** [comment]
This no longer errors on master
