### ISSUE TITLE
Refining string literals doesnt work with Generics

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#7212]
### [Flow Try](https://flow.org/try/#0C4TwDgpgBAKuEGcoF4oHICGAzYEBOaUAPuhAG74hoDcAULVgK4B2AxsAJYD2zUEAHhgC2YADYQAPAGoYALljwEAPgAUoSPJgBKKAG9aASA5Yoa+CmSpMOfGh36ojqAdpOoAX1rugA)

Looks like this issue was introduced in `v0.84.0`

It's all great and good that you don't just refine to `empty` anymore but making it impossible ot even use the variable **in any way** pretty much makes it useless.

In this case it actually appears to refine and work perfectly in `0.83.0` as it definitely refines it to the string literal `'after'` 

So at this time you can no longer use unions with literals.

---

**Note** In my case I do require the generic as it is utilized to further refine the types that are composed within.

Would normally take some time to go and find and possibly submit PR but based on all my PR's being ignored not going to put in the effort for now. :-D

**Comment by jbrown215** [comment]
@dsainati1 this might be related to the work you did with refinements on enums?

**Comment by bradennapier** [comment]
@dsainati1 @jbrown215 

By the way, another example of where this is an issue was reported by my peer  I just realized although it isnt using generics so it appears you are right - refining of enums is what is broken!

https://github.com/facebook/flow/issues/7194

[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzAZwC4CcCWBjVYTABQxwwYAIgKZSYB2lYlAHgIa5ioCeADpQHQDCXXmAAqlNKJ4MAvGADeAHzABqZHAC2lVAAs6AcwBcYAEZw4MSi1phFAXwDcJMgEFaAEzBQArrVyY4WmQwdG1vdFoDFBYtRlZ2YX5BbEC0L1oARjA5AAoASmNxSWlsgD4wHPkUTW09WiMOdG8GOzynFKC8KFoAJmyKgrEJVCkRGXLK6q1dA2MoFhhkFrbnMABZFgBrBlDkbxg8ExYlz0CwDvdMVACbAFpTOF1G5uB5xYYETBgYELCI6NizDYeESAj4hA6aV2+zwcgwzTAAH50hl8mA5r18k5CKQxAAJACSAGUwMTSWsAAoAeQASqIXAA5UTGaEHPjqaZ1fTZGRwpofL4-KBwdDYBiJDhwMAAIjMFisNmU1k40ohqTwADcFgi5KzUOyajN6jy+QjkQByeGUc3osDmt5Lc3Y3EAYQWPzOQPYcBMACtKAkSphgph9LQRZRPCYAyxvEswFdzcFlUjEWrOigdHB9u4AGIsL79PV8cOoACiTGD13qFPQcF46C4zuAkPlfHg+hyyCzOfzXzyQA)

**Comment by dsainati1** [comment]
The change I made with refinements essentially requires that when you refine a value out of a type, the value being removed is part of the type in the first place (under the types-as-sets-of-values interpretation). The first example you linked doesn't work because some `T` that is a subtype of `Types` might not contain the value `"after"`, so it doesn't make sense to refine it out. In general I would argue that a generic that is a subtype of a union is not a useful type since you have no information about which elements of the union are included on any given instantiation of the generic.

Regarding your second example,  that does seem to be incorrect. I will look into it.

**Comment by bradennapier** [comment]
@dsainati1 I mus t have a complete misunderstanding of generics then.  I would greatly appreciate if you could help me out here.  How would I go about using a value in multiple places and have Flow know its going to be the same value throughout the call.

Essentially in my mind if I use a generic and send it around Flow should be able to know that value will be the same as it is passed around.

For example something like

```
async function getRecordsHigherThanID<+T: 'Deposit' | 'Withdrawal', +M: DB$TableByName<T>>(tableID: T) {
    const models: Array<M> = await getModels(tableID); // truncated...
}
```

In this case I would expect that flow would see that T will be one or the other  'Deposit' or 'Withdrawal' - then when I use it to build other types it should know to sepate it as 

```
Array<DB$TableByName<'Deposit'>> | Array<DB$TableByName<'Withdrawal'>>
```

However it does appear to remain as

```
Array<DB$TableByName<'Deposit' | 'Withdrawal'>>
```

**Comment by bradennapier** [comment]
Ok so maybe it wasn't clear from the example what im expecting here.  

### [Try Flow](https://flow.org/try/#0FAFwngDgpgBAIgIQCoEMBGAbKBnGBeGAcjiggHtsBLEQmAHyIHVqALAEwCcUB3FDWhoQCCAYxFkArgDsaAbmDBxU7CBgh0WXAQDyaAFZQRIAHQAzDlCgAvKAAoA3sBgxR46SABcMANoBGALoANE7wpBTUXt4gHBJQQSHMIOxcvBhehInJPHyEwQC+AJQKoJCwALJkbFAYADwA1EgAknBeiKiYOAB8+DAAJABKUChs2lIYYDX2dMAAkKaUUmxCGBi2BV69AKJYALZQMkilNeDQZKZqGjiBME1wncB0efeKZMqqbGg9ugZGZhbWdkczh2lWq9VurWQl2wnVs6g6zS8t3WMAqVVqt26QOcMAsIAkHCkMGxMzmCyWKzWxNxUHxhIuHWwUUuzX8MDysw5zg5hQUpmkRkorxgAHNaYNxBw2NgABKUEUsKAcJAsFBSZrg9IkchUGj0JisTjZfiwkLwrBI4AFYkhPEEokfYwg9Fwy5FDnAKAAD3IHFU-KkguFYpA2vCIGwVOxShUNOwEgwqgIIYlZClsvliuVqvVcFsxDCusIBTM5OWqwK8mcdvpFnjieAHu9vv9ApAQqJIcyRtSket0desbrCaTovFhjT0rlCqVKrVzXz3ZSORL80W5bWVZpdKJw8T8jyQA)

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
