### ISSUE TITLE
Trying to access undefined object property after an if fails

### ISSUE THREAD

**Issue by roine** [facebook/flow#7216]
[Working sample][working]
```flow
if (!!(obj && obj.o && obj.o != ''))
  return obj.o
```
[Broken sample][broken]
```flow
if (hasO(obj)) 
   return obj.o
...
function hasO(obj:{g: number, o?: string}):boolean {
	return !!(obj && obj.o && obj.o != '') 
}
```

The `if` seems to be ignored when using a function.

[working]: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoGBTALmOAjAKwC4wBvAcxIDsBXAWzwwCcAaXAfhIGcsmBLKuQC+YALxlKAFiGpUUGlQDGWPnCpgocOAAoAHiXa0GzAJTdeA8mVRgwfKGG0BCJ9vwEwAMk+5CAOjgvH3cAsCdxAHIIkxNrW1smbBomdRC4AG4bMBkEpJSwACIAEwwoAEMaGBwefkECzJlZeSUVNTAACzKuAHk3QiIKanpGVg5zWuEzPC1MMvVSVABIRKxk9Rc+j29fAlDttLDI6LBUISA
[broken]: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoGBTALmOAjAKwC4wBvAcxIDsBXAWzwwCcAaXAfhIGcsmBLKuQC+YALxlKAFiGpUUGlQDGWPnCpgocOAAoAHiXa0GzAJTdeA8mVRgwfKGG0ALAIZcA8tvwETJ67dsmbBomdW8AOjgAbhswGUDg0LAAIgATDCgXGhgcHn5BZJiZWXklFTUwVw8vQiIKanpGVg5zfOEzPC1MF3VSVABIIKwQ9QBCUZqCMAAyadxCSJm5iLgwUfEAcg2-VCEgA

**Comment by jbrown215** [comment]
We don't propagate refinements through functions :( Our refinement analysis is very conservative by design because supporting a more complete analysis would be:
1. Expensive in terms of time/space
2. Very hard to make sound
