### ISSUE TITLE
Missing Node assert strict mode: require('assert').strict

### ISSUE THREAD

**Issue by crccheck** [facebook/flow#7217]
In Node 10 and 8.13.0 you can do (abridged for clarity):
```
$ node
> const assert = require('assert').strict
> assert.equal(1, '1')
{ [AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 1
+ '1'] }
> assert.strictEqual(1, '1')
{ [AssertionError [ERR_ASSERTION]: Input A expected to strictly equal input B:
+ expected - actual

- 1
+ '1'] }
```

but the current definition is missing it: https://github.com/facebook/flow/blob/a2ed5108713c75bf7fbb2d3bbeb2c1281290609e/lib/node.js#L2057

docs: https://nodejs.org/docs/latest-v10.x/api/assert.html#assert_strict_mode

Since `assert.strict` has the same type signatures as `assert`, I have an idea of how to do it, but I'm sure it's not the best way.

**Comment by jbrown215** [comment]
Feel free to put up a PR
