### ISSUE TITLE
An exported infered return type of reduce function is broken since version 0.86

### ISSUE THREAD

**Issue by alexandersorokin** [facebook/flow#7227]
The following code is type-checked in previous version of Flow and is not type-checked in Flow since 0.86.

Bug is only reproduced when code is split in several files.

First file:
```
const createObjectByFieldNamesArray = (fieldNames: $ReadOnlyArray<*>) => fieldNames.reduce((obj, name) => {
  obj[name] = undefined;
  return obj;
}, {});

export type CreateObjectTypeByFieldNamesArray<FieldNames: $ReadOnlyArray<*>> =
  $ObjMap<
    $Call<typeof createObjectByFieldNamesArray, FieldNames>,
    () => mixed,
  >;
```

Second file:
```
import type {CreateObjectTypeByFieldNamesArray} from './CreateObjectTypeByFieldNamesArray';

declare var abcObj: CreateObjectTypeByFieldNamesArray<['a', 'b', 'c']>;

// OK in flow <= 0.85
// ERROR in flow >= 0.86
(abcObj: {a: mixed, b: mixed, c: mixed});

```

It is still type-checked when all code is merged in single file in any Flow version.

As a result Try Flow does not show any difference when you change it version: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgGIEkAyAomIGiEAjOgMZwB2AzgC5iUBOApgIYNsDyARgCs2lBgCEAntgCWbGABMAchwC2bOgEEWLDuLABeMAAooM+UtV0AXGAAkAJU5yeNGOM3bxAHhAA+AJT6PmAmsooqagB07HIArpRshoZwggA0YDThAXpBAN6oYGDJAgDaGaoAuvpgMTRybCY0bHIA3Plg7AwxLDSFgq0Avmk5-X6tqGwAHgAOcCxMDOJTbGAAwuxcvILCDAAqi2wS0qHmau46nkdm4Va2DhxOLm5a575Bem02-AIAshxTnm0CjYVhwYDBPAslnAoMx1twvttDqYwhYzuI0pcUWofClAUYskFlFIJk1cQUfGNMDgCMQSAAmQF1SgwDjsMAAN1ZYA4fEoX2sa048K2Ij2SyRx2uaM8xQA5BxZWlZXxFWBZZRZeUKehDDy+YJrDkONYiSS5Gk+CbiaTmFazSNWkA

This described above type "CreateObjectTypeByFieldNamesArray" is important because it used in Pick utility type definition:

```
export type Pick<Source: $Subtype<{}>, FieldNames: $ReadOnlyArray<$Keys<Source>>> =
  $ObjMapi<
    CreateObjectByFieldNamesArray<FieldNames>,
    <FieldName>(fieldName: FieldName) => $ElementType<Source, FieldName>,
  >;

declare var abObj: Pick<{a: number, b: number, c: number}, ['a', 'b']>;

(abObj: {a: number, b: number}); // Should be OK
(abObj: {a: string, b: string}); // Should be ERROR
(abObj: {a: number, b: number, c: number}); // Should be ERROR
```

**Comment by alexandersorokin** [comment]
Are there other ways to define `Pick` type?

If there are no other ways then I will not be able to upgrade Flow to 0.86 or above and eventually I will be forced to migrate from it.

**Comment by SamChou19815** [comment]
Flow will now require full annotation on exports since types first
