### ISSUE TITLE
Flow unable to understand trivial variable equivalence when determining refinements

### ISSUE THREAD

**Issue by rkrv** [facebook/flow#7228]
I ran into a issue where flow will not recognise a type of a copied variable for conditional rendering in React:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50q4A7AZ2IAVMgA9iAXjAAKAN5gAFoSwwwAXwBcYeUpVbB+DLwDm6gJRgJAPkXKYXVFACuvGhj5gA6vgo4cZfDlbFXUtHTsAfn1CQxNzbVQwMB4BYgUKfgAJO0tg+0SwVkInfF5FDOyQgDIqsAAeEXE8iVldGDUwYCsuNVQgA

```js
const Text = ({ html }: { html: string }) => html;

function Wrapper({ html }: { html?: string }) {
  const hasHtml = html;
  return hasHtml && <Text html={html} />;
}
```

Funny enough, this will work:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50q4A7AZ2IAVMgA9iAXjAAKAN5gAFoSwwwAXwBcYeUpVbB+DLwDm6gJRgJAPkXKYXVFACuvGhj5gA6vgo4cZfDlbFXUtHTsAfn1CQxNzbVQwMGBgMB4BYgUKfgAJO0tg+0SwVkInfF5CsAAyarAAHhFxQolZXRg1ZKsuNVQgA

```js
const Text = ({ html }: { html: string }) => html;

function Wrapper({ html }: { html?: string }) {
  return html && <Text html={html} />;
}
```

Am I missing something?

**Comment by TrySound** [comment]
Refinements are not saved with new variables. It's expected behaviour. Just use already refined variable.

**Comment by rkrv** [comment]
> Just use already refined variable.

That becomes complicated in [larger scenarios](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50q4A7AZ2IAVMgA9iAXjAAKAN5gAFoSwwANIsoATDLwDmYAL4AuMPKUqTg-Dt3qFWm5cLW9hgJRgJAPhmowYAB5tADcvP39TewptPQNw-1lzGDj-AOAQsLcuVCgAV14aDD4wAHV8ChwcMnw5RWU1DWibQxMzeoB+JxdbRpjdTrArZoMPWXCeAWIFCn4AYT5CMl5JOpUwADJ13psuf1ZCXPxeRRn55aXiTcCRcVWYCUT6g229B6i+5+AvLjigA), like:

```js
const Text = ({ html, heading }: { html: string, heading: string }) => (
  <div>
    {heading}
    {html}
  </div>
);

function Wrapper({ html, heading }: { html?: string, heading?: string }) {
  const hasContent = html && heading;
  return hasContent && <Text html={html} heading={heading} />;
}
```

**Comment by rkrv** [comment]
Thanks for your quick reply, @jbrown215! I'd be interested in helping with testing when somebody picks up this task.

**Comment by villesau** [comment]
@rkrv I got very definite answer to same problem here: https://github.com/facebook/flow/issues/6146#issuecomment-439139904

This has been reported many times already. I think that it's because the restriction is not well documented and the use case is pretty idiomatic JS. If you know the restriction, it's very easy to avoid it and still being able write clean code. Just avoid destructing objects that has this kind of "cross dependencies"
