### ISSUE TITLE
Null value ternary check with value_if_true expression having multiple function calls

### ISSUE THREAD

**Issue by kkirby** [facebook/flow#723]
Hello,

I believe I have found a bug.

If you have a possibly null value and check its value with a ternary, then the first call to a function property of the value will pass, but the second call will fail. It's a little hard to describe all the circumstances so I've written up some examples below.

```javascript
 1  /* @flow */
 2  class Abc {
 3      prop: ?{
 4          a: Array<Abc>,
 5          b: Array<Abc>
 6      };
 7      
 8      // Passes
 9      a(): ?{a:Array<Abc>,b:Array<Abc>} {
10          return this.prop ? {
11              a: this.prop.a,
12              b: this.prop.b
13          } : null;
14      }
15      
16      // Passes
17      b(): ?{a:number,b:number} {
18          return this.prop ? {
19              a: this.prop.a.length,
20              b: this.prop.b.length
21          } : null;
22      }
23      
24      // Fails
25      c(): ?{a:number,b:number} {
26          return this.prop ? {
27              a: this.prop.a.indexOf(new Abc),  // <-- This passes
28              b: this.prop.b.indexOf(new Abc)   // <-- This fails
29                                                //     test.js:28:16,26: property b
30                                                //     Property cannot be accessed on possibly null value
31                                                //     test.js:3:12,6:5: null
32          } : null;
33      }
34      
35      // Fails
36      d(): ?{a:number,b:number} {
37          return this.prop ? {
38              a: this.prop.a.indexOf(new Abc), // <-- This passes
39              b: this.prop.b.length            // <-- This Fails
40                                               //     test.js:39:16,26: property b
41                                               //     Property cannot be accessed on possibly null value
42                                               //     test.js:3:12,6:5: null
43          } : null;
44      }
45      
46      // Passes
47      e(): ?{a:number,b:number} {
48          return this.prop ? {
49              a: this.prop.a.length,
50              b: this.prop.b.indexOf(new Abc)
51          } : null;
52      }
53  }
```

Here is the full error output:

	test.js:28:16,26: property b
	Property cannot be accessed on possibly null value
	test.js:3:12,6:5: null
	Error path:
	test.js:3:12,6:5: NullT [null]
	test.js:28:16,26: ~> GetT [property b] comes from
	test.js:3:12,6:5: . MaybeT [?object type]
	test.js:28:16,26: . ~> GetT [property b] comes from
	test.js:28:16,19: . . InstanceT [Abc]
	test.js:28:16,24: . . ~> GetT [property prop]

	test.js:28:16,26: property b
	Property cannot be accessed on possibly undefined value
	test.js:3:12,6:5: undefined
	Error path:
	test.js:3:12,6:5: VoidT [undefined]
	test.js:28:16,26: ~> GetT [property b] comes from
	test.js:3:12,6:5: . MaybeT [?object type]
	test.js:28:16,26: . ~> GetT [property b] comes from
	test.js:28:16,19: . . InstanceT [Abc]
	test.js:28:16,24: . . ~> GetT [property prop]

	test.js:39:16,26: property b
	Property cannot be accessed on possibly null value
	test.js:3:12,6:5: null
	Error path:
	test.js:3:12,6:5: NullT [null]
	test.js:39:16,26: ~> GetT [property b] comes from
	test.js:3:12,6:5: . MaybeT [?object type]
	test.js:39:16,26: . ~> GetT [property b] comes from
	test.js:39:16,19: . . InstanceT [Abc]
	test.js:39:16,24: . . ~> GetT [property prop]

	test.js:39:16,26: property b
	Property cannot be accessed on possibly undefined value
	test.js:3:12,6:5: undefined
	Error path:
	test.js:3:12,6:5: VoidT [undefined]
	test.js:39:16,26: ~> GetT [property b] comes from
	test.js:3:12,6:5: . MaybeT [?object type]
	test.js:39:16,26: . ~> GetT [property b] comes from
	test.js:39:16,19: . . InstanceT [Abc]
	test.js:39:16,24: . . ~> GetT [property prop]

And finally the code without line numbers:

```javascript
/* @flow */
class Abc {
    prop: ?{
        a: Array<Abc>,
        b: Array<Abc>
    };
    
    // Passes
    a(): ?{a:Array<Abc>,b:Array<Abc>} {
        return this.prop ? {
            a: this.prop.a,
            b: this.prop.b
        } : null;
    }
    
    // Passes
    b(): ?{a:number,b:number} {
        return this.prop ? {
            a: this.prop.a.length,
            b: this.prop.b.length
        } : null;
    }
    
    // Fails
    c(): ?{a:number,b:number} {
        return this.prop ? {
            a: this.prop.a.indexOf(new Abc),  // <-- This passes
            b: this.prop.b.indexOf(new Abc)   // <-- This fails
                                              //     test.js:28:16,26: property b
                                              //     Property cannot be accessed on possibly null value
                                              //     test.js:3:12,6:5: null
        } : null;
    }
    
    // Fails
    d(): ?{a:number,b:number} {
        return this.prop ? {
            a: this.prop.a.indexOf(new Abc), // <-- This passes
            b: this.prop.b.length            // <-- This Fails
                                             //     test.js:39:16,26: property b
                                             //     Property cannot be accessed on possibly null value
                                             //     test.js:3:12,6:5: null
        } : null;
    }
    
    // Passes
    e(): ?{a:number,b:number} {
        return this.prop ? {
            a: this.prop.a.length,
            b: this.prop.b.indexOf(new Abc)
        } : null;
    }
}
```

**Comment by samwgoldman** [comment]
Hi @kkirby. Thank you for writing up this very detailed issue report! Your details make it easy to see what is going on. I believe you are running into a [documented shortcoming](http://flowtype.org/docs/dynamic-type-tests.html#caveats) in dynamic type tests.

Hopefully the documentation will explain why Flow behaves as it does, and the provided workaround will help you push through. I want to be clear that Flow's errors in this case don't necessarily indicate a type error in your code, but allowing this code requires some analysis that Flow doesn't currently perform, so Flow is pessimistic.

As far as the workaround, what you need to do is pull off `this.prop` into a local variable, so Flow can know for sure that the function calls (`indexOf` in this case) don't change the value of property.

Please let me know if the documentation is unclear and feel free to reopen if you run into further complications. Thanks again!

**Comment by kkirby** [comment]
Ah, yeah, that'll do it. I appear to be having issues like this a lot. At any rate, thanks for your response, and sorry for filing a bug on a documented issue.

**Comment by samwgoldman** [comment]
Don't worry about opening an issue. I'm sorry that we have to close this without a better resolution. We are definitely interested in the mutation analysis that would help Flow accept this code, and we're already tracking that. Please continue to file issues—your feedback is appreciated!
