### ISSUE TITLE
$ReadOnlyArray<*> type should default to literals

### ISSUE THREAD

**Issue by iddan** [facebook/flow#7232]
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAGUBVASQBUiwAuMAEgCUBTAQwBMB5bGATwEEAToNa8APCAB8YALxgA2gHIAIgEtWAWxztcigDRhFAYRgBXAEa6DigBJtB+K4aIAHDs10BdANzp8vF2ZiU1VCOXoAURhmDWZsfAoA5jF-QLgoYnIqA2xTDXNmQUlfVGBgYgALOFMYdjA3XFxUAAoAIjVNbVxW2mDQgEoSssrq2rAoVlUYFtb+VroiEPxBoA)

```typescript
/* @flow */

const SUITS : $ReadOnlyArray<*> = ['Diamonds', 'Clubs', 'Hearts', 'Spades'];

type Suit = $ElementType<typeof SUITS, number>;

// Should pass
("Diamonds" : Suit);

// Should fail
("A": Suit);
```

**Comment by jbrown215** [comment]
`*` is deprecated, so we won't be working to improve it.
