### ISSUE TITLE
$NonMaybeType does not work inside $ObjMap

### ISSUE THREAD

**Issue by adamsmatthew** [facebook/flow#7234]
### The Issue

Unless I'm missing something (totally possible), it appears that `$NonMaybeType` cannot be applied using `$ObjMap`.

I would expect the following to have an error, but it doesn't:

```
type MaybeObj = {|a?: number|};

type NonMaybeTypeFunc = <T>(param: T) => $NonMaybeType<T>;
type NotMaybeObj = $ObjMap<MaybeObj, NonMaybeTypeFunc>;

// $ExpectError
const foo: NotMaybeObj = {};
```

```
No errors!
```

[^ Try flow link.](https://flow.org/try/#0C4TwDgpgBAsghiARhA8ogVlAvFA3gHzgH4AuKAOwFcBbZAJ3wF8BuAKFdEigDkB7c+EggAVcBABilcgGNsUADzCAfAAowcOnGplhASmxKoAEj4CEyUZEVK2naH2CDkaTDiMv4YeU9QYANDz8PpYSUtI27AD0kcYAogAekNLAsXR0vHSs0vwAzsBQAGa8vGQOPi5yuCxAA)

### Attempts To Narrow It Down

- It appears as if the `$NonMaybeType` simply isn't applied, since errors based on the type of the optional property are still found, e.g.:

```
type MaybeObj = {|a?: number|};

type NonMaybeTypeFunc = <T>(param: T) => $NonMaybeType<T>;
type NotMaybeObj = $ObjMap<MaybeObj, NonMaybeTypeFunc>;

// $ExpectError
const bar: NotMaybeObj = {a: 'hi'};
```

```
7: const bar: NotMaybeObj = {a: 'hi'};
                                ^ Cannot assign object literal to `bar` because string [1] is incompatible with number [2] in property `a`.
References:
7: const bar: NotMaybeObj = {a: 'hi'};
                                ^ [1]
1: type MaybeObj = {|a?: number|};
                         ^ [2]
```

[^ Try flow link.](https://flow.org/try/#0C4TwDgpgBAsghiARhA8ogVlAvFA3gHzgH4AuKAOwFcBbZAJ3wF8BuAKFdEigDkB7c+EggAVcBABilcgGNsUADzCAfAAowcOnGplhASmxKoAEj4CEyUZEVK2naH2CDkaTDiMv4YeU9QYANDz8PpYSUtI27AD0kcYAogAekNLAsXR0vHSs0vwAzsBQiBpkDj4ucrhwZADkABYAllUsrEA)

- Applying `$NonMaybeType` to the object properties without `$ObjMap` gives the expected error:

```
type MaybeObj = {|a?: number|};

type NotMaybeObj = {a: $NonMaybeType<$PropertyType<MaybeObj, 'a'>>}

// $ExpectError
const foo: NotMaybeObj = {};
```

```
6: const foo: NotMaybeObj = {};
                            ^ Cannot assign object literal to `foo` because property `a` is missing in object literal [1] but exists in `NotMaybeObj` [2].
References:
6: const foo: NotMaybeObj = {};
                            ^ [1]
6: const foo: NotMaybeObj = {};
              ^ [2]
```

[^ Try flow link.](https://flow.org/try/#0C4TwDgpgBAsghiARhA8ogVlAvFA3gHzgH4AuKAOwFcBbZAJ3wF8BuAKFdEigDkB7YeElQZseOGQAkfcoOQAVcBAA8EgAp1ekOqAWQls4egA0UAORxTAPkuN2AejtQJAUQAekAMbBndDXVYevOQAzsBQAGa8vGR8AgjIaJg4uCysQA)

- It doesn't seem like using `$NonMaybeType` in a function is the issue:

```
type NonMaybeTypeFunc = <T>(param: T) => $NonMaybeType<T>;

let makeNonMaybe: NonMaybeTypeFunc;
    
function context(v: ?number) {
  const num: number = makeNonMaybe(v);
}
```

```
No errors!
```

[^ Try flow link.](https://flow.org/try/#0C4TwDgpgBAcg9gOwLIEMQCMIBVwQGICuCAxlALxQA8WAfABRgoBOKAtgFxRYCU5NUAEnjI0mHJGo0A3ACgZAGwjAorFAGsIw1Bgicto7LkIlZUM1BkAzIsWABLRFGKJgEAB7A6AN04B+BASsmEy8AN4yZs4IAM7KARxQ8cHkKuqaiNqY3tyyAL4yQA)

**Comment by alexandersorokin** [comment]
Optional property information is not belong to property type but belong to an object at whole. Roughly speaking you may treat `{|a?: number|}` as `{||} | {|a:number|}`.

Actually you can replace property type using object $ObjMap and $NonMaybeType. See example:
```
type MaybeObj = {|a: ?number|}; // Now type '?number' is equals to 'number | null | undefined'. So  $NonMaybeType affect it.

type NonMaybeTypeFunc = <T>(param: T) => $NonMaybeType<T>;
type NotMaybeObj = $ObjMap<MaybeObj, NonMaybeTypeFunc>;

// $ExpectError
const foo: NotMaybeObj = {};
```
https://flow.org/try/#0C4TwDgpgBAsghiARhA8ogVlAvFA3gHzgC4oB+AOwFcBbZAJ3wF8BuAKFdEigDkB7c+EggAVcBABilcgGNsUADzCAfAAowcOnGolhASmxKoAEj4CEyUZEVK2naH2CDkaTDiMv4YeU9QYANDz8PpYSUtI27AD0kcYAogAekNLAsXR0vHSs0vwAzsBQAGa8vCQOPi5yuCxAA

If you use $ObjMap with `{|a?: number|}` (equals `{|a: number|} | {||}`). In that case `$ObjMap<{|a?: number|}, NonMaybeTypeFunc>` equals `$ObjMap<{|a: number|}, NonMaybeTypeFunc> | $ObjMap<{||}, NonMaybeTypeFunc>`. In turn it equals `{|a: number|} | {||}`. You can see that object type is not changed at all after $ObjMap transformation.

If you use $ObjMap with `{|a?: ?number|}`. In that case `$ObjMap<{|a?: ?number|}, NonMaybeTypeFunc>` equals `$ObjMap<{|a: ?number|}, NonMaybeTypeFunc> | $ObjMap<{||}, NonMaybeTypeFunc>`. In turn it equals `{|a: number|} | {||}>`. So null value is not assignable to property `a` after $ObjMap transformation.

Be aware that Maybe type and optional type are different topics. Optional types are additions for object and functions definitions that can be used only there and affect objects and functions itself. Maybe types can be used anywhere in place of any other type and affect wrapped type.

**Comment by SamChou19815** [comment]
This can now be done through `Required`
