### ISSUE TITLE
Return type of Subclass method should allow the return of an extended superclass object

### ISSUE THREAD

**Issue by philiiiiiipp** [facebook/flow#7236]
I am struggling to find the correct description for my question, but I am essentially trying to understand why I cannot have a subclass method return a more detailed version of the parent classes method.

Here is an example of what I am trying to do:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCAhgM54AquBAvGAN6phjEBcYpGATgJYB2AczCoAvumz4wAUQAeGPHwAmeRSXJVJdRswB0etZWoAaJmABG7PgFcAtmbxdR6AMYwypMAEEGpxXAAUAJTsBhoE2sxceBhWXHwMLOwA5AAWxDDwSWAiANzCzGJiqK7uRGB4cgqKHt4RfkHssvJKKqHUPsxgUTFxCWxgqemZRubsAIwATADM2XmmhUA

This behaviour is working in javascript, is this a bug in flowtype or should I write my type definitions differently?

**Comment by yury** [comment]
Use exact

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCAhgM54AquBAvGAN6phjEBcYpGATgJYB2AczCoAvumz4wAUQAeGPHwAmeRSXJVJdRswB0egCSziAYwwAeNZWoA+ADRMwAI3Z8ArgFtHeLqPTGYZKRgAIIMDopwABQAlOyWGgTazFx4GK5cfAws7ADkABbEMPA5YCIA3MLMYmKo-oFEYHhyCopBoUkRMeyy8koq8dRhzGApaRlZbGD5hcW2TuwAjABMAMylFQ7VQA

**Comment by philiiiiiipp** [comment]
Ahh, right. I actually had both of the types in ```||``` like so 

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBCAhgM54AquBAvGAN4A+qYYxAXGKRgE4CWAOwDmYVIwC+6bPjABRAB4Y8AgCZ4VJclRl0mLMADojmytQA0+gEacBAVwC2lvDzGTUAYxhlSYAIIN9FTgACgBKThNtAnp9MB48DFseAQY2TgByAAtiGHh0sHEAblFWSTdPbyIwPEVlFR9-GNYgsM4FJVV1SOoA1jiEpJT6NLAsnLyzMGswAEYAJgBmAuL9MqA

Seems like it does not allow the base type to be exact then. Is there a way of saying that it returns ```BaseType``` and all extensions of it without opening the base type up?

**Comment by philiiiiiipp** [comment]
I suppose in other way is there the inverse of $Exact somewhere hidden?

**Comment by philiiiiiipp** [comment]
Ok I learned how to do it, leaving this here for future reference:

```
/* @flow */

type AType = {|
  a: string 
|}

type BType = {|
  ...AType,
  b: number
|}

type CType = {|
  ...BType,
  e: number
|}

class A {
  do(): { ...AType } {
   return ({ a: 'hallo' }: AType) ; 
  }
}

class B extends A {
  do(): { ...BType } {
   return { a: 'hallo', b: 123 }; 
  }
}

class C extends B {
  do(): { ...CType } {
   return { a: 'hallo', b: 123, e: 123 }; 
  }
}
```
