### ISSUE TITLE
Refinements are too complex

### ISSUE THREAD

**Issue by nickshanks** [facebook/flow#7237]
I am trying to use refinements to prove at runtime that a blob of JSON is a valid instance of a type, so that I can return that type instead of an 'any'. Please [see my example](https://flow.org/try/#0C4TwDgpgBAKgFgSwHYHMoF4oG8A+AoKKAawhAC4oBnYAJ2RQBo8cBfAbjz1EigClKA9kgx9BSAAp0AtgmAIAbtByihAQRo0AhiCjL+QgPIAjAFYQAxsA7do+idNkLomeQIQATXVCQBXADZ+XtR0qF6+UkYQNF5GAgJ+EJpI1uC2YupaOpgZ2gA8dgB8KTx2xmaWIgAkAMpwmpC5WFAA2sH0ALoUdlAsRZzmQtRQKBDA8PQiABQ+NH4AlBTjoegF2ARQA0hD7prAmhRty1AA5FgARCQgZ2Rn8pp+PhBnLMdsAPRvAGaj5nAAqrNqgIpBA4AIAO7TWZzDiETZDExiLpiERlCzAAB0nxoEAgAC8IJNeNUDAA5DFgTQ0SiEnZ7OYw9YIT5QSYIShLFCTRFCBnrQg44AzYQ85LrYBwGgQ7wQcFQACiGgENEmjPY-UGwCg7M5U1FyN5FFi8USwgApL8LERKBgCkzKKVTOjuWI5lAAGTu9ZoywYy6UF28jEJVASjDoTAARg9XsIPsx-sDSDmzQADO1w5hjpdjjHxakBCzRX7SJmTocUK8NVstezHeUtZgkwbk0a4gkklALXArTaVusAIQD0V5wg2QtQEcRrMCJ2WXOewdJ7U1pLmCATnIgRlAA).
I am running into two issues that don't seem to have solutions. Have I missed something? Perhaps this constitutes a feature request?

The first is that there are no refinements in Flow that assert only a given set of properties exist on an object. In the example linked above, the output of Object.keys() is compared against the known keys of type Thing. If this check passes, there should be no error "inexact X is incompatible with exact Y", since we know the object has those keys and only those keys. Though it would be even better if I could use $Keys<> somehow and not duplicate the names of each property.

The second issue is that the value type 'Json' in $Shape<{ [string]: Json }> for the property 'key' has already been refined to be a string (by typeof json.key === 'string'), but this refinement is being ignored, resulting in errors such as "boolean is incompatible with string in property 'key'". Boolean and the other types causing errors should have already been removed as a possible type for that property.

Possibly related tickets:
https://github.com/facebook/flow/issues/3041
https://github.com/facebook/flow/issues/4183
https://github.com/facebook/flow/issues/4825

**Comment by noppa** [comment]
Personally, I'm doing typesafe JSON parsing like this: [example](https://flow.org/try/#0C4TwDgpgBAKgFgSwHYHMoF4oG8A+AoKKAawhAC4oBnYAJ2RQBo8cBfAbjz1EigClKA9kgx9BSAAp0AtgmAIAbtByihAQRo0AhiCjL+QgPIAjAFYQAxsA7do+idNkLomeQIQATXVCQBXADZ+XtR0qF6+UkYQNF5GAgJ+EJpI1uC2YupaOpgZ2gA8dgB8KTx2xmaWIgAkAMpwmpC5WFAA2sH0ALoUdlAsRZzmQtRQKBDA8PQiABQ+NH4AlBTjoegF2ARQA0hD7prAmhRty1AA5FgARCQgZ2Rn8pp+PhBnLMdsAPRvAGaj5nAAqrNqgIpBA4AIAO7TWZzDiETZDExiLpiES8aoGAByADowJoaJQIJMdns5usaKMZsIsOtCJcKIihFAAGRMqA2ASfKAMpBYy4YdCYY6HFDHKAAfi5Yl5pCgFDufg8uwQQgAohoBDRJsdLsdSYQWHh2JxPj4kJZlcJ5Yq5Kr1ZqwDQBGADrR6HM1oRgHBHeDvBBfWrHZqAAYASSQVs8aMxUE+GqgDqdUVAUDOlSwibALDOwZhhrwQA).  
I know this does not exactly constitute to a solution for the issue - I'm sure those refinements could be useful elsewhere too - but might be useful to your specific use case anyway.

**Comment by vicapow** [comment]
Hi @nickshanks,

Thanks for your feedback. That said, it sounds like maybe there's a few issues going on here. Would you mind creating a separate ticket for each one? It also really helps consolidate and triage issues if you can simply them down to simple demos, with expected and actual behavior called out in the ticket.

As example, the first error in your try flow link is related to exact / inexact behavior that is working as expected. It's much easier to see this as a example:

````js
type O = {| key: string |};
const json: mixed = JSON.parse('{ "a": "a", "key": "key"}');
if (json && typeof json === 'object' && !Array.isArray(json)) {
   (json: O); // Error. json has an `a` property so we can cast to `O`
}
````
