### ISSUE TITLE
Generic type is not compatible with rest Array

### ISSUE THREAD

**Issue by piuccio** [facebook/flow#7239]
[Flow try](https://flow.org/try/#0PTAEBUAsFNQMwK4DsDGAXAlgeyaAJtHBktAM6gCGuF62uKATtBWlgwDSgZqgKlmgA5tBIMMKUgCgQoVvjKMMAI1gB3SC0oNBCALYi05FFVArQABwql+eWVlkwhI6AxbRbiVJhyTPtHPJEJAA8AIIAfAAUAJSgAN6SoKBMaAgMuJEAdNkU2qQAXKChsQC84aCRcRYUAJ4ANlgUeIW5guQAvtEA3JLtktJgACKExLAU8Mj+uGgaPNAAHubQ6OQATKBIeioMUig4pDw03rglgaPBANqbutuc19sAulHd-TIAwli65nUUxFJHdEiAEZOKtukA)

I've narrowed down the code to the following

```js
// The function defines an action creator, it uses generics
// to describe what arguments can be passed to the generated function
function define<A>() {
  return (...args: A) => ({ payload: args });
}

// Define a function that expects 2 numbers
const action = define<[number, number]>();

// Complains
action(1, 2);
```

I have one function that generates another one, I want to specify which arguments are allowed as arguments for the generated function, but if I use generics then I get the error that a generic is not compatible with Array.

**Comment by ninjaprox** [comment]
As per mentioned in the [doc](https://flow.org/en/docs/types/functions/#toc-rest-parameters), you need to explicitly use `Array` type for rest parameter, so the following is supposed to work.

```javascript
function define<A>() {
  return (...args: Array<A>) => ({ payload: args });
}
```

However, it doesn't, the workaround will be:

```javascript
function define<A>(): ((...args: Array<A>) => Object) {
  return (...args) => ({ payload: args });
}
```

**Comment by goodmind** [comment]
Flow can't infer generic types inside function bodies
