### ISSUE TITLE
Use --json in emacs plugin

### ISSUE THREAD

**Issue by mroch** [facebook/flow#724]
The [emacs plugin](https://github.com/facebook/flow/blob/master/flow-types.el) should call `flow --json` instead of parsing the CLI output. Right now we have to maintain a special format for emacs, matching the [caml format](https://github.com/emacs-mirror/emacs/blob/cdd5e86967e0a3d23da3079dc5b17ace699e66b3/lisp/progmodes/compile.el#L159) built into emacs.

Instead, it would be nice if all plugins used `--json` and did their own formatting in whatever way made the most sense for them. Relatedly, see https://github.com/facebook/vim-flow/issues/15.

**Comment by calebmer** [comment]
I’m going to close this since the emacs plugin is now at https://github.com/flowtype/flow-for-emacs

This might still be an issue though, so maybe reopen there if you want? 😊
