### ISSUE TITLE
exact objects with indexer properties fails to type check

### ISSUE THREAD

**Issue by villesau** [facebook/flow#7240]
[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AeQEagC8oA3gD6ICQA1ANoDWWaAXKAM4oBOAlgHYBzALps+AVwC2+LF0TkAvsgDGsPp1Cx8bAsTIBDNgEYATAGZ5QA)

following code:

```
// @flow

type Ob = {|
	+[key: string]: number
|}

const ob: Ob = {a: 123}
```

fails. There are valid reasons to use exact indexer: You want to define that all the possible properties have certain type what ever the key is. If the `Ob` type would be inexact, that would mean that it's possible that the object has what ever in it. 

Actually having inexact type 

```
type Ob = {
	+[key: string]: number
}

```

type does not make much sense: What ever key you have should be number, but the object also might have some other properties? There is clear conflict in the logic: the type _needs_ to be something, but it also _might_ be something else.

**Comment by SamChou19815** [comment]
Now it succeeds
