### ISSUE TITLE
readonly object spread fails: property `bar` is read-only in object type [1] but writable in object literal [2].

### ISSUE THREAD

**Issue by villesau** [facebook/flow#7242]
[Try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgDyARqALygDeAPoqKANSSywBc9DbFAQ2w8AzrmwBLAHYBzUAwC+iRQG5k6LHlABjWFLGgArhgAmA3CgBiElNBMBhPZAlzaACmNmLPSgEoaAHyIAJBudKAc3PSggsKgAOQAbgLQEibxoAoANKAAdPme5qQKvkA)

Following code: 

```
// @flow

export type Ob = {|
  +foo: {| +bar: string |}
|};

export const updateFieldConfig = (update: Ob) =>
	({ foo: { bar: 'valid' }, ...update })
```

results following error:

```
4:   +foo: {| +bar: string |}           ^ property `bar` is read-only in object type [1] but writable in object literal [2].
References:
4:   +foo: {| +bar: string |}           ^ [1]
8: 	({ foo: { bar: 'valid' }, ...update })
            ^ [2]
```

As seen from the snippet, there is no writing happening. The nested object is what's failing. The error location is also very awkward: It's in the type, not in the usage which makes suppressing very inconvenient.

There has been similar bug that's been already fixed in 0.83.0 version, but most likely very related and would lead to proper fix in this case too: https://github.com/facebook/flow/issues/6089

**Comment by nmote** [comment]
This no longer errors in master
