### ISSUE TITLE
Suggestion: ReadWrite Utility type

### ISSUE THREAD

**Issue by dcosson** [facebook/flow#7243]
It would be useful to have a utility type that is the opposite of `$ReadOnly`, to make an object's attributes read/writable.

The use case is really the same as anywhere you might want to use ReadOnly. One specific example I have is that there's a library for the Apollo graphql API that generates the graphql types as read-only, and would be useful to be able to use those same type definitions and be able to mutate them.

The readonly docs say `Additionally, other utility types, such as $ObjMap<T>, may strip any read/write annotations, so $ReadOnly<T> is a handy way to quickly make the object read-only again after operating on it:`

I'm not sure why it says "may", but `$ObjMap` does not actually seem to strip the readonly annotation. I guess this isn't technically a bug but it is misleading. [Here is an example of the current behavior](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN6phgDUAhgFxgDOGATgJYB2A5gBoa9AEYseAVwC2IvByEBfANzps+MAFUeXbOTAAeAGoA+ABSGAlOWNhDKtQQBKeBgBMA6twx5ipCgBIAeREAKwBZBhx9XwFNbWxjFVpaVABjOB52MAwAC14+Fmc3Tx0fEj1qZOTmMAByBlqhKtoxMABGRSTkzDz+ADoGPVqRWqUgA)

**Comment by villesau** [comment]
Spreading stripping modifiers definitely looks like a bug to me.

**Comment by alexandersorokin** [comment]
Spreading stripping modifiers looks OK to me because spreading create a new object.

```
type OnlyNumber = {+a: number };

var x1: OnlyNumber = {a: 1};

type RO = {+a: number | string };
type RW = {...RO};

var ro: RO = x1;
var rw: RW = {...ro};

// Not a problem because 'rw' is new object and changing it does not affect 'x1' object and field x1.a is still the number.
rw.a = "2"; 
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyAdjFgHICuAtgEZ4BOYAvGAN4DUAhgFxjE16TAL4BudADcuTAB4BGPiTJU6jFu15g5Y9NnxgASoXWdNA1UwA+YAM4YGAS2IBzMDr0EDAdRMA6f0Y6qFJMDHB8Rury4iFgDAgRPqxs-r5hQcDAYORwGGBcYDhhtDB41GD0AMZclDYEAOTx9WAONvx4SHC0AFZ4lXlcxAAmYJUAFoPOTq4OeUNweG3EuflQUH159fLNXb39+cNg8r4FrbYYDjAw-IKMqPEn6gBEAExPomDo6EA

**Comment by goodmind** [comment]
#7643

**Comment by SamChou19815** [comment]
At this point, behavior for the spread type is impossible to change, so I will just say `{...Obj}` will give you a read-write type, forever
