### ISSUE TITLE
Nested generic (polymorphic) type definitions not working as expected

### ISSUE THREAD

**Issue by amsul** [facebook/flow#7244]
I am trying to type a generic function that has nested generic functions - but failing miserably in being able to do so.

To summarize the scenario:

1. `createStore` takes `State` as a type argument
1. Within `createStore`, `addActor` takes `Payload` as a type argument
1. `addActor` is invoked by passing in an `actor`, which takes the `State` and `Payload` as type arguments.

However, when `addActor` is invoked with an `actor` that is valid, I get this error:

> Cannot call `store.addActor` with `selectActor` bound to `actor` because property `selected` is missing in object literal [1] but exists in `State` [2] in the return value.

The bug can be seen here: [Nested Generic Types](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCAxhnAE4A8AyhgIYZ4A0YACnVvHQCYB8YAXjAAKWg2ZsOXbgEpB-APwASagAs6+GvUa90UAK4A7UgEs4hsMXJ5xtCni3jewgM7a8ALjBjGcgN6oYGAGxhhmFjzcJGRU7JxwPM50pBRe0RSOjCxx0rz+gUFg1hj65BbCOFIJ3F451XIC-AGFhTB4GGCGeAAeGOzkYXQwPgRCyTGu7iyV8TwyBS3E5i5wbQB08ADmwl29-YPD7vMtAL4FZwXFpRbNhZHp5EznqBfAb+jY+GAAslgjgmBbi48G1SHgamAFAARcRPC6fAjUEF4Uh1HgA24ANyG+k8YBhjDAAB8wG5yCZDJtiZ19ABbABGeEeLz0RlM5ks1lsMTwAHUTBhVA9hPkgm0Om57ACrDZGHZrJRfiNnLcgsDQYwIYZ9DAYOdjmBxWBxhQAZLrGt7ikqEiNWi+K5kaQHvMLiF2RZ1SiMMK3LCwDNpKKwCYoCJA9U1tiYLiQ4Y-cY8HAwwS8MGglcyoCFoUvWCIRGeFGccwc2cguWwKACm9vKo4DruGAAHIAeQAKmAmeQKAUlvHVngNnBtn7GGs85qDTXgHWGzAm93e0F+yt1ltJuJhzADavB8PtoXuNuDSgWUA)

I've tried looking around for similar polymorphism issues but I can't really find anything particular to this type of error.

Any pointers would really be appreciated!

**Comment by SamChou19815** [comment]
After full annotation, it works. Full annotation in this example is now the requirement.
