### ISSUE TITLE
Allow field overrides when spreading types (not spreading values)

### ISSUE THREAD

**Issue by nvie** [facebook/flow#7253]
**Example**

```javascript
type Thing = {|
  id: number,
  name: string,
|};

type Thing$External = {|
  ...Thing,
  id: string,  // Overwrite ID's to be strings, not numbers
|};

function toExternal(thing: Thing): Thing$External {
  return { ...thing, id: thing.id.toString() };
  //     ^ Cannot return object literal because number [1] is incompatible
  //       with string [2] in property `id`.
}
```

**Expected behaviour**

This should work.

[Try link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AFQBYCWAdgOagC8oA3gD6KiiEAmAXKMQK4C2ARlgCcANA1BYAHikHEAhtACSbUAGcUAkqRGNZ3LO1XqyI2gF8A3MnTY8RMgBIAopOlzKNeowB03ghq1MlAz9EUwtESE5iAGMUQlhiUBRYJykBWWgAChRbUnZfMgBKPJzHZzTXalEo+NUA-TUNN2yNTwlU9MULRgEsFE40mlBvT2ajANBzRBNEIA)

**Comment by villesau** [comment]
Here is a pr that should fix the issue: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This no longer errors on master
