### ISSUE TITLE
Problem with intersection types & React props

### ISSUE THREAD

**Issue by DavidBabel** [facebook/flow#7254]
With latest flow, i got the props which is an intersection type, the first of it contain a "name" field :
![image](https://user-images.githubusercontent.com/5599375/49793328-41924880-fd35-11e8-91e9-a2cd93d49e65.png)

But when i try to create my component with a spread of this props i got this error : 
![image](https://user-images.githubusercontent.com/5599375/49793506-ab125700-fd35-11e8-808b-45b9b975484b.png)
```[eslint] Cannot create `BinaryField` element because property `name` is missing in props but exists in `ParameterInfos` (see ./src/modules/creatives/form/params-field/choice-binary.jsx:8). [flowtype-errors/show-errors]```

The props of `<BinaryField>`has the exact same Props define like this : 
```js
type Props = ParameterInfos &
  AdditionnalProps & {
    choices: ParamDetails[]
  };
```

What am i doing wrong ? I cannot get it.

**Comment by TrySound** [comment]
Use type spread. Intersection has a bit different usages

**Comment by DavidBabel** [comment]
thanks for the quick answer, i will give it a try

**Comment by DavidBabel** [comment]
I did the spread this way : 
```js
type Props = {
  ...ParameterInfos,
  ...AdditionnalProps
};
```
But i got all keys to become "mixed" : 
![image](https://user-images.githubusercontent.com/5599375/49795807-422ddd80-fd3b-11e8-9d2c-895d5935139e.png)

When the spreaded type has more consistent types : 
![image](https://user-images.githubusercontent.com/5599375/49795854-5ffb4280-fd3b-11e8-8995-734881e05fa4.png)

What am i missing there ?

**Comment by TrySound** [comment]
Provide please http://flow.org/try

**Comment by DavidBabel** [comment]
Here it is : [flow try](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUUoUQkYkoBJAO0wgDOcALxwA3uThwerJAC44AmFGA8A5uQC+FKrXoBBACaHgMYBB4yANgxxghoiVKIBHAK7AihhQCMIEK1QeLR0aOjgAYQALYCtDWwh7EXFJOAA6DKYWNg5uPkEAGlSMtKMTMwtrBPsiqTQ3KCIeGAA1FCs3eUVlVQ1tSiQAD0hYODQrFAEhAHEkHk5gNAAVIZgAMWAkOLhVucMhZHQYNIjcSHnmgB5o2Pi7AQA+FOc9zgAKAEpnqTgiGAaeHA3qkfnBLiYAG4PEGgsGQh5ge5pGRsS4AenhMNB4OAUMRiQEaXqjTmrXanXRmNhPzEMBihPx9jSrg8XjgADJ2QQWZ4kIZ8JosWCMbjoaCPhQpILBbpwllSdUHN8SllZLlePwBLV0hkyqZzJZ2oqQgNhtB4ONJkIVoN1pttrsePtEMRjqdwBZSZd5c1FU8nL9XlBPt8Xv8oIDLrN5iplqsNltDOISnTgAz7poxg0mmSOkhhAAiDhKAtwNEPSVwaXkIA)

**Comment by TrySound** [comment]
Exact types should help here
https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUUoUQkYkoBJAO0wgDOcALxwA3gB9ycOD1ZIAXHAEwowHgHNyEgL4UqtegEEAJieAxgEHnIA2DHGCGjJ0uEQCOAV2BETSgCMICFtUHm09Sho6OABhAAtgWxMHCCcRcSkZADpcphY2Dm4+QQAaN1zs03NLaztUp3KZNC8oIh4YADUUWy9FZVV1LV19JAAPSFg4NFsUASEAcSQeTmA0ABVxmAAxYCRkuC3lkyFkdBhs2NxIFY6AHgSklMcBAD5xN3aTTgAKAEoPjIZEQYK0eHAfm4gXA7uYAG6vKHQmHw15gF7ZORsO4AelRSOhsOACPRaQE2RabWWXR6fVx+ORQLEMES5NJTmynh8fjgADJeQQub4kCZ8DoCTC8cTEdC-hQZOLxQYYvlqQ1nIC4JV8vIirx+AImlrctULFYbD11eRIuRxpN4DM5kJNmMdnsDkceCdEMQLldwNZqXdVR11e8xJ9jr8ARHoSCwTClis1Bstrt9iZxJUWcA2S8dNNWu0ab0kMIAEQcFTluA417yuCK8hAA

**Comment by DavidBabel** [comment]
Thanks for the tips ! 
I see what, but my exact problem seems to be that flow complains on extra param on spread.

What we do is having generic props we spread over many different components. But each components does not have to manage every

**Comment by DavidBabel** [comment]
Thanks again for your feedback. I'm still digging into this

**Comment by DavidBabel** [comment]
And how are we supposed to allow spread to ignore the extra props ? 

[Flow try here](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUUoUQkYkoBJAO0wgDOcALxwA3gB9ycOD1ZIAXHAEwowHgHNyEgL4UqtegEEAJieAxgEHnIA2DHGCGjJ0uEQCOAV2BETSgCMICFtUHm09Sho6OABhAAtgWxMHCCcRcSkZADpcphY2Dm4+QQAaN1zs03NLaztUp3KZNC8oIh4YADUUWy9FZVV1LV19AHpRuMTkuA12OBh4+jBHIQtZJCQTIRQeEzhgDR5oeggFzgFyJAAPSFg4NFsUASEEpL3rjl2hZHQYbNjcJAeEgOgAeV7JBoCAB84jc7RMnAAFABKOEyGREGCtHhwJFuDFwUHmABu0IJhKJpOhyzSAmycjYoNG1IphOJwDJtKc2RabRBXR6fWZrMpGLEC2A9O59M8Pj8cAAZIqCHLfJt8Do2USWZzyYSURQZFqtQYYvkBVCMq4cnlmPIirx+AImnBKtULFYbD0oa6dtRJZoAKK2ARIAD8ShUak0GPGROEiaTyZTqbT6bgiyIEX011u8AeTyEFo6cA+IK2iGIfwB4GsAtBJZgUNhYnhFeRaLbhKxOKJEL2YkqkulKx091a7UFvSQwgARBwVHO4KNoUa4CbyEA)

**Comment by EugeneZ** [comment]
@DavidBabel 

[How about this?](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUUoUQkYkoBJAO0wgDOcALxwA3gB9ycOD1ZIAXHAEwowHgHNyEgL4UqtegEEAJieAxgEHnIA2DHGCGjJ0uEQCOAV2BETSgCMICFtUHm09Sho6OABhAAtgWxMHCCcRcSkZADpcphY2Dm4+QQAaN1zs03NLaztUp3KZNC8oIh4YADUUWy9FZVV1LV19AHpRuMTkuA12OBh4+jBHIQtZJCQTIRQeEzhgDR5oeggFzgFyJAAPSFg4NFsUASEEpL3rjl2hZHQYbNjcJAeEgOgAeV7JBoCAB84jc7RMnAAFABKOEyGREGCtHhwJFuDFwUHmABu0IJhKJpOhyzSAmycjYoNG1IphOJwDJtKc2RabRBXR6fWZrMpGLEC2A9O59M8Pj8cAAZIqCHLfJt8Do2USWZzyYSURQZFqtQYYvkBVCMq4cnlmPIirx+AImnBKtULFYbD0oa6dtRJZoAKK2ARIAD8ShUak0GPGROEiaTyZTqbT6bgiyIEX011u8AeTyEFo6cA+IK2iGIfwB4GsAtBJZgUNhYnhFeRaLbhLQ1hU4jg-sDGhDYdKbtyMrgOgykulK1IcApWJxRIhezElRlM757UFvSQwgARBwVEe4KNoUbp+QtUA)

**Comment by DavidBabel** [comment]
Seems to be the best approach, thanks
