### ISSUE TITLE
include third .flow definition failed

### ISSUE THREAD

**Issue by snasc** [facebook/flow#7255]
my directory structure

    my_proj
      node_modules
        @my_scope
          a_lib
            index.js
            index.js.flow
      src
        .flowconfig
        index.js

the content of `.flowconfig`:

    [ignore]

    [include]
    ../node_modules/@my_scope

    [libs]

    [lints]

    [options]
    module.system.node.resolve_dirname=../node_modules

    [strict]

the content of `src/index.js`:

    const alib = require('@my_scope/a_lib');

the Error is: **can not resolve module @my_scope/a_lib**.  So why? I jus want to use the third-party `.flow` defs.

Actually, I've used this method successfully, and it still work (flow 0.81.0~0.86.0); but in a new project, it failed.

**Comment by SamChou19815** [comment]
There is not enough information to repro.
