### ISSUE TITLE
How to deal with object missing properties?

### ISSUE THREAD

**Issue by alexshelkov** [facebook/flow#7256]
What is the best way to handle cases like this:

```javascript

// Test is some class which contain obj property which is
// an Object which may or may not contain different props
class Test {
  obj: {};
  
  constructor() {
    this.obj = {}
  }
}

let t = new Test();

let o1 = t.obj; // so the type of o1 is {}

// if (o1.test) { // ERROR: property `test` is missing in object type [1].
// // I need somehow to check if test exist an object
// }
```

I have found few options here: **[Link to code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCmYAjgK74DOALgJZwB2Y15Y51AtgA4z4BcYuiFgJIwAJmACSYAMYFpAazBQ4AJzABDBnA4166mGA7qV6tswxZqWgEYArfNMpgE1SsKe51ANysBzMJRwYGxwotRQAJ6MTpQRHPgAdBZgyQDKQW5MkjKaAOROohm4TDzJcHZ8AN6UFJQA-HyaEQC+6NIw6uTM2LVglahgYOW2Vc0A3AMpg9L0VCokjqoAFACUfZODmeQJw2AAvH3jk62tqNwx+2B0+Eg9VKsTZ-hOcACMl5Q7do+YjFBgSzeCRqVDWlTAvwAogAlaEAeWhfA4Km0+BUsTAAAMQZRMYxmGwmKw6P4rEM7A4YnFCABtV4AXSSvxSv1O4QBgNefDhFMcK2BtTBEKweCyWTg8lQp3OQwATJdqrU+HQRDAADRgBJat7jYWSJzi+Qa6wkJwqfD2Rz4cTWKIwKw1FR8Kz4AAe6kcAFpyMj8OpROh2YDZQLQetpc8hgBmS48y2fTqsXx0JaVZoat4rR5BuBR0OUIW-CQG5j6chBXxwUIazTie10R0ac0aGDl-jqDgcCKTACQfcGeoAQqbnLgoq5nKp5OQ6lLUEA)**, but I am not sure if this is a recommended approach to solve this problem.

**Comment by TrySound** [comment]
The problem is that test is not specified in obj and you cannot use it explicitly. Make it optional if it may not exist

**Comment by alexshelkov** [comment]
Yep I know that, but what if I don't know what props may be in that object? For example if it returned as JSON from some remote call? So the type of o1 is {} or Object.

**Comment by TrySound** [comment]
`any` or `string | { [string]: mixed }`

**Comment by alexshelkov** [comment]
Would really appreciate if you could give an example on https://flow.org/try

**Comment by TrySound** [comment]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCmYAjgK74DOALgJZwB2Y15Y51AtgA4z4BcYuiFgJIwAJmACSYAMYFpAazBQ4AJzABDBnA4166mGA7qV6tswxZqWgEYArfNMpgE1SsKe51ANysBzMJRwYGxwotRQAJ6MTpQRHPgAdBZgyQDKQW5MkjKaAOROohm4TDzJcHZ8AN6UFJQA-HyaEQC+6NIw6uTM2LVglahgYOW2fGzUAB74ogDcAymD0vRUKiSOqgAUAJR9c4OZ5AnDYAC8fc2zg62tqNwxJ2B0+Eg9VFuzN-hOcACM95SHdne4TA61i8TgUCGv2OMLAuWGDkouTAADIUVCwABCU50EQGNEBOL4CFQhI1KgnWG5ZZ+XLbSpgTBgACiACVWQB5Vl8DgqbT4FSxMAAA3JlGFjGYYy6fkYNnsjkJ8TAAG1vgBdJILJZOdR8Gl0fynH5k2pzJmLOgU6z6ygqWXG76mqgAJgecC+ik6YHw43ijimqGuwPW6x+fA5dkRm2dlHpjKweCyWTg8iD6FuQzdp2qtT4uJgMAANGAEmWfucE5InCn5CXrCQnCp8AqauJrFEYFYaio+FZfepHABaci8-DqUToENwF2x+npj5fADM90jrYSnVYvjo60qzRLP02QMhYaXc76VYkNeY+nIQV8cFCJc04i7dB7GmbGhgd-46g4HARHMACQoGDFWABCjbOLgUSuM4qjyOQdTpkAA

**Comment by alexshelkov** [comment]
Thank you very much! It is quite interesting. But still, in that case we not sure that `obj` is an `Object`, is it possible just to check for optinal props without having to check for `typeof o1 === 'object' && o1 != null`?

**Comment by TrySound** [comment]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCmYAjgK74DOALgJZwB2Y15Y51AtgA4z4BcYuiFgJIwAJmACSYAMYFpAazBQ4AJzABDBnA4166mGA7qV6tswxZqWgEYArfNMpgE1SsKe51ANysBzMJRwYGxwotRQAJ6MTpQRHPgAdBZgyQDKQW5MkjKaAOROohm4TDzJcHZ8AN6UFJQA-HyaEQC+6NIw6uTM2LVglahgYOW2VQDaVCp+ALp8bNQAHvjizQDcAymD0vQTJI6qABQAlH3rg5nkCcNgALx9q+utrajcMTdgdPhIPVRHa8-4TjgAEY3pRLnY-uEwPtYvE4FAhkCEjUqDdrrdchM-LljpUwJgwABRABKxIA8sS+BwVNp8CpYmAAAYoyiMxjMOZdPyMGz2RwBOKEUZAqZJTbbJzqPhYuj+W7A5G1dYErZ0VHWaWUSayt4KlkAJnecEBik6YHw83ijiWqCeUP2+2BfDJdgclEOiqouPxWDwWSycHktvQLyGhtu1VqfDoIhgABowAkk8DVj7JE4A-IE9YSE4VPg+TVxNYojArDUVHwrBb1I4ALTkan4dSidD2uD6z3uk5PUNwADMbxdhYSnVYvjo+0qzQTwMOkIRjv7Xe9BIkGeY+nIQV8cFCCc04jLdArGnzGhg2-46g4HAi6wAkE-BmmAEK55y4KKuZyqeTkOpgyAA

**Comment by alexshelkov** [comment]
It looks like some hack, but it seems to work. Thank you. But I am still not sure that it is recommended way to handle optional object props.

**Comment by TrySound** [comment]
They are not optional. They are unknown. If you know them you may specify in type.
