### ISSUE TITLE
Interface won't accept unions in indexers

### ISSUE THREAD

**Issue by kkaefer** [facebook/flow#7257]
[Try in Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswBLAOwBctCp8cSBJKmuhsAb1TB7AG0AzpUIUA5gF0AXGCEjyosAB8w5AK4BbAEY1UAXwDc6SgE8ADiQDCccjmLUwAXk7deg4WKkz38pSo3bCPUNUGCxKMAAPaSsbOxInLgBIKDg4aQByTSJ0gBoXRKzCaQBmIPRQ8OMwaWZqWnp4yMMgA)
```js
/* @flow */

declare interface Interface {
    [string]: string | number
};

type Concrete = {
    [string]: string | number
};

let x: Concrete = {
    foo: 'bar',
    bar: 3
};

let y : Interface = x;
```

When using indexers, an Interface won't accept a concrete type `Concrete` and fails with this error:

```
16: let y : Interface = x;
                        ^ Cannot assign `x` to `y` because number [1] is incompatible with string [2] in the indexer property.
References:
8:     [string]: string | number
                          ^ [1]
4:     [string]: string | number
        ^ [2]
```

When removing the indexers and replacing them with verbatim properties like this:

```
declare interface Interface {
    foo: string | number,
    bar: string | number
};

type Concrete = {
    foo: string | number,
    bar: string | number
};
```

Flow accepts the code. I think flow should match the `Concrete` to `Interface` even when unions are used in the interface.

**Comment by gkz** [comment]
Works currently
