### ISSUE TITLE
flow fails to report error for map key value structure when dynamic keys are used and the key argument is typed

### ISSUE THREAD

**Issue by gdanov** [facebook/flow#7258]
[here's the live example](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQE4CuAxiqALygDeiooA2gJYAmAXKAM6FMB2A5gF1QHaqw7cCffgBpQLLBk4cAggQIBDNAB5J0gHwBfRMcTQs5ViK48BlUAHImrFg4DcZi6CK902FgCSLPZOLu7IIFykJFicnIiRACQAogAe2GTJ6rAEnuQa1vjEZPbUDhoARiQOouKOqQ0OhoYeeaAVhYSk5FTULQlgnNGx8UlpGShZBDmIFQzlVQ7CvXUOjf0DUSQxcZsp6ViZ2blzrMs0q+utkQC0NwBiKgEAMneIkD5kTLC8oCixKBUAAoAJQcIrdWj0MYHI7TXL0AgWIgEX7UZgsQS1diOABeuKaxmMBSo-24wJBrQ+vC+Pz+AJUACFQeCumQoaBIkNtiM6JywPsJlMZojkaiaAwfH4sIFMdiOA58YSTBEwHdHi83tTab8yYCAMIsvBslAc8zkJGcUoYrEXHGKgnNDzQgXjQ6TY58pEoFG-S0eYn2PUqQ2U5DalDfXUMgAiRoh7L55tAlutUswMqCtrE9qVTr5XOGuxdoEF7uFCJTYr9sQDyCAA)

and bellow is the code. What seems to be the case is that (correctly) typed dynamic key value switches off the validation of the value for literals used in return or initialization *only*. untyped key value works as expected.
Assignment `a[id] = {id:'zz'}` works as expected and throws error.
```
// @flow

type Struct = {
  [id: string] : {id: string, deps: Array<string>}
}

let id : string = 'iidd';
let untypedId = 'iidd';

// success
// $ExpectError
let a : Struct = {'abc': {id: 'xxx'}};

let b : Struct = {};
// success
// $ExpectError
b['abc'] = {id: 'xx'};

// success
// $ExpectError
b[id] = {id: 'xx'};

// --FAIL--
function testA(): Struct{
  // $ExpectError
  return {[id]: {id: 'zz'}}
}
a = testA();

function testAB(): Struct{
  // success
  // $ExpectError
  return {[untypedId]: {id: 'zz'}}
}

// --FAIL--
function testAC(): Struct{
  let res = {[id]: {id: 'zz'}};
  // $ExpectError
  return res;
}
a = testAC();

function testAD(): Struct{
  let res = {[untypedId]: {id: 'zz'}};
  // success
  // $ExpectError
  return res;
}
```

**Comment by gdanov** [comment]
refines #2928

**Comment by gdanov** [comment]
and  #1971

**Comment by gdanov** [comment]
As I keep trying to figure out the safe boundaries, I did some experimenting with immutable's Map. The schema is similar to the example above, the weirdness again manifests itself only when initializing something with incompatible literal.
```

function testE (idx: string) : Map<string, DepsUnit> {
  // success, detects errors
  // $ExpectError
  return Map ({'abc': {id:'x'}})
}

function testEA (idx) : Map<string, DepsUnit> {
  // FAIL
  return Map ({[idx]: {id:'x'}})
}
// $ExpectError
testEA ('abc');
// fail
testEA (123);

function testEB (idx: string) : Map<string, DepsUnit> {
  // FAIL
  return Map ({[idx]: {id:'x'}})
}
// fail
testEB ('abc');
// $ExpectError
testEB (123);

function testEC (idx: string) : Map<string, DepsUnit> {
  // success
  // $ExpectError
  return Map ({}).set(idx, {id:'x'});
}

function testECC (idx) : Map<string, DepsUnit> {
  // success
  // $ExpectError
  return Map ({}).set(idx, {id:'x'});
}
```

**Comment by LaurentRos** [comment]
Same here

```js
// @flow strict

type StaticKey = {|
  staticKey: string,
|};

const staticKeyObject: StaticKey = {
  staticKey: 'Haha',
};

type DynamicKey = {|
  [key: number]: string,
|};

const dynamicKeyObjectKO: DynamicKey = {
  [1]: "Just a string",
  // Error is expected here but none received
  [8]: 1,
};

// Error well received in that case
dynamicKeyObjectKO[1] = 2;
```

Or live example [[HERE]](https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKFygJ4AOApqAMooCGK2A0qYaALygDeAPrqMjXVkaEAXH0wA7AOYAaXJwC+AbnxZY41H1oMmAeQBGAK1I5RVLYKasOPTQKGiA5AAlqAC2oPZS-ETKgAIoTi1AC22sxsXDYA2gDWTKLiAK4heqRoALqiqBIyct64quoooAAmQaHh+kY49DqigcFhFhHWvNEAjFmgAEQAUkka1GIYUj2yvCCgAKJoaLBooBhIoKQAHmQ4pKWgrunkekkl4mrkaMakGABu2zEAHN0dXsq4U7Pzi-Ck0NCg51iXG47UagFDuEpYahIUi4cpNKqGYwoOqdDJWABMyiAA)

When could you have it fixed please ?
We use that a lot for our normalized Redux states

**Comment by maartenschumacher** [comment]
Is there a workaround for this? Can I somehow force cast a variable to be untyped?
