### ISSUE TITLE
False positive for object literal, control flow and spread operator

### ISSUE THREAD

**Issue by dannyc5** [facebook/flow#7260]
[Bug reproduced in repl](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccAKrgQLxgDeqYYARgIYBOAXGAHYCuAtozytUAX3TZ8REgCE25SdToMoJTsTIVR6AMZwuAZwxMeASxgATdWGoAKfXD55pJGJ0Yu8zLgEo1MuRTWAHy0qACQMHhGzPrmUH4a+ADc9GCpDCZQYHYOTi7eoWFhwMBgAOoAEgCaYFUA8gCqYABydUQAggCSADIA-OlgImB4MPoESgyTMXHWoZPzTGycAIwANAMMYvNbaWGsUTysXHMLKnCcEwtgAHS301DrVyKPkyIpO6iMphbqNhisPDw3iSQA)

```
type FooType = {
  bar: number
}

type FooBarType = {
  foo: FooType
}

const buildFoo = (someBool: boolean): FooBarType => {
    let asdf: FooType;
  
    if (someBool) {
		// WHY YOU NO FAIL?
    } else {
      asdf = {
        bar: 1,
      }
    }
  
    return {
      foo: {
        ...asdf,
      },
    };
}
  
buildFoo(true);
```

I would expect flow to error for the `true` branch.

**Comment by SamChou19815** [comment]
We now error on this
