### ISSUE TITLE
Type confusion when using generics object field names and arrays

### ISSUE THREAD

**Issue by abustany** [facebook/flow#7263]
Sorry about the not really descriptive title...

I'm having a piece of code that deals with arrays inside an object, and am trying to type it. The arrays are uniform (each array has all its elements of the same type), however different arrays hold object of different types.

The following [Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHhgE4CGAxhgIJmVYAquBAvGADwBqAfABTcA2gF0AlGDa8w3ANzooAVwB2NAJZxlYMngDmagM4Y8ZAMIY4ZTkwBcYAN4BfADQy7AEgDSeLAeu8BVDAwNWMAW3NLO34JKTB3UwoYGE4Scmo6BgpmVld3Qhg8MLxlDBZ8a1c+XlQxOwA3ODUAEwdUR3RsfDBaZTUwpMk24OUKYrsjMjVlXWcgsAQ8NV0ACww7ZUUwgCMTOcd5TFYwAAUYCmV2YbABzagMxR0yCfJp2fmwuGa8GBepmf2hy6BAA6pYYK0OPZ5hd+kkDHZenCYKI5sEcOdLgjTpi8Kj2ugdPojCZIlYwWQIa4AOSwgYwAzUwLBGKSaT8eyjcZganU1yLZZrOwABkcYlqhyJhmMZgs5PBzRpGIueEZzLArLiHNuinuNEeJjsvNcn2+vx51LFEqAA) illustrates the issue (the code itself is useless, I trimmed it as much as possible to only keep the error). It kind of looks like Flow memoizes the result of the `$Call` on its first invocation, and doesn't consider the fact that the second call to `registerCtor` has a different field name. If I copy paste `registerCtor` as `registerCtor2` and use that in the second call, then Flow is happy.

This was tried with version 0.88 and master as deployed on Flow Try.

**Comment by goodmind** [comment]
[This](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swAnAUwHNCBnfCsgYXzjIB4AVALjAG8AvgBowANV4ASANIUAnrS4A+RQApUYMIQYBbFm14qAlGAC8isBKYBDGDHbtRqgG6SAShSsATAPLYYsgEEyMitZB0VjMzEwADIxEQkAURgKbQpsfE5ZAAcKLhFHRVRDXic4Qk9+VAF0fByKMADsQm0bUyqNbCs03noyQmwqIXUwBApCKgALfF5sTG0AI0ZhgQBuWvqwAAUYK2wGkw6wVrmoKwJMSjJe-H7B4Y1tOE8KGBu7oer11DrcsAB1NgwSqHPgjPYtGy0XhNSEwADaAF0HmBsrt9tDtuiKEiVuhKDR6Iw9BxAWRgSIAOQQ1owWiU1QjIymcwqPhdHpgSmUkRjCbTXgABgEhmK3wJdAYzFYpKBnipaL2FHpjI0zKibJOmDOFyuvG5IieLzeXMpIrFQA) works
