### ISSUE TITLE
The lint rule `deprecated-utility` is not documented

### ISSUE THREAD

**Issue by doberkofler** [facebook/flow#7270]
The new lint rule `deprecated-utility` introduced in flow 0.89 is not documented

**Comment by jbrown215** [comment]
cc @dsainati1

**Comment by arcollector** [comment]
excuse me, but setting` deprecated-utility=false` breaks flow, this is my `.flowconfig`

```
[ignore]
.*/node_modules/.*
.*/dist/.*

[include]

[libs]
flow-typed

[options]
all=true
deprecated-utility=false
```

flow says:

 .flowconfig:12 Unable to parse line.

**Comment by dsainati1** [comment]
This isn't how you turn off a lint error. You have to use the `[lints]` section of the `.flowconfig`, and set `deprecated-utility=off`
