### ISSUE TITLE
How can I import a class field type definition?

### ISSUE THREAD

**Issue by fterh** [facebook/flow#7272]
I have installed Flow type definitions for ExpressJS (https://github.com/flow-typed/flow-typed/blob/master/definitions/npm/express_v4.16.x/flow_v0.32.x-/express_v4.16.x.js).

I have a function that accepts a single argument (the `query` property of `express$Request` - line 33). How can I import just that particular type (e.g. as `queryType`) to type my function (e.g. `function foo(query: queryType) { ... }`?

Currently, I declared a queryType by copying and pasting the definition, but this is obviously undesirable because I have to manually update the type definition should express$Request change in the future.

**Comment by mirek** [comment]
```
type Query = $PropertyType<express$Request, 'query'>

// or:

type Query = $PropertyType<typeof myRequest, 'query'>
```
?

**Comment by fterh** [comment]
I'll look into that, thanks!

Also, I apologize for the wrong forum :)
