### ISSUE TITLE
I still need $Supertype

### ISSUE THREAD

**Issue by bigslycat** [facebook/flow#7273]
I use `$Supertype` in [typed contracts](https://github.com/bigslycat/typed-contracts). And this is the only way to make [this](https://github.com/bigslycat/typed-contracts/blob/master/src/contracts/object/object.js#L10) and [this](https://github.com/bigslycat/typed-contracts/blob/master/src/contracts/object/shape.js#L10) code work. What should I do after `$Supertype` is removed? Help me.

**Comment by steida** [comment]
Switch to TypeScript. Facebook has two kinds of open source. A real one likes React. And the second one, when they just mirror some internal tools and almost nothing more. DraftJS, Relay, Flow etc. are fake open source projects only to confuse people. I highly recommend avoiding such traps. Marry Christmas.

**Comment by bigslycat** [comment]
I was hoping to get a constructive response, not an opinion sry.

**Comment by TrySound** [comment]
Did you changed your mind?

**Comment by jbrown215** [comment]
`$Supertype` was the original way we (unsoundly) gave some sort of support for variance. Now, you can mark the type parameter contravariant using `-` to use the behavior `$Supertype` gives you in a sound way.
