### ISSUE TITLE
Flow runs out of memory when using symlinks in a monorepo

### ISSUE THREAD

**Issue by migueloller** [facebook/flow#7274]
I've got a monorepo set up with Lerna and various packages. Recently Flow started to fail with the following output:

```
Launching Flow server for /Users/miguel/Code/cosmos
Spawned flow server (pid=61935)
Logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.log
Monitor logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.monitor_log
Launching Flow server for /Users/miguel/Code/cosmos
Spawned flow server (pid=62772)
Logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.log
Monitor logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.monitor_log
Launching Flow server for /Users/miguel/Code/cosmos
Spawned flow server (pid=63610)
Logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.log
Monitor logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.monitor_log
Launching Flow server for /Users/miguel/Code/cosmos
Spawned flow server (pid=64448)
Logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.log
Monitor logs will go to /private/tmp/flow/zSUserszSmiguelzSCodezScosmos.monitor_log
Lost connection to the flow server (0 retries remaining): \Out of retries, exiting!
```

Basically, it just runs out of retries. After some inspection I was able to reduce the issue to the addition of a dependency from one of the local packages (i.e., `lerna --scope $PACKAGE_A add $PACKAGE_B`). It seems that Flow doesn't like these symlinked packages very much. Weirdly enough, we already had dependencies like these in our monorepo, but it's only started giving us issues now. We've been seeing degrading performance over time so perhaps this has been an issue for a while but now it's hit enough critical mass to prevent Flow from working at all.

After taking a look at the logs, one line sheds light into the issue:

```
Subprocess(64457): fail 16Unhandled exception: SharedMem.Hash_table_full
```

Increasing `sharedmemory.hash_table_pow` from `19`, the default value to `20` fixed the issue. This isn't desirable, though. Is this an issue because of the symlinks? Is it simply that there's more files and Flow needs to keep them in memory?

Any guidance here would be appreciated!

**Comment by jedwards1211** [comment]
@migueloller just curious, did you create the symlinks using `flow-mono-cli`?  I've had some success using `flow-mono-cli` in lerna monorepos

**Comment by vicapow** [comment]
How many files does `flow ls` show? It may shed some light on the issue. One guess is that the symlinked modules are showing up to flow as duplicates. especially in a monorepo with symlinked node_modules in every package, that could add up quickly.

Additionally, try excluding everything but modules that have types in our `.flowconfig` to help cut down on the files flow needs to parse.

**Comment by migueloller** [comment]
@vicapow, `flow ls` doesn't seem to duplicate the symlinked files. The command reports 234,102 files.

**Comment by migueloller** [comment]
@vjpr, we've successfully leveraged hoisting from Yarn workspaces to avoid duplicate dependencies in our filesystem. Flow is running pretty quickly now that we've increased the available memory in the hash table.

The file count is 234,2012.

**Comment by vjpr** [comment]
Cool, I ran into the memory issue too and the recommendation fixed it also.

**Comment by SamChou19815** [comment]
Unfortunately, there are no repro provided so it's hard to figure out what's happening.
