### ISSUE TITLE
Connect to a flow server over ip

### ISSUE THREAD

**Issue by mnieber** [facebook/flow#7276]
Hi, 

I would like to know if it's possible to run a Flow server in a Docker and setup my local Flow configuration such that it connects to that server. I haven't found any mention of this in the documentation, but usually this is possible when there is a server/client setup.

I'm asking because I'm editing my sources on the host (in Sublime Text) but all code - including Flow - runs inside a Docker.

Best,
Maarten

ps The intended approach would have an additional problem with translating server-side filenames to client-side filenames, but that might be solvable in some way.

**Comment by SamChou19815** [comment]
The recommended way is to use the remote container setup supported by VSCode. I think Flow should work in this case.
