### ISSUE TITLE
Empty object litterals are not typechecked since flow 0.89.0

### ISSUE THREAD

**Issue by flegall** [facebook/flow#7287]
This code doesn't have any errors in flow 0.89.0, while it has errors in previous flow releases.
```
// @flow
var obj: { foo: boolean } = { };
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQA3AhgJ1LARgKwIwBcoA3qJLLMdpdAKaoB2oAvqALymsDcQA

**Comment by dsainati1** [comment]
This is intentional because obj is inexact. If you want this to report an error make the type of obj exact. 
https://flow.org/try/#0PTAEAEDMBsHsHcBQA3AhgJ1LARgKwIwBcoA3gD6iSyzHbXQCmqAdqGQL6gC8po7A3IiA

**Comment by flegall** [comment]
Ok, I see. 

When I'm using empty objects, it's usually not to add properties afterwards, it's temporary : 

I usually just write :
`var user: User = { };`

Then I expect flow to complain about missing properties from AType.
And then I add the missing properties : 
`var user: User = { id: '1', name: 'John' };`

With this change, it changes a bit my workflow.

**Comment by dsainati1** [comment]
If you don't want to add properties afterwards, you should consider making the type of `User` exact. This will maintain the behavior you want.

**Comment by vaukalak** [comment]
@dsainati1 it looks like the functionality is inconsistent with type intersections:

```
// @flow
type goldContainer = { gold: number };
type woodContainer = { wood: number };
type woodAndGoldContainer = goldContainer & woodContainer
var obj1: woodAndGoldContainer = { gold: 1 };
```
this code throws an error:

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagOa2gCYDCsAdsgIYCWpmATqALygDeu+BAXKKQK4C2AI3qgAvgG4UGbPFixiZSjRHM2s+dz5CREqVlDqCAQVIEA4hxLlqtBszyErS26ABkBuQuvK6iAG4UDLCCAFYAjNyGJuaWijYqrOyE3GFi4kA

And that's actually good, cause I didn't find an option to make intersection work with `$Exact`.

Also, for everyone who would like to continue using types partial interface implementation, looks like we can use interfaces for that:
https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUAcVmgBMBhWDPNHUAb1AHNyKAuUVAVwFsARowC+AbkSICtAM7o2HGnQbZuZSkvT1UjALzNQ4oA
