### ISSUE TITLE
Accessing an array item of an empty array doesn't report an error

### ISSUE THREAD

**Issue by NameFILIP** [facebook/flow#7288]
Example: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKcAxgJYCGMAkgHZRxgC8YA3gngEYDOZGeALjAB+bhgBOZWgHMAvgG50JOLTFgK48UICCmilgA8xclToMAfMzABtALqLUy1XBh4AdPGkAKDeOsAGWzcOHj48AEp5MGBgMAwAC3FEbnVaMDxNOHEgA

**Comment by k15a** [comment]
https://flow.org/en/docs/types/arrays/#toc-array-access-is-unsafe

**Comment by jamesisaac** [comment]
Closing as answered above.  For now, if you want to enforce safe access of an array, you can union the type with `void` e.g. `Array<SocialInfo | void>`.

**Comment by thecotne** [comment]
> Closing as answered above. For now, if you want to enforce safe access of an array, you can union the type with `void` e.g. `Array<SocialInfo | void>`.

is it possible to enforce `Array<T | void>` at config level? like some strict rules?

**Comment by jamesisaac** [comment]
Unfortunately nothing at the moment.  Some relevant discussion here: #7439
