### ISSUE TITLE
writableStream.bytesWritten does not exist in built-in node.js

### ISSUE THREAD

**Issue by cvlr** [facebook/flow#7293]
- flow-bin 0.89.0
- Node 11.5.0
- Yarn 1.14.0-20181221.0548
- WebStorm 2018.3.2

```js
import * as fs from 'fs';

const writableStream = fs.createWriteStream('');

console.log(writableStream.bytesWritten);
//                         ^^^^^^^^^^^^
```

# Error

> Flow: Cannot get `writableStream.bytesWritten` because property `bytesWritten` is missing in `WriteStream` [1].

## Built-in node.js

```
  declare class WriteStream extends stream$Writable {
    close(): void
  }

  declare function createWriteStream(path: string, options?: Object): WriteStream;
```

Why is not the build-in node.js 100%?

**Comment by jbrown215** [comment]
Feel free to add it in! The libdefs are primarily maintained by the community.

**Comment by farzonl** [comment]
@goodmind  or @vicapow  I put out a PR for this change could you mark this issue as has a PR?  Also if either of you have tome to review the change I would appreciate it. thanks!
