### ISSUE TITLE
flow coverage --color doesn't work when output is a pipe

### ISSUE THREAD

**Issue by benjaminjkraft** [facebook/flow#7299]
I love `flow coverage --color`!  But it sometimes produces a ton of output, so I want to pipe it to a pager like `less`.  Sadly, it assumes that anyone piping its output couldn't possibly want color, even if color was explicitly requested.  I'd love to have `--color=always` or some such, as many unix commands have, that says "no really, do color even if the output isn't a tty".

**Comment by mroch** [comment]
Which version are you using? I would expect https://github.com/facebook/flow/commit/40481090273ca94d14879122d1cb971fc1cb18da to have changed this in a recent version (can’t tell which one on my phone)

**Comment by benjaminjkraft** [comment]
It sure does work now!  (In 0.89.0.)  My apologies for not checking first.
