### ISSUE TITLE
export = in declarations file

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#73]
I try to use bluebird.
The definition file is like that.
```typescript

declare module "bluebird" {

  declare class Promise<R>  {
    constructor(callback: (resolve : (result: R) => void, reject: (error: any) => void) => void): void;
    then<U>(onFulfill?: (value: R) => Promise<U> | U, onReject?: (error: any) => Promise<U> | U): Promise<U>;
    catch<U>(onRejected?: (error: any) => Promise<U> | U ): Promise<U>;
    static resolve<T>(thenable?: Promise<T> | T): Promise<T>;
    static reject(error: any): Promise<any>;
    static all<T>(promises: Array<Promise<T>>): Promise<Array<T>>;
    static race<T>(promises: Array<Promise<T>>): Promise<T>;
  }
}

```
The problem is that I have no way to declare that 'bluebird' is 'Promise', with typescript I would do : 
```
export = Promise;
```
is there a way to declare such behavior ?

**Comment by ransanjeev** [comment]
What's the workaround for this? 
I am trying to use the var ClassNames = require('classnames') ;
Not sure how to declar the interface for this.

**Comment by samwgoldman** [comment]
Generally you should be able to use the "special" identifier `exports` to declare your default exports. However, it seems there is an issue (#457) with polymorphic default exports which will prevent a default exported bluebird Promise class from correctly type checking.

See #455 for an example of the `exports` declaration.

**Comment by mroch** [comment]
ok, #457 is fixed, so this should be possible in master, and when 0.13 is released.
