### ISSUE TITLE
function accepting a union type ends up unsoundly casting to any

### ISSUE THREAD

**Issue by benjaminjkraft** [facebook/flow#7302]
Consider the [following code](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4DqAlhgBYAieUxArjBgDwAqAfGAF4wAEgBKeYgBMA8gDsYWTgG9JzNhwBcYbgF9+AH20BuMMGBgAzsQC2BAE54L7DGGqyw9AnE92wcO6p2ADR+vgjAcCLiUnIK6FCssgDGGNRw7takFDT0TCzOnADCvAAUcGQAVlok5FS0jGoFxQCUWoVgSqhgYA4YrHbuZZVgAGQjfpUAdKr5HM1g+oblFUaoOuglmbU5DbMYJSqNmmAAjDqtYHjWONjNJmY9eH0DFqeom1l1uUf7JxdXNywd26INBIIexBgFkivX6sleJyAA):
```
type MaybeWithDefault<T> = $ReadOnly<{default: T}> | T; // same result in the other order, or w/o $ReadOnly

function maybeWithDefault<C>(obj: MaybeWithDefault<C>): C {
  return (obj && obj.default) || obj;
}

(maybeWithDefault({default: 1}): empty); // returns 1
(maybeWithDefault(1): empty);            // also returns 1
```
(As motivation, this is a function you might want to call on the result of `import()` when you don't know if you have an ES6 or CJS module.)

It's not totally clear to me what the result of this _should_ be: perhaps flow should complain about the definition `maybeWithDefault`, since `maybeWithDefault<{default: number}>({default: number})` does not have type `{default: number}` but rather `number`.  (For this reason it's not totally clear to me what the correct type of this function is.)  But it should definitely complain somewhere: we have a perfectly valid function which Flow now claims returns `empty`.

Note that if you give explicit structural types (e.g. `{default: number}`) to the arguments, it [still fails](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4DqAlhgBYAieUxArjBgDwAqAfGAF4wAEgBKeYgBMA8gDsYWTgG9JzNhwBcYbgF9+AH20BuMMGBgAzsQC2BAE54L7DGGqyw9AnE92wcO6p2ADR+vgjAcCLiUnIK6FCssgDGGNRw7takFDT0TCzOnADCvAAUcGQAVlok5FS0jGoFxQCUWoVgSqhgYA4YrHbuZZVgAGQjfpUAdKr5HM1g+oblFUaoOuglmbU5DbMYJSUqjZpgAIw6Wkd7WrKs1hR2Os2tYHjWONjNJmY9eH0DFjOqE2WTquWO+xKpxudwezy0bw+WC+3VRaNRP2IMAskV6-VkgNOQA).  But if you write them both as `MaybeWithDefault<number>`, it [correctly complains](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4DqAlhgBYAieUxArjBgDwAqAfGAF4wAEgBKeYgBMA8gDsYWTgG9JzNhwBcYbgF9+AH20BuMMGBgAzsQC2BAE54L7DGGqyw9AnE92wcO6p2ADR+vgjAcCLiUnIK6FCssgDGGNRw7takFDT0TCzOnADCvAAUcGQAVlok5FS0jGoFxQCUWoVgSqhgYA4YrHbuZZVgAGQjfpUAdKr5HM1g+oblFUaoOuglmbU5DbMYJSUqjZpgAIw61Vl1ucdcsqzWFHa8za1geNY42M0mZj14fQGFjOqE2Vx2eXU+xKp0u23qkIK90eeGery0Hy+WB+3VxeNxf2IMAskV6-VkwNOQA) about the cast to `any`.

It's possible this is related to #7300 -- certainly it's related to my last addendum there -- but since the example is pretty different I figured I'd make a separate issue.

**Comment by benjaminjkraft** [comment]
Here's an interesting variant: if I try to type `MaybeWithDefault` as
```javascript
type MaybeWithDefault<T> = $ReadOnly<{default: T}> | $Diff<T, {default: mixed}>;
```
now passing `{default: 1}` [gives the right output type, but `1` does not](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4DqAlhgBYAieUxArjBgDwAqAfGAF4wAEgBKeYgBMA8gDsYWTgG9JzNhwBcYbgF9+AHxENqUKDwA0YFWvYYA-FoC21AB55JegNzoorWQGMMajhZMEdSChp6JhZbTgBhXgAKODIAKy0ScipaRhsOBN4ASi14q1QwMAAnPAxWKtCU9LAAMhawVLSAOlVYjiKwfUNO7x10JPDsqLy+jCTrWa0ARh0SsDxHHGwizzBgYDAWahgAZ1QJiJzo-LmltY2trB3Kl9eX-bAT1hwcOBP3BQdADWqCAA).  (I now realize this is not the correct type: `$Diff` wants an object, and doesn't do what I want anyway.  But it's interesting in the context of the bug)  This appears to be because Flow is unable to coerce 1 to `MaybeWithDefault<number>` -- but instead of erroring as such it just coerces to `empty`.  If I add an explicit type of `MaybeWithDefault<number>` to the `1`, flow now [errors on both sides](https://github.com/facebook/flow/issues/7302), as it should: once because it cannot cast `1` to `MaybeWithDefault<number>`, and once because it cannot cast the result to `empty`.

**Comment by benjaminjkraft** [comment]
Aha!  I've found the correct way to type this function, and once I do, Flow [is happy with it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCqAdgCa5QCGArjOmALxgA8AKgHwAUAJAEq4UkA8kRiYmAbzKUa6AFxgWAXzZgAPgoCUDFSwDcqVFCpEAxugCWcImAC2FTACNcAdXPoAFgBFy1WkwDCnHAOAFby-hryXP4UMDBMxFK+6AA0YIFg4qhgYABOuOhUudYcwSFgAGQVYGUAdEkyWqrqZfqKBhx2ji5uXj4yHACMkWC4NthYGro5M7Nz8wuLwMCjublwuWAcAM7ucDQkYE5gRFQ2TrkaqJ32Tq4e3tK0HJL9tPKDiiNjE5hTiwD5stVutNjs9gcjvhTudcJdrl07r1HskXg13pl0XIwJ8vvIfpNpsC4aCtrt9jBDsdXk9sTCLl9UEA):
```
type Undefault = <T>($ReadOnly<{default: T}> | T) => T;

function maybeWithDefault<C>(obj: C): $Call<Undefault, C> {
  return (obj && obj.default) || obj;
}
```

So the bug is probably in the fact that the type I originally gave `maybeWithDefault` is not correct -- and rather than reporting a type error in the definition, flow deduces that the type is uninhabited, and proceeds from that contradiction to the original issue.

As a side node, I tried to simplify the type like so:
```
type Undefault = <T>($ReadOnly<{default: T}> | T) => T;

const maybeWithDefault: Undefault = (obj) => {
  return (obj && obj.default) || obj;
}
```
This definition [errors all over the place](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCqAdgCa5QCGArjOmALxgA8AKgHwAUAJAEq4UkA8kRiYmAbzKUa6AFxgWAXzZgAPgoCUDFSwDcqVAGM4RAM50AthUwAjXAHUAlugAWAEXLVa84lK91GDjgbACstehVxVDAwACdcdCpYojAg0LAAMgywYJCAOj8ZLVV1XP1FA1BUDitbB2d3TxkOAEYNeVwLbCwNXRj+gcGh4ZHgYDBcWNi4WNTTFzgaEjA7MCIqCztYjWrauydXD2laDkkm7zAWxXaJrp6+kcfBsYmpmbmFpZX8dc3JnZq1n2DSO-lOhQuZ2OckuimuHTumF6YBek2msw480WMGWqyh-nkvy211QKCAA).  The errors are kind of meaningless: they say things like
```
`T` [1] is incompatible with `T` [2]
```
(where those two `T`s do refer to the same type variable, I believe) but I think they do point to the fact that neither of these types are quite right.  Somehow the `$Call` seems to cause Flow to do what I want, but anything that makes `<U>(U) => $Call<T, U>` a different type from `T` seems quite suspicious to me.  (I guess in lambda-calculus land this is called an [η-conversion](https://en.wikipedia.org/wiki/Lambda_calculus#%CE%B7-conversion).)

**Comment by wchargin** [comment]
As you probably realize, the `type Undefault` is empty. Its type
requires it to discriminate in ways that the runtime elision cannot
(α-renaming `default` to `x` for readability):
 
```js
// @flow
type Undefault = <T>($ReadOnly<{x: T}> | T) => T;
declare var f: Undefault;
const a: {x: 1} = f<{x: 1}>({x: {x: 1}});
const b: {x: {x: 1}} = f<{x: {x: 1}}>({x: {x: 1}});
// Both of the above expressions elide to `f({x: {x: 1}})`, so they must
// evaluate to the same value, but no value has type `{x: 1}` and also
// type `{x: {x: 1}}`.
```

([Flow Try link.][try-1])

[try-1]: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagKoDsATTSAQwFdplQBeUAHgBUA+ACgBIAlTEggeT2io6AbwAeALlAMAvk1AAfKQEoachgG5ERAMbQSAJ2wA3A6EiT8RUhWSbtsPAGcqJSWMkBGaTTMiJoL1Z3UGCvaSU7B2dQACM3f1Dpb1pIP3jPJKCE-zCIxCA

Accordingly, the type expression `$Call<Undefault, C>` doesn’t make
sense to me. What type _should_ `$Call<Undefault, {x: {x: 1}}>` evaluate
to? It has to evaluate to two incompatible types!

Aside: as long as you’re using `&&` and `||` with parameters of generic
type, you should probably be aware of #6671. I can’t tell that it’s
directly related to this issue.

(And, :wave: !)

**Comment by benjaminjkraft** [comment]
:wave: and thanks for the response!

> As you probably realize, the `type Undefault` is empty.

You make a good point!  I had convinced myself that something weird and universally-quantified was going on as long as the `<T>` is on the right side (`<T>(...)` rather than `Undefault<T>`) but now I don't think that makes any sense -- you end up filling in the quantifier sooner or later.

That all said: I wonder if what's going on here has something to do with how flow interprets unions as having some sort of left-first precedence.  (Which I think I've seen mentioned on other issues, although now I can't find them and it doesn't appear to be documented.)  That is, Flow is interpreting `$ReadOnly<{x: T}> | T` as something to the effect of `$ReadOnly<{x: T}> | (T \ $ReadOnly<{x: T}>)` (where `\` is set-difference).  If we interpret union as such, then the type is correct (`f<{x: {x: 1}}>` can accept an `{x: {x: {x: 1}}}`, but not an `{x: {x: 1}}`).

Given that definition of union, unless I'm missing something the "correct" type signature with `Undefault` is in fact correct, and Flow understands it.  In that case the bug is somehow triggered by specifying the type argument, or by writing it the first way I tried (which perhaps similarly counts as specifying the type argument).  Or perhaps it's better to say Flow is inconsistent as to which meaning of union it uses.

As an aside, `$await` has a similar type:
https://github.com/facebook/flow/blob/2ac56861e3ceff9ca406ae586fbafb3480c6c0b7/lib/core.js#L643
I wonder how that works -- I suppose in practice it's somewhat difficult to create a `Promise<Promise<T>>` since the Promise spec does its best to collapse those whenever possible, but it's surely a concern in theory!

> Aside: as long as you’re using `&&` and `||` with parameters of generic
> type, you should probably be aware of #6671. I can’t tell that it’s
> directly related to this issue.

Huh, good to know!  I agree it doesn't seem to matter here -- and anyway I'm not super worried about type-checking of this function itself, rather of its callers, so problems with `&&` only matter to me insofar as they allow me to write an incorrect type and have Flow accept it.

**Comment by wchargin** [comment]
Here is another strange observation about your original code—Flow will
in fact raise the proper errors at the call site [if you inline the
parameter type alias, `MaybeWithDefault<C>`:][try-2]

```js
// @flow

type MaybeWithDefault<T> = $ReadOnly<{default: T}> | T;
function f<T>(obj: MaybeWithDefault<T>): T {
  return (obj && obj.default) || obj;
}
// No errors on either of the following!
(f({default: 1}): empty);
(f(1): empty);

function g<T>(obj: $ReadOnly<{default: T}> | T): T {
  return (obj && obj.default) || obj;
}
// Appropriate errors on both of the following!
(g({default: 1}): empty);
(g(1): empty);
```

[try-2]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWQIZoBGWA6gJYoAWAIlpPgK7QoA8AKgHygC8oAJACUs+ACYB5AHbQ0rAN6j6TFgC5Q7AL7cAPuoDciSI0kBjFOViTQkDpwAUsIgCs1BYmUq0lzNlwCUauygcoigoABOWCiM4VYOzqAAZImgjk4AdIoMPn6g2rppBhqIIKAAcrCgWOHhsOEAzqlWWJ7VqZCg1DiQsNBw8OSSAOYAhIh2kHYK3qqgAIwaAVUAthjofgYTdnNLWKvrBobGZhZWQ7bxLgLCYlIy8lnKKIFaeepLQSFhkdGxoJdJFJpTIzFC5fKpZxFEpgACCGAwtUR5HwKBw1VqDSaoCIsGo7U6VG6vX6g1G4yGU0ePjUC12+zQGwp23pa0ZBiAA

So clearly at least _part_ of this is a bug and not just some convoluted
formulation of unions and universals.

> with how flow interprets unions as having some sort of left-first
> precedence

Ugh… thanks for the pointer to #2212 (a fitting issue number); I’ve been
trying to find a reference to this for a while. Yes, Flow’s algebra of
types leaves something to be desired:

  - [intersections are not commutative][cap-no-comm];
  - [intersections are not associative][cap-no-assoc];
  - [unions do not absorb][cup-no-abs] (`x: T` should imply `x: T | U`);
  - and, as you now point out, unions are not commutative.

[cap-no-comm]: https://github.com/facebook/flow/issues/5895#issuecomment-370009967
[cap-no-assoc]: https://github.com/facebook/flow/issues/6641
[cup-no-abs]: https://github.com/facebook/flow/issues/6945

> That is, Flow is interpreting `$ReadOnly<{x: T}> | T` as something to
> the effect of `$ReadOnly<{x: T}> | (T \ $ReadOnly<{x: T}>)`

I’m not _exactly_ sure what you mean by this. Extensionally, those sets
are of course identical, so it’s not just a question of what the union
operator does, but something about how it interacts with instantiation
of universal quantifiers. Right?


> I wonder how that works -- I suppose in practice it's somewhat
> difficult to create a `Promise<Promise<T>>` since the Promise spec
> does its best to collapse those whenever possible, but it's surely a
> concern in theory!

Right. I’ve asked a friend who knows way more about this than I do and
will post back if he has any insights.

**Comment by benjaminjkraft** [comment]
> I’m not _exactly_ sure what you mean by this. Extensionally, those sets
are of course identical, so it’s not just a question of what the union
operator does, but something about how it interacts with instantiation
of universal quantifiers. Right?

Yeah, I'm not exactly sure how to rigorously describe what I mean, but it's the fact that that quantifier may be a part of some other type as well that is important.  (Also, I now realize it should really be `$ReadOnly<{x: T}> | (T \ $ReadOnly<{x: mixed}>)` or something -- well I think that `mixed` should be whatever the bound on `T` is.)  So in particular (dropping the `$ReadOnly`s just to make this less verbose) `{x: T} | (T \ {x: mixed})` is equivalent to `T`, but `({x: T} | (T \ {x: mixed})) => T` is not equivalent to `T => T` -- if `T` is an `{x: mixed}` we have to take the left option.  We can fill in say `T = {x: number}` to get `{x: {x: number}} => {x: number}`, but not to get `{x: number} => {x: number}` -- if we want the left side to be `{x: number}` we need `T = number`.  Again, I'm not sure about the rigorous construction but it feels like there exists a consistent definition that should be possible here.

**Comment by SamChou19815** [comment]
This is now erroring under `inference_mode=lti`
