### ISSUE TITLE
Spread operator inconsistency with optional object properties

### ISSUE THREAD

**Issue by Dbuggerx** [facebook/flow#7304]
In the following code, I'd expect both functions to throw an error, but the _spread_ version works.
[Try it](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swoBDQmAZwEFqBRADwAcBTAtgEwAomAuMLQCUggEJgA3qjBgATm3yY5pabLABIcoKYA6cgBoZ6gEY7dJo+rC5zuYwF8A3KgfoseIiTDUAFnEwYLloaOAAxShgxTHwAdTg5AGtqPkERcSljBSUVTPUNXUKmRxc3VHwAT3YhMABeTI0Aam0wEzg4GDZybCtNRrMwbEwAWxM2OV6m3AB+QWp8OUJsAHNXdErqiXrpLUE2jq6e4w0BodHxydsfBaXVhyA)

```
/* @flow */

function failsAsExpected(x: A): B {
  return {
     a: x.a,
     b: x.b,
     c: x.c
  };
}

function shouldAlsoFailButWorks(x: A): B {
  return {
   	...x
  };
}

type A = {
    +a: boolean,
    +b: number,
    +c?: string
}

type B = {
    a: boolean,
    b: number,
    c: string
}
```

**Comment by villesau** [comment]
@Dbuggerx this pull request fixes this issue as well: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This now has the expected behavior on master
