### ISSUE TITLE
Missing type annotation error when using immutable Map merge

### ISSUE THREAD

**Issue by luca-borrione** [facebook/flow#7309]
I have a case in one of my reducers which is using merge from immutable Map:
```javascript
case ADD_QUESTION: {
  const { question }: { question:Question} = action.payload;
  const questionMap: QuestionMap = ((fromJS(question): any): QuestionMap);
  return state.merge({ [question.id]: questionMap });
}
```
All is working, and unit tests are fulfilled, however flow complains about something:
`
Missing type annotation for `K`. `K` is a type parameter declared in `Map` [1] and was implicitly instantiated at call of method `merge` [2]. (questions.js:22:14)flow
Missing type annotation for `K_`. `K_` is a type parameter declared in function type [1] and was implicitly instantiated at call of method `merge` [2].
`

I can't figure out how to fix it:
- I saw a similar question in [stackoverflow](https://stackoverflow.com/questions/53347301/unable-to-resolve-flow-annotation-error-when-using-immutablejs-records-and-calli) with no answers. Apparently the same error is thrown when using update and setIn as well
- It appears to be related with a fix landed on 0.85 see [Asking for required annotations](https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8)

**Comment by luca-borrione** [comment]
I am getting a similar error whe using mergeIn too:
```javascript
case ADD_USER_TO_QUESTION_VOTES: {
  const { payload }: { payload:AddUserToQuestionVotesPayload } = action;
  const { authedUserId, questionId, optionKey } = payload;
  return state.mergeIn(
    [questionId, optionKey, 'votes'],
    authedUserId,
  );
}
```

`
Missing type annotation for `K`. `K` is a type parameter declared in `Map` [1] and was implicitly instantiated at call of method `mergeIn` [2]. (questions.js:28:14)flow
Missing type annotation for `V`. `V` is a type parameter declared in `Map` [1] and was implicitly instantiated at call of method `mergeIn` [2]. (questions.js:28:14)
`

**Comment by jbrown215** [comment]
Answered on SO. Flow is asking you to specify an explicit type argument. Here's a simpler example:
[Missing annotation error](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXzDigxACUREAeAFQD4AKASgC54BvMZGOVDV1ZBAjwAPvGoBfANwAoGQDdY8AB7wAvASIlyiJrJkBbHMEEgAdCGUAHHDAwBndSqnwA9K-gBZLPftZUAObwUKioOBjEuPgg3LZAA)
[Fixed](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtXzDigxACUREAeAFQD4AKASgC54BvMZGOVDV1ZBAjwAPvGoBfANwAoGQDdY8AB7wAvASIlyVAM4YYWVAHMGjWTIC2OYIJAA6EMoAOOGBl3qVU+AHpf8ABiWMogwACEQA)
