### ISSUE TITLE
Variables from destructuring assignments seem to be not correctly typechecked.

### ISSUE THREAD

**Issue by Eyyub** [facebook/flow#731]
```js
/* @flow */
var p : string = 'Hello samg';
p = 1; // error, correct                                                                                                     

var {foo} : {foo : string} = {foo : 'bar'};
foo = 1; // no error                                                                                                         
(foo : number | string);
```

I would expect an error in the second case, I believe, maybe, it's because of a difference about how simple variables and destructuring assignments are initialized.

**Comment by mroch** [comment]
btw, if `foo`'s type is still just `string`, the `(foo : number | string);` test will pass.

you should do something like `(foo: boolean);` and make sure you see errors for both `string` and `number` (if it indeed should be a union, but it seems like it should just be string)

**Comment by Eyyub** [comment]
Yes `(foo : number | string);` will pass but `foo = 1;` should not, no ?
This is an example with `(foo : boolean)` : 
```js
/* @flow */
var {foo} : {foo : string} = {foo : 'bar'};
foo = 1; // no error
(foo : number);
(foo : string);
(foo : boolean);
```
```
assign.js:5:2,4: number
This type is incompatible with
assign.js:5:8,13: string

assign.js:6:2,4: number
This type is incompatible with
assign.js:6:8,14: boolean
```
As you see it seems even if there is a type annotation, `foo` acts like if there was not, and `Flow` considers `foo` as a `number` in this context.

**Comment by mroch** [comment]
yeah, I just meant that if you're writing a unit test, it's more useful to test against things it //can't// be, so that the error message tells you what it actually is.

in this case saying `(foo: number | string)` because you expect it to be the union misses the fact that it's actually not the union, it's just number (string was incorrectly lost).

**Comment by Eyyub** [comment]
Oh ok, sorry I misunderstood :/

**Comment by samwgoldman** [comment]
I think we can build an intuition about the expected behavior here through desugaring:

Destructuring:
```javascript
var { foo } : { foo: string | number } = { foo: "foo" };
foo = true; // should error: boolean ~> string, boolean ~> number
foo = 1; // OK, number is a subtype of string | number
(foo : number); // OK, refinement via definite assignment
```

Desugared:
```javascript
var foo: string | number = "foo";
foo = true; // should error: boolean ~> string, boolean ~> number
foo = 1; // OK, number is a subtype of string | number
(foo : number); // OK, refinement via definite assignment
```

Currently, the former does not behave as the latter does, but I think it should. @Eyyub, is this the information you were looking for?

**Comment by Eyyub** [comment]
@samwgoldman Thanks it's helpful, I thought it should have this behavior so now I'm sure !

To keep a trace here, this is what I asked on IRC (with a little more explaination) : 

```js
/* @flow */
var [foo] : [number]; // should have an init but we don't care in this case
```
This declaration calls `pattern_decl` which itself calls `destructuring`.
  Because it's an array pattern, it triggers [Flow_js.flow cx (t, GetElemT(i, reason, tvar))](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L309).
Then, it triggers [number ~> tvar](https://github.com/facebook/flow/blob/master/src/typing/flow_js.ml#L2910) so `number` is a subtype of `tvar` and it ends here(than calls `Env_js.init`).

BUT if we have a type annotation (which is the case here), should we not have `tvar ~> number` instead ?

Because actually, if I well understand, having `number ~> tvar` makes `foo` to have a `tvar` which has `number` as subtype, as `specific` and `general` type at declaration by a call to `Env_js.init_var`.
So to me, it seems logic Flow accepts `foo = 'lol';` because it will trigger `string ~> general_foo_type_tvar` so `general_foo_type_tvar` will have (I'm not 100% sure about this) `number` and `string` as subtype (lowerbound constraint ??) and `number | string` as upperbound constraint ?
And `foo`'s specific type will be `string`.

However, at "pre main pass" we said `tvar ~> number` (which seems logic to me) in my mind there is no more issue.
________________________
That's actually what's in my mind, but it seems wrong, so I would really appreciate if someone can say to me what I have not understand yet(btw, it's not urgent).

Thaanks !

**Comment by Eyyub** [comment]
Any thought ?

**Comment by samwgoldman** [comment]
I think you've traced the execution correctly. `statement_decl` -> `var_declarator` -> `pattern_decl` -> `destructuring`, but I am not sure that's the right place to look.

The semantics that I would like to see would make the following expressions equivalent: `var i: number = 0` with `var [i]: [number] = [0]`, but currently those are distinct. The difference is, as you've noticed, that the former prevents `i` from accumulating more upper bounds, whereas the latter allows it. The latter is, in effect, like `var i = 0` (without an annotation).

The trick, then, is to figure out *why* `var i: number = 0` is different from `var i = 0`. For that, you should look to `variable`, called from `statement`, in the "post" phase, after the `statement_decl` phase. See the logic around `has_anno` (in the latest revisions of that code)? `Env_js.force_general_type` has some nice comments that will give background on that.

The solution to this problem is to ensure the destructuring-annotated declaration form also forces a general type.

**Comment by Eyyub** [comment]
So, after some discussion on IRC with @gabelevi @jeffmo @samwgoldman (thanks guys) I'm resuming and asking a question here.

[For instance](https://github.com/Eyyub/flow/commit/35227871234db1d9723d297a5e5b7b2e5931cc10) : `var {n} : {n : number} = {n:3};`
Here I needed to unify `foo`'s tvar with `number`, so @gabelevi gently told me to see what was going on around `LookupT` which worked perfectly. However, actually, `LookupT` is only for props. So I started to look at `BecomeT` which do a unification and it also worked _but_ before unifying it repositions the reason so instead of having :
```javascript
  4: n = 'foo';
             ^^^^^ string. This type is incompatible with
  3: var {n} : {n : number} = {n : 3};
                         ^^^^^^ number

// We got :
  7: n = 'foo';
         ^^^^^ string. This type is incompatible with
  6: var {n} : {n : number} = {n : 3};
          ^ number
```
We could add something like a `bool` to the constructor `BecomeT` to say if we want repositioning or not, but if it's not already done maybe it's because it doesn't make sense (and GetPropT will reposition also anyway).

So, my question is, do you think it makes sense to use `LookupT` for looking at an array index ? The name `LookupT` is somewhat ambiguous for my cheap english.

Any thought ?
