### ISSUE TITLE
switch statement refinement confused w/ constant variables?

### ISSUE THREAD

**Issue by chrisnojima** [facebook/flow#7310]
https://flow.org/try/#0C4TwDgpgBAglC8UAMUA+UCMaoCYBQUUeAxgPYB2AzsFKQNYBcyCyJF1UARgE70TlMsiDGyo1iAQ3LEIAGwgATJjhb48AMwCu04AEsKUchABuEbgApOTCAFswoAJQBvAL54N24noPrzEpjAOUE4EUJQA7rrAxAAWfkEhhISSlND0DKFJXNwQEnSZUCnQPHwCBYQ8uflZRYVSMvJK5dlVBQoQ6hKassAZWYRGphYSDqFubh46+uRQAOZ+AQmhEVGx8cEFtUh9-ZV5mxKpmDtZe9VJtTgnSWdtHV091wMmZvFjeC5QQA

a simple type `type A = 0 | 1 | 2`

if i use a constant for the cases like
```
const ok: 0: = 0
function f(a: A) {
  switch(a) {
    case ok:
      break
```

flow gets confused (` never(a)
                ^ Cannot call `never` with `a` bound to `b` because number literal `2` [1] is incompatible with empty [2]`)

If i replace the var `ok` with `0` then it refines correctly

```
function g(a: A) {
  switch(a) {
    case 0:
```

**Comment by dsainati1** [comment]
We don't currently refine against variables (even if they are constant) like this. If they really are constant, you can just use the value of the constant instead.

**Comment by chrisnojima** [comment]
thats too bad. the values are generated off of some protocol files so i don't want to hard code them

**Comment by goodmind** [comment]
@chrisnojima this is still bug, why close it?

**Comment by chrisnojima** [comment]
I no longer use flow so I no longer am concerned about the outcome. I'll just unsub

**Comment by goodmind** [comment]
Is this only reason why you moved from Flow or more there was more?
