### ISSUE TITLE
Null check is forgotten when calling method in string interpolation

### ISSUE THREAD

**Issue by rasmusprentow** [facebook/flow#7312]
If you check that type is not null and then call a method with it in a string interpolation or concatenation, then it will not "remember" the type check on following uses in the same scope. 

https://flow.org/try/#0FAFwngDgpgBAwgewLYQDZQB4HkBGArKAYxBgF4YBvYGGHAQwCcAuGAfgoDMEEXWA7AK5IcUBgF9gE4IQR8AziQ50AlqjlkYACgT4WiFOmz4iIAJRkAfJWowGUEAIZ8YOvADp6DGADJvL-B6MblwIPn4ABgAkFHLIUACy9gAWCAAm2gGewdymYtGugQzZCG4gCADKIAzKfADmmrnhksAtMvKKKmoATBoZeHrIaJi4BMTmpFZUNHYOTv7unmHzhcVLsUgJyWl9KyHmANTLWSGlFVU19abN0rIKMADuCAwA1nI95H0DBsPGY5bWNFs9kczgKi18RyCISWUQoYKh3DycMyCIQYiaUmAHAEfGIylkMHWmxAKVSAB59gAVFiCYSiCyaGoQAQgFiU8w0oQiLxTIGzZxMlmSIA

**Comment by jbrown215** [comment]
function calls invalidate refinements: https://flow.org/en/docs/lang/refinements/#refinement-invalidations-

**Comment by rasmusprentow** [comment]
Yes, but it invalidates other properties as well, which simply seems wrong. 

There is a better example here: 
https://github.com/facebook/flow/issues/7315
