### ISSUE TITLE
Where does flow-upgrade list per-version changes?

### ISSUE THREAD

**Issue by kevinSuttle** [facebook/flow#7313]
I was looking at upgrading a repo from v.0.82.0 to v.0.84.0 using flow-upgrade. 
This repo isn't on Babel v7 yet, which means babel-eslint can't grok the `...` inexact Object syntax. 

I decided to do some digging to see if I could write my own codemod, but could not find where the changes required for each version are stored. _e.g._ 

```
1. Adds `...` to the end of all inexact object types.

Flow is changing its object type syntax to be exact by default. See the blog
post at https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf
for details. This codemod will add '...' to the end of all inexact object types.
```

I see where the code accesses the versions, but not where the delta content for each version is specified. 

https://github.com/facebook/flow/blob/41b0eab99cdc5199421f7cccad9e0c4950f8b2f9/packages/flow-upgrade/src/upgrade.js#L47-L59

My guess is a server somewhere, but I wanted to confirm.

**Comment by jbrown215** [comment]
https://github.com/facebook/flow/tree/41b0eab99cdc5199421f7cccad9e0c4950f8b2f9/packages/flow-upgrade/src/upgrades

The `...` codemod hasn't landed yet, but I can make that happen soon!
