### ISSUE TITLE
Function call wrongfully invalidates refinement

### ISSUE THREAD

**Issue by rasmusprentow** [facebook/flow#7315]
When calling a method flow invalidates the refinement even when the the function uses other properties. 

```
type ComplexObject = {
  bar: ?{foo: ?number, foz: number}
  
}

const fails = (obj: ComplexObject) => {
  return  obj.bar && 
              obj.bar.foo && 
              obj.bar.foz &&
               `${someMethod(obj.bar.foo)}${obj.bar.foz.toString()}`
                                                                                  

}


const works2 = (obj: ComplexObject) => {
   return obj.bar && obj.bar.foo && `${obj.bar.foo}${obj.bar.foz}`
}


function someMethod<+T: number>(input: T) : number {
  return input
}
```
Error: 
```
8:   return obj.bar && obj.bar.foo && obj.bar.foz && `${someMethod(obj.bar.foo)}${obj.bar.foz.toString()}`
                                                                                          ^ Cannot get `obj.bar.foz` because property `foz` is missing in null or undefined [1].
References:
3:   bar: ?{foo: ?number, foz: number}          ^ [1]
```

In the example above bar is null or undefined according to flow, but there is no way that the call to `someMethod` would modify the bar property since it only receives the foo property. 
Making it read only also doesn't change this. 

https://flow.org/try/#0FAFwngDgpgBAwgewLYQDZQB4HkBGArKAYxBgF4YBvAH2BhgGocBDAJwC4YB+AEgCUomAEywA7VGAA81egDMECDpxEBXJDigsANAzkAvDirUaqAXwB8wU8GCEEIgM4kZTAJap7ZGAAoE+DohR0bHwiEABKMjNKWhgWKBBlFhEYXzwAOmYWGAAybJT8DNY0uQQcvNTClmKEXTKYAANuCntkKABZeIALBEEfAszqhDCTJoqBvTSQBABlEBYXEQBzL2H64BNrGztHGAB3BBYAa3sAJk8+vH9kNExcAmII0iiKGNj4xOSx1jqvqpK6xoUX6DEZA-pFPQmNYbawyZQiYguOwwFpIdpdHoSegAFQMqnULDMXgWEGUIA42IieKMWRedDiCSSMBJZPWQA

**Comment by jbrown215** [comment]
Flow is very conservative with refinements. Function calls will always havoc refinements in scope, even if the values are not being used in the function.

It's possible to be more precise here, but that's hard and resource intensive. This is not currently on our roadmap.
