### ISSUE TITLE
Shorter syntax for generic variables/constants.

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#7319]
if you need that creates a factory, that accepts only certain types, you can do that with:
```
// @flow
type FooWrapper<T> = (foo: T) => { foo: T };

const createFooCreatorWrapper = <T>(): FooWrapper<T> =>
  (foo: T) => ({ foo });
        
const numberCreatorWrapper: FooWrapper<number> = createFooCreatorWrapper();
numberCreatorWrapper(123); // NO ERROR
numberCreatorWrapper('123'); // ERROR
```
This works fine. However, since `createFooCreatorWrapper` always returns `FooWrapper<T>`, the declaration syntax may be a bit shorter:
```
const numberCreatorWrapper: <number> = createFooCreatorWrapper();
```
This shorter syntax may become very handy, if you need to for example declare a bunch of typed redux actions.

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagGK1gOoBOAhulkQDwAqAfKALygAUk+AXKNQJSP0DeoNrE7VQAXwDciRAGNYAOwDOyULKKYSyTHlgBhDVthFiZCo1A1azbp12nymKnT6JQLYaN4N6zQcIluaXcQkLlFFVAFAFcAWwAjJwNNZGMHCjt8dKdKGISneiZ1FJ18ZKMTUkciG2k8xKJy1MqzJ2YARgAmAGYg0BBQADkAeVAAUQAlCeGJxHqkw2bsmoByLu6VvoHJ6dnQ0MQB+WVVeZbqzs5cuIbCtUXSwiqKDp6gxCA

**Comment by TrySound** [comment]
@vaukalak Do you mean function call parameters?
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagGK1gOoBOAhulkQDwAqAfKALygAUk+AXKNQJSP0DeoNrE7VQAXwDciRAGNYAOwDOyULKKYSyTHlgBhDVthFiZCo1A1azbp12nymKnT6JQLYaN4N6zQcIluaXcQkLlFFVAFAFcAWwAjJwNNZGMHCjt8dKdKGISneiZ1FJ18ZKMTUkciG2k8xKJy1MqzJ2YARgAmAGYg0BBQADkAeVAAUQAlCeGJxAH6pMNm7JqAci7u1b6ByenZ0NDw5VUFlurOi2KtUv0ltKqKXLiG624OnqDEIA

**Comment by vaukalak** [comment]
Thanks.
