### ISSUE TITLE
Empty destructuring assignments should not be allowed.

### ISSUE THREAD

**Issue by Eyyub** [facebook/flow#732]
```js
/* @flow */
var {};
var {} = [];
var {} = {};
var {} = {foo:3};
```
Flow do not throw an error.

I think it can be/should be handle(d) in the parsing step.

**Comment by kkirby** [comment]
According to the [spec](http://www.ecma-international.org/ecma-262/6.0/#sec-destructuring-assignment), an empty `{}` can be used as the left-hand-side expression.

	ObjectAssignmentPattern[Yield] :
		{ }
		{ AssignmentPropertyList[?Yield] }
		{ AssignmentPropertyList[?Yield] , }

**Comment by Eyyub** [comment]
Yes you're right, thanks !

**Comment by kkirby** [comment]
Unless you plan on creating a new issue specifically for `var {};`, then I would keep this issue open since flow doesn't see that as a syntax error. An empty `{}` may be allowed by the spec, but the spec also states that an initializing value is required.

**Comment by Eyyub** [comment]
See #730
