### ISSUE TITLE
Unexpected behavior when accessing property of optional object within .map

### ISSUE THREAD

**Issue by ezhlobo** [facebook/flow#7320]
It disallows to get property of optional object within `.map` callback even if I added a condition around.

```js
type Props = {
  test?: {
    list: Array<string>,
    name: string,
  },
}

const Test = (props: Props) => {
  // Works:
  const first: string = props.test ? props.test.name : ''
  
  // Throws Error:
  const second: Array<string> = props.test 
    ? props.test.list.map(item => props.test.name) 
    /*                                      ^^^^^ */
    : ['']
}
```

[Example on flow.org/try](https://flow.org/try/#0FDAuE8AcFMAIAUBOB7SBnWBeWBvYtZRo1QB+ALl3wNgBsBLEygQUUQENwAeExegOwDmAPgA01Av3YBbaJV4DB4ggF9xKkAGNk-ErAAqxUFlgAKSCnSUkqNAEoswqgW27jAM3qImsBUJMWtgB0RHqksIHoIUZBUrKwlADkidTUrnpo0K4AJixsnDygfEJO2JFo0XoSsOHllaBBDCRB0uyQpvRE0o4RlhWhDXHQDtWUANrJALrAGsAA9ABUwOnGhnrY5n3WfQ6YTqbUXNn0AG7C1Th1A7AAZDdm1QQ8kOz8wpd99bEy0Cpcc2gXm9qnYNDRcFcjLd7pDmk0Gq12p1oN09g9wU9Aa93rDBj8-gCgedwXZQYc5sczsA7MAFnMgA)

However when we assign `props.test` to variable (let's say `test`), it starts working as expected without any error.

[Example with assignment to variable on flow.org/try](https://flow.org/try/#0FDAuE8AcFMAIAUBOB7SBnWBeWBvYtZRo1QB+ALl3wNgBsBLEygQUUQENwAeExegOwDmAPgA01Av3YBbaJV4DB4ggF9xKkAGNk-ErAAqxUFlgAKHISOwVlJKjQBKLMKoFtu4wDN6iJrAVCJkR6pJYkAHRSsrCUAOSx1NTuemjQ7gAmLGycPKB8Qi7YwcYSsKHF4QwR0uyQpvRE0s5hoJEy0E6llADa8QC6wBrAAPQAVMDJxoZ62KaQKOi2C47NeG46esUm8-bhxcCI0KAAroj8ZtRc6fQAbsKlODvoe1YAZK8XNDQ8kOz8wo9li8IlFoCouMM0L9-qUHBovoDdlt3rAnmhga0qq0anUGtAmpgXKZSgQfn8AWiMW1ZODIdD7l8HHDLsNrndgMzRsMgA)

**Comment by ezhlobo** [comment]
While I was going through issues in this repository I found `dump-types` command of flow:

So for the script above it returns:
```js
~/test.js:3:1,8:1: type Props = {test?: {list: Array<string>, name: string}}
~/test.js:10:7-10: (props: Props) => void
~/test.js:10:14,16:1: (props: Props) => void
~/test.js:10:15-26: Props
~/test.js:11:9-21: string

// START first assignment
~/test.js:11:25-29: Props
// Type when condition:
~/test.js:11:25-34: void | {list: Array<string>, name: string}
~/test.js:11:25-57: string
~/test.js:11:38-42: Props
// Type after condition:
~/test.js:11:38-47: {list: Array<string>, name: string}
~/test.js:11:38-52: string
~/test.js:11:56-57: string
// END first assignment

~/test.js:13:9-29: Array<string>
// START second assignment
~/test.js:13:33-37: Props
// Type when condition:
~/test.js:13:33-42: void | {list: Array<string>, name: string}
~/test.js:13:33,15:10: Array<string>
~/test.js:14:7-11: Props
// Type after condition:
~/test.js:14:7-16: {list: Array<string>, name: string}
~/test.js:14:7-21: Array<string>
~/test.js:14:7-50: Array<string>
~/test.js:14:27-30: string
~/test.js:14:27-49: (item: string) => string
~/test.js:14:35-39: Props
// Type within .map callback:
~/test.js:14:35-44: void | {list: Array<string>, name: string}
~/test.js:14:35-49: string
~/test.js:15:7-10: Array<string>
~/test.js:15:8-9: string
// END second assignment
```

**Comment by lll000111** [comment]
That is a known and documented limitation that won't go anywhere soon (that means "away"). You have an inner function for `map`, and Flow auto-assumes anything outside some function is mutable. You have to assign the property to a `const` variable, after the type refinement check, outside the inner function, if you want the inner function to use it without type refinement check.

Or in other words: Your check for `undefined` is in the outer scope, so Flow does not consider it valid for the inner scope because of the default mutability assumption for anything that is a function, no matter how silly that may seem to a *human* observer looking at the code, thinking "but this is synchronous".
