### ISSUE TITLE
uncovered code - possible bug

### ISSUE THREAD

**Issue by albertywu** [facebook/flow#7322]
```js
class Foo {
  a: string;
  constructor(a: string) {
    this.a = a;
  }
}

const ok = new Foo('a'); // ok

class Bar {
  async useFoo(f: Foo) {
    return this;
  }
}

const notOk = new Foo('a'); // expression on the right-hand-side is uncovered
```

Note that the above code compiles properly. My question is why the second occurrence of `new Foo('a')` is uncovered in flow (v0.89.0)? Seems like a bug?

Interestingly, the following changes all turn "uncovered" -> covered:
• remove `async` keyword in Bar
• remove the function params `f: Foo` in Bar
• replace `return this` with `return` in Bar

Can anyone shed light into what's going on here?

**Comment by villesau** [comment]
It's got broken between `0.53.1` and `0.54.0`, no idea why.

**Comment by nmote** [comment]
I've simplified the repro a little bit:

```
// @flow

class FakePromise<T> {}
declare function resolve<T>(object: FakePromise<T> | T): FakePromise<T>;

class Foo {
  constructor() {
  }
}

class Bar {
  useFoo(f: Foo): void {
  }
}

resolve(new Bar());

(new Foo(): number); // Should error
```

This should issue an error, but as far back as Flow v0.37 (the earliest in try) there is no error.

**Comment by nmote** [comment]
Still simpler:

```
// @flow

class Foo {
  constructor() {
  }
}

type Bar = {
  useFoo(f: Foo): void
};

({}: Bar | {});

(new Foo(): number);
```

**Comment by goodmind** [comment]
Unsealed object?

**Comment by nmote** [comment]
No, it has to do with how unions are typechecked
