### ISSUE TITLE
Literal typed object fields admit increment operator

### ISSUE THREAD

**Issue by popham** [facebook/flow#7323]
When I define an object type field with a literal numeric or string type, Flow lets me increment that field, e.g.

```js
type T = { a: 0 };
const t: T = { a: 0 };
t.a += 1; // No error from Flow

type U = { b: "some string" };
const u: U = { b: "some string" };
u.b += "asdf"; // No error from Flow
```

This stands in contrast against plain old variables that do restrain incrementing, e.g.

```js
let v: 0 = 0;
v += 1; // Flow flags this as an error

let w: "some string" = "some string";
w += "asdf"; // Flow flags this as an error
```

**Comment by mroch** [comment]
closing in favor of https://github.com/facebook/flow/issues/7195 since it's slightly broader... `*=` also doesn't work on member expressions. i have a fix in the works!
