### ISSUE TITLE
Failed to load recheck stats error.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#7324]
One of the `flow-typed` maintainers here, we've lately been running into an error that's pretty strange and would love some insight.

We've been getting a lot of `Failed to load recheck stats from "sometempfile". Reason: "File doesn't exist"`.

We get these errors consistently in Travis ([example](https://travis-ci.org/flow-typed/flow-typed/jobs/475567073)). Running the tests locally, we also get these sometimes.

It appears to only be happening for Flow version `0.89`, any thoughts on what could be going on?

**Comment by jbrown215** [comment]
cc @gabelevi

**Comment by gabelevi** [comment]
Yeah, sorry, it's a small QOL issue that I've been meaning to fix. I'll get that message silenced for `flow check` ASAP.

**Comment by gabelevi** [comment]
https://github.com/facebook/flow/commit/034cabe3521045f2fe6c382c06e9a462ac894788 fixes. I'll try and pick it into v0.90

**Comment by AndrewSouthpaw** [comment]
Thanks so much for the quick action! ❤️
