### ISSUE TITLE
missing property typecheck is broken.

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#7325]
For some reason this code doesn't give me an error anymore in `0.89.0` 

```
type A = { x: number };
const a: A = { };
```

Looks like a serious bug. If I switch to `0.88.0` - everything works fine. I don't see any mention for this in release notes of `0.89.0`: https://github.com/facebook/flow/releases
 
reproduce: https://flow.org/try/#0C4TwDgpgBAglC8UDeUAeAuKA7ArgWwCMIAnKAXwG4AoAYwHssBnYKAQ0zkRUqA

**Comment by jbrown215** [comment]
Duplicate of https://github.com/facebook/flow/issues/7287
