### ISSUE TITLE
typeof frozen object property is generic, not literal type

### ISSUE THREAD

**Issue by philippelesaux** [facebook/flow#7329]
In using frozen objects to create enums, it seems the literal value is not inferred to the type of that object's property.

In the following example, when using the $Values utility we get a union of the values, as expected (`'THING' | 'THING_TWO'`), but when using `typeof` to get the type of one of these properties, we get a type of `string`. I'd expect to get the string literal type instead.

```
const ENUM = Object.freeze({
    THING: 'THING',
    THING_TWO: 'THING_TWO',
});

const notAThing: typeof ENUM.THING = 'NOT_A_THING' // no error

const isAThing: $Values<typeof ENUM> = 'IS_A_THING' // Cannot assign `'IS_A_THING'` to `isAThing` because string [1] is incompatible with enum [2].
```

[Try Flow](https://flow.org/try/#0MYewdgzgLgBAogOQKoFkYF4YHkBGArAU2CgDoAzAJwIIC8CAKAbwCgY2YAVACQEkEBxAFwwA5Nz78RAGlbtxAgPocA6lmFjeilVmnMAvgEoA3M2ahIsMCCgBBDgAsAlmADmwqAE8ADgRBl4yCgk8vwYoghYHAo2SpqSMAD0CTBWMAQUFCAUpubQMI4Qdk6uwgAkAGoAhgA2AK4EEAA8nj5+AagAfGEiPADK0bESIonJAMKVYFawlRAQji5gMAAGPf0xISJLMFAgywVFzi5bOESVtRAEMNAUhzAA2gCMALr5EPlgoAC2XpVQjjjVS4Ad0cUHsaTAtU+9wATE8SEA)

Of course, typing each property individually works, but I'd expect `Object.freeze()` to produce the same output. Is there another way around this?

**Comment by gkz** [comment]
Fixed as of v0.238
