### ISSUE TITLE
Removal of gen-flow-files breaks our internal scripts

### ISSUE THREAD

**Issue by nvie** [facebook/flow#7337]
We have been relying on the output of `gen-flow-files` for some of our internal tooling.  We knew going in that this tool was experimental.  By that we assumed that it could contain bugs, but we did not anticipate that it would be taken out completely so suddenly.  `gen-flow-files` definitely served a niche, just like @chixor mentioned in https://github.com/facebook/flow/issues/5871#issuecomment-371647981 already.  At the same time I understand why you want to drop support for it, but it's going to be a pretty expensive investment for us to dive in and rewrite our tooling now — especially given that there's no obvious replacement for it with the same outcome.

Is there a happy medium we could find for this?  Could for example, the `gen-flow-files` tool (as it exists in 0.88) be published to a separately installable npm package?  Or could this be restored until its replacement tool is done?

The lack of this tool is unfortunately now holding us back from upgrading Flow beyond 0.88, which sucks 😞

**Comment by jbrown215** [comment]
cc @avikchaudhuri (deleted in f837fec17686b5f72c01e112694191c32e0d3d3c)

We have a (really good) replacement on the way! I'll let Avik answer your question about adding it back until that replacement is done.

**Comment by nmote** [comment]
@nvie If you would like to revert that commit I'll be happy to look at the PR. I am a bit worried that it will be hard to get it building, since I'm assuming that the motivation for removing it was to land some changes without having to update it. But if you can get it building, I don't see why we couldn't put it back in until we have a replacement ready.

**Comment by chrisdothtml** [comment]
> We have a (really good) replacement on the way!

@jbrown215 any idea when this will happen?

**Comment by jbrown215** [comment]
Nope :\ It's not currently highly prioritized.
