### ISSUE TITLE
Unexpected behaviour with nested maybe types inside if statement when calling another function first

### ISSUE THREAD

**Issue by ovidb** [facebook/flow#7338]
I noticed that flow fails to recognize a maybe type on an object even after checking for it. (with if statement) but ONLY if there is a function call before accessing the property.

I'm not sure if this is expected behavior, and if it is can someone please explain why this is the case?

Here is the example:

```
type L1 = {
    level1: L2
}

type L2 = {
    level2: ?L3
}

type L3 = {
    level3: string
}

const func1 = ({ level3 }: L3) => {
  	return level3;
}

const inBetweenCall = () => {
 	return '';
}

// Works as expected
const noFunctionCallWorks = ({ level1 }: L1) => {
    if (level1.level2) {
      	func1(level1.level2);
    }
}

// calling another function before calling the target function fails
const withFunctionCallFails = ({ level1 }: L1) => {
    if (level1.level2) {
	inBetweenCall();
      	func1(level1.level2);
    }
}
```
No issues when the check is performed on an object that's not nested.
```
// Works
const shallowWorks = ({ level2 }: L2) => {
    if (level2) {
	inBetweenCall()
      	func1(level2);
    }
}
// Same
const destructuringWorks = ({ level1: { level2 } }: L1) => {
	if (level2) {
	inBetweenCall()
      	func1(level2);
    }
}
```
// Playground
https://flow.org/try/#0C4TwDgpgBAMgjFAvFA3gKCpqAbCA3CbOALlgCY0BfNNUScpVDLXA7M0gfhgGYqa60Xo3RYc+Qj1IBnYACcAlgDsA5vzQBjAPZLZUAGYBXJRoTIAFCnFseUSqV4BKJAD4mmAJByIwQ3KXWkgDc6tq6wFDKAEI+AO4QEEoAwgCG2NiM5s6IbqJePn4BAORFIdRoAPQVUADqWnIA1tJQKc0QAB6QGsAQACaaOnpKWgBixt0KOqnpdY3NFlashAj2sHDZucyYCvpQ5ktEAHQHZM6iYlAeRiZw+xJHJ44hYtTlVVAaadjKKi3DwAALCByAzjYCTAIAIwg+nq0E+6R+UEB0GAKTkKh8oJM4J0BhSCmw0gG4SgsQUgLGOIh02wIwJRMyi3uKwc61c7iwOz2Bzgx3uZCgADIhYEHgL+TYzlsuUoYsB4olaVlnhcwnoUoxeZLCGRVWIruNbtrHvq7OpKtVZk0SXppACvlpYtb5ntmWxBasYKcOedtrs7h7pR4PNE4glkl8sjLPNdTIHdU8Za9LVAAMopAC2EFtEV6EFkckM3T8PxdTLFJFQYs9djZGyYoYDj0bobl4aVUccMcuceNAqTL34QA

**Comment by AugustinLF** [comment]
This behaviour is normal and is called [refinement invalidation](https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations). Flow is conservative in its analysis and considers that `inBetweenCall` might invalidate your previous `if-check`.

**Comment by jbrown215** [comment]
What @AugustinLF said 👍
