### ISSUE TITLE
Unexpected throwing of "Cannot cast object literal to `A` because inexact object literal [1] is incompatible with exact `A`"

### ISSUE THREAD

**Issue by nvie** [facebook/flow#7343]
This is unexpected behaviour:

```javascript
type A = {| foo?: number, bar?: number |};
({foo: 1, bar: 2}: A);  // Both provided: OK
({foo: 1}: A);          // One provided: OK
({bar: 1}: A);          // One provided: OK
({}: A);                /* ???
 ^ Cannot cast object literal to `A` because inexact object literal [1] is incompatible with exact `A` [2]. */
```

Can someone confirm this is a bug, or explain why my assumption is wrong here?

See full example on [Try](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeAPqJLLAPwBcoAdgK4C2ARlgE4A0obAhpzqNWHTqFIBfANyIAFMUqx6ARl4DO9AEyT6uAJTTQoEKABCsFAAtQGTrABuASwAmWF-QDyAaXmKqqrp4hsahYSZgngw4do6u7l6+ChqBeiHhYaZRMfbObh6gPn5BBkYZ5camAHJYTtZctrnxBQyWhd7UoAA8gCgEoACq0QAe2ADGKO58WFb8zrBMnIhAA).

**Comment by vicapow** [comment]
This is because `{}` in Flow is an [unsealed object](https://flow.org/en/docs/types/objects/#unsealed-objects-) which acts differently than what you might expect. To get the behavior you're after, you can use something like `{...undefined}` or `{...null}`.

**Comment by vicapow** [comment]
I also just created a ticket to track the discussion around possibly deprecating or removing unsealed objects https://github.com/facebook/flow/issues/7424
