### ISSUE TITLE
Flow doesn't type-check JSX props in plain-function type notation

### ISSUE THREAD

**Issue by Mr-Wallet** [facebook/flow#7346]
If a pure functional component is typed as the following, props are checked correctly:
```
type StatelessComponent<Props> = {
  (props: Props): React$Node
};
```

However with the following typing, invalid props are incorrectly given a pass:
```
type StatelessComponent<Props> = (props: Props) => React$Node;
```

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0uKIigAqAC2RkaRHDQGUyOSaFTCSyAHYBzUACIiKyutDpG6ADTElAE1CjxksiQCu6Slhi3YtsvtjoSiHAE8HoADKOGKU0FIkAMJMmEqUSjgAPAAKBiQAfKAAvKAA3oigoAAUHl4AXKCpniQAlBVUtDgAJABysKaUiAC+ANzcvILCoKawUqBKsHiWEqAylHIKymqa2rqlxhNYoJQAHjhYRHpp2wBu8bMCrioClWkATKBDJNThpjxgfgHBoeEkUTGwOIJFJpTI5EppCpVLw1bKZBp0VrtSh9QrcT7zaEkB45XIAHwKhSURFQlAqJH2S0MhOI2gqSlsqAARo5EHiuqBuDRARTQABZXyRITQUzRDCA+I4CrfHBhCJi2KSkHVO5g4qlWpwvKE9g4WxYJTjWzQaB9LrcRA0aCkMjJIjsBIKiUJbZ7eKmMgInAAOidQKSJ1gyFMmXyhQdHS24LqFA4PoAouFScD8GDQzTQLr9YaihnCokBULkCK-ZK84VxiTKFlciwhCxzRWm7Tq7k7o3m8B0hmaqjQOaukA)

It seems to me that these two types should be more or less totally equivalent. Am I misunderstanding something, or is Flow mishandling the latter case?

**Comment by goodmind** [comment]
Have same error with 
```
import * as React from 'react'

declare function createField<
  Values, 
>(values: Values): <Key: $Keys<Values>>(props: {|
  name: Key, 
  children: (value: $ElementType<Values, Key>) => any
|}) => React.Node

const Field = createField({
  firstName: '',
  lastName: 0,
})

const a = <Field name="firstName">{value => {}}</Field>
const b = <Field name="lastName">{value => {}}</Field>
const c = Field({name: 'lastName', children: value => {}})
```

**Comment by Mr-Wallet** [comment]
My OP doesn't appear to have any problems on the latest version of Flow. I'm not sure what goodmind was expecting but their case seems to be a little more involved and might warrant a new issue if it's still present. It's possible that this issue is closeable.
