### ISSUE TITLE
Cannot Read Type of Contravariant Property

### ISSUE THREAD

**Issue by orlandoc01** [facebook/flow#7349]
Given a class like:
```
class Lambda<-Input, +Output> {
  -input: Input;
  +output: Output;
}
```
I would expect to be able to use the `$PropertyType` utility to read the type of the `input` property on a `Lambda`. However, flow does not seem to allow this with [arrow ]functions, giving the error:

```
Cannot instantiate `$PropertyType` because property `input` is not readable.
```

See the [Flow Error here](https://flow.org/try/#0MYGwhgzhAEAyYFsBGATMAeAtASQHYAcBXAFwBpoBqAeRKOID5oBvAKGmkwEsCSAuaPHQDcbSgHtafaDWLCWAXxbEAnvgCm0AIK5l8ZGmgBeOIlQYwO8heX0RLYGNwRi0TijW5inFUejpY-Nq6pmj0ABQg-LAAlFEhGKIAJAAKAE5i6qkqACqqav7kAOTcdIX0pElpGWpZyrnqBdCFErIkZSyMhowgQkA) for a more concrete example of this. Is this a bug or is there some other principle being violated here? The function isn't reading from this "write-only" property of the instance, so I wouldn't expect flow to error.

**Comment by SamChou19815** [comment]
This is expected.
