### ISSUE TITLE
Optional props doesn't work with declared types

### ISSUE THREAD

**Issue by MikeYermolayev** [facebook/flow#7351]
https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqStZQBeUAClgCMArALlAG8BDAfjoEEAnDxgTwB4cHAJboA5gD4AvgEpi4hogCQHAKbYArh3ShKVAHSMA3IknHE+WKXpCAJnQDkjTDfsAaUIxoBtALruKNABMMsjYPAAOKqAAsrA2KtDECqCKtnSCIqKuiKAp6IwAtirp2MJi2YqeoJzc-Bli4tmSyGhYuAVxCXSx8Ykk9EppoPYAjIEAzG45eYXFw04u2bmVdF6O9n4myBakHb3SiEA

Please take a look at this repro snippet.

Scenario:

We have a function which accepts object with optional property:
`const foo = (obj: {a?: Array<string>}) => obj.a;`

Everything works as supposed when I'm calling function and pass plain object:
`foo({a: ['abc']})`

But things stop work when I'm trying to pass instance of declared type with Non-optional property:
```
const model: Model = {
	id: '123',
  	name: 'asd',
  	a: ['a'],
}

foo(model) // ERROR here. Cannot call `foo` with `model` bound to `obj` because array type [1] is incompatible with undefined [2] in property `a`.
```

If I remove `?` from function expression then error disappears but that doesn't satisfy me as I have cases when property is missing.
Also everything is OK when I use destructuring, e.g:

```
foo({...model}); // OK

foo({a: model.a}) //OK
```

So, looks like a bug.

Thanks in advance

**Comment by AugustinLF** [comment]
It's behaving as expected. What if the `foo` functions removes the `a` property? It would be valid from its point of view, but now `model` wouldn't be a `Model`, which would be an error. To do what you want, you need to type `a` as read-only. You can find more details on how this works [here](https://flow.org/en/docs/lang/depth-subtyping/).

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqStZQBeUAClgCMArALlAG8BqAQwH46BBAJy+YE8APDi4BLdAHMAfAF8AlMUkNEASC4BTbAFcu6UJSoA6ZgG5E004nyxS9EQBM6AcmaY7jgDShmNANoBdTwoaACY5ZGw+AAc1UABZWDs1aGIlUGV7OmExcXdEUDT0ZgBbNUzsUQlc5W9Qbl5BLIlJXOlkNCxcIoSkunjE5JJ6FQzQRwBGYIBmDzyC4tLRlzdc-Oq6H2dHALNkK1Iu-tlEIA

**Comment by MikeYermolayev** [comment]
Oh, totally forgot about read-only properties. Thanks for the answer!
