### ISSUE TITLE
relatedTarget property in the MouseEvent constructor's parameter is badly typed

### ISSUE THREAD

**Issue by julienw** [facebook/flow#7354]
See https://github.com/facebook/flow/blob/f7e2adc834f02f29041b6a6c8e895f3a5a1dcd2c/lib/dom.js#L299 compared to https://github.com/facebook/flow/blob/f7e2adc834f02f29041b6a6c8e895f3a5a1dcd2c/lib/dom.js#L324.

**Comment by jbrown215** [comment]
Feel free to put up a PR to fix. Please link to documentation to make it easier to review.

**Comment by julienw** [comment]
thanks @jamesisaac for fixing this :)
