### ISSUE TITLE
oncontextmenu is misisng from HTMLButtonElement

### ISSUE THREAD

**Issue by jasonLaster** [facebook/flow#7357]
I'm seeing this error: 

> Cannot assign onContextMenu to bp.oncontextmenu because property oncontextmenu is missing in HTMLButtonElement [1].

which is surprising to me because `HTMLButtonElement` has other properties like `onblur` and `onclick`

**Comment by jbrown215** [comment]
Feel free to put up a PR that adds this and link to relevant documentation to make it easier to review
