### ISSUE TITLE
Flow's CSSStyleDeclaration is missing userSelect

### ISSUE THREAD

**Issue by bsmith-cycorp** [facebook/flow#7359]
![table_react_js_ _cyc-ui](https://user-images.githubusercontent.com/25161635/51206383-8b8ac300-18cd-11e9-8256-b89b28e88d61.png)

**Comment by shubhodeep9** [comment]
@jbrown215 I would like to work on this.

**Comment by jbrown215** [comment]
@shubhodeep9: Feel free to put up a PR. This is probably a good starting point: https://github.com/facebook/flow/blob/ef74a645241326a10eba82164feb197eb8f10ac9/lib/cssom.js#L71
