### ISSUE TITLE
Is it possible to remove all maybe fields of an object

### ISSUE THREAD

**Issue by philiiiiiipp** [facebook/flow#7366]
I am using $ObjMap to create a validation object based on an input object. It looks something like this 

```
export type ValidationTemplate<Shape> = $ObjMap<
  InputObject,
  (V: any) => ValidationTest | ValidationSubtemplate,
>;
```

With this I can reliably enforce that every key needs a validation function. However I just noticed that maybe keys:

```
type A = {
  first?: number
}
```

Also end up as a maybe validation function which I do not want because it is now allowed to omit those validation functions. Is there a way to convert all maybe keys of an object to non maybe types? 

I think #7234 is related here.

**Comment by SamChou19815** [comment]
We now have `Required`
