### ISSUE TITLE
$Values causes the object it's called on to lose its types

### ISSUE THREAD

**Issue by clarityflowers** [facebook/flow#7372]
Reproduced on [try flow](https://flow.org/try/#0MYewdgzgLgBAhsKBLcMC8MBmBXMiVgA8AKgFwzQBOSYA5gDQwBqAfABQBQAkFAJ4AOAU3LEOASnJsAbnAA22YczHoWMAN4AfGAGo+QkY20z5ipjA0Bfdd0qCo2SmBjS5C8k2VpVbNdx4DBej9jBW4LMQBuDgsomDj4hMT4jg4AelSYcFleTLBBGH5KECFKPngwABMYbAh8kEwYABImV0EIGABaDpgkWAB3EEoAa3a4dsEADyFEQQqOHDxkVCg2qABGNmU1JJ24jjjQSFgEJch0awSTggBBcivwQgBya4BhYgBJAHkAOQB9a8ejDA2AAtgAjQSUdj7RLPN5fP4AmFxMQwiwpOJ6fLXfDgACycH450anzBACsCfxCFj6vBcZBGIQABqMACa7HuYEkIUUTM8qlZ-Jg7IxMCxMBxp2JLRMEEIkoIlJYMMO0AoAAsQNhZBUAOqDIbkBWoDDbLHkOEfH7-QEwHnkNYwdEq8BqiCa7UVACilCKlCN9Mp518SU5txgj3VglkshAMAGlB1jzR0VFCTSGSgAwKRRKyDaMDB2FgYDjzVa7WAclknW6vXjBtG4ymghmcwW9LFqwATJsLjBVcd6e1Tci6adw5ynq8rYjbcDwZDoUlLQibWOxEFLvSAEJ3enT+HWnfz0EQqGcFcztcnjcpmHi41gIMYEnkynUgK0zkQRks4UcvS3KtOQfIqMKQoii6RwalqOo+n6AanC+-ZxGGFpRjGcYJkmW7xJye7qGKAQWtex62vaMDdk6KbokkY57OkYrZoUxSQvmoyVE0MoKJW1a1j0sAVCAbRgI8-QGgAhPMuCdis0C9ls0Fqj+wZjuh44EIes42kCZ5LpesJkXOG54Whu77qc2k3qei4XgxEbGb8t4JKicTOpiAQSoGhLEqSFKEp+QjfsOf5soBpzASYoGQZByp7J5QjeVKr48W08o+fw8UDq6sDunBeoGkhBDBsR+iOUec6MJRjoeTlMH5Z6CGDMV+K+aO24Thh0axg2iYVIC6kWUR5oVTpJ7VSBVE0e5qbpkAA). 

In `test1()`, the `actions` object has only one property, and we use `$Values`, and we get the error we expected from `shouldError`.

In `test2()`,  the `actions` object has two properties, but we don't use `$Values`, and we get the expected error.

In `test3()`, the `actions` object has two properties and we use `$Values`, and there is no error. What is going on here? It would be one thing if `$Values` was creating an unexpected type, but in this case a type that shouldn't be affected at all is changing.

**Comment by goodmind** [comment]
Similar example

https://flow.org/try/#0PTACDMBsHsHcCh4BcCeAHApgAgMpYLxYDeAPvFlgNQCGAXFgHYCuAtgEYYBOANOVW-QDOSTgEsGAc3gkAvgG5EAEwwBjSNU7YAbhqwZmLQfQAkAeTYArALLU0ogDw5uWewGlnANQB8ACndYPAEoCL2ISKlRMen9KHUgmDHoPLFkvBXhlNQ1tXWpISBMPPITBe0iMaHA9A0E0xEFYUSQVAAssHzzIADpy4KI+FWpBbAAiahHaPgo5DvyuuIT6Aw5OQKmsNk1qAGsFCkHhrBG2CfWZzvnixKxhMUk1igpNjB29rGVwaiZIJEnH9ou5XoGBYaFQgQUMngQA

**Comment by SamChou19815** [comment]
The issue was fixed a while ago
