### ISSUE TITLE
[feature request] remove types using the ocaml binary without npm

### ISSUE THREAD

**Issue by hasenj** [facebook/flow#7373]
Is it on the roadmap to have the type removal be integrated into the ocaml binary? I really dislike npm/node and would like to avoid having to use it. I like that flow is written in a language that compiles to a binary (instead of being written in javascript), but if this binary does not also act as a compiler, then I still have to depend on node/npm. 

This might seem unusual among web developers, but I really dislike the ecosystem around "modern" javascript and would like to have absolutely nothing resembling node.js in my projects.

Is it possible to use the flow binary to remove the type annotation (i.e. 'transpile' flow to plain js) without any npm dependency?

**Comment by hasenj** [comment]
I see, thanks for your response.

Just in case, if someone else worked on this kind of feature, what are the chances of it being integrated into flow (assuming there was no problem with the quality). That is, is it even considered within the scope of what the `flow` command might do?

**Comment by hasenj** [comment]
The use case I had in mind is wanting to have a statically-typed version of Javascript but without relying on NPM.

Now you may ask _why_ do I want to not rely on npm? I have some reasons but at this point it's just going to turn to a philosophical discussion about why having npm/node.js as a dependency is a good thing or not.

**Comment by goodmind** [comment]
There is fastpack pretty printer that uses Flow AST
