### ISSUE TITLE
Property is missing in null or undefined 

### ISSUE THREAD

**Issue by alexgurr** [facebook/flow#7374]
```
function updateLocalPackageTemplate(
  newPackage: ?LocalPackageType,
  packages: Array<LocalPackageType> = PACKAGE_TEMPLATES
) {
  if (!newPackage || !newPackage.custom) { return packages; }

  const newPackages: Array<LocalPackageType> = [...packages];
  const index = newPackages.findIndex(
    (singlePackage: LocalPackageType) => singlePackage.name === newPackage.templatedFrom
  );

  newPackages.splice(index, 1, newPackage);

  return newPackages;
}
```

I get ```Cannot get `newPackage.templatedFrom` because property `templatedFrom` is missing in null or undefined [1].```

I have an explicit truthy check on this so why is it complaining? Can't work it out.

**Comment by alexgurr** [comment]
I saw that function calls clear refinements but I assumed the truthy check before would prevent that being an issue?

**Comment by jbrown215** [comment]
That's precisely the problem :) The truthy check happens _before_ the function call, so Flow "forgets" that information after the function call.

Flow can't prove that `findIndex` doesn't change `newPackage.tempaltedFrom` before calling that callback, so it conservatively assumes it does and errors.

**Comment by alexgurr** [comment]
Makes sense, thanks for your help.
