### ISSUE TITLE
Marking a key as optional in combination with type spread

### ISSUE THREAD

**Issue by philiiiiiipp** [facebook/flow#7375]
It seems as if spreading a type, and overriding some of the key types with optional keys does not work properly.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+qAkNvgFxgDOGATgJYB2A5gDS0Abky4BXALYAjPG1SUAvunoEAQqQrUaAOh2EBdXHgD8TVp15g5isJYDGcLqzCSmasuSFMATJflA

**Comment by jbrown215** [comment]
An optional key with some type shouldn't overwrite a required key with the same type. Think about how this would work with values:

```
type A = {|
	type: string,
	v: number
|}

type B = {|
	...A,
	type?: string 
|}

declare var x: A;
declare var y: B;

{...x, ...y}; // This still has a property `type` with type `string`.

**Comment by philiiiiiipp** [comment]
Ah ok, that actually makes total sense.

 I was trying to find a solution for #7366 without maintaining two types at the same time.

**Comment by jbrown215** [comment]
Ah I see. My knowledge about ObjMap is pretty limited, so I won't be able to help out there.
