### ISSUE TITLE
Help with disjoint unions: possible to narrow with function?

### ISSUE THREAD

**Issue by carmanchris31** [facebook/flow#7379]
Contrived example:

```js
/* @flow */

type ObjTypeA = {| type: 'A', letter: 'a' |};
type ObjTypeB = {| type: 'B', letter: 'b' |};
type ObjType = ObjTypeA | ObjTypeB;

const AHelper = {
  getLetter: (obj: ObjTypeA) => obj.letter,
};

const BHelper = {
  getLetter: (obj: ObjTypeB) => obj.letter,
};

const helpers = {
  A: AHelper,
  B: BHelper,
};

const helperForObj = (obj: ObjType) => {
  return helpers[obj.type];
};

const obj: ObjTypeA = { type: 'A', letter: 'a' };

// Okay
helpers[obj.type].getLetter(obj);

// Errors
helperForObj(obj).getLetter(obj);
```
[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFYAqueAgmALxgDeAPmNvgFxgDk13ANGBh4MGPACcu3AIbcwzAL4BuTFSJlK+AEL0mrdnilaBQkWMk9icxSoPqKahiQf5arZ5rxaVqAMZwAOwBnDDBqAAk8GHxxXUZUMDAAcxEAGTMJLgAKODIuDypqAEp6AD4wXNIAOmFRCX5UZXR-YNCtSOiJOITktIyLHLz7Ty0SunLKmv6Gpr9AkLAACyiYoO7E6i4IlfqerS52nfEZnxaF5c7xADE4cWddQdJ8jSox8vjE8REAV3EApaOQQA2pMDABdFSzM6hSrPFw0OJsKhSPiCWrmKSyMCzYDAIgAa2kWFQF1WILIVXBVRSGHSdXEjyKPlxYAAouJxLcgiSjjc7mRGdS+vTGT5UEA)

Same thing happens with a more 1-1 example:
```js
// ...

const helperForObjType = (type: $PropertyType<ObjType, 'type'>) => {
  return helpers[type];
};

const obj: ObjTypeA = { type: 'A', letter: 'a' };

// Okay
helpers[obj.type].getLetter(obj);

// Errors
helperForObjType(obj.type).getLetter(obj);
```
[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDyARgFYAqueAgmALxgDeAPmNvgFxgDk13ANGBh4MGPACcu3AIbcwzAL4BuTFSJlK+AEL0mrdnilaBQkWMk9icxSoPqKahiQf5arZ5rxaVqAMZwAOwBnDDBqAAk8GHxxXUZUMDAAcxEAGTMJLgAKODIuDypqAEp6AD4wXNIAOmFRCX5UZXR-YNCtSOiJOITktIyLHLz7Ty0SunLKmv6Gpr9AkLAACyiYoO7E6i4IlfqerS52nfEZnxaF5c7xADE4cQL8XSyDLgASAAVxOBjsTwAee7wgm4Bm4pTG5XiiXEIgAruIAksjkEANoGAC6KlmZ1ClXyGkKcTYVCkfEEtXMUlkYFmwGARAA1tIsKgLqtkZN0VUUhh0nVxINSEUfLSwABRcSfcRBFlHG53fH4AVVAxFLl9PkCoXoVBAA)

I tried the `%checks` hint [as noted here](https://github.com/facebook/flow/issues/4390#issuecomment-315413610) to no avail. Is this a bug or not possible?

**Comment by chrissnyder** [comment]
Also curious if a solution to this is possible. My use-case is the helper function partially applies arguments to another function. Possible to do without, but results in more boilerplate.

**Comment by SKHecht** [comment]
I believe I'm running into the same issue. I made a minimal repro of my issue, and its very similar to OP's: 
https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPlAZggXFAZ2ACcBLAOwHMAaKUgE3wHJ44mp0BfAbgChRIUAEIBDYsjSYARmPzkArgFspEYrQbNRxdlz68AxnHJEo8ghFYSAFDjj5WASmQA+bAgB0tvoePBT5rWsZYnwtJyRXAAMAElRg92DOSL0BaFYAeWJAlEtMLT0fEzMLcgBZETAJVF4oWDx-CwRqGuFZBq1mnl4DIyLzDKyxa1tMrXsEUbEHfCIyKhc0FsK-YphyCVWyioBtEcHidwYAXT5a4ghgeWJ1zZsJ-Yc+Lp7fBoGtAGUAd1JgfQALYb3MZ1OCTYjTQgkCiUBbVWoEH5-QF3MH7Q70Bzw2pQfQicxQFgIJj4bE43G9Fb9dYoTblMC7YFiDEnFrk86Xa5vcio8GPNlQTgCvEEphaEmLcm1ZbcjbU+mMtFaFmnKUcq43am8h6q2pCvVPPhAA

In ever possible refinement of the disjoint union, the code type checks (you can see this in the switch statement). However, when you run the exact same code without refining anything first, flow complains. 

I also tried using generics, and get the same issue:
https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAPlAZggXFAZ2ACcBLAOwHMAaKUgE3wHJ44mp0BfAbgChRIUAEIBDYsjSYARmPzkArgFspEYrQbNRxdlz68AxnHJEo8ghFYSAFDjj5WASmQA+bAgB0tvoePBT5rWsZYnwtJyRXAAMAElRg92DOSL0BaFYAeWJAlEtMLT0fEzMLcgBZETAJVF4oWDx-CwRqGuFZBq1mnl4DIyLzDKyxCQAeGCF7BEytZxtJwZDYIQd8IjIqFzQWwr9imHIJXbKKgG1bKbF3BgBdPlriCGB5Yn3D2bhz4gc+Lp7fBoGtABlADupGA+gAFiMxhN3vMZmd5vYlisSBRKBtqrUCKDwVC3h9LvQHFjalB9CJzFAWAgmPhSWTyb0dv19ihDuUwKc5loiTcWoz7o9nv9yAT5l8BVBOFKKVSmFo6ZtGbVtqKDqzOdy4bzrrcVUKni9WeKwvrajKLd8+EA
