### ISSUE TITLE
Error when importing relative paths

### ISSUE THREAD

**Issue by matthojo** [facebook/flow#7382]
### Issue Summary

When importing certain relative path modules I get the following error;

```
[Flow] Cannot resolve module `../<file name>`. [InferError]
```

The file paths that Flow has this error for do exist.

### To Reproduce

```
├── src
│   └── index.js <--- `import * from '../lib/foo'`
├── lib
│   └── foo.js
```

1. Import a module from a different directory in a parent of files directory

I'm not 100% this isn't also caused in other local path patterns.

 **Further Information**

<details>
<summary>Actual directory structure</summary>

```
|-cypress
|  | ... Cypress test files / folder ...
|-bin
|-gallery
|  |-components <--- `[Flow] Cannot resolve module `../lib/filename`. [InferError]`
|  |-data
|  |-docs
|  |-lib
|- node_modules
|  | ... all the modules ...
|-.github
|-lib
|  | ... built files ...
|-flow-typed
|  | ... flow typed modules ...
|-src
|  | ... main code ...
```

</details>
<details>
<summary><code>.flowconfig</code></summary>

```
[ignore]
.*/cypress/**/*
.*/lib/**/*
.*/node_modules/**/*
.*/docs/*

[include]

[libs]

[lints]

[options]
all=true

[strict]
```

</details>

### Technical details:

* Node Version: v9.11.2
* OS: OS X 10.14

----------
Possibly Related: https://github.com/facebook/flow/issues/6960

**Comment by TrySound** [comment]
What is your flowconfig and where do you keep it?

**Comment by matthojo** [comment]
@TrySound thanks for the quick response.

`.flowconfig` is in the root of the project.

This is what we have; 

<details>
<summary><code>.flowconfig</code></summary>

```
[ignore]
.*/cypress/**/*
.*/lib/**/*
.*/node_modules/**/*
.*/docs/*

[include]

[libs]

[lints]

[options]
all=true

[strict]
```

</details>

**Comment by 0rvar** [comment]
The problem could be that the lib folder is in your [ignore] section

**Comment by matthojo** [comment]
**Updated original post**

I've added some additional information on the exact directory structure and config I'm seeing the error with.

**Comment by TrySound** [comment]
@matthojo You ignored lib and flow cannot resolve to it. That's the problem.

**Comment by matthojo** [comment]
@TrySound thanks, I’ll take a look in the morning - I _think_ this may also be happening for files outside of lib.
Out of interest does the ‘lib’ folder exclusion in  the flow config traverse sub-directories? I was only intending it on being ‘lib’ in the project root.

**Comment by matthojo** [comment]
So, I've looked into this again and there are other modules from other areas outside of `lib` causing errors.

```
|-cypress
|  | ... Cypress test files / folder ...
|-bin
|-gallery
|  |-components
|  |  |-isolated <--- `[Flow] Cannot resolve module `../../../src/Filename`. [InferError]`
|  |-data
|  |-docs
|  |-lib
|- node_modules
|  | ... all the modules ...
|-.github
|-lib
|  | ... built files ...
|-flow-typed
|  | ... flow typed modules ...
|-src
|  | ... main code ...
```

**Comment by Poirette** [comment]
I have the exact same problem. I'm not ignoring any folder except stuff in node_modules.

It seems like flow is trying to resolve the module from the root folder of my project. e.g:

`import { User } from '../../../models';`

throws the following error:

`Cannot resolve module /Users/20syl/Documents/models/index.js.`

My folder architecture looks like this:

```
Users
 - 20syl
  - Documents
   - www
    - myApp
     - src
      - module
       - models
        index.js
       - components
        - MyComponent
         - SubComponent
          - index.js
        - MySecondComponent
		 ... etc.
```
My app is very large and has tons of relative imports, which works well. For instance other files are importing the same file but work correctly.

**Comment by aleccaputo** [comment]
also having this issue. Actually it's just when using Webstorm...if i run the "flow" command, the errors don't show up. Also if i control click the reference in webstorm (with the "use webstorm to resolve files" option clicked) it will bring me to the folder...so it can clearly resolve it.

**Comment by mattmischuk** [comment]
Has anyone found the solution to this problem? I’m having this with

```jsx
import image from "./assets/image.webp"
```

however PNG images from the same director work without an error.

```jsx
import image from "./assets/image.png"
```

**Comment by wenbo** [comment]
I have the exact same problem too.

and from the time being the solution to this problem is to use absolute path such as 
import Lib from '/root/absolute/path'

**Comment by SamChou19815** [comment]
Closing since the bug probably has been fixed. There are a lot of reports that might be related to different problems. Without a repro, it's hard to tell what's going on.
