### ISSUE TITLE
Flow indexer property + computed property = check fails

### ISSUE THREAD

**Issue by loysagienn** [facebook/flow#7385]
No errors here:
```js
type RegionId = string;
type RegionName = string;

type Region = {
  id: RegionId,
  name: RegionName
};

type Regions = {
    [RegionId]: Region
};

const regionId: RegionId = 'region_id';

const region: Regions = {
  [regionId]: {
    banana: 500
  }
};
```

[In playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeA5gJZwB2AkgCZgC8YAzhgE5mUkDcmuBxclQByAQwC2BJqw5deffEVIVKjMAG9UYMGVoAuJUJq0ANFrCUJeA4JVjJqAL7zsi21WZrN27QG13xgC6NspUTvIAxh4YYGyhxiFGdGoA5HFGAPq6KZHRsfGJKp5M3mC+6Sp0wRrm2gBGopaWBgCsAAxt5o7hQA)

**Comment by dsainati1** [comment]
Yeah this is a known problem with computed indexer properties; we currently treat them as `any`. This is definitely on my radar though!

**Comment by vicapow** [comment]
consolidating this with https://github.com/facebook/flow/issues/7439
