### ISSUE TITLE
$FlowFixMe ignored when used inside [declarations] file

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#7388]
If I add this configuration to my `.flowconfig` file:

```
[declarations]
.*/dist/.*
```

I get an error in one of the `.js.flow` definitions living in a `dist` folder that should be ignored by a `// $FlowFixMe`.

In practice, if I remove `[declarations]` I don't get any error (`$FlowFixMe` respected), if I add `[declarations]` I get an error (`$FlowFixMe` ignored)

**Comment by ZhangYiJiang** [comment]
I think this is the same issue as https://github.com/facebook/flow/issues/6717

**Comment by FezVrasta** [comment]
Thanks @ZhangYiJiang, you are right.
