### ISSUE TITLE
"Illegal return statement" at top level of Node.js module

### ISSUE THREAD

**Issue by talbenari1** [facebook/flow#7389]
The following code is a completely valid module in Node.js:

```js
return;
```

This is because of the function that wraps all Node modules:
```js
(function (exports, require, module, __filename, __dirname) {
    // code gets "injected" here
});
```

However, Flow hits a parse error and throws "Illegal return statement" for the file. Is there a way to avoid the parse error without wrapping the entire module in a pointless IIFE?

Somewhat related: #6351

**Comment by jbrown215** [comment]
What's your use case for this? Exposing that implementation detail at the type level seems like it adds complexity for little benefit.

**Comment by talbenari1** [comment]
Well, one example would be short-circuiting behavior in a script (e.g. processing command-line arguments) without prematurely exiting the process (a la `process.exit()`) so that other async events can finish.

**Comment by jcready** [comment]
How about:

```js
/*:: (function (exports, require, module, __filename, __dirname) { */
return;
/*:: }); */
```

**Comment by talbenari1** [comment]
Actually yeah, that would solve it. Don't know why I hadn't thought of doing that, thanks @jcready :smile:
