### ISSUE TITLE
Cannot cast to array type when using union + intersection

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#7391]
Works ok:

```
opaque type UserId = string
opaque type GroupId = string

type EntryDetails = (
  | {
      type: 'user',
      id: UserId
    }
  | {
      type: 'group',
      id: GroupId
    }
) & {
  name: string
}

function foo(entries: Array<EntryDetails>) {
  (entries: Array<EntryDetails>)
}
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVcAOBDAjgVwFMwAXAT02IFUBnQgJwEkATMAXjBpPoEsA7AOYYcBYuUpgA4vTj5MLdp278hqccQCifbmQAihEth4waigBSowYAD5gA3patP1ALjAByfHXruANI6cwHmY3WgYWALAAX0dbB0CrVw8BGTk-SKtgt2lZeWZImIBKMAAye0c+bABbQjcuXkFUGNQofD4AYxIeOD4wKDg4M0JtXkIaNwBBenpsMgAeLR19Q2MaAD5i+LAhkZ4xyenZhZG9AyMTDabUIA

Gives error:
```
opaque type UserId = string
opaque type GroupId = string

type Entry = (
  | {
      type: 'user',
      id: UserId
    }
  | {
      type: 'group',
      id: GroupId
    }
)

type EntryDetails = Entry & {
  name: string
}

function foo(entries: Array<EntryDetails>) {
  (entries: Array<EntryDetails>)
}
```
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVcAOBDAjgVwFMwAXAT02IFUBnQgJwEkATMAXjBpPoEsA7AOYYcBYuUpgA4vTj5MLdp278hqccQCifbmUUAKVGDAAfMAG9DRq+oBcYAOT469ewBpLVsD2Z3aDFh5gAL6WphaeRrYOAjJyboFG3nbSsvLMgSEAlOjqYFo6ACKEJNg8MDSK+fS6AGTmlnzYALaEdly8gqghqFD4fADGJDxwfGBQcHB6hNq8hDR2AIL09NhkADxVZEUlZTQAfJn1RlMzPHOLy6sbM1vFpeUHXahAA

**Comment by jbrown215** [comment]
Weird. The only difference here is the use of the type alias. Thanks for reporting!

**Comment by SamChou19815** [comment]
No longer repros
