### ISSUE TITLE
Flow crashes with "Unhandled exception: Worker_failed"

### ISSUE THREAD

**Issue by SimenB** [facebook/flow#7395]
After upgrading to Flow 0.91.0, we've seen the Flow process crash every other build or so on CI with the following error:

```
Worker interrupted with signal: sigkill
Subprocess(363): fail 2Unhandled exception: Worker_failed (process_id = 363): (Worker_quit WEXITED 2)
Raised at file "src/core/lwt.ml", line 3008, characters 20-29
Called from file "src/unix/lwt_main.ml", line 42, characters 8-18
Called from file "src/commands/checkCommands.ml", line 135, characters 27-86
Called from file "src/commands/commandUtils.ml", line 13, characters 4-32
```

See example: https://circleci.com/gh/facebook/jest/46156

Not sure what other details you need. `.flowconfig`:

```
[ignore]
.*/examples/.*
.*/node_modules/metro-bundler/.*
.*/node_modules/metro/.*
.*/node_modules/module-deps/.*

[options]
module.name_mapper='^pretty-format$' -> '<PROJECT_ROOT>/packages/pretty-format/src/index.js'
module.name_mapper='^types/\(.*\)$' -> '<PROJECT_ROOT>/types/\1.js'
module.name_mapper='\(jest-[^/]*\)' -> '<PROJECT_ROOT>/packages/\1/src/index.js'
include_warnings=true
emoji=true

[strict]
nonstrict-import
unclear-type
unsafe-getters-setters
untyped-import
untyped-type-import

[version]
^0.91.0
```

**Comment by TrySound** [comment]
@SimenB Here's similar thread. CircleCI has some problems with workers. Even jest-worker package failed in it. https://github.com/atlassian/react-beautiful-dnd/issues/1007#issuecomment-446415426

**Comment by SimenB** [comment]
Thanks! I'll add `maxWorkers: 1` - it's just lint and flow, so it's gonna be donna way before the actual test run anyways.

**Comment by benjy** [comment]
I'm getting the same error when running inside a docker container both locally and on gitlab ci, the max workers fix doesn't seem to help.

    docker run -v $(pwd):/mnt -w /mnt --entrypoint ./node_modules/.bin/flow node:8 check

**Comment by SamChou19815** [comment]
This is likely fixed in newer versions.
