### ISSUE TITLE
Flow loses type refinment with React.useRef

### ISSUE THREAD

**Issue by debel27** [facebook/flow#7396]
It appears Flow loses type refinement after an assignment to some React ref :

```javascript
/* @flow */
import {useRef} from 'react';

const ref1 = useRef('val');
const ref2 = useRef(0);

if(ref1.current) {
  ref1.current + 'test'; // OK
  ref2.current = 3;
  ref1.current + 'test'; // KO
}
```
The error is : 

```
10:   ref1.current + 'test'; // KO
      ^ Cannot add `ref1.current` and `'test'` because null [1] is incompatible with string [2].
References:
[LIB] ..//static/v0.91.0/flowlib/react.js:322:   declare export function useRef<T>(initialValue: ?T): {current: T | null};
                                                                                                                    ^ [1]
10:   ref1.current + 'test'; // KO
                     ^ [2]
```

You can [try it here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYA3gK4DOApgEqVQC+YUecmYA5HpQIYDGB7ANypUvOADtyRLlACMYALxgKNOgAp2AN24x2ASmFjJ0ugCZFyqrShqADAZHobM2QDpepPF3EE9JVGBgLu6e3kQA1BwElFJCYMDAYADyANIBQWYhXpQ+FgDMwoHBHtm5kezRsYLxiSlJqPRAA)

**Comment by jbrown215** [comment]
Assignments invalidate refinements conservatively: https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations
