### ISSUE TITLE
No errors about function parameter option properties when they are unused

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#7399]
[**Flow Try Link**](https://flow.org/try/#0C4TwDgpgBAysD2AnAhgcwgWXgOwJYMQHkxhccBnKAXigG8AfAKChagGsIIwAlAV2zzZUALigAjePAA2EZNgA0zVjgCiiRElEAKNRsQBKagD4oAN3i4AJotZRIicjgCSlgKrkIlgEIhuEALbwwBCi5MCIuEI2rMiWlgCCAMaJEOTkuGIyABLI5AAWACrwAMLIiXkhUFp5uXmh4ZGohlQmEtKyCkosVgAykWw5+amiMBDAADxhEUJG0Syxli592AO1w1Xx6sggkw0zzSbmVnNQVoRiAFYQicDkPcjBYYTYUiCibTJyjPQAvgDcjEYADN+DcyNhTnhgHAkGhMDh8Egql06CjbGlyCdbHFrGjWECCVjWAB9UlElgAE6p5KgAH2aaSUT8RgQ4VgoUhiKQKIx9KIjpZUSwAPTCqAAOkljB+jCAA)

No errors from this code:

```js
type StorageMonitorOptions = {|
    keepRunning: boolean,
    onError: (Error) => void,
    personIdUsedByRemote: string,
    addAccessibleHashToCache: (hash: string) => boolean,
    idLinkHashes: Set<string>,
    addIdLinkHashes: (Array<string>) => void,
    idObjectsLatestOnly: boolean
|};

function initStorageMonitor (
    {
        sss,
        ddd,
        fff,
        ___,
        äää,
        ß,
        __
    }: StorageMonitorOptions
): void {
  // ...
}
```

Errors will start to be reported as soon as a value is actually used in the function body.

**Comment by SamChou19815** [comment]
Flow now errors on them.
