### ISSUE TITLE
Type definitions for flow-parser

### ISSUE THREAD

**Issue by aushatov** [facebook/flow#7406]
Hi there!
Where can I find actual type definitions for "flow-parser" package? I use this npm package https://www.npmjs.com/package/flow-parser, and i want to use static type checking with "Flow" for result of "parse" function.

**Comment by jbrown215** [comment]
I didn't notice any type definitions in flow-typed. What's your use case? Most tools that I know of that operate on the Flow AST have their own types for it.

**Comment by aushatov** [comment]
My case is autodocumentation tool.
I use "flow-parser" to get Flow AST from project typedef files, and then analize tree and collect some data for generation docs. Parsing and analizing is Node JS code with Flow types, and I want to use result of "parse" as known typed object instead of common Object.

**Comment by jbrown215** [comment]
Ah, that sounds really cool!

I'm not sure that there are any type definitions for flow-parser, but you may want to use recast to do the traversal: https://github.com/benjamn/recast

You can use the flow-parser to generate the AST and visit it using recast in a way that's better than a common Object.
