### ISSUE TITLE
OSS instructions for building the website are outdated

### ISSUE THREAD

**Issue by jbrown215** [facebook/flow#7408]
Following the instructions in our README lead to errors building the site.

This makes OSS contributors have trouble testing their changes, which makes it harder for them to contribute.

**Comment by open-source-explorer** [comment]
Is this issue taken up?

**Comment by open-source-explorer** [comment]
@jbrown215 Is this issue open for new contributors?

**Comment by jbrown215** [comment]
@open-source-explorer: Yes! I will review any PRs that solve this issue.
