### ISSUE TITLE
Refinement with `=== null` and union type doesn't work if referenced

### ISSUE THREAD

**Issue by kangax** [facebook/flow#7409]
https://flow.org/try/#0C4TwDgpgBAQghgJwCrmgXigbwFBSgYwHsA7YCUgLigAoBKKNAPigDdCBLAEwBpsBfbKEixEDKMQCuAGylQAPiOSoA3NmwAzCcXzB2JKAnKcICagCNEVeAno48AentRgAC3YBnKCYSEEnwhLAuAQk7sBQHgBihIRiFghQAIRoGJIyqnhRMVAAZDlQ8QB0RKTkwHQZUMGOzm6eAO6+ANbu1U7xSSni0rJ5BYjFJGSkFfxAA

```js
type BarType = {
  content: () => void,
}
type Bar = null | BarType;

function render(bar: Bar) {
  // this errors out
  const isFoo = bar !== null;
  isFoo && bar.content();
  
  // this works
  bar !== null && bar.content();
}
```

Potentially related issues: 

- https://github.com/facebook/flow/issues/7252
- https://github.com/facebook/flow/issues/7188

**Comment by TrySound** [comment]
This is expected. Refinements are not kept in variables.
https://github.com/facebook/flow/issues/7228#issuecomment-444163399
https://github.com/facebook/flow/issues/4874

**Comment by kangax** [comment]
@TrySound thanks, TIL
