### ISSUE TITLE
Sorting a tuple doesn't invalidate any types associated with specific positions in the tuple

### ISSUE THREAD

**Issue by dsainati1** [facebook/flow#7410]
https://flow.org/try/#0MYewdgzgLgBAhgJwTAvDA2gcgIyYDQwAMAugNwBQiCAdBCAlABQCUFoksUAptDAFwxoCAJZgA5qnhJ0JNuF7doAJn4wwAVwC2AIy7I0VdNjLl2CnlADMqjTr2TDsmAHpnMPQnqn5nCwBZVIVEJA2ljUhc3D3ogA
```
const arr = ['1', 0];
arr.sort();
const test : string = arr[0];
const test2 : number = arr[1];
```

Sorting `arr` should invalidate the 0th position having a string type and the 1st position having number. The right thing to do is probably just to set all the positions to have the type of the union of all the types in the tuple.

**Comment by lexi-lambda** [comment]
This is the same bug as #7222 and #4702.
