### ISSUE TITLE
Flow should have an FAQ page

### ISSUE THREAD

**Issue by jbrown215** [facebook/flow#7411]
The FAQ page should cover (at the very least):
1. disjoint unions
2. refinement invalidation
3. writing HOCs
4. annotating exports

**Comment by AugustinLF** [comment]
I've made the PR #4554 a bit ago. It's not a FAQ, but more of a "common mistakes". I can update it if you'd like!

**Comment by kushthedude** [comment]
@jbrown215 Is the issue still open?

**Comment by jbrown215** [comment]
https://flow.org/en/docs/faq/

Feel free to add more!
