### ISSUE TITLE
Variance sigils are ignored on function declaration type parameters

### ISSUE THREAD

**Issue by mwiencek** [facebook/flow#7412]
Flow version: 0.91.0

## Expected behavior

Flow should check that a function declaration's type parameters are used in proper positions with respect to their variance.

```JavaScript
// These type check!
function f1<+T>(x: T): mixed {}
function f2<-T>(x: T): T { return x }
```

## Actual behavior

Flow ignores variance annotations on function declarations. They do currently work in conjunction with type aliases, however:

```JavaScript
// These error, as expected.
type F1 = <+T>(x: T) => mixed;
type F2 = <-T>(x: T) => T;
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCmAzvmPgE5lxkA0YAhoaQB4AO+AxgC74AmAdKk4BPNmABiARjABeMAB4A1NgB8ACiYAuHAEoZysAFsAlk14BuQSJJiATDPkBaFeq3Zd0-dgsYseIiR44ADsAck4AQlQoAFcgriNgsCgJRWdNHS1jUx4wAG8AXyjY+MSoGzknNXS3VzywMnxOaLIgsCYwQqA

**Comment by wchargin** [comment]
Possibly related: <https://github.com/facebook/flow/issues/6534>.

**Comment by mwiencek** [comment]
Just curious, how come this syntax is being banned?
