### ISSUE TITLE
disjoint unions and functions created inside `if` checks

### ISSUE THREAD

**Issue by kurtgn** [facebook/flow#7414]
I have a disjoint union of two types and an `if` statement that is supposed to run only for one of the types. Everything works fine until I **create a function inside this `if` statement**. After that, typechecking works only if I destructure properties, otherwise it throws errors.

    // @flow
    
    
    export type OpenAction = {
      type: "OPEN",
      platform: string
    };
    
    export type SaveAction = {
      type: "SAVE",
      uniqueId: string
    };
    
    function someReducer(action: OpenAction | SaveAction) {
      if (action.type === 'OPEN') {
        // this creates error
    
        (() => console.log(action.platform))()
      }
      if (action.type === 'OPEN') {
        const { platform } = action;
    
        // using destructured prop does not create error
        (() => console.log(platform))()
      }
    }

Flow version: 0.91.0

## Expected behavior

Not throwing type errors

## Actual behavior

    Cannot get action.platform because property platform is missing in SaveAction

Just have a look:
https://flow.org/try/#0PTAEAEDMBsHsHcBQyCmAPADrATgF1LgJ4YqgDyJAdgIIDGuAlrJaALygDeioBxKAXKABEZAAoBRAHJCANN1AZoAQ1yQcAW0EBnXNgaUA5ogC+AblSYc+IiVABlJQDcUdRszad5NgcLvUAauKy8gCulAwAjiEoAJIAJtq6+kZmyJBh9EwsWrDqKABKKHEhtCjYABRKmcyCFCg01SwAPvZOLo0AlJ48DJCglY0AdN5srOwA5GJS411cPDwgBAAWDFqgtNgoKihrZdg48jzl5V2sAHzrzDnQKINwBgNulIOKKmrY6h0dJ-LG8r39KpPYZ8UYTKaSGbdea0K74DgKZSqDSgYweIFZczzUCLEJaZKgOI7XQlXAhTZxBT7DCE2A7UCUWD4DZbXCkPYHbHHU4XWGUa63e7lV7Ij5fH48P5-IA

**Comment by jbrown215** [comment]
This is a case of refinement invalidation. Flow doesn't try to track how a value might change when it's put in a closure. Instead, it conservatively assumes that the value may have changed.

When you destructure the value, it is no longer part of the mutable object.
