### ISSUE TITLE
Remove unsealed objects

### ISSUE THREAD

**Issue by vicapow** [facebook/flow#7424]
unsealed objects seem to be unintuitive to most users new to Flow. It also seems to be a common source of unsoundness in mature projects.

**Comment by goodmind** [comment]
Probably as lint rule?

**Comment by TrySound** [comment]
@vicapow Do you mean this? https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf

**Comment by vicapow** [comment]
@TrySound I believe that's in relation to exact objects, not unsealed objects but maybe there's some implications with defaulting to exact objects on unsealed objects I'm not understanding.

@goodmind A flow lint rule would be great! But there's still the problem of having to do `{...null}` if you want to create an empty, but not unsealed object.

````js
const a: { foo: string} = {}; // No error?!
````

**Comment by lukeapage** [comment]
Wow finally I understand all the weird bugs!

If you were allowed to assign any property to inexact object, then reading it back would be any but you wouldn’t have to make an empty object be weird in its definition.. wouldn’t that still allow unsealed usage untyped but not lead to many problems for people trying to use flow?

**Comment by nifgraup** [comment]
`{}` could be an exact object in some contexts and unsealed in others:

```
// exact
const foo1: {| bar?: boolean |} = {};
foo1.bar = true;

// unsealed
const foo2 = {};
foo2.baz = 1;
```

**Comment by thecotne** [comment]
this is very important as unsealed objects are common only in facebook code base and no one else is familiar with this concept specially those who want  to have sound type system

**Comment by gkz** [comment]
See https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c
