### ISSUE TITLE
Flow should not restart when modifying the flowconfig file

### ISSUE THREAD

**Issue by vjpr** [facebook/flow#7428]
After any config change, the server needs to be restarted. For me this takes 1 minute of waiting before I can see if the error is fixed.

Also, the majority of these 200K files are `node_modules` that I have to put in `[untyped]`.

So the solution is:

- don't re-run server every time config changes
- allow ignoring all `node_modules` dirs from being looked at, but prevent "module not found" errors.

**Comment by vicapow** [comment]
Thanks for reporting these issues. The second issue was previously reported #5186 so how about we focus this issue on the first?

**Comment by jbrown215** [comment]
Flow needs to know many of the options specified in the flowconfig to:
1. Know what is valid syntax
2. Know what files to parse (and use that information to build a dependency graph)
3. Know what errors/warnings to report
4. (more things that I don't know off the top of my head)

I'm not sure that it's feasible to continue a Flow server after a flowconfig change. There may be certain changes that don't require a restart, but flowconfigs are not edited nearly as frequently as the other files in your project. I don't think anyone on the team will devote time to optimizing this.

**Comment by jbrown215** [comment]
I'll leave this open in case anyone is interested in taking a whack at this.
