### ISSUE TITLE
Cannot declare an interface inside a module definition

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#7433]
Flow version: 0.91.0

## Expected behavior

I expect the following definition to work. But it doesn't. How else can I define an interface inside a module definition?

```js
declare module 'mapbox-gl' {
 	export interface Source { };
};
```

[Link](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaALawoCu0BA5IdgA4BGsAHgLQDm0loA3oqAJBomtWLgAuoAJYA7MWlyRsGAgGVYpXMp6gAvgG5E+oA)

**Comment by avikchaudhuri** [comment]
This should work:
```
declare module 'mapbox-gl' {
 	declare interface Source { }
}
```
