### ISSUE TITLE
React.createRef and correct usage

### ISSUE THREAD

**Issue by neutraali** [facebook/flow#7442]
To my understanding the **React 16** `createRef` API (with support for `.current`) should be working at present. Maybe I'm understanding something wrong but I've tried several different ways of writing the same thing and the [related documentation](https://flow.org/en/docs/react/refs/) is woefully out of date.

I have a [sample TryFlow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nQCQAegRIAwhAB2MLLLgwIcMABs8bYNNTAAJmwB0AV2AGARkZhLpcLKqwh58BCOG4AFsFW7K0gFyYVDAGAHIQ+gA0wmJIACosbBAEcBZWMorIAOZwABSUqFgwEXCoRmYgwDAAlIiuQnYOAPwBqDBQWplRouJw8axwSXAAErEAsgAyGdk5yMWoYMjSxbrAAG41LsLMrM0lbR1dMXASyKqqZngA1nAA7u7ycLiqwLiXHSmW1rXCMhLPr7sZtImDUeAA+OAVAAeWF0dAAvvQ6FgoZBYHB9ARkEZVPAnmh0AAhT7pFFyaS6dDYPDBKTgGROAA8nAg3AhgiEAH1UtYAtT8AZsARGWQeTIyGC3DJWlAjPhoDkwFxUAEWdwahyhKVWFBFcqqvQhEIYJ5UAZuSSbHx+cFcJRkHIhTkDcJ4cJWg6XhisFicTA1bwBMJ6vYQAFRZayF1jQlw2LpFHg79-pcAs64OCBG6hIjhJz3ItdPY-i9rnwclhVk4AosQRn2cHgMkcgBlfbSTI5E3AM0WtLSAy4IxQXy29SoVAhZCOKoGLT6KEAeQIOTIK1QyDM9l0ZFBPD4AFoAIwa4NCJu5ACE3d78cHw9HBgAjkYsFAmC2GvLdWQDI5pEYu6nkaRo3uad5DiOTjmKow7OoaRrZkaF5dgkgxgUqrJmsmpYZvu5AEEY0j4MA4rASBGHKgYOGvBWVayC6IFIdmuZCL4+i6uRKGUVhBgNKQl74RG-a7kGIH6PYciKKaBiYdwBjbFgCFIZQMDDjYORniIIhwAAJAAYqoEA3PpwBQqMbAnNI0gQPAlAEG+8hsIp5A3mQcBECQKBwKspyvioEA6DApHSI0Z6Mjx8n8QIBixXJqDwgM0glq8PD8GB+aFsWKaJfZaUZfG8KSiBQjpTJ8WDp43i+EhQiMiIkVmvxxVCIxbpukAA) here and I'm unsure what I'm doing wrong. I want to define a `<button>` -ref with **React.Ref**, but that ultimately results in:

` Cannot get 'this._button.current' because property 'current' is missing in 'String' [1].`

I've tried variations of:
```javascript
_button: React.Ref<'button'>
_button: React.Ref<HTMLButtonElement>
_button: React.ElementRef<'button'>
_button: React.ElementRef<HTMLButtonElement>
```
... And no luck. At this point I don't really know which variation is even _supposed_ to work. Using `flow-bin` **0.92.0**.

**Comment by TrySound** [comment]
@neutraali Look at what createRef returns
https://github.com/facebook/flow/blob/master/lib/react.js#L240
```
  declare export function createRef<T>(
  ): {current: null | T};
```
It's not React.Ref.

Here's fixed example
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAArFjoC8cA3nQCQAegRIAwhAB2MLLLgwIcMABs8bYNNTAAJmwB0AV2AGARkZhLpcLKqwh58BCOG4AFsFW7K0gFyYVDAGAHIQ+gA0wmJIACosbBAEcBZWMorIAOZwABSUqFgwEXCoRmYgwDAAlIiuQnYOAPwBqDBQWplRouJw8axwSXAAErEAsgAyGdk5yMWoYMjSxbrAAG41LsLMrM0lbR1dMXASyKqqZngA1nAA7u7ycLiqwLiXHSmW1rXCMhLPr7sZtImDUeAA+OAVAAeWF0dAAvvQ6FgoZBYHB9ARkEZVPAnmh0AAhT7pFFyaS6dDYPDBKTgGROAA8nAg3AhgiEAH1UtYAvxHkYoL4YAFqfgDABReyOWTYAiMsg8mRkCEAHzg0hxqjg8LcMlaUCM+GgOTAXFQARZ3BqHKEpVYUFN5qq9CEQhgnlQBm5JJsfDFwVwlGQcjlORdwl1dpgIZeGKwWJxMCtvAEwnq0oCit9ZC67oSWaV0lz6d+-0uAXDcHBAijiOEnPci109j+L2ufByWFWTgCixB1fZ6eAyRyAGV9tJMjkPcAvT60tIDLhBcLl+pUKgQshHFUDFp9FCAPIEHJkFaoZBmey6Mignh8AC0AEYbemhCPcgBCWfzovL1cnAMABHIwsCgJgxwaY1HTIAwZSMO83zdN1f29f8VyFIDr0FcNXTdKM3U-GcEkGNCzVZL0y3basH3IAgjGkfBgGVZCUPI80DGo14ux7WQIxQwi61dXx9EdNjiI4yiDAaUgvzo7NFzvNMUP0ew5EUT0DAo7gDG2LB8MIygYEFGwcnfEQRDgAASAAxVQIBuWzgChUY2BOaRpAgeBKAIcD5DYfTyF-Mg4CIEgUDgVZTjAlQIB0GAWOkRp30ZKTdNkgQDGynTUHhAZpDbV4eH4NDG2bVty3y3ySrKot4TBd8hFKrTcuXTxvF8QihEZER0q9WTGrdATdV1IA

**Comment by neutraali** [comment]
Thanks for the fast reply @TrySound - Sorry if this was one of the more trivial "issues". Personally I think updating the docs section concerning this would help many of us whose first instinct is _not_ to sift through the source code. 😸

**Comment by TrySound** [comment]
@neutraali Would you like to submit a PR?
