### ISSUE TITLE
Generic constraint is ignored when used in contravariant position

### ISSUE THREAD

**Issue by tntmarket** [facebook/flow#7446]
```
const A = <T: 1>(f: T => void) => {};

// passes, but should fail
A((_: 'bad') => {}); 
```

Flow version: 0.92.1

## Expected behavior
Flow complains that the passed-in function has the wrong argument

## Actual behavior
Flow does not complain

## More test cases

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAxnAdgZwC5gCCYAvGADwAqAXGAIwB8AFFLZaQ2AG5wCWAJgEoOYAN4BfANypUwYGAAOAQxw4ApjgA0YAEYBXAjgAWcPTH5goS3jFSEmTAPq0A5DqX8XwkpwmDJYDJyiirqWmAqYGoAHgpq6Hhq-HYOzvTevuL+Mpi4BABCpBQ09MzRbBliUkHyVjbhkTFxCUmo+UxuHl7SGNj4YADCRVS0jEzlYOw+k5USPcF1MOH6BNgwAJ5gmAC2CjDWuBE6pgR4RmpgAE5qeHqXWNxKMHpqqAOpru6elZ3fkkA

## Why I want this to work

I want to type a higher order React component that injects props. I want flow to warn me when the inject props don't match the component being enhanced:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYBAntqWAMJw5wB2pvAgBVWpOizZgAggCMAzgTxUCXHv0FgAvmCh5uYAOR4K1AwG5UqSnwVgAEgHkOYALxgAPF15R0AcwBcDGAAHoEKeOi8vloAfAAUqGBJnNy46gSBsuHKqmkCBJ58Pr4xqACUrjEMmhZWNkS5fPmuYHHYethygYyhYLwArpgypHhaFS5V7gAm6ABuYMAxFskryXW8tgCivAAW5LyUpFMtjhxxjellZgvAYADqO8xgU3Ckckw76O+8cETWODByJEAPxAA

**Comment by wchargin** [comment]
`T` is being inferred as `empty`.

Your function type `("bad") => void` is a subtype of `(empty) => void`.
In turn, `empty` is a subtype of `1`, so `f: (empty) => void` can be
passed to `A<empty>`.

If you instead write `A<"bad">((_: "bad") => {})`, then Flow _does_
raise an error as you might expect.

In your React example, `Component` is an `AbstractComponent<empty>`, and
so `HOC<empty>(Component)` is perfectly valid.

This looks sound to me.

**Comment by samwgoldman** [comment]
@wchargin is right on here. One hint is that the program doesn't actually have a runtime error.

That said, I think there's a lot of room for Flow to be more helpful in this case. In the `f` function, the type parameter `T` never appears in an input position and thus never has the opportunity to be anything other than `empty`.

**Comment by tntmarket** [comment]
I see, thank you for the help.

I had a misunderstanding where I believed flow would pattern match `T` against the argument at the place I called `A(...)`, but I see now that it infers a type that fits in the constraints of the argument and definition.

My original issue was more like this: 

```
/* @flow */
import React, { type ComponentType, type AbstractComponent } from 'react';

const injectMaybeX = <Config: { x: ?string }>(
    Component: AbstractComponent<Config>
): AbstractComponent<$Diff<Config, { x: ?string } >> => 
    props => <Component {...props} x={null} />;

const TrimX = ({x}: { x: string }) => <div>{x.trim()}</div>;

const Enhanced = injectMaybeX(TrimX);
          
// I think this errors, cause it attempts to .trim() null?
<Enhanced/>;
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYBAntqWAMJw5wB2pvAgBVWpOizZgAggCMAzgTxUCXHv0FgAvmCh5uYAOR4K1AwG5UqSnwVh0vAFalqAWXLMZpABpgAvGAAeLl4odABzAC4GMAAPKIB+BTx7MK0APgAKVDAczm5cdQIo2STlVQKBAiC+ULC01ABKYvlFMvy+SoCAEgARdCgoapDwukY4sETFFK0wNLS-eezc7D1sOQXA8o6NegA6fZW4Ne0Y33peAFcYGG1gNIsrGyIhZMwffwz6GM0osaik6aaBobAIAE3QADc0l9dlNMBkGpoAsBwVCHtZeLYAKK8AAW5F4lFIoL8dkczgIbg83gyLywXgaFlyzNyqGAwDAAEkmLj7ABrHnodakPB6PByOiUcgXOTsdBEcgEAikHAEdYEOBgWGvBFgS7XeJAA

But I mistakenly stripped it down to a non-representative test case. I'll rename the issue.
