### ISSUE TITLE
Can't return anything when returning Class<T> and T is a union

### ISSUE THREAD

**Issue by quentinvernot** [facebook/flow#7449]
Flow version: tested with 0.89.0 and 0.92.1

With this code:
```js
type MyUnion = ArrayBuffer | Uint8Array;
function foo<T: MyUnion>(x: T): Class<T> {
  if (x instanceof ArrayBuffer)
    return ArrayBuffer;
  return Uint8Array;
}
```

2 errors occur:

```js
6:   	return ArrayBuffer;
             ^ Cannot return `ArrayBuffer` because `ArrayBuffer` [1] is incompatible with `T` [2].
  References:
  [LIB] ..//static/v0.92.1/flowlib/core.js:647: declare class ArrayBuffer {
                                                              ^ [1]
  4: function foo<T: MyUnion>(x: T): Class<T> {
                                           ^ [2]
```
```js
7:   return Uint8Array;
            ^ Cannot return `Uint8Array` because `Uint8Array` [1] is incompatible with `T` [2].
  References:
  [LIB] ..//static/v0.92.1/flowlib/core.js:722: declare class Uint8Array extends $TypedArray {}
                                                              ^ [1]
  4: function foo<T: MyUnion>(x: T): Class<T> {
                                           ^ [2]
```

Interestingly, the function still works as intended when called:
```js
(foo(new Uint8Array([])): Class<ArrayBuffer>); // Error, which is normal, we want that
(foo(new Uint8Array([])): Class<Uint8Array>); // Success
```

Here is a [Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAqgHYCWcZYAvGAIIBOTAhlgEICuUUeTYAD5gSFMhgAczNlgDcqKFzIBjDFRpQ4cADwAVAFxFSlagD4AFAA9DugJSGAwjFYBnF3tNgA3qjBgKUGBW-mQuGKwqeHCB0uzcvPy2vmAAkEx4GFxMNLGcPHxM8n7pmdkiYpK58gC+6OaacOZkeEii4lIs7OYA2gC6tvZgTq7uufEFprayYMDAYACiLHBMqPVaTS3l7bk9-YPDbtptlZ1Yk9OzYADKXMrKeG5AA) link if you want to have a look.

I've seen a few similar looking issues where there is a `Class<T>` and `T` is a Union type, it looks to me like flow wants `T` to be a `MyUnion` instead of being a type that fits this union. Did I miss something? Maybe there a `$OneOf<MyUnion>` utility function somewhere that could help?

**Comment by quentinvernot** [comment]
It looks like it has nothing to do with `Class<T>`. Generics typed with a union seem to be the cause. Here is a smaller snippet:

```js
class A{};
class B{};

const foo = <T: (A | B)>(x: T): T => (x instanceof A) ? new A() : new B();

(foo(new B()): A); // Error, which is normal, we want that
(foo(new B()): B); // Success
```

[Try-Flow link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQQG8BfAbkx3zACEzLM4A7XAFzCjjjAF4wAPABUAXGAAUhMAB86ASgB84gB5ihctXwUTlYAJas22ZhgCmcKETlgA-GGamkhcdbEOktF43Fc4493QuGlbkYMDAYACiAE7RcNEANGAIABZ6GCn6BMzxALbYMEkIpsnGHGwp2GyoPtz+joFywbRyoeFgAMoArhhm+EA)

**Comment by dsainati1** [comment]
This is an error because you are saying that your function returns something of the same type as its input, but this is in fact not the case. The annotation `T : (A | B)` means that the function is generic over any `T` that is a subtype of `(A | B)`, and you want it to return something of the same type as the `T` you instantiate it with. However, the function as written only ever returns `A` or `B`; no matter what `T` is. So if `T` is an instance of some class `C` that subclasses `A`, you won't return ` C` from your function as required by the type signature. This is why you have a type error here.

**Comment by quentinvernot** [comment]
@[dsainati1](/dsainati1) My bad, shouldn't have used classes. Let's try that again. Here is an even smaller example:

```js
const foo = <T: string | number>(x: T): T => '' + x; // No errors, probably shouldn't fail before someone calls it anyway

(foo(4): string); // Fails because it expects foo<number> to return number, not because foo is wrong
(foo(4): number); // There should be an error caused by this call
```
[Try-Flow link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjjAF4wAeAFQC4wCAnAS2wHMwAfMbAVwFsARgFNGAPgAUAD3rUAlLPJiwAcgCGKsAGowUgNxhgwMADlSoxnEa4ANGAAOlwWsEwAngwAWcXjAAm2CqEUGrMMGAixIzCDHD8wjgxGGowMLhgzIRq2G4Iam7oEsRwEgAsCgz4LOxyBkZgAGKhaRHCyby4MZlgwlL2bfjpxZR8QqLK+KTR+LyM2DwCIox22HCEIu2dRCQZ6QiW7KhFJGUVo0u1hsbUnqIxuN6+fq1g2T2Mloxgm8LPgh74TzMdLJVJAA)

I'm mostly wondering why flow doesn't freak out; it does react when [only returning empty string](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjjAF4wAeAFQC4wCAnAS2wHMwAfMbAVwFsARgFNGAPgAUAD3rUAlLPJiwAchUBuIA) or when [removing the `string | number` constraint](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzCjjjAF4wAeAFQD4AKADwC4xqBKV682sAcj5gA1GEYBuIA).

**Comment by dsainati1** [comment]
The logic above still applies. If `foo` is instantiated with `empty` as `T`, returning a string will cause your function annotation to be a type-error, since `string` is not a subtype of `empty`.

**Comment by quentinvernot** [comment]
Exactly, and if you call `foo()`, flow does emit an error and everything is fine. If you call `foo(4)` however, flow seems to think the function will return a number somehow.

`foo` doesn't abide by its own contract, it can't, and flow doesn't print an error to tell about it. Returning `''` instead of `'' + x`, will make flow print an appropriate error. Removing the constraint on `T` will also result in the expected error.

**Comment by dsainati1** [comment]
Ah I see what you are saying. The issue here is that Flow doesn't infer generic types, so we defer the error until `foo` gets used in an incorrect manner.

**Comment by quentinvernot** [comment]
Yeah, I figured trying to guess what a generic was going to end-up being before seeing a call could very easily turn into a giant halting-problem-shaped headache. But it looks like, when a generic is typed, flow tries.

Here it ends up typing the generic argument (`x`)  with whatever the constraint is (`string | number`), it then sees `'' + x` and interprets it as `string + (string | number)` and stop there since it can't solve this without any additional info. We *know* `'' + x` will always return a string, but all flow sees is a `BinaryExpression` between a `string` and a `string | number` and someone wisely chose not to try all branches.

So... is there a way to ask flow to delay the typing until `foo` gets called and it has all the information? Like some kind of `$ExactlyOneOf<string | number, T>` utility type? `$Keys` and `$Values` seem to create unions, but I can't see how to break them apart or assemble them selectively.

**Comment by dsainati1** [comment]
I don't know exactly what your usecase is, but perhaps you are looking for function overloading? Something like defining 
```
declare function foo(x: number) : number;
declare function foo(x: string) : string;

(foo(3) : number);
(foo("string") : string);
(foo(true) : bool);
```

**Comment by quentinvernot** [comment]
Hey! I didn't know you could declare something twice with different types, neat. I'll see what I can do to apply it (lots of things to type). Thank you!
