### ISSUE TITLE
remove esproposal.export_star_as from config

### ISSUE THREAD

**Issue by dnalborczyk** [facebook/flow#7451]
`export * as ns from` ~was recently added~ will be added to the ecma spec fairly soon.

this option can be removed from the code base as well as the website:
https://github.com/facebook/flow/blob/master/website/en/docs/config/options.md#esproposalexport_star_as-enableignorewarn-

additional info: https://v8.dev/blog/v8-release-72#module-namespace-exports
https://github.com/tc39/tc39-notes/blob/master/es9/2018-09/sept-27.md#normative-add-export--as-ns-from-mod-contd

_edit: I suppose it's not quite added JUST yet, but there shouldn't be anything in the way. TC39 is only waiting for implementers._

**Comment by mroch** [comment]
this option was deprecated in 0cc18c2499ab91ecc25a15153882fe1b2b5cbc4c and removed in 3ab812f3893a7687eaa8ad030ab89273b7e3542f!
