### ISSUE TITLE
website: Font size too big especially on mobile devices

### ISSUE THREAD

**Issue by open-source-explorer** [facebook/flow#7453]
Check out the [reponsinator view](http://www.responsinator.com/?url=https%3A%2F%2Fflow.org%2F) demonstrating overall apperance of the webite across various devices.

> It becomes weird especially in the landscape mode.

**Comment by jamesgeorge007** [comment]
@jbrown215 I would love to work on this :clap: Do you have any sort of intentions on how it should be refactored :thinking:

**Comment by jbrown215** [comment]
@jamesgeorge007: Nope! I have no design knowledge or preferences. I'll happily review, though

**Comment by DHvyas** [comment]
> Check out the [reponsinator view](http://www.responsinator.com/?url=https%3A%2F%2Fflow.org%2F) demonstrating overall apperance of the webite across various devices.
> 
> > It becomes weird especially in the landscape mode.

I haven't checked the code but I am guessing the CSS for the font size must be in terms of vw (view-width). Changing it to REM should fix it.

**Comment by nicollbryla** [comment]
Hi.👋🏻 I’d like to solve it.

**Comment by Adityaintel** [comment]
Can I work on this if it's still open?

**Comment by SamChou19815** [comment]
The new website should have fixed the issue.
