### ISSUE TITLE
Flow does not infer that generic types cannot be different

### ISSUE THREAD

**Issue by JakubRimal** [facebook/flow#7454]
Flow version: v0.92.1

## Expected behavior

No errors.

## Actual behavior

Error "Cannot call `bar` with `param` bound to `prop` because string [1] is incompatible with null [2]."

## Step to reproduce
```javascript
/* @flow */

type TOptions = { prop: string } | { prop: null };

function foo<T: TOptions>(param: $PropertyType<T, 'prop'>) {
    bar<$PropertyType<T, 'prop'>>(param);
}

function bar<TProp>(prop: TProp): TProp {
    return prop;
}
```

I would expect that Flow would know that T is either { prop: string } or { prop: null } and thus $PropertyType<T, 'prop'> has to resolve to the same type (both string or both null) in both places -  in param type and in generic type passed when calling bar.

See it in [Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqA8jhgJZwB2AzmALxgDeYOATnDgFxg0ZvkqAczABfMAB9mrDtzBUArjBhiA3OigKqAYwrUwUOHAA8hHiTKVaAPgAUOAIZsHAWx4ASAAqy8bbIVw8UwAaMABydk4w6wBKZlQwRLAAIydjLx8-LAD8EPDInGi7R2cXGPVRDS1dKxS0wm9OYtlzRpwY1tl4pLA2PAwFNioZTgqgA).

**Comment by dsainati1** [comment]
Flow doesn't infer generics. It will, however, do the right thing if you don't unnecessarily constraint `bar`; functions don't require explicit type arguments to instantiate: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqA8jhgJZwB2AzmALxgDeYOATnDgFxg0ZvkqAczABfMAB9mrDtzBUArjBhiA3OigKqAYwrUwUOHAA8hHiTKVaAPgAUOAIZsHAWx4ASAAqy8bbIVw8UwAaMABydk4w6wBKZlQwRLAAIyd7J1cY9VENLV0rFKdTb047SLlCEpwY8yr4pLA2PAwFNioZTmygA

**Comment by JakubRimal** [comment]
Ok, thank you for the info and the advice how to solve my example.
