### ISSUE TITLE
Unexpected reserved type in typeof _ 

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7461]
Flow version: 0.92.1

```js
declare var _: number
type A = typeof _
```

## Expected behavior

No errors

## Actual behavior

```js
2: type A = typeof _ 
                   ^ Unexpected reserved type
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0CYUwxgNghgTiAEA3W8D6AueA7ArgWwCMQYAoAFwE8AHBAQXgF55KaB7AMzRKA

**Comment by Bannerets** [comment]
Regression in v0.84.0.

**Comment by goodmind** [comment]
Same error with any other reserved type
```
declare var PropTypes: {any: string}
type S = typeof PropTypes.any
```
```
2: type S = typeof PropTypes.any                             
                              ^ Unexpected reserved type
```
https://flow.org/try/#0CYUwxgNghgTiAEA3W8AKMD2AHAKgTyxAGcAueAbygDs8yiAXGASyoHMBfAKHoIQGV4AXng9CGAGZpMuXkQB01PJyA

**Comment by yuyao17** [comment]
Is there a workaround for this?

**Comment by goodmind** [comment]
@yuyao17 renaming variable

**Comment by goodmind** [comment]
Better example if Flow implements https://github.com/tc39/proposal-promise-any
```js
declare class Promise<+R> {
  static any<Elem, T: Iterable<Elem>>(promises: T): Promise<Elem>;
}

type F = typeof Promise.any
```
```js
5: type D = typeof Promise.any                           ^ Unexpected reserved type
```
