### ISSUE TITLE
React higher order component by-passes null check when injecting optional prop

### ISSUE THREAD

**Issue by tntmarket** [facebook/flow#7466]
My React component accepts `string`. It complains as I'd expect if I pass `null`, but it does not complain if I pass `null` via a higher order component.

```
/* @flow */
import React, { type ComponentType, type AbstractComponent } from 'react';

// This higher order component injects an optional string
const injectMaybeX = <Config: { x: ?string }>(
    Component: AbstractComponent<Config>
): AbstractComponent<$Diff<Config, { x: ?string } >> => 
    props => <Component {...props} x={null} />;

// This component accepts just a string
const TrimX = ({x}: { x: string }) => 
    <div>{x.trim()}</div>;


// This fails, like I expect
<TrimX x={null}/>
 
// I think this fails during runtime, but there is no type error?
const Enhanced = injectMaybeX(TrimX);
<Enhanced />
          
// This fails as I'd expect though
const EnhancedWithExplicitType = injectMaybeX<{x: ?string}>(TrimX);
<EnhancedWithExplicitType />
```

Flow version: 0.92.1

## Expected behavior
Flow complains that `TrimX` does not accept `null` when I create `Enhanced`

OR 

Flow warns me that I might want to explicitly declare the generic type

## Actual behavior
Flow does not complain

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuYASgKYCGAxgQDRgDeYBAntqWAMJw5wB2pvAgBVWpOizZgAggCMAzgTxUCXHv0FgAvmCh5uYAOR4K1AwG5UqYMDBCAFujlgHAczuk8YfABMPYSty46kTovABWpNRO5Lxe2ATofOQwYAp4oS6oAbwKYKER1ACy5MwypAAaYAC8YAA8XLxQ6C4AXAxgAB5tAPxpGVoAfAAUqGBjnIF8AgRtsmnKqkHT9XxNLgOoAJSz8ooLk8G1ACQAIuhQUCuNzXSMXWC9iv3aAwPVb6Pj2HrYTlVvKzU0wYADowd84L9tB0qvReABXGAwbTAAYWKw2eyOfwHYFUSikeJOMLw3LkVJPXiZbK5ITpTCVGpDegdTRtO5tPpUrSbd5gT5jWredAANwGLJBT0wQ02mlqwGFYvR1lsDicUHI6BgcjoMHQAGt2ABJMCkDpsaioWp0rCVGFwxHI1GjDFgADqdmYYG8cFITgIarAvDgRA1WqYcDg3SyfFyAFFeHYYgTvNU8uFIgRiqUKkMbQzNhZagmk7wU2BneMq+NXVj1ZrtWByE4jQZU2aLUQA3B4W4YzkiCXk6RvG70AG4+a9ZRxyJJDV8pns2VyrUWT0uS5NMN8+VC1ah2WR2OJ1P0DPhKIKwMgA

## Notes/Thoughts
* I originally thought the problem was (https://github.com/facebook/flow/issues/7446)

**Comment by jbrown215** [comment]
This is a known issue that we are working on. Unfortunately, it's not a simple fix.

It's particularly nefarious because it doesn't even ask for an annotation when it's exported.

(cc @avikchaudhuri: another example of what we were discussing last week)

**Comment by SamChou19815** [comment]
Flow now complains about this.
