### ISSUE TITLE
Missing type annotation for call of `compose`.

### ISSUE THREAD

**Issue by amccloud** [facebook/flow#7468]
Flow version: 89.0

## Expected behavior

More information about missing type annotations or documentation on `$Compose`

## Actual behavior

Can't export composed functions

* Link to Try-Flow or Github repo: https://flow.org/try/#0CYUwxgNghgTiAEA3W8wHsC2AHNBnEAXPACQDCmO+A3AFA0gAeOMALvKAGZQCuEb62PCAAUwqAEp4AXgB88KABp4wgEaTZ8NTSA

**Comment by amccloud** [comment]
Ran into this again but a bit wiser now. No issue here! As usual, I just need to provide annotations before the value is exported 🙈

https://flow.org/try/#0CYUwxgNghgTiAEA3W8wHsC2AHNBnEAXPACQDCmO+A3AFACW2aMALvAFTxS7wBKIUYVgDMYmeACI4A5uNo1mATywIA8gHcAdgAVRWbgF54AbwA+NePBAAPKNgggAksCK5mMOhoDmNEwF85isrwABJoYDpoevCGpuaWNnaExr4WqWnwPv408koIEVExcQB0JeraurgANMUloeEVNFk06BquqGgaGuDMTEQAFHHkjF0azER80kUAggBGrjDSQzgjzAA8+bgAfDQAlNGbvPyC03NuixQdIKOrZRsHhuiM+AMWS5ej+-B9WBV7+gerN4rYwlIo-SK4FLWWxYez6IxGXwpAD0m2qFignyguzkQgArhpBHQOvAAKIJWEgb4VIgbPZGOJwZh4mAaeCrYB0RDwVG0XzZFptcidbogYDkmH2aLtEWCJh9CWJHZyaw4FjGGVdOUwSrwYVa5hixWU+BZIA

**Comment by goodmind** [comment]
I still think it is wrong
https://flow.org/try/#0CYUwxgNghgTiAEA3W8wHsC2AHNBnEAXPACQDCmO+AUFaJLAgGYCuAdmAC4CWarqFeEABUA7mgA8AQQA08AEKzSAPgAUjKERWSAlPAC8S+bMYAjTXN0H4pbZp37DpGiAAeOGB36tcnk-v7YgqISrMwYJiAwsgD6MapU8PAqUJaGAOQAFiAQEGhp0glJKQ7wAIxU2jQA9FXwAHJo8ADmIKyRXGC48FlwVK7unujenlD+6IH44qHhkTFxKoXJqfCZ2bn5i8VW5dpAA

**Comment by amccloud** [comment]
@goodmind I agree that maybe it should have generics. Short of that, providing the return type to `compose` seems to work? I’d expect `compose` in your example to break because it appears at an input position, and neither it or the functions it is composing are annotated 

You’d have to create your own function and parametric definition around `$Compose` like you did in your example with `compose2` to avoid having to assign to a variable to annotate the return value of compose

**Comment by SamChou19815** [comment]
Close now since the annotation is expected anyways with types-first.
