### ISSUE TITLE
"Could not decide which case to select" with `Object` and function that returns `string`

### ISSUE THREAD

**Issue by cakoose** [facebook/flow#7469]
Flow version: v0.92.1 (and master, as of right now)

```
type T1 = (() => string) | Object;
type T2 = (() => Object) | Object;

function assert1(m: T1): void {}
function assert2(m: T2): void {}

assert1(() => JSON.stringify(1));  // <-- error reported (unexpected!)
assert2(() => JSON.stringify(1));  // <-- no error (as expected)
```

[flow.org/try link](https://flow.org/try/#0C4TwDgpgBAKgjFAvFAFCglEgfFAzsAJwEsA7Ac0wB8oB5AIwCsIBjYAbgChRJYAmJVBmy1GLYFRFNWnDgDMAriVZEA9iSgBDXLggFgcFAFsAXLDjpTANxVEAJlADeAXzmLlazdt3BeR0zF4LKGs7RxcOLR09AyFEHAApAGUaADkAOnxiciJZEBRzdDYoKAB6EqgAHgBaKqhdAhUCKAIIMEbgCHsURQgAD0hWToBCdAivPV9YhOT0zNIyHLyCotLy6tqSFTqCBqaULTr+sU70IA)

```
7: assert1(() => JSON.stringify(1));  // <-- error reported (unexpected!)
           ^ Could not decide which case to select. Since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To fix add a type annotation to return [3].
  References:
  1: type T1 = (() => string) | Object;
                ^ [1]
  1: type T1 = (() => string) | Object;
                                ^ [2]
  7: assert1(() => JSON.stringify(1));  // <-- error reported (unexpected!)
                   ^ [3]
```

**Comment by dsainati1** [comment]
`Object` is equivalent to `any`, so either case of the union would work. I would highly recommend avoiding the `Object` and `Function` type annotations.

**Comment by cakoose** [comment]
> `Object` is equivalent to `any`

Oh, you're right, looks like Flow 0.88.0 (released in December) made them equivalent.

But then why doesn't Flow report an error on the call to `assert2`?

**Comment by dsainati1** [comment]
To be honest, I'm not sure. Union speculation is a little bit arbitrary. I'd recommend annotating the argument as the error suggests.

**Comment by cakoose** [comment]
Adding an annotation gets rid of the error:

```
assert1((): string => JSON.stringify(1));
```

But I don't understand why.  If `Object` is equivalent to `any`, how Flow able to decide which case to select?

How is it supposed to work?  (It seems like there's a bug somewhere here but it's hard to tell because apparently my understanding of the expected behavior is incorrect.)
