### ISSUE TITLE
Flow going into flow-typed directory when options all=true

### ISSUE THREAD

**Issue by daslani** [facebook/flow#7472]
Flow version: 0.93.0
Flow-Typed version: 2.5.1

## Expected behavior

Running ./node_modules/.bin/flow should not go into flow-typed directory
Running with option all=true and ignore should not go into that directory

## Actual behavior

Flow returns an error for axios Flow-Typed definition:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ flow-typed/npm/axios_v0.18.x.js:132:15

Cannot use http$ClientRequest [1] without 0-1 type arguments.

     flow-typed/npm/axios_v0.18.x.js
      129│
      130│   declare class AxiosError<T,R = T> extends Error {
      131│     config: AxiosXHRConfig<T,R>;
      132│     request?: http$ClientRequest | XMLHttpRequest;
      133│     response?: AxiosXHR<T,R>;
      134│     code?: string;
      135│   }

     /private/tmp/flow/flowlib_2ebbbcbe/node.js
 [1] 1297│ declare class http$ClientRequest<SocketT = net$Socket> extends stream$Writable {
```
## Steps to Reproduce:

Create .flowconfig file
```
[ignore]
.*/flow-typed/.*
<PROJECT_ROOT>/dist/.*
.*/node_modules/.*

[include]
<PROJECT_ROOT>/src/.*

[options]
all=true
```
Install axios and flow modules
```
$ npm install axios
$ npm install -D flow-bin flow-typed
$ ./node_modules/.bin/flow-typed install
$ ./node_modules/.bin/flow
```

Thank you 😄

**Comment by goodmind** [comment]
@daslani it also does it without `all=true`

**Comment by goodmind** [comment]
Probably it is issue about `[ignore]`, not `all=true`

**Comment by lll000111** [comment]
https://github.com/facebook/flow/blob/v0.93/lib/node.js#L1297

>    declare class http$ClientRequest<SocketT = net$Socket> extends stream$Writable {

Interesting, I did not know Flow had a default value option for generic parameters. On the other hand, if it isn't used it seems to be a useless feature? He should not have to provide a parameter if that default value actually worked. Using '*' was deprecated, so if you want to just use the default, what do you do?

**Comment by goodmind** [comment]
@lll000111 `http$ClientRequest<>` would work
