### ISSUE TITLE
Error for optional class property despite implementing interface

### ISSUE THREAD

**Issue by carmanchris31** [facebook/flow#7474]
Flow version: 0.93.0

## Expected behavior

1. I would expect flow not to throw an error because the class interface explicitly declares foo as an optional property.

## Actual behavior

Flow throws an error as if the property was not declared at all. In contrast, an object literal typed with the same interface or analogous type does not throw an error as the property is declared (event though its value is still `undefined`).

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAssQJ4BGeAYnHGAN6phhRsD8ALjAAKAJRgAvAD4wANzgYAJqgC+AbnSkYxAM66wAdQw4AFnACuOVuwwBbAA4w8dvLgM16TG5zWbUpHBYujhgCCbmVj6SYFh4SMZmltZs-sDAYADKkTBKYEy82BQiFlhKeFBFShIMVmCEBHAEBsmCqOFJUWwAdHxw-oHBoVhwNsKejCxsUpwa6OlgAMKWuIQAtHgAHsSOzqJwANb0vE1gcAwAVnikoR2mYNj4RGR4YsJgqCM2vanoj4QkchgWiTGwAFToDgoXB4fSEogkMnkihUcx4ASCITAxBgujgADlRmxhCDvGwIVCZhw5qgFstSk8NttdsVDsc+AQzpdrrcImAcJDXm0cXjCd8+pogA

Very contrived example of how this can causes headaches in practice:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAglhgLbExgDeqYYWx9eA-AFxgAzjgLYA5gBp2YHAE8ADnkEixWKTIQALONXqUAFAEoVoidIC+AbnSkYxIULC0GTMAwUw8PXE5p1GZjYOeSUwAF4wAHJiLDBY1xgomw4ZUjgsVQBXUhw4AgMuHgFhM3UjVhkQrQwhADoiikjGlLALGU0dPUMK4I4wdMycdz1qCLAAIkp4+kmwAGpZGvrQikWJuonW1P73KDADHGWG7jxe1ABIDkGRMHo5ADlTyidIiYBZOU5T9ycJhaWtROPABGy2VX6EI4BDwOCyBDi9yePBeoLmiwwo22bQhEJhcIRI3o1Fa7XaqDsDicABE4OIwHgAB74LAAEycLkClRCiia0WIYFZdOSqHJlMcYAAMhgAF7EAishnMvBsjkBNx9VbjGJgGCy+WskVijK3BKBV5gADaWDwSFp4gMUQAytwokZJJxbVL9QrHQBxeVyN0em1ITlMAC6NlQZqY9Sg+QAomQtAYDLGYBVwgA+bkDE1wLx1eAOjN1bS6fTGIw2Cw1oA

**Comment by wchargin** [comment]
Note that changing `withoutFoo.foo` to `(withoutFoo: IMaybeFoo).foo` on
line 13 removes the error. This is a Liskov violation.
