### ISSUE TITLE
Refinements fail for bracket notation

### ISSUE THREAD

**Issue by dggriffin** [facebook/flow#7475]
Seems related to #1399

Flow version: 0.92.1

## Expected behavior
Refinements between bracket and dot notation are functionally equivalent.

## Actual behavior
Flow doesn't properly refine types when checking for the existence of properties using bracket notation.

Try-Flow Link:
https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUASAOQwLQHsA7AGxCwC4oBnYAJwEtCBzAGijRQF8BuNNUSFABCCZCnbYhBEmUo0GzFhx58AxkRpQAZvnyU4iJDmmkKULACMAhrSwq0ACi0BXQquD0i1YM61aHwAAWjEz6UOJCAJSUAG749AAmyGhQUPRaUAHBzADaxkSmALqRKcmpUAD0FVAJ+N6+GTq0sOypnKUQxFTQSKWV1bX1ftr4zSKl7ZxOupGRvHwC0DAATKKomDAA+gUgcnQhbMrzi8KrhuKYQtsyewqsR2oawCP4y-pnyFs7lJY2dvNOVzuTyEIb+IIhd7hU7RKBxRJlNIZLIhAB0XxkJVSvXKVRqdRoDRGzTgEw6XR6fTxg0JwyawlaUEm01es14qVKpSAA

**Comment by dominicfraser** [comment]
I have also found this. 

The example I have created shows how behaviour when trying to infer a type in a disjoint union of exact types fails if the properties are accessed via bracket notation, but work when using dot notation. 

https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKByAAqSWAXNgM4D2AthAPonABOAlgHYDm1ZzEWANBlGHplI9UMTpM2fFAF8A3GjT5oAIQTJ0mXMqKlKNCS3bAA7mV5pZCpeGgwy9NYjgooK62gDGnOlABmZGTEcIhI2ra6WORUtAxGHFy8AkIiYtiCwhCiIFjyigAUfgCuzJ7AjJxQdEV+fvnAABZGwQ4qAJTEAG5kjAAmyPyMflD1TWwA2uEEALoI8IhR+rGS7JzcbfxI-FCNRgB0GakgUAD0J-4AhowANiQ7ZFAsflk7DRfA2LtsWFAURb4AI2gZGGylg-Bk-Agt2gW0wp3OvQe1Vq-gcbigELQMkKgTabQ8YJgACZ1Kh+MpiIsYoY2AluHxMIcsmlaaxpHkbJA3KTQpodrYqdEDHE6aZzBzrETWrzYKTXCpiR5vMxfAEyMTgrKkJS9DTRatEjxkplslTmdlctZCiUyhVmFVgDU6l9WC1HMSOlBun0BpghiNXXswfMFsLlvE1lgNpg4ZggxbQAioN56PQIGVrscnlk7o13p8xqwfow7iCBdyYFjMNCSLDtmcoEjHc60fQMVicerPQSgA

**Comment by thers** [comment]
@goodmind still reproducible.

**Comment by goodmind** [comment]
huh

**Comment by goodmind** [comment]
It probably works if both types have same property, but not sure what I missed in PR

**Comment by goodmind** [comment]
This actually has bugs even without bracket refinements, it isn't `B` in else clause

**Comment by gkz** [comment]
Both examples in this issue both work now without errors.
