### ISSUE TITLE
Extended types are not working fine....

### ISSUE THREAD

**Issue by xhubbsaxo** [facebook/flow#7476]
I can not re-open https://github.com/facebook/flow/issues/7407 so I will continue here.

@vicapow your explanation is quite clear: "This is working as expected" but, I would like to get to the bottom of problem because we are starting having similar problems in multiple places related to list based components.

This is very basic real world example:

```
<List>
    <MyCustomItem1 id={1} myCustomProp1={1} />
    <MyCustomItem2 id={1} nyCustomProp2={2} />
</List>
```
From List component point of view:
- children must have id prop
- it can have anything else custom (we don't care about it, and we should not block it)

How it's possible using current flow version to declare type for List children prop?

**Comment by jbrown215** [comment]
[Does this work for you](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAMIAWwANgCaUAdgAViYdAF44Abzpw4wPgC55ggK4gARligAaOXADaqGFGCCA5gF0VyQU11wA9E7gARCILLxcySik0INXgYTjZKEzgIAjhQtlxufiE4MDFUOgBfemZWOAAZYBNRCHE4KVl5OATeASxBFQB+ABJsZD4AeUEeJgBBKChkJgAeVvwAOgBRHiwQOpgRqhgxns0TAfx2EkhBOaGuGqFi8QA+U-0shlweNHQAWSZ2NRMSTfBPOYBGOCwADxg6vjoUZLV7bXbSRQqdRaHSOVAkLChcwWKaoLAqNbIjLHGQZOhXG5we6PZ4gUHvQQwABM3z+AKBizG5J2lKGEOUcGh2j0cHhs3acSgABVuJYMaYsTjpHj8ddUOgCpFfv9BIDMIzmbtFTAjqgpTKhtrjgYhsSnjAXlsKTAvooJNIAMwZXkIpGWVFYCQAIkxli9zmN8lND3NlreLOpCj49oALM6+VgBWFhaKLN7fRZ-U5jUMnEagA)?

**Comment by xhubbsaxo** [comment]
Amazing!!! Thank you very much. It should cover all the cases.
