### ISSUE TITLE
Flow is not getting installed, facing syntax error in src/parser/flow_ast.ml

### ISSUE THREAD

**Issue by ossdev07** [facebook/flow#7477]
uname -a
Linux 8cd2f3a1381c 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 GNU/Linux

Cloned flow package and ran command **npm install**. Facing below issue:
npm install 
npm WARN prepublish-on-install As of npm@5, `prepublish` scripts are deprecated.
npm WARN prepublish-on-install Use `prepare` for build steps and `prepublishOnly` for upload-only.
npm WARN prepublish-on-install See the deprecation note in `npm help scripts` for more information.

> undefined prepublish /flow
> yarn workspace flow-parser run prepublish

yarn workspace v1.13.0
yarn run v1.13.0
$ make js
if [ -e dist/flow_parser.js ]; then \
        [ flow_parser.js -nt dist/flow_parser.js ] || cp dist/flow_parser.js flow_parser.js; \
else \
        make -C ../../src/parser js; \
        cp ../../src/parser/flow_parser.js flow_parser.js; \
fi
make[1]: Entering directory '/flow/src/parser'
cd /flow/src/parser//../..; \
ocamlbuild -use-ocamlfind -no-links -pkgs js_of_ocaml src/parser/flow_parser_dot_js.byte; \
[ -e "src/parser/flow_parser.js" -a "src/parser/flow_parser.js" -nt "_build/src/parser/flow_parser_dot_js.byte" ] || \
        js_of_ocaml --opt 3 \
                -o src/parser/flow_parser.js \
                _build/src/parser/flow_parser_dot_js.byte
+ ocamlfind ocamldep -package core_kernel -package ppx_gen_rec -package ppx_deriving.show -package sedlex -package wtf8 -package ppx_deriving -package dtoa -package js_of_ocaml -modules src/parser/flow_ast.ml > src/parser/flow_ast.ml.depends
File "src/parser/flow_ast.ml", line 13, characters 6-7:
Error: Syntax error
Command exited with code 2.
Compilation unsuccessful after building 5 targets (4 cached) in 00:00:01.
js_of_ocaml: Error: Sys_error("_build/src/parser/flow_parser_dot_js.byte: No such file or directory")
Makefile:86: recipe for target 'js' failed
make[1]: *** [js] Error 1
make[1]: Leaving directory '/flow/src/parser'
cp: cannot stat '../../src/parser/flow_parser.js': No such file or directory
Makefile:18: recipe for target 'flow_parser.js' failed
make: *** [flow_parser.js] Error 1
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed.
Exit code: 1
Command: /usr/local/bin/node
Arguments: /opt/yarn-v1.13.0/lib/cli.js run prepublish
Directory: /flow/packages/flow-parser
Output:

info Visit https://yarnpkg.com/en/docs/cli/workspace for documentation about this command.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! undefined prepublish: `yarn workspace flow-parser run prepublish`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the undefined prepublish script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-02-15T13_58_03_469Z-debug.log

Please guide to resolve the same. Thanks in advance.

**Comment by jbrown215** [comment]
Which ocaml version are you using? cc @mroch

**Comment by mroch** [comment]
My guess is that ppx_gen_rec isn’t installed. 

Try this to install the deps:

```
opam pin add flowtype . -n
opam install flowtype --deps-only
```

**Comment by ossdev07** [comment]
@jbrown215 ocaml -version
The OCaml toplevel, version 4.02.3

@mroch Have already installed using below command:
opam install ppx_gen_rec js_of_ocaml sedlex

Will try out these commands and update the ticket. Thanks for the help.

**Comment by jbrown215** [comment]
We also use ocaml 4.05.0

**Comment by ossdev07** [comment]
@jbrown215 Thanks. Have installed ocam 4.05.0 with command opam switch install 4.05.0. 

@mroch Thanks for the help.
Issue has been resolved after following below steps:
opam pin add flowtype . -n
opam install flowtype --deps-only
opam install js_of_ocaml
eval $(opam config env)

Flow binary has not been created. Could you please guide to generate flow binary.
Thanks in advance.

**Comment by ossdev07** [comment]
Binary has been created in bin folder after running command **make all**.
