### ISSUE TITLE
conflicting function type declaration and implementation does not raise errors

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#748]
Here is an example:

```js
/* @flow */

/*:: declare function foo(x: string, y: number): string*/
function foo(x, y) {
  return x + String(y);
}
foo('Hello', 'bar');
```

I would have expected to get following error:

```
flow check

/Users/gozala/Projects/flowing/flowing.js:9:1,19: function call
Error:
/Users/gozala/Projects/flowing/flowing.js:9:14,18: string
This type is incompatible with
/Users/gozala/Projects/flowing/flowing.js:3:41,46: number

Found 1 error
```

But instead I get

```
flow check

Found 0 errors
```

**Comment by Gozala** [comment]
Following does not seem to raise any errors either:

```js
/*::
declare var foo:(x: string, y: number) => string
*/
function foo(x, y) {
  return x + String(y);
}

foo('Hello', 'bar');
```

**Comment by samwgoldman** [comment]
This isn't the correct way to use comment annotation for functions. Flow does not try to match up declared types with defined types like this, so in end Flow's inferred type for `foo` is overwriting your declared type.

If you want to use comment syntax, you need to do it like this:

```javascript
function foo(x /*: string */, y /*: number */) /*: string */ {
  return x + String(y);
}
```

**Comment by Gozala** [comment]
> This isn't the correct way to use comment annotation for functions. Flow does not try to match up declared types with defined types like this, so in end Flow's inferred type for foo is overwriting your declared type.

> If you want to use comment syntax, you need to do it like this:

> ```js
function foo(x /*: string */, y /*: number */) /*: string */ {
  return x + String(y);
}
```

I was in fact trying to figure out how to do the alternative function annotation present in [flotate](https://github.com/jareware/flotate):

```js
/* @flow */
/*: (x: string, y: number): boolean */
function foo(x, y) {
    return x.length * y === 5;
}
foo('Hello', 42);
```

Given your comment I assume such a feature is not available, which is unfortunate.

Anyhow I still think it would be useful for `flow` to handle conflicts (even if by just reporting) between declared and inferred types rather just favoring inferred ones.

**Comment by Gozala** [comment]
I think this issue is pretty much the same as #838 so closing this one.
