### ISSUE TITLE
propTypes no longer part of React.AbstractComponentStatics

### ISSUE THREAD

**Issue by cprodescu** [facebook/flow#7484]
One cannot reference `propTypes` on a `ComponentType<*>` since 2e7d5a26babe69f2b17cba25f6f62a524534c635.
Is this intended? If yes, do you have a suggestion for handling this?

Example code:
```
import * as React from 'react';

function testHoc<-Props>(Component: React.ComponentType<Props>, props: Props) {
	return class Wrapper extends React.Component<Props> {
      static propTypes = Component.propTypes; // Error here: property `propTypes` is missing in 
`React.AbstractComponentStatics`
      
      render() {
      	return <Component {...props} />
      }
    };
}
```

[Flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqlACuAOwbo4wsAWpkCACTh0APAFoACs2xkAfAAoAwi1zDqwggC4qXAgDpDOCaYIAVAJ7ZqSjXC3aANGDYmmSW3loAlGAA3qgAkJwEgniSdDDkFADqeCTYHnhg1AAe0sIAJhQ09Lb2xk5ewdrRqGAtrbIkBOh0gZpuHhQAvGA1jmY2QT59Mnytrc2zYJxl1Hi6kTELYPHUiclgSiMmZtE2pxNaAL5gwNrzsxd3YBd8F0A)

**Comment by jbrown215** [comment]
We intentionally did not include propTypes because the static tracking should get rid of the need to use propTypes. I understand that someone may want some runtime verification as well, since `any` exists. We could include it as `propTypes?: any` in the libdef, which is how we type it for classes.

**Comment by jbrown215** [comment]
I'd be willing to accept a PR that adds propTypes to AbstractComponentStatics

**Comment by cprodescu** [comment]
Thank you, will look into it.
