### ISSUE TITLE
Cannot import useState because there is no useState export in react.

### ISSUE THREAD

**Issue by ionutcirja** [facebook/flow#7489]
I just update react to latest version (16.8.2) and flow is complaining about this.

'Cannot import useState because there is no useState export in react.'.

Any plans to update flow?

Thanks

**Comment by jbrown215** [comment]
This has already been in Flow for a few versions now. Which Flow version are you using?

**Comment by ionutcirja** [comment]
0.93.0

**Comment by TrySound** [comment]
@ionutcirja How do you import it?

**Comment by TrySound** [comment]
Also do you have globally installed flow?

**Comment by ionutcirja** [comment]
Flow is installed locally as a dev dependency.
I'm importing as it should be imported: import {useState} from 'react'

Thanks

**Comment by TrySound** [comment]
This is weird. Could you make a screenshot with the error in terminal?

**Comment by ionutcirja** [comment]
Sure, here it is.
Many thanks for your help.

<img width="867" alt="screen shot 2019-02-20 at 3 57 02 pm" src="https://user-images.githubusercontent.com/5065425/53105128-76d2c800-3528-11e9-9dbc-b9699e5bd17f.png">

**Comment by jbrown215** [comment]
Can you also run `flow version` and show us the output just to be sure?

**Comment by ionutcirja** [comment]
Yep. 
<img width="426" alt="screen shot 2019-02-20 at 4 04 41 pm" src="https://user-images.githubusercontent.com/5065425/53105577-4f302f80-3529-11e9-899d-807091a2219c.png">

**Comment by ionutcirja** [comment]
Hmm, I think it might be about flow-babel-webpack-plugin.

**Comment by ionutcirja** [comment]
It seems it is not. Now I'm running out of ideas.

**Comment by ionutcirja** [comment]
When I'm running just flow I'm getting not errors, but something strange saying flow server didn't match the client.
 
<img width="697" alt="screen shot 2019-02-20 at 4 46 38 pm" src="https://user-images.githubusercontent.com/5065425/53108585-30cd3280-352f-11e9-83ad-bc986d75a03c.png">

**Comment by jbrown215** [comment]
Did you recently upgrade Flow? It's possible that your old server was still running and so it didn't launch a 0.93.0 server

**Comment by ionutcirja** [comment]
Yes, upgraded few hours ago. Is there any way to 'clear' the old version.
I removed node modules and reinstalled already.

**Comment by jbrown215** [comment]
`flow stop`

**Comment by ionutcirja** [comment]
Still getting 'Cannot import useState because there is no useState export in react.' when I run webpack.

**Comment by TrySound** [comment]
@ionutcirja You probably have flow in transitive dependencies.
https://github.com/zhirzh/flow-babel-webpack-plugin/blob/master/package.json#L8

I would get rid from this plugin. It doesn't have official support and since it's archived it doesn't have any support.

**Comment by TrySound** [comment]
Closing as not related to flow.

**Comment by ionutcirja** [comment]
Problem fixed. Many thanks for your help.

**Comment by Shettysai** [comment]
how is it fixed?

**Comment by shaantanu9** [comment]
How to fix it? 

**ERROR in ./src/counter.jsx 12:32-40
export 'useState' (imported as 'useState') was not found in 'react' (module has no exports)**

![Screenshot at 2022-03-06 21-01-58](https://user-images.githubusercontent.com/33876955/156930020-cec43a37-aead-469e-8f6d-cd6ac4ccc164.png)

**Comment by shaantanu9** [comment]
Find the Solution Use Flow as metion by many developers above I tried installing flow and it work 

`npm i -D flow-babel-webpack-plugin` works for me, but

Also If that not work try once this also
`"flow-bin": ">=0.44.2 <1",`
