### ISSUE TITLE
Unexpected behavior for union-typed arrays

### ISSUE THREAD

**Issue by ninofiliu** [facebook/flow#7495]
Flow version: `0.93.0`

## Expected behavior

An object of type `Array<A>` can be assigned to an object of type `Array<A|B>`.

## Actual behavior

An error is thrown because of incompatible `A` and `B` types. However, when using the spread syntax and performing the equivalent operation, the error is gone. The same script in TypeScript doesn't trigger any errors. I don't even think there should be an error in the first place, which is why I'm filling this bug report.

```ts
const a: Array<number> = [10];
const b: Array<string> = ['ten'];
let c: Array<number|string>;

c = [10];
c = ['ten'];
c = a; // This error shouldn't trigger an error
c = b; // This error shouldn't trigger an error
c = [...a];
c = [...b];
```

[tryflow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAEMAuMAQQCdKiBPAHmwFcBbAIwFNKA+MAXjABtAIwAGALoBuTDgJg2ZKjQYFKAS2wBzXgMEByfB2x6pqGB0IZF1Oo1adKAH1Ubt0zPyFjTGT-sPGPp5EkmDAwGAAKgAWarhgXJRwlGC40XBMMAAmxoT46pqaXMTYCdTJHgJsoeFRsfGJyanpmTkGYPlqhcVEpY2UlUIAdCNEQbojQ2ymqLUcAI5MagBuRObYlkS4HGAIavgthEQ2tPEAtLzYcGVJlAA0xA0AHgAOHBiGWehYeIRZZMx2MUBGJpD85BwyC4tJ4DEY9NJzIQoAD7FxnJ0tO4oJ5QagcQI4cZpASwFkSZ4OJIgA)

**Comment by jbrown215** [comment]
This is not a bug. Take this example:

```
//@flow
const a: Array<number> = [10];
const b: Array<number | string> = a;
b.push('ten');

a.forEach((x: number) => x.toFixed()); // Runtime error!
```

If you want this subtyping behavior, use `$ReadOnlyArray` which prevents writes and thus prevents this error.
