### ISSUE TITLE
Unclear error message when exporting a function without explicitly annotated signature

### ISSUE THREAD

**Issue by lxe** [facebook/flow#7497]
Flow version: 0.93

Ran into an unclear error message when I exported the [following code](https://flow.org/try/#0GYVwdgxgLglg9mABGEBbARgUwE4GcAUAlIgN4BQiiECuUiumUA8sAHJpZ6IC8ymA7ogDKjADwoMOAHxEA3BSo06AQ2zZlATxbtJXXgEE1mgHTBscVPgbM2HHLmMA3ZQBsQmAoULzK2RiGwkVXUtW11cMgBfMjIgA):

```js
function numbers() {
  const setOfNumbers = new Set<number>();
  const arrayOfNumbers = Array.from(setOfNumbers.values());
  return arrayOfNumbers;
}

// No errors
```

[Exporting this function yields a cryptic error message](https://flow.org/try/#0GYVwdgxgLglg9mABGEBbARgUwE4GcAUAlIgN4BQiiECuUiumUA8sAHJpZ6IC8ymA7ogDKjADwoMOAHxEA3BSo06AQ2zZlATxbtJXXgEE1mgHTBscVPgbM2HHLmMA3ZQBsQmAoULzK2RiGwkVXUtW11cMgBfMjJMAA8ABzhsOgATTGBlEBc6CU5ceTIgA):

```js

function numbers() {
  const setOfNumbers = new Set<number>();
  const arrayOfNumbers = Array.from(setOfNumbers.values());
  return arrayOfNumbers
}

export default numbers;

/*
3:   const arrayOfNumbers = Array.from(setOfNumbers.values());
                            ^ Missing type annotation for `A`. `A` is a type parameter declared in function type [1] and was implicitly instantiated at call of method `from` [2].
References:
[LIB] ..//static/v0.93.0/flowlib/core.js:280:     static from<A>(iter: Iterable<A>, mapFn: void): Array<A>;
                                                  ^ [1]
3:   const arrayOfNumbers = Array.from(setOfNumbers.values());
                            ^ [2]
*/
```

## Expected behavior

I'm unsure why the error is being thrown in the first place, but I heard through word of mouth that export signatures should be annotated.

Would like the errors messages in that case to be more actionable, for example:

```
[6] export default numbers; 
^ Missing export type annotation. Exports must be annotated because of [insert reason]
```

Or something of the sort

**Comment by conradreuter** [comment]
This is expected behavior, definitely not a bug.

Fix
```
function numbers(): Array<number> {
  const setOfNumbers = new Set<number>();
  const arrayOfNumbers = Array.from(setOfNumbers.values());
  return arrayOfNumbers;
}

export default numbers;
```

or if you're lazy (and have no fear of the existential type):
```
function numbers(): * {
  const setOfNumbers = new Set<number>();
  const arrayOfNumbers = Array.from(setOfNumbers.values());
  return arrayOfNumbers;
}

export default numbers;
```

**Comment by jbrown215** [comment]
`[insert reason]` may be too much to fit in an error message. I plan to add a "Documentation" section to error messages that may help this.

The reason it tells you where the type parameter was implicitly instantiated is so that you can figure out how to explicitly instantiate it at the callsite.

This isn't a bug.

**Comment by lxe** [comment]
> The reason it tells you where the type parameter was implicitly instantiated is so that you can figure out how to explicitly instantiate it at the callsite.

Sorry I guess I mis-tagged it as a bug. But why doesn't the error message specify the line number of the function instead of the internal library?

```js
export function numbers(): Array<number> {
  const setOfNumbers = new Set<number>();
  const arrayOfNumbers = Array.from(setOfNumbers.values());
  return arrayOfNumbers;
}
```

Works fine, after adding the exported function return value type, even without doing ```Array.from<number>(setOfNumbers.values());```

It's till unclear why there's no error at all when function is not exported.

> or if you're lazy (and have no fear of the existential type):

I was under the impression that existential type is deprecated?

**Comment by jbrown215** [comment]
> Sorry I guess I mis-tagged it as a bug. But why doesn't the error message specify the line number of the function instead of the internal library?

it specifies both, right? The error points to where the missing annotation is, and it refers to the library so you know that it is polymorphic.
