### ISSUE TITLE
$ObjMap adds 'any' to 'Array<string>' return type when extracting return type

### ISSUE THREAD

**Issue by mgreenw** [facebook/flow#7498]
Flow version: 0.93

Using the [Official Documentation's $ObjMap Example](https://flow.org/en/docs/types/utilities/#toc-objmap) I am running `$ObjMap` as such:

```
type ExtractReturnType = <V>(() => V) => V;

function run<O: {[key: string]: Function}>(o: O): $ObjMap<O, ExtractReturnType> {
  return Object.keys(o).reduce((acc, k) => Object.assign(acc, { [k]: o[k]() }), {});
}

const o = {
  a: () => true,
  b: () => 'foo',
  c: () => ['hey there'],
};
```

## Expected behavior

By itself, `c` is of type `() => Array<string>`.

Example: https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwBVxoBeKAHgDUA+ACjoEopSaornX2BuAKF4BmOfOgCWAe3xREwigHkAXFADeAbQDWEEEoDOSUfgDmAXSUAxYWMkBfeuKVzGSgCRyARgCsAssjDyANLAIKOhYuATEkGzKvFDS2HhS7h4Q6AB0miA6dOKMaYgQACY4qBAMaKiB6pxsyanAacg6OqKG+HQVgcpQGqZQ4r1MUNaMXSN81vyoknr9LCqxUMhKQ1xIOBD+i24rNVAA5ALi4vtbcai7LGyq+wAWWlDA9wX7xlvW3EA

## Actual behavior

However, when the following code is added, `c`'s type changes to `() => Array<any|string>`:

```
const p = run(o).c;
```

Example: https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwBVxoBeKAHgDUA+ACjoEopSaornX2BuAKF4BmOfOgCWAe3xREwigHkAXFADeAbQDWEEEoDOSUfgDmAXSUAxYWMkBfeuKVzGSgCRyARgCsAssjDyANLAIKOhYuATEkGzKvFDS2HhS7h4Q6AB0miA6dOKMaYgQACY4qBAMaKiB6pxsyanAacg6OqKG+HQVgcpQGqZQ4r1MUNaMXSN81vyoknr9LCqxUMhKQ1xIOBD+i24rNVAA5ALi4vtbcai7LGyq+wAWWlDA9wX7xlvWfHFxvNP4s2DzGTtXJpVDcIA

Just running the method causes flow to add the `any` type to the return type. I'm not sure if this is a bug with `$ObjMap` or any of the mentioned bugs above.

Note: I Initially posted about this [here](https://github.com/facebook/flow/issues/6874#issuecomment-466065848) but was referred to submit a new issue.

**Comment by dsainati1** [comment]
If you look in the core libdefs you will see that the type of `Object.keys` is `any => Array<string>`. This `any` is propagated through your function calls to reflect this fact, and Flow's inference picks the type that fits both `any` and `string` for `c`. You can recover the stricter behavior by annotating: https://flow.org/try/#0C4TwDgpgBAogHsATgQwMbAEoWAV0QOwBVxoBeKAHgDUA+ACjoEopSaornX2BuAKF4BmOfOgCWAe3xREwigHkAXFADeAbQDWEEEoDOSUfgDmAXSUAxYWMkBfeuKVzGSgCRyARgCsAssjDyANLAIKOhYuATEkGzKvFDS2HhS7h4Q6AB0miA6dOKMaYgQACY4qBAMaKiB6pxsyanAacg6OqKG+HQVgcpQGqZQ4r1MUNaMXSN81vyoknr9UErdyEpDXG7i4gA2gW7LNVB6iAaGgai7LGwAgogoIBQHR2zWLCqxUEtQK2xIOBD+rzsfPYAcgE6yBfzip0B5x6QIAFlooMAEQUgcY-tY+HE4rxpvhZmBnjJ2rk0qhuEA

**Comment by mgreenw** [comment]
@dsainati1 Thanks for the response! I don't exactly understand why the `any` here needs to propagate as I am dealing with the object's values and not the keys. 

In the following example, I have two test cases. `result` has type ```{ a: boolean, b: Array<any | number> }``` and `result2` has the type ```{ a: boolean, b: Array<any | boolean> }```. Do you have any suggestion for how I could more strictly type the `assertTypes` function so the types for `b` in `result` and `result2` do not include the `any` but without having to strictly annotate `testObjectType` and `testObjectType2`? Thanks!

**Comment by dsainati1** [comment]
A first suggestion would be to remove the `Function` type annotation in the definition of `assertTypes`, as this is just an alias for `any`. Another would be to avoid using Object.assign, as this is also `any`-typed.
