### ISSUE TITLE
Вoes not show an error

### ISSUE THREAD

**Issue by gespispace** [facebook/flow#7501]
Flow version: 93.0

## Expected behavior
Show error 
# Actual behavior
Don't show error

If i have `div` around element, i see error but if i don't have `div` around i don't get error 

* Link to Try-Flow or Github repo: [with error](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IooQB6a6g4Ce6QqADKhLADdkpQsJzEcAVwDOoALygA3olCgAdsVSEAXKCU4syXQHMANIgC+rRAEkchVLPnKAdABNCkMQK0DgAClToKupaOvqGJrrB0HaObIiQCrrkyLC6oK7unopKABQaegZC9iaiElIycsUAlJraoAyKWHklbToAPL7I4gB8vTqacYT2Y33AgyNtTazT6ZnZubyEZiUtWgCQHQpdoD3j4wNDo2dnfQUejcpj1xWGqhq0tNPPOsBXN3OXMZNBzMIA) 23 line

* Link to Try-Flow or Github repo: [without error](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IooQB6a6g4Ce6QqADKhLADdkpQsJzEcAVwDOoALygA3olCgAdsVSEAXKCU4syXQHMANIgC+rRAEkchVLPnKAdABNCkMQK0DgAClToKupaOvqGJrrB0HaObIiQCrrkyLC6oK7unopKABQaegZC9iaiElIycsUAlJraoAyKWHklbToAPL7I4gB8vTqacYT2Y33AgyNtTazT6ZnZubyEZiUtWgCQHQpdoD3jZ6B9BR6NymPnFYaqGrS00-c6wKNnTQ7MQA) 23 line

**Comment by jbrown215** [comment]
This is an extremely under-specified bug report. In the future, please include more details so that we know what's wrong before I look at the code sample.

The issue is that we don't eagerly check defaultProps against props. You specify the type of name to be string, but you set it to null in the defaultProps. If you set it to`?string` there is no error.

**Comment by gespispace** [comment]
@jbrown215  
Sorry for the bad description.

I understand what i set ?string there is no error.

Error is not in defaultProps, error is i don't see error message.
Tag `div` around `<ItemStatus />` clear the error message.

**Comment by jbrown215** [comment]
If you run Flow with ‘—show-all-branches’ it will point to the defaultProps
and error
-- 
Sent from Gmail Mobile
