### ISSUE TITLE
Cannot assign `...` to `...` because number is incompatible with string

### ISSUE THREAD

**Issue by kldkv** [facebook/flow#7502]
Flow version: 0.93.0

## Expected behavior
No errors.

## Actual behavior
Flow cannot specify the correct type for the return value. In the example, `foo ('string')` can return only the string type, `foo ('number')` can return only the number type.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKfATwAcBTALjAHIBnfAJ0OwHNWYAD5tsmALYAjBl1YBKFpx79hYMVJlgA3qjBhcJTvpIATQkRJgAvGACyAQ3wALAHRd72E3HGU5YAHw2AAwuAKwA3LpgqACQhFBg1PQM1lY2HNy8An46enlcDPiYXKQGnubEpAD8bOzeDIIsGcoCkXlgAL7o7fGJtIyp6erSsjlR7QVFJcblFtVgAIxgLAC0C215XV2oZUbwMADWDAeKmSo25FTNWfKRu-hgRwf7LMOaFxSUrG+j4UA

**Comment by dsainati1** [comment]
Flow's refinements are not powerful enough to figure this out. This is in general undecidable, so I would be surprised if any language supported this sort of code.

**Comment by goodmind** [comment]
Use overloads
