### ISSUE TITLE
Types from external files fail to match Flow Conditional Types

### ISSUE THREAD

**Issue by piglovesyou** [facebook/flow#7504]
Flow version: 0.93.0

## Expected behavior

Locally defined types and externally defined types behave identically.

## Actual behavior

Let's say `$Call<Function & Function & ... , T>` is Flow Conditional Types.

While [locally defined types match one of patterns perfectly](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmhEDOaAMrBttABRoBcoLb0ACoBPAA5oAlLwAKuWAFtKjADz92I8QD4A3MnRY8BA-XqgAErGhplgzaADeiUKAw165XEQqxcHQVPNLa1tdZ1FKcWUAVU0-UABeOyiAgBIAYXZoZSdnXIAyUA5lADVY2QUla1KJBLsLKxLNCRzc0AKi0o5imsTAhuqW3IAaQecYxABfZHIxAjUhWYTQEiJ5ACM0XF1EED5WdUWAKwZyUHgfAGtTSEoSNAA6RDv4PrQOAEZm1vvw8Q4GZj7aBfXI-CJvAi9Li8eYaSQg5xgv6QuzlRSMe74eiWABubwA2mgALoSBGgJEQ2qFHigACCuFw2GEqiBcKaZIpHA4hJJVOhewEcNJQA), externally defined types try to match just the first pattern and fail.

* Link to Github repo: https://github.com/piglovesyou/reproduce-flow-imported-type-problem

### Complement

The reason I use Conditional Types instead of ordinal overloading:

```js
// Not works
declare class Hole<T> {
    pipe<U>(T => Promise<U>): Hole<U>;
    pipe<U>(T => U): Hole<U>;
}
```
... is because it doesn't work. Since `T => U` contains `T => Promise<U>`, Union Types cannot decide one of the methods.

As long as using locally defined types, Flow Conditional Types work very well.  I believe it's a very powerful feature. I hope this issue will be addressed soon.

**Comment by SamChou19815** [comment]
it should be fixed already
