### ISSUE TITLE
Spread with empty array literal is incompatible with object expecting ReadOnlyArray

### ISSUE THREAD

**Issue by gajus** [facebook/flow#7505]
Flow version: v0.93.0

## Setup

Code:

```js
type ClientUserConfigurationType = {|
  +interceptors?: $ReadOnlyArray<string>,
  +typeParsers?: $ReadOnlyArray<string>
|};

const defaultConfiguration = {
  interceptors: [],
  typeParsers: []
};

const foo = (clientConfiguration: ClientUserConfigurationType = defaultConfiguration) => {
	
};

foo({
  interceptors: [],
  typeParsers: [],
  ...defaultConfiguration
});

```

Sandbox: https://flow.org/try/#0C4TwDgpgBAwgNgSwgO2AVQM4QE4wPbIBmCA5gK7YCGwCBAKuNALxQDeAPgFBRQDUCqHAGMIYYHmwYA-AC4oAEgBKESgBMA8sjggAgtiogAPBmDYBJAHwAabn1CQACpUk5pcpSo1bd+ykZNmyJac7AC+ANycnEIEJlCqEISUZHDA+ESkFNS0yFAsrLYCwMKi4pJyANoAujY89hBOLuVQ1ZwRUTHIcYR4eHlQABRCiChpBMTkVDQEcvBIqJg46RNZ08gMkP0JSSljGZPZBACUeRZsnACQbZGcPXgDBTxFJWISGJU1tvWNWM3VtVAAHTA7bJVLLTJTHJtI7hIA

## Expected behavior

No error.

There is no reason why [] should be incompatible with `$ReadOnlyArray`.

This example shows how empty array is used to produce default configuration.

## Actual behavior

Error:

```
2:   +interceptors?: $ReadOnlyArray<string>,
                     ^ read-only array type [1] is incompatible with empty array literal [2].
References:
2:   +interceptors?: $ReadOnlyArray<string>,
                     ^ [1]
16:   interceptors: [],
                    ^ [2]
3:   +typeParsers?: $ReadOnlyArray<string>                    ^ read-only array type [1] is incompatible with empty array literal [2].
References:
3:   +typeParsers?: $ReadOnlyArray<string>                    ^ [1]
17:   typeParsers: [],
                   ^ [2]

```

**Comment by jbrown215** [comment]
`[]` is compatible with `$ReadOnlyArray`. The issue here has to do with the spread operator.

**Comment by nmote** [comment]
This no longer errors in master.
