### ISSUE TITLE
flow 0.93.0 not validating styled-component code (0.91.0 working fine)

### ISSUE THREAD

**Issue by Ziv-Barber** [facebook/flow#7513]
Flow version: 0.93.0

## Expected behavior

    const StyledMyComp: typeof MyComp = styled(MyComp)`
      margin: ${(props) => props.theme.spacing.unit * 2}px !important;
      padding: ${(props) => props.theme.spacing.unit}px;
      background: black;
      color: white;
    `

Passing flow in 0.91.0 but not 0.93.0

## Actual behavior

* Link to Try-Flow or Github repo:

**Comment by jbrown215** [comment]
I'm closing this because you didn't give an example on flow.org/try. Feel free to reopen this issue after adding the example.
