### ISSUE TITLE
Strict mode option to automatically cast any to mixed

### ISSUE THREAD

**Issue by zeorin** [facebook/flow#7515]
## Proposal

A new strict mode option that, when enabled, automatically casts all instances of `any` to `mixed`.

It should affect the results of `flow coverage`. If `any` is treated as `mixed`, the effective coverage should go up.

It should _not_ apply to any instances of a [`suppress_type` alias](https://flow.org/en/docs/config/options/#toc-suppress-type-string), much like [`unclear-type`](https://flow.org/en/docs/linting/rule-reference/#toc-unclear-type) does not currently apply to an instance of a `suppress_type` alias. [This way one could still down-cast.](https://github.com/facebook/flow/issues/2221#issuecomment-448502729)

We'd have to consider whether this ought to influence the behaviour of the [`untyped-import`](https://flow.org/en/docs/linting/rule-reference/#toc-untyped-import) and the [`untyped-type-import`](https://flow.org/en/docs/linting/rule-reference/#toc-untyped-type-import) rules. If `any` is treated as `mixed`, then untyped imports would no longer be aliased to `any`, but to `mixed` instead.

We should consider whether this should also apply to `Object` and `Function`, at least in contexts where a value with either of those types is being referenced. However, in contexts where the type of a value needs instead to _match_ `Object` or `Function`, aliasing them to `mixed` would effectively _reduce_ soundness.

## Use case

This is useful to stop accidental use of `any` not caught by the existing lint rules. E.g. when using the return value of [`JSON.parse`](https://github.com/facebook/flow/blob/v0.93.0/lib/core.js#L476), [`Response.json`](https://github.com/facebook/flow/blob/v0.93.0/lib/bom.js#L1031), or any 3<sup>rd</sup> party type definitions that use `any` in a way that might flow back into the user's codebase.

This would encourage actually refining the return values (and handling potential errors), or at the very least making a type cast explicit by forcing the use of a `suppress_type` alias, which could thus be searched for in code reviews or by CI tools.

This is similar to what is asked for in https://github.com/facebook/flow/issues/1611, but is not limited to library definitions.

It would also be a solution to https://github.com/facebook/flow/issues/2470 (in particular it would incidentally implement the 3<sup>rd</sup> suggestion).

**Comment by zeorin** [comment]
Just to note that `Function` and `Object` are actually aliased to `any` since version 0.88.0, vastly simplifiying the handling of these types. In this proposal, they would thus also be aliased to `mixed`, regardless of where they occur.

**Comment by SamChou19815** [comment]
Closed for the same reason as #1611
