### ISSUE TITLE
The compiler does not look ahead when the return type is a function

### ISSUE THREAD

**Issue by patrickjtoy** [facebook/flow#7519]
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCoAsCWAzmAnAE4DWh6AJgKYDGMAhmXWFAK4B2DALvjjcwdGHQC2AHmYA+ABTMAXGGYAaDsoDeYANoU6AT2WE+ZfNwDmAXWXMwAXwCUygEZw4Y5twDcqek1Z2Ll4BIRExKVkFW3UoZQBBMjJmA2kZZzA3DzovX1RRCTkAZlVtAA9lAEZ1IzAAJnUAL2Uih0d8iLkAcgYu9R0u5j6wLpdhnq6rdowsPCIwGjg6Ym44PhJyClpGFjYOHn5BYQLxAGFOJPw6GjTolQy5OLBtPUNjU3NrWzawAF4ZTLuTw+Pw7QL7EJHcISc6Xa63JT3ZSPBJJFJpRx-AFZYF5E6wszXYqOOTlKo1ZQNMDNMCtJwdGEXQk0bq9EkDIbqUbjXpTVBAA)

```
/* @flow */

// This works

declare function elem<a>(a: a, f: { [key: string]: a }): boolean;
declare function elem<a>(a: a, f: Array<a>): boolean;

elem(3, { x: 1, y: 2, z: 3 })
elem('c', ['a', 'b', 'c'])

// This does not work

declare function elemCurried<a>(a: a): (f: { [key: string]: a }) => boolean;
declare function elemCurried<a>(a: a): (f: Array<a>) => boolean;

elemCurried(3)({ x: 1, y: 2, z: 3 })
elemCurried('c')(['a', 'b', 'c'])
```

As shown in the above example, the compiler is matching the overloaded function based only on the type of the first argument when the return type of the function is itself another function. In such cases, the compiler should check if the return of an overloaded function is a function and then recursively type check the remaining arguments to ensure the correct function is selected.

**Comment by jbrown215** [comment]
```
declare function elemCurried<a>(a: a): (f: { [key: string]: a }) => boolean;
declare function elemCurried<a>(a: a): (f: Array<a>) => boolean;
```

How would this overloading work at runtime anyway if it's given the same amount of arguments of the same type?

**Comment by patrickjtoy** [comment]
@jbrown215 I'm not sure I understand your question. I will try to clarify though: The function `elemCurried` is a representation of an untyped function in a third-party library. It would have some internal logic for deciding what the received type is and perform the necessary steps. The declarations are just to help flow determine if the function is being called in a legal manner by the consumer of the library.

Hopefully that makes sense!

**Comment by jbrown215** [comment]
@patrickjtoy Your explanation makes sense, but then the type of elemCurried doesn't make so much sense. polymorphism (via <a>) makes the function read:
"for all types `a`, we take a value of type `a` and return ___"

So overloading over "all types" isn't faithfully modeling the semantics of this third party lib.

**Comment by patrickjtoy** [comment]
@jbrown215 You do have a valid point. The library has some of its own data types and in the case of the function `elem` the value of type `a` is constrained to the type class `Setoid`. I'm making an attempt to create valid Flow types for the library, but running into an issue where the examples provided with the library indicate that, for instance, the primitive `string` is a valid `Setoid`. My initial thought was to provide function overloads to circumvent this issue, but perhaps that isn't the right approach.

**Comment by jbrown215** [comment]
How about:
```
declare function elemCurried<a: Setoid>(a: a): 
((f: { [key: string]: a }) => boolean | 
(f: Array<a>) => boolean)
```

If you can determine which subclasses of `Setoid` lead to certain behavior you'll be able to make more a more accurate libdef :)

**Comment by patrickjtoy** [comment]
Thanks for the suggestion. Something like that would definitely work for all data types which are subclasses of `Setoid`, however Flow doesn't know that the primitive `string` is a member of `Setoid` (from the perspective of the library). It may be that the library is flawed here, in that it's definition of `Setoid` doesn't appear to match the methods of `string`.

**Comment by jbrown215** [comment]
Hmm, yea it's hard to type libraries that weren't written with types in mind. To me, that's usually indicative of sketchy API design. Types are a concise way of explaining the high level details of a function. If you can't capture the meaning of your function in a type (not necessarily Flow's current set of features, but a reasonable looking type), then that's probably indicating that your function is too complicated and should be simplified.

**Comment by patrickjtoy** [comment]
Fair enough, thanks for the help thinking things through!

**Comment by jbrown215** [comment]
No problem, sorry we couldn't come to an elegant solution :\

Good luck!

As for an explanation of the behavior, Flow will pick the first function signature that matches the arguments given. This is usually desirable and a lot of overloading relies on it today. I'm going to close this issue, but feel free to discuss with us / the flow-typed people further on discord if you want more support!

https://discord.gg/8ezwRUK
