### ISSUE TITLE
JSX is not validating properly

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#752]
Seems like JSX fragments have `any` type instead of `ReactElement` or similar.
```
/* @flow */
var foo: string = <div>Error!</div>;
```
http://tryflow.org/#e6774c44067fa1f57ca16afb2773d9ef

**Comment by samwgoldman** [comment]
[Yup](https://github.com/facebook/flow/blob/2be7a3c723573ed7ab8f8b2104e16204968b0f11/src/typing/type_inference_js.ml#L3935). Good catch. Works for capitalized elements in JSX, but not lowercase/built-ins.
