### ISSUE TITLE
Flow requires me to explicitly annotate useState only if I return the setter function

### ISSUE THREAD

**Issue by folz** [facebook/flow#7521]
Flow version: 0.93.0

## Expected behavior

Flow should allow me to return the `setArg` function in `[arg, setArg] = useState('initial')`, e.g.:

```js
export const useHook = (initial: string) => {
  const [arg, setArg] = useState(initial);

  return [arg, setArg];
};
```

## Actual behavior

Flow requires I provide an annotation to the `useState()` call, but only if I return the setter function. If I do not, I am not required to annotate `useState()`.

**Return only the arg, not the setter:**

```js
export const useHook1 = (initial: string) => {
  const [arg, setArg] = useState(initial);

  // type-at-pos shows
  // arg: string
  // setArg: ((((string) => string) | string)) => void
  
  return arg;
};
```

**Return the arg and setter, without explicitly specifying \<S\>**

```js
export const useHook2 = (initial: string) => {
  // Missing type annotation for `S` [...] implicitly instantiated at call of `useState`.
  const [arg, setArg] = useState(initial);

  // type-at-pos shows
  // arg: any | string
  // setArg: ((((any) => any) | any)) => void

  return [arg, setArg];
};
```

**Return the arg and setter, do explicitly specify \<S = string\>**
```js
export const useHook3 = (initial: string) => {
  const [arg, setArg] = useState<string>(initial);
  
  // type-at-pos shows
  // arg: string
  // setArg: ((((string) => string) | string)) => void

  return [arg, setArg];
};
```

## Link to Try Flow

[View on Try Flow](https://flow.org/try/#0JYWwDg9gTgLgBAbwK4GcCmBlGBDGaC+cAZlBCHAORRrYDGMFA3AFDMD0bcASmjElADs4EAQBsAnnBgALNHGxQA5gBo4AiPBlz0MPFAB0zNAA9IsOLREp4qNAAkIEANYBGOAF44ACmADgMYGxRAC44ayhfRQBKDwA+RGY4Cyt4AG0FFTDeAEElAF0POFssXDQfPwCgqJZEuA4pcTA0AFpcZsgUMOkIAHcUWvqM0PDIgc4dXMVQrxmvEYFouLCYCIWYgB9l1eiY93iANwhgABNa2uo+QXklFnwa+p5LoS1rxXkBY6zdNChVHv9ukh4CYwKJgLR-BIwk0IURxJE4AAeDCxIymaDwSwCaxFdAOZwAJkK5X8gRCW0iu3iCFqWJx6SUqgm+UKxRweBJlVE1VYSXqMEaLTaHS6vX6fM4Q3ekk280UYy+k2ms2wAnEVOlG01GsOJ15cAu-CEDMyzMUeVu904jyNUlkr3enx0elUxwgcBBYIhMChKBhwDhSIwhTlqJBGOS2JseMcTgAzMTfKSgsMVpSljSknS0hkmTkWZ42aVEaHOWSeUkFQKmq0YO0IJ0UN0+gqpXKFWblTM5Rqe3BZWm1jqjqdzrxbSa8zBJhbmHdmEA)

**Comment by jamesisaac** [comment]
I believe it's a case of the situation described here: https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8

> In order to infer a type, Flow needs to see all the values that might reach a given position. In order to infer types in input positions which are exported from a module, Flow would need to analyze files together with all of their transitive dependents. This is called “global” type inference, and while theoretically possible, this would be impossible to scale to the size of our codebase.
> 
> Instead of global type inference, Flow makes a humble request: annotate the input positions of your modules and we can infer the rest. This makes it possible to infer modules in parallel in dependency order.

By exporting `setArg`, Flow can no longer globally infer all the possible values that could flow into that state (the fact that `initial` is a string is a bit irrelevant when it comes to overall safety of the codebase).

Either way, it's not like adding `<string>` is particularly cumbersome...?

Agree the error message could be clearer though, like mentioned in #7497

**Comment by folz** [comment]
Yeah, I was wondering if flow behaves because of the input-export situation you linked. And you're right, adding `<string>` is not cumbersome and is what I ended up doing. However, I wanted to flag this for two reasons:

First, because flow types `arg` and `setArg` differently based on whether I export `setArg`. My expectation is that if flow is able to recognize `arg` as `string` and `setArg` as `(string) => void` when I don't export `setArg`, flow should continue to recognize those types even when I export `setArg` as well. Or on the flip side, if flow requires me to annotate `useState()`, it should do so whether or not I export `setArg`.

Second, because based on the libdef for `useState`, it looks like flow ought to be able to infer both `arg` and `setArg` as `<S = string>`. That is, I don't think the act of exporting `setArg` should cause an generic type to be exported, since `<S>` should be made concrete with the type of the `initialState` argument.

```js
declare export function useState<S>(
  initialState: (() => S) | S,
): [S, ((S => S) | S) => void];
```

Of course, I may be misunderstanding what Flow does when it tries to infer types from arguments. If so, I'm sorry for the noise and please feel free close the issue.

**Comment by jamesisaac** [comment]
As far as I understand the point is: if you're *not* exporting `setArg` outside of the file, Flow can trivially find all usages of it, and therefore infer a type for `S` that satisfies all those usages.  It doesn't matter if `initialState` is of type `string`, because that could still satisfy an `S` of, say, `string | number`.

However, if you export it, there are now thousands of other potential call sites, and solving inference around that becomes a lot more challenging.  For reasons of performance on large codebases, the Flow team made the conscious decision to force type annotations in this instance.  This gains abilities such as parallelisation, like they mention in the blog post, without sacrificing soundness.

While in theory yes it might be the better DX to globally infer all the inputs anyway (and like they say in the blog post that would have worked before Flow 0.16), it's a conscious trade-off that's been made for practical performance reasons.

**Comment by folz** [comment]
I see, that makes sense. Thanks for your time and the explanation.
