### ISSUE TITLE
Optional property error when property is defined with static defaultProps

### ISSUE THREAD

**Issue by rumax** [facebook/flow#7524]
Flow version: 0.78.0 / 0.86.0

## Expected behavior

Flow understands `static defaultProps` and optional properties properly

## Actual behavior

Flow does not respect default properties defined with `static defaultProps`

* Link to Try-Flow or Github repo: https://www.npmjs.com/package/react-native-view-pdf

Example:

Assuming I have the properties defined as following:

```
type Props = {
  /**
   * A Function. Invoked on load error with {nativeEvent: {error}}.
   */
  onError?: (Error) => void,

  /**
   * A Function. Invoked when load completes successfully.
   */
  onLoad?: () => void,

 ....
```

And have 

```
static defaultProps = {
    onError: () => {},
    onLoad: () => {},
    ...
  };
```

Trying to use them lead to flow error:

```
onError: (event: any) => void;
onError(event: any) {
    const { nativeEvent } = event || {};
    this.props.onError(nativeEvent || new Error('unknown error'));
}
```

<img width="653" alt="screen shot 2019-03-03 at 12 21 03" src="https://user-images.githubusercontent.com/2707180/53694426-fe34fc80-3dae-11e9-94ee-33b811530836.png">

## Workarounds

Workarounds like making the properties required are not acceptable because:

- It leads to confusion in documentation
- It leads to ESLINT error 

<img width="539" alt="screen shot 2019-03-03 at 12 24 02" src="https://user-images.githubusercontent.com/2707180/53694445-51a74a80-3daf-11e9-9338-fe1f79d08d49.png">

**Comment by jbrown215** [comment]
It looks like you're conflating `Props` with `Config`. In `Props`, you don't need to mark the defaultProps optional. `Props` represents the type of `this.props`, so if you make props optional there then even specifying them in defaultProps won't make them optional.

When you pass props to a component, Flow uses the `Config` of the component to determine which props are required. Flow automatically takes your Props and defaultProps and figures out the Config.

**Comment by rumax** [comment]
So you want to say that I should have:

```
type Props = {
  onError: (Error) => void,
 ...
``` 

(without `?`) ?

But this was my initial point. When I want to provide the component, such syntax is confusing, because from the definition I clearly see that the property is requires, which means that the user should provide `onError` callback. But it's wrong, because it should be optional and searching for `defaultProps` in each component doesn't make any sense for the user.
