### ISSUE TITLE
Flow 0.92.0 and 0.93.0 not supporting styled-components + example code

### ISSUE THREAD

**Issue by Ziv-Barber** [facebook/flow#7525]
Flow version: 0.92.0 and 0.93.0

```
   // @flow

   import React from 'react' // eslint-disable-line no-unused-vars
   import styled from 'styled-components'

   type MyProps = {
        className?: string
   }

   const MyComp = (props: MyProps) => (
       <span className={props.className}>Test</span>
   )

   const StyledMyComp = styled(MyComp)`
     margin: ${(props) => props.theme.spacing.unit}px;
   `
```

## Expected behavior

To work (working in 0.91.0

## Actual behavior

Can't find props.theme
props.theme.spacing.unit is not a string

**Comment by jamesisaac** [comment]
This is more an issue in the libdef for `styled-components`, which makes more sense in the `flow-typed` repo where those live.  The release notes for Flow 0.92 state:

> Likely to cause new Flow errors:
> Some fixes to tagged template literals will surface a new set of pre-existing errors!

So, Flow has become stricter, and to be compatible with Flow 0.92+ the libdef will require some tweaks.

It looks like there's an issue open for this in `flow-typed` already: https://github.com/flow-typed/flow-typed/issues/3170

**Comment by Ziv-Barber** [comment]
OK thanks. I wasn't sure where it should belong.
I'll close this one.
