### ISSUE TITLE
$Exact<typeof ... not working

### ISSUE THREAD

**Issue by penx** [facebook/flow#7526]
Flow version:
0.94.0

## Expected behavior

I would expect

```js
const defaults = {
  one: 'one',
  two: 'two'
};

type MyProps = $Exact<typeof defaults>;

const overrides: MyProps = {
  one: 'a',
  two: 'b',
  three: 'c'
};
```

to be equivalent to

```js

type MyProps2 = {|
  one: string,
  two: string
|};

const overrides2: MyProps2 = {
  one: 'a',
  two: 'b',
  three: 'c'
};
```

And to error with

```
Cannot assign object literal to `overrides` because property `three` is missing in `MyProps` [1] but exists in object literal [2].
```

## Actual behavior

No errors when using `type MyProps = $Exact<typeof defaults>;` whereas

```js
type MyProps2 = {|
  one: string,
  two: string
|};
```

correctly raises an error

* Link to Try-Flow or Github repo:

https://flow.org/try/#0MYewdgzgLgBAJgUwGYEMCuAbKEYF4YDeAUDDOAgFwwDk51ANCTFAO4hXWsjVEC+A3ESJQAngAcEMALIiACgCcQYnPgAkAUQAeKYFAA8oiSCTxk6LBAB8goqEiwQANwTz5AS0QQqMhUpWEmcg4UBiYuDgAjUNIoAAt5BEoaYB4BIWFxSR9FZQAmPEIAH0CwJOh3MABzRhi2KnK3KqJCtNtwaDJnVw8ECFzvORy+guJSIJoQmuY6miipuISk6hS+GyIgA

**Comment by SamChou19815** [comment]
Working now
