### ISSUE TITLE
Try-catching an error makes class type `empty` within the class's methods

### ISSUE THREAD

**Issue by talbenari1** [facebook/flow#7530]
Flow version: 0.94.0

## Expected behavior

```js
try {
  throw new Error();
} catch (e) {}

class Foo {
  bar(foo: Foo) {
    foo.nonexistentProperty(); // this should emit an error
  }
  
  static baz(foo: Foo) {
    foo.nonexistentProperty(); // this should also emit an error
  }
}

// calling them with invalid arguments should emit errors too
new Foo().bar(1234);
Foo.baz(1234);
```

## Actual behavior

`Foo` is apparently empty within `bar` and `baz`. However, **if you remove the try-catch block, the errors appear**.

([Try Flow](https://flow.org/try/#0C4JwngBA3gUBHABYgPYHcIDsCmGCiIqIAFAJQDcMAvhAMYCGwtiEx2p0VMMtANvQGcBEAGIoU0OBABG9EgDNxALlHiOsePEUoAdJhQ4AHgEsBwbJmAAFVAAdsIYGDLkIAejcJEpiAMQoAV14AEwhsAFtjYAh6TDDCFBApLngpM0ZjWhl6AC9ibRUxFHUpLXE9A2wTMwtrOwcnF3dPJB8-QJCY3gEJCKiYuIciZOpuDzp6Xl5jTABzLwiINCiWGYA3SeNQuVmA8NrhdqDQvuihxOFgcRgcDCKyHVkSAEYAJgBmABYKGCLH3OIby+FCAA))

([Try Flow with the try-catch removed](https://flow.org/try/#0MYGwhgzhAEBiD29oG8BQ1oCMwCcAUAZogFxyICUK6G0R8AdAHbyMCmAHgJYQAurjPAAo54AB1Y4eATzzkA3NAD0i6DwAW3aBDXwAriAAm0VgFtOPaGEbGcInNQC+1arzA9OwLGABehEmXhKNBpaRCYWDm4+AWExCWlZBWVVDRhtPUNLEAgkU3NLawk7R1QnVGTgMBAQTkYAcxTTaAB3czVoWoA3Ks4jXDrdE34eNJ19IzyLIvgcGB5EVDZmgNl6bHwARgAmAGYAFnlUBAZsX239+SA))

**Comment by jbrown215** [comment]
It also errors correctly if you remove the throw. Thanks for reporting!

**Comment by also** [comment]
It's more than just classes:

```js
let x: number[] = [];
try {
  throw new Error(`just capturing a stack trace`);
} catch (e) {}
// this is fine
x.push(null);
```

`x` has type `empty` after the catch.

[Try Flow ](https://flow.org/try/#0DYUwLgBAHgXBB2BXAtgIxAJwNoF0IF4JcBuAKDAwE8IBvUiCMACwwHsB3BETgUQzYwAKAAYArRAGdIAYwCGABzCIMAS3gBzCLIhTZ0gNaMMekMICUZAL4Q5YaUwiCQZ2pdIB6d4yYqJEXxAAZmogpFAAdPKSTIJIwMAWQA)
