### ISSUE TITLE
Because an indexer property is missing in  null or undefined

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/flow#7538]
I'm receiving this warning from flow:
```
Cannot get `rates[exchange.baseCurrency]` because an indexer property is missing in  null or undefined 
```
![flow1](https://user-images.githubusercontent.com/3165839/53998904-41310000-4120-11e9-835b-fc435dc9b142.png)

But I already checked the `rates` variable. I can fix this warning replicating the check inside of the map function but I think it is not the best approach.

![flow2](https://user-images.githubusercontent.com/3165839/53998948-67ef3680-4120-11e9-862f-d27184e759c7.png)

So is it a bug or I'm doing something wrong?

Flow version: "flow-bin": "^0.93.0"

**Comment by jamesisaac** [comment]
This is probably a case of the first question discussed in the new [FAQ section](https://flow.org/en/docs/faq/) of the docs.

Flow doesn't keep track of side effects, so as far as it's concerned, your `mapToArray` function call could well be mutating `rates`, so it invalidates your check.  You can get around this by having a local variable for `rates` within the `renderExchanges` function.  Marking `rates` as [read-only](https://flow.org/en/docs/types/utilities/#toc-readonly) could be another solution.

If that doesn't answer your question and you'd like more help, please try and create a minimum reproduction on https://flow.org/try/ before reopening - there's a lot of context missing in your screenshots which makes it harder to provide help.
