### ISSUE TITLE
No error when reassigning variable in a closure

### ISSUE THREAD

**Issue by JakeCoxon** [facebook/flow#7541]
Flow version: 0.94.0

## Expected behavior

Since flow won't know whether the closure is called or not, I would expect the type of `a` to be `string | number`

## Actual behavior

Type of `a` is `string`

[Flow try](https://flow.org/try/#0GYVwdgxgLglg9mABAWwJ4DFwQBQEoBciAzlAE4xgDmiA3gFCKIA2AplIgIaIC8iARFxLkqfANwNEEgNoBGALoA6YHFIBRDhAAW2PDwB8tCYy68ATOMYBfXBcmNSbEKSQdRiAPTvOiGEWJkKSjpLOiA)

```javascript
function myFunc(): string {
  let a = "a string";
  
  [1].forEach(() => {
    a = 2;
  });
  
  return a; // a is string
}
```

**Comment by dsainati1** [comment]
Yikes. This is pretty scary. Thanks for pointing this out. I think we have a fix in the works that should be out in one of the next versions.
