### ISSUE TITLE
String is incompatible with string literal from computed union

### ISSUE THREAD

**Issue by langri-sha** [facebook/flow#7547]
For a union of object types that all contain some property whose value is a literal string type, it's not possible to create a union of those string literal types that can be used as an enum.

Flow version: 0.94

## Expected behavior

Would expect that what looks like to result in an enum to work, a la:

```
type ActionType = 'ALPHA' | 'BETA'

;('ALPHA': ActionType)
```

## Actual behavior

Instead `;('ALPHA': ActionType)` satisfies `'ALPHA'`, but doesn't satisfy `'BETA'`. 

### Example with `$PropertyType`:

```
const moduleActionCreators = {
  exportA () { return { type: ('ALPHA': 'ALPHA') } },
  exportB () { return { type: ('BETA': 'BETA') } }
}

type FnReturn = <A>(() => A) => $Exact<A>
type ActionCreator = $Values<typeof moduleActionCreators>
type Action = $Call<FnReturn, ActionCreator>
type ActionType = $PropertyType<Action, 'type'>
  
;('ALPHA': ActionType)
```

[Try Flow :link:](https://flow.org/try/#0MYewdgzgLgBAtiAJgVwDYFMCCwoEtwDCATugIZQhEQwC8MA3gFAwzoAeADpVJjABQBKBjBJRkRMMKgBPDugBc-AOSYAMgAUAEpiWKVG7UqEBfGMYA0zVp24AhfkPoj0YiVNkLltgKIAVHXo+-kZmZozGjIwycjAAYmAASi7iknQAPJgAfHyCtJkwmEI0+QAk3mykOBmZUR4FOPhgxGQURLQwJQBqpKjI6BBp0eggAGbwSGhYDYQk5JQQNUP1eODtJQQ9qGnxSa5g5suNzXNEi3XYK2C+dXQl6kQgckQy13IZ0-swSkNKNSyMAG4+PotAFDuBXugBIwgA).

### Example with `$ElementType`

```
const moduleActionCreators = {
  exportA () { return { type: ('ALPHA': 'ALPHA') } },
  exportB () { return { type: ('BETA': 'BETA') } }
}

type FnReturn = <A>(() => A) => $Exact<A>
type ActionCreator = typeof moduleActionCreators
type Action = $ObjMap<ActionCreator, FnReturn>
type ActionType = $ElementType<$ElementType<Action, $Keys<Action>>, 'type'>
  
;('ALPHA': ActionType)
```

[Try Flow :link:](https://flow.org/try/#0MYewdgzgLgBAtiAJgVwDYFMCCwoEtwDCATugIZQhEQwC8MA3gFAwzoAeADpVJjABQBKBjBJRkRMMKgBPDugBc-AOSYAMgAUAEpiWKVG7UqEBfGMYA0zVp24AhfkPoj0YiVNkLltgKIAVHXo+-kZmZozGjIwycjAAYmAASi7iknQAPJgAfHyCtJkwmEI0+QAk3mykOBmZUR4FOPhgxGQURLQw0eggAGbwSGhYDYQk5JQQtTHYeODtJQDyAEYAVgCypBwZQ00jreZxickSNZ3102C+dXRlGHDoYFAXcmnX6Lf3j+ibZ3slANLo0ggX0amUyeyUnSUNRYjAA3Hx9FoAqdGh8BIwgA).

**Comment by SamChou19815** [comment]
Should be fixed a long time ago
