### ISSUE TITLE
config option default-with-existential

### ISSUE THREAD

**Issue by vaukalak** [facebook/flow#7549]
## Motivation (why to not deprecate `*`)

I believe that inference is the most powerful side of flow-type, also I really appreciate performance orientation flow team has taken. However, completely deprecating `*` in favor of performance, can makes flow working faster, but writing, reading and supporting code gets way slower. For that reason I think flow should allow `*`, when people care more about readability rather then type-check performance, because:
1 - not all projects are large-scale applications (for example you may build a small micro-service).
2 - developers may want to use `*` only in a some specific areas of their application.
3 - sometimes it's better to concentrate, on the feature developer is working on now, and stub what needed with `*`, and when done just fix type-check performance warnings (thanks to `deprecated-type`).

I have a project with about 100k lines of codes (without node_modules), and I actually do not have any big performance issues, rarely type-check runs for about 1-2 sec, but I'm totally fine with that, against increasing codebase with really obvious declarations.

## Proposal

Add property under `[options]` called `default-with-existential` to config, that will default missing generic function type annotations as `*`, with following rules:
```
connect() -> connect<*, *, *, *, *>()
connect<Comp>() -> connect<Comp, *, *, *, *>()
connect<Comp, State>() -> connect<Comp, State, *, *, *>()
connect<*, State>() -> connect<*, State, *, *, *>()
```

## Use case

I think participators of this discussion may like this feature: https://github.com/facebook/flow/issues/7125

## PS

If flow team is not going to completely remove `*` from the project, please consider introducing `bad-performance-type` to not list `*` with other `deprecated-type`.

**Comment by goodmind** [comment]
@vaukalak but case with `connect` can be used with new placeholder type

**Comment by vaukalak** [comment]
@goodmind thanks for your answer, could you please describe a bit more what do you mean?

**Comment by goodmind** [comment]
@vaukalak https://github.com/facebook/flow/blob/master/tests/implicit_instantiation/test.js

**Comment by vaukalak** [comment]
@goodmind thanks for your answer, actually I've tried to find documentation about `_` vs `*`, but no luck. Actually `connect` was not here, but I found some cases that do not work with `_`, but works with `*`:

https://flow.org/try/#0MYewdgzgLgBAhgJwXAngdWQBxgXhgCjgEoAuGAEgCUBTOAEwHkwAbFAQSVQB4B9APlwCA2nAC6AbgBQMGbJmTCndFnwBGUhRr0mrDshRcwAVwC2AI2oI+RKZKA

https://flow.org/try/#0MYewdgzgLgBAhgLhgEgEoFM4BMDyYA2AngIIBOpchAPAPoB8MAvDANoCMANAEwcDMAugG4AUAApEKDNjxEyFamACuAWwBG6UnQCUgoA

So for now `_` looks identical to `*`, but with some bugs :)

**Comment by goodmind** [comment]
@vaukalak its not bug, its intentionally less powerful

**Comment by goodmind** [comment]
@jbrown215 can you clarify if Flow team plans to remove `*` completely from code base, or it would be always under `deprecated-type` and never removed?

**Comment by jbrown215** [comment]
@avikchaudhuri is a better person to answer that question. I believe we intend to remove it eventually.

`_` is the same thing as not supplying a type argument to a call/constructor and it can only be used as an explicit type argument to calls/constructor. So these two calls are equivalent:

```
function test<T1, T2>() {}

test();
test<_, _>();
```

**Comment by vaukalak** [comment]
@goodmind Thanks for your effort on this issue. After applying some refactoring my code, I was able to achieve approximately same results for `_`, that I had with `*`. Not as cool as it was, but can leave with that. However I think it should be possible to add config option, to allow skipping trailing `_` in function invocation, like that:
```
connect() -> connect<_, _, _, _, _>()
connect<Comp>() -> connect<Comp, _, _, _, _>()
connect<Comp, State>() -> connect<Comp, State, _, _, _>()
connect<_, State>() -> connect<_, State, _, _, _>()
```
Cause right now it's possible to write:
```
function test<T1, T2>() {}

test();
test<_, _>();
```
but not:
```
test<_>();
```
