### ISSUE TITLE
Set is missing entries() and values() method declarations

### ISSUE THREAD

**Issue by bolinfest** [facebook/flow#755]
https://github.com/facebook/flow/blob/master/lib/core.js#L338 does not have everything in https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set

**Comment by bolinfest** [comment]
There is also a `keys()` method. Note that:

    Set.prototype.keys === Set.prototype.values

is `true`.

**Comment by jamesgpearce** [comment]
You are always a month ahead of me ;)
