### ISSUE TITLE
Type guards cannot be extracted

### ISSUE THREAD

**Issue by mulholio** [facebook/flow#7551]
## Expected behavior
Flow infers types when type guards are extracted into named variables

## Actual behavior
Flow does not infer types from type guards which are extracted into variables

----

I am writing a function which contains a type guard. I would like to extract this type guard to a more informative variable like so:

```javascript
/* @flow */

function maybeParseJSON<T>(
  input: string | T,
  defaultValue: T
): ?T {
  const defaultIsDefined = typeof defaultValue !== 'undefined';
  const isJSON = typeof input === 'string'; // extracting to this variable breaks type inference
  if (isJSON) {
    // parse JSON
  } else { // i.e. !isJSON / is a string
    if (typeof input === 'undefined' || defaultIsDefined)
      return defaultValue;
    return input;
  }
}
```

Unfortuantely, when placed outside the `if` clause, Flow cannot infer that the return type is not a string and I get this error:

```
Cannot return `input` because string [1] is incompatible with `T` [2].
```

It seems to me that type guards such as `typeof input === 'string'` should be extractable.

#### REPLs both with the variable inline and extracted
[With extracted variable](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBbAQw'E8AjAUwAUKAnAZzoCkBlAeQDkAPABUAfAApUYMIWwAHTPgBcYVvmYyA5mAA+YIQBpJYACZ0oFTDHwA1CjEx1lQ1AEplAfiFgA3kdwlVEzMLKwBJVgARMxk6YzAAXjB8Klk6OCgg80sbOwcwAEJ4xIByHFMoGONigG4-APxpVm5+BKSUtIyZeQaiktV1bA0ao0IMsUIm3j4XHyMpYGAwWRZ2MGa+IwBfMDoYVe8wBekAOjpjgon1w8awChU1TTnpMeTU9Ok5BQSisFLscsqxR0unKIXw4SiFWwsRcTykzDo+EwzFIoOytnsdFqUnhiORpC6CmxYE2qE2QA) (with bug)
[Without extracted variable](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBbAQwE8AjAUwAUKAnAZzoCkBlAeQDkAPABUAfAApUYMIWwAHTPgBcYVvmYyA5mAA+YIQBpJYACZ0oFTDHwA1CjEx1lQ1AEplAfiFgA3kdwlVEzMLKwBJVgARMxk6YzAAXjB8Klk6OCgg80sbOwcwAEJ4xIByHFMoGONigG4jQgyxZNT06TkFBKKwYtV1bA1ilx8jKWBgMFkWdjBufiMAXzA6GCnvMFHpADo6DYLCVhm+NelWMAoVNU1h6QamtIyZeXwOkrLo7FjinV1ykPxwqIq72MLiuUmYdHwmGYpB+2Vs9jotSkYIhUNIDwUSLAc1QcyAA) (no bugs)

**Flow version:** 0.92.1 (local) also occuring in 0.94 in REPL.

**Comment by FezVrasta** [comment]
You can use `%checks` to make the type guard work in its own function.

```
function isJson(input): boolean %checks {
  return typeof input === 'string';
}
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxCBnAKXJIApDsAHTfASgC4wAjOOGAUwCGpAKS4AFv1wBrcmADeqMGABO-fJhWl8AT0b84UMkxZgAvBbABycvhUMA5lYDcqAL7oseIiTABbQR0ufgAFQRVyfkoAZQB5ADkAHgAVAD5aJWNmfE5be2wHMAAfMGSAGkyAE34oQUwYfAA1QRhMfk5k1A4wAH5khUzcElswatr6-ABJcgARGoZ+SvMwXX1DUZq6hubW-jAAQksrHDGFypdMwiN6KhpsehM2VgHlZWBgMEZwyLAYhMy3GB+DAfvIwO8yAA6fiQg4UP7xcFkOSCMB5RyZZRXMC0VYGIwMbLmI4nebYRZWYolMZbKazMmLViY15qDRaDbjbYtNquV6qdSaUiEli8sAeNxAA
