### ISSUE TITLE
Classes do not have callable signatures

### ISSUE THREAD

**Issue by talbenari1** [facebook/flow#7552]
Flow version: 0.94.0

## Expected behavior

```js
class Foo {}

(Foo: { (): Foo }); // This should be OK
```

## Actual behavior

```
3: (Foo: { (): Foo });
    ^ Cannot cast `Foo` to object type because a callable signature is missing in statics of `Foo` [1] but exists in object type [2].
References:
1: class Foo {}
         ^ [1]
3: (Foo: { (): Foo });
         ^ [2]
```

This bug makes it impossible to define a type that accepts any arbitrary callable object. In my use case, I wanted to enforce that the right-hand-side of an `instanceof` check was callable, without restricting the type of the callable object. I get the same error if I change the type to `() => void`.

([Try Flow](https://flow.org/try/#0MYGwhgzhAEBiD29oG8C+AodAKB8BcK0WAlAbtKsQNxA))

**Comment by goodmind** [comment]
@talbenari1 but class isn't callable, do you mean `new`able ?

**Comment by talbenari1** [comment]
...What? Classes most certainly _are_ callable, by which I mean that they have the [[Call]] internal field as described in the ECMAScript spec. Just because it's a semantic error to call them without `new` doesn't mean they're not callable (the [algorithm for calling a function](https://ecma-international.org/ecma-262/9.0/index.html#sec-ecmascript-function-objects-call-thisargument-argumentslist) explains what I'm talking about).

Why do I care, you might ask? Well how else can I define _the type of all `val` where `typeof val === "function"`_? I get that nominal typing gets in the way here a bit, but there really should be a way to encode that type.

**Comment by slawomir-brzezinski-at-clarksons** [comment]
Another use case is having callable a type, say `Foo`, and being able to group all it's utility functions in static members of the very type, say `Foo.isFootastic(value)`.

**Comment by SamChou19815** [comment]
We don't plan to support this pattern, since it prevents us from detecting class that should be newed instead of called.
