### ISSUE TITLE
Cannot resolve name `SpeechSynthesisVoice`.Flow(InferError)

### ISSUE THREAD

**Issue by lensbart** [facebook/flow#7555]
## Missing/Incorrect APIs
SpeechSynthesisVoice

## Relevant documentation
https://developer.mozilla.org/en-US/docs/Web/API/SpeechSynthesisUtterance/voice

The Flow plugin for VSCode recognises `SpeechSynthesisVoice` as an interface in the popup when I mouseover the type error, but it shows up as an error as well:

> any(implicit)
> interface SpeechSynthesisVoice
> Cannot resolve name `SpeechSynthesisVoice`.Flow(InferError)

**Comment by goodmind** [comment]
@lensbart are you willing to do pull request?

**Comment by lensbart** [comment]
Currently I don’t have the time but I might look into it later (except if OCaml is required because I don’t have any experience with the language)

**Comment by goodmind** [comment]
@lensbart it isn't. Look into `lib` folder it is bunch of js files

**Comment by goodmind** [comment]
https://github.com/facebook/flow/pull/7740
