### ISSUE TITLE
Support for arm64 architecture

### ISSUE THREAD

**Issue by ossdev07** [facebook/flow#7556]
Dear Team,

We were able to build the flow package for aarch64(arm64) architecture and generate flow binary.

Need flow-bin to execute packages like preact, chalk, graphql and many more packages in arm64 platform, as there is no existing binary in releases to download for arm64 platform all these packages are failing in arm64 platform.

Please guide me to get flow in the official aarch64 repository and in releases link i.e. https://github.com/facebook/flow/releases/.

Thanks in advance.

Regards,

**Comment by mroch** [comment]
to be attached to the github release and included in flow-bin, it needs to be built by appveyor or circleci, so that we can verify its integrity and so it's done automatically (can't block the release of flow-bin on someone manually building the aarch64 version). I think that means making circleci cross-compile for aarch64. is that something you're able to take on?

**Comment by ossdev07** [comment]
@mroch I have compiled in local arm64 machine and binary has been created successfully. But could you please let me know how to add it to appveyor or circleci to generate arm64 binary. I have used shippable CI to generate binary and commit to same git package. It can be viewed in https://github.com/ossdev07/flow and link to shippable console used to generate and copy the binary is https://app.shippable.com/github/ossdev07/flow/runs/8/1/console.
Could you please guide me how i can get the same in releases?
Thanks in advance.

**Comment by ossdev07** [comment]
@mroch Circleci and appveyor does not support arm64 currently. Have added .drone.yml to get the binary and add it to github releases. Please find below console of drone:
https://cloud.drone.io/ossdev07/flow/10/1/2.

**Comment by ossdev07** [comment]
@mroch 
CircleCI and AppVeyor CI does not support native compilation in arm64 platform. Could you please suggest any other CI or approach to build flow package in arm64 platform.

Thanks in advance.

**Comment by ossdev07** [comment]
> to be attached to the github release and included in flow-bin, it needs to be built by appveyor or circleci, so that we can verify its integrity and so it's done automatically (can't block the release of flow-bin on someone manually building the aarch64 version). I think that means making circleci cross-compile for aarch64. is that something you're able to take on?

Currently pursuing on cross-compiling flow package with circleci. Will update once i get solution.
Thanks in advance.

**Comment by akhilgupta74** [comment]
@mroch @gabelevi @samwgoldman 
Hey Guys,
This really looks exciting and I am getting a lot of hits regarding Flow for ARM64.
May I know, what needs to be done to get this included in your official support list?

I do possess ARM64 servers at my end to support native ARM64 builds and do all experimental stuff. 
What I need is support from your expertise to move further 😄 

Cheers,

**Comment by rhenwood-arm** [comment]
On the topic of providing platform support: Looking at the assets in the releases here:
https://github.com/facebook/flow/releases
It would appear to my reading that there is currently an assumption in the release file names the platform x86_64. Is there an effort to develop a suitable naming scheme to enable multiple binaries (x86_64, aarch64, etc) to be released?

**Comment by mroch** [comment]
can you please try this binary from #8606?

https://40977-25880891-gh.circle-artifacts.com/0/flow-linux-arm64.zip

cc @ossdev07 @rhenwood-arm @odidev

**Comment by odidev** [comment]
@mroch,

Thanks for the binary. I have tested this in my local arm64 machine and it is working perfectly fine.

**Comment by odidev** [comment]
@mroch,

May I know when are you planning on releasing the arm64 flow binary?
