### ISSUE TITLE
npm install --save-dev flow-bin@0.95.0 fails

### ISSUE THREAD

**Issue by jwineman** [facebook/flow#7557]
```
$ npm install --save-dev flow-bin@0.95.0
npm ERR! code ETARGET
npm ERR! notarget No matching version found for flow-bin@0.95.0
```
Flow version: 0.95

I noticed the npm package points to https://github.com/flowtype/flow-bin which doesn't have this release.  Which of these repositories is supposed to be the source of truth?

## Expected behavior
https://github.com/facebook/flow/releases/tag/v0.95.0 installed
## Actual behavior
Error (above)

* Link to Try-Flow or Github repo:

**Comment by goodmind** [comment]
@jwineman it still isn't published

**Comment by goodmind** [comment]
flow-bin is different repository https://github.com/flowtype/flow-bin
