### ISSUE TITLE
Add $Arguments feature for extracting function call signature

### ISSUE THREAD

**Issue by mike1808** [facebook/flow#7573]
Now, it is impossible to extract the function call signature. There are some libraries, like [flow/Arguments](https://github.com/lttb/flown/blob/master/src/Arguments/index.js) which provide types for extracting arguments but they don't support functions where min_aritiy != arity.

Problem example:

```js
declare function arguments<A>(() => any): []
declare function arguments<A>((A) => any): [A]
declare function arguments<A, B>((A, B) => any): [A, B]
declare function arguments<A, B, C>((A, B, C) => any): [A, B, C]

type Arguments<F> = $Call<typeof arguments, F>
  
declare function extractReturn<R, F: (...any[]) => R>(F): R;
  
type Return<F> = $Call<typeof extractReturn, F>;

function decorate<F: Function>(f: F): (...Arguments<F>) => Return<F> {
	return (...args) => f(...args);
}

const foo = (arg1: string, arg2?: number) => {};

foo('s');
foo('s', 0);

const bar = decorate(foo);

bar('s');
bar('s', 0); // error is thrown here
```

[Try Flow](https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtX1gHNkBbEVDAZwB4BBAPgApGBKeAXnoNQE8WAueAG0AugChQkWAhTpseAjGJkKNBs1ptO3PoKG1xk6HCRpMufEVLkqdADTwAQk0a0HjrVyi8Bwt08NwYxkzeUsla1V7JwcAYRd-RzjPHV99dzjxMQweAAcEWgiVWwAxLnZ4ABJYqAgIahz8nERFZRtKBzKxeHgJIOlTOQt4EAAPDBgoTAAlEAxkGFRqac7BRgA6Te8eURTpphLfaYBubt7GhFn5xeoyjiqauoa8kGaR8cmZuYXUTvpTsSycwKSQ4SYYEC3QQlUIWJiIaG+DabQptKJlPbfG53ADeYgAkHBrvhkesiJQUohSeSWKcAL5iMRgPCUDBIHA4e6MIgARkErJgWFQhAcRAATAB+QSoUgAIxAMBSOLpAMQHMYAHJKBraYD1VqNQ4AAy6pkstmy2D3UHgkCMNU4U2WmCa7W652uw3wE3HIA)

**Comment by SamChou19815** [comment]
We now have `Parameters`
