### ISSUE TITLE
Small HOC example doesn't work

### ISSUE THREAD

**Issue by feonit** [facebook/flow#7578]
Example:
```
//@flow
import React from "react";

const HOC = <Props>(C) => {
	class User extends Component<Props> {
		return (){
			return <C {...this.props}>test</C>
		}
	}
	return User;
};

const Name = ({name}) => <div>{name}</div>;
type NameProps = {name: string};
const NameWrapper = HOC<NameProps>(Name);

const test = (
	<NameWrapper name={'boo'} />
)
```
Flow version:
tested on 0.92.0 and 0.95.1
"react": "16.6.3",

## Expected behavior
Without errors

## Actual behavior
```
Cannot create NameWrapper element because props [1] is incompatible with Props [2].

 [2]  5│        class User extends Component<Props> {
       :
     15│ const NameWrapper = HOC<NameProps>(Name);
     16│
     17│ const test = (
 [1] 18│        <NameWrapper name={'boo'} />
     19│ )
```

https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCUBTAQwGNdwNpkcAiDYsmgbnnhOgDsBnXACQHkAwjgC8OADwAFSqi4A+ABSCAlKLk4A3vACQJSES5ccAVS4EMOAgA8sBDgBMjgqug52sUmfM07t9LACuGBw4Cspa2pH+QSHiwhoAdElYABaIXAmoXgC+crY84sCCcr7ZOmV+BIHBJmYYLNksbJw8OAByRMgEoqEaHJ0E2aoi6uL2iABucn0D2YXjUyxYAJ6o3R1d0tCyPTNdAFw4PBiIHADmjc3cuBsEAOoYRKhrFmICguK3W7KKt8pN7GuOHyuDECh0nwGDyeLxw-S6Ig0AHIAEbQaBI7I4YAlZRAA

I think it is a bug, some opinion?

**Comment by goodmind** [comment]
https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCUBTAQwGNdwNpkcAiDYsmgbnnhOgDsBnXACQHkAwjgC8OADwAFSqi4A+ABSCAlKLk4A3vACQJSES5ccAVS4EMOAgA8sBDgBMjgqug52sUmfM07t9LACuGBw4Cspa2pH+QSHiwhoAdElYABaIXAmoXgC+crY84sCCcr7ZOmV+BIHBJmYYLNksbJw8OAByRMgEoqEaHJ0E2aoi6uL2iABucn0D2YXjUyxYAJ6o3R1d0tCyPTNdAFw4PBiIHADmjc3cuBsEAOoYRKhrFmICguK3W7KKt8pN7GuOHyuDECh0nwGDyeLxw-S6Ig0AHIAEbQaBI7I4YAlZRAA

**Comment by feonit** [comment]
Thank you very much, it would be better if the error message became more informative in the future.
