### ISSUE TITLE
ReadOnly opaque type not checked within same file

### ISSUE THREAD

**Issue by nrabinowitz** [facebook/flow#7579]
Flow version: v0.94.0

## Expected behavior

With a standard opaque object type, I get appropriate type-checking within the same file:
```javascript
opaque type Foo = {|
  foo: 'foo'
|};
(null: Foo);
//  ^ Cannot cast `null` to `Foo` because inexact null [1] is incompatible with exact object type [2].
```
I expect the same type with `$ReadOnly` applied to have the same behavior.

## Actual behavior

The `$ReadOnly` type produces no errors:
```javascript
opaque type Foo = $ReadOnly<{|
  foo: 'foo'
|}>;
(null: Foo);
// No errors!
```
[Try Flow](https://flow.org/try/#0FAewDghgjgrgpgAgC4E8yIGIhAgvAgEgCU4IATAeQDsAbFAHgG8AfYBBAM2wC4EByLiD7BmAXwB8AbmDAAFFRg0avLCACUkoA)

Using `+` to mark the properties as read-only [works as expected](https://flow.org/try/#0FAewDghgjgrgpgAgC4E8yIGIhAgvAgbwB9gEEBqAM2wC4EByake4IgXwG5hgAKAOxgAbQXSwgAlByA).

**Comment by jbrown215** [comment]
Nice catch! Thank you for reporting.

**Comment by SamChou19815** [comment]
Now it errors
