### ISSUE TITLE
generic to be any type

### ISSUE THREAD

**Issue by HsuTing** [facebook/flow#7584]
## Proposal
Try to fix koa type error in [flow-type/flow-typed](https://github.com/flow-typed/flow-typed/pull/3229).

## Use case
```js
declare class events$EventEmitter {}

type Context = {
  body:  string | JSONObject | JSONArray | null,
};

type JSON = | string | number | boolean | null | JSONObject | JSONArray;
type JSONObject = { [string]: JSON };
type JSONArray = Array<JSON>;

type Middleware<C = {}> =
    (ctx: Context & C, next: () => Promise<void>) => Promise<void>|void;

declare class Application extends events$EventEmitter {
  use<C: {}>(fn: Middleware<C>): this,
}
  
let app = new Application();
  
app.use((ctx) => {
  ctx.body = 1; // This should throw erorr. I think `ctx` is `any` type here.
  ctx.body = 'test';
});

app.use<{}>((ctx) => {
  ctx.body = 1; // This throw erorr.
  ctx.body = 'test';
});
```
[Try it](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnxANxAOwC7IBIBRLPIgWwEtdcQZ4BvAXwCgXcBPABwQGEB7PCAAeueAF5GLePABG-YBwBcM5LhiVsAc3gAfeACkAygHkAcidkArcGP3HzAQRgwoHPfGwBXCBAA0LEwA3GycPIamZhIeahraHt7ksnQe8vwQIFDYCT4QHg4W1rb5kc6uHCFhCAWWNmBikgzwANqxmloAuioF8MHs3NWlLm7RZW4APAUAfCH94QCylMDAGQDusCDjvNHMUxLSMvAAFPXCKgJCovAAZPC8fp4iuCpHAJQSewAKMPxUyJsYfhLKbvcRfH5-AFA4BTXSApazUBIOCIaCoeCOLhcCCUMBQXCUQToUQ4YBoTA4fDEUi4CjUWj0BgHLz-LYqXZHABm2BUi2Waw2WxBKlwAAtKMgAqwZCwMmIoFjotgQKsMVicXiCYI3iEZQquAA6FkgI4nXDCUF7JkyU4G+SKaIARiC8AA9K74AAVcVoZCi-g+YDwMU-VV0fguA3wACSwfF2AA1vAAAanZPwCUprIcdNVeCiuggA0HW329ySADktDUFZCTFes31RtZHLNFo+Uht5rtCnL8Gdbo93szIf4YZ+kZL3bL0SrIBrdYbQA).
How can I modify to fix this error? If this is a bug in `flow`?

**Comment by jamesisaac** [comment]
I'm not sure I fully understand what you're aiming for, but a couple of things to bear in mind:

1. You might have more success using `ctx: { ...Context, ...C }` rather than `ctx: Context & C` in the definition for Middleware (it removes the error in your example).

2. `{}` is an [unsealed object](https://flow.org/en/docs/types/objects/#toc-unsealed-objects), whereas if you use `{||}` you'd be explicitly preventing any additional properties.

**Comment by HsuTing** [comment]
As `koa` user, they may use the custom middleware which will add some functions in `ctx`, For example:
```js
import custom from 'koa-custom';

app.use(custom);
app.use(async (ctx, next) => {
  const test = ctx.customFunction();
  await next();
}));
```
But `customFunction` is not in the basic `ctx`, this will throw error when using `koa` type in `flow-typed`. To fix this, we need to add a way which can let user add a new custom context. This should work with the basic `ctx`, too. In this case, `ctx` should be `Context & { customFunction: () => string }`.

[Here](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/koa/index.d.ts) is typescript definition.

**Comment by SamChou19815** [comment]
This now errors under `inference_mode=lti`
