### ISSUE TITLE
Switch statement does not refine input type

### ISSUE THREAD

**Issue by nickshanks** [facebook/flow#7585]
This was supposed to be reported along with #7297, but I seem to have forgotten to do so. It is a different error, and was the code I tried to use to work around the errors flow returned in that ticket.

When all branches of an argument type are covered in a switch statement (and each case returned from), any following code is unreachable (including implicit return of undefined).
In other words, a switch statement should refine the type of its argument as it passes over 'case' selectors. Once all possibilities of the input type are exhausted (and returned from in each case), any further code is unreachable.

Flow version: 0.95.2

## Expected behaviour

No Error.

## Actual behaviour

"Cannot expect T as the return type of function because enum [1] is incompatible with implicitly-returned undefined."

https://flow.org/try/#0C4TwDgpgBAggznCwDiAnA9gVzFAvFAcgENMATAS3QKgB9DyBbIgcwjmroIDdzSIqA3AChQkWAiQBRAB7AIAOziV5eQgDoAVmGYd1DMAGZdBNfoAsBYQGN0i4FAiyFS2wDF0qeIhQZsqgBTAAFzi3mhYYACUIV5STorKeAB8UADeQlBQcADu5MBWABZQgZFpGZlQVkSIhCQUVEHlFVCoSJioKib6RsLNVTUEjCxsBI3Nma3A7Z2a2pZNldXQ3Lz8owsTbR16YBa9UAC+wkdAA

Changing the final case to `default` causes the expected behaviour:
(i.e. flow knows that after a `default: return;` any following code is unreachable, and that the function cannot implicitly return undefined)

https://flow.org/try/#0C4TwDgpgBAggznCwDiAnA9gVzFAvFAcgENMATAS3QKgB9DyBbIgcwjmroIDdzSIqA3AChQkWAiQBRAB7AIAOziV5eQgDoAVmGYd1DMAGZdBNfoAsBYQGN0i4FAiyFS2wDF0qeIhQZsqgBTAAFzi3mhYYACUIV5STorKeAB8UADeQlBQcADu5MBWABZQgZFpGZlQVkSIhCQUVEHlFVCoSJioKib6RsLNVTUEjCxsBI3Nma3A7Z2a2pZNUHwAZiQANsELE20demAWvVAAvsLHQA

Because the type of the argument is refined before function entry by the argument typing & compiler, the two code examples are equivalent.

**Comment by jamesisaac** [comment]
You can throw an error to help get round this (either in the `default` statement or outside the `switch`).  Useful for catching run-time issues where the enum ends up with an unexpected value:

https://flow.org/try/#0C4TwDgpgBAggznCwDiAnA9gVzFAvFAcgENMATAS3QKgB9DyBbIgcwjmroIDdzSIqA3AChQkWAiQBRAB7AIAOziV5eQgDoAVmGYd1DMAGZdBNfoAsBYQGN0i4FAiyFS2wDF0qeIhQZsqgBTAAFzi3mhYYACUIV5STorKeAB8UADeQlBQcADu5MBWABZQgZFpGZlQVkSIhCQUVEHlFVCoSJioKib6RsLNVTUEjCxsBI3Nma3A7Z2a2pZNldXQ3Lz8owsTbR16YBa9FXwAZiQANsEbUMAFGNlQ8hC3kqgYqP6BIRD6oJGR+wC+wgBQA

**Comment by nickshanks** [comment]
But if the compiler (babel or flow-remove-types) is doing it's job properly, the function cannot be called with an unexpected value, because the compiler will fail to produce any JS output that could get executed where the type constraint could be violated.

**Comment by jamesisaac** [comment]
As far as I understand that's not the goal of either of those tools.  Flow is simply a layer of annotations for static type checking, which get stripped out at build-time.  They don't affect the run-time behaviour of your code.

Unlike a fully statically typed language, Flow is more for gradual typing on top of JS, so couldn't really make those optimisation guarantees anyway.  What would stop you from importing `extensionForAssetGroup` from another non-Flow file and calling it with `'gifs'`.. in that situation it would be annoying if Flow had stripped out your `throw`.  I suppose you could argue that if the function was never exported outside a `// @flow` file then it would be safe to optimise, but I just don't think that's really a goal of Flow.

**Comment by nickshanks** [comment]
I thought that was the goal of TypeScript: Javascript with optional type hinting; Flow is type-saftey with optional Javascript.

**Comment by nickshanks** [comment]
Oh, that's cool, I've not seen function overloading documented on flow.org, is it new?

I have neither this code nor the code in the previous ticket (#7297) in my application, since neither of them were error-free, so I am not looking to solve this in my own codebase (but the alternatives are educational), I was just closing some unsaved text documents that had been open for three months on my computer :-) and trying to report an error that ought not to occur.

**Comment by FireyFly** [comment]
I think the `declare` syntax is meant for use in libdefs, not sure how it works within the same file as the function it's declaring the type for. (I would expect it to leave the function untyped, and then just declare that the function can be used in the given ways from outside modules.) I believe it behaves as an intersection of function types, i.e. `('audio' => '.mp3') & ('images' => '.jpg') & ('video' => '.mp4')`.

**Comment by jamesisaac** [comment]
> I thought that was the goal of TypeScript: Javascript with optional type hinting; Flow is type-saftey with optional Javascript.

Hmm, where did you hear that?  I think it's the other way round if anything.  TS ships with a compiler (tsc) which supports some extensions to the run-time language (e.g. [language-level support for enums](https://www.typescriptlang.org/docs/handbook/enums.html)) and maybe does some optimisations like the ones you suggest.  Whereas Flow by contrast has always been about not modifying the run-time language, and just having type annotations that can be easily stripped away to leave syntactically valid JS.

**Comment by avikchaudhuri** [comment]
@jamesisaac is right about the workaround. This is a known exhaustiveness checking bug, we do plan to fix it. cc @gkz

**Comment by SamChou19815** [comment]
This now correctly passes type checking.
