### ISSUE TITLE
$ElementType yields any when accessesing missing indexer property

### ISSUE THREAD

**Issue by FireyFly** [facebook/flow#7590]
Trying to index an object with types like `string` or `number` seems to produce `any` when the object type lacks an indexer.  Applies to both inexact and exact objects.

This could easily inadvertently pollute other parts of the code base, and seems like a soundness concern.

Flow version: 0.95.2

## Expected behavior
No `any`--either error or `mixed` would seem like a reasonable choice to me, depending on how `$ElementType` is meant to behave.

## Actual behavior
Behaves as `any`.

## Example
```js
type Obj = {
  name: string,
  age: number,
};

// These ought to error
type T1 = $ElementType<Obj, string>;
([1, 'hello any']: T1);
type T2 = $ElementType<$Exact<Obj>, string>;
([2, 'hello any']: T2);

// ... (the Try has a few more cases, omitted here for brevity)
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBA8gRgKygXigbwFBSgOwIYC2EAXFAM7ABOAljgOYA0WUedJuArgXBJUwL4BuDBgD0oqABUAFhDLQ8AG0VQA9hzrTgUYKqi9KqyhlCQpARhRQAJAFFFEIjmCTwEADzwEDclVp0APmEACgBtcx8AclllPTwcEEiAXVJJcwBKYRM3KQAmKzsHJxc3dzsADzwAY2BPRACfChp6IIww3KiYxTiE5NTczJFTaEkAZgL7RwhnV0g6705uXlaw0c6IWJZelKlRweyzSQAWCaLpkrmK6tqvBsWeShXQo-XN+MSd4-2xCRlqMigYEMkEoihA+kohkoZB8AHdqMBpFAAAaFKYzUoAWTwYEafhayKgPH8KJwXAeyIO0GxYCsmGwoSa-h2ZKWfAwQiGOUkAFZTuiLh4aXjmoFhOIbLZypAarZIUY2qEeVEcKptKoANZ9KQ8zJAA

**Comment by goodmind** [comment]
@FireyFly this actually produces `empty`, not `any`
