### ISSUE TITLE
npm flow-bin still is 0.95.1 (0.95.2 is 4 days old)

### ISSUE THREAD

**Issue by lll000111** [facebook/flow#7591]
https://www.npmjs.com/package/flow-bin

> version
> 0.95.1

and, as of now,

> v0.95.2
> @facebook-github-bot facebook-github-bot released this 4 days ago

<br>

**It is vital** for my well-being, world peace, the end of the end of the Mueller investigation and also for our successful earth-defense against extraterrestrial invasion that the npm package is updated ASAP *(the JS code on the armed satellites is checked with Flow)*!

<br>

**Comment by goodmind** [comment]
It is already 0.96.0

**Comment by avikchaudhuri** [comment]
Should be fixed soon as part of the 0.96.0 release.

**Comment by lll000111** [comment]
@avikchaudhuri Well, still nothing, no 0.96 on npm.... and not all versions where built yet, right now Linux still is missing.

**Comment by avikchaudhuri** [comment]
Yeah we’re having some problems with the Linux build, there’s a circleci
issue.

**Comment by lll000111** [comment]
Same issue again now with 0.96.1 &mdash; two days since release, npm version still is 0.96.,0

Something broken in the process that it keeps happening?
