### ISSUE TITLE
Object Type docs is outdated

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7594]
https://flow.org/en/docs/types/objects/#toc-object-type

>However, if you need to opt-out of the type checker, and don’t want to go all the way to any, you can instead use Object. Object is unsafe and should be avoided.

This is incorrect now, because `Object` _is_ `any`

**Comment by AlokTakshak** [comment]
@jbrown215  I would like to contribute to it ,can you tell me what is to be done?

**Comment by goodmind** [comment]
@AlokTakshak https://github.com/facebook/flow/blob/master/website/en/docs/types/objects.md

**Comment by goodmind** [comment]
I think this was fixed already

**Comment by goodmind** [comment]
PR that fixed it https://github.com/facebook/flow/pull/7843

**Comment by goodmind** [comment]
@AlokTakshak maybe you can try other issues
