### ISSUE TITLE
Typing for mix-in class factories

### ISSUE THREAD

**Issue by knoan** [facebook/flow#7595]
Flow version: 0.95.1

## Expected behavior

I'm migrating to Flow an internal JavaScript framework that heavily relies on ES6 [mix-in](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Mix-ins), with class factories structured along the lines of:

```javascript
function Mixin(Base) {
  return class extend Base {

    constructor() { super() }

    mixin() { … }

  }
}
```

where `Base` is a class implementing a common structural pattern.

I'd expect to be able to type such methods as:

```javascript
interface IBase {}
interface IMixin {}

function Mixin<T:Object&IBase>(Base: Class<T>): Class<T & IMixin> {
    return (class extends Base implements IMixin { constructor() {super()} })
}

class Work { constructor() {} }

const mixedin: Work & IMixin= new (Mixin(Work))();
```

## Actual behavior

Flow complains about being unable to `return 'class { ... }' because '<<anonymous class>>' [1] is incompatible with 'T'`.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gCSAQsQM4UDeAvproSeVQLIYAe2MC3SooAVyykcGOFjC8BWADwAVAFwB5AEYArPFIBkNengB8ACloM1YAMIx6dVaYCUN+49VgDPftlNCqACQBHg4YgRy5qQOdHRgeHz4WAAm8VYUGAC2AA4weFl4uPGUCoKMYKSydDgEYlJwBOYuQnRiOYTNzGDMLqis6DGOYADqjQDWQpXVtfU4jc1C3QNVWDVgWfx4Kdg2YwSTPqV+WAC8YFh4SOZlWOb74y4uzQDcqEA

Everything works as expected if type checking is suppressed like:

```javascript
function Mixin<T:Object&IBase>(Base: Class<T>): Class<T & IMixin> {
    return (class extends Base implements IMixin { constructor() {super()} }:any)
}
```

or if I manually replace the generic argument like:

```javascript
function Mixin(Base: Class<Work>): Class<Work & IMixin> {
    return (class extends Base implements IMixin { constructor() {super()} })
}
```

**Comment by avikchaudhuri** [comment]
Seems worth thinking about how to support mixins like [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Classes#Mix-ins), but it's not a priority right now. cc @samwgoldman
