### ISSUE TITLE
Using typeof to determine type and assign value accordingly

### ISSUE THREAD

**Issue by tanohzana** [facebook/flow#7596]
Flow version: "flow-bin": "^0.92.0"

## Expected behavior

<img width="170" alt="flowError" src="https://user-images.githubusercontent.com/10516852/55147103-1269e080-5146-11e9-9623-0c368cdfc360.PNG">

## Actual behavior

<img width="417" alt="flo-error" src="https://user-images.githubusercontent.com/10516852/55147390-94f2a000-5146-11e9-905d-d022324d4b75.PNG">

**Comment by goodmind** [comment]
This is refinement invalidation, please inline `typeof` in `if`.
Also link to Try Flow would be better than screenshots
https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations

**Comment by avikchaudhuri** [comment]
As @goodmind said ^
