### ISSUE TITLE
Unnecessary error for accessing property of undefined

### ISSUE THREAD

**Issue by blax** [facebook/flow#76]
In the following example
```
/* @flow */

function length(x) {
  return x.length;
}

var a;
a = "definitely not undefined"
var total = length("Hello") + length(a);
```
I'm getting this error: `property length
Property cannot be accessed on possibly undefined value`

However this version:
```
/* @flow */

function length(x) {
  return x.length;
}

var a;
a = "definitely not undefined"
var total = length(a);
```
results in `Found 0 errors`

**Comment by samwgoldman** [comment]
We should be able to prevent this issue with `const` (#431). This behavior should be documented, but I don't see what could be done to prevent it.

Maybe we could track, along with the type of each function, a list of closed over variables, so we only need to havoc on the variables that might be modified? That is, flow would understand that `length("hello")` doesn't modify `a`.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by samwgoldman** [comment]
The snippet from the original issue now works correctly on master and we also have const refinements, so I'm going to close this one out as solved.
