### ISSUE TITLE
Getter unrecognized when encapslating class within `$ReadOnly`

### ISSUE THREAD

**Issue by pulli23** [facebook/flow#7600]
Flow version: 0.95.2

When a class has a getter (no setter) the property defined by this getter should be found even if the class is encapsulated inside `$ReadOnly<>` utility type.

## Actual behavior

When a class has a getter (no setter) the getter is no longer found when encapsulating the class within a `$ReadOnly<class>`  type. Flow gives an error of a missing property.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsAQTAG9UwwBzAUwBcwATbW7ACgEoAuMAfgDsArgFsARtQBOpchTDi6A8XzC0AFgEtcAOgD6DANzSAvtN3dBoiQYoY4fXLXECMtOOI5SZy9Vt1gAvGAArFZgxsboNnb02JwAJABK1NgMAPJ8MACeADyEAHz+YHzUSIQcBtiaTCwG6NKoQA

**Comment by goodmind** [comment]
Related: https://github.com/facebook/flow/issues/7572

**Comment by pulli23** [comment]
I went ahead and tested it a bit more - and noticed this worked pre version 0.77. Between 0.76 and 0.77 this stopped working.

**Comment by goodmind** [comment]
![image](https://user-images.githubusercontent.com/3275424/55282451-df059c80-5365-11e9-9c97-f1fbe3f99abc.png)
Because of this change probably

**Comment by goodmind** [comment]
https://github.com/facebook/flow/commit/ecbace2a34c4843bb0c2438e8759e818e1786394

**Comment by pulli23** [comment]
Is this still known? Especially since the workaround -- double declaring variables (first in an declaration list in the class and then later as getter setter is now actually being shown as error).

**Comment by darichey** [comment]
@pulli23 Your example in try flow seems to work now. Can you confirm?
