### ISSUE TITLE
Autocomplete for strings literal types

### ISSUE THREAD

**Issue by futuun** [facebook/flow#7601]
## Proposal
Add autocomplete for string literal types ie.:
```js
function example1(x: "foo" | "bar" | "baz") {}
example1("")
          ^-- that could get suggestions

type Example2 = "foo" | "bar"
const sample: Example2 = ""
                          ^-- here as well
```

## Use case
My particular use case was validating css classes from our css framework. I could easily export them into literal type with strings, it get’s validated properly but suggestions would be really nice. It would also have more common applications ie.:
- suggestions for type property on redux actions
- suggestions for react component props that are string literals

**Comment by gkz** [comment]
this should work now (you can trigger autocomplete manually with ctrl-space if required)
