### ISSUE TITLE
Improve dynamic keys infering

### ISSUE THREAD

**Issue by sudeshyadav-pws** [facebook/flow#7606]
With following code:
```js
function make(prop) {
	return {
		[prop.name]: prop.value,
	};
}

const withA = make({name: 'a', value: 5});

(withA.a : number);
(withA.b : number);
```
Flow will throw an error:
```
10: (withA.b : number);
           ^ Cannot get `withA.b` because property `b` is missing in object literal [1].
References:
2: 	return {           ^ [1]
```
Which is ok. But if we add one more call expression of function `make`:
```js
function make(prop) {
  	const result = {
      [prop.name]: prop.value,
    };
	return result;
}

const withA = make({name: 'a', value: 5});
const withB = make({name: 'b', value: 5});

(withA.a : number);
(withA.b : number);

(withB.a : number);
(withB.b : number);
```

Flow does not report any error. It should report error on `(withA.b : number);` and `(withB.a : number);`

Flow version: any

Flow Try https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYGsCmAKADgJzlwEpEBvAKEUQEgIEBnKRfTBkAG2YF5yrqBAbQJEAdGFTJMAXQBciEblEA3VBxCYANP2oBfANwUarKCHxJW7Lod0UK9ME0QB3GFAAWAQUS80WbGQSUvIA5Kghmoiq6pjyAKy6xIYOTq4eAEI+KBg4gZKxiCEARhFRahrxiYYU2GleoqiI8mAgyEWY+Ek1dZ6iRU2ILW0dXd1u7ukNA0PtnYa145P9za2zo0A

**Comment by SamChou19815** [comment]
Out of scope since we will now require the function to be annotated.
