### ISSUE TITLE
Embedded child component errors if parent is wrapped in HoC 

### ISSUE THREAD

**Issue by TomiS** [facebook/flow#7612]
Flow version: 0.96.1

## Expected behavior
No errors are shown

## Actual behavior
Trying to use embedded Child component through Parent gives an error when Parent is wrapped in HoC

Error message:
```
29:   <HocParent.Child />
                 ^ Cannot get `HocParent.Child` because property `Child` is missing in `React.AbstractComponentStatics` [1].
References:
21: const hoc = <C: {}>(component: React.AbstractComponent<C>): React.AbstractComponent<C> => {
                                                                ^ [1]
```

* Link to Try-Flow:
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduANmugMIAWwTAJnFgA8YWAHY902PDAB0bEpBGiYAHgDeAXwB8cVXThxKYrFAAUASh179BrDACuUEXBF2mTevvV0vzVnAAKyIbwgsJiElQycuAQiiIqqgA+cLhcvIYAXJiR0gByEDxYcIlalvqoMMgwwLhwnNw8WZL4svKxSgAqAJ5gWMoImh42RqYWugCQlPaOJjBcqNJgxGALqQ2GZkPq+t50gcGyaXwAvHVH9HQA9JdwAOoA8hgA0gDKdMr7SppWH0FKhw04JdvspLp94t9GLEKnAOBBaqdlGwshpNCZcG04jAmjkAIIAIwqUCk0QUSiRmjMOKk0gJRJJmPJbG0x20un0UwcTgxMSxNB22ys1jgUJEMIAEvDwfBTnDcCZpZsGNc4ABRDAYR4vACEuvektw0u++mUBulAN4QJBlzNfwhQuFIqAA

Same as plain code
```js
import * as React from 'react';

class Child extends React.Component<{}> {
  render() {
    return null;
  }
}

class Parent extends React.Component<{| children: React.Node |}> {
  static Child: React.ComponentType<*>;
  render() {
	return(this.props.children);
  }  
}

Parent.Child = Child;

// WORKS
<Parent>
  <Parent.Child />
</Parent>

const hoc = <C: {}>(component: React.AbstractComponent<C>): React.AbstractComponent<C> => {
  return component;  
} 
      
const HocParent = hoc(Parent);

// ERRORS!!!
<HocParent>
  <HocParent.Child />
</HocParent>    
```

**Comment by FireyFly** [comment]
Makes sense to me: a `React.AbstractComponent<C>` indeed doesn't really know anything about the static fields available directly on the component itself.

Typing it as
```js
const hoc = <C: {}, S: {}>(component: React.AbstractComponent<C> & S): React.AbstractComponent<C> & S => {
  return component;  
}
```
appears to work (i.e., take an `AbstractComponent` of some config `C`, intersected with some object of static fields `S`, and similarly return a `React.AbstractComponent<C> & S`). You'd probably have to adjust the type as appropriate for a more involved HOC than just a no-op one.

**Comment by TomiS** [comment]
@FireyFly Thanks for your suggestion. It indeed removes the error and works in that sense.

I'm a still hesitant though. This would mean that to make HoCs actually compatible with any valid React component (as many of them supposed to be, I think), one would need to add that extra intersection definition to all HoC typings everywhere. I doubt adding it has been very popular in e.g. flow-typed library typings, which practically makes all of those libs incompatible with any component that has components as static fields.

Thinking further, it could be said that the React ecosystem is moving towards favoring function components over class components so wondering if this whole approach should just be flagged as anti-pattern in some documentation somewhere.

**Comment by FireyFly** [comment]
I think indeed HOCs tend not to copy over static properties (i.e. often `hoc(YourComponent)` wouldn't have the statics of `YourComponent`--hence why [the React docs][1] suggest either exporting them as separate named exports, or using something like [hoist-non-react-statics][2].

Indeed it looks like the recent development with hooks might replace many uses of HOCs, so we might see a bit of a paradigm shift. Guess time will tell :)

[1]: https://reactjs.org/docs/higher-order-components.html#static-methods-must-be-copied-over
[2]: https://github.com/mridgway/hoist-non-react-statics

**Comment by TomiS** [comment]
Ah, didn't know that React docs already discourage using statics for this. Thanks, I learned something new at least. So maybe this isn't worth further discussion, closing.
