### ISSUE TITLE
Incorrectly shown error when using exact objec type with all optional attributes

### ISSUE THREAD

**Issue by pulli23** [facebook/flow#7624]
Flow version: 0.96.2

## Expected behavior

When one creates an exact object type, which contains just optional attributes. And later initializes an object using this type, where no attributes are initialized. I expect this to work, as an "empty" object is obviously a subtype of an object with just optional attributes.

`
type T = {|
  value?: ?string,
|}

const t:T = {};`

## Actual behavior

Flow returns an error on initializing the object: Cannot assign object literal to `t` because inexact object literal [1] is incompatible with exact `T` [2]

* Link to Try-Flow or Github repo: https://flow.org/try/#0FDAuE8AcFMAIBVYF5YG8A+xawG4EMAbAV2gH4AuWUgZ1ACcBLAOwHMAaYdAXxAGMB7JrVihyiFKi4BuIA

**Comment by borlaym** [comment]
Just want to bring some attention to this issue by commenting. The fixes to object spreading unveiled this bug in our codebase.

**Comment by gkz** [comment]
Fixed: https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c
