### ISSUE TITLE
$ObjMap is not respecting generic function types

### ISSUE THREAD

**Issue by cain-wang** [facebook/flow#7631]
Hi, I'm trying to use $ObjMap to map an object with values into an object with functions returning the same typed values.

Somehow Flow is not recognizing the generic type in the function.

```js
type MapToFunc = <T>(T) => T => T;

declare function run<O>(o: O): $ObjMap<O, MapToFunc>;
      
const defs = {
  str: '',
  num: 12
};

run(defs).str(12); // !! expect error as 12 is not compatible with string but Flow yields no errors
```

[try flow](https://flow.org/try/#0C4TwDgpgBAsghmAKgewGIFcB2BjKBeKAHkQD4AKRASnxKkRroG4AoZgEwmwBs4AnaAGZZswAJbJMUXlkIB5csgBcUWZWUASWQCMAVvDByANLAQoMOEiyjWbzbBIDOwKBwEP8UAN7NrT3soByAMMfKEx0AFtlAEYAJmYAXxZmaUwyVwdKADo-MjjKRigAeiKoCAAPSBEy3l5kXig4dzioUXdMZGd7CLA4MS0uaAB3UWAACyg-UUwAcyA)

**Comment by goodmind** [comment]
$ObjMap just doesn't work with input positions

**Comment by cain-wang** [comment]
> $ObjMap just doesn't work with input positions

Ah, that is confusing. Thanks for the pointer. Do you know where can I find documentation or hints what positions are supported in $ObjMap or other generics usage?

**Comment by goodmind** [comment]
There isn't anything about it in docs

**Comment by cain-wang** [comment]
Thanks for the answers above!

I wonder if this is something Flow team will add support to?

**Comment by goodmind** [comment]
@jbrown215 can this be implemented or this is limitation in how `$ObjMap` inherently works?

**Comment by jbrown215** [comment]
I'm pretty unfamiliar with the implementation of `$ObjMap`. In general, I know our destructors need a lot of work.

**Comment by Diggsey** [comment]
This should still be marked as a bug, at least until the documentation is updated to clarify when this type can be used.

**Comment by jedwards1211** [comment]
@goodmind is the concept of input and output positions documented anywhere?  I wish I could understand it a bit better, but seems counterintuitive (esp. considering I would naively think of a return type as "output")

**Comment by jedwards1211** [comment]
Actually it seems like the input position you're referring to is something to do with mapping to a function specifically, since if I map the properties to values it works fine...

**Comment by cain-wang** [comment]
Oops

**Comment by SamChou19815** [comment]
Closing since mapped type fixes this: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyMTXpyQ5LEZNCDx0zKJWuJtBQW49AOkMm+AhEWGhCKmZ6lgC+6hAi1AEYAAQAsrYAKhAAYiRgyQC8yQA8GQB8ABQZAJSFZckZdQ0A3AA6UO0iYHSYyTB5OlDJxFDFAPKVEMjJY9XTwADaANLJcEMA1hj8EDAzALrTFWPLe7UF9cdLe9FtQ8n39+0a9LjJIjD0hcnA7fcvaNMAOSA1i-ZKKcjTACMACZ2jd2u0RhV3vRqr5-hVYdVmskAPR45LuDB4IloNAQNDJBjJWGrT5QCCvSDkIxYMi8GgpADu2gAFsl-mskOwAG4YNBMaDUUUABl8MKhUN8UJA0SAA

$ObjMap will be dead in the future
