### ISSUE TITLE
LSP request fails with "cannot instantiate non-class type PolyT" when optional type argument is omitted

### ISSUE THREAD

**Issue by noppa** [facebook/flow#7632]
Flow version: 0.96.0

## Expected behavior
LSP command "textDocument/definition" works correctly.

## Actual behavior
When extending a generic class that has optional type parameters, omitting those optional parameters will make LSP requests inside the subclass fail.

```javascript
// @flow
class A<Props, State = any> {

}

class B extends A<any> {
  foo() {
    return 3
  }

  bar() {
    return this.foo()
  }
}
```
Requesting LSP command textDocument/definition for `this.foo` inside `B.bar` outputs error
```text
[Error - ] Request textDocument/definition failed.
  Message: (Failure
   "(Failure \"cannot instantiate non-class type PolyT\")\
  \nRaised at file \"pervasives.ml\", line 32, characters 17-33\
  \nCalled from file \"src/typing/members.ml\", line 372, characters 19-42\
  \nCalled from file \"src/common/utils/utils_js.ml\", line 81, characters 21-26\
  \nCalled from file \"src/typing/members.ml\", line 548, characters 8-48\
  \nCalled from file \"src/typing/members.ml\", line 484, characters 25-81\
  \nCalled from file \"src/server/command_handler/getDef_js.ml\", line 76, characters 22-47\
  \nCalled from file \"src/server/command_handler/getDef_js.ml\", line 113, characters 13-47\
  \nCalled from file \"src/server/command_handler/getDef_js.ml\", line 182, characters 8-37\
  \nCalled from file \"src/server/command_handler/getDef_js.ml\", line 211, characters 42-91\
  \nCalled from file \"src/core/lwt.ml\", line 2101, characters 16-20\
  \n")
  Code: -32001
``` 

If I specify the second type argument (`extends A<any, any>`), the error goes away and "go to definition" works as expected. Since `React$Component` is defined as 
`class React$Component<Props, State = void>`, I can't use LSP features in most of my React components, which is how I originally came across this issue.

I'm not 100% sure if this is an issue with Flow or the [flow-for-vscode](https://github.com/flowtype/flow-for-vscode) VSCode plugin that I'm using for LSP, but the error seems to originate from deep inside Flow's internals so I figured I should start with here. `flow check` runs without errors.

* Link to Try-Flow or Github repo:
https://github.com/noppa/flow-poly-t-lsp-issue

**Comment by pierpo** [comment]
Same issue here, and I'm using the LSP with Vim (through `coc.nvim` plugin).

So I don't think it comes from [flow-for-vscode](https://github.com/flowtype/flow-for-vscode).

**Comment by miguel-guedes** [comment]
Just to add to the OP, it seems that it is the server started by the `flow lsp` command that is failing. Like the OP, I do not get any errors when I run `flow check` but starting `flow lsp` manually and requesting a definition for a class attribute or method results in the error described above.

**Comment by noppa** [comment]
To mitigate the problem, I've started to put explicit `any`s to `extends Component<Props, any>` etc. It's a but cumbersome but better than not having lsp support.

**Comment by noppa** [comment]
It seems that this has been fixed at some point. I can't reproduce it in the [sscce branch](https://github.com/noppa/flow-poly-t-lsp-issue/blob/flow-latest) with Flow version 0.111.3.
