### ISSUE TITLE
flow-dev-tools throwing errors

### ISSUE THREAD

**Issue by meandmax** [facebook/flow#7633]
Flow version: 0.89

## Expected behavior

Auto-generated flow suppress comments in code-base

## Actual behaviorz

Two kinds of errors, I also got it working once but really do not know how:
Got the instructions from: https://medium.com/flow-type/upgrading-flow-codebases-40ef8dd3ccd8

using this command: `../flow/tool add-comments --all --bin ./node_modules/.bin/flow --comment "\$FlowSuppress fix it" ./`

Getting different errors: 

<img width="603" alt="Screen Shot 2019-04-10 at 9 33 11 pm" src="https://user-images.githubusercontent.com/6309638/55877018-4a5c3380-5bdc-11e9-83eb-6df09935c075.png">

or 

<img width="920" alt="Screen Shot 2019-04-10 at 9 42 21 pm" src="https://user-images.githubusercontent.com/6309638/55877065-64961180-5bdc-11e9-8e69-48e95133acae.png">

**Comment by jbrown215** [comment]
try passing --check check as a flag, too. 

I think ./tool expects a server to be running

**Comment by jbrown215** [comment]
I updated this in the blog post too. Thanks for letting me know!
