### ISSUE TITLE
Objects have different exact types

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7641]
This is regression from Flow 0.88

Flow version:

0.96.1

## Expected behavior

```js
const ww = { a: 1 }
const d: typeof ww = { } // error
const dd: {|a: number|} = {} // error
```

## Actual behavior

```js
const ww = { a: 1 }
const d: typeof ww = { } // no error
const dd: {|a: number|} = {} // error
```

* Link to Try-Flow or Github repo:
[Try Flow](https://flow.org/try/#0MYewdgzgLgBA7nGBeGBvGBDAXDAjDAXwChRJYATHKATwAcBTEAM3kRXQJgHouYwQY9AE5CQQkuGgxylNAB9sfAK4BbAEbC5ndpx6CRYoA)

**Comment by dsainati1** [comment]
This is a known issue that has been raised in other threads before. #7345, for example
