### ISSUE TITLE
Refinements frequently used?

### ISSUE THREAD

**Issue by dlthomas** [facebook/flow#7645]
https://flow.org/en/docs/lang/refinements/ starts out "Refinements are a frequently used aspect of any type system."  My understanding is that many (most?) type systems don't have refinements, in the sense used here.  Reporting so that it can be fixed or I can learn something.

**Comment by drwlrsn** [comment]
I am pretty new to this whole thing, but consider a variant in Ocaml:

```ocaml
type basic_color =
| Black | Red | Green | Yellow | Blue | Magenta | Cyan | White
```
We would use pattern matching on some value with the type of `basic_color`. Seems quite similar.

**Comment by dlthomas** [comment]
I'm not sure where the theory falls but I can certainly see the similarity.

But the question isn't whether there are other type systems with refinements, but rather whether there are type systems without.  I contend that there are major, well known type systems without anything equivalent (probably most clearly C).

Replace "any type system" with "some type systems" and it's a claim I might've made.  Replace it with "most type systems" and I'd be a little surprised but not bother correcting.  But "any type system" seems far enough off that I stumbled, going through the docs.

**Comment by goodmind** [comment]
Maybe any strong type system? C is weakly typed

**Comment by dlthomas** [comment]
I think strong/weak is mostly orthogonal.  A restricted C that had strong typing would still not have refinements.

**Comment by lll000111** [comment]
There needs to be a new tag "bikeshedding" so that it can be used for this discussion.

**Comment by goodmind** [comment]
@ll000111 this isn't just chatting, it is about misleading documentation

**Comment by lll000111** [comment]
@goodmind Sure - the same great importance as [the discussion about how many angels can dance on the head of a pin"](https://en.wikipedia.org/wiki/How_many_angels_can_dance_on_the_head_of_a_pin%3F). Very valuable!

**Comment by mrkev** [comment]
@dlthomas— feel free to PR "any" to "many" and tag me for the merge. There are certainly typesystems without refinements (: Thanks for the catch.
