### ISSUE TITLE
Flow doesn't recognize that destructured properties in function parameters are read-only with regards to the object

### ISSUE THREAD

**Issue by Mr-Wallet** [facebook/flow#7648]
Flow version: v0.97.0

When an object is destructured in the parameters of a function, I would prefer if flow Flow didn't produce errors that result from the possibility of re-assigning properties on the object.  Having to mark Maybe properties as covariant can be somewhat tedious, and solving the error can be quite counter-intuitive for those unfamiliar with it since the function can't easily produce the error being guarded against.

[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AWTQCoAWAlgHYDmoAvKAN6gqmUBcoAzigE7lUC+AbmQBjWGU6gAtmgBiAVzLCaoABQMmvUHzbrmFAPxtOPSloCUNAHz1EoUFywo5XMoy5ysQviLETp8xQAlLABDABMAeTJoNAAFLlgMZTVGPS0dUABqDUpDDm5NPgtqazpbe0dnV24PLx9xFClCPTZ8Yk1aXV42AHINdlASAZDU3h6tIX8FYRVpdsozSdlp4PComPjE2ebeRaA)

I recognize that a reference to the object is technically reachable through the `arguments` object, but accessing `arguments` is now generally agreed as bad practice in most applications. Accomodating such use cases could involve annotation escape hatches, more strict application of type-checking when the `arguments` token is present in a function, or a flow config setting.

**Comment by cprodescu** [comment]
While I see how this can be inconvenient in your case :(, this is not a bug, but an explicit design decision in Flow.

`myFunc` (which takes the argument without the read-only / covariance annotation) could delete the key `thing` from the object, which is exactly what Flow's sound type system defends against.

**Comment by Mr-Wallet** [comment]
Can you explain how it could delete the key without accessing `arguments`?

**Comment by SamChou19815** [comment]
Close since the behavior is expected. We only use the declared signature to decide the type of the function.

**Comment by Mr-Wallet** [comment]
My issue is that if it were actually using my declared signature as given in the Try Flow link, it shouldn't behave this way.
