### ISSUE TITLE
Object width subtyping broken on object map values

### ISSUE THREAD

**Issue by rtsao** [facebook/flow#7649]
Width subtyping seems partially broken with object maps. 

Flow version: 0.97

## Try Flow

Works as expected (object): https://flow.org/try/#0PTAEAEDMBsHsHcBQiCGBnAngOwMakgK64AuAlrFqALYCmxAFrACYAUsARgFYBcoA3pFixeaYgCdSWAOYBfAJT8ZyYhgAONUAHkuoALz9Bw0KInSANKHYoxvLASrsaYmQG5kOCqNAA3FNFC82px6BkK8AET0NNBw4RZWNqAAjABMAMyuyLQMzCy+0HJuQA

Does not work as expected (object as object map value):
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCGBnAngOwMakgK64AuAlrFqALYCmxAFrACYAUVKADgFygDeA2mmIAnUlgDmAXR69IsWDyGiJAXxUBKPiuTEMHGqADyAIwBWAWU6gAvH0EixUmXIWgljgDShjKYTywEVMY0wmoA3Mi0DMwsvADWNBjO8jwARPQ00HCpXj5+oACMAEwAzGrqYaAgoADqsMJxaKDooDQAHvo4xDRMyDgUQqAAbijQoDwmFla28YnJrumZ2bm+PMVlKhGIUYysI9AVVWAAyowE0Eyg8PVxyEA

**Comment by dsainati1** [comment]
This is an issue with invariance, not with width subtyping. Correct me if I am wrong but I believe this was also answered in our community discord?
