### ISSUE TITLE
missing bin/examples when installing HEAD via homebrew

### ISSUE THREAD

**Issue by Niggler** [facebook/flow#765]
```
$ brew install flow --HEAD
==> Cloning https://github.com/facebook/flow.git
Updating /Library/Caches/Homebrew/flow--git
==> Checking out branch master
==> make
Error: No such file or directory - bin/examples
```

**Comment by gabelevi** [comment]
Oh boy, it looks like I messed up when deploying 0.14.0. I should have updated the homebrew formula to NOT reference bin/examples, since we no longer create that directory as of https://github.com/facebook/flow/commit/b904adf1aaefa5b58990819bc03b01e7b618cb32 

Sorry for the trouble!
