### ISSUE TITLE
HTMLElement.focus missing options object

### ISSUE THREAD

**Issue by gaastonsr** [facebook/flow#7651]
## Missing/Incorrect APIs

The focus method of HTMLElement is [missing](https://github.com/facebook/flow/blob/e0b7df928800d54df4f66c450ac436e5a1419b3f/lib/dom.js#L1621) the [options](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus) object. 

## Relevant documentation

[Typedef](https://github.com/facebook/flow/blob/e0b7df928800d54df4f66c450ac436e5a1419b3f/lib/dom.js#L1621).
[Focus docs](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement/focus).

**Comment by cindyyu** [comment]
Hi,

I am attempting to address this issue in PR #7711 as my first contribution. :smile:

Thanks,
Cindy

**Comment by cindyyu** [comment]
This should be addressed by #7711.
