### ISSUE TITLE
Object.keys always returns array of string for typed objects as maps

### ISSUE THREAD

**Issue by danrot** [facebook/flow#7652]
Flow version: 0.97, 0.86 (and probably a lot more)

## Expected behavior

If I have a type `{[number]: Object}` and pass a variable of this type to `Object.keys` I would expect a `Array<number>` in return.

## Actual behavior

The returned type is `Array<string>`.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1FgptgFygDeA2mgK4C2ARngE4C6xA8rQFZ7JYC+oAXlK8A3IkQAKdlx4A6ANZ4Anhgn5sASmIBBBgwCGSgDxU6jAHwaRQA

**Comment by pbondoer** [comment]
I disagree, [MDN clearly states](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_objects/Object/keys#Description) `Object.keys` returns an array of strings.

You can try this yourself in node:

```node
> Object.keys([1, 2, 3, 4])
[ '0', '1', '2', '3' ]
> Object.keys({ 1: 'test' })
[ '1' ]
```

**Comment by dsainati1** [comment]
Yep. This is the correct behavior unfortunately. Javascript can be a little weird.

**Comment by goodmind** [comment]
I think number keys shouldn't exist actually since all keys are converted to strings, even on arrays?

**Comment by danrot** [comment]
OK, that's really weird. But I have the same opinion as @goodmind then... Unless there anyway I can get the keys in the type I've used when adding them?

**Comment by pbondoer** [comment]
@danrot

Have you tried the [`$Keys` utility type](https://flow.org/en/docs/types/utilities/#toc-keys)?

This should give you what you are looking for, though you might need to cast the return of `Object.keys` to `any[]` for it to work.

**Comment by danrot** [comment]
I have now casted the entries to `number` afterwards, works in my case quite well.
