### ISSUE TITLE
Flow 0.97 LSP causes most code to be marked as uncovered, even if the server reports (correctly) that it's 100% covered

### ISSUE THREAD

**Issue by lxe** [facebook/flow#7654]
**Update**:

Issue was introduced in 313d6c7

---

Tracking in flow-for-vscode as well: https://github.com/flowtype/flow-for-vscode/issues/332

Some LSP-related change between 0.96 and 0.97 causes VSCode listening to `flow-bin/flow-osx-v0.97.0/flow lsp --from vscode` to mark most code as uncovered:

With `flowtype.flow-for-vscode-1.1.1` :

![image](https://user-images.githubusercontent.com/1486609/56442631-5b750680-62a6-11e9-958f-118a193461c4.png)

Observe that the task bar shows `coverage 100%`, but every line is marked as uncovered.

Flow `0.96` does not cause flow-for-vscode to exhibit this behavior:

<img width="817" alt="Screen Shot 2019-04-19 at 1 25 11 PM" src="https://user-images.githubusercontent.com/1486609/56442712-9f680b80-62a6-11e9-9a96-8b16dcb7ca70.png">

**Comment by lxe** [comment]
https://github.com/facebook/flow/compare/v0.96.0...v0.97.0 bet it's something to do with trusted types

**Comment by lxe** [comment]
Looks like 3801a0283 - `v0.96.0 (3 weeks ago) <avik@fb.com>` is not the same as flow-bin@0.96.0, as this problem also happens there.

**Comment by lxe** [comment]
This issue appeared in this commit: 313d6c739 

cc @dsainati1

**Comment by dsainati1** [comment]
Hmmmm. Is this limited to VSCode?

**Comment by lxe** [comment]
I tried with 

```
[options]
trust_mode=none
```

```
trust_mode=check
```

```
trust_mode=silent
```

With no difference

**Comment by lxe** [comment]
> Hmmmm. Is this limited to VSCode?

@dsainati1 I haven't tried any other editor or plugin. I guess maybe the flow lsp extension needs to update to take https://github.com/facebook/flow/commit/313d6c739b8ec00a0d18e01d9d26e273c4097865#diff-84d0c6a799d463d1e58a368fdfb53bf5L1009 into the account

**Comment by dsainati1** [comment]
I can reproduce with my editor. I think this has to do with the fact that I left trust-coverage mode off for the LSP's persistent coverage command, but I suppose that didn't have the effect I thought it did. Unsure why our tests didn't catch this, but I can fix it for the 0.98 release of Flow.

**Comment by lxe** [comment]
Thanks @dsainati1 

I'm trying to debug the flow-to-vscode side of things. Getting coveredPercent with a bunch of uncoveredRanges

```
{
  "coveredPercent": 100,
  "uncoveredRanges": [
    {
      "range": {
        "start": {
          "line": 8,
          "character": 7
        },
        "end": {
          "line": 8,
          "character": 15
        }
      }
    },
    ...
  ],
  "defaultMessage": "Un-type checked code. Consider adding type annotations."
}
```

**Comment by dsainati1** [comment]
Problem is this line: https://github.com/facebook/flow/commit/313d6c739b8ec00a0d18e01d9d26e273c4097865#diff-84d0c6a799d463d1e58a368fdfb53bf5R1024

No idea how our tests didn't catch this. Thanks for the bug report!

**Comment by dsainati1** [comment]
Cool I have a fix for this. Should land by Monday and make it into the next release.

**Comment by vicapow** [comment]
Thanks for the quick fix!

**Comment by lxe** [comment]
Nice! Thank you!
