### ISSUE TITLE
Optional properties prevent casting generic objects

### ISSUE THREAD

**Issue by pbondoer** [facebook/flow#7664]
Flow version: **0.97.0**

> Possibly related to #5334

When you have an unsealed object map-like type defined as in the example, it is impossible to cast it to any other object type even though the additional, non-map-like properties are marked as optional. Not sure if bug or by design?

The only workaround I found was either removing the `key?: string` property from `KeyedObject`, or adding a `key?: string` property to `MyObject`. In practice, we can never populate the `key` property (as it is optional), but this "pollutes" my types with an extra, unwanted property.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAaQ1IwBMB5AIwCsMBjYgXjAG9UYMAGtaAfgBcYAM6F8ASwB2AcwA0gsAG1ZClQF0pAQ0Wl1AXwDc6bHiIlylALKkW7LmF4ChiwwFsMUjpKahry9FKKAK6+zBj45laoMBjEhvj4Us6unISaeh5aGl5CYD7+UgDkhBiyFeolYGFSAIz1YGZtxd5+AWBVNYQATHUaQk1gg20dqHqJycSidOHUtAzZXHkFABRpGStL67l6AJQWQA

## Expected behavior

Flow should not throw an error.

## Actual behavior

```
    24: let keyed: KeyedObject[] = (arr: KeyedObject[]);
                                    ^ Cannot cast `arr` to array type because property `key` is missing in `MyObject` [1] but exists in `KeyedObject` [2] in array element.
        References:
        13: let arr: MyObject[] = [
                     ^ [1]
        24: let keyed: KeyedObject[] = (arr: KeyedObject[]);
                                             ^ [2]
```

---

If this is indeed a bug, I would be happy to help with this, but I would appreciate some pointers on where to look if possible :)

**Comment by vikr01** [comment]
Any updates on this? Running into [a similar bug](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN4A+qAkFCQPwBcYAdgK4C2ARngCcANKjBg6vAIYC2XPoJHUAvgG502fGABC08lVoTpsnv2Gpla9AGM47AM4YwADzY6BeylJlgADKtQ29o5YbMSkFE4qQA).

**Comment by SamChou19815** [comment]
This only works if everything is readonly
