### ISSUE TITLE
$TupleMap<Array<T: Union>, ...> has unexpected handling

### ISSUE THREAD

**Issue by MMeent** [facebook/flow#7665]
Flow version: 0.97.0

## Expected behavior

I expected that the in the TupleMap, the seperate union members were mapped, and then a new union was created.

## Actual behavior

Only one mapping was made, with the full union, resulting in type errors due to bug #4211.

Potential solution: Supply a $UnionMap function, mapping each union member seperately.

* [Link to Try-Flow](
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDSumAagIYwCuuAKjrgApkCWATgGJysA8BANGADyALjABvANoEAuqJABfAHxgAvGAAUBAJSrlUgQBIAojFwBbXADt0dPN0ECCi6QG5UqAMZxLAZ3Rh0XD9BACMAK0FLRlY4bFVxMCg4OFEAIhCyVlSweTcvX39A4PCAWUoYdGYGGLi1MUTktIysgQyAL1EARlzUMD7+gcGh4ZHRkYx6MCNrVmYg3gERcSlZMDJLTCV4gxpKbFMSsmxuAEFWVjJMXkVHYnIqWnomNk4efiFFRTdPbz8wAGsAG7PVg+SK4IiYUTTdCzeYGSE+bhYPBwKABILoUIRKLVWI3AL0NEY4o46L4+ISCSpJJwVJ8dKZVLSVw-AoA4EsUGHDaI6EzOZIhHEJEo3DEopY0rlSp47AEsUSzHYsoVKo1ZRqKk05L0sCMrLSATU9p6zos75AA)

**Comment by goodmind** [comment]
It is expected actually

**Comment by MMeent** [comment]
fair enough? Though I tried the following, and that failed too:


[example on flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDSeWAagIYwCueAKrngArkCWATgDwDyANEQHxgAvGADahPgBIAojDwBbPADsM9fNz6F+AXVQATPAGMY5NgWPkAzpbBcARgCsjGMAG9UYAAVfLGchhZDMAA3ShpLDlp+AApaAEoALjAAQTY2ciwOSQpqPAio-gBuD29PX39AsGUMNhY8yJj4pNT0zOyw+sl7BwBZchwWSL4OCTBSJJk5RRU1PCGBGNHSOOFBcT5SbX5t4tQAX3RDOCVfMAwk1zAoODgk31qlAHM+O1MkpSp5Ozw2MD3hNxXG5JABEAAsSCCXm8wABGP7FMBI5Eo1Fo9EYzFY7Gojw4-EEwkEvFE0lE1ByFwYPIYWHNNIZDjRe4sJ4AHw+Xx+cUEIm6zgAdNVanlohg4gL5P1ouRVmByKJYdo4hS8FSaQAmemtJkAcmucF1bN1rzYup5AP5hgwQpUIssYolUpwMrlCoADMrVerfABmbWM0T6m66vgsp7aMBssQm0yhsCc75sLaWxyC4V1B3i71nGkAFgDmSDpvjiZ+kejQYN8fDjxTfLT1ttNUzjpz1N8AFZCyMSDkaLNmOwONh8HAoGc+MHDYJo8QyB1B6xOKO8OPJ7GzdtU04mxnRdmgA)

**Comment by goodmind** [comment]
Flow team currently against adding new $ types, so I don't know if this is would be possible, but maybe it is easier to create $UnionToTuple

**Comment by MMeent** [comment]
After more research, the both example's issues seem to be missing disjoint union type detection for tuples, which I hadn't seen the issues for. Therefore, the issue I'm having specifically is #4296. 

Regarding UnionToTuple, that would probably be difficult to implement as it will imply an order in the union, which does not exist (as `object | number === number | object`). A better alternative would probably have a Set as the target type or something like that, but that will probably not be nescessary once #5048 is merged

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
