### ISSUE TITLE
Implicit instantiation with `_`

### ISSUE THREAD

**Issue by retyui** [facebook/flow#7671]
Flow version: 0.97.0

## Expected behavior
Flow retrieved the type irrespective of export

## Actual behavior
Аf you don't  export the result of the generic function, the type is retrieved without problems.
In the example, if we export the result of the generic function, we get an error with the following text:
```
Please use a concrete type annotation instead of `_` in this position.
```

[Try ...](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmgb7bloCCF1JAPACoA0oACgD4AFIlChyATwAOaAFyguiAJQKA3mNDC8AcwCMC-qtBqAPhJnzFfadklxsKQ6FMBfHpoDU5WAGVyuJQkOgrCyqAAvIKKiK4A3MgYNADO5KAAqvwAIsxcAKIA+gBieXlZCgBEmTn5xaVZFZGgVdm5hSVlFQnIaAAe0rC4aUkkqaBEKLZMRWhoKE30aIwsbDQcBXwkRAC2AEZouCLVbXVlygkg4lfXN7d39+IAegLQS8kERO+g2HQ0i0wWWTfEgkWDkRjsUBBVJLeawSCgAAGBURUNo5AAFpRkqABslKFQaAA6RCXADqGMYuNwsF2r22OIA-IkUmkiNIUMsZnM9AsGExWITOBtQFs9gcjq1ah0sudkMJ2ZzprMUHphHplESpLJKsdpfUKudQJd8AFKGgAG5zCQYgjagiaeWKrkqtUarWWXVS9r1ABMhrixuAfVkFGtBxpuD4TDG2BIkmQyCAA)
```js
// @flow

declare function createAction<T, P>(
  type: T
): {
  (arg1: P): {| type: T, payload: P |},
  +toString: () => T
};

const UPDATE_FEED: "UPDATE_FEED" = "UPDATE_FEED";

// What problems? I only added 'export'
export const udpateFeed = createAction<_, number>(UPDATE_FEED);
//                                     ^ Please use a concrete type annotation instead of `_` in this position.

const updateFeed1 = createAction<_, number>(UPDATE_FEED);

(updateFeed1(1).type: "UPDATE_FEED"); // work fine, retrieved the type 




// Expected error, test any
(updateFeed1(1).type: "UPDATE_FEED2"); 
```

**Comment by goodmind** [comment]
This is intended

**Comment by jbrown215** [comment]
See https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8 for more info
