### ISSUE TITLE
Explicit type specification for component rendering <MyComponent<T> />

### ISSUE THREAD

**Issue by retyui** [facebook/flow#7672]
## Proposal
Now there is no possibility to explicitly specify the generic type for the component.

This syntax can solve the problem:
```js
<MyComponent<T> />;
```

I can be rea

## Use case
```js
// @flow
import React from 'react';

class MyComponent<T> extends React.Component<{| +item: T |}>{  }

<MyComponent<number> item={1} />; // work good
<MyComponent<string> item={1} />; // error
```

**Comment by jamesisaac** [comment]
Yeah agreed this could be useful, I've run into it before (although for my use-case I've now just started using Hooks, which are easier to type).  In the end I worked around it like this:

```js
class ConcreteComponent extends MyComponent<number> {}

<ConcreteComponent item={1} />
```

...although that solution only works for class components, not functional components.

Supported in TypeScript since 2.9: https://github.com/Microsoft/TypeScript/pull/22415

**Comment by goodmind** [comment]
I have implemented parsing side, would submit PR soon

**Comment by jbrown215** [comment]
This is something that's been on my list for a while, but I was never sure I would get to it. Thanks for looking into this, @goodmind! I will review as soon as I can.

**Comment by villesau** [comment]
@goodmind will your PR also add support for something like:

```
type LinkProps<T> = {a: T};
declare var AAA<T>: React$StatelessFunctionalComponent<{children: (props: LinkProps<T>) => void}>;
```

[try flow](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoGATzCTgBlgA7AawAUcwBnAHgBUAfHAC8cAN4oAXHD4BfCgBMkaADYoicAG7q4AQX38B05OhgASAMowUMJCqRcuAMQCuTDMAhMUKgMK5IJiQmGB4xNAALYBUFIiZpAAowTi5pRlYOCG5DAEoRIU0IYAVZAQpyHn1dAS4YKGYAcx4AeiqyoA)

see: https://github.com/flow-typed/flow-typed/pull/3281/files#diff-f6fab52153e41297b233b7e3a1975af6R86

**Comment by goodmind** [comment]
@villesau, no, why?

**Comment by villesau** [comment]
Would be useful with type definitions.

**Comment by goodmind** [comment]
Why not generic function?

**Comment by villesau** [comment]
How would you express this:

```
type LinkProps<T> = {a: T};
declare var AAA<T>: React$StatelessFunctionalComponent<{children: (props: LinkProps<T>) => void}>;
```

**Comment by goodmind** [comment]
`declare function AAA<T>(props: {children: (props: LinkProps<T>) => void}): React$Node`

**Comment by clayne11** [comment]
Any movement on this? This is an awesome feature in Typescript.

**Comment by asazernik** [comment]
The PR just got merged, so I guess we'll see!
