### ISSUE TITLE
Flow doesn't recognize implementing class inside a callback parameter that takes a callback

### ISSUE THREAD

**Issue by mechanicious** [facebook/flow#7678]
Flow version: 0.98.0

## Expected behavior
Of the two:
[errors:](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgJIGUIBsILHAIx2QG8AoAexExzwFVxgsAKBOLLAxAawC5lmAEzj5k-DNlz4iEAJTIAvAD5kANwrBBAGmQBXRljEC2HACoUAShAC2FVRADC7TjyMAxfXmBUdJlwj4BYVFxGilCHHllNQ1BKJV1TVl+RMEAbjIAXzIyBCw4AGcC5AAhQog3JghTKuRgawAHHGsIcGKJWmlicmRkKjD6A1ZnLgD+IRE4IzKCiqqayMUE2J19MCYjYbNLGztHEdd+DxAvH2Q-UcCJkNLyypwFuSWYpOfU+RTY0mzMoA)
```js
interface ISelectable {
onSelectUntil(callback: (data : ISelectable) => void, until : (callToRemoveCallback : Function, callback: (data : ISelectable) => void) => void): void;
}

class BaseFileTile implements ISelectable {
  onSelectUntil(callback: (data : BaseFileTile) => void, until : (callToRemoveCallback : Function, callback: (data : BaseFileTile) => void) => void) : void {}
}
```
[passes:](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgJIGUIBsILHAIx2QG8AoAexExzwFVxgsAKBOLLAxAawC5lmAEzj5k-DNlz4iEAJTIAvAD5kANwrBBAGmQBXRljEC2HACoUAShAC2FVRADC7TjyMAxfXmBUdJlwj4BYVFxGilCHHllNQ1BKJV1TVl+RMEAbjIAXzIyBCw4AGcC5AAhQog3JghTKuRgawAHHGsIcGKJWmlicmRkKjD6A1ZnLgD+IRE4IzKCiqqayMUE2J19MCYjYbNLGztHEdd+DxAvH2Q-UcCJkLQBrrklmKTH1PkU2NJszKA)
```js
interface ISelectable {
onSelectUntil(callback: (data : ISelectable) => void, until : (callToRemoveCallback : Function, callback: (data : ISelectable) => void) => void): void;
}

class BaseFileTile implements ISelectable {
  onSelectUntil(callback: (data : BaseFileTile) => void, until : (callToRemoveCallback : Function, callback: (data : ISelectable) => void) => void) : void {}
}
```
either both should throw an error or both should pass. 
## Actual behavior
The first one passes and the second one doesn't.

**Comment by SamChou19815** [comment]
This is expected due to variance rules.
