### ISSUE TITLE
[Regression] Parameter type inference in `Array.reduce`

### ISSUE THREAD

**Issue by kejistan** [facebook/flow#7680]
0.98.0 appears to have broken type inference around `Array.reduce`, specifically when the initial accumulator is a different type that the array values.

Flow version:
0.98.0

## Expected behavior
Infer the accumulator parameter type based on the initial accumulator value (when present).

## Actual behavior
Infers the accumulator parameter type to always be the array's type.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swE4AnAa0OwHMBxAU2yYsNwCUmATTXJgB4AKgBowANQB8AClRgwcAEYArAFxgA3gEMKFbQE8NAQT2GRUgL6j5YbblyYAtphjb8lDRJsKn2gA7+bBoy3mDCAJRgALxSkjYRXlq2FEz4mBSkyioAdLr6BjmpfAJyCr4BQRQ+5faOLm4eFLYRANyoluhYeEQkYEoUcFQszKzsXLz8QmKSsrbZGjpmRmCmBRbWtnXOru6e8bZ+gcFgoeKRMXHeqImSyQqp6ZmKqnnLRZOltgrAwGAAogBHTCEABu2hgLHwYA8diUcFBTDATAAHgJ-ND8AALQgAZzAeLsYG6BGIpAQhGxdlItCgbGKYH8um0TjSbBhBiCxMoYAARNpeadsYTyNR8bQwAAGHIATgA7BFvqdtOJQVFYmAjlUZCqwGqagptg09s0FG0OqggA

**Comment by goodmind** [comment]
@mvitousek is this related to new `EmptyT Zeroed` flavor?
