### ISSUE TITLE
string is casted to union of literal strings without any check

### ISSUE THREAD

**Issue by thecotne** [facebook/flow#7682]
Flow version: 0.98.0 (latest)

## Expected behavior

i expect this code to error because `currentPage` and `currentPage2` are `undefined` and not `'PersonalInfo' | 'ContactInfo' | 'ChangePassword'`

## Actual behavior

string is casted to union of literal strings without any check

[Try it for yourself](https://flow.org/try/#0MYewdgzgLgBADiCECWAjANgUwAoEMDmmEMAvDAN4BQAkAORyYBOE4u6AtMmAGYi0BcMWtiYswbAJI8+AGhq1QYKLmBRO0gUIDC4Zaqm9acmHWAALXGELs4uJAHcQjACabaWi1Zx2Ijl7UoAX0pFaBgWAFtvQkFoRi58UiFQKDBMAJDwMOAAV0ZGTCU8GJgAEgA1NhyiAB4oAE8GEG54RBQMaKIAPiTIzpoAflakNCxiogBtPvGAXRpBYVFWdAM+SkzIWFz8wqhxgCZBAApF5mXV2hgAH21dFSgL6+1PQjwHJ1cASl6QKPHB4btMYESbTEFzagLERncQrDSUIA)

## code 

```js
const possiblePages = {
	'personal-info': 'PersonalInfo',
	'contact-info': 'ContactInfo',
 	'change-password': 'ChangePassword'
}
const somePage: string = 'cotne'

const currentPage: $Values<typeof possiblePages> = somePage
	? possiblePages[somePage]
	: 'PersonalInfo'

const currentPage2: ('PersonalInfo' | 'ContactInfo' | 'ChangePassword') = somePage
	? possiblePages[somePage]
	: 'PersonalInfo'

```

**Comment by jcready** [comment]
[Smaller example](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AeAueBnALjAlgHYDmA3AFCiSwLIzwBmA9k5gN4A+zrA5NzxwC+FME0K54Adyg54AXkYsA2qgC6peAHpNUmfHxZ4hJpP0BbAA4R8YfDggBPeAAMohB8-LltRpvBAwMEwwWOQAFNI4mABGLBAgbgCUFBEymLgEJMnhkZiEAK5m0QHZqVFG+RAQpblITPjANWnwOA4WIEwMikzJQA):

```ts
declare var x: string;
declare var foo: {|foo:'foo'|};
const wat = foo[x]; // wat is now implicitly `any`

// no errors
(wat: boolean);
(wat: string);
(wat: number);
(wat: null);
(wat: void);
(wat: typeof foo);
```

**Comment by thecotne** [comment]
turns out this is kind of documented and same is true for arrays

https://flow.org/en/docs/types/objects/#toc-objects-as-maps

> property accesses are assumed to have the annotated type, even if the object does not have a value in that slot at runtime. It is the programmer’s responsibility to ensure the access is safe, as with arrays.

```js
var obj: { [number]: string } = {};
obj[42].length; // No type error, but will throw at runtime
```

https://flow.org/en/docs/types/arrays/#toc-array-access-is-unsafe

> When you retrieve an element from an array there is always a possibility that it is undefined. You could have either accessed an index which is out of the bounds of the array, or the element could not exist because it is a “sparse array”.

> For example, you could be accessing an element that is out of the bounds of the array.

```js
// @flow
let array: Array<number> = [0, 1, 2];
let value: number = array[3]; // Works.
                       // ^ undefined
```

## now i wonder if there is any strict rule i can turn on so that array/object item/property access returns `T | void` when there is no guarantee that object/array has value for key/property

**Comment by jcready** [comment]
Those docs are talking specifically about object types **with indexers**. My example is both missing an indexer in its type **and** is exact.

**Comment by thecotne** [comment]
@jcready now i see you are right this is much worse then i thought  

and i have found that this is already reported https://github.com/facebook/flow/issues/7392

closing this one
