### ISSUE TITLE
HTMLImageElement.decode() method is missing

### ISSUE THREAD

**Issue by jcready** [facebook/flow#7683]
## Missing/Incorrect APIs
The `decode()` method of the `HTMLImageElement` interface is missing. It returns a `Promise` that resolves when the image is decoded and it is safe to append the image to the DOM. This prevents a decoding delay on the next frame.

## Relevant documentation
https://html.spec.whatwg.org/multipage/#dom-img-decode
https://developer.mozilla.org/en-US/docs/Web/API/HTMLImageElement/decode

**Comment by vicapow** [comment]
Thanks for reporting @jcready I can try to fix this if I get some time. If anyone else wants to jump on this first, the relevant code is here: https://github.com/facebook/flow/blob/c34fd59cf346650fbf2eeaedc38af9adf1d17da8/lib/dom.js#L2974

**Comment by vicapow** [comment]
It ended up not taking much effort and I've done it here: https://github.com/facebook/flow/pull/7691

**Comment by vicapow** [comment]
Looks like this went out with 0.98.1
