### ISSUE TITLE
Type refinement requires triple equals

### ISSUE THREAD

**Issue by jasonLaster** [facebook/flow#7689]
Flow version: 98

## Expected behavior

Enumerated objects with a string type field should be refined with double equals.

## Actual behavior

Enumerated objects with a string type field require refinement with triple equals.

[try flow](https://flow.org/try/#0C4TwDgpgBAyg9gVwE4GMIGE4DtgR1AXigG9kAbKALigGdgkBLLAcygF8AoUSWYAQ1yESNRKgg1qxEcjQSSUANp1GLALrUA8gCMAVhBTB2AGigpsuHJKX0mzdVACCNEFhQA1PmQQQAPPBkY5njAAHzs4WwA3BxQsXHx8RwQAB5gcEiG3NAAYghkAGYMZGQQACYeXr4A1AAqYUTEAD4xUFV0AhDUAET5eYXFZV1GLVUAbp7e1DUcjVFJqemZ4NAAShB6BmUV3kJNI+243Ujr+rilQy3jldQAtgzJZTNzKWkZUFlQAAp4pbbb0A1mrE2vxDlAupAsL8WF0ntEXot3stYBBgMASuUJtU6kJcgUihj-j4cY0oGsNmd-vCFm8Pk4XO4sT5avU8f1CUySWSTptMZUoKTvlC-ljohxeq5gAxsFBmKj-GJMDhggAKFoHTq8DrDWIMUrUZS2DgASmoMFR6K2TIVaCVFlCAqgWDyFGILTMWDotFEaCEGoAdNIxDRAz7xAo9aporr8lAVQBCINoY0kFqxYAACyQcAA7k6IHmAKJIbNIFVdACqWAA1lhc1hYGGoABJAAiXWN0fY7uwXo99r9oIgoYCIf7wQjpSjHA4AHpZzG4-Hx-hGqSV8BA0PCEQIT9bB3U-P4sdgMgG87itFj92Wqfz6YgvgAGTPx-KnBbjpQeO7yHQ5guigAB+d8B2oS8yGiTggA)

```js
type SourceContent = {url : string }
type Content =   {[string]: AsyncValue<SourceContent> } ;
              
export type FulfilledValue<+T> = {|
  +state: "fulfilled",
  +value: T
|};
export type RejectedValue = {|
  +state: "rejected",
  value: mixed
|};
export type PendingValue = {|
  +state: "pending"
|};
export type SettledValue<+T> = FulfilledValue<T> | RejectedValue;
export type AsyncValue<+T> = FulfilledValue<T> | RejectedValue | PendingValue;

function getSourceContent(
  contents: Content,
  id: string
): SettledValue<SourceContent> | null {

  const content = contents[id];

  // NOTE: content.state === "pending" works!
  if (!content || content.state == "pending") {
    return null;
  }

  return content;
}
```

#### Error
```
32:   return content && content.state != "pending" ? content : null;
                                                     ^ Cannot return `content && (content.state != "pending") ? content : null` because: Either string literal `pending` [1] is incompatible with string literal `fulfilled` [2] in property `state`. Or string literal `pending` [1] is incompatible with string literal `rejected` [3] in property `state`.
References:
13:   +state: "pending"              ^ [1]
5:   +state: "fulfilled",
             ^ [2]
9:   +state: "rejected",
             ^ [3]
```

**Comment by dsainati1** [comment]
This is on purpose. We discourage the use of `==` (as do most JS style guides), with the exception of `== null` checks since those are equivalent to `=== null || === undefined`. The semantics are very surprising, and supporting refinements on this operator would have similarly surprising results.

**Comment by jasonLaster** [comment]
Thanks
