### ISSUE TITLE
Incorrect "string literal incompatible with empty" error when destructuring function params

### ISSUE THREAD

**Issue by chrisvasz** [facebook/flow#7694]
Flow version: 0.98

## Expected behavior

Destructuring in a function component parameter list works the same way as destructuring from the body of the function.

## Actual behavior

The first scenario gives an error and the second succeeds.

* [Flow try link](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoSgeirgBUALYAZzjV0gDslP4BzYADckrFJzjBO7KEQxwkM6AC5KMAJ5gkcAPLcACjjCsAvHADeAH3JwJAEyVxOAVxAAjBQBprcdZof4Ibnw4CwIYAHcIfC8LAF8KckwnKRhgQJ1uAAozOw8fDS1Yh10kAwgjAEpzbyIYJyhxTO8bAB4UOAYiTGMzPiQYAAkuzIrYn2AYABskYwAiAGEUac5bFChZnzW+mB78AH1XSbEAa3xYgD5mmzhJyWOrlqoUS5sKhJsklLTxbaGkTBG1WucFq9XEvi0xihBECSGCAH44AADKiw+EAEjMwFssSRcAcKIiEAxWJxSO8sXIlMo5Bo9CYrHY4FhvDyDAg4SQwigeVsEBEjgg-CEWjE8kUUAAdLTaIwtIFJmo4LZgJhMAoeGgtCwfAwtJMIGgUKl0hBMLqtLYRDAoE4MPVJHw4OUFMbvtLyBD6JEykY4KZLN5sQ5nG5PN4If5YcFQvgidFyHEEp8MN9vRBMmBDMwHHQfdmqmZvOxOMx4DlsXkvWNTFnysxSHA6Vay7b7UQOhqJKWYKhbM7zZILXAwGsUHhbmWav0wXAmsC2h0uj1fsNRuMpjMFkseKt1psoNtdgcjpxThcrjZbmeHk8XnA3pQPslU+lV-9AUXgaCGvlNP7oQCII4ERFE0UxbFcXxZEqCJElIPJGxKViIA)

**Comment by SamChou19815** [comment]
The issue seems to be fixed a while ago.
