### ISSUE TITLE
Parameter types of an unknown function are unknown

### ISSUE THREAD

**Issue by sAs59** [facebook/flow#7702]
Flow version: 0.98.1

The code below used to be working fine on versions **< 0.89**
Now it breaks on versions **> 0.90**

```
// @flow

type A = {
  foo: 'foo',
  bar: () => void
};

type B = {
  foo: 'foo'
};


function func(obj: A | B) {
  if (typeof obj.bar === 'function') obj.bar();
}
```

## Expected behavior

No error.

## Actual behavior

Error: Cannot call `obj.bar` because the parameter types of an unknown function [1] are unknown.

[Try-Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AQVALygDeiookssAXKAOSWx0A0ZoARgIYBOtAFAEpCAPlAA3WAEsAJogC+AbmTpsoAEKESbRrQZU68pckgBXAHYBjFJNhmK5i31jsAVrXwAfdUNLlJkUD4VLFgA5xcAOi5uQgIiBgdrWzohcKieQSU5IA)

**Comment by dsainati1** [comment]
This occurs because of a type-safety change we made in 0.9 when refining `mixed` to a function. Previously we allowed you to call this function with any arguments you wanted, but this is unsafe because just checking that `mixed` is a function doesn't give you any information about what arguments it expects. This behavior is correct.

What's weird about this example is that the type of `obj.bar` is set to `mixed`, which is what triggers the above behavior. Rather I think it should error since `B` has no `bar` property, or at the very least have type `() => void | void`. As a work around, if you give `B` a `bar` property (even one of type null or void), the error disappears.

**Comment by JeremyCraigMartinez** [comment]
Thank you for this response as it's very informative. However, I'm still unsure about a valid general workaround. See the example below

```js
// @flow strict

const dialog: mixed = document.getElementById('my-element-id');
if (dialog != null && typeof dialog.showModal === 'function') {
  dialog.showModal();
}
```

Error reads:

```
flow: error
infer - showModal (Cannot call `dialog.showModal` because the parameter types of an unknown function [1] are unknown.)```

**Comment by dsainati1** [comment]
When refining `mixed` to a function, all the information this gives you is that you have a function. This provides no information at all about how many or what kind of arguments the function accepts, or what its return type is. As such, it is not safe to call that function. The right thing to do here is not to use `mixed` and to find a specific type for `dialog`.

**Comment by skeggse** [comment]
I'd like the ability to create a type `Ref` that includes all referenceable types - objects and functions - for use in associating them via a `WeakMap` with arbitrary values. I am not able to do this as of 0.90.0 ([see try](https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKFygJ4AOApqAEqmSgC8oA3qAHSugC+oAPqABSvMAhgDtCAbQC6ASjoA+UCMIBufFljDUoAG51Qw0ogDqpQQGsAsoOIAeKpAA0oALYYAHqQAmslblKvisGgooJAArsI4GOqgAOakKLxo1ABclNRSqS7uHoy4oKBJKKFowtrMcQlJkFIq7Ph+AUEh4ZHRSPGJKWkO2oLQoaSZbp4yDHll7ZXUjlp9AzW4dbggoKTQ7fAAFqRJ+ERkoACiWqTCwfRZnj5hEShRpermpEhIgnG8pCdnqcenKKPjDA0XgAQk+f24PH2pFgNHBZ1AINo9AA5LAAEYAK1IOBRkMR8JQzCqMkKxWEKnyQL40Nhqy+RKqdGRoBRN1awhRAPy+UmHwZxOm9L+zFm-VIC3ynDW7VA1N4tLhAqZyNRGOxuO5PL5hMFPV1YvmlI4i1wQA)). Low-priority for sure, but it'd be neat to have some way of supporting functions-as-opaque-references.

**Comment by danielo515** [comment]
What is the solution to this? How can I call a function like this? I know the funciton takes no args, why I can't call it with no args?

```
function newFunction(
  value: string | Date | { toDate: (v: void) => Date }
): Date {
  if (typeof value === 'string') return new Date(value)
  if (typeof value?.toDate === 'function') return value.toDate()
  return value
}
```

**Comment by SamChou19815** [comment]
This now works
