### ISSUE TITLE
`flow` fails cryptically when .flowconfig references nonexistent files

### ISSUE THREAD

**Issue by spicyj** [facebook/flow#771]
This is what happens to me with a freshly cloned relay repo:

![image](https://cloud.githubusercontent.com/assets/6820/9620982/ec6fc7a6-50d5-11e5-825d-4bad6d5bffba.png)

The .log file has the same errors that `flow check` prints, but it would be nice if `flow` could print those errors too…

**Comment by mroch** [comment]
fixed a while back, yay
