### ISSUE TITLE
Declaring a function type prevents refinement invalidation

### ISSUE THREAD

**Issue by danwang** [facebook/flow#7718]
Flow version: all versions

## Expected behavior
This code should not pass type check because id is not guaranteed to be a string:

```jsx
const doSomething = (id: ?string) => {
  const bad: () => void = () => {id = null}
  if (id) {
    bad();
    (id: string);
  }
}
```

## Actual behavior
It passes type check.

Removing the type annotation on `const bad` makes it error as expected; for example: https://flow.org/try/#0MYewdgzgLgBAJiAyiAtgUygCwJZgOYwC8MAFNnAFwwD80ATrngJREB8MA3gFAwyiSwARgEM4RUi0LsO5cWACuAG0UBfHjGwAzUuRbdevEXBJMA3Ot5lKMeozPq1KoA

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBAJiAyiAtgUygCwJZgOYwC8MAFNnAFwwD80ATrngJREB8MA3gFAwyiSwARgENKpFoXYA3EOSLi2nOcTABXADbqAvjxjYAZqXItuvXiLgkmAbl28yY+oxu6dWoA

**Comment by SamChou19815** [comment]
This now errors.
