### ISSUE TITLE
Expected return type does not trigger error in invalid SetElemT against ObjT indexer with non-literal key

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#772]
Given

``` javascript
type T = { [key: string]: number };
```

The following does not fail:

``` javascript
function test(key: string): T {
  var ret = {}
  ret[key] = "not a number";
  return ret;
}
```

Replacing `key` with a literal triggers the expected error:

``` javascript
function test(): T {
  var ret = {};
  ret["key"] = "not a number";
  return ret;
}
```

Annotating the `ret` variable triggers the expected error:

``` javascript
function test(key: string): T {
  var ret: T = {};
  ret[key] = "not a number";
  return ret;
}
```

Assigning the property through `SetT` instead of `SetElemT` triggers the expected error:

``` javascript
function test(): T {
  var ret = {};
  ret.key = "not a number";
  return ret;
}
```

**Comment by mroch** [comment]
this is on master, right? seems similar to https://github.com/facebook/flow/commit/9b3fc8c3917f9299ea7d8fa8f853fca17bbf48cb but for computed properties?

**Comment by samwgoldman** [comment]
This is on master, yes. I just pulled and double-checked. I haven't dug into this one, except to reduce it down to this and bisect it a bit. This does seem like it could be related to that change, though.

**Comment by mroch** [comment]
so the problem here is that `ret` is not a dictionary, so `ret[key]` is ignored (!!!). we can't currently turn an existing `ObjT` into a dictionary.

I'm thinking that we could ban this practice, rather than try to mutate an existing object into a dictionary. we can already detect when it happens, since we explicitly ignore it right now:

```
    (* otherwise, string and number keys are allowed, but there's nothing else
       to flow without knowing their literal values. *)
    | (StrT _, ElemT(_, ObjT _, _))
    | (NumT _, ElemT(_, ObjT _, _)) ->
      ()
```

right now, you'd be able to annotate it with a dict type like you noted. once we have computed properties, you'd be able to do this instead:

```
var ret = {
  [key]: "not a number"
};
```

**Comment by samwgoldman** [comment]
Thank you for digging into this. I agree that we should ignore this loudly if we need to ignore it.

I guess I was hoping that the dictionary constraint, `T` from the declared return type of the function would propagate back to the type of `ret`, similar to how flow detects the following error:

```javascript
/* @flow */

type T = { foo: string };

function test(): T {
  var ret = {};
  ret.foo = 0;
  return ret;
}
```
```
test.js:7:13,13: number
This type is incompatible with
test.js:3:17,22: string
```

**Comment by mroch** [comment]
yeah, what's happening there is that `ret` starts out as (a tvar with a lower bound of) an `ObjT` with an empty property map and `dict_t = None`, then `ret.foo = 0` does a `SetPropT` which mutates the property map, then it flows `ret` to `T` and notices the collision.

the difference is that the property map is mutable, but the `dict_t` is not, so doing `ret[key] = 0` can't change it to `dict_t = Some {key = <key type>; value = number; ...}`.

**Comment by samwgoldman** [comment]
Thanks for explaining that so clearly. I think there may be value in inferring dictionary types, but understand that doing so would be complicated, so I'm happy to leave that as a wishlist item.

Let's use this issue to track adding some noisy output for this pattern, so people will know to add the appropriate annotations.

**Comment by SamChou19815** [comment]
This was fixed when I fixed the unsoundness issues with indexed writes.
