### ISSUE TITLE
Object.values/keys/entries on a sealed object should return a sealed array of object values/keys/entries

### ISSUE THREAD

**Issue by lxe** [facebook/flow#7721]
Flow version:

0.98.1

## Expected behavior

Object.values/keys/entries of a sealed object should return a sealed array of  values/keys/entries.

Looks like it's returning an array of `mixed`s instead. 

## Actual behavior

```js
const sealedObject = {
  foo: {
    prop: 2323
  },
  bar: { 
    key: 34
  }
}

// Good: Inference works on sealed objects:
// OK
sealedObject.foo.prop;

// Good:
// Cannot get `sealedObject.bar.lol` because property `lol` is missing in object literal [1].
sealedObject.bar.lol; 

// Values should return a sealed array:
const values = Object.values(sealedObject);

// Bad: Cannot get `values[0].prop` because property `prop` is missing in mixed [1].
values[0].prop;

// Bad: Cannot get `values[1].bar` because property `bar` is missing in mixed [1].
values[1].bar;
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBBCmBDANvAJgeQEYCt7FgF4YBvAKBhgDMQQAuUiymABwCcQWGAmAZj6YBfADRMsiNgxIwmlANbwAng14AWIWUFkyCFOmx4CAOhogA3DqSpMufFCPIQyMzAD0rmAHFaaBgGFEMDAQWABzeFgAA11rAzsHJ0iYLHxEAFcEVg4WeDYoRRhIx2QkgEsIGABbcohSsFCYOpgQWwIYZFKoXJQYAG0ARgBdI213GAB1AAsC8rAAclgoSfKYRDgrdFW2NkQCkCpGsCpctk38nIgAfmub67JQSFgANxQ0+AriOOMX5DeIAAoYvpWlAAJQWMg-P69AAMw3YnAsUPeA2G4jYELGABVlhUAO4gNhyCpUOrwe7gaDrPRoACC212MGIvRIpgY-REpHRPEEgwhQLpDMUsOGpgsAvpO2FcKM6PFG0FUtRsokZiAA

**Comment by goodmind** [comment]
No, it shouldn't this is unsound behavior

**Comment by lxe** [comment]
> No, it shouldn't this is unsound behavior

I think we should rethink the mantra of "soundness" as a "win all arguments" card, and give practicality some room.

It's reasonable to assume that values of a sealed object is a sealed array of items whose values can be inferred the same way as they are inferred on the sealed object.

Sealed arrays currently work very well:

https://flow.org/try/#0MYewdgzgLgBBCmBDANvAJgQQE5cQTxgF4YBtAbxgDMQQAuGAFgCYYBfAGhgHJE4osAlmADmXTswC6AbgBQMhCnTZceEgAYJAOmohZC1Jhz51WgEaIss+UgPLjARgkwA1MS4xEYEFAAW8LHyCIlx6NkpGqo4wAPTEAMxW+uEqJExOzs6hioYpaZpQIAAyIADu-gDCiAgAFACUVtHRMMUgANYQMMgCrfAewMDwEBBCwjAgAK5Qw2i9phNgaB1ClP4dvr0yjTBQeAAOvSCUHsjIMPCoALbwYLAQPoj7HVUeMONgAuDW2XaqcVqeeF8IyschkQA

Why not make `Object.values()` behave the same way?

**Comment by lxe** [comment]
Also if the issue is that order of the keys is not defined, I've never actually seen this in practice. I think it's safe to assume that the key order of sealed object matches what's written.

**Comment by goodmind** [comment]
You can use TypeScript if you're okay with sacrificing soundness

**Comment by goodmind** [comment]
Object.keys/values/entries would be revisited only after making object types exact by default

**Comment by lxe** [comment]
Literally nothing in Flow or Typescript is "sound". I can write a runtime thing 100 different ways that will pass the static checks and will still break when running the code. 

https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUBDATgc0QegCpEAuRAbwB8BnOAWwFMAFLOABzKsVsYBUALGGBxkwIOgCMGWRJQC+8xIXwBKCgChEWiAloAbBgDo9cHJlyGezVm0v0GAoThUBudXPXqdYalEQA3DD0YABMAeQkAKwZoRABeCm57FnZOJL5BYTIAZgAmRDk5N3UI6OhDEIZgIWt2aSgAT0MIIL00UpioABoAoNCO6B6AcisUtiGe8k1evRAGMnBK6rAGEK73V08UdEDg8KjOzc8gA

This weird zeal to bring flow to some imaginary line where things are "sound" is sacrificing real world value that a type checker should have.

**Comment by goodmind** [comment]
@lxe TypeScript doesn't have soundness in goals, but Flow does

**Comment by lyleunderwood** [comment]
@lxe Soundness isn't a binary here, it's on a spectrum. No software system is one hundred percent "sound" in an absolute sense, but the whole goal of introducing static typing to javascript is to increase overall soundness. Just because you can find errors or work around the type system using various corner cases doesn't mean that greater soundness is somehow an unreasonable goal, and just because those corner cases exist doesn't mean that what amounts to a huge hole in soundness should be introduced to the type system. It would let many errors through in a very high-traffic part of the API.

For what it's worth, I agree that `Object.values` is handled in a very poor and disappointing way in flow currently, and I sincerely hope that it is improved when exact by default happens.

**Comment by lxe** [comment]
Greater soundness is not an unreasonable goal.

Greater soundness at the cost of practicality, productivity, developer experience, with diminishing returns in the areas of runtime stability, is not a very good goal.

Sorry for getting over-passionate about it, but I've been wrestling both TypeScript and Flow to do what I think is correct, and I think I should just concede that the computer is right, and the human is wrong.
