### ISSUE TITLE
Hints / suggestions / autocomplete are missing

### ISSUE THREAD

**Issue by lxe** [facebook/flow#7723]
ref: https://github.com/flowtype/flow-for-vscode/issues/333

When types are available, key/property suggestions should be recommended by flow. 

Expected Behavior (TypeScript):

<img width="688" alt="Screen Shot 2019-05-05 at 8 01 45 AM" src="https://user-images.githubusercontent.com/1486609/57195955-ceb88280-6f0c-11e9-8104-3b5d75035b69.png">

Observed Behavior (flow-for-vscode with TS/JS VSCode extensions disabled):

<img width="461" alt="Screen Shot 2019-05-05 at 8 04 10 AM" src="https://user-images.githubusercontent.com/1486609/57195940-bea0a300-6f0c-11e9-9dfa-48314d475ca9.png">

It does work for classes, as demonstrated in the Readme:

<img width="849" alt="Screen Shot 2019-05-05 at 8 14 35 AM" src="https://user-images.githubusercontent.com/1486609/57196057-e80dfe80-6f0d-11e9-81cc-7ef99e9395a4.png">

Doesn't work for React components or props:

![nosuggestions1 mov](https://user-images.githubusercontent.com/1486609/57727760-26f72f00-7647-11e9-8868-2d90d2529b71.gif)

Sometimes it's showing incorrect suggestions.

<img width="907" alt="Screen Shot 2019-05-14 at 12 50 31 PM" src="https://user-images.githubusercontent.com/1486609/57727777-31b1c400-7647-11e9-9651-0c332ca2b218.png">

My vscode config:

```
{
  "editor.snippetSuggestions": "none",
  "editor.wordBasedSuggestions": false,
}
```

JS/TS Extension is disabled.

Flow version 0.98.1
Flow Language Support Extension 1.1.0

**Comment by maciekbb** [comment]
Are there any plans to implement this? This issue actually dates back to 2016 https://github.com/facebook/flow/issues/3074
