### ISSUE TITLE
Refinement does not work for arrow function

### ISSUE THREAD

**Issue by cjolowicz** [facebook/flow#7724]
Flow cannot type refine the case statement. Possibly the type refinement is not applied inside the arrow function passed to `filter`? The workaround at the end of this description suggests that this is indeed the case.

According to Try-Flow, this is already fixed in master, but I could not find the commit or another issue reporting this.

**Link to [Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAzngE5gC8YA3qmGAJYAmAXGAHYCuAtgEbkANPU4BDHnnbEMZRhwDmqAL4BudAGM4HaWAByAeX0AFKmABEB42bWbtGMACUAogFl9ANScB9QgGUnDl6+hADCIU6+vqZmzm6ePv6BwWERvtbo2Ph6cHA4AILqGIxapnQMmZJgFXBQeoZGymqYuAQOeDxwAG54JOS+XOrqeMTEBUUl1GVVLezVtbEe3n4BQaHhkcIMXKRk7L1kjRktYGPFHFQiAD7ZuadaV47tXT07-YPDo4VnTVBcHF8lbbkYgACmkogwBGo3BgMEEYFEAI47DuHAAlLQRMQEIwMOoABZgEGI8YcAB0FQxUwY6lEpEcrkWCRWyXWvlYIgYDDIeAwXDI53BkKo0K4sLAAH5OGKYGApBgIXgyVBGDBIWQQUCKJQAHxgLVgACElGoJLOZK1aLUXLAzDwUFEYowHJt3N5-MFCsh1rASmUqCAA)**

```js
/* @flow */

type User = {
  id: number,
  name: string
};

const NOOP = "NOOP";
const REMOVE_USER_SUCCESS = "REMOVE_USER_SUCCESS";

type NoopAction = {
  type: typeof NOOP
};

type RemoveUserSuccessAction = {
  type: typeof REMOVE_USER_SUCCESS,
  user: User
};

type Action =
  | NoopAction
  | RemoveUserSuccessAction;

function users(state = null, action: Action) {
  switch (action.type) {
    case REMOVE_USER_SUCCESS:
      return state == null ? null : state.filter(user => user !== action.user); // fails
    default:
      return state;
  }
}
```

Flow version: 0.98.1

## Expected behavior

No errors.

## Actual behavior

```
27:       return state == null ? null : state.filter(user => user !== action.user);
                                                                             ^ \
Cannot get `action.user` because property `user` is missing in `NoopAction` [1].
References:
24: function users(state = null, action: Action) {
                                         ^ [1]
```

## Workaround

This workaround passes flow:

```js
    case REMOVE_USER_SUCCESS: {
      const { user } = action;
      return state == null ? null : state.filter(u => u !== user);
    }
```

**Link to [Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAzngE5gC8YA3qmGAJYAmAXGAHYCuAtgEbkANPU4BDHnnbEMZRhwDmqAL4BudAGM4HaWAByAeX0AFKmABEB42bWbtGMACUAogFl9ANScB9QgGUnDl6+hADCIU6+vqZmzm6ePv6BwWERvtbo2Ph6cHA4AILqGIxapnQMmZJgFXBQeoZGymqYuAQOeDxwAG54JOS+XOrqeMTEBUUl1GVVLezVtbEe3n4BQaHhkcIMXKRk7L1kjRktYGPFHFQiAD7ZuadaV47tXT07-YPDo4VnTVBcHF8lbbkYgACmkogwBGo3BgMEEYFEAI47DuHAAlLQRMQEIwMOoABZgEGI8YcAB0FQxdAAkOpRKRHK5FgkVsl1r52FMGAxbDoaGAgRQlKYSd8RNywGQ8BguGRzuDIVRoVxYWAAPycFUwMBSDAQvBkqCMGCQsggrhUAB8ArAAEJKNRBWi1BKlOKwMw8FBRCqMKx3QwpTK5WAFXgXWA3W6gA)**

**Comment by AugustinLF** [comment]
It's a common issue, flow doesn't know that when the callback of your filter is called, your refinement is still valid. See the [FAQ](https://flow.org/en/docs/faq/#toc-i-m-in-a-closure-and-flow-ignores-the-if-check-that-asserts-that-foo-bar-is-defined-why).

**Comment by cjolowicz** [comment]
Thanks for the clarification.

Interesting that the code should pass flow on `master`, though.
