### ISSUE TITLE
Support `documentation` in LSP

### ISSUE THREAD

**Issue by namuol** [facebook/flow#7725]
## Proposal

Support the `documentation` field for various datatypes of the LSP implementation.

Examples include:

- [`CompletionItem::documentation`](https://microsoft.github.io/language-server-protocol/specification#textDocument_completion)
- [`SignatureInformation::documentation`](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp)
- [`ParameterInformation::documentation`](https://microsoft.github.io/language-server-protocol/specification#textDocument_signatureHelp)

## Use case

It's very helpful to be able to see documentation data in your IDE without needing to navigate to the implementation.

The GIF below was recorded with VSCode's `@builtin` TypeScript language features enabled, which implements the `documentation` field:

<a href="https://cl.ly/632078366b3f" target="_blank"><img src="https://d2ddoduugvun08.cloudfront.net/items/2N2P2G3k0g1I2z1D3K3E/Screen%20Recording%202019-05-15%20at%2010.14%20AM.gif" style="display: block;height: auto;width: 100%;"/></a>

(**Note:** this doesn't work well with Flow in practice of course, and you'll notice there are actually two type descriptions being displayed; one from Flow's LSP, and one from TS's)

**Comment by kevinbarabash** [comment]
I turned off the builtin TypeScript plugin because it was confusing seeing TypeScript's interpretation of Flow types along side the actual Flow types, but I really miss the documentation.

**Comment by mroch** [comment]
this was added starting in [Flow 0.128](https://github.com/facebook/flow/releases/tag/v0.128.0), with additional significant improvements in 0.133-0.136. :-D

**Comment by namuol** [comment]
> this was added starting in [Flow 0.128](https://github.com/facebook/flow/releases/tag/v0.128.0), with additional significant improvements in 0.133-0.136. :-D

Maybe a silly question: How feasible do you think it'd be to backport newer LSP functionality to older versions of Flow? Is there sufficient modularity with the LSP functionality that it could be carried back without a ton of refactoring?
