### ISSUE TITLE
Generics with new keyword

### ISSUE THREAD

**Issue by Whoaa512** [facebook/flow#7726]
Flow version: 0.98.1

## Expected behavior

No flow errors

## Actual behavior
Cannot call `this.Ctor` because property `constructor` is missing in `CacheValue`

[Try-Flow](https://flow.org/try/#0MYGwhgzhAEDCIEsCmA7ALgHlmYALJAamCAK5IB80A3gFDRxoD2ATgFxzhRY75GkV1og4IxQQ0zEsCbMAFADdiZeJAjsVXbHkJKKASmqD69NLgQQAdLBnQAvNEX8NEQQF8aggEZg5e9Tx1+Q3oASGYkNBJmFGgUJAB3aFNzKxlZPTcaVyA)

**Comment by goodmind** [comment]
https://flow.org/try/#0MYGwhgzhAEDCIEsCmA7ALgHlmYALJAamCAK5IBc0A3tMAPYoRoBOJwadzAFAJSUBudBABNoAXwB81AFDQ4HZpXiQIWHPiKkkE2dF31GLNgq79iZZVCXgoavIXPaeMua+hpcCCADpYC6AC80GZalhC6YtK6AEZg3Hxw6g5aLtAAkMxIaCTMKNAoSADu7p4+fpy8EdJiQA works
