### ISSUE TITLE
Cannot call `data.map` because property `map` is missing in `T` [1]

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/flow#7728]
Flow version:
0.98.1

Error:
Cannot call `data.map` because property `map` is missing in `T` [1]

Description:
Even after check if the value is empty I'm getting this error.

Try Flow:
[Link to try flow](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxLZFICiAZvUhnAL5z1QQhwDkUqDLwBQw+vgB2GYBAkFiAMSQw0ACwA8SlaoAiFFAD4AFMLhwwXEMEUSAXHCMBKOAF4DcAAqXrSTcrV65AaYpnAoUADmhAD89igSAJ4A2gC6ws44oWiyhPBJADYQKAAmwBIR2MQwADJFpeUprvKk5JRG9Cj5xI5ZOXnF+pXKgSiNLs1kFL7RWgH6xj1m2RK5cElIUFxQQzC0m9BjE63Te1sLomY0DEwYRk6u7plmZlW1JWURRjBQ+Eg9oWYLNwfAoJE4Ac8AHQwVRIMFVEaLZ5mSFoChqIxVU7QJHIyH0MqdfIJO7ONxwV51D7tTrdJGsf5mAQwfBQORPZ6Fd7lELIgbkXnPDZbUKsYRisxiSTSWQcfyqADSSAShHuHLgzNZci8wOIkIEhAg+QAbkgjEk8BIUCAkPZeCAEkqErw2Ckeuw4KIYAkwEg4E6mhyrTb7LkoB9xV6fX6nYQRk0nalQlKpDAZHIALKO5WEDwoCJmjLCACQy1WeH5KGwXPqFTgwugbCaNFmGljI2MTG0sdxnuRwHoRgAhJXnJq2Xw3rXITORBDx3JK5CQCgwEYANbKh4OdSlY0GHCbhKQ4NIVjqAD0e4MjndQA)

**Comment by dsainati1** [comment]
Flow doesn't infer generic types, so you need to annotate the return type of your function like so: https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecCuAzkgMowoxLZFICiAZvUhnAL5z1QQhwDkUqDLwBQw+vgB2GYBAkFiAMSQw0ACwA8SlaoAiFFAD4AFMLhwwXEMEUSAXHCMBKOAF4DcAAqXrSTcrV65AaYpnAoUADmhAD89igSAJ4A2gC6ws72OAA2ECgAJsASEfYARhAQWagS2Hn6cPbRWgH62EhQXFC20bTt0Ow4oWiyhPBJOfmFEdjEMAAyuQVFKa7ypOSURvQoWcSOg8OjteTTyoEoyy6rZBS+jf66+sZ7ZkMSI3BJbR0nMD0dF1d1rc-tAnqIzDQGEwMEYnK53AMzGYZvMJkUjDAoPgkHtQmYLNwfAoJE48UiAHQwVRIEkzM7PJFmcloChqIwzEFQBmM8n0QrbLIJWHONxwFELSabba7BmsXFmAQwfBQOSIpHjRZTMlHFAhRlfaChVjCY1mMSSaSyDj3ADSSAShDhargiuVci8hOI5IEhAqADckEYkngJCgQEh7LwQAk7QleGwUnt2HBRDAEmAkHBYys1aHw-YRlBJibU+nM7HCGcVrHUqFzVIYDI5ABZGP2wgeFARQPOAYASFe7zwOuwGsmrV6UDYKxoTQ0FbOxiY2gr3JTjOA9CMAEIdc5XSq+KjNeTTyIyQe5DrySAUGAjABre3whzqAp+gw4J8Jcl5pCsdQAHp3wMRwkyAA

**Comment by BrunoQuaresma** [comment]
@dsainati1 thank you! But the error description should be better right? Or have some warning about not infer generic types?
