### ISSUE TITLE
Object.keys cannot be used correctly in type refinement of isEmpty.

### ISSUE THREAD

**Issue by AndrewSouthpaw** [facebook/flow#7729]
Flow version: v0.98.1

Given a [Flow try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxCBnAUQFsAHfATwApDtbN8AuMAbwF8AlKDDcARnDgwApgENSAUlwALKbgDW5ZMF6owYAE5T8mfaQDyogFar8AOjVSG5Fmw4Db07AHN8SsAF5AsAAGVD50XBJyfDA4K24eAB9EvjBE3jAoCW5o-VYvMFT-MCZ+bjkGAV09Gtq9VEIoEoBCChp6ZjjLAQEdPSYu2yy4HPw8717gbXIlOEwYABMwbDgYqX19OH0w9EaWi2sCe0dnLvdPHz9A4uDenmqBqyHssFz8ye0ZGHI4V9n5pYrNYbLZhIA), I'd expect no errors. Instead it errors, unable to perform the correct type refinement.

```js

function isEmpty(input: {})/* : boolean %checks */ {
  return Object.keys(input).length === 0
}

const obj: {||} | { foo: string } = ({}: any)
            
if (!isEmpty(obj)) {
  (obj.foo: string) // should not error
}

if (!Object.keys(obj).length === 0) {
  (obj.foo: string) // also should not error
}
```

**Comment by dsainati1** [comment]
I don't think we support this refinement right now, but it seems like a reasonable feature to add.

**Comment by goodmind** [comment]
Is this related to tuples length refinement or completely unrelated?

**Comment by AndrewSouthpaw** [comment]
I don't have enough context about your question to answer whether it's truly unrelated, but it wasn't because of tuples length refinement that I'm asking the question. ;-)

**Comment by SamChou19815** [comment]
This is unlikely to get supported.
