### ISSUE TITLE
inference error related to position in source files

### ISSUE THREAD

**Issue by chasestarr** [facebook/flow#7745]
## Description
In my source code, I have 3 folders sorted alphabetically. The first and third folders contain the exact same code. The second folder exports a typed function with generics. Strangely, _only the third folder fails a flow check_, folder one passes.

<img width="279" alt="Screen Shot 2019-05-20 at 1 47 26 PM" src="https://user-images.githubusercontent.com/5317799/58050999-d760a980-7b05-11e9-8b1d-a01a56843978.png">

Flow version: 0.98.1

## Expected behavior
* Source code order should not affect flow check.
* Flow should infer the function type with only one generic.

## Actual behavior
* Duplicate code alphabetically after type definition fails flow check but if before, it passes.
* Flow infers the function type with two generics.
* Link to Try-Flow or Github repo: https://github.com/chasestarr/flow-reproduce-infer-error-position-in-source

## Notes
* If the `Options` type is in the same file as `fn` calls, flow infers correctly.
* If the code is within the same folder, flow infers correctly.

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/c-after/index.js:6:24

string [1] is incompatible with number [2] in type argument N.

     src/c-after/index.js
     3│ import fn from "../b-function/index.js";
     4│ import type {Options} from "./types.js";
     5│
 [1] 6│ export const Comp = fn<Options>("hello", options => 2);
     7│

     src/b-function/index.js
 [2] 6│   <N: number, T>(N, (T) => number): any,



Found 1 error
```

**Comment by SamChou19815** [comment]
The issue no longer repros on newer versions of Flow, and it is likely fixed after types-first.
