### ISSUE TITLE
singleton strings cannot have spaces

### ISSUE THREAD

**Issue by gregwebs** [facebook/flow#775]
This is not blocking me because the workaround is just to use underscores in place of spaces. But maybe it is an easy fix.

```
type HasSpacing = "foo bar"
function takeSingleton(str: HasSpacing){
  console.log(str)
}
takeSingleton("foo bar")
```

```
/home/ruby/frontrow/student-web/js/helpers/translate.js:7:1,24: function call
Error:
/home/ruby/frontrow/student-web/js/helpers/translate.js:7:15,23: string
Expected string literal foo bar
/home/ruby/frontrow/student-web/js/helpers/translate.js:3:19,27: string literal foo bar
```

**Comment by mroch** [comment]
weird. this comes from https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L3519, which is before my time. trying to figure out why it's there... removing those two functions fixes it.

**Comment by gregwebs** [comment]
thanks!
