### ISSUE TITLE
Documentation for $Values utility type should specify using Object.freeze() to create enums from an object's values.

### ISSUE THREAD

**Issue by taylorkline** [facebook/flow#7752]
The [values](https://flow.org/en/docs/types/utilities/#toc-values) documentation correctly specifies that: "`$Values<T>` represents the union type of all the value types (**not the values, but their types**!) of the enumerable properties in an `Object Type T`" (bolded emphasis mine)

However, you can get the union of all the values themselves if you freeze the object first. Here's an example from #627:

```
const messageType = Object.freeze({
  TEXT: 0,
  CREATE_THREAD: 1,
});
type MessageType = $Values<typeof messageType>;

// works, as expected
const workingEx: MessageType = messageType.TEXT;

// errors, but wouldn't have errored if messageType was not frozen since 2 is a number
const test: MessageType = 2;
```

The documentation of `$Values<T>` should be updated to mention this important distinction which is valuable for enums.

**Comment by mgtitimoli** [comment]
I recommend you to try [this other alternative](https://github.com/facebook/flow/issues/627#issuecomment-389668600)

**Comment by danielo515** [comment]
@mgtitimoli while your explained alternative is safer, this is about document that `$Values` can be used to extract literal enums from frozen objects, which is an undocumented feature and gave me a couple of headaches to understand why some of my enums worked as expected and some didn't
