### ISSUE TITLE
flow-bin@0.99 not yet published on npm

### ISSUE THREAD

**Issue by fabiomcosta** [facebook/flow#7756]
Even though the sites says the latest version is 0.99, it hasn't yet been published to npm for the flow-bin package, see: https://www.npmjs.com/package/flow-bin

https://flow.org/en/
https://github.com/facebook/flow/releases

**Comment by retyui** [comment]
![image](https://user-images.githubusercontent.com/4661784/58328894-f039c980-7e3b-11e9-84ae-b1041ade12bd.png)

**Comment by jcready** [comment]
@retyui https://github.com/facebook/flow/releases/tag/v0.99.0

**Comment by retyui** [comment]
Can be closed

**Comment by jcready** [comment]
@retyui why do you say that? As of the time of writing this comment npm still shows 0.98.1 as the latest version, yet [version 0.99.0 as been released](https://github.com/facebook/flow/releases/tag/v0.99.0).

**Comment by goodmind** [comment]
https://www.npmjs.com/package/flow-bin/v/0.99.0
