### ISSUE TITLE
Flow doesn't check a react component witch start with a lower letter

### ISSUE THREAD

**Issue by retyui** [facebook/flow#7757]
Flow version: 0.98.1

## Expected behavior
Flow.js will check React props without dependency of name

## Actual behavior
Component `Fbt` work fine,
but a component called `fbt` seems ignored:

[Try ...](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgAUcwBnOAXjgG9y4+UAXAEZyAXwrkAJkjQAbFETgA3BXEwAjGAMTEYAEgDKMFDCSykLFgDEArgDsMwCHZSyAwrkh2kdmAB4mCFYAPgppOQV6FSg4K01tZHR9IxMzC2t7R2dXD3BnH39AkIlyPzj4FHYuACZROAB6UIb6uCQADzoMJElWqBwoABo4AHMICElKUo0KqtqGpvqW9Rt4AAskRTsIXv64IYB1VZM4YDYwHHVzEAB+ciA)

```js
import React from 'react';

type Props = {
   a:1
};

declare var fbt: React$StatelessFunctionalComponent<Props>;
declare var Fbt: React$StatelessFunctionalComponent<Props>;


<Fbt a={2} />; // expected error, good


<fbt a={2} />; // but here no error , What is problem?
```

**Comment by goodmind** [comment]
@retyui because lower letters are for DOM elements

**Comment by goodmind** [comment]
`fbt` is also already supported by flow in OCaml code

**Comment by fabiomcosta** [comment]
Yeah, this is correct, the JSX transform uses the capital letter to define if it will create a React.createElement call to a user defined component or a DOM element, so this is a JSX behavior that Flow is just following.

**Comment by goodmind** [comment]
https://github.com/facebook/flow/tree/master/tests/facebook_fbt_some
