### ISSUE TITLE
Flow refinement with simple conditional expression against undefined

### ISSUE THREAD

**Issue by ShukantPal** [facebook/flow#7764]
Flow version: 0.98.1

## Expected behavior

I am building a react component where I want to use this type of syntax:

```
// PropsType = { knotVector: ?TupleVector };

const knotVectorLength = (props.knotVector) ? props.knotVector.length : 0;
```
The conditional expression already checks if `props.knotVector` isn't undefined; hence, using `props.knotVector.length` should be valid (assuming that `TupleVector` defines a `length` property).

## Actual behavior

I get an error that `undefined` and `null` are missing the `length` property. It will be hard for me to use the explicit syntax: `if (props.knotVector != null)` since I am also using another (strict) ESLint plugin that is against this overly verbose code style.

**Comment by SukantPal** [comment]
Also, Flow should be compatible with lodash's `isNil`.

**Comment by SamChou19815** [comment]
Cannot repro
