### ISSUE TITLE
Object index of a union type silently does not work

### ISSUE THREAD

**Issue by gregwebs** [facebook/flow#777]
I tried to save myself some typing (pun intended!) with a definition like this:

```
type IntlText = "Hello" | "GoodBye"
type IntlMsgs = { [key: IntlText]: string }
var messages : IntlMsgs =
  { "Hello": "Hola"
  }
console.log(messages["GoodBye"])
```

However, flow does not reject this program

**Comment by avikchaudhuri** [comment]
This is working as intended: dictionary types have some necessary unsoundness built into them.
