### ISSUE TITLE
Lint: inexact-spread fails with invalid "statics of function type"

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#7770]
Flow version: 0.99.1

I am unsure if this is a bug or just a new feature which needs more explanation. I have the following code:

```js
// @flow

type GlobPattern = string;

type GlobOptions = {|
  +absolute?: boolean,
  +ignore?: $ReadOnlyArray<string>,
  +root?: string,
|};

type GlobCallback = (
  error: null | Error,
  filenames: $ReadOnlyArray<string>,
) => void;

export default function glob(
  globPattern: GlobPattern,
  options: GlobOptions | GlobCallback,
) {
  // implementation reduced to absolute minimum
  return { ignore: ['**/node_modules/**'], ...options };
}
```

However, it fails on `inexact-spread` lint:

```text
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/test.js:20:10

Cannot determine the type of object literal [1] because it contains a spread of inexact statics of function type [2].
Being inexact, statics of function type [2] might be missing the types of some properties that are being copied. Perhaps
you could make it exact? (inexact-spread)

     17│   globPattern: GlobPattern,
 [2] 18│   options: GlobOptions | GlobCallback,
     19│ ) {
 [1] 20│   return { ignore: ['**/node_modules/**'], ...options };
     21│ }
     22│

Found 1 error
```

This is a new error after upgrading from 98 to 99. But I cannot understand what is wrong here. What are `statics of function type`? And why is it wrong in my example? Thank you very much for checking it.

**Comment by goodmind** [comment]
@mrtnzlml you're spreading callback function

**Comment by mrtnzlml** [comment]
Aha! Silly me. Now it's obvious. I couldn't understand the error message. Still a bit confused about what are statics of function type though.

Thank you very much @goodmind, not a bug.

**Comment by goodmind** [comment]
@mrtnzlml static of function type is something like this
```
function f() {}
f.bar = 'ok'
```

**Comment by goodmind** [comment]
Error message could be better, I don't think you can make exact function statics

**Comment by mrtnzlml** [comment]
I see, thanks. Yeah, the error message is difficult to understand. I was really trying to figure out what does it mean to make a function (statics) exact.
