### ISSUE TITLE
[React] Cannot call useCallback with function callback because T is incompatible with rest array

### ISSUE THREAD

**Issue by retyui** [facebook/flow#7788]
I can call a `useCallback(callback);` hook with a callback function witch looks like `(...args: T) => {}`

## Incorrect APIs

```js
import { useCallback } from 'react';

const useFn = <Args: $ReadOnlyArray<empty>>(fn: (...a: Args) => mixed): void => {
    // Cannot call `useCallback` with function bound to `callback` because `Args` is incompatible with rest array.
    useCallback((...args: Args) => fn(...args)); 
 
}
```
[try...](https://flow.org/try/#0JYWwDg9gTgLgBAbzgVwM4FMDCBDANrgI2wGMBrOAXzgDMoIQ4ByKdEmRgbgCgviIA7VPDToAYvzgBeOAB4AglADmqAFxwAJACVWAEwDy-XAE8FUbEZnpwMIwD5bACmr81DgHQfsahcoCUU2zgQYAAPdB1fNQA3CGAdAMQuOGS4JJSRHHwiMgd3TyVVOB9Uf0lA5zy3bALfX25UiiA)

## Relevant documentation
does not need

**Comment by jbrown215** [comment]
Your `useFn` function has no need to be generic. The type parameter `Args` only appears in the input to the function, so it has no effect on the return type. If you replace Args with just `$ReadOnlyArray<empty>` then there are no errors
