### ISSUE TITLE
Function.prototype.apply should accept 2 arguments only

### ISSUE THREAD

**Issue by kangax** [facebook/flow#7791]
Just had a bug in production where someone accidentally used `Function#apply` instead of `Function#call`. Roughly like so:

```js
function getUrl() { return 'some string' }
axios[method].apply(axios, getUrl(), someArg, someOtherArg);
```

I looked into why Flow hasn't caught this. `getUrl()` returning a string means that it conforms to an Iterable expected of a 2nd argument. But if `apply` didn't accept more than 2 arguments, this would have been caught.

To reproduce:

```js
(function () { }).apply({}, [], 1) // no error
```

Flow version: 0.100

## Expected behavior

It should error with "expected 2 arguments" or some such.

## Actual behavior

No error is reported.

* Link to Try-Flow or Github repo: https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygCgJQG8C+AUKhgHQCGADpQDYCemARIwDSKNhxSLkBOv5Oo2wBuIA

TS gets this right: https://www.typescriptlang.org/play/#src=(function%20()%20%7B%20%7D).apply(%7B%7D%2C%20%5B%5D%2C%201)

Surprisingly, according to this test, https://github.com/samwgoldman/flow/blob/ef5d4a4b896ad9cb1fb49227e253c7135b349255/tests/function/apply.js `apply(..., "some string")` should be an error, but it seems that's no longer the case (since version 0.39)?

**Comment by goodmind** [comment]
I believe this is related to spread?
