### ISSUE TITLE
Missing Maybe property should error (regression)

### ISSUE THREAD

**Issue by keeganstreet** [facebook/flow#7794]
This example is provided in the [Maybe Type documentation](https://flow.org/en/docs/types/maybe/):

```
// @flow
function acceptsMaybeProp({ value }: { value: ?number }) {
  // ...
}

acceptsMaybeProp({ value: undefined }); // Works!
acceptsMaybeProp({});                   // Error!
```

The error in this example is reported in Flow 0.88, but is not reported in Flow version 0.89 and newer.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBDXXAUwAd8BnAWTIE8AjKgBQCc4aAKAN5gAbmRiYqYAL4AuMMLESq8gPzZMAWw7cZASgWowYYMDAA6S6mnoK1Ok1YcefIaPGT5OACZUohbCpvfQBuEzMAdThuAGt6AEJUO1oGZnYuXgFBaT0w43yCwoLTMABlTBoaOHogsHw4MA5yUipuXm54sH4AC3x8GnpZU1hEc2iAc2AqbGBvOFx6YHwWGipFzScqYD10EoBRNuiwQnowblpo-FqAsAAGcwAOB4AaRsx8MGw4D-uHgE4ANRAA

**Comment by vicapow** [comment]
I suspect this may actually be related to the unsealed objects and `{}`.

You can see that this errors with the following:

````js
acceptsMaybeProp({...null});
```

and also

```
type E = {};
const a: E = {};
acceptsMaybeProp(a);
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBDXXAUwAd8BnAWTIE8AjKgBQCc4aAKAN5gAbmRiYqYAL4AuMMLESq8gPzZMAWw7cZASgWowYYMDAA6S6mnoK1Ok1YcefIaPGT5OACZUohbCpvfQBuEzMAdThuAGt6AEJUO1oGZnYuXgFBS3MNGBhpPTDjEtKy0tMwAGVMGho4eiCwfDgwDnJSKm5ebniwfgALfHwaellTWERzaIBzYCpsYG84XHpgfBYaKjXNJypgPXRKgFFu6LBCejBuWmj8JoCwAAZzAA5XgBo2zHwwbDhfi9XgBOADUQA

**Comment by vicapow** [comment]
Could potentially be merged with: https://github.com/facebook/flow/issues/7424

**Comment by SamChou19815** [comment]
This is now erroring.
