### ISSUE TITLE
Parser allows injection of runtime code via comments

### ISSUE THREAD

**Issue by lhorie** [facebook/flow#7801]
Flow version: 0.100.0

## Expected behavior

Type comments should not be treated as runtime code

## Actual behavior

Specially crafted comments allow fooling flow into thinking something has a type that differs arbitrarily from its runtime type

* Link to Try-Flow or Github repo:

https://flow.org/try/#0MYewdgzgLgBAhjAvDA5ACwKYBsshQbgChRJYAjJGAbwQHoAqALhgEYZ7aBfIsgOjl5QQAMQCWADwwATABQBKfDFq0YENCACuWKTAwAnPSD0xMejIT5CAMiADu+gMJwIGeYuUwwIWKYxA

Corresponding transpiled code (via babel):

https://babeljs.io/repl/#?babili=false&browsers=last%202%20Chrome%20versions&build=&builtIns=false&spec=false&loose=false&code_lz=MYewdgzgLgBAhjAvDA5ACwKYBsshQbgChRJYAjJGAbwQHoAqALhgEYZ7aBfIsgOjl5QQAMQCWADwwATABQBKfDFq0YENCACuWKTAwAnPSD0xMejIT5CAMiADu-gMJwIGeYuUwwIWKYxA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=flow&prettier=false&targets=&version=7.4.5&externalPlugins=%40babel%2Fplugin-proposal-optional-chaining%407.2.0

**Comment by goodmind** [comment]
I think this is by design

**Comment by wchargin** [comment]
Link to docs, for completeness:
<https://flow.org/en/docs/types/comments/>
