### ISSUE TITLE
Flow (maybe ocaml) error when using error.message

### ISSUE THREAD

**Issue by runn1ng** [facebook/flow#781]
I have this piece of code in a class (simplified here to the smallest failing example)

    try {
        throw new Error("message");
    } catch (err) { 
        if (err.message === "message") {
            return 0;
        } else {
            return 0;
        }
    }

When I try to run `flow` on this, I get this error

    <<<<<<<<
    merge_env /[file address].js:451:9,464:9:
    try: non-uniform distribution of entry err: None, None, Some var:
    Called from file "set.ml", line 304, characters 38-41
    Called from file "list.ml", line 73, characters 12-15
    >>>>>>>>

and flow ignores this file. When I fix it like this, it starts working as expected

    try {
        throw new Error("message");
    } catch (err) { 
        var isString: boolean = err.message === "message";
        if (isString) {
            return 0;
        } else {
            return 0;
        }
    }

I have no idea what that means :)

**Comment by samwgoldman** [comment]
Thank you for making such a clear reproducible test case! Definitely a bug. I was just poking around this code myself.

**Comment by samwgoldman** [comment]
Slightly smaller example:
```javascript
try {
} catch (e) { 
    if (e) {
      return;
    }
}
```

The binding `e` only exists in the catch, which makes this kind of related to the let/const stuff I'm working on, too. I think I can fix this as part of that work.

**Comment by gabelevi** [comment]
Thanks for the report! @bhosmer patched this in https://github.com/facebook/flow/commit/2816602f5cf609ceb677b386b26d1bca416e1274, though a better fix will come in the future. See the commit message more more info
