### ISSUE TITLE
Duplicate export with separate `declare module`

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7810]
Flow version: 0.100.0

```js
declare module 'module/scope/element' {
	declare export default () => number;
}

declare module 'module/scope' {
	declare export {default as element} from 'module/scope/element';
}
                    
declare module 'module' {
	declare export {element} from 'module/scope';
}
```

## Expected behavior

No errors

## Actual behavior

```
13: 	declare export {element} from 'module/scope';
                     ^ Duplicate export for `element`
```

* Link to Try-Flow or Github repo:

https://flow.org/try/#0FAgmFMGMBsEMCdwAIC2B7UBXayDk6scB6AZ0jQAdwjwcVwA7AF1wG9gBICGBZcADwpp4TJBABmsbKIAUASiQBeAHxIGmFACNw8ANzAAvmChxEqDNjwFLpclTadupvoOGjWEqdFGwSSWuD0zAZI4vBoKEj4FsRklNQBQSz6Rkhp6RmZmcBOvOaEVjHgDlwmeQJCIkisiYxMIWERUdaxdsUpQA

**Comment by goodmind** [comment]
@samwgoldman I see commits about rewriting modules, can you help with this one?

**Comment by goodmind** [comment]
@mroch this blocks many modules on `flow-typed`

**Comment by saml-kounta** [comment]
This is still very much an issue. It doesn't make any sense why this is seen as a duplicate export.

**Comment by SamChou19815** [comment]
This issue seems to be fixed a long time ago
