### ISSUE TITLE
Relay types - Importing non-existent type `import type { DoesntExist } from "./file"` will import as any

### ISSUE THREAD

**Issue by Stephen2** [facebook/flow#7818]
Flow version:
`0.95.1`

## Expected behavior
Flow should throw error when `import type` for a type that isn't exported by the other file

## Actual behavior
Flow is happy to import anything, and treats it as `any` typed.

# Component file:
```
import type {
  LinkAppPageDetail_LinkAppMutationVariables as LinkAppMutationVariables,
  LinkAppPageDetail_LinkAppMutationResponse as LinkAppMutationResponse,
} from "types/LinkAppPageDetail_LinkAppMutation.graphql";
```

graphQL relay file (relevant bits):
```
/*::
import type { ConcreteRequest } from 'relay-runtime';
export type LinkAppInput = {|
  orgId: string,
  requestId: string,
  clientMutationId?: ?string,
|};
export type LinkAppPageDetail_LinkAppMutationVariables = {|
  input: LinkAppInput
|};
export type LinkAppPageDetail_LinkAppMutationResponse = {|
  +linkApp: ?{|
    +orgIdToken: string
  |}
|};
export type LinkAppPageDetail_LinkAppMutation = {|
  variables: LinkAppPageDetail_LinkAppMutationVariables,
  response: LinkAppPageDetail_LinkAppMutationResponse,
|};
*/
```

It works great!

But I can also change component to:
```
import type {
  FAKE,
  POTATO,
} from "types/LinkAppPageDetail_LinkAppMutation.graphql";
```
And flow doesn't complain about can't find import, it just treats as `any` and allows bugs through :(

**Comment by Stephen2** [comment]
Sorry about lack of replication repository, I'll try and do it this weekend, but work is ultra busy right now.

I'll come back to this ASAP if it's not a simple situtation to work on.

I bet using `https://github.com/relayjs/relay-examples/tree/master/todo` could replicate immediately

**Comment by SamChou19815** [comment]
This should be fixed a long time ago
