### ISSUE TITLE
Cannot declare stateless functional component with defaultProps in libdefs

### ISSUE THREAD

**Issue by karmeleon** [facebook/flow#7826]
Flow version: 0.101.0

I've written a stateless functional React component similar to this:

```jsx
import React from 'react';

type Props: {
    a: number,
    b: string,
};

function Component({a, b}: Props): React.Node {
    return <div>a is {a} and b is {b}</div>;
}

Component.defaultProps = {
    a: 1,
};

export default Component;
```

I would like to be able to write a Flow libdef for this component so that it can be imported with its default props into another package. But I can't seem to get it to work, no matter how I declare `Component`. Is there a way to do this?

## Expected behavior
The linked Try-Flow typechecks correctly

## Actual behavior
The linked Try-Flow does not recognize the existence of `defaultProps` on component `Component`.

* Link to Try-Flow or Github repo:
[Link!](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocgEyTQBsUi4YBPMJOABRzAGc4AvHADeKAFxwAdgFcQAIyRQANHDkTeMKMEkBzAL4VqtBkwBujOAGFckSUkkwJw8nDgAKMD14TuEPgEoJZHQYABIAOQgaClcaTBRpOhhfPicXVzhxKVkFZXSDcgLyAHpizLo6ZgALDk8-fkYOGqJyNAhJDTg0QTgAHmtwdvt4FAFhAFY9VQEAIl5pMBm4YoA+ClLq4H5eKohEqlUOCABrFBZDtATeDgB3DmPJCBu4AAMUF7gqlAa4OISkupgVrtToHIT9GxDBzTOYLJarUhAA)

**Comment by dsainati1** [comment]
This is gonna be fixed in the next release! Update your try-flow link to use the master version and you'll see the error goes away!

**Comment by karmeleon** [comment]
Oh perfect timing, thanks!
