### ISSUE TITLE
Flow cannot distinguish function from object

### ISSUE THREAD

**Issue by retyui** [facebook/flow#7831]
Flow version: 0.100.0

I am trying to describe the type for the function `makeStyles()` from [`@material-ui/core`](https://github.com/flow-typed/flow-typed/pull/3373)

And using overload to describe two cases:
- when the first argument is a function
- when the usual object

## Expected behavior
Can be described not called object

## Actual behavior
And ran into the problem that the flow cannot distinguish the function from the object:

[Try link](https://flow.org/try/#0C4TwDgpgBAKgFhAttAvFA3gKCgYwPYA2eATgFwYCGOwAlgG4TkDOwxNAdgOYC+m3A3JkyhIUAMrACUNFgCQAbRZsuAXXLpevTABMIOAhWLQ6hqIgoBrRtigAyKAAoHOCgQIAjKhfIP4SCACU0gB84pJBKKF0eDTaQTb2Ti5unjjeYQQRUTFxQpjmVg7oxHh4wKQa3AGCBRBOwAjIWRg2Dg3+AHT4RMQdVLQMzKwcnNU2re3IXYQkfdT0jFDsAK6I7hDE1VAA9NtQEAAekNT7xCXEQlBQRsDLxOyOxaXllWNV-EA)
```js
type Theme = {
 color: {active: string}
};

type Stl = {
	[string]: {}
}

declare var make:
  & ((callback: (Theme) => Stl) => void) 
  & ((callback: Stl) => void)


make({root:{}});

make((theme) => {
  (theme.color.active: string);
  
  (theme.color.active: number); // expect error

  return ({root:{}});
});
```

**Comment by retyui** [comment]
https://github.com/flow-typed/flow-typed/pull/3373

**Comment by chasestarr** [comment]
looks to be similar to https://github.com/facebook/flow/issues/6784 (who's author is seemingly working on material-ui flow-typed defs as well), and ultimately links to this umbrella issue https://github.com/facebook/flow/issues/6490. Is using `$Shape` a reasonable work-around? Is there a better suggestion?

**Comment by retyui** [comment]
@chasestarr hack with `$Shape<>` has helped

[Try flow.js](https://flow.org/try/#0C4TwDgpgBAKgFhAttAvFA3gKCgYwPYA2eATgFwYCGOwAlgG4TkDOwxNAdgOYC+m3A3JkyhIUAMrACUNFgCQAbRZsuAXXIASMXAqQAPOm4A+PkIAmEHAQrFoda1EQUA1o2xQAZFAAUXnBQIEAEZUTuRe8EgQAJTShuKSMShxdHg0pjFunj5+AcE4ofEEicmp6UKYji5e6MR4eMCkBtxRgpUQPsAIyMUYbl6dkQB0+ETEg1S0DMysHJwtbn0DyMOEJOPU9IxQ7ACuiIEQxC1QAPQnUBAAHpDUF8S1xEJQUDbAO8Ts3jV1DU3zzfwgA)

**Comment by retyui** [comment]
Experimenting I found a strange pattern:

- If the function returns the type `$ObjMap<T, F>`, we [do not have  "case problem"](https://flow.org/try/#0C4TwDgpgBAKgFhAttAvFA3gKClAxgewBt8AnALgygENdgBLANwgoGdgS6A7AcygF8ANJj4BuTJlCQoAZVCEIAHgAKJfGBYCoAYUJUWLCCwB8UNFhwBtHXoMsAuhQAk0uFUgL0fEwB8oAChU1FlMTZ1d3TyMASiFRcXEAEwhcXRJoBioSKEQqAGsIWRB5FgpzKGVVdU1ZQgpC+QqgzTYOHiMjP2wcPCpCQgAjGlyKP3gkCCiQmWBCLqinAHl+gCsAWTcFGs0-SZQTFq5uIyEcRqrp2umixUDzg7aOtmuSi-moRyW1ja3-Xf32Q7HYRiTA5fL1Qx+dBQVT4YClPj8KIgsEFOSQ4AIZBTMp+THjAB0BGIJAJNHoTFYAJ4yPEODxWIgRKIpDJtEYzCgnAAroh+hASMioAB6YVQCAAD0gtHFJFUJE0uAQuFy1E4IDpMIgwG5JE4lFh8IwiLifFpQA).

- But when a function returns another function witch return `$ObjMap<T, F>` (as in the example below) we have got an error: ` Could not decide which case to select, need type for "theme"`


[Try flow.js](https://flow.org/try/#0C4TwDgpgBAKgFhAttAvFA3gKClAxgewBt8AnALgygENdgBLANwgoGdgS6A7AcygF8ANJj4BuTJlCQoAZVCEIAHgAKJfGBYCoAYUJUWLCCwB8UNFhwBtHXoMsAuhQAk0uFUgL0fEwB8oAChU1FlMTZ1d3TyMASiFRcUloWRB5AAl8fABrADFOBQB9QPVNWUITND8wVXUAfgoCqpYokKhHAHkAIwArAFk3BRLNPyaUEzYOHiMxTAATCFxdEmgGKhIoRCoMiCT5FgpzKGUG4uBCCm3FQo0oMa5uIyM-bBw8KkJCdpoMij94JAhhkwlJ5RM5yCBpTI5Q5BY6lIQ4aFFGQnUHJC5Ha7sW73PxsNG7ZGEEHItEQ7K5S6woyxKbrTbnFh+dBQVT4YB7Pj8KK0jZbMGM4AIZDNfZ+QV-AB0BGIJAlNHoTFYWJ43PEODFQogUqIpDltEYzCgnAAroh2hASNyoAB6a1QCAAD0gtHtJFUJE0uAQuAy1E4IDVLIgwGNJE4lFZ7IwnLifFVQA)

```js
type Theme = {
  color: { active: string },
};

type Style<Props, Classes> = {
  [Classes]: $Shape<{}> | (Props => $Shape<{}>),
};

type StyleHookFn<_Props, Stl> = (props?: _Props) => $ObjMap<Stl, () => string>;

declare var makeStyles: {
  <Props, Stl: Style<Props, string>>(
    callback: (Theme) => Stl
  ): StyleHookFn<Props, Stl>,
  <Props, Stl: Style<Props, string>>(styles: Stl): StyleHookFn<Props, Stl>,
};

makeStyles({ root: {} });

makeStyles(theme => { //  Erro: Could not decide which case to select, need type for `theme`
  (theme.color.active: string);

  (theme.color.active: number); // expect error, check any

  return { root: {} };
});
```

**Comment by chasestarr** [comment]
it's because `Stl` and `() => Stl` are considered equivalent

I made [these changes](https://flow.org/try/#0C4TwDgpgBAKgFhAttAvFA3gKClAxgewBt8AnALgygENdgBLANwgoGdgS6A7AcygF8ANJj4BuTJlCQoAZVCEIAHgAKJfGBYCoAYUJUWLCCwB8UNABJpcKpAVYcAbR16DLALoV0fKAB8oAChU1FlMTTwBKIT4jMQlwaFkQeQAJfHwAawAxTgUAfUD1TVlCEzQ-MFV1AH4KPIqWMJCoMwB5ACMAKwBZawUizT8GlBM2Dh5o8QATCFxdEmgGKhIoRCo0iAT5FgplOsLgQgoNxXyNKBGubiMjPyKfWARkRqLBkyOU9KydoL3imJW1o4sPzoKCqfDADxePhhP6rdZyQx+YAPVChbD+ZFICAAOgIxBI2Jo9CYrHYFxh4hwSJRuKIpEJtEYzCgnAArohWhASDCoAB6XlQCAAD0gtEFJFUJE0uAQuDS1E4IEpoIgwFZJE4lDBEIwULE0LEQA) to make your example pass. Most notably the `$Shape` around the result of `Style<Props, Classes>`

See this issue and related bug reports to better understand what's happening: https://github.com/facebook/flow/issues/106
