### ISSUE TITLE
Flow-remove-types inside (alpine node 8) docker doesn't remove %checks.

### ISSUE THREAD

**Issue by pulli23** [facebook/flow#7833]
Flow version:

0.102.0-rc
flow-remove-types version:
2.101.0

## Expected behavior
When a function contains the identifier `%checks` flow-remove-types should remove that identifier when processing the function/file.

## Actual behavior

This actually works *outside* docker environments, where flow-remove-types works as expected. However inside a (node 8-alpine linux) docker flow remove types removes everything. Except the `%checks` pragma.

* Link to Try-Flow or Github repo:

https://github.com/pulli23/error-flow-remove-types-docker

Simple docker file, build the docker, then run it and inside the docker run `flow-remove-types test.js`

**Comment by motiz88** [comment]
Which version of `flow-remove-types` are you using outside the Docker environments? AFAICT this is a regression in v2, fixing now.

**Comment by pulli23** [comment]
> Which version of `flow-remove-types` are you using outside the Docker environments? AFAICT this is a regression in v2, fixing now.

Updated with information (refreshing the page while writing the post removed it). - I indeed use 2.101.0.
