### ISSUE TITLE
Type guard (%checks) doesn't refine any type

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#7834]
Flow version: 0.101.0

## Expected behavior

I would expect an `any` type to be refined to the checked type when guarded by a `%checks` call.

## Actual behavior

The `any` type is preserved.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgM4AWYAvGAN5ikLEC2AXGBgE4CuBAvgG5MuAgCFinACbU6YWFnZdeYQeijcAdgGMMxOBrBkSFABT4M7Y5QA+YcVICU7AEZw4MPAEMDAUi3k8LQBrUjpUMAiwTjwMbk4DcwA6RhYwAEIqGk1JPChiDTxJIT50LX1SDDBzdm8sGXoUtg4efiFiKDATIzJyMxiHBzCwAEgk+QEwVD4gA

**Comment by goodmind** [comment]
it works like this tho
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiAlgM4AWYAvGAN4A+YpCxAtgFxgYBOArgfQC+Abky4CAIWLcAJtTqNYWTj35gho1FF4A7AMYZicHWDIkKACnwZOAQx1YAlJwBGcODDz2wAUj3k8PQBrUjpUMDBuPAxebhNrADpmNlRBdD1jUgwwa05zSkYpWXlaJhYOLj4CEVRiKDALMzJyK2jHRzCwAEhE5NZhMHCInOiEpVFBIA

**Comment by FezVrasta** [comment]
@goodmind that's not the same thing tho, in your example the `pet` variable has the type assigned, and it's the type guard which allows `any`.

**Comment by SamChou19815** [comment]
This is due to limitation of refinement system. We have to have a literal tag for disjoint union.
