### ISSUE TITLE
Flow issue "Please upgrade flow to version >=0.75."

### ISSUE THREAD

**Issue by loth0** [facebook/flow#7835]
Flow version:
0.102.0-rc

Visual Studio Code
Extension: Flow Language Support

flow can't be started with the latest flow version due to version number passing 0.100. I get these error messages:

Output:
```

[Error - 22:37:38 - FoodShare\FoodShare\.flowconfig] Error loading flow using option 'useNPMPackagedFlow'
Pkg flow-bin not found in e:\Git\FoodShare\FoodShare, e:\Git\FoodShare
[Info  - 22:37:38 - FoodShare\FoodShare\.flowconfig] Found flow using option `pathToFlow`
[Info  - 22:37:39 - FoodShare\FoodShare\.flowconfig] Using flow 'C:\Users\Johan\AppData\Roaming\npm\flow.cmd' (v0.102.0-rc)
[Error - 22:37:39 - FoodShare\FoodShare\.flowconfig] Failed to start flow
Error: Flow version 0.102.0-rc doesn't support 'flow lsp'. Please upgrade flow to version >=0.75.
```

**Comment by goodmind** [comment]
@mroch

**Comment by telaoumatenyanis** [comment]
This is because of how semver handles the 'rc' in the version number: 

`semver.satisfies("0.102.0-rc", ">=0.75") // false`
`semver.satisfies("0.102.0", ">=0.75") // true`

https://github.com/flowtype/flow-for-vscode/blob/89f7115948d8c2db388667de43ec40046ecb22ad/lib/flowLSP/utils/assertFlowSupportsLSP.js#L7

**Comment by Mayank1791989** [comment]
@telaoumatenyanis Please close this issue.

**Comment by telaoumatenyanis** [comment]
@Mayank1791989 Sorry, this is not my issue and therefore have no way to close it 😅

**Comment by Mayank1791989** [comment]
Oh sorry :)

**Comment by 29er** [comment]
still an issue for me

**Comment by istomyang** [comment]
Turn off use LSP
![image](https://user-images.githubusercontent.com/67993732/87213716-6c9dad80-c359-11ea-9d4d-9bf145f77989.png)

**Comment by Mayank1791989** [comment]
@istomyang Which version of flow you are using?

**Comment by istomyang** [comment]
@Mayank1791989 Must under 0.75 version, but I know the latest version is 0.129.0. 
Because I am now reading a vuejs codes, it's not in development.

**Comment by Mayank1791989** [comment]
@istomyang Are you seeing the message even after turning off useLSP?

**Comment by istomyang** [comment]
@Mayank1791989  
No. Message above says she can't support flowlsp, and I have no lsp server, so I turn it off and no error shows.

**Comment by liyachun01** [comment]
For people who just want flow to work, and if is using Flow Language Support, read the `[readme](https://github.com/flowtype/flow-for-vscode#setup)`!
![image](https://user-images.githubusercontent.com/7907204/98834825-9d623080-247a-11eb-9317-a0ea65b9721c.png)
`Make sure you are able to run the flow command from the command line (or see Configuration to customize the command or use NPM packaged flow).`

**Comment by liyachun01** [comment]
For people who just want flow to work, and if is using Flow Language Support, read the [readme](https://github.com/flowtype/flow-for-vscode#setup).

![image](https://user-images.githubusercontent.com/7907204/98835417-5b85ba00-247b-11eb-90a0-c430d522169b.png)

> Make sure you are able to run the flow command from the command line (or see Configuration to customize the command or use NPM packaged flow).

**Comment by liyachun01** [comment]
> For people who just want flow to work, and if is using Flow Language Support, read the [readme](https://github.com/flowtype/flow-for-vscode#setup).
> 
> ![image](https://user-images.githubusercontent.com/7907204/98835417-5b85ba00-247b-11eb-90a0-c430d522169b.png)
> 
> > Make sure you are able to run the flow command from the command line (or see Configuration to customize the command or use NPM packaged flow).

no need for `"flow.useLSP": false`

**Comment by lectricas** [comment]
> Turn off use LSP ![image](https://user-images.githubusercontent.com/67993732/87213716-6c9dad80-c359-11ea-9d4d-9bf145f77989.png)

can you please elaborate where I should turn off this setting?
