### ISSUE TITLE
React stateless component with ES6 default props fails

### ISSUE THREAD

**Issue by honzabrecka** [facebook/flow#7838]
```js
// @flow

import React from 'react';

type Props = {
  loading?: boolean | { delay: number },
}

const Button = ({ loading = false }: Props) => <span>Foo</span>;

export default Button;
```

Flow version: 0.101.0

## Expected behavior

Compiles without any error

## Actual behavior

Throws:

```
const Button = ({ loading = false }: Props) => <span>Foo</span>;
                     ^ object type [1] is incompatible with boolean [2].
```

* Link to Try-Flow or Github repo:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AEoCmAhgMb6TaxqgDk2pFdA3MrgJ4ZGgAK1GAM6gAvKADeiUKDgkAJigB2AcwD8ALlAAjWLGilFoAD4TQcotBIdNigK5otRbKAC+AGkQvkZWIsH4AIVtcXF9RUAAKcRlYeSVlcMgSaEEeF01+WCEASlEAPlAAHkEMEkU8gDFdQuASsry2RCIADyw8MyIk22hA4NDFNiA

**Comment by jbrown215** [comment]
This is a known issue. We are working on a fix, but it has been more difficult than we anticipated.

**Comment by jbrown215** [comment]
I spoke with @samwgoldman yesterday, who is working on the fix, and it seems like he has made some good progress on it!

**Comment by SamChou19815** [comment]
This now works.
