### ISSUE TITLE
The "latest" npm tag points to a pre-release

### ISSUE THREAD

**Issue by thecotne** [facebook/flow#7840]
>```
>$ npm dist-tags ls flow-bin
>latest: 0.102.0-rc
>```
>Is this intended? I would have expected latest: 0.101.0
>
> https://github.com/flowtype/flow-bin/issues/163

**Comment by jbrown215** [comment]
cc @mroch

**Comment by mroch** [comment]
Thanks for the report. I will update our process to use `--tag next` when publishing prereleases to npm.

**Comment by mroch** [comment]
I’ll add, though, that it’s probably a bad idea to use flow-bin without a version constraint or with the latest tag. Every release usually contains breaking changes so you probably want to be intentional about upgrading.

**Comment by jbrown215** [comment]
This should be fixed since we released 0.101.1

I'll let Marshall close this when he lands his changes to the infra to prevent this from happening in the future.
