### ISSUE TITLE
Flow type does not accept the defaultProps use react lazy

### ISSUE THREAD

**Issue by wiloke1** [facebook/flow#7841]
#### Can u help me
https://stackoverflow.com/questions/56073501/flow-type-does-not-accept-the-defaultprops-use-react-lazy

#### 1. defaultProps in Post Component:
```js
static defaultProps = {
  featureImage: "",
  featureRatio: "16x9"
}
```
#### 2. use component with React lazy
```js
const PostLazy = lazy<PostProps>(
  (): any => import("../components/Post")
);

<PostLazy
  featureImage={item.featureImage}
/>
```
#### 3. and I received the Flow error
```
Cannot create `PostLazy` element because property `featureRatio` is missing
in  props [1] but exists in  `PostProps` [2].
```
#### It works well when I use it in the usual way
```js
import Post from "../components/Post";
```

**Comment by jbrown215** [comment]
You should use `lazy<React.Config<Props, DefaultProps>>` to keep default props optional. You'll also need to make a DefaultProps type alias for the class.
