### ISSUE TITLE
need full coverage for node.js

### ISSUE THREAD

**Issue by salisbury-espinosa** [facebook/flow#7844]
Flow version: 0.92.1

error: 
```js
property `TextEncoder` is missing in module `util` (see https://github.com/facebook/flow/blob/v0.92.1/lib/node.js#L1854). (flowtype-errors/show-errors)
```
https://github.com/facebook/flow/blob/0.92.1/lib/node.js#L1920

in module "util" missing TextEncoder  ( https://nodejs.org/api/util.html#util_class_util_textencoder )

**Comment by goodmind** [comment]
@salisbury-espinosa would you contribute?

**Comment by goodmind** [comment]
This actually was added in later versions

**Comment by goodmind** [comment]
https://github.com/facebook/flow/pull/7713
