### ISSUE TITLE
React.ChildrenArray<React.Element<typeof Child>> doesn't report errors

### ISSUE THREAD

**Issue by dmnd** [facebook/flow#7845]
## Repro steps
Flow version: 101.1

```js
import * as React from "react";

function Child() {
  return null;
}

type Props = {|
  children: React.ChildrenArray<React.Element<typeof Child>>,
|};

function Parent({children}: Props) {
  return children;
}

const jsx = <Parent><div /></Parent>;
```

[Link to Try Flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcARFDvmQNwBQdBArgHb7AQtwDCAFsABsAJgAoAlHADedOHEowmULiyYCB9AL4MYATzBY4ABWJh0AXikAfGXFz9hlFgC5MVGADo+goY4CCUKGQdAB5sPA8AUQEsECwWGGDdfQgCHnshAD4MgBo6Sw16RlZ2TiNkRxgRSTtvRw0XYwhTCWlZeUUuGoc4zQZcTlR4ACtUAA84C2DDcriYDOChYAA3OAB6edXpioyaIA)

## Expected behavior
Expect to see a type error around the children being passed to `<Parent />`

## Actual behavior
No error.

In fact, it looks like Flow fails, because there's an uncaught error in a promise reported in the console.

I noticed this problem in my app, but instead of crashing, Flow just misses type errors. I used Try Flow to construct a minimal example of the error but the code seems to crash Try Flow. Interestingly, the minimal example of crashing Try Flow correctly reports error in my app.

**Comment by goodmind** [comment]
@jbrown215 this looks the same as we discussed in Discord
