### ISSUE TITLE
Duplicated tests for `React.memo` 

### ISSUE THREAD

**Issue by wgao19** [facebook/flow#7848]
Flow version: 0.102

## Actual behavior

The tests in [this file](https://github.com/facebook/flow/blob/master/tests/react_16_6/memo.js) are duplicated. It looks like the second chunk is intended for `MemoComponentWithEqual`.

```jsx
const MemoComponent = React.memo(Component);

const _a = <MemoComponent foo={3} />;
const _b = <MemoComponent />; // Error missing foo
const _c = <MemoComponent foo={3} bar={3} />; // Error extra bar
const _d = <MemoComponent foo="string" />; // Error wrong type for foo

const MemoComponentWithEqual = React.memo(Component, (props1, props2) => props1 === props2);

const _e = <MemoComponent foo={3} />;
const _f = <MemoComponent />; // Error missing foo
const _g = <MemoComponent foo={3} bar={3} />; // Error extra bar
const _h = <MemoComponent foo="string" />; // Error wrong type for foo
```

Only the tests look off, there is no issue about typing.

**Comment by jbrown215** [comment]
Good catch!

**Comment by wgao19** [comment]
I'd like to give this a try :)

I've updated the components as well as the test exp files accordingly, and have managed to make the current test suite pass. I'm wondering, how should I test the with equal function?

**Comment by jbrown215** [comment]
Sorry, I must have missed this notification. Thanks for cleaning it up! The current tests seem fine to test it-- you can just replace _e -> _h with `MemoComponentWithEqual`. The idea is that providing the equality function shouldn't break type checking.

**Comment by jbrown215** [comment]
Fat fingered that, my b

**Comment by wgao19** [comment]
Hey @jbrown215 I've pulled up the branch but noticed that there are some failed tests. They don't seem to be related with these changes though?

**Comment by jbrown215** [comment]
Which test was failing? CI looks like it's passing on master right now.

**Comment by wgao19** [comment]
I realize that my tests are run on my earlier build of flow. But when I tried to rebuild flow, I ran into this error
```
File "src/server/protocol/socketHandshake.ml", line 1:
Error: The files src/stubs/flowEventLogger.cmi
       and src/monitor/serverStatus.cmi make inconsistent assumptions
       over interface FlowEventLogger
Command exited with code 2.
Compilation unsuccessful after building 89 targets (88 cached) in 00:00:02.
make: *** [build-flow] Error 10
```

So I tried to go through the installation steps again and I got a parse error from opam
```
[ERROR] File "/Users/wgao19/.opam/4.05.0/packages.dev/flowtype/opam", line 44, character 0-1: parse error.
[WARNING] Errors in opam file from flowtype source, ignored (fix with 'opam pin edit')
```

The .opam/4.05.0/packages.dev/flowtype/opam file looks like this

<img width="671" alt="Screenshot 2019-07-10 at 2 58 39 AM" src="https://user-images.githubusercontent.com/2055384/60915534-a3f8fa80-a2be-11e9-808c-e7837f2ebf12.png">


Sorry I'm really very inexperienced with this..

**Comment by goodmind** [comment]
Try `make clean`

**Comment by wgao19** [comment]
@goodmind thanks for the pointer, rebased and rebuilt and the test is passing now!

**Comment by goodmind** [comment]
@wgao19 is this fixed?

**Comment by wgao19** [comment]
Hi @goodmind yes it is fixed and I believe the PR has landed internally. Thanks again!
