### ISSUE TITLE
Using array-typed object maps as typed array

### ISSUE THREAD

**Issue by goldmont** [facebook/flow#7850]
```javascript
type User = {
    id: number,
    name: string
}

export default class Test {

    users: User[] = {
        User1: {
            id: 1,
            name: 'x'
        },
        User2: {
            id: 2,
            name: 'y'
        },
        User3: {
            id: 3,
            name: 'z'
        },
        [...]
    };

    constructor() {
        this.printUsers(this.users);
    }

    printUsers(data: User[]) {
        for (let key in data) {
            console.log(data[key].id); // WORKS
            console.log(data[key].name); // WORKS TOO
        }
    }

}
```

**Somewhere in your code**
```javascript
const x = new Test();
```

Why I can declare an **object** as `User[]` array-type and keep the code working? It's maybe due to [**Structural Typing**](https://flow.org/en/docs/lang/nominal-structural/) or it is a Flow syntax-checker bug? WebStorm is suggesting me `User` fields when I try to access to `data[key]` object. I cannot find any documentation about that, maybe it's an advanced less-known usage. Thanks for your efforts.

**Comment by goodmind** [comment]
https://flow.org/try/#0C4TwDgpgBAqgzhATlAvFA3gKCjqBLAEwC4oA7AVwFsAjJAGm11IENKIS5hE9SBzTAL6ZMEAB5gA9omBQCEAGbNyAGxkBjZczhwoAFQicMw3FHIJEcEvCQBtALqojJk9cQBGElmff8xKG4YfZxY2EgByUTDGbwFAn1cAJk9ooN8SBLjUslZ2KDCQKKDYlJdzAGZkrJxCEjLM1JDcsIAvQp9ikwEAbmNcNQlSTkRyNWApAAoASicfYAALPDgAOjBuUmBXOHH5xaWzJDhJns7enFWeDfMtgmZgZitze2mvH3kpKHHlCBkAawgQfCkWS3ZjPEo+fqDCRfJbKCS8cY3O42P4gOxLQhHKAAemxUAA6gB5ABKAGkAMrg7yQuDQiCw+GIkEo-7oxpY3EEkkUvSEwlUqBCE6CIA
