### ISSUE TITLE
Flow's interfaces can extend classes

### ISSUE THREAD

**Issue by popham** [facebook/flow#7855]
Flow version: v0.102.0

## Expected behavior
Flow rejects `interface I extends X { /* ... */ }` where X is a class.

## Actual behavior
Flow accepts `interface I extends X { /* ... */ }` where X is a class.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsADTAG8BfdASwDsAXAUwCcpsN6wBJMegDweoAmBYiVRgw1AFwSArgFsARkwDcqCqigzqGWpTjVufeoIAUASmkBhHPgA8HAHykxYRvVozGBrHgK9+QkTO4uJSsopMYAC8YACsquIU6ib+xgLmVja49g5mqilGphZg1r62hLn51PRIBQHmZhlEeagm1bWpRY3FHC1AA

I recently discovered this and consider it a feature that spares me from using `I & X` and `Class<I> & Class<X>` annotations, but I wanted to verify that it's a feature before refactoring a bunch of code. None of the `tests/interface/*` files use the pattern.

**Comment by popham** [comment]
I recall a comment in the source about migrating interface multiple inheritance away from the intersection operator. I anticipate that maintaining support for this bug/feature would complicate that process.

**Comment by SamChou19815** [comment]
I don't see a problem with that, since it's all type level stuff, and we can interpret the class to be interface like when you are extending it.
