### ISSUE TITLE
Object.keys return value treated different than other functions returning Array<string>

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#7857]
Flow version: 0.102.0

## Expected behavior

Flow should treat the return type of `Object.keys` the same way as other functions returning `Array<string>`.  The return type for `Object.keys` is `Array<string>` as defined by https://github.com/facebook/flow/blob/master/lib/core.js#L71.

## Actual behavior

Currently flow allows pushing non-string elements to the arrays return by `Object.keys`, but does not allow pushing of non-string to arrays returned by other functions.

[Example](https://flow.org/try/#0PTAEAEDMBsHsHcBQBjWA7AzgF1JWtQBeUACgEoAuUAQQCdaBDATwB5taBLNAcwD4j+AbQC6AbkQp02UA3pFc+cuNm0AdAAcArhgAWJAEQAjBgC99ZUaBChYAa2aIVG7XsgNoGAKYWrYT-VhaGQxQTwAPdU9kLE8AEwlUTBxYQwAreQBvRFAchVgqI1l9ABpEAF9xSSTQW08mEOIAeTSorFVa+pIU1ItEDoxnXQNjMx9rOwd+wdd3LzGweB18dQxi0CwdDhDdWE1oWNBDTxk0UICgw00cLbQAcixEIA)

If we want the return value of `Object.keys` to be treated differently it should be typed differently.

**Comment by goodmind** [comment]
Related #6927

**Comment by kevinbarabash** [comment]
I'm going close this as a dupe of that ticket.  Thanks for linking to that.

**Comment by goodmind** [comment]
Duplicate of #6927
