### ISSUE TITLE
Inexact open type not failing as a function

### ISSUE THREAD

**Issue by SergioMorchon** [facebook/flow#7858]
Flow version: 0.101.0

Given the following code:
```javascript
var o1: {
  foo: string,
} = () => {}; // Error - OK

var o2: {
  foo: string,
  [key: string]: any,
} = () => {}; // NO Error - shouldn't it error here too?
```

## Expected behavior
* To have an error in both `o1` and `o2` examples.

## Actual behavior
* Everything passes.

* Link to Try-Flow or Github repo: https://flow.org/try/#0G4QwTgBA9gjAXBA3gKAhAZlKCDOAXMASwDsBzAGmQF8IBeCACgEo6A+JKgbggHoeIAomDBRIAWggB5ANLJkoSFABMCFGkzYI+ImUpoA2gGsApgE9cBEqQC6CEMVOUa9Zmw7c+EAHKTBw0RASOAAWUACuADYAJsQA5HgQhAnG-pDBKcYQeFgA-EA

## Workaround
Change the `[key: string]: any` by `...`:
```javascript
var o3: {
  foo: string,
  ...
} = () => {};
```

**Comment by atabel** [comment]
I works fine in flow 0.98.1 and bellow

**Comment by SamChou19815** [comment]
Now it both errors.
