### ISSUE TITLE
Destructuring an object as an array should be an error

### ISSUE THREAD

**Issue by SergioMorchon** [facebook/flow#7859]
Flow version: 0.101.0

Having the following:
```javascript
const [w, a, t] = {p: ''};
```

## Expected behavior

To fail. Example with TS: https://www.typescriptlang.org/play/#code/MYewdgzgLgBA2gdwDQwIYqgXRgXhgbwAcAuGAcjIF8BuIA

## Actual behavior

No errors
* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBA2gdwDQwIYqgXRgXhgbwAcAuGAcjIF8BuIA

**Comment by thecotne** [comment]
as a workaround you one can explicitly disable indexer on object type like so

```js
declare var obj: {|
  -[mixed]: empty,
  +p: 'string' 
|}

const [w, a, t] = obj // Error: an index signature declaring the expected key / value type is not readable.
```

but you can't be doing this for all object ...
