### ISSUE TITLE
Type not widened by assignment in switch statements

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#786]
```javascript
var a = "";
var b = "";
declare var x: mixed;
switch (x) {
  case "foo":
    a = 0;
  default:
    b = 0;
}
(a : string); // no error, expected number ~> string
(b : string); // no error, expected number ~> string
```

@mroch Any idea what's going on in this example? I was trying to write a counter example for let/const, but wasn't able to trigger an expected error, leading me to this.

**Comment by samwgoldman** [comment]
Oh, after slightly more digging, it's the presence of the `default` case that prevents widening. If I remove the `default` case, then I see the expected error for `a`.

**Comment by mroch** [comment]
adding a `break` at the end of the first case also seems to make both `a` and `b` error, so this sounds like a problem with fallthrough merging.

**Comment by ngavalas** [comment]
I think I've found the bug (at least from my testing) and the fix is relatively simple; I can make a pull request for it tonight.  I was wondering if there was a good way to add test cases for this so it doesn't break in the future -- the test cases I wrote to debug this obviously are intended to fail once the bug is fixed; I basically just adapted the code from the original issue and it fails once the proper types are inferred.

**Comment by samwgoldman** [comment]
@ngavalas That's awesome! IMO, the best test cases are the ones that add expected error output, because then the test suite assets not only on the existence of the error, but also the quality of it—in particular the locations associated with the error. Obviously expected to fail is the best kind of expected to fail. :smiley:

**Comment by ngavalas** [comment]
Ah, I see now, the output gets diffed with the .exp file in the test directory.  I'll work on making sure this change doesn't break anything else then.

**Comment by ngavalas** [comment]
We can move the discussion to #792 if you'd like, but I have definitely identified the issue and *why* it happens, but I'm not sure what the most correct way to fix it is.  What I did certainly works and all of the test cases still pass (it produces the correct errors from number->string at the annotation, not at the a=0 assignment site), so I do believe it's correct, but we could also go down the route of havoc'ing the new changeset in all cases also -- I'm not sure of what the consequences of either choice are in the long run.
