### ISSUE TITLE
Flow_js.Not_expect_bound("Did not expect BoundT") with %checks

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7863]
Flow version: v0.102.0

<details>
<summary>The old reproduction case</summary>

```js
// @flow

declare class Zero {}
declare class Succ<+N> {
  +prev: N;
}

declare function succ<N>(N): Succ<N>;

type N1 = Succ<Zero>;
type N2 = Succ<N1>;
type N3 = Succ<N2>;
type N4 = Succ<N3>;
type N5 = Succ<N4>;
type N6 = Succ<N5>;
type N7 = Succ<N6>;
type N8 = Succ<N7>;
type N9 = Succ<N8>;

declare function add<A>(Zero, A): A;
declare function add<A, B>(
  a: Succ<A>,
  b: B
): Succ<$Call<Add, A, B>> %checks(succ(add(a.prev, b)));
type Add = typeof add;
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaFtgM7GgBaausoA3gL6qY76E6mgDKArhhgDwBqAHIA+OolChBAB3wA3AFyhhAbkSMmRVpG4A7DABcAlrD2hivAWIAUwgJTKeffmPWJDATxkFhARlAAXi4rfkpqUXUvHxUAJiCQl39Ij29fAGYE52tYlOjfABYs0OF0vLSVAFZipILymOEANhrrSvrfAHYW10b2lQAObuEOvuEATiH+lK0WAl0DEzNQbBQUfgBBURtw2AAaUHXHA-V0bTn9I1NzFbX1-YAhLcllp1DN3eeAI2V7xCPs-gAEgAwthoNANqt9ndQI9xABSDAAC0wAGtiDZLHwbDccQA6ORoeT7T72MlRCrrVYJfKwSDLVbqIA) (see the console)

</details>

---

```js
// @flow
declare function f<A>(string, A): A
declare function f<A>(a: A): $Call<F, 'c', A> %checks(null)
type F = typeof f
```

The value inside `%checks` can be anything, not just `null`.

## Expected behavior

No crashes.

## Actual behavior

On the code above Flow displays the following error:

```
(8054) merge_strict_job THROWS: [1] /Users/user/index.js: Flow_js.Not_expect_bound("Did not expect BoundT")
Raised at file "map.ml", line 130, characters 10-25
Called from file "hack/utils/collections/myMap.ml", line 15, characters 13-23
```

* Link to Try-Flow or Github repo: [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQATApgY2gQwE6tJAK4B26ALgJazEEA8AggHwAUAzmThcQOYA0o9AJQAuASgzY8BEuSo1IDFllFDRAEgDCWaNFoAxfgHJ0h-k1ABSdAAsMAa1bNihHYMRkAngAd8e0AF5QTx9YSAIgA) (see the console)

**Comment by panagosg7** [comment]
Looks like an issue with `%checks`. Taking a look.

**Comment by Bannerets** [comment]
I updated the code in the first post to be much more minimal.

**Comment by goodmind** [comment]
lol, is this really fix...
