### ISSUE TITLE
Invalid test for await parsing

### ISSUE THREAD

**Issue by nicolo-ribaudo** [facebook/flow#7865]
Flow version:
`master` (as of 2019-06-29)

## Actual behavior
https://github.com/facebook/flow/blob/42aef47837f510a9af6aefce1e770853c9709ee2/src/parser/test/flow/async_await/migrated_0007.js#L1

## Expected behavior
`await` is not a valid parameter name for async functions.
Chrome throws `Uncaught SyntaxError: Unexpected reserved word`

**Comment by mroch** [comment]
i have a fix for this, pending review internally
