### ISSUE TITLE
`export type { SomeClass } from "./someFile"` leaks class values for import

### ISSUE THREAD

**Issue by popham** [facebook/flow#7868]
Flow version: v0.102.0

## Expected behavior
`export type { SomeClass } from "./someFile"` provides only a `SomeClass` type to importers.

## Actual behavior
`export type { SomeClass } from "./someFile"` provides a `SomeClass` type *and value* to other files without any flow errors. This leads to runtime errors around `SomeClass` values that aren't available. In my use case and environment, this behavior smelled like a circular import.

* Link to Try-Flow or Github repo: https://github.com/popham/junk1.git

**Comment by mvitousek** [comment]
@nmote, does this look related to the work you were doing on type exports in April?

**Comment by nmote** [comment]
Yes, I set out to solve this issue but I ran into some problems while doing so. I don't remember exactly what they were.

**Comment by SamChou19815** [comment]
This is fixed in 0.230.0
