### ISSUE TITLE
Ternary logic using `typeof` not being taken into account when type checking.

### ISSUE THREAD

**Issue by glennflanagan** [facebook/flow#7872]
Flow version: 0.102.0

## Expected behavior
Flow should give no errors

## Actual behavior
A function which has a check to see if an argument type is `string` which then applies a ternary variable and passes down that variable to another function which only doesn't accept a string gives an error, even though the passed down variable can never be a string.

Apologies for the description but I'm not sure how to word this one accurately. I'm positive it's a bug as the passed down value can never be a string. Below is a code example and a link to the REPL.

Example
```js
function foo (bar: Array<any> | string) {
	const isString = typeof bar === 'string';
  	const passMe = isString ? undefined : bar;
 	const something = baz(passMe);
}

function baz(qux?: Array<any>) {
	return true;
}
``` 

Error: 
```
4:  	const something = baz(passMe);
                           ^ Cannot call `baz` with `passMe` bound to `qux` because string [1] is incompatible with array type [2].
References:
1: function foo (bar: Array<any> | string) {
                                   ^ [1]
7: function baz(qux?: Array<any>) {
                      ^ [2]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0GYVwdgxgLglg9mABMOdEAoBGBDATgLkQEFddsBPAHmzHID5EAfRAZylxjAHMBKRAbwBQASAgI2iGCwDK7Tl0QBeRFHIAHAKZxgiHLiWLlAcjYduRgNyDEiUeKiI12FiwCyGpZJlzuiAPyI4AAmGsCcGkGIhHpWtmJgEixwALYaUAAW8p44AF7oTi7uPFYAvoKCoJCwCLrYeQCOIAAefoQkZFQ09HxCwrhpILhI7CAapUA

**Comment by mvitousek** [comment]
Flow's type refinements aren't propagated through variables, so Flow won't connect the dots between `isString` being true and `passMe` being undefined or a string. I don't think we're likely to change this behavior soon (especially because mutability makes this harder--what if I mutated `bar` between the definition of `isString` and `passMe`?). You can do this instead and it will work: https://flow.org/try/#0GYVwdgxgLglg9mABMOdEAoBGBDATgLkQEFddsBPAHmzHID5EAfRAZylxjAHMBKRAbwBQiRAEgICNogAO2FiwCyAU0QBeRFHLSlcYIhy41q9QHI2HbicQB+ROAAmS4JyX3EhAwG5h4yVFZwALZKUAAWnFxq+tgAXuiy8so83gC+goKgkLAI0XEAjiAAHtaEJGRUNPR8QqK4ISC4SOwgSqmIQA

**Comment by glennflanagan** [comment]
@mvitousek thanks for the quick feedback the and workaround example. I'm unclear as to whether this is a bug or not so I'll leave it to you to close if you see fit.

**Comment by tjjfvi** [comment]
Something like this also works, and is shorter than repeating the refinement multiple places:
```ts
function X(val : string | number){
  let str = typeof val === "string" ? val : null;
  let num = typeof val === "number" ? val : null;
  str ? gimmeString(str) : null;
  num ? gimmeNumber(num) : null;
}

function gimmeNumber(x : number){}
function gimmeString(x : string){}
```

[Try-Flow Link](https://flow.org/try/#0FAMwrgdgxgLglgewgAgBoAoBuBDANsgLmQGcYAnOCAc2QB9kIwBbAIwFMyBKAb2GWVxsYJcsgC8yGAE8ADmwQhkOfGNXIARKQrV1yAPxK8hBmFy4A3HwFCTTcZNnzFy8WvWNWHXQZdFGZy34tfWQqOCYmNgBlckoqdC1OY38LKw8QsIi2ADlmdjJ0DyS-U1SAX2BQSFhEFEzI3M8CgA9kvI4eCvBoeCRQ8MiY7XjWoi04zuAgA)
