### ISSUE TITLE
Imported object type reports wrong error on intersection

### ISSUE THREAD

**Issue by borlaym** [facebook/flow#7873]
When you import an object type, and intersect it with another, and use an optional value in it as it were not optional, instead of reporting that undefined does not match type xyz, flow reports that the value is not a member of the imported type.

Flow version: 102.0

## Expected behavior
Report that undefined is not the correct type.

## Actual behavior
Reports that the property is missing in the imported object type. 

Try-Flow with expected behavior, when the type is not imported:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1LgJ4YqgBCAhtqALygDeiAkAG4XQCuKAXKAHYcAtgCMU2RAF8A3MiIlQAMVixaDZnwqCUAfl4BnXNgCWfAOaTk6LHlABjWHwOgTfMaoAUGbLAx7e9fk0eUANjM1AJAEpaAD41JmwUXA5sPlAvHz0AOg0tLL0OYVD3AAYAGlAAVkiZaUtMHHx7R3xYDlw3OncA3NIJXiUVADJyKmiaOMYEpJS0lzFuwK0ImskpIA

Repository with actual issue:
https://github.com/borlaym/flow-issue

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
