### ISSUE TITLE
$Compose/$ComposeReverse isn't a subtype of (...any) => any

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7874]
Flow version: v0.102.0

```js
// @flow
declare var c1: $Compose
;(c1: (...args: any) => any) // error
declare var c2: $ComposeReverse
;(c2: (...args: any) => any) // error
```

[try flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswA3IsHARgC4wASAYTgFsAHOAZy1QG4AKanX4A6MUQDmnOvgB2ATwCUYALwA+MHKWZcBYmQo4ATHSasO3AEpZSWQtz6CTYUeMJSZC5es1egA)

## Actual behavior

I see the weird `Cannot cast c1 to function type because function type [1] is incompatible with function type` errors.

## Expected behavior

`$Compose` behaves like a function, so I expect it to be a subtype of `(...args: any) => any`.

Also, If it will be fixed, it allows creation of `$TupleReduce` via `$TupleMap`:

<details>
<summary>Example</summary>

```js
// @flow

declare function apply<Args, R>(f: (...Args) => R, ...args: Args): R
type _Apply = typeof apply
type Apply<Fn, Args> = $Call<_Apply, Fn, Args>

declare function reduce<Fn, A, T>(Fn, A, T): $Call<
  Apply<
    $Compose,
    $TupleMap<T, Fn>,
  >
, A>
type _Reduce = typeof reduce

export type Reduce<Fn, A, T> = $Call<_Reduce, Fn, A, T>

type MergeAll<T> = Reduce<<X, V>(V) => ((X) => ({...$Exact<X>, ...$Exact<V>})), {}, T>

declare function mergeAll<A>(A): MergeAll<A>

const x = mergeAll([{a: 1}, {b: 1}, {c: 1}])

;(x: {a: 1, b: 1, c: 1})

;(x: {a: 1, b: 1, c: '1'}) // error
```

[try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmjYAO90AngDwCCuA5gM4A0oAEoA+ABSQAXKFEA6OZ14BKUAF5hQgXJl5eUhT0VTBics3oEA+u0YtVoU+diQ6N5ibMFrTNgDESA-XUVUAASAGFsaGhWK1cBPwDuHmFkdCw8AmIyKhpQfBQiDDRWBNB2AQAVMVLy0ArDUIio1kRQMtcWtrbw2ABbelgeND5WrpCKoiY0AFkGVgr4kmERtpSAlIdLQTQCortNpzydwrRkNAAPAdxyew8hY6KS-zLKoMbI6Itt3eHQGtfkJtQNM0Nw0OxmlU7N8TqxWAANAQANTESOUamkonh6PUogA3loQgBRc7YCgI5agQkksnkVgogC+ikUAjxDIBqEwOHwhFIFGotF6oK44Oa7DE7AaILBEOi4uQGBoPBu5zsQplUVEAG08dgpABGdmgPEAIwNRrxGHNAF1FMgANyic5SXUGgRm0D6gRWz1Mh1Ol16z3ut2gH0Acn14aZoBAoFBuFguCAA)

</details>

---

* Link to Try-Flow or Github repo: [link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcswA3IsHARgC4wASAYTgFsAHOAZy1QG4AKanX4A6MUQDmnOvgB2ATwCUYALwA+MHKWZcBYmQo4ATHSasO3AEpZSWQtz6CTYUeMJSZC5es1egA)

**Comment by SamChou19815** [comment]
Closing since support for these types is removed in 0.232
