### ISSUE TITLE
Flow reports wrong function call as error

### ISSUE THREAD

**Issue by gryn** [facebook/flow#7876]
Flow version: 0.97.0

## Expected behavior
Flow should report the error where it is, not where it is not. (In this case, the next function call)

## Actual behavior
Flow reports the error or the previous function call, instead of the next one, which contains the error.

Smallest reproducible (uses Immutable):
```
// @flow
import { Map, List, Record, type RecordOf, type RecordFactory } from 'immutable';
type User = { name: string, bike: string };
const UserRecord: RecordFactory<User> = Record<User>({ name: '', bike: '' });
const adam = UserRecord({ name: 'Adam', bike: 'Generic' });

// valid call
adam
   .setIn(['name'], 'John')
// invalid call
// ¡¡¡this call's error is promoted to the previous setIn() call!!!
  .setIn(['bike'], 3)
;

```
Error in last call is normally reported like this:
```
Cannot call adam.setIn because:
 • Either array literal [1] has an arity of 1 but tuple type [2] has an arity of 0 in
   the first argument.
 • Or array literal [1] has an arity of 1 but tuple type [3] has an arity of 2 in the
   first argument.
 • Or array literal [1] has an arity of 1 but tuple type [4] has an arity of 3 in the
   first argument.
 • Or array literal [1] has an arity of 1 but tuple type [5] has an arity of 4 in the
   first argument.
 • Or array literal [1] has an arity of 1 but tuple type [6] has an arity of 5 in the
   first argument.
```
But is instead reported on the first call like this:
```
Cannot call adam.setIn because property setIn is missing in User [1].
```

I have had this error appear at a far distance within the same file, but I was unable to reproduce that behavior with a small amount of code. (In the example above the calls have to be chained). But I have code that fails in my repo in a jest test file, which had a `merge()` call during setup, and several tests down had an invalid `setIn()` call. Flow reported the error on the `merge()` call at the top.

**Comment by SamChou19815** [comment]
This should be fixed by local type inference that much better localized the errors.
