### ISSUE TITLE
`[...new Map<K, V>().entries()]` is unsoundly typed `Array<(any | [K, V])>`

### ISSUE THREAD

**Issue by dmnd** [facebook/flow#7881]
Flow version: 0.102.0
## Context
```js
type K = string;
type V = string;

// The inferred type of `entries` here is `Array<(any | [K, V])>`,
// but I expect it be simply `Array<[K, V]>`

const entries = [...new Map<K, V>().entries()];
entries.filter(() => Math.random() > 0.5).reduce(x => x);

// If you remove the `filter(...)` you get the expected type.
// If you change `filter(...)` to `filter(Boolean)`, you get the expected type.
// If you remove the `reduce(...)` you get the expected type.
// But if you have both the `filter` and `reduce`, `any` is inferred 🤯
```
[Try Flow](https://flow.org/try/#0C4TwDgpgBA0lC8UDOwBOBLAdgcwNwChRIoA1BZNLPffAelqgBUALaLAMwlVQgBMoi0APbsoAAwiZKEJGKiseUdEnEBBbgEMQAHgAUGzCCgAfKAG0YAGlIBdAJQA+MZboMARgFdgUAJJQIAB6QAMbe6N5u0EjoALZgADZGYuqoWtoW1iQ2TjTBQpgo-lIYMuRmAHSVmBAA7lAAshpg2lakDrp25ZLSSB02BN0lSOXs6PHAXLodCA4NGsDM5amYvEIx07MADOUArJ08vB7BELoBM1ABdgSuvqIgQh5QPDFCAG7QC9Bio+OTleV2OT3R7YCDeT7+IIQUJ8ATgCDlG4+O4PKDBZgGUHiH4TVC6f6AgRCbFjXG6ABCQiE8QgBkB1mBUFB4NYkJCE34gkR9FuUEZzzeH1ZYgORxOBKBqOZAlZgXZsK5N3JXiUKMeGPeUDcQgWMq+OK4cgM-BFfDFznEBhAcmUSkwnG4sMAfBuAel2gA)

## Expected behavior
I expect the inferred type of the `entries` array to be `Array<[K, V]>`.

## Actual behavior
Instead, the inferred type of `entries` is `Array<(any | [K, V])>`.

**Comment by SamChou19815** [comment]
This is now inferred with the correct type without any.
