### ISSUE TITLE
Add error codes to error messages

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#7885]
## Proposal

Each error message should have a specific code as part of the error message, e.g. `FLOW1234` similar to how TypeScript includes `TS1234` in its error messages.

## Use case

This would make searching for help about certain error messages easier.

**Comment by goodmind** [comment]
Why would you search for error messages? Error message should be self-explanatory

**Comment by jsatk** [comment]
I think this would be a super nice addition.

**Comment by jeremywiebe** [comment]
@goodmind There's two big reasons that I can think of... 

* They make the error much more "googleable" (especially as the text of the error may change over time, but the number wouldn't)
* They make it easy to provide documentation about the error and how to resolve it (for example: https://github.com/koalaman/shellcheck/wiki/SC1090)

**Comment by goodmind** [comment]
@jeremywiebe that's what I mean by self-explanatory error messages shouldn't need their own documentation pages with 10 paragraphs

**Comment by goodmind** [comment]
@mroch do you think it's possible to make ppx that generates IDs from error message constructor names?

**Comment by halaei** [comment]
I wonder how every single `$FlowFixMe` line in react-native code has error code. As an example:
```js
    // $FlowFixMe[reassign-const]
    pattern = pattern.slice(1);
```

How do they know which error code should be suppressed when using `$FlowFixMe`? If the error codes are not in the message, where do they look for them?

So maybe this feature has more use than searching the error for help.

**Comment by mrtnzlml** [comment]
@halaei Flow tells you the error code when displaying an error so you can suppress it manually (see: https://flow.org/en/docs/errors/). You actually have to use the error code to suppress the errors nowadays. Alternatively, on larger codebases, these `$FlowFixMe[CODE]` comments are added manually via `update-suppressions` CLI command from Flow.

I think this issue should be closed because Flow already uses (and requires) error codes.

**Comment by gkz** [comment]
We have error codes! They are displayed at the end of the error message.
