### ISSUE TITLE
$ElementType doesn't work properly with union of objects

### ISSUE THREAD

**Issue by oonsamyi** [facebook/flow#7889]
Flow version: 0.102.0

## Expected behavior
`$ElementType` should work correctly with the nested union of objects:
```js
type A = { a: string }
type B = { b: number }
type C = { deep: A | B }

;(1: $ElementType<$ElementType<C, 'deep'>, 'b'>) // should be correct
```
Because the next example works correctly:
```
;(1: $ElementType<A | B, 'b'>) // correct
```
## Actual behavior
 Above example causes an error: `Cannot instantiate $ElementType because property b is missing in A [1].`

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgFCiRQBCCyUARpoQK4C2TEu5V40AMIMUAEwgQwmOAB86fCgG4AFAEZMAEgCiAGwgcIhYABUBAHll0ANFADkTWwD4AlFAD0bqAGMA9rlwQXsBKapq6+oYm5tp6BkamkGaCNrbikk4pDi7unlgAFj5sOqLM0L7+gcBAA

**Comment by lyleunderwood** [comment]
huh, interesting that [adding an intermediate type seems to work fine](https://flow.org/try/#0C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgFCiRQBCCyUARpoQK4C2TEu5V40AMIMUAEwgQwmOAB86ffjQAiEsAwAkAUQA2EDhELAAKgIA8ggDRQA5OMnWAfAG4KTgBQBGTFt37DJyFMVSStrJkcASigAemioAGMAe1xcCHjgCldPbx09A2MzHzz-M0sbOzBHUPCHKNjsAAtEtm1RZmgklLTgIA)

**Comment by goodmind** [comment]
Shouldn't $ElementType work like regular property access?
https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKBDAXFAzsAE4CWAdgOZooC+A3GqJFAEILLqYBGeZArgFsuEItXqNw0AMLtUGKABMIEMHjgpWYhmiUBjADZYi0AG5GoAMwD2VvFO3WrAOiUqnXOlAD0XqCKJWREA

**Comment by goodmind** [comment]
https://flow.org/try/#0C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgFCiRQBCCyUARpoQK4C2TEu5V40AMIMUAEwgQwmOAB86fCuIDGAG1S5oAN3VQAZpgAkAURUQOEQsAAqAgDyy6AGigByJi4B8AbigB6X1AA9gDWFLpeFIoQqupaOqKGJmYW1nbGpuaWNpC2gs4u4pKe+e7ekaJeQA

This works the same as property access, so it's not an issue

**Comment by oonsamyi** [comment]
@goodmind Thank you! You are right, I close the issue.

I think the next example has the right behavior:
https://flow.org/try/#0C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgFCiRQBCCyUARpoQK4C2TEu5V40AMIMUAEwgQwmOAB86fCuIDGAG1S5oAN3VQAZpgAkAURUQOEQsAAqAgDyy6AGigByJi4B8AbigB6X1AA9gDWFLpeFIoQqupaOqKGJmYW1nbGpuaWNpC2gs4u4pKe+e7eil5AA
