### ISSUE TITLE
Support textDocument/codeLens for type information request in LSP

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7890]
## Proposal

Support `textDocument/codeLens` request

- [`textDocument/codeLens`](https://microsoft.github.io/language-server-protocol/specification#textDocument_codeLens)
- [`codeLens/resolve`](https://microsoft.github.io/language-server-protocol/specification#codeLens_resolve)

## Use case

Support type annotations for top-level variables in codeLens like ReasonML and OCaml language servers

![image](https://user-images.githubusercontent.com/3275424/60743467-30d44900-9f8b-11e9-9bd3-731d47d3e5b0.png)

**Comment by goodmind** [comment]
- Worst case
![ezgif com-video-to-gif](https://user-images.githubusercontent.com/3275424/61012432-f78b4700-a397-11e9-8fd7-a21e338809ba.gif)
- Normal case
![image](https://user-images.githubusercontent.com/3275424/61012442-083bbd00-a398-11e9-8e09-71e1875ae4eb.png)

**Comment by vicapow** [comment]
For context for others, is was discussed that the output in most cases might be too verbose. We could consider adding this behind some sort of configuration Flag

**Comment by mroch** [comment]
we should talk through what specific code lenses we'll support. agree that the signature might be too verbose, or redundant. but there are other lenses like find-refs that seem like a good fit.

**Comment by mostafaeweda** [comment]
Using CodeLens for type inference or hints might be noisy or too verbose.

While that way might be useful for languages where annotations are optional (OCaml) to demonstrate value, when possible; in other languages with strong-typing (Java, C++) or encouraged-typing, like Flow here (or TypeScript's use of CodeLens in references), it'd be better to avoid the noise and save the editor-space for code.

* Java: https://github.com/redhat-developer/vscode-java/blob/master/package.json#L166
* cquery: https://github.com/cquery-project/vscode-cquery/blob/master/package.json#L901
* TypeScript: https://github.com/microsoft/vscode/blob/master/extensions/typescript-language-features/package.json#L102

**Comment by SamChou19815** [comment]
This will be too noisy. If one day we add it, it will be via inlay hint.
