### ISSUE TITLE
Losing refinement with string literal union

### ISSUE THREAD

**Issue by beaucollins** [facebook/flow#7892]
Flow version: all

## Expected behavior

When refining a type union of string literals the type of the refined variable should constrain to the refined values.

## Actual behavior

After a refinement of the type union of string literals, Flow allows any string literal to be assigned to the refined type.

__Note__ this only seems to happen when using a strict equals `===` comparison or a `case 'literal'` for refinement.

* Link to Try-Flow or Github repo: https://flow.org/try/#0FAFwngDgpgBA8hEBLA9gOxgXhgcnVHGAH1xAHcVCScQALAJygIG5g2AzAVzQGNl0YUAB4BDALYQANlAAUKRKjQAueAvQBKFQn4YA3sBgwk7GHLUZMl0hRzqY+w4cYhO9DDQZMcrQwF8DpvI6WubqPjA86ADOIDAARiIAJioy4NAoJkGKdtg4gLwbgJU73gEyCcmqOmEBzq4YZay+QA

**Comment by goodmind** [comment]
@beaucollins `typeof` is broken for this kind of things

**Comment by beaucollins** [comment]
> typeof is broken for this kind of things

Ok, the `typeof` was mostly an attempt to show that the refinement is gone. My IDE shows that the refinement of `thing` using `===` turns it into the type `string` after the refinement block.

It's probably a case of me not understanding refinement completely.

**Comment by goodmind** [comment]
@beaucollins non-strict comparison doesn't do refinements I think
