### ISSUE TITLE
Anonymous interface doesn't display anything

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7895]
Flow version: 0.102.0

```js
type Foo = interface {
  foo: number
};

```

## Expected behavior
```
interface Foo
```
or
```
type Foo = interface { foo: number }
```

## Actual behavior
```
(unknown)
```

This also makes any type that uses this interface display `(unknown)`
So this pretty much makes them unusable with IDE

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBLAdsCAnAZgQwGNoBvAKCilwQC4p0BXAWwCMcyBfIA

**Comment by goodmind** [comment]
@panagosg7 I guess this is fixed?

**Comment by panagosg7** [comment]
Yes, c7f7cb9c71d56fd34c999d68abecf62224f27fb2
