### ISSUE TITLE
Follow symlinks inside of `node_modules`

### ISSUE THREAD

**Issue by cpojer** [facebook/flow#790]
When using `npm link`, Flow doesn't follow symlinks for projects. Can we change Flow so it follows one level deep into `node_modules/<project>`?

**Comment by cpojer** [comment]
For now I'm using the workaround proposed in #644, but that is kind of messy without `<rootDir>` support.

**Comment by samwgoldman** [comment]
If you wanted to take a crack at this, you can find the relevant code [here](https://github.com/facebook/flow/blob/a373455f42e5c7062b3c6234241d2ed64014fda3/src/typing/module_js.ml#L248). Note that there is some logic to resolve symlinks already, but I'm not surprised there are missing cases.

**Comment by gabelevi** [comment]
It's a bit of a can of worms. @yiding took a crack at it with https://github.com/facebook/flow/commit/004a63e72e227e820d97fe552045bf43b8e5c411 but `find` has trouble with filesystem loops and will do different things depending on the implementation of `find` (see the internal discussion for that diff). https://github.com/facebook/flow/commit/564292f7802ce577804a5fca7f887888068f0c9f partially reverted that change, keeping some limited symlinking support for linking within a Flow root.

**Comment by samwgoldman** [comment]
Looks like symlink resolution is back in 0ca84434bd68bcee3368da0fdbbe49aa1250f275

**Comment by samwgoldman** [comment]
Wanted to check in here. Is this issue resolved? What are the steps to reproduce?
