### ISSUE TITLE
Object.assign will influence following statement

### ISSUE THREAD

**Issue by ckitterl** [facebook/flow#7905]
Flow version: 0.102.0

```
class ActionOperator {
  action:? any;

  dispatchInit(param: any = {}) {
          // return if action is null
          if (!this.action) {
              return;
          } 
  		  let force = false;
    
          /* if I invoke `createInitAction` here. It will be OK! */
      	  // this.action.createInitAction(force, param); // Works!
    
    
          Object.assign({}, {a: 1});
  
         // After the Object.assign() statement, it's not work
         this.action.createInitAction(force, param);  // Error!
   }
}
```
The code expected work but I get the following a flow error

```
19:          this.action.createInitAction(force, param);
                         ^ Cannot call `this.action.createInitAction` because property `createInitAction` is missing in null or undefined [1].
References:
2:   action:? any;
            ^ [1]
```
* [Link to Try-Flow](https://flow.org/try/#0MYGwhgzhAECCwBcCWB7AdgeQA4FMBOYCKe0A3gFDTRiKpoBcA-NWgJ4Dc5XVAJkhFkLAAFgEk0SBAApBBALb0WraAF4yAXwCUZSlT36A9Aeh4cCAK5400JADNqtdDZhpzIELv3670KQEIEYX4AOhpkdG0KL2i9UwsrThi9dWhdAEg0qhAzaFtiYBxVXLAQCBxEvU8YgwAqG3tRGzQANxQAa0KAA2BTQhxxSXhwtE7oYXwcYOhRBGgAdyR3aAAjQowAaT9oGoMqqkzoI2hAkLC6YJ6cPoGEIbopPLwCgBpoWTA5TQqqKr2vDGWACscIhQlAkABzNBSUjqV6kMCKACMWgqfz0R1gtgQ+GgEBQckK7zk0BQuAIw1ethAKDm0BpZQcwwA5DBCVAwBCcOiqCcIKFHGgLr0cTc7ugHvkcK9iV9POpyOogA)

**Comment by mroch** [comment]
this is a limitation of Flow's analysis. since objects are mutable, Flow doesn't know for sure that `Object.assign` does not have a reference to the `this` object and mutates `this.action`. so, function calls invalidate the `if (!this.action) return` refinement. the built-in `Object.assign` is very likely not reassigned, but all functions are treated this way.

see https://flow.org/en/docs/lang/refinements/#toc-refinement-invalidations

**Comment by ckitterl** [comment]
@mroch There is another problem which looks like the same problem. Could you help?
```
let passParams;
passParams = passParams || {}; 
passParams['hello']; // Works!!
['hello', 'world'].map(key => {return passParams[key]}) // Error!!
```
