### ISSUE TITLE
$Pred isn't considered in function overloading

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7909]
Flow version: v0.102.0

```js
declare function filter<T, P: $Pred<1>>(
  arr: $ReadOnlyArray<T>,
  predicate: P,
): $Refine<T, P, 1>[];
declare function filter<T>(
  arr: $ReadOnlyArray<T>,
  predicate: (value: T) => boolean,
): T[];

const bar = [1, 2, 3]

const b = filter(bar, (a): boolean %checks => a === 2)
const a = filter(bar, (a): boolean => true)
```

## Expected behavior

No errors

## Actual behavior

```
12: const b = filter(bar, (a): boolean %checks => a === 2)              
       ^ Could not decide which case to select, since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To fix add a type annotation to return [3].

References:
1: declare function filter<T, P: $Pred<1>>(   
^ [1]
5: declare function filter<T>(   
^ [2]
12: const b = filter(bar, (a): boolean %checks => a === 2)
                               ^ [3]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtVKwgxBgB4AVAGngAUAueAEhrmFIEYA+TgCgCh48WDAaMASiCjAA8qggBPAIIwYUeRU6UB8AA6ssYKMQY0tASlETEWVCArVT8LgG0AugG4+oSLAQp02HgERCQa-ILClpIyckoqahpagnogwAZGIAw8AG5QEMiZ8ORm8AC8nPAARjg4EJKo5gzkbp58YHgAzhhVsGXwzuzUAEzUAMyufG2d3ZV91iEwPJWw1DxQFlU1dVD4AKRgABbgANYdZRVQZaWl8ENmU6hdQnOExIvLMKvrDNW19efwDAwApmIA

**Comment by goodmind** [comment]
@panagosg7

**Comment by SamChou19815** [comment]
We don't plan to improve this type, and it will likely be deleted in the future (cc @panagosg7 ). Instead, we will release type guard soon.
