### ISSUE TITLE
integration with jest?

### ISSUE THREAD

**Issue by jonslenkooyala** [facebook/flow#791]
I annotated some JavaScript, and now the associated Jest tests fail to parse the original code. I am guessing it is due to the type annotations I added to function signatures. Is this a Flow issue? A Jest issue? Or, most likely, an issue with me not understanding how to get them working together (did I miss something simple like a silly head)? Thanks for help.
jest v0.5.2
flow 0.15.0
```
SyntaxError: /Users/xyzpdq/Dev/repos/x/y/z/pdq.js: Unexpected token :
```

**Comment by gabelevi** [comment]
So once you start writing The JavaScript Of The Future (ES2015, ES2016, Flow, etc) you need to transform your JavaScript with a tool like Babel or JSTransform before you run it. Babel has a pretty awesome setup page and it includes instructions for jest. Try it out!

https://babeljs.io/docs/setup/#jest

**Comment by jonslenkooyala** [comment]
Thanks, I will go learn up!
