### ISSUE TITLE
Types for async pipe (composition) does not catch obvious mistake

### ISSUE THREAD

**Issue by honzabrecka** [facebook/flow#7910]
Declaration:

```js
// @flow

type P<X> = X | Promise<X>

export type UnaryFn<A, B> = (value: A) => P<B>

export type UnaryFnP<A, B> = (value: A) => Promise<B>

declare type PipeP = <A, B, C>(ab: UnaryFn<A, B>, bc: UnaryFn<B, C>) => (value: A) => UnaryFnP<A, C>

```

Usage:

```js
// @flow

import { pipeP } from './index'

const a = (x: number): string => x + ''
const b = (x: string): number => parseInt(x)
const aP = (x: number) => Promise.resolve(x + '')
const bP = (x: string) => Promise.resolve(parseInt(x))

// this works fine
pipeP(a, b)(1)
pipeP(aP, bP)(1)
pipeP(aP, b)(1)
pipeP(a, bP)(1)

// should fail
pipeP(a, a)(1)
```

Flow version: 0.101.1

## Expected behavior

It should fail (on last line), because the second `a` in pipe is not compatible with returned type of the first `a`.

## Actual behavior

It compiles fine even though types are not compatible.

Actually it's resolved as `(alias) pipeP<number, number, string>(f1: (v: number) => number | Promise<number>, f2: (v: number) => string | Promise<string>): (v: number) => Promise<string> (+29 overloads)`, which is correct. But it seems like it does not perform second step - it does not check whether passed functions are compatible with this computed resolution.

**Comment by Bannerets** [comment]
Change of `P<B>` to `Promise<B> | B` fixes it, weird. See [try flow](https://flow.org/try/#0FAFwngDgpgBACgHgBoD4YF54CcD2BbASwGcpk0AfGJYYAelqgA8IcsQZxoYBVAOwEMsYAGK8EAQQA0MAEJpMACgBu-ADYBXKAC4Y4gJQY0iOcCYs2HSLD6CRYqbPkxlazTv2Hs+YqTkxKMjRmrOyc1gJCoogOfooqGtq6BuhGuIQkCCbAACZQAMaqgrAqWDAQBNBwOhLSMtIAwigK-ABGOjaR9rUo0i157RF2mQ0oyWguCe5jPINRNTCNwDAwwHk4vETs-BjOjDq86ngtUFh6OptYBLwA5p6MMADUMADkz6vrmzAtOwp7MBdXa5nGAHI4nTwQQQkACSvBAvz07w2WzgPz+oOOp08cDSPgAdFgoEQcKolFBfo8Xs9EWtkV9UYo-gCbtMcd4SASiSSyQpIVgYXCEYjlnRaBwABbEGAAd1YAGsiDAAGZXKDAcqVZq9PQKACMiI1UDgzTgvTgOv16oqRpN2r1Butxv4ZotiNF-3FOHUqmyyv4BFUVs1zpg-FdNCAA).

> Actually it's resolved as `(alias) [...]`

By the way, that type seems to be from TypeScript, not from Flow.

**Comment by honzabrecka** [comment]
Strange. I tried `B | Promise<B>` without success. `Promise<B> | B` works like charm, thanks!
