### ISSUE TITLE
Allow @jsx pragma to be set in .flowconfig

### ISSUE THREAD

**Issue by Hubro** [facebook/flow#7911]
I'm starting out a new project using flow and preact. The only way to make flow play nice with preact is to add `// @jsx h` to all my source files. It feels pretty silly to have to add the exact same flags to all my source files. It should be possible to set this globally in `.flowconfig`.

For example:

```
[options]
jsx.pragma=h
```

**Comment by goodmind** [comment]
Duplicate of #7010
