### ISSUE TITLE
Supports %checks modifier on class methods

### ISSUE THREAD

**Issue by telaoumatenyanis** [facebook/flow#7920]
## Proposal

Allow the use of the `%checks` modifier on class methods.

## Use case
A big example is the lodash `flow-typed` file. Function such as `isNil` are defined like this:

```js
declare class Lodash {
    isNil(value: any): boolean
}
```

New feature would allow the following:

```js
declare class Lodash {
    isNil(value: any): boolean %checks (value != null);
}
```

Right now, the use of this method does not allows flow to know that the checked value is not null:

```js
const test: ?React$Element<any> = window.document.getElementById('test')
if (!isNil(test)) {
   return ReactDOM.createPortal(test, this.containerEl) // Throw flow error about test being undefined
}
```

**Comment by goodmind** [comment]
https://github.com/facebook/flow/pull/7735

**Comment by telaoumatenyanis** [comment]
Nice! Sorry, I missed it while searching for existing issue.

**Comment by goodmind** [comment]
Not sure if `declare class` would work, only tested regular class

**Comment by goodmind** [comment]
@telaoumatenyanis added your lodash example to tests

**Comment by SamChou19815** [comment]
Closing this since we only plan to support this for type guard
