### ISSUE TITLE
$ReadOnlyArray is tainted with assignment of wrong type

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7921]
This issue was originally found in https://github.com/facebook/flow/pull/7620 PR

/cc @mvitousek

Flow version: 0.102.0

```js
declare function freeze<T>(a: Array<T>): $ReadOnlyArray<T>

const m = freeze([1])
m[0] = 'string' // should only error here

;(m[0]: number) // shouldn't error here, since it is read-only
```

## Expected behavior

Array still has type `$ReadOnlyArray<number>`

## Actual behavior

Array has type `$ReadOnlyArray<string | number>`

* Link to Try-Flow or Github repo: https://flow.org/try/#0CYUwxgNghgTiAEAzArgOzAFwJYHtVLhAC8QAeAFQD4AKKALngEEYYoBPCygSgYBIAlEFGAB5VBDbNWHKgChZYPAGcM8ALbwAvARDEQ1ANoBGALpdZagwAYTW+AHIVMLKgDm9+QG5qlmw1TIagBGIDDm8rJAA

**Comment by Bannerets** [comment]
In the example you can replace `freeze<T>(a: Array<T>): $ReadOnlyArray<T>` with `freeze<T>(a: $ReadOnlyArray<T>): $ReadOnlyArray<T>` and it won't change anything.

Also it is actually a more general issue, where `=` on read-only properties changes the type.

```js
const a0 = (['s']: $ReadOnlyArray<*>)
a0[0] = 2 // no errors below if you comment this line
;(a0[0]: string) // should not error
const a01 = (['s']: $ReadOnlyArray<*>)
a01[0] -= 2 // error
;(a01[0]: string) // ok

const a1 = ({ a: 's'}: { +a: * })
a0.a = 2 // error
;(a0.a: string) // should not error
const a11 = Object.freeze({ a: 's' })
a11.a = 2 // error
;(a11.a: string) // should not error
                 
class A2<+T> {
  +v: T
}
class A21<T> extends A2<T> {
  constructor(v: T): void {}
  v: T
}
const a21 = new A21('s')
const a2 = (a21: A2<*>)
a2.v = 33
;(a2.v: string) // should not error
```

[try flow](https://flow.org/try/#0FAYw9gdgzgLgBAQwAxwLxwBQG0DkUcC6AXHACQBKApggCYDyEANgJ4CCATuwswDwBUAPgCUwZFiQE0cAEzAA3BjESSsdgEsIAcyFwA9LrhQAFmACujGnAhh4lTmHahIsREgCMU7HkIkK1ekxsnNz8wqLu4pIAtOjSegZ27A7yihHKhjDqWjr6cGAA1sBO0PAIHugYAN6IJN4AviTVANQIJHxwdSLIAHQIUnG5ickKPa0ZWdrxhibmlta29o7gJYhu5XB0AEYAVpQgMN0AZuyUlABelFU1cN4dXWu9-VNDjiMPY6oak7nGZhZWNjgL2AcFBYPBENBoEYCCgUDgrGkPCaABUBHBKiC4E0AG4kFHAOrQ2HwxFuHhooEADxglAgNFJSMpmNBy1Upn2DgweLgKKEJBxYDUlkqRNBPIJRLZpWk6wglAA7gjZRhvCJpYg4hUELKSIjQl1pN0cVIAMymlI640qTJfHIGX6zAELJLsIA)

I guess the behaviour with found errors is not strictly defined and is not in Flow Team priority.

**Comment by lyleunderwood** [comment]
@Bannerets In your second example set you've got `a0` where i think you mean `a1`. :smiley:

**Comment by SamChou19815** [comment]
This behavior is now expected in the new type inference engine
