### ISSUE TITLE
Flow cannot differentiate between an imported type and an imported function of the same name when using a wildcard alias.

### ISSUE THREAD

**Issue by TomasBarry** [facebook/flow#7922]
Flow cannot differentiate between an imported type and an imported function of the same name when using a wildcard alias.

Given the following snippet:

```es6
// @flow

import * as React from 'react'

const X = (): React.Fragment => (
  <React.Fragment>
    <p>
      { 'Hello :)' }
    </p>
  </React.Fragment>
)

export default X
```

Flow version: 0.100.0

## Expected behavior

Flow should build successfully. I would expect Flow to differentiate between the `Fragment` type and the `Fragment` function.

## Actual behavior

Flow gives the following error:
```
const X = (): React.Fragment => (
                 ^ Cannot use function type as a type because function type is a value. To get the type of a value use `typeof`.
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQiCWBbADrATgF1AFSgCGAzqAEoCmxAxvpNrGqAOTY32vK2wB2pfAA1QAXlAAKAJQAuSp1wA6AGLZiAczRU++UQD5JiUKAA81OktUatOvUeOmMdhw4DebABJVocUDKmsoAC+9sYmwE724eb0Kmqa2rh2UshUAB5YeKAAJlSQxACu0MKIQA

**Comment by jcready** [comment]
The react libdef doesn't export a `Fragment` type. Only the function. https://github.com/facebook/flow/blob/ad608421aa5f6a7754037227d806999d17b12bf5/lib/react.js#L262

And the `Fragment` function returns a `React.Node`, not a `React.Fragment` so you would need to set the `X` return type as `React.Node`:

```js
// @flow

import * as React from 'react'

const X = (): React.Node => (
  <React.Fragment>
    <p>
      { 'Hello :)' }
    </p>
  </React.Fragment>
)

export default X
```

**Comment by TomasBarry** [comment]
Interesting, [SublimeLinter-flow](https://github.com/SublimeLinter/SublimeLinter-flow) seems to be perfectly fine with a `React.Fragment` as a return type.

We prefer not to return a `React.Node` as that can be `null` whereas we would rather be more explicit so we make use of `React.Element<'div'>` (for example) quite frequently as that is not nullable.

Is there a way, other than returning `typeof React.Fragment` to indicate that we are returning a fragment (and the return value cannot be `null`)? This becomes even more interesting when returning custom components.

**Comment by jcready** [comment]
> We prefer not to return a `React.Node` as that can be `null` whereas we would rather be more explicit so we make use of `React.Element<'div'>` (for example) quite frequently as that is not nullable.

But `React.Fragment` says it returns `React.Node`, there's nothing you can do to change that. You can explicitly cast it to `any` if you'd like.

> Is there a way, other than returning `typeof React.Fragment` to indicate that we are returning a fragment (and the return value cannot be `null`)?

Well, setting the return type of `X` to be `typeof React.Fragment` will cause an error because `typeof React.Fragment` is a function. You could set the return type to be `$Call<typeof React.Fragment, *>`, but that will just be the same as `React.Node`.
