### ISSUE TITLE
$ElementType in the upper position doesn't work well with object unions

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7931]
Flow version: v0.102.0

It works only the first time in a file in the upper position, when the property doesn't exist in some objects in the union:

```js
type A = { a: string }
type B = { b: number }

declare function f0(a: $ElementType<A, 'b'>): string
declare function f0(a: $ElementType<B, 'b'>): number
const a0: number = f0(3) // number (ok)
const b0: string = f0(3) // string (not ok)
const c0: string = f0('1') // string (not ok)

declare function f1(a: $ElementType<A | B, 'b'>): string
const a1 = f1('3') // error (ok)
const b1 = f1('3') // no errors (not ok)
const c1 = f1('3') // no errors (not ok)
const d1 = f1(3) // no errors

type T2 = $ElementType<A | B, 'b'>
const a2: T2 = 'a' // error (ok)
const b2: T2 = 'a' // no errors (not ok)

// ---

type T3 = $ElementType<A | B, 'b'>
declare var a3: T3
declare var b3: T3
;(a3: 'a') // error (ok)
;(a3: 'a') // error (ok)
;(b3: 'a') // error (ok)
;(b3: 'a') // error (ok)
```

* Link to Try-Flow or Github repo: [try flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgFCiRQBCCyUARpoQK4C2TEu5FFAEwgBjADapc0AGZtCw4PgD2hKFIAMACgxQAJAFFREDhELAAKuAgAeGABooAciYOAfAEpMOAiUEjxk1Vl5JRV1LUx9Q2NTC0grWnsnVw8odi4eCmFlHDQ1Vk5uXkQwgGY3KAB6CtSCnigNRQBrN0zs4GY87DwiUmLNMsrqrx76wkV2ppaswhzhTuGSBjCHAEYHcqqu71INMYnm-iExCWkghWVVFfDdAyMTc0sbKAAfOkTnd09un2mc1BWllcHCV1oMoDxcIpeA0Dr92kwAcUgSCNtUxuDcJDcFhRuMoJNWjN2sJEZcNMDQZt0RCoTjdniCXCoAJSVIrgMqYoMVisPxqNAzAAmBiRO4xR5wV4JRwfQl-QWYIUMByoBxgmnQxltZgKqBKxAqtWc7m03H7FoUTYAWhtfMsepKItu0QecUlbxlrl8xwCADcJGgSoqSt7-NB-bwmEGHRQANxaaOG1EmzUHeOoROq5Ma+oE+NRzBJ9WYqG55pAA)

Related to #7889

**Comment by goodmind** [comment]
Related?

```js
//@flow

declare var foo: {| bar: number |}

declare function defineProperty<O, K>(
  obj: O,
  key: K,
  prop: {
    get(): $ElementType<O, K>,
  }
): void;

defineProperty(foo, 'bar', {
  get() {
    return 'hello string'
  },
})

foo.bar
```

[try flow](https://flow.org/try/#0PTACDMBsHsHcCh4BMCmBjSBDATigBAG457jTQBceA3gD54BGOlAdgK4C29K2eNAvolQYc+cK2ZoALgEtozPKnDTmKAArZoAB26SAngB4A8gBo8AaQB8ACnh480egCtKJ23gDWKXZTPG3mjU1KKjc7AHMUSSsASkoAEgBRSBR2FGZJABVdbSNTSz87AVjCaGkkAG5BFCUVdS0dXStSaFMAckZsVtMQ8MiY6lC8XElWbHlWgAsUSBg8AGdJbGUw1rc+Pz5oxGaAOg74IA)

/cc @jbrown215

**Comment by SamChou19815** [comment]
Expected, since the first signature's param type is already any
