### ISSUE TITLE
Read-only private fields don't work correctly

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7937]
Flow version: v0.102.0

I can't write into a covariant private field in the constructor:

```js
class A {
  +#a: number
  constructor (a: number) {
    this.#a = a // should not fail
    this.#a = 5 // should not fail
  }
  m() {
    this.a = 5 // error  
  }
}

class B {
  +a: number
  constructor (a: number) {
    this.a = a // ok
    this.a = 5 // ok
  }
  m() {
    this.a = 5 // error
  }
}
```

* Link to Try-Flow or Github repo: [try flow](https://flow.org/try/#0FAYwNghgzlAECCsDexawNQGIIC5YDsBXAWwCMBTAJ1VhAHt8oAXSwkJuy2AClwJIqUAlMhpomACwCWUAHTZYAXlgRYAejWwoEuoTAATAnSawAZhClgxsSTPmrlAVnWbtug0ZPnLNAL41ibhEUNHFpOQdYZw1YKkpOND9gf1BIGFgAIVE0dD4iMioaekYWNg4uXjx8wWDrWwilFRdYOgBrOvDZSOjNNqS0QNrQm07u5rjOJN8gA)

**Comment by SamChou19815** [comment]
Class private fields are now fully supported.

**Comment by Bannerets** [comment]
The link to Try Flow reports the same errors just as when the issue was created, though. (On versions v0.183.1 and the current master.)

Writing to private readonly fields should be allowed inside the class constructor, just as it is allowed for public readonly fields. [Example in TypeScript, where this works correctly](https://www.typescriptlang.org/play?#code/FAYwNghgzlAECCsDexawE4FMIBMD2AdmAJ6wDEEAXLAQK4C2ARpuqrCIVAC7q0hd50sABRUaDZugCUyNmi4ALAJZQAdBVgBeWBFgB6PbCgK8tMDhp4usAGYQlYObEUr1u7QFZ9h46fOXrOwc2AF82emEZFDR5ZTUNT29YFnRBNFDgMNBIGFgAYVk0AAd0JQA3CC5MDGx8IlIxOiYWNg4Cbl5+NNFqJskopxc1dx0k3zMLAitbe0cY5zjVEa8DIxMJgJngtDC0CIH5oaWtWBXDFLTYDKzwaDgAIUKa3EISHV6JFrQ2jr4BIR64ma0iesVcI10qzwAGtBotlkkYRk9pFQQtwSczsl0KlWDtMkA)

**Comment by SamChou19815** [comment]
You are right. I will reopen it.

**Comment by SamChou19815** [comment]
This is fixed by https://github.com/facebook/flow/commit/798d3e8f41aef847c633c2bd896aa1ef5ba27e08. You can verify it by selecting the master version on try flow.
