### ISSUE TITLE
Suggestion: Remove line numbers from test snapshots

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7938]
## Proposal

Many commits in the Flow repository contain useless diff such as this:

![image](https://user-images.githubusercontent.com/10106819/61303972-143cda00-a7f1-11e9-9b52-f94ee2d894f7.png)

(source: https://github.com/facebook/flow/commit/34038774c4b9941e5ebcfd4c65600bb445b32868)

In some cases it is very difficult to find something useful in those diffs.

To solve this problem, I suggest removing locations from errors in the test snapshots. It may look like this:

![image](https://user-images.githubusercontent.com/10106819/61304196-74cc1700-a7f1-11e9-910e-ce6f15ac01e7.png)

Another solution might be creating an own diff tool.

**Comment by SamChou19815** [comment]
The line numbers are very helpful information to help decide whether some use-def information has been properly tracked for types.
