### ISSUE TITLE
After v0.84 type-at-pos on flow-try doesn't work with object types

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7939]
For example, with this code

```js
declare function bar<T>(x: T, y: string | T): T;
const y = bar({ a: 1, b: 2 }, { c: 3 })

y.a
```

[flow try](https://flow.org/try/#0FA18ZECYKYMYBsCGAnWACAZgVwHbwAuAlgPZ4YBGaAPACoB8AFAB4BcGdANBgJ4cBnQqmJ4A5hgA+nAJQc6AbmDxyQvhgC8VNEwDeGZBwCMPShwBMGAL4998DgGZrMkLwB0yYEA)

![image](https://user-images.githubusercontent.com/10106819/61336955-0eb8b180-a83c-11e9-9038-5ce4c3a2b928.png)

^ v0.83.0

![image](https://user-images.githubusercontent.com/10106819/61336967-15472900-a83c-11e9-8299-a1ea944b79b3.png)

^ v0.84.0

In the editor I see hints with any version, thus I think it is related to js-of-ocaml build.

I guess it is because `re_string_match` isn't implemented in JS and it fails on the `property_key_quotes_needed` function.

![image](https://user-images.githubusercontent.com/10106819/61337450-0f524780-a83e-11e9-910e-99c1a9637683.png)

**Comment by goodmind** [comment]
/cc @mroch 
Related #7698

**Comment by gabrielrumiranda** [comment]
Can I take this ?

**Comment by mroch** [comment]
yes, that'd be awesome!

a couple of thoughts, if `property_key_quotes_needed` is indeed the culprit:

1) making `Str` work in JS is way out of scope, better to do this without regexes
2) technically, property keys are IdentiferNames, which can contain unicode without having to be quoted. the `IdStart` and `IdContinue` unicode character sets are huge. the lexer [can match them](https://github.com/facebook/flow/blob/e81e9f3e9a102cc9e8ec212f7cde23062cef7757/src/parser/flow_lexer.ml#L1686-L1690) if we need to be pedantic about it, but I don't think it's worth the complexity; better to just unnecessarily quote some keys

**Comment by SamChou19815** [comment]
Fixed
