### ISSUE TITLE
Error when trying to upgrade to 15.0 when using HomeBrew on El Capitan GM Candidate

### ISSUE THREAD

**Issue by admmasters** [facebook/flow#794]
Getting the following when attempting to upgrade flow using 'brew upgrade flow':

fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
Command exited with code 2.
make: *** [build-flow-native-deps] Error 10

**Comment by gabelevi** [comment]
Hi @admmasters sorry you're having trouble!

I'm afraid I haven't tested Flow's build for OSX 10.11 and I'm not sure how well Flow builds. It sounds like homebrew doesn't bottle for 10.11 and instead installs from source. For some reason our build seems to fail on El Capitan.

Is there a verbose flag that might show you the build errors? Maybe `brew upgrade -v flow`? It would be useful for me to see what is failing. 

I'm upgrading a laptop to El Capitan to investigate. If it's easy, then I'll try and fix. But it might be hard to keep things working on 10.11...I think Travis CI just runs 10.9 and we just assume if it works on 10.9 then it works on 10.10. If a lot has changed for 10.11 and if we don't have any one testing 10.11 our support will definitely rot :/

**Comment by gabelevi** [comment]
Well I have good news and bad news.

The good news is that Flow seems to build fine on 10.11. I tried `brew install flow` and I also cloned this repo and ran `make test`.

The bad news is I have no idea what is causing you trouble. Maybe when I see why the build is failing for you I'll be more help. Sorry!

**Comment by yphoenix** [comment]
I had similar issues on El Capitan GM, in the end I used the following:

opam install flowtype

And that worked for me. YMMV.

**Comment by iamdustan** [comment]
I simply did `brew uninstall flow && brew install flow` and had no issues. The actual install should work fine, just the update path in brew seems to error.

**Comment by admmasters** [comment]
Odd - uninstalling, then installing manually without using Brew - works. Brew then worked when I tried to install once again.
