### ISSUE TITLE
Width subtyping doesn't work with nested object type structures.

### ISSUE THREAD

**Issue by charltongroves** [facebook/flow#7940]
Flow version: 0.102

## Expected behavior
This snipped of code should produce no errors
``` js
type NestedSuperType = {
  obj: {
    id: string,
  },
};

type NestedSubType = {
  obj: {
    extraProp: string,
    id: string,
  },
}

const nestedSubObj: NestedSubType = {
  obj: {
    extraProp: "",
    id: '',
  },
};

const nestedSuperObj: NestedSuperType = nestedSubObj;
```

[Link to example in flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgMpwDRgCuAzgJYB2A5mAOQKkAmALgBZjGEBGTAngA4VKNAggCmYAMYBDcmBZSAbuJlg4nAFaiJTdlzAyGuvqIBOYXsYxZiTE4W2ET4mKQDW4zqPgIAdOgvi2ITGJgAq-OIAvGAA3qhgqhoAXLHxCWCMKTYmgnhpAL55+QDc-hE4XOHGYNFxCaIAHrZSAAomcHxZtrlpauopdemZ7N1UeQmFqPnoEnDkNrqcAPLJFZxVUan1TSat7Z1gAESH44n9W0MMKccFU+iYYKEspMRgCHAmrsQEUq+kOsQWHBCDAGH5ZvMdO9PoIAGIUUQpIIhDY1RYrdSle5YABChCYBFIUDe4lsPHMLHExCkAFtSc8qG9-mwpGByKIbKJDH0tEwrGAfIKytUAHIcphc5GmVG1XqrQYJYbZHoTIpYgJgMWchhBdblWUJPoDNLbZptDpdHJjE0ZK4jK2UU6TaaoCELdna3UYlJaiU6yr6i5Gi6m3bmg7HU6Ku00YQFNXYx7PV5QKSkGDEAD8rrmC1T6eIPvFkuC0sDHr9Xo0WIeeJ0rBebw+X2zbqhzcERc9pbCgcGgp8FZLyw0UxrWCe4jUClIwNeMmIYjMjdYUnrlKcGXnYCcUgYwAQOQlW444igHyIZEZrHE-OpdJ3oigibrYB4wMkMnIcChR9JcApRtGmaMA+H2ABCVB8wzHw+gAbUOYCw32Q4AF00QARgAJgAZigtMYL6HwkL2DpMNwxNcAHN55CYV5KDgQRVHIbMgA)

## Actual behavior

If my understanding of width subtyping is correct, the above snipped should return no errors. But instead, it produces this
```
Cannot assign `nestedSubObj` to `nestedSuperObj` because property `extraProp` is missing in object type [1] but exists in object type [2] in property `obj`
```

Making all nested objects readonly seems to fix the issue, but i'm fairly certain that shouldn't matter (check out the flow try to see more information)

For example, this works fine without readonly refinement
``` js
type SuperType = {
  obj: {
    id: string,
  },
};

type SubType = {
  extraProp: string,
  obj: {
    id: string,
  },
}

const subObj: SubType = {
  extraProp: "",
  obj: {
    id: ""
  }
}

const workingFine: SuperType = subObj;
```

[Link to example in flow.org/try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgMpwDRgCuAzgJYB2A5mAOQKkAmALgBZjGEBGTAngA4VKNAggCmYAMYBDcmBZSAbuJlg4nAFaiJTdlzAyGuvqIBOYXsYxZiTE4W2ET4mKQDW4zqPgIAdOgvi2ITGJgAq-OIAvGAA3qhgqhoAXLHxCWCMKTYmgnhpAL55+QDc-hE4XOHGYNFxCaIAHrZSAAomcHxZtrlpauopdemZ7N1UeQmFqPnoEnDkNrqcAPLJFZxVUan1TSat7Z1gAESH44n9W0MMKccFU+iYYKEspMRgCHAmrsQEUq+kOsQWHBCDAGH5ZvMdO9PoIAGIUUQpIIhDY1RYrdSle5YABChCYBFIUDe4lsPHMLHExCkAFtSc8qG9-mwpGByKIbKJDH0tEwrGAfIKytUAHIcphc5GmVG1XqrQYJYbZHoTIpYgJgMWchhBdblWUJPoDNLbZptDpdHJjE0ZK4jK2UU6TaaoCELdna3UYlJaiU6yr6i5Gi6m3bmg7HU6Ku00YQFNXYx7PV5QKSkGDEAD8rrmC1T6eIPvFkuC0sDHr9Xo0WIeeJ0rBebw+X2zbqhzcERc9pbCgcGgp8FZLyw0UxrWCe4jUClIwNeMmIYjMjdYUnrlKcGXnYCcUgYwAQOQlW444igHyIZEZrHE-OpdJ3oigibrYB4wMkMnIcChR9JcApRtGmaMA+H2ABCVB8wzHw+gAbUOYCw32Q4AF00QARgAJgAZigtMYL6HwkL2DpMNwxNcAHN55CYV5KDgQRVHIbMgA)

* Link to Try-Flow or Github repo: [Link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgMpwDRgCuAzgJYB2A5mAOQKkAmALgBZjGEBGTAngA4VKNAggCmYAMYBDcmBZSAbuJlg4nAFaiJTdlzAyGuvqIBOYXsYxZiTE4W2ET4mKQDW4zqPgIAdOgvi2ITGJgAq-OIAvGAA3qhgqhoAXLHxCWCMKTYmgnhpAL55+QDc-hE4XOHGYNFxCaIAHrZSAAomcHxZtrlpauopdemZ7N1UeQmFqPnoEnDkNrqcAPLJFZxVUan1TSat7Z1gAESH44n9W0MMKccFU+iYYKEspMRgCHAmrsQEUq+kOsQWHBCDAGH5ZvMdO9PoIAGIUUQpIIhDY1RYrdSle5YABChCYBFIUDe4lsPHMLHExCkAFtSc8qG9-mwpGByKIbKJDH0tEwrGAfIKytUAHIcphc5GmVG1XqrQYJYbZHoTIpYgJgMWchhBdblWUJPoDNLbZptDpdHJjE0ZK4jK2UU6TaaoCELdna3UYlJaiU6yr6i5Gi6m3bmg7HU6Ku00YQFNXYx7PV5QKSkGDEAD8rrmC1T6eIPvFkuC0sDHr9Xo0WIeeJ0rBebw+X2zbqhzcERc9pbCgcGgp8FZLyw0UxrWCe4jUClIwNeMmIYjMjdYUnrlKcGXnYCcUgYwAQOQlW444igHyIZEZrHE-OpdJ3oigibrYB4wMkMnIcChR9JcApRtGmaMA+H2ABCVB8wzHw+gAbUOYCw32Q4AF00QARgAJgAZigtMYL6HwkL2DpMNwxNcAHN55CYV5KDgQRVHIbMgA)

**Comment by lyleunderwood** [comment]
Object properties are invariant by default, meaning subtypes are not going to match, only exact type matches will match. If you make your object properties covariant by wrapping your object types in `$ReadOnly` for example, then the property types will begin to match subtypes, meaning your errors should go away.

**Comment by charltongroves** [comment]
@lyleunderwood right.

I understand why they're invariant for examples like
``` js
type SuperType = {
	obj: {
		[any: string]: ?number
	}
};

type SubType = {
	obj: {
		prop: number,
		[any: string]: ?number,
	}
}

const subObj: SubType = {
	obj: {
		prop: 19
	}
}

const obj: SuperType = subObj;
```
As you would be able to do this, which would be unsound

``` js
obj["prop"] === null
```

But I can't see why my example code in the flow.org/try is unsound. As far as I can see, there is no properly typed way you could write to the nested properties.

**Comment by charltongroves** [comment]
Update:

I figured out why it has to be invariant.
Because if it wasn't, this is possible
```
const nestedSubObj: NestedSubType = {
  obj: {
    extraProp: "",
    id: '',
  },
};

const nestedSuperObj: NestedSuperType = nestedSubObj;
nestedSuperObj.obj = {
	id: "",
}

nestedSuperObj.obj === nestedSubObj.obj // true

nestedSubObj.obj.id === undefined // Invalid with its original type sig
```

Good job flow team, glad this isn't a bug.
