### ISSUE TITLE
Flow incorrectly parses params in an arrow function type

### ISSUE THREAD

**Issue by Bannerets** [facebook/flow#7944]
Flow version: v0.103.0

---

```js
type Fn = (arg: number string) => void;
```
is parsed as
```js
type Fn = (arg: number, string) => void;
```

[flow try](https://flow.org/try/#0FAFwngDgpgBAYgOxgXhgCgIYCcDmAuGBAVwFsAjKLGAZxCwEsEcBKFAPhgDcB7egEwDcwIA)

### Expected behavior

There should be a parse error.

### Actual behavior

No errors.

---

Some other examples:

```js
type Fn0 = (arg: number c: string) => void // no errors (parsed as `(arg: number, c: string)`)
type Fn1 = <T>(arg: number string) => void; // error
type Fn2 = (number string) => void; // error
declare function fn3 (arg: number string): void // error
```

[flow try](https://flow.org/try/#0FAFwngDgpgBAYgOxgXhgCgIYCcDmAuGBAVwFsAjKLGAZxCwEsEcBKFAPhgDcB7egEwDcwUJFiIADCnTZ8hUhSoBjArQZNWyDj34wA9LsLcYlLNyzV0EbNSh8YGCwANMuAsXKUANDGU06jFkdmEWh4BABGKQAeABU2F1l3BT81FnYuXkE9AxMzELEEACYpNCTKFICNLUyBbOMsUyxgPihFABtsWAAzIgRFEHpuJC6EAGZpVzkPKlVKgm07fXrG4CA)

**Comment by mroch** [comment]
fix up for review internally (D16430158).  thanks!
