### ISSUE TITLE
Flow accepts object literal wihtout required fields

### ISSUE THREAD

**Issue by koluch** [facebook/flow#7957]
Following code passes type checking, but throws exception in runtime (as expected):

```
type TestType = { field: string }
const variable: TestType = { };
console.log(variable.field.toString())
```

Flow version: 0.103.0

## Expected behavior
Flow should complain about missing required field

## Actual behavior
`No errors!`

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAKhDOwbmgXigbygMwJYQBsATALikQCdcA7AcygF8AoAYwHtrEoA3AQyt4AjAhDJxEySFHRYGAblYd4bEQDoCbWgAo+A4RFV5CRVcDYBlYFTpaAlLaA

**Comment by goodmind** [comment]
This is expected, https://flow.org/en/docs/types/objects/#unsealed-objects-

**Comment by Bannerets** [comment]
Flow behaves that way since v0.89, see https://github.com/facebook/flow/issues/7345
