### ISSUE TITLE
Interfaces as map not working properly

### ISSUE THREAD

**Issue by sheerlox** [facebook/flow#7960]
Flow version: 0.102.0

## Code ([Try-Flow](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgLIE8CS5rycgbwChlkBtAawnQC5kBnMKUAcwF06QBXAWwCNoAbiIBfIkQD0E5PGAAbekQQB7EI2Q8sOWIgh0M2SDvwBeQiWQByKugCMlurYAMAGgvXqAJgfJbAVjcxSWkAd2UoCkUVNTANdAB5PgArCAQwOmJSSmo6RmYQdk5eAShRZDNMqxt7R1d3G29HANEgA))

```js
interface MyInterface {
  [key: string]: number;
}

// fails
const myInterface: MyInterface = {
  'key1': 10,
  'key2': 15,
}

// works
const myObject: {
  [key: string]: number
} = {
  'key1': 10,
  'key2': 15,
}
```

## Expected behavior

This is an official example from [Flow/Interfaces as maps](https://flow.org/en/docs/types/interfaces/#toc-interfaces-as-maps) (cf [Flow/Obcts/Objects as maps](https://flow.org/en/docs/types/objects/#toc-objects-as-maps)).

I expect it to work without returning errors.

## Actual behavior

```
Cannot assign object literal to `myInterface` because an index signature declaring the expected key / value type is missing in object literal [1] but exists in `MyInterface` [2].
```

**Comment by SamChou19815** [comment]
It works now
