### ISSUE TITLE
Declarations don't respect union types with defaultProps

### ISSUE THREAD

**Issue by jack-guy** [facebook/flow#7977]
Flow version: v0.104.0

I'm trying to write a flow declaration file describing a functional React component with defaultProps but I'm unable to do so because of a bug with defaultProps in declaration files.

## Expected behavior
Flow will allow passing in a defaultProp with a type matching the union type in a declaration interface.

## Actual behavior
Flow complains the prop does not match all of the unioned types.

```
import * as React from 'react';

declare interface Props {
  borderColor: "other" | "default";
}

declare var Container$defaultProps: {
  borderColor: "default",
};

declare var npm$namespace$Container: {
  (x: Props): React$Node,

  defaultProps: typeof Container$defaultProps
};

declare var Container: typeof npm$namespace$Container;
```

<Container />

* Link to Try-Flow or Github repo: [try-flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdAJlrgDbKVzAB2MWUBPFjgAFYmHQBvOnDgAjaMygBhCK2gAuOACIIMABb9tcAD47mggK6sY2+gF8GzNh2EA3DnFW9kPfgBILZGsYMQgJLWlZBSglVXUoLW0gkO0AGjp7eiYWdk4PKDhuMBB-bmQQLFQwIX9vGF9ufkiZOAAKAA8tMIkASi1sPBh-ADkIZgzWlJse1C0YAE8wLAgCLwgfPyhArCsZ8VRM7Oc89096xua4ReXVopKyiqqa3Cw6jYat7LoAHgutuAAegAfAxAQg6IDAXAABIQADu130wHQ8Ig1kY8mEJ1cmJ41yWwFwyFYcAAYupEQApADKDBuwlmcAAvHBJCZWjE4mpNORkIwyKZyNMYGQMiYsgwCJZuPhgBt1psmlA2lFZPJFPx4tBMt0Dr02a1ZJQYJYoNxyAQIBBaJkGP9lQA6EVM1nSACQXK1PMSwt2wRsYqOCEBQA)

**Comment by jcready** [comment]
If you set the `Props.borderColor` to be read-only then it will work.

```
declare interface Props {
  +borderColor: "other" | "default";
}
```

**Comment by jack-guy** [comment]
Hey @jcready thanks so much for the tip! That unblocks us :) am I mistaken in thinking this is a bug then? I'll admit I'm not super familiar with the finer details of flow's typechecking.

**Comment by goodmind** [comment]
@jack-guy  It also works if you use `type`, so I just wouldn't use `interface` anywhere where `class implements` isn't used. 

This also looks like `flowgen`-generated code

**Comment by SamChou19815** [comment]
This seems to work now.
