### ISSUE TITLE
How use $PropertyType for function stateless components of react?

### ISSUE THREAD

**Issue by feonit** [facebook/flow#7980]
It seems like the issue https://github.com/facebook/flow/issues/1081

example:

```js
// This code not work with component as function

function Button({loading, children}: {|
    loading: boolean,
    children: string,
|}) {
    return (
        <button>
            {children}
            {loading && <div className="loading"/>}
        </button>
    )
};

function SpecialButton({loading}: {|
    loading: $PropertyType<$PropertyType<typeof Button, 'props'>, 'loading'>
|}) {
    return (
        <div>
            <Button loading={loading}>
                special text
            </Button>
        </div>
    )
}

const specButton = <SpecialButton loading={10000}/> // <-- no error
// (its NOT OK for me)
```

**Comment by goodmind** [comment]
There isn't `props` property on function

**Comment by goodmind** [comment]
[try flow](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQFA0D09cAKgBbDq4QAmWcAdhHgB3aAGs4w4DFZwu4CPyz94aOAQCu-fMEV1N2mLv5wAQhpgxFACgDeAGwjJuwfgHMANHPb3ulfgC+AFxwtgA+NHBRcI7Orm4hAEYQEPY4-B6R0bg+fsohqDBQ8ZlhAQCUoVlRlDAaUCbW1dFRADyJFlb8AHzNLS22OcC+-gF9-VEOTi7ucABkc3CtLgBucvZoqAByyCBYALwARLEzbof03WMTbfQdloq9LeU0AQDc+lo6inAAymBYuGAyHs5nu-DsJ3iwVCERakPcIQAJABRNJ7FTMACe-1a2DwMAAdKisOiYAAFYhgVCtGDYrAQAhmToPLxkeFuMi9MqVWzNWr1RrjNqrR7XFqtUFdGLTeL7KZxdwBUViiaof6A4FwGBYAAeMCF-Va9ElDwNRpFzWeYxoXH4hTgaoBJpM+yWfwBQJBzJM7LlAEYAAxBgMBOAXMNMVoAWijAggcCwUGIUAYTGs0nQWwA8sw4FmANLqaBwPblIA)
