### ISSUE TITLE
Error when calling JSON.stringify(...).includes(...)

### ISSUE THREAD

**Issue by jpirzent** [facebook/flow#7985]
Flow version: 0.102.0

## Expected behavior
No Error
## Actual behavior
When calling `JSON.stringify(...).includes(...)` I get the following error:
`Cannot call "JSON.stringify(...).includes" because property "includes" is missing in  undefined [1].`
I'm not sure if I'm missing something, or if there is a type missing on my end.

* Link to Try-Flow: [Link](https://flow.org/try/#0C4TwDgpgBAwg9gOwGYEsDmUC8UDeAoKKAZwFcAjAKwgGNgAuY4AJxQQwB9GW2BtAXQA0eAJABDWikREGRZqw5d5-IcOqIAJimCSERAPwMA8pRrAhAXzx41u4FBuo0DeMnRZcI0idoMARE1EEdTgAW18hQnFtKT8iUOhZbjRwgnsNLR1pD0JCRAg-PJScqGAAdzg-MrgiqEtzAG4rPAApAGVDADkAOkT5FCQQAAoHdC6bTWjdAEou1moAGxJ1CCJB30KpxqA)

Any help would be appreciated.

**Comment by goodmind** [comment]
@jpirzent `Object` means `any`

**Comment by goodmind** [comment]
Also because your field is optional

**Comment by jpirzent** [comment]
Ah, my bad. Thank you very much :+1:
