### ISSUE TITLE
Improve error message when a function call invalidates type refinement

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#7987]
## Proposal
If you call a function after doing a type refinement, flow invalidates the refinement.  If the code after the type refinement relies on the refinement, the error message flow produces is the same error message as if the refinement had not be done.  It would be nice if the error message could include the fact that the type refinement was invalidated and even better if it could specify which line invalidated the refinement.

## Example
Current behavior:
```js
type Cursor = {
  prev: ?number,
  next: ?number,
};

const fn = (cursor: Cursor) => {
  if (cursor.prev) {
    (cursor.prev: number);
    console.log("foo");
    (cursor.prev: number);  // null or undefined is incompatible with number
  }
};
```

Desired Behavior
```js
type Cursor = {
  prev: ?number,
  next: ?number,
};

const fn = (cursor: Cursor) => {
  if (cursor.prev) {
    (cursor.prev: number);
    console.log("foo"); // invalidates refinement of cursor.prev on line 7
    (cursor.prev: number);  // null or undefined is incompatible with number, type refinement invalidated by method call on line 8
  }
};
```

## Use Case
The use case of this change to the error message would be to help people understanding this behavior which is by design, but admittedly a little confusing for newcomers.

**Comment by goodmind** [comment]
Related https://github.com/facebook/flow/issues/6610

**Comment by goodmind** [comment]
Maybe this is even duplicate? What you think @kevinbarabash?

**Comment by kevinbarabash** [comment]
@goodmind I agree, definitely a duplicate.  Thanks for finding that ticket.
