### ISSUE TITLE
Module resolving doesn't work for '.jpeg' imports, but works for '.jpg' (Error: Cannot resolve module 'someImage.jpeg')

### ISSUE THREAD

**Issue by marinoguerieri** [facebook/flow#7992]
Flow version: 0.104.0

## Expected behavior
`JPEG ` image imports should be resolved, but it works only if I change the extension to `JPG` (note the missing `E` letter).

## Actual behavior
`JPEG` images imports are not resolved, throws `cannot resolve` error.

See the screenshots below.

I start with `react-post.jpeg` which (mysteriously) isn't resolved but then I figure out that import works for all the other _"JPEG"_ images, and the only difference is in the extension (`JPEG` vs `JPG`)
![flow-jpeg-cannot-resolve](https://user-images.githubusercontent.com/29713150/62520165-46a88880-b82d-11e9-88d6-de73e0779e4a.png)

Then I rename image to `react-post.jpg` and change the import line accordingly which makes the error go away.
![flow-jpg-works-fine](https://user-images.githubusercontent.com/29713150/62520164-46a88880-b82d-11e9-94ed-06c81935e6a2.png)

Please ignore all other errors, they are there because I had just introduced Flow to the file and intended to start "flowifying" it.

**Comment by goodmind** [comment]
You can use `module.name_mapper.extension` in `.flowconfig`

**Comment by marinoguerieri** [comment]
Ok, thanks.
