### ISSUE TITLE
Subjective experience: Flow often crashes and reinitializes, then gets stuck reinitializing / stops working without noticing / is generally not very reliable

### ISSUE THREAD

**Issue by marinoguerieri** [facebook/flow#7993]
Flow version:
0.104.0

## Expected behavior
To work without crashing and creating mess.
I don't really have much to say. I'm here just to express my personal observations without much specific instructions to reproduce it because I don't know what's causing it. It just doesn't seem reliable.

## Actual behavior

I've been trying to make it work but without obvious reason it crashes or silently stops working (making me think my code is correct when it's not). After it crashes it attempts to restart but it often gets stuck and then I have to kill it manually... It's just a mess and feels like a burden to my project. CPU usage is often very high, making my laptop overheat. It would be fine if it did all the rescaning once, but doing it like every 5 minutes because of crash is making my laptop overheat. Also it's slow to analyze code upon saving, it lags quite a bit. 

Please realize that it's not my intention to be negative, it's just that something is not quite right and I can't figure out what.

Opinion:
As an alternative I'm looking into TypeScript. I feel that it, being an actual programming language, will be more stable and suitable for static type checking. I get that people want to use JavaScript for everything because then they can do things incrementally and not have to migrate their codebases, but I can't but ask myself whether it's a good idea because solution already exists (it's TypeScript), and it's also quite "incremental" because for the most part what is valid JavaScript is also valid TypeScript. Maybe it's just my bad luck with Flow, I dunno...

Regards,
Marino

**Comment by goodmind** [comment]
What editor you use? Do you use global Flow or node_modules project Flow?

**Comment by marinoguerieri** [comment]
VS Code, latest version.

Hm.. I'm using global Flow, but actually I'm using it via VS Code Flow extension, not directly (not `flow status`) Now I realize that maybe the problem is due to extension and not Flow itself. However,  I find that using it without extension is quite crude, so I'd prefer not to have to use it that way in order to avoid issues.

**Comment by goodmind** [comment]
You should use NPM packaged flow, and remove global one, then it should work fine I think.
If you still have problems with it, then we can summon someone from Flow team (I'm just a user too)

**Comment by marinoguerieri** [comment]
Ok, thank you, I'll try it when I have time.
