### ISSUE TITLE
Callable Object types are broken

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#7994]
The [Callable Object](https://flow.org/en/docs/types/functions/#toc-callable-objects) example in the docs has been broken since version 0.99.0.

Flow version: 0.104.0

## Expected behavior

```
type CallableObj = {
	(number, number): number,
	bar: string
};

function add(x, y) {
  return x + y;
}

// $ExpectError
(add: CallableObj)

```

[FlowTry](https://flow.org/try/#0PTAEAEDMBsHsHcBQyAuBPADgU1AYQIbTT4BG0WA8iQFagC8oA3ogJAAUAdgK4C2JWAJwA0obn0EBKAFyje-YaxL4BMgM4oBASw4BzRAF8A3MkhcOAYxSbYHUPgAm9tgA8RaCU0ShQArCi4Cts6gANSgaMb6yCCgACQAos7YlvECArACiGwO9jIERKTkVNQSiEA)

## Actual behavior

No errors.

**Comment by goodmind** [comment]
This isn't about callable objects, but https://github.com/facebook/flow/issues/106
