### ISSUE TITLE
`$ElementType` is unsound with other `$ElementType` on return type

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#7995]
Flow version: 0.104.0

```js
//@flow

declare var foo: {| bar: number |}

declare function defineProperty<O, K>(
  obj: O,
  key: K,
  prop: {
    get(a: $ElementType<O, K>): $ElementType<O, K>,
  }
): void;

defineProperty(foo, 'bar', {
  get(a) {
    a // this is number
    return 'hello string'
  },
})

foo.bar
```

## Expected behavior

```
14:   get(a) {
         ^ Cannot call `defineProperty` with object literal bound to `prop` because string [1] is incompatible with number [2] in the return value of property `get`.
References:
16:     return 'hello string'               ^ [1]
3: declare var foo: {| bar: number |}
```

## Actual behavior

```
No errors!
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTACDMBsHsHcCh4BMCmBjSBDATigBAG457jTQBceA3gD54BGOlAdgK4C29K2eNAvolQYc+cK2ZoALgEtozPKnDTmKAArZoAB26SAngB4A8gBo8AaQB8ACnh480egCtKJ23gDWKXZTPG3mjU1KKjc7AHMUSStMSgASAFFIFHYUZkkAFV1tI1NLAEo4xOTUjKyUHPMLPzsBAsJoaSQAbkEUJRV1LR1dK1JoUwByRmwB0xDwyOi86lC8TDwQPEkAC2kAZzx1vDZOblncSVZseQHllEgYPDXJbGUwgbc+Pz48xD6AOmH4IA

**Comment by SamChou19815** [comment]
This now errors.
