### ISSUE TITLE
Inconsistency between `interface` and `type`

### ISSUE THREAD

**Issue by AlexMSmithCA** [facebook/flow#8000]
Flow version: v0.104.0

## Expected behavior

Consistency between `interface` and `type` in guarding against mutability of arguments.

## Actual behavior

Swapping between `interface` and `type` yields inconsistent behavior.  In the following example, `type` will complain about passing in an object with `b: string` to a function expecting `b?: string` as this is potentially unsafe if the function mutates `b` to be `undefined`:

```js
type A = { a: string, b?: string };
type B = { a: string, b: string };

function f1(): B{
  return {a:'b', b:'b'};
}
function f2(value: A) { // would be satisfied with $ReadOnly<A> as well
}

const v = f1();
f2(v);
```

If we swap `type` for `interface`, this error goes away.  Why might the behavior differ here?

* `interface` example: [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUAQVAG9Q8AuUAZ3WzQHMAaUAIwH5aGnVmoAL4BuFBhz4ioAEIUqvRi3YdF-QaMSJIAV1QF0yWKlCQAjAAoAlLRnlEoUNkzod2E+RoByDl5XUfL00hbT0DIxNIACYLADc8aB1MWhIrCkQQxAJjBlBY0ABeU0srMWi40qA)
```sh
No errors!
```
* `type` example: [try flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAhgFygDOyATgJYB2A5gDSgBGA-JTQy6AC+AbhQZsAIQLEyvOkzac5-ZkNGJIAV0YBjZPViNQkAIwAKAJSUJRRKFC1MyTbSNEKAcg4f2Hcl48RREENbT0DI0gAJjMAN1JoTUxKHAtiYMREHUMaUFjpU0tRaLiLYSA)
```sh
12: f2(v);
       ^ Cannot call `f2` with `v` bound to `value` because string [1] is incompatible with undefined [2] in property `b`.
References:
3: type B = { a: string, b: string };
                            ^ [1]
2: type A = { a: string, b?: string };
                             ^ [2]
```

**Comment by goodmind** [comment]
`interface` works more like `class`, than `type` and it is only really used with `implements` clause

**Comment by AlexMSmithCA** [comment]
Yeah, that's a fair point.  It's still surprising that this would occur though, as `interface` still appears to be valid here.

**Comment by SamChou19815** [comment]
Now they are consistent.
