### ISSUE TITLE
$ObjMapi seems to break later refinement

### ISSUE THREAD

**Issue by dperetti** [facebook/flow#8004]
Flow version: 0.104.0
## Expected behavior
Refinement should work no matter how the union of types was built.
## Actual behavior
Building the union of types with $ObjMapi seems to prevent later refinement.

[Flow Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgOoEMB2ALmIXGAEYCmYu5M1pYAJpVAJb7W4DGhbc+AM5gYbANYMAFm0GpCATwAO1AIK9+QsAF4wAbwA+qMGAAiAeQD6AFQASASQDKALj2HjxwXAC2lAHIBXLyoAJxd8QJCAGiMwfQBfaONzaxsVKxcDGI9vSgdCYI4AcxdBfKLE2LjUeLklVXUBAGlKeW0wABJm+UEAHjU+AUEAPgBudExTGUVcQm5JMAQ4fxgmBbhgsRFxKRmnVCh-fAb8ZimZuZ70sH6NLqGACkIXK0iaYMLBF3aAUXofIisdT6x0ErysQwAlHpUFUmGdZpJ7gByZK2RxI166Tw+AJBSihMAARgATHEoRM4GJxlhfJRKKtGPh1l5cKIAF5cY4kOrCcitDgAK0o6nwhRIkk5AxOElajRowlwYAARAplC5GkqwIpgnBlMEFBgsHAoOLqHByELeAA6Q04aj+QTUdpmC0AWVwijYJDITDIhGkwkkhEIik+mFgiCt60KwEo+GAvu4gmAqsoyf8fFEfDTwAAxKRuABac0ClmKdwVyu1ZRgb4AD3yPEINwEgJrOh6jRcLfwXVeADUvv3Wf408CpcMHo0B1CtENXGArUv+69U+rKtX6hPsGx-W3KJd5zpnW6PWxLq9643eD390NqWAAMIS7ibBAS-3464gnd7uprDYFWEDhCDjFgmFQbhBmIJsNEEKw0yeb9t13SR93HOCj2hJJLDRZw9GxPwInxFxCVXOoXBRXD7AcDEEhiVFUiuLEcjyApRUomAxAFDFuTVMAqJSNIkXoqpbV8RAwCWYIwHYfBWWQjQ+OoBBULAAUHWIAA3Ec003RSBDadphxgUdeh7QRfzQoELKGecsncW07GIR1KC8YRGEWDY9igoRiFA0oe27LkdBYnFiIJMjlMoxj0SqXzShIRCe2JYKpTaMLcjKDiBPkOBeLXATGOEsSJhsRBKC0-ElytMB9kOLlgnpfxuEoe5YIENKNChXR0AASEEVSEXa44rVTHqHOMbhcEdIrqOElxJrAPqEuIbg2g6-ArUItiijACZ-RkZg4DTfAkWILzNicQt7iW4xyCa3AqUrOqXum2bBLwpFFpelboJoDbRsI3EQn2rBDuES7hEAPg3ABRdu6KEe56qwrKo4he4wgA)

```js
// Want to be able to define actions like this
type Actions = {|
  DO_THIS: {|
    someNumber: number,
  |},
  DO_THAT: {|
    someString: string,
  |}
|}
type ActionKey = $Keys<Actions>;

// Dispatch would work like that:
function dispatch<T: ActionKey>(t: T, args: $ElementType<Actions, T>) {
}
dispatch('DO_THIS', {someNumber: 12}) // ok

// Need to normalize action types by injecting the action key K as a "type: K" property
// of the object.
// We use $ObjMapi to do this https://flow.org/en/docs/types/utilities/#toc-objmap            
type ExtractActionType = <K: ActionKey, V: $Values<Actions>>(K, V) => {| ...V, type: K |}
type ActionsWithType<T> = $ObjMapi<T, ExtractActionType>

// Check whether ActionsWithType works as intended
const actionsTest: ActionsWithType<Actions> = {
  DO_THIS: {someNumber: 1, type: 'DO_THIS',},
  DO_THAT: {someString: 'lkj', type: 'DO_THAT'},
}

// Now our final Action type with just values
type Action = $Values<ActionsWithType<Actions>> 
      
// It seems to work:
const testAction: Action = {someNumber: 1, type: 'DO_THIS'}
const testAction2: Action = {someString: 'yo', type: 'DO_THAT'}

// However... 
function reduce(action: Action) {

  switch(action.type) {
      case 'DO_THAT': 
      	const c = action.someString // this doesn't work :-(
        break
      
      case 'DO_THIS': 
      	const a = action.someNumber // this works 🤔
        break
      
    }
}
```

**Comment by murrayju** [comment]
I'm seeing a very similar problem in v0.135.0. I'm trying to do the exact same `$ObjMapi` for the same purpose (make Redux actions easier to define). I've written up a whole bunch of test cases that fail: [try flow\(https://flow.org/try/#0PTAEGMHsFsFMGdQDMBONQCVYBMCuAPAKABcBPAB1kx13FhQB4BlAGlAEEA+UAXlAAp4xAIbFYALlBNQAH1AA3SAEtsbYeGJLIAO0nsAlL25MA3IUIgOGrdtBlKieAAtIuADbZQAIyrZY4N2EUHFAlW2InJUQkSBRoUUJYfHJY4jsKKiYlaHI3WHZrHQBZYXIGABVeUCEUMIBzbj4Ab0JQUABtcoBdSQASJidS2AYm0HJhUjdIYWxJYW1SNno0FEkvSEg8+dAAX04WQh2zCzAAUWT5zwjM7Nz8wu0S8mraJztBtOvQAGtYUlDHLA0sJEF8AAb2WBgsZoSgoMihcJOKgYAAS0kgXgAVv5iIlkql0pRQOdxto-NgCpodPAGOxJFkcnkqTYngxOI1QL0APLYp5KBitDgHNoMADSbAAapx+BLQJLDDxuKMAHRqyVsSGSMW7A6cY6WADCOnk9GIiEZdxZxVKiOIkFAwiJVCg2hEYXqjrcbjGkHg8CUXjyVmp2ng+JS8OdIdwwjc1rDdIZt2ZDzZHKqvUlcdwCAYpMuOATtK4+vMlnKkUQUVAAHcPo7QINyXkUMhcNoHqAppBvog3EpfhHCZDQKjLq3mGwuFVBCIxAy1A89IrjAawAAFWH0Nz-SGeeLPSBIJsT+jRWIQYKiWBYPB0Ns+Ka14dR0fjlv0NmsDjJpn3UN005XpznUYgGB5PlSkFNoC3JIsHhLfYhQYaV+AVIwxzPRgf2lPUywsAAqQjWkI0BDWvMRECdYJ73oZBLy+OolFNWwmHnKhLkdf1IHAJQb08S1U0A0pSNAAABcYUGEaBQCadibx2RElE0OMFLEd4qCEIJNG0Opqg4hi2wiGt4AHOhQGPTSpHtYIxMkoIZLkj9sFbJ4lObVzz0bQ9kDQWSwJsaN7VPT82yQDsHlI4BXzSPwkGEdw0giztQyvWAbzvWh6GYDjpz-K002gjl+CFD1VLcdSJBsm8RVCryUHgSQXLc6CqunZD9EkLKH1y2qYzjYs6QzFo2mCYhcBQWw5xvAB+BlDL4cr+MqvLHWXAb40Q4aupqjSlTkoU2ldIR6tbKpAp0WaVVHWazvPdpLu0G6Mi6UBJG0dw3DMNoxqBSbbE8867qB+gZrEJdQ0MSRtLEH7djMHZyzAKjzWR0BKxrGsnSEgDWVKFUMarAEm0gWtQAASQAck8AdfjsB14rCKgvgHU6rPgXByEjMRPCe8NR0rPGbWeZoZCO385LGCYphmD7cGgHw2x2Oq2gAIUkUZxkmaZZgM2o9N1CWK2J+BYFgaBQQdWtYm+UITy+bXZc8GsklyJQ+OIXcFGUbAJcNTXpZ1uWfZUI3ftASwABkMvkT1XE+ZEg+d0BsEgBBtCptIbZQb5jbAAARTWZBkJHS-R7RIDSa82c0cAIEgPw2CxXBTvAZFwDtiJRCJ4XHltcBth8Z0AFpB9OkFG1xhMnkIE7PgQYgnnKChPWaCX6Slp3dckABOcPfo1reZZ30AqZiSAqYPtoA7klX89AIu74OI5CH4VHl9XvTJCFmfSn0Mw79F6f3IPUAqwl8ZlF6GKP4tJf5FXIByAB5hRxVSqKNX6F95qgE+oregqtvBBGwTUeoL90agX-JZE8LhybgEoreGgD5qguHcJ4YerccBz3oT1HK7Ve5-0QfwJoKtDoR03uDWAbAtYnxmLsQOWoz7sCpmwbeIdcFK12KuAQqo1Sw0kQxSAkhVGeB2PoAhR8JFSOTrrORUsFFUzVso6xIcSGG1MZhIRoA1Qqj0WwLwQQjEyJMWY-2kgJFaN8Q-J+4TMKRIfpjRAg8OGgiTvWTYLpuGMPoiFHsdswjyDjCobxyBmaU1AHUXM-oolhN8cfYOwTYl5XMBHSwvQABiz5SS4hwKcFAKxQAjwbn03E3sEpKDcIgPALMHT5MKZ4DhVDnEuzYhxCWFjanSPqbY0Y9jHEqKCTDYgBt9LuIOp47xtSL6BK2aYl+yCTgkgmbAes9B9HaHNlcB0w9hBBmmQoOZN53g92YqxSy2JcTUWCP8gcfNEICDCNZKAfggVxSiOMYg7cEDrVDPAfQDyEnRhtqw7wVAOGeBiMZBs5BJopDNiqEgGQQxBT4FSWMW0cUVGRAIgilhTigoiK4Oobw4IUmLNUc2lsGZ1lttxSmNNuyDioLWFSkQkRUBal+W0kI2AqVTuneAmds4yopZtYsDyKagDdt0q4Scsw5jzCKhCOLuAhXGgDUAcBGwdiCqOOmsAGXEgAOrzF5gmdBzpJBUyUfs+p8s8HK1kHYjIka9lLMOccpScgdnJrPoaK+RxQDoyFmbIZwQNDe3GP6aMmLO5v2zZQSN0a02gAAOy2ITMgzxuynHGMjRffNegHidvrdVKNPaDmttscGt0TqbDDojWfVNvaz79qnSG2dOh7mtI6WTLpGgel9MvIM5wrgPDIGEOM1OuYpWzJhUsutC6x0xudpG-x2AB1Ms3YAkdjbx2xrPm+j907Q1DvXFyHdtY92816f049LCz1jJ9FMm92gCl3uMQ+7tz7T4AAZ22gcwzmhxf6X2gDwzsSQwGN3aC3WAdpnTkjWpg0e5hp7yUXqQ9ekK0AogBkNpCOtFHP00e-UJqjlICMPPo7uxj+7sDMbbIMqAwzy3-EQ5MrjDoeP+k9BhrtRGlH4aht+x9hmxProk8Z9G0nIOyeg4exTrHiWIZJUkkto4azab43UPxuA0hhCEBldj4yNN-NrGgQ2xjnTxQfcu8+GwP0dpM3F1d5mZ2WbnWBmzUGD2wacwhjjrnErucZZ53jpDvB+cRIF2R6mr1hYi-pKL+5YBIFixOttQmkvtf-Z1yjFmktAA)

In trying to narrow this down, I've reduced it to an even simpler case: [try flow](https://flow.org/try/#0PQKhCgAJIZQSwLYAcA2BTSB3A9gJwNZwB2A5pGgB4CGy6kAZnLgM4AuANFgBZq4YJUkkAG5UUAVwxi+VACYBPSAGNsRVlWLNIrHpHxp5AOiiQAUuLaQLxMgBIAamMlbMcHdq5wXefFqpbKJDQlVjRZKBBgcHBWeSDIABUeAEEQuFUAWUFIAF5IAG8AHxNkgC4Cwu04tHKAcmTaziQqeRRsOXKicQQAI15IQoBfdhMAIXKiqqC60cbIZtb22XK2XBsB4ZMAYQnK2OnIWq3ajZGhgG5o-YxU1nSiLTyHJzRmAB4ktFv7rKQAPmiAAp8lMaocGk0Wm0OpAAOyQQblb6qZgASkuwNBMzmC2hy0O9Gw2BOiMgyIe6PAmOudWOCKRaRRlOAwEgtgAYm1MABRChBEJhbm4XB4KkgmngnFQpZ1HpyEkMu5My4stmc7A8vnBUKyIUi3BirGHWaQxYwgAM9LJjIpKtZHK5vP5Or1oup1VpUrN+NqhOJVvJaLtasdWoFuuFbvypMDzPt6s1zsFkYN7oOtQAIgrrUrbeBVQ6NU7tcn9YaJfVs7Hg4XEyWI2XMbiZQSiVWbUH8-HQ0mG1H5tKYfCYx3KV3IABaKfTmezufzheL6eQFnRUAQaAASSIHgwsleTDCymw+84On42Vk2FekCI2FYkD4snERFkVDUKEU+8YRAw59BkDvrIu56AYxhbg8oRyJwtgAPI9AAVr8cCQF4VjMEerDYMeyDiKEIH7swh7AdcDAiggIFEbQ-Skd+xBuPcERRDE1SwIgqBfDavy5BUJS7AO3qdN0fS4KcYz8c2MKrOsQwjNAOwVLJ4BDGurK-Fo-6kcw2E6FQD7-gA0gYqF+LI+7AcQWEgaIEhSBpugAAbXA58wikEuCxOAgR4PprFOkBYSBm8yR-Dxti8lQIRvHBiHIW8JRyZAbwGZw9h-ICKWQPYqK5KFkyGAV9hnh6kAGWJfx-Jc46fJAJDtCgkDYPQHhof5r6BR2AFobpD5uFgcAoA1Yhcuh2jYSQaC-rgel-roaAAI7iHANmTb58T0ORkBURxokqPu1VzWG6i5iZHh6eObXmUF8DUeSvyhTkj2JCkXGCOOox4SBfQjcwXAavZem7l+2F3g+fRcFQwizRgzA0GgLHxJ8d2CAATDxl0dbm7w3RxyP-FVqo1RDSBIIoSj+DebTYPgjX4OAKiQdorysPBCE8fkfEFEalamni5TDol4xcxWJoCXzrb+ps8kTNzdKbIMGKhGwrPlEjr1IJSgJKyziGqy9ua-CjY6quyGgoBp2Hk6wShcIBAEIF4AjW1w9MovpzOs6Mcjs5z4olTzYstrUcqyCSgsyyLXri76bYIolCl++mcsjAr461sW4auqm2uezCasG4IcYhkWR2lm6OeIV7+L5z8qNF+npd9tnHuVzCGOyNd7HoHjfzG6yOPoKJ2sAw+CEWA+hJKBYjU7v+NnOGR2AUf+AhIAjNwdmjTyOLZ7zt53t3qxVVVpmCAeSfiw6KvczBGxiidn6LF91H67ZY3f5b+3L18oh-BYJhnF0KZJxbT+uIFAwF6Bm0gM+P82FiA2TgMBC+n90wQkDjCYO8oAyb3rgAxuWcQG-WwOAyB0DYFjVQkQRByDBzhFPtiXmLZLQjnfngns9Ys6oLPscJhmDX44LYTWfBvZCETlASQiBDByGSEoQ7ZgRFSCgjFKwm+f9uwl1ESmbhdQsyCLUewzRnDgHiOIaQ6RA0YGyKsvIxRZAUEMMlPo3+hi6yZxMRI8xUDLF9HJhYP8rE0K2JsJwHon1NBQTIQNLQFCrKYBFEoi+yimx0JfrHVRLjhEcPcfqIhYCpHeIar4qg-iupaGCaQUJ4TIJoG9oUmJ1jsLxNUPYuhySQTPzhM4h4H81xgBMDAP6ShCCkE-JwawSiqAATEHAfwygIakBvP+cGkN0gGkgJEVSsA4aAS0IGFGVSHz+L8NMlAszmDrxzDfAAzGFHezgPj61rkgFGlUgQPzqOgzpV8rkomuZrD5xoo5BwERkh4-z76yzfjc1xgCy6iVMfkqJDVYnwOoTM2h3odGSj4T6EO0K-mwoIR4sxBSZFwKoTQjB9DAW1CfqkyALCf7gqJVoxstLeHUrSZLZlzAIVpxEcY3JiLJHIqsRSipZBrgqN5fy-+2SgHsu5nosFfLWVCrwHk0VFiUWNMgJK6l2LKzdLVVkoxOTNUiq8dA4ppTSJBK8HYw5VC2C1ORQ0ilzTEltOlSkwSEsCUsrNW4xVlrPFkp8cEEpGEyn6sdSEyAYTeo1LqWbD1lCvWtO9O0rlXTVUQqAA)

Another bizarre thing that this second one shows is that a type alias can have different behavior from the explicit type. I'll probably open a new ticket for that.
