### ISSUE TITLE
Error throwing functions are not typed correctly

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#8005]
Given a control flow where one of the branches throws an error, I should be able to use an error throwing function and have it typecheck correctly, but that is not the case right now. For example:

```js
function fail() {
        throw new Error();
}
function foo(a: string): string {
	switch(a) {
      case 'bar':
        return 'bar';
      default:
        throw new Error();
    }
}

function foo2(a: string): string {
	switch(a) {
      case 'bar':
        return 'bar';
      default:
        // $ExpectError
        fail();
    }
}
```

Flow version: 0.104.0

## Expected behavior

It should typecheck.

## Actual behavior

It fails typecheck with the error: "Cannot expect string as the return type of function because string [1] is incompatible with implicitly-returned undefined."

[Link to Try-Flow or Github repo](https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqJAIa7QAUAlKAN6KgOMPYAWATgqOgKbygCibDmyoBuRAF8UGHPkKRYscsQBcoAM7Y2udAHNKazdr21EASHXxc2TC2XU6TBpmLruoAOQAjYmw8r6JwY2bmxUNkJvXw9xIIATbhJUaGwAoOZ2Th4+QWExQIYpKWksPAIiRQAmZUMtHX1a411TCysbO2IHAsYXN08fPzT0kLCI-ujYpwSklKGgkFAAEn4ADwAHbhxc2DZuphIyfKYioA)

**Comment by villesau** [comment]
Try adding `return` before `fail()`. 

```
function fail() {
        throw new Error();
}
function foo(a: string): string {
	switch(a) {
      case 'bar':
        return 'bar';
      default:
        throw new Error();
    }
}

function foo2(a: string): string {
	switch(a) {
      case 'bar':
        return 'bar';
      default:
        return fail();
    }
}
```

**Comment by volkanunsal** [comment]
Thanks, that works!

**Comment by goodmind** [comment]
@villesau this looks more like bug that this PR https://github.com/facebook/flow/pull/7658 or this https://github.com/facebook/flow/pull/7657 were trying to fix
