### ISSUE TITLE
Option 'exact_by_default' is not supported

### ISSUE THREAD

**Issue by OvestLabs** [facebook/flow#8006]
Flow version: **0.104.0**

## Expected behavior
Should be supported since it's in the documentation [here](https://flow.org/en/docs/config/options/#toc-exact-by-default-boolean)

## Actual behavior
Fails with the following error:
```
.flowconfig:14 Unsupported option specified! (exact_by_default)
error Command failed with exit code 8.
```

```
// .flowconfig
[options]
exact_by_default=true
```

**Comment by TrySound** [comment]
It was not released yet. There is only lint rule.
https://github.com/facebook/flow/releases

**Comment by TrySound** [comment]
FYI it's added to 0.105
https://github.com/facebook/flow/releases/tag/v0.105.0
