### ISSUE TITLE
Version `0.105.0` is missing the binaries

### ISSUE THREAD

**Issue by philiiiiiipp** [facebook/flow#8011]
The latest `flow-bin@0.105.0` seem to be missing the platform packages

```
$ npm install flow-bin

+ flow-bin@0.105.0
updated 1 package and audited 1787939 packages in 7.595s

$ npx flow
spawn /Users/philipp/node/dev/dh/sfa-api/node_modules/flow-bin/flow-osx-v0.105.0/flow ENOENT
```

**Comment by dperetti** [comment]
Same issue with yarn.

**Comment by avikchaudhuri** [comment]
Something got messed up during the release. Should be fixed now, sorry! Thanks @mroch for helping sort this out.
https://www.npmjs.com/package/flow-bin
