### ISSUE TITLE
Cannot compare generic with itself

### ISSUE THREAD

**Issue by lyleunderwood** [facebook/flow#8017]
Flow version: 0.98.0+

## Expected behavior

```javascript
const compareGeneric = <T: number>(a: T, b: T): boolean => 
  a < b;
// no errors
```

## Actual behavior

```javascript
const compareGeneric = <T: number>(a: T, b: T): boolean => 
  a < b;
//^ Cannot compare `T` [1] to `T` [2].
```

* Link to Try-Flow or Github repo: [try](https://flow.org/try/#0FA1jGD2B2DOAuACKBbADgQwE4FNEF5EAKDALkWgFcUAjHLAGkRvKtvoEpybJIAbHBmgEAfIgyIAPMwDcIKHCQYAJsoDiOaPQCW4AlIAqranSwiS5A0xaIDXW6PGIA1LJAB6d4lwY+fAJ6IAO4AFhhIAJLBQkjasIjwkIgoGADWePAheDyU0MrxAAZGFCb0iAA+iAAi4TgFwAoIyJDo2DgaWli6+pLFbKbmZLbWlvY8-ILC+GLAiE7SNHJAA)

I suspect this is linked to the change in 0.98.0 referenced here, as it's the only thing I could find that sounded sort of related: 

> Fix an unsoundness with addition or logical operators when combined with generics (#6671, #7070).

Those issues point at this change: https://github.com/facebook/flow/commit/db8a41e4e2fbfca0fffddebb69917b1835789872

So the question I'm left with is, how _should_ I type this comparison function, if not in the way I've typed it? This really _looks_ like it should be fine. Math operators and `===` all work as expected in the same position.

**Comment by jcready** [comment]
Not an ideal workaround:

```ts
const compareGeneric = <T: number | Date>(a: T, b: T): boolean => a - b > 0;
```

**Comment by barretron** [comment]
2 ways I can think of:

```js
const compareGeneric = <T: number | Date>(a: T, b: T): boolean => 
  +a < +b;

const compareGeneric2 = <T: number | Date>(a: T, b: T): boolean =>
          Number(a) < Number(b);
```

**Comment by lyleunderwood** [comment]
Thanks, I hate it.

Using `Number` looks like the clearest option to me. 

Is there some underlying reason I should understand that explains why this behavior is correct? Or is this actually a bug?

**Comment by barretron** [comment]
Seems buggish since it's really easy to defeat, e.g. this doesn't error:

```js
const compareGeneric = <T: number>(a: T, b: T): boolean => 
  Boolean(a) && a < b; // Works
```
Or even nonsensical things:

```js
const compareGeneric = <T: number>(a: T, b: T): boolean => 
  isNaN(a) && a < b; // Works
```

But it also seems like generics aren't really needed here:

```js
const compare = (a: number | Date, b: number | Date): boolean => 
  a < b;
```

**Comment by lyleunderwood** [comment]
thanks @mroch
