### ISSUE TITLE
Make `Function` alias to `{ [[call]]: any }`

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#8020]
## Proposal

Make `Function` alias to `{ [[call]]: any }` instead of `any`

## Use case

It would error if you provide non-callable things and also seems more safe, instead of outright `any`

**Comment by kevinbarabash** [comment]
Is `{ [[call]]: any }` equivalent to `{ (...args: any[]): any }`?

I didn't know about `[[call]]`, are there any docs for it?  I can't seem to find docs for callable types either.

**Comment by goodmind** [comment]
There's PR for call property https://github.com/facebook/flow/pull/7790 docs, not sure about equivalency

**Comment by SamChou19815** [comment]
We now updated the docs to recommend other safer patterns: https://flow.org/en/docs/types/functions/#any-function
