### ISSUE TITLE
defining modules that are accessed via a relative require/import path

### ISSUE THREAD

**Issue by JacksonKearl** [facebook/flow#8026]
This page https://flow.org/en/docs/libdefs/creation/#toc-declaring-a-module states `defining modules that are accessed via a relative require/import path will be documented soon`. Is this available yet? It seems the line has been around for 2 years now.

**Comment by goodmind** [comment]
This is duplicate of https://github.com/facebook/flow/issues/3609

**Comment by goodmind** [comment]
Best docs that exists is here https://github.com/facebook/flow/issues/1996#issuecomment-230919868
