### ISSUE TITLE
`make all-homebrew` fails during `mkdir scripts/ppx_gen_flowlibs`

### ISSUE THREAD

**Issue by Moisan** [facebook/flow#8027]
Flow version: 0.105.2

## Expected behavior
Build to complete successfully on mac when using `make all-homebrew`.

## Actual behavior
Fails with the following error:
```
+ mkdir scripts/ppx_gen_flowlibs
mkdir: scripts/ppx_gen_flowlibs: File exists
Command exited with code 1.
Failure:
  Error during command "mkdir scripts/ppx_gen_flowlibs": Ocamlbuild_pack.My_std.Exit_with_code(10).
```
See this [homebrew-core pull-request](https://github.com/Homebrew/homebrew-core/pull/43058).

* Link to Try-Flow or Github repo: No link possible the issue is about building flow on mac.

**Comment by mroch** [comment]
@Moisan do you have the full logs? can't repro locally and the tests on the PR seem gone.

**Comment by Moisan** [comment]
[Here is the full log from the Homebrew CI on mojave.](https://gist.github.com/Moisan/390a77b097a4584047ad29c567300f83)
