### ISSUE TITLE
Should `interface` reject static interface members?

### ISSUE THREAD

**Issue by popham** [facebook/flow#803]
I just tried to use  a static member function within an interface, and I got an unexpected identifier error:

``` js
/* @flow */

interface A {
  static someStatic(): void;
} // inter.js:4:10,10: Unexpected identifier
```

Is relaxing `Type._object env` to `Type._object ~allow_static:true env` ([src/parser/parser_flow.ml](https://github.com/facebook/flow/blob/25e6368959740e845cb962fe2843c503c7d6c4cc/src/parser/parser_flow.ml#L2885)) fraught with peril?  (I expect the override semantics of `class` to get applied, so I don't see any problem.)

**Comment by gabelevi** [comment]
How would you like to use an interface with static members? Can you give a small motivating example?

**Comment by popham** [comment]
The case that won't go away is alternate constructors:

```js
interface I {
  static ctorPattern1<T>(p1: number): T;
  static ctorPattern2<T>(p1: string): T;
}
```

In a serialization library of mine, I've got a `Reader` class:

```js
export default class Reader {
  // Imagine properties here.

  constructor(arena: Arena, depth: uint, isOrphan: boolean, segment: SomeBuffer) {
    if (depth > arena.maxDepth) {
      throw Error("Depth exceeded");
    }
    // Populate properties here.
  }

  // Pure virtual static.  Don't worry, this doesn't actually work :).
  static _deref: (arena: Arena, pointer: Datum, depth: uint) => Reader;

  static _fieldGet<T>(context: Struct, offset: uint, defaultArena: Arena): T {
    var pointer = {
      segment: context._segment,
      position: context._pointersSection + offset
    };

    if (pointer.position < context._end && !isNull(pointer)) {
      return this._deref(context._arena, pointer, context._depth+1);
    } else {
      return this._deref(defaultArena, defaultArena._root(), 0);
    }
  }

  static _fieldUnionGet<T>(context: Struct & Discr, discr: uint16, offset: uint, defaultArena: Arena): T {
    throwOnInactive(context.which(), discr);
    return this._fieldGet(context, offset, defaultArena);
  }
  // ...
}
```

The last time I pushed this through Flow (without the pure virtual static), it choked on the `this._deref` references inside the `_field...` statics (an issue for another day).  An interface `interface Derefable { static _deref ... }` would be useful in `Reader` subclasses:  `class Subclass extends Reader implements Derefable`.

More generally, I don't think that interfaces can add anything to Flow without statics.  Simple `type`s combine with the intersection operator to provide without-statics interfaces:

```
interface J {
  sMethod(): void;
  method(): void;
}

interface K {
  method2(): void;
}

class C implements J,K {...}
```

versus

```
type J = {
  sMethod(): void;
  method(): void;
};

type K = {
  method2(): void;
};

const C: J & K = class {...};
```

**Comment by popham** [comment]
Looks like a [recent commit](https://github.com/facebook/flow/commit/b72d1c61487f9e95ddbe68c4f994d9699b7b71c9#diff-5c9b93a1febb707483495f384257a069R2884) picked this up.  Whoo hoo.

**Comment by popham** [comment]
The parse errors went away. Unfortunately, Flow doesn't check the types.

**Comment by calebmer** [comment]
TypeScript doesn’t support this behavior, and I personally don’t think we should either. Please let me know if you disagree 😊

**Comment by popham** [comment]
I disagree. Statics are available on JS instances through `constructor`. Shouldn't Flow reasonably handle the following?

```js
interface I {
  constructor: {
    a: string
  }
}
```

Isn't `static` sugar preferable?

**Comment by calebmer** [comment]
Interfaces don’t really represent instances in the same way classes do. It’s better to think of interfaces as a classlike sugar for defining object types like `type I = {}` 😊

However, I see your usecase and we’d love to support a pattern like:

```js
type InstanceStatic = {
  staticA: number,
  staticB: number,
  staticC: number,
  new (): Instance,
};

type Instance = {
  a: number,
  b: number,
  c: number,
  constructor: InstanceStatic,
};
```

If you don’t want to use ES6 classes 😊

**Comment by popham** [comment]
Hmm. Given interface inheritance via the spread operator, if `implements` is extended to operate with object types, I'll never touch `interface` again. Is it fair to say that interfaces are intended to track TypeScript's for cross-compatibility?
