### ISSUE TITLE
Unions Refinements Bug

### ISSUE THREAD

**Issue by jinmayamashita** [facebook/flow#8035]
Flow version: 0.105.2

## Expected behavior

The following ([Flow playground link](https://bit.ly/30sa7BU)) should work:

## Actual behavior

Breaks with the following error:

```
8:   bar({ ...f, opt: true })
         ^ Could not decide which case to select, since case 1 [1] may work but if it doesn't case 2 [1] looks promising too. To fix add a type annotation to .type [2].
References:
11: type Bar = { ...Foo, opt: boolean }               ^ [1]
8:   bar({ ...f, opt: true })
         ^ [2]
```
I think it seems this type-refinement should work (as it does in Typescript)
https://codesandbox.io/s/friendly-ride-k8t6p?fontsize=14

**Comment by jbrown215** [comment]
This is because of a bug in our spread implementation. I am currently working the fixes for this.

**Comment by nmote** [comment]
This no longer errors in master
