### ISSUE TITLE
Cannot assign between variables of the same type T using $Keys<T> 

### ISSUE THREAD

**Issue by danny-does-stuff** [facebook/flow#8036]
Flow version: 0.105.2

## Expected behavior

When using a constant of type `$Keys<T>`, I expect to be able to use that constant as if it didn't change. 

```js
const key: $Keys<T> = 'someKey'
t1[key] = t2[key] // should not give an error
```

## Actual behavior

The constant of type `$Keys<T>` always behaves as if it could be any of the keys of T.
```js
const key: $Keys<T> = 'someKey'
t1[key] = t2[key] // says that it can't assign because it could be any of the keys from T
```

This is a trivial example, but the flow try shows why this is useful and important. Thanks!

* Link to Try-Flow : https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFKBDAXFAZ2ACcBLAOwHMAaTKAI33IFcBbeiY2rAY3wEFixbCAA8qUgBN8RMlQC+APm5RpaAO4ALbMAgA3TvnoIANhGzl56K+h5xyRKADMEARnzxEKDFix4oAOS6RAEqWIxQABxhUHxQANoSagFSAfIAujFqqFo6+obO2CYEEPIqVnYOwM4IAEweCMhodH74AfQm2JqhLQz4rgAMMXGJUm2pGVn4Odq6BsT4JMyl5ejoAPSbUAAqAEoAkgBq+-wAMlD7ALIACqcAopd3AHLb-Nv7APJPa5WOANYQED4AAkAGlAQRRJ5FE0AtgAugXHBXPEASB0k0kbVUYD0mstvwAMLbACqZygJIAyncoIT+NSoPwngARKAAdQAEgBNC7bAKUi43D67V4vWz2f4Q7ZwD7zdRkXQCIQiURgiFQhCKGEoeLoACQcJ6BvoRoCkh6ePQaII0tlnHlpF0ADoXMQ7tgeJoABRetEg8EgSHQgCUyBhGD1SJRaIxKCxOPR1mD6CAA

**Comment by SamChou19815** [comment]
The behavior is expected, although it limits expressivity.

In your example, typeof `t2[key]` should be `$Values<T>`, which is a union of all values types, which is unsafe to be assigned to `t1[key]`.

Supporting this soundly would require special-casing just for this syntax, which we don't plan to do
