### ISSUE TITLE
Flow Reports Incompatible type Error When Reduce Callback Uses Ternary Expression

### ISSUE THREAD

**Issue by paboulos** [facebook/flow#8049]
Flow version:0.106.2

## Expected behavior
This should not be an error.
## Actual behavior
Cannot call `[...].reduce` with function bound to `callbackfn` because number [1] is incompatible with array type [2] in the return value.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzAHMBTfAWQFcZ8BLABxhNzAF4wAPNgPjAG0AzABowAVhEAmEQHYAugDoATiQAmlDCQAUmgIYYMIjJUWKAlDzCbUYMEZNgApJzat2ABjAB+MHozys2Bg6+Jp8doqy5gBcPvqmInyRANzoAQRgJCZUNAxMLOyaHDHYlAC2AEaZ5qy8giLiYFJgckqq6lq6+jEAgiY6AJ4APCUVmdyGxorFZZVmFlY24Y7Oru5esX70lLgAFprh0Rvx-MnomDjp2XSMzGyWRWAjs9W1wmKSMgrKahoLlr49PpDJ5jCYmaajOY1MAAb2sNjAtCgln2k2WHGqrjAbnMMN88i2u1RJlMAF8wMp8MZsBtSQlZEJUKYUuggA

**Comment by kevinbarabash** [comment]
The problem is that `push` doesn't return an array like `concat` does.  Instead it returns the number of values that were pushed, in this case `1`.  Flow is doing the right reporting this as an error.

To fix the code you could use an array spread like so:
```js
const errMultiples = (x: number) => [3, 5, 2, 7].reduce((acc: Array<number>, curr: number) => (
  curr % x === 0 ? [...acc, curr] : acc), []);
```
