### ISSUE TITLE
Generic Type seems to `remember` previous usage?

### ISSUE THREAD

**Issue by philiiiiiipp** [facebook/flow#8051]
Flow version: all

## Expected behavior
Generic types should not remember previous usage?

## Actual behavior
It seems is if the previous usage of a generic in a type gets remembered.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0FAehAIFEA8BcCcCGBjWBncsAWBTc8dYBXeAO0wE8AHPAewDNxFx6jTUBLW8hpngIwBWOVMFjU8MBClgARAEKRSCCgBUJAHlUA+cAF5wACgCU+3QBIAwogA2NjcHDgNAJW2GTZ8C9N7dLgBpHcCtbew0AMXcAb3AAagBzQgUlFQAucAjwAF9fXQiA8B0g7QBuYKcnMQkoOCRUFOV4NQkARi1dA08-EOs7BydXd27-PO8gp1D+yJj4pLlFJooMrNyvAqLtEvLKyuBkG0Q0DABBAH1LQ+PwaOAASHnGlRMMtAQOUgSbivA7gmIyOAAORveAfBJAn7ZXZVbI-KoHI4YeQXK4YW4PZKLZ7GDKkIgAW34OHg312f0IJHIACYoTDwMA4fD6QzxDRvJSyOoaCd9L0whopPUFqlmtycBpzpckdptNV2S5OaRxfI+VN7EKZE8xZoUdLjrLmbtQBAAKpocGYXDgNCIAl4NkOgDuHGQeH4BEQAGs0AB+ACE4A4jAotCI4GQtAJ9uU4G4dCIsCDSadtHgPoZkdIbyYfKOFHYRlx4AACvAoxw0BLFQDlRITp1dCD3p9IVmc-w82gC8gixkyxWq64lSrG+BaSaOQATHD0D6W7AOmqp9MYX3yvA1qni86tNV9DV1LXYnU0dpStGG9tJxBnPcGfOFl6l8sEyvVkf1u9j5tg1vAfZuBzWAcBzB9uyfMZbicGxCHwUCiBsWAdgZJwCDQRCkwfJ1EA4G8TGCdDMIAOmQLBEHgE5YEMAAGYxCIQpC8xwvDwH4AiqjQxikwgWlsiAA

**Comment by mvitousek** [comment]
Simplified example https://flow.org/try/#0FAehAIFEA8BcCcCGBjWBncsAWBTc8dYBXeAO0wE8AHPAewDNxFx6jTUBLW8hpngIwBWOVMFjU8MBClgARAEKRSCCgBUJAHlUA+cAF5wAEgDCiADZmNwcOA0AlbQApHASn267bvR4A01owAK8LQ08OLqNFo+4ADkAOaECkoqMdrA2gDcwMDIZohoGACCAPrGeQXgAN7AAJAJcorK8BSuAFzgaAgcpHFV-jY1BMRksZ3w3XEx-eAAvjbz4MAz0zY55Rjypet9dYmNKm3gpEQAtvw48H0Lg4Qk5ABM03MLi8srL6viNOB2t2QROEK+igcCQqCSTTUmhKZXyaDSXzwv2GpAB8mBUjBDWSzQBGk2sIKaQ+C1AEAAqmgJphcB1ECc8IjMAB3DjIPD8AiIADWaAA-ABCcAcRgUWhEcDIWgnBnKcDcOhEWDC5XM2jwXmLKWkTpMYHgQ7Iu4AoHeUZdHpTbW6-j6w1-VESdFmx5AA

**Comment by SamChou19815** [comment]
This now works under `inference_mode=lti`
