### ISSUE TITLE
S => $Shape<S> is not assignable to S => $Shape<S>

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#8052]
Flow version: 0.106.2

https://flow.org/try/#0GYVwdgxgLglg9mABDAJgHgMoD4AUKCmATjAG74BciGiAvFogCQYAWAhgA76ZYCUl1dRiw5dsiAN4AoRIkL4oIQkgLEykgL5A
```
function id<S>(derive: S => $Shape<S>): S => $Shape<S> {
  return derive
}
```
> ```
> 2:   return derive            ^ Cannot return `derive` because `S` [1] is incompatible with `$Shape` of `S` [2] in the return value.
> References:
> 1: function id<S>(derive: S => $Shape<S>): S => $Shape<S> {
>                                       ^ [1]
> 1: function id<S>(derive: S => $Shape<S>): S => $Shape<S> {
>                                                        ^ [2]
> ```

Declaring a type helps as a workaround:
https://flow.org/try/#0C4TwDgpgBAIhBOBLAbhAPAZQHxQLxQzxwBIMALAQ0kywChaAzAVwDsBjYRAexakQBMaACn4IUEAFywxqGgEopcJLOxQA3rShR4EYE3i9RyiLQC+tIA
```
type Derive<S> = S => $Shape<S>

function id<S>(derive: Derive<S>): Derive<S> {
  return derive
}
```

> ```
> No errors!
> ```

**Comment by noppa** [comment]
Also works if you give `S` some kind of constraint

```javascript
function id<S: any>(derive: S => $Shape<S>): S => $Shape<S> {
  return derive
}
```

[Try](https://flow.org/try/#0GYVwdgxgLglg9mABDAJgHgMoC5EEMwCeAfABQoCmATjAG7k4aIC8RiAJBgBa4AO5mRAJQNmrDtz4DEAbwBQiRJXJQQlJBWp1ZAX1mzUJEoNGIS03DgCs2wYLMXrggHS4nUOADEYAD3IoSAEyCQA).

**Comment by gkz** [comment]
Works if you use the safe replacement `$Partial`: 
https://flow.org/try/#0GYVwdgxgLglg9mABDAJgHgMoD4AUKCmATjAG74BciGiAvFogCQAKAhobCwDaZYCUl1Oo1bsYXHogDeAKESJC+KCEJICxMtIC+QA

https://flow.org/en/docs/types/utilities/#toc-partial
