### ISSUE TITLE
Flow refines `any` type outside (and before) if statement

### ISSUE THREAD

**Issue by torjusb** [facebook/flow#8053]
Flow version: v0.106.3

## Expected behavior

An `any` type should stay `any` outside `if` statements.

## Actual behavior

Flow appears to refine an `any` type if it is used in an `if` statement, not just within the scope of the `if` but also outside it and before.

* Link to Try-Flow or Github repo:

Example 1 with generators (no error in Flow v0.102.0):
https://flow.org/try/#0MYewdgzgLgBAZiEMC8MAUATAhlApgORAHcAuGAER1wEoUA+dAbwCgYZs9CjmBfagbmbM4AVzDAoAS3AAqeIgBGWAE5pqZAOK4wuZThDKAPFjABPADQwAbiEkZLJ0wxZtQkWBwLEUMU5NwANhjotMgMOkQUVGqCbKy+-kHyIJhUXAJCruDQMGAiALYKuj5+gcFq9DAAjLFsdfEA9A0wyrj5IFaSYADmMFAAFpIQMJJw8JIAHrjDA7gwusoGlgoisET9pgD88aPoeYXFyEcwAAy0LjA8vMxAA

Example 2:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swBzAU3wDUBDGACgEoAuMW7ATzAG9UwATlUwDS2CkgAitfBWYBuMKgC+6XCQDO+MADcwAXnJU6jJvPRY8REmC0DC2Mgw1s7Dsk16Dho22FWobo4MOmbowMBgAEoUALZwOu5g+AAWhBpgUIQAHhQZqRRgFAICcAKohFBgIQb6hgAMnjzKQA

**Comment by TheHaff** [comment]
+1

**Comment by goodmind** [comment]
@panagosg7

**Comment by gkz** [comment]
I don't see any errors anymore in the latest version of Flow
