### ISSUE TITLE
Crash for \u2028 or \u2029 in a string

### ISSUE THREAD

**Issue by pvdz** [facebook/flow#8054]
Flow version:

I only tested online as I don't have internal access anymore ;)

astexplorer reports flow-0.106.2
https://astexplorer.net/#/gist/15eb31fbb1024faa6f42a4940d8beb4a/0c6265df81b125356765ef40144d7844d7eeb7dd

flow playground reports v0.106.3 (you'll have to use debug tools to trace the error, but the same error is thrown there as it is for astexplorer)
https://flow.org/try/#0BYSwFAlA3AUARICgI5SA

## Expected behavior

It should parse the following string, containing a `\u2028` character literal just fine:
```
" ";
```

## Actual behavior

Something error happened

Internal error: Offset_utils.Offset_lookup_failed(_, "Failure while looking up column. Index: 3. Length: 2.")

**Comment by avikchaudhuri** [comment]
Traced this back to 0.90 (0.89 was OK), and release notes seem to confirm: https://github.com/facebook/flow/releases/tag/v0.90.0

**Comment by SamChou19815** [comment]
Looks like this is no longer crasing.
