### ISSUE TITLE
flow refactor --rename doesn't work for type aliases

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#8059]
I ran `flow refactor src/lexer.js 74 9 --rename stat` and it outputs a list of locations within the file that should be changed.  Using the Flow plugin for VSCode I can rename the variable at location 74:9 to `stat`.  When I try the same thing with a type alias, `flow` doesn't return any locations to update and the VSCode plugin does nothing.

**Comment by SamChou19815** [comment]
Closing since `flow refactor` is no longer a subcommand.
