### ISSUE TITLE
`var x = x.y;` should be an error

### ISSUE THREAD

**Issue by danvk** [facebook/flow#806]
I would have expected Flow to flag this as an error:

``` javascript
var x = x.y;
```

`x` is undefined, so accessing a member should be an error. This sort of thing is usually an indication of a typo.

```
$ echo 'var x = x.y;' | flow check-contents
No errors!
```

This is with Flow 0.15.

**Comment by AgentME** [comment]
Related: https://github.com/facebook/flow/issues/693

**Comment by vkurchatkin** [comment]
Fixed in master
