### ISSUE TITLE
Flow (maybe?) unable to refine react-redux `connect` overload when related type is imported

### ISSUE THREAD

**Issue by loganfsmyth** [facebook/flow#8069]
Flow version: 0.107.0

I'm running into this with `react-redux` using the type definitions in `flow-typed`. This _may_ be related to https://github.com/facebook/flow/issues/7563 but it is hard to tell. I've also put together a small reproduction that I hope will help to speed this along.

With the example reproduction in https://github.com/loganfsmyth/__bug-flow-react-redux-connect, if you try to `connect` in certain cases, Flow will report an error unexpectedly. In the case of my reproduction, it seems to at a minimum happen when the component props reference a class that has been imported from another file. If the same class file is pasted directly into the `index.js` however, Flow reports no typechecking issues.

## Expected behavior

Flow should not error, just like if the class declaration were inside the `index.js` file.

## Actual behavior

Flow errors unexpectedly and with no clear way to resolve the issue.

* Link to Try-Flow or Github repo: https://github.com/loganfsmyth/__bug-flow-react-redux-connect

In this case, the error is
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ index.js:32:6

All branches are incompatible:
• Either a call signature declaring the expected parameter / return type is missing in DispatchProps [1] but exists
  in function type [2].
• Or a call signature declaring the expected parameter / return type is missing in DispatchProps [1] but exists in
  function type [3].

    index.js
[1] 22│ type DispatchProps = {|
    23│   doAction: () => void,
    24│ |};
      :
    29│   },
    30│   ({
    31│     doAction: () => {},
    32│   }: DispatchProps)
    33│ );
    34│

    simple-react-redux.js
[2]  6│   | ((dispatch: D, ownProps: OP) => DP)
[3]  7│   | ((dispatch: D, ownProps: OP) => (dispatch: D, ownProps: OP) => DP);



Found 1 error
```

**Comment by SamChou19815** [comment]
This issue is likely fixed a while ago.
