### ISSUE TITLE
Abstract class support

### ISSUE THREAD

**Issue by popham** [facebook/flow#807]
I don't see abstract classes on the roadmap.  Any chance of support under Flow?

I want a class that looks like so:

``` js
class ReaderA {
  // Imagine properties here.

  constructor(arena: Arena, depth: uint, isOrphan: boolean, segment: SomeBuffer) {
    if (depth > arena.maxDepth) {
      throw Error("Depth exceeded");
    }
    // Populate properties here.
  }

  // Pure virtual static.  This doesn't work.
  static _deref(arena: Arena, pointer: Datum, depth: uint): Reader;

  static _fieldGet<T>(context: Struct, offset: uint, defaultArena: Arena): T {
    var pointer = {
      segment: context._segment,
      position: context._pointersSection + offset
    };

    if (pointer.position < context._end && !isNull(pointer)) {
      return this._deref(context._arena, pointer, context._depth+1); // NG
    } else {
      return this._deref(defaultArena, defaultArena._root(), 0); // NG
    }
  }
  // ...
}
```

My current work-around, I think, is to extract `_fieldGet` to an external function, `fieldGet`.  I create a class and an interface:

``` js
class Reader {
  // Imagine properties here.

  constructor(arena: Arena, depth: uint, isOrphan: boolean, segment: SomeBuffer) {
    if (depth > arena.maxDepth) {
      throw Error("Depth exceeded");
    }
    // Populate properties here.
  }
}

interface ReaderI {
  static _deref(arena: Arena, pointer: Datum, depth: uint): Reader;
  static _fieldGet<T>(context: Struct, offset: uint, defaultArena: Arena): T;
}
```
- For all implementors of `ReaderI`, `_fieldGet` calls my extracted `fieldGet`.
- In places where I would have used the type `ReaderA`, I can use `Reader & ReaderI`.  That will be a useful type alias:  `type ReaderA = Reader & ReaderI`.

**Comment by popham** [comment]
To make this work, I've given each of my pure virtuals an implementation that always throws.  I think that Flow could manage this analogously without much data remodeling.

**Comment by popham** [comment]
I think that #452 could be generalized to cover abstract classes.  If class methods implement a `this` pseudoparameter for constraining the `this` magic reference, then my use case could be handled as:

```js
interface ReaderVirtuals {
  static _deref(arena: Arena, pointer: Datum, depth: uint): this;
  // I don't know the semantics of `this` well enough.
  // Do I need to reproduce the entirety of `Reader`'s interface here?
}

class Reader {
  constructor(arena: Arena, depth: uint, isOrphan: boolean, segment: SomeBuffer) {...}
  static _fieldGet(
      this: Class<this & ReaderVirtuals>, // `_fieldGet` can only be called on a
                                          // Reader extender that implements the
                                          // `ReaderVirtuals` interface.
      context: Struct,
      offset: uint, defaultArena: Arena
  ): this {
    var pointer = {
      segment: context._segment,
      position: context._pointersSection + offset
    };

    if (pointer.position < context._end && !isNull(pointer)) {
      return this._deref(context._arena, pointer, context._depth+1);
    } else {
      return this._deref(defaultArena, defaultArena._root(), 0);
    }
  }
  // ...
}
```

Traditional abstract classes are a special case of the above (`this: Class<this & Virtuals>` for all static members and `this: this & Virtuals` for all members).

**Comment by nmn** [comment]
Everything Abstract Classes provide from a type system point of view can also be done with Interfaces. (Support for `implements` landed recently).

Partial implementation of abstract classes wouldn't work since Flow isn't a compiler. So for that you'd need to use real classes.

**Comment by mbrowne** [comment]
If using interfaces to implement this, does that mean that something like the below boilerplate should be used:

    interface MyInterface {
        foo(): void;
        bar(): void;
    }

    class AbstractClass implements MyInterface {
        constructor() {
            if (Object.getPrototypeOf(this) === AbstractClass.prototype) {
                throw Error('AbstractClass should not be instantiated directly; write a subclass');
            }
            ...
        }
    
        foo() {
            throw Error('Not implemented');
        }
        
        bar() {
            console.log('default implementation of bar');
        }
    }

It would be a little inconvenient to have to write stubs for every method in the interface, so maybe it would be better not to have the abstract class implement the interface but only its subclasses:

    class AbstractClass {
        ...
    }
    
    class ConcreteClass implements MyInterface {
    }

Not sure if that's a good idea though...

**Comment by nmn** [comment]
Update. There's also `$Abstract` utility type in Flow that makes Abstract classes somewhat possible. Look up the lib typed for `React.Component` for more details. Super experimental right now, but it'll probably keep getting better since it's being used for React.

**Comment by Chaoste** [comment]
Here is an example for the usage of $Abstract: https://github.com/facebook/flow/issues/2464#issuecomment-248749163
