### ISSUE TITLE
Generic argument type breaks optional chaining

### ISSUE THREAD

**Issue by thers** [facebook/flow#8078]
```
type A<T: {} = {}> =
  | {| [key: string]: string |}
  | void;

type B =
  | {| [key: string]: string |}
  | void;

function testA(val: A<>) {
  return val?.['test']; // Unexpected error
}

function testA(val: B) {
  return val?.['test']; // No error
}
```

Flow version:
`v0.107.0`

## Expected behavior
No error

## Actual behavior
Error

* Link to Try-Flow or Github repo:
https://flow.org/try/#0C4TwDgpgBAggPAFQFxQN4F8oF43oHzYBQUUAPmuQNoDWEIKAzsAE4CWAdgOYC6jLHnMumJkoANwD2rACYBuQoVCQoAISIlyqKrXpQmbLrz38uQkeUkz5hAGYBXdgGNgrCeyjAITGAAoxAQwAbFHg8AEo0EWYIYDtmdwDAgH4AOkoAck8mdO55YVsHZ1d3LOBfRJQVCNQomLiEoNSM0py8kSA

**Comment by SamChou19815** [comment]
Now both work
