### ISSUE TITLE
Allow covariance in arrays and other complex types

### ISSUE THREAD

**Issue by chrisdevereux** [facebook/flow#808]
The following doesn't type check:

```
type Union = A | B;
type A = 'a';
type B = 'b';

function test(): Union[] {
  var array: A[] = ['a'];
  return array;
}
```

I checked also using Union as the value type for Set, also with class inheritance. In certain circumstances, flow seems to infer that the array should be typed `Union[]`. For example, if I do this, the typecheck passes:

```
function test(): Union[] {
  var value: A = 'a';
  return [value];
}
```

I also get a slightly confusing error message when I try to typecheck the first example:

```
5:10,12: string literal b
Expected string literal a, got b instead
4:10,12: string literal a
```

(v0.15.0)

**Comment by samwgoldman** [comment]
This is problematic in general because arrays are mutable.

```javascript
/* @flow */

type Union = A | B;
type A = 'a';
type B = 'b';

var as: A[] = ['a'];
var abs: Union[] = as; // expected error
abs.push('b'); // legal, but `as` is no longer `A[]`
```

I agree that the error message is confusing. It requires quite a bit of knowledge about how Flow works to understand what that error means.

**Comment by TrySound** [comment]
$ReadOnlyArray is available for along time
