### ISSUE TITLE
Optional property implements

### ISSUE THREAD

**Issue by goodmind** [facebook/flow#8080]
Flow version: 0.107.0

Originally from https://github.com/joarwilk/flowgen/issues/99

Related issue https://github.com/facebook/flow/issues/7474

## Expected behavior

`No errors`

## Actual behavior

```
6:   endpoints?: Array<string>;
                 ^ Cannot implement `A` [1] with `B` because undefined [2] is incompatible with array type [3] in property `endpoints`.
References:
5: declare class B implements A {
                              ^ [1]
6:   endpoints?: Array<string>;
                 ^ [2]
2:   endpoints?: Array<string>;
                 ^ [3]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYOwLgpgTgZghgYwgAgILIN4ChnIiAEwAcB7UMAZwH4AuNKKOATwB4KwpQBzAPgG4sAXxzIsBCAgA2cKCilwKFZACFkwALZFJEdfkppMI-MTLhqdVA2ZsO3fkKxA

**Comment by SamChou19815** [comment]
This was fixed
