### ISSUE TITLE
Object spread not work in the argument of the function.

### ISSUE THREAD

**Issue by HsuTing** [facebook/flow#8082]
Flow version: v0.107.0

## Expected behavior

No error.

## Actual behavior

Throw the error: 

```js
14:   const { command } = ctx.request.body;
              ^ property `command` is missing in mixed [1].
References:
3:     body: mixed,
             ^ [1]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAwg9gO2BAHsKBeKBvAUFKAJwgEcBXCAZ2AC4d8CoAjOAExDoFsBLFCVgDQMAvkOG5cAY0TUok4CjrwkqdFjwFi5KrXqNmbDjjlxOnAIYJWdAETJqNqKJFiA3BOkJZ9tVAAU8oqwiMhoAJSYAHx6Jl7o2CZmlqxOmHIKAHRaFNQZLOzuwq5AA

**Comment by jcready** [comment]
This is working as intended.

**Comment by HsuTing** [comment]
Why?
`ctx.request.body` is the type in `flow-typed`. How can I fix it without directly changing the `ctx.request.body`?

**Comment by jcready** [comment]
Because you cannot know for sure what that value will be. That's why it's set to `mixed`. You can use [refinements](https://flow.org/en/docs/lang/refinements/) to get from `mixed` to your desired type.

**Comment by HsuTing** [comment]
@jcready Thanks you! This is helpful, but I tried this:

```js
if (ctx.request.body instanceof Objet && ctx.request.body.command) {
  const { command } = ctx.request.body;
}
```

I got this:

```js
8:   if (ctx.request.body instanceof Objet && ctx.request.body.command) {
                                     ^ Cannot resolve name `Objet`.
```

However, I tried this code. This did not throw error with `flow`, but this can not work in `js`.

```js
if (ctx.request.body instanceof {} && ctx.request.body.command) {
  const { command } = ctx.request.body;
}
```

I am sorry to ask again, can you help me? How the best way to check the type?

**Comment by pascalduez** [comment]
@HsuTing ` s/Objet/Object`

**Comment by HsuTing** [comment]
My fault, I did not check the message. The question is this:

```js
const test = (ctx: Context) => {
  if (ctx.request.body instanceof Object && ctx.request.body.command) {
    const { command } = ctx.request.body;
  }
};

/**
14:   if (ctx.request.body instanceof Object && ctx.request.body.command) {
                                                ^ property `command` is missing in `Object` [1].
References:
14:   if (ctx.request.body instanceof Object && ctx.request.body.command) {
                                      ^ [1]
*/
```
@pascalduez Sorry 😅.

**Comment by kevinbarabash** [comment]
The following works:
```js
const test = (ctx: Context) => {
  if (ctx.request.body && ctx.request.body.command) {
    const { command } = ctx.request.body;
  }
};
```

**Comment by HsuTing** [comment]
Oh! Thank you @kevinbarabash .
