### ISSUE TITLE
Unbound generic in return position matches return value of String methods

### ISSUE THREAD

**Issue by lyleunderwood** [facebook/flow#8085]
Flow version: All

## Expected behavior

This should error:

```javascript
function identity<T>(value: T): T {
  if (typeof value === 'string') {
    return value.substr(0,0); // here
  }

  return value;
}
```

## Actual behavior

It does not error.

This, however, does:

```javascript
function identity2<T>(value: T): T {
  if (typeof value === 'string') {
    const emptyStr: string = value.substr(0,0); // cast it to string, and it errors
    return emptyStr;
  }

  return value;
}
```

* Link to Try-Flow or Github repo: ([Try](https://flow.org/try/#0GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKANwEMAbENALkXwEp79EBvAKEWWEWJwAOaOLwrU0iALzTEAcgDOUAE4wwAc1mN2XboggJFiNAFsBOAMrKpiMTQB08kACNFS4gAYANO8YBuRAD0AXqUMBAA1ogIiAAGJmbYlkoxiORgKIhQABYSghIw8ohKaAJwSlBoGeSFMa6qajE63MVQIEpI8RbKvjoAvhw6LW1Itmg9-RygkLDRqBhY2ABMBCSjLMwM2twwvPzYQiI2VDRSMgrK9Zpbuvpghp2JyvR16tajDs6uHt5+gcEQ1SgyCBUDgiBeak8qXSwKMSiUZXkTSKaFa7SMpi6Sh63AmzVRwyO4nGQA))

According to the core libdef, [`substr` returns `string`](https://github.com/facebook/flow/blob/6ed70e1dd72778a01f1f3a25db92bc2d717fb5e4/lib/core.js#L342). Obviously I would expect its return value to error in the same way that something cast to `string` does. The return value appears to be magical in some way.

This applies to all methods of `String` that with the return type `string` that I have tested, including `concat` and `slice`.

Just as a data point, [TS handles this case as I would expect](https://typescript-play.js.org/#code/GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKANwEMAbENALkXwEp79EBvAKEWWEWJwAOaOLwrU0iALzTEAcgDOUAE4wwAc1mN2XboggJFiNAFsBOAMrKpiMTQB08kACNFS4gAYANO8YBuHdxKaFAgSkgmZtiWSv7cAL4cOkEhYTZUNP5xQA).

**Comment by SamChou19815** [comment]
This now errors.
