### ISSUE TITLE
Using temporary variable to check existence

### ISSUE THREAD

**Issue by danny-does-stuff** [facebook/flow#8090]
Flow version: 0.107.0

Very simple reproduction shown in the [flow try](https://flow.org/try/#0GYVwdgxgLglg9mABAWwJ4DFwQBQAcCGATvsgFyID8AzlITGAOYCUiA3gFCKIQI2IxUACoTgA3GABMAphPIAjOHAA2U-EgC8iAIRaCxZJ0SGeYPoVVKAyrXoNyNOo0SaBwsZJmVEekonIByaWB8ECUof3YAXyA)

## Expected behavior
When using a temporary variable derived from a value to check the existence of that value, I expect type refinement to happen on the original value.

## Actual behavior
Checking a temporary variable derived from the variable in question does not refine the type of the original value.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0GYVwdgxgLglg9mABAWwJ4DFwQBQAcCGATvsgFyID8AzlITGAOYCUiA3gFCKIQI2IxUACoTgA3GABMAphPIAjOHAA2U-EgC8iAIRaCxZJ0SGeYPoVVKAyrXoNyNOo0SaBwsZJmVEekonIByaWB8ECUof3YAXyA

**Comment by dannyharding10** [comment]
Well, I ran into this exact issue and went to create a new issue. Little did I know some helpful user already made an issue for it 🤦‍♂ . Here's another flow try that shows the behavior

https://flow.org/try/#0CYUwxgNghgTiAEA3W8oC54H4DOAXGAlgHYDmAUKJLAsjPAEYaZECuAtvSDGWWAPZE8qAIJFgAIQz0+fCCChF4AXngBCVVHgAyLWtX0eBAGbwAFFFESAlPADeZePH6DcqAAqE2IDHkKllqGQAvmRAA

**Comment by SamChou19815** [comment]
Flow only supports type refinements in a limited set of syntactic forms.
