### ISSUE TITLE
Can't safely type ref for a functional component using `useImperativeHandle` (possible solution starting point)

### ISSUE THREAD

**Issue by jeffvandyke** [facebook/flow#8092]
Possible solution (doesn't work, needs refinement): Add new `React.GenericRef<T>` for `React.useImperativeHandle` and `React.forwardRef`

After exploring the different places ref types can show up in React types, and attempting to add workable types to a custom component that follows the `useImperativeHandle` example given on the [official React docs (link)](https://reactjs.org/docs/hooks-reference.html#useimperativehandle), It seems to me that a decent type for the `FancyInput` parameter `ref` would be a new `React.GenericRef<T>` defined as `type GenericRef<T> = { current: T | null, ... } | ((instance: T | null) => mixed) | null | void`, or something similar (obviously translated to `declare type` style).

The name `GenericRef` seems natural given that `React.Ref` is similar, only also takes `number | string`, and the instance/current `T` type needs to be `React$ElementType`, which `ref`-s given to `useImperativeHandle` do not and cannot uphold (by default, without `forwardRef`, functional components do not have instances).

Open for discussion; this might make it possible to safely use imperative handles without needing refs to be subclasses of `React.ElementType<T>`.

## Missing/Incorrect APIs
- React.useImperativeHandle
- React.forwardRef
- React type reference

## Relevant documentation
<https://flow.org/en/docs/react/types/>

**Comment by ravindasenarath** [comment]
I have the same question. For a functional component I'm getting following error.

`
     src/apps/orders/ConfirmActionModal.js
     119│   )
     120│ }
     121│
 [2] 122│ export default forwardRef(ConfirmActionModal)
     123│

     /tmp/flow/flowlib_2ad08bac/react.js
 [1] 289│   declare export function forwardRef<Config, Instance>(
     290│     render: (
     291│       props: Config,
     292│       ref: {current: null | Instance} | ((null | Instance) => mixed),
     293│     ) => React$Node,
     294│   ): React$AbstractComponent<Config, Instance>;

`

Wondering what is the return type for functional component.

My stackoverflow [question](https://stackoverflow.com/questions/62993543/ambiguous-error-from-flow-type-on-useimperativehandle-which-cannot-resolve) on this

**Comment by SamChou19815** [comment]
Yeah refinement will be needed.
