### ISSUE TITLE
Broken Error

### ISSUE THREAD

**Issue by pizzarob** [facebook/flow#8094]
What is this error? It does not give any indication to what `T` is. I am hovering over the `.sort` function

![image](https://user-images.githubusercontent.com/5282495/65192441-f166b600-da2b-11e9-9204-6568b611b525.png)

**Comment by goodmind** [comment]
it's probably sort type argument

**Comment by goodmind** [comment]
This looks like bug to me
https://flow.org/try/#0PTAEAEDMBsHsHcBQiCmAPADrATgF1AMawB2AzvgJ6wBcoAgttgIYUA8xArgLYBGK2APlABeUAG0AjABpQAJgC6AbmToseQiXKhIsWCNBUAdKRy4AFGYCUtTr34ihAb0ShQ2FLg7ZioCcoC+lspAA
```js
// @flow

export const yo: Array<number> = [1, 2];

export const foo = yo.sort((): number => {
  return 1;
});
```

**Comment by gkz** [comment]
Can't reproduce the error anymore
