### ISSUE TITLE
Add support for ES6 symbol types

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#810]
Code along this lines causes an error:

``` js
Class List {
  $$typeof: symbol;
  constructor() {
     this.$$typeof = Symbol.for('mylib/symbol')
  }
}
```

**Comment by Gozala** [comment]
I did not quite figured out how to add a primitive type support and at this point I don't have enough time to digg into to do it. So I have created this libdef for my use:

```js
// See https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol
type symbol = Symbol;
declare class Symbol {
  static (value?:any): symbol;
  static for(key:string): symbol;
  static keyFor(symbol:symbol): string;
  toString(): string;
  valueOf(): symbol;
  // Well-known symbols
  static iterator: symbol;
  static match: symbol;
  static replace: symbol;
  static search: symbol;
  static split: symbol;
  static hasInstance: symbol;
  static isConcatSpreadable: symbol;
  static unscopables: symbol;
  static species: symbol;
  static toPrimitive: symbol;
  static toStringTag: symbol;
}
```

I'm happy to send a pull to include it into `core.js` until proper support is built.

**Comment by eranimo** [comment]
Has Symbol.iterator support been implemented?

**Comment by donkeybonks** [comment]
This would be really good to have because it is a common use-case with React Redux to use symbols for action namespacing (and slightly better performance, too).

**Comment by yasserhussain1110** [comment]
yo

**Comment by kevinSuttle** [comment]
https://github.com/facebook/flow/blob/master/lib/core.js#L84 ?

**Comment by gajus** [comment]
Is there any plan to support Symbols?

https://flow.org/try/#0MYewdgzgLgBAYiEBlAngWwEYgDYwLwyqY4AUA5HAPKVkCUA3AFCiSwBCAhgE5Fa4G9SZNgEEASnSaMoKAA4BTGJwBeAFTmKCAbwA+jAJABqGQoBcME-JAAzeIkHYANIxiuYhgG4dsAV3kBGc2guAEswAHNGHQBfGB0YXQNjDXNLGyVuB2c3dy9feQAmczAfTHkuKOipFmgYDG58GBJ65XMVdQVafAA+BKrGRnquEi0DS3MEZHQ+bJh9PL8imH9GaIYgA

Currently `typeof` construct is useless, and symbol cannot be used as a literal value.

**Comment by SamChou19815** [comment]
Symbols support to be supported
