### ISSUE TITLE
Bug and/or bad error reporting regarding enum type unification

### ISSUE THREAD

**Issue by mpcsh** [facebook/flow#8103]
Flow version: 0.108.0

## Expected behavior
It's tough to say what should be expected here. I think a good solve would be either more accurate error reporting (it's currently difficult to localize the source of the problem), or no error at all.

## Actual behavior
This is the result of a couple-hour-long debugging session at work, that we feel could have been less painful. I have pared down the issue to a minimal example that illustrates the problem.

Consider the following type definitions:
```js
type Red = "Hearts" | "Diamonds";
type Black = "Clubs" | "Spades";

type Deck = {|
  red: Array<Red>,
  black: Array<Black>
|};
```

And the following utility function:
```js
import React from "react";

const renderDeckByColor = (deck, color) => deck[color].map(card => <span>{card}</span>);
```

This function takes a deck and a color, and renders all the cards of that color in the deck a list of `span`s. Pretty simple so far.

Now, consider the following `Deck`:
```js
const deck: Deck = {
  red: ["Hearts", "Diamonds", "Diamonds"],
  black: ["Clubs", "Clubs", "Spades"]
};
```

Again, no problems here. So let's try rendering the deck by color:
```js
const redDeck = renderDeckByColor(deck, "red");
```

No problems... yet. What if we also want the black cards? When we add the following line, `flow` suddenly vomits:
```js
const blackDeck = renderDeckByColor(deck, "black");
```
```
    13: const renderDeckByColor = (deck, color) => deck[color].map(card => <span>{card}</span>);
                                                   ^ Cannot instantiate array type because enum [1] is incompatible with string literal `Diamonds` [2].
        References:
        10:   black: Array<Black>
                           ^ [1]
        9:   red: Array<Red>,
                        ^ [2]
    13: const renderDeckByColor = (deck, color) => deck[color].map(card => <span>{card}</span>);
                                                   ^ Cannot instantiate array type because enum [1] is incompatible with string literal `Hearts` [2].
        References:
        10:   black: Array<Black>
                           ^ [1]
        9:   red: Array<Red>,
                        ^ [2]
    13: const renderDeckByColor = (deck, color) => deck[color].map(card => <span>{card}</span>);
                                                   ^ Cannot instantiate array type because string literal `Clubs` [1] is incompatible with enum [2].
        References:
        10:   black: Array<Black>
                           ^ [1]
        9:   red: Array<Red>,
                        ^ [2]
    13: const renderDeckByColor = (deck, color) => deck[color].map(card => <span>{card}</span>);
                                                   ^ Cannot instantiate array type because string literal `Spades` [1] is incompatible with enum [2].
        References:
        10:   black: Array<Black>
                           ^ [1]
        9:   red: Array<Red>,
                        ^ [2]
```

The big problem here is that the fix (which we found through essentially educated trial-and-error) is not in the slightest bit obvious from reported errors. All we had to do was simply say `color: string` in the arguments to `renderDeckByColor`. You can try it out in the try-flow link below and watch the error disappear.

As discussed above, I'm not sure exactly how this *should* behave. I don't fully understand why this is a type error in the first place. But, if this is a legitimate error, I feel there has to be a better way to report it.

Thanks for reading this wall of text!

* [try-flow link here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAIn0pqYG51CBPHM0mQAmYALzMAEpSIBnJmAA+zACIYKWOADshcrr35gAQjGoBrMcwDCMAK4AjOYuYBlHBSFld3PgOVkq5uIA3gqoYGCsQgBcYACC+PgUPAA85EIAfAA0YWB2JgEx8YkpxmbpqAoAvlyoVFoyxKzaZPh+AYY8lnDw+BYAFB4BmWB1PQCUYulgg6YA2qMEALoAdFgUOH1UFPgiolPJMm6a6UFbO5XJwIcUx2M1dZoN0-6mMW2BYEE5kTGzTFLbQhyYZMVTqLQ6JggsEabRyRbZcJ5My-JjWezAqy2BxQlxuDzw1DVdAPJ6Rd4WJoeVovDpdHoDF4gyJMO61erEZEBCniKktd507oERlDZhc0ysjhAA)

**Comment by goodmind** [comment]
@jbrown215 is this $ElementType bug?

**Comment by thehogfather** [comment]
@mpcsh FYI the fix you describe makes the errors disappear by implicitly returning `any` for the result type of the function. I would be cautious in doing that.

**Comment by mpcsh** [comment]
@thehogfather this doesn't seem - to me - to be related to the result type. Could you elaborate a little more?

**Comment by thehogfather** [comment]
> The big problem here is that the fix (which we found through essentially educated trial-and-error) is not in the slightest bit obvious from reported errors. All we had to do was simply say color: string in the arguments to renderDeckByColor. You can try it out in the try-flow link below and watch the error disappear.

@mpcsh my comments were pointing out that the 'fix' you mention here i.e., setting `color: string` makes the error disappear because the return type of the `renderDeckByColor` becomes `any` after that change. See [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAIn0pqYG51CBPHM0mQAmYALzMAEpSIBnJmAA+zACIYKWOADshcrr35gAQjGoBrMcwDCMAK4AjOYuYBlHBSFld3PgOVkq5uIA3gqoYGCsQgBcYACC+PgUPAA85EIAfAA0YWB2JgEx8YkpxmbpqAoAvlyoVFoyxKzaZPh+AYY8lnDw+BYAFB4BmWB1PVEN+BiaAOYAlGLpYIOmANqjBAC6AHRYFDh9VBT4IqKLyTJumulBh8eVycAXFFezNXWaDUv+pjFtgWBBHKRGIrJhSI6EOTDJiqdRaHRMaGwjTaOQbbLhPJmEFMaz2KFWWwOREuNweNGoarod6fSJ-CxNDytb4dLo9AbfaGRJivWr1YhYgL08SMlp-VndAgcobMQWmHkcIA) for an example - put your cursor on `redDeck` in line 20 and look at the bottom of the page to see the inferred type.

**Comment by mpcsh** [comment]
Woah! That is very surprising to me. I think this is simply a case of me not understanding flow well enough. Is this behavior documented somewhere?
