### ISSUE TITLE
Flow does correctly handle default function parameters on nested objects

### ISSUE THREAD

**Issue by grantsheppard** [facebook/flow#8104]
Flow version: 0.108.0

## Expected behavior

When using default function parameters to default nested object values, Flow should correctly enforce the relevant types.  For example:
```js
/* @flow */
type Args = {
  dependencies?: {
  	logger: (*) => void
  }
}

function defaultLogger(message: string) {
  console.log(message)
}

function someFunction({ dependencies: { logger = defaultLogger } = {} }: Args) {
  logger(1) // should be flagged as an error but is not (passing a number instead of a string)
}
```

## Actual behavior

The above does not generate a Flow error. Defaulting the values inside of the function does generate an error, ie:
```js
/* @flow */
type Args = {
  dependencies?: {
  	logger: (*) => void
  }
}

function consoleLogger(message: string) {
  console.log(message)
}

function someFunction(args: Args) {
  const { dependencies: { logger = consoleLogger } = {} } = args;
  logger(1)
}
```

Try Flow link [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCCATgOYDOYAvGAN6phgAmueAds6wMYCWuZA-AC5a9MAEh4JEriLCAFCACUVAHxgAbnG6NRAX1T7UUAK5d03OKzCdLZODFwAZOFJlyAtnzIBDacLLoRNysJMp0DDasdg4AdJIeXr64igaoqMDAYACSAHIAwgDyAEpFAKJ5ACrCjHB8YKxw6GCwvmDeVjJEcERgctjeZGTBJG31xu4ARjJtFN5gAUEhKSZmFlbMUN7GMOhkWazEJOO4rLtyNEwsJxw8fMIXktI91JHRTi5PYLpUtN+6wocyGFRI83ABGFKGDJgQolcpVZowXyzDpELo9PoDIYhUascZTHoDUYLYbLUyccyWS6bba7fYAMXJlNYcm8pDIAPZwIitiaF2YbBuvA5tDAoOe1ls9nerh632oND+PzZ5AA3CCPuDIWkgA) with both examples.

**Comment by thehogfather** [comment]
@grantsheppard the Existential type `*` has been deprecated - see [here](https://flow.org/en/docs/types/utilities/#existential-type--). I'd specify your function type explicitly if you can. For instance [this](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCCATgOYDOYAvGAN6phgAmueAds6wMYCWuZA-AC5a9MAEh4JEriLCAFGXRFurEgEoqAPjAA3ON0aiAvqhOooAVy7pucVmE52ycGLgAycKTLkBbPmQBDaWFFZVUNOgZHVmdXADpJX38g3DVTVFRgYDAASQA5AGEAeQAlEoBRAoAVYUY4PjBWOHQwWCCwAPsZIjgiMDlsALIyFRIOxosfACMZDooAsFDRtMtrW3tmKACLGHQyHNZiEkncVj25GiYWU44ePmFLyWk+6mjY909nsCMqWh+jYRHMgRURPbwARjSZiyYGKZUqNVaMCC8y6RB6fQGQxGqnGrEmMz6Q3GS3C5isnBsdiuWx2ewOADEKVTWHIAqQyICOSCok4WpdmGxbrxObQwGCXg4nC4Pl4+j9qDR-r92eQANygz4QqEZIA) errors as expected
