### ISSUE TITLE
Optional chaining: inconsistent behavior

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8106]
Hello! 👋 I found an issue and I don't know how to explain it (potential bug). I know optional chaining is not fully implemented (https://github.com/facebook/flow/issues/6613) but this seems to be different issue (?). Look at the following code:

```js
// @flow strict

const obj: ?{ field?: ?string } = null;

function variant1() {
  if (obj == null || obj.field == null) {
    return null;
  }

  // Doesn't fail, why?
  // See: https://mrtnzlml.com/docs/javascript#dangerous-getters
  const value: string = obj.field;
}

function variant2() {
  if (obj?.field == null) {
    return null;
  }

  // You could fix it with this:
  // const field = obj?.field;
  // if (field == null) {
  //   return null;
  // }

  // Fails, why? How is it different from the first variant?
  const value: string = obj.field;
}
```

Both variants seem to be doing the same but they behave differently. The first variant fails but I always considered it to be valid because of how getters can be dangerous, see: https://mrtnzlml.com/docs/javascript#dangerous-getters

But I'd expect that the first variant would fail for the same reason but it doesn't. Why is it behave differently and what is the actual explanation here?

Thank you very much for having a look. :)

**Comment by TrySound** [comment]
This already asked before here https://github.com/facebook/flow/issues/6613

**Comment by mrtnzlml** [comment]
So is it the same issue after all? I am closing this one then. I really wasn't sure it's the same problem. Thanks! :)
