### ISSUE TITLE
scrollTo is missing in HTMLElement

### ISSUE THREAD

**Issue by BrunoQuaresma** [facebook/flow#8107]
Code:
```
const content = document.querySelector('#content')
if (content) content.scrollTo(0, 0)
```

Flow error:
```
Cannot call `content.scrollTo` because property `scrollTo` is missing in  `HTMLElement` [1].Flow(InferError)
dom.js(1036, 36): [1] `HTMLElement`
```

VSCode Print:
<img width="926" alt="Screen Shot 2019-10-01 at 11 20 57" src="https://user-images.githubusercontent.com/3165839/65970809-8f4f7d00-e43d-11e9-82db-ab2a7f2c5bfc.png">

**Comment by danieltodonnell** [comment]
Tracked in https://faunadb.atlassian.net/browse/CON-607

**Comment by Jeffrang** [comment]
I m facing this issue as well, any idea on when this will be worked on?

**Comment by Brianzchen** [comment]
This property does exist in `HTMLElement`, but not `Element` in the current version, tested on v0.132.0.

If anyone's coming across this and finds an issue, check that you have refined the type to `HTMLElement` in the following way.
```
const content = document.querySelector('#content');
if (content instanceof HTMLElement) {
  content.scrollTo(0, 0);
}
```
