### ISSUE TITLE
Type parameter any-fied after passed to function type

### ISSUE THREAD

**Issue by Ashoat** [facebook/flow#8110]
Flow version: 108.0

[Try Flow](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwEogI4FcTIBd4BvAKHngCNoALALnkJgEsA7AcwG5SBfU0ggE8ADggBiOVmAA8mLAzl5CAPngBeeAAo48jNgCU61QDcA9s2DdSoJHETRUGUzgIgYJcvBzIQs7AuwlAmVNADNJMAYJKT8sZX0GMwtuPmtwaDtjWHgYZ1cYBTy3K1yXNwA6bxBNbX8qU1MIQzVVYh59blL8yp8anQYmNnZm1vbOopge6trdYgAfOfajEjHSLoqqvrrieBpmAYIWDngllpWOtYmprdmqWgOj9hOR8-Gyyc2Zhh3qKHp4Vg4AC2lDcz2WbQu6w+vS+JDuf2+Cx44LOkM4QA)

Apologies if the explanation seems ambiguous. I'm working on updating Express's libdef to avoid the use of `$Subtype`, and am having trouble due to this.

## Expected behavior

All of the bottom statements should error

## Actual behavior

No errors

**Comment by thehogfather** [comment]
@Ashoat try [this - flow try](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwEogI4FcTIBd4BvAKHngCNoALALnkJgEsA7AcwG5SBfU0ggE8ADggBiOVmHgBeeAB5MWBkryEAfAAo4yjNgCUs9fABuAe2bBupUEjiJoqDGZwEQMEuXg5kITQDNJMAYJKX0Gc0tuPhtwaHsTWHgYFzcYFVT3axTXdwA6Hz9tbAZKMzMIQxljYh59bhy0gt9NYt0mNnYqmrqGzJhmop0GYgAfUbqjEl7SRvzC1uGSeBpmBg6OeEnq6frZ-sHFkuXqKHpGAhZN7Z69uYGFtpGqWgZWHABbSnct7t2+3IPFpPE6vEjjHi-Ka1epAA)


```js
declare class Request {
  blah: string;
}

type Func = <Req: Request>(req: Req) => void;

declare class Router {
  use(func: Func): void;
}

declare var router: Router;

router.use((req: bool) => {});
router.use((req: string) => {});
router.use((req: {||}) => {});
router.use((req: { hi: string }) => {});
router.use((req: { blah: string }) => {});
router.use((req: { blah: number }) => {});
router.use((req: { blah: {||} }) => {});
```

**Comment by Ashoat** [comment]
Thanks, that seems to work! I ended up taking a different approach while typing Express, so I'm not 100% sure if that would have worked. (In our case, the function is a union of functions, so we'd have to parameterize each of the union members separately, which might make Flow struggle to match variants correctly.) Either way - I'll close this issue out now since it's no longer relevant to me. Appreciate the help!!
