### ISSUE TITLE
Simple example with inexact object doesn't properly type check

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#8112]
Flow version: 0.97 up to latest, maybe this is also happening in earlier versions.

## Expected behavior

This should be an error:

```
var obj1: { foo: string } = {};

obj1.foo.toString(); 
```

## Actual behavior

The previous example doesn't cause any errors in Flow.

* Link to Try-Flow or Github repo: https://flow.org/try/#0G4QwTgBA9gRgVgRgFwQN4QGZSigzgFzAEsA7AcwgF8IBeNSgbgCgnZEA6LKd-KAZUKkyACgCUDIA

**Comment by SamChou19815** [comment]
This now correctly errors.
