### ISSUE TITLE
Flow does not type check output when using spreading of generic type

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#8113]
Flow version: 0.97 onwards (at least)

## Expected behavior

The implementation of `blah` should cause an error

```
type Base = {|
  a?: string,
  b: string
|};

type Props<A> = {|
  ...Base,
  ...A
|};

function blah<A>(a: A): Props<A> {
  return {
    foo: 1, // Commenting this also type checks for Flow, even though b is a required field in Props<A>
    ...a
  };
}

const a = blah({ qwe: 1 });

console.log(a.b)
```

## Actual behavior

The code above does not cause any errors with Flow.

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAQghgZ2gXigbwD4CgpTgfgC4oFgAnASwDsBzAGhygCNjTLasMBfAbiy1CQoABTIB7MAgA8AQQB8UVJkYA6NfCQNcalTM69+AMwCuVAMbAKYqswA2cABay5ACjjEZASmKiJ0+eiMZBDAxmQ2aIwAkIZiYsQAjFq4UDpwjAZc-GbWpHiKdo4uaFAAjgDuEIlQXJ58WDlUCGK2ECq2YjRuKkyeQA

**Comment by panagosg7** [comment]
This is a Flow error as of v0.111.0.
