### ISSUE TITLE
delete check too eager?

### ISSUE THREAD

**Issue by villesau** [facebook/flow#8115]
Flow version: 0.109.0

## Expected behavior

No error

## Actual behaviour

Following code:

```
/* @flow */

const ob1 = { a: 1 };
const { ...ob2 } = ob1;
delete ob2.a;
```

Gives following error:

```
5: delete ob2.a;
          ^ Cannot delete `ob2.a` because undefined [1] is incompatible with number [2].
References:
5: delete ob2.a;
   ^ [1]
3: const ob1 = { a: 1 };
                    ^ [2]
```

repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzDgCMBGMAXjAG8wBDALjHIF8BuTHAmsAOn5IAmMC0pEyHACYBTGNPzTxg3nTZA

In many many cases this is valid way of reducing the properties of an object that is then passed forward and causes unnecessary friction when the intention is clear. I saw multiple similar cases in our code base. It's of course debatable how Flow should work in this case.

**Comment by villesau** [comment]
The above can be worked around by this:

```
/* @flow */

const ob1 = { a: 1 };
const { a, ...ob2 } = ob1;
```

Which is essentially equal to above, but often times linter lints against this since `a` would be unused variable.

**Comment by Brianzchen** [comment]
I don't think this is a bug, `ob1` is actually inferred to `{| a: number |}`. When you spread that into `ob2`, it also retains the same type as `ob1`.

If in `ob2` you plan to optionally have `a` then you can add refine the type as you spread like so
[try-flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwDyARmALxgDeYAhgPwBcYAdgK4C2RuATmAL6qoAxnCYBndGDhEAjGUo1Gs3gG4hI8fIB02qQCY+jYnKnTVAE1wxc6fHs3VlQA)
