### ISSUE TITLE
Generics restricted to union types don't allow returning of refined subtypes

### ISSUE THREAD

**Issue by Mr-Wallet** [facebook/flow#8119]
This is particularly a problem in any function that needs to return a duplicated object of the input type. For example if I want to have a single function that takes any of `A|B|...|N` and return exactly the same type, I don't see any way to make its type accurately checked without "tricking" Flow using a ridiculous level of boilerplate (and probably accidentally removing some of the type safety).

This doesn't work at all: [Try Flow](https://flow.org/try/#0C4TwDgpgBAagjFAvFA3lUkBcUDkA3OHKAXwG4AoDaGAJiVXXAm3xqLPPIDMBXAOwDGwAJYB7PlAC2IXoIA8AFWzwAPrQB8ACgCG2BQEo9qclCjCuUHQDoqSRMnyF9x06YBOEYDzcS0VFgTsFKbEUBAANgDO0Cgmrh5ePgz+uHhsJMEk5MRAA)
```
type V1 = { type: 'v1' };
type V2 = { type: 'v2' };

function myfunc<T: V1|V2>(a: T): T {
  if (a.type === 'v1') {
    return { type: 'v1' };
  } else {
    return { type: 'v2' };
  }
}
```

Flow reports that the return values are incompatible with `T`. I've played around with type casting and use of the `+` covariant annotation, but nothing seems to help. The fundamental problem is that I can't find any way to assure flow that I've proven what subtype of `T` I'm dealing with at runtime and can guarantee that I'm returning the same type.

**Comment by SamChou19815** [comment]
This is an expected limitation.
