### ISSUE TITLE
Incorrect result for $Call type with function that maps to object

### ISSUE THREAD

**Issue by anderco** [facebook/flow#8126]
Flow version: 0.109.0

Consider the following example:
```js
type Call = $Call<<T>(T) => {|prop: T|}, string>;
({prop: 10}: Call); // <--- No error?
```
## Expected behavior

The type `Call` would be equivalent to `{|prop: string|}` and the cast would fail with
```
({prop: 10}: Call); // <--- No error?
           ^ Cannot cast object literal to `Call` because number [1] is incompatible with string [2] in property `prop`.
```
## Actual behavior

No error. Flow adds `number` to the type of `prop`:

```
$ flow type-at-pos --evaluate-type-destructors types.js 4 6
type Call = {|prop: (number | string)|}
```

* [Example at TryFlow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAKATnDmALxgDeAPjqTgFxgDOGxAlgHYDmtAXwDcmXAQDCAQxgxKYACRSZAHmUAVAHwAKNQEpKGmvUYs1ggDRsOPXhpGot1BmRYByOAGtXAliTK6hMGBgMAB5DwcnEzAARgAGHyJGAKDgeQBRAA98AGMMdOJSYnRHZ2Ywdy9EpRgU4LCI0uj46ulawPrlAFoesAA5ODA8QrhiAH5UMCnpmdm5+bBJheWVsCA)

**Comment by SamChou19815** [comment]
This now errors with `inference_mode=lti` on
