### ISSUE TITLE
Property assignment on object with null prototype fails

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#813]
Flow currently does not typecheks following code snippet:

``` js
/* @flow */
export var html = Object.create(null);

["a","abbr","address"].forEach(tagName => {
  html[tagName] = (properties, children) =>
    ({tagName, properties, children})
});
```

producing following error:

``` js
/Users/gozala/Projects/reflex/src/core.js:4:1,7:2: call of method forEach
Error:
/Users/gozala/Projects/reflex/src/core.js:4:2,4: property `a`
Property not found in possibly null value
/Users/gozala/Projects/reflex/src/core.js:2:33,36: null

/Users/gozala/Projects/reflex/src/core.js:4:1,7:2: call of method forEach
Error:
/Users/gozala/Projects/reflex/src/core.js:4:6,11: property `abbr`
Property not found in possibly null value
/Users/gozala/Projects/reflex/src/core.js:2:33,36: null

/Users/gozala/Projects/reflex/src/core.js:4:1,7:2: call of method forEach
Error:
/Users/gozala/Projects/reflex/src/core.js:4:13,21: property `address`
Property not found in possibly null value
/Users/gozala/Projects/reflex/src/core.js:2:33,36: null
```

**Comment by samwgoldman** [comment]
Simpler repro:

```javascript
/* @flow */
let o = Object.create(null);
o.p = null;
```

```
test.js:4
  4: o.p = null;
       ^ property `p`. Property not found in possibly null value
  3: let o = Object.create(null);
                           ^^^^ null
```

**Comment by danielo515** [comment]
This is a very old issue. There is no workaround ? There is no fix?

**Comment by bvaughn** [comment]
This form also errors:
```js
var foo = Object.create(null, {
  bar: 1
});
```
```
1: var foo = Object.create(null, {
             ^ .bar of Object.create. Property not found in
2:   bar: 1
          ^ Number
```

You can work around this like so:
```js
var foo = Object.create(null, ({
  bar: 1
} : any));
```

You can work around the example @samwgoldman pasted like so:
```js
var foo = (Object.create(null) : Object);
foo.bar = true;
```

**Comment by qm3ster** [comment]
You could always just do this :rofl: 
```js
const known: {[Coords]: number} = /* :: {} // */ Object.create(null)
```
(it actually works)

**Comment by clintwood** [comment]
@qm3ster, can you explain why this works? Is it an OCaml thing? :see_no_evil:

**Comment by qm3ster** [comment]
@clintwood this dark magic is using flow's [Comment Syntax](https://flow.org/en/docs/types/comments/).
But, unlike normal use to write types in a file that can be interpreted without preprocessing, here it actually pretends that your javascript is different, and the compiler is none the wiser.
It's definitely a dirty hack.

But the point is, this is what javascript sees:
```js
const known = Object.create(null)
```
and this is what flow sees:
```ts
const known: {[Coords]: number} = {} || Object.create(null)
```
which since `{}` is always truthy, is equivalent to
```ts
 const known: {[Coords]: number} = {}
```

---------

Also, my news feed today:
![image](https://user-images.githubusercontent.com/10551234/37028840-1bfb5932-213e-11e8-83d0-a94ea4fae7d2.png)

--------

Also, there's no flow highlighter, only `ts`, and that's racist.

**Comment by Gozala** [comment]
It is also possible to do following:

```js
const known: {[Coords]: number} = (Object.create(null):Object)
```

I'm not entirely sure why flow allows to cast it to Object.

**Comment by qm3ster** [comment]
1) That's not as funny
2) That will show as decreased coverage
