### ISSUE TITLE
Optional chaining gets confused by `| void` or `| null` inside parameterized type

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#8132]
Given the following code:
```
type Foo = {
    bar: ?{
      baz: ?string,
    },
};

type OrVoid<T> = T | void;

declare var fooOrVoid: OrVoid<Foo>;
console.log(fooOrVoid?.bar?.baz);
            
declare var fooOrVoid2: Foo | void;
console.log(fooOrVoid2?.bar?.baz);
```

There should be no errors.

Currently there is an error in `console.log(fooOrVoid?.bar?.baz);` which uses the `OrVoid` parameterized type.  I ran across this when trying to use optional chaining with react-apollo.

https://flow.org/try/#0C4TwDgpgBAYg9nKBeKBvAUFLUBGBDAJwC4oB+DbbfALxNIGdgCBLAOwHMAaTbAX294BudOlCQoAeQIA1OMwAmAHgAqAPmRRlUAD5QAbnPnD08iAGMANoWh7CUAGYIpshSWeHF8OKuFm4rejgLCAA6Czh2AApHOHcFUhD8AgSaAEphSkzsE3MrAhs7GLj5ACYSLx19Q19-QOCwiOinGUMSlMJ26nT0IA

**Comment by SamChou19815** [comment]
This seems to be fixed now
