### ISSUE TITLE
Improve $Compose helper

### ISSUE THREAD

**Issue by moroine** [facebook/flow#8137]
## Proposal

I worked a bit on flow-typed definitions, and had troubles to type [ramda.pipe](https://ramdajs.com/docs/#pipe) function. 

I'm trying to remove `*` usage from the definition, mainly around Curry. 

Currently we have:

https://github.com/flow-typed/flow-typed/blob/89b0d35e3ad239b51762faef6478ec5881504f52/definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js#L33-L41

```typescript
  declare type __CurriedFunction1<A, R, AA: A> = (...r: [AA]) => R;
  declare type CurriedFunction1<A, R> = __CurriedFunction1<A, R, *>;


  declare type __CurriedFunction2<A, B, R, AA: A, BB: B> = (
    ((...r: [AA]) => CurriedFunction1<BB, R>) &
    ((...r: [$npm$ramda$Placeholder, BB]) => CurriedFunction1<AA, R>) &
    ((...r: [AA, BB]) => R)
  );
  declare type CurriedFunction2<A, B, R> = __CurriedFunction2<A, B, R, *, *>;
```

I manage to make it works with the current definition:

https://github.com/moroine/flow-typed/blob/1897df81e66e43c278e092ac051f857b128389da/definitions/npm/ramda_v0.26.x/flow_v0.104.x-/ramda_v0.26.x.js#L61-L67

```typescript
  declare type CurriedFunction1<A, R> = (...r: [A & A]) => R;


  declare type CurriedFunction2<A, B, R> = (
    ((...r: [A]) => CurriedFunction1<B, R>) &
    ((...r: [A, B]) => R) &
    ((...r: [$npm$ramda$Placeholder, B]) => CurriedFunction1<A, R>)
  );
```

Unfortunately, this causes new errors around `pipe` definition... 

The issue here is we can't use `$Compose` & `$ComposeReverse` as they create unary function but ramda will pass all given parameters to the first function.

$Compose & $ComposeReverse were introduced by https://github.com/facebook/flow/commit/ab9bf44c725efd2ed6d7e1e957c5566b6eb6f688

Here we have different usage: 
- Library returning only unary:
     - [Redux](https://redux.js.org/api/compose)
- Library returning function with the same arity of the first one
    - [Lodash](https://lodash.com/docs/4.17.14#flow)
    - [Ramda](https://ramdajs.com/docs/#pipe)

# Proposition

I think it would be great to support Lodash & Ramda behavior with a way to keep support for Redux.  

I've started doing some work here and it seems to work as expected (I'm just staring learning ocaml, so code is not that good) https://github.com/moroine/flow/commit/67f2ca026b9dc1a6a58f6478e55359141ad81185

Finally, as a side note, I think flow should propose more built-in helper to ease library definitions which is currently a pain to properly type, common operations such as `omit` or more advanced such as `curry`.

**Comment by SamChou19815** [comment]
We are unlikely to augment $Compose, as each special cased type introduces maintenance burden and we have to worry about how it interacts with other parts of the system, especially with generics.
