### ISSUE TITLE
Subclass of `T` is incompatible with `Class<T>`

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#814]
Here is a code that produces above error:

```js
/*flow*/

export class ThunkNode {
  /*::
  key: string;
  type: NamedThunk;
  */
  constructor(key, NamedThunk) {
    this.key = key
    this.type = NamedThunk
  }
}

/*::
type NamedThunk = Class<Thunk>
*/

export class Thunk {
  /*::
  static displayName: string;
  */
  static withDisplayName(displayName/*:string*/) {
    class NamedThunk extends Thunk {
      /*::
      static mounts: number;
      */
    }
    NamedThunk.displayName = displayName
    NamedThunk.mounts = 0
    return NamedThunk
  }
}
export var thunk = (key/*:string*/) =>
  new ThunkNode(key, Thunk.withDisplayName(key.split('@')[0]));
```

I guess issue is that subclass of `T` does not satisfy `Class<T>` but then I'm not sure how to express `Class<Subclass<T>>`.

**Comment by Gozala** [comment]
Something along these lines is used for [Reacts React.Component sub-classes](https://github.com/facebook/flow/blob/master/lib/react.js#L51-L62)

But I'm afraid I'm not sure how to express this for my use case.

**Comment by samwgoldman** [comment]
When I run your example, I get 4 different errors. Can you please make this example smaller, so it exhibits the issue more directly?

**Comment by Gozala** [comment]
I have figured out answer to my question. Issue was caused by the fact that `NamedThunk` was `Class<Thunk>` instead of `SubClass<Thunk>`.

Looking at React.Component thing I found a way to express subclasses as:

```js
type SubClass<Super, C: Super> = Class<C>;
type NamedThunk = SubClass<Thunk, *>;
```

**Comment by Gozala** [comment]
> When I run your example, I get 4 different errors. Can you please make this example smaller, so it exhibits the issue more directly?

That is odd I get only one error:

```
➜  reflex  (isomorphic) flow status                                                                                                        ✗ ✭ ✱
Flow server launched for /Users/gozala/Projects/reflex
Spawned flow server (child pid=31661)
Logs will go to /private/tmp/flow/zSUserszSgozZalazSProjectszSreflex.log
The Flow server will be ready in a moment.

/Users/gozala/Projects/reflex/src/core.js:34:3,62: Library type error:
/Users/gozala/Projects/reflex/src/core.js:34:3,62: constructor call
Error:
/Users/gozala/Projects/reflex/src/core.js:18:14,18: Thunk
This type is incompatible with
/Users/gozala/Projects/reflex/src/core.js:30:12,21: NamedThunk

Found 1 error
```

**Comment by Gozala** [comment]
I run it with flow@0.15.0 installed via npm from flow-bin.

```
➜  reflex  (isomorphic) flow --version                                                                                                     ✗ ✭ ✱
Flow, a static type checker for JavaScript, version 0.15.0
```

**Comment by Gozala** [comment]
Anyway this is further reduced test case:

```js
/*flow*/

export class ThunkNode {
  /*::
  type: NamedThunk;
  */
  constructor(NamedThunk) {
    this.type = NamedThunk
  }
}

/*::
type NamedThunk = Class<Thunk>
*/
export class Thunk {
  static create() {
    return class extends Thunk {}
  }
}

export var thunk = () => new ThunkNode(Thunk.create())
```

**Comment by Gozala** [comment]
So issue was on my end, but I'd like to keep this issue open mainly so that `SubClass<T>` could be documented on the website.

**Comment by samwgoldman** [comment]
What is `SubClass<T>`? Did you mean `Class<T>`? If so, it is [documented already](http://flowtype.org/docs/quick-reference.html#the-class-t-constructor).

**Comment by Gozala** [comment]
> What is SubClass<T>? Did you mean Class<T>? If so, it is documented already.

Let me clarify. As I mentioned in comment https://github.com/facebook/flow/issues/814#issuecomment-141257260 there is this in obvious code pattern used in lib/react.js:

```js
type SubClass<Super, C: Super> = Class<C>;
type MySubClass = SubClass<MySuperClass, *>;
```

I think it's worth documenting what what `*` is & even that this pattern itself as it was far from obvious how to express such a thing.

**Comment by samwgoldman** [comment]
I agree that the existential type stuff should be documented. I also agree that bounded polymorphism should make its way into the official docs (currently only documented in the announcement in the blog).

This pattern that combines both features is interesting, but I think documenting the above two concepts separately is a higher priority.

**Comment by adrianheine** [comment]
The `SubClass` patterns doesn't help if you for example want to have an object holding different subclasses:

```
class NodeType {}
class Text extends NodeType {}
type SubClass<Super, C: Super> = Class<C>;

var x: {[key: string]: SubClass<NodeType, *>} = {}

x.a = Text
x.b = NodeType
```

While `SubClass<NodeType, *>` is any subclass of `NodeType`, it's still just one subclass at the same time. I get why it's this way, but is there a way for this to work?
