### ISSUE TITLE
Expand $Values to support tuple types?

### ISSUE THREAD

**Issue by loganfsmyth** [facebook/flow#8143]
## Proposal

Allow `$Values` to take all of the values of a tuple type, not just an object.

## Use case

Flow currently defines `Promise`'s `all` and `race` as
```
static all<T: Iterable<mixed>>(promises: T): Promise<$TupleMap<T, typeof $await>>;
static race<T, Elem: Promise<T> | T>(promises: Iterable<Elem>): Promise<T>;
```

It seems like in a perfect world, `$Values<>` would allow this to instead be:
```
static race<T: Iterable<mixed>>(promises: T): Promise<$Values<$TupleMap<T, typeof $await>>>;
```

For instance, you could be racing two different operations with two difference result types that are tagged union for instance, e.g.

```
Promise.race([
  fetchThing().then(value => ({ type: "fetch", fetched: value }),
  loadCachedThing().then(value => ({ type: "cache", cached: value }),
])
```
and right now you instead would have to assign each item an index and then use that to tell which type it was.

**Comment by SamChou19815** [comment]
It's now supported
