### ISSUE TITLE
Re-exporting an import with inferred generics loses types

### ISSUE THREAD

**Issue by jjenzz** [facebook/flow#8144]
I'm not entirely sure if this is a Flow bug or if my expectations are incorrect but I'll raise it here for discussion. Happy to move this elsewhere if needed.

Flow version: 0.109.0

## Expected behavior

When using `export { thing } from './file.js'` the inferred types for `thing` are maintained when imported from that file.

## Actual behavior

Types are lost.

## How to reproduce

https://github.com/jjenzz/flow-reexport-bug

Create a file `a.js`:

```js
function someFunction<T>(param: T): T {
  return param;
}

export function foo() {
  return someFunction("test");
}
```

Then create a file `b.js`:

```js
export { foo } from './a';
```

Then import from `b` in `c.js`:

```js
import { foo } from './b';

const num: number = foo();
```

The above doesn't complain about incompatible types when it should: [flow.org/try](https://flow.org/try/#0GYVwdgxgLglg9mABAZzgWwKYDFzXmAHgBUA+ACgAcBDAJyrQC5EiBKJoxAbwChFEaMUEDSTU6aANzcAvt24YAHhTg0oiUJFgJ1cOGRZde-QcKSpMOTfjIAiKBmRQbLKbO4QEjxGBCNvvgCMMGkQAXh09FyA)

**Comment by SamChou19815** [comment]
With types first, they all need to be annotated
