### ISSUE TITLE
React.memo can not add custom properties

### ISSUE THREAD

**Issue by HsuTing** [facebook/flow#8145]
Flow version: 0.109.0

## Expected behavior

1. Can add the custom properties to `React.memo`.
2. According  to the [source code](https://github.com/facebook/react/blob/master/packages/react/src/memo.js), `React.memo` should return the type.

## Actual behavior

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AoctCAOwGd4BRADxXABsk4BeOACgCUPAHxwA3uThwiMAK5QacADwATYADdhMJAyUB6NZooBfCuRZswnAHTaGPfkO6j8dmGUrV68ACo74vMjoMNYgSCAQSmLGwnwWHEgCZn4Mtv4OgiIEbh5UtPYoAFxwDFDANADmDikhMACeYEhpDIIUXvYARsX1jRCYcPFWXLw1tg1IbfnwaMWl5VUj-s0wrUA

**Comment by SamChou19815** [comment]
This is working as designed, since we only support function statics in limited form.
