### ISSUE TITLE
Derived type for tuple destructuring const assignments isn't "fixated"

### ISSUE THREAD

**Issue by nvie** [facebook/flow#8149]
Flow version: 0.109.0

## Expected behavior

The following code should derive `(selected: boolean)` as the type, and thus throw a Flow error when comparing to a string literal.

```js
const [selected] = ([true]: [boolean]);
if (selected === 'yes') {
  //         ^^^ Why isn't this an error?
}
```

## Actual behavior

When assigning a const through an array destructuring, it derives `(boolean | string)` as the type, because of the comparison-to-a-string following later. [Try Flow](https://flow.org/try/#0PTAEHUAsFMDtQIYGckEsDmtW3Y0BjAe1iQBdQAzAJ0IFtF4EqqEBPUAE2jKoFd9SvKtnQAaUKnJdhAN24AoEKAAUAI0KEANtATwAPqB4iAlIiShSMC6wAO0cauj4EvJNFCEKoTdncB2ADp5IhJyAG03bQFoDgBdUABeFTDSPmhYgC5QMPUtHVhY4wBueVQvZUinUhjEhKSAclZuetMAb3lQUCVOnp6APQGISHZUJFh68ktRhlBoZkIqAH55AF95IA)

I would expect this to have the same result (a Flow error) as when not using array destructuring, like in [this example](https://flow.org/try/#0PTAEFECVIeU0AUBeUBTAHgB1QYwC6oAmAlAFAigDqAlngBYD2ArnqAIYBOHbAnqIagDOeDk3xMO1AHYBzADShaaLgw6D26jNnxFSOBlOGhBqADa4ChAEygUCEU1QAuUACMGDc2ynEA3KWoAM0QTcx1rWyQUAHIeIWjiUABvUgBfUiA):

```js
const selected2 = (true: boolean);
if (selected2 === 'yes') {
  //          ^^^ Flow error, as expected!
}
```

## React hooks

This is the most minimal / stripped down / bare bones example of a common pattern in modern React with [`useState()` hooks](https://flow.org/try/#0PTAEDECcHsFtQEoFMCGBjALgKACZLQDYqRKhIAeADtJBqAGYCuAdpgJbTOiMDOSAyhhQYkAHn4A+ABRtmbDGxQFBwpAC5QUqQEpQAXgmh+ugD5HtGgNr8ANJqn99h46DMuDoAG7Q2OALoA3FhYIKAA6gAWSFwoPDxsAOZyzAmgKKBonDx09DDwKDGQkCgAnqB42ZCMmIyQsgl28uVIdZ5IPCFgUgBG0NAEqFxmlfW6saAYURMllEh23fgovKTQ9KAEsqQA7AB0WJnM2aCWfAOYSDh2fBj8SGci-vrcfCoior39g9L0SnzaQWw1lJTvgHvo9HpQAByErtKG6ADeWFAoFCKPR6IAetjwhEymweMwoXRJgS0lwWjBIAB+LAAXywQA).

**Comment by SamChou19815** [comment]
This is now correctly erroring.
