### ISSUE TITLE
What are you doing?

### ISSUE THREAD

**Issue by uxitten** [facebook/flow#8150]
<img width="521" alt="Screen Shot 2019-10-23 at 12 15 27 AM" src="https://user-images.githubusercontent.com/1549069/67331098-38176680-f52a-11e9-9d5f-7e93c767555b.png">

<img width="565" alt="Screen Shot 2019-10-23 at 12 28 05 AM" src="https://user-images.githubusercontent.com/1549069/67332523-00112300-f52c-11e9-944d-3b7db25bee9f.png">

I have stayed 30 minutes here, what are you doing?

**Comment by nmote** [comment]
This isn't normal behavior for Flow, but there's not much we can do with the information you've provided. Feel free to open a new issue and choose the "Bug Report" option if you'd like to follow up. Make sure to fill out all of the requested information.
