### ISSUE TITLE
Allow field default when spreading value

### ISSUE THREAD

**Issue by moroine** [facebook/flow#8151]
The following code report an error

```typescript
type PersonalBestNugitSettings = {|
  current: number,
  headerMetric: null | string,
|};

function normalizeNugitSettings(
  nugitSettings: PersonalBestNugitSettings
): PersonalBestNugitSettings {
  return {
    headerMetric: null,
    current: 0,
    // Following spread error with 
   // Cannot spread `nugitSettings` because string [1] is incompatible with null [2].
    ...nugitSettings,
  };
}
```

https://flow.org/try/#0FAFwngDgpgBAClATgZwPYDsCGAbAQlZEAOQFcBzASxAGUoQQL0zkYBeGAbwB9gYYBjEokRR0IAFwx0JALYAjJABpeMABZRMAEyQBZOogr9J07NhhcYhA02VcAvgG5gwAGYl0-BhimpEMnBQAXlCklDR0DEzIABQq0mG09IzMkggoGDj4hKFUiZHMwACUqUhoWHgExOS5EcksHCoiIELonCp86lq6+obGJKbKfHyCwqISMAAMg0MAdHPxNUlR047AdkA

Flow version: v104-v110

## Expected behavior

No error

**Comment by lyleunderwood** [comment]
Hmm, if you [spread in the other properties](https://flow.org/try/#0FAFwngDgpgBAClATgZwPYDsCGAbAQlZEAOQFcBzASxAGUoQQL0zkYBeGAbwB9gYYBjEokRR0IAFwx0JALYAjJABpeMABZRMAEyQBZOogr9J07NhhcYhA02VcAvgG5gwAGYl0-BhimpEMnBQAXlCklDR0DEzIABQq0mG09IzMkggoGDj4hKFUiZHMwACUqUhoWHgExOS5EcksHCoiIELonCp8AHRdDXy9ahraiHogBkZSJKbKfXyCwqISMAAMU712K51d8TVJUSuOwHZAA) then it works fine...

[testing](https://flow.org/try/#0C4TwDgpgBAKlC8UAkAlCBDAJgeQHYBsQAeAbwB8AoKKAMwEsJ9MAuKXAV33yjKgGdgAJzq4A5gBoKZAL4A+ANwUKAYwD2uAbVWrWcRCSq0GTVhy6TpiigAoD1AHSPbh6vUYs2nfJOrSAlD5QjvY02ha6flbOrsYeZt6GwaGq4bCRSqCQUNgIyGhYeISklDHupl6SMgpKahrAUABG6IKsOfqGbiae5hSWStFBTnbURmXdCb4BiY5NgqnY6TbDnXEV0-az84uZ0ACyueQdseVcPPxCIhJSfSrqmk0AXqz77aVd8RZRw8EDb6s9k0CwUeqV2iwGKxOE0GG3QD1B23A0AAcgcjmN4mcBMIxJ8and6g12A8nlBUa9Ru81jcBj9hn8oYF-ECZsT4b1WMjwctjuMWRs2akufIgA)

**Comment by moroine** [comment]
@lyleunderwood yeah, but still looks like a bug.

**Comment by dsainati1** [comment]
This has been fixed by @jbrown215's spread changes coming in 0.111.0! If you pick the master branch on your try-flow link you'll see it no longer errors!
