### ISSUE TITLE
Static properties not work at function components

### ISSUE THREAD

**Issue by feonit** [facebook/flow#8152]
Example:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgWwA5wE4AuyYAhgM5gBKApiQMZFR5yZgDketDbA3KqgQCe2amAAKzbBQC8YAN6owYOgAt0MACacAdgC5S2wagC+-KAFdtDdHG1gAYjGoAPABRzV6rdW3H9EuCkASgUlTgJzPDtXRSUwAB4NdAA3AD4PNU0dY3jgJLTYoJMzS2tbBydnAEkCakxXENjwyOjYgEhElNTc-NTCpWLUYGAwaTGwABU8QTAARlGx-kcXADoautGKl3XMPjpbMiIAUWd8Wo0AEWooEnMYAmXnTZp6AhXMOrh4gKlU10egnwhiN0HY4AQVNQ8GAoOpqPx9tpDmBkuhqEhZDElPETmdqJdrrd7o8+nEErjCPirjc7g9KmtaphSWT5GwjnhmHgAIRgbTgsAIfAAazYpjJuQp52pRLpqx2zIlp0pBJpxMqfSKwIWsimMwATNqEQdjkqpYTaY8DbIXgx3p9vpIyH8AXxhmB2ZzUJKqea1S49QyNrIdkD+G6AOoEKAAfiAA

```js
import * as React from 'react';

type Props = {
  children: any
}

function Flex({children}: Props){
  return (
    <div>{children}</div>
  )
}

function FlexItem(){
  return (
  	<div></div>
  )  
}

// === Try 1 ===

Flex.Item = FlexItem;
const ExortedDefaultFlex = React.memo<Props>(Flex);

// in other file

const view = (
  <ExortedDefaultFlex>
    <ExortedDefaultFlex.Item>
      {'Error! not work'}
    </ExortedDefaultFlex.Item>
  </ExortedDefaultFlex>
)

// === Try 2 ===

const ExortedDefaultFlex2 = React.memo<Props>(Flex);
// Error
ExortedDefaultFlex2.Item = Item;
```

How do this for work?

**Comment by SamChou19815** [comment]
We will only support function statics in some limited pattern. Specifically, they have to be attached to a syntactic function directly.
