### ISSUE TITLE
Function accepting array of union types does not accept array of more specific type

### ISSUE THREAD

**Issue by aarongoin** [facebook/flow#8153]
Apologies if this is the same issue as some of the other union issues currently open. None of the other union issues seem to match my use case.

Flow version: v0.96.0 (project flow version) but reproducible with v0.110.0

## Expected behavior

If I have a function that accepts an array of a union type: 

`function foo(arg: Array<string | number>) { /* do stuff in here */ }`

I would expect calling the function with a more specific type to not produce a type error.

So `foo(["this", "is", "only", "strings"])` should NOT error.

## Actual behavior

Calling `foo(["this", "is", "only", "strings"])` gives a type error: "string [1] incompatible with number [2] in array element"

Reproduced here:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCqAdgJZzEAqYAvGMQK4C2ARngE5gA+YAzhu1LEA5gG50UBsQDGGcsTDxhAQXbsAhlgAU0gFxEyFSgG0AugEowAb1Rgw0irzgw8AOiVbXX6efEBfCSlZeUU4YQA1dRgGPB19EnlKSxs7B2InF3cwnV9UANRgYDAEOHYAa14wKCECBAALPAVSDABySvU+IWEXMCkQgDcomPQlSOjYgCJ+dgnc0aHYgAZcgqKS8srq4lqGhQwG9gJ1Q7A8FyZGjEq4KDAWOH2wbHxKoTBjjSx0NP4nvH4EhRVJ9aGBjBM6hMADRgRYwiYAE2hYAALABWUziVBKYGaLQYf4YQHEXFYFarO4MDCnNSlV63fZHNSaewUDDqITXYgwLBgCgEG5PBq9Qx7XD-b6OakE-gAZQEXVJ+mmXTMoPBCGREwwWqgE0xIzCpPxhPlghEpJWP2lhIAcsw2OwlfQHRw1XRjHCwABGGEAJhhAGYDdijcztDKMPbWBxLVigA

**Comment by jcready** [comment]
Use `$ReadOnlyArray<string | number>` instead.

**Comment by aarongoin** [comment]
I see. That works if my function isn't mutating the array--as in my minimal example case above--but what's the right way to go about this if that function actually mutates the array? For example, if I have a method that takes an array of numbers or strings and converts all numbers to strings, how should I type that argument? I realize that I could map over the read-only input array and return a new array, but what solution exists to handle mutating the existing array in place?

**Comment by jcready** [comment]
In your Try Flow link you provided you have the following:

```js
// but errors if the array contains only one of the union types

const testStringArray: string[] = ["w", "t", "f"];

logArray(testStringArray);

const testNumberArray: number[] = [0, 1, 2, 3];

logArray(testNumberArray);
```

The solution is to do either:
```js
const testStringArray = ["w", "t", "f"];
const testNumberArray = [0, 1, 2, 3];
```
Or
```js
const testStringArray: Array<string | number> = ["w", "t", "f"];
const testNumberArray: Array<string | number> = [0, 1, 2, 3];
```

**Comment by aarongoin** [comment]
Hmm, I think I see now. Thanks for your responses. I'll go ahead and close this issue.
