### ISSUE TITLE
"Type incompatible" error may return incomprehensible position

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#816]
Consider the following setup:

```
/* file1.js   @flow */
class Foo {
  foo: number;
}
module.exports = Foo;


/* file999.js   @flow */
function something(): Foo {
  return new Foo();
}
function otherthing(): Date {
  return something();
}
```

The error reported will be

```
js/test1.js:3:11,35: Foo
This type is incompatible with
[LIB] core.js:222:1,277:1: Date
```

In other words, Flow reports an error in a totally innocent line `module.exports = Foo;`, and at the same time says nothing about the unrelated and possibly hard to find file file999.js which actually causes the error...

**Comment by samwgoldman** [comment]
I just tested this with master and Flow blamed the import (which I had to add to your example here). Hopefully this will be fixed in the next release.

**Comment by calebmer** [comment]
This has been fixed. Please let us know if you are still having this issue 😊
