### ISSUE TITLE
Class field named 'static' fails to parse

### ISSUE THREAD

**Issue by thorn0** [facebook/flow#8165]
Flow version: 0.108.0

## Expected behavior

```js
class A {
  static = 1;
}
```
should parse without errors

## Actual behavior

`Unexpected token` error

* Link to Try-Flow or Github repo:

https://flow.org/try/#0MYGwhgzhAECC0G8BQ1oQC5nQS2NAvNAIwDcSAvkkA

Note that
```js
class A {
  static
  b;
}
```
should NOT parse as 2 fields.

**Comment by SamChou19815** [comment]
This can be now parsed correctly.
