### ISSUE TITLE
[Discussion / Request] Required Type Annotations

### ISSUE THREAD

**Issue by bradennapier** [facebook/flow#8170]
## Proposal

So I finally came across a blog post which answers probably every question and problem I have ever had with flow.  Life seems to suddenly make sense -- non stop I would wonder (and post bug reports without answer) about how imported values work so differently for some reason.

https://medium.com/flow-type/asking-for-required-annotations-64d4f9c1edf8

This being said, it exposes a pretty problematic situation where flow **should** be able to be smarter in some cases here.

Lets look at a crude example that is an over-simplification of my situation:

### Example

```javascript
type Example$Object = {|
  one?: string,
  two?: number,
|};

function Example<P: Example$Object>(obj: P): {| obj: P |} {
  return Object.freeze({ obj });
}

export const RESULT = Example(Object.freeze({ one: 'two' }));
```

### Result 

```
10: export const RESULT = Example(Object.freeze({ one: 'two' }));
                          ^ Missing type annotation for `P`. `P` is a type parameter declared in function [1] and was implicitly instantiated at call of `Example` [2].
References:
6: function Example<P: Example$Object>(obj: P): {| obj: P |} {
   ^ [1]
10: export const RESULT = Example(Object.freeze({ one: 'two' }));
                          ^ [2]
```

### [Try Flow](https://flow.org/try/#0C4TwDgpgBAogHgQwLZgDYQCQHkBGArCAY2CgF4oBvAHwCgooB7AOwgH4AuKAZ2ACcBLJgHMANHSjAA7gw5QmAVyQ4IvMVQC+Abho0AZvKbF+zWIhToAPAAVO8ZGky4CxAHwAKBvk5WAlJ2qMXlBWUBqU4rwQwPK8TFBORMAAdLqREABeEG4UgXhQ6j7a6joQcGAMvCSEzDxQAEowAMoAqgAyACpkpvbobgnEKWmZ2YwsnADkUgzj+T6FQA)

My question is -- if we have a frozen object and/or in general I can't see why this doesn't end up working out - since everything is `$Exact` and validated it should be able to absolutely guarantee that the type ends up being `{| obj: {| one: 'two' |} |}` without any compromise.

In addition, I would personally like to see where Flow takes frozen objects and turns the typing to literals since that can also then be guaranteed.

---

Interestingly, the only apparent solution to this without having to create tons of seemingly needless types all over the please would be to use the soon to be removed `*` type.  This seems to be a fairly strong case when it is worthwhile

```
export const RESULT = Example<*>({ one: 'two' });
```

**Comment by SamChou19815** [comment]
Since types-first, we will require all exports to be annotated, and won't make any attempt to infer function calls at module boundaries.
