### ISSUE TITLE
String literal is incompatible with a generic type of string literal

### ISSUE THREAD

**Issue by ylemkimon** [facebook/flow#8172]
```js
/* @flow */
type X = "A";

function foo<T: X>(x: T) {
  switch (x) {
      case "A":
  }
}
```

Flow version: v0.110.0

## Expected behavior
:smile:

## Actual behavior
```
6:       case "A":
              ^ string literal `A` [1] is incompatible with `T` [2].
References:
6:       case "A":
              ^ [1]
4: function foo<T: X>(x: T) {
                         ^ [2]
```

## Possible workaround
Casting either the string literal or argument to the type of the generic type works:
```js
/* @flow */
type X = "A";

function foo<T: X>(x: T) {
  switch ((x: X)) { // OR
      case ("A": X):
  }
}
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAaYAvGAEQCCZA3KqlAK4B2AxugJZxNhRxwA8AFQBchAHwAKAB6jBASjABvVGDABnBO3QsAFmGkLlq42BYBDNfkplhKsAF9U9oA

**Comment by gnprice** [comment]
FTR, this [was fixed](https://github.com/facebook/flow/blob/main/Changelog.md#01390) in v0.139.0.
