### ISSUE TITLE
Better support for class factories and $ObjMap

### ISSUE THREAD

**Issue by garyolsen** [facebook/flow#8175]
## Proposal

Any of these would work for me:
- Provide some way to define an interface based on an object type (the opposite of the `$Rest<AnInterfaceType, {}>` trick I've seen to convert an interface type to an object type)
- Support suppression of only specific errors with `suppress_comment`
  - Something like `eslint-ignore no-param-reassign` where a kind of error is specified
  - It'd be fragile, but even being able to provide a regex for the error message to be suppressed would be fine for me (I don't mind the build breaking when we upgrade Flow if a message has changed)
- Allow `class X extends Y` where `Y: Class<T>` for an object type `T`; I don't know enough about how Flow treats object types differently to know whether or not this is a good idea.

## Use case
Our project is already typed with Flow. I'm replacing model classes with implementations that are generated based on a schema defined by JS object literals. (For FB folks: consider what a nodejs variant of EntSchema would look like if there was no the codegen build step.)

I've had success doing this with Flow.  Extracting an object type from the schema using simple metaprogramming is easy to do with `$ObjMap` and function interface overloads (e.g. `{kind: 'string'}` generates a property of type `string`).

The problem comes when I add type annotations to the function call that returns the class. I really don't care about typing *within* the factory function (as in #7595).

The model classes I'm replacing often have static and instance methods; at first I moved these completely within the schema definitions so that I could do
```javascript
// replaces:
// export class User {firstName = ''; someMethod(): void {...}}
export const User = defineEntityClass({
  fields: {firstName: {kind: 'string', defaultValue: ''}},
  methods: {someMethod: (user: User) => {...}},
});
```
I'm not filing an issue for this, but I'm raising it as an alternative I've considered that does not generate Flow errors. The problem was that uses of `User` seemed to not treat it a class type; IIRC functions that would otherwise infer a generic parameter type from a function argument would bail when encountering an instance of `User`.  There were other issues as well but I don't think they're relevant.

So instead I went with using the class-generating function to define a base class; the extending class would then be able to define any statics and instance methods, and it would be clearly known as a `class` to Flow.
```javascript
// replaces:
// export class User {firstName = ''; someMethod(): void {...}}
// $FlowFixMe
export class User extends defineEntityClass({
  fields: {firstName: {kind: 'string', defaultValue: ''}},
}) {
  someMethod(): void {...}
}
```
This works really, really well except for the suppression comment; without it an error `Cannot extend  object type [1] with 'User' because  object type [1] is not inheritable.Flow(InferError)`. My concern with the comment is that we could end up suppressing some other error unintentionally. And, it's not great to encourage folks to suppress errors.

This link replicates the issue with a simpler example: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgLIE8wDmcAhjGAJYDOYALnIQKYB2DATsTQxQLYAOMDbsxodycJtThQw3OABMGZAMYxilSg2oAjNQzlhxGLMTCURNcktNKAFoOIA6MABU7YYkpoBXUj36DhUXEKJgA3OBhQzXcweBoDKCMZBhFeVjgCdm5uciYCWnpSeCQoOFYwBShc8gtxahhyAGsGJLAwFTVqAFUNcoYAD04mOWpuYmaAYVV1AHUamwBlGlYvTy9WBgAKAG9WtrAqxRGALjBtqtYzADliIVPtxty5U4ByM1ZcgheAGjAHf4Avr9-g4AXsAQBKJIASReUVMyy8BAIAn0dAOTxiCGI+HRxCYTDg5i4JigXiYnjETFoNg4YA23lYEiSJhYSA66jACBscA0YDScF4bAs0VyKi8CncMDIUhpvK4AtC5AU+i0+HxYCScC0ACsGJ5aLghQ50DDqRtSDV8AgGC99LxOiF3NTtXqDdz5SEoGwNmijVwEHAvDBVS1MGAvBo0fRFcquM4TQoOhsDuTKcExpNppQ5jRFoi1hsADzOAB8mwhpymnRLpYA3Ohw64qBRqNy6Taufj4uiNvxLBwGL8tF54gh5jENPFZQKhawRZQknm6cQUyPyDAxxOACQAeV12GIvBCZgYxH0srznuCGtynFYUA8DBNd7Yj6UXAAYnB6Ls2ko6gLOhWArU5wmVBs2gua5bgYU53k+b5UDaaYaBuO4EQ+PIkLBDlqG-OBq05AYhhGGRxgYIic3mJYVkLBgiwI8sITOVAwTaVAAIkeJSnoABeMA2TAAiqIrBtNl4hxoLQ2D4OWT4IQbcMAFFWHScoAFouXSPJDSFOt3BtSg4CEE0JJ-KTyEuGSMKYLxuC0NhFKSVT1LALTZ2FfAcnUT4DOIIyTOfVBzLgBw5DgTQriJZT+ioGhTnxXBnI48MFjgX5lmtCdbyYe93y4Zd4hbPcDyPO0kl3aQAPWPk8xbQMmBeMcykaYdRwoYrpUjZZB2oPMuCIUgTVQV8HyfMAACFV1Y-9ALo4DQLAcC5EgjFrPQuDML85DYjUGytoQvIGzBJIJnxZqIz5UqdUPY9xzzZ0QnyibNkJeJ4DgR5dPRWx8QIQraRoKEaH9KbVzuoV9AEm67qLabWF+WtNldU5nBYvjSzAABBNScVret0Dw8HWCosASOYMjM0o7Nc3zBb1gYhHIb0ZjWNO8NoWkTsdR6igCEJFMBvJtSyl+TtGsugH4iSvT9TsJRvoIE19k1LizDAHRygEoSEdE5zNi1yyNtknG8dwIsjoIUtnPDQkRfU9r4gUSgrL0EKjekzbTlx9gLbshy2BtpSsHtn0xc1jqXbduQPdXcLIsoaKaFi+LEqYZK1o41WYW5rhIxJF1dX1HswdyU9z3F21pUYGXqXD8puWYLkuAp4YaS4PDdo40GhRJgAmMABL-daYIwq2kJQ-bve27C2PQXuuAR-uWehsBYaPeHV37pGyxR3U0YxrHffxstCdzluwF5jXKC8Xg0k0fq3AbsA7A2X4GCiVhcHq3TFD5MwG4yCBlYI0SgJpibLzJm3KmFEqJ01oqsRkTNt6rzAAAMjOOrICZQlorQBGzXYp1sGa23kPQSDAkBQOzGJOOrB+7GzHltE+FsrbBySEsIB9JiBUGiBqBudCGFe1NiwosAdHKsHYWlCwNd2C8OoPw0WrBBEJyijFOKZgfbmzEfZCRwcgA)

While the example I've provided looks kind of silly—*"why not just use normal type annotations?"*—we do have our reasons :smile: I'm not proposing this as a key feature within Flow, but I am assuming that there is some forward path regarding the split between interface and object types that I don't have insight into so I'd like to see how we can work with where Flow is going.

**Comment by SamChou19815** [comment]
`Class<...>` can only accept an instance type as a type argument, so this is not related to these other utility types. We will not change this behavior of `Class`
