### ISSUE TITLE
null or undefined [1] is incompatible with null or undefined [2]

### ISSUE THREAD

**Issue by dlthomas** [facebook/flow#8180]
Flow version: master, 0.111.2, everything I've checked back to somewhere in 0.7x (where it gets fuzzy as the message changes)

## Expected behavior

The code given is accepted, or a clearer error message is generated.

## Actual behavior

An error is generated that complains two identical types are incompatible.  I believe it's a false positive, but if not the error message should be improved.

Swapping the tuple type (`[?number]`) for an array type (`Array<?number>`) gets rid of the errors.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBDAzgTwHYDGYUAroQC4CWcexccAFAJQBcYACgE5wC2lWAUwA8AfjwkeAIwGcAfGADeqAJAEaWcmADaADwC6bLWInTOesAF4wGBBkqauvfgIB0GGDAZbUYX38d8gi6cAlhwMABuAgwM4h5sxlIyTEwAND5+ekwA3Bm+IeQknLQ6uQC+QA

**Comment by borlaym** [comment]
I know this is not a solution, but it works if you annotate the Promise inside Promise.all:

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBDAzgTwHYDGYUAroQC4CWcexccAFAJQBcYACgE5wC2lWAUwA8AfjwkeAIwGcAfGADeqAJAEaWcmADaADwC6bLWInTOesAF4wGBBkqauvfgIB0GGDAZbUYX38d8gi6cAlhwMABuwsZSMrIM4h5MADQ+fnpMANxpviHkJJy0OtkAvkA

I agree that flow's error reporting often leaves something to be desired. I have often ran into similar issues, and the first thing to do is to properly add the type parameter. Why it is like this though, I don't know.

**Comment by SamChou19815** [comment]
This is no longer erroring under `inference_mode=lti`
