### ISSUE TITLE
Property missing in object type [1], but exists in object type [2]

### ISSUE THREAD

**Issue by tebuevd** [facebook/flow#8184]
Flow version: v0.112.0

## Expected behavior
No error

## Actual behavior
Type error

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCGAxhgK6EwCSAdjmRmALxgDeqYnYxMAlnjQwAuNhy6deAExE0yAWwBGeAE4AaMeLIBnFSNZgpM+UrVgMvOXgBacGnhFaMy3jQDmYAL4bP68Vt4Y9mwG0mCyiiqqZhZ4AF62QY7Obp6oHgDcmLgEeAAe+KR4krT0jCzsXDz8gnre2rqi4hKh4SbeHr4+Yv6BteKGYcYqYh1pmahQZDSkvLZgk9MAFLkieQWBxXQMAJSNYMp45Mo0YLmZXqjEto5gWCIk5JQlDMxsGegLxItY2+lAA

**Comment by tebuevd** [comment]
Typescript for comparison: https://www.typescriptlang.org/play/#code/PQKgBAAgZgNg9gdzCYAodAXAngBwKZgCGAxhgK6EwCSAdjmRmALxgDeqYnYxMAlnjQwAuNhy6deAExE0yAWwBGeAE4AaMeLIBnFSNZgpM+UrVgMvOXgBacGnhFaMy3jQDmYAL4bP68Vt4Y9mwG0mCyiiqqZhZ4AF62QY7Obp6oHgDcmLgEeAAe+KR4krT0jCzsXDz8gnre2rqi4hKh4SbeHr4+Yv6BteKGYcYqYh1pmahQZDSkvLZgk9MAFLkieQWBxXQMAJSNYMp45Mo0YLmZXqjEto5gWCIk5JQlDMxsGegLxItY2+lAA

**Comment by pladaria** [comment]
make your `expectedInput` properties read-only:

```
/* @flow */
type actualInput = {
    client: {
      id: number,
      user: { id: number, timeZone: string }
    },
    site: { id: number, timezone: string }
};

type expectedInput = {
   +client: {
    +user: {
      +id: number
    },
  },
  +site: {
    +id: number
  },
};

function func(x: expectedInput) {
  return x;
}

const y: actualInput = {};

func(y);```
