### ISSUE TITLE
Problem inferring type using object spread of function result

### ISSUE THREAD

**Issue by pladaria** [facebook/flow#8185]
Flow version: 0.112.0

```js
type T = {|a: string|} | {|b: string, c?: boolean|};

declare function f(): T;

const v1 = f(); // const v1: T = f(); // this works
const v2 = {...v1};

// v1 and v2 should have the same type (T)

const test1: T = v1; // ok
const test2: T = v2; // error

// v2 is inferred as: {| a?: string, b?: string, c?: boolean |} | {| b: string, c?: boolean |}
```
[try flow](https://flow.org/try/#0C4TwDgpgBAKlC8UDeAfAhgLigZ2AJwEsA7AcxQF8oVkUAjLXQ0gGigGMB+LWgex4BsIaIhQDcAKHEATCG35o80AGYBXIm2AEeRKEoAUASiwwJ4tttxQAbgEYEuw6KgB6Z1AJLrdgtigBbYRU0fn4QKFBIKSg0XxhWAmAoAHcePABrbDMLRKsAJnskADpi23JTVy9ooii8nAALHhV+KLq0K2hgOuhsND8O8Gg9GANJcyJLYAhcG2N7WycKnjSs8cTJ3FzZxDyFtwg8PFTJCtqfdyIlfcUomKxUaK4cfGISVlpHxhfWTm4+QWEqJRqPd6E8mK92I9eAIhDoKEA)
## Expected behavior

`v2` should have type `T`

## Actual behavior

`v2` has a different type

**Comment by SamChou19815** [comment]
This now works
