### ISSUE TITLE
Losing intersection type when spreading an element inside map function

### ISSUE THREAD

**Issue by tanqhnguyen** [facebook/flow#8188]
Flow version: 0.112

## Expected behavior
According to flow docs (https://flow.org/en/docs/types/intersections/)

> When you create an intersection of object types, you merge all of their properties together.

From my understanding, constructing a new object type using intersection should result in the same type as using spread operator (as shown in this example https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAdgIYC2mAXKAM7IBOAlqQOagC+A3ChtgBCBXKABkxUOXa0yAV0oAjTE2580WUAGERRRKFAA6YzgA0+qTLqkFypol6JEAY1ilGoSnWGESFanQA5MiYjIGmlrIAjGoubh7OdDqElDxAA)

## Actual behavior
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAdgIYC2mAXKAM7IBOAlqQOagC+A3ChtgBCBXKABkxUOXa0yAV0oAjTE259EAY1ilGoSnUEBtALojDJCtToByVLGsAaKTLoBOV92N8tO5KA0GJiKUAHSU5OgAFJEAbgCUBAB8xIigoEyYyHJMpClpaSGFMalqiFxxPEA
In the above snippet, when spreading an element using `map` on an array of an intersection type, the value's type is lost.

However, using spread operator to construct the type doesn't lead to the error
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAdgIYC2mAXKAM7IBOAlqQOagC+A3ChtgBCBYqAB0EnABpQ5drTIBXSgCNMTbn0QBjWKUahKdQQG0AuiJMkK1OgHJUsOzLkKAnG+5m+u-clDaxuYilGKU5OgAFJEAbgCUBAB8xIigoEyYyIpMpClpaRJiMamaiFxxPEA

**Comment by dsainati1** [comment]
This is fixed by annotating the type of `v`: https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAdgIYC2mAXKAM7IBOAlqQOagC+A3ChtgBCBXKABkxUOXa0yAV0oAjTE259EAY1ilGoSnUEBtALojDJCtToByVLGsAaKTLoBOV92N8tO5KA0GJiKUAHSU5OgAFJEAbqAGAJQEAHzEiKCgTJjIckykaRkZIcUx6WqIXAk8QA

@jbrown215 do you know why this happnes

**Comment by SamChou19815** [comment]
This now works
