### ISSUE TITLE
getContext("2d") should return CanvasRenderingContext2D

### ISSUE THREAD

**Issue by danvk** [facebook/flow#819]
I'm currently using this typecast-ridden code to work with HTML `<canvas>`:

```javascript
var canvas = (this.refs.canvas.getDOMNode() : HTMLCanvasElement),
    ctx = ((canvas.getContext('2d') : any) : CanvasRenderingContext2D);
```

The `HTMLCanvasElement` cast would be hard to avoid, but the `CanvasRenderingContext2D` cast shouldn't be. The problem is [this declaration][1]:

```
type RenderingContext = CanvasRenderingContext2D | WebGLRenderingContext;
declare class HTMLCanvasElement extends HTMLElement {
    getContext(contextId: string, ...args: any): ?RenderingContext;
}
```

- If `contextId` is `"2d"`, `getContext` will return a `CanvasRenderingContext2D`.
- If it's `webgl`, `getContext` will return a `WebGLRenderingContext`.

If a string literal is passed to `getContext` (and it's hard to imagine a situation where it wouldn't be), then the return type should always be one of these, not the hard-to-work-with union type.

See also #61

[1]: https://github.com/facebook/flow/blob/25e6368959740e845cb962fe2843c503c7d6c4cc/lib/dom.js#L642

**Comment by samwgoldman** [comment]
That declaration should be updated to use overriding and string literal types, so we can avoid the union return type. Shouldn't be hard, something like this:

```
type RenderingContext = CanvasRenderingContext2D | WebGLRenderingContext;
declare class HTMLCanvasElement extends HTMLElement {
    getContext(contextId: "2d", ...args: any): ?CanvasRenderingContext2D;
    getContext(contextId: "webgl", ...args: any): ?WebGLRenderingContext;
    getContext(contextId: string, ...args: any): ?RenderingContext; // fallback
}
```

That said, you should be able to (and should prefer to) use a dynamic type test instead of a cast for this.

```javascript
var ctx = canvas.getContext('2d');
if (ctx == null) {
  // error handling
} else if (ctx instanceof CanvasRenderingContext2D) {
  // ctx is refined here
} else {
  // ctx is a WebGLRenderingContext? handle error here
}
```

If we had the string literal override, you wouldn't need to handle the WebGLRenderingContext branch, because we'd know a more exact type, so it would look like this:

```javascript
var ctx = canvas.getContext('2d');
if (ctx == null) {
  // error handling
} else {
  // ctx is a CanvasRenderingContext2D
}
```

Much nicer.

**Comment by danvk** [comment]
:+1:

Would be great to get this fix in the next flow release!

**Comment by samwgoldman** [comment]
@danvk Updating the flowlib is pretty straightforward. Would you be interested in working on a PR for it? Also, just wanted to confirm, did I adequately explain what you can do today to safely use this API before the improvements land in Flow?
