### ISSUE TITLE
Intersections of object types are treated differently than object spread to form a new type

### ISSUE THREAD

**Issue by tanqhnguyen** [facebook/flow#8193]
I don't know if this is an intended behaviour or a bug. I might be confused between intersection and object spread to form a new type because their behaviour are pretty similar

Flow version: 0.112

## Expected behavior
IMO, object type intersection and "type spread" should be treated the same way.

## Actual behavior
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAlgCYBcoAdgK4C2ARpgE6gC+A3ChtgEIFcoAGTFaAQwaZqAZ2StSNAOaceiCbNQ0AxqEh1dyUrBqhlmZPwAUASmoAFVrAalZmADz8AfMUShQVks6VjMSCmoARgAaSWlqAHJkTHkEtUQORA0tXX1DHWNTUGT5O0dnV3cvUXEJC2p6ZjZOXyJ-UB1TeVAmIQl4CVJkc0sbWx4A9qDkELD2gIA6JaZo+dA6mVBI9szMoA

In the above snippet, `const b = await getB();` b is apparently of type `A` and not `B`, hence the "missing name" error

The fix is to change
```js
type B = A & { name: string };
```
to
```js
type B = { ...A, name: string };
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAlgCYBcoAdgK4C2ARpgE6gC+A3ChtgEIFioAHRicAGloBDBpmoBnZK1I0A5px6JpC1DQDGoSHQPJSsGqDWZk-ABQBKagAVWsBqQWYAPPwB8xIigoKw2dKyWJBTUAIxSNLLyoADkyJhKyZqIHIjaugZGJvpmFqBpSo4ubh5evqAAZMLS1tT0zGycAURBoPoWSqBMQtLw0qTIVjb2DjzBPaHI4ZE9wWIiTBIroM1JMT05OUA

This problem also happens without `async`
https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoAlgCYBcoAdgK4C2ARpgE6gC+A3ChtgEIFcoAGTFaAQwaZqAZ2StSNAOaceiSHRoBjZKVg1QyzMn4AKAJTVBRRKFCsTdVoZIVqARgA0k6dQDkyJjy-mqIHIgaWrr6hkHyltai4hLG1PTMbJzEdqDaBvKgTELGppY89rmOyM6uufYAdE1MXvWgqTKgHrkREUA

**Comment by cvoege** [comment]
Any update on this? We use intersection types extensively, and now if we try to upgrade to 0.111.0 or greater we get around 1800 flow errors, and changing every single type we have to use spread instead of intersection is not a viable solution.

This definitely seems like a bug, as our intersection types and the operations we're trying to do on them are totally valid from a typing standpoint.

**Comment by borlaym** [comment]
This is kind of preventing us to update flow, since we use intersection exclusively, but any time we use object spread as a value, it gives an error.

**Comment by tanqhnguyen** [comment]
This seems to be working now, I'm closing it :)
