### ISSUE TITLE
Unable to refine string to string literal

### ISSUE THREAD

**Issue by jcready** [facebook/flow#8199]
Flow version: 0.112.0

## Expected behavior
Able to refine `string` type to a string literal type.

## Actual behavior
Unable to refine `string` type to a string literal type.

```ts
const TYPE = {
  FOO: ('FOO': 'FOO'),
};

const onlyTypes = (type: $Values<typeof TYPE>) => TYPE[type];

const callIfType = (str: string) => {
  if (str === TYPE.FOO) {
    onlyTypes(str); // Unexpected error occurs here
  }
}
```

* Link to Try-Flow: https://flow.org/try/#0MYewdgzgLgBAKgTQAoFEYF4YG8BQMYBiA8kQFwwAUA5MUVeTSVQJQA0OAvgNw46iSxwAGwCecEQAcAphAyUokqeQAkANQCGQgK4yAPAukgAZvGQoAfMwznTqANoGpAXR59w0GME1CAkkfHSchTQAE7koQCWYADmVug2uPgRJsFQIRjomIioAHS0Von4MMJiihCpIcw8+BycQA

**Comment by dsainati1** [comment]
We don't do refinements against things that are not literals. We will hopefully support refining against `const` variables at some point, but even then, declaring a `const` object doesn't prevent re-assigning its fields.

**Comment by jcready** [comment]
> We don't do refinements against things that are not literals.

Why?

Flow knows the type of `TYPE.FOO` must be the string literal `'FOO'`. Even if I defined `TYPE` like this it still fails.

```ts
const TYPE: {|
  +FOO: 'FOO'
|} = {
  FOO: 'FOO',
};
```

The type-at-pos of `TYPE.FOO` is `'FOO'`. Flow would not allow me to reassign `TYPE.FOO` since it is read-only. How is this not a bug?

**Comment by dsainati1** [comment]
> How is this not a bug?

This is a philosophical question. Is something a bug if it's just unimplemented? It's something we plan to support, we just haven't done it yet. This is why I didn't close the issue.

**Comment by jcready** [comment]
What's the sound of one person switching from flow to [typescript](https://www.typescriptlang.org/play/?ssl=9&ssc=52&pln=9&pc=20#code/MYewdgzgLgBAKgTQAoFEBcMDeAxA8rjAcj10IF8YBeLAKBhhKJMJrIG4abRJZwAbAJ5wBABwCmEKjAAUUUWKb5CASioA+eMhQBtOeIC6HLuGgxgAQz58AkgDNh4qdOgAnDK4CWYAOarKGzDoYD1sZVypKakRUADoSVUD6en4heQhnKBdlDnoyViA)?
