### ISSUE TITLE
Arrow-function syntax parse error

### ISSUE THREAD

**Issue by jasonkuhrt** [facebook/flow#820]
Coming from https://github.com/babel/babel/issues/2400#issuecomment-141582336

Apparently this does not work in flow today but it seems to me that it should/is a valid feature:

```
const foobar = <X> (x:X): X => x
```

**Comment by samwgoldman** [comment]
Let's keep tracking this in the Babel issue. If it turns out to be a Flow bug, we can reopen this.

**Comment by gcanti** [comment]
FYI: the babel issue is now tracked here https://phabricator.babeljs.io/T2400 (still open)
