### ISSUE TITLE
Declaring a unary function type alias reduces type safety

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#8200]
## [No error](https://flow.org/try/#0FAFwngDgpgBAqgOwIYCcwDEEB4CSAaGAeQD4YBeGHc0gBmFElgBUkJyYsAFYgCgEpq8ZGkxcC3egBMoAYwA2qWADdUMEKwBcMFhHoyA9ggDOIGADN9+rQgCuAWwBGUFO3UR+PAOQX9nvsBhAmCA): 
```js
type UnaryFn<I, O> = I => 0

type Tap = <P>() => UnaryFn<P, P>

declare var tap: Tap

const foo: number = tap()('foo')
```

## [Error, as expected]():
```js
type Tap = <P>() => (P => P)

declare var tap: Tap

const foo: number = tap()('foo')
```

**Comment by dsainati1** [comment]
You have a typo in your example without the error. You probably mean to have `UnaryFn` return O, but you wrote 0 (the number), which is why `Foo` can be a number.
