### ISSUE TITLE
delete appears to invalidate refinements

### ISSUE THREAD

**Issue by jimmydief** [facebook/flow#8204]
Flow version: 0.112.0

## Expected behavior

`delete` does not invalidate refinements.

## Actual behavior

`delete` seems to invalidate refinements.

[Link to Try-Flow or Github repo](https://flow.org/try/#0GYVwdgxgLglg9mABMOcAUAPAXIg3gTx1wG0BnKAJxjAHMBdHcq2gX0QB9EA3OGAExYBKPAChEiGMESYAdPmG4RASD4BTADaqoqxBjnEA5AEMDdANyIA9JcQAxaqrGIVGrTr35DAI1MXrdoxh1UicWETCgA)

**Comment by SamChou19815** [comment]
Expected behavior. The current behavior is sound due to potential alias problems.
