### ISSUE TITLE
Provide a more helpful error message when `[lib]` config points to runtime code instead of type defs

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#821]
After trying 0.16 I get this error for ever export statement in my code. It is also unclear from the error message what the issue is or how to fix that.

**Comment by Gozala** [comment]
Here is the very minimal example that still does cause above error:

```js
/* @flow */

export const send =/*::<a>*/(action/*:a*/, address/*:(action:a)=>void*/)/*:void*/ =>
  address(action)
```

**Comment by Gozala** [comment]
It feel like it may be related to the thing mentioned in the release notes for 0.16.0:

> Likely to cause new Flow errors:

>  - Some module exports that didn't require annotations before may now require annotations


I wonder if I'm missing some kind of annotations, but can't really tell as I don't see anything like that in docs.

**Comment by gabelevi** [comment]
I tried the example in isolation and didn't get any errors with 0.16.0. Can you provide more context? Even if it's not a minimal repro, it will help us figure out what's going on!

**Comment by Gozala** [comment]
It's odd but I did used to get it even though I have removed all other files from my project. Now that I've create completely new project dir with only this file it seems to pass. I'll try to figure out what may be triggering this and provide more context here

**Comment by Gozala** [comment]
@gabelevi ok I've just published actual repo that has all my code and produces errors outlined in the issue: https://github.com/gozala/reflex/tree/type-flow

I'm not quite sure combination of what causes this issue, I'll publish another branch with it if I manage to reduce surface.

**Comment by Gozala** [comment]
I have reduced repo to this https://github.com/gozala/reflex/tree/type-flow-min and frankly I don't see what the difference between code I pasted in issue and what I have there.

**Comment by Gozala** [comment]
One more observation, if I remove [my configuration](https://github.com/Gozala/reflex/blob/type-flow-min/.flowconfig#L6-L7) from `.flowconfig` no errors are reported.

**Comment by Gozala** [comment]
Ok I just re-read docs for `.flowconfig` and it seems `libs` section is not for actual code but rather for external type declarations which is probably why I was observing this issue.

I still would like to keep this issue open cause it's confusing error message that is worth improving.

**Comment by samwgoldman** [comment]
For better or worse, we don't error on this code anymore.
