### ISSUE TITLE
Generic async function parse error: Unexpected token `,`, expected the token `)`

### ISSUE THREAD

**Issue by AuthorityFX** [facebook/flow#8213]
Flow version:  0.105.2

## Expected behavior

Async function with multiple generic types will be parsed correctly

## Actual behavior

Unexpected token `,`, expected the token `)`

async arrow function multiple generics (ERROR!)
https://flow.org/try/#0C4TwDgpgBA6g9gJwNYQQHgJIBooEEcBKAfFALxQAUAlgHYBWEAxsBACYBcU2UAhggOYBnTrgCUZEgQDcUAFCzGcGoOBRWVQWB7BGAC3jJUZXoJA1GUTDnxRiFWVChgEcYHAMoEnD6it5CRFgOvALC-sGsEABmYbgICDwgaCoItPxEsuKkJADewQgQwACuCDRQNEUANpVSsgC+UkA 

arrow function multiple generics (no error) https://flow.org/try/#0C4TwDgpgBA6g9gJwNYQQHgJIBooEEcBKAfFALxQAUAlgHYBWEAxsBACYBcU2UAhggOYBnTrgCUZEgQDcUAFCzGcGoOBRWVQWB7BGAC3jJUZKJhz4oxCrKhQwCOMDgGUCTs9Sm8hIlmu8Bwl5+rBAAZoG4CAg8IGgqCLT8RLLipCQA3n4IEMAArgg0UDS5ADYlUrIAvlJAA

async arrow function one generic (no error)
https://flow.org/try/#0C4TwDgpgBA6g9gJwNYQQHgJID4oF4oAUAlgHYBWEAxsBACYBcUGANFAIYIDmAzo2ySACUeHPxABuKACgplOCW7AotItzBtglABbxkqPO24gSlKJiwEpUKGARxgcXSgSMnqc8yvsuvdgM-WtBAAZr4AgggIbCBoigiknFhSwrg4AN5eCBDAAK4IJFAkOQA2xeJSAL7iQA

* Link to Try-Flow or Github repo:

**Comment by AuthorityFX** [comment]
bump

**Comment by sola92** [comment]
bump
