### ISSUE TITLE
Cant get partial application function to work 

### ISSUE THREAD

**Issue by yoavniran** [facebook/flow#8215]
Flow version: 113

I have a function (partial application) that either returns a function if only the first param is passed or executes entirely in case it receives the necessary params.
The result of the full execution is a promise which seems to be causing the problem.

The following sample reproduces the issue:

```javscript

 type Doer = (name: string, ...args: mixed[]) => Promise<number>[];
 type LaterDoer = (name: string, ...args: mixed[]) => Promise<boolean>;

   const partial = (
        doSomething: Doer,
        name?: string,
        ...args?: mixed[]): Promise<boolean> | LaterDoer => {

      const doTheThing = async (name: string, ...args: mixed[]): Promise<boolean> => {

        const results = doSomething(name, ...args);
        const resolved = await Promise.all(results);

        return resolved[0] === 1 && resolved[1] === 2;
      };

      return name ? doTheThing(name, ...args) : doTheThing;
   };

   (async () => {

     const doesSomething = () => [Promise.resolve(1), Promise.resolve(2)];

     //#1 can work with all required args - returns promise 
     const now = await partial(doesSomething, "test", 1,2,3);

     //#2 partial application - returns function to be called later with the rest...
     const later = partial(doesSomething);

     const theEnd = await later("test", 1,2,3); //flow reports error here
   })();

```

## Expected behavior

no error.

Im probably missing something here but cant figure out what. Tried posting on [stackoverflow](https://stackoverflow.com/questions/59089421/cant-get-partial-application-and-async-play-together-in-flow) but no answers for a while so perhaps it is an issue with flow

## Actual behavior

error:

```
    33:   const theEnd = await later("test", 1,2,3);
                               ^ Cannot call `later` because a call signature declaring the expected parameter / return type is missing in `Promise` [1].
        References:
        10: 		...args?: mixed[]): Promise<boolean> | LaterDoer => {
                                  ^ [1]

```

* Link to [Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgAiceATmALxgAUAdgIYC2eAXGAM4akCWtA5gBowAOlH1Sfdm0bcAHngAmAbQC6ASkoA+MAAVScGezwAeWgFdGAIzKbVAblTZ8YADL0MZYmUo0GzNpw8-EKiwuKS0nKKqhoU2noG3EbGlnBwMHj0tJoOqADGcLScYDjiGNz0MD7UqACQtQpwAMoGeBgAFrx8bF6kAnW1fngA-AFcXf31oeHso2Ay8srqbAmGJqnpmdlgAD6u7p4k5HFgAN7otQVFGGCNACrteA9dPvTsWLR5vkysHOPBIjEEik8yiSzUK30axSaQyWW0J3OAyuxVIeHYZhgGHYPkaLWYHS6dB+ISBkjUDnqKJuaPY6QAbopXgh6NwbqskngwjAYNRaZjsRSLrU0RgzKRaGBaQzogAGFSUChUACMYAAZGqpeiZcplQqlVQAEyUgC+uRFbXFkqGYGGtzgDyenX4xOYpLCwI0bHuj2e-AcZvQ1DeHy+1DUcXOYDAqGj1Pt6PxbWdfGqsW0Sg5RmE0pgjOoyrUQizXNz+cNahUDhj0eAwAAxKq8lkwAg4KQANattntMCVKpogCOZm4aIUfeBYAAtFqxRKcdxGMwFBUMBksLGwPHaIhmaybqVSOVKtRGonWoSAQAiDycK9CZUCQ0CADMQujm7r9cNJTKFSq9A4DgMDcM25SFNOs5WjiUBmJ84GShgcBgNYW79kyMAHOQCA9mAHQELSGChJu8aYR4xy-ke-6niQ7BJpefDvh+caFMU+EAKK0OOVD0CybJgGRZDUDe6IYPeYCPs+b7VjGJpqOGdhAA)

**Comment by mirek** [comment]
You're missing instanceof Promise check maybe? https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAodAXAngBwKZgAiceATmALxgAUAdgIYC2eAXGAM4akCWtA5gBowAOlH1Sfdm0bcAHngAmAbQC6ASkoA+MAAVScGezwAeWgFdGAIzKbVAblTZ8YADL0MZYmUo0GzNpw8-EKiwuKS0nKKqhoU2noG3EbGlnBwMHj0tJoOqADGcLScYDjiGNz0MD7UqACQCnAAygZ4GAAWvHxsXqQCdX54APwBXJ19taHh7MNgMvLKKqhqbAmGJqnpmdlgAD6u7p4k5HFgAN51BUUYYA0AKm14950+9OxYtHm+TKwco8EiYgkUlmUQWy10+jWKTSGSy2hO51qtUuxVIeHYZhgGHYPgazWY7U6dG+IUBkjUDiRKOuaPY6QAbooXgh6NxrqskngwjAYNRaZjsRS6rU0RgzKRaGBaQzogAGFSUChUACMYAAZGqpeiZcplQqlVQAEyUgC+lNF4slAzAgxucHujw6-GJzFJYSBGjYdweT34DjN6Gor3en2osW05zAYFQUepdvR+NaTr41XDYCUHKMwmlMEZ1GVaiEma5ObzhrUKgc0ajwGAAGJVXksmAEHBSABrFtstpgSpVNEARzM3DRCl7QLAAFotWKJTjuIxmAoKhgMlgY2A47REMzWddSqRypVqA0Ey1Cf8AEQeTiXoTKgSGgQAZiFUY3tbrhpKZQqVXoOA4DA3BNuUhRTjOlo4lAZgfGBkoYHAYDWJufZMjABzkAg3ZgO0BC0hgoQbnGGEeMcP6Hn+J4kOwiYXnwb7VmA3BQDQpHeLwnBZHkeBwKxxYaJGUaQRKG4mhuTFxnhACitBjlQ9AsmyYDsaQ1DXuiGB3mAD5gE+YCvhuqAmmoYZAA

**Comment by SamChou19815** [comment]
Flow is not designed to handle all possible dynamic patterns, and partial application is something that's unlikely to get good support. In this example, overloading is a better option.
