### ISSUE TITLE
Flow doesn't error when adding "void" variables to numbers

### ISSUE THREAD

**Issue by julienw** [facebook/flow#8217]
Flow version: 0.113

## Expected behavior

I expect flow to warn me when I try to do arithmetic computation but one of my variables has the type void.

## Actual behavior

Flow finds no error.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0CYUwxgNghgTiAEA3W8oC4kHsCWwDcAUAcjPAEbwC88AjIRQNTVSHEphWrwPl5A

**Comment by dsainati1** [comment]
This was originally intentional (since there is no runtime error here), but recent discussion among the team indicates we feel that the additional strictness here is probably worth it. We will investigate a fix.
