### ISSUE TITLE
`new this(...)` fails within class static methods

### ISSUE THREAD

**Issue by popham** [facebook/flow#822]
I want to create a class instance within a static method of the same class, e.g.

```js
class A {
  n: number;
  constructor(n: number) {
    this.n = n;
  }
  static create(n: number): A {
    return new A(n+1); // I'd like to generalize this to `new this...`
  }
}
```

In my particular use case, I'm extending the class many times to embellish it with different non-static methods; there is no need to include additional constructor logic.  I would like to avoid creating a `static create(...)` method within each of my extending classes, but the following fails:

```js
class A {
  n: number;
  constructor(n: number) {
    this.n = n;
  }
  static create<T>(n: number): T {
    return new this(n+1);
  }
}

class B extends A {
  someMethod(a: string): void {
    console.log(a);
  }
}

var a: A = A.create(5);
var b: B = B.create(5);

/*
someFile.js:7:12,24: constructor call
Constructor cannot be called on
someFile.js:1:7,7: statics of A

Found 1 error
*/
```

My extending classes are generated code, so this isn't a big deal in my case (no maintenance overhead and gzipping should vanish the verbose code from the wire).  The error message is obviously a false negative.

**Comment by samwgoldman** [comment]
@popham This is resolved by your latest contributions, right?

**Comment by popham** [comment]
Ugh.  Kinda.  Closing....
