### ISSUE TITLE
Flow doesn't work if intersection-observer polyfill is used

### ISSUE THREAD

**Issue by coolemur** [facebook/flow#8221]
Flow version: 0.113.0

## Expected behavior

1. Setup flow.
2. In app.js use "import 'intersection-observer';" polyfill.
3. Below this line use some // @flow code that should show some errors.

Flow should warn about error

## Actual behavior

Flow doesn't warn about errors, except when you use // @flow code above 'intersection-observer' polyfill.

**Comment by coolemur** [comment]
App.js example that shows "No errors!" (but it should):

```
import "intersection-observer";

// @flow
function foo(x: number): string {
  if (x) {
    return "x";
  }
  return "default string";
}

console.log(foo("2"));
```

**Comment by coolemur** [comment]
Basically flow doesn't work with other import/require modules.

**Comment by jcready** [comment]
The `// @flow` comment needs to be before all other lines.

**Comment by coolemur** [comment]
Sorry, I missed that. Thank you.
