### ISSUE TITLE
Array for..in loop

### ISSUE THREAD

**Issue by tilhi3** [facebook/flow#8222]
Flow version: v0.98

## Expected behavior
```
type MyItem = { stuff?: boolean, doSomething: boolean };
class A {
  someArray: Array<MyItem> = [];

  myFunc() {
    for (let i in this.someArray) {
      this.someArray[i].doSomething = false; //ok, because index exists always 
    }
    this.someArray.push({doSomething: true});
  }
}
```

## Actual behavior
```
type MyItem = { stuff?: boolean, doSomething: boolean };
class A {
  someArray: Array<MyItem> = [];

  myFunc() {
    for (let i in this.someArray) {
      this.someArray[i].doSomething = false; //cannot use for .. in because of string index 
    }
    this.someArray.push({doSomething: true}); //if type is {[string]: MyItem} i can't use array functions
  }
}
```

* Link to Try-Flow or Github repo: [link](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyWAkhngLZgC8YA3mAM4YCuUUA-AFxgBGccGHgCGAOwA0YACZwAynAp4MACwCWogOY9+gkaLABfANyoAxjGGNGYAIL1UYJgrw2ATq+FYebj1gA8xGSUAHw0YADaALomDmAUWABiLKKmABQAlPaOjlBwrmCpQhhgqiX6KqqMAHSMzj6emXSx2WAV1bWK9VjhqpFVMvKKFZphUMIwjHhGYMDAcADWkrx4psIsk2VSeAAeYDuVGNbjCJ7WzYbnbTV17p5VOOvKqXQDzsNara4seAbpJo4GVAGIA)

**Comment by gkz** [comment]
This is correct, you shouldn't use `for .. in` on an array. `for .. in` iterates over object keys. Use  a `for .. of` loop or a `for` loop with numeric index variable.
