### ISSUE TITLE
Optional chaining causes errors when desugaring does not

### ISSUE THREAD

**Issue by marcusdarmstrong** [facebook/flow#8229]
Flow version: 0.114.0

## Expected behavior

```
type MaybeEmpty = {||} | {| +test: string |};

const foo: MaybeEmpty = { test: "" };

foo.test?.length
```

I would expect no error for this (safe) dereference (as with the equivalent `foo.test ? foo.test.length : undefined;`).

## Actual behavior

```
    7: foo.test?.length
           ^ Cannot get `foo.test` because property `test` is missing in object type [1].
        References:
        5: const foo: MaybeEmpty = { test: "" };
                      ^ [1]
```

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4CiAtjtmALxgDeAPqwL5iss8DUGPAGcMALjAiATgEsAdgHNuHANzoAxnFkiwUOHHElyVWvSbMwgkeIBE1sCvS64AOksYA-M5h4FGABaOeq7CGGDuOkFuXj7y-mDiAK6yACZ4UHJ4yaqoQA

**Comment by TrySound** [comment]
The error is not about optional chaining at all. You cannot access object field which not exist in all types of union. This restriction makes manipulations safer.
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4CiAtjtmALxgDeAPqwL5iss8DUGPAGcMALjAiATgEsAdgHNuHANzoAxnFkiwUOHHElyVWvSbMwgkeIBE1sCvS64AOksYgA

To work around this you can provide common `kind` or `type` field. Check it's value will refine union to specific type.

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4CiAtjtmALxgDeAPmANYCWAdgCYAuMAHI8tbMLCsAvlJbtu-IcKgBXGDGEAaMAGoMeAM4YhxgE68A5lOkBudAGM4PY2Chw4QkuSrisjFk5eQRE1DW0wA2MhACIYsDt0LigwAAp3OAA6RT5GBiYVdU0AShZUMDcPTKiMAH5MmDweSwwAC1RpVGS0jOzgvIKxOixhUuZyyqya+sbmto70IA

**Comment by marcusdarmstrong** [comment]
I realize that the _error_ doesn't really have to do with optional chaining. My argument is that optional chaining should be subject to the same rules as the equivalent desugared syntax that does not trigger this error case—Namely that checking for properties that do not exist in all types of the union is not an error when done in a conditional context (which is exactly what an optional chain is).

The workaround here isn't viable because 1. the entire point of ?. is to provide syntax that avoids if statements 2. The actual type I'm working with here is generated from a GraphQL Union—adding a discriminant to make the type system happen has negative performance implications and isn't a reasonable thing to ask of all of our GraphQL usages.

**Comment by TrySound** [comment]
Union is quite complex thing. Optional chaining work in case of optional or nullable objects.
```
type A = {|
  b?: ?{|
    test: string
  |}
|}

a.b?.test
```

And actually with graphql you should have discriminant out of the box. It's called `__typename`. You can specify it in your query to refine specific type.

**Comment by marcusdarmstrong** [comment]
Using `__typename` is the performance penalty I was talking about—We shouldn't need to inflate our response sizes with unnecessary information to make our type system happy.

**Comment by noppa** [comment]
@TrySound 
> You cannot access object field which not exist in all types of union.

I think you can access such field if the accessing happens in a refinement, like an if statement or ternary, and then inside that statement where Flow has correctly refined the type to be some subset of the original union.

Slightly modified version of your example where everything works fine:
```javascript
if (foo.test) console.log(foo.test)
```
[Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCyAhlgEZ4CiAtjtmALxgDeAPqwL5iss8DUGPAGcMALjAiATgEsAdgHNuHANzoAxnFkiwUOHHElyVWvSbMwgkeIBE1sCvTSoYABS64AOksYAlGA1acDB4HvDybnpewr5AA)

I don't see why Flow couldn't interpret that that if we reach the RHS of `test?.length`, the LHS has already been refined to be `{| +test: string |}`.

Interestingly, 
```javascript
(foo.test || null)?.length
```
also passes but
```javascript
(foo.test ?? null)?.length
```
doesn't, so there might be some other weirdness or bugs here too :man_shrugging:

**Comment by SamChou19815** [comment]
Now the pattern is supported.
