### ISSUE TITLE
Re-export default or as default both fail

### ISSUE THREAD

**Issue by cesarandreu** [facebook/flow#823]
I'm trying to re-export the default export of a module, but it's failing.

The following syntax is valid ES6 module syntax ([source](http://exploringjs.com/es6/ch_modules.html#leanpub-auto-re-exporting)):

```js
// Re-export the Module's default
export { default } from './Module'
```

```js
// Re-export Module as the default
export { Module as default } from './Module'
```

## Reproducible example:

**A/A.js**
```js
/* @flow */
export default function a (value: number): number {
  return value
}
```

**A/index.js**
```js
/* @flow*/
export { default } from './A'
```

**B.js**

```js
/* @flow */
import a from './A'
a(123)
a('123')
```

**.flowconfig**

```
[options]
module.system=node
strip_root=true
```

**Output**

```
A/index.js:2:10,16: Unexpected token default

B.js:2:15,19: index.js
Required module not found

Found 2 errors
```

**Comment by lapanoid** [comment]
@samwgoldman Why it is closed? It will be fixed in 0.17? Have exactly the same now with 0.16.
