### ISSUE TITLE
Flow and index.js imports

### ISSUE THREAD

**Issue by camurai** [facebook/flow#8231]
This is not a bug but something I suggest including in the documentation for flow as I can see others running into a similar problem.

If you do not add // @flow to index.js files you have that are re-exporting your components, the type checking will not work on any imports from those index.js files.

Of course this makes perfect sense once I knew what the cause was. it was losing the types since it importing from a file that was not set up for flow (even though the source file was). It is very easy to forget those index.js files even exist though, and it caused some serious frustration and almost made me give up on flow before I found out what was happening. 

I highly suggest mentioning this in the documentation to save others from that headache and wasted time.

**Comment by gkz** [comment]
I feel like this isn't a common enough issue to put in the FAQ - in general if you haven't enabled Flow in a file it isn't going to type-check, I don't think we need to have this additional specific example
