### ISSUE TITLE
Types for generic incorrectly interpreted

### ISSUE THREAD

**Issue by zjaml** [facebook/flow#8233]
Flow version:
0.113.0
## Expected behavior
the following code works
```js
type Type<T: { name: string }> = T
const obj: Type<{ name: 'name' }> = { name: 'name' }
```
## Actual behavior
Got the following error:
```js
//Cannot instantiate `Type` because  string literal `name` [1] is incompatible with  string [2] in property `name` of type argument `T`.
const obj: Type<{ name: 'name' }> = { name: 'name' }
```

* Link to Try-Flow or Github repo:
https://flow.org/try/#0FAFwngDgpgBAKpKAeOAuGBvGA7AhgWynQGcQAnAS2wHMYBfAPhgF55gBjAe21Jk4CMAVugTQkWPIXQBySVGn0mrCQSIxZqhXWDAA9LpVT1crTArEYuGMQCu-cND4AzTDlUlyVWnQCEwANwAFIZqGoRa6CEelDT0AJRAA

**Comment by maartenschumacher** [comment]
The same happens for nested objects
```
type Works<T: { name: string }> = T;
const obja: Works<{ name: string, bar: string }> = { name: "foo", bar: "b" };

type DoesntWorks<T: { name: { foo: string } }> = T;
const objb: DoesntWorks<{ name: { foo: string, bar: string } }> = { name: { foo: "d", bar: "b" } };
// Cannot instantiate `DoesntWorks` because property `bar` is missing in object type [1] but exists in object type [2] in property `name` of type argument `T`.

// it is a subtype tho
({ name: { foo: "hi", bar: "hi" } }: { name: { foo: string } });
```
https://flow.org/try/#0FAFwngDgpgBA6gewE4GsDOAeAKgLhgbxgDsBDAWyjzRCQEsiBzGAXwD4YBeGLAbmAGMERajAQAjAFYk8iVJkKkKVGvQYAaGGJJJldRi3ZcF5SjABEAMwQIzGrTvNizLPqEiwAIgihoiIWejYeMZKBDBWCLqqLAac3HyCwiCikmJ4Xj5+AfLEJsHh1lGMdtpFTMyxRrmhhBF4ZgAmtpqljs4VzK4A9F0wtMm0aDAkMGgArmLg0DAgABYIwAAUIaa1heaztM329ZvtLPmKqwWRoyr6HQCUPEA

**Comment by lukeapage** [comment]
Its because the property is not read only. so you could cast to the object, mutate it to not be the string literal 'name' and then the original object in the original typing would be invalid..

https://flow.org/try/#0FAFwngDgpgBAKpKAeOAuGBvGBqAdgQwFsp0BnEAJwEtcBzGAXwD4YBeeYAYwHtdyZuAIwBW6BNCRY8REjADkBYnMYt2WRbIUzlDYMAD0+9TPRaljGFVIx8MUgFdB4aAIBmmGBrKUa9BgEJgAG4ACmNiUw0ddHDZcmo6RgBKIA

**Comment by lukeapage** [comment]
e.g. to stop cases like this:

https://flow.org/try/#0GYVwdgxgLglg9mABAQwDwBUBciDeizIC2AptgM5QBOMYA5ogL4B8AFAEbboCUuAUIojYA6AiUQBeRAHIwcKPiLEpAbn6JKxKCEpI2qhqt5QAngAdiiAEITcAHzWjS0x1LW2DvXhAQVEcNgBW2NaSeI7YMopSjIbILP4BXKpAA

I wasn't sure how to make your example fail exactly though, but I guess its linked to the same principle

**Comment by mvitousek** [comment]
@lukeapage is correct, you can read more about this in our docs here: https://flow.org/en/docs/lang/depth-subtyping/
