### ISSUE TITLE
Flow stops type checking when using defaultProps in combination with calling a function as a property initializer

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#8239]
Flow version: 0.114.0

## Expected behavior
There seems to be something strange going on when combining default props in a React component with an initializer function that receives `this` as a parameter, when the function is defined as having overloads. The example below should showcase the problem. Commenting out either of the lines mentioned in the code, cause Flow to start type checking the component again, but having them all uncommented makes Flow stop type checking.

## Actual behavior
Flow does not show any error, even though the component has a required prop that is not being passed. It also doesn't fail when passing random props. It's basically not type checking at all anymore.

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAEIA2yAFnALxwA3nThwAFMAB2qGMim4sALjgBhEpClYpMAJQqAbhGAATADSiJ+uEdNwA9PbgBGAHRqSIbfAgBXeDA8wOic0mzyJnAQAEaoWFAGbIFsuBoQWjoAkjJyCmwEyMCccAScEADuNsihJsgwwOmuTXQAvvR0Jli43JRVUHDR3DwqXLz0YmKMLGwACsRg6IJCAD6WBBAQKrJQ0gDmdMttDN1o6Org6d5wWAAeMNom6Nh4MK7nmt4APHMQCwB8wksjjgACZ3E13NA4KkQF4dFF-HBknBOgVfJwYD8FnBQloUFJIjE4gkkjwUmkMjBsrJ5IoSoViqUKlUanUGlJLDT6rgUVg0RisYthEdLJQCfFxLpARM4JQYL4oFI4FJ0ZxxnAWgwxMCAMzgppRfowuE+RHIgD6yAAslhAhBIp0TlA2el8YTYvFEkiydCKd5qbk6QUiiUypUDNVTC6OWJLTa7ZFBINeOJAsFdDQ4K0GMCmZVUDw-JxIoFiJV5NcoMR+mTetEushfHE4AADdYQFtwYJSMjwMCUOI6Oi3SCwX05X0XSkB2lsQSfd6XeH2P70IA

**Comment by leoasis** [comment]
Another thing I found is that if we explicitly type `defaultProps`, that seems to make Flow type check things again: https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQdMAnmFnAEIA2yAFnALxwA3nThwAFMAB2qGMim4sALjgBhEpClYpMAJQqAbhGAATADSiJ+uEdNwA9PbgBGAHRqSIbfAgBXeDA8wOic0mzyJnAQAEaoWFAGbIFsuBoQWjoAkjJyCmwEyMCccAScEADuNsihJsgwwOmuTXQAvvR0Jli43JRVUHDR3DwqXLz0YmKMLGwACsRg6IJCAD6WBBAQKrJQ0gDmdMttDMyscAAiWAW+nDBzEAsCwsuH7d1o6Org6d5wWAAeMG0JnQ2DwMFcn003gAPHcFgA+YSWRxwABM7ia7mgcFSIC8Oii-jgyTgnSuNzhITCKCkkRicQSSR4KTSGRg2Vk8kUJUKxVKFSqNTqDSklk59VwpMuyGut3mqBUF3JcvuizgAHlogArLrgohYLAALyw4iELV07TElFp8XEuiREzglBgvigUjgUmunHGcBaDDEKIAzBimlF+rj8T4iSSAPrIACyWECEEinTeUGF6RpdNi8USxOZONZ3g5uW5BSKJTKlQM1VMmdFYjjieTkUEg144kCwQtcFaDBR-MqqB4fk4kUCxEq8l+UGI-WZvWiXRlcTgAAN1hB13BglIyPAwJQ4jo6P9ILAizki182aWuWxBNDId8CfZ4fQgA

**Comment by SamChou19815** [comment]
Now it's working as expected.
