### ISSUE TITLE
Logically equivalent intersection/union constructs behave differently

### ISSUE THREAD

**Issue by popham** [facebook/flow#824]
Under Flow, the following are logically equivalent:
1. `Discr & (B | C)`
2. `Discr & B | Discr & C`
3. `Discr & K`, where `type K = B | C`
(I verified that `&` has higher precedence than `|` over [here](https://github.com/popham/flow/blob/intersect-prec/tests/intersection/intersection.exp#L2-L8), [here](https://github.com/popham/flow/blob/intersect-prec/tests/intersection/assoc.js), and [here](https://travis-ci.org/popham/flow/jobs/80765062#L333)).

Flow handles them inconsistently (in a case involving circular importing):

```js
// main.js
import { B, C } from "./extensions";

type K = B | C;

type Discr = {
  which(): number;
};

export default class A {
  static sMethod(p: B | C): bool {
    return false;
  }
  static tMethod(p: Discr & (B | C)): bool {
  /*
    main.js:1:13,13: C
    This type is incompatible with
    main.js:1:10,10: B
  */
  //static tMethod(p: Discr & B | Discr & C): bool { /* OK */
  //static tMethod(p: Discr & K): bool {
  /*
    main.js:1:13,13: C
    This type is incompatible with
    main.js:1:10,10: B
  */
    if (p.which() === 5) {
      throw new Error("Peep");
    }
    return this.sMethod(p);
  }
}
```

```js
// extensions.js
import A from "./main";

export class B extends A {
  which(): number {
    return 1;
  }
}
export class C extends A {
  which(): number {
    return 2;
  }
}
```

**Comment by avikchaudhuri** [comment]
This will be fixed in an upcoming release.
