### ISSUE TITLE
string literal treated as any if nested in object hierarchy

### ISSUE THREAD

**Issue by thecotne** [facebook/flow#8244]
Flow version: v0.114.0

## Expected behavior

should error when type does not match

## Actual behavior

problems are detected only if value is not nested

* [Try-Flow](https://flow.org/try/#0PTAEAEDMBsHsHcC0BnALgJwJYGNUCg9UBPABwFNQAlWAV1QoF5QBvAHz1FAGpoBDI2qgBcoAOTZYqAHZlReVgF8CxcqACysACY1oZAMqpe9UEzYdu6QWRHU6ZeUryay2PugoA3XulABbLTr6hvQiGtq6Bkb2eMjwmKjYABagABT+4UFRAHSWdll8AnQAlCzm2LzIFOKSMqJCIKCwANZlFVVSkqDIsKAS0rL1YMiJtNCaoGToluh4jpiQqemBkfQ5Vvn8giYMTNX9oiXMCg3NePOLARHBZGt5BVs7ux2oXT19tYfHQyM645PTZwWaUumVWuVW9zo2yYABYAEyfBrDUZ-KawGZOFxuTzeUDg6xUKwEWLxJKpfEbQqoQ6tSpid4DE4tTjlOmiZ6vXo1Rlgf7o0CYZCNFpzIEUyEvR707kHFhfYWA8nrCXQsQc7pc-aI3lonyChXnFLizZQqXw7UTXUCoXNIA)

```js

// @flow-strict

type Route = {|
  +layout: 'cotne'
|}

type ModuleState = {|
  +route: Route
|}

declare var moduleState: ModuleState

switch (moduleState.route.layout) {
  case 'cotne':// ok
  case 'not so cotne':// should error
}

if (moduleState.route.layout === 'cotne') {}// ok
if (moduleState.route.layout === 'not so cotne') {}// should error
if (moduleState.route.layout === 42) {}// should error

declare var route: Route

switch (route.layout) {
  case 'cotne':// ok
  case 'not so cotne':// error is ok
}

if (route.layout === 'cotne') {}// ok
if (route.layout === 'not so cotne') {}// error is ok
if (route.layout === 42) {}// error is ok

```

**Comment by thecotne** [comment]
workaround with typeof

```js
// @flow-strict

type Route = {|
  +layout: 'cotne'
|}

type ModuleState = {|
  +route: Route
|}

declare var moduleState: ModuleState

const layout: typeof moduleState.route.layout = moduleState.route.layout

switch (layout) {
  case 'cotne':// ok
  case 'not so cotne':// should error
}

if (layout === 'cotne') {}// ok
if (layout === 'not so cotne') {}// should error
if (layout === 42) {}// should error

```

**Comment by thecotne** [comment]
@dsainati1 this is not about refinements actually since i am not trying to refine anything in my examples.

**Comment by SamChou19815** [comment]
It's now fixed
