### ISSUE TITLE
How does flow use with react native and option 'all=true'?

### ISSUE THREAD

**Issue by wolrd** [facebook/flow#8255]
I want use option 'all=true'. But I don't want to parse node_modules folder.
But I receive an error: Cannot resolve module react-native.

My config:
```
[ignore]
.*/node_modules/*

[include]

[libs]

[lints]

[options]
all=true

[strict]

[untyped]
.*/node_modules/react-native 
```

Another config (doesn't work too):
```
[ignore]
.*/node_modules/*

[include]

[libs]

[lints]

[options]
module.system.node.resolve_dirname=node_modules
all=true

[strict]

[untyped]
.*/node_modules/react-native
```

Any ideas?

**Comment by jamesisaac** [comment]
Would `[declarations]` solve your problem? https://flow.org/en/docs/config/declarations/

Also, with your `[untyped]` example. seeing as you didn't end the regex with `.*`, I don't think it will actually be matching any files in `react-native`.

**Comment by wolrd** [comment]
@jamesisaac 
"Would [declarations] solve your problem? https://flow.org/en/docs/config/declarations/"
how to use it?

**Comment by jamesisaac** [comment]
```
[declarations]
<PROJECT_ROOT>/node_modules/react-native/.*
```

But I haven't used it with `all=true`, so can't tell you if that would cause any problems.

**Comment by wolrd** [comment]
@jamesisaac 
I got another error. What do you think about it?
Error:
 ```
┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ App.js:43:16

Cannot create Text element because property createElement is missing in exports [1].

     App.js
     40│           )}
     41│           <View style={styles.body}>
     42│             <View style={styles.sectionContainer}>
     43│               <Text style={styles.sectionTitle}>Step One</Text>
     44│               <Text style={styles.sectionDescription}>
     45│                 Edit <Text style={styles.highlight}>App.js</Text> to change this
     46│                 screen and then come back to see your edits.

     node_modules/react/cjs/react.development.js
```

**Comment by SamChou19815** [comment]
[declarations] should be the solution
