### ISSUE TITLE
Developing lib files is developer unfriendly when flow crashes on edit

### ISSUE THREAD

**Issue by 0xR** [facebook/flow#826]
Flow currently has no support for converting typescript .d.ts files. Also most libraries don't have flow support. Therefore if you want to do type checking on a library you need to write interface files. Currently each time you edit an interface file, the server detects an edit and exits with the following message: 
```
Modified lib file: somedir/interfaces/somelib.js
flow server is out of date. Exiting.
```

A restart of the server takes around 15 seconds. This means that developing interface definition files is so developer unfriendly that I don't want to bother.

This issue is a feature request to support reloading lib declarations just like any other file with type declarations in flow. This will make me want to use flowtype in my projects and write interfaces for the libraries I use.

You can +1 this issue if you agree. Yes, the comments will get messy, but github does not provide an alternative to show interest.

(I looked for duplicate issue's, but I couldn't find one)

**Comment by 0xR** [comment]
Upon further investigation, the 15 second startup time is due to not ignoring node_modules. Which is something I forget regularly. The startup time is now 3.3 seconds. 

As a workaround for the server crashing I am using a command like this:
``` bash
while true; do flow server; done
```

This gives something close to the workflow I would need, but it is by no means ideal.

**Comment by samwgoldman** [comment]
I can't reproduce this and I suspect that something else is going wrong on your end here. Flow should reload to pick up changed lib files, but it shouldn't just shut down. It seems like you have different versions of Flow—how are you integrating Flow into your workflow?

**Comment by 0xR** [comment]
That's interesting, this was on the latest flow version, but I've been
trying many versions to see whether I can use flow for my project. I was
under the impression shutting down was default behavior. I'll make a
minimal example when I have time.

Op za 3 okt. 2015 02:32 schreef Sam Goldman <notifications@github.com>:

**Comment by moll** [comment]
Seeing the same thing here with Flow v0.20.1 off of Homebrew, built from source. Having a directory in `[libs]`, modifying a file and seeing the server exit. That does _not_ occur when modifying a regular `.js` file not under `[libs]`.

**Comment by 0xR** [comment]
On flow 0.27 this issue seems to be resolved. The startup time is much better by default. Also having ide integration will ensure flow is automatically restart on file save.

Therefore I'm closing this issue.
