### ISSUE TITLE
Regression: Matching union of tuples

### ISSUE THREAD

**Issue by kkaefer** [facebook/flow#8263]
**Flow version:** 0.109.0 and above. 0.108.0 and below work fine.

## Expected behavior

Flow accepts this code.

## Actual behavior

[Code](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMQJbQpYBOoAvKANoB2ArgLYBGpAuqAD7UDOKJ+NAOasA3Mkh0aAYxT5YNUFPkA3UigAUkQsRIAuPNtIBKUAG9EoS6C1FSAOm7R8UrOoAMRsQF9EQA):

```js
// @flow

type Filter = [number] | [string];

function convert(filter: Filter) {
    filter.slice(0);
}
```

Error reported is:

```
Cannot instantiate tuple type because string [1] is incompatible with number [2].

        2│
 [2][1] 3│ type Filter = [number] | [string];
        4│
        5│ function convert(filter: Filter) {
        6│     filter.slice(0);
        7│ }
        8│
```

(edit: shortened example)

**Comment by dsainati1** [comment]
I have identified the issue here; fix is in progress.
