### ISSUE TITLE
Default parameter initialisers can't refer to other parameters

### ISSUE THREAD

**Issue by sebmck** [facebook/flow#827]
```javascript
/* @flow */

function foo(a, b = a) {}
```

Incorrectly reports an error of:

```
$ flow check

/Users/sebmck/Scratch/flow-test/index.js:3:21,21: identifier a
Could not resolve name

Found 1 error
```

Default parameter initialisers should allow reference to all parameters to the left.

**Comment by samwgoldman** [comment]
Nice catch. This feels like a good first bug, if you're so inclined.

**Comment by sebmck** [comment]
There are a few other (possibly related) bugs with default parameters that I've found that I'll try and get a minimal reproduction of. Currently enabling Flow on the entire Babel codebase since let/const was added :tada: (@samwgoldman :heart:)

**Comment by samwgoldman** [comment]
I take it back about this being a good first bug—this is going to require some surgery.

**Comment by samwgoldman** [comment]
@sebmck Should object-destructured params be able to refer to keys bound in any order?

```javascript
function f({ foo, bar = baz, baz = foo }, qux = baz) {
  return [foo, bar, baz, qux];
}
f({ foo: "foo" }) // => ["foo", null, "foo", "foo"] or ["foo", "foo", "foo", "foo"] ?
```

Babel says `bar` is `null`, but I want to confirm that's the spec behavior, and I imagine you're better at interpreting the spec than I am. :wink:

**Comment by samwgoldman** [comment]
For flow, the above question isn't exactly relevant, because we don't support default values in destructurings, so I went ahead with a PR. The PR should also make it easier to support destructuring/defaults in the future, too.

**Comment by jozanza** [comment]
@samwgoldman Thank you! This is awesome. Hope it gets merged soon :+1:

**Comment by sebmck** [comment]
@samwgoldman That should be a TDZ error. The `null` is actually `undefined`, it's just that the Babel REPL serialisation is shitty.

**Comment by samwgoldman** [comment]
@sebmck Cool. We should handle that as an error once we support destructuring+defaults, assuming the method in my PR survives code review. :pray:

**Comment by samwgoldman** [comment]
Fix already landed in master.
