### ISSUE TITLE
Exact type downtyped to "any" after invalid comparison

### ISSUE THREAD

**Issue by nrabinowitz** [facebook/flow#8270]
Flow version: 0.116.1

## Expected behavior

```
type Field = {|id: string, type: 'NUMBER'|};
type Selection = {|field: Field|};

function run(selection: Selection): string {
  const {field} = selection;
  if (field.type === 'UNKNOWN') {
    // Should be a Flow error
    return field.unknownProperty;
  }
  return 'test';
}
```

## Actual behavior

No Flow error occurs. May be a dupe of #7194, but Flow errors correctly when the comparison uses a known value:

```
type Field = {|id: string, type: 'NUMBER'|};
type Selection = {|field: Field|};

function run(selection: Selection): string {
  const {field} = selection;
  if (field.type === 'NUMBER') {
    // Is actually a Flow error
    return field.unknownProperty;
  }
  return 'test';
}
```

Note that this does not occur when you pass `Field` in as the function argument - the indirection of having `Field` as a property of the argument seems necessary for the bug.

* Link to Try-Flow or Github repo: https://flow.org/try/#0FAFwngDgpgBAYgSygGwCYwLwwN4B8GoBcMAziAE4IB2A5gDQzjTEDkAcgKoCyAQgKIAlFrgC+AblCRYAZRRQAxiAQB7Kphy4AZkjTFEKVKInBNAVyqKVa8uYAUJOZdXFZyBUtUBKYmUq0cwACQ8qpkONoGIuoObk5UEjAwgQiaMLYRaAB0TLAYeTAsHGwA0mwA8gDqbCyeAYn1MORQIKbkahmomeYA1lTKAO5UAArkytDk4An1IkFNLW0FIFBkLBIiQA

**Comment by jamesisaac** [comment]
It's because Flow treats that branch of code as unreachable, so doesn't check/report errors.  Some discussion in #4134 ... I think it would be nice if this could be linted against.  But closing as duplicate as there are quite a lot of issues on this already.
