### ISSUE TITLE
Type incompatibility despite identical types

### ISSUE THREAD

**Issue by DullReferenceException** [facebook/flow#8272]
Flow version: 0.116.1

## Expected behavior

This assignment should succeed since the type of the parameter and the type of the property are identical:

```
export class EntityList<A> {
  entities: Array<$Shape<A>>;
  constructor(entities: Array<$Shape<A>>) {
    this.entities = entities;
  }
}
```

## Actual behavior

Instead, I get the error:

> Cannot assign `entities` to `this.entities` because `A` [1] is incompatible with `$Shape` of `A` [2] in array element.

This can be demonstrated at [this Try Flow repro](https://flow.org/try/#0KYDwDg9gTgLgBAYwDYEMDOa4FEB2MCWMAngDL5owA8AggHxwDeAUHHMHofsGgFxzVQoKIpQAkAZQAWKMMBq1aAbhaIIOClACuCGNAAU7AgW58BQkROmz5tAJSMVrGJPIA6Q525wAvGw7G0ZVYAXyZQoA).

**Comment by fabiomcosta** [comment]
could it be related to https://github.com/facebook/flow/issues/8242 ?

**Comment by amccloud** [comment]
Doesn't look like #8242 to me

I think this is `$Shape` working as expected. `$Shape<T> !== $Shape<T>` the same way `T === T` 

I was able to get this to work as expected by [creating a type `B: Array<$Shape<A>>` ](https://flow.org/try/#0KYDwDg9gTgLgBAYwDYEMDOa4FEB2MCWMAngDL5owA8AggDRwBCAXHNVFCkZQCQDKAFijDAaAPnFwA3gCg4cYHkL5gaFgwDcsxBBwUoAVwQxoACgUECKtQEopWuTH7kAdOaUq4AXnmLLaTXIAvtLB0tIIOhRwSOTw3jjAAO7YvqSxJgDaknAwKjAsAIwATADMcIEAutaa0jEUrr7KaBkADBXOOBAwAJI4uBZEcAD0Q9jgwEbAACZwAGYo+Ej6UMBwJonQANaY+LNwAES5FPvW0kA)

**Comment by TrySound** [comment]
Use `$ReadOnlyArray` instead. I use always use it and never have this problem.

**Comment by TrySound** [comment]
Also $Shape in two cases may produce different types. This works
https://flow.org/try/#0KYDwDg9gTgLgBAYwDYEMDOa4FEB2MCWMAngDL5owA8AggFxwDeAdCwL4A0cAQvQCQDKACxRhgNAHzjGAKDhxgeQvmBp61KFBRFKXcQG5ZiCDgpQArghjQAFAoIEVajVp3iAlDLlyYg8kztKKnAAvPKKDmgGcqzSMUA

**Comment by DullReferenceException** [comment]
`$ReadOnlyArray` [has the same problem](https://flow.org/try/#0KYDwDg9gTgLgBAYwDYEMDOa4FEB2MCWMAngDL5owA8AggHxwDeAUHHMHofsGgFxwAkAJWAoAJgHkcSItShQURSvwDKACxRhgNWrQDcLRBBwUoAVwQxoACnYEC3PkJESpMuQqVqNWurQCUjAasMKrkAHS2nNxwALxsHPZo+qwAvkxpQA).

Will see if a secondary generic type as you showed in the second case works for this scenario.

**Comment by gkz** [comment]
Works if you use the safe replacement, `$Partial`:
https://flow.org/try/#0KYDwDg9gTgLgBAYwDYEMDOa4FEB2MCWMAngDL5owA8AggHxwDeAUHHMHofsGgFxzVQoKIpQAkABRSx8KJDVq0A3C0QQcFKAFcEMaAAp2BAtz4ChIiVIKz5tAJSMVrGAAtyAOkOducALxsOYzRlVgBfJnCgA

https://flow.org/en/docs/types/utilities/#toc-partial
