### ISSUE TITLE
Spreading identical values with properties and indexers creates errors

### ISSUE THREAD

**Issue by chrbala** [facebook/flow#8276]
Similar to #8178, but with an additional property. Spreading identical values with properties and indexers creates errors.

```javascript
export type Trie<T> = {
  [string]: Trie<T>,
  _?: T,
};

const x: Trie<number> = { };
const y: Trie<number> = { };

const z: Trie<number> = { ...x, ...y };
```

Flow version: 0.117.0

## Expected behavior
Two values with identical types should always be spreadable

## Actual behavior
Error is thrown:
```
    11: const z: Trie<number> = { ...x, ...y };
                                           ^ Cannot determine a type for object literal [1]. `Trie` [2] cannot be spread because the indexer string [3] may overwrite properties with explicit keys in a way that Flow cannot track. Can you spread `Trie` [2] first or remove the indexer?
        References:
        11: const z: Trie<number> = { ...x, ...y };
                                    ^ [1]
        9: const y: Trie<number> = { };
                    ^ [2]
        4:   [string]: Trie<T>,
              ^ [3]
```

* Link to Try-Flow or Github repo: [tryflow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAFXwEsMAeKgPjAF4wBvVMMAbQDOhOgDsA5gF0AXNTqMWAGh5gA+gH4ZVJQF8A3OgDGcEULBZNchiICuAWwBGGfKw6cwe1EZPFSF+lbtHZ3Yud31PY1MALz9GGwcnF1CAOlSsBTBU5NIw1CA)

**Comment by chrbala** [comment]
Interestingly, this works if passed into a function, despite having the same effect.

```javascript
/* @flow */

export type Trie<T> = {
  [string]: Trie<T>,
  _?: T,
};

const x: Trie<number> = { };
const y: Trie<number> = { };

const merge = <T>(a: T, b: T) => ({ ...a, ...b });
const z: Trie<number> = merge(x, y);
```

Test on [tryflow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAFXwEsMAeKgPjAF4wBvVMMAbQDOhOgDsA5gF0AXNTqMWAGh5gA+gH4ZVJQF8A3OgDGcEULBZNchiICuAWwBGGfKw6cwe1EZPFSF+lbtHZ3Yud31PY1NbJzFKDiZmAAoAQ00FMHtNAEp2VkS3ADoi5PSigvt3LP0vUwAvP0YbBycXMGj8WMSsdNIq1CA).

**Comment by jbrown215** [comment]
That's an unsoundness in generic checking.

I have work in the pipeline that allows this, but it exposes some nastier issue somewhere else in the type checker that makes it unshippable. Specifically, it creates an error in a library definition with no references to actual source code.

**Comment by grit96** [comment]
A similar bug makes it impossible to spread on indexed object into a literal object matching the same type.

[tryflow 1](https://flow.org/try/#0PTACDMBsHsHcCgAuBPADgUwAQEkB2ATdAD3X0wF5MBvTAbQGdEAnAS1wHMBdALk1wFcAtgCN0TTAF8A3PADG0XI0zJeeQiTKUqwgIZNeAVgnw5CpQC9VBYqQrVw0aLwDMAGkwA6L8mlA)

[tryflow 2](https://flow.org/try/#0C4TwDgpgBAEhCGATCAnAzgFXNAvFA3lANoB28AthAFxRrAoCWJA5gLo12MtQC+A3ACgBoSFABiEYAGMAFgHkwwBgHsSmbFDz4APgKhRKwGcsQB+GgHIYAUQCCAEQtRtUCwHFrGJy4sAFOQDKXs6uvgCqwT6+thgAwjDervbWADKe1hYANHpQAEYmIOa09EzM2foyCMjoRXBIqOqQ5VBSKBDIJErwADZoRRbK5AzAiRZoFBAAtMqMzEyjTFLdAK7IWTlSM23d8EqqAJJmHCUsAtr8QgIAZsskUnskUAD6zJJ11WgAFMqKKmo0pgk0nkv1UjQgAEoaO8GlhRPgcvpNmpgFBKvV0NCqrCNHhvqC1FAAGREqA-B5oAB06I+EKgpjJBKpNIaUBo+AuiKgbWAyxQjwR+iFQtsUikEEUlngYDA3QYUl2fwA9AArNCqdbC4W+FDwZjkeCWEjKSYK2QQTVa-QWWLwc2TWKqejKboWI0ms2VS1WiwAD0mbQAjssIHR2pMAO7DGRu1wADQAsikYMBgGAAEoQYOhkbNK3WX1gBhtNCWSYARm9WspNZZ6C5Fx4AiAA)

**Comment by SamChou19815** [comment]
This is expected behavior that we don't change
