### ISSUE TITLE
experimental.well_formed_exports is on by default in React Native 0.62, yet has unclear error messages and is undocumented

### ISSUE THREAD

**Issue by jamesisaac** [facebook/flow#8279]
[This commit](https://github.com/facebook/react-native/commit/d9b84450a19c95eeae1f5e3c6a32983690e1ecbe) (cc @panagosg7 ) has added these config options to the default `.flowconig` template in new React Native projects starting from 0.62:

```
experimental.well_formed_exports=true
experimental.types_first=true
```

From what I can see, neither of these options are documented anywhere (would expect them to be [here](https://flow.org/en/docs/config/options/#toc-available-options)).

The issue I think people will have with `experimental.well_formed_exports=true`, is that it will introduce hundreds of errors into any mature codebase.  The [Flow docs for React components](https://flow.org/en/docs/react/components/#toc-stateless-functional-components) suggest to type functional components like so:

```js
function MyComponent(props: Props) {
```

This will lead to an error under `well_formed_exports`, as (from what I understand) they need to be typed like so:

```js
function MyComponent(props: Props): React.Node {
```

The error message doesn't even make it clear that this option is the reason.  It makes it sounds like it's the lint rule's fault (`signature-verification-failure=warn`), but turning that to `off` makes no difference:

```
Cannot build a typed interface for this module. You should annotate the exports of this module with types. Missing type annotation at function return: (`signature-verification-failure`)
```

The only way I was able to remove these hundreds of new errors (as I didn't have time to update hundreds of export signatures), was process of elimination trying disabling various lines in the flowconfig until the errors disappeared.

**Comment by panagosg7** [comment]
Thanks for bringing this up @jamesisaac ! I'll remove these flags from the template, at least until we formally announce types-first mode, and update with the necessary documentation.

**Comment by panagosg7** [comment]
Sure! I'll request the pick once the fix is landed.

**Comment by jamesisaac** [comment]
Fixed in the latest RC 👍 https://github.com/react-native-community/releases/issues/157#issuecomment-585877321
