### ISSUE TITLE
Async function can not use generic types

### ISSUE THREAD

**Issue by HsuTing** [facebook/flow#8281]
Flow version: 0.117.1

## Expected behavior

`async function` should work.

## Actual behavior

Can not work.

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBARgQwE4wLwwDwDUBcMDeMA1gKYCee0SAlmAOYwC+AfABQBuCANgK4l5YAlJSg16aZjE68SAOlJkA3AChQkWADMQINDAQQyYYJlwFi5EWIYsO3PgOEwACkhABbahBIYqtOpNRJaT55ckUgA

**Comment by SamChou19815** [comment]
It now works, not sure when it was fixed.
