### ISSUE TITLE
charAt, charCodeAt and codePointAt are weird

### ISSUE THREAD

**Issue by nnmrts** [facebook/flow#8284]
Flow version: 0.117.1

## Expected behavior

```js
const string = "ABC";

string.charAt();
string.charCodeAt();
string.codePointAt();
// ^ no errors

const maybeANumber = string.codePointAt(100);

Math.round(maybeANumber);
// ^ errors because maybeANumber could be undefined

if (typeof maybeANumber === "number") {
	Math.round(maybeANumber);
	// ^ should be fine now because we checked it this time
}

```
## Actual behavior
```js
const string = "ABC";

string.charAt();
string.charCodeAt();
string.codePointAt();
// ^ errors "Cannot call `string.[...]` because  function [1] requires another argument."

const maybeANumber = string.codePointAt(100);

Math.round(maybeANumber);
// ^ doesn't error but maybeANumber could be undefined

```

* Link to Try-Flow or Github repo:
[here](https://flow.org/try/#0MYewdgzgLgBNBOBLMBzGBeGAiAggIQGEsBuAKFIWRQDpgALAQ3hygAoBKMy1Wx+AkABMApiw5coSHqBEAFEMihjOpAPSqYAPRjD48EPAjYCDMGBCxgDADbWYAA240A2tTcBdezABGwqwFcIYRgYADN-MGAoRHAYZwBGdxh4YQBHf0QUo1MLOl0YJhR-AFthMChqLHJQSFhihgBPXxwAORLfeAw4SSpaIWF5RTF4gAYRlVIAWQYoOmp9CMFWeqbRNuKOlXUtGEEQYQgwAHJYXX1O7386xub1jphQf2tBH2DF4VDkYUEgA)

## Explanation

In my opinion, the definitions of these methods are kind of wrong, because

1. they don't actually require an argument; passing no argument means `NaN` which means 0 in this context
2. `codePointAt` could return `undefined` when `pos` is greater than the string's length ([ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt#Return_value))
3. there's no reason for the `charAt` parameter being called `pos` instead of `index` while the others are not ([ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/charAt#Parameters))
	- MDN only calls the `codePointAt` parameter `pos` ([ref](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/codePointAt#Parameters))
	- TC39 calls all of them `pos`, but also "index" in their explanations ([ref](https://tc39.es/ecma262/#sec-properties-of-the-string-prototype-object))
	- we developers probably would all call them `index`

*Point 1* is debatable though, because ECMAScript actually specifies this:
**String.prototype.charCodeAt ( *pos* )**
and not
**String.prototype.charCodeAt ( [ *pos* ] )**
which they normally do for actually optional parameters, but in this case, `pos` will always get converted to `NaN` if it's undefined anyways. And passing `NaN` to those methods always returns the first index.
BUT, for example the flow definition of the global function `parseInt` is technically also not following ECMAScript. Flow says that `parseInt` accepts `mixed` as string, but it doesn't. And it says that `radix` is optional, but it actually isn't. Well, it won't throw, but almost every function of core JavaScript won't throw because of type-juggling and intelligent implementation. I get why Flow allows `mixed` here, otherwise we would have a pretty hard time checking our strings.
Same goes for `isNaN` for example. Would be weird if Flow errors on `isNaN("test")` just because we wanted to check that value, right?
In my opinion, `string.charCodeAt()` to get the first index should be allowed. It's a common pattern.

*Point 2* should be pretty clear.

*Point 3* is not **that** important but I think we should decide on one parameter name for all three methods here.

So my proposal is that this:
```js
	// ...
	charAt(pos: number): string;
    charCodeAt(index: number): number;
    codePointAt(index: number): number;
	// ...
```
should be this:
```js
	// ...
	charAt(index?: number): string;
    charCodeAt(index?: number): number;
    codePointAt(index?: number): number | undefined;
	// ...
```
or maybe just this:
```js
	// ...
	charAt(index: number): string;
    charCodeAt(index: number): number;
    codePointAt(index: number): number | undefined;
	// ...
```

Thoughts?

**Comment by Brianzchen** [comment]
I like this. I think it adds more protection to a codebase to prevent runtime errors. The same thing happens with `'string'[123]` which is defined as always returning a string but should be either `string | void` which I've seen a few complaints about this before.

For being optional params, I think the current impl is fine because the function is quite useless if you pass nothing in. This can help to ensure you're writing useful code.

Thoughts @nnmrts ?

I'll raise a PR and see if it sticks.
