### ISSUE TITLE
Method 'replace' is missing in DOMTokenList

### ISSUE THREAD

**Issue by w01fgang** [facebook/flow#8285]
## Missing/Incorrect APIs
`replace` method is missing in DOMTokenList

## Relevant documentation
https://developer.mozilla.org/en-US/docs/Web/API/DOMTokenList/replace

**Comment by w01fgang** [comment]
Am I right that the definition should be added here?
https://github.com/facebook/flow/blob/master/lib/dom.js#L1331

**Comment by jamesisaac** [comment]
Yup, that would be the right place.
