### ISSUE TITLE
Can't use `implements` as an object key

### ISSUE THREAD

**Issue by sebmck** [facebook/flow#829]
Not sure if it's related to just a library file but I'm currently unable to use reserved words as property names. I have the following declare class:

```javascript
declare class BabelNodeClassDeclaration extends BabelNode {
  type: "ClassDeclaration";
  id: BabelNodeIdentifier;
  body: BabelNodeClassBody;
  superClass?: void | BabelNodeExpression;
  decorators: any;
  typeParameters: any;
  superTypeParameters: any;
  implements: any;
}
```

Note the `implements` property name. This causes the parser to fail with:

```
[LIB] types.js:365:3,12: Library parse error:
[LIB] types.js:365:3,12: Use of future reserved word in strict mode
```

However if I wrap `implements` in quotes like:

```javascript
"implements": any;
```

then I get a different error, this time not from the parser of:

```
[LIB] types.js:522:3,11: Library type error:
[LIB] types.js:522:3,11:
illegal name
```

Is there anyway around this? I'm unable to change the name of that property and need to annotate it.

Any help is appreciated, thanks!

**Comment by mroch** [comment]
`type Foo = {implements: string};` also errors, so I don't think it's related to being in a library file

**Comment by sebmck** [comment]
@mroch Wasn't 100% sure whether or not the "Library parse error" message was specific or more general.
