### ISSUE TITLE
Incrementaly migration Flow to Typescript.

### ISSUE THREAD

**Issue by Little001** [facebook/flow#8293]
I have two problems with migration.

**Importing types/classes/(from TS),... in FlowJS**
https://stackoverflow.com/questions/59993606/import-typescript-file-in-flowjs-eslit-flow-cannot-resolve-module

**Importing types/classes/(from FlowJS),... in TS**
Same problem with **ESLINT**

Did somebody solving this issue?

**Comment by Little001** [comment]
Why did you closed this issue?

**Comment by TrySound** [comment]
Why migrate to typescript?
