### ISSUE TITLE
Bounded generics not working for for anonymous (arrow) function

### ISSUE THREAD

**Issue by pulli23** [facebook/flow#8294]
Flow version: 0.118.0

## Expected behavior
When binding a generic to a type, I expect the generic to just work/accept any type that is a subset of that type. This is especially useful for generic functions as member "properties", which is a common way to bind `this`.

## Actual behavior
The binding syntax itself gives a syntax error. - A bound generic within a normal function, or a non bound generic do work as expected.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQjIFcB2BjALgS1uqOgQILoCeAtrKgM4A8AKgFxGqUBGApgE4B8ACgBuAQ2itGAGlAAPZunbceASlABvAL7JMBWtlBpCAXlAja5LKCZ9QwsROly2nXqqM3NAbm279kWLCgJmYWmFYszko2duKgUrKsCi4qQR6IGkA

**Comment by Brianzchen** [comment]
Try flow no longer throws an error
