### ISSUE TITLE
Object construction fails for disjoint unions

### ISSUE THREAD

**Issue by kkaefer** [facebook/flow#8295]
Flow version: 0.118

Given this code:

```js
// @flow

type FirstOperation = { type: 'first' };
type SecondOperation = { type: 'second' };

type Operation = FirstOperation | SecondOperation;

function add(type: 'first' | 'second'): Operation {
  return { type };
}
```
([Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AMQJYBOAzigPLaECGK+sAdqALygDeo62AXKAOSRFSvUAF8A3Kkw4AylgDGDACYUs1Wg2ZsOUnr2Lylw8ck44VauoxYES5SjUugAPqFkL6y++voTEkAK70ct6gVIqKABSmugK2wi56Bh68AJQ85g4arIigoIRYKP6EjOymohIiQA)).

## Expected behavior

Flow should accept this code. TypeScript does accept it without complaints.

## Actual behavior

Flow reports this error message:

> Cannot return object literal because: Either string literal `second` [1] is incompatible with string literal `first` [2] in property `type`. Or string literal `first` [3] is incompatible with string literal `second` [4] in property `type`.

```
References:
8: function add(type: 'first' | 'second'): Operation {
                                ^ [1]
3: type FirstOperation = { type: 'first' };
                                 ^ [2]
8: function add(type: 'first' | 'second'): Operation {
                      ^ [3]
4: type SecondOperation = { type: 'second' };
                                  ^ [4]
```

**Comment by dsainati1** [comment]
`{type : 'first' | 'second'}` (the type of `{type}`) is not the same as `{type : 'first'} | `{type : 'second'}` (the type of `Operation`). 

Consider what would happen if you wanted to write `second` to the result of the function. You can't write `second` to something of type `Operation` because it isn't compatible with one branch of the union, but you can write it to `{type}` because the field itself is a union type. 

Typescript accepts this (unsafely) because they don't model the variance of object fields like this.

**Comment by alexandersorokin** [comment]
@dsainati1, I understand the case if field type is invariant .

But could you explain why `{|+type : 'first' | 'second'|}` is not same as `{|+type : 'first'|} | {|+type : 'second'|}`?

**Comment by alexandersorokin** [comment]
Nevermind. I have found counterexamples:

For covariant types:
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AEQJYDOAVrPgHYCq5K+s5oAvKAN4A+A1OtgFygDkAQ35sAvqDatO3LH34AjEaIDcqTDgBi+LNAAm1Og2bsu6ucIkDFY1YgDG9QilCCAjH3Yzz-SwqVNWLwFhFXtHZ0htPQN6d1AtHX1yQwC3VQdyJ1BdIlIKGPI4ghIyKhoU5kjEgtdVfEhQAAockvzk2IA6GSZGZiF+AEpWRFBQDKyAJyxI8ixdD2kzYP9mFryyw1qRl1cu9QC-W1GQKwBXAHMfQTsUU8FoaDQx+hRBCkIrH3eULEFdUFgDX6oHqLkIhHw5wAtlgaC55LAAG44IguB4IObbcbOeQXbwBKYzOZ7bDKUCIUTIbEuABMCyC-TElk8Sz8TOMDJC6XC2VypQKdLwfLatHoqRp3MyESiSUMgoS0XaRl5rQ29AlyCAA

For contravariant types: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AEQJYDOAVrPgHYCq5K+s5oAvKAN4A+AtOtgFygDkAQ35sAvqDatO3LH34AjEaIDcqTDgBi+LNAAm1Og2bsu6ucIkDFY1YgDG9QilCCAjH3Yzz-SwqVNWLwFhFXtHZ0htPQN6d1AtHX1yQwC3VQdyJ1BdIlIKGPI4ghIyKhoU5kjEgtdbDKzBACYPNiChf0lPMyt-YzaQ9PDs3NKC5rwR-PL6VMbBzIiopMNxhOjkmeYckqmV23xIUAAKJoA6GSZGZnaASlZEUFB65wAnLEjyLF0WgGp+3pccweoCq6xW53UAT8tkeICsAFcAOY+QR2FDwwTQaBoJ70FCCCiEHqgQkoLCCXSgWCHdokw6CQiEfCIgC2WBoLnksAAbjgiC4sQgvsDnqB5EjvAE3h8vhDsKpREA
