### ISSUE TITLE
Incorrectly inferring `undefined` object properties

### ISSUE THREAD

**Issue by jjenzz** [facebook/flow#8300]
I really wasn't sure what title to give this bug report but the issue is as follows:

```jsx
type Thing = { one: string };

const foo: Thing = {};

// will result in `{ one: undefined }` but doesn't error
const bar: Thing = { one: foo.one };

// errors correctly 
const baz: Thing = { one: undefined };
```

Flow version: master

## Expected behavior

I expected (perhaps incorrectly so please correct me if so) that I'd get an error saying `Thing` expects a string for `one` property.

## Actual behavior

No error occurs

https://flow.org/try/#0C4TwDgpgBAKgFgSwHYHMoF4oG8oHskQBcUAzsAE7JoC+A3AFD0DG+ZUAZrrsfFRtnUYB6IVADuCADaSo5CCQCuk4FGRQABjnxEoCpABMI7ZBH1Rq6qACMFK-bnlIA5Cojlyucs1YqrAQ3IeRFR+LQJiTlwAOm1zBnoRKDcPchIoFncIJmBJEChvJDZ-AC8gvkwwnT1DYwIzOiA

**Comment by penx** [comment]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqAFgJYB2A5mALxgDeYc5eAXGAM4YBOF1AvgG50wYGFJRxGMHm7c43DmGKy8qAMbMuYKHDjsSfWgyYt2AV3IATPFAp4rYISLEBDa1JlyFSldzWa5Nq6cABMxpY2dixWwoHaAEau3KEGZFTGjMxsOnrhzqiiYO6OfgFa0iEAzJmmOQCMTnEVYEncVWlGdFlmuXBVAHTZTS5gGCrknhzEcOYwjrLy3MqqrBotIQAsmc7x0m2bnRnddexbQywjhWLjeJOk0tOz88UwHHBeSyv+60GVegBWI7Ubq7FptIFEdIgkzZM6Ai4EApAA

**Comment by TrySound** [comment]
Empty objects are unsealed and not type safe.
https://github.com/facebook/flow/issues?q=is%3Aopen+is%3Aissue+label%3A%22unsealed+objects%22

here's proper answer
https://github.com/facebook/flow/issues/2327#issuecomment-242063803

**Comment by gkz** [comment]
Fixed: https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c
