### ISSUE TITLE
Cannot opam install flow_parser on OCaml 4.08

### ISSUE THREAD

**Issue by dexterleng** [facebook/flow#8304]
```
opam install flow_parser
The following dependencies couldn't be met:
  - flow_parser -> ocaml < 4.08.0
      base of this switch (use `--unlock-base' to force)
  - flow_parser -> ppx_tools_versioned = 5.2 -> ocaml < 4.08.0
      base of this switch (use `--unlock-base' to force)
```

Is 4.08 yet to be supported or am I doing something wrong?

**Comment by mroch** [comment]
we only officially support 4.07, but we've been slowly unblocking the things that were keeping us from upgrading to 4.08, notably sedlex 1.99 -> 2.0. it might not be much work left at this point. patches are welcome!

**Comment by hhugo** [comment]
see #8362
