### ISSUE TITLE
Well known Symbol.asyncIterator missing from core.js

### ISSUE THREAD

**Issue by Beanow** [facebook/flow#8307]
## Missing/Incorrect APIs
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol/asyncIterator

## Relevant documentation

https://github.com/facebook/flow/issues/1824
https://github.com/facebook/flow/pull/3990

https://github.com/tc39/proposal-async-iteration

**Comment by gkz** [comment]
It's there now: https://github.com/facebook/flow/blob/main/lib/core.js#L270
