### ISSUE TITLE
Type isn't correct after spreading or condition

### ISSUE THREAD

**Issue by w01fgang** [facebook/flow#8309]
Flow version:
0.119.1
## Expected behavior
```javascript
type Challenge = {|
  id: string,
|};

const getId = (challenge?: Challenge): string => {
const { id } = challenge || {};

return id;
}
                       
const test1: string = getId({ id: 'test' });
const test2: string = getId();
```
This should give an error as id can be undefined
## Actual behavior
No errors, id is always a string.

* Link to Try-Flow:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDCAFgIYwx4B2A5gQLxgDeAPqmGAJYAmAXGAGcMAJ060ANKhYBfANzoAxnCpCwdDAEluYRgAoFZCtToB+fiXKVaeAJT8ho2joB8zVEpUZmXbdJ1gDS2MCFhZmOXRhPAwAV2EqH3lpdg5UtPSMjndlVQw8IQBGexExGn91LV0mH34AcjyhWrBpG3kPXPyMACZixzLGCu5dVqA

**Comment by jamesisaac** [comment]
> Empty objects are unsealed and not type safe.
> https://github.com/facebook/flow/issues?q=is%3Aopen+is%3Aissue+label%3A%22unsealed+objects%22

If you were to write it out as `{ ...null }`, it would error as expected.

**Comment by w01fgang** [comment]
Thank you, @jamesisaac. Unfortunately this doesn't look intuitive.
Anyway it's documented https://flow.org/en/docs/types/objects/#toc-unsealed-objects
Thank you!
