### ISSUE TITLE
`T` is incompatible with `$Shape` of `T` in the first argument of property `test`.

### ISSUE THREAD

**Issue by fourstring** [facebook/flow#8319]
Flow version: latest

## Expected behavior

```javascript
interface Test<T> {
  test(t:$Shape<T>):void;
}

class TEST<T> implements Test<T> {
  test(t:$Shape<T>):void {}
}
```
In the snippet above, class `TEST` should implement interface `Test<T>`.

## Actual behavior
Flow seems to be unable to match `$Shape<T>` in class `TEST` with it in interface `Test<T>`.

I just hope the interface can be implemented correctly, and I have read the docs of `$Shape` and Generic Types, search the error on Google, but I even didn't find any useful information. Examples in those docs are too simple to solve my problem.

What should I do? Thanks a lot.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gAqeAzjgDyUB8YA3qmGPnQBQ4BcAEgDKAC2IAHPIyYBKfgDc4GACYBuVAF90pGMRo0qAUWGUZYDAFsJMPJby5D1OufaduOPkLGTpzeUqqbNqaQA

**Comment by amccloud** [comment]
Seems related to https://github.com/facebook/flow/issues/8272

**Comment by mirek** [comment]
Lifting it up works fine https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gAqeAzjgDyUA0YAymALxgAkrAFsQAOeRgD5RYAN6owYfHQAUOAFysAlMoBucDABMA3KgC+6UjGI0aVAKKtKjFuy68BwsRIwBbQTDye8uFbUdA5sEtKy8jhKqhraelImRkA

**Comment by gkz** [comment]
Works if you use the safe replacement, `$Partial`: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAdgFwKYBOUAhgMZ5gAqeAzjgDyUB8YA3qmGPnQBQ4BcAEgAKxAjgzEYjJgEp+ANzgYAJgG5UAX3SkYxGjSoBRAMqUZYDAFsADjDxW8uQ9ToX2nbjj5DR4ydLM8kqqbNqaQA

https://flow.org/en/docs/types/utilities/#toc-partial
