### ISSUE TITLE
Not able to handle union types

### ISSUE THREAD

**Issue by penx** [facebook/flow#8325]
Flow version: 0.120.1

## Expected behavior

All of the following should not error:

```jsx
import type { Node } from 'react';
import React from 'react';

const MyComponent = ({children, someProp}: {children: Node} | {someProp: number}) => (
	children ? children : <div>{someProp}</div>
);

const MyComponent2 = (props: {|children: Node|} | {|someProp: number|}) => (
	props.children ? props.children : <div>{props.someProp}</div>
);

const MyComponent3 = 
      ({children, someProp} :
       {|children?: Node, someProp: number|} | {|children: Node, someProp?: number|}) => (
	children ? children : <div>{`${someProp}`}</div>
);

const MyComponent4 = (props: {|children: Node|} | {|someProp: number|}) => (
	props.hasOwnProperty('children') ? props.children : <div>{props.someProp}</div>
);
```

## Actual behavior

Multiple errors reported such as:

> property `children` is missing in object type
> property `someProp` is missing in object type
> Cannot get `props.someProp` because property `someProp` is missing in object type
> Cannot coerce `someProp` to string because undefined [1] should not be coerced.

* Link to Try-Flow or Github repo:

https://flow.org/try/#0JYWwDg9gTgLgBDAnmApnA3nAchAJmgXzgDMoIQ4ByKFAQwGMZKBuAKFEljgCU7GSyFanyZtW9CADsAzvACyiAMLlIklJPgBeOAAp09ABbAANrhqSANHGnkUABTJgCALgyGTZ9a5z4iAHwwbEHtHV0kAVxAAIxQoAgBKOE0APl1WAEh3U3M4AH44LM9JOFcAHlxgADdk9CCQiCdSgHoK6tZ4sQkZeSUVKXUYACYk3TBHaVd0P0LzbzwUP38MPzqHBrDImKhFxJS09LGG6QA6GfU8uEOwE7Pistaaq5PVxwJmh-bOqVk4BWVwfoaADMI1YcHBEL0tysLwaRGcYIhEKmt1yc3wMNsazAG2isUWcACKKM2S82HmmOC2LRcAieO2CSSqR0GVuFzZ9yqNQABgASWpY17ct4tLmfVjib49f6qAYAFhGOiek2mJKK6IWSymsJxtM2+MZexZB3GxwMtGkAHkAO6SbGxJA6Si3SiJfJPU5qnKc6roD06kUfDoSoA

**Comment by SamChou19815** [comment]
This is a known limitation of refinements of union objects. If you want to distinguish them reliably, use another property with literal types.
