### ISSUE TITLE
Performance cliff when extending EventTarget and overloading addEventListener

### ISSUE THREAD

**Issue by julienw** [facebook/flow#8326]
Flow version: 0.120.1
but we reproduce in 0.96 so it's not especially new.

## STR
1. Clone https://github.com/julienw/bug-flow-performance-cliff
2. run Yarn to install the flow dependency
3. run `time yarn flow check`

## Expected behavior

The flow check is quick (a few seconds max).

## Actual behavior

The flow check is super slow (~50 seconds with this simple test, ~100 seconds on our more complex use case).

* Link to Github repo:
https://github.com/julienw/bug-flow-performance-cliff

If we remove the `addEventListener` overload or the inheritance, this is fast again.

/cc @canova who spent a lot of time debugging the issue on our side.

**Comment by SamChou19815** [comment]
The perf issue no longer repros with latest flow
