### ISSUE TITLE
React: Flow cannot infer generic type of HOC

### ISSUE THREAD

**Issue by btraut** [facebook/flow#8330]
Flow version: v0.121.0 (and earlier versions)

**UPDATE: I've reduced the repro case and title from the original post following Jack's first comment below.**

When using HOCs in React, I'm struggling to get flow to infer generic types. Take for instance this case where I'm using the "trivialHOC" example from the docs:

```
import React, { type AbstractComponent } from 'react';

function trivialHOC<Config>(Component: AbstractComponent<Config>): AbstractComponent<Config> {
  return Component;
}

const DemoComponent = () => <div />;

const WrappedDemoComponent = trivialHOC(DemoComponent);
```

Error is on the call to `trivialHOC(DemoComponent)`:
```
Missing type annotation for `Config`. `Config` is a type parameter declared in  function [1] and was implicitly instantiated at  call of `trivialHOC` [2].
```

I'm not sure if it's a red herring, but I noticed that this error only repros when I export the wrapped component (`export default WrappedDemoComponent;`). Otherwise flow seems happy with it.

## Expected behavior:
Flow should be able to infer the type of the component as it's passed into `trivialHOC` and it should correctly return a component of type `AbstractComponent<Config>`.

## Actual behavior
Flow cannot infer the inbound type and therefore complains that no generic type has been provided.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMY4A0oA3qDgJ7qGgCCARgM45Zk4DCsDLAB2hYXgC+oSFkGgA5FhLl5AbkSJIAV2HlkIulmQA3ZMWgAJAPJ8APAOGRkAcwB8ACgFDR4gFytObl4vTB8cexEnNwBKf3YuHnIQkTFwhyjXGkRQUCUcLSxhUGSw9QkNUhEuUAARQlRYEtTQAF5Qd2jWzNsAExNQYFd1RErhaoB1HnQmHrqGpvFWwxMzSxt3OcbBUNTo4ZBQABUAC2ZCLFksUD6OYmmSLA5QZEhQelgtUErUVGaPvBwx2QT1EAA88NBkKJfIhCKDMLhroRIMQtNA8JM7jNNgscOogA

**Comment by jackhsu978** [comment]
To add to that, here is a slightly simpler example:
```
function trivialHOC<Config: {}>(Component: AbstractComponent<Config>): AbstractComponent<Config> {
  return Component;
}

const Foo = () => null;

export const FooA = trivialHOC(Foo); // error!
```

Error:
```
export const FooA = trivialHOC(Foo); // error!
                       ^ Missing type annotation for `Config`. `Config` is a type parameter declared in function [1] and was implicitly instantiated at call of `trivialHOC` [2].
References:
3: function trivialHOC<Config: {}>(Component: AbstractComponent<Config>): AbstractComponent<Config> {
   ^ [1]
9: export const FooA = trivialHOC(Foo); // error!
                       ^ [2]
```

Here is the [try-flow link](https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDGMA0cDecYCeYScAggEYDOMU6MAwhOBAHZIvwC+cAZlE3ADkUVBkEBuAFCSeAVxYZgrfFGAA3YCgA2ACQDy9ADyMWPYAHMAXLk4A+ABSNmbDtYrVaGJ5BcxjrM3NbAEo3Kho6b1Z2PxNA21xJODgRGFkoFjgo3ylOaTRWajgAMQgIOABeOHtgyoSWWS0tKUkkAA9IWDgCliLSiFJKlXVNXQN7fuDxOAB6GbgkKH4oAEJWjuh4Hr6ygCEhmhHtfSMcOwmyqekgA).

**Comment by btraut** [comment]
I'm updating the title and description of this issue given somewhat based on @jackhsu978's addition:

1. I've realized that adding an explicit generic type to the call to `trivialHOC` can actually fix the issue: `const FooA = trivialHOC<{}>(Foo); // works!`.
2. My main issue is that I expect Flow to infer this type for me. This is doubly important when using something like Redux's `compose` function which allows us to chain multiple HOCs together. When using `compose`, we don't directly call the HOC, and therefore we don't have the opportunity to specify the generic type (`<{}>` in this case). It seems Flow infers some HOC types, but I haven't figured out the pattern yet.

**Comment by btraut** [comment]
Oh no! I think I just answered my own question, and it's a scary answer. According to https://flow.org/en/docs/types/generics/, flow doesn't infer generic types. That explains why it's forcing me to specify one above.

…but why then do examples like this clearly show that flow is inferring types?

```
function identity<T>(val: T): T {
 return val; 
}

const foo = identity(8); // type is "8"
const bar: string = foo; // error!
```

https://flow.org/try/#0GYVwdgxgLglg9mABDAJgUzLKBPAPAFQD4AKANwEMAbALkXwEpb9EBvAKEQCc0oROkKlANyI2AXzZsICAM5REwOHEQBeZOkwwcxABz0RAegOIcABzTIZiAEQ7rU2fIBG5TrTmcYYAOaqFSw2M0Tk44TgBCNiA

**Comment by dsainati1** [comment]
This has to do with the **variance** of these generics (https://flow.org/en/docs/lang/variance/). The `Config` generic appears **contravariantly** in the definition of `AbstractComponent`, and thus contravariantly in the type of the argument of your HOC. By contrast the `T` generic appears **covariantly** in the type of `val`. 

We specifically do not allow you to export inferred contravariant positions, because it becomes impossible to know how much the type will widen when used in different files. Notice that the error disappears if you don't try to export `fooA`.
