### ISSUE TITLE
$Key not working for generic

### ISSUE THREAD

**Issue by pizzarob** [facebook/flow#8332]
Flow version 1.107.0

```js
function test<State>() {
	const onChange = (key: $Keys<State>) => {}
    return onChange;
}
const INITIAL = { foo: 'bar' };
function hey() {
 	const change = test<typeof INITIAL>();
        // Error here. 
        // Cannot call `change` with `'foo'` bound to `key` because property `foo` is missing in `State`
  	change('foo');
}
```

Try flow:

https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygHgMpQIaoB8AFAJSIDeAUAJAQIaIIDCAFnmAOYqIC8ixANYoAngC5EAEgDSotDnxFyvQpQC+VRFsQAnFFBA6kLdlxQBuKhvphGASQBydgCp2AggBk+lRMDhwJAHIAIzwdQMQ1S1BIWAREVlEySk06BihECFNub1QMTCgRAAcUOGBERxd3DxJSSy06bJRiQL84QLqrIA

**Comment by noppa** [comment]
Works if you add explicit return type to `test`

```javascript
function test<State: any>(): (key: $Keys<State>) => void {
    const onChange = key => {}
    return onChange;
}
const INITIAL = { foo: 'bar' };
function hey() {
    const change = test<typeof INITIAL>();
    change('foo');
}
```

[Try Flow](https://flow.org/try/#0GYVwdgxgLglg9mABFApgZygHgMpQIaoBcieYAngHwAUAlMVQNYpnEAkA0s2jvqhTYgC8FRADc4MACaIA3gCgAkBAQZECAMIALUgHMUQxEzJCRMgL5zEVxACcUUEDaQbtYPQG45F5WFUBJADk-ABU-AEEAGQMZRGA4OGIAcgAjPBtExDNPUEhYBERNZlpZSyUVKEQIVz0DVAxMKDIABxQ4YERAkPCI6hpPKyVqlCpEuLhEvq8gA).

**Comment by SamChou19815** [comment]
Under the new escape-generic annotation requirement and when it's fully annotated, this example now works.
