### ISSUE TITLE
Flow can't decide which case to select, even when only one case matches the number of explicit function type parameters I use 😔

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#8333]
Flow version: (at least) 0.111.3-0.120.0

I'm trying to create library defs for `@repeaterjs/repeater`.  I'm having issues with these overloads:

```js
  declare function zip<T1, T2, T3>(contenders: [Contender<T1>, Contender<T2>, Contender<T3>]): Repeater<[T1, T2, T3]>;
  declare function zip<T1, T2>(contenders: [Contender<T1>, Contender<T2>]): Repeater<[T1, T2]>;
  declare function zip<T>(contenders: Iterable<Contender<T>>): Repeater<T[]>;
```
Then in my test I'm calling `zip` with explicit function type parameters. 
**There's no way in hell Flow should be unable to pick the correct overload, because only one of the overloads has three parameters.**

```js
  const zipped: Repeater<[string, number, boolean]> = Repeater.zip<
    string,
    number,
    boolean
  >([
    new Repeater<string>(async (push, stop) => push('test')),
    [2, Promise.resolve(3)],
    Promise.resolve(true),
  ]);
```

## Expected behavior

No errors

## Actual behavior
```
38: const zipped: Repeater<[string, number, boolean]> = Repeater.zip<
                                                        ^ Could not decide which case to select, since case 1 [1] may work but if it doesn't case 3 [2] looks promising too. To fix add a type annotation to array literal [3], to new `Repeater` [4], or to call of method `resolve` [5].
References:
30: declare function zip<T1, T2, T3>(
    ^ [1]
36: declare function zip<T>(contenders: Iterable<Contender<T>>): Repeater<T[]>;
    ^ [2]
44:   [2, Promise.resolve(3)],
      ^ [3]
43:   new Repeater<string>(async (push, stop) => push('test')),
      ^ [4]
45:   Promise.resolve(true),
      ^ [5]
```
* Link to Try-Flow or Github repo: [Try Flow Link](https://flow.org/try/#0FAehAIAEDMBsHsDuxgBMCmBjWBDATuuAC4CeADoQAoCuAzgBYA8AmgJbqyoA04AcugA8i4ALzgAtqwHpUAPlHgAFMHDgAbjljV0ALnCU88SbXQt2neQB9wbDqmABKUfINHWJxgH5+Q2QG40LFwCYnJCAGUieDIFRUV0PDxPPRwAOxInEXlJaVQnADJ9Q2NTNXhWOQCMbHxCUgpwACV0ChwiBIBRaUxqKLwzOx5momo8VIUcmR4fYTFJuViVcDI6ej0aBgHOacEiWS4l2iiyPUjox2citw9h0dSrJvQRsaqg2vAa2lpH1vb+222j2e4zmUimfF2EzBciWrHEZFg6HE6FSRG+AEFaCRUpgAOIohJteD-czcIF3Ha+cAAbyWmHgqSOeGomD6ylUqkEWF6xL0zV+nW6PJJg3JY0pewOqgcejKFQCqlSu0UGi06GS4G8uxlVxKjAAkn8iXhmrRqLAiFsybcxrJ-EsCMDGI1ZCrNNo+TrXHrDYS+qbzZaAdbwNYbfd7aoiPRDIh4okNWkMutiu5TL68MaAxarUMnnc7QqoJAcFicRnjYoddH3AFDkQ2qxMOAAF6sE6hCjwaCt9sBAC+gRqIXqhAAwgz2qkMP0ACryERLawAEkx2MwFYARojGN604x56HwLOeEnT+lZEvwMutzu9x5D9YT+Azy+L1f76Z51fZ3XqsFCGgagcSIVgGV7MgDwARh4WcACZYIAZldOlJxRGdaD0ABtCdUXQhJoP2cBcKnGcDzgoiSPwudkIAXUcPkWnQNoCKw2cYOPBDj0Q2j7X-d4gJAsDxjbSD2Ngij2Q+NDpwSTDwBwmSyPYyilII+DZHonV+WYv5GDYjj4N415h0A4DWWEiCD1dek8NkvB5NvUwqPs6zZG0piWLnLDjJQWyjggihUEYgV+iwplWFSABzHhUmocRNwSHhN3geBETSXiFB0ryADpRMYes8EimKljihKkqWFK0uY1JgFdLDSvQRAfl0giIui11S3XJQVgYHgjmiTJ5F6+hFAAcnaI4xocBwpQUrjPxyghaDStR0EURCHFoubFuW1b1qIZl0Fm4BaIcPwgA)

**Comment by mirek** [comment]
Flow is right, 3rd option matches first two, right?

Does something like this solve the issue? https://flow.org/try/#0FAehAIAEDMBsHsDuxgBMCmBjWBDATuuAC4CeADoQAoCuAzgBYA8AmgJbqyoA04AcugA8i4ALzgAtqwHpUAPlHgAFMHDgAbjljV0ALnCU88SbXQt2neQB9wbDqmABKUfINHWJxgH5+Q2QG4UDGx8QlIKcABlIngyBUVFdDw8Tz0cADsSJxF5SWlUJwAyfUNjUzV4VjkAtCxcAmJyQgAldAocIkSAUWlMami8MzseFqJqPDSFXJkeH2ExKbk4lXAyOno9GgZBzhnBIlkuZdposj0omMdnYrcPEbG0q3A78eqgusJg2lon1vR2xO23B+o3Gkyk0z4ezBeVky1Y4jIsHQ4nQaSI3wAgrQSGlMABxVGJdrwAa2HbA+67XzgADey0w8DSxzw1Ew-WUqlUgiwfRJehabQ6eG6PP6gOG6BBaSp+0OqgcenKlQCqjSe0UGi06BS4G8ewV11KjAAkkLiXgWrRqLAiOKKeNZP5lgQpYwmrINZptPyDa4jaaif1LdbbWSgU1wNZng8naoiPRDIgEkkdelMhsSu5TAG8Obgza7dHHSqoJAcNjcTnzYoDfH3CXju1WJhwAAvVinBoUeDQNsdgIAX0CtRCXcIAGFGR00hgBgAVeQiZbWAAkWJxmCrACMkYw-VnGAvI+A5zw02eMrDVKvt7v9x4j9ZT+Bzy-L8vDQeFx+59UwoRuiIXM2UnNFUVnBQ3Q9TtFFA6dZyghwsnkJoamCepoGoXEiFYRk+zIQ89FvUwFkdRQGTAmdEloPQ5wNAU-iFRgVznahEXQABZHACOfQDgKIODwMSR1OVEsTxJQCjjnwihUH5X5-gGABtZlWDSABzHg0mocQt0SHgt3geAkXSABdRcfkFRIADp2zIRQlOWNVEEsxiAVUjSPXLDclFWBgeGOGJkJWNZFAAcg6Y4wqQuVwCUgAmHh73QayCFoYy1HQRQAGYHFM2LktS9B0tgTLFCA7QHEOUyHD8IA

**Comment by jedwards1211** [comment]
@mirek that doesn't work, it doesn't report some errors it should, like if I change `Repeater<[string, number, boolean]>` to `Repeater<[string, number, number]>`.  I doubt `$TupleMap` actually works correctly on `Iterable`s?

I don't understand why you're saying the third option matches the first two, each option has a different number of type parameters so it's completely unambiguous which one matches the 
number of explicit type parameters I provided.

**Comment by mirek** [comment]
Yes, my example was not correct, take a look at this simplified example that is focusing just on that part:

https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaJAK4B2GALgJawmgAkaAHubthQEpoDOR05APABUAfAAoADgC5QABVywAtpS5ohw0AB9QgzfQCS5NKwBG0VXMXLVI3YIA0obCQCeDp8-Va6AQS7OyBkbYpubySipqtm4u0R4AlNKCqJg4+ISkFNS0AF6U4kLSgSZm-EqMaCjCYhg0hiTouFyJCfSCROJmALLY+fag5M7iaLCQ9EwsbOScPHzqoPMLi0ugyDUkXOSgueJDKNIA2hu4lCQA5g4kRArGRg5HJ6cAuqAAvFt5ovuI8xbhaAB0+C4sGgADc0KIAOTYSFxOzfWRhKyA7gg8GiACMcIRv2RQLREJYRDQcUQjziQA

^^ it errors correctly, you can update types to double check. I think the way to go is to build something on that.

The third option matches because $Iterable<T> matches [], [T], [T, T], [T, T, T...] and so on.

**Comment by jedwards1211** [comment]
Amazing, that does seem like it would work for the type defs I'm trying to create.  Thanks!
