### ISSUE TITLE
flow imports modules as "any" when using webpack's dynamic imports

### ISSUE THREAD

**Issue by btraut** [facebook/flow#8338]
Flow version: v0.122 (and older versions)

Flow added support for dynamic import syntax here: https://github.com/facebook/flow/pull/3544. Unfortunately, it fails to type check the imported values. This results in everything being imported as "any" types.

```
// Cat.js:
export const message: string = 'Meow';


// CatLoader.js
import('path/to/Cat.js').then(({ message }) => {
  // This should cause an error, but it doesn't!
  const numberOfCats: number = message;
});
```

Given that `import()` has been supported by webpack for years, are there plans to add typechecking?

Thanks!
– bt

**Comment by TrySound** [comment]
@btraut Make sure you have flow annotations in both of your modules. I works for me more than a year.

Also it's not "webpack's dynamic import". Dynamic import is part of standard.

**Comment by btraut** [comment]
Totally right, TrySound. This was a false alarm. The importer in my codebase was flow-typed, but not the _imported_.
