### ISSUE TITLE
React forwardRef incompatible with AbstractComponent

### ISSUE THREAD

**Issue by chasestarr** [facebook/flow#8343]
Flow version: `0.122.0`

```js
import * as React from 'react';

const Child = (props: {foo?: string}) => null;
const ForwardChild = React.forwardRef<{foo?: string}, mixed>(props => null);

const Parent = (props: {renderChild: React.AbstractComponent<{}>}) => null;

function Component() {
  return (
    <div>
      <Parent renderChild={Child} />
      <Parent renderChild={ForwardChild} /> // <-- fails here
    </div>
  );
}
```

## Expected behavior
I expected it to operate similarly to the stateless functional component where if the props type has optional values, `{}` is compatible. I ultimately want to provide a render-prop interface that accepts any component given that its props properties are optional.

## Actual behavior

```
12:       <Parent renderChild={ForwardChild} />
           ^ Cannot create `Parent` element because property `foo` is missing in object type [1] but exists in object type [2] in property `renderChild`.
References:
5: const Parent = (props: {renderChild: React.AbstractComponent<{}>}) => null;
                                                                ^ [1]
4: const ForwardChild = React.forwardRef<{foo?: string}, mixed>(props => null);
```

* Link to Try-Flow: [link](https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvAMIAWwANgCZwAvHAAUYYmFQAuOAG8CECAH4ZbKMGYBzAL4BKIQD44zAK48e9Jq3gAxaAHdkUPl14Dh2PDAB0CqI+dsAgAeeUUVODUNHQAaOBBgAA8sPgMxCXRBI1NzXUsWNjgABScsZnhhdIhJGVlKZj4sKFd+GU98bwBBACM1L3YSSGYymFDtAz1DYzMLBjoCE2Z8YBY4AA0RfVk6ODhKGBMoZlEd3bhgvmAANwNTs-OS+vh6xubufkFZFr5tOAB6W73XbBR4jPZlV7fT52fxOFzvH7-QFnYJ-S43U55OjaOhAA)

**Comment by TrySound** [comment]
Types are incompatible. Look, here you have the same issue.
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvAMIAWwANgCYAuTFRgA6AIIAjNlDwx2JSMyzMYAHgDeBCBAD8QmcGYBzAL4A+OAF44ACjDEwqAJTXLzAK48e9Jq3gAYtAA7shQfFy8fNbCcqLaUKHh2ASa2noGMFBGZgA0cCDAAB5YfOb2juhW7l48zr4sbHAACmEq8DYVEE5CGpTMfFhQkfxC2HFSMnIK4CztmhamrtVwnt70DAQezPjALHAAGrauGnRwcJQwHlDMdmfncGp8wABu5vcPj6398P2Dw9x+FYNCM+KY4AB6d6fc5qb7tC4qf6g4FBRJhCKAsGQ6EPNQQ55ve71OimOhAA

To solve this, specify the type on parent
https://flow.org/try/#0JYWwDg9gTgLgBAKjgQwM5wEoFNkGN4BmUEIcA5FDvmQNwBQduEAdqvAMIAWwANgCYAuTFRgA6AIIAjNlDwx2JSMyzMYAHgDeBCBAD8QmcGYBzAL4A+OAF44ACjDEwqAJTXLzAK48e9Jq3gAYtAA7shQfFy8fNbCcqLaUKHh2ASa2noGMFBGZgA0cCDAAB5YfOb2juhW7l48zr4sbHAACmEq8DYVEE5CGpTMfFhQkfxC2HFSMnIK4CztaTr6cIYmFqau1XCe3vQMBB7M+MAscAAatq4adHBwlDAeUMx21zdwanzAAG7mL69vrf14P1BsNuPwrBoRnxTHAAPQ-P43NQA9q3FQgqEQoKJMIRMHQuEI15qWEfb4vep0Ux0IA

**Comment by chasestarr** [comment]
Thank you for the suggestion. I see that it is incompatible because an error is raised, but what I'd like to better understand is why `const Child = (props: {foo?: string}) => null;` does not raise an error.

**Comment by SamChou19815** [comment]
You can make `foo` readonly to fix the error
