### ISSUE TITLE
Use of $ObjMap incorrectly throws 'Missing type annotation'

### ISSUE THREAD

**Issue by penx** [facebook/flow#8344]
Flow version: v0.122.0

## Expected behavior

When using `$ObjMap` as follows:

```js
// @flow
import React from 'react';

type StyledShorthandFactory<V> = (any) => V;
type ExtractShorthand = <V>(V: any) => StyledShorthandFactory<V>;

type BuiltinElementInstances = {
    div: React$ElementRef<'div'>
}

type ConvenientShorthands = $ObjMap<
    BuiltinElementInstances,
    ExtractShorthand
  >;

const styled: ConvenientShorthands = {
	div: () => <div />
}

export const MyDiv = styled.div;
```

The type 'V' on StyledShorthandFactory should be inferred on each call from $ObjMap, so the type shouldn't need to be defined elswehere and the above code should not error.

## Actual behavior

```
11: type ConvenientShorthands = $ObjMap<
                                ^ Missing type annotation for `V`. `V` is a type parameter declared in function type [1] and was implicitly instantiated at `$ObjMap` [2].
References:
5: type ExtractShorthand = <V>(V: any) => StyledShorthandFactory<V>;
                           ^ [1]
11: type ConvenientShorthands = $ObjMap<
                                ^ [2]
```
* Link to Try-Flow or Github repo:

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgDKn0QgBNeAC2w5RxAHZCAYmRzYOAHgBqAPlABeUAAoZHAJQ6ta1p26gAogA8cWRWIlTZO0Oo161ALlCGTbS1+DkERcVxXeUVlT1Z2Lh4AIQBXZGgcZGlrQVRCaRwASWkAZxwZUkIS9wBvRFAG0CFkADc-IkUAEhzCPIKiSBVaZpbaDUQAXzZLHgBhWGkW-OR8nGdImSFq3U6AeQAjACsAWWJ0FXrG1PTM7NzV4rKKqoAaS4a7BycIyU3LjXipAWZVAZVCwj880Wy1W61+sm2oDqAEgRn49IEtCoRqBgOMpohCLZMLhQEDSnhjhwACKtdxgsIAOhGrCAA

**Comment by atabel** [comment]
Not sure why but this doesn't produce the error:
```js
// @flow
import React from 'react';

type BuiltinElementInstances = {
    div: React$ElementRef<'div'>
}

type ConvenientShorthands = $ObjMap<
    BuiltinElementInstances,
    <V>(V: any) => (any => V)
>;

const styled: ConvenientShorthands = {
	div: () => <div />
}

export const MyDiv = styled.div;
```

https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gEoCmAhgMZ6RayqgDkWJ5tA3IojgJ7qGgBCArsmg5kAOwCi0QqkKicASVEBnHMVGlCS0AF5QAb0SgjoACbIAbgC4CjHABJJ02TiKQAPLTPnaAPkQBfNk5uUABhWFFzWWRnAGUAC2wceLUTLV07AHkAIwArAFlidDdDYwEhEQkpGTlFFTUNJQAaUqM3ADUfAAp26zUOAEodH1Au-uHQdoHEH1ZEUgiVUBUOKRNrcMjouMTcFNE0nX1EAEgvay6h7RG3L1BgP0DEQgAPTFxQBeU8fI4AEQsRxWawAdF5WEA

**Comment by TheMightyPenguin** [comment]
@penx Flow doesn't infer generics, so I think this won't work 😞 From the docs:

> Warning: Flow does not infer generic types. If you want something to have a generic type, annotate it. Otherwise, Flow may infer a type that is less polymorphic than you expect.

https://flow.org/en/docs/types/generics/

I also saw your issue here https://github.com/flow-typed/flow-typed/pull/3767 as I was trying to do the same, but no luck so far.

**Comment by KlaraFickova** [comment]
I patched the libdef by duplicating and tweaking the object:
```  
declare type ConvenientShorthands = {
    a: StyledShorthandFactory<React$ElementRef<'a'>>,
    abbr: StyledShorthandFactory<React$ElementRef<'abbr'>>,
    address: StyledShorthandFactory<React$ElementRef<'address'>>,
    area: StyledShorthandFactory<React$ElementRef<'area'>>,
    article: StyledShorthandFactory<React$ElementRef<'article'>>,
    aside: StyledShorthandFactory<React$ElementRef<'aside'>>,
    audio: StyledShorthandFactory<React$ElementRef<'audio'>>,
    b: StyledShorthandFactory<React$ElementRef<'b'>>,
    base: StyledShorthandFactory<React$ElementRef<'base'>>,
    bdi: StyledShorthandFactory<React$ElementRef<'bdi'>>,
    bdo: StyledShorthandFactory<React$ElementRef<'bdo'>>,
    big: StyledShorthandFactory<React$ElementRef<'big'>>,
    blockquote: StyledShorthandFactory<React$ElementRef<'blockquote'>>,
    body: StyledShorthandFactory<React$ElementRef<'body'>>,
    br: StyledShorthandFactory<React$ElementRef<'br'>>,
    button: StyledShorthandFactory<React$ElementRef<'button'>>,
    canvas: StyledShorthandFactory<React$ElementRef<'canvas'>>,
    caption: StyledShorthandFactory<React$ElementRef<'caption'>>,
    cite: StyledShorthandFactory<React$ElementRef<'cite'>>,
    code: StyledShorthandFactory<React$ElementRef<'code'>>,
    col: StyledShorthandFactory<React$ElementRef<'col'>>,
    colgroup: StyledShorthandFactory<React$ElementRef<'colgroup'>>,
    data: StyledShorthandFactory<React$ElementRef<'data'>>,
    datalist: StyledShorthandFactory<React$ElementRef<'datalist'>>,
    dd: StyledShorthandFactory<React$ElementRef<'dd'>>,
    del: StyledShorthandFactory<React$ElementRef<'del'>>,
    details: StyledShorthandFactory<React$ElementRef<'details'>>,
    dfn: StyledShorthandFactory<React$ElementRef<'dfn'>>,
    dialog: StyledShorthandFactory<React$ElementRef<'dialog'>>,
    div: StyledShorthandFactory<React$ElementRef<'div'>>,
    dl: StyledShorthandFactory<React$ElementRef<'dl'>>,
    dt: StyledShorthandFactory<React$ElementRef<'dt'>>,
    em: StyledShorthandFactory<React$ElementRef<'em'>>,
    embed: StyledShorthandFactory<React$ElementRef<'embed'>>,
    fieldset: StyledShorthandFactory<React$ElementRef<'fieldset'>>,
    figcaption: StyledShorthandFactory<React$ElementRef<'figcaption'>>,
    figure: StyledShorthandFactory<React$ElementRef<'figure'>>,
    footer: StyledShorthandFactory<React$ElementRef<'footer'>>,
    form: StyledShorthandFactory<React$ElementRef<'form'>>,
    h1: StyledShorthandFactory<React$ElementRef<'h1'>>,
    h2: StyledShorthandFactory<React$ElementRef<'h2'>>,
    h3: StyledShorthandFactory<React$ElementRef<'h3'>>,
    h4: StyledShorthandFactory<React$ElementRef<'h4'>>,
    h5: StyledShorthandFactory<React$ElementRef<'h5'>>,
    h6: StyledShorthandFactory<React$ElementRef<'h6'>>,
    head: StyledShorthandFactory<React$ElementRef<'head'>>,
    header: StyledShorthandFactory<React$ElementRef<'header'>>,
    hgroup: StyledShorthandFactory<React$ElementRef<'hgroup'>>,
    hr: StyledShorthandFactory<React$ElementRef<'hr'>>,
    html: StyledShorthandFactory<React$ElementRef<'html'>>,
    i: StyledShorthandFactory<React$ElementRef<'i'>>,
    iframe: StyledShorthandFactory<React$ElementRef<'iframe'>>,
    img: StyledShorthandFactory<React$ElementRef<'img'>>,
    input: StyledShorthandFactory<React$ElementRef<'input'>>,
    ins: StyledShorthandFactory<React$ElementRef<'ins'>>,
    kbd: StyledShorthandFactory<React$ElementRef<'kbd'>>,
    label: StyledShorthandFactory<React$ElementRef<'label'>>,
    legend: StyledShorthandFactory<React$ElementRef<'legend'>>,
    li: StyledShorthandFactory<React$ElementRef<'li'>>,
    link: StyledShorthandFactory<React$ElementRef<'link'>>,
    main: StyledShorthandFactory<React$ElementRef<'main'>>,
    map: StyledShorthandFactory<React$ElementRef<'map'>>,
    mark: StyledShorthandFactory<React$ElementRef<'mark'>>,
    menu: StyledShorthandFactory<React$ElementRef<'menu'>>,
    meta: StyledShorthandFactory<React$ElementRef<'meta'>>,
    meter: StyledShorthandFactory<React$ElementRef<'meter'>>,
    nav: StyledShorthandFactory<React$ElementRef<'nav'>>,
    noscript: StyledShorthandFactory<React$ElementRef<'noscript'>>,
    object: StyledShorthandFactory<React$ElementRef<'object'>>,
    ol: StyledShorthandFactory<React$ElementRef<'ol'>>,
    optgroup: StyledShorthandFactory<React$ElementRef<'optgroup'>>,
    option: StyledShorthandFactory<React$ElementRef<'option'>>,
    output: StyledShorthandFactory<React$ElementRef<'output'>>,
    p: StyledShorthandFactory<React$ElementRef<'p'>>,
    param: StyledShorthandFactory<React$ElementRef<'param'>>,
    picture: StyledShorthandFactory<React$ElementRef<'picture'>>,
    pre: StyledShorthandFactory<React$ElementRef<'pre'>>,
    progress: StyledShorthandFactory<React$ElementRef<'progress'>>,
    q: StyledShorthandFactory<React$ElementRef<'q'>>,
    rp: StyledShorthandFactory<React$ElementRef<'rp'>>,
    rt: StyledShorthandFactory<React$ElementRef<'rt'>>,
    ruby: StyledShorthandFactory<React$ElementRef<'ruby'>>,
    s: StyledShorthandFactory<React$ElementRef<'s'>>,
    samp: StyledShorthandFactory<React$ElementRef<'samp'>>,
    script: StyledShorthandFactory<React$ElementRef<'script'>>,
    section: StyledShorthandFactory<React$ElementRef<'section'>>,
    select: StyledShorthandFactory<React$ElementRef<'select'>>,
    small: StyledShorthandFactory<React$ElementRef<'small'>>,
    source: StyledShorthandFactory<React$ElementRef<'source'>>,
    span: StyledShorthandFactory<React$ElementRef<'span'>>,
    strong: StyledShorthandFactory<React$ElementRef<'strong'>>,
    style: StyledShorthandFactory<React$ElementRef<'style'>>,
    sub: StyledShorthandFactory<React$ElementRef<'sub'>>,
    summary: StyledShorthandFactory<React$ElementRef<'summary'>>,
    sup: StyledShorthandFactory<React$ElementRef<'sup'>>,
    table: StyledShorthandFactory<React$ElementRef<'table'>>,
    tbody: StyledShorthandFactory<React$ElementRef<'tbody'>>,
    td: StyledShorthandFactory<React$ElementRef<'td'>>,
    textarea: StyledShorthandFactory<React$ElementRef<'textarea'>>,
    tfoot: StyledShorthandFactory<React$ElementRef<'tfoot'>>,
    th: StyledShorthandFactory<React$ElementRef<'th'>>,
    thead: StyledShorthandFactory<React$ElementRef<'thead'>>,
    time: StyledShorthandFactory<React$ElementRef<'time'>>,
    title: StyledShorthandFactory<React$ElementRef<'title'>>,
    tr: StyledShorthandFactory<React$ElementRef<'tr'>>,
    track: StyledShorthandFactory<React$ElementRef<'track'>>,
    u: StyledShorthandFactory<React$ElementRef<'u'>>,
    ul: StyledShorthandFactory<React$ElementRef<'ul'>>,
    var: StyledShorthandFactory<React$ElementRef<'var'>>,
    video: StyledShorthandFactory<React$ElementRef<'video'>>,
    wbr: StyledShorthandFactory<React$ElementRef<'wbr'>>,
    // SVG
    circle: StyledShorthandFactory<React$ElementRef<'circle'>>,
    clipPath: StyledShorthandFactory<React$ElementRef<'clipPath'>>,
    defs: StyledShorthandFactory<React$ElementRef<'defs'>>,
    ellipse: StyledShorthandFactory<React$ElementRef<'ellipse'>>,
    g: StyledShorthandFactory<React$ElementRef<'g'>>,
    image: StyledShorthandFactory<React$ElementRef<'image'>>,
    line: StyledShorthandFactory<React$ElementRef<'line'>>,
    linearGradient: StyledShorthandFactory<React$ElementRef<'linearGradient'>>,
    mask: StyledShorthandFactory<React$ElementRef<'mask'>>,
    path: StyledShorthandFactory<React$ElementRef<'path'>>,
    pattern: StyledShorthandFactory<React$ElementRef<'pattern'>>,
    polygon: StyledShorthandFactory<React$ElementRef<'polygon'>>,
    polyline: StyledShorthandFactory<React$ElementRef<'polyline'>>,
    radialGradient: StyledShorthandFactory<React$ElementRef<'radialGradient'>>,
    rect: StyledShorthandFactory<React$ElementRef<'rect'>>,
    stop: StyledShorthandFactory<React$ElementRef<'stop'>>,
    svg: StyledShorthandFactory<React$ElementRef<'svg'>>,
    text: StyledShorthandFactory<React$ElementRef<'text'>>,
    tspan: StyledShorthandFactory<React$ElementRef<'tspan'>>,
    // Deprecated, should be HTMLUnknownElement, but Flow doesn't support it
    keygen: StyledShorthandFactory<React$ElementRef<'keygen'>>,
    menuitem: StyledShorthandFactory<React$ElementRef<'menuitem'>>,
    ...
  }
```
Feel free to copy-paste it as well. It seems to work all right.

**Comment by zipzapp** [comment]
> I patched the libdef by duplicating and tweaking the object:
> 
> ```
> declare type ConvenientShorthands = {
>     a: StyledShorthandFactory<React$ElementRef<'a'>>,
>     abbr: StyledShorthandFactory<React$ElementRef<'abbr'>>,
>     address: StyledShorthandFactory<React$ElementRef<'address'>>,
>     area: StyledShorthandFactory<React$ElementRef<'area'>>,
>     article: StyledShorthandFactory<React$ElementRef<'article'>>,
>     aside: StyledShorthandFactory<React$ElementRef<'aside'>>,
>     audio: StyledShorthandFactory<React$ElementRef<'audio'>>,
>     b: StyledShorthandFactory<React$ElementRef<'b'>>,
>     base: StyledShorthandFactory<React$ElementRef<'base'>>,
>     bdi: StyledShorthandFactory<React$ElementRef<'bdi'>>,
>     bdo: StyledShorthandFactory<React$ElementRef<'bdo'>>,
>     big: StyledShorthandFactory<React$ElementRef<'big'>>,
>     blockquote: StyledShorthandFactory<React$ElementRef<'blockquote'>>,
>     body: StyledShorthandFactory<React$ElementRef<'body'>>,
>     br: StyledShorthandFactory<React$ElementRef<'br'>>,
>     button: StyledShorthandFactory<React$ElementRef<'button'>>,
>     canvas: StyledShorthandFactory<React$ElementRef<'canvas'>>,
>     caption: StyledShorthandFactory<React$ElementRef<'caption'>>,
>     cite: StyledShorthandFactory<React$ElementRef<'cite'>>,
>     code: StyledShorthandFactory<React$ElementRef<'code'>>,
>     col: StyledShorthandFactory<React$ElementRef<'col'>>,
>     colgroup: StyledShorthandFactory<React$ElementRef<'colgroup'>>,
>     data: StyledShorthandFactory<React$ElementRef<'data'>>,
>     datalist: StyledShorthandFactory<React$ElementRef<'datalist'>>,
>     dd: StyledShorthandFactory<React$ElementRef<'dd'>>,
>     del: StyledShorthandFactory<React$ElementRef<'del'>>,
>     details: StyledShorthandFactory<React$ElementRef<'details'>>,
>     dfn: StyledShorthandFactory<React$ElementRef<'dfn'>>,
>     dialog: StyledShorthandFactory<React$ElementRef<'dialog'>>,
>     div: StyledShorthandFactory<React$ElementRef<'div'>>,
>     dl: StyledShorthandFactory<React$ElementRef<'dl'>>,
>     dt: StyledShorthandFactory<React$ElementRef<'dt'>>,
>     em: StyledShorthandFactory<React$ElementRef<'em'>>,
>     embed: StyledShorthandFactory<React$ElementRef<'embed'>>,
>     fieldset: StyledShorthandFactory<React$ElementRef<'fieldset'>>,
>     figcaption: StyledShorthandFactory<React$ElementRef<'figcaption'>>,
>     figure: StyledShorthandFactory<React$ElementRef<'figure'>>,
>     footer: StyledShorthandFactory<React$ElementRef<'footer'>>,
>     form: StyledShorthandFactory<React$ElementRef<'form'>>,
>     h1: StyledShorthandFactory<React$ElementRef<'h1'>>,
>     h2: StyledShorthandFactory<React$ElementRef<'h2'>>,
>     h3: StyledShorthandFactory<React$ElementRef<'h3'>>,
>     h4: StyledShorthandFactory<React$ElementRef<'h4'>>,
>     h5: StyledShorthandFactory<React$ElementRef<'h5'>>,
>     h6: StyledShorthandFactory<React$ElementRef<'h6'>>,
>     head: StyledShorthandFactory<React$ElementRef<'head'>>,
>     header: StyledShorthandFactory<React$ElementRef<'header'>>,
>     hgroup: StyledShorthandFactory<React$ElementRef<'hgroup'>>,
>     hr: StyledShorthandFactory<React$ElementRef<'hr'>>,
>     html: StyledShorthandFactory<React$ElementRef<'html'>>,
>     i: StyledShorthandFactory<React$ElementRef<'i'>>,
>     iframe: StyledShorthandFactory<React$ElementRef<'iframe'>>,
>     img: StyledShorthandFactory<React$ElementRef<'img'>>,
>     input: StyledShorthandFactory<React$ElementRef<'input'>>,
>     ins: StyledShorthandFactory<React$ElementRef<'ins'>>,
>     kbd: StyledShorthandFactory<React$ElementRef<'kbd'>>,
>     label: StyledShorthandFactory<React$ElementRef<'label'>>,
>     legend: StyledShorthandFactory<React$ElementRef<'legend'>>,
>     li: StyledShorthandFactory<React$ElementRef<'li'>>,
>     link: StyledShorthandFactory<React$ElementRef<'link'>>,
>     main: StyledShorthandFactory<React$ElementRef<'main'>>,
>     map: StyledShorthandFactory<React$ElementRef<'map'>>,
>     mark: StyledShorthandFactory<React$ElementRef<'mark'>>,
>     menu: StyledShorthandFactory<React$ElementRef<'menu'>>,
>     meta: StyledShorthandFactory<React$ElementRef<'meta'>>,
>     meter: StyledShorthandFactory<React$ElementRef<'meter'>>,
>     nav: StyledShorthandFactory<React$ElementRef<'nav'>>,
>     noscript: StyledShorthandFactory<React$ElementRef<'noscript'>>,
>     object: StyledShorthandFactory<React$ElementRef<'object'>>,
>     ol: StyledShorthandFactory<React$ElementRef<'ol'>>,
>     optgroup: StyledShorthandFactory<React$ElementRef<'optgroup'>>,
>     option: StyledShorthandFactory<React$ElementRef<'option'>>,
>     output: StyledShorthandFactory<React$ElementRef<'output'>>,
>     p: StyledShorthandFactory<React$ElementRef<'p'>>,
>     param: StyledShorthandFactory<React$ElementRef<'param'>>,
>     picture: StyledShorthandFactory<React$ElementRef<'picture'>>,
>     pre: StyledShorthandFactory<React$ElementRef<'pre'>>,
>     progress: StyledShorthandFactory<React$ElementRef<'progress'>>,
>     q: StyledShorthandFactory<React$ElementRef<'q'>>,
>     rp: StyledShorthandFactory<React$ElementRef<'rp'>>,
>     rt: StyledShorthandFactory<React$ElementRef<'rt'>>,
>     ruby: StyledShorthandFactory<React$ElementRef<'ruby'>>,
>     s: StyledShorthandFactory<React$ElementRef<'s'>>,
>     samp: StyledShorthandFactory<React$ElementRef<'samp'>>,
>     script: StyledShorthandFactory<React$ElementRef<'script'>>,
>     section: StyledShorthandFactory<React$ElementRef<'section'>>,
>     select: StyledShorthandFactory<React$ElementRef<'select'>>,
>     small: StyledShorthandFactory<React$ElementRef<'small'>>,
>     source: StyledShorthandFactory<React$ElementRef<'source'>>,
>     span: StyledShorthandFactory<React$ElementRef<'span'>>,
>     strong: StyledShorthandFactory<React$ElementRef<'strong'>>,
>     style: StyledShorthandFactory<React$ElementRef<'style'>>,
>     sub: StyledShorthandFactory<React$ElementRef<'sub'>>,
>     summary: StyledShorthandFactory<React$ElementRef<'summary'>>,
>     sup: StyledShorthandFactory<React$ElementRef<'sup'>>,
>     table: StyledShorthandFactory<React$ElementRef<'table'>>,
>     tbody: StyledShorthandFactory<React$ElementRef<'tbody'>>,
>     td: StyledShorthandFactory<React$ElementRef<'td'>>,
>     textarea: StyledShorthandFactory<React$ElementRef<'textarea'>>,
>     tfoot: StyledShorthandFactory<React$ElementRef<'tfoot'>>,
>     th: StyledShorthandFactory<React$ElementRef<'th'>>,
>     thead: StyledShorthandFactory<React$ElementRef<'thead'>>,
>     time: StyledShorthandFactory<React$ElementRef<'time'>>,
>     title: StyledShorthandFactory<React$ElementRef<'title'>>,
>     tr: StyledShorthandFactory<React$ElementRef<'tr'>>,
>     track: StyledShorthandFactory<React$ElementRef<'track'>>,
>     u: StyledShorthandFactory<React$ElementRef<'u'>>,
>     ul: StyledShorthandFactory<React$ElementRef<'ul'>>,
>     var: StyledShorthandFactory<React$ElementRef<'var'>>,
>     video: StyledShorthandFactory<React$ElementRef<'video'>>,
>     wbr: StyledShorthandFactory<React$ElementRef<'wbr'>>,
>     // SVG
>     circle: StyledShorthandFactory<React$ElementRef<'circle'>>,
>     clipPath: StyledShorthandFactory<React$ElementRef<'clipPath'>>,
>     defs: StyledShorthandFactory<React$ElementRef<'defs'>>,
>     ellipse: StyledShorthandFactory<React$ElementRef<'ellipse'>>,
>     g: StyledShorthandFactory<React$ElementRef<'g'>>,
>     image: StyledShorthandFactory<React$ElementRef<'image'>>,
>     line: StyledShorthandFactory<React$ElementRef<'line'>>,
>     linearGradient: StyledShorthandFactory<React$ElementRef<'linearGradient'>>,
>     mask: StyledShorthandFactory<React$ElementRef<'mask'>>,
>     path: StyledShorthandFactory<React$ElementRef<'path'>>,
>     pattern: StyledShorthandFactory<React$ElementRef<'pattern'>>,
>     polygon: StyledShorthandFactory<React$ElementRef<'polygon'>>,
>     polyline: StyledShorthandFactory<React$ElementRef<'polyline'>>,
>     radialGradient: StyledShorthandFactory<React$ElementRef<'radialGradient'>>,
>     rect: StyledShorthandFactory<React$ElementRef<'rect'>>,
>     stop: StyledShorthandFactory<React$ElementRef<'stop'>>,
>     svg: StyledShorthandFactory<React$ElementRef<'svg'>>,
>     text: StyledShorthandFactory<React$ElementRef<'text'>>,
>     tspan: StyledShorthandFactory<React$ElementRef<'tspan'>>,
>     // Deprecated, should be HTMLUnknownElement, but Flow doesn't support it
>     keygen: StyledShorthandFactory<React$ElementRef<'keygen'>>,
>     menuitem: StyledShorthandFactory<React$ElementRef<'menuitem'>>,
>     ...
>   }
> ```
> 
> Feel free to copy-paste it as well. It seems to work all right.

Nice! I pasted this into my `flow-typed/npm/styled-components_v5.x.x` file at the end, and Flow stopped complaining about styling material-ui components. 

🥳
