### ISSUE TITLE
Flow server doesn't pick changes after npm link'ing

### ISSUE THREAD

**Issue by mirek** [facebook/flow#8345]
Flow version: 0.122.0

## Expected behavior

After linking flow server should pick this fs notification and react to it.

## Actual behavior

After using:
```
cd my-project
npm link ../my-dep1
```

Flow server doesn't pick up changes (npm pointing to linked npm now).

Workaround I'm using is `killall flow` or just using `npx flow check` instead of server.

**Comment by mirek** [comment]
If it helps trying to resolve it with:
```
npx flow force-recheck "./node_modules/@my-company/my-linked-npm"
```

...shows an error:
```
This module resolves to <<PROJECT_ROOT>>/../my-linked-npm/package.json which is outside both your root directory
and all of the entries in the [include] section of your .flowconfig. You should either add this directory to the
[include] section of your .flowconfig, move your .flowconfig file higher in the project directory tree, or move this
package under your Flow root directory.
```

**Comment by SamChou19815** [comment]
Not enough info to repro
