### ISSUE TITLE
Documented approach to typing HOC passing props in React not working with class component

### ISSUE THREAD

**Issue by sattaman** [facebook/flow#8348]
Flow version: 0.122.0

## Expected behavior

Typing as per documentation of HOC should work. Example as in documentation is here:

The following code works for annotating a HOC which passes in a prop

    /* @flow */
    
    import * as React from 'react';
    
    
    /* withHoverState HOC */
    
    type State = {
      hover: boolean,
    };
    
    export type InjectedProps = {|
      foo: string
    |};
    
    function withHoverState<T>(
      InnerComponent: React.ComponentType<{| ...T, ...InjectedProps |}>
    ): React.AbstractComponent<T> {
      	return (props) => <InnerComponent {...props} foo="bar" />
      };
    
    
    /* Button HOC */
    
    type ButtonProps = {|
      text: string,
      ...InjectedProps
    |}
    
    const UnwrappedButton = ({ text, foo }: ButtonProps) => <button>${text} - ${foo}</button>
    
    const Button = withHoverState(UnwrappedButton);
    
    
    /* Test usage */
    
    const Test1 = () => <Button text="test" />

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudVKDAIMhABYAJOADca+AMqFShGmAkB5AMLI0qQgE8cqxctUBeMAG9UYMGJlyAXGABGcODDoA7ADSoAvvyoNAAeeERgBkZgAJJeAFY0jDQAJgAKLDiUFpYAPjZgUO7O5IT4GF4A5qi5gehQAK5ejBhwXsKikg4KSioAPAAqAHwAFAVxXnKarHiTXoTOtAyEAHTTuG008wOGNH15YCtHAz6HR3GJyemZlLVDqACUi9yrAIIupfjL67NbhINDKwFACQXEIDXw7RGOBuDzAZkBfQmUxmm3mViOKxhcCy-kK7jMACIXKR8ISwMB7rY6ughAAhBqEQhtNRaHToKKqBlMtoZHHZKz5WwqEILMCfCqVPy2TEXJIqa78mr+dD0NqlMAAVS8CC+OCMKW5zPaFhGlkioUIpyKcDA-mcRt5sPhiJcjONQwAJJYRYQ8QBaMDem3+PrAN08rz3VBqrwax0mjriKSyHqmEba3WkfWpBMPIKCcADGgahrkUiVVQoVXq4jF0oARnhYBGcIRYD6CYtoqJKlK5Mp6CAA

## Actual behavior

When the inner component is changed to be a class flow is no longer happy

    /* @flow */
    
    import * as React from 'react';
    
    
    /* withHoverState HOC */
    
    type State = {
      hover: boolean,
    };
    
    export type InjectedProps = {|
      foo: string 
    |};
    
    function withHoverState<T>(
      InnerComponent: React.ComponentType<{| ...T, ...InjectedProps |}>
     ): React.AbstractComponent<T> {
      class Inner extends React.Component<T> {
        render() {
          return (
            <InnerComponent
              foo="bar"
              {...this.props}
            />
          );
        }
      };
      return Inner;
    }
    
    /* Button HOC */
    
    type ButtonProps = {|
      text: string,
      ...InjectedProps
    |}
    
    const UnwrappedButton = ({ text, foo }: ButtonProps) => <button>${text} - ${foo}</button>
    
    const Button = withHoverState(UnwrappedButton);
    
    
    /* Test usage */
    
    const Test1 = () => <Button text="test" />

Giving the error

    29:   return Inner;
                 ^ Cannot return `Inner` because inexact class `Inner` [1] is incompatible with exact `T` [2].
    
        References:
    
        19:   class Inner extends React.Component<T> {
                    ^ [1]
    
        [LIB] ..//static/v0.122.0/flowlib/react.js:258:   > = React$AbstractComponent<Config, Instance>;

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudVKDAIMhABYAJOADca+AMqFShGmAkB5AMLI0qQgE8cqxctUBeMAG9UYMGJlyAXGABGcODDoA7ADSoAvvyoNAAeeERgBkZgAJJeAFY0jDQAJgAKLDiUFpYAPjZgUO7O5IT4GF4A5mCouYHoUACuXowYcF7CopIOCkoqADwAKgB8ABQFcV5ymqx4U16EzrQMhAB0M7jtNAuDhjT9eWCrx4M+R8dxicnpmZR1wzYAlEvcawCCLqX4Kxtz24RDYZWAr0GAUSiTORgUIqLwpSjLRjrWZbBaA4G2WxcOFyUaPDGYrE0QiNfAdcaEwn9SH4X6owgFSmYopwMwAIhcpHwbMZTKsx1W4gw5FWOFu-l5hOADyZj34hIltnqRJJZNiXim+H4EsE4AAQo1CIR2motDp0FFVAaje0MnAsmAcvlbCoQoswF8KpU-LYBZckiobvbyLUdfR2qUwABVLwIb44Iwpa3GjoWUaWSIws4ssD+ZzJ223fFmIH9FyGlPDAAklldhH8YAAtGAayz-P1gOWbV4Hqhw15IwXU51xFJZL1TKMY3HSAnUkO5QIhIMaJHGuRSJVVCh0P3IyvSgBGR1gPGO0tDzNu9kqUpssDS9BAA

**Comment by mirek** [comment]
Because Inner class is polymorphic? https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBdkwBDAZzACUBTUgY2KnzizAHJ87H2BudVKDAIMhABYAJOADca+AMqFShGmAkB5AMLI0qQgE8cqxctUBeMAG9UYMGJlyAXGABGcODDoA7ADSoAvvyoNAAeeERgBkZgAJJeAFY0jDQAJgAKLDiUFpYAPjZgUO7O5IT4GF4A5mCouYHoUACuXowYcF7CopIOCkoqADwAKgB8ABQFcV5ymqx4U16EzrQMhAB0M7jtNAuDhjT9eWCrx4M+R8dxicnpmZR1wzYAlEvcawCCLqX4Kxtz24RDYZWAr0GAUSiTOT9ACqzhGYFCKi8KUoy0Y61mWwWMKB1lsti4yLko0ewPx+K4hEa+A643J5P6kPwvyxhAK9PxRTgZgARC5SPgeeyOVZjqtxBhyKscLd-MLycAHhzHvxyXLbPUCTQqTTYl4pvh+HLBOAAEKNQiEdpqLQ6dBRVTmy3tDJwLJgHL5WwqEKLMBfCqVPy2MWXJIqG5u8i1Y30dqlMDQrwIb44IwpJ1WjoWUaWSKIs5csD+ZyZl23UlmIH9FwWrPDAAklh9hH8YAAtGAm1z-P1gLXnV4Hqg414E2Xs51xFJZL1TKMkynSGnUhOVQIhIMaAnGuRSJVVCh0KOE1vSgBGD1gEke6sT-O+3kqUo8sCK9BAA
