### ISSUE TITLE
`Cannot perform arithmetic operation because null [1] is not a number.` Appears on subtraction, but don't on addition.

### ISSUE THREAD

**Issue by carljohnesan** [facebook/flow#8349]
Flow version: 0.122.0

## Expected behavior
```js
// type Props = { ...

type State = {
  count: number,
  n: null | number,
  // ... ,
};

class Counter extends React.Component<Props, State> {
  // state = { ...

  subtract = (): void => {
    this.setState((state) => ({
      count: state.count - state.n, // Error - `Cannot perform arithmetic operation because null [1] is not a number.`
    }));
  };

  add = (): void => {
    this.setState((state) => ({
      count: state.count + state.n, // Error - `Cannot perform arithmetic operation because null [1] is not a number.`
    }));
  };

  // render() { ...
}
```

## Actual behavior
```js
// type Props = { ...

type State = {
  count: number,
  n: null | number,
  // ... ,
};

class Counter extends React.Component<Props, State> {
  // state = { ...

  subtract = (): void => {
    this.setState((state) => ({
      count: state.count - state.n, // Error - `Cannot perform arithmetic operation because null [1] is not a number.`
    }));
  };

  add = (): void => {
    this.setState((state) => ({
      count: state.count + state.n, // No error somewhy
    }));
  };

  // render() { ...
}
```
[Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AZRQIYo4C8oA3gD6KigDGsArgHYoBcozjAtgEZYAnADQ1OHLtGihKnHv2GJKAXwDcyEKABKWAnRSgAwrG4ZYzLK1ABnAJbdG0IjbOI6jq1cNNWgiqKuExBz4RKR+tLQMLOygAAwiEWKykgmgqsi0VlgoIcQAFAGhAKoYACahAhwFgVjBNQCUoCQAfKAAJLgAFgTYADy5WM31HABusDal4REonTZWAHSFxE2gAPK8AFZYevMEHjYA5sx5M3OLNULWNSXlxAInswtLWPX1arRKGdaMvCgCuig8sNQGMJlNaKcntkBnlqqFGi1QHlyKJElFWBxnvN0foALRXULzZiXDQAUQEAlgAmsnSY0EmPWwBGEoD2oCwAA9sHosKVUWlXu80mpRARSqUgaNxpMUYlIYtoTVYc8Ea1kfzIt4YlicaAANQE4hEklgABysHZFKp1mMWHgnTQ-KUgtE6SUQA)

**Comment by mroch** [comment]
in v0.118, we added a new lint, `unsafe-addition`, which warns if either operand of an addition is `null` or `void`. hope this helps!

add this to `.flowconfig`:
```
[lints]
unsafe-addition=error
```

**Comment by mroch** [comment]
filed https://github.com/facebook/flow/issues/8350 to fix the missing docs

**Comment by carljohnesan** [comment]
Thank you! It helped!
