### ISSUE TITLE
Node_modules folder reporting errors, any way to suppress?

### ISSUE THREAD

**Issue by bringking** [facebook/flow#835]
Maybe I missed a section in the help docs, but having a basic project and running 

```flow check```

results in a ton of errors reported about dependencies inside the node_modules folder. Is there any way to suppress these errors?

<img width="1082" alt="screen shot 2015-09-21 at 8 20 20 am" src="https://cloud.githubusercontent.com/assets/864845/9996027/ed1ad7d6-6039-11e5-9e6d-f5a918c512b4.png">

**Comment by GGAlanSmithee** [comment]
See if #719 or [this](http://flowtype.org/docs/third-party.html) can be of any help.

**Comment by bringking** [comment]
This work around fixed my issues
