### ISSUE TITLE
Timout or recursion error when using set.values().next().value

### ISSUE THREAD

**Issue by mstange** [facebook/flow#8351]
Flow version: v0.122.0

```js
function fun() {
  const mySet = new Set();
  mySet.add(5);
  const val = mySet.values().next().value;
  mySet.delete(val);
}
```

## Expected behavior

Flow should finish type checking this code.

## Actual behavior

Flow times out or exits with a recursion limit exceeded error.

* Link to Try-Flow or Github repo: https://flow.org/try/#0GYVwdgxgLglg9mABKMAKAlIg3gKEYiBAZykQFsBPAZQFNSBeRMGgd0VqgwG49zq6AdAEMAJiNQBWdD3yEwJRADchAG0SNKHAcpUgaRDAOYAPTum2q9MvlpE0VdGqh3ScAXxxA

Adding a type annotation to val (`number | void`) allows Flow to finish:

```js
function fun() {
  const mySet = new Set();
  mySet.add(5);
  const val: number | void = mySet.values().next().value;
  mySet.delete(val);
}
```
https://flow.org/try/#0GYVwdgxgLglg9mABKMAKAlIg3gKEYiBAZykQFsBPAZQFNSBeRMGgd0VqgwG49zq6AdAEMAJiNQBWdD3yEwJRADchAGwBcTEGQBGNAE6IAPkrgwRiRpQ4DlKkDSIYBzAB6d0N1fZl9rImip0NKi20jgAvjhAA

**Comment by mvitousek** [comment]
Thanks for the report and the repro, looking!

Even smaller repro:
```
type MySet<T, R> = {
  delete(value: T): void,
  nextval():
    | {
        value: ?R,
      }
    | {
        value: T,
      },
};

declare var mySet: MySet<*, void>;
const val = mySet.nextval().value;
mySet.delete(val);
```
