### ISSUE TITLE
Duplicated comments in JSX

### ISSUE THREAD

**Issue by thorn0** [facebook/flow#8352]
Flow version: 0.123.0

```
<Example />; // a
<Example />; // b
```

## Expected behavior

There should be 2 comments in the AST.

## Actual behavior

3 comments in the AST. `// a` is duplicated.

* Link to Try-Flow or Github repo: https://github.com/prettier/prettier/pull/8071, [Try-Flow](https://flow.org/try/#0DwUQHghgtgDgNgUwAQHoB8BuVKkQFCiSyKqbZIBGQA)

**Comment by gkz** [comment]
Should be fixed in the next version
