### ISSUE TITLE
Flow infers incorrectly types when enum is involved and there's an if-else.

### ISSUE THREAD

**Issue by shardel23** [facebook/flow#8353]
Flow version: 0.122.0

SetArray is a function of type (Array<enumType>) => void.
Code snippet:
(stringOrEnumValue) => {
                let newArray;
                if (
                  stringOrEnumValue === enumType.value1 ||
                  stringOrEnumValue === enumType.value2
                ) {
                  newArray = [stringOrEnumValue];
                } else {
                  newArray = [enumType.value1, enumType.value2];
                }
                SetArray(newArray);

## Expected behavior
In both cases newArray is Array<enumType>, so there shouldn't be a problem.

## Actual behavior
Cannot call `SetArray` with `newArray` bound to the first parameter because  string [1] is incompatible with  enum [2].Flow(InferError)

* Link to Try-Flow or Github repo:

**Comment by Brianzchen** [comment]
It's more helpful if you provide a try-flow to see what your code actually looks like. Maybe your error is related to your `Array<>` type but I can't be too sure. 

I've tried to replicate your code in a try-flow, and there's no errors, what difference do you have from what I supplied?

https://flow.org/try/#0PTAEAEDMBsHsHcBQiDGsB2BnALqAygKbYCCATqQIYCeoAvKABTYE4BcoZlVAPDqQJboA5gD4AlKwBusfgBM6I0AG8AvgG5kaLLgLoArgFsAKlQAOBOssShQkitD0EAjOwDkTgEwBmVwBprtvaOHm5eACwArH6I6poYOKDMCfQMfIJCAPKkAKL6BgBqQQRiClY20ESg6ATwnNQaNvyQjAE2acJZuYaFDha0-aC6hibmAHR2vU6gAD7TraDtmTl5PY50A0PGZgTjRR4BJUrz1bXk1JYA2oudK0UAug2gKoPQmBZHNjYndTT0F5sjHYTRxOXyDPKA3a9DwPAIqAKEEhnKgMb7IsQaWKIJLYBiuHGuDFAA
