### ISSUE TITLE
Flow cannot find .flow files when re-exporting component using full path.

### ISSUE THREAD

**Issue by ernestostifano** [facebook/flow#8354]
***Flow version: 0.123.0***

### Step 1: Build a React Components Library

`./index.js`
```js
// IMPORT USING FULL PATHS (INCLUDING EXTENSION)
import {ComponentA} from './components/component-a/index.js';
import {ComponentB} from './components/component-b/index.js';
import {ComponentC} from './components/component-c/index.js';

// RE-EXPORT FOR FINAL CONSUMPTION
export {ComponentA, ComponentB, ComponentC}
```

### Step 2: Compile Your Library

1. Your compilation process.
2. **Use** `flow-copy-source` **to ship Flow annotations.**

### Step 3: Try Consuming your Components Library

`./somewhere/in/another/project/index.js`
```js
import {ComponentA} from '@me/my-library';

function App() {
    return(
        // NO PROP HINTS OR TYPE-CHECKING
        <ComponentA />
    );
}

export {App};
```

## What is happening?

Flow is failing to find the `.flow` file (which is right next to each components file).

**Please Note: (In library `./index.js` file)**

* If directory path is used (`import {ComponentA} from './components/component-a';`), everything works fine.
* If extension is omitted (`import {ComponentA} from './components/component-a/index';`), everything works fine.

This is strange because writing `index` without extension, per node module resolution specs, should be the same as writing `index.js`.

Something similar should happen when directory-importing.

Using full path when importing/exporting ensures broader compatibility (ECMAScript modules on the way).

**Comment by Brianzchen** [comment]
I could be wrong and someone else can correct me, but this seems like an issue with module resolution more than anything else.

In your `index.js.flow` library file, when importing without a file extension, for example `./components/component-a/index`, flow can assume and do a module resolution. But when you give an explicit file extension, `./components/component-a/index.js`, there is no resolution taking place so your flow index file is actually importing your transpiled component files which are not flow typed so you're getting no hints/errors.

One thing to note is that `*.js.flow` files do not necessarily have to import another `*.js.flow` file. These files are just like source maps. If I import `A` then give me flow types from `A.js.flow`.
For example I've seen some libraries not use `flow-copy-source` and instead their `index.js.flow` simply maps back to their `/src` code.

I guess it comes down to what compatibility/use cases are you trying to support by adding the `.js` to your import path?

**Comment by SamChou19815** [comment]
It's unclear what went wrong. Unfortunately, there is no repro so hard to debug.
