### ISSUE TITLE
Wrong range of `AssignmentExpression`

### ISSUE THREAD

**Issue by fisker** [facebook/flow#8358]
Flow version: 0.122.0

## Expected behavior

`AssignmentExpression` range should [0,5]

## Actual behavior

`AssignmentExpression` is [0,4]

* Link to Try-Flow or Github repo:

https://flow.org/try/#0IYXgFAjAlEA

**Comment by mroch** [comment]
thanks! fixing this right away

**Comment by fisker** [comment]
I also found it was wrong since oldest  version in `Try-Flow`, nobody use it?

**Comment by mroch** [comment]
@fisker do you have an example for other expressions?

**Comment by mroch** [comment]
found one for sequences: https://github.com/facebook/flow/issues/8364
