### ISSUE TITLE
Extract types of function parameters only works when the extracted types are represented in form of a tuple

### ISSUE THREAD

**Issue by tanqhnguyen** [facebook/flow#8365]
Flow version: 0.123

## Expected behavior
Using `$Call` to extract the function parameter should allow to return the type itself instead of forcing the use of `tuple`

## Actual behavior
Only works if the extracted types are put inside a tuple

I have this simple type to extract types of function parameters (the actual implementation has multiple `Extract` to meet different amount of parameters, I removed them to make the example easier to read)
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHhgE4CGAxhmALxgA8AggHwAU7zAlPa2BQB2WXnX4BtZgF0A3OjzEccMrWz4wzMgHMArgFs8gjAGdGAFX4MAJAGEKMGIxLlqGADRgLcsD7CooOoI0AJZwgmAYeMYY7DgUlHoAXGAARnBwMHhC3MmC+il4ZGAA3qg+ZHgYOmThAIy+vqgAvuhqBACyWGa4BAyaugZGpm1wUBFRGKzejVRh0WBwANbJnd3qDOLkOniyqLOC84JwGADyy2CrPfRg4rWyQA

Now that I need to have a new type to extract only the first parameter, based on the above type, I come up with this
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHhgE4CGAxhmALxgA8AggHwAU7zAlPa2BQB2WXnX4BtZgF0A3OjzEccMrWz4wzMgHMArgFs8gjAGdGAFX4MAJAGEKMGIxLlqGADRgLcsD7CooOoI0AJZwgmAYeMYY7DgUlHoAXGAARnBwMHhC3MmC+il4ZGAA3qg+ZHgYOmThAIy+vqgAvmWNagQAYsFk0Zq6BkbmlmBWhJkDGGa4eCza+oYmQx4ADKyY02AAslhT6gxdPRh984PtcFARURis3o1UYdFgcADWydu7BAzkOnhy94KPQRwDAAeVeWx2GwYtRkQA
Apparently, `$ElementType` can't understand `$Call`'s result

I tried again with another approach which is to return a single type instead of a tuple in `Extract`
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCiAHhgE4CGAxhmALxgA8AggHwAU7zAlPa2BQB2WXnX7MA3OigBXQTQCWcQWAx4AzhnY4KlALYAuMACM4cGHiHcjgmXuN4yYAN6owYMngwyyKgIzugWCoAL5ugZi4BABiCmSazGQA5nZ4ghiMACr8DAAkAMIUMDCMJOTUGAA0YNmR+GAAsliZUfRgsfEYiSl6aRnY+HBQqhoYrFJBqFTKmmBwANZGTS31DOQyeFLTgrOCcBgA8ouNza0MfhJAA

it still doesn't work. I'm not sure if I'm doing anything wrong or there is bug. Feel free to close the issue if it's intended to work that way (also some explanation would be nice so that someone can understand it in the future)

**Comment by SamChou19815** [comment]
We now have `Parameters` as builtin, like TS
