### ISSUE TITLE
When using await, different and confusing error locations for imported functions vs functions in the same file

### ISSUE THREAD

**Issue by julienw** [facebook/flow#8367]
## Proposal
These errors should appear at the most logical location.

## Use case
See this repository: https://github.com/julienw/flow-issue-2
Don't forget to run `yarn install`.

I did 3 test cases:
- test-1.js => uses a libdef
- test-2.js => everything is contained in one file
- test-3.js => uses a local import

The error in test-2.js makes sense: 
```
Cannot call store.get because function [1] requires another argument.

 [1] 13│     get(key: string): boolean;
       :
     20│     const store = tx.objectStore();
     21│
     22│     // $ExpectError
     23│     store.get();
     24│ }
     25│
```
The errors for test-1 and test-3 are the same and are confusing in this case.
```
Cannot call await with openDB() bound to p because:
 • Either cannot call db.transaction because property transaction is missing in Promise [1].

     test-1.js
     2│ import { openDB } from 'idb';
     3│
     4│ async function foo() {
     5│   const db = await openDB();
     6│
     7│   let tx = db.transaction();
     8│   const store = tx.objectStore();

     flow-typed/idb_v5.js
 [1] 2│   declare export function openDB(): Promise<DB>;
```

In this case the error is especially confusing because it makes no sense. The error is still really about `store.get`: adding a parameter to the call fixes the error.

But in more complex cases the "sub" error was properly showing `store.get`, yet the error's primary location still was at `await openDB()`.

There are several problems here:
1. The error itself is super confusing in this case.
2. The location is improper. In more complex use cases, the real error can be quite far from the pointed location.
3. This is especially a problem when writing libdefs for the flow-typed repository, for tests containing $ExpectError comments. Indeed one call (in this case `openDB`) can return an object we want to reuse for several tests, some positive and some negative, and we want to pinpoint the right location of the error.

Thanks for looking at this with me.

**Comment by julienw** [comment]
I was under the impression that some form for this error appeared with Flow v0.121, but this specific error seems to exist for a long time.

**Comment by julienw** [comment]
Replacing:
```js
interface ObjectStore {
  get(key: string): boolean;
}
```
by
```js
interface ObjectStore {
  get(key: string | number): boolean;
}
```
(so using a union as parameter type)
makes an "sub error" appear about `store.get` this time:
```
    Error ------------------------------------------------------------------------------------------ test_idb-v5.x.x.js:8:22
    
    Cannot call await with `openDB()` bound to `p` because:
     - Either cannot call `store.get` because:
        - Either undefined [1] is incompatible with string [2].
        - Or undefined [1] is incompatible with number [3].
     - Or cannot call `db.transaction` because property `transaction` is missing in `Promise` [4].
    
       test_idb-v5.x.x.js:8:22
        8|     const db = await openDB();
                                ^^^^^^^^
    
    References:
       test_idb-v5.x.x.js:13:5
       13|     store.get();
               ^^^^^^^^^^^ [1]
       idb_v5.x.x.js:26:14
       26|     get(key: string | number): Promise<any>;
                        ^^^^^^ [2]
       idb_v5.x.x.js:26:23
       26|     get(key: string | number): Promise<any>;
                                 ^^^^^^ [3]
       idb_v5.x.x.js:17:37
       17|   declare export function openDB(): Promise<DB>;
                                               ^^^^^^^^^^^ [4]
```
But this still has the other weird error, and the "main" error is still on the `await openDB` call.

**Comment by mirek** [comment]
Yes, this is annoying, I'm running into this issue few times a week, the quick workaround is to:

1. put explicit annotation on result of await, ie, instead of:
```
const db = await openDB()
```
...do temporarily:
```
const db: MyDBType = await openDB()
```
...to see correct location, or if you don't have type at hand:
```
let db
await openDB().then(_ => db = _)
```
...will do the trick.

I don't know why flow thinks that result of await can be Promise<R> or R when there's a type error related to that error later on.

**Comment by julienw** [comment]
Thanks for your comment!

> const db: MyDBType = await openDB()

In my case I'm writing this in a test for a libdef in flow-typed. So doing what you suggest here could hide a `await openDB` returning `any`.

Maybe I could also try to cast it to something else with a `$ExpectError` to check this as well...

**Comment by SamChou19815** [comment]
The issue seems to be fixed a long time ago
