### ISSUE TITLE
SomeClass<T> | T erased to any

### ISSUE THREAD

**Issue by charlag** [facebook/flow#8369]
Flow version: up to 0.124

In the provided example `Promise<T> | T` becomes `any` and everything that uses it fails to infer types too.
It doesn't matter if ` Promise<T> | T` is declared as `type` or just inline.

## Expected behavior
Type is inferred correctly and error is reported

## Actual behavior
Error is not reported.

Please not that if in the provided example `$Promisable` (which is `Promise<T> | T`) is replaced with `Promise`, then everything works as expected. My guess is that unification fails in an interesting way here.

* [link to try-flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVATApgYxgQwCcsw98BncsABULgFsBLcrAHgGoAlAPjAG9UYMOQAu+EYxxh8MGKwAqAGjABRGFnoAuMABJaDZvgBG6hd24AKLOvpYAdiPLaAgoUL4AnqzUbuASm19JhZWV3cveXMAbkEwWJEAC3tWAFVLODsAMQBXGChGWQB+bQsANxlsrG1OPzAAXl4g5jY0sAAfMBTlDM4sACtcEWKwKzc4Qm18Ow9ahpo6YJbeDpSA+YMQtJiAX3RsMmIwEQ8ABxI9BcMTNnZI+vXFs3aweRjUKGy7HAkMsAxEL4UERmMoVKpgJgADywGDW8n4sWIImyhDsI3KMEqk2mfkEqF2qCwkJO4xEpAyojAJ0uLAATCVQsoAEKWfDaC4bYymZzcZRGdlNchctgs2aNGlsADazmZAF1-Pd-ghAaILBYAHSaogAc3IYoezXVMhgFh1er8MSEQlQ6jJbINIVEhEYdm13BitrA-IdbDs2XoRiwhHdsWtHy+PzR+BwOCwJ0cAGURM7XeQLE5hMmXdragIrVacBS4Op1fBtencbt86hqRssLTTXy-OrEvY1ZL8Pg+UZZfq8-mwMBgGAAJJk8gJOC5DBgKD4ApgJLEbRGIzCSfTr1gP0BoOhq3R2Px8hJlO6iyryt+IA)

**Comment by mirek** [comment]
Just leave out result annotation to see inferred signature
https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1ABQDwAqAfKALyiGgA+eATrALYCWAzlkccpAK4B2AYxTNYfUJHwBBADSgAQsQAUAQwBceKcVkAjdQQUBKUAG9EoUHSwoedMbgYt2AOmXRoigNqhlO0AF0DRABfM3NQRAFRVhRvcnomNiwnS1ZYaAA3LEUAcmVswMi+aNBtOPsE5xS0zMUARkCw8N5BYVFQDDpmPhQAZRROvgBzRVZ1aIHBo1NzQtToJLhh1kCQxEgVHQMnFAALLD5FAH1yUmnw8xBQAEkY1h3YHmgAE3FlZmhQPct1bVK7h+eJVAfB4jG0WDooQ6XV6-S6w0OHlqAWQQQMQA

**Comment by charlag** [comment]
Thanks for the reply!
I have two questions:
1. This assumes correct `Promise.all` definition. It would already be enough for me (that's what I'm trying to achieve with hacks in the first place). Here's out definition for Bluebird: https://github.com/tutao/tutanota/blob/c86278015ae867c565845cc22a1abb15e2347c71/flow/api/libs.js#L52
Is this the right place? Should I also use TupleMap? https://github.com/facebook/flow/blob/4215b5cfb27254f0e927b557291d13ec2b53d6af/lib/core.js#L692
2. It still feels wrong that in my example it turns into any, did I misuse something?

I will probably just try to replicate definition from core but it still kinda bugs me when things may silently go wrong

**Comment by mirek** [comment]
1. yes
2. yes, don't cast to any

Using `any` means "i don't care if things silently go wrong".
