### ISSUE TITLE
$All utility type

### ISSUE THREAD

**Issue by charlag** [facebook/flow#8370]
## Proposal
I propose to have additional utility type (like `$ObjMap` or `$Call`) called `$All`. It would check that predicate holds for all element of the array. 

Currently it's not possible to assert certain properties like "all keys in this object are nullable".

## Use case
I'm writing a type annotation for [Mithril](mithril.js.org/). It uses hyperscript and utilizes components and props, like React.
I would like to assert that you can omit props if all keys in it are optional. 

So if I have a component

```js
class WithNonNullKeys implements MComponent<{a: string}> {}
```
then I have to use it like
```js
m(WithNonNullKeys, {a: "hi"})
```
but if I have
```js
class WithNullableKeys implements MComponent<{b?: string}> {}
```
I can use it like
```js
m(WithNullableKeys)
```

I use this overload currently:

```typescript
declare interface Mithril {
	// We would like to write a definition which allows omitting Attrs if all keys are optional
	(component: string | Component | MComponent<void> | Class<MComponent<void>>, children?: Children): Vnode<any>;

	<Attrs: {[?string]: any}>(
		component: string | Component | Class<MComponent<Attrs>> | MComponent<Attrs>,
		attributes: Attrs,
		children?: Children
	): Vnode<any>;
}

interface MComponent<Attrs> extends Lifecycle<Attrs> {
	/** Creates a view out of virtual elements. */
	view(vnode: Vnode<Attrs>): ?Children;
}

export type Child = Vnode<any> | string | number | boolean | null;
export type ChildArray = Array<Children>;
export type Children = Child | ChildArray;
```

I would like to say something like
```ts
type $AllKeysAreNullable<T> = $All<$Keys<T>, Nullable>;

declare interface Mithril {
  <Attrs: $AllKeysAreNulalble<Attrs> | void>(component: Class<MComponent<Attrs>, children?: Children): Vnode<any>;
  // ...
}
```

for some definition of `Nullable`.

Please let me know if there is a way to do this already and I'm missing something. It might be that I don't understand Flow deep enough and `Nullable` is impossible to define.

**Comment by SamChou19815** [comment]
This is unlikely to get supported, since the proposed utility type `$All` doesn't return anything, unlike other util types. This is also too specialized.
