### ISSUE TITLE
Type refinement stopped working in 0.125

### ISSUE THREAD

**Issue by frontendphil** [facebook/flow#8377]
Flow version: 0.125

## Expected behavior

The type refinement works as expected (it did in 0.124). In the last version methods written like this produced the expected return type based on the type parameter that was passed. Now, these methods fail the type check.

## Actual behavior

Type error.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phjb4BcYA5IY6gL7q0EBCpFVNXHgaNurDpiFgAKkICyAQxx9K1Qg0IAaAdwbd2nKQAU4AZ1MBLAEYw8s-Kb4ASANJ4spgDz28inAD5DfBkhRzJiAB8wfVQoAFcAOwBjDAs4BLAkgCc8BQw8bwYTc2tbH1N-AAouBmkASgYnAFFbAFs8BIwfb3klTRl-fmok9NMMGgALCwSAcz5s3PyAcQ68LIsk6qE6gQELKGqp2YA6LjAAQhIyLjqh6kmsxDAEvCQmrMesysYER9nBfCMHbUDjUAQ5DBxLIZDBHGYGWKJFJpDILPJ4FYvdabGpgYqWGx2UINIhgKK8VRgUwICwYJITLb4W6U4YKUwEZiMBgQqEZSrkLhsDTA+5JNkcsTcvCQ6FgfmCvQi+5gATUAAmeCgCjiMAwDFhjyQLzeHzgXx+fzmXCBAg4bCAA

----

You can see this even better [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCWAzoQFxgYBOArngDRUu57MA5IUGoAvumz4wAIVIVe9Gczace1KQLCCZoiZn5gAKvwCyAQxzzK1JkXWzmM8ZMMAFOHTo0ARjDwm+HTyACQA0nhYdAA8gXgWOAB8rtJxwWTEAD6y6FDsAHYAxhg0cPlghax45hh4scweXr7+aYkAFJrMRgCUzCEAov4Atnj5GHGxZpZcxokK1IVldBgsABY0+QDm8pXVtQDio3isNIUd-N28ilAd61sAdJpgAIQkZJrd89RrrIhg+XgkP1WL9WG1BAhfls+PhBJdqBJqLwqhh2Kxyhg7psXKg8kUSmUKlUanhDgCTmdOmBGt4-AF+HRekQwNk5DYwHQEDQMIVVud8J92QtzHQCMJBMwUWjyuRNDN6HZVHhEd9CiKxbpJXhUeiKHLaHRlCwOMreN8wGawAATPBQczsGAYFSrX5IAFAkFwMEQqHbTRw3gSfSLfLLMBQOBwHbE2rgkSXXGR+4KoA)

If you change `foo.isA` to `foo.isB` you get a type error. Which is correct because after `create('A')` the result must be of type `A` and can't be `B`.

**Comment by dsainati1** [comment]
Good catch. Working on a fix

**Comment by frontendphil** [comment]
Any status on that? This is halting us from upgrading to any newer flow version.

**Comment by dsainati1** [comment]
The fix for this is quite complex and might not be able to come out before the planned rework of utility types planned for this year. Is it possible to rewrite this code to avoid the use of `$ElementType`? You might try overloading the definition of this function instead?

**Comment by frontendphil** [comment]
Suppressing isn't really an option because that would remove type-safety from some key parts of our application. We use this in some core factory functions. If we can't trust what comes out we have a problem. 

When you're saying "overloading the definition of the function", how do I do that? Is that something I can do inline with the function definition? Do I need to declare the function somehow?

**Comment by dsainati1** [comment]
```
declare function foo(x : number) : string;
declare function foo(x : string) : number;

function foo(x) {
  ... definition goes here
}
```
Something like this. Here, if `foo` is given a number Flow will know it returns a string, and vice versa.

**Comment by frontendphil** [comment]
I guess this one really is harder to fix than I expected :D

**Comment by dsainati1** [comment]
Yea, the fix is quite complex. We are addressing it as part of a larger set of improvements, but I would not expect it to land soon, unfortunately.

**Comment by SamChou19815** [comment]
This now works.
