### ISSUE TITLE
update-suppressions subcommand missing?

### ISSUE THREAD

**Issue by osmestad** [facebook/flow#8384]
In the 0.124.0 release notes: https://github.com/facebook/flow/releases/tag/v0.124.0 a new `update-suppressions` subcommand is mentioned for `flow-dev-tools`, I'm not able to see this anywhere?

Trying to run it as I assume it would be ran results in:
```
../flow/tool update-suppressions --bin node_modules/.bin/flow .
Unsupported command `update-suppressions`
usage: /Users/osmestad/Code/flow/packages/flow-dev-tools/bin/tool [COMMAND]

Valid values for COMMAND:
add-comments     Adds flow comments
babel            Runs babel
convert          Converts legacy tests to new j0nx
error-summary    Shows a list of how many times each error message occurs in a flow check
help             Shows usage message
new-test         Creates a new empty test
record           Records tests
remove-comments  Removes unused flow comments
test             Runs tests
```

**Comment by mroch** [comment]
ah, you're right. this is an internal command we use to deal with overlapping projects. for example, www.facebook.com and m.facebook.com are in the same codebase but have separate .flowconfigs, except there are some files that are included in both. `./tool remove-comments` in www sometimes removes suppressions that are unused in `www` but still necessary in `m`, so `update-suppressions` keeps track of that.

it's still a work in progress that will eventually also replace `add-comments --all` (so, no UI).

I think we can deprecate `remove-comments` and release `update-suppressions`, though it's still pretty experimental. I wonder if it'd be useful to anyone to be worth the effort to generalize?

**Comment by comp615** [comment]
@mroch I'm trying to suss out what that command might do from the comments. We're trying to get to 0.132.0 at Twitter and add specificity to all our suppressions. I'd assumed there would be a codemod to do this, and I'm guessing this might be it? Although from the description above it might be a little different. Is this the right tool for that? Are there other upgrade paths?
