### ISSUE TITLE
Make the "priority list" publicly available

### ISSUE THREAD

**Issue by nnmrts** [facebook/flow#8393]
Since this is an open-source project, the priorities for it should be open and public as well. If the maintainers think they shouldn't be, then at least a clarification about that fact would be wonderful.

I'd suggest a public to-do list, a Github "project" or a regularly updated roadmap.

**Comment by belka-ew** [comment]
Duplicate https://github.com/facebook/flow/issues/6833

**Comment by gkz** [comment]
You can see our 2020 roadmap here: https://medium.com/flow-type/what-were-building-in-2020-bcb92f620c75
