### ISSUE TITLE
Using $Shape does not correctly infer undefined fields?

### ISSUE THREAD

**Issue by nvie** [facebook/flow#8398]
Flow version: 0.126.1 (but older versions are also affected)

## Expected behavior

The expected behavior is that Flow would throw an error on the last line:

```js
type User = $Shape<{|
  +name: string,
  +email: string,
|}>;

const user: User = {
  ...null,
};

user.name.toLowerCase();
//        ^^^^^^^^^^^
//        Would expect error here, since
//        `name` can still be undefined
```

## Actual behavior

It's incorrectly accepted as a valid program, reporting no errors. See [Try-Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AVQM5YBOoAvKACQDKAFgIbYA8A3gD6KigDUAdnQLZYAXKHwoiASx4BzADQduWfnQnQRYyTPmsAvgD4A3MgDGsHmNABXQkREFiZUMwUA6Nz0vRo8nUcTXiFz5BFxRYABkEYgBhOkIACgBKIxBONLSAPSzsnIzEVPS0gHVYTwATUCwAD2xjFEqiIlgSGmIsWVEpYyx8sELOAANgrAHQYzoeURRVaFAAIxxLHjKsSCksMsQgA).

It may be worth nothing that if you avoid the use of `$Shape` in the `User` definition, this bug _is_ getting caught correctly. See [Try-Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AVQM5YBOoAvKAN4A+iooA1AHYCGAtlgPwBco+KRAS0YBzADS0GWVswHRuvfkLGIqAXwDcyAMaxGfUAFdCRHgWJlKEgHQ3GB6NHEbkR4lZbsrKWABkExAGFmQgAKAEpNIA).

**Comment by noppa** [comment]
See #7316, #7730, #7566, #5702, #6039, #6796.

That's how `$Shape` works, it's an unsound escape hatch. Use
```javascript
type Partial<T> = $Rest<T, {...}>
```
instead. [Try Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQiAmBTAxtAhgJzaAC4CeADgQAp6ECW20APACoB8oAvKACQBKaAzoWYAaUAG8AdFIC+LZCXKgAqvzS4O3PthQB5AHbRiDKrlr0GYgD6JQoPdgC2aAFyhBuGnoDmwm6DQO2DTQru6ePoiWsiwA3MgYsHqCoACuqriuKmoaYn5SEnop0NC+0nGIaWoFjmgShLAAMghqAMLYqgAUAJRxILb9-QB6wyOjg4h9A-0A6rBFKP4AHuQYhP64uLDqABZqaKL8nhhoE2BTtgAG9k4XoBjYem60xaAARgQpeuiQnmgoiEA).

**Comment by arcollector** [comment]
please close your question so we can center in the unsewered ones
