### ISSUE TITLE
Functions declared after return statement are not checked correctly

### ISSUE THREAD

**Issue by chrisvasz** [facebook/flow#8399]
Flow version: 0.127.0

## Expected behavior

Functions declared after the return statement should be checked correctly. In this example:

```jsx
function A() {
  let func: number => mixed = () => {}
  return go()

  function go() {
    func('abc');
  }
}
```

## Actual behavior

The commented line above does not trigger a type error, and my IDE shows me that the line is not covered by flow: 
![image](https://user-images.githubusercontent.com/189950/84553810-c2d7ec00-acda-11ea-9015-83bda588d242.png)

If I move the `function go` declaration to a point above the return statement, the type error appears correctly.

[Try-Flow link](https://flow.org/try/#0GYVwdgxgLglg9mABAQQBQEpEG8BQjEA2AplIqJAFyJggC2ARkQE6IC8AfIrTAB5EAmbRBjacsAXzyImJEEyQBzOBhxTy0eIuWZc+fOtQByAIb0Ih9AG4pk8UA)

**Comment by SamChou19815** [comment]
Fixed a while ago.
