### ISSUE TITLE
Add node.js hello world example

### ISSUE THREAD

**Issue by CrabDude** [facebook/flow#84]
```javascript
// @flow
var http = require('http')

http.createServer(function(req, res) {
	res.end('Adam Crabtree is a super cool guy!')
}).listen(8000)

console.log('Server running at http://127.0.0.1:8000')
```

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by samwgoldman** [comment]
Sorry you've waited so long for a response on this. We'd love to see this kind of example come in the form of a community contribution. You or anyone else can contribute docs by submitting a PR to the `gh-pages` branch of this repository. Thanks!
