### ISSUE TITLE
Generic return value of a single-generic, single-branch function is not inferred (incompatible-type error)

### ISSUE THREAD

**Issue by pascallapradebrite4** [facebook/flow#8404]
Flow version: 0.127.0

## Expected behavior

If I have a generic function that takes in a value of that generic type, and simply returns it. I would expect Flow to understand that the returned type is that of the generic type through inference.

My actual use case is more complex, involving a generic type alias with a function inside using that generic, stored in arrays themselves being aliased, where the function finds an item that matches a given business logic criteria, but I was able to simplify the example down to the point where it can be reproduced with a simple identity function.

## Actual behavior

If I have such a function, Flow does not keep track of the generic parameter, and returns an **incompatible-type error** (this example uses `number` for the generic type):

> Cannot assign `id(...)` to `item` because `TData` [1] is incompatible with number [2]. [incompatible-type]

In my example, I pass in the value, so I would expect the return type to be inferred from the function's input, but even if I explicitly pass `number` to the function's generic parameter when calling it, Flow still doesn't infer the return type of it.

This is particularly weird because we can see that the return type is inferred to be `TData`, but for some reason is not "determined" to be the `number` that I defined `TData` to be.

### Workround

I did however find a workaround, where if I **explicitly type the return value of the function** to be `TData`, **no error is returned** and I can use my item appropriately.

As such, the bug doesn't really hurt, but it's still somewhat annoying to have to type the return value of the function manually when the rest of the code base I'm working on pushes for using inference as much as possible. And it still took me a couple of hours to realize the issue was not me misusing types somehow and to figure out how to make it work without just doing an `any` cast or `$FlowFixMe`.

## Minimal reproduction

```typescript
function id<TData>(data: TData)
// Uncomment the next line to see that explicitly typing the return value works.
// : TData
{
  return data
}

const item1: number = id(10) // Error "TData is incompatible with number".
const item2: number = id<number>(10) // Doesn't work either.
```

☝️ [Try on flow.org](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5sxCATAHgBUARAQ33oD4AKcx+gLjDs4EpUwYGACqeOAFtJAU2z4w+ABYyw2GQA8FMQusVwwAZxmrljMJoAOO3IXwwAnooeXdAc0UqwAJxn5M3qQAbvQwmKoIcN4A1oYAdEIiPHxMqADeqGA+fgGkHKkAvui4JIYKdjKSAIw82JiSAEYy3mAAvGTkrFUADPxgwmAAot7eUWAARCn0ZIZkEpKWjIQNMBF2Smr1Td7jCSXYZWT4lQBMtVvNbR2UdY3NbD19A7RwMobYAOQKkTEW680JIA)

Thanks!

**Comment by gkz** [comment]
We don't infer generics. If you have a function which uses generics, you should annotate its return value.

**Comment by pascallapradebrite4** [comment]
Ah, I see the warning in the documentation now that you mention it, sorry for that. Thanks for your time!
