### ISSUE TITLE
Docs should be updated for new error suppression mechanisms

### ISSUE THREAD

**Issue by lyleunderwood** [facebook/flow#8406]
Upon upgrading to 0.127.0, I received the following error:

`.flowconfig:15 Unsupported option specified! (suppress_comment)`

I figured this must be a result of the new error suppression stuff, so I figured I would go to `flow.org` and see what changes I should make to my config to resolve the issue. I found a bunch of documentation that no longer applies:

https://flow.org/en/docs/config/options/#toc-suppress-comment-regex

**Comment by gkz** [comment]
You're right, the docs should be updated.

In the meantime, you can take a look at this blog post: https://medium.com/flow-type/making-flow-error-suppressions-more-specific-280aa4e3c95c

**Comment by dsainati1** [comment]
Docs were updated in 42de9df5cf38d12b6fc51cb6a50f97b17e053828
