### ISSUE TITLE
Flow unable to trace generic type from parameter to assignment

### ISSUE THREAD

**Issue by gitonthescene** [facebook/flow#8407]
Flow version: 1.127.0

## Expected behavior

Flow unable to detect compatible static type from generic parameter linked to argument.

## Actual behavior

Flow able to detect compatible static type from generic parameter linked to argument.

* Link to Try-Flow or Github repo: [Try example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAxngJYBueATmALxgDeqYYA1gIwD8AXGAGcMNcgDsA5gBpWHAEx8wogK4BbAEa1UAX1Qk4ooWChLRDMAB4A8jgwA+ABRgapCtRqSOHgIY1x-axgAlAy2zDLOZFS0ANrsALpmPuLaANzolD5OLlE0-MSRbmZMcvwAzAAs5WA6xqKOEa60HgDk7LLNHlWBqEA)

**Comment by gitonthescene** [comment]
It seems to be binding the type in [the final line here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAxngJYBueATmALxgDeqYYA1gIwD8AXGAGcMNcgDsA5gBpWHAEx8wogK4BbAEa1UAX1Qk4ooWChLRDMAB4A8jgwA+ABRgapCtRqSOHgIY1x-axgAlAy2zDLOZFS0ANrsALpmPuLaANzolD5OLlE0-MSRbmZMcvwAzAAs5WA6xqKOEa60HgDk7LLNHlWBqLXmQiISDlkFTWCt7Z1g3UA).

**Comment by dannyharding10** [comment]
I made it worse by getting rid of all errors! But it doesn't seem to be type checking properly now.... https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBKeAxngJYBueATmALxgDeqYYA1gIwD8AXGAGcMNcgDsA5gBpWHAEx8wogK4BbAEa1UAX1Qk4ooWChLRDMAB4A8jgySwAaX5CREgHwAKMDVIVqNO+z89nYAhjTi-NYYAJQMrswy3mRUtADa7AC6ZmHi2gDc6JRhXj4pNPzEyX5mTHL8AMwALI1gOsainkm+tHYA5OyyvXYt0ejAwGCWlgAKAMpgGAAW5AKCi3BKMAAmYBpgIaa0NHA0AISo7Z2lfn1cQ2AjqEA

**Comment by SamChou19815** [comment]
Now Flow has stricter annotation requirements, and with additional annotations, it should work as expected.
