### ISSUE TITLE
$ObjMap with (relatively) trivial map not doing type checking on first arg of tuple.

### ISSUE THREAD

**Issue by gitonthescene** [facebook/flow#8408]
Flow version: 1.127.0

## Expected behavior
Expected error with first argument of $ObjMap<T,F> in the example below.

## Actual behavior
Does not appear to be doing type checking first argument of $ObjMap<T,F>.  The mapping seems to be treating the generic parameter in the type function as "any" instead of doing type checking.  The second (hard-coded) type does seem to be checked though and is the only thing generating an error the example below.

* Link to Try-Flow or Github repo: Repo with [Try](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN5gCGAXGAM4YBOAlgHYDmYAvgNya4CAIVIUwAIzpsArgFtxeJj37Z8YAMKiZ8xSsEaqGKvC5lyAH1RhqdQgBorEukIfm+6VQQDqLDAAtNMgAeADUAPgAKEIBKUjCwAG0Quw0AXT01ACU8emkYDAAVfTIAEgB5cQArAFkqHCD1Q2M4DhSff3Uw-lQIylowACI-OpwsAZ5baP4IhPIBqgG6AbwADypZHBg8Ae47AEYAZlS6EoAFJjh8Jmwi-CDs3PzbvBT5gbCpntm3ugAmADZdodjmAzhcrjdBPccnlCoJXgsPtMEgkBgBjRADV44FgcLGDOBMNEDVL7I4nc6XRSQu4PWHPBHvT4zVEYhD4gY4vGvQnE0kDfwsa54PBsEkU8HUrDPaGPOH4RlIoA)

**Comment by gitonthescene** [comment]
Here is a [similar issue](https://flow.org/try/#0C4TwDgpgBAglC8UDeUCGAuKBnYAnAlgHYDmUAvgNwBQokUAwglIQK4C2ARhLtbdAOr5gAC0aIAPADUAfAApJASgTSoAbUkAaBgF1e4aACUIWFgBtgAFX0wATEwAk9VKdPjBI+lpjSqVUxGAoAA8ARkwjE3MrSFsmVQBmABYNJO0-AOCbcOMzS2s7RATkgCIk4rSgA) with $Call<F,T>

**Comment by SamChou19815** [comment]
This issue is now fixed with `inference_mode=lti` on, which will become default soon.
