### ISSUE TITLE
Width subtyping does not work with optional property

### ISSUE THREAD

**Issue by charlag** [facebook/flow#8421]
Hi, thanks for Flow.

Flow version: 0.127.0

## Expected behavior
Type without property is a subtype of type with optional property
## Actual behavior
It is not a subtype

Same code as try flow:

```js
type A = {name: string, address: string, also?: ?string, ...};
type B = {name: string, address: string, another: Array<number>, ...};


const b: B = makeB()
const a: A = b


function makeB(): B {
  return {
    name: "name",
    address: "address",
    another: [],
  }
}
```

Please correct me if I'm wrong in my assumption and it works as intended.

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAglC8UDeA7AhgWwgLigZ2ACcBLFAcwBoo0ATGwiPPXAk8qtAGzwHsB+XH1alKUAHQSAvgG4AUKEhQAQgmTosLIiI50GTTW1FoUPYAAsIhXDEKE0IADwoArhgBGlgHxUJYmbICAYx4UAig3XBVEDDQAawglAAoASllg0OBqa1U3ANkAM2cUQOBiEKgY+KTkyORZKCgGYGdCFDqGhvUcKAAiLp6Keo7aekZmXpG9PAGhhuNTCysoAG0AXUGGyVlJIA

**Comment by jcready** [comment]
This is a valid `makeB` function and is why it is not a subtype:

```ts
function makeB(): B {
  return {
    name: "name",
    address: "address",
    another: [],
    also: 1,
  }
}
```

**Comment by charlag** [comment]
I disagree, when I meant `B`, I meant `B`, not supertype of `A` and `B`. It could be declared like so:
```typescript
declare function makeB(): B;
```
and I believe it should still work. Why not? All required properties are there, no optional properties are conflicting.

**Comment by jcready** [comment]
All flow knows is that `b` is a `B` type. The `B` type can have extra properties. Those properties can conflict with the properties on type `A`. Therefore they are not compatible to be assigned to each other.

```ts
// Valid B type
const b: B = {
  name: "name",
  address: "address",
  another: [],
  also: 1,
};
const a: A = b; // not a valid A type since the `also` property is a number instead of a string
```
Conversely
```ts
// Valid A type
const a: A = {
  name: "name",
  address: "address",
  also: "foo",
  another: "bar",
};
const b: B = a; // not a valid B type since the `another` property is a string instead of an array of numbers
```

**Comment by charlag** [comment]
Thanks for the answer! I can understand this with inexact typing - B might or might not have a conflicting property. But what about exact types? We can prove that they *don't* have any conflicting properties

What if we declare B like this:
```ts
type A = {name: string, address: string, also?: ?string, ...};
type B = {|name: string, address: string, another: Array<number>|};


const b: B = makeB()
const a: A = makeB();


declare function makeB(): B;
```

this currently [does not work](https://flow.org/try/#0C4TwDgpgBAglC8UDeA7AhgWwgLigZ2ACcBLFAcwBoo0ATGwiPPXAk8qtAGzwHsB+XH1alKUAHQSAvgG4AUKEhQAQgmQAfdFhZERHOgyba2otCh7AAFhEK4YhQmhAAeFAFcMAI2sA+NTNkBAMY8KARQHrgqiBhoANYQSgAUAJSywaHA1LaqMfFJyXIBNBCBnGgMUABmriiBwMQhULkJKZHSQA).

If I instead declare A as an interface:

```ts
interface A {name: string, address: string, also?: ?string};
type B = {|name: string, address: string, another: Array<number>|};


const b: B = makeB()
const a: A = makeB();


declare function makeB(): B;
```

then it [works](https://flow.org/try/#0JYOwLgpgTgZghgYwgAgILIN4jgWwgLmQGcwpQBzAGmTgBNaoIijCSyQqaAbIgewH5C-NhQC+AbgBQYAJ4AHFACFkAXkwAfbHlakK1OgyYtiujvpC8wAC2iFUUKHBkAeEAFccAI2gA+dRMlAhF4QEmRPQmU1HDgAawhFAAoASklg0LAaO1VkGPik5KlA2ggELjhGZBg3EAQwYBDcuISUyPEgA). Maybe it's a gap in my understanding why one should work and another doesn't

**Comment by noppa** [comment]
@charlag If that was allowed, you could do `a.also = 'foo'` and run into trouble somewhere else where the `B` value is expected to *not* have a property "also", like
```javascript
type A = {name: string, address: string, also?: ?string, ...};
type B = {|name: string, address: string, another: Array<number>|};


const b: B = makeB()
// Flow currently does not allow this, but if it did,
// we'd be able to modify "b" as if its type was A
const a: A = b

a.also = 'foo'

type C = {| ...B, also: number |}

const c: C = {
    also: 10,
    ...b, // woops, this will overwrite "also" with a string-value 
}

c.also.toFixed(2) // runtime error

declare function makeB(): B;
```
[Try Flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeA7AhgWwgLigZ2ACcBLFAcwBoo0ATGwiPPXAk8qtAGzwHsB+XH1alKUAHQSAvgG4AUKEhQAQgmQAfdFhZERHOgyba2otCh7AAFhEK4YhQmhAAeFAFcMAI2sA+NTNkBAMY8KARQHrgqiBhoANYQSgAUAJSywaHA1LaqHgFoYly8qgDkAGY8PMUBCtAAwqpIauISShzcPLhuntZQfkEhYYG49YhIslAT1O24AIwADBTjkxJiHlQA9OtQAO4VYHhUlsR4O8ScnFA8AG7W2yTA0ABEhTyPp5bU+DrkALRXXK5oLJJEECu0xMAeAAxYgADwgNESACZklBNlBCK4UMBiFgoNZCDxCAEaBBApw0AwoKUsYEcSEoDF4klkpFpEA).  
Flow is ok with your example if you either declare the problematic property as covariant/readonly
```javascript
type A = {name: string, address: string, +also?: ?string, ...};
```
[Try Flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeA7AhgWwgLigZ2ACcBLFAcwBoo0ATGwiPPXAk8qgajQBs8B7APy4BrUpSgA6KQF8A3AChQkKACEEyAD7osLImKq16jZvj3tqKPsAAWEQrhiFCaEAB4UAVwwAjOwD4NOXlggGM+FAIob1w1RAw0AGsIFQAKAEp5MIjgagd1b2CAekKoADkram5uPgB3CBoLEAw+Bnli6gkefnUAcgAzPj4e4KVoAGF1JA1JKRUDXj5cTx87KEDQ8MiQ3AnEJHkoQ8r+XABGAAYKA6OpCW8qdprBsDwqG2I8KBriKqg+ADc7DUSMBoAAiLp8MFfYg2aimNhkAC0-x4Hmg8mkoU6CwkwD4ADFiAAPeopABMaSg7UIHhQwGIWCgdkILWCNAgIW4aAYUD6dJCDPCUHiSVSaRisiAA).
or copy the `B` object right before assigning to `A`
```javascript
const a: A = {...makeB()}
```
[Try Flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeA7AhgWwgLigZ2ACcBLFAcwBoo0ATGwiPPXAk8qtAGzwHsB+XH1alKUAHQSAvgG4AUKEhQAQgmQAfdFhZERHOgyba2otCh7AAFhEK4YhQmhAAeFAFcMAI2sA+NTNkBAMY8KARQHrgqiBhoANYQSgAUAJSywaHA1LaqSBJiMfFJyZIBaGJcvKoA5ABmPDxVAQrQAMI5auISShzcPLhuntZQfkEhYYG4bYhIslBz1L24AIwADBSz83keVAD0O1AA7vVgeFSWxHiHxJycUDwAbtYHJMDQAEQVPG9XltT4OuQALT3LiuaCyEppcq9MTAHgAMWIAA8IDREgAmZJQPZQQiuFDAYhYKDWQg8QgBGgQQKcNAMKA1fGBQkhKAFBIpSLSIA).  
This way we can be sure that modifying `a` won't break other places where the same value is expected to be `B`.  
I'm not sure why the interface-version works and if that's intended or not.

**Comment by charlag** [comment]
@noppa thanks a lot for the detailed explanation with examples, aliasing and variance indeed cause issues!
