### ISSUE TITLE
False positive with simple case using bracket notation in objects

### ISSUE THREAD

**Issue by Almouro** [facebook/flow#8426]
Flow version: 0.128.0

## Expected behavior

```js
type StringToNumber = {[string]: number};

const noError = (id: string) => {
  const map: StringToNumber = {
    [id]: "nonsense"
  };
}
```

The above code should fail because "nonsense" is not a number.

## Actual behavior

No error is reported

Note that for the code below, no errors are reported
```js
const id = "matchId";
const map: StringToNumber = {
  [id]: "nonsense"
};
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgDKGATgJYB2A5gCpwByArgLYBGeJYAvGAN4DaAZ1KUqAXQBcYCi3YkAvgG50AYzgVhYMgBNuYAETMAhhhUALAJLb9ytRoxhjOKcXLU6TNhz29UYMPw6kgYU6oJ4Gnj6qEqqYQ4keNqMKhz0cACiJCRwnDwAFDpSwm5UAJTcAHx8fmB2mk4uIu4Mst48vv7+gdrB+qGRkdH+sfKoQA

**Comment by mirek** [comment]
Yes, this is quite bad https://flow.org/try/#0C4TwDgpgBAKlC8UDeAfKBtAzsATgSwDsBzAXQC4oCBXAWwCMIcoUBfAbgCgBjAewOygAzBFAAUeACYVs+YgEoKceAD4xSDJPJQA5AR7AoAQ0q0GObVBZzufAccSDR2gF58A1tuu9+BuhWr0jCKGAHSuBG4cAPRRUHRQeJhQMoREHEA
