### ISSUE TITLE
I can't get HTML properties from Node? 

### ISSUE THREAD

**Issue by simkessy** [facebook/flow#8431]
I'm trying to either set nextSibling or previousSibling on an html element but it's returning this I don't understand. 

   

       let selectedElement: ?HTMLElement;
          const setOptionRef = ref => {
            selectedElement = ref;
          };
        
       const handleScrolling = (direction: number) => {
        const container = containerRef.current;
    
        // Based on keyboard navigation we get the next or previous option
        // When we reach the start or end of the list, move to the start or end of the list based on the direction
        const nextOption =
          direction > 0
            ? selectedElement?.nextSibling
            : selectedElement?.previousSibling;
    
        // Handles which option to display once we've hit the end of the list range
        const endRangeOption =
          direction > 0
            ? container?.firstChild?.firstChild
            : container?.firstChild?.lastChild;
    
        const selectedOption: HTMLElement = nextOption || endRangeOption;
    
        // If one of these nodes is missing exit early
        if (!container || !selectedOption) return;
    
        const containerHeight: number = container.getClientRects()[0]?.height;
        const overScroll: number = selectedOption?.offsetHeight / 3;
    
        const scrollPos: number =
          selectedOption?.offsetTop +
          selectedOption?.clientHeight -
          containerHeight +
          overScroll;
    
        container.scrollTop = scrollPos;
       };

I keep getting these Flow type errors: 

> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> src/Typeahead.js:175:40
> 
> Cannot get selectedOption?.offsetHeight because property offsetHeight
> is missing in Node [1]. [prop-missing]
> 
>      src/Typeahead.js
>      172│     if (!container || !selectedOption) return;
>      173│
>      174│     const containerHeight = container.getClientRects()[0].height;
>      175│     const overScroll = selectedOption?.offsetHeight / 3;
>      176│
>      177│     const scrollPos =
>      178│       selectedOption.offsetTop +
> 
>      /private/tmp/flow/flowlib_349b825f/dom.js  [1] 608│   nextSibling: ?Node;
> 
> 
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> src/Typeahead.js:175:40
> 
> Cannot get selectedOption?.offsetHeight because property offsetHeight
> is missing in Node [1]. [prop-missing]
> 
>      src/Typeahead.js
>      172│     if (!container || !selectedOption) return;
>      173│
>      174│     const containerHeight = container.getClientRects()[0].height;
>      175│     const overScroll = selectedOption?.offsetHeight / 3;
>      176│
>      177│     const scrollPos =
>      178│       selectedOption.offsetTop +
> 
>      /private/tmp/flow/flowlib_349b825f/dom.js  [1] 615│   previousSibling: ?Node;
> 
> 
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> src/Typeahead.js:178:22
> 
> Cannot get selectedOption.offsetTop because property offsetTop is
> missing in Node [1]. [prop-missing]
> 
>      src/Typeahead.js
>      175│     const overScroll = selectedOption?.offsetHeight / 3;
>      176│
>      177│     const scrollPos =
>      178│       selectedOption.offsetTop +
>      179│       selectedOption.clientHeight -
>      180│       containerHeight +
>      181│       overScroll;
> 
>      /private/tmp/flow/flowlib_349b825f/dom.js  [1] 608│   nextSibling: ?Node;
> 
> 
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> src/Typeahead.js:178:22
> 
> Cannot get selectedOption.offsetTop because property offsetTop is
> missing in Node [1]. [prop-missing]
> 
>      src/Typeahead.js
>      175│     const overScroll = selectedOption?.offsetHeight / 3;
>      176│
>      177│     const scrollPos =
>      178│       selectedOption.offsetTop +
>      179│       selectedOption.clientHeight -
>      180│       containerHeight +
>      181│       overScroll;
> 
>      /private/tmp/flow/flowlib_349b825f/dom.js  [1] 615│   previousSibling: ?Node;
> 
> 
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> src/Typeahead.js:179:22
> 
> Cannot get selectedOption.clientHeight because property clientHeight
> is missing in Node [1]. [prop-missing]
> 
>      src/Typeahead.js
>      176│
>      177│     const scrollPos =
>      178│       selectedOption.offsetTop +
>      179│       selectedOption.clientHeight -
>      180│       containerHeight +
>      181│       overScroll;
>      182│
> 
>      /private/tmp/flow/flowlib_349b825f/dom.js  [1] 608│   nextSibling: ?Node;
> 
> 
> Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈
> src/Typeahead.js:179:22
> 
> Cannot get selectedOption.clientHeight because property clientHeight
> is missing in Node [1]. [prop-missing]
> 
>      src/Typeahead.js
>      176│
>      177│     const scrollPos =
>      178│       selectedOption.offsetTop +
>      179│       selectedOption.clientHeight -
>      180│       containerHeight +
>      181│       overScroll;
>      182│
> 
>      /private/tmp/flow/flowlib_349b825f/dom.js  [1] 615│   previousSibling: ?Node;

**Comment by Brianzchen** [comment]
I've answered this on https://stackoverflow.com/a/62855465/13243085. Do you still need help on this?
