### ISSUE TITLE
Can’t assign values to `mixed` when it’s within an Array or Object type

### ISSUE THREAD

**Issue by roryokane** [facebook/flow#8432]
Flow version: v0.128.0

## Expected behavior

According to the documentation page [Mixed Types][mixed-docs], anything can be assigned to `mixed`:

> `mixed` will accept any type of value. Strings, numbers, objects, functions– anything will work.

That documentation page doesn’t say it should work any different when `mixed` is inside an array or object. Therefore, the following code, which uses an `Array<mixed>` type, should pass Flow type checking:

```ts
const arrayOfNumbers: Array<number> = [1, 2, 3];
const arrayOfMixed: Array<mixed> = arrayOfNumbers;
```

Additionally, all of the example code in the “Actual behavior” section should pass Flow type checking.

I know that [covariance and contravariance](https://flow.org/en/docs/lang/variance/) can sometimes cause similar confusion, but I don’t see why it would change my expectations here.

[mixed-docs]: https://flow.org/en/docs/types/mixed/
[TypeScript-unknown]: https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-0.html#new-unknown-top-type

## Actual behavior

Flow raises type errors in four of the six paragraphs of code below (**[demo on Try Flow][try-flow-repro]**):

~~~ts
// @flow

// mixed works when it’s a top-level value
const num: number = 3;
const mix: mixed = num;

// mixed FAILS inside array types
const arrayOfNumbers: Array<number> = [1, 2, 3];
const arrayOfMixed: Array<mixed> = arrayOfNumbers;

// mixed FAILS inside object types
const personWithNumberAge: { age: number } = { age: 55 };
const personWithMixedAge: { age: mixed } = personWithNumberAge;

// mixed FAILS inside indexed object types
const stringsToNumbers: { [string]: number } = { "a": 1, "b": 2 };
const stringsToMixed: { [string]: mixed } = stringsToNumbers;

// mixed FAILS inside indexed object types as function parameters (my use-case)
function withStringsToMixed(obj: { [string]: mixed }): Array<string> {
  return Object.keys(obj);
}
withStringsToMixed(stringsToNumbers);

// generics work inside indexed object types
function withStringsToGeneric<T>(obj: { [string]: T }): Array<string> {
  return Object.keys(obj);
}
withStringsToGeneric(stringsToNumbers);
~~~

The type errors are of this form:

> Cannot assign `somethingContainingNumbers` to `somethingContainingMixed` because number [1] is incompatible with mixed [2] in [some container]. [incompatible-type]

All four errors that Flow raises for the above example code:

~~~
    9: const arrayOfMixed: Array<mixed> = arrayOfNumbers;
                                          ^ Cannot assign `arrayOfNumbers` to `arrayOfMixed` because number [1] is incompatible with mixed [2] in array element. [incompatible-type]
        References:
        8: const arrayOfNumbers: Array<number> = [1, 2, 3];
                                       ^ [1]
        9: const arrayOfMixed: Array<mixed> = arrayOfNumbers;
                                     ^ [2]
    13: const personWithMixedAge: { age: mixed } = personWithNumberAge;
                                                   ^ Cannot assign `personWithNumberAge` to `personWithMixedAge` because number [1] is incompatible with mixed [2] in property `age`. [incompatible-type]
        References:
        12: const personWithNumberAge: { age: number } = { age: 55 };
                                              ^ [1]
        13: const personWithMixedAge: { age: mixed } = personWithNumberAge;
                                             ^ [2]
    17: const stringsToMixed: { [string]: mixed } = stringsToNumbers;
                                                    ^ Cannot assign `stringsToNumbers` to `stringsToMixed` because number [1] is incompatible with mixed [2] in the indexer property. [incompatible-type]
        References:
        16: const stringsToNumbers: { [string]: number } = { "a": 1, "b": 2 };
                                                ^ [1]
        17: const stringsToMixed: { [string]: mixed } = stringsToNumbers;
                                              ^ [2]
    23: withStringsToMixed(stringsToNumbers);
                           ^ Cannot call `withStringsToMixed` with `stringsToNumbers` bound to `obj` because number [1] is incompatible with mixed [2] in the indexer property. [incompatible-call]
        References:
        16: const stringsToNumbers: { [string]: number } = { "a": 1, "b": 2 };
                                                ^ [1]
        20: function withStringsToMixed(obj: { [string]: mixed }): Array<string> {
                                                         ^ [2]
~~~

The last paragraph of my code example, “generics work inside indexed object types”, shows that this issue can be worked around by adding an unused generic parameter to the function. This workaround is only possible if the `mixed`-containing type is a parameter to the function, not if it’s a local variable.

For comparison, when I try writing [equivalent code in TypeScript][TypeScript-equivalent-repro] by changing `mixed` to `unknown`, TypeScript raises no errors. I know that Flow and TypeScript are not always directly comparable, though, since their type systems differ in a few ways.

[try-flow-repro]: https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgLYEsAeBTAJqPLAE4DWAzoQBY4B2oGALoJgElAhqI7AA4C00OAG45ooQW2gBXHIgDGsWuUahaktAC4VagEY5ioALygAzAG45CpemybMuAkdVpzKMHfygAYgEEAkgBkAZQZFDDwcUDZiYjYAT05Y7hxyC0VlKJjYgHlIADkdPXJNb2i4gB4nXWIAPkNQAG0ARgAaUAAmVuMAXXN5NMjS7MgAWWx8YsGy9zxaowy4nPy0KvIXVGmvPyCQ8jCI2G0AKxxZZUZE5NSrJOJyBQB1Jiolqu8AcxxNAG9Ij81KvSgAC+dR+bD+oAArJDgb1LMobndaI9GFRRvZ3p9QGCIRsQUZEQ8ni89Ji1m4xgQfAFghhQuEQuF7KADsdTgkkik+lYlMQ6W9yAAVWAk27fBq8-ldf4FfT47GgABEbEVmhaSu0qvasKuykltAFwvR4wV9X1b2l1mZ8vNQpFstWyHWlM2NJ2e0ZOGZrJOZwu7EokEktFOGAUoG4UTYaBwjEKoAAFGh4pJyDheLI2GmAJSIIMhxhh+jwJ6BRh8g12414BOs8Vm8tS2wuoHZiaZMrm2pfRCgUDEWOSYj0LJHX0AOlIOFi5FrR2z5iBiBLqLLFcNsGrCdtwtF5AXTrAH1oegwskoRDI7oZdKZHh97POnLzwdD4ZXVDX-LtAHE6KfZDKQVqjnQ563NS1BWBNtQBKDsu2xXt+0HYdQFHNlGEnadZ1ZA8lw-L9K2FP8Tz5WRt0bIj7WWQoFyAA

[TypeScript-equivalent-repro]: https://www.typescriptlang.org/play/index.html?ssl=1&ssc=1&pln=29&pc=40#code/PTAEEsDtQFQTwA4FMDKBjATuBAXAsAFCEigCukA1pAPYDu0t1GFAzqLQBZLTg6CYBGwCGoHNQQBaADZIAbkkmgZgyaSSE01SCxyhIpALYAuXQYBGSDKAC8oAMwBudZu2h94AB7HyVOtBt79RyICEm8aenYmVggtcAATJFBBDAxBOBFEJBYnLR1k1LgAeQAzADkzCxZjAEEUtIAeAPMMAD5rUABtAEYAGlAAJj7bAF0gjVykuqLigFVKcMgaqfqw3zabfLSS8v1mliDiMFWIxmY2KBZ4xOpTACskNB0cTOyCcZdkDBZNAHVeDh2zWqAHMkMYAN5JUHGJoWUAAX3akME0NAAFY0Qixs4dJ9vpA-jgOHMfPQQWDQMjUcdoIibHjfv9ARZyQcQkd5r5ImcYpcEjEEu4kHFQDd7o8MshXu8dNosJBgSwYNRmV8IZ0KEg4MY5VBgcMYRVLHTKaAAESCM3GXrm0xWgZYnIuXUKpXUEkLdUdTXa0Au-VeTkRE3+t2q-aEQ5kIMMKLnWL8qCC4Wiu4PJ4vJJsYrkR7gTSgBDJQT6JA4SqgAAU+nSpBYSHEaEE9YAlIQc5A8wXaP8UDh5YrlR7fJWxV6fTr+3qDdHSbSW0sCvV-W1wYRQKAMGXSBhoIU048AHQ+liju4toLwwg9ol9gdu4f0Suh5Xhi+R9mgUGQCzgNBsU4KF5K4BSQIURTFdNJSydtcxwfMGF7KdXWVABxbhfzQeoYBaM9bnHLVJwHGcYARBdQFqJcV0pddN23XdQH3cUcGPLVTzFd8CCvAgbw4O89TddCfywNBn2QwcVSNFgLyAA

**Comment by jcready** [comment]
>I know that covariance and contravariance can sometimes cause similar confusion, but I don’t see why it would change my expectations here.

Here is why:

```ts
const arrayOfNumbers: Array<number> = [1, 2, 3];
const arrayOfMixed: Array<mixed> = arrayOfNumbers;
arrayOfMixed[0] = 'foo'; // allowed for `Array<mixed>` but violates `Array<number>`
```

Because `arrayOfMixed` is allowed to be mutated **and** because it is referentially the same array as `arrayOfNumbers` it is possible that line 3 could occur and is thus an error to allow line 2. There are a couple ways around this.

```ts
// use spread to create a new reference which can be mutated without affecting the `arrayOfNumbers`
const arrayOfMixed: Array<mixed> = [...arrayOfNumbers];

// use a read-only array to prevent mutation
const arrayOfMixed: $ReadOnlyArray<mixed> = arrayOfNumbers;
```

In your follow up examples:

```ts
// mixed works when it’s a top-level value
const num: number = 3;
const mix: mixed = num;
// This is allowed because they are constants and can never be reassigned or mutated.
```

```ts
// mixed FAILS inside object types
const personWithNumberAge: { age: number } = { age: 55 };
const personWithMixedAge: { age: mixed } = personWithNumberAge;
// This fails otherwise I could do
// personWithMixedAge.age = 'foo';
```


[Your try flow link, but with all read-only and no errors](https://flow.org/try/#0PTAEAEDMBsHsHcBQiSgLYEsAeBTAJqPLAE4DWAzoQBY4B2oGALoJgElAhqI7AA4C00OAG45ooQW2gBXHIgDGsWuUahaktAC4VagEY5ioALygAzAG45CpemybMuAkdVpzKMHfygAYgEEAkgBkAZQZFDDwcUDZiYjYAT05Y7hxyC0VlKJjYgHlIADkdPXJNb2i4gB4nXWIAPkNQAG0ARgAaUAAmVuMAXXN5NMjS7MgAWWx8TQASACUcNjws2mhYksyy9zxaowy4nPy0KvIXVHWvPyCQ8jCI2G0AKxxZZUZE5NSrJOJyBQB1Jio9qreADmOE0AG9IiDNJU9KAAL51CFsKGgACsqPhvUsyg+X1ov0YVFG9mBoNAEIA1MiyScEUZcT8-gC9KSjm4xgQfAFghhQuEQuF7KAbvdHgkkik+lYlMReUDyAAVWDMz7ghoyuVdaEFfR08mgABEbANmhahu0JvamLeyg1tHlSuJ431FPqdqBWusQr17sVyp1h2Qxw5p25FyuApwQpFDyeL3YlEgklojwwClA3CibDQOEYhVAAAo0PFJOQcLxZGwywBKRBJlOMNP0eB-QKMWX2v1OvAFkVq13uz206vFQZld21MGIUCgYi5yTEehZO6xgB0pBwsXIvbu1fMcMQLcJbY7Dtg3YLvqVKvIe6DYBBtD0GFklCIZHD-N5go8MbFzwlOtk1TdMjyoE85T9ABxOhn1kMoFWqHdbjVN1201TQFXhEdQBWcoJ3JadZ3nRdQGXUVGHXTdtxFO8DzAiDOyVGCn1lWRL3Qpj-X2Qo9yAA)
