### ISSUE TITLE
Flow 0.127.0 broke $FlowFixMe

### ISSUE THREAD

**Issue by strager** [facebook/flow#8445]
Flow version: 0.127.0

## Expected behavior
$FlowFixMe anywhere in a comment suppresses type checker errors on the following line.

## Actual behavior
$FlowFixMe in a comment suppresses errors only if $FlowFixMe is the only text in that comment.

## Repro

* Link to Try-Flow or Github repo: https://gist.github.com/strager/2184cf46de7c5df7b47a628f05cd4931

In the following example, Flow version 0.126.0 reports no errors (because all errors are suppressed by $FlowFixMe comments), but Flow version 0.127.0 reports an error for the last line (because the comment includes other text in addition to $FlowFixMe):

```javascript
/* @flow */

function add(x: number, y: number) {
    return x + y;
}

add(2, 2);
// $FlowFixMe
add("hello", "world");
// Testing something. $FlowFixMe
add("hello", "world");
```

**Comment by gkz** [comment]
Take a look at https://medium.com/flow-type/making-flow-error-suppressions-more-specific-280aa4e3c95c

Basically we had to standardize the comment suppression syntax, so now comment text before the `$FlowFixMe` is not allowed.

**Comment by strager** [comment]
> so now comment text before the `$FlowFixMe` is not allowed.

Where is this mentioned in the post you linked, or in Flow's documentation?

**Comment by gkz** [comment]
cc @dsainati1 if the blog post/docs need to be updated

**Comment by dsainati1** [comment]
Apparently the docs have never included any info on this as far as I can tell, so I will work on writing something about errors and suppressions in general.
