### ISSUE TITLE
Does not handle switch case cascading correctly

### ISSUE THREAD

**Issue by atty-stripe** [facebook/flow#8447]
Flow version: 0.129.0

## Expected behavior
```js
const absurd = <T>(x: empty): T => {
  throw new Error('Cannot render field.');
};

type Animal = 
  | {type: 'insect'}
  | {type: 'fish'}
  | {type: 'bird'};

const handleAnimal = (a: Animal) => {
  switch (a.type) {
    case 'insect':
    case 'fish':
      console.log('It does not fly.');
      break;
    case 'bird':
      console.log('It flies!');
      break;
    default:
      absurd(a.type);
  }
};
```

I expect this code to not have any errors.

## Actual behavior

Flow thinks the default case is reachable, and errors out.

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBAhgIwgVwE4BMYF4YB4AqAfABQAeAXDAKYC2ADlAJ4CUl+2hMA3gFAwxQAFqhAB3GGCriAoqhGpiAcgDCcMGBCxUVMOiqoYAMwCWVADboAdIuYBuHgF97PJnSowAgmGM04Z7DB8MAA+3K5UlIrGkFTAUIoOQaFc4ZEmEIIJSWGMbpEIxhgJzqCQsIJq6GZUXj5+AcRwlLW+Zswc3EEQosZQwIIwjZbh7bz8-MBwEO5RMXGK5EETUzPpmYvj46UQINWWZiAA5koAkrDoIFQQEppGZozWdkvjCNpwANb2m5PTMIoFRQ2mxg212VH2R1OsEMZlMEAAhDYvsDXlQPsj+HpDHBkGYoEDNgB6QkwaSkNxxASCYzXUB6AQgGAIdzIMBvfqIaoAGnguip+iohhA2husH08ksz34iBQGCGI2RiScPCAA

**Comment by arcollector** [comment]
i dont see any error, if you pass an argument of  type Animal, default case would never happen.

**Comment by atty-stripe** [comment]
There's no logic error, but Flow shows this, leading me to believe this is a bug in Flow.

![image](https://user-images.githubusercontent.com/31416034/88695431-bc4cda80-d0b6-11ea-8650-dd9def604256.png)

**Comment by arcollector** [comment]
why do you need a default case if you have exhausted all the differents Animal types, again theere is no bug here

**Comment by atty-stripe** [comment]
This is a concept called exhaustiveness checking, quite common in type systems. Flow doesn't have a native way to do this, so many users create a helper like the `absurd` function above.

**Comment by arcollector** [comment]
remove the empty type annotation

**Comment by atty-stripe** [comment]
I'm quite familiar with Flow and think my problem is well stated, so not looking for debugging help. Thanks for chiming in, but I'd like to hear from the Flow team here if possible.

**Comment by lulalachen** [comment]
Just FYI, https://github.com/facebook/flow/issues/7303#issuecomment-468007086
Was search for ways of implementing the exhaustiveness check and found this, might be helpful.
But it's weird that it doesn't respect cascading when it's extracted into another function.

**Comment by SamChou19815** [comment]
This is working as expected now.
