### ISSUE TITLE
Flow is too restrictive about spreading objects and computed properties.

### ISSUE THREAD

**Issue by Mr-Wallet** [facebook/flow#8448]
Probably related to #8186

I am trying to upgrade flow beyond 0.111.0 (where many unsoundness problems related to type/object spreads were resolved). However, there's a good chance we will simply stop at a prior version and never upgrade, because the trade-offs aren't clearly making our code safer and more maintainable.

Specifically, we heavily favor a "pure" style of coding where we avoid object mutation whenever possible. Therefore it bears extra human scrutiny whenever we see `o[x] = y;` because that's a code smell. This a problem with the new restriction on computed properties, where the only apparent work-around is to create an object and mutate it later (this also means that inline object definitions are also impossible in many cases, bloating the size of perfectly-readable code.) The only resource on the internet for dealing with these errors seems to be a small afterthought of the [Medium post about v111](https://medium.com/flow-type/spreads-common-errors-fixes-9701012e9d58). (Addl. request: official documentation on flow.org about these errors.)

More concretely, we can't perform operations like these: [Try Flow](https://flow.org/try/#0C4TwDgpgBAogdgVwLZQLxQOQEMNQD6YBGGA3AFCiRQAqATghALJZhpQDeUA2trgRsQC6ALijB60AL7kAxgHs4AZ2BQAHqPjI2vcmQD0eqACIAqouhY4UAJZwAJhFURaRqIoQBzDxGXWFUADNaORRGCDtrLTA5ZQAaKEIEFVsAG1sIYTJ5JRUsAHlaACFROgZmVnQACnYyKDruVRExCTJJEolygEpyAygAOTlgDP65KAQ4PytaCABHBGtpuzFR6YD0qHyigDp9Q0KscyX-SzhBrGBJxT0ZA4u4D3jgAAtrRRs3uUIANz8ERRSQBsaB0WFAAO7WZ5QOS0cGQp5yJJQNJwaAAdh2vQAEnIwRAvs54gAxFK4jZgMBYaZwYAAqA3OAYFTmaBGRHARTWByuZ7QAAG7EkfOWbgg0Ge5xsHN2biwAQgHgQVKWWA8WFsynpIUItnOMOsWBSUEcYFJnP840u7zGcFRMh8iipIB2MoACuchrQ4KJFVTLENoA4AlgECkVF9DQw4c92VAkElzrYPNDaNYPLqjZ8AFYQGTATGGADCJ0GbjA0ywSzWtDiG3s9JLKmmSDkBJs9kczgSuZD5jET2c0FeUFOgVskOgEEQKDkAQ2KSNylT90UO0o0AAGmxOFwueo3OIk00l0n8CPkIQu9IyAFxnnJtGngARCDB0McyrZ0Qbzrfji1eppmABAvX-epwKgIMQzDAA1SNhgwAcFzkDBYgAiCoC2LDs3QqBr0kMg3Q9ZxvWhAlaFTBwoHLORIFoUBH1jeNgETe4UzTDNoUIHM8zXcBoAATW3bg9w0acmnEKNr1vOB738VtnEoiBXWCMBP240QBPiGiwDE5BfygLcanAoCQKsYyMMw7DuLQyzuB0poAAZcPwoA)

Ultimately, the problem seems to be that Flow wants to guarantee it doesn't get into a combinatorial explosion of unions when encountering computed properties. The work-around is to get outside the definition of the, object, and then outside the typecast to the supertype that would contain all those unions, and _then_ assigning the key is permitted. However, this work-around means that we stop scrutinizing object mutations as closely, which could be a problem in a Redux application.

Granted, we could be making better use of `$ReadOnly` to try and avoid this problem, but it's a very large codebase and applying that to 95%+ of our objects would be a huge undertaking just to get better spread typing. As it is, we will probably never even get to "exact by default", let alone re-annotating all our objects as `$ReadOnly`.

What I would like to see (and if this isn't possible, you may consider this a **Proposal**) is some way to tell Flow that I plan on doing the supertype casting immediately, so raising an alarm about the computed property is premature. Intuitively, if it's inside of a literal object definition (heck, even a recursive one), Flow should be able to see if there is a type cast glued onto the object and waive the error as long as the computed property is known to be a subset of the possible keys on the typecast object. In other words, it should be possible for this to pass type-checking even without any new syntax. Instead, it throws a fit over calculating a union that will never be used.

Am I missing something, or is this simply something that Flow can't handle right now?

**Comment by noppa** [comment]
You can get around the second problem case by annotating the defaults explicitly
```javascript
type X = { [idx: string]: string | number };
function withDefaults(obj: X): X {
    const defaults: X = {
        defaultValue: 'hello',
    }
    return {
        ...defaults,
        ...obj
    };
}
```

**Comment by toots** [comment]
Adding a +1 here. We are also using spread patterns that ought to be properly typed by flow. Typically this:
```javascript
const updatableUserAttrs = ({
  startDate,
  title
}) => ({
  ...(startDate !== undefined ? { startDate } : {}),
  ...(title !== undefined ? { title } : {})
});
```
This won't type check because each spread is treated as a union. However, there is no need for a union, the pattern is pretty self-contained and explanatory so one would expect the computed types for each spread objects to be `{| startDate?: ... |}` and  `{| title?: ... |}`.

This is an issue for us because those patterns are really useful, modular, easy to read and conducive to static typing. Flow really shouldn't force us to either break them up or explicitly type them. This example is small but we have much larger ones in the code base for which type inference should work for us not against us..
