### ISSUE TITLE
Built-in casting from maybe

### ISSUE THREAD

**Issue by donalatorre** [facebook/flow#8449]
## Proposal 
Suppose I have `x` of type `?number`. I want to cast `x` to `number`, and throw an error if x is not defined. This is what I'm doing:

```
const x = (4: ?number);
const enforceDefined = (x: ?number) => {
        if(x) return x;
        throw "x is undefined";
};
const y = (enforceDefined(x): number);
```

Which is ok, but it would be nice to have a built-in function to do this for me, specially since this may be useful for any type.

**Comment by jamesisaac** [comment]
NB you can use the utility type $NonMaybeType for casting: https://flow.org/en/docs/types/utilities/#toc-nonmaybe but it has different semantics from your example - it won't throw an error, so you lose some soundness.

**Comment by donalatorre** [comment]
Ok, got it. It makes sense that flow just sticks to compile time errors.
In case someone bumps into the same problem, I found a Node package `assert.invariant`, which pretty much does what I need. It's simply a runtime assertion, but flow understands and stops complaining about `x` being null.
```
const invariant = require('invariant');
const x = (4: ?number);
invariant(x, 'X should be defined!');
const y = (x: number);
```

**Comment by jamesisaac** [comment]
You could also just write that assertion manually:

```js
const x = (4: ?number);
if (x == null) throw new Error('X should be defined!');
const y = (x: number);
```
