### ISSUE TITLE
Invalid "const referenced before declaration" errors

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#845]
I seem to get it for a following code:

```js
/* @flow */

type List = {head:any, tail:List};
const second = (list:List) => {
  const [head, tail] = list;
  return tail;
}
```

**Comment by sporto** [comment]
Same with

```
const { value } = event.target
let languageUser = this.getLanguageUser(value)
```

**Comment by samwgoldman** [comment]
Should be fixed by #831

**Comment by samwgoldman** [comment]
Fixed in e7ea4dc74bb79b62c2b707ceeeacf7ddf102147c

**Comment by Gozala** [comment]
Is this going to be released anytime soon ? I'd like to release version of my library that uses flow via travis.ci but current stable version can't handle many `cost` usages.

**Comment by gabelevi** [comment]
Sorry, I'm working on the deploy right now. Hopefully today or tomorrow 0.17.0 will be released. Thanks for your patience!

**Comment by Gozala** [comment]
Thanks
