### ISSUE TITLE
Broken type parameter inference in higher-order function

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#8458]
Flow version: 0.131.0

## Expected behavior

Should not have type errors:
```js
function some<T>(collection: Iterable<T>, predicate: T => any): boolean {
  for (const element of collection) {
    if (predicate(element)) return true
  }
  return false
}
some(new Set(['foo']), (tag: string) => tag.startsWith('a'))

const some2 = <T>(predicate: T => any) => (collection: Iterable<T>): boolean => {
  for (const element of collection) {
    if (predicate(element)) return true
  }
  return false
}
some2((tag: string) => tag.startsWith('a'))(new Set(['foo']))
```

## Actual behavior
```
15: some2((tag: string) => tag.startsWith('a'))(new Set(['foo']))
                                                ^ Cannot call `some2(...)` with `new Set(...)` bound to `collection` because string [1] is incompatible with `T` [2] in type argument `Yield` [3] of the return value of property `@@iterator`. [incompatible-call]
References:
15: some2((tag: string) => tag.startsWith('a'))(new Set(['foo']))
                                                         ^ [1]
9: const some2 = <T>(predicate: T => any) => (collection: Iterable<T>): boolean => {
                                                                   ^ [2]
[LIB] ..//static/v0.131.0/flowlib/core.js:540: interface $Iterator<+Yield,+Return,-Next> {
                                                                    ^ [3]
```

If you look at this error it doesn't even give a hint about what type it has inferred for `T`.  Maybe it's failing to even infer a type at all?

* Link to Try-Flow or Github repo:
https://flow.org/try/#0GYVwdgxgLglg9mABAZzgWwKYB4AqA+ACgjgBsSNp4wAuRASSgwCcBDAI3NzwBpEAHJhgAmMCC0a0ciALx5ELMAE8AlLTZxSGBYgDeAKESJgcJoiIJkURBnKYwVuMETEyFWAmW6DhxDCcEBYVFxDAIbDDsoZU9BKBAmJCgmEAxvAF9vWPikYBYSZFSM1EwCMAwAd0QAZQwoAgBtAHJjOEaAXWVeAigWAHNaSyYYMF7PWUQe3oA6SxYmKGQAdRgoAAsCRpZG6L09YjBLFHQMACYZRC4AwRExCUQpcYUVGTlzV0oEWgZmdk58VUQ6k02nG+kMxlM5gOVnCkUQjmcpHIHzAnjBPj8ZkCNxCYVsGHs0UQWQSE2SqUMGUMJJyeQKeiKxxOBG6fQGSWGoxeEz6Mx68yWK3Wm22ylKFWqtQazQ07R2QA

**Comment by SamChou19815** [comment]
This is now fixed with new escape-generic annotation requirements.
