### ISSUE TITLE
Exporting Polymorphic functions

### ISSUE THREAD

**Issue by DanielHeath** [facebook/flow#846]
I've run into an odd issue. The following code typechecks fine if I don't export the variable:

``` js
/* @flow */

export var Url = SequenceCb(function Url(idx: number): string {
    return `https://${idx}.example.org`;
});

function SequenceCb<U>(cb: (x: number) => U): () => U {
    var idx = 0;
    return function() {
        idx = idx + 1;
        return cb(idx);
    };
}
```

Flow 0.14 produces:

```
test.js:3:18,5:2: type parameter U of function call
Missing annotation
```

I can't see a way to provide the annotation flow is asking for.
I tried `... Url = SequenceCb<string>(functi...` but that generated:

```

test.js:3:18,5:1: relational comparison
Error:
test.js:3:18,34: boolean
Cannot be compared to
test.js:3:37,5:1: function

test.js:3:29,34: identifier string
Could not resolve name

Found 2 errors
```

**Comment by ianobermiller** [comment]
Any update? I'm running into the same thing trying to use a typed version of `react-redux`s `connect`:

function typedConnect<
  TDefaultProps,
  TProps,
  TStateProps: $Shape<TProps>,
  TDispatchProps: $Shape<TProps>,
>(
  mapStateToProps: (state: AppState) => TStateProps,
  mapDispatchToProps:
    (dispatch: (action: AppAction) => void) => TDispatchProps,
  component: _ReactClass<TDefaultProps, TProps, *, *>,
): _ReactClass<TDefaultProps, $Diff<TProps, TStateProps>, *, *> {
  return connect(
    mapStateToProps,
    mapDispatchToProps,
  )(component);
}

**Comment by Gozala** [comment]
I'm pretty sure this is the same issue as #2105. It's just polymorphic high order functions needs to return function that is explicitly annotated as polymorphic with params bound to outer parameters or else those functions are treated as monomorphic but not fully typed.

**Comment by SamChou19815** [comment]
Types first will require all exported symbols to be annotated.
