### ISSUE TITLE
Flow 0.16 in opam

### ISSUE THREAD

**Issue by pvolok** [facebook/flow#847]
Flow 0.16 is out but not in opam yet. Just a reminder.
@gabelevi

**Comment by wldcordeiro** [comment]
@int3 this issue is older but it's true for the new 0.18 as well.

**Comment by gabelevi** [comment]
Looks like the PR is outstanding https://github.com/ocaml/opam-repository/pull/5036

**Comment by avsm** [comment]
@gabelevi it fails to build in CI, so we can't merge it yet.

```
# File "src/server/autocompleteService_js.ml", line 128, characters 14-29:
# Error: Unbound value Debug.json_of_t
# Command exited with code 2.
### stderr ###
# abort: there is no Mercurial repository here (.hg not found)
# make: *** [build-flow] Error 10
```

**Comment by Eyyub** [comment]
@avsm : See #1013, maybe yiou will have a solution
