### ISSUE TITLE
Disjoint union in tuple to express function arguments does not work

### ISSUE THREAD

**Issue by frontendphil** [facebook/flow#8470]
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phgCGAXGAM4YBOAlgHYDmqAvutnxgACizg5GAHkIsujAHykKVMAAsaHACYw8LBgAoAdMZqzGDGXICUpRQDc4bTX3RQArhwDGGNnA5gAYTgAWxw-PA4MfXI1DW1dMF4GUXEpAG1mdm4wAB8iAF15G0pqdS0dFn0Acgw8ZiqrdGoWPAw3Fn8ONxgYPiA

Flow version: 0.132.0

## Expected behavior

In the example above I would expect to be able to call `handler` with both a `string` and an object of type `A`. 

## Actual behavior

It seems like when expressed like this flow expects the argument to be both a string and of type `A`

**Comment by SamChou19815** [comment]
Expected behavior due to function parameters have to be contra-variantly typed
