### ISSUE TITLE
A name can be used as a type only if it refers to a type, interface, class, or enum definition.

### ISSUE THREAD

**Issue by gajus** [facebook/flow#8475]
```js
import Cursor from 'pg-cursor';
import Result from 'pg/lib/result';

export default class QueryStream extends Readable {
  _reading: boolean;

  _closed: boolean;

  _result: Result;

  cursor: Cursor;

```

`pg-cursor` and `pg/lib/result` are untyped.

This code used to work and assume that `Result` and `Cursor` are `any`.

Starting `0.132.0` it is throwing an error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/QueryStream.js:23:12

Cannot use Result as a type. A name can be used as a type only if it refers to a type, interface, class, or enum
definition. To get the type of a non-class value, use typeof. [value-as-type]

     20│
     21│   _closed: boolean;
     22│
     23│   _result: Result;
     24│
     25│   cursor: Cursor;
     26│


Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/QueryStream.js:25:11

Cannot use Cursor as a type. A name can be used as a type only if it refers to a type, interface, class, or enum
definition. To get the type of a non-class value, use typeof. [value-as-type]

     22│
     23│   _result: Result;
     24│
     25│   cursor: Cursor;
     26│
     27│   batchSize: number;
     28│

```

It is not clear how to update the code if I want to continue treating these references as `any`.

To be clear, I still want to reference them here, since it serves the purpose of documentation.

The first thing I tried was to mark them as untyped, but that does not eliminate the error:

```ini
[untyped]
.*/node_modules/pg-cursor/.*
.*/node_modules/pg/.*

```

**Comment by Brianzchen** [comment]
This is intensional with the latest release, check out https://github.com/facebook/flow/releases/tag/v0.132.0
> Disallow using any-typed values type annotations.

All you need to do is just like the error message says and update `cursor: Cursor;` to `cursor: typeof Cursor;`

[Example](https://flow.org/try/#0CYUwxgNghgTiAEA3W8AeAueUB2BPA3AFCFgD22AzgC7y6arwC88AzEWZTQF6ZW4AOIUgDM0TVviA)

**Comment by keithgabryelski** [comment]
This change makes it incredibly difficult to justify upgrading flow when a large repository uses many non-flow imports.

How can I disable this error ? or at least tag someone on the flow team to be responsible for updating all my company's code that is currently broken?

**Comment by gajus** [comment]
@Brianzchen The error says to use `typeof`

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/types.js:28:20

Cannot use WebClient as a type. A name can be used as a type only if it refers to a type, interface, class, or enum
definition. To get the type of a non-class value, use typeof. [value-as-type]

     25│
     26│ export type MaintenanceTaskServiceConfigurationType = {|
     27│   +slackAppId: DatabaseRecordIdType,
     28│   +slackWebClient: WebClient,
     29│   +sparkpostApiKey: string,
     30│   +twilioClient: TwilioClientType,
     31│   +twilioCredentials: TwilioCredentialsType,

```

When I try to use `typeof`, I get another error:

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/types.js:28:27

Cannot reference type WebClient [1] from a value position. [type-as-value]

 [1]  6│   WebClient,
       :
     25│
     26│ export type MaintenanceTaskServiceConfigurationType = {|
     27│   +slackAppId: DatabaseRecordIdType,
     28│   +slackWebClient: typeof WebClient,
     29│   +sparkpostApiKey: string,
     30│   +twilioClient: TwilioClientType,
     31│   +twilioCredentials: TwilioCredentialsType,

```

It is not clear what is the solution.

**Comment by gajus** [comment]
> This change makes it incredibly difficult to justify upgrading flow when a large repository uses many non-flow imports.

Not to mention that you need to rewrite your codebase again once types are added.

**Comment by keithgabryelski** [comment]
> This change makes it incredibly difficult to justify upgrading flow when a large repository uses many non-flow imports.
> 
> How can I disable this error ? or at least tag someone on the flow team to be responsible for updating all my company's code that is currently broken?

here is my primary concern:

```
Cannot assign new QuotesApplet() to this.quotesApplet because QuotesApplet [1] is incompatible with class
QuotesApplet [2]. [incompatible-type]

   quotesApplet: typeof QuotesApplet;      <----------- QuotesApplet is a class

   configure(space: DiffeoApplicationSpace, features?: Object) {
     super.configure(space, features);
     space.state.addReducers(reducers);
     this.rootElement = 'boardsApplet';
     this.quotesApplet = new QuotesApplet();  <---------- this right here
     space.registerApplet(this.quotesApplet);
   }

```

I'm trying to create a narrow case that fails -- i haven't yet done been successful.

in this case, the call of `new QuotesApplet()` doesn't seem to have a reasonable resolution

**Comment by bobsilverberg** [comment]
We have a project that only has partial Flow coverage. Prior to this release we were able to define a type in a file that isn't covered by Flow, import that type into a file that is covered by Flow, and it all worked. Now that generates this error. 

Is there a plan to provide an option to disable this error?

**Comment by gkz** [comment]
There are no plans to disable the error. Using something that is `any` or is in an untyped file as a type is meaningless, it's just `any`. You can replace all those annotations with `any`. I'll look into providing a better error message.

**Comment by ospfranco** [comment]
I'm sorry, but that is not a solution, semantically speaking the types might be any, but replacing them with any in the codebase looses information for whomever is reading the code.

Could we consider for a moment here that not only machines read the code and realize that forcing us to replace everything with `any` is a bad solution?

**Comment by gkz** [comment]
You can type it as `any` and add a comment. It's more confusing when reading the code to use annotations that look like types but are actually secretly `any`.

**Comment by Download** [comment]
Trying to upgrade flow, which had not been done for a long time on a big project I am working on and I am realizing why.... I already solved a ton of errors and now I hit this and it basically is a dead end. 

You had community members very clearly tell you there is a problem with release 0.132.0 in that it makes it nearly impossible for many projects to upgrade. You ignored those comments... 

Why not put these kind of improvements behind a flag so people can upgrade their projects and turn on extra checks when needed/useful to them? If I read your comments i will have to change a thousand files just so Flow stops complaining about something which really has no negative impact at all.... Sad now.

**Comment by Download** [comment]
> realize that forcing us to replace everything with any is a bad solution?

Without any way to suppress this error that does not involve changing hundreds of files, this is the end of the line for my upgrade attempt. I cannot justify these changes to my employer. I realize it's been a long time since 0.132.0 came out. However, I still want to comment here. Because I think the Flow developers have stepped over the issue raised here too easily. You could have added a config option that would have allowed us to get the benefits of Flow without having to pay this huge price.

**Comment by rachaelbrownie** [comment]
I am with you @Download. I have been working on this for a while and now I want to give up. There has to be a way to suppress this, it's the only reasonable option here.
