### ISSUE TITLE
Overloaded function is not refining maybe type

### ISSUE THREAD

**Issue by UnsungHero97** [facebook/flow#8477]
Flow version: `v0.130.0`

## Expected behavior
I have the following validation function:

```
declare function isValidUUID(value :null) :false;
declare function isValidUUID(value :void) :false;
declare function isValidUUID(value :mixed) :boolean;

const UUID_PATTERN = /^[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$/i;
function isValidUUID(value) {
  return value && UUID_PATTERN.test(value);
}
```

The goal is to validate a value and pass it on to a React component.

```
let orgId :?UUID;
if (isValidUUID(orgId)) {
  return (
    <OrgContainer orgId={orgId} />
  );
}
```

The expected behavior is for Flow to refine `orgId` as not `null` or `undefined` because the only way to enter the `if` body is when `orgId` is defined. I've tried various approaches to typing `isValidUUID`... using an interface, using `%checks`... haven't been successful.

## Actual behavior
Flow gives the following error:

```
Cannot create `OrgContainer` element because null or undefined [1] is incompatible with string [2] in property `orgId`. [incompatible-type]
```

https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50ATMqmCqzCEAnjjJgAqpICSAETABeMAGdC+DADsA5l179BEqAFdNNDHE1gMKgGoUYGbtPkAKAG4PjEgFybjMDAAlGA+UA4qZHp8AkImZoQWVjb2js6ych5evu5wTiFhEVGo+rFGpuaW1nYOTi6ZnjDeoVgYAB5k3AUARnBwMJSaXKhUlmpSGQD6AAoAggAq8wCiJABySmDAAHoA2gAMALQAnLMHAGIAugDeABwAvgf7x6eXVwAsD08n59cfj4ffV5-L4va4ARgATHcACTADBceKVZI1NL1LJNMghK6oMBgViEYz4KyNZoAMlJE3kMwWyzWADpCGQ1OjvEEuHd0KJxGAAPL4bTTeg4FQbbG4gjaGTcUL1dlcUaacZ87QAYUshAoWjI+A2riuYAlUrAd1CysFcGFIUUAD4wGK8WQCUSwK4cbiwAAebgYdzWq6G7h3D3Ab2+t1s1B3YZciSzHA4c3C0VugOhAD8ssj8rGxDjODVmg1Wp1yj1Bv5RpNPjziZUVtt9owUBdKVq6TcAaCWLduPxhKsrvd7o9yoLRc02vLku4in9FcDm2tPbAEdxHN7jv7YH8gTlQA

**Comment by SamChou19815** [comment]
This is not the pattern we intend to support. We allow predicate functions to refine values.

**Comment by gkz** [comment]
I would try something like this instead: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcwAlAUwEMBjYqfOLMAcn0pqYG50ATMqmCqzCEAnjjJgAqpICSAETABeMAGdC+DADsA5l1RU4mtVNlyA+gAUAggBUbAURIA5JWGAA9ANoAGALQBOK18AMQBdAG8ADgBfXx8AoLDwgBZY+MCQiNS4vwyk7PTEiIBGACZogBJgDD0oAFdNGgxDMAA3ChgMbgpCMml5AAp2mDqyAEoALjAAfn6FcNQwMFZCOvxNNo7RsAAyHZN5S1sHZwA6XrUhrfGZzZGJKc06mBguaPRRcTAAeXxtC3oOBUrgWSwI2hk3DAEzmby4BiMxF+2gAwoZCBQtGR8K4BuEwODIWBotDkQC4ECxkoAHxgUHLMirdZgAaLJZgAA83AwrWp4UJ3GiHOA3N5bLGcI+YgkVhwOHJQJBbIF0NmpklCOMspwaM0GKxOOUeIJf0hUywFBEACMyMiiSSJtqFSoqYpafTNcQVcphl0en1TAMLdbbabuBK2RgoCyBVT6UsVmsNqz2eyOcjdfrNNiTRDuIp+WGScBqWylhGlu8E4yk2Ani84UA
