### ISSUE TITLE
The search functionality is mostly useless

### ISSUE THREAD

**Issue by Brianzchen** [facebook/flow#8478]
I'm trying to jump to the flow options `exact_by_default` quickly but typing in the search gives me random results. I'd have to just type it in google or navigate manually through the docs section.

Attached screenshot of results I get.

<img width="1440" alt="Screen Shot 2020-09-03 at 9 51 31 am" src="https://user-images.githubusercontent.com/12436524/92048453-14b87b80-edcb-11ea-853c-43ce43fd2a98.png">

**Comment by SamChou19815** [comment]
Since the new website is released, it should be usable now.
