### ISSUE TITLE
Type refinement can't be put into reusable function

### ISSUE THREAD

**Issue by Brianzchen** [facebook/flow#8479]
Flow version: 0.133.0

## Expected behavior
There should be no errors as the `if` shouldn't be run unless the type is correct

## Actual behavior
There is an error saying that it can't find properties of string and boolean even though my `valid` function does type refinement

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAKlC8UBGB7FAbCBDAdlAPlAM7ABOAljgOYFQDeUokAXMWZTQL4DcAUACYQAxuiyloANzFQsrGH15CUOElCnpy-BFAAUKJACs5ASgQA+eryhRyAM11MIKe-oMJ4iAOQkK1T6fFgAFdSPFssdCIIPms7B3AnF0N3L1QMbBx-KECQsIiomOyIYNDGUiDo3h5eXjiddU0dLGNTOisoJRV0gDp0FCom7sdjPk4ausdnGSgAQg8ob3Y-KAAyFcYEqaxZ+c80zFwstutOoh6+gawhhJGqoA

**Comment by jcready** [comment]
Read the docs: https://flow.org/en/docs/types/functions/#toc-predicate-functions

https://flow.org/try/#0C4TwDgpgBAKlC8UBGB7FAbCBDAdlAPlAM7ABOAljgOYFQDeUokAXMWZTQL4DcAUACYQAxuiyloANzFQsrGH15CUOElCnpy-BFAAUKJACs5ASlaoM2PAFIhAC2EBrIlAQA+erxfjgAV1J4mCBQAMyh9AygAQnhEAHISCmpYqAAyFMZwINDwqJioWPNMXFi+Hl5eclCddU0dLGNjDxclFQsAOnQUKjq2wONS8srdQJCZXLiEjmS0jMhRrHH8wstYxrpPKBaids7urF7M-t5OIA

**Comment by Brianzchen** [comment]
Perfect just what I'm looking for! Thank you 🙏
