### ISSUE TITLE
Interfaces can't be accessed with bracket notation

### ISSUE THREAD

**Issue by levenleven** [facebook/flow#8483]
Flow version: 0.133.0

## Expected behavior

It should be possible to use valid keys with bracket notation for accessing properties of variable of interface type

## Actual behavior

Results in error: _an index signature declaring the expected key / value type is missing in ..._

```typescript
interface Headers {
  Authorization: string,
}

const headers: Headers = { Authorization: '' }
const a = headers['Authorization'] // error here
```
[Try-Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAdgFwKYCdIEMBjTUACUzwBMcBnUAb0VFAEEBXdAC1m2QC890yWKgBcoauh6oA5gBpEAX0SICwiaA7kq2amLKUaoALz0W7Lj36DhYgOS3QS1anV5jGrTQDattp258AkKotgC6QA)

I know it works fine if `interface` is replaced with `type`. But it is not possible when declaration is from builtin types for example

**Comment by SamChou19815** [comment]
This was fixed in the latest release
