### ISSUE TITLE
Adding never type to the library

### ISSUE THREAD

**Issue by MuhammedBeraKoc** [facebook/flow#8484]
##  Proposal
Adding a new type called `never` -though naming can be changed- to the predifened types for functions which throw an error or loop endlessly.

## Use case
Especially useful for error functions.
```js
function ThrowAnError: never {
  throw new Error('Oops! There is a problem.')
}
```

**Comment by lyleunderwood** [comment]
I think this is just the `empty` type. ([try](https://flow.org/try/#0MYewdgzgLgBApgJwSBMC8MAUBKAXPAWwAcoBPdAPhgG8AoGGKAC2QHcYw52BRJFHANy0AvkNqhIsAIb4wAVwIAjROnh8Eg2uPDQ1yBACZVOfHGJlKNEUA))
