### ISSUE TITLE
Union issue: Type A is not B and not C, but is B | C

### ISSUE THREAD

**Issue by nrabinowitz** [facebook/flow#8486]
Flow version: 0.133.0

## Expected behavior

Given the following definitions:
```
type Constant = 'constant';

type FieldExpr<T> = {|
  +field: string
|};
type LiteralExpr<T> = {|
  +literal: T
|};

type Expr<T> = FieldExpr<T> | LiteralExpr<T>;
type ConstantExpr<T> = Expr<Constant> | LiteralExpr<T>;
```
there should be no way that `Expr<number>` could be cast to `ConstantExpr<number>`, as it doesn't match either branch of the union.

## Actual behavior
```
const field: Expr<number> = {field: "foo"};

// These two fail as expected, demonstrating that the field is not part of the union
(field: Expr<Constant>);
(field: LiteralExpr<number>);

// Should fail, but pass
(field: ConstantExpr<number>);
(field: Expr<Constant> | LiteralExpr<number>);
```

[Link to Try-Flow](https://flow.org/try/#0C4TwDgpgBAwg9gOwM7AIYOFAvFA5AY0RXWFwG4AoC0SKAMQEsIAbAEwFEAPMAJwB4AKgD5sUAN4AfClCgBqAGZM2ALigoeDBAHMKEgL6Ua0ADINgEHqmZdegkTknS5zMxauqBug1SNQb-YVFGFg5uAJEJKFNzS2swu0pqcGh4ZDQMfztRTNTiDAio11jM4UTCNKhFENVMhABXAFsAIwt7cSqVKAAieTg4Lu8KAHoh+lQGZihUJCgIbgh8c1YKAAoO1hr43PTgIQBKSjWlDcKYq1rGlp59yhGoAGUACzg6tkrx5gAaKCa6zDBpkhVutVNsSBdmq0DsDjptbGD8lBItE3HFbPVIddoVQgA)

**Comment by SamChou19815** [comment]
This is working as expected, since we will expand `FieldExpr`.
