### ISSUE TITLE
Question: is it possible to annotate objects that act like maps?

### ISSUE THREAD

**Issue by submain** [facebook/flow#849]
Suppose I have a regular object:

    var someobj = {
        item1: { name: 'Some Name' },
        item2: { name: 'Some Other Name'},
        item3: { name: 'Yet Another Name'}
    };

Is there a way to create a type alias where the values are of a fixed type, but the keys can have arbitrary names?

I'd imagine something like:

    type Item = { name: string };
    type MyObj = Object<Item>;

Thanks!

**Comment by mroch** [comment]
yep, `{ [key: string]: Item }`

see http://flowtype.org/docs/objects.html#objects-as-maps
