### ISSUE TITLE
Destructuring a nullable object with fallback to an empty object leads to false negative

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#8491]
```js
// @flow strict
type Foo = {foo: string}

declare var object: ?Foo

const {foo} = object ?? {}

;(foo: string)
```

Flow version: 0.34.0

## Expected behavior
```
property `foo` is missing in null or undefined [1]. [incompatible-use]
```

## Actual behavior
```
No errors!
```

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKBQJ4AOApqAGKyygC8oA3pFQFzLoYB2A5gL664ATElmgBDNGQBu40LABGAK2EpWAfkqx+WWB1QMmsHrVmLloVaoZ9cAbgAUB1qkzcAlLiA

**Comment by TrySound** [comment]
This is just unsealed object. It always behaves this way.
https://github.com/facebook/flow/issues?q=is%3Aopen+is%3Aissue+label%3A%22unsealed+objects%22
Here's how you can get sealed empty object
https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKBQJ4AOApqAGKyygC8oA3pFQFzLoYB2A5gL664ATElmgBDNGQBu40LABGAK2EpWAfkqx+WWB1QMmsHrVmLloVaoYA6GxwCu0aH1wBuABQHWqTNwCUuIA

**Comment by Hypnosphi** [comment]
@TrySound there's an error in your example:

```
6: const {foo} = object ?? {...null}
          ^ property `foo` is missing in object literal [1]. [prop-missing]
References:
6: const {foo} = object ?? {...null}                           ^ [1]
```

**Comment by Hypnosphi** [comment]
This seems to work correct though:

```js
const {foo}: $Rest<Foo, {...}> = {...object}
```

https://flow.org/try/#0PTAEAEDMBsHsHdQGcAuAnAlgYxQKBQJ4AOApqAGKyygC8oA3pFQFzLoYB2A5gL664ATElmgBDNGQBu40LABGAK2EpWAfkqx+WWB1QMmsHqwAkAJRKoAPBoA0DAHSOeAPloPH8pTj64A3AAoDVlRMbgBKXCA

**Comment by SamChou19815** [comment]
Now this errors since unsealed object support is removed.
