### ISSUE TITLE
Presence of an unrelated statement can affect whether errors are reported in other places

### ISSUE THREAD

**Issue by suchipi** [facebook/flow#8492]
Flow version: 0.134.0

## Expected behavior

Adding or removing a statement referencing one variable should not affect whether errors are reported on a completely different variable.

## Actual behavior

The presence of a statement referencing one variable can cause flow errors to disappear in a different, unrelated variable:

![2020-09-25 02 56 28](https://user-images.githubusercontent.com/1341513/94249371-0e568480-fedd-11ea-9eb9-cb3776a518f6.gif)

* Link to Try-Flow or Github repo:

The code shown in the above GIF is found here in this repro repo: https://github.com/suchipi/safety-match-flow-test

Instructions for reproducing:
- Clone the repo
- Run `yarn install`
- Run `yarn flow status`
- Notice flow reports an error
- Uncomment [line 7 of `src/index.js`](https://github.com/suchipi/safety-match-flow-test/blob/main/src/index.js#L7)
- Run `yarn flow status`
- Notice flow no longer reports an error

**Comment by SamChou19815** [comment]
I checked it on the latest Flow version, and they consistently error now.
