### ISSUE TITLE
Can't check for non-own instance properties

### ISSUE THREAD

**Issue by alexvision** [facebook/flow#8498]
In 0.129 this change was introduced: 
$Keys<...> will no longer include non-own instance properties, matching the behavior of Object.keys.

Is there any way to check for non-own instance properties that is currently implemented?

This is an example of what I would like to be doing: 
https://flow.org/try/#0C4TwDgpgBAggxsAlgewHZQLxQOQ21AHxwCF8jsBhMnAEWwG4AoRuAGwEMBnTqAMWWQBlYMgBO0AN6MoUTsHZI4UdghSpOALigSA2iqRot8A6gC6WgCQBpCCE4AefkJHiAfAF9M26TNhbsAGYC2AA0UAD04VAAcsjAUBAAHpAIEAAmPjLE-gBG7KKhEVGx8UkpwOmZUBS57ABeoVU0uYgBAYWRCckQqRky7kwyQcgAFACU3v0+eaLjk1Du0-VewKIArhBMi0A

**Comment by STRML** [comment]
Bumping this issue as it is still causing problems. A minor change in 0.129 makes certain `$Keys<T>` usage impossible.

**Comment by gkz** [comment]
We aren't changing this, the previous behaviour was a bug.

**Comment by STRML** [comment]
That may be, but there is no way now (that I know of) to get the type we need in the example.

**Comment by STRML** [comment]
See also https://github.com/facebook/flow/commit/293d6ff459cb63c1eb187d7baa3713ec219a21de#r43020023, which points out a new bug in the error message.

**Comment by gkz** [comment]
> See also [293d6ff#r43020023](https://github.com/facebook/flow/commit/293d6ff459cb63c1eb187d7baa3713ec219a21de#r43020023), which points out a new bug in the error message.

I think I fixed that already - check the latest version

**Comment by STRML** [comment]
Thanks, can confirm you did. Do you have any suggestion on how to type functions on the class in the example?
