### ISSUE TITLE
How can I debug how flow is getting the types coverage?

### ISSUE THREAD

**Issue by danielo515** [facebook/flow#8501]
Hello,
I have certain project where flow is not able to determine the proper types imported from other local files.
It is not giving me errors, but it is not checking them properly either.
The folder structure is like this (but with hundreds of more files):

```
./src
    ├ components 
    │   ├ SpringProvider 
    │    │    ├ SpringProvider.js 
    │    │    ├ SpringProvider.spec.js 
    │    │    ├ SpringProvider.stories.js 
    │    │    ├ index.js 
    │    │    ├ localeConfig.js 
    │    │    └ reducer.js 
    ├ hooks 
    │    ├ useClickAway.js 
    │    ├ useDimensions.js 
    │    ├ useLanguage.js 
    │    ├ useLocale.js 
    │    ├ useNumber.js 
    │    ├ usePushCard.js 
    │    └ useToggle.js 
    ├ index.js 
    ├ reactUtils 
    │    └ isSingleChildOfType.js 
    └ types.js 
```

The thing is that, the files at hooks are not properly typed. If I, for example, export a type from `components/SpringProvider` it does not have any effect there, flow infers them as `any`. 
How can I debug why this happens?
Is there any log that can help me determine what happens and why?

**Comment by dsainati1** [comment]
Are all the files in your project `flow`-typed? Do you have `// @flow` at the top of every file?

**Comment by danielo515** [comment]
Yes to both. The files are indeed being typed by flow, but flow tells me that the imported types are not specified

**Comment by dsainati1** [comment]
Hmm. It's hard to tell what is going on just from a description of the project structure. Can you possibly provide a small repository that demonstrates the issue?

**Comment by danielo515** [comment]
I tried several times to reproduce the issue, but it is very hard, and it seems to happen only on very big projects.
That's why I was looking for a way to debug it myself.

**Comment by danielo515** [comment]
I noticed that some of my cases were caused because I was missing `@flow` annotations in some intermediary files. Iike index where I just export everything and that kind

**Comment by dsainati1** [comment]
That would make sense. Flow needs all the files in its dependency graph to be typed in order to provide full coverage.
