### ISSUE TITLE
Type alias can behave differently from explicit type

### ISSUE THREAD

**Issue by murrayju** [facebook/flow#8508]
Flow version: 0.135.0

## Expected behavior
A type alias can be used interchangeably with the equivalent explicit type without changing type checking results.

e.g. given
```
type Simple = Complex<string>
```
Any subsequent type definitions could use `Simple` or `Complex<string>` interchangeably.

## Actual behavior
Using a type alias in place of the more explicit type can change the behavior of the type system.

* Link to Try-Flow or Github repo: [Try-Flow](https://flow.org/try/#0PQKhCgAJIZQSwLYAcA2BTSB3A9gJwNZwB2A5pGgB4CGy6kAZnLgM4AuANFgBZq4YJUkkAG5UUAVwxi+VACYBPSAGNsRVlWLNIrHpHxp5AOiiQAUuLaQLxMgBIAamMlbMcHdq5wXefFqpbKJDQlVjRZKBBgcHBWeSDIABUeAEEQuFUAWUFIAF5IAG8AHxNkgC4Cwu04tHKAcmTaziQqeRRsOXKicQQAI15IQoBfdhMAIXKiqqC60cbIZtb22XK2XBsB4ZMAYQnK2OnIWq3ajZGhgG5o-YxU1nSiLTyHJzRmAB4ktFv7rKQAPmiAAp8lMaocGk0Wm0OpAAOyQQblb6qZgASkuwNBMzmC2hy0O9Gw2BOiMgyIe6PAmOudWOCKRaRRlOAwEgtgAYm1MABRChBEJhbm4XB4KkgmngnFQpZ1HpyEkMu5My4stmc7A8vnBUKyIUi3BirGHWaQxYwgAM9LJjIpKtZHK5vP5Or1oup1VpUrN+NqhOJVvJaLtasdWoFuuFbvypMDzPt6s1zsFkYN7oOtQAIgrrUrbeBVQ6NU7tcn9YaJfVs7Hg4XEyWI2XMbiZQSiVWbUH8-HQ0mG1H5tKYfCYx3KV3IABaKfTmezufzheL6eQFnRUAQaAASSIHgwsleTDCymw+84On42Vk2FekCI2FYkD4snERFkVDUKEU+8YRAw59BkDvrIu56AYxhbg8oRyJwtgAPI9AAVr8cCQF4VjMEerDYMeyDiKEIH7swh7AdcDAiggIFEbQ-Skd+xBuPcERRDE1SwIgqBfDavy5BUJS7AO3qdN0fS4KcYz8c2MKrOsQwjNAOwVLJ4BDGurK-Fo-6kcw2E6FQD7-gA0gYqF+LI+7AcQWEgaIEhSBpugAAbXA58wikEuCxOAgR4PprFOkBYSBm8yR-Dxti8lQIRvHBiHIW8JRyZAbwGZw9h-ICKWQPYqK5KFkyGAV9hnh6kAGWJfx-Jc46fJAJDtCgkDYPQHhof5r6BR2AFobpD5uFgcAoA1Yhcuh2jYSQaC-rgel-roaAAI7iHANmTb58T0ORkBURxokqPu1VzWG6i5iZHh6eObXmUF8DUeSvyhTkj2JCkXGCOOox4SBfQjcwXAavZem7l+2F3g+fRcFQwizRgzA0GgLHxJ8d2CAATDxl0dbm7w3RxyP-FVqo1RDSBIIoSj+DebTYPgjX4OAKiQdorysPBCE8fkfEFEalamni5TDol4xcxWJoCXzrb+ps8kTNzdKbIMGKhGwrPlEjr1IJSgJKyziGqy9ua-CjY6quyGgoBp2Hk6wShcIBAEIF4AjW1w9MovpzOs6Mcjs5z4olTzYstrUcqyCSgsyyLXri76bYIolCl++mcsjAr461sW4auqm2uezCasG4IcYhkWR2lm6OeIV7+L5z8qNF+npd9tnHuVzCGOyNd7HoHjfzG6yOPoKJ2sAw+CEWA+hJKBYjU7v+NnOGR2AUf+AhIAjNwdmjTyOLZ7zt53t3qxVVVpmCAeSfiw6KvczBGxiidn6LF91H67ZY3f5b+3L18oh-BYJhnF0KZJxbT+uIFAwF6Bm0gM+P82FiA2TgMBC+n90wQkDjCYO8oAyb3rgAxuWcQG-WwOAyB0DYFjVQkQRByDBzhFPtiXmLZLQjnfngns9Ys6oLPscJhmDX44LYTWfBvZCETlASQiBDByGSEoQ7ZgRFSCgjFKwm+f9uwl1ESmbhdQsyCLUewzRnDgHiOIaQ6RA0YGyKsvIxRZAUEMMlPo3+hi6yZxMRI8xUDLF9HJhYP8rE0K2JsJwHon1NBQTIQNLQFCrKYBFEoi+yimx0JfrHVRLjhEcPcfqIhYCpHeIar4qg-iupaGCaQUJ4TIJoG9oUmJ1jsLxNUPYuhySQTPzhM4h4H81xgBMDAP6ShCCkE-JwawSiqAATEHAfwygIakBvP+cGkN0gGkgJEVSsA4aAS0IGFGVSHz+L8NMlAszmDjgAJokOUO+QC5sdK4EUHwVAkV1gORrpkVGLlXDuAcvvDsbwB6cQLv8FyQEtpoGho+V44DWBaBtu+CakBvoanXjmG+ABmMKO9nAfH1rXJAKNKpAgfnUdBnSr4YpRJizWZLjRRyDgIjJDxaX31lm-LFrjAFl1EqY-JUSGqxPgdQmZtDvQ6MlHwn0IdOU0u5QQjxZiCkyLgVQmhGD6H0tqE-VJkAWE-1ZQqrRjZtW8M1WkyWhrmBsrTiI4xuT+WSMFVYtVFSyDXBUda21-9slANNdzPRLKbXGodXgPJzqLFCsaZAd1mrJWVm6SGrJRicnhqdV46BxTSmkSCV4OxhyqFsFqYKhparmmJLaZ6lJgkJZyqNSmtx-r02eJVT44IJSMJlNjfmkJKLqnFrqWbMtlCK2tO9O0i1XTg1sqAA)

Sorry this example is a bit long, but my attempts to reduce it made the problem go away. The interesting bit for this ticket is at the bottom. There is the definition
```
type TheActionMap2 = ExpandedActions<SimpleActionMap>;
```
Followed by 2 sets of tests that I expect to be equivalent. The key difference being
```
type Actions2 = $Values<ExpandedActions<SimpleActionMap>>;
// vs
type Actions3 = $Values<TheActionMap2>;
```
The same set of tests with each of these produces a different set of type errors.

**Comment by SamChou19815** [comment]
All of them are correctly failing now
