### ISSUE TITLE
Property missing in ____ViewStyle_Internal

### ISSUE THREAD

**Issue by grit96** [facebook/flow#8509]
Flow version: 0.122.0

## Expected behavior

Object that conforms to `ViewStyleProp` should not show flow error.

## Actual behavior

```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ app/components/activity/app-update-activity.js:30:47

Cannot create View element because property color is missing in ____ViewStyle_Internal [1] but exists in object
literal [2] in array element of property style.

     app/components/activity/app-update-activity.js
      27│         <Text style={[styles.text, styles.pad, styles.divider]}>
      28│           {description}
      29│         </Text>
      30│         <View style={[styles.row, styles.pad, styles.divider]}>
      31│           <Button title='Ignore' onPress={() => {}} style={styles.button} />
      32│           <Button title='Update now' onPress={() => {}} style={styles.button} />
      33│         </View>

     app/components/activity/styles.js
 [2] 114│   divider: {
     115│     borderTopColor: Theme.lightGrey,
     116│     borderTopWidth: 1
     117│   },

     node_modules/react-native/Libraries/StyleSheet/StyleSheetTypes.js
 [1] 664│   $ReadOnly<$Shape<____ViewStyle_Internal>>,

```

* Link to Try-Flow or Github repo:

Cannot reproduce in [flow.org/try](https://flow.org/try/#0PQKhCgAIUhhB7ADgTwE4EsDmALALpACgGMBKSAMQEMiBTAI3ngGsAaSASQDsiA6SSzgBNI6XAGd+AM0noANukq4aYnlAjRIAFWzoJY+AFdUtSEXiCaIifNqcxNYQaE1UkXNksBZdpsg2adpaShkIinG4eapAAMuywAKIAcgDK8ZAyspbo4e6WqIz4guioNES48KjIkPCSEbqQ+kYmuCU0qtBRAAKSsvAA7g0t6GUAtL1ElLJdwagAtopqwODgAOQG9oMYZSsA3Mu4yIiWAIKc6PNKgonmlgC8m9mYe+AHR5CJiugAbjQIvagANUmBjuD04T2WNAAHogKvhXpY-hUgbIQZB7pwDLJZJAAD5gzB496fH5IwHAmjPaGw1Dww6I+D-Y6oVCUZAotEYrE4-EAEgASjRKIIAPKcWTIZms5AAHjJHJoAD49tS4W56ZAAArwbK4BXoyAAb1xUEgUIAXJBMbM6C4WKbkJbrbbUPbcQBfFUwtUIyDxQSYGhcezifX3Y2m8qIJ0GG1202ZSS4GNx12mjA4ZNW2Mu+2QSAMXDlWYp3PgD1eml0t4AEXOATE6HgnDD2exROdLiJYiG4KJp3Oigc1wsz1A6hgguo+A+uG+NBW1jZhnwYmQPZosysBco9mEzYomShDCh-FC9VhfRcDgL8HcUQP6BFyTPwlOgny6GEdCqAmqR3CRpjEsRB8gAK1KfAJmxG8AAMAE14EwShYPNKI8FwRAxHNYBgEwURsAMOgeDMWZgEkah6EYJhgGQJDKDUKJtCyWZEEyWYAlwT5H3CRDkO3MR5EzCVICKaRr04fBJHyLc+mwRQIhoKJyCPE8GiOIhRJoGROGUSARnSCpIGhShWMyNgr1MbB4A2WYKksew7HQOhMi0iisVwKIvgpFRIGSbITEMVxZGXAxCngIgJEoEpIEDXTWUudIZMU0x4FmDjJIkbI6jEKIMhoNg2KFDYmBoGhEH4AsMG01L0s4rSxCIDA6EeYzqGwSBQKQdUjnaCctA8DYuqOWl0D06LLEoBoiJDapaiCwZkEyCR3AUibUrsWMbx-FKQrosKokmTAKgIrcBGEShxLKFLYUbOdm1a86GnQAAvVqakgL4xr6FRFheDUAH0gYB6JQtwZIDkyAGuCUVBOEmA0BSFUVxVlCN83HSBYKKMQ2LZWCGhocQUpxvGql9D73HqUjYV0yT2nzdRGfzdh8D6ComD0c45GikTyix0m9oJ7LYGSZI2DoMLqlR6bECrSAVh6aEVlfBXOGbBcGY0BWlahFX6lyNzKA8rWQCWfNBbZAB+S0VnV3SVfxRWjxWe1TUx2C+i-dwCZDFaPEgL3BHcOactq2nONN01tdZwOOa52YedQPn4CxoOfbCOAxYlqXsqna7Z3nSB9ujmBIFmdZ8HWECdUy6pXBG2wuMDXz4lmKLQjvDxXCcUQopi9XVwMOW4QcU382SMrIAwrCcOACwfl6EaeDst7sUoHgKkwYAAhGABVZJ54isRgAAdXoYBRcP9OOpmcv7K0ri5F+-NoHNwPvewG3IDrDLG2bBUbsMZgCxh4LAeBfZE39pYMBmZQ5UwkDTDW9NS6lxZmzeOz1E4hWTuTVOsFYEQMzlfHO+A85CgLiSSwJdX5lwrj2SA1dOq12JkZRunFKAtz4G3Du+5cg9zOMTdag9ZZVjHmgvyU8Z7YVwgvGgS8XAr3gGvEKm9UDb13gfI+kUz4XyvsAQhUkjJ2RihYJ+sgX6M3foY7+v8GxNhbBSIBkAPaFmLMLaB2ZUyh16PhaCnV0BQnkStVONRJCzUNm4tKxkAyWBqBIhB4dkG4CjrQ9BcdUCcywUnFOWMomzGFuEEhBZc7hHzjOKhxdDASPoVXIaLCJBsJcE3ThyhuHt1Vl3LsvchEDzvKI0eghUnM0kTAoss9ZE0EXkgRRq85CqK3jvTg+9D6CGProugl8xbAHyRIu+JjLBmMoM-UO1kBiwXyQTS6khIJLn2ik0u798m2PrE5ABTjljAKZhoU+HgcgByKCUMoDjtywVkC0WCbBYIBEEB44yABHAw3xJj1X5rBDMEDx6-ICCTYokEQX1HRbgWQkKsYwrhTQRFyLMiSTcPgxMuBYLDI0NoeoPYlqWC4qVCQoFSgOACIFH4rhDZgu0oy1W6LwHivZctU278YUvL-g4wBnyXEgNFUmOFhtOyuA+r44YCNECBOCXSua4Sia7TFTEwMc0Ek6EQWlCOKDaESNjuzTJCccl4KxgywpWdxYlLIWUihFS5w-CqQYGpldGH1N1I0huzSOFcL9B0p6XSBF934H0oeI9aTiJdWk0Z09xkyPnlM+RMzUBKJURvRZmjVnrPPps-RDK9nGIfkck5H0zk+rFVcq6xM9orjlQmMVir7HvNRAVVVHsMXioNgHHVPikIGpxEaoJFjTVhIiQHOd1q4mSDtdTR1yTmVlzdZgxs2DebeslZmP1xTJZBsgOU4kYbqHVMLbUmNNc43106omySrTW6ps7vwxhgj+6WBEWIYeYihmoMLZPMZmFS1yIUVWuZ681EaOWVotZOim1bMPnOttrgDmP2OZu7t-QsZzv7Tcsodzh2PPTFK8dbzHFTuceONB2L-mHLxcCx8EgwUQqhT2aK86JCUqRd5Gl8J6V9qxX83FQL7rhEJbSElEmuK0gpVS+TqL8H0bPQNNlkNOWUG5Z1IF-LuBxKFSlDVjKoX0bYE9aFQhfaWcsW-U0knaQcf-lxkEPH1VRi1YunMXY9Urv8euk1-Nt0WsNlGfdtrC2JKQXTB5BaRkXo9dknBuTYKReIdnQNmdX2F3DTQkZ36mGwj-U04CQHk08M6eBnpUGrT9Ng7my4Zmi3SLnuhyt1b5m1vUUslZ2iT5Ef0VGMj99TFEyo402oPaytIAY7cvwYMR35ijMF5VHz3bqsTpwU+n8ouWCu+cWMH9g63yMtlk9uW2DZX1Ql41FjhuFayVer1prYJXZGDfB9lWn3VZDW+ou9XtaNdjXXVrLSOugb4d3CDmbhH9bg4M4byHi2obG+WjDk3sN1rww2wjejtng5vitijnb-usfzFdm7L3TuTrCzOy7lAoRc4zgu+7gvHuyU-oZYV9qkmfczj9w1f2-PfPPRgorwOSu3vmFCCHt2KsBph+Q6c8O6ufoa9GprDT-3sPa20lNvDqjdcg1m6D+PBv5sZhI4no3JnTOXlhhZM363zY2cR4AOu9cveZx29bz8jvl0F8Lr+lo7GcZVRdmAYPsgAAkaBSru+XbIEvp757gXfd7rFklffCIrtdyuAfq6B9zLXoPweGKh4b0pL64e1Y-ZGr9luUesITW15u9vOtpud7j7NAy80Ify9rH3Jayf+9mcoqbOHZv4cbfTw+7ey94Bj2t8xKv35Xbz+x1PryQsZ6+VjHXl-73bkNjrkvhjpdhxy5xGvfh4tK43RV1dSb09VbzRUjw7wN1IVhxNz7wjSjQYStxa1H3Rwn0xyd2xx61dz6xzXgyJykRXz9wrQDw3yp2Dxp1D0WwZ0FxGEMWP0OTjzZ1oXP0FyfzwB51C2nUz0kSLFajB2inwk4AJnkk8TEFMksG0kY3wF3EJl4L7AoQ6niULX4PUWyE0F2yhXmFUM4GiD7U0IEOyAACE7x3EPNQgVDBD+QC9x4RtCCy019MNSCg9cM5sCMFs98I8DDOB6DKN492dE9tCOC781Us8tDBDjCiw0oCZ3Usl5BSoH8vCRhLkDcbDl9SciCKdA9psXCd86dm1qDtCkiTC0ofDWcz9TQwijDijZggjzsvk+NVNAV8URMfVxMEjtD4hvNtxZNqVjN2jLDrCGicUmjhNNNRNtNSULDshOjYVujDMUVaVwCvDdDNUE9KjOAZjajuN+cYBJ45DCQpjOAc8ToXpmwuISVp4ZDDYxCOJjIB1+A9AiY5xwQJFCwOpDiVjxVPN1irD701ivDjiMBTigNZAti+duCPi+0MlYj0B4jDixgoSRYxZUiCD0j7DiD18a0t8Q83Cw99F1iESkxSjGDyiOdlix1r8lVecuD79DjfiiEYjrBYTLB4T6MUjvdUSJl0TMinDsjt9ad3D8j99EjSNC19lY9T9-jtD6TcAwSaSQihjwgRiNNQVwVUBJj1iIYpMDM5MFjFN+jshPimVFTRIhMVStNiUNSvCtT9M5jdSFM28vCZTjTmCKjrS9NZTKSJ1ODwtQivD1DEBojME4iWSCTyskTkgUSUMuTxsSCsTqdXDd8hTPDCjlsxT20T8NspTBCAy5TfSeDniDj1iAQXA5xoJhCriA4biJD7iZCQxCzbx7xlD1iAyrlzD1iIj3FszsgSzRpoI8ydiCy+DEBhQihwQKzRDxC7ipCHjZCGyFDMsRlYIRzBAxzMBWyoUVy1zOyojNzRzHgjSzDhBlz9zwRnSoyScYzycJssjsSKDcSqDD4tzHhiTJT-DnzwQByISPzMAdyCloSmS4SfyijIj-yIzx40iryHDKdnD+TKCPDgLdk0lxTMy-DXT8wfy-yvz6i0l+NTT1MCVRM1TJifyZidTejFj8EfzzyTTlTCK6NLS9zVzHgyK7SKL9STzmLwQjSE9SKhBsKQihy+xOK1zATXozjJg4UQy5zWo3jFztYRKDyoTPNqLBj0LOpTzMAxLgTziBKPYfyjSAK-BmSsZgLfV2S0lIK0Nry4zN8EzcjBTw8zKxU0EUKGC3z1KDKKSf4b8zttjvzNLnSjLpLFLwQRg2TwK0ErLV8MTHD4zyDEy8inLNLwqpVXKMz3Ksz3zAqr8fKqSfSdjaKzT6KxN1SmK1ybTpMEV7S+jQrMAeKiqCKWiiUdNTLNLKryKjNKK2quLMAaLPL2qPS9L1UfzWzgqTK6qRhwyilkSorOTrLoLbz7KBS8TtlgK0zmY3LfCmCrFTRRqkBhrdinjhzNLeyyzJLtxpL6zZKu55Ky46qxqVLNK-yXTdqMLTrSzV1Dq8kKgLBUBk8gyisQqGBUA-qo8RcZrIy5royFrYqYK+ScSkzw8QawamdkKMrtrSTbxQaXBk9v4dV8yLlfqXA-yAbxq4SUaXAQLixwbsBO8IL5qYqeT4qciVrHydlibUBqa0pab0ryMJSsr1LKbUBSbP58aYs0xM9GrmixjWiyqfqcbUAZiyb6geiuqOLhaZSAaVNhjirmqJioVhblb9dVb5iHS0VhbPjtb-CjahA8bSx4wITLaxUybGTjKKbObCTcBab6bobLzYbma7KEqHLVrD5havbeb0b+bUKdr-N8xnakx7avEywnbOatb9c3bgbPa50faLLmZoqMibzeS7zErHL9Fw6c60bNqMayiE9NapUk6CbCrcLGi9bZbSrJjhbKqVaZMzbaqE7cBraW7damr26DaFa-ru6Tbe6aruqibFb06XtXq47sbJ6PTG6JbCbhaAzXbgyJrw6oxc7IrLLGbC7bKyDWb4LkyD6kBI7q7o7Mq0K3rV6XAd6xaHbJbaTbpRAHE-UatKk2UW9opTUShMAsRgHH0DpC1y1KgqY+w2VUsTN5EqECYdoLB3JwU2B9AsZKA6B9BUQlBYIJFv6NNWp6hJg+g2QJAwJo0SgQp31TVDYRyShnUvdC12Bah9pA4BB9SSGQUpoiAdBZBHBGw+xcZSh0AZBNIdVNs-8-FJhiHldIA6HKl+ZM1mGf9ZCUpBG5BhB+Z5Jw1YJcH8GwoaAiHC0+HmwAdOHDBuHurLHwgBGhHhAVGGH+Z9AOI4HMA7UFJ6gRF1GJpJI2AaGGE1lOAVg6kHJfNP9VoUlIA94NhcgJFv9FjWh8CYa558J3AiISI0pyJKIGBmBaJ6JXyNtpZp5aNlybIf7mwCYxIblUAJBbRcArwcV-730JEnor5eLqmNNv4VhjHGRTHHYFZXH5xXZBzYJdY6xR6CYzBJJ8hN05JhgOo6LmxEFnGWHQ4BGJLsguxjobD0V+gCZjo9IGUQGpUoUzBURZghDYp4A9J0t+Z8kjyI1E9kBXjJoXJOVU4wHlAJA5IFJDZ003B2ZRJ4A+BAdAKWTdYRg1mhCJEIy2BoRaBEB4QAVtJjZwVQVrnYwhCLzfduSi6Wa4KHyPDYX4XSmn6V7pm27+n8g+gRmVgGXwqYH7AmXcXbmOWhnbnWWhV2XCbdZT5WRAyNoWhGQAWPBwMdHhGtmJhwg+gRWs0QgLokwuxcgPnC0dB0WJDO5agppdYxXjl4obCoX3aYWjwIcRXO9CB0GsWsx1ZFXKBEASACW7DYzMSg7L6yXkzYWnXEAqXY6zZTQhWRX+n-WmXHWRWmX-W+WXABXJmQm5xJBkAEBJJOIrkhI7ArJdGtnspX9jX8KZabDyAjITIzICoRBagZWPwcV1oeh+hWohVzrsRkAoUk3JHU2ziM3kmzjFmJAe0NX+As3PpProIJRTWQDzWsYO2U2Rh5mlBJIbWCA7WPJLRYXAtcBXWOSMmz7PWL7SWkb9FZ3kB53u3JJA2saT203F3PTo4iRnZoQRhN2Vh72nZYWYVX3X4H2m4XAv3X4nZcZKIkiiZWnwm32FYgPaARhooVX-38xAORzoPy1UYJmITJgsBOBWZNwxBM3MONnc2cV82A4mobIJB4WS2y2oRTIiovtq3Nm62YoG2vY+xm3V0JQoUMPMAsOlB25zGRkF3+2KmBgh2uPwhrIgSJLW3J3yaWSxORhRAcPl3V3wVLQewShcBBHt2kNT6iXz7YLEakr9F5PFP25L2E8xPsP25+mN2PSmWP2hAOXOI-2H31OiZBGmW6Bdx5E9m0PaSxPJ5ZBJA5m+2JXhPKoa3h38PM5DZSOxByO268wRl4AhUMA1znNLPePcP4EA4NH6YOAp2Qr5P7Agv+PtYIzbXMW13+Awp4BtORkC69P92DP7yj3tliv5FD10yH7MaLOs3AvJAbYIOBnav4OH3bOpMxv33LXP3hvf3UApvIOWh3PsBFuVgvOSvfPCaxOb2M2xWhOe0GWooR3iPLA4uEvR6kvtYUuXA0vWoRUdvz3xVKZcvAm8sGvdOPW4qvXD2jP2us2z302L3uvVtH6g335Huge73v3pun2X3huHPBA1v5u1u3PNPVvhuoOaAQOWmypwOYfIOkPsfYOnAkfCabvUBmOQuFmwue0a2tn1oOJdwjAbwnpLZkBPcFKKfmPLQdBVyAg5njZ7AJAvoaAfpTVbRTB5A5YbxlnXJYJufeg+g1PSPsQyuy4Jhq4RfvoQkCx7tioWfhBsgLAAILBJIRIXv88G43uJB5hspxcVd0lM6JrFfjmDdKuMGswvpGxvn6ul9PubLmuEbOAr7w9Xe+hzOJEFehUefPpdBnJMgCZmwRI3bHxnw+AxRIB3xPxBAPN2xRfxevZ2wiBpe7Urec3ZWAgE9w-+nveE+FwH2+ezemXGpFnZA-PBKuAe9YDKkpmjw6mHmJAREYiUpqzuHyZ5IyFwo9Jj6lzdY4Upol0EpsdVpHGCRXnRAALOmiAzBQb7vU4RU+IUJjK6BWRKhOn8BCWsnCJiJSJ8naBCmaI6JkJEMRk8K+-oQF-mE7oi4CaRB8B5gNmWLh9nqi6x6+nTc8GzHmR69noL0G8MNDhAOIEYajYmIa3kwgg+AyQVOAxELQpMoBIcD-lCEgT6kAATB-HbBcpOUXsZoFWSJ6zkcBAnEAbSi9gED5+WjfmAAEZhs7-NgfUAAAMbAYAVXlywCRXorPHfr9X35pxbsEA48pASeib96g2QMAd824GqZCBcKEYBwMEEkcmBZCIfhUHmCttYB4g3fmuSj6Q4JUHePgMcSvBCo6OikEoIuBwLGR1YBgHAOpEohXcy4Qgp1FAPbBiBsAGATgEwFNSZps812fXN8VzyH5GUZmXWAAHEGWbAXWMkCCHZBWAqsXWIYV3D1AR+1xKcjIVn40sjw4tVMEl0SEMsyhZYfMKkPSEhDqh8YWoUeByGNgxAjQ1wPiHU6PBfSaCY4OI2ugJQmw+3RkKPzEE5dLApPbSHs2EBFB8q2zPrBYD4D9CNI+AIYanHIZoJ7Yz7LiEIGijCBhopZKoMn1-DeQeY3zTOCUBNzwwGGT0ERN01f4aADImfRfjcA-ghwpos0G+AYliEPFVhyjbiCMJxDXFxhlvCDLNDmHek0EzwtfurAsDvCOonwi1Iaw27kMBhawwEYJzC4gi4BEwxYVkAEymB8g8XfgFCF0ASIq24IomNCMgAvD8RCIyqEz1gxMcnAoxP4ZBABH3QjKlZQwB4NfwG8WR3AFUkyJZ65RC0KUFEbkLFHMwYRlUOEZYBYG3wjwsUBlsAECHBDQhu4f4esKBGiFQRtQbVG8NO5EiyOpI8keKMkZUjPIaSAyCsI5E6jKBtvbIJ4VPCQjOMWUSSNgIkFOBrRz9LUZBH5DcQOhhNF6FwAsBEDdRgcHQIIzlycQEuuMPaOU3SwfR00jvd4IYMmAcc3mYTCJj+ixihjnARAvgAgGEFxjlGMKLsNQDMH78y+xQeuH9Ri4AoIoW0VJmVCwapx6GXYPAeR1ZADAKeEiIUMnDGi6pdIvkWCAWPDEEx5gVQSXtXEkBYhKRXDAxpNDOAXAHE8aUwJXBKJfpzACMXUC4Aoi0BJW14bMc2FzGUNFisuW0AYybBVpHhauWTilCvj5iFOhYgmIcNpBVADI3YhkVNBwSBhUAUfCcZ-3IE4gWGDYg8FGD4CsoQheIl6HCzbrTtRAi4YhiwlajSRokTDayLpDCD8x9orgGgBzy87Yg3WaJL7vDRLoh12a8E43tCGlw1IBa1LYNvmGAlQhgxkzeFr7A0iSMxonieFgjGY54jq4rgfcZT0og2FmIRsDyKCmyDdxRApKFFuVCMSuB8g-SeUVGJWagTLiPwCROgMsAbcbwkEkjkYBYb4BxgKKUiVyWf6TBDsd-XEkOjCgITR6kfQtJ0Dxi4AZgW4JsNKJXrwt+msklwMhIfZqkmW2mCZh6GVD7BAYwMTQKyDsCeSIYHKaGOmzhgIx7gSMYUGKAlAyh0YCpNJGVjiliBPJVyHfkpI7hZppQ8CQqZ5O4jhB4AdACCExm4TtRqgDUjkQMJ4nKA0ETDfICNAOARAFIRfHEJLxaACAiphg1np4lKhttVYhsPSaaiYSndup1UjMRpgz5tSmMDQayFiGEAiJJepEFqLpCGTxMNgnwx4K5GmnAB5pI5YoGghGitTGp73DoGkkkn5AuISgNwCtLmC1SJAJQKlDFE+G9hCQ2DWJilFGnxTDB7zPXmgmpAlB4uN4bKBYEwCtAJAK7GgJgDIBGRWQRQMaYQGxmusKAVHGjpkDQiL4s84M8aXMAIAABtQ0MozvBDgAAGrbAAAsAAViRkqx3QbAOmW9KHAAAtW2HwJ4AAB2AABxsyAAzAAE4xZ2MrmQAF0SA6vNBJJLEClQROX0tces3LH-TJoBIBoAf0n5gytZUM20DDJhBwy9wmcJGSjMq4Yy+ApbAidRwraky2GzMAqWNM8k0y6Z6ssXszIVjszOZkAd0ErPV7vwKZnk7+BlJRgSgpQbIGUBB2NAABqEaOiPnAf1+wq4ocFcBuAegk5uIZOXzKUBqcgZWcwcJcBHA0B85BPFOcXJoABzuhfYfEAOAuDDg857oAuUXIZlKB4Ipc4IYSBbnZzK5HcrufXMFkGyh5Fc9uRYBrkAcjQhcxqCikzlTy25uc2eZ3NrmLzoIDcleVn2Hkzzq5m8+eSnKXmZA+5ydLsKvJzlVy55CHBecnIpmdiA5S6a+SPI3ldyn5Q4C+a-P3nTz15R8gufe2-aPzCpnYt2d+wJ7Uzf5rcm+TcDYAwKD5AChWcAsgVvzD5V3ADsfPvmnyNZjcoGXfKJC4KxeF8puZgEIW4QtAIoGsCKEtCAt9BKUacAYGQEahN+1IW5FbCAWQLX4yci4BgAtCQAY5WUyUCyATmIL-5VcxUOXLXlVzMFCHbmaaEVBuh3QkU8ALxhZSDQQIvUxBH+FnHWz+YggZAPDETjjsqgcUFwEOC2nCh+gjScIAXzEBfZ5gLcQQdCFwDItNOfUKIIYVKBC9OUHgX8KYiMWmR2OZigIBYsuA6DCJUMzXkNAPEZiHM5Y5Gf83XGYD3pwwKIIEOsUDBBwNqXcLNGnEwCpozTWGOP1NTHRP8SAOcEYIAyU94ltATxRouUBaLK0c4caDFCfAvgTh+kT-JrmAbzihRSA+QP1IPDZ8dQufPMYbGpnQpMg3kDTOYxgAfiDgCsldusnsWWZhoCIFQHgFmCyAAAxPIimS1TtOwbVULSB6iWBgYAMNIVksSlQwYYLgeGDiHSlThY5aME0DhXzpQISYvUqxWsgGDXMKgaCNyfQ08kiAbI-hTJX8rJDfx5QHyD5RoD2J8SflkK2jCll9EaBgVigUFd5IhXyQ-lIoaQCGGjkvLhFOU95a-BvjsTv2NiD+klwilJd1Fny4mIbA-DdQUVfYpDqICqAEAK44KdAGxDGjfgJ+Z3RkBUGcGTBEA8kWMZJBIBAr3J2K8FepXZUihOVBwDodIrgUWAGVYAOasyoBTIq8VtGFyEYABFFB1gcqkFZDJxVKrDVfQQMWavaG0rywKiqkN6DOW+hLlAIb6LcpoDJTYYjyxGCStRhkrTQPAMNbyHiDUcygMoS5aDHuQ+q-VDyyYEotDXhrI104GNcDGuV-KE19y1KbIBTX5gw1PACNVGtwCZqgYsUr2YYNzUpTHlhancEQCYCHiaAXqn3nIC5W194+3zJlk3wCATN461AJgMjJVbQrLQsK7YvHU5pjq4Aoq8kJOpfoi1qiM6idXzinWK0ZiK6udSqnXV-VPiW6-4DusXUykD1yIOFYusqqnr51a6xdQGSvVHrNawodAOsHVXoKAFSXYWn+RmL2rn1jqy+Z0L-kyL4FpoT9dUU+I-qX1e82Be-OnS7qSa1RGUhBr-XiKgNWqkDZzT-KVUkNr6wDZqtg23qkA36p9ZBv-UaqYNH6zmgGXA3EbkNEtMjRgvQ2K0AyiGmjThug0Ma4NqAAMlhtY1QakFsixjWvQ5T9N8GX4JlmsiLAOBxNu4DwGT0E24136pGt9QJs42i1ucfGiRcBs43G11NSm3DeRvk2oAraimlDXhoo0L0G6Jmujcpq00Xr16Vm7xDZrQ2ca36um0zQZvzBIBqAnajTahvw0HLZlDidiRFNdXywPVwMUtpJHPhSpE1+a9EKaCdjqxvp7fBLQrAYDCN-2TsDgXwL4GZaFYJAnLXlpWCSzCtqWlYCzNK33yVgbMyrQ+wABstWp2CLMa0KwxZLWlYNLMK2hafQ0Uyta4trX+q0pgioNdlNynFrS1Gaz1d6ssyxb61SXAFagBhXbrz1wQSSFQGwTIBv4ZCioWcX8hwCqVhkSSD6v6ZJajBTLUQBhyIADrDtg9WId-EuWRbbtMWvNY8p22SQgQGAHhsSuRjCL45soTHkYNkDztnWYgNboyEEAypse1oUHcN3kBnAwq0OtblxElg4IRgiO4bggNGjNhJgaO2MKDqS4NqlAUIcGLaoJXmpPSw2n7cGtyn5gb4Tq6lbEPp14gVFSXInSTqyXYamdbO7Nf0HvXnrMgkm1AMkE5WfkmdcOmgGwQp1N1jsri44Fm36bGxygTLBlKFKlROcUpTLE9tdrZ1y7MOZ1L6rbEV3wAmWUYTztUXV2wxrtAUVEBYEe2ahNK38QppkAECs7XFNYUoBUFqnRA9mQ3AnnbA1hrcphQ4h2LDr2ZTUghvIjHn7qD3i7jKukcPfkHcGrdXdxO93bv1qnHbbYompHg+zWRERMg4mkwlJtz0yapNKe3AGns90aY+dC6tnVWohlzATtAen9s6wu3yA4BTLODM0m87K7+g3ehNrTowCFkZmMtBXaN2CktBQpxKcKS6shBurqwFy4GOwCcU0ABtSap5ZTsynU7yV429NdGqm1i819+ahtXDLEGeAbg-TBdsa25ZCoW+y3dHhbpc5OwSgRwRQNrt1A16b1FPPaDOu23OrVFpyhfZAEuU1gBAAEwwIJGQDL7eURAXQKvpm0vahthoVNSWr33lrLlmgfrQgbrXJqkuRc5QGfov22wr92QG-U-qW4acPOP7ZzgtwfYv6hQuAa7Y-I-1zqlth689cnO-1shf9QMpLsWvACegopbwBIWEq2A+rNQvUmUMnM0BSLbgqWzENiFS1fAxlqWzQKloogWIlIVWvLUItRh-aZQIh+KMMHEOSGZDAB+fecuAPAxQD4IFwBAYlDQGgUcBkw0gFm1DbDDgUogC4cQCJz8wvIa5UcArUAwbD4B9YA4dYhOH7AR+ubeAEimAHLDB+voN4bcMb6PDYhyzBIaQC+HN9rymUP4fkiBHEj0R5NSmriMWHwtfW4nckcQOpHRDxhjI5IdNC6Hsp+R51jQCCOYGqj2BwbQWtKOVgetbwS5cvtaTVGcDtRow14YaNZGmjI22UK0cKNL6V9xR3o-aHMNhbetVy3zCkYNDIH8wyc6mdNP7mPAFZloeY+0ZANgG7DYRqAxEYkZRHuj6+htcWvtCCHlgbx+ZgwgkDhh0w-QS0LsdfgBdOuWe+-R50wW0tR6tsBltdvzDXsnuxBmgyrFNAKL3qggP4-ex-L67oIlobLZgp-LaUpOloArUiaS5FAvof1NE9+23pIAyQtsJJcgGhMEbEAyebE0iYEPPBwAHx1cL5ktBFGpjiAbY-cGpkBYeAyQ4UyuSS4qBSTX4FwOAAVl7AgAA)

One of the differences is that my style object is created with `StyleSheet.create()`.

**Comment by ashwinibm** [comment]
+1 have the same issue.

**Comment by FanchenBao** [comment]
The key part of the error message is

> color is missing in ____ViewStyle_Internal

This is `____ViewStyle_Internal`

>```
>export type ____ViewStyle_Internal = $ReadOnly<{|
>  ...$Exact<____LayoutStyle_Internal>,
>  ...$Exact<____ShadowStyle_Internal>,
>  ...$Exact<____TransformStyle_Internal>,
>  backfaceVisibility?: 'visible' | 'hidden',
>  backgroundColor?: ColorValue,
>  borderColor?: ColorValue,
>  borderBottomColor?: ColorValue,
>  borderEndColor?: ColorValue,
>  borderLeftColor?: ColorValue,
>  borderRightColor?: ColorValue,
>  borderStartColor?: ColorValue,
>  borderTopColor?: ColorValue,
>  borderRadius?: number | AnimatedNode,
>  borderBottomEndRadius?: number | AnimatedNode,
>  borderBottomLeftRadius?: number | AnimatedNode,
>  borderBottomRightRadius?: number | AnimatedNode,
>  borderBottomStartRadius?: number | AnimatedNode,
>  borderTopEndRadius?: number | AnimatedNode,
>  borderTopLeftRadius?: number | AnimatedNode,
>  borderTopRightRadius?: number | AnimatedNode,
>  borderTopStartRadius?: number | AnimatedNode,
>  borderStyle?: 'solid' | 'dotted' | 'dashed',
>  borderWidth?: number | AnimatedNode,
>  borderBottomWidth?: number | AnimatedNode,
>  borderEndWidth?: number | AnimatedNode,
>  borderLeftWidth?: number | AnimatedNode,
>  borderRightWidth?: number | AnimatedNode,
>  borderStartWidth?: number | AnimatedNode,
>  borderTopWidth?: number | AnimatedNode,
>  opacity?: number | AnimatedNode,
>  elevation?: number,
>|}>;
>```

Indeed, `color` is not in it. `color` is in `____TextStyle_Internal`. So you can try something like this and see if `flow` is satisfied.

```javascript
import type {
  ViewStyleProp,
  TextStyleProp,
} from 'react-native/Libraries/StyleSheet/StyleSheet';

const styles: {[string]: ViewStyleProp | TextStyleProp} = StyleSheet.create({
  foo: {
    color: 'white'
  }
});
```

**Comment by SamChou19815** [comment]
It's a react-native typing issue. From the issue itself, it doesn't seem to the case that Flow is wrong
