### ISSUE TITLE
  for (const val of [1,2,3])  fails

### ISSUE THREAD

**Issue by bitfrost** [facebook/flow#851]
for (const val of [1,2,3]) {
     console.log(val);
  }

src/SchemaToFlow.js:42:10,14: Unexpected token const

This cannot be suppressed with a suppress_comment

http://eslint.org/docs/rules/prefer-const.html and babel seem to suggest the above is valid/correct es6

**Comment by samwgoldman** [comment]
This has been fixed since #831. You can build the master branch if you need this today, or you can wait until we cut another release. Thanks!
