### ISSUE TITLE
React Component defaultProps "Hoisting" Bug

### ISSUE THREAD

**Issue by ernestostifano** [facebook/flow#8512]
Flow version: **0.136.0**

*Note: React components default props Flow implementation is still under discussion (#6644). However, this new issue is to report a new unexpected/undocumented/questionable change in current behavior.*

## Expected behavior
As per [documentation](https://flow.org/en/docs/react/components/#toc-using-default-props) and like in previous versions, the expected behavior is for Flow to detect optional props by looking at component's `defaultProps` static property.

## Actual behavior
Flow fails to detect props as optional when `defaultProps` is defined before the component is declared (hoisted function/class declarations). Error shows **ONLY** when the component is consumed in a different file (using ES6 Named Import/Export syntax).

* Link to Try-Flow or Github repo: N/A. See examples below.

### Examples:

<details>

**<summary>This Works</summary>**

```js
/** @flow */

import React from 'react';

type Props = {
    propA: string,
    propB: number,
    propC: boolean
};

function Works(props: Props): React$Element<'div'> {
    return <div {...props} />;
}

// DECLARED AFTER COMPONENT.
Works.defaultProps = {
    propA: '',
    propB: 0,
    propC: false
};

export {Works};
```

```js
/** @flow */

import React from 'react';
import {Works} from './works.js';

function App(): React$Element<typeof Works> {
    return <Works />; // NO ERRORS HERE.
}

export {App};
```

</details>

<details>

**<summary>This Does Not Work</summary>**

```js
/** @flow */

import React from 'react';

type Props = {
    propA: string,
    propB: number,
    propC: boolean
};

// DECLARED BEFORE COMPONENT!
DoesNotWork.defaultProps = {
    propA: '',
    propB: 0,
    propC: false
};

function DoesNotWork(props: Props): React$Element<'div'> {
    return <div {...props} />;
}

export {DoesNotWork};
```

```js
/** @flow */

import React from 'react';
import {DoesNotWork} from './does-not-work.js';

function App(): React$Element<typeof DoesNotWork> {
    return <DoesNotWork />; // MISSING PROPS ERRORS HERE.
}

export {App};
```

</details>

**Comment by SamChou19815** [comment]
Now both works since Flow 0.187.0.
