### ISSUE TITLE
Wrong Annotation on WeakMap (React's ComponentType)

### ISSUE THREAD

**Issue by ernestostifano** [facebook/flow#8517]
Flow version: **v0.137.0**

## Expected behavior
`WeakMap` to accept React's `ComponentType<any>` as a valid key type.

## Actual behavior
Flow complains about `ComponentType<any>` not being compatible with `object` type. JS Classes and Functions are perfectly valid keys for `WeakMap`. 

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBLAtgBzgJwBcxCBPHAUzAG8BhOXOAOwqcIBVyKBfMKfBmADk+CgEMAxoSEBudBOYBnYllIB1cQGsAsmJxgAvGBZINYnXoA89RizadKlsU1IA+ADTGArlgBGFfFcACgBKGSA

**Comment by SamChou19815** [comment]
This is intentional to future proof React typing so that we don't assume the exact representation of React component. This is an unfortunate side effect. We recommend suppression in this case.
