### ISSUE TITLE
`new someInstance.constructor(...)` regression

### ISSUE THREAD

**Issue by popham** [facebook/flow#852]
The following fails:

```js
class T {
  n: number;
  constructor(n: number) {
    this.n = n;
  }
}

var t = new T(1);
var tp: T = new t.constructor(19);

/*
someFile.js:2:6,11: property `n`
Property not found in
someFile.js:3:3,5:3: new object

Found 1 error
*/
```

I mentioned it back in https://github.com/facebook/flow/pull/657, and I closed it as fixed.  If I remove the `T` annotation on `tp`, then Flow yields no errors.  This may be how I fooled into believing that it was fixed.  Or maybe it was fixed and has regressed.

**Comment by samwgoldman** [comment]
@popham I just tried this on master and I don't get the same error. Can you confirm this is still an issue?

**Comment by popham** [comment]
It's kinda fixed by a PR.
