### ISSUE TITLE
Worker interrupted with signal: sigkill

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#8523]
Flow version: 0.136.0

## Expected behavior

Flow should work without throwing sigkill messages.

## Actual behavior

When I run flow-bin (`flow check`) on CircleCI, some times I get the following error:

```
$ /home/circleci/repo/frontend/node_modules/.bin/flow check
Worker interrupted with signal: sigkill
Subprocess(360): fail 2Unhandled exception: Worker_failed (process_id = 360): (Worker_quit WEXITED 2)
Raised at file "map.ml", line 135, characters 10-25
Called from file "src/unix/lwt_engine.ml", line 302, characters 8-36
```

This started happening after I migrated the repository to use Yarn Workspaces, but I already tried to set `flow-bin` in the `no-hoist` list without seeing any improvement.

**Comment by kmkr** [comment]
[This comment](https://github.com/facebook/flow/issues/8058#issuecomment-527202246) helped us, may help you too.

**Comment by SamChou19815** [comment]
This is likely fixed a long time ago.
