### ISSUE TITLE
Is there a tool to automaticly convert type annotations into the comment-based syntax?

### ISSUE THREAD

**Issue by hexagonrecursion** [facebook/flow#8524]
## Proposal

It would be useful to have a tool that can automatically convert flow annotations to the comment-based syntax. Maybe back too.

## Use case

[semgrep](https://github.com/returntocorp/semgrep/) is a search-and-replace tool for multiple programming languages including js. It currently is not capable of parsing the flow type annotations https://github.com/returntocorp/semgrep/issues/838. One possible workaround to be able to use both tools is to use the comment-based syntax. An automated tool that can convert an entire codebase from one syntax to another would be handy.

If the tool was able to convert back too, maybe semgrep could use it under the hood to replace code while preserving the type annotations.

**Comment by noppa** [comment]
[Babel plugin transform-flow-comments](https://babeljs.io/docs/en/babel-plugin-transform-flow-comments/) seems to be exactly what you want, at least of one way transform.

**Comment by SamChou19815** [comment]
We are unlikely to build one, but you can try yourself.
