### ISSUE TITLE
Unsoundly loses one branch when another is uninitialized, at top of loop

### ISSUE THREAD

**Issue by gnprice** [facebook/flow#8526]
Flow version: v0.137.0 (and older versions on flow.org/try, including at least v0.37.0 which is the oldest)

## Expected behavior
Should report an error in the following code, which fails at runtime with `TypeError`:
```js
let thing;
for (const x of [0, 1]) {
  if (thing) {
    thing.nonsense(); // boom! but no error
  }
  thing = { x: 1 };
}
```

## Actual behavior
No error is reported.

On inspection with an IDE, `flow type-at-pos`, or `$Flow$DebugPrint`, Flow is apparently seeing the variable's type where it appears at the top of the loop as simply `void`, when it should be `void | {| x: number |}`. That'd be enough to cause this issue.

A key element of the repro case is that on entering the loop, the variable is uninitialized. If instead the variable is initialized with `undefined` -- which should have the exact same behavior at runtime -- then Flow correctly reports an error:
```js
let other = undefined;
for (const x of [0, 1]) {
  if (other) {
    other.nonsense(); // error, correctly
  }
  other = { x: 1 };
}
```
and inspection shows it correctly sees the variable's type as `void | {| x: number |}`.

* Link to Try-Flow: [here](https://flow.org/try/#0CYUwxgNghgTiAEA3W8BmED2B3AIiARgK4DmACjAJYB2ALgFzwAkAYplo3kWZbQNwBQ-CCBrwaAC2rEBqDDHgAKMBioBnUQA94GVPADaABgA08AIwBdAJTwA3v3ho2nEuWo0FEqZYEOKuj5JUxNZ2Dg6eQQB0VCqqIGogCt7wAPQp8PgYGAC2AIQZhKIx8CAwMHL28AC+lRHE8AC8tvAaDKbVAjVCItoSpY3whFSgqNQgwDJyispqmtq6hiYWIZXo2M7cbgoYfTDelX6KO+KlK2G9JzDRsfFxSbyp6aXlMCbKZeA0EACelTUOx36TRsLTaHX4NSAA)

**Comment by gnprice** [comment]
Here's another bit of unsoundness involving uninitialized variables which is sort of an inverse to this one; not sure if it's the same underlying issue.

If instead of using, and then initializing, the variable in a loop body, we do the same thing in a function expression's body (perhaps because we're expressing the same loop using `Array.prototype.forEach`)... then instead of forgetting that the variable might be already initialized, Flow forgets that it might still *not* yet be initialized:
```js
let thing;
[0].forEach(() => {
  thing.f(); // boom! but no error
  thing = { f: () => {} };
})
```

Inspection shows that Flow sees the variable's type as the type that the code further down would initialize it to.

Here again, if the variable is explicitly initialized to `undefined`, Flow sees both possibilities and correctly reports an error:
```js
let other = undefined;
[0].forEach(() => {
  other.f(); // error, correctly
  other = { f: () => {} };
})
```

And [here's a Try-Flow link](https://flow.org/try/#0CYUwxgNghgTiAEA3W8BmED2B3AIiARgK4DmACjAJYB2ALgFzwAkAYplo3kWZbQNwBQ-CCBrwaAC2rEBAbQAMAXQB0qDDACiUMOIAUOgJTwAvAD54Ab37w0bTiXLUaOiVP0DrLqsRUHe8APT+8PgYGAC2AITBhKJUGPAgMDBqVmKSXsYWaAwGxmbmAL7wBQIF+oLCohgSiZmEVKCo1CDAsooqapraeoamFqno2HbcjjrV4oluqeOJPm4BQYnJMAA08GBqcGA0EACe0zUwmebZ8Ll9hcWl5UA) for these.

**Comment by SamChou19815** [comment]
This is now fixed.
