### ISSUE TITLE
Cannot use Dispatch as a type

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#8534]
Flow version: 0.133.0

## Expected behavior

Using `Dispatch<A>` should work.

## Actual behavior

![Screen Shot 2020-11-15 at 2 44 38 PM](https://user-images.githubusercontent.com/151600/99195031-3d58dc00-2751-11eb-95c0-dc450674fdec.png)

**Comment by Brianzchen** [comment]
Can you provide a try flow? https://flow.org/try/

**Comment by volkanunsal** [comment]
I can't really replicate it on try flow, but it definitely happens in my environment. I upgraded from v104.

**Comment by Brianzchen** [comment]
Without a code snippet it's hard to help. But it looks like you're providing a variable that's not a type and is instead a variable, which flow decided to disallow to prevent further bugs. I think it's from [0.132.0](https://github.com/facebook/flow/releases/tag/v0.132.0) 

Here's the commit https://github.com/facebook/flow/commit/282b2e5b1f1525c0eb2b41719ec2ff89d3c21cd6

**Comment by SamChou19815** [comment]
Not enough info to repro
