### ISSUE TITLE
Modules with %checks refinement throw signature-verification-failure

### ISSUE THREAD

**Issue by volkanunsal** [facebook/flow#8535]
Flow version: 0.138.0

## Expected behavior

`%checks` refinement should work.

## Actual behavior

![Screen Shot 2020-11-15 at 3 52 49 PM](https://user-images.githubusercontent.com/151600/99196535-ef48d600-275a-11eb-85a9-c1b135d8b00d.png)

**Comment by gkz** [comment]
Try 
```
export default function hasOwnProperty(o: Object, k: string): boolean %checks {
  ...
}
```
