### ISSUE TITLE
Error when no error expected (incompatible-cast)

### ISSUE THREAD

**Issue by nifgraup** [facebook/flow#8536]
```
/* @flow */

function foo() {
  let x: ?string;
  let y: ?string;
  for (let i = 0; i < 10; i++) {
    if (!x || !y) continue;
// No error if only x is checked
//    if (!x) continue;
    (x: string);
  }
}
```

Flow version:
All on https://flow.org/try

## Expected behavior
No error
## Actual behavior
```
10:     (x: string);
         ^ Cannot cast `x` to string because possibly uninitialized variable [1] is incompatible with string [2]. [incompatible-cast]
References:
4:   let x: ?string;
         ^ [1]
10:     (x: string);
            ^ [2]
```

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKASjAG9UwwYBTfMADwC4wB+AZ3wAnQtgDmAbkbM2YAJ48Bw0ZOnkhYSq3aEwAXjAAGCWF0AeMAEZjpgNS3aDJk0JRNAQg5gAPt7Du5WlwSImxMFilgYDAAOTgwFiEhOA1XMBIYOU5TfjBcAAsWXABrFgATVCjnUzdKTyCQ0XCpaspuMEERcWoWsABfVAGgA

**Comment by SamChou19815** [comment]
Fixed in Flow 0.185.0
