### ISSUE TITLE
Flow 0.138 upgrade: Could not locate flowlib files

### ISSUE THREAD

**Issue by pascalduez** [facebook/flow#8539]
Flow version: `0.138.0`

## Expected behavior

No error

## Actual behavior

`/node_modules/.bin/flow check src`

--> `Could not locate flowlib files`

## Link to Try-Flow or Github repo

https://github.com/pascalduez/react-module-boilerplate

## Env

Ubuntu 18.04.5 LTS
yarn 1.22.5
Node 15.0.1

## Other

Listing the content of `/tmp/flow` there's qui an amount of `flowlib_[hash]`.
As well as user specific one (so I can see other users stuff...)
`zShomezSfoozSrepositorieszSbar.lock` (.lock, .log, .log.old, .monitor_log.old, .recheck_stats, .sock, .pids, etc.)

**Comment by mroch** [comment]
i'm able to repro this if `/tmp/flow/flowlib_[hash]` is owned by a different user. for example:

```
rm -rf /tmp/flow/flowlib_*
sudo flow check
flow check
```

short term fix is to delete `/tmp/flow` to clear out the files owned by someone else. medium term workaround is to set `FLOW_TEMP_DIR` to a per-user scratch directory, perhaps `~/.cache/flow`. we'll fix this, though.
