### ISSUE TITLE
Function argument types

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#854]
Right now flow does not let you capture function arguments type so that their types can be enforced elsewhere. The most basic use case I can think of is `setTimeout` which is currently [encoded as follows](https://github.com/facebook/flow/blob/70dfcfe09b8ebf4ca1cbb660a89ce7d5eb3319c6/lib/core.js#L550)

```js
declare function setTimeout(callback: any, ms?: number, ...args: Array<any>): number;
```

Note that `setTimeout` may pass any number and type of arguments to the callback rather then respecting it's type signature.

I think most reasonable solution would be to allow "rest" arguments be captured as a polymorphic tuple type:

```js
declare function setTimeout <Args> (callback: (...args:Args) => any,
                                    ms?: number,
                                    ...args: Args): number;

```

In fact I was surprised this did not worked out of the box (see #811) and currently such code produces `Failure("Did not expect BoundT")` errors.

Also note that `.call` and `.apply` many other functional utils do suffer from the limitations.

**Comment by samwgoldman** [comment]
This seems like the same issue as #811. How is it different?

**Comment by Gozala** [comment]
@samwgoldman It is pretty similar bot exactly the same as there I want to constraint some arguments with a specific type and use that same type as property on record type. In this case t's just matter of expressing that A function has same arguments as B functions + callback and ms. I can imagine that this could be fixed without necessarily resolving #811 although proper fix would address both.

I don't mind if you want to close #811 as being duplicate of this one and if fix here does not address it I'll just reopen.

**Comment by Gozala** [comment]
Oddly enough I managed to find a workaround for this that works. I don't really have time to simplify it, neither I think it really solves the problem, but in case someone is blocked just like I am it may be useful to them:

```us
const thunk$0 = (key:string, view:(..._:any) => Child):ThunkNode => thunk(key, view)

const thunk$1 = <a> (key:string, view:(a:a, ..._:any) => Child, a:a):ThunkNode =>
  thunk$$(key, view, a)

const thunk$2 = <a, b> (key:string,
                        view:(a:a, b:b, ..._:any) => Child,
                        a:a, b:b):ThunkNode =>
  thunk$$(key, view, a, b)

const thunk$3 = <a, b, c> (key:string,
                           view:(a:a, b:b, c:c, ..._:any) => Child,
                           a:a, b:b, c:c):ThunkNode =>
  thunk$$(key, view, a, b, c)

const thunk$4 = <a, b, c, d> (key:string,
                              view:(a:a, b:b, c:c, d:d, ..._:any) => Child,
                              a:a, b:b, c:c, d:d):ThunkNode =>
  thunk$$(key, view, a, b, c, d)

const thunk$5 = <a, b, c, d, e> (key:string,
                                 view:(a:a, b:b, c:c, d:d, e:e, ..._:any) => Child,
                                 a:a, b:b, c:c, d:d, e:e):ThunkNode =>
  thunk$$(key, view, a, b, c, d, e)

const thunk$6 = <a, b, c, d, e, f> (key:string,
                                 view:(a:a, b:b, c:c, d:d, e:e, f:f, ..._:any) => Child,
                                 a:a, b:b, c:c, d:d, e:e, f:f):ThunkNode =>
  thunk$$(key, view, a, b, c, d, e, f)

const thunk$7 = <a, b, c, d, e, f, g> (key:string,
                                 view:(a:a, b:b, c:c, d:d, e:e, f:f, g:g, ..._:any) => Child,
                                 a:a, b:b, c:c, d:d, e:e, f:f, g:g):ThunkNode =>
  thunk$$(key, view, a, b, c, d, e, f, g)

const thunk$8 = <a, b, c, d, e, f, g, h> (key:string,
                                 view:(a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h, ..._:any) => Child,
                                 a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h):ThunkNode =>
  thunk$$(key, view, a, b, c, d, e, f, g, h)

const thunk$9 = <a, b, c, d, e, f, g, h, i> (key:string,
                                 view:(a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h, i:i, ..._:any) => Child,
                                 a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h, i:i):ThunkNode =>
  thunk$$(key, view, a, b, c, d, e, f, g, h, i)

const thunk$10 = <a, b, c, d, e, f, g, h, i, j> (key:string,
                                 view:(a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h, i:i, j:j, ..._:any) => Child,
                                 a:a, b:b, c:c, d:d, e:e, f:f, g:g, h:h, i:i, j:j):ThunkNode =>
  thunk$$(key, view, a, b, c, d, e, f, g, h, i, j)

type $thunk
  = typeof(thunk$0)
  | typeof(thunk$1)
  | typeof(thunk$2)
  | typeof(thunk$3)
  | typeof(thunk$4)
  | typeof(thunk$5)
  | typeof(thunk$6)
  | typeof(thunk$7)
  | typeof(thunk$8)
  | typeof(thunk$9)
  | typeof(thunk$10)

// thunk$$ is not really useful it's just there to make flow happily type check all the variations of `thunk$n`
const thunk$$:$thunk = (key, view, ...args) =>
  ({$$typeof: "ThunkNode", key, value: view(...args)})

// What we really care about is `thunk` and more specifically that it's args are validated against args of the `view`.
export const thunk:$thunk = (key, view, ...args) =>
  new ThunkNodeType(key, view, args)
```

**Comment by Gozala** [comment]
P.S.: I also noticed that if I adde `thunk$11`, `thunk$12` to the union type flow start to become super slow eventually finishing correctly. With `thunk$20` it was taking up to 5mins on my machine :)

**Comment by Gozala** [comment]
Now I just wish I could generalize it somehow to be able to reuse it

**Comment by samwgoldman** [comment]
I'm currently working on some stuff that will subsume this issue. I have added a note to ensure the `setTimeout` use case is covered. Thanks for the issue. I'm going to track this separately.

**Comment by unscriptable** [comment]
I'm trying to do something somewhat similar for some AOP functions.  Example:

```js
// A generic function, parameterized by its arguments and return types:
type F<A,T> = (...args:A) => T;

// A function that will be called with the same arguments as another function, but we don't care about the return value (so we use mixed):
type BeforeAdvice<A> = (...args:A) => mixed;

//type alias for the `before` function below.
type Before<A,T> = (f:F<A,T>, advice:BeforeAdvice<A>) => T;

// A function that serves as a proxy to another function, insert a side-effect before the function runs:
// IOW: Call advice before f, with the same arguments.
// Advice result is ignored.
export const before:Before = (f, advice) => function (...args) {
    advice.apply(this, args); // ignore advice's return value
    return f.apply(this, args);
};
```

I get the error: 

> 0: 
>      ^ Failure("Did not expect BoundT")

Is this what you're working on @samwgoldman ?

**Comment by amilajack** [comment]
What is the current method of declaring function types?

**Comment by jedwards1211** [comment]
@Gozala the flow-typed defs for `reselect` use that hacky workaround for a similar situation...
We basically need flow to infer a tuple type parameter so that we can `$TupleMap` it.

**Comment by suchipi** [comment]
Why was this closed? This is still an issue.

**Comment by jedwards1211** [comment]
Agreed...I also wish ECMAScript allowed putting rest arguments before the end of the list, so that we could type things like `reselect` something like this:

```js
declare export function createSelector<Args, Inputs, Output>(
  ...baseSelectors: $TupleMap<Inputs, V => (...args: Args) => V>,
  finalSelector: (...inputs: Inputs) => Output
);
```
