### ISSUE TITLE
Use simple class field initializers to infer the type of the field and accept it as a well formed export

### ISSUE THREAD

**Issue by noppa** [facebook/flow#8541]
## Proposal
```javascript
export class Foo {
    greeting = 'Hello'
    greet = (name: string): string => `${this.greeting} ${name}`
}
```
Flow should consider the type of this class to be
```javascript
class Foo {
    greeting: string
    greet: (name: string) => string
}
```
without additional explicit types, and it sould be enough to qualify for well_formed_exports and types_first.

## Use case
We have quite a bit of React component classes that have callback methods declared as arrow functions in class fields instead of class prototype methods, and I believe our codebase is not alone in this, as arrow functions bind this to the class and are then usable as callback functions to onClick handlers, etc.

In well_formed_exports/types_first, however, Flow would have us write the above code example as
```javascript
export class Foo {
    greeting: string = ''
    greet: string => string = name => `${this.greeting} ${name}`
}
```
This is, in my opinion, noisier, less readable, and overall just needlessly different from the original code. Even worse, the codemod to auto-transition to well_formed_exports would rewrite the original to
```javascript
export default class Foo {
  greeting: string = 'Hello';
  greet: ((name: string) => string) = (name: string): string => `${this.greeting} ${name}`
}
```
_ugh_. 
As far as I can see, these pain points in transitioning to types_first would just disappear if the type of a class field would be "locked" to be the value of its initializer when there is one and the initializer is simple enough to infer without needing to rely on types of other files .

The two downsides that I can see with this approach seem small enough to me that the change would still be a net-positive.

1. Flow would still probably not be able to infer the field type when the initializer value is something more complex, like the result of a function call.  
-> That's ok, you can just require explicit types in those cases, limiting the inference to only work with primitive literals and functions would still be a huge win.
2. Currently, you can reassign values of different types to the class fields inside the same file and Flow's inference automatically expands the inferred type to include all the different assignments.
```javascript
// Totally valid, as long as we don't export Bar
class Bar {
  greet = (name: string): string => `Hello ${name}`

  changeGreet() {
    this.greet = (id: number): string => `Hello user #${id}`
  }
}
```
This would no longer be possible. I would argue that this is not only a very rare use-case and a minor problem, but also that preventing later assignments to different type than what's in the initializer (when there is no explicit type that allows it) would be a good feature, as doing so is more often than not a mistake or at least a code smell.

**Comment by SamChou19815** [comment]
Fixed in 0.228.0
