### ISSUE TITLE
Issue with await and Promise

### ISSUE THREAD

**Issue by andidev** [facebook/flow#8543]
The use case for the example may not be the best because it is simplified to see the issue

```js
/* @flow */
// why is this fine (should be an error)
async function getValueWrapper(): Promise<{| field: string |}> {
    const subscription = await getValue();
    return subscription;
}
async function getValue(): Promise<{| differentField: string |}> {
    return Promise.resolve({differentField: 'value'});
}

// and this results in an error
async function getValueWrapper2(): Promise<{| field: string |}> {
    const subscription = await getValue2();
    const b = {
        field: subscription.differentField,
    }
    return subscription;
}
async function getValue2(): Promise<{| differentField: string |}> {
    return Promise.resolve({differentField: 'value'});
}
```

Flow version:
0.138.0

Live Example
[corrected live example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoYwwIBYE8wCWAzmAC7bFhQEB2ApmABRHZwCuMAJmAEYMCGNMHQBOIuCICUqfkVw0AxlTaLSBOEIDmdUgDV+MNnQDqI-gAdzoxpIBcYAAriAtsToAeAN4AfKgTpc9kSkIrSaYN4AvgB8YJ6oYIlgChrBYERsPEQKoeZqGmAAvGD8CPwEpGDaegZGNgDcCUkiOmwiQhlZOQR56jSNkTJyisqqfVU6+oZ0NvZOcK5EHj5gnARQUKJ0NKQAYv6B6SFhETFxTYktpG1C84t0AHQtRHAwAG4znmsbWzv7AZx7AByN61OhAyKSAaodCYQTcciUZ4cUgkWglISicQiIbyJRQFQKfJaSZg0wWKwiABMs0cLjcXl81ABQWONHCUVi8SSyVSlU62VyxKKJTKFQmNWmNKhF15NDSPBF3J5SWZhwF3V6Gge302LT+B04ABpZYMeVcbulMoKesTobI8aMieNqlMjNK5vSlozVus9ds9obWaF2acubKLe06Qs3E86C93p9db9AyywCCwRCZZEgA)

[old incorrect live example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoYwwIBYE8wCWAzmAC7bFhQEB2ApmABRHZwCuMAJmAEYMCGNMHQBOIuCICUqfkVw0AxlTaLSBOEIDmdUgDV+MNnQDqI-gAdzoxpIBcYAAriAtsToAeAN4AfKgTpc9kSkIrSaYN4AvgB8YJ6oYIlgChrBYERsPEQKoeZqGmAAvGD8CPwEpGDaegZGNgDcCUkiOmwiQhlZOQR56jSNkTJyisqqfVU6+oZ0NvZOcK5EHj5gnARQUKJ0NKQAYv6B6SFhETFxTYktpG1C84t0AHQtRHAwAG4znmsbWzv7AZx7AByN61OhAyKSAaodCYQTcciUZ4cUgkWglISicQiIbyJRQFQKfJaSZg0wWKwiABMs0cLjcXl81ABQWONHCUVi8SSyVSlU62VyxKKJTKFQmNWmNKhF15NDSPBF3J5SWZhwF3V6Gge302LT+B04ABpZYMeVcbulMoKesTobI8aMieNqlMjNK5vSlozVus9ds9obWaF2acubKLe06Qs3E86C93p9db9AyywCCwRCZZEgA)

**Comment by STRML** [comment]
The type error is poorly located and poorly written, but there is a real type error there. You're returning `subscription` from `getValueWrapper2()` when you should be returning `b`.

[Fixed Example](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoYwwIBYE8wCWAzmAC7bFhQEB2ApmABRHZwCuMAJmAEYMCGNMHQBOIuCICUqfkVw0AxlTaLSBOEIDmdUgDV+MNnQDqI-gAdzoxpIBcYAAriAtsToAeAN4AfKgTpc9kSkIrSaYN4AvgB8YJ6oYIlgChrBYERsPEQKoeZqGmAAvGD8CPwEpGDaegZGNgDcCUkiOmwiQhlZOQR56jSNkTJyisqqfVU6+oZ0NvZOcK5EHj5gnARQUKJ0NKQAYv6B6SFhETFxTYktpG1C84t0AHQtRHAwAG4znmsbWzv7AZx7AByN61OhAyKSAaodCYQTcciUZ4cUgkWglISicQiIbyJRQFQKfJaSZg0wWKwiABMs0cLjcXl81ABQWONHCUVi8SSyVSlU62VyxKKJTKFQmNWmNKhF15NDSPBF3J5SWZhwF3V6Gge302LT+B04ABpZYMeVcbrxobI8aMieNqlMjNK5vSlozVus9ds9obWaF2acubKLe06Qs3E86C93p9db9fSywCCwRCZZEgA)

**Comment by andidev** [comment]
Oh sorry you are right. The Live example was incorrect. Added the correct one to avoid confusion.

**Comment by andidev** [comment]
Closing this an reopening a new issue for case 1

**Comment by gnprice** [comment]
The first half of this example (where there's no error) is indeed a bug.

One notable feature of this bug is that it's dependent on the order of the definitions: if you define `getValue` first and then `getValueWrapper`, you get an error in `getValueWrapper` as you should.

It looks like this may be the same issue as #8761 -- see some variations that do and don't reproduce the issue, in my comment there.
