### ISSUE TITLE
Cannot spread objects with indexer property and different value types - Flow shows [prop-missing] error

### ISSUE THREAD

**Issue by DmitryGonchar** [facebook/flow#8544]
Flow version: 0.138.0 (latest)

## Expected behavior

When I spread two objects with properties of different types into one - it should be allowed, I think.

## Actual behavior

Flow shows `[prop-missing]` error, at least when object types have indexer property

Seems to be an indexer issue, as spread works if property key is hardcoded:
https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKAzA9jgXFAHYCuAtgEYQBOANGigL4DcaaokUAQgsuprgLFyVOhigUAhtUIBnYNQCWRAOb0mrduGgBhXnBTdNAYxxF5USYVSWKxwgca8k4zACJJdt9ex5CARihGNGC0U3NgCWtDAA8QAC9CHiZnVyg3OPjvZF8hf1oJaUI3AAsIABtynDcgkJMzCxjoqABqAG15JVUAXUI9FMQkKAA6UckC0eGKIKgAelmoAHkAaQBCIA

## Link to Try-Flow or Github repo:

https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFKAzA9jgXFAHYCuAtgEYQBOANGigL4DcaaokUAQgsuprgLFyVOhigUAhtUIBnYNQCWRAOb0mrduGgBhXnBTdWmNAGMcReVEmFUUANrylqgLqEDjXknGYARJIpTX1tsPEIARgAGKEY0WLMLKwpbQ0cFZRU3bigmLx8oXwAPEAAvYORQoSjaCWlCAHIACwgAGxacepi4tnNLYChClIcnDKy9XMQkADoZyRqZqYoWIA

**Comment by SamChou19815** [comment]
No longer shows the error.
