### ISSUE TITLE
flow-remove-types no longer correctly removes class properties with variance sigils

### ISSUE THREAD

**Issue by isker** [facebook/flow#8549]
Good: everything before and including 2.119.1
```bash
$ yarn global add flow-remove-types@2.119.1 > /dev/null
$ flow-remove-types --version
v2.119.1%
$ flow-remove-types <<< '// @flow
class Foo {
  +bar: number;
}'
//
class Foo {

}
```
Bad: everything after 2.119.1
```bash
$ yarn global add flow-remove-types@2.120.1 > /dev/null
$ flow-remove-types --version
v2.120.1%
$ flow-remove-types <<< '// @flow
class Foo {
  +bar: number;
}'
//
class Foo {
  +bar        ;
}
```
Haven't tested the babel preset.

**Comment by mroch** [comment]
IIRC, I fixed a bug because the meaning of an uninitialized vs missing class property changed in the TC39 proposal since we implemented it. it's now supposed to leave the prop and just erase the type. but yeah, if it's leaving the variance sigil that's a bug. thanks!

**Comment by isker** [comment]
That's this https://github.com/facebook/flow/commit/5f4b44e991d84cf08d44834629a9fbb09a4edbf8 then.
