### ISSUE TITLE
Error with array of Intersected Objects

### ISSUE THREAD

**Issue by adhesivewombat** [facebook/flow#8550]
Flow version: 0.139.0

## Expected behavior
When creating a new flow object type using an intersection, I would expect this type to behave the same way whether or not it is in an array.

## Actual behavior
```
type A = {cool: string};
type B = A & {neat: string};

const foo: B = {cool: 'wow', neat: 'wowee'};
const bar: B[] = [foo];

const test = (a: A) => {};
const testArray = (a: A[]) => {};

test(foo);            // no error
testArray(bar);   // error
```
Error: Cannot call `testArray` with `bar` bound to `a` because property `neat` is missing in `A` [1] but exists in object type [2] in array element. [prop-missing]

* Link to Try-Flow:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4DGccMAXGAM4YBOAlgHYDmAvgNyZcBAEKkiYAGQUOeAIYYGzdt37pqHZmCg0GoslRr0wAcgSJjAGjAz5DU4jx5jq9ZoBGslroDaAXTHe2nC+AqiuGGAYeJpkABSyDIQAlKQAfBQucBoRUcyELCyyWGLxiX4pJOnkqpjRGLFBSQK5GPmFWLEeLE1AA

**Comment by SamChou19815** [comment]
The error message now explains why this is an error
