### ISSUE TITLE
incompatible-call error with a specific combination of intersection types and type parameters

### ISSUE THREAD

**Issue by xinxinw1** [facebook/flow#8558]
Flow version: 0.140.0

Here is the code involved (I've reduced it to this from a bigger example involving Jest):
```js
// @flow

type OrigType = { testFn(): void };
type SelfType<T> = T;
type UpdateType<T> = {||} & SelfType<T>;

declare var testType: UpdateType<UpdateType<OrigType>>;

// type-at-pos correctly says t has type () => void
const t = testType.testFn;
// but it somehow can't be called??
testType.testFn();
```

## Expected behavior

There should not be an error calling `testType.testFn` when the type of `testType.testFn` is already known to be a function with no arguments.

It should work the same way as these working variations of the broken version:
```js
// only one use of UpdateType<T>
declare var testTypeWorking1: UpdateType<OrigType>;
testTypeWorking1.testFn();

// not using SelfType<T>
type UpdateTypeWorking2<T> = {||} & T;
declare var testTypeWorking2: UpdateTypeWorking2<UpdateTypeWorking2<OrigType>>;
testTypeWorking2.testFn();

// not using intersections
// (this fails to trigger an error for unknown functions)
type UpdateTypeWorking3<T> = SelfType<T>;
declare var testTypeWorking3: UpdateTypeWorking3<UpdateTypeWorking3<OrigType>>;
testTypeWorking3.testFn();

// intersecting SelfType<T> twice??
// (this fails to trigger an error for unknown functions)
type UpdateTypeWorking4<T> = {||} & SelfType<T> & SelfType<T>;
declare var testTypeWorking4: UpdateTypeWorking4<UpdateTypeWorking4<OrigType>>;
testTypeWorking4.testFn();

// declaring separate outer and inner update types
type UpdateTypeOuter<T> = {||} & SelfType<T>;
type UpdateTypeInner<T> = {||} & SelfType<T>;
declare var testTypeWorking5: UpdateTypeOuter<UpdateTypeInner<OrigType>>;
testTypeWorking5.testFn();
```

## Actual behavior

```
$ flow --show-all-branches
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/modules/test-type.js:12:10

Cannot call testType.testFn because: [incompatible-call]
 • Either property testFn is missing in object type [1].
 • Or property testFn is missing in object type [1].
 • Or cannot instantiate UpdateType because property testFn is missing in object type [1] but exists in OrigType [2].

 [1]  5│ type UpdateType<T> = {||} & SelfType<T>;
      6│
 [2]  7│ declare var testType: UpdateType<UpdateType<OrigType>>;
      8│
      9│ // type-at-pos correctly says t has type () => void
     10│ const t = testType.testFn;
     11│ // but it somehow can't be called??
     12│ testType.testFn();
     13│
```

All the code is included in the Try Flow link below:

* Link to Try-Flow or Github repo: https://flow.org/try/#0PTAEAEDMBsHsHcBQiAuBPADgU1AeQE4CWA5gCqY4C8oA3qClgM4oBiAdgBQCUAXKAG6xCAE1ABfANyoKoAMpZokctgA8pAHyhqpKemygAqhmEBDBsqxrN1GgB9bY0ADI5CpRStTEwrAGNoJvg4-IH0TCgWfEam5h7RZlgWKgQkFurqXiD0FAC0ZjkYsIygvrD4Qb4o0GigjCZoxSigABYmjTLcWpqCIoilbMz0WmHMFgB0DMzsUlkARgCuTYRNjLAAtljNCCUmbADkTbM4vibQ0FjCAPyXqOHjk6ycXJlgOW85tes48GUA1oRsYgCQKEMyEWADUCwSD0Zo4EyzWD8LDILIQ6pQtg4eaMHDQwzGBJJDTePwBILA-AjCIUADqfwBxAAjFFCbFVCkyBQMrdRnSGYCmRNwuxuC9QGxYE0cYzXIpieppPp4uysPT8P9AQAmKzDOwOZygHSk-yBYKhB4WdWa4ha1kxRL8jWMnUqx3Ya0u5JELnYdK6O5Om1a4VTJ7iyXSxiygEMfC4yrggZKnBuq0C4gAZl11Hk8o8GikPlNFJCVMtQcZmftRMrgOzabrWe9qW5PIrHozmdDjzFqLAsaw8b8KFlefcqg09HghF8WGuKYJDvTzsBABYc7R7I4XOOFYa9wWecXyeby4HO6viGua6rPeuVI3LzaN5y0u2L2qM2ue6Lnv3QBPEFAVqLAMECBIoUWIdQF2UQASxKl5jZHA9CYRcnywXBoPwTd9R3OUJ0sQsMJQiwAEk2EQvDtwPNwFSLMkzUpakVxtABWW93SwnDHzIihKOot82wDPln0Zdjf3DRAgA

**Comment by SamChou19815** [comment]
The issue has been fixed a while ago
