### ISSUE TITLE
some incompatible instantiation errors

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#856]
I keep running into following error, which I believe is invalid given that no constraints on polymorphic type has being provided yet:

```js

/* @flow */


type Step <model, action> = (state:model, message:action) => model
type Config <model, action> = {
  step: Step<model, action>;
  init: model;
  actions: Array<action>;
}

const run = <model, action>(config:Config<model, action>):void => {
  var state = config.step(config.init, {type: 'Nothing'})
}
```

I would expect that `action` type restrictions should be derived from provided `step` function or `actions` array.

**Comment by samwgoldman** [comment]
If I understand what you're trying to say, then you would also hope that this much smaller example would be valid?

```javascript
function test<T>(f: (x: T) => void) {
  f(0);
}
```

**Comment by Gozala** [comment]
@samwgoldman I think that example does captures the issue indeed. Or it could be that I just don't understand how to express what I'm aiming for and error produces by flow does not make it any clear what am I doing wrong.

**Comment by samwgoldman** [comment]
So, I'm confident that this error is expected and correct. The idea with generics is that their representation is unknown. This is crucial for parametricity—given a function `<T>(x: T) => T`, I know that is the identity function. If the implementation of that function could return any value, that my ability to prove things about the code based on the type is gone. Your original issue says that "no constraints on polymorphic type has being provided" but I would argue that the ultimate constraint has been provided—the representation is abstract.
