### ISSUE TITLE
This code makes the try flow REPL to blow up

### ISSUE THREAD

**Issue by danielo515** [facebook/flow#8560]
The following valid code makes the REPL to fail:

```js
import React from 'react'
import type { Node, Element, ChildrenArray } from 'react'

type ItemType = Element<typeof ListItem | typeof ListHeader>

type Props = {
  children: ChildrenArray<ItemType>,
}

function List({ children }: Props) {
  return <div>{children}</div>
}

type ItemProps = {
  children: Node,
  onClick?: () => void,
}

function ListItem({ children, onClick }: ItemProps) {
  return <div onClick={onClick}>{children}</div>
}

type HeaderProps = {
  children: Node,
}

function ListHeader({ children }: HeaderProps) {
  return <div>{children}</div>
}

const Row = ({ left, right }: { left: string, right: Node }): Node => {
  return (
    <ListItem>
      {left}
      <span>{right}</span>
    </ListItem>
  )
}

const x = () => (
  <List>
    <Row left="gender" right="${gender}" />
    <Row left="birthDate" right="xxx" />
    <Row left="Number" right="xxx" />
    <Row left="sendEnrollmentLetter" right="stuff" />
  </List>
)
```

Flow version:

## Expected behavior
To show the type errors detected

## Actual behavior
Nothing happens, but if you check the developer console you can see that several exceptions are raised.

[Link to the example
](https://flow.org/try/#0PTACDMBsHsHcCgCWBbADtATgFwAQCUBTAQwGNdwNpkcByDYsmpNTXLAT1QJwG8cA5aABMCAGhwBRSAWQEAdlnEBhABaJIQ+nICCGDEXY4AvjgpVa9UlibwOXHAEksMgCqduAXknTZCgDx2BNDgOAAyiADOWE4yOAA+OIHBYZFYABLEIhgAfPC27jgACpSoEThePPA4OCRqGloAXDiq6pryuvrsfjHIblzZovBGeeAArnJkiNByKVEAFHy1rVrGTcXQpQCUvFU49FijGDN+QogAbtk8S-XyRn7ApxdDeYGOzsjrpeU71ddtck1BCJBtVpkpIIgSABrAD8TTm2w82RwZ2giCEg2G8DGEywUxm4SiPQWNTq-3EYIh0NWbxknwi20q1X2h2OjxwlMhUI8PE50KMlz+WjuD3OuSxrwyRCy9O+TNJy3kgOEYme2PGk2ms3SmQIGBJQvkNKlMpKDJ+ewIByOOBOYquZOF90e4ryJGmUXwcG+JOk4EUe0QAHMVLgjE0+H6sE0ohhEHIg+I4yHowIVcZNsqROVkfKWTa5rtqn5CdF3rlqpXeFHhlXixFUEQ5Jdk6GRQ2mxXK-dSz0u5s1e65J6AB4+xHIwvF0td4t4b1RjwAIiD8iyS8DKeXABIeKu5FkjBvgLPbfPYDhF0uAEaIbAqAAiRGcG9bWGXI8-x9PfnPl4I-rLnIiD8KMyDXnqr7BqGH5fjgJ5FmeC4Ae+S4RGuEhyJQkCQL4WChFazgYFBW5oQc4DgN+uw9qkuQDkAA)

**Comment by firecoder1** [comment]
It works for me though?

**Comment by danielo515** [comment]
Probably they updated it? I think the previous last version was 0.141.0 and now they are on the 142?

**Comment by firecoder1** [comment]
I suppose so
