### ISSUE TITLE
Cannot cast an object of inexact type to a type with added optional prop

### ISSUE THREAD

**Issue by Hypnosphi** [facebook/flow#8564]
Flow version: 0.42.0

## Expected behavior
No error, as `bar` is optional

## Actual behavior
Cannot cast `foo` to `Bar` because property `bar` is missing in `Foo` [1] but exists in `Bar` [2]. [prop-missing]

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN5QkBcYAzhgE4CWAdgOYA0YAdAIC+mXAQBCAQ2bkqNOPSZsuvAEZSA-ApYce-IegAmeAMYwpBAG5Swc+sTjoAFLbCTmASlRA

```js
/* @flow */

type Foo = {foo: string, ...}
type Bar = {foo: string, bar?: string, ...}

declare var foo: Foo

(foo: Bar)
```

**Comment by gkz** [comment]
A valid value for `{foo: string, ...}` is `{foo: 'hello', bar: 23}` (the `...` allows any additional properties). Such a value is not a valid `Bar`, so the error is correct. On the other hand, the opposite is correct (`Bar` is a `Foo`): https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgBiccYAvGAN5QkBcYAzhgE4CWAdgOYA0YAdAIC+Abky4CAIQCGzclRpx6TNl14AjGQH4lLDj35DRqACZ4AxjBkEAbjLAbm9acyMAKB-WJwAlKKA
