### ISSUE TITLE
Flow 0.143.0 fails to start on Windows 10

### ISSUE THREAD

**Issue by CrOrc** [facebook/flow#8574]
Flow version: 0.143.0

## Expected behavior
On windows 10 flow should start and report errors
## Actual behavior
Flow fails to start with exit code 3221225781 and no messages at all.

**Comment by mroch** [comment]
ouch, sorry about this. 0.143 contains a new dependency on C++, which is likely the culprit here.

to help me debug, can you see if installing the C++ runtime from Microsoft fixes the issue? https://aka.ms/vs/16/release/vc_redist.x64.exe

**Comment by mroch** [comment]
never mind, it doesn't help.
