### ISSUE TITLE
$Shape does not work in cases with $Diff

### ISSUE THREAD

**Issue by andrejs-sisojevs** [facebook/flow#8581]
Flow version: 0.143.1

## Expected behavior

`$Shape<$Diff<A, B>>` allows subset of fields from `$Diff<A, B>`

## Actual behavior

`$Shape<$Diff<A, B>>` does not recognise any fields from `$Diff<A, B>`

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAaQ1LAF4wBvVMNsASwBMBGALjABnQvg4A7AOYBuVu24AmAcNGSZAXxmZcBYmQpgAgg2q0wAMmay2AOls1SAGitgAxnDFQOEgQHkARgBWGC6E6prYeEQk5JQAQsZGFizsYLbWBk4pwgCGhBhKIuLSzjl5ALIYgoLZEhgA-AUqxRroETrR+rH2MJWCxgAkACIcUFAAPLEOJqQAfOHaUW5iwmBYAl20PVUpO4xMQoS5+WAA5NnnJ1OlGBVVNcdnglyXru6e3sxqYC1ti+4rpAE-QAygALbIUCYzHbsPYHI4CM4XK6Hcq9e6I7JPE7fGS-YhLFYALyBYIhGAm3V60Lh10xyPhaLutUx2NxqCAA

```
/* @flow */

export type Key = {
    id1: string;
    id2: string;
};

export type A = Key & {
    ...Key,
    config: Object;
};

export type B = A & {
    ...A,
    state: string;
    stateMessage?: string;
};

export type BKeyless = $Diff<B, Key>;

export const x: BKeyless         = { state: 'aaa', stateMessage: 'asd', config: {} };
export const y: $Shape<B>        = { state: 'aaa', stateMessage: 'asd' };
export const z: $Shape<BKeyless> = { state: 'aaa', stateMessage: 'asd' }; // !!! FAILURE
```

**Comment by noppa** [comment]
The error seems to be related to the way your union types are defined, e.g. `Key & {...Key`.
If you instead define them as 
```javascript
export type Key = {
    id1: string;
    id2: string;
};

export type A = {
    ...Key,
    config: Object;
};

export type B = {
    ...A,
    state: string;
    stateMessage?: string;
};
```
The error goes away.

[Playground](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAaQ1LAF4wBvVMNsASwBMBGALjABnQvg4A7AOYBuVu24AmAcNGSZAXxmZcBYmQpgAgg2ay2AOgs1SAGlNgAxnDFQOEgQHkARgCsM9wuqa2HhEJOSUAELGLOxgFmYGtrHCAIaEGEoi4tJ2qekAshiCgikSGAD8mSo5GujBOmH6EVYwRYLGACQAIhxQUAA8EdbUtAB8QdqhjmLCYFgCzbStxbGrjExChGkZYADkKQe7w3kYhcWlO-uCXEcOTi5uzGpgtfVTTrOkAh0AygAWKQog1Gq3Y6022wE+0Oxy2BTaFyhKWuuxeMjexGmswAXt9-oCMIMWm0QeCTkiYRD4ecykiUWjUEA)

**Comment by gkz** [comment]
See above comment (best solution), but also solved by using `$Partial`: 
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBTAHgBzgJwBcxCBPHDMAaQ1LAF4wBvVMNsASwBMBGALjABnQvg4A7AOYBuVu24AmAcNGSZAXxmZcBYmQpgAgg2q0wAMmay2AOls1SAGitgAxnDFQOEgQHkARgBWGC6E6prYeEQk5JQAQsZGFizsYLbWBk4pwgCGhBhKIuLSzjl5ALIYgoLZEhgA-AUqxRroETrR+rH2MJWCxgAkACIcUFAAPLEOJqQAfOHaUW5iwmBYAl20PVUpO4xMQoS5+WAA5NnnJ1OlGBVVNcdnglyXru6e3sxqYC1ti+4rpAE-QACtkiBxsjAJjMduw9gcjgIzhcrodyr17kjsk8Tt8ZL9iEsVgAvIGg8GQibdXow+HXLEohHou61LE4vGoIA

https://flow.org/en/docs/types/utilities/#toc-partial
