### ISSUE TITLE
Way to restrict generic types of two components that should share the same concrete type at use place

### ISSUE THREAD

**Issue by danielo515** [facebook/flow#8582]
## Proposal
I have two components that work in tandem (parent child relationship) and they must share generic types. So when you instantiate the parent with one specific type, all the child components must be restricted to take only that type on their generic.

## Use case

I want this to fail because I'm restricting the generic value to number, so the child should only accept number on this context

```js
<Parent onChange={console.log} value={5}>
    <Child value="5"/>
</Parent>
```

Someone at stack-overflow proposed some syntax that does not parse properly, but at least express what I would like to achieve:

```
children: ChildrenArray<Element<ComponentType<ChildProps<T>>>>
```

Here is a snippet of one failed attempt:

```js
//@flow
import type { ChildrenArray, Element } from 'react'
import React, { Children, type Node } from 'react'

type ParentProps<T> = {
  onChange: (value: T) => void,
  value: T,
  children: ChildrenArray<Element<typeof Child>>,
}

export function Parent<T>({
  children,
  value,
  onChange,
}: ParentProps<T>) {
  const childComponents = Children.map(children, (child) => 
        React.cloneElement(child, {
          onSet: () => {
            onChange(child.props.value)
          },
        })
    )
    return <div>{childComponents}</div>
}

type ChildProps<T> = {
  children?: Node,
  value: T,
  onSet?: () => void,
}

const Child = <T>({children, onSet}: ChildProps<T>) => {
  return <button onClick={onSet}>{children}</button>
}

<Parent onChange={console.log} value={5}><Child value="5"/></Parent>
```
And [here is the stack-overflow question](https://stackoverflow.com/questions/66008906/how-to-sync-a-generic-type-between-a-parent-and-child-component-in-flow?noredirect=1#comment116709746_66008906) where I asked about how to do this.

**Comment by SamChou19815** [comment]
We do not intend to support these kind of use cases that inspect jsx internals
