### ISSUE TITLE
Cannotbuild a typed interface for this module: createFragmentComponent

### ISSUE THREAD

**Issue by simkessy** [facebook/flow#8583]
Flow version: 0.143.1

## Expected behavior: 

No type error

## Actual behavior: 

GraphQLTaggedNode
Cannot build a typed interface for this module. You should annotate the exports of this module with types. Cannot determine the type of this call expression. Please provide an annotation, e.g., by adding a type cast around this expression.Flow(signature-verification-failure)

```
 // @flow
    import { type Node } from 'react';
    import { createFragmentContainer, graphql } from 'react-relay';
    import type { MyComponent } from './__generated__/MyComponent.graphql';
    
    const RequestTitle = (props: {| request: MyComponent |}): Node => {
    
      return (
        <Box color="white" display="flex" direction="row" alignItems="center"></Box>
      );
    };
    
    export default createFragmentContainer(RequestTitle, {
      request: graphql`
        fragment MyComponent on TakedownRequest {
          id
          title
          primaryType
        }
      `,
    });

```

**Comment by gkz** [comment]
This is due to Types First: https://medium.com/flow-type/types-first-the-only-supported-mode-in-flow-jan-2021-3c4cb14d7b6c
```
import type {RelayFragmentContainer} from 'RelayModern';
...
export default (createFragmentContainer(RequestTitle, ...):  RelayFragmentContainer<typeof RequestTitle>);
```

**Comment by simkessy** [comment]
I see. Can the docs be updated, I would have never have just figured this out and this medium put didn't show up when I was googling the error.
