### ISSUE TITLE
Miss parser option `tokens` in flow_parser.js

### ISSUE THREAD

**Issue by fisker** [facebook/flow#8594]
We use [`tokens: true` in Prettier](https://github.com/prettier/prettier/blob/24a3673876b2e65b692e42748a2499c8ed07f6e5/src/language-js/parser-flow.js#L15), can we document this option?

**Comment by Brianzchen** [comment]
Should be added to here, https://github.com/facebook/flow/tree/master/packages/flow-parser#options
