### ISSUE TITLE
Does Flow Support Enums ?

### ISSUE THREAD

**Issue by ammanvedi** [facebook/flow#8597]
I can see there is discussion about enum support in 

https://github.com/facebook/flow/issues/627
https://github.com/facebook/flow/issues/7837

and babel has added something about this in release notes

https://babeljs.io/blog/2021/02/22/7.13.0#new-flow-features-12193httpsgithubcombabelbabelpull12193-12234httpsgithubcombabelbabelpull12234

and further this seems to cause no errors

https://flow.org/try/#0KYOwrgtgBAGlDeAoKKoEEoF4oCIDOAhngCZ46IC+iiAxgPYh4AuUAZllABTABcsAlFgB8CalUStOMAHRp+1IA

So i am wondering if enums are supported because i cant find any docs about it and open discussions seems to have concerns from some members about this feature yet it seems to work

Thanks !

**Comment by lyleunderwood** [comment]
https://github.com/facebook/flow/commit/a044a71b1d5b284dcce0c9fe1a4d070072c816ab
https://github.com/facebook/flow/commit/d503ff4d93593a04c070f049e07a5fe9cd4ebe11

> This diffs moves the existing Flow Enums Babel transform, as defined and used in WWW, to its own package. We copy over the code and tests.
> 
> In the future, when we open-source Flow Enums (announce, and move the docs to flow.org), I'll update and expand the README with more information.

:thinking:

**Comment by gkz** [comment]
This is an experimental feature that is not ready an open-source announcement. I'll comment on this issue when I do make an announcement.

**Comment by gkz** [comment]
@ammanvedi @lyleunderwood:
https://medium.com/flow-type/introducing-flow-enums-16d4239b3180
https://flow.org/en/docs/enums/

**Comment by ammanvedi** [comment]
> @ammanvedi @lyleunderwood:
> https://medium.com/flow-type/introducing-flow-enums-16d4239b3180
> https://flow.org/en/docs/enums/

thank you !
