### ISSUE TITLE
Unexpected incompatible-type error within loop

### ISSUE THREAD

**Issue by wouterhund** [facebook/flow#8598]
Flow version: 0.145.0

## Expected behavior
The following code should not give an incompatible-type error:

```
let someVar: ?{message: any} = null;

function foo1() {
  someVar = null; // [2]
  while(true) {
    someVar = { message: "hello world" }; // object literal [1] is incompatible with null [2]. [incompatible-type]
    break;
  }
}
```

Since it is functionally equivalent to:

```
function foo2() {
  someVar = null;
  someVar = { message: "hello world" };
}
```

Which is allowed by Flow.

## Actual behavior
Flow gives an incompatible-type error where it is not expected.

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVMCmAXMBnOAW0wDUBDAJwC4wB+Ab2LzzIHNMayA7ATwF8wAXjBcArjBgBudFFFcAxtgCWcLmChw4ARgAUASjD1UYfEVKUhI8VONgEACyVYd2CqMwGjJkwWLkKlvRgTCzsNABE9pgScHZwFDAAJuFgfNLeYABGFJhkANbpqah8MnKKKmoacABM+oa2vuYBwmIShY3+gcGYzGwcYJHR8HEJyanSJUA

**Comment by SamChou19815** [comment]
Now this works.
