### ISSUE TITLE
flow print-signature command mentioned in docs, nowhere to be found in actual CLI

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#8602]
Boy it would sure be great to have, but I don't see any `print-signature` command in the flow 0.145.0 CLI, despite it being shown here: https://flow.org/en/docs/cli/

**Comment by shubhamayush12** [comment]
Hello   Can I  try to fix this . Since I am a beginner to open source contributions . Can you help me to understand what should be done

**Comment by jedwards1211** [comment]
Flow isn't a good place to begin making open source contributions because it's an extremely complex program and it's written in OCaml.

**Comment by shubhamayush12** [comment]
Ok  Sir But how can we check if the command is supposed to exist .

**Comment by shubhamayush12** [comment]
OK

**Comment by jedwards1211** [comment]
Oh right. Looks like you're after Hacktoberfest $...your approach here is spammy.  If you want to avoid being flagged for spam, you'll have to find projects where you can figure out what to contribute without asking, or you can figure out the bulk of what needs to be done and only have to ask about details.
