### ISSUE TITLE
Add option for safe Array access

### ISSUE THREAD

**Issue by stackptr** [facebook/flow#8603]
## Proposal

Add an option, e.g. `safe_array_access`, defaulting to `false`, that produces a `?T` when accessing an element in an Array:

```js
const arr: Array<number> = [0, 1, 2]

// default, off
let value: number = array[1]; // Works.

// on
let value: number = array[1]; // Error
let value: ?number = array[1] // Works.
```

## Use case

Based on previous discussions that I've seen, the motivation for unsafe Array access has been as a convenience for developers and to ease adoption into existing codebases. However, it is reasonable for developers to desire strict Array access for newer codebases.

The page on [Flow strict](https://flow.org/en/docs/strict/) that due to the high adoption of Flow types, the trade-off around convenience and type safety may be flipped. However, I do not think this would be a suitable candidate for a rule because it appears that the machinery around this checking might be deeper than what is defined in the core libdef.

**Comment by stackptr** [comment]
Apologies, this was posted accidentally

**Comment by noppa** [comment]
There's also the new [`.at(index)` proposal](https://github.com/tc39/proposal-relative-indexing-method). Maybe instead of making the existing indexed access safe (and introducing bunch of new errors in existing codebases), we could add the new `.at()` method to libdefs and make it return `void | T` so new code can use that for the extra safety.

**Comment by stackptr** [comment]
Thanks for mentioning that proposal, @noppa.

> Maybe instead of making the existing indexed access safe (and introducing bunch of new errors in existing codebases)

I want to note that the reason this proposal is an option for the type-checker itself rather than a change to the libdefs is to avoid introducing such breaking changes for codebases that already use `flow`. Maybe there is something I've missed in how this would work.

Since I have no context to inform how hard it is to add such an option (contributors with expertise in either the type system or parser can hopefully provide color to validate or reject this approach) I am certainly open to approaches pertaining to changing or adding libdefs. To that end, the `.at(index)` proposal you reference looks like a great alternative to what I'm proposing here.

This all being said, while I agree that unsafe Array access is a sensible compromise for ease of adoption, it seems to me incompatible for a type-checking project as goals shift from emphasizing convenience to type-safety, which seems to be the rationale for Flow strict. In making this proposal, my hope is that projects using `flow` could be move toward better type safety as is practical for their codebase size.

**Comment by noppa** [comment]
`Array.prototype.at` is now at stage 4, so I guess it should also be added to the libdefs.  
But should it return `T` or `void | T` :thinking:
