### ISSUE TITLE
Unexpected parser state on valid file 😱  (problems with automatic semicolon insertion?)

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#8605]
Flow version: 0.145.0

Seems like there might be a problem with ASI in the parser.

## Expected behavior

Flow can parse [this file](https://github.com/jedwards1211/flow-parse-bug/blob/master/constants.js)

## Actual behavior
```
Error ┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈┈ src/constants.js:0:1

Unexpected parser state: (Failure
  "out of order
\"/Users/andy/github/jcore-historian-client/src/constants.js\": (65, 44) to (65, 45) >
\"/Users/andy/github/jcore-historian-client/src/constants.js\": (65, 33) to (65, 43)")
```

Doesn't reproduce in try flow, but I have a repo: https://github.com/jedwards1211/flow-parse-bug

If I add a type annotation to the offending line, the error goes away:

```diff
-export const VALID_TIMEOUT_MAX = PAGE_SIZES[0]
+export const VALID_TIMEOUT_MAX: number = PAGE_SIZES[0]
```

**Comment by noppa** [comment]
Is this because of ASI or because of well_formed_exports? I think the explicit type may be required in that export in [types_first/well_formed_exports](https://medium.com/flow-type/types-first-a-scalable-new-architecture-for-flow-3d8c7ba1d4eb). Confusing error either way.

**Comment by jedwards1211** [comment]
I wondered about well formed exports as well.  However, there were no errors on many other unannotated declarators.  *Surely* well formed exports doesn't change the parser behavior.  But I wonder if it led to regressions in the parser if they no longer have parsing test cases without well formed exports.

**Comment by mroch** [comment]
sorry about this... it's not coming from the parser itself, but from the type signature analysis that we do during the parsing phase so it's manifesting as a parse error.

@samwgoldman, this is coming from type_sig: https://github.com/facebook/flow/blob/cf31233b3053f83f790ee7657492c4b980b6d5dd/src/parser_utils/type_sig/type_sig_utils.ml#L78

**Comment by samwgoldman** [comment]
Thanks for the report! I have a fix on the way.

**Comment by jedwards1211** [comment]
Thank y'all!
