### ISSUE TITLE
flow-parser unexpectedly creates a global variable caml_create_file

### ISSUE THREAD

**Issue by thorn0** [facebook/flow#8609]
Flow version: flow-parser@0.146.0

## Expected behavior

```js
require("flow-parser");
console.log(global.caml_create_file);
// undefined
```

## Actual behavior

 ```js
require("flow-parser");
console.log(global.caml_create_file);
// [Function: U2]
```

**Comment by fisker** [comment]
And `caml_fs_tmp` too

**Comment by mroch** [comment]
indeed, this doesn't seem desirable. it's coming from js_of_ocaml:

https://github.com/ocsigen/js_of_ocaml/blob/3.5.2/runtime/fs.js#L225-L235

not sure the best way to fix it yet

**Comment by mroch** [comment]
we upgraded js_of_ocaml in 0.146, but this isn't new right? the old version did it too:

https://github.com/ocsigen/js_of_ocaml/blob/3.4.0/runtime/fs.js#L232

**Comment by fisker** [comment]
I'm sure it's new , we have this check in Prettier long time ago.

**Comment by mroch** [comment]
passing `--no-extern-fs` to js_of_ocaml fixes this. will be in 0.147. thanks!
