### ISSUE TITLE
[Feature Request] less horribly verbose syntax for typing generic arrow function chains

### ISSUE THREAD

**Issue by jedwards1211** [facebook/flow#8610]
Once upon a time, we could write function chains like this (real world example):

```js
type Resolver<S, A, C, I, R> = (S, A, C, I) => Promise<R>

const processArgs = 
  <A1: {}, A2: {}>(process: (args: A1) => A2) =>
  <S, C, I, R>(resolver: Resolver<S, A2, C, I, R>) =>
  (src: S, args: A1, appContext: C, info: I): Resolver<S, A1, C, I, R> =>
    resolver(src, process(args), appContext, info)
```

Now `types-first` requires all of that to be duplicated in a type annotation on the id.  But to make matters worse, the changes in 0.136.0 require return type annotations on every step of the chain to prevent escaped generic errors.  Meaning the amount of return type annotation code required is O(n^2) where n is the length of the chain...

So now I have to write this garbled mess:

```js
function processArgs<A1: {}, A2: {}>(
  process: (args: A1) => A2
): <S, C, I, R>(
  resolver: Resolver<S, A2, C, I, R>
) => Resolver<S, A1, C, I, R> {
  return <S, C, I, R>(
    resolver: Resolver<S, A2, C, I, R>
  ): Resolver<S, A1, C, I, R> => (
    src: S,
    args: A1,
    appContext: C,
    info: I
  ): Promise<R> => resolver(src, process(args), appContext, info)
}
```

So Flow is now a productivity killer when writing in a heavily functional style.  The signature in my first example should be completely sufficient for `types-first` mode to determine the type of `processArgs`.  Return type annotations shouldn't be needed in the middle of arrow function chains.

**Comment by SamChou19815** [comment]
There are two limitations here:
1. We have to have types-first for scalability
2. Flow doesn't infer unannotated stuff to be generic.
These two restrictions are unlikely to change
