### ISSUE TITLE
Conditional props raise an unexpected error in certain situations

### ISSUE THREAD

**Issue by kevinbarabash** [facebook/flow#8611]
Flow version: 0.146.0

## Expected behavior
Conditional props should work consistently regardless of where a value comes from as long as the values are the same type.

## Actual behavior
In certain situations, flow will error with `speculation-ambiguous` when a conditional prop is passed the result of function call.  Passing a literal or variable of the same type does not trigger the error.

I've created a minimal reproduction in the [playground](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAERbV0sDciiOAnukqgACo3RkAvKADeAH0SgloABbtIALlAkcWZADsA5gBpFygUID8WyhgGm5AX1BzZC5avXXQt9PbNKFpTeLCQArgBGqMg4LMagIKDIkKBBSWTsAI5hyOwAJqkqlPqFwsgk4WUk+gDkeLrIhoaUWIhOPIg00KRkAEJhODiwJZQAHjjFeWRUtDgAdADCTJj6xTgAPGKwEgB8sgGg7Pp5LQAUAJRaM3RzAHKwJ-seHuw4YVgl+mHQ0FwJYGh0NBbGtQCccERkNADo5ELDEOt+oNhp5KJBJCxgJBYLAWAkdjxEQMhiUghjwlEYnjgASEUiSfiOokxkI6JQCi1GFh4gAxHFg2CUap1Yg0GiUPygCKwHAqUDocRkIj1IraIioYQ4NCUOnElFqNEYrE4vFk0KRaKxRmgXg0YY6UDNHAAVSw0FA0guWh0eiMHr2mOxuJ4dv0Dve7ukTtd0AuIfteAjAGUGkZvanDB7HZQXW647wiciSgb0TJo3nzs4aX9EiQVLBvgV9DKfFgubqi6jSxGqwSlLX643QM28JzsB2GSXJDJkxnezwgA)

The code is pretty short so I'm including it here as well:
```
// @flow
import * as React from "react";

type Props = {|
    href: string,
    type?: empty,
|} | {|
    href?: empty,
    type?: "submit", // if type is required then the issue isn't trigger
|};

class Button extends React.Component<Props> {
    render(): React.Node {
        return null; // implement detail
    }
}

<Button href="/foo" />;
<Button type="submit" />;
<Button />;

// expected error, Foo doesn't accept both props at the same time
<Button href="/foo" type="submit" />; 

const getUrl = (): string => "/foo";
const url = getUrl();
const urlString: string = getUrl();

<Button href={getUrl()} />; // should not error
<Button href={url} />;  // should not error
<Button href={urlString} />;
```

**Comment by SamChou19815** [comment]
These examples now behave the same as you expect.
