### ISSUE TITLE
Missing flowlint for the old exact object type syntax

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8612]
Hello! 👋 We are using `exact_by_default=true` option for a while now and after seeing [this commit](https://github.com/facebook/relay/commit/6fa0b0d83b45af67d086e5b850b4b49915eccb4a) I decided to check what it takes to switch from explicit exact `{| |}` syntax to implicit exact `{ }` syntax.

This article (https://medium.com/flow-type/on-the-roadmap-exact-objects-by-default-16b72933c5cf) suggests that Step 3  (done) should involve _"a default-off flowlint to complain about using the old exact object type syntax"_, however, there doesn't seem to be such lint. Am I missing something or such lint indeed doesn't exist? 🤔 

BTW, other than that, everything seems to be working well! 👍 

Thank you very much! 🙂

**Comment by gkz** [comment]
Take a look on this page: https://flow.org/en/docs/linting/rule-reference/#toc-ambiguous-object-type

**Comment by mrtnzlml** [comment]
@gkz I am aware of this lint but that's not what I am looking for (and what I understood from the old article). From my understanding, `ambiguous-object-type` just like `implicit-inexact-object` are preventing you from mixing multiple styles and are both prioritizing the explicit types:

```js
type A = {x: number}; // Error
type B = {x: number, ...} // Ok
type C = {| x: number |} // Ok
```

However, I am looking for an evolution of these rules where explicit _exact_ types are no longer allowed, so:

```js
type A = {x: number}; // Ok (exact)
type B = {x: number, ...} // Ok (open)
type C = {| x: number |} // Error
```

Is there something like this? Isn't this what the article talks about? 🤔 

Essentially what is [described here](https://github.com/facebook/relay/commit/6fa0b0d83b45af67d086e5b850b4b49915eccb4a):

> Flow standard is now to use `{ }` for strict objects and `{ key: value, ... }` for open objects. This removes the old syntax from the docs.

**Comment by mrtnzlml** [comment]
Looking at this file, I'd say there is no such thing: https://github.com/facebook/flow/blob/d8dd6e73e7c806ed3d212cd297d21c9d970d2be6/src/common/lints/lints.ml 🕵️

**Comment by gkz** [comment]
cc @jbrown215

**Comment by mrtnzlml** [comment]
I figured that it's kind of achievable with [`eslint-plugin-flowtype`](https://github.com/gajus/eslint-plugin-flowtype):

```js
{
  'flowtype/require-exact-type': ['error', 'never'],
  'flowtype/require-inexact-type': 'off',
}
```

This should completely ignore inexact syntax `...` and prevent usage of the exact types `{| |}`. But there are still other issues like this one: https://github.com/gajus/eslint-plugin-flowtype/issues/467

> Internally we have an ESLint rule with autofixer for this, but I don't think it's open-source.

@gkz Would you please consider open-sourcing it? Even if it's just a [gist](https://gist.github.com/)? 🙂

**Comment by mrtnzlml** [comment]
I just realized there are 2 other motivations why to have such Flow lint:

- Eslint ignored files might still have the old syntax (happened to us by accident that we ignored `.storybook` folder)
- Flow types inside comments (I mean inside special `/*:: … */` comments) are being ignored by `flowtype/require-exact-type` rule and I am not aware of any other better Eslint rule which would handle this case and autofix it

**Comment by gkz** [comment]
@mrtnzlml, the ESLint rule `use-exact-by-default-object-type` has been published as part of https://www.npmjs.com/package/eslint-plugin-fb-flow

**Comment by mrtnzlml** [comment]
Thanks, @gkz! Unfortunately, there is a problem with it: https://github.com/facebook/flow/issues/8715

**Comment by mrtnzlml** [comment]
PR with a fix: https://github.com/facebook/flow/pull/8716
