### ISSUE TITLE
0.146.0 complains about 'incompatible-use'  unexpectedly

### ISSUE THREAD

**Issue by yoavniran** [facebook/flow#8613]
Flow version: 0.146.0

## Expected behavior

up to 146, this would work without an error:

```javascript
let data;
    const someFlag = 1;

    if (param) {
        data = { foo: "bar"};
    }

    if (data) {
        if (isSomething(someFlag)){
            doSomething(data.foo);
        }                        
    }

```

## Actual behavior

Now its breaking with: 

```
    30:             doSomething(data.foo);
                                     ^ Cannot get `data.foo` because property `foo` is missing in possibly uninitialized variable [1]. [incompatible-use]
        References:
        21:     let data;
                    ^ [1]
```

The fact of calling a function that doesnt involve the object in question is enough to make Flow "forget" about the check performed a line before. 

This seems like a bug to me

* Link to [Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjOA7AzgFzABM4BlOAWwFN8ALAS2wHMwBeMACijjgEo2AfGCx44MKgDp4TLj14BudCIJh6uctTqMW7DgAcAhgCcDFfqyEBCS4ZMVFmHCoRwjAa1xtOt0+aEBvVDBgsHFCIgN8A0UQ4SdCXEoqADEYAx0wAEYHWPoob2NfMEDY2Iior38wbjgALjAAIgAjYwaAXxiQtvRc-I5yg34qkKDS4JINGgZmfsiDCRr+MbBR4O6OpXjiOCpcbHwAdVc3L31Cs0Fi1dCaYjnO4OUEpNT0r2yekLyCuyHrsrmlWqPHqzVaG1i3Wu31mUT+y1UfTUky0M0S1FeTF4vBKCJCEySqJkAwWcgepTaeKppWu63QJF2+yO7g4+CMAFcqApUC53LhWRyuYogA)

**Comment by gkz** [comment]
Calling a function invalidates refinements (Flow is conservative in its analysis). It's possible that the definition of `isSomething` closes over `data` (or `isSomething` calls some other function that does that), and could reassign it. 

Either make data a `const` so Flow knows that it won't be reassigned, or pull out `data.foo` into its own `const` before calling `isSomething`.

```
if (data) {
  const foo = data.foo;
  if (isSomething(someFlag)){
    doSomething(foo);
  }  
}
```

**Comment by yoavniran** [comment]
Thats a shame. This is precisely the kind of thing that makes me (and many others) want to ditch Flow altogether. Is having to rewrite your code for no other reason than to make Flow happy... 😞
