### ISSUE TITLE
react hoc documentation incorrect?

### ISSUE THREAD

**Issue by cmtmc** [facebook/flow#8620]
https://flow.org/en/docs/react/hoc/

Last example there
```javascript
//@flow
import * as React from 'react';

function trivialHOC<Config: {}>(
  Component: React.AbstractComponent<Config>,
): React.AbstractComponent<Config> {
  return Component;
}

type DefaultProps = {| foo: number |};
type Props = {...DefaultProps, bar: number};

class MyComponent extends React.Component<Props> {
  static defaultProps: DefaultProps = {foo: 3};
}

const MyEnhancedComponent = trivialHOC<React.Config<Props, DefaultProps>>(MyComponent);

// Ok!
module.exports = MyEnhancedComponent;
```

copy-paste it to newly created CRA app gives 
```
Cannot build a typed interface for this module. You should annotate the exports of this module with types. Cannot determine the type of this call expression. Please provide an annotation, e.g., by adding a type cast around this expression.Flow(signature-verification-failure)
```

And in https://flow.org/try/ it shows "No errors!"

Problems with Types-First?  Please advise.

**Comment by cmtmc** [comment]
Or how to
```javascript
export default trivialHOC<React.Config<Props, DefaultProps>>(MyComponent);
```

Thanks!

**Comment by Brianzchen** [comment]
You need to explicitly annotate the var `MyEnhancedComponent`. With types first, flow does not allow inference through a dependencies.

So it would be something like this
```
type EnhancedProps = {
  foo: number,
  bar: number,
};

const MyEnhancedComponent: React.AbstractComponent<EnhancedProps> = (
  trivialHOC<React.Config<Props, DefaultProps>>(MyComponent)
);
```

And here's the [try](https://flow.org/try/#0PTAEAEDMBsHsHcBQBLAtgB1gJwC6gFSgCGAzqAEoCmRAxnpFrKqAORbV0sDciikArgDs6yWINA4syAG7Ii0ABIB5AMIAeFWMjIA5gC5QAb1AA6M6AC+APgAUiUKE0YxlQTgNVaOEwEEARiSSXk6Ygq44Glq6VgA0iACUHhze-oFYwUyh4ZGC2jpWRvag7Dj8WOIhLm48Frw4AJ7olKAAIpSQRPzQOAAKjOhkALxGAD6gkLCwBoL8qH6UWKAjFjwNTaB9sAOgw8ZmJm0dXb39JDGgfkRY07PzWOf7ljyINNCkZACy9ZVhbqCUAA8cK4ACZkTx0Ew-bKbAYFQxFQJEHDIGigEHtTrdWEkAyHLEnLZDIzjSYGADMT0QtUQa2aAFFBAALIjCSggnE7QoOCZTUAzOYLOIOS7Xfm3IXU540MSBUBfRkstkg6FuJJeXwBIJ0VURRWsmjsnEFYZ2BySGRyRSqNQQ7yaXK6NQ487447G2xfXXxBLPECgJQAawAhIhULAQV1KCZAZhcMSFcyDezdTwgA)

Does that work for you?

**Comment by cmtmc** [comment]
Thanks a lot, this does. 2 more questions pls:

1. type Props is already declared, so why it isn't enough just 
```javascript
const MyEnhancedComponent: React.AbstractComponent<Props> = 
```

2. Maybe add this into HOC docs with reference to types-first?

**Comment by Brianzchen** [comment]
> 1. type Props is already declared, so why it isn't enough just
> 
> ```js
> const MyEnhancedComponent: React.AbstractComponent<Props> = 
> ```

Seems like you can just do this and it works too, suppose I was just showing a fully example but do whatever you like to create your prop interface 😄 

---

And the reason HOC docs are wrong I imagine is because HoCs are not really the standard in react given the introduction of hooks and types first came out AFTER hooks so maybe either no one noticed or no one bothered 😓 . But would you be keen to update the docs given they effect you? Otherwise maybe it's something I can put on my todo list

**Comment by SamChou19815** [comment]
We now have docs on how to deal with the missing annot error
