### ISSUE TITLE
The .flowconfig [options] section may need to mention that Flow is no longer supports esproposal configuration.

### ISSUE THREAD

**Issue by judysocute** [facebook/flow#8623]
I use this option in my .flowconfig file:
```
[options]
esproposal.class_instance_fields=warn
```
Flow give this to me:
```
flowconfig:19 Error setting value for "esproposal.class_instance_fields".
Flow no longer supports esproposal configuration.
The only supported value for this option is `enable`, which is also the default.
```

I tested many times, and I found out that since "v1.135.0", Flow is no longer supports esproposal configuration in [options].
I believe the [documentation](https://flow.org/en/docs/config/options/#toc-esproposal-class-instance-fields-enable-ignore-warn) has to mention that.

**Comment by gkz** [comment]
Thanks for feedback, this should be fixed now. I also split out the deprecated options in the docs so that it's more clear what's deprecated.
