### ISSUE TITLE
 error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by FezVrasta** [facebook/flow#8628]
Flow version: 0.147.0

## Expected behavior

flow should run without errors

## Actual behavior

when I run Flow on my GitHub Workflow I get:

```
/github/workspace/node_modules/flow-bin/flow-linux64-v0.147.0/flow: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory
```

See https://github.com/popperjs/react-popper/runs/2192949490

* Link to Try-Flow or Github repo: N/A

**Comment by mroch** [comment]
as part of adding ARM64 support, >= 0.147 requires libatomic (part of GCC).

it looks like the `culturehq/actions-yarn:latest` image you're using is based on `node:13-slim`. from the [node docker docs](https://hub.docker.com/_/node):

```
node:<version>-slim
This image does not contain the common packages contained in the default tag and only contains the minimal packages needed to run node. Unless you are working in an environment where only the node image will be deployed and you have space constraints, we highly recommend using the default image of this repository.
```

Is there a way you could use the full image instead?

**Comment by FezVrasta** [comment]
I see, thanks for the help, I'll need to find an alternative GitHub Action, do you have any suggestion by chance?

I'll close this since it seems to be an expected breaking change.

**Comment by SergioMorchon** [comment]
The same just happened to me with Ubuntu 20.04 in WSL2:
> ~/dev/webapp ▶ yarn flow
/home/smorchon/dev/webapp/node_modules/flow-bin/flow-linux64-v0.154.0/flow: error while loading shared libraries: libatomic.so.1: cannot open shared object file: No such file or directory

**Comment by jadh4v** [comment]
FWIW, installing `build-essentials` solves this problem for me in WSL2.
