### ISSUE TITLE
Class loses new-ability when used as value in object type declaration

### ISSUE THREAD

**Issue by Ashoat** [facebook/flow#8632]
Flow version: v0.147.0

I don't think the `test3` line below should error:

```js
declare class Test {
  constructor(): this;
}

const test = new Test(); // works

declare var test2: {|
  test: Test,
|};

const test3 = new test2.test(); // doesn't work
```

[Try Flow](https://flow.org/try/#0CYUwxgNghgTiAEkoGdnwComQF3gbwCh5EB7AOxxgFcxsSYAKASgC55sALAS2QG4CAvgQJhyOdllwBeeGRAB3DJOa94AejXx59ANbJhoJHHgA3WBJwAmNngA+RC9jaYcAGgK2B-EWNzZJAMzwMnKK-lYAdOHYKuqawCRYZADkuNowOkA)

**Comment by Ashoat** [comment]
I think this is solved by using `typeof Test` in the declaration:

```js
declare var test2: {|
  test: typeof Test,
|};
```

**Comment by gkz** [comment]
The name of the class when used as an annotation is the type of the instance. You can use either `typeof X` or `Class<X>` to get the type of the class itself.
