### ISSUE TITLE
Flow fails in gitlab CI with exit code 6

### ISSUE THREAD

**Issue by jcolakk** [facebook/flow#8638]
Flow version: 0.147.0

## Expected behavior
Flow to successfully execute on Gitlab CI.

## Actual behavior
Flow exits with code 6 `The flow server is not responding`. 

Not sure if relevant info, but this happens when trying to upgrade `@babel/core` package. This happened to us in the past but clearing the GitLab CI cache helped, but now it's not helping. 

I can't reproduce it locally, it only happens in the CI.

**Comment by mroch** [comment]
can you check `/tmp/flow/<path to root>.log` for an error about why the server is failing to start?
