### ISSUE TITLE
Is flow capable of building strings out of keys of nested objects?

### ISSUE THREAD

**Issue by danielo515** [facebook/flow#8649]
Hello.
I'm trying to make an internationalization function type safe. The function takes an object and returns a function that takes strings that map to keys on the object. This is easy for plain properties (just do `$Keys`), but this should allow for nested maps. The type is simple enough, so this project is not as ambitious as #5767
I will even be happy with a maximum fixed amount of of nesting, but I saw that it is possible to define recursive types so I though it may be possible to make this infinitely type safe?

This is a failed attempt I made

```flow
type Plain = { [string]: string }
type Nested = { [string]: Plain | string }
type Phrases = Plain | Nested

type GetPhraseType<T0: Phrases> = $Call<
    & (<K:Nested>() => GetPhraseType<K>)
    & (<K:Plain>() => $Keys<K>)
    , T0>

type Poly = (ph: Phrases) => (k: GetPhraseType<Phrases>) => string

const phrases: Phrases = {
  test: '99',
  nested: {
    something:'99',
  },
}

const pol: Poly = (p) => k => ''

pol(phrases)('testu') // should error
```

[try](https://flow.org/try/#0C4TwDgpgBACgNgQwJYDsoF4oG8oG0DOwATqgOYC6AXFISSqVAL4BQokUAchIRACYbY8tMlViJUUAD41iZJq3DQYACyIJ83AfGRppXHr2YL2AcQjAVajQBVFAHmsAGapfXcAfAIAkAYQRw4O2YoEKgAMigACjsAaUp9YD53SIBKDE8zC1U3W0hY9xTg0IjouO1UZLT0Ty8YiBB8fMLQqAAaKCd3IzYlAHs4EAFIsGUXbI18Ks9IgGtqTNcbe0WPKZk6UiMAY16UQigRq24xo-wBLCLEwmoAcgBOO5vWopRuRN5qC5b8XoBbc2UZEo90ezxCjGeLGYOz2wAO-Rc-UGmGGaxm6SgNxuRjA-WG424KUiNyuwAArjcUkA)

There are other similar approaches like #5844 which just similar, and #5767 which is way more complex. Before I waste more hours into this I want to know if it is theoretically impossible to do in flow.

**Comment by SamChou19815** [comment]
It's unclear to me what you want from this example. Maybe an implementation of the function can help.
