### ISSUE TITLE
"Could not decide which case to select" error occurs on lowercase

### ISSUE THREAD

**Issue by conradreuter** [facebook/flow#8666]
Flow version: 0.151.0

When using discriminated unions I noticed something odd:

This works: ([Try Flow](https://flow.org/try/#0C4TwDgpgBAwg9gOwGYEsDmUC8AoKUA+UA3oQNQDWKCAJgFxSiRxJQDSV1AdAGIDyvBAL64CxMpRr1GEZmw6cAQgEEASkOzYAxogDOwOTSxReAIwBWETcE5IAThAgAvCAAoiIvr3ouA5J5-0fvw+AJQANCLKKt4+UQFQsaqhEYIhGtoIelBIcHDwyOj0+agYmMQSdAZcnsIZWSYAhrbFhbCIJUZEFfTsNIqqwkA))
```js
type Config =
  | {| +kind: typeof Kind.FOO |}
  | {| +kind: typeof Kind.BAR |}

const Kind = Object.freeze({
  FOO: ('FOO': 'FOO'),
  BAR: ('BAR': 'BAR'),
})

const fooConfig: Config = {kind: Kind.FOO}
const barConfig: Config = {kind: Kind.BAR}
```

but this gives `[speculation-ambiguous]`: ([Try Flow](https://flow.org/try/#0C4TwDgpgBAwg9gOwGYEsDmUC8AoKUA+UA3oQNQDWKCAJgFxSiRxJQDSV1AdEnHAQL64CxMpRr1GEZmw6cARgEMATgOzYAxogDOwGTSxQA8nIBWEdcG5KIEAF4QAFESE849BwHIAYocMf63r4eAJQANEKKSu4eAEIAggBK-lCxiSHh-MFqmgg6UK7wyOj0hagYmMRidHpcroI5eZGlxbCIZQZEVfTsNPLKgkA))
```js
type Config =
  | {| +kind: typeof Kind.foo |}
  | {| +kind: typeof Kind.bar |}

const Kind = Object.freeze({
  foo: ('FOO': 'FOO'),
  bar: ('BAR': 'BAR'),
})

const fooConfig: Config = {kind: Kind.foo}
const barConfig: Config = {kind: Kind.bar}
```

Note that the only difference is in the casing of the keys of `Kind`.

Also note that the keys of `Kind` don't need to be equal to the values for this to work. ([Try Flow](https://flow.org/try/#0C4TwDgpgBAwg9gOwGYEsDmUC8AoKUA+UA3oQNQDWKCAJgFxSiRxJQDSV1AdAGIDyvBAL64CxMpRr1GEZmw6cAQgEEASkOzYAxogDOwOTSxReAIwBWETcE5IAThAgAvCAAoiIvr3ouA5AEUAVQANH3p-YJ8ASgAaEWUVbx8ALSUABVCoZLSo2MFIjW0EPSgkODh4ZHR6CtQMTGIJOgMuT2FC4pMAQ1saqthEWqMiRvp2GkVVYSA))

**Comment by SamChou19815** [comment]
This now type checks.
