### ISSUE TITLE
Strange behavior when mixing Generic Promises

### ISSUE THREAD

**Issue by shirohana** [facebook/flow#8668]
Flow version: v0.151.0

## Expected behavior

Expect `No errors!` in sample.

## Actual behavior

Error reported, but if and only if one situation that would be no error.

Here's the sample:

### Sample 1 (works as expect)

<pre><code><a href="https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAm6NjqFlYw2roGACqmZFo6evqR1voJxuhQzIwAxhhycIxguQXEjj4MLm4eXoSm5KhgYFx4GMxcpbXungB07VJwMABueI7k9GAATAAMfD6oqsDAYADqcFwA1lK0e3gAHviFqDRSWAVgVf4ULWD5JTJgACY0GNPp0SkG4XhwUDKeXyjTENB+QIqVXuj0Yz2mxDIbw+91WYDseBwWwwYG4ri4ewUuOOeFOrVhz0kYFESPeNGWQA">https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAm6NjqFlYw2roGACqmZFo6evqR1voJxuhQzIwAxhhycIxguQXEjj4MLm4eXoSm5KhgYFx4GMxcpbXungB07VJwMABueI7k9GAATAAMfD6oqsDAYADqcFwA1lK0e3gAHviFqDRSWAVgVf4ULWD5JTJgACY0GNPp0SkG4XhwUDKeXyjTENB+QIqVXuj0Yz2mxDIbw+91WYDseBwWwwYG4ri4ewUuOOeFOrVhz0kYFESPeNGWQA</a></code></pre>

```ts
/* @flow */

type A = {| a: number |}
type B = {| b: string |}

type $Await<P> = $Call<<R>(Promise<R>) => R, P>

type $CallAwait<T> = $Await<$Call<T>>

function funcA (): Promise<A> {
  return Promise.resolve({a: 20})
}

// Works as expect
async () => {
  const data: $CallAwait<typeof funcA> = await funcA()
  const a: A = data
  // Report errors in expect
  const b: B = data
}
```

### Sample 2 (unexpected errors reported)

When calls `$CallAwait` only once, everything works well, but if called more than once, errors reported:

<pre><code><a href="https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAm6NjqFlYw2roGACqmZFo6evqR1voJxuhQzIwAxhhycIxguQXEjj4MLm4eXoSm5KhgYFx4GMxcpbXungB07VJwMABueI7k9GAATAAMfD6oquWFxaWrolU1rn1ewk0tbR1dPbv1g3jDYxPkkmAA5PMPi8vowMBgAKIAHviFTDgYG4ri4qBoUiwBTAVX8FCO+RKMjAABMaBhpuloikDOE8HAoGU8vlGmIaDiiRUqgikRhaAxiGQ0Ri3qgPt8-ngAYwgSC4GCIVD8jC-CRDq1EYxkczMZZrDFUniCZT8gcyRTNtSJbSwPdREz0TQ3kA">https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAm6NjqFlYw2roGACqmZFo6evqR1voJxuhQzIwAxhhycIxguQXEjj4MLm4eXoSm5KhgYFx4GMxcpbXungB07VJwMABueI7k9GAATAAMfD6oquWFxaWrolU1rn1ewk0tbR1dPbv1g3jDYxPkkmAA5PMPi8vowMBgAKIAHviFTDgYG4ri4qBoUiwBTAVX8FCO+RKMjAABMaBhpuloikDOE8HAoGU8vlGmIaDiiRUqgikRhaAxiGQ0Ri3qgPt8-ngAYwgSC4GCIVD8jC-CRDq1EYxkczMZZrDFUniCZT8gcyRTNtSJbSwPdREz0TQ3kA</a></code></pre>

```ts
/* @flow */

type A = {| a: number |}
type B = {| b: string |}

type $Await<P> = $Call<<R>(Promise<R>) => R, P>

type $CallAwait<T> = $Await<$Call<T>>

function funcA (): Promise<A> {
  return Promise.resolve({a: 20})
}

function funcB (): Promise<B> {
  return Promise.resolve({b: '20'})
}

// Expect no error
async () => {
  // Reported 2 errors:
  // 1. Cannot assign `await funcA()` to `data` because property `a` is
  //    missing in `B` [1] but exists in `A` [2]. [prop-missing]
  // 2. Cannot assign `await funcB()` to `data` because property `b` is
  //    missing in `A` [1] but exists in `B` [2]. [prop-missing]
  const data: $CallAwait<typeof funcA> = await funcA()

  // Reported 2 errors:
  // 1. Cannot assign `data` to `a` because property `a` is missing in
  //    `B` [1] but exists in `A` [2]. [prop-missing]
  // 2. Cannot assign `data` to `a` because property `b` is missing in
  //    `A` [1] but exists in `B` [2]. [prop-missing]
  const a: A = data
}

// Expect no error
async () => {
  // Reported 2 errors:
  // 1. Cannot assign `await funcA()` to `data` because property `a` is
  //    missing in `B` [1] but exists in `A` [2]. [prop-missing]
  // 2. Cannot assign `await funcB()` to `data` because property `b` is
  //    missing in `A` [1] but exists in `B` [2]. [prop-missing]
  const data: $CallAwait<typeof funcB> = await funcB()

  // Reported 2 errors:
  // 1. Cannot assign `data` to `a` because property `a` is missing in
  //    `B` [1] but exists in `A` [2]. [prop-missing]
  // 2. Cannot assign `data` to `a` because property `b` is missing in
  //    `A` [1] but exists in `B` [2]. [prop-missing]
  const b: B = data
}
```

### Sample 3 (strange but works correctly)

Now I create 2 same type of `$CallAwait` and called only once per type, it would work in expect.

<pre><code><a href="https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAm6NjqFlYw2roYAIz6ACqmZFo6evqR1knGxmoEWdHpGABMOWYxGYU5eahQzIwAxhhycIxg9U3Ejj4MLm4eXoSm5KhgYFx4GMxc7f3ungB0k1JwMABueI7k9GAlAAx8Pqiqnc2t7WeiPX2uC17CI2MTUzNzd4PLeKsbW+SSYAA5AdAUcTuhgMAwABRAAe+GaTDgYG4ri4qBoUiwTTAPX8FGejTaMjAABMaBhdoVKvF9OE8HAoB0Go1hmIaMVmV0eoTiRhaAxiGRyZTnpCwHY8Dg4Fx+aiZVIwAoUfC8M1eYwSQDRMKKTRwahxXCEfzGMj5ejMdjGri-CQnuMiZr+SKqZZrDSyvTGVzGo92ZyrjzHXywNqxK6xVDJdLZSiuGjFcq8Kr1SHnQKiBG9eCgA">https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAm6NjqFlYw2roYAIz6ACqmZFo6evqR1knGxmoEWdHpGABMOWYxGYU5eahQzIwAxhhycIxg9U3Ejj4MLm4eXoSm5KhgYFx4GMxc7f3ungB0k1JwMABueI7k9GAlAAx8Pqiqnc2t7WeiPX2uC17CI2MTUzNzd4PLeKsbW+SSYAA5AdAUcTuhgMAwABRAAe+GaTDgYG4ri4qBoUiwTTAPX8FGejTaMjAABMaBhdoVKvF9OE8HAoB0Go1hmIaMVmV0eoTiRhaAxiGRyZTnpCwHY8Dg4Fx+aiZVIwAoUfC8M1eYwSQDRMKKTRwahxXCEfzGMj5ejMdjGri-CQnuMiZr+SKqZZrDSyvTGVzGo92ZyrjzHXywNqxK6xVDJdLZSiuGjFcq8Kr1SHnQKiBG9eCgA</a></code></pre>

```ts
/* @flow */

type A = {| a: number |}
type B = {| b: string |}

type $Await<P> = $Call<<R>(Promise<R>) => R, P>

type $CallAwait1<T> = $Await<$Call<T>>
type $CallAwait2<T> = $Await<$Call<T>>

function funcA (): Promise<A> {
  return Promise.resolve({a: 20})
}

function funcB (): Promise<B> {
  return Promise.resolve({b: '20'})
}

// Expect no error
async () => {
  const data: $CallAwait1<typeof funcA> = await funcA()
  const a: A = data
  // Report errors in expect
  const b: B = data
}

// Expect no error
async () => {
  const data: $CallAwait2<typeof funcB> = await funcB()
  const b: B = data
  // Report errors in expect
  const a: A = data
}
```

---

Is it there're something I hav't got in Flow, or just I used in an incorrect way?

The goal is create a Generic Type that extract the resolve value of Promise returns by a function.

```ts
// Works
type $Await<P> = $Call<<R>(Promise<R>) => R, P>

function func (): Promise<TypeA> {}
const a: TypeA = (await func(): $Await<$Call<typeof func>>)
```

```ts
// Works
type $Await<P> = $Call<<R>(Promise<R>) => R, P>
type $CallAwait<P> = $Await<$Call<P>>

function func (): Promise<TypeA> {}
const a: TypeA = (await func(): $CallAwait<typeof func>)
```

```ts
// Should works but report errors
type $Await<P> = $Call<<R>(Promise<R>) => R, P>
type $CallAwait<P> = $Await<$Call<P>>

function func1 (): Promise<TypeA> {}
function func2 (): Promise<TypeB> {}
const a: TypeA = (await func1(): $CallAwait<typeof func1>)
const b: TypeB = (await func2(): $CallAwait<typeof func2>)
```

Here's another completely sample:

<pre><code><a href="https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAmagQWVjDaugYAYowMscyMAMYYcnCMpmRaOnr6Edb68cbGYZqW1tF6AEzFCWBJqemZ2ZrVBoU2JWXY6l0dAMz1iclpGVlmHQWV3VllqOSoYGBQYy2Mq2PEjj4MLm4eXoSmSysrXHgYzFybB+6eAHSXUnAwAG54juT0YDUADHwfMswKoVmtmhMtqlRLt9q4Hl5hKcQRcrjc7gijs88K8Pl9yJIwAByAHEoEgsG0KRYVJgXb+CiosApTIyMAAExoGF+uRiM0i+j6eDgUGhKRObRoeQw4sIu2ZrMY7N+xDIXJ5lPQKxoNLpDJIKPOLLZso1vOmXSFQlF4uRUpldoVxqV7KJonV3JoWpButpKXpfkNTJdps5XoYAxl1vwtohEodMTlzvOrtlqrE5p9Or1AYNRtTYfNkdm02FcbGyLE0qT8eEKZWabA7szXq1qmAwDAABU4GA8MrmAQ9GAPEw4On2HBmLKAAblqCzx7lbs2qBNCVifMhLGefQnFdrjcewOM+5HfTI9BnE3K2U4NU7w5PF5vT77pzkWgMAGg4GNsMcBPc8X1xN8kU-ZsGFJf5iT-bVqX9U9gxvAC73DHlIzLNcwAfRMRwfRUwwzT1NRWKk-X1IMCzQ9li3aaMF1wqsyBrAjhCI9DfhPLNyIQyi82okNC3Q+i+XyK1tyYvD8NlRxtwfHwG1vFUGEfXjQX43NkJolSzQjBj+UkoTpPtatHXkoSgKU-8RNUsAeLbPjfW07dUL0jDeVLGU6lXWN122WT6QUwgbM4+z1KczSXKQtzwv0zCKkiDpfKPSsgssxlrOUpsW1I71nJzWKhPcpsxO8mJhiknC8PMpNMuDRScuItTWzI6KiqoxlSqLAyo0q-Rqv85iMoU4QwtDdC8s89t0E7Hs+wHKQbmHWUx0YCcWRoZhPA5ZssDARQB24OQAy6KRl2FTQAHFjvkFJZhGRp1gmNorRKa8QXjDY5UDVr3Mua5bgoX4AQEQrxR+us-oc4S0SBzZCWgslwY6xCupQ+LPJLQUmPjE4xHx5quNa-Ls3RwTuqx8rcZwus2jrYm3QYRz2oo1ySupvrbsYE6Htp4b8YZ7YmfTUmZohgSdLhjyxJ5vnHrx9LCcrUWoNhsm+IEIA">https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN4A+YAhgFxgB2ArgLYBGeATmJQL6ZcBAEKkK1dgwDOGLgEtGAc14DB+MABJCCGnIwAeAAoA+MRoDCNGDH36ASsYAUhrnFZypee8YCUpU3YANGAmagQWVjDaugYAYowMscyMAMYYcnCMpmRaOnr6Edb68cbGYZqW1tF6AEzFCWBJqemZ2ZrVBoU2JWXY6l0dAMz1iclpGVlmHQWV3VllqOSoYGBQYy2Mq2PEjj4MLm4eXoSmSysrXHgYzFybB+6eAHSXUnAwAG54juT0YDUADHwfMswKoVmtmhMtqlRLt9q4Hl5hKcQRcrjc7gijs88K8Pl9yJIwAByAHEoEgsG0KRYVJgXb+CiosApTIyMAAExoGF+uRiM0i+j6eDgUGhKRObRoeQw4sIu2ZrMY7N+xDIXJ5lPQKxoNLpDJIKPOLLZso1vOmXSFQlF4uRUpldoVxqV7KJonV3JoWpButpKXpfkNTJdps5XoYAxl1vwtohEodMTlzvOrtlqrE5p9Or1AYNRtTYfNkdm02FcbGyLE0qT8eEKZWabA7szXq1qmAwDAABU4GA8MrmAQ9GAPEw4On2HBmLKAAblqCzx7lbs2qBNCVifMhLGefQnFdrjcewOM+5HfTI9BnE3K2U4NU7w5PF5vT77pzkWgMAGg4GNsMcBPc8X1xN8kU-ZsGFJf5iT-bVqX9U9gxvAC73DHlIzLNcwAfRMRwfRUwwzT1NRWKk-X1IMCzQ9li3aaMF1wqsyBrAjhCI9DfhPLNyIQyi82okNC3Q+i+XyK1tyYvD8NlRxtwfHwG1vFUGEfXjQX43NkJolSzQjBj+UkoTpPtatHXkoSgKU-8RNUsAeLbPjfW07dUL0jDeVLGU6lXWN122WT6QUwgbM4+z1KczSXKQtzwv0zCKkiDpfKPSsgssxlrOUpsW1I71nJzWKhPcpsxO8mJhiknC8PMpNMuDRScuItTWzI6KiqoxlSqLAyo0q-Rqv85iMoU4QwtDdC8s89t0E7Hs+wHKQbmHWUx0YCcWRoZhPA5ZssDARQB24OQAy6KRl2FTQAHFjvkFJZhGRp1gmNorRKa8QXjDY5UDVr3Mua5bgoX4AQEQrxR+us-oc4S0SBzZCWgslwY6xCupQ+LPJLQUmPjE4xHx5quNa-Ls3RwTuqx8rcZwus2jrYm3QYRz2oo1ySupvrbsYE6Htp4b8YZ7YmfTUmZohgSdLhjyxJ5vnHrx9LCcrUWoNhsm+IEIA</a></code></pre>

**Comment by SamChou19815** [comment]
Now both work
