### ISSUE TITLE
where can I find the papers?

### ISSUE THREAD

**Issue by cgcgbcbc** [facebook/flow#867]
I wonder if there are publications available?

**Comment by popham** [comment]
The sources used to reference the "Pottier Thesis".  I'm 99% sure that [this is a translation](https://hal.inria.fr/file/index/docid/73205/filename/RR-3483.pdf).  It's *a* paper, anyway.  (It doesn't layout generalization to OO classes, but I suspect that it was Flow's starting point.)

**Comment by samwgoldman** [comment]
@cgcgbcbc No publications specifically about Flow as of yet.
