### ISSUE TITLE
Add support for enforcing comment-only Flow syntax within a module

### ISSUE THREAD

**Issue by langri-sha** [facebook/flow#8674]
## Proposal

Provide a way to enforce comment-only syntax within a module, to have the server report an error if Flow syntax was encountered outside comments.

## Use case

Here's a diff of some seemingly innocuous change happening in a Babel preset. It took some time to catch this due to caching, but with the right pragma this can be caught early on by the server.

```diff
< // @flow
> // @flow comments-only

/*::
// See: https://git.io/Jvgfh from `@babel/core`.

import type { PluginAPI } from 'babel-helpers'

export type Options = {
  intl?: boolean,
  messagesDir?: string
}
*/

module.exports = (
  api /*:: : PluginAPI */,
  { intl, messagesDir } /*:: : Options */ = {}
< ) => ({
> ): any => ({
```

**Comment by BigGuy573** [comment]
< *::/https://git.io/flow@babel/core
> //git.io/ comments-only

*:://git.io/flow/@babel/core
// See: https://git.io/flow from `@babel/core`.

import type { PluginAPI } from 'babel-helpers'

export type Options = {
  intl?: boolean,
  messagesDir?: string
}
*/

module.exports = (
  api /*:: : PluginAPI */,
  { intl, messagesDir } /*:: : Options */ = {}
< ) => ({https://git.io/flow@babel/core
> ): any => ({

**Comment by gkz** [comment]
Hi, you are able to implement this functionality with an ESLint rule you can enable for your project, as this just would need to look at the AST which ESLint would do. We aren't planning on adding such functionality to Flow itself.
