### ISSUE TITLE
Flow v0.143.0 removed support for types_first option but documentation still advises its use

### ISSUE THREAD

**Issue by sustmi** [facebook/flow#8681]
Flow v0.143.0 removed support for `types_first` option in `.flowconfig`: https://github.com/facebook/flow/releases/tag/v0.143.0

However, the online documentation says:
>  Note: If you are using a version where types-first is enabled by default (ie. >=0.134), make sure you set types_first=false in your .flowconfig while running the codemods.

See: https://flow.org/en/docs/lang/types-first/

I tried to use v0.143.0 and added `types_first=false` to my `.flowconfig` and I got error:
```
.flowconfig:16 Unsupported option specified! (types_first)
```

**Comment by dsainati1** [comment]
Yes, v0.143.0 made `types_first` the only supported mode, so the `.flowconfig` option to turn it off is no longer available. I would be happy to accept a PR to remove this language from the docs.

**Comment by mroch** [comment]
@dsainati1 doesn't this mean the annotate-exports codemod no longer works? we should remove it, and update the docs to say to upgrade incrementally to 0.142 to use the codemod before upgrading further.

**Comment by SamChou19815** [comment]
We now mark it as removed config.
