### ISSUE TITLE
Make classes/interfaces a subtype of object types containing no functions

### ISSUE THREAD

**Issue by mischnic** [facebook/flow#8687]
Flow version: 0.153.0

```js
class Position {
    value: number = 2
}

declare function find({value: number, ...}): boolean;

let pos = new Position();
find(pos);
```

https://flow.org/try/#0MYGwhgzhAEAKD2ECWAXJ8B20DeAoaB0AbmCAK4CmAXNBmQLYBGFATtALzQBMuAvrrgAmFUGBYVoAMzIZgaTFKQZBACmwly1Wg2YsANNAB0x3gEoajePBAUwGANwCbKaAAdEHWhQDucRKnQMFVNHSSVVdwgQoA

## Expected behavior

This should work fine as in previous versions because the only reason for classes to not be subtypes of object types is making sure that functions aren't unbound. However, if no functions are actually unbound, this should be safe.

## Actual behavior

```
8: find(pos);
        ^ Cannot call `find` with `pos` bound to the first parameter because `Position` [1] is not a subtype 
          of object type [2]. Class instances are not subtypes of object types; consider rewriting
          object type [2] as an interface. [class-object-subtyping]
References:
7: let pos = new Position();
             ^ [1]
5: declare function find({value: number, ...}): boolean;
                         ^ [2]
```

**Comment by dsainati1** [comment]
No. This would create an inconsistent and confusing type hierarchy, and it doesn't really seem to be that important, as the example you linked above can be an interface with very little effort.

**Comment by mischnic** [comment]
Thanks, you're right, the parameter can just be replaced with an interface. I guess I'm still thinking in <v0.153.0 where an object type and interface are mostly the same
