### ISSUE TITLE
Flow Try is broken: "Parsing_heaps_exceptions.ALoc_table_not_found"

### ISSUE THREAD

**Issue by mischnic** [facebook/flow#8699]
https://flow.org/try/#0MYGwhgzhAEAa0G8BQ1XQgFzBglsaA5gKYYAUYAXNAHYCuAtgEZEBOANNI1ZiztQQEpkaEdBYlaLajSIB3OKQEBuFGgC+SDUmAB7apjG1pAXjgA6YhhUsjipUA

https://flow.org/try with 0.155

Code:
```js
class X {
    static get(a: number, b: string){
        return new X();
    }
}

const run = X.get;
run();
```

## Expected behaviour

Either no error is reported, or there is a diagnostic in the right pane

## Actual behavior

There's an error printed in the console, mentioning `Parsing_heaps_exceptions.ALoc_table_not_found`

<img width="1031" alt="Bildschirmfoto 2021-07-10 um 12 11 33" src="https://user-images.githubusercontent.com/4586894/125159488-f902cc00-e177-11eb-9cbb-558216d2a9a1.png">

**Comment by samwgoldman** [comment]
Thanks for raising this issue! I just landed a fix, but I'll re-open until Try Flow updates with the new code.
