### ISSUE TITLE
Interfaces/declaration files are not auto-reloaded

### ISSUE THREAD

**Issue by CrabDude** [facebook/flow#87]
1. `flow start --lib interfaces/`
1. Create an error that shows in `flow`
2. Update/create corresponding interface file / declaration
1. Run `flow` => Error still displayed (interface file has not been updated on server)
1. `flow stop`
1. `flow start --lib interfaces/`
1. `flow` => Error gone.

**Comment by icynoangel** [comment]
+1

**Comment by mroch** [comment]
should be fixed (around 0.9, probably?). now the server restarts itself when the lib files change.
