### ISSUE TITLE
Using Function.bind causes a method-unbinding error.

### ISSUE THREAD

**Issue by AaronAsAChimp** [facebook/flow#8704]
Flow version: v0.153.0

## Expected behavior

A method bound to the `this` reference should suppress the method-unbinding error. Binding a method to `this` prevents the exact errors that the method-unbinding check is meant uncover. It also makes it difficult to bind event handlers using vanilla JS or JQuery.

## Actual behavior

The following code:

```js
class A {
  events() {
    this._onSubmit.bind(this);
  }
  _onSubmit() {}
}
```

produces the error:

```
../\-:3:     this._onSubmit.bind(this);
                  ^ Cannot get `this._onSubmit` because property `_onSubmit` [1] cannot be unbound from the context [2] where it was defined. [method-unbinding]
    References:
    ../\-:3:     this._onSubmit.bind(this);
                      ^ [1]
    ../\-:5:   _onSubmit() {}
               ^ [2]
```

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYGwhgzhAECC0G8BQ1oFMBuaB2AXCAFAJSIqrS4AWAlhAHQD6A9tgMoCuARgLbW52dq2ACYEqtIgG4yAXzLM2XXrmKI5MoA

**Comment by dsainati1** [comment]
This is working as intended. Prefer to use an auto-binding arrow method in cases like this.
