### ISSUE TITLE
An object-as-map's value type is ignored when returning the object from a function

### ISSUE THREAD

**Issue by benchristel** [facebook/flow#8719]
Flow version: 0.157.0, 0.154.0

## Expected behavior

This should fail to typecheck, as the returned object's property value is not a `string`:

```
function makeMap(key: string): {|[string]: string|} {
  return {
    [key]: 999
  }
}
```

## Actual behavior

No errors.

* Link to Try-Flow or Github repo:

  https://flow.org/try/#0GYVwdgxgLglg9mABAWwIYGsCmBZVAHACiwE8AuRAZygCcYwBzASnIG8AfAbStoYF1zudemwC+iFgChEiapighqSSdOkcS-RAE5tUxCIn6gA

**Comment by jbrown215** [comment]
https://flow.org/try/#0CYUwxgNghgTiAEA3W8DWICeAueBnALjAJYB2A5gNwBQAFAN4Da6GAujgJycC+OjBx5NnkKkyXAJQUgA minimized repro
