### ISSUE TITLE
Cannot resolve name devicePixelRatio 

### ISSUE THREAD

**Issue by Dagur** [facebook/flow#8724]
If I try to use `devicePixelRatio` without `window.` in front I get this error:

> Cannot resolve name devicePixelRatio. [cannot-resolve-name]  infer

**Comment by Brianzchen** [comment]
https://github.com/facebook/flow/blob/main/lib/dom.js#L4157
If anyone wants to, it should be a pretty simple fix to add it somewhere around here as
```
declare var devicePixelRatio: number;
```
