### ISSUE TITLE
`String.prototype.concat()` should accept `Array<mixed>`, not only `Array<string>`

### ISSUE THREAD

**Issue by justingrant** [facebook/flow#8728]
## Missing/Incorrect APIs

`String.prototype.concat` should allow any type as its arguments.

`concat(...values: Array<string>): string` should be `concat(...values: Array<mixed>): string`

## Relevant documentation

According to the [MDN docs](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/concat) for the `concat()` method of the `String` built-in type: 

> If the arguments are not of the type string, they are converted to string values before concatenating.

Passing numbers, objects, etc to `String.prototype.concat` is is valid JS behavior but causes an error in Flow.

This is important because the alternative to String#concat is the `+` operator, but that operator is problematic because using `+` to concatenate a string to an object will cause `valueOf` to be called on the object before it's coerced to a string. Some types (notably the new ECMAScript ["Temporal"](https://github.com/tc39/proposal-temporal) date/time API that's currently in Stage 3) will [throw when `valueOf` is called](https://tc39.es/proposal-temporal/docs/plaindate.html#valueOf) so that users don't inadvertently use `<` or `>` to compare objects that have specialized comparison methods.

BTW, I discovered this Flow problem while fixing React's use of the `+` operator on strings and objects, because React was crashing and/or displaying confusing error messages when Temporal instances were rendered or used as props. This issue is causing https://github.com/facebook/react/pull/22064 to fail its Flow check.

PR coming!

**Comment by FezVrasta** [comment]
There are a lot of instances where Flow requires an actual string rather than letting JS implicitly cast it. I think it's a design decision.

You can always do `.concat(String(mixedThing))` to produce the same result.

**Comment by justingrant** [comment]
Yep, agree. Per @samwgoldman at https://github.com/facebook/react/pull/22064#issuecomment-900005558, this isn't a change that Flow is going to make, so I'm going to close this issue. Thanks!
