### ISSUE TITLE
Request for adding support for IBM Power Linux (ppc64le) platform

### ISSUE THREAD

**Issue by seth-priya** [facebook/flow#8732]
## Proposal
 Support the IBM Power Linux LE Platform (ppc64le) and provide binaries

## Use case
A number of node packages like csstype and others that are used in the Power ecosystem depend on flow-bin which does not work currently ad the ppc64le binary for flow is not available from the community

**Comment by seth-priya** [comment]
I have been able to build and run all the tests for flow on ppc64le (Fedora 24), attaching the logs for reference

only change needed was to extend this condition for "ppc64le" , 

[flow-test-logs.txt](https://github.com/facebook/flow/files/7019516/flow-test-logs.txt)
 https://github.com/facebook/flow/blob/main/Makefile#L315

**Comment by jbrown215** [comment]
cc @mroch
