### ISSUE TITLE
Closing connection 'server #1' due to uncaught exception in command loop: Unix.Unix_error(Unix.EPIPE, "write", "")

### ISSUE THREAD

**Issue by christianvuerings** [facebook/flow#8736]
We upgraded Flow from 0.152.0 to 0.158.0 and now we regularly see the server shutting down (every 10 to 15 minutes).

Flow version: 0.158.0
Node.js version: v14.15.4

## Expected behavior

No regular shut down of the Flow server

## Actual behavior

Flow occasionally shuts down, we see the following exception in the `monitor_log`:

```
Aug 24 14:47:45.353 [info] File watcher reported 7 files changed
Aug 24 14:51:14.121 [error] Closing connection 'server #1' due to uncaught exception in command loop: Unix.Unix_error(Unix.EPIPE, "write", "")
Aug 24 14:51:14.121 [error] backtrace:
Aug 24 14:51:14.121 [error] Raised by primitive operation at file "src/unix/lwt_unix.cppo.ml", line 710, characters 39-67
Aug 24 14:51:14.121 [error] Called from file "src/unix/lwt_unix.cppo.ml", line 562, characters 17-28
Aug 24 14:51:14.121 [error] 
Aug 24 14:51:14.186 [error] Flow server (pid 20710) was killed with sigsegv signal
Aug 24 14:51:14.186 [info] Monitor is exiting code -6 (Dying along with signaled server)
Aug 24 14:51:14.186 [info] Broadcasting to threads and waiting 1 second for them to exit
```

* Link to Try-Flow or Github repo: Not available - this is an internal only repo. I am just flagging the issue since

**Comment by dsainati1** [comment]
We have fixed a number of segfaults in version 158, but it's possible there are still a few around. If possible do you think you could isolate a repro that you would be able to link in the form of a Github repo?

**Comment by christianvuerings** [comment]
@dsainati1 is there a way to figure out what the root cause is when a segfault happens? Our codebase is +2 million lines of JS so it's tricky to know which file / import is causing the issue. Definitely willing to share a few files if we can pinpoint which ones cause the issue.

Also know that we ended up disabling `experimental.refactor` which fixed the following issues:

* The flow runs at 100% as soon as we save 1 file in VSCode.
* The `Getting code actions` never stopped

![Screen Shot 2021-08-24 at 9 04 43 AM](https://user-images.githubusercontent.com/127199/130650903-ed543a9e-b0c7-4560-b6ab-75e094b2a6a2.png)

![image](https://user-images.githubusercontent.com/127199/130650955-d90a3d26-d149-4196-af40-a1e1d61d23ba.png)

**Comment by dsainati1** [comment]
Does disabling `refactor` also fix the segfault?

**Comment by christianvuerings** [comment]
> Does disabling `refactor` also fix the segfault?

@dsainati1 So far, yes, we are no longer seeing the segfault after setting `experimental.refactor=false` in our flow config.

We will update this issue if we would end up seeing it again.
