### ISSUE TITLE
Please document  $Shape

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#875]

**Comment by avikchaudhuri** [comment]
Probably not. All Flow features that have a `$` prefix are understood to be experimental. In particular, the design of $Shape is not well-understood by even the authors: it's current implementation serves an immediate purpose, but we want to replace it with something else that's more generally useful and easily explainable.

**Comment by lll000111** [comment]
Is the explanation still true? The new documentation [on the type-casting page for example](https://flow.org/en/docs/types/casting/#type-cast-expression-syntax-a-classtoc-idtoc-type-cast-expression-syntax-hreftoc-type-cast-expression-syntaxa) at the very end points to a solution that uses `$Shape` in the return type as "correct solution". So is it official now? I have not found any documentation though.

**Comment by XaserAcheron** [comment]
The "`$` prefix means experimental" comment certainly seems out of date, unless we're really supposed to believe that all but two of the publicly documented utility types are experimental. :P

At any rate, +1 to documenting $Shape. It's now saving me a lot of headaches regarding object factories (see #5470), and I wish I'd known about it sooner.

**Comment by reyronald** [comment]
Just commenting to see if we can revive this issue. Just bumped into $Shape by literally reading the source code and it happened to be exactly what I was needing.

**Comment by arsnl** [comment]
Good... 2018 and `$Shape` still "experimental" when `Partial` is common in TypeScript.
