### ISSUE TITLE
name-already-bound error defining variables in switch case

### ISSUE THREAD

**Issue by grit96** [facebook/flow#8758]
Flow version: discovered in 0.149.0 and reproduced in 0.161.0

## Expected behavior

Constants defined in different switch cases that have a return or break shouldn't result in `name-already-bound` error.

## Actual behavior

Constants defined in different switch cases do result in `name-already-bound` error.

```js
function fun(action, state) {
  switch (action.type) {
  case 1:
    const foo = 'bar';
    return {...state, foo};
  case 2:
    const foo = 'baz';
    return {...state, foo};
  default:
    return state;
  }
};
```

```
7:     const foo = 'baz';
             ^ Cannot declare `foo` [1] because the name is already bound. [name-already-bound]
References:
4:     const foo = 'bar';
             ^ [1]
```

Link to Try-Flow or Github repo:

https://flow.org/try/#0GYVwdgxgLglg9mABKMAKAhteYA0iDOU6UApgJSIDeAUIgQO4xQQAWiGWCAdFAJ4AO5KrUQR0+EogCMALhF0ICQsjhxEAXkQByAEboATloDc8xPpJQQ+pJS53CxEnmCqAviYXjJAJjl0FSlAqapq66ABexqbmltZUdlwOpM5uHogAJiTA6CAANlB+-jFWSEkkaa7U7kA

**Comment by mroch** [comment]
the whole switch statement is one lexical scope, so you can't declare the same const (or let) in different cases. it also fails in Chrome:
<img width="478" alt="Screen Shot 2021-10-04 at 10 09 02 AM" src="https://user-images.githubusercontent.com/3012/135866253-777bcbf3-8d60-45ef-a1de-8ef0d777d1d7.png">

however, you can create lexical scopes using blocks (`{ }`) like this: 
```
  case 1: {
    const foo = 'bar';
    return {...state, foo};
  }
  case 2: {
    const foo = 'baz';
    return {...state, foo};
  }
```
https://flow.org/try/#0GYVwdgxgLglg9mABKMAKAhteYA0iDOU6UApgJSIDeAUIgQO4xQQAWiGWCAdFAJ4AO5KrUQR0+EogCMALmF06EBIWRw4iALyIA5ACN0AJ20BuEXQMkoIA0kpd7hYiTzA1AX1N03IsRMQAmORoFUWUoVXUtPXQALxMzRAsrGyp7LkdSF3dPRG86ABMSYHQQABsoGQSk6yQMkhzvDyA

**Comment by grit96** [comment]
@mroch Interesting - I didn't know that. Thanks for the info!
