### ISSUE TITLE
Untyped modules no longer possible to be used (implicit 'any')?

### ISSUE THREAD

**Issue by pulli23** [facebook/flow#8759]
Flow version: 0.161.0

## Expected behavior

When importing a module that has no typing defined we would still like to properly "type" the names, in the 'hopes', 'preparation' of said module to get fully typed.  Even if flow has to consider those types as `any` - This worked prior to version 0.161.0 and isn't documented to change.

## Actual behavior

Importing any module without flow definitions results in an error alike:

```
Error:(16, 14) Importing a type from an untyped module makes it `any` and is not safe! Did you mean to add `// @flow` to the top of `mobx`?
```

Is it possible to suppress this warning/error?

* Link to Try-Flow or Github repo:

**Comment by gkz** [comment]
We found that the cost of people unintentionally importing types not realizing they were `any` outweighed any theoretical benefit. You can add a flowfixme above the import if you wish, e.g. `// $FlowFixMe[untyped-type-import]`

**Comment by pulli23** [comment]
While I appreciate the choice, it still doesn't really work:
```
import {observable} from "mobx";
// $FlowFixMe[untyped-type-import]
import type {ObservableMap} from "mobx";

const myMap: ObservableMap = observable(new Map());
```

Results in the error like:

```
Cannot use `ObservableMap` as a type because it is an `any`-typed value. Type `ObservableMap` properly, so it is no longer `any`-typed, to use it as an annotation.
```

Would I have to add a flow fix me statemetn for each declaration using the types?

**Comment by gkz** [comment]
It doesn't really make sense to use `ObservableMap` as a type - it really is just `any`. It's completely meaningless to Flow. My recommendation would not to do this at all. If you really want to you can add `$FlowFixMe`s where appropriate. Or better yet, add some types to whatever you are importing. It's better to have some minimal types with a bunch of `$FlowFixMe`s and `any`s than to not have Flow enabled at all for a file.
