### ISSUE TITLE
Propname havoc forgotten after conditional or loop

### ISSUE THREAD

**Issue by gnprice** [facebook/flow#8777]
Flow version: v0.163.0

## Expected behavior
After a refinement is invalidated ("havoced", as the code calls it) by writing to a property, it should stay invalidated wherever the control flow can reach from there (unless it gets refined again.)

## Actual behavior
When the invalidation happens in certain conditional or loop contexts, it gets forgotten after the conditional or loop is complete.  This is unsound.

In particular we can write `coerce`.  For example with `if`:
```js
const v: { f?: mixed } = {};
const vv = v;
function coerce<A, B>(x: A): B {
  v.f = () => { throw null };  // Refine v.f.
  if (true) {
    vv.f = () => x;  // Invalidate the refinement.
  }
  return v.f(); // Should error!  Trying to still use the refinement.
}
```

Other cases ([try](https://flow.org/try/#0PTAEHUCcEsBcFNQGMD29JMQVwM7QHYDmoAhqAGYqSEqwL6gAOkKj+JAttvpPOQfC75YAOgBQY1PhyxQANwBcoAN4UA-Eo7QAHvAAmoAL6gAvCsMBuSSmmy5c0-Kvks+JLGg3kaDPAA8AIIANKAAQgB8ABTaSgEAlEqhKmKg8iLkjpFxpuEqoLAAFiwA7qD4WAA2FUYWqSCgAEp8Amnk4qnQGZGwkFjw2copqfJy6ZnZJrnataD1AJL4ciQV0HokCPkFiLz8+ILwwu1GQ7ywWJAMo+RZtfUAygUolQboLJAAhKkAKpAAngTEWAoUAyaBVUC4RCFbbNPZCURiQwSMT1AAighsMkg60QZCWMHgsF+oBQGVoW0gyBIOHgOHEYiJjEQAUcygARhoVEglGyUCgKvASPhDJYxHp4EgKiRePJpaAYnkOUpVCJVUYamKJVKZfimDy+QKhVZxZLpYhdb9laBVSJ1QAyUBzBDYoGQPxaXR6cJWSIkWITXKDOpgAAS6HgAHIcKQGK8qCEyDsBPDNusKDpaaA4EEhvUhQYyMUYBtUJBeO4KsSCEsVmsPERNjDdvtDkNOqBfSI2dlhr2+-2B4PUiQuyIkDNZmAUABrNtdEfdvLaLuOX4Tocb4YLse1Yz1OOQEI0FB6CTB0Bh3hRkEoLhUmnR4oUqFbLOLZardaeBiEQnRyjULQ9BHO2naLqoPR9KAdoOtEK5mL8cTrpu27juq9RfAA8qimGgAec4dguAxMKAagdsubKrtkSgAAzIRuqG7pOoBYTheFllQBFgcRoGMNkFGrvRm6kKOaF7mArG4fhHTzl2PFdHxtTwBUNLyvBoBrsJjHoRJ2FSRxkBcUReQ4MUcBIAUHZ8XkSDUlCvTwEoAkIUxA7aeJLF6exbxnqAAqyNAVgyYRcl5E+YKIJE1nORpQmDu5zGSd5nHBdxeQAR2tSMBY-HqZpwkiWyO46Z5bHSVmsngRQVCZUwtQxYhcX9glGFeeVoHGaoGWRNAb4abllEuVpolMa1ZUGUZoVdTVPV9Q1SEFYVxUeUl7WVcR3W9aS-VqYNsXDUVYmJW1E2pZ11WUrN23zU1fYtbp40+UiQA)) include where the invalidation happens inside a short-circuiting operator, the ternary operator, or a switch, while, for, for-in, or for-of statement.

## Discussion
I discovered this from reading the code while debugging #8251. The symptoms are similar, but with the unrefinement coming from a property write rather than a function call. The fix turns out to also be separate (though related), so filing it as a separate issue.

* Link to Try-Flow or Github repo: [here](https://flow.org/try/#0PTAEHUCcEsBcFNQGMD29JMQVwM7QHYDmoAhqAGYqSEqwL6gAOkKj+JAttvpPOQfC75YAOgBQY1PhyxQANwBcoAN4UA-Eo7QAHvAAmoAL6gAvCsMBuSSmmy5c0-Kvks+JLGg3kaDPAA8AIIANKAAQgB8ABTaSgEAlEqhKmKg8iLkjpFxpuEqoLAAFiwA7qD4WAA2FUYWqSCgAEp8Amnk4qnQGZGwkFjw2copqfJy6ZnZJrnataD1AJL4ciQV0HokCPkFiLz8+ILwwu1GQ7ywWJAMo+RZtfUAygUolQboLJAAhKkAKpAAngTEWAoUAyaBVUC4RCFbbNPZCURiQwSMT1AAighsMkg60QZCWMHgsF+oBQGVoW0gyBIOHgOHEYiJjEQAUcygARhoVEglGyUCgKvASPhDJYxHp4EgKiRePJpaAYnkOUpVCJVUYamKJVKZfimDy+QKhVZxZLpYhdb9laBVSJ1QAyUBzBDYoGQPxaXR6cJWSIkWITXKDOpgAAS6HgAHIcKQGK8qCEyDsBPDNusKDpaaA4EEhvUhQYyMUYBtUJBeO4KsSCEsVmsPERNjDdvtDkNOqBfSI2dlhr2+-2B4PUiQuyIkDNZmAUABrNtdEfdvLaLuOX4Tocb4YLse1Yz1OOQEI0FB6CTB0Bh3hRkEoLhUmnR4oUqFbLOLZardaeBiEQnRyjULQ9BHO2naLqoPR9KAdoOtEK5mL8cTrpu27juq9RfAA8qimGgAec4dguAxMKAagdsubKrtkSgAAzIRuqG7pOoBYTheFllQBFgcRoGMNkFGrvRm6kKOaF7mArG4fhHTzl2PFdHxtTwBUNLyvBoBrsJjHoRJ2FSRxkBcUReQ4MUcBIAUHZ8XkSDUlCvTwEoAkIUxA7aeJLF6exbxnqAAqyNAVgyYRcl5E+YKIJE1nORpQmDu5zGSd5nHBdxeQAR2tSMBY-HqZpwkiWyO46Z5bHSVmsngRQVCZUwtQxYhcX9glGFeeVoHGaoGWRNAb4abllEuVpolMa1ZUGUZoVdTVPV9Q1SEFYVxUeUl7WVcR3W9aS-VqYNsXDUVYmJW1E2pZ11WUrN23zU1fYtbp40+UiQA)

**Comment by SamChou19815** [comment]
All of the issues should be fixed since we enabled `inference_mode=constrain_writes` by default.
