### ISSUE TITLE
Havoc forgotten after while, for-in, or for-of

### ISSUE THREAD

**Issue by gnprice** [facebook/flow#8778]
Flow version: v0.163.0

## Expected behavior
After a refinement is invalidated ("havoced"), in particular by a function call or a write to a property, it should stay invalidated wherever the control flow can reach from there (unless it gets refined again.)

## Actual behavior
When the invalidation happens in the body of a while, or the body or right-hand side of a for-in or for-of, it gets forgotten after the loop is complete.  This is unsound.

In particular we can write `coerce`.  For example, using for-of:
```js
const v: { f?: mixed } = {};

function store(x: mixed) {
  v.f = () => x;
};

function coerce<A, B>(x: A): B {
  v.f = () => { throw null };  // Refine v.f.
  for (const i of [0]) {
    store(x);  // Invalidate the refinement.
  }
  return v.f(); // Should error!  Trying to still use the refinement.
}
```

More cases ([tryflow](https://flow.org/try/#0PTAEHUCcEsBcFNQGMD29JMQVwM7QHYDmoAhqAGYqSEqwL6hb6TzkHwC28+sAdAFD9U+HLFAA3AFygA3hQD80jtAAe8ACagAvqAC8srQG5B5JkljQUDUVXgAKFUtUaAlLP6gJvcntB23ugB8oCrGRiZmFlbIaBjwADwAggA0oABCgQ7SiS7Sae6e4t6+-nrBcrAAFpAoAO6g+FgANk3ahp4goABKrOxe5AKelJB+wqKg0KAoPgDaAAwAum4yHp6gNiwOLu2gnQCS+OIkTdDqJAigVYgsbPic3HyrWqsssFiQDEXk-u2dAMqVFDNTToGqQACEngAKpAAJ4EYiwFDrCwtRg4RBXUA3dhcHgCZ6CToAEU4VlEkHOiDIRxg8FgsKmPlolXQyBIGJwAn4DIADohEr4ZAAjRSyJDSYUoFBNeAkfBacLqeBIJokFgSdUhaRyUU60C8Q3aNr8ZWq9WIWmgXmS6Wy+XGM1qjVW2H6w28Y0AMlAewQlKRkHiyjU6kCjpVzstWvITlDZVkBqNOh9fvQ5yowecYeM-DsJGyAXKq06AAl0PAAOQ4UgMUFUVJkHF3PFiKrnCjOGtwZIlsDyzRkUz4cyWBhIY6tVCQFjmJqMghHE5nCxES6s7G9FsPQYTHx2ACMbjWJ9PZ-PF5PJF4wt4SB2uzA9cgq2g++vwuPl+-P6vN7vD6dCgADWr7vjeywUD8v4wX+t73sanTPoIniymI0DGB0YDliw1brCgXDspyoC1KyGpYouxynOcY6gIQ9I1sMNB0Nwu6dKR0CyoAZARgX4H6QRxsp+LybjfNssGnh+AGIWAUIAPLEnJoDIZ4b58RBiaCYgdgiYmYntMIq5YPA7Q6HB0k6J08mKcpM5UH2oBcRQVAALQEDxqngZ+elUH4kwEKAsKidBElSQhlmyQpSkqXu6neXIwx+RMDBieJEmeGFpmPqA1nRXZL6eXFkGJXY-kMEFenQYZBDGVlpD-uF2W5bZYK8fmGkJb5pXJVBLhuNVjQmZemUyTlUUtfZhXtfFzkjN1AWpZubwfA+F4jRFY02TFnROcMLnTLuanTcVXWTNMgXBWlsHrU140xUd-E+XNZ0+Klq3XQ1WVWXd+VtY9nXPUyF2VeJA21ca9XwV9kVbb9U3-bNSXnYtYNDWtn2jc191eSdgPI-4bivO8+DvWeN3fbDrXPEAA)):
```js
type A = {b?: {c: boolean}};
declare var x: { b?: { ... } };
declare var p: boolean;
declare var y: { ... } & Iterator<mixed>;
declare var f: mixed => { ... } & Iterator<mixed>;

(a: A) => {
  // Here's an error, a refinement that fixes it,
  // and a function call correctly invalidating the refinement.
  if (1)                                      a.b.c;   // error
  if (a.b)                                    a.b.c;   // ok
  if (a.b) { f();                             a.b.c; } // error

  let i;
  // Here's some cases where the invalidation gets forgotten.
  // while…
  if (a.b) { while (p) f();                   a.b.c; } // TODO error
  if (a.b) { while (p) { f(); continue; }     a.b.c; } // TODO error
  // … for-in…
  if (a.b) { for (i in y) f();                a.b.c; } // TODO error
  if (a.b) { for (i in f());                  a.b.c; } // TODO error
  if (a.b) { for (i in y) { f(); continue; }  a.b.c; } // TODO error
  if (a.b) { for (i in f()) continue;         a.b.c; } // TODO error
  if (a.b) { for (i in f()) return;           a.b.c; } // TODO error
  // … for-of.
  if (a.b) { for (i of y) f();                a.b.c; } // TODO error
  if (a.b) { for (i of f());                  a.b.c; } // TODO error
  if (a.b) { for (i of y) { f(); continue; }  a.b.c; } // TODO error
  if (a.b) { for (i of f()) continue;         a.b.c; } // TODO error
  if (a.b) { for (i of f()) return;           a.b.c; } // TODO error
}
```

## Discussion
I discovered this from test cases I wrote for my fix to #8251, and the symptoms are similar to #8251 or #8777. But fixing those bugs turns out not to fix these cases, and a completely separate fix is needed here.

* Link to Try-Flow or Github repo: [here](https://flow.org/try/#0PTAEHUCcEsBcFNQGMD29JMQVwM7QHYDmoAhqAGYqSEqwL6hb6TzkHwC28+sAdAFD9U+HLFAA3AFygA3hQD80jtAAe8ACagAvqAC8srQG5B5JkljQUDUVXgAKFUtUaAlLP6gJvcntB23ugB8oCrGRiZmFlbIaBjwADwAggA0oABCgQ7SiS7Sae6e4t6+-nrBcrAAFpAoAO6g+FgANk3ahp4goABKrOxe5AKelJB+wqKg0KAoPgDaAAwAum4yHp6gNiwOLu2gnQCS+OIkTdDqJAigVYgsbPic3HyrWqsssFiQDEXk-u2dAMqVFDNTToGqQACEngAKpAAJ4EYiwFDrCwtRg4RBXUA3dhcHgCZ6CToAEU4VlEkHOiDIRxg8FgsKmPlolXQyBIGJwAn4DIADohEr4ZAAjRSyJDSYUoFBNeAkfBacLqeBIJokFgSdUhaRyUU60C8Q3aNr8ZWq9WIWmgXmS6Wy+XGM1qjVW2H6w28Y0AMlAewQlKRkHiyjU6kCjpVzstWvITlDZVkBqNOh9fvQ5yowecYeM-DsJGyAXKq06AAl0PAAOQ4UgMUFUVJkHF3PFiKrnCjOGtwZIlsDyzRkUz4cyWBhIY6tVCQFjmJqMghHE5nCxES6s7G9FsPQYTHx2ACMbjWJ9PZ-PF5PJF4wt4SB2uzA9cgq2g++vwuPl+-P6vN7vD6dCgADWr7vjeywUD8v4wX+t73sanTPoIniymI0DGB0YDliw1brCgXDspyoC1KyGpYouxynOcY6gIQ9I1sMNB0Nwu6dKR0CyoAZARgX4H6QRxsp+LybjfNssGnh+AGIWAUIAPLEnJoDIZ4b58RBiaCYgdgiYmYntMIq5YPA7Q6HB0k6J08mKcpM5UH2oBcRQVAALQEDxqngZ+elUH4kwEKAsKidBElSQhlmyQpSkqXu6neXIwx+RMDBieJEmeGFpmPqA1nRXZL6eXFkGJXY-kMEFenQYZBDGVlpD-uF2W5bZYK8fmGkJb5pXJVBLhuNVjQmZemUyTlUUtfZhXtfFzkjN1AWpZubwfA+F4jRFY02TFnROcMLnTLuanTcVXWTNMgXBWlsHrU140xUd-E+XNZ0+Klq3XQ1WVWXd+VtY9nXPUyF2VeJA21ca9XwV9kVbb9U3-bNSXnYtYNDWtn2jc191eSdgPI-4bivO8+DvWeN3fbDrXPEAA)

**Comment by SamChou19815** [comment]
All of the issues should be fixed since we enabled `inference_mode=constrain_writes` by default.
