### ISSUE TITLE
Havoc forgotten after for-loops and do-while loops

### ISSUE THREAD

**Issue by gnprice** [facebook/flow#8779]
Flow version: v0.163.0

## Expected behavior
After a refinement is invalidated ("havoced"), in particular by a function call or a write to a property, it should stay invalidated wherever the control flow can reach from there (unless it gets refined again.)

## Actual behavior
When the invalidation happens in the body or update-expression of a for-loop, or the body or test of a do-while loop, or a block with a labelled break, it can get forgotten after the loop is complete.  This is unsound.

In particular we can write `coerce`.  For example, using a `for` body:
```js
const v: { f?: mixed } = {};

function store(x: mixed) {
  v.f = () => x;
};

function coerce<A, B>(x: A): B {
  v.f = () => { throw null };  // Refine v.f.
  for (let i = 0; i < 1; i++) {
    store(x);  // Invalidate the refinement.
  }
  return v.f(); // Should error!  Trying to still use the refinement.
}
```

More cases ([tryflow](https://flow.org/try/#0PTAEHUCcEsBcFNQGMD29JMQVwM7QHYDmoAhqAGYqSEqwL6hb6TzkHwC28+sAdAFD9U+HLFAA3AFygA3hQD80jtAAe8ACagAvqAC8srQG5B5JkljQUDUVXgAKFUtUaAlLP6gJvcntB23ugB8oCrGRiZmFlbIaBjwADwAggA0oABCgQ7SiS7Sae6e4t6+-nrBcrAAFpAoAO6g+FgANk3ahp4goABKrOxe5AKelJB+TfBi0L4ADO2T8aAAjLMA1MtuMh6eoDYsDi7toJ0AkvjiJE3Q6iQIoFWILGz4nNx8m1qbLLBYkAxF5P7tToAZUqKGamnQNUgAEJPAAVSAATwIxFgKG2FhajBwiDuoAe7C4PAE70EnQAIpwrKJINdEGQzjBxojQCgfLRKuhkCQcTgBPxYIiAA6IRK+GQAI0UsiQ0glKBQYxI+C04XU8CQTRILAk2pC0jkUoNoF4pu0bX46s12sQjNAQrlCqV+GMVq1OrtiONpt45oAZKAjghaWjIPFlGp1IFXRr3ba9eQnJGyrITWadAGg+hrlRw84o8Z+HYSNkAuVNp0ABLoeAAchwpAYkKoqTIBKeRLEVWuFGcDbgyQrYGVmjIpnw5ksDCQ51aqEgLHMTRZBDOFyuFiIt05+N6HZeg1A0B8dgWbi2F8vV+vN4vJF4Et4SAOhzAzcgm2PfnvEvPt--AF3g+T4vp0KAANafieP7rBQAKAQhQGPs+5qdO+gieGMEzGB0YDViw9bbCgXDcryoC1JyOp4qu5yXNcU6gIQ4wNsMNB0Nwh6dMMgBkBFB34PrBwx+O0QrtP8Lj7IhSEgahYBwgA8uS8mgOhnhfsWAmpkJdgiYYbjiS+Uk-jJOidApSkqQuVBDqA3GgOoKAALQUdAYy8Wp0GaXIDlafBwiblg8DtDoLljH4QqScZKGmXJinKapR6eb+qY+XIBmgBKLAkOBhkhZUrmIHYEXtFFwWvqA5nxVZH4efxyXeeicj+QQgVlaFhXiZJWylbJFVxZZUI2XZWoSvALQaBlWXgYe6kwamTTGulmXwNloBNGVgE9TFfUWeh7xAA)):
```js
type A = {b?: {c: boolean}};
declare var x: { b?: { ... } };
declare var p: boolean;
declare var y: { ... } & Iterator<mixed>;
declare var f: mixed => { ... } & Iterator<mixed>;

(a: A) => {
  // Here's an error, a refinement that fixes it,
  // and a function call correctly invalidating the refinement.
  if (1)                                      a.b.c;   // error
  if (a.b)                                    a.b.c;   // ok
  if (a.b) { f();                             a.b.c; } // error

  let i;
  // Here's some cases where the invalidation gets forgotten.
  // for…
  if (a.b) { for (; p; f());                  a.b.c; } // TODO error
  if (a.b) { for (; p;) f();                  a.b.c; } // TODO error
  // … do-while…
  if (a.b) { do { f(); continue; } while (p); a.b.c; } // TODO error
  if (a.b) { do { f(); break;    } while (p); a.b.c; } // TODO error
  if (a.b) { do { continue; } while (f());    a.b.c; } // TODO error
  // … labelled break.
  if (a.b) { l: { f(); break l; }             a.b.c; } // TODO error
}
```

## Discussion
I discovered this from writing test cases for my fix to #8251, and the symptom looks a lot like #8251, #8777, or #8778.  But fixing all three of those bugs leaves this one still outstanding. I haven't succeeded in debugging what's causing this one.

* Link to Try-Flow or Github repo: [here](https://flow.org/try/#0PTAEHUCcEsBcFNQGMD29JMQVwM7QHYDmoAhqAGYqSEqwL6hb6TzkHwC28+sAdAFD9U+HLFAA3AFygA3hQD80jtAAe8ACagAvqAC8srQG5B5JkljQUDUVXgAKFUtUaAlLP6gJvcntB23ugB8oCrGRiZmFlbIaBjwADwAggA0oABCgQ7SiS7Sae6e4t6+-nrBcrAAFpAoAO6g+FgANk3ahp4goABKrOxe5AKelJB+TfBi0L4ADO2T8aAAjLMA1MtuMh6eoDYsDi7toJ0AkvjiJE3Q6iQIoFWILGz4nNx8m1qbLLBYkAxF5P7tToAZUqKGamnQNUgAEJPAAVSAATwIxFgKG2FhajBwiDuoAe7C4PAE70EnQAIpwrKJINdEGQzjBxojQCgfLRKuhkCQcTgBPxYIiAA6IRK+GQAI0UsiQ0glKBQYxI+C04XU8CQTRILAk2pC0jkUoNoF4pu0bX46s12sQjNAQrlCqV+GMVq1OrtiONpt45oAZKAjghaWjIPFlGp1IFXRr3ba9eQnJGyrITWadAGg+hrlRw84o8Z+HYSNkAuVNp0ABLoeAAchwpAYkKoqTIBKeRLEVWuFGcDbgyQrYGVmjIpnw5ksDCQ51aqEgLHMTRZBDOFyuFiIt05+N6HZeg1A0B8dgWbi2F8vV+vN4vJF4Et4SAOhzAzcgm2PfnvEvPt--AF3g+T4vp0KAANafieP7rBQAKAQhQGPs+5qdO+gieGMEzGB0YDViw9bbCgXDcryoC1JyOp4qu5yXNcU6gIQ4wNsMNB0Nwh6dMMgBkBFB34PrBwx+O0QrtP8Lj7IhSEgahYBwgA8uS8mgOhnhfsWAmpkJdgiYYbjiS+Uk-jJOidApSkqQuVBDqA3GgOoKAALQUdAYy8Wp0GaXIDlafBwiblg8DtDoLljH4QqScZKGmXJinKapR6eb+qY+XIBmgBKLAkOBhkhZUrmIHYEXtFFwWvqA5nxVZH4efxyXeeicj+QQgVlaFhXiZJWylbJFVxZZUI2XZWoSvALQaBlWXgYe6kwamTTGulmXwNloBNGVgE9TFfUWeh7xAA)

**Comment by SamChou19815** [comment]
All of the issues should be fixed since we enabled `inference_mode=constrain_writes` by default.
