### ISSUE TITLE
replace-existentials codemod always errors

### ISSUE THREAD

**Issue by lyleunderwood** [facebook/flow#8782]
Flow version: 0.162.1

## Expected behavior

`flow codemod replace-existentials` functions without error.

## Actual behavior

I've tried this codemod on multiple machines and had other developers try it, and always get the same error:

```
$ cat /etc/lsb-release 
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=20.04
DISTRIB_CODENAME=focal
DISTRIB_DESCRIPTION="Ubuntu 20.04.3 LTS"

$ ./node_modules/.bin/flow version
Flow, a static type checker for JavaScript, version 0.162.1

$ ./node_modules/.bin/flow codemod replace-existentials
Unhandled exception: (Failure hd)
Raised at file "stdlib.ml", line 29, characters 17-33
Called from file "list.ml", line 30, characters 10-23
Called from file "src/commands/commandUtils.ml", line 13, characters 4-32
```

**Comment by gnprice** [comment]
Indeed, I reproduce.

I've just sent a fix as #8783. But the debugging that led to that fix also gives the following workaround.

When you see that traceback, pretend that it was instead an error message reading:
> Error: filenames or --input-file are required

(The filenames can be directories, so `flow codemod replace-existentials --write .` may be the whole command you need.)

When I try that in a small test repo, the actual codemod works great:
```diff
-const x: * = 3;
+const x: number = 3;
```
