### ISSUE TITLE
Autoimport will import an extra line when importing on an existing line

### ISSUE THREAD

**Issue by Brianzchen** [facebook/flow#8785]
Flow version: 0.164.0

## Expected behavior
It shouldn't add a new line and when I press enter it should just autocomplete what I'm typing
![ezgif-4-14703bf7eb4b](https://user-images.githubusercontent.com/12436524/141226162-2257b40e-196d-4f38-bc09-d4ac67bc5759.gif)

**Comment by mroch** [comment]
fixed in 6478fd60a858b716170415173ecfc5917a894279 (0.192.0)!
