### ISSUE TITLE
Type signature for object resulting in the merge of two others

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#879]
Hi! I'm currently trying to add types to the redux library here: https://github.com/rackt/redux/pull/817.

I've stumbled with a limitation trying to type check the following funcion: https://github.com/rackt/redux/pull/817/files#diff-bbee70eeb9acc231aa3ecbc538908a44R36
```js
...
// TODO: Cannot make this to correctly type check that the resulting props match
// the Counter prop types
export default connect(mapStateToProps, mapDispatchToProps)(Counter);
```

which is defined in the following module declaration: https://github.com/rackt/redux/pull/817/files#diff-1f87b84a5891d39a04a6e9197b9cd896R8.
```js
...
declare type MapStateToProps<State, Props> = (state: State) => Props;
declare type MapDispatchToProps<Dispatchable, Props> = (dispatch: Dispatch<Dispatchable>) => Props;

declare function connect<State, Dispatchable, ComponentProps, DefaultProps, ComponentState, StateProps, DispatchProps: $Diff<ComponentProps, StateProps>>(
  mapStateToProps: MapStateToProps<State, StateProps>,
  mapDispatchToProps: MapDispatchToProps<Dispatchable, DispatchProps>
) : (component: Component<DefaultProps, ComponentProps, ComponentState>) => Component<DefaultProps, ComponentProps, ComponentState>;
```

The function in this case accepts two function arguments. The first one takes an argument of type `State` and returns another type `StateProps`. The second one takes a function, `dispatch`, and returns another object of type `DispatchProps`. The `connect` function returns another function that accepts a React component, and I want to enforce that the props type of that component be the type resulting of the _merge_ between `StateProps` and `DispatchProps`.

As you can see in the type definition above, I've tried using the internal `$Diff` type, but with no luck. I can make StateProps and DispatchProps be whatever I want and flow will still not raise any type errors.

Is there a way to do this type checking with Flow? If not, are there any plans on adding this in the future?

Thanks for your attention, and sorry if the example is quite cumbersome (probably there is a way simpler example to showcase what I'm trying to do)

**Comment by leoasis** [comment]
Finally made it work here: https://github.com/rackt/redux/pull/817/files#r41014938. Ultimately the problem was not the `$Diff` type (it works correctly it seems), but the `Component` type, which was not the correct one to use. Changing it to `ReactClass` made it type check correctly.

In any case, leaving this open to ask if there are any plans or making `$Diff` or something similar part of the public API in a future release, as it is quite handy (since merging objects is quite a normal operation in JS).

**Comment by samwgoldman** [comment]
Hi @leoasis. I'm glad you figured out the issue. The `$`-prefixed types are explicitly private, as their behavior is often subtle, has not been thoroughly generalized. We might add a `$`-prefixed type to push something through in the short term while we work to devise a fully general solution—The `react` module libdefs fall under this category, broadly.

I am keenly interested in making finalized and public, documented versions of necessary "use case" types, but have no short term plans to do so.

Does that answer your question?

**Comment by leoasis** [comment]
Definitely, good to hear it is on the roadmap then. So then consider the referenced PR for the `redux` lib as an extra use case for this yet-internal type! Will be using it for now, until something more stable (and public) comes up.
