### ISSUE TITLE
False negative on coverage for hoisted calls appearing below return statements

### ISSUE THREAD

**Issue by traviskaufman** [facebook/flow#8790]
Flow version: master

## Expected behavior

Given the following code in a file named `test.js`:

```js
/** @flow strict-local */

exec('hi');
exec(null);

function exec(a: ?string): number {
  f(a);

  return Math.random();

  function f(a: ?string): void {
    if (shouldDoSomethingWith(a)) {
      console.log('do something');
    } else {
      console.log('do nothing');
    }
  }

  function shouldDoSomethingWith(a: ?string): boolean {
    if (a == null) {
      return false;
    }
    return a.startsWith('do');
  }
}
```

This should report 100% coverage when run with `flow coverage test.js`

## Actual behavior

Flow reports the line `shouldDoSomethingWith(a)` as uncovered, _unless_:

- You **remove the return statement**
- You **move the return statement to the last line**
- You place the declaration for `shouldDoSomethingWith` _above_ `f`

![image](https://user-images.githubusercontent.com/1185269/142658951-ecf3fc37-125e-4faa-9221-41796e12d008.png)

I'm not sure if this is intended behavior, but it seems strange that order of hoisted functions or whether or not there's a return statement dictates coverage. Let me know how I can help further! 

* Link to Try-Flow or Github repo: https://flow.org/try/#0PQKhAIAEDMBsHsDu4DOAXATgSwMZoLQI4CGs4IwAUJQKYAeNOAFAOQAWWLAlANy0PMAdgFdYsXtWjDBeLPEHh6jJsQBc4APzpsggOZd1IgLYAjGhnABvSuHDQVEm+Aw00wjAoCyxNGwB0GMSCACbwRkyOtlIyaHIK9mqa2lh6BuAAbvBYwVZOtljQ4EwobPCiwQAi8ADKYa4cegDqWL4OXLm2neA48ijwsDR+CLqsoah1vim63HxdAL6KsCg0HV3dvf2Dw6Pw4ILwk3ozeeBzTmdO0bLyqKXlVbVG9VPNrYlamFNpJvCbQav5QoqcAAXhBe1E4gBnRcbg8dlIy1mnTOXVh7gUxD86GIGDQKFebB2x1sZzOQA

NOTE: the best way to repro this is to copy it into an editor as a `test.js` file and run `flow coverage --color test.js` and see the line that gets reported.

**Comment by mvitousek** [comment]
Thanks for the report--this and similar issues will be fixed by some of the changes to the environment that @jbrown215 is currently working on, as a part of the larger local type inference project (https://medium.com/flow-type/introducing-local-type-inference-for-flow-6af65b7830aa)

**Comment by SamChou19815** [comment]
This is now fixed.
