### ISSUE TITLE
Flow issues "Unexpected identifier, expected the token `;`" after the token await. Bug or unsupported feature?

### ISSUE THREAD

**Issue by rafasanmartinez** [facebook/flow#8792]
Flow version: 0.165.1

## Expected behavior
According to my understanding, Flow should just should not issue the error in the title. It seems like it does not recognize the `await` token. It might be a bug in my code either, but after doing some research, I would humbly dare to say that it is not the case.

## Actual behavior
Flow issues an `Unexpected identifier, expected the token ";"` error after the token `await`

## Proposal
Flow should provide support for `await`.

The use for the sugar syntax `await` is extremely useful, and I cannot use Flow for my applications if it does not support it. The use of `await` is very extended at this time. 

## Use case
You can see the problem in  [Link to Try-Flow](https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoA1pqgFygDOyATgJYB2A5gDSgBuAhtAK6ZqdJmwC+AbkSIAxrGZ1QPSnkJFEoMhWoByHjvYbufQbv2JJ0uQuShIsWAVAAKAJSUACvVgBbRjUwAHhwAPgIw9QBIekxkfnpmUGZMeFAvX39MZ0h+ZhlkRnlnGJpYaC5MThiAK0x813VNTUiA5AAVRh9MWH5kbNz8wuY3Rqax6MxS8qyeVykxsbFOAEYABnW5o00xTbEreUUAIx56Jzdw4kRI60UsLCceeB5GW3tYNykJuISk-mhoKRiIA)

**Comment by ChrisRast** [comment]
You're missing an `async` statement at ligne 17.

https://flow.org/try/#0PTAEAEDMBsHsHcBQAXAngBwKagIKgLygDeoA1pqgFygDOyATgJYB2A5gDSgBuAhtAK6ZqdJmwC+AbkSIAxrGZ1QPSnkJFEoMhWoByHjvYbufQbv2JJ0uQuShIsWAVAAKAJSUACvVgBbRjUwAHhwAPgIw9QBIekxkfnpmUGZMeFAvX39MZ0h+ZhlkRnlnGJpYaC5MThiAK0x813VNTUiA5AAVRh9MWH5kbNz8wuY3Rqax6MxS8qyeVykxsbFOAEYABnW5o00xTbEreUUAIx56Jx4aVDyXV3DiREjrRSwsM-geRlt7WDcpCbiEpL8aDQKRiIA

**Comment by rafasanmartinez** [comment]
ooops...thank you @ChrisRast , and sorry for the inconveniences.
