### ISSUE TITLE
flow-parser: syntax error for `declare var x` without types

### ISSUE THREAD

**Issue by sosukesuzuki** [facebook/flow#8794]
Flow version: 0.165.1

## Reproduce

```js
const { parse } = require("flow-parser");

const code = `declare var x;`;

const result = parse(code);
console.log(JSON.stringify(result.errors, null, 2));
```

## Expected behavior

No errors.

(flow-parser 0.164.0 outputs like this)

```json
[]
```

## Actual behavior

```json
[
  {
    "loc": {
      "source": null,
      "start": {
        "line": 1,
        "column": 13
      },
      "end": {
        "line": 1,
        "column": 14
      }
    },
    "message": "Unexpected token `;`, expected the token `:`"
  },
  {
    "loc": {
      "source": null,
      "start": {
        "line": 1,
        "column": 14
      },
      "end": {
        "line": 1,
        "column": 14
      }
    },
    "message": "Unexpected end of input"
  }
]
```

## Additional Context

This was found while working on Prettier (https://github.com/prettier/prettier/pull/11845)

* Link to Try-Flow or Github repo: https://flow.org/try/#0CYUwxgNghgTiAEA3W8AeBuI

**Comment by gkz** [comment]
Looking at the changelog for 0.165: (https://github.com/facebook/flow/blob/main/Changelog.md#01650)

> The Flow parser now requires that variables declared using the declare var syntax be annotated with a type. declare var x; is now illegal.

So it no longer parses as it's not something we're supporting from now on
