### ISSUE TITLE
Module declarations: Export default polymorphic function along with types

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#880]
I'm trying to create a module declaration for a library that exports a polymorphic function, along with some types, but currently I'm not sure how to achieve that. I've seen in the issues and in some of the core libs declaration in the source that to define a default exported function you use `declare var exports`, so I tried to do that here:

```js
import type { Middleware, MiddlewareAPI, Dispatch, Store } from 'redux';

declare module 'redux-thunk' {
  declare type Thunk<State, Dispatchable> = (dispatch: Dispatch<Dispatchable>, getState: () => State) => ?Dispatchable;
  declare type ThunkMiddlewareDispatchable<State, Dispatchable> = Thunk<State, Dispatchable> | Dispatchable;

  declare var exports: {
    <State, Dispatchable>(
      api: MiddlewareAPI<State, ThunkMiddlewareDispatchable<State, Dispatchable>>
    ) : (next: Dispatch<Dispatchable>) => Dispatch<ThunkMiddlewareDispatchable<State, Dispatchable>>
  };
}
```

When I do this I have the following type errors:

```
someFile.js:6:15,19: "Thunk" export of "redux-thunk"
Property not found in
someFile.js:6:57,69: exports of "redux-thunk"

someFile.js:6:22,48: "ThunkMiddlewareDispatchable" export of "redux-thunk"
Property not found in
someFile.js:6:57,69: exports of "redux-thunk"
```

If I remove the exports declaration, the types are recognized again. It seems that the `declare var exports` is like overriding whatever was first declared, and I cannot find the correct syntax to move the type declarations into the `declare var exports` block.

Is there a way to correctly achieve this?

**Comment by samwgoldman** [comment]
@leoasis I know it's been a while since you opened this, but I'm having trouble seeing the issue here, since you didn't include the source to which Flow attributes the unexpected error, presumably in `someFile.js`. Can you add that?

**Comment by leoasis** [comment]
It turns out that the problem happens also with non polimorphic exported default functions, check this simpler example:

.flowconfig:
```
[ignore]

[libs]
libs

[include]
```

libs/foo.js:
```js
declare module 'foo' {
  declare type Foo = { a: string };

  declare var exports: {
    (a: number, b: number): number;
  }
}
```

example.js:
```js
/* @flow */

import blah from 'foo';
import type { Foo } from 'foo';

blah(1, 2);
```

I get a flow error:
```
$ flow
example.js:4
  4: import type { Foo } from 'foo';
                   ^^^ "Foo" export of "foo". Property not found in
  4: import type { Foo } from 'foo';
                              ^^^^^ exports of "foo"


Found 1 error
```

That error is gone if I change `declare var exports:` to a named export: `declare var blah:`, but I have to import it as `import { blah } from 'foo'`, which is not what I want/need.

**Comment by samwgoldman** [comment]
@Eyyub you added the declare type stuff, if I recall. Does this issue make sense to you? Seems like we aren't able to declare a default export (using the `exports` "trick") and have declared types as well.

**Comment by Eyyub** [comment]
The only way for this issue to make sense for me, is that Flow enters in [this case] (https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L2330), because as you see with the `TODO` and `(* ??? *)` the behavior was unknown so I said `for_types` value in this case is `SMap.empty`, which disable `declare type` decls ! Does it make sense ?

**Comment by samwgoldman** [comment]
Hm, seems reasonable to return the `module_scope.entries` which are `Value`s, right?

**Comment by Eyyub** [comment]
Sorry not sure if I understand, did you mean, in this case, assign `for_types` to the entries which are `Value `s ?

**Comment by samwgoldman** [comment]
Err, I wrote `Value`s but I definitely meant `Type`!

**Comment by Eyyub** [comment]
Np it's what I thought you wanted to say, but I asked just to be sure.
So yes, as it seems now `Type` and `Value` are clearly different, IMHO I do not see something to say against doing what you said !
