### ISSUE TITLE
Logical nullish assignment triggers an error

### ISSUE THREAD

**Issue by maicol07** [facebook/flow#8806]
Flow version: 0.165.1

## Expected behavior

No error

## Actual behavior

`??=` triggers two errors:

```
    ../\-:7:   x ??= x;
               ^ Invalid left-hand side in assignment
    ../\-:7:   x ??= x;
                   ^ Unexpected token `=`
```

*   Link to Try-Flow or Github repo: https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVUCuA7AxgFwEs5swo44AKADwC4wB+bTAWwCMBTAJwEp6BnfF0LYA5mADeqMGEJQwNHpOkywXDvkxdS1ANwqAviuqMGAXjB6V6zdrAAiACYcoAQ0wx8YQcLH39RkA

**Comment by gkz** [comment]
We don't support logical assignment operators yet. It's something we are considering looking at next half.

**Comment by SamChou19815** [comment]
This is now supported in the latest release.
