### ISSUE TITLE
LSP find_references not supported since 0.164

### ISSUE THREAD

**Issue by fabiomcosta** [facebook/flow#8816]
Hello folks,
Starting on 0.164 find_references is not working, which breaks the ability for editors using flow's LSP to show references of a variable used on the codebase.

I could confirm that when I used 0.163 it works as expected.

Looking at the release of 0.164 I see: `Removed flow find-refs command.`
But my guess is that `find_refences` was supposed to stay functional and it might have been broken accidentally.

Flow version: 0.164

## Expected behavior

find_references should work on my editor

## Actual behavior

I get an error saying that find_references is not supported on the current LSP server.

Thank you for your help!

**Comment by gkz** [comment]
https://github.com/facebook/flow/blob/main/Changelog.md#01640

> Support for finding references and renaming has been removed. While these features often worked well, they also caused extremely bad performance and crashes. We hope to reimplement these features as soon as we can.
