### ISSUE TITLE
Question on Documented Example

### ISSUE THREAD

**Issue by gsklee** [facebook/flow#882]
In [one of the documented examples](http://flowtype.org/docs/quick-reference.html#the-function-constructor), it's given that:

```javascript
// Valid! (`Function` may flow into any function type)
function foo(): Function { 
  return function(x: number): number { return x; }
}
var d: (str: string) => string = foo(); // Valid!
```

But if the result of `foo()` is a function which expects a number and outputs a number, how come `d` is being specified as `string => string`?

**Comment by samwgoldman** [comment]
You can read the `Function` annotation as "any function." By annotating the return type of `foo`, we're instructing Flow to discard the information it has except that the returned value is a function.

If you remove the annotation, you should see your expected error. (In general, Flow actually knows *more* about your code the *fewer* annotations you add.)
