### ISSUE TITLE
Flow can't select a tuple type over array if items are not typed inline

### ISSUE THREAD

**Issue by mourner** [facebook/flow#8829]
Flow version: v0.169.0

```js
let p = {x: 1};
let a: [number] | Array<number> = [p.x];
```

## Expected behavior

No errors.

## Actual behavior

```
2: let a: [number] | Array<number>  = [p.x];
                                      ^ Could not decide which case to select, since case 1 [1] may work but if it doesn't case 2 [2] looks promising too. To fix add a type annotation to `p.x` [3]. [speculation-ambiguous]
References:
2: let a: [number] | Array<number>  = [p.x];
          ^ [1]
2: let a: [number] | Array<number>  = [p.x];
                     ^ [2]
2: let a: [number] | Array<number>  = [p.x];
                                       ^ [3]
```

Even though `p.x` is explicitly a number (doesn't matter if `p` is typed, it's a sealed object), Flow shows the error above until the code is updated as follows:

```js
let p = {x: 1};
let a: [number] | Array<number> = [(p.x: number)];
```

This doesn't seem to make any sense to me — why does Flow require such explicit typing if `p.x` type is already known anyway?

* [Link to Try-Flow](https://flow.org/try/#0DYUwLgBADhC8EG8AeAuCBGAvgbgFCkgEM0BtAOwFcBbAIxACcBdCAHwgEF77CBPAHkq0GAPghwIJKADokjbEA)

**Comment by SamChou19815** [comment]
The issue seemed to be fixed in 0.199
