### ISSUE TITLE
Better utilise union types generated when looping through nested objects

### ISSUE THREAD

**Issue by frednomoon** [facebook/flow#8834]
Have been trying to deal with an odd error.. Easier to just demonstrate with code:

https://flow.org/try/#0MYewdgzgLgBFCm0YF4YG8BQMYEMBc6W2u+MAjEQL4A0MRARgZsTPYzAExUaUYYDy9AFbxgUAHQBreAE8IACgTQAlOIBmIAE4BRHMAAW86TP5h4KAHyFsgkWKmyFSqAG1jp+AF1VGnXsPGACoA7iCW1sSgkCAANvDiMSAA5oqIru5mnm6yISDeVMo8ykA

```
const test = {
  a: {
    aa: 1
  }, 
  b: {
    bb: 2
  }
}

Object.keys(test).forEach(keyOne => {
  Object.keys(test[keyOne]).forEach(keyTwo => {
    console.log(test[keyOne][keyTwo])
  })
})
```

Feels like this would be a very common coding pattern so am surprised this hasnt come up more frequently. But yeah Flow is clever enough in this instance to figure out that `keyTwo` can be either `aa` or `bb` at the line of the console log. However it is not clever enough to figure out that those values are scoped to their parent structures.

I definitely have some appreciation of why this might be difficult to solve.. however am interested to hear peoples thoughts in relation to how we could handle this / any workarounds in the meantime!

**Comment by gkz** [comment]
Using `Object.keys`, seems like the keys of your objects are not static, and it doesn't really matter what they are. If you annotate your object as a dictionary (of dictionaries), you'll see we no longer error: 
https://flow.org/try/#0MYewdgzgLgBFCm0BcMDeBtaAnAlmA5gLoobZ5EpgCuAtgEbxYC+TMAvGgFAwwCGJ3Hn34wAjIKYAaGILoChMOnJgAmCZyadOAeToAreMCgA6ANbwAnhAAUCaAEpjAMxBYAor2AALa+YvaweHYAPi4eXQMjM0sbOyh0PwD4QkcXd08fPwAVAHcQELChUEgQABt4Y1KQfFtEeMTAwgTLXJAUiXsNeyA
