### ISSUE TITLE
Referencing types from hyphenated modules

### ISSUE THREAD

**Issue by danvk** [facebook/flow#884]
I have this module definition in a `[libs]` directory:

```
declare module "data-canvas" {
  declare class DataCanvasRenderingContext2D extends CanvasRenderingContext2D {
    pushObject(o: any): void;
    popObject(): void;
    reset(): void;
  }
}
```

This provides types for `node_modules/data-canvas`. This works fine, until I need to reference one of those types from code in another module. They hyphen is a problem:

```
function getRenderer(ctx: data-canvas.DataCanvasRenderingContext2D, scale: (num: number) => number) {
src/main/PileupTrack.js|43 col 31 error|  Unexpected token -
```

I tried quoting it:

```
function getRenderer(ctx: "data-canvas".DataCanvasRenderingContext2D, scale: (num: number) => number) {
src/main/PileupTrack.js|43 col 40 error|  Unexpected token .
```

I eventually discovered that `import type` works:

```
import type {DataCanvasRenderingContext2D} from 'data-canvas';
function getRenderer(ctx: DataCanvasRenderingContext2D, scale: (num: number) => number) {
```

This isn't really an issue with Flow, I just wanted to file an issue with the solution in case anyone else runs into this in the future!

**Comment by samwgoldman** [comment]
I'm confused. If you rename your declared module to `nospace`, you can access the types using a qualified syntax like `nospace.DataCanvasRenderingContext2D`? If you can, that feels like a bug. I think the hyphen is unrelated.

**Comment by danvk** [comment]
If I change the declaration to

```
declare module "datacanvas" { ... }
```

Then I can refer to `datacanvas. DataCanvasRenderingContext2D`. But that's not the name of the NPM package, which is [already published with a hyphen][1]. So I'd rather not rename the NPM package.

[1]: https://www.npmjs.com/package/data-canvas

**Comment by samwgoldman** [comment]
@jeffmo This behavior is really surprising. IMO, we should require the type to be imported through the `import type` syntax. Jeff, is this a bug or intended behavior?

**Comment by samwgoldman** [comment]
Oh, and thanks for confirming @danvk. :)

**Comment by danvk** [comment]
Lemme double check what I said about referring to `datacanvas.DataCanvasRenderingContext2D`, I may have misinterpreted the errors.

**Comment by danvk** [comment]
If I put this in a `[libs]` file:

```
declare module "mymodule" {
  declare class Foo {
    x: number;
  }
}
```

and then do this:

```javascript
function foo(x: mymodule.Foo) {
}
```

Then I get the error you might expect: `type-annotation 'mymodule' Could not resolve name`. The `import type` statement still works.

So... forget I said anything :)
