### ISSUE TITLE
Enum entries cannot be used as keys.

### ISSUE THREAD

**Issue by deadalnix** [facebook/flow#8841]
Enum values are constants, so I don't really get how flow comes up with such an error. In any case, it is probably wrong. It would also be extremely beneficial to be able to do this.

Flow version: 0.171.0

## Expected behavior
Enum entries are used as keys.

## Actual behavior
Cannot assign computed property using `Keys` [1]. [invalid-computed-prop]

* Link to Try-Flow: [See this on tryflow](https://flow.org/try/#0PTAEAEDMBsHsHcBQBTAdgVwLagNLIJ4DOoA3oqKAGKyygC8oADADTmgBCAhgE72gCMrAL6JE0ZABdQADwBcpANp4iAXVDzCE7gEtUAcyF8yFJQUIA6arDXyARJBq3WJ5Ra7cboWwCMeTxCJAA).

**Comment by gkz** [comment]
https://flow.org/en/docs/enums/using-enums/#toc-mapping-enums-to-other-values
