### ISSUE TITLE
Flow doesn't seem to understand infinit loops

### ISSUE THREAD

**Issue by deadalnix** [facebook/flow#8844]
Flow seems to think the control flow might get past an infinite loop and complains about an implicit return.

Flow version: 0.171.0

## Expected behavior
Flow understand that the loop is infinite and therefore control never reaches past it. Therefore, there is no implicit return.

## Actual behavior

See [tryflow](https://flow.org/try/#0FAMwrgdgxgLglgewgAhAhAKOAuZEwC2ARgKYBOANMkQIZm4b7HkCUyAvAHx6GlnIAfHgBthLXEz7IA3sGTIA7gAs4wksgwwyYEm1nz5UJAGcYyGh2p0sLANxyDcEBovs3IsTIcHkZEjDAyFDh7HwBfYG9kOEsaUOQIiKA)

flow produces the following error:
Cannot expect number as the return type of function because number [1] is incompatible with implicitly-returned undefined.

**Comment by jbrown215** [comment]
While your case is a trivial one, in general determining if a loop is infinite is an undecidable problem. It is unlikely that we will try to address this. You can throw an error on the outside of the loop to get flow to pass without having to return a default number.
