### ISSUE TITLE
Flow-bin exiting with ENOENT in alpine docker container

### ISSUE THREAD

**Issue by taavisildeberg** [facebook/flow#8846]
I am unable to run flow in Docker Alpine image in ci pipeline after upgrading it to latest version.  Similar issues has been reported - https://github.com/facebook/flow/issues/3649, https://github.com/facebook/flow/issues/7509. Suggested fixes in listed issues are not solving the issue

Flow version: 0.171 and 0.172

## Expected behavior

Flow command works correctly 

## Actual behavior

```
/app # yarn run flow
yarn run v1.22.4
$ /app/node_modules/.bin/flow
events.js:291
      throw er; // Unhandled 'error' event
      ^

Error: spawn /app/node_modules/flow-bin/flow-linux64-v0.172.0/flow ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:268:19)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Emitted 'error' event on ChildProcess instance at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:274:12)
    at onErrorNT (internal/child_process.js:468:16)
    at processTicksAndRejections (internal/process/task_queues.js:80:21) {
  errno: -2,
  code: 'ENOENT',
  syscall: 'spawn /app/node_modules/flow-bin/flow-linux64-v0.172.0/flow',
  path: '/app/node_modules/flow-bin/flow-linux64-v0.172.0/flow',
  spawnargs: []
}
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
/app #
```

## Steps to reproduce
- docker run -ti --rm **node:14.8.0-alpine** sh
- mkdir app && cd app
- yarn init
- yarn add -D flow-bin
- yarn flow

**Comment by mroch** [comment]
can you please try running `/app/node_modules/flow-bin/flow-linux64-v0.172.0/flow` directly to get yarn and node out of the equation?

**Comment by taavisildeberg** [comment]
Here is the result: 
````
/app # ls -la /app/node_modules/flow-bin/flow-linux64-v0.172.0
total 30224
drwxr-xr-x    2 root     root          4096 Feb 19 07:32 .
drwxr-xr-x    7 root     root          4096 Feb 19 07:32 ..
-rwxr-xr-x    1 root     root      30939384 Feb 19 07:32 flow
/app # /app/node_modules/flow-bin/flow-linux64-v0.172.0/flow
sh: /app/node_modules/flow-bin/flow-linux64-v0.172.0/flow: not found
/app #
````

**Comment by taavisildeberg** [comment]
Also tested with node:17-alpine image.  With out of the box image flow fails to run again, but after `apk add gcompat` and `apk add libatomic` flow started to working

**Comment by mroch** [comment]
we removed the dependency on libatomic in flow 0.192.0! let us know in a new issue if there's anything else not working on alpine.
