### ISSUE TITLE
Enhancement: better Flow Enums refinement when casting

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8853]
Hola! 👋 I have a feature request I'd like to propose. Say we have the following enum:

```js
enum Status {
  Active,
  Paused,
  Off,
}
```

And some data (not important):

```js
const data: string = "yadada";
```

Now let's say we want to cast this `data` value to the enum value. There are currently two recommended options:

```js
const maybeStatus: Status | void = Status.cast(data);
if (maybeStatus != null) {
  const status: Status = maybeStatus;
}
```

Or we can do a one-line solution with a default fallback:

```js
const status: Status = Status.cast(data) ?? Status.Off;
```

What I'd like to propose is this (call `isValid` and later `cast` without the necessity for `??` fallback):

```js
if (Status.isValid(data)) {
  const status: Status = Status.cast(data); // ERROR - but can it still be `void` at this point?
}
```

https://flow.org/try/#0KYOwrgtgBAygLgQzmAzlA3gKClAggYzgEsA3YAGmygAUFVgATSnAeQDM3KBfTTfAexAo4UBkgQAuKMIBOREAHMoAXigAiAJ4IxYtQG5eAoSIgINAI2DwkqKdeRoAPlBL8iDFbEQOAdPgTCABRiiACUBkRsUIGmFlbeqFAAhKrgADZpoRhURsLSCSgAjHYFnrGW9qgGPHyCecI2KABMJY2elSh+AXDB4lkA-P1ejT7sbAaYkdEdPkQoAGoIae69YVlYOLkiDQ4AzK0O7QVdQSEI4VAA9JdQAMIIIFBE28QZUJZQAAau7p9QSFA4AALOZQAAObhAcH6mB4QA

cc @gkz

**Comment by gkz** [comment]
We don't have the capability of implementing such a refinement in general (e.g. `Map` `.has` also doesn't refine) at the moment, but if this changes in the future I would like to add this

**Comment by SamChou19815** [comment]
I believe this is resolved by @gkz's work in https://github.com/facebook/flow/commit/6355cf93b8d06c32475215a1b1eb82e12556f445
