### ISSUE TITLE
Flow isn't auto discovering `.flow` declaration files for top-level re-exports

### ISSUE THREAD

**Issue by thejewdude** [facebook/flow#8854]
Flow version: 0.173.0

## Expected behavior
When I import any object from flux, the `.flow` declaration files should be auto discovered and flow should provide typings and completions. 
```javascript
// @flow
import { ReduceStore } from "flux/utils";
```
## Actual behavior
Flow doesn't discover the declation files and all exports are typed as `any(implicit)`. I have to drill down `node_modules` and import from the actual file like so: 
```javascript
// @flow
import ReduceStore from "flux/lib/FluxReduceStore"
```

* Link to Try-Flow or Github repo: https://github.com/thejewdude/playground-flux-flow

**Comment by SamChou19815** [comment]
Expected, since `import { ReduceStore } from "flux/utils";` doesn't have `@flow` so it's untyped.
