### ISSUE TITLE
Inconsistent instanceof incompatible-type-arg error

### ISSUE THREAD

**Issue by elgbar** [facebook/flow#8855]
Flow version: 0.173.0

## Expected behaviour

Using `instanceof` in an `if` statement should be valid code

## Actual behavior

The new instanceof in v0.173 refuses to work with generic types, but only within `if`.

[Link to Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVBjGBDAzrsANWwCcBLbAIxgFMAeAFQD4wBvAX3SgFcA7DAC5k4vMLxEB1OCQDWZXgHNGTABQA3UgFlsAT0o0AXEVIVq9ZgEo2qMGDJQw6rbv13euAdn404D4uSpaK1Z0W05OVB5+IREwBGkZUjg+ABNlJxJtPUNjALNlYJswDBEPO1x-MABeMA1Mlxo3Dy8MHz8TQJoAbiL7FTIK0gsQ21si8KA)

**Comment by Robloche** [comment]
Fixed in v0.185.0!
