### ISSUE TITLE
0.174.0 NPM binary

### ISSUE THREAD

**Issue by neutraali** [facebook/flow#8856]
Apparently [0.174.0 is available](https://github.com/facebook/flow/releases/tag/v0.174.0) now, containing a few Windows-related `dfind` -fixes that might resolve some issues.

However, `npm show flow-bin versions` still shows `0.173.0` to be the latest version. Would be nice to get the latest release into NPM / `flow-bin`.

**Comment by mroch** [comment]
our deploy automation had a glitch. it's published now!
