### ISSUE TITLE
Types `bool` vs. `boolean`: motivation and possible simplification

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8857]
I never knew about this, but apparently, there are two identical types in Flow: `bool` and `boolean`.

```js
const x1: bool = true;
const x2: boolean = true;

const y1: boolean = x1;
const y2: bool = x2;
```

https://flow.org/try/#0MYewdgzgLgBAHgRgFwwEYhAGxgXhlAJwFcBTAbgChRJY4AmFdLEgQzF32PIqvGhgCeyNBkyt2eRJWr8BDEVg71KQA

The purpose of this discussion is understand the motivation behind these 2 types. Are there any differences? Are they identical? Why do they exist?

And in case they are the same: what about removing one?

Thanks! 😊 

Relevants docs page: https://flow.org/en/docs/types/primitives/#toc-booleans

**Comment by jonathan-rosa** [comment]
If they are the same, I vote keep boolean because it's the one of the two used in JavaScript and has always been a reserved keyword, the other has no significance.

**Comment by mrtnzlml** [comment]
Type `boolean` (as opposed to `bool`) is also recommended by Flow docs: https://flow.org/en/docs/types/primitives/#toc-booleans
