### ISSUE TITLE
$Rest<$Rest<ExactT, {}>, {}> is not assignable to $Rest<ExactT, {}>

### ISSUE THREAD

**Issue by noppa** [facebook/flow#8858]
Flow version: 174.1

## Expected behavior

The following should type check without errors
```javascript
type A = {|
    a: string,
|}

type Partial<T> = $Rest<T, {}>

declare var a: Partial<A>
declare var b: Partial<Partial<A>>

a = b
```

## Actual behavior
Flow gives a type error on the assignment
```
    10: a = b
            ^ Cannot assign `b` to `a` because undefined [1] is incompatible with string [1] in property `a` of type argument `T` [2]. [incompatible-type-arg]
        References:
        2:     a: string,
                  ^ [1]
        5: type Partial<T: any> = $Rest<T, {}>
                        ^ [2]
```

* Link to Try-Flow or Github repo: [Try-Flow](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFTUCGAuKAzsAE4CWAdgOYA0aKAvmmqJFAArbHCnYA2APABUAfAigASAEoQiQ6snrCmAEwgBjXp2gA3TjnwcuPATCWqNWqLuJQARgc7c+-Q05PClabGNtogA)

According to [the docs for `$Rest` utility type](https://flow.org/en/docs/types/utilities/#toc-rest), `$Rest<A, {}>` should make all A's properties optional when A is an exact type. So in the above example, that `Partial<A>` should essentially be
```javascript
{|
  a?: string, 
|}
```

Turning all properties optional the second time should basically be a no-op, right?  
This _does_ type check:
```javascript
declare var c: {|a?: string|}

b = c
// or the other way around, both are fine
// c = b
```

**Comment by gkz** [comment]
Did you mean to use an exact empty object type?

https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFTUCGAuKAzsAE4CWAdgOYA0aKAvmmqJFAArbHCnYA2APABUAfAigASAEoQiQ6shQNhTACYQAxr07QAbpxz4OXHgJjK1m7VD3EoAI0OduffkeenhytNjF20QA

p.s. we have a `$Partial` utility type built in - need to add docs for it

**Comment by noppa** [comment]
Nope, [that won't work](https://flow.org/try/#0C4TwDgpgBAglC8UDeAfAUFTUCGAuKAzsAE4CWAdgOYA0GWARvuQK4C29ExtKAvmmqEhQACtmLBS2ADYAeACoA+BFAAkAJQhF51ZCl4L+AYwD25IlDBiJ0mPlHjJsmEsRI6mPFADkX2nzRAA)  
the Partial trick relies on the inexact object. [`$Rest` docs](https://flow.org/en/docs/types/utilities/#toc-rest):
> $Rest<{|n: number|}, {}> will result in {|n?: number|} because an in-exact empty object may have an n property

Nice to know about the proper built in though :+1:

**Comment by SamChou19815** [comment]
Closing since we now have Partial. $Rest might be gone in one day too, because we have Omit
