### ISSUE TITLE
Flow should not require return annotation if annotated function is returned

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#886]
Here is a specific example:

```js

/* @flow */

type Action = {$typeof: string}
type ByID = {$typeof: "ByID", id:number, act: Action}

export const by = (id:number) =>
  (act:Action):ByID =>
    ({$typeof: "ByID", id, act});
```

With this code I get:

```
/Users/gozala/Projects/flowing/src/flowing.js:8:3,9:31: return
Missing annotation

Found 1 error
```

It is really odd to annotate first function specially given that annotation is repeated right away on returned function.

**Comment by Gozala** [comment]
BTW annotating an outer function vs annotating a returned function works but I find doing so awkward and would prefer to annotate each level instead.

**Comment by JohnyDays** [comment]
I've been doing some functional stuff recently, and this has been a particularly unpleasant nuisance, although it's possible to work around as @Gozala explained

**Comment by samwgoldman** [comment]
Same as #841
