### ISSUE TITLE
Declare module multiple times and merge result

### ISSUE THREAD

**Issue by alebiavati** [facebook/flow#887]
I'm trying to create a module that will allow me to register enumerator types from different modules. Here is how I define enums using flow:

**enum.js**

```
// global Enum class
declare class Enum {}
declare module "enum" {
    declare function register(type: string, values: Array<string>): void;
}
```

**fruit.js**

```
declare class Fruit extends Enum {}
declare module "enum" {
    declare var Fruit: {
        ORANGE: Fruit,
        APPLE: Fruit,
    };
}
```

**animal.js**

```
declare class Animal extends Enum {}
declare module "enum" {
    declare var Animal: {
        CAT: Animal,
        DOG: Animal,
    };
}
```

When I typecheck this, the checker only sees the enums declared in the first file. The other `declare module "enum"` are discarted. 

I know this worked before I updated flow to 0.16.0. Is there something else I should be doing or is this not supported anymore?

Thanks

**Comment by samwgoldman** [comment]
@alebiavati This is an interesting use of `declare module`, and I think it would help me to see what you are trying to accomplish overall. Would it be possible to share something more detailed to expose the pattern here?

It would be very helpful to see:
* The directory structure (are you declaring in lib files or source files?)
* How you are using the `enum` module—where is it required from? What is the expected type?
* Your `.flowconfig`

A small repo showing this would be ideal.

**Comment by calebmer** [comment]
Going to close since we did not get more information. Please let us know if this is something you still want! 😊
