### ISSUE TITLE
bug, when destructuring JS-objects in a flow-typed specification

### ISSUE THREAD

**Issue by mfc3370** [facebook/flow#8874]
Flow version: 0.176.2
Node version: v16.13.2
Yarn Version: 1.22.17
System: MacOS Big Sur (version 11.4)

## Expected behavior
Run without errors

## Actual behavior
Showing errors on terminal
```
$ flow check
Unhandled exception: "Assert_failure src/parser_utils/type_sig/compact_table.ml:121:4"
Raised at Stdlib__string.index_rec in file "string.ml", line 115, characters 19-34
Called from Stdlib__string.contains_from in file "string.ml", line 179, characters 15-34
```

* Link to Try-Flow or Github repo: https://github.com/mfc3370/flow-test (Please pay special attention to this [comment](https://github.com/mfc3370/flow-test/blob/master/flow-typed/custom.js#L10))

* Steps to reproduce

git clone git@github.com:mfc3370/flow-test.git
yarn
yarn test:flow

**Comment by mvitousek** [comment]
Thanks for the report!

@samwgoldman Looks like an issue possibly with type sigs? I can repro this by pasting 
```
const forms = {
    STATES: {
        idle: 'idle',
        busy: 'busy',
    },
};
const {STATES} = forms;
```
in any [libs] file. Do we even support this kind of operation in libdefs?

**Comment by samwgoldman** [comment]
Fix incoming, thanks for the report! You can work around for now by writing the definitions in the reverse order:

```
const STATES = {
    idle: 'idle',
    busy: 'busy',
}
const forms = {
    STATES
};
```
