### ISSUE TITLE
Flow should reduce union type in conditionals

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#888]
Following example does not type check:

```js
/* @flow */

type Stepper = {step: Function};
type Updater = {update: Function};
type Config = Stepper|Updater;

export const init = (config:Config) => {
  const next = config.step != null ? config.step :
               /*nofx(*/config.update/*)*/;

  // ...
}
```

It produces following error:

```
Users/gozala/Projects/flowing/src/flowing.js:9:32,37: property `update`
Property not found in
/Users/gozala/Projects/flowing/src/flowing.js:9:25,30: object type

Found 1 error
```

In fact providing a type cast also does not fix the issue and produces same errors:

```js
/* @flow */

type Stepper = {step: Function};
type Updater = {update: Function};
type Config = Stepper|Updater;

export const init = (config:Config) => {
  const next = config.step != null ? config.step :
        /*nofx(*/(config/*:Updater*/).update/*)*/;

  // ...
}
```

The problem is in both cases `config` in else block is still assumed to be `Stepper|Updater` although given that in else block it's known that `config.step == null` type of config type should be <code>~~Stepper~~|Updater</code> and there for code should type check.

It's even more surprising that type casting also does not resolve this.

**Comment by samwgoldman** [comment]
> It's even more surprising that type casting also does not resolve this.

Note that Flow [does not support downcasting](http://flowtype.org/blog/2015/02/18/Typecasts.html#safety). If you know this, it is unsurprising that your type cast raises a type error, based on the current behavior of the type checker.

**Comment by samwgoldman** [comment]
OK, so the proposed refinement isn't safe because of subtyping.The details are a bit twisty, so consider this carefully.

Coming up with counterexamples for this, I actually found a bug in Flow...

```
/* @flow */

type X = { a: string } | { b: number };

function f(x: X): string {
  if (x.a) {
    // x.a must be a string, right? well...
    return x.a;
  }
  return "";
}

f({ b: 1, a: 1 }); // ...not quite
```

Flow finds no issue with this code, but we've managed to return a number from a function annotated to return a string. Oops!

**Comment by samwgoldman** [comment]
@Gozala Let me know if I can help further explain why this kind of refinement is unsafe (I can come up with a few more counterexamples). The reason why we can do this at all with sentinel values is because every component of the union definitely has the same key. Due to subtyping, an unspecified key in an object type may still exist at runtime—i.e., the lack of an annotation is not proof of the lack of the key.

**Comment by Gozala** [comment]
@samwgoldman thanks I think I got an idea from your counter example and re-reading http://flowtype.org/blog/2015/07/03/Disjoint-Unions.html I see now that sentinel property is required for this to work.

I would still re-open this issue though as I think two things should happen:

1. Disjoint Union announcement content should find itself into docs for Union types: http://flowtype.org/docs/union-intersection-types.html

2. Flow should probably complain about union types that can't be refined which would make issue with my code more obvious. I believe in my case I could just have had two different type of `init` functions instead of trying to allow two diffs type of configs.

If 2 is not a proper solution maybe error message could be improved "property `update` not found in object type" is really not not obvious.

**Comment by samwgoldman** [comment]
The disjoint union behavior is more of a refinement/dynamic type test issue, and is duly documented in [that section of the docs](http://flowtype.org/docs/dynamic-type-tests.html#tagged-unions).

Regarding error messages, it's certainly a known problem that errors around union types are difficult to understand. There are quite a few issues already open about that already, so I don't think we need another one.

**Comment by AlicanC** [comment]
Is there a reason for this to be unsafe?

```javascript
/* @flow */

type A = {
  foo: string,
};

type B = {
  baz: boolean,
};

const a: A = {
  foo: 'test',
};

const b: B = {
  baz: true,
};

function logIt(param: A | B) {
  if (typeof param.foo === 'string') {
    logA(param);
  }

  if (typeof param.baz === 'boolean') {
    logB(param);
  }
}

function logA(param: A) {
  console.log(param.foo);
}

function logB(param: B) {
  console.log(param.baz);
}

logIt(a);
logIt(b);
```

[flowtype.org/try Link](https://flowtype.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgCCYAvGAN6phhRxwBcYAzhgE4CWAdgOYA0qAXwDc6bPjAAhUhSpgARgEMAXozl0YeBZ37D0AYzicWYBY2JlK1WgzAByDHha2dI1AaMZ5jKRdmKVYGwArngu6FBBnHoY7IZg8NwAkhgAFDgKrAoAtmZgAD6SAJQy1OxQYClieHDl6ZlZAHTWpCRktiwcPLbFltTxcNyEaRnZhSLUAuil5ZW41bUjjf4tbWpwGlrdJX0JEsP1Y7KTk6gRUTFxCUN12WY9su5M63gNCfvZTXSHJ2fRsZz9bh7G45IrbR7PV4Dd5LZTfdAJZIpBSHRGpORjIA)

We should be able to downcast with proper runtime checks. Especially with the new "exact object types" (which I haven't tested yet).
