### ISSUE TITLE
JSX allow passing multiple Objects to props key

### ISSUE THREAD

**Issue by AuthorityFX** [facebook/flow#8882]
Flow version: 0.177.0

## Expected behavior

JSX should not allow passing multiple objects to props key

```
const Comp = (props: {|
  style?: {|
    something?: number,
  |},
|}) => {
  return null;
}

const ShouldBeError = () => {
  return (
    <Comp style={{}, { something: 12}} />
  );
}
```
## Actual behavior

No Flow error when passing two objects to style prop

* Link to Try-Flow or Github repo: https://flow.org/try/#0JYWwDg9gTgLgBAJQKYEMDG8BmUIjgcilQ3wG4AocmATzCTgGUaAbegXjgBJkUATAeQB2zagB4A3gB9ycOAGdcSGAAtgggOYB+AFxxBAVxAAjJFAA05SQF8AfJRp04ABRxg5cDt1QDhYqTPkWJB1GIItrO3I0CEE5eABhXDAPOAAKMFc5XRcINwBKDxs4cQCiGH0oQT19ZmYKK0po2Ph+AGkU1IK2IpLZMoqq1IDZUUTwQOpWNnFxeUUVNXVdAEYAJisrOAB6O1k8+soomLi4AFEADzoMJF5TqBwoDq6e0qUBtOG4UaSJqZmrMzFDbbXZwfbkBpHZqMZQQGq8ABCSDuDyehWKr3KlQ+shGY2ScUmSGm4gBxTmICUqg0K3Wmx2AXBViAA

**Comment by gkz** [comment]
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Comma_Operator

There is probably an ESLint rule you can enable to if you want to ban this

**Comment by jbrown215** [comment]
This is not a bug-- this is a sequence expression. JS is hilarious.
