### ISSUE TITLE
Error thrown when parsing regexp with `d` flag on Node.js v10

### ISSUE THREAD

**Issue by fisker** [facebook/flow#8886]
Flow version: 0.179.0

## Expected behavior

Not throw error

## Actual behavior

Error thrown

* Link to Try-Flow or Github repo:

```text
> require('flow-parser').parse('/./d')
Thrown:
SyntaxError: Invalid flags supplied to RegExp constructor 'd'
```

The value of RegExpLiteral should be `null` per ESTree spec https://github.com/estree/estree/blob/master/es5.md#regexpliteral

**Comment by mroch** [comment]
this was fixed in 30e59baea97f8cdf84065d312df52d98fdb2e1d1 which is already in 0.179.0. are you sure you're using 0.179?

**Comment by mroch** [comment]
or do you mean that Flow parses it but because of the `value` field, the runtime is throwing if it doesn't support `d`?

**Comment by fisker** [comment]
> are you sure you're using 0.179?

Yes, I'm sure.

> or do you mean that Flow parses it but because of the value field, the runtime is throwing if it doesn't support d?

I think so.
