### ISSUE TITLE
Flow.org/try keeps loading forever

### ISSUE THREAD

**Issue by bitsapien** [facebook/flow#8899]
This is a bug on the flow.org/try website.

## Expected behavior
Should show AST, Errors and JSON on the right.
## Actual behavior
Is stuck in the loading state
<img width="1507" alt="image" src="https://user-images.githubusercontent.com/3462960/175550894-b609cf36-cf74-424e-96a6-e0ec781df3ad.png">

Tested this on Safari on Mac/iOS and Chrome on Mac.

I see the following error in the console
<img width="1500" alt="image" src="https://user-images.githubusercontent.com/3462960/175551298-d26e871c-4407-4de7-8ec0-a8800138761e.png">

**Comment by SamChou19815** [comment]
It might be caused by we updated to js_of_ocaml 4 in the last release. You can try to use the 0.180.1 version from the dropdown meanwhile.

As a note for myself, these issues might be relevant:
https://github.com/dbuenzli/brr/issues/4
https://github.com/ocsigen/js_of_ocaml/pull/997

**Comment by SamChou19815** [comment]
The issue is fixed now master now. I will soon deploy a patch release to fix the default selected version on try flow.
