### ISSUE TITLE
Unsound property access for union types

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#890]
``` javascript
/* @flow */

type X = { a: string } | { b: number };

function f(x: X): string {
  if (x.a) {
    // x.a must be a string, right? well...
    return x.a;
  }
  return "";
}

f({ b: 1, a: 1 }); // ...not quite
```

Existence checks `if (x.a)` and explicit null/undefined checks `if (x.a != null)` all exhibit this behavior.

**Comment by bhosmer** [comment]
Turns out it's not about unions - purely about inconsistent assumptions about object types and subtyping in different places:
```
var x: { a: number } = { a: 1, b: 1 };
if (x.b) {
  var y: string = x.b;
}
```
Couple of things to dig into here. Update shortly

**Comment by avikchaudhuri** [comment]
Good catch! My bad for not thinking through the consequences of the hack that enables this code to typecheck.

**Comment by samwgoldman** [comment]
Subtyping is a cruel mistress...

**Comment by TrySound** [comment]
Is this still unsound?
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAaYAvGAN5gCGAXGAM4YBOAlgHYDmYAvmAD4UwAIzpsArgFsheJjwDc6KGLYBjDCzhswUABQAPOoQCUdRq04VUYMCyhh9AOipHL168GBg9TsBLGNhAioGZnYOABowVg4ACwwAfjAEPBgYB3SrNyY8DDEmLW8qBWtuTOzc-LAAIiqFUtRdShEwAEZI2laeIzkwDzB0hzY4DDAARzEWDDwgA

**Comment by vkurchatkin** [comment]
Seems fine!
