### ISSUE TITLE
No document that caught errors are any-typed

### ISSUE THREAD

**Issue by rlamacraft** [facebook/flow#8900]
Hi,

I've been using Flow for over a year but only today noticed that variables introduced by catch block are essentially any-typed. Whilst this makes sense, given essentially anything can be thrown in JS from any point in the call tree, I don't think this is at all obvious and some documentation highlighting this would no doubt prevent substantial confusion. Even better yet, a linter warning would be awesome help raise this a potential foot-gun.

An example of what I mean is [demonstrated in this Try-Flow](https://flow.org/try/#0C4TwDgpgBAggNhATsKBeKBvAPgKCvqAWwgGcSBDAcwgC4oA7AV0ICMkAaHLAXwG4ccAM0b0AxsACWAe3oMIAd3hJgACkIlKdJqyQBKOkuSY8BRBGCNEsjEVIVqddZSgBqKABYATFD45uA4EQQYwIoYAALRCl5KAAiEiliKCQoxFj+bihRcmBRcJUIXRCCegVDVUKMoA).

Cheers!

**Comment by rlamacraft** [comment]
Thanks!

Thinking about this some more, is this something that could actually be improved by having the type checker consider the introduced error variable as having the type `mixed` so that any code in the catch block first has to check that it has something of the right type? 

Introducing such a change would no doubt be quite burdensome on all error handling code, so I can understand not wanting to type it that way for that reason, but it would improve the correctness of the type checker, wouldn't it? As it stands, it is quite easy to assume you have an instance of `Error` but actually at runtime have a string or something else entirely.

**Comment by mvitousek** [comment]
That's definitely something we've considered, and will keep thinking about for the future--possibly gated under a flowconfig option or something. The main blocker is the enormous number of errors that would arise in repos if we made such a change, but it is definitely an appealing soundness improvement .

**Comment by gkz** [comment]
You can explicitly annotate a catch parameter as `mixed`:

```
try {
} catch (e: mixed) {
}
```
though we do not yet have an option to make this behavior the default
