### ISSUE TITLE
Missing support for Array.prototype.at()

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8902]
👋 

## Missing/Incorrect APIs

Missing API: `Array.prototype.at()`

## Relevant documentation

- https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/at

## Flow.org/try

https://flow.org/try/#0MYewdgzgLgBAhgJwXAngRhgXhgbQKwA0MaATEQBxFoDMADEQCwMC6A3AFDsA2AprAJZgAJjwAeWGCQ7tQkELwB0XEAHMAFAAMAqhEEr4YGIJHiQAMxgASAN7GxAXxhQAFjyNQeAWxgI+AVwQwHiEjCCtrRGR0BTgoNTtRAEp7DUSOAHp0mDEABx5gDxCQPygckoAuGAAiHT0DI2ExGHNJJ1d3Lx9-QODQmHIqzgSJAFopTlkIeR4lVU1asH04Q2GWmwTHfg9vXygAoJD+MJtI1DQYuITk1Iys3PzC5pKyqEqa3UX61Ysxjp3ug59Gi0QZAA

```text
5: console.log(`Using an index of ${index} the item returned is ${array1.at(index)}`);
                                                                         ^ Cannot call `array1.at` because property `at` is missing in `Array` [1]. [prop-missing]
References:
[LIB] ..//static/v0.181.2/flowlib/core.js:874: declare class Array<T> extends $ReadOnlyArray<T> {
                                                             ^ [1]
10: console.log(`Using an index of ${index} item returned is ${array1.at(index)}`);
                                                                      ^ Cannot call `array1.at` because property `at` is missing in `Array` [1]. [prop-missing]
References:
[LIB] ..//static/v0.181.2/flowlib/core.js:874: declare class Array<T> extends $ReadOnlyArray<T> {
                                                             ^ [1]
```

**Comment by Robloche** [comment]
This issue seems fixed in v0.185.0.

https://flow.org/try/#0MYewdgzgLgBAhgJwXAngRhgXhgbQKwA0MaATEQBxFoDMADEQCwMC6A3AFDsA2AprAJZgAJjwAeWGCQ7tQkELwB0XEAHMAFAAMAqhEEr4YGIJHiQAMxgASAN7GxAXxhQAFjyNQeAWxgI+AVwQwHiEjCCtrRGR0BTgoNTtRAEp7DUSOAHp0mDEABx5gDxCQPygckoAuGAAiHT0DI2ExGHNJJ1d3Lx9-QODQmHIqzgSJAFopTlkIeR4lVU1asH04Q2GWmwTHfg9vXygAoJD+MJtI1DQYuITk1Iys3PzC5pKyqEqa3UX61Ysxjp3ug59Gi0QZAA

**Comment by mrtnzlml** [comment]
@Robloche I don't think the `.at()` method was added; I think Flow is broken now because this code is valid as well in 0.185.0 ([flow.org/try](https://flow.org/try/#0MYewdgzgLgBAhgJwXAngRhgXhgbQKwA0MaATEQBxFoDMADEQCwMC6A3AFDsA2AprAJZgAJjwAeWGCQ7tQkELwB0XEAHMAFAAMAqhEEr4YGIJHiQAMxgASAN7GxAXxhQAFjyNQeAWxgI+AVwQwHiEjCCtrRGR0BU9YgEkAERAAORAoAFFRfmg1O1EASnsNfI4gA)):

```js
const array1 = [5, 12, 8, 130, 44];

let index = 2;

console.log(`Using an index of ${index} the item returned is ${array1.mmmIDoNotExist(index)}`);
```

cc @mroch @mvitousek

**Comment by gkz** [comment]
Yeah it's broken on Try Flow for version 0.185. Works if you switch to master branch however. Don't know why

**Comment by Robloche** [comment]
Ah yes, sorry.
