### ISSUE TITLE
Cannot spread a disjoint union in certain cases

### ISSUE THREAD

**Issue by danny-does-stuff** [facebook/flow#8905]
Flow version: 0.182.0

## Expected behavior
Should be able to spread a disjoint union into a new object. This behavior is very similar to something described in [this flow blog post](https://medium.com/flow-type/spreads-common-errors-fixes-9701012e9d58#a465) that was fixed in 0.111.0, but there seems to be some cases where it doesn't work properly.

## Actual behavior
Spreading a disjoint union causes errors in some cases, like inside of a condition, or when the value is made by a function. All of the cases I was able to find where flow errors in an unexpected way are shown and commented in the Flow try.

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwCCYAvGAN5hZ4BcYA5AIZ1gC+GO+AQieZR7XQBGdADRhcAD3QAnBrQB2AVwC2g3NNap2eMAGEeRAD5hOW4MDAAVABb4Abg2kBLBoJj50cMGrABnXOiUXr7WiOLS0nDSvqjugei4vui6tLpaAMZw8klg6ak8FFS4AkyaqOZgAMrY0rgMACZO8gDmYAxg8lHKDDB6YAhRANYxCUn6pBQAdNPpZU5QYAAU6QCU5Khgm2AVACJwiR1wgQPSg23ymMpR+AxQCRrtmfKN6E5ZPRtbo8kFYNOTszYbFQTxy3UwahSYAA-ONeEUSsxgRUELgnNJ6mAanA3LhlL5+k50NYwOCfEUYvMlmTcLo1mRPpsKtVag0mq0ok5mk0emB6vtfPI6MchozKIkfhM-tMafpgVtthYWXVGi02h1cEgHDBFB5rAxAk4CU0oOpapj+YkhSLTmLQYb5KaIrh6pY8dgeLKxd84VNpiazS63coPfKtsyair2er5JqwNrdYTieIJNgYE50kS+DpkJbfOAToM7VkcpI0xmicHsPlSF6FT7fv8y+nM+gq5pgfVcOkYI57I5SQxBrTaIs1sQAHx6EElwLdLtw7rD3RjswWPYHTo2s4IWzyeM9RNGwdd7yYdVQRTydKvLIYCW+6WTee0zQVEAb-P9IZJkkMffNhW8QcGAWTqgkIZRI454OM4rjuDO2SBIBrZVjWJ60veYyNtMKGVu6ZRAA

**Comment by SamChou19815** [comment]
Now all of them work
