### ISSUE TITLE
type refinement does not work on nested properties when using predicate functions 

### ISSUE THREAD

**Issue by dannyharding10** [facebook/flow#8908]
Flow version: 0.183.0

## Expected behavior
Using a predicate function should refine types of nested properties in the object that is passed to the predicate

## Actual behavior
Nested properties of objects are not refined when the parent object is passed to the predicate.

Please let me know if you need anything else from me on this issue 👍

* Link to Try-Flow or Github repo: https://flow.org/try/#0C4TwDgpgBAchDOwoF4oCgqagHygb10QENgBXeALigHIBBAYQBUBJANQFFqAaKIgY2ABLAG4QAYoIgAbACZVgAJ1LRsAXwxZcBYmUo1mMBiw7U1aNKEhRaKfBswA7BMAhzYztOrQB6b1EYAFoLwUGAKroJ8JNAAZqQOAoIA9g5QMkkIUA5JSOExgk5QAAZEAHROiK5FaHEJQim8zPC0iaIAFERUtACUVABGSUlSEESpAKR8ARB8ANYhePZQ4WQKqWUVLjKlOuQoyKh0TGycnua+-kEhYRFRLlAAVOkI90sQ+YVFG1U18YkNXzImi0hO0AVQ4IhelABkMRuNJtM5nYsK8VqkAdtgCRdvsDkZjtRTmgZNMpERwlBhOTeF1zLU-ql6W0pP1BsNRt18F5BDEoB0ga0IB1upyFijziUBSCIEUoPAAklSLJXu9oOtnK5Fkz1ZUtvxpRJpDJuqceXydZtMdiQriaPiTKLFudAtB4EQALbQPhJEm8EKS5qC2UAdySCiRqqgwam6JyUAKvCg9PqDi1vw65Q1esFhtkJvUEoBUpEMt4UngSSjYbmaDNbSLgelGYBIuRWG1md1pX1JdzxtOQA

**Comment by SamChou19815** [comment]
This is expected, since predicate function only adds refinements on the argument you passed in.
