### ISSUE TITLE
flow seems to be confused by function declaration

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#891]
Below are two examples, first one works as expected while the second (I believe incorrectly) does not:

```js
/* @flow */

export const run = (task:?Function) => {
  if (task != null)  {
    task()
  } else {
    throw TypeError("task must be a function")
  }
}
```

The following example fails with "function call Function cannot be called on possibly null value" error.

```js
/* @flow */

const run = (task:?Function) => {
  if (task != null)  {
    const run = () => {
      return task()
    }

    run()
  } else {
    throw TypeError("task must be a function")
  }
}
```

**Comment by jeffmo** [comment]
Yea, this is a KP (see http://flowtype.org/docs/dynamic-type-tests.html#caveats)

It's because, at the moment, having a function call inside a refinement will invalidate Flow's certainty about that refinement (Flow isn't currently able to follow the function call and confirm that it doesn't change the value of `task` back to null by way of some other closure).

For now you can work around this for now by saving the refined variable to a different local var first inside the toplevel of the environment like this: https://gist.github.com/jeffmo/ca3323170edb7bcbd0a7

**Comment by Gozala** [comment]
> Yea, this is a KP (see http://flowtype.org/docs/dynamic-type-tests.html#caveats)

> It's because, at the moment, having a function call inside a refinement will invalidate Flow's certainty about that refinement (Flow isn't currently able to follow the function call and confirm that it doesn't change the value of task back to null by way of some other closure).

Well in the mentioned caveat it makes sense because passed object can be mutated by an outer function. But the provided example outer function can't possibly change argument that is function to null or undefined so I think flow could handle that case without necessarily follow function calls.

@jeffmo Presume flow assumes that any function call may have unpredictable side effect and type can can change from anything to anything which is not great but in that case I would argue that following example should work fine (which is closer to my actual code in fact):

```js
/* @flow */

const run = (task:?Function) => {
  const safeTask = task;
  if (safeTask != null)  {
    const run = () => {
      return safeTask()
    }

    run()
  } else {
    throw TypeError("task must be a function")
  }
}
```

In this case `const safeTask  = task ` should be refined to `Function` and invoking a function should have no effect given that `const` is used and there for it should not be possible to change `safeTask` value.

**Comment by samwgoldman** [comment]
@Gozala The caveats section calls this out specifically.

> Flow does not currently perform mutation analysis, so in some cases, Flow will throw away a refinement that is always safe to keep. As more analyses are implemented, Flow will hopefully come to understand the following examples are sound.

**Comment by samwgoldman** [comment]
You're also right that `const` is more low-hanging fruit when it comes to keeping refinements. Investigating whether it is worthwhile to special-case const is on my radar already.
