### ISSUE TITLE
Possible parser regression in ExportAllDeclaration since v0.171.0

### ISSUE THREAD

**Issue by SGrondin** [facebook/flow#8911]
Flow version: v0.171.0 and later, including the latest release (v0.183.1)

## Expected behavior
A file containing the following line should parse:
```js
export * as Error from './errors.js'
```

## Actual behavior
As of [4b9ccbaa](https://github.com/facebook/flow/commit/4b9ccbaa7d9db48b19b686ce7c1668f1f19b76ef) (@mroch), the parser raises `Parse_error.Error (_, errors)` where errors is a list of 4 `Loc.t * Parse_error.t`:
```
{ Loc.source = None; start = { Loc.line = 1; column = 12 };
  _end = { Loc.line = 1; column = 17 } }
Unexpected identifier, expected the identifier `from`
{ Loc.source = None; start = { Loc.line = 1; column = 18 };
  _end = { Loc.line = 1; column = 22 } }
Unexpected identifier, expected a string
{ Loc.source = None; start = { Loc.line = 1; column = 18 };
  _end = { Loc.line = 1; column = 22 } }
Unexpected identifier, expected the token `;`
{ Loc.source = None; start = { Loc.line = 1; column = 23 };
  _end = { Loc.line = 1; column = 36 } }
Unexpected string, expected the end of an expression statement (`;`)
```

I was unable to reproduce it on flow.org/try but I can confirm that `Parser_flow.program "export * as Error from './errors.js'"` raises a `Parse_error` exception in v0.183.1 and v0.171.0, and that it does NOT raise in v0.170.0

Thank you!

**Comment by mroch** [comment]
thanks for the report!

do you know if it's 4b9ccbaa specifically? or that just looks the most suspicious in 0.171.0?

`export * as` support is still gated by the `esproposal_export_star_as` parser option. I suspect it's not parsing because you have to enable that option. buuut, this proposal (https://github.com/tc39/proposal-export-ns-from) became standard in 2018! we should definitely remove the option.

I do wonder why the behavior changed in 0.171.0. I wonder if there was a different bug "fixed" in 171 that made it correctly obey the `esproposal_export_star_as` option instead -- thereby making it error by default.

**Comment by SGrondin** [comment]
Thank you for the great response.

> do you know if it's https://github.com/facebook/flow/commit/4b9ccbaa7d9db48b19b686ce7c1668f1f19b76ef specifically? or that just looks the most suspicious in 0.171.0?

Oops, I phrased it as a fact but having just tested it, it turned out I was wrong!
The previous commit (`bb82b352b`) fails as well, so the issue is not specifically due to `4b9ccba`

> export * as support is still gated by the esproposal_export_star_as parser option. I suspect it's not parsing because you have to enable that option

Yes! Awesome, it worked. Thank you

> buuut, this proposal (https://github.com/tc39/proposal-export-ns-from) became standard in 2018! we should definitely remove the option (T127807668 internally).

I'm not a contributor, but as a user this definitely seems like the right answer.

> I do wonder why the behavior changed in 0.171.0. I wonder if there was a different bug "fixed" in 171 that made it correctly obey the esproposal_export_star_as option instead -- thereby making it error by default.

Yup, that's what my sixth sense is telling me, too. Maybe someone could write a `git bisect` script...

**Comment by mroch** [comment]
f360297ed2112e2828d4fe3dc9d75ec2d347ab98 removes the flag
