### ISSUE TITLE
`exact_empty_objects=true` for conditional objects?

### ISSUE THREAD

**Issue by mrtnzlml** [facebook/flow#8916]
Hello! 👋 I am trying to enable `exact_empty_objects=true`; however, there are some occurrences of conditionally set object properties in my codebase. Something like this:

```js
const error = {};
error.message = pragma;
if (locations) {
  const groups = locations.groups;
  error.message = groups?.message;
  error.line = Number(groups?.line);
  error.column = Number(groups?.column);
  error.endLine = Number(groups?.endLine);
  error.endColumn = Number(groups?.endColumn);
}
return error;
```

See: https://github.com/adeira/universe/blob/9ef855a480e1e4496dbcaca25ac3a4181887767f/src/eslint-fixtures-tester/src/index.js#L21-L31

Flow returns the following errors:

<img width="746" alt="Screen Shot 2022-08-10 at 17 56 41" src="https://user-images.githubusercontent.com/978368/184037244-ba08ce27-b2e9-467f-a950-35c0f077cef8.png">

What is the correct approach in this case? What solution do you recommend? Cc @gkz

**Comment by gkz** [comment]
Hi, I will publish a blog post later this year that will describe how to migrate to enabling `exact_empty_objects` (including some codemods).
If you don't want to wait and don't have many errors, you can fix this manually by adding a type annotation to `const error = {};`. The properties you add conditionally should be optional

**Comment by gkz** [comment]
Here is the blog post: https://medium.com/flow-type/improved-handling-of-the-empty-object-in-flow-ead91887e40c
