### ISSUE TITLE
React.createElement children as inner tag content is not typed

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#892]
When I add the `children` as part of the component props type, it only allows to pass it as an attribute in JSX, not as the inner element content:

```js
/* @flow */
import React from 'react';

type Props = {
  children: ReactElement<any, any, any>
};

class Foo extends React.Component<{}, Props, {}> {
  render() {
    return <div>{this.props.children}</div>;
  }
}

// This type checks
React.render(<Foo children={<h1>Hello</h1>} />, document.getElementById('foo')); 

// This fails saying `children` is not specified
React.render(<Foo>
  <h1>Hello</h1>
</Foo>, document.getElementById('foo')); 
```
If `children` were optional in the `Props` type, it would even ignore completely what's passed as the tag inner content. It only pays attention to the `children` attribute.

Perhaps there should be another param in the component to specify the `ChildrenType`? and then somehow merge those two prop types as part of what could be inside `this.props` in the component, and in order to accept children either as the `children` attribute or as the inner tag content.

**Comment by SevInf** [comment]
Any news on this?

**Comment by arypurnomoz** [comment]
Any update on this? v0.20.1 still has this problem
