### ISSUE TITLE
Comment syntax can't use optional args

### ISSUE THREAD

**Issue by Brianzchen** [facebook/flow#8925]
I'm writing a package that's supports straight node so I'm using flow comment syntax. Some of my variables I want to be optional so normally it'd be `a?: string` so with comment syntax I expect it to be `a/*?: string*/`. But I get an unexpected error as shown in screenshot.

Flow version: 0.186.0

## Expected behavior
I'm able to set optional args with comment syntax

## Actual behavior
I can't. Refer to screenshot

<img width="1067" alt="Screen Shot 2022-09-12 at 8 53 43 pm" src="https://user-images.githubusercontent.com/12436524/189636408-62a6c69d-f364-4290-a0c4-4864da79cf99.png">

* Link to Try-Flow or Github repo: https://flow.org/try/#0MYewdgzgLgBAZgVzMGBeGAKAhgfgFwzQBOAlmAOYA0MARgPQBU+hUpFDdAlGgHwwDeAKBgiYWAHRQQAMRIAPAKYATDJwDcw0TUkz5y1RoC+gwaEixEyNJiwFiZKrUZ3WDjt1R8hosTtmKVdU0RbSl-fSDDIA

Issue replicated in try flow

**Comment by mrtnzlml** [comment]
@Brianzchen You can write it like this:

```js
const func1 = (a?: number, b/*:: ?: number*/) => {
    a?.toFixed();
    b?.toFixed();
}

const func2 = (a: number, b/*: number*/) => {
    a.toFixed();
    b.toFixed();
}
```

See: https://flow.org/try/#0MYewdgzgLgBAZgVzMAjDAvDAFAQwPwBcMYCAtgEYCmATgDQzkD0AVAUYcWVdc4wJQYAfDADeAKBiSY+AHRQQAMQCWAD0oATLHwDcEqeTxzFqjVt0BfMWNCRYiZACYM2HERIUa9Jq04ee-IVE9SRwjZTVNHWCGMJNIiyA

It is described in docs as well:

> Note: If you want to use optional function parameters you’ll need to use the include comment form.

See: https://flow.org/en/docs/types/comments/ 😎

**Comment by Brianzchen** [comment]
Ah thank you! My bad for not reading all the docs
