### ISSUE TITLE
Line with $FlowFixMe[prop-missing] should not give [unnecessary-optional-chain] warning

### ISSUE THREAD

**Issue by ToyboxZach** [facebook/flow#8926]
0.186.0

Flow version:

## Expected behavior
No warning
## Actual behavior
[unnecessary-optional-chain] warning

```
const MyObj{
 otherMethod(){}
}

....

   //$FlowFixMe[prop-missing]
   MyObj.methodThatGetsSetInAWeirdWay?.();
```

This is a regression in the latest version, I would assume that if I already say a prop is missing, it should let me use the conditional operator as much as I want in the next line since, the prop may be missing. 

Obviously a workaround is to actually add the right types, but for my specific case it is very annoying to do.

**Comment by SamChou19815** [comment]
I cannot repro the issue with your example on 0.186. The latest release doesn't have this issue.
