### ISSUE TITLE
Incorrect error when assigning value through generic 

### ISSUE THREAD

**Issue by dannyharding10** [facebook/flow#8929]
Flow version: 0.187.1

## Expected behavior
If a value can be assigned to a standard type, those same types should also be assignable when using generics.

## Actual behavior
When assigning between generics, flow gives an error.

* Link to Try-Flow or Github repo: [clicky](https://flow.org/try/#0C4TwDgpgBAglC8UDeUwCcD2YBcUDkAhnlAL4BQokUAQgsqpjvgEbHmXQwA2XdcAPjTIVw0AOIQAdhDQBLAMYAeACoA+OsuFkAJhHlcCaaADdDUArhg69Bo1FNooAcykyFMXBOlylMVWQB6AKgAOQxnVx8oAHcMNABrAGcoADNZaTJ5DElE4ChJbK83eWUMMMkin0seOgJhIKgxDHSnKGAAC0wAVyd2iO8FKG0MCGSCvNiEzOzc-uLSyoVPSIVFbi51RBcB+StA4JhJEA6WtvaCPPT9Lt1kgnzsuajJpOmcvO35ssKV+WreLa-KxZd4PCq-Ba-ZY7NY8TbmLTCIA)

**Comment by SamChou19815** [comment]
This is expected, because you declare `T` as invariant. Check https://flow.org/en/docs/lang/variance/ for more detail.

If you do `type Generic<+T> = T`, then it will work.
