### ISSUE TITLE
Change `SpreadProperty` to `SpreadElement` in AST

### ISSUE THREAD

**Issue by fisker** [facebook/flow#8930]
[Playground](https://flow.org/try/#0BQbwdBCGC+CUQ)

`SpreadProperty` has been remove in ESTree since long time ago, https://github.com/estree/estree/pull/148/files.

Should use `RestElement` to align with other tools.

**Comment by gkz** [comment]
I believe it should be `SpreadElement` in this case? Rather than `RestElement`

**Comment by fisker** [comment]
Ah, yes. Apologize.
