### ISSUE TITLE
Try Flow fails to load

### ISSUE THREAD

**Issue by ablamunits** [facebook/flow#8931]
Flow version: N/A

## Expected behavior

Expecting https://flow.org/try/ to load

## Actual behavior

Try Flow fails to load with the following error:

```
Uncaught Error: Load timeout for modules: vs/nls!vs/editor/common/config/editorOptions_unnormalized2,vs/nls!vs/editor/editor.main,vs/css!vs/base/browser/ui/aria/aria_unnormalized3,vs/css!vs/editor/editor.main,vs/editor/editor.main.nls
http://requirejs.org/docs/errors.html#timeout
    at makeError (require_2_3_3.js:4:1067)
    at h (require_2_3_3.js:4:4042)
    at require_2_3_3.js:4:4238
```

<img width="1604" alt="Screenshot 2022-10-13 at 13 43 25" src="https://user-images.githubusercontent.com/9403859/195587477-f060660a-2b4b-4253-b1a4-df5e9379005d.png">

**Comment by SamChou19815** [comment]
This seems to be transient issue. It should be able to load now.
