### ISSUE TITLE
Flow not reacting to any changes in codebase starting with v0.183.0

### ISSUE THREAD

**Issue by AlbertPrograms** [facebook/flow#8932]
It seems like flow doesn't react to any updates I make in my code, and this behavior starts showing from _v0.183.0_ and up. I've been experimenting with this for quite a few hours now, not knowing the reason of the inconsistency, so I resorted to rolling back versions and this is where I arrived.

_I'm using Windows 10 x64 21H2 with node v16.18.0._

**Flow version**: v0.183.0 and up

## Expected behavior
_Using version v0.182.0_

Running flow on erroneous code produces an error:  
![182 error - error](https://user-images.githubusercontent.com/33540758/196251671-1a94d45a-420c-4467-a52a-9766f9961e41.png)

Running flow on corrected code produces no errors:  
![182 ok - ok](https://user-images.githubusercontent.com/33540758/196251674-5bf6c61d-63c6-4eb2-af01-e34d0bbd9e8d.png)

## Actual behavior
_Using version v0.183.0 and v0.190.0, they both produce the same results_

Running flow on erroneous code produces an error:  
![183 error - error](https://user-images.githubusercontent.com/33540758/196251677-33cf45d3-edbf-44bc-af4e-9ee4a7cbdf6a.png)

Running flow on corrected code still produces an error:  
![183 ok - error](https://user-images.githubusercontent.com/33540758/196251679-2e2b80a4-3c51-4baa-a593-98507790155e.png)

The only way I can get flow to react to the new code is by restarting the flow server, i.e. running `flow stop` and `flow` again.

I can reproduce this seemingly no matter what the other circumstances are. All I need to do it is run the current version of flow and make changes to my files. The output doesn't change unless I stop and restart the flow server.

**Comment by mroch** [comment]
sorry for the trouble, and thanks for the report!

I suspect this is related to the "Fix bug where Watchman events might be ignored on Windows" change in 0.183.0 (and related fix in 0.183.1). if you're not using watchman, it uses our built-in file watcher; we use watchman on everything internally so our own file watcher is ironically less tested.

I'll take a look. if it's feasible for your team, installing watchman (https://facebook.github.io/watchman/) provides a lot of benefits like more reliable change detection, source control integration and "lazy mode".

**Comment by AlbertPrograms** [comment]
Thanks! I'm new to flow so I'm still learning the ropes. I'll install watchman for my test projects for now. I think my team might already be using watchman on the project, since they don't seem to have this issue.

**Comment by CrOrc** [comment]
For now only manually running `flow force-recheck` on changed files might help.
