### ISSUE TITLE
`$Diff` appears to recreate original type instead of diffing

### ISSUE THREAD

**Issue by somewhatabstract** [facebook/flow#8933]
Flow version: 0.190.0

Given type `Pick`:

```js
type Test = {
    a: number,
    b: string,
}

type Pick<T, K> = {
    [K]: T[K];
};
```

I can do the following:

```js
type TestAOnly = Pick<Test, "a">;
// THIS WORKS; try changing a's value to a string or adding values
const x: TestAOnly = {
    a: 4,
    //b: "string",
    //c: 4,
};
```

I can then also do this (you can try it without this step too, this was me experimenting on getting this working, which I couldn't):

```js
type TestAAsAny = $ObjMapConst<TestAOnly, any>;
// THIS WORKS; try adding b, too
const y: TestAAsAny = {
    a: "test",
};
```

Since these two steps work, it follows that this should also work, but instead of giving the difference between the two types (i.e. a type with only `b`), it gives back a type equivalent to the original `Test` type.

```js
type TestNoA = $Exact<$Diff<Test, TestAAsAny>>;
// or type TestNoA = $Exact<$Diff<Test, TestAOnly>>;
// THIS SHOULD BE AN ERROR
// Instead, this type seems to work exactly like the original type Test
const w: TestNoA = {
    a: 5,
};
```

## Expected behavior
It should give the difference of the two types.

## Actual behavior
You can see the actual behavior on Try Flow below.

* Link to Try-Flow or Github repo: [Link to Try-Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAquAzumALxgDeqYdYAhgFxgB2ArgLYBGuATgBpa9bi1J8AlqwDmQgL6oMOfAAUJAYwDWAHgICwAaQB8FasLoBtAwF0WBK9YDcqOc6V5CJdAEEA8qxhMUzUtXS99ACIGCKNnYGBCAAkASQBlMAB1XwAlA1THMHQ+IPUACwYZKWlGAHJiMAA3Bhh2fHQ4RjBxKrA4PkYAEwGeppaSVHU4VlIwAA87Lz8AoMoaekYWABYhdfjRMAjumQid+nj1Lfk3LA8iUm9vYm9WFbAAEl9uACsAWQZsADCU1IYXu-kC+gqmFiqHiSTSmRyeQKRSCDCGPW4+nacAmwLImAW90ez1ea3ozAO6C8Jxc12UnlIADk4N5TG8AKKzBjqdDaN4AEQkUCgoPQ+juPhJLyMMLhBBS6VSiV8AFUADICsAAIQ5YG8TLAHOy2RysISyWm1PR2NKEnqN3wxFwuE4Do6CD6mjAuG5vMCYBgEk0bVK+D6EmkUmahQZkrxVrACCJ6BZbNW5g2YAArFdUEA)

**Comment by somewhatabstract** [comment]
Well, nevermind. I got things working.

See [here](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAquAzumALxgDeqYdYAhgFxgB2ArgLYBGuATgBpa9bi1J8AlqwDmQ+mADGLbnDgxcDVkIC+qDDnwAFCQoDWAHgICwhlgBIAygAsGeSwD53FMHYCiADwYFdHM7ABEJKChLa3DI6KsbT3cAbj19PEISdABBAHlWGExvYzNLbOsqZkZWTGslGsxtVNRgYEIACQBJBzAAdTyAJQBpBxSwdD5ihRcZKWlGAHJiMAA3Bhh2fHQ4RjBxebA4PkYAE1PD9c2SVAU4VlIwfxYiUnzC4soaeWqAFjl6G1RGAAEQHGQggF0BqTLZQsBtU4sEFdfZOODsGCnViLMi8MBOfjbOCnBiYSGobRpDL4V65HLEHK1bx2PLcABWAFlXABhe6kcpvApFayaTAtNqdHr9IajcaTYoMc6HbjWHZwW78siYF7ZHIMpmfajCOjVEHobIU+RA5Hg6RW+gwvhwk0I4BI0Go4jozHY3FgfGEvjE0nknTUrCZOkAOTgORZASCITiUUF6GsdP1jNqnjSkoI3V6Dg6eQAqgAZMJgABCvjAOWjYF8g0GQ1a7S6DwtSrVTgkK0j+GIuFwnAHuwQx1MYFwgWCRTAMAkpm2hKOkmkUg2EwMWVImq7YAQutIsfjX1dwLBk3mFKpqCAA)

My original pick type was not correct (it was causing a union of the value types). Fixing that, seems to have corrected things in my example.

Still, I am confused by what happened above - even with the unioning of types, I would expect it to work in the final stage because this is about omitting the keys.

**Comment by SamChou19815** [comment]
Closing since we now have `Pick`
