### ISSUE TITLE
`$Keys` doesn't include interface extensions

### ISSUE THREAD

**Issue by somewhatabstract** [facebook/flow#8934]
Given:

```
interface A {
    a: number;
}

interface B {
    b: number
}

interface C extends A, B {}
```

One can then define a type, like:

```
type X<K: $Keys<C>> = {|
    x: K,
|}
```

I would expect `K` to be validated against all keys of interface `C`, including those from `A` and `B` that it extends, but instead, it only includes those explicitly listed in `C`.

So, this fails:
```
const x: X<"b"> = {
    x: "b",
}
```

Flow version: 0.190.0

## Expected behavior
Given the example above, keys from extended interfaces should be valid.

## Actual behavior

The keys from the extended interfaces are not included by `$Keys`.

* Link to Try-Flow or Github repo: [Try Flow](https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoAlgOwC4FMBOUAhgMa5gCCYA3qmPWEQFxiYCuAtgEYEDcqAX1QYcBYmTAAhGnQZcW7bgUHCseQqXIBhMLgAeeTABMAzpQA0UmkNTYAngAdyADQA8AaRYASd7jsnXLQA+ILAAXhoAH1l6PRZ3c1RIm2BgMAAVAAt0MxNMuDYYIzAEOHwAawBCVBI4TBNsMDiwNwAiLlbQiNoGJpZ21sSbIA)

**Comment by gkz** [comment]
`$Keys` only gets "own" keys (as far as we analyze "own" vs not properties). This is so a runtime operation `Object.keys` models this type operation (somewhat)

**Comment by muratkorkmaz106** [comment]
![image](https://user-images.githubusercontent.com/101784453/200150650-1d51c171-ec8f-48c7-af3b-aa7898aa8f2b.jpeg)

**Comment by somewhatabstract** [comment]
OK, understood. That makes sense.

That said, it's things like this that make Flow seem more academically interesting that practically applicable. I feel we spend more time fighting it to describe what we need than to get things done. Perhaps it's just a mindset thing.

In the end, I had to create two types - one where we combine interfaces together into one through `extends` and another where we combine the keys of those interfaces as a separate `KeysOfThePrimeInterface` type.

Thanks for the response and all the work.

**Comment by gkz** [comment]
Are interfaces the right choice here, or would object types combined with object type spread work better? TypeScript doesn't have object type spread so people often lean on interfaces, but in Flow object type spread is probably the better choice most of the time

E.g.

```
type A = {
    a: number;
};

type B = {
    b: number
};

type C = {
  ...A,
  ...C,
};

type X<K: $Keys<C>> = {
    x: K,
};

// works
const x: X<"b"> = {
    x: "b",
};
```

**Comment by somewhatabstract** [comment]
That's a great question and unfortunately, that wasn't going to work because I couldn't get function overloading working with non-interface types and that is needed for the thing I was working on.

**Comment by gkz** [comment]
Note you can still type overloaded functions in object like so:

```
type C = {
    m: (string => 1) & boolean => 2
};
```
https://flow.org/try/#0C4TwDgpgBAwlC8UDeAoK6oFsBcUAUAzsAE4CWAdgOYIB8UAjAJRQBkUARgPacA2EAhuVpQATCgC+AbhQoAJhADGPfsWgA3FVAW4Y0vAoB0mPACIixE41xM9h4yQCuEK6MaSgA

**Comment by somewhatabstract** [comment]
Yes, unfortunately, for what I was working on that was going to be a lot more work.

I had some third-party types I was converting from TypeScript to Flow and rewriting them so that we overloaded functions that way was going to be a much bigger lift than using interfaces to combine overloads.

**Comment by somewhatabstract** [comment]
It's a lot easier to compose things using interfaces than creating types for each overloaded function and then combining each one.
