### ISSUE TITLE
Default value is not validated when deconstruction is used

### ISSUE THREAD

**Issue by taavisildeberg** [facebook/flow#8972]
Flow version: 0.196.1

## Expected behavior
 Default value is validated against literal values

## Actual behavior
Default value is not validated and 

* Link to Try-Flow or Github repo:
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVxhgCQFEAeADgKYDGALrgE5VxVgB2AhgLbFgAmxUTArjOTAA3JjF7sAzgAs4-DmABG7ETACWHJuWIdUUXgwqq4DMAHNi5AMJx4VAEwAKAN7M2YALxgA5Bwm+OXgC+AFwurMTBYABEErykpMQSElFgAD7RCExUDKoMpinpURp5xFRRgQCUYE6oYGASCKrkpFJgDq7EVTV1daRMEuwxcQlJKZFUFrzZ0aYTxAxRANy1PX0DGVk5eWNgE+RTJlEAnsQw8AhLK739g8XmZXXjk9NRExyXdYGoX+jmVjZ0RxhNiRIbxRLJSqLMCYMAAdToAGsJABCVB-ay2IEdYJFJglMpQuqwhFUZFo2F4IhkSg0OjoiyYwHOHFRUq0QkVaHErDUDkooA

**Comment by gkz** [comment]
Thanks for the report

**Comment by SamChou19815** [comment]
This issue is caused by Flow's existing unsoundness wrt literals, where they exist in a superposition state of being a literal and being a more general type, which causes bug like this. We might be able to fix that next year.
