### ISSUE TITLE
Singleton classes 

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#898]
It is not obvious how singleton classes can be annotated via flow I tried bunch of things without much success and finally end up with something like this:

```js
/* @flow */

export const None = function None()/*:{$typeof: "Effects.None"}*/ {
  if (None.instance == null) {
    this.$typeof = "Effects.None"
    None.instanceof = this
  }
  return None.instance
}
```

This works for a simple case but I feel like more complex case would be a lot more difficult to annotate. I think this deserves own entry in the docs.

**Comment by samwgoldman** [comment]
I'm all for improving the docs. I don't think what you have here is very actionable, though. What could you have read in the docs that would have helped you?
