### ISSUE TITLE
Declare class factories, such as Backbone Models?

### ISSUE THREAD

**Issue by marosurbanec** [facebook/flow#899]
Extensive googling and reading through docs and examples didn't show any example of a very common pattern in Javascript - having functions that return classes. A canonical example is Backbone:

```
var User = Backbone.Model.extend({
  getFullName: function() {
    return this.get('firstName') + ' ' + this.get('lastName');
  }
});

var exampleUser = new User();
exampleUser.set('firstName', 'Johny'); //set() is a method from Backbone.Model
exampleUser.set('lastName', 'Something');
exampleUser.getFullName(); //method coming from User class
```

In JSDoc, I could annotate the class as follows, with some IDEs being able to figure out a decent autocompletion:

```
/**
 * @class User
 * @augments Backbone.Model
 */
var User = Backbone.Model.extend(/**@lends User.prototype */{
  getFullName: function() {...}
});
```

Is there any way how to properly annotate this pattern in Flow?

**Comment by HerringtonDarkholme** [comment]
You can use intersection type to annotate `extend`. http://flowtype.org/docs/union-intersection-types.html#_

**Comment by marosurbanec** [comment]
Do you mean to collect all possible return types in a construct like this?

```
class Backbone.Model {
  static extend: ((clsDef: any) => Class<User>) & ((clsDef: any) => Class<Permission> & ((clsDef: any) => Class<UserGroup>);
}
```

That still leaves the question of how to tell Flow about the new type. The only possible way I can think of is to duplicate the information in a separate "type" construction (below), which mandates each method or property to be duplicated.

```
declare class User {
  getFullName(): string;
};

var User = (Backbone.Model.extend({
  getFullName: function() {
    return this.get('firstName') + ' ' + this.get('lastName');
  }
}): Class<User>);
```

**Comment by HerringtonDarkholme** [comment]
```
declare class Backbone.Model {
  static extend<T>(def: T): Class<T & Backbone.Model>
}
```

I think this issue should go to stackoverflow...

**Comment by marosurbanec** [comment]
I agree, the issue moved to 
http://stackoverflow.com/questions/33023860/flowtype-how-to-write-declaration-for-class-factories-such-as-backbone-models
