### ISSUE TITLE
Flow stops immediately after initial check

### ISSUE THREAD

**Issue by CrOrc** [facebook/flow#8991]
**Flow version:** v0.198.1 and v0.198.0
_I'm using Windows 10 x64 21H2 build 19044.2486_

## Expected behavior
Flow makes initial check and continues watching for changes in filesystem.

## Actual behavior
Flow makes initial check and stops immediately.
Checked it with both default filewatcher and with watchman, e.g.
```
flow start --file-watcher watchman
```
Flow version v0.197.0 starts normally and continues watching for changes in filesystem.
Using watchman because of issue #8932

**Comment by mroch** [comment]
Sorry about this! It's fixed by 97939527c92c0f09c44349e72ef41c577073e7b9 and we'll do a patch release today.

**Comment by mroch** [comment]
just released 0.198.2
