### ISSUE TITLE
Internal type checking error under local type inference

### ISSUE THREAD

**Issue by flex-tjon** [facebook/flow#8998]
Flow version: 0.198.2, `inference_mode=lti`

## Expected behavior
No type errors under local type inference

## Actual behavior
There's an internal type checking exception and an `incompatible-type` error that I think is a consequence of the internal exception. 

* Link to Try-Flow or Github repo: [Link](https://flow.org/try/#0FAFwngDgpgBAagQwDYEsAmBlKCBOBjACwAUEUcYBeGAb2BhgGokEAjKJALhgGcQcUAdgHMANHUYA3ZAFco3LgBIAStjQB5AUjABBHDgRgAPL37CAfGIC+AbmChIsLLkIkylGuKat2XAPwnBUU8pJFl5GF9lVQ0tXX0jAPMrW3toGCIcAHsIbndaegZMgW0ICC0uAApudig8ECg0RRUEdU0dPQNDRFRMbHxiUhwzAEpKMxgJTPQxArwcbHre5wGycKiWmPb4ruR0J37XIZnGAEdZHDAuBAEwZLs0WuZ5idwYASgAd32XQbXm1tiHSM3xWQ1sDzwT1gUnIECyOS4GWy3BSEKhMAAZtIBHUUEUYHgiiBSAJuABJAQhdCHbgVdYAradEGHEZcFiZTJIbACcGPXCwLE4kB4gQ8KAgDAETIfACiekyOAq7M53OGXEm6BShNJIBePRp7neXz6P1WADp5mhpHgoIZxPQHY6nY64p1unsTaCzPbnb76GYKhUqWgaSIYBBBqMKON8n64-QUBiYBUffG-RGyGaQmFKFQBNIkEgYAAfYuptPOjM4M3MNhFih5gtF0vliuOqtZmRyGtQYQgAi5qgABlbbdGsbbvvmIGkOFFwZptknzssdmXTu1vD11MGeVHk9rPnDgxr3iQx3Xjuzci4Hev3Avl5s+7TC9+Zog0m4BCDuxDkaXS96GnWd5z-RcXz9SwwwqABtABdLh3SWA5BgQ4ZhhSIDE2TbViUEclKXA34KiNZlfgwjwgPoaoJSlWV5UVPhZEwyDfUsGB2GqKjqLhZEzSKEoyjAX99QowCgNoyVpTlLJFQxZBqlYoDLCAA), need to check with master branch to see the errors under LTI

**Comment by mvitousek** [comment]
Thanks so much for the report and repro! We've identified the issue here and will have a fix in the next release. For now you can avoid this issue by adding an annotation to the declaration of `validPair`, which will address both errors.

**Comment by flex-tjon** [comment]
Ah awesome, thank you for your quick response! Glad to be unblocked for now 😄
