### ISSUE TITLE
Question: Should this be parse error?

### ISSUE THREAD

**Issue by fisker** [facebook/flow#9000]
I was working on Prettier to make tests run both `flow` and `babel-flow` parser https://github.com/prettier/prettier/pull/14245, and found an edge case.

https://github.com/facebook/flow/blob/f87d5bf972f47f14e8e51f8ad26da82a96770175/tests/generics/generics.js#L40

`flow` can parse `function` as identifier, but `babel` can't, and I found other keywords like `class`/`while` can't be used there.

Should it be valid or invalid?

**Comment by gkz** [comment]
I found it surprising and weird that `function` (lowercase) can be used as a type. Support for this was added when support for the `Function` type was added, back in 2015, but I am not aware of anyone actually using this (or even being aware of this). I would be happy to remove support for this and make this an error.

**Comment by fisker** [comment]
Thanks for the explanation, feel free to close if it not worth to fix.

**Comment by gkz** [comment]
I have a diff in progress to make it an error, just needs to be reviewed (internally)
