### ISSUE TITLE
Predicate functions causing internal typechecking errors

### ISSUE THREAD

**Issue by flex-tjon** [facebook/flow#9004]
Flow version: 0.199.0

## Expected behavior
No Flow errors in this code snippet

## Actual behavior
Flow raises internal typechecking errors. This seems to be a not infrequent issue with predicate functions (returning `boolean %checks`) in 0.199.0 that I didn't notice in 0.198.1.

* Link to Try-Flow or Github repo: https://flow.org/try/#0GYVwdgxgLglg9mABDAzgJQKYRAJxTANwzQEMoMAKHMjALkQG8BqKATwAc7EUocYwA5gBpEAOnEBfAJT0ARnDgAbDCSQBSCAAssAaxSMAUImOIcGKLiQUjJ6uVFtOiALyvEAIjPY8hDAH0IBB5VKHdEAB9wm2M7DAcODBc3TyxcfCI-WRJ8FDDI6NMaeKdXZw8vNN8-FBAAWzyok0L7R0TS8tSfDPYcOAATEGgGgtjituSKrv9akgAPYabR1qSylO906f4F2yLl9rXKjPxa9mVMsxIdbZjdhJWO9aqtBRQMdxspAG4DCQMDDFm7DgOCgiECYB4iBAr3QnQ2ACFshh9GVrDdyPQAPzMVr0Hh8QQicSiX4yRDyJQqdRaXQogB8NnhCmUqjRO3IiAAZJyCsYKKhMI8iKRyFQaFIIo0muy4ntksBgbUQIoSNdpQB6dWIAAkADFFHAAO66mCzACyGAA2vxAicyDBZMoALStAC6vJlY3u7lkFyuUg+nyAA

**Comment by SamChou19815** [comment]
You can workaround this problem for now by rewriting the predicate function as a function declaration instead of an arrow function:

```js
export function usesRecursiveBases(
  rate: ?{+type: string, ...}
): boolean %checks {
  return Boolean(
    rate &&
      (isRecursiveRate(rate) ||
        rate.type === "formula" ||
        // $FlowFixMe[incompatible-type]
        rate.type === "break")
  );
}
```

We will try to fix this soon, but now our predicate function support in non-function declarations seems to be very buggy.
