### ISSUE TITLE
Incorrect node location

### ISSUE THREAD

**Issue by fisker** [facebook/flow#9016]
Flow version: 0.201.0

## Expected behavior

```js
type A = (
  | B 
  | C
)[]
```

The `ArrayTypeAnnotation` should start from line 1.

```js
type A = (
         ^ Should start from here
  | B 
  | C
)[]
```

## Actual behavior

The `ArrayTypeAnnotation` start from the first `elementType`.

* Link to Try-Flow or Github repo:

https://flow.org/try/#0C4TwDgpgBAglC8UAUBYAUFKAfKAhK6mOAwugJQDaAukA

**Comment by mroch** [comment]
thank you for the great bug report (as usual)!
