### ISSUE TITLE
Flow does not typecheck code if the magic comment is not on the first line

### ISSUE THREAD

**Issue by DanielHeath** [facebook/flow#902]
This means it is easy to create files which look like they are typed, but are silently ignored.

It also means that you can't start a typechecked file with `#!/usr/bin/env node`.

**Comment by gabelevi** [comment]
https://github.com/facebook/flow/pull/903 would solve your problem :)

I think we're using https://github.com/facebook/flow/issues/284 to track this feature request, so I'm going to close out this issue. Thanks for reporting though!
