### ISSUE TITLE
Sometimes Flow reports error without indication of its location

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#904]
```
function onClick(e: SyntheticMouseEvent & {target: HTMLElement}) { /* ... */ }
function render(callback: (e: SyntheticMouseEvent) => void) { /* ... */ }
render(onClick);
```

will result in the following error message:

```
test.js: inconsistent use of library definitions
[LIB] dom.js:64:1,68:1: EventTarget
This type is incompatible with
[LIB] dom.js:392:1,425:1: HTMLElement
```

Note that the error message gives no indication as to where the error has actually occurred. If the source file is sufficiently big, locating this error becomes extremely hard. And if the functions are defined in separate external files -- nearly impossible...

**Comment by calebmer** [comment]
This should no longer be an issue. If you are still having a problem with this please let us know 😊
