### ISSUE TITLE
[flow-remove-types] doesn't remove some types

### ISSUE THREAD

**Issue by headfire94** [facebook/flow#9043]
## Expected behavior

tool removes all types from file

## Actual behavior

only particular types removed

* Link to Try-Flow or Github repo: https://github.com/headfire94/flow-remove-types-example

See source file https://github.com/headfire94/flow-remove-types-example/blob/master/index.js
and output https://github.com/headfire94/flow-remove-types-example/blob/master/output.js

Output contains following line with types
```
const _getRequest = retry(
    (url        , params: {} = {}, endpointFn: function): Promise<any> =>
fetchival(`${endpointFn()}${url}`, { timeout: HTTP_GET_TIMEOUT }).get(params),
    { delayTimesMs: ['5s', '10s'] }
)
```

**Comment by panagosg7** [comment]
The input file has a parse error, due to the keyword `function` that is used as a type. If you change that, then remove-types works as expected.
