### ISSUE TITLE
flow_parser.js file increased from 0.7M to 2.7M in v0.210

### ISSUE THREAD

**Issue by fisker** [facebook/flow#9044]
The package size is too big, Prettier unable to upgrade it. https://github.com/prettier/prettier/pull/15002#issuecomment-1617127383

**Comment by SamChou19815** [comment]
Thanks for the report. We are looking into this. We will cut a release soon so it likely won't be fixed in 0.211.0, but this is definitely something we want to improve.

**Comment by SamChou19815** [comment]
https://github.com/facebook/flow/commit/b28958a35758f957d8e6a856e532b49e5c6101b2 seems to cause the bloat.

**Comment by SamChou19815** [comment]
Well, looks like I manage to fix it because I do the release.

**Comment by fisker** [comment]
Thank you!
