### ISSUE TITLE
`Omit` does not work well with unions

### ISSUE THREAD

**Issue by lazytype** [facebook/flow#9046]
Flow version: 0.211.0

## Expected behavior

The following code has no type error
```js
const object: Omit<
  | {
    type: 'A';
    data: number;
    a: number;
  }
  | {
    type: 'B';
    data: string;
    b: string;
  },
  'type'
> = {data: 42, a: 42}
```

## Actual behavior

Flow displays multiple errors

* Link to Try-Flow or Github repo: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAJwKYEMwBcD6aArlLnALYYrgA2WAzvXGCADQgYAeOBARgJ74AJhhhYiNXClzEM7DFCLl602e0hQhcMtCw18ufgAcqyGUTkhyWIyaEHjp85a4m0FBbj0A6QyfwIRFhoQipmsgC+6hAi1AD0AFQABAACMDQQAO5JCXEAOlAFGvS4SRC8AFYYeMhJAPLk2gA8BUlJAD5JwK1tSX4YtQDkAIKDANw9bUJYXrWK5LwYaBNQvUlYc0qLyz0RPZ3dq739QwBC45NJ07NJJe5QCCtrvLV3cA9PSVE9g-2DBQA+JIAXi61w2SQALAAmVjrWowiIrNggABuSyY0GoqIADN5oQBGAneHEgCJAA

**Comment by jbrown215** [comment]
Addressed by https://github.com/facebook/flow/commit/328d949f19c7b9d146e5613355e5e6590b4a2883 and coming out in 0.211

**Comment by lazytype** [comment]
@jbrown215 I see the following error in the playground
> TryFlow encountered an internal error: [0,[248,"Jsoo_runtime.Error.Exn",35],{}]

**Comment by jbrown215** [comment]
I confirmed in a local project that it works. Not sure why it makes the playground overflow
