### ISSUE TITLE
Allow to import types from other modules in module declarations

### ISSUE THREAD

**Issue by leoasis** [facebook/flow#905]
It is a very common case to depend on types defined in other modules to declare the API for a new module that depends on it. Currently the only way to make this work (AFAIK) is to define the types globally in the module that is depended on, and use that directly. It would be great to be able to use `import type` in the declaration files just as with regular code.

What's odd though is that I first tried to do that, and the `import type` line was at least making flow recognize the types being imported. The problem seems to be that is just loads the identifier (and not the type definition), so it doesn't type check. To show an example:

Given the following config:

```
[ignore]

[include]

[libs]
interfaces/

[options]
module.system=node
```

And the following two module declarations:

```js
// bar.js
declare type bar$Bar<T> = (t: T) => T;

declare module 'bar' {
  declare type Bar<T> = bar$Bar<T>;
}
```

```js
// foo.js
import type { Bar } from 'bar'; // would be nice to use this, but does not work

declare module 'foo' {
  // Note: using the global type, not the imported one
  declare function doWithBar<T>(bar: bar$Bar<T>) : T;
}
```

And this code that uses all this:

```js
/* @flow */

import { doWithBar } from 'foo';

doWithBar(); // On purpose missing the parameter, so it causes a type error
```

As it is like this, Flow will correctly show 
```
index.js:6:1,11: function call
Error:
index.js:6:1,11: undefined (too few arguments, expected default/rest parameters)
This type is incompatible with
interfaces/bar.js:1:27,37: function type
```

But if I change the `foo.js` declaration to use the imported type:
```js
// foo.js
import type { Bar } from 'bar';

declare module 'foo' {
  declare function doWithBar<T>(bar: Bar<T>) : T;
}
```

The code no longer fails to type check (No errors).

But Flow seems to understand this a little at least, since if I remove the `import type` line from the declaration, Flow will yell at me saying:
```
foo.js:2:38,43: identifier Bar
Could not resolve name
```

It would be nice to have this way to import type dependencies in the module declarations, to avoid polluting the global namespace with ad-hoc namespaced types, like `bar$Bar`.

**Comment by jeffmo** [comment]
This is finally on my near-term plate, and we're going to be chatting more about it over [here](https://github.com/flowtype/flow-typed/issues/16) -- so lets consolidate discussion there.
