### ISSUE TITLE
Cannot return class type as T: Cannot return `root(...)` because a call signature declaring the expected parameter / return type is missing in `SomeModel` [1] but exists in  function type [2].Flow(prop-missing)

### ISSUE THREAD

**Issue by DominicTobias** [facebook/flow#9073]
I have defined `root` as:

```ts
export declare function root<T>(init: (dispose: Dispose) => T): T;
```

```ts
// @flow
import { root } from "@maverick-js/signals";

export class SomeModel {
  static idAttribute: string = "symbol";
}

export function createSomeModel(): (dispose: Dispose) => SomeModel {
  return root(() => new SomeModel());
}
```

It's unfortunate that Flow can't seem to infer the return type but I think that's correct?

However I get this error:

```
Cannot return `root(...)` because a call signature declaring the expected parameter / return type is missing in  `InstrumentV2` [1] but exists in  function type [2].Flow(prop-missing)
```

I tried to explicitly tell it the type but no difference:

```ts
root<SomeModel>(() => new SomeModel())
```

I'm confused as I don't understand how Flow could not know the return type when calling `new SomeClass` (of course it's the instance of the class). So I'm unsure how I can get it to understand that?

**Comment by SamChou19815** [comment]
The error is expected, although the error message is bad. The function `createSomeModel` is expected to return a function `(dispose: Dispose) => SomeModel`, but you returned `SomeModel`

**Comment by DominicTobias** [comment]
> The error is expected, although the error message is bad. The function `createSomeModel` is expected to return a function `(dispose: Dispose) => SomeModel`, but you returned `SomeModel`

Oh damn of course, thanks!
