### ISSUE TITLE
Recursive/deep Partial

### ISSUE THREAD

**Issue by DominicTobias** [facebook/flow#9079]
I'm trying to convert a TS .d.ts and it has a def for recursive partial which `flowgen` failed to properly convert as it uses `infer`:

original TS:

```ts
declare type DeepPartial<T> = {
	[P in keyof T]?: T[P] extends (infer U)[] ? DeepPartial<U>[] : T[P] extends readonly (infer X)[] ? readonly DeepPartial<X>[] : DeepPartial<T[P]>;
};
```

And there are some online discussions about this for TS: https://stackoverflow.com/questions/41980195/recursive-partialt-in-typescript

I couldn't find anything about it in Flow. Is it possible?

This is what flowgen did (`X` is undefined):

```js
type $FlowGen$If<X: boolean, Then, Else = empty> = $Call<
  ((true, Then, Else) => Then) & ((false, Then, Else) => Else),
  X,
  Then,
  Else,
>;

type $FlowGen$Assignable<A, B> = $Call<
  ((...r: [B]) => true) & ((...r: [A]) => false),
  A,
>;

declare type DeepPartial<T> = $ObjMapi<
  T,
  <P>(
    P,
  ) => $FlowGen$If<
    $FlowGen$Assignable<$ElementType<T, P>, U[]>,
    DeepPartial<U>[],
    $FlowGen$If<
      $FlowGen$Assignable<$ElementType<T, P>, $ReadOnlyArray<X>>,
      $ReadOnlyArray<DeepPartial<X>>,
      DeepPartial<$ElementType<T, P>>,
    >,
  >,
>;
```

Which is also very complex compared to TS. Thanks!

**Comment by SamChou19815** [comment]
Flow now supports conditional type and mapped type, so you can write down a similar one:

https://flow.org/try#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIACLYbCMAAKVH83AAPAAVAB8WIAvFjgAAdKCMiQAbUJWPSWJ6tAgMCxFIAugB+ZBY5lYqWCjlCrEKBpQNgkLEACnSP0oWIAqgBKNlykW4-FEknFXBk7VUg1Y8WS6UU2Xy+SK5VYgAkACVWGwAPJQXC0ACC1DoZI1JixAA0aUavT7-YGQzRaGS8QTiZRSRaYzTkPapY7CXKFYI3fZTFAEFiAD5Y4QiGa1rFoYjLKBYo1FoUF23GjNm8ndqkAbmZSLHLKVdVwVGwWNs9ixEDQACtxenTVnzWTgBhxcA0AewOLk2HgGwD9hxRX0ggkUiqQ-H5OV6urBgRVY0F+wF+2QADEKVhsF+2CTjEID5CYJBwNAQT5ABVgAEwAIwAGxWKhIBIkAA

flow-gen is not maintained by us, so you need to contact the maintainer of flow-gen to add support for newer features.

**Comment by DominicTobias** [comment]
> Flow now supports conditional type and mapped type, so you can write down a similar one:
> 
> https://flow.org/try#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIACLYbCMAAKVH83AAPAAVAB8WIAvFjgAAdKCMiQAbUJWPSWJ6tAgMCxFIAugB+ZBY5lYqWCjlCrEKBpQNgkLEACnSP0oWIAqgBKNlykW4-FEknFXBk7VUg1Y8WS6UU2Xy+SK5VYgAkACVWGwAPJQXC0ACC1DoZI1JixAA0aUavT7-YGQzRaGS8QTiZRSRaYzTkPapY7CXKFYI3fZTFAEFiAD5Y4QiGa1rFoYjLKBYo1FoUF23GjNm8ndqkAbmZSLHLKVdVwVGwWNs9ixEDQACtxenTVnzWTgBhxcA0AewOLk2HgGwD9hxRX0ggkUiqQ-H5OV6urBgRVY0F+wF+2QADEKVhsF+2CTjEID5CYJBwNAQT5ABVgAEwAIwAGxWKhIBIkAA
> 
> flow-gen is not maintained by us, so you need to contact the maintainer of flow-gen to add support for newer features.

Very nice, thanks! Cool to see flow can do it cleanly
