### ISSUE TITLE
Type check react with addons

### ISSUE THREAD

**Issue by teod** [facebook/flow#909]
We are trying to type check some react components that also are using the react with addons.
We are getting the **react/addons Required module not found** error everywhere ReactWithAddons is imported:

``` javascript
import ReactWithAddons from 'react/addons';
```

I think addons is missing from the default flow [react.js](https://github.com/facebook/flow/blob/master/lib/react.js) lib definitions.
This is our current .flowconfig:

```
[ignore]
.*/node_modules/react/.*
[include]

[libs]
../interfaces/*
```

Manually copying the react.js lib definitions and adding them to the interfaces folder, will give incosistent use of library definitions error:

```
inconsistent use of library definitions
/tmp/flow/flowlib_3bb4def6/react.js:68:1,73:1: ReactElement
This type is incompatible with
/../interfaces/react.js:68:1,73:1: ReactElement
```

Manually adding `declare var addons: any;` to the react.js lib definition and using the addons directly:

``` javascript
somecomp.jsx

1. import React from 'react';
2. var PureRenderMixin = React.addons.PureRenderMixin;
```

will still return an error:

```
somecomp.jsx:2:29,34: property `addons`
Property not found in
somecomp.jsx:1:8,12: module react
```

Can you please advise how we can overcome this problem ?

**Comment by samwgoldman** [comment]
Ultimately we need to allow React to provide its own type declarations, including separate ones for addons vs. no addons. I also believe people are actively working on that, so if you sit tight, there should be a solution eventually.

Until then, the current workaround is to copy the flowlib stuff into your project and run flow with the `--no-flowlib` option. At that point, you can modify the local copy (adding a module for `'react/addons'`, say) until Flow is convinced of the correct types.

**Comment by TrySound** [comment]
Is this still relevant? Addons was extracted from react, so it shouldn't be a problem now.

/cc @vkurchatkin
