### ISSUE TITLE
[Question]: How to fix flowgen test after flow update

### ISSUE THREAD

**Issue by DominicTobias** [facebook/flow#9090]
### What do you want to know?

I'm updating a couple of things in [flowgen](https://github.com/joarwilk/flowgen) (since Flow now supports most of the missing utils)

After updating flow-bin to 0.217, [this test](https://github.com/joarwilk/flowgen/blob/master/src/__tests__/spread.spec.ts) started to fail:

```js
it("should use spread when performing union of object types", () => {
  const ts = `
type Foo = { foo: number };
type Bar = { bar: string };
const combination: Foo & Bar;
`;
 // ...
```

The jest snapshot is now invalid:

```
exports[`should use spread when performing union of object types 1`] = `
"declare type Foo = {
  foo: number,
  ...
};
declare type Bar = {
  bar: string,
  ...
};
declare var combination: { ...Foo, ...Bar };
"
`;
```

[Playground](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCGiWVGwAAIWsYcQAxYg4gC8OOAAB0oDicTBiMgccIRDNeNTaVZOdSkQBuamY3DYvFrHEAISoZIp7JxmEojPspigCDZNJxnKs3L5UAFQuOOMgLPSkTg0EZwDVnOJEF4Fqs4soON5MRA+RMJBNUCC+QADFYAEwARgA7P6QEigA)

I understand the principle that `Bar` has a spread and so could contain `foo` of the wrong type, but what is the correct way to do this in flow so I can fix the logic? Thanks

Edit: Looking at [intersections/#toc-intersections-of-object-types](https://flow.org/en/docs/types/intersections/#toc-intersections-of-object-types) it seems like the correct output should be `declare var combination: Foo & Bar`?

Edit edit: Assume that's correct, raised a PR: https://github.com/joarwilk/flowgen/pull/201

**Comment by SamChou19815** [comment]
I think the change is due to Flow changing the default of `exact_by_default=true` around 0.200.

`declare var combination: Foo & Bar` looks reasonable to me. Although you can also choose to interpreting all TS object types as exact, so that the spread can continue to work.

Does this answer your question?

**Comment by gkz** [comment]
There is a blog post about the exact by default change: https://medium.com/flow-type/exact-object-types-by-default-by-default-cc559af6f69

**Comment by DominicTobias** [comment]
Thanks for the info makes sense!
