### ISSUE TITLE
Importing compiled flow libraries

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#910]
I've being struggling to type check apps that use compiled flow libraries.

The problem is that in my program I import a package 'foo' who's `package.json#main` points to `./dist/index.js` where dist file are generated via babeljs and have an [UMD](https://github.com/umdjs/umd) format and look roughly like this:

```js
(function (global, factory) {
  if (typeof define === 'function' && define.amd) {
    define(['exports', 'react'], factory);
  } else if (typeof exports !== 'undefined') {
    factory(exports, require('react'));
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports, global.React);
    global.index = mod.exports;
  }
})(this, function (exports, _react) {
  'use strict';
/*::
  import type {VirtualElement} from "reflex/src/core";
  import type {Address} from "reflex/src/signal";
  
  type RenderTarget = Node|Element|HTMLElement;
  type Configuration = {target: RenderTarget};
...
```

What this gives us is:

- If you ignore `dist` flow fails to import foo and fails to type check for that reason.
- If you do not ignore `dist` it will attempt to also type check `foo/dist/index.js` and still fail but in this case with "Unexpected token import", presumably because imports supposed to be at the top level not inside the function.

Either options seems bad though and even if flow was able to handle `foo/dist/index.js` and not complain about import inside a function it still would not be ideal as comments could be stripped out in dist files. It would make much more sense if it was passible to tell flow that source for this package is in this in this directory. I guess it has to be something like `[include]` directive but with a package name mapping so that imports would be resolved correctly.

Another (probably better) alternative could be to introduce "flow" field for the `package.json` so that `package.json#flow.main` could take precedence over `package.json#main` when flow resolves import path.

**Comment by Gozala** [comment]
Note that this issue arises only if your program A depends on flow checked library B that depends on flow checked library C.

**Comment by Gozala** [comment]
I think #838 is somewhat relevant here as it could have resolved this issue.

**Comment by Gozala** [comment]
Posting a quote from IRC that helps with this issue:

```
2:13 PM — •jeffmo looks for the docs on module.name_mapper ...
2:14 PM <•jeffmo> gozala: This *might* do what you’re looking for: http://flowtype.org/docs/advanced-configuration.html#options (see “module.name_mapper")
2:15 PM <•jeffmo> it lets you intercept Flow’s internal module name resolution steps
2:15 PM <•jeffmo> by specifying a regexp replacement pattern
2:15 PM <gozala> jeffmo: oh right I have not realized I could use that for this
2:15 PM <gozala> jeffmo: thanks
2:15 PM <•jeffmo> Maybe you could specify that “node_modules/your_package” maps to “node_modules/your_package/pre-build-version.js"
```

**Comment by Gozala** [comment]
I'm keeping this one open as I still think that mapping via `package.json` field is worth having specially because .flowconfig based configuration becomes more complicated with a number of libraries (see #238 )

**Comment by AgentME** [comment]
Relevant: https://github.com/facebook/flow/issues/593. I just did with a manual work-around:
>For my [ud](https://github.com/AgentME/ud) library, I've included [a hand-written Flow type declaration file](https://github.com/AgentME/ud/blob/master/flow-lib.js) and [instructions in the readme](https://github.com/AgentME/ud#types) to include that file under the [libs] section of the application's `.flowconfig` (and instructions on working around Flow bug #676).

>It would be convenient for users if I could specify the Flow declaration file [in package.json like Typescript supports](https://github.com/facebook/immutable-js/blob/45bf542ad583545fe6759a7310e0303f43d56b0b/package.json#L18).

**Comment by samwgoldman** [comment]
I think there's room for improvement here, but we've implemented a scheme where you can include `.js.flow` files in your npm module, and Flow will use those instead of the corresponding `.js` files. Check out [the "flow" build step in the fbjs project](https://github.com/facebook/fbjs/blob/9271b3676ceec5fc77f8bf23523f143ec89fb983/gulpfile.js#L68) for an example of this in practice.
