### ISSUE TITLE
Can't iterate through chars in a string

### ISSUE THREAD

**Issue by Ashoat** [facebook/flow#9103]
Recent versions of Flow are printing type errors when iterating through a `string`: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCtnsAAJ7JQsQBeLEAHRAOTwRBJAG4iVAaTAIHiABSYiRY154iAwHFSACUWOANKxQrZ0BIEFKViICEZuJ51KgSJpdIZWOZotZ7IAkmx5Fj0tzKHyBVBhSK7OLsJKINLcQBtLU6gC6cppSJiIHyJhIcGgQXyAAYrAAmIOBgCMICRQA

I could iterate using a classic indexed `for` loop, but I'm a little confused about why Flow doesn't let you use `for-of` or `for-in` with a `string`. My understanding is that this is kosher in JavaScript, but I may be wrong.

**Comment by Ashoat** [comment]
It looks like `for-of` was working before Flow v0.200

**Comment by SamChou19815** [comment]
This is intentional to avoid footguns like `new Set(someStr)`. If you want to do this anyways, you can use `for (const s of new String(someStr)) {...}`

**Comment by Ashoat** [comment]
Fair enough, thanks for the quick response!

**Comment by gkz** [comment]
Yes, this change was made to make it so primitive values were no longer subtypes of `interface {}` (see new  https://flow.org/en/docs/lang/type-hierarchy/). This caused more issues than it was worth.
