### ISSUE TITLE
Conditional type only works if I inline it

### ISSUE THREAD

**Issue by mwiencek** [facebook/flow#9107]
Flow version: 0.222.0

I couldn't figure out why [Flow is giving an error and inferring `number` here](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIACKRbAABRMcAgbCxAF4scAADpQLFY2isSjILHCEQzXi0pEAblptMx2Fx+KJplJJApWIAJAAlVhsADyUFwtAAgtQ6AAePENEUktgAPl5UH5ayxAGlsLQACprDUAait+optPpVqxCgaUDY4plcsVyrVNFoGsSyQNWIA-KzpiYscgXVi3R7BN6qVZ00jI1KLbQSBrHXGE9gRA9aEaTdiCZR7jbjParbwsXazSyc7XsPn9U7yQmk-JPanfex-ar1cH0j9KFiAGpOqPTwt0xPu-sp8XAdNWTNRq0AbTNAF1F-Ti6Xy35TW21gAmeuN5sARm75st7Y1VZrtob5qfhr5F+xK9jAAZjvJszQfe8zWvZ8gI7D9GHbW9vwgxtoK7c8BSxBCkLAx9W1fL99Sg68COtG98zQ39nSXekcNtei6xQp80JgzDTUY7BQIdKCHzIt9HRI-iKOY4jwOA4SQMon9WK7Gj6To6tEIYpTcOY2S0OAv9jS9OpcCoQUYAWZQSTpUFpIgySO0dfUAAoE3pEgICESgwGwFkGwcrE4UYPiZK8nYAHdp24GQWU4iyn1pABKFl8ggOA2CNDQlgMrEjMWR4zN6SKrM7VirOQqiu3s2isScly3I8zkyp8vzUK8nzSPNa8aoU1lsGC0L3Ow1SRKo2SYrihKktpFL9JYdLjKy8qcuYvLBJawrIrEs0JJfcipPUlqSq8irXJ6zzaqU+rIMapTmugtqFJ89a1uu+kgpC3Awt6z8toGlrNP1IasXixLz3GtLjixNgWW1QliTFc8AHoYfKoRGEYUgUixMIsRwd0AEchDgQpSj8NGICxAADNhdwABgPKxGSoCUHwATgADiZknaVBWy2EbCnGwAclpyhecbRmWeio0YhAfITBIUygnyCmrGvJWrApkAkSAA). (Sorry for the all the code; I tried to minimize it as much as I could. The intent of the `set` function is in the comment at the bottom: `supposed to be equivalent to d[0].year = 1988`).

At first I thought I made a typo somewhere, but after a couple hours playing with the code (:cry:), I found out [the error goes away if I inline some of the conditional types](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIACKRbAABRMcAgbCxAF4scAADpQLFY2isSjILHCEQzXi0pEAblptMx2Fx+KJplJJApWIAJAAlVhsADyUFwtAAgtQ6AAePENEUktgAPl5UH5ayxAGlsLQACprDUAait+optPpVqxCgaUDY4plcsVyrVNFoGsSyQNWIA-KzpiYscgXVi3R7BN6qVZ00jI1KLbQSBrHXGE9gRA9aEaTdiCZR7jbjParbwsXazSyc7XsPn9U7yQmk-JPanfex-ar1cH0j9KFiAGpOqPTwt0xPu-sp8XAdNWTNRq0AbTNAF1F-Ti6Xy35TW21gAmeuN5sARm75st7Y1VZrtob5qfhr5F+xK9jAAZjvJszQfe8zWvZ8gI7D9GHbW9vwgxtoK7c8BSxBCkLAx9W1fL99Sg68COtG98zQ39nSXekcNtei6xQp80JgzDTUY7BQIdKCHzIt9HRI-iKOY4jwOA4SQMon9WK7Gj6To6tEIYpTcOY2S0OAv9jS9OpcCoQUYAWZQSTpUFpIgySO0dfUAAoE3pEgICESgwGwFkGwcrE4UYPiZK8nYAHdp24GQWU4iyn1pABKFl8ggOA2CNDQlgMrEjMWR4zN6SKrM7VjwtUr8qKdZMvR9WVhyVUcgxDJIUjnaN2VjeMlwi0SVwHddN23bNLTzdqSqdVqTxLFo7K8pyXLcjzOVo7ylL81CvJ80jzWvOaFNZbBgtC9zsKK4xkKo2SYrihKktpFL9JYdLjKyrFzOYvLBPWwrPyYkrOrXKVKoVarA01UMGqzNkZmPA6Pusr6ytTDcMyzSUcwGw7oZ-OSRvdMbaE0qzQPU9au3s+aptc-bPPmnylsglalLW6DNoUnyJPNYDGfpIKQtwMLIeUqSCYZ1n9TOrF4sS89rrS44sTYFltUJYkxXPAB6ZXHqERhGFIFIsTCLEcHdABHIQ4EKUo-F1iAsQAAzYXcAAYDysRkqAlB8AE4AA5Pet2lQVsthG3txsAHIXcoEPGw973oqNGIQHyEwSFMoJ8ntqxr0zqx7ZAJEgA).

In case it's not clear, I only changed the following in the type parameters of the `set` function overloads:

```diff
-K2: KeyType2<T, K1>
+K2: PropType<T, K1> extends $ReadOnlyArray<mixed> ? number : PropType<T, K1> extends {...} ? $Keys<PropType<T, K1>
```
which essentially expands the `KeyType2` definition in-place.

I was hoping for a way to do all of this without overloads to begin with, but alas, [my best attempt did not work](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIACKRbAABRMcAgbCxAF4scAADpQLFY2isSjILHCEQzXi0pEAblptMx2Fx+KJplJJApWIAJAAlVhsADyUFwtAAgtQ6AAePENEUktgAPl5UH5ayxADkyg02ATKPcNQBqAAqvCx9oA0thaATIjkWTK5YrlWqaLQNfZTFAEFiAD6s6YmfX6iW0+ker0+rEKBpQNjigDa6R+lCxADE4ECJC6rNXCyYsbL7ABdFP0rEAfixAAoW63S+X7Jn5Nnc1K0yQNY79T3e+3zZaUja7Y682WK42XQ2JFO6TP6SzsCIHrRpwBKacsx1G2kaJZUQUwBbKEl00ETl1p70SX1S2XsQOq9VQ3DdIo1jNkZn1F0ADV9W7HcIDQAArC9OR3asrCoBASBZPN0I-H1oMHYdxQtewF1tRg3yxfCvyTDsoKxfdDxaZsoBPFl8ggOA2CvHM6lwO8sWOLE2BZbVCWJMVeIAemkrESCERhGFIFIsTCLEcEzABHIQ4EKUo-DUiAsQAAzYPMAAZGysRkqAlABGABOAAOZyTNpUFOzYF0LJdAByWzKD8l0nNck8jRiEB8hMEhnyCfILKsAAmFKrAskAkSAA).

**Comment by mwiencek** [comment]
I don't have to expand it within the `set` type parameters; it also works if expand it in the `KeyType2` definition:
```diff
-type KeyType2<+T, +K1> = KeyType<PropType<T, K1>>;
+type KeyType2<+T, +K1> = PropType<T, K1> extends $ReadOnlyArray<mixed> ? number : PropType<T, K1> extends {...} ? $Keys<PropType<T, K1>> : empty;
```

**Comment by SamChou19815** [comment]
The behavior seems expected to me. `number` is coming from `KeyType<DatePeriods>`. Conditional type is order sensitive. If you switch the order of two conditions in KeyType, it would work

**Comment by mwiencek** [comment]
@SamChou19815 Thanks for the pointer, but not sure I follow: in the expanded version the order of the conditions is the same, isn't it?

The error message suggests that `K2: KeyType2<T, K1>` should be `number`, but `K1` is `KeyType<DatePeriods>`, which is also `number`. Indeed this works fine:

```
('year': KeyType2<DatePeriods, KeyType<DatePeriods>>);
```

**Comment by mwiencek** [comment]
@SamChou19815 Thanks for the fix!
