### ISSUE TITLE
Object with null prototype does not extend interface {}

### ISSUE THREAD

**Issue by mwiencek** [facebook/flow#9108]
Flow version: 0.222.0

## Expected behavior

I very often use `null`-prototype objects in place of `Map`s because they're simpler, easier to serialize to JSON, and usually work with any utility that already accepts "plain" object types but not `Map`s.

Although Flow seems to handle `null`-prototype objects much better than TypeScript, there is one annoyance I have with them, which is that they don't extend `interface {}`.

So, I'd expect all of the code below to type-check.

```js
// @flow

type NullProto = {__proto__: null, a: string, b: string};

declare var x: NullProto;

// These all error.
(x: interface {});

new WeakSet<NullProto>();

type P = Pick<NullProto, 'a'>;
new WeakSet<P>();

type Cond<+O, +K> = O extends interface {} ? O[K] : empty;
('': Cond<NullProto, 'a'>);
```

## Actual behavior

Everything under "These all error" triggers an error.

I believe `{__proto__: null, ...}` should be a subtype of `interface {}`, but maybe you guys have a reason that shouldn't be the case?

While it would be possible to add `{__proto__: null, ...}` to the type definitions for `WeakSet`, `WeakRef`, `WeakMap`, `Pick`, etc., it's also annoying to have to handle it separately in every conditional type that deals with object types, or have to specify it separately for every type parameter bound that accepts object types.

* Link to Try-Flow or Github repo: https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCAHoMQACAACMCIAHcADpQUktYzYgBy2lwAAVKBAwtiALzY4D4fBwsKc5DYoa4XjYjB8+ymKAIIVoUVSdIIJEAblJpI0Syo2Gxx2x8j5NOGDKZECVZKgWOxABUcmUNdxcNiTIzKFZSQAKHXY9KArhgDXAJEASmNpJ2hOxAHVWF0AMq9AA8evpjLCAD4XYHlX41ti6azs3AwF147SDWEhQByDBl5PGkPhyMxiSxump9MmikagDC0DYsYA1AB5IW9gDSydz-ft8gaUDYJA9fhM3t9SOxAH5sf2ANrDgC62L52BED1oxpdZbLfK7M6L+qTEHLleTrZiIHyJhIcGgQXyAAYrAAmQCrB-EAkSAA

**Comment by SamChou19815** [comment]
Unfortunately, I don't think this is something we want to support. Some existing code might already rely on this behavior, which I think is legit: https://flow.org/try#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCGiWVGwAAJbPYcTBiMgcelAVwwLjgEiANwAHVgxCsYQAylJ0ggABQASnpUBiIHyJhIcGgQXyAAYrAAmWVWCUgJFAA

We generally don't support prototype stuff well, and would recommend against using prototype stuff.

**Comment by mwiencek** [comment]
OK, thanks for considering it, at least.
