### ISSUE TITLE
Missing documentation for "render-types"?

### ISSUE THREAD

**Issue by Haroenv** [facebook/flow#9114]
Hi, I don't use Flow myself, but just found out about the `render-types` feature through https://twitter.com/_gsathya/status/1745481549775053045/photo/1. I tried to find documentation about `renders` and `*renders` and I could only find the code implementation (`renders_kit` and associated files I think), nothing in the documentation site.

Seeing as this is an interesting distinction and feature between Flow and TypeScript, it could be interesting to put this somewhere on the website, or if it already exists, changing the content so one could find it by searching for `renders`, `render types` or `render-types` on the documentation.

Have a great day all!

**Comment by alexmckenley** [comment]
Hey @Haroenv thanks for opening the issue! We're in the process of polishing the docs for this feature and working on a more formal announcement for the blog in the next few weeks. I'll update this issue once its posted!

**Comment by SamChou19815** [comment]
Available now in https://flow.org/en/docs/react/render-types/
