### ISSUE TITLE
[homebrew] regression test failure with 0.226.0,0.227.0

### ISSUE THREAD

**Issue by chenrui333** [facebook/flow#9116]
relates to:
- https://github.com/Homebrew/homebrew-core/pull/159390
- https://github.com/Homebrew/homebrew-core/pull/160348

cc @alexmckenley

**Comment by SamChou19815** [comment]
The issue has been fixed in https://github.com/facebook/flow/commit/20515edff2822daf26cd32a0ddaa277af86d5ae9, which will be contained in a new release soon.

**Comment by chenrui333** [comment]
Thanks @SamChou19815! 

shipped in https://github.com/Homebrew/homebrew-core/pull/161598
