### ISSUE TITLE
The `experimental.ts_syntax` doesn’t seem to do anything

### ISSUE THREAD

**Issue by short-dsb** [facebook/flow#9122]
Flow version: 0.229.2

## Expected behavior

Per the [changelog for 0.229.0](https://github.com/facebook/flow/blob/main/Changelog.md#02290), enabling `experimental.ts_syntax=true` should allow some TypeScript syntax, e.g., `ReadOnly` versus `$ReadOnly`.

## Actual behavior

Using TypeScript syntax results in errors like this one:
> Cannot resolve name ReadOnly. [cannot-resolve-name]

I attempted to repro this via Try-Flow but the config option isn’t available there for 0.229.x (see link below). Additionally, it’s missing from the [documentation](https://flow.org/en/docs/config/options/).

* Link to Try-Flow or Github repo: [Try-Flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCMRA+RMJDg0CC+QADFYAEwkgCcpJASKAA)

**Comment by SamChou19815** [comment]
The name should be `Readonly`. Note that `o` is not capitalized.
