### ISSUE TITLE
Support rest parameters in interface files

### ISSUE THREAD

**Issue by philikon** [facebook/flow#913]
Consider the following interface file, `interface/foo.js`:

```javascript
declare module 'foo' {
  declare class Foo {
    bar(...args): Foo;
  }
}
```

Running flow 0.16.0 against this, I get:
```
.../interface/foo.js:3:16,16: Library parse error:
.../interface/foo.js:3:16,16: Unexpected token )
```

Am I doing it wrong, or is this just not supported yet?

**Comment by samwgoldman** [comment]
Rest parameters are supported, but Flow is complaining that you have not provided a type annotation to the rest argument (unexpected `)`, when it was expecting white space or a `:` to kick off the type annotation).

This does work:

```javascript
declare module 'foo' {
  declare class Foo {
    bar(...args: any[]): Foo;
  }
}
```

Note that the rest parameter has an array type.

**Comment by philikon** [comment]
Oh. Duh. Thanks!

**Comment by philikon** [comment]
Mayyyybe Flow's error message could be more helpful? Rather than suggesting that my syntax is broken, tell me that I'm missing a type annotation?
