### ISSUE TITLE
Top level exports

### ISSUE THREAD

**Issue by StefanoBalocco** [facebook/flow#9136]
I'm trying to convert some typescript code to flow but there is a part that seems invalid in flow:
```
class foo {
    bar() {

    }
}

if( typeof exports === 'object' ) {
    exports.foo = foo;
}
```

Flow version: 0.232

## Expected behavior
No error

## Actual behavior
Exports can only appear at the top level [invalid-export]

* Link to Try-Flow or Github repo:
https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCSww1wABDBiNjgAAdKDY0nYzCUAAUAEoCcTiWTsUjicyoMS4DBKdiWsYIDBsQpGBBKBISNiALyS7EAcggaAAVnUJNLsbSiSSyYLhaKrHiIBLccQANwsmIgfImEhwaBBfIABisACYAMzOqx2kBIoA

**Comment by SamChou19815** [comment]
TypeScript probably shouldn't accept this code, since it's too dynamic to analyze the signature of the module.
I think in this case, TS might think that the code is a script rather than a module, so it has more relaxed checks.
