### ISSUE TITLE
flow strict should allow unclear types for generics

### ISSUE THREAD

**Issue by ayroblu** [facebook/flow#9138]
## Proposal

With the removal of inexact types for generics matching exact types in the recent versions, we should have an easy way to specify Function, Object types in Generics while in `@flow strict`

```
type Gen<T: Object> = ...
```

## Use case

We use `@flow strict` to reduce the usages of any types. However, for generics, we want to say that something is struct `Object`. Before we would just use `{}` (or `{...}`) but that's now gone, we would like a way to say something is an Object without receiving the wrath of the checker that we're doing something wrong

**Comment by SamChou19815** [comment]
> Before we would just use {} (or {...}) but that's now gone

What do you mean by this? `{...}` is a good upper bound for all objects, if you want to include interfaces as well as objects, you can use `interface {}`

This page contains information you can find to specify the top types: https://flow.org/en/docs/lang/type-hierarchy/

**Comment by ayroblu** [comment]
[try flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIAIIAHgAKshcdQ6HjgFZKUiAHzUrEAXixwAAOlAseysRJiQTWUjWZjsFiAEKE4k40m0PGJZJsWkMpmsjmc7m8-lrLEAYVFJJokoA8mgAFZ1CRyxkstkcrlYnlQPl+dUAEW14t1eNOtDNCst7OttvtAqxAHV5fjXWTgBhifZTFAEDTqWrsQANeUi8OSyPRqTpeO0pOCgCa8q1GfJUaxMdzCYLWIAWvLnWWs5Wc3GEzEQPkTCQ4NAgvkAAxWABMAGYx1ZByAkUA)

**Comment by SamChou19815** [comment]
Arrays are invariantly typed, so you need to use `$ReadOnlyArray` instead

**Comment by ayroblu** [comment]
Invariants don't let you type function inputs though?

[try flow](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+IFkolXpUCWewUEAwhCQgRDH8wEH4hMnwROHlsNnw4KHwwSLAAC3wANyo4LFxscWQuHgMNZmwsiRSAWglaY1cq-hIAa2wJXNpG4Vxcdvdu3v7B0RxKUYMhKDBSqmbWwIq3eagoOrKSKgH0wtMMPznY7d2SfcoBiEZ-aG5G3Ix085AF-ZhsRoRehqUEiNMgSQHlSruBZxJrMcJwMhzAC+-EgGiCLWMAAIAEIQeQAHgA1AAVAB8WIAvFiSVSKfkIHA2AAdPxrLEAQQJJOQuPxBOAViFSLJFOpJNZmOwuO5vLxhMSyTYoqpNMl7IAwrK+YSAPJoABWdQkKvF6uxABFtfKCadaKa1VBzdKAOqqrk24AYXn2UxQBAisnOrEADVVOIJnu9WN96QDouDAE1VVqoz6pHHA8GAFqqq1pmMZ-1Zp1QGIgfImEhwaBBfIABisACYAMwtqz1kBIoA)

**Comment by SamChou19815** [comment]
For functions parameters, you will need contra-variance `-`.

**Comment by SamChou19815** [comment]
The `unclear-type` error is there because these types are just any, which is inherently unsafe. It's conceptually the same as [this lint rules](https://typescript-eslint.io/rules/no-explicit-any/), except that it's built in the checker itself. If you are unhappy with it, you can disable the lint
