### ISSUE TITLE
Flow hangs every now and then requires restarting

### ISSUE THREAD

**Issue by ayroblu** [facebook/flow#9142]
Flow version: 0.228.0

I noticed, and also from talking with my colleagues, that sometimes flow gets into a state where it no longer provides type hints in lsp and hangs when checking. flow stop and start fixes the issue, but it's a bit annoying. Occurs on the order of days / weeks. Have you had a similar issue at Meta?

**Comment by SamChou19815** [comment]
When it happens, it would be helpful to get the logs from flow. It will be available at /tmp/flow in mac and linux

**Comment by ayroblu** [comment]
macOS Sonoma. We don't configure a watcher. Will do

**Comment by ayroblu** [comment]
Closing for now as I don't have a repro will reopen if I catch it
