### ISSUE TITLE
Component syntax is not enabled

### ISSUE THREAD

**Issue by neutraali** [facebook/flow#9144]
Flow version: `0.235.1`

## Expected behavior

Using the [VSC extension](https://github.com/flow/flow-for-vscode), **React** [component syntax](https://flow.org/en/docs/react/component-syntax/) works out of the box.

## Actual behavior

![unsupported-syntax](https://github.com/facebook/flow/assets/16540190/5ff0da65-b6b6-42a9-8a4a-9acd139590e8)

## Further notes
I can't really say whether this is a bug with the extension or Flow itself. I've searched for the better part of the day and coudn't find any hints on how to resolve the issue. Has anyone else run into this problem? How does one "enable" the component syntax?

**Comment by SamChou19815** [comment]
We need to document it, but to enable, put the following in the flowconfig's `[options]`: `component_syntax=true`

**Comment by SamChou19815** [comment]
It's now documented https://flow.org/en/docs/react/component-syntax/#toc-enable-component-syntax

**Comment by neutraali** [comment]
Thanks for the quick reply @SamChou19815. I'll take this chance to ask another quick one: Is [prettier](https://flow.org/en/docs/tools/eslint/#toc-usage-with-prettier) supposed to work with component syntax?

![unexpected-identifier](https://github.com/facebook/flow/assets/16540190/04016ad2-b8db-4f75-8493-a55771c04a69)

**Comment by SamChou19815** [comment]
@neutraali The PR that adds support (https://github.com/prettier/prettier/pull/16191) is in the main branch of prettier, but they have not cut a release yet. To use it with prettier, you will need to use a prettier built from the main branch.

**Comment by neutraali** [comment]
Thanks again @SamChou19815 👍🏻
