### ISSUE TITLE
Alternative defaultProps not working with component syntax

### ISSUE THREAD

**Issue by neutraali** [facebook/flow#9147]
Flow version: `0.235.1`

## Expected behavior

`defaultProps` works when declaring it as:

``` 
type Props = {
    name: string
}
component Test(...props: Props) {
   return <h1>{`Hello ${props.name}!`}</h1>;
}
component.defaultProps = {
   name: 'World'
}
```

## Actual behavior

`Cannot assign object literal to "Test.defaultProps" because property `defaultProps` is missing in "React.AbstractComponentStatics"`

---

[Try-Flow Link](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0STMjAglAkAAIAFRcjAkLkAJVYyi5MEo6S5AHIosppQBuAA6UBVK2MXIACpLGIKALxc4AqrlcqDObDILn2UxQBC8Y38nGW4QiG4q+nK1WPdLsr4+LkAFXaEgAFFZw9TdZbtbCSABKQ0OkXRKyUgCiMExyhDIYTeoAfImoCaTbYSBA2lYiAgQ9KABJ4IhcgDqHNwbAAhNK456TfSeyqHSwJEJKMWADy1ACM+YAsrRTeaubTDZGSFYzeZ6fyoGwuQBJfkiVc69cYHHb2isfFcitsccAemn+fdg6gQfsVg0Wh0Md1XINI1i0XcxLWlD8JGld1PRVCCv1pRhcDoAA5JcDXA4NFTfBR2U5LlvxSHRA2DBVchABoTBIOBoCSBoAAYrAAJgAZgANisOiQHpIA)

At the end of the docs detaling [React class/function components](https://flow.org/en/docs/react/function-and-class-components/), there's an "alternative" way to declare `defaultProps` which we have been using so far. However, this doesn't quite seem to work with [component syntax](https://flow.org/en/docs/react/component-syntax/), which is kinda weird because one would assume that they largely follow the rules for functional components.

Is this intentional?

**Comment by SamChou19815** [comment]
This is intentional. Note that it will stop working for functions as well starting from React 19: https://react.dev/blog/2024/04/25/react-19-upgrade-guide#removed-proptypes-and-defaultprops
