### ISSUE TITLE
Custom module directory 

### ISSUE THREAD

**Issue by mikhail-riabokon** [facebook/flow#915]
I am using webpack for build project assets, and some time I need imort component to another which is deeply located. So to accomplish this, I write next:
```js
import MyCmp from '../.../../../../folder/components/MyCmp.jsx';
```

But with webpack I can resolve this long path if set module directories, by default it's node_modules.
```js
// webpack.config.js
...
resolve: {
  modulesDirectories: ['node_modules', 'folder'],
  extensions: ['', '.js', '.jsx']
}
...
```

So I can change this import statement to next variant:
```js
import MyCmp from 'components/MyCmp.jsx';
```

The questions is, how to set one more module directory to .flowconfig? Or is it possible. Thank you.

**Comment by jeffmo** [comment]
At the moment we only have a limited set of config options for module resolution unfortunately.

The most powerful one we have right now is [`module.name_mapper`](http://flowtype.org/docs/advanced-configuration.html#options) where you can specify a regexp search/replace that gets applied to module names before Flow tries to actually resolve the name.

I think having something like a `module.resolve_directories` config option similar to webpack's would make sense, though. I'll see if I can whip something together.

**Comment by mikhail-riabokon** [comment]
@jeffmo Thank you.

**Comment by josebalius** [comment]
This would be awesome indeed as I use webpack in the same way.

**Comment by josebalius** [comment]
@jeffmo also module.name_mapper solved this for me using an absolute path, which is an okay solution, but if we could get relative path in there then it would be perfect.

**Comment by jeffmo** [comment]
Just an update: https://github.com/facebook/flow/commit/dd1bac13de23766fae15b54de89f5b55e3b09bf9 landed which makes the `<PROJECT_ROOT>` token available in name_mapper templates (so you could do something like `module.name_mapper = '^\(.*\)$' -> '<PROJECT_ROOT>/folder/\1'` to address the OP request). This should be available in the next release (which should cut in the next week or 2)

**Comment by josebalius** [comment]
@jeffmo woohoo! Thank you

**Comment by mikhail-riabokon** [comment]
@jeffmo Thank you. It would be really helpful. Will you close this issue after release or we ca do it now?

**Comment by jeffmo** [comment]
Oh right, closing this out :)

**Comment by chiefGui** [comment]
Hey @jeffmo—I read your commit but so far I couldn't comprehend how does it work exactly. According to the tests, seems like it is resolving custom path names, but I am not that sure.

Do we have any docs for that? Am I right that it is adding this resolving capability to flow? 🤔

**Comment by superhawk610** [comment]
@chiefGui I'm over 2 years late so I doubt this will help you, but for anyone else who ends up here, to enable additional module directories in Flow, simply add this line to your `.flowconfig`:

```diff
[ignore]

[include]

[libs]

[lints]

[options]
+ module.name_mapper='^\(.*\)' -> '<PROJECT_ROOT>/src/\1'

[strict]
```

**Note:** this assumes you're using a Create React App-like project layout with all your `.js/.jsx` files in a `src` directory. If not, make sure to change the second path accordingly. If you had it all under `app/js`, you would use

```diff
- module.name_mapper='^\(.*\)' -> '<PROJECT_ROOT>/src/\1'
+ module.name_mapper='^\(.*\)' -> '<PROJECT_ROOT>/app/js/\1'
```
