### ISSUE TITLE
[Proposal] Mark state & prop arrays in components & hooks as readonly

### ISSUE THREAD

**Issue by Ayc0** [facebook/flow#9152]
## Proposal

When using the an object as a prop or as a state, Flow prevents you from mutating it directly (like `state.attr = value` or with `state[attr] = value`)
But when using arrays, you can still use `state.push()` or `state.sort()` and other mutating methods (but not `state[0] = value` as this is already covered by the other rule)

Proposal: automatically replace `Array` for `$ReadOnlyArray` for states & props

[REPL](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0STMjAglAkAAJgFzKQBlSwLLn0rkwSjpLkAciiyilXIAOlAlUrICJ2V8fFyAGLEAAUSq5XOpjAAgtQ6MgucIRDcANoAXV4huNEsYACVWGwAPJQQbmmi0K0AEk97F9-ottAAPDabgA+Z1QI0m71oABWcwkVt5TVwVrjJhFSoAlDyXamM1mrHmuQBeLkAFgATABuLkAeg7OqIAHcuSYJZQrdVPhBuSJUplsFyMK7YSrk-OzVG7QAGB31rnNzvd7V9gfUDkj4FQcdcydCmdzk0Vt0BuhWRj5Wp6gCMZa7XP5tQg2jYXISLUEr9oOx5ciQv7-lAgCYBBOU7Cjebp3rCD5DCQHISHqn7dj+f64ABQEgYeQ5WpB+FsLB8FXrOy6Limbphj6fq0GhT4vu+OE9hAoFHsOXJRGwAy0ChHpehGrFRlYGGcthu7cbxpECV6wn0Vytj2Fydr2NOvAQbsgrTpuDYCle0a5twBbXEW9LxnqwB5laa70iWrYujpCw1twW4tu2X77jxJHgaOZ7UdOykSEIlDJnmMhchAMBcr+EBbGpGncnagnCQAwn+PgmMZfJkIZCzRqG4ksWhsbWZQ8Z2Y6rkullLG5Q8eLsZBnHyQFingc1gxNSpLV5e1MlYVxPVBfx-UicqS7pVpkBtQVW6mdO1W2iYjr1Q6jXzSNW0blub7dQeYH8SF56XuFc4edgLpLfllAda+H7yXh-6AcBgXnWRUEEVRF4IdeEE0Xq6b5NyuBwDsYocvFVbKCQJYPQdz1jXJX4fQRX3Eb9EH-ZRcFAzRt1gxDmnQ7DMDwxAiMBCjc1GiwkXRVy0bxi6RpGtGTDAvGwCPXi9LRh2fNQJzS48x2kv0kquQgA0JgkHA0BJA0a5WM2ADMABsVhriA9JAA)

<img width="699" alt="image" src="https://github.com/facebook/flow/assets/22725671/f0b7a2ba-844d-4a88-addb-ea228645f508">

## Use case

Make sure that the rules of React are getting applied for even more edge cases: props & states should never be mutated manually (as it can break re-renders). Flow already does some internal computation to detect some mutation, but ReadOnlyArray already exists for this exact use-case for arrays

**Comment by SamChou19815** [comment]
This is an intentional choice. We have tried to automatically transform it into $ReadOnlyArray, but it's just too impractical to rollout on a large codebase.

**Comment by Ayc0** [comment]
What about with a settings under `[options]` in the `.flowconfig` file?

**Comment by SamChou19815** [comment]
That can be a good idea, but we do not have time to implement this now. We can accept contributions. Note that it will still not catch all problems, since we also completely give up on class methods, and assume whatever you call don't mutate things.

**Comment by Ayc0** [comment]
I thought more about this: there is the same issue for all objects passed in props, and also deep objects. So if there is an object with an array instead, both should be marked as readonly

**Comment by mvitousek** [comment]
In the next Flow release, Flow will now ban mutating methods from being called on Arrays, Sets, and Maps. We still don't treat them entirely as ReadOnlyArrays for the purposes of passing them to other functions, which may cause mutation, because the rollout would be impractical, but the example here will now error as expected.
