### ISSUE TITLE
Flow does not support " export * as module from './module' "

### ISSUE THREAD

**Issue by lapanoid** [facebook/flow#916]
I am getting 

```
export * as module from './module'
         ^^ Unexpected identifier
```

**Comment by jeffmo** [comment]
There is a [recent/pending proposal](https://github.com/leebyron/ecmascript-more-export-from) for `export * as` for some future ES.next (but note that this is not actually part of ES6).

This is on our todo list in any case.

**Comment by lapanoid** [comment]
@jeffmo could this be suppresed?

I tried this

```
/* $FlowIssue */
export * as api from './api'
```

```
[options]
suppress_comment=\\(.\\|\n\\)*\\$FlowIssue
```

But still have the same error.

**Comment by lapanoid** [comment]
This is basically the same and valid for flow 

```
import * as _api from './api'
export const api = _api;
```

**Comment by jeffmo** [comment]
> @jeffmo could this be suppresed?

Ah, yea that's actually a separate bug where parse errors aren't properly suppressed by suppression comments (cc @gabelevi )

**Comment by aintnorest** [comment]
@jeffmo is there another way to suppress errors?

**Comment by jeffmo** [comment]
We don't currently have a way to suppress parse errors. This syntax is still a stage1 proposal so it's very new. We do intend to support it, it's just not been implemented yet.

I'll try to hop on this over the holidays if I find myself with some downtime -- it shouldn't be too difficult to add.

**Comment by jeffmo** [comment]
FYI: `export * as ` went out in 0.21 behind the 'esproposal.export_star_as=enabled' .flowconfig option

https://github.com/facebook/flow/commit/57b41d09774dd658778349374fd16afd6f3a333f

**Comment by JCMais** [comment]
@jeffmo is the issue mentioned above 

> Ah, yea that's actually a separate bug where parse errors aren't properly suppressed by suppression comments 

fixed?

**Comment by nerdess** [comment]
sorry to step into this already closed issue!

i've got the flag

`esproposal.export_star_as=enable`

set in my .flowconfig 

but sth like

`export * as bla from 'blubb';`

gives me an "Syntax error: Unexpected token" (on the "as")...

btw: i am not familiar with flow, i am just trying to get my head around some code that was given to me.

**Comment by nerdess** [comment]
ok i fixed the code now by changing this

`
// @flow
export * as bla from 'blubb';
`

to this

`
// @flow
/* eslint-disable import/first */
import * as bla from 'blubb';
export {bla};
`

it works, but of course a working solution with keeping the export *-code would be much nicer :(
