### ISSUE TITLE
Would flow have "Community Declarations"? [Question]

### ISSUE THREAD

**Issue by umidbekkarimov** [facebook/flow#917]
Example for Typescript https://github.com/borisyankov/DefinitelyTyped

**Comment by jeffmo** [comment]
I think we were hoping not to have to fork DefinitelyTyped, but in practice the conversion between .d.ts files and flow lib defs has proven pretty difficult to automate.

I think @splodingsocks started building something like this for Flow, though: https://github.com/splodingsocks/FlowTyped

**Comment by umidbekkarimov** [comment]
Oh grate, couldn't find any repo like this, we should continue there.

(Anyway, I think it would be better to "flow" team own repo like this)

**Comment by samwgoldman** [comment]
I'm not sure there's anything else we can do to resolve this issue. Please contribute library definitions to the FlowTyped project.

**Comment by danvk** [comment]
@samwgoldman is that this? https://github.com/splodingsocks/FlowTyped

For the record, there are currently zero type definitions files there right now :)
