### ISSUE TITLE
React.ElementType not working for children

### ISSUE THREAD

**Issue by neutraali** [facebook/flow#9174]
( Sorry if the label was wrong! )

Using the following example code:

```js
type Props = {
    text: React.ElementType
};

component Component(props: Props) {
    return <span>{props.text}</span>;
}
```

[Try-Flow link](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SQAOj5VgACAAKlFhJE5AF5OcB2ZzxZyFvIJMhOQAlVjKKwAUTa3gkABVVuz6QBudnsyAiRjQCycgDC6RNXx8AApqYwSLLefyAJQisUSlgSISUKCcgA8TGBAD5gA6SP4FBJ6QGAPTBqAh-VQem5EANEwkODQJINAAMVgATABmAAcVhLIHpQA)

...I'm running into the following error:

```
Cannot create `span` element because in property `children`: [incompatible-type] Either AbstractComponent [1] is incompatible with `React.Element` [2]. Or AbstractComponent [1] is incompatible with `React.Portal` [3]. Or AbstractComponent [1] is incompatible with `$Iterable` [4]
```

Am I doing something wrong? I'm kind of having a hard time figuring it out by [the docs](https://flow.org/en/docs/react/types/) alone.

**Comment by gkz** [comment]
You want `React.Node` or `React.MixedElement`
