### ISSUE TITLE
Regression with incompatible-type detection

### ISSUE THREAD

**Issue by Robloche** [facebook/flow#9189]
Flow version: 0.239.1

## Expected behavior
Following code should be OK:
```js
const a: Array<number> = [1,2,3];

if (a.length > 0) {
  const b: number = a.pop();
}
```
Since `a` has at least one item and is declared as an array of `number`, the returned value of `a.pop()` is necessarily a `number`.

## Actual behavior
I get this error: 
```
4:   const b: number = a.pop();
                       ^ Cannot assign `a.pop()` to `b` because undefined [1] is incompatible with number [2]. [incompatible-type]
References:
[LIB] ..//try-flow-website-js@0.239.1/flowlib/core.js:1045:     pop(): T | void;
                                                                           ^ [1]
4:   const b: number = a.pop();
              ^ [2]
```

This code used to produce no error up to version [0.238.3](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SVs9gABBhkOyAILUOgAHmEIhuAD52QBedkAbQAjLwAEy8ADMAF0ANwAHSg2rgMHZAAoMFY2lAEBJauzxQAGACU7OA2vZ7LZEnZaG5wpuks5VkYsINtq1UHp2tyIAaJhIcGgSQa1qsCuVAA4rMqQPSgA).

But it started to give one from version [0.239.0](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SVs9gABBhkOyAILUOgAHmEIhuAD52QBedkAbQAjLwAEy8ADMAF0ANwAHSg2rgMHZAAoMFY2lAEBJauzxQAGACU7OA2vZ7LZEnZaG5wpuks5VkYsINtq1UHp2tyIAaJhIcGgSQa1qsCuVAE4rNaQPSgA).

`shift()` presents the same issue as well.

**Comment by SamChou19815** [comment]
This is intentional to make the typing more sound and align with TypeScript behavior

**Comment by Robloche** [comment]
What the point since it forces us to add useless tests, only to satisfy Flow?
I really don't get it.
