### ISSUE TITLE
tryflow is down

### ISSUE THREAD

**Issue by jaredly** [facebook/flow#920]
I believe it's managed by y'all?
I'm getting the heroku "this app is failing" message

**Comment by samwgoldman** [comment]
Quick Internet search reveals a repo by @ptmt — maybe he can help?

**Comment by samwgoldman** [comment]
(For what it's worth, http://tryflow.org/ is working for me.)

**Comment by ptmt** [comment]
Indeed, It's on Heroku's cheapest paid account, due to `flow` memory consumption may fail sometimes. If you had any suggestions please fill an issue here https://github.com/ptmt/tryflow/issues

**Comment by samwgoldman** [comment]
Thanks for following up Dmirty, and thank you very much for creating and providing tryflow for free!
