### ISSUE TITLE
Re-add documentation for %checks and mark as deprecated

### ISSUE THREAD

**Issue by Dagur** [facebook/flow#9226]
See https://github.com/facebook/flow/issues/9223#issuecomment-2477004892

**Comment by SamChou19815** [comment]
The documentation is already here: https://flow.org/en/docs/types/functions/#predicate-functions

**Comment by Dagur** [comment]
Apologies.  I couldn't find it and the search came up with nothing.

Þann fim., 14. nóv. 2024, 21:04 Sam Zhou skrifaði ***@***.***
