### ISSUE TITLE
null check ignored after second line of conditional block

### ISSUE THREAD

**Issue by trusktr** [facebook/flow#9241]
Flow version: **0.255**

type narrowing from a conditional check is ignored after the second statement of a conditional block

## Expected behavior

Type narrowing should not be lost.

## Actual behavior

Type narrowing is lost and the property becomes nullable again.

## Reproduction

```js
class A {
    foo: {foo: string} | null = {foo: 'adsf'}

    aMethod(): void {
        if (this.foo) {
            console.log('foo') // comment this out, error goes away
            this.foo.foo // <---- error
        }
    }
}
```

```js
class A {
    foo: {foo: string} | null = {foo: 'adsf'}

    aMethod(): void {
        if (this.foo) {
            // console.log('foo') // comment this out, error goes away
            this.foo.foo // <---- no error
        }
    }
}
```

[Flow Try](https://flow.org/try/#1N4Igxg9gdgZglgcxALlAIwIZoKYBsD6uEEAztvhgE6UYCe+JADpdhgCYowa5kA0I2KAFcAtiRQAXSkOz9sADwxgJ+NPTbYuQ3BMnTZA+Y2yU4IwRO4A6SFBIrGVDGM7c+h46fNRLuKxJIGWh8MeT0ZfhYlCStpHzNsFBAMIQkIEQwJODAQfiEyfBE4eWw2fDgofDBMsAALfAA3KjgsXGxxZC4eAw0G-GhcWn9aY3wWZldu-g1mbGqJUoBaCRHEzrcDEgBrbAk62kXhXFxJ923d-cPRHEpTgyEoMDaqZdW7vKgoOfaSKgOKpqmDA+d4gB5fMA-P6LCCMLLQbiLOoYCqgh6-GDYRYIXYLSgkRZkCR4jpddwPfJLZjpOBkO4AX34kA0SSeGBIJAABABBTnAAA6UE5ws5MGIyD5YogEvspigCHpnIAPpyjrhOQBeSXizkAcnYJBguvpgsFIs5GAAsrtahA2AAKACUEoaEDgbD5ZvNIrgME59oktVpViljs9Qu9kdsJAgbSsRAQ9t1Ut1YYA9GnOZARN4JJzA7TORBUrxOSZKBBKJyEBB2haAO50L2R80Fkgh4gdiDN70miPCvv03IgBomEhwaBJBoABisACYAKwLqzTkD0oA)

**Comment by gkz** [comment]
https://flow.org/en/docs/faq/

**Comment by trusktr** [comment]
Hmm, interesting. After years of TypeScript usage, I've haven't had a problem with it.

Here's TypeScript's version:

[TypeScript example 1](https://www.typescriptlang.org/play/?#code/MYGwhgzhAECC0G8BQ1XQGYHtMC5Fd2ggBcAnASwDsBzAX2gB9pKBXEEaAXn2zwHIwAEwjo+tJCjRgAsgFNiAC0yCAFAEo8AN0zlBiSWjTl00FYvIQAdATX7D9tMEyUImELMshM1FXwJ81Awc0cysCa2xoAHoo6AAeAFokhOZMaFlSUkxSIMNxPKRaIA)

Here's an example where I've purposefully tricked TypeScript's type refinement and to make it have a runtime error:

[TypeScript tricked](https://www.typescriptlang.org/play/?#code/MYGwhgzhAECC0G8BQ1XQGYHtMC5Fd2ggBcAnASwDsBzAX2gB9pKBXEEaAXn2zwHIwAEwjo+tJCjQAjPACEJaaMEyUSpFsGKZSACgCUiSYtTEAFuQgA6KV2YBTAO7RZ+o8bMXrlzFIBWtjwg3cTcwAFk7M0xBfTwAN0xyQUNjNHJ0aB1AywIDZFTU5VVMEDtLEExqHT4CPj03AuhsqUsAW2jXRsUiiBKyiqq+bIIiFgAHMcwIO0EQAE9oOwAPC2IIAH46hoLh7BzsaAB6Q+gAHgBaS-PodUpicla7RdJSbQBCbdRxRXEQ0EgYLIUmgfL48PAmKx2LYoSAFGh2jE8p8muYrKDoAAyTGZbKg-aYGFsED1H5IP4qEjQMAwxxwaASMCWcKRUwdPRAA)

Maybe for full type safety, if the type of the thing used before the refined type (f.e. `console`) does not contain a property that is of the type that contains the refined property, and also does not have any methods that accept the type of the object containing the refined property, then it can avoid canceling the refinement. It would have to also not have any `any` or similar properties that would prevent the refinement from carrying on, and any methods that accept `any` or more generic types than the passed in args would need to be checked based on call-site types. But that seems like a lot of work!
