### ISSUE TITLE
Values used as types should always result in an error

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#927]
``` us
function f<T>(x: T): T { return x }
var a: f<number> = f; // no error, but should
```

For more context on this see (#923)

**Comment by samwgoldman** [comment]
This has nothing to do with generics/parameterization, but is a bug. More cases:

```javascript
/* @flow */
function f() { }
var a: f; // no error
```

```javascript
/* @flow */
var f;
var a: f; // no error
```

**Comment by TrySound** [comment]
Fixed
https://flow.org/try/#0GYVwdgxgLglg9mABMAPAFQHwAoAeAuRNASgLUQG9EAnAUyhCqR0QF8AoANwEMrEuDUYEAFsARjSoZEAXmQBuRAHpFiMHEQSqcKgBpEokFEQBnABZwQAGwAmQA
