### ISSUE TITLE
module boilerplate wrapper confuses flow

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#931]
If you use babel to compile flow written library with `flow-comments` plugin to preserve types as comments and with `--module` flag to generate module boilerplate generated code is no longer type checks with flow. Here is an example:

## `./src/code.js`
```js
/* @flow */

export type Dictionary <value> = {[key:string]: value}
```

## `./dist/code.js`
```js
(function (global, factory) {
  if (typeof define === "function" && define.amd) {
    define(["exports"], factory);
  } else if (typeof exports !== "undefined") {
    factory(exports);
  } else {
    var mod = {
      exports: {}
    };
    factory(mod.exports);
    global.index = mod.exports;
  }
})(this, function (exports) {
  /* @flow */

  "use strict";

  /*:: export type Dictionary <value> = {[key:string]: value}
  */
});
```

Flow does not expect `export` operators to a the top level:

```sh
flow check

dist/code.js:18
 18:   /*:: export type Dictionary <value> = {[key:string]: value}
            ^^^^^^ Unexpected token export


Found 1 error
```

Which does make sense on one hand but on the other hand makes it impossible to depend on compiled libraries (see #910 for more details)

**Comment by samwgoldman** [comment]
This is a bug in that plugin. I see you already have opened an issue there. Opening more issues isn't going to help get this fixed faster.

**Comment by Gozala** [comment]
@samwgoldman I'm not trying to speed up by creating more issues, as I pointed out in the issue on the plugin side I do think this will require collaboration on both sides as I don't think there is a clear path for resolving this on the plugin side, I may be wrong but hoisting all the exports may not work as some of the definitions will be inside the wrapper function.
