### ISSUE TITLE
Support flow.base property for overriding root of the package from flow perspective

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#932]
This first has being brought up in #910 as I was trying to use flow written libs as my dependencies & run into #931 as transpiled flow code is no longer a valid flow code which at the moment means that if library A depends on library B it needs to do this thing in the `.flowconfig`

```ini
module.name_mapper='A' -> 'A/src/index'
module.name_mapper='A/other' -> 'A/src/other'
...
```

That is painful but bearable if your dependency graph is very shallow but as it grows it becomes more & more painful specially because flow does not really care about nested `.flowconfig` files (see #238) which means at every level you need to also copy mappers for your children.

On the other hand though the only reason issue is present is because flow follows node's module resolution logic during imports and there for end up analyzing transpiled files instead of the original source. Now if flow introduced `flow.base` property in the package.json & then used that field to resolve module path against that would resolve all of the issues. I think adding `flow.main` along would also be helpful for single file packages where diff file instead of directory is more desired.

**Comment by Gozala** [comment]
Also note that since flow already looks at `package.json`  to find a `main` module  and that is also recursive that would mean library users that library author will have to provide a path while library user will have to do nothing differently.

**Comment by samwgoldman** [comment]
We've had this [since 0.18.1](https://github.com/facebook/flow/blob/master/Changelog.md#v0181) via `PROJECT_ROOT`. Although I think you'd be better served by `.js.flow` files based on the content of this issue.
