### ISSUE TITLE
Type of object value not inferred correctly in for-in loop

### ISSUE THREAD

**Issue by chenglou** [facebook/flow#935]
``` js
type A = {
  a: string,
  b: string,
}

const obj: A = {
  a: 'aaa',
  b: 'bbb',
};

for (let key in obj) {
  if (!obj.hasOwnProperty(key)) {
    continue;
  }
  const a: number = add(obj[key], 2);
}
```

Where `add` is `(number, number) => number` (just to highlight the point that it's not `+` operator's fault).

I guess this is tricky? Because if you define the type of `A.a` as a number then the user probably need to do some complex case matching in the loop to signal what type `obj[key]` is.

**Comment by samwgoldman** [comment]
This is interesting, and I wonder if it's related to #890 (which isn't actually specific to unions).

I haven't looked into it, but maybe I can help you with a workaround? The following does raise the expected type error:

```
for (let key of Object.keys(obj)) {
  const a: number = add(obj[key], 2);
}
```

**Comment by chenglou** [comment]
My question is, how can I correctly avoid the type error in this situation?
```js
type A = {
  a: string,
  b: number,
}

const obj: A = {
  a: 'aaa',
  b: 1,
};

for (let key of Object.keys(obj)) {
  if (key === 'b') {
    const a: number = add(obj[key], 2);
  }
}
```
The above still throws even though I made sure the key is `b`:
```
 28:     const a: number = add(obj[key], 2);
                               ^^^^^^^^ string. This type is incompatible with
 12: function add(a: number, b: number): number {
                     ^^^^^^ number
```
Which is what I meant by this might be tricky with an object containing heterogenous types of values.

**Comment by samwgoldman** [comment]
Hrm, well, we could make Flow clever enough to know that `key` is the string literal type `'b'` within that branch. In this case, you could also replace `obj[key]` with `obj['b']`, which has no error.

**Comment by appsforartists** [comment]
Not sure if this belongs here, in #890, or in its own bug, but Flow is mad about this code:

```javascript

type Point2DT = {
  x?:number,
  y?:number
};

function getCSSPair(planProperty, value:number|Point2DT) {
  let cssKey, cssValue;

  switch (planProperty) {
    case TweenProperty.TRANSLATION:
      cssKey = 'transform';

      if (value.hasOwnProperty('x') && value.hasOwnProperty('y')) {
        cssValue = `translate(${ value.x }px, ${ value.y }px,)`;

      } else if (value.hasOwnProperty('x')) {
        cssValue = `translateX(${ value.x }px`;

      } else if (value.hasOwnProperty('y')) {
        cssValue = `translateY(${ value.y }px,)`;
      }
      break;
```

even though I check for `x` and `y` before I access them.

Is there a way to tell Flow that if `planProperty` is `translation`, `value` can only be a `Point2DT`?

**Comment by torarnek** [comment]
Any progress on this? Using For ... in is quite common in javascript.

**Comment by SamChou19815** [comment]
This kind of dynamic pattern won't be supported
