### ISSUE TITLE
Fatal error: exception End_of_file

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#937]
```sh
flow server
[2015-10-12 12:06:04] Initializing Server (This might take some time)
[2015-10-12 12:06:04] executable=/usr/local/lib/node_modules/flow-bin/vendor/flow
[2015-10-12 12:06:04] version=0.17.0
Worker interrupted with signal: sigsegv
Fatal error: exception End_of_file
```

Can't really tell what exactly is going on here, trying to reduce the scope to find what exactly causes this issue.

**Comment by Gozala** [comment]
Ok it looks like content of this file is causing the error:

```js
/* @flow */

import {Dictionary} from "dictionary"
import {Address} from "reflex/src/signal"

// hooks

export type Hook <target> = {
  hook: (node:target, name:string, previous:any) => void,
  unhook: (node:target, name:string, next:any) => void
}


export type nameOverrides = Dictionary<string>
export type supportedAttributes = Dictionary<string>

// hooks/event-handler

export type EventConfig = {type:string, capture:boolean}
export type supportedEvents = Dictionary<EventConfig>

export type EventPhaseName
  = 'capture'
  | 'bubble'

export type EventListener = EventListener
export type DOMEventTarget = EventTarget
export type EventTarget
  = DOMEventTarget
  & {[key:string]: EventListener}

export type DOMEvent = Event
export type Event
  = DOMEvent
  & {currentTarget: EventTarget}

export type handleEvent = (phase:EventPhaseName) =>
  (event:Event) => void

export type ReflexAddress = Address
export type Address
  = ReflexAddress
  & {reflexEventListener: ?EventHandler}


export type eventHandler = (address:Address) =>
  Hook<EventTarget>
```

**Comment by Gozala** [comment]
Ok looks like this line is enough to cause this:

```js
export type EventListener = EventListener
```

**Comment by Gozala** [comment]
P.S.: I am not saying that like makes sense but it's still bad the flow crashes instead or reporting an error.

**Comment by Gozala** [comment]
I tried following to fix crash:

```js
type DOMEventListener = EventListener
export type EventListener = DOMEventListener
```

But it still seem to ended up being the same, presumably because flow tries to recursively resolve `EventListener`. Which makes me wonder if there is a way to define extensions to flow built-in types like this:

```js
export type DOMEvent = Event
export type Event
  = DOMEvent
  & {currentTarget: EventTarget}
```

**Comment by Gozala** [comment]
There is a following option to achieve what I wanted in my last comment on could create separate file to namespace flow provided globals:

## `./dom.js`
```js
/* @flow */

export {EventListener, EventHandler, Event, EventTarget}
```

and then import it from file that wishes to overload those names:

## `./index.js`

```js
import * as DOM from "./dom"

export type EventTarget
  = DOM.EventTarget
  & {[key:string]: DOM.EventListener}

export type Event
  = DOM.Event
  & {currentTarget: DOM.EventTarget}
```

**Comment by samwgoldman** [comment]
Yeah, you're right that this should never ever crash Flow. Smallest repro I can find is `type T = T`, so the export isn't related.

You probably didn't intend to create a bottom type, but that's what this kind of type is. I suppose it could be useful to define such a type, so perhaps the fix is to allow this pattern.

Note that it *is* possible to define a recursive type, and mutually recursive types.

**Comment by gabelevi** [comment]
Oh geez. We definitely shouldn't be sigsev'ing. @samwgoldman have you started looking into this? If not, I'll get a fix in.

**Comment by samwgoldman** [comment]
@gabelevi Nope, I haven't investigated this.
