### ISSUE TITLE
Allow importing types from flow's `lib` into a namespace

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#938]
Currently flow exposes all the type definitions from https://github.com/facebook/flow/tree/master/lib globally and overloading some of require extra file boilerplate (see https://github.com/facebook/flow/issues/937#issuecomment-147498365) it would be nice if individual typedefs could be imported same as from other modules. I would suggest exposing them from `flow/*` namespace so one could do:

```js
import * as DOM from "flow/dom";
```

**Comment by samwgoldman** [comment]
The purpose of the dom type defs is to help flow understand code that is designed to run in a browser environment, where classes like `HTMLElement` are available in the global namespace.

How would this help people write code that runs in a browser? Say the above import line did what you expected, and I wrote code like this:

```javascript
import * as DOM from "flow/dom";

function eventHandler(e: DOM.Event): void {
  if (e.target instanceof DOM.HTMLElement) {
    e.target.innerHTML = "Hello, World!";
  }
}
```

Perhaps we could understand the type annotation of the `e` parameter within Flow, and the type annotation would be erased before running in a browser, but the `instanceof` check would remain, and the browser runtime has no idea what `DOM.HTMLElement` is.

Can you provide complete semantics on this feature? Until you can make that more clear, I am :-1: on this proposal.

**Comment by Gozala** [comment]
> Can you provide complete semantics on this feature? Until you can make that more clear, I am :-1: on this proposal.

@samwgoldman As I mentioned in the description the reason I want this feature is so one could override currently taken global name with a type extension to it. As also pointed out there is an a specific example in #937 

For clarification I'm going to paste an example here:

```js
import * as DOM from "flow/dom"

export type EventTarget
  = DOM.EventTarget
  & {myLibMaintainedExtension: MyLibMaintainedExtension}

export type Event
  = DOM.Event
  & {currentTarget: EventTarget}
```

Also note that I don't expect code above to override global `EventTarget` or `Target` it's just it is impossible to use those names locally either if you intend to extend same named types without workarounds like illustrated in https://github.com/facebook/flow/issues/937#issuecomment-147498365

**Comment by Gozala** [comment]
Also note that flow won't type check if code attempts to do `event.currentTarget.myLibMaintainedExtension = myThing` when `event` is flow's predefined `EventTarget`.

Argument can be made well that one could just use a non-conflicting name, although I think it would be unfortunate to take up so many type names and forcing users to rename or hack around like displayed in https://github.com/facebook/flow/issues/937#issuecomment-147498365

**Comment by samwgoldman** [comment]
Flow isn't "taking up" names like `EventTarget`—DOM is.

**Comment by samwgoldman** [comment]
Extending the globally declared DOM types seems like a misfeature to me, regardless. There are definitely cases where Flow's type declarations are incomplete, and people have rightfully complained that it's difficult to work around that, but what you're trying to do here doesn't seem like a good idea. Are you also modifying the global EventTarget at runtime?

**Comment by Gozala** [comment]
> Extending the globally declared DOM types seems like a misfeature to me, regardless. 

That is not about that though it's about using globally declared type names for different purposes locally. 

> There are definitely cases where Flow's type declarations are incomplete, and people have rightfully complained that it's difficult to work around that, but what you're trying to do here doesn't seem like a good idea. Are you also modifying the global EventTarget at runtime?

While I agree that in genera mutating DOM constructs is a bad idea there are still a cases where that is necessary & in fact with addition of Symbol types in JS it's also less error prone.

I can live without this specially since there is still a way to bind global names from other module to then rebind them but it just seems really odd to require such workaround.

> Are you also modifying the global EventTarget at runtime

That is exactly a reason I'm want to define `EventTarget` extension locally.

**Comment by samwgoldman** [comment]
> Also note that flow won't type check if code attempts to do event.currentTarget.myLibMaintainedExtension = myThing when event is flow's predefined EventTarget.

Are you saying here that you want to enable this pattern?

What about the code snippet from my first response to this issue? I feel like I brought up a legitimate issue with this proposal, but you haven't addressed that.

**Comment by Gozala** [comment]
> Are you saying here that you want to enable this pattern?

All I want is to allow library flow to type check libraries that sometimes need to do things that may not be considered best practices. That being said I don't suggest to make `Event` or `EventTarget` extendable as `window` instead I think library author should be allowed to override globally available type like `Event` or `EventTarget` by their extensions like illustrated in this example https://github.com/facebook/flow/issues/938#issuecomment-147565267 without going through extra hoops like illustrated in the other example https://github.com/facebook/flow/issues/937#issuecomment-147498365

> What about the code snippet from my first response to this issue? I feel like I brought up a legitimate issue with this proposal, but you haven't addressed that.

I am sorry I just don't understand how that example is relevant here ? Same runtime error can be made with any type alias defined or exported from any other file:

```js
import * as MyLib from "mylib";

function eventHandler(e: MyLib.Event): void {
  if (e.target instanceof MyLib.HTMLElement) {
    e.target.innerHTML = "Hello, World!";
  }
}
```

Also I would assume that flow could catch such errors at compile time.

**Comment by samwgoldman** [comment]
> All I want is to allow library flow to type check libraries that sometimes need to do things that may not be considered best practices.

Is that a "yes" or a "no"?

> I am sorry I just don't understand how that example is relevant here?

It's relevant because `e.target instanceof MyLib.HTMLElement` would fail at runtime, because `MyLib.HTMLElement` would not be bound at runtime.

You haven't yet shared a single example of runtime code (you've only shown type definitions). Take the time to write a complete example, and explain how the code would be type-stripped for execution in a browser. Until you can provide such an example, I don't have anything to add to this discussion.

**Comment by Gozala** [comment]
> > All I want is to allow library flow to type check libraries that sometimes need to do things that may not be considered best practices.
> Is that a "yes" or a "no"?

It depends on how such pattern is going to be enabled. As I said I don't want to just make Event or EventTarget open ended, but I do want to allow `type Event = DOMEvent & { myLibMaintainedExtension: string }` without additional boilerplate. I am not sure if that is Yes or a No in regards to your question.




> It's relevant because e.target instanceof MyLib.HTMLElement would fail at runtime, because MyLib.HTMLElement would not be bound at runtime.

I think you are misunderstanding me, but believe me I'm trying my best to make it clear. I'll try to give a more specific example of what I meant here:

## `mylib.js`
```js
export type Foo = {$$typeof: "Foo", ... }
export type Bar = {$$typeof: "Bar", foo: Foo}
....
```

## `impl.js`

```js
import * as MyLib from "./mylib"

function receive(message): void {
  if (message instanceof MyLib.Bar) {
    updateState(...)
  }
}
```

This code above has same problem as you've pointed out, that is why I do not understand how it was relevant to this specific issue.



> You haven't yet shared a single example of runtime code (you've only shown type definitions). Take the time to write a complete example, and explain how the code would be type-stripped for execution in a browser. Until you can provide such an example, I don't have anything to add to this discussion.

I'm more than happy to share an actual real life code snippets, the only I was not doing so is because I got an impression that shortest possible code snippets were more welcome.

My very specific example is related to implementation of [hooks in virtual-dom](https://github.com/Matt-Esch/virtual-dom/blob/master/docs/hooks.md) library. To save you from reading linked documentation, I'll give a little overview here. virtual-dom library provides similar DOM abstraction as React with slight differences in API performance and focus. At the end of the day though you create virtual DOM nodes like `node("div", { id: "foo" }, [node("span", null, "hello world")])`. But not all of the DOM APIs can be expressed with attributes and properties (.focus() for example or addEventListener) for such things virtual-dom library provides hooks abstraction that has following type signature:

```js
type Hook = {
  hook: (node:HTMLElement, propertyName:string, previousValue:?Hook) => void
  unhook: (node:HTMLElement, propertyName:string, nextValue:?Hook) => void
}
```

Hooks can be used to box property values in order to deal with those special DOM APIs, basically they serve same purpose as react's `componentDidMount` and `componentWillUnmount` lifecycle methods, just at the different level:

```js
node("div", {id: "foo, focus: Focus()})
```

You can find implementation of Focus & other hooks here: https://github.com/Matt-Esch/virtual-dom/blob/master/virtual-hyperscript/hooks/focus-hook.js

Now presumably we want to implement hook for event handling which looks something like this:

```js
/* @flow */

type Hook = {
  hook: (node:EventTarget, key:string, previous:?Hook) => void,
  unhook: (node:EventTarget, key:string, next:?Hook) => void
}

const hookProperty = 'Symbol.for(mylib.eventHandler.hook)'
const eventStore = 'Symbol.for(mylib.event.store)'

export const eventHandler = (handler:EventListener):Hook => {
  // Canche hook per event handler to avoid creating one
  // on each render.
  if (handler[hookProperty] == null) {
    handler[hookProperty] = new EventHandlerHook(handler)
  }

  return handler[hookProperty]
}

const toEventType = key =>
  key.replace('on', '')
     .replace('Capture', '')

const isCapturing = key =>
  key.endsWith('Capture')

const handleEvent = (event:Event):void => {
  const {target, type} = event
  if (target[eventStore] != null) {
    const handler = target[eventStore][type]
    if (handler != null) {
      handler(event)
    }
  }
}

export class EventHandlerHook {
  handler: EventListener;
  constructor(handler:EventListener) {
    this.handler = handler
  }
  hook(node:EventTarget, key:string, previous:?Hook) {
    const type = toEventType(key)
    if (previous == null) {
      node.addEventListener(type, handleEvent, isCapturing(key))
    }

    if (node[eventStore] != null) {
      node[eventStore] = {}
    }
    node[eventStore][type] = this.handler
  }
  unhook(node:EventTarget, key:string, next:?Hook) {
    if (next == null) {
      node.removeEventListener(toEventType(key), handleEvent, isCapturing(key))
    }
  }
}
```

This code does not type check and produces following errors:

```sh
src/event-handler-hook.js:14
 14:   if (handler[hookProperty] == null) {
                   ^^^^^^^^^^^^ property `Symbol.for(mylib.eventHandler.hook)`. Property not found in
 14:   if (handler[hookProperty] == null) {
           ^^^^^^^ object type

src/event-handler-hook.js:15
 15:     handler[hookProperty] = new EventHandlerHook(handler)
                 ^^^^^^^^^^^^ property `Symbol.for(mylib.eventHandler.hook)`. Property not found in
 15:     handler[hookProperty] = new EventHandlerHook(handler)
         ^^^^^^^ object type

src/event-handler-hook.js:18
 18:   return handler[hookProperty]
                      ^^^^^^^^^^^^ property `Symbol.for(mylib.eventHandler.hook)`. Property not found in
 18:   return handler[hookProperty]
              ^^^^^^^ object type

src/event-handler-hook.js:30
 30:   if (target[eventStore] != null) {
           ^^^^^^^^^^^^^^^^^^ access of computed property/element. Indexable signature not found in
 30:   if (target[eventStore] != null) {
           ^^^^^^ EventTarget

src/event-handler-hook.js:49
 49:     if (node[eventStore] != null) {
             ^^^^^^^^^^^^^^^^ access of computed property/element. Indexable signature not found in
 49:     if (node[eventStore] != null) {
             ^^^^ EventTarget

src/event-handler-hook.js:50
 50:       node[eventStore] = {}
           ^^^^^^^^^^^^^^^^ assignment of computed property/element. Indexable signature not found in
 50:       node[eventStore] = {}
           ^^^^ EventTarget

src/event-handler-hook.js:52
 52:     node[eventStore][type] = this.handler
         ^^^^^^^^^^^^^^^^ access of computed property/element. Indexable signature not found in
 52:     node[eventStore][type] = this.handler
         ^^^^ EventTarget


Found 7 errors
```

All those errors make sense because in this case we use our special non-standard fields to cache hook instances & to store event listeners. In my opinion the most reasonable solution in this case is to change that code to extend base DOM types with extensions that implementation is going to rely on:

```js
/* @flow */

import * as DOM from "flow/dom"

type Hook <target> = {
  hook: (node:target, name:string, previous:any) => void,
  unhook: (node:target, name:string, next:any) => void
}


const hookProperty = 'Symbol.for(mylib.eventHandler.hook)'
const eventStore = 'Symbol.for(mylib.event.store)'

type EventStore = {[key:string]: EventListener}

type EventListener
  = DOM.EventListener
  & {'Symbol.for(mylib.eventHandler.hook)': ?Hook<EventTarget>}

type EventTarget
  = DOM.EventTarget
  & {'Symbol.for(mylib.event.store)': ?EventStore}

type Event
  = DOM.Event
  & {target: EventTarget}


export const eventHandler = (handler:EventListener):Hook<EventTarget> => {
  // Canche hook per event handler to avoid creating one
  // on each render.
  if (handler[hookProperty] == null) {
    const hook = new EventHandlerHook(handler)
    handler[hookProperty] = hook
    return hook
  } else {
    return handler[hookProperty]
  }
}

const toEventType = key =>
  key.replace('on', '')
     .replace('Capture', '')

const isCapturing = key =>
  key.endsWith('Capture')

const handleEvent = (event:Event):void => {
  const {target, type} = event
  if (target[eventStore] != null) {
    const handler = target[eventStore][type]
    if (handler != null) {
      if (handler.handleEvent != null) {
        handler.handleEvent(event)
      } else if (typeof(handler) == "function"){
        handler(event)
      }
    }
  }
}

export class EventHandlerHook {
  handler: EventListener;
  constructor(handler:EventListener) {
    this.handler = handler
  }
  hook(node:EventTarget, key:string, previous:?Hook) {
    const type = toEventType(key)
    if (previous == null) {
      node.addEventListener(type, handleEvent, isCapturing(key))
    }

    if (node[eventStore] == null) {
      const store = {}
      store[type] = this.handler
      node[eventStore] = store
    } else {
      node[eventStore][type] = this.handler
    }
  }
  unhook(node:EventTarget, key:string, next:?Hook) {
    if (next == null) {
      node.removeEventListener(toEventType(key), handleEvent, isCapturing(key))
    }
  }
}
```

The only issue here is that `import * as DOM from "flow/dom"` won't work unless hack described earlier is employed in our case it is enabled with:

```sh
mkdir node_modules & mkdir node_modules/flow
echo "/* @flow */\nexport {EventListener, Event, EventTarget}" > node_modules/flow/dom.js
```

Also note that I don't necessarily want to use import, it's just aliasing and then reusing name causes #937 and there is also no other way to refer to global type defs as far as I can tell. That being said I would like if any global type could also be imported that is because or other types installed through libs or local are usually be imported.

Hope this clarifies it.

**Comment by samwgoldman** [comment]
OK, so you're absolutely correct that minimal reproductions are preferred, but let me make it clear what I mean by that. A minimal reproduction is a complete program that exhibits some unexpected behavior. An issue report would include the reproduction, the actual output, and the expected output.

"Small code snippets" are not a minimal reproduction because they don't give a complete picture. I recognize that creating minimal reproductions is work—often the program you are working on is larger and complex. The helpful thing to do is *not* to take a couple lines from that program and post an issue, but rather to write a *smaller* program that exhibits the same issue.

For example, here is a minimal reproduction of this issue, as I understand it.

Here is what you would like to express:

```javascript
/* @flow */

export function a(e: HTMLElement): void {
  e.foo = true;
}

export function b(e: HTMLElement): bool {
  return e.foo == true;
}
```

This module does a simple thing. It returns `true` from `b` when it's argument has previously been passed to `a`, and `false` otherwise. You might invoke it like so:

```javascript
/* @flow */

import { a, b } from "./ab"

declare var x: HTMLElement;
declare var y: HTMLElement;

a(x);
b(x); // true
b(y); // false
```

However, you can't write such a file, because `foo` is not a property of `HTMLElement`. You can, however, write this:

```javascript
/* @flow */

type T = HTMLElement & { foo?: bool };

export function a(e: T): void {
  e.foo = true;
}

export function b(e: T): bool {
  return e.foo == true;
}
```

However, you don't want to write the signature of `a` or `b` using the argument type `T` (why?). You want to write this instead:

```javascript
/* @flow */

import * as DOM from "flow/dom";

type HTMLElement = DOM.HTMLElement & { foo?: bool };

export function a(e: HTMLElement): void {
  e.foo = true;
}

export function b(e: HTMLElement): bool {
  return e.foo == true;
}
```

Note that each snippet of JavaScript here is a complete program, without external dependencies? It's much easier to see what is going on here. It is also easy to see *why* you are asking for something.

**Comment by samwgoldman** [comment]
Oh, lastly, I think there is a better way to solve your underlying issue, which is to store the handlers in a `WeakMap` instead of on the `EventListener`s themselves.

```javascript
const handlerCache = new WeakMap();
export const eventHandler = (handler:EventListener):Hook<EventTarget> => {
  // Canche hook per event handler to avoid creating one
  // on each render.
  if (handlerCache.has(handler)) {
    return handlerCache.get(handler);
  } else {
    const hook = new EventHandlerHook(handler);
    handlerCache.set(handler, hook);
    return hook;
  }
}
```

**Comment by Gozala** [comment]
@samwgoldman Your simplified examples definitely make a lot more sense and are clearer.

> Oh, lastly, I think there is a better way to solve your underlying issue, which is to store the handlers in a WeakMap instead of on the EventListeners themselves.

I have no illusion that code I provided is the best solution for the problem, but in a given circumstances such a nasty solutions may be required and I just hoped flow could accommodate them.

Thanks
