### ISSUE TITLE
flow does not seem to support exports.default

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#939]
following code
```js
import dictionary from "object-as-dictionary"

const nameOverrides/*:type.nameOverrides*/ = dictionary({
  className: 'class',
  htmlFor: 'for'
```

where `object-as-dictionary` is installed from https://github.com/Gozala/object-as-dictionary and is compiled by babel to a following output:

```js
/* @flow */

"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});

/*:: export type Dictionary <value> = {[key:string]: value}*/
/*:: export type $dictionary <value> = (data:?{[key:string]: value}) =>
  Dictionary<value>

;*/;;

var dictionary /*:$dictionary*/ = function dictionary(data) {
  var value = Object.create(null);

  if (data != null) {
    for (var _key in data) {
      if (data.hasOwnProperty(_key)) {
        value[_key] = data[_key];
      }
    }
  }

  return value;
};

exports.dictionary = dictionary;
exports["default"] = dictionary;
```

produces an error:

```sh
 8: const nameOverrides/*:type.nameOverrides*/ = dictionary({
                                                 ^ function call. Callable signature not found in
 8: const nameOverrides/*:type.nameOverrides*/ = dictionary({
                                                 ^^^^^^^^^^ exports
```

Presumably because `exports.default` is not supported by flow which makes it really difficult to use with babel compiled dependencies.

**Comment by samwgoldman** [comment]
This question is related to the dark corner that is ES6 module/CJS module interop. @jeffmo, can you weigh in on this?

I believe that @Gozala's issue can be boiled down to this:

foo.js:
```javascript
/* @flow */
exports.default = 0;
```

bar.js:
```javascript
/* @flow */
import x from "./foo";
(x : string);
```

actual output:
```
bar.js:3
  3: (x: string);
      ^ exports. This type is incompatible with
  3: (x: string);
         ^^^^^^ string
```

expected: something like "number is incompatible with string"

note that `(x.default : string)` gives the expected error.

**Comment by samwgoldman** [comment]
This is working as designed, but right now the semantics for mixing CommonJS and ES6 modules isn't standardized. We do what Babel does, but things might change up if/when Node supports ES6 modules.
