### ISSUE TITLE
Support additional export-from statement proposal

### ISSUE THREAD

**Issue by ludofischer** [facebook/flow#940]
`A.js`:

``` javascript
export default 5;
```

`B.js`:

``` javascript
export a from './A';
```

Unexpected identifier error:

```
src/B.js:2
  2: export a from './A';
            ^ Unexpected identifier
```

Flow 0.17

**Comment by samwgoldman** [comment]
Is this syntax valid ES2015? I'm not seeing a production in [the spec](http://www.ecma-international.org/ecma-262/6.0/#sec-exports) for this. The only production that has a *FromClause* doesn't appear to permit a simple identifier as the *ExportClause*.

Do you have existing code that uses this syntax? How is it compiled?

**Comment by samwgoldman** [comment]
OK, so this seems to be a ES2016 [proposed syntax](https://github.com/leebyron/ecmascript-more-export-from) from Facebook's own @leebyron. I don't think Flow has an established rule about what stage proposals we'll implement, but stage 1 seems a bit early to me. Looks like this one might hit stage 2 soon. I imagine this feature will have plenty of support internally to push it through :-)

**Comment by samwgoldman** [comment]
This is the same issue as #916. Linking the issues so we can close them all when a fix lands.

**Comment by GuillaumeLeclerc** [comment]
How is the state of that issue ?

**Comment by LucianoGraziani** [comment]
Still fails on v0.33.0

**Comment by abouthiroppy** [comment]
+1

**Comment by jyane** [comment]
:+1:

**Comment by renatorib** [comment]
+1

**Comment by xareelee** [comment]
+1

**Comment by sibelius** [comment]
the same still happens on 0.44

**Comment by rohmanhm** [comment]
@sibelius please take a look this comment https://github.com/facebook/flow/issues/916#issuecomment-179849998

**Comment by sibelius** [comment]
@rohmanhm  https://github.com/facebook/flow/issues/916#issuecomment-179849998 does not solve 

`export a from './A';`

**Comment by SFantasy** [comment]
the same on 0.53

**Comment by sonaye** [comment]
Anybody faces the issue where suppress comments don't work for this case?

**Comment by asolove** [comment]
What is the error you're seeing that suppress comments aren't preventing? Is the error getting attached to a different line in the source?

**Comment by sonaye** [comment]
@asolove The flow error related to `transform-export-extensions` not being fully supported yet, it's the same line.
<img width="266" alt="screen shot 2017-08-31 at 3 03 59 am" src="https://user-images.githubusercontent.com/23000873/29900237-2c94952a-8df9-11e7-89eb-cec708e981c1.png">
```
Error: src/configs/lib.js:42
 43: export axios from 'axios';
            ^^^^^ Unexpected identifier
```
and of course `suppress_comment=\\(.\\|\n\\)*\\flow-disable-next-line`.

**Comment by vkurchatkin** [comment]
You can't suppress parsing errors

**Comment by sonaye** [comment]
@vkurchatkin Got it, we wait till support for it lands then.

**Comment by Diokuz** [comment]
Same for `0.58.0`

**Comment by silvenon** [comment]
This is a completely acceptable workaround:

```js
export { default as a } from './a'
```

**Comment by sibelius** [comment]
can we add an option for this

https://github.com/facebook/flow/issues/916#issuecomment-310114962

much like

`esproposal.export_star_as=enabled` ?

**Comment by salisbury-espinosa** [comment]
Same for `0.68.0`

**Comment by SamChou19815** [comment]
Closing since this is non-standard syntax. We can reopen if the new proposal is adopted one day.
