### ISSUE TITLE
Singleton-typed object properties can be invalidated via aliasing

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#947]
Consider the following snippet, which works correctly:

``` javascript
/* @flow */
type T = { p: number }
var obj = { p: 0 };
var t: T = obj;
obj.p = ""; // expected error, string ~> number
```

Compare to following:

``` javascript
/* @flow */
type T = { p: "a" }
var obj = { p: "a" };
var t: T = obj;
obj.p = "b"; // no error, but inconsistent with t: T
```

**Comment by calebmer** [comment]
It looks like this has been fixed? https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoALgTwA4FMwAqYAvGAN5jYBcYARAIa1gC+qAbvQE5hwBGAViXKUaDJswDc7LmHQ0ipPvylKAdNiG1etCWGDAwAOzhhcnTnE4AaMLwCu6MAEtDAYziGAzk8-pchxwQndAALWXkgA
