### ISSUE TITLE
Interface declaration for ES6 class not working

### ISSUE THREAD

**Issue by rhasson** [facebook/flow#948]
When flow checking the following ES6 class:

```javascript
class CallRouter {
	constructor() {
		this.client = new twilio.RestClient(...);
		this.activeCalls = new Map();
	}
        makeCall() { ... }
}
```

I get the errors shown below:

```
libs/call_router.js:13
 13: 		this.client = new twilio.RestClient(config.twilio.production.account_sid, config.twilio.production.auth_token);
       ^^^^^^^^^^^ assignment of property `client`
 13: 		this.client = new twilio.RestClient(config.twilio.production.account_sid, config.twilio.production.auth_token);
            ^^^^^^ property `client`. Property not found in
 11: class CallRouter {
           ^^^^^^^^^^ CallRouter
```

I've created an interface definition for this class as follows: 

```javascript
declare class CallRouter {
	static client: Object;
	static activeCalls: Object;
}
```

But I'm still getting the error above.  Am I missing something?  Am I properly declaring the class interface?

Thanks,
Roy

**Comment by samwgoldman** [comment]
Hi Roy,

Interface definitions (`declare class ...`) are normally used to describe 3rd party libraries, like twilio's JavaScript library. For your own code, the idea is that you add type information inline.

The correct way to annotate a class is [shown in the documentation](http://flowtype.org/docs/classes.html). Note that each field (`x`, `y`) is annotated inside the class declaration itself. In your case, you want to provide annotations for `client` and `activeCalls`.

Does that help?

**Comment by GGAlanSmithee** [comment]
I hade the same missconception as you about `declarations`.  Maybe #833 can further explain why this doesn't work.

**Comment by rhasson** [comment]
@samwgoldman I read the documentation but annotating directly in the class declaration introduces an additional build step that I don't have today.  I prefer declaring the class in an interface file as I do with other things (modules, etc.) which makes it cleaner for me.

@GGAlanSmithee thanks for the clarification.  I'm trying to keep my annotations separate from the actual class declaration but that doesn't seem to be possible at this point in time I guess.

Thanks,
Roy

**Comment by rhasson** [comment]
This solved my problem.  Inline annotations without needing an extra build step to remove/comment out the annotations.

http://flowtype.org/blog/2015/02/20/Flow-Comments.html

**Comment by iam-peekay** [comment]
@samwgoldman I tried to annotate types for static properties within the class itself, but running into errors: 

(note, I'm using `any` type for now as I gradually add types to this codebase)
```javascript
class MyStore {
  static client: any;
  static errors: any;

  @observable data: Array<string> = [];
  @observable isFetching: boolean = false;
  @observable isLoaded: boolean = false;

  /* ... OTHER STUFF ...*/

  constructor(options: { client: any, errors: any }) {
    this.client = options.client;
    this.errors = options.errors;
  }
}
```

Flow throws an error saying:
```
src/stores/MyStore.js:38
 38:       const res = await this.client.get('/v2/accounts');
                                  ^^^^^^ property `client`. Property not found in
 23: class MyStore {
           ^^^^^^^^^^^^^ MyStore

src/stores/MyStore.js:44
 44:       this.errors.addApiError(e);
                ^^^^^^ property `errors`. Property not found in
 23: class MyStore {
           ^^^^^^^^^^^^^ MyStore

src/stores/MyStore.js:57
 57:     this.client = options.client;
         ^^^^^^^^^^^ assignment of property `client`
 57:     this.client = options.client;
              ^^^^^^ property `client`. Property not found in
 23: class MyStore {
           ^^^^^^^^^^^^^ MyStore

src/stores/MyStore.js:58
 58:     this.errors = options.errors;
         ^^^^^^^^^^^ assignment of property `errors`
 58:     this.errors = options.errors;
              ^^^^^^ property `errors`. Property not found in
 23: class MyStore {
           ^^^^^^^^^^^^^ MyStore
```

Also, my `.flowconfig` has static fields enabled:
```
esproposal.class_static_fields=enable
esproposal.class_instance_fields=enable
```

Any idea what I might be doing wrong?
