### ISSUE TITLE
T<x>|T<y> should be identical of T<x|y>

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#950]
So here is a shortest illustration that is still a realistic example I was able to come up with:

```js
/* @flow */

type Lazy <t> = {
  type: "Lazy",
  force: () => t
}

type Driver = {
  text: (text:string) => string|VirtualText
}

type Library = {
  text: (text:string) => string|VirtualText|Lazy<string>|Lazy<VirtualText>
}

type VirtualText = {
  type: "VirtualText",
  text: string
}

class LazyText {
  type: "Lazy";
  text: string;
  constructor(text) {
    this.text = text
    this.type = "Lazy"
  }
  force():string|VirtualText {
    if (driver == null) {
      throw Error("No driver")
    }

    return driver.text(this.text)
  }
}

let driver:?Driver = null

const lib:Library = {
  text: text =>
    driver == null ? new LazyText(text) :
    driver.text(text)
}
```

So the problem is `LazyText.prototype.force` will return either `string|VirtualText` because it depends on a driver that may return either one or the other. But that causes flow to error with:

```
rc/scratch.js:41
 41:     driver == null ? new LazyText(text) :
                              ^^^^^^^^ LazyText. This type is incompatible with
 13:   text: (text:string) => string|VirtualText|Lazy<string>|Lazy<VirtualText>
                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ union type


Found 1 error
```

As far as I understand because `LazyText` is understood as `Lazy<string|VirtualText>` which does not seem to satisfy union type of `Lazy<string>|Lazy<VirtualText>` which I find surprising.

Now if I modify type of `Library` to:

```js
type Library = {
  text: (text:string) => string|VirtualText|Lazy<string|VirtualText>
}
```

This code no longer fails, but then I run into different issue when defining larger union type reported as #949

**Comment by gabelevi** [comment]
Consider arrays. `Array<string | number>` could be an array of only strings, an array of only numbers, AND an array of both strings and numbers. However `Array<string> | Array<number>` can only be an array of only strings or an array of only numbers. So there is a difference between `
T<x>|T<y>` and `T<x|y>`.

Also `Lazy<string | VirtualText>` is neither a `Lazy<string>` (which would always return a `string` when you call `force()`) nor is it a `Lazy<VirtualText>` (which would always return a `VirtualText` when you call `force`).

**Comment by samwgoldman** [comment]
As Gabe pointed out, the premise of this issue doesn't hold.

**Comment by Gozala** [comment]
@gabelevi Thanks for the explanation, it does make sense to me now.
