### ISSUE TITLE
Proposal: initializable variables

### ISSUE THREAD

**Issue by jaredly** [facebook/flow#951]
A common pattern I use is that of an `initializable variable` -- a variable that starts as null, but is thereafter only ever set to be of type `T`. It's different from a `Maybe` type in that it will never be set to null after the initial declaration.

This would be useful in cases where `flow` has already checked that the value is not `null`, and can be confident that it will never again be `null`. Consider the following example:

```js
let proc = null;
if (somecondition) {
  proc = spawn('child');
  process.on('exit', () => proc.kill());
}
```

Currently, flow complains that `proc` might be null in the call to `proc.kill()`. I'd like a way to annotate the declaration of `proc` to say "once it's non-null, it will never again be". That way it can enforce that is never set to be `null` as well, and be confident in correctness.

Something like:
```js
let proc: !ChildProcess = null;
```

**Comment by samwgoldman** [comment]
In this example, why not declare `proc` inside the conditional branch?

**Comment by jaredly** [comment]
b/c I use `proc` elsewhere. forgive the trivial example

**Comment by samwgoldman** [comment]
But, then can't `proc` be null if `!somecondition`? I think it might help to get a fuller example.

**Comment by jaredly** [comment]
So a bit fuller:
```js
declare var spawn: (name: string) => child_process
function autoKillingMaybeSpawn(): ?child_process {
  let proc: ?child_process = null;
  if (checkIfWeNeedToSpawn()) {
    proc = spawn('child');
    // Set things up so we don't leave orphans around
    process.on('exit', () => proc.kill());
    //                       ^-- flow complains here, saying "proc might be null"
  }
  return proc;
}
```
Flow is taking a somewhat conservative view here, b/c there's some asynchronous stuff going on. In between the `proc = spawn('child')` and the `exit` event handler, `proc` might have been legally assigned to null again b/c it's type is `?child_process`. Therefore flow complains.

But I know will never assign `proc` to be null once initialized. I want a way to formally promise that, so that flow can be confidant that proc won't be null for the `proc.kill()` expression.

See also the last example [here on mutation analysis](http://flowtype.org/docs/dynamic-type-tests.html#caveats)


Now, in this example at least it's statically provable that proc will not be assigned to null, but there are plenty of cases where it's not reasonable to do that statically, but I as the user want the ability to promise that I wont (and have flow make me keep that promise).

**Comment by jeffmo** [comment]
So since the discussion on this issue, Flow has included support for checking latent initialization of variables. So to take the example in the OP, you can do this now:

```js
let proc: ChildProcess;
if (somecondition) {
  proc = spawn('child');
  process.on('exit', () => proc.kill());
}
```

Flow will trace that `proc` is not initialized -- until it has been initialized, at which point it will assume it's annotated type.
