### ISSUE TITLE
Mandatory parameters in libs declarations

### ISSUE THREAD

**Issue by danvk** [facebook/flow#956]
It would be helpful to have a way to express, in a `[libs]` file, that a function parameter is mandatory. For example:

``` javascript
declare function isEqual(a: any, b: any): boolean;
```

can be called as any of these, without error:

``` javascript
_.isEqual();
_.isEqual(1);
_.isEqual(1, 2);
_.isEqual(1, 2, 3);
```

The zero- and one-parameter version type checks because the unspecified parameters are set to `undefined`, which matches `any`. The three-parameter version type checks because the third parameter is ignored.

While these do gibe with JavaScript runtime behvaior, it would be nice if there were a way for the author of the library declarations file to enforce stricter checks, e.g. that the parameters are not `undefined`.

See discussion at https://github.com/splodingsocks/FlowTyped/pull/1#issuecomment-149357004

**Comment by danvk** [comment]
Copying this over from the FlowTyped PR...

FWIW, TypeScript & the DefinitelyTyped underscore declarations flag an incorrect number of arguments as an error. This is currently impossible with Flow.

One arg:
```javsacript
/// <reference path="typings/tsd.d.ts" />
_.isEqual(1);
```
```
$ tsc foo.ts
foo.ts(3,1): error TS2346: Supplied parameters do not match any signature of call target.
```

Two args:
```javsacript
/// <reference path="typings/tsd.d.ts" />
_.isEqual(1, 1);
```
```
$ tsc foo.ts
```

Three args:
```
/// <reference path="typings/tsd.d.ts" />
_.isEqual(1, 1, 1);
```
```
tsc foo.ts
foo.ts(2,1): error TS2346: Supplied parameters do not match any signature of call target.
```

**Comment by calebmer** [comment]
Function arity is now enforced 👍
