### ISSUE TITLE
Flow errors if matching type union if primitives aren't handled first

### ISSUE THREAD

**Issue by Gozala** [facebook/flow#957]
Here is an example

```js
/* @flow */

export type Node
  = string
  | {type: "Node", render: () => string}

export const render = (node:Node):string => {
  if (node.type === "Node") {
    return node.render()
  }

  if (typeof(node) === "string") {
    return String(node)
  }

  throw TypeError("Unsupported node argument was passed")
}
```

That fails with a following error:

```
src/scratch.js:9
  9:     return node.render()
                ^^^^^^^^^^^^^ call of method `render`
  9:     return node.render()
                     ^^^^^^ property `render`. Property not found in
  9:     return node.render()
                ^^^^ String
```

Please also note that error messages does not really clarify the issue, well after knowing what the issue is it seems not too bad, but for quite some time I had no idea what was going on. Also in larger code it's much worth as actual type union had much more options and errors were reported on each one.

Switching condition order seems to resolve the issue:

```js
/* @flow */

export type Node
  = string
  | {type: "Node", render: () => string}

export const render = (node:Node):string => {
  if (typeof(node) === "string") {
    return String(node)
  }

  if (node.type === "Node") {
    return node.render()
  }

  throw TypeError("Unsupported node argument was passed")
}
```

My guess is flow assumes that `String.prototype.type` maybe set to "Node" and there for I see this issue, but I am questioning if it is a good idea to optimize for such rare use case ? If users needs to deal with a code that modifies `String.prototype` would not it make more sense for a user to explicitly handle that via different type like `type myString = string & {type: string}` or am I missing something here ?

**Comment by samwgoldman** [comment]
Not sure why we didn't give you this error before, but this is what Flow currently shows for your first example:

```
test.js:8
  8:   if (node.type === "Node") {
                ^^^^ property `type`. Property not found in
  4:   = string
         ^^^^^^ String

test.js:9
  9:     return node.render()
                     ^^^^^^ property `render`. Property not found in
  9:     return node.render()
                ^^^^ String
```

The code on line 8 tries to access `node.type`, but we still think `node` might be a `string`. That's why switching the type tests solves the issue.
