### ISSUE TITLE
Unsound disjoint union refinement caused by prop aliasing

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#958]
``` javascript
/* @flow */

type T
  = { t: "a", a: number }
  | { t: "b", b: string };

var a = { t: "a", a: 0 };
var b: T = a;
a.t = "uh oh";

// why "uh oh"?
if (b.t === "a") {
} else {
  // bad deduction, assuming this can cause runtime errors
  (b.b : string);
}
```

**Comment by bhosmer** [comment]
@samwgoldman thanks Sam - @avikchaudhuri check it out - type compat on tagged unions has to be nominal if the RHS might be aliased.

**Comment by TrySound** [comment]
@samwgoldman Currently this assignment is forbidden `a.t = "uh oh";`. Can this be considered as fixed?
https://flow.org/try/#0PQKgBAAgZgNg9gdzCYAoVAXAngBwKZgAqqYYAvGAN5gYBcYARAIYMA0YT9AdgK4C2AIzwAnMAF8SYAD5Ua9BgLZgB9AM4ZhASy4BzcQG50ANyaim5WXUYt2nMAAYDqE6JVELTQ0wB0GCwx4ACzA4QIZDVGBgMARArEYgkLCAflRNKDAACgFfcjIKZgYASipUMTA8GFUCSkko5SYAEzBGvEaeAGMMTTguW1VVfm09DEDNVTAOpi5Jph5qsGEeLm6+AhFhOGFVSWzvATA1DWGiwzEgA

**Comment by samwgoldman** [comment]
Yeah, we can close this. The fix for this was to "write back" the annotation to the literal (e.g., [1]) but note that this isn't a great fix. There's a larger issue here which should be tracked separately. Currently working on getting that issue documented properly and will open a new issue to track it.

1. Example:
```
var a = { p: "foo" };
var b: { p: string | number } = a; // "foo" < `string | number`, then write back `string|number| to a.p
(a.p: string); // number < string error
```
