### ISSUE TITLE
Automatic type creation on module boundaries 

### ISSUE THREAD

**Issue by TiddoLangerak** [facebook/flow#959]
Flow can infer a lot of type information automatically, but unfortunately that isn't shared across module boundaries, which I do understand. However, it would be great if there is some way to assign automatically inferred types to a type name, which currently isn't possible AFAIK. For example, consider the following snippet:

``` javascript
function objectFactory() {
    return {
        myProperty : 3
    };
}

console.log(objectFactory().myProperty * 3);
```

This snippet checks fine. However, consider the following variation on the snippet:

``` javascript
export function objectFactory() {
    return {
        myProperty : 3
    };
}
```

This now gives the error:

```
  2: export function objectFactory () {
                                     ^ return. Missing annotation
```

As far as I know the only way to work around this is by defining the return type of the factory explicitely, i.e.:

``` javascript
type MyType = {
    myProperty : number
};

export function objectFactory() : MyType { /* etc */ }
```

Certain styles of Javascript programming make use of factory functions like these extensively. In such code bases having to create explicit types for all these functions result in a lot of boilerplate. It would therefore be great if there was some way to automatically assign a name to the inferred type, e.g. something like this:

``` javascript
export function objectFactory() : =MyType { /* etc */ };
```

This would eliminate all of the boilerplate. 

Would such a thing be possible? Or are there practical reasons why this can't be done?

**Comment by vkurchatkin** [comment]
This is fixed, closing
