### ISSUE TITLE
Include jsdoc comments in completion entry

### ISSUE THREAD

**Issue by fdecampredon** [facebook/flow#96]
Autocomplete return a something like that : 

``` typescript
type CompletionEntry = {
  name: string;
  type: string;
  func_details: ?{
    return_type: string;
    params: { name: string; type: string }[]
  };
  path: string;
  line: number;
  endline: number;
  start: number;
  end: number;
}
```

however it would be helpful for IDE integration to get the JSDoc comment (even as a simple text).

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by nmn** [comment]
This feels like a feature that could be implemented in IDE plugins instead of Flow.

**Comment by vkurchatkin** [comment]
@nmn not really, if autocomplete is provided by Flow

**Comment by nmn** [comment]
@vkurchatkin Oh, I think I misunderstood the problem.

**Comment by mroch** [comment]
@vrama628 added this in https://github.com/facebook/flow/commit/a478128e41205a479e5c8ddbfaf1e920b856f0b2 and similar commits
