### ISSUE TITLE
Track type of `this` in callbacks

### ISSUE THREAD

**Issue by danvk** [facebook/flow#968]
There's an error (marked with `<---`) in this snippet which Flow could potentially catch:

```javascript
class RemoteFile {
  url: string;
...
  promiseXHR(xhr: XMLHttpRequest): Q.Promise<[any, Event]> {
    var url = this.url;
    var deferred = Q.defer();
    xhr.addEventListener('load', function(e) {
      if (this.status >= 400) {
        deferred.reject(this.status + ' ' + this.statusText);
      } else {
        deferred.resolve([this.response, e]);
      }
    });
    xhr.addEventListener('error', function(e) {
      deferred.reject(`Request for ${this.url} failed: ${this.status}`);  // <---
    });
    this.numNetworkRequests++;
    xhr.send();
    return deferred.promise;
  }
}
```

The problem is that `this` inside the `addEventListener` callback refers to the `XMLHttpRequest` object (I believe) and not the `RemoteFile` class. The latter has a `url` property but not a `status` property, whereas the former has `status` but not `url`. Clearly this code isn't right!

Flow doesn't complain, though. It thinks `this` has type `any` in the event listener.

Where possible, the DOM declarations should indicate the type of `this` in callbacks to prevent this sort of mistake.

For example, Google's Closure Compiler provides an [`@this`][1] annotation. You can see an example of this in action in the declaration for [`Array.prototype.find`][2].

[1]: https://developers.google.com/closure/compiler/docs/js-for-compiler#tag-this
[2]: https://github.com/google/closure-compiler/blob/816bcb75ca2d8c8e32dbb76f2164ad85cee5c1fb/externs/es6.js#L1096-L1104

**Comment by samwgoldman** [comment]
Ref #452

**Comment by danvk** [comment]
Closing as a dupe
