### ISSUE TITLE
Class exported via module.exports cannot be imported by name

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#969]
Suppose you have a very simple file such as
```
/* foo.js    @flow */
export type FooProps = { x: number; y: number; };

class Foo {
  constructor(props: FooProps) {
    // do something...
  }
};
module.exports = Foo;
```

If you want to import `Foo` and `FooProps` from another file, you need to say
```
import type * as Foo from "./foo.js";
import type {FooProps} from "./foo.js";
```
whereas a more obvious syntax
```
import type {Foo, FooProps} from "./foo.js";
```
doesn't work. I can't believe this was consciously designed to work that way, so probably a bug.

**Comment by kkirby** [comment]
Try this: `import type Foo, {FooProps} from "./foo.js";`

`import * as Foo` is generally the same as `import Foo`, the former being that the values are imported into the current scope. So any modifications on `Foo` itself won't propagate to the module. At least that is what I think the difference is.

**Comment by pasha-mf** [comment]
Thank you, this syntax worked!
I guess this issue can be closed now ;)

**Comment by samwgoldman** [comment]
@pasha-mf FWIW, you can also close your own issues. :)
