### ISSUE TITLE
null typecheck refinement doesn't work on object destructuring

### ISSUE THREAD

**Issue by kkirby** [facebook/flow#975]
If you do a null check on a property, and then destructure that property and use it, Flow will error saying that you cannot do an operation on a possibly undefined value.

```javascript
/*  1 */ // @flow
/*  2 */ type foo = {
/*  3 */         x?: number,
/*  4 */         y?: number
/*  5 */ };
/*  6 */ 
/*  7 */ function doesntWork(a:foo){
/*  8 */     if(a.x){
/*  9 */         let {x,...others} = a;
/* 10 */         let calc = x * 12;
/* 11 */     }
/* 12 */ }
/* 13 */  
/* 14 */ function works(a:foo){
/* 15 */     if(a.x){
/* 16 */         let x = a.x;
/* 17 */         let calc = x * 12;
/* 18 */     }
/* 19 */ }
/* 20 */  
/* 21 */ doesntWork({x:1});
/* 22 */ works({x:1});
```

Output:
```
test.js:10
 10: 		let calc = x * 12;
     		           ^ undefined. This type is incompatible with
 10: 		let calc = x * 12;
     		           ^^^^^^ number
```

**Comment by samwgoldman** [comment]
The `a.x` expression in your `works` example hits [this code path](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L3198) which searches for refinements.

The `{x} = a` assignment goes through a [different code path](https://github.com/facebook/flow/blob/master/src/typing/type_inference_js.ml#L355), which doesn't have the refinement logic.

It should be possible to make this work.
