### ISSUE TITLE
Array.sort method doesn't take a comparator

### ISSUE THREAD

**Issue by johnislarry** [facebook/flow#976]
Repro -- The following gives a flow error:

`[1,2,3,4,5].sort((a, b) => a < b);`

and it should return [5,4,3,2,1].  It doesn't seem possible to use a comparator with the sort method here.

**Comment by samwgoldman** [comment]
You didn't include it here, but this is the error I get:

```javascript
pro:flow-test sam$ flow check
test.js:3
  3: [1,2,3,4,5].sort((a, b) => a < b);
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ call of method `sort`
  3: [1,2,3,4,5].sort((a, b) => a < b);
                                ^^^^^ boolean. This type is incompatible with
number. See: [LIB] core.js:153
```

Flow is telling you that your function returns a boolean, but the comparator expects a numeric return type. [Documentation for `sort`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/sort) backs Flow up here.

I don't think this is a bug in Flow, but rather a bug in your program that Flow has correctly detected. Did you mean `a - b`?

**Comment by johnislarry** [comment]
You are 100% right, thank you!
