### ISSUE TITLE
Type annotations are not allowed in untyped mode?!

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#978]
I just upgraded to the new version of Flow 0.18, and it made me very happy. Apparently the new version breaks Flow's initial promise, citing from flowtype.org:

> Flow's type checking is **opt-in**: files are not type checked unless you ask it to. This means that you can gradually convert your JavaScript codebase to Flow while reaping incremental benefits. When you do opt-in a file, Flow tries to type check the code automatically by performing type inference, reporting errors without further manual guidance....

This is no longer true. I have files in my codebase that I did not ask to typecheck, yet Flow goes inside anyways, finds something it doesn't like, and reports an error:
```
21:   static inflate(data): Story {
                           ^ Type annotations are not allowed in untyped mode
```
Normally if I have Flow errors that I don't have time to fix, I'd remove `@flow` from file's header turning type-checking off; or put `// $FlowFixMe` before the offending line (if it's just 1 error). Neither of these methods work now.

Adding insult to injury, all other perfectly valid files will now say something like 
```
 10: var Story = require("./Story.js");
                 ^^^^^^^^^^^^^^^^^^^^^ Story.js. Required module not found
```

Not sure what to do... Any suggestions? Any way to turn off the "Type annotations in untyped mode" check?

**Comment by mroch** [comment]
are you actually on 0.18, or on master?

In 0.18, types should always be enabled: https://github.com/facebook/flow/blob/e70c6cf71667655789074a66ba0e66f3c39e8646/src/parsing/parsing_service_js.ml#L47

the diff that does what you're running into (https://github.com/facebook/flow/commit/e87b8556d6789b6022a0bb1020d4df2bfd0ccec4) landed after 0.18. I'm in the process of adding a `@noflow` option that allows types but doesn't check them, which will definitely land before 0.19.

sorry for the breakage though.

**Comment by pasha-mf** [comment]
Thank you, this helped. I checked out right up to the commit you mentioned (`d3f6f17`), and the problem has gone.

**Comment by hishnash** [comment]
Im on version 0.20.0 and im getting this:
```
node_modules/babel-types/lib/definitions/index.js:43
 43: function assertEach(callback /*: Function*/) /*: Function*/ {
                                  ^^^ Type annotations are not allowed in untyped mode
```

**Comment by mroch** [comment]
@hishnash there's a similar report in #1180 so let's discuss there
