### ISSUE TITLE
Overload function call operator?

### ISSUE THREAD

**Issue by zsszatmari** [facebook/flow#979]
Hi!

I'd like to use https://www.npmjs.com/package/observable. It can be either invoked with a callback, and then it returns with a function that can be later used to unsubscribe, or it can be invoked with no arguments, in that case it returns the current value.

I am trying the model things above like this:

```javascript
type Observable<X> = ((callback : (value : X)=>void) => ()=>void) | 
					 (() => X);
```

But it does not seem to work for the second form, it seems to use only the first one.
Am I missing something?
Thank You!

**Comment by samwgoldman** [comment]
Overloads are correctly represented as [intersection types](http://flowtype.org/docs/union-intersection-types.html#intersection-example), not union types.

If you are trying to write declarations for an external library, you can also use the `declare function` statement multiple times, and Flow will collapse them into a single intersection type automatically.

**Comment by zsszatmari** [comment]
Sounds logical. And really, I tested and works flawlessly. Thanks! Extra kudos for the swift reply.
