### ISSUE TITLE
Object literal with spread property does not correctly overwrite properties

### ISSUE THREAD

**Issue by samwgoldman** [facebook/flow#981]
``` javascript
var o1 = { foo: 0 };
var o2 = { ...o1, foo: "" };
var foo = o2.foo;
```

`foo` is `number | string`, instead of `string`.

**Comment by samwgoldman** [comment]
Hunting/blaming around the source makes me think @mroch might have some upcoming changes/wip here?

**Comment by chenglou** [comment]
Any news on this?

**Comment by adimit** [comment]
See also: #6108, #6800, and probably many more; the problem has been cropping up quite a bit and cause erroneous typing rejections when the object types aren't inferred.

**Comment by villesau** [comment]
@samwgoldman made a PR that fixes this: https://github.com/facebook/flow/pull/7298

**Comment by nmote** [comment]
This has the expected behavior on master
