### ISSUE TITLE
Handle assertions

### ISSUE THREAD

**Issue by zsszatmari** [facebook/flow#989]
Hi!

  I don't know if this would be possible at all, but it would nice if assertions would be handled. For example:

```javascript
const assert = require('assert');

const messageElement = createDiv.querySelector('textarea');
assert(messageElement instanceof HTMLTextAreaElement);
const message = messageElement.value;
```

**Comment by samwgoldman** [comment]
In fact, something very much like this is already supported. Facebook uses an `invariant` function, which is part of [fbjs](https://github.com/facebook/fbjs/blob/master/src/__forks__/invariant.js), but you can also use a [NPM package](https://www.npmjs.com/package/invariant), which someone helpfully extracted from React.

Let me know if that works for you.

**Comment by zsszatmari** [comment]
The invariant package from npmjs does the trick, thanks for pointing out!
