### ISSUE TITLE
Add configuration for shared mem size

### ISSUE THREAD

**Issue by patryk0605** [facebook/flow#99]
Hi all,

I am trying to do one of the examples and keep receiving the following error: 

/flow/examples/01_HelloWorld # flow check
Error initializing: Cannot allocate memory

Any ideas what might the issue might be? I am running this on: 

SUSE Linux Enterprise Server 11 (x86_64)
VERSION = 11
PATCHLEVEL = 3

Thanks in advance for the support!

**Comment by quark-zju** [comment]
I have the same issue. strace shows flow tries to allocate 23GB memory:

```
mmap(0x500000000000, 23756541952, PROT_READ|PROT_WRITE, MAP_SHARED|MAP_FIXED|MAP_ANONYMOUS|MAP_NORESERVE, 0, 0) = -1 ENOMEM (Cannot allocate memory)
```

**Comment by bradencanderson** [comment]
Someone just ran into this problem at my work. We have a flow server running as part of our build process, and for some reason `/tmp/flow` was filled up with 5 gigs of stuff, maxing out the drive and causing an ENOSPC error.

Unfortunately I have no more details -- someone killed the flow processes and cleared out the directory before I could get to it.

**Comment by facebook-github-bot-2** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by raould** [comment]
Ubuntu 14.04 x86 / 3.8 GiB RAM / core 2 duo / 5.6 G disk available.
I cloned from git & ran make & then ran the tests and the mostly all failed. A lot had this "Cannot allocate memory" message.

**Comment by fiatjaf** [comment]
I have the same problem here, 50MB free RAM. If this is too little, perhaps there should be a warning somewhere about how much RAM this thing consumes.

**Comment by samwgoldman** [comment]
Right now we allocate a bunch of memory up front for the server, which is great for us internally where we have beefy machines and want super fast type feedback.

Making this configurable isn't a high priority for us internally, but community contributions to add a config option are very welcome.

**Comment by dsilva** [comment]
I also ran into this and worked around it with "ulimit -v unlimited", but it was surprising to learn from this ticket that Flow crashed because Hack (?) mmaps a couple dozen gigabytes of memory for its own heap.

**Comment by mroch** [comment]
@gabelevi fixed?

**Comment by arypurnomoz** [comment]
is there anyway to specify how much memory should flow use?

**Comment by nmn** [comment]
Pretty sure this is fixed now. Will close soon unless someone here chimes in.

**Comment by ysangkok** [comment]
How is it fixed ? I don't see any command line options mentioned in the readme .

**Comment by nmn** [comment]
@ysangkok The Flow docs are slightly outdated. Please try looking at the output from `flow --help`.

Also, I was talking about the `Error initializing: Cannot allocate memory` thing being fixed now.

**Comment by vicapow** [comment]
I believe this been fixed a while ago but please re-open if not.
