### ISSUE TITLE
Flow fails to typecheck legal code with Maps

### ISSUE THREAD

**Issue by johnislarry** [facebook/flow#990]
# Repro

flow init in an empty directory, add this code to test.js, run flow check.

```
/* @flow */

const x: {[key: string]: number} = new Map([['k', 1]]);
x.get('k');
```
```
$ flow version
Flow, a static type checker for JavaScript, version 0.18.1
$ flow check
test.js:4
  4: x.get('k');
     ^^^^^^^^^^ call of method `get`. Function cannot be called on
  3: const x: {[key: string]: number} = new Map([['k', 1]]);
                              ^^^^^^ number


Found 1 error
```

But to my knowledge this should typecheck

**Comment by samwgoldman** [comment]
So, the `{ [key: string]: number }` syntax is for [objects as maps](http://flowtype.org/docs/objects.html#objects-as-maps), but here you're using a `Map` as a map, so you would type that using the `Map` class type, i.e., `const x: Map<string,number> = new Map()`.

**Comment by johnislarry** [comment]
Ah, I see.  Thanks for clearing that up!
