### ISSUE TITLE
Function matches a $Shape

### ISSUE THREAD

**Issue by pasha-mf** [facebook/flow#993]
I was type-annotating a library `find` function, and was surprised to find that Flow allows a function to be used in place of a `$Shape`:

```
declare function find<T: Object>(source: Array<T>, target: $Shape<T>);
find([{foo: 1}], (e) => e.bar > 3); // This should have been an error
```

A more simplified version is this:

```
declare function test(x: {foo?: number});
test(() => 1);
```

Basically whenever you declare an object whose keys are all optional, then any function will match that object. That doesn't sound right...

**Comment by TiddoLangerak** [comment]
I think it accepts this because a function is also an object. Therefore a function is actually a valid instance of an type without any required keys. So I do think this is correct behaviour, it's just a bit unexpected.

**Comment by samwgoldman** [comment]
I agree with @TiddoLangerak's assessment. I don't see how this program can "go wrong" with the current typing rules.

**Comment by pasha-mf** [comment]
Ok, here's another example, perhaps this time closer to home:
A simple React component with no props and with a single "state" variable `this.state.foo`. I am testing a `setState()` method, and the first invocation is correctly identified as an error: neither `state.bar` nor `state.baz` are valid variables. The second invocation of `setState`, which does exactly the same thing as the first one only in a deferred manner, goes unnoticed by Flow typechecker. The reason for this is  that instead of matching call signature of `(state: TestState) => TestState`, it matches a call signature of `(state: any) => any` because any function can match `$Shape<TestState>`.

```
// @flow
type TestState = {foo: number};
class Test extends ReactComponent {
  static defaultProps: {};
  props: {};
  state: TestState;

  test() {
    this.setState({bar: this.state.baz > 3}); // This is flagged as Flow error
    this.setState((state) => { // This isn't
      return {bar: state.baz > 3};
    });
  }
}
```

Of course, in Javascript functions are objects. But they are also not, in the sense of their `typeof(...)` is `"function"`, not an `"object"`, and it is very common to write polymorphic methods that take either an object or a function as an argument. With your current architecture these methods cannot be effectively type-checked, which seems like a huge type-checking gap for any application.

**Comment by samwgoldman** [comment]
That example seems like a bug in the React type definitions.

**Comment by pasha-mf** [comment]
Ok, just checked the definitions in `[LIB] react.js` -- they aren't perfect. But even if I try to write my own definition, it still fails to produce Flow error in the example above
```
// @flow
type TestState = {foo: number};
class Test extends ReactComponent {
  static defaultProps: {};
  props: {};
  state: TestState;

  _setState(update: ((currentState: TestState) => $Shape<TestState>) | $Shape<TestState>,
            callback?: () => void) {
    super.setState(update, callback);
  }

  test() {
    // $ExpectFlowError
    this._setState((state) => {
      return {bar: state.baz > 3};
    });
  }

};
```

**Comment by samwgoldman** [comment]
All right, cool. Getting somewhere now. What's happening here:

* At the `_setState` call site, Flow first checks the argument against the LHS of the union in the parameter type, but it fails due to the dependent flow that looks up `baz

**Comment by calebmer** [comment]
This will be fixed in an upcoming version of Flow 👍
