### ISSUE TITLE
Constructor cannot be called on CommonJS exports of ....

### ISSUE THREAD

**Issue by johnislarry** [facebook/flow#996]
## Repro

Make two files: `test.js`

```
/* @flow */

export default class Test {
  constructor() {}
}
```

and `main.js`

```
/* @flow */

const Test = require('./test');
const x = new Test();
```

and in `main.js` there's an error

```
$ flow check
main.js:4
  4: const x = new Test();
               ^^^^^^^^^^ constructor call. Constructor cannot be called on
  4: const x = new Test();
                   ^^^^ CommonJS exports of "/Users/jonaldislarry/test/test.js"


Found 1 error
```

But this code works and this error is confusing.  Is the error legitimate?

**Comment by mroch** [comment]
looks like you need to do `const Test = require('./test').default;`

see https://github.com/facebook/flow/blob/9345927d449493530ddc8a4c24cdb07ec35ad9c3/tests/es6modules/es6modules.js#L197

@jeffmo what adds the `default` export in the es6 compatibility? is that a babelism, or is there a spec for that?

**Comment by mroch** [comment]
if you're using ES6 `export`, maybe you can also use ES6 `import` instead of commonjs's `require`, which would make this [nicer](https://github.com/facebook/flow/blob/9345927d449493530ddc8a4c24cdb07ec35ad9c3/tests/es6modules/es6modules.js#L117).

**Comment by mroch** [comment]
... babel [exports the class itself](http://babeljs.io/repl/#?experimental=true&evaluate=true&loose=false&spec=true&code=export%20default%20class%20Test%20%7B%0A%20%20constructor()%20%7B%7D%0A%7D) so I agree this seems like a bug unless there's something I'm missing about es6/commonjs interop.

**Comment by samwgoldman** [comment]
Flow should follow whatever Babel does. I believe that is the intention of the existing code, but if not, I think it should be.

**Comment by johnislarry** [comment]
Yeah, this was transpiled with babel before running

**Comment by alexeyraspopov** [comment]
Any updates on this?

**Comment by hmeerlo** [comment]
I get the exact same error with immutable.js using the class produced by a Record() call. Any update?

**Comment by vkurchatkin** [comment]
This seems to be the expected behaviour.

**Comment by samwgoldman** [comment]
Is there a special case when CJS importing a ES module that only has a default export? ( no named exports). If so this should be pretty easy to fix.

**Comment by vkurchatkin** [comment]
@samwgoldman IIRC there was (in Babel), but not anymore

**Comment by calebmer** [comment]
This is the correct behavior 👍
