### ISSUE TITLE
Default function binding

### ISSUE THREAD

**Issue by mhagmajer** [facebook/flow#997]
Is there a way to let flow know that given function is bound to an object with specific properties and methods? Please see [`Meteor.publish`](http://docs.meteor.com/#/full/meteor_publish) as an example. This function is bound to a context that has methods such us `this.added`, `this.changed` and others.

This is what I'm doing right know as an work-around:

``` javascript
  // .interfaces/meteor.js
  declare function publish(name: string, func: Function): void;
  declare class PublishContext<T: Object> {
    userId: ?string;
    added(collection: string, id: string, fields: $Shape<T>): void;
    //...
  }
```

``` javascript
  // server/publish.jsx
  Meteor.publish(name, function(operationId: string, ...args) {
    (function() {
      this.added('coll', id, {a: 1});
    }).call((this: Meteor.PublishContext));
  });
```

**Comment by samwgoldman** [comment]
Ref #452
