### ISSUE TITLE
Move emacs plugin to a dedicated repository

### ISSUE THREAD

**Issue by dgellow** [facebook/flow#999]
Could you create an official repository for flow-types.el? Similar to the [facebook/vim-flow](https://github.com/facebook/vim-flow) plugin.
I think it would improve visibility and make it easier to work on it together.

**Comment by FossiFoo** [comment]
this, please. i would contribute by making a proper mode and adding my company-flowtype auto-complete. having this in the root dir of flow makes it hard to properly submit PRs.

**Comment by samwgoldman** [comment]
OK cool. If that's holding you back from contributing, let's do it.

**Comment by FossiFoo** [comment]
nice :)

**Comment by FossiFoo** [comment]
any progress? is there anybody i can bug with this?

**Comment by avikchaudhuri** [comment]
I can take this up

**Comment by dgellow** [comment]
@avikchaudhuri @samwgoldman So is there something in progress related to this issue?

**Comment by avikchaudhuri** [comment]
Yeah, expect something to materialize later this week.

**Comment by dgellow** [comment]
@avikchaudhuri ping?

**Comment by FossiFoo** [comment]
bump

**Comment by dgellow** [comment]
The emacs package has been moved to https://github.com/flowtype/flow-for-emacs/. I close the issue.
See https://github.com/facebook/flow/pull/2731 for details.
